### ISSUE TITLE
example image

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#1]
![image](https://f.cloud.github.com/assets/2662304/664777/3dad6c32-d78d-11e2-9ecf-b921afebfb0b.png)

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/10440038/b40bcb6c-7146-11e5-93ac-db2e177e39f8.png)

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/11323720/0ea2a5f4-9123-11e5-9c30-d57072b8e12c.png)

![image](https://cloud.githubusercontent.com/assets/2662304/11323728/3cb6e810-9123-11e5-97b3-662fd6f35725.png)

**Comment by ktsaou** [comment]
![animation2](https://cloud.githubusercontent.com/assets/2662304/12218264/04b64296-b723-11e5-93b7-91be7abbfed9.gif)

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/12373555/abd56f04-bc85-11e5-9fa1-10aa3a4b648b.png)

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/12373713/f9d0260e-bc8a-11e5-9c60-cc77ad4e5c4b.png)

**Comment by ktsaou** [comment]
![animation5](https://cloud.githubusercontent.com/assets/2662304/12373715/0da509d8-bc8b-11e5-85cf-39d5234bf976.gif)

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/12377654/9f566e88-bd2d-11e5-855a-e0ba96b8fd98.png)

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/12377813/f8a6e1c0-bd32-11e5-815c-080d688ba32e.png)

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/12530273/421c4d14-c1e2-11e5-9fb6-ca6d6dd3b1dd.png)

![image](https://cloud.githubusercontent.com/assets/2662304/12530376/29ec26de-c1e6-11e5-9af1-e48aaf781795.png)

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/12765473/879b8e04-ca07-11e5-817d-b0651996c42b.png)

**Comment by ktsaou** [comment]
![image](https://cloud.githubusercontent.com/assets/2662304/12766538/12b272fa-ca0d-11e5-81e1-6a9f8ff488ff.png)

**Comment by ishmaelen** [comment]
Would it be possible to include these dashboards as examples in the git package or somehow make them available?

**Comment by ktsaou** [comment]
Hi, what do you believe is their use?

**Comment by ishmaelen** [comment]
Easier to understand examples than the huge complex example provided today. I am but a telco-operations engineer and know next to nothing about web/html. Their use would simply be for people like me to easier get an introducton with examples to netdata.

**Comment by ishmaelen** [comment]
If you do not wish to include more examples to package; please consider sending me a couple on the side to monkeilas <at> gmail - thanks!

**Comment by ktsaou** [comment]
The first few of these images are from an old version of netdata.
The others are used by the wiki.
I still don't understand why you need them. You can download them from this page, but what would be the use of them?

**Comment by ishmaelen** [comment]
Hello,

The usage for me is that they are examples that contain less code than the big huge one and of such could be of great usage to understand how to create my own. I do not understand how HTML works and of such its troublesome to create good looking pages.

Example:
[side by side](https://camo.githubusercontent.com/8905ffd303177236fbf5a25ef26a81d9a28d38ce/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323636323330342f3638393937392f38303764666234652d646163362d313165322d383534362d3664383366646230353836362e706e67)

**Comment by ktsaou** [comment]
I see.

You can view the old dashboard. It is accessed on your netdata using the `/old/` url.
It is a lot slower though (google charts) and the old API that supports it will be deleted in time.

You can also check the `/demo.html` and `/demo2.html` on your netdata server. You can view source on these to get the idea of the new dashboard (`/demo.html` is the simplest and you can add as many charts are you like).

Last, you can check the `/dashboard.html` page, which I use for performance testing javascript chart libraries. In this you will find all the chart libraries currently supported by netdata.

You need to know some basic HTML though.

Costa
