### ISSUE TITLE
SAML authentication

### ISSUE THREAD

**Issue by juanvasquezreyes** [netdata/netdata#10010]
Will be nice to integrate it with some saml or auth authentication when going to the UI to secure when going to the dashboard

maybe something like this at the netadata.conf file
[web]
  saml enabled = yes
  saml Metadata URL = x.x.x.x
  saml Entity ID =
  saml NameID Format = ss

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
