### ISSUE TITLE
Netdata has no metrics on apps.sockets.

### ISSUE THREAD

**Issue by RicardoJSTeixeira** [netdata/netdata#10018]
Hi
Netdata has no metrics on apps.sockets.

I have more than 30 servers running netada, all fully funtional with the same configs.
I reinstalled netdata and nothing changed.
Netdata error logs doesn't say anything about apps.sockets, or that something is broke.

How can I debug this issue?

Thanks for your atention.

##### Question summary
no metrics on apps.sockets.

##### OS / Environment
Centos 7

##### Component Name
apps.sockets

##### Expected results
Metrics on apps.sockets

**Comment by thiagoftsm** [comment]
Hello @RicardoJSTeixeira ,

I tested now on my machine and I can see without any problems the sockets, so I have few questions for you:

1 - Did you upgrade for the latest Netdata version(`1.25.0`)?
2 - Did you compile Netdata? Or did you use kickstart to upgrade?
3 - Which memory mode are you using with these Netdata agents?
4 - I already had problems with CentOS and SELinux that affects `ebpf.plugin`. I believe that `apps.plugin` also could have problems to read `/proc` depending of how it was configured. Can you see any reference to `apps.plugin` inside your audit.logs?
5 - Do you have any information related to `apps.plugin` inside your `error.log`?

I hope with your answers we will be able to fix this problem.

Best regards!
