### ISSUE TITLE
Detect installation method & inform users

### ISSUE THREAD

**Issue by OdysLam** [netdata/netdata#10017]
##### Feature idea summary

A common user pattern is to install netdata using the native package managers of their Linux distributions, like APT and RPM. The problem is that we don't have any control over the packages that are maintained by the maintainers of the package managers and often they omit certain parts of netdata, namely netdata cloud libraries and the claiming script.

Thus, users are unable to use the cloud or find the claiming script but are unaware that the installation method is the culprit. This creates a considerable support load as also a very bad UX.

##### Expected behavior

Netdata Agent is able to detect the installation method and if 1) a package manager is used b) netdata cloud parts are omitted, then it informs the users (e.g banner) that he/she should uninstall the agent re-install using the one-line script.

cc @manos-saratsis for prioritization and @Ferroin for more information regarding the detection.

**Comment by Ferroin** [comment]
Installation method detection is dead simple. If there's a `.environment` file in the user config directory (`/etc/netdata` on most builds, `/opt/netdata/etc/netdata` for the static builds), then it was installed through one of our official installers (our only installer that does not do this is our binary packages, but they have working cloud support so the second check should make this irrelevant). 

The contents of said file are simple POSIX shell variable definitions, and can be used to determine further information aobut the install itself if required (though i don't think we need that for this).

**Comment by OdysLam** [comment]
A user on Reddit had the same issue on macOS and homebrew.

**Comment by Ferroin** [comment]
Yeah, it's a known issue with the Homebrew formula.

They have the same requirements that almost all Linux distros do for packaging that are causing this issue, namely that they don't accept support for features that require statically linking in libraries that are already available as part of the repository itself.

As far as the _why_, it's largely a matter of ensuring good security, with static linking you're tied to whatever library versions you used at build time and don't automatically get security updates just by updating the library itself.

**Comment by OdysLam** [comment]
Another one: https://community.netdata.cloud/topic/136/after-upgrade-to-ubuntu-20-04-lts-netdata-will-not-load-in-my-browser/5

All these incidents are since we created this issue, all from different users. As a data point for the prioritization.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
