### ISSUE TITLE
Bad condition in enable_netdata_updater() function cause auto-updating not working

### ISSUE THREAD

**Issue by marcingarski** [netdata/netdata#10025]
##### Bug report summary

After #9966 Netdata stopped auto-updating. The cause of this is probably bad condition in `enable_netdata_updater()` function from `packaging/installer/functions.sh`. On line 984 you test for zero length string (`if [ -z "${1}" ] ; then`) but it should be non-zero length string (`-n`).

##### Component Name

packaging
##### Steps To Reproduce

1. Wait for auto-update or run
2. bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```
 --- Check if we must enable/disable the netdata updater tool ---
Unable to determine what type of auto-update scheduling to use, not enabling auto-updates.

 FAILED  Cannot enable netdata updater tool 
```

**Comment by ilyam8** [comment]
@Ferroin take a look

**Comment by Ferroin** [comment]
@marcingarski Nice catch, not sure how that got past review.

**Comment by Ferroin** [comment]
Fix merged. This should automatically start working again without any user intervention once tonight's nightly build is published.
