### ISSUE TITLE
missing metrics in war room

### ISSUE THREAD

**Issue by jimerickson** [netdata/netdata#10021]
##### Question summary
when i go to my netdata cloud war room it only displays metrics for total cpu utilazation, and available memory. it is not showing total disk i/o, total network bandwiidth, and tempurature. i have recently switched to ubuntu 20.10 arm64 because of problems getting raspbian 64-bit to connect. but all my amd64 machines on ubuntu 20.04 are affected too. when i go to "localhost:19999" all the metrics are displayed. what have i done wrong? my netdata was compiled from github on all my machines and is updated nightly. i can pastebin the error.log, access.log and debug.log of a recently claimed node if necessary (i tried to attach them but github says something went wrong when attempting to do so.).
##### OS / Environment
ubuntu 20.04 amd64, ubuntu 20.10 arm64
##### Component Name
ACLK???
##### Expected results
expected netdata cloud war room to display total cpu utilazation, available memory, total disk i/o, total network bandwith, and tempurature.

**Comment by jimerickson** [comment]
[error.log](https://github.com/netdata/netdata/files/5322355/error.log)
[access.log](https://github.com/netdata/netdata/files/5322356/access.log)

ok here are the files, finally got it to work.

**Comment by stelfrag** [comment]
Hi @jimerickson could you update to the latest  version ?

There is fix that will address the problem you are facing

**Comment by jimerickson** [comment]
thank you i will do that!
