### ISSUE TITLE
Tarball checksum validation failed

### ISSUE THREAD

**Issue by mobcer** [netdata/netdata#10023]
##### Question summary
On the installation procedure executed by kickstart.sh, I get the following error 

>  ABORTED  Tarball checksum validation failed. Stopping netdata installation and leaving tarball in /tmp/netdata-kickstart-IFlDnKrvIY
>
What should I do?
##### OS / Environment
Debian 9 with shell root access
##### Component Name
kickstart.sh
##### Expected results
to be installed without interrupt

**Comment by Ferroin** [comment]
This is probably a result of caching issues we've had with Google Cloud Storage (which we use for hosting our build artifacts). As a general rule, if you try about an hour or so later when you run into this, it should work correctly.

We've been looking into solution for this for some time now but have so far not found any practical fix.

**Comment by OdysLam** [comment]
@mobcer We are so sorry that you are experiencing this. As @Ferroin said, we are aware and we want to fix this. Thanks for mentioning it though, it helps to assess priority.

In any case, welcome to our community! Don't hesitate to comment on any thread and join our forums at https://community.netdata.cloud!
