### ISSUE TITLE
Graphs shown on local server (port 19999) but not on cloud.

### ISSUE THREAD

**Issue by altimore** [netdata/netdata#10026]
##### Bug report summary

With the Network UPS Tool plugin (charts.d/ups.conf), i claimed the node on cloud, I can see the graphs for the UPS on the local server (http://raspberry_local_ip:19999/) but not on the cloud server.
![Screenshot from 2020-10-05 14-18-09](https://user-images.githubusercontent.com/662362/95070292-f4a51080-0718-11eb-8fa5-3881dd9ee382.png)

![Screenshot from 2020-10-05 14-38-15](https://user-images.githubusercontent.com/662362/95070217-d7704200-0718-11eb-8365-2802600fc8af.png)

Please note that the errors and warning from /etc/netdata/health.d/nut.conf are triggered correctly and the alerts are displaying the yellow and red circle in the cloud web interface and the alarms appears correctly in the bell menu on the top right of the interface.

The call to the api works as well :
![Screenshot from 2020-10-05 14-49-04](https://user-images.githubusercontent.com/662362/95070972-00dd9d80-071a-11eb-8a10-1befd138f422.png)

##### OS / Environment

```
pi@raspberrypi:/etc/netdata $ uname -a; grep -Hv "^#" /etc/*release  # Linux
Linux raspberrypi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="9"
/etc/os-release:VERSION="9 (stretch)"
/etc/os-release:VERSION_CODENAME=stretch
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version

pi@raspberrypi:/etc/netdata $ netdata -V
netdata v1.25.0-115-nightly

##### Steps To Reproduce

On a computer with network ups tools installed.
1. install net data with the oneliner install script
2. login in the cloud to get the token
3. claim the node with the claim script

##### Expected behavior

I expected the cloud detail page with the graphs to match the one on the local machine on the port 19999 and see the graphs of the ups data.

**Comment by stelfrag** [comment]
Hi @altimore 

Could you share your `error.log` file?

**Comment by altimore** [comment]
Hello @stelfrag, 

Here it is : 
[error.log](https://github.com/netdata/netdata/files/5326943/error.log)

**Comment by altimore** [comment]
My bad, the error.log i posted was almost empty, here is a new version after reloading both pages (http://192.168.100.54:19999/#menu_nut_nutdev1_submenu_ups;theme=white and https://app.netdata.cloud).

[error.log](https://github.com/netdata/netdata/files/5326999/error.log)

**Comment by havanahjoe** [comment]
I've been meaning to post a similar report. I have a lot of missing graphs in my cloud that are available locally. This is happening on three servers, two Ubuntu 18.04.5 LTS and one Raspberry OS in two different physical locations. Running v1.25.0-115-nightly on all three.

Is there a limit somewhere that we might be hitting where certain sensors just don't get sent or are getting truncated? CPU data is missing from all three. Not sure if this is a more widespread issue.

Every second, Netdata collects 4,791 metrics on UbuntuServer1, presents them in 411 charts and monitors them with 142 alarms.
Every second, Netdata collects 4,170 metrics on UbuntuServer2, presents them in 332 charts and monitors them with 108 alarms.
Every second, Netdata collects 1,585 metrics on RaspberryPiServer, presents them in 248 charts and monitors them with 92 alarms.

It doesn't seem like I have that many metrics, and I'd expect the Pi server to be fine since it has the least.

**Comment by stelfrag** [comment]
Could you try the following:

Reload agent's health by doing (if agent installed under /usr)

- sudo /usr/sbin/netdatacli reload-health

or 

- Send a USR2 signal to the agent's PID 
  - e.g. something like  **sudo kill -USR2 _netdata_**
- Go to the cloud (app.netdata.cloud) and refresh the page

Do the missing charts appear with data?

**Comment by altimore** [comment]
@stelfrag here are the commands i typed :
```
pi@raspberrypi:/etc/netdata $ sudo /usr/sbin/netdatacli reload-health
pi@raspberrypi:/etc/netdata $ ps aux |grep netdata
netdata   6311  4.4 21.1 300912 93656 ?        Ssl  09:40  12:53 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D
netdata   6313  0.0  0.6  16144  2844 ?        Sl   09:40   0:00 /usr/sbin/netdata --special-spawn-server
netdata   6548  6.6  0.8   7336  3752 ?        S    09:40  19:17 /usr/libexec/netdata/plugins.d/apps.plugin 1
netdata  13432  1.0  0.5   3548  2632 ?        S    13:40   0:30 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata  13437  1.2  0.6   3928  3048 ?        S    13:40   0:35 bash /usr/libexec/netdata/plugins.d/charts.d.plugin 1
pi       21406  0.0  0.4   4360  1904 pts/1    S+   14:28   0:00 grep --color=auto netdata
pi@raspberrypi:/etc/netdata $ sudo kill -USR2 6311
pi@raspberrypi:/etc/netdata $ sudo kill -USR2 6313
pi@raspberrypi:/etc/netdata $ sudo systemctl restart netdata
```

Then reloaded https://app.netdata.cloud/, same as before, no charts for the UPS.
I tried in Firefox and in Chrome, same result.

@havanahjoe Same problem on an Intel NUC with Ubuntu 20.04.1 LTS, missing the UPS data graphs with a similar NUT config.
I can see the CPU data and it tops at 20% maximum, it is not saturated.

**Comment by stelfrag** [comment]
Hi @altimore 

Please do not restart netdata after the -USR2 signal. 

The USR2 will cause a health reload (and send refreshed chart information to the cloud). Seeing if that helps (or not) we will see how to further investigate.

**Comment by altimore** [comment]
ok, i re ran the kill USR2 on the two processes and refreshed the browser on app.netdata.cloud without restarting netdata, i still miss the UPS graphs.

**Comment by stelfrag** [comment]
@hmoragrega Please take a look

**Comment by OdysLam** [comment]
@havanahjoe, we are so sorry that you too are experiencing this. It's a known bug and we are racing to fix this.

On a sidenote, welcome to our community :) I hope you enjoy your stay here.  We also have a forum at https://community.netdata.cloud. Cheers!

**Comment by stelfrag** [comment]
Hi @altimore , @havanahjoe 

Could you upgrade to the latest nightly to check if the problem is resolved?

**Comment by altimore** [comment]
Hello, 

It works with the latest version (v1.25.0-115-nightly) as a bonus it takes in account the parameter nut_priority=1 (which it did not on the cloud before) so i have it on top of the other metrics.

Thanks a lot for your prompt solution.
