### ISSUE TITLE
Emails are not send despite successful notifications tests

### ISSUE THREAD

**Issue by gpastuszko** [netdata/netdata#10022]
#### Summary

I’m running netdata in a container. 

.msmtprc is setup correctly and all test as describe in [documentation ](https://learn.netdata.cloud/docs/agent/health/notifications/email) are successful. The 3 test email are sent out successfully!

```
bash-5.0# su -s /bin/bash netdata
bash-5.0$ whoami
netdata
bash-5.0$ /usr/libexec/netdata/plugins.d/alarm-notify.sh test

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2020-10-04 13:21:37: alarm-notify.sh: INFO: sent email notification for: host.com test.chart.test_alarm is WARNING to 'admin@host.com'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2020-10-04 13:21:38: alarm-notify.sh: INFO: sent email notification for: host.com test.chart.test_alarm is CRITICAL to 'admin@host.com'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2020-10-04 13:21:39: alarm-notify.sh: INFO: sent email notification for: host.com test.chart.test_alarm is CLEAR to 'admin@host.com'
# OK
```

However, when I stress the CPU for over 20min no notification email has been send. 

Nothing in regards to failed alert can’t be found in the logs.
 
Found this issue

https://github.com/netdata/netdata/issues/6807#issue-490862755

...but there is no solution nor a hint on how to troubleshoot this issue.

**Comment by OdysLam** [comment]
Hey @gpastuszko 

Welcome to our community! We are so sorry that you encounter this issue, but no worries, we will get to the bottom of this 💪

Just to be super clear, you have followed the troubleshooting mentioned in #6807? Furthermore, how did you install Netdata and what OS are you using?

Finally, please make sure that you are running the latest version of Netdata. You can update it following the [documentation](https://learn.netdata.cloud/docs/agent/packaging/installer/update).

**Comment by gpastuszko** [comment]
Your alarm_notify.sh script somehow doesn't pick the env $HOME variable of the netdata user.

**_workaround_**:
moving the **/etc/netdata/.msmtprc** onto **/etc/msmtp** and setting the permission to 0644 solves this problem.

**Comment by thiagoftsm** [comment]
Hello @gpastuszko ,

When Netdata sends an email, it uses the function

https://github.com/netdata/netdata/blob/fba31ed22dd61161ec9ac4547e1b9b8a11cc35d3/health/notifications/alarm-notify.sh.in#L823

and this function does not get environment variables like `$HOME`, the command used to send the email that gets information from its internal configuration to send data.

About the permission, Netdata runs as `netdata` user, unless you change this during the installation, and this user needs to have condition to read configuration files.

Best regards!

**Comment by gpastuszko** [comment]
Hey @OdysLam

> I’m running netdata in a **container**.  (official container: OS would be alipne 3.12)


Hello @thiagoftsm 

>` .msmtprc `is **setup correctly** and all test as describe in [documentation ](https://learn.netdata.cloud/docs/agent/health/notifications/email) are successful. **The 3 test email are sent out successfully**!
> 
> ```
> bash-5.0# su -s /bin/bash netdata
> bash-5.0$ whoami
> netdata
> bash-5.0$ /usr/libexec/netdata/plugins.d/alarm-notify.sh test
> 
> # SENDING TEST WARNING ALARM TO ROLE: sysadmin
> 2020-10-04 13:21:37: alarm-notify.sh: INFO: sent email notification for: host.com test.chart.test_alarm is WARNING to 'admin@host.com'
> # OK
> 
> # SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
> 2020-10-04 13:21:38: alarm-notify.sh: INFO: sent email notification for: host.com test.chart.test_alarm is CRITICAL to 'admin@host.com'
> # OK
> 
> # SENDING TEST CLEAR ALARM TO ROLE: sysadmin
> 2020-10-04 13:21:39: alarm-notify.sh: INFO: sent email notification for: host.com test.chart.test_alarm is CLEAR to 'admin@host.com'
> # OK
> ```


Just to clarify,

- docker official installation 
- email test are successful as **netdata** user
- no email alarm is send
- in logs: msmtp error 76
- moved msmtprc to` /etc/msmtprc `, still no good. netdata has no access
- changed the owner to netdata  -> works
- moving it to `/etc/netdata/.msmtprc`  and setting permissions to 666 results in no emails again
- moving back to /etc/msmtprc -> works

**Conclusion**
The script, which start calling all the other scripts. Doesn't know were is the $HOME of `netdata `user

Kind regards

**Comment by ilyam8** [comment]
`$HOME` is https://github.com/netdata/netdata/blob/cedb8707c8ce1728984da85a58d24c26ddc24ad9/daemon/common.c#L14

btw, not `/etc/netdata`

---

> moving back to /etc/msmtprc -> works

[I see it is](https://wiki.archlinux.org/index.php/Msmtp)

- `~/.msmtprc` or `$XDG_CONFIG_HOME/msmtp/config`
- the system configuration file belongs at `/etc/msmtprc`

---

> moving it to /etc/netdata/.msmtprc and setting permissions to 666 results in no emails again

Do we suggest it in the docs?

**Comment by thiagoftsm** [comment]
> Do we suggest it in the docs?

We give in the [documentation](https://learn.netdata.cloud/docs/agent/health/notifications/email#simple-smtp-transport-configuration) instructions to read `msmtp` official documentation, but it was wrote there the following command:

```
chmod 600 ~/.msmtprc
```

and this is a contradiction with the found solution.

**Comment by ilyam8** [comment]
```cmd
[ilyam@ilyam-pc ~]$ getent passwd netdata
netdata:x:967:967:netdata:/opt/netdata/var/lib/netdata:
```

home is

> /opt/netdata/var/lib/netdata

**Comment by ilyam8** [comment]
oh, i missed _running netdata in a container_ part (first sentence i know 🙈).

it is `/etc/netdata`, indeed

```cmd
bash-5.0# getent passwd netdata
netdata:x:201:201:Linux User,,,:/etc/netdata:/usr/sbin/nologin
```

That is why we have successful notifications tests.

What could be wrong is `HOME` is being changed on nd process start.

I added loging `HOME` env var to the python collector

```cmd
bash-5.0# cat /usr/libexec/netdata/python.d/example.chart.py | grep os -B 1
    def check(self):
        import os
        self.info(os.environ.get('HOME'), 111)
```
And restarted netdata containers.

For some reason `HOME` is `/root`

```cmd
[ilyam@ilyam-pc ~]$ docker logs heuristic_margulis 2>&1 | grep python.d | grep example
2020-10-05 19:18:34: python.d INFO: plugin[main] : [example] built 1 job(s) configs
2020-10-05 19:18:34: python.d INFO: example[example] : /root 111
2020-10-05 19:18:34: python.d INFO: plugin[main] : example[example] : check success
2020-10-05 19:22:43: python.d INFO: plugin[main] : [example] built 1 job(s) configs
2020-10-05 19:22:43: python.d INFO: example[example] : /root 111
2020-10-05 19:22:43: python.d INFO: plugin[main] : example[example] : check success
```

**Comment by ilyam8** [comment]
@gpastuszko i think this can be solved if we set `HOME` to `/etc/netdata` on container creating

```cmd
[ilyam@ilyam-pc ~]$ docker run -d --env HOME=/etc/netdata netdata/netdata
```

```cmd
[ilyam@ilyam-pc ~]$ docker exec -it musing_brown curl http://127.0.0.1:19999/netdata.conf | grep home
	# home directory = /etc/netdata
```

**Comment by gpastuszko** [comment]
way to go @ilyam8 ! You got to the bottom of that issue. Thanks a lot. (Thumbs up!)

Setting `ENV `var is what we did. Actually we went little further. We have set `msmtp `  locally on the host and only the binary is bind mounted to container. The rational behind it was, that we have some other services which required `sendmail `  too.

Kind regrads

**Comment by OdysLam** [comment]
@gpastuszko we are glad that we found a solution that works. @ilyam8 and @thiagoftsm great work as always!
