### ISSUE TITLE
charts.d plugin: Operation not permitted sudo: unable to initialize policy plugin

### ISSUE THREAD

**Issue by mbarper** [netdata/netdata#10037]
##### Question summary

Unable to run sudo commands inside a chart.d plugin script. It reports:

```
sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin

```
##### OS / Environment

Ubuntu 16/18

##### Component Name

charts.d plugin

##### Expected results

I'm not really sure about if the problems come from Netdata user is a guess account or from a CapabilityBoundingSet thata avoids sudo commands, but I would like to execute sudo commands as another user (not root) to be able to monitor things in the OS that belongs to a specific user and I can't perform those commands without sudo rights for Netdata user.

The thing is, if I use the debug mode:

```
# become user netdata
sudo su -s /bin/sh netdata

# run the plugin in debug mode
/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 X Y Z
```

it works fine.

But when rely on netdata service I get the error in the summary section. 

Any clue? Something I can do? Any trick?

Thanks in advance and regards,
Moises

**Comment by baskinsy** [comment]
I have the same issue with megacli python.d plugin. I have followed the official instructions to add netdata user to sudoers and also I added it to the sudo group with no luck.

```
2020-10-07 19:36:52: python.d ERROR: megacli[megacli] : sudo: unable to change to root gid: Operation not permitted
2020-10-07 19:36:52: python.d INFO: plugin[main] : megacli[megacli] : check failed
```
Also on debug with the netdata user it works.

**Comment by ilyam8** [comment]
> the problems come from Netdata user is a guess account or from a CapabilityBoundingSet

**Comment by ilyam8** [comment]
Related https://github.com/netdata/netdata/issues/8535#issuecomment-606401520

**Comment by baskinsy** [comment]
> Related [#8535 (comment)](https://github.com/netdata/netdata/issues/8535#issuecomment-606401520)

Tried the solution here: https://github.com/netdata/netdata/issues/8535#issuecomment-606401520

but got the same problem..

**Comment by ilyam8** [comment]
Did you `systemctl daemon-reload`?

**Comment by baskinsy** [comment]
yes...

**Comment by baskinsy** [comment]
```
root@host2 /etc/netdata # systemctl daemon-reload
root@host2 /etc/netdata # systemctl restart netdata.service 
root@host2 /etc/netdata # cat /etc/systemd/system/netdata.service.d/cap-sys-admin.conf 
[Service]
CapabilityBoundingSet=CAP_SYS_ADMIN
```

```
2020-10-07 23:15:59: python.d ERROR: megacli[megacli] : sudo: unable to change to root gid: Operation not permitted
2020-10-07 23:15:59: python.d INFO: plugin[main] : megacli[megacli] : check failed
```
Strange it didn't worked...

**Comment by OdysLam** [comment]
Hey @baskinsy , welcome to the community :)

**Comment by mbarper** [comment]
Do you guys think we could use something like the perf plugin?

> Accessing hardware PMUs requires root permissions, so the plugin is setuid to root.

But with the setuid to the user you need to run the plugin.

Or maybe add the capabilities to be able to do `sudo` to another user.

**Comment by ilyam8** [comment]
Probably fixed by https://github.com/netdata/netdata/pull/10201
