### ISSUE TITLE
weird time on charts

### ISSUE THREAD

**Issue by nenonano** [netdata/netdata#10049]
Hi all

I'm running netdata on more than a linux server.. all VM under hyper-v

on just one machine, I'm having issues with the time in the grapps (see attach)

just upgraded netdata to the last available nightly release

sysadmin@srv-web:~$ $(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V
netdata v1.25.0-138-nightly

sysadmin@srv-web:~$ uname -a
Linux srv-web 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux
![Cattura](https://user-images.githubusercontent.com/17139113/95585569-a7d67800-0a3f-11eb-9291-50cddccf27b7.PNG)

sysadmin@srv-web:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

sysadmin@srv-web:~$ date
ven  9 ott 2020, 14.45.34, CEST
sysadmin@srv-web:~$ timedatectl status
      Local time: ven 2020-10-09 14:46:35 CEST
  Universal time: ven 2020-10-09 12:46:35 UTC
        RTC time: ven 2020-10-09 12:47:37
       Time zone: Europe/Rome (CEST, +0200)
 Network time on: yes
NTP synchronized: no
 RTC in local TZ: no

**Comment by jacekkolasa** [comment]
Hi @nenonano!
Do you have default timezone settings in Dashboard-options/Locale tab?

Can you check /api/v1/charts response, to make sure timezone is the same, and check in any chart `last_entry` value, if it's not in the future??

**Comment by RahmatAliMalik5** [comment]
I also got weird results. It is showing me time `24:56:24`. Should show `00:56:24`.

![image](https://user-images.githubusercontent.com/31620469/104958385-be527f00-59f1-11eb-8ee7-f5de3044dd2c.png)

**Comment by stelfrag** [comment]
Closing in favor of https://github.com/netdata/netdata/issues/9533
