### ISSUE TITLE
freeipmi.plugin "exited with error code 1"

### ISSUE THREAD

**Issue by wcallgair** [netdata/netdata#10044]
##### Bug report summary
I get the following error when starting netdata with freeipmi enabled:

```
2020-10-08 17:17:26: netdata INFO  : PLUGINSD[freeipmi] : thread created with task id 188989
2020-10-08 17:17:26: netdata INFO  : PLUGINSD[freeipmi] : set name of thread 188989 to PLUGINSD[freeip
2020-10-08 17:17:26: netdata INFO  : PLUGINSD[freeipmi] : connected to '/usr/libexec/netdata/plugins.d/freeipmi.plugin' running on pid 188993
2020-10-08 17:17:26: netdata ERROR : PLUGINSD[freeipmi] : read failed: end of file (errno 9, Bad file descriptor)
2020-10-08 17:17:26: netdata INFO  : PLUGINSD[freeipmi] : PARSER ended
2020-10-08 17:17:26: netdata ERROR : PLUGINSD[freeipmi] : '/usr/libexec/netdata/plugins.d/freeipmi.plugin' (pid 188993) disconnected after 0 successful data collections (ENDs).
2020-10-08 17:17:26: netdata ERROR : PLUGINSD[freeipmi] : child pid 188993 exited with code 1.
2020-10-08 17:17:26: netdata ERROR : PLUGINSD[freeipmi] : '/usr/libexec/netdata/plugins.d/freeipmi.plugin' (pid 188993) exited with error code 1 and haven't collected any data. Disabling it.
2020-10-08 17:17:26: netdata INFO  : PLUGINSD[freeipmi] : thread with task id 188989 finished

```
Free ipmi works when ran manually or in debug from the netdata user:
```
bash-4.2$ /usr/libexec/netdata/plugins.d/freeipmi.plugin 5 debug 
CHART ipmi.events '' 'IPMI Events' 'events' 'events' ipmi.sel area 90002 5
DIMENSION events '' absolute 1 1
CHART ipmi.sensors_states '' 'IPMI Sensors State' 'sensors' 'states' ipmi.sensors_states line 90001 5
DIMENSION nominal '' absolute 1 1
DIMENSION critical '' absolute 1 1
DIMENSION warning '' absolute 1 1
CHART ipmi.temperatures_c '' 'System Celsius Temperatures read by IPMI' 'Celsius' 'temperatures' 'ipmi.temperatures_c' 'line' 90010 5
DIMENSION i6_n212_r2 'Exhaust Temp i6' absolute 1 1000
DIMENSION i5_n3_r2 'Inlet Temp i5' absolute 1 1000
```
I did notice that It takes about 10 seconds to gather any output from freeipmi on this machine. Could this by why netdata is abandoning freeipmi?

##### OS / Environment
```
Linux **** 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.7.1908 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.7.1908 (Core)
/etc/system-release:CentOS Linux release 7.7.1908 (Core)
```

##### Netdata version
netdata v1.24.0.19.nightly

##### Component Name
freeipmi

**Comment by ilyam8** [comment]
@wcallgair hi, sorry for the late response. This bug is likely fixed in the master/latest stable version. If it is not the case, please comment/reopen the issue.

**Comment by mailinglists35** [comment]
I am experiencing the same on centos 7. 
output from plugin attached

````
Installed Packages
netdata.x86_64                                                            1.30.1-1.el7                                                    @epel-testing
netdata-conf.noarch                                                       1.30.1-1.el7                                                    @epel-testing
netdata-data.noarch                                                       1.30.1-1.el7                                                    @epel-testing
netdata-freeipmi.x86_64                                                   1.30.1-1.el7                                                    @epel-testing
````
[ipmi.txt](https://github.com/netdata/netdata/files/6361919/ipmi.txt)

**Comment by mailinglists35** [comment]
`ipmimonitoring` gives `/usr/sbin/ipmi-sensors: permission denied` if run as `netdata`.  it runs ok as root

**Comment by ilyam8** [comment]
OP problem is likely a CapabilityBoundingSet restriction when running as a service, which could be solved by [resetting the set](https://community.netdata.cloud/t/freeipmi-plugin-internal-system-error/1145/6?u=ilyam8).

**Comment by mailinglists35** [comment]
great, it worked, thank you!

Could you enable this workaround by default?

`CapabilityBoundingSet=~`

**Comment by ilyam8** [comment]
Well well, it effectively removes **all** `CapabilityBoundingSet` limits, which is a security hardening feature.

I agree that is a very annoying problem, it keeps popping up here and there and I keep saying to people to apply this workaround.

But, I think, that is the logic: we want to have this security feature on, and it should be a user deliberate action to remove it.


**I am not a specialist**, perhaps we could relax Netdata systemd service hardening and switch to `AmbientCapabilities`.

- `AmbientCapabilities`: grants capabilities that the process normally wouldn't have started with.

- `CapabilityBoundingSet`: limits capabilities the process is allowed to obtain. It doesn't grant any. Even if the service running as root and uses `sudo` it is not possible to gain any capabilities which are not in the set.

**Comment by mailinglists35** [comment]
ah, I see. then perhaps this should be instead an entry into the freeipmi plugin docs?

**Comment by mailinglists35** [comment]
> OP problem is likely a CapabilityBoundingSet restriction when running as a service, which could be solved by [resetting the set](https://community.netdata.cloud/t/freeipmi-plugin-internal-system-error/1145/6?u=ilyam8).

Thank you, I have followed one of the replies and set
`CapabilityBoundingSet = CAP_SYS_RAWIO`

it was on the same system that worked with `~`, but was upgraded from 1.30 to 1.34.1 (oracle linux 7 via OL7_developer_epel repo)

Could you please add this bit of info about the capabilities in the plugin documentation?

Thanks!

**Comment by ilyam8** [comment]
@mailinglists35 I added CAP_SYS_RAWIO to Netdata's systemd unit CapabilityBoundingSet in #13154.
