### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by alexmyczko** [netdata/netdata#10047]
you might want to work togetherbwith the official debian package maintainers of netdata.

and taking your packaging the following list of things should be fixed:

https://mentors.debian.net/package/netdata/

**Comment by OdysLam** [comment]
Hey @alexmyczko,

We are in contact with the Debian Maintainers and we are trying to find a slot and have a kickoff meeting so that we can address their reservations and properly support the Official Package manager!
