### ISSUE TITLE
web_log module create dimension based on log's endpoint and status code

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#10056]
##### Question summary
I have already done this in promtail and I wonder if it is possible to handle it on the netdata,
Our Nginx logs contain some endpoints and status codes, we want to know the status code per endpoint.
Right now I have to define patterns in order to get requests per pattern but still, I don't know the status codes per endpoint.
Here is a sample metric I have generated based on the same log in promtail (I don't have to manually define patterns to detect the endpoints) :
```
myapp_request_status{app="myapp",instance="myapp-01.app.x.y.z:9080",job="app_exporter",request_url="/v1/get_event",status="200"}
``` 

##### Component Name
web_log

**Comment by ilyam8** [comment]
Hi. There are 3 charts per url pattern:
 - Responses By Status Code
 - Bandwidth
 - Request Processing Time

So it is possible to get response status codes per endpoint, do you mean a chart per every endpoint w/o setting a pattern?


> dimension based on log's endpoint and status code

How would that chart look like?

**Comment by yasharne** [comment]
Thanks @ilyam8 for your clarification, I realized I had a misconfiguration and now I get response codes per pattern, but I wonder if it is possible to create patterns automatically so that we don't need to update the configuration every time

**Comment by yasharne** [comment]
Also, is it possible to have HTTP method per url_pattern?

**Comment by ilyam8** [comment]
> Also, is it possible to have HTTP method per url_pattern?

This is pretty easy to add.

> to create patterns automatically

Looks like another configuration option. How many different uri's do you have in your logs? Just curios.

**Comment by yasharne** [comment]
@ilyam8 This Nginx has 9 different URI but some of our Nginx servers have more than one hundred different URI

> This is pretty easy to add.

How can I add it the configuration file?

**Comment by ilyam8** [comment]
no, it is not implemented😄 i mean easy to add to the source code.

**Comment by yasharne** [comment]
@ilyam8 Also, since both python version and go version of web_log is running, I cannot find the metrics generated by the go version on the Prometheus, do they have the same name on metrics?

**Comment by ilyam8** [comment]
> python version and go version of web_log is running

Then they have different job names.
