### ISSUE TITLE
How to view text-based Nginx Access log inside netdata?

### ISSUE THREAD

**Issue by mcnaveen** [netdata/netdata#10055]
### Question summary
How to view text-based Nginx Access log inside netdata?

##### OS / Environment
Linux sitsg-server 5.4.0-48-generic # 52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

##### Component Name
Nginx

##### Expected results
Currently, all I can view is a chart of Nginx Logs. But I want to view and search the text-based log inside that. Is it possible? Because I want to analyze and monitor the Unique IP.

**Comment by ilyam8** [comment]
Hi @mcnaveen, no, it is not possible, all collected data is presented as charts.

**Comment by mcnaveen** [comment]
No other possible way buddy? Badly need that.

**Comment by ilyam8** [comment]
> search the text-based log inside that

^^ not possible, yes. It is not because of lack of plugin, netdata doesnt store logs.

**Comment by mcnaveen** [comment]
Ok got it.
