### ISSUE TITLE
Click a line to select it in same way selecting it in the legend does.

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#10069]
##### Feature idea summary

It would be very useful if clicking a line on a chart in the netdata dashboard had the same effect as clicking its series from the legend.

Sometimes it is quite tricky to figure out from looking at the legend what line you are actually interested in selecting. Being able to just 'click' the line itself would be very useful. 

##### Expected behavior

For example I would like to just click the line with the step in the image below:

![image](https://user-images.githubusercontent.com/2178292/96013307-03887300-0e3d-11eb-933b-51f9453b0da2.png)

and see same outcome as if I had selected it via the legend:

![image](https://user-images.githubusercontent.com/2178292/96013408-2155d800-0e3d-11eb-823b-a67970c242fd.png)

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
