### ISSUE TITLE
Displaying Mb/s for OpenVPN.total_traffic plugin on Netdata.cloud

### ISSUE THREAD

**Issue by DonZheng** [netdata/netdata#10062]
##### Feature idea summary
When OpenVPN plugin is enabled, Netdata Could displays openvpn.total_traffic by `kilobits/s`. 

What it looks now:
![image](https://user-images.githubusercontent.com/40833875/95792954-43156900-0d30-11eb-95ff-f9e18e8a6229.png)

##### Expected behavior
`Mb/s` is preferrable for most server monitering operators so that the metrics are more readable. 
Suggest we set `Mb/s` as default for openvpn.total_traffic.

I would argue all network related metrics shall adopt `Mb/s` as default metrics. Maybe it's just me.

**Comment by manos-saratsis** [comment]
@DonZheng it's not just you, we need to improve there and maybe let users switch to their preferred units

**Comment by manos-saratsis** [comment]
@DonZheng I am closing the ticket as we opened a separate one to track it. Low prio unfortunately
