### ISSUE TITLE
Disable specific health-alarms in specific time-period

### ISSUE THREAD

**Issue by exetico** [netdata/netdata#10063]
##### Question summary
Is it possible to mute a alarm, in a specific time-period? 

Real Scenario:
`ipv4 tcphandshake`, `ipv4  udperrors` and `netfilter last collected` are reporting error at 2:31 every night, due to daily backups. I can't control how it's done, but it's recovered after 5 minuters (appx.)

I know that the task will be executed at 2:30, so I was searching for an option to disable the alarm from 2:30 to 2:45, or something simular.

Are there an option to ignore a specific alart, in a given timeperiod?

##### OS / Environment
CentOS, RedHat and more

##### Component Name
Alarms
health.d:
 - udp_errors.conf
 - tcp_resets.conf
 - netfilter.conf

##### Expected results
By "muting"/ignore alarms in a given period of time, no emails will be sent related to the given health-topic (both "attention" and "recoevered" state), but only between 2:30 to 2:45, if that's the time-period. However, it will still alert me, if an alarm goes on (for the mentioned health confs.), if it's outside the defined timestamps.

**Comment by ilyam8** [comment]
dup of https://github.com/netdata/netdata/issues/9097

**Comment by ilyam8** [comment]
Hi @exetico ,unfortunately there is no such option. 

There is [health management API](https://learn.netdata.cloud/docs/agent/web/api/health#disable-or-silence-specific-alarms), it allows to enabled/disable specific alarms in runtime. I understand that is not what you want but still worth to mention.
