### ISSUE TITLE
Histograms always showing +Inf

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#10075]
##### Bug report summary
Throughout the Dashboard the Histograms in web_log go.d charts only ever show +Inf and no actual values. Been this way a while I think.

##### OS / Environment
```
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)
```

##### Netdata version
 v1.25.0-164-g023a622b

##### Component Name
Web

##### Steps To Reproduce

Screenshot attached.

Using default histogram configuration values.

##### Expected behavior

Netdata to restore display of stats in the Histograms.

<img width="781" alt="Netdata dashboard" src="https://user-images.githubusercontent.com/13329789/96070643-84c12380-0e98-11eb-9729-8663e74dfbe8.png">

**Comment by ilyam8** [comment]
Hi, it seems buckets are in in microseconds 

https://github.com/netdata/go.d.plugin/blob/f66c28fd6f7bbc68815567f06e5daf5b822de942/config/go.d/web_log.conf#L98-L101

https://github.com/netdata/go.d.plugin/blob/f66c28fd6f7bbc68815567f06e5daf5b822de942/modules/weblog/logline.go#L560-L568

**Comment by TheOldMan2000** [comment]
Thanks, I'm sure it used to work fine out of the box with default histogram: [1,3,10,30,100] which relate to seconds.

1sec = 1000 milliseconds (multiply the time value by 1000)
and
1ms = 0.001 seconds (divide the time value by 1000)

so as the histogram chart says requests per second and not milliseconds, I tried 
`histogram: [0.001,0.002,0.003,0.004,0.005]`

but no success, it still says +Inf (unsure what that means?).

Should the chart display number of requests in 1 millisecond, 2 milliseconds etc? Or should it show as it does now requests per second (humanising the value) but the list show the numbers per millisecond?

**Comment by TheOldMan2000** [comment]
Putting the integers in 1000's produces some more info and a list on the right.

e.g. histogram: [1000,2000,3000,4000,5000,10000]

<img width="756" alt="netdata Dashboard histogram" src="https://user-images.githubusercontent.com/13329789/96280343-c4d6f200-0fcf-11eb-9e37-301e5f41556d.png">

**Comment by ilyam8** [comment]
Yes, it show number of requests per second. I see we store the value in microseconds

https://github.com/netdata/go.d.plugin/blob/1305e1afb4b57776ce29daa2fedfa631c16dde1d/modules/weblog/logline.go#L560-L568

What we can do is to have configuration in seconds (`0.001`, etc) and convert internally to microseconds.

**Comment by ilyam8** [comment]
@hamedbrd do you want to fix this?

Configuration is in milliseconds

https://github.com/netdata/go.d.plugin/blob/1305e1afb4b57776ce29daa2fedfa631c16dde1d/config/go.d/web_log.conf#L98-L101

Both `request processing time` and `upstream response time` values are in microseconds (we convert them)

https://github.com/netdata/go.d.plugin/blob/1305e1afb4b57776ce29daa2fedfa631c16dde1d/modules/weblog/logline.go#L560-L568


So we need to convert config `histogram` option to microseconds (ms=>us) and then pass it to NewHistogram

https://github.com/netdata/go.d.plugin/blob/1305e1afb4b57776ce29daa2fedfa631c16dde1d/modules/weblog/metrics.go#L85-L87

---

Since this option is broken we could change it - have it in seconds.

@TheOldMan2000 what do you think? What is better - seconds (`[0.1, 0.2,..]`) or milliseconds (`[100, 200,...]`)?

**Comment by TheOldMan2000** [comment]
Thanks guys, you're awesome. I think probably milliseconds as that's how responses are measured in Apache logs and if you are using a page tester like GT Metrix.
