### ISSUE TITLE
Is it possible to compress CPU section?

### ISSUE THREAD

**Issue by JakeMHughes** [netdata/netdata#10073]
##### Question summary
The CPUs section in netdata displays all the CPU data with a separate chart for each core. With most CPUs this is perfectly fine, but with multi-processor servers this section gets pretty large. 

Are there any options to compress this section some? for instance Windows task manager would have multiple smaller charts on the same line, is there anything similar in netdata?

If not, are there any recommendations?

##### OS / Environment
Ubuntu 20.04

##### Component Name
[cpu.cpu#]

**Comment by TheOldMan2000** [comment]
Great idea, my VPS has 48 virtual cores so I tend to avoid this section.

**Comment by ilyam8** [comment]
Hi, atm you either have per core charts or no

```cmd
[plugin:proc:/proc/stat]
  per core cpu utilization = no
```

**Comment by OdysLam** [comment]
@JakeMHughes ,  thanks for the suggestion. The tip that Ilya suggests is suitable for your needs?

BTW, welcome to our community! If you have any other questions please create an issue or even better create a post at our [forums](https://community.netdata.cloud)! :)

**Comment by Ferroin** [comment]
Perhaps we could add an option to display the per-core charts at half height? Even with only 16 vCPUs on a Ryzen 7 1700 these sections get a bit unwieldy.

**Comment by JakeMHughes** [comment]
So digging in the docs a bit, I found the page about [custom dashboards](https://learn.netdata.cloud/docs/agent/web/gui/custom). 
Looks like a simple 
```    
    <div data-netdata="cpu.cpu0"
        data-chart-library="dygraph"
        data-title="CPU0"
        data-width="300"
        data-height="100"
        data-after="-600"
        data-legend="no"
        data-common-max="chart-group-1"
        ></div>
    <div data-netdata="cpu.cpu1"
        data-chart-library="dygraph"
        data-title="CPU1"
        data-width="300"
        data-height="100"
        data-after="-600"
        data-legend="no"
        data-common-max="chart-group-1"
        ></div>
```
works and looks decent enough
![data](https://user-images.githubusercontent.com/46405216/96170122-30965d80-0ef1-11eb-85ed-f76004449591.png)

So thats definitely an option, but it would be nice to have it as an optional setting in the base dashboard

**Comment by Ferroin** [comment]
Actually, being able to have them be reduced width like that as well as reduced height would be awesome. The change would indeed need to be in the dashboard code though.

@jacekkolasa Any idea how much effort this might require?

**Comment by Ferroin** [comment]
Updating the tags on this one, it’s a UI/UX feature request for the dashboard at this point, not a question.

**Comment by jacekkolasa** [comment]
It's not that difficult to do, but we would need to build some UI to control this, because if we change the behaviour for everyone, there will be always someone who won't like it...

Right now you can build custom dashboards using app.netdata.cloud. There are more features coming there. I'm not sure how big priority this is to build new features like this in Agent Dashboard.
CC @manos-saratsis @dim08

**Comment by Ferroin** [comment]
The individual node view on app.netdata.cloud would honestly benefit from this as well, as it has the exact same issues WRT over-crowded CPU charts.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
