### ISSUE TITLE
Zend Opcache and PHP charts

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#10074]
##### Feature idea summary

I noticed that there are no stats in Netdata for Opcache by default. In the past I've noticed that there are a few Opcache dashboards showing big colourful pie charts etc for stats on GitHub, and I noticed some stats displayed in PHP info.

Zend Opcache
Opcode Caching | Up and Running
-- | --
Optimization | Enabled
Startup | OK
Shared memory model | mmap
Cache hits | 332
Cache misses | 191
Used memory | 26239688
Free memory | 2121243960
Wasted memory | 0
Interned Strings Used memory | 2022576
Interned Strings Free memory | 4268456
Cached scripts | 191
Cached keys | 194
Max keys | 7963
OOM restarts | 0
Hash keys restarts | 0
Manual restarts | 0

<img width="1024" alt="PHP 7 3 23 - phpinfo()" src="https://user-images.githubusercontent.com/13329789/96069338-e764f000-0e95-11eb-830a-7dc408afe6ca.png">

 I would imagine adding some real-time stats and charts for Zend Opcache to Netdata would be quite useful for sysadmins. The icing on the cake would be some out of the box, zero configuration PHP stats. The existing PHP collectors have never worked for me re FastCGI, PHP-FPM handlers etc on CentOS 7 with Apache.

##### Expected behavior

Netdata to display Zend Opcache information and stats.

Many thanks.

**Comment by ilyam8** [comment]
Hi @TheOldMan2000 👋 I have feeling that 

> Opcache 

I see there is [`opcache_get_status`](https://www.php.net/manual/en/function.opcache-get-status.php) function in php to get those metrics, have no clue how to it works and how to get those metrics or if they even exposed. 

> PHP charts

What are you referring to? What php chart? 🤔

**Comment by TheOldMan2000** [comment]
#What are you referring to? What php chart?

Exactly! ;)

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
