### ISSUE TITLE
Question: how to disable the "apache" collector

### ISSUE THREAD

**Issue by candlerb** [netdata/netdata#10081]
#### Question summary

I am most likely being dense here.  I want to disable the apache collector, so that it doesn't keep logging:

```
::1 - - [15/Oct/2020:19:57:27 +0100] "GET /server-status?auto HTTP/1.1" 200 1539 "-" "-"
::1 - - [15/Oct/2020:19:57:28 +0100] "GET /server-status?auto HTTP/1.1" 200 1538 "-" "-"
::1 - - [15/Oct/2020:19:57:29 +0100] "GET /server-status?auto HTTP/1.1" 200 1539 "-" "-"
...
```

I have tried:

```
cd /opt/netdata/etc/netdata
cp orig/go.d.conf .
vi go.d.conf
```

Edited this file:

```
...
modules:
#  activemq: yes
   apache: no
#  bind: yes
...
```

Restarted netdata, no difference.

I have also edited /opt/netdata/etc/netdata/netdata.conf

```
[netdata.runtime_apache_local]
        # history = 5
        enabled = no
```

Again no difference.

I tried to search [documentation](https://learn.netdata.cloud/docs/agent/collectors/reference#enable-and-disable-plugins), but that showed how to disable the entire go.d plugin, rather than an individual one.  There is also documentation on how to [configure the plugin](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/apache) but not how to disable it.

##### OS / Environment

Ubuntu 18.04

```
# /opt/netdata/bin/netdata -V
netdata v1.26.0
```

##### Component Name

apache collector

##### Expected results

To be able to disable it

**Comment by ilyam8** [comment]
Hi @candlerb 👋 You need to disable python version too (`python.d.conf`).

**Comment by ilyam8** [comment]
You disabled it correctly, it is `go.d.conf` and there you enabled/disable specific collectors.

**Comment by ilyam8** [comment]
We migrating py=>go so we have some collectors written in both/languages 😄

**Comment by candlerb** [comment]
Thank you!

For reference, I did the following:

```
cd /opt/netdata/etc/netdata
cp orig/python.d.conf .
vi python.d.conf
```
```
...
apache: no
...
```

Then after `systemctl restart netdata` the problem is solved.

(also I put `netdata.runtime_apache_local` back how it was in `netdata.conf`)

**Comment by ilyam8** [comment]
> netdata.runtime_apache_local

These are _Time Execution_ charts for every py/go collector jobs. (`Netdata Monitoring->{go.d,python.d}`)
