### ISSUE TITLE
1.26.0 - Plugin: Slabinfo - compilation warnings (expect argument)

### ISSUE THREAD

**Issue by BKPepe** [netdata/netdata#10086]
### Bug report summary

While cross-compilation of Netdata 1.26.0, I noticed these warnings: 
https://gist.github.com/BKPepe/82f9a66e8f01e1eb0565b57baa182c1d

Almost the same for collectors/proc.plugin/sys_class_infiniband.c and  `collectors/proc.plugin/proc_pagetypeinfo.c`

##### OS / Environment
Linux super_cool_name 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

##### Netdata version
netdata v1.26.0

##### Component Name
Plugins: slabinfo, proc

##### Steps To Reproduce

- Try to cross-compile it for OpenWrt

##### Expected behavior
There shouldn't be warnings.

**Comment by ilyam8** [comment]
@BKPepe thx for reporting!

@Saruspete hi, since you are the collector author, would be nice if you help us one more time 😉

**Comment by Saruspete** [comment]
Hello,

Thanks for reporting. These difference in type seems to be related to the target CPU Arch (I guess 32bit CPU ?)
It appears to be a way to automatically get the target format: https://en.cppreference.com/w/cpp/types/integer

I've updated the reported printf in my branch "fix_printf". Can you please test it: https://github.com/Saruspete/netdata/tree/fix_printf

Thanks

**Comment by BKPepe** [comment]
Hi,

Yes, target CPU is 32 bit. I tried your patch and I see there are still some warnigns.

```
collectors/slabinfo.plugin/slabinfo.c: In function 'read_file_slabinfo':
collectors/slabinfo.plugin/slabinfo.c:194:23: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t {aka unsigned int}' [-Wformat=]
             slabdebug("    Line %zu has only %lu words, skipping", l, procfile_linewords(ff,l));
                       ^
collectors/slabinfo.plugin/slabinfo.c:16:23: note: in definition of macro 'slabdebug'
     fprintf(stderr, ##args); \
                       ^~~~
```

**Comment by Saruspete** [comment]
Ok, fixed

I'll create PR
