### ISSUE TITLE
Resizing the height of a chart using the up and down icons broken on mobile (iPad)

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#10091]
##### OS / Environment

iPad OS

##### Netdata version
v1.26.0-6-g33c7a110

##### Component Name
Web

##### Steps To Reproduce

When using an ipad, attempt to resize the height of a chart using the up and down icons. Nothing happens.

##### Expected behavior
Restore height adjustment controls on dashboard charts.

**Comment by jacekkolasa** [comment]
Hi @TheOldMan2000 , is this the same issue as https://github.com/netdata/netdata/issues/9286?

**Comment by TheOldMan2000** [comment]
Hi @jacekkolasa yes, thank you, it's the same issue.
