### ISSUE TITLE
FreeBSD net inbound and net outbound does not have data. 

### ISSUE THREAD

**Issue by emanzx** [netdata/netdata#10094]
##### Bug report summary

Net data failed to get data on net inbound and net outbound for the aggregated network bandwidth.

##### OS / Environment

```
FreeBSD dnsvgitnlognode.local 12.1-RELEASE-p10 FreeBSD 12.1-RELEASE-p10 GENERIC  amd64
1201000
```

##### Netdata version

  $(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V
2020-10-18 11:59:19: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2020-10-18 11:59:19: netdata INFO  : MAIN : SIGNAL: Not enabling reaper

##### Component Name

![image](https://user-images.githubusercontent.com/2576990/96358417-8fe6ae80-1139-11eb-953a-8848040f9957.png)
there is no data for the total bandwidth 
![image](https://user-images.githubusercontent.com/2576990/96358435-b3a9f480-1139-11eb-81c3-4b89888f7c31.png)
Overview displayed the inbound and outbound as 0 forever. 

##### Steps To Reproduce

1. Install netdata in freebsd 12.1 using script or package.
2. check the dashboard. 

##### Expected behavior

Netdata should be able to display aggregated network bandwidth.

**Comment by thiagoftsm** [comment]
Hello @emanzx ,

I installed the latest Netdata now on `FreeBSD 12.1-RELASE-p10` and I configured this Netdata to stream data for another Netdata and I am having the network chart with the data:

![err](https://user-images.githubusercontent.com/49162938/96450392-a8bc9600-1205-11eb-9b11-540cc0d9e46e.png)
 

Which Netdata version (`netdata -V`) are you runing?
How did you install your Netdata?

Best regards!

**Comment by kchiem** [comment]
I can confirm having the same problem, but on FreeBSD 12.2:

```
$ uname -rs
FreeBSD 12.2-RELEASE-p1

$ netdata -V
netdata v1.26.0
```
![ScreenClip](https://user-images.githubusercontent.com/17679003/102541061-c458e700-4064-11eb-89ff-24c79a6d1ef8.png)

![ScreenClip](https://user-images.githubusercontent.com/17679003/102541068-c91d9b00-4064-11eb-87c8-e8a275e0b91e.png)

**Comment by vlvkobal** [comment]
Please show the settings of the `plugin:freebsd:getifaddrs` section in `http://localhost:19999/netdata.conf`. What interfaces do you have on your system?

**Comment by kchiem** [comment]
> Please show the settings of the `plugin:freebsd:getifaddrs` section in `http://localhost:19999/netdata.conf`. What interfaces do you have on your system?

When I go to that URI, I get "You are not allowed to access this resource."

There's only one interface on it, re0.

**Comment by vlvkobal** [comment]
To access the effective configuration, you should uncomment `allow netdata.conf from` in the `web` section of `netdata.conf` and add your IP to the list of allowed hosts.

**Comment by kchiem** [comment]
There was no web section, which added to the confusion.  Everything in the getifaddrs sections is commented out:

```
[plugin:freebsd:getifaddrs]
	# enable new interfaces detected at runtime = auto
	# total bandwidth for physical interfaces = auto
	# total packets for physical interfaces = auto
	# total bandwidth for ipv4 interfaces = auto
	# total bandwidth for ipv6 interfaces = auto
	# bandwidth for all interfaces = auto
	# packets for all interfaces = auto
	# errors for all interfaces = auto
	# drops for all interfaces = auto
	# collisions for all interfaces = auto
	# disable by default interfaces matching = lo*
	# set physical interfaces for system.net = igb* ix* cxl* em* ixl* ixlv* bge* ixgbe* vtnet* vmx*

[plugin:freebsd:getifaddrs:re0]
	# enabled = yes
	# bandwidth = auto
	# packets = auto
	# errors = auto
	# drops = auto
	# events = auto

[plugin:freebsd:getifaddrs:lo0]
	# enabled = no

[plugin:freebsd:getifaddrs:pflog0]
	# enabled = yes
	# bandwidth = auto
	# packets = auto
	# errors = auto
	# drops = auto
	# events = auto
```
	
Everything here comes from a straight `$ pkg install netdata`.

**Comment by vlvkobal** [comment]
Please add
`set physical interfaces for system.net = igb* ix* cxl* em* ixl* ixlv* bge* ixgbe* vtnet* vmx* re*`
to the `plugin:freebsd:getifaddrs` section in your `netdata.conf`. Can you see network bandwidth data?

**Comment by kchiem** [comment]
Yes!

**Comment by vlvkobal** [comment]
Cool, then I'm making a PR...
