### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by davtur19** [netdata/netdata#10092]
##### Bug report summary

The latest version on docker has a memory leak
previous version: sha256:cccd8d5d278b5d8035e39c6c3a1eb82f1977ff03dbe210665a25d5a17e41ae76
current version: sha256:7e190b9d58fb679e701716ada472e1220e8f91f552f516470f53f804b8e54329

##### OS / Environment
Running on docker image: netdata/netdata

Host info:
```Linux roc-rk3399-pc 5.8.13-rockchip64 #20.08.8 SMP PREEMPT Mon Oct 5 15:59:02 CEST 2020 aarch64 aarch64 aarch64 GNU/Linux
/etc/armbian-image-release:BOARD=roc-rk3399-pc
/etc/armbian-image-release:BOARD_NAME="ROC-RK3399-PC"
/etc/armbian-image-release:BOARDFAMILY=rk3399
/etc/armbian-image-release:BUILD_REPOSITORY_URL=https://github.com/armbian/build
/etc/armbian-image-release:BUILD_REPOSITORY_COMMIT=c239158
/etc/armbian-image-release:DISTRIBUTION_CODENAME=focal
/etc/armbian-image-release:DISTRIBUTION_STATUS=csc
/etc/armbian-image-release:VERSION=20.05.0-trunk
/etc/armbian-image-release:LINUXFAMILY=rockchip64
/etc/armbian-image-release:BRANCH=current
/etc/armbian-image-release:ARCH=arm64
/etc/armbian-image-release:IMAGE_TYPE=user-built
/etc/armbian-image-release:BOARD_TYPE=csc
/etc/armbian-image-release:INITRD_ARCH=arm64
/etc/armbian-image-release:KERNEL_IMAGE_TYPE=Image
/etc/armbian-image-release:IMAGE_UUID=bf6fa458-a3be-44d2-b6df-c1ad2f8af936
/etc/armbian-release:BOARD=roc-rk3399-pc
/etc/armbian-release:BOARD_NAME="ROC-RK3399-PC"
/etc/armbian-release:BOARDFAMILY=rk3399
/etc/armbian-release:BUILD_REPOSITORY_URL=https://github.com/armbian/build
/etc/armbian-release:BUILD_REPOSITORY_COMMIT=c239158
/etc/armbian-release:DISTRIBUTION_CODENAME=focal
/etc/armbian-release:DISTRIBUTION_STATUS=csc
/etc/armbian-release:VERSION=20.05.0-trunk
/etc/armbian-release:LINUXFAMILY=rockchip64
/etc/armbian-release:BRANCH=current
/etc/armbian-release:ARCH=arm64
/etc/armbian-release:IMAGE_TYPE=user-built
/etc/armbian-release:BOARD_TYPE=csc
/etc/armbian-release:INITRD_ARCH=arm64
/etc/armbian-release:KERNEL_IMAGE_TYPE=Image
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

 netdata v1.26.0-5-gc7f2b109

##### Component Name

idk

##### Steps To Reproduce

I just updated to the new image
I use `save` as db engine

##### Expected behavior

Don't have 2GB of ram occupied after 2 hours

![image](https://user-images.githubusercontent.com/13476215/96338977-daaceb80-1091-11eb-80dc-7f7ce59f9ac5.png)

**Comment by ilyam8** [comment]
Hi @davtur19 

> netdata v1.26.0-5-gc7f2b109
> The latest version on docker has a memory leak

So prev version has no? Did you use `v1.25.0`?

Lets see components memory usage `Applications->mem`

**Comment by davtur19** [comment]
The previous version is this: sha256:cccd8d5d278b5d8035e39c6c3a1eb82f1977ff03dbe210665a25d5a17e41ae76 from netdata/netdata:latest
So it's netdata/netdata:latest from two days ago, I'm not sure what the previous version was, but I'm sure of the image I was using and it didn't give any problems

![image](https://user-images.githubusercontent.com/13476215/96376423-17a2dc00-117f-11eb-80d2-08c9e18cabd4.png)

**Comment by mfundul** [comment]
@Ferroin can you point us to the relevant git commits between those 2 docker builds? @thiagoftsm could this be a memory leak in ebpf?

@davtur19 can you share your error logs? (could be at `var/log/netdata/error.log` or in the docker logs). Are you using the ebpf collector?

**Comment by ilyam8** [comment]
@mfundul it is not ebpf

> Running on docker image: netdata/netdata

**Comment by thiagoftsm** [comment]
> @Ferroin can you point us to the relevant git commits between those 2 docker builds? @thiagoftsm could this be a memory leak in ebpf?

No @mfundul , `ebpf.plugin` by default does not run on docker, because Alpine team does not compile the `bpf` syscall with its kernel, also there are other configuration with docker that disable the plugin.

**Comment by mfundul** [comment]
@davtur19 can you also share your `etc/netdata/netdata.conf`?

**Comment by davtur19** [comment]
> @davtur19 can you share your error logs? (could be at `var/log/netdata/error.log` or in the docker logs). Are you using the ebpf collector?

[error.log](https://github.com/netdata/netdata/files/5401891/error.log)

> @davtur19 can you also share your `etc/netdata/netdata.conf`?

[netdata.conf](https://github.com/netdata/netdata/files/5402006/netdata.conf.txt)


Now I am using the latest version netdata/netdata:latest, same problem
I tried version 1.26.0 and 1.25.0 from docker and I have the same problem
It is very strange, since I did not have such a high RAM usage before, I use `save` as database, but with `KSM` the use was limited, could an update of my kernel or docker have caused some problems? because that's the only thing I've done
I also restored a backup of the netdata config, and still have a very high RAM usage

As I was writing I did a kernel update and restarted the SBC, and now the problem seems to be gone...
I now have this kernel version 5.8.16

![image](https://user-images.githubusercontent.com/13476215/96456728-3193fb80-121f-11eb-9619-1b1d81a37e1c.png)
