### ISSUE TITLE
Text font size is far too small to read without large zooming on gauges when using an iPad.

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#10090]
##### Bug report summary
Although responsive, the text that accompanies dashbaord gauges is far too small to read when using a standard iPad.
(Gauges shown at top in System Overview and those recently restored in Go.d Web_Log)

##### OS / Environment
ipad OS 14x

##### Netdata version
v1.26.0-6-g33c7a110
 

##### Component Name
web

##### Steps To Reproduce

General usage.

##### Expected behavior

Larger gauges to make better use of available horizontal space with increased font size to ensure readable text labels.

**Comment by ilyam8** [comment]
Issue moved to [netdata/dashboard #297](https://github.com/netdata/dashboard/issues/297) via [**ZenHub**](https://www.zenhub.com/)
