### ISSUE TITLE
Remote ssh setup

### ISSUE THREAD

**Issue by duhzon** [netdata/netdata#10099]
Hello guys! Last year i installed netdata on Beowulf cluster setup with fedora in my University lab, but we had some problem and it was re installed. Due to covid situation i cant go to lab and im trying to setup again all metrics in one display with a custom dashboard. But im facing a early situation. I can run netdata on main network node, but cannot display netdata on other machine. 
I will brieffly describle what is the situation:
The Beowulf cluster is running with fedora in a LAN wich gateway is 192.168.1.1. There is 12 pc with statical IP from 192.168.1.100 - 192.168.1.112. Im in away from campus but can acess every machine from ssh. I use ssh into "real" ip from node 0,  ssh @127.x.x.x to go into main node wich is 192.168.1.100 from that lan. Só installed netdata there and can see console with http://127.x.x.x:19999 (i cant get anything with http://192.168.1.100:19999 its due to lan topology and ssh feature? So, once im in ssh into main node i can jump to any network node with ssh lps@lps0x where x is the machine number, to go into node 192.168.1.102 i use ssh lps@lps02. I tried to install netdata on these nodes but i cannot run netdata in any of these, i already tried to get real ip in linux terminal wich is 127.x.x.60 for node 2 and tried http://127.x.x.60:19999 once i getnothing with 192.168.1.102:19999 but without luck, so i cannot make these netdata comunnicate with main node. Im running out of ideas. There is a way to acess main node with 192.168.1.100:1999 from outside of lan? Or 127.x.x.x:19999 its the only way? Why i cannot see netdata on other nodes with ssh? I tried firewall stuff but without sucess. There is a way to see networks topology? If its a star topology for exemplo. Thanx in advice im new im ssh configuration im still trying to understand the role of lan ip and real one but with covid situation ssh is the only way i have to setup netdata on beowuld cluster. Thanks in advice guys!

**Comment by ilyam8** [comment]
@duhzon hi

I think `parent-child` setup would help you, see https://learn.netdata.cloud/docs/agent/streaming.

Then you ssh into parent(main) node and observe add hosts from there.


> i cant get anything with http://192.168.1.100:19999 its due to lan topology and ssh feature

Could be netdata listens only on localhost, see

```cmd
# ss -ntl | grep 19999
LISTEN 0      4096         0.0.0.0:19999      0.0.0.0:*          
LISTEN 0      4096            [::]:19999         [::]:*
```
