### ISSUE TITLE
Adding another modifier than ALT + click + mouse drag for the linux users

### ISSUE THREAD

**Issue by altimore** [netdata/netdata#10104]
##### Feature idea summary
Hello, 

The default behaviour in some (most) linux system window manager for ALT + click + drag is to move the window so we cannot use your metric correlation function in the netdata cloud interface.

##### Expected behavior
It would be nice if you can add a different shortcut which would be usable without changing the window manager settings.

Regards, 

Thomas.

**Comment by jacekkolasa** [comment]
Hi @altimore! Can you check if other modifier keys work (ctrl or meta/windows key)? Perhaps only our description is wrong? It should support also other modifier keys.

**Comment by altimore** [comment]
Hello, 

It's working with the ctrl key, thanks.

Maybe you could add an overlay like when we press the "?" key in GMail with all the shorcuts available.
![004_best-gmail-keyboard-shortcuts-4686794-0852ef75c64547feb336f96dbb1be04e](https://user-images.githubusercontent.com/662362/98771026-f2f7f800-23fc-11eb-9f63-e737e2c493b1.jpg)


Regards,

Thomas.
