### ISSUE TITLE
Netdata update failed - Centos 6

### ISSUE THREAD

**Issue by ipiasecki** [netdata/netdata#10106]
Hi.

I tried to update netdata on centos 6, but process failed.

I attached a screenshot.

What now ?
![Zrzut ekranu 2020-10-20 104246](https://user-images.githubusercontent.com/11630236/96562657-4aed8400-12c1-11eb-9bcb-68ff52df7694.png)

**Comment by vlvkobal** [comment]
@stelfrag Please check #9978. You defined `CONTEXT_PARAM` twice.

**Comment by stelfrag** [comment]
Taking a look

**Comment by evrynet1** [comment]
Unfortunately I'm still getting the same error even after @stelfrag fix using:

bash <(curl -Ss https://my-netdata.io/kickstart.sh)

(I removed the tmp files from /tmp before re-running the installer)

**Comment by stelfrag** [comment]
> Unfortunately I'm still getting the same error even after @stelfrag fix using:
> 
> bash <(curl -Ss https://my-netdata.io/kickstart.sh)
> 
> (I removed the tmp files from /tmp before re-running the installer)

The nightly build (that will have the above fix) will be available in a few hours (lets say 6 hours to be on the safe side). 

Can you try again?

**Comment by evrynet1** [comment]
@stelfrag still the same but I will wait overnight and give it a try tomorrow. thank you!

**Comment by evrynet1** [comment]
@stelfrag worked perfectly now, thanks for the quick fix

**Comment by OdysLam** [comment]
@evrynet1, we are glad that we made it work in the end! BTW, welcome to our community!

Please, if you have any feedback for us, we would love to hear your thoughts at our forums: https://community.netdata.cloud
