### ISSUE TITLE
Custom python plugins breaks with print statement

### ISSUE THREAD

**Issue by cg-cnu** [netdata/netdata#10119]
##### Bug report summary

Not sure if I am doing something wrong here, but having a **print** statement in any of the custom **python plugins** stops all of them from loading. Lost couple of hours trying to debug this.
 
##### OS / Environment

```
CentOS-7
```

##### Netdata version

v1.24.0

##### Component Name

Python plugins

##### Steps To Reproduce

1. enable the custom.chart.py
2. random values chart shows up in the UI
3. edit the custom.chart.py and place a print statement
4. chart won't show up in the UI

##### Expected behavior

Ideally, I would expect the custom charts to show up in the interface even with print statements.

**Comment by ilyam8** [comment]
Hi. This is expected, plugins.d reads `stdout`, see https://learn.netdata.cloud/docs/agent/collectors/plugins.d#operation

> The `stdout` of external plugins is connected to Netdata to receive metrics, with the API defined below.

> The `stderr` of external plugins is connected to Netdata's `error.log`.

There are `self.error`/`self.warning`/`self.info`/`self.debug` for logging.

**Comment by cg-cnu** [comment]
Hey @ilyam8 I was not aware of that. I was under the assumption the **data** returned by get_data is used by Netdata. Thanks!

**Comment by OdysLam** [comment]
@cg-cnu Thanks for bringing this to our attention. Perhaps @joelhans this is some feedback to improve our docs, thoughts? 

(P.S @cg-cnu welcome to our community :) )

**Comment by cg-cnu** [comment]
Thanks @OdysLam 🙂 
The document page for writing the [custom python plugin](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin#how-to-write-a-new-module) clearly outlined how to write the python plugin, adding Segments on **local testing** and **caveats** would be very helpful.
