### ISSUE TITLE
Netdata Cloud ECN href tag appears to be formatted incorrectly

### ISSUE THREAD

**Issue by Rav4s** [netdata/netdata#10118]
##### Bug report summary

When you navigate to a specific node in Netdata Cloud and scroll to ECN, the raw HTML is visible instead of a link.
![Screenshot 2020-10-21 121228](https://user-images.githubusercontent.com/63246200/96818398-0e1bad00-13e7-11eb-840d-65d6aca9fc69.png)

I inspected the webpage HTML and found that the <a> tag was using &lt and &gt instead of < and >.
![Screenshot 2020-10-21 121311](https://user-images.githubusercontent.com/63246200/96818571-533fdf00-13e7-11eb-8206-4c9120ab103a.png)

Upon changing the HTML with < and > in the <a> tag, I was able to view the link properly.
![Screenshot 2020-10-21 121829](https://user-images.githubusercontent.com/63246200/96818654-7bc7d900-13e7-11eb-9c78-2a593152567a.png)
![Screenshot 2020-10-21 121901](https://user-images.githubusercontent.com/63246200/96818678-88e4c800-13e7-11eb-81e0-2707b8140cee.png)

##### OS / Environment

```
Linux redacted 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 8.2.2004 (Core) 
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="8 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="8"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="CentOS Linux 8 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:8"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-8"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="8"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 8.2.2004 (Core) 
/etc/system-release:CentOS Linux release 8.2.2004 (Core)
```

##### Netdata version

netdata v1.26.0-43-nightly
##### Component Name

Netdata Cloud
##### Steps To Reproduce

1. Open Netdata Cloud in your browser
2. Navigate to one of your nodes
3. Scroll down to ECN
4. You will see raw HTML instead of a link to the Wikipedia article

##### Expected behavior

I expected a link to the article to show up instead of raw HTML. I was able to reproduce this on a few other nodes running different netdata versions in Netdata Cloud. This does not affect the netdata web interface at *:19999, only Netdata Cloud.

**Comment by Rav4s** [comment]
Just discovered that this affects the softnet chart as well:
![Screenshot 2020-10-22 081433](https://user-images.githubusercontent.com/63246200/96877454-46e77080-143f-11eb-90b2-9df070698066.png)

**Comment by OdysLam** [comment]
Thanks @Rav4s for bringing this to our attention and welcome to our community!

Please, if you have any feedback for us, we would love to hear your thoughts at our forums: https://community.netdata.cloud

**Comment by jacekkolasa** [comment]
fix deployed to https://app.netdata.cloud/, thanks @Rav4s!
