### ISSUE TITLE
PROCFILE: Cannot open file '/proc/sysvipc/shm'

### ISSUE THREAD

**Issue by 643406834** [netdata/netdata#10111]
Wed Oct 21 11:51:30 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:32 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:34 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:36 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:38 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:40 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:42 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:44 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:46 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:48 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:50 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:52 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:54 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:56 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:51:58 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:00 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:02 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:04 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:06 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:08 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:10 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:12 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:14 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:16 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:18 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:20 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:22 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:24 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:26 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:28 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:30 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/shm'
Wed Oct 21 11:52:32 2020 daemon.err netdata[2090]: PROCFILE: Cannot open file '/proc/sysvipc/s
##### OS / Environment
Linux OpenWrt 4.14.195
```

```

##### Netdata version

 1.26.0-1

##### Steps To Reproduce

1. ...
2. ...

**Comment by vlvkobal** [comment]
Since there is no such file on your system, you can disable `shared memory totals` in the `[plugin:proc:ipc]` section of `netdata.conf` to get rid of these messages.
```
[plugin:proc:ipc]
	shared memory totals = no
```
