### ISSUE TITLE
Document reinstallation procedure on https://learn.netdata.cloud/docs

### ISSUE THREAD

**Issue by agarthetiger** [netdata/netdata#10124]
##### Feature idea summary
Document reinstallation procedure on docs site

I'm trying to configure netdata running on a Raspberry Pi 4b to export to VictoriaMetrics running on the same instance. I'm following https://learn.netdata.cloud/docs/agent/exporting/prometheus/remote_write which says to install (Google) protobuf and snappy and then reinstall netdata. 

According to https://github.com/netdata/netdata/issues/9758 I should be able to reinstall by removing the updater script and running the kickstart again with "...the exact same value for the --install option as the original install". 

When I ran this originally I used the code generated on the Get Netdata docs page, which doesn't have a `--install` option, instead I used `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel --disable-telemetry` Is this the command I should run again to reinstall? I would be useful if the reinstall procedure was documented if it's going to be required when enabling Prometheus remote write.  

I searched https://learn.netdata.cloud/docs but I didn't find any relevant results for reinstall.

##### Expected behavior
Reinstallation procedure is documented on https://learn.netdata.cloud/docs

**Comment by Ferroin** [comment]
Agreed, the docs could be made significantly more clear here.

In practice, you just need to use the same options you used originally with the install (so in your case `--no-updates --stable-channel --disable-telemetry`).

Also, for future reference, instead of manually removing the updater script, you can add `--reinstall` to the options you pass to the installer to have it act as if the update script isn’t there.

**Comment by OdysLam** [comment]
hey @agarthetiger , welcome to our community, and thanks for bringing this to our attention! cc @joelhans you might find this interesting.

**Comment by agarthetiger** [comment]
Thank you for the welcome and for confirming the original options. I think I'll also be using the `--reinstall` flag as I've still got issues with getting the prometheus remote write working, but I'll post on the community forum about that separately. 

It would be great to mention the `--reinstall` flag in the docs too.

**Comment by agarthetiger** [comment]
It looks like I can't add the `--reinstall` flag to the existing options. When I do I get the following output.

```shell
pi@desktop-pi:~ $ bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel --disable-telemetry --reinstall
 --- Found existing install of Netdata under: / --- 
 --- Attempting to update existing install instead of creating a new one --- 
[/home/pi]$ sudo //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron Fri 23 Oct 22:38:58 BST 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Fri 23 Oct 22:38:59 BST 2020 : INFO:  Current Version: 001026000052
Fri 23 Oct 22:38:59 BST 2020 : INFO:  Latest Version: 001026000052
Fri 23 Oct 22:38:59 BST 2020 : INFO:  Newest version (current=001026000052 >= latest=001026000052) is already installed
 OK  

 --- Updated existing install at /usr/sbin/netdata --- 
```

If I remove the other options and just run `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstall` then netdata will re-install, but I presume it has not retained all the previous settings. The console output shows it has not remembered the `--no-updates` flag, as the end of the reinstall output showed this.

```shell
 --- Installing (but not enabling) the netdata updater tool --- 
Update script is located at /usr/libexec/netdata/netdata-updater.sh

 --- Check if we must enable/disable the netdata updater tool --- 
Auto-updating has been enabled through cron, updater script linked to /etc/cron.daily/netdata-updater

If the update process fails and you have email notifications set up correctly for cron on this system, you should receive an email notification of the failure.
Successful updates will not send an email.
```

At the moment at least it seems you have to remove the update script. (Full disclosure, I haven't actually done this, I've been uninstalling with the uninstaller and reinstalling.)

**Comment by OdysLam** [comment]
Thanks for the additional info @agarthetiger. @Ferroin is looking into it and he will respond here promptly. Thanks for pointing this out and for your patience!

In the meantime, please remove the update script and confirm that everything works as expected. Rest assured that your feedback will lead to a timely improvement on this front. Thanks for helping us :)

**Comment by agarthetiger** [comment]
No problem :) I tried reinstalling by removing the file `/usr/libexec/netdata/netdata-updater.sh` and adding the `--reinstall` flag, but got the following output. The web dashboard shows I'm running version v1.26.0 which might be relevant.  

```shell
$ sudo rm /usr/libexec/netdata/netdata-updater.sh 
pi@desktop-pi:~/ $ bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel --disable-telemetry --reinstall
 --- Found existing install of Netdata under: / --- 
 ABORTED  Existing installation detected which cannot be safely updated by this script, refusing to continue.
```

**Comment by OdysLam** [comment]
@agarthetiger Thanks for the additional data point. So it doesn't pick up the --reinstall flag. 

Without users like you, we wouldn't be able to find issues and bugs so fast ,thanks!
