### ISSUE TITLE
Disk warn calculation question

### ISSUE THREAD

**Issue by junpet** [netdata/netdata#10127]
Why is this alarm green? It should throw a warning. What do I miss?

##### Question summary
![image](https://user-images.githubusercontent.com/3465278/96893381-ef6ef200-148a-11eb-9a20-8aeaeca9d192.png)

##### OS / Environment
Debian / Docker
##### Component Name
Alarm
##### Expected results
it should be yellow and warning.

**Comment by thiagoftsm** [comment]
@jacekkolasa, please, take a look on this.

**Comment by ilyam8** [comment]
Hi @junpet 👋 It is green because 89.3 < 90. 

See https://learn.netdata.cloud/docs/agent/health/reference#special-use-of-the-conditional-operator

**Comment by junpet** [comment]
Ah sorry, I was too tired and missed the syntax. Thanks and sorry for taking your time.

**Comment by OdysLam** [comment]
@junpet No worries, welcome to the community :)  Make sure you create an account and join our forum at https://community.netdata.cloud 🙏
