### ISSUE TITLE
Fixed scales for temperature graphs

### ISSUE THREAD

**Issue by Kuro-Maii** [netdata/netdata#10132]
##### Question summary
When looking at the graphs generated by `sensors` for the CPU and GPU temperatures it is very hard to see where in the acceptable range it is for the visible data.
The temperature graphs also have a tendency to flatten out to +- 0.4°C if the temperature is stable enough.

I have tried to figure out how to set a scale from the documentation but I could not figure this out beyond recreating an existing graph as a custom graph

##### Component Name
from the tool tip on the graph: `python.d:sensors, sensors.temperature`

##### Expected results
have the graphs scale to a fixed Y range of (for example) 0 - 110°C or to a range of 0 to the reported critical temperature.

this will still allow the graph to flat line for long periods of stable temperatures but it gives a better idea of the temperature being high or low while stable.

considering the output of `sensors` has a bit of a "wild" range for my current GPU (an ASUS Radeon R9 270) I can understand that this is not feasible to use as valid range.
personally I would clamp the range to a more sensible set of the aforementioned 0-110°C
as an example of what I mean here is the output on my system:
```
$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +58.0°C  (high = +82.0°C, crit = +100.0°C)
Core 0:        +56.0°C  (high = +82.0°C, crit = +100.0°C)
Core 1:        +54.0°C  (high = +82.0°C, crit = +100.0°C)
Core 2:        +59.0°C  (high = +82.0°C, crit = +100.0°C)
Core 3:        +59.0°C  (high = +82.0°C, crit = +100.0°C)

amdgpu-pci-0100
Adapter: PCI adapter
vddgfx:      1000.00 mV 
fan1:        1640 RPM  (min = 1000 RPM, max = 3000 RPM)
edge:         +81.0°C  (crit = +104000.0°C, hyst = -273.1°C)
power1:      114.00 W  (cap = 216.00 W)
```

**Comment by Saruspete** [comment]
That is indeed an interesting feature: disable the auto-scaling on the fly per chart. That would work also with other graphs, like "All systems processes" or "Entropy"

I would love a small button for every chart to enable/disable the auto-scaling (scale back to 0, instead of the min value)

**Comment by Ferroin** [comment]
Agreed, this would be an excellent feature to have in general. Re-tagging this as a feature request.

@jacekkolasa Any idea how hard this might be to implement?

**Comment by jacekkolasa** [comment]
@Kuro-Maii You're right, there is no way to change that directly in the App (there's no UI for that). But you can change that in dashboard_info.js file, like it has been done for the CPU: https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info.js#L759

You can do it either in that file, and repeat that change after every installation, or add custom dashboard_info.js, according to those instructions: https://learn.netdata.cloud/docs/agent/web/gui#customizing-the-standard-dashboard. Please let me know if I can be any help with this.

Anyway, having that feature (button to toggle, enforcing min-value to 0) is a good idea! Cc @dim08

**Comment by Kuro-Maii** [comment]
@jacekkolasa Even with the instructions page it was a lot of trail and error before I managed to actually figure out what file I needed to edit where and then what to put in said `custom_dashboard_info.js`.
adding to that it took almost an hour till I figured out that it was being chased somewhere server side and all I could do was change the filename, edit the config to match and restart. just restarting didn't do anything.
in total it took me over 3 hours of messing about before I managed to get the graphs to render with a set range. of which there was less then a minute for setting a range that looked right.

Any way of setting a range on the the page or just in a global setting for graphs would be a lot better then trying to figure out what name I need to put into a custom settings file.
per graph would be better as some won't need it or some will need a different range. but I do stand by that the dynamically scaling ranges of what is in view are not very usable.
a dynamic scale would still be fine if an "over everything" is used.
so keeping track of what the lowest value is starting from [datatype].max and highest value [datatype].min at time of installation and then storing something like `current_min_max = [min(current_val, prev_min), max(current_val, prev_max)]`?
that would keep the ranges dynamic but also allow for then to be usable in seeing if a value is going up or down over longer then visible time

**Comment by jacekkolasa** [comment]
@Kuro-Maii sorry for late reply. Having settings that allow users to force some y-axis range is nice idea, we just need to build UI for it. As for getting min/max since installation time - this is currently not available via Agent API, so it would need some work in the agent. (@stelfrag do you know if it would be hard to build that, ie. storing extreme values across all history?)

Right now we need to focus on completing set of features in Netdata Cloud, so I cannot tell when we'll be able to prioritise this feature idea. But I'll write here in case we'll start working on it.

**Comment by stelfrag** [comment]
> @Kuro-Maii sorry for late reply. Having settings that allow users to force some y-axis range is nice idea, we just need to build UI for it. As for getting min/max since installation time - this is currently not available via Agent API, so it would need some work in the agent. (@stelfrag do you know if it would be hard to build that, ie. storing extreme values across all history?)
> 
> Right now we need to focus on completing set of features in Netdata Cloud, so I cannot tell when we'll be able to prioritise this feature idea. But I'll write here in case we'll start working on it.

We can't store min/max just yet and running a query across all dimensions to get the values would be very expensive. We will need to work a way to store min/max as metrics are being collected so it will be available instantly.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
