### ISSUE TITLE
New alarms UX is confusing

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#10130]
##### Feature idea summary

The new alarms UX (non-interactive counter on the left, interactive bell on the right), confuse me as to "where to click to expand this error".

##### Expected behavior

Since I guess you are not going back to merge the counter and the bell; would you make the counter interactive too? (i.e. same as the bell)

**Comment by manos-saratsis** [comment]
@stdedos we will change soon the top navbar and your feedback will be discussed. I am closing this and stay tuned!
