### ISSUE TITLE
Stop netdata being accessed with IP:PORT (NGINX Reverse Proxy)

### ISSUE THREAD

**Issue by mcnaveen** [netdata/netdata#10135]
##### Question summary

How to block accessing netdata via IP:PORT

##### OS / Environment
Linux sitsg-server 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

##### Expected results
I have netdata running on VPS. And I did reverse proxy it with Domain Name.

The problem is I can still access it via IPADDR:PORT. I want to block it. I just want to open it via my domain name only

**Comment by Saruspete** [comment]
Hello,

You can add the following configuration in /etc/netdata/netdata.conf :

```
[web]
  allow connections from = localhost 127.0.0.1
```

That should filter the connections to allow only your locally running apps (like your reverse proxy)

**Comment by mcnaveen** [comment]
Perfect 💯
