### ISSUE TITLE
No chart is showing - exactly *zero* metrics/charts/alerms/nodes?

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/netdata#10136]
##### Bug report summary

After installation, netdata shows exactly zero charts... So no chart is on the screen... 

![image](https://user-images.githubusercontent.com/5236035/97082833-18d07f00-163f-11eb-9978-a83e36a43717.png)

**Note** (that maybe helpful to debug)

0. I am using Netdata Helm chart on Kubernetes.
1. Here is the log of netdata child and netdata parent: 
[netdata-child.log](https://github.com/netdata/netdata/files/5432945/netdata-child.log)
[netdata-parent.log](https://github.com/netdata/netdata/files/5432946/netdata-parent.log)

2. When I go to the Netdata child docker container and run `curl http://localhost:19999/api/v1/data?chart=system.cpu`, I see 
```
{
 "labels": ["time", "guest_nice", "guest", "steal", "softirq", "irq", "user", "system", "nice", "iowait"],
    "data":
 [

  ]
}
```
(I wait for several minutes, but still zero data points).
3. When I go to netdata parent and do the same, I see 
```
bash-5.0# curl http://localhost:19999/api/v1/data?chart=system.cpu
Chart is not found: system.cpu
```
4. When I use port forwarding (forward to my mac on 19998) and access it remotely (`http://localhost:19998/api/v1/data?chart=system.cpu`), I see 
```
{
 "labels": ["time", "guest_nice", "guest", "steal", "softirq", "irq", "user", "system", "nice", "iowait"],
    "data":
 [

  ]
}
```
again.

5. (edited) I change the flood protection threshold and here is the new logs, which may contain more useful information:

(netdata child) 
[netdata-child-10.25.log](https://github.com/netdata/netdata/files/5434785/netdata-child-10.25.log)

6. (edited) I made more experiments. I tried to (1) disable persistence (2) disable lots of components, but still no use.

##### OS / Environment

```
bash-5.0$ uname -a; uname -K
Linux test-one-55929 3.10.0-862.14.1.5.h428.eulerosv2r7.x86_64 #1 SMP Wed Mar 11 06:00:00 UTC 2020 x86_64 Linux
uname: unrecognized option: K
BusyBox v1.31.1 () multi-call binary.

Usage: uname [-amnrspvio]

Print system information

        -a      Print all
        -m      The machine (hardware) type
        -n      Hostname
        -r      Kernel release
        -s      Kernel name (default)
        -p      Processor type
        -v      Kernel version
        -i      The hardware platform
        -o      OS name
```

##### Netdata version

bash-5.0$ /usr/sbin/netdata -V
netdata v1.25.0
 

##### Component Name

everything!

##### Steps To Reproduce

1. Install netdata helm chart
2. look at it

##### Expected behavior

Should see things like cpu/memory/...

**Comment by ilyam8** [comment]
closing in favor of https://github.com/netdata/helmchart/issues/176
