### ISSUE TITLE
netdata/mosquitto will not build on macOS

### ISSUE THREAD

**Issue by 42Network** [netdata/netdata#10137]
##### Bug report summary

netdata/mosquitto will not build on macOS. This means I cannot get netdata to claim my system. 
```
mosquitto.c:59:10: error: implicit declaration of function 'mach_absolute_time' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ticks = mach_absolute_time();
               ^
1 error generated.
make[2]: *** [lib/CMakeFiles/libmosquitto.dir/mosquitto.c.o] Error 1
make[1]: *** [lib/CMakeFiles/libmosquitto.dir/all] Error 2
make: *** [all] Error 2
 FAILED   
```
##### OS / Environment

```
Darwin Nathans-MBP.42network.xyz 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
```

##### Netdata version

netdata v1.26.0-63-g92c32f27
 

##### Component Name

netdata/mosquitto

##### Steps To Reproduce

1. sudo ./netdata-installer.sh --install /usr/local
2. Error:

/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-mosquitto-XXXXXX.onynw3W4/mosquitto-v.1.6.8_Netdata-4/lib/mosquitto.c:59:10: error: implicit declaration of
      function 'mach_absolute_time' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ticks = mach_absolute_time();
                ^
1 error generated.
make[2]: *** [lib/CMakeFiles/libmosquitto.dir/mosquitto.c.o] Error 1
make[1]: *** [lib/CMakeFiles/libmosquitto.dir/all] Error 2
make: *** [all] Error 2
 FAILED   

##### Expected behavior

This is a know issue with the main mosquitto and Xcode 12. See this link:

https://github.com/eclipse/mosquitto/issues/1831

Apparently you need to add #include <mach/mach_time.h> to mosquitto.c

**Comment by 42Network** [comment]
Any updates?

**Comment by OdysLam** [comment]
Hey @42Network, 

Thanks for pinging us again on this one. It seems that we dropped the ball, we are sorry! I am pinging our engineers and they will respond shortly. Thanks for the patience :)

**Comment by underhood** [comment]
@OdysLam I created PR https://github.com/netdata/mosquitto/pull/10 that should fix it. Need somebody who has actual access to MacOS to test it

**Comment by underhood** [comment]
https://github.com/netdata/netdata/pull/10283 should fix this when it is merged :)
