### ISSUE TITLE
How to export snapshots of over 10 minutes length?

### ISSUE THREAD

**Issue by paxsali** [netdata/netdata#10149]
Netdata stores about 1 hour worth of history per default on the live view.

When exporting this data to a snapshot, the length varies from a 4min time window to 12min maximum from simple tests I have done.

How do I export a snapshot of the entire 1 hour or 3600 seconds (current) time frame to disk, so I can import it later to another netdata instance and have it displayed there in full length (of 3600 seconds).

Is it possible you'd have to tweak some config parameters to achive this?

Thanks in advance.

**Comment by jacekkolasa** [comment]
Hi @paxsali! Before you click "export", please zoom out the charts (for example by using `-` button on one of the toolboxes), then the visible timeframe should be exported. Please change "seconds per point" slider to store more points. Will that solve your problem?

We'll have date-range-picker soon, zooming out should be easier then. :)

**Comment by jacekkolasa** [comment]
closing but feel free to reopen if you have further questions
