### ISSUE TITLE
dashboard: allow to collapse graphs (per-graph, per-family, etc..)

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#10141]
##### Feature idea summary

In the dashboard, when we have systems with a large number of CPUs (more and more common these days), at least 4 graphs are generated per CPU: utilization, interrupts, softirq, softnet. which can take up to 1/3 a page
Same for disk_mountpoint: 10 graph per filesystem/disk, which fills another 1/3 of a page.

When trying to identify a workload problem, we often need to correlate CPU/Memory/Disk & network. That induces a lot of scroll back & forth to check if the highlighted zone or cursor matches.

With a way to collapse unwanted charts / families, that would allow a smoother analysis / experience (which is always needed during prod troubleshooting).

##### Expected behavior

Have way to quickly collapse a group/family of charts to reduce the noise of chart analysis. 
This collapse should expand when using anchors, so not to break shortcut links.

**Comment by cg-cnu** [comment]
I usually end up creating a custom dashboard for the specific use case, which is pretty easy to get started and faster to load especially when I am working on a custom plugin. But, I agree with you on having the ability to collapse the un necessary stuff. If the hidden/collapsed charts are remembered across sessions it would help in load times as well. Netdata right now takes a decent minute to load all the 1000s of charts on first launch, which is not needed and not a great user experience.

**Comment by cg-cnu** [comment]
> Netdata right now takes a decent minute to load all the 1000s of charts on first launch, which is not needed and not a great user experience.

I felt I need to explain this. Usually netdata is blazing fast, I have it running on my raspberry Pi 4 and zero and the UI is responsive on both the machines in seconds. But at work, where we are on legacy browsers and it takes time. So, its not an issue with netdata but the browser version. But, it would be great, if Netdata have a way to disable/hide certain charts to improve the load times and the performance at the user end. Thanks!

**Comment by Saruspete** [comment]
> > Netdata right now takes a decent minute to load all the 1000s of charts on first launch, which is not needed and not a great user experience.
> I felt I need to explain this. Usually netdata is blazing fast, I have it running on my raspberry Pi 4 and zero and the UI is responsive on both the machines in seconds. But at work, where we are on legacy browsers and it takes time. So, its not an issue with netdata but the browser version. But, it would be great, if Netdata have a way to disable/hide certain charts to improve the load times and the performance at the user end. Thanks!

Sorry to tell that, but this is totally unrelated to the issue here. 
I'm not talking about Rpi toys, but real servers with between 40 and 256 CPUs. Performance is not the issue, it's about the UX during troubleshooting analysis.

If the browsers provided at work are old, just download a newer one: firefox or chrome doesn't need admin rights to install since many years.
By default, netdata will only load & refresh the charts being displayed. If you can't use other browsers, set the parameter "Page scroll handling" to "async", which will only load the charts when scrolling ends. 
All solutions (chart collapse, async scroll) will still need to generate the empty div/canvas in the background at load time (so seems to be your issue), but scrolling will consume less resources.

Cheers,

**Comment by cg-cnu** [comment]
Sorry, I felt like I butted into your conversation. I agree with you. Cheers!

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
