### ISSUE TITLE
Simple way to manage data collecting

### ISSUE THREAD

**Issue by Ansem93** [netdata/netdata#10140]
##### Feature idea summary
Since I need to only monitor some thing on my serve I would like to choose which data will netdata collect and store.
Also it would like to order them

##### Expected behavior
I was thinking about some option:
1) In the settings add a tab where every chart is listed. Something like two columns: on the left the active ones and on the right the disabled ones. From there maybe add the possibility to order them
2) In the home page: add an edit button, when you click it every chart will be paused, an add button will appear (to re-add removed charts) and at the side of every chart there will be a trash button to remove them. Also the possibility move them up and down 

I think that the first option would be easier and cleaner, but I'm not a UI designer so there could be a lot of better option!

**Comment by thiagoftsm** [comment]
Hello @Ansem93 ,

I assignee our product manager to take a look in your request, but while we do not bring this feature for the UI, you can disable `plugins` or some features editing `netdata.conf`.

Best regards!

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
