### ISSUE TITLE
plugins.d: chart `type.id` 200 chars limit 

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#10164]
##### Feature idea summary

From the [external plugins api docs](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#external-plugins-api):

> If a plugin does not behave properly (outputs invalid lines, or does not follow these guidelines), will be disabled by Netdata.

**I think this is ok and should be so**, but sometimes we need to be less strict and don't disable a plugin on any problem.

Disabling a plugin is not good if the plugin is an orchestrator (contains a lot of collectors).

---

There is implicit chart `type.id` length limit (200 chars), see https://github.com/netdata/helmchart/issues/156#issuecomment-718694118

I think we need:
 - document 200 chars limit.
 - don't disable a plugin, but ignore all the charts with `type.id` length > limit.

or

 - document 200 chars limit.
 - disable a plugin, but on creating a chart (`CHART ...`) and with appropriate message.

Optionally: increase the limit?

@netdata/agent

**Comment by mfundul** [comment]
The limit cannot be increased without breaking compatibility with memory modes `map` and `save`.

**Comment by ilyam8** [comment]
Ok, i vote for

> don't disable a plugin, but ignore all the charts with type.id length > limit.

**Comment by ilyam8** [comment]
Back to this, it seems the fastest workaround is to fix this inside go.d.plugin, just not create (CHART ...) charts with len(type.id) >= 200.

**Comment by ilyam8** [comment]
In addition to changes to the go.d.plugin we need to add this to the plugins.d documentation (minor).
