### ISSUE TITLE
Hide "Update now" button

### ISSUE THREAD

**Issue by juanvasquezreyes** [netdata/netdata#10169]
Is there a way to hide the button "update now" without updating the version?

if not, can the check be on until the last number version v1.26.x

This is my current version
Your netdata version: v1.26.0

And this is the version it want me to update to
Latest version: v1.26.0-91-nightly

**Comment by manos-saratsis** [comment]
@juanvasquezreyes There is no configuration for hiding the update button. It will be more subtle in the future. Also we should consider not showing this when the user is on the latest stable.

**Comment by Ferroin** [comment]
@manos-saratsis The fix here is to have the dashboard on stable installs only check against stable versions for updates. I’m not sure how difficult that actually is to achieve though.

**Comment by Saruspete** [comment]
Please bear in mind we also have "system-team managed" versions from the packages (either rebuilt per-use from the scripts, or provided by distributions maintainers). So an option to set in the configuration here would definitively be better.

**Comment by jacekkolasa** [comment]
@manos-saratsis @Ferroin Currently on stable installs we check against newest stable versions. Please correct me if you've seen different behaviour.
