### ISSUE TITLE
Alarm: web log 1m internal errors

### ISSUE THREAD

**Issue by rjbathgate** [netdata/netdata#10173]
#### Question summary  

My "web log 1m internal errors" flagged critical recently.

In the dashboard, the graph shows a big spike in request, with a decent amount of errors (in particular 5xxs). See screenshots attached.

![Netdata-Cloud](https://user-images.githubusercontent.com/14904553/97816553-ed165e80-1cfa-11eb-9c1c-1dfd266909dc.png)
![Netdata-Cloud2](https://user-images.githubusercontent.com/14904553/97816554-ef78b880-1cfa-11eb-81c1-9cea8b13877a.png)

The spike in traffic was expected, but the errors alongside it weren't, so I'm attempted to dig into server logs to see what was going on, however the apache2 error logs `/var/log/apache2/error.log` for the time period are empty.

These are servers I have recently taken over so not famililar if apache2 logs are elsewhere, but all my investigation suggests this is the right place, and the access.log in the same place is collacting correctly.

So, my question, how can I see where NetData is looking for these logs, which are then used in `web log 1m internal errors`.

As 500 Errors in nature might result in a server not responding, such as 504 etc, which, in this case, the server probably isn't responding and therefore isn't logging. **So, how then does NetData get this information?** Perhaps my presumption that it simply looks at the apache error logs is wrong?

And, can I see which specific Error 5xxs NetData is seeing from the Dashboard, rather than just the generic 5xx classification?

Basically, how can I find more information about these Error 5xxs which were recorded?

Alarm Source: 
`301@/usr/lib/netdata/conf.d/health.d/web_log.conf`

##### OS / Environment
```
Linux ip-1xxxxxx 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.3 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.3 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
netdata v1.26.0-77-nightly

##### Component Name
web log 1m internal errors Alarm

**Comment by ilyam8** [comment]
Hi @rjbathgate 

> So, how then does NetData get this information? Perhaps my presumption that it simply looks at the apache error logs is wrong?

No, you are not wrong, `weblog` collector reads log file.

These are predefined `weblog` jobs (if you haven't created your `web_log.conf` that files is use)

See `paths` parameter: 
> https://github.com/netdata/go.d.plugin/blob/70946e7be6e92bca981cfe1112f3c01289bd064a/config/go.d/web_log.conf#L190-L222

One of them is active.

To get which one:
 - cd netdata log dir
 - (as `root`) `> error.log`
 - (as `root`) `systemctl restart netdata.service`
 - `grep web_log error.log` 

---

> And, can I see which specific Error 5xxs NetData is seeing from the Dashboard, rather than just the generic 5xx classification?

Yeah, see the chart right below `Request By Type` chart, it is on your screenshot - `Server Error Responses By Status Code` (they are `500` in your case).

---

> In the dashboard, the graph shows a big spike in request, with a decent amount of errors (in particular 5xxs).

To be honest not really decent if we count their number - it is 2 `500` responses per second.

The alarm

https://github.com/netdata/netdata/blob/c7b4218826d7cee089eaa4d5c5cbf93d34de857f/health/health.d/web_log.conf#L301-L312

Perhaps the alarm is to strict 🤔

**Comment by rjbathgate** [comment]
> See paths parameter:
> https://github.com/netdata/go.d.plugin/blob/70946e7be6e92bca981cfe1112f3c01289bd064a/config/go.d/web_log.conf#L190-L222

This references `/var/log/apache2/access.log` - not the error.logs, and the 500 errors in question won't be stored in the access.log, but rather the error log.

So, following the same path, `/var/log/apache2/error.log` is, as mentioned, empty. All error.log archives in here are all but empty.

> cd netdata log dir
> (as root) > error.log
> (as root) systemctl restart netdata.service
> grep web_log error.log

Sorry but not clear what you're suggesting with that - can you elaborate?

> Perhaps the alarm is to strict thinking
I appreciate 2 a second isn't huge, but it's 2 too many when it comes to a 500 error, and ultiamtely I need to find the log files Netdata is getting this data from (even if it's just two), so I can dig deeper.

**Comment by ilyam8** [comment]
Ok, there are some debug messages about log file during format autodetection

https://github.com/netdata/go.d.plugin/blob/1cfb9a649aa805654c61ee80ce54d4f3c23a5a97/modules/weblog/init.go#L101-L137

Try debug mode

> https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#troubleshooting
