### ISSUE TITLE
statsd_process() in dead loop

### ISSUE THREAD

**Issue by luokaink** [netdata/netdata#10176]
##### Bug report summary
static inline size_t statsd_process(char *buffer, size_t size, int require_newlines);
if buffer is ":", this function will never end.

I do not know why the buffer is ":" and it only happens on virtual machines. Anyway, there is a definitely bug in function statsd_process().

**Comment by ilyam8** [comment]
@luokaink thx for reporting the bug!

**Comment by OdysLam** [comment]
@luokaink Thanks for reporting this bug and welcome to our community. Actually, this is very awesome, as you not only pointed out the bug but knew exactly what was it. 

We would love to have your expert voice in our community forums: https://community.netdata.cloud 🚀
