### ISSUE TITLE
Set alarm URL, or make it redirect to host

### ISSUE THREAD

**Issue by fayak** [netdata/netdata#10174]
##### Question summary

I have hundreds of netdata agents monitoring an infrastructure. I also configured one to be a registry, and all the nodes announce this node as the registry. When an alarm is triggered on Slack, I have 3 links:

![netdata](https://user-images.githubusercontent.com/11300056/97859649-35387f80-1d01-11eb-8c0d-729119a54fb6.jpg)

1. is a link to the node triggering the alert FQDN, without the port
2. is a link to the registry trying to redirect me to the triggering node
3. is the same as n1

The thing is, link 1 doesn't work because it omits `:19999` (I don't want netdata to be accessible on `:80`) and I don't know how to fix it.
Link 2 doesn't work either because I never visited the triggering node before. 
```
Sorry... your account is not linked to a netdata server named: node01-qa3-...
```

If I manually visit the node, then link n2 works.

I'd like to:
- Know how to configure link n1 to include the node's port
- Know how to be automatically redirected on link n2 without prior visit to the node
- Maybe make a link to the node on the `Sorry... your account is not linked to a netdata server` page to the node (with its port)

I have hundreds of node, and I can't ask all the people in the company to visit each node, they'd like a direct working link when there's an issue.

I've payed attention to some other issues opened here (like #6975 #7646), but I couldn't find the answers I need.

Is it achievable ? Have I missed something ?

Thanks for your help !

##### OS / Environment

Debian, netdata v1.26.0 installed through apt repo

**Comment by manos-saratsis** [comment]
@fayak Thanks for using Netdata! These problems will not exist in Cloud as we will soon offer centralized dispatch of alarm notifications from Cloud. Initially we will offer notifications via emails to the users of the space and within the next months we will add other integrations like Slack. The metric data will remain in your servers as we do not store metric data in Cloud. Also you will be able to troubleshoot across your entire infrastructure and use features like the new Overview with composite charts (multiple hosts participate there), metric correlations and dashboards.

If you still insist on using the current setup, please let us know and we will try to help.

**Comment by fayak** [comment]
Hi @manos-saratsis !

Thanks for your response. I'm not sure our company will be comfortable using Netdata's cloud features, even it does not store our monitoring data. To be honest, I don't understand quite well the value added by Netdata's cloud that cannot be performed in a self hosted solution.

I think I'll fix it temporarily with this patch for the moment:
```
diff --git a/web/gui/goto-host-from-alarm.html b/web/gui/goto-host-from-alarm.html
index 7d12f848..fbf7debf 100644
--- a/web/gui/goto-host-from-alarm.html
+++ b/web/gui/goto-host-from-alarm.html
@@ -227,6 +227,7 @@ var netdataRegistryCallback = function(machines_array) {
     }
 
     document.getElementById('bodylog').innerHTML = "Sorry... your account is not linked to a netdata server named: <b>" + escapeUserInputHTML(urlOptions.host) + '</b>';
+    document.location.replace("http://" + netdataURL(urlOptions.host + ":19999"));
 };
 
 netdataQueryParse();
```

which does exactly what I want. I'm not sure how to apply it automatically without breaking anything in future release/modification of this page

**Comment by fayak** [comment]
I'll go with this ansible task:
```
- name: Set Netdata automatic redirection when clicking on an alert link
  lineinfile:
    create: no
    insertafter: "your account is not linked to a netdata server named"
    line: '    document.location.replace("http://" + netdataURL(urlOptions.host + ":19999"));'
    path: "/var/lib/netdata/www/goto-host-from-alarm.html"
```

We'll see how it performs :man_shrugging:
