### ISSUE TITLE
Cloudflare and Netdata - increase in Error 521 (site down)

### ISSUE THREAD

**Issue by rjbathgate** [netdata/netdata#10182]
##### Question summary

For the last 6 months, all my domains have been running through CloudFlare, with no problems whatsoever.

Last week I installed Netdata on the web servers these domains point to.

Since then, I have experienced a large number of Error 521 (Web Service Down).

https://community.cloudflare.com/t/community-tip-fixing-error-521-web-server-is-down/42461
```
A 521 error happens when we are unable to make a TCP connection to your origin server. Specifically, Cloudflare tried to connect to your origin server on port 80 or 443, but received a connection refused error. This is often caused by security or firewall software and happens if the origin server has directly refused Cloudflare’s proxy request.
```

I don't beleive it's a conindence as we've gone from no Error 521s in about 6 months to at least one a day, and the same behaviour on three servers.

When a site is in this state, it can be intermittant; i.e. I receive the error, but can see from analytics some users are still on the site.

If I turn CloudFlare off temporarily, it's accesible again, and there is no indication from the Netdata stats of anything untoward going on like CPU overloads etc

My initial thoughts are:
- Running Netdata has added some resource consumption
- The server therefore is closer to redlining at anypoint
- Therefore Error 521s are more likely.

However, without CloudFlare on, things are back to normal.

Could it be:
- Running Netdata has added some resource consumption
- The server therefore is closer to redlining at anypoint
- CloudFlare has a very sensitive 'up check' and Netdata running has resulted in a slightly slower response time (????) (this is a guess as to what's going on)
- Therefore Error 521s from CloudFlare are more likely

Is anything Netdata is doing likely to result in CloudFlare seeing the server as inaccessible?

Is it common to experience a server slow down which accects production from installing NetData? If so, is there anything I can do to reduce this, such as decrease global update frequency? Otherwise it looks like the onlu solution is to stop using netdata, but I don't beleive that should be neccassary as obviously many people out there have no problems.

##### OS / Environment
```
Linux ip-1xxxxxx 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.3 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.3 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
netdata v1.26.0-77-nightly

##### Component Name
Netdata service itself, and CloudFlare

##### Expected results
No increase in Web Server Errors with the installation of Netdata.

**Comment by ilyam8** [comment]
Hi

> Last week I installed Netdata on the web servers these domains point to.
> Since then, I have experienced a large number of Error 521 (Web Service Down).

I don't think it is Netdata related, but it is easy to check - enable/disable `netdata.service` and check the errors.
