### ISSUE TITLE
Libreswan Plugin: doesn't track traffic/uptime and check function fails

### ISSUE THREAD

**Issue by wash2** [netdata/netdata#10188]
##### Doesn't track traffic/uptime
The charts.d Libreswan plugin doesn't properly parse `add_time`, `inBytes`, and `outBytes` from `ipsec whack --trafficstatus`. This causes the graphs in the dashboard to have no data for the libreswan plugin.

There is an extraneous comma at line 81, character 45, in `/usr/libexec/netdata/charts.d/libreswan.chart.sh` that prevents the regex from matching the output of `ipsec whack --trafficstatus`

_not working_
```shell
  source <(
    {
      libreswan_ipsec whack --status
      libreswan_ipsec whack --trafficstatus
    } | sed -n \
      -e "s|[0-9]\+ #\([0-9]\+\): \"\(.*\)\".*IPsec SA established.*newest IPSEC.*|libreswan_connected_tunnels[\"\1\"]=\"\2\"|p" \
      -e "s|[0-9]\+ #\([0-9]\+\): \"\(.*\)\",.* add_time=\([0-9]\+\),.* inBytes=\([0-9]\+\),.* outBytes=\([0-9]\+\).*|libreswan_traffic_in[\"\1\"]=\"\4\"; libreswan_traffic_out[\"\1\"]=\"\5\"; libreswan_established_add_time[\"\1\"]=\"\3\";|p"
  ) || return 1

```

_working for me_
```shell
  source <(
    {
      libreswan_ipsec whack --status
      libreswan_ipsec whack --trafficstatus
    } | sed -n \
      -e "s|[0-9]\+ #\([0-9]\+\): \"\(.*\)\".*IPsec SA established.*newest IPSEC.*|libreswan_connected_tunnels[\"\1\"]=\"\2\"|p" \
      -e "s|[0-9]\+ #\([0-9]\+\): \"\(.*\)\".* add_time=\([0-9]\+\),.* inBytes=\([0-9]\+\),.* outBytes=\([0-9]\+\).*|libreswan_traffic_in[\"\1\"]=\"\4\"; libreswan_traffic_out[\"\1\"]=\"\5\"; libreswan_established_add_time[\"\1\"]=\"\3\";|p"
  ) || return 1

```

-e "s|[0-9]\+ #\([0-9]\+\): \"\(.*\)\"**====COMMA REMOVED HERE====**.* add_time=\([0-9]\+\),.* inBytes=\([0-9]\+\),.* outBytes=\([0-9]\+\).*|libreswan_traffic_in[\"\1\"]=\"\4\"; libreswan_traffic_out[\"\1\"]=\"\5\"; libreswan_established_add_time[\"\1\"]=\"\3\";|p"

##### Check function fails
The libreswan check function fails because of mutliple permission errors despite following the steps in the [libreswan plugin documentation](https://learn.netdata.cloud/docs/agent/collectors/charts.d.plugin/libreswan). This causes the libreswan plugin to be automatically disabled until netdata is restarted, and the libreswan plugin isn't rendered in the dashboard.
What fixed this issue for me was adding the following to `/etc/systemd/system/multi-user.target.wants/netdata.service` but I don't think this was the best approach.
```
# is required for libreswan plugin
CapabilityBoundingSet=CAP_SETGID
CapabilityBoundingSet=CAP_SETUID
CapabilityBoundingSet=CAP_AUDIT_WRITE
```

##### OS / Environment

```
Linux atg11vpn1 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.8 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.8"
/etc/os-release:PRETTY_NAME=OpenShift
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
/etc/os-release:HOME_URL="https://www.redhat.com/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.8"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.8 (Maipo)
/etc/system-release:Red Hat Enterprise Linux Server release 7.8 (Maipo)
```
this is running on a VM, and the output of `ipsec--version` is
`Linux Libreswan 3.25 (netkey) on 3.10.0-1127.19.1.el7.x86_64`
##### Netdata version

 netdata v1.26.0

##### Component Name

collectors

##### Steps To Reproduce

1. bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel --disable-telemetry
2. yum -y install libreswan
3. ipsec --version
`Linux Libreswan 3.25 (netkey) on 3.10.0-1127.19.1.el7.x86_64`
4. add client connection
5. send traffic over ipsec tunnel
6. navigate to libreswan plugin view in the netdata dashboard

##### Expected behavior

The libreswan check function should not fail because of permission errors for users who have followed the steps in the documentation, and the traffic/uptime should be parsed from `ipsec whack --trafficstatus`

**Comment by ilyam8** [comment]
Hi, yeah, we have problems with all the collectors that use `sudo` since we _hardened_ netdata systemd unit file 😅

Related PR https://github.com/netdata/netdata/pull/10088 / issue https://github.com/netdata/netdata/pull/10088

So the solution is to guess/find missed capability or unset [CapabilityBoundSet](https://github.com/netdata/netdata/issues/10079#issuecomment-720983709).

**Comment by ilyam8** [comment]
If it is only comma then let's make it optional (`.?`). Are you willing to make a PR?

btw very nice bug report summary @wash2 👍

**Comment by wash2** [comment]
Sure I'll make a PR that makes the comma optional. And thanks :).

**Comment by ilyam8** [comment]
The issue with permissions (`CapabilityBoundingSet`)/documentation is not resolved. @Ferroin what do we do? Are you ok with adding 

```cmd
# is required for libreswan plugin
CapabilityBoundingSet=CAP_SETGID
CapabilityBoundingSet=CAP_SETUID
CapabilityBoundingSet=CAP_AUDIT_WRITE
```

?
