### ISSUE TITLE
Option `--build-judy` on FreeBSD `12.2`

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#10195]
##### Bug report summary
When I tried to use `--build-judy` on FreeBSD 12.2 I had the following problems that did not allow me to use `dbengine` with FreeBSD:

1 - I had to install `libtool` that was not installed after I upgrade
2 - On FreeBSD I cannot finish the compilation thanks these [errors](https://github.com/netdata/netdata/files/5487805/files.zip)

##### OS / Environment
```
FreeBSD freebsd 12.2-RELEASE FreeBSD 12.2-RELEASE r366954 GENERIC  amd64
1202000
```

##### Netdata version
v1.26.0-116-gaeff0ced7
 

##### Component Name
Packaging

##### Steps To Reproduce
1. Compile on FreeBSD12.2 Netdata with the flag `--build-judy`: 

```
# ./netdata-installer.sh --dont-wait --build-judy --install /usr/local 
```

##### Expected behavior
To be able compiling Netdata using the new available option.

**Comment by mfundul** [comment]
I don't really see the errors in the attached file, but I do see the use of libasan and ebpf. You should remove all those extra flags for FreeBSD.

**Comment by thiagoftsm** [comment]
@mfundul , please , take a look at `err` file:

```
[/tmp/netdata-judy-XXXXXX.t4MujlK0/libjudy-1.0.5-netdata2]# env CFLAGS= CXXFLAGS= LDFLAGS= automake --add-missing --force --copy --include-deps 
configure.ac:7: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:7: https://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.ac:147: installing './compile'
configure.ac:238: installing './config.guess'
configure.ac:238: installing './config.sub'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
src/Judy1/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Judy1/Makefile.am: installing './depcomp'
src/JudyCommon/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/JudyHS/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/JudyL/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/JudySL/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am:1: warning: naming a subdirectory 'obj' causes troubles with BSD make
parallel-tests: installing './test-driver'
tool/Makefile.am:1: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
 OK   

[/tmp/netdata-judy-XXXXXX.t4MujlK0/libjudy-1.0.5-netdata2]# env CFLAGS= CXXFLAGS= LDFLAGS= autoconf 
 OK   

[/tmp/netdata-judy-XXXXXX.t4MujlK0/libjudy-1.0.5-netdata2]# env CFLAGS= CXXFLAGS= LDFLAGS= ./configure 
 OK   

[/tmp/netdata-judy-XXXXXX.t4MujlK0/libjudy-1.0.5-netdata2]# env CFLAGS= CXXFLAGS= LDFLAGS= make -C src 
libtool:   error: '../JudyCommon/*.lo' is not a valid libtool object
 FAILED   

 FAILED  Failed to build libJudy. 
```

**Comment by rcmelendez** [comment]
Hey @thiagoftsm 
I had the same error on the same FreeBSD version as well. I had to install Judy via `sudo pkg install Judy` and then create symbolic links because the netdata installer script was looking for Judy libraries in `/usr/lib` and `/usr/include` and the FreeBSD package manager installed them in `/usr/local/lib` and `/usr/include`. It worked for me:

```
/usr/include/Judy.h -> /usr/local/include/Judy.h
/usr/lib/libJudy.a -> /usr/local/lib/libJudy.a
/usr/lib/libJudy.so -> /usr/local/lib/libJudy.so
/usr/lib/libJudy.so.1 -> /usr/local/lib/libJudy.so.1
/usr/lib/libJudy.so.1.0.3 -> /usr/local/lib/libJudy.so.1.0.3
```

**Comment by thiagoftsm** [comment]
Thank you for your update @rcmelendez !
@Ferroin , we had issues like this reported when Netdata is compiled on PFsense, probably we need to take a look at FreeBSD installation process.

**Comment by Ferroin** [comment]
Can we get confirmation of whether this is still an issue or not, and if not close it?

**Comment by thiagoftsm** [comment]
@Ferroin I will test it and if the problem is fixed, I will close it.

**Comment by thiagoftsm** [comment]
I tested now on `FreeBSD 13.0-RELEASE-p11` and I observed the problem was fixed.

@rcmelendez I am going to close this issue, but if you still have the issue, please, let us know for we reopen and fix.
