### ISSUE TITLE
De-claim node via command line

### ISSUE THREAD

**Issue by DonZheng** [netdata/netdata#10191]
##### Feature idea summary
De-claiming node from cloud waroom via command line. i.e. 
`sudo netdata-declaim.sh -token=<token> -rooms=<roomid> -url=https://app.netdata.cloud`

At the moment, operator can remove node from waroom manually on netdata.cloud. This cannot scale well. In case of managing large server pool where add/delete server operations are frequent, a command line option will be very useful for automation purposes.

##### Expected behavior
`sudo netdata-declaim.sh -token=<token> -rooms=<roomid> -url=https://app.netdata.cloud`
`DECLAIM SUCCESS`
or
`ERROR: #$%^&*(`

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
