### ISSUE TITLE
TrueNAS (FreeBSD) auto update does not work

### ISSUE THREAD

**Issue by abrbon** [netdata/netdata#10198]
On my TrueNAS 12 server (based on FreeBSD) the auto-update does not work.

If i run the "/etc/periodic/daily/netdata-updater" script manually it does work fine altough i have to answer 1 question during the script with "Y" (or "N") before it can continue and finish the update.

`[/tmp/netdata-updater-XXXXXXXXXX.SxF11L2O/netdata-v1.26.0]# mv go.d.plugin-v0.23.0.freebsd-amd64 /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin
override rwxr-x---  root/netdata for /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin? (y/n [n])`

I have checked if the netdata-updater actually runs via cron by editing the netdata-updater script with a simple 
1 line code "touch /root/test-netdata-updater-cron.txt" and ran the 'periodic daily' command to force the cron to 
execute the daily scripts and the test-netdata-updater-cron.txt is created in my /root/ folder as intended.

But i can not find any logs or anything why the netdata-updater script does not work.

I have created a new jail on TrueNAS and installed netdata v1.25 from source inside this new jail.

Any ideas?

**Comment by Ferroin** [comment]
Most likely cause is a difference between GNU and FreeBSD userspace. I’ll try to make a point to look into this further either later today or early tomorrow.

**Comment by ilyam8** [comment]
Default is no confirmation, `mv` asks on overwriting only when it is explicitly called with `-i` option. Same behavior for both GNU and bsd versions ([a funny related topic](https://forums.freebsd.org/threads/prompt-confirmation-y-n-to-move-a-file.70676/)).

**Comment by ilyam8** [comment]
Likely not, but i have only this in mind - could it be an alias?

**Comment by Ferroin** [comment]
It might be an alias, but I would be rather surprised if that was leaking into a shell script. Aliases should be defined in the profile files, not the shell rc files, and thus should not be visible in shell scripts.

**Comment by abrbon** [comment]
I don't think it's an alias issue because there is a second 'mv' command i can see in the installer log which did not ask for confirmation during install.

`[root /root/netdata-v1.25.0]# mv go.d.plugin-v0.22.0.freebsd-amd64 /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin  ... OK
[root /root/netdata-v1.25.0]# chown root:netdata /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin  ... OK
[root /root/netdata-v1.25.0]# chmod 0750 /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin  ... OK
[root /root/netdata-v1.25.0]# touch /usr/local/netdata/etc/netdata/.opt-out-from-anonymous-statistics  ... OK
[root /root/netdata-v1.25.0]# cp system/netdata-freebsd /etc/rc.d/netdata  ... OK
[root /root/netdata-v1.25.0]# stop_all_netdata  ... OK
[root /root/netdata-v1.25.0]# service netdata onestart  ... [root /root/netdata-v1.25.0]# /usr/sbin/service netdata onestart  ... OK
OK
[root /root/netdata-v1.25.0]# curl -sSL --connect-timeout 10 --retry 3 http://localhost:19999/netdata.conf  ... OK
[root /root/netdata-v1.25.0]# mv /usr/local/netdata/etc/netdata/netdata.conf.new /usr/local/netdata/etc/netdata/netdata.conf  ... OK
`

**Comment by abrbon** [comment]
I think i found the problem in the netdata-updater.sh script.
It is in the random sleep function : 

```
# Random sleep to aileviate stampede effect of Agents upgrading
# and disconnecting/reconnecting at the same time (or near to).
# But only we're not a controlling terminal (tty)
# Randomly sleep between 1s and 60m
if [ ! -t 1 ] && [ -z "${NETDATA_NOT_RUNNING_FROM_CRON}" ]; then
  sleep $(((RANDOM % 3600) + 1))s
fi
```
The problem is the 's' on the end of the 'sleep ...' line.
FreeBSD does not expect a 's' on the end.
It should always be in seconds.
Simply removing the 's' at the end of the line seems to solve the problem in my case.

**Comment by abrbon** [comment]
With the little bit of bash scripting knowledge i have i made the following changes to the 'netdata-updater.sh' file to make this work on my FreeBSD install on TrueNAS.

```
# Random sleep to aileviate stampede effect of Agents upgrading
# and disconnecting/reconnecting at the same time (or near to).
# But only we're not a controlling terminal (tty)
# Randomly sleep between 1s and 60m
if [ ! -t 1 ] && [ -z "${NETDATA_NOT_RUNNING_FROM_CRON}" ]; then
        if [ "$(uname -s)" = "FreeBSD" ]; then 
                sleep `jot -r 1 1 3600`
        else
                sleep $(((RANDOM % 3600) + 1))s
        fi
fi
```

**Comment by Ferroin** [comment]
Confirmed, that is indeed the issue.

@abrbon Would you be willing to open a PR with your changes? I can do so instead if you want, but I’d much rather you got the credit for the fix since you were the one who figured it out.

**Comment by abrbon** [comment]
> Confirmed, that is indeed the issue.
> 
> @abrbon Would you be willing to open a PR with your changes? I can do so instead if you want, but I’d much rather you got the credit for the fix since you were the one who figured it out.

Thx Ferroin, i created my very first PR today :)
Hope i have done it correctly. Let me know if not.
