### ISSUE TITLE
feature: make charts legend position configurable via gui

### ISSUE THREAD

**Issue by Roki100** [netdata/netdata#10208]
Hello! i have upgraded my netdata from 1.14 to 1.26 and i really hate the recent 1.26 change that brings the labels on the bottom instead of the right, and i have a question if there is any possibility to bring the "normal" look back without downgrading? if no, how i can downgrade to the latest version that includes the better look?

**Comment by nurlennart** [comment]
+1

**Comment by F-He** [comment]
Agreed, an option to switch back to the "normal" design would be nice.

**Comment by manos-saratsis** [comment]
@Roki100 thx for your feedback. Moving forward we will do more changes on the charts. Regarding the dimensions at the bottom of the chart we want to offer a setting so you can place them on the right hand side Cc @jacekkolasa

**Comment by jacekkolasa** [comment]
@manos-saratsis maybe we could put this setting to Dashboard Options? I was thinking that we could remove "Enable data padding when panning and zooming?" setting (i think it has very insignificant impact) and put legend-position in that place?

**Comment by aldem** [comment]
In the meantime - is there any way to get it back by editing some configuration file or dashboard source (without recompiling anything) or downgrading is the only option?

To be honest, changes like this without any option to preserve old look and feel are quite inconvenient - and this was really significant change. Reading new bottom placed legends is very difficult to compare values, and takes significantly more time while right-side placement provides almost instantly the complete overview (especially for many values).

**Comment by jacekkolasa** [comment]
We will add this option soon, until then there is unfortunately no way to hack around... You can only revert to older dashboard version by modifying `packaging/dashboard.checksums` and `...version` files as they were before this change - https://github.com/netdata/netdata/commit/db02098d667569438615de721c42d288f4199065

But that will unfortunately remove date-picker as well.

**Comment by nikooo777** [comment]
hey guys, I'm just chiming in to also say that the legend moving to the bottom is really making charts harder to read. I really hope a configuration option comes in as soon as possible, I'd have to be forced to rollback.

Best regards

**Comment by jacekkolasa** [comment]
Option has been added and will land on Tuesday in stable release. Thanks everyone for your opinion and votes!
