### ISSUE TITLE
convert kilo to megabytes

### ISSUE THREAD

**Issue by free514** [netdata/netdata#10209]
how change diplay kilobytes to megabytes
in cloud netdata

http://prntscr.com/vf7qmj

**Comment by free514** [comment]
any update?

**Comment by rigas40** [comment]
maybe script

**Comment by vlvkobal** [comment]
Please look at a relevant [comment](https://community.netdata.cloud/t/change-chart-resolution-for-ntpd-plugin/1411/4) at Netdata community forum.
