### ISSUE TITLE
netdata 1.26 rpm contain a empty ebpf.plugin

### ISSUE THREAD

**Issue by kjellgren** [netdata/netdata#10200]
##### Bug report summary
RPM for netdata 1.24 install file `/usr/libexec/netdata/plugins.d/ebpf.plugin` that is working fine but when I use the RPM for 1.26 I get an empty file (that do not work).

##### OS / Environment
RHEL (RedHat) 7.9

##### Netdata version
1.26.0 

##### Component Name
ebpf

##### Steps To Reproduce
Install netdata-1.26.0-1.el7.x86_64.rpm

**Comment by Saruspete** [comment]
Hello,

From the package name, it seems to be coming from EPEL, not netdata upstream.
I think the EPEL specfile for Centos7 is here: https://src.fedoraproject.org/rpms/netdata/blob/epel7/f/netdata.spec which does not provide the ebpf plugin.
Compare it to our official specfile which conditionally includes ebpf if the required packages are installed on the system (and is not explcitely disabled from ./configure step):  https://github.com/netdata/netdata/blob/master/netdata.spec.in

So you can either :
- ask epel for support of ebpf
- use our installer script to have "out-of-rpm" but more widely supported
- use the `contrib/rhel/build-netdata-rpm.sh` script to build it according to your needs (that what I do for my prod)

Cheers

**Comment by kjellgren** [comment]
Hello,
I download the RPM file from [packagecloud.io](https://packagecloud.io/netdata/netdata/packages/el/7/netdata-1.26.0-1.el7.x86_64.rpm)

**Comment by thiagoftsm** [comment]
@Ferroin , please, can you take a look on this when you have a time.

**Comment by pdgaaa** [comment]
Hi,
I just installed last version from packagecloud 1.31.0 on RHEL 7.9 (kernel options for BPF are good) and I haven't the ebpf plugin, directory /usr/libexec/netdata/plugins.d/ebpf.d/ does not exist.

Is there somewhere the logs of the package build ?

Could we change the title of this issue as it concern netdata rpm not specificaly 1.26 ?

Regards
