### ISSUE TITLE
Create a new "shared" dimension for "System RAM" chart

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#10206]
##### Feature idea summary
Create a new "shared" dimension for "System RAM" chart.
See the discussion [here](https://github.com/netdata/netdata/issues/10153#issuecomment-720444099) for more details.

**Comment by vlvkobal** [comment]
The changes have been prepared, but in a discussion with @ilyam8 we decided that separating shared memory creates more problems than benefits. Especially it affects alarms, where we have to treat shared memory as used so in all places calculations should contain `$used + $shared`.

The change won't be implemented. I'm closing the issue.
