### ISSUE TITLE
Issue Installing & Subsequently Updating Netdata

### ISSUE THREAD

**Issue by ilyesm** [netdata/netdata#10219]
##### Bug report summary
When I tried to install Netdata, the kickstart installation script had a fatal error and made the OS crash. After a couple tries, the install went through, but when I try to run the kickstart script to update the installation, the same crash happens. The crash always happens after the following verbose log:

`make[2]: Entering directory '/tmp/netdata-updater-cFg09QMcxy/netdata-v1.26.0-152-g3d6f47f9'
  CC       libnetdata/os.o
  CC       web/api/formatters/json_wrapper.o
  CC       web/api/formatters/charts2json.o
  CC       web/api/formatters/rrdset2json.o`

##### OS / Environment

```
Linux rpi-docker 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version
netdata v1.26.0-147-nightly
 

##### Component Name
One Click Kickstart Script

##### Steps To Reproduce
1. Run bash <(curl -Ss https://my-netdata.io/kickstart.sh)
2. Let the script run until:

`make[2]: Entering directory '/tmp/netdata-updater-cFg09QMcxy/netdata-v1.26.0-152-g3d6f47f9'
  CC       libnetdata/os.o
  CC       web/api/formatters/json_wrapper.o
  CC       web/api/formatters/charts2json.o
  CC       web/api/formatters/rrdset2json.o`

##### Expected behavior
The script stops, and the SSH connection to the machine is dropped. Seeing the Netdata CPU and RAM charts when this happens, there is a break in the data, and then a sudden spike in the CPU usage and RAM usage, and another break in the data while the Raspberry Pi restarts.

**Comment by stelfrag** [comment]
Wow this one fell between the cracks @ilyesm did you manage to install ?

**Comment by ilyam8** [comment]
Closing due to no response. The OS crash may be due to a bad SD card. @ilyesm, if you still have a problem when installing Netdata, please let us know.
