### ISSUE TITLE
Doesnt see all slaves on master

### ISSUE THREAD

**Issue by badkaktus** [netdata/netdata#10212]
##### Question summary
I have 7 servers with netdata. 1 of them - master, other 6 is slaves. Netdata version - 1.23.2. When i started service, i see on master only 5 servers (1 master and random 4 slaves). After every restart i saw random servers. Why i doesn't see all slaves?

Master settings:
`cat /etc/netdata/netdata.conf`
```
# global netdata configuration
[global]
        stock config directory = /etc/netdata/conf.d
dbengine multihost disk space = 3032
memory mode = dbengine
page cache size = 32
[web]
        web files owner = tools
        web files group = tools
#       bind to = localhost

[health]
        stock health configuration directory = /etc/netdata/conf.d/health.d
```

Slaves settings:
`cat /etc/netdata/netdata.conf`
```
# global netdata configuration
[global]
        stock config directory = /etc/netdata/conf.d
# disable the local database
        memory mode = none

[web]
        web files owner = root
        web files group = root
        bind to = localhost

[health]
#       stock health configuration directory = /etc/netdata/conf.d/health.d
# disable health checks
    enabled = no
```
and i try this
```
# global netdata configuration
[global]
        stock config directory = /etc/netdata/conf.d
        # disable the local database
        memory mode = none
[web]
        web files owner = root
        web files group = root
        bind to = localhost

[health]
        enabled = no
        stock health configuration directory = /etc/netdata/conf.d/health.d

#[plugins]
#       web_log = yes
```

##### OS / Environment
CentOS 7
Netdata 1.23.2

##### Expected results
I want to see all servers :)

**Comment by stelfrag** [comment]
@badkaktus can we see what is happening in the parents error.log after it is restarted as the children try to connect?

**Comment by thiagoftsm** [comment]
Hello @badkaktus ,

Another suggestion, I observed you are using the version `1.23.2`, and we are actually working with Netdata `1.26`, if it is possible, please, try to update your Netdata.

Best regards!

**Comment by badkaktus** [comment]
> 
> 
> @badkaktus can we see what is happening in the parents error.log after it is restarted as the children try to connect?

Here 2 log-files
[error_slave04.log](https://github.com/netdata/netdata/files/5523107/error_slave04.log)
[error_master.log](https://github.com/netdata/netdata/files/5523108/error_master.log)

error_master.log - its parents error.log. _server-dts02_ - its master server, other - slaves.

error_slave04.log - log-file from server, cannot connect to parent



> 
> 
> Hello @badkaktus ,
> 
> Another suggestion, I observed you are using the version `1.23.2`, and we are actually working with Netdata `1.26`, if it is possible, please, try to update your Netdata.
> 
> Best regards!

unfortunately, the servers are located inside the corporate network and do not have access to the external network. Updates come only from the internal EPEL repository, which is not updated very quickly. 1.23.2 its latest version right now in that repo.

**Comment by stelfrag** [comment]
Hi @badkaktus, sorry for the delayed response

The `error_master.log` file ends at `12:00` and so there is no way to check what happened at

```
2020-11-11 12:07:07: netdata INFO  : STREAM_SENDER[server-dts04.company.corp.net] : STREAM server-dts04.company.corp.net [send to dtstb.company.corp.net:19999]: connecting...`
2020-11-11 12:07:07: netdata INFO  : STREAM_SENDER[server-dts04.company.corp.net] : STREAM server-dts04.company.corp.net [send to dtstb.company.corp.net:19999]: connecting...
2020-11-11 12:07:07: netdata INFO  : STREAM_SENDER[server-dts04.company.corp.net] : STREAM server-dts04.company.corp.net [send to dtstb.company.corp.net:19999]: initializing communication...
2020-11-11 12:07:07: netdata INFO  : STREAM_SENDER[server-dts04.company.corp.net] : STREAM server-dts04.company.corp.net [send to dtstb.company.corp.net:19999]: waiting response from remote netdata...
2020-11-11 12:07:07: netdata ERROR : STREAM_SENDER[server-dts04.company.corp.net] : STREAM server-dts04.company.corp.net [send to dtstb.company.corp.net:19999]: server is not replying properly (is it a netdata?).
```

when the child tried to connect. 

Could you also share the `stream.conf` for the parent and children?

**Comment by badkaktus** [comment]
Sorry for delay.

All external info in attachments:
[conf.zip](https://github.com/netdata/netdata/files/5608184/conf.zip)
[error_slave04.log](https://github.com/netdata/netdata/files/5608185/error_slave04.log)
[error_master.log](https://github.com/netdata/netdata/files/5608186/error_master.log)

**Comment by badkaktus** [comment]
@stelfrag i added info. thanks

**Comment by stelfrag** [comment]
Hi @badkaktus 

I am sorry for the delay in getting back to you. What I noticed in the configuration that you sent is for the api key

`ccd15cd2-dbc3-4ed1-b5a2-8b55c3ce3b6d`

The corresponding section on the parent node is not enabled 
```
# mgts-server04 DMZ
[ccd15cd2-dbc3-4ed1-b5a2-8b55c3ce3b6d]
    # enable/disable this API key
    enabled = no

    # one hour of data for each of the slaves
    default history = 3600

    # do not save slave metrics on disk
    default memory = ram

    # alarms checks, only while the slave is connected
    health enabled by default = auto
```

can you change that line to  `enabled = yes` and retry?

**Comment by stelfrag** [comment]
Hi @badkaktus 

Did you manage to get this working?
