### ISSUE TITLE
build netdata for macOS from source fails

### ISSUE THREAD

**Issue by AWHubGit** [netdata/netdata#10213]
I tried to build netdata for macOS exactely as per
https://learn.netdata.cloud/docs/agent/packaging/installer/methods/macos#install-netdata-from-source
sudo ./netdata-installer.sh --libs-are-really-here --require-cloud --install /usr/local

Build fails: configure: error: User required agent-cloud-link but it can't be built!
.../lib/mosquitto.c:59:10: error: implicit declaration of function 'mach_absolute_time' is invalid in C99

Installed the Judy library before proceeding compiling Netdata successfully, but then /usr/include/Judy.h doesn't exist building own copy. env: libtoolize: No such file/directory. Failed to build libJudy.

This replies to "anyone wishing to connect macOS hosts via a Netdata Agent connected to Netdata Cloud can do so by building from source without problems!!!!"

_Originally posted by @AWHubGit in https://github.com/netdata/netdata/issues/9061#issuecomment-723662554_

**Comment by OdysLam** [comment]
Hey @AWHubGit,

We are sorry that you encountered this and welcome to our community!

We are working on it. Can you please tell us the OS version that you are using?

Best,
Odysseas

**Comment by AWHubGit** [comment]
macOS 10.15.7 (19H15).

**Comment by Kyngo** [comment]
@AWHubGit I'm having the same problem here, with the same version of OSX. How did you install libJudy?

**Comment by AWHubGit** [comment]
I followed the instrucs here
[netdata macOS](https://github.com/netdata/netdata/blob/master/packaging/installer/methods/macos.md)
Therein is written to install judy library. Downloaded judy-1.0.5 from sourceforge and did usual as per readme ./configure, make check, make install. No errors when compiling.

**Comment by 42Network** [comment]
I have similar problem building on macOS. I got Judy to work, but not mosquito. See #10137.

**Comment by OdysLam** [comment]
Although this is not a solution at all, can I suggest to use docker?  I know that docker runs inside a VM on macos, so I am not sure what system metrics it will have access to, but if you want to use it for application monitoring, it will be able to function without a problem, *I think*.

Installation instructions: https://learn.netdata.cloud/docs/get

**Comment by stelfrag** [comment]
There is work in progress that will address this issue (remove libmosquitto dependency). Stay tuned!

**Comment by underhood** [comment]
https://github.com/netdata/netdata/pull/10283 should be fixed there
