### ISSUE TITLE
Gaps in streamed charts / k8s helm deployment

### ISSUE THREAD

**Issue by champtar** [netdata/netdata#10220]
##### Bug report summary
Investigating some random issue on a K8S cluster, trying to deploy netdata to have more visibility, the graphs are full of gaps/holes/discontinuities
![image](https://user-images.githubusercontent.com/3536755/98616602-2175b600-22cb-11eb-921e-5b0c0e85d074.png)

##### OS / Environment
```
4.18.0-193.19.1.el8_2.x86_64
Red Hat Enterprise Linux 8.2 (Ootpa)
k8s v1.18.6
containerd 1.2.13
```

##### Netdata version
```
netdata v1.26.0
chart netdata-2.0.15
```

##### Component Name
?

##### Steps To Reproduce

Deploy using helm chart netdata-2.0.15

```
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
  path: /netdata(/|$)(.*) 
  hosts:
    - pilot
  tls:
    - secretName: pilot-tls
      hosts:
        - pilot

parent:
  env:
    DO_NOT_TRACK: 1

  database:
    persistence: false

  alarms:
    persistence: false

  nodeSelector:
    kubernetes.io/hostname: master-01

  tolerations:
    - operator: Exists
      effect: NoSchedule

  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          process scheduling policy = nice
          process nice level = -10
          memory mode = save

        [plugins]
          cgroups = no
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = no
          go.d = no
          node.d = no
          apps = no
          proc = no
          idlejitter = no
          diskspace = no
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [11111111-2222-3333-4444-555555555555]
          enabled = yes
          history = 172800
          default memory mode = save
          health enabled by default = auto
          allow from = *

child:
  env:
    DO_NOT_TRACK: 1
  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          process scheduling policy = nice
          process nice level = -10
          memory mode = none
          update every = 5
        [health]
          enabled = no
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [stream]
          enabled = yes
          destination = netdata:{{ .Values.service.port }}
          api key = 11111111-2222-3333-4444-555555555555
          timeout seconds = 60
          buffer size bytes = 10485760
          reconnect delay seconds = 5
          initial clock resync iterations = 60
```

##### Expected behavior
Everything works

##### Comments
I've already tried to bump `buffer size bytes` on the childs, to set the nice value at -10 instead of 19, and increase `update every`
I've verified that the settings are applied via `curl IP:19999/netdata.conf` (don't know how to check for stream.conf)
Depending on the servers we have between 7.5k et 8.5k metrics
no buffer full logs (`kubectl logs -l role=child --all-containers | grep -i buf`)

**Comment by champtar** [comment]
Ok I added `errors flood protection period = 0` and now I see
```
netdata ERROR : STREAM_SENDER[cache-07] : STREAM cache-07 [send to netdata:19999]: buffer full (1048576-bytes) after 353796 bytes. Restarting connection
```
(one could argue that rate limiting errors by default is a really bad idea but that is out of topic)

so the issue is that `buffer size bytes` is ignored

**Comment by ilyam8** [comment]
> rate limiting errors by default is a really bad idea but that is out of topic

Tend to agree 👍 

---

> so the issue is that buffer size bytes is ignored

It is `10485760` in the config and `1048576` according logs.

@vlvkobal take a look.

**Comment by ilyam8** [comment]
> so the issue is that buffer size bytes is ignored

Yes, you are right. The fix is coming!
