### ISSUE TITLE
Permission issue of alarm execute

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#10222]
##### Question summary
trying to execute the script when alarm raised, pretty simple configuration under one of the health .conf with additional line like below:
`exec: /root/test.sh`

and below are the permissions of the file:
```
-rwxrwxrwx 1 netdata netdata  100 Nov 10 14:22 test.txt
-rwxrwxrwx 1 netdata netdata   85 Nov 10 14:20 test.sh
```

inside the test.sh, it's pretty simple, print all the parameters to test.txt:
```
#!/bin/bash

echo `date` >> /root/test.txt

for i in "$*"; do
    echo $i >> /root/test.txt
done
```

But no matter how I tried, I ended up with below error from netdata:

```
sh: /root/test.sh: Permission denied
sh: line 0: exec: /root/test.sh: cannot execute: Permission denied
```

##### OS / Environment
CentOS Linux release 7.8.2003 (Core)

**Comment by thiagoftsm** [comment]
hello @startryst ,

Netdata runs as `netdata` user that should not have access to file inside `/root`, please, can you move the script to another directory to test?

Best regards!

**Comment by startryst** [comment]
@thiagoftsm Thanks, that's the point of my issue, and now I can execute the script fine.

but another issue is, some of my command and file manipulation of my script still facing the same issue, so how can I execute the script by user of root? rather than user of netdata? because it's clumsy for me to change all the necessary files into netdata access ready.

**Comment by thiagoftsm** [comment]
Hello @startryst ,

This is not a simple case,  Netdata is not installed as root, because this is not recommended. One possible solution for you, it would be to set permissions for your script like `ebpf.plugin`, but this is not recommended unless you have very good motives to do this. The `ebpf.plugin` has these permissions, because it needs to load ebpf programs inside the kernel. 

@Ferroin and @ilyam8 do you have a better suggestion for @startryst problems with permission?

**Comment by startryst** [comment]
Hi, @thiagoftsm 

I tried your u+s approach, check it out below, still facing some issues when running:

the permission set to exactly the same as ebpf.plugin:
```
[root@xxx netdata]# ls -lht test.sh
-rwsr-x--- 1 root netdata 965 Nov 11 21:11 test.sh
[root@xxx netdata]# ls -lht /usr/libexec/netdata/plugins.d/ebpf.plugin
-rwsr-x--- 1 root netdata 310K Oct 15 05:36 /usr/libexec/netdata/plugins.d/ebpf.plugin
```

In the test.sh, there're two commands need to be executed:
```
        sed -i 's/0.0.0.0\/0#./0.0.0.0\/0#5/' /etc/tinc/hphk/hosts/hphk2
        systemctl restart tinc@hphk
```

but comes with below error with the alarm been raised:
```
sed: couldn't open temporary file /etc/tinc/hphk/hosts/sedBQH2sB: Read-only file system
Failed to restart tinc@hphk.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
```

**Comment by startryst** [comment]
> Hi, @thiagoftsm
> 
> I tried your u+s approach, check it out below, still facing some issues when running:
> 
> the permission set to exactly the same as ebpf.plugin:
> 
> ```
> [root@xxx netdata]# ls -lht test.sh
> -rwsr-x--- 1 root netdata 965 Nov 11 21:11 test.sh
> [root@xxx netdata]# ls -lht /usr/libexec/netdata/plugins.d/ebpf.plugin
> -rwsr-x--- 1 root netdata 310K Oct 15 05:36 /usr/libexec/netdata/plugins.d/ebpf.plugin
> ```
> 
> In the test.sh, there're two commands need to be executed:
> 
> ```
>         sed -i 's/0.0.0.0\/0#./0.0.0.0\/0#5/' /etc/tinc/hphk/hosts/hphk2
>         systemctl restart tinc@hphk
> ```
> 
> but comes with below error with the alarm been raised:
> 
> ```
> sed: couldn't open temporary file /etc/tinc/hphk/hosts/sedBQH2sB: Read-only file system
> Failed to restart tinc@hphk.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
> ```
> 
> the permission of /etc/tinc/hphk/hosts folder comes with below permission, it's not accessible to netdata, but I presume the command is executed under root due to the +s permission, isn't it?
> `drwxr-xr-x 3 root root`

For above finding, it all comes down permission issue, sed and systemctl needs to be +s as well, and also the write permission to the folder of /etc/ is not allowed for netdata user.

So this looks not a sustainable approach, welcome to other ideas.

**Comment by thiagoftsm** [comment]
Hello @startryst ,

the message:

> sed: couldn't open temporary file /etc/tinc/hphk/hosts/sedBQH2sB: Read-only file system

is saying that your filesystem was mounted with read-only option, so it is not possible to do any changes on file system.

On the other hand, the permission `4750` that you applied allow any user to execute the script as `root`, and `root` user does not have blockers to read, but it cannot write when the file system is read only. 

- Are you mounting the file system with `/etc/fstab` ? If it is the case, please, can you said us the options used to mount the file system.
- CentOS has another way to mount filesystems, but I do not remember. If you are using it, please, can you take a look on the options.

Best regards!

**Comment by ilyam8** [comment]
> but another issue is, some of my commands and file manipulation inside my script still facing the same permission issue...

Well, it is getting complicated, what i would do is to write a service which is running as root and add to this service an HTTP API and would use this API to do what i need, then i have no permissions issue and don't need to mess with `netdata` user, etc.

Not sure tho, just thinking out loud.

let's wait for help from @Ferroin

**Comment by startryst** [comment]
update to keep it alive

**Comment by thiagoftsm** [comment]
@Ferroin , when you have a time, please, take a look on this issue.
