### ISSUE TITLE
Health alarm can do both (execute script on top of the alarm)?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#10221]
After add the execute: path, the notification by alarm-notify.sh seemed be overrode, so how can do both?

**Comment by thiagoftsm** [comment]
Hello @startryst ,

I understood that you want to use both `alarm-notify.sh` and another script, if this is correct, you can create another script that calls both methods like this:

```sh
#!/bin/bash

/usr/libexec/netdata/plugins.d/alarm-notify.sh "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${16}" "${17}" "${18}" "${19}"  "${20}" "${21}" "${22}" "${23}" "${24}"
/path/to/your/script arguments_that_you_need.
```

And this script will be the value for the variable `execute`.

Best regards!

**Comment by startryst** [comment]
Thanks, that works for me
