### ISSUE TITLE
Chart creation very slow over time

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#10233]
##### Bug report summary

Start an agent that has tens of thousands of charts in the same host, and measure the time before it's up.

Creating a chart will trigger obsoletion cleanup code whose time complexity is directly proportional to the number of charts in that host. The worst-case scenario is a single node (parent or child) where ephemeral charts have been generated over time. You can end up with hundreds of thousands of charts before the database rotates to remove them.

##### Component Name

daemon
##### Steps To Reproduce

1. Use `memory mode = dbengine`.
2. Start an agent that has tens of thousands of charts in the same host, and measure the time before it's up (metadata log replay will slow it down).

**Comment by ilyam8** [comment]
> Creating a chart will trigger obsoletion cleanup code

No longer the case. #11222
