### ISSUE TITLE
Need help on a custom python.d plugin with local json import

### ISSUE THREAD

**Issue by ShagoY** [netdata/netdata#10237]
Hello,
First of all, I have little experience with Python but with the help of existing scripts I managed to do what I wanted.

Context :

I created a script that generates a json file in the following form:
```
{
    "Temp": 23.75,
    "Rpm": 1350,
    "Pwm": 55
}
```
So here is my python script :
```
# -*- coding: utf-8 -*-
# Description: example netdata python.d module
# Author: Put your name here (your github login)
# SPDX-License-Identifier: GPL-3.0-or-later
# /usr/libexec/netdata/plugins.d/python.d.plugin debug 1 control_fan
# /usr/libexec/netdata/plugins.d/python.d.plugin debug trace control_fan

import json
from bases.FrameworkServices.SimpleService import SimpleService

# default module values (can be overridden per job in `config`)
# update_every = 5
# priority = 60000
# retries = 60

ORDER = [
    'temp',
    'rpm',
    'pwm',
]

CHARTS = {
    'temp': {
        'options': [None, 'Temperature Sensor', 'Celsius', 'Temperature', 'control_fan.temp', 'line'],
        'lines': [
            ['temp', None, 'absolute', 1, 1000]
        ]
    },
    'rpm': {
        'options': [None, 'Rpm Speed', 'Rotations/min', 'Fan', 'control_fan.rpm', 'line'],
        'lines': [
            ['rpm', None, 'absolute']
        ]
    },
    'pwm': {
        'options': [None, 'Pwm Duty', 'percentage', 'Fan', 'control_fan.pwm', 'line'],
        'lines': [
            ['pwm', None, 'absolute']
        ]
    }
}

class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.json_path = self.configuration.get('json_path')

    def check(self):
        if not (self.json_path and isinstance(self.json_path, str)):
            self.error("'json_path' is not defined")
            return False
        return True
        
    def _get_data(self):
        try:
            with open(self.json_path) as f:
                self.data = json.load(f)
            temp = int(self.data['Temp'] * 1000)
            rpm = self.data['Rpm']
            pwm = self.data['Pwm']
        except:
            return None

        return {'temp': temp, 'rpm': rpm, 'pwm': pwm} or None
```
The .conf file
```
json_path: '/tmp/fan_control.json'.
```
My problems are :

1- With check() = False and testing it in debug mode, my script doesn't close properly. I have to ctrl+c manually. 
It stays stuck on ```python.d INFO: plugin [main] : check failed.```

2- Also I try to manage correctly the errors that can come from the json. Like "empty" or others.
I would like some advice on how to do this correctly.
Currently my script runs in loop if the json file is empty for example. Is this the right behavior ?

3- I couldn't find a "simple" example of a python script that fetches a json file, so I created the script "from scratch". I'm not sure if I used the "best practices".
For example, I return values directly with "return {'temp': temp, 'rpm': rpm, 'pwm': pwm}" whereas most scripts do it with "return data". But I couldn't do otherwise... 
So if someone could help me to make my script more "suitable", I would be very happy :)

Thanks in advance.

**Comment by ilyam8** [comment]
@ShagoY 👋 

config is a set of jobs, job is an instance of module with specific parameters.

https://github.com/netdata/netdata/blob/4f117894d2ca499bad82dd622a1cfeced50bb87d/collectors/python.d.plugin/apache/apache.conf#L50-L56


Example config:

```yaml
job_name1:
  option1: value
  option2: value

job_name2:
  option1: value
  option2: value

...
```

---

> Also I try to manage correctly the errors that can come from the json

As all errors in python - usually you use `try/except`.

```python
try:
  do_something()
excecpt Exception as error:
  self.error(err)
  ...
```

---
 
> I couldn't find a "simple" example of a python script that fetches a json file

There are dozens of way how you get data - the general idea is you need to define charts (`ORDER`, `CHARTS`) and return `dict` from `_get_data()` which contains dimensions ids.

**Comment by ShagoY** [comment]
@ilyam8 
Thanks a lot, I was able to solve my first two issues :-)

But as for the last one (dict), I'm afraid it's completely beyond me..
I tried to use the existing ones but they are of "UrlService" class, so they require some modifications that goes far beyond my python skills.
I just can't get my values from "_get_raw_data" :-(

I would have liked a simple example of a python script that grabs a locally located json.
And eventually put it here : https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/example

Thanks again!

**Comment by ilyam8** [comment]
@ShagoY there is debug mode, see readme

> https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin#how-to-debug-a-python-module

So you can debug your module.

```json
{
    "Temp": 23.75,
    "Rpm: 1350,
    "Pwm": 55
}
```

is not a valid json, you can check it https://jsonlint.com/, that is why your module doesn't work.

valid is


```json
{
    "Temp": 23.75,
    "Rpm": 1350,
    "Pwm": 55
}
```

---

> But as for the last one (dict), I'm afraid it's completely beyond me..

See your CHARTS, all of them has dimensions (`lines`), first parameter is dimension id, in your case they are:

- `temp`
- `rpm`
- `pwm`

`_get_data` returns `dict`: keys - dimensions ids, values - their corresponding values. You did it right btw

```python
return {'temp': temp, 'rpm': rpm, 'pwm': pwm}
```

---

I simplified your script and added some error logging

```python

import json
from bases.FrameworkServices.SimpleService import SimpleService

ORDER = [
    'temp',
    'rpm',
    'pwm',
]

CHARTS = {
    'temp': {
        'options': [None, 'Temperature Sensor', 'Celsius', 'Temperature', 'control_fan.temp', 'line'],
        'lines': [
            ['Temp', 'temp', 'absolute', 1, 1000]
        ]
    },
    'rpm': {
        'options': [None, 'Rpm Speed', 'Rotations/min', 'Fan', 'control_fan.rpm', 'line'],
        'lines': [
            ['Rpm', 'rpm', 'absolute']
        ]
    },
    'pwm': {
        'options': [None, 'Pwm Duty', 'percentage', 'Fan', 'control_fan.pwm', 'line'],
        'lines': [
            ['Pwm', 'pwm', 'absolute']
        ]
    }
}

class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.json_path = self.configuration.get('json_path', '/tmp/fan_control.json')
        
    def _get_data(self):
        data = dict()
        try:
            with open(self.json_path) as f:
                data = json.load(f)
            data['Temp'] *= 1000
        except Exception as error:
            self.error(error)
            return None

        self.debug('collected data: {0}'.format(data))
        return data or None
```

**Comment by ShagoY** [comment]
I am literally in tears...

It was so simple... It seemed to me that I had tested it.
I was using the debug mode but considering my level, I certainly didn't understand my mistake :-|

Note: For the json, it was a bad copy/paste, sorry.

Thank you so much, You are my god.
