### ISSUE TITLE
Color-code relevant System Overview gauges

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#10238]
##### Feature idea summary

For the basic "System Overview" (i.e. the gauges)
![image](https://user-images.githubusercontent.com/1153921/80827388-b9fee100-8b98-11ea-8f60-0d7824667cd3.gif)

I would expect that they would be color coded i.e. CPU/RAM/SWAP would appear orange >80%, red at >=95%
It is really weird to me that I see sometimes 100% Used Swap in green (one of the times being when I am flushing the swap when a "real weird situation" has happened that my 2G swap on 64G RAM is >75% utilized).

Also, I would move the `%` on the values themselves, and instead add their maximum below (x Ghz / total RAM / total swap)

For the "un-measurable" units (max disk / net) - either ignore them, or save the "maximum value" that has been seen historically. Especially for internet-facing "nets", I would definitely not expect to have a 1Gbps maximum on an "absolutely no more than" 10Mbps internet-capable interface.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.

**Comment by stdedos** [comment]
Maybe we can get a summary publicly?
There's the ticket already anyway 😕

**Comment by ilyam8** [comment]
> Maybe we can get a summary publicly?

When we have it - for sure. We've considered this feature request important even it has no "👍"
