### ISSUE TITLE
Hostname is not written into syslog when using streaming.

### ISSUE THREAD

**Issue by dlevene1** [netdata/netdata#10245]
##### Question summary

When streaming from multiple hosts and alerting on one via syslog, the hostname is not being written into the file. SMTP notifications are correctly referencing the hostname, but syslo

![image](https://user-images.githubusercontent.com/10554724/99351726-251fc300-28f1-11eb-86ef-3ed0b0db1a00.png)

Config is pretty basic, but worked on a standalone host.

![image](https://user-images.githubusercontent.com/10554724/99351821-5e583300-28f1-11eb-9b8f-f512e0b8f017.png)

My question is - have I missed out some config, or is this a potential bug.

##### OS / Environment

RHEL 7.9

##### Component Name

Netdata rsyslog monitoring.

##### Expected results

The hostname should be in the syslog output.

**Comment by ilyam8** [comment]
Hi @dlevene1 Thx for reporting 👋 

Looks like a bug according provided logs. Not sure who to tag 🤔 @thiagoftsm perhaps you? 😄

**Comment by thiagoftsm** [comment]
Hello @dlevene1 ,

Firstly I apologize the delay to work on this, but I was busy with other tasks.
I made an environment like yours and I could recreate the reported bug:

```
Nov 23 19:56:41 hades thiago: netdata CRITICAL on  at Mon Nov 23 19:56:40 UTC 2020: system.cpu 4.23%
Nov 23 19:56:59 hades thiago: netdata CRITICAL on  at Mon Nov 23 19:56:58 UTC 2020: system.cpu 7.12%
Nov 23 19:56:59 hades thiago: netdata CRITICAL on  at Mon Nov 23 19:56:58 UTC 2020: system.cpu 18.3%
```

I am making a PR right now to fix this.

Thank you  for your report!

**Comment by dlevene1** [comment]
Hi @thiagoftsm,

Fantastic, I see a PR has been raised - thanks for fixing quickly.

Kudos to you and the team for a great product.

**Comment by ilyam8** [comment]
@dlevene1 thx for testing it, we made some changes and i am pretty sure they work, but if you have time to test it again, please do 😉

**Comment by dlevene1** [comment]
@ilyam8 - tested again, and it looks to be working as expected. Thanks.
![image](https://user-images.githubusercontent.com/10554724/100159363-8d783100-2efd-11eb-8be2-d32f44336686.png)
