### ISSUE TITLE
Netdata won't install on Centos 7

### ISSUE THREAD

**Issue by kozicpetar** [netdata/netdata#10246]
##### Bug report summary
I tried to install Netdata on Centos WHM server with kickstart. I already have netdata on several WHM servers and as I know can work.
I tried to run command:
`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel`
and
`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait --stable-channel`

Script run, install dependency and back with error:

```bash
[/tmp/netdata-kickstart-LMbAFS5Yzb]# curl -q -sSL --connect-timeout 10 --retry 3 --output /dev/stdout https://api.github.com/repos/netdata/netdata/releases/latest  OK

[/tmp/netdata-kickstart-LMbAFS5Yzb]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-LMbAFS5Yzb/sha256sum.txt https://github.com/netdata/netdata/releases/download/v1.26.0/sha256sums.txt  OK

[/tmp/netdata-kickstart-LMbAFS5Yzb]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-LMbAFS5Yzb/netdata-latest.tar.gz https://github.com/netdata/netdata/releases/download/v1.26.0/netdata-v1.26.0.tar.gz  OK

[/tmp/netdata-kickstart-LMbAFS5Yzb]# tar -xf netdata-latest.tar.gz  OK

 ABORTED  Cannot install netdata from source (the source directory does not include netdata-installer.sh). Leaving all files in /tmp/netdata-kickstart-LMbAFS5Yzb
```

I checked folder:
`/tmp/netdata-kickstart-LMbAFS5Yzb`  and there is `netdata-installer.sh` script.

I tried to run again installation, but now I get error about file checksum:

```bash
[/tmp]# curl -q -sSL --connect-timeout 10 --retry 3 --output /dev/stdout https://api.github.com/repos/netdata/netdata/releases/latest  OK

[/tmp]# curl -q -sSL --connect-timeout 10 --retry 3 --output /sha256sum.txt https://github.com/netdata/netdata/releases/download/v1.26.0/sha256sums.txt  OK

[/tmp]# curl -q -sSL --connect-timeout 10 --retry 3 --output /netdata-latest.tar.gz https://github.com/netdata/netdata/releases/download/v1.26.0/netdata-v1.26.0.tar.gz  OK

 ABORTED  Tarball checksum validation failed. Stopping netdata installation and leaving tarball in
```

##### OS / Environment
```
NAME            : CloudLinux
VERSION         : 7.9 (Boris Yegorov)
ID              : cloudlinux
ID_LIKE         : rhel fedora centos
VERSION_ID      : 7.9
```

##### Netdata version
I tried to install latest netdata v1.26
 

##### Component Name
Netdata

##### Steps To Reproduce
Run command:
`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel`

##### Expected behavior
Expected netdata to be installed.

**Comment by ilyam8** [comment]
@kozicpetar hi

It's been a while.

> I tried to install latest netdata v1.26

Have you tried latest, perhaps it is (magically) fixed 😄

**Comment by kozicpetar** [comment]
Hi @ilyam8,
yes I tried, won't work.
I'm talking with Ferroin about that here:

https://github.com/netdata/netdata/issues/10128#issuecomment-763060586

**Comment by stelfrag** [comment]
Closing in favor of #10128
