### ISSUE TITLE
netdata using termux

### ISSUE THREAD

**Issue by laguill** [netdata/netdata#10243]
Hi, 
I'm using termux on an asus memo pad 7, i386 arch
I would like to collect and dispaly data from a weather station running on a esp32. I'm using mqtt and node red.
Is it possible to install netdata with termux.
I tried https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart but that was unsucessfull
If someone can help me on this
I'm pretty new in termux

**Comment by stelfrag** [comment]
Hi @laguill 
I only have access to an android device to try termux on, so I don't know the esp32 specifics. Trying from sources, it will not compile at this point due to pthread dependency.

**Comment by laguill** [comment]
Hi 
Thank you for your answer. The esp32 is just use to send data with mqtt.
So if I understand I cannot install netdata server on android ?
Is there an alternative ?

**Comment by OdysLam** [comment]
Hey @laguill,

Welcome to our community :) 

I think it would be best to run Netdata on a Raspberry pi and then collect the data with a [custom python collector](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin). For your use-case, it would be best perhaps to simply push the metrics to a hosted InfluxDB (it can run locally too). To push the metrics, you can do a simple HTTP request, so it simplifies your setup substantially.

Cheers :)

**Comment by OdysLam** [comment]
BTW, if you do manage it to run on termux , please tell us how! We would love to enrich our documentation. Cheers!

**Comment by laguill** [comment]
Hi @OdysLam thank you for answering me.
Unfortunatly I want to reuse an android tablet. Maybe this is not the best reliable device but I like the idea of recycling things.
If I can't use netdata then I'll probably use sqlite3 and node-red dashboard
Thank you for your help.

And if someone has alredy done that or think of a better way I will be glad to hear from him.

**Comment by OdysLam** [comment]
Having fiddled with IoT quite a lot, I am not sure that sqlite is the best option. Maybe look into TimescaleDB and InfluxDB?

**Comment by laguill** [comment]
I know there is a pkg request for influxdb and with TimescaleDB I don't know how to use it.
I installed postgresql within termux but then I don't have enough knowledge :/

**Comment by underhood** [comment]
@laguill I am in fact doing something similar. Made home-made thermostat with e-ink display with esp8266 (older version of esp32) with my own custom firmware based on Sming framework. It sends data to RPi however (with MQTT).
Depending on workload next days I might find some time and try if it is possible to use netdata on termux in some android emulator... (never tried such thing)

**Comment by underhood** [comment]
@laguill I am almost able to make it work like this:
```
pkg install cmake
pkg install git
pkg install libuuid
pkg install automake
pkg install autotools
pkg install pkg-config
pkg install curl
pkg install wget

pkg in libandroid-spawn

git clone https://github.com/netdata/netdata.git --depth=100
mkdir netdata-install
cd netdata
pwd
> /data/data/com.termux/files/home/netdata
./netdata-installer.sh --install /data/data/com.termux/files/home/netdata/netdata-install --disable-ebpf
```
Problem seems to be Android doesn't implement `pthread_setcancelstate` for some weird reason. I will try and find some workaround for this but it might take a while. After this is solved I do not see any reason why netdata can't run on the termux.

![Screenshot from 2020-11-27 10-53-45](https://user-images.githubusercontent.com/6674623/100436245-60fc1a80-309f-11eb-934c-72be9a74905b.png)


@mfundul just pinging you as you might have some ideas or seen this already. Low chance as this seems to be android specific thing but anyway.

**Comment by underhood** [comment]
@laguill Unfortunately it looks like making it work on Termux would require us patching Netdata to work on this specific platform. :(

**Comment by laguill** [comment]
Hi @underhood 
Wow you are much better than me !
I'm afraid I won't be able to help you. 

I'm able to run
home assistant with configurator and hacs
node-red
esphome

My device is a tablet asus memo pad 7 with i686 arch
It is rooted with lineage os 16.0

For now it is doing the job. But if I want to store temperature data to compare with previous years I am a bit stuck. 
I've heard I can use a Hdd in ntfc but I am not sure if this a good idea

thanks for your help :)

**Comment by underhood** [comment]
@laguill well sorry I don't have better news for you. I managed to make it work in the end even with Cloud support but that requires heavy patching and had to disable almost all internal plugins (collectors) of netdata as those had additional requirements that Termux was not able to satisfy. This is not however way I can recommend to any user as it is too complex and hacky.

**Comment by mfundul** [comment]
Could it be that we're just not setting the correct CFLAGS and LDFLAGS for libpthread in Android?

**Comment by underhood** [comment]
@mfundul no, I have found just those functions don't exist on android, other pthreads functions are available. I managed to build it in the end. But had to get rid of those functions and manually disable all internal plugins (as they had other unmet dependencies not present in termux).
Also went in contact with termux guys and they told me they are manually patching those functions for example emulating those functions with signals or atomic flags etc. sample:
https://github.com/search?p=1&q=org%3Atermux+pthread_cancel&type=Code

**Comment by underhood** [comment]
@laguill unfortunately this is not currently feasible. We might revisit this issue when libuv migration is finished as that might remove some of the problems of why netdata can't currently run on termux.

**Comment by Mahoo12138** [comment]
So disappointed to see this issue

**Comment by DocMAX** [comment]
This is what i get:

![grafik](https://github.com/netdata/netdata/assets/5351323/06255222-4507-4d9b-bf1f-38a95bd951c2)
