### ISSUE TITLE
System crashes when enabling ebpf plugin in netdata

### ISSUE THREAD

**Issue by JOOSTR** [netdata/netdata#10258]
##### Question summary

Hello, we are running into an issue where the entire system crashes if we enable the ebpf plugin.

I ran this curl -sSL https://raw.githubusercontent.com/netdata/kernel-collector/master/tools/check-kernel-config.sh | sudo bash and it does not report any errors.

It works as expected without the plugin enabled.

##### OS / Environment
Ubuntu Server 18.04 LTS (GNU/Linux 4.18.0-25-generic x86_64) running in ESXi
##### Component Name
ebpf.plugin
##### Expected results
System not crashing, I have attached error logs.

[kernelpanic.log](https://github.com/netdata/netdata/files/5565888/kernelpanic.log)
[netdata.log](https://github.com/netdata/netdata/files/5567333/log1.log)

**Comment by thiagoftsm** [comment]
Hello @JOOSTR ,

I am trying to recreate the problem now to fix, and I have few questions for you:

- How did you install your Netdata?
- What is Netdata version you are running?
- Please, can you run the command `cat /proc/version_signature` and give us the output?

Best regards!

**Comment by JOOSTR** [comment]
Installed using netdata kickstarter.
We are using Netdata 1.26
This is the output: Ubuntu 4.18.0-25.26-generic 4.18.20

**Comment by thiagoftsm** [comment]
Hello @JOOSTR ,

I installed the kernel version that you were running, and I discovered that if I run direct on terminal `/usr/libexec/netdata/plugins.d/ebpf.plugin` as root user, it needs more time to crash then when it is called from Netdata. This has relationship either with `libbpf` or the plugin, I will bring a kick hotfix that will disable the plugin when Netdata is running on Ubuntu with this kernel version, and I will continue digging the problem to fix the problem completely.

Best regards!

**Comment by thiagoftsm** [comment]
An additional information, after 10 minutes running on kernel `Linux test 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` I did not have any problems with `ebpf.plugin`, so it is also possible that the kernels `4.15` and `4.18` running on Ubuntu are not supported, but I prefer do not consider this for while.

**Comment by OdysLam** [comment]
Hey @JOOSTR  and welcome to our community! I understand that it must have been frustrating, but thankfully we have amazing engineers like @thiagoftsm, so it got fixed pretty fast.

If you do have any other issue, please don't hesitate to contact us at our forums: https://community.netdata.cloud

**Comment by JOOSTR** [comment]
Yes, thank you for your help.

**Comment by thiagoftsm** [comment]
> Yes, thank you for your help.

And thank you to report the problem for us!  :)
