### ISSUE TITLE
Discourse forum not sending email

### ISSUE THREAD

**Issue by TerminalAddict** [netdata/netdata#10257]
can't login to https://community.netdata.cloud/
and when I "forgot my password" , I never receive an email.

I couldn't find any other way to contact you

**Comment by ilyam8** [comment]
Hi @TerminalAddict 👋 Thx for reporting!

@OdysLam please take a look.

**Comment by OdysLam** [comment]
Hey @TerminalAddict, the issue has been resolved, I think. Thank you for reporting this, I am sorry for the inconvenience. 

Thanks @ilyam8 for the ping ! :)
