### ISSUE TITLE
Example of python urlservice accessing session cookie auth resources.

### ISSUE THREAD

**Issue by csmarshall** [netdata/netdata#10256]
#### Question summary
I wrote a plug to pull out metrics from my arris surfboard modem a few weeks back here: 
https://github.com/csmarshall/netdata-arris-surfboard-modem-plugin-python/

And it worked great, until the modem died and I replaced it, in the interim comcast pushed a software update and now one is required to authenticate with a session cookie to your own modem :gruble: 

Looks like a variation of this code:
 https://github.com/andrewfraley/arris_cable_modem_stats/pull/10/commits/274036321ded8a7b89d0a57a9103bb57615f468a

Will most likely solve my problem, as it doesn't seem that the built in basic_auth methods will work.  

Does anyone know of any other examples of adding session cookie auth to accessing something via the urlservice?  At first blush it seems like I'm going to have to do some pretty deep brain surgery to wire this in, but maybe I'm not understanding it completely.

##### OS / Environment
Python / Linux?

##### Component Name
urlservice

##### Expected results
can I haz pretty graphs plz....

**Comment by ilyam8** [comment]
Hi @csmarshall 👋 

`UrlService` uses [urllib3](https://urllib3.readthedocs.io/en/latest/), so if the library allows it we can do it. We need to check it.

**Comment by OdysLam** [comment]
Hey @csmarshall welcome to our community and thanks for the new plugin. We would love you to see PRing the collector or PR an improvement (perhaps a new method?) to the urlservice function that would enable the cookie authentication.

Apparently, urllib3 can support [cookies](https://stackoverflow.com/questions/2422922/python-urllib3-and-how-to-handle-cookie-support), so we would love to see this improvement finding it's way into the source code.
