### ISSUE TITLE
Qos : tc-qos-helper nest class group

### ISSUE THREAD

**Issue by limbo127** [netdata/netdata#10250]
Hello
https://firehol.org/fireqos-manual/fireqos-class/
fireqos permit group class but it seems not work with netdata

Exe : 
class6  group cebox prio 1 max $WAN_SPEED commit 80%
class6 10_192_30_67_64125 prio 3
..

tc-qos-helper seems to be parse correctly with name class cebox/10_192_30  but nothing display
Regards, 
Nicolas

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
