### ISSUE TITLE
Badges: transform value to text based on conditions

### ISSUE THREAD

**Issue by adia** [netdata/netdata#10266]
First of all, I don't know if this feature is in scope, so feel free to reject it. Thanks!

I think it would be useful to have a way to display a string in the value spot of badges, similar to how the value_color parameter works. So, something like:

```value_string=Unknown:null|Very Slow>100|Slow>30|Fast```

... will display "Unknown" if no value has been collected, "Very Slow" if the value is more than 100, "Slow" if more than 30 and "Fast" otherwise.

I think this would be useful for dashboards to display some textual status without having to do API requests with JS.

**Comment by OdysLam** [comment]
Hey @adia,

Thanks for this feature request and welcome to our community! The agent team will respond shortly!

**Comment by thiagoftsm** [comment]
Hello @adia ,

I took a fast look in our webserver, and to bring this feature we would need to change  the functions:

- [calc_colorz](https://github.com/netdata/netdata/blob/4de1c2e6cca67d8fcd87ebd88879293042aeda8c/web/api/badges/web_buffer_svg.c#L558) - Responsible to write the value to the badge.
- [buffer_svg](https://github.com/netdata/netdata/blob/4de1c2e6cca67d8fcd87ebd88879293042aeda8c/web/api/badges/web_buffer_svg.c#L735) -  Here I am considering  a complete new argument like you suggested. 
- [web_client_api_request_v1_badge](https://github.com/netdata/netdata/blob/4de1c2e6cca67d8fcd87ebd88879293042aeda8c/web/api/badges/web_buffer_svg.c#L864) - And we will add a new parameter to this string.

Of course we will also need to update our documentation to bring this new feature.

@dim08 , please, take a look in the request for we make a plan to bring it.

Best regards!

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
