### ISSUE TITLE
Redis connections chart question

### ISSUE THREAD

**Issue by Tommuh** [netdata/netdata#10267]
Hi guys,

I have a question about a Redis chart, it is about the **redis_local.clients**
Where does this value come from? 

We have some issues regarding Redis and connections that we try to resolve - this chart always seems to cap at 100/101 when those issues occur. I'm not here to get help with Redis, just curious where this value is based on.

![image](https://user-images.githubusercontent.com/2089879/99803607-0d874b00-2b3a-11eb-9709-db3d4008cd6c.png)

**Comment by ilyam8** [comment]
Hi, that chart

https://github.com/netdata/netdata/blob/333badb3a7da910c8926b72adfab93c0bb999305/collectors/python.d.plugin/redis/redis.chart.py#L95-L100


Metrics descriptions: https://redis.io/commands/info#notes

- `connected_clients`: Number of client connections (excluding connections from replicas).
- `blocked_clients`: Number of clients pending on a blocking call (BLPOP, BRPOP, BRPOPLPUSH, BLMOVE, BZPOPMIN, BZPOPMAX).

**Comment by Tommuh** [comment]
Thank you for your quick response.
