### ISSUE TITLE
nvidia-smi user statistics broken for LDAP users (not in /etc/passwd)

### ISSUE THREAD

**Issue by scatenag** [netdata/netdata#10264]
With latest updates to nvidia stack and netdata something is broken in nvidia-smi users charts:
nvidia_smi.gpu0_processes_mem shows correctly the process by the nvidia_smi.gpu0_user_mem and nvidia_smi.gpu0_user_num are empty.

![broken](https://user-images.githubusercontent.com/46522361/99726296-9bb9ed80-2ab6-11eb-8ab2-e7a9cb900e46.png)

netdata version: v1.26.0
NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     
on CentOS Linux release 7.9.2009 (Core)

trying to debug it seems that 

- nvidia smi returns the correct pid
- `get_username_by_pid_safe` is not finding the username for pid,
that is, 
in ` /usr/libexec/netdata/python.d/nvidia_smi.chart.py`
running

```
for info in processes_info:
            pid = info.find('pid').text
            print(int(pid));
            print(info.find('process_name').text);
	    print(int(info.find('used_memory').text.split()[0]));
	    print(get_username_by_pid_safe(pid, passwd_file));
            processes.append({
                'pid': int(pid),
                'process_name': info.find('process_name').text,
                'used_memory': int(info.find('used_memory').text.split()[0]),
                'username': get_username_by_pid_safe(pid, passwd_file),
	    })
        return processes

```
I got no username

```
92144
python
1577

```

but ps is finding the right info

```
ps -p 92144 -o pid,vsz=MEMORY -o user,group=GROUP -o comm,args=ARGS                                                 1 ↵  22:34:57
   PID MEMORY USER     GROUP    COMMAND         ARGS
 92144 30673852 a.molin+ di_users python        python experiments_with_leam.py
```

Any thoughts to debug this ?

**Comment by ilyam8** [comment]
Hi @scatenag 

check `passwd_file` content

**Comment by scatenag** [comment]
Ok; I think I found the cause but not the solution:

the user is an LDAP user;

passwd_file does not contains it.

it's weird because I could have sworn it worked with LDAP users until recently.

**Comment by ilyam8** [comment]
We look for a pid in the `/etc/passwd` file.

https://github.com/netdata/netdata/blob/149a7c3f3665545253cbe243afa642101764243f/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L247-L269

**Comment by scatenag** [comment]
yep, but LDAP users are not in /etc/passwd ...

**Comment by ilyam8** [comment]
It is expected then, but we need to mention in in the module readme to avoid confusions.

**Comment by scatenag** [comment]
oh no! It is true: it never worked with LDAP users!

I should invent something for LDAP user !
(ps -p Is is capable; we must be too !)
any thoughts ?

**Comment by ilyam8** [comment]
I have no expirience with LDAP, so 🤷‍♂️, unfortunately 😄 

Since you are using LDAP - try to look for solutions/test stuff.

**Comment by ilyam8** [comment]
@scatenag workaround is to use user `uid` if there is no user in `/etc/passwd`, does it sound any good?

**Comment by scatenag** [comment]
@ilyam8 using `uid` is better than nothing, but I think is not a good overall solution...we could do better.

I mean: both the following solutions (using psutil or pwd) are able to retrieve the correct username:

```
import psutil
...
username = psutil.Process(pid).username()
```

and

```
import os 
import pwd
...
proc_stat_file = os.stat("/proc/%d" % pid)
uid = proc_stat_file.st_uid
username = pwd.getpwuid(uid)[0]
```

How we can proceed ?

**Comment by ilyam8** [comment]
Well, i think `pwd` reads data from `/etc/passwd` 🤔 

Instead of `pwd.getpwuid` we do 

https://github.com/netdata/netdata/blob/149a7c3f3665545253cbe243afa642101764243f/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L285

and `passwd_file` is 

```python
{uid: (name, passwd, uid, gid, comment, home_dir, shell), ...}
```

---

are you sure `pwd.getpwuid` works for LDAP user when you call it as `netdata` user?

**Comment by scatenag** [comment]
yes, it is.

using
```
        for info in processes_info:
            pid = info.find('pid').text
            proc_stat_file = os.stat("/proc/%d" % int(pid));
            uid = proc_stat_file.st_uid;
            processes.append({
                'pid': int(pid),
                'process_name': info.find('process_name').text,
                'used_memory': int(info.find('used_memory').text.split()[0]),
                'username': pwd.getpwuid(uid)[0],
            })
```

**Comment by ilyam8** [comment]
`pwd` is python built-in (std library)

```python
>>> import pwd
import pwd # builtin
```

We can use it, i don't remember why we decided to not use it 🤔

**Comment by scatenag** [comment]
For docker compatibility

**Comment by ilyam8** [comment]
well then we need to fallback to our custom implementation only if we are inside docker, `pwd` otherwise.

**Comment by scatenag** [comment]
something like the following ?

```
def isDocker():
        return os.environ.has_key('NETDATA_HOST_PREFIX');

def getUserByPid(pid):
    if isDocker():
        passwd_file = read_passwd_file_safe()
        return get_username_by_pid_safe(pid, passwd_file)
    else:
        proc_stat_file = os.stat("/proc/%d" % int(pid))
        uid = proc_stat_file.st_uid
        return pwd.getpwuid(uid)[0]
```

then

```
    def processes(self):
        processes_info = self.root.find('processes').findall('process_info')
        if not processes_info:
            return list()

        passwd_file = read_passwd_file_safe()
        processes = list()
        for info in processes_info:
            pid = info.find('pid').text
            processes.append({
                'pid': int(pid),
                'process_name': info.find('process_name').text,
                'used_memory': int(info.find('used_memory').text.split()[0]),
                'username': getUserByPid(pid),
            })
	return processes

```

**Comment by ilyam8** [comment]
@scatenag hey, could you test #10268?

**Comment by scatenag** [comment]
As replied on the PR:
Tested outside docker: it is running fine!
@ilyam8 Great work!

**Comment by ilyam8** [comment]
@scatenag great, still would be nice to know what source `pwd` uses to get users data 🤷‍♂️ 😄 But nice it works!

**Comment by scatenag** [comment]
Hi @ilyam8 ;
I have to re-open this issue because, recently (this month?), I started to lose usernames of LDAP users again.
(dont ask me why...maybe an update to pwd lib ?)

Only way to get them back is to patch [`get_username_by_pid_safe`](https://github.com/netdata/netdata/blob/f5e4ec6c30f9d7d7f91cc8e08574ec539e75e02e/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L283-L293) as 
```
def get_username_by_pid_safe(pid, passwd_file):
    path = os.path.join(PROC_PATH, pid)
    try:
        uid = os.stat(path).st_uid
    except (OSError, IOError):
            return ''
    if IS_INSIDE_DOCKER:
        try:
            return passwd_file[uid][0]
        except KeyError:
            return str(uid)
    else:
        return pwd.getpwuid(uid)[0]
```

The fact is that `pwd.getpwall()` of [`read_passwd_file_safe`](https://github.com/netdata/netdata/blob/f5e4ec6c30f9d7d7f91cc8e08574ec539e75e02e/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L274-L280) does not return username for uid of not-local (that is LDAP/AD) users. Instead pwd.getpwuid(uid)[0] does the correct job.

[Related PR ](https://github.com/netdata/netdata/pull/11854)

Thanks and regards

**Comment by TheTyrius** [comment]
Hello, I would like to propose another addition to this feature: Fallback to uid if `getpwuid` fails, regardless of docker involvement.
In my case, nvidia-smi reports the uid of a user inside an unpriviledged lsc container. This uid is not known on the host, and the monitoring fails with `2022-02-19 16:28:41: python.d ERROR: nvidia_smi[nvidia_smi] : update() unhandled exception: 'getpwuid(): uid not found: 100110'`. I guess before the latest change, `str(uid)` would have been used in this case. Do you think, we could reintroduce this?

**Comment by ilyam8** [comment]
Hi, @TheTyrius. If I understand you correctly we need the following

```python
def get_username_by_pid_safe(pid, passwd_file):
    path = os.path.join(PROC_PATH, pid)
    try:
        uid = os.stat(path).st_uid
    except (OSError, IOError):
        return ''
    try:
        if IS_INSIDE_DOCKER:
            return passwd_file[uid][0]
        else:
            return pwd.getpwuid(uid)[0]
    except KeyError:
        return str(uid)
```

Can you change `get_username_by_pid_safe` and see if it fixes your problem?

**Comment by TheTyrius** [comment]
Hi @ilyam8 thanks for getting back to me so very fast!
Indeed that is what I was asking. I edited the file and from my quick tests it seems to be working as expected.

I see you already drafted a PR, so I won't have to. I'd be glad to see this improvement merged :) Thanks again.

**Comment by ilyam8** [comment]
@TheTyrius the fix is merged
