### ISSUE TITLE
Raspberry Pi CPU temp

### ISSUE THREAD

**Issue by ShagoY** [netdata/netdata#10274]
Hello,

According to your docs, and [here](https://github.com/netdata/netdata/issues/8603), only the charts.d module allows to do it.

However while installing my new RPI, I discovered a rather strange behavior...
I installed by accident the lm-sensors package and even if it doesn't discover any sensors (and even without launching the discovery), Netdata discovered the Raspi temperature via "cpu_thermal-virtual-0 temperature (sensors.cpu_thermal_virtual_0_temperature)".
I have the charts.d modules disabled so it seems to come from the python module!

So there is a way to make this compatible "out of the box" with the cpu sensor of the RPI with python :)

**Comment by ilyam8** [comment]
Hi @ShagoY, yeah, `lm-sensors` in the repo, but it does not produce the expected results.

**Comment by ilyam8** [comment]
@ShagoY thx for noticing this and being an active user 👍 However, for my knowledge, `lm-sensors` doesn't really work in RPi.

**Comment by ShagoY** [comment]
@ilyam8 Sorry if I wasn't clear... English is not my native language ;-)
But that's exactly what I tried to say. Lm-sensors are strictly useless on Raspberry but the simple fact of installing it (without even configuring it) allows Netdata to get the CPU temperature back :)

**Comment by Ferroin** [comment]
The Pi 4 is a different SoC from the earlier versions, so the CPU temperature sensor may be exposed in a different way which happens to work.

Alternatively, the Pi Foundation may have finally listened to all the people in the community asking them to enable the kernel config that exposes sensors handled by the kernel’s thermal-management API as hwmon devices, which would mean this now works on any Pi if you have a new enough kernel...

**Comment by ShagoY** [comment]
Thank you for this information, also know that the "tip" also works on the 3b/3b+/3a+ version.

I admit I don't know if it comes from the new kernel or not, I used the chart.d script before.

It would be interesting if Netdata could recover the CPU temperature without the installation of the lm-sensors package, especially knowing that the chart.d script is deprecated compared to the python one.

Thanks in advance :)
