### ISSUE TITLE
MySQL go.d.plugin fails on Ubuntu 20.04 with MariaDB 10.5

### ISSUE THREAD

**Issue by lucasRolff** [netdata/netdata#10281]
##### Bug report summary

On Ubuntu 20.04 we're seeing the MySQL go.d.plugin doesn't work as it should with certain versions of MariaDB.

```
[ DEBUG ] mysql[local] mysql.go:97 connected using DSN [netdata@tcp(127.0.0.1:3306)/]
[ DEBUG ] mysql[local] collect.go:15 executing query: 'SELECT VERSION()'
[ ERROR ] mysql[local] mysql.go:129 Invalid character(s) found in prerelease "MariaDB-1:10"
```

The actual MariaDB version:

```
MariaDB [(none)]> SELECT VERSION();
+-----------------------------------------+
| VERSION()                               |
+-----------------------------------------+
| 10.5.8-MariaDB-1:10.5.8+maria~focal-log |
+-----------------------------------------+
1 row in set (0.000 sec)
```

##### OS / Environment

```
Linux ip-172-26-13-231 5.4.0-1011-aws #11-Ubuntu SMP Mon May 11 13:17:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

 
netdata v1.26.0-242-nightly

##### Component Name

go.d.plugin mysql

##### Steps To Reproduce

1. Install Ubuntu 20.04 (Focal)
2. Install MariaDB 10.5 from the official MariaDB mirrors
3. Create the `netdata` user and grant permissions to read all slaves

##### Expected behavior

Collection should work for the go version of the mysql collector.

We need this for collecting info from `show all slaves status` which doesn't seem to be available in the python version of the module.

**Comment by ilyam8** [comment]
Hi @lucasRolff 

This bug was fixed in https://github.com/netdata/go.d.plugin/pull/498

Will be in the master this week

**Comment by lucasRolff** [comment]
Thanks @ilyam8 I didn't realize go.d.plugins was a separate repo! That explains why it didn't turn up here!

**Comment by ilyam8** [comment]
Yeah, it is a separate repo, netdata's installer download latest version from [releases page](https://github.com/netdata/go.d.plugin/releases) if actual < latest.
