### ISSUE TITLE
Disabling prometheus plugin not working

### ISSUE THREAD

**Issue by kevinkk525** [netdata/netdata#10288]
##### Bug report summary

I'm trying to disable the plugin "prometheus" that pulls data from all prometheus endpoints.
I tried adding to /etc/netdata/netdata.conf:
```
[plugins]
        /usr/libexec/netdata/plugins.d/go.d.plugin/prometheus = no
        prometheus = no
        go.d/prometheus = no
        go.d.plugin/prometheus=no
```
Neither of these options work. The only way that worked was to disable the whole go.d plugin completely, which is not quite what I want to do..

##### OS / Environment

```
Linux droidserver.fritz.box 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

 netdata v1.26.0-255-nightly

##### Component Name

prometheus

##### Steps To Reproduce

1. Standard installation with all plugins enabled by default
2. Try to disable prometheus plugin by adding to netdata.conf [plugins]

##### Expected behavior

adding "prometheus = no" to netdata.conf [plugins] should disable the plugin

**Comment by ilyam8** [comment]
Hi @kevinkk525 

To disable specific go collector you need to edit [`go.d.conf`](https://github.com/netdata/go.d.plugin/blob/master/config/go.d.conf)

```yaml
modules:
  prometheus: no
```

cd to `/etc/netdata/` and `sudo ./edit-config go.d.conf`

**Comment by kevinkk525** [comment]
oh, thanks a lot! That makes sense.. Didn't find that in the documentation (or didn't make the right conclusion, there is not much about disabling plugins).
Thanks for the help.

**Comment by ilyam8** [comment]
Indeed i couldnt find it too, at least it is not clear

[`Enable, configure, and disable modules`](https://learn.netdata.cloud/docs/agent/collectors/reference#enable-configure-and-disable-modules) points to [`collectors quickstart`](https://learn.netdata.cloud/docs/agent/collectors/quickstart) which has not `disabling` section. @joelhans
