### ISSUE TITLE
Increase history of netdata

### ISSUE THREAD

**Issue by Andrew7374** [netdata/netdata#10306]
I want increase amount of time (history) in netdata. I find post:
https://learn.netdata.cloud/guides/longer-metrics-storage
but I don't know how get amount of metrics to calculate.

Also, I find somewhere in internet information that netdata holding only last 5 minutes and I have missunderstanding, because I see now data from 7:04 to now.
My netdata.conf - [global] history looks like:

[global]
	# history = 3996

So if it is amount of seconds then 3996s / 60s = 66.6 min / 60 = 1.11h - so it's not true, because I see last 7hours...

I have 60GB of RAM to use. From netdata charts I see the most using RAM is about 10GB, so 50GB is still free (info append to calculations).

My server:

Linux ns3054945 4.19.62-mod-std-ipv6-64-rescue #828825 SMP Tue Jul 30 13:54:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic

Netdata version:
netdata v1.26.0-292-nightly

Anyone can explain me how it's works? My general purpose is set history to keep history from last week.

**Comment by ilyam8** [comment]
Hey, @Andrew7374. We suggest using [dbengine](https://learn.netdata.cloud/docs/agent/database) (the default memory mode). Assuming that you collect 2000 metrics on your system, this should give you ~3 days of retention. Use [the calculator](https://learn.netdata.cloud/docs/store/change-metrics-storage) to have a more accurate estimation.
