### ISSUE TITLE
Include `<img>` element showing the related badge in (mail) alarm notifications

### ISSUE THREAD

**Issue by nodiscc** [netdata/netdata#10309]
##### Bug report summary

In the default (mail) alarm notification template, it would be useful to include the URL/`<img>` element to the corresponding alarm badge.

##### OS / Environment

Desktop or web mail client as main notification method/recipient.

##### Netdata version

v1.26.0 

##### Component Name

health

##### Steps To Reproduce

I use mail as my main notification method for monitoring alerts. My go-to action after receiving a critical notification (or repeated warning notifications) if to open a task/ticket in the appropriate tool to diagnose and patch/fix the problem.

Most of the time i embed an img `![](https://url.to/netdata/badge.svg)` in the report so that the issue/ticket is always linked to the state of this specific alarm (I may add others if they are related, or come back to a supposedly fixed problem and see that the alarm is back up) and when/why it is raised, etc.

To do this I have to open the relevant netdata dashboard, go to the alarms menu/popup, find the relevant alarm badge, copy its image URL, go to the ticketing system and paste it there.

##### Expected behavior

It would be very useful, to have the badge that is related to the alarm included in the mail template as `<img>` element (I don't know much about other notification methods, non-mail notification could need other markup such as markdown, or not support it at all), in the form `<img src="https://$NETDATA_FQDN:$NETDATA_PORT/api/v1/badge.svg?chart=$CHART&alarm=$ALARM&refresh=auto" />`

3 steps shorter (and scrolling through many alarms takes a long time to find the relevant one) than doing it with my current method.

It also allows reading to old/unacknowledged notifications in the mailbox and instantly knowing if the relevant alarm is still up.

I'm looking for a way to customize the mail template to achieve this (does the template system allow it? have not looked yet), also I might suggest that this should be the default, or documented.

Thanks

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
