### ISSUE TITLE
Haproxy python plugin

### ISSUE THREAD

**Issue by ashish1099** [netdata/netdata#10321]
Issue reported but closed https://github.com/netdata/netdata/issues/2189

##### OS / Environment
Xenial 16.04

##### Netdata version
1.26

##### Component Name
Haproxy python.d plugin

##### Steps To Reproduce
1. enable haproxy stats under any frontend
2. enable the haproxy plugin
```
http://127.0.0.1:63661/haproxy?stats;csv;norefresh
```
3. monitor the haproxy log and you would two entries 
```
2020-12-03T03:18:02+01:00 localhost haproxy[19080]: 127.0.0.1:28490 [03/Dec/2020:03:18:02.642] netdata-monitoring netdata-monitoring/<NOSRV> 0/-1/-1/-1/0 503 237 - - SC-- 182/1/0/0/0 0/0 "GET /haproxy HTTP/1.1"
2020-12-03T03:18:12+01:00 localhost haproxy[19080]: 127.0.0.1:28824 [03/Dec/2020:03:18:12.631] netdata-monitoring netdata-monitoring/<STATS> 0/0/0/0/1 200 21725 - - LR-- 180/1/0/0/0 0/0 "GET /haproxy?stats;csv;norefresh HTTP/1.1"
```

##### Expected behavior
when setting up the haproxy config to use via_url, it tries to hit the haproxy twice.

1. stats
2. info

but in case of `info` there is no **info** in the haproxy stats page, not sure why we are doing this and we can not get `info` stats from the stats page.
it's resulting in 503 all the time.

**Comment by ilyam8** [comment]
@ashish1099 hi 👋  thx for reporting!

I checked haproxy code and to be honest a little bit confused 😄 


Could you try to change `_get_data` to

```python
    def _get_data(self):
        to_netdata = dict()
        self.request, self.url = self.options_['stat'], self.options_['stat']
        stat_data = self._get_stat_data()
        if self.poll is SocketService:
            self.request, self.url = self.options_['info'], self.options_['info']
            info_data = self._get_info_data(regex=self.options_['regex'])
            to_netdata.update(info_data)
        to_netdata.update(stat_data)
        return to_netdata or None
```

and check if it fixes the problem?

**Comment by ilyam8** [comment]
Oh, i see

https://github.com/netdata/netdata/issues/2189#issuecomment-301779436

Module does HTP requests
 - `http://ip.address:port/haproxy_stats;csv`: stats in csv format.
 - `http://ip.address:port/haproxy_stats`: same stats + idle metrics but in html format.

> but in case of info there is no info in the haproxy stats page

so we do it only to get `idle`.

**Comment by ilyam8** [comment]
> but in case of info there is no info in the haproxy stats page

So threre no `info` page, we fetch `/haproxy_stats` in csv and html formats.

https://github.com/netdata/netdata/blob/307a974c7ed6e3fb5e3b1899d208627c1b94dd2d/collectors/python.d.plugin/haproxy/haproxy.chart.py#L218-L220

 - `http://127.0.0.1:7000/haproxy_stats;csv;norefresh'`
 - `http://127.0.0.1:7000/haproxy_stats'`

```python
In [10]: url_remove_params('http://127.0.0.1:7000/haproxy_stats;csv;norefresh')
Out[10]: 'http://127.0.0.1:7000/haproxy_stats'
```

**Comment by ashish1099** [comment]
@ilyam8 hey thanks for picking this up.

The fix seems to me and I had the same plan to fix it as well and yes even I got confused as well because there is `info` on the stats page if we expect the same output what we get from the `socket` file

let me know, if we are on the same page, so I can just test and send a patch of it

**Comment by ashish1099** [comment]
> ```python
> In [10]: url_remove_params('http://127.0.0.1:7000/haproxy_stats;csv;norefresh')
> Out[10]: 'http://127.0.0.1:7000/haproxy_stats'
> ```

But another problem lies that we have to fix the documentation, that we need the `stats uri /haproxy_stats` to be present in the haproxy.cfg otherwise haproxy will just end up in 503.

so I see two fixes.

1. if we go ahead with the same code, fix the documentation that the haproxy needs to have `stats uri <path> present in the haproxy config
2. we fix the plugin and get rid of the `info` stuff

**Comment by ilyam8** [comment]
i think 1.

We are [moving python collectors to go](https://github.com/netdata/go.d.plugin/issues/483) and i will fix it in the new version.

**Comment by ashish1099** [comment]
perfect then should I raise a PR for the doc fix ?

**Comment by ilyam8** [comment]
Would be perfect!

**Comment by ashish1099** [comment]
done https://github.com/netdata/netdata/pull/10322
