### ISSUE TITLE
Can't update netdata

### ISSUE THREAD

**Issue by playday3008** [netdata/netdata#10337]
##### Bug report summary

Ill trying to update netdata from `v1.19.0-239-nightly` to latest

##### OS / Environment

```
Linux MajorDoMoRPi 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version

netdata v1.26.0-325-nightly (after "updating")
netdata v1.19.0-239-nightly (before)

##### Steps To Reproduce

```
sudo -s
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry
```

##### Expected behavior

```
Mon  7 Dec 21:38:03 MSK 2020 : INFO:  Updating tarball checksum info
//usr/libexec/netdata/netdata-updater.sh: line 268: syntax error near unexpected token `('
//usr/libexec/netdata/netdata-updater.sh: line 268: `  fatal "You are running this script as user with uid $(id -u). We recommend to run this script as root (user with uid 0)"'
 FAILED

 ABORTED  Failed to update existing Netdata install
```

**Comment by playday3008** [comment]
Thats a modified Raspbian OS Lite (MajorDoMo for Raspberry Pi)
used this image file https://drive.google.com/uc?id=1OflJo9q5-SmSkfTZV6sGRfk5Z5DvvfL3&export=download

**Comment by playday3008** [comment]
Also, after "update" node in Netdata cloud unreachable and need update

**Comment by OdysLam** [comment]
Hey @playday3008,

We have currently a known issue with our updater, although I am not sure if it is related to your issue. We have taken note and one of our engineers will come back to triage this. 

Thank you!

**Comment by Ferroin** [comment]
It looks like you are running into a bug in that particular version (v1.19.0-239) of the updater script.

By default, current copies of the kickstart install script will attempt to update an existing install using the updater script instead of creating a new install over top of the existing one. You can bypass this by adding `--reinstall` to the install command, which should both get you the newest version and should allow automatic updates to work properly as well.

**Comment by underhood** [comment]
@playday3008 were you able to fix your issue with the steps @Ferroin lists above?

**Comment by playday3008** [comment]
No, bcoz netdata preinstalled and preconfigurated and integrated into MajorDoMo home page, after `--reinstall` option I don't know how to correctly configure netdata same as before

**Comment by ilyam8** [comment]
Closing this issue, the fix is https://github.com/netdata/netdata/issues/10337#issuecomment-742695375
