### ISSUE TITLE
"hostname" setting not being respected by Graphite exporter

### ISSUE THREAD

**Issue by nrhtr** [netdata/netdata#10339]
##### Bug report summary

After setting the "hostname" setting for a graphite exporter in "exporting.conf", Netdata continues to send metrics with the global hostname setting

##### OS / Environment

Running in a docker container.
```
/ # uname -a; grep -Hv "^#" /etc/*release
Linux <hostname> 5.2.10-1.el7.elrepo.x86_64 #1 SMP Sun Aug 25 11:20:04 EDT 2019 x86_64 Linux
/etc/alpine-release:3.12.1
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.12.1
/etc/os-release:PRETTY_NAME="Alpine Linux v3.12"
/etc/os-release:HOME_URL="https://alpinelinux.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

##### Netdata version

```
 / # netdata -V
netdata v1.26.0-324-ga3e50d5b
```

##### Component Name

Graphite exporter

##### Steps To Reproduce

1. Configure netdata with hostname = "foo.bar"
2. Configure graphite exporter with hostname "foo_bar"
3. Observe metrics being sent to Graphite as "prefix.foo.bar.baz"

##### Expected behavior

Expected hostname to be "foo_bar". I'm trying to work-around https://github.com/netdata/netdata/issues/7856

**Comment by vlvkobal** [comment]
You can set `hostname` in `[exporting:global]`. I don't think it is reasonable to set a different hostname for every connector instance.

**Comment by vlvkobal** [comment]
Anyway, it's a bug. Either in the documentation or in the code. Should we override the option in an instance configuration or mention in the documentation that `hostname` is available only in `[exporting:global]`?

@dim08, @ilyam8 - any thoughts?

**Comment by vlvkobal** [comment]
I decided, that it's better to support the `hostname` option on the instance level. So, here's the fix.
