### ISSUE TITLE
Repeat only sends clear notification after duration

### ISSUE THREAD

**Issue by kaiomatico** [netdata/netdata#10332]
##### Bug report summary

When setting the the global repeat duration for health alarms, the clear notifications are also being delayed with the duration. Example `/etc/netdata/netdata.conf`
```
[health]
    default repeat warning = 24h
    default repeat critical = 24h
```
##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 netdata v1.26.0, installed deb from packagecloud for ubuntu/debian

##### Component Name

Every health check is affected
##### Steps To Reproduce

1. set the default repeat warning and default repeat critical to a value, for example 1h
2. configure health_alarm_notify.conf so you get notifications, for example slack or email
3. run a stress test to generate load and trigger a load health check alarm
4. after the notification about high load is received, stop the stress test program and see that the cleared load message is delayed so that it is sent 1h later

##### Expected behavior

Default repeat warning and default repeat critical should only repeat still open warnings in health checks (which it does fine :+1:  ) , but should not delay resolved / clear notifications. Thank you very much in advance!

**Comment by ilyam8** [comment]
> Default repeat warning and default repeat critical should only repeat still open warnings in health checks (which it does fine 👍 ) , but should not delay resolved / clear notifications.

This is expected behaviour, indeed. @kaiomatico thx for reporting the issue!

**Comment by kaiomatico** [comment]
Hi everyone, is there any update yet? I have tried to find the problem in the code myself, but I can't find it. For now I have the following workaround:
1. In the `python.d.conf` enable the `alarms: yes` collector
2. Create a `health.d/alarms.conf` with the following content:
```
alarm: alarms_not_clear
on: alarms_local.alarms
lookup: 'max -1m unaligned foreach !alarms_local.* !system.entropy.lowest_entropy !system.load.load_average_1 !system.load.load_average_5 !system.cpu.10min_cpu_usage !system.softnet_stat.1min_netdev_budget_ran_outs *'
every: 1m
crit: $this > 0
repeat: critical 24h
info: Server still has alarms not cleared in the last 24h
to: noclear
```
3. In the `health_alarm_notify.conf` create the following role to only get still open warnings, but no clear messages:
```
role_recipients_slack[noclear]="#netdata|critical"
```

The problem / bug with this workaround is, that also the clear messages are being sent into the channel, even though only critical messages should be sent. Am I doing something wrong with the |crtical filter?

Thank you in advance

**Comment by kaiomatico** [comment]
So I think I found the part of the code which needs adjustment to fix the problem: 

https://github.com/netdata/netdata/blob/d127d2f6818a6ac96be0d7954d63a882969e76c6/health/health.c#L955-L975

But I can't figure out how the if/else statements work

**Comment by ilyam8** [comment]
> The problem / bug with this workaround is, that also the clear messages are being sent into the channel, even though only critical messages should be sent.

@kaiomatico severity filtering feature supposed to work like that, see https://github.com/netdata/netdata/issues/10624

**Comment by ilyam8** [comment]
@thiagoftsm @vlvkobal lets discuss this issue. This bug makes [`repeat`](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-repeat) feature unusable.

I did some tests manually and i confirm that CLEAR notification get delayed by _repeat_ seconds. I doubt it supposed to work like that.

@thiagoftsm i don't understand the following sentence from our docs

> Netdata will activate the repeat notification for CRITICAL, CLEAR and WARNING messages.

Why CLEAR is in there? What does it mean _activate the repeat notification for CLEAR messages_?

---

My tests, the alarm was CLEARed in few seconds, but, as you can see, got delayed by 5 minutes because of `repeat: warning 5m`


```cmd
[ilyam@pc ~]$ mail
mail version v14.9.22.  Type `?' for help
/var/spool/mail/ilyam: 2 messages 2 unread
▸U  1 netdata            2021-03-19 21:50  152/10997 pc needs attention - zookeeper last collected secs - zookeeper_local.requests
 U  2 netdata            2021-03-19 21:55  152/11169 pc recovered - zookeeper last collected secs - zookeeper_local.requests
```

**Comment by thiagoftsm** [comment]
Firstly thank you to report the problem and finding part of the solution.

> So I think I found the part of the code which needs adjustment to fix the problem:

You are right, for clean notification we need to define the smallest value possible to repeat_every

> But I can't figure out how the if/else statements work

These statements are used to update the `repeat_every` according what was given in our alarm/template files, but they also adjust flags when are necessary. All adjusts are done if and only if, the alarms have `repeat` keyword.

Best regards!

**Comment by ilyam8** [comment]
Fixing the bug we discovered https://github.com/netdata/netdata/issues/10847
