### ISSUE TITLE
Metric problems with v1.26.0-333-nightly

### ISSUE THREAD

**Issue by Jessimon** [netdata/netdata#10341]
Hello,

This morning a number of my servers installed v1.26.0-333-nightly.
From then on i am missing a lot of metrics in Grafana (I use a Netdata - Prometheus - Grafana stack)

Example of metrics that stopped working:
netdata_apps_mem_MiB_average
netdata_cpu_cpu_percentage_average
netdata_disk_space_GiB_average

**_Setup_**
I have about 30 servers with natdata on it.
The local Netdata streams the metrics to a central netdata server. From there the metrics are send to Prometheus and visualized in Grafana.

The central monitoring server is running Debian 10.
The others servers are Amazon linux , Debian 10 and Ubuntu 20.04.

I don't see anything wrong in the error.log.

Appreciate the help.

**Comment by vlvkobal** [comment]
Do you have `exporting.conf` in your configuration directory? It has a higher priority than the `[backend]` section of `netdata.conf`. There was [a bug in the exporting configuration](https://github.com/netdata/netdata/issues/10165#issuecomment-732048355) and a fix for that (#10323) was merged yesterday.

**Comment by Jessimon** [comment]
It is not in my /etc/netdata folder, but i see the file in /etc/netdata/orig
For the moment 333 is the latest build that is available.

Should i delete the file?

**Comment by Jessimon** [comment]
Can it be that the labels of the metrics have changed?
For example netdata_cpu_cpu_percentage_average -> netdata_cpu_cpu

I hope this is a bug, otherwise i have to change all my Grafana dashboards and this practicly also means that i lost all my historical data. (It is still there but a pain to see)

**Comment by vlvkobal** [comment]
Yes, this is a bug. I'm looking into it.

**Comment by Befisch** [comment]
We are also affected. Let us know if we can provide any further insights. (Testdata, affected metrics, ..)
Thank you, appreciate the work!
