### ISSUE TITLE
daily and manual netdata update fails

### ISSUE THREAD

**Issue by rbike** [netdata/netdata#10351]
##### Bug report summary
Daily netdata update cron job reports error 127
Manual netadata update with "bash <(curl -Ss https://my-netdata.io/kickstart.sh)" is not working (runs indefinitely)

##### OS / Environment
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

##### Netdata version
netdata v1.26.0-333-nightly

##### Component Name
Updater

##### Steps To Reproduce
1. I have installed netdata using the automatic online installation script "bash <(curl -Ss https://my-netdata.io/kickstart.sh)". 
2. Everything was running fine for weeks
3. Since this night I get the following error message from the daily netdata update cron job:
```
/etc/cron.daily/netdata-updater: line 31: /etc/cron.daily/netdata-updater.sh: No such file or directory
run-parts: /etc/cron.daily/netdata-updater exited with return code 127
```
4. I tried a manual update with "bash <(curl -Ss https://my-netdata.io/kickstart.sh)". This results in the following cmdline output:
```
 --- Found existing install of Netdata under: / ---
 --- Attempting to update existing install instead of creating a new one ---
[/root]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron
```
and then nothing happens. I had to stop the process with Ctrl-C after some time.
5. The problem persists after an uninstall and new install. 
 
##### Expected behavior
The daily netdata update should run without an error message.
The manual netdata update should not run indefinitely

**Comment by Ferroin** [comment]
Both appear to be a result of the same problem. Should have a PR up to fix this shortly.

**Comment by stdedos** [comment]
Apologies - but now that this is in, how do we force an update to happen?

Or do we have to manually apply the patch?

**Comment by stdedos** [comment]
I did that 😕
```
fork: retry: No child processes
```

ad infinitum (I didn't let it run for a long time, I have history of fork-bombing my workstation 😂)

**Comment by stdedos** [comment]
@ilyam8 ping

**Comment by ilyam8** [comment]
@stdedos i am pretty sure updates is fixed in master - i tested https://github.com/netdata/netdata/pull/10352

Before the PR it was indeed an infinite loop (netdata v1.26.0-333-nightly), but it is fixed now.

Make sure you reinstalled nd, check nd version

---

> I did that 😕
> fork: retry: No child processes

Please post seq of commands you did (copy from terminal)

**Comment by stdedos** [comment]
I _am_ on the aforementioned version.

I am doing `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry --disable-cloud --reinstall`, no progress is done: I just see `found existing install`, `sudo //usr/libexec ...` and after a while `fork: retry: No child processes`

**Comment by ilyam8** [comment]
@Ferroin please take a look^^

**Comment by Ferroin** [comment]
@stdedos Can you try `bash -x <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry --disable-cloud --reinstall` and post the exact output (it will probably be quite a lot)?

I’m not seeing the same issue myself here, which makes it rather difficult for me to figure out what exactly is going on in your case.

**Comment by stdedos** [comment]
It's very complicated to extract anything from that system to post it on Github 😕 

I see exactly the same behavior that I see on the ticket: I cannot update, because the script keeps forking itself ad infinitum. 

Anyway; this is taking too long - I'll just patch crudely patch the script and run the update....
