### ISSUE TITLE
Install script incorrectly sets PATH environment for agent binaries causing claim to fail on OSX

### ISSUE THREAD

**Issue by krital** [netdata/netdata#10356]
##### OS / Environment

```
Darwin Alexs-Mac-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```

##### Netdata version

 netdata v1.26.0-344-ga3ada604

##### Component Name

Installer script

##### Steps To Reproduce

1. sudo ./netdata-installer.sh --install /usr/local
2. Copy claim command from cloud and run sudo netdata-claim.sh -token=<XYZ> -rooms=<ABC> -url=https://app.netdata.cloud
3. Get sudo: netdata-claim.sh: command not found

##### Expected behavior

Expected behaviour is for the claim command to work

I was able to work around this by specifying the full path to the script as follows:

sudo /usr/local/netdata/usr/sbin/netdata-claim.sh -token=<XYZ> -rooms=<ABC> -url=https://app.netdata.cloud

So we need to either:

A. Change cloud to indicate the correct script claim command for OSX
B. Set the PATH correctly on OSX
C. Add a symlink to a dir already in the PATH (my preference)

**Comment by Ferroin** [comment]
Option A isn’t really an option unless we want to stop giving an exact command and instead tell users how to construct the command they need (I think we should do this regardless though, this is going to continue to be an issue no matter what platform).

Option B is not an option. We should not be mucking about with core OS-level configuration just to support a feature that not all users will want to use.

Option C should work.

**Comment by krital** [comment]
Ok in that case can I suggest we add symlinks (option C) to netdata, netdatacli and the updater / claim scripts in /usr/local/sbin which is in line with what brew does?

**Comment by stelfrag** [comment]
@Ferroin should we close this one?

**Comment by Ferroin** [comment]
Yes, I _think_ this can safely be closed now as the preferred claiming approach is to use the kickstart script, which _should_ find the claiming script correctly on macOS now.
