### ISSUE TITLE
Alarm notification for Telegram does not work using the kickstart-static64.sh installation

### ISSUE THREAD

**Issue by Simonmicro** [netdata/netdata#10359]
_This has been reported before in #9494, but did not receive any response since it has been considered fixed._

##### Bug report summary
Telegram notifications does not work for real alarms (see the log below). Using the test (https://learn.netdata.cloud/docs/agent/health/notifications/email/) they work normally.

```
curl: (77) error setting certificate verify locations:  CAfile: /opt/netdata/etc/ssl/certs/ca-bundle.crt CApath: none
2020-12-04 13:57:46: alarm-notify.sh: ERROR: failed to send telegram notification for: [hostname] [alertname] is CRITICAL to '[chatid]' with HTTP response status code 000.
```

##### OS / Environment
```
$ cat /etc/debian_version
10.6
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version
 ```
$ /opt/netdata/bin/netdata -V
netdata v1.26.0-333-gae04be5a
$ $(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V
2020-12-09 19:27:06: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2020-12-09 19:27:06: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
2020-12-09 19:27:06: netdata ERROR : MAIN : LISTENER: IPv4 bind() on ip '0.0.0.0' port 19999, socktype 1 failed. (errno 98, Address in use)
2020-12-09 19:27:06: netdata ERROR : MAIN : LISTENER: Cannot bind to ip '0.0.0.0', port 19999
2020-12-09 19:27:06: netdata ERROR : MAIN : LISTENER: IPv6 bind() on ip '::' port 19999, socktype 1 failed. (errno 98, Address in use)
2020-12-09 19:27:06: netdata ERROR : MAIN : LISTENER: Cannot bind to ip '::', port 19999
2020-12-09 19:27:06: netdata FATAL : MAIN : LISTENER: Cannot listen on any API socket. Exiting... # : Invalid argument

2020-12-09 19:27:06: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2020-12-09 19:27:06: netdata INFO  : MAIN : EXIT: cleaning up the database...
2020-12-09 19:27:06: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
2020-12-09 19:27:06: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
```

##### Component Name
`health/alarm-notify.sh`

##### Steps To Reproduce
_I'm experiencing this on multiple instances, all with different configs. I updated them all to make sure I'm using the latest version, but the issue persists..._

1. Install current stable Debian
2. Install Netdata using `kickstart-static64.sh`
3. Setup your Telegram bot inside the settings
4. Make sure it works by sending a test alarm
5. Run something like `fallocate -l 99G bigfile` to trigger a real alert (depending on your system)
6. Watch your logs...

##### Expected behaviour
Well, it should work?

**Comment by OdysLam** [comment]
Thanks for posting this bug @Simonmicro , we will make sure to get back to you!

**Comment by thiagoftsm** [comment]
Hello @Simonmicro ,

I want to confirm something with you, but before I will say what I did:

1 -  I created a VM with Slackware Current and I installed Netdata using `kickstart-static64.sh`.
2 - I shutdown `netdata` process
3 - I edited the file `/opt/netdata/etc/netdata/health_alarm_notify.conf` to add my `Telegram` configuration.
4 - I changed permission of the file for `netdata.netdata`.
5 - I created the following alarm:

```
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -3s at 0 every 3 percentage foreach *
 units: %
 every: 1s
  warn: $this > 1
  crit: $this > 4
```

6  - I went to the directory `/opt/netdata/usr/libexec/netdata/plugins.d`
7 - I ran `./alarm-notify.sh test`
8 - I ran `/opt/netdata/usr/sbin/netdata`
9 - I ran the following script: `for i in `seq 0 1000000` ; do echo $i > /dev/null ; done`

With these steps, I received alarm from the steps `7` and `9`, so I cannot recreate the cited bug.

Now the doubts:

1 -  Where did you create your `health_alarm_notify.conf`?
2 - What are the file owner?
3 - Do you have some health errors inside your `/opt/netdata/var/log/netdata`?

Best regards!

**Comment by Simonmicro** [comment]
@thiagoftsm Hmm, I executed `sudo /opt/netdata/etc/netdata/edit-config health_alarm_notify.conf` to edit the respective file and inserted the needed credentials. I'll resetup it from scratch later on and will then document every command I executed in which order and what actions I took.
Stay tuned :)

**Comment by Simonmicro** [comment]
Okay, I was - again - able to reproduce the bug. As I have no idea how to create a custom alarm I went with my `fallocate` (more realistic) trigger again - here are my notes:
```
Created Debian VM (using libvirtd) with fresh netinst iso from the website
Assigned: 1GB ram, 2 cores, 20GB disk
All defaults, Europe timezone, no desktop+printer service, added ssh utils

Installed curl via apt
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)
sudo /opt/netdata/etc/netdata/edit-config health_alarm_notify.conf

Modified respective fields (the file was full with example stuff, so definitively not empty!):
SEND_TELEGRAM="YES"
TELEGRAM_BOT_TOKEN="..."
DEFAULT_RECIPIENT_TELEGRAM="..."

CTRL+X to exit nano

cd /opt/netdata/usr/libexec/netdata/plugins.d
./alarm-notify.sh test

-> Works! I've got the expected 3 Telegram msgs!

Now with a real alarm:

cd
fallocate -l 15G bigfile
tail -f /opt/netdata/var/log/netdata/*

[WAITED for 2 minutes]

Got error & no telegram message:

curl: (77) error setting certificate verify locations:  CAfile: /opt/netdata/etc/ssl/certs/ca-bundle.crt CApath: none
2020-12-11 21:49:47: alarm-notify.sh: ERROR: failed to send telegram notification for: debian disk_space._.disk_space_usage is WARNING to '[chatid]' with HTTP response status code 000.
```

And just to be sure: The same behaviour after rebooting the fresh vm.

> 1 - Where did you create your health_alarm_notify.conf?
2 - What are the file owner?
3 - Do you have some health errors inside your /opt/netdata/var/log/netdata?

1: Idk - `edit_config` did everything it there `/opt/netdata/etc/netdata/`
2: `la -la` reports: `-rw-r--r--  1 netdata netdata` for the config
3: A ton of boot-up errors about already existing charts. This triggers the flood protection and end... When you want to see more, you may need to recreate the vm as described above. This way you can also investigate further `:|

**Comment by Simonmicro** [comment]
*Bump*

**Comment by thiagoftsm** [comment]
Hello guys,

I returned to this problem today, and I observed that when I installed Netdata using [this](https://github.com/netdata/netdata/releases/download/v1.28.0/netdata-v1.28.0.gz.run) static binary, I did not have problems to receive alarms on Telegram or Slack, I will test now `kickstart-static64.sh`.

Best regards!

**Comment by thiagoftsm** [comment]
I tested again using the link `bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)` and I had success to received alarms on Telegram and Slack. I had success using the following enviroment:

```
Distribution: Slackware Current
Kernel: 5.10.6
Curl Version: 7.74
```

My `health_alarm_notify.conf` has the following configuration for Telegram:

```
SEND_TELEGRAM="YES"
TELEGRAM_BOT_TOKEN="MY_TOKEN"
DEFAULT_RECIPIENT_TELEGRAM="-VALUE"
```
please, pay attention that `DEFAULT_RECIPIENT_TELEGRAM` is a negative value.

I had analogous results using `static binary` or compiled Netdata with the following alarm:

```
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -3s at 0 every 3 percentage foreach *
 units: %
 every: 1s
  warn: $this > 1
  crit: $this > 4
```

I will install now a Debian 10 on a VM and try to recreate the issue there, but at least on Slackware the static binary is working as expected.

Best regards!

**Comment by ilyam8** [comment]
@Ferroin 

see

```
curl: (77) error setting certificate verify locations:  CAfile: /opt/netdata/etc/ssl/certs/ca-bundle.crt CApath: none
```

i have same problem

```cmd
[pc etc]# ls -l | grep ssl
lrwxrwxrwx  1 root    root       8 янв 11 22:22 ssl -> /etc/ssl
```

=>

```cmd
[pc etc]# ls /opt/netdata/etc/ssl/certs/ca-bundle.crt
ls: cannot access '/opt/netdata/etc/ssl/certs/ca-bundle.crt': No such file or directory

[pc etc]# ls /opt/netdata/etc/ssl/certs/ca-certificates.crt
/opt/netdata/etc/ssl/certs/ca-certificates.crt
```

I think it should be `ca-certificates.crt`, not `ca-bundle.crt`.

**Comment by ilyam8** [comment]
system `curl`

```cmd
[ilyam@pc bin]$ curl-config --ca
/etc/ssl/certs/ca-certificates.crt
```

[bundeld `curl`](https://github.com/netdata/netdata/blob/40da71e1eb0b65e24745df332d8e28a716830b00/packaging/makeself/jobs/50-curl-7.73.0.install.sh#L26)
```cmd
[ilyam@pc bin]$ pwd
/opt/netdata/bin
[ilyam@pc bin]$ ./curl-config --ca
/opt/netdata/etc/ssl/certs/ca-bundle.crt
```

**Comment by thiagoftsm** [comment]
@ilyam8 I agree that this is the problem, but I installed Netdata using kickstart-static64 on a Debian 10.7 VM and I verified that we do not have more the symbolic link at `/opt/netdata/etc`, and thanks this I can send alarms and I also could claim the agent.

@Simonmicro , please, could you run the following commands:

```bash
# cd /opt/netdata/etc/netdata
# mv ssl old_ssl
# mkdir ssl
# chown -R netdata.netdata ssl
```

And after this, please, restart Netdata. 

Best regards!

**Comment by Simonmicro** [comment]
@thiagoftsm

First, sorry that it took a while to report back.
Secondly, you commands did not work - but there is a good possibility that I messed something else up, as I have not the vm ↑ from before available right now.

@Ferroin Any estimate how (and when :sweat_smile:) I could test this update (before?) it rolls out for everyone? Just in case my help/confirmation could be needed :grin:

**Comment by Ferroin** [comment]
@Simonmicro Given that the fixes have been merged, tonight’s nightly builds (should be published by 01:00 UTC tomorrow, but you may need to wait until 02:00 UTC to see the new version due to issues with how GCS handles caching) should have the bug fixed.

Thanks for your interest in helping test though, it’s always great to see we have users who care enough about Netdata to contribute!
