### ISSUE TITLE
Redefinition of abs() macro causes problems with C++ plugins.

### ISSUE THREAD

**Issue by KickerTom** [netdata/netdata#10353]
##### Bug report summary
Related to #10178. When using libnetdata from C++, it is easy to hit a problem with redefinition of abs macro in libnetdata.h, as C++ does not allow this kind of redefinitions. Also, it can be a bit misleading to redefine "standard" functions.

##### Netdata version
master from git 

##### Component Name
libnetdata, netdata core.

##### Steps To Reproduce
Include libnetdata header in C++ source along with some 'pure' C++ headers, e.g. boost/regex.hpp. Compilation of the C++ code fails with clashing names.

**Comment by OdysLam** [comment]
Thanks, @KickerTom for reporting this. We have communicated it internally and we will come back to you shortly!
