### ISSUE TITLE
Netdata update fails with "bash: warning: shell level (1000) too high, resetting to 1"

### ISSUE THREAD

**Issue by arnowelzel** [netdata/netdata#10366]
##### Bug report summary
When I try to update an existing Netdata installation with `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` I only get the following error and Netdata will not be updated:

```
 --- Found existing install of Netdata under: / ---
 --- Attempting to update existing install instead of creating a new one ---
[/root]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron bash: warning: shell level (1000) too high, resetting to 1
bash: warning: shell level (1000) too high, resetting to 1
bash: warning: shell level (1000) too high, resetting to 1
bash: warning: shell level (1000) too high, resetting to 1
bash: warning: shell level (1000) too high, resetting to 1
bash: warning: shell level (1000) too high, resetting to 1
```

The last line `bash: warning: shell level (1000) too high, resetting to 1` will repeat until I stop the script with Ctrl+C.

##### OS / Environment

```
Linux example.com 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

netdata v1.26.0-333-nightly

##### Steps To Reproduce

Execute `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`.

##### Expected behavior

The updater script works as usual.

**Comment by Ferroin** [comment]
This is a known bug that has been fixed in the current nightlies.

You will need to manually re-run the installer you originally used, adding the `--reinstall` option to get the newest version.

Please see: https://community.netdata.cloud/t/periodically-anacron-job-cron-daily-on-localhost-reports-a-problem-with-netdata-updater-sh/612 for more info.

**Comment by Ferroin** [comment]
Pinning this issue for visibility to users.
