### ISSUE TITLE
Problem: netdata-updater.sh

### ISSUE THREAD

**Issue by drkt7** [netdata/netdata#10368]
Hi

with netdata (Your netdata version: v1.26.0-333-gae04be5a), i have this message: (with cron)

/etc/cron.daily/netdata-updater:
/etc/cron.daily/netdata-updater: line 31: /etc/cron.daily/netdata-updater.sh: No such file or directory

Thanks

**Comment by ilyam8** [comment]
Hi @drkt7 👋 

Looks like same issue https://github.com/netdata/netdata/issues/10351

> netdata v1.26.0-333-nightly
> /etc/cron.daily/netdata-updater: line 31: /etc/cron.daily/netdata-updater.sh: No such file or directory

Fixed in https://github.com/netdata/netdata/issues/10351

See https://github.com/netdata/netdata/issues/10366#issuecomment-742699376 (basically you need reinstall latest master)
