### ISSUE TITLE
Persist `$TMPDIR` from environment on install to allow usage in updater.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#10377]
As in the title.

This would allow users who install Netdata and set a custom value for `$TMPDIR` to not need to change anything to use the same location for the updater script when using auto-updates.

Should still be overridden if `$TMPDIR` is set at updater runtime, but should take precedence over `/tmp` and `$PWD` when trying to find a location to place temporary files.

**Comment by therealgilles** [comment]
One option would be to add the variable to /etc/netdata/netdata.conf or a separate config file, and have the updater read it.
