### ISSUE TITLE
Agent installed using installer script needs sudo to run on OSX

### ISSUE THREAD

**Issue by krital** [netdata/netdata#10390]
##### Bug report summary

Agent installed using installer script needs sudo to run on OSX. This is because the script that runs as sudo seems to create some files as root instead of the netdata user. As a result you need sudo to start the agent.
##### OS / Environment

```
Darwin alexs-mac-pro.lan.lan 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H114
```

##### Netdata version

 netdata v1.26.0-344-ga3ada604

##### Component Name

Agent installer script 
##### Steps To Reproduce

1. Run the installer script as per the documentation
2. Try to run the agent without sudo
3. Agent exits because of permissions

##### Expected behavior

Agent should run without requiring sudo using the netdata user created during installation.

**Comment by iigorkarpov** [comment]
@krital sorry for long silence. They say that better late than never; I doubt that but I am looking at your issue now and have to ask you, is this still actual? Many things have changed during this time.

**Comment by iigorkarpov** [comment]
Please do if you have some spare time.

**Comment by krital** [comment]
Ok so I gave it another go, it didnt requite sudo but asked for my password which is fine. However it failed to install with the following: 

`configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.
 FAILED  ''

 ABORTED  Failed to configure Netdata sources.


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata  .-.   .-.   .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'               '-'   '-'   '-'   '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

 ABORTED  Netdata failed to build for an unknown reason.

 FAILED

The following non-fatal warnings or errors were encountered:

  - Command "/bin/bash /var/folders/pr/fn75mgj90l3c1pzpn9jt_slc0000gn/T/netdata-kickstart-XXXXXXXXXX.Ei0g5YDs/install-required-packages.sh netdata" failed with exit code 1.
  - Failed to install all required packages, but installation might still be possible.
  - Command "sudo ./netdata-installer.sh --install-no-prefix /usr/local/netdata --require-cloud" failed with exit code 1.

 ABORTED  netdata-installer.sh failed to run correctly.`

**Comment by krital** [comment]
I actually installed libuv manually (compiled locally) and it is still failing. This could be because its looking for headers in the wrong place or that you are assuming the wrong CPU architecture? (I am running on an Apple Silicon Mac)

**Comment by krital** [comment]
Ok so I tried to install on an intel Mac and it fails with a compilation error this time:

`  CC       libnetdata/eval/eval.o
libnetdata/clocks/clocks.c:192:19: error: implicit declaration of function 'clock_nanosleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    while( (ret = clock_nanosleep(clock, TIMER_ABSTIME, &req, NULL)) != 0 ) {
                  ^
libnetdata/clocks/clocks.c:192:19: note: did you mean 'clock_sleep'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/mach/mach.h:137:25: note: 'clock_sleep' declared here
extern kern_return_t    clock_sleep(mach_port_t,
                        ^
libnetdata/clocks/clocks.c:192:42: error: use of undeclared identifier 'TIMER_ABSTIME'
    while( (ret = clock_nanosleep(clock, TIMER_ABSTIME, &req, NULL)) != 0 ) {
                                         ^
libnetdata/clocks/clocks.c:347:21: error: implicit declaration of function 'clock_nanosleep' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    while ((errno = clock_nanosleep(CLOCK_REALTIME, 0, &req, &rem)) != 0) {
                    ^
  CC       libnetdata/libnetdata.o
3 errors generated.
  CC       libnetdata/locks/locks.o
make[2]: *** [libnetdata/clocks/clocks.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
 FAILED  ''

 ABORTED  Failed to build Netdata.

 FAILED`

Please note that on both CPU architectures the required packages say they can not be all found but tries to install anyway. Sounds like we can close this issue and open 2 new ones, one per CPU architecture?

**Comment by iigorkarpov** [comment]
Just to be sure - did you use the kickstart script?

**Comment by krital** [comment]
Yes, specifically used the command Netdata.cloud suggested to add an agent:

`curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token T69***** --claim-rooms 8cf**** --claim-url https://app.netdata.cloud`

**Comment by cpipilas** [comment]
Original issue has been fixed.
