### ISSUE TITLE
netdata: symbol lookup error: netdata: undefined symbol: _ZN6google8protobuf8internal24proto3_preserve_unknown_E

### ISSUE THREAD

**Issue by sniffski** [netdata/netdata#10409]
##### Bug report summary
I was trying to update from v1.26.0-333-nightly to 1.28.0 stable and got the following error when trying to start the service
"netdata: symbol lookup error: netdata: undefined symbol: _ZN6google8protobuf8internal24proto3_preserve_unknown_E"
Already tried updating protobuf with pip, but that doesn't solve the issue.

##### OS / Environment
```
$ uname -a; grep -Hv "^#" /etc/*release
Linux xxxxxxxxx-xxx 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version
$ dpkg -l | grep -i netdata
ii  netdata                                                     1.28.0                                      amd64        real-time charts for system monitoring

$ netdata -V
netdata: symbol lookup error: netdata: undefined symbol: _ZN6google8protobuf8internal24proto3_preserve_unknown_E 

##### Component Name
netdata

##### Steps To Reproduce
Just install v1.26.0-333-nightly and try to update with "curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.deb.sh | sudo bash" and then "sudo apt install netdata"

##### Expected behavior
I was expecting to get newer netdata version 1.28.0 up and running but that didn't happen.

**Comment by vlvkobal** [comment]
Do you have `libprotobuf` installed? What version?

**Comment by sniffski** [comment]
below:
```
$ dpkg -l | grep libprotobuf
ii  libprotobuf-c-dev:amd64                                     1.3.3-1                                     amd64        Protocol Buffers C static library and headers (protobuf-c)
ii  libprotobuf-c1:amd64                                        1.3.3-1                                     amd64        Protocol Buffers C shared library (protobuf-c)
ii  libprotobuf-dev:amd64                                       3.6.1.3-2ubuntu5                            amd64        protocol buffers C++ library (development files) and proto files
ii  libprotobuf-lite17:amd64                                    3.6.1.3-2ubuntu5                            amd64        protocol buffers C++ library (lite version)
ii  libprotobuf17:amd64                                         3.6.1.3-2ubuntu5                            amd64        protocol buffers C++ library
```

**Comment by vlvkobal** [comment]
Hmm, I can't reproduce the issue. Could you remove all `libprotobuf` packages, run `apt autoremove` and install Netdata again?

**Comment by sniffski** [comment]
that definitely made my heart skip a few beats... it removed gnome-session, dgm and few others... :D
anyway I reinstalled some of them before autoremove and now I have the same netdata issue and only three of these protobuf packages:
```
$ dpkg -l | grep protobuf
ii  libprotobuf-lite17:amd64                                    3.6.1.3-2ubuntu5                            amd64        protocol buffers C++ library (lite version)
ii  libprotobuf17:amd64                                         3.6.1.3-2ubuntu5                            amd64        protocol buffers C++ library
ii  python3-protobuf                                            3.6.1.3-2ubuntu5                            amd64        Python 3 bindings for protocol buffers
```

**Comment by vlvkobal** [comment]
> that definitely made my heart skip a few beats...

:scream: I'm sorry about that.

What is the output of
`ldd /sbin/netdata | grep protobuf`,
`ldconfig -p | grep protobuf`, and
`nm -D /lib/x86_64-linux-gnu/libprotobuf.so.17 | grep unknown_E`
on your system?

**Comment by sniffski** [comment]
Thank you for your time in investigating this with me! Below is the info:
```
$ ldd /usr/sbin/netdata | grep protobuf
	libprotobuf.so.17 => /usr/local/lib/libprotobuf.so.17 (0x00007f68f58bb000)
$ ldconfig -p | grep protobuf
	libprotobuf.so.17 (libc6,x86-64) => /usr/local/lib/libprotobuf.so.17
	libprotobuf.so.17 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libprotobuf.so.17
	libprotobuf.so (libc6,x86-64) => /usr/local/lib/libprotobuf.so
	libprotobuf-lite.so.17 (libc6,x86-64) => /usr/local/lib/libprotobuf-lite.so.17
	libprotobuf-lite.so.17 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.17
	libprotobuf-lite.so (libc6,x86-64) => /usr/local/lib/libprotobuf-lite.so
$ nm -D /lib/x86_64-linux-gnu/libprotobuf.so.17 | grep unknown_E
nm: '/lib/x86_64-linux-gnu/libprotobuf.so.17': No such file
$ nm -D /usr/local/lib/libprotobuf.so.17 | grep unknown_E
$
```

**Comment by vlvkobal** [comment]
You have two libraries installed in different places and the one Netdata is linked against is definitely a lame one - it doesn't have the `_ZN6google8protobuf8internal24proto3_preserve_unknown_E` symbol. How did you install `/usr/local/lib/libprotobuf.so.17`? Is it possible that you installed it from the source? You should delete it. Look at the output on my machine:
```
vlad@ubuntu-20-04:~$ ldd /sbin/netdata | grep protobuf
        libprotobuf.so.17 => /lib/x86_64-linux-gnu/libprotobuf.so.17 (0x00007fdbbd0d5000)
vlad@ubuntu-20-04:~$ ldconfig -p | grep protobuf
        libprotobuf.so.17 (libc6,x86-64) => /lib/x86_64-linux-gnu/libprotobuf.so.17
vlad@ubuntu-20-04:~$ nm -D /lib/x86_64-linux-gnu/libprotobuf.so.17 | grep unknown_E
00000000002f53b8 D _ZN6google8protobuf8internal24proto3_preserve_unknown_E
vlad@ubuntu-20-04:~$
```

**Comment by sniffski** [comment]
I think initially the nightly version was installed from source then I've tried updating with stable version from apt. Can you advice how do I remove completely netdata and then install stable version from apt?

**Comment by sniffski** [comment]
quite destructive :D
```
$ sudo apt purge libprotobuf17 libprotobuf-lite17 python3-protobuf netdata
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  android-framework-res android-libaapt android-libandroidfw fonts-cantarell gir1.2-accountsservice-1.0 gir1.2-gck-1 gir1.2-gcr-3 gir1.2-gdm-1.0
  gir1.2-graphene-1.0 gir1.2-handy-0.0 gir1.2-mutter-6 gir1.2-nma-1.0 gir1.2-rsvg-2.0 gnome-shell-common libantlr3-runtime-java libbasicusageenvironment1
  libcddb2 libcommons-cli-java libcommons-io-java libcommons-lang3-java libcrypto++6 libdca0 libdvbpsi10 libedata-cal-2.0-1 libgdm1 libgroupsock8 libixml10
  libkate1 liblastfm5-1 liblivemedia77 libmpcdec6 libmygpo-qt5-1 libnetfilter-acct1 libopenmpt-modplug1 libplacebo7 libproxy-tools libresid-builder0c2a
  libsdl-image1.2 libsidplay2 libsmali-java libspatialaudio0 libsrt1 libssh2-1 libupnp13 libusageenvironment3 libvlc-bin libvlc5 libvlccore9 libxmlunit-java
  libxpp3-java switcheroo-control ubuntu-wallpapers ubuntu-wallpapers-focal vlc-bin vlc-data vlc-plugin-notify vlc-plugin-qt vlc-plugin-samba
  vlc-plugin-skins2 vlc-plugin-video-output vlc-plugin-video-splitter vlc-plugin-visualization xwayland yaru-theme-gnome-shell
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  aapt* apktool* chrome-gnome-shell* evolution-data-server* gdm3* gnome-online-accounts* gnome-session* gnome-shell* gnome-shell-extension-prefs*
  gnome-tweak-tool* gnome-tweaks* libebook-1.2-20* libebook-contacts-1.2-3* libedata-book-1.2-26* libphonenumber7* libprotobuf-lite17* libprotobuf17* netdata*
  python3-macaroonbakery* python3-protobuf* vlc* vlc-plugin-base*
0 upgraded, 0 newly installed, 22 to remove and 0 not upgraded.
After this operation, 34,9 MB disk space will be freed.
Do you want to continue? [Y/n] 
```

**Comment by vlvkobal** [comment]
Can you find `_ZN6google8protobuf8internal24proto3_preserve_unknown_E` in any file from the `ldconfig` list?

**Comment by vlvkobal** [comment]
What do the following commands show?
```
cat /etc/ld.so.conf
cat /etc/ld.so.conf.d/*
```

**Comment by sniffski** [comment]
Not sure if that's what you asked, but:
```
$ for l in $(ldconfig -p | grep protobuf | awk -F'=> ' '{print $2}'); do nm -D $l | grep "_ZN6google8protobuf8internal24proto3_preserve_unknown_E" && echo $l; done
00000000002f53b8 D _ZN6google8protobuf8internal24proto3_preserve_unknown_E
/usr/lib/x86_64-linux-gnu/libprotobuf.so.17
00000000000742b0 D _ZN6google8protobuf8internal24proto3_preserve_unknown_E
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.17
```

**Comment by sniffski** [comment]
> What do the following commands show?
> 
> ```
> cat /etc/ld.so.conf
> cat /etc/ld.so.conf.d/*
> ```
```
$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf
$ cat /etc/ld.so.conf.d/*
/usr/lib/x86_64-linux-gnu/libfakeroot
# Multiarch support
/usr/local/lib/i386-linux-gnu
/lib/i386-linux-gnu
/usr/lib/i386-linux-gnu
/usr/local/lib/i686-linux-gnu
/lib/i686-linux-gnu
/usr/lib/i686-linux-gnu
# libc default configuration
/usr/local/lib
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
# Legacy biarch compatibility support
/lib32
/usr/lib32
# Legacy biarch compatibility support
/libx32
/usr/libx32
```

**Comment by vlvkobal** [comment]
Quite a thick ld path configuration :grin:

**Comment by vlvkobal** [comment]
Well. We don't know if any software, installed on your machine, depends on `/usr/local/lib/libprotobuf.so.17` and we don't know how to delete it correctly. You can try simply renaming `/usr/local/lib/libprotobuf.so.17` -> `/usr/local/lib/libprotobuf.so.17.bak` and run `ldconfig` without any options.

**Comment by vlvkobal** [comment]
... and check if Netdata will be linked to `/usr/lib/x86_64-linux-gnu/libprotobuf.so.17` (`ldd /sbin/netdata | grep protobuf`).

**Comment by vlvkobal** [comment]
If something goes wrong with other software, rename the library back and run `ldconfig`.

**Comment by sniffski** [comment]
> ... and check if Netdata will be linked to `/usr/lib/x86_64-linux-gnu/libprotobuf.so.17` (`ldd /sbin/netdata | grep protobuf`).

$ ldd /usr/sbin/netdata | grep protobuf
	libprotobuf.so.17 => /usr/local/lib/libprotobuf.so.17 (0x00007f0ef0412000)

**Comment by sniffski** [comment]
> If something goes wrong with other software, rename the library back and run `ldconfig`.

f.. it! that won't be under your issues trend! :rofl:

**Comment by sniffski** [comment]
ldconfig always restore back the link to shitty /usr/local/lib...

**Comment by vlvkobal** [comment]
I've found a way to delete the library. `ldconfig` is too smart. It searches for libraries and makes fresh links to them. You should move the library out of its directory to a place that is not configured in `ld.so.conf`.

**Comment by sniffski** [comment]
> I've found a way to delete the library. `ldconfig` is too smart. It searches for libraries and makes fresh links to them. You should move the library out of its directory to a place that is not configured in `ld.so.conf`.

Just did exactly the same! Thanks! I think it is solved now! :smile:
