### ISSUE TITLE
1.27.0.deb built without Cloud dependencies

### ISSUE THREAD

**Issue by dtipro** [netdata/netdata#10403]
##### Bug report summary
After updating to 1.27.0 via the .deb package my existing nodes are no longer able to communicate with Netdata Cloud and new nodes are unable to be claimed.  When opening the dashboard I see a message stating:

> The installer could not prepare the required dependencies to enable Netdata Cloud functionality

When trying to claim a node I receive:

> This agent was built without the dependencies for Cloud and cannot be claimed

This was working with the 1.26.0 .deb package and works if 1.27.0 is installed via the kickstart script.

##### OS / Environment
Can reproduce on real hardware and in a VM
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
netdata v1.27.0
 

##### Component Name
packaging

##### Steps To Reproduce

1. Install netdata 1.27.0 using the .deb from packagecloud
2. Attempt to register with Netdata Cloud

##### Expected behavior
Netdata agent registers with Netdata Cloud

**Comment by stevecorya** [comment]
I have the same issue with Debian 10; upgrade from 1.26.0 to 1.27.0 causes eight nodes to display "All nodes have errors" in the dashboard. Downgrading to 1.26.0 brings them all back up. 

I have not tried re-installing 1.27.0 with the kickstart script.

**Comment by Ferroin** [comment]
There was a bug with the Cloud code in 1.27.0 that we unfortunately did not catch until after the release. We’re in the process of doing a new release that includes a fix for this.

**Comment by derobert** [comment]
Seeing this with 1.28.0 from packagecloud / Ubuntu Xenial too.

**Comment by osmanlicilegi** [comment]
Same here with 1.28.0 from packagecloud on Ubuntu Bionic.

**Comment by CberYellowstone** [comment]
centos7.9 from packagecloud have this bug too

**Comment by CberYellowstone** [comment]
> There was a bug with the Cloud code in 1.27.0 that we unfortunately did not catch until after the release. We’re in the process of doing a new release that includes a fix for this.

but the bug is still in 1.28.0

**Comment by Ferroin** [comment]
The bug in the cloud code was unrelated to the bug causing the binary packages to not have cloud support. I’ve just opened a PR that (should) fix cloud support in our binary packages (it’s actually been broken since the end of October).
