### ISSUE TITLE
Date-picker for custom dashboard

### ISSUE THREAD

**Issue by rider8581** [netdata/netdata#10407]
Good day!

Thank you for creating this awesome project.

I am impressed cause this project is very useful and easy-to-use.

Now I am trying to create the custom dashboard, however, I couldn't place a date-picker on my custom dashboard.

![image](https://user-images.githubusercontent.com/52605718/102687515-9cc96200-41bd-11eb-87ba-f518c1927808.png)

Would you kindly confirm if it is possible to put this date-picker on my custom dashboard?

if possible, how should I do it?

Looking forward to your kind reply.

Thank you very much.

**Comment by jacekkolasa** [comment]
Hi @rider8581 ! This is currently not possible, but I agree it would be good to have.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.

**Comment by manos-saratsis** [comment]
@rider8581 you can use [dashboards](https://learn.netdata.cloud/docs/cloud/visualize/dashboards) on Netdata Cloud including the date time picker for charts and component synchronization. Not scoped to be added to agent custom dashboards
