### ISSUE TITLE
Cannot update netdata with netdata-updater.sh

### ISSUE THREAD

**Issue by benpro** [netdata/netdata#10406]
##### Bug report summary

```
wget raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-updater.sh
chmod +x netdata-updater.sh
./netdata-updater.sh 
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
[...]
Strange loop...
```

Same with bash -x :

```
bash -x ./netdata-updater.sh --not-running-from-cron --no-self-update
+ set -e
+++ dirname -- ./netdata-updater.sh
++ CDPATH=
++ cd -- .
++ pwd -P
+ script_dir=/root
+ '[' -x /root/netdata-updater ']'
+ script_source=/root/netdata-updater.sh
+ logfile=
+ ndtmpdir=
+ trap cleanup EXIT
+ '[' -n --not-running-from-cron ']'
+ '[' --not-running-from-cron = --not-running-from-cron ']'
+ NETDATA_NOT_RUNNING_FROM_CRON=1
+ shift 1
+ '[' -n --no-self-update ']'
+ '[' --no-self-update = --not-running-from-cron ']'
+ '[' --no-self-update = --no-updater-self-update ']'
+ '[' --no-self-update = --tmpdir-path ']'
+ break
+ '[' '!' -t 1 ']'
+ : /etc/netdata/.environment
+ source /etc/netdata/.environment
++ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
++ CFLAGS=-O2
++ LDFLAGS=
++ NETDATA_PREFIX=
++ NETDATA_CONFIGURE_OPTIONS=' --with-bundled-lws=externaldeps/libwebsockets'
++ NETDATA_ADDED_TO_GROUPS=' adm proxy'
++ INSTALL_UID=0
++ NETDATA_GROUP=netdata
++ REINSTALL_OPTIONS='--auto-update --stable-channel --disable-telemetry '
++ RELEASE_CHANNEL=stable
++ IS_NETDATA_STATIC_BINARY=no
++ NETDATA_LIB_DIR=/var/lib/netdata
+ export NETDATA_LIB_DIR=/var/lib/netdata
+ NETDATA_LIB_DIR=/var/lib/netdata
+ [[ -z '' ]]
+ [[ -f /var/lib/netdata/netdata.tarball.checksum ]]
++ cat /var/lib/netdata/netdata.tarball.checksum
+ NETDATA_TARBALL_CHECKSUM=1a4f3bf630088c06acfdc7b639cf6fa182077666323d671ee525af13b06f77ce
+ export NETDATA_NIGHTLIES_BASEURL=https://storage.googleapis.com/netdata-nightlies
+ NETDATA_NIGHTLIES_BASEURL=https://storage.googleapis.com/netdata-nightlies
++ id -u
+ '[' 0 '!=' 0 ']'
+ '[' -t 2 ']'
+ exec
+ self_update
+ '[' -z '' ']'
+ newer_commit_date
+ echo 'Checking if a newer version of the updater script is available.'
Checking if a newer version of the updater script is available.
+ command -v jq
+ command -v python
+ '[' -z '' ']'
+ commit_date=9999-12-31T23:59:59Z
+ '[' -e /root/netdata-updater.sh ']'
++ date -r /root/netdata-updater.sh +%s
+ script_date=1608369535
++ date -d 9999-12-31T23:59:59Z +%s
+ '[' 253402300799 -ge 1608369535 ']'
+ echo 'Downloading newest version of updater script.'
Downloading newest version of updater script.
++ create_tmp_directory
++ '[' -n '' ']'
++ '[' -z '' ']'
++ _cannot_use_tmpdir /tmp
++ local testfile ret
+++ TMPDIR=/tmp
+++ mktemp -q -t netdata-test.XXXXXXXXXX
++ testfile=/tmp/netdata-test.nH7QA7dnVL
++ ret=0
++ '[' -z /tmp/netdata-test.nH7QA7dnVL ']'
++ printf '#!/bin/sh\necho SUCCESS\n'
++ chmod +x /tmp/netdata-test.nH7QA7dnVL
+++ /tmp/netdata-test.nH7QA7dnVL
++ '[' SUCCESS = SUCCESS ']'
++ ret=1
++ rm -f /tmp/netdata-test.nH7QA7dnVL
++ return 1
++ TMPDIR=/tmp
++ mktemp -d -t netdata-updater-XXXXXXXXXX
+ ndtmpdir=/tmp/netdata-updater-bnsA1BqAdM
+ cd /tmp/netdata-updater-bnsA1BqAdM
+ _safe_download https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-updater.sh ./netdata-updater.sh
+ url=https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-updater.sh
+ dest=./netdata-updater.sh
+ command -v curl
+ curl -sSL --connect-timeout 10 --retry 3 https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-updater.sh
+ return 0
+ chmod +x ./netdata-updater.sh
++ pwd
+ exec ./netdata-updater.sh --not-running-from-cron --no-self-update --tmpdir-path /tmp/netdata-updater-bnsA1BqAdM
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
[...] looping
```

##### OS / Environment

```
uname -a; grep -Hv "^#" /etc/*release
Linux lxd00 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

```

##### Netdata version

 
```
netdata -V
netdata v1.27.0
```

##### Steps To Reproduce

1. Try to update
2. It loops

##### Expected behavior

Should update sucessfully.

**Comment by benpro** [comment]
Seems related to this part:

```
+ newer_commit_date
+ echo 'Checking if a newer version of the updater script is available.'
Checking if a newer version of the updater script is available.
+ command -v jq
+ command -v python
+ '[' -z '' ']'
+ commit_date=9999-12-31T23:59:59Z
```

**Comment by benpro** [comment]
```
  if command -v jq > /dev/null 2>&1; then
    commit_date="$(_safe_download "https://api.github.com/repos/netdata/netdata/commits?path=packaging%2Finstaller%2Fnetdata-updater.sh&page=1&per_page=1" /dev/stdout | jq '.[0].commit.committer.date' | tr -d '"')"
  elif command -v python > /dev/null 2>&1;then
    commit_date="$(_safe_download "https://api.github.com/repos/netdata/netdata/commits?path=packaging%2Finstaller%2Fnetdata-updater.sh&page=1&per_page=1" /dev/stdout | python -c 'from __future__ import print_function;import sys,json;print(json.load(sys.stdin)[0]["commit"]["committer"]["date"])')"
  fi

```

I have neither `jq` nor `python` so it fails.
With `python3` it's OK.

```
ln -s /usr/bin/python3 /usr/bin/python
```

**Comment by kaplandani** [comment]
I'm on 26 version, and attempt to update netdata results in something like this (this is ps -ef 
 | grep netdata) 


root     72704 72701  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72708 72704  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72711 72708  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72714 72711  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72721 72714  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72729 72721  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72733 72729  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72738 72733  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72742 72738  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72746 72742  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72749 72746  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72753 72749  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72756 72753  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72759 72756  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72762 72759  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72766 72762  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72769 72766  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72772 72769  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72776 72772  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72779 72776  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72782 72779  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72785 72782  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72788 72785  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72791 72788  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72795 72791  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72798 72795  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72801 72798  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72806 72801  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72811 72806  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72815 72811  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72819 72815  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72822 72819  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72825 72822  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72828 72825  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72832 72828  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72835 72832  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72838 72835  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72842 72838  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72847 72842  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72852 72847  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72856 72852  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72860 72856  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72863 72860  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72866 72863  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72870 72866  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72874 72870  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72878 72874  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72883 72878  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72886 72883  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh
root     72889 72886  0 10:58 pts/13   00:00:00 bash //usr/libexec/netdata/netdata-updater.sh

and there are plenty more....

**Comment by underhood** [comment]
There has been a fixed bug in `netdata-updater.sh` unfortunately to update it (the update script) you have to reinstall. Quoting @Ferroin:
>As of 2020-12-09, this is fixed in the nightlies.

>Affected users will need to manually update the system using your original install method instead of the updater (make sure to add --reinstall and the same options you installed with originally if using the kickstart.sh or kickstart-static64.sh scripts, otherwise it will try to run the updater and run into a different issue caused by the same bug). 

Additional info:
- #10366 
- https://community.netdata.cloud/t/periodically-anacron-job-cron-daily-on-localhost-reports-a-problem-with-netdata-updater-sh/612
