### ISSUE TITLE
Big sur MAC os 11.1,  agent is working but no web view

### ISSUE THREAD

**Issue by fate8383** [netdata/netdata#10410]
Big sur MAC os 11.1

I cannot get to the web view, localhost:19999 or any other local IP i bind it to. I cannot get to see the web view. Installed via home-brew, also tried from source. Reinstalled, removed many times both homebrew and netdata itself still not able to. I can see in the net stat port and IP are listening, Curl returns HTTP ok but no content. Webview is just hanging to load but nothing. Is this a Big Sur issue? or it is me issue?

**Comment by krital** [comment]
Is this on Intel or M1 hardware? I have no issues on Intel but we don't have M1 hardware to try yet.

**Comment by fate8383** [comment]
Intel, I had no problem either on Catalina. Upgraded to Big Sur and it was again ok on v1.26 then netdata update happened to v1.27, it stopped working. Also updated to v1.28 still not working. Uninstalled reinstalled all dependencies and netdata itself, still no luck

**Comment by krital** [comment]
Could please ensure you have followed the instructions here for installing from source? https://github.com/netdata/netdata/blob/master/packaging/installer/methods/macos.md

Specifically:
`
1. xcode-select --install
2. brew install ossp-uuid autoconf automake pkg-config libuv lz4 json-c openssl@1.1 libtool cmake
3. git clone https://github.com/netdata/netdata.git
4. cd netdata/
5. sudo ./netdata-installer.sh --install /usr/local
`

The only error you should get is eBPF which is currently only supported on Linux.

**Comment by fate8383** [comment]
yes, i might have done something wrong, multiple times. I will look into that...it woks now. thanks!
is access list (allow connections from) working on this install? I tried to access after changing the netdata conf file for "bind to" and "allow connections from", but i cannot access from another device in the network. I have another netdata setup on another device i followed the same way and it is working for the other device. For this mac one I cannot get it work. I can see it is listening on correct IP and port as I bind it to but allow connections list seems to be not allowed. I don't see anything in the access.log

**Comment by krital** [comment]
I am glad this worked for you. Could I please ask you to open a new issue for this to keep them separate?
