### ISSUE TITLE
MySQL replication alert broken due to difference in behaviour between Python and Go implementations

### ISSUE THREAD

**Issue by Daniel15** [netdata/netdata#10427]
##### Bug report summary
`mysql_local.slave_thread_running` should fire if MySQL replication has stopped. One of my replicas stopped working recently:
```
             Slave_IO_Running: Yes
            Slave_SQL_Running: No
```

However, Netdata did not fire an alert.

The alert calculation is defined as the following:
```
($sql_running == -1 OR $io_running == -1)?0:1
```

The breakage appears to be due to a difference between the Python and the Go implementations. The Python one returns `1` for running and `-1` for stopped:

https://github.com/netdata/netdata/blob/3aa4556baf8937088f2d236a8cd79cdd6512aaa4/collectors/python.d.plugin/mysql/mysql.chart.py#L154-L162

On the other hand, the Go version returns `0` (not `-1`) for stopped:

https://github.com/netdata/go.d.plugin/blob/master/modules/mysql/collect_slave_status.go#L81-L96

In addition to breaking the alert, this also causes some odd behaviour with the chart. Netdata charts appear to strip out series where all values are 0, so if the slave SQL is not running (`Slave_SQL_Running: No`), there'll be no `sql_running` series at all:

![](https://d.sb/2020/12/firefox_26-22.11.00.png)

cc @ilyam8 (https://github.com/netdata/go.d.plugin/pull/404)

##### OS / Environment
```
Linux ny02 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux bullseye/sid"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version
netdata v1.28.0-31-nightly
 

##### Component Name
go.d

**Comment by ilyam8** [comment]
Hi @Daniel15, thx for reporting the issue!

TO be honest i dont like having `-1` for `No` (or no value, anything except `Yes`), i dont remember why we did it like that 🤔 

Probably because of 

> Netdata charts appear to strip out series where all values are 0

(which i dont really like too as default).

**Comment by Daniel15** [comment]
Sure, it may make sense to change the value that's logged, however the alerts need to be updated too :) Currently I'm not aware when replication breaks since the alert is broken.

**Comment by OdysLam** [comment]
Thanks @Daniel15 for reporting this. We just returned from vacations, so @ilyam8 should be able to get back to you on this pretty quick.

In case you are interested, you could PR a fix for this, but from the comments made by @ilyam8, I am not sure if he prefers to revert or find a better solution.

In any case, if you have any further ideas, please do share. Cheers (and a happy new year :) )
