### ISSUE TITLE
Try

### ISSUE THREAD

**Issue by stevenans9859** [netdata/netdata#10436]
Try

_Originally posted by @stevenans9859 in https://github.com/netdata/netdata-cloud/issues/33#issuecomment-751659131_

**Comment by zootedz** [comment]
> Try
> 
> _Originally posted by @stevenans9859 in https://github.com/netdata/netdata-cloud/issues/33#issuecomment-751659131_

**Comment by ilyam8** [comment]
@stevenans9859 hi, you seem forget to add the issue description, probably opened it by mistake. Closing it.
