### ISSUE TITLE
Updater deadlocks

### ISSUE THREAD

**Issue by Pingger** [netdata/netdata#10439]
##### Bug report summary

Since a few weeks the update script no longer works. IT spawns >5000 Copies of itsself until aborted (with SIGINT).

##### OS / Environment

```
Linux v2202009116398126984 5.8.0-1-amd64 #1 SMP Debian 5.8.7-1 (2020-09-05) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux bullseye/sid"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

 
```netdata v1.26.0-333-nightly```

##### Component Name

packaging? (Updater)

##### Steps To Reproduce

```# bash <(curl -Ss https://my-netdata.io/kickstart.sh) --auto-update
 --- Found existing install of Netdata under: / ---
 --- Attempting to update existing install instead of creating a new one ---
[/etc/netdata]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron 
```
stuck here with around 5000-7000 processes (continueally increasing)
![image](https://user-images.githubusercontent.com/4761298/103482614-17ab9300-4de2-11eb-977d-c86356735175.png)
![image](https://user-images.githubusercontent.com/4761298/103482624-23975500-4de2-11eb-9fed-cbd9233f468e.png)
(Normal)
![image](https://user-images.githubusercontent.com/4761298/103482654-52153000-4de2-11eb-87f8-2ba0136d1395.png)

##### Expected behavior

Update to be performed and not several thousand processes to be spawned

##### Additional context
`/usr/libexec/netdata/netdata-updater.sh` yields the same result, but without output.
![image](https://user-images.githubusercontent.com/4761298/103482722-bf28c580-4de2-11eb-8010-9109cb5d7b58.png)

**Comment by underhood** [comment]
There has been a bug in the updater recently that has been fixed. Take a look:
- https://github.com/netdata/netdata/issues/10366
- https://community.netdata.cloud/t/periodically-anacron-job-cron-daily-on-localhost-reports-a-problem-with-netdata-updater-sh/612

Quoting @Ferroin:
> As of 2020-12-09, this is fixed in the nightlies.

> Affected users will need to manually update the system using your original install method instead of the updater (make sure to add --reinstall and the same options you installed with originally if using the kickstart.sh or kickstart-static64.sh scripts, otherwise it will try to run the updater and run into a different issue caused by the same bug).
