### ISSUE TITLE
Incorrect disk space reported.

### ISSUE THREAD

**Issue by snorkrat** [netdata/netdata#10438]
##### Bug report summary

Netdata reports incorrect disk usage for multiple disks.

##### OS / Environment

```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
```

##### Netdata version

 v1.28.0

installed via homebrew

##### Steps To Reproduce

1. View reported disk usage on netdata
2. View reported disk usage on macOS
3. See that they are different

##### Expected behavior

Disk usage on Netdata should match that reported by macOS

I'm going to focus on one disk.  I have an 8TB External drive. if i cmd+i (get info) on the drive it reports

Capacity: 8TB
Available: 482.2 GB (401 KB purgeable)
Used: 7,518,428,332,032 bytes (7.52 TB on disk)

Disk utility also shows: 
<img width="525" alt="Screenshot 2021-01-02 at 14 08 41" src="https://user-images.githubusercontent.com/29180003/103459028-0ee48f80-4d04-11eb-9a12-4385da09469f.png">

However Netdata shows: 
<img width="1039" alt="Screenshot 2021-01-02 at 14 09 34" src="https://user-images.githubusercontent.com/29180003/103459040-2ae83100-4d04-11eb-8583-23a0c801743a.png">

That's almost 700GB difference in the "used" alone.  There are also discrepancies with my other disks, but I'm assuming that the same issue/reporting will affect them all?

**Comment by vlvkobal** [comment]
Disk Utility shows the size in TB, Netdata in TiB. You can run `df -hg` in Terminal and check the size in GiB - just multiply it by 1024 to get TiB.

You can read about the difference between these units at https://en.wikipedia.org/wiki/Megabyte.

**Comment by stelfrag** [comment]
I am closing this, for further questions (on this and other topics) , I recommend using the [community forum](https://community.netdata.cloud/) !!
