### ISSUE TITLE
Big sur MAC os 11.1 “allow connection from” is not working

### ISSUE THREAD

**Issue by fate8383** [netdata/netdata#10431]
I have realized that "allow connection from" is not doing anything. This was working on v1.26 but now I am on latest version (nightly). Not sure where it stopped working but I cannot access from another network device to netdata agent web. I used "bind to" to the device IP, which is working I can see on listening IP and the port but not accessible by another device in the network. Access logs shows no attempts from another device in the network. I have another netdata instance on another device and that one is accessible by different network devices. So I don't think this is some restriction on my network setup. I even tried tuning off Mac firewall, no success. Installed netdata from source.

**Comment by ilyam8** [comment]
Cleaning up issues.

@fate8383 if you still experience this issue consider using our [Discord channel](https://discord.gg/mPZ6WZKKG2). There are people who can answer/help you.
