### ISSUE TITLE
Notifications still active even when set to silent

### ISSUE THREAD

**Issue by stemy2** [netdata/netdata#10437]
##### Bug report summary
I wanted to silence some alarm, so i modified their config file to set their "to:" to "silent". I even restarted the netdata service, but i still receive the notifications.

##### OS / Environment

```
4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
Yunohost (based on debian 10.6)
```

##### Netdata version

 
Don't know, the commands return me "command not found" and "syntax error".
##### Component Name

Alarms
##### Steps To Reproduce

1. Set all alarms to silent
2. Restart netdata service

##### Expected behavior

No more notifications.

**Comment by ilyam8** [comment]
Hi @stemy2

> Don't know, the commands return me "command not found" and "syntax error".

This is not expected, knowing netdata version is important, so lets try to fix the problem. 

- `netdata -V`

Doesn't work if `netdata` is not in `PATH`, it is expected.

- `$(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V`

Should work if `netdata` process is up and running.

```cmd
[ilyam@pc netdata]$ $(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V
netdata v1.28.0-106-g26cb82a3
```

^^ Do you get _syntax error_ executing that command? Could you copy paste your cmd with the error like i did?

---

> Set all alarms to silent

Do you want to disable [health monitoring](https://learn.netdata.cloud/docs/agent/health) completely?

**Comment by stemy2** [comment]
I forgot the $
`netdata v1.28.0`

**Comment by ilyam8** [comment]
Do you want to disable [health monitoring](https://learn.netdata.cloud/docs/agent/health) completely?

Or some specific alarms?

**Comment by stemy2** [comment]
> Do you want to disable [health monitoring](https://learn.netdata.cloud/docs/agent/health) completely?

This.

**Comment by stemy2** [comment]
Only silence mail notifications.

**Comment by ilyam8** [comment]
Then i suggest to change `SEND_EMAIL="YES"` to `SEND_EMAIL="NO"` in the `health_alarm_notify.conf`

**Comment by ilyam8** [comment]
See [notifications docs](https://learn.netdata.cloud/docs/agent/health/notifications#configuration)

**Comment by anctr** [comment]
**Silent doesn't work all the time.**

Here is a case where it doesn't work. It has worked in other configs

netdata -v
netdata v1.28.0-131-nightly
-------------------------------------------------------------

On the dashboard
1min_netdev_budget_ran_outs
WARNING
average number of times, during the last 1min, ksoftirq ran out of sysctl net.core.netdev_budget or net.core.netdev_budget_usecs, with work remaining (this can be a cause for dropped packets)
Alarm value  
8.7811061
Alarm configuration
Warning when
$this > (($status >= $WARNING) ? (0) : (10))
Critical when
Check every
10 seconds
Calculation
Execute
/usr/libexec/netdata/plugins.d/alarm-notify.sh
Source
18@/etc/netdata/health.d/softnet.conf
Role
silent
---------------------------------------------------------
**in the email message**


Alarm information:    1min_netdev_budget_ran_outs    average number of times, during the last 1min, ksoftirq ran out of sysctl   net.core.netdev_budget or net.core.netdev_budget_usecs, with work remaining   (this can be a cause for dropped packets)
--
Alarm value:    11.2714908 events

-----
**/etc/netdata/health.d/softnet.conf**

   alarm: 1min_netdev_budget_ran_outs
      on: system.softnet_stat
      os: linux
   hosts: *
  lookup: average -1m unaligned absolute of squeezed
   units: events
   every: 10s
    warn: $this > (($status >= $WARNING) ? (0) : (10))
   delay: down 1h multiplier 1.5 max 2h
    info: average number of times, during the last 1min, ksoftirq ran out of sysctl net.core.netdev_budget or net.core.netdev_budget_usecs, with work remaining (this can be a cause for dropped packets)
      to: silent

**Comment by stemy2** [comment]
I had to restart my server for some reason, and since then, i didn't have any more notifications.

**Comment by anctr** [comment]
I restarted the service many times and it still sends emails after that.

**Comment by isakrubin** [comment]
Same issue, multiple checks set to silent on multiple machines, services restarted multiple times, still getting emails, very frustrating

example..

root@xxx:/etc/netdata# netdata -V
netdata v1.29.0-27-nightly
root@xxx:/etc/netdata# pwd
/etc/netdata
root@xxx:/etc/netdata# EDITOR=vim ./edit-config health.d/disks.conf
Editing '/etc/netdata/health.d/disks.conf' ...

template: out_of_disk_space_time
      on: disk.space
      os: linux freebsd
xxxxx
      to: silent

netdatacli reload-health
systemctl restart netdata

**Comment by anctr** [comment]
In my case, I am not using multihost and still seeing the problem.

**Comment by ilyam8** [comment]
@anctr hi, how did you install netdata?

**Comment by anctr** [comment]
I believe I did this
bash <(curl -Ss https://my-netdata.io/kickstart.sh)

I did it on 2 machines which are pretty identical w.r.t. configuration. The silent works on one, but not the other.

**Comment by ilyam8** [comment]
>  if one machine with an alarm set to silent sends the data to another machine configured for multihost storage, and that machine does not have the same alarm set to silent, then it's not silenced. At the moment just a suspicion, not researched it yet.

I think you are right, [parent](https://learn.netdata.cloud/docs/agent/streaming) instance uses its own alarms.
