### ISSUE TITLE
Matrix/Rocket chat notifications are not working

### ISSUE THREAD

**Issue by skibbipl** [netdata/netdata#10432]
##### Bug report summary
I've set up matrix notifications for my own matrix server. But what I'm seeing in the logs is following:
```
2020-12-29 17:15:01: alarm-notify.sh: ERROR: failed to send Matrix notification for: server disk_backlog.dm-6.10min_disk_backlog is CLEAR to '!HvcHeOkiWKcHwDNZlk:my.server', with HTTP response status code 000.
```
But when I started debugging notifications I can see them sent to matrix and I can see them in the chat:
```
--- BEGIN curl command ---
/usr/bin/curl -X POST --data $'  {\n    "msgtype": "m.notice",\n    "format": "org.matrix.custom.html",\n      "formatted_body": "\342\232\240\357\270\217 server needs attention - <b>test alarm</b><br>test.chart (test.family)<br><a href=\\"https://app.netdata.cloud\\">test alarm = new value</a><br><i>this is a test alarm to verify notifications work</i>",\n      "body": "\342\232\240\357\270\217 server needs attention - test alarm test.chart (test.family) https://app.netdata.cloud test alarm = new value this is a test alarm to verify notifications work"\n  }' https://my.server/_matrix/client/r0/rooms/%21HvcHeOkiWKcHwDNZlk%3amy.server/send/m.room.message\?access_token=<cut>
--- END curl command ---
--- BEGIN received response ---
{"event_id":"$O6b9OUg5oCqI1nGytp1yD43KaZVGlNAbB_co6i7Ka_A"}
--- END received response ---
RECEIVED HTTP RESPONSE CODE: 200
2020-12-29 17:23:51: alarm-notify.sh: INFO: sent Matrix notification for: server test.chart.test_alarm is WARNING to '!HvcHeOkiWKcHwDNZlk:my.server'
```
##### OS / Environment
```
Linux server 5.9.0-5-amd64 #1 SMP Debian 5.9.15-1 (2020-12-17) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux bullseye/sid"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version
v1.28.0 installed from prebuild static 64-bit binaries.

##### Component Name
Notifications

##### Steps To Reproduce
Configure matrix notifications according to:
https://learn.netdata.cloud/docs/agent/health/notifications/matrix?q=health_alarm_notify.conf&size=n_20_n

##### Expected behavior
Notifications are sent correctly.

**Comment by skibbipl** [comment]
#10359 looks pretty similar, perhaps the root cause is the same?

**Comment by skibbipl** [comment]
Also the same issue is for Rocket chat.

**Comment by ilyam8** [comment]
@skibbipl thx for reporting it, looks like there is a problem when netdata installed from prebuild static 64-bit binaries 🤔 We will check it!

**Comment by thiagoftsm** [comment]
> @skibbipl thx for reporting it, looks like there is a problem when netdata installed from prebuild static 64-bit binaries thinking We will check it!

I agree with @ilyam8 , I tried to replicate yesterday compiling Netdata from scratch, and I did not have any problems. I will try to use the prebuild to confirm this.

**Comment by yasharne** [comment]
@ilyam8 @thiagoftsm  same problem here #10463

**Comment by thiagoftsm** [comment]
Helo @yasharne ,

> @ilyam8 @thiagoftsm same problem here #10463

Sorry for the delay, I was on vacation, I am installing Matrix/Rocket to understand the problem.

Best regards!

**Comment by ilyam8** [comment]
There is problem with static netdata, see https://github.com/netdata/netdata/issues/10359#issuecomment-758202948

**Comment by ilyam8** [comment]
The fix is merged https://github.com/netdata/netdata/pull/10491
