### ISSUE TITLE
Netdata not showing CPU usage correctly

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#10443]
##### Bug report summary

htop shows an instance is using 30 to 40 percent of CPU on average but netdata is now showing the CPU usage correctly

htop output:
![image](https://user-images.githubusercontent.com/7656049/103525759-0a031580-4e95-11eb-91b5-dd06ae5de28d.png)
netdata output:
![image](https://user-images.githubusercontent.com/7656049/103525818-1f783f80-4e95-11eb-9c3a-d6b445e41fa1.png)
refresh interval on netdata is 2 seconds

##### OS / Environment

```
Linux api-1.app.x.y.z 4.4.0-187-generic #217-Ubuntu SMP Tue Jul 21 04:18:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.6 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.6 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

 netdata v1.28.0

**Comment by yasharne** [comment]
UPDATE: restarting the netdata unit didn't fix the issue but rebooting the machine fixed the issue

**Comment by ilyam8** [comment]
@yasharne hi

> UPDATE: restarting the netdata unit didn't fix the issue but rebooting the machine fixed the issue

How it is going after the restart, no more problem?


---


> netdata v1.28.0

And old legend? Do you use `/old` endpoint?

And `systemd.cpu` chart has negative values 🤔

**Comment by stelfrag** [comment]
Hi @yasharne 

Do you observe that everything is normal after the reboot of the machine?

**Comment by yasharne** [comment]
Hi @ilyam8 No we don't use `/old`
@stelfrag Yes, everything is normal after the reboot.
