### ISSUE TITLE
Troubleshoot coverity missing defects in netdata source code

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#10449]
##### Bug report summary

Coverity missed the flaw [here](https://github.com/netdata/netdata/pull/10391). We need to understand how to tune coverity to cover more code.

**Comment by mfundul** [comment]
After studying coverity user models I have concluded they can't help with what we want. User models cannot force coverity to cover code that hasn't been covered, or to interpret self-contained code differently. Their primary purpose is to define external dependency behaviour and the primary benefit is reducing false positives. Catching more bugs than before is only possible when external code has unknown behaviour and the user model helps define it.

There is Coverity Support for AUTOSAR Coding Standards by Synopsys:
https://www.synopsys.com/content/dam/synopsys/sig-assets/datasheets/ds-coverity-autosar-standards.pdf
In rule M5-0-15 in page 13 we can see that coverity supports "Array indexing shall be the only form of pointer arithmetic."
Since our bug is indeed valid pointer arithmetic, it leads me to believe that coverity simply cannot detect this kind of error in its current implementation.

My final experiment was to check that the buggy code is indeed covered by injecting an obvious bug right before the flawed code. Coverity successfully discovered the injected bug, whose scope closed right after the missed flaw. It is clear that coverity analyzed the whole code block and was unable to detect the missed flaw yet again.

**Comment by krital** [comment]
Thanks @mfundul great progress. So it looks like we can not depend much on Coverity scans for detecting security problems. Do you agree that we can increase coverage though by getting to scan more of our code by increasing what we compile in either a single or multiple scans? My idea on this was to have a mode where tests are executed, the dependencies of which cause more plugins to be compiled and therefore scanned. We can achieve the same probably by just enabling everything and if that is not possible we can do multiple scans (e.g. multiple types of dbEngine)?

**Comment by mfundul** [comment]
I agree that attempting to enable everything sounds like a good idea. A maximal linux configuration sounds best to me. I don't know what we can do about BSD or Mac OS.

**Comment by krital** [comment]
Well that would be huge improvement compared to now. We could then look at VMs to performa additional scans (e.g. OSX VMs on AWS)
