### ISSUE TITLE
A lot of "curl: (3) URL using bad/illegal format or missing URL" in logs

### ISSUE THREAD

**Issue by serge1peshcoff** [netdata/netdata#10440]
##### Bug report summary

When the app is started, I get a lot of following messages in logs:

```
2021-01-03 18:53:44: cgroup-name.sh: WARNING: cannot find the name of docker container '57b89f7c410772fdacf81ab7cad2481042f54dee5124f3ecddfaed47da0b6fcc'
2021-01-03 18:53:44: cgroup-name.sh: INFO: cgroup 'docker_57b89f7c410772fdacf81ab7cad2481042f54dee5124f3ecddfaed47da0b6fcc' is called '57b89f7c4107'
2021-01-03 18:53:45: cgroup-name.sh: INFO: Running API command: curl "/var/run/docker.sock/containers/0ee1ff28865ca6704ca357f235413102b24ec94b58c81f2ab73239d08c7a1cc1/json"
curl: (3) URL using bad/illegal format or missing URL
```

Additionally, I receive this notification (on Telegram as I have it as a alert platform), so this may be connected (the hostname matches the docker container's `hostname` output):
```
⚠️ 4e16fe809eca needs attention - 10s ipv4 tcp resets received
ipv4.tcphandshake (tcp)
10s ipv4 tcp resets received = 92 tcp resets/s
average TCP RESETS this host is receiving, over the last 10 seconds (this can be an indication that a service this host needs, has crashed; clear notification for this alarm will not be sent)
```

##### OS / Environment

```
OMV5, netdata as a Docker container

# uname -a
Linux shuttle.local 5.8.10-custom #1 SMP Sun Nov 15 00:58:27 MSK 2020 x86_64 GNU/Linux
# uname -r
5.8.10-custom
```

##### Netdata version

```
➜  ~ docker exec netdata netdata -v
netdata v1.28.0-63-gc5f3f15d
```
 

##### Steps To Reproduce

1. Restart the container

##### Expected behavior

No error logs.

**Comment by vlvkobal** [comment]
Please read about [Docker container names resolution](https://learn.netdata.cloud/docs/agent/packaging/docker#docker-container-names-resolution).

**Comment by serge1peshcoff** [comment]
@vlvkobal I have the PGID env variable set in the container though:
```
➜  ~ docker exec netdata sh -c 'echo $PGID'
994
```

can it be something else causing this?

**Comment by vlvkobal** [comment]
Have you mounted `docker.sock`? You can do something like this:
```
docker run -d --name=netdata \
  -p 19999:19999 \
  -v netdataconfig:/etc/netdata \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  --env PGID=974 \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  netdata/netdata
```
Don't forget to check `docker` group id using "grep docker /etc/group | cut -d ':' -f 3" and change `PGID` accordingly.

**Comment by ilyam8** [comment]
The issue is 

> 2021-01-03 18:53:45: cgroup-name.sh: INFO: Running API command: curl "/var/run/docker.sock/containers/0ee1ff28865ca6704ca357f235413102b24ec94b58c81f2ab73239d08c7a1cc1/json"


It is URL illegal format, indeed.

The code

https://github.com/netdata/netdata/blob/7ac626bb8148976cdaa78baae4de2c1a9a81b898/collectors/cgroups.plugin/cgroup-name.sh.in#L68-L74

`-S` is _True if FILE exists and is a socket_.


Looks like `/var/run/docker.sock` is not mounted => that check fails => we try to connect via network using unix socket path as URL.
