### ISSUE TITLE
Entropy alarms false positives?

### ISSUE THREAD

**Issue by feldsam** [netdata/netdata#10458]
##### Bug report summary
I am getting many times a day low entropy alarms, but looks like false positives.

I geting following warnings

```
Alarm information: lowest_entropy minimum entries in the random numbers pool in the last 10 minutes
--
Alarm value: 19 entries
```

but when I login to host immediatelly and run following command I get much higher value

```
# cat /proc/sys/kernel/random/entropy_avail 
3310
```

##### OS / Environment

```
Linux node1.feldcloud.net 5.4.17-2036.101.2.el7uek.x86_64 #2 SMP Wed Dec 2 17:56:16 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/oracle-release:Oracle Linux Server release 7.9
/etc/os-release:NAME="Oracle Linux Server"
/etc/os-release:VERSION="7.9"
/etc/os-release:ID="ol"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.9"
/etc/os-release:PRETTY_NAME="Oracle Linux Server 7.9"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:oracle:linux:7:9:server"
/etc/os-release:HOME_URL="https://linux.oracle.com/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.oracle.com/"
/etc/os-release:
/etc/os-release:ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
/etc/os-release:ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
/etc/os-release:ORACLE_SUPPORT_PRODUCT="Oracle Linux"
/etc/os-release:ORACLE_SUPPORT_PRODUCT_VERSION=7.9
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
/etc/system-release:Oracle Linux Server release 7.9
```

##### Netdata version
netdata v1.28.0
 

##### Component Name
system.entropy

##### Expected behavior
No false positives, or missing I something?

**Comment by ilyam8** [comment]
Hi @feldsam 

The info

> lowest_entropy minimum entries in the random numbers pool in the last 10 minutes

I see it is `in the last 10 minutes`


> cat /proc/sys/kernel/random/entropy_avail 

Returns current result.

So it seems it is not false positive, have you checked `system.entropy` chart? Does it contain `Alarm value`?

**Comment by feldsam** [comment]
Hi, I just checked graph, and with last 15minit graph I see som low peak to only 265, but on historic graphs I dont see it, because looks like it is average and not min/max numbers. So it looks like some problem with entropy for few minutes regulary. Any advice? My cpu has rdrang instruction and I also run rngd on machine. It is KVM hypervisor

**Comment by ilyam8** [comment]
> because looks like it is average and not min/max numbers.

Exactly. If time range is big you get average.


> So it looks like some problem with entropy for few minutes regulary. Any advice?

Unfortunately i cant help. Probably @Ferroin could suggest something.

**Comment by OdysLam** [comment]
Let's continue the discussion on the community forum. @feldsam we are trying to migrate discussions and support related questions on our forums, which is a better platform for it.

@ilyam8 thanks for engaging ✌️

Community forum topic: https://community.netdata.cloud/t/entropy-alarms-false-positives/742
