### ISSUE TITLE
Incomplete package from PackageCloud

### ISSUE THREAD

**Issue by CberYellowstone** [netdata/netdata#10457]
When I install netdata `v1.28.0` from the `packagecloud`,  Web UI send a massage like this
>The installer could not prepare the required dependencies to enable Netdata Cloud functionality
![image](https://user-images.githubusercontent.com/37031767/103771607-fefde000-5062-11eb-81e7-d9dc4de1e41b.png)

Both `.rpm` or `.deb` have this problem, And there is also a message from `netdata-claim.sh`:

>This agent was built without the dependencies for Cloud and cannot be claimed

I'm not the only one with this problem, @Habetdin has this problem, too

the system I use is `centos 7.9` , and  @Habetdin 's is `Ubuntu 18.04`

looking for a reply @prologic @underhood

**Comment by underhood** [comment]
@CberYellowstone @Habetdin thanks for reporting the issue. There is a PR that should fix this already. Apologize for the delayed answer during the Christmas holidays.

**Comment by x86txt** [comment]
Hi, this issue is affecting your .deb package too. I just installed it today and am seeing the same error in the GUI and when manually running netdata-claim.sh, I receive: 

    This agent was built without the dependencies for Cloud and cannot be claimed

This is on Debian Buster.
