### ISSUE TITLE
Prometheus Remote Write support isn't compiled

### ISSUE THREAD

**Issue by dgsus** [netdata/netdata#10454]
Hi,

i cant seem to enable remote write on the latest stable version 1.28

after a fresh install (bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-cloud --disable-telemetry --stable-channel - and no errors during install/compile apart from ebpf) im getting:

2021-01-05 21:35:26: netdata INFO  : EXPORTING : thread created with task id 108018
2021-01-05 21:35:26: netdata INFO  : EXPORTING : set name of thread 108018 to EXPORTING
2021-01-05 21:35:26: netdata INFO  : EXPORTING : Processing connector instance (my_victoriadb)
2021-01-05 21:35:26: netdata INFO  : EXPORTING : Instance (my_victoriadb) on connector (prometheus_remote_write) is enabled and scheduled for activation
2021-01-05 21:35:26: netdata INFO  : EXPORTING : Instance my_victoriadb on prometheus_remote_write
2021-01-05 21:35:26: netdata ERROR : EXPORTING : Prometheus Remote Write support isn't compiled

[root@xxxx-xxxx~]# netdata -version
netdata v1.28.0

[root@xxxx-xxxx~]# uname -a; grep -Hv "^#" /etc/*release
Linux 0521988-xxxx.xxxx-xxx.xx3.10.0-1160.6.1.el7.x86_64 #1 SMP Wed Oct 21 13:44:38 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.9 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.9"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
/etc/os-release:HOME_URL="https://www.redhat.com/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
/etc/system-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)

my exporting.conf

[exporting:global]
    enabled = yes
     send configured labels = yes
     send automatic labels = no
     update every = 2

[prometheus:exporter]
    # send names instead of ids = yes
    # send configured labels = yes
    # send automatic labels = no
    # send charts matching = *
    # send hosts matching = localhost *
    # prefix = netdata

 [prometheus_remote_write:my_victoriadb]
     enabled = yes
     destination = xxxx:8428
     remote write URL path = /api/v1/write
     data source = average
     prefix = netd
     hostname = xxxx-xxxx
     update every = 10
     buffer on failures = 10
     timeout ms = 20000
     send names instead of ids = yes
     send charts matching = *
     send hosts matching = localhost *

thanks in advance for any help!

**Comment by vlvkobal** [comment]
Have you installed the `protobuf` and `snappy` libraries?
Check the `configure` script output:
```
checking for PROTOBUF... yes
checking for snappy::RawCompress in -lsnappy... yes
checking for protoc... /usr/bin/protoc
checking for g++... (cached) /usr/bin/g++
checking if prometheus remote write backend should be enabled... yes
```

**Comment by dgsus** [comment]
Hi @vlvkobal ,

indeed, "computer says no"

checking for PROTOBUF... no
checking for snappy::RawCompress in -lsnappy... no
checking for protoc... no
checking for g++... (cached) no
checking if prometheus remote write backend should be enabled... no

however i have the python and el7 packages:

[root@xxxxxconf]# pip show protobuf
Name: protobuf
Version: 3.14.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages
Requires: six
Required-by:


[root@xxxxx conf]# pip show snappy
Name: snappy
Version: 2.8
Summary: Studying the topology and geometry of 3-manifolds, with a focus on hyperbolic structures.
Home-page: http://snappy.computop.org
Author: Marc Culler and Nathan M. Dunfield
Author-email: culler@uic.edu, nathan@dunfield.info
License: GPLv2+
Location: /opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages
Requires: decorator, future, ipython, pypng, spherogram, plink, snappy-manifolds, FXrays, cypari
Required-by:

yum
Package protobuf-2.5.0-8.el7.x86_64 already installed and latest version
Package snappy-1.1.0-3.el7.x86_64 already installed and latest version

do i have the right yum/python packages?

thank you!

**Comment by dgsus** [comment]
i just installed snappy devel package and now i see snappy ok but still no protobuf... i also tried installing the devel package but no luck.



checking for PROTOBUF... no
checking for snappy::RawCompress in -lsnappy... yes
checking for protoc... /bin/protoc
checking for g++... (cached) /bin/g++
checking if prometheus remote write backend should be enabled... no

**Comment by vlvkobal** [comment]
It looks like you don't have the protobuf C++ library installed. Python package won't help here. I've compiled Netdata on Fedora 32
```
sudo yum install protobuf-devel
sudo yum install snappy-devel
sudo yum install gcc-c++
sudo ./netdata-installer.sh
```
```
checking for PROTOBUF... yes
checking for snappy::RawCompress in -lsnappy... yes
checking for protoc... /usr/bin/protoc
checking for g++... (cached) /usr/bin/g++
checking if prometheus remote write backend should be enabled... yes
```

**Comment by dgsus** [comment]
i have all of those and it still fails... i also tried removing the packages and installing them again, no joy.

[root@xxxxx# yum install protobuf-devel snappy-devel gcc-c++
Package protobuf-devel-2.5.0-8.el7.x86_64 already installed and latest version
Package snappy-devel-1.1.0-3.el7.x86_64 already installed and latest version
Package gcc-c++-4.8.5-44.el7.x86_64 already installed and latest version

what else could i check?

checking for PROTOBUF... no
checking for snappy::RawCompress in -lsnappy... yes
checking for protoc... /bin/protoc
checking for g++... (cached) /bin/g++
checking if prometheus remote write backend should be enabled... no

**Comment by vlvkobal** [comment]
Well, you have old versions installed
```
[vlad@fedora-32 ~]$ sudo yum install protobuf-devel snappy-devel gcc-c++
Package protobuf-devel-3.11.2-2.fc32.x86_64 is already installed.
Package snappy-devel-1.1.8-2.fc32.x86_64 is already installed.
Package gcc-c++-10.2.1-9.fc32.x86_64 is already installed.
```

Look at `config.log`. You should find there something like this
```
configure:11555: checking for PROTOBUF
configure:11562: $PKG_CONFIG --exists --print-errors "protobuf >= 3"
configure:11565: $? = 0
configure:11579: $PKG_CONFIG --exists --print-errors "protobuf >= 3"
configure:11582: $? = 0
configure:11622: result: yes
configure:11627: checking for snappy::RawCompress in -lsnappy
configure:11663: g++ -o conftest -g -O2 -std=c++11   conftest.cpp -lsnappy >&5
configure:11663: $? = 0
configure:11685: result: yes
configure:11690: checking for protoc
configure:11708: found /usr/bin/protoc
configure:11721: result: /usr/bin/protoc
configure:11738: checking for g++
configure:11769: result: /usr/bin/g++
configure:11796: checking if prometheus remote write backend should be enabled
configure:11811: result: yes
```

**Comment by dgsus** [comment]
thanks for your help @vlvkobal!

i managed to get it working by removing any previous attempts of installing protobuf and just installed these 3

yum install https://cbs.centos.org/kojifiles/packages/protobuf/3.6.1/4.el7/x86_64/protobuf-3.6.1-4.el7.x86_64.rpm
yum install https://cbs.centos.org/kojifiles/packages/protobuf/3.6.1/4.el7/x86_64/protobuf-compiler-3.6.1-4.el7.x86_64.rpm
yum install https://cbs.centos.org/kojifiles/packages/protobuf/3.6.1/4.el7/x86_64/protobuf-devel-3.6.1-4.el7.x86_64.rpm
