### ISSUE TITLE
Error on install and uninstall

### ISSUE THREAD

**Issue by AshleyHunter01** [netdata/netdata#10452]
Can't install:
root@SliceSMP:~# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 --- Found existing install of Netdata under: / ---
 --- Existing install appears to be handled manually or through the system package manager. ---
 ABORTED  Existing installation detected which cannot be safely updated by this script, refusing to continue.

root@SliceSMP:~# sudo <(curl -Ss https://my-netdata.io/kickstart.sh) --allow-duplicate-install
sudo: /dev/fd/63: command not found
root@SliceSMP:~# curl: (23) Failed writing body (607 != 1369)

When trying to uninstall:
root@SliceSMP:~# ./netdata-uninstaller.sh --yes
./netdata-uninstaller.sh: line 445: /etc/netdata/.environment: No such file or directory

Something went wrong :(

**Comment by Ferroin** [comment]
Indeed, it looks like something broke your install, though I’m not sure what.

The `--allow-duplicate-install` option _should_ work, the error message there indicates some networking issue trying to actually fetch one of the files needed for the install, though I couldn’t begin to guess what might be wrong there.

**Comment by dmoneymaker** [comment]
Following

**Comment by mdhz** [comment]
@AshleyHunter01 Did you find any solution as I'm having the same problem?
Using Ubuntu 18
