### ISSUE TITLE
netdata behind nginx not working

### ISSUE THREAD

**Issue by moeinrahimi** [netdata/netdata#10469]
netdata behind nginx results to this error. it cannot load some js files. it works fine accessing directly.
I get this message in browser console and it's same across other browsers like chrome and firefox, it's same message on both http and https.
```
GET https://netdata.website.org/static/js/main.7045b854.chunk.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
```
![netdata bentoapp org_ (1)](https://user-images.githubusercontent.com/13715024/103996824-9f611b00-51af-11eb-908e-aa1f8d31f710.png)

my nginx conf
``` nginx
upstream backend {
    # the Netdata server
    server 127.0.0.1:19999;
    keepalive 64;
}

server {
    # nginx listens to this
    listen 80;

    # the virtual host name of this
    server_name netdata.website.org;

    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/netdata.website.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/netdata.website.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```
installation method: bash <(curl -Ss https://my-netdata.io/kickstart.sh)
my machine spec:
ubuntu 18.04
nginx 1.18
netdata v1.28.0-68-nightly

**Comment by thiagoftsm** [comment]
Hello @moeinrahimi ,

I tested now Netdata behind `nginx 1.12.2` and I could not recreate the problem, I ma using the following configuration with self-signed certificate:

```
    server {
        listen       8081;
        server_name  localhost;
        stub_status;

        location / {
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https; #New
            proxy_http_version 1.1;
            proxy_pass_request_headers on;
            proxy_set_header Connection "keep-alive";
            proxy_store off;
            gzip on;
            gzip_proxied any;
            gzip_types *;
            rewrite ^/netdata(/.*)$ $1 break;
            proxy_pass http://localhost:20000;
         }

         ssl on;
         ssl_certificate /etc/nginx/cert.pem;
         ssl_certificate_key /etc/nginx/key.pem;

        location = /50x.html {
            root   /var/www/html;
        }
    }
```

I think you can have two problems:

1 - Our SSL configuration is not the same, but I am not a Nginx specialist to measure the impact of this difference.
2 - What is the browser version you are using to access Netdata?

I will update my nginx to verify if I can recreate the problem running behind the latest Nginx.

Best regards!

**Comment by thiagoftsm** [comment]
I updated now for the version `1.18` and I did the following change in the previous configuration:

```
    server {
        listen       8081 ssl;
        server_name  localhost;
        stub_status;

        location / {
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https; #New
            proxy_http_version 1.1;
            proxy_pass_request_headers on;
            proxy_set_header Connection "keep-alive";
            proxy_store off;
            gzip on;
            gzip_proxied any;
            gzip_types *;
            rewrite ^/netdata(/.*)$ $1 break;
            proxy_pass http://localhost:20000;
         }

         ssl_certificate /etc/nginx/cert.pem;
         ssl_certificate_key /etc/nginx/key.pem;

        location = /50x.html {
            root   /var/www/html;
        }
    }
```

I did not have problems to access Netdata and I understood the difference between our configuration, please, take a look in the other options I am using that are not present in your configuration file.

Best regards!

**Comment by petecooper** [comment]
@moeinrahimi - try temporarily disabling your anti-virus software, does that help?

https://thisinterestsme.com/err_incomplete_chunked_encoding/

Also, try disabling "Predict network actions to improve page load performance" in Chrome if that is enabled.

**Comment by OdysLam** [comment]
Since we have migrated our Support process on our forums at https://community.netdata.cloud, I think it's best that we continue the discussion there, in the Netdata Agent Support category.

Thanks @thiagoftsm for chiming in and @petecooper for the firewall idea, it's actually the more frequent culprit!

Best,
Odysseas

**Comment by moeinrahimi** [comment]
thank you for helping to solve my issue.
I solved it by adding these two lines to my location block in nginx.
``` nginx
   proxy_buffers 8 1024k;
  proxy_buffer_size 1024k;
```
@thiagoftsm I tried your config but no luck.
