### ISSUE TITLE
last collected alert is not fixed in the dashboard and the alert is not sent to the channels

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#10463]
##### Bug report summary

In our parent/child architecture, a netdata agent on a MySQL database server is transmitting the metrics to a parent server.
Today I accidentally opened this dashboard from the parent's web UI and realized there is an alert on the dashboard:
![image](https://user-images.githubusercontent.com/7656049/103861511-c990db00-50d2-11eb-9547-d91ef4e93414.png)
Here is the state of the `mysql_local.query`:
![image](https://user-images.githubusercontent.com/7656049/103861687-0ceb4980-50d3-11eb-89f9-a4db7da272a3.png)
So obviously the last collected alert is solved but I still see the alert notification.
The other problem is we didn't get any alerts when the last collected alert was fired, I tried the test notifications and it works correctly but it's been a while since we didn't get any alerts from any of our netdata parents.
We send alerts to slack, rocket chat, and matrix but I didn't see any logs regarding successful or failed notification sending, the only log I have with the word alert is this one:
```sh
cat /opt/netdata/var/log/netdata/error.log.1 | grep alarm
2021-01-06 13:34:49: netdata INFO  : HEALTH : Postponing alarm checks for 60 seconds, because it seems that the system was just resumed from suspension.
2021-01-06 18:32:31: netdata ERROR : STREAM_RECEIVER[runner-01.tool.afra.snapp.infra,[172.16.77.120]:33434] : Failed to create an alarm for dimension sent of chart net.veth7e0c093 5 times. Skipping alarm.
```

##### OS / Environment

parent server:
```
4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

parent: 1.28.0
child: 1.23.0

##### Component Name

Health

**Comment by yasharne** [comment]
@ilyam8 I just uninstalled netdata using the `netdata-uninstaller.sh` script and reinstalled netdata `v1.26.0` (prebuilt) but the notification problem still persists, here is the alert in the dashboard which should be repeated every 2 hours but we haven't got any alert in the last week:
![image](https://user-images.githubusercontent.com/7656049/104415692-ae691400-5587-11eb-9622-95090139193c.png)
I don't even see any logs about the `alarm-notify` in the logs:
![image](https://user-images.githubusercontent.com/7656049/104415913-191a4f80-5588-11eb-87a1-5526c33f6329.png)
Test alerts are working as expected

**Comment by ilyam8** [comment]
Hi @yasharne 

Likely https://github.com/netdata/netdata/issues/10359#issuecomment-758202948

Bundled cURL hardcoded CAFile points to non-existent ca bundle.

If you create a symlink `ca-certificates.crt -> ca-bundle.crt` it should fix the issue.

Test script uses system cURL, that is why they work.

> and reinstalled netdata v1.26.0 (prebuilt)

1.25 - 1.28 version affected.

https://github.com/netdata/netdata/pull/10491 is the fix.

**Comment by yasharne** [comment]
Thanks @ilyam8 
Do  I have to restart the netdata on the parent node?

**Comment by ilyam8** [comment]
@yasharne i think not

**Comment by yasharne** [comment]
@ilyam8 This either requires netdata restart or creating a symlink between `ca-certificates.crt -> ca-bundle.crt` is not the solution because we still are not getting alerts

**Comment by ilyam8** [comment]
@yasharne did i understand you correct?

you did:
 - creating a symlink between ca-certificates.crt -> ca-bundle.crt
 - netdata restart

And it didn't fixed the issue?

**Comment by yasharne** [comment]
@ilyam8 No I didn't restart the parents 
and yes I have created the symlink:
```sh
ls -s /opt/netdata/share/ssl/certs/ca-certificates.crt /opt/netdata/share/ssl/certs/ca-bundle.crt
```

**Comment by ilyam8** [comment]
Ok, lets `grep alarm error.log` one more time

**Comment by yasharne** [comment]
@ilyam8 Here is the output on the machine which should have at least  7 `last collected` errors for `web_log` charts and many more ram usage alerts:
![image](https://user-images.githubusercontent.com/7656049/104922878-824afa00-59b0-11eb-978c-390fd5ca836c.png)

**Comment by ilyam8** [comment]
Interesting, i expect it matches some alarm-notify script logs

```cmd
[ilyam@pc netdata]$ grep alarm error.log | grep alarm-notify.sh: | head -3
2021-01-18 11:24:34: alarm-notify.sh: ERROR: failed to send Matrix notification for: pc net_drops.wlp5s0.inbound_packets_dropped is WARNING to '!ROOMID:SERVERNAME', with HTTP response status code 000.
2021-01-18 11:26:26: alarm-notify.sh: INFO: not sending notification for CLEAR of 'pc.system.cpu.10min_cpu_usage' (last status was UNINITIALIZED)
2021-01-18 11:34:24: alarm-notify.sh: ERROR: failed to send Matrix notification for: pc net_packets.wlp5s0.inbound_packets_dropped_ratio is WARNING to '!ROOMID:SERVERNAME', with HTTP response status code 000.
```

Are there any active alarms at the moment? Do you see them on the dashboard? (or `/api/v1/alarms?active`)

**Comment by yasharne** [comment]
@ilyam8 Yes, one of the children has two active alarm:
![image](https://user-images.githubusercontent.com/7656049/104923625-8deaf080-59b1-11eb-823f-d3e248ddc0aa.png)
For the first one, the alert triggered about 3 hours ago:
![image](https://user-images.githubusercontent.com/7656049/104923771-c4287000-59b1-11eb-986b-257a2c36c701.png)
And now the local time is 17:22 and ram usage is back to normal:
![image](https://user-images.githubusercontent.com/7656049/104923826-db675d80-59b1-11eb-8df9-00ce64210beb.png)
But as you can see on the first screen shot, it is still an active alert in the dashboard

**Comment by yasharne** [comment]
@ilyam8 Here is the output for `/api/v1/alarms?active`:
```
{
	"hostname": "netdata-c5-01.x.y.z",
	"latest_alarm_log_unique_id": 1604750261,
	"status": true,
	"now": 1610995877,
	"alarms": {
		"disk_space._.disk_space_usage": {
			"id": 1604749788,
			"name": "disk_space_usage",
			"chart": "disk_space._",
			"family": "/",
			"active": true,
			"disabled": false,
			"silenced": false,
			"exec": "/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh",
			"recipient": "sysadmin",
			"source": "12@/opt/netdata/etc/netdata/health.d/disks.conf",
			"units": "%",
			"info": "current disk space usage",
			"status": "CRITICAL",
			"last_status_change": 1610855475,
			"last_updated": 1610995848,
			"next_update": 1610995908,
			"update_every": 60,
			"delay_up_duration": 60,
			"delay_down_duration": 900,
			"delay_max_duration": 3600,
			"delay_multiplier": 1.500000,
			"delay": 90,
			"delay_up_to_timestamp": 1610855565,
			"warn_repeat_every": "0",
			"crit_repeat_every": "7200",
			"value_string": "90.5%",
			"last_repeat": "1610992469",
			"calc":"$used * 100 &#x2F; ($avail + $used)",
			"calc_parsed":"((${used} * 100) &#x2F; (${avail} + ${used}))",
			"crit":"$this &gt; 90",
			"crit_parsed":"(${this} &gt; 90)",
			"green":null,
			"red":null,
			"value":90.4784698
		}
	}
}
```

**Comment by yasharne** [comment]
@ilyam8  updating to `1.29.1` fixed the issue, thanks for your efforts
