### ISSUE TITLE
High RAM usage by netdata-master

### ISSUE THREAD

**Issue by Ziars** [netdata/netdata#10471]
##### Bug report summary

I have Netdata master on the host system and ~50-60 Netdata slaves in LXD containers. Every second one slave collects ~1000-1200 metrics. Your [calculator](https://learn.netdata.cloud/docs/store/change-metrics-storage#calculate-the-system-resources-ram-disk-space-needed-to-store-metrics) tells that Netdata must use ~1100-1300MB of RAM. But in our case netdata-master consumes ~6GB of memory and keeps growing (7 days uptime).

##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.6 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.6 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```
##### Netdata version

``` shell
~# netdata -V
netdata v1.28.0
```

netdata.conf params:

``` conf
[global]
        run as user = root
        web files owner = root
        web files group = netdata
        hostname = myhost
        access log = none
        history = 1800
        memory mode = dbengine
        page cache size = 16
        dbengine multihost disk space = 20105
[health]
        enabled = no
[statsd]
        enabled = no
```

##### Steps To Reproduce

Connect more than 50 slaves to one master with 1000-1200 metrics per each slave, set `dbengine multihost disk space` to `20105` Then wait 5-7 days.

##### Expected behavior

Lower RAM usage. If I set `dbengine multihost disk space` to lower value, memory consumption lowers too. For example, with `dbengine multihost disk space` set to `1536`, netdata-master was using ~1.3GB RAM. Basing on these observations I can make an assumption that netdata-master RAM usage is directly related to the `dbengine multihost disk space` value. Is this behavior expected or is it a bug?

**Comment by mfundul** [comment]
The calculator doesn't compute the netdata agent's total memory usage, but only what `memory mode = dbengine` demands. Granted, this should be the majority of the memory usage in your scenario.

If I use the calculator I get something around 5.5GiB:
![image](https://user-images.githubusercontent.com/44345837/104039752-6e004380-51df-11eb-9a2c-af720fc9a65d.png)

Moreover, memory usage [scaling](https://learn.netdata.cloud/docs/agent/database/engine#memory-requirements) is to be expected at the moment.

**Comment by maciejasembler** [comment]
I am experiencing the same, reported here:

https://github.com/netdata/netdata/issues/10423

I would expect the ram usage to stabilize after time defined in "history" setting. Is that not honoured with dbengine anymore ?

**Comment by mfundul** [comment]
> 
> 
> I am experiencing the same, reported here:
> 
> #10423
> 
> I would expect the ram usage to stabilize after time defined in "history" setting. Is that not honoured with dbengine anymore ?

As described in the [docs](https://learn.netdata.cloud/docs/agent/database/engine#configuration) `history` is indeed not honoured: "The Agent ignores the history setting when using the database engine.".

The memory leak though could be something else, so I will take a look at the original issue.

**Comment by maciejasembler** [comment]
This might be an effect of me misunderstanding how DBEngine works.

I will revisit it with changing "dbengine multihost disk space" and update the original issue.

Thank you for linking this.

**Comment by underhood** [comment]
@kaskavel similar to what we have been talking on friday :)

**Comment by maciejasembler** [comment]
@Ziars you might want to take a look at this ticket later and check your dbengine stats:

https://github.com/netdata/netdata/issues/10423

**Comment by haydenseitz** [comment]
I am seeing a behavior of the netdata agent taking ~1.7Gb memory on start. The community link above has full details. 
It does not seem like a memory leak, because a restart of the agent service brings memory usage immediately up to the 1.7Gb mark.

**Comment by maciejasembler** [comment]
@haydenseitz Hi there!

I was chasing this myself - running netdata in parent-children setup in a small EKS cluster.

You can find my findings here, I suggest disabling proc and cgroups plugin and play around with whitelisting their components (which for sure can be done for proc, not sure about cgroups):
https://github.com/netdata/netdata/issues/10423

**Comment by ilyam8** [comment]
> I suggest disabling proc
> whitelisting their components

@maciejasembler as you did in https://github.com/netdata/netdata/issues/10423#issuecomment-808945886

`/proc/net/dev` `disable by default interfaces matching` option needs to be adjusted to filter out virtual net interfaces (veth* or cali* or whatever interfaces depends on the network plugin).

Having other proc modules enabled shoudln't be a problem, the data they collect is not dynamic.

**Comment by haydenseitz** [comment]
@maciejasembler I'm not sure the issue I'm seeing is a memory leak, because as soon as the agent is started, memory usage immediately jumps to over 1Gb. I've switched all my agent installations to use the stable release channel, and they are not having the issue. It may come back when they upgrade to the next release, we will see...

**Comment by webotop** [comment]
Hi guys,

It was ok for a while but since a few days Netdata raises my ram up to 95% .... I get back my ram under 30% when I stop Netdata Agent service.

**Comment by OdysLam** [comment]
@webotop can you please verify that you are running the latest version of the Netdata agent? (run `netdata -v`)

**Comment by webotop** [comment]
I am running netdata v1.31.0-76-nightly

**Comment by ilyam8** [comment]
@webotop what's your setup? Parent/child? How many children instances?

**Comment by cakrit** [comment]
@webotop the calculator [here](https://learn.netdata.cloud/docs/store/change-metrics-storage) is fairly accurate regarding memory and disk space usage. The questions @ilyam8 asks are inputs to that calculator, which you can use yourself to tweak how much memory will be used (linked to retention). 

P.S. We are working hard to drastically reduce these requirements.

**Comment by webotop** [comment]
Hi,

I am afraid the issue is not about my setup or the calculator, it is all about that Netdata is taking up to 95% of my real memory while it goes down to 30% without it running ...

**Comment by ilyam8** [comment]
@webotop it would be very helpful if you describe your case using [the bug template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md)

- `##### Bug report summary`
- `##### OS / Environment`
- `##### Netdata version`
- `##### Installation method`
- `##### Steps To Reproduce`
- `##### Expected behavior`

We can discuss your case in this issue.

>  it is all about that Netdata is taking up to 95% of my real memory while it goes down to 30% without it running

Can you share exact numbers and not percentages? How do you measure it? What command line tool do you use?

**Comment by webotop** [comment]
@ilyam8 Okay if this can help you guys

Bug report Summary
Having netdata taking up to 95% ram when activated rather than 30% when not used.
I am having 2go of real memory.

OS / Environment
Debian GNU/Linux 10 (buster)

Netdata version
netdata v1.31.0-76-nightly

Installation Method
bash <(curl -Ss https://my-netdata.io/kickstart.sh)

Steps to reproduce
Well here I dunno I didn't change nothing in my setup. I guess just having a debian 10 up to date ...

Expected Behaviour
With Netdata activated it was taking up to 40% of my real memory. Witch is fine.

-- I do believe that Netdata is not caching anymore in virtual memory. But why ...

**Comment by ilyam8** [comment]
Thanks, @webotop!

- Is your setup a single Netdata instance?
- How do you measure memory? Using `free`?
- Could you show show `netdata -W buildinfo`?
- Could you send [a snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) to `ilya@netdata.cloud`?
