### ISSUE TITLE
`netdata-updater.log.*` written to `/` around time of update checks, and not removed

### ISSUE THREAD

**Issue by petecooper** [netdata/netdata#10472]
##### Bug report summary

Netdata writes log files to `/`, around the time of the `crontab` update checks, comprising the following text:

```
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
```
Files are named `netdata-updater.log` plus an appended six character (random?) alphanumeric string:

```
$ ls -al /
total 4194416
drwxr-xr-x  19 root     root       4096 Jan  9 06:30 .
drwxr-xr-x  19 root     root       4096 Jan  9 06:30 ..
lrwxrwxrwx   1 root     root          7 Oct 16 21:39 bin -> usr/bin
drwxr-xr-x   4 root     root       4096 Jan  9 06:29 boot
drwxr-xr-x  17 root     root       3820 Jan  9 06:30 dev
[…]
drwxr-xr-x   2 root     root       4096 Oct 16 21:39 media
drwxr-xr-x   3 root     root       4096 Jan  4 15:02 mnt
-rw-------   1 root     root        110 Jan  5 23:32 netdata-updater.log.1sSTom
-rw-------   1 root     root        110 Jan  7 00:23 netdata-updater.log.3N2cem
-rw-------   1 root     root        110 Jan  7 23:55 netdata-updater.log.CAiReb
-rw-------   1 root     root        110 Jan  5 00:21 netdata-updater.log.a4UvWb
-rw-------   1 root     root        110 Jan  8 23:41 netdata-updater.log.tbVkHv
drwxr-xr-x   9 do-agent root       4096 Jan  4 14:55 opt
dr-xr-xr-x 134 root     root          0 Jan  9 06:29 proc
[…]
```

##### OS / Environment

```
$ uname -a; grep -Hv "^#" /etc/*release 
Linux tonight 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

```
$ netdata -V
netdata v1.28.0
```

```
$(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V
netdata v1.28.0
```

##### Component Name

Packaging (tbc)

##### Steps To Reproduce

1. Install Netdata from 1.28.0 release.
2. Manually set `crontab` checking, e.g.: `27 23 * * * bash /usr/libexec/netdata/netdata-updater.sh`

##### Expected behavior

Log files to be kept in appropriate Netdata log dir, and / or logs to be left in `tmp`, and / or logs cleared from `/`.

**Comment by Ferroin** [comment]
This has been a known issue for a while but has never really been high enough priority to fix it.

In practice, you should only be seeing these if the updater is failing (which it probably is in your case, as there is a known bug with a pending fix right now, see https://github.com/netdata/netdata/pull/10447 for more details on that), as we only leave behind log files when the update was not successful.

**Comment by petecooper** [comment]
Thanks @Ferroin – I'll close given it's a known issue, I appreciate the link!

**Comment by Ferroin** [comment]
@petecooper Actually, unless you mind I’d like to leave this open as we don’t have an issue tracking the log-handling problem and it’s something that we really should fix (not having anything tracking it is pat of why it’s never ended up being a high enough priority to fix it).

**Comment by alokraj68** [comment]
This issue has actually filled my whole server today. it has happened on 2 servers with netdata version 1.7

**Comment by alokraj68** [comment]
the root cause is ubuntu installation had python json module missing. hence all these problems. :(

**Comment by petecooper** [comment]
@alokraj68 - did you find a workaround?

**Comment by ilyam8** [comment]
What json module @alokraj68? Python has a built-in package called json.

**Comment by alokraj68** [comment]
It was that if you run the update script manually you will get the missing package message, just install all of them manually. then your issue will be resolved.
