### ISSUE TITLE
Postgresql support？

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#10485]
##### Bug report summary
https://learn.netdata.cloud/docs/export/external-databases lists all supported database through connectors, including postgresql ( with Prometheus remote write).

But the [storage providers](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage) show that only 
PostgreSQL/TimescaleDB is supported. Here PostgreSQL/TimescaleDB is not the native postgresql but a time-series database with a plugin on postgresql.

So, the conclusion is that native is not supported to be the backend of netdata?

If yes, please update the document.
If no, the [adapter](https://github.com/timescale/promscale) shows that it only supported timescaledb not native postgresql. How could I use native postgresql as backend of netdata?

**Comment by ilyam8** [comment]
Hi @oleotiger 

> the conclusion is that native is not supported to be the backend of netdata

I think you are right, @vlvkobal please take a look

**Comment by vlvkobal** [comment]
@oleotiger you are right. PostgreSQL doesn't support Prometheus remote write natively. TimescaleDB or a new [PostgreSQL Prometheus Adapter](https://www.postgresql.org/about/news/postgresql-prometheus-adapter-initial-release-2070/) should be used to export data to PostgreSQL.

**Comment by ilyam8** [comment]
@vlvkobal then we need to update our documentaion?
