### ISSUE TITLE
Syntax error: anomalies.chart.py

### ISSUE THREAD

**Issue by Lamera** [netdata/netdata#10499]
##### Bug report summary

I enabled the anomalies collector according to [https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/anomalies](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/anomalies).
After restarting the agent I got this syntax error:
`
2021-01-13 13:35:06: python.d WARNING: plugin[main] : [anomalies] error on loading source : SyntaxError('invalid syntax', ('/usr/libexec/netdata/python.d/anomalies.chart.py', 84, 108, "        self.charts_available = [c for c in list(requests.get(f'{self.protocol}://{self.host}/api/v1/charts').json().get('charts', {}).keys())]\n")), skipping it
`

##### OS / Environment

```
Linux netdata 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

 netdata v1.28.0-116-nightly

##### Component Name

Collectors
##### Steps To Reproduce

1. Enable anomalies

##### Expected behavior

No syntax errors.

**Comment by ilyam8** [comment]
Hi @Lamera 👋 

What is your python version? [I see this module require python version 3](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/anomalies#requirements).

```cmd
[ilyam@pc ~]$ python --version
Python 3.9.1
```

**Comment by Lamera** [comment]
Python 3.8.5

**Comment by ilyam8** [comment]
@Lamera 

You can set python version explicitly in the `netdata.conf`

```cmd
[ilyam@pc netdata]$ grep "plugin:python.d" -A 2 netdata.conf
[plugin:python.d]
	# update every = 1
	command options = -ppython3
```

**Comment by ilyam8** [comment]
@andrewm4894 

> 2021-01-13 13:35:06: python.d WARNING: plugin[main] : [anomalies] error on loading source : SyntaxError('invalid syntax', ('/usr/libexec/netdata/python.d/anomalies.chart.py', 84, 108, " self.charts_available = [c for c in list(requests.get(f'{self.protocol}://{self.host}/api/v1/charts').json().get('charts', {}).keys())]\n")), skipping it

I would consider it as a bug, i suggest to add python version detection to the module and log a message that say that python3 is required, etc.

**Comment by andrewm4894** [comment]
thanks @Lamera for raising the issue - i'll add a better error message as this has already happened a few times with others. 

p.s. would love to hear any feedback or learnings from your use of it - i created a thread in the community forum where i am looking to collect feedback from people: https://community.netdata.cloud/t/anomalies-collector-feedback-megathread/767.

**Comment by ilyam8** [comment]
@andrewm4894 i think we need to add https://github.com/netdata/netdata/issues/10499#issuecomment-759523781  to the anomalies collector readme

**Comment by ilyam8** [comment]
Cleaning up the issues.

Using python3 is a requirement according to the collector [documentation](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/anomalies#requirements).
