### ISSUE TITLE
Account Linking is harmful and is a Non-Feature

### ISSUE THREAD

**Issue by kromit** [netdata/netdata#10497]
I have multiple (20+) agents sending streams to central server. All health notification are sent from that server only. I do not use cloud services.

During several upgrades, I've noticed different issues that could be easily fixed by doping old time series on the central server. So this is my default upgrade practice now: Drop data, restart central server, everything is working. But there is one problem: All links in the notifications are broken due to account linking and I have to visit every single node again to make it work.

```
Sorry... your account is not linked to a netdata server named: 
agent.example.com
```

Notification links like `https://netdata.example.com/goto-host-from-alarm.html?host=agent.example.com`are handled differently than `https://netdata.example.com/host/agent.example.com` and it makes no sense since everyone can just rewrite the URL. This is pseudo-security and is actually harming the security by providing a false sense of it.

What account is it anyway? I've tried to find some agent documentation on it, but was not successful. How am I supposed to explain to my boss that he can not click on the critical notification, because his non existent "account" is "not linked" and he just need to rewrite the link from time to time on his mobile?

Account Linking should be removed entirely because: 
- the are no accounts 
- the are no security benefits
- it provides false security sense
- it leads to bad user experience

**Comment by OdysLam** [comment]
Hey @kromit,

Thanks for this great feedback. We no longer use GitHub to discuss general issues, but instead, we use our forums at https://community.netdata.cloud.

I will close this issue and continue the discussion on the topic that I created on the Feature Request category. In case you want to track it, create a forum account, and reply to the topic.

Thanks and welcome to our community :)
