### ISSUE TITLE
netdata changes ownership of my directory

### ISSUE THREAD

**Issue by moeinrahimi** [netdata/netdata#10504]
this is really odd I have one directory which holds my MongoDB database files which belongs to user bento and when I start netdata user bento changes to netdata, I'm also trying to setup MongoDB monitoring. I'm not sure if that's the cause of ownership changes.
![image](https://user-images.githubusercontent.com/13715024/104591095-7ba34680-5681-11eb-9e4a-d6f97ad41e5f.png)

**Comment by moeinrahimi** [comment]
starting and stopping netdata has nothing to do with the above issue, I suspect it is related to commands I mentioned in this issue #10503

**Comment by ilyam8** [comment]
Hi @moeinrahimi 

Netdata Agent uses [pymongo library](https://pymongo.readthedocs.io/en/stable/) and executed the following commands:

 - [`serverStatus`](https://github.com/netdata/netdata/blob/586945c2b78f5dc4680972d92c2d5e9d0bb9a617/collectors/python.d.plugin/mongodb/mongodb.chart.py#L598)
 - [`dbStats`](https://github.com/netdata/netdata/blob/586945c2b78f5dc4680972d92c2d5e9d0bb9a617/collectors/python.d.plugin/mongodb/mongodb.chart.py#L612)
 - [`replSetGetStatus`](https://github.com/netdata/netdata/blob/586945c2b78f5dc4680972d92c2d5e9d0bb9a617/collectors/python.d.plugin/mongodb/mongodb.chart.py#L623)
 - [`getReplicationInfo`](https://github.com/netdata/netdata/blob/586945c2b78f5dc4680972d92c2d5e9d0bb9a617/collectors/python.d.plugin/mongodb/mongodb.chart.py#L633-L639)

Also it has no permissions to alter any data or change directores permissions:

```cmd
  "roles" : [
    {role: 'read', db: 'admin' },
    {role: 'clusterMonitor', db: 'admin'},
    {role: 'read', db: 'local' }
  ]
```

`read` is self-explanatory, [`clusterMonitor`](https://docs.mongodb.com/manual/reference/built-in-roles/#clusterMonitor) provides read-only access to monitoring tools.

---

I don't know what causes the issue, it would be nice to replicate it and understand - can you provide additional details about your setup: mongodb version, install method (docker or not), pymongo version, netdata version.
