### ISSUE TITLE
We need to be able to tune WSS and MQTT Connection properties

### ISSUE THREAD

**Issue by krital** [netdata/netdata#10512]
We need to be able to specify connection properties that are used by the agent to connect to the cloud. Specifically we need the following at both WSS and MQTT layers:

1. Disable Naggle (AKA TCP_NO_DELAY)
2. Specify the TCP Connection Timeout
3. Specify the buffer sizes used on socket read / write

**Comment by Ferroin** [comment]
Just to make sure it doesn’t get forgotten, these changes should undergo proper testing on not only Linux but also macOS and FreeBSD. Their networking stacks are different enough that we may have to special-case some things there.

**Comment by krital** [comment]
Fair point however the things I am asking are pretty standard and exist on all OSs.. Please note I am not trying to change the OS settings but do it in the agent code.

**Comment by underhood** [comment]
all those depend in our case on libwebsockets (what they do and how much their API allows us to affect that). Will look into that
For naggle ACLK-NG disables it but is not really necessary appart from MQTT keep-alives there are not really any tiny messages (thanks to the JSON encapsulation)

**Comment by underhood** [comment]
nagle seems to be disabled by LWS library by default on unix

**Comment by underhood** [comment]
> 3. Specify the buffer sizes used on socket read / write
Do you mean our buffers or socket buffers SO_RCVBUF/SO_SNDBUF

**Comment by krital** [comment]
I mean socket buffers, I want to be able to tune these easily from the configuration

**Comment by underhood** [comment]
OK will investigate, quick look seems there is not much exposed by LWS to us to tune this

**Comment by ilyam8** [comment]
No longer relevant.
