### ISSUE TITLE
Is there document about native metrics collected by netdata?

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#10514]
I use netdata to collect metrics and export them to timescaledb with data provider. After getting metrics from postgresql, I find netdata is a really inspiring and excellect tool.

With as-collected metrics I wanna output some meaningful metrics. For example, I wanna calclute cup utilization with metrics such as system.cpu.idle,system.cpu.user,system.cpu.iowai,system.cpu.system.
I know that I can get metrics as average and cpu utilization ratio is stored in the database directly. But here I wanna do it myself for flexible control and understanding of the system.

Q1:

So, is there any document that describe the meaning/unit of the metrics?

Q2:

If I wanna to lean how to calclute metrics in average format, is there any document that help me to find the calcluting way from source code?

This is not a bug, but I didn't get response after posting this question on Netdata Community for about 3 days.

**Comment by ilyam8** [comment]
Hi @oleotiger 

> This is not a bug, but I didn't get response after posting this question on Netdata Community for about 3 days.


Sorry for that expirience. Sometimes it takes some time, we are trying to reply as soon as possible.

Lets continue the discussion on the forum!
