### ISSUE TITLE
lack of dbengine statistics if proc plugin is disabled (`Netdata Monitoring->dbengine`)

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#10510]
##### Bug report summary

Discovered in #10423, see [the comment](https://github.com/netdata/netdata/issues/10423#issuecomment-760223846).

Use case: netdata in k8s - Netdata parent has all collectors disabled, because children instances are responsible for data collection. However parent instance maintains the database.

I think the only requirement for `Netdata Monitoring->dbengine` is enabled dbegine memory mode. 

Currently those statistics populated by [global_statistics_charts](https://github.com/netdata/netdata/blob/de6035c543296de179e359a415664106d66c3878/daemon/global_statistics.c#L174) function which seems doesnt executed if there are no active collectors.

##### OS / Environment

any

##### Netdata version

`netdata v1.28.0-134-g6dade0cd0`
 

##### Component Name

`daemon`

##### Steps To Reproduce

1. Parent-child setup, parent memory mode is dbengine, all collectors on the parent instance are disabled.

##### Expected behavior

Always have dbengine statistics if memory mode is dbengine.

**Comment by kam1kaze** [comment]
I've tested various combinations of active collectors and dbengine stats work only if `proc` collector is enabled. So my config looks like this now:

```
        [plugins]
          cgroups = no
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = no
          go.d = no
          node.d = no
          apps = no
          proc = yes
          idlejitter = no
          diskspace = no
```
