### ISSUE TITLE
Cannot export metrics to timescaledb

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#10529]
##### Bug report summary
With prometheus remote write, I can export data to postgresql through [postgresql-prometheus-adapter](https://github.com/CrunchyData/postgresql-prometheus-adapter). 

I can export metrics to timescaledb through netdata-timescale-relay in json format as well.

But when I use [proscale](https://github.com/timescale/promscale) to export metrics to timescaledb through prometheus remote write, I get error message from promscale like 
```
level=error ts=2021-01-15T06:20:35.557Z caller=write.go:239 msg="Write header validation error" err="unsupported data format (not protobuf or json)"
```

Export.conf

```
[prometheus_remote_write:netdata_remote_write]
    enabled = yes
    destination = localhost:9201
    remote write URL path = /write
    data source = as collected
    prefix = netdata
    hostname = xxx
    update every = 3
    buffer on failures = 10
    # timeout ms = 20000
    # send names instead of ids = yes
    # send charts matching = *
    # send hosts matching = localhost *

```

##### OS / Environment
CentOS Linux release 7.7.1908

##### Netdata version
netdata v1.28.0-128-g852bbdf 

##### Component Name
export

##### Steps To Reproduce
netdata is compiled with protobuf and snappy. Component works well with postgresql as database through postgresql-prometheus-adapter and with timescaledb through promscale.

But when I change database to timescaledb and change adapter to promscale, I get errors printed by promscale:
```
level=error ts=2021-01-15T06:20:50.557Z caller=write.go:239 msg="Write header validation error" err="unsupported data format (not protobuf or json)"
```

##### Expected behavior
Data should export to timescaledb through promscale as described by the document.

**Comment by ilyam8** [comment]
Closing in favor of #10537
