### ISSUE TITLE
Incorrect launch of netdata on ubuntu 20 - service running on 0.0.0.0 and ::1 interfaces. 

### ISSUE THREAD

**Issue by collex100** [netdata/netdata#10535]
##### Bug report summary
I have an issue with binding service. In config file in [web] section we set 
bind to = 127.0.0.1
 but service still running on 0.0.0.0 and ::1 interfaces. 

These settings work fine on Ubuntu 18.04, but they don't work correctly on ubuntu 20.04

##### OS / Environment
Ubuntu 20.04

##### Steps To Reproduce
1) clone https://github.com/firehol/netdata.git в каталог /usr/src/netdata
2) run cd /usr/src/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here
3) uncomment line bind to
4) systemctl restart netdata

##### Expected behavior
The application must start using the domain and port

##### Settings

cat /etc/netdata/netdata.conf | grep -v "#"

[global]

[web]
  bind to = 127.0.0.1

[plugins]

[health]

[registry]

[backend]

[statsd]

[plugin:fping]

[plugin:idlejitter]

[plugin:tc]

[plugin:python.d]

[plugin:charts.d]

[plugin:go.d]

[plugin:node.d]
...

##### NGINX

server {
    listen      {{ IP }}:19999;
    location / {
        auth_basic           "O-ops! Password required";
        auth_basic_user_file /usr/share/netdata_auth;
        proxy_pass http://127.0.0.1:19999;
    }
}

**Comment by ilyam8** [comment]
Hi @collex100 👋 

Thx for reporting the bug, however i can't reproduce it.

I doubt it is distro specific, my distro is manjaro.

```bash
# Netdata version
[pc ilyam]# /opt/netdata/usr/sbin/netdata -v
netdata v1.28.0-178-gdab0a6f6

# Current 'bind to' setting
[pc ilyam]# grep "bind to" /opt/netdata/etc/netdata/netdata.conf
	# bind to = *
	# bind to = udp:localhost tcp:localhost

# Let's check listen address, it is 0.0.0.0 as expected
[pc ilyam]# ss -ntlp | grep netdata
LISTEN 0      4096       127.0.0.1:8125       0.0.0.0:*    users:(("netdata",pid=49394,fd=43))
LISTEN 0      4096         0.0.0.0:19999      0.0.0.0:*    users:(("netdata",pid=49394,fd=4))
LISTEN 0      4096           [::1]:8125          [::]:*    users:(("netdata",pid=49394,fd=42))
LISTEN 0      4096            [::]:19999         [::]:*    users:(("netdata",pid=49394,fd=5))

# Let's change 'bind to' to '127.0.0.1' 
[pc ilyam]# sed -i 's/# bind to = \*/bind to = 127.0.0.1/' /opt/netdata/etc/netdata/netdata.conf

# Checking changes, all is ok
[pc ilyam]# grep "bind to" /opt/netdata/etc/netdata/netdata.conf
	bind to = 127.0.0.1
	# bind to = udp:localhost tcp:localhost

# Netdata service restart
[pc ilyam]# systemctl restart netdata

# Checking listen address - it is '127.0.0.1' as expected
[pc ilyam]# ss -ntlp | grep netdata
LISTEN 0      4096       127.0.0.1:8125       0.0.0.0:*    users:(("netdata",pid=50518,fd=38))
LISTEN 0      4096       127.0.0.1:19999      0.0.0.0:*    users:(("netdata",pid=50518,fd=4))
LISTEN 0      4096           [::1]:8125          [::]:*    users:(("netdata",pid=50518,fd=33))
```

**Comment by ilyam8** [comment]
Interesting observation - `[web] bind to` option affects statsd, i think it shouldnt, but not sure. 

@stelfrag @vlvkobal @thiagoftsm ?

**Comment by thiagoftsm** [comment]
Hello @collex100 ,

Like @ilyam8 I tried to replicate the problem on `Ubuntu  20.04.1` and I did not have success:

![VirtualBox_ubuntu_20_04_21_01_2021_17_45_17](https://user-images.githubusercontent.com/49162938/105390269-c5a3a380-5c10-11eb-9bb2-03b44fed7912.png)

Please, can you do the following request for Netdata?

```bash
curl  -o netdata.conf http://localhost:19999/netdata.conf
```

And after this, please, take a look at the options `bind to` and `config directory`.  I am suspecting that your `netdata` is installed in another directory and you are not changing your `bind to` as you are expecting.

Best regards!

**Comment by collex100** [comment]
The installation in this way helped
`$ bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

Thank you guys for your prompt support. I had a release from a year ago. This latest release of the program has become much cooler. :)
