### ISSUE TITLE
Oracle Linux 8 can`t install 

### ISSUE THREAD

**Issue by Gushtera** [netdata/netdata#10534]
Hello guys,
after deep debugging I can`t understand where is the issue. Here is the error that I`m getting:

configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.
 FAILED

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues

 FAILED

 ABORTED  netdata-installer.sh exited with error

-----------------------------------------------------------------------------------------

and this is the start of the installation:

/etc/os-release information:
NAME            : Oracle Linux Server
VERSION         : 8.3
ID              : ol
ID_LIKE         : fedora
VERSION_ID      : 8.3

We detected these:
Distribution    : fedora
Version         : 8.3
Codename        : 8.3
Package Manager : install_dnf
Packages Tree   : rhel
Detection Method: /etc/os-release
Default Python v: 3

Searching for distro_sdk ...
Searching for autoconf_archive ...
 > Checking if package 'autoconf-archive' is installed...
Searching for autogen ...
 > Checking if package 'autogen' is installed...
Searching for libz_dev ...
 > Checking if package 'zlib-devel' is installed...
Searching for libuuid_dev ...
 > Checking if package 'libuuid-devel' is installed...
Searching for libmnl_dev ...
 > Checking if package 'libmnl-devel' is installed...
Searching for json_c_dev ...
 > Checking if package 'json-c-devel' is installed...
Searching for libuv ...
 > Checking if package 'libuv-devel' is installed...
Searching for lz4 ...
 > Checking if package 'lz4-devel' is installed...
Searching for openssl ...
 > Checking if package 'openssl-devel' is installed...
Searching for judy ...
 > Checking if package 'Judy-devel' is installed...
Searching for libelf ...
 > Checking if package 'elfutils-libelf-devel' is installed...

**Comment by stelfrag** [comment]
Hi @Gushtera :wave: 

thank you for reporting this!

@Ferroin can you please take a look?

**Comment by ilyam8** [comment]
@Gushtera 

> configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.

Did you try to install `libuv-devel` and rerun the installer?

We had [similar issue with oracle linux 7](https://github.com/netdata/netdata/issues/8602#issuecomment-610235552).

**Comment by cstrouse** [comment]
`yum update --allowerasing` resolved this for me on a pre-baked centos 8 OLS vm on linode.

**Comment by stelfrag** [comment]
Hi @Gushtera 

Did you manage to resolve this?

**Comment by ilyam8** [comment]
Closing due to no response. @cstrouse thanks for sharing the fix 👍
