### ISSUE TITLE
Debian Buster 

### ISSUE THREAD

**Issue by NA7KR** [netdata/netdata#10547]
Debian Buster 
The following packages have unmet dependencies:
 libelf-dev : Depends: libelf1 (= 0.176-1) but 0.176-1.1 is to be installed
 libjson-c-dev : Depends: libjson-c3 (= 0.12.1+ds-2) but 0.12.1+ds-2+deb10u1 is to be installed
E: Unable to correct problems, you have held broken packages.

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues

 FAILED

 ABORTED  netdata-installer.sh exited with error

**Comment by kllngtme** [comment]
Yea, not sure what happened or if I was seeing that before on mine but since the latest docker pull I'm getting:
netdata exited with code 139

I'm running this on a docker container on a raspberry pi 4

**Comment by Coxis** [comment]
I'm also having this problem. I'm trying to install Netdata on OMV 5 running on a Rapsberry PI 4 4GB. 

 exit code 139

**Comment by kllngtme** [comment]
I decided to downgrade and got it working again using netdata/netdata:v1.27.0

**Comment by ilyam8** [comment]
Thx for reporting, guys. Reason is [Alpine 3.13.0](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0)

> Therefore, the following platforms are not suitable as Docker hosts for 32-bit Alpine Linux 3.13.0, due to containing out-of-date libseccomp: Amazon Linux 1 or 2, CentOS 7 or 8, Debian stable without debian-backports, Raspbian stable, Ubuntu 14.04 or earlier, and Windows. This applies regardless of whether the Linux distribution Docker packages or separate Docker package repositories are used

**Comment by NA7KR** [comment]
What is the fix?

**Comment by stelfrag** [comment]
The two issues (installation on debian buster and docker installation on RPI4) seem to be unrelated.

- For now using netdata/netdata:v1.27.0 (RPI4 docker) works until we see how to deal with it properly.  
- For the debian buster installation, @Ferroin would it helpful to have more information to troubleshoot and/or improve the process?

**Comment by ilyam8** [comment]
> Unable to correct problems, you have held broken packages

i would do the following @NA7KR 

```
sudo apt-get update
sudo apt-get ugrade
sudo apt-get autoremove

# then try to install netdata again
```

**Comment by Ferroin** [comment]
For the Docker issues, we’re rolling back to using Alpine 3.12 as a base for the time being, and will re-evaluate each time there’s a new version of Alpine released. Starting with tonight’s  nightly build, the `latest` tag for the Docker images should work properly again on Debian and Raspbian.

**Comment by stelfrag** [comment]
Hi @kllngtme the latest tag for the docker image now works properly on RPi4

**Comment by kllngtme** [comment]
> Hi @kllngtme the latest tag for the docker image now works properly on RPi4

Thanks, works no issues

**Comment by stelfrag** [comment]
Hi @NA7KR 

Did you manage to complete the installation following the suggestion by @ilyam8  in a previous [comment](https://github.com/netdata/netdata/issues/10547#issuecomment-767400492)?

**Comment by stelfrag** [comment]
Closing this, feel free to join our [community forums](https://community.netdata.cloud/) for additional help if needed!
