### ISSUE TITLE
netdata agent runs out of memory without warning

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#10540]
##### Bug report summary

The netdata agent, or any other process in the system, can run out of memory unexpectedly. The reason is that the process can hit the per-process limit of the maximum number of memory mappings (`vm.max_map_count`, `/proc/sys/vm/max_map_count`).

Netdata does not detect this, and does not warn about it before it happens. At a high level, what needs to happen per process is to compare `wc -l /proc/PID/maps` with `cat /proc/sys/vm/max_map_count`.

What is missing is the collector logic and the corresponding alarms.

##### Netdata version

 
v1.28.0

##### Component Name

collectors
health
##### Steps To Reproduce

1. Set-up netdata with `memory mode = save`. This creates at least one mapping per dimension.
2. Enable statsd collector and increase its limits:
    - `max private charts allowed = 65536`
    - `max private charts hard limit = 70000`
3. Create an adequate number of dimensions:
```
for (( i = 1 ; i < 65536 ; ++i )) ; do
  echo -e "kong.F5Monitor.request.status.total:1|c\nmymetric.name$i:1|c" | socat -t0 -  tcp:127.0.0.1:8125 ;
  echo $i ; 
done
```
This way, the netdata agent itself will run out of memory.

##### Expected behavior

Netdata should warn before a process runs out of memory.

**Comment by ilyam8** [comment]
Column names

```
address perms offset  dev   inode   pathname
```

> Netdata does not detect this, and does not warn about it before it happens. At a high level, what needs to happen per process is to compare wc -l /proc/PID/maps with cat /proc/sys/vm/max_map_count

@mfundul Is it really just counting the entries? I see there are a lot of entries with `0` inode 🤔

**Comment by thiagoftsm** [comment]
Yes @ilyam8 ,

As you can see at the [comment](https://elixir.bootlin.com/linux/latest/source/fs/proc/task_nommu.c#L189), they are also mapped region, so we need to count them.

**Comment by ilyam8** [comment]
Reading `/proc/PID/maps` requires root privileges => an external plugin. 

I think a collector for this is not required, a note in the documentation for `mode memory = save` will do:

- `save` mode is not default
- it is well-known that every chart/dimensions is +1 `map_count`
- it is well-known that default `max_map_count` is 65530

So switching to memory mode `save` a user need to take it into account and increase the parameter if it is expected netdata instance is going to have a lot of charts/memory. Increasing that parameter is not a problem at all.

**Comment by mfundul** [comment]
> Increasing that parameter is not a problem at all

It is a problem because users may not have privileges to increase it, and also, as we saw internally, increasing the value restarts all pods in the node in kubernetes.

> I think a collector for this is not required

A collector is required, since the biggest issue is not netdata itself (`dbengine` avoids the problem), but the fact that we don't monitor other processes that may run out of memory this way. We need a new alarm for this and it is of critical importance to the users in my opinion.

**Comment by ilyam8** [comment]
I see elasticsearch has special init container to modify that value

https://github.com/elastic/helm-charts/blob/3fb0c8267e146ef9ae8d8de7f836bb775c03e960/elasticsearch/templates/statefulset.yaml#L161-L168

I doubt it restarts all pods in the node in kubernetes.

**Comment by mfundul** [comment]
> 
> 
> I see elasticsearch has special init container to modify that value
> 
> https://github.com/elastic/helm-charts/blob/3fb0c8267e146ef9ae8d8de7f836bb775c03e960/elasticsearch/templates/statefulset.yaml#L161-L168
> 
> I doubt it restarts all pods in the node in kubernetes.

@knatsakis observed this restart.

**Comment by thiagoftsm** [comment]
@mfundul I took a look inside kernel now to verify what it would be necessary to do with `ebpf.plugin` to collect data, and I observed that with our current structure, it is not possible to collect the information. This happens because the [structure](https://elixir.bootlin.com/linux/latest/source/include/linux/mm_types.h#L567) that we need to read data has a `__randomize_layout`.
