### ISSUE TITLE
OpsGenie API URL is hardcoded into alarm-notify.sh, more an oversight than a bug

### ISSUE THREAD

**Issue by tinyhammers** [netdata/netdata#10556]
##### Bug report summary

Alerts not being sent to OpsGenie via the native integration, showing an HTTP 401 error

##### OS / Environment

```
Linux edge-audio-01-cr 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="8"
/etc/os-release:VERSION="8 (jessie)"
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="http://www.debian.org/"
/etc/os-release:SUPPORT_URL="http://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version
netdata v1.28.0

 

##### Steps To Reproduce

Setup the Netdata OpsGenie integration within OpsGenie and got the API key. Added the key to health_alarm_notify.conf as per the documenation.
Ran a test alert via `usr/libexec/netdata/plugins.d/alarm-notify.sh test sysadmin`
Output was stating HTTP 401 error when trying to send to OpsGenie. Given there is no definable API endpoint, guessed it must be hardcoded somewhere. 
Found the specific line in `usr/libexec/netdata/plugins.d/alarm-notify.sh`, line 2182. The API endpoint is defined as `https://api.opsgenie.com/v1/json/integrations/webhooks/netdata?apiKey=${OPSGENIE_API_KEY}`
There is a different URL for OpsGenie accounts in the EU which is `https://api.eu.opsgenie.com/v1/json/integrations/webhooks/netdata?apiKey=${OPSGENIE_API_KEY}` (note api.EU.opsgenie...)
I have amended this and rolled out a new version of `alarm-notify.sh` across the estate and it is now working as expected, so can confirm that this does fix the issue for EU account holders.

##### Expected behavior

Expected to follow documentation and for alerts to be received by OpsGenie. This does not work for EU OpsGenie customers due to the hardcoded API endpoint.

Can this be set as a variable so users can specify the endpoint relevant to their OpsGenie account?

**Comment by OdysLam** [comment]
Thanks @tinyhammers,

Would you be interested in contributing this? It should be relatively easy to PR and get it accepted. What do you think @ilyam8  ?

**Comment by ilyam8** [comment]
Hi @tinyhammers 

You are right, it is hardcoded

https://github.com/netdata/netdata/blob/b66c01d9b826d7b6f763c48ab73b0d5e4de58227/health/notifications/alarm-notify.sh.in#L2182

We need to add `OPSGENIE_HOST` variable.

Are you willing to make a PR?

**Comment by thiagoftsm** [comment]
Hello @tinyhammers ,

Thank you for the report. I did not know that we had different URLs, when we worked with OpsGenie, this information was not explicit.

**Comment by tinyhammers** [comment]
Hey @ilyam8 
Happy to do a PR for this. 
@thiagoftsm, no worries, I only found it by accident 😂

**Comment by tinyhammers** [comment]
Whats your PR procedure?

**Comment by thiagoftsm** [comment]
Hello @tinyhammers ,

You will need to do the following steps:

1 - Clone Netdata.
2 - Change the file `health/notifications/alarm-notify.sh.in ` to use the new variable.
3 - Change the file `health/notifications/health_alarm_notify.conf` to insert the variable there.
4 - After this you commit the changes and create a PR.
5 - Github you require you to sign our CLA.

If you have any doubt, please, let me know.

Best regards!

**Comment by tinyhammers** [comment]
OK, so seem to have done this as two PRs for some reason. Sorry.
Also, I called it OPSGENIE_API_URL as that seemed a little more descriptive 😃

https://github.com/netdata/netdata/pull/10561
https://github.com/netdata/netdata/pull/10562

**Comment by thiagoftsm** [comment]
> OK, so seem to have done this as two PRs for some reason. Maybe as I did it via the web UI? Sorry.
> Also, I called it OPSGENIE_API_URL as that seemed a little more descriptive smiley
> 
> #10561
> #10562

No problem, please, take a look in our comments for your PRs.
