### ISSUE TITLE
charts with different granularity are not aligned

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#10554]
![Peek 2021-01-26 09-14](https://user-images.githubusercontent.com/2662304/105813477-bd2ad000-5f64-11eb-8706-5678cb869f0e.gif)

The second chart has 5-sec granularity. The others have 1-sec.

When the charts are not full, the charts are not aligned. To my understanding the 5-sec chart (the 2nd) does not respect the visible duration, which should be the same for all charts.

**Comment by ilyam8** [comment]
Issue moved to [netdata/dashboard #299](https://github.com/netdata/dashboard/issues/299) via [**ZenHub**](https://www.zenhub.com/)
