### ISSUE TITLE
Machine virtualization incorrectly identified in proxmox host with lxc containers

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#10568]
##### Bug report summary
Our system-info.sh returns "none" for virtualization technology, but it is lxc.

##### OS / Environment
Debian buster

##### Netdata version
Latest
 

##### Component Name
system-info.sh

##### Steps To Reproduce
run `systemd-detect-virt` and `systemd-detect-virt -v`. The former returns `lxc`, the latter `none`.

##### Expected behavior
Return the correct virtualization technology.

reference: https://community.netdata.cloud/t/best-way-to-setup-netdata-in-a-proxmox-host-with-some-lxc-containers/81

**Comment by cakrit** [comment]
It's probably container virtualization actually. Preparing a fix that I'll validate with the user.

**Comment by vlvkobal** [comment]
#10569 didn't really fix the issue. The same problem was [reported](https://community.netdata.cloud/t/netdata-installed-in-lxc-retrieves-statistics-from-bare-metal/3175) recently for the Proxmox environment
```
	"virtualization": "none",
	"virt_detection": "systemd-detect-virt",
	"container": "unknown",
	"container_detection": "systemd-detect-virt",
```
I also tested the script on Proxmox installed in VMware ESXi and got
```
NETDATA_SYSTEM_VIRTUALIZATION=vmware
NETDATA_SYSTEM_VIRT_DETECTION=systemd-detect-virt
NETDATA_SYSTEM_CONTAINER=unknown
NETDATA_SYSTEM_CONTAINER_DETECTION=systemd-detect-virt

```
The `lxc` virtualization technology is container virtualization so it is returned by `systemd-detect-virt -c`. We should report `NETDATA_SYSTEM_CONTAINER=lxc` in that case.
