### ISSUE TITLE
Problematic handling of sub-second durations

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#10571]
Durations in certain charts can be returned in a strange precision (hundreds of nanoseconds), but our charts can only display durations in seconds, causing the following:

![image](https://user-images.githubusercontent.com/43294513/106316523-be3c5580-6221-11eb-95ac-15b269f951f7.png)

The specific charts are from Redis (collected via the prometheus collector) in our production.

**Comment by ilyam8** [comment]
Issue moved to [netdata/dashboard #301](https://github.com/netdata/dashboard/issues/301) via [**ZenHub**](https://www.zenhub.com/)
