### ISSUE TITLE
modified swap.conf defaults after every update

### ISSUE THREAD

**Issue by fate8383** [netdata/netdata#10576]
debian 10
netdata latest nightly
autoupdate on
I have few applications and I am aware that I am using swap so changing swap notification conf file in swap.conf, like 15-20 to 40-50 etc... every day netdata updates and overwrites my setup to defaults. everything else I set up remains the same, such as telegram notification and other settings for monitoring.

**Comment by stelfrag** [comment]
You can use the edit-config to make changes in the swap.conf file. 

During installation (and updates) the stock swap.conf file is placed under 
`/usr/lib/netdata/conf.d/health.d/swap.conf`

local changes to the file should go to 

`/etc/netdata/health.d/swap.conf`

Please also check [Health configuration](https://learn.netdata.cloud/docs/agent/health/reference#health-configuration-files)

**Comment by ilyam8** [comment]
@fate8383 hi 👋 @stelfrag is correct, it is not a bug, but expected behaviour - all stock configuration files are overwritten during installation/update.

If there are any questions consider to use [Netdata Comminuty forum](https://community.netdata.cloud/)!

**Comment by fate8383** [comment]
my apologies, i only found swap.conf under stock files, but after edit with edit-conf it generated under /etc/netdata/health.d. I assume it will be fine now. Thanks
