### ISSUE TITLE
Unable to Enable TLS for Web GUI

### ISSUE THREAD

**Issue by x86txt** [netdata/netdata#10575]
##### Bug report summary
When adding the necessary sections to netdata.conf to enable TLS for the web gui, TLS is never enabled and there are no indications in the log files as to why it is failing to enable.

##### OS / Environment

```
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"

-  tried both the apt package (1.12) I believe as well as the latest from github using the bash <(curl -Ss https://my-netdata.io/kickstart.sh) command.
```

##### Netdata version
netdata v1.28.0-226-nightly
 
##### Component Name
web

##### Steps To Reproduce
1. Add/Uncomment the following to /etc/netdata/netdata.conf
```
[web]
         ssl key = /etc/netdata/my.crt
         ssl certificate = /etc/netdata/my.key
         bind to = *
```
##### Expected behavior
Netdata shouold start answering requests over TLS on port 19999, yet it continues to operate unencrypted on port 19999.

**Comment by thiagoftsm** [comment]
Hello @x86txt ,

What are the permissions of the files `/etc/netdata/my.crt`, and  `/etc/netdata/my.key`?
Are you linking Netdata against OpenSSL? Or are you using another SSL library?

Best regards!

**Comment by stelfrag** [comment]
Hi @x86txt 

Did you manage to get this working?

**Comment by ilyam8** [comment]
Closing due to no response.
