### ISSUE TITLE
Netdata Cloud not loading data

### ISSUE THREAD

**Issue by iTzEthqnHD** [netdata/netdata#10589]
Hi, I just did a fresh install on a new server and it seems like Netdata Cloud is struggling to pull data. The node consistently shows time out when it isnt displaying. A reboot didnt help :(

**Comment by OdysLam** [comment]
Hey @iTzEthqnHD ,

I am so sorry that you are encountering this issue. Please make sure you open a  topic in our Support category at https://community.netdata.cloud. This way we can engage with our engineers and figure out the problem.

Don't worry, we got you covered! ✌️
