### ISSUE TITLE
The PackageCloud still not work in lastest version from rpm/deb

### ISSUE THREAD

**Issue by CberYellowstone** [netdata/netdata#10594]
the same problem as #10457 
the fix pr seems not works correctly
the problm is still there
version: `netdata.x86_64 0:1.29.5-1.el7` 

I'm sure I'm not the only one with this problem in the lastest version

@underhood @Ferroin

**Comment by OdysLam** [comment]
Hi @CberYellowstone,

Are you still experiencing this? 

cc @Ferroin

**Comment by CberYellowstone** [comment]
> Hi @CberYellowstone,
> 
> Are you still experiencing this?
> 
> cc @Ferroin

yeah, now I have update my netdata to the latest version `1.29.2-1.el7`
but the bug still exist
Do I need to provide more information?

**Comment by Ferroin** [comment]
First off, apologies for not following up with you sooner on this.

As far as additional information: What distribution are you seeing this on? Is it CentOS 7, RHEL 7, or some other RHEL derivative (like OEL or Amazon Linux)?

**Comment by CberYellowstone** [comment]
> First off, apologies for not following up with you sooner on this.
> 
> As far as additional information: What distribution are you seeing this on? Is it CentOS 7, RHEL 7, or some other RHEL derivative (like OEL or Amazon Linux)?

here is the detail

> [root@localhost ~]# ll /etc/*centos*
> -rw-r--r--. 1 root root 37 11月 23 23:08 /etc/centos-release
> -rw-r--r--. 1 root root 51 11月 23 23:08 /etc/centos-release-upstream

> [root@localhost ~]# cat /etc/centos-release
> CentOS Linux release 7.9.2009 (Core)

> [root@localhost ~]# uname -r
> 3.10.0-1160.15.2.el7.x86_64

> [root@localhost ~]# getconf LONG_BIT
> 64

**Comment by Ferroin** [comment]
Ok, just confirmed it locally too, something is wrong with how we’re building the packages. For some reason we’re not bundling libwebsockets properly.

**Comment by CberYellowstone** [comment]
> Ok, just confirmed it locally too, something is wrong with how we’re building the packages. For some reason we’re not bundling libwebsockets properly.

as far as I know, this bug has been 'fix' by 3 times
hope the bug can really repaired this time

**Comment by Ferroin** [comment]
After digging a bit, I’m pretty sure I know what’s wrong here, PR that (should) fix things properly should be up shortly.

**Comment by CberYellowstone** [comment]
> After digging a bit, I’m pretty sure I know what’s wrong here, PR that (should) fix things properly should be up shortly.

ok, I will eeedback after the new version comes out

**Comment by Ferroin** [comment]
The fix for this has been merged, so nightly packages (in the `netdata-edge` repo) should have proper cloud support starting tonight. It looks like we will be having another patch release either today or tomorrow s well, so the stable version should get the fix very soon as well.
