### ISSUE TITLE
no tags on dockerhub for 1.29.0

### ISSUE THREAD

**Issue by gyoza** [netdata/netdata#10592]
no tags on dockerhub for 1.29.0

**Comment by Ferroin** [comment]
Confirmed, something went wrong in the tag generation for our Docker images for the release, though I0m not sure what yet.

As of right now, the `latest` and `stable` tags are both v1.29.0, and the `v1.28.0` tag got unintentionally overwritten. Working on getting a `v1.29.0` tag up and fixing the `v1.28.0` tag.

**Comment by Ferroin** [comment]
The `v1.29.0` tag on DockerHub is correct now and should work without issue.

**Comment by Ferroin** [comment]
The `v1.28.0` tag is nos fixed as well.

**Comment by gyoza** [comment]
TYVM!!!!
