### ISSUE TITLE
ipv4 metrics not in influxdb but ipv6 shows even though disabled on host

### ISSUE THREAD

**Issue by mamema** [netdata/netdata#10605]
i've reported into an closed issue, which has the same reported:

https://github.com/netdata/netdata/issues/2819

**Comment by ilyam8** [comment]
Hi @mamema!

If you believe there is Netdata Agent bug please use bug template https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md

If you are not sure and just willing to ask a question - [consider to use our community forum](https://community.netdata.cloud/c/support/agent-support/14).

**Comment by mamema** [comment]
tried to make a community post and waiting since two days that my post gets published. Useless community!

**Comment by OdysLam** [comment]
Hey @mamema, 

Thanks for the feedback. The way our forums works, it screens out long walls of text that are not code snippets (between three backticks ```Like this```). I had to manually accept your post today and it's visible on the forums.

Thank you for your patience. See you there!
