### ISSUE TITLE
Claim node fails behind HTTPS proxy

### ISSUE THREAD

**Issue by robinhuiser** [netdata/netdata#10607]
##### Bug report summary
When running the `netdata-claim.sh` script to join a room, the script fails with the error "Unknown HTTP error message".

##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

netdata v1.29.0-13-nightly

##### Component Name

claim

##### Steps To Reproduce

1. install using `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
2. update /etc/netdata/netdata.conf under `[cloud]` with `proxy = http://proxy.my.domain:3128/`
3. run `sudo netdata-claim.sh -token=xxxx -rooms=yyyy -proxy=http://proxy.mydomain.3128/`

Output of last command:

~~~
Token: ****************
Base URL: https://app.netdata.cloud
Id: 02a48cf2-XXXXXXXXX-a7bb2fa79e79
Rooms: 67df4254-YYYYYYYY-f6323f398b62
Hostname: node-01
Proxy: http://proxy.mydomain:3128/
Netdata user: netdata

Failed to claim node with the following error message:: Unknown HTTP error message[7]
~~~

##### Expected behavior

Netdata agent is successfully claimed by room.

##### Issue analysis

The temporarily file `/var/lib/netdata/cloud.d/tmpout.txt` is parsed by the script `netdata-claim.sh` where the logic only assumes a single occurrence of "HTTP" (line 348).

When behind a HTTPS proxy (Squid in this case), the file contains the following content:

~~~
HTTP/1.1 200 Connection established

HTTP/2 204 
content-type: application/json; charset=utf-8
date: Sat, 06 Feb 2021 11:39:35 GMT
netdata-request-id: zdAnGw80Hm-000003
vary: Accept-Encoding
~~~

As you can see... the logic will break here.

##### Workaround / solution

Add to line 348 in script `netdata-claim.sh` a `tail -1` statement as shown below:

`HTTP_STATUS_CODE=$(grep "HTTP" "${CLAIMING_DIR}/tmpout.txt" | tail -1 | awk -F " " '{print $2}')`

**Comment by stelfrag** [comment]
Hi @robinhuiser 

Thank you for the report and the most helpful analysis!
