### ISSUE TITLE
Netdata erratic effect on DOKS cluster even after delete

### ISSUE THREAD

**Issue by lowercase00** [netdata/netdata#10609]
##### Bug report summary
After deleting every resource on `netdata` namespace, pods still have unusually high resource consumption.
I checked if everything was deleted with:

```
$ kubectl get all -n netdata            
> No resources found in netdata namespace.
```

But my cluster is extremely erratic. there's definitely something wrong with it.
The first annotation is when I installed it - the second when I deleted everything.
No other changes have been made to the cluster.

![Screen Shot 2021-02-06 at 20 05 34](https://user-images.githubusercontent.com/21188280/107131615-c5fd9900-68b6-11eb-942a-9e73a57b1df5.png)

Orange is Prometheus.
This is stacked. It seems that my application has been affected: Flask + Redis + RabbitMQ + Celery.
Already restarted every single deployment a few times, no results.

##### OS / Environment
This was installed with the 1-Click App in DigitalOcean Marketplace to an existing Kubernetes Cluster.
No uninstall command provided.

##### Netdata version
1.28.0

**Comment by ilyam8** [comment]
Hi @lowercase00 

You said you deleted Netdata

> After deleting every resource on netdata namespace

But there is `netdata` dimensions on your screenshot (blue one). I see it after 2nd annotation.

**Comment by lowercase00** [comment]
Actually, this is a glitch in Grafana - the value of the series is zero, but it still appears in the chart since some other point in time has a value. I managed to "fix" the cluster by reconstructing all nodes. It might be worth checking if netdata might have any background process running that might provoke this kind of behavior.

**Comment by ilyam8** [comment]
Netdata Agent uses cpu extensively on start during pod/container **initial** discovery and name resolution. It should be up to 30 seconds (depends on the number of the running containers). It shouldn't affect other processes cpu usage.

Since you've figured out that it was _a glitch in Grafana_ im closing the issue.

Keep in mind that you always can check nodes/pods/containers cpu and mem usage using `kubectl top`.
