### ISSUE TITLE
netdata-updater fails tarball checksum validation

### ISSUE THREAD

**Issue by therealgilles** [netdata/netdata#10606]
##### Bug report summary

```SHELL
> # /etc/cron.daily/netdata-updater 
Checking if a newer version of the updater script is available.
Sat 06 Feb 2021 12:53:21 PM PST : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Sat 06 Feb 2021 12:53:21 PM PST : INFO:  Current Version: 00102800000000
Sat 06 Feb 2021 12:53:21 PM PST : INFO:  Latest Version: 00102900000000
grep: sha256sum.txt: No such file or directory
grep: sha256sum.txt: No such file or directory
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
Sat 06 Feb 2021 12:53:22 PM PST : ERROR:  FAILED TO UPDATE NETDATA : Tarball checksum validation failed. Stopping netdata upgrade and leaving tarball in
```

##### OS / Environment
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version
netdata v1.28.0
 
##### Component Name
netdata-updater

##### Steps To Reproduce
Run /etc/cron.daily/netdata-updater.

##### Expected behavior
Expecting the checksum to be validated.

**Comment by therealgilles** [comment]
I do not understand how this is supposed to work:

```SHELL
create_tmp_directory() {
  if [ -n "${NETDATA_TMPDIR_PATH}" ]; then
    TMPDIR="${NETDATA_TMPDIR_PATH}"
  else
    if [ -z "${TMPDIR}" ] || _cannot_use_tmpdir "${TMPDIR}" ; then
      if _cannot_use_tmpdir /tmp ; then
        if _cannot_use_tmpdir "${PWD}" ; then
          echo >&2
          echo >&2 "Unable to find a usable temprorary directory. Please set \$TMPDIR to a path that is both writable and allows execution of files and try again."
          exit 1
        else
          TMPDIR="${PWD}"
        fi
      else
        TMPDIR="/tmp"
      fi
    fi

    mktemp -d -t netdata-updater-XXXXXXXXXX
  fi
}
...
ndtmpdir=$(create_tmp_directory)
```

create_tmp_directory does not return any value.

**Comment by therealgilles** [comment]
Also not understanding this code:

```SHELL
    ndtmpdir=$(create_tmp_directory)
    cd "$ndtmpdir" || exit 1
```

I read bash can only return integer value, see [here](https://stackoverflow.com/questions/3236871/how-to-return-a-string-value-from-a-bash-function).

**Comment by therealgilles** [comment]
I suggested a fix in https://github.com/netdata/netdata/pull/10550#issuecomment-774746167.

**Comment by Ferroin** [comment]
> I do not understand how this is supposed to work:
> 
> ```shell
> create_tmp_directory() {
>   if [ -n "${NETDATA_TMPDIR_PATH}" ]; then
>     TMPDIR="${NETDATA_TMPDIR_PATH}"
>   else
>     if [ -z "${TMPDIR}" ] || _cannot_use_tmpdir "${TMPDIR}" ; then
>       if _cannot_use_tmpdir /tmp ; then
>         if _cannot_use_tmpdir "${PWD}" ; then
>           echo >&2
>           echo >&2 "Unable to find a usable temprorary directory. Please set \$TMPDIR to a path that is both writable and allows execution of files and try again."
>           exit 1
>         else
>           TMPDIR="${PWD}"
>         fi
>       else
>         TMPDIR="/tmp"
>       fi
>     fi
> 
>     mktemp -d -t netdata-updater-XXXXXXXXXX
>   fi
> }
> ...
> ndtmpdir=$(create_tmp_directory)
> ```
> 
> create_tmp_directory does not return any value.

It prints the temporary directory to use, which then gets picked up by the `$()` command substitution and assigned to the `ndtmpdir` variable. This type of construct is the only way in shell script to return a non-integer value from a function without the function itself creating a new environment variable.

You are correct though that the `mktemp` call should be outside of the `if` block here. I’ll have a PR up shortly to fix that.

**Comment by Ferroin** [comment]
Correction, it’s a bit more complicated than moving the `mktemp` call, we need to just print the value of `$NETDATA_TMPDIR_PATH` if it’s set...

Still, nice catch on this one, I’m actually a bit embarrassed that I did not notice it myself despite having recently spent a lot of time working on this code.

**Comment by Ferroin** [comment]
No, NVM, the correct fix here is indeed moving the `mktemp` call out of the `if` block.

**Comment by therealgilles** [comment]
Shells are notoriously bad as programming languages. Which is why a lot of people use python instead nowadays.
If you wanted to make the return value more explicit, you could do the following:

```SHELL
...
    local retval=$(mktemp -d -t netdata-updater-XXXXXXXXXX)
    echo $retval # return value
```

Another wacky solution would be to encode the string as a number, return it, and decode it on the other side.

**Comment by OdysLam** [comment]
Thanks @therealgilles for catching this and contributing a fix. This project could be nowhere as successful without it's contributors. 

If you have any questions, feel free to hop into our [forums](https://community.netdata.cloud) and ask. I will be super happy to help you in your Netdata experience.

Cheers :)
