### ISSUE TITLE
How to close netdata  monitoring?

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#10600]
I wanna to show only a few metrics.

I closed all except the system cpu util.

But I find no way to close Netdata Monitoring( including exporting/exporting prometheus/web/statsd) on the dashboard.

Is there any way?

**Comment by vlvkobal** [comment]
There is no way to disable the whole Netdata Monitoring section, but you can disable every chart separately. For example:
```
[netdata.exporting_main_thread_cpu]
	enabled = no
```

**Comment by OdysLam** [comment]
Hey @oleotiger,

We have moved our support efforts over at https://community.netdata.cloud! If you have any question, please use our forums and our vibrant community will help you out!.

Thanks @vlvkobal for replying. Closing the issue to continue over the forums :)
