### ISSUE TITLE
Metrics lost for last 10-15 minutes after restart

### ISSUE THREAD

**Issue by aldem** [netdata/netdata#10611]
##### Bug report summary

When restarting netdata (static build for linux-x64) the I see that metrics for ca. 10 minutes before restart are lost:

![image](https://user-images.githubusercontent.com/754722/107135538-de43d700-68fb-11eb-9c09-9582e49b4d39.png)

In this particular case I restarted it at 4:17:40 - but the "hole" is around 10 minutes, and all metrics are affected - not only CPU.

I restarted it again at ca. 4:34 and didn't see any metrics since 4:06:

![image](https://user-images.githubusercontent.com/754722/107135802-16e4b000-68fe-11eb-98a2-b78e8866fbab.png)

And there is an additional short hole after:

![image](https://user-images.githubusercontent.com/754722/107135814-367bd880-68fe-11eb-8bf9-3e18ce207751.png)

##### OS / Environment

Debian 10 and Ubuntu 20.04

##### Netdata version

netdata v1.29.0

##### Component Name

netdata

##### Steps To Reproduce

1. Start netdata and let it run for few minutes
2. Restart

My configuration:
```
[global]
        history = 777600
        memory mode = dbengine
        timezone = CET
        dbengine disk space = 2048
        dbengine multihost disk space = 2048
        page cache size = 256
        access log = none

[plugins]
        enable running new plugins = no
        tc = no
        apps = yes
```

##### Expected behavior

Metrics are expected to be saved on restart/shutdown.

In previous versions (before 1.29) restart caused only few seconds of lost metrics.

**Comment by mfundul** [comment]
Can you share your `var/log/netdata/error.log` around the time of the restart?

**Comment by aldem** [comment]
Sure. Though I could not find anything unusual and as I could reproduce it in at least two different systems with different configurations I doubt this is something specific to my install.

[netdata-error.log](https://github.com/netdata/netdata/files/5938493/netdata-error.log)

**Comment by ilyam8** [comment]
What i did:
 - removed old netdata (installed from source)
 - installed v1.29.0 using [netdata-v1.29.0.gz.run](https://github.com/netdata/netdata/releases/download/v1.29.0/netdata-v1.29.0.gz.run) (default configuration)
 - waited for several minutes, checked the dashboard

<img width="1135" alt="Screenshot 2021-02-08 at 13 06 20" src="https://user-images.githubusercontent.com/22274335/107205144-8fd32d00-6a0e-11eb-909f-4b3795aed271.png">

- restarted netdata service (sudo systemctl restart netdata) and checked the dashboard again

I see no gaps, but all metrics got lost

<img width="1135" alt="Screenshot 2021-02-08 at 13 06 55" src="https://user-images.githubusercontent.com/22274335/107205253-b42f0980-6a0e-11eb-95fb-aa3eba614771.png">


Memory mode settings

```cmd
[ilyam@pc ~]$ curl -s http://127.0.0.1:19999/netdata.conf | grep "memory mode"
	# memory mode = dbengine
	# private charts memory mode = dbengine
```

**Comment by mfundul** [comment]
It appears it has to do with the cgroups plugin @vlvkobal
![image](https://user-images.githubusercontent.com/44345837/107226246-894eb080-6a22-11eb-829c-68fa8a522178.png)

This was reproduced in Alpine 3.12. It probably has to do with musl libC.
