### ISSUE TITLE
http://<parent>/host/<child> (without a trailing /) is broken

### ISSUE THREAD

**Issue by kousu** [netdata/netdata#10626]
##### Bug report summary

Going to a child node's page and forgetting the final / breaks the page.

Works: ![2021-02-14-042937_1366x768_scrot](https://user-images.githubusercontent.com/987487/107873130-042e2600-6e7e-11eb-8b78-daa667e53f04.png)

Fails: ![2021-02-14-042608_1009x643_scrot](https://user-images.githubusercontent.com/987487/107873129-03958f80-6e7e-11eb-83e5-2911a67b533d.png)

##### OS / Environment

```
Linux monitor.neuro.polymtl.ca 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

netdata v1.19.0

 

##### Component Name

web

##### Steps To Reproduce

1. Follow https://learn.netdata.cloud/docs/agent/streaming#database-replication to set up a parent/child stream
2. Go to http://parent:19999/host/child

##### Expected behavior

I should see the dashboards. Maybe a 301 to the page with the / on the end.

**Comment by ilyam8** [comment]
Hi @kousu 👋 Thx for reporting the issue.

However

> netdata v1.19.0

v1.19.0 is quite old 

> released this on 28 Nov 2019

Latest is [v1.29.1](https://github.com/netdata/netdata/releases/tag/v1.29.1)


I'm closing this issue due to the old netdata version. Please update to the latest.
