### ISSUE TITLE
LISTENER: IPv4 bind() port 19999, socktype 1 failed

### ISSUE THREAD

**Issue by didli** [netdata/netdata#10639]
Fedora 32 x64 cinnamon
Linux 5.10.15-100.fc32.x86_64
netdata Version : 1.29.0

I'm running netdata through https://blablabla:19999 with a valid ssl certificate.   

Recently, netdata won't start anymore, with this log : 
```sh
LISTENER: IPv4 bind() on ip 'blablabla' port 19999, socktype 1 failed.
LISTENER: Cannot bind to ip 'blablabla', port 19999
```

There's only one instance running :
```sh
netdata    21758  1.1  0.5 374032 86884 ?        Ssl  15:10   0:03 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D
netdata    21776  0.0  0.0  30400  6836 ?        Sl   15:10   0:00  \_ /usr/sbin/netdata --special-spawn-server
netdata    21896  0.0  0.0  13116  3352 ?        S    15:10   0:00  \_ /usr/bin/bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata    21904  2.0  0.0  73804  9700 ?        S    15:10   0:07  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
netdata    21906  0.0  0.1 724200 22828 ?        Sl   15:10   0:00  \_ /usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata    21908  0.4  0.0  28604  9072 ?        S    15:10   0:01  \_ /usr/libexec/netdata/plugins.d/cups.plugin 1
netdata    21910  0.5  0.3 1044864 49216 ?       Sl   15:10   0:01  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata    21913  0.0  0.0   2580   864 ?        S    15:10   0:00  \_ /usr/libexec/netdata/plugins.d/nfacct.plugin 1
```

... but netstat shows this :
```sh
tcp        0      0 192.168.1.112:19999     0.0.0.0:*               LISTEN      956        1954243    21758/netdata       
tcp        0      0 127.0.0.1:19999         0.0.0.0:*               LISTEN      956        1954242    21758/netdata
```
Is this related to my problem please ?

Note : if i comment the line 'bind to = localhost' in /etc/netdata/netdata.conf, things seems to be a bit better (no more "cannot bind port 19999" in systemctl status netdata) but the netdata dashboard is still not showing up either way ...

**Comment by MrZammler** [comment]
Hi didli!

It seems that "something" is using the port, and netdata can't bind to it...

If you completely stop netdata, does netstat show anything bound to 19999 then ? (either for localhost or the real ip) ?

The same issue has also been mentioned in our [Netdata community forum](https://community.netdata.cloud/), so there might be some more info there (e.g. https://community.netdata.cloud/t/unable-to-start-netdata-service/535).

**Comment by didli** [comment]
Hi ! netstat shows that nothing is bind to port 19999 when netdata is stopped.

**Comment by didli** [comment]
hmm... i've found the issue, but I'm not too sure about the proper way to solve this :
It seems the latest netdata update in Fedora change the netdata.conf file. I can get netdata running again if i put back the old conf file. Now the problem is that there's quite the difference with the update between these two conf files... It seems merging these differences is going to be a pain.

**Comment by MrZammler** [comment]
Glad you traced it down!

Indeed, configuration files changes between versions can be a problem. So, I will close this, if you need any help with the conf file, do visit the [Netdata community forum](https://community.netdata.cloud/) for more help.

Thanks!
