### ISSUE TITLE
Sendmail in Docker image fails

### ISSUE THREAD

**Issue by flexo3001** [netdata/netdata#10630]
##### Bug report summary
When configuring netdata to send emails with `EMAIL_SENDER="netdata <netdata@foo.bar>"` it fails in `alarm-notify.sh` because the sendmail inside the image does not support the **-F** option https://github.com/netdata/netdata/blob/fa9e0b95ebb69cd53643618af7950a7db1cff6fb/health/notifications/alarm-notify.sh.in#L858.

The exact error:
```
2021-02-14 15:41:03: alarm-notify.sh: ERROR: failed to send email notification for: ebola9 test.chart.test_alarm is WARNING to 'root' with error code 1.
# FAILED

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
/usr/sbin/sendmail: unrecognized option: F
BusyBox v1.31.1 () multi-call binary.

Usage: sendmail [-tv] [-f SENDER] [-amLOGIN 4<user_pass.txt | -auUSER -apPASS]
		[-w SECS] [-H 'PROG ARGS' | -S HOST] [RECIPIENT_EMAIL]...

Read email from stdin and send it

Standard options:
	-t		Read additional recipients from message body
	-f SENDER	For use in MAIL FROM:<sender>. Can be empty string
			Default: -auUSER, or username of current UID
	-o OPTIONS	Various options. -oi implied, others are ignored
	-i		-oi synonym, implied and ignored

Busybox specific options:
	-v		Verbose
	-w SECS		Network timeout
	-H 'PROG ARGS'	Run connection helper. Examples:
		openssl s_client -quiet -tls1 -starttls smtp -connect smtp.gmail.com:25
		openssl s_client -quiet -tls1 -connect smtp.gmail.com:465
			$SMTP_ANTISPAM_DELAY: seconds to wait after helper connect
	-S HOST[:PORT]	Server (default $SMTPHOST or 127.0.0.1)
	-amLOGIN	Log in using AUTH LOGIN
	-amPLAIN	or AUTH PLAIN
			(-amCRAM-MD5 not supported)
	-auUSER		Username for AUTH
	-apPASS 	Password for AUTH

If no -a options are given, authentication is not done.
If -amLOGIN is given but no -au/-ap, user/password is read from fd #4.
Other options are silently ignored; -oi is implied.
Use makemime to create emails with attachments.
```

**Comment by ilyam8** [comment]
Thx for reporting @flexo3001 !

**Comment by flexo3001** [comment]
@ilyam8 thank you fixing it that fast!

**Comment by bv-ritesh** [comment]
@mrckndt can you share the steps we need to follow to send email notifications from docker image?

**Comment by Ferroin** [comment]
> @mrckndt can you share the steps we need to follow to send email notifications from docker image?

The primary requirement is to provide a suitable `/etc/msmtprc` and `/etc/aliases` for your setup. Assuming you don’t have any special requirements for how mail is routed and are just using the default alert configuration for Netdata, this consists of a trivial alias file mapping `root` (and, for debugging reasons, `postmaster` and `MAILER-DAEMON`) to the email address you want to receive the notifications, and a minimal msmtp configuration to relay the mail to an actual mailserver.

The Arch Linux wiki has a rather nice page about msmtp that covers the basics of configuration [here](https://wiki.archlinux.org/title/Msmtp) (note that the Docker image already includes msmtp with the required links set up to be used by Netdata for email notifications, so you can skip the installation info), and the full documentation for msmtp can be found [here](https://marlam.de/msmtp/msmtp.html).

**Comment by bv-ritesh** [comment]
@mrckndt thank you for your help.
I was able to configure netdata alarms in the following manner.
1. update /etc/msmtprc with correct details 
2. updating the sendmail="/usr/bin/msmtp" in health_alarm_notify.sh

Again thank you.
