### ISSUE TITLE
netdata: feature: network: iface status params

### ISSUE THREAD

**Issue by k0ste** [netdata/netdata#10638]
Inspired by #10628.

For ifaces we need to know about:

`/sys/class/net/${iface}/`:
- `mtu`
- `speed`
- `carrier`
- `lower_${parent}`
- `operstate`

If interface return invalid argument, for example for 'gre' interfaces, netdata should ignore this, or we need some white-list for iftypes.

**Comment by OdysLam** [comment]
Hey k0ste,

Thanks for the feature request. I will open a topic in our community forum (https://community.netdata.cloud) in the Feature Requests category. Again, welcome to our little community :)
