### ISSUE TITLE
If I want to watch the number of TCP connections and file descriptors for POD not  node's, how should i do?

### ISSUE THREAD

**Issue by zixingkong** [netdata/netdata#10658]
##### OS / Environment

```

```

##### Steps To Reproduce

1. ...
2. ...

**Comment by ilyam8** [comment]
Hi @zixingkong

> number of TCP connections and file descriptors for POD

It is not currently possible, but that is a very nice thing to have, indeed. However,implementation wise it is very tricky, if even possible.

If you want to discuss it further, i suggest to use our [Community forum](https://community.netdata.cloud/). Thanks for using Netdata!

**Comment by OdysLam** [comment]
@zixingkong,

We would love you to submit a feature request and explain why you would like this implemented. The more information you give us, the.  best we will be able to assess the work/value and prioritize it accordingly.
