### ISSUE TITLE
Changes on ebpf.plugin

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#10679]
Netdata is bringing new  ebpf collectors and this requires few changes for ebpf.plugin:

1 - It needs to load different eBPF programs, right now it is only loading `kprobes`.
2 - The new collectors will have charts integrated with `apps.plugin` and we will need to simplify this integration.
3 - Right now we are only creating charts on `ebpf` and `apps` submenu, but ideally data related to hard disk should go to disk, data related to memory should go to mem, and so on. To fix this, it is necessary pass `contexts` as arguments for few functions.

**Comment by ilyam8** [comment]
> To fix this, it is necessary pass contexts as arguments for few functions.

**Comment by thiagoftsm** [comment]
> Could you elaborate why? Just curiousity, why do you need the context to _to fix this_ (data related to hard disk should go to disk, data related to memory should go to mem).

Yes, when we create a chart for hard disks inside computer it is more easy to use `contexts` to define chart description instead the chart name.  No less important the `ebpf` charts are always using default contexts, this will also give freedom for us to create specific contexts.

**Comment by ilyam8** [comment]
[important] Treat context as a metric name [/important]. So it is not a chart description.

> ebpf charts are always using default contexts

What is default context? 🤔

**Comment by thiagoftsm** [comment]
> What is default context? thinking

The  chart id:

```
"ebpf.inbound_packets": 		{
			"id": "ebpf.inbound_packets",
			"name": "ebpf.inbound_packets",
			"type": "ebpf",
			"family": "Network connections",
			"context": "ebpf.inbound_packets",
}
```
