### ISSUE TITLE
netdata: net: interface state: prometheus: used old metrics format

### ISSUE THREAD

**Issue by k0ste** [netdata/netdata#10671]
Currently we can't alert, like `interface {{ $labels.family }} on {{ $labels.instance }} is down`, because metrics use old prometheus format:

```python
netdata_net_bond0_operstate{instance="netdata"}
netdata_net_eth0_operstate{instance="netdata"}
netdata_net_vlan445_operstate{instance="netdata"}
netdata_net_tap1_operstate{instance="netdata"}
netdata_net_eth0_nic_speed_max{instance="netdata"}
```
should be:
```python
netdata_net_interface_operstate{instance="netdata", family="bond0"}
netdata_net_interface_operstate{instance="netdata", family="eth0"}
netdata_net_interface_operstate{instance="netdata", family="vlan445"}
netdata_net_interface_operstate{instance="netdata", family="tap1"}
netdata_net_interface_operstate{instance="netdata", family="eth0"}
```

**Comment by ilyam8** [comment]
We discussed it with @vlvkobal 

Mapping charts into metrics (yes, there is no metrics, but only charts) is tricky.

During charts=>prometheus metrics conversion we use the chart context as a metric name. It means that we shouldn't put any variables in the chart that doesn't belong to that metric.

Having operstate, mtu, speed, etc. in the `net.net` (context, read it as `net.bandwidth`) chart is wrong, they are different metrics.

I think we need to create a separate chart (likely hidden) for every metric and remove them from the `net.net` chart.

**Comment by vlvkobal** [comment]
The plan is to delete `duplex` and `operstate` variables. We can't delete `speed_max` because it is used in alarm calculations. We'll create charts `net_speed`, `net_duplex`, `net_operstate`. We should add `interface` to the context.
