### ISSUE TITLE
General Protection Fault

### ISSUE THREAD

**Issue by gaia** [netdata/netdata#10677]
Current nightly on Debian 10, I see this in the console

![image](https://user-images.githubusercontent.com/87547/108883846-c7b7a400-75ba-11eb-9f25-e2f3e2c3ec3a.png)

Is this not to be concerned about, or do you want logs and conf? thanks guys!

**Comment by thiagoftsm** [comment]
Hello @gaia ,

What is your Netdata version? We released few hours ago a new Netdata, it is possible this problem was fixed.

Best regards!

**Comment by gaia** [comment]
`v1.29.2-25-nightly`. i will update and re-open if i see this again. thanks thiago.

**Comment by thiagoftsm** [comment]
> `v1.29.2-25-nightly`. it says it is the latest, but on github it says 1.29.3
> 
> ![image](https://user-images.githubusercontent.com/87547/108904627-95667080-75d3-11eb-8643-00c179bb469e.png)

@Ferroin is your `kickstart` script with problem?

**Comment by ilyam8** [comment]
```cmd
0 ~ $ curl -s https://storage.googleapis.com/netdata-nightlies/latest-version.txt
v1.29.2-25-nightly
```

Need to wait a bit to get latest updated, there is always some delay after release

**Comment by gaia** [comment]
either way, it is unlikely that this bug was introduced in v1.29.2-25 and fixed in v1.29.3.x...

**Comment by gaia** [comment]
```
Feb 23 00:33:19 box kernel: [ 8111.192904] EBPF PROCESS[5346]: segfault at 7f0753018c30 ip 000055f1e3c59de0 sp 00007f07540c4bd0 error 4 in ebpf.plugin[55f1e3c4f000+2f000]
Feb 23 01:35:36 box kernel: [11848.277841] PLUGIN[proc][28693]: segfault at 18 ip 000055e996ffd08f sp 00007ff1847bca80 error 4 in netdata[55e996ec3000+1fc000]
Feb 23 02:38:05 box kernel: [15597.623737] traps: PLUGIN[proc][3608] general protection fault ip:5601a402e084 sp:7f16b05a5a80 error:0 in netdata[5601a3ef4000+1fc000]
Feb 23 04:50:10 box kernel: [23522.797771] PLUGIN[proc][21052]: segfault at 60350c6f ip 00005601fc382084 sp 00007f00681d2a80 error 4 in netdata[5601fc248000+1fc000]
Feb 23 05:52:38 box kernel: [27270.623080] traps: PLUGIN[proc][9705] general protection fault ip:563b676c008f sp:7f99188b9a80 error:0 in netdata[563b67586000+1fc000]
```

**Comment by vlvkobal** [comment]
Could you [install Netdata from sources](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual) using `sudo CFLAGS="-O0 -ggdb -fsanitize=address -fno-omit-frame-pointer" ./netdata-installer.sh`? You'll get a backtrace in `error.log` on crash.

You may need to install `libasan5` before compiling with `-fsanitize=address`.

**Comment by Ferroin** [comment]
@thiagoftsm Nope, there0s no bug in the kickstart script or the updater. The first nightly after v1.29.3 had not happened yet, and the nightly release channel doesn’t include stable versions when deciding whether to update or not.

Aside from that, there’s also a window of about an hour after the nightly is published before updates to it work reliably.

**Comment by thiagoftsm** [comment]
> @thiagoftsm Nope, there0s no bug in the kickstart script or the updater. The first nightly after v1.29.3 had not happened yet, and the nightly release channel doesn’t include stable versions when deciding whether to update or not.
> 
> Aside from that, there’s also a window of about an hour after the nightly is published before updates to it work reliably.

Thank you for the explaination!

**Comment by gaia** [comment]
so should i try to install again or should i use the flags to catch a backtrace?

**Comment by stelfrag** [comment]
Hi @gaia 

Do you still experience this issue?

**Comment by gaia** [comment]
> Hi @gaia
> 
> Do you still experience this issue?

thanks for checking in Stelios. it is gone now.
