### ISSUE TITLE
health: make alarms less sensitive, tune severity levels

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#10687]
The idea is to make our default alerts less noisy and more useful.

Having too sensitive alarms, ironically, backfires us - people stop paying attention to them (even disabling _health_ completely 😅).

Current problems:
 - focus on edge cases, not on general (~better safe then sorry). Nice in theory, but not that nice in practice.
 - using `crit` level a lot. `crit` (red!) means something really bad. Even if it doesn't suppose to mean it you implicitly treat it like that.
 - lack of `notice` level, pretty often we use `warn` just to show that there is something thay **might be** no normal.

**Comment by thiagoftsm** [comment]
To complement this issue, I already saw problems with the following alarms:

| Alarm | interval of time it was running | Number of alarms received |
|--------- | ----------------------------------- | ------------------------------------|
|disk_util.sda.10min_disk_utilization | Between 8:17 PM and 8:26 PM | 108|
|ipv4.udperrors.1m_ipv4_udp_receive_buffer_errors| Between 11:47:30 PM and 11:48:25 PM | 12|

**Comment by ilyam8** [comment]
> disk_util.sda.10min_disk_utilization | Between 8:17 PM and 8:26 PM | 108

The alarms

https://github.com/netdata/netdata/blob/2bddc7a0f4ad406bf45f526a853b3d025839bc3b/health/health.d/disks.conf#L131-L143

I wonder how it is possible to get 108 alarms 🤔 I see there is 15 minutes delay down 🤔

**Comment by thiagoftsm** [comment]
> I wonder how it is possible to get 108 alarms thinking I see there is 15 minutes delay down thinking

It was really strange, but this happened, I will generate them again when a kernel compilation finishes, and I will also get the dashboard snapshot for each one of them.

**Comment by thiagoftsm** [comment]
I am compiling a kernel with the commands `make -j4 bzImage && make -j4 modules && make -j4 modules_install`, during this time I received more than 200 alarms, and [this](https://github.com/netdata/netdata/files/6044984/cpu.zip) is the computer snapshot .

**Comment by thiagoftsm** [comment]
I ran one more time a script that drops 6096 tables in PostgreSQL 12.4 and recreate them when the drop process is finalized. This time I had only `96`  alarms instead `108` alarms. The period of time that the SQL script ran was 11:08 PM -> 11:16 PM. The snapshot of the dashboard is [here](https://github.com/netdata/netdata/files/6046315/disk.zip).

[top](https://github.com/netdata/netdata/issues/10687#issuecomment-785998630)

**Comment by thiagoftsm** [comment]
For this alarm, I can say it was something completely unexpected, because I was only testing TCP connections, so I do not have conditions to recreate it.

[top](https://github.com/netdata/netdata/issues/10687#issuecomment-785998630)
