### ISSUE TITLE
PagerDuty V2 API not sending warning alarms, only critial

### ISSUE THREAD

**Issue by slamanna212** [netdata/netdata#10685]
##### Bug report summary
Warning alarms such as low entropy, tcp handshake, Requests By Type (web_log_nginx.requests_by_type), are not triggering pagerduty alarms. Critical alarms are working, warning ones are not. I checked the health_alarm_notify.conf, I have my API key and it works and the test alarms appeared and were cleared. I also checked the roles and all of them are set to the default. 

##### OS / Environment

```
Linux Bene-NYC-CC01v 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

```

##### Steps To Reproduce

1. ...
2. ...

##### Expected behavior

Pagerduty should get warning and critical alarms.

**Comment by ilyam8** [comment]
Hi @slamanna212 

We log info/error messages when sending notifications to pagerduty

https://github.com/netdata/netdata/blob/bbcfd952f8ade178e2e17202cd9dfbd2e8f569de/health/notifications/alarm-notify.sh.in#L1097-L1103


Check netdata error.log

> grep "pagerduty notification" error.log

**Comment by ilyam8** [comment]
Closing due to no response.
