### ISSUE TITLE
ERROR 405: Cannot download charts index from server: http://xxx:19999/api/v1/charts

### ISSUE THREAD

**Issue by osxhu** [netdata/netdata#10694]
访问netdata错误
ERROR 405: Cannot download charts index from server: http://192.168.100.136:19999/api/v1/charts
##### Bug report summary

I have been running the netdata v1.28 nigthy version for a while, using the install.sh script command to install,
I found ERROR 405 during my visit today. I first executed the uninstall.sh script. After reinstalling the latest version using the curl kickstart.sh script, the problem persists. After searching for the error, use the tail -f /var/log/netdata/*.log command to proceed. Check, there is still no error log after executing 5mini, so we ask for the help of technical experts, thank you.
##### OS / Environment
System vesion:Centos 7.9
Software version：netdata v1.29.3-24-nightly
##### log infomation

[log.txt](https://github.com/netdata/netdata/files/6048458/log.txt)

##### charts index  infomation（open"http://192.168.100.136:19999/api/v1/charts"）
[index.txt](https://github.com/netdata/netdata/files/6048465/index.txt)

**Comment by ilyam8** [comment]
Hi @osxhu 

The problem is `net.enp0s29u1u1u5` operstate chart variables value, it is `nan`, it makes json invalid.

```cmd
		"net.enp0s29u1u1u5": 		{
			"id": "net.enp0s29u1u1u5",
			"name": "net.enp0s29u1u1u5",
			"type": "net",
			"family": "enp0s29u1u1u5",
			"context": "net.net",
			"title": "Bandwidth (net.enp0s29u1u1u5)",
			"dimensions": {
				"received": { "name": "received" },
				"sent": { "name": "sent" }
			},
			"chart_variables": {
		"duplex": null,
		"operstate": nan,
		"nic_speed_max": null
			},
			"green": null,
			"red": null,
```

**Comment by osxhu** [comment]
Thank you for your reply. Do I need to modify the network card-related values in the configuration file? Please help indicate the location of the modification! Many thanks

**Comment by ilyam8** [comment]
Could you show

> cat /sys/class/net/enp0s29u1u1u5/operstate

**Comment by osxhu** [comment]
![image](https://user-images.githubusercontent.com/18412762/109283665-06b75500-785a-11eb-827e-4667f871f00c.png)

**Comment by ilyam8** [comment]
Temporary fix is to disable monitoring `enp0s29u1u1u5`

in the netdata.conf

```cmd
[plugin:proc:/proc/net/dev:enp0s29u1u1u5]
        enabled = no
        # virtual = no
```

**Comment by osxhu** [comment]
As the solution you gave, I disabled the network card setting in the corresponding position in netdata.conf, but the error persisted. Use netdata -info to get the following information, please check it, I hope it will be helpful to solve this problem!

### **##### Print netadta -info**
[root@libraryserver netdata]# netdata -info
2021-02-26 18:16:32: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2021-02-26 18:16:32: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
2021-02-26 18:16:33: netdata ERROR : MAIN : LISTENER: getaddrinfo('nfo', '19999'): Name or service not known
 (errno 2, No such file or directory)
2021-02-26 18:16:33: netdata FATAL : netdata : LISTENER: Cannot listen on any API socket. Exiting... # : Success

2021-02-26 18:16:33: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2021-02-26 18:16:33: netdata INFO  : MAIN : EXIT: cleaning up the database...
2021-02-26 18:16:33: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
2021-02-26 18:16:33: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...

**Comment by ilyam8** [comment]
Looks like somehow it is possible to bypass `isnan` condition in the fucntion ?

https://github.com/netdata/netdata/blob/5a14cdbe68892c116f59859690d778d516c468a8/database/rrdvar.c#L254-L269

@mfundul @stelfrag @underhood any ideas?

**Comment by vlvkobal** [comment]
Have you compiled Netdata from sources or installed it using `kickstart-static64.sh`?

**Comment by osxhu** [comment]
> Have you compiled Netdata from sources or installed it using `kickstart-static64.sh`?
Yes,I confirm use "kickstart-static64.sh"shell install this program.And success.

**Comment by vlvkobal** [comment]
Could you [install Netdata from sources](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual)? Don't forget to [uninstall](https://learn.netdata.cloud/docs/agent/packaging/installer/uninstall) it first.

**Comment by osxhu** [comment]
The first time is to uninstall the uninstall script
Then reinstalled, as follows:
1. ./netdata-uninstaller.sh --force -y
2. bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)  --all

**Comment by osxhu** [comment]
I tried to uninstall and reinstall according to the official documentation. Check the records of the installation process for any problems. When I visit the 19999 webpage, I still get a 405 error.
[process_log.txt](https://github.com/netdata/netdata/files/6049282/process_log.txt)

**Comment by osxhu** [comment]
![Uploading image.png…]()

**Comment by osxhu** [comment]
![image](https://user-images.githubusercontent.com/18412762/109294785-9c59e100-7868-11eb-93b9-41a6d5313e95.png)

**Comment by ilyam8** [comment]
@osxhu looks like reinstall doesn't help and you are having same problem

You can check if there are some `nan`'s 

> curl -s http://127.0.0.1:19999/api/v1/charts | grep ": nan"

**Comment by stelfrag** [comment]
I can't reproduce this

**Comment by ilyam8** [comment]
Same problem https://community.netdata.cloud/t/centos-7-yum-install-netdata-but-error-405/985/5 but with `apps.files` chart.

**Comment by vlvkobal** [comment]
@stelfrag have you tried it on CentOS 7.9? Did you install Netdata using the kickstart script or from sources?

**Comment by stelfrag** [comment]
> @stelfrag have you tried it on CentOS 7.9? Did you install Netdata using the kickstart script or from sources?

No its not the exact 7.9 version -- was via kickstart 

@MrZammler did you try on 7.9?

**Comment by MrZammler** [comment]
Yes, I tried the `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` method on a clean Centos 7.9 (CentOS Linux release 7.9.2009 (Core)) setup. Couldn't reproduce it...

I tried feeding garbage to operstate via `path to get net device operstate` pointing to a random (or in same cases non-existant) file... The code seems to handle every case and defaults to 0...

I will also try to install with `bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --all` and let you know.

**Comment by osxhu** [comment]
> @osxhu looks like reinstall doesn't help and you are having same problem
> 
> You can check if there are some `nan`'s
> 
> ```shell
> # ssh to the server with netdata
> curl -s http://127.0.0.1:19999/api/v1/charts | grep ": nan"
> 
> # OR from the remote server
> curl -s http://192.168.100.136:19999/api/v1/charts | grep ": nan"
> ```

![image](https://user-images.githubusercontent.com/18412762/109627002-22816a80-7b7c-11eb-9f56-75bf7ba6340d.png)

**Comment by osxhu** [comment]
After completely uninstalling today, according to the previous installation method, after the installation, the indicators can be normally obtained and used, and the web page language has been successfully Chineseized.
Installation steps:
1.yum install zlib-devel gcc make git autoconf autogen automake pkgconfig
2.git clone https://github.com/netdata/netdata.git --depth=100
3.cd netdata
4../netdata-installer.sh
