### ISSUE TITLE
Sort legends by usage

### ISSUE THREAD

**Issue by fitzg2** [netdata/netdata#10715]
##### Bug report summary
It would be nice if while hovering the graphs the legends on the right would be sorted from high to low. Otherwise you can't click on a certain timeline and scroll down a long list of legends to see the actual perpetrator. Or.. allow to lock in at X time frame.

##### OS / Environment
Not needed

##### Netdata version
netdata v1.29.0

##### Component Name
Dashboard

##### Steps To Reproduce
1. For a long enough legend list you can't scroll down while hovering a graph

##### Expected behavior
1. sort legends by use
or
2. allow to lock at certain timeframe so as to allow to browse the list of legends

**Comment by OdysLam** [comment]
Hey @fitzg2,

Thanks for this bug report. Can you please share a screenshot?

**Comment by ilyam8** [comment]
This issue is a feature request, duplicate of https://github.com/netdata/netdata/issues/1566

**Comment by fitzg2** [comment]
Nevermind. Expanding the list kind of solves it. If the developers don't want to sacrifice speed for this ''feature'' then it can be done on click. Am happy expanding the list. Closing.
