### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED anomalies.chart.py

### ISSUE THREAD

**Issue by nclsclsn** [netdata/netdata#10724]
##### Bug report summary
I enabled the anomalies collector according to https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/anomalies.
After restarting the agent I got this syntax error:
2021-03-08 17:29:46: python.d WARNING: plugin[main] : anomalies[local] : unhandled exception on init : SSLError(MaxRetryError("HTTPSConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/charts (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))",),), skipping the job

##### OS / Environment

```
Linux sandbox.local.arcticlake.com 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

##### Netdata version

 Netdata v1.29.3

##### Component Name

Anomalies Collector

##### Steps To Reproduce

1. Secure netdata with self-signed certificate
2. Enable anomalies collector

##### Expected behavior

Provide configuration to verify self-signed certificate or option to skip TLS verification

**Comment by andrewm4894** [comment]
Thanks @nclsclsn - i'll look into this and see what best option might be. 

If you have any, we'd love you hear any feedback from using the anomalies collector for a bit in [the community thread here](https://community.netdata.cloud/t/anomalies-collector-feedback-megathread/767).

In regard to this issue i think we need to make available the `verify` option in [requests](https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification) calls that [`netdata-pandas`](https://github.com/netdata/netdata-pandas) makes and likewise for the async requests `asks` makes when getting the data from the netdata REST API.

**Comment by andrewm4894** [comment]
Another option, if you have the time and inclination and a dev type machine you can try this out on would be to try just install from my branch and see if the changes work. 

```
## Install netdata from branch

# prepare
sudo apt-get update
sudo apt-get install python3-pip
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
sudo apt-get update

# install netdata from source
mkdir tmp
sudo curl -Ss 'https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh' > tmp/install-required-packages.sh && bash tmp/install-required-packages.sh --dont-wait -i netdata
sudo curl -Ss 'https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh' > tmp/install-required-packages.sh && bash tmp/install-required-packages.sh --dont-wait -i netdata-all

# clone branch
git clone --branch anomalies-collector-dogfooding-improvements https://github.com/andrewm4894/netdata.git --depth=100

# install from branch
cd netdata
sudo ./netdata-installer.sh --dont-wait

## Set up anomalies collector

# become netdata user
sudo su -s /bin/bash netdata

# install required packages for the netdata user
pip3 install --user netdata-pandas==0.0.38 numba==0.50.1 scikit-learn==0.23.2 pyod==0.8.3

# exit netdata user
exit

# turn on anomalies collector
cd /etc/netdata/
sudo ./edit-config python.d.conf
# Set `anomalies: no` to `anomalies: yes`
# Save changes

# restart netdata
sudo systemctl restart netdata

# wait a few minutes and hopefully you will see "Anomalies local" charts just above "Netdata Monitoring"
```

I've just done this on a dev machine myself to test i have not broken anything and it all still works as expected. 

I just now need to learn how to do your step 1 above "Secure netdata with self-signed certificate" to try re-create something closer to the environment you have.

**Comment by ilyam8** [comment]
Fixed in https://github.com/netdata/netdata/pull/11003
