### ISSUE TITLE
Netdatacli fails to shutdown Netdata Agent on MacOS

### ISSUE THREAD

**Issue by odyslam** [netdata/netdata#10721]
##### OS / Environment

```
macOS Catalina
```

##### Netdata version

v1.29

##### Component Name

netdatacli

##### Steps To Reproduce

The issue is intermittent. Some times it works as expected, some times it will not.

When it does, the first time that it runs it returns no output but the Agent keeps running. Additional execution of the same command will output an error: `Can't open pipe, are you sure that the Netdata Agent is running?`. 

##### Expected behavior

The Netdata Agent is close succesfully.

**Comment by OdysLam** [comment]
Perhaps this is relevant to #10842 @underhood. Linking them all together

**Comment by MrZammler** [comment]
Hi @OdysLam 

Did a few tries here (M1), it seems to work.... (i.e. start, shutdown, start... cycle for 5-6 times in a row). I'm running it as a regular user, compiled from source (not homebrew).

**Comment by OdysLam** [comment]
@MrZammler I used the homebrew version. Does your version work with cloud? When you mean source, you don't mean kickstart.sh, right?

**Comment by MrZammler** [comment]
Yes, it works with cloud after the latest mqtt changes from @underhood . It takes a bit of a hassle, but it builds using `./netdata-installer.sh`. There's more info here: https://github.com/netdata/netdata/pull/11145

I'll try to help @underhood iron out some other build issues. I'm don't use the homebrew version, to avoid various conflicts. If it gets built from source, it should be ok then for homebrew too.

**Comment by OdysLam** [comment]
From an internal slack chat @MrZammler I had with @Ferroin quite some time ago, we deduced that it's probably an issue with how we have hard-coded the pipe. 

The issue appeared in the brew package quite often when I was testing netdata with a statsd plugin. I think that if we solve #7587, this should be solved once and for all as well.

**Comment by Ferroin** [comment]
Given that we have never been able to reliably reproduce this one, and we _think_ it’s fixed now, I’m closing it.
