### ISSUE TITLE
netdata exposes two netdata_info metric after update

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#10729]
##### Bug report summary

we had a few netdata agents with version `1.22.1`, after upgrading them to version `1.29.3` they are exposing two `netdata_info` metrics to the prometheus:
```

netdata_info{application="netdata", instance="server1.compute.x.y.z", job="netdata-central", version="v1.22.1"} 
netdata_info{application="netdata", instance="server1.compute.x.y.z", job="netdata-central", version="v1.29.3"} 
```
These children are streaming to a parent, I also see these instances twice on the `mirrored_hosts` in `/api/v1/info` of the parent
We are using the prebuilt netdata.

##### Netdata version

 child: `1.22.1` updated to `1.29.3`
parent: `1.29.1`

##### Component Name

update

##### Steps To Reproduce

1. update the child using update script

**Comment by stelfrag** [comment]
Hi @yasharne 

Sorry for the delayed response. Has this been resolved ?

**Comment by yasharne** [comment]
Hi @stelfrag 
Yes, the only solution i found was to uninstall the netdata on the child and re-install it

**Comment by yasharne** [comment]
@stelfrag Reinstalling the netdata is not a good solution, If I should re-install netdata every time I want to update a netdata instance then what is the use-case of the `netdata-updater` script?

**Comment by jouhlmann** [comment]
@stelfrag Looks like the issue still exists, faced it again with auto-update to 1.37 today on most hosts.
