### ISSUE TITLE
Sync monitoring

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#10725]
If the syscall  `sync` is called frequently, this can create performance bottleneck, netdata needs to bring a monitor for this using eBPF plugin.  

This plugin will have one chart demonstrating the frequency that the syscall is called and we will also have an alarm for it.

**Comment by Ferroin** [comment]
If possible, I think it would make more sense to make this as generic as possible and let users pick exactly which syscalls to monitor. `sync()` heavy workloads may matter to some, but for others they may be a complete non-issue.

**Comment by thiagoftsm** [comment]
> If possible, I think it would make more sense to make this as generic as possible and let users pick exactly which syscalls to monitor. `sync()` heavy workloads may matter to some, but for others they may be a complete non-issue.

We can expand this for other syscalls like `syncfs()`, we started with it, because it was what other companies were doing, but I do not have any objection to add other syscalls related to commit filesystem caches to disk. @manos-saratsis do you have objection?

**Comment by Ferroin** [comment]
> > If possible, I think it would make more sense to make this as generic as possible and let users pick exactly which syscalls to monitor. `sync()` heavy workloads may matter to some, but for others they may be a complete non-issue.
> 
> We can expand this for other syscalls like `syncfs()`, we started with it, because it was what other companies were doing, but I do not have any objection to add other syscalls related to commit filesystem caches to disk. @manos-saratsis do you have objection?

There are a bunch of other calls though that are expensive and have a big impact on system performance. Just a short list off the top of my head

* the whole `stat()` family of syscalls
* the whole `fork()` family of syscalls
* most of the namespace related syscalls (`unshare()` in particular is rather expensive).

In an ideal situation, we would have one program per syscall and let users configure which ones to load and therefore which ones to monitor, but that may get out of hand quickly (Linux has well over 200 syscalls right now).

**Comment by thiagoftsm** [comment]
@Ferroin and @ilyam8 thank you for your contribution.

I will continuing moving forward the PR that has `sync`,  I am missing few tests to finish it. For the other `syscalls` suggested [here](https://github.com/netdata/netdata/issues/10725#issuecomment-794000014), I will create a differnt PR separated for them when the `sync` PR is merged.

**Comment by thiagoftsm** [comment]
I already created this [issue](https://github.com/netdata/kernel-collector/issues/205) for we move  forward what we are discussing here, but I have doubts for you (@ilyam8 and @Ferroin ) and for the whole community should we bring only calls for the function? Or will we give a better representation for our users using histograms?

**Comment by Ferroin** [comment]
I think it kind of depends on the syscall itself. For the sync related stuff histograms make sense. Same probably for the `stat()` family.

But some things we might want to monitor (like `unshare()` or `fork()`) probably make more sense as simple rate measurements.

Now that I think of it, it might even make sense to have both a simple rate measurement and histograms for most of the system calls, and just let users choose which of the two (or both) they want to see for any given system call.
