### ISSUE TITLE
NG per cloud request charts

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#10747]
create chart per cloud req. type in NG (this chart is present in ACLK Legacy already)

**Comment by UmanShahzad** [comment]
For reference, here's a full list of charts (in pictures) available for ACLK-legacy currently (in reverse order):

![Screenshot from 2021-07-07 10-38-08](https://user-images.githubusercontent.com/10018065/124712673-0ff7b300-df19-11eb-9c58-6a02cf8c37aa.png)
![Screenshot from 2021-07-07 10-38-03](https://user-images.githubusercontent.com/10018065/124712684-11c17680-df19-11eb-877f-92adc0028e86.png)
![Screenshot from 2021-07-07 10-37-54](https://user-images.githubusercontent.com/10018065/124712687-125a0d00-df19-11eb-95fe-1f13ff462571.png)
![Screenshot from 2021-07-07 10-37-50](https://user-images.githubusercontent.com/10018065/124712690-12f2a380-df19-11eb-9abe-4ee95ee34627.png)
![Screenshot from 2021-07-07 10-37-46](https://user-images.githubusercontent.com/10018065/124712691-138b3a00-df19-11eb-9b7e-2156338eb33e.png)
![Screenshot from 2021-07-07 10-37-38](https://user-images.githubusercontent.com/10018065/124712692-14bc6700-df19-11eb-84ad-0da908892e12.png)
![Screenshot from 2021-07-07 10-37-34](https://user-images.githubusercontent.com/10018065/124712696-1554fd80-df19-11eb-9437-e5312fb7874d.png)
![Screenshot from 2021-07-07 10-37-28](https://user-images.githubusercontent.com/10018065/124712699-16862a80-df19-11eb-8821-e09cde8048ca.png)
![Screenshot from 2021-07-07 10-37-22](https://user-images.githubusercontent.com/10018065/124712703-171ec100-df19-11eb-9e8b-dd50ff1f67d0.png)
![Screenshot from 2021-07-07 10-37-18](https://user-images.githubusercontent.com/10018065/124712706-17b75780-df19-11eb-99c1-e274fc8072e6.png)
![Screenshot from 2021-07-07 10-37-07](https://user-images.githubusercontent.com/10018065/124712708-184fee00-df19-11eb-9ee9-2d2e8b1800fe.png)
![Screenshot from 2021-07-07 10-36-27](https://user-images.githubusercontent.com/10018065/124712712-18e88480-df19-11eb-936c-105fb21ca4f6.png)

**Comment by UmanShahzad** [comment]
Hey @underhood, quick question:

We only want the `netdata.aclk_cloud_req_cmd` chart to be added in this issue. But this is a full list of charts below which are the ones in legacy and not in ng yet (not including `netdata.aclk_cloud_req_cmd` and the ones having to do with libmosquitto<->libwebsockets read/write queues):

- `netdata.aclk_cloud_req_version`
- `netdata.aclk_cloud_q_recvd_to_processed`
- `netdata.aclk_thread0_cpu`, `netdata.aclk_thread1_cpu`, etc.

Do we want to add these in the future too, or maybe as part of this issue?

**Comment by underhood** [comment]
- we will not need mosq<->lws charts as they do not make sense under new ACLK
- we should do the per thread usage charts - feel free to make them separate issue and PR
- netdata.aclk_cloud_q_recvd_to_processed is also good to have (can be separate PR and issue for easier tracking)

**Comment by UmanShahzad** [comment]
@underhood Excellent, thank you, I'll make new issues & PRs for each.

**Comment by UmanShahzad** [comment]
We discussed privately and determined that due to a difference in how things work now between NG & legacy, we will create two charts rather than 1:

- `netdata.aclk_cloud_req_http_type` will show a breakdown of HTTP query types, e.g. `/api/v1/data` vs. `/api/v1/chart` etc.
- `netdata.aclk_cloud_req_type` will show a breakdown at a higher-level, e.g. `http` vs `alarm_update` vs `metadata_alarms` etc. This is based off of the entries found in `aclk/aclk_query.c#aclk_query_handlers`.

**Comment by UmanShahzad** [comment]
Made https://github.com/netdata/netdata/issues/11331 for per-thread CPU usage & https://github.com/netdata/netdata/issues/11332 for `netdata.aclk_cloud_q_recvd_to_processed`.
