### ISSUE TITLE
`unable to send audit message: Operation not permitted` when exec command with sudo

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#10745]
I wanna add my own collector/python plugin to netdata with a microarchitecture metrics collecting tool:[pcm](https://github.com/opcm/pcm).

The code is simple. Here I post the key codes:
```python
# in __init__
self.command = 'sudo -n /path/to/pcm/pcm.x -i=1 -csv'
# rewrite function _get_data to decode raw data.
```

After restart netdata service, I got error message:
```
sudo: unable to change to root gid: Operation not permitted
sudo: unable to initialize policy plugin
```

As mentioned in issue[8535](https://github.com/netdata/netdata/issues/8535#issuecomment-606401520), I tried to add `CapabilityBoundingSet=CAP_SETGID` and `CapabilityBoundingSet=CAP_SETUID` in netdata.service.

Then `systemctl daemon-reload && service netdata restart`.

Error message changed:
```
sudo: unable to send audit message: Operation not permitted.
```

With adding more log here, I can see that pcm error message:
```
Try to execute 'modprobe msr' as root user and then
you also must have read and write permissions for /dev/cpu/*/msr devices (/dev/msr* for Android). The 'chown' command can help.
Access to Processor Counter Monitor has denied (no MSR or PCI CFG space access).
```

I have add netdata to sudoers and set `NOPASSWD`.

I tried:
```
su -s /bin/bash - netdata
/usr/libexec/netdata/plugins.d/python.d.plugin test_cmd debug trace nolock
```
and I can get correct output.

1. How to add tools as python plugin which need root privilege?
2. I think there are lots of tools that need root privilege to run to collect system metrics. Is it better to packaging the method as a public method in `ExecutableService`?

**Comment by ilyam8** [comment]
Hi, you are right general, to get it working you need:

 - add netdata to your `/etc/sudoers`

```cmd
netdata ALL=(root)       NOPASSWD: /path/to/command
```

 - modify netdata systemd unit CapabilityBoundingSet

Here you have 2 options: extend it adding missing capabilities or reset it. Extend can be tricky, because you need to know exact capabilities.

[See how to reset CapabilityBoundingSet](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/adaptec_raid#requirements)

**Comment by oleotiger** [comment]
> Hi, you are right in general, to get it working you need:
> 
> * add netdata to your `/etc/sudoers`
> 
> ```batchfile
> netdata ALL=(root)       NOPASSWD: /path/to/command
> ```
> 
> * modify netdata systemd unit CapabilityBoundingSet
> 
> Here you have 2 options: extend it adding missing capabilities or reset it. Extend can be tricky, because you need to know exact capabilities.
> 
> [See how to reset CapabilityBoundingSet](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/adaptec_raid#requirements)

It works. Thank you.

What about the second question? `I think there are lots of tools that need root privilege to run to collect system metrics. Is it better to packaging the method as a public method in ExecutableService?`.

I think it's better to add a public method or member to indicate whether to execute the command with sudo in ExecuableService.

**Comment by ilyam8** [comment]
Yes, that sounds reasonable.

> It works. Thank you.

Great! (resetting the set doesn't feel good, but guessing what capabilities are needed in every case is frustrating)
