### ISSUE TITLE
Error while installing, /dev/fd/63: line 1: Access: command not found

### ISSUE THREAD

**Issue by kobimx** [netdata/netdata#10744]
##### Bug report summary
I am experienging an error while installing via the one-liner on a new ubuntu server installation. It seems like the URL https://my-netdata.io/kickstart.sh is not accessible and it gives a "Access to file is not permitted: /usr/share/netdata/web/kickstart.sh" error if i open it in a web browser

##### OS / Environment

```
Ubuntu server
```

##### Component Name
Website one liner URL (?)

**Comment by RamboFR05TY** [comment]
Having the same issue and it looks like the Kickstarter script is missing: 
![image](https://user-images.githubusercontent.com/12777352/110544130-e9289c00-8133-11eb-9516-37a97cba01bf.png)

**Comment by kobimx** [comment]
> Having the same issue and it looks like the Kickstarter script is missing:
> ![image](https://user-images.githubusercontent.com/12777352/110544130-e9289c00-8133-11eb-9516-37a97cba01bf.png)

Yeah, somebody done goofed

**Comment by RamboFR05TY** [comment]
I was going in loops trying to figure out what I was doing wrong then I thought it was locked to only allow access from a curl, was close to banging my head but knew I could trust the good old GitHub Issues :P

**Comment by ilyam8** [comment]
Thanks for reporting, guys! We are working on the fix.

**Comment by ilyam8** [comment]
It is fixed 🎉

**Comment by kobimx** [comment]
Thanks guys
