### ISSUE TITLE
Agent MQTT Connections timeout due to KA not received (Production)

### ISSUE THREAD

**Issue by krital** [netdata/netdata#10750]
##### Bug report summary
In our ingestion broker logs (VerneMQ) we see a large number of agent connections being kicked out due to KA not received. The log entries are very frequent and look like this: 

15:31:59.648 [warning] client {[],<<"97db2e90-80c9-11eb-8e97-b1e9895fd031">>} with username <<"97db2e90-80c9-11eb-8e97-b1e9895fd031">> stopped due to keepalive expired
15:33:41.863 [warning] client {[],<<"c2d9b108-3d3e-11eb-981d-d6c25567ad10">>} with username <<"c2d9b108-3d3e-11eb-981d-d6c25567ad10">> stopped due to keepalive expired
15:33:45.591 [warning] client {[],<<"922f49ee-3c69-11eb-88f6-8d60c5a432aa">>} with username <<"922f49ee-3c69-11eb-88f6-8d60c5a432aa">> stopped due to keepalive expired
15:36:15.943 [warning] client {[],<<"d4c37ed0-4ef0-11eb-ac1e-d8d090584889">>} with username <<"d4c37ed0-4ef0-11eb-ac1e-d8d090584889">> stopped due to keepalive expired
15:38:29.638 [warning] client {[],<<"fd185a39-3097-49a2-a379-061cc2691d21">>} with username <<"fd185a39-3097-49a2-a379-061cc2691d21">> stopped due to keepalive expired

##### OS / Environment
Any OS
```

```

##### Netdata version
Unknown so far, presumed to be latest version 1.29.3
 

##### Component Name
ACLK

##### Steps To Reproduce

1. Start a Netdata Agent that is claimed to the cloud
2. Leave idle and see it getting disconnected

##### Expected behavior
According to the MQTT specification, each connection has a KA interval defined. When there is no other activity (nothing published / consumed), the client needs to send a PING packet to the server before the KA interval elapses. The Broker will respond to that keeping the connection alive. If the broker has not heard from a client for 1.5 x KA interval, it closes the connection and produces the above log entry.

**Comment by stelfrag** [comment]
Although this has been observed in 1.29.3 there are a lot of agents in versions 1.26 and 1.25 that cannot be updated. 

A bug that was fixed in https://github.com/netdata/netdata/pull/10401 (which would be version 1.27.0-4 or so) means that all previous versions (about v1.24.0-195 onwards) have an increased probability to "deadlock" after a network loss.

**Comment by krital** [comment]
However in this case it looks like a deadlock that prevents the KA packet to be sent causing the network loss. If you could run an agent with a small KA interval and leave it idle it may get reproduced?

**Comment by underhood** [comment]
for keepalive to be broken ACLK_Main would have to lock. Do the agents reconnect quickly after this issue? If not deadlock is more probable (user would have to restart agent manually?)

**Comment by krital** [comment]
Not sure how to get this information, the vernemq logs only log this when the connection is stopped due to KA expiry and because the username is tha claim id I could get it. I guess we can find out from big query both the agent version and when they reconnected?

**Comment by underhood** [comment]
Not sure as well. Trying to get something to get by. Just by testing keep-alive keep being sent without issue. Therefore there must be something triggering this...

**Comment by krital** [comment]
I have taken the last 10K log entries with Ka expired messages and extracted the distinct claim ids. @cakrit then matched the agent versions and found that even the latest versions / post deadlock fix suffer from the issue. So we need a new plan to investigate further.

**Comment by stelfrag** [comment]
No need to keep this
