### ISSUE TITLE
Netdata monitoring Pihole causes a lot of log lines in pihole.log

### ISSUE THREAD

**Issue by mattpson** [netdata/netdata#10763]
##### Bug report summary

Netdata monitoring Pihole causes a lot of log lines in pihole.log

##### OS / Environment

```
Linux homebase-pi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux
Raspbian GNU/Linux 10 (buster)
```

This is on a Raspberry Pi 3B.

Pihole is: Pi-hole v5.2.4 Web Interface v5.4 FTL v5.7

##### Netdata version

 netdata v1.29.3-125-nightly

##### Component Name

pihole plugin

##### Steps To Reproduce

When Netdata is running on the host the logfile pihole.log quickly fills up with these lines:

```
Mar 13 23:50:39 dnsmasq[4271]: config cachesize.bind is <TXT>
Mar 13 23:50:39 dnsmasq[4271]: config insertions.bind is <TXT>
Mar 13 23:50:39 dnsmasq[4271]: config evictions.bind is <TXT>
Mar 13 23:50:39 dnsmasq[4271]: config hits.bind is <TXT>
Mar 13 23:50:39 dnsmasq[4271]: config misses.bind is <TXT>
Mar 13 23:50:39 dnsmasq[4271]: config auth.bind is <TXT>
Mar 13 23:50:39 dnsmasq[4271]: config servers.bind is <TXT>
```
These lines is repeated every second when Netdata is running. If I stop Netdata the lines doesn't occur and just normal log is produced. This is obviously not ideal on a device that runs from a SD card where writes will wear out the media faster.

I notice that Netdata is querying the Pihole API via HTTP requests to 127.0.0.1 and that these sometimes time out producing 'broken' graphs (other metrics are working fine). According to Pihole developers there is another way to query the API like:

```
$ echo ">cacheinfo >quit" | nc localhost 4711
cache-size: 10000
cache-live-freed: 0
cache-inserted: 822
```

which seems more reliable that constantly querying the HTTP API every second on a limited device like a RPi.
That API is described here: https://docs.pi-hole.net/ftldns/telnet-api/

##### Expected behavior

I expect the logfiles not to fill up with irrelevant items when using Netdata to monitor my Pihole.

**Comment by ilyam8** [comment]
Hi @mattpson 👋 

Same issue https://github.com/netdata/netdata/issues/9642

Query interval (`update_every`) is configurable.

---

>  pihole.log quickly fills up with these lines
> Mar 13 23:50:39 dnsmasq[4271]: config cachesize.bind is <TXT>
> Mar 13 23:50:39 dnsmasq[4271]: config insertions.bind is <TXT>

This looks like [dnsmasq](https://github.com/netdata/go.d.plugin/tree/master/modules/dnsmasq#dnsmasq-dns-forwarder) collector 🤔 

From [man dnsmasq](https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html)

> The cache statistics are also available in the DNS as answers to queries of class CHAOS and type TXT in domain bind. The domain names are cachesize.bind, insertions.bind, evictions.bind, misses.bind, hits.bind, auth.bind and servers.bind.

---

[Telnet-api](https://docs.pi-hole.net/ftldns/telnet-api/) looks good, indeed! We bypass lighttpd using it. We need to check if it provides same metrics as web api (likely it does).

And i guess the problem will be solved when https://github.com/pi-hole/FTL/pull/659 is merged.

**Comment by ilyam8** [comment]
@mattpson simple change is changing `pihole` collector default `update_every` to 5 or 10. Sounds like it would be ok. What do you think?

**Comment by mattpson** [comment]
Been testing with `update_every` set to 3 or 5 and it does log less as expected but the time-outs still happen making the graphs look choppy.  

Getting:

```
[ DEBUG ] pihole[pihole] job.go:170 skip the tick due to previous run hasn't been finished
[ ERROR ] pihole[pihole] collect.go:140 Get "http://127.0.0.1/admin/api.php?getQueryTypes&auth=1234": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[ ERROR ] pihole[pihole] collect.go:131 Get "http://127.0.0.1/admin/api.php?summaryRaw&auth=1234": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[ ERROR ] pihole[pihole] collect.go:158 Get "http://127.0.0.1/admin/api.php?topClients=5&auth=1234": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[ ERROR ] pihole[pihole] collect.go:149 Get "http://127.0.0.1/admin/api.php?getForwardDestinations&auth=1234": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[ ERROR ] pihole[pihole] collect.go:167 Get "http://127.0.0.1/admin/api.php?topItems=5&auth=1234": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
(changed auth for privacy and readability)

I don't see go.d.plugin having any `timeout:` property to tweak?

**Comment by ilyam8** [comment]
@mattpson there is `timeout` configuration option. Increase it 

https://github.com/netdata/go.d.plugin/blob/ddd8ce5ddb013c85fd4777413a0d7ccc0efc6cf5/config/go.d/pihole.conf#L74-L77

All plugins that do http requests have same set of options - https://github.com/netdata/go.d.plugin/tree/master/pkg/web#configuration-options

**Comment by ilyam8** [comment]
@mattpson set both `update_every` and `timeout` to 5 or 10.

**Comment by ilyam8** [comment]
I think using 5 as default for both fo those parameters is ok, we need to change 1=>5 it. @vlvkobal

**Comment by ilyam8** [comment]
> I think using 5 as default for both fo those parameters is ok, we need to change 1=>5 it.

fixed in https://github.com/netdata/go.d.plugin/pull/563
