### ISSUE TITLE
Is it nornal for freeipmi to collect data at so low frequency?

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#10765]
`freeipmi.plugin: data collection speed was 113081523 usec`

I got message as shown above.

conf like 
```
[plugin:freeipmi]
    update every = 5
    command options = debug
```

Is there command options `debug` necessary?

It's almost 2 min for freeipmi to collect data once. I think it takes 5~10 seconds at most to collect the metrics at one time point.

What's more, after enable freeipmi it takes about 10mins for ipmi chart to show on dashboard.

Is it normal?

**Comment by vlvkobal** [comment]
> Is there command options debug necessary?

No, you don't need it, and, actually, it might be the cause of such a long response. I'm closing the issue, but feel free to reopen it if you still experiencing the delay.
