### ISSUE TITLE
`send charts only` does not effectively filter metrics using graphite backend

### ISSUE THREAD

**Issue by n0coast** [netdata/netdata#10762]
##### OS / Environment

```
Linux hostname.340.amzn2.x86_64 #1 SMP Thu Feb 4 05:54:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Amazon Linux"
/etc/os-release:VERSION="2"
/etc/os-release:ID="amzn"
/etc/os-release:ID_LIKE="centos rhel fedora"
/etc/os-release:VERSION_ID="2"
/etc/os-release:PRETTY_NAME="Amazon Linux 2"
/etc/os-release:ANSI_COLOR="0;33"
/etc/os-release:CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
/etc/os-release:HOME_URL="https://amazonlinux.com/"
/etc/system-release:Amazon Linux release 2 (Karoo)
```

##### Netdata version

  ```
netdata v1.29.3
```

##### Component Name

exporting?
##### Steps To Reproduce

1. Configure multiple netdata headless streaming clients
2. Configure netdata as stream reciever
3. Configure netdata.conf [backend] section to send metrics to graphite
4. Add `send charts only` to [backend] to filter out many metrics
```
send charts matching = apps.cpu apps.mem apps.swap !apps !apps.* !cpu.* !disk_avgsz.* !disk_backlog.* !disk_iotime.* disk_ops.* !disk_space.reserved_for_root disk_space.* disk_util.* !ip.* !ipv4.* !ipv6.* !net.veth* net.* !netdata.* !services.* !users.* disk.* !disk_await.* !disk_inodes.* !disk_mops.* !disk_qops.* !disk_svctm.* !groups !groups.* mem.* !net_packets.* !netfilter system.cpu system.load system.io system.ram system.swap system.net system.uptime !system.* !*
```
5. Observe as graphite  receives and creates whisper files for metrics that should not be sent, for instance some (but not all?!) group metrics continue to be received by graphite after netdata is stopped/started.
6. I have tried multiple combinations for instance on the `groups` metrics to exclude them entirely, including !groups, !groups*, and !groups.*, but still graphite receives groups metrics
7. 
##### Expected behavior

send charts only would send only metrics matching patterns as documented.

**Comment by vlvkobal** [comment]
I applied your configuration
```
[backend]
	enabled = yes
	type = graphite
	send charts matching = apps.cpu apps.mem apps.swap !apps !apps.* !cpu.* !disk_avgsz.* !disk_backlog.* !disk_iotime.* disk_ops.* !disk_space.reserved_for_root disk_space.* disk_util.* !ip.* !ipv4.* !ipv6.* !net.veth* net.* !netdata.* !services.* !users.* disk.* !disk_await.* !disk_inodes.* !disk_mops.* !disk_qops.* !disk_svctm.* !groups !groups.* mem.* !net_packets.* !netfilter system.cpu system.load system.io system.ram system.swap system.net system.uptime !system.* !*
```
There are no `groups` metrics in the output
```
$ nc -l -p 2003 | grep gr
netdata.arch-esxi.mem.numa.pages_migrated 0.0000000 1615800898
```

BTW, the backends subsystem is deprecated. You should use the [exporting engine](https://learn.netdata.cloud/docs/agent/exporting) instead.

**Comment by n0coast** [comment]
I will try updating to the exporting engine and see if that resolves the issue.

**Comment by n0coast** [comment]
I updated my config to use the exporting engine, and while I used what I believe to be an identical configuration as I had setup for backend in netdata.conf I no longer see metrics coming in for `groups`. Maybe I had some misconfiguration in the original config - either way it's fixed and working now so I'll close this issue. Thanks for the help!
