### ISSUE TITLE
Netdata RAM usage computation does not match free(1) output

### ISSUE THREAD

**Issue by fayak** [netdata/netdata#10795]
##### Bug report summary

I'm trying to figure out what's eating up my RAM on some server, and the values from netdata charts and `free(1)` don't exactly match.

```bash
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G         22G        2.2G        3.2G        6.5G        5.1G
Swap:            0B          0B          0B
$ free
              total        used        free      shared  buff/cache   available
Mem:       32949424    23706180     2425348     3393880     6817896     5382504
Swap:             0           0           0
```
From System/RAM
![ram](https://user-images.githubusercontent.com/11300056/111509761-57c9b300-874d-11eb-8a21-08cc5fd7b897.jpg)
From Applications/mem
![ramapp](https://user-images.githubusercontent.com/11300056/111509772-5ac4a380-874d-11eb-9121-b308fccd52e7.jpg)

Free memory reported by `free(1)` is 2.2GiB while netdata at the same time report 1.8 GiB

`free(1)` reports 22GiB of used memory while netdata reports 26.3GiB. Even if we add the shared memory, we're having 25.2 GiB.

buff/cache reported by `free(1)` is 6.5GiB while netdata reports 3.2 + 0.1.

When I look directly at /proc/meminfo, the `Cached` info doesn't match what netdata reports indeed:
```
Buffers:          111732 kB
Cached:          6185508 kB
```

Is there something I'm missing here ?

##### OS / Environment

```
$ uname -a
Linux host 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
```

##### Netdata version
```
$ netdata -V
netdata v1.29.3-48-nightly
```
 

##### Component Name

collectors ?

##### Steps To Reproduce

Debian 9 started from a long time. Has a big tmpfs (~3.3 GiB), root partition is an overlay over a squashfs and a tmpfs.
Many apps running, some interactions with the fs to have some cache

##### Expected behavior

Have the RAM values matching `free(1)`

**Comment by ilyam8** [comment]
Hi @fayak 

Netdata collects data from `/proc/meminfo`. It could not match `free` output, indeed.

I see `free` output/calculation can differ, [it depends on kernel/version](https://access.redhat.com/solutions/406773).

Netdata calculates free memory as  `MemFree` / 1024.

Used is 

https://github.com/netdata/netdata/blob/e66b02ff6a936454acd63788c7b0e7953f0c1480/collectors/proc.plugin/proc_meminfo.c#L148-L150

Relevant discussion - https://github.com/netdata/netdata/issues/10153

**Comment by ilyam8** [comment]
> free(1) reports 22GiB of used memory while netdata reports 26.3GiB.
> buff/cache reported by free(1) is 6.5GiB while netdata reports 3.2 + 0.1.

This PR https://github.com/netdata/netdata/pull/10183, reason https://github.com/netdata/netdata/issues/10153#issuecomment-719993868

**Comment by fayak** [comment]
Ok so I guess the netdata output makes more sense than free then. Maybe is it worth dividing this chart a bit more ? Like include shmem, unreclaimable cache ? But I think you guys mot probably already thought about it.

Thanks for the answer !
