### ISSUE TITLE
Docker entrypoint script can't claim node

### ISSUE THREAD

**Issue by torkelrogstad** [netdata/netdata#10809]
The current `run.sh` entrypoint in the Docker image contains logic for claiming a node, but this is currently broken:

https://github.com/netdata/netdata/blob/3b5a69c2a29817f4fe114c09107f7e57e5a4d26d/packaging/docker/run.sh#L24-L27

The arguments needs to have a `=` between the parameter name and the actual parameter.

**Comment by ilyam8** [comment]
@torkelrogstad hi 👋  thx for reporting, you are right

https://github.com/netdata/netdata/blob/3b5a69c2a29817f4fe114c09107f7e57e5a4d26d/claim/netdata-claim.sh.in#L190-L209


It is funny, i even fixed that bug in https://github.com/netdata/netdata/pull/10692, but then close the PR 🙈
