### ISSUE TITLE
my version is v1.29.3-140-nightly ,one day time picker were gone,It used to exist

### ISSUE THREAD

**Issue by im-yangp** [netdata/netdata#10815]
![image](https://user-images.githubusercontent.com/49512694/111741336-528d7500-88c1-11eb-927c-7939e3f39e36.png)

**Comment by stelfrag** [comment]
Hi @im-yangp 

Do you still experience this issue? Can you try to clear your browser's cache?

**Comment by im-yangp** [comment]
It does not take effect. I have two machines.centos is successful,ubuntu is  a failure

**Comment by stelfrag** [comment]
> It does not take effect. I have two machines.centos is successful,ubuntu is a failure

Could you try to access the ubuntu machine via an incognito browser window?

If that doesn't work, I would suggest re-installing

**Comment by im-yangp** [comment]
@stelfrag 
Thank you for your help

**Comment by stelfrag** [comment]
Hi @im-yangp 

did you manage to get it working?

**Comment by ilyam8** [comment]
How did you install netdata @im-yangp?

**Comment by stelfrag** [comment]
Closing this. If the issue persists, please update to the latest version and / or reopen this issue so we can further investigate
