### ISSUE TITLE
Add extended metrics to the diskstats module

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#10848]
##### Feature idea summary
The `iostat` utility provides extended stats for new kernels. Additional fields in `/proc/diskstats` are documented in the kernel documentation: [iostat](https://www.kernel.org/doc/Documentation/iostats.txt) and [stat](https://www.kernel.org/doc/Documentation/block/stat.rst). We should add new charts for

||||
|-|-|-|
| discard I/Os    | requests      | number of discard I/Os processed |
| discard merges  | requests      | number of discard I/Os merged with in-queue I/O |
| discard sectors | sectors       | number of sectors discarded |
| discard ticks   | milliseconds  | total wait time for discard requests |

||||
|-|-|-|
| flush I/Os      | requests      | number of flush I/Os processed |
| flush ticks     | milliseconds  | total wait time for flush requests |

**Comment by ilyam8** [comment]
@vlvkobal did you check `iostat` code? What's the plan? To show those values as is?

i mean this part

https://github.com/sysstat/sysstat/blob/3e400d593af86ee2cb53d7780c771b3603acbfc7/iostat.c#L1465-L1517

**Comment by vlvkobal** [comment]
`iostat` - `diskstats plugin` comparison

metric | iostat label | iostat calculation | diskstats chart | diskstats dimension
--- | --- | --- | --- | ---
Indicate the number of transfers per second that were issued to the device. A transfer is an I/O request to the device. Multiple logical requests can be combined into a single I/O request to the device. A transfer is of indeterminate size. | tps     | S() rd_ios + wr_ios + dc_ios | — | —
Indicate the amount of data read from the device expressed in a number of blocks (kilobytes, megabytes) per second. Blocks are equivalent to sectors and therefore have a size of 512 bytes. | Blk_read/s (kB_read/s, MB_read/s) | S() rd_sectors | disk | reads
Indicate the amount of data written to the device expressed in a number of blocks (kilobytes, megabytes) per second. | Blk_wrtn/s (kB_wrtn/s, MB_wrtn/s) | S() wr_sectors | disk | writes
Indicate the amount of data discarded for the device expressed in a number of blocks (kilobytes, megabytes) per second. | Blk_dscd/s (kB_dscd/s, MB_dscd/s) | S() dc_sectors | disk | **discards**
The total number of blocks (kilobytes, megabytes) read. | Blk_read (kB_read, MB_read) | rd_sectors | — | —
The total number of blocks (kilobytes, megabytes) written. | Blk_wrtn (kB_wrtn, MB_wrtn) | wr_sectors | — | —
The total number of blocks (kilobytes, megabytes) discarded. | Blk_dscd (kB_dscd, MB_dscd) | dc_sectors | — | —
The number (after merges) of read requests completed per second for the device. | r/s | S() rd_ios | disk_ops | reads
The number (after merges) of write requests completed per second for the device. | w/s | S() wr_ios | disk_ops | writes
The number (after merges) of discard requests completed per second for the device. | d/s | S() dc_ios | disk_ops | **discards**
The number (after merges) of flush requests completed per second for the device.  This counts flush requests executed by disks. Flush requests are not tracked for partitions. Before being merged, flush operations are counted as writes. | f/s | S() fl_ios | — | —
The number of sectors (kilobytes, megabytes) read from, written to or discarded for the device per second. | sec/s (kB/s, MB/s) | S() rd_sectors + wr_sectors + dc_sectors | — | —
The number of sectors (kilobytes, megabytes) read from the device per second. | rsec/s (rkB/s, rMB/s) | S() rd_sectors | disk | reads
The number of sectors (kilobytes, megabytes) written to the device per second. | wsec/s (wkB/s, wMB/s) | S() wr_sectors | disk | writes
The number of sectors (kilobytes, megabytes) discarded for the device per second. | dsec/s | S() dc_sectors | disk | **discards**
The number of I/O requests merged per second that were queued to the device. | rqm/s | S() rd_merges + wr_merges + dc_merges | — | —
The number of read requests merged per second that were queued to the device. | rrqm/s | S() rd_merges | disk_mops | reads
The number of write requests merged per second that were queued to the device. | wrqm/s | S() wr_merges | disk_mops | writes
The number of discard requests merged per second that were queued to the device. | drqm/s | S() dc_merges | disk_mops | **discards**
The percentage of read requests merged together before being sent to the device. | %rrqm | S() rd_merges | disk_mops | reads
The percentage of write requests merged together before being sent to the device. | %wrqm | S() wr_merges | disk_mops | writes
The percentage of discard requests merged together before being sent to the device. | %drqm | S() dc_merges | disk_mops | **discards**
The average size (in kilobytes) of the I/O requests that were issued to the device. Note: In previous versions, this field was known as avgrq- sz and was expressed in sectors. | areq-sz | S() (rd_sectors + wr_sectors + dc_sectors) / (rd_ios + wr_ios + dc_ios) | — | —
The average size (in kilobytes) of the read requests that were issued to the device. | rareq-sz | S() rd_sectors / rd_ios | disk_avgsz | reads
The average size (in kilobytes) of the write requests that were issued to the device. | wareq-sz | S() wr_sectors / wr_ios | disk_avgsz | writes
The average size (in kilobytes) of the discard requests that were issued to the device. | dareq-sz | S() dc_sectors / dc_ios | disk_avgsz | **discards**
The average time (in milliseconds) for I/O requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them. | await | S() (rd_ticks + wr_ticks + dc_ticks) / (rd_ios + wr_ios + dc_ios) | disk_svctm | svctm
The average time (in milliseconds) for read requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them. | r_await | S() rd_ticks / rd_ios | disk_await | reads
The average time (in milliseconds) for write requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them. | w_await | S() wr_ticks / wr_ios | disk_await | writes
The average time (in milliseconds) for discard requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them. | d_await | S() dc_ticks / dc_ios | disk_await | **discards**
The average time (in milliseconds) for flush requests issued to the device to be served.  The block layer combines flush requests and executes at most one at a time. Thus flush operations could be twice as long: Wait for current flush request, then execute it, then wait for the next one. | f_await | S() fl_ticks / fl_ios | disk_await | **flushes**
The average queue length of the requests that were issued to the device. Note: In previous versions, this field was known as avgqu- sz. | aqu-sz | S() rq_ticks | disk_backlog | backlog
Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits. | %util | S() tot_ticks | disk_util | utilization

Metrics available only in `diskstats plugin`

metric | chart | dimension
--- | --- | ---
Disk Current I/O Operations | disk_qops | operations
Disk Busy Time | disk_busy | busy
Disk Total I/O Time | disk_iotime | readms, writems

**Comment by vlvkobal** [comment]
My conclusion - we have to add only `discards` and `flushes` dimensions, that's it.

**Comment by vlvkobal** [comment]
Verified our existing charts once more. The essence of read/write and extended operations is a bit different. Thus, having separate charts for extended operations is more logical. I updated the tables accordingly.
