### ISSUE TITLE
ACLK-NG Mac OS compatibility

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#10842]
##### Bug report summary

ACLK-NG can't build on Mac OS due to few small issues:
-> `endian.h` missing including necessary functions like `be16toh`
-> use of undeclared identifier 'CLOCK_BOOTTIME'
-> implicit declaration of function 'pipe2' (mac knows only `pipe`)

##### OS / Environment
```
La wonderful fruity OS
```

##### Component Name
ACLK-NG
##### Steps To Reproduce
`netdata-installer --aclk-ng` on Mac OS

##### Expected behavior
It builds and works automagically

**Comment by OdysLam** [comment]
Do we have any update on this @underhood ? It's a blocker to enable netdata-cloud in homebrew installations.

**Comment by underhood** [comment]
@OdysLam I have been asking around about getting Mac VM for development...

**Comment by OdysLam** [comment]
We had internal chat with @underhood and @kaskavel. Let's keep this thread to sync about any macOS VM and testing. 

Looking forward for the fixes ✌️

**Comment by chenrui333** [comment]
Any update on this thread?

**Comment by Conna576** [comment]
I honestly don't think I have this installed right.  It all makes no sense.  😞

**Comment by underhood** [comment]
@chenrui333 we are working on this. There is already one PR that improves things considerably and another one incoming. Currently, we are in code freeze ahead of release. They will go in ASAP as the code freeze is lifted.
