### ISSUE TITLE
Health: telegram bot just sent one or two messages 

### ISSUE THREAD

**Issue by smilenazy** [netdata/netdata#10862]
##### OS / Environment

```
CentOS 7 
```

##### Netdata version

netdata v1.29.3
##### Installation method

bash < (curl -Ss https://my-netdata.io/kickstart.sh) all
##### Component Name

Health use by telegram 
##### Steps To Reproduce

1. config telegram 
2. stop mysql slave 
3. telegram bot sent message to group
4. recover mysql slave (but no sent recover messages)
5. stop other mysql slave but bot not sent a messages ...

##### Expected behavior

help to take this .. because i can see alarms on the web .  i want its can send message to telegram and when i recover this alarms  
bot can send a recover message to group  Thanks

**Comment by smilenazy** [comment]
bot recover it  but too slowly 

![image](https://user-images.githubusercontent.com/59309899/112594343-becd2300-8e43-11eb-8f8c-c2c5d9954600.png)

when this time   other mysql error  cant send  alarms on group ..

**Comment by ilyam8** [comment]
@smilenazy hey 👋 

That is the alarm

https://github.com/netdata/netdata/blob/12b3e5fd62ec7e6703a48f359c7bcf7a2b0a5198/health/health.d/mysql.conf#L80-L88

There is [delay: down 5m](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) option, it means that CLEAR notifications is delayed by 5 minutes.

**Comment by smilenazy** [comment]
OK i try this
