### ISSUE TITLE
Discord Alert broken ?

### ISSUE THREAD

**Issue by Whisper40** [netdata/netdata#10877]
##### Bug report summary
I created a webhook on Discord, i added those environment variable. But nothing is sent, in logs there is no one word with "Discord or Webhook".

```
- DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}     ex : "https://discord.com/api/webhooks/8260....47318882364.."
- DISCORD_RECIPIENT=${DISCORD_RECIPIENT}   ex : "discussions"
- SEND_DISCORD="YES"
```

The connection with your cloud is working properly. I already tried to disconnect it, to erase everything and to only set discord and not the cloud, same result.

##### OS / Environment

```
Docker Installation 
```

##### Netdata version
Latest -> v1.29.3-215-nightly

##### Steps To Reproduce

1. Your recommended docker compose
2. Add discord webhook
3. Start your container
4. You don't receive anything.

##### Expected behavior
I should receive something when netdata stops, start, cpu 100%.... ( like with mails..)

**Comment by ilyam8** [comment]
Hi @Whisper40, where did you add those variables?

**Comment by Whisper40** [comment]
I added them in my docker compose in order that they can be available at the container boot
```
    environment:
      - TZ=Europe/Paris
      - PUID=201
      - PGID=201
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=${NETDATA_CLAIM_URL}
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - DEFAULT_RECIPIENT_DISCORD=${DEFAULT_RECIPIENT_DISCORD}
      - SEND_DISCORD="YES"
```

**Comment by ilyam8** [comment]
Ok, i see, i think it is not possible to set health notification parameters via environment variables. [You need to set them](https://learn.netdata.cloud/docs/agent/health/notifications/discord) in the [health_alarm_notify.conf](https://github.com/netdata/netdata/blob/master/health/notifications/health_alarm_notify.conf)

**Comment by Whisper40** [comment]
Hum thanks okay, but i'm using docker, and the default configuration purposed with volume does not permits that.
I found that this file is in `/usr/lib/netdata/conf.d/health_alarm_notify.conf`

But the data of the container is not going on the host in order that i modify what i need : 
`- $CONFIG_DIR/netdata/conf.d:/usr/lib/netdata/conf.d`

**Comment by ilyam8** [comment]
@Whisper40 use configuration is in the `/etc/netdata`, check https://learn.netdata.cloud/docs/agent/packaging/docker#host-editable-configuration

**Comment by Whisper40** [comment]
Oh ok it's why it's an empty one ;) Thanks

**Comment by Whisper40** [comment]
Hello, i re open this issue, because there is something that i don't understand..
I'm now running the netdata:stable version ( created 3 days ago).

I have one file : health_alarm_notify.conf : 
```
SEND_DISCORD="YES"
DISCORD_WEBHOOK_URL="https://discord.com/api/we..."
DEFAULT_RECIPIENT_DISCORD="netdata"
```
I have netdata cloud that is linked.
Netdata cloud sends me many notification (tcp/disk) alarms.
But never on discord.. I don't receive any real alarm..

Did you test discord connection ?
Yes, and it works, i receive the test alarm in my channel, but never true alarm...

**Comment by ilyam8** [comment]
> Netdata cloud sends me many notification (tcp/disk) alarms.

What are those notifications? [As you already know](https://github.com/netdata/netdata/issues/10902#issuecomment-813004342) sometimes it is expected (e.g Agent respects to:silent, Clound doesn't).

Discord notification method is just [a HTTP POST request](https://github.com/netdata/netdata/blob/0068b7c11a65058778e96029264e374f0ca7fa1e/health/notifications/alarm-notify.sh.in#L1611-L1668), if the request is correct then it should work.

If there are any problems the correct place to check is error.log

> docker logs NAME 2>&1 | grep "sent discord"

**Comment by Whisper40** [comment]
When i execute manual test, it works like that : 
![image](https://user-images.githubusercontent.com/30440458/113826086-0c218c80-9782-11eb-9f4f-dc6d4c68130e.png)

Your command return nothing ( after my manual test ! ) : 
![image](https://user-images.githubusercontent.com/30440458/113826209-3115ff80-9782-11eb-97e3-f1d3f6daaf0a.png)

**Comment by Whisper40** [comment]
I received my first alert ! : system.cpu (cpu), 10min cpu iowait = 51% Good :)

**Comment by ilyam8** [comment]
haha good for you bad for your server 😄

**Comment by Whisper40** [comment]
Normal thing ;) All of my server are really used a lottt :)
