### ISSUE TITLE
No guest-chart in System Overview for qemu guests

### ISSUE THREAD

**Issue by linuzer** [netdata/netdata#10874]
##### Bug report summary
I have two libvirt/qemu hosts, one running on Ubuntu 20.10 ("banana"), the other on Debian-testing ("gehtnix"). On both I installed netdata using the online installer. 
On the Ubuntu box, I see in the System Overview section a chart called "guest" showing the CPU-activity of the installed guest vm. 
On the Debian box, I don't have that chart, rather the guest activity is included into the system-chart.

Why does the Debian box not show that guest-chart?

I googled already several days in order to rule out any configuration issues, but I didn't find any hints pointing me in the right direction. So I cannot tell for sure, if it is a bug, or a configuration issue -- or something entirely different. 

Any help would be highly appreciated!
![Bildschirmfoto 2021-03-28 um 13 53 26](https://user-images.githubusercontent.com/3530673/112751327-a852d300-8fcd-11eb-96f2-b1edc4963149.png)
![Bildschirmfoto 2021-03-28 um 13 53 31](https://user-images.githubusercontent.com/3530673/112751334-abe65a00-8fcd-11eb-8630-97778cc7acff.png)

##### OS / Environment
netdata runs native, no container.

uname -a; grep -Hv "^#" /etc/*release
```
Linux gehtnix 5.10.0-5-amd64 #1 SMP Debian 5.10.24-1 (2021-03-19) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux bullseye/sid"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version
netdata -W buildinfo
```
Version: netdata v1.29.3-215-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     YES
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```
##### Installation method
bash <(curl -Ss https://my-netdata.io/kickstart.sh)

##### Component Name
System overview

##### Steps To Reproduce
1. install a virtual machine with libvirt/qemu
2. ...not sure...

##### Expected behavior
There should be a global chart for all guest CPU-activities.

**Comment by ilyam8** [comment]
Hi @linuzer 

Try to `Dashboard Options -> Performance -> Which dimensions to show -> All`

**Comment by linuzer** [comment]
Hi ilyam8
that's interesting, didn't know about that option!
Now I see a lot more categories, among them also "guest", but only showing "0.0" as value. The CPU usage from the guests is still shown as "system"...
![Bildschirmfoto 2021-03-28 um 19 07 27](https://user-images.githubusercontent.com/3530673/112760981-3d1ef600-8ff9-11eb-9813-02625d2b2b8f.png)

**Comment by ilyam8** [comment]
Netdata collects these metrics from `/proc/stat`. So that is what your system reports.

```cmd
ilyam@xxx:~$ cat /proc/stat | grep cpu
cpu  47954862 800158 27122330 6733883060 540538 0 157256 539542 0 0
cpu0 47954862 800158 27122330 6733883060 540538 0 157256 539542 0 0
```

`guest` is word 9 (if we don't count `cpu`)

https://github.com/netdata/netdata/blob/4c34788d51646f1f41bcb663e9df5731ee5024cc/collectors/proc.plugin/proc_stat.c#L600-L613


---

You an check it manually, it seems `guest` value doesn't increase

**Comment by linuzer** [comment]
Thanks a lot for your help! You are right, on Ubuntu it shows these values, on Debian not:
```
root@banana:~# cat /proc/stat | grep cpu
cpu  1908302 34808 1616160 45109366 1553590 0 169355 0 775932 0
cpu0 972892 18089 816140 22745756 674336 0 12304 0 409394 0
cpu1 935410 16719 800020 22363610 879253 0 157051 0 366538 0
```

```
root@gehtnix:~# cat /proc/stat | grep cpu
cpu  3702870 10657 25708068 172576958 693493 0 76249 0 0 0
cpu0 1227178 1855 2567467 21284609 162618 0 257 0 0 0
cpu1 1245866 435 8799032 14895460 17375 0 26818 0 0 0
cpu2 67861 1615 2365858 22868854 105567 0 12881 0 0 0
cpu3 76253 1054 2824844 22429718 58710 0 5010 0 0 0
cpu4 877758 772 3386393 21059955 101734 0 21602 0 0 0
cpu5 62273 889 2425970 22986881 60855 0 4486 0 0 0
cpu6 52002 1031 1975237 23363570 74819 0 1979 0 0 0
cpu7 93676 3005 1363265 23687907 111811 0 3212 0 0 0
```

So, in other words I have to investigate, why Qemu on Debian doesn't report the guest values?
You don't have by coincidence any clue on that, do you?

**Comment by ilyam8** [comment]
No, i don't know 🤷‍♂️ Not a specialist, guessing here, perhaps it is a matter of configuration options (something with virtual cpus)

**Comment by linuzer** [comment]
OK, thanks a lot for your help!

**Comment by ilyam8** [comment]
@linuzer of there are any questions consider to use [our community fourm](https://community.netdata.cloud/).

---

> So, in other words I have to investigate, why Qemu on Debian doesn't report the guest values?


If you manage to find out the reason, please post it here 😄

**Comment by linuzer** [comment]
I have news on this:
It seems indeed to be a linux kernel-bug affecting all kernels after 5.9. There is a Debian bug report on this:

[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986371](url)

**Comment by ilyam8** [comment]
Thanks for sharing @linuzer!
