### ISSUE TITLE
netdata-1.30.0/mqtt_websockets: No rule to make target 'all'.

### ISSUE THREAD

**Issue by candrews** [netdata/netdata#10891]
##### Bug report summary

Trying to build netdata 1.3.0 with the configure options `--enable-cloud --with-aclk-ng` results in this error:
```
Making all in mqtt_websockets
make[2]: Entering directory '/var/tmp/portage/net-analyzer/netdata-1.30.0/work/netdata-1.30.0/mqtt_websockets'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/var/tmp/portage/net-analyzer/netdata-1.30.0/work/netdata-1.30.0/mqtt_websockets'
make[1]: *** [Makefile:5743: all-recursive] Error 1
```
[build.log](https://github.com/netdata/netdata/files/6237199/build.log)

##### OS / Environment

```
$ uname -a; grep -Hv "^#" /etc/*release
Linux irrational 5.11.0-gentoo-x86_64 #1 SMP Mon Feb 15 09:44:11 EST 2021 x86_64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz GenuineIntel GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.7
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo/Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:HOME_URL="https://www.gentoo.org/"
/etc/os-release:SUPPORT_URL="https://www.gentoo.org/support/"
/etc/os-release:BUG_REPORT_URL="https://bugs.gentoo.org/"
```

##### Netdata version

1.3.0

##### Installation method

Using `configure` and `make`

##### Component Name

Build system

##### Steps To Reproduce

1. `./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/netdata-1.30.0 --htmldir=/usr/share/doc/netdata-1.30.0/html --libdir=/usr/lib64 --localstatedir=/var --with-user=netdata --enable-cloud --with-aclk-ng --enable-jsonc --enable-plugin-cups --enable-dbengine --disable-plugin-nfacct --disable-plugin-freeipmi --disable-backend-kinesis --enable-lto --disable-backend-mongodb --disable-backend-prometheus-remote-write --disable-plugin-xenstat --enable-x86-sse --with-zlib`
2. `make -j5`

##### Expected behavior

Should build successfully, or if conflicting/invalid options are provided, exit with a descriptive error message.

**Comment by underhood** [comment]
Hi, I should probably add autoconf check for missing git submodules to print nicer error message in this case.
The problem however is simple you need to run `git submodules update --init --recursive` which should populate `mqtt_websockets` directory

**Comment by candrews** [comment]
I'm not using git though. I'm using the release archive .tar.gz from https://github.com/netdata/netdata/releases/tag/v1.30.0

**Comment by underhood** [comment]
I see, thank you for reporting this. We are fixing this ASAP

**Comment by diizzyy** [comment]
Can confirm the same on FreeBSD

**Comment by Ferroin** [comment]
Indeed, this should be the case currently on all platforms.

We’re planning on doing a patch release some time next week that should include a fix for this, though there will hopefully be a fix in the nightlies before the end of the week.
