### ISSUE TITLE
disk_backlog alarm reports

### ISSUE THREAD

**Issue by Whisper40** [netdata/netdata#10902]
##### Bug report summary

On a fresh Netdata install, running with Docker on branch "stable - 4 days ago".
By default the alarm : disk_backlog is to: silent.
But netdata cloud sends me the alarm :
Alarm information:    10min_disk_backlog    average disk backlog size over the last 10 minutes
Alarm value:    11898.25 ms

##### OS / Environment
Docker
##### Netdata version
build stable

##### Installation method
Docker Compose
##### Component Name
disks.conf  -> 10min_disk_backlog
##### Steps To Reproduce
Fresh install with docker and produce something in order that this alarm is raised

##### Expected behavior
I should not receive this alarm because it is set to: silent

In my disks.conf (the default one, i don't have touch it..) : 
```

# you can disable an alarm notification by setting the 'to' line to: silent


# -----------------------------------------------------------------------------
# low disk space

# checking the latest collected values
# raise an alarm if the disk is low on
# available disk space

template: disk_space_usage
      on: disk.space
      os: linux freebsd
   hosts: *
families: !/dev !/dev/* !/run !/run/* *
    calc: $used * 100 / ($avail + $used)
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING ) ? (80) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: up 1m down 15m multiplier 1.5 max 1h
    info: disk space utilization
      to: sysadmin

template: disk_inode_usage
      on: disk.inodes
      os: linux freebsd
   hosts: *
families: !/dev !/dev/* !/run !/run/* *
    calc: $used * 100 / ($avail + $used)
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING)  ? (80) : (90))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: up 1m down 15m multiplier 1.5 max 1h
    info: disk inode utilization
      to: sysadmin


# -----------------------------------------------------------------------------
# disk fill rate

# calculate the rate the disk fills
# use as base, the available space change
# during the last hour

# this is just a calculation - it has no alarm
# we will use it in the next template to find
# the hours remaining

# template: disk_fill_rate
#       on: disk.space
#       os: linux freebsd
#    hosts: *
# families: *
#   lookup: min -10m at -50m unaligned of avail
#     calc: ($this - $avail) / (($now - $after) / 3600)
#    every: 1m
#    units: GB/hour
#     info: average rate the disk fills up (positive), or frees up (negative) space, for the last hour


# calculate the hours remaining
# if the disk continues to fill
# in this rate

# template: out_of_disk_space_time
#       on: disk.space
#       os: linux freebsd
#    hosts: *
# families: *
#     calc: ($disk_fill_rate > 0) ? ($avail / $disk_fill_rate) : (inf)
#    units: hours
#    every: 10s
#     warn: $this > 0 and $this < (($status >= $WARNING)  ? (48) : (8))
#     crit: $this > 0 and $this < (($status == $CRITICAL) ? (24) : (2))
#    delay: down 15m multiplier 1.2 max 1h
#     info: estimated time the disk will run out of space, if the system continues to add data with the rate of the last hour
#       to: sysadmin


# -----------------------------------------------------------------------------
# disk inode fill rate

# calculate the rate the disk inodes are allocated
# use as base, the available inodes change
# during the last hour

# this is just a calculation - it has no alarm
# we will use it in the next template to find
# the hours remaining

# template: disk_inode_rate
#       on: disk.inodes
#       os: linux freebsd
#    hosts: *
# families: *
#   lookup: min -10m at -50m unaligned of avail
#     calc: ($this - $avail) / (($now - $after) / 3600)
#    every: 1m
#    units: inodes/hour
#     info: average rate at which disk inodes are allocated (positive), or freed (negative), for the last hour

# calculate the hours remaining
# if the disk inodes are allocated
# in this rate

# template: out_of_disk_inodes_time
#       on: disk.inodes
#       os: linux freebsd
#    hosts: *
# families: *
#     calc: ($disk_inode_rate > 0) ? ($avail / $disk_inode_rate) : (inf)
#    units: hours
#    every: 10s
#     warn: $this > 0 and $this < (($status >= $WARNING)  ? (48) : (8))
#     crit: $this > 0 and $this < (($status == $CRITICAL) ? (24) : (2))
#    delay: down 15m multiplier 1.2 max 1h
#     info: estimated time the disk will run out of inodes, if the system continues to allocate inodes with the rate of the last hour
#       to: sysadmin


# -----------------------------------------------------------------------------
# disk congestion

# raise an alarm if the disk is congested
# by calculating the average disk utilization
# for the last 10 minutes

template: 10min_disk_utilization
      on: disk.util
      os: linux freebsd
   hosts: *
families: *
  lookup: average -10m unaligned
   units: %
   every: 1m
   green: 90
     red: 98
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1))
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1))
   delay: down 15m multiplier 1.2 max 1h
    info: average percentage of time the disk was busy over the last 10 minutes
      to: silent


# raise an alarm if the disk backlog
# is above 1000ms (1s) per second
# for 10 minutes
# (i.e. the disk cannot catch up)

template: 10min_disk_backlog
      on: disk.backlog
      os: linux
   hosts: *
families: *
  lookup: average -10m unaligned
   units: ms
   every: 1m
   green: 2000
     red: 5000
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1))
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1))
   delay: down 15m multiplier 1.2 max 1h
    info: average disk backlog size over the last 10 minutes
      to: silent

```

**Comment by ilyam8** [comment]
Hi @Whisper40 

This is well-known problem, Netdata Cloud doesn't respect both [delay](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) and [to](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-to) alarm configuration options. It is by initial design, so it is expected. 

We are working on _fixing_ this, check my brief explanation in https://github.com/netdata/netdata/issues/10896#issuecomment-812591403

**Comment by Whisper40** [comment]
Oh sry.. I have read something on the doc mentioning that Netdata Cloud was based on alarms of each node so it's why i have think that it should work as i said..

**Comment by ilyam8** [comment]
~related https://community.netdata.cloud/t/ram-in-swap-alert/118/9?u=ilyam8

**Comment by ilyam8** [comment]
> Alarm information: 10min_disk_backlog average disk backlog size over the last 10 minutes
Alarm value: 11898.25 ms

@Whisper40 

How often does this happen? Does this correlate with some kind of workload on the server? (high disk backlog)

**Comment by Whisper40** [comment]
The server have 2*3TB of disk.
I'm using LVM Thin volumes for the data storage (~5.5TB)
It happens regularely (at least 5 times per day i think) each time that i download huge files ( 8-100GB ). 

I don't really understand this error, because it appears each time because my server work ahah)
I already have got 60000 ms or things like that without having any problem on my side..

```
Alarm information:    10min_disk_backlog    average disk backlog size over the last 10 minutes
Alarm value:    36544.2594421 ms
```

**Comment by ilyam8** [comment]
Could you do `iostat -x 1 5` **when that alarm is active** and share the output (you need `sysstat` package installed, `iostat` is part of it)

**Comment by alex222efx** [comment]
Hi @ilyam8 

Could you please let me know if there is another way to disable the disk_backlog alarm?
In /etc/netdata/netdata.conf I have set backlog to "no" for each disk, but it still sends notifications:


[plugin:proc:/proc/diskstats:xvda]
        # enable = yes
        # enable performance metrics = yes
        # bandwidth = auto
        # operations = auto
        # merged operations = auto
        # i/o time = auto
        # queued operations = auto
        # utilization percentage = auto
        # backlog = auto
          backlog = no

**Comment by ilyam8** [comment]
> but it still sends notifications:

You mean Netdata Cloud notifications?

**Comment by ilyam8** [comment]
> Could you please let me know if there is another way to disable the disk_backlog alarm?

To disable it completely you need to copy [disks.conf](https://github.com/netdata/netdata/blob/master/health/health.d/disks.conf) to the /etc/netdata/health.d/ (or opt/netdata/etc/netdata/health.d, depends on your install) and comment out

https://github.com/netdata/netdata/blob/a389f1a17e3b977e2d36969d830ac63218829b2d/health/health.d/disks.conf#L153-L167

**Comment by Whisper40** [comment]
@ilyam8 Hello, sry for the delay, my provider took 4 days to reinstall the server.. many problems..
This is the output just after that i received the alert : 
```
iostat -x 1 5
Linux 4.19.0-16-amd64 (s10)     04/07/2021      _x86_64_        (8 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.12    0.01    0.15    0.03    0.00   99.69

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svc                                     tm  %util
sda              0.30   22.30      9.81   1693.61     0.01    10.39   3.46  31.78    3.82    7.67   0.17    32.93    75.96   0.                                     06   0.13
dm-0             0.00    0.02      0.00      0.09     0.00     0.00   0.00   0.00    0.00    3.78   0.00     4.71     4.00   3.                                     22   0.01
dm-1             0.00   10.96      0.08    285.03     0.00     0.00   0.00   0.00   11.41   18.92   0.21    16.50    26.00   0.                                     05   0.05
dm-2             0.00   10.96      0.08    285.03     0.00     0.00   0.00   0.00   11.41   18.92   0.21    16.50    26.00   0.                                     05   0.05
dm-4             0.01    8.48      0.15    126.26     0.00     0.00   0.00   0.00    6.61  795.30   6.74    16.98    14.89   0.                                     07   0.06

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.00    0.13    1.00    0.13    0.00   98.75

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svc                                     tm  %util
sda              0.00  757.00      0.00  96292.00     0.00   388.00   0.00  33.89    0.00    0.21   0.00     0.00   127.20   0.                                     00   0.00
dm-0             0.00    9.00      0.00     36.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     4.00   0.                                     00   0.00
dm-1             0.00 1136.00      0.00  96256.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00    84.73   0.                                     00   0.40
dm-2             0.00 1136.00      0.00  96256.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00    84.73   0.                                     00   0.40
dm-4             0.00  368.00      0.00  47104.00     0.00     0.00   0.00   0.00    0.00    0.02   0.01     0.00   128.00   0.                                     01   0.40

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.13    0.13    1.00    0.25    0.00   98.50

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svc                                     tm  %util
sda              0.00  713.00      0.00  90292.00     0.00   388.00   0.00  35.24    0.00    0.21   0.00     0.00   126.64   0.                                     00   0.00
dm-0             0.00    9.00      0.00     36.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     4.00   0.                                     00   0.00
dm-1             0.00 1061.00      0.00  90132.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00    84.95   0.                                     00   0.40
dm-2             0.00 1061.00      0.00  90132.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00    84.95   0.                                     00   0.40
dm-4             0.00  358.00      0.00  45080.00     0.00     0.00   0.00   0.00    0.00    0.02   0.01     0.00   125.92   0.                                     01   0.40

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.12    0.25    0.75    0.25    0.00   98.62

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              0.00  725.00      0.00  92196.00     0.00   356.00   0.00  32.93    0.00    0.21   0.00     0.00   127.17   0.00   0.00
dm-0             0.00    9.00      0.00     36.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     4.00   0.00   0.00
dm-1             0.00 1072.00      0.00  92160.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00    85.97   0.00   0.00
dm-2             0.00 1072.00      0.00  92160.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00    85.97   0.00   0.00
dm-4             0.00  368.00      0.00  47104.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00   128.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.13    0.13    0.88    0.13    0.00   98.75

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              0.00  757.00      0.00  96292.00     0.00   388.00   0.00  33.89    0.00    0.20   0.00     0.00   127.20   0.00   0.00
dm-0             0.00    9.00      0.00     36.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     4.00   0.00   0.00
dm-1             0.00 1136.00      0.00  96256.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00    84.73   0.00   0.00
dm-2             0.00 1136.00      0.00  96256.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00    84.73   0.00   0.00
dm-4             0.00  368.00      0.00  47104.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00   128.00   0.00   0.00

```

**Comment by Whisper40** [comment]
@ilyam8 Second alarm : 
iostat -x 1 5
Linux 4.19.0-16-amd64 (s10)     04/07/2021      _x86_64_        (8 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.14    0.02    0.21    0.05    0.00   99.58

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              0.29   29.67      9.68   2191.68     0.01    13.20   3.40  30.79    3.95   11.70   0.34    33.15    73.87   0.07   0.21
dm-0             0.00    0.07      0.00      0.27     0.00     0.00   0.00   0.00    0.00    1.82   0.00     4.71     4.00   1.42   0.01
dm-1             0.01   20.73      0.18    826.57     0.00     0.00   0.00   0.00   12.13   23.01   0.48    21.04    39.88   0.06   0.13
dm-2             0.01   20.73      0.18    826.57     0.00     0.00   0.00   0.00   12.13   23.01   0.48    21.04    39.88   0.06   0.13
dm-4             0.01    9.87      0.17    332.35     0.00     0.00   0.00   0.00    6.72 1150.68  11.35    19.87    33.68   0.13   0.13
dm-5             0.01    4.10      0.14     61.05     0.00     0.00   0.00   0.00    6.88 3955.00  16.20    19.31    14.90   0.05   0.02

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.13    0.25    1.00    0.00    0.00   98.62

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-0             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-1             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-2             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-4             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-5             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.88    0.13    5.51    0.00    0.00   92.48

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              0.00    1.00      0.00      4.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     4.00   0.00   0.00
dm-0             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-1             0.00    1.00      0.00      4.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     4.00   0.00   0.00
dm-2             0.00    1.00      0.00      4.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     4.00   0.00   0.00
dm-4             0.00    1.00      0.00      4.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     4.00   0.00   0.00
dm-5             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.25    0.12    1.50    0.00    0.00   98.13

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-0             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-1             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-2             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-4             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-5             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.13    0.25    1.13    0.00    0.00   98.50

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sda              0.00    2.00      0.00     60.00     0.00    13.00   0.00  86.67    0.00    0.00   0.00     0.00    30.00   0.00   0.00
dm-0             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-1             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-2             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-4             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00
dm-5             0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     0.00     0.00   0.00   0.00

**Comment by ilyam8** [comment]
@Whisper40 thanks, can you show _Disk Backlog_ chart when the alarm is active?

**Comment by Whisper40** [comment]
on branch "stable - 4 days ago" ;)
Yes 1.30.0.
Actually i only have this chart .
Backlog error : 2021-04-07 10:21:28 +0000 UTC    ( On the graph it corresponds to my timezone : 12:21 )
Alarm value: 
10366.58802 ms 

![image](https://user-images.githubusercontent.com/30440458/113855431-4a2da900-97a0-11eb-8064-2afa14b62083.png)

**Comment by Whisper40** [comment]
@ilyam8 Do you have all you need, or need more informations ?
