### ISSUE TITLE
Updating from Xenial to Focal will not allow netdata-updater to work

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#10943]
##### Bug report summary

After updating from Xenial to Focal, I get:
```
/etc/cron.daily/netdata-updater:
netdata: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory
```

Kickstart script won't work, since (again) it depends on the locally installed version

##### OS / Environment

Ubuntu Focal 20.04.1

##### Netdata version

v1.30.0-18-nightly

##### Installation method

kickstart script

##### Steps To Reproduce

1. ...
2. ...

**Comment by stdedos** [comment]
Manual/forced invocation gives:
```console
$ bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry --disable-cloud
 --- Found existing install of Netdata under: / --- 
 --- Attempting to update existing install instead of creating a new one --- 
[/home/h]$ sudo //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron [sudo] password for sntentos: 
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
Πεμ 08 Απρ 2021 03:52:05 μμ EEST : INFO:  Running on a terminal - (this script also supports running headless from crontab)
netdata: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory
Πεμ 08 Απρ 2021 03:52:05 μμ EEST : INFO:  Current Version: 00000000000000
Πεμ 08 Απρ 2021 03:52:05 μμ EEST : INFO:  Latest Version: 00103000000016
./netdata-latest.tar.gz: OK
/tmp/netdata-updater-qtCtc3ARmp/netdata-updater.sh: line 298: cd: too many arguments
 FAILED  

 ABORTED  Failed to update existing Netdata install 

$ sudo apt-get install libjson-c-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjson-c-dev is already the newest version (0.13.1+dfsg-7ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
$ locate libjson-c.so.
Running:
locate '*libjson-c.so.*'
/lib/x86_64-linux-gnu/libjson-c.so.3
/lib/x86_64-linux-gnu/libjson-c.so.3.0.1
/snap/core/10908/lib/x86_64-linux-gnu/libjson-c.so.2
/snap/core/10908/lib/x86_64-linux-gnu/libjson-c.so.2.0.0
/snap/core/10958/lib/x86_64-linux-gnu/libjson-c.so.2
/snap/core/10958/lib/x86_64-linux-gnu/libjson-c.so.2.0.0
/snap/core18/1988/lib/x86_64-linux-gnu/libjson-c.so.3
/snap/core18/1988/lib/x86_64-linux-gnu/libjson-c.so.3.0.1
/snap/core18/1997/lib/x86_64-linux-gnu/libjson-c.so.3
/snap/core18/1997/lib/x86_64-linux-gnu/libjson-c.so.3.0.1
/snap/core20/904/usr/lib/x86_64-linux-gnu/libjson-c.so.4
/snap/core20/904/usr/lib/x86_64-linux-gnu/libjson-c.so.4.0.0
/snap/core20/975/usr/lib/x86_64-linux-gnu/libjson-c.so.4
/snap/core20/975/usr/lib/x86_64-linux-gnu/libjson-c.so.4.0.0
```

**Comment by Ferroin** [comment]
See #10931 and #10936.

In short, the updater failure is not due to upgrading your OS (Netdata not starting _is_, but there is exactly nothing we can do about that), but due to a big in the updater that was just fixed yesterday. The update process _should_ start working by itself within the next few hours.

For future reference, you can pass `--reinstall` to the kickstart script (with otherwise identical options to what you used on the initial install) to skip attempting to run the updater and just do a regular install over top of your existing install (though this still preserves any data and configuration you already have).

**Comment by stdedos** [comment]
Oh yeah, I forgot `--reinstall`; I should add it to my bash-history.

_Please_ try to be more careful/test more extensively that `/etc/cron.daily/netdata-updater` script!
It's not fun to keep debugging what's wrong with it.

Or - just publish deb packages (and whatever else ofc)

**Comment by Ferroin** [comment]
> Oh yeah, I forgot `--reinstall`; I should add it to my bash-history.
> 
> _Please_ try to be more careful/test more extensively that `/etc/cron.daily/netdata-updater` script!
> It's not fun to keep debugging what's wrong with it.

Believe me, we’re not fond of debugging issues with it either.
 
> Or - just publish deb packages (and whatever else ofc)

See https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages

**Comment by stdedos** [comment]
If I replace my version now, will the deb package pick up where the installed version left off?

**Comment by Ferroin** [comment]
Unfortunately no, you would have to uninstall the existing copy of Netdata and then install the DEB package. If you do go that route, make sure to back up any configuration (in `/etc/netdata`) or data (in `/var/lib/netdata` and `/var/cache/netdata`) you want to keep, as the uninstaller will remove it.

**Comment by stdedos** [comment]
Whoever tries to be smart after me:
Preserve the `/var/lib/netdata/www` folder if you go for in-place replace
