### ISSUE TITLE
opensips module require opensipsctl command

### ISSUE THREAD

**Issue by aldotms70** [netdata/netdata#10947]
##### Bug report summary

require_cmd to find opensipsctl is unsed in opensips_check function.

##### OS / Environment
all

```

```

##### Netdata version
all

##### Steps To Reproduce

1. Do not configure opensips.conf
2. opensipsctl is available with 'which' command

##### Expected behavior
require_cmd find the opensipsctl command with path and valorize opensips_cmd=$OPENSIPSCTL_CMD after line 33.

**Comment by ilyam8** [comment]
Hi @aldotms70, are you willing to make a PR with the fix?
