### ISSUE TITLE
mysql.galera_cluster_state alarm improvement

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#10940]
##### Bug report summary

mysql.galera_cluster_state alarm introduced in issues #6962 and #6934.
It includes 5 statuses:
```
template: mysql_galera_cluster_state
      on: mysql.galera_cluster_state
  lookup: average -10s
   every: 10s
    warn: $this < 4
    crit: $this < 2
   delay: up 30s down 5m
    info: node state (0: undefined, 1: joining, 2: donor/desynced, 3: joined, 4: synced)
      to: dba
```
_Originally posted by @ekexcello in https://github.com/netdata/netdata/issues/6962#issuecomment-537002612_

However, it was recently found that status _5 - inconsistent_ is missing in this alarm. Difference is minimal and final alarm looks as follows:
```
template: mysql_galera_cluster_state
      on: mysql.galera_cluster_state
  lookup: average -10s
   every: 10s
    warn: $this != 4
    crit: ($this < 2) OR ($this > 4)
   delay: up 30s down 2m multiplier 1.5 max 30m
    info: node state (0: Undefined, 1: Joining, 2: Donor/desynced, 3: Joined, 4: Synced, 5: Inconsistent)
      to: dba
```
diff:
```
       on: mysql.galera_cluster_state
   lookup: average -10s
    every: 10s
-    warn: $this < 4
-    crit: $this < 2
+    warn: $this != 4
+    crit: ($this < 2) OR ($this > 4)
    delay: up 30s down 2m multiplier 1.5 max 30m
-    info: node state (0: undefined, 1: joining, 2: donor/desynced, 3: joined, 4: synced)
+    info: node state (0: Undefined, 1: Joining, 2: Donor/desynced, 3: Joined, 4: Synced, 5: Inconsistent)
       to: dba
```

##### OS / Environment
```
Linux  5.10.27-gentoo x86_64 AMD EPYC 7451
Gentoo Base System release 2.7
```
##### Netdata version
```
netdata v1.29.3
```
##### Installation method

Installed from portage (emerge)

##### Component Name

Health

**Comment by ilyam8** [comment]
Hi @ekexcello 

Check this https://github.com/codership/wsrep-API/blob/eab2d5d5a31672c0b7d116ef1629ff18392fd7d0/wsrep_api.h#L256-L262

```c
typedef enum wsrep_member_status {
    WSREP_MEMBER_UNDEFINED, //!< undefined state
    WSREP_MEMBER_JOINER,    //!< incomplete state, requested state transfer
    WSREP_MEMBER_DONOR,     //!< complete state, donates state transfer
    WSREP_MEMBER_JOINED,    //!< complete state
    WSREP_MEMBER_SYNCED,    //!< complete state, synchronized with group
    WSREP_MEMBER_ERROR,     //!< this and above is provider-specific error code
    WSREP_MEMBER_MAX
} wsrep_member_status_t;
```

There is another state, indeed. It is `ERROR`, i am not sure what `this and above is provider-specific error code` means 🤔 

Where did you find `Inconsistent`?

---


```
    warn: $this != 4
    crit: ($this < 2) OR ($this > 4)
```

Do you mean the following:
 - OK: SYNCED
 - WARN: JOINED
 - CRIT: any other

?

**Comment by ilyam8** [comment]
That is [wsrep_local_state_comment](https://www.percona.com/doc/percona-xtradb-cluster/8.0/wsrep-status-index.html#wsrep_local_state_comment) description.

> Internal number and the corresponding human-readable comment of the node’s state. Possible values are:


Num | Comment | Description
-- | -- | --
1 | Joining | Node is joining the cluster
2 | Donor/Desynced | Node is the donor to the node joining the cluster
3 | Joined | Node has joined the cluster
4 | Synced | Node is synced with the cluster

**Comment by ekexcello** [comment]
Hello @ilyam8 
> 
> Check this https://github.com/codership/wsrep-API/blob/eab2d5d5a31672c0b7d116ef1629ff18392fd7d0/wsrep_api.h#L256-L262
> 
> There is another state, indeed. It is `ERROR`, i am not sure what `this and above is provider-specific error code` means thinking
> 
> Where did you find `Inconsistent`?

One of our nodes went into this state after flapping networking issues, here's the output:
```
MariaDB [(none)]> show status like 'wsrep_cluster%'; show status like 'wsrep_local_state%';
+----------------------------+--------------------------------------+
| Variable_name              | Value                                |
+----------------------------+--------------------------------------+
| wsrep_cluster_capabilities |                                      |
| wsrep_cluster_conf_id      | 12345678901234567890                 |
| wsrep_cluster_size         | 0                                    |
| wsrep_cluster_state_uuid   | 00000000-0000-0000-0000-000000000000 |
| wsrep_cluster_status       | Disconnected                         |
+----------------------------+--------------------------------------+
5 rows in set (0.001 sec)

+---------------------------+--------------------------------------+
| Variable_name             | Value                                |
+---------------------------+--------------------------------------+
| wsrep_local_state_uuid    | 00000000-0000-0000-0000-000000000000 |
| wsrep_local_state         | 5                                    |
| wsrep_local_state_comment | Inconsistent                         |
+---------------------------+--------------------------------------+
```
So, this is really `Error`. Probably, WSREP developers reserved these statuses for some reason. In this state node fall out of cluster and doesn't replicate transactions to others anymore while WSREP library itself remains initialized. So if some information will be written on this node, it will be lost as this node can join the cluster only with full state transfer (wiping local data before).

> Do you mean the following:
> 
>     * OK: SYNCED
Correct
>     * WARN: JOINED
Warn: "JOINING" or "DONOR/DESYNCED"
>     * CRIT: any other
everything that is not "SYNCED, JOINING or DONOR/DESYNCED"
So, `0,1,5` - critical; `2,3` - warning; `5` - ok.

**Comment by ilyam8** [comment]
So what do you think? We call it `Error`? 🤔 

We need to update also

https://github.com/netdata/netdata/blob/53b51bc800a445668f9e66995b0c20977bcf7819/web/gui/dashboard_info.js#L1506-L1513

**Comment by ekexcello** [comment]
As it was called "inconsistent" in galera output, it might be probably better to call it also `inconsistent`. However, `Error` also describes the case. 

BTW, according to
```
    WSREP_MEMBER_SYNCED,    //!< complete state, synchronized with group
    WSREP_MEMBER_ERROR,     //!< this and above is provider-specific error code
    WSREP_MEMBER_MAX
```
in case WSREP library is provided not by Galera, but by something else (for instance, Percona), status `5` can have different description and there can be more statuses, but only first five (0-4) might be same for different library vendors.
