### ISSUE TITLE
high netdata cpu usage

### ISSUE THREAD

**Issue by Whisper40** [netdata/netdata#10952]
##### Bug report summary

After fews days that netdata works, netdata is the service that consumes a the most when no users are on my server.
Netdata is consuming around 5-8% all the time. I think it's really too much for a monitoring tool.
##### OS / Environment
Docker installation, stable version. (Last pushed9 days agobynetdatabot)
##### Netdata version
stable version. (Last pushed9 days agobynetdatabot)

##### Installation method
Docker

##### Step to reproduce

1. Just a basic installation with Netdata/ Netdata cloud/ And discord notification

##### Expected behavior
I think that it should be really less.
A rutorrent container with 1800 torrents is consuming at the time 3%...

![bugnetdata](https://user-images.githubusercontent.com/30440458/114199452-9b7e9980-9954-11eb-8619-bcdc55421866.gif)

Docker stats showing highter values than what netdata is saying.
Who say right and why ?
![image](https://user-images.githubusercontent.com/30440458/114264042-e944e180-99e8-11eb-91b5-88881cc60c77.png)

**Comment by ilyam8** [comment]
Hi @Whisper40 

Can you send [a snapshot](https://learn.netdata.cloud/guides/step-by-step/step-07#export-and-import-a-snapshot) to the ilya@netdata.cloud ?

**Comment by ilyam8** [comment]
Oh, you can check netdata components metrics (including cpu usage) under `Netdata Monitoring` metrics.

**Comment by Whisper40** [comment]
Hi @ilyam8 I sent it !

**Comment by ilyam8** [comment]
@Whisper40 i got it, i see

- netdata uses 2.5% of one core in average and spiked to 6% (`apps.cpu`)
- netdata collects 5k+ metrics every seconds
- there are 417 alarms

There is 30+ running containers on the system and i assume you create/remove them from time to time (i see there is cpu spike up to 50% for `containers` dimensions on the `apps.cpu` every ~2minutes).

I see from 10 to 50 new started processes on your system every second (`system.forks`) and 2100+ active proccesses in average. => `apps.plugin` (external collector) uses quite a while - 3-4% of 1 core.

So netdata + apps.plugin = 5-8%. Taking into accound amount of metrics (5k+) and data collection frequency (1 second) it is not that bad.

---

How often do you remove/create containers?

**Comment by Whisper40** [comment]
Containers are recreated only when upgrade are found each night at 4:00am (Europe/Paris)
( Today multiple containers have been recreated for testing purpose).

Actually there is not a lot of containers, i think there will be 3 times the actual value in the future.
Can i select to request the metrics only every 10 seconds ?

**Comment by Whisper40** [comment]
I set my netdata.conf to : 
```
[global]
    update every = 10
```

Result : 
Every 10 seconds, Netdata collects 2 032 metrics on s10, presents them in 536 charts and monitors them with 324 alarms.

**Comment by ilyam8** [comment]
Reason is that it takes some time to discover all the running containers. In your case it takes more then 10 seconds.

**Comment by ilyam8** [comment]
@Whisper40 from what i've seens `apps.plugin` consumes _a lot_ of cpu due to number of active processes. You can start from increasing only its `update every`.

If you don't really need _real-time_ metrics, then increasing global `update every` works too.

**Comment by ilyam8** [comment]
@Whisper40 as we've figured out it is not a bug. CPU usage you have is expected. But it doesn't mean we won't be working on improving netdata performance.
