### ISSUE TITLE
Plugins not working anymore after nightly update.

### ISSUE THREAD

**Issue by Tommuh** [netdata/netdata#10958]
Version: v1.30.0-18-nightly

Since the last update some plugins aren't working any more.
Debug log stays empty, error log says nothing unusual.

The data gets pushed to one server that collects all metrics. 
All the servers (Ubuntu 18.04) have the same new version installed.

Plugins that don't work any more but do work sporadically but mostly not:

- Apache
- Fail2Ban
- MySQL
- Postfix
- PHP-FPM

What is working:

- System overview
- CPUs
- Memory
- Disks
- Networking Stack
- IP4v Networking
- IP6v Networking
- Network Interfaces
- Firewall (netfilter)
- systemd Services
- Applications
- User Groups
- Users
- eBPF
- Redis
- Netdata Monitoring

I tried restarting Netdata on all servers but this doesn't do much. Any ideas what I can do?

**Comment by Tommuh** [comment]
I think I'm becoming insane - it suddenly works again after 20+/- minutes ...

**Comment by stelfrag** [comment]
Hi @Tommuh 

Thank you for reporting this. Did you notice that the parent node was not updating or the children (or both?)

**Comment by stelfrag** [comment]
Inconclusive. Will revisit if it is observed again
