### ISSUE TITLE
Information about memory used by kernel is incomplete

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#10960]
##### Bug report summary

While debugging the eBPF plugin, we realized that it consumes much more memory than reported by Netdata and most of it is allocated by the kernel (related issues: #10949, [Netdata consuming high ram amount](https://community.netdata.cloud/t/netdata-consuming-high-ram-amount/1005)). The sum of memory allocated by processes and kernel memory doesn't match the total used memory. The missing part is percpu memory that is actively used by [eBPF and other subsystems](https://patchwork.kernel.org/project/linux-mm/patch/20180807005607.53950-1-dennisszhou@gmail.com/).

##### OS / Environment

Arch Linux 5.11.13-arch1-1

##### Netdata version

netdata v1.30.0-18-g8bc32ad6e

##### Component Name

proc plugin

##### Expected behavior

The `mem.kernel` chart displays information about percpu memory.

**Comment by ilyam8** [comment]
A little note: meminfo->Percpu not always in place, we shouldn't create a dimension (or create a chart?) if there is no such metric.

Some examples:

| Distro      | Kernel            | meminfo->Percpu exists |
| ----------- | ----------------- |------------------------|
| Debian      | 4.9.0-8-amd64     | no                     |
| Debian      | 4.19.0-13-amd64   | yes                    |
| Manjaro     | 5.10.26-1-MANJARO | yes                    |
