### ISSUE TITLE
Why netdata conflicts with kubernetes dashboard, when the netdata service started, my k8s-dashboard (with port: 31779) cannot access

### ISSUE THREAD

**Issue by OneCodeMonkey** [netdata/netdata#10963]
Why netdata conflicts with kubernetes dashboard, when the netdata service started, my k8s-dashboard (with port: 31779) cannot access.

When I stop the service `systemctl stop netdata`，then k8s dashboard can access :(

Is anybody have the same problem?

**Comment by ilyam8** [comment]
Hi @OneCodeMonkey 

Can you provide us more details about your setup, what's that dashboard, netdata version, netdata installation method, etc. There is [a template when you create a bug report](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md) - could you fill it?.

**Comment by OneCodeMonkey** [comment]
> Hi @OneCodeMonkey
> 
> Can you provide us more details about your setup, what's that dashboard, netdata version, netdata installation method, etc. There is [a template when you create a bug report](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md) - could you fill it?.
> 
> Netdata listens on 19999 and 8125 (statsd) by default.
> 
> > then k8s dashboard can access
> 
> You mean you access it and get what response?

access k8s dashboard via https://{IP}:31779，cannot connect.
Once stop the netdata.service,  it can be browsered.

**Comment by OneCodeMonkey** [comment]
Oh，my fault. I tried to restart and the two dashboard works well.
Thks  : )

**Comment by ilyam8** [comment]
@OneCodeMonkey np, nice you get it working 🎉 

If there are any question consider to use our [community forum](https://community.netdata.cloud/).
