### ISSUE TITLE
(ebpf.plugin) `mem.cachestat_ratio` chart has gaps

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#10967]
##### Bug report summary

ssia

<img width="1148" alt="Screenshot 2021-04-13 at 00 25 05" src="https://user-images.githubusercontent.com/22274335/114464640-b3714a00-9bee-11eb-9f3d-9914d382be6c.png">

##### OS / Environment

```
Linux pc 5.10.26-1-MANJARO #1 SMP PREEMPT Thu Mar 25 16:56:17 UTC 2021 x86_64 GNU/Linux
```

<details>
<summary>/etc/release [Click]</summary>

```cmd
/etc/arch-release:Manjaro Linux
/etc/lsb-release:DISTRIB_ID=ManjaroLinux
/etc/lsb-release:DISTRIB_RELEASE=21.0.1
/etc/lsb-release:DISTRIB_CODENAME=Ornara
/etc/lsb-release:DISTRIB_DESCRIPTION="Manjaro Linux"
/etc/manjaro-release:Manjaro Linux
/etc/os-release:NAME="Manjaro Linux"
/etc/os-release:ID=manjaro
/etc/os-release:ID_LIKE=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:PRETTY_NAME="Manjaro Linux"
/etc/os-release:ANSI_COLOR="32;1;24;144;200"
/etc/os-release:HOME_URL="https://manjaro.org/"
/etc/os-release:DOCUMENTATION_URL="https://wiki.manjaro.org/"
/etc/os-release:SUPPORT_URL="https://manjaro.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.manjaro.org/"
/etc/os-release:LOGO=manjarolinux
```

</details>

##### Netdata version

`Version: netdata v1.30.1-1-g3bab9bb7`

<details>
<summary>buildinfo [Click]</summary>

```cmd
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-cloud' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           NO (by user request)
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES shared-lib
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

</details>

##### Installation method

From source.

##### Component Name

`collectors/ebpf.plugin`

##### Steps To Reproduce

1. enable `cachestat` in the `ebpf.d.conf`
2. restart netdata service, see `Memory->page cache (eBPF)->mem.cachestat_ratio` chart

##### Expected behavior

`mem.cachestat_ratio` has no gaps.

---

 - if we have no events, then we need to treat it as 100% hit rate (no misses)

https://github.com/netdata/netdata/blob/3bab9bb7b16d90471a4ee04843dd4e97116e8e17/collectors/ebpf.plugin/ebpf_cachestat.c#L128

 - if the ratio is 0, we need to show it. We don't need `if` here: 

https://github.com/netdata/netdata/blob/3bab9bb7b16d90471a4ee04843dd4e97116e8e17/collectors/ebpf.plugin/ebpf_cachestat.c#L388-L393

**Comment by thiagoftsm** [comment]
You are completely right about your suggestion, we set the variable to zero and we added the condition before to send data to keep compatibility with other tools, but I do not have objections to change it.

**Comment by ilyam8** [comment]
> keep compatibility with other tools

The tools you are referring to:
 1. doesn't show hit rate if it is 0%
 2. treat hit rate as 0% when total number of events is 0 (and doesn't show it see 1.)

Is that correct? I really doubt 1st and not really agree with 2nd.

- 0 is a valid value, it is ok to have 0% hit rate, it means there are only misses.
- i can see you confusion with setting hit rate to 100% when there are 0 events. No hits/misses, how can hit rate be 100%? What if i say you that miss rate is 0, does it sounds good? If so, then `hit rate = 1 - miss rate` => 1 => 1 * 100 = 100%

Let's ask @Ferroin to comment on the subject so we have one more opinion.

---

In my opinion _compatibility with the tools_ is not strong enough argument to have the chart with gaps. 

Anyway would be interesting to see a tool (you want to be compatible with) output example.

**Comment by thiagoftsm** [comment]
Running on the latest kernel compiled to have `CO-RE` it has the following output on my environment:

```bash
3 warnings generated.
    HITS   MISSES  DIRTIES HITRATIO   BUFFERS_MB  CACHED_MB
       0        0       34    0.00%          164       1995
       0        0      137    0.00%          164       1995
       0        0        0    0.00%          164       1995
      20        0       20  100.00%          164       1995
       0        0        0    0.00%          164       1995
       0        0        0    0.00%          164       1994
       0        0        0    0.00%          164       1994
       0        0        0    0.00%          164       1994
^C       0        0        0    0.00%          164       1994
```

We are not using 100% the same algorithm, because I already did some modifications to have a smooth chart, but you can see it [here](https://github.com/iovisor/bcc/blob/master/tools/cachestat.py).

**Comment by ilyam8** [comment]
> because I already did some modifications to have a smooth chart

You mean those gaps, correct? I see calculation is exactly the same (total, hits, misses).

**Comment by thiagoftsm** [comment]
> > because I already did some modifications to have a smooth chart
> 
> You mean those gaps, correct? I see calculation is exactly the same (total, hits, misses).

Yes, the original generates a lot of gaps.

**Comment by vlvkobal** [comment]
Hit ratio = 0% looks like a problem, but it is not if the number of misses equals 0. Compare, for example, two cases
```
hits = 0, misses = 0
```
and
```
hits = 0, misses = 1000
```
Using your algorithm the ratio for both cases will be `0%`. Do you feel the catch?

I think having `ratio = 100%` for `hits = 0, misses = 0` is more logical.

**Comment by ilyam8** [comment]
**if** there is requirement to show same values as [cachestat.py](https://github.com/iovisor/bcc/blob/21d866e2d70fa737c8ffd0f63523450bd3cd79d9/tools/cachestat.py#L153-L154) script, then we need to show 0%. I don't understand how making gaps makes it more compatible and charts more _smooth_ 🤷‍♂️

**Comment by vlvkobal** [comment]
> if there is requirement to show same values as cachestat.py script

Why it should be? I believe Logic is more important than compliance with the script.

**Comment by thiagoftsm** [comment]
> I think, having ratio = 100% for hits = 0, misses = 0 is more logical.

I agree with you, when I was working with the collector, I never liked the original result, this was the motive I made some changes.
