### ISSUE TITLE
Add netdata uptime metric and export it as a special (global) variable (health)

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#10968]
##### Feature idea summary

Idea is to add netdata process uptime chart to the `Netdata Monitoring->netdata`. It will allow us to see if the netdata process was restarted.

In addition i suggest to export netdata process uptime as [a health special variable](https://learn.netdata.cloud/docs/agent/health/reference#variables) (e.g `$uptime` or `$nd_uptime`). It would be very handy in some alarms (e.g: don't trigger for N minutes after netdata restart). [Netdata update triggers ipv4.tcphandshake alerts](https://github.com/netdata/netdata/issues/9799) issue is a good example.

##### Expected behavior

- new chart `Netdata Monitoring->netdata->uptime`
- new health global variable `$uptime` or `$nd_uptime`.

Keep in mind that this is just an idea, if there are any problems with it feel free to comment.

**Comment by ilyam8** [comment]
@vlvkobal @thiagoftsm what do you think, guys?

**Comment by thiagoftsm** [comment]
> @vlvkobal @thiagoftsm what do you think, guys?

I think it makes sense, because we also have a chart monitoring how long the computer is up `system.uptime`, this additional information would give for users how long their system ran without monitoring.

**Comment by Ferroin** [comment]
Agreed, being able to determine downtime on the Netdata agent itself is exceedingly useful.

Additionally, being able to have alarms behave differently just after a restart is exceedingly useful (perhaps we should also export the system updtime as a special variable for alarms to look at for similar reasons), and it would also be useful to be able to warn on a restart of the agent without an associated system restart (though I do not think we should provide such an alarm by default).

**Comment by stelfrag** [comment]
This is good to have !!! We will need to have that information also on the parent for all the children.

**Comment by vlvkobal** [comment]
The idea is to add a separate internal plugin for Netdata uptime and make it impossible to disable it. We don't need the health variable because we can access the value from the `netdata.uptime` chart in alarms.

**Comment by ilyam8** [comment]
> we can access the value from the netdata.uptime chart

That sounds good!

**Comment by ilyam8** [comment]
Ok, looks like netdata global statistics is actually a module of the proc plugin

https://github.com/netdata/netdata/blob/27552389682e7162b52ea1a69683f2e457ad2dff/collectors/proc.plugin/plugin_proc.c#L189

We decided to try to move it out from proc and make it a separate plugin. Then we can easily add netdata process uptime to it.

This will fix https://github.com/netdata/netdata/issues/10510
