### ISSUE TITLE
Netdata 1.30.1 - mqtt_websockets compilation issue (gcc dep hardcoded and openssl pc requirement)

### ISSUE THREAD

**Issue by diizzyy** [netdata/netdata#10971]
The following can be found in ```mqtt_websockets/Makefile``` 
```
CC = gcc -std=gnu99
CFLAGS = -Wextra -Wall `pkg-config --cflags openssl`
```
This breaks compilation on any platform that doesn't ship gcc (FreeBSD for example) or doesn't call it gcc.
Regarding openssl, why doesn't it use parameters set by configure script?

**Comment by underhood** [comment]
Hi @diizzyy yes you are right this is not the best way to do this. I have a patch incoming which switches mqtt_websockets to use autotools. Not sure though how quickly can we release it.

**Comment by diizzyy** [comment]
Sounds great, thanks!
This issue can also be seen in c-rbuf/Makefile
From what I tell this also seems to override global cflags but I guess this will be fixed by the autotools integration.

**Comment by underhood** [comment]
Yep indeed same goes for `c-rbuf` or anything under `mqtt_websockets`

**Comment by diizzyy** [comment]
Great, thanks!

**Comment by underhood** [comment]
@diizzyy  Thanks as well for reporting. It helps a lot to hear back from users.

**Comment by diizzyy** [comment]
Perhaps it would be an idea to add a FreeBSD CI to avoid similar issues in the future. The Gerbera project seems to have one running for instance.
