### ISSUE TITLE
Can’t Remove

### ISSUE THREAD

**Issue by stavro-venustech** [netdata/netdata#10983]
Hi,
I love net data. But it got corrupted so i used the uninstaller. After running it i have found out that I can't update/install/purge/autoremove files (anything to do with apt) the file causing all the probems is libpython3.7-dev. Please Help. Im running Raspbian.

##### OS / Environment

```

```

##### Steps To Reproduce

1. ...
2. ...

**Comment by stavro-venustech** [comment]
Every time i try to delete the file it says structure needs cleaning. I am not willing to reflash

**Comment by stavro-venustech** [comment]
fixed it by doing sudo shutdown -F -r now

**Comment by ilyam8** [comment]
Hi @stavro-venustech 

Nice that you managed to fix the problem 👍
