### ISSUE TITLE
Health parser

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#10996]
##### Bug report summary
The health files accepts backslash to indicate that next line is continuation of the current according the following code:

https://github.com/netdata/netdata/blob/a3c46ef3ec305bb2fa0e8f64e87e9ac8b99d6714/health/health_config.c#L555

but, this code is not expecting alarms like this:

```conf
   alarm: my_example
      on: example_python_example.random
   units: boolean
  lookup: sum -3s foreach *
    warn: $this > 200
    crit: $this > 250
   every: 20s\
#  repeat: warning 15s critical 10s
  module: example\
    info: Testing repeat\
      to: sysadmin
```

when this alarm is given to Netdata, it concatenates all 5 lines to `every`.

We need to update the parser to verify if next line is really a continuation of the current, or it is another keyword.

Our documentation also needs to be updated

##### OS / Environment

```
All operate systems
```

##### Netdata version

This is an ancient bug also present in the latest version

##### Installation method
Any method

##### Component Name

Health
Documentation

##### Steps To Reproduce
Write an alarm appending backslashes to the end of lines.

##### Expected behavior

To have a parser that won't ignore lines when backslashes are appended.

**Comment by vlvkobal** [comment]
Why do you think this is a bug? Why should we ignore backslashes at the end of a line? We use them by design or don't. I don't like the idea of adding magic to the configuration logic.

BTW, our documentation should be updated anyway - there is nothing about backslashes.

**Comment by stelfrag** [comment]
@MrZammler 

As we need to build and maintain a hash for the config we need to take this into account

**Comment by ilyam8** [comment]
For me it looks like lack of documenation about the health entity multiline value _feature_.

I suggest we add it:
 - to the https://learn.netdata.cloud/docs/agent/health/reference#entity-format (Entity format general section, as a additional point to the list)
 - or as a separate subsection if we want to make it more explicit (Entity types, Entity format, **Entity multiline value**).

---

Still, if there is a value, we can handle it during parsing:
 - if the entity value ends with `/` we treat the value as multiline
 - if the next line after `/` starts with [well-known keyword](https://github.com/netdata/netdata/blob/c166feb572ead175ffd64fab3fec0603f87abeb6/health/health_config.c#L7-L29) we don't treat it as the value.

**Comment by thiagoftsm** [comment]
> Why do you think this is a bug? Why should we ignore backslashes at the end of a line? We use them by design or don't. I don't like the idea of adding magic to the configuration logic.

I do not think to ignore is the correct, I think we need to take a look in the next line and verify if it is a continuation, or there was a typo error, and the next line is another entity.

> BTW, our documentation should be updated anyway - there is nothing about backslashes.

I agree.
