### ISSUE TITLE
[question] does the offline static build for centos 6 make use of external optional rpms?

### ISSUE THREAD

**Issue by mailinglists35** [netdata/netdata#11008]
If I use [offline method](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/offline) for an offline centos 6, do I still need the [optional rpms](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual#centos-rehel-6-x) `liblz4`, `Judy`and `openssl`, or is their functionality already included in the static build?

sorry to post here, but attempting to use https://community.netdata.cloud is [total waste of time](https://community.netdata.cloud/t/impossible-to-post-topic/1117/5)

**Comment by OdysLam** [comment]
Everything is included in the offline method.

in the forums, the forum software actually protects us from SPAM, I really don't know why it didn't let you post, but this is happening on rare occasions that it deems that the user could be a bot. 

Looking forward to seeing you in the forums, as GitHub is only used for bug tracking 😇
