### ISSUE TITLE
 compare the performance of MySQL on two machines in one chart

### ISSUE THREAD

**Issue by hope1234567hope** [netdata/netdata#11016]
How to display MySQL information on two machines in the same time period in one chart? To give a simple way to implement this, I would like to compare the performance of MySQL on two machines

**Comment by andrewm4894** [comment]
You could claim both nodes using netdata cloud and then the default charts on the space overview screen would be an aggregation over both machines.

**Comment by hope1234567hope** [comment]
sorry,My network cannot access the netdata cloud。have  other  way?

**Comment by hope1234567hope** [comment]
My test environment can connect to netdata cloud。 
now  my  netdata version: v1.30.1
and   .environment  file  IS_NETDATA_STATIC_BINARY="no"

but in   netdata cloud ，in "Node Name" say:
“Agent needs update
Please update your agent to the version 1.26 to use the new Cloud Overview! ”            why???????

**Comment by ilyam8** [comment]
@hope1234567hope, hey 👋 if you have a problem with connecting Netdata Agent to the Cloud consider using our [community forum](https://community.netdata.cloud/c/metrics-alerts-insights/10) or [Discord server](https://discord.gg/mPZ6WZKKG2).
