### ISSUE TITLE
Can not update to aclk-ng using latest v1.30.1-76 and kickstart-static64.sh

### ISSUE THREAD

**Issue by nicknaychov** [netdata/netdata#11018]
Hi
I am running latest v1.30.1-76 on CentOS and when I try to update to aclk-ng
`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --aclk-ng
Unknown option '--aclk-ng' or invalid number of arguments. Please check the README for the available arguments of /dev/fd/63 and try again`

in error log:
`2021-04-23 08:24:21: netdata ERROR : ACLK_Query_0 : ACLK version negotiation failed. No reply to "hello" with "version" from cloud in time of 3s. Reverting to default ACLK version of 2.`

I suspect that option is still not implemented in kickstart-static64.sh. Any chance to be added?

Thanks

##### OS / Environment

```

```

##### Steps To Reproduce

1. ...
2. ...

**Comment by ilyam8** [comment]
@nicknaychov, hey. ACLK-NG is included in the static build, there is no need to add that parameter.
