### ISSUE TITLE
Telegram notifications don't work

### ISSUE THREAD

**Issue by thegamerrrr** [netdata/netdata#11023]
Hi, I set everything in the file for notifications in fact when I try to run the test using the command it works and i receive the test notifications on telegram, but then I don't receive the real notifications, am I wrong or I forget something?

**Comment by ilyam8** [comment]
Hi @thegamerrrr 

That sounds like a bug, but there is not enough information to be sure.

Please format your post [according to the bug report template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md).

**Comment by thegamerrrr** [comment]
##### Bug report summary

Hi, I set everything in the file for notifications in fact when I try to run the test using the command it works and i receive the test notifications on telegram, but then I don't receive the real notifications

##### OS / Environment

Place the output from the command in the code section below.  
 -->

/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic


##### Netdata version


Version: netdata v1.30.1-79-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO

##### Component Name

Health notifications

##### Steps To Reproduce

1. Set all the informations for the telegram notifications
2. Test the notifications with the command in the faq
3. Wait for a real notification

##### Expected behavior

Receive the notifications of the alerts

**Comment by ilyam8** [comment]
@thegamerrrr thanks!

> Receive the notifications of the alerts

I guess you see some alarms are active on the dashboard, but there are no notifications? What alarms are you referring to?

**Comment by ilyam8** [comment]
Asking because there is [delay](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) option. I suspect it could be the reason you don't receive notifications.

**Comment by thegamerrrr** [comment]
Yes, i don't receive no one notification even if in the dashboard are actives

**Comment by ilyam8** [comment]
> if in the dashboard are actives

What notifications are active in your case?

---

Anyway, let's check `error.log`. Usually, it is a good place to start with

> grep "send telegram" /var/log/netdata/error.log

**Comment by thegamerrrr** [comment]
2021-04-25 02:54:04: go.d ERROR: prometheus[telegram_bot_for_alertmanager_local] Get "http://127.0.0.1:9087/metrics": dial tcp 127.0.0.1:9087: connect: connection refused
2021-04-25 02:54:04: go.d ERROR: prometheus[telegram_bot_for_alertmanager_local] check failed

This is the unique error that contain the "telegram" word

**Comment by thiagoftsm** [comment]
Hello @thegamerrrr ,

I remember when I was reviewing the telegram original PR, I had an initial problem to generate the key, but everything was OK after to fix this problem, My  `health_alarm_notify.conf` is configured with parameters like these:

```
SEND_TELEGRAM="YES"

TELEGRAM_BOT_TOKEN="000000000:AAAAAAAAAAA-XXXXXXXXXXXXXXXXXXXXXX"

DEFAULT_RECIPIENT_TELEGRAM="-999999999"
```

please, pay attention that the token has the format `9 numbers:11 letters and numbers-22 letters and numbers`, and my default recipient is a negative value with  9 bytes length.

**Comment by thegamerrrr** [comment]
I already set all the informations, in fact when i send the command to test the notifications it works
https://i.imgur.com/lnEwspr.jpg

**Comment by ilyam8** [comment]
We log `sent telegram`/`failed to send telegram` when sending telegram notifications

https://github.com/netdata/netdata/blob/ac92f8c910ba79ecb0f3ee03727d336996fa664b/health/notifications/alarm-notify.sh.in#L1306-L1313

---

I am trying to figure out what alarms are active - perhaps those with `to: silent` or `delay: ...`...

**Comment by thegamerrrr** [comment]
I am trying again to send notifications and now the ssh send, like 700 strings:

/etc/netdata/health_alarm_notify.conf: line 835: $'\r': command not found
/etc/netdata/health_alarm_notify.conf: line 838: $'\r': command not found
/etc/netdata/health_alarm_notify.conf: line 842: $'\r': command not found
/etc/netdata/health_alarm_notify.conf: line 844: syntax error near unexpected token `$'{\r''
'etc/netdata/health_alarm_notify.conf: line 844: `custom_sender() {
2021-05-02 21:17:27: alarm-notify.sh: ERROR: Failed to load config file '/etc/netdata/health_alarm_notify.conf'.
2021-05-02 21:17:27: alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host 'markvm.it', chart 'test.chart' to 'sysadmin' for 'test_alarm' = '100' for status 'CLEAR'.
+ '[' 1 -ne 0 ']'
+ echo '# FAILED'
# FAILED
+ test_res=1
+ last=CLEAR
+ id=4
+ exit 1


But the file was just copied

**Comment by thiagoftsm** [comment]
> I am trying again to send notifications and now the ssh send, like 700 strings:
> 
> /etc/netdata/health_alarm_notify.conf: line 835: $'\r': command not found
> /etc/netdata/health_alarm_notify.conf: line 838: $'\r': command not found
> /etc/netdata/health_alarm_notify.conf: line 842: $'\r': command not found
> /etc/netdata/health_alarm_notify.conf: line 844: syntax error near unexpected token `$'{\r'' 'etc/netdata/health_alarm_notify.conf: line 844: `custom_sender() {
> 2021-05-02 21:17:27: alarm-notify.sh: ERROR: Failed to load config file '/etc/netdata/health_alarm_notify.conf'.
> 2021-05-02 21:17:27: alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host 'markvm.it', chart 'test.chart' to 'sysadmin' for 'test_alarm' = '100' for status 'CLEAR'.

It looks like that `/etc/netdata/health_alarm_notify.conf` was edited with a windows editor, because their editors use `\r` as break line. How did you edit your config file?
