### ISSUE TITLE
Errors on every restart with current statsd.d/k6.conf

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#11026]
##### Bug report summary

Every restart of netdata I get the following errors:
```
netdata ERROR : STATSD : STATSD: invalid type 'avg' at line 56 of file '/usr/lib/netdata/conf.d/statsd.d/k6.conf'. Using 'last'. (errno 2, No such file or directory)
netdata ERROR : STATSD : STATSD: invalid type 'avg' at line 102 of file '/usr/lib/netdata/conf.d/statsd.d/k6.conf'. Using 'last'.

```

##### OS / Environment

```

```

##### Component Name

 netdata/collectors/statsd.plugin/statsd.c 

##### Steps To Reproduce

1. ...
2. ...

##### Expected behavior
It looks like there is a typo in statsd.plugin where the type on on lines # 1048, 1064, 1632 should be `avg` rather than `average`.
The error message is created on line# 1053 of `collectors/statsd.plugin/statsd.c`
The files `collectors/statsd.plugin/k6.conf` and the `docs/guides/monitor/statsd.md` files have `avg` as their types so I am assuming that was what was meant to be in statsd.c

**Comment by ilyam8** [comment]
@Steve8291 thanks for reporting the bug!

You are right, it is not `avg` but `average`

https://github.com/netdata/netdata/blob/5ddc1be576cec218b39387928325624e04e66f13/collectors/statsd.plugin/statsd.c#L1044-L1051

@OdysLam let's get it fixed in https://github.com/netdata/netdata/pull/10985 ?

**Comment by OdysLam** [comment]
Hey @Steve8291 , thanks for reporting this. it's indeed a typo on my part. 

Mea culpa. Fixing it asap
