### ISSUE TITLE
installer failed

### ISSUE THREAD

**Issue by GamerAtlantis** [netdata/netdata#11027]
When I try to do the commands to link it to the website I am getting command not found can I link it any over way

**Comment by ilyam8** [comment]
Hi @GamerAtlantis 👋 

Could you elaborate a bit on the problem?

> I try to do the commands to link it to the website I am getting command not found

If you do something in the terminal, can you copy/paste the output? Or at least a screenshot?

**Comment by GamerAtlantis** [comment]
When I tryed to link the node to the dashbord with the code what I get off the websites after setting an account up. It is nort finding the code on my vps.

**Comment by ilyam8** [comment]
Do you mean when you try to [claim your node](https://learn.netdata.cloud/docs/agent/claim#how-to-claim-a-node)?

And show `ps faxu | grep "[n]etdata"` output

**Comment by ilyam8** [comment]
Closing due to no response. @GamerAtlantis I hope you managed to fix the problem!
