### ISSUE TITLE
Netdata incorrectly places logfiles to `/` root

### ISSUE THREAD

**Issue by a-schaefers** [netdata/netdata#11030]
I'd like to propose log files go to /var/log or maybe /var/crash as reasonable locations.

I undertand this was done on purpose in https://github.com/netdata/netdata/issues/5679 but it's just not the correct way to handle this.

Let's exit non-zero on errors and just let the mailer handle the getting of our attention without littering the root filesystem.

**Comment by ilyam8** [comment]
Hi @a-schaefers 

This issue reported in https://github.com/netdata/netdata/issues/10954

Closing as duplicate
