### ISSUE TITLE
cgroups v2 metrics not showing up

### ISSUE THREAD

**Issue by hferreira23** [netdata/netdata#11053]
##### Bug report summary

Cgroups v2 info not showing up on Netdata.

##### OS / Environment

I'm using Netdata v1.30.1-79-nightly container in 3 different machines (1 amd64, 2 armv7 - rpi3 and 4).

The RPI4 also serves as a Stream server while the other 2 are collectors. All servers are running Debian testing fully patched.

The docker containers metrics don't show up in Netdata in neither of the servers. 

Relevant logs
```
Apr 26 23:32:17 plex-server docker-compose[8032]: #033[33mnetdata            |#033[0m 2021-04-26 22:32:17: netdata INFO  : PLUGIN[cgroups] : thread created with task id 127
Apr 26 23:32:17 plex-server docker-compose[8032]: #033[33mnetdata            |#033[0m 2021-04-26 22:32:17: netdata INFO  : PLUGIN[cgroups] : set name of thread 127 to PLUGIN[cgroups]
Apr 26 23:32:17 plex-server docker-compose[8032]: #033[33mnetdata            |#033[0m 2021-04-26 22:32:17: netdata INFO  : PLUGIN[cgroups] : use unified cgroups true
Apr 26 23:54:30 plex-server docker-compose[8032]: #033[33mnetdata            |#033[0m 2021-04-26 22:54:30: netdata INFO  : PLUGIN[cgroups] : STREAM plex-server.hmfamily.xyz [send]: sending metrics...
Apr 27 00:10:06 plex-server docker-compose[8032]: #033[33mnetdata            |#033[0m 2021-04-26 23:10:06: netdata INFO  : PLUGIN[cgroups] : STREAM plex-server.hmfamily.xyz [send]: sending metrics...
Apr 27 00:30:16 plex-server docker-compose[8032]: #033[33mnetdata            |#033[0m 2021-04-26 23:30:16: netdata INFO  : PLUGIN[cgroups] : STREAM plex-server.hmfamily.xyz [send]: sending metrics...
Apr 27 01:26:04 plex-server docker-compose[8032]: #033[33mnetdata            |#033[0m 2021-04-27 00:26:04: netdata INFO  : PLUGIN[cgroups] : STREAM plex-server.hmfamily.xyz [send]: sending metrics...
Apr 27 03:32:58 plex-server docker-compose[8032]: #033[33mnetdata            |#033[0m 2021-04-27 02:32:58: netdata INFO  : MAIN : EXIT: Stopping main thread: PLUGIN[cgroups]
```

**Comment by vlvkobal** [comment]
Please provide the output of `tree -d /sys/fs/cgroup`.

Let's also see what is in the `[plugin:cgroups]` section in http://localhost:19999/netdata.conf.

**Comment by vlvkobal** [comment]
It would also be interesting to see the output of `curl http://localhost:19999/api/v1/charts | grep '"id": "services.'`.

**Comment by hferreira23** [comment]
Requested outputs:

netdata.conf

´´´
[plugin:cgroups]
	# cgroups plugin resource charts = yes
	# update every = 2
	# check for new cgroups every = 20
	# use unified cgroups = auto
´´´
tree:

´´´
/sys/fs/cgroup
├── dev-mqueue.mount
├── init.scope
├── -.mount
├── sys-fs-fuse-connections.mount
├── sys-kernel-config.mount
├── sys-kernel-debug.mount
├── sys-kernel-tracing.mount
├── system.slice
│   ├── actions.runner.hferreira23-docker-cadvisor.fuckingserver.service
│   ├── alsa-restore.service
│   ├── atopacct.service
│   ├── atop.service
│   ├── avahi-daemon.service
│   ├── avahi-daemon.socket
│   ├── bluetooth.service
│   ├── boot.mount
│   ├── chrony.service
│   ├── console-setup.service
│   ├── containerd.service
│   ├── cron.service
│   ├── dbus.service
│   ├── dbus.socket
│   ├── dev-zram0.swap
│   ├── docker-17c1b98c4c9077fa0b30510bd48d86d47226a92b3d8a4d5305a787de97dfb0c5.scope
│   ├── docker-1fa88f11cc94d60340b7f34e63117f0896d290479f46464293ea97cd1bc25a62.scope
│   ├── docker-3580bf1c03c5f0dffe536e26f0a02050d7bd9a103f9b5de8ff01254f1f665bf8.scope
│   ├── docker-406374fb00979b29c5db0a4bcbad6a16b1effc62a49bc1a6c367de3f15dd276d.scope
│   ├── docker-44fff2377c71d9940c75758c7a73cd6dce869c5a620259e7e7d6cbf81f22a1cd.scope
│   ├── docker-4d5da766dc33582038f46d9530e9b14fcd7aa931ae9575d6da49b5f619813409.scope
│   ├── docker-5b1a4c8b02bfd502ca0076d63b41b1880abe44f9b6feed6b5dae4b5b800143ed.scope
│   ├── docker-79ed420f1e029fa78371fec1867f9b6f7bbc2c09094dde4d4f7e8fc6a8eb090e.scope
│   ├── docker-83e3d1c179043093b887d5032778535666fd564b659ad00ed99b4a71416f4713.scope
│   ├── docker-8733ea79718bac2aa00f0e258528b74cbc265e7beb522e72e03462d781723ce1.scope
│   ├── docker-9d04c87fb4fd2917f271394a59589cb4ad516d2ba71dba3dbffdfda4c1c34a54.scope
│   ├── docker-c17d9f6943dec8479048a92990eb549ee119f5a86fcd386d249237a5789af782.scope
│   ├── docker-c2ebfae70ab33d2d4a8bc7030963f03d6c3d98fd16df9b703e7617a69b9bf1f8.scope
│   ├── docker-d3263e43cb6c087bb003d8fea257c9d6dd28add3f17a2b734b15915e3825afdf.scope
│   ├── docker.service
│   ├── docker.socket
│   ├── fake-hwclock.service
│   ├── hciuart.service
│   ├── ifupdown-pre.service
│   ├── ifup@eth0.service
│   ├── ifup@wlan0.service
│   ├── isc-dhcp-server.service
│   ├── keyboard-setup.service
│   ├── kmod-static-nodes.service
│   ├── knot.service
│   ├── networking.service
│   ├── raspi-config.service
│   ├── rc-local.service
│   ├── rng-tools-debian.service
│   ├── rpi-eeprom-update.service
│   ├── rsyslog.service
│   ├── run-docker-netns-0dd7db7fb229.mount
│   ├── run-docker-netns-42ebc5df2d28.mount
│   ├── run-docker-netns-7a89d4f5f54a.mount
│   ├── run-docker-netns-9c4897a7bf8b.mount
│   ├── run-rpc_pipefs.mount
│   ├── smartmontools.service
│   ├── ssh.service
│   ├── syslog.socket
│   ├── system-bthelper.slice
│   ├── systemd-fsckd.socket
│   ├── systemd-fsck-root.service
│   ├── systemd-initctl.socket
│   ├── systemd-journald-audit.socket
│   ├── systemd-journald-dev-log.socket
│   ├── systemd-journald.service
│   ├── systemd-journald.socket
│   ├── systemd-journal-flush.service
│   ├── systemd-logind.service
│   ├── systemd-modules-load.service
│   ├── system-docker\x2dcompose.slice
│   │   ├── docker-compose@ara.service
│   │   ├── docker-compose@base.service
│   │   ├── docker-compose@docker_pull_exporter.service
│   │   ├── docker-compose@pihole.service
│   │   ├── docker-compose@prometheus.service
│   │   └── docker-compose@wireguard.service
│   ├── systemd-random-seed.service
│   ├── systemd-remount-fs.service
│   ├── systemd-resolved.service
│   ├── systemd-rfkill.socket
│   ├── systemd-sysctl.service
│   ├── systemd-sysusers.service
│   ├── systemd-tmpfiles-setup-dev.service
│   ├── systemd-tmpfiles-setup.service
│   ├── systemd-udevd-control.socket
│   ├── systemd-udevd-kernel.socket
│   ├── systemd-udevd.service
│   ├── systemd-udev-trigger.service
│   ├── systemd-update-utmp.service
│   ├── systemd-user-sessions.service
│   ├── system-getty.slice
│   │   └── getty@tty1.service
│   ├── system-modprobe.slice
│   ├── system-systemd\x2dfsck.slice
│   │   └── systemd-fsck@dev-disk-by\x2dpartuuid-76081915\x2d01.service
│   ├── system-uwsgi.slice
│   │   └── uwsgi@speedtest_exporter.service
│   ├── triggerhappy.service
│   ├── triggerhappy.socket
│   ├── var-lib-docker-overlay2-07d296eb62d2e2da9bff8c6ded4d9e3c07c5c956436315b995d61c5f9e49dbe9-merged.mount
│   ├── var-lib-docker-overlay2-4b975a6d804ed9dc649c20ce4972fbacbbe8ee172654de3ed9ee44e8866c4f2b-merged.mount
│   ├── var-lib-docker-overlay2-a4fe3aa5ec53d0b8d063823173e97c0c492ba45203594b064031932e18c82b6e-merged.mount
│   ├── var-lib-docker-overlay2-f61b3b07785bebe44d395dd805ea17e4e1ef2b20d41688f7f874467c43720dd1-merged.mount
│   ├── var-lib-docker-volumes-pihole_pihole_opt-_data.mount
│   ├── wpa_supplicant.service
│   └── zram-swap-config.service
└── user.slice
    └── user-2388.slice
        ├── session-1748.scope
        └── user@2388.service
            ├── app.slice
            └── init.scope

116 directories
´´´
curl (comes up empty)
´´´
❯ curl http://localhost:19999/api/v1/charts | grep '"id": "services.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  338k  100  338k    0     0  9944k      0 --:--:-- --:--:-- --:--:-- 10.0M
´´´

**Comment by vlvkobal** [comment]
1. It looks like you copied the contents of the `netdata.conf` file, not the `http://arch-esxi:19999/netdata.conf` HTTP endpoint. There should be much more options.
2. Did you run `tree` from the host or from the inside of the Netdata container?
3. If you have `jq` installed please run the following (change the name of the container `netdata` to what you really have on your machine)
```
docker inspect netdata | jq “.[] | .Mounts”
```

**Comment by hferreira23** [comment]
Sorry for the delay, haven't had the time to further troubleshoot this.

2. actually send me in the path to fix my issue. I'm using docker-compose to manage the container and the mount for /sys is:

```
volumes:
  - /sys:/host/sys
```

So its quite obvious what the issue was. Adding ``` path to unified cgroups = /host/sys/fs/cgroup ``` to the ``` plugin:cgroups ``` setting got everything working.

Not a bug in Netdata but me being an idiot. Thanks for the help :)

**Comment by ilyam8** [comment]
That actually looks like a bug. 

I set `use unified cgroups` to yes, see the path - it has double `/host` prefix.


```cmd
[ilyam@pc ~]$ docker exec netdata curl -s http://127.0.0.1:19999/netdata.conf | grep "unified cgroups"
	use unified cgroups = yes
	# path to unified cgroups = /host/host/sys/fs/cgroup/unified
```

**Comment by ilyam8** [comment]
I had no Cgroups v2 enabled when was testing https://github.com/netdata/netdata/issues/11053#issuecomment-829491646

Tested with enabled Cgroup v2 and all works well if I follow https://learn.netdata.cloud/docs/agent/packaging/docker#create-a-new-netdata-agent-container and set `use unified cgroups = yes` manually.

I opened [an issue for cgroups version detection problem](https://github.com/netdata/netdata/issues/11094).
