### ISSUE TITLE
Ubuntu: Installing netdata package makes web interface inaccessible

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#11062]
##### Bug report summary

Installing netdata package makes web interface inaccessible

A ton of `sudo chmod -R netdata ...` are needed to have an accessible interface (if not more)

##### OS / Environment

Ubuntu Focal

##### Netdata version
latest

##### Installation method

package

----

Side thoughts:

Your log files contain **a bajillion** of warnings and errors, that **should not be real errors**:

- Unable to find overriding configuration in /etc/netdata
- Plugin X cannot find Y (when Y is not installed, so there would be nothing to track)

All of that, make manual error navigation much harder (and vetting logs for sharing even impossible)

It would be nice if the `/var/log/netdata` was accessible by admins, or a notice that some `usermod -aG` would be nice-to-do.

**Comment by OdysLam** [comment]
Hey @stdedos,

Thanks for this. Can you please verify for us what was your installation method and the version of netdata? 
run `netdata -version`

**Comment by stdedos** [comment]
> Can you please verify for us what was your installation method

> > ##### Installation method
> > package

> ... and the version of netdata?
> run `netdata -version`

v1.30.1

**Comment by stdedos** [comment]
Can you please triage and fix this?

It even messes up with upgrades nowadays ...

**Comment by Ferroin** [comment]
Apologies for the delayed response on this.

The most likely case is that you have custom values set for the `web files owner` and/or `web files group` options in `/etc/netdata.conf`. Those need to match the file ownership of the web UI files themselves (yes, I know this is stupid, but I’m unfortunately not the one who has any say in whether we do this or not).

**Comment by stdedos** [comment]
> The most likely case is that you have custom values set for the `web files owner` and/or `web files group` options in `/etc/netdata.conf`

First of all, it's `/etc/netdata/netdata.conf`, and
no; `web files owner` and `web files group` are commented out, and their default value appears to be `netdata`.

> Those need to match the file ownership of the web UI files themselves (yes, I know this is stupid, but I’m unfortunately not the one who has any say in whether we do this or not).

From my position, I cannot make such claim (as I am _only_ a user) - but we seem to have a mutual feeling about this.

You must either ship a debian variant of `/etc/netdata/netdata.conf`; or (more easily probably), either pack the files with the correct owner/group or invest in some post-inst deb-action

**Comment by Ferroin** [comment]
> > The most likely case is that you have custom values set for the `web files owner` and/or `web files group` options in `/etc/netdata.conf`
> 
> First of all, it's `/etc/netdata/netdata.conf`, and

Yes, my bad.

> no; `web files owner` and `web files group` are commented out, and their default value appears to be `netdata`.

This is strange, the default config file we ship in our official packages _should_ have those lines uncommented and set to `root` and `netdata` respectively. Doing so yourself should allow you to work around the issue in the short term.

> 
> > Those need to match the file ownership of the web UI files themselves (yes, I know this is stupid, but I’m unfortunately not the one who has any say in whether we do this or not).
> 
> From my position, I cannot make such claim (as I am _only_ a user) - but we seem to have a mutual feeling about this.
> 
> You must either ship a debian variant of `/etc/netdata/netdata.conf`; or (more easily probably), either pack the files with the correct owner/group or invest in some post-inst deb-action

Just to confirm, you are using our official packages as described [here](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages), or are these the packages provided by Canonical with Ubuntu 20.04?

In the first case, then there’s a bug we need to fix, while in the second there’s not really much we can do beyond what a user could do, as Canonical maintains their own packages for Netdata independent of us.

**Comment by stdedos** [comment]
> Just to confirm, you are using our official packages as described [here](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages)?

The ones from PackageCloud.

Indeed, I just downloaded the package and the values inside seem to be root/netdata.
I guess the deb-specific configuration was somehow missed; I will apply it manually.

Let's check what will happen with the next update.

In the meantime, if you could somehow fix or note this
> It would be nice if the /var/log/netdata was accessible by admins, or a notice that some usermod -aG would be nice-to-do.

That'd be great 😀

**Comment by ilyam8** [comment]
I installed Netdata v1.31.0 using the `PackageCloud` repository and I had not problems with the web interface.

> config file we ship in our official packages should have those lines uncommented and set to root and netdata respectively

I confirm it.

@stdedos closing the issue for now.

**Comment by ilyam8** [comment]
> Your log files contain a bajillion of warnings and errors, that should not be real errors

Also, confirm this too 😅
