### ISSUE TITLE
Export the list of apps not matching `apps_groups.conf`

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#11063]
It would be nice, if:
* there was a list of the applications that fall through matching of `apps_groups.conf`
* there was a way to inherit (pre or post) the default `apps_groups.conf`, so I will be able to define my own stuff, and keep getting updated from your `apps_groups.conf` too

**Comment by manos-saratsis** [comment]
@stdedos thx for reaching out. I am not sure if I understand your needs:
- do you want to have a list of application matching each group via a GUI?
- why not to edit the apps_groups.conf to add your own stuff on top of the apps groups that are currently there?

**Comment by stdedos** [comment]
> * do you want to have a list of application matching each group via a GUI?

All non-matching applications. I have quite a lot cpu spent on "other" apps, and I want to start working on reducing it, small steps at a time.
A way to query those applications for a specific point in time should be possible, as netdata seems to redraw the graph on-the-spot when the file is changed. Therefore, an API call that could query those "other" apps (i.e. by passing an epoch value) would be helpful.

> * why not to edit the apps_groups.conf to add your own stuff on top of the apps groups that are currently there?

Because I want to keep updating automatically, and keep up-to-date to whatever changes you do in `apps_groups.conf`, without the manual process of merging or inspecting (until at least e.g. I come at a disagreement with your `apps_groups.conf` that you won't accept upstream).
If I copy that file to /etc, then it starts to be "my own", which I don't want to maintain.

**Comment by ilyam8** [comment]
> All non-matching applications. I have quite a lot cpu spent on "other" apps, and I want to start working on reducing it, small steps at a time.

Oh, I did it some time ago. That is what I did:
 - identify processes PIDs for a specific group
 - find those processes `/proc/PID/comm` and `/proc/PID/cmdline` (we match against these values)

For instance, if I want to debug `other` group

```cmd
[pc plugins.d]# ./apps.plugin debug without-users without-groups 2>&1 | grep -m 1 "target 'other' has aggregated" | awk -F':' '{print $3}' | sed 's/^[[:space:]]*//;s/ *$//g'
1 400 901 929 955 959 1004 1014 1017 1021 1025 1068 1071 1086 1093 1097 1108 1115 2121

[pc plugins.d]# for i in $(echo "1 400 901 929 955 959 1004 1014 1017 1021 1025 1068 1071 1086 1093 1097 1108 1115 2121"); do \
printf "[%d %s] cmdline=%q\n" \
$i $(cat /proc/$i/comm 2>/dev/null) $(cat /proc/$i/cmdline 2>/dev/null | tr -d '\0'); done
[1 systemd] cmdline=/sbin/init
[400 smartd] cmdline=/usr/bin/smartd-n-A/var/log/smartd/-i600
[901 kwalletd5] cmdline=/usr/bin/kwalletd5--pam-login78
[929 start_kdeinit] cmdline=/usr/lib/kf5/start_kdeinit
[955 kded5] cmdline=/usr/bin/kded5
[959 kwin_x11] cmdline=/usr/bin/kwin_x11
[1004 ksmserver] cmdline=/usr/bin/ksmserver
[1014 polkit-kde-auth] cmdline=/usr/lib/polkit-kde-authentication-agent-1
[1017 kaccess] cmdline=/usr/bin/kaccess
[1021 xembedsniproxy] cmdline=/usr/bin/xembedsniproxy
[1025 org_kde_powerde] cmdline=/usr/lib/org_kde_powerdevil
[1068 gmenudbusmenupr] cmdline=/usr/bin/gmenudbusmenuproxy
[1071 kdeconnectd] cmdline=/usr/lib/kdeconnectd
[1086 pamac-tray-plas] cmdline=/usr/bin/pamac-tray-plasma
[1093 yakuake] cmdline=/usr/bin/yakuake
[1097 msm_kde_notifie] cmdline=/usr/bin/msm_kde_notifier
[1108 python3] cmdline=python3/usr/bin/manjaro-hello
[1115 agent] cmdline=/usr/lib/geoclue-2.0/demos/agent
[2121 kscreenlocker_g] cmdline=/usr/lib/kscreenlocker_greet--graceTime5000--ksldfd29
```

**Comment by stdedos** [comment]
Cool!

Of course, I'd prefer the API output (because that means, if I find a spike on the UI, I can ask the API "What was _that_ about?"), but that is workable too 😀

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
