### ISSUE TITLE
Documentation: Is the lookup line really required?

### ISSUE THREAD

**Issue by tknobi** [netdata/netdata#11085]
##### Bug report summary

From the [Health configuration reference](https://learn.netdata.cloud/docs/agent/health/reference/#entity-format): 

> The on and lookup lines are always required.

However, it seems that the lookup line it is not required at all. [Example 1](https://learn.netdata.cloud/docs/agent/health/reference/#example-1) already does not have this line. Why is it written as required in the documentation? Should this be changed?

##### Component Name

Documentation

**Comment by ilyam8** [comment]
Hi @tknobi 

I think you are right, `lookup` is not mandatory.

For instance, all our _last_collected_secs_ alarms have no `lookup`

https://github.com/netdata/netdata/blob/master/health/health.d/apache.conf#L4-L16
