### ISSUE TITLE
Unable to see ipmi-dcmi power statistics in netdata

### ISSUE THREAD

**Issue by 8465231** [netdata/netdata#11106]
##### Bug report summary

I want to be able to track my servers power usage in netdata. The power information is available by running inside the container:

# ipmi-dcmi --get-system-power-statistic
Current Power                        : 254 Watts
Minimum Power over sampling duration : 0 watts
Maximum Power over sampling duration : 519 watts
Average Power over sampling duration : 236 watts
Time Stamp                           : 05/06/2021 - 14:19:30
Statistics reporting time period     : 231287000 milliseconds
Power Measurement                    : Active

I can not figure out how to get this imported into netdata though. This bug seemed to indicate that I could add this command to the freeipmi.plugin command but that just fails and I can not find any further mention or information on the matter.

https://github.com/netdata/netdata/issues/7066

##### OS / Environment

```
I am running the latest docker version of netdata on unraid, freshly updated this morning.
```

##### Netdata version

Version: netdata v1.30.1-112-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' '--with-libJudy=externaldeps/libJudy' 'CFLAGS=' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES

##### Installation method

Installed the unraid ready docker image from the app store.

##### Component Name

freeipmi.plugin

##### Steps To Reproduce

1. install netdata docker
2. try to add ipmi-dcmi --get-system-power-statistic to freeipmi.plugin command fails

##### Expected behavior

The above bug seemed to indicate that this would allow the monitoring of dcmi data in netdata. I can not find anymore information on dcmi and netdata anywhere on the net so I have nothing to go on besides that bug report.

**Comment by 8465231** [comment]
I have read the documentation, it does not mention dcmi at all It only tells how to ignore sensors, not add missing sensors. 

The power statistics only show up through dcmi, not the regular ipmi sensors.

**Comment by vlvkobal** [comment]
I'm not a specialist in IPMI, moreover, I don't have access to IPMI hardware. Power statistics should be displayed by default in the `ipmi.watts` chart ("System Power read by IPMI"). `ipmi_monitoring_sensor_iterator_next()` walks through sensors, `ipmi_monitoring_sensor_read_sensor_reading()` gets data.

Maybe @Saruspete can help :shrug:.

**Comment by 8465231** [comment]
Yeah, the rest of the sensors work properly without an issue. The problem is that with supermicro motherboards (and apparently HP, possibly dell) the power statistics are delivered through the dcim and not the regular ipmisensors. 

The data is there and available as you can see above, it uses the same freeipmi package to do it, just a different command.

Is there a way to add a manual graph to netdata? I could not find any good documentation about adding a completely custom datapoint, basically get a simple value with grep and have netdata plot it into a graph.

**Comment by vlvkobal** [comment]
You can write a custom plugin in [Bash](https://learn.netdata.cloud/docs/agent/collectors/charts.d.plugin#a-chartsd-module) or [Python](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin#how-to-write-a-new-module).
Examples: [Bash](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/example), [Python](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/example).

**Comment by Saruspete** [comment]
I  used the standard FreeIPMI module on Dell, HPE, Intel and SuperMicro. And while testing that to be sure on supermicro, @8465231 is indeed right: the wattage is not reported on Supermicro systems through the sensor reading: only volts, rpms & temperature.

That would be a nice improvement, but would take a long time to be done (and subject to the rather slow 10second refresh time, while the `ipmi-dcmi` command is able to do per-second sampling.

I guess a bash/awk script would be the most quick & portable for such a small addition.  I should be able to do it quickly, if you want.

**Comment by 8465231** [comment]
Yes, that would be fantastic, still quite new to linux (only be using it regularly for ~6 months) so it would take me much longer then I want to admit to figure this out by myself. 

Still plan to figure out custom sensors at some point as there are a few other metrics I have wanted to monitor over time but that is a slow roll job for another time.

Right now I am trying to figure out the optimal power/disk spindown/speed settings for optimal power usage (and lowest noise in the living room) and being able to log power usage in netdata would make it FAR easier.

**Comment by 8465231** [comment]
No rush, just curious if you had a chance to make a script for this yet?

**Comment by 8465231** [comment]
@Saruspete No rush, just curious if you had a chance to make that script? Thanks.

**Comment by Saruspete** [comment]
Woops, very sorry for not replying before @8465231 
Yes, I did make some tests, and some refinements to avoid drift.

Let me do a few refinings on the script, and I'll publish it here.
For upstream, that would need more changes, like be incorporated in the freeipmi module... we'll see

**Comment by 8465231** [comment]
Ok cool. Sounds good!

**Comment by Saruspete** [comment]
Here's the plugin: https://gist.github.com/Saruspete/344304c48ae2af6edea6e856c09236ab

You can try it: 
```
typeset dst="/usr/libexec/netdata/plugins.d/ipmi-dcmi.plugin"
wget -O "$dst" "https://gist.githubusercontent.com/Saruspete/344304c48ae2af6edea6e856c09236ab/raw/1c3c155e132b76982a24f1fd8655ebc07baeb8bd/ipmi-dcmi.plugin"
chmod +x $dst

echo "netdata	ALL=(ALL)	NOPASSWD: $dst" >> /etc/sudoers.d/netdata-ipmidcmi

# Then, try it as target user (netdata)
su -s /bin/bash netdata $dst
```

**Comment by Saruspete** [comment]
Note: for sudo to work with systemd capabilities drop, you'll need to add :
```
CapabilityBoundingSet=CAP_SETUID
CapabilityBoundingSet=CAP_SETGID
```

**Comment by 8465231** [comment]
I will try that tomorrow, re-doing some hardware in the server right now so it is down for the moment.

I am using the netdata docker, are the commands the same for that? I think it is based on alpine and sudo does not apply?

**Comment by 8465231** [comment]
@Saruspete 

Ok, got the server back up I think. gave the above commands a go in the docker but it failed on the : 

echo "netdata	ALL=(ALL)	NOPASSWD: $dst" >> /etc/sudoers.d/netdata-ipmidcmi

I tried searching for both netdata-ipmidcmi file and sudoers.d folder but could not find it anywhere in the docker. 

Not sure where to go from there.

**Comment by Saruspete** [comment]
Hum, I chose to run the whole script in sudo to avoid starting "sudo + ipmi-dcmi" every time (as sudo has a much more heavy performance impact, which would lead to sampling drift).

If you are in a docker without sudo, you can try to workaround this by either:
- setting /dev/ipm0 readable by netdata: `chgrp netdata /dev/ipmi0; chmod g+rw /dev/ipmi0`
- setting "ipmi-dcmi" setuid itself, and removing the check in the script:  `chmod u+s $(type -P ipmi-dcmi)`

**Comment by 8465231** [comment]
@Saruspete
It is the official docker image which seems to be based on alpine. I have only been using linux regularly for 6 months, still very much in the learning curve.

After searching it seems that sudo can be installed on alpine but needs some extra configuration steps. I think I got it installed and the sudoer folder is now there.

I ran the commands again and all worked until I tried running the script.

bash-5.0# su -s /bin/bash netdata $dst
/usr/libexec/netdata/plugins.d/ipmi-dcmi.plugin: line 26: timeoutCmd+= 2: not found
No binary ipmi-dcmi available in '/bin /usr/bin'

I am guessing this means that the ipmi-dcmi is not in the path for the docker? Does the path need to be updated for the docker in the script?

Thanks for the help, think I almost have it lol.

**Comment by Saruspete** [comment]
> I am guessing this means that the ipmi-dcmi is not in the path for the docker? Does the path need to be updated for the docker in the script?

yes, it should be in /sbin or /usr/sbin. From the log output, there's only "/bin" "and "/usr/sbin" in $PATH

**Comment by 8465231** [comment]
Well, I echo $PATH, it gives me this:

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

but even though trying to run it manually didn't work it works in netdata!

![firefox_K5A6DydqkL](https://user-images.githubusercontent.com/76955719/119989709-017fb880-bfb7-11eb-8278-4e65f3a4e9aa.jpg)

Thanks a lot!

Is there an easy way to make this persistent with docker updates?

**Comment by 8465231** [comment]
I can understand that, I am very grateful for your time getting this working on a limited scale anyways.

What about a more custom option for docker persistence such as a script in a local folder that could be run upon docker start that would check if it was installed and if not install it? not sure if these commands could be scripted?

**Comment by 8465231** [comment]
Just dropping this here in case anyone finds this on google. Managed to create a script that installs this plugin (along with the apcupsd package needed for monitoring a UPS). I have not figured out how to have to run automatically on startup of the docker but it can be run manually inside the docker using a mapped persistent folder.

`#!/bin/bash

apk update && apk upgrade && apk add apcupsd sudo

typeset dst="/usr/libexec/netdata/plugins.d/ipmi-dcmi.plugin"
wget -O "$dst" "https://gist.githubusercontent.com/Saruspete/344304c48ae2af6edea6e856c09236ab/raw/1c3c155e132b76982a24f1fd8655ebc07baeb8bd/ipmi-dcmi.plugin"
chmod +x $dst

echo "netdata	ALL=(ALL)	NOPASSWD: $dst" >> /etc/sudoers.d/netdata-ipmidcmi`
