### ISSUE TITLE
DBEngine using more memory than it should?

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#11111]
@gvasquez95 has to restart netdata frequenty, because DBEngine is using too much memory. DBEngine memory usage increasing to 400MB with just 3808 metrics and the default settings. Goes down significantly after restart. From the charts I just saw that the page cache statistics chart showed the "descriptors" constantly increasing. 

What's the expected memory footprint with the default settings for 4k metrics?

**Comment by cakrit** [comment]
It looks like the normal memory usage of the entire netdata process with 3 days of retention is under 200MB (closer to 180MB, aligned pretty well with the output of the calculator). So I'm closing this one, anything significantly above this figure can be configured a bug worth investigating.

**Comment by gvasquez95** [comment]
@cakrit it eats all memory on the instances despite how much memory is available, so it can add up to a couple GBs

**Comment by cakrit** [comment]
@gvasquez95 I asked in https://github.com/netdata/netdata/issues/11095 if you see the memory usage linked with the ACLK issue at all. Let's follow up there, we do know that when metrics appear and disappear all the time, we're doing a good job keeping the memory in check. I hadn't seen evidence for that in your infra, but we'll need to dig deeper.
