### ISSUE TITLE
Deleted War-room has returned and cannot be deleted now.

### ISSUE THREAD

**Issue by bazwalt** [netdata/netdata#11135]
Hi all,

I have a war-room in my space that was deleted yesterday evening and it has subsequently returned this morning upon my login.

I now cannot delete it again and it keeps telling me I am no longer a room member. I also cannot re-add myself to the room.

**Comment by ilyam8** [comment]
Issue moved to [netdata/netdata-cloud #93](https://github.com/netdata/netdata-cloud/issues/93) via [**ZenHub**](https://www.zenhub.com/)
