### ISSUE TITLE
Docs feedback on: Infrastructure monitoring with Netdata

### ISSUE THREAD

**Issue by jonnygoz** [netdata/netdata#11146]
**Issue with: Infrastructure monitoring with Netdata**

Hi, trying to figure out if/how I can claim my Mac after I installed Netdata and have a cloud account? I tried the claim script but it doesn't seem to work.

**Comment by OdysLam** [comment]
Hey, 

Thank you for this. We are currently working on our macOS release since a couple of bugs have been surfaced. 

In the meantime, for the time being, we would suggest using Netdata in a docker container, using Docker Desktop for Mac.
