### ISSUE TITLE
is swapio wrong?

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#11140]
##### Bug report summary

While I was finishing the PR https://github.com/netdata/netdata/pull/11090 I observed that `in` and `out` on chart `swapio` are showing the opposite of `read` and `write` on eBPF charts. After to take a look in the sar official documentation available [here](https://man7.org/linux/man-pages/man1/sar.1.html) and also this [Red Hat description](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/4/html/introduction_to_system_administration/s1-memory-rhlspec), I suppose our dimensions are invernted.

##### OS / Environment

All Linuxes 

##### Netdata version

v1.30.1-117-g31098d9ed

##### Installation method

Compilation from scratch.

##### Component Name
```
proc.plugin
```

##### Steps To Reproduce

1. Compile the PR  https://github.com/netdata/netdata/pull/11090 and compare `swapio` with `eBPF` correlated chart.

##### Expected behavior

eBPF and proc plugin must be synchronized.

**Comment by thiagoftsm** [comment]
@ilyam8 and @vlvkobal I am thinking to use #11090 to fix this issue.

**Comment by vlvkobal** [comment]
I don't have any swap devices configured but I compared dimensions and their underlying data in `system.swapio`, `system.io`, and `disk.*`. It looks like everything is correct. Please check disk reads/writes when you are testing your PR.

**Comment by ilyam8** [comment]
I took a look at [the documentation you are mentioning](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/4/html/introduction_to_system_administration/s1-memory-rhlspec):

 - `pswpin`:  the pages the system brought in swap.
 - `pswpout`: the pages the system brought out swap.

https://github.com/netdata/netdata/blob/07a9fd07631135fb2025169ab3c1e68f07c28f81/collectors/proc.plugin/proc_vmstat.c#L138-L144

From the system point of view, it reads from (`pswpin`) and writes (`pswpout`) to swap. Why is that wrong?

**Comment by vlvkobal** [comment]
`sar`:
```
              pswpin/s
                     Total number of swap pages the system brought in
                     per second.

              pswpout/s
                     Total number of swap pages the system brought out
                     per second.
```

Red Hat
```
pages being brought in from swap (pswpin/s) as there were going out to swap (pswpout/s)
```

Thus, `pswpin` = `read` from swap device, `pswpout` = `write` to swap device.

The sentence you crossed out is the correct one.

**Comment by ilyam8** [comment]
Thanks, you are right. It confirms that in/out is confusing when you are looking at the swap chart 😄 You treat it as _in/out to swap_, but in fact, it is _out from/to swap_.

**Comment by thiagoftsm** [comment]
> https://github.com/netdata/netdata/blob/07a9fd07631135fb2025169ab3c1e68f07c28f81/collectors/proc.plugin/proc_vmstat.c#L138-L144
> 
> ~From the system point of view, it reads from (`pswpin`) and writes (`pswpout`) to swap. Why is that wrong?~
> 
> Ok, it is the opposite - for the system, `pswpin` is written and `pswpout` is read.


Yes, this was the conclusion I arrived, so the dimensions are inverted, and the next screenshot proofs this:

![Screenshot_20210513_135639](https://user-images.githubusercontent.com/49162938/118136024-2e4aa200-b3f3-11eb-8356-1c85252717f1.png)


I will push another commit to synchronize the information.

**Comment by thiagoftsm** [comment]
After an internal meeting, we arrived in agreement that the names can be strange for some developers, but they are not contradicting each other.
