### ISSUE TITLE
statsd metrics stop updating when the application is restarted

### ISSUE THREAD

**Issue by Lazin** [netdata/netdata#11158]
##### Bug report summary

Statsd collector is not reliable if the application that sends metrics is restarted often.

##### OS / Environment

```
Linux Unknown 5.11.17-100.fc32.x86_64 #1 SMP Wed Apr 28 14:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/fedora-release:Fedora release 32 (Thirty Two)
/etc/os-release:NAME=Fedora
/etc/os-release:VERSION="32 (Workstation Edition)"
/etc/os-release:ID=fedora
/etc/os-release:VERSION_ID=32
/etc/os-release:VERSION_CODENAME=""
/etc/os-release:PLATFORM_ID="platform:f32"
/etc/os-release:PRETTY_NAME="Fedora 32 (Workstation Edition)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:LOGO=fedora-logo-icon
/etc/os-release:CPE_NAME="cpe:/o:fedoraproject:fedora:32"
/etc/os-release:HOME_URL="https://fedoraproject.org/"
/etc/os-release:DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
/etc/os-release:SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Fedora"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=32
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Fedora"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION=32
/etc/os-release:PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
/etc/os-release:VARIANT="Workstation Edition"
/etc/os-release:VARIANT_ID=workstation
/etc/redhat-release:Fedora release 32 (Thirty Two)
```

##### Netdata version

```
Version: netdata v1.30.1-153-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

##### Installation method

kickstart.sh

##### Component Name

statsd

##### Steps To Reproduce

1. install netdata, enable statsd in config, restart netdata
2. run the application that expors statsd metrics
3. go to localhost:19999 to see that the charts are created
4. stop the application, check that the newly created charts are not updating anymore
5. start application again, here the chart might start updating again or it'll just keep being frozen

the statsd charts from the app will disappear eventually, restarting the app or the netdata might help or not (I can't see any logic behind it)

##### Expected behavior

The charts will be available in web UI even if the app is not working for a while. Restarting the app won't break the monitoring.

**Comment by ilyam8** [comment]
Hi @Lazin 👋 

Did you check `error.log`? If no I suggest doing the following:

 - enable statsd in config, restart netdata; run the application that exports statsd metrics; 
 - `tail -f error.log`
 - stop the application; start the application again
 - check the log output

---

> Statsd collector is not reliable if the application that sends metrics is restarted often.

That is interesting, I wonder why the restart breaks anything 🤔 Perhaps the app sends something not expected?

Can we check the metrics?
 - create a local udp server
 - configure the app to send metrics to it
 - restart the app, check the result

The is the udp server python script (port 2115), it prints all the received messages to the stdout

```py
import random
import socket

server_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
server_socket.bind(('', 2115)) 

while True:
    message, address = server_socket.recvfrom(1024)
    print(message)
```

**Comment by ilyam8** [comment]
Closing due to no response.
