### ISSUE TITLE
Unable to open the web interface of Netdata :(

### ISSUE THREAD

**Issue by GinoSchreuders** [netdata/netdata#11162]
Dear reader,

I've been working with Netdata since Monday.

At first my web interface worked but after I installed nginx my web interface stopped working.

I have now been working for more than 10 hours to get the web interface of Netdata working, but I can't.

Tried to reinstall Netdata several times and have also looked at solutions from others but they don't work for me.

It might be helpful to say that I am new to Linux systems.

If you need any screenshots or command output, please ask.

**Comment by ilyam8** [comment]
Hi @GinoSchreuders 

If you believe there is a bug, please add all the info according to [the bug template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md).

If you are unsure and need support consider using [our community forum](https://community.netdata.cloud/).

In any case, try to provide as much information as you can:

- what is _web interface of Netdata working_
- what actions did you take (_have now been working for more than 10 hours to get_)
- your setup (remote server in local network or some cloud provider virtual machine)

**Comment by ilyam8** [comment]
Closing the issue because it is a question/support request and we use the community forum for that.
