### ISSUE TITLE
apps.plugin consuming high cpu on medium load server

### ISSUE THREAD

**Issue by bymodude** [netdata/netdata#11164]
##### Bug report summary

apps.plugin is consuming ~70% CPU (70% of a 5950x core) on my medium load server (cpu all core utilization only at 50%, not thousands of processes), this doesn't seem right, how would I go about debugging this?

##### OS / Environment
- uname -a; grep -Hv "^#" /etc/*release  # Linux
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
```

##### Netdata version
```
Version: netdata v1.30.1-153-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

##### Installation method
kickstart.sh

##### Component Name
apps.plugin

##### Steps To Reproduce
1. Run netdata on medium loaded server (in this case a 16 core server with about 2 dozen medium cpu loaded processes and very heavy i/o work load
2. observe apps.plugin consuming almost an entire cpu core for collecting data

##### Expected behavior
I understand netdata needs resources to collect data and that these resources can be high, but 70% of an entire cpu core is excessive, it seems something weird is going on

**Comment by ilyam8** [comment]
Hi @bymodude 

You are right. 70% is a lot and not expected.

Could you send [a snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) to <ilya@netdata.cloud>? It will help us to debug the problem.

cc @vlvkobal

**Comment by ilyam8** [comment]
@bymodude 

 - Does `apps.plugin` consume 70% right after the netdata restart? Or its CPU usage slowly increasing over time? (you sent the snapshot for the last 5 minutes)
 - `apps.plugin is consuming ~70% CPU` Did you check it using Netdata itself or some cli tool?

Let's double-check it using top

> top -n 10 -b -p $(pidof apps.plugin) | grep $(pidof apps.plugin)

**Comment by ilyam8** [comment]
> 70% is a lot and not expected.

Depends on the number of active processes/number of created processes/s. I get ~60% of a single core with 20k+ active processes.

**Comment by cloudition** [comment]
Hi,
I have a constant CPU utilization between 20% and 60%. Is this normal? As far as I remember this was not the case in the past...
![image](https://user-images.githubusercontent.com/60007632/127137331-ef181792-81d7-42a4-bef2-74ae735f95c0.png)

**Comment by ilyam8** [comment]
> between 20% and 60%. Is this normal?

[Depends on your setup/workload](https://github.com/netdata/netdata/issues/11164#issuecomment-844994163). 

---

> apps.plugin
> As far as I remember this was not the case in the past...

We haven't changed apps.plugin [for a long time](https://github.com/netdata/netdata/commits/master/collectors/apps.plugin/apps_plugin.c). _not the case in the past_ - did you have the same workload on the server?

**Comment by ilyam8** [comment]
@cloudition Could you send [a snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) to <ilya@netdata.cloud>?

**Comment by ilyam8** [comment]
Hey, guys, are you still having this issue with the latest version? @bymodude @cloudition

**Comment by cloudition** [comment]
Hi,
not it's running normal again. Thank you very much!

![image](https://user-images.githubusercontent.com/60007632/135051707-c70246c8-4770-4b83-aa94-4552e19fbb07.png)

**Comment by ilyam8** [comment]
Ok, thanks for the quick reply. Closing for now. Аf the problem reappears, let us know.
