### ISSUE TITLE
BUG: Fix eBPF support on static binaries for Debian/RPM packages

### ISSUE THREAD

**Issue by knatsakis** [netdata/netdata#11174]
## Goal

Have eBPF enabled in all installations that have Kernel version newer 4.11

@Ferroin 

We should include this on the "binary distros" epic.

Let's approach this holistically, and check 

1. if eBPF is enabled by default on all supported platforms
2. if eBPF is enabled on all supported CPUs (depending on kernel version).
3. examine the possibility to differentiate CI/CD for the core agent from all the rest of add-ons / plugins / etc.

**Comment by Ferroin** [comment]
Closing this, as it’s no longer valid.
