### ISSUE TITLE
Suggestions: Logarithmic precision

### ISSUE THREAD

**Issue by haasn** [netdata/netdata#1118]
It would be interesting to experiment with a logarithmic precision mode, which divides graphs into “frequency” buckets of increasing size.

That way you could balance a high update frequency and accurate realtime data with the ability to have a very long backlog (months/years), where the precision will drop down to lower values instead (e.g. one update per minute/hour/day).

**Comment by ktsaou** [comment]
yes this would be nice.

**Comment by thinrope** [comment]
While this concept seems very interesting for some cases, is there any backend that implements this?

Or are you talking just combining several sampling frequencies with and aggregation function?
This can be done in RRD, as well as whisper (http://graphite.readthedocs.io/en/latest/whisper.html)

**Comment by cakrit** [comment]
I think that we haven't classified this correctly, the point of this thread is to store data for longer periods, with lower sampling rates as we go further to the past. I'm pretty sure that it's part of our design for the new DB, perhaps not using a logarithmic function. @mfundul what do you think?

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
