### ISSUE TITLE
netdata installer blocked due to CloudFlare Captcha

### ISSUE THREAD

**Issue by lucasRolff** [netdata/netdata#11185]
##### Bug report summary

It seems like sometimes CloudFlare flags IPs as "not nice" which results in a Captcha challenge for my-netdata.io - when being on a server, it's hard for us to to solve the captcha.

```
# curl -IXGET https://my-netdata.io/kickstart-static64.sh -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
HTTP/2 403
date: Tue, 25 May 2021 14:57:02 GMT
content-type: text/html; charset=UTF-8
cf-chl-bypass: 1
permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
x-frame-options: SAMEORIGIN
cf-request-id: 0a45a08b4f0000b6b9ec919000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=GhzR1eDAMQsQufSgxC6LCpxgwPp%2Bj5OHjBHz0RJFB6ZdSCvk5fnvGfuDUIr%2FKqUR2K7RfE08RUAWHhuu%2BED6xId4sLW6BfwpWCfgsR8DaXjulwDASD8REZs55Q%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 654f9d254e7bb6b9-LUX
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
```

##### OS / Environment

```
Linux EU-LU-LUX-413 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

N/A

##### Installation method

kickstart-static64

##### Component Name

Installer

##### Steps To Reproduce

A bit hard to replicate, but get an IP that CloudFlare doesn't seem to like.

##### Expected behavior

It would be ideal to have the installer script where captcha is disabled, or maybe an alternative place to fetch it (Maybe fetching the installer script directly from git's master branch is fine, assuming master is considered "stable").

**Comment by ilyam8** [comment]
@Ferroin can you help with this issue?

Relevant link: https://support.cloudflare.com/hc/en-us/articles/200170056-Understanding-the-Cloudflare-Security-Level

**Comment by Ferroin** [comment]
In general, fetching directly from the master branch here on GitHub is safe. I’ve been trying to push for just using that in general for some time now, but have been unsuccessful because then we can’t see how many times people download the script.

**Comment by ilyam8** [comment]
Ok, but we set "Security Level" for a reason and are not going to change it, correct?

**Comment by ilyam8** [comment]
I am thinking we could change it from Medium (the default according to doc) to Low and that is it 🤔

**Comment by Ferroin** [comment]
> Ok, but we set "Security Level" for a reason and are not going to change it, correct?

That would be a question for @netdata/cloud-sre, as they are the ones generally responsible for that part of our infrastructure.

**Comment by ilyam8** [comment]
Closing is for now. But we are still waiting for @netdata/cloud-sre response.
