### ISSUE TITLE
GNU autotools fails to determine version when using release archives

### ISSUE THREAD

**Issue by diizzyy** [netdata/netdata#11214]
Currently configure.ac relies on git and that netdata is in a git repo to determine version which fails since the packaged version isn't a valid git repo and relying on git for packaging isn't ideal.

Ref:
https://github.com/netdata/netdata/blob/master/configure.ac#L8

OS: FreeBSD 13
Tested version: 1.31.0 (it's been broken for quite some time now)

**Comment by Ferroin** [comment]
@netdata/agent It would be great if we could fix this. The ideal behavior is that if we are not in a git repo, we look at `packaging/version`. The code in `configure.ac` looks like it _should_ be behaving this way, but it appears to not do so at least for some systems, so we definitely have a bug somewhere.

I would volunteer to work on this, but I’m unfortunately a bit busy with the installer overhaul at the moment.

**Comment by cpipilas** [comment]
Fixed in latest versions
