### ISSUE TITLE
fix eBPF installer flag --enable-ebpf

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#11227]
##### Bug report summary

If I provide the installer with `--enable-ebpf` it means I specifically ask to build `ebpf` (as a user I say I really want this feature). In such case, if there is a failure to use it the error need to be more explicit and not some hidden warning on line 235 out of 2000 of installer output.

Currently, it just prints a warning that users need to search for in the log and he will just be wondering why the charts are missing..

##### Installation method
./netdata-installer.sh
##### Component Name
eBPF build system/installer
##### Steps To Reproduce
for example install netdata with flag `--enable-ebpf` on system where `packaging/check-kernel-config.sh` fails
##### Expected behavior
To keep the pattern of netdata and in general the behaviour should be:
- default - try to build, warn if can't but continue
- disable-XYZ - don't even attempt build
- enable-XYZ - I really want this feature. If you can't build it **be loud and let me know why!**

**Comment by Ferroin** [comment]
This should probably just fail the build, though it’s far from the only such case...

**Comment by ilyam8** [comment]
> To keep the pattern of netdata
> This should probably just fail the build

My understanding of the pattern - the build should never fail (especially if the component is optional)

**Comment by ilyam8** [comment]
> In such case, if there is a failure to use it the error need to be more explicit and not some hidden warning on line 235 out of 2000 of installer output.

I remember @Ferroin added a nice `defer errors` feature, so you can read all the errors at the end of the output

**Comment by Ferroin** [comment]
If a user asked for a feature, and we can not provide it, then we should fail the build. Period.

If you go to get a pizza with a specific set of toppings, but the restaurant is out of one of those toppings, do you expect them to make the pizza without that topping and only tell you after they get it to your table, or should they ask you what to do _before_ making the pizza? The principle is the same here.

IOW, we should be replicating the same tristate logic used in most configure scripts for optional features:

* If the user asked for the feature to be disabled, don’t build it at all.
* If the user asked for the feature to be enabled, fail the build if we can’t build with it enabled.
* Otherwise, try to build it if the dependencies are present, but do not fail the build if it can’t be built for some reason.

**Comment by ilyam8** [comment]
[It wasn't my view](https://github.com/netdata/netdata/issues/11227#issuecomment-856824259) how it should work, just said that it doesn't look like the current pattern.

**Comment by underhood** [comment]
> [It wasn't my view](https://github.com/netdata/netdata/issues/11227#issuecomment-856824259) how it should work, just said that it doesn't look like the current pattern.

Well it is what I do on ACLK side and know from most other SW (3 state configure flags).... my apologies for assuming (probably incorrectly) that was the netdata pattern

**Comment by underhood** [comment]
> make the pizza without that topping and only tell you after they get it to your table
in this case it is more like they make pizza without that topping and you only discover it after you started eating

**Comment by ilyam8** [comment]
> only discover it after you started eating

[I expect all of them to be printed to the terminal](https://github.com/netdata/netdata/blob/master/netdata-installer.sh#L1894) at the end of the output.

**Comment by ilyam8** [comment]
@underhood @Ferroin you guys suggesting screwing up half-cooked pizza if there is no one ingredient. What a waste 😄 

(jokes aside - i personally have nothing against this approach (if it is not a pizza ofc))

**Comment by Ferroin** [comment]
> > only discover it after you started eating
> 
> [I expect all of them to be printed to the terminal](https://github.com/netdata/netdata/blob/master/netdata-installer.sh#L1894) at the end of the output.

Agreed, we should definitely be making more active use of the deferred error reporting functionality than we currently are.

**Comment by thiagoftsm** [comment]
Keep active!

**Comment by thiagoftsm** [comment]
Keep active!
