### ISSUE TITLE
Disable the local dashboard not working

### ISSUE THREAD

**Issue by marionassef** [netdata/netdata#11250]
##### Bug report summary
Hi, 
I'm trying to disable the local dashboard by edit "mode = none" but it doesn't work, still can access 
Netdata dashboard on 19999 port, 
[web]
        # ssl key = /opt/netdata/etc/netdata/ssl/key.pem
        # ssl certificate = /opt/netdata/etc/netdata/ssl/cert.pem
        # tls version = 1.3
        # tls ciphers = none
        # ses max window = 15
        # des max window = 15
        # mode = none
        # web files owner = netdata
        # web files group = netdata
        # disconnect idle clients after seconds = 60
        # timeout for first request = 60
       # accept a streaming request every seconds = 0
        # respect do not track policy = no
        # x-frame-options response header =
        # allow badges from = *
        # allow badges by dns = heuristic
        # allow netdata.conf from = 
        # allow netdata.conf by dns = no
        # enable gzip compression = yes
        # gzip compression strategy = default
        # gzip compression level = 3
        # web server threads = 2
        # web server max sockets = 256

please advice

##### OS / Environment
Ubuntu 16.04.7 LTS

```

```

##### Netdata version
 v1.31.0-61-gd1ec82a81

##### Installation method
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)

##### Steps To Reproduce

1. ...
2. ...

##### Expected behavior
can't access the dashboard on port 19999, dashboard should be accessible only from the cloud

**Comment by ilyam8** [comment]
Hey @marionassef, [you need to remove `#`](https://learn.netdata.cloud/docs/agent/web/server#configuration).

**Comment by marionassef** [comment]
@ilyam8 thanks bud, my bad
