### ISSUE TITLE
Unable to build on Oracle Linux 8.3 VM

### ISSUE THREAD

**Issue by vibhutigupta** [netdata/netdata#11260]
I am getting the following error, I even tried running install-required-packages.sh and then reinstalled using netdata installer but ended up with same issue. 

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues

 FAILED

 ABORTED  netdata-installer.sh exited with error
****

**Comment by MrZammler** [comment]
Hi @vibhutigupta ! Thanks for your report! We'll try to replicate, it's probably some missing dependencies!

**Comment by Ferroin** [comment]
This _may_ be related to a problem we0re having on CentOS 8 right now. Can you try installing libarchive and rerunning the Netdata installer? If it’s the same issue as the one on CentOS 8 that _should_ get things working.

**Comment by MrZammler** [comment]
I've just tried on a clean Oracle Linux 8.3, and I think libuv-devel is missing here... Configure fails with 
`checking for uv_fs_scandir_next in -luv... no
configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.`

And `dnf --setopt=strict=0 install libuv-devel` returns `No match for argument: libuv-devel`, guess it's no longer in default repositories...

**Comment by Ferroin** [comment]
Ah, yeah, that’s probably the case.

I’m not sure how we would get header files for libuv on OEL though, we have to depend on a third-party repo for RHEL/CentOS 8 as it is because of questionable choices made by RHEL (which seem to now be inherited by OEL).

We probably have a similar issue on whatever the most recent release of Amazon Linux is as well for exactly the same reason.

**Comment by MrZammler** [comment]
@vibhutigupta Can you try installing `libuv-devel` using `yum install https://yum.oracle.com/repo/OracleLinux/OL8/distro/builder/x86_64/getPackage/libuv-devel-1.40.0-1.el8.x86_64.rpm` and try to build again please?

@Ferroin Yes, not sure if it should be automated by the installer or provide instructions to the user....

**Comment by vibhutigupta** [comment]
@MrZammler It worked, Thanks guys for a quick turnaround.

**Comment by Ferroin** [comment]
@MrZammler We should add it to the installer. The better question is whether that’s a repo we can enable or not, as that would be preferred to pulling in single packages.
