### ISSUE TITLE
kickstart-static64.sh is corrupt

### ISSUE THREAD

**Issue by vanpelt** [netdata/netdata#11266]
##### Bug report summary

The MD5 is no longer d80cb6e7b48f2825aade13120ec5364d as described [here](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64).  When attempting to run it, it throws the following error:

```
/tmp/netdata.sh: line 427: syntax error: unexpected end of file
```

This is the tail of the file:

```
if [ -n "${NETDATA_CLAIM_TOKEN}" ]; then
  progress "Attempting to claim agent to ${NETDATA_CLAIM_URL}"
  NETDATA_CLAIM_PATH=/opt/netdata/bin/netdata-claim.sh

  if "${NETDATA_CLAIM_PATH}" -token=${NETDATA_CLAIM_TOKEN} -rooms=${NETDATA_CLAIM_ROOMS} -url=${NETDATA_CLAIM_URL} ${NETDATA_CLAIM_EXTRA}; then
    progress "Successfully claimed node"
  else
    run_failed "Unable to claim node, you must do so manually."
  fi
fi
laim node, you must do so manually."
  fi
fi
```

##### OS / Environment

Docker

##### Netdata version

Latest

##### Installation method

Kickstart Static

##### Steps To Reproduce

```
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)
```

##### Expected behavior

Your installer should work and your CI should detect an MD5 change, update docs, and run the installer.

**Comment by Ferroin** [comment]
The script itself is indeed corrupted due to it having been incorrectly updated on the web server hosting it. Working on fixing it right now.

**Comment by Ferroin** [comment]
The copy on the web server has been fixed now. It may take an hour or so for the effects to propagate through any downstream caches though.
