### ISSUE TITLE
alarm-notify.sh has invalid conditional statements for sendmail

### ISSUE THREAD

**Issue by raytracy** [netdata/netdata#11261]
##### Bug report summary

**alarm-notify.sh  cannot import the EMAIL_SENDER variable setting to change the sender name, and always send mail using netdata as sender.**

##### OS / Environment

uname -a; grep -Hv "^#" /etc/*release
```
Linux fada-lavender.mori.cloud 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 8.4.2105
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="8"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="8"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="CentOS Linux 8"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:8"
/etc/os-release:HOME_URL="https://centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-8"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="8"
/etc/plesk-release:18.0.36.0
/etc/plesk-release:Plesk Obsidian 18.0
/etc/redhat-release:CentOS Linux release 8.4.2105
/etc/system-release:CentOS Linux release 8.4.2105

```
##### Netdata version

netdata -W buildinfo
```
Version: netdata v1.31.0
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' '--with-libJudy=externaldeps/libJudy' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

##### Installation method

**bash <(curl -Ss https://my-netdata.io/kickstart.sh)  --stable-channel --dont-wait** 

##### Component Name

health_alarm_notify.conf
alarm-notify.sh

##### Steps To Reproduce

1. ./edit-config health_alarm_notify.conf
2. find and change EMAIL_SENDER to (ex:) ="lavender \<lavender@hostname.tld\>"
3. test notification email as per:
https://learn.netdata.cloud/docs/agent/health/notifications
4. check received email

##### Expected behavior

I would expected received a email which display sender name as configured _lavender_, but it always display _netdata_ as sender name whatever I change the MAIL_SENDER to anything in health_alarm_notify.conf

------
Debug:

I found that the line #918 in /usr/libexec/netdata/plugins.d/alarm-notify.sh has code as:
[ -n "${sender_name}" ] && sendmail --help 2>&1 | grep -q "\-F " && opts+=(-F "${sender_name}")

The conditional statement:
sendmail --help 2>&1 | grep -q "\-F "
actually not work in my OS.

I have tested in CentOS 8/7, both of them will stuck with this statement and waiting for a stdin input. That cause the check failed and abandoned the next opts+'(-F command, which should fill in the correct sender name.

I have try to modify this line as:
[ -n "${sender_name}" ] && opts+=(-F "${sender_name}")

Now it can send out the correct sender name as I have configured.

Since I don't know what is the correct way to fix the problem, I would like report this issue to you for reference.

BTW, the netdata v1.26.0-333-nightly version has no this issue since it did not do the sendmail --help checking.

**Comment by ilyam8** [comment]
Hey @raytracy 

Try to change it to 

```bash
[ -n "${sender_name}" ] && sendmail --help 2>&1 | grep -q "\-F " && opts+=(-F "${sender_name}")
```

---

> The conditional statement:
sendmail --help 2>&1 | grep -q "-F
actually not work in my OS.
I have tested in CentOS 8/7, both of them will stuck with this statement and waiting for a stdin input.

You forgot to add closing `"`

**Comment by ilyam8** [comment]
That condition were added in https://github.com/netdata/netdata/pull/10631

**Comment by raytracy** [comment]
> Try `sendmail --help 2>&1 | grep -q "\-F " && echo 1`

It still not working in my CentOS 8/7, this command did not echo anything, just hang on there and waiting for me to type some thing until I press Ctrl-C to break it.

**Comment by ilyam8** [comment]
@raytracy could you try `sendmail -xxx`? The idea was to get _Usage_ adding any unrecognized option.

**Comment by MrZammler** [comment]
Hi!

Ok, we could probably catch this if we check whether `sendmail` is actually a symlink to busybox. If it is, then don't set `-F`.

`-F` _should_ be missing only on busybox `sendmail`. Other `sendmail` implementations (i.e. from postfix) should be ok, and should be safe to set `-F` then.

What do you think @ilyam8 ?

Btw, I will try to install busybox to check for sure, but when I tried on Gentoo and enabled busybox's symlinks, Gentoo package manager failed to do so and responded with:
```

setting USE=make-symlinks and emerging to / is very dangerous.
 it WILL overwrite lots of system programs like: ls bash awk grep (bug 60805 for full list).
 If you are creating a binary only and not merging this is probably ok.
 **set env VERY_BRAVE_OR_VERY_DUMB=yes if this is really what you want.**
```

**Comment by ilyam8** [comment]
Sounds good to me.

> Btw, I will try to install busybox to check for sure.

Consider using our docker image for testing.

**Comment by Ferroin** [comment]
> Sounds good to me.
> 
> > Btw, I will try to install busybox to check for sure.
> 
> Consider using our docker image for testing.

Our Docker image doesn’t use Busybox `sendmail`, it’s got msmtp installed and set up to use as `sendmail`(because it0s just about the easiest option out there to configure, and doesn’t have this issue).

However, such testing could be done by starting the Docker image and then uninstalling msmtp with `apk del msmtp`.

**Comment by ilyam8** [comment]
Wait, is it not busybox sendmail?

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ docker exec nd sh -c 'ls -l $(which sendmail)'
lrwxrwxrwx    1 root     root            12 Apr 14 10:24 /usr/sbin/sendmail -> /bin/busybox
```

**Comment by Ferroin** [comment]
It _shouldn’t_ be, looks like we may have a bug in our docker images...
