### ISSUE TITLE
Please deprecate the node.js collector "fronius"

### ISSUE THREAD

**Issue by ccremer** [netdata/netdata#11268]
Hi.
I'm the original author that contributed the ["fronius"](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/fronius) collector based on nodejs.
I have contributed the plugin years ago but not maintained it (not that it really needed it AFAIK).

In the meantime, I have developed an alternative [Prometheus exporter](https://github.com/ccremer/fronius-exporter) in Go.
I don't intend to further maintain or support the netdata collector for Fronius if there would be an issue with it. 
If you have a deprecation strategy, you are free to activate that.

Or alternatively and if you want to keep the fronius data collection as part of netdata, you could integrate the exporter as a pure data-collector client without the Prometheus parts in go.d.plugin and provide config migration instructions.
I would also be open for ideas/PRs if the exporter could be optimized for better go.d.plugin integration.
However, unfortunately I don't intend to contribute such a migration to go.d.plugin by myself.

(I'm not sure if I'm at the right place. Feel free to transfer/triage this issue wherever it's appropriate.)

**Comment by ilyam8** [comment]
Yeah, we are going to deprecate it.

**Comment by OdysLam** [comment]
Thanks for letting us know @ccremer :)

**Comment by ilyam8** [comment]
Will do that, no need to keep the issue open.
