### ISSUE TITLE
split snmp.conf into several conf files possible?

### ISSUE THREAD

**Issue by l2isbad** [netdata/netdata#1126]
it is realy a pain to manage one conf file in json when number of devices are increasing.
is it possible to make snmp module to load configuration from more then one  file?

**Comment by irizzi** [comment]
+1
It will be very useful...
and if a file has bad syntax bypass it and continue.

**Comment by l2isbad** [comment]
Syntax not a big problem with [jsonlint](https://github.com/zaach/jsonlint)

**Comment by irizzi** [comment]
ok. but in any case there would be a better management

**Comment by ktsaou** [comment]
yes, I will do if we manage to collect 20+ different SNMP configurations.

I suggest to make PRs adding sample configurations to https://github.com/firehol/netdata/blob/master/conf.d/node.d/snmp.conf.md

At the point we will have 20 different of them, I will create a subdirectory, put them all there and have the SNMP module configuration `node.d/snmp.conf` to just point the ones the user needs loaded.

**Comment by irizzi** [comment]
monitor ups

`"hostname": "x.x.x.x",
            "community": "public",
            "update_every": 5,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
            "charts": {
                "ups.volts": {
                    "title": "voltage",
                    "units": "V",
                    "type": "line",
                    "priority": 1,
                    "family": "ups",
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.33.1.3.3.1.3.1",
                            "algorithm": "absolute",
                            "multiplier": 1,
                            "divisor": 1
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.33.1.4.4.1.2.1",
                            "algorithm": "absolute",
                            "multiplier": 1,
                            "divisor": 1
                        },
                        "batt": {
                            "oid": "1.3.6.1.2.1.33.1.2.5.0",
                            "algorithm": "absolute",
                            "multiplier": 1,
                            "divisor": 10
                        }
                    }
                }`


monitor mikrotik ethernet interface
` "hostname": "x.x.x.x",
            "community": "public",
            "update_every": 2,
            "max_request_size": 50,
            "options": { "timeout": 5000 },
            "charts": {
                "ether X": {
                    "title": "ether X",
                    "units": "Kbps",
                    "type": "area",
                    "priority": 10,
                    "family": "mikrotik",
                    "dimensions": {
                        "in": {
                            "oid": ".1.3.6.1.2.1.31.1.1.1.X.9",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024
                        },
                        "out": {
                            "oid": ".1.3.6.1.2.1.31.1.1.1.X.9",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1048576
                        }
                    }
                }`

and more available soon

**Comment by ktsaou** [comment]
Use 3 apostrophes to list the in block mode.

Please give at least a title to each config, and preferably fork the repo, change the file a pointed above and make a PR.

**Comment by ktsaou** [comment]
A title, like `UPS XXX model A, version 3` or `Mikrotik model A, firmware 1.0`

**Comment by l2isbad** [comment]
[In telecommunications, the use of the SI definition of the unit is the standard](https://en.wikipedia.org/wiki/Megabit).  So for interface bandwidth divisor eq 1000/1000000/1000000 etc (Kbit/Mbit/Gbit).

**Comment by ktsaou** [comment]
I think we should find a way to support multiple config files for all modules that support jobs (python.d, node.d, etc).
This would allow applications to register themselves to netdata (install a file in a directory for letting netdata know what to collect).

We could also support `inotify` so that netdata can configure itself at runtime.

@l2isbad 	what do you think?
@cakrit 	we probably need this on our roadmap.

**Comment by l2isbad** [comment]
All jobs in 1 file looks better to me. I like 1 config file + `reload` feature

**Comment by ktsaou** [comment]
I didn't mean to remove this feature.

But we could support (eg for `web_log`):

- `/etc/netdata/python.d/web_log.conf`
- `/etc/netdata/python.d/web_log.d/` having a `.conf` file for each job.

Both at the same time.

**Comment by l2isbad** [comment]
This is `split snmp.conf into several conf files possible` feature request. So @gmosx :smile:

**Comment by ktsaou** [comment]
I think we need this generally. Check #4731 

I am closing this. Let's discuss this issue there.

**Comment by cakrit** [comment]
We're proceeding in #6432
