### ISSUE TITLE
"uknown_alert" fired from my host

### ISSUE THREAD

**Issue by r33int** [netdata/netdata#11279]
##### Bug report summary

Hello, I am using Netdata Cloud to monitor my hosts. Sometimes, my Proxmox host fires a critical "uknown_alert" with a very high value. This happens on moderate system load in a VM/container (installing software for example). When I click this alert, the panel is loading forever, so I have no way to know where this alert comes from.

![image](https://user-images.githubusercontent.com/22567851/123139538-a080be80-d456-11eb-8e73-6d7317baba43.png)

![image](https://user-images.githubusercontent.com/22567851/123139528-9c54a100-d456-11eb-9efb-e20eb2c1dfbb.png)

##### OS / Environment

```
Linux pve01 5.4.106-1-pve #1 SMP PVE 5.4.106-1 (Fri, 19 Mar 2021 11:08:47 +0100) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

````
Version: netdata v1.31.0
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
````

##### Installation method

Used the kickstart.sh script.

##### Component Name

I am not sure whether this bug is caused by the agent itself, or by the web interface.

##### Steps To Reproduce

1. Use the Netdata agent on a Proxmox host
2. Put a VM or container under moderate load

##### Expected behavior

The alert should not be classified as "uknown_alert", and the metric which the alert originates from should be displayed to the user.

**Comment by MrZammler** [comment]
Hi @r33int ! Thank you for your report! Do you get an email from this alert? Can you forward it please to manolis att netdata.cloud?

**Comment by r33int** [comment]
> Hi @r33int ! Thank you for your report! Do you get an email from this alert? Can you forward it please to manolis att netdata.cloud?

Hi, thank you for your reply! Nope, I did not get any email from this alert.
Cheers

**Comment by ilyam8** [comment]
Issue moved to [netdata/netdata-cloud #139](https://github.com/netdata/netdata-cloud/issues/139) via [**ZenHub**](https://www.zenhub.com/)
