### ISSUE TITLE
Handle build parameter --disable-https

### ISSUE THREAD

**Issue by MrZammler** [netdata/netdata#11277]
##### Bug report summary

When the flag `--disable-https` is provided to the installer, the agent fails to build. We should handle such cases perhaps during configure, and maybe disable parts of the agent that need it, so it can be built without SSL.

##### OS / Environment

```
Linux 6am 5.10.27-gentoo #17 SMP Thu Jun 3 09:05:47 EEST 2021 x86_64 AMD Ryzen 5 4500U with Radeon Graphics AuthenticAMD GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.7
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo/Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:HOME_URL="https://www.gentoo.org/"
/etc/os-release:SUPPORT_URL="https://www.gentoo.org/support/"
/etc/os-release:BUG_REPORT_URL="https://bugs.gentoo.org/"
```

##### Installation method

`netdata-installer.sh`

##### Steps To Reproduce

1. Try to build with: `./netdata-installer.sh --disable-https`

##### Expected behavior

Should be able to build the agent.

**Comment by Ferroin** [comment]
The problem child is probably `dbengine`. I forget _why_ it depends on linking against `libcrypto`, but I’m fairly certain that it does not build correctly without it. Most likely this is just a case of the interdependencies between configure options not being handled correctly.

**Comment by thiagoftsm** [comment]
> The problem child is probably `dbengine`. I forget _why_ it depends on linking against `libcrypto`, but I’m fairly certain that it does not build correctly without it. Most likely this is just a case of the interdependencies between configure options not being handled correctly.

Dbengine uses few functions from `openssl` in some parts of the [code](https://github.com/netdata/netdata/blob/107bb52b0139701368d9d53370be8504e312b228/database/engine/rrdengineapi.c#L25-L32). Support for `TLS` and `Dbengine` was brought more or less during the same period of time, but I do not remember which feature was merged before, probably we have some problems with our autoconf files as @Ferroin said.

**Comment by MrZammler** [comment]
I think (and as Timo also mentioned), we should also disable cloud when https is disabled. Right now for me at least, it fails to build with just `--disable-https` on aclk (but does build if I add `--disable-cloud`).

?

**Comment by MrZammler** [comment]
Thanks @ilyam8 for remind me this, will check if it still applies.

**Comment by ilyam8** [comment]
Just checked 

> ./netdata-installer.sh --install /opt --disable-https

and it worked for me without any problems.

**Comment by MrZammler** [comment]
> Just checked
> 
> > ./netdata-installer.sh --install /opt --disable-https
> 
> and it worked for me without any problems.

Hmmm, does it try to compile aclk-ng when you tested it ? (It still breaks here, e.g:

```
aclk/aclk.c: In function 'load_private_key':
aclk/aclk.c:51:9: warning: implicit declaration of function 'RSA_free' [-Wimplicit-function-declaration]
   51 |         RSA_free(aclk_private_key);
      |         ^~~~~~~~
```

**Comment by ilyam8** [comment]
You are right, it doesn't work when compiling with aclk-ng.

**Comment by cpipilas** [comment]
Closing since all relevant PRs have been merged.
