### ISSUE TITLE
netdata does not start

### ISSUE THREAD

**Issue by maravento** [netdata/netdata#11275]
Ubuntu 20.04.2 LTS
kernel 5.4.0-77-generic
netdata v1.19.0
netdata.conf
```
[global]
        run as user = netdata
        web files owner = root
        web files group = root
        # Netdata is not designed to be exposed to potentially hostile
        # networks. See https://github.com/netdata/netdata/issues/164
        bind socket to IP = 127.0.0.1
```

firewall: Everything from "lo", "127.0.0.1" is accepted. Port 19999 is open

**possible bug:**

```
netdata.service - netdata - Real-time performance monitoring
     Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-06-22 17:01:34 -05; 12min ago
       Docs: man:netdata
             file:///usr/share/doc/netdata/html/index.html
             https://github.com/netdata/netdata
    Process: 52675 ExecStart=/usr/sbin/netdata -D (code=exited, status=1/FAILURE)
   Main PID: 52675 (code=exited, status=1/FAILURE)

jun 22 17:01:34 server netdata[52675]: 2021-06-22 17:01:34: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
jun 22 17:01:34 server netdata[52675]: LISTENER: IPv4 bind() on ip '127.0.0.1' port 19999, socktype 1 failed.
jun 22 17:01:34 server netdata[52675]: LISTENER: Cannot bind to ip '127.0.0.1', port 19999
jun 22 17:01:34 server netdata[52675]: LISTENER: Cannot listen on any API socket. Exiting...
jun 22 17:01:34 server netdata[52675]: EXIT: netdata prepares to exit with code 1...
jun 22 17:01:34 server netdata[52675]: EXIT: cleaning up the database...
jun 22 17:01:34 server netdata[52675]: Cleaning up database [0 hosts(s)]...
jun 22 17:01:34 server systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
jun 22 17:01:34 server netdata[52675]: EXIT: all done - netdata is now exiting - bye bye...
jun 22 17:01:34 server systemd[1]: netdata.service: Failed with result 'exit-code'.
```
port is not in use and there is no access to localhost: 19999

`netstat -nat | grep 19999`
out: nothing

```
sudo /usr/sbin/netdata -D
2021-06-22 17:39:26: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Segment violation
```
**measures (netdata or netdata.service):**
```
sudo apt purge netdata && sudo apt install netdata
sudo systemctl stop netdata && sudo systemctl start netdata && sudo systemctl status netdata
netdata.service - netdata - Real-time performance monitoring
     Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-06-22 18:39:04 -05; 203ms ago
       Docs: man:netdata
             file:///usr/share/doc/netdata/html/index.html
             https://github.com/netdata/netdata
   Main PID: 340316 (netdata)
      Tasks: 9 (limit: 18941)
     Memory: 2.4M
     CGroup: /system.slice/netdata.service
             └─340316 /usr/sbin/netdata -D

jun 22 18:39:04 server systemd[1]: Started netdata - Real-time performance monitoring.
jun 22 18:39:04 server  netdata[340316]: SIGNAL: Not enabling reaper
jun 22 18:39:04 server netdata[340316]: 2021-06-22 18:39:04: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
```
screenshot

![Captura de pantalla -2021-06-22 18-51-40](https://user-images.githubusercontent.com/14880802/123014123-2800fb80-d38b-11eb-892b-694d2d4c4a5b.png)
![Captura de pantalla -2021-06-22 18-51-49](https://user-images.githubusercontent.com/14880802/123014127-29322880-d38b-11eb-8f81-82dd99435347.png)
![Captura de pantalla -2021-06-22 18-51-59](https://user-images.githubusercontent.com/14880802/123014129-29cabf00-d38b-11eb-85fe-145f7ced32e0.png)
![Captura de pantalla -2021-06-22 18-52-10](https://user-images.githubusercontent.com/14880802/123014131-2a635580-d38b-11eb-8563-fee05d0eea53.png)

PD: installation via: `apt netdata` because it is for a server and requires the most stable version possible
via `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` this does not happen (netdata v1.31.0-76-nightly)

**Comment by thiagoftsm** [comment]
Hello @maravento ,

This is a very old Netdata version, our current version is 1.31. If you want to install a stable version using `apt`, my suggestion is to use our stable repo, you can see the instructions [here](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages)

You can use `kicksstart` to get the stable version, but it will be necessary to pass as argument `--stable-channel`, for more details you can take a look [here](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart).

Any doubt, please, let us know.

Best regards!

**Comment by maravento** [comment]
and it is not easier to update the ubuntu/debian repositories with the latest more stable version

**Comment by thiagoftsm** [comment]
> And isn't it easier to update the debian/ubuntu repositories?

I am Slackware user, so I confess I do not know. @Ferroin I will transfer this question for you.

> PD: I have [published a post](https://www.maravento.com/2021/06/netdata.html) to avoid this kind of unnecessary confusion

About your post "¡Muchas Gracias! Me gustó mucho leelo :smile:, pido disculpas por no tenermos una instalación sencília en Debian/Ubuntu, pero no tenga duas que nos vamos a hacer todo el posibile para las personas haceren la instalación de netdata en sus computadoras de una manera más sencilia."
