### ISSUE TITLE
Netdata initial kickstart installation fails on Big Sur 

### ISSUE THREAD

**Issue by samrafalowski** [netdata/netdata#11291]
##### Bug report summary

When I run `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --install /usr/local/netdata`,
<img width="1135" alt="Screen Shot 2021-06-29 at 4 30 11 PM" src="https://user-images.githubusercontent.com/10368337/123863242-589ae500-d8f7-11eb-8f77-41c39d377135.png">
<img width="1139" alt="Screen Shot 2021-06-29 at 4 30 20 PM" src="https://user-images.githubusercontent.com/10368337/123863243-59337b80-d8f7-11eb-91a4-cbc122864d3c.png">
<img width="1132" alt="Screen Shot 2021-06-29 at 4 30 27 PM" src="https://user-images.githubusercontent.com/10368337/123863245-59cc1200-d8f7-11eb-9f1b-53e55196b74f.png">
<img width="1139" alt="Screen Shot 2021-06-29 at 4 30 34 PM" src="https://user-images.githubusercontent.com/10368337/123863247-59cc1200-d8f7-11eb-8de6-fa923c3835c1.png">
 the installation fails with ```[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-judy-XXXXXX.Ur90gZKl/libjudy-1.0.5-netdata2]# env CFLAGS=-fPIC CXXFLAGS= LDFLAGS= aclocal
env: aclocal: No such file or directory
 FAILED
 FAILED  Failed to build libJudy.
 --- Run autotools to configure the build environment ---
[/private/var/folders/sj/rbq_yfzs647_xv9939sh_wvh0000gn/T/netdata-kickstart-XXXXXXXXXX.Hltbuibj/netdata-v1.31.0-90-g09549ae6d]# autoreconf -ivf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I build/m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
 FAILED```

##### OS / Environment

MacOS Big Sur 11.4

##### Netdata version

n/a, installation fails

**Comment by ilyam8** [comment]
Closing this in favor of #10422 (the same issue - the kickstart script doesn't work on Big Sur).
