### ISSUE TITLE
Netdata.cloud email notification 'localhost' issue

### ISSUE THREAD

**Issue by cybertechsolution** [netdata/netdata#11290]
I recently set up a netdata on my 4 nodes and im managing and monitoring the data of all 4 nodes on netdata.cloud. But I'm frustrated by one issue, when I received a mail of warning or critical issue it never mentions the node name I have given in the conf file of netdata nor it uses the hostname I given to my node, instead it just says 'localhost' on literally every node which is not distinguishable when it comes to monitoring and analyzing the alerts on mail. Please dig into this. I think it's a bug, but if I'm missing something please let me know.

**Comment by ilyam8** [comment]
Hey, @cybertechsolution. Sorry for the late reply. I believe it has been fixed, please verify and let us know if you still have the problem.
