### ISSUE TITLE
python.d/smartd_log triggering alarms with python.d_job_last_collected_secs

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#11305]
##### Bug report summary

I am getting alarms once per day with my current configuration using python.d/smartd_log
The alarm is for 
Chart: netdata.runtime_smartd_log
Family: python.d
I have attempted to fix by increasing the value of `update_every: 10` in my `smartd_log.conf`
This does not fix the issue.
After looking deeper into the problem I can see that the alarm is thrown every time my logs are rotated by logrotate.
I have the following config set for logrotate:
```
/var/log/smartd/*.csv {
   copytruncate
   daily
   rotate 1
   compress
   notifempty
   missingok
}
```
Every time logrotate runs the alarm triggers. Checking the logs, there is no gap in the data as I have `copytruncate` set.
I have the following in my /etc/default/smartmontools configuration:
`smartd_opts="-A /var/log/smartd/ -i 600"`
So smartd adds a line to the .csv file every 10 seconds.
Checking the rotated log files, I can see there is no gap in the data. The last line of the rotated file is exactly 10 seconds from the first line in the truncated file.

I've also noticed that the Netdata Monitoring charts for netdata.runtime_[chart] are labeled in units ms (milliseconds) but all the settings in the config files are in seconds. 
In `health.d/python.d.plugin.conf` The alarm has `calculation $now - $last_collected_t` which is going to be in milliseconds but the  warning is `5 * $update_every` and `$update_every` would be set in seconds.  Don't know if that has something to do with it.

##### OS / Environment

```
OS:         Ubuntu 20.04.2 LTS (focal)

```

##### Netdata version

```
Version: netdata v1.31.0-92-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-cloud' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           NO (by user request)
    ACLK Next Generation:    NO
    ACLK Legacy:             NO
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES shared-lib
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

##### Component Name

collectors/python.d.plugin/smartd_log/smartd_log.chart.py

##### Steps To Reproduce

1. ...
2. ...

##### Expected behavior
Should not be getting alarms related to the rotation of log files.

**Comment by ilyam8** [comment]
@Steve8291 Thanks for reporting the issue!

Meanwhile, until it is fixed, you can modify [python.d_job_last_collected_secs](https://github.com/netdata/netdata/blob/365a8fb8bad397856f110595a65373c0b5ec47a1/health/health.d/python.d.plugin.conf#L4-L17) by excluding `smartd_log` module.

`module: *` => `module: !smartd_log *`

**Comment by Rishabhraghwendra18** [comment]
Hi @ilyam8 . may I also work with you on this issue ?

**Comment by ilyam8** [comment]
Hey, @Rishabhraghwendra18. That would be awesome. Do you use `smartd_log` collector?

**Comment by Rishabhraghwendra18** [comment]
@ilyam8 Sorry for late reply due to health issues I was not able to reply . No I haven't used `smartd_log` collector . I am first timer you can say . I will like to give it a try
