### ISSUE TITLE
Chart legend displays misleading value depending on zoom level

### ISSUE THREAD

**Issue by FailedShack** [netdata/netdata#11317]
##### Bug report summary

This issue is similar to #9373 however this time in regards to the values displayed in chart legends, as they seem to be calculated from an average, when in this case the preferred outcome would be a sum for the given time range.

##### OS / Environment

```
Firefox 89.0.2
netdata (Docker) on Ubuntu 20.04
```

##### Netdata version

```
netdata v1.31.0-101-nightly
```

##### Installation method

```
Docker
```

##### Component Name

```
web and/or daemon
```

##### Steps To Reproduce

Create a chart with an absolute value which counts the number of occurrences of an event since the previous value.
View the chart in the web, then hover your mouse over the peaks. Notice how the values in the legend differ at different zoom levels.

At this point in time, a single "share" expired.
<img width="1037" alt="shares_real" src="https://user-images.githubusercontent.com/39192928/124651335-134c5980-de9b-11eb-932f-812e6586d63b.png">

When we zoom out, it tells us that 0.33 shares expired instead. This is wrong.
Note how it also says a single share was accepted. If you zoom back in, the actual number of accepted shares was 3.
<img width="1041" alt="shares_misleading" src="https://user-images.githubusercontent.com/39192928/124651265-fc0d6c00-de9a-11eb-8e48-eadc645d911a.png">

##### Expected behavior

The displayed amounts matched the real amount of shares which were either accepted or expired during a given time period, regardless of zoom level. From what I can tell, it is performing some kind of average during that timespan, when the desirable outcome would be a sum. There is as far as I can tell no way to switch between them.

We are using an absolute value because if it were incremental, it would give the amount of shares accepted or expired *per second*. This is not what I'm looking for.

**Comment by ilyam8** [comment]
Hi, @FailedShack.

>  it is performing some kind of average during that timespan

You are correct, you get average when zooming out. That is the same issue as #9373.
