### ISSUE TITLE
Cannot establish websocket to api.netdata.cloud without IPv6

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#11327]
@ohthehugemanatee commented on [Fri Jul 09 2021](https://github.com/netdata/helmchart/issues/225)

To reproduce:
- Boot a system with `ipv6.disable=1` on the kernel command line
- Install netdata with `ACLK-Legacy` and claim to the cloud
- Observe failure logs:
```
ERROR : ACLK_Main : Libwebsockets: Unable to open socket
 (errno 97, Address family not supported by protocol)
```

There are two possible changes we could make to address this:

1) Document IPv6 in the requirements section of the relevant docs, OR
2) Gracefully fall back to IPv4. 

---

Used image: [netdata:v1.31.0](https://hub.docker.com/layers/netdata/netdata/v1.31.0/images/sha256-94efb3ba63c66bf042621c6347fc3ea4e81f93338e7d7f443de21c29e733bcb1)

**Comment by underhood** [comment]
Probably related to https://github.com/netdata/netdata/pull/11080

maybe we need to build LWS without IPv6 support on such systems or take a look at `LWS_FALLBACK_GETHOSTBYNAME`

**Comment by ilyam8** [comment]
Closing this as wontfix. @underhood if you think that we still need to get this fixed for ACLK legacy, please reopen.

**Comment by underhood** [comment]
I think it is reasonable. Legacy will be removed in one or two releases completely.
