### ISSUE TITLE
#netdata IRC channel

### ISSUE THREAD

**Issue by FedericoCeratto** [netdata/netdata#11325]
There is now a #netdata IRC channel on Libera Chat, intended to replace the existing channel on Freenode 
Related to #742

**Comment by OdysLam** [comment]
That's awesome! We have a large number of different platforms, including discord and a forum.

Would you be able to provide us with a link? Unfortunately, I don't have a huge experience with IRC :)

**Comment by FedericoCeratto** [comment]
Some clients might support this URI `ircs://irc.libera.chat:6697/netdata`
There's also an experimental webchat: https://web.libera.chat/#netdata

Perhaps bridging the channel with other platform would be useful

**Comment by ilyam8** [comment]
Thanks, @FedericoCeratto!
