### ISSUE TITLE
Auto refreshing of charts does not work properly, because data points appear in the future

### ISSUE THREAD

**Issue by albert-92** [netdata/netdata#11324]
#### Summary

My fresh netdata installation is not working properly (on an aws ec2 instance).

Right after the installation it works for a few seconds, but then suddenly a data point in the future (like 15-20 min ahead of time) appears and the auto updating of the charts in the web interface does not work anymore (see screenshot below).

![2021-07-08 16_30_29-ip-10-9-65-56 netdata dashboard](https://user-images.githubusercontent.com/23524318/124941391-0a7a9580-e00b-11eb-9e8d-f94916790c15.png)

I already tried versions v1.31.0 and v1.24.0. Same problem with both versions.

Does anybody know what's going on or how to solve this problem?

**Comment by MrZammler** [comment]
Hi @albert-92 ! Thank you for your report.

Can you please share your `error.log` file (usually located under `/var/log/netdata/` please? 

Thank you!

**Comment by albert-92** [comment]
> Hi @albert-92 ! Thank you for your report.
> 
> Can you please share your `error.log` file (usually located under `/var/log/netdata/` please?
> 
> Thank you!

Sure. There is one INFO dominating the log. I guess it is related to the issue:

```
...
2021-07-14 16:40:38: netdata INFO  : HEALTH : Ignoring metric with out of order timestamp.
2021-07-14 16:40:38: netdata INFO  : HEALTH : Ignoring metric with out of order timestamp.
2021-07-14 16:40:38: netdata INFO  : HEALTH : Ignoring metric with out of order timestamp.
2021-07-14 16:40:38: netdata INFO  : HEALTH : Ignoring metric with out of order timestamp.
2021-07-14 16:40:38: netdata LOG FLOOD PROTECTION too many logs (201 logs in 0 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 1200 seconds.
2021-07-14 16:43:03: nfacct.plugin INFO  : MAIN : NFACCT process exiting
```

**Comment by MrZammler** [comment]
Hi @albert-92, thanks! Just to rule it out, can you check that there's not something weird with the system clock, ie. adjusting at some point to another data/time via ntp perhaps?

**Comment by albert-92** [comment]
That was the first thing i checked, but it seems to be fine:

```
                      Local time: Wed 2021-07-14 17:12:46 CEST
                  Universal time: Wed 2021-07-14 15:12:46 UTC
                        RTC time: Wed 2021-07-14 15:11:38
                       Time zone: Europe/Berlin (CEST, +0200)
       System clock synchronized: no
systemd-timesyncd.service active: yes
                 RTC in local TZ: no

```

**Comment by MrZammler** [comment]
Yes, long shot, but had to check :-)

So, does it happen on every restart of netdata? What method was used to install? Can you also check that there's not two or more instances of netdata running? Are you using dbengine as memory mode? Is it possible please to send the complete error.log file to manolis at netdata dot cloud?

From the screenshot you attached, I assume it works okay up to 16:31:30 and then suddenly (and instantly) goes to 16:39:00, at that point the system time is 16:31 ?

Thanks!

**Comment by ilyam8** [comment]
>  Is it possible please to send the complete error.log file to manolis at netdata dot cloud?

I think having [a snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) could be also useful. @albert-92, please!

**Comment by albert-92** [comment]
> So, does it happen on every restart of netdata? What method was used to install? Can you also check that there's not two or more instances of netdata running? Are you using dbengine as memory mode? Is it possible please to send the complete error.log file to manolis at netdata dot cloud?

Yes it happens on ever restart. I did a fresh _Automatic one-line installation script_ and the problem still occurs. I removed all netdata files previous to the fresh install. Only 1 instance is running in memory mode.

> From the screenshot you attached, I assume it works okay up to 16:31:30 and then suddenly (and instantly) goes to 16:39:00, at that point the system time is 16:31 ?

Exactly!

I sent you the error.log and snapshot.

**Comment by ilyam8** [comment]
@albert-92 

The snapshot you sent us has gaps only on external collectors charts (apps, python.d). Can you wait until (let's say) `system.cpu` chart stops showing the metrics and then do a snapshot?

---


And I noticed [python nvidia_smi](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nvidia_smi#nvidia-gpu-monitoring-with-netdata) module consumes ~a lot of CPU.

Consider
- disabling [`loop_mode`](https://github.com/netdata/netdata/blob/03002eb22812ca342a591e9b961821e2c0afdcd1/collectors/python.d.plugin/nvidia_smi/nvidia_smi.conf#L64).
- increasing [`update_every`](https://github.com/netdata/netdata/blob/03002eb22812ca342a591e9b961821e2c0afdcd1/collectors/python.d.plugin/nvidia_smi/nvidia_smi.conf#L23) for this module to 10.

Or you can [disable it completely](https://github.com/netdata/netdata/blob/03002eb22812ca342a591e9b961821e2c0afdcd1/collectors/python.d.plugin/python.d.conf#L77) as a part of debugging.

**Comment by albert-92** [comment]
> The snapshot you sent us has gaps only on external collectors charts (apps, python.d). Can you wait until (let's say) `system.cpu` chart stops showing the metrics and then do a snapshot?

Oh sorry i though it included gaps in all metrics. I disabled python nvidia_smi, deleted the cache and sent you guys a new snapshot.

**Comment by MrZammler** [comment]
Well, it seems that the snapshot can't pick up the gaps, as in the screenshot (on the latest snapshot you sent...)

The screenshot shows a metric collected at about 17:15, a gap up until 17:23:57 when there is another metric being collected.

When I load the snapshot (netdata-ip-10-9-65-56-20210715-165857-540.snapshot) I see constant values from 17:59 up to 18:07:15... At the same time the local windows machine shows (from the screenshot) 17:08 (it could be you have 1 hour difference between local and the instance).

In the error.log there are also log lines starting with `2021-07-15 13:05:01` which then turn to `2021-07-15 13:03:58` at some point...

It is evident that the instance is under load, and it could somehow mess with netdata working correctly... Is it perhaps possible to run for a while netdata on it's own, and see if we can link the machine load with this behaviour?

Thank you very much for your help!

**Comment by albert-92** [comment]
Ok, so it looks like the system time is drifting / jumping. This might cause the problem in netdata.

```
-@-:~$ chronyc tracking
Reference ID    : A9FEA97B (169.254.169.123)
Stratum         : 4
Ref time (UTC)  : Tue Jul 20 08:29:45 2021
System time     : 0.000000000 seconds slow of NTP time
Last offset     : +0.000004305 seconds
RMS offset      : 0.000008808 seconds
Frequency       : 2.974 ppm slow
Residual freq   : +0.004 ppm
Skew            : 0.245 ppm
Root delay      : 0.000317649 seconds
Root dispersion : 0.000294169 seconds
Update interval : 16.1 seconds
Leap status     : Normal

-@-:~$ chronyc tracking
Reference ID    : A9FEA97B (169.254.169.123)
Stratum         : 4
Ref time (UTC)  : Tue Jul 20 08:29:26 2021
System time     : 68.951713562 seconds fast of NTP time
Last offset     : +68.995574951 seconds
RMS offset      : 21.818315506 seconds
Frequency       : 2.974 ppm slow
Residual freq   : +0.261 ppm
Skew            : 0.245 ppm
Root delay      : 0.000323057 seconds
Root dispersion : 0.000248578 seconds
Update interval : 0.0 seconds
Leap status     : Normal

```

I was not able to solve the time problem yet. As soon as it is fixed, i'll let you know if it also resolves the problem with netdata.

**Comment by albert-92** [comment]
Okay, so the problem emerged due to some conflicts of ntp and puppet on my aws ec2 instance. This caused the system time to jump / drift and netdata apparently got confused. 

After solving the time issues on my system, netdata is also working fine. So it was not a netdata error.

**Comment by MrZammler** [comment]
Thank you @albert-92 for your follow up!
