### ISSUE TITLE
Unable to suppress cgroup specific charts

### ISSUE THREAD

**Issue by fti-cneve** [netdata/netdata#11321]
I'm running netdata on a debian 10 (buster). I need to suppress/hide following list of charts from netdata.
```
- CPU Usage (100% = 1 core) Per Core (cgroup_xxxx_ctr.cpu_per_core)
- CPU Usage within the limits (cgroup_xxxx_ctr.cpu_limit)
- Interface Duplex State (net_duplex)
- Memory Activity (cgroup_xxxx_ctr.mem_activity)
- Memory Page Faults (cgroup_xxxx_cr.pgfaults)
- Memory Utilization (cgroup_xxxx_ctr.mem_utilization)
- Used RAM within the limits (cgroup_xxxx_ctr.mem_usage_limit)
```

Unfortunately in netdata.conf I found that, We can only disable **"CPU Usage (100% = 1 core) Per Core (cgroup_xxxx_ctr.cpu_per_core)"** through netdata.conf. ( Please correct me if I am wrong. ) And **"Interface Duplex State (net_duplex)"** is also possible to disable but in that case we need to specify interface (for eg. eth0) here explicitly.

I would like to disable all of the above remaining cgroup charts from netdata. 
Are we going to support for disable cgroups charts through netdata configuration file in upcoming releases of netdata??

OS / Environment:
Debian 10 (buster)
Netdata Version: v1.31.0

Output of uname -a; grep -Hv "^#" /etc/*release # Linux

Linux buildhost 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
Output of netdata -W buildinfo.

Configure options:  '--prefix=/opt/score' '--with-user=netdata' '--sysconfdir=/opt/score/etc' '--localstatedir=/opt/score' '--with-zlib' '--with-math' '--with-jemalloc=/opt/score' '--enable-https' '--enable-plugin-nfacct' 'CFLAGS=-I/opt/score/include -ftree-vectorize'
Features:
    dbengine:                NO
    Native HTTPS:            YES
    Netdata Cloud:           NO 
    TLS Host Verification:   YES
Libraries:
    jemalloc:                YES
    JSON-C:                  NO
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     NO 
    mosquitto:               NO
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO

**Installation method**
from github, using make

**Comment by vlvkobal** [comment]
Please look at the relevant [comment](https://community.netdata.cloud/t/how-to-disable-some-of-the-cgroups-charts-from-netdata/1451/2?u=vlvkobal) on our community forum.

As for the `net_duplex` charts - you can disable them for all interfaces:
```
[plugin:proc:/proc/net/dev]
	duplex for all interfaces = no
```

I'm closing the issue. If you have any questions, please consider using the [community forum](https://community.netdata.cloud).
