### ISSUE TITLE
Scheduled “downtime” for a type of check?

### ISSUE THREAD

**Issue by haasn** [netdata/netdata#1133]
I have a scheduled `zpool scrub` that runs at a fixed time and day. During this time, `netdata` likes to go crazy with `disk utilization` warnings because the zfs scrub consumes all idle disk bandwidth, often switching between disks during the course of the scrub.

In other notification systems like icinga2, I can schedule a fixed downtime period for any given check, e.g. “don't warn me about ‘disk’ checks on the first of a month from 1:00 to 6:00”. It would be great if I could do the same for netdata alarms.

**Comment by ftpproxy** [comment]
I do have the same problem with a scheduled task. I would like to vote for that feature!

**Comment by dpointk** [comment]
I'd like to vote for this feature too. Tx.

**Comment by pm73** [comment]
I also have this problem. I will probably disable this check completely to stop e-mails with alerts.

**Comment by ktsaou** [comment]
Yes, this is really needed.

**Comment by Ferroin** [comment]
This is likely going to require work on the C side of things, which is a bit beyond my current expertise.  I can still help with it, but it may get done faster if someone else is involved.

**Comment by Ferroin** [comment]
Closing in favor of #3187, as that has slightly more fleshed out discussion.
