### ISSUE TITLE
netdata-updater fails with No rule to make target 'aclk/aclk-schemas/proto/agent/v1/connection.proto'

### ISSUE THREAD

**Issue by jason-azze** [netdata/netdata#11339]
##### Bug report summary

I have been running Netdata for many months with netdata-updater successfully running from `/etc/cron.daily/netdata-updater`. At some time in the last few weeks (today is 2021-07-14), anacron began reporting failures. Yesterday I got around to checking. :smiley: 

The error is:
```
No rule to make target 'aclk/aclk-schemas/proto/agent/v1/connection.proto'
```
To attempt a fix, I re-ran `netdata-installer.sh` from yesterday's latest release. It seemed that this fixed the problem and I was successfully upgraded to `v1.31.0-116-nightly`. I then manually ran `netdata-updater.sh` and it reported that no update was needed.

Unfortunately the error is back again today as netdata-updater tries to get me to version `v1.31.0-118-nightly`.

##### OS / Environment

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
```

##### Netdata version
```
Version: netdata v1.31.0-116-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' '--with-bundled-libJudy' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                NO
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    ACLK Next Generation:    NO
    ACLK Legacy:             YES
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```
##### Installation method

I installed with the netdata one-liner method for Linux, then re-installed by downloading the latest tarball, expanding it, and running the installer from inside the resulting `netdata-master` directory.

##### Component Name

`netdata-updater.sh` (but really some `make` target that can't be satisfied as written)

##### Steps To Reproduce

Run (in my case) `/etc/cron.daily/netdata-updater` as root, or allow `anacron` to do its thing.

##### Expected behavior

Netdata should be updated, or if no update is needed, the updater should do nothing.

##### Appendix
Here's the make error with some additional surrounding context:
```
rm -f web/api/queries/sum/*.o
rm -f web/api/tests/*.o
rm -f web/server/*.o
rm -f web/server/static/*.o
test -z "" || rm -f 
test -z "" || rm -f 
test -z "test-suite.log" || rm -f test-suite.log
make[1]: Leaving directory '/tmp/netdata-updater-xcYmj87VKk/netdata-v1.31.0-118-gfd9e87e8a'
 OK   

 --- Compile netdata --- 
[/tmp/netdata-updater-xcYmj87VKk/netdata-v1.31.0-118-gfd9e87e8a]# make -j32 
make: *** No rule to make target 'aclk/aclk-schemas/proto/agent/v1/connection.proto', needed by 'aclk/aclk-schemas/proto/agent/v1/connection.pb.cc'.  Stop.
 FAILED   

Wed 14 Jul 2021 08:24:44 AM EDT : ERROR:  FAILED TO UPDATE NETDATA : FAILED TO COMPILE/INSTALL NETDATA
```

**Comment by MrZammler** [comment]
Hi @jason-azze ! Thank you for reporting this!

The problem has been addressed with https://github.com/netdata/netdata/pull/11338, and it new nightly tarballs from today should be ok!

**Comment by johnpiers** [comment]
I can confirm that this issue has been resolved, @underhood (On Discord) was of massive assistance. :-)

**Comment by MrZammler** [comment]
Great! Thanks!
