### ISSUE TITLE
RHEL/CentOS rpm installation missed default stock configuration

### ISSUE THREAD

**Issue by tuzkiyoung** [netdata/netdata#11344]
##### Bug report summary

RHEL/CentOS rpm installation missed default stock configuration

##### OS / Environment
 CentOS 7.9. And I also tested on CentOS 7.8 and Debian 10.9.

##### Netdata version
v1.31.0 stable channel

##### Installation method

RPM

##### Component Name

configuration

##### Steps To Reproduce
1. update yum repo
2. yum install netdata

##### Expected behavior
In the current version of netdata via YUM installation, the default configuration missed the "stock config directory" in the [global] section and the "stock health configuration directory", "enable stock health configuration" in the [health] section.
I deployed netdata and my customized config files which do not have these two configurations with Ansible, and this issue makes the deployment failed.
I used to maintain the same config files whatever the OS is. And this really troubles me cause I have to maintain another config file just for CentOS!
Oh, one more thing, the installation procedure does not make the folder /usr/lib/netdata/conf.d.
Pls fix this bug ASAP. THX

**Comment by ilyam8** [comment]
> Oh, one more thing, the installation procedure does not make the folder /usr/lib/netdata/conf.d.

Hey, @tuzkiyoung.

I just installed [Netdata v1.31.0](https://packagecloud.io/netdata/netdata) on Centos8 (docker container) and the directory has been created.

```cmd
[root@82816876ba5f ~]# ls -l /usr/lib/netdata/conf.d
total 136
-rw-r--r-- 1 root root 10498 May 19 11:50 apps_groups.conf
-rw-r--r-- 1 root root   190 May 19 11:50 aws_kinesis.conf
drwxr-xr-x 2 root root  4096 Sep 30 08:52 charts.d
-rw-r--r-- 1 root root  1534 May 19 11:50 charts.d.conf
drwxr-xr-x 2 root root  4096 Sep 30 08:52 ebpf.d
-rw-r--r-- 1 root root  1609 May 19 11:50 ebpf.d.conf
-rw-r--r-- 1 root root  2595 May 19 11:50 exporting.conf
-rw-r--r-- 1 root root  1233 May 19 11:50 fping.conf
drwxr-xr-x 2 root root  4096 Sep 30 08:52 go.d
-rw-r--r-- 1 root root  1474 Feb 20  2021 go.d.conf
drwxr-xr-x 2 root root  4096 Sep 30 08:52 health.d
-rw-r--r-- 1 root root 46906 May 19 11:50 health_alarm_notify.conf
-rw-r--r-- 1 root root    57 May 19 11:50 health_email_recipients.conf
-rw-r--r-- 1 root root  1010 May 19 11:50 ioping.conf
-rw-r--r-- 1 root root  1310 May 19 11:50 node.d.conf
drwxr-xr-x 2 root root  4096 Sep 30 08:52 python.d
-rw-r--r-- 1 root root  2057 May 19 11:50 python.d.conf
drwxr-xr-x 2 root root  4096 Sep 30 08:52 statsd.d
-rw-r--r-- 1 root root  8209 May 19 11:50 stream.conf
```
