### ISSUE TITLE
Logs monitoring

### ISSUE THREAD

**Issue by mo0nsniper** [netdata/netdata#1134]
I think a good addition to netdata would be the option to see the system logs.
This way you can check what happend in the logs when a chart had a spike.

I know that netdata collects only metrics now but maybe there would be a way for doing this.

**Comment by Tap3** [comment]
Hi,

I use [ccze](https://github.com/cornet/ccze) for colourized my log file. But add a lightweight log viewer in netdata 'ill be great.

**Comment by ktsaou** [comment]
I really like this idea, but we need to find a way of doing efficiently at the edge.

**Comment by cakrit** [comment]
Assigning to myself, to discuss and split work.

**Comment by ktsaou** [comment]
@cakrit 	low priority. This is important, but not now.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
