### ISSUE TITLE
Is there an option to compress data before it is streamed?

### ISSUE THREAD

**Issue by sniffski** [netdata/netdata#11343]
Hi Guys,
Great work and appreciate your efforts in making monitoring so powerful and easy to use!
I am facing an issue with excess data sent out of my computer, after some digging I've found out that netdata is streaming huge amount of data to my streaming collector server. I am using it to monitor my laptop's performance and all worked well until I've had to switch to metered connection and just in two days I've manage to use all my data...
Is there an option to make netdata compress the data before it is streamed?

**Comment by MrZammler** [comment]
Hi @sniffski !

Sorry for our late reply... Currently there is no support for compressing streaming data. However there are currently ongoing efforts to re-visit this area (streaming/replication).

I'm not sure how feasible is to use an external way to compress the traffic, i.e. if using openvpn (and the streaming traffic goes over it) to enable compression on it...

**Comment by ilyam8** [comment]
As @MrZammler correctly said, unfortunately, there is no support for compressing streaming data at the moment, but we've added this feature request to our backlog.
