### ISSUE TITLE
noslav @ethcc on macos

### ISSUE THREAD

**Issue by noslav** [netdata/netdata#11353]
    ~/Doc/c/m/go-ethereum  on   feature/multicall !2 ?2  ssh -i /Users/pranay/Downloads/ethcc_netdata root@51.159.190.143
               _
 ___  ___ __ _| | _____      ____ _ _   _
/ __|/ __/ _` | |/ _ \ \ /\ / / _` | | | |
\__ \ (_| (_| | |  __/\ V  V / (_| | |_| |
|___/\___\__,_|_|\___| \_/\_/ \__,_|\__, |
                                    |___/

Welcome on Docker + Docker-Compose + gosu + pipework (GNU/Linux 4.4.0-134-generic x86_64 )

System information as of: Tue Jul 20 09:57:49 UTC 2021

System load:	0.93		Int IP Address:	10.197.164.143
Memory usage:	0.0%		Pub IP Address:	51.159.190.143
Usage on /:	2%		Swap usage:	0.0%
Local Users:	2		Processes:	149
Image build:	2019-03-07	System uptime:	17:19 hours
Disk :	l_ssd 150G
Disk :	b_ssd 25G
Disk :	l_ssd 150G

Documentation:	https://github.com/scaleway-community/scaleway-docker
Community:	https://github.com/scaleway-community/scaleway-docker
Image source:	https://github.com/scaleway-community/scaleway-docker

Docker 18.09.0 is running using the 'overlay2' storage driver.
Installed tools: docker-compose, nsenter, gosu and pipework are installed.
Last login: Tue Jul 20 09:52:16 2021 from 91.197.138.36
root@scw-epic-wright:~# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version:
 --- Fetching script to detect required packages... ---
[/tmp/netdata-kickstart-9H0lTwNEGN]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-9H0lTwNEGN/install-required-packages.sh https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh  OK

 --- Running downloaded script to detect required packages... ---
[/tmp/netdata-kickstart-9H0lTwNEGN]# /bin/bash /tmp/netdata-kickstart-9H0lTwNEGN/install-required-packages.sh netdata Loading /etc/os-release ...

/etc/os-release information:
NAME            : Ubuntu
VERSION         : 16.04.5 LTS (Xenial Xerus)
ID              : ubuntu
ID_LIKE         : debian
VERSION_ID      : 16.04

We detected these:
Distribution    : ubuntu
Version         : 16.04
Codename        : 16.04.5 LTS (Xenial Xerus)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2 (will install python3 too)

Searching for distro_sdk ...
Searching for gcc ...
 > Checking if package 'gcc' is installed...
dpkg-query: no packages found matching gcc
Searching for autoconf ...
 > Checking if package 'autoconf' is installed...
dpkg-query: no packages found matching autoconf
Searching for autoconf_archive ...
 > Checking if package 'autoconf-archive' is installed...
dpkg-query: no packages found matching autoconf-archive
Searching for autogen ...
 > Checking if package 'autogen' is installed...
Searching for automake ...
 > Checking if package 'automake' is installed...
dpkg-query: no packages found matching automake
Searching for libtool ...
 > Checking if package 'libtool' is installed...
dpkg-query: no packages found matching libtool
Searching for pkg_config ...
 > Checking if package 'pkg-config' is installed...
dpkg-query: no packages found matching pkg-config
Searching for cmake ...
 > Checking if package 'cmake' is installed...
dpkg-query: no packages found matching cmake
Searching for libz_dev ...
 > Checking if package 'zlib1g-dev' is installed...
dpkg-query: no packages found matching zlib1g-dev
Searching for libuuid_dev ...
 > Checking if package 'uuid-dev' is installed...
dpkg-query: no packages found matching uuid-dev
Searching for libmnl_dev ...
 > Checking if package 'libmnl-dev' is installed...
dpkg-query: no packages found matching libmnl-dev
Searching for json_c_dev ...
 > Checking if package 'libjson-c-dev' is installed...
dpkg-query: no packages found matching libjson-c-dev
Searching for libuv ...
 > Checking if package 'libuv1-dev' is installed...
dpkg-query: no packages found matching libuv1-dev
Searching for lz4 ...
 > Checking if package 'liblz4-dev' is installed...
dpkg-query: no packages found matching liblz4-dev
Searching for openssl ...
 > Checking if package 'libssl-dev' is installed...
dpkg-query: no packages found matching libssl-dev
Searching for judy ...
 > Checking if package 'libjudy-dev' is installed...
dpkg-query: no packages found matching libjudy-dev
Searching for libelf ...
 > Checking if package 'libelf-dev' is installed...
dpkg-query: no packages found matching libelf-dev

The following command will be run:

NOTE: Running apt-get update and updating your APT caches ...
apt-get update
apt-get install autoconf autoconf-archive autogen automake cmake gcc libelf-dev libjson-c-dev libjudy-dev liblz4-dev libmnl-dev libssl-dev libtool libuv1-dev pkg-config uuid-dev zlib1g-dev

Press ENTER to run it >
NOTE: Running apt-get update and updating your APT caches ...
apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:5 http://ppa.launchpad.net/scaleway/stable/ubuntu xenial InRelease
Hit:6 http://security.ubuntu.com/ubuntu xenial-security InRelease
Reading package lists... Done
apt-get install autoconf autoconf-archive autogen automake cmake gcc libelf-dev libjson-c-dev libjudy-dev liblz4-dev libmnl-dev libssl-dev libtool libuv1-dev pkg-config uuid-dev zlib1g-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gcc : Depends: cpp (>= 4:5.3.1-1ubuntu1) but it is not going to be installed
       Depends: gcc-5 (>= 5.3.1-3~) but it is not going to be installed
       Recommends: libc6-dev but it is not going to be installed or
                   libc-dev
 libssl-dev : Depends: libssl1.0.0 (= 1.0.2g-1ubuntu4) but 1.0.2g-1ubuntu4.13 is to be installed
              Recommends: libssl-doc but it is not going to be installed
 libtool : Depends: cpp but it is not going to be installed
           Depends: libc6-dev but it is not going to be installed or
                    libc-dev
 uuid-dev : Depends: libc6-dev but it is not going to be installed or
                     libc-dev
            Depends: libuuid1 (= 2.27.1-6ubuntu3) but 2.27.1-6ubuntu3.6 is to be installed
 zlib1g-dev : Depends: zlib1g (= 1:1.2.8.dfsg-2ubuntu4) but 1:1.2.8.dfsg-2ubuntu4.1 is to be installed
              Depends: libc6-dev but it is not going to be installed or
                       libc-dev
E: Unable to correct problems, you have held broken packages.

We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/netdata/netdata/issues

##### OS / Environment

```

```

##### Netdata version

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues

 FAILED

 ABORTED  netdata-installer.sh exited with error

##### Steps To Reproduce

1. ...
2. ...

**Comment by ilyam8** [comment]
Hey, @noslav. Please, adjust the OP according to our [bug template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md), and update the title. It is not clear what the problem is.
