### ISSUE TITLE
Cannot send alarms to multiple MS Teams channels

### ISSUE THREAD

**Issue by KeemoLV** [netdata/netdata#11354]
I cannot figure out how to send alarm notification to multiple MS team channels. I've configured health_alarm_notify.conf, and I can send to one channel without any problems. So, my MSTEAMS_WEBHOOK_URL is right. My DEFAULT_RECIPIENT_MSTEAMS looks like this `DEFAULT_RECIPIENT_MSTEAMS="CHANNEL1_ENCODED CHANNEL2_ENCODED"`. But when I run alarm-notify.sh test it sends alarm twice to the first channel.

**Comment by KeemoLV** [comment]
If I add 3 channels, it will send the test alarm 3 times to one channel.

**Comment by ilyam8** [comment]
Hi, @KeemoLV. Please update the issue according to [the bug template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md) (summary, netdata version, install method, etc.).

**Comment by ilyam8** [comment]
@KeemoLV I think I've found the problem, can you test #11355?

**Comment by KeemoLV** [comment]
Sorry, I couldn't test this earlier. This indeed fixed my problem, thank you very much. 

I've got one more question. I have channel dedicated to critical alarms, and one for all other alarms. Can I exclude critical alarms from sending to that channel?

**Comment by ilyam8** [comment]
> Can I exclude critical alarms from sending to that channel?

I don't think so.

That is the only alarms severity filtering option we have

https://github.com/netdata/netdata/blob/c5732041b66e6417a7d948905525a1ce70be8f18/health/notifications/health_alarm_notify.conf#L163-L169
