### ISSUE TITLE
"Nesting of hosts is not allowed" when using GUID to access replicated nodes

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#11352]
##### Bug report summary

If I access a replicated node with `<IP>:<Port>/host/<GUID>/` then switching to another one using replicated nodes menu I get _Nesting of hosts is not allowed._ response (`<IP>:<Port>/host/<GUID>/host/<Hostname>/` URL).

[That message comes from `web_client_switch_host` function](https://github.com/netdata/netdata/blob/d2030d0241ec30a372c84656ff6a7bc3fe0c9e81/web/server/web_client.c#L1337-L1348)

##### OS / Environment

not relevant

##### Netdata version

`Version: netdata v1.31.0-132-nightly`

<details>
<summary>buildinfo</summary>

```cmd
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' '--with-bundled-libJudy' 'CFLAGS=' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    ACLK Next Generation:    YES
    ACLK Legacy:             YES
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

</details>

##### Installation method

Docker

##### Component Name

webserver

##### Steps To Reproduce

1. set up parent/child.
2. get child GUID from parent's `/api/v1/info` endpoint.
3. access the child node using GUID.
4. **click on the same child instance via replicated nodes menu.**

##### Expected behavior

Do no get "Nesting of hosts is not allowed" when using GUID to access replicated nodes.

**Comment by stelfrag** [comment]
This is minor, closing
