### ISSUE TITLE
Netdata - Nginx Plus API

### ISSUE THREAD

**Issue by nmarantos** [netdata/netdata#11364]
Hi,

We are facing an issue with netdata configuration about Nginx Plus and API.
We have installed nginx plus [ nginx/1.19.10 (nginx-plus-r24-p1) ] , we have updated netdata to the version 1.31.0 and we have tried with python 2 and 3 both to solve our issue.

We are trying to install python.d.plugin/nginx_plus (NGINX Plus monitoring with Netdata | Learn Netdata) but perhaps the plugin is based on deprecated methods from python version. The status page that the config is needed is http://localhost/api/6 and not /status, right?
We noticed that after a GET method, the json object which returns is the following error and cannot parse it.
AttributeError("‘list’ object has no attribute ‘get’")

but nginx returns
[“nginx”,“processes”,“connections”,“slabs”,“stream”,“http”,“resolvers”,“ssl”]

Can you help with the configuration and the plugin?
Do you think that there is something else to do from our side?

**Comment by ilyam8** [comment]
Hi, @nmarantos 

Answered in https://community.netdata.cloud/t/netdata-nginx-plus-api/1552/2?u=ilyam8

Related issue https://github.com/netdata/netdata/issues/6730

**Comment by ilyam8** [comment]
Hi, @nmarantos 

Answered in https://community.netdata.cloud/t/netdata-nginx-plus-api/1552/2?u=ilyam8

Related issue https://github.com/netdata/netdata/issues/6730

**Comment by nmarantos** [comment]
Hi @ilyam8 

thank you

**Comment by ilyam8** [comment]
@nmarantos let's continue the discussion on [the forum](https://community.netdata.cloud/t/netdata-nginx-plus-api/1552).

**Comment by ilyam8** [comment]
Added in https://github.com/netdata/go.d.plugin/pull/992
