### ISSUE TITLE
Netdata 1.31.0 chart API does not handle archived charts

### ISSUE THREAD

**Issue by dkennedy-dejero** [netdata/netdata#11379]
##### Bug report summary

After the change to sqlite for the chart metadata (https://github.com/netdata/netdata/issues/9658 and https://github.com/netdata/netdata/issues/9815), it seems like the api/v1/chart API entrypoint does not handle archived charts.

##### OS / Environment

`Linux/x86_64`

##### Netdata version

```
Version: netdata v1.31.0
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--with-bundled-lws=externaldeps/libwebsockets' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

##### Component Name

web/api

##### Steps To Reproduce

For a given archived chart ID:
1. api/v1/charts does not contain the chart ID - expected.
2. api/v1/archivedcharts does contain the chart ID - expected
3. api/v1/data?chart=chartId returns data fro the chart - expected
4. api/v1/chart?chart=chartId returns not found - not expected

##### Expected behavior

api/v1/chart?chart=chartId should return the description for the chart.
In particular, dashboard.js refuses to create the chart because it cannot fetch the description.

This worked correctly prior to the sqlite migration.

**Comment by dkennedy-dejero** [comment]
If I can get confirmation that the expected behavior is reasonable (as this appears to be a regression), I can start looking at creating a patch.

**Comment by stelfrag** [comment]
Hi @dkennedy-dejero well spotted. 

It is a known issue and be supported by reworking the chart / archivedcharts endpoints. The ARCHIVED state for a chart will be removed (on a running agent) as it made sense only when we kept the entire metadata always in memory (pre-sqlite) and we were rebuilding all the charts on startup. 

Although that made the charts available (in memory) the archivedcharts endpoint was never put to use so you could also end up not being able to see the archived charts in the dashboard. Keeping the archived charts in memory (and re-creating on agent startup) proved to be very inefficient and in a parent - child setup especially with ephemeral nodes this would quickly consume a lot of memory. 

For the dashboard to work, it needs the chart to appear in the /api/v1/charts (of course also the /api/v1/chart). As you have noticed the data endpoint already supports fetching data for an archived chart by accessing the sqlite database, building the necessary internal structures and finally executing the data query (and cleanup the structures afterwards). This also works for a parent - child setup and is a functionality that will be used especially for a cloud enabled setup. The api/v1/info endpoint will provide the full list of available children (even non active) so their (archived) charts can be fetched.

Stay tuned!

**Comment by dkennedy-dejero** [comment]
Making sure I understand:
Is the plan to eliminate the concept of "archived" chart, so that all charts from the current session and prior sessions are available through /api/v1/charts, /api/v1/chart and /api/v1/data, and to eliminate /api/v1/archivedcharts (undocumented anyway)?

Separately, is there any plan to shift inactive charts out of memory, or alternatively to reduce the memory footprint of charts? Our collector is currently structured to generate a lot of short-lived charts, which obviously isn't an ideal use of netdata. The result is an ever-growing memory footprint that could be reduced if inactive charts were pushed out of memory after a while (i.e. converted to archived charts, in the current implementation).

Finally, what is the timeline for the changes you described above?

**Comment by cpipilas** [comment]
Closing in favour of https://github.com/netdata/netdata/issues/10627
