### ISSUE TITLE
A node's dashboard does not show new charts in netdata registry while http://${ip}:19999 does

### ISSUE THREAD

**Issue by lwbt** [netdata/netdata#11385]
##### Bug report summary

I noticed that one of my nodes did not update in my space on https://app.netdata.cloud/spaces/. I imported more zpools (no recompiling of the agent) and added the ipmi plugin (recompiled the agent) after I first opened the node in my space. I kept the tab open. Not the browser tab, the tab in the navigation under *War Rooms* > *General*, where it reads *Overview*, *Nodes*, *Dashboards*, *Alerts*, *MY_NODE1*, *MY_NODE2* and so forth. Metrics kept streaming in but neither charts for the new zpools or ipmi data showed up. I had to close the tab---again, not the browser tab---and open the node again to find the new data and charts.

As I understand, the component that runs https://app.netdata.cloud/spaces/ is the registry, which can be self-hosted and is part of netdata agent. Sorry if I got that wrong, please tell me where to file this bug if this is the wrong place.

I have not tried to run my own registry, therefore I cannot tell if this is just an issue with the version/software that runs https://app.netdata.cloud/spaces/ or with the registry in general. http://${ip}:19999 has now issues and displays the new charts just fine.

##### OS / Environment

Same as in https://github.com/netdata/netdata/issues/11381

```
$ uname -a; grep -Hv "^#" /etc/*release
Linux za31 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=21.04
/etc/lsb-release:DISTRIB_CODENAME=hirsute
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 21.04"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="21.04 (Hirsute Hippo)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 21.04"
/etc/os-release:VERSION_ID="21.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=hirsute
/etc/os-release:UBUNTU_CODENAME=hirsute

```

##### Netdata version

```
$ netdata -W buildinfo
Version: netdata v1.31.0-142-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-plugin-freeipmi' '--with-bundled-lws' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    ACLK Next Generation:    NO
    ACLK Legacy:             YES
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO

$ $(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V
netdata v1.31.0-142-nightly

```

##### Installation method

```
$ bash <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstall --enable-plugin-freeipmi --nightly-channel

```

##### Component Name

registry

##### Steps To Reproduce

1. Install Netdata on a new node.
2. Register the node ion your space on https://app.netdata.cloud/spaces/.
3. Got to *War Rooms* > *General*, where it reads *Overview*, *Nodes* and open the detail view of the new of the hostname you just added so that it reads:  *Overview*, *Nodes*, *Dashboards*, *Alerts*, *MY_NEW_NODE*.
4. Keep this open. Make changes to the machine or the agent. I imported zpools (without recompiling netdata agent) and added ipmi monitoring plugin (with recompiling netdata agent). Both of these changes did not show up as new charts across page refreshes or closing the browser. http://${ip}:19999 has now issues and displays the new data just fine.
5. Close the tab named *MY_NEW_NODE*, open it again and find the new charts.

##### Expected behavior

Ideally the view updates without requiring to close and reopen the node's detail view tab to find new charts.

**Comment by ilyam8** [comment]
Issue moved to [netdata/netdata-cloud #128](https://github.com/netdata/netdata-cloud/issues/128) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ilyam8** [comment]
Hey, @lwbt. You are using Netdata Cloud, I moved the issue to the Netata Cloud issues tracker.
