### ISSUE TITLE
ebpf.plugin doesn't add "module" when sending CHART definition

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#11384]
##### Bug report summary

[CHART](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#chart) is

> CHART type.id name title units [family [context [charttype [priority [update_every [options [plugin [module]]]]]]]]

eBPF plugin doesn't send [module].

As the result, we have only one entry in the [api/v1/info](https://registry.my-netdata.io/swagger/#/default/get_info) response and one entry in anonymous statistics.

```json
"collectors": [

		{
			"plugin": "ebpf.plugin",
			"module": ""
		},

```

##### OS / Environment

not relevant

##### Netdata version

`Version: netdata v1.31.0-148-g561557c5a`

##### Installation method

not relevant

##### Component Name

`collectors/ebpf.plugin`

##### Steps To Reproduce

1. Netdata with running eBPF plugin.
2. Check `/api/v1/info` response.

##### Expected behavior

eBPF plugin sends [module] for all its modules charts.

**Comment by thiagoftsm** [comment]
To fix this issue it is necessary to change the helper [ebpf_write_chart_cmd](https://github.com/netdata/netdata/blob/e2303fea720871ef568a175d8a50a478154a1db8/collectors/ebpf.plugin/ebpf.c#L393-L406) and pass as argument for the function the module name. I am bringing a PR to fix this.

**Comment by ilyam8** [comment]
Closing in favor of #11388
