### ISSUE TITLE
Total TCP Connections

### ISSUE THREAD

**Issue by congdonglinux** [netdata/netdata#1140]
I want show total tcp connection from mutil host on one garph, please help me.

**Comment by ktsaou** [comment]
You can't right now in one chart, without writing javascript.
What you can do now, is show multiple charts.

I have a task in my todo to implement this in a better way.

**Comment by arulvelu21** [comment]
My question is to merge CPU and RAM alert from the same system using Line Graph . Is this possible ?

**Comment by ktsaou** [comment]
> My question is to merge CPU and RAM alert from the same system using Line Graph . Is this possible ?

Unfortunately it is not currently.

**Comment by ktsaou** [comment]
@gmosx 	this is about merging charts from multiple servers.
I have seen another one requesting the same.
It is on our roadmap.

**Comment by cakrit** [comment]
We will add this to netdata.cloud. Closing it from here.
