### ISSUE TITLE
Netdata is sometimes unable to restart

### ISSUE THREAD

**Issue by a-schaefers** [netdata/netdata#11409]
On Ubuntu 18.04 and 20.04 servers I have found on multiple servers that sometimes `systemctl restart netdata` fails. The result is that sometimes I am not receiving alerts for things until it is too late because netdata is not being automatically restarted if it e.g. were to crash. 

Here are my findings during debugging:

1. Netdata logs contain `Aug 05 18:38:55 server reset_netdata_trace.sh[24756]: /usr/libexec/netdata/plugins.d/reset_netdata_trace.sh: line 8: /sys/kernel/debug/tracing/kprobe_events: Device or resource busy`

2. The graphical web interface appears to be "working", but the systemd restart is failing.

```
sudo systemctl status netdata -l
[sudo] password for adam: 
● netdata.service - Real time performance monitoring
   Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2021-08-05 18:50:37 CDT; 11s ago
  Process: 24267 ExecStopPost=/usr/libexec/netdata/plugins.d/reset_netdata_trace.sh (code=exited, status=1/FAILURE)
  Process: 24264 ExecStart=/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D (code=exited, status=1/FAILURE)
  Process: 24262 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 24261 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 24259 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 24249 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 24264 (code=exited, status=1/FAILURE)
```

3. pgrep shows its still running while systemctl status shows it is failing. 

```
pgrep netdata -a
28081 /usr/sbin/netdata
28083 /usr/sbin/netdata --special-spawn-server
# it still has processes dangling even though it is apparently crashed according to systemd!
```

4. pstree does show it this way

```
systemd --
├─netdata─┬─apps.plugin
        │         ├─bash
        │         ├─ebpf.plugin───9*[{ebpf.plugin}]
        │         ├─go.d.plugin───20*[{go.d.plugin}]
        │         ├─netdata───{netdata}
        │         ├─python───3*[{python}]
        │         └─29*[{netdata}]
```

5.  Next step is manual kill:

`sudo kill 28081 28083`

6. Restart netdata one last time, `systemctl restart netdata` OK it works this time! YAY.

Confirm the issue does not reoccurr

```
sudo systemctl stop netdata
adam@server:~$ pgrep netdata
adam@server:~$ 
```

GOOD. No dangling processes.

I have had to do this 3 times on 3 different servers in the last 2 days.

**Comment by a-schaefers** [comment]
Regarding the graphical interface still working while systemd claims it's failed - the issue is very serious, because it is not fully functional. For example I have observed that the servers in this state are **not sending out alert emails**

**Comment by stelfrag** [comment]
Hi @a-schaefers. Thank you for reporting this!

- what version of netdata are you using? 
- what was the installation method?

**Comment by a-schaefers** [comment]
netdata v1.31.0-165-nightly
we used the kickstart script

**Comment by MrZammler** [comment]
Hi @a-schaefers ! Can you please forward the `error.log` file (preferably if you can for the time the restart failed) to manolis at netdata dot cloud?

Thank you!

**Comment by MrZammler** [comment]
`reset_netdata_trace.sh` also fails on my test system (although not at the moment the main netdata binary), and we need to take a look at that... It could perhaps cause systemd to flag the service as failing.

**Comment by thiagoftsm** [comment]
> `reset_netdata_trace.sh` also fails on my test system (although not at the moment the main netdata binary), and we need to take a look at that... It could perhaps cause systemd to flag the service as failing.

Hello @MrZammler ,

This script is not necessary, because we are using now `libbpf`, this was used only with the first eBPF versions.

**Comment by MrZammler** [comment]
Thanks @thiagoftsm ! So we should probably remove it? 

I don't think the script is the one causing the fail to the main netdata binary, as the pids show, it seems maybe like the old instances of netdata did not shutdown gracefully... We'll need to look the `error.log` for any clues...

**Comment by thiagoftsm** [comment]
> Thanks @thiagoftsm ! So we should probably remove it?
> 
> I don't think the script is the one causing the fail to the main netdata binary, as the pids show, it seems maybe like the old instances of netdata did not shutdown gracefully... We'll need to look the `error.log` for any clues...

I think so, I will make a PR for this.

**Comment by a-schaefers** [comment]
I'm still trying to find time to get that `error.log` file for you guys. Sorry for the delay. Stay tuned.

**Comment by MrZammler** [comment]
Hi @a-schaefers , sorry for not mentioning it, it should be under `/var/log/netdata/`. If there are also rotated `error.log`, we could use them as well. Thanks!

**Comment by ilyam8** [comment]
> > Thanks @thiagoftsm ! So we should probably remove it?
> > I don't think the script is the one causing the fail to the main netdata binary, as the pids show, it seems maybe like the old instances of netdata did not shutdown gracefully... We'll need to look the `error.log` for any clues...
> 
> I think so, I will make a PR for this.

Please, do!

**Comment by thiagoftsm** [comment]
> Please, do!

Done :handshake: !

**Comment by stelfrag** [comment]
@thiagoftsm so can we close this issue now? :smiley:

**Comment by thiagoftsm** [comment]
Yes @stelfrag ! :)
