### ISSUE TITLE
View/Edit All Configured Alerts 

### ISSUE THREAD

**Issue by samrafalowski** [netdata/netdata#11408]
**Goal:** 

See a complete list of all alerts in the Alerts Smartboard, including clear, warning, and critical. Each alert should be able to be edited, silenced, snoozed, and deleted from the UI. These configurations will be found in the right hand bar. 

**Acceptance Criteria**

- As a user, I want to know if there are alerts associated with a node for a specific timeframe. 
- As a user, I want to be able to sort my alerts by severity, date, value, and node name. 
- As a user, I want to be able to edit and delete an alert in the UI right hand bar. 
- As a user, I want to be able to silence an alert by pressing a silence button. 
- As a user, I want to be able to snooze an alert for a time I specify in the UI right hand bar. 
- When a user clicks on the alert, the right hand bar with configuration should open. 
- As a user, I want to be able to specify the retention time for this alert and its history in the configuration in the right hand bar. 

**Notes **
- Other user journeys to be specified

**Comment by ilyam8** [comment]
@samrafalowski , hey. It looks like this issue belongs to https://github.com/netdata/product

**Comment by ilyam8** [comment]
Issue moved to [netdata/product #2347](https://github.com/netdata/product/issues/2347) via [**ZenHub**](https://www.zenhub.com/)
