### ISSUE TITLE
dismiss alarms from the dashboard

### ISSUE THREAD

**Issue by kachkaev** [netdata/netdata#1142]
I was setting up a new dockerized project on my server yesterday. The `docker-compose.yml` file contained a definition of an internal network that was shared by a few local services. Because I was running `docker-compose up` and `docker-compose down` until I felt satisfied with the result, this network was killed and recreated several times.

It seems that netdata picked all these temporary networks and is now warning me about them being unavailable for some time:

![veth](https://cloud.githubusercontent.com/assets/608862/19516559/77dc8c34-95f4-11e6-93ba-aa34001fa035.png)

This list goes on and on.

I'm wondering if there could be any way to distinguish this case (which is obviously not something to worry about) with some real network issues. Shame that I can't suggest any solution because I'm not competent enough in how monitoring works and how docker networks are seen by the OS or netdata.

Feel free to join the discussion if you have any thoughts.

**Comment by l2isbad** [comment]
Same with ppp+ interfaces

**Comment by ktsaou** [comment]
I can think 2 solutions that can work now:

1. There is a template alarm that applies to all network interfaces. On the servers you have this issue, create alarms (copy the template) for the interfaces you want to monitor and disable the template.

2. When this happens, send a SIGUSR2 to netdata to rescan everything about its alarms

The best solution would be to dismiss this alarm from the UI. But this requires authentication to be implemented first.

**Comment by jurgenhaas** [comment]
As a follow up on the referenced issue #1163, thanks to @l2isbad, I would like to add that for the specific Docker case I would like to think that there is a difference between a Docker container shut-down and a crash. The latter should trigger alarms, the former not.

Is anything like that possible? Not seeing this distinction in @ktsaou alternatives above, so maybe there could be a third approach?

**Comment by ktsaou** [comment]
hm... what is a container crash? Does such a thing exist?

If it does not exist, then you simply don't need alarms for network interfaces attached to containers. You can disable the template, and add alarms only for the physical interfaces of the system.

On the other hand, if you need alarms to exist only under certain conditions (e.g. when a container is running), we could invent a solution where something external to netdata (a script may be), might be called to take this decision and inform netdata. Would this be something useful?

**Comment by jurgenhaas** [comment]
Responded in the other thread

**Comment by mailinglists35** [comment]
> The best solution would be to dismiss this alarm from the UI. But this requires authentication to be implemented first.

for the simple use case when just one person from one browser is looking at netdata page, can this alarm be dismissed locally in browser, without the need to ask netdata backend to write data so therefore without the need for authentication?

**Comment by ktsaou** [comment]
> for the simple use case when just one person from one browser is looking at netdata page, can this alarm be dismissed locally in browser, without the need to ask netdata backend to write data so therefore without the need for authentication?

the dashboard already does this automatically. It does not show a notification if the alarm has already be viewed by you. To see the difference, view the same dashboard with a different browser. A notification will pop-up.

**Comment by mailinglists35** [comment]
> the dashboard already does this automatically. It does not show a notification if the alarm has already be viewed by you.

hm, for me it stays on forever after I view it. I did not allow browser notifications, though.

**Comment by ktsaou** [comment]
> hm, for me it stays on forever after I view it. I did not allow browser notifications, though.

I guess you mean the badge at the top. This will not go away. Only the notification is not shown.

**Comment by mailinglists35** [comment]
> I guess you mean the badge at the top. This will not go away

yes, that badge. shall I open a separate issue if I wanted autoclearing of badge?

**Comment by cakrit** [comment]
Such alarm floods due to planned maintenance will be preventable when #3187 and #2673 are closed. Still, a way to clear/dismiss alarms in batch should be provided. We probably won't be able to do it via the UI at this stage, but I'm adding this with the others.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
