### ISSUE TITLE
More levels of hierarchy at dashboard menu

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#1143]
At least for snmp charts.
I have 100+ snmp hosts and it would be great if they could be grouped (like charts can be grouped with "family" option)
It should be on roadmap i think.

**Comment by ktsaou** [comment]
Actually, if you don't currently need the 2 levels on the SNMP servers, you could group them much the network or disk charts are grouped (i.e. each device is a family).

But, yes, we should extend the dashboard a bit to allow more or different groupings.

**Comment by ktsaou** [comment]
This is on our roadmap.
There are a couple of duplicate issues too.
