### ISSUE TITLE
Netdata no docker  monitored

### ISSUE THREAD

**Issue by 643406834** [netdata/netdata#11436]
##### Bug report summary
no docker monitor
![image](https://user-images.githubusercontent.com/39716940/129364454-9f67b99f-07a2-44a2-b5bd-dfc383fb4baf.png)

##### OS / Environment
openwrt liunx router x64 
![image](https://user-images.githubusercontent.com/39716940/129364548-7fcb7afa-0761-4caf-9745-5c7f25bc25a4.png)

```

```

##### Netdata version
netdata | 1.30.1-1
docker | 20.10.7-1
![image](https://user-images.githubusercontent.com/39716940/129364815-58abbce2-f4da-42e5-b120-8883fc211fd7.png)
![image](https://user-images.githubusercontent.com/39716940/129364996-01a16fc4-0396-44b3-8927-6be8995bdb58.png)

**Comment by ilyam8** [comment]
Hey, @643406834, what was the problem?

**Comment by 643406834** [comment]
solved：
[plugins]
	cgroups = yes

[plugin:cgroups]
	cgroups plugin resource charts = yes
	update every = 2
	check for new cgroups every = 10
	use unified cgroups = yes
	path to unified cgroups = /sys/fs/cgroup
