### ISSUE TITLE
netdata-updater failing on all of my systems with /lib/cpp failes sanity check

### ISSUE THREAD

**Issue by pnunn** [netdata/netdata#11443]
##### Bug report summary

netdata is trying to run the updater from cron and failing.

Large amounts of output that seems to work, stuff built OK etc.
Gets to protobuf and fails with the error 
checking how to run the C preprocessor... gcc -E
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/tmp/netdata-protobuf-kTxGOH/protobuf-3.17.3':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
 FAILED   

This is happening on multiple systems.

##### OS / Environment

To get this information, execute the following commands based on your operating system:
Linux cwprfw 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

Place the output from the command in the code section below. 
```
[/tmp/netdata-protobuf-kTxGOH/protobuf-3.17.3]# ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/libexec --libdir=/usr/lib --with-zlib --with-math --with-user=netdata --with-bundled-lws CFLAGS2 LDFLAGS= 
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... no
checking for FCC... no
checking for KCC... no
checking for RCC... no
checking for xlC_r... no
checking for xlC... no
checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... no
checking dependency style of g++... none
checking how to run the C preprocessor... gcc -E
checking for gcc... gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/tmp/netdata-protobuf-kTxGOH/protobuf-3.17.3':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
 FAILED   
```

##### Netdata version

<!--
Provide output of `netdata -W buildinfo`.

Version: netdata v1.31.0-192-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    ACLK Next Generation:    NO
    ACLK Legacy:             YES
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
 
If Netdata is running, execute: $(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V
netdata   146477  0.0  0.1   4028  3136 ?        SN   08:13   0:01 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata  4077223  1.2  5.9 407688 119244 ?       SNl  Aug15  71:37 /usr/sbin/netdata
netdata  4077229  0.0  0.1  26712  2228 ?        SNl  Aug15   0:00 /usr/sbin/netdata --special-spawn-server
netdata  4077492  0.0  1.1  71932 23668 ?        SNl  Aug15   5:46 /usr/bin/python3 /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata  4077493  0.6  0.2  59684  5396 ?        SN   Aug15  40:06 /usr/libexec/netdata/plugins.d/apps.plugin 1
root     4077494  0.3  0.4 860656  9016 ?        SNl  Aug15  22:55 /usr/libexec/netdata/plugins.d/ebpf.plugin 1
netdata  4077498  0.0  0.2 723632  4032 ?        SNl  Aug15   2:45 /usr/libexec/netdata/plugins.d/go.d.plugin 1

##### Installation method

cron Update

##### Component Name

protobuf

##### Steps To Reproduce

run the updater 

##### Expected behavior

I don't get emailed error logs in the morning.

**Comment by MrZammler** [comment]
Hi @pnunn , thank you for your report, we will look into it as soon as possible.

**Comment by underhood** [comment]
The correct behavior should be for installer to continue even if protobuf fails to build. Autotools can afterwards either use system protobuf in case `detect` used or disable ACLK-NG altogether.

@Ferroin I think we have to change this in installer and I will retest behavior of autotools to make sure it works as expected

**Comment by underhood** [comment]
@pnunn as @MrZammler mentioned above installing C++ compiler will fix the issue

**Comment by pnunn** [comment]
Thanks guys. Not sure this is a great answer. I'm not sure I want a c++ compiler living in my firewall.

**Comment by Ferroin** [comment]
@underhood The current behavior in the installer _should_ be to only fail the install on a failure to build protobuf if the `--require-cloud` flag was passed. Otherwise we just log the error and report it at the end of the install.

@pnunn Could you share the contents of `/etc/netdata/.environment` (assuming you’ve installed without setting a custom install prefix) on an affected system?

**Comment by Ferroin** [comment]
NVM, per discussion with @underhood on Slack, the current behavior is incorrect, so a PR will be forthcoming shortly to fix it.
