### ISSUE TITLE
Alerts Smartboard Timeline 

### ISSUE THREAD

**Issue by samrafalowski** [netdata/netdata#11448]
**Goal** 
As a user, I want to be able to view a timeline of all historical alerts that have been raised. I want to be able to select and zoom in on specific parts of the timeline to better troubleshoot issues in my node. I want to be able to see a highlight in accordance to when the alert was first raised as a warning (yellow highlight) and when the alert was raised as critical (red highlight). 

**Acceptance Criteria**

[ ] I can choose to view a timeline of one specific alert or all alerts on a node. 
[ ] The period of time where there are warning alerts will be highlighted in yellow. 
[ ] The period of time where there are critical alerts will be highlighted in red. 
[ ] I can zoom into specific parts of the alerts timeline by clicking and selecting as I do on the metrics correlations page.

**Comment by ilyam8** [comment]
@samrafalowski , hey. It looks like this issue belongs to https://github.com/netdata/product

**Comment by ilyam8** [comment]
Issue moved to [netdata/product #2348](https://github.com/netdata/product/issues/2348) via [**ZenHub**](https://www.zenhub.com/)
