### ISSUE TITLE
Fail to collect HAProxy stats site

### ISSUE THREAD

**Issue by jessie-txt** [netdata/netdata#11468]
##### OS / Environment: Ubuntu 20

```
Linux team-c-lb-svr 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version
netdata v1.31.0-222-nightly

##### Installation method
One line script

##### Component Name
`python.d/haproxy.conf`

##### Steps To Reproduce

1. Following guide in https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/haproxy with a little modification (username, oassword, port, url)
2. Not show in my netdata cloud war room

##### Expected behavior

SHOW THE CHART

**Comment by ilyam8** [comment]
Hey, @jessie-txt.

Let's [run the python.d.plugin in the debug mode](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin#how-to-debug-a-python-module) (change `<module>` to `haproxy`).

**Comment by ilyam8** [comment]
Closing due to no response.
