### ISSUE TITLE
Cannot scrape windows exporter metrics because it has more than 3000 metrics

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#11504]
##### Bug report summary
I have added windows_exporter to the prometheus exporters plugin. but it won't show me the logs, when I run it in debug mode I get the below log:
```
[ DEBUG ] build[manager] build.go:302 building prometheus[windows_exporter] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/prometheus.conf autodetection_retry:0 module:prometheus name:windows_exporter priority:70000 timeout:15 update_every:5 url:http://172.21.16.27:9182/metrics]
[ DEBUG ] run[manager] run.go:41 tick 0
[ WARN  ] prometheus[windows_exporter] collect.go:28 endpoint 'http://172.21.16.27:9182/metrics' returned 9071 time series, limit is 3000
[ ERROR ] prometheus[windows_exporter] job.go:157 check failed
```

##### OS / Environment

```
netdata docker image
```

##### Netdata version

v1.31.0

##### Installation method

Docker

##### Component Name

go.d

**Comment by ilyam8** [comment]
Hi, @yasharne.

There are [max_time_series](https://github.com/netdata/go.d.plugin/blob/9e912ff0bde663f2319f00bc315140d59c59fc91/config/go.d/prometheus.conf#L99-L102) and [max_time_series_per_metric](https://github.com/netdata/go.d.plugin/blob/9e912ff0bde663f2319f00bc315140d59c59fc91/config/go.d/prometheus.conf#L94-L97) configuration options. You can change the limit.

> but it won't show me the logs

I believe it is in the logs because the message severity level is `WARN` (not `DEBUG`). And we need to update the message, should add a note to adjust "max_time_series" option.

**Comment by yasharne** [comment]
Hi @ilyam8 
I have set `max_time_series_per_metric: 300000` and `max_time_series: 100000` but I still get this error:
```
[ WARN  ] prometheus[windows_exporter] collect.go:28 endpoint 'http://172.21.16.27:9182/metrics' returned 9071 time series, limit is 3000
```
P.S: neither `max_time_series_per_metric` nor `max_time_series`'s default values were not 3000, maybe there is another variable I should set

**Comment by ilyam8** [comment]
[3000 is the default](https://github.com/netdata/go.d.plugin/blob/9e912ff0bde663f2319f00bc315140d59c59fc91/modules/prometheus/prometheus.go#L31).

Could you show this line?

> [ DEBUG ] build[manager] build.go:302 building prometheus[windows_exporter] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/prometheus.conf autodetection_retry:0 module:prometheus name:windows_exporter priority:70000 timeout:15 update_every:5 url:http://172.21.16.27:9182/metrics]

If you have set `max_time_series` it should be in the "config" map.

---

Or show `/etc/netdata/go.d/prometheus.conf`.

**Comment by yasharne** [comment]
@ilyam8 
```
max_time_series_per_metric: 300000
max_time_series: 100000
jobs:
  - name: windows_exporter
    url: http://172.21.16.27:9182/metrics
    timeout: 15
```

**Comment by ilyam8** [comment]
@yasharne ok, I see, those are not global settings.

Try the following:

```yaml
jobs:
  - name: windows_exporter
    url: http://172.21.16.27:9182/metrics
    timeout: 15
    max_time_series: 100000
```

**Comment by yasharne** [comment]
@ilyam8 Works now thanks, I saw `global` keyword in the description of this parameter that's why I put it in global section :)
https://github.com/netdata/go.d.plugin/blob/9e912ff0bde663f2319f00bc315140d59c59fc91/config/go.d/prometheus.conf#L99-L102

**Comment by ilyam8** [comment]
I agree that is a bit misleading (a lot of text, hard to understand)

- [[ GLOBAL ]](https://github.com/netdata/go.d.plugin/blob/9e912ff0bde663f2319f00bc315140d59c59fc91/config/go.d/prometheus.conf#L12-L29)
- [[ List of JOB specific parameters ]](https://github.com/netdata/go.d.plugin/blob/9e912ff0bde663f2319f00bc315140d59c59fc91/config/go.d/prometheus.conf#L58-L184)
