### ISSUE TITLE
prometheus plugins metrics are not exposed in the netdata metrics

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#11502]
##### Bug report summary
I have configured `prometheus` plugin to scrape metrics from a [wmware exporter](https://github.com/pryorda/vmware_exporter), and the charts are shown in the netdata UI:
![screenshot_14](https://user-images.githubusercontent.com/7656049/133049372-6df12388-1a56-4199-9327-0b93f486ddba.png)
this child is streaming to a parent which is scraped by a prometheus sever, the problem is I cannot see the metric inside the prometheus server. I searched inside the metrics but none of them contains `vmware`

##### Netdata version

both parent and child `v1.31.0`

##### Installation method

Prebuilt

##### Component Name

go.d

**Comment by ilyam8** [comment]
Hi, @yasharne.

Could you try the following

> curl http://NODE:19999/api/v1/allmetrics?format=prometheus&source=as-collected | grep "[wv]mware"``

Do you get any `vmware` metrics?

**Comment by yasharne** [comment]
Hi @ilyam8 No it doesn't show anything

**Comment by ilyam8** [comment]
- you see the charts on both the child and parent dashboard
- you don't get those charts(metrics) exported when using `/api/v1/allmetrics` endpoint

Is that correct?

Keep in mind that you need to change `format=prometheus` to `format=prometheus_all_hosts` when scraping the parent.

**Comment by yasharne** [comment]
Thanks @ilyam8 the problem was now using `prometheus_all_hosts`
