### ISSUE TITLE
Health monitoring - traffic light overview

### ISSUE THREAD

**Issue by antons-** [netdata/netdata#1150]
I'm thinking about building an IoT project that uses a physical traffic light that reports on the health of our servers. The alert system in netdata would be great to hook into for this.

Something similar to this (original link https://www.raspberrypi.org/magpi/build-status-light/):
![towerlight](https://cloud.githubusercontent.com/assets/3037189/19623100/068e5bca-9919-11e6-8abc-6f043f00851c.jpg) - this is for Jenkins but the general concept is the same.

I did some digging and with an external script I could collect this information from `/api/v1/alarms`. Alarms use red for critical,  orange for warning and bright green for ok which maps perfectly to a traffic light. 

So the highest level of alert at the present moment (if any alerts at all) will dictate the color of the traffic light.

That got me thinking. It might be cool to show a traffic light inside netdata too near the top.

So may I suggest that a new endpoint is created that just reports on the overall health status? If not, that's cool, thanks for building such an awesome product! 😃

**Comment by ktsaou** [comment]
nice!

so which are the conditions? red = at least one critical alarm, yellow = at least one warning, green = no alarms?

**Comment by antons-** [comment]
What you described @ktsaou is exactly what I had in mind!

**Comment by jurgenhaas** [comment]
@antons- I couldn't resist and build something around this idea. Please have a look at https://gitlab.paragon-es.de/tools/netdata-trafficlight and let me know what you think.

@ktsaou If this is something you want to make use of, please feel free.

**Comment by ktsaou** [comment]
very nice!

**Comment by ilyam8** [comment]
> That got me thinking. It might be cool to show a traffic light inside netdata too near the top.

I believe this is implemented 😄 

<img width="938" alt="Screenshot 2021-01-28 at 20 20 35" src="https://user-images.githubusercontent.com/22274335/106174617-49780580-61a6-11eb-959b-2cbeea68e896.png">
