### ISSUE TITLE
Naming convention of LXD container graphs keep changing between versions

### ISSUE THREAD

**Issue by Kramerican** [netdata/netdata#11503]
##### Bug report summary

Up until Netdata 1.28 (at least) I could stream statistics for my LXD containers (using labels for example) using the convention:

cgroup_containername.cpu (or whatever I wanted)

Now I had to set up some new environments, and in the latest nightly - v1.31 - this has changed yet again. Now I need to access metrics using:

cgroup_lxc-payload-containername.cpu

_Why does this keep changing?_

This forces me to do a platform-wide upgrade and change lots of code to match this new naming convention so I can stream my labels properly. This is rather annoying and this is not the first time this has happened! I've seen this happen 3 or 4 times already in the years I've used Netdata, and is one of the primary reasons I no longer allow Netdata to auto-update as these are production systems that need to work. (not to mention the occasional breaking build which has accidentally been released into the wild...).

##### OS / Environment

Ubuntu in various versions 18+

##### Netdata version

Specifically v1.28 vs 1.31 in this case.

##### Installation method

kickstart

##### Expected behavior

Consistent behavior with regards to the naming convention of graphs for LXC containers.

##### Followup question:

I cannot find any documentation on installing a specific version, as I wanted to try and install v1.28 in the new systems to - well, save me some work first of all and second: Make sure this is Netdata acting up and not some changes in LXD/LXC which is causing this, as I realize this might not be the fault of Netdata at all.

**Comment by ilyam8** [comment]
Hi, @Kramerican. 

Let's see. `cgroup.plugin` uses [cgroup-name.sh](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh.in) bash script to map id's into names. These are the changes since v1.28.0

```diff
[ilyam@pc ~]$ diff v1.28.0 master
430a431,438
>   elif [[ ${CGROUP} =~ machine.slice_machine.*-lxc ]]; then
>     # libvirtd / lxc containers
> 	# examples:
> 	# before: machine.slice machine-lxc/x2d969/x2dhubud0xians01.scope
>     # after:  lxc/hubud0xians01
> 	# before: machine.slice_machine-lxc/x2d969/x2dhubud0xians01.scope/libvirt_init.scope
> 	# after:  lxc/hubud0xians01/libvirt_init
>     NAME="lxc/$(echo "${CGROUP}" | sed 's/machine.slice_machine.*-lxc//; s/\/x2d[[:digit:]]*//; s/\/x2d//g; s/\.scope//g')"
```

Added in #11006

---

Could you show

```cmd
grep "is called" error.log | grep lxc
```

**Comment by ilyam8** [comment]
We will try to be more careful with such changes in the future. Thanks for reporting @Kramerican.
