### ISSUE TITLE
Syntax Error in netdata uninstaller script

### ISSUE THREAD

**Issue by flyrobot27** [netdata/netdata#11530]
##### Bug report summary

unable to uninstall netdata using the official script with the error stating:

bash: syntax error near unexpected token `newline'

##### OS / Environment

POP OS 20.04 LTS
Linux 5.11.0-7633-generic #35~1630100930~20.04~ae2753e-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux

##### Netdata version

netdata v1.31.0-258-nightly

##### Installation method

Using provided script: bash <(curl -Ss https://my-netdata.io/kickstart.sh)

##### Component Name

netdata-uninstaller.sh

##### Steps To Reproduce

Following the guide on https://learn.netdata.cloud/docs/agent/packaging/installer/uninstall/
1. wget https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-uninstaller.sh
2. chmod +x ./netdata-uninstaller.sh
3. ./netdata-uninstaller.sh --yes --env <environment_file>

##### Expected behavior

Uninstalling netdata agent

**Comment by stelfrag** [comment]
Hi @flyrobot27 

Note that the `<environment_file>` needs to be replaced by the path of the .environment file for your installation. 

```
Find your .environment file, which is usually /etc/netdata/.environment in a default installation.
```

So the command in this case would look 

`./netdata-uninstaller.sh --yes --env  /etc/netdata/.environment`

**Comment by flyrobot27** [comment]
Looks like my brain was smooth. Thanks.
