### ISSUE TITLE
[Bug]: Dimension not stored in apps.mem

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#11542]
##### OS / Environment

Ubuntu 20.04

##### Netdata version

Latest nightly

##### Installation method

kickstart

##### Component Name

charts, dbengine

##### Steps To Reproduce

Using memory mode dbengine.
Run updater or kickstart reinstall while netdata is running and you have the UI open on the Applications memory chart. Observe the "build" dimension in Applications memory appearing.
After the updater restarts netdata, reload the dashboard. The "build" dimension is no longer there, even when zero dimensions are shown.

##### Expected behavior

"build" dimension should be there.

**Comment by stelfrag** [comment]
Cleanup / this has been resolved
