### ISSUE TITLE
Integration between eBPF and cgroups

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#11558]
The eBPF plugin will be integrated with cgroup plugin showing charts for each available cgroup. 
When the host has `systemd`, eBPF plugin will also show charts for every service running on host.

The following steps are planned to bring the full integration between collectors, according previous meetings:

- [x] Bring descriptions to dashboard, this will be used to update links later. (https://github.com/netdata/netdata/pull/11547)
- [x] Create shared memory inside cgroup plugin (https://github.com/netdata/netdata/pull/11559)
- [x] Create helpers inside eBPF plugin, modify documentation, plugin options and bring charts related to swap (https://github.com/netdata/netdata/pull/11573).
- [x] Add integration for process, file descriptor, VFS, directory cache and OOMkill (https://github.com/netdata/netdata/pull/11611)
- [x] Bring integration for socket, shared memory, and cachestat. And update documentation (https://github.com/netdata/netdata/pull/11642)
- [ ] Add alarms for cgroups

**Comment by ilyam8** [comment]
Hey, @thiagoftsm. Does it make sense to have "Add alarms for cgroups" as a separate issue?  It looks like technically the integration is done and we could close the issue.

**Comment by thiagoftsm** [comment]
I agree @ilyam8 , I will create an issue exclusively for alarms.
