### ISSUE TITLE
Can’t Acces to the dashboard from http://ip:19999

### ISSUE THREAD

**Issue by Osfuco** [netdata/netdata#11563]
Good afternoon, I just installed Netdata on my CentOS Linux 7.9.2009 (Core) server with the command that appears on github (bash <(curl -Ss https://my-netdata.io/kickstart.sh)
), but I can’t access through http: // 82. (full ip): 19999

I've tried reinstalling but doesn't works.

**Comment by MrZammler** [comment]
Hi @Osfuco !

A few questions, is your server perhaps behind a firewall? Is the port 19999 open to the outside world?

Are you getting a specific error when trying to access it? 

Did the installation complete okay, and can you see that the netdata service is indeed running?

Thanks!

**Comment by bioshazard** [comment]
Default is to serve on localhost. Can you `curl localhost:19999` on the machine its installed? If so, you need to update the `bind` config in `/etc/netdata/netdata.conf` and for full IP access, you need router port forwarding, but that would be  outside the NetData responsibility.

**Comment by ilyam8** [comment]
Closing in favour of https://community.netdata.cloud/t/cant-acces-to-the-dashboard-from-http-ip-19999/1768/2
