### ISSUE TITLE
Long/short options don't work for eBPF plugin binary

### ISSUE THREAD

**Issue by UmanShahzad** [netdata/netdata#11568]
##### Bug report summary

Long (and I believe short) options provided to the eBPF plugin are not properly applied; all other programs still get run even if only specific ones are selected.

##### Component Name

ebpf.plugin

##### Steps To Reproduce

1. Compile everything.
2. Try to run the `ebpf.plugin` binary with any long/short command and notice that all other programs still run.

##### Expected behavior

Only the selected program should run.

**Comment by thiagoftsm** [comment]
@ilyam8 it is on my horizon, I plan to fix this and the DEB packages before new release.
