### ISSUE TITLE
`plugins.d` obsolete chart

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#11590]
##### Bug report summary

As it was described [here](https://github.com/netdata/netdata/pull/11573#issuecomment-927744895), when there is inversion of values when we are obsoleting charts, this will create problems for Netdata and agent can crash.

The test was made creating the chart with the following command:

```
CHART nginx1.swap_read_call '' 'Calls to function <code>swap_readpage</code>.' 'calls/s' 'swap' '' 'line' 45100 1 '' 'ebpf.plugin' 'swap'
```

And the problem was discovered when the following obsolete line was sent:

```
CHART nginx1.swap_read_call '' 'Calls to function <code>swap_readpage</code>.' 'calls/s' 'swap' 'line' ''  45100 1 'obsolete'
```

In this example there was an inversion between `context` and `chart type`. Netdata did not crash immediately, but it was registered core dump when the agent exit.

##### OS / Environment

```
Linux thiago-virtualbox 5.10.68-1-MANJARO #1 SMP PREEMPT Wed Sep 22 12:29:47 UTC 2021 x86_64 GNU/Linux
/etc/arch-release:Manjaro Linux
/etc/lsb-release:DISTRIB_ID=ManjaroLinux
/etc/lsb-release:DISTRIB_RELEASE=21.1.4
/etc/lsb-release:DISTRIB_CODENAME=Pahvo
/etc/lsb-release:DISTRIB_DESCRIPTION="Manjaro Linux"
/etc/manjaro-release:Manjaro Linux
/etc/os-release:NAME="Manjaro Linux"
/etc/os-release:ID=manjaro
/etc/os-release:ID_LIKE=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:PRETTY_NAME="Manjaro Linux"
/etc/os-release:ANSI_COLOR="32;1;24;144;200"
/etc/os-release:HOME_URL="https://manjaro.org/"
/etc/os-release:DOCUMENTATION_URL="https://wiki.manjaro.org/"
/etc/os-release:SUPPORT_URL="https://manjaro.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.manjaro.org/"
/etc/os-release:LOGO=manjarolinux

```

##### Netdata version

netdata v1.31.0-411-g0aabb106a

##### Installation method
Compilation from master branch

##### Component Name

database

##### Steps To Reproduce

1. Change the order of `context` (6th variable) and `chart type` (7th variable) for the any call of the function [ebpf_write_chart_obsolete](https://github.com/netdata/netdata/blob/d1d630243731acc3974d3ba1b3d7b3433669ef02/collectors/ebpf.plugin/ebpf.c#L447).
2. Create an environment where a chart can be obsoleted.
3. Compile branch
4. Run commands that will force chart to be obsolete. 
5. Wait few seconds and stop agent;

##### Expected behavior

If some external plugin sends an inverted option to obsolete a chart, agent cannot crash.

**Comment by cpipilas** [comment]
No longer relevant
