### ISSUE TITLE
netdata.conf is broken after new installation

### ISSUE THREAD

**Issue by nitrogear** [netdata/netdata#11653]
##### Bug report summary

Tried to perfom a weekly upgrade with:
./netdata-installer.sh --install /opt --enable-ebpf
Compilation and installation went without any error, but config /opt/netdata/etc/netdata/netdata.conf was renewed to:
```
You are not allowed to access this resource.
```

Tried to delete completely /opt/netdata, cloned repo again and got the same result on 2 servers.

##### OS / Environment

Ubuntu: 18.04
Ubuntu: 16.04

##### Netdata version
netdata v1.31.0-370-nightly

##### Installation method
From source code with netdata-installer.sh

##### Steps To Reproduce

git clone --recurse-submodules https://github.com/netdata/netdata.git --depth=10
cd netdata
./netdata-installer.sh --install /opt --enable-ebpf

##### Expected behavior
Default config file /opt/netdata/etc/netdata/netdata.conf is created

**Comment by MrZammler** [comment]
Yes, it seems that it is a permissions issue.

During installation netdata will try with curl or wget to download the netdata.conf from a running agent.

Does your local IP match one of those in `allow netdata.conf from` ?

**Comment by nitrogear** [comment]
@ilyam8 yes, that's right
no errors during installation. Installed once again the latest night build `netdata v1.31.0-381-nightly`
however, build v1.31.0-381-nightly doesn't try to download config from localhost:19999/netdata.conf at the end of installation, so now the main config wasn't touched
but issue is still present: I have `allow netdata.conf from = localhost` and can't get config with `curl -v localhost:19999/netdata.conf`

**Comment by ilyam8** [comment]
Hey, @nitrogear. Let's check what is happening

 - install this branch, it contains additional logging

```cmd
git clone https://github.com/ilyam8/netdata --branch log_acl_netdata_conf --depth 1 nd_log_acl_netdata_conf
cd nd_log_acl_netdata_conf
./netdata-installer.sh ...
```

- let's disable log flood protection

```cmd
[ilyam@pc netdata]$ grep flood netdata.conf
	errors flood protection period = 12000000
	# errors to trigger flood protection = 200
```

- and now we can `curl` and check the logs

```cmd
[ilyam@pc netdata]$ curl -s localhost:19999/netdata.conf > /dev/null
[ilyam@pc netdata]$ curl -s localhost:19999/netdata.conf > /dev/null
[ilyam@pc netdata]$ grep ACCESS error.log
2021-10-15 17:23:52: netdata INFO  : WEB_SERVER[static3] : ACCESS ALLOWED ip: 'localhost', host: ''
2021-10-15 17:23:53: netdata INFO  : WEB_SERVER[static6] : ACCESS ALLOWED ip: 'localhost', host: ''
```

**Comment by ilyam8** [comment]
Just to make it clear: **every time** you `curl localhost:19999/netdata.conf` you get 

> ACCESS DENIED ip: '195.201.XXX.XXX

in the error.log?
