### ISSUE TITLE
netdata failed to install on Mac 

### ISSUE THREAD

**Issue by VMLTV** [netdata/netdata#11679]
Hello,

Does anybody found some fixes for these?

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

**Comment by MrZammler** [comment]
Hi @VMLTV 

Are you trying on an Intel, or M1 mac ? Also the OS version please?

Support for building on Mac is currently in progress...

**Comment by VMLTV** [comment]
Hello @MrZammler Intel Catalina 10.15.7

**Comment by MrZammler** [comment]
Ok, thanks! Are you trying to build via the kickstart script (https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart) or by cloning the repo?

**Comment by VMLTV** [comment]
Via the kickstart
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --install /usr/local/


First error with Bash
bash --version echo $?
GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)


This script does not support running as EUID 0 on macOS. Please run it as a regular user.
 FAILED  

 WARNING  It failed to install all the required packages, but installation might still be possible.

**Comment by dillera** [comment]
Running into this issue. I can build and install netdata by hand, following the info here:

https://github.com/netdata/netdata/issues/6863
`
autoreconf -ivf
./configure --prefix=/usr/local/netdata/usr --sysconfdir=/usr/local/netdata/etc --localstatedir=/usr/local/netdata/var --with-zlib --with-math --with-user=netdata CFLAGS="-O2 -I$(brew --prefix)/opt/openssl/include" LDFLAGS="-L$(brew --prefix)/opt/openssl/lib"
CFLAGS="-O2 -I$(brew --prefix)/opt/openssl/include" LDFLAGS="-L$(brew --prefix)/opt/openssl/lib" make
`

So I have netdata installed in /usr/local/netdata.
I cannot get the kickstart command to not try and re-install everything (and fail).

If I have built and installed netdata how can manually:

1. Run the configure for it to create etc/netdata.conf
2. run the net-claim.sh by hand to register the node


the deamon just dies as no config:
`
dillera@trashcan /usr/local/netdata/usr/sbin $ ./netdata -d
2021-11-11 17:46:57: netdata INFO  : MAIN : CONFIG: cannot load user config '/usr/local/netdata/etc/netdata/netdata.conf'. Will try the stock version.
2021-11-11 17:46:57: netdata INFO  : MAIN : CONFIG: cannot load stock config '/usr/local/netdata/usr/lib/netdata/conf.d/netdata.conf'. Running with internal defaults.
2021-11-11 17:46:57: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/usr/local/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2021-11-11 17:46:57: netdata FATAL : MAIN : Cannot change directory to '/usr/local/netdata/var/cache/netdata' # : No such file or directory

2021-11-11 17:46:57: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2021-11-11 17:46:57: netdata INFO  : MAIN : EXIT: cleaning up the database...
2021-11-11 17:46:57: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
2021-11-11 17:46:57: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
`

Running CLAIM:
`
dillera@trashcan /usr/local/netdata/usr/sbin $ ./netdata-claim.sh 
Unable to communicate with Netdata daemon, querying config from disk instead.
Unable to communicate with Netdata daemon, querying config from disk instead.
Token: ****************
Base URL: https://app.netdata.cloud
Id: D45A4D12-E21C-4D48-A36A-84B7BAF507AC
Rooms: 
Hostname: trashcan
Proxy: 
Netdata user: dillera
No write permission in claiming working directory /usr/local/netdata/var/lib/netdata/cloud.d
`

**Comment by dillera** [comment]
> Via the kickstart bash <(curl -Ss https://my-netdata.io/kickstart.sh) --install /usr/local/
> 
> First error with Bash bash --version echo $? GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)
> 
> This script does not support running as EUID 0 on macOS. Please run it as a regular user. FAILED
> 
> WARNING It failed to install all the required packages, but installation might still be possible.

use brew to install all of those dependancies. It will still break however on openssl.

**Comment by MrZammler** [comment]
Hi @dillera, thanks for your input!

We are currently working on the best way to install on MacOS. At the moment it seems the best bet is to install on a local user directory if you want to try it out.

Thanks!

**Comment by dillera** [comment]
So @MrZammler - i can install by hand on my Mac.

How can I:

1. run the scripts that will discover all the devices and create the /etc/netdata.conf file?

Once I have that I can start the agent, once the agent starts I can run the net-claim.sh and attach the node to my account.

**Comment by stelfrag** [comment]
> This issue has been inactive for 30 days. It will be closed in one week, unless it is updated.

keep active

**Comment by MrZammler** [comment]
Hi @dillera. Really sorry we left this stale and un-answered. There have been some recent advancements for macos compilation and usage, and netdata is also in [homebrew](https://formulae.brew.sh/formula/netdata). Can we pick it up by using a newer version and see if you still have problems?

Thanks and again sorry for not communicating earlier.

**Comment by MrZammler** [comment]
Closing this, the situation on macos should be better by now. If anything still is wrong we should check in a fresh issue.

**Comment by elisboa** [comment]
> `brew install bash make autoconf automake pkg-config zlib libuv ossp-uuid `

Just passing by to report that this command enabled netdata compilation on a M1 Mac Mini. Thanks a lot!
