### ISSUE TITLE
Install scripts -> netdata repo

### ISSUE THREAD

**Issue by kachkaev** [netdata/netdata#1169]
I apologise if this questions has already been discussed, but I have not found it.

At the moment netdata's installation instructions rely on the contents of another github repo called [firehol/netdata-demo-site](https://github.com/firehol/netdata-demo-site):

```
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata
curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh netdata-all
```

This implies that if anyone wants to install or update netdata with the most convenient method, they have to check both [firehol/netdata](https://github.com/firehol/netdata) and [firehol/netdata-demo-site](https://github.com/firehol/netdata-demo-site) against being hacked to avoid poisoning their servers with malware. I know that the probability of this is tiny and that if any of the two repos is compromised, someone has obtained access to all firehol's repos. However, one _single point of failure_ is still better than two :–)

If all netdata resources were kept under one roof, it would become easier for the organisations to maintain their mirrored security-cleared copies of the tool and be more confident that they do not accidentally harm their infrastructure at some point.

What is the reason for keeping `install-required-packages.sh` in another repo? If this is solely to update them independently and thus avoid false notifications in the interface, could they be just maintained in a separate branch?

**Comment by ktsaou** [comment]
You are right.
I will move it to the netdata repo and probably integrate it into the installer somehow.

The netdata-demo-site is used to turn a linux into a netdata demo site (this how I maintain the demo sites), so this script was prepared for that purpose and finally made it into netdata.

**Comment by ktsaou** [comment]
We are working to provide our own packages for netdata.
So, I think we can close this.
