### ISSUE TITLE
Error 101: Cannot load jQuery: [...]/lib/jquery-2.2.4.min.js

### ISSUE THREAD

**Issue by MartMlr** [netdata/netdata#11742]
##### Bug report summary

The shipped jquery version in /usr/share/netdata/lib/ seem to have changed in the recent nightly build from 2.2.4 to 3.6.0, which causes localhost:19999/dashboard.html and all custom made dashboards to break. 

This only occures on freshly installed maschines with the most recent build. (v1.31.0-450-nightly)
Last install i made successfully without this issue was 1.31.0-370-nightly.

probably related to: https://github.com/netdata/netdata/pull/11710

##### OS / Environment

OS: Ubunutu 21.04

##### Netdata version

v1.31.0-450-nightly

**Comment by ilyam8** [comment]
@MartMlr thanks for reporting the issue. I tested #11710 and it fixes the problem.
