### ISSUE TITLE
How can I change my space name?

### ISSUE THREAD

**Issue by mkaand** [netdata/netdata#11757]
Hello,

I just joined and installed netdata on my server and I liked dashboard. But how can I change my space name? It looks like doesn't let me change it. Thanks in advance.

**Comment by manos-saratsis** [comment]
@mkaand Unfortunately you cannot right now. This is high prio on our to do list and should be there after a couple of weeks

**Comment by mkaand** [comment]
Thanks for information. I'll wait for updates.
