### ISSUE TITLE
Error relocating /usr/lib/libnspr4.so: gettid: symbol not found

### ISSUE THREAD

**Issue by srozinov** [netdata/netdata#11786]
Hello!

##### Bug report summary
Trying to set up UPS monitoring according to
https://learn.netdata.cloud/docs/agent/collectors/charts.d.plugin/nut

What I get in my netdata container:
bash-5.0# upsc
Error relocating /usr/lib/libnspr4.so: gettid: symbol not found

##### OS / Environment
Linux aquanas 5.4.128-1-pve #1 SMP PVE 5.4.128-2 (Wed, 18 Aug 2021 16:20:02 +0200) x86_64 Linux
/etc/alpine-release:3.12.8
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.12.8
/etc/os-release:PRETTY_NAME="Alpine Linux v3.12"
/etc/os-release:HOME_URL="https://alpinelinux.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.alpinelinux.org/"

##### Netdata version
Version: netdata v1.31.0-229-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' '--with-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    ACLK Next Generation:    YES
    ACLK Legacy:             YES
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
 
##### Installation method
Run with Docker

**Comment by ilyam8** [comment]
Hi, @srozinov. Thanks for reporting, but I think this is the same issue as #10903. It will be solved after[ switching to alpine 3.14](https://github.com/netdata/helper-images/pull/140#issuecomment-954758278).

Closing as duplicate.

**Comment by srozinov** [comment]
Thanks! Have read #10903. Does it mean I have to wait for the next version for Docker to make NUT work?

**Comment by ilyam8** [comment]
Yes, it will be fixed in the 'latest' image after v1.32.0 release (when https://github.com/netdata/helper-images/pull/140 is merged).
