### ISSUE TITLE
Ubuntu 14.04 & kickstart static 64: Agent is correctly claimed, no data is sent (libwebsockets err=20)

### ISSUE THREAD

**Issue by mx5gr** [netdata/netdata#11784]
##### Bug report summary
Netdata is correctly installed using the kickstart-static-64 script, agent is claimed correctly within Cloud but no data is displayed on the Cloud (node shows as unavailable".

##### OS / Environment

Ubuntu 14.04 LTS with OpenSSL 1.0.1f and 1.0.2g

Linux pc09nj2s 4.2.0-35-generic #40~14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=14.04
/etc/lsb-release:DISTRIB_CODENAME=trusty
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="14.04.4 LTS, Trusty Tahr"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 14.04.4 LTS"
/etc/os-release:VERSION_ID="14.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

##### Netdata version

Version: netdata v1.31.0
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--with-bundled-lws=externaldeps/libwebsockets' '--with-libJudy=externaldeps/libJudy' 'CFLAGS=-static -O3 -I/openssl-static/include' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES

##### Installation method

We are trying to install the latest Nedata 1.3.1 to an Ubuntu 14.04  LTS host. We tried to install it using the kickstart-static64 method (https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64) due to OpenSSL issues

##### Component Name

Agent is correctly claimed in the cloud, however ACLK does not connect, thus the server shows within the Cloud as "unavailable"

Errors within /opt/netdata/var/log/netdata/error.log:

netdata ERROR : ACLK_Main : Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=2)

However, curl -vs https://app.netdata.cloud & curl -I https://app.netdata.cloud connect with no errors!

**Comment by MrZammler** [comment]
Hi @mx5gr thanks for your report!

It seems there was a recent issue with ca-certificates, which may be the cause of your problem. Can you try to update the package on your install ?

Can you please also paste the output of `curl -vs https://app.netdata.cloud` ?

**Comment by Ferroin** [comment]
@MrZammler is correct, this is an issue with the CA trust store on the syste in question. Updating the `ca-certificates` package to the absolute latest version _should_ fix this (and even if you do not run updates for anything else, you absolutely _should_ keep that package up to date, not doing so is a potentially serious security issue).

**Comment by mx5gr** [comment]
Problem located....

I updated the ca certificates using the latest ones, however the update-ca-certificates command did not sign the /etc/ssl/certs/ directory when invoked.

I had to manually run:

`/usr/bin/c_rehash /etc/ssl/certs`

After this command, everything went back to normal!
