### ISSUE TITLE
Use latest libbpf to include a fix for a bug?

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#11796]
Initially reported in https://github.com/netdata/netdata-cloud/issues/191 by @vuong-bse :

I connect a new node by code rendered on cloud, and got error same is: https://github.com/libbpf/libbpf/issues/403
I found a solution by edit file in here.
https://github.com/libbpf/libbpf/commit/2ab26159262b61c7725c97a92beb46c5cfda068b

----

The libbpf repo has a fix for it merged in their latest version. Not sure if we can/should require it and when.

**Comment by thiagoftsm** [comment]
> The libbpf repo has a fix for it merged in their latest version. Not sure if we can/should require it and when.

We are already working with a more recent `libbpf` at [kernel-collector](https://github.com/netdata/kernel-collector),  so I preferred to bring it immediately, because I do not want a new release with any possible bug related to `eBPF` and `libbpf`.
