### ISSUE TITLE
Raspberry Pi : libssl-dev not installing

### ISSUE THREAD

**Issue by Mausy5043** [netdata/netdata#11813]
When installing on a Raspberry Pi using the method prescribed [here](https://learn.netdata.cloud/guides/monitor/pi-hole-raspberry-pi) causes an error:

```
Press ENTER to run it >
NOTE: Running apt-get update and updating your APT caches ...
apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13.0 MB]
Fetched 13.0 MB in 10s (1357 kB/s)
Reading package lists... Done
apt-get install autoconf autoconf-archive autogen automake cmake g++ gcc libelf-dev libjson-c-dev libjudy-dev liblz4-dev libmnl-dev libssl-dev libtool libuv1-dev make netcat pkg-config uuid-dev zlib1g-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.1 (= 1.1.1d-0+deb10u6+rpt1) but 1.1.1d-0+deb10u7 is to be installed
E: Unable to correct problems, you have held broken packages.
```

##### OS / Environment

Vanilla [`raspberrypi-ua-netinst`](https://github.com/FooDeas/raspberrypi-ua-netinst) install. 

```
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
If it matters:
```
CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
OF: fdt: Machine model: Raspberry Pi 3 Model B Rev 1.2
```

##### Installation method

`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

##### Component Name

```
The following packages have unmet dependencies:
 libssl-dev : Depends: libssl1.1 (= 1.1.1d-0+deb10u6+rpt1) but 1.1.1d-0+deb10u7 is to be installed
E: Unable to correct problems, you have held broken packages.
``` 

##### Steps To Reproduce

See above.

I fixed this by downgrading libssl1.1 with `sudo apt install libssl1.1=1.1.1d-0+deb10u6+rpt1` but it would be much more fun if the script did this on its own.

**Comment by Mausy5043** [comment]
BTW, after upgrading the system from `buster` to `bullseye` I was able to install the application without issues. I'd love it though if an upgrade would not be required.

P.S.: The forementioned website mentions an installtime of 2 minutes:

> After a two-minute installation and with zero configuration, you'll be able to see all of [blablabla].

But that is a gross underestimation of the kickstart installer. 😞

**Comment by ilyam8** [comment]
@Mausy5043 Netdata is getting more complex and compiling it takes more and more time. And it very much depends on the number of CPU cores (more - faster).

Install Netdata with [kickstart-static64.sh](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64) is very fast (a pre-compiled static binary) and it is going to be the default method soon (except OSes for which we have native packages).

**Comment by Jihakuz** [comment]
Just had a look about in the Debian repositories and I don't think is is an issue anymore (?)

`libdev-ssl` depends on `libssl1.1@1.1.1d-0+deb10u6+rpt1` but apt is trying to install `1.1.1d-0+deb10u7`.

The repo that the packages are being obtained from is [here](http://archive.raspberrypi.org/debian/dists/buster/main/binary-armhf/Packages).

In there you can see:

```
Package: libssl1.1
Source: openssl
Version: 1.1.1d-0+deb10u6+rpt1
```

which is the version that `libdev-ssl` depends on:

```
Package: libssl-dev
Source: openssl
Version: 1.1.1d-0+deb10u6+rpt1
...
Depends: libssl1.1 (= 1.1.1d-0+deb10u6+rpt1)
```

Don't have a Raspberry Pi on hand but the install script for Raspbian could be the issue.

Just me poking around, could be wrong on all of this :p

**Comment by Dim-P** [comment]
@Mausy5043 I just tried installing Netdata through a local build (`wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --build-only`) on a clean installation of `buster` and I didn't encounter any `libssl-dev` dependency issues. The following library version were installed:

```
pi@raspberrypi:~ $ sudo dpkg -l | grep libssl
ii  libssl-dev:armhf               1.1.1n-0+deb10u1                    armhf        Secure Sockets Layer toolkit - development files
ii  libssl1.1:armhf                1.1.1n-0+deb10u1                    armhf        Secure Sockets Layer toolkit - shared libraries
```

Unless this is still an issue for you, I will mark it as resolved and close it. 

BTW, an installation using a static build takes precedence over a local build now if one omits the `--build-only` option when using the `kickstart.sh` script (which is very fast as Ilya mentioned).

**Comment by Mausy5043** [comment]
Thanks.
