### ISSUE TITLE
Installation fails on Raspberry Pi 4 4GT and 8GT Raspberry Pi OS Bullseye

### ISSUE THREAD

**Issue by mikael-ri** [netdata/netdata#11812]
##### Bug report summary

When trying to install netdata on a Raspberry Pi 4 (tried both 4GT and 8GT models) the installation fails after a while with following error message:
```
/usr/bin/ld: ml/Host.o: in function `ml::TrainableHost::trainDimension(ml::DetectableDimension*, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > > const&)':
Host.cc:(.text+0x1e04): undefined reference to `__atomic_exchange_8'
/usr/bin/ld: ml/Host.o: in function `ml::DetectableHost::detectOnce()':
Host.cc:(.text+0x36a8): undefined reference to `__atomic_exchange_8'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:5233: netdata] Error 1
make[2]: Leaving directory '/tmp/netdata-kickstart-yWsPIBsSJO/netdata-v1.31.0-522-g2e471c4cd'
make[1]: *** [Makefile:6481: all-recursive] Error 1
make[1]: Leaving directory '/tmp/netdata-kickstart-yWsPIBsSJO/netdata-v1.31.0-522-g2e471c4cd'
make: *** [Makefile:3536: all] Error 2
 FAILED   

 FAILED  

 ABORTED  netdata-installer.sh exited with error 
```
installation command is as follows:
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-cloud --disable-telemetry --dont-wait
```

##### OS / Environment

```
$ uname -a; grep -Hv "^#" /etc/*release  # Linux

Linux hostname 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```

##### Netdata version

Latest version that the kickstart.sh tries to install.

##### Installation method
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-cloud --disable-telemetry --dont-wait
```
##### Steps To Reproduce

1. run the command `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-cloud --disable-telemetry --dont-wait` on a Raspberry Pi 4 Raspbian Bullseye

##### Expected behavior

Installation to go through normally and have netdata working.

**Comment by vkalintiris** [comment]
Thanks for reporting this @mikael-ri.

While we are investigating this issue, I think that this command might work for your setup:

`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-cloud --disable-ml --disable-telemetry --dont-wait`

**Comment by mikael-ri** [comment]
Thanks for the quick reply. I will try that out now.

**Comment by mikael-ri** [comment]
Hi @vkalintiris 

The script went through nicely, so your advice worked. Thanks a lot!!

**Comment by Mausy5043** [comment]
> --disable-cloud --disable-ml --disable-telemetry --dont-wait   

Is there somewhere where those switches are documented?

**Comment by vkalintiris** [comment]
@Mausy5043 the kickstart script propagates extra arguments to the [`netdata-installer.sh`](https://github.com/netdata/netdata/blob/454387fcf4d30b57f0f2264f9d4acce081808d7a/netdata-installer.sh#L198) script as part of the installation.

BTW, [packaging/installer/kickstart-ng.sh](https://github.com/netdata/netdata/blob/454387fcf4d30b57f0f2264f9d4acce081808d7a/packaging/installer/kickstart-ng.sh) will be released in a couple days and it will solve most of the installation problems users are facing, by installing proper debian/rpm packages or the static builds of Netdata.
