### ISSUE TITLE
netdata(V1.30.1) plugin  segfault  on openwrt(LEDE x86_32) with musl 1.2.2

### ISSUE THREAD

**Issue by WYC-2020** [netdata/netdata#11830]
[   56.036301] PLUGIN[diskspac[5977]: segfault at 4b0 ip b7f5aee6 sp b764c140 error 4 in libc.so[b7f58000+50000]
[   56.036553] Code: 00 8d 76 00 0f b6 08 39 d9 74 5a 83 c0 01 83 ea 01 a8 03 74 0f 85 d2 75 eb 31 c9 5b 89 c8 5e 5f c3 8d 76 00 31 c9 85 d2 74 f1 <0f> b6 08 39 d9 74 34 69 f3 01 01 01 01 83 fa 03 77 13 eb 27 8d b6

**Comment by vlvkobal** [comment]
You haven't provided any information about your environment. AFAIK LEDE project merged with OpenWRT back in 2018. What version do you use? Where is it installed?

**Comment by WYC-2020** [comment]
@vlvkobal  
Use [openwrt](https://github.com/openwrt/openwrt.git) official source code to compile x86 32-bit, install，select the netdata plugin，this problem occurs when musl is updated to 1.2.2, and 1.1.24 does not have this problem

**Comment by WYC-2020** [comment]
@vlvkobal Is diskspac not compatible with musl1.2.2 version？

**Comment by WYC-2020** [comment]
I have fixed it

**Comment by vlvkobal** [comment]
@WYC-2020 could you share your fix?

**Comment by WYC-2020** [comment]
@vlvkobal https://github.com/WYC-2020/packages/commit/2b4ee995466b33712b60ecfd98b06c01e5896a4d#diff-40cd970b2629010408d80405dffd30b266af9e3581ec1232a4874a5135fdfc83 
fix musl1.2.x time_t format error

**Comment by vlvkobal** [comment]
Cool 👍, Thank you!
