### ISSUE TITLE
Cannot install netdata from source

### ISSUE THREAD

**Issue by Nirjonadda** [netdata/netdata#11832]
Cannot install netdata from source (the source directory does not include netdata-installer.sh). I am using AlmaLinux v8

`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

![ScreenShot00428](https://user-images.githubusercontent.com/6899856/143770181-65bbf72a-01d6-47ea-80f6-5f30cf224f38.png)

**Comment by MrZammler** [comment]
Hi @Nirjonadda ! thanks for your report. Does the problem persist? Just tried the script and seems ok.

**Comment by Nirjonadda** [comment]
Yes !  Netdata is installed and running now!
