### ISSUE TITLE
Netdata daily update cron-job locks up the server during update

### ISSUE THREAD

**Issue by Apparyllis** [netdata/netdata#11864]
##### Bug report summary

We have noticed that the /etc/cron.daily/netdata-updater script is causing high CPU usage on a daily basis.

![image](https://user-images.githubusercontent.com/84717110/144745907-fcec8fef-a6fa-4695-ad24-f59bdb218132.png)

Only a subset of our servers suffer from this, seemingly our lower-grade servers. Is there anything that can be done to prevent downtime on a daily basis?

##### OS / Environment

Linux apparyllis-api-v2-2 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

##### Netdata version
Version: netdata v1.32.0-8-nightly
  
##### Installation method

kickstart.sh

##### Component Name

Daily update cron job

##### Steps To Reproduce

We have a variety of servers, and our lower-grade servers are affected by daily updates, while our larger-stronger servers do not suffer from this.

##### Expected behavior

Server remains functional during daily update.

**Comment by jdelStrother** [comment]
Anecdotal, but I've always found the updater to take massive amounts of memory & cpu via cc1plus, it's why I'm switching a bunch of servers over to the static builds. Not helpful, I know, but will follow this with interest...

**Comment by Ferroin** [comment]
See https://github.com/netdata/netdata/issues/11859#issuecomment-985492017

**Comment by Apparyllis** [comment]
> Anecdotal, but I've always found the updater to take massive amounts of memory & cpu via cc1plus, it's why I'm switching a bunch of servers over to the static builds. Not helpful, I know, but will follow this with interest...

Thank you for that suggestion. We've moved our lower-grade servers over to kickstart-static64.sh and this seems to have solved the downtime issue. We also just now noticed our higher-grade servers experience the same downtime, but because they're faster at building the non-static packages, the status page doesn't see it down long enough in order for it to report downtime on our status pages.

**Comment by ilyam8** [comment]
Closing in favour of #11859
