### ISSUE TITLE
SyntaxError in changefinder.chart.py

### ISSUE THREAD

**Issue by GiantCrocodile** [netdata/netdata#11874]
##### Bug report summary

No syntax error should be thrown.

##### OS / Environment

Fresh NetData install on a Debian 11 x64 system

##### Netdata version

```
Version: netdata v1.32.0-11-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' '--with-bundled-protobuf' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                YES
    TLS Host Verification:      YES
    Machine Learning:           YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

##### Installation method

automatic installer script

##### Steps To Reproduce

Just check /var/log/netdata/error.log after starting it

Log extract:

```
2021-12-07 10:52:45: python.d WARNING: plugin[main] : [changefinder] error on loading source : SyntaxError('invalid syntax', ('/usr/libexec/netdata/python.d/changefinder.chart.py', 183, 18, '        data = {**data_score, **data_flag}\n')), skipping it
```

Server runs Python 2.7.18 according to python -V

##### Expected behavior

No syntax error thrown.

**Comment by ilyam8** [comment]
Hi, @GiantCrocodile. That error is expected, changefinder works only with python3. See [Requirements](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/changefinder#requirements).
We have no plans to make it compatible with python2 (python2 is EOL since January 1, 2020).

**Comment by ilyam8** [comment]
> Server runs Python 2.7.18 according to python -V

If you have Python 3 installed, you need to tell Netdata to use it.  Pass the below command in the python plugin section of your netdata.conf file:

```
[plugin:python.d]
  # update every = 1  
  command options = -ppython3
```

**Comment by GiantCrocodile** [comment]
I see. I would have expected that the auto-installer does set it to python3 automatically if it's installed on the system or that it's set by default. Now the error is gone. Maybe this is a possible improvement @ilyam8?

**Comment by ilyam8** [comment]
python.d.plugin uses the default python version on your system

https://github.com/netdata/netdata/blob/81a3feae6f838e4ff415fa6e411c569e5db7b932/collectors/python.d.plugin/python.d.plugin.in#L3

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ grep -i pretty /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ ls -l $(which python)
lrwxrwxrwx 1 root root 9 Jan 24  2017 /usr/bin/python -> python2.7
```

**Comment by ilyam8** [comment]
Perhaps we can change the order to python3, python, python2. @Ferroin does it sound ok?

**Comment by GiantCrocodile** [comment]
@ilyam8 Maybe issue should be reopened so it's not overlooked.

**Comment by ilyam8** [comment]
@GiantCrocodile since that is an easy fix, I went forward and made a [PR](https://github.com/netdata/netdata/pull/12001).
