### ISSUE TITLE
NetFilter no NEW connections in monitoring

### ISSUE THREAD

**Issue by thyn** [netdata/netdata#11880]
##### Bug report summary

I have some servers with 150 k connection load max. I have conntrack enabled but I don't  see any information about New Connections. I have only invalid connections. Conntrack as I understood is working correctly. Table has about 70 k records. Services are working and everything looks good

##### OS / Environment

```
Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

netdata v1.32.0-16-nightly

##### Installation method

netdata.cloud snippet

##### Component Name

netfilter conntrack

##### Steps To Reproduce

Setup server debian 11

Linux de-ha-public-2 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

iptables rules
```
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m set --match-set SOMESET src -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -j REJECT --reject-with tcp-reset
-A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
-A INPUT -p icmp -j REJECT --reject-with icmp-port-unreachable
-A INPUT -j REJECT --reject-with icmp-port-unreachable
COMMIT

```

cat /proc/net/stat/nf_conntrack

```


entries  clashres found new invalid ignore delete delete_list insert insert_failed drop early_drop icmp_error  expect_new expect_create expect_delete search_restart
00007cc8  00000000 00000000 00000000 00000ee6 00000000 00000000 00000000 00000000 00000003 00000003 00000000 00000005  00000000 00000000 00000000 00000bad
00007cc8  00000000 00000000 00000000 00000f31 00000000 00000000 00000000 00000000 00000007 00000007 00000000 00000006  00000000 00000000 00000000 00000b6c
00007cc8  00000000 00000000 00000000 00000edd 00000000 00000000 00000000 00000000 00000006 00000006 00000000 00000012  00000000 00000000 00000000 00000c10
00007cc8  00000000 00000000 00000000 00000e88 00000000 00000000 00000000 00000000 00000003 00000003 00000000 0000000a  00000000 00000000 00000000 00000b80
00007cc8  00000000 00000000 00000000 00000e71 00000000 00000000 00000000 00000000 00000004 00000004 00000000 00000006  00000000 00000000 00000000 00000c16
00007cc8  00000000 00000000 00000000 00000e40 00000000 00000000 00000000 00000000 00000001 00000001 00000000 0000000d  00000000 00000000 00000000 00000c16
00007cc8  00000000 00000000 00000000 00000f0a 00000000 00000000 00000000 00000000 00000008 00000008 00000000 00000003  00000000 00000000 00000000 00000c36
00007cc8  00000000 00000000 00000000 00000e8e 00000000 00000000 00000000 00000000 00000001 00000001 00000000 00000016  00000000 00000000 00000000 00000b8c
00007cc8  00000000 00000000 00000000 00000d97 00000000 00000000 00000000 00000000 00000005 00000005 00000000 00000016  00000000 00000000 00000000 00000b37
00007cc8  00000000 00000000 00000000 00000dad 00000000 00000000 00000000 00000000 00000002 00000002 00000000 0000000f  00000000 00000000 00000000 00000aad
00007cc8  00000000 00000000 00000000 00000ca7 00000000 00000000 00000000 00000000 00000006 00000006 00000000 00000013  00000000 00000000 00000000 0000053c
00007cc8  00000000 00000000 00000000 00000bf4 00000000 00000000 00000000 00000000 00000006 00000006 00000000 00000002  00000000 00000000 00000000 00000533

```

conntrack -L

```
sample (one of 70k records)
 6 431989 ESTABLISHED src={ANY REMOTE IP} dst={ANY LOCAL IP} sport=41532 dport=443 src={LOCAL IP} dst={REMOTE IP} sport=443 dport=41532 [ASSURED] mark=0 use=1
```

conntrack -E, seems that everything is ok

```
    [NEW] tcp      6 120 SYN_SENT src=ip0 dst=ip1 sport=28830 dport=80 [UNREPLIED] src=ip1 dst=ip0 sport=80 dport=28830
 [UPDATE] tcp      6 60 SYN_RECV src=ip0 dst=ip1 sport=28830 dport=80 src=ip1 dst=ip0 sport=80 dport=28830
 [UPDATE] tcp      6 10 CLOSE src=ip0 dst=ip1 sport=28830 dport=80 src=ip1 dst=ip0 sport=80 dport=28830
```

##### Expected behavior

New connection should be shown

**Comment by thyn** [comment]
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/5173734/145336888-0f600818-d67a-4e29-9002-cf0e5aab1822.png">

**Comment by vlvkobal** [comment]
There are no new connections in your `/proc/net/stat/nf_conntrack`
```
 entries  clashres    found      new  invalid   ignore
00007cc8  00000000 00000000 00000000 00000ee6 00000000
00007cc8  00000000 00000000 00000000 00000f31 00000000
00007cc8  00000000 00000000 00000000 00000edd 00000000
00007cc8  00000000 00000000 00000000 00000e88 00000000
```
The `proc` plugin reads exactly this file to get data from the system.

**Comment by thyn** [comment]
You can see here 

```
    [NEW] tcp      6 120 SYN_SENT src=ip0 dst=ip1 sport=28830 dport=80 [UNREPLIED] src=ip1 dst=ip0 sport=80 dport=28830
 [UPDATE] tcp      6 60 SYN_RECV src=ip0 dst=ip1 sport=28830 dport=80 src=ip1 dst=ip0 sport=80 dport=28830
 [UPDATE] tcp      6 10 CLOSE src=ip0 dst=ip1 sport=28830 dport=80 src=ip1 dst=ip0 sport=80 dport=28830
```
 I have new connections. As I understood they are marked as invalid. But in conntrack -E everything is ok

Also I've changed the rules

```-A INPUT -p tcp -m tcp --dport 443 -m conntrack --ctstate NEW -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80  -m conntrack --ctstate NEW -j ACCEPT
```
and make curl. Everything was ok. In production I have about 500 requests per second. It's very strange thing.

**Comment by vlvkobal** [comment]
The only time the `conntrack` tool reads `/proc/net/stat/nf_conntrack` is with `-S expect` and it happens only if it [can't get information via `ctnetlink`](https://git.netfilter.org/conntrack-tools/tree/src/conntrack.c?h=conntrack-tools-1.4.6&id=089a538678aa12bbf1025e0cad035d1e7781ff68#n2992).

You might need to [configure `nf_conntrack`](https://www.kernel.org/doc/Documentation/networking/nf_conntrack-sysctl.txt).

**Comment by vlvkobal** [comment]
Have you tried the [`nfacct` plugin](https://learn.netdata.cloud/docs/agent/collectors/nfacct.plugin)?

**Comment by thyn** [comment]
> Have you tried the [`nfacct` plugin](https://learn.netdata.cloud/docs/agent/collectors/nfacct.plugin)?

yes, i've tried now

plugin log
```
nfacct.plugin: iteration 17, dt 998310 usec
nfacct.plugin: calling nfacct_collect()
nfacct.plugin: calling nfacct_send_metrics()
nfacct.plugin: calling nfstat_collect()
nfacct.plugin: calling nfstat_send_metrics()
BEGIN netfilter.netlink_new
SET new = 0
SET ignore = 0
SET invalid = 34647317
END
BEGIN netfilter.netlink_changes
SET insert = 0
SET delete = 0
SET delete_list = 0
END
BEGIN netfilter.netlink_search
SET searched = 0
SET search_restart = 45771500
SET found = 0
END
BEGIN netfilter.netlink_errors
SET icmp_error = 86040
SET insert_failed = 47646
SET drop = 47649
SET early_drop = 0
END
BEGIN netfilter.netlink_expect
SET found = 0
SET new = 0
SET searched = 0
END
nfacct.plugin: iteration 18, dt 1000447 usec
nfacct.plugin: calling nfacct_collect()
nfacct.plugin: calling nfacct_send_metrics()
nfacct.plugin: calling nfstat_collect()
nfacct.plugin: calling nfstat_send_metrics()
BEGIN netfilter.netlink_new
SET new = 0
SET ignore = 0
SET invalid = 34647599
END
BEGIN netfilter.netlink_changes
SET insert = 0
SET delete = 0
SET delete_list = 0
END
BEGIN netfilter.netlink_search
SET searched = 0
SET search_restart = 45771948
SET found = 0
END
BEGIN netfilter.netlink_errors
SET icmp_error = 86040
SET insert_failed = 47646
SET drop = 47649
SET early_drop = 0
END
BEGIN netfilter.netlink_expect
SET found = 0
SET new = 0
SET searched = 0
END
nfacct.plugin: iteration 19, dt 1000367 usec
nfacct.plugin: calling nfacct_collect()
nfacct.plugin: calling nfacct_send_metrics()
nfacct.plugin: calling nfstat_collect()
nfacct.plugin: calling nfstat_send_metrics()
BEGIN netfilter.netlink_new
SET new = 0
SET ignore = 0
SET invalid = 34647938
END
BEGIN netfilter.netlink_changes
SET insert = 0
SET delete = 0
SET delete_list = 0
END
BEGIN netfilter.netlink_search
SET searched = 0
SET search_restart = 45772440
SET found = 0
END
BEGIN netfilter.netlink_errors
SET icmp_error = 86042
SET insert_failed = 47647
SET drop = 47650
SET early_drop = 0
END
BEGIN netfilter.netlink_expect
SET found = 0
SET new = 0
SET searched = 0
END
nfacct.plugin: iteration 20, dt 1000415 usec
nfacct.plugin: calling nfacct_collect()
nfacct.plugin: calling nfacct_send_metrics()
nfacct.plugin: calling nfstat_collect()
nfacct.plugin: calling nfstat_send_metrics()
BEGIN netfilter.netlink_new
SET new = 0
SET ignore = 0
SET invalid = 34648267
END
BEGIN netfilter.netlink_changes
SET insert = 0
SET delete = 0
SET delete_list = 0
END
BEGIN netfilter.netlink_search
SET searched = 0
SET search_restart = 45772927
SET found = 0
END
BEGIN netfilter.netlink_errors
SET icmp_error = 86043
SET insert_failed = 47647
SET drop = 47650
SET early_drop = 0
END
BEGIN netfilter.netlink_expect
SET found = 0
SET new = 0
SET searched = 0
END
nfacct.plugin: iteration 21, dt 1000331 usec
nfacct.plugin: calling nfacct_collect()
nfacct.plugin: calling nfacct_send_metrics()
nfacct.plugin: calling nfstat_collect()
nfacct.plugin: calling nfstat_send_metrics()
BEGIN netfilter.netlink_new
SET new = 0
SET ignore = 0
SET invalid = 34648577
END
BEGIN netfilter.netlink_changes
SET insert = 0
SET delete = 0
SET delete_list = 0
END
BEGIN netfilter.netlink_search
SET searched = 0
SET search_restart = 45773391
SET found = 0
END
BEGIN netfilter.netlink_errors
SET icmp_error = 86043
SET insert_failed = 47649
SET drop = 47652
SET early_drop = 0
END
BEGIN netfilter.netlink_expect
SET found = 0
SET new = 0
SET searched = 0

```

**Comment by thyn** [comment]
> The only time the `conntrack` tool reads `/proc/net/stat/nf_conntrack` is with `-S expect` and it happens only if it [can't get information via `ctnetlink`](https://git.netfilter.org/conntrack-tools/tree/src/conntrack.c?h=conntrack-tools-1.4.6&id=089a538678aa12bbf1025e0cad035d1e7781ff68#n2992).
> 
> You might need to [configure `nf_conntrack`](https://www.kernel.org/doc/Documentation/networking/nf_conntrack-sysctl.txt).

I've took clean vm with debian 11

install netdata
add one rule 

```
-A INPUT -p tcp -m tcp --dport 80  -m conntrack --ctstate NEW -j ACCEPT
```
to activate nf__conntrack

install nginx, curl it

and the problem the same. All is invalid in metrics, 

conntrack -E 

shows NEW

**Comment by ilyam8** [comment]
I did a quick search and https://github.com/torvalds/linux/commit/8e8118f893138d4cc3d4dbf4163d7497fca54a9d could be the cause

**Comment by thyn** [comment]
I also that ticket but can't understand why everything is invalid

> I did a quick search and [torvalds/linux@8e8118f](https://github.com/torvalds/linux/commit/8e8118f893138d4cc3d4dbf4163d7497fca54a9d) could be the cause

**Comment by ilyam8** [comment]
I see there are 3 places in the code when `invalid` counter gets increased:

- [Not prepared to track yet or error occurred](https://github.com/torvalds/linux/blob/4de593fb965fc2bd11a0b767e0c65ff43540a6e4/net/netfilter/nf_conntrack_core.c#L1881-L1884).
- [Not valid part of a connection](https://github.com/torvalds/linux/blob/4de593fb965fc2bd11a0b767e0c65ff43540a6e4/net/netfilter/nf_conntrack_core.c#L1910-L1913).
- [Can't track with proto module](https://github.com/torvalds/linux/blob/4de593fb965fc2bd11a0b767e0c65ff43540a6e4/net/netfilter/nf_conntrack_core.c#L1918-L1931).

The chart title says:
> **Invalid** - packets are seen which can not be tracked.

For such packets, conntrack will neither create a new connection tracking entry nor associate it with an existing entry.

**Comment by ilyam8** [comment]
Yep, "new", "ignore" and "delete" are [hardcoded zeroes](https://github.com/torvalds/linux/blob/626bf91a292e2035af5b9d9cce35c5c138dfe06d/net/netfilter/nf_conntrack_standalone.c#L435-L449).

 - remove "ignore" [patch](https://github.com/torvalds/linux/commit/4afc41dfa5a716e9e7a90c22972583f337c0bcbf).
 - remove "new", "delete" [patch](https://github.com/torvalds/linux/commit/4afc41dfa5a716e9e7a90c22972583f337c0bcbf).

**Comment by thyn** [comment]
> Yep, "new", "ignore" and "delete" are [hardcoded zeroes](https://github.com/torvalds/linux/blob/626bf91a292e2035af5b9d9cce35c5c138dfe06d/net/netfilter/nf_conntrack_standalone.c#L435-L449).
> 
> * remove "ignore" [patch](https://github.com/torvalds/linux/commit/4afc41dfa5a716e9e7a90c22972583f337c0bcbf).
> * remove "new", "delete" [patch](https://github.com/torvalds/linux/commit/4afc41dfa5a716e9e7a90c22972583f337c0bcbf).

well, is there any way to monitor that?

**Comment by ilyam8** [comment]
I don't know of any (the kernel doesn't track them), according to the patch author those counters "does not seem too helpful nowadays".
