### ISSUE TITLE
Installation inconsistencies on Ubuntu 18.04.02/06

### ISSUE THREAD

**Issue by sashareds** [netdata/netdata#11892]
##### Bug report summary
For the last few weeks, I've been installing netdata over multiple servers. Everything was smooth. But the last few days, things weren't going smooth at all. 
The whole install is too short.
Uninstall script cannot uninstall netdata fully.
No directory created under /etc/

Here is an output from `bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`
https://pastebin.com/0h17aL5R

##### OS / Environment
```
root@hetz-nbg1-micro-01:~# uname -a; grep -Hv "^#" /etc/*release
Linux hetz-nbg1-micro-01 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.6 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.6 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
```
root@hetz-nbg1-micro-01:~# netdata -W buildinfo
-bash: netdata: command not found
```

##### Installation method

Tried Linux with one-line installer and Linux with pre-built static binary

##### Component Name

Installer

##### Steps To Reproduce

Regular running script `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`, no additional parameters

1. ...
2. ...

##### Expected behavior

Download packages
Unpack and build them
Add netdata in /etc/ and shell environment.

**Comment by ilyam8** [comment]
Hi, @sashareds. 

> The whole install is too short.

You are using ["kickstart-static64.sh"](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64), this method uses a pre-compiled static binary to install Netdata. It is much faster than ["kickstart.sh"](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart) (downloads the source code and compiles it), it is expected. I checked your output and it is completely fine.

> No directory created under /etc/

It is expected when using "kickstart-static64.sh". This script installs Netdata at `/opt/netdata`.

> Uninstall script cannot uninstall netdata fully.

Can you be more specific? What is not removed?

**Comment by ilyam8** [comment]
Closing the issue because I see no "Installation inconsistencies".
As for "Uninstall script cannot uninstall netdata fully" - if there is a problem we need a separate issue. We have open [Uninstaller script does not remove netdata-updater](https://github.com/netdata/netdata/issues/11911) issue, perhaps it is what you mean.

**Comment by Shahnavazi1985** [comment]
Re: [netdata/netdata] Installation inconsistencies on Ubuntu 18.04.02/06 (Issue #11892)

**Comment by sashareds** [comment]
@ilyam8 sorry, I was hoping for an open dialogue and someone would ask more questions before we get into the core issues

The 64 version was my second try to see if this solves the issues. But it didn't. And now I can't even deinstall it.

The none64 installer causes a lot of errors such as 

-    Could not find cmake, which is required to build libwebsockets. The install process will continue, but you may not be able to connect this node to Netdata Cloud.
-    Could not find cmake, which is required to build JSON-C. The install process will continue, but Netdata Cloud support will be disabled.
-    Failed to build libbpf. You may not be able to use eBPF plugin.

The exact same ubuntu build on another box a month or so ago had no such issues, hence I suspect something is dodgy with the installer.

After installing cmake and fixing library issues manually, cloud dashboard can't connect to the server
