### ISSUE TITLE
Missing documentation for checks.plugin

### ISSUE THREAD

**Issue by kickoke** [netdata/netdata#11907]
##### Bug report summary

Documentation for `checks.plugin` is missing:

https://github.com/netdata/netdata/blob/master/collectors/checks.plugin/README.md

What is the status of this plugin? Is it under development, already shipped, or deprecated? 

Can you add some details about this plugin so that David and I can write something about it? 

##### Component Name

`checks.plugin`

**Comment by vlvkobal** [comment]
It is an internal plugin for debugging. It shows some timings - when a call started, time difference for netdata and apps.plugin chart processing.

**Comment by kickoke** [comment]
@vlvkobal Thanks for the information. 
If it is a plugin that our end users don't use, we can remove this page from the docs completely? 
@DShreve2 what's your opinion? 

Nevertheless, we need to make sure that our development team knows what this plugin does and where they can find more information.

**Comment by DShreve2** [comment]
@kickoke I say we remove this from the TOC/sidebar if it exists there. I'll remove it from Swiftype now. That should be enough to make it undiscoverable and leave it in Github.
