### ISSUE TITLE
Update to v1.32.1 error

### ISSUE THREAD

**Issue by juliokele** [netdata/netdata#11906]
error after running "/etc/cron.daily/netdata-updater":
```
Wed 15 Dec 2021 09:55:38 AM CET : INFO:  Checking if a newer version of the updater script is available.
Wed 15 Dec 2021 09:55:39 AM CET : ERROR:  FAILED TO UPDATE NETDATA : Cannot download latest stable tag from https://github.com/netdata/netdata/releases/latest
```

error after running "bash <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstall --stable-channel":
```
[/tmp/netdata-kickstart-3foXxLMnm3]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-3foXxLMnm3/netdata-latest.tar.gz https://github.com/netdata/netdata/releases/download/1.32.1/netdata-1.32.1.tar.gz  OK

 ABORTED  Tarball checksum validation failed. Stopping Netdata Agent installation and leaving tarball in /tmp/netdata-kickstart-3foXxLMnm3.
Usually this is a result of an older copy of the file being cached somewhere upstream and can be resolved by retrying in an hour.
```

netdata source link in script and on github not the same (netdata-1.32.1.tar.gz vs. netdata-v1.32.1.tar.gz)!

netdata source link in script:
https://github.com/netdata/netdata/releases/download/1.32.1/netdata-1.32.1.tar.gz

netdata source link on github:
https://github.com/netdata/netdata/releases/download/1.32.1/netdata-v1.32.1.tar.gz

**Comment by mullnerz** [comment]
There is a duplicated and wrong tag created at https://github.com/netdata/netdata/tags 
1.32.1 vs. v1.32.1
so the update script fails to validate the latest tag at https://github.com/netdata/netdata/blob/ac0c8abbef175433c48421d4eeaf5fa61cb6b703/packaging/installer/netdata-updater.sh#L184

Just removing the bad tag would make the updates work again.
Please fix!

**Comment by maneamarius** [comment]
This fix should make kickstart.sh work with any tags, with 'v' in their names or not
We'll merge this in master soon and update the checksum file, then you can try again.
A fix for release publishing workflow will follow up.

https://github.com/netdata/netdata/commit/3e66e3fc3412b752502007337263e1af9337f084

**Comment by obourdon** [comment]
@maneamarius I do not think this fix is enough as I made a quite similar one (adding the v in front of $latest) but the next problem occurs in the next step: 

```
/opt/netdata/usr/libexec/netdata/netdata-updater.sh --not-running-from-cron
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
Wed Dec 15 12:11:16 UTC 2021 : ERROR:  FAILED TO UPDATE NETDATA : Cannot download latest stable tag from https://github.com/netdata/netdata/releases/latest
 FAILED

 ABORTED  Failed to update existing Netdata install
```

**Comment by maneamarius** [comment]
I will have a look at netdata-updater.sh, I think that will need a similar change..

**Comment by maneamarius** [comment]
https://github.com/netdata/netdata/pull/11908/files

**Comment by Ferroin** [comment]
Closing, as this should now be fixed. Please comment here if you still are seeing this issue.

**Comment by mullnerz** [comment]
The fix does not help with the failing automatic updates:

```
 # /etc/cron.daily/netdata-updater
Thu Dec 16 10:37:31 CET 2021 : INFO:  Checking if a newer version of the updater script is available.
Thu Dec 16 10:37:32 CET 2021 : ERROR:  FAILED TO UPDATE NETDATA : Cannot download latest stable tag from https://github.com/netdata/netdata/releases/latest
```

/opt/netdata/usr/libexec/netdata/netdata-updater.sh fails checking the latest release tag at the line:
https://github.com/netdata/netdata/blob/ac0c8abbef175433c48421d4eeaf5fa61cb6b703/packaging/installer/netdata-updater.sh#L184

**Comment by juliokele** [comment]
It worked for me (v1.32.0 to v1.32.1 over /etc/cron.daily/netdata-updater)

**Comment by spinitron** [comment]
Today I got four of these

```
Fri 17 Dec 2021 06:55:31 AM EST : INFO:  Checking if a newer version of the updater script is available.
Fri 17 Dec 2021 06:55:31 AM EST : ERROR:  FAILED TO UPDATE NETDATA : Cannot download latest stable tag from https://github.com/netdata/netdata/releases/latest
```

and one of these (on a hyper-v vm)

```
/tmp/netdata-updater-fYeV4CcNru/netdata-updater.sh: 324: kill: Illegal number: 1564 1549
```

I am using this to build and install netdata

```
curl https://my-netdata.io/kickstart.sh >/tmp/kickstart.sh
sh /tmp/kickstart.sh --dont-wait --dont-start-it --stable-channel
```

**Comment by Ferroin** [comment]
For those still seeing errors like this:

```
Fri 17 Dec 2021 06:55:31 AM EST : INFO:  Checking if a newer version of the updater script is available.
Fri 17 Dec 2021 06:55:31 AM EST : ERROR:  FAILED TO UPDATE NETDATA : Cannot download latest stable tag from https://github.com/netdata/netdata/releases/latest
```

Double check the version of Netdata you have installed with `netdata -V`. Chances are, the update worked and you’ll see `v1.32.1` as the version, and a quirk of how the updater script work smeans that the (broken) updater code from v1.32.1 is still running on your systems.  If this is the case _and_ the update happened before approximately 2021-12-17 12:00 UTC, these bogus errors should resolve themselves within the next 24 hours or so. Alternatively, you can set the timestamp on the updater script to an arbitrarily ancient date (for example, with `touch -t 1970-01-01T00:00:00`) and that will also silence the messages.

> For those who care, this bogus error is showing up because v1.32.1 still has the old updater code (we merged the fix after the release), which thus ends up installed when the update works correctly. However, the timestamp on the updater script after the update will be newer than when the fix got merged, so instead of pulling the latest code automatically from GitHub before trying to run the update, the updater will run with the old (broken) code. Some other fixes for the updater code were merged today, which will mean that anybody who has updated to v1.32.1 _already_ will stop seeing those errors starting tonight, as the most recent changes to the updater script here on GitHub are newer than the file.

---

For those seeing errors like: 

```
/tmp/netdata-updater-fYeV4CcNru/netdata-updater.sh: 324: kill: Illegal number: 1564 1549
```

These should go away starting tonight, as the fix for this particular error case has been merged, though just like the above mentioned bogus ‘latest stable tag’ errors they may recur if you update to v1.32.1 _after_ today.

**Comment by ilyam8** [comment]
I believe this has been fixed. If anyone still has this problem, let us know.
