### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by nnovikov** [netdata/netdata#11912]
##### Bug report summary

Netdata send second HTTP response '400 Bad Request'.

##### OS / Environment

Debian GNU/Linux 10 (buster)

TCP Stream from Wireshark:
```
GET /api/v1/alarms?active HTTP/1.1
X-Forwarded-Host: example.com
X-Forwarded-Server: example.com
X-Forwarded-For: 192.168.128.36
Connection: keep-alive
Host: srv123:10100
user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
accept: application/json, text/plain, */*
accept-language: en-US,ru;q=0.7,en;q=0.3
accept-encoding: gzip, deflate, br
cache-control: no-cache, no-store
pragma: no-cache
dnt: 1
referer: https://example.com/srv123/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
cookie: experimentation_subject_id=<...>

HTTP/1.1 200 OK
Connection: keep-alive
Server: Netdata Embedded HTTP Server v1.32.1
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Date: Thu, 16 Dec 2021 14:11:53 GMT
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Thu, 16 Dec 2021 14:11:54 GMT
Content-Encoding: gzip
Transfer-Encoding: chunked

<...>

HTTP/1.1 400 Bad Request
Connection: close
Server: Netdata Embedded HTTP Server v1.32.1
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Type: text/plain; charset=utf-8
Date: Thu, 16 Dec 2021 14:11:53 GMT
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Thu, 16 Dec 2021 14:11:54 GMT
Content-Length: 27
```

##### Netdata version

Version: netdata v1.32.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--with-bundled-lws' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                YES
    TLS Host Verification:      YES
    Machine Learning:           YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES

##### Installation method

Netdata installed from official deb package

**Comment by MrZammler** [comment]
Hi @nnovikov, thanks for your report. Will try to replicate the problem.

**Comment by MrZammler** [comment]
Hi @nnovikov 

Can you please elaborate more on your setup ? Is the GET request from a different machine on the network, or localhost? Are you using https?

Thanks!

**Comment by nnovikov** [comment]
I tried via a nginx proxy (http client to nginx with TLS, connection from nginx to netdata without TLS ) and a direct tcp connection from browser without TLS.
I didn't check the connection from the localhost

**Comment by ilyam8** [comment]
@nnovikov did you check without Nginx proxy? If there are no problems (likely), it is not Netdata that sends 400, but Nginx.

**Comment by nnovikov** [comment]
I can't view the request body in pcap dump. After receiving 200/OK http client closes the connection by sending FIN/ACK. At the same time, netdata sends headers with the code 400, but does not have time to send the response body, as it receives a FIN/ACK.
S --> C 200/OK
C --> S ACK
C --> S FIN/ACK
S --> C 400 Bad Request
S --> C FIN/ACK
C --> S RST

Have you been able to reproduce this problem?

**Comment by stelfrag** [comment]
@nnovikov are you still experiencing this  ? (as we haven't managed to figure out what is going on)

**Comment by nnovikov** [comment]
This does not happen again on the new version.
