### ISSUE TITLE
Installation fails with "Tarball checksum validation failed" due to geoblock

### ISSUE THREAD

**Issue by danmichaelo** [netdata/netdata#11939]
##### Bug report summary

I've been getting 

```
Thu 06 Jan 2022 06:29:22 AM UTC : ERROR:  FAILED TO UPDATE NETDATA : Tarball checksum validation failed. Stopping netdata upgrade and leaving tarball in /tmp/netdata-updater-b6V3QsjMYY
Usually this is a result of an older copy of the tarball or checksum file being cached somewhere upstream and can be resolved by retrying in an hour.
```

from my nightly netdata update cron jobs for a while. Because of the "Usually this is a result of…" notice, I postponed to investigate for a bit, but since it's been happening every day for two weeks or so, I finally decided to check, and this is what I found:

```
$ curl https://storage.googleapis.com/netdata-nightlies/sha256sums.txt
56e43d5710bf0990fcde8b553a8a58a74025b639b8aa2d7021a3f52b67213c76 *./latest-version.txt
ee10b02b8c8065aee9e90c56b042bfc623b317c0f05756108b4d8420d59a571e *./netdata-aarch64-latest.gz.run
ee10b02b8c8065aee9e90c56b042bfc623b317c0f05756108b4d8420d59a571e *./netdata-aarch64-v1.32.1-37-gfbf0ee3c5.gz.run
1725e751379dd7d9c653581ed99652dde85cc2964795fff50b2e125c9da2e4e1 *./netdata-armv7l-latest.gz.run
1725e751379dd7d9c653581ed99652dde85cc2964795fff50b2e125c9da2e4e1 *./netdata-armv7l-v1.32.1-37-gfbf0ee3c5.gz.run
e5598ded2974082fdecb0e9a916214d78672cd988c8db8ac98acf2c7ada04d3a *./netdata-latest.gz.run
cf907bf2155f9cc15da9a035f94c72192d60136d0200bcfbd5e87694808e34f3 *./netdata-latest.tar.gz
da6795669c2da652dbdf1573dde7839d2f0d597f028df5cd9151a3765e65baa8 *./netdata-ppc64le-latest.gz.run
da6795669c2da652dbdf1573dde7839d2f0d597f028df5cd9151a3765e65baa8 *./netdata-ppc64le-v1.32.1-37-gfbf0ee3c5.gz.run
e5598ded2974082fdecb0e9a916214d78672cd988c8db8ac98acf2c7ada04d3a *./netdata-v1.32.1-37-gfbf0ee3c5.gz.run
cf907bf2155f9cc15da9a035f94c72192d60136d0200bcfbd5e87694808e34f3 *./netdata-v1.32.1-37-gfbf0ee3c5.tar.gz
e5598ded2974082fdecb0e9a916214d78672cd988c8db8ac98acf2c7ada04d3a *./netdata-x86_64-latest.gz.run
e5598ded2974082fdecb0e9a916214d78672cd988c8db8ac98acf2c7ada04d3a *./netdata-x86_64-v1.32.1-37-gfbf0ee3c5.gz.run
```

```
curl -q -sSL https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>
```

##### OS / Environment

This happens on multiple servers. All run Debian buster and are located in Linode's data center in **Frankfurt, Germany**.

**Comment by Ferroin** [comment]
Most likely culprit is https://github.com/netdata/netdata/commit/52f743c5a7cdd3b56c36ac4c054bf182c5e193b1, investigating further.

**Comment by Ferroin** [comment]
Correction, missed the error code, infrastructure issue in this case, still looking into it though.

**Comment by Ferroin** [comment]
OK, looking further into this, I can’t replicate the issue myself (tested using both a Digital Ocean droplet and a Vultr VM, both in their respective datacenters in Frankfurt), which means it’s probably either something specific to Linode, or to your particular setup.

Can you please share the full output of `curl -v -sSL https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz`? I suspect something is up between your system and the GCS servers, and the request and response headers should (hopefully) shed some more light on what’s going on here.

**Comment by danmichaelo** [comment]
Sorry for the slow reply! Weirdly enough, the issue went away the same day I reported it! January 6th was the last time I got the error. I'll re-open the issue if it happens again. Thanks a lot for trying to reproduce it ❤️
