### ISSUE TITLE
[BUG] Cannot Update netdata Agent with One-Liner - Checksum error

### ISSUE THREAD

**Issue by Compr0mzd** [netdata/netdata#11936]
##### Bug report summary

Cannot update to the last version with the one-liner command

##### OS / Environment
```Linux *redacted* 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```
##### Netdata version
```Version: netdata v1.32.0-32-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' '--with-bundled-protobuf' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                YES
    TLS Host Verification:      YES
    Machine Learning:           YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

##### Installation method

I have the .environnement file with the IS_NETDATA_STATIC_BINARY="no"

##### Component Name

Update one-liner script not working 

##### Steps To Reproduce

1.```bash <(curl -Ss https://my-netdata.io/kickstart.sh) ```
2. 
Found` existing install of Netdata under: / 
 --- Attempting to update existing install instead of creating a new one ---
[/etc/netdata]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron Mon 03 Jan 2022 11:24:54 AM CET : INFO:  Checking if a newer version of the updater script is available.
Mon 03 Jan 2022 11:24:54 AM CET : INFO:  Downloading newest version of updater script.
Mon 03 Jan 2022 11:24:54 AM CET : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Mon 03 Jan 2022 11:24:55 AM CET : INFO:  Current Version: 00103200000032
Mon 03 Jan 2022 11:24:55 AM CET : INFO:  Latest Version: 00103200100032
Mon 03 Jan 2022 11:24:55 AM CET : INFO:  Update available
./netdata-latest.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Mon 03 Jan 2022 11:24:55 AM CET : ERROR:  FAILED TO UPDATE NETDATA : Tarball checksum validation failed. Stopping netdata upgrade and leaving tarball in /tmp/netdata-updater-vslu7w3oc4
Usually this is a result of an older copy of the tarball or checksum file being cached somewhere upstream and can be resolved by retrying in an hour.
 FAILED

 ABORTED  Failed to update existing Netdata install```
 I tried to delete the tarball and clean my tmp folder without any success
##### Expected behavior

Update of Netdata client.

**Comment by Ferroin** [comment]
Possibly related to #11939

**Comment by Compr0mzd** [comment]
> Possibly related to #11939 

Thanks for that i am in the exact same setup as him ! Gonna check for the resolution now. Appreciate it

**Comment by ilyam8** [comment]
Hi, @Compr0mzd. Are you still having this issue?

**Comment by Compr0mzd** [comment]
> Hi, @Compr0mzd. Are you still having this issue?

Hi ! I fixed it by installing the update of netdata with apt.
