### ISSUE TITLE
Adding support for time markers

### ISSUE THREAD

**Issue by MartijnBraam** [netdata/netdata#1195]
I've switched my servers to netdata for monitoring. Before I had a self-written central monitoring system. Everything runs great with netdata but I'm missing one feature from my old system.

On my old system I have a command called `monitoring-marker` that can be called by scripts or admins to add time markers to all monitoring charts. For example `monitoring-marker Starting backup`. The result would be something like:

![mockup](https://cloud.githubusercontent.com/assets/6928199/19889278/5e84a6e6-a034-11e6-802a-3231f487bd9c.png)

**Comment by thinrope** [comment]
Yep, very useful, a simple case of the requested in issue #1114. Having time periods (begin/end, start/stop) as well as points (HDD crashed, database hacked) is very useful.

**Comment by ktsaou** [comment]
Nice. I like this.
It is related to #312

**Comment by ktsaou** [comment]
@gmosx 	I think this is nice.

**Comment by ktsaou** [comment]
oh! I think this is already implemented.

![peek 2018-11-23 15-12](https://user-images.githubusercontent.com/2662304/48945229-3f0cb200-ef32-11e8-841e-b36f61011fee.gif)

Just press ALT + select an area on any chart.
