### ISSUE TITLE
[Bug]: megacli plugin won't start `UnicodeDecodeError`

### ISSUE THREAD

**Issue by tazard** [netdata/netdata#11977]
### Bug description

megacli plugin won't start and gives this error in `/var/log/netdata/error.log`:

```
2022-01-14 22:22:50: python.d WARNING: plugin[main] : megacli[megacli] : unhandled exception on check : UnicodeDecodeError('utf-8', b'  Firmware Version   : \xfa\x19\n', 23, 24, 'invalid start byte'), skipping the job
```

Disabling battery stats resolves the issue.  With `do_battery: no` netdata loads the megacli plugin successfully.

It looks like the firmware version is given as some binary data by my H700 RAID controller for whatever reason. Perhaps adding `errors=ignore` to the unicode decode would sidestep the issue? https://stackoverflow.com/a/27454001

### Expected behavior

megacli starts

### Steps to reproduce

1. Follow https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/megacli/
2. Add megacli to sudoers
3. Reset CapabilityBoundingSet
4. Enable the collector
5. Enable battery stats
6. Restart netdata

### Installation method

kickstart.sh

### System info

```shell
Linux pve 5.13.19-2-pve #1 SMP PVE 5.13.19-4 (Mon, 29 Nov 2021 12:10:09 +0100) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian

Dell R710 with H700i RAID card that works with megacli
```

### Netdata build info

```shell
Version: netdata v1.32.1-50-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by tazard** [comment]
Log from running the battery command manually `megacli -AdpBbuCmd -a0`:

[2022-01-14 megacli battery.txt](https://github.com/netdata/netdata/files/7871135/2022-01-14.megacli.battery.txt)

**Comment by ilyam8** [comment]
Hi, @tazard. Thanks for reporting the issue. I tend to agree that we can just ignore such errors when reading a response. 

Can you test #11979?

**Comment by ilyam8** [comment]
The process is to get 2 approving reviews. We will merge it on Monday.
