### ISSUE TITLE
可以为centos6编译netdata-1.32.1-1.el6.x86_64.rpm？

### ISSUE THREAD

**Issue by 1265578519** [netdata/netdata#11981]
### Bug description

可以为centos6编译netdata-1.32.1-1.el6.x86_64.rpm？

在packagecloud.io库中只有netdata-1.19.0-1.el6.x86_64.rpm ，我有联系对方，对方说明了情况
```
Packagecloud 仅托管 netdata 包，我们不拥有或管理它们。 可以直接联系netdata吗？
```
![1](https://user-images.githubusercontent.com/6442439/149756997-30dffbc6-6734-48a2-8c08-ae676a27641f.png)
![2](https://user-images.githubusercontent.com/6442439/149757006-6d50ffba-80e9-43f8-9c3e-dee9eecf02de.png)

1.19.0中找不到1.32.1那种历史记录查看的选项，希望能安排下支持一个rpm

### Expected behavior

可以为centos6编译netdata-1.32.1-1.el6.x86_64.rpm？

### Steps to reproduce

1.centos 6.10 x64
2.
3.
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
centos 6.10 x64
```

### Netdata build info

```shell
可以为centos6编译netdata-1.32.1-1.el6.x86_64.rpm？
```

**Comment by 1265578519** [comment]
我觉得此处发视乎不太合适？应该在社区中发？https://community.netdata.cloud/

**Comment by MrZammler** [comment]
Hi @1265578519 

It's not clear from your message what the problem is, is it possible to continue it in English?

Thanks!

**Comment by 1265578519** [comment]
> 嗨@1265578519
> 
> 从您的留言中不清楚是什么问题，可以用英文继续吗？
> 
> 谢谢！

chrome fanyi

You can compile netdata-1.32.1-1.0 for CentOS 6 el6. x86_ 64.rpm？
In packagecloud There is only netdata-1.19.0-1.0 in the IO library el6. x86_ 64. Rpm, I contacted the other party and the other party explained the situation
Packagecloud only hosts netdata packages. We do not own or manage them. Can I contact netdata directly?
The option to view the history of 1.32.1 cannot be found in 1.19.0. I hope it can be arranged to support another rpm

**Comment by Ferroin** [comment]
CentOS 6 went end-of-life upstream as of 2020-11-30 (note that this means that you are missing more than a year’s worth of security fixes), and as such we will not be publishing any new packages for it. Even prior to that though, we had to drop support for CentOS 6 for technical reasons (continuing support would have required us to build most of our dependencies ourselves instead of using system-provided versions), which is why the last packages are so old.

Our [static builds](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64) stil work there, and that is the recommended approach if you absolutely need to run Netdata on CentOS 6.

**Comment by 1265578519** [comment]
> CentOS 6 已于 2020 年 11 月 30 日在上游结束生命周期（请注意，这意味着您错过了一年多的安全修复），因此我们不会为它发布任何新软件包。即便在此之前，出于技术原因，我们不得不放弃对 CentOS 6 的支持（继续支持将需要我们自己构建大部分依赖项，而不是使用系统提供的版本），这就是最后一个软件包如此陈旧的原因。
> 
> 我们的[静态构建](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64)仍然在那里工作，如果您绝对需要在 CentOS 6 上运行 Netdata，这是推荐的方法。

![QQ图片20220118211840](https://user-images.githubusercontent.com/6442439/149944747-18d18aa9-6f17-4d04-baa7-0ca5e786b4c3.png)

centos 6下1.19.0实测可替换最新的1.32.1 web模板，直接刷新浏览器缓存生效
fanyi
The 1.19.0 measurement under CentOS 6 can replace the latest 1.32.1 web template and directly refresh the browser cache to take effect


现在已经完美解决了我的问题，它可以选择历史进行查看了
我将会继续使用1.19.0版本，因为我需要centos 6的2.6内核
fanyi
Now that my problem has been perfectly solved, it can select history to view
I will continue to use version 1.19.0 because I need the 2.6 kernel of CentOS 6

[web.tar.zip](https://github.com/netdata/netdata/files/7889287/web.tar.zip)

**Comment by ilyam8** [comment]
Closing since this issue is not a bug.

- CentOS 6 is EOL, we will not be publishing any new packages for it.
- Get the latest Netdata on Centos6 - we suggest using static builds.

**Comment by 1265578519** [comment]
> 关闭，因为此问题不是错误。
> 
> * CentOS 6 已停产，我们不会为它发布任何新的软件包。
> * 在 Centos6 上获取最新的 Netdata - 我们建议使用静态构建。

它停止在了2019-11-27的v1190，它有希望能升级到v1260-2020-10-14？
根据你说的，centos 6在2020 年 11 月 30 日停止，它应当获得的最终版本是v1260？
fanyi
He stopped at v1190 on November 27, 2019. Is there any hope that he can upgrade to v1260-2020-10-14? 
According to what you said, CentOS 6 will stop on November 30, 2020. The final version it should get is v1260?

**Comment by 1265578519** [comment]
packagecloud居然把安装包删了，，，wget下载访问出404了，这里留个备份


centos 6
[netdata-1.19.0-1.el6.x86_64.zip](https://github.com/user-attachments/files/17350379/netdata-1.19.0-1.el6.x86_64.zip)
centos 7
[netdata-1.32.1-1.el7.x86_64.zip](https://github.com/user-attachments/files/17350384/netdata-1.32.1-1.el7.x86_64.zip)
