### ISSUE TITLE
[Bug]: Mellanox Infiniband counter port_rcv_data and port_xmit_data handled incorrectly as bytes within sys_class_infiniband.c

### ISSUE THREAD

**Issue by stephane-maillan** [netdata/netdata#11991]
### Bug description

Hi

There is an issue in the infiniband statistics reporting sys_class_infiniband.c for the Mellanox/Nvidia network card
    GEN(port_rcv_data,                   bytes,   "Received",                      1, __VA_ARGS__)  \
    GEN(port_xmit_data,                  bytes,   "Sent",                         -1, __VA_ARGS__)

port_rcv_data and port_xmit_data are handles as bytes while these counters as per the documentation represent double word of 32 bits

https://community.mellanox.com/s/article/understanding-mlx5-linux-counters-and-status-parameters

Those the netdata reported value is 4 time lower of the real value 

We validated the issue with correct measurement with tool such as ib_send_bw 

### Expected behavior

For this 2 counters the netdata reported value must be multiply by 4 if handled like bytes or reported as 32 bits unit instead 

### Steps to reproduce

1. generate traffic with ib_send_bw and compare statistic reported by ib_send_bw and netdata infiniband cntbytes

### Installation method

from source

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
netdata -W buildinfo
Version: netdata v1.32.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--with-bundled-lws' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                YES
    TLS Host Verification:      YES
    Machine Learning:           YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by ilyam8** [comment]
@Saruspete, hi. Can you help us (again) with this issue?

**Comment by Saruspete** [comment]
Hello,

Thanks for reporting it. Indeed, it seems I missed the multiplicator. Let me check if it's the same case with the Omnipath hardware I got, as these counters are fetched from the firmware. If so, the fix will be very simple.

**Comment by Saruspete** [comment]
The cluster I'm usually using being down, having no IB card on hand and the stats being managed by mellanox I'll just rely on your tests and the doc.

Can you please test this branch:
https://github.com/saruspete/netdata/tree/fix_ib_counters 

The commit is just changing a 1 to a 4:  https://github.com/Saruspete/netdata/commit/5fc30ee84931efc569bda87925d3026e01d6d887

**Comment by ilyam8** [comment]
> Those the netdata reported value is 4 time lower of the real value
> We validated the issue with correct measurement with tool such as ib_send_bw


> The commit is just changing a 1 to a 4

This definitely looks like a fix. I think you can make a PR @Saruspete. Big thanks!

**Comment by Saruspete** [comment]
Well, changing a value I though would be only 1/-1, which is multiplied later but it's not a clean way to do that.
At least, the divider is consistant on the [kernel docuementation](https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-infiniband) too: it's because IB uses 4 Lanes. 

Thus, I expect [all vendors](https://github.com/torvalds/linux/tree/master/drivers/infiniband/hw) to respect this format.
```
		port_xmit_data: (RO) Total number of data octets, divided by 4
		(lanes), transmitted on all VLs. This is 64 bit counter

		port_rcv_data: (RO) Total number of data octets, divided by 4
		(lanes), received on all VLs. This is 64 bit counter.
```
