### ISSUE TITLE
[Bug]: Unable to install latest version in static mode

### ISSUE THREAD

**Issue by obourdon** [netdata/netdata#12002]
### Bug description

Tried on several distributions namingly Flatcar and Debian latest where it used to work like a charm:

```
DEST=/opt/bin
/usr/bin/sudo /usr/bin/mkdir -p ${DEST}
/usr/bin/sudo /usr/bin/wget --no-verbose https://my-netdata.io/kickstart-static64.sh -O ${DEST}/kickstart-static64.sh
/usr/bin/sudo /usr/bin/bash ${DEST}/kickstart-static64.sh --non-interactive --stable-channel --dont-start-it >/dev/null
```

Error is: 

```
ABORTED  Static binary checksum validation failed. Usually this is a result of an older copy of the file being cached somewhere upstream and can be resolved by retrying in an hour.
```

### Expected behavior

Install as it used to do before

### Steps to reproduce

See above

### Installation method

kickstart-static64.sh

### System info

```shell
Linux flatcar-nomad 5.10.80-flatcar #1 SMP Fri Nov 19 19:28:59 -00 2021 x86_64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz GenuineIntel GNU/Linux
/etc/lsb-release:DISTRIB_ID="Flatcar Container Linux by Kinvolk"
/etc/lsb-release:DISTRIB_RELEASE=2983.2.1
/etc/lsb-release:DISTRIB_CODENAME="Oklo"
/etc/lsb-release:DISTRIB_DESCRIPTION="Flatcar Container Linux by Kinvolk 2983.2.1 (Oklo)"
/etc/os-release:NAME="Flatcar Container Linux by Kinvolk"
/etc/os-release:ID=flatcar
/etc/os-release:ID_LIKE=coreos
/etc/os-release:VERSION=2983.2.1
/etc/os-release:VERSION_ID=2983.2.1
/etc/os-release:BUILD_ID=2021-11-19-2019
/etc/os-release:PRETTY_NAME="Flatcar Container Linux by Kinvolk 2983.2.1 (Oklo)"
/etc/os-release:ANSI_COLOR="38;5;75"
/etc/os-release:FLATCAR_BOARD="amd64-usr"
```

```
Linux ca7e2fe230ed 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```
```


### Netdata build info

```shell
latest
```

### Additional info

debuting the installation script showed that

`NETDATA_STATIC_ARCHIVE_URL=https://github.com/netdata/netdata/releases/download/1.32.1/netdata-x86_64-1.32.1.gz.run`

but this file does not exist, there is a missing v in front of the version

`https://github.com/netdata/netdata/releases/download/1.32.1/netdata-x86_64-v1.32.1.gz.run
`
just works

**Comment by ilyam8** [comment]
Hi, @obourdon. Thanks for reporting the issue and for debugging it. Indeed, you are right, the problem is:
 - the latest is tag is **without** "v" prefix (1.32.1).
 - the attachment file name is **with** "v" prefix (netdata-x86_64-v1.32.1.gz.run).

I see we have both "v" and "latest" attachments, I think they are the same (netdata-x86_64-v1.32.1.gz.run == netdata-x86_64-latest.gz.run).

The fix could be just changing

https://github.com/netdata/netdata/blob/37082fcbc150619b54b2a64c3621afc617607adc/packaging/installer/kickstart.sh#L997

to 

```bash
 export NETDATA_STATIC_ARCHIVE_URL="https://github.com/netdata/netdata/releases/download/${latest}/netdata-${SYSARCH}-latest.gz.run" 

```

**Comment by obourdon** [comment]
@ilyam8 many thanks for digging into this so quickly, on my side I did a similar temporary fix in the kickstart file (using inline sed) just by adding the missing v and it works also exactly as the one you suggested
