### ISSUE TITLE
[Bug]: Config gets written to disk every minute even when no changes happen

### ISSUE THREAD

**Issue by rchukka** [netdata/netdata#12029]
### Bug description

config.v2.json and hostconfig.json gets written to disk every minute even if there is no change on host system, and show up in netdata charts as docker writes. sysdig reports ~34KB written every minute to disk which matches with file sizes.
<img width="638" alt="netdata_auto_writes" src="https://user-images.githubusercontent.com/1387753/150656358-e209538e-7886-4ede-b79f-2994d4d30fd4.png">
<img width="905" alt="netdata_chart" src="https://user-images.githubusercontent.com/1387753/150656394-fd97f897-b318-477a-a8d6-7366f354f14b.png">

### Expected behavior

Config files shouldn't be written to disk if there was no system or application changes happen. The only changes between writes seem to be timestamps in the JSON related to health check.

`Log":[{"Start":"2022-01-22T15:42:07.005011231-06:00","End":"2022-01-22T15:42:07.109609939-06:00",`

### Steps to reproduce

1. Start netdata docker container with steps provided in official installation.
2. Only changes to netdata.conf were `	update every = 3
	memory mode = dbengine
	page cache size = 32
	dbengine disk space = 128
	access log = none`
3. Monitor systemdd services disk writes in netdata and/or use sysdig to detect writes or check the timestamps for config.v2.json and hostconfig.json files in /var/lib/docker/containers/**netdata*container*id**
...

### Installation method

docker

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.3 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.3 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.32.1-117-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=' 'LDFLAGS='
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

I was debugging disk writes by other application using netdata and came across this issue. If this is expected behavior please let me know if there is anyway to avoid these writes.

**Comment by ilyam8** [comment]
Hi, @rchukka. That is not a bug it is due to [health checks](https://learn.netdata.cloud/docs/agent/packaging/docker#health-checks) being enabled. You can disable health checks using the `--no-healthcheck=true` option.

**Comment by rchukka** [comment]
@ilyam8 Wouldn't you agree that writing whole 32KB file when there are no alerts or system changes just to update timestamp is bit excessive?, this seems to run against core feature of netdata which optimizes metrics storage and flush to db?

**Comment by ilyam8** [comment]
@rchukka ah, you are under impression that those files have something to do with Netdata and Netdata writes them - that is not the case, those are Docker's files.
