### ISSUE TITLE
[Bug]: unable to install using one-line installer in ARMv6l

### ISSUE THREAD

**Issue by c0bra-dev** [netdata/netdata#12032]
### Bug description

I am unable to install netdata using the one-line installer on ARMv6l.
The one line installer tries to download an unexisting file (netdata-armv6l-latest.gz.run)

This is my hardware
model name      : ARMv6-compatible processor rev 7 (v6l)
Hardware        : BCM2835
Model           : Raspberry Pi Model B Plus Rev 1.2

### Expected behavior

I installed Netdata multiple time in the past using  the one line installer. I would expect the installer not to fail.

### Steps to reproduce

1.  SSH to any ARMv6l system (example Raspberry pi B)
2.  Run one line installer with or without stable channel flag: bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel
3.  Installation fails

### Installation method

kickstart.sh

### System info

```shell
Linux hostname 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021 armv6l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=raspbian
```

### Netdata build info

```shell
Netdata build does not even start
```

### Additional info

Shell output:

```shell
[/tmp/netdata-kickstart-KAZWCXd8DT]$ sh -c curl\ https://github.com/netdata/netdata/releases/latest\ -s\ -L\ -I\ -o\ /dev/null\ -w\ \'%\{url_effective\}\'\ \|\ grep\ -o\ \'\[\^/\]\*\$\'
 OK

 --- Downloading static netdata binary: https://github.com/netdata/netdata/releases/download/1.32.1/netdata-armv6l-latest.gz.run ---
[/tmp/netdata-kickstart-KAZWCXd8DT]$ curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-KAZWCXd8DT/netdata-armv6l-latest.gz.run https://github.com/netdata/netdata/releases/download/1.32.1/netdata-armv6l-latest.gz.run
 OK

[/tmp/netdata-kickstart-KAZWCXd8DT]$ curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-KAZWCXd8DT/sha256sum.txt https://github.com/netdata/netdata/releases/download/1.32.1/sha256sums.txt
 OK

 ABORTED  Static binary checksum validation failed. Usually this is a result of an older copy of the file being cached somewhere upstream and can be resolved by retrying in an hour.
```
Thank you for the attention

**Comment by Ferroin** [comment]
This appears to be an issue in our handling of the GitHub API when trying to fetch a static build for the local system (this _should_ be falling back to a local build, because we don’t (currently) publish static builds for ARMv6).

I suspect this is another case of GitHub returning a 200 status code and a JSON or XML payload with error information instead of properly returning a 404 status like they should be...

**Comment by Ferroin** [comment]
@c0bra-dev In the short term, you should be able to work around this by adding `--build-only` to the flags you’re passing to the installer. Long-term that should not be needed (we should default to behaving as if it was specified, at least until we eventually start publishing ARMv6 static builds), but it will get things working in this case.

**Comment by c0bra-dev** [comment]
@Ferroin Thank you very much for the quick answer. The workaround is indeed working for me.
I am amazed by the dedication of the netdata team. Thank you everyone for making this tool what it is.

**Comment by ilyam8** [comment]
We use either `curl` or `wget` to download a file. I checked both and only `curl` has the _problem_ with the non-zero exit code on 404 response.

- `wget` (exit code 8)

```cmd
# wget -T 15 -O netdata.gz.run https://github.com/netdata/netdata/releases/download/1.32.1/netdata-armv6l-latest.gz.run
--2022-01-24 23:18:15--  https://github.com/netdata/netdata/releases/download/1.32.1/netdata-armv6l-latest.gz.run
SSL_INIT
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-01-24 23:18:15 ERROR 404: Not Found.

# echo $?
8
```

- `curl` (exit code 0)

```cmd
# curl -q -sSL --connect-timeout 10 --retry 3 --output netdata.gz.run https://github.com/netdata/netdata/releases/download/1.32.1/netdata-armv6l-latest.gz.run
# echo $?
0
```

it appears there is `--fail` parameter

<details>
<summary>--fail description</summary>

>        -f, --fail
>              (HTTP) Fail silently (no output at all) on server errors.
>              This is mostly done to enable scripts etc to better deal
>              with failed attempts. In normal cases when an HTTP server
>             fails to deliver a document, it returns an HTML document
>              stating so (which often also describes why and more). This
>              flag will prevent curl from outputting that and return
>             error 22.
>
>              This method is not fail-safe and there are occasions where
>              non-successful response codes will slip through,
>              especially when authentication is involved (response codes
>              401 and 407).

</details>

Adding it seems fixes the issue

```cmd
# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output netdata.gz.run https://github.com/netdata/netdata/releases/download/1.32.1/netdata-armv6l-latest.gz.run
curl: (22) The requested URL returned error: 404
# echo $?
22
```
