### ISSUE TITLE
[Bug]: Netdata healthcheck failing after disabling local agent dashboard

### ISSUE THREAD

**Issue by Jasmin25** [netdata/netdata#12063]
### Bug description

I am running latest netdata on docker. As I didn't want the dashboard running on local agent and using resources, I followed this guide to disable local agent dashboard: https://learn.netdata.cloud/docs/configure/common-changes#disable-the-local-agent-dashboard-httpnode19999

After disabling, the data is still being received at https://app.netdata.cloud/ so that's all working as expected. But on my host, the netdata-container is continuously failing healthchecks. 

![image](https://user-images.githubusercontent.com/3504743/151704798-d719fc63-fc3b-419b-ad1a-f2ffd6d5bccf.png)

### Expected behavior

Healthcheck should be independent of local agent dashboard, so even if it is disabled, the healthcheck should succeed. 

### Steps to reproduce

1. Run netdata on Docker
2. Make sure configuration is editable on host using this guide: https://learn.netdata.cloud/docs/agent/packaging/docker#host-editable-configuration
3. Disable local agent dashboard using this guide: https://learn.netdata.cloud/docs/configure/common-changes#disable-the-local-agent-dashboard-httpnode19999 
4. Check status of the container using command: `docker ps --filter "name=<NETDATA_CONTAINER_NAME>"`  and it will show "unhealthy" under status. 

### Installation method

docker

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.7 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.7 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

### Netdata build info

```shell
Version: netdata v1.33.0-9-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

**Comment by ilyam8** [comment]
Hi, @Jasmin25. This can be fixed by setting `NETDATA_HEALTHCHECK_TARGET` env var to "cli", see [Health Checks](https://learn.netdata.cloud/docs/agent/packaging/docker#health-checks).

**Comment by Jasmin25** [comment]
Thanks for the quick response, that resolved the issue!
