### ISSUE TITLE
[Bug]: Doesn't categorise the afpd process

### ISSUE THREAD

**Issue by rossburton** [netdata/netdata#12075]
### Bug description

My NAS uses [netatalk](https://en.wikipedia.org/wiki/Netatalk) to provide a [AFP](https://en.wikipedia.org/wiki/Apple_Filing_Protocol) server.  The process that does the actual I/O is `afpd` but this gets categorised as _other_ in the process charts.

### Expected behavior

`afpd` is categorised as _nfs_, or pulled out into its own category.

### Steps to reproduce

1. run netatalk
2.
3.
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Debian 11
```

### Netdata build info

```shell
netdata 1.29.3
```

**Comment by ilyam8** [comment]
Hi, @rossburton. Are you willing to make a PR? If yes - we need to update `apps_groups.conf`, this particular line [this line](https://github.com/netdata/netdata/blob/944a76b98c6c36ebb403c7f9e748876169fdb929/collectors/apps.plugin/apps_groups.conf#L168) if you think the process should be in the `nfs` group.
