### ISSUE TITLE
[Bug]: missing mqtt_wss_client.h

### ISSUE THREAD

**Issue by meepmeep** [netdata/netdata#12095]
### Bug description

Unable to finish install of netdata because of a missing "mqtt_wss_client.h" (see logs below).
Is there a missing requirement ?

### Expected behavior

It should work .
I'm running netdata since few years, always updating with netdata-updater.sh, but this morning it brokes.

I tried to reinstall from scratch and get this error.

### Steps to reproduce

1. curl -Ss 'https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh' >/tmp/install-required-packages.sh && bash /tmp/install-required-packages.sh -i netdata
2. git clone https://github.com/netdata/netdata.git && cd netdata
3. sudo ./netdata-installer.sh
...

### Installation method

from git

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux Daenerys 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.3 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.3 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.32.1-16-gcdd7e9326
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' '--with-bundled-protobuf' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                   NO
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       NO
    ACLK-NG New Cloud Protocol: NO
    ACLK Legacy:                YES
    TLS Host Verification:      YES
    Machine Learning:           NO
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

  CC       database/sqlite/sqlite_aclk_chart.o
In file included from database/sqlite/../../aclk/aclk.h:6,
                 from database/sqlite/sqlite_aclk.c:10:
database/sqlite/../../aclk/aclk_util.h:6:10: fatal error: mqtt_wss_client.h: No such file or directory
    6 | #include "mqtt_wss_client.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:5763: database/sqlite/sqlite_aclk.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from database/sqlite/../../aclk/aclk.h:6,
                 from database/sqlite/sqlite_aclk_chart.c:8:
database/sqlite/../../aclk/aclk_util.h:6:10: fatal error: mqtt_wss_client.h: No such file or directory
    6 | #include "mqtt_wss_client.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by ilyam8** [comment]
Hi, @meepmeep. You need `--recursive`

> git clone --recursive https://github.com/netdata/netdata

We have this flag in [our docs](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual#install-netdata).

**Comment by meepmeep** [comment]
indeed, I read something about that and I thought I did the recursive git.
Sorry !
