### ISSUE TITLE
API: context queries

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12113]
### Discussed in https://github.com/netdata/netdata/discussions/12112

<div type='discussions-op-text'>

<sup>Originally posted by **ktsaou** February 10, 2022</sup>
@stelfrag I have a question about the context queries of the API.

Let's take an example:

This is a query to get the `net.net` context of all network interfaces from the registry:

```sh
# curl 'https://registry.my-netdata.io/api/v1/data?context=net.net&points=10&before=0&after=-3600&options=jsonwrap|absolute|aligned&format=json&group=average'  
{
   "api": 1,
   "id": "net.net",
   "name": "net.net",
   "view_update_every": 360,
   "update_every": 1,
   "first_entry": 1644242696,
   "last_entry": 1644502692,
   "before": 1644502680,
   "after": 1644499081,
   "dimension_names": ["received", "sent", "received", "sent"],
   "dimension_ids": ["received", "sent", "received", "sent"],
   "chart_ids": ["net.vpn0", "net.vpn0", "net.eth0", "net.eth0"],
   "latest_values": [0, 0, 152.1515692, -101.602063],
   "view_latest_values": [2.3656864, 0, 177.8589566, 230.913013],
   "dimensions": 4,
   "points": 10,
   "format": "json",
   "result": {
 "labels": ["time", "received", "sent", "received", "sent"],
    "data":
 [
      [ 1644502680, 2.3656864, 0, 177.8589566, 230.913013],
      [ 1644502320, 3.0973238, 0, 178.8174752, 234.0979086],
      [ 1644501960, 2.420643, 0.0015556, 241.082902, 249.3213201],
      [ 1644501600, 1.7989107, 0, 181.404258, 255.9037317],
      [ 1644501240, 2.9663318, 0, 183.7845692, 243.5694234],
      [ 1644500880, 3.2396554, 0, 187.1236171, 264.6914973],
      [ 1644500520, 3.6822969, 0, 181.2079066, 239.4728118],
      [ 1644500160, 2.5123004, 0, 183.8695478, 241.8341782],
      [ 1644499800, 1.8818442, 0, 177.1267165, 233.9350358],
      [ 1644499440, 1.7134265, 0, 177.5188331, 244.8658513]
  ]
},
 "min": -264.6914973,
 "max": 241.082902
}
```

We see that it returned 5 dimensions:

1. the timestamp
2. `net.vpn0/received`
3. `net.vpn0/sent`
4. `net.eth0/received`
5. `net.eth0/sent`

Note that we requested `group=average`, so for every of the 10 points received, the agent aggregated `"view_update_every": 360` database points, with the `sum` function.

All good so far.

Now we run the same query, but we request back a flattened array:

```sh
# curl 'https://registry.my-netdata.io/api/v1/data?context=net.net&points=10&before=0&after=-3600&options=jsonwrap|absolute|aligned&format=array&group=average' 
{
   "api": 1,
   "id": "net.net",
   "name": "net.net",
   "view_update_every": 360,
   "update_every": 1,
   "first_entry": 1644242697,
   "last_entry": 1644502693,
   "before": 1644502680,
   "after": 1644499081,
   "dimension_names": ["received", "sent", "received", "sent"],
   "dimension_ids": ["received", "sent", "received", "sent"],
   "chart_ids": ["net.vpn0", "net.vpn0", "net.eth0", "net.eth0"],
   "latest_values": [0.3820606, 0, 125.6404329, -220.1619118],
   "view_latest_values": [2.3656864, 0, 177.8589566, 230.913013],
   "dimensions": 4,
   "points": 10,
   "format": "array",
   "result": [2.3656864,3.0973238,2.4221986,1.7989107,2.9663318,3.2396554,3.6822969,2.5123004,1.8818442,1.7134265],
 "min": 1.7134265,
 "max": 3.6822969
}
```

Boom! What is this? How the dimensions where flattened? Which algorithm was used?
I was expecting a sum of all dimensions into one.

Note the `before` and `after` of both responses. They match.

So, how (the first row in the first response):

```
2.3656864, 0, 177.8589566, 230.913013
```

leads to (the first number of the second response):

```
2.3656864
```

Further questions:

1. The context query, does it go through multiple hosts of a parent, or limits itself to the host it queried?
2. Normally, it would be beneficial the flattening of multiple dimensions to one to happen using a different algorithm. But there is no option to do that. Can we add it?

</div>

**Comment by ktsaou** [comment]
@hugovalente-pm this is the issue we faced about context queries. It is required for changing node page at the cloud.

**Comment by hugovalente-pm** [comment]
@ktsaou that is then linked to this one netdata/cloud-frontend#2875, will ping you on that one to clarify one thing
