### ISSUE TITLE
[Feat]: Group processes based on state

### ISSUE THREAD

**Issue by myin142** [netdata/netdata#12139]
### Problem

Currently the processes are only grouped in running and blocked states, so it's not possible to see the number of processes in each state like Running(R), Sleep(D or S) or Zombie(Z). Especially zombie processes are useful to know about.

### Description

Discussed in #12133

Instead or in addition to the running and blocked states, it should show the processes in each state that Linux supports.

### Importance

really want

### Value proposition

1. It's a more detailed information that what we currently get.
2. Knowing how much zombie processes are on your system could help spotting potential problems.

**Comment by ilyam8** [comment]
From what I know there is no effective way to get the number of processes/threads in a state. 
- this can be done only by reading `/proc/[pid]/stat` (e.g. [node_exporter processes collector](https://github.com/prometheus/node_exporter/blob/f7086d437bc0b652ad56fe1a775b1994d7076796/collector/processes_linux.go#L118-L148) does it).
- 3rd field is the state.

> Note: **running** and **blocked** (system.overview chart) we get from `/proc/stat`, that file contains only those counters.

From [man procfs](https://man7.org/linux/man-pages/man5/proc.5.html):

| Character | Description                                                        |
|-----------|--------------------------------------------------------------------|
| R         | Running                                                            |
| S         | Sleeping in an interruptible wait                                  |
| D         | Waiting in uninterruptible disk sleep                              |
| Z         | Zombie                                                             |
| T         | Stopped  (on a signal)  or  (before Linux 2.6.33) trace stopped    |
| t         | Tracing stop (Linux 2.6.33 onward)                                 |
| W         | Paging (only before Linux 2.6.0)                                   |
| X         | Dead (from Linux 2.6.0 onward)                                     |
| x         | Dead (Linux 2.6.33 to 3.13 only)                                   |
| K         | Wakekill (Linux 2.6.33 to 3.13 only)                               |
| W         | Waking (Linux 2.6.33 to 3.13 only)                                 |
| P         | Parked (Linux 3.9 to 3.13 only)                                    |

---

[apps.plugin](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin#appsplugin) parses procfs ([including stat file](https://github.com/netdata/netdata/blob/2ff0c5c3cf96a80eaed28c955edb00dc6a249dd8/collectors/apps.plugin/apps_plugin.c#L1351) for every process), so it already has all needed data, we need just to create charts.

cc @vlvkobal 

- we can create a chart per state (processes family).
- default is only for Z (zombie).
- can be adjusted via the configuration file.

The problem with Z processes is their command (`proc/[pid]/comm`) is "defunct", I think the same goes for the command line (`proc/[pid]/cmdline`). So we can't group them 😑.

We don't really do this, but I see no problem with the following - why don't we add just a chart with the number of processes in a state per state to apps.plugin?

**Comment by codeguru1** [comment]
One thing I don't understand about this feature request is, what benefit is there to collect the number of Zombie processes in a system? Except for holding PID they are not consuming any resources. A zombie process is a process which has exited properly, released all its resources, but is maintaining a place in the process table.

**Comment by myin142** [comment]
I am relatively new to all this monitoring but doesn't every bit of information help finding problems. If there are suddenly many zombie processes I would assume there is some kind of problem. Or are zombie processes something completely normal that you shouldn't pay attention to?

**Comment by ilyam8** [comment]
I think they are not normal and usually, you want to find the cause. cc @Ferroin
