### ISSUE TITLE
[Feat]:  Looking for authors on "Observability with Netdata"

### ISSUE THREAD

**Issue by diksahtn** [netdata/netdata#12132]
### Problem

We are looking for authors on "Observability with netdata"
Mail:
You can connect with dikshant@bpbonline.com

### Description

Observability with Netdata
Observability enables IT teams to better understand their infrastructure, allowing them to identify and troubleshoot issues quickly, collaborate to solve problems, and make data-driven decisions to move the business forward.
With insightful metrics, visualizations, and data-driven dashboards, this book provides IT teams with complete, comprehensive, real-time visibility into the entire technology stack.

This book explains the purpose of observability and how it can be used in your IT environment to improve performance and solve problems. We show how to install Netdata on various operating systems, including Linux, macOS, and container platforms such as Kubernetes and Docker.

Then we learn how to monitor the entire technology stack, including systems, hardware, applications, databases, devops, and containers. You will be assessing, monitoring, and troubleshooting your infrastructure with a series of insightful metrics, visualizations, and data-driven dashboards for improved site reliability and continuous high-performance of business systems and applications. For complete control of the containerization infrastructure, you will be monitoring the status of hundreds or thousands of individual containers, as well as various container agents such as dockerd, kubelet, and kube-proxy. Then, we monitor popular databases such as MySQL, MongoDB, CockroachDB, PostgreSQL, and Redis, keeping a close eye on the health and performance of enterprise databases. Toward the end of the book, experts will share some of their best practices for keeping a close eye on every infrastructure asset and monitoring its health status around the clock on a single dashboard.

**Target Audience:**
System Administrators, IT Administrators, Network Administrators, Network Engineers, System Analyst, Cloud Administrators, SRE Team.

**Page count:** 250 - 325 pages

### Importance

nice to have

### Value proposition

1.Contact us
2.
3.
...

**Comment by ilyam8** [comment]
Hi, @diksahtn. Can you update the title? It is missing.

**Comment by diksahtn** [comment]
> Hi, @diksahtn. Can you update the title? It is missing.

Which title you are talking about.
