### ISSUE TITLE
Discord link is not working

### ISSUE THREAD

**Issue by vobruba-martin** [netdata/netdata#12137]
### Bug description

I tried Discord link in the latest release description and it is not working

![image](https://user-images.githubusercontent.com/6897988/153935165-2f858408-4739-4a64-a568-18893d565e85.png)

### Expected behavior

Working link

### Steps to reproduce

1.
2.
3.
...

### Installation method

other

### System info

```shell
...
```

### Netdata build info

```shell
...
```

**Comment by vobruba-martin** [comment]
I've found a working link [here](https://www.netdata.cloud/blog/netdata-is-launching-its-discord-server/): https://discord.gg/mPZ6WZKKG2

**Comment by ilyam8** [comment]
Thanks for letting us know, @vobruba-martin. I've updated the link.
