### ISSUE TITLE
[Feat]: discover apps running on the host system

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#12152]
### Problem

The current application's detection logic is non-existent in fact. We rely on a list of predefined jobs for every data collection module (e.g [apache.conf](https://github.com/netdata/go.d.plugin/blob/cdc567315a86ffe55faffc324e98daf8691f912c/config/go.d/apache.conf#L156-L161), [mysql.conf](https://github.com/netdata/go.d.plugin/blob/cdc567315a86ffe55faffc324e98daf8691f912c/config/go.d/mysql.conf#L89-L136)).

pros:
 - very simple and explicit.

cons:
 - listing all theoretically possible targets results in a huge [prometheus.conf](https://github.com/netdata/go.d.plugin/blob/cdc567315a86ffe55faffc324e98daf8691f912c/config/go.d/prometheus.conf#L208) (661 jobs).
 - since we don't really know if an app is running, this approach is basically a port scan. **Which we do on every Netdata (re)start**.
 - 99.9% of predefined jobs fail (and are supposed to do so), but it produces [a lot of log messages](https://github.com/netdata/netdata/issues/6038).

### Description

Part of netdata/product#2751.

---

Use the mechanisms offered by the host system to 

1. discover running applications
2. identify them (guessing is acceptable here)
3. create appropriate data collection jobs based on 1. and 2.

This should work **during runtime**.

### Importance

must have

### Value proposition

1. fixes problems describes as "cons" in the **Problem** section (significantly reduce the number of error/warning messages in the error.log file which is great by itself).
2. allows automatically creating data collection jobs during runtime (no need to restart netdata service).
3. enabler for some interesting features described in netdata/product#2751 (e.g. if we discover that application A is running and we have a collector for it, but fail to gather data - we can notify about it in the UI).

### Proposed implementation

I don't have specifics about implementation now. We will do some research with @codeguru1 and update this issue.

- this feature applies only to go.d.plugin.
- we need to restructure the go.d.plugin current discovery mechanism (read config files) to be extensible, so we can add additional _discoverers_.

**Comment by codeguru1** [comment]
The first step towards implementation (for localhost) would be to keep track of active(LISTEN) ports/new services and map it to the available collectors. Based on this information, go.d.plugin would propagate message to netdata-agent. The best approach to keep track of active ports(and deduce new service) is reading procfs(e.g/proc/net/tcp). We need to evaluate if there are already some libraries implemented. For example:
1. https://github.com/mitchellh/go-ps
2. https://github.com/cakturk/go-netstat

These packages seem not to be maintained recently. But this can be a pointer for us to implement our own (if needed) in a platform agnostic way. For example, we probably want to support Linux, FreeBSD and Darwin.

**Comment by thiagoftsm** [comment]
> The first step towards implementation (for localhost) would be to keep track of active(LISTEN) ports/new services and map it to the available collectors. Based on this information, go.d.plugin would propagate message to netdata-agent. The best approach to keep track of active ports(and deduce new service) is reading procfs(e.g/proc/net/tcp). We need to evaluate if there are already some libraries implemented. For example:

About the listening ports, I already taked with @cpipilas and we plan to bring this feature with eBPF.plugin this quarter.

I observed that you cited `/proc/net/tcp`, if there is not any library available, you can take a look [here](https://github.com/netdata/netdata/blob/master/collectors/ebpf.plugin/ebpf.c#L1845-L1848) and [here](https://github.com/netdata/netdata/blob/master/collectors/ebpf.plugin/ebpf.c#L949-L974), because part of the code for the new chart were already merged.

Any doubt, please, let me know.

**Comment by ilyam8** [comment]
@thiagoftsm is great the feature is going to be (asap) added ebpf, but it doesn't help us at all now.

**Comment by thiagoftsm** [comment]
@Ferroin I think netdata agent could create a named shared memory for all process to communicate. between them. We could have a thread dedicated to do this.

**Comment by Ferroin** [comment]
I suspect implementing it as a segment per info source may be better in the long run. The tricky part regardless would be dependency tracking though (for example, if we are running eBPF, then the process supplying the data needs to provide info from `/proc/net/tcp`, but if we are not running anything that needs it we shouldn’t waste resources parsing/fetching it)

**Comment by ilyam8** [comment]
Implemented in #17064.
