### ISSUE TITLE
[Feat]: installer preflight check – "if library X is installed, then optional feature Y can be enabled at install time"

### ISSUE THREAD

**Issue by petecooper** [netdata/netdata#12170]
### Problem

Netdata is capable of monitoring an increasing number of metrics on a given server. Some metrics are not enabled at install time unless one or more specified libraries / dependencies are installed and enabled, for example:

https://github.com/netdata/netdata/blob/38536eb4238b8e9018f96377eaf79636240fd424/netdata-installer.sh#L256

I have no visibility of whether `libgoogle_cloud_cpp_pubsub_protos` and dependencies are available unless I run a script to check myself. If it's trivial for me to install additional dependencies to take full advantage of Netdata's feature set, I would really like that option.

### Description

Provide an option to run the Netdata installer in preflight mode. This mode will check for optional libraries / dependencies that are required for optional features at time of install.

Note: this is _not_ related to collectors where there's nothing to collect (i.e. Apache log collector where Apache isn't installed), but specifically for install time functionality.

### Importance

nice to have

### Value proposition

1. More servers & users can make use of existing features (i.e. the work is already done on the Netdata side, and for a small amount of work installing an extra library, more features can be enabled at the server side).
2. More users use functionality, more eyeballs, improvements can be made to features.
3. Project brings attention to lesser-known features, valuable PR exercise.

### Proposed implementation

The checks that are run within the installer could perhaps be outboarded to run a preflight check _before_ the installer commences, maybe with a `--preflight` option or similar.

**Comment by ilyam8** [comment]
I think this is no longer relevant because using netdata-installer.sh (compiling from source) is not a recommended way to install Netdata. cc @netdata/agent-sre
