### ISSUE TITLE
"charts to skip from training" should only exclude charts where anomaly detection will not add value

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#12177]
#### Summary

- The current list of "charts to skip from training" is more an inclusion list than an exclusion list, since we specify what not to exclude and exclude everything else.

`    # charts to skip from training = !system.* !cpu.* !mem.* !disk.* !disk_* !ip.* !ipv4.* !ipv6.* !net.* !net_* !netfilter.* !services.* !apps.* !groups.* !user.* !ebpf.* !netdata.* *`

- More specifically the concern is that application specific metrics are all ignored which means that anomalies within an applications functioning will not be detected.

- The objective of this ticket is to discuss and arrive at a final list of metrics/charts to skip from training

- This ticket is linked to #12178  which is required to auto select dimensions for training, otherwise we run the risk of having too many dimensions to train for and running up a high CPU/perf cost.

**Comment by andrewm4894** [comment]
i'm not sure what the specific issue is with the defaults as they are?

application specific measures are covered by `!apps.*`. 

unless maybe @ktsaou means that we should add more such that if specific collectors are enabled then they would be automatically picked up. 

for example on london demo site you can see that [nginx charts](http://london.my-netdata.io/#menu_nginx_local;after=0;before=0;theme=slate;utc=Europe/Dublin) would not be included by default. 

so maybe the thinking is we should add much more in anticipation such that user does not have to do the manual config to add an `!nginx*` entry perhaps?

**Comment by shyamvalsan** [comment]
@andrewm4894 yes that's exactly the point, that any application specific charts (nginx, postgres, whatever) should show up here. 
The config is after all named "charts to skip from training" so the user would not think they need to manually add any charts here.

**Comment by ktsaou** [comment]
> i'm not sure what the specific issue is with the defaults as they are?
> 
> application specific measures are covered by `!apps.*`.

@andrewm4894 no, they are not. `apps.*` monitors the resource utilization of applications. That is, their CPU, RAM, network, disk, etc. They do not include application metrics, my mysql queries, mysql index performance, nginx connections, etc.

In fact, every application generated metric is ignored with the default setting.

> unless maybe @ktsaou means that we should add more such that if specific collectors are enabled then they would be automatically picked up.

The filter should work the other way around. Exclude charts we know they are not useful for anomaly detection and metrics we know they are noisy. Everything else is potentially useful. So, everything except a very specific list, should be included.

> for example on london demo site you can see that [nginx charts](http://london.my-netdata.io/#menu_nginx_local;after=0;before=0;theme=slate;utc=Europe/Dublin) would not be included by default.

Exactly! Actually every application generated metric is excluded with the default setting.

> so maybe the thinking is we should add much more in anticipation such that user does not have to do the manual config to add an `!nginx*` entry perhaps?

Why to pick a few? Exclude a few and let all the others automatically participate in anomaly detection.

With ticket https://github.com/netdata/netdata/issues/12178 we will eliminate automatically every metric that seems irrelevant for ML training and prediction.

**Comment by andrewm4894** [comment]
@vkalintiris maybe we might think a bit more about another more obvious and cleaner way to define this. With still some maybe hard upper limit perhaps so we still have some upper bound.

Not sure but agree would be nicer if the ml "just worked" a bit more out of the box for whatever collectors etc are enabled (up to some same limit or upper bound we can at least have a gaurantee on maybe (which the user can increase if they want maybe.

**Comment by shyamvalsan** [comment]
@andrewm4894 @vkalintiris wonder if as part of the testing that @erdem2000 is doing - after the default config is testing - we could run some tests to find the "breaking point" and set a max threshold for number of dimensions based on that? Then leave it to the user to change it if they so wish. 

Also, can we arrive at a list of charts or metrics where we're all agreed we do NOT want to monitor for anomalies for functional reasons (because the user wouldn't care)? @ktsaou mentioned we should exclude Netdata metrics. Who's the right expert to have that discussion with?

**Comment by ktsaou** [comment]
> Also, can we arrive at a list of charts or metrics where we're all agreed we do NOT want to monitor for anomalies for functional reasons (because the user wouldn't care)? @ktsaou mentioned we should exclude Netdata metrics. Who's the right expert to have that discussion with?

I think `netdata.*` can be safely excluded. These are internal netdata metrics, not something useful for the infra of the users.

For the others, I would first attempt not exclude anything and see in real-life which ones are usually noisy (via the anomaly rate bar on the charts), to exclude them. We have to be very picky here. We need to exclude only metrics that are alway problematic. If something is potentially useful and we exclude it, we will hurt the usefulness of the entire project.

> @andrewm4894 @vkalintiris wonder if as part of the testing that @erdem2000 is doing - after the default config is testing - we could run some tests to find the "breaking point" and set a max threshold for number of dimensions based on that? Then leave it to the user to change it if they so wish.

I suggest to add a configuration item for this, but leave it unset by default. We don't want to limit it before enabling ML by default. So, while ML is not enabled by default, there should be no cap.

**Comment by vkalintiris** [comment]
> I would first attempt not exclude anything and see in real-life which ones are usually noisy

I like this idea. I'll have a custom version of the agent run, and I'll try to see how many of them we could remove.

**Comment by andrewm4894** [comment]
We will have thumbs up and down at the metric level when user expands a row in the heatmap. So from that over time we will build up a thumbs up/down ratio or thumbs down rate for each metric. From that then we will be able to see what metrics across all our users have consistently high thumbs down rates. That will then be user driven evidence that we will need to rethink those specific metrics. 

I'd be ok with excluding `netdata` stuff (i'll be manually turning them back on for our internal dogfooding but agree not really something out of the box we want to annoy users with - every cloud session will elevate all the `netdata` related metrics for example so we can consider that noise from users POV).

I'm hesitant to make any real judgement or decisions on any specific handling of specific metrics unless we have really strong theoretical justifications. For example, excluding the `netdata` ones being a good example of this. So maybe there is more here, i dont know.  

> see in real-life which ones are usually noisy

This is what I would be hesitant to do anything too rash on just yet since we would need to unleash it on the whole world of nodes and servers to really get a proper feel for this - which is what the thumbs up/down user driven telemetry is trying to formalise a bit more.

**Comment by shyamvalsan** [comment]
@andrewm4894 So let's say we just exclude `netdata` stuff and everything else is included by default + we have @vkalintiris recent change to ensure constant dimensions are not re-trained. 

For internal dog-fooding we should just leave all dimensions in and see how it fares. 

Then we can take a look at the anomaly rate variation (and CPU/perf cost) and decide if we need to exclude more dimensions. 

If we are in agreement, let's revisit this issue closer to MVP (post dog-fooding) and make the final call.

**Comment by shyamvalsan** [comment]
@andrewm4894 @ktsaou 

So are we OK to now make the below change? 

**Current:** 
`# charts to skip from training = !system.* !cpu.* !mem.* !disk.* !disk_* !ip.* !ipv4.* !ipv6.* !net.* !net_* !netfilter.* !services.* !apps.* !groups.* !user.* !ebpf.* !netdata.* *
`
**Proposed:**
`# charts to skip from training = netdata.* *`

**Comment by vkalintiris** [comment]
> I'm hesitant to make any real judgement or decisions on any specific handling of specific metrics unless we have really strong theoretical justifications. For example, excluding the netdata ones being a good example of this. So maybe there is more here, i dont know.

FWIW, `interrupts + softirqs` related charts & dimensions are very noisy on my host.

**Comment by shyamvalsan** [comment]
**Proposed:**
`# charts to skip from training = netdata.* * cpu.interrupts.* cpu.softirqs.*`

Yes, we would expect those two to be noisy. So considering the proposed list here, we're not going to gain a lot in terms of performance by excluding these metrics but we should reduce unnecessary anomaly triggers.

**Comment by shyamvalsan** [comment]
Closed by https://github.com/netdata/netdata/pull/12494
