### ISSUE TITLE
[Bug]: Custom dashboard for remote server with authentication

### ISSUE THREAD

**Issue by myin142** [netdata/netdata#12172]
### Bug description

I cannot create a custom dashboard for a remote server that needs authentication.

I am currently protecting the netdata endpoint with nginx authentication. But in the custom dashboard I cannot add any kind of authentication to the request. It does ask me for the username and password for the remote server via nginx. But it isn't used in the request. The `Authorization` header is not set. The dashboard works if I remove the authentication.

### Expected behavior

Dashboard should work with a remove server that needs authentication. The requests should have an `Authorization` header.

### Steps to reproduce

1. Setup netdata behind nginx with authentication
2. Create a custom dashboard that displays data for that server
3. Access the dashboard and input the username and password
4. Nothing gets shown because the request fail either with a CORS error or 401 error.
...

### Installation method

kickstart.sh

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.3 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.3 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.33.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by myin142** [comment]
I also tried this option. Some requests (I think only OPTIONS) did send with the authentication data. Most of the other used the normal URL without authentication.

**Comment by cpipilas** [comment]
@jacekkolasa any ideas/options to move this forward?

**Comment by jacekkolasa** [comment]
@myin142 is the authentication header sent properly, if the charts are on the same host as the host of the Custom Dashboard?

I've proxied dashboard behind `auth_basic` and the headers seem to be ok.
If you have different hosts in Custom Dashboard, i suggest you setup your routing in nginx config. Maybe it will work when you first access host of those charts directly in the browser, so you're then being asked for the authentication, and afterwards the calls from your Dashboard are authenticated properly?

Generally speaking, Netdata dashboard doesn't do anything with authentication, it should all have been handled by nginx configs.

**Comment by myin142** [comment]
I assume so. I needed this because I wanted a single dashboard for multiple servers and I think the same host worked but not the remote host since that needed authentication. But I'm not working on that project anymore. I can't really try things out anymore.
