### ISSUE TITLE
[Bug]: The Netdata Cloud said that my node does not have proto-support but my node said it does

### ISSUE THREAD

**Issue by AnnAngela** [netdata/netdata#12193]
### Bug description

The Netdata Cloud said that my node does not have proto-support:

![image](https://user-images.githubusercontent.com/9762652/154877465-8806a935-4f4f-4559-a138-9630f8ebe642.png)

 but my node said it does:

![image](https://user-images.githubusercontent.com/9762652/154877554-f189b526-9298-4563-80b0-2a12761d2c0f.png)

I tried to reinstall the agent, but it doesn't change anything.

### Expected behavior

They should say the same thing.

### Steps to reproduce

Just open the netdata cloud and see the notification.

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.33.1-30-g0a51695ef
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by stelfrag** [comment]
@AnnAngela thank you for reporting this, we will take a look on the cloud side. Your agent is good to go indeed and will work just fine.

**Comment by stelfrag** [comment]
@ravilushqa @burbuli8ra can you please check?

**Comment by ravilushqa** [comment]
@stelfrag yes, I'll check it

**Comment by ravilushqa** [comment]
@AnnAngela thanks for reporting! Can you please share your account email or space-id to identify your problem

**Comment by burbuli8ra** [comment]
Hello @stelfrag !
In Cloud dashboard FE we display the value of `isProtobufCapable` key for each node, received from the API call of `/api/v1/spaces/{spaceId}/rooms/{roomId}/nodes`!
I am not quite sure how the mechanism of BE validates protobuf support for adding the value to the response, but in order to make sure that this issue is on BE side only, would it be possible for you to invite me to the space that the issue occurred and also share the node id which should have protobuf support for checking the api response to verify that we indeed receive `isProtbufCapable: true` for it?

**Comment by ravilushqa** [comment]
Also I've updated nodes state in the cloud, so your problem might be solved

**Comment by AnnAngela** [comment]
> @AnnAngela thanks for reporting! Can you please share your account email or space-id to identify your problem

Oh, I've re-checked the space page and the notification has been gone, NP now.

(Just wanted to mention, in many times the space page needs too much time to update the nodes' states, for example the alarm status, IDK why =。=)
