### ISSUE TITLE
[Feat]: NXINX Unit support

### ISSUE THREAD

**Issue by aehlke** [netdata/netdata#12204]
### Description

I see explicit support for Nginx, Nginx+ but couldn't find reference if their more modern application server Nginx Unit is supported by this project. Thanks

### Importance

blocker

### Value proposition

1. performance monitoring not just of other layers of my stack, but also the web layer. nginx unit is clearly the future of nginx platform so more community will move to it over time as it continues to expand and catch up with capabilities.

**Comment by ilyam8** [comment]
Hi, @aehlke. You are correct, we have no collector for NGINX Unit. Brief googling showed that it [doesn't expose any metrics](https://github.com/nginx/unit/issues/427). Am I missing something? Do you know how to gather metrics from NGINX Unit?

**Comment by aehlke** [comment]
Good question and amazingly it seems you're right :( Subscribed to the issue to monitor

**Comment by aehlke** [comment]
Upstream now moved it to scheduled for their upcoming sprint, and have asked for any input on what metrics would be helpful - any experience to offer them on that point?

**Comment by ilyam8** [comment]
@aehlke I think the developers know better - in general performance and health metrics.

**Comment by websitevirtuoso** [comment]
I hope that we will find any way how to monitor nginx php-unit in netdata

**Comment by ilyam8** [comment]
@websitevirtuoso I see that basic metrics were added (https://github.com/nginx/unit/issues/427#issuecomment-1127412471). Can you check it on your instance?

**Comment by oracast** [comment]
@ilyam8 Yes I can. Could you assist me in which menu item to check them? I will be happy to help

**Comment by websitevirtuoso** [comment]
@ilyam8 Yes I can. Could you assist me in which menu item to check them? I will be happy to help
