### ISSUE TITLE
[Feat]: netdatacli aclk-state info

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12217]
### Problem

```sh
# netdatacli aclk-state
ACLK Available: Yes
ACLK Implementation: Next Generation
New Cloud Protocol Support: Yes
Claimed: Yes
Claimed Id: eef2e7b4-1976-11e6-ae19-7cdd9077342a
Online: Yes
Used Cloud Protocol: Legacy
```

### Description

Users do not have enough visibility on what is happening, so it is impossible for them to trace, debug and report ACLK connectivity issues.

### Importance

blocker

### Value proposition

Provide enough information so that people can see how cloud connectivity works.

### Proposed implementation

```
Netdata version: <VERSION>
Netdata Uptime: DATE and TIME
Cloud URL: <CLOUD URL>

ACLK: available or not available
Version: 2 (instead of Next Generation)
Protocols Supported: LEGACY or PROTOBUF (instead of Legacy and New)
Protocol Used: PROTOBUF (instead of Legacy and New)
Claim Id: <CLAIM_ID>
Status: ONLINE or TRANSPORT (connected but never heard anything for cloud) or OFFLINE
Last Connected: DATE and TIME
Reconnects: # of reconnects so far
Messages sent: number
Messages received: number

Node: <HOSTNAME>
Machine Guid: <MACHINE_GUID>
Node Id: <NODE_ID> or NONE
Status: ONLINE or TRANSPORT or OFFLINE
Child: IP:PORT or ME or STALE (old child we have data for)
Parent: IP:PORT or NONE
Hopes: number of streaming hops.
Node Metadata: IDLE or STREAMING, batch id: number, last acked: sequence number, waiting to send: <FROM> - <TO>
Charts Metadata: IDLE or STREAMING, batch id: number, last acked: sequence number, waiting to send: <FROM> - <TO>
Alerts Metadata: IDLE or STREAMING, batch id: number, last acked: sequence number, waiting to send: <FROM> - <TO>
Queries: # of API queries received so far

(similarly for all nodes served by this agent)
```

**Comment by ktsaou** [comment]
@underhood please have a look.

**Comment by underhood** [comment]
Yep on it, most of it is easily added.

- `Status: ONLINE or TRANSPORT (connected but never heard anything for cloud) or OFFLINE` This one needs to be groomed with cloud properly as agent currently has no notion of cloud considering it offline. We do care about MQTT connection being alive (both by sending MQTT pings and by other means like counting PUBACKS) so we do indeed know our comms are working. We do not have a way to know currently if Cloud-UI considers us online.

- netdata version and netdata uptime -> reason to create this endpont is to not polute info until it becomes huge mess. Most of stuff you gave as example above we need and should add. I would however add only ACLK related fields

**Comment by ktsaou** [comment]
> * We do not have a way to know currently if Cloud-UI considers us online

You are right, but still there is a strong indication you are online: the cloud talks to you back at the application level. Until you hear something back, you are not online for sure.

Anyway, if you add the message counters I suggested, we will be able to see you are not online by the message counts.



> * netdata version and netdata uptime -> reason to create this endpont is to not polute info until it becomes huge mess. Most of stuff you gave as example above we need and should add. I would however add only ACLK related fields

Yes, ok.
