### ISSUE TITLE
[BUG]: Queries from the cloud for non existing nodes should return appropriate error

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#12243]
### Problem

 Long timeouts on the cloud because the agent will not respond for failed queries with a failed message

### Description

Queries from the cloud for a non existent node id now record an error message in the error.log but do not inform the cloud

```
2022-02-25 08:19:34: netdata ERROR : ACLK_Query_0 : Host with node_id "xxxxxxxx/api/v1/data?after=1645769674&before=1645769974&context=system.net&dimensions=received&format=json&group=average&gtime=0&options=absolute%7Callow_past%7Cflip%7Cjsonwrap%7Cms&points=35" not found! Query Ignored!
```

- The error should be in the access.log
-  A response of the failure should reach the cloud

### Importance

blocker

### Value proposition

1.
2.
3.
...

**Comment by ktsaou** [comment]
This is not a feature. It is a high priority bug!

When the agent does not respond to the cloud, the cloud has only one option: wait a really long time and then timeout!

This is the worst thing to do at the agent. Is like keeping an HTTP socket open and never replying to it, waiting for the browser to timeout.

We are constantly experiencing such timeouts on the cloud. The cloud team has set a hard timeout on all agents requests to 10s, to work around it, which has another big set of problems. What if the query is for huge amounts of data that cannot be completed in 10 seconds?

Please fix this asap and make sure the agent **ALWAYS** responds to the cloud, no matter what the condition are, no exceptions allowed at all.
