### ISSUE TITLE
[Bug]: Netdata Agent does not start automatically in Ubuntu nodes. 

### ISSUE THREAD

**Issue by tkatsoulas** [netdata/netdata#12250]
### Bug description

When you install the Netdata Agent in a Ubuntu machine (v20.04+), the netdata.service is not enabled by default.

### Expected behavior

Autostart the Netdata Agent.

### Steps to reproduce

1. Create a fresh install of Ubuntu
2. Run the kickstart script

### Installation method

kickstart.sh

### System info

```shell
# uname -r 
5.13.0-28-generic
```

### Netdata build info

```shell
netdata -W buildinfo
Version: netdata v1.33.1-30-g0a51695ef
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by Ferroin** [comment]
Further info:

* I’ve reproduced this myself now on Ubuntu 20.04.
* Systemd recognizes properly that we should be enabled by default (second line of `systemctl status netdata` on an affected system includes `vendor preset: enabled`).
* The issue is invariant of the kickstart script. Manually configuring the repositories and installing the package by hand still shows the same problem. This indicates the problem is somewhere in our package.

Note that this _cannot_ be properly reproduced in a Docker container, it needs an actual Ubuntu system (be it a VM or a physical machine), as it has to do with service handling by the init system.

**Comment by ralphm** [comment]
I looked into this a bit, as I encountered the problem in a fresh virtual machine. This [question](https://unix.stackexchange.com/questions/274624/automatically-enable-systemd-services-installed-using-deb) has several answers, and I _think_ that we need to explicitly add `dh-systemd` as a `Build-Depends` in the `control` file, to have it create instructions in `postinst` to enable the service as per the vendor preset.

**Comment by ralphm** [comment]
Right. I'll dig some more then.

**Comment by ralphm** [comment]
After a bit of digging by building the package myself, it turns out that including `db_systemd` as above triggers the section inserted at `#DEBHELPER#` to include the following snippet. This properly enables the service as expected and isn't there in the packages we publish. So there is some _magic_ involved by the inclusion of this dependency.

```
# Automatically added by dh_systemd_enable/12.10ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'netdata.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'netdata.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'netdata.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'netdata.service' >/dev/null || true
	fi
fi
# End automatically added section
```

I understand that `dh-systemd` is a transitional package, so I don't know why this works (for me). I don't know if explicitly triggering the inclusion of `dh_systemd_enable` is the _proper_ way.

**Comment by ralphm** [comment]
Possibly, this doesn't work as expected in the way we currently have it because the compat level we use is 9, whereas level 10 has the systemd stuff included in the init sequence.

**Comment by ralphm** [comment]
I have rebuilt with compat level 10, and that seems to work as expected, so maybe we should consider upping this?

**Comment by Ferroin** [comment]
Ah, yeah, we probably should do that. I had completely forgotten we were still on compat level 9 even though we no longer have any platforms we build for that use debhelper 9. I’ll get a PR opened shortly to bump that.

**Comment by ralphm** [comment]
I just checked the most recent nightly (236), but it seems that `postinst` still doesn't have the expected bits for enabling the package, even though my locally created package does. There must be something different between the build machine and mine.
