### ISSUE TITLE
[Bug]: Netdata packages installed by kickstart should have predictable binding by default

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12256]
### Bug description

Today, we ship binary packages that have by default a different binding for netdata:

1. DEB packages, bind by default to `localhost`
2. RPM packages, bind by default to `localhost`
3. Static binaries, bind by default to `*`
4. Source installations, bind by default to `*`
5. Docker installations, bind by default to `*`

Binding to `localhost` requires configuration by most users to enable remote use of netdata in their network. 
Also, binding to `localhost` means that users trying to access `http://ip:19999` they get a "connection refused" message.

If we really need to ship netdata with some access limitations, probably a better way is `allow connections from`, not `bind`.

### Expected behavior

netdata should not have any binding restrictions by default.

### Steps to reproduce

Install netdata in all these different ways.

### Installation method

kickstart.sh

### System info

```shell
All of them.
```

### Netdata build info

```shell
Latest.
```

cc: @Ferroin @ilyam8 @stelfrag

**Comment by Ferroin** [comment]
We _almost_ certainly do want access restricted by default. Netdata _should not_ be exposed globally without some form of security.

Given this, I would suggest that we should:

* Bind to all interfaces.
* Accept connections only from IP addresses that the local system has assigned to it’s interfaces, with the exact value generated at runtime on startup (IOW, on startup, Netdata should check what IP addresses the local system has and set `allow connections from` to that list internally unless it is defined in the user provided `netdata.conf`).
* For Docker containers only, instead default to accepting connections from _subnets_ that the container is on, because limiting to IP addresses only would make the container inaccessible.
* Add special keywords for the above `accept connections from` behaviors so users can explicitly request those behaviors.
* Add info in the installer output that indicates that remote access will require the user to modify configuration.

**Comment by ktsaou** [comment]
We already have an access list in netdata.conf:

```
# allow netdata.conf from = localhost fd* 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* UNKNOWN
```

This allows connections from all private networks.

But, this is a different discussion. This ticket is about binding, which should always be `*` by default.

**Comment by Ferroin** [comment]
I don’t agree that they are different discussions, but I do agree that the default access control list is _probably_ sufficient to not require us changing anything beyond the bind to address.

**Comment by ktsaou** [comment]
@Ferroin all users of netdata should get binding by default to `*`. We never agreed to change that. Please make sure the packages we ship do bind to `*`.

If you believe netdata's web interface should be protected somehow by default, please start a new discussion. For the moment this is not decided, so all netdata packages we ship should not have any access restriction by default. Users can configure access restrictions if they want. But until we decide otherwise, the default should be unrestricted.

**Comment by Ferroin** [comment]
> @Ferroin all users of netdata should get binding by default to `*`. We never agreed to change that. Please make sure the packages we ship do bind to `*`.

I was never the one who set things up this way, it dates from before I joined the company.

> If you believe netdata's web interface should be protected somehow by default, please start a new discussion. For the moment this is not decided, so all netdata packages we ship should not have any access restriction by default. Users can configure access restrictions if they want. But until we decide otherwise, the default should be unrestricted.

We ourselves say that you should not expose Netdata to the public internet without some form of authentication. Our current default access control list is consistent with this, so we should not need to change anything here.

**Comment by ktsaou** [comment]
> I was never the one who set things up this way, it dates from before I joined the company.

I am sorry if I offended you. It was not my intention.

Still binary packages as we ship them today, bind to `lo`. Please make them bind to `*` (remove the setting from `netdata.conf`). Actually we shouldn't ship any netdata.conf by default (this is why we also agreed to remove the web file check).

Please make this happen.

> We ourselves say that you should not expose Netdata to the public internet without some form of authentication. Our current default access control list is consistent with this, so we should not need to change anything here.

As I said, this is separate discussion. Only `netdata.conf` is protected with an access list by default. The discussion about having an access list by default can happen as a separate ticket.

Please bind netdata to `*` by default.
