### ISSUE TITLE
Netdata and OOMScoreAdjust

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12251]
### Problem

Netdata by default sets the following in systemd `netdata.service`:

```
OOMScoreAdjust=1000
```

and in `netdata.conf`:

```
[global]
   OOM score = 1000
```

This means that netdata is the first application to be killed when the system runs out of memory, although netdata may not be the application with memory leak.

### Description

The original idea for this default, was to protect the system when we have a memory leak in netdata.

The worst case scenario (supporting the current default) was this:

You run a database server and together with it netdata. Netdata has a memory leak and pushes the system to go out of memory. If the database server and netdata have the same out of memory score, the database server will be killed by the kernel.

On other hand, in real-life scenarios, it is quite common for applications to leak memory, and by having netdata run with an out of memory score of 1000, netdata is the first the be killed, even when it is not the offender, so users lose their monitoring system first.

### Importance

must have

### Value proposition

The monitoring system should be there to monitor the system even when the system is under memory pressure.

### Proposed implementation

Ideally the monitoring system should not have a memory leak and always work within predictable memory limits. We should have tests in place to ensure there is no possibility to ship a netdata agent with memory issues. In that case, Netdata's out of memory score should be negative. Users should set sensitive apps (like database servers) to a lower setting to ensure they will survive a memory pressure situation.

Since today we cannot guarantee that netdata will never have a memory leak, I suggest to set `OOMScoreAdjust=0` setting in both `netdata.service` and in `daemon.c` (default in `netdata.conf`) and let netdata participate in out of memory situations like any other app.

cc: @Ferroin @ilyam8 @stelfrag

**Comment by Ferroin** [comment]
Starting with just moving to the default OOM score of zero should be sufficient in a vast majority of cases, and avoids the possibility of the agent not getting selected in the event of an OOM event it caused itself. Even if we don’t have any memory leaks, running with a negative score when we _are_ one of the larger memory consumers on most systems (even with dbengine usage) is a bit risky as it can actually lead to an OOM situation taking longer to be resolved automatically (and, on _most_ modern Linux systems, Netdata should be restarted automatically by systemd anyway).
