### ISSUE TITLE
[Bug]: mqtt_wss_client.h: No such file or directory

### ISSUE THREAD

**Issue by mdoulabi1** [netdata/netdata#12264]
[Bug]: mqtt_wss_client.h: No such file or directory

hi
I'm using centos 7 and i'm trying to install net data but i get this eror
i'll be thanksfull to help me.

### Expected behavior

i wanna install netdata on my server

### Steps to reproduce

1. git clone https://github.com/netdata/netdata.git --depth=100
2. cd netdata/
3. ./packaging/installer/install-required-packages.sh --dont-wait --non-interactive netdata 
4.  ./netdata-installer.sh

### Installation method

from git

### System info

```shell
CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
git clone https://github.com/netdata/netdata.git
```

### Additional info

![image](https://user-images.githubusercontent.com/59202978/155947264-092ba2cc-5409-4678-bf72-342fe084a91e.png)

**Comment by MrZammler** [comment]
Hi @mdoulabi1 ! Thanks for the report.

Can you try again please but after the `cd netdata/` do also a `git submodule update --init --recursive` ? You might need to try it again in a clean checkout of netdata.

Thanks!

**Comment by mdoulabi1** [comment]
> Hi @mdoulabi1 ! Thanks for the report.
> 
> Can you try again please but after the `cd netdata/` do also a `git submodule update --init --recursive` ? You might need to try it again in a clean checkout of netdata.
> 
> Thanks!

thank you for your quick reply
i run `git submodule update --init --recursive`  and i got an other error that says :
the ..... file already exists 
removed those file and run command again and fixed my problems.
thanks alot

**Comment by ilyam8** [comment]
Hi, @mdoulabi1. You forgot to add `--recursive` option. See [Install Netdata on Linux from a Git checkout](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual#install-netdata):

```cmd
git clone https://github.com/netdata/netdata.git --depth=100 --recursive
```
