### ISSUE TITLE
[Bug]: Netdata Updater outputs to stderr even on success

### ISSUE THREAD

**Issue by godismyjudge95** [netdata/netdata#12286]
### Bug description

It appears that the Netdata updater outputs to stderr when checking to see if a tmp directory can be used.
This is an issue since some systems are setup to email the root (or other users) when cron jobs output to stderr.

The fix for this is relatively simple, but I don't have enough time at the moment to submit a pull request.

This is the line causing the issue: https://github.com/netdata/netdata/blob/d9c91c23ce318b21c1e11efdcebbbaf9d29096c6/packaging/installer/netdata-updater.sh#L120

The reason why this causes an error is because the script is attempting to execute a script (where on some systems it might fail - ie. if the tmp directory is not executable).

---

### Solution
To fix this all we have to do is change that line to the following:
```bash
      if [ "$("${testfile}" 2>/dev/null)" = "SUCCESS" ] ; then
```

This redirects the stderr to /dev/null and still outputs "SUCCESS" when the script is successfully executed.

---

### Expected behavior

No error should be outputted to stderr on a successful update.

### Steps to reproduce

1. Install Netdata with autoupdate enabled
2. Manually run the update script:  `/etc/cron.daily/netdata-updater`
3. Error is outputted even if the update is successful:
```
/etc/cron.daily/netdata-updater: line 120: /tmp/netdata-test.rCn0Lj9eJn: Permission denied
/etc/cron.daily/netdata-updater: line 120: /tmp/netdata-test.w5QyEkgJcA: Permission denied
```

### Installation method

kickstart.sh

### System info

```shell
Linux mercury.infomedia.com 4.18.0-348.7.1.lve.el8.x86_64 #1 SMP Fri Dec 24 16:27:48 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/cloudlinux-release:CloudLinux release 8.5 (Vladimir Shatalov)
/etc/os-release:NAME="CloudLinux"
/etc/os-release:VERSION="8.5 (Vladimir Shatalov)"
/etc/os-release:ID="cloudlinux"
/etc/os-release:ID_LIKE="rhel fedora centos"
/etc/os-release:VERSION_ID="8.5"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="CloudLinux 8.5 (Vladimir Shatalov)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:cloudlinux:cloudlinux:8.5:GA:server"
/etc/redhat-release:CloudLinux release 8.5 (Vladimir Shatalov)
/etc/system-release:CloudLinux release 8.5 (Vladimir Shatalov)
```

### Netdata build info

```shell
Version: netdata v1.33.1-86-gdcc0aed56
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=-static -O3 -I/openssl-static/include' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by Ferroin** [comment]
@godismyjudge95 Would you be willing to open a PR with the change you proposed? I can do so instead if you want, but I would much rather see you get proper credit for the fix here if possible.

**Comment by godismyjudge95** [comment]
> @godismyjudge95 Would you be willing to open a PR with the change you proposed? I can do so instead if you want, but I would much rather see you get proper credit for the fix here if possible.

Done, I thought there was more of a procedure to submitting a pull request, but it appears I just needed to be on the master branch.
