### ISSUE TITLE
[Feat]: Improve detection of cpu details

### ISSUE THREAD

**Issue by cpipilas** [netdata/netdata#12291]
### Problem

CPU frequency on some nodes may not be properly detected:

![0hz](https://user-images.githubusercontent.com/30462769/156366810-b05391e5-fd74-45b1-b0f0-15bbd3375ff0.png)

### Description

There are cases with machines/containers in which CPU frequency is not properly detected. For example on a mac:

```
mac-3:sbin copi$ /usr/local/netdata/usr/libexec/netdata/plugins.d/system-info.sh
....
NETDATA_SYSTEM_CPU_LOGICAL_CPU_COUNT=unknown
NETDATA_SYSTEM_CPU_VENDOR=unknown
NETDATA_SYSTEM_CPU_MODEL=unknown
NETDATA_SYSTEM_CPU_FREQ=unknown
NETDATA_SYSTEM_CPU_DETECTION=none
....
```

### Importance

nice to have

### Value proposition

- Improve clarity in cloud/single node view

**Comment by cpipilas** [comment]
cc @MrZammler

**Comment by Ferroin** [comment]
At least for Linux, there are some cases we simply can’t get this info.

On Linux, we have three possible mechanisms for finding the CPU frequency, and all of them can fail:

* The `lscpu` command, which may or may not be installed, and cannot always get the CPU frequency itself.
* The `dmidecode` command, which may or may not be installed, only works if run on actual hardware (not guaranteed to work in VMs, and does not work in containers), only supports some CPU architectures (POWER hardware, for example, does not have DMI tables for the command to look at), and may not actually provide the requisite information (this is dependent on the BIOS/UEFI vendor).
* Scanning files under `/sys/devices/system/cpu/cpu0/cpufreq`, which requires read access to said files (not guaranteed on a well secured system), as well as requiring the kernel to actually have a working CPUFreq driver loaded and running.

---

On the macOS side of things, we appear to have determined that this is an issue of permissions WRT the commands we try to run.

**Comment by ilyam8** [comment]
This issue will be closed automatically when #12293 is merged. It fixes your specific problem @cpipilas (x86_64 macOS). If this issue is supposed to fix a more general problem - let me know.

**Comment by iigorkarpov** [comment]
`sysctl -n machdep.cpu.brand_string | awk '{print $NF}'`

**Comment by ilyam8** [comment]
@iigorkarpov why the problem? We use `sysctl -n hw.cpufrequency` for Darwin/x86_64.

**Comment by iigorkarpov** [comment]
@ilyam8 I read `system-info.sh` _after_ my first answer, sorry. And yes, the script works for me. Need a case when it does not.
