### ISSUE TITLE
[Bug]: Netdata node connection issue MacOS

### ISSUE THREAD

**Issue by DShreve2** [netdata/netdata#12301]
### Bug description

Trying to connect my Mac for Product training using the Mac script. Receiving the attached error:

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues

### Expected behavior

A connected node.

### Steps to reproduce

1. Copy the MacOS install script from Netdata Cloud.
2. Paste in terminal
3. Execute
...

### Installation method

kickstart.sh

### System info

```shell
Darwin Ds-MacBook-Pro.attlocal.net 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
```

### Netdata build info

```shell
n.a.
```

**Comment by ilyam8** [comment]
Hi, @DShreve2. Can you show the whole output? Also, if you need just to install it (and not install specifically from the source), consider using [brew](https://formulae.brew.sh/formula/netdata).

**Comment by cpipilas** [comment]
A lot of fixes have been introduced since Mar, please comment if the problem still exists.
