### ISSUE TITLE
[Feat]: How to open .ndf files and .njf and .snapshot files

### ISSUE THREAD

**Issue by mingtianshi** [netdata/netdata#12328]
### Problem

How to open .ndf files and .njf and .snapshot files？

### Description

i don't know,How do they open

### Importance

nice to have

### Value proposition

1.
2.
3.
...

**Comment by stelfrag** [comment]
Hi @mingtianshi 

The .ndf and .njf files are used by the agent to store the collected metrics and related index to those metrics respectively. You can not use / open them directly. 

The .snapshot file can be viewed by selecting ![image](https://user-images.githubusercontent.com/52996999/157196730-f1910a98-702d-4e73-93a1-077e6e8ebf23.png) on the agent dashboard

**Comment by mingtianshi** [comment]
so how do i use ndf and .njf

**Comment by stelfrag** [comment]
> so how do i use ndf and .njf

You don't use them directly, the agent uses those internally to store metrics
