### ISSUE TITLE
[Bug]: Alert email for a child re-directs to the parent

### ISSUE THREAD

**Issue by dimko** [netdata/netdata#12376]
### Bug description

**Preconditions:**
- 2 nodes in a parent/child setup
- Child streams data through the parent
- alert configuration for the child lives on the parent
- alert is raised for the child in the parent
- smtp settings are configured in parent so it can send emails for alerts

When a user clicks the Go To Chart CTA button inside the alert email for an alert raised for the child, she gets re-directed to parent's url instead of the childs.

Email re-direct is using machine guid, referenced as agentId and it seems to be using the parent's machine guid instead of the child's

### Expected behavior

User should be re-directed to child's dashboard, to the affected by the alert chart

### Steps to reproduce

1. Setup a parent and a child streaming through the parent
2. Setup proper smtp settings in parent so it can send emails for alerts
3. Trigger an alert for the child in the parent
4.  Access user's email and follow the Go To Chart CTA inside the email for the raised alert

### Installation method

docker

### System info

```shell
/etc/alpine-release:3.15.0
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.15.0
/etc/os-release:PRETTY_NAME="Alpine Linux v3.15"
```

### Netdata build info

```shell
Version: netdata v1.33.1-140-gd5baf4ca5
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--with-bundled-libJudy' '--disable-ebpf' 'CFLAGS=' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

**Comment by dimko** [comment]
Affects https://github.com/netdata/cloud-frontend/issues/2955

**Comment by MrZammler** [comment]
Ok, indeed it doesn't work correctly.

I have a parent (**(6am) f34bed50-af44-11ec-af72-0c3796231cc3**) and a child (**(raspberrypi) 4266cdbe-af46-11ec-910b-e45f01241614**) both unclaimed.

When I get an alert from the parent for the child, the parent constructs this url:

`https://app.netdata.cloud/alarms/redirect?agentId=f34bed50-af44-11ec-af72-0c3796231cc3&host=raspberrypi&chart=system.ram&family=ram&alarm=ram_in_use&alarm_unique_id=1648548297&alarm_id=1648548310&alarm_event_id=2&alarm_when=1648548373&alarm_status=WARNING&alarm_chart=system.ram&alarm_value=39.3%25`

The agentId there is for the parent. Clicking this will get me to the cloud where I'm redirected to this url: 

`http://192.168.0.54:19999/#top;nowelcome=1;host=raspberrypi;chart=system.ram;family=ram;alarm=ram_in_use;alarm_unique_id=1648548297;alarm_id=1648548310;alarm_event_id=2;alarm_when=1648548373;alarm_status=WARNING;alarm_chart=system.ram;alarm_value=39.3%25`

Which when clicked will get me to the parent, on chart system.ram, etc.

If the first link had contained the agentId of the child, the redirect would be:

`http://192.168.0.54:19999/host/raspberrypi/#top;nowelcome=1;host=raspberrypi;chart=system.ram;family=ram;alarm=ram_in_use;alarm_unique_id=1648548297;alarm_id=1648548310;alarm_event_id=2;alarm_when=1648548373;alarm_status=WARNING;alarm_chart=system.ram;alarm_value=39.3%25`

And that would take me to the child dashboard (through the parent of course, 192.168.0.54 is the parent).

The machine guid is picked up by the `alarm-notify.sh` script here: https://github.com/netdata/netdata/blob/8edef126a6cbf8cd7f3e4731b4b53bb71627b376/health/notifications/alarm-notify.sh.in#L2298-L2315

So, I guess 2 solutions, but it needs the cloud's assistance and input (cc @jacekkolasa ):

1) Pass the child's GUID to the script and build the link with that one. Not sure how it will affect the cloud when the parent is claimed.
2) Cloud to create the correct link by always adding `/host/HOSTNAME` to the link. This should work even for the parent. (i.e. `http://192.168.0.54:19999/api/v1/info` == `http://192.168.0.54:19999/host/6am/api/v1/info`)

**Comment by jacekkolasa** [comment]
@MrZammler I think we need to have the child's GUID anyway, especially in those cases where we redirect to the Cloud (AFAIK we cannot identify using hostname in the Cloud).

Could we maybe have `agentId` for a child, but also, have for example `parentId` represent parent guid? This way, if we cannot find the child in visited-nodes api, we could try navigating to parent via /host url. Having both ids would allow us to quickly modify behaviour of redirect, if needed.

**Comment by MrZammler** [comment]
Ok, we could try this. We could add a `childId` (and leave `agentId` as is to represent the parent, so that the change would be cleaner) ?

**Comment by MrZammler** [comment]
@jacekkolasa I've posted a small change to the agent's notification in https://github.com/netdata/netdata/pull/12609, and we can discuss/test when you have time.

However, I'm a bit confused on how exactly this whole thing works, even if past tests revealed the problem, today I can't get a redirect (and makes sense since my test new agent was never claimed to the cloud - how does it know how to redirect? registry?). Perhaps sometime in the following days we could check it out. Thanks!

**Comment by jacekkolasa** [comment]
@MrZammler if your agent hadn't been claimed to the cloud, you could still get the redirect using the cloud's registry. Iframes save every agent when you visit it while being signed-in to the cloud. So the next time you'll get notifications, it checks agentId<->visitedUrl pair and, if it's found, redirects (or at least shows the list of urls so you can redirect manually).

Maybe you didn't fulfill this criteria before testing? (You hadn't visited your agent while being signed in to the cloud)
List of visited urls can be accessed with https://staging.netdata.cloud/api/v1/accounts/{acountID}/nodes/{agentID}

accountID is taken from /accounts/me
