### ISSUE TITLE
[Bug]: ci triggers publishing a new nightly release if no commits have been made

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#12389]
### Bug description

- ci bumps the version.
- ci triggers publishing a new nightly release if no commits have been made.

This issue was [fixed for Travis](https://github.com/netdata/netdata/issues/10298) but was not taken into account during the transition to GHA (or there is a bug 🤷‍♂️).

### Expected behavior

No nightly release if no commits have been made.

### Steps to reproduce

Check commits/nightly packages.

### Installation method

other

### System info

```shell
n/a
```

### Netdata build info

```shell
n/a
```

**Comment by Ferroin** [comment]
Actually, it never got properly implemented in Travis, see: https://github.com/netdata/netdata/pull/11486.

This _is_ something we want though, it’s just not an especially high priority right now.
