### ISSUE TITLE
[Bug]: netdatacli limits the message size

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#12396]
### Bug description

netdatacli has limit for output size of 4096

### Expected behavior

do we just increase this limit or make it transfer arbitrary message sizes?

**Comment by Ferroin** [comment]
I would vote for arbitrary message sizes, we should be future-proofing this if at all possible.

**Comment by cpipilas** [comment]
@underhood what is the latest status on this?

**Comment by underhood** [comment]
@cpipilas this is a relatively small issue, it was not picked up due to what I perceive to be higher prio. things (now for example fixing the mqtt5 problem from yesterday)
it is just a matter of planning, also a good beginner-friendly issue

**Comment by underhood** [comment]
In general, it is problem only for bigger parents and `netdatacli aclk-state` command which is to my knowledge the only one which can produce longer output (and only in case there are a lot of children). This same data can be received also by `/api/v1/aclk-state` endpoint.

For those reasons, I consider it a low priority.

**Comment by ckcckk** [comment]
@underhood Is there anyone working on this issue？If not，may I have a try？

**Comment by underhood** [comment]
@ckcckk Hi, i have it on my backlog but have not yet got to it (did just short look at it and then was interrupted by higher prio stuff). Currently working on the h2o webserver integration. Sure you can have a go at it :)

**Comment by ckcckk** [comment]
@underhood Thanks for your reply, I will deal with this issue next.

**Comment by deekshithpranav** [comment]
Hey @underhood, I am new to the project and if the issue is still unsolved I would really like to give it a go to actually start my open-source journey. Can you assign the to me?

**Comment by jphwang212** [comment]
> I would vote for arbitrary message sizes, we should be future-proofing this if at all possible.

By future-proofing, would getting the system limits like max argument size be a solution?
