### ISSUE TITLE
[Feat]: When ACLK is not connected, it should state when it will reconnect

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12409]
### Problem

When a node is not online, `aclk-state` should indicate when it will be the next time to reconnect:

```sh
# /opt/netdata/bin/netdatacli aclk-state
ACLK Available: Yes
ACLK Version: 2
Protocols Supported: Legacy, Protobuf
Protocol Used: Legacy
Claimed: Yes
Claimed Id: fdb94188-9730-11ec-aab7-dca632bb8656
Cloud URL: https://app.netdata.cloud
Online: No
Reconnect count: 69
```

Also, it would be useful to state:

1. The time it was last connected
2. The time it last attempted to connect and
3. The reason of the last disconnection or last failed connection attempt

Something like:

```sh
# /opt/netdata/bin/netdatacli aclk-state
ACLK Available: Yes
ACLK Version: 2
Protocols Supported: Legacy, Protobuf
Protocol Used: Legacy
Claimed: Yes
Claimed Id: fdb94188-9730-11ec-aab7-dca632bb8656
Cloud URL: https://app.netdata.cloud
Online: No
Reconnect count: 69

Last Connection: DATETIME
Last Disconnection: DATETIME
Last Disconnection Message: connection refused | disconnected from cloud | other error

Reconnection exponential backoff: DURATION
Next Connection Attempt: DATETIME
```

### Description

As above.

### Importance

must have

### Value proposition

Users should have visibility on cloud connection attempts and failures

### Proposed implementation

As above

**Comment by ktsaou** [comment]
@underhood

**Comment by ktsaou** [comment]
Also, does `Reconnect count` include connection attempts?
It does not seem to...

**Comment by underhood** [comment]
> Also, does `Reconnect count` include connection attempts? It does not seem to...

I considered `reconnect count` to mean naturally `MIN( (successful_connections_to_cloud - 1) , 0)` and that is exactly how is it implemented.

**Comment by ktsaou** [comment]
ok. @underhood we need however to provide more transparency. The way it is now, users cannot tell when their nodes will reconnect.

**Comment by underhood** [comment]
https://github.com/netdata/netdata/pull/12458 implements most of it except the reason for the last connection failure -> reason we currently don't have a single place/variable where we decide this. We log it always but in code, it is all over the place.

**Comment by underhood** [comment]
@ktsaou #12458 doesn't implement your point No.3 as that has some prerequisites to be done. I created https://github.com/netdata/netdata/issues/12480 so it doesn't get forgotten
