### ISSUE TITLE
[Bug]: timex plugin is cryptic

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12405]
### Bug description

On one of my servers, I have an alarm about `system_clock_sync_state` having `0 synchronization state`.

I tried to find what is happening. How this plugin finds out about it?

Nothing about it here:
![image](https://user-images.githubusercontent.com/2662304/158275543-d561f0f4-e683-4af8-9fc4-9982f3fe60f5.png)

Nothing about it here:
![image](https://user-images.githubusercontent.com/2662304/158275574-1d551eff-9c3b-4d83-a3b5-82e89fad8ee1.png)

At the documentation:
https://learn.netdata.cloud/docs/agent/collectors/timex.plugin
Nothing about the source of the data:
![image](https://user-images.githubusercontent.com/2662304/158275638-cfafaba3-3f6b-4dd5-9738-ed066a56a9ee.png)

At the forum about the alarm, also nothing about the source of data about this alarm:
![image](https://user-images.githubusercontent.com/2662304/158275669-72cd3f22-ae6e-44c3-98d1-a028f5a03616.png)

At the server, I see the clock is synced:

```sh
# timedatectl 
               Local time: Τρι 2022-03-15 01:03:03 EET
           Universal time: Δευ 2022-03-14 23:03:03 UTC
                 RTC time: Τρι 2022-03-15 01:02:39
                Time zone: Europe/Athens (EET, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: yes

Warning: The system is configured to read the RTC time in the local time zone.
         This mode cannot be fully supported. It will create various problems
         with time zone changes and daylight saving time adjustments. The RTC
         time is never updated, it relies on external facilities to maintain it.
         If at all possible, use RTC in UTC by calling
         'timedatectl set-local-rtc 0'.
```

### Expected behavior

1. Netdata should state where the timex.plugin collects its data
2. Netdata should provide enough information for the user to verify the information
3. Netdata should provide more information on why the alarm is raised
4. Netdata should provide more information on how the problem can be fixed

### Steps to reproduce

I am not sure. The alarm is raised on this server by itself.

### Installation method

from source

### System info

```shell
# uname -a; grep -HvE "^#|URL" /etc/*release
Linux costa-pc 5.16.11-2-MANJARO #1 SMP PREEMPT Fri Feb 25 11:27:31 UTC 2022 x86_64 GNU/Linux
/etc/arch-release:Manjaro Linux
/etc/lsb-release:DISTRIB_ID=ManjaroLinux
/etc/lsb-release:DISTRIB_RELEASE=21.2.4
/etc/lsb-release:DISTRIB_CODENAME=Qonos
/etc/lsb-release:DISTRIB_DESCRIPTION="Manjaro Linux"
/etc/manjaro-release:Manjaro Linux
/etc/os-release:NAME="Manjaro Linux"
/etc/os-release:ID=manjaro
/etc/os-release:ID_LIKE=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:PRETTY_NAME="Manjaro Linux"
/etc/os-release:ANSI_COLOR="32;1;24;144;200"
/etc/os-release:LOGO=manjarolinux
```

### Netdata build info

```shell
# netdata -W buildinfo
Version: netdata v1.33.1-151-gcda2fe06d
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O1 -ggdb' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by DanTheMediocre** [comment]
The timex plugin appears to only look at the return values of adjtimex(&timex{ }) in order to determine system_clock_sync_state, checking whether it is equal to the TIME_ERROR value or not. It seems the required information for why the alarm was raised and how it can be resolved would be part of the NTP info which already has the NTPD collector as part of the python.plugins orchestrator. Or am I missing something important here?

**Comment by ilyam8** [comment]
@DanTheMediocre it was indeed an sync issue because of 

> Warning: The system is configured to read the RTC time in the local time zone.
>         This mode cannot be fully supported. It will create various problems
>         with time zone changes and daylight saving time adjustments. The RTC
>         time is never updated, it relies on external facilities to maintain it.
>         If at all possible, use RTC in UTC by calling
>         'timedatectl set-local-rtc 0'.

**Comment by ktsaou** [comment]
Guys, this ticket is about adding proper information at dashboard_info.js

1. at `dashboard_info.js` to explain the source of the data.
   The current text is:
   
   > [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol) lets you automatically sync your system time with a remote server. This keeps your machine’s time accurate by syncing with servers that are known to have accurate times.
   > 
   > The system clock synchronization state. It is strongly recommended having the clock in sync with reliable NTP servers. Otherwise, it leads to unpredictable problems. It can take several minutes (usually up to 17) before NTP daemon selects a server to synchronize with.
   
   I think it should also state that: This information is provided by the `ntp_adjtime()` system call and reflects the status of the system kernel regarding clock synchronization.
   
2. The same addition should be made to the timex.plugin page at our documentation: https://learn.netdata.cloud/docs/agent/collectors/timex.plugin
   
3. The forum should also state it and it should also have a note that the following output of `timedatectl` may also trigger the netdata alert:
   
   > The system is configured to read the RTC time in the local time zone.
         This mode cannot be fully supported. It will create various problems
         with time zone changes and daylight saving time adjustments. The RTC
         time is never updated, it relies on external facilities to maintain it.
         If at all possible, use RTC in UTC by calling
         'timedatectl set-local-rtc 0'.
   
4. The description of the alarm should be changed from:
   
   > the system time is not synchronized to a reliable server
   
   to:
   
   > when set to 0, the system kernel believes the system time is out of sync
   
5. We may be able to get more details about the sync state. What is especially interesting is that the kernel can report a clock error (probably hardware related). @ilya knows more details.

**Comment by DanTheMediocre** [comment]
The collector could be checking against the status field of the timex struct instead of its return value? this contains all the different flags that currently would trigger an unsync alarm, and can distinguish between an unsynced clock and a hardware clock error.
I'm unsure that the timedatectl warning triggers the alert, it is a different check that tells us the same thing: there is a setting (local rtc) that causes the kernel to at some point have an unsynced clock, even without a hardware error. From what I understand from the function documentation this is rtc setting is not part of the information npt_adjtime provides

**Comment by DanTheMediocre** [comment]
I have made some adjustments to the dashboard, readme and alarm info wrt the info source and alarm description, would it okay to do a pull request for these @ilyam8?

**Comment by ilyam8** [comment]
Thanks for helping us to resolve this issue, @DanTheMediocre.

---

>  this contains all the different flags that currently would trigger an unsync alarm, and can distinguish between an unsynced clock and a hardware clock error.

I think we checked the flags and there are really only two possible cases (you mentioned both of them: unsynced clock, hardware clock error).

**Comment by DanTheMediocre** [comment]
those 2 cases would refer to whether the STA_UNSYNC or the STA_CLOCKERR flag is set, the current flag is a combination of those and the PPS flags. It is of course also possible to not report on the PPS flags though, but if the status mask is checked anyways why not include checks those potential error causes? But the easy solution is just to differentiate between unsync and clockerr

       TIME_ERROR
              The system clock is not synchronized to a reliable server.
              This value is returned when any of the following holds
              true:

              *  Either STA_UNSYNC or STA_CLOCKERR is set.

              *  STA_PPSSIGNAL is clear and either STA_PPSFREQ or
                 STA_PPSTIME is set.

              *  STA_PPSTIME and STA_PPSJITTER are both set.

              *  STA_PPSFREQ is set and either STA_PPSWANDER or
                 STA_PPSJITTER is set.

**Comment by ilyam8** [comment]
@tkatsoulas check 3 in https://github.com/netdata/netdata/issues/12405#issuecomment-1076218116
