### ISSUE TITLE
[Bug]: https://my-netdata.io/kickstart.sh checksum does not match documentation.

### ISSUE THREAD

**Issue by AreAArseth** [netdata/netdata#12439]
### Bug description

Reading https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart#verify-script-integrity I see a way to verify the installer:
[ "8ce9f7ab7250dd7c52a3ee4fe6ae0a5a" = "$(curl -Ss https://my-netdata.io/kickstart.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"
And it fails:
$ [ "8ce9f7ab7250dd7c52a3ee4fe6ae0a5a" = "$(curl -Ss https://my-netdata.io/kickstart.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"
FAILED, INVALID

### Expected behavior

That OK, VALID is returned.

### Steps to reproduce

1. Run [ "8ce9f7ab7250dd7c52a3ee4fe6ae0a5a" = "$(curl -Ss https://my-netdata.io/kickstart.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"
2. It fails.
3. Actual checksum returned is
$ curl -sS https://my-netdata.io/kickstart.sh |md5sum
78dc96482a9e6f30d534a1290fe16ab4  -
...
The file returned is:
[kickstart.sh.gz](https://github.com/netdata/netdata/files/8283493/kickstart.sh.gz)

### Installation method

kickstart.sh

### System info

```shell
Linux simsrv105.nordicsemi.no 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Mon Jan 17 07:06:06 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux"
/etc/os-release:VERSION="8.5 (Ootpa)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VERSION_ID="8.5"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8.5"
/etc/redhat-release:Red Hat Enterprise Linux release 8.5 (Ootpa)
/etc/system-release:Red Hat Enterprise Linux release 8.5 (Ootpa)
```

### Netdata build info

```shell
No install possible
```

**Comment by ilyam8** [comment]
Will be fixed by https://github.com/netdata/learn/pull/938

**Comment by ilyam8** [comment]
Hi, @AreAArseth. There is a delay between updating the kickstart.sh script and the actual page on our learn website.
