### ISSUE TITLE
[Bug]: libvirt VMs are monitored twice

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12434]
### Bug description

Every VM spawned by libvirt, now has 2 entries, one with the VM name and another with the VM name and `libvirt` appended.
The right one to monitor is the second one (with `libvirt`) and it is the one that also tracks disk and network.

![Peek 2022-03-16 20-30](https://user-images.githubusercontent.com/2662304/158661933-45ff1dc6-8b4a-4d4e-94be-2ca4e8a5fcd3.gif)

### Expected behavior

Only one cgroup instance should be reported for every libvirt VM.

### Steps to reproduce

CGroups unified tree has been disabled, by passing `systemd.unified_cgroup_hierarchy=0` to kernel boot parameters.

Then, start any VM with Virtual Machine Manager or `virsh`.

### Installation method

from source

### System info

```shell
# uname -a; grep -HvE "^#|URL" /etc/*release
Linux costa-xps9500 5.15.25-1-MANJARO #1 SMP PREEMPT Wed Feb 23 14:44:03 UTC 2022 x86_64 GNU/Linux
/etc/arch-release:Manjaro Linux
/etc/lsb-release:DISTRIB_ID=ManjaroLinux
/etc/lsb-release:DISTRIB_RELEASE=21.2.4
/etc/lsb-release:DISTRIB_CODENAME=Qonos
/etc/lsb-release:DISTRIB_DESCRIPTION="Manjaro Linux"
/etc/manjaro-release:Manjaro Linux
/etc/os-release:NAME="Manjaro Linux"
/etc/os-release:ID=manjaro
/etc/os-release:ID_LIKE=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:PRETTY_NAME="Manjaro Linux"
/etc/os-release:ANSI_COLOR="32;1;24;144;200"
/etc/os-release:LOGO=manjarolinux
```

### Netdata build info

```shell
# netdata -W buildinfo
Version: netdata v1.33.1-140-gd5baf4ca5
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O0 -ggdb' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

Here is a tree of the memory cgroup controller:

```sh
# tree -d /sys/fs/cgroup/memory
/sys/fs/cgroup/memory
├── dev-hugepages.mount
├── dev-mqueue.mount
├── docker
│   └── 197319f8f901ef8b464fbde84ddea54ce702be9c6736681a729dcbe28d6baa15
├── machine.slice
│   ├── machine-qemu\x2d5\x2dfreebsd12.3.scope
│   │   └── libvirt
│   └── machine-qemu\x2d8\x2dwin10.scope
│       └── libvirt
```

**Comment by ktsaou** [comment]
On this line:

https://github.com/netdata/netdata/blob/4dca6582bd42b2ffc954c6e35bce0f3bc65e1ef4/collectors/cgroups.plugin/sys_fs_cgroup.c#L406

It should say:

```
      " !*/libvirt "
```

(an asterisk is missing).

But, using the setup, on non-unified cgroups tree, the cgroup does not have any disk I/O reported.
The problem is that we need to parse the `blkio*_recursive` files too, and add a new family called `disk recursive`.

This will allow the above change to function properly on both unified and non-unified cgroups trees.

Also the recursive blkio files, will allow netdata to monitor properly even recursive containers.

In the unified hirerachy, all blkio are recursive. There are no non-recursive versions of them.

Generally, all cgroups resources are supposed to be recursive. CPU is, memory is. It seems that blkio accidentaly was not recursive and kernel developers decided to add the `*recursive` files to have the same feature as all other resources, while maintaining backwards compatibility.

So, the `cgroups.plugin` should either:

1. Parse both non-recursive and recursive blkio files
   or
2. Prefer the recursive versions when they are available

BTW, `cgroup-network` cannot associate network interfaces with the `.scope/libvirt` versions of the cgroups under the unified hierarchy. However it works for both `.scope` and `.scope/libvirt` in non-unified cgroups.

**Comment by ilyam8** [comment]
I am in favor of 

> Prefer the recursive versions when they are available and report them as disk

A note: the fix is only for Cgroups v1.

**Comment by ktsaou** [comment]
> I am in favor of
> 
> > Prefer the recursive versions when they are available and report them as disk

Me too.

**Comment by ilyam8** [comment]
Hi, @ktsaou. Can you test #12462?

**Comment by ktsaou** [comment]
Thanks. It works!
