### ISSUE TITLE
[Feat]: Collect VM information from cloud providers as part of system-info.sh

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12432]
### Problem

Instance type & availability zone are important information to be collected from cloud providers.

Depending on the cloud provider, there may be CLI tools we can use to get this information.

### Description

In netdata cloud, I would like to see the type of VM each node is.

### Importance

must have

### Value proposition

Cloud provider node information defines the quality of the virtual hardware provided. So, although the CPU architecture is important for bare-metal nodes, for virtual nodes the instance type is the most important parameter.

**Comment by PanosJee** [comment]
By having the instance type could find some more metadata (network interface max speed, storage type) by looking up in some public [datasets](https://instances.vantage.sh/).

**Comment by Ferroin** [comment]
We can, for most providers, do a `whois` lookup on the external IP to ID the provider, though this won’t always work. This could actually be done in the Cloud itself directly, and would probably be more efficient than having the agent do the lookup (but OTOH would not work for child nodes).

Beyond that though it’s complicated to reliably fetch this info.

* AWS EC2 provides a metadata API this information can be tretrieved from.
* AWS Lightsail does not appear to provide any such functionality.
* GCP GCE provides a metadata API which is different from that provided by AWS EC2 that appears to provide this information, though I’m not certain if it does or not from reading their documentation.
* Azure provides a metadata API  which is also different from that provided by AWS EC2 that may provide this information, but it is not immediately obvious from the documentation whether it does or does not.
* Digital Ocean provides it’s own metadata API, but it doesn’t provide the required info. We would have to take the droplet ID from this data and then look it up via the user’s account on DO to ID the instance type, which is not realistic.
* Vultr is essentially the same as DO, but with yet another different API.
* Linode appears to lack any such functionality.

It’s important to note that we need API handling _per provider_. There is a standard ‘well-known’ IPv4 SLAAC address for retrieving this type of data, but the exact API it provides is _not_ standardized, and differs by provider.

**Comment by PanosJee** [comment]
AWS has a couple of ways for an instance to expose it's metadata that is easily queryable from within either via an HTTP call or CLI

- [URI](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html)
- [CLI](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-discovery.html)

**Comment by Ferroin** [comment]
@PanosJee If that also works for Lightsail instances and not just EC2, that would be great, but we still have to remember that every cloud provider is different here. This isn’t some ‘one-and-done’ type thing unless we look at it solely as a set of multiple requests on a per-provider basis.

**Comment by PanosJee** [comment]
Yes indeed but just covering AWS for starters is a big enough market to
give some very useful dataset.

**Comment by Ferroin** [comment]
Indeed. I’ll look into adding this for AWS at some point later today. We’ll probably just use the URI approach since we can count on having `curl` or `wget` but not necessarily the AWS CLI tools.

Depending on how involved it is, I will probably also look at doing the same for GCP.
