### ISSUE TITLE
[Bug]: agent does not propagate the right chart and dimension liveness to cloud

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12443]
### Bug description

There are many cases:

1. Charts being live on the agent, but not live at the cloud
2. Charts being obsolete on the agent, but live at the cloud

The way this works now, the cloud is out of sync on charts and dimensions, presenting either incomplete or wrong information about the charts that are available on the cloud.

This is a critical issue, that deserves first priority resolution, as it makes the cloud unusable.

### Expected behavior

Charts and dimensions should always be in-sync with cloud

### Steps to reproduce

1. Start and stop containers and VMs. The cloud table of contents gets bigger and bigger.
2. Start containers and while they run, reboot the machine. After agent restart, charts on the cloud persist although the charts are not there any more.
3. Combine the 2 above (so, have some old charts, reboot, start the containers again) to get into charts being live at the agent, but not live at the cloud.

### Installation method

kickstart.sh

### System info

```shell
N/A
```

### Netdata build info

```shell
# netdata -W buildinfo
Version: netdata v1.33.1-187-g4dca6582b
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O0 -ggdb' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

Related to:

* https://github.com/netdata/cloud-frontend/issues/3030
* https://github.com/netdata/netdata/discussions/12358

@stelfrag @papazach @ilyam8 @dimko

**Comment by ktsaou** [comment]
@ralphm the answer to your missing charts.

**Comment by ralphm** [comment]
I am not sure this is the same case. In my node, I don't have containers, some of the basic charts are missing, and also what I see in cloud is a strict subset of what the agent has.

**Comment by stelfrag** [comment]
@papazach please check

I observe that for a parent / child setup 
- Parent starts (3043d49c-53c3-41b3-a9ba-9c50dc662626)
- A child previously connected is offline (node 447f21d2-c4a9-42f9-9be9-2f4c876921ee)
- Parent reports that this child is not live (live=0, queryable=1)
  - Shouldn't this "mark" that everything related to that node is not live ?
     - The `last_entry` for charts for this node is updating as if it was actively collected
- The parent does not receive "Start streaming charts" for this node
   -  Please confirm. We do not send start streaming to the agent if the node is reported with `live = 0` ?
      -  This prevents the parent from sending any updates regarding the dimensions of the node and doing cleanup

**Comment by papazach** [comment]
> Shouldn't this "mark" that everything related to that node is not live ?

Sorry I quite did not get that. The only thing that we do when we are informed that a node instance is not live, is to update its liveness state in a table where we keep such informational fields about all node instances and that's it.

Do you mean that in such case we should go ahead and update all NULL last_entries of all dimensions and charts with the current timestamp?

> We do not send start streaming to the agent if the node is reported with live = 0

Correct, we do NOT send `StreamChartsAndDimensions` commands to node instances that have `liveness: false`

**Comment by stelfrag** [comment]
> Correct, we do NOT send `StreamChartsAndDimensions` commands to node instances that have `liveness: false`

As discussed, we need this so a parent can send the necessary information to allow the cloud can do a cleanup of charts/dimensions.

**Comment by papazach** [comment]
> > Correct, we do NOT send `StreamChartsAndDimensions` commands to node instances that have `liveness: false`
> 
> As discussed, we need this so a parent can send the necessary information to allow the cloud can do a cleanup of charts/dimensions.

Ok, I'll perform the change and release it really soon.
The only thing that I am not sure about @stelfrag is whether this should be the only change that the Cloud should perform, or not.

Should we also do this? 

> ... we should go ahead and update all NULL last_entries of all dimensions and charts with the current timestamp?

**Comment by stelfrag** [comment]
> ... we should go ahead and update all NULL last_entries of all dimensions and charts with the current timestamp?

This will be tricky, because if the node goes live, you will not receive "active" dimensions again because that was the last state transmitted (agent will generate an identical payload and figure out you already have it)

I think this should be done more efficiently. This is because a parent starting will always "announce" children as "live=false" if the children are not yet connected (but eventually do) [_sure when the parent starts children will connect  faster than the aclk connection is established but that's not always the case_ ]

Keeping the info at the node level (node is live=false at a specific timestamp) and then use that info to override on the fly chart/dimension last_entry as needed for incoming (for example FE or other queries) queries could be more optimal (but you know best :smiley: )

**Comment by papazach** [comment]
>Keeping the info at the node level (node is live=false at a specific timestamp) and then use that info to override on the fly chart/dimension last_entry as needed for incoming (for example FE or other queries) queries could be more optimal (but you know best 😃 )

Noted yes it should be much better performance-wise. 

I will create the tickets to perform those changes and ping you to re-test your scenarios right after.

cc @juacker @TonyPath

**Comment by hugovalente-pm** [comment]
This relates to the stale charts existing bug netdata/product#2771

**Comment by ktsaou** [comment]
Guys, this is critical for the cloud to cleanup chart states. Implementing the tasks mentioned here will greatly improve the stability and reliabity of the cloud.

I think this also happens on childs. Obsolete charts do show up as current. Do you want me to find such cases?

**Comment by hugovalente-pm** [comment]
one of the tasks has already been completed by last week netdata/cloud-backend#79 by @juacker and the remaining one has been started by @papazach netdata/cloud-backend#80, hopefully this week we'll be able to test and confirm if these are the fix or something unknow is there

**Comment by papazach** [comment]
Both be tasks have been merged and released to production, if they were the only dependency of this ticket I suppose we can close this as well.

**Comment by ktsaou** [comment]
Great to see this is done. You rock guys!
