### ISSUE TITLE
[Bug]: cgroup network interface charts should have context cgroups.*

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12453]
### Bug description

Network interfaces belonging to cgroups, are detected via `cgroup-network` and renamed to the cgroup category.

During this renaming, netdata changes `id`, `name`, `family` and `priority`.

`context` should also be changed from `net.*` to `cgroup.net_*`. So:

1. `net.net` should become `cgroup.net_net`
2. `net.carrier` should become `cgroup.net_carrier`
3. `net.mtu` should become `cgroup.net_mtu`
4. `net.operstate` should become `cgroup.net_operstate`
5. `net.packets` should become `cgroup.net_packets`
6. `net.drops` should become `cgroup.net_drops`
7. etc

This means that network interface alarms for cgroups will now be different.

### Expected behavior

The way it is today (maintaining the `net.*` context) introduces 2 problems in netdata cloud:

1. In the overview dashboard cgroup network interfaces disappear from the cgroups section and appear in the network section
2. In the overview dashboard, the network interfaces get random order of charts, because of the mixed priorities that charts of the same context are having.

### Steps to reproduce

Run a couple of VMs or containers and visit the overview dashboard on netdata cloud.

### Installation method

from source

### System info

```shell
N/A
```

### Netdata build info

```shell
# netdata -v
netdata v1.33.1-187-g4dca6582b
```

**Comment by ilyam8** [comment]
@ktsaou you can test #12454, it is a draft because I haven't added alarms, but the network charts context is fixed.

```cmd
git clone --recursive https://github.com/ilyam8/netdata --branch=fix_cgroup_net_context nd_ilyam_fix_cgroup_net_context
cd nd_ilyam_fix_cgroup_net_context
./netdata-intaller.sh ...

```

**Comment by ktsaou** [comment]
It works! Let's merge it!

**Comment by ilyam8** [comment]
I need to update:
 - health (add alarms)
 - the charts info (dashboard_info.s)
