### ISSUE TITLE
[BUG] Cant remove stale/non working nodes via webui or kicakstart script

### ISSUE THREAD

**Issue by MikeJakubik** [netdata/netdata#12472]
Hi,

I have a node that changed hostnames, ever since then I've been unable to get it running in the Cloud webui (there is no option to remove it). I tried deleting /var/dn/netdata/cloud.d and passing a new UUID only to get this error.

Connection attempt 1 successful
Failed to claim node with the following error message:"invalid node id"

Nothing is being reported in the error log but the webui shows the node as unreachable.

This is on FreeBSD 13 using the port version 1.33.1.

Thanks.

**Comment by cpipilas** [comment]
Nodes can now be properly removed from Netdata Cloud
