### ISSUE TITLE
[Bug]: several freeipmi plugin problems

### ISSUE THREAD

**Issue by atriwidada** [netdata/netdata#12485]
### Bug description

1. Debugging steps explained in collectors/freeipmi.plugin/README.md does not work on default install. 
2. Package dependency for netdata-plugin-freeipmi need to include libipmimonitoring6.

### Expected behavior

$ sudo su -s /bin/sh netdata
$ /usr/libexec/netdata/plugins.d/freeipmi.plugin 20 debug 

(should runs fine ...)

### Steps to reproduce

On a clean system with netdata already installed and local IPMI access ready (kernel modules etc).
1.  sudo apt install netdata-plugin-freeipmi
2. sudo su -s /bin/sh netdata
3. /usr/libexec/netdata/plugins.d/freeipmi.plugin 20 debug 

will result
sh: 2: /usr/libexec/netdata/plugins.d/freeipmi.plugin: Permission denied

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux vmlab 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
$ netdata -W buildinfo
Version: netdata v1.33.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

solution to (1): change group ownership of /usr/libexec/netdata/plugins.d/freeipmi.plugin to netdata
solution to (2): add libipmimonitoring6 to contrib/debian/control, netdata-plugin-freeipmi package

capture of my session:

$ sudo apt install netdata-plugin-freeipmi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  freeipmi freeipmi-bmc-watchdog freeipmi-ipmidetect freeipmi-tools libipmiconsole2 libipmidetect0
The following NEW packages will be installed:
  freeipmi freeipmi-bmc-watchdog freeipmi-ipmidetect freeipmi-tools libipmiconsole2 libipmidetect0 netdata-plugin-freeipmi
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
...

$ sudo ipmimonitoring
Caching SDR repository information: /root/.freeipmi/sdr-cache/sdr-cache-vmlab.localhost
Caching SDR record 71 of 71 (current record ID 71) 
ID | Name             | Type                                | State    | Reading    | Units | Event
1  | Ambient Temp     | Temperature                         | Nominal  | 28.00      | C     | 'OK'
2  | Planar 3.3V      | Voltage                             | Nominal  | 3.32       | V     | 'OK'
3  | Planar 5V        | Voltage                             | Nominal  | 5.06       | V     | 'OK'
4  | Planar 12V       | Voltage                             | Nominal  | 12.15      | V     | 'OK'
5  | Planar VBAT      | Voltage                             | Nominal  | 3.14       | V     | 'OK'
6  | Fan 1 Tach       | Fan                                 | Nominal  | 9372.00    | RPM   | 'OK'
7  | Fan 2 Tach       | Fan                                 | Nominal  | 8875.00    | RPM   | 'OK'
...

$ sudo su -s /bin/sh netdata
$ id
uid=999(netdata) gid=999(netdata) groups=999(netdata),4(adm),13(proxy),133(docker)

$ /usr/libexec/netdata/plugins.d/freeipmi.plugin 20 debug           
sh: 2: /usr/libexec/netdata/plugins.d/freeipmi.plugin: Permission denied

$ exit
$ sudo ls -l /usr/libexec/netdata/plugins.d/freeipmi.plugin
-rwsr-x--- 1 root root 487008 Feb 15 00:47 /usr/libexec/netdata/plugins.d/freeipmi.plugin
$ sudo chgrp netdata /usr/libexec/netdata/plugins.d/freeipmi.plugin
$ sudo ls -l /usr/libexec/netdata/plugins.d/freeipmi.plugin
-rwxr-x--- 1 root netdata 487008 Feb 15 00:47 /usr/libexec/netdata/plugins.d/freeipmi.plugin
$ sudo chmod u+s /usr/libexec/netdata/plugins.d/freeipmi.plugin
$ sudo ls -l /usr/libexec/netdata/plugins.d/freeipmi.plugin
-rwsr-x--- 1 root netdata 487008 Feb 15 00:47 /usr/libexec/netdata/plugins.d/freeipmi.plugin
$ sudo su -s /bin/sh netdata
$ /usr/libexec/netdata/plugins.d/freeipmi.plugin 20 debug 
/usr/libexec/netdata/plugins.d/freeipmi.plugin: error while loading shared libraries: libipmimonitoring.so.6: cannot open shared object file: No such file or directory
$ 

$ sudo apt install libipmimonitoring6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libipmimonitoring6
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.

...

$ sudo su -s /bin/sh netdata
$ /usr/libexec/netdata/plugins.d/freeipmi.plugin 20 debug 

( ... works fine now ...)

**Comment by Ferroin** [comment]
On further inspection, we are probably not setting the correct permissions on the freeipmi plugin on install, which in turn would cause the issues described with debugging.

**Comment by juliokele** [comment]
Still not working with netdata-plugin-freeipmi 1.38.1 package (owner+permission problem)

workaround:
```
chown root:netdata /usr/libexec/netdata/plugins.d/freeipmi.plugin
chmod 4750 /usr/libexec/netdata/plugins.d/freeipmi.plugin
```

**Comment by 8465231** [comment]
This issues still exsists, just tried installing the ipmi plugin twice on brand new ubuntu 20.04 installs and both times it fails to work.

Looked into it and sure enough it seems to be a permissions issue.

-rwsr-x--- 1 root root 745K Feb 25 18:20 /usr/libexec/netdata/plugins.d/freeipmi.plugin

Also if I try to run it in debug mode as the netdata user I get a permission denied error.

Is there a way to manually fix the permissions? Will I have to reinstall the system again to get it working? About to put this server into production and really need to get this setup before then.

**Comment by 8465231** [comment]
to make things stranger I install everything exactly the same way a week ago on another system but it worked on that one.

**Comment by juliokele** [comment]
> This issues still exsists, just tried installing the ipmi plugin twice on brand new ubuntu 20.04 installs and both times it fails to work.
> 
> Looked into it and sure enough it seems to be a permissions issue.
> 
> -rwsr-x--- 1 root root 745K Feb 25 18:20 /usr/libexec/netdata/plugins.d/freeipmi.plugin
> 
> Also if I try to run it in debug mode as the netdata user I get a permission denied error.
> 
> I tried changing the sgid and while netdata could then run it, it gave this error
> 
> ```
> freeipmi.plugin: calling _init_ipmi_config()
> freeipmi.plugin: calling ipmi_monitoring_init()
> freeipmi.plugin: detecting IPMI minimum update frequency...
> freeipmi.plugin: checking data collection speed iteration 1 of 10
> (ipmi_monitoring_ipmi_communication.c, _inband_init, 145): ipmi_ctx_find_inband: success
> 2023-02-26 14:59:30: freeipmi.plugin ERROR : MAIN : ipmi_monitoring_sensor_readings_by_record_id(): internal system error (errno 9, Bad file descriptor)
> 2023-02-26 14:59:30: freeipmi.plugin FATAL : freeipmi.plugin : freeipmi.plugin: data collection failed. # : Success
> 
> /usr/libexec/netdata/plugins.d/freeipmi.plugin(+0x34621)[0x557ddab40621]
> /usr/libexec/netdata/plugins.d/freeipmi.plugin(+0xd94a)[0x557ddab1994a]
> /usr/libexec/netdata/plugins.d/freeipmi.plugin(+0xb967)[0x557ddab17967]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fe06ff45083]
> /usr/libexec/netdata/plugins.d/freeipmi.plugin(+0xca7e)[0x557ddab18a7e]
> ```
> 
> ipmimonitoring works fine when run as root.
> 
> Is there a way to manually fix the permissions? Will I have to reinstall the system again to get it working? About to put this server into production and really need to get this setup before then.

same problem hier with netdata-plugin-freeipmi v1.38.1

my permissions/ownership workaround:
```
chown root:netdata /usr/libexec/netdata/plugins.d/freeipmi.plugin
chmod 4750 /usr/libexec/netdata/plugins.d/freeipmi.plugin
```

**Comment by 8465231** [comment]
> same problem here with netdata-plugin-freeipmi v1.38.1
> 
> my permissions/ownership workaround:
> 
> ```
> chown root:netdata /usr/libexec/netdata/plugins.d/freeipmi.plugin
> chmod 4750 /usr/libexec/netdata/plugins.d/freeipmi.plugin
> ```

It worked! Thanks!
