### ISSUE TITLE
[Bug]: //usr/libexec/netdata/netdata-updater.sh: 56: 3: Bad file descriptor WARNING  Failed to enable auto updates. Netdata will still work, but you will need to update manually.

### ISSUE THREAD

**Issue by EnesPalit** [netdata/netdata#12490]
### Bug description

When installing Netdata I got this output and error:

```
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
OK
 
//usr/libexec/netdata/netdata-updater.sh: 56: 3: Bad file descriptor
WARNING  Failed to enable auto updates. Netdata will still work, but you will need to update manually.
```

I tried uninstalling and reinstalling but it stays the same. Also tried stable and nightly but no difference.

Netdata works but because of that error/warning I can't add claim it to my room:

```
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token jRYjCfChwe5x-ToWOrwcyBXuDDVytiwoFMBfhkjeZI_jMRDeDgcwwghzMQeHa-6JxBf-z5qZVH__GjDpdz-lz99tlD3YdUvP0h8qSyG9dsetyaB_biDX05Iut1ZqM3OslRos --claim-rooms edd524ef-j5bb-4b6b-b51b-49da73f1b756 --claim-url https://app.netdata.cloud
--2022-03-22 19:20:36--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 2a06:98c1:3121::8, 2a06:98c1:3120::8, 188.114.97.8, ...
Connecting to my-netdata.io (my-netdata.io)|2a06:98c1:3121::8|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

/tmp/netdata-kickstart.sh                           [ <=>                                                                                                 ]  55.20K  --.-KB/s    in 0.001s

2022-03-22 19:20:36 (63.8 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [56523]


 --- Using /tmp/netdata-kickstart-TRJvMnGNe0 as a temporary directory. ---
 --- Checking for existing installations of Netdata... ---
 --- Found an existing netdata install at /, with installation type 'binpkg-deb'. ---
[/tmp/netdata-kickstart-TRJvMnGNe0]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron
//usr/libexec/netdata/netdata-updater.sh: 56: 3: Bad file descriptor
 FAILED

 ABORTED  Failed to update existing Netdata install at /
```

### Expected behavior

That it installs without any errors/warnings.

### Steps to reproduce

`wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel`

`wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token jRYjCfChwe5x-ToWOrwcyBXuDDVytiwoFMBfhkjeZI_jMRDeDgcwwghzMQeHa-6JxBf-z5qZVH__GjDpdz-lz99tlD3YdUvP0h8qSyG9dsetyaB_biDX05Iut1ZqM3OslRos --claim-rooms edd524ef-j5bb-4b6b-b51b-49da73f1b756 --claim-url https://app.netdata.cloud`

### Installation method

kickstart.sh

### System info

```shell
Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.33.1-195-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by Ferroin** [comment]
Bug in the updater, should only affect installs that would use native packages, working on a fix.

**Comment by andresg747** [comment]
Hello!
I see it's been fixed within #12491 now merged to master.
How can I target that specific version?

I'm getting this error running:
`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

thanks in adv

**Comment by Ferroin** [comment]
Correction, looks like GitHub Actions is still not fully recovered at this point, so it looks like it will probably be tomorrow (nightlies normally get triggered around 00:00 UTC each day, and the relevant parts are generally published by 02:00 UTC).

**Comment by sergioadofaci** [comment]
Hello,

I think we have to wait for the next build to run successfully : https://github.com/netdata/netdata/actions/runs/2031479078

**Comment by EnesPalit** [comment]
Just tried this again `wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh`
But doing `netdata -W buildinfo`
Still returns same version: `Version: netdata v1.33.1-195-nightly`
How do I get the latest fixed nightly build?

**Comment by doublescotch** [comment]
Hello, iv have tried installing netdata a few minutes ago, and issue is still there,  im getting  `Version: netdata v1.33.1-195-nightly`
after a `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
and my netdata-updater.sh dont work

The update should be uploaded tomorow?
Thanks

**Comment by ilyam8** [comment]
@EnesPalit @doublescotch there is a bug in our release workflow - nightly Debian packages haven't been published. The fix is #12522.

**Comment by doublescotch** [comment]
Hi, update worked, but something like half for me, as i need to laucnh` wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh` trought a `sudo -i` opening, if i do regular sudo i will have an error about cron creation, and if i do whitout sudo, i will have  more error ( but the https://learn.netdata.cloud/docs/agent/packaging/installer/ say to run the wget "as normal user" so i guess i shouldnt have to laucnh it trought sudo?)

and when i succeed the install whitout error from `sudo -i` console, if i try to relaunch the process to try  netdata-updater.sh, i get the previous error again :

```
 OK 

Sun 27 Mar 2022 17:43:38 ACDT : INFO:  Auto-updating has been ENABLED through cron, updater script linked to /etc/cron.daily/netdata-updater

Sun 27 Mar 2022 17:43:38 ACDT : INFO:  If the update process fails and you have email notifications set up correctly for cron on this system, you should receive an email notification of the failure.
Sun 27 Mar 2022 17:43:38 ACDT : INFO:  Successful updates will not send an email.


root@rootkit:~# wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
--2022-03-27 17:43:49--  https://my-netdata.io/kickstart.sh
Résolution de my-netdata.io (my-netdata.io)… 104.21.13.159, 172.67.156.192, 2606:4700:3036::ac43:9cc0, ...
Connexion à my-netdata.io (my-netdata.io)|104.21.13.159|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : non indiqué [application/octet-stream]
Enregistre : «/tmp/netdata-kickstart.sh»

/tmp/netdata-kickstart.sh         [ <=>                                            ]  55.12K  --.-KB/s    ds 0.008s  

2022-03-27 17:43:49 (6.42 MB/s) - «/tmp/netdata-kickstart.sh» enregistré [56443]


 --- Using /tmp/netdata-kickstart-tHYJYMS0xF as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- Found an existing netdata install at /, with installation type 'binpkg-deb'. --- 
[/tmp/netdata-kickstart-tHYJYMS0xF]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron 
Sun 27 Mar 2022 17:43:50 ACDT : ERROR:  FAILED TO UPDATE NETDATA : You are running this script as user with uid 0. We recommend to run this script as root (user with uid 0)
 FAILED 

 ABORTED  Failed to update existing Netdata install at /

root@rootkit:~# 
```

so the error is asking me to launch the script throught root user with uid 0, but im launching it with root user and uid 0 ?
iv tried it on a ubuntu 20.04 lts fresh install, on vm

**Comment by doublescotch** [comment]
this is the error im getting at the end of installation, abour cron permission :
```
ln: impossible de créer le lien symbolique '/etc/cron.daily/netdata-updater': Permission non accordée
 WARNING  Failed to enable auto updates. Netdata will still work, but you will need to update manually.
```
so i try to launch the updater mannualy : 
```
$ cd /usr/libexec/netdata
$ sudo ./netdata-updater.sdh
```
its reporting me : 
`Sun 27 Mar 2022 19:58:36 ACDT : ERROR:  FAILED TO UPDATE NETDATA : You are running this script as user with uid 0. We recommend to run this script as root (user with uid 0)`
the same as when i launch all the process from a `sudo -i`

**Comment by doublescotch** [comment]
as a temporary solution for me, isnt there any way to add the cloud connect token whitout using the updater? like a command that just set the token whitout using netdata-updater.sh?

or maybe an option at the fresh install with kickstart, by including the token directly at the installation?

**Comment by ilyam8** [comment]
@doublescotch you are right, there is another bug 🙈 - deb packages (I guess rpm too) have no `/etc/netdata/.environment` file which contains some needed info for the updater. I will open a new issue.

**Comment by doublescotch** [comment]
oh okay thanks i will wait so, i was sure that i was messing with my permissions somewhere, i have even tried to launch the updater trought the netdata user created by kickstart, but no way haha

this product seems really awesome and powerfull, sad to discover it just at the moment you cant do the full install to try its full potential ^^

last question, if i choose to use it just trought 19999 for now, is there a clean unninstaller script for that i will be able to remove and reinstall when the bug will be corrected? Because for now i have only tried on a test vm, not on my server

i ask this because when you run `wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh` with a netdata already installed,  the script will try to launch updater instead of doing the whole kickstart again, but actually the updater is broken for me, so its mean i will not beeing able to get the corrected version and connect my cloud...

So i will have to unnistall all before being able to kickstart again?

**Comment by ilyam8** [comment]
@doublescotch you can upgrade using "sudo apt-get update && sudo apt-get upgrade"

**Comment by doublescotch** [comment]
oh okay sorry, i didnt thought this will work for netdata 
thanks

**Comment by doublescotch** [comment]
I dont know if there is a link with this `/etc/netdata/.environment` issue, ui is working, but after the first hardware reboot after fresh installation, my netdata ui page become stuck on the first grey background with netdata writted in white when trying to open it, and then if i reload the page again, the port dosnt answer anymore
If i do an apt remove and then install, it will work again, until i reboot just one time and then stuck on background then no answer again

**Comment by ilyam8** [comment]
@doublescotch there are several bugs, I've found 2 so far, the fixes: #12524 (fix netdata-updater.sh on Debian/Ubuntu), #12526 (fix enabling auto-updates when using kickstart.sh)

**Comment by ilyam8** [comment]
I created 2 issues:
 - #12525
 - #12527

**Comment by EnesPalit** [comment]
The fix let me install netdata but when I try to clain it gives me another error in [12531](https://github.com/netdata/netdata/issues/12531)

**Comment by doublescotch** [comment]
All is fixed for me, i have updated and succeed to install my cloud token today,
Thanks all
