### ISSUE TITLE
[Feat]: add new chart for timex.plugin synchronization fault source

### ISSUE THREAD

**Issue by DanTheMediocre** [netdata/netdata#12500]
### Problem

Looking at the timex plugin for issue #12405, it is apparent that a system_clock_sync_state value of 0 is the result of return value TIME_ERROR by the ntp_adjtime(&timex{}) function (https://man7.org/linux/man-pages/man2/adjtimex.2.html).

This TIME_ERROR can be caused by 2 distinct sources, a synchronization fault or a hardware clock fault, which can be checked by verifying in the timex struct whether the status field has flagged STA_UNSYNC or STA_CLOCKERR

It would be useful to know which of the flags is raised to provide some more information, and to be able to view this on the dashboard in addition to system_clock_sync_state

### Description

A new chart alongside system.clock_sync_state and system.clock_sync_offset as part of the timex plugin that provides the clock synchronisation fault source, identifying if STA_UNSYNC and/or STA_CLOCKERR is set.

### Importance

nice to have

### Value proposition

1. Provides an additional metric using an existing collector from information that is already present
2. Allows to more easily identify and resolve the source of an unsynced system clock

### Proposed implementation

Check the timex_buf.status field in the current plugin for the STA_UNSYNC and STA_CLOCKERR flag
Create an additional metric for timex.plugin that identifies whether either or both flags are set 
Create a new chart for the dashboard to display the new metric. 
If either value is set the current system_clock_sync_state will already raise an alarm, so no additional health checks should be needed.

**Comment by ilyam8** [comment]
Thanks for the detailed feature request, @DanTheMediocre.

**Comment by DanTheMediocre** [comment]
Thank you for such a swift pickup of the issue, was gonna learn how to properly add to the collector and dash as an exercise this morning when I saw you already had a good PR

**Comment by ilyam8** [comment]
@DanTheMediocre see my comment in the PR about additional cases when we can get TIME_ERROR. I haven't checked it properly, but the quick checking of the Linux src code showed that we can be interested in other time_status bits too. If you are interested in this topic you can investigate and do a PR that adds needed status bits dimensions to the "System Clock Status" chart.

**Comment by DanTheMediocre** [comment]
the other options are for additional Pulse-Per-Second synchronisation that improves the accuracy of the NTP down to a couple microseconds, but this is from what I can tell not really that commonly used. The actual TIME_ERROR flag is encoded as
(STA_UNSYNC|STA_CLOCKERR) | (STA_PPSTIME & (STA_PPSJITTER | !STA_PPSSIGNAL)) | (STA_PPSFREQ & (STA_PPSWANDER | !STA_PPSSIGNAL)
Or in plain speak, the other reason for an error flag is PPS is enabled with either a period or a frequency pulse, and the signal is lost or there is jitter flag wrt period or a wander flag wrt frequency. 
https://doc.ntp.org/archives/4.1.1/pps/
I don't really think this is much of an added benefit to most Netdata users (and if that were the case it is probably better suited to the NTPD plugin than the timex)

**Comment by ilyam8** [comment]
> I don't really think this is much of an added benefit to most Netdata users

Perhaps you are right.

TIME_ERROR occurs when:

1. **loss of synchronization**: either STA_UNSYNC or STA_CLOCKERR is set.
2. **loss of PPS signal**: STA_PPSFREQ or STA_PPSTIME is set and STA_PPSSIGNAL is clear.
3. **jitter exceeded**: both STA_PPSTIME and STA_PPSJITTER are set.
4. **wander exceeded**: STA_PPSFREQ is set and either STA_PPSWANDER or STA_PPSERROR is set.

I don't have enough knowledge/experience to say if 2-4 are worth to be monitored.
