### ISSUE TITLE
[Bug]: cannot update my macos node installation

### ISSUE THREAD

**Issue by gfay63** [netdata/netdata#12515]
### Bug description

On my macos node, even though I have auto-update enabled, it is not updating. 

And when I try to update manually, it crashes. The result of:

`curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh`

is the following:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 56443    0 56443    0     0   282k      0 --:--:-- --:--:-- --:--:--  293k

 --- Using /var/folders/y3/hsh81nzs1r35v9ylm6b778wm0000gn/T/netdata-kickstart-XXXXXXXXXX.wG8xBojM as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- Found an existing netdata install at /usr/local/netdata, with installation type 'kickstart-build'. --- 
[/var/folders/y3/hsh81nzs1r35v9ylm6b778wm0000gn/T/netdata-kickstart-XXXXXXXXXX.wG8xBojM]$ sudo /usr/local/netdata/usr/libexec/netdata/netdata-updater.sh --not-running-from-cron 
Thu Mar 24 16:08:15 CDT 2022 : INFO:  Checking if a newer version of the updater script is available.
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
/usr/local/netdata/usr/libexec/netdata/netdata-updater.sh: line 393: [: : integer expression expected
Thu Mar 24 16:08:15 CDT 2022 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Thu Mar 24 16:08:15 CDT 2022 : INFO:  Fetching dependency handling script...
/usr/local/netdata/usr/libexec/netdata/netdata-updater.sh: line 331: /install-required-packages.sh: Read-only file system
Thu Mar 24 16:08:15 CDT 2022 : ERROR:  FAILED TO UPDATE NETDATA : Cannot download https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh
 FAILED 

 ABORTED  Failed to update existing Netdata install at /usr/local/netdata
```

### Expected behavior

Expect the update to complete and update my macos node both automatically via auto-update, or manually via the kickstart.sh script.

### Steps to reproduce

1. Starting with my macos node properly installed and functioning well.
2. Per the local dashboard, I am being notified that "A new version of netdata is available!" => It is not updating automatically.
3. Try a manual update via `curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh` => Fails with the result above.

### Installation method

kickstart.sh

### System info

```shell
Darwin IronmanMacPro2.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```

### Netdata build info

```shell
Version: netdata v1.33.1-151-nightly
Configure options:  '--prefix=/usr/local/netdata/usr' '--sysconfdir=/usr/local/netdata/etc' '--localstatedir=/usr/local/netdata/var' '--libexecdir=/usr/local/netdata/usr/libexec' '--libdir=/usr/local/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--with-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS= -I/usr/local/opt/openssl@1.1/include -I/usr/local/include' 'LDFLAGS= -L/usr/local/opt/openssl@1.1/lib -L/usr/local/lib'
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    NO
    cgroup Network Tracking: NO
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

This originally came from a different issue #12383.

**Comment by Ferroin** [comment]
Looks like at least two bugs:

- An issue (possibly two) in the code that checks for a newer version of the updater script (specifically the `newer_commit_date` function). This is largely harmless, it just means that any fixes here on GitHub won’t be used until Netdata itself is updated. You can silence that particular part of the error output by just running the updater script directly with with `sudo /usr/local/netdata/usr/libexec/netdata/netdata-updater.sh --updater-no-self-update --not-running-from-cron`.
- An almost certainly unrelated issue with our handling of pulling in any new build dependencies, which appears to be what’s actually causing things to fail here. You can (probably) work around this by ensuring that `TMPDIR` is set to a writable temporary directory (`/tmp` _should_ work on macOS, but I’m not 100% certain on that) in the environment when you run the command.

**Comment by gfay63** [comment]
Not having much luck. If I echo $TMPDIR, it is set to:

`/var/folders/y3/hsh81nzs1r35v9ylm6b778wm0000gn/T/`

and looking at the errors above, that is exactly the path that the script is failing on.

After doing some research, this $TMPDIR weirdness is what the macOS evidently does normally. And my understanding is that this is so that the system creates folders within it with the proper privs, and I should not modify it.

As for /tmp on macos, it is a symlink to /private/tmp.

Here are all the privs:
```
IronmanMacPro2:netdata gfay$ /usr/bin/stat -F $TMPDIR /tmp /private/tmp
drwx------ 257 gfay staff 8224 Mar 29 16:03:24 2022 /var/folders/y3/hsh81nzs1r35v9ylm6b778wm0000gn/T//
lrwxr-xr-x 1 root wheel 11 Feb  6 15:22:11 2022 /tmp@ -> private/tmp
drwxrwxrwt 31 root wheel 992 Mar 29 16:03:01 2022 /private/tmp/
```

I did try setting TMPDIR to a full priv location:

```
IronmanMacPro2:~ gfay$ /usr/bin/stat -F $TMPDIR 
drwxrwxrwx 2 gfay staff 64 Mar 29 15:45:46 2022 /Users/gregfay/tmp/
```

...however, get the same errors. It appears the script is launching another shell so the TMPDIR is getting reset? Note the temporary directory it is trying to use:

```
IronmanMacPro2:~ gfay$ curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 56465    0 56465    0     0   117k      0 --:--:-- --:--:-- --:--:--  119k

 --- Using /var/folders/y3/hsh81nzs1r35v9ylm6b778wm0000gn/T/netdata-kickstart-XXXXXXXXXX.O7XyB7Ie as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- Found an existing netdata install at /usr/local/netdata, with installation type 'kickstart-build'. --- 
[/var/folders/y3/hsh81nzs1r35v9ylm6b778wm0000gn/T/netdata-kickstart-XXXXXXXXXX.O7XyB7Ie]$ sudo /usr/local/netdata/usr/libexec/netdata/netdata-updater.sh --not-running-from-cron 
Tue Mar 29 15:54:25 CDT 2022 : INFO:  Checking if a newer version of the updater script is available.
Tue Mar 29 15:54:26 CDT 2022 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Tue Mar 29 15:54:26 CDT 2022 : INFO:  Fetching dependency handling script...
/usr/local/netdata/usr/libexec/netdata/netdata-updater.sh: line 311: /install-required-packages.sh: Read-only file system
Tue Mar 29 15:54:26 CDT 2022 : ERROR:  FAILED TO UPDATE NETDATA : Cannot download https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh
 FAILED 

 ABORTED  Failed to update existing Netdata install at /usr/local/netdata
```

Ran again with sudo, and the same thing.

As for part 1 of your response, running `sudo /usr/local/netdata/usr/libexec/netdata/netdata-updater.sh --updater-no-self-update --not-running-from-cron` is a little different output but still fails as you'd expect:

```
IronmanMacPro2:~ gfay$ sudo /usr/local/netdata/usr/libexec/netdata/netdata-updater.sh --updater-no-self-update --not-running-from-cron
Password:
Tue Mar 29 16:13:00 CDT 2022 : INFO:  Checking if a newer version of the updater script is available.
Tue Mar 29 16:13:00 CDT 2022 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Tue Mar 29 16:13:00 CDT 2022 : INFO:  Fetching dependency handling script...
/usr/local/netdata/usr/libexec/netdata/netdata-updater.sh: line 311: /install-required-packages.sh: Read-only file system
Tue Mar 29 16:13:00 CDT 2022 : ERROR:  FAILED TO UPDATE NETDATA : Cannot download https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh
```

**Comment by Ferroin** [comment]
@gfay63 If you want to help with testing the copy from the PR, you can download it from https://raw.githubusercontent.com/Ferroin/netdata/updater-tmpdir-fix/packaging/installer/netdata-updater.sh.

It would need to be run with `sudo` using the same options I mentioned above: `--updater-no-self-update --not-running-from-cron`. The PR itself only fixes the TMPDIR thing though, because I’ve been unable to reproduce the issue with the code checking for a newer copy of the updater script, and therefore can’t really figure out what’s going wrong there.

That said, I suspect you will still see it running into the issue you outline in #12516, though at least it will get that far instead of choking on the TMPDIR thing.

**Comment by gfay63** [comment]
@Ferroin Thank you so much! That truly means a lot. I think your product is amazing so am determined to make it work, even though macos won't be a huge part of my platform later on...just is now for dev. 

Testing that PR copy now...

**Comment by gfay63** [comment]
@Ferroin It is completed! But right, it still was not able to launch due to that other issue. 

Oddly, there isn't even anything in the logs as though it didn't even "try" to launch?

There is one error at the very end. Not sure if important, but here is the final output:

```
 --- is installed now! --- 
  enjoy real-time performance and health monitoring...

sed: 1: "/usr/local/netdata/etc/ ...": extra characters at the end of l command
Wed Mar 30 08:20:40 CDT 2022 : INFO:  Updating tarball checksum info
```

...and here is the full dump in case anything in there of interest:

[netdata updater fix PR test run 3-30-22.txt](https://github.com/netdata/netdata/files/8380868/netdata.updater.fix.PR.test.run.3-30-22.txt)
