### ISSUE TITLE
macos reinstall/uninstall flows of kickstart script not correcting/removing LaunchDaemons plist file

### ISSUE THREAD

**Issue by gfay63** [netdata/netdata#12513]
> One other presumably side note, but FYI: The re-install and install scripts are not replacing the plist file for launching the service upon mac reboot. It still had the old location to the custom directory (from my first install attempt) in it. But I assume that only was affecting the issue of it launching upon reboot. FYI though that the scrips need to be corrected for this as well.

_Originally posted by @gfay63 in https://github.com/netdata/netdata/issues/12383#issuecomment-1066201482_

**Comment by ilyam8** [comment]
Hi, @gfay63. Thanks for creating the issue, but could you re-create it [using the bug report template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2Cneeds+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+)? Thanks in advance.

**Comment by gfay63** [comment]
> Hi, @gfay63. Thanks for creating the issue, but could you re-create it [using the bug report template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2Cneeds+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+)? Thanks in advance.

Ah, gotcha. Will do.

**Comment by gfay63** [comment]
@ilyam8 Quick question. Sry, but how do I do that and properly reference the other issue? When I click on "Reference in new issue" from the original one, it just provides a simple quote reply dialog without the bug report template. I need to do for several so wanted to make sure I'm doing right so the new ones have the context...

![image](https://user-images.githubusercontent.com/4573115/160001006-8b6c5d2c-13ff-4094-b2ad-9d1576916dcc.png)

**Comment by ilyam8** [comment]
@gfay63 you just use [the bug report template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2Cneeds+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+) (click on the link). And you can mention the issue in the "Bug description" section.

**Comment by gfay63** [comment]
resubmitted bug with template
