### ISSUE TITLE
[Bug]: macos reinstall/uninstall flows of kickstart script not correcting/removing LaunchDaemons plist file

### ISSUE THREAD

**Issue by gfay63** [netdata/netdata#12514]
### Bug description

On macos, the kickstart script is not addressing the LaunchDaemons in either the uninstall or reinstall flows.

### Expected behavior

In the case of Uninstall: Should **remove** the LaunchDaemons com.github.netdata plist file.

In the case of Re-install: Should **update** the LaunchDaemons com.github.netdata plist file.

### Steps to reproduce

1. Installed a new node on macos via kickstart to a custom path.
2. Had issues, so tried a re-install, but to the default path.
3. Still had issues, so tried a complete uninstall/re-install
In both cases above, the list file remained pointing to the old custom path from step 1.

### Installation method

kickstart.sh

### System info

```shell
Darwin IronmanMacPro2.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```

### Netdata build info

```shell
Version: netdata v1.33.1-150-nightly
Configure options:  '--prefix=/usr/local/netdata/usr' '--sysconfdir=/usr/local/netdata/etc' '--localstatedir=/usr/local/netdata/var' '--libexecdir=/usr/local/netdata/usr/libexec' '--libdir=/usr/local/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--with-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS= -I/usr/local/opt/openssl@1.1/include -I/usr/local/include' 'LDFLAGS= -L/usr/local/opt/openssl@1.1/lib -L/usr/local/lib'
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    NO
    cgroup Network Tracking: NO
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

FYI that the netdata build info above was from the second install.

This issue arose while trying to solve issue #12383

**Comment by gfay63** [comment]
Just FYI that a subsequent uninstall again did leave the orphaned `com.github.netdata` plist file in place, pointing to the non-existent path `/usr/local/netdata/usr/sbin/netdata`

**Comment by Ferroin** [comment]
The reinstall case here _should_ end up fixed by https://github.com/netdata/netdata/pull/13451.

The uninstall case will need more work, but should be relatively easy to fix.
