### ISSUE TITLE
[Bug]: Where is v1.33.1 release?

### ISSUE THREAD

**Issue by metajiji** [netdata/netdata#12523]
### Bug description

The latest release is v1.33.1, but github think what latest release v1.33.0.
![image](https://user-images.githubusercontent.com/3463175/160268963-66e363c1-a3d8-4647-80b6-69c8ef104fa2.png)

Meanwhile direct link is still available https://github.com/netdata/netdata/releases/tag/v1.33.1

Also github badges show latest release is v1.33.0
![image](https://user-images.githubusercontent.com/3463175/160269000-b97a3c84-26e8-40ec-acc8-f5579afea562.png)

### Expected behavior

Latest release v1.33.1

### Steps to reproduce

1. Open github project page https://github.com/netdata/netdata

### Installation method

other

### System info

```shell
na
```

### Netdata build info

```shell
na
```

**Comment by maneamarius** [comment]
This is resolved now.
