### ISSUE TITLE
[Feat]: Migrate ovpn_status_log to go.d.plugin with support for status version 2 and 3

### ISSUE THREAD

**Issue by surajnpn** [netdata/netdata#12541]
### Problem

openvpn_status_log collector written in python.d plugin doesn't work with newer openvpn versions

### Description

Currently, openvpn_status_log collector is a part of python.d plugin which hasn't been updated for long time. This collector only supports `status-version` 1. Newer openvpn by default use `status-version` 2. Supporting version 2 is a big chunk of work, and at this point migrating/rewriting the whole collector in go.d.plugin with support for status-version 2/3 is more suitable.

We need to cover:

- [ ] --status-version 1.
- [ ] --status-version 2.
- [ ] --status-version 3.
- [ ] [pre-shared keys case](https://github.com/netdata/netdata/issues/2075) (`--status-version` parameter doesn't affect the format).

### Importance

must have

### Value proposition

1. support for status-version 2 which is default in newer openvpn servers
2. migration of unmaintained python.d.plugin collectors to go.d.plugin

**Comment by ilyam8** [comment]
@surajnpn so we have 4 different variants:

- `--status-version 1`.
- `--status-version 2`.
- `--status-version 3`.
- [pre-shared keys case](https://github.com/netdata/netdata/issues/2075) (`--status-version` parameter doesn't affect the format).

**Comment by surajnpn** [comment]
Some samples from linux @ilyam8 

**Version 2** with connected client:
```
TITLE,OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar 22 2022
TIME,2022-03-31 11:47:46,1648716466
HEADER,CLIENT_LIST,Common Name,Real Address,Virtual Address,Virtual IPv6 Address,Bytes Received,Bytes Sent,Connected Since,Connected Since (time_t),Username,Client ID,Peer ID,Data Channel Cipher
CLIENT_LIST,gofle,x.x.x.x:59523,10.8.0.2,,19265,261631,2022-03-31 11:47:34,1648716454,UNDEF,10,0,AES-128-GCM
HEADER,ROUTING_TABLE,Virtual Address,Common Name,Real Address,Last Ref,Last Ref (time_t)
ROUTING_TABLE,10.8.0.2,gofle,x.x.x.x:59523,2022-03-31 11:47:37,1648716457
GLOBAL_STATS,Max bcast/mcast queue length,1
END
```
**without connected client**
```
TITLE,OpenVPN 2.5.5 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar 22 2022
TIME,2022-03-31 11:49:55,1648716595
HEADER,CLIENT_LIST,Common Name,Real Address,Virtual Address,Virtual IPv6 Address,Bytes Received,Bytes Sent,Connected Since,Connected Since (time_t),Username,Client ID,Peer ID,Data Channel Cipher
HEADER,ROUTING_TABLE,Virtual Address,Common Name,Real Address,Last Ref,Last Ref (time_t)
GLOBAL_STATS,Max bcast/mcast queue length,1
END
```

**Comment by ilyam8** [comment]
@surajnpn why skipping v1? 🤔

**Comment by surajnpn** [comment]
v1 is already implemented, just following the existing example for that. In addition to support for v2/v3 status log, I will implement separate charts per user with individual traffic in/out dimensions. The python collector for openvpn just compiles total user and total bandwidth and creates 2 charts. The go.d collector for openvpn(the one that uses management interface instead of status log), however creates separate charts per user. I think it is good addon to openvpn_status_log collector too.
