### ISSUE TITLE
[Feat]: add collecting CPU throttling statistics to cgroups.plugin

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#12595]
### Problem

Not possible to see if a container's CPU gets throttled. See netdata/netdata-cloud#375.

### Description

The idea is to track containers' CPU throttling enforced by the [CFS-Cgroup bandwidth control mechanism](https://www.kernel.org/doc/html/latest/scheduler/sched-bwc.html).

### Importance

must have

### Value proposition

1. This enhancement will allow identifying excessively (CPU) throttled applications.

#### cgroups v1

We need to read the `cpuacct/cpu.stat` file. Its content:

```cmd
nr_periods 7
nr_throttled 2
throttled_time 127918677
```

- `nr_throttled`
  > number of period intervals (as specified in `cpu.cfs_period_us`) that have elapsed.
- `nr_throttled`
  > number of times tasks in a cgroup have been throttled (that is, not allowed to run because they have exhausted all of the available time as specified by their quota).
- `throttled_time`
  >  the total time duration (in nanoseconds) for which tasks in a cgroup have been throttled.

#### cgroups v2

The same file name, but the content is different

```cmd
usage_usec 73899
user_usec 27213
system_usec 46685
nr_periods 7
nr_throttled 3
throttled_usec 139381
```

---

**We need the following charts**:
 - The percentage of runnable periods when tasks in a cgroup have been throttled.
 - The total time duration for which tasks in a cgroup have been throttled.

**Comment by lukasmrtvy** [comment]
@ilyam8 Hey, I am trying this change on Fedora CoreOS 36.20221029.20.1 ( Podman 4.3.0, Kernel 6.0.5, Nedata 1.36.1 ) with cgroups v2 enabled, but graphs for `CPU Throttled Runnable Periods` and  `CPU Throttled Time Duration` are 0 in both cases.
The problem is that container is actually throttled:

```
podman exec youthful_almeida cat /sys/fs/cgroup/cpu.stat
usage_usec 24714116
user_usec 18259227
system_usec 6454888
core_sched.force_idle_usec 0
nr_periods 110
nr_throttled 110
throttled_usec 79284667
nr_bursts 0
burst_usec 0
```

**Comment by ilyam8** [comment]
Hi, @lukasmrtvy. You have very small throttling counters. These counters only accumulate over time and never decrease. The throttling charts show the per-second rate. No increase - 0 values expected. The container you show is not really throttled.
