### ISSUE TITLE
[Bug]: Reviewdog in pipeline does not show filename

### ISSUE THREAD

**Issue by xrgman** [netdata/netdata#12597]
### Bug description

When I submitted my pull-request I noticed that one of the automatic checks failed to complete, the ESLint check. When looking deeper into the issue, I saw that this was because of the complexity of some JavaScript functions. The error does however **Not** show me which file the error occurs in, leaving me to guess where to find the error.

I think it would be better to alter the output of these errors to include the filename. 
These errors can be found [here](https://github.com/netdata/netdata/runs/5733071414?check_suite_focus=true).
See the screenshot below for an example error message:

![image](https://user-images.githubusercontent.com/913334/161496862-aac839c2-421a-4123-a4f0-37a37ad61a6a.png)

### Expected behavior

Filename to be in the error message

### Steps to reproduce

1. Create a pull-request that changes some big JavaScript file, like main.js
2. Look at the error log from the ESLint job.

### Installation method

from git

### System info

```shell
-
```

### Netdata build info

```shell
-
```

**Comment by xrgman** [comment]
@ilyam8 Yes! I already had a screenshot ready. Forgot to include it in the issue description.

**Comment by ilyam8** [comment]
@xrgman you can see the warnings here https://github.com/netdata/netdata/pull/12546/files (just scroll down through the changed files)

**Comment by ilyam8** [comment]
@xrgman I think it is supposed to work like that. I guess this can be tuned by changing the [reporter](https://github.com/reviewdog/action-eslint#reporter) parameter

https://github.com/netdata/netdata/blob/feb2b193dbbf044fc89120b17371699a67190ab7/.github/workflows/review.yml#L107

but not sure we need that. cc @netdata/agent-sre
