### ISSUE TITLE
[Bug]: User reports invalid timex alert

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#12604]
### Bug description

A user has reported in an interview that he started receiving alerts for `timex.conf`. He doesn't have NTP running, they're using something else instead. 

### Expected behavior

Don't assume that NTP is running, alert only if it is?

### Steps to reproduce

I suppose it's to
1. Disable NTP
2. Run Netdata

### Installation method

kickstart.sh

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

### Additional info

Will send the link to the user, so he can provide answers to any additional questions.

**Comment by ilyam8** [comment]
- We did some improvements to the alarm and corresponding chart description in #12495.
- We added the "System Clock Status" chart which provides the clock synchronization fault source in #12501.

We don't assume NTPd (or any other time sync daemon) running, but report whatever the system clock state is according to the kernel.

E.g. the problem in #12405 was that the system was configured to read the RTC time in the local time:

> Warning: The system is configured to read the RTC time in the local time zone.
         This mode cannot be fully supported. It will create various problems
         with time zone changes and daylight saving time adjustments. The RTC
         time is never updated, it relies on external facilities to maintain it.
         If at all possible, use RTC in UTC by calling
         'timedatectl set-local-rtc 0'.

**Comment by cakrit** [comment]
Closing based on this latest comment and as the user hasn't commented.

**Comment by powerman** [comment]
I've similar issue.
I don't use neither systemd nor ntpd.
It's a home workstation, so BIOS time is in local timezone, not UTC.
On boot my system executes `hwclock --hctosys --localtime`.
Every hour it runs `ntpdate -s -b -u $(dnsip {0,1,2,3}.gentoo.pool.ntp.org)`.
On shutdown it executes `hwclock --systohc --localtime --noadjfile`.
So, my clock is synchronized… why the alarm is active?

**Comment by ilyam8** [comment]
@powerman because the system clock is unsynchronized according to the kernel. If you sure it is false positive in your case you can disable the alarm using `enabled alarms`:

```
# netdata.conf
[health]
    enabled alarms = !system_clock_sync_state *
```

**Comment by powerman** [comment]
@ilyam8 Is there anything I can do to tell kernel clock is synchronized? How exactly you're checking for this?

**Comment by ilyam8** [comment]
See the [collector description](https://learn.netdata.cloud/docs/agent/collectors/timex.plugin) for more info.

And try `timedatectl`, do you get a warning message?

**Comment by ilyam8** [comment]
Ok, the chart description:

> The kernel code can operate in various modes and with various features enabled or disabled, as selected by the [ntp_adjtime()](https://man7.org/linux/man-pages/man2/adjtimex.2.html) system call. The system clock status shows the value of the time_status variable in the kernel. The bits of the variable are used to control these functions and record error conditions as they exist.

> UNSYNC - set/cleared by the caller to indicate clock unsynchronized (e.g., when no peers are reachable). This flag is usually controlled by an application program, but the operating system may also set it. CLOCKERR - set/cleared by the external hardware clock driver to indicate hardware fault.

The collector readme doesn't have all details, there is a link to [adjtimex](https://man7.org/linux/man-pages/man2/adjtimex.2.html). From the call man:

> The buf.status field is a bit mask that is used to set and/or retrieve status bits associated with the NTP implementation.

> STA_UNSYNC (read-write)
>    Clock unsynchronized.

Netdata checks for the `STA_UNSYNC` bit in buf.status after calling `adjtimex`.
