### ISSUE TITLE
[Feat]: ACLK flight recorder

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#12626]
### Description

Record the history of ACLK connections, their start/end, reason for disconnection and various major events of interest into SQLite DB.

Creates ID for every ACLK connection attempt and records events (both by their ID and as a log) into the DB. This way it is easy to query what happened with every connection in history (up to what we set as maximum history to keep - to not fill HDD)

Clean up too old DB records according to config.

Sending this to Cloud is not part of this Issue (interface/protocol TBD) but is prerequisite.

### Importance

really want

### Value proposition

1. Higher visibility of what happens with ACLK for users and developers alike
2. This will be shown in cloud in future
3. This will be accessible by agent local api+netdatacli in the future
...

**Comment by stelfrag** [comment]
Do we still need this (after aclk.log)?

**Comment by underhood** [comment]
superseded by cloud based event log
