### ISSUE TITLE
[Feat]: Report when Hard Drive(s) are in a read-only state

### ISSUE THREAD

**Issue by MatthewABrantley** [netdata/netdata#12628]
### Problem

As a netdata user,

It is possible that monitored nodes have their hard drives put into "Read-Only" mode, and then Netdata Agent+Cloud will have every individual chart in an error state for the node, but the node itself will not be in an "error state" in Netdata Cloud. This happens at least in Ubuntu as this is the default behavior for failing hard drives, it may occur in other cases. 

Picture attached for reference, 

![netdataROM-noerror](https://user-images.githubusercontent.com/20295023/162327561-46edc22e-2b3f-453d-914e-2cab3a31efa6.png)

### Description

When a node has a disk drive enter read-only mode, that information should be relayed in Netdata Cloud, probably flagged as a "red error"? 

Arguably, any drive, not just the root drive as in my case here. This may not be the universally correct though, as presumably someone could have purposefully put a drive in read-only mode. I think the root drive being "ro" can clearly be considered an issue. 

### Importance

nice to have

### Value proposition

The value proposition for this feature would be to allow users to quickly understand when their nodes have disk drives enter read-only mode. Especially in my specific case, with the root drive entering RO mode because of a failing disk drive, the entire node is non-functional, and ideally I would be notified of this so that I can get it replaced or repaired ASAP. 

### Proposed implementation

Even if the root drive is in this state, the read-only information can still be gathered from:

/proc/mounts

It can be parsed out of the drive info there, flagged as "ro", here is an example from a ubuntu server using LVM. 

/dev/mapper/ubuntu--vg-ubuntu--lv / ext4 ro,relatime,data=ordered 0 0

**Comment by thiagoftsm** [comment]
ping @cpipilas !

**Comment by cpipilas** [comment]
Thanks @Raltrwx!

**Comment by ilyam8** [comment]
Netdata needs to write data to storage for its operation. As read-only storage prevents this, Netdata cannot function or alert you of the problem.
