### ISSUE TITLE
[Feat]: Rename `--install` option for `kickstart.sh`.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#12659]
### Problem

The name `--install` is very generic, and does not actually describe what the option does very well.

### Description

The option should be renamed to a more descriptive name, such as `--install-prefix`.

### Importance

really want

### Value proposition

1. Less potential confusion from users as to what a given set of options for the script means.
2. We can internally reuse the `--install` name for other purposes.

### Proposed implementation

This should happen in two parts:

1. The first part should add the new option with the new name, and add a deprecation warning to the existing `--install` option.
2. The second part, to be merged a few months later, should remove the `--install` option.

**Comment by Ferroin** [comment]
Reopening this so that the second part does not get forgotten. Target date for that is currently 3 months from now (2022-08-03).

**Comment by iigorkarpov** [comment]
Is it YYYY-MM-DD?

**Comment by iigorkarpov** [comment]
My PR left non-merged. Should I remove it?

**Comment by maneamarius** [comment]
Sounds good, let's keep the ticket open until we implement the second part.

**Comment by Ferroin** [comment]
@DShreve2 We ideally should have a reminder about this in the release notes.

The PR to actually finish things here will probably not be ready before the release, but is likely to be ready and merged by mid August, so I’m thinking we should just remind users about the impending change.

**Comment by Dim-P** [comment]
@Ferroin what's the plan of action here?

I can see 3 possible solutions to eventually close this one:

1. Make a PR now to remove `--install` support in next week's release.
2. Add a final deprecation warning in the release notes of next week's release and remove `--install` one release after the next one.
3. Leave it as is and remove `--install` support when Netdata v2.0.0 gets released.

Thoughts?

**Comment by Ferroin** [comment]
I had originally been planning on option 2, but option 3 is probably the better approach. That said, if we’re still planning on the next release being 2.0, then options 2 and 3 are equivalent.
