### ISSUE TITLE
[Feat]: Disable cloud sign-in dialog

### ISSUE THREAD

**Issue by wolph** [netdata/netdata#12654]
### Problem

I've got multiple machines that I have netdata running on and multiple machines that I access netdata from and I'm getting really tired of seeing this dialog constantly. I'm already connected to the cloud but it keeps on asking me to sign-in.

Note that I don't want to disable the cloud support, I like it. It's just the dialog that's really annoying.

### Description

Add a setting to disable the "Sign-in to Netdata Cloud"

### Importance

really want

### Value proposition

1. It annoys the users less
2. It can help keep cloud adoption high (it seems that disabling cloud support is my only alternative right now)

### Proposed implementation

Similar to disabling the cloud entirely through `enabled = no`, it would be nice to have a `cloud_dialog = no` setting

**Comment by UltraBlackLinux** [comment]
I'd also like this. I don't need or want the login features but they pop up everywhere. If it shows me things I can't use why would it even show them?

**Comment by andrewm4894** [comment]
just to check - is it this box? 

![image](https://github.com/netdata/netdata/assets/2178292/a867cea3-90bd-44ca-94e0-f76d7b5a8130)

**Comment by andrewm4894** [comment]
Just asking as latest agent dashboard v2 should not have any popups like this afaik. its just the sign in button in corner now really.

![image](https://github.com/netdata/netdata/assets/2178292/61f3e4a5-c709-4a65-8e65-280a2820bcf1)

**Comment by UltraBlackLinux** [comment]
if you click on functions, you get a login popup
there is a sign in button 
the cog on the left is a sign-in feature

I just don't want buttons or UI elements that require a sign-in to function.

**Comment by andrewm4894** [comment]
@UltraBlackLinux is it this one? 

![image](https://github.com/netdata/netdata/assets/2178292/330a0d82-edcc-4aeb-9a47-1695aa3388ec)

im not sure we have any actual popups left (as in the annoying modal ones that block your use of the app like /v1 has) - but just want to be double sure im not missing anything. 

can you add some screenshots just so i can be sure of what ones you are talking about?

**Comment by ilyam8** [comment]
@andrewm4894 hey, @UltraBlackLinux is not OP and his complaint is "don't want buttons or UI elements that require a sign-in to function". I think this is _wontfix_, we do want to show things that will become available after connecting to Cloud.

**Comment by MrZammler** [comment]
Closing this as the original request was for V1, and as @ilyam8 said the second request is at the moment at least `wontfix`.
