### ISSUE TITLE
[Bug]: Netdata not following dbengine configuration after update

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#12666]
### Bug description

after upgrading netdata to latest stable version (1.33.1) using the update script, I see the below log in `systemctl status netdata`:
netdata[13512]: 2022-04-12 09:59:04: netdata INFO  : MAIN : Found 0 legacy dbengines, setting multidb diskspace to 256MB

But when I open `http://127.0.0.1:19999/netdata.conf`, I see my custom value (which is correct):
```
[global]
	memory mode = dbengine
	dbengine multihost disk space = 35000
	page cache size = 32
	update every = 10
```
if I do `systemctl restart netdata`, the log disappears but I'm not sure if it is following my configuration or it is following the default value

### Expected behavior

follow the configuration in the `netdata.conf` file

### Steps to reproduce

1. update existing netdata to 1.33.1 using update script

### Installation method

kickstart-static64.sh

### System info

```shell
Linux netdata-01 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.6 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.6 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

### Netdata build info

```shell
Version: netdata v1.33.1
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=-static -O3 -I/openssl-static/include' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: legacy-static
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by MrZammler** [comment]
Hi @yasharne!

The message `Found 0 legacy dbengines, setting multidb diskspace to 256MB` _should_ only appear on a fresh install, when there is no netdata.conf yet. And even after that, if you don't edit the `netdata.conf` to put a custom `dbengine multihost disk space`, it should not display again (the value computed is stored in a file (you should see the message `Created file /somewhere/dbengine_multihost_size to store the computed value`.

The value in `dbengine multihost disk space` will override the value computed. You can also check the value of `multidb-disk-quota` in `/api/v1/info`.

The only way to see the message again on a restart, is for the file that stores this value to be missing. In this case it will try to re-create it, and print the message, but the working value will be the one from `netdata.conf`.

**Comment by yasharne** [comment]
Thanks for your explanation @MrZammler 
So in my scenario, it wasn't a fresh install, I was upgrading an older netdata using the update script, therefore I had a `netdata.conf` file there already.
But as I checked the endpoint you mentioned, it shows the correct value (same as the one inside the old `netdata.conf` file)

**Comment by MrZammler** [comment]
There is a possibility that even though there is an option already in `netdata.conf` we still evaluate the automatic detection, maybe we could skip it perhaps...

Thanks!
