### ISSUE TITLE
[Bug]: Static installer ignores --no-updates options 

### ISSUE THREAD

**Issue by aldem** [netdata/netdata#12679]
### Bug description

When using static installer (kickstart-static64.sh) the option `--no-updates` has no effect.

### Expected behavior

`--no-updates` option is expected to disable automatic updates.

### Steps to reproduce

1. Run `kickstart-static64.sh --no-updates`
2. Crontab entry is created: `/etc/cron.daily/netdata-updater` and points to update script.

### Installation method

kickstart-static64.sh

### System info

```shell
Looks like it is system-independent
```

### Netdata build info

```shell
Version: netdata v1.33.1
```

### Additional info

Looks like the problem is in invocation of `netdata-*.run` script, the parameter is set via `${NETDATA_AUTO_UPDATES:+--auto-update}` - this actually provides `--auto-update` if `NETDATA_AUTO_UPDTAES`variable is set - and it is set to `0` (instead of empty string - as it used to be) when option `--no-updates` is provided to kickstart.

**Comment by ilyam8** [comment]
Fixed in https://github.com/netdata/netdata/pull/12296.
