### ISSUE TITLE
[Bug]: Incorrect versioning of release artifacts and binaries in release v1.34.0

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#12692]
Due to bugs in the new release engineering code, there are numerous issues with versioning for the v1.34.0 release of Netdata. More specifically:

- The release artifacts on the release itself show a version of `v1.33.1-339-g0046735ba` instead of `v1.34.0`
- The binaries for the release, irrespective of the source, also show the same version.
- The Docker images for the release have incorrect image tags that are inconsistent with our previous Docker image tag.
- Git tags ended up partially duplicated.

The release itself is _otherwise_ fine, and does include everything outlined in the release notes.

We are currently working on a patch release (expected to be created on 2022-04-15) that will correct these issues.

**Comment by candrews** [comment]
The newly created [1.34.1 release](https://github.com/netdata/netdata/releases/tag/v1.34.1) still has some problems.

The release archive https://github.com/netdata/netdata/releases/download/v1.34.1/netdata-v1.34.1.tar.gz contains at its root a directory named `netdata-v1.33.1-345-g89fb721f6`

**Comment by ilyam8** [comment]
Netdatabot is also [unaware there is 1.34.1](https://github.com/netdata/netdata/commit/f526e03f4780c4dc46e10f539e5d7affbfa45265).
Latest (nightly) Debian package is `1.34.0-9-nightly`

```cmd
$ apt-cache madison netdata | head -n 1
   netdata | 1.34.0-9-nightly | https://packagecloud.io/netdata/netdata-edge/debian bullseye/main amd64 Packages
```

**Comment by vermaete** [comment]
The [sha256sums.txt](https://github.com/netdata/netdata/releases/download/v1.34.1/sha256sums.txt) still has the files of the  1.33.1 release.

**Comment by ilyam8** [comment]
Ok, I see, the v1.34.1 tag was created in the [v1.34 branch](https://github.com/netdata/netdata/tree/v1.34). If that is expected then it looks like CI is not ready for this change.

**Comment by metajiji** [comment]
Now `https://my-netdata.io/kickstart.sh` - broken too and install latest 1.33.1 instead real latest 1.34.1 version. The root cause in github artifacts.

Actual behavior for `v1.34.1` release

```bash
$ curl -sL https://github.com/netdata/netdata/releases/download/v1.34.1/sha256sums.txt 
892022f0f9c43a61f8ef11699c9f2958540d5ee1430adbdbb4b40a1cf9514e20 *./latest-version.txt
02ef6992e1c7563096dada37c97be5e014a134a5cc53647fcc5cbb2b93a11edf *./netdata-aarch64-latest.gz.run
02ef6992e1c7563096dada37c97be5e014a134a5cc53647fcc5cbb2b93a11edf *./netdata-aarch64-v1.33.1-345-g89fb721f6.gz.run
407234fa0128dc4459e88c62c9681084580947454b16735f96aed85f1acd4ca7 *./netdata-armv7l-latest.gz.run
407234fa0128dc4459e88c62c9681084580947454b16735f96aed85f1acd4ca7 *./netdata-armv7l-v1.33.1-345-g89fb721f6.gz.run
6cab818bcc5170b91a79bfe9a42eb71e45c875e260f0e3fc36bd507e7d00a678 *./netdata-latest.gz.run
cc27a73d5e92eb7a89b85516594bf1c4f52d4f5cc2104772588d7b7ce093f179 *./netdata-latest.tar.gz
2e311dbb6ab271603b32f77a3369403a40a0f58d66097698169c88ea0e5bb073 *./netdata-ppc64le-latest.gz.run
2e311dbb6ab271603b32f77a3369403a40a0f58d66097698169c88ea0e5bb073 *./netdata-ppc64le-v1.33.1-345-g89fb721f6.gz.run
6cab818bcc5170b91a79bfe9a42eb71e45c875e260f0e3fc36bd507e7d00a678 *./netdata-v1.33.1-345-g89fb721f6.gz.run
cc27a73d5e92eb7a89b85516594bf1c4f52d4f5cc2104772588d7b7ce093f179 *./netdata-v1.33.1-345-g89fb721f6.tar.gz
6cab818bcc5170b91a79bfe9a42eb71e45c875e260f0e3fc36bd507e7d00a678 *./netdata-x86_64-latest.gz.run
6cab818bcc5170b91a79bfe9a42eb71e45c875e260f0e3fc36bd507e7d00a678 *./netdata-x86_64-v1.33.1-345-g89fb721f6.gz.run
```

Expected behavior for as example `v1.32.0` release

```bash
$ curl -sL https://github.com/netdata/netdata/releases/download/v1.32.0/sha256sums.txt 
6d76ebb821de1fe85bd21210963de7eed576fef5e7df2a50b24e9368fd72d199 *./latest-version.txt
1d257873b367aa2966f36dce96375d628a7b980f15cee9936509978af383dbf0 *./netdata-aarch64-latest.gz.run
1d257873b367aa2966f36dce96375d628a7b980f15cee9936509978af383dbf0 *./netdata-aarch64-v1.32.0.gz.run
2fa7641f426b23deb193cec692bd64d0dfc2e7f4bb0d24d05ff3429a87f06d0e *./netdata-armv7l-latest.gz.run
2fa7641f426b23deb193cec692bd64d0dfc2e7f4bb0d24d05ff3429a87f06d0e *./netdata-armv7l-v1.32.0.gz.run
3f22e84b25b3b8fc9dd4d37d976cedb8e5b590fb1d4769a23157bd9c4e6366fb *./netdata-latest.gz.run
5e066d322f88013cea78eb9bb42bca64599278b9db8d46593777e4258743fefd *./netdata-latest.tar.gz
c0934ecbcd61ed04811cdba1afffa2e209b24e1279f4670de8efa488b73fc0a4 *./netdata-ppc64le-latest.gz.run
c0934ecbcd61ed04811cdba1afffa2e209b24e1279f4670de8efa488b73fc0a4 *./netdata-ppc64le-v1.32.0.gz.run
3f22e84b25b3b8fc9dd4d37d976cedb8e5b590fb1d4769a23157bd9c4e6366fb *./netdata-v1.32.0.gz.run
5e066d322f88013cea78eb9bb42bca64599278b9db8d46593777e4258743fefd *./netdata-v1.32.0.tar.gz
3f22e84b25b3b8fc9dd4d37d976cedb8e5b590fb1d4769a23157bd9c4e6366fb *./netdata-x86_64-latest.gz.run
3f22e84b25b3b8fc9dd4d37d976cedb8e5b590fb1d4769a23157bd9c4e6366fb *./netdata-x86_64-v1.32.0.gz.run
```

**Comment by Ferroin** [comment]
We’re working on fixing the release artifacts for v1.34.1 as we speak.

**Comment by Ferroin** [comment]
> Ok, I see, the v1.34.1 tag was created in the [v1.34 branch](https://github.com/netdata/netdata/tree/v1.34). If that is expected then it looks like CI is not ready for this change.

This is expected, and the CI is correct. If we’re doing patch releases on release branches (as was discussed), then nightlies by definition are _not_ based on those patch releases (because they aren’t patch whatever plus some number of commits, since patch whatever is not a snapshot of the state of the `master` branch).

**Comment by Ferroin** [comment]
The release artifacts on the v1.34.1 release should be correct now.

**Comment by cakrit** [comment]
Looks fixed.
