### ISSUE TITLE
[Bug]: Wrong charttype used for ip.inbound_conn?

### ISSUE THREAD

**Issue by vobruba-martin** [netdata/netdata#12693]
### Bug description

It looks like that ip.inbound_conn chart is collecting absolute values instead of incremental.
![image](https://user-images.githubusercontent.com/6897988/163551419-a80ad63a-a1db-4c42-90f1-24093a5f5ed5.png)
Those drops are caused by Netdata restarts.

### Expected behavior

The chart should look like ip.tcp_outbound_conn because I doupt that I have millions of inbound connections per second.
![image](https://user-images.githubusercontent.com/6897988/163551856-166fa625-e17c-4f8f-9cbb-ab25c1c0dd11.png)

### Steps to reproduce

1. Just start Netdata and watch ip.inbound_conn chart.

### Installation method

kickstart.sh

### System info

```shell
Linux 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.34.0
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by thiagoftsm** [comment]
Thank you @vobruba-martin I will take a look on this today.

**Comment by thiagoftsm** [comment]
Helo @vobruba-martin ,

Sorry for the delay, but today is a holiday in my country. The bug will be fixed with the PR https://github.com/netdata/netdata/pull/12698.

A doubt, considering that you were running the `socket` thread, did you have the bugs reported [here](https://github.com/netdata/netdata/issues/12027), or the sockets ran normally?

Best regards!

**Comment by vobruba-martin** [comment]
Thank you @thiagoftsm !

Yes, I'm currently testing the socket thread. It runs without any error. Good job!

**Comment by thiagoftsm** [comment]
Hello @vobruba-martin ,

Thank you very much for your update. The PR already have enough approves, but I will merge it only on Monday. When it is merged the problems you are having with the chart will be fixed.

Best regards!

**Comment by thiagoftsm** [comment]
Hello @vobruba-martin ,

Next nightly will have the bug fixed.

Thank you for your report, and I apologize for the bug.

Best regards!
