### ISSUE TITLE
[Feat]: Add MySQL Percona statistics

### ISSUE THREAD

**Issue by vobruba-martin** [netdata/netdata#12705]
### Description

Percona Server for MySQL provides additional statistics. It would be great to see them in Netdata.

User/Thread statistics and status variables for 8.0:
https://www.percona.com/doc/percona-server/8.0/diagnostics/user_stats.html
https://www.percona.com/doc/percona-server/8.0/ps-variables.html#status-variables

User/Thread statistics and status variables for 5.7:
https://www.percona.com/doc/percona-server/5.7/diagnostics/user_stats.html
https://www.percona.com/doc/percona-server/5.7/ps-variables.html#status-variables

### Importance

nice to have

### Value proposition

Percona Server for MySQL adds several `INFORMATION_SCHEMA` tables, several commands, and the userstat variable. The tables and commands can be used to understand the server activity better and identify the source of the load.

### Proposed implementation

It should be enough to extend `go.d/mysql` plugin to detect new `INFORMATION_SCHEMA` tables and server status variables.

**Comment by ilyam8** [comment]
Hi, @vobruba-martin. I see you mention:
 - [INFORMATION_SCHEMA.CLIENT_STATISTICS](https://www.percona.com/doc/percona-server/8.0/diagnostics/user_stats.html#CLIENT_STATISTICS)
 - [INFORMATION_SCHEMA.USER_STATISTICS](https://www.percona.com/doc/percona-server/8.0/diagnostics/user_stats.html#THREAD_STATISTICS)
 - [INFORMATION_SCHEMA.THREAD_STATISTICS](https://www.percona.com/doc/percona-server/8.0/diagnostics/user_stats.html#USER_STATISTICS)

Let's narrow down the scope of this request and discuss only USER_STATISTICS. If we need other table statistics let's have them as a separate feature request.

---

I see [we collect](https://github.com/netdata/go.d.plugin/blob/2f32cd89f308f5e2f5a7479ebd7ba478b4fde7ab/modules/mysql/collect_user_statistics.go#L8-L25) user statistics for MariaDB, but the USER_STATISTICS table schema is a bit different:
 - [MariaDB](https://mariadb.com/kb/en/user-statistics/#using-the-information-schema-table).
 - [Percona](https://www.percona.com/doc/percona-server/8.0/diagnostics/user_stats.html#USER_STATISTICS).

For MariaDB we have the following charts per a user:
 - User CPU Time (`cpu_time`).
 - Rows Operations (`read`, `sent`, `deleted`, `inserted`, `updated`).
 - Commands (`select`, `update`, `other`).

For Percona it would be the same charts, the only difference is Rows Operations (`fetched`, `updated`, and probably `table_read`).

Does it look good to you? Are there any other stats in the USER_STATISTICS table you think are important to collect?

**Comment by vobruba-martin** [comment]
It looks good but I would also add these stats (if I'm not mistaken, all of them are also available in MariaDB):

Important for me:
`TOTAL_CONNECTIONS`, `BINLOG_BYTES_WRITTEN`, `ROLLBACK_TRANSACTIONS` and `LOST_CONNECTIONS`

Less important for me but still nice to have:
`COMMIT_TRANSACTIONS`, `DENIED_CONNECTIONS`, `ACCESS_DENIED` and `EMPTY_QUERIES`

**Comment by ilyam8** [comment]
> COMMIT_TRANSACTIONS – The number of COMMIT commands issued by this user’s connections.
> ROLLBACK_TRANSACTIONS – The number of ROLLBACK commands issued by this user’s connections.

Oh, both of these counters are commands, so I guess we can just add them to the "Commands" chart.

**Comment by vobruba-martin** [comment]
I think that `COMMIT` and `ROLLBACK` commands should be in separate charts. They are transaction commands and they are mostly autogenerated by the server. Especially if you have autocommit turned ON, which is the default behavior.
