### ISSUE TITLE
[Feat]: Translations for the main programs

### ISSUE THREAD

**Issue by LimeZky** [netdata/netdata#12710]
### Description

I think that Netdata should have translations for its main programs. You can do this by uploading texts to a translate platform and everyone free can help with it.

### Importance

must have

### Value proposition

1. Help local developers from different countries
2. More easy to understand
3. More people will know and use Netdata

**Comment by ilyam8** [comment]
Hi, @LimeZky. Thanks for the request, but we have [no plans for multilingual support](https://github.com/netdata/netdata/issues/8933#issuecomment-625319404) for now.

**Comment by LimeZky** [comment]
As there is not only for documents, but more for the main UI which is more stable
