### ISSUE TITLE
[Chore]: remove python.d/* announced in v1.34.0 deprecation notice

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#12723]
### Problem

n/a

### Description

In accordance with v1.34.0 [deprecation notice](https://github.com/netdata/netdata/releases#deprecation-notice), in the upcoming release we want to have removed:

- [x] [python.d/apache](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/apache)
- [x] [python.d/couchdb](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/couchdb)
- [x] [python.d/dns_query_time](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/dns_query_time)
- [x] [python.d/dnsdist](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/dnsdist)
- [x] [python.d/elasticsearch](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/elasticsearch)
- [x] [python.d/energid](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/energid)
- [x] [python.d/freeradius](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/freeradius)
- [x] [python.d/httpcheck](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/httpcheck)
- [x] [python.d/isc_dhcpd](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/isc_dhcpd)
- [x] [python.d/mysql](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/mysql)
- [x] [python.d/nginx](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/nginx)
- [x] [python.d/phpfpm](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/phpfpm)
- [x] [python.d/portcheck](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/portcheck)
- [x] [python.d/powerdns](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/powerdns)
- [x] [python.d/redis](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/redis)
- [x] [python.d/web_log](https://github.com/netdata/netdata/tree/v1.33.1/collectors/python.d.plugin/web_log)

All of the items should be moved to https://github.com/netdata/community.

### Importance

must have

### Value proposition

1. no duplicate collectors.
2. no unmaintained code in the netdata/netdata repo.

**Comment by Ferroin** [comment]
We will need to audit what dependencies each of these have on the host system, as we can probably cut back on what Python modules we install in some of our packaging code.

**Comment by ilyam8** [comment]
Among those we are deleting only the mysql collector has a dependency: 

 - we kind of need it for custom collectors (see #1906)
 - on the other hand, we can add a note in the docs - if you want to use a custom python collector that uses MySQLService - you need to install the lib manually.

**Comment by ilyam8** [comment]
@Ferroin `python-dnspython` package can be removed
