### ISSUE TITLE
[Feat]: Feature or Bug: Disable cloud in Docker Container

### ISSUE THREAD

**Issue by jonathanmmm** [netdata/netdata#12736]
### Problem

Hi,

I am using netdata in my local setup, I put it behind a proxy (only being inside a local docker network, netdata itself having no internet connection).

I am trying to disable all requests that go to another ip, than the one of my server.

I set:
```
      - DO_NOT_TRACK=1
      - DISABLE_TELEMETRY=1
      - NETDATA_DISABLE_CLOUD=1
      - NETDATA_REQUIRE_CLOUD=0
```
as environment variables via docker-compose (the last two are probably not intended to work)

Also I mounted 

`/var/lib/netdata/cloud.d/cloud.conf`
with the following content:
```
[global]
    enabled = no
```
I also tried with
```
[global]
    enabled = no
    cloud base url = https://localhost
```

I shutdown the container stack and removed all volumes and forced recreate while starting up.
In my browser I see the following urls that it connects to:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/32403139/164452126-72690ea7-798a-4adc-affa-bb4f1534fded.png">

### Description

I don't know if it is a bug or not just implemented.

I will probably use Netdata far less. I don't want any cloud connectitity.

Like I previously wrote in an issue:
Even sending only the IP to third parties (like google) is giving away personal data that violates personal rights (lawsuit in Germany, Munich):
https://www.theregister.com/2022/01/31/website_fine_google_fonts_gdpr/

It would be nice to have an easy way to disable any connections that go anywhere from the browser.
I don't need a new way to disable connections that the container tries itself, because I blocked its connection to the internet already.
Anybody that wants to do that can use a reverse proxy in front of it and put it into an internal docker network.

### Importance

blocker

### Value proposition

.

### Proposed implementation

create DISABLE_CLOUD environment variable or make this /var/lib/netdata/cloud.d/cloud.conf work in docker containers.

Would be really great

**Comment by Ferroin** [comment]
The `latest-version.txt` Google URL is part of the update check code. We probably should have a way to disable this for reasons that have nothing to do with privacy. However, this _cannnot_ be self-hosted by the agent’s internal web server, and we do have a legitimate interest in informing the user that a newer version of our software.

The `netdata-news.cdn.prismic.io` URL is for the news functionality in the dashboard. Just like the update check, this cannot be self-hosted by the agent’s internal web server (though the check for new news items should probably be done by the agent itself and not the dashboard), and we do (to some extent) have a legitimate interest here.

For the `registry.my-netdata.io` stuff, you can add the following two lines to your `netdata.conf` to get rid of that:

```
[registry]
    registry to announce = http://localhost:19999
```

**Comment by jonathanmmm** [comment]
> The `latest-version.txt` Google URL is part of the update check code. We probably should have a way to disable this for reasons that have nothing to do with privacy. However, this _cannnot_ be self-hosted by the agent’s internal web server, and we do have a legitimate interest in informing the user that a newer version of our software.
> 
> The `netdata-news.cdn.prismic.io` URL is for the news functionality in the dashboard. Just like the update check, this cannot be self-hosted by the agent’s internal web server (though the check for new news items should probably be done by the agent itself and not the dashboard), and we do (to some extent) have a legitimate interest here.
> 
> For the `registry.my-netdata.io` stuff, you can add the following two lines to your `netdata.conf` to get rid of that:
> 
> ```
> [registry]
>     registry to announce = http://localhost:19999
> ```

Thanks for your answer, I don't want to selfhost anything, except using the netdata dashboard without anything, no update check, no cloud connection, no analytics. Just the dashboard. 

Of course pressing the button, like "check update" or "sign in" would connect to any service, but if I don't press these buttons.
I see your interest, but not giving people the choice to use it privately will hurt netdata more than it will benefit it.
People will propably avoid it and will tell people not to use it anymore, when/because there is a resistance to truly host it privately.

I am completely fine with having such services builtin, but there should at least be an opt-out without building from scratch and either live with an old version or maintaining a fork.

**Comment by mcinquin** [comment]
Hello,

I can add that being able to output everything is an important feature in an air-gapped environment.
