### ISSUE TITLE
[Feat]: dbengine page cache should not be dumpable and should enable KSM

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12744]
### Problem

Today we allocate pagecache pages using `malloc()` and free them with `free()`:

- `malloc()`: https://github.com/netdata/netdata/blob/72a5ec6e37d22dd6c7cfe2562ef72bc86025b114/database/engine/rrdengine.c#L179
- `malloc()`: https://github.com/netdata/netdata/blob/72a5ec6e37d22dd6c7cfe2562ef72bc86025b114/database/engine/rrdengine.c#L334
- `malloc()`: https://github.com/netdata/netdata/blob/e91d1110e5998ede7bc8aecf5309c28176361acf/database/engine/rrdengineapi.c#L727
- `free()`: https://github.com/netdata/netdata/blob/e91d1110e5998ede7bc8aecf5309c28176361acf/database/engine/pagecache.c#L1225
- `free()`: https://github.com/netdata/netdata/blob/e91d1110e5998ede7bc8aecf5309c28176361acf/database/engine/pagecache.c#L359
- `free()`: https://github.com/netdata/netdata/blob/e91d1110e5998ede7bc8aecf5309c28176361acf/database/engine/rrdengineapi.c#L205

I suggest to allocate them with `mmap()` (and free them with `munmap()`) and use `madvise()` to set the following options:

1. `MADV_DONTFORK`, to prevent these pages from being copied on `fork()`.
2. `MADV_MERGEABLE`, to enable these pages to be deduped with KSM (this can half the cache size impact on the system).
3. `MADV_DONTDUMP`, to prevent these pages from being included in coredumps.

The change seems trivial. There are only 3 places where memory pages are allocated and only 3 places where memory pages are freed.

### Description

See above.

### Importance

must have

### Value proposition

Netdata parents need a large page cache to efficiently support large context queries. We need these page caches to be as efficient as possible.

The suggested change will allow netdata parents to scale a lot better.

### Proposed implementation

See above.

**Comment by ktsaou** [comment]
@stelfrag @ilyam8 please check this.

**Comment by ktsaou** [comment]
For coredump control, keep in mind that there is also a `/proc/PID/coredump_filter` which allows selecting the type of memory that will be dumped, but I think we need to allocate with `mmap()` to actually make any good use of it. See `man core` for more information.

**Comment by Ferroin** [comment]
Speaking with my user hat on, this is also helpful for users who simply want to run with a larger DBEngine page cache size (for example, because they want to ensure that accessing the dashboard does not hit the disk until they get very deep into historic data), albeit not as much as for those who are dealing with large numbers of child nodes.
