### ISSUE TITLE
[Feat]: Monitor Netdata's sqlite database

### ISSUE THREAD

**Issue by MrZammler** [netdata/netdata#12766]
### Problem

We should have charts monitoring our sqlite, in terms of size, operations, etc.

### Description

Especially for cloud connectivity, sqlite is constantly used. Monitoring it could also reveal ways to optimize operations and how it correlates with the whole Netdata state.

### Importance

nice to have

### Value proposition

1. Understand how it is used, and ways to optimize if needed.

**Comment by andrewm4894** [comment]
Curious, do we actually have a SQLite collector? I searched but couldn't find one.

**Comment by MrZammler** [comment]
This is mostly done.

**Comment by glibg10b** [comment]
@andrewm4894 I wish :cry:
