### ISSUE TITLE
[Bug]: dbegnine deadlock

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12770]
### Bug description

We have two parents. The setup is like this:

20 childs -> parent1 -> parent2

On the parents we randomly experience deadlocks at the dbengine. Once this happens, the parents do not respond to data queries any more.

It is totally random. It happens daily, but we don't know what exactly triggers it. It does not happen on both parents concurrently. Sometimes only on parent 1, other times only on parent 2.

1. [stack trace of deadlock on parent1](https://pastebin.com/Ljn2b9ms)
2. [stack trace of deadlock on parent2](https://pastebin.com/19d2AzZS)
3. [second stack trace of deadlock on parent2](https://pastebin.com/Dqnp95pw)
4. [second stack trace of deadlock on parent1](https://pastebin.com/j6v6uUzc)
5. [third stack trace of deadlock on parent2](https://pastebin.com/gvCR3AdV) this must be early in the deadlock.
6. [third stack trace of deadlock on parent1](https://pastebin.com/Q0TBwJnj) this seems to be only at the global rrd_lock. ML is disabled in this version.

### Expected behavior

Not deadlock

### Steps to reproduce

1. Let the parents running
7. Hit them with random queries
8. Once per day, eventually they will deadlock

### Installation method

kickstart.sh

### System info

```shell
# uname -a; grep -HvE "^#|URL" /etc/*release
Linux gce-parent1 5.10.0-12-cloud-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
# $(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
Version: netdata v1.34.0-53-g8ed8c59fc
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O1 -ggdb' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by stelfrag** [comment]
Closing as there have been several changes / improvements. Will create a new one if needed
