### ISSUE TITLE
[Bug]: UPS/NUT label and data not appeared in Netdata Cloud after changing

### ISSUE THREAD

**Issue by srozinov** [netdata/netdata#12780]
### Bug description

1. Added NUT support:
nut_ups=ups@172.19.0.1

It appeared in Agent and Cloud, all was OK.

2. Added 
nut_names["ups@172.19.0.1"]="Main UPS"

and renamed several times. Now it appeared in Agent under new label but in Cloud the old label persisted and no new data posted.

3. Removed NUT support by commenting out above lines. It disappeared in both Agent and Cloud after a while.

4. Restored NUT support and label. It appeared in Agent but not in Cloud.
 
Do I need to remove and reinvite my Agent again to the Room? Or there is a way to synchronize NUT label and data without reinvitation?

### Expected behavior

Restoration of NUT label and data in NetData Cloud.

### Steps to reproduce

1. Add NUT support:
nut_ups=ups@172.19.0.1

2. Add a label
nut_names["ups@172.19.0.1"]="Main UPS"

and rename it after appearance.

3. Remove NUT support by commenting out above lines. 

4. Restore NUT support and label again.

### Installation method

docker

### System info

```shell
Linux aquanas 5.4.128-1-pve #1 SMP PVE 5.4.128-2 (Wed, 18 Aug 2021 16:20:02 +0200) x86_64 Linux
/etc/alpine-release:3.15.3
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.15.3
/etc/os-release:PRETTY_NAME="Alpine Linux v3.15"
```

### Netdata build info

```shell
Version: netdata v1.33.1-250-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--with-bundled-libJudy' '--disable-ebpf' 'CFLAGS=' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

**Comment by srozinov** [comment]
Screens:

Cloud: https://drive.google.com/file/d/1FJR2kjYab0SENpFDj9IrbMebVtOCIRT3/view?usp=sharing
Local: https://drive.google.com/file/d/1FG_EcRk1qkIpcPlvcJ9Xqmr9Qrbe-znl/view?usp=sharing

**Comment by ilyam8** [comment]
@srozinov hi, can you adjust the title? It is "[Bug]:".

**Comment by cpipilas** [comment]
@srozinov would it be possible to update to the latest version and  re-test?

**Comment by srozinov** [comment]
> @srozinov would it be possible to update to the latest version and re-test?

Yes after update the issue has gone. OK to close it, thanks!
