### ISSUE TITLE
[Feat]: Go plug-in: Integer type support for SNMP monitoring

### ISSUE THREAD

**Issue by srozinov** [netdata/netdata#12804]
### Problem

When querying Mikrotik router for CPU/Memory usage, I see:

[ DEBUG ] run[manager] run.go:41 tick 0
[ DEBUG ] snmp[Router] collect.go:46 skipping OID '1.3.6.1.2.1.25.3.3.1.2.1' (unsupported type 'Integer')
[ DEBUG ] snmp[Router] collect.go:46 skipping OID '1.3.6.1.2.1.25.2.3.1.5.65536' (unsupported type 'Integer')
[ DEBUG ] snmp[Router] collect.go:46 skipping OID '1.3.6.1.2.1.25.2.3.1.6.65536' (unsupported type 'Integer')

### Description

Need to support standard Integer type for absolute charts. Previous Node SNMP plug-in supported this.

### Importance

really want

### Value proposition

This is needed to broaden supported device list and data monitored by SNMP useing Go plug-in.

**Comment by ilyam8** [comment]
@surajnpn the type we skip

```
EndOfContents     Asn1BER = 0x00
UnknownType       Asn1BER = 0x00								
Integer           Asn1BER = 0x02
BitString         Asn1BER = 0x03
OctetString       Asn1BER = 0x04
Null              Asn1BER = 0x05
ObjectIdentifier  Asn1BER = 0x06
ObjectDescription Asn1BER = 0x07
IPAddress         Asn1BER = 0x40															
TimeTicks         Asn1BER = 0x43
Opaque            Asn1BER = 0x44
NsapAddress       Asn1BER = 0x45
NoSuchObject      Asn1BER = 0x80
NoSuchInstance    Asn1BER = 0x81
EndOfMibView      Asn1BER = 0x82
```

I think `Integer` is that list by (my) mistake 😅
