### ISSUE TITLE
[Feat]: Use externally prepared Docker images for static builds instead of creating them on-demand for each build.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#12817]
### Problem

Currently, our static build process prepares a Docker image locally each time a static build is run. This is inefficient and wastes resources in CI, as well as leaving things in an undesirable state on developer systems.

### Description

The static build process should use pre-built Docker images instead of building them on-demand each time a static build is run.

### Importance

really want

### Value proposition

1. Static builds should run a bit faster, especially for non-native architectures.
2. Developers won’t have to deal with dead containers left behind by the static build process.

### Proposed implementation

Implementation will be in two phases:

1. Adding a new Dockerfile to https://github.com/netdata/helper-images to build the requisite images (to be named `netdata/static-builder`).
2. Modifying the static build code to use the new image instead of preparing one locally.

**Comment by ivangergo3** [comment]
@dimko we might need to change our CI as well
