### ISSUE TITLE
[Feat]: When more than one certificate placed in the "ssl certificate" file only the first cert is returned

### ISSUE THREAD

**Issue by drawks** [netdata/netdata#12840]
### Bug description

When following the documented steps for enabling tls by placing
```
[web]
    ssl key = /etc/pki/tls/private/netdata.key
    ssl certificate = /etc/pki/tls/certs/netdata.crt
```
in the config and restarting netdata. Netdata starts and is attempting to start a tls session, however it only ever offers the first certificate present in the `ssl certificate` file, I would expect that it would offer up all certificates from this file suchy that a certificate and its intermediate could be used.

### Expected behavior

All certificates present in `ssl certificate` should be returned by the tls listener.

### Steps to reproduce

1. generate a certificate pair from an intermediate pki
2. place both the certificate and the intermediate certificate concatenated in a file
3. set `ssl certificate` to point to your certificate file
4. set `ssl key` to point to the key
5. restart netdata
6. use `gnutls-cli` or `openssl s_client` to connect to the netdata tls listener
7. observe that only the first certificate is returned and client cannot establish trust due to the missing intermediate certificate
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux localhost.localdomain 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)
```

### Netdata build info

```shell
Version: netdata v1.33.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-plugin-freeipmi' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
Install type: unknown
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: NO
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by Ferroin** [comment]
This appears to be a result of the fact that CentOS 7 is still using a 1.0.x version of OpenSSL. OpenSSL versions prior to 1.1.0 had issues with handling of full certificate chains all in one file.

@thiagoftsm is looking into this a bit further to confirm for certain and see if there are any workarounds. Independent of what he may find, our static builds _should_ be unaffected by this issue on CentOS 7 (because they use their own copy of OpenSSL), so if using those is an option for you that may be the quickest resolution.

**Comment by drawks** [comment]
Any updates on this?

**Comment by thiagoftsm** [comment]
Hello @drawks ,

Sorry for delay. We are working to fix some issues with TLS and there is a [PR](https://github.com/netdata/netdata/pull/14120) under review right now, so for while we did not address this issue.

I will talk with @MrZammler and @Dim-P to verify the possibility to address this issue as soon the PR is merged
 
Best regards!

**Comment by ilyam8** [comment]
Closing because no one seems to be working on it and Centos7 will be EOL in six months.
