### ISSUE TITLE
[Feat]: implement helper script which retrieves available netdata versions

### ISSUE THREAD

**Issue by maneamarius** [netdata/netdata#12855]
### Problem

We don't have a easy way to find available netdata versions for installation.

### Description

Implement helper script which retrieves available netdata versions.

### Importance

nice to have

### Value proposition

Will be easier for end users to find available netdata versions.

**Comment by Ferroin** [comment]
Closing as not planned for now, as there seems to be little to no interest among users in installing old versions.
