### ISSUE TITLE
[Bug]: Invalid permissions of /etc/netdata after installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by solution-al** [netdata/netdata#12871]
### Bug description

I installed netdata on a brand new Ubuntu 20.04 VPS like this when running as `root`:
```
# bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry --dont-wait
```

Installation ends with exit code 0, but netdata is unable to start - this is a first problem - exit code should not be 0 in this case!

Now, when looking `netdata` service log, then this is seen:
```
# journalctl -u netdata.service
...
May 11 08:50:50 xxx netdata[38148]: Cannot change directory to '/etc/netdata'
May 11 08:50:50 xxx netdata[38148]: EXIT: netdata prepares to exit with code 1...
May 11 08:50:50 xxx netdata[38148]: EXIT: cleaning up the database...
May 11 08:50:50 xxx netdata[38148]: Cleaning up database [0 hosts(s)]...
May 11 08:50:50 xxx netdata[38148]: EXIT: all done - netdata is now exiting - bye bye...
May 11 08:50:50 xxx systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
...
```

Looking at `/etc/netdata` permissions shows the following:
```
# ls -ld /etc/netdata
drwxr-x--- 10 root root 4096 May 11 07:51 /etc/netdata
```

Also, all files under `/etc/netdata` are with the same permissions. I would expect them to be for `netdata:netdata`:
```
# ls -la /etc/netdata
total 100
drwxr-x---  10 root root  4096 May 11 07:51 .
drwxr-xr-x 110 root root  4096 May 11 07:51 ..
drwxr-xr-x   2 root root  4096 May 11 00:24 charts.d
drwxr-xr-x   2 root root  4096 May 11 00:24 custom-plugins.d
drwxr-xr-x   2 root root  4096 May 11 00:24 ebpf.d
-rwxr-xr-x   1 root root  2045 May 11 00:24 edit-config
drwxr-xr-x   2 root root  4096 May 11 07:51 go.d
-rw-r--r--   1 root root 47595 May 11 07:51 health_alarm_notify.conf
drwxr-xr-x   2 root root  4096 May 11 07:51 health.d
-rw-r--r--   1 root root    69 May 11 00:24 .install-type
-rw-r--r--   1 root root   518 May 11 07:51 netdata.conf
-rw-r-----   1 root root     0 May 11 07:51 .opt-out-from-anonymous-statistics
drwxr-xr-x   2 root root  4096 May 11 07:51 python.d
drwxr-xr-x   2 root root  4096 May 11 00:24 ssl
drwxr-xr-x   2 root root  4096 May 11 00:24 statsd.d
```

I see that `/etc/netdata` has `root:root` as owner and group, thus making it impossible for netdata process to start. I would expect this directory.

I've installed netdata like this multiple times and have not had any problems before. Also, this problem does not seem to happen every time (maybe different kickstart.sh is served depending on the IP address of the server I'm installing it into?).

Has something changed?

### Expected behavior

`/etc/netdata` and everything under it owner and group should be `netdata`.

### Steps to reproduce

Install netdata:
```
# bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry --dont-wait
```

### Installation method

kickstart.sh

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux xxx 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
netdata -W buildinfo
Version: netdata v1.34.0-139-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by maneamarius** [comment]
I tested on a fresh VM running Ubuntu 20.04 and I can not reproduce the issue, it works fine for me.
Could you please try uninstalling netdata, cleaning up any related folders (/etc/netdata, /usr/lib/netdata etc.), and then try installing again.
Maybe take a screenshot of the last page of the installation log, would be helpful and if you see any errors during the installation try to capture them.

**Comment by solution-al** [comment]
I did recrate a new VPS from snapshot (in Hetzner) and performed a clean installation while seeing this problem. However, when this problem does not exist (on some other VPS), then I see that the only difference with permissions is this:
```
# ls -ld /etc/netdata
drwxr-xr-x 10 root root 4096 May 11 07:51 /etc/netdata
```

Basically read-write permissions are assigned to others too. This feels also wrong and might be even insecure.

Does netdata store its installation log somewhere?

**Comment by iigorkarpov** [comment]
These permissions are perfectly normal. Please compare the other directory permissions in /etc/
Permissions for directory are slightly different from the file permissions. For directory drwr-xr-x meant the the owner can do whatever he wants, his group can "read" the directory, that is to list the files in it, and "execute" it, which means they can cd to this directory and access its content. Same for "others".

**Comment by solution-al** [comment]
@iigorkarpov I understand what these permissions mean, but I disagree that it's fine since other directories in `/etc` have same permissions (which in major cases is like you said, but is also not always true due to some exceptions - at least for my installation).

However, since `/etc/netdata` might contain sensitive data (for example `/etc/netdata/python.d/postgres.conf` containing database access credentials) then the permissions described above might give access to any non-privileged user to that information. This is definitely not okay.

You might argue that `/etc/netdata` itself might have more open permissions, but only files containing sensitive data should have stricter permission bits, but this is just error-prone and sooner or later some file will have too open permissions thus possibly leaking sensitive information.

Any reason why `/etc/netdata` should not be owned by `netdata:netdata` and have permissions 750 (e.g. `drwxr-x---`) by default?

**Comment by iigorkarpov** [comment]
@solution-al sorry for being a Captain Obvious 😃 
I can't answer your last question however. Historically, maybe?

**Comment by solution-al** [comment]
After further investigation I suspect that the problem is caused by a more secure cloud-provider (in this particular case Hetzner) VPS base image. `umask` in that VPS shows the following:
```
# umask -S
u=rwx,g=rx,o=
```

However, on a default Ubuntu installation:
```
# umask -S
u=rwx,g=rx,o=rx
```

As mentioned above then `netdata` creates `/etc/netdata` directory with the following permissions on a new system:
```
# ls -ld /etc/netdata
drwxr-xr-x 10 root root 4096 May 11 07:51 /etc/netdata
```

This in turn means that if default Ubuntu installation is used then netdata manages to start successfully and there is no apparent problem. However, if owner and group of `/etc/netdata` would be set to `netdata` then it would also start with a more secure configuration (and it does not make any sense to have `root` as owner and group anyway). And of course permissions on `/etc/netdata` should be set to 750 due to possible security concerns mentioned above.

Should I create a separate issue for this or is this issue good enough?

**Comment by iigorkarpov** [comment]
Luckily I have Hetzner account. So I created Ubuntu 20 VPS:

```
root@ubuntu-2gb-hel1-2:~# umask -S
u=rwx,g=rx,o=rx
```

It seems that you set the custom mask at some moment.

**Comment by solution-al** [comment]
@iigorkarpov thanks for checking! After further investigation I can indeed confirm that we have changed default umask configuration by our provision software to be more secure by default.

Nevertheless:

1) `netdata` should work even with these stricter permission settings in effect - can be accomplished by setting user and group of `/etc/netdata` to `netdata` instead of `root`. I can confirm that `netdata` for us seems to work when setting `netdata` as owner and group manually to `/etc/netdata` after installation.

2) A totally separate issue is abovementioned security concern - I will create a separate GitHub issue for that.

**Comment by Ferroin** [comment]
Closing this as it appears to have been an issue with user configuration.
