### ISSUE TITLE
[Feat]: guess the release channel from the program version if `.environment` doesn't exist

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#12888]
### Problem

[get_release_channel()](https://github.com/netdata/netdata/blob/73bb8888f3bffcb36b99b9341f15d21b3de844d0/web/api/formatters/charts2json.c#L7-L37) expects:

- `%s/.environment` file.
- `RELEASE_CHANNEL` line in the file.

❗ **Native packages have no that file**.

If the file doesn't exist we always assume that the release channel is stable:

https://github.com/netdata/netdata/blob/73bb8888f3bffcb36b99b9341f15d21b3de844d0/web/api/formatters/charts2json.c#L13-L15

Which, as you may guess, is correct only 50% of the time 😄 

Facts:
 - If you install the Netdata deb package, the default release channel is nightly, you always get the wrong release channel value.

### Description

I think we need to implement a fallback method if `.environment` is missing. This is must-have for our native packages.

### Importance

must have

### Value proposition

1. People using native packages will get the correct release channel => the dashboard version check will work.

### Proposed implementation

I suggest parsing Netdata binary version: e.g. if it is `vX.Y.Z` - stable, nightly otherwise.

**Comment by Ferroin** [comment]
Relevant to https://github.com/netdata/dashboard/issues/393, which this should actually fix.
