### ISSUE TITLE
[Feat]: Use systemd units as apps groups

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata#12897]
### Problem

The apps.plugin allows for grouping processes under a logical name. Everything that is not mentioned in `apps_groups.conf` is then grouped under `other. Systemd services are examined by the cgroups plugin, and represented as a separate navigation item.

### Description

The systemd services examined by the cgroups plugin could be use to provide additional default groups. This allows us have a nice base line without having to extend apps_groups.conf, while still retaining the flexibility to have custom groupings as-is. The agent could also extract additional metrics for systemd services this way.

### Importance

nice to have

### Value proposition

1. Better grouping out-of-the box
2. Unifying apps and services
3. Retaining flexibility to have custom groupings 

### Proposed implementation

Possible caveat: wanting to group systemd services under e.g. `network` while also wanting to inspect individual cgroups for the grouped services.

**Comment by ilyam8** [comment]
I think this is no longer needed.

>  Everything that is not mentioned in apps_groups.conf is then grouped under `other.

This has been fixed, not an issue anymore.
