### ISSUE TITLE
[Bug]: Changing From Nightly To Stable (w/ `apt`)

### ISSUE THREAD

**Issue by ghost** [netdata/netdata#12904]
### Bug description

Had a little trouble switching from the nightly version to the stable version.

### Expected behavior

To go into a `netdata`'s configuration file and switch a setting rather than reinstalling the whole program.

### Steps to reproduce

```shell
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --reinstall
apt update
```

### Installation method

kickstart.sh

### System info

```shell
Linux [username] 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
```

### Netdata build info

```shell
Version: netdata v1.34.1
Configure options:  '--build=aarch64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/aarch64-linux-gnu' '--libexecdir=${prefix}/lib/aarch64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-ebpf' 'build_alias=aarch64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: aarch64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

I am kind surprised that the default setting is not the stable version, but you probably have your reasons. 
Anyhow, a workaround to this is to remove already existing update/repo file with `sudo rm /etc/apt/sources.list.d/netdata-edge.list` and verify the change with `apt update`. I would have tried to make a pull request for this myself, but I am not familiar with any other package management system besides `apt`.

**Comment by Ferroin** [comment]
It’s not properly documented yet, but you actually can switch release channels for native packages without having to use the kickstart script. Our repository configuration is handled as a package itself, so you can use the package manager to switch which repo config is installed.

On a Debian/Ubuntu system with an existing Netdata install, the following should switch from nightly builds to stable builds:

```bash
apt install netdata-repo
```

And this should switch from stable builds to nightlies:

```bash
apt install netdata-repo-edge
```

Similar commands should work on any native package based install, not just Debian/Ubuntu.

Internally, the two packages mutually conflict with each other so that only one gets installed at a given time, so installing one should automatically uninstall the other.

We ideally do need to update our documentation to talk about this properly.

**Comment by zach83** [comment]
Good to know!

**Comment by iigorkarpov** [comment]
The statement about conflicting packages is not really true for RPM. There you can disallow and allow repositories without removing them. I did this when I wrote Ansible playbooks and it works.

**Comment by ilyam8** [comment]
> To go into a netdata's configuration file and switch a setting rather than reinstalling the whole program.

Closing as wontfix.
