### ISSUE TITLE
[Bug]: Charts from sys and proc with repetitive gaps every few seconds

### ISSUE THREAD

**Issue by kryztoval** [netdata/netdata#12914]
### Bug description

Graphs under CPU up to Firewall show constant repetitive gaps that are spaced a couple seconds as can be seen in the image
![image](https://user-images.githubusercontent.com/5733028/168487724-3fc4bd0a-f0f9-415a-9e9a-8b6faf44c277.png)

### Expected behavior

There should be no gaps when collecting the data

### Steps to reproduce

This is my current setup, not sure if there are things that can be interchangeable
1. Armbian Jammy on Raspberry PI 3B+ or PI 4 either of those set up with wired connection
2. Set up netdata
3. Set up wireless connection
4. Remove wired connection

That is it, you should have gaps now.

### Installation method

kickstart.sh

### System info

```shell
Linux bitgreen 5.15.24-bcm2711 #22.02.1 SMP PREEMPT Sun Feb 27 09:03:22 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
/etc/armbian-image-release:BOARD=rpi4b
/etc/armbian-image-release:BOARD_NAME="Raspberry Pi 4"
/etc/armbian-image-release:BOARDFAMILY=bcm2711
/etc/armbian-image-release:BUILD_REPOSITORY_COMMIT=92a1c729d-dirty
/etc/armbian-image-release:VERSION=22.02.1
/etc/armbian-image-release:LINUXFAMILY=bcm2711
/etc/armbian-image-release:ARCH=arm64
/etc/armbian-image-release:IMAGE_TYPE=stable
/etc/armbian-image-release:BOARD_TYPE=wip
/etc/armbian-image-release:INITRD_ARCH=arm64
/etc/armbian-image-release:KERNEL_IMAGE_TYPE=Image
/etc/armbian-image-release:IMAGE_UUID=602e23c6-2bba-47d1-9d72-151ee2255a94
/etc/armbian-release:BOARD=rpi4b
/etc/armbian-release:BOARD_NAME="Raspberry Pi 4"
/etc/armbian-release:BOARDFAMILY=bcm2711
/etc/armbian-release:BUILD_REPOSITORY_COMMIT=92a1c729d-dirty
/etc/armbian-release:VERSION=22.02.1
/etc/armbian-release:LINUXFAMILY=bcm2711
/etc/armbian-release:ARCH=arm64
/etc/armbian-release:IMAGE_TYPE=stable
/etc/armbian-release:BOARD_TYPE=wip
/etc/armbian-release:INITRD_ARCH=arm64
/etc/armbian-release:KERNEL_IMAGE_TYPE=Image
/etc/armbian-release:BRANCH=current
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Version: netdata v1.34.1
Configure options:  '--build=aarch64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/aarch64-linux-gnu' '--libexecdir=${prefix}/lib/aarch64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-ebpf' 'build_alias=aarch64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: aarch64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

My guess is that for some reason a netdata collector times out when collecting the data for the ethernet interface. I am not sure why it does this, it doesn't matter if the ethernet is enabled or disabled, the only thing that matters is that it has a wire and that it is physically linked to another device (I guess a loopback connector would work but I have not tried that yet). I do not understand why this is happening but it was really weird to see.

**Comment by ilyam8** [comment]
Hi, @kryztoval. Can you do the following:

- update to the nightly release.
- check if it has the bug.
- if so - export a [snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot).
- and send it to `ilya@netdata.cloud`.

**Comment by Ferroin** [comment]
> > Hi, @kryztoval. Can you do the following:
> > 
> > * update to the nightly release.
> 
> I am trying but I can't find a way to instal nigthly prebuilt, seems I would have to install from source for this
> 
This is unexpected, we _should_ be publishing usable AArch64 and ARMv7l native packages for Ubuntu 22.04 in the nightlies in addition to stable builds, and even if those do not get pulled in for some reason the ARM static builds should work.

For future reference, with the native packages, you can switch between release channels using the distribution package manager as described here: https://github.com/netdata/netdata/issues/12904#issuecomment-1129110153

**Comment by kryztoval** [comment]
Yeah I did change repositories but the version didn't change from v1.34.1 to anything different but it didn't. I also was expecting something to say it was nigthly in the version name but there was nothing. 

So it seems the v1.34.1 that was installed

 is the nigthly build?

Even then, build-only still had the gaps, v1.34.0-q (followed by a bunch of numbers) also had the gaps and installing from netdata-repo-edge again still has the gaps.

Ok, sending file to the email provided

**Comment by ilyam8** [comment]
@kryztoval for some reason the snapshot has not enough data and the data is only for the last 5 minutes.

Check the 2nd chart under "Netdata Monitoring" -> "proc" section. Some of the proc collectors need more than a second to gather data.

**Comment by kryztoval** [comment]
I exported the last 5 minutes at 1s resolution, otherwise it would export 2 hours at 5second resolution which would obscure the gaps. 

Under netdata monitoring -> proc I can see that netdev is taking an average of 2000 units while all others are between 0 and 7.
![image](https://user-images.githubusercontent.com/5733028/168926242-870d8983-2a5d-4136-b066-d35231239caf.png)

and as soon as I plug in the ethernet cable
![image](https://user-images.githubusercontent.com/5733028/168926333-6a53ce7f-7c8f-4d5a-a31d-19b7dfdc945e.png)
netdev goes down to stay between 0 and 4
![image](https://user-images.githubusercontent.com/5733028/168926389-f22bb6dc-e331-41b7-80a8-985081a35044.png)

Sending you a 2 hour window via email in a minute

**Comment by ilyam8** [comment]
To debug it:

- go to `HOST:19999/netdata.conf`
- find `[plugin:proc:/proc/net/dev]` section. It will show you which files it read:

```ini
[plugin:proc:/proc/net/dev]
	# filename to monitor = /proc/net/dev
	# path to get virtual interfaces = /sys/devices/virtual/net/%s
	# path to get net device speed = /sys/class/net/%s/speed
	# path to get net device duplex = /sys/class/net/%s/duplex
	# path to get net device operstate = /sys/class/net/%s/operstate
	# path to get net device carrier = /sys/class/net/%s/carrier
	# path to get net device mtu = /sys/class/net/%s/mtu
```

The first one contains data for all network interfaces, and the rest (with `%s`) - Netdata reads every one of those files for every network interface (`%s` replaced with the iface name).

- We could check if disabling reading any of the files by:
  - uncommenting the line
  - changing the path to something that doesn't exist

But that is unlikely and we can start by disabling collecting network interfaces (first one then the other):
  - look for `[plugin:proc:/proc/net/dev:%s]` (`%s` is the iface name) sections and:
    - uncommenting the enabled line and change it to no
    - restart Netdata, and see if there are still gaps: if yes, disable the next interface.

**Comment by kryztoval** [comment]
if I do
`time cat /sys/devices/net/enx############/speed`
it takes over 1s and returns a -1 when the wire is unplugged

if I do the same with the wire plugged it takes 0m0.006s
I think that is the query that is timing it out

The weird thing is that it does not take that amount of time all the time, it returns in 0m0.007s some times and then it takes aroind 3.5s to respond other times.

Trying to test if it was always this slow I ran this
`while true; do date -In; time cat /sys/class/net/enx############/speed; done`

Then I filteresd all that had 3 seconds and i got the next section with this format
Line number - iso date
Line number : real from 'time' command
-- = non contiguous lines.

```
23-2022-05-18T17:27:08,788535753+00:00
24:real 0m3.580s
--
205-2022-05-18T17:27:13,396365353+00:00
206:real        0m3.647s
--
377-2022-05-18T17:27:18,061250162+00:00
378:real        0m3.589s
--
543-2022-05-18T17:27:22,686137065+00:00
544:real        0m3.872s
545-2022-05-18T17:27:27,145176543+00:00
546:real        0m3.768s
--
695-2022-05-18T17:27:36,490438680+00:00
696:real        0m3.590s
--
787-2022-05-18T17:27:41,101419468+00:00
788:real        0m3.556s
--
931-2022-05-18T17:27:45,686841125+00:00
932:real        0m3.610s
--
1069-2022-05-18T17:27:50,323796355+00:00
1070:real       0m3.551s
--
1211-2022-05-18T17:27:54,901113421+00:00
1212:real       0m3.552s
--
1363-2022-05-18T17:27:59,473085308+00:00
1364:real       0m3.552s
--
1509-2022-05-18T17:28:04,056407863+00:00
1510:real       0m3.608s
--
1651-2022-05-18T17:28:08,698305982+00:00
1652:real       0m3.575s
--
1769-2022-05-18T17:28:13,297382356+00:00
1770:real       0m3.614s
--
1915-2022-05-18T17:28:17,943431859+00:00
1916:real       0m3.545s
--
2057-2022-05-18T17:28:22,517186653+00:00
2058:real       0m3.612s
--
2191-2022-05-18T17:28:27,150066488+00:00
2192:real       0m3.555s
--
2331-2022-05-18T17:28:31,730258174+00:00
2332:real       0m3.550s
--
2473-2022-05-18T17:28:36,300822881+00:00
2474:real       0m3.652s
--
2615-2022-05-18T17:28:40,983362340+00:00
2616:real       0m3.641s
--
2757-2022-05-18T17:28:45,643238798+00:00
2758:real       0m3.653s
--
2899-2022-05-18T17:28:50,327606737+00:00
2900:real       0m3.641s
--
3041-2022-05-18T17:28:54,990309429+00:00
3042:real       0m3.650s
--
3183-2022-05-18T17:28:59,671765769+00:00
3184:real       0m3.641s
--
3325-2022-05-18T17:29:04,333881121+00:00
3326:real       0m3.652s
--
3473-2022-05-18T17:29:09,003402266+00:00
3474:real       0m3.653s
--
3629-2022-05-18T17:29:13,676210841+00:00
3630:real       0m3.652s
```

Note all the removed lines were from queries with 0m0.006s replies.

**Comment by kryztoval** [comment]
Those are the descriptors that generate delays when the ethernet wire is not plugged it
```
/proc/net/wireless
/sys/class/net/enx############/speed
/sys/class/net/enx############/duplex 

```

**Comment by ilyam8** [comment]
`/proc/net/wireless` too?

**Comment by kryztoval** [comment]
Yes. I checked each of them individually, as long as 1 of those are being queried the gaps will be there.

First I disabled only network, and the gaps were still there, then removed wireless. no more gaps.
Since there is only 1 thing in wireless I went to check it and, sure enough, it also had the same 0.006s response most of the time and then it would take 3.6s to reply.

**Comment by ilyam8** [comment]
So if you

```
[plugin:proc:/proc/net/dev:enx############]
  enabled = no
```

Do you still have gaps because of wireless?

**Comment by kryztoval** [comment]
I did this and I still got gaps. yes.

```
[plugin:proc]
/proc/net/wireless = yes
/proc/net/dev = no
```

**Comment by kryztoval** [comment]
This is the most annoying thing ever. I updated the kernel and wireless does not show gaps on its own now.

So I thouight, what if I create a loop that reads the speed and duplex things and then when it finishes it writes it to a file, in such a way that it can wait for proc to be done without making netdata wait, data would then be read from the cache file instead of being collected every seconds.

But turns out if I attempt to read the value of speed or duplex for an interface that has a carrier of 0 I get the delay and it affects netdata polling as well, system wide, for all proc endpoints. It doesn't matter if I do this query on the filesystem on my own. 

My workaround is to make a small script that checks for the carrier signal for the interface and if it is equal to 1 i read the value and write it to a cache file, this file is the file i configured in netdata.conf.
If the carrier is 0 then I do not even attempt to read speed or duplex at all. For sanity I set them to -1 and unknown respectively in the cache file.

**At this point I know this is not a problem with netdata.** This could be an issue with the network stack, the NIC driver, the kernel, or something else. But certainly not a netdata issue.

Could it be avoided by netdata? Sure if netdata checked for carrier before querying the other descriptors/endpoints. Should netdata do this? I do not think so, however that is not my call.


Dumb command to test
```
while true; do if [ "$(cat /sys/class/net/enx############/carrier)" == "1" ]; then cat /sys/class/net/enxb827eb2f1e57/speed > /tmp/enx############.speed; cat /sys/class/net/enxb827eb2f1e57/duplex > /tmp/enx############.duplex; fi; sleep 0.8; done
```

netdata.conf
```
[plugin:proc:/proc/net/dev]
        path to get net device speed = /tmp/%s.speed
        path to get net device duplex = /tmp/%s.duplex
```

**Comment by kryztoval** [comment]
I agree with this. It may be an isolated case for a specific kernel/device combination. At least this time we know exactly where it is presenting itself so if it appears again affected users have a workaround. 

Thanks for all the help :)
