### ISSUE TITLE
[Feat]: Change `charttype` of the eBPF plugin charts to heatmap

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#12925]
As discussed in the main [issue](https://github.com/netdata/netdata-cloud/issues/265), when we have `heatmaps` available in agent, it will be necessary to change some latency charts like `filesystem`,  and `disk`.

We do not expect to change the plugins logic (at least for eBPF), so we will only change the `charttype`.

**Comment by hugovalente-pm** [comment]
blocked by Fall-back to stacked chart type for charts flagged as heatmaps netdata/dashboard#403

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/issues/12928#issuecomment-1867778288
