### ISSUE TITLE
[Feat]: Change charttype of fping charts to heatmap

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#12928]
### Problem

No heatmap visualization for latency charts

### Description

As discussed in the main https://github.com/netdata/netdata-cloud/issues/265, when we have heatmaps available in agent, it will be necessary to change the fping charts which latency into heatmpas

### Importance

really want

### Value proposition

Correct visualization for this type of charts

**Comment by ilyam8** [comment]
@hugovalente-pm having changes added to the fping plugin will take some time, because we will need:
 - Make a PR to https://github.com/schweikert/fping (fast).
 - Wait until it is merged and a new version is released.

**Comment by ilyam8** [comment]
If by the rest you mean non-fping related - it doesn't block, yes.

**Comment by hugovalente-pm** [comment]
blocked by Fall-back to stacked chart type for charts flagged as heatmaps netdata/dashboard#403

**Comment by ilyam8** [comment]
It looks like this heatmap change is not happening, I am going to close all related issues because there is no value in keeping them open. We can reopen if/when needed.
