### ISSUE TITLE
[Feat]: Change charttype of statds.plugin charts to heatmap

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#12929]
### Problem

No heatmap visualization for latency charts

### Description

As discussed in the main netdata/netdata-cloud#265, when we have heatmaps available in agent, it will be necessary to change the statsd charts with latency metrics (TBC)

### Importance

really want

### Value proposition

Correct visualization for this type of charts

**Comment by thiagoftsm** [comment]
Hello @hugovalente-pm ,

As you can see in our [documentation](https://learn.netdata.cloud/docs/agent/collectors/statsd.plugin), this is a generic collector, so I do not think we can create a statiic list.

Best regards!

**Comment by ilyam8** [comment]
@hugovalente-pm scroll down from https://learn.netdata.cloud/docs/agent/collectors/statsd.plugin#counters

**Comment by hugovalente-pm** [comment]
closed as per the above
