### ISSUE TITLE
[Feat]: Change charttype of idlejitter charts to heatmap

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#12927]
### Problem

No heatmap visualization for latency charts

### Description

As discussed in the main https://github.com/netdata/netdata-cloud/issues/265, when we have heatmaps available in agent, it will be necessary to change the idlejitter chart which measures CPU idle jitter in milliseconds lost per second.

### Importance

really want

### Value proposition

Correct visualization for this type of charts

**Comment by hugovalente-pm** [comment]
blocked by Fall-back to stacked chart type for charts flagged as heatmaps netdata/dashboard#403

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/issues/12928#issuecomment-1867778288
