### ISSUE TITLE
[Feat]: health editor or assistant

### ISSUE THREAD

**Issue by luison** [netdata/netdata#12932]
### Problem

Very happy with netadata features, but I still struggle to edit values for false positive alarms on specific values.
We for example now have a specific disk partition raising an inode time and value alarm. I can't figure out exactly how I should change the health.d configuration file to affect only this specific value that we would like to increase for that partition.
On the previous dashboard I recall having a value with a command that I can find anymore.
In this case I am uncertain if I have to "ignore" that partition on the generic inode health value alarm and the creation a new one, what is the syntax or if should adjust it using the "family" value.
The documentation for editing health is very generic and each plugin/module has different syntax that is not so easy (at least for me) to understand. Assuming netdata is a sysadmin tool help for non so technical staff would be a great improvement.

### Description

A tool perhaps from the dashboard alarms that could generate the syntax to adjust that specific value on the /etc/health.d corresponding file or even better from the interface itself.

Alternatively, any visual tool to debug the user define health adjustments with the current system values to determine which alarms would raise with those with the say... last X hours of data.

### Importance

nice to have

### Value proposition

1. netdata produces too many alerts
2. many of those might be considered false-positives or are least require lower values
3. editing health conf is rather complicates for non pure developers

### Proposed implementation

Any form of assistant to generate health rules modification from the current one.
A debugger so one can test possible configuration against last X hours data so you can determine if that would have ignored o raised one if implemented.

**Comment by ilyam8** [comment]
> A tool perhaps from the dashboard alarms that could generate the syntax to adjust that specific value on the /etc/health.d corresponding file or even better from the interface itself.

I think we can call it done - [Alerts Configuration Manager](https://github.com/netdata/netdata/blob/master/docs/cloud/alerts-configuration-manager.md). This is Cloud feature. 

It will be replaced later with the actual UI editor (health/alarms is a part of dynamic configuration).
