### ISSUE TITLE
[Bug]: There are no alerts for warning even if it already meets the threshold

### ISSUE THREAD

**Issue by jrca025** [netdata/netdata#12944]
### Bug description

I use netdata mainly for monitoring disk space usage. There is 1 monitor that already exceeds the warning threshold but there are no alerts being sent.

![image](https://user-images.githubusercontent.com/89201548/168936779-6162eed1-e73e-4bae-a3ab-8421e0a943fb.png)

### Expected behavior

When threshold is reached for warning/critical level, alerts would be sent

### Steps to reproduce

1. create a disk usage monitor that has at least 80%+ usage
2. observe if alerts would be sent

### Installation method

kickstart.sh

### System info

```shell
Linux VM1 5.4.0-1067-azure #70~18.04.1-Ubuntu SMP Thu Jan 13 19:46:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

### Netdata build info

```shell
Version: netdata v1.33.0-13-g779bc1d64
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by ilyam8** [comment]
Hi, @jrca025. Do you have the alarm raised on the Agent local dashboard (Amarms->Active)?

**Comment by jrca025** [comment]
Hi @ilyam8 where do I find that option in here?

![image](https://user-images.githubusercontent.com/89201548/169008073-e262fdab-7893-460d-898d-2c4bd94e8e2e.png)

**Comment by ilyam8** [comment]
@jrca025 See [Local Agent Dashboard](https://learn.netdata.cloud/docs/agent/web/gui)

**Comment by jrca025** [comment]
@ilyam8 I dont see the (Alarms->Active) option on local dashboard.

However on the netdata.conf

The health section is commented out which means it is active/enabled by default right?

![image](https://user-images.githubusercontent.com/89201548/169013253-af24ced3-84d3-4a48-b331-61d9c54d6743.png)

**Comment by MrZammler** [comment]
Hi @jrca025 

When you are in the local dashboard of the agent, check the upper right corner of the page. It should look like this:

![image](https://user-images.githubusercontent.com/1905463/169041356-17431fbb-a0db-4dc2-9a14-dec38b08b001.png)

Click on either numbers and you'll get the current raised alerts for that agent.

**Comment by MrZammler** [comment]
Hi! Ok, it will actually trigger a WARNING after 90%.

The part there on the alert config says that if the current status is WARNING or CRITICAL, then trigger a WARNING after 80%, else trigger it after 90.

If you wish you can [create](https://learn.netdata.cloud/docs/monitor/configure-alarms) a custom alert from this, and use your own thresholds.

**Comment by jrca025** [comment]
Hi @MrZammler thank you for this. Can I just modify this existing config so it can fit my expectations?

- Send a warning when usage > 80% 
- Send a critical alert when usage > 90%

warn: $this > 80
  crit: $this > 90

**Comment by MrZammler** [comment]
Sure!

If you follow the link above, using `edit-config health.d/disks.conf`, you will make a copy of this alert config in your /etc/netdata/health.d/ folder. Edit the numbers then to reflect your choice. Most likely you want:

`warn: $this > (($status >= $WARNING ) ? (70) : (80))`
`crit: $this > (($status == $CRITICAL) ? (80) : (90))`

So that's going to trigger a WARNING from a CLEAR when 80%, will keep it until it falls under 70% and a critical will be over 90% and keep it until it falls under 80%.

**Comment by jrca025** [comment]
Thanks for this @MrZammler

**Comment by ilyam8** [comment]
>  it will actually trigger a WARNING after 90%.

> The part there on the alert config says that if the current status is WARNING or CRITICAL, then trigger a WARNING after 80%, else trigger it after 90.

See [Special use of the conditional operator](https://learn.netdata.cloud/docs/agent/health/reference#special-use-of-the-conditional-operator)
