### ISSUE TITLE
[Feat]: Show UPS load in watts

### ISSUE THREAD

**Issue by crafty35a** [netdata/netdata#12959]
### Problem

There is no way to track actual power consumption.

### Description

Currently, Netdata graphs UPS load in percent (this is APCUSD's LOADPCT value). It would be really handy to also see load in watts. Here is how UnRAID shows it: ![image](https://user-images.githubusercontent.com/1082003/169289929-5bce7268-28ff-4dd8-bf14-dae68308965c.png)

Although APCUPSD does not provide this value, it's just a simple calculation of LOADPCT multiplied by [NOMPOWER](http://www.apcupsd.org/manual/#:~:text=NOMPOWER). This would give us a way to easily track actual power consumption over time.

### Importance

really want

### Value proposition

1. Ability to view actual server power draw, and track it over time
2. Easily use this data to track electricity costs to run a server

**Comment by ilyam8** [comment]
@crafty35a, hi 👋 Can you show the output of `apcaccess status <IP>`?

**Comment by crafty35a** [comment]
> @crafty35a, hi 👋 Can you show the output of `apcaccess status <IP>`?

No problem! Here it is:
````
root@Tower:~# /sbin/apcaccess status
APC      : 001,032,0754
DATE     : 2022-05-19 15:08:52 -0400
HOSTNAME : Tower
VERSION  : 3.14.14 (31 May 2016) slackware
UPSNAME  : Tower
CABLE    : USB Cable
DRIVER   : USB UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2022-05-17 16:35:33 -0400
MODEL    : CP1000PFCLCDa
STATUS   : ONLINE
LINEV    : 122.0 Volts
LOADPCT  : 15.0 Percent
BCHARGE  : 100.0 Percent
TIMELEFT : 45.0 Minutes
MBATTCHG : 25 Percent
MINTIMEL : 10 Minutes
MAXTIME  : 0 Seconds
OUTPUTV  : 122.0 Volts
DWAKE    : -1 Seconds
LOTRANS  : 100.0 Volts
HITRANS  : 139.0 Volts
ALARMDEL : 30 Seconds
NUMXFERS : 0
TONBATT  : 0 Seconds
CUMONBATT: 0 Seconds
XOFFBATT : N/A
SELFTEST : NO
STATFLAG : 0x05000008
SERIALNO : CX1LW7003492
NOMINV   : 120 Volts
NOMPOWER : 600 Watts
END APC  : 2022-05-19 15:08:54 -0400

````

**Comment by ilyam8** [comment]
@crafty35a can you test #12965?

**Comment by crafty35a** [comment]
> @crafty35a can you test #12965?

Absolutely - do I just wait for a new edge build to show up on docker hub?

**Comment by ilyam8** [comment]
@crafty35a I created a docker image from my branch, use it for testing: `ilyam8/netdata-test-for-github`. It is built for the Linux platform only, if you need different - just say and I'll make it multiarch.

**Comment by crafty35a** [comment]
Seems to be working great, thank you very much!
![image](https://user-images.githubusercontent.com/1082003/169524900-606bd156-35da-4cf9-8062-e99fca4654ff.png)

**Comment by ilyam8** [comment]
Nice, don't forget to switch back to netdata/netdata after the PR is merged 😄

**Comment by ilyam8** [comment]
The changes will be in today's nightly release.
