### ISSUE TITLE
[Feat]: BigQuery exporting

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#12957]
### Problem

I would like to be able to export my data to Google BigQuery using the [netdata exporting engine](https://learn.netdata.cloud/docs/agent/exporting)

### Description

I would like to just be able to configure BigQuery like any of the other supported methods listed [here](https://learn.netdata.cloud/docs/agent/exporting#integration)

### Importance

really want

### Value proposition

1. Easy long term storage in a modern managed data lake like BigQuery.
2.
3.
...

### Proposed implementation

I believe this BQ api should be able to enable and handle this: https://cloud.google.com/bigquery/docs/write-api and there is also a go library too: https://pkg.go.dev/cloud.google.com/go/bigquery/storage/managedwriter

**Comment by PanosJee** [comment]
I think a PubSub export is what you need ([where you can now have a BigQuery subscription](https://cloud.google.com/blog/products/data-analytics/pub-sub-launches-direct-path-to-bigquery-for-streaming-analytics))
