### ISSUE TITLE
[Bug]: tmp/netdata-kickstart.sh: 342: arithmetic expression: expecting primary: ""  ERROR  Installer exited unexpectedly (0-)

### ISSUE THREAD

**Issue by ewlikodjo** [netdata/netdata#12960]
### Bug description

I'm trying to install netdata on my kali 

### Expected behavior

/tmp/netdata-kickstart.sh                                       [  <=>                                                                                                                                    ]  74.57K   364KB/s    in 0.2s    

2022-05-19 19:18:14 (364 KB/s) - ‘/tmp/netdata-kickstart.sh’ saved [76362]

/tmp/netdata-kickstart.sh: 342: arithmetic expression: expecting primary: ""
 ERROR  Installer exited unexpectedly (0-)

### Steps to reproduce

1.
2.
3.
...
1

### Installation method

kickstart.sh

### System info

```shell
kali linux
```

### Netdata build info

```shell
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token mIg20bIiZcUwXZ6K3wmvsxXaKUdM5de9rzgabgEh7Z3vSGKwcp6NhnGNbnc2_vMMObGZv9MNmrFkyigOu2dHc9AmT6RCsCIaYximIiICxFGeegsF8IqRfOQxt0493h-3fuLgAxE --claim-url https://app.netdata.cloud
--2022-05-19 19:18:13--  https://my-netdata.io/kickstart.sh
```

### Additional info

please help

**Comment by IslamAlam** [comment]
I am having the same issue in Ubuntu too:

    
    wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
    --2022-05-20 14:45:41--  https://my-netdata.io/kickstart.sh
    Resolving my-netdata.io (my-netdata.io)... 188.114.96.10, 188.114.97.10, 2a06:98c1:3120::a, ...
    Connecting to my-netdata.io (my-netdata.io)|188.114.96.10|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: unspecified [application/octet-stream]
    Saving to: ‘/tmp/netdata-kickstart.sh’
            
    /tmp/netdata-kickstart.sh       [ <=>                                        ]  74.57K  --.-KB/s    in 0.03s   
    
    2022-05-20 14:45:41 (2.23 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [76362]
    
    Illegal instruction
    /tmp/netdata-kickstart.sh: 342: /tmp/netdata-kickstart.sh: arithmetic expression: expecting primary: ""
    ERROR  Installer exited unexpectedly (0-)
    
    This is almost certainly the result of a bug. If you have time, please report it at https://github.com/netdata/netdata/issues/new/choose.
