### ISSUE TITLE
[Bug]: No data retention in parent Agent with an older version child on OpenWRT

### ISSUE THREAD

**Issue by odynik** [netdata/netdata#12962]
### Bug description

User has Netdata running on a Debian machine (v1.34) and setup for dbengine, user has netdata on an Openwrt X86 router (still on v1.30). webUI and local metrics are disabled.

It seems to be streaming fine to the Linux machine but not getting any history stored/recalled from the dbengine it seems.
dbengine disk space and dbengine multihost disk space has been configured. Don't want to store metrics on the router due to limited disk space

Summary of technical info
#### Parent
OS: Debian
Netdata: v1.34

#### Child
OS: OpenWRT 
Netdata: v1.30
Installation method: OpenWRT

### Expected behavior

User was expecting to see the historic values collected from the child Netdata agent to the parent Netdata agent.

### Steps to reproduce

1. Versions need to set-up the same architecture and test it.
2.
3.
...

### Installation method

other

### System info

```shell
Debian - v1.34
OpenWRT - v1.30
```

### Netdata build info

```shell
Debian - v1.34
OpenWRT - v1.30
```

#### Parent netdata.conf
```
[global]
	memory mode = dbengine
	 page cache size = 32
         dbengine disk space = 22560
	 dbengine multihost disk space = 22560
	 memory deduplication (ksm) = yes
[web]
          allow netdata.conf from = localhost
```
#### Parent stream.conf
```
[API_KEY_OPENWRT]
    enabled = yes
    default memory mode = dbengine
    memory mode = dbengine
```

#### Child netdata.conf
```
[global]
        update every = 2
        memory deduplication (ksm) = no
        debug log = syslog
        error log = syslog
        access log = none
        run as user = root
        memory mode = none

[web]
        mode = none
        allow connections from = localhost  and some IPs
        allow dashboard from = localhost and some IPs

[plugins]
        cgroups = no
        apps = no
        charts.d = no
        fping = no
        node.d = no
        python.d = no

[health]
        enabled = no

[plugin:proc:ipc]
        shared memory totals = no
```

#### Child stream.conf
```
[stream]
enabled = yes
```

**Comment by dragon2611** [comment]
I think its working with the openwrt end on 1.34, I restarted both nodes and the data from about 16:10 Yesterday onward was still showing.

**Comment by odynik** [comment]
Nice !!! 🚀 
Thank you @dragon2611 for reporting the issue.
