### ISSUE TITLE
[Bug]: kernel: ... traps: netdata[...] general protection fault ip

### ISSUE THREAD

**Issue by iredmail** [netdata/netdata#13004]
### Bug description
netdata failed to start and log these lines:
```
May 24 07:07:12 host systemd[1]: netdata.service: Service hold-off time over, scheduling restart.
May 24 07:07:12 host systemd[1]: netdata.service: Scheduled restart job, restart counter is at 2425.
May 24 07:07:12 host systemd[1]: Stopped Real time performance monitoring.
May 24 07:07:12 host systemd[1]: Starting Real time performance monitoring...
May 24 07:07:12 host systemd[1]: Started Real time performance monitoring.
May 24 07:07:12 host kernel: [74582.899970] traps: netdata[8614] general protection fault ip:58f010 sp:7ffdd906a650 error:0 in netdata[401000+7a1000]
May 24 07:07:12 host systemd[1]: netdata.service: Main process exited, code=dumped, status=11/SEGV
May 24 07:07:12 host systemd[1]: netdata.service: Failed with result 'core-dump'.
```

### Expected behavior

netdata service starts normally.

### Steps to reproduce

1. Download the latest `.gz.run` package
2. Install with command `./netdata-v1.34.1.gz.run --accept`.

Note: tried netdata versions: 1.34.1, 1.34.0, 1.33.1.

### Installation method

other

### System info

```shell
# uname -a; grep -HvE "^#|URL" /etc/*release
Linux host.example.com 5.4.0-1072-aws #77~18.04.1-Ubuntu SMP Thu Apr 7 21:38:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.6 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.6 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

### Netdata build info

```shell
# /opt/netdata/bin/netdata -W buildinfo
Version: netdata v1.33.1
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=-static -O3 -I/openssl-static/include' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: manual-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```
```


### Additional info

_No response_

**Comment by MrZammler** [comment]
Hi @iredmail thank you for your report.

We will try to reproduce the issue. Is it possible to check with `coredumpctl` utility for any core dumps kept by systemd?

Also if possible, can you share the `error.log` file?

Is this a new, fresh install? Or has this happened after an update?

Thanks!

**Comment by iredmail** [comment]
> We will try to reproduce the issue. Is it possible to check with `coredumpctl` utility for any core dumps kept by systemd?

Didn't find any coredump files (under `/var/lib/systemd/coredump`).

> Also if possible, can you share the `error.log` file?

Here it is: https://pastebin.com/fME8bfRJ

> Is this a new, fresh install? Or has this happened after an update?

Not a fresh install.

It ran an old netdata release before, then i just upgrade it (`./netdata-v1.34.1.gz.run --accept`) with the latest 1.34.1. As mentioned in first post, i also tried 1.34.0, 1.33.1, neither works.

**Comment by MrZammler** [comment]
Ok, thanks!

There is something we can try, but this unfortunately might mean that the agent will start with a clean state of metrics. (But we need to do it to check if that's the problem).

Can you please rename the folder `/opt/netdata/var/cache/netdata/dbengine` to e.g. `/opt/netdata/var/cache/netdata/dbengine_old` ? (dbengine is where the metrics are held. The `error.log` suggests it might fail while trying to read them).

We won't delete your old dbengine files, just want to see if it's there where the problem can be.

Thanks!

**Comment by iredmail** [comment]
It works after renamed the folder. :)

**Comment by MrZammler** [comment]
Nice, glad to hear it! One favor though, if possible.

Can you please pack the contents of the dbengine_old folder (not sure of the total size) and maybe forward them to manolis at netdata dot cloud? Not sure if they will fit an email, perhaps not...

**Comment by iredmail** [comment]
Too late, I removed it. :(
