### ISSUE TITLE
Setup PPA for Debian systems

### ISSUE THREAD

**Issue by facetoe** [netdata/netdata#1302]
I saw your comment @ktsaou on Reddit regarding setting up a PPA (https://www.reddit.com/r/linuxadmin/comments/5fkxan/netdata_the_cli_killer_for_linux_performance/dal313l/). I'd be happy to look into hosting this on one of my servers this weekend.

**Comment by ktsaou** [comment]
perfect!

I don't know how to build the package though. We need to provide a post installation script to take care of certain things and somehow let the user know of (or somehow, safely install) updated configuration files.

Ideally, I would like to provide something like a "nightly" build, or something that can be hooked to github and update the package on the ppa on every commit to the master branch of this repo.

**Comment by facetoe** [comment]
Sounds good. Debian packages have a concept of pre and post install scripts and there is already a mechanism for dealing to changes to configuration files so that should be easy enough. For some reason I was under the impression that someone had already created the structure necessary for building .deb files however I can't seem to find this in the repo. Do you know if anyone has done this work yet? 

I like the idea of a nightly build. I'll have a go at building this and commit all the code in a separate repo, that way you have the option of hosting the PPA and debian infrastructure yourself or letting someone else do the hosting.

**Comment by ktsaou** [comment]
@lhw @FedericoCeratto take care of the debianization of netdata. Check #651.
I think most of their work is in `contrib/debian`.

**Comment by facetoe** [comment]
Ahh my bad, shouldn't post before finishing my morning coffee!

**Comment by FedericoCeratto** [comment]
@ktsaou actually it's on https://anonscm.debian.org/git/collab-maint/netdata.git

**Comment by ktsaou** [comment]
@FedericoCeratto thanks!
Is there anything to change at the main repo? I see only the changelog has changed. Right?

**Comment by facetoe** [comment]
Ok @ktsaou I've made some progress here. Current plan is as follows:

#### Nightly build
*  push made to master
*  kicks off Github Webhook to post to hosting server
*  Apache routes request to simple python program
    - pull master
    - build new package
    - snapshot current repo with aptly (https://www.aptly.info/)\
    - publish latest version with aptly to the `testing` component
 
#### Major Release
As above, however the release is published to the `stable` component

I need to test the Github Webhooks and write the little Python program but I've got the basics working manually. 

I'll document the installation process as a guide so you are able to reproduce it if necessary. 

Let me know if you can see any problems with the current plan!

**Comment by FedericoCeratto** [comment]
@ktsaou If you are referring to the differences between https://anonscm.debian.org/git/collab-maint/netdata.git and contrib/debian - I haven't been porting the changes back into contrib/debian so they might be quite different.
The contents of contrib/debian are not being used during the package build.

**Comment by ktsaou** [comment]
@facetoe I agree - all these would be great. Do you want me to setup a VPS on digitalocean for this?
I will need your public SSH key (send it to costa@tsaousis.gr).

Keep in mind I am also experimenting with opensuse OBS to build RPM based packages, thanks to @breed808 (https://github.com/firehol/netdata/issues/1306#issuecomment-265449699). If you send me your SSH public key, I'll add you to the OBS VPS setup there.

OBS works (thank you very much @breed808), but I need to test all these packages on every system. I have setup multiple lxc-based containers here for most distros, to test them, but I haven't found the time yet to complete it.

There is also a PR that affects the `netdata.spec` file: #1345 issued by @breed808 and under review by @alonbl (who created all the autoconf structure of netdata). This is an attempt to add opensuse support of the `spec` file.

The truth is that I am little lost with all these, so if you have some time to spare organizing them, It would be great help.

**Comment by facetoe** [comment]
@FedericoCeratto would it be possible to merge any changes you've made back into `contrib/debian`? If I set up a nightly build as proposed it would make sense to build the packages in the same way. 

@ktsaou I've emailed you my public key. I wouldn't worry about a VPS as yet as I'd like to look into OBS first - it sounds interesting. If we can get it building packages for multiple distros that would be a great help in keeping all the packaging stuff organized. I should have a solid block of time this weekend to work on it.

**Comment by breed808** [comment]
@facetoe if you need any help with the OBS I'm happy to assist, though my experience is more on the RPM packaging side.

**Comment by facetoe** [comment]
Awesome thanks @breed808, I'll hit you up if I get stuck!

**Comment by FedericoCeratto** [comment]
@facetoe I can send a PR, otherwise you can also build straight from the
Debian git repo

**Comment by facetoe** [comment]
@FedericoCeratto doesn't the Debian git repo lag behind master?

**Comment by ktsaou** [comment]
@facetoe I added your key to the VPS @breed808 has installed the OBS script (`setup_buildserver.sh` in `/root`).

Login with `ssh root@139.59.161.10`. Short instructions provided by @breed808 here: https://github.com/firehol/netdata/issues/1306#issuecomment-265449699

**Comment by ktsaou** [comment]
and, I have tested it. It works, but I haven't tested the RPM packages yet.

**Comment by facetoe** [comment]
Awesome thanks @ktsaou. I'll have a go at getting the OBS to produce Debian packages tonight. 

With testing the packages, that sounds like something that would be handy to automate. Were you just installing each package into a suitable container and then checking that netdata responds on 19999? If there was more to it let me know. I'll look at automating the testing of packages against the various distros.

**Comment by ktsaou** [comment]
Well, the package installation should go through a series of steps:

1. create the `netdata` user and group
2. if the `docker` is available, add user `netdata` to the `docker` group
3. install the netdata files and make sure they have the proper permissions
4. make sure `setcap` is used on apps.plugin (or setuid to root if `setcap` does not work)
5. install the proper start-up file
6. install the logrotate configuration
7. install an empty `/etc/netdata/netdata.conf`

Then we have 2 issues, which I am not sure how they should be handled:

1. package dependencies. netdata normally depends on `zlib`, `libuuid`, `curl` and `bash`, but a lot more packages may be required based on the features the user is willing to use.

2. configuration files should be preserved during a netdata update, but if the existing configuration files have not been edited by the user, they should be just overwritten. `netdata-installer.sh` has md5 hashes of all configuration files shipped with netdata, so it knows if a configuration file is just a stock version or not. If it is, it overwrites it. If it is not, it keeps it. In all cases, it installs a `.conf.orig` file to let the user have the latest version of the config file.

**Comment by ktsaou** [comment]
all these decisions are already handled by `netdata-installer.sh`, so I can work you through them. But I am not sure how they be handled in a packaged version of netdata.

**Comment by breed808** [comment]
> Well, the package installation should go through a series of steps:
> 
> 1. create the netdata user and group
> 2. if the docker group is available, add user netdata to the docker group
> 3. install the netdata files and make sure they have the proper permissions
> 4. make sure setcap is used on apps.plugin (or setuid to root if setcap does not work)
> 5. install the proper start-up file
> 6. install the logrotate configuration
> 7. install an empty /etc/netdata/netdata.conf
> 
Some of these are already covered by the spec file and possibly in the Debian contrib area (E.G. netdata user/group, file & permissions, logrotate) and the other can be added fairly easily.
The difficult entry might be the docker group, as the DEB/RPM packages can only detect and/or create a docker group on installation or upgrade.

> Then we have 2 issues, which I am not sure how they should be handled:
> 
> package dependencies. netdata normally depends on at least zlib and libuuid. curl, python and bash should also be there (but not required), A lot more packages may be required based on the features the user is willing to use.

Both the DEB and RPM families support 'hard' runtime dependencies, which will force all users to install specified packages as dependencies.
They have differing levels of support for 'soft' dependencies:

- [Depends, Recommends, Suggests, Enhances, Pre-Depends for DEB packages](https://www.debian.org/doc/debian-policy/ch-relationships.html)

- [Recommends and Suggests for RPM packages](https://fedoraproject.org/wiki/Packaging:WeakDependencies)

Personally I think it would be easier to cover everything under hard runtime dependencies, though some users may object having to install all possible dependencies regardless of usage.

> configuration files should be preserved during a netdata update, but if the existing configuration files have not been edited by the user, they should be just overwritten. netdata-installer.sh has md5 hashes of all configuration files shipped with netdata, so it knows if a configuration file is just a stock version or not. If it is, it overwrites it. If it is not, it keeps it. In all cases, it installs a .conf.orig file to let the user have the latest version of the config file.
> 
This is fairly easy to implement, RPM spec files have `%config(noreplace)` which will replace unmodified config files, or save a `$FILENAME.rpmnew` config file in the same directory if the config file has been modified.
DEB packages list package config files in the [conffile](https://www.debian.org/doc/debian-policy/ch-files.html#s-config-files) file. `apt/apt-get/aptitude` will prompt a user if they wish to overwrite or keep a config file when upgrading the package.

**Comment by ktsaou** [comment]
ok. I just need to add that `/var/lib/netdata` and `/var/cache/netdata` have to be created.

**Comment by ktsaou** [comment]
@facetoe are you working on this? There is no pressure. I just would like to know if I have to seek for help on setting up a PPA and/or OBS...

**Comment by facetoe** [comment]
@ktsaou sorry I've been flat out lately at work and haven't had a chance to do any work on this. It's all good if you want to seek additional help, more than one of us can work on the various problems at a time. 

Realistically I doubt I will be able to do any work on this until after Christmas. I do have a few weeks off work around there though so should be able to get some work done on the PPA/OBS stuff.

**Comment by ktsaou** [comment]
Perfect. I am looking forward for your work after Christmas!

**Comment by FedericoCeratto** [comment]
@facetoe the Debian repo contains the debian/ directory, it's not meant to replicate netdata's repo, and it's used to build the official Debian package.

**Comment by paulkatsoulakis** [comment]
We have issue #5963 that is our initial round of repositories implementation, together with automations that will allow us to publish our own set of packages for the various distributions we support.

In this first round, we focus on establishing the necessary infrastructure and automations, while we reuse our existing content for spec files and packaging configs that we have built with the help of our community.  There will be also a round of improvements on these configurations and of course many more iterations to get ourselves at an enterprise level state regarding packaging.

Your help has been key in all these initiatives, as we value our community and we drive our goals to serve community needs.  Do not hesitate to provide any inputs or insights on #5963, any help is valued and appreciated!
