### ISSUE TITLE
[Feat]: Mirroring Debian package repos fail due to duplicate file names.

### ISSUE THREAD

**Issue by ValorousSalmon** [netdata/netdata#13029]
### Problem

My institution maintains a local debian repository that contains mirrors of mutlple releases, for ease of controlling patch cycles on our test/dev/prod servers.

While attempting to mirror the Netdata repos for Debian Stretch, Buster, and Bullseye (9, 10, 11) using aptly, I received an error: 

`ERROR: unable to publish: unable to process packages: error linking file to ...../pool/main/n/netdata/netdata_1.34.1_amd64.deb: file already exists and is different`

This is because all three of these debian releases are using the exact same file names for their packages.

### Description

According to Debian repository rules found here:

https://wiki.debian.org/DebianRepository/Format?action=show&redirect=RepositoryFormat#Duplicate_Packages

"A repository must not include different packages (different content) with the same package name, version, and architecture."

This is due to the structure of how an official Debian repository works. packagecloud.io seems to get around this by faking the repo structure at request time so there are no filename conflicts. However, for those of us trying to mirror more than one release into a standard format repository, we end up with filename conflicts.

In short - you're not supposed to use the same file name - "netdata_1.34.1_amd64.deb" - for multiple releases.

### Importance

really want

### Value proposition

Fixing this will help people who mirror multiple releases of debian repositories. I'd hazard Ubuntu as well, but I can't test that.

Unfortunately, I don't know if the filenames are a product of packagecloud.io service, or if the Netdata project has control over them.

Our local mirrors allows us to update our repository once, and ensure that there are no package version differences between dev and prod, even though the two environments may be updated several weeks apart.

### Proposed implementation

Unless I'm mistaken, making the package filenames unique by simply adding the debian version it was built on/for will solve the problem with the least impact.

I am not a debian maintainer, and I couldn't find any filename convention rules that would be applicable, but I believe using something like:  

`netdata_1.34.1+deb10_amd64.deb`

should do the job.

This would need to be done to all packages in the release to avoid naming conflicts.

**Comment by Ferroin** [comment]
Long term we probably want this internally anyway, as it should make finally transitioning off of PackageCloud to our own repo infrastructure much easier.

As of right now we’re just publishing the packages with the names they get given by Debian’s own package build infrastructure (`dpkg-buildpackage` and associated tooling), so it should be relatively easy to just rename them prior to upload.

**Comment by Ferroin** [comment]
PR is up to fix this in future packages, but we have no practical way currently to correct existing package file names on PackageCloud.

As mentioned above, we have plans in the works to move to self-hosting our repos, and if we still have any packages sitting around at that point that need their names fixed, catch them then.

**Comment by ValorousSalmon** [comment]
Excellent news! Once the new packages get published with non-colliding filenames, I don't believe the existing packages will be a problem, at least for our mirroring purposes. Thanks!

**Comment by ValorousSalmon** [comment]
@Ferroin I assume we're due for another stable release soon - any chance we'll see this fix in place at that time?

**Comment by Ferroin** [comment]
I’m hoping to get this fixed in time for the release at the end of the month, but I’ve not had time to actually dig into this yet, so it unfortunately may not be fixed by then.

**Comment by Ferroin** [comment]
Quick update: We’re in the process of moving our DEB package hosting to new self-hosted infrastructure, and plan to resolve this properly as part of that move. Current estimate is some time by the end of Q1 2023 at the latest.

**Comment by Ferroin** [comment]
With the merge of #14290 and #14301, this should be resolved. All of our DEB packages on our current infrastructure should have distro-specific tags in the version information so that they do not conflict.

If this is still an issue, please comment here and I’ll reopen it.
