### ISSUE TITLE
Re-evaluate the default value for "host anomaly rate threshold"

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13050]
Currently `host anomaly rate threshold` is set to `0.01` by default.

This means that if more than 1% of dimensions are anomalous at the same time then the host itself is considered in an anomalous state. 

Reasons for re-evaluation
- 1% seems a bit low, and we maybe risking background noise levels of anomaly rate triggering anomaly events
- Now that the feature has been released, we can actually analyze a few real world scenarios and see what the background anomaly rate looks like and what (if any) a more suitable default for `host anomaly rate threshold` should be. 

See example of anomaly rate = 1.5% triggering anomaly events - in this particular case this turned out to be noise

![image](https://user-images.githubusercontent.com/24860547/171497208-ca5204bf-cdc0-44a6-b4bc-33e3dda86ef5.png)

**Comment by shyamvalsan** [comment]
From what I can see on production, in almost every case where I drill down into an anomaly rate spike (where anomaly rate < 2%) the resultant anomalous metrics are pure noise and not really telling me anything interesting.

**Comment by shyamvalsan** [comment]
Let's update `host anomaly rate threshold` to 0.02 on staging and doing a comparative study?  @vkalintiris @andrewm4894

**Comment by shyamvalsan** [comment]
After a few days of observing production and staging - I think it would be safe bet to update the default value `host anomaly rate threshold` to `0.02 `

thoughts? @vkalintiris @andrewm4894

**Comment by vkalintiris** [comment]
> thoughts? @vkalintiris @andrewm4894

Fine by me.
