### ISSUE TITLE
[Bug]: Installation error - deal looping

### ISSUE THREAD

**Issue by William8Work** [netdata/netdata#13063]
### Bug description

I tried to install netdata on my ubuntu 20.04 machine but the installation was kept looping.

In file included from ml/kmeans/dlib/dlib/all/../dnn/../matrix.h:11,
                 from ml/kmeans/dlib/dlib/all/../dnn/tensor.h:8,
                 from ml/kmeans/dlib/dlib/all/../dnn/cpu_dlib.h:9,
                 from ml/kmeans/dlib/dlib/all/../dnn/cpu_dlib.cpp:8,
                 from ml/kmeans/dlib/dlib/all/source.cpp:82:
ml/kmeans/dlib/dlib/all/../dnn/../matrix/matrix_la.h: In function 'long int dlib::svd4(dlib::svd_u_mode, bool, const dlib::matrix_exp<EXP>&, dlib::matrix<typename EXP::type, uM, uN, MM1, L1>&, dlib::matrix<typename EXP::type, qN, qX, MM2, L1>&, dlib::matrix<typename EXP::type, vM, vN, MM3, L1>&) [with EXP = dlib::matrix_op<dlib::op_trans<dlib::matrix_op<dlib::op_trans<dlib::matrix<double, 1, 2> > > > >; long int qN = 1; long int qX = 1; long int uM = 1; long int uN = 1; long int vM = 2; long int vN = 1; MM1 = dlib::memory_manager_stateless_kernel_1<char>; MM2 = dlib::memory_manager_stateless_kernel_1<char>; MM3 = dlib::memory_manager_stateless_kernel_1<char>; L1 = dlib::row_major_layout]':
ml/kmeans/dlib/dlib/all/../dnn/../matrix/matrix_la.h:225:32: warning: iteration 1 invokes undefined behavior [-Waggressive-loop-optimizations]
  225 |             y = abs(q(i)) + abs(e(i));
      |                             ~~~^~~~~~
ml/kmeans/dlib/dlib/all/../dnn/../matrix/matrix_la.h:163:20: note: within this loop
  163 |         for (i=0; i<n; i++)
      |                   ~^~

### Expected behavior

I ran this command and it should finish the installation properly:

wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token 35TqeAhSN_qwP6bU2W0JVq5qthzxx8S1mYn40ciXVW2bETOXCWkA6v-WMfSAe1fs6sSxSifpAJpNw3V9y9XL2JMMPGGs7cSYxGX_1WODMPQL0IjYDJgaczVEtUged-p-KsEP-YI --claim-url https://app.netdata.cloud

### Steps to reproduce

1. Run the wget command
2. See the error
3.
...

### Installation method

kickstart.sh

### System info

```shell
Linux g1wrk08 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.3 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.3 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
the installation was not successful.
```

**Comment by MrZammler** [comment]
Hi @William8Work ! Sorry for the (very) late reply.

Does this error occur still? Have you tried recently? Can you retry please and paste the whole command output?

Thanks!

**Comment by Ferroin** [comment]
Closing this due to no response. If we get a response to the above request for more information, we will reopen it.
