### ISSUE TITLE
[Bug]: fping charts shouldn't have the hostname

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13068]
### Bug description

https://github.com/netdata/netdata/issues/12641 was closed, but the issue with `fping` remains. If the maintainer in https://github.com/schweikert/fping/pull/253 doesn't merge the PR, we should source it or find another way to handle the issue. 

### Expected behavior

No hostname on fping charts

### Steps to reproduce

1.
2.
3.
...

### Installation method

kickstart.sh

### System info

```shell
-
```

### Netdata build info

```shell
-
```

**Comment by ilyam8** [comment]
Fixed in https://github.com/netdata/cloud-frontend/issues/3510
