### ISSUE TITLE
[Feat]: Vendor libJudy in our source tree.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#13086]
### Problem

We are increasingly dependent on Judy for features and performance. However, it’s abandonware, and is not universally packaged. Right now, we’re functionally vendoring it when needed by handling things in the install script. However, this approach has a number of issues:

- Due to how our CI works, it means everything has to build successfully without Judy available, even though we almost never actually install without it.
- Build issues with Judy are functionally build issues for all of Netdata, but the current situation means that they generally get punted to the agent SRE team who are not well equipped to handle them.
- It’s still possible for users to build without Judy at all.

### Description

Instead of relying on the somewhat shaky bundling code in the installer code, we should vendor the libJudy code directly in our source tree, much like we’re doing for SQLite3.

### Importance

blocker

### Value proposition

1. Judy will always be available for any features that require it, independent of what the system may provide.
2. dbengine support will always be available as an option.
3. Build issues with Judy can be fielded more directly by the agent team, instead of the agent SRE team, allowing for a better quality of support.

**Comment by underhood** [comment]
#13362
