### ISSUE TITLE
[Bug]: `netdata` user is not added to desired groups when installing using native packages

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#13090]
### Bug description

There is a [list of user groups](https://github.com/netdata/netdata/blob/86b979aaadbe3f2c2358f3dc76d2fcd60b51d5d4/packaging/makeself/install-or-update.sh#L107) we want `netdata` user to be added (e.g `adm` to read NGINX/Apache web server logs).

We do it when using:

 - build from the source.
 - static build.

### Expected behavior

`netdata` user is added to desired groups when installing using native packages.

### Steps to reproduce

1. install Netdata using native packages on a host that has at least one of the desired user groups
2. run `id netdata`

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux deb-work 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.34.0-289-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by iigorkarpov** [comment]
This can be a tricky thing to implement. These groups will be different for different versions of different distributions. Though currently we provide relatively small set.

**Comment by iigorkarpov** [comment]
I will look at it first thing tomorrow.

**Comment by iigorkarpov** [comment]
Is this true for both RPM. and DEB? On which systems was this tested?

**Comment by ilyam8** [comment]
Debian 11.

**Comment by iigorkarpov** [comment]
Thanks. Then I'll start with DEB. Any info on RPM?

**Comment by iigorkarpov** [comment]
Also, I was once told that collectors that require special access rights run with sudo/doas, etc... Is that not true?

**Comment by iigorkarpov** [comment]
Just an idea. Wouldn't it make more sense to use the uniform approach for all collectors?

**Comment by ilyam8** [comment]
I am not sure what you mean, but this discussion doesn't belong to this issue.

**Comment by Ferroin** [comment]
@iigorkarpov Things are mostly uniform right now. C code and other compiled code utilizes either SUID or capabilities to get the right permissions, while the scripts (which do not work with SUID or filesystem capabilities) utilize `sudo` (though it would be great if we could properly support other elevation mechanisms there).

**Comment by ilyam8** [comment]
I tried to find an answer myself. The only manipulation we do with `netdata` user:

https://github.com/netdata/netdata/blob/4c64b8ea4ff720d946bbb9a11ca7474c5673bb6c/netdata.spec.in#L450-L455

If I am not missing something - the issue is not fixed for RPM.

**Comment by iigorkarpov** [comment]
I worked only with DEB. The issue was closed automatically.

But I checked installation on Rocky Linux 8. Netdata user was added to 
```
adm:x:4:netdata
nobody:x:65534:netdata
netdata:x:988:
docker:x:987:netdata
```

**Comment by ilyam8** [comment]
Interesting, I installed Netdata in a Rockylinux 8 docker container (before installing Netdata I made sure I had `adm` and `nignx` groups):

```cmd
[root@51c8791d67c9 /]# id netdata
uid=996(netdata) gid=993(netdata) groups=993(netdata),992(docker)
```

**Comment by iigorkarpov** [comment]
I bet I never added netdata to any group manually. Let me double-check this.

**Comment by ilyam8** [comment]
@iigorkarpov try to find a place in the code where we add `netdata` to groups - I couldn't (except [this](https://github.com/netdata/netdata/issues/13090#issuecomment-1153898391)).

**Comment by iigorkarpov** [comment]
Ansible installation to Fedora 35 does not add netdata to any group except `docker`

**Comment by iigorkarpov** [comment]
Yes
