### ISSUE TITLE
[Bug]: Netdata installer sh script does not work on Keenos 

### ISSUE THREAD

**Issue by ozsen06** [netdata/netdata#13124]
### Bug description

Keenos is an os for routers based on openwrt by Keenetic 
it allows you to install opkg packages like
`opkg install netdata`
witch, I was successful of installing netdata but I wanted to use netdata cloud with my device (from my findings the maintainer of the pre compiled package is not so interested in supporting cloud) I used the install script 
`curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh`
or
`curl https://my-netdata.io/kickstart-static64.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh`

Output

`I NEED YOUR HELP
It seems I cannot detect your system automatically.
And it seems I cannot find a known package manager in this system.
Please open a github issue to help us support your system too.
 FAILED`
`  - Cannot find an os-release file ...
  - Unable to determine Linux distribution for native packages.
  - Could not install native binary packages, falling back to alternative installation method.
  - No static build available for mips CPUs.
  - Could not install static build, falling back to alternative installation method.
  - Command "/opt/bin/bash /tmp/netdata-kickstart-XXXXVjy4EN/install-required-packages.sh netdata" failed with exit code 1.
  - Failed to install all required packages, but installation might still be possible.

 ERROR  Installer exited unexpectedly (2-0)`

uname -a
Linux [redacted, hostname] 4.9-ndm-5 #0 SMP Wed Mar 30 08:35:55 2022 mips GNU/Linux

### Expected behavior

Netdata installing successfully using the install script provided by netdata "Add nodes to General" part of the page as I have done with 4 other servers for this device I have also tried to use static64.sh same results

### Steps to reproduce

1. On a device running KeenOS enable the opkg support
2. Connect to the device root@[ipadress] -p222
3. Use the install script 
...

### Installation method

kickstart.sh

### System info

```shell
Linux [redacted, hostname] 4.9-ndm-5 #0 SMP Wed Mar 30 08:35:55 2022 mips GNU/Linux
grep: /etc/*release: No such file or directory
```

### Netdata build info

```shell
-sh: netdata: not found
I have not been able to install it 

but if I install using opkg
Features:
    dbengine:                   NO
    Native HTTPS:               NO
    Netdata Cloud:              NO (by user request)
    ACLK Next Generation:       NO
    ACLK-NG New Cloud Protocol: NO
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           NO
    Stream Compression:         NO
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
from what I have red online (https://github.com/openwrt/packages/issues/158059 the maintainer is not interested in enabling Netdata Cloud: while compiling
```

### Additional info

KeenOS behaves like openwrt and is based on openwrt so I don't think It will be hard to make so that the script installes just like it would in a OpenWrt system

**Comment by Ferroin** [comment]
This unfortunately is not as simple as it probably sounds. The key issue here is not that the system is like OpenWRT, it’s that you want to install on what appears to be 32-bit MIPS hardware. Put simply, we have no practical way to provide pre-built packages for such hardware currently (static builds would be the only way we could theoretically do it, but we’re dependent on Alpine as a build platform there and Alpine has no MIPS support at all), and are unlikely to be able to do so any time in the near future.
