### ISSUE TITLE
[Bug]: Netdata Crash (netdata FATAL : DBENGINE : Cannot allocate dbengine page cache page, with mmap() # : Invalid argument)

### ISSUE THREAD

**Issue by stohn** [netdata/netdata#13133]
### Bug description

I experience crashes of the netdata process with the new 1.35.0 / 1.35.1 versions.

From netdata error.log:
`netdata FATAL : DBENGINE : Cannot allocate dbengine page cache page, with mmap() # : Invalid argument`

I run a master server with 6 clients streaming to it (Server: 8 Cores, 48GB RAM). 
The master stores everything within a large dbengine: 
  ```
  memory mode = dbengine
  page cache size = 20000
  dbengine multihost disk space = 96000
  ```
 
This holds a lot of data (apx. 70 days history every 1 second, for master + all clients).
The page cache size is set to this large value intentionally since the physical hard disks are very slow and caching is needed.

When I now pick one of the servers in dashboard and zoom out to max, netdata allocates a lot of memory (up to about 20 GB) which is as intended. But when I continue to look at different charts then the "mmap()" error occurs. It seems the 20GB is a magical limit (might be related with the page cache size).

However the netdata 1.34.1 release version can allocate 32GB RAM easily and whatever "stress" I put to it (zoom out, look at different charts, ...) it never crashes.

I observed a similar behavior and crashes with 1.34.x snapshot builds (before 1.35.0 release) and found the new memory allocator was responsible for it. Then I saw the commit that the mmap was replaced with malloc and thought 1.35.0 release would be good to use... But there seem to be still some mmap problems inside.

### Expected behavior

no crash (like in 1.34.1 and before)

### Steps to reproduce

1. large dataset in dbengine (96 GB), system with RAM 48 GB, large pagecache
2. use dashboard zoom out to max and look at multiple charts => netdata allocates more and more ram
3. when netdata allocated 20GB RAM then the crash happens every time a new chart is looked at (and more date should be loaded).

### Installation method

kickstart-static64.sh

### System info

```shell
Linux monitor 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.35.0-2-gfee539f8e
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' '--with-bundled-libJudy' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: manual-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by stelfrag** [comment]
@stohn thank you for reporting this. In our tests we have used a page cache size of 30000 without problems (collecting 90K+ metrics per second), but looks like something is not quite right (in general).  We will add an option to switch to malloc.
