### ISSUE TITLE
[Bug]: Version 1.35.1 agent crashes when viewing dashboard via cloud

### ISSUE THREAD

**Issue by MikeJakubik** [netdata/netdata#13147]
### Bug description

Hi,

I recently updated to 1.35.1 and the agent is now crashing as soon as I click on overview or node via the cloud interface. I can access the interface locally and it keeps on running just fine. Below is what I can see in error.log.

```
2022-06-15 08:45:48: apps.plugin ERROR : MAIN : Cannot fetch process 76054 command line (command 'ps') (errno 3, No such process)
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.

```

In my system log I see evidence of the crash.

`pid 31790 (netdata), jid 0, uid 302: exited on signal 10 (core dumped)`

### Expected behavior

Not crash

### Steps to reproduce

1. Install netdata agent on FreeBSD
2. View stats via cloud interface
3.
...

### Installation method

from source

### System info

```shell
FreeBSD staging.swift-api.com 13.1-STABLE FreeBSD 13.1-STABLE #0 stable/13-be3f66738: Tue Jun 14 14:45:31 EDT 2022     root@staging.swift-api.com:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
1301504

FreeBSD clang version 14.0.4 (https://github.com/llvm/llvm-project.git llvmorg-14.0.4-0-g29f1039a7285)
```

### Netdata build info

```shell
Version: netdata v1.35.1
Configure options:  '--disable-unit-tests' '--with-aclk-ng' '--disable-plugin-cups' '--enable-dbengine' '--disable-plugin-freeipmi' '--enable-lto' '--prefix=/usr/local' '--localstatedir=/var' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/share/info/' '--build=amd64-portbld-freebsd13.1' 'build_alias=amd64-portbld-freebsd13.1' 'CC=cc' 'CFLAGS=-O2 -pipe -march=native  -fstack-protector-strong -fno-strict-aliasing ' 'LDFLAGS=  -fstack-protector-strong ' 'LIBS=' 'CPPFLAGS=-D_WANT_VMMETER' 'CXX=c++' 'CXXFLAGS=-O2 -pipe -march=native -fstack-protector-strong -fno-strict-aliasing  ' 'PKG_CONFIG=pkgconf' 'CPP=cpp'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: NO
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by MrZammler** [comment]
Hi @MikeJakubik thanks for the report.

Can you please share your `access.log` and `error.log` to manolis at netdata dot cloud?

Thanks!

**Comment by MikeJakubik** [comment]
> Hi @MikeJakubik thanks for the report.
> 
> Can you please share your `access.log` and `error.log` to manolis at netdata dot cloud?
> 
> Thanks!

Sure, logs have been sent.

**Comment by MrZammler** [comment]
Hi @MikeJakubik 

Thanks for the logs! There is a hint there to indicate the crash taking place after a specific query. Although different compiler, and different environment, is it maybe possible to try a nightly version that contains this patch https://github.com/netdata/netdata/pull/13137 ?

**Comment by MikeJakubik** [comment]
I found the doc describing the build process @ https://github.com/netdata/netdata/blob/master/packaging/installer/methods/source.md

However, i get this error when compiling. This file doesn't exist in netdata or my system (when the port version compiled OK)

  CC       database/ram/rrddim_mem.o
  CC       database/sqlite/sqlite_functions.o
  CC       database/sqlite/sqlite_aclk.o
In file included from database/sqlite/sqlite_aclk.c:10:
In file included from database/sqlite/../../aclk/aclk.h:6:
./aclk/aclk_util.h:6:10: fatal error: 'mqtt_wss_client.h' file not found
#include "mqtt_wss_client.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
gmake[2]: *** [Makefile:5780: database/sqlite/sqlite_aclk.o] Error 1
gmake[2]: Leaving directory '/tmp/netdata'
gmake[1]: *** [Makefile:6534: all-recursive] Error 1
gmake[1]: Leaving directory '/tmp/netdata'
gmake: *** [Makefile:3561: all] Error 2

**Comment by MrZammler** [comment]
Hi Mike, sorry for not responding earlier.

Inside the netdata directory, please run the following: `git submodule update --init --recursive` and then try again. Thanks!

**Comment by MikeJakubik** [comment]
Hi,

Thanks that did the job compile-wise. But I can't quite run it as is, it's missing the magic that the port gives it. If I could get a release style tgz based on the master branch I could trick the port into building it instead of 1.35.1.

The port looks for https://github.com/${PORTNAME}/${PORTNAME}/releases/download/v${DISTVERSION}/

[root@staging ~]# daemon -c -u netdata /tmp/netdata/netdata
[root@staging ~]# 2022-06-16 11:57:08: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/db/netdata/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2022-06-16 11:57:08: netdata ERROR : MAIN : uv_fs_scandir(/var/db/netdata/cache/netdata): no such file or directory (errno 2, No such file or directory)
2022-06-16 11:57:08: netdata FATAL : MAIN : Cannot change directory to '/var/db/netdata/cache/netdata' # : No such file or directory

2022-06-16 11:57:08: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2022-06-16 11:57:08: netdata INFO  : MAIN : EXIT: cleaning up the database...
2022-06-16 11:57:08: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
2022-06-16 11:57:08: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...

[root@staging ~]# ls /var/db/netdata/
cloud.d                         health                          netdata.api.key                 registry
dbengine_multihost_size         lock                            pythond-jobs-statuses.json

**Comment by MikeJakubik** [comment]
Hi,

I have figured out finally how to get this running (had to edit the configure.ac file dir locations), it is not crashing now when I hit overview in the cloud UI.

Thank you!

**Comment by MrZammler** [comment]
Good to hear! Thank you very much for taking the time and effort to update!
