### ISSUE TITLE
[Bug]: After the Netdata agent installation it stays offline

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata#13164]
## Issue

After installing Netdata using the kickstart script, the user faced an issue where the agent stayed offline. It looks like the daemon is not started by the kickstart script by default.

cc: @MrZammler @cpipilas 

### Expected behavior

On executing the kickstart script, the netdata agent / daemon should start running automatically and if the claim tokens are used, the node should be automatically claimed on the cloud.

### Steps to reproduce

1. Install Netdata using the kickstart script
2. Node is offline

...
[netdata.txt](https://github.com/netdata/netdata/files/8920337/netdata.txt)

### Installation method

kickstart.sh

### System info

```shell
Ubuntu Linux
```

### Netdata build info

```shell
V 1.35.1
```

**Comment by cakrit** [comment]
The issue I saw was not because the agent didn't start, so I'm creating a different issue on the experience on the cloud side.

**Comment by cpipilas** [comment]
Confirmed with Ubuntu 20.04 & Netdata 1.35.0-29-nightly

```
-- Attempting to claim agent to https://app.netdata.cloud --- 
 --- Attempting to claim agent to https://app.netdata.cloud --- 
[/tmp/netdata-kickstart-T4UtY139mp]$ sudo /usr/sbin/netdata-claim.sh -token=TOKEN -rooms= -url=https://app.netdata.c
loud -daemon-not-running 
Unable to communicate with Netdata daemon, querying config from disk instead.
Unable to communicate with Netdata daemon, querying config from disk instead.
Token: ****************
```

cc @stelfrag @Ferroin @underhood
