### ISSUE TITLE
[Feat]: Add an apps section within each container

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata#13190]
### Problem

Currently Netdata only visualises the cpu, mem, disk and net on each container. It will be of great help for users to monitor the applications within each container.

<img width="203" alt="image" src="https://user-images.githubusercontent.com/96257330/174860974-a29aead0-6c65-471e-af35-c1802650cbac.png">

cc: @ktsaou @cakrit @cpipilas 

### Description

Currently Netdata only visualises the cpu, mem, disk and net on each container. It will be of great help for users to monitor the applications within each container.
On the Netdata agent, we should segregate the applications per container and add an Apps section with all relevant charts.

### Importance

must have

### Value proposition

1. Users can monitor their applications per container
2. Provides higher granularity for troubleshooting
3. Users can get an aggregated view of applications across all containers from the global Applications section and can compare the performance per container
...

### Proposed implementation

On the Netdata agent, we should segregate the applications per container and add an Apps section with all relevant charts.

**Comment by ilyam8** [comment]
I believe that in the majority of cases 1 container == 1 app => container metrics == the app metrics. So the "Apps" section within each container doesn't look useful.
