### ISSUE TITLE
[Feat]: Default alerts for apps plugin

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata#13191]
### Problem

Currently our Netdata default alerts are not configured based on process groups in the apps plugin. It will be great to have alerts specific to app / process groups and allow users to set limits per group.

### Description

Currently our Netdata default alerts are not configured based on process groups in the apps plugin. It will be great to have alerts specific to app / process groups and allow users to set limits per group.
This can be useful to identify memory leaks, cpu limits per process / group, disk utilisation etc

cc: @ktsaou @cpipilas @cakrit @ilyam8 @MrZammler 

### Importance

must have

### Value proposition

1. Provides users per app control
2. Can help identifying and reporting memory leaks if the memory footprint of a process increases
3. Set default limits on cpu, mem and disk utilisation per app group
...

### Proposed implementation

Introduce additional default alerts per process group based on the app_plugins.

**Comment by Ferroin** [comment]
The reason we don’t have this is that for alerts on app groups to make sense, you have to know the _exact_ workload the system is supposed to be running, as well as a lot of details about the hardware.

Saying, for example, that nginx or Apache shouldn’t exceed some percentage of CPU utilization is good, but to decide what that percentage should be, you need to know how much CPU time is needed to service each request (very dependent on both the hardware and the workload) and what the expected peak request rate is, _and we have no way to figure that out ourselves_.

This means that in trying to provide ‘default’ alarms, we will end up with most of them either having a nonsensically high threshold (and therefore never triggering and just wasting resources in the health code) or having a nonsensically low threshold (and therefore firing all the damn time, contributing to alert fatigue, and not actually doing anything useful, much like the old softnet alarms, or the disk utilization percentage alarms on a file server, or the RAM usage alarms on a properly sized virtualization host).

We can easily provide _example_ alarms if we want, but they should not be enabled by default (not even silent, but literally not enabled), but providing actual enabled alarms by default here makes very little practical sense.

**Comment by sashwathn** [comment]
@Ferroin Yes you are absolutely right and may be we can create some sample alerts which our users can configure based on their infrastructure and configurations.

But do you think we can actually identify memory leaks by monitoring the memory footprint of a process / process group? Ideally the memory footprint should be relatively stable / static and could we report in case we see that a specific process mem footprint is continuously increasing?

**Comment by cakrit** [comment]
Doesn't it make sense in most use cases to have an automated warning when any process group takes more than 95% CPU and critical when it goes to 98% or 99%? 

The memory leak @sashwathn mention also makes sense, we discussed this with Costa. 

There's also the following, shouldn't anything above 0 be a warning?
<img width="365" alt="image" src="https://user-images.githubusercontent.com/43294513/175068725-b39439ba-7d96-4355-a578-2f05b92a819a.png">
