### ISSUE TITLE
[Bug]: After child disconnection and reconnection, parent returns nulls for anomaly rates

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13210]
### Bug description

We saw with @andrewm4894 that after a child node restarted, we started getting nulls for certain highlighted windows in the anomaly advisor. The screenshot is from one of them. We had a similar issue in the past. The weird that for other windows it did return data.

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/43294513/175322705-941ecdc9-09e2-4727-a14f-3ba676f1734b.png">

### Expected behavior

Consistently return the anomaly data

### Steps to reproduce

1. I suppose restart a child node and try selecting different windows to request the anomaly data from the parent.

### Installation method

kickstart.sh

### System info

```shell
-
```

### Netdata build info

```shell
-
```

**Comment by andrewm4894** [comment]
this is failing because we get all nulls from the anomaly rates chart from the parent for some reason - here is internal slack thread to discuss private since is ip addresses etc involved. 

https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1655994946769379

**Comment by cpipilas** [comment]
@andrewm4894 what was the version used?

**Comment by andrewm4894** [comment]
@Dim-P no, not related - i think we can actually close this one as things have moved on and we are using the new /weights endpoint for this.
