### ISSUE TITLE
[Bug]: SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 80

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#13213]
### Bug description

Unable to connect via https port 19999 following nightly update 3-4 days ago. Browser can no longer connect over internet. Netdata Error Log reports:

`netdata INFO  : WEB_SERVER[static1] : You are running an OpenSSL older than 1.1.0, web server will not enable multithreading.`

This is false, I'm using 1.1.1.o:

Server Version: Apache/2.4.54 (cPanel) **OpenSSL/1.1.1o** mod_fcgid/2.3.9 mod_cpanel/1.4

After trying to open Netdata Dashboard via https://myserver.com:19999 which always worked before Error Log shows:

`netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 80`

I have replaced my cert.pem and key.pem files in /etc/Netdata/ssl just in case, no effect. Unsure why Netdata won't use the existing available Certs in /etc/ssl/ directory out of the box, would save a lot of hassle!

Have trying reinstalling (kickstart). No effect, still won't let me connect as normal. Thanks.

### Expected behavior

Connect via TLS as normal.  Compatibility with OPENSSL 1.1.1.o. Use available server host certs and key by default, but may be a feature request if intentional. Thank you 😊 

### Steps to reproduce

1. Connect to bookmarked url https://myserver.com:19999
2. Browsers say they cannot connect to site.
3. Check error log with SSH command: less /var/log/netdata/error.log | grep WEB_SERVER
...

### Installation method

kickstart-static64.sh

### System info

```shell
Linux vpsxxxxxx.inmotionhosting.com 3.10.0-1160.21.1.vz7.174.13 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
Version: netdata v1.35.0-65-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

2022-06-23 23:05:30: netdata INFO  : EXPORTING : No connector instances to activate
2022-06-23 23:05:30: netdata INFO  : EXPORTING : EXPORTING: no exporting connectors configured
2022-06-23 23:05:30: netdata INFO  : EXPORTING : cleaning up...
2022-06-23 23:05:30: netdata INFO  : EXPORTING : thread with task id 12374 finished
2022-06-23 23:05:30: netdata INFO  : WEB_SERVER[static1] : You are running an OpenSSL older than 1.1.0, web server will not enable multithreading.
2022-06-23 23:05:30: netdata INFO  : WEB_SERVER[static1] : POLLFD: LISTENER: listening on 'tcp:0.0.0.0:19999'
2022-06-23 23:05:30: netdata INFO  : WEB_SERVER[static1] : POLLFD: LISTENER: listening on 'tcp:[::]:19999'
2022-06-23 23:05:30: netdata INFO  : STATSD_COLLECTOR[1] : thread created with task id 12395
2022-06-23 23:05:30: netdata INFO  : STATSD_COLLECTOR[1] : set name of thread 12395 to STATSD_COLLECTO
2022-06-23 23:05:30: netdata INFO  : STATSD_COLLECTOR[1] : STATSD collector thread started with taskid 12395
2022-06-23 23:05:30: netdata INFO  : STATSD_COLLECTOR[1] : POLLFD: LISTENER: listening on 'udp:[::1]:8125'
2022-06-23 23:05:30: netdata INFO  : STATSD_COLLECTOR[1] : POLLFD: LISTENER: listening on 'udp:127.0.0.1:8125'
2022-06-23 23:05:30: netdata INFO  : STATSD_COLLECTOR[1] : POLLFD: LISTENER: listening on 'tcp:[::1]:8125'
2022-06-23 23:05:30: netdata INFO  : STATSD_COLLECTOR[1] : POLLFD: LISTENER: listening on 'tcp:127.0.0.1:8125'
2022-06-23 23:05:30:  INFO  : MAIN : Does not have a configuration file inside `/etc/netdata/ebpf.d.conf. It will try to load stock file.
2022-06-23 23:05:30: netdata INFO  : PLUGIN[proc netdev] : thread created with task id 12390

**Comment by thiagoftsm** [comment]
Hello @TheOldMan2000 ,

When I installed a CentOS 7.x VM I have the exactly same information reported by you, but on my environment the OpenSSL is older than `1.1.0`:

```sh
[vagrant@10 ~]$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
[vagrant@10 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[vagrant@10 ~]$ uname -a
Linux 10.0.2.15 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
For me to recreate what you are describing I need an information, did you compile `OpenSSL 1.1.1o` on your CentOS? Or did you install the package from a specific repo?

Best regards!

**Comment by TheOldMan2000** [comment]
Hello @thiagoftsm 

Thanks for the reply. I just ran the same commands as in your post and I can't believe it, but I get the same version coming back as you! It looks like there are 2 versions installed. I don't know where OpenSSL 1.0.2k-fips came from, but it looks like Netdata is going off that one instead of the version detailed via WHM/Cpanel.

`root@vpsxxx [~]# openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
root@vpsxxx [~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
root@vpsxxx [~]# uname -a
Linux vpsxxx.inmotionhosting.com 3.10.0-1160.21.1.vz7.174.13 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 x86_64 x86_64 GNU/Linux`

To answer your question, I've never knowingly installed OpenSSL myself from a repo. I assumed it  gets updated by EasyApache and WHM/Cpanel software update procedures which use Yum.

I'm currently on WHM version shows 104.0.4 and CentOS v7.9.2009 STANDARD virtuozzo. I just went to the site and searched for OpenSSL and in the release notes for v1.0.4 it does say the older version: 

https://docs.cpanel.net/release-notes/104-release-notes/

> cPanel & WHM version 104 includes the following third-party applications:
> 
> Third-party application | Version | Source
> openssl | 1.0.2k-21.el7_9 | RPM
> openssl-devel | 1.0.2k-21.el7_9 | RPM
> openssl-libs | 1.0.2k-21.el7_9 | RPM
> 

In the WHM documentation, it states:

`Not all internet browsers or clients will support TLSv1.3, which requires OpenSSL 1.1.1 or higher.`

I am of course using TLSv1.3 (and TLSv1.2).

Actually, I just went to Apache Status in WHM and it looks like I got an update, I'm now on 1.1.1p:

```
Apache server status for vpsxxx.inmotionhosting.com
Server Version: Apache/2.4.54 (cPanel) OpenSSL/1.1.1p mod_fcgid/2.3.9 mod_cpanel/1.4
Server MPM: event
```

**Comment by TheOldMan2000** [comment]
Hello, I just found some info on this issue in this Cpanel topic. I need some sleep to digest it, but it seems to cover the discrepancy we're seeing...

https://forums.cpanel.net/threads/openssl-1-1-1n-should-we-update-it-manually-or-will-it-be-done-by-cpanel-soon.699085/

**Comment by thiagoftsm** [comment]
Hello @TheOldMan2000 , 

Sorry for the delay to answer, but I was on vacation.
I saw the topic in the `cpanel` channel, and I will try to recreate with the issue with the environment described there and I will bring a fix.

Best regards!

**Comment by TheOldMan2000** [comment]
Thank you, much appreciated. Hope you had a good break!

I'm unsure why this recently became an issue, from reading the threads at Cpanel forums, it seems that there have always been 2 versions of OpenSSL in on CentOS 7 WHM/EasyApache servers, one in EasyApache and an outdated system version.

My Netdata install still refuses to let me connect to its 19999 Dashboard, so I'm hoping it's something to do with this reported issue.

:)

**Comment by thiagoftsm** [comment]
Hello @TheOldMan2000 ,

Yes it was very good, thank you! :)

I was talking with people from our SRE team (@Ferroin, @maneamarius) about your issue and they reported me that by default the kickstart will always try to use the local environment packages, this means that it will always link against the `OpenSSL 1.0.2`, but `netdata` also allows users to use the `static` version hat is compiled with a more recent `OpenSSL` (Right now we are using version `1.1.1.X`.) that does not have these issues.

Now about what your reporting. I remember to see an analogous problem months/years ago when `TLS 1.3` became the unique version accepted by my browser. Considering everything that you described, it is possible you also had your browser updated. :thinking: 

Finally, a possible solution for you will be to install `netdata` using kickstart like this:

```sh
# curl -o /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --static-only
````

Running this command with the given arguments `netdata` will ignore completely the local packages. For more details you can take a look in this [link](https://learn.netdata.cloud/docs/agent/packaging/installer/reinstall#changing-the-install-type-of-an-existing-installation) .

Best regards!

**Comment by TheOldMan2000** [comment]
Thanks @thiagoftsm much appreciated!

I read up following that link and made backups then ran your command as root.
I don't think it's worked for me, as I'm still seeing Netdata error.log complain OpenSSL is out of date and it won't let me connect to the Dashboard via port 19999 as normally does until last week.

`
# uname -a; grep -HvE "^#|URL" /etc/*release
Linux vps71163.inmotionhosting.com 3.10.0-1160.21.1.vz7.174.13 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
`

`# netdata -W buildinfo
Version: netdata v1.35.0-84-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
`

`less /var/log/netdata/error.log | grep WEB_SERVER
2022-06-28 16:57:20: netdata INFO  : MAIN : EXIT: Stopping main thread: WEB_SERVER[static1]
2022-06-28 16:57:20: netdata INFO  : WEB_SERVER[static1] : freeing local web clients cache...
2022-06-28 16:57:20: netdata INFO  : WEB_SERVER[static1] : stopped after 15 connects, 15 disconnects (max concurrent 1), 15 receptions and 0 sends
2022-06-28 16:57:20: netdata INFO  : WEB_SERVER[static1] : closing all web server sockets...
2022-06-28 16:57:20: netdata INFO  : WEB_SERVER[static1] : all static web threads stopped.
2022-06-28 16:57:20: netdata INFO  : WEB_SERVER[static1] : thread with task id 14362 finished
2022-06-28 16:57:22: netdata INFO  : WEB_SERVER[static1] : thread created with task id 17330
2022-06-28 16:57:22: netdata INFO  : WEB_SERVER[static1] : set name of thread 17330 to WEB_SERVER[stat
2022-06-28 16:57:22: netdata INFO  : WEB_SERVER[static1] : You are running an OpenSSL older than 1.1.0, web server will not enable multithreading.
2022-06-28 16:57:22: netdata INFO  : WEB_SERVER[static1] : POLLFD: LISTENER: listening on 'tcp:0.0.0.0:19999'
2022-06-28 16:57:22: netdata INFO  : WEB_SERVER[static1] : POLLFD: LISTENER: listening on 'tcp:[::]:19999'
2022-06-28 17:55:28: netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 96 
2022-06-28 17:55:29: netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 96 
2022-06-28 17:55:29: netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 96 
2022-06-28 17:55:32: netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 96 
2022-06-28 17:55:32: netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 96 
2022-06-28 17:55:32: netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 96 
2022-06-28 17:55:34: netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 96 
2022-06-28 17:55:34: netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 93 
2022-06-28 17:55:34: netdata INFO  : WEB_SERVER[static1] : 0 SSL Handshake error (error:00000005:lib(0):func(0):DH lib) on socket 93`

Thanks again for the help.

**Comment by thiagoftsm** [comment]
Hello @TheOldMan2000 ,

I created a VM running CentOS from scratch and after this I installed netdata:

```sh
# curl -o /tmp/netdata-kickstart.sh htt^C://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --static-only --dont-start-it
```

I went to directory `/opt/netdata/etc/netdata/ssl` and I created self signed certificates and after this I adjusted the permissions:

```sh
# openssl req -newkey rsa:2048 -nodes -sha512 -x509 -days 365 -keyout key.pem -out cert.pem
# chmod 640 key.pem
# systemctl start netdata
# ps aux| grep netdata
netdata   2877  2.7  2.8  76784 28892 ?        SNsl 13:25   0:00 /opt/netdata/bin/srv/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D
netdata   2882  0.0  0.1  23684  1060 ?        SNl  13:25   0:00 /opt/netdata/bin/srv/netdata --special-spawn-server
root      3000  0.5  0.1   6164  1480 ?        SN   13:25   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
netdata   3010  0.0  0.1   1900  1064 ?        SN   13:25   0:00 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata   3041  0.2  1.9 731572 19816 ?        SNl  13:25   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata   3053  3.0  1.9 136132 19496 ?        SNl  13:25   0:00 /usr/bin/python3 /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
``` 

Finally I accessed the dashboard using `Mozilla Firefox 102.0` and when I took a look at `access.log` I did not have the error:

```sh
[root@localhost ssl]# grep "SSL Handshake error " /opt/netdata/var/log/netdata/error.log
[root@localhost ssl]#
```

It called my attention that in your last message you still looked for a log inside `/var/log/netdata`, but  when `kickstart.sh` receives the option `--static-only` it should be installed at `/opt/netdata/` and the logs would be at `/opt/netdata/var/log/netdata/`, please, can you confirm that your binaries are in the correct place running `ps aux| grep netdata`?

Thanks!

**Comment by TheOldMan2000** [comment]
Ah, thanks for all your help anyway! TBH I can't understand why this was never an issue before last week, I've left it running for a few months but a reinstall seems in order. Presumably I would copy the current 3 backup configs and folders to the static install, except for the netdata.conf, as that would reference and switch back the old /etc/Netdata directories?

**Comment by TheOldMan2000** [comment]
I ran that command again to see what it actually reported, in case you can spot any clues as to why it does work for me...

```
curl -o /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --static-only

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76921    0 76921    0     0   186k      0 --:--:-- --:--:-- --:--:--  186k

 --- Using /tmp/netdata-kickstart-tLWWQGcudU as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- Found an existing netdata install at /, with installation type 'kickstart-build'. --- 
[/tmp/netdata-kickstart-tLWWQGcudU]# //usr/libexec/netdata/netdata-updater.sh --interactive --not-running-from-cron 
Wed Jun 29 18:00:42 BST 2022 : INFO: netdata-updater.sh:  Checking if a newer version of the updater script is available.
Wed Jun 29 18:00:43 BST 2022 : INFO: netdata-updater.sh:  Running on a terminal - (this script also supports running headless from crontab)
Wed Jun 29 18:00:43 BST 2022 : INFO: netdata-updater.sh:  Fetching dependency handling script...
Wed Jun 29 18:00:43 BST 2022 : INFO: netdata-updater.sh:  Running dependency handling script...
Loading /etc/os-release ...
Running in non-interactive mode
 > CentOS Version: 7 ...
 > Checking for EPEL ...

/etc/os-release information:
NAME            : CentOS Linux
VERSION         : 7 (Core)
ID              : centos
ID_LIKE         : rhel fedora
VERSION_ID      : 7

We detected these:
Distribution    : centos
Version         : 7
Codename        : 7 (Core)
Package Manager : install_yum
Packages Tree   : centos
Detection Method: /etc/os-release
Default Python v: 2 (will install python3 too)

Searching for distro_sdk ...
Searching for libatomic ...
 > Checking if package 'libatomic' is installed...
Searching for autoconf_archive ...
 > Checking if package 'autoconf-archive' is installed...
Searching for libz_dev ...
 > Checking if package 'zlib-devel' is installed...
Searching for libuuid_dev ...
 > Checking if package 'libuuid-devel' is installed...
Searching for libmnl_dev ...
 > Checking if package 'libmnl-devel' is installed...
Searching for json_c_dev ...
 > Checking if package 'json-c-devel' is installed...
Searching for libuv ...
 > Checking if package 'libuv-devel' is installed...
Searching for lz4 ...
 > Checking if package 'lz4-devel' is installed...
Searching for openssl ...
 > Checking if package 'openssl-devel' is installed...
Searching for judy ...
Searching for libelf ...
 > Checking if package 'elfutils-libelf-devel' is installed...

All required packages are already installed. Now proceed to the next step.

Wed Jun 29 18:00:49 BST 2022 : INFO: netdata-updater.sh:  Current Version: 00103500000084
Wed Jun 29 18:00:49 BST 2022 : INFO: netdata-updater.sh:  Latest Version: 00103500000084
Wed Jun 29 18:00:49 BST 2022 : INFO: netdata-updater.sh:  Newest version (current=00103500000084 >= latest=00103500000084) is already installed
 OK 

 --- Updated existing install at / --- 
 --- Successfully updated existing netdata install at /. --- 
 --- Not attempting to claim existing install at / (no claiming token provided). --- 


```

**Comment by thiagoftsm** [comment]
> Ah, thanks for all your help anyway! TBH I can't understand why this was never an issue before last week, I've left it running for a few months but a reinstall seems in order. Presumably I would copy the current 3 backup configs and folders to the static install, except for the netdata.conf, as that would reference and switch back the old /etc/Netdata directories?

As I said previously, I had the same issue when I updated a browser. I do not use neither `CentOS` nor `Cpanel` in a high frequency, so the unique conclusion I can arrive right now, it is they manage to update packages in a way that the issue was generated recently.

When you pass the argument `--static-only` it will start using directory `/opt/netdata/etc/netdaa` instead `/etc/netdata.

**Comment by TheOldMan2000** [comment]
Thank you both, much appreciated. I'm using an iPad with the latest iPadOS to view it and I test via SSLLabs and get A+ for the server hostname itself (which is how I connect to Netdata), and each of my website domains the same rating, and all provide TLSv1.2 and TLSv1.3 fine (even with Cloudflare disabled for my actual websites).

 I will certainly try the option to put it behind Apache. I tried and failed this before a few years ago and was eventually told it wouldn't work on my system, but those docs seem to have changed, they were mostly based on Nginx at the time. 
 
I'm unsure which option on that page to follow, though!

My cloud VPS server with WHM/Cpanel has its main hostname that I normally connect to via https://myvps.inmotionhosting.com:19999 but no site on it in /var/www/html. I have about 7 actual websites with their own domains, mostly my personal sites, plus a few sites for clients that I designed for and 100% manage. All are behind Cloudflare. So using the 1 current Netdata install with web_log to access each virtual host's dom log as well as the Apache access_log, each separate PHP-FPM status page and each websites own Redis instance/pool gives me a nice overview of the server. 

So I don't know which proxy option to choose. Could you recommend which of the proxy options to go for? Plesk is mentioned too but not Cpanel if that's relevant.

**Comment by Ferroin** [comment]
I’m not quite as versed in configuration with Apache as with NGinx or H2O, but from your description it sounds like it might make the most sense to put Netdata in it’s own virtual host. I have no idea what may be needed to integrate that with Cpanel or WHM though.

---

On a side note, closing this as the original issue is effectively resolved (by having multiple workarounds). We can continue the discussion, but the general preference is to not leave issues open if the original problem has been resolved.

**Comment by TheOldMan2000** [comment]
Thank you, I'll have a play around with it. It's certainly frustrating how they let CentOS7 continue to run an insecure encryption system without updating it. I expect my host will move to Almalinux or Lightspeed at some point this year, especially now that WHM/Cpanel are dropping support soon.

**Comment by TheOldMan2000** [comment]
I couldn't get it work by putting it behind Apache, same thing happens. The Apache access and Netdata access logs show I'm connecting, I get 200 http codes, but the Netdata error log shows the same errors every time I try to connect via any of my virtual hosts or the server host name with /netdata folders.

**Comment by TheOldMan2000** [comment]
I managed to get Netdata working again.

I did an uninstall then ran the static command and it this time it installed in the /opt/netdata/etc/netdata folder (yuck!).

`curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh --static-only --static-install-options --disable-telemetry --disable-cloud`

I saw the installer mentioned it was accessing /etc/ssl/pki/certs so I assumed it would preconfigure setup of the TLS/SSL for me, but the SSL folder was empty when I looked. So I created cert.pem and key.pem with nano, and copied pasted my cert info from WHM for the hostname. 

Restarted Netdata and it let me straight in via the usual https://myserver.com:19999 address.

**Comment by thiagoftsm** [comment]
Hello @TheOldMan2000 ,

Thank you for the additional information, I had some issues past 3 days so I could not write a new PR, but I am already planning for this week to create a PR that will look in more directories to fix this issue,

Best regards!
