### ISSUE TITLE
Installed Netdata on Ubuntu via wget but netdata.service is not found[Bug]: 

### ISSUE THREAD

**Issue by amvots** [netdata/netdata#13212]
### Bug description

I installed Netdata via the wget command from the installation doc with all the defaults. But I could not do any of the systemctl commands to query or restart Netdata. 

rita@ubuntuServer3:~$ sudo systemctl status netdata
netdata.service
   Loaded: error (Reason: No such file or directory)
   Active: inactive (dead)

### Expected behavior

I expected to something similar to the following like my other Netdata on another system:

rita@server4:~$ sudo systemctl status netdata
[sudo] password for rita: 
● netdata.service - Real time performance monitoring
   Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2022-06-21 23:29:27 PDT; 1 day 13h ago
  Process: 3409 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 3408 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 3406 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 3399 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 3410 (netdata)
    Tasks: 157 (limit: 12287)
   CGroup: /system.slice/netdata.service
           ├─ 3410 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D
           ├─ 3589 /usr/libexec/netdata/plugins.d/go.d.plugin 1
           ├─ 3592 /usr/bin/python3 /usr/libexec/netdata/plugins.d/python.d.plugin 1
           ├─ 3593 /usr/libexec/netdata/plugins.d/ebpf.plugin 1
           ├─ 3598 /usr/local/bin/fping -N -l -Q 1 -p 200 -R -b 56 -i 1 -r 0 -t 5000 AppleTV4K2 iPhoneXS iPhoneXS-CA1 Fi
           ├─ 3603 /usr/libexec/netdata/plugins.d/apps.plugin 1
           └─37221 bash /usr/libexec/netdata/plugins.d/charts.d.plugin 1
...

### Steps to reproduce

1. Install the latest Netdata on Ubuntu
2. After installation, issue "sudo systemctl status netdata"

### Installation method

kickstart.sh

### System info

```shell
# Linux
Linux ubuntuServer3 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

### Netdata build info

```shell
rita@ubuntuServer3:~$ netdata -W buildinfo
-bash: netdata: command not found
rita@ubuntuServer3:~$
```

**Comment by ilyam8** [comment]
Hi, @amvots. Can you try

```cmd
sudo systemctl enable netdata
sudo systemctl start netdata
```

**Comment by amvots** [comment]
Hi @ilyam8,
Here are the results from the commands that you asked me to execute on our system:

Last login: Thu Jun 23 16:23:15 2022 from 147.21.64.22
rita@ubuntuServer3:~$ sudo systemctl enable netdata
Failed to issue method call: No such file or directory
rita@ubuntuServer3:~$ 

rita@ubuntuServer3:~$ sudo systemctl start netdata
Failed to issue method call: Unit netdata.service failed to load: No such file or directory. See system logs and 'systemctl status netdata.service' for details.
rita@ubuntuServer3:~$

**Comment by amvots** [comment]
The netdata.service is installed in the directory /opt/netdata/system/. I added this directory to the $PATH but the service is still not available.

**Comment by amvots** [comment]
I saw this post but I am not sure if it is still relevant. Should I give this a go? Thanks.

https://samiux.blogspot.com/2016/04/howto-netdata-on-ubuntu-14044-lts.html

**Comment by Ferroin** [comment]
This should (hopefully) be mostly resolved by https://github.com/netdata/netdata/pull/13451.

**Comment by amirhmoradi** [comment]
I got a similar issue, and fixed it by running these:

```
# Fixes netdata service start errors:
chown -R netdata:root /var/lib/netdata
chown -R netdata:root /etc/netdata
```
