### ISSUE TITLE
[Bug]: `custom-plugins.d/` is created under `/etc/netdata` which shouldn't contain executable scripts

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#13226]
### Bug description

- `custom-plugins.d/` is created under `/etc/netdata`

https://github.com/netdata/netdata/blob/157dafc232de64b3447dbe5f9e3a23c0e2a18e5a/collectors/Makefile.am#L31

- Netdata uses `CONFIG_DIR/custom-plugins.d` as the default

https://github.com/netdata/netdata/blob/157dafc232de64b3447dbe5f9e3a23c0e2a18e5a/collectors/plugins.d/plugins_d.c#L126-L128

### Expected behavior

`custom-plugins.d/` is created under `/usr/libexec/netdata/`.

### Steps to reproduce

1. Install Netdata (any install method will do).
2. Check `/etc/netdata`.

### Installation method

kickstart.sh

### System info

```shell
n/a
```

### Netdata build info

```shell
netdata v1.35.0-75-nightly
```

**Comment by MrZammler** [comment]
@Ferroin do you agree we should move this to `/usr/libexec/netdata/` ? I think it's do-able, provided we take care of existing custom plugins there (do we have such?)

**Comment by Ferroin** [comment]
Yes, we should move it, but we should keep looking in the old location as well for compatibility reasons (and maybe issue a warning if we find things there?), at least for a few releases.

**Comment by Ferroin** [comment]
Thinking further on this, the new location should probably be in `/var/lib/netdata`, not `/usr/libexec/netdata`. It’s generally expected behavior that an uninstall leaves things behind in `/var`, but not that it leaves things behind in `/usr`, and we need to consider handling of native packages here, not just local builds.

**Comment by ilyam8** [comment]
Closing because it doesn't look like it will be fixed and very low priority - no reason to keep it open.
