### ISSUE TITLE
[Bug]: fping alerts got triggered erroneously

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13229]
### Bug description

I cloned a VM where I had an fping running for app.netdata.cloud
Netdata on both VMs generated invalid alerts for latency and quality, for slightly different reasons. 
The first VM generated alerts right after a restart.
The second VM generated alerts when it started collecting data. The attached files are from the second VM.

### Expected behavior

Data collection starts/restarts shouldn't affect the fping alerts

### Steps to reproduce

1. Configure fping
2. Start netdata, leave it running for a bit, restart it, monitor alerts.

### Installation method

kickstart.sh

### System info

```shell
ubuntu 20.04
```

### Netdata build info

```shell
latest
```

### Additional info

The three uploads in the folder below contain the responses of /api/v1/alarms and of the /data calls 
https://drive.google.com/drive/folders/1RQ-Y15MgK6LKTLE9E9-Rt7zcNqbcKEXG?usp=sharing

**Comment by ilyam8** [comment]
@cakrit `app.netdata.cloud` is not _pingable_ (no response) 🤷‍♂️ I checked 3 different IP addresses.

> The first VM generated alerts right after a restart.

Perhaps it depends on domain name -> IP address resolution. Sometimes you get an IP that responds to ICMP.

**Comment by cakrit** [comment]
Ok, maybe it stopped being pingable after the migration to AWS. I should have looked more closely to the charts I guess.
