### ISSUE TITLE
[Bug]: Committed memory is not calculated properly on FreeBSD

### ISSUE THREAD

**Issue by MikeJakubik** [netdata/netdata#13231]
### Bug description

The Committed_AS (whatever AS means) memory seems wrong on FreeBSD. Netdata shows this as 660MiB, while according to the system it should be 2,012M.  According to the FreeBSD folks, this should be a calculated value of active+inactive memory.

"Wired memory is memory that, for whatever reason, cannot be relocated or swapped at the time of polling. It generally includes IO pages and kernel stuff.  Active is the memory that is relocatable and in active use, inactive is memory that is relocatable and eligible to be swapped out.  Some wired memory will "belong" to processes (for things like system calls) but generally falls under the authority of the kernel from my understanding. I should note though that freebsd reports memory only, if something gets moved out to swap that page will get laundered and then appear as free until the page is swapped back in"

### Expected behavior

Proper value

### Steps to reproduce

1. Look at mem.committed on FreeBSD

### Installation method

kickstart.sh

### System info

```shell
FreeBSD staging.swift-api.com 13.1-STABLE FreeBSD 13.1-STABLE #0 stable/13-be3f66738: Tue Jun 14 14:45:31 EDT 2022     root@staging.swift-api.com:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
1301504
```

### Netdata build info

```shell
Version: netdata v1.35.0-75-nightly
Configure options:  '--prefix=/usr/local/usr' '--sysconfdir=/usr/local/etc' '--localstatedir=/usr/local/var' '--libexecdir=/usr/local/usr/libexec' '--libdir=/usr/local/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--disable-dependency-tracking' '--with-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=-O2 -march=native' 'LDFLAGS=' 'CXXFLAGS=-O2 -march=native'
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: NO
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

top shows:

last pid: 26043;  load averages:  0.33,  0.27,  0.20                                                                                                             up 13+02:34:08  17:40:50
82 processes:  1 running, 81 sleeping
CPU:  0.1% user,  0.0% nice,  0.1% system,  0.1% interrupt, 99.7% idle
Mem: 144M Active, 1869M Inact, 13G Wired, 104K Buf, 109G Free
ARC: 9246M Total, 5137M MFU, 2087M MRU, 106M Header, 1892M Other
     5634M Compressed, 12G Uncompressed, 2.25:1 Ratio
Swap: 4096M Total, 4096M Free

While graph shows:

![Screenshot 2022-06-27 174137](https://user-images.githubusercontent.com/73555475/176040515-0fadd4c1-b83d-4b98-97f6-8d42b61ec611.png)

**Comment by ilyam8** [comment]
Relevant comment: https://github.com/netdata/netdata/issues/13172#issuecomment-1164066008
