### ISSUE TITLE
[Bug]: `anomaly_detection.anomaly_rates` sometimes inconsistent with `points=1`

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#13237]
### Bug description

If i make a request like this to the agent i see the raw data

```

qry1

http://HOST:19999/api/v1/data?chart=anomaly_detection.anomaly_rates&options=nonzero&after=1656406500&before=1656406710&dimension=*cpu.cpu0_softirqs*TASKLET

{
 "labels": ["time","cpu.softirqs|cpu.cpu0_softirqs|TASKLET"],
    "data":
 [
 [ 1656406710,0.8],
 [ 1656406680,0.733],
 [ 1656406650,0.833],
 [ 1656406620,0],
 [ 1656406590,0],
 [ 1656406560,0],
 [ 1656406530,0]
]
}
```

Now if i make the window here 30s smaller i can see a subset of above data:

```

qry2

http://HOST:19999/api/v1/data?chart=anomaly_detection.anomaly_rates&options=nonzero&after=1656406530&before=1656406710&dimension=*cpu.cpu0_softirqs*TASKLET

{
 "labels": ["time","cpu.softirqs|cpu.cpu0_softirqs|TASKLET"],
    "data":
 [
 [ 1656406710,0.8],
 [ 1656406680,0.733],
 [ 1656406650,0.833],
 [ 1656406620,0],
 [ 1656406590,0],
 [ 1656406560,0]
]
}
```

All fine. The problem is if i do the same 2 requests above but with `points=1` i see some inconsistency. 

```

qry3

http://HOST:19999/api/v1/data?chart=anomaly_detection.anomaly_rates&options=nonzero&after=1656406500&before=1656406710&dimension=*cpu.cpu0_softirqs*TASKLET&points=1

{
 "labels": ["time","cpu.softirqs|cpu.cpu0_softirqs|TASKLET"],
    "data":
 [
 [ 1656406710,0.338]
]
}
```
now with the smaller window i see:

```

qry4

http://HOST:19999/api/v1/data?chart=anomaly_detection.anomaly_rates&options=nonzero&after=1656406530&before=1656406710&dimension=*cpu.cpu0_softirqs*TASKLET&points=1

{
 "labels": ["time","cpu.softirqs|cpu.cpu0_softirqs|TASKLET"],
    "data":
 [
 [ 1656406620,0]
]
}
```

The `0` in this last response is the problem, it should be the average of qry 2 so ~0.39

### Expected behavior

`qry4` above should properly just average the data in `qry2`

### Steps to reproduce

1.
2.
3.
...

### Installation method

kickstart.sh

### System info

```shell
x
```

### Netdata build info

```shell
x
```

### Additional info

reported by me internally here: https://netdata-cloud.slack.com/archives/C01K28B4V7Y/p1656407464255829

**Comment by MrZammler** [comment]
Hi @andrewm4894 , is this still an issue? There have been a lot of changes on the query engine...

Tried to replicate it somehow, but wasn't actually successful but I'm not sure if it was just my case of data.
