### ISSUE TITLE
[Bug]: container name resolution doesn't work - kind cluster

### ISSUE THREAD

**Issue by Garahk** [netdata/netdata#13251]
### Bug description

I have a VM test environment, where a k8s cluster has been deployed using kind. There I deployed netdata using helm charts

Besides the docker container where Kind cluster is mounted, kubelet and kubeproxy sections, the rest is a long list of what I assume are the pods of the cluster, no identifiable names, picture attached

![image](https://user-images.githubusercontent.com/99432183/176333735-29805b41-6415-4b8b-883c-81cce52dc793.png)

Only customization done when installling netdata is changing the parent.port and service.port from the default 19999 to a port 31000/container, 21000/host.

### Expected behavior

Find the names of the pods in an user friendly format

### Steps to reproduce

1. Installed netdata with helm parent.port/service.port=31000 in a Kind cluster
2. Expose parent pod in a different port 32000
3. Access the default dashboard and find the names of the pods are not user-friendly

### Installation method

helmchart (kubernetes)

### System info

```shell
Linux niaK8s 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
bash-5.1# netdata -W buildinfo
Version: netdata v1.35.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--with-bundled-libJudy' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

This is single node deployment.

Thank you in advance

**Comment by Garahk** [comment]
Hello @ilyam8 let me know if there's any other information missing, I'll be glad to provide. I understand there's a lot of issues to take care, let me just add that this is my testing server, however we have a dozen production servers which were recently migrated to K8s, waiting for the testing server to work so that we can apply Netdata to the others.

**Comment by ilyam8** [comment]
@Garahk, hey. I just installed a kind cluster and Netdata. I see it is not only the name resolution is broken but cgroups monitoring in general:

<img width="1626" alt="Screenshot 2022-07-04 at 21 15 20" src="https://user-images.githubusercontent.com/22274335/177202763-1543db69-0028-48b4-9453-4448d2adb18e.png">

**Comment by Garahk** [comment]
@ilyam8 Regarding the cgroups, I wasn't sure if it was due to the naming or something else, didn't think of including, my apologies

**Comment by ilyam8** [comment]
Hi, @Garahk. Can you test `ilyam8/netdata-test-for-github` image? It is built using the #13302 branch.

**Comment by ilyam8** [comment]
I merged the PR because I tested the changes locally on my kind cluster.

**Comment by Garahk** [comment]
Hello @ilyam8 , how can I test the fix? As I mentioned I use helm to install netdata, when I try to test it in my cluster, the official image will be downloaded (1.35.1), do I have to wait for the changes to be part of the next release? Or is there any specific way to create the chart/image that has the changes you just added.

Thank you in advace,

BR

**Comment by ilyam8** [comment]
You can test it today by adding `--set image.repository=ilyam8/netdata-test-for-github --set image.tag=latest` to helm install.

**Comment by Garahk** [comment]
I tested it like you mentioned, it would seem it now resolves the names correctly, however shouldn't we get CPU/memory statistics as well? Only getting net eth0 metrics on all pods:

![image](https://user-images.githubusercontent.com/99432183/177386262-d1be7d66-da05-423a-adb7-65268e93153f.png)

**Comment by ilyam8** [comment]
For me, it works (see the After screenshot in https://github.com/netdata/netdata/pull/13302). Can you send me a [snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) to `ilya@netdata.cloud`? Also, maybe you need to wait up to 10 seconds until the CPU/mem stats will appear. Did you try to refresh the page later?

**Comment by Garahk** [comment]
Apologies you were right, I had it running for some minutes more, and now I see cpu/mem/disk/eth metrics on most of the pods, however I see there are duplicated entries on the list for each pod, I've sent you an snapshot to ilya@netdata.cloud, would you be able to take a look and confirm if it's working properly?

Thank you again.

BR,

**Comment by ilyam8** [comment]
@Garahk, hey.

> however I see there are duplicated entries on the list for each pod

I see you have metrics for both pods (`k8s_pod_...`) and containers (`k8s_cntr_...`) - by default, we should filter all the pods (don't really need them because a pod metrics is an aggregation of pod containers metrics), but it didn't work in your case.

Let's do the following:

```cmd
kubectl exec -it <NETDATA_CHILD_POD_NAME> -c netdata -- bash
apk add tree
# and share the output of the command
tree -d /host/sys/fs/cgroup
```

---

> however we have a dozen production servers which were recently migrated to K8s, waiting for the testing server to work so that we can apply Netdata to the others. 

I believe the issues you were having are kind cluster specific - we never tested installing Netdata in there. I think you can give it a try Netdata in production.

**Comment by Garahk** [comment]
@ilyam8 , hello,

Attaching here the output of tree command:
[netdata-child-wqrdm_tree-output.log](https://github.com/netdata/netdata/files/9055495/netdata-child-wqrdm_tree-output.log)

> I believe the issues you were having are kind cluster specific - we never tested installing Netdata in there. I think you can give it a try Netdata in production.

Been working with the Netdata version for Docker for quite sometime now and it works flawlessly, but we have some customers that decided to go with Kind for production (temporarily but also indefinitely, while they go for a full deployment) and that's the reason we're struggling with Kind. 

Really appreciate the prompt support you've given so far, is there something else that can be done to filter the pods only (configuration?) , so that there's no duplicates,

Thank you in advance.

**Comment by ilyam8** [comment]
>  to go with Kind for production

Interesting, I was under the impression that Kind is not for production 😄

> is there something else that can be done to filter the pods only

Yes, we need to adjust the default filter - that is why I asked you for the `tree` output.

**Comment by ilyam8** [comment]
@Garahk the 2nd snapshot looks good, I see there are only `k8s cntr ...` containers (no more `k8s pod ...`). The latest `ilyam8/netdata-test-for-github` is built using the #13324 branch.

**Comment by Garahk** [comment]
@ilyam8 Yes, I tested the changes, and they work wonders, seems to me it's in tip-top shape :), glad you could take a look to the snapshot.

On a completely unrelated question, do you know if there's any planning to include a count of expected pods? as in a relation of running vs. expected pods, as to know whether there's a pod that's not coming up (crashloopback or error)

**Comment by Garahk** [comment]
@ilyam8 , I know that is to soon to ask, but if I may, when could we expect to have this in the official netdata/helmchart? so as to deploy with:

helm repo add netdata https://netdata.github.io/helmchart/
helm install netdata netdata/netdata

**Comment by ilyam8** [comment]
We recently added [k8s state collector](https://github.com/netdata/go.d.plugin/tree/master/modules/k8s_state#kubernetes-cluster-state-monitoring-with-netdata). I think it provides those metrics, check the docs.

I also [updated netdata helmchart](https://github.com/netdata/helmchart/pull/286): add a new instance (Deployment) with that collector. But the feature is disabled by default because the latest stable Netdata image has no it - will be enabled after when we have a new release.

**Comment by ilyam8** [comment]
> when could we expect to have this in the official netdata/helmchart?

It is not really helmchart related. The default is using the latest stable Netdata image, but it is configurable. So you have 2 options:

 - keep using stable release - then you wait until we release a new version of Netdata.
 - use nightly Netdata release - no need to wait but it is nightly 😄

**Comment by ilyam8** [comment]
> Is the nightly version the one we've been using from your repo?

No. The one you used is my personal, it will be `netdata/netdata`. We build `netdata/netdata:latest` every night if there are any changes. So we need to wait when #13324 is merged +1 day.

> --set image.tag=nightly

It is `latest` - `--set image.tag=latest`. I wouldn't recommend using it temporarily for testing, not sure it is a good idea to use it in production.

> --set k8sState.enabled=true

Correct!

---

I did some changes and rebuilt `ilyam8/netdata-test-for-github`. Can you test it one more time?

**Comment by Garahk** [comment]
Hello @ilyam8,

> No. The one you used is my personal, it will be netdata/netdata. We build netdata/netdata:latest every night if there are any changes. So we need to wait when https://github.com/netdata/netdata/pull/13324 is merged +1 day.

Ok, I'll monitor then #13324 and wait for it to be merged plus 1 additional day, to find the netdata/netdata:latest to be the winner 😄 

> I did some changes and rebuilt ilyam8/netdata-test-for-github. Can you test it one more time?

I tested it, looks great, sent you a snapshot as well from this latest test.

**Comment by Garahk** [comment]
Hi @ilyam8 , I see that a version `v1.36.0` has been comitted, wondering if such version contains already the fixes you helped develop for this issue, and the k8sState enabled by default already.

**Comment by ilyam8** [comment]
>  and the k8sState enabled by default already

Thanks for the reminder 👍 I made a [PR](https://github.com/netdata/helmchart/pull/299).

**Comment by Garahk** [comment]
> > and the k8sState enabled by default already
> 
> Thanks for the reminder 👍 I made a [PR](https://github.com/netdata/helmchart/pull/299).

Sure!, so will you include in this PR the fixes for the name resolution? or has this already been included in `v.136.0`?

**Comment by ilyam8** [comment]
v.1.36.0 has all the fixes
