### ISSUE TITLE
[Bug]: Active-active grandparent reports only immediate children on restart.

### ISSUE THREAD

**Issue by vkalintiris** [netdata/netdata#13297]
### Bug description

Setting up the following active-active hierarchy works correctly:

![graphviz](https://user-images.githubusercontent.com/25480816/177138562-06bc6c05-c07e-4b18-96c8-6397e48b76c3.svg)

That is, `ggp1`'s dashboard reports all the nodes, `gp1` reports all nodes except for `ggp1` and `ggp2`, etc.

However, after restarting `gp1` a couple times and visiting its dashboard, I can see only hosts `p1` and `p2`. The rest of the hosts are not accessible, ie. `c1`, `c2`, `gp2`.

In the following logs:

- `c1 = nd0:20000`
- `c2 = nd1:20001`
- `p1 = nd10:20010`
- `p2 = nd11:20011`
- `gp1 = nd100:20100`
- `gp2 = nd101:20101`
- `ggp1 = nd1000:21000`
- `ggp2 = nd1001:21001`

c1: http://localhost:20000/api/v1/info

```
	"uid": "377eb935-9b5f-3591-b4d6-367c64361ce1",
	"mirrored_hosts": [
		"nd0"
	],
	"mirrored_hosts_status": [
		{ "guid": "377eb935-9b5f-3591-b4d6-367c64361ce1", "hostname": "nd0", "reachable": true, "hops": 0, "claim_id": null, "node_id": null }
	],
```

c2: http://localhost:20001/api/v1/info
```
	"mirrored_hosts": [
		"nd1"
	],
	"mirrored_hosts_status": [
		{ "guid": "a5a65bb8-235e-3c98-91ed-6ce4d38f22ef", "hostname": "nd1", "reachable": true, "hops": 0, "claim_id": null, "node_id": null }
	],
```

p1: http://localhost:20010/api/v1/info
```
	"mirrored_hosts": [
		"nd10",
		"nd0",
		"nd1",
		"nd11"
	],
	"mirrored_hosts_status": [
		{ "guid": "a8246306-2b8d-3123-9cbb-157b8684fe30", "hostname": "nd10", "reachable": true, "hops": 0, "claim_id": null, "node_id": null },
		{ "guid": "377eb935-9b5f-3591-b4d6-367c64361ce1", "hostname": "nd0", "reachable": true, "hops": 1, "claim_id": null, "node_id": null },
		{ "guid": "a5a65bb8-235e-3c98-91ed-6ce4d38f22ef", "hostname": "nd1", "reachable": true, "hops": 1, "claim_id": null, "node_id": null },
		{ "guid": "eae5179f-c542-36e8-b949-205c2717bebb", "hostname": "nd11", "reachable": true, "hops": 1, "claim_id": null, "node_id": null }
	],
```

p2: http://localhost:20011/api/v1/info
```
	"mirrored_hosts": [
		"nd11",
		"nd0",
		"nd10",
		"nd1"
	],
	"mirrored_hosts_status": [
		{ "guid": "eae5179f-c542-36e8-b949-205c2717bebb", "hostname": "nd11", "reachable": true, "hops": 0, "claim_id": null, "node_id": null },
		{ "guid": "377eb935-9b5f-3591-b4d6-367c64361ce1", "hostname": "nd0", "reachable": true, "hops": 2, "claim_id": null, "node_id": null },
		{ "guid": "a8246306-2b8d-3123-9cbb-157b8684fe30", "hostname": "nd10", "reachable": true, "hops": 1, "claim_id": null, "node_id": null },
		{ "guid": "a5a65bb8-235e-3c98-91ed-6ce4d38f22ef", "hostname": "nd1", "reachable": true, "hops": 2, "claim_id": null, "node_id": null }
	],
```

gp1: http://localhost:20100/api/v1/info (_problematic node after restarts_)
```
	"mirrored_hosts": [
		"nd100",
		"nd10",
		"nd11"
	],
	"mirrored_hosts_status": [
		{ "guid": "71cd4618-2e0b-39f6-8607-546a44ebbf6d", "hostname": "nd100", "reachable": true, "hops": 0, "claim_id": null, "node_id": null },
		{ "guid": "a8246306-2b8d-3123-9cbb-157b8684fe30", "hostname": "nd10", "reachable": true, "hops": 2, "claim_id": null, "node_id": null },
		{ "guid": "eae5179f-c542-36e8-b949-205c2717bebb", "hostname": "nd11", "reachable": true, "hops": 2, "claim_id": null, "node_id": null }
	],
```

gp2: http://localhost:20101/api/v1/info
```
	"mirrored_hosts": [
		"nd101",
		"nd11",
		"nd100",
		"nd0",
		"nd10",
		"nd1"
	],
	"mirrored_hosts_status": [
		{ "guid": "d8c34ffd-a6da-3109-83cb-a58d0bdb66c4", "hostname": "nd101", "reachable": true, "hops": 0, "claim_id": null, "node_id": null },
		{ "guid": "eae5179f-c542-36e8-b949-205c2717bebb", "hostname": "nd11", "reachable": true, "hops": 3, "claim_id": null, "node_id": null },
		{ "guid": "71cd4618-2e0b-39f6-8607-546a44ebbf6d", "hostname": "nd100", "reachable": true, "hops": 1, "claim_id": null, "node_id": null },
		{ "guid": "377eb935-9b5f-3591-b4d6-367c64361ce1", "hostname": "nd0", "reachable": true, "hops": 3, "claim_id": null, "node_id": null },
		{ "guid": "a8246306-2b8d-3123-9cbb-157b8684fe30", "hostname": "nd10", "reachable": true, "hops": 3, "claim_id": null, "node_id": null },
		{ "guid": "a5a65bb8-235e-3c98-91ed-6ce4d38f22ef", "hostname": "nd1", "reachable": true, "hops": 3, "claim_id": null, "node_id": null }
	],
```

ggp1: http://localhost:21000/api/v1/info
```
	"mirrored_hosts": [
		"nd1000",
		"nd11",
		"nd100",
		"nd0",
		"nd10",
		"nd101",
		"nd1",
		"nd1001"
	],
	"mirrored_hosts_status": [
		{ "guid": "36dc7bb9-f199-3ebf-975f-95c52feeb6c8", "hostname": "nd1000", "reachable": true, "hops": 0, "claim_id": null, "node_id": null },
		{ "guid": "eae5179f-c542-36e8-b949-205c2717bebb", "hostname": "nd11", "reachable": true, "hops": 6, "claim_id": null, "node_id": null },
		{ "guid": "71cd4618-2e0b-39f6-8607-546a44ebbf6d", "hostname": "nd100", "reachable": true, "hops": 4, "claim_id": null, "node_id": null },
		{ "guid": "377eb935-9b5f-3591-b4d6-367c64361ce1", "hostname": "nd0", "reachable": true, "hops": 4, "claim_id": null, "node_id": null },
		{ "guid": "a8246306-2b8d-3123-9cbb-157b8684fe30", "hostname": "nd10", "reachable": true, "hops": 6, "claim_id": null, "node_id": null },
		{ "guid": "d8c34ffd-a6da-3109-83cb-a58d0bdb66c4", "hostname": "nd101", "reachable": true, "hops": 2, "claim_id": null, "node_id": null },
		{ "guid": "a5a65bb8-235e-3c98-91ed-6ce4d38f22ef", "hostname": "nd1", "reachable": true, "hops": 4, "claim_id": null, "node_id": null },
		{ "guid": "fc4f7b2e-6d02-3674-a2b4-33d05ec4d214", "hostname": "nd1001", "reachable": true, "hops": 1, "claim_id": null, "node_id": null }
	],
```

ggp2: http://localhost:21001/api/v1/info
```
	"mirrored_hosts": [
		"nd1001",
		"nd11",
		"nd100",
		"nd0",
		"nd10",
		"nd101",
		"nd1000",
		"nd1"
	],
	"mirrored_hosts_status": [
		{ "guid": "fc4f7b2e-6d02-3674-a2b4-33d05ec4d214", "hostname": "nd1001", "reachable": true, "hops": 0, "claim_id": null, "node_id": null },
		{ "guid": "eae5179f-c542-36e8-b949-205c2717bebb", "hostname": "nd11", "reachable": true, "hops": 5, "claim_id": null, "node_id": null },
		{ "guid": "71cd4618-2e0b-39f6-8607-546a44ebbf6d", "hostname": "nd100", "reachable": true, "hops": 3, "claim_id": null, "node_id": null },
		{ "guid": "377eb935-9b5f-3591-b4d6-367c64361ce1", "hostname": "nd0", "reachable": true, "hops": 5, "claim_id": null, "node_id": null },
		{ "guid": "a8246306-2b8d-3123-9cbb-157b8684fe30", "hostname": "nd10", "reachable": true, "hops": 5, "claim_id": null, "node_id": null },
		{ "guid": "d8c34ffd-a6da-3109-83cb-a58d0bdb66c4", "hostname": "nd101", "reachable": true, "hops": 1, "claim_id": null, "node_id": null },
		{ "guid": "36dc7bb9-f199-3ebf-975f-95c52feeb6c8", "hostname": "nd1000", "reachable": true, "hops": 1, "claim_id": null, "node_id": null },
		{ "guid": "a5a65bb8-235e-3c98-91ed-6ce4d38f22ef", "hostname": "nd1", "reachable": true, "hops": 5, "claim_id": null, "node_id": null }
	],
```

### Expected behavior

An active-active node should display all nodes that have an equal or less-than depth level, regardless of restarts.

### Steps to reproduce

1. Setup the aforementioned hierarchy of nodes.
2. Stop/Start the first grandparent a couple times.
3. Check the `api/v1/info` endpoint of the restarted node.

I suspect this can be reproduced even with a single-level of active-active parents, although it might be more difficult to do so.

### Installation method

other

### System info

```shell
Linux nd-01 5.18.7-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jun 25 20:06:14 UTC 2022 x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux bookworm/sid"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Agent built on top f00e4b8a404e3d59b90aa9f1bc294ed5e1832805 with:

CFLAGS='-Wall -Wextra -g -O0' ./netdata-installer.sh --dont-wait --dont-start-it --install ~/opt/master
```

### Additional info

p1 logs:
[access.log](https://github.com/netdata/netdata/files/9038901/access.log)
[error.log](https://github.com/netdata/netdata/files/9038904/error.log)

p2 logs:
[access.log](https://github.com/netdata/netdata/files/9038926/access.log)
[error.log](https://github.com/netdata/netdata/files/9038928/error.log)

gp1 logs:
[access.log](https://github.com/netdata/netdata/files/9038931/access.log)
[error.log](https://github.com/netdata/netdata/files/9038932/error.log)

gp2 logs:
[access.log](https://github.com/netdata/netdata/files/9038933/access.log)
[error.log](https://github.com/netdata/netdata/files/9038934/error.log)

**Comment by MrZammler** [comment]
Hi @vkalintiris . Will check this.

**Comment by vkalintiris** [comment]
@MrZammler for the time being I'm only interested in having the team look into the logs that I've attached, in case I've missed something.

I'll try to reproduce this with a smaller/simpler hierarchy of nodes, I created the issue with the full hierarchy of nodes in order to have this available for future reference.

**Comment by MrZammler** [comment]
Do note (in case it matters) there is a small delay between reconnects (and we should get rid of that), i.e. when disconnecting from one destination and go to another, do allow some time (~30 secs) before the new connection is activated to check the dashboard.

**Comment by vkalintiris** [comment]
> Do note (in case it matters) there is a small delay between reconnects (and we should get rid of that), i.e. when disconnecting from one destination and go to another, do allow some time (~30 secs) before the new connection is activated to check the dashboard.

Right, I've let the whole thing run for ~30 mins. Also, the issue persists even when restarting `gp1` again (which makes me suspect the sender part of the connection is the culprit).

**Comment by vkalintiris** [comment]
Well... multiple levels of active-active configurations are not actually supported (at least, for the time being). The limitation comes from the fact that we can specify the destinations only through `[stream] destination = dst1 dst2 dst3`, and the agent picks only the 1st successful connection.
