### ISSUE TITLE
[Bug]: Applications > mem shows high email usage when exim, postfix, and dovecot aren't installed

### ISSUE THREAD

**Issue by synthead** [netdata/netdata#13292]
### Bug description

The email metric in Applications > mem shows high memory usage on my box:

![image](https://user-images.githubusercontent.com/820984/176970857-8c690f43-0c06-49d1-886c-c87751fa5fd9.png)

The documentation says that this metric gathers data about exim, postfix, and dovecot usage:  https://github.com/netdata/netdata/blob/master/collectors/COLLECTORS.md#email=

However, exim, postfix, and dovecot aren't installed (and the daemons aren't running).

### Expected behavior

"email" metric from Applications > mem should always be 0 when the services it monitors don't exist.

### Steps to reproduce

I am trying to troubleshoot a problem where a large amount of memory is being allocated on my box, so I'm actually trying to find the steps to reproduce this using Netdata!  I am unsure of how to reproduce this, so I'll just make a vague set of steps.

1. Ensure that exim, postfix, and dovecot aren't installed.
2. Run Netdata for 24h.
3. Inspect graph for Applications > mem and observe that email shows data above 0.

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux <censored> 5.18.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 25 Jun 2022 20:22:01 +0000 x86_64 GNU/Linux
/etc/os-release:NAME="Arch Linux"
/etc/os-release:PRETTY_NAME="Arch Linux"
/etc/os-release:ID=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:LOGO=archlinux-logo
```

### Netdata build info

```shell
Version: netdata v1.35.1
Configure options:  '--prefix=/usr' '--sbindir=/usr/bin' '--sysconfdir=/etc' '--libexecdir=/usr/lib' '--localstatedir=/var' '--with-zlib' '--with-math' '--with-user=netdata' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -flto=auto' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

**Comment by ilyam8** [comment]
Hi, @synthead. "Applications > mem" metric source is [apps.plugin](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin#appsplugin). 

- It collects processes metrics (not application-specific metrics) and groups them. So the metrics are per **process groups**. Data collection is reading `/proc/PID/stat` and `/proc/PID/status` for every process.
- Process/group mapping is done by matching the configured list of patterns against `/proc/PID/cmd` or `/proc/PID/cmdline`.


This is the `email` group:

https://github.com/netdata/netdata/blob/f00e4b8a404e3d59b90aa9f1bc294ed5e1832805/collectors/apps.plugin/apps_groups.conf#L124

---

> The documentation says that this metric gathers data about exim, postfix, and dovecot usage:

Those are collectors that collect application-specific metrics.

**Comment by synthead** [comment]
Interesting, it looks like `zmstat*` was added in 2016 with this PR: https://github.com/netdata/netdata/pull/585

ZoneMinder has a script called `zmstats.pl` that I think is getting picked up as a "mail" client by mistake.  Here's the process running on a machine (via `ps -ef`):

```
http         809     741  0 Jul04 ?        00:00:00 /usr/bin/perl -wT /usr/bin/zmstats.pl
```

**Comment by ilyam8** [comment]
I see it was moved from zimbra to email in https://github.com/netdata/netdata/pull/630

**Comment by ilyam8** [comment]
@synthead I think we can exclude that zoneminder script

```yaml
 email: dovecot imapd pop3d amavis* !zmstats.pl zmstat* zmmailboxdmgr saslauthd opendkim postfwd2 smtp* lmtp* sendmail postfix master pickup qmgr showq tlsmgr postscreen oqmgr 
```

**Comment by synthead** [comment]
Awesome!!  Thanks a bunch, @ilyam8!
