### ISSUE TITLE
[Bug]: Fix (possible) data races in the agent

### ISSUE THREAD

**Issue by vkalintiris** [netdata/netdata#13298]
### Bug description

When running netdata under helgrind reports many issues, rendering the tool effectively unusable when trying to verify the correctness of our changes due to the noise.

I'm opening this issue so that we can fix the low-hanging fruit first. Thankfully, most of them seem to be related to non-atomic variables RD/RW accesses. However, some of these variables are used as guards for thread creation and things might go awry without us being able to tell most of the time.

### Expected behavior

Ideally, sanitizers and valgrind tools should report 0 issues. Practically, we should:

- Fix those that seem critical enough and/or add too much noise in the reports of such tools.
- Add suppression files for the rest of them.

### Steps to reproduce

1. Start somewhere a parent.
2. Perform a debug build with -O0.
3. Run the agent as a child with health/ml and all plugins disabled in RAM mode under helgrind.

For example, on Linux:

```
$ cat nd0.conf
[global]
    hostname = nd0
    config directory = /home/vk/repos/tmp/multind/nd0/etc/netdata
    log directory = /home/vk/repos/tmp/multind/nd0/var/log/netdata
    cache directory = /home/vk/repos/tmp/multind/nd0/var/cache/netdata
    lib directory = /home/vk/repos/tmp/multind/nd0/var/lib/netdata
    errors flood protection period = 9999
    errors to trigger flood protection = 99999999
    memory mode = ram

[health]
    enabled = no

[ml]
    enabled = no

[plugins]
    enable running new plugins = no
    timex = no
    checks = no
    idlejitter = no
    tc = no
    diskspace = no
    proc = no
    cgroups = no
    statsd = no
    slabinfo = no
    go.d = no
    charts.d = no
    fping = no
    ioping = no
    python.d = no
    apps = no
    ebpf = no
    macos = no

[web]
    default port = 20000

$ valgrind --tool=helgrind --log-file=helgrind.log --time-stamp=yes ~/opt/master/netdata/usr/sbin/netdata -D -c nd0.conf
```

### Installation method

other

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

### Additional info

- Helgrind report generated by starting & streaming a child to parent (from the child's end): [helgrind-netdata.log](https://github.com/netdata/netdata/files/9040156/r0.log)
- The report attached from helgrind does not include additional errors reported when shutting down the agent.
- The report was generated by running a trimmed-down version of the agent (no health/ml/dbengine/plugins). Additional issues will be reported when enabling additional functionality.

**Comment by Dim-P** [comment]
@vkalintiris Are there more outstanding helgrind issues after the 2 PRs you created above?
