### ISSUE TITLE
[Feat]: Post install if the agent cannot connect to cloud the reason for it should be sent to cloud UI via HTTPs

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13294]
### Problem

When Netdata agent installs successfully using kickstart/claim script - but is not able to connect to cloud for whatever reason - the fact of and reason for this should be communicated to the cloud UI for the user to see. Currently the UI just shows the nodes as offline with no explanation why.

### Description

If the Netdata agent, post install from the kickstart claim script, fails to connect to the cloud and the ACLK connection never gets connected, the agent should communicate through other means (HTTP/HTTPs) some basic information on why the connection failed so that this can be used on the frontend to notify user of potential workarounds. 

The possible reasons where this sort of fallback communication is required are: 
- Agent version is too old
   - If agent version is older than the version required to connect to cloud. This information must be transmitted to cloud so the user can be guided to upgrade the agent using the right commands and method to do so. 
- Agent couldn't be notified/Agent needs a restart
   - If install and claim was successful but agent needs to be restarted. This information must be transmitted to cloud so the user can be guided to restart the agent using the right commands and method to do so. 
- Network or other temporary issue connecting to the cloud

Along with failure reason, the OS name and version must also be transmitted since the workaround or solution could be OS specific. 

### Importance

must have

### Value proposition

1. Users will be able to connect nodes to cloud even if there is a snag during claim

**Comment by shyamvalsan** [comment]
cc: @cpipilas @ktsaou @hugovalente-pm 

We've started work on BE (and soon FE) to detect nodes that are disconnected post install and show appropriate information to users, but the work described in this ticket would be needed from agent side to ensure we can provide accurate steps to recover.

**Comment by hugovalente-pm** [comment]
thanks for the visibility @shyamvalsan, the BE work you are speaking about is this right? Identify newly claimed nodes which are disconnected from cloud netdata/cloud-backend#253

@cpipilas @stelfrag do you think we can prioritize this work on agent side?

**Comment by shyamvalsan** [comment]
Yes @hugovalente-pm 

Without this agent fix, the plan is to do:
- https://github.com/netdata/cloud-backend/issues/253 on BE to identify such nodes
- https://github.com/netdata/cloud-frontend/issues/3594 on FE to notify users about this
- https://github.com/netdata/learn/issues/1080 on Docs for a page to redirect users to

But with this agent fix, we can be more specific about what the user needs to do instead of a generic help page.

P.S: https://github.com/netdata/netdata-cloud/issues/471 is the original ticket, tracking all of  this.

**Comment by ilyam8** [comment]
>  to the cloud and the ACLK connection never gets connected
> the agent should communicate through other means (HTTP/HTTPs)

I am not sure that is possible. @shyamvalsan do we need this issue?
