### ISSUE TITLE
[Bug]: netdata on kubernetes crashing

### ISSUE THREAD

**Issue by marliyev** [netdata/netdata#13307]
### Bug description

new deployment of netdata on k8s cluster all pods crashing

### Expected behavior

n/a

### Steps to reproduce

1. 
2.
3.
...

### Installation method

helmchart (kubernetes)

### System info

```shell
Linux ip-172-31-64-62 5.15.0-1011-aws #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
all pods crashed
```

**Comment by ilyam8** [comment]
Hi, @marliyev. Can you provide more details, e.g.:

- bare-metal/VM or Cloud?
- have you changed any values in the helmchart or just installed using defaults?
- what do you mean by "crashed"? What commands did you use to identify that? Can you share the commands/output?
- did you check Netdata containers logs?

**Comment by marliyev** [comment]
VM
default
kubectel get pods -> all crashed
container logs shows just crashed
i am tried on 10 new k8s cluster, same, netdata just crashing

**Comment by ilyam8** [comment]
Thanks, but I am still not clear what "crashed" is. Can you share both the command output and the logs? Thanks in advance!

**Comment by marliyev** [comment]
> Thanks, but I am still not clear what "crashed" is. Can you share both the command output and the logs? Thanks in advance!

i think you never deployed netdata on k8s cluster! coz netdata not working on k8s!

**Comment by marliyev** [comment]
kubectl describe pod netdata-child-62jrv
Name:         netdata-child-62jrv
Namespace:    default
Priority:     0
Node:         k8s-dev-worker04/10.0.7.70
Start Time:   Tue, 05 Jul 2022 11:27:29 +0000
Labels:       app=netdata
              controller-revision-hash=78f5bcc879
              pod-template-generation=1
              release=netdata
              role=child
Annotations:  checksum/config: 20d6c20fda77afb76a8922767b5592e69684a5cb99cd46e171324d20e27f6265
              container.apparmor.security.beta.kubernetes.io/netdata: unconfined
Status:       Running
IP:           10.0.7.70
IPs:
  IP:           10.0.7.70
Controlled By:  DaemonSet/netdata-child
Init Containers:
  init-persistence:
    Container ID:  docker://13af8f8fefa3556a337866f776606926f9164e3bbf73ffbc761bc574d39545b2
    Image:         alpine:latest
    Image ID:      docker-pullable://alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
       chmod 777 /persistencevarlibdir; 
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 05 Jul 2022 11:27:33 +0000
      Finished:     Tue, 05 Jul 2022 11:27:33 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        10m
    Environment:  <none>
    Mounts:
      /persistencevarlibdir from persistencevarlibdir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w9n8g (ro)
Containers:
  netdata:
    Container ID:   docker://c1b69141cd5bfe7cdf41ba23285863a1b764559c8857a2f65a3fbd665bcc005e
    Image:          netdata/netdata:v1.33.1
    Image ID:       docker-pullable://netdata/netdata@sha256:2301852dc751c7f50f4c2cce5e6d5fc35dd0258f579ddaeca882d3b0591e6839
    Port:           19999/TCP
    Host Port:      19999/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 05 Jul 2022 11:33:26 +0000
      Finished:     Tue, 05 Jul 2022 11:33:26 +0000
    Ready:          False
    Restart Count:  6
    Liveness:       http-get http://:http/api/v1/info delay=0s timeout=1s period=30s #success=1 #failure=3
    Readiness:      http-get http://:http/api/v1/info delay=0s timeout=1s period=30s #success=1 #failure=3
    Environment:
      NETDATA_CLAIM_URL:               https://app.netdata.cloud
      NETDATA_CLAIM_TOKEN:             Jv6XbnUFOxP52BVBwhwWk03TTvi2cm5tGOmL3cJVvqVMVVHaN92PpiKCTi8oGOD7pH7tU34IhfWId102Smf-dKXBVVyWxEWrZrnGSGagLs2-2yQYRM86_Dm7jb_A4KIFH_4DDNU
      NETDATA_CLAIM_ROOMS:             33f8cd73-ecd1-4f02-bc16-27ec691f6c63
      MY_POD_NAME:                     netdata-child-62jrv (v1:metadata.name)
      MY_NODE_NAME:                     (v1:spec.nodeName)
      MY_POD_NAMESPACE:                default (v1:metadata.namespace)
      NETDATA_LISTENER_PORT:           19999
      NETDATA_PLUGINS_GOD_WATCH_PATH:  /etc/netdata/go.d/sd/go.d.yml
    Mounts:
      /etc/netdata/go.d.conf from config (rw,path="go.d")
      /etc/netdata/go.d/k8s_kubelet.conf from config (rw,path="kubelet")
      /etc/netdata/go.d/k8s_kubeproxy.conf from config (rw,path="kubeproxy")
      /etc/netdata/go.d/sd/ from sd-shared (rw)
      /etc/netdata/netdata.conf from config (rw,path="netdata")
      /etc/netdata/stream.conf from config (rw,path="stream")
      /host/etc/os-release from os-release (rw)
      /host/proc from proc (ro)
      /host/sys from sys (rw)
      /var/lib/netdata from persistencevarlibdir (rw)
      /var/run/docker.sock from run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w9n8g (ro)
  sd:
    Container ID:   docker://96b3be854bc059d58b432565e6628a9b01d84d886b168fc7881409c7f610b297
    Image:          netdata/agent-sd:v0.2.3
    Image ID:       docker-pullable://netdata/agent-sd@sha256:a32a819ddd3462de3a2481be323ed20bfb0a15560a89576fd950e233a31f01da
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 05 Jul 2022 11:27:35 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  150Mi
    Requests:
      cpu:     50m
      memory:  100Mi
    Environment:
      NETDATA_SD_CONFIG_MAP:  netdata-child-sd-config-map:config.yml
      MY_POD_NAMESPACE:       default (v1:metadata.namespace)
      MY_NODE_NAME:            (v1:spec.nodeName)
    Mounts:
      /export/ from sd-shared (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w9n8g (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:  
  run:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
  os-release:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/os-release
    HostPathType:  
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      netdata-conf-child
    Optional:  false
  persistencevarlibdir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/netdata-k8s-child/var/lib/netdata
    HostPathType:  DirectoryOrCreate
  sd-shared:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-w9n8g:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 :NoSchedule op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  11m                 default-scheduler  Successfully assigned default/netdata-child-62jrv to k8s-dev-worker04
  Normal   Pulling    10m                 kubelet            Pulling image "alpine:latest"
  Normal   Created    10m                 kubelet            Created container init-persistence
  Normal   Pulled     10m                 kubelet            Successfully pulled image "alpine:latest" in 2.595313037s
  Normal   Started    10m                 kubelet            Started container init-persistence
  Normal   Pulled     10m                 kubelet            Successfully pulled image "netdata/netdata:v1.33.1" in 1.232636218s
  Normal   Pulling    10m                 kubelet            Pulling image "netdata/agent-sd:v0.2.3"
  Normal   Created    10m                 kubelet            Created container sd
  Normal   Started    10m                 kubelet            Started container sd
  Normal   Pulled     10m                 kubelet            Successfully pulled image "netdata/agent-sd:v0.2.3" in 1.192122985s
  Normal   Pulled     10m                 kubelet            Successfully pulled image "netdata/netdata:v1.33.1" in 1.202181085s
  Normal   Pulling    10m (x3 over 10m)   kubelet            Pulling image "netdata/netdata:v1.33.1"
  Normal   Started    10m (x3 over 10m)   kubelet            Started container netdata
  Normal   Created    10m (x3 over 10m)   kubelet            Created container netdata
  Normal   Pulled     10m                 kubelet            Successfully pulled image "netdata/netdata:v1.33.1" in 1.228435973s
  Warning  BackOff    59s (x56 over 10m)  kubelet            Back-off restarting failed container

kubectl logs netdata-child-62jrv -c netdata
ls: /var/run/balena.sock: No such file or directory
Netdata detected docker.sock
Creating docker group 998
Assign netdata user to docker group 998
2022-07-05 11:38:39: netdata INFO  : MAIN : Using host prefix directory '/host'
2022-07-05 11:38:39: netdata INFO  : MAIN : TIMEZONE: using strftime(): 'UTC'
2022-07-05 11:38:39: netdata INFO  : MAIN : TIMEZONE: fixed as 'UTC'
2022-07-05 11:38:39: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
2022-07-05 11:38:39: netdata ERROR : MAIN : LISTENER: IPv4 bind() on ip '0.0.0.0' port 19999, socktype 1 failed. (errno 98, Address in use)
2022-07-05 11:38:39: netdata ERROR : MAIN : LISTENER: Cannot bind to ip '0.0.0.0', port 19999
2022-07-05 11:38:39: netdata ERROR : MAIN : LISTENER: IPv6 bind() on ip '::' port 19999, socktype 1 failed. (errno 98, Address in use)
2022-07-05 11:38:39: netdata ERROR : MAIN : LISTENER: Cannot bind to ip '::', port 19999
2022-07-05 11:38:39: netdata FATAL : MAIN : LISTENER: Cannot listen on any API socket. Exiting... # : Invalid argument

2022-07-05 11:38:39: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2022-07-05 11:38:39: netdata INFO  : MAIN : EXIT: cleaning up the database...
2022-07-05 11:38:39: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
2022-07-05 11:38:39: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...

**Comment by ilyam8** [comment]
You can change [.Values.child.port](https://github.com/netdata/helmchart/blob/88db726b409e92b1d5fa461998f9d1a8e6beb097/charts/netdata/values.yaml#L211-L213) (e.g. adding `--set child.port=20000` when installing the helmchart).

> but i need netdata on node too

Why do you need 2 instances of Netdata running on a host?

**Comment by marliyev** [comment]
thanks

**Comment by marliyev** [comment]
cool, thanks a lot ;)

**Comment by marliyev** [comment]
ok, thanks, anyone can help with this issue?

**Comment by marliyev** [comment]
fixed by deleting helm deployed filesystem pvc and recreating local pvc
