### ISSUE TITLE
[Bug]: Flood of alerts (python.d_job_last_collected_secs, go.d_job_last_collected_secs) which are not actionable

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13310]
### Bug description

Netdata is sending out a huge amount of alert notifications for these two alerts:
- python.d_job_last_collected_secs
- go.d_job_last_collected_secs

### How often do we sent alert notification emails for these alerts?

- In the **last 30 days** these alerts were sent out  **350K** times
- In the **last 7 days** these alerts were sent out **70K** times 
- In the **last 24 hours** these alerts were sent out **20K** times. 

This is a trend that's consistently seen over time. And spread equally across both these alerts.

These alerts indicate that the python (or go) data collection job:
- was collecting metrics before
- hasn’t been able to collect any metrics for the last 5+ iterations in a row

The [guidance](https://community.netdata.cloud/t/python-d-job-last-collected-secs/2036) we provide asks the user to inspect the logs for why the agent cannot collect metrics for a particular job. But this is a **vague** statement and many users will not know what to look for or what to do with what they find.

### Expected behavior

- As a user I expect the alert to be more specific
   - Tell me which specific collector has a problem
- As a user I expect the alert to be more useful
   - Give me more specific directions on how to solve or workaround the problem
   - I am using Netdata to monitor the services I run, I do not want to spend my time investigating why Netdata is not working
- Netdata should figure out which (if any) collectors are mainly causing this problem and (ideally) fix those collectors to prevent this problem rather than leaving it to the users to debug
- If there are cases where there's no reasonable action a user can take to prevent an alert then consider NOT sending a notification for such an alert (and simply displaying the alert in the alerts view) OR at least consider buffering (send one such notification for every X such occurrences)

### Steps to reproduce

N/A

### Installation method

other

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

### Additional info

- The numbers shared above are excluding internal Netdata users, without excluding us the numbers increase by roughly 15% (82K alerts per week, instead of 70K alerts)

- 25-30% of users (not counting internal users) consistently receive these alerts

- Over the last 7 days
   - 2153 unique users have received either of these alerts
   - 2061 of them have received it more than once
   -  829 of them have received it 10+ times
   -  137 of them have received it 100+ times
   -     9 of them have received it 1000+ times

**Comment by shyamvalsan** [comment]
cc: @ktsaou @cakrit @netdata/product

**Comment by MrZammler** [comment]
Hi!

There have been some changes in the past week to reduce the number of those alerts. Also we're trying to make alerts more descriptive in general. And we will focus on these last collected more.

**Comment by hugovalente-pm** [comment]
this was discussed and this bug actually needs to be split into multiple ones:

- [ ] Provide additional information that can help pinpoint where the problem actually is
- [ ] Review the python.d_job_last_collected_secs and go.d_job_last_collected_secs alert names to be more meaningful
- [ ] Understand what problems are happening or configurations tweaks are needed on the collectors to reduce the number of alerts
- [ ] Allow user to define a period to NOT send another notification for such an alert for X period of time

**Comment by hugovalente-pm** [comment]
closing this one as not to be done since we should track the work that sinned out of this one

**Comment by hugovalente-pm** [comment]
closing as per the previous comment https://github.com/netdata/netdata/issues/13310#issuecomment-1183392014
