### ISSUE TITLE
`vsphere` plugin won't grab statistics on vCenter restart

### ISSUE THREAD

**Issue by nghtrifork** [netdata/netdata#13319]
Environment:
- netdata 1.20
- go.d.plugin 0.16.0
- ubuntu 64bit

I have done a restart of the vcenter and the vsphere plugin wouldn't be able to grab the metrics again. This is the message I have seen in the logs:

`2020-03-04 09:30:35: go.d ERROR: vsphere[vcenter1] error on discovering : discovering resources : ServerFaultCode: The object 'vim.view.ContainerView:session[52392fb3-6476-9880-46da-41cfbdc3ef7e]527b5585-e3e8-eb56-d733-b0cb99d654eb' has already been deleted or has not been completely created`

Expected behaviour:
If the session cannot be found (and thus received such an error) I expect vsphere plugin will try to log in agan and continue getting metrics.

After a restart of netdata (and creating a new vsphere session) all metrics were back as expected

**Comment by cakrit** [comment]
This has been here for too long and it's an edge case that is problematic for us to replicate, since we need to keep getting 60 day trials and reinstalling every time we want to try something. 

The workaround is to restart netdata after a vcenter restart.
