### ISSUE TITLE
One failed check breakes all the others

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#13317]
**Environment:**
OS: Linux 5.10.110-gentoo x86_64
Netdata version: netdata-1.34.1-r1
Go.d plugin: 0.31.2

Same used to happen with Netdata-1.33 and all the versions of plugin tested (using since 0.30.0 at least)

**The issue:**
Several checks configured to be monitored with go.d plugin, for instance mysql, nginx, directory check and some other things.
Mysqld has certain misconfiguration and performs slowly. On certain point an alert is sent about failure of mysql check (that's reasonable as can be caused with timeout).
However, in 3-5 minutes several more false positive alerts appear, for example, nginx check, while service has no performance issues.
An alert is followed by next bunch:
```
go.d job last collected secs = 00:01:10 ago (netdata.execution_time_of_nginx_local_IPv4 go.d)
go.d job last collected secs = 00:03:27 ago (netdata.execution_time_of_filecheck go.d)
```
and so on.
This renders monitoring useless as all these alerts recover only with netdata restart or removal of first (failing mysql) check.
Moreover. Even in case nginx alert can be explained with relation to mysql (but in fact system has no issues with nginx performance), the filecheck relies on filesystem only, so it's just checked with the same plugin and thus fails. There are some other failing checks that have no connection to mysql except for being checked with same go.d plugin instance.
Unfortunately, nothing is logged into netdata log file for this issue except normal messages about sending alerts into different channels.

**Expected behavior:** on one failing check others should not affect other services.

**Comment by ilyam8** [comment]
Hey, @ekexcello. Do you still have the issue? Perhaps it was connected with #13175.

**Comment by ekexcello** [comment]
Hello @ilyam8 
It might be connected, but it will be clear a bit later whether this is gone or not: this is usually visible during extended maintenance with services taken down and up. Last weeks this wasn't happening, at least, but no big maintenance happened also.

**Comment by ilyam8** [comment]
> go.d job last collected secs = 00:01:10 ago (netdata.execution_time_of_nginx_local_IPv4 go.d)
> go.d job last collected secs = 00:03:27 ago (netdata.execution_time_of_filecheck go.d)

A bunch (for every data collection job) of "last collected secs" alarms means the plugin got stopped/disabled by Netdata. There should be a reason why in the logs (`grep -i plugsind error.log`).

**Comment by ilyam8** [comment]
@ekexcello closing for now. I will reopen if there is new info.
