### ISSUE TITLE
Breaking changes for Netdata Agent 2.0

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#13347]
### Problem

There are a number of changes that will break backwards compatibility. So, users who are using Netdata and have integrated it to their monitoring stack may experience incompatibilities after an upgrade to a Netdata with these changes.

The same is true when using multiple Netdata Agents versions at the cloud. New and old Netdata Agents may produce incompatible results that cannot be aggregated to a single view.

### Description

These are the changes we need to introduce, but they will break backwards compatibility:

1. All collectors should report metrics in natural units (e.g. bytes, instead of kilobytes, megabytes, etc).
  
2. All contexts should be changed to comply to our new Metric Types, which is closer to OpenTelemetry. This change will allow the dashboard menu to be rendered exclusively on contexts, without the need for `family` and `priority`.
  
3. Find a way so that charts with the same prototype (e.g. cgroups.cpu) will have the same context, although a separate section on the dashboard (e.g. containers, k8s containers, systemd services).
  
3. Remove `family` and `priority` from the metadata. Removing the `family` means we need a different alarm variables index (per data collection job?).
  
5. Negative dimensions should be a flag for visualization, not stored in the database as negative.
  
6. All dimension names should be lower case.

7. Charts/Instances should be given an id and name automatically.

6. Remove `chart type` and replace it with new metadata according to our new Metric Types, which should be based on chart labels.
  
9. We need a new datatype to name instances in a more friendly way. For example, instances may be disks, network interfaces, processes, containers, tables, databases, nginx web servers, log files, or whatever. Adding a new datatype to replace the word `instances` with something more appropriate for each chart, will significantly improve learning curve with Netdata.

10. Update the chart titles to reflect the kind of instances they monitor. For example, cgroups cpu title should be "CGROUP CPU Usage", not just "CPU Usage".

11. New plugins.d protocol to allow more flexible use of metadata.
  
12. ~~New streaming protocol version.~~ done
  
13. ~~New defaults for tiering to improve retention (use up to 2GB of disk space and store up to 5 years of retention for 2k metrics)~~ done

14. Each alarm should be shipped on its own file so that users can overwrite each of them without sourcing all the others.

### Importance

blocker

### Value proposition

1. Better compatibility with the industry standards (natural units, non-negative-metrics and contexts)
2. More generic mechanism to build the dashboards with less heuristics (at last remove "my shame", use more flexible metric types to control visualization)
3. Better defaults for all users

### Proposed implementation

Each of these should be on its own ticket, explaining what we will do.

**Comment by vkalintiris** [comment]
> 4. Negative dimensions should be a flag for visualization, not stored in the database as negative.

> 6. New plugins.d protocol to allow more flexible use of metadata.

I'm curious about these two, we can discuss them in more detail on the separate issues that we will open.

Also, since we are on the topic of breaking changes for 2.0, it would be nice if we could add improvements in the streaming version negotiation on the list.

**Comment by ktsaou** [comment]
> Also, since we are on the topic of breaking changes for 2.0, it would be nice if we could add improvements in the streaming version negotiation on the list.

added it

**Comment by ktsaou** [comment]
@ralphm check this.

**Comment by hugovalente-pm** [comment]
> 2. All contexts should be changed to comply to our new Metric Types, which is closer to OpenTelemetry. This change will allow the dashboard menu to be rendered exclusively on contexts, without the need for family and priority.

> 3. Find a way so that charts with the same prototype (e.g. cgroups.cpu) will have the same context, although a separate section on the dashboard (e.g. containers, k8s containers, systemd services).

These two relate to this work https://github.com/netdata/netdata-cloud/issues/354 where me and @ilyam8 had been iterating on an approach to tackle it https://github.com/ilyam8/nd-ctx-menu. This approach doesn't give the solution to 3. (initial idea was to have, for example, k8s as a prefix on the context)

**Comment by underhood** [comment]
There were some internal discussions regarding netdata 2.0 already. Is this issue meant to encompass all of them or only the new "metric organisation model" described above?

**Comment by ktsaou** [comment]
> There were some internal discussions regarding netdata 2.0 already. Is this issue meant to encompass all of them or only the new "metric organisation model" described above?

Everything that breaks compatibility, default behavior, etc should be here.
