### ISSUE TITLE
[Feat]: ML should now stop producing new metrics for the anomaly rate

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#13344]
### Problem

ML is creating a hidden chart with the anomaly rate of all dimensions.

Now that we have tiering and a new query engine that can automatically select the optimal tier to query, and it also calculates anomaly rates together and in parallel with data queries, we should stop duplicating the metrics.

Duplication of the metrics heavily impacts the memory footprint of dbengine and it also lowers significantly its retention. This is now unecessary.

### Description

The new metrics correlations algorithm (`volume`) is similar to what we should be doing to get anomaly rates across the entire set of metrics for any given duration. And it is extremely fast!

### Importance

must have

### Value proposition

1. Lower the memory footprint of dbengine, by eliminating duplicate metrics
2. Increase the available retention of dbengine, by eliminating duplicate metrics
3. Eliminate a hard working runtime thread that computes and stores the anomaly rate chart for every metric

### Proposed implementation

Based on the new metrics correlations algorithm (`volume`) we will have a similar result without the need to store duplicate metric data.

**Comment by ktsaou** [comment]
@vkalintiris @andrewm4894

**Comment by vkalintiris** [comment]
Not applicable (and hence not an issue) any more.
