### ISSUE TITLE
[Bug]: Agent not sending metrics to parent node periodically

### ISSUE THREAD

**Issue by dr460nf1r3** [netdata/netdata#13356]
### Bug description

Continuing the discussion from here: https://github.com/netdata/netdata/issues/13326#issuecomment-1179678994
One agent does not successfully stream metrics at times, resulting in false alerts and no data.

![image](https://user-images.githubusercontent.com/12834713/178235965-485d4397-9ed0-4e43-b5f8-3329ecd2019d.png)

Parents log of the time period: https://bin.garudalinux.org/?8fff06a6e5dbc886#5bzpXVMqQMZfuiv8oj8NYxj9bM8vNXsypM3naeKn3eHh
Child log of the time period: https://bin.garudalinux.org/?4659b02d9858f2e3#Biv1oB8C7SfBcsb1tcfAMsaBiVEioGpKZ3q7go6XaYJn

stream.conf child:
```
[stream]
    api key = {{ netdata_stream_token }}
    buffer size bytes = 15728640
    destination = {{ netdata_stream_parent_ip }}
    enable compression = yes
    enabled = yes

[logs]
    debug log = none
    error log = none
    access log = none
```
stream.conf parent:
```
[{{ netdata_stream_token }}]
    allow from = *
    default memory node = dbengine
    enable compression = yes
    enabled = yes
    health enabled by default = auto
```
netdata.conf child:
```
[global]
    memory mode = none
    update every = 2
[web]
    mode = none
```
netdata.conf parent:
```
[global]
    dbengine multihost disk space = 40960
    page cache size = 32
    update every = 2
```

### Expected behavior

The stream works without issues.

### Steps to reproduce

This probably can't be reproduced as I have 10+ other agents running the same settings without issues. 

### Installation method

docker

### System info

```shell
Linux garuda-build 5.18.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 07 Jul 2022 17:18:13 +0000 x86_64 GNU/Linux
/etc/os-release:NAME="Arch Linux"
/etc/os-release:PRETTY_NAME="Arch Linux"
/etc/os-release:ID=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:LOGO=archlinux-logo
```

### Netdata build info

```shell
Version: netdata v1.35.0-161-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--with-bundled-libJudy' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

- The nodes stream to the parent via Zerotier SDN, the connection seems to be stable judging from a ping I left running. 
- 10+ other nodes run the same configuration without issues. 
- No apparent high load on both child & parent
- After applying suggestions of the linked issue, the occurrences became less but didn't stop happening

**Comment by dr460nf1r3** [comment]
Hey :) 
So yes, the problem continues but it did indeed happen less. I increased the timeout value, now I'm evaluating the result. Will get back at you once I have some data :)

**Comment by MrZammler** [comment]
Hi @dr460nf1r3 !

Is there any update on this? 

Thanks!

**Comment by MrZammler** [comment]
Nico, will close this. If the issue persists with newer versions of agent, do let us know to have a look. Thanks!

**Comment by dr460nf1r3** [comment]
Hey @MrZammler ! Sorry for the very late reply, this somehow slipped through my issues. In the end, we eventually ended up replacing the container and haven't had issues since. Now happily running Netdata on Nix based infrastructure. Sorry for letting this get stale again!

**Comment by MrZammler** [comment]
No problem @dr460nf1r3 thanks for following up!
