### ISSUE TITLE
[Bug]: Review the python.d_job_last_collected_secs and go.d_job_last_collected_secs alert names to be more meaningful

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#13377]
### Bug description

These alert names current aren't meaningful to the user, we should review them to mention clearly that this is a Netdata collector failure or something similar

### Expected behavior

Have more meaningful alert names presented to the user

### Steps to reproduce

N/A

### Installation method

other

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

### Additional info

N/A

**Comment by hugovalente-pm** [comment]
as part of the discussions different scenarios were considered and we seemed to fall into the conclusion that we should:
* have the current name as the `id` of the alert
* the `name` field should be used as a more meaningful to the user (same cases it could be the same as the `id`)
* the `name` field should be able to be complemented with variables (e.g. `$family` or some chart labels)

**Comment by MrZammler** [comment]
Hi @hugovalente-pm 

Mind if I close this?

The go.d last collected alerts where disabled with #13485 and there is also a similar one #13310 ?

**Comment by MrZammler** [comment]
Ok, sorry this was forked from #13310, will leave open.

**Comment by hugovalente-pm** [comment]
@MrZammler since we have forked the #13310 into multiple ones that probably means that one can be closed as `won't do` mentioning that lower task bugs/tickets have been opened. wdyt?

**Comment by hugovalente-pm** [comment]
actually, I had mentioned that but didn't close it... my bad
https://github.com/netdata/netdata/issues/13310#issuecomment-1183392014

**Comment by MrZammler** [comment]
This is similar I guess to https://github.com/netdata/netdata/issues/13376, i.e. provide more meaningful info in the alerts. We continue there I think, ok @hugovalente-pm ?
