### ISSUE TITLE
[Bug]: Understand what problems are happening or configurations tweaks are needed on the collectors to reduce the number of alerts

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#13378]
### Bug description

Following the report on https://github.com/netdata/netdata/issues/13310 we have these alerts being triggered to often and flooding the users'

### Expected behavior

We should dive into to understand the collector failures that are happening and if there is some fix to be done or we need to adjust our configurations

### Steps to reproduce

N/A

### Installation method

other

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

### Additional info

N/A

**Comment by ilyam8** [comment]
I think we can close this issue. A relevant discussion is [happening here](https://github.com/netdata/netdata/discussions/14059).

**Comment by hugovalente-pm** [comment]
@ilyam8 this bug is a different case, the discussion you mention is to better surface to the user the reason why the alert was triggered (better title displayed on UI and notifications) this bug is about
> Following the report on https://github.com/netdata/netdata/issues/13310 we have these alerts being triggered to often and flooding the users'

if you look to the linked ticket these are the relevant stats

> Netdata is sending out a huge amount of alert notifications for these two alerts:
>   * python.d_job_last_collected_secs
>   * go.d_job_last_collected_secs

> How often do we sent alert notification emails for these alerts?
>   * In the last 30 days these alerts were sent out 350K times
>   * In the last 7 days these alerts were sent out 70K times
>   * In the last 24 hours these alerts were sent out 20K times.

**Comment by ilyam8** [comment]
@hugovalente-pm can you please explain how to fix this issue? To change all alerts INFO? Some specific alerts INFO? To change in what way?

> We should dive into to understand the collector failures that are happening and if there is some fix to be done or we need to adjust our configurations

If you were referencing only to those two alarms - Netdata is no longer sending them.

**Comment by andrewm4894** [comment]
I think there should be some easy way for NC to scan for "potential misconfigured alerts" or "regular alerts" and suggest some action. 

It could literally just be some heuristics or business logic somewhere in NC , or the agent even, to just look for obviously "regular" alerts and tag them as such.

So trying to come at it from a different angle of not trying to root cause the alert itself, just accept it happens and make it easy for use to spot them and deal with them. It's never going to be one size fits all so I think coming at it from top down as another sort of layer in NC or even the agent have a check to scan last 24 hours or few days and just tag regular alerts that occur with some silly frequency (and make it a customizable config param even perhaps).

**Comment by ilyam8** [comment]
@andrewm4894 I don't understand what you are suggesting. To do exactly what? It was decided to have additional information + steps to debug as community forum topics. tkatsoulas and Ancairon spent quite a lot of time working on this.

btw, what is NC?

**Comment by hugovalente-pm** [comment]
> If you were referencing only to those two alarms - Netdata is no longer sending them.

yes, the original ticket this bug derived from was just for those two alerts, so if we no longer send them this can be closed but not because of the other discussion 😄 

> * python.d_job_last_collected_secs
> * go.d_job_last_collected_secs

IIRC @shyamvalsan was looking to the sendgrid stats of sent notifications per alert and those where main offenders

@andrewm4894 's suggestion is an interesting one but it isn't part of this bug, we may already have some ticket about that I can try to find it.
