### ISSUE TITLE
[Bug]: zero alarms and no alarm logs displayed in dashboard - kind cluster

### ISSUE THREAD

**Issue by Garahk** [netdata/netdata#13375]
### Bug description

I have a test environment, where a k8s cluster has been deployed using kind. There I deployed netdata using helm charts

The alarm's section of the dashboard shows zero alarms critical/warning, despite doing stress tests: 

![image](https://user-images.githubusercontent.com/99432183/178767008-77d517c7-2512-4239-9977-56e800a79512.png)

The section of alarm logs won't also display any event:

![image](https://user-images.githubusercontent.com/99432183/178767157-b1cbd3d1-ffb4-4888-92ba-059c198ac6f5.png)

### Expected behavior

The alarms/alarm.logs section to provide any active crit/war alarms, and the alarm logs to show the past and present events, similarly to the capture below:

![image](https://user-images.githubusercontent.com/99432183/178770426-46fdeca9-9b8f-41d4-af79-1fbda105ffa7.png)

### Steps to reproduce

1. Log into netdata's dashboard
2. Access the alarms section and find zero crit/warnings
3. Access the alarm logs and find zero events

### Installation method

helmchart (kubernetes)

### System info

```shell
Linux niaK8s 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
Version: netdata v1.35.0-161-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--with-bundled-libJudy' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

This is single node deployment.

Thank you in advance

**Comment by Garahk** [comment]
> What instance? parent or child?


@ilyam8 , seems I was looking at the child instance, but reading on documentation is the parent who handles the alarms and alerts, is that correct? or can the child also handle alarms?


> Can you please check the output of http://node:19999/api/v1/alarms?all ? At first look it seems that no alarms where loaded...
> 
> Can you check the directory /usr/lib/netdata/conf.d/health.d/ that it has alarm configurations, and also that in netdata.conf that health enabled = yes ?

@MrZammler , I looked at the child instance and the health is disabled,

![image](https://user-images.githubusercontent.com/99432183/178780156-8d7156d8-1ac7-4d35-a420-56c37bd7fcdc.png)

while the parent has health enabled by default?:

![image](https://user-images.githubusercontent.com/99432183/178780239-381cc84b-1b56-4192-bda8-007010873c88.png)

Here's a sample of what seems to be cleared alarms in the parent:

![image](https://user-images.githubusercontent.com/99432183/178780649-0218f31f-ebfc-449e-b4fb-5372b96f6142.png)

On the right menu (parent), only 3 sections are present (system overview, anomaly detection and netdata monitoring), is this correct, will it still provide alarms triggered by pod's usage?

![image](https://user-images.githubusercontent.com/99432183/178780785-2b3b5e39-5e25-4350-9bbd-5031908b9cb8.png)

**Comment by ilyam8** [comment]
@Garahk the helmchart default is disabled health on children and enabled on the parent. The parent instance does health checks for chidren metrics.

**Comment by ilyam8** [comment]
> On the right menu (parent), only 3 sections are present (system overview, anomaly detection and netdata monitoring), is this correct, will it still provide alarms triggered by pod's usage?

Because almost all the collectors disabled on the parent instance - there is a child netdata that runs on the same host and it collects metrics.
