### ISSUE TITLE
[Bug]: Provide additional information that can help pinpoint where the problem actually is

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#13376]
### Bug description

For now, on the below alerts we need to be able to show additional information that will help the user pinpoint where the actual problem is:
* python.d_job_last_collected_secs, go.d_job_last_collected_secs: which module from the collectors actually failed
* httpcheck_web_service_unreachable: which URL was unreachable (reported here also https://github.com/netdata/netdata-cloud/issues/130)
* fping alerts - fping_host_reachable and fping_host_latency: which host was unreachable or had the latency

### Expected behavior

We should have these additional details coming as part of the alert info on:
* Notifications
* Alerts drawer
* Alerts dedicated page

### Steps to reproduce

N/A

### Installation method

other

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

### Additional info

N/A

**Comment by ilyam8** [comment]
Related discussion: https://github.com/netdata/netdata/discussions/14059. @hugovalente-pm do we need to keep this issue open? I think the title is 100% correct but it is blocked by the discussion.

**Comment by hugovalente-pm** [comment]
@ilyam8 I would say yes, the discussion was triggered to find the solution to tackle this bug. until we implement something this can't be closed since we didn't solve it
I added a comment to the discussion to see if we agree on what needs to be done

**Comment by MrZammler** [comment]
This should be ok after the `summary` field in alerts.
