### ISSUE TITLE
[Feat]: Go collector for PostgreSQL

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13387]
### Description

A better performant Go collector for PostgreSQL must be created and used as the default. Currently only a Python collector exists, which also has a 3rd party package dependency.

---

https://github.com/netdata/product/issues/2956

### Importance

really want

### Value proposition

1. Will enable Netdata to include Postgres in service discovery in K8s environments
2. Better performance while collecting Postgres metrics

**Comment by thiagoftsm** [comment]
Hello @shyamvalsan and @ilyam8 ,

Go collector will need a dependency to communicate with PostgreSQL server, and in the best case scenario this dependency will use protocol V3 to speed up some analysis from our end.  Of course due the fact we are talking about `Go`, we will have an improvement due the fact we will use as static binary.

A quick research shows that we have at least two projects ([lib/pq](https://github.com/lib/pq) and (go-pg)[https://github.com/go-pg/pg]) that can help us.

**Comment by thiagoftsm** [comment]
I forgot one important thing, like python plugin we will need to ensure that our plugin is working in different versions of the database, including the future [15](https://www.postgresql.org/about/news/postgresql-15-beta-2-released-2479/)

**Comment by shyamvalsan** [comment]
Interesting open source tool written in go which collects most postgres metrics we need

https://github.com/rapidloop/pgmetrics

**Comment by thiagoftsm** [comment]
> Interesting open source tool written in go which collects most postgres metrics we need

I read few parts of the code, and I agree with your initial impression. I liked the fact that it is monitoring PostgreSQL since version `9.4`, and it also  taking care of `WAL` and `Replication`.

**Comment by shyamvalsan** [comment]
Interestingly they also have a section on AWS RDS monitoring via cloudwatch, which is also something we need. 

https://pgmetrics.io/docs/aws.html

**Comment by ilyam8** [comment]
@anayrat, @NikolayS, @unhandled-exception, hey guys 👋 We plan to rewrite python Postgres collector in go and improve it (add new metrics, change grouping, etc). Can we use your expertise to help us with improving it (e.g. ask questions, test new version)?

**Comment by anayrat** [comment]
Great! I think, the most suitable driver is https://github.com/jackc/pgx

**Comment by unhandled-exception** [comment]
> ... @unhandled-exception, hey guys 👋 We plan to rewrite python Postgres collector in go and improve it (add new metrics, change grouping, etc). Can we use your expertise to help us with improving it (e.g. ask questions, test new version)?

I'm ready to help.

**Comment by ilyam8** [comment]
Current status:

- [X] [QUERY_WAL](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L174)
- [X] [QUERY_ARCHIVE](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L231)
- [X] [QUERY_BACKEND_USAGE](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L266)
- [X] [QUERY_TABLE_STATS](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L336)
- [X] [QUERY_INDEX_STATS](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L346)
- [X] [QUERY_DATABASE](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L356)
- [X] [QUERY_BGWRITER](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L379)
- [X] [QUERY_LOCKS](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L394)
- [X] [QUERY_DATABASES](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L450)
- [X] [QUERY_SUPERUSER](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L663)
- [X] [QUERY_SHOW_VERSION](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L669)
- [X] [QUERY_FORCED_AUTOVACUUM](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L690)
- [X] [QUERY_TX_WRAPAROUND](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L708)
- [X] [QUERY_DIFF_LSN](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L727)
- [ ] [QUERY_STANDBY](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L463)
- [ ] [QUERY_REPLICATION_SLOT](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L473)
- [ ] [QUERY_STANDBY_DELTA](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L480)
- [ ] [QUERY_STANDBY_LAG](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L545)
- [ ] [QUERY_REPSLOT_FILES](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L558)

**Only replication related metrics are missing**. Need to setup replication in my lab.

Questionable queries:

- [ ] [QUERY_BACKEND](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L251)
  >  I believe the query is wrong (active backend calculation), do we need this metric?
- [ ] [QUERY_BLOCKERS](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L408)
  >  Do we really need this metric?
- [ ] [QUERY_AUTOVACUUM](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L675)
  > I couldn't find autovacuum "workers" type description in the doc, need to the Postgres source code. Questionable metric. Do we need it?

**Comment by anayrat** [comment]
>     * [ ]  [QUERY_BACKEND](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L251)
>       > I believe the query is wrong (active backend calculation), do we need this metric?

Yes, it is really weird how the calculation is done. Maybe you can look at how it is done check_pgactivity https://github.com/OPMDG/check_pgactivity/blob/master/check_pgactivity#L2347

> 
>     * [ ]  [QUERY_BLOCKERS](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L408)
>       > Do we really need this metric?

I don't think we need this if we use a query like the one I mentioned above. We just want how many backends are waiting for a lock.

> 
>     * [ ]  [QUERY_AUTOVACUUM](https://github.com/netdata/netdata/blob/221fd512873613a10b3d95b25a8a4d542b2c4801/collectors/python.d.plugin/postgres/postgres.chart.py#L675)
>       > I couldn't find autovacuum "workers" type description in the doc, need to check the Postgres source code. Questionable metric. Do we need it?

I think yes, I could be useful to know what kind of autovacuum is running.

**Comment by ilyam8** [comment]
> I think yes, I could be useful to know what kind of autovacuum is running.

Ok, possible "workers"

- [src](https://github.com/postgres/postgres/blob/9e4f914b5eba3f49ab99bdecdc4f96fac099571f/src/backend/postmaster/autovacuum.c#L3168-L3183)
  - `autovacuum: VACUUM`
  - `autovacuum: VACUUM ANALYZE`
  - `autovacuum: ANALYZE`

^^ All these 3 can have `(to prevent wraparound)`
- [src](https://github.com/postgres/postgres/blob/9e4f914b5eba3f49ab99bdecdc4f96fac099571f/src/backend/postmaster/autovacuum.c#L3206-L3207)
  - `autovacuum: BRIN summarize`

**Comment by ilyam8** [comment]
Ok, I think our query is wrong because all "to prevent wraparound" should go into "vacuum_free" - https://github.com/OPMDG/check_pgactivity/blob/4e6d9c4076f7f7b680c57b2b7cf1dac8406f8052/check_pgactivity#L2135-L2145

**Comment by ilyam8** [comment]
@unhandled-exception @anayrat I have a question regarding QUERY_STANDBY%% queries. 

- I set up replication following this [Digital Ocean guide](https://www.digitalocean.com/community/tutorials/how-to-set-up-physical-streaming-replication-with-postgresql-12-on-ubuntu-20-04). I use docker, so all the standby instances have the same IP address (127.0.0.1).
- I see we use `pg_replication_slots.slot_name` and `pg_stat_replication.application_name` (joined by pid) to uniquely identify standby.
- However, in my setup, there are no replication slots.

| pid | usesysid | usename  | application_name | client_addr | client_hostname | client_port | backend_start              | backend_xmin | state | sent_lsn  | write_lsn | flush_lsn | replay_lsn | write_lag | flush_lag | replay_lag | sync_priority | sync_state | reply_time |
|-----|----------|----------|------------------|-------------|-----------------|-------------|----------------------------|--------------|-------|-----------|-----------|-----------|------------|-----------|-----------|------------|---------------|------------|------------|
| 513 | 10       | postgres | walreceiver      | 127.0.0.1   |                 | 36098       | 2022-07-28 18:13:43.066347 | 00           |       | streaming | 0/5000148 | 0/5000148 | 0/5000148  | 0/5000148 |           |            |               | 0          | async      | 2022-07-28 18:32:11.002285|00   |
| 548 | 10       | postgres | walreceiver      | 127.0.0.1   |                 | 56232       | 2022-07-28 18:20:40.075688 | 00           |       | streaming | 0/5000148 | 0/5000148 | 0/5000148  | 0/5000148 |           |            |               | 0          | async      | 2022-07-28 18:32:11.002207|00  |

The questions: what is the correct way to uniquely identify a standby instance?

**Comment by ilyam8** [comment]
Closing this issue because the [initial implementation](https://github.com/netdata/go.d.plugin/tree/master/modules/postgres#postgresql-monitoring-with-netdata) is done. Go version collects the same metrics (slightly different grouping, metric names) + adding/removing new databases/replication standby at runtime (was requested in #9822).

The new version of go.d.plugin with Postgres collector will be released today (available in nightlies tomorrow).

We will continue to improve the collector. Any suggestions are welcome - it will be relatively easy to implement them for now (compared to the python version).
