### ISSUE TITLE
[Feat]: Missing after compilation and installation netdata.sevice

### ISSUE THREAD

**Issue by zhangke-zk** [netdata/netdata#13386]
### Problem

 Missing after compilation and installation netdata.sevice

### Description

Use the following methods compile :
autoreconf -ivf
./configure --prefix=/root/test/netdata/bin --sysconfdir=/root/test/netdata/bin/etc --localstatedir=/root/test/netdata/bin/var --libexecdir=/root/test/netdata/bin/usr/libexec --disable-x86-sse --host=arm-linux 
make 

install:
make install 

### Importance

really want

### Value proposition

1.After the installation is complete, the netdata.service file is not available. When starting NetData, you need to configure the netdata.conf configuration file and create many folders. Therefore, you are advised to add netdata.service to the installation file

### Proposed implementation

Modify Makefile

**Comment by MrZammler** [comment]
Hi @zhangke-zk 

Any reason why you use this to compile? Can you check the [kickstart](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart/) script? It should handle most of the cases you refer to.
