### ISSUE TITLE
The installer failed to prepare the required dependencies for Netdata Cloud functionality

### ISSUE THREAD

**Issue by caroffer12** [netdata/netdata#13430]
### Bug description

Hi Team,

we are using netdata cloud and installed the agent with one-line installer on the ubuntu server it was working for long time. when we restarted our server last week netdata stopped working. we tried to reinstall netdata using the below command . But it still doesn't work. can you please check on this.
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --reinstall

### Expected behavior

Netdata needs to run on the server without any error and I should be able to see my server on the cloud url. https://app.netdata.cloud/spaces/carofferawsprod

### Steps to reproduce

1.To fix the issue i reinstall the agent on the server 
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --reinstall
2.Checked the firewall is opened on the server 

```cmd
 netstat -ntul
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9443            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:33895         0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::1311                 :::*                    LISTEN
tcp6       0      0 :::19999                :::*                    LISTEN
tcp6       0      0 :::8000                 :::*                    LISTEN
tcp6       0      0 :::9443                 :::*                    LISTEN
udp        0      0 127.0.0.1:8125          0.0.0.0:*
udp        0      0 127.0.0.53:53           0.0.0.0:*
udp        0      0 127.0.0.1:161           0.0.0.0:*
udp6       0      0 ::1:161                 :::*
3.
...
```

### Installation method

kickstart.sh

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux ubuelastic 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
$(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
Version: netdata v1.35.0-206-g94a783fc6
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' '--with-bundled-libJudy' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

 But when i check curl http://localhost:19999/api/v1/info . I see agent-claimed and aclk-available is false

```json
  "cloud-enabled": true,
        "cloud-available": true,
        "aclk-ng-available": true,
        "aclk-ng-new-cloud-protocol": true,
        "aclk-legacy-available": false,
        "aclk-implementation": "Next Generation",
        "agent-claimed": false,
        "aclk-available": false,
        "aclk-available-protocol": null,
        "memory-mode": "dbengine",
        "multidb-disk-quota": 256,
        "page-cache-size": 32,
        "stream-enabled": false,
        "stream-compression": true,
        "hosts-available": 1,
        "https-enabled": true,
        "buildinfo": "dbengine|Native HTTPS|Netdata Cloud|ACLK Next Generation|New Cloud Protocol Support|TLS Host Verification|Machine Learning|Stream Compression|protobuf|JSON-C|libcrypto|libm|zlib|apps|cgroup Network Tracking|EBPF|perf|slabinfo|Prometheus Remote Write",
        "release-channel": "nightly",
        "web-enabled": true,
        "notification-methods": "",
        "exporting-enabled": false,
        "exporting-connectors": "",
        "allmetrics-prometheus-used": 0,
        "allmetrics-shell-used": 0,
        "allmetrics-json-used": 0,
        "dashboard-used": 0,
        "charts-count": 808,
        "metrics-count": 5043,
        "ml-info": {
```

When i check the status of the service . I see the below commands
systemctl status netdata

```cmd
● netdata.service - Real time performance monitoring
     Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-07-25 14:41:40 UTC; 40min ago
    Process: 3079753 ExecStartPre=/bin/mkdir -p /opt/netdata/var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 3079758 ExecStartPre=/bin/chown -R netdata:netdata /opt/netdata/var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 3079769 ExecStartPre=/bin/mkdir -p /opt/netdata/var/run/netdata (code=exited, status=0/SUCCESS)
    Process: 3079771 ExecStartPre=/bin/chown -R netdata:netdata /opt/netdata/var/run/netdata (code=exited, status=0/SUCCESS)
   Main PID: 3079773 (netdata)
      Tasks: 100 (limit: 308719)
     Memory: 228.8M
     CGroup: /system.slice/netdata.service
             ├─3079773 /opt/netdata/bin/srv/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D
             ├─3079775 /opt/netdata/bin/srv/netdata --special-spawn-server
             ├─3080014 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
             ├─3080017 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
             ├─3080021 /opt/netdata/usr/libexec/netdata/plugins.d/ebpf.plugin 1
             ├─3080031 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
             └─3080041 /usr/bin/python3 /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1

Jul 25 14:41:40 ubuelastic systemd[1]: Starting Real time performance monitoring...
Jul 25 14:41:40 ubuelastic systemd[1]: Started Real time performance monitoring.
Jul 25 14:41:40 ubuelastic [3079773]: CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
Jul 25 14:41:40 ubuelastic netdata[3079773]: 2022-07-25 14:41:40: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
Jul 25 14:41:41 ubuelastic [3080021]: Does not have a configuration file inside `/opt/netdata/etc/netdata/ebpf.d.conf. It will try to load stock file.
Jul 25 14:41:41 ubuelastic [3080021]: Name resolution is disabled, collector will not parser "hostnames" list.
Jul 25 14:41:41 ubuelastic [3080021]: The network value of CIDR 127.0.0.1/8 was updated for 127.0.0.0 .
Jul 25 14:41:41 ubuelastic [3080021]: Cannot read process groups configuration file '/opt/netdata/etc/netdata/apps_groups.conf'. Will try '/opt/netdata/usr/lib/netdata/conf.d/apps_groups.conf'
```

**Comment by ilyam8** [comment]
Hi, @caroffer12. It looks like there is no problem with dependencies, because you have

```
        "cloud-available": true,
        "aclk-ng-available": true,
        "aclk-ng-new-cloud-protocol": true,
        "aclk-legacy-available": false,
        "aclk-implementation": "Next Generation"
```

It means that the Agent is built with Cloud support.


```
        "agent-claimed": false,
        "aclk-available": false,
```

^^ And that means that the Agent is not claimed/ACLK is not connected. 

Did you check error.log? If not:


```cmd
tail -f /opt/netdata/var/log/netdata/error.log | grep -i aclk
sudo systemctl restart netdata.service

# check the output of `tail`
```

**Comment by caroffer12** [comment]
Hi @ilyam8,

I have tried restarting the service but no luck.

 tail -f /opt/netdata/var/log/netdata/error.log | grep -i aclk
^C
root@ubuelastic:/# tail -f /opt/netdata/var/log/netdata/error.log
2022-07-26 14:36:13: cgroup-name.sh: INFO: docker container '6c9f06d75e28c61c75018b27500d48e6eb7d0cdcc260347b4a0ad53e375b71ae' is named 'es06'
2022-07-26 14:36:13: cgroup-name.sh: INFO: cgroup 'docker_6c9f06d75e28c61c75018b27500d48e6eb7d0cdcc260347b4a0ad53e375b71ae' is called 'es06'
2022-07-26 14:36:13: /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : running: exec /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/sys/fs/cgroup/cpu,cpuacct/docker/6c9f06d75e28c61c75018b27500d48e6eb7d0cdcc260347b4a0ad53e375b71ae'
2022-07-26 14:36:13: cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/sys/fs/cgroup/cpu,cpuacct/docker/6c9f06d75e28c61c75018b27500d48e6eb7d0cdcc260347b4a0ad53e375b71ae'
2022-07-26 14:36:13: cgroup-name.sh: INFO: Running command: docker ps --filter=id="6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7" --format="{{.Names}}"
2022-07-26 14:36:13: cgroup-name.sh: INFO: docker container '6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7' is named 'metricbeat_metricbeat_1'
2022-07-26 14:36:13: cgroup-name.sh: INFO: cgroup 'docker_6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7' is called 'metricbeat_metricbeat_1'
2022-07-26 14:36:13: /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : running: exec /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/sys/fs/cgroup/cpu,cpuacct/docker/6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7'
2022-07-26 14:36:13: cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/sys/fs/cgroup/cpu,cpuacct/docker/6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7'
2022-07-26 14:36:14: cgroup-name.sh: INFO: cgroup 'init.scope' is called 'init.scope'

**Comment by MrZammler** [comment]
Hi @caroffer12 

Can you try to re-claim the agent? Most likely that means re-running the kickstart command (which should find the installation) and pass it the token and related data from the cloud page, as if adding a new node.

**Comment by MrZammler** [comment]
Do you remember if something happened, i.e. an upgrade or similar that could cause the installation to lose it's cloud configuration? Have you noticed whether e.g. any custom configuration was lost as well?

**Comment by caroffer12** [comment]
Hi @MrZammler,

I already tried reinstall. do you still want me to try again 
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --reinstall

Yes i don't see netdata folder under /etc . I have setup elasticsearch monitoring . But that file is missing.

**Comment by MrZammler** [comment]
Hi!

You don't need to re-install. You just need to claim, i.e. if you go to the cloud, hit "Add node", it should list the command you need to run to claim the agent (i.e. make it aware to the cloud). It should look something like this:

```
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token yeZWbcFL8WWwezci5phu1HmdrOcr3FsfACXXXXXXFdCWp1Q7uHeTAoO1fSVHlZEKYjOzDpUrQQgtKP4bl8U40ALEsUrkVSuW79Ng-iB5rPbdkJEdTGobpzVj8aNHCg --claim-url https://app.netdata.cloud
```

**Comment by caroffer12** [comment]
Hi @MrZammler,

When i tried to claim . it says node is already registered. As per the documentation i tried deleting `cloud.d` folder. It got claimed but still i am not able to see the server on Dashboard.

```
netdata-claim.sh -token=xxxxxxxxxxxxxx -rooms=xxxxxx -url=https://app.netdata.cloud -id=$(uuidgen)
Unable to communicate with Netdata daemon, querying config from disk instead.
Unable to communicate with Netdata daemon, querying config from disk instead.
Token: ****************
Base URL: https://app.netdata.cloud
Id: c2bee8d1-7cd7-4d08-bb9d-dac9ffde73d8
Rooms: xxxxxxxxxxxxxxxxxxx
Hostname: ubuelastic
Proxy:
Netdata user:
Generating private/public key for the first time.
Generating RSA private key, 2048 bit long modulus (2 primes)
..+++++
.+++++
e is 65537 (0x010001)
Extracting public key from private key.
writing RSA key
Connection attempt 1 successful
uv_pipe_connect(): no such file or directory
Make sure the netdata service is running.
The claim was successful but the agent could not be notified (0)- it requires a restart to connect to the cloud.
```

**Comment by MrZammler** [comment]
It seems the claim succeded. When you run netdata now (leave it running a bit), what does /api/v1/info say ?

**Comment by caroffer12** [comment]
Hi @MrZammler ,

Netdata is running for 30 mins now . But still i see agent-claimed is false

```"cloud-enabled": true,
	"cloud-available": true,
	"aclk-ng-available": true,
	"aclk-ng-new-cloud-protocol": true,
	"aclk-legacy-available": false,
	"aclk-implementation": "Next Generation",
	"agent-claimed": false,
	"aclk-available": false,
	"aclk-available-protocol": null,
	"memory-mode": "dbengine",
	"multidb-disk-quota": 256,
	"page-cache-size": 32,
	"stream-enabled": false,
	"stream-compression": true,
	"hosts-available": 1,
	"https-enabled": true,
	"buildinfo": "dbengine|Native HTTPS|Netdata Cloud|ACLK Next Generation|New Cloud Protocol Support|TLS Host Verification|Machine Learning|Stream Compression|protobuf|JSON-C|libcrypto|libm|zlib|apps|cgroup Network Tracking|EBPF|perf|slabinfo|Prometheus Remote Write",
	"release-channel": "nightly",
	"web-enabled": true,
	"notification-methods": "",
```

**Comment by MrZammler** [comment]
Ok... strange...

So, you installed Netdata, and it's working, under /opt/ using a static install.
You then run the kickstart script with the claim parameters, but the agent was not claimed (There's still nothing under `/opt/netdata/var/lib/netdata/cloud.d/cloud.conf`, right?)

Will try to reproduce the above scenario, see if there is anything wrong there with claiming.

Thanks!!

**Comment by caroffer12** [comment]
Hi @MrZammler,

I don't see any files under this folder
```root@ubuelastic:/opt/netdata/var/lib/netdata/cloud.d# ls -lrt
total 0
```
But i see files under this folder 
```root@ubuelastic:/var/lib/netdata/cloud.d# ls -lrt
total 16
-rw------- 1 root root 1675 Jul 26 15:18 private.pem
-rw-r--r-- 1 root root  451 Jul 26 15:18 public.pem
-rw-r--r-- 1 root root   70 Jul 26 15:18 cloud.conf
-rw-r--r-- 1 root root   36 Jul 26 15:18 claimed_id
```

```root@ubuelastic:/var/lib/netdata/cloud.d# systemctl status netdata
● netdata.service - Real time performance monitoring
     Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-07-27 06:57:25 UTC; 3h 42min ago
    Process: 4161234 ExecStartPre=/bin/mkdir -p /opt/netdata/var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 4161240 ExecStartPre=/bin/chown -R netdata:netdata /opt/netdata/var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 4161251 ExecStartPre=/bin/mkdir -p /opt/netdata/var/run/netdata (code=exited, status=0/SUCCESS)
    Process: 4161253 ExecStartPre=/bin/chown -R netdata:netdata /opt/netdata/var/run/netdata (code=exited, status=0/SUCCESS)
   Main PID: 4161255 (netdata)
      Tasks: 106 (limit: 308719)
     Memory: 244.1M
     CGroup: /system.slice/netdata.service
             ├─  63634 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
             ├─4161255 /opt/netdata/bin/srv/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D
             ├─4161259 /opt/netdata/bin/srv/netdata --special-spawn-server
             ├─4161512 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
             ├─4161516 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
             ├─4161517 /opt/netdata/usr/libexec/netdata/plugins.d/ebpf.plugin 1
             └─4161519 /usr/bin/python3 /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1

Jul 27 06:57:25 ubuelastic systemd[1]: Starting Real time performance monitoring...
Jul 27 06:57:25 ubuelastic systemd[1]: Started Real time performance monitoring.
Jul 27 06:57:25 ubuelastic [4161255]: CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
Jul 27 06:57:25 ubuelastic netdata[4161255]: 2022-07-27 06:57:25: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/clou>
Jul 27 06:57:26 ubuelastic [4161517]: Does not have a configuration file inside `/opt/netdata/etc/netdata/ebpf.d.conf. It will try to load stock file.
Jul 27 06:57:26 ubuelastic [4161517]: Name resolution is disabled, collector will not parser "hostnames" list.
Jul 27 06:57:26 ubuelastic [4161517]: The network value of CIDR 127.0.0.1/8 was updated for 127.0.0.0 .
Jul 27 06:57:26 ubuelastic [4161517]: Cannot read process groups configuration file '/opt/netdata/etc/netdata/apps_groups.conf'. Will try '/opt/netdata/usr/>
```

**Comment by MrZammler** [comment]
Ok, so there are left-overs from the previous installation, and kickstart detects that...

Is there anything under `/etc/netdata` ?

**Comment by caroffer12** [comment]
Hi @MrZammler 

There is no netdata folder
```
root@ubuelastic:/etc# cd net
netconfig            netdata-old/         netplan/             network/             networkd-dispatcher/ networks
```

**Comment by MrZammler** [comment]
We will most likely need to remove by hand any left-overs from the previous install...

Could you (very carefully) remove the following if they exist?

`/var/lib/netdata`
`/var/cache/netdata`
`/var/log/netdata`
`/usr/lib/netdata`
`/usr/libexec/netdata`
`/usr/share/netdata`

And any files like `/usr/sbin/netdata`, `/usr/sbin/netdatacli` and `/usr/sbin/netdata-claim.sh` ?

After that please try to run again the kickstart script with the claim parameters (token, etc).

Thank you!

**Comment by caroffer12** [comment]
Thanks @MrZammler . It Worked i am able to see the server in the https://app.netdata.cloud/.

I have 1 more server where "aclk-available": false,

```
 tail -f /var/log/netdata/error.log | grep -i aclk
2022-07-28 14:44:08: netdata ERROR : ACLK_Main : Failed to Get ACLK environment
2022-07-28 14:44:08: netdata INFO  : ACLK_Main : Wait before attempting to reconnect in 0.657 seconds
2022-07-28 14:44:09: netdata INFO  : ACLK_Main : Attempting connection now
2022-07-28 14:44:09: netdata INFO  : ACLK_Main : HTTPS "GET" request to "app.netdata.cloud" finished with HTTP code: 429
2022-07-28 14:44:09: netdata ERROR : ACLK_Main : The HTTP code not 200 OK (Got 429)
2022-07-28 14:44:09: netdata ERROR : ACLK_Main : Failed to Get ACLK environment
2022-07-28 14:44:09: netdata INFO  : ACLK_Main : Wait before attempting to reconnect in 0.124 seconds
^C
```
````
"cloud-enabled": true,
	"cloud-available": true,
	"aclk-ng-available": true,
	"aclk-ng-new-cloud-protocol": false,
	"aclk-legacy-available": false,
	"aclk-implementation": "Next Generation",
	"agent-claimed": true,
	"aclk-available": false,
	"aclk-available-protocol": null,
	"memory-mode": "dbengine",
	"multidb-disk-quota": 256,
	"page-cache-size": 32,
	"stream-enabled": false,
	"stream-compression": "disabled",
	"hosts-available": 1,
	"https-enabled": true,
	"buildinfo": "dbengine|Native HTTPS|Netdata Cloud|ACLK Next Generation|TLS Host Verification|Stream Compression|JSON-C|libcrypto|libm|zlib|apps|cgroup Network Tracking|EBPF|perf|slabinfo",
	"release-channel": "nightly",
```
```
 netdata -v
netdata v1.33.1-28-nightly
```

**Comment by MrZammler** [comment]
Alright! Glad it did!

Now, this one, I think you should first try to update it. Can you run the kickstart script on it ? (No need to use any parameters like re-install etc).

**Comment by caroffer12** [comment]
@MrZammler Thanks It worked.

**Comment by MrZammler** [comment]
Great! Thank you!!

**Comment by caroffer12** [comment]
Hi Team,

I tried restarting the service . But still no luck.

 tail -f /opt/netdata/var/log/netdata/error.log | grep -i aclk
^C
***@***.***:/# tail -f /opt/netdata/var/log/netdata/error.log
2022-07-26 14:27:27: cgroup-name.sh: INFO: cgroup
'docker_6c9f06d75e28c61c75018b27500d48e6eb7d0cdcc260347b4a0ad53e375b71ae'
is called 'es06'
2022-07-26 14:27:27:
/opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN :
running: exec
/opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh
--cgroup
'/sys/fs/cgroup/cpu,cpuacct/docker/6c9f06d75e28c61c75018b27500d48e6eb7d0cdcc260347b4a0ad53e375b71ae'
2022-07-26 14:27:27: cgroup-network-helper.sh: INFO: searching for network
interfaces of cgroup
'/sys/fs/cgroup/cpu,cpuacct/docker/6c9f06d75e28c61c75018b27500d48e6eb7d0cdcc260347b4a0ad53e375b71ae'
2022-07-26 14:27:27: cgroup-name.sh: INFO: Running command: docker ps
--filter=id="6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7"
--format="{{.Names}}"
2022-07-26 14:27:27: cgroup-name.sh: INFO: docker container
'6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7' is named
'metricbeat_metricbeat_1'
2022-07-26 14:27:27: cgroup-name.sh: INFO: cgroup
'docker_6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7'
is called 'metricbeat_metricbeat_1'
2022-07-26 14:27:27:
/opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN :
running: exec
/opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh
--cgroup
'/sys/fs/cgroup/cpu,cpuacct/docker/6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7'
2022-07-26 14:27:27: cgroup-network-helper.sh: INFO: searching for network
interfaces of cgroup
'/sys/fs/cgroup/cpu,cpuacct/docker/6ce820b536d046a304491e28bb68a457544c94bca40f573980ab4fcfa02b55e7'
2022-07-26 14:27:28: cgroup-name.sh: INFO: cgroup 'init.scope' is called
'init.scope'
2022-07-26 14:29:19: alarm-notify.sh: WARNING: Cannot find file
'/opt/netdata/etc/netdata/health_alarm_notify.conf'.
^C

Regards,
Suresh

**Comment by MrZammler** [comment]
Hey @caroffer12 !

The log you're pasting is from July, is this a new problem? Is it the same node we where checking or a new one? Can you check `/var/log/netdata/error.log`?
