### ISSUE TITLE
[Feat]:  ntfy.sh

### ISSUE THREAD

**Issue by mabed-fr** [netdata/netdata#13432]
### Problem

My notification services is not available

### Description

ntfy (pronounce: notify) is a simple HTTP-based [pub-sub](https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern) notification service. It allows you to send notifications to your phone or desktop via scripts from any computer, entirely without signup, cost or setup. It's also [open source](https://github.com/binwiederhier/ntfy) if you want to run your own.

### Importance

must have

### Value proposition

1. compatibility ( IOS, ANDROID, CLI, ....
2. Self hosted
3. K I S

### Proposed implementation

Implementation as a notification service like 

[alerta.io](https://learn.netdata.cloud/docs/agent/health/notifications/alerta)
[Amazon SNS](https://learn.netdata.cloud/docs/agent/health/notifications/awssns)
[Custom](https://learn.netdata.cloud/docs/agent/health/notifications/custom)
[Discordapp.com](https://learn.netdata.cloud/docs/agent/health/notifications/discord)
[Dynatrace](https://learn.netdata.cloud/docs/agent/health/notifications/dynatrace)
[Email](https://learn.netdata.cloud/docs/agent/health/notifications/email)
[Flock](https://learn.netdata.cloud/docs/agent/health/notifications/flock)
[Gotify](https://learn.netdata.cloud/docs/agent/health/notifications/gotify)
[Google Hangouts](https://learn.netdata.cloud/docs/agent/health/notifications/hangouts)
[IRC](https://learn.netdata.cloud/docs/agent/health/notifications/irc)
[Kavenegar](https://learn.netdata.cloud/docs/agent/health/notifications/kavenegar)
[Matrix](https://learn.netdata.cloud/docs/agent/health/notifications/matrix)
[Messagebird](https://learn.netdata.cloud/docs/agent/health/notifications/messagebird)
[Microsoft Teams](https://learn.netdata.cloud/docs/agent/health/notifications/msteams)
[Opsgenie](https://learn.netdata.cloud/docs/agent/health/notifications/opsgenie)
[PagerDuty](https://learn.netdata.cloud/docs/agent/health/notifications/pagerduty)
[Prowl](https://learn.netdata.cloud/docs/agent/health/notifications/prowl)
[PushBullet](https://learn.netdata.cloud/docs/agent/health/notifications/pushbullet)
[PushOver](https://learn.netdata.cloud/docs/agent/health/notifications/pushover)
[Rocket.Chat](https://learn.netdata.cloud/docs/agent/health/notifications/rocketchat)
[Slack](https://learn.netdata.cloud/docs/agent/health/notifications/slack)
[SMS Server Tools 3](https://learn.netdata.cloud/docs/agent/health/notifications/smstools3)
[StackPulse](https://learn.netdata.cloud/docs/agent/health/notifications/stackpulse)
[Syslog](https://learn.netdata.cloud/docs/agent/health/notifications/syslog)
[Telegram](https://learn.netdata.cloud/docs/agent/health/notifications/telegram)
[Twilio](https://learn.netdata.cloud/docs/agent/health/notifications/twilio)
[Dashboard](https://learn.netdata.cloud/docs/agent/health/notifications/web)

**Comment by c0depool** [comment]
It will be awesome to have ntfy.sh integration available out of the box. For anyone looking for a workaround, try adding something like this in your health_alarm_notify.conf to make use of the [custom](https://learn.netdata.cloud/docs/agent/health/notifications/custom) notifications -

```
SEND_CUSTOM="YES"
DEFAULT_RECIPIENT_CUSTOM="https://ntfy.example.com/netdata"
custom_sender() {
    local msg="${host} ${status_message}: ${alarm} ${raised_for}"
    httpcode=$(docurl -X POST \
                     -u "user:password" \
                     -d "${msg}" \
                     ${1})
    if [ "${httpcode}" = "200" ]; then
      info "sent custom notification ${msg}"
      sent=$((sent + 1))
    else
      error "failed to send custom notification ${msg} with HTTP error code ${httpcode}."
    fi
}

**Comment by skibbipl** [comment]
Do you know perhaps how I could map ${status} variable into other values?
I would like to use emoji tags but I need a matrix like this:
status -> emoji_name
warning -> warning
critical -> exclamation
recovered -> white_check_mark
