### ISSUE TITLE
[Bug]: tiering issues

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#13443]
### Bug description

1. Tiering misses the last incomplete point of higher tiers. So, when a metric stops being collected, the last incomplete point is never written to the database.
2. Tiering misses entire metrics if the metrics do not collect at least a full point to satisfy a tier. So, if a metric is collected for 30 seconds and then it stops, it will never appear in tier1 (60 seconds), or tier2 (3600 seconds).
3. Backfilling `full` backfills only collected metrics.
4. Backfilling `full` does not add the data in the right order for db rotation to work as expected.
5. We have observed some cases that higher tiers report less metrics than tier0.

### Expected behavior

Do all the above the right way.

### Steps to reproduce

Enable tiering

### Installation method

kickstart.sh

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

**Comment by ilyam8** [comment]
@ktsaou is this issue still relevant?

**Comment by ilyam8** [comment]
I believe everything has been addressed.
