### ISSUE TITLE
[Bug]: Netdata with Kubernetes - custom alarm templates not recognized by health and netdatacli reload-health not working

### ISSUE THREAD

**Issue by Garahk** [netdata/netdata#13465]
### Bug description

Deployed netdata with helm-chart in a kubernetes kind cluster with 3 nodes, 1 kind-control-plane and 2 workers

![image](https://user-images.githubusercontent.com/99432183/181862291-130574a8-5bb8-4586-a89f-e605ab0d8c01.png)

Health has been enabled in the childs, there's 3 childs, one per node of the cluster, as I want the metrics and alarms of the cgroups cpu/mem usage, as well as alarms triggered by the cgroups.

![image](https://user-images.githubusercontent.com/99432183/181862334-006906fb-829a-4a26-ada2-c6dc5488a352.png)

Otherwise parent pod doesn't offer much metrics or alerts:

![image](https://user-images.githubusercontent.com/99432183/181862382-15fe7bc8-1089-4ca6-975c-5984c416e1d5.png)
![image](https://user-images.githubusercontent.com/99432183/181862869-8a2f8107-5664-4e87-97cb-7510825e9d9a.png)

When checking the dashboards of each of the nodes (child's pods), on the alert's section it would seem the health has more alerts and actually seem to work

![image](https://user-images.githubusercontent.com/99432183/181862283-fc47476d-b5d6-44d2-9211-79463f86a9d7.png)

However there's only the stock alarms, not any of the sources placed in /etc/netdata/health.d directory:

![image](https://user-images.githubusercontent.com/99432183/181863009-5989a3a5-c62c-4dc3-911b-13af03884d93.png)

Example:

![image](https://user-images.githubusercontent.com/99432183/181863337-edc01003-1ac7-4f42-beac-f655a1b81d4d.png)

### Expected behavior

I want to be able to configure lower thresholds in the `cpu.conf`, `ram.conf`, `cgroups.conf` alarm template files, just like it's possible when deploying netdata in a container within a docker swarm. In docker I used to copy a modified template into the container with `docker cp`, or simply create one with vi inside the /etc/netdata/health.d directoy, lastly I would reload the health with `netdatacli reload-health`, however in kubernetes this is not working, executing the `netdatacli` command does nothing, normally running it in a docker container it would take a couple seconds to give me the prompt of the container back, here it returns inmediatly having done no change.

### Steps to reproduce

1. Deploy netdata with helm-chart
2. `kubectl cp` the customized `cpu.conf/ram.conf/cgroups.conf` into the pod's netdata container inside `/etc/netdata/health.d` directory
3. Reload health with `netdatacli reload-health`
4. Confirm in netdata's main dashboard the new alarms are triggered

### Installation method

helmchart (kubernetes)

### System info

```shell
Linux 3.10.0-1160.62.1.el7.x86_64 #1 SMP Wed Mar 23 09:04:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.9 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.9"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
/etc/system-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

### Netdata build info

```shell
Version: netdata v1.35.0-191-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--with-bundled-libJudy' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

This is a 3 nodes K8s kind cluster, production cluster

Appreciate the support

**Comment by Garahk** [comment]
I have a test cluster as well, also based on Kind, which has only 1 node, therefore all pods are scheduled in this one. It's worth mentioning that this one node kind cluster has no issues with custom alerts, I had 4 files uploaded to the child pod at /etc/netdata/health.d, with very low thresholds so the alarms are triggered with very few resource consumption and almost immeadiatly after the service is up, I do this very low thresholds configuration to confirm custom alerts are working, and the result is as below:

RAM alarm, source is ram.conf at /etc/netdata/health,d/ram.conf
![image](https://user-images.githubusercontent.com/99432183/182246707-33dd5731-598a-4da8-9e18-2572de9f034a.png)

cgroups alarms, source is cgroups.conf at /etc/netdata/health,d/cgroups.conf
![image](https://user-images.githubusercontent.com/99432183/182247156-03bf2277-45ea-4f0a-bf63-f9a179915723.png)

I basically use the same helm chart in both nodes, any clue as to why on multiple node cluster it doesn't work but in single node it does?

**Comment by ilyam8** [comment]
> Otherwise parent pod doesn't offer much metrics or alerts:

Hi, @Garahk. Use the Replicated Nodes menu, you can go to any child dashboard from there.

<img width="1727" alt="Screenshot 2022-08-02 at 09 43 12" src="https://user-images.githubusercontent.com/22274335/182309200-2b27ccec-71f2-487b-b000-d6c1518e21b0.png">

**Comment by ilyam8** [comment]
> kubectl cp the customized cpu.conf/ram.conf/cgroups.conf into the pod's netdata container inside /etc/netdata/health.d directory

The correct way is using [child.configs](https://github.com/netdata/helmchart/blob/b47b20c53b2922b09b15e424560019c370b13c14/charts/netdata/values.yaml#L266). Add your custom alarms to the child.configs option.

**Comment by Garahk** [comment]
On the other hand, I wondered myself what would happen if instead of placing the conf files in the child pods, I placed them in the parent pod, and got what was expecting, alarms in all of the child pods, I was looking specially at the cgroups alarms, since the cluster's services have been distributed amongts the 3 nodes, and we want to have track of the resource consumption by each of the pods.

![image](https://user-images.githubusercontent.com/99432183/182417797-26ca3ae0-4555-47ad-adf8-798bef60888b.png)

You'll notice the number of alarms are different, and I confirmed that the alarms are different at each child pod as well by looking at the description. Also all have the source from the files at `/etc/netdata/healt.d/`

![image](https://user-images.githubusercontent.com/99432183/182418919-be3b44f6-70e3-4138-8bcb-9b1eda752cf8.png)

Is this method of enabling custom alarms not correct or supported?

Depending on your answer, I would also like to add that I've configured msmtp (sendmail has never worked on our deployment model, but msmtp works great on our docker swarm thus why we use it also in the K8s deployment) but am not getting the notifications as it happens on Docker swarm.

![image](https://user-images.githubusercontent.com/99432183/182420220-9e3afaf5-ac3b-4bff-9fcd-b9b0838326a1.png)

Note: Test notifications work, but regular are not being sent.

I suppose it has something to do with configuration, but not sure where to look now.

**Comment by ilyam8** [comment]
>  if instead of placing the conf files in the child pods, I placed them in the parent pod, and got what was expecting, alarms in all of the child pods

Yes, that is the preferred way.

- health on the parent: check the children nodes alarms via the parent's Replication Nodes menu.
- health on children: check the children nodes alarms by accessing their dashboard.
- custom alarms work, mounting them under `/etc/netdata/health.d/` is correct. If an alarm doesn't work - error.log is a good place to start to debug (e.g. could be health alarm syntax error, Netdata logs a message in that case).

**Comment by MrZammler** [comment]
Hi @Garahk . Have you maybe checked the error.log ? Or have you gone with the route of using the parent for the alerts?

**Comment by MrZammler** [comment]
Closing this due to age. @Garahk please open a new issue with more information if the problem still occurs.

**Comment by pmiriyev** [comment]
reopen:

same issue here, test alerts works but triggers doesn't.

# become user netdata
sudo su -s /bin/bash netdata

# enable debugging info on the console
export NETDATA_ALARM_NOTIFY_DEBUG=1

# send test alarms to sysadmin
/usr/libexec/netdata/plugins.d/alarm-notify.sh test

# send test alarms to any role
/usr/libexec/netdata/plugins.d/alarm-notify.sh test "ROLE"

this ones works, receiving alerts but triggered ones not coming

**Comment by pmiriyev** [comment]
lets say this one is triggered but without alert to discord channel:

time=2024-01-31T09:57:40.649+00:00 comm=netdata source=health level=warning tid=365 thread=HEALTH msg_id=9ce0cb58ab8b44df82c4bf1ad9ee22de node=worker04 instance=disk_backlog.sdi context=disk.backlog code=0 alert_id=1706694441 alert_unique_id=1706694699 alert_event_id=3 alert_transition_id=b6dfbc446a344b1496cbcb61ac689cd2 alert_config=823565b54a9eed824876fee349d6b67c alert=10min_disk_backlog alert_class=Latency alert_component=Disk alert_type=System alert_recipient=silent alert_duration=120 alert_value=5031.011685 alert_value_old=1142.2337683 alert_status=WARNING alert_value_old=CLEAR alert_units=ms alert_summary="Disk sdi backlog" alert_info="Average backlog size of the sdi disk over the last 10 minutes" alert_notification_timestamp=2024-01-31T09:57:40+00:00 msg="ALERT '10min_disk_backlog' of instance 'disk_backlog.sdi' on node 'worker04', transitioned from CLEAR to WARNING"
