### ISSUE TITLE
[Feat]: Allow users to define labels at the collection job level

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13486]
### Problem

We now have support for chart labels in the agent and the cloud (adding filtering by labels on Monday), but no way for users to add their own label key/value pairs. 

### Description

As a quick win, allow users to define label keys and values at the **data collection job** level (e.g. different labels for each DB instance connected to). The collector will be responsible to add lower level labels (e.g. such as the database name when a DB instance has multiple databases on it).

### Importance

really want

### Value proposition

Custom labels allow users to organize their metrics in ways that make sense to them. 

### Proposed implementation

go.d.plugin for sure, but we should discuss:
- Are the host labels enough for the system plugins such as proc and sys?
- What do we do about cgroups? Can it be generic or needs a case by case investigation and implementation?

**Comment by sashwathn** [comment]
@cakrit : Now that we allow custom labels at the job level, I want to understand the actual use of this.
I believe what we are allowing users to set is some custom labels for their jobs (to differentiate one from another). But we already have a default label _collect_job which we are able to "Group by" and "Filter" from and these custom labels will now be an additional label over and above these and I am not sure if these are good from a UX perspective.

@shyamvalsan and @ilyam8 for more comments.

**Comment by cakrit** [comment]
Since the question is public, I'm pasting here the responses we provided in Slack:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/43294513/192847343-c0881aaf-da1b-4742-9a29-3944a143e0d4.png">
