### ISSUE TITLE
[Feat]: Implement an endpoint to provide statiscal information on the agent metrics 

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#13482]
### Problem

We would like to get statistical information provided directly from an endpoint on the agent and don't reply on data available from other sources: spread on other endpoints and not "crunched" and/or messages.

### Description

The statistical information that we would like to have available is:

**Metrics/Dimensions/Collectors**
* Number of metrics collected (dimensions)
* Number of metrics collected per data collection frequency
* Number of data collection plugins, modules and jobs

**Data Retention**
* Number of data points in the database
* Minimum, average and maximum data retention across all metrics
* Memory used for storage (what are the ramifications depending on memory mode?)

This endpoint should have an options parameter to allow:
* getting statistics for the node instance of itself
* getting statistics for a specific node instance of a node he his having data from
* getting statistics for all node instances it has data from

### Importance

must have

### Value proposition

Provide more insights with statistical information on what the agent is collecting and storing

**Comment by hugovalente-pm** [comment]
@amalkov @papazach @stelfrag the initial ideation ticket for the statistics endpoint to be made available on the agent

**Comment by amalkov** [comment]
https://github.com/netdata/cloud-frontend/issues/3697

**Comment by ktsaou** [comment]
Something like this is already implemented: http://localhost:19999/api/v1/dbengine_stats
We implemented this for the calculator.

Per node instance is not implemented. It can be tricky, because the figures are per bound to each database tier.

**Comment by ralphm** [comment]
@ktsaou and I had a related discussion after a question by @Ancairon, where he was looking for the average number of metrics in a typical production install of the Agent.

I propose we implement this as time series, where the Agent reports the statistics shown in the Agent dashboard:

- The total number of metrics collected right now.
- The total number of corresponding contexts.
- The total number of alerts.

There are some existing metrics for dbengine, but that doesn't work for lean agents that run in `ram` mode. These should be independent of the used storage engine, and appear in the `netdata` section.

**Comment by ilyam8** [comment]
It looks like a stale issue - closing. Feel free to open it again if you still need it.
