### ISSUE TITLE
[Bug]: Claiming a node fails

### ISSUE THREAD

**Issue by rondior** [netdata/netdata#13516]
### Bug description

 Failed to claim node for an unknown reason.

### Expected behavior

Add node to my war room and for node to install properly 

### Steps to reproduce

1.ADD NODE: Run the script below on your node's terminal
2.Attempting to claim agent
3. WARNING  Failed to claim node for an unknown reason
4. Unknown HTTP error message"

### Installation method

kickstart.sh

### System info

```shell
Linux vmi957476.contaboserver.net 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.36.0-8-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by ilyam8** [comment]
Hi, @rondior. Can you show the script output related to 

> 2.Attempting to claim agent
> 3. WARNING Failed to claim node for an unknown reason
> 4. Unknown HTTP error message"

**Comment by rondior** [comment]
Hi @ilyam8 love the fallout logo! 
I'll apologize ahead of time. Im new to githum and networking so may take some patience getting me to find you the right info you need. :/

**Comment by rondior** [comment]
--- Attempting to claim agent to https://app.netdata.cloud --- 
 --- Attempting to claim agent to https://app.netdata.cloud --- 
174467
174471
[/tmp/netdata-kickstart-nOmYwNJfgw]# /usr/sbin/netdata-claim.sh -token=AXfib8BTXvEo89AANvPPT1TEuFJsTaicI_26Y4KfQqTykwUXOJuSzgmYReELSsBppllTFewNs1HidtMoXlb2fg1VTq-cShySYod2-1jII3aeJGJ8SFR-2U3J5cAoVz3OcSAnoys -rooms= -url=https://app.netdata.cloud 
Unable to communicate with Netdata daemon, querying config from disk instead.
Unable to communicate with Netdata daemon, querying config from disk instead.
Token: ****************
Base URL: https://app.netdata.cloud
Id: 
Rooms: 
Hostname: vmi957476.contaboserver.net
Proxy: 
Netdata user: netdata
Connection attempt 1 successful
Failed to claim node with the following error message:"Unknown HTTP error message"
 FAILED

**Comment by rondior** [comment]
WARNING  Failed to claim node for an unknown reason. This usually means either networking problems or a bug. Please retry claiming later, and if you still see this message file a bug report at https://github.com/netdata/netdata/issues/new/choose

The following non-fatal warnings or errors were encountered:

  - Command "/usr/sbin/netdata-claim.sh -token=AXfib8BTXvEo89AANvPPT1TEuFJsTaicI_26Y4KfQqTykwUXOJuSzgmYReELSsBppllTFewNs1HidtMoXlb2fg1VTq-cShySYod2-1jII3aeJGJ8SFR-2U3J5cAoVz3OcSAnoys -rooms= -url=https://app.netdata.cloud" failed with exit code 7.
  - Failed to claim node for an unknown reason. This usually means either networking problems or a bug. Please retry claiming later, and if you still see this message file a bug report at https://github.com/netdata/netdata/issues/new/choose

**Comment by rondior** [comment]
I believe that is what you have asked for.  If not let me know.
thanks

**Comment by underhood** [comment]
@rondior not sure how comfortable would you be to modify the claiming script to add some debug info?

**Comment by MrZammler** [comment]
>  Id:

This is kinda weird. It should have the machine guid there I think, either from when the agent run and created it, or created by the script itself...

@rondior Is the agent running ok ? (aside from not being claimed) ?

**Comment by rondior** [comment]
How do I check to see if the agent is running ok?

**Comment by underhood** [comment]
- Is there any netdata process running?
-  If running as service what does `systemctl status netdata` say (assuming you are running systemd distro)?
-  How about netdata error log (/var/log/netdata/error.log assuming you installed into default location)?

**Comment by underhood** [comment]
are you running claim script as privileged user (sudo/root?)

**Comment by rondior** [comment]
root@vmi957476:~# systemctl status netdata
● netdata.service - Real time performance monitoring
     Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2022-08-19 08:52:46 PDT; 6s ago
    Process: 2850589 ExecStart=/usr/sbin/netdata -D $EXTRA_OPTS (code=exited, status=1/FAILURE)
   Main PID: 2850589

**Comment by ilyam8** [comment]
@rondior can you try [uninstalling Netdata](https://github.com/netdata/netdata/issues/13498#issuecomment-1220689866) and installing it again?

**Comment by rondior** [comment]
> @rondior can you try [uninstalling Netdata](https://github.com/netdata/netdata/issues/13498#issuecomment-1220689866) and installing it again?

root@vmi957476:~# sudo apt-get purge netdata
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libnetfilter-acct1 libprotobuf17 libsnappy1v5
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  netdata*
0 upgraded, 0 newly installed, 1 to remove and 9 not upgraded.
After this operation, 120 MB disk space will be freed.
Do you want to continue? [Y/n] y
Abort.

**Comment by rondior** [comment]
I hit Y and then it said "abort"?  Was that supposed to happen?

**Comment by ilyam8** [comment]
That is supposed to remove Netdata.

**Comment by rondior** [comment]
Ok cool.  I will try to reinstall then

**Comment by rondior** [comment]
Ok i reinstalled it.  It said it was successful.  The node showed up in my war room but it says it's OFFLINE.  Node info unknown.

**Comment by rondior** [comment]
--- Using /tmp/netdata-kickstart-8ydOVnB3Bo as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- Found an existing netdata install at /, with installation type 'binpkg-deb'. --- 
[/tmp/netdata-kickstart-8ydOVnB3Bo]# //usr/libexec/netdata/netdata-updater.sh --interactive --not-running-from-cron 
Fri 19 Aug 2022 10:29:22 AM PDT : INFO: netdata-updater.sh:  Checking if a newer version of the updater script is available.
Hit:1 http://asi-fs-w.contabo.net/ubuntu focal InRelease
Get:2 http://asi-fs-w.contabo.net/ubuntu focal-updates InRelease [114 kB]
Get:3 http://asi-fs-w.contabo.net/ubuntu focal-backports InRelease [108 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 http://asi-fs-w.contabo.net/ubuntu focal-updates/main amd64 Packages [2,039 kB]
Get:7 http://asi-fs-w.contabo.net/ubuntu focal-updates/main i386 Packages [706 kB]
Get:8 http://asi-fs-w.contabo.net/ubuntu focal-updates/universe i386 Packages [687 kB]
Get:9 http://asi-fs-w.contabo.net/ubuntu focal-updates/universe amd64 Packages [939 kB]
Hit:6 https://packagecloud.io/netdata/netdata-edge/ubuntu focal InRelease      
Hit:10 https://packagecloud.io/netdata/netdata-repoconfig/ubuntu focal InRelease
Fetched 4,708 kB in 1s (4,067 kB/s)            
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
netdata-repo-edge is already the newest version (1-2).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
Hit:1 http://asi-fs-w.contabo.net/ubuntu focal InRelease
Hit:2 http://asi-fs-w.contabo.net/ubuntu focal-updates InRelease               
Hit:3 http://asi-fs-w.contabo.net/ubuntu focal-backports InRelease             
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease               
Hit:4 https://packagecloud.io/netdata/netdata-edge/ubuntu focal InRelease      
Hit:6 https://packagecloud.io/netdata/netdata-repoconfig/ubuntu focal InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
netdata is already the newest version (1.36.0-31-nightly).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
 OK 

 --- Updated existing install at / --- 
 --- Successfully updated existing netdata install at /. --- 
 --- Attempting to claim existing install at /. --- 
 --- Attempting to claim agent to https://app.netdata.cloud --- 
 --- Attempting to claim agent to https://app.netdata.cloud --- 
[/tmp/netdata-kickstart-8ydOVnB3Bo]# /usr/sbin/netdata-claim.sh -token=yf5olWJaFZeYbWq0lp6OUioBh-txTpe7IaLQsYEcdWZhzaDWCw5jjNrbg9caC6Icn8I1sJG2Jde4y8osDNEM6L4MIlMtXXD748TT8oJH_kntjm0uH4-jNaw4F9dEbPz4ucsvbI0 -rooms= -url=https://app.netdata.cloud -daemon-not-running 
Unable to communicate with Netdata daemon, querying config from disk instead.
Unable to communicate with Netdata daemon, querying config from disk instead.
Token: ****************
Base URL: https://app.netdata.cloud
Id: e1587e62-242a-4604-8fec-6483aa2747f5
Rooms: 
Hostname: vmi957476.contaboserver.net
Proxy: 
Netdata user: netdata
Generating private/public key for the first time.
Generating RSA private key, 2048 bit long modulus (2 primes)
........................................................................................................+++++
.................................+++++
e is 65537 (0x010001)
Extracting public key from private key.
writing RSA key
Connection attempt 1 successful
uv_pipe_connect(): no such file or directory
Make sure the netdata service is running.
The claim was successful but the agent could not be notified (0)- it requires a restart to connect to the cloud.
 OK 

 --- Successfully claimed node --- 
Official documentation can be found online at https://learn.netdata.cloud/docs/.

Looking to monitor all of your infrastructure with Netdata? Check out Netdata Cloud at https://app.netdata.cloud.

Join our community and connect with us on:
  - GitHub: https://github.com/netdata/netdata/discussions

**Comment by rondior** [comment]
![Screen Shot 2022-08-19 at 1 40 27 PM](https://user-images.githubusercontent.com/29822150/185676637-f67f884b-f7c6-4175-8dd8-b4e47e8acaeb.png)

Node still offline after restart.  Clicked on node it says trying to load charts but its just stuck on that page.  Nothing loads.

**Comment by MrZammler** [comment]
Hi @rondior 

Can you try a `systemctl status netdata` and then most likely `systemctl start netdata` ? It seems the agent is not running...

**Comment by rondior** [comment]
It seems like whatever was done during this fixed the issue.  The node is now online.  Thanks to everyone for all the help with this. Hopefully something was learned... Closing now.
