### ISSUE TITLE
[Bug]: Postgres db read throughput metrics are inaccurate

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata#13512]
### Bug description

The db_rows_read_ratio is showing the wrong ratio of fetched to returned rows. The actual calculation should be a simple:
{$fetched} * 100 / {$returned}. But currently it is being calculated as {$fetched} * 100 / ({$returned} + {$fetched}).

Also, we should only collect the fetched ratio and there is no need to show the returned ratio as it will always be 100%.

cc: @ilyam8 , @thiagoftsm , @vlvkobal @shyamvalsan @cakrit .

### Expected behavior

The actual calculation should be a simple:
{$fetched} * 100 / {$returned}. But currently it is being calculated as {$fetched} * 100 / ({$returned} + {$fetched}).

### Steps to reproduce

1. Setup a postgres instance
2. Check the db_rows_read_ratio metric.

### Installation method

kickstart.sh

### System info

```shell
This is relevant to any system and is an issue on the collector.
```

### Netdata build info

```shell
This is relevant to the V1.36 release.
```

**Comment by ilyam8** [comment]
>  {$fetched} * 100 / {$returned}. But currently it is being calculated as {$fetched} * 100 / ({$returned} + {$fetched}).

Why? The chart shows fetched/returned distribution. 50/50% means equal (num of fetched rows == num of read/scanned rows). Any other distribution makes sense too.

**Comment by ilyam8** [comment]
I think there is a misunderstanding about the chart - it is the **same** as `postgres.db_rows_read` (which shows rows/s), but shows percentages.

**Comment by sashwathn** [comment]
@ilyam8 : The intention of this metric is to check how many rows were scanned (returned) for the number of rows to be fetched to the client. The total number of rows (denominator) should be the number of rows scanned (returned) and the number of rows fetched is a ratio of the returned.
https://documentation.solarwinds.com/en/success_center/dpa/content/dpa-postgre-resource-metrics.htm#:~:text=The%20Rows%20Fetched%20value%20is%20different%20than%20the,rows%20returned%20to%20the%20client.&text=The%20total%20number%20of%20rows%20scanned%20by%20queries%20executed%20against,rows%20returned%20to%20the%20client.

**Comment by sashwathn** [comment]
The dashboard_info says and this should ideally give us a ratio of the number of fetched rows against the number of returned rows. The chart as a percentage of the postgres.db_rows_read does not make much sense here.

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/96257330/184351892-fc8b3446-606f-4706-a00b-f5bedc1e4c4e.png">

**Comment by ilyam8** [comment]
> The intention of this metric is to check how many rows were scanned (returned) for the number of rows to be fetched to the client.

90/10 - returned 9 times more than fetched. It doesn't make sense to you?

I don't do any calculations in the collector, just use the [percentage-of-incremental-row](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#dimension) dimension algorithm.

Doing it differently means adding complexity: save prev fetched/returned values for every database, calculate delta manually and then calculate percentage.

**Comment by shyamvalsan** [comment]
Ratio of rows fetched : rows returned = (rows fetched * 100) / (rows returned)

Let's take an example

At 15:31:30 for the charts db in production there were:
- 593,253 rows fetched
- 979,258 rows returned

![image](https://user-images.githubusercontent.com/24860547/184356117-d1f9072a-9aa8-46de-a5a2-2cedbee9b3e2.png)

So the ratio of rows fetched : rows returned = (593253*100)/979258 = 60.58% 

ie. The database was reasonably efficient at completing read queries. 60% of the rows it scanned through were in fact needed to satisfy read queries.

But what the chart we have currently reports for this same timestamp 15:31:30 for the same database is:

fetched = 36% and returned = 64%

This number could be misleading is what @sashwathn is talking about if I am not mistaken.

![image](https://user-images.githubusercontent.com/24860547/184357023-7e0b7244-7103-49c2-9f53-ea86856dfac9.png)

--

To be clear, there's nothing wrong with the "Database rows read" chart (which shows raw data), but when we do a "Database rows read ratio" chart then it would be more useful if it shows how efficient the database is rather than just show a percentage ratio.

**Comment by ilyam8** [comment]
@shyamvalsan I understand the confusion, but the ratio chart shows it, the problem is the interpretation of the data - 50/50 means the best possible distribution, 64/36 means returned is (almost) 2 times more.

The "problem" is very clear and I don't say we don't have it. Just saying that it (IMO) shows "how efficient the database", just not that explicit probably.

**Comment by sashwathn** [comment]
@ilyam8 : As Shyam pointed out above, the fetched and returned are related to each other and the fetched rows is a subset of the returned and will be better to show it that way.

There is nothing wrong with the current one but the 50% vs 50% actually means we have a fully indexed database and no action for the user. We could rather show this as a 100% fetched metric which says it in as many words.. :)

**Comment by cakrit** [comment]
There is something wrong with this one, we need the single value.

**Comment by cakrit** [comment]
In https://github.com/netdata/product/issues/2990 @ilyam8 said that

> It is the number of "sequential scans" vs "bitmap scans" (I 🤷‍♂️ what that is). I couldn't find anything to backup the "should be close to 100%" statement (let's don't count the datadog article).

The full picture as explained [here](https://www.cybertec-postgresql.com/en/postgresql-indexing-index-scan-vs-bitmap-scan-vs-sequential-scan-basics/) is that we have three things that could happen:
 - Index scan: All the data we want to return exist already in the index, so we don't need to read any rows from the actual table. Most efficient, but rare.
 - Bitmap scan: All available indexes are used to limit the number of rows that will need to be read. If the indexes are very specific, we'll need to read exactly the number of rows we'll return.
 - Sequential scan: You end up reading the entire table and filtering. There are use cases when this may actually be good (requesting A LOT of data) but they are extremely rare. 

Given these, what exactly is it that we measure and call it rows fetched / returned?

**Comment by shyamvalsan** [comment]
Let's go to the source :) 

https://github.com/postgres/postgres/blob/master/src/include/pgstat.h#L149


```
/* ----------
 * PgStat_TableCounts			The actual per-table counts kept by a backend
 *
 * This struct should contain only actual event counters, because we memcmp
 * it against zeroes to detect whether there are any stats updates to apply.
 * It is a component of PgStat_TableStatus (within-backend state).
 *
 * Note: for a table, tuples_returned is the number of tuples successfully
 * fetched by heap_getnext, while tuples_fetched is the number of tuples
 * successfully fetched by heap_fetch under the control of bitmap indexscans.
 * For an index, tuples_returned is the number of index entries returned by
 * the index AM, while tuples_fetched is the number of tuples successfully
 * fetched by heap_fetch under the control of simple indexscans for this index.
 *
 * tuples_inserted/updated/deleted/hot_updated count attempted actions,
 * regardless of whether the transaction committed.  delta_live_tuples,
 * delta_dead_tuples, and changed_tuples are set depending on commit or abort.
 * Note that delta_live_tuples and delta_dead_tuples can be negative!
 * ----------
 */
typedef struct PgStat_TableCounts
{
	PgStat_Counter t_numscans;

	PgStat_Counter t_tuples_returned;
	PgStat_Counter t_tuples_fetched;
```

That wasn't very helpful tbh.. 

Most other references to this I could find (not just datdog) refers to rows fetched being the actual rows that contained the data that was being queried for while rows returned is number of rows returned by the storage layer to be scanned.

Here's what @sashwathn had found from SolarWinds. 

![image](https://user-images.githubusercontent.com/24860547/184383823-2b151aaf-332d-4990-b30c-c25a5089cbd3.png)

**Comment by ilyam8** [comment]
Related:
 - [commit](https://github.com/postgres/postgres/commit/3465c8a8692fb628bc2710fbeedb9aeb534b0400)
 - [discussion](https://postgr.es/m/9eeeccdb-5dd7-90f9-2807-a4b5d2b76ca3@oss.nttdata.com)

**Comment by ilyam8** [comment]
@anayrat @unhandled-exception can you help?

**Comment by anayrat** [comment]
Hello,
I will look at this in a few days, sorry for the delay.

**Comment by anayrat** [comment]
Thanks for raising this issue. From a user point of view, maybe we should have one metric has explained by @sashwathn https://github.com/netdata/netdata/issues/13512#issuecomment-1213085132

The best case is when we read has many rows that are needed i.e fetched = returned => 100%
The worst case is when we read too many rows and fetch none 0%

So, the formula `{$fetched} * 100 / {$returned}` make sense.

**Comment by sashwathn** [comment]
Thanks @anayrat for your valuable inputs.
@ilyam8 / @vlvkobal : Can we modify our ratios accordingly?

cc: @shyamvalsan @amalkov @ralphm @thiagoftsm

**Comment by ilyam8** [comment]
`{$fetched} * 100 / {$returned}` added in netdata/go.d.plugin#801. However, we have the same _problem_ as with all positive ratios (0 value ambiguity). Perhaps we need to convert it to fetched_miss_ratio?

**Comment by sashwathn** [comment]
> `{$fetched} * 100 / {$returned}` added in [netdata/go.d.plugin#801](https://github.com/netdata/go.d.plugin/pull/801). However, we have the same _problem_ as with all positive ratios (0 value ambiguity). Perhaps we need to convert it to fetched_miss_ratio?

We will need to figure out a solution which is global.. Right now, if we consider zero fetched and zero returned for most cycles as 100%, the average will always be skewed higher than usual.

@shyamvalsan any suggestions?

**Comment by ilyam8** [comment]
Also, probably we need to add overall ratio metrics (the ones we add are per data collection ratios, not overall).

**Comment by shyamvalsan** [comment]
While aggregating `db_rows_read_ratio `across multiple databases, I think we should first `SUM()` on the `rows_returned `and the `rows_fetched` and then take the ratio. In this way the ratio returned will be a true aggregate and we won't have a problem with handling the zero ambiguity either.

DB1: 100 rows fetched, 200 rows returned
DB2: 1 rows fetched, 10 rows returned
DB3: 0 rows fetched, 0 rows returned

SUM(rows_fetched) = 101
SUM(rows_returned) = 210

Aggregate rows read ratio = 50.5%

Filtering on each DB will also show accurate rows read ratio (as long as div/0 is handled for DB3)

Calculating the ratios first and then doing the average would give us misleading results in this case. Assuming my rusty math is correct.
