### ISSUE TITLE
[Bug]: netdata v1.36.1 fails to link libJudy correctly with LTO enabled on FreeBSD

### ISSUE THREAD

**Issue by forkbomb9** [netdata/netdata#13527]
### Bug description

Netdata uses plain `ar` to link libJudy, which causes the build to fail due to LTO link errors under FreeBSD[^1][^2].

This can be fixed by setting `AR` to the output of `cc --print-prog-name=llvm-ar`[^3] when compiling with Clang. It has the added benefit of working even when multiple clang/llvm versions are installed.

In theory this should be reproducible under Linux too. Unfortunately I have not been able to test whether it's the case.

references:
[^1]: https://github.com/netdata/netdata/issues/13520
[^2]: https://github.com/netdata/netdata/issues/13522
[^3]: https://bugzilla.mozilla.org/show_bug.cgi?id=1480005 and https://bugzilla.mozilla.org/show_bug.cgi?id=1539280

### Expected behavior

netdata uses llvm-ar to link libJudy when compiling with Clang.

### Steps to reproduce

1.
2.
3.
...

### Installation method

from source

### System info

```shell
FreeBSD localhost 13.1-RELEASE-p1 FreeBSD 13.1-RELEASE-p1 GENERIC amd64
1301000
```

### Netdata build info

```shell
Version: netdata v1.36.1
Configure options:  '--disable-unit-tests' '--disable-cloud' '--disable-plugin-cups' '--enable-dbengine' '--disable-plugin-freeipmi' '--enable-lto' '--prefix=/usr/local' '--localstatedir=/var' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/share/info/' '--build=amd64-portbld-freebsd13.1' 'build_alias=amd64-portbld-freebsd13.1' 'CC=cc' 'CFLAGS=-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing ' 'LDFLAGS= -Wl,-rpath,/usr/local/lib -fstack-protector-strong ' 'LIBS=' 'CPPFLAGS=-D_WANT_VMMETER' 'CXX=c++' 'CXXFLAGS=-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  ' 'PKG_CONFIG=pkgconf' 'PKG_CONFIG_LIBDIR=/usr/ports/net-mgmt/netdata/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig' 'CPP=cpp'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO (by user request)
    ACLK Next Generation:       NO
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: NO
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by Ferroin** [comment]
Confirmed that this is an issue on Linux as well (tested building with Clang 14.0.6 on my laptop), and also confirmed that the fix works there.

We ideally need something in the configure script (and CMake) to set this automatically so that a manual workaround is not needed.

I’m updating the labels here to mark this as a build system issue and not a packaging issue (because we need to handle this properly irrespective of packaging), and adding a CI label because we should in theory be checking builds with LTO even if we don’t build that way by default ourselves.
