### ISSUE TITLE
[Feat]: Add a summary dashboard section to PostgreSQL 

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13532]
### Description

Add a summary section for PostgreSQL

Summary should contain: 
- Total DB size
- Total connection utilization
- Cache Hit Ratio
- Rows Fetched vs Returned
- Uptime

### Importance

must have

### Value proposition

1. Quick summary view of PostgreSQL before diving into individual charts

**Comment by ilyam8** [comment]
@shyamvalsan #13534 has been merged, should we close the issue?
