### ISSUE TITLE
[Feat]: Update postgreSQL metrics organization

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13542]
### Description

This is the updated proposal for PostgreSQL metric organization. 

The main difference from what exists today, that is being proposed (based on discussion with @amalkov @sashwathn) is to organize metrics by functionality and not by whether they are global or grouped by database. So we won't have any more "db_" sections, and instead we will have the following sections. 

- summary
  - count (chart to be present after summary, no need of separate section)
  - uptime (chart to be present after summary, no need of separate section)
- size
- connections
- transactions
- throughput
- performance
- tables
- indexes
- queries
- bloat
- vacuum & analyze
- replication
- wal
- checkpointer
- background writer
- locks
- catalog

### Importance

must have

### Value proposition

1. Meaningful and structured organization of metrics is a must for users to easily, intuitive and usefully explore metrics and troubleshoot optimally.

**Comment by shyamvalsan** [comment]
Here's a more detailed list which lists what metrics (and charts) should be present in each section. Charts which should be "Grouped by database" by default are specifically called out. Charts in italics do not exist yet, and are [to be added](https://github.com/netdata/netdata/issues/13510).

- summary
  _- count of databases_
  - uptime
- size
  - _total db size vs available disk space_
  -  db_size
- connections
  -  connnections_utilization
  -  connections_usage
  -  db_connections_utilization
  -  db_connections
  - _oldest connection age_
- transactions
  -  db_transactions_ratio
  -  db_transactions
  -  oldest_transaction_xid
  -  percent_towards_txid_wraparound
  - _long running transaction count_
- throughput
  -  db_rows_read_ratio
  -  db_rows_read
  -  db_rows_written
- performance
  -  db_buffer_cache_hit_ratio
  -  db_blocks_read
  -  db_conflicts
  -  _dead_rows_ratio_
  -  _hot updated rows_
  -  db_temp_files
  -  db_temp_files_data
- _tables_
  -  _count of table columns which are entirely NULL_
  -  _count of table columns with only one value_
  -  _count of tables not vacuumed in last 7 days_ 
  -  _count of tables not analyzed in last 7 days_ 
  -  _age of oldest table vacuum_ 
  -  _age of oldest table analyze_
- _indexes_
  - _index cache hit ratio_
  -  _count of unused indexes_
- _queries_
  -  _number of active, idle, idle in transaction queries_
  -  _histogram of slow queries_
  - _count of blocked queries_
- _bloat_
  -  _percentage of tables with bloat_
  -  _total size of table bloat_
  -  _percentage of total table size that is bloated_
  -  _percentage of indexes with bloat_
  -  _total size of index bloat_
  -  _percentage of total index size that is bloated_
- vacuum & analyze
  -  autovauum_workers
  -  percent_towards_emergency_autovacuum
  -  _last vacuum age_
  -  _last autovacuum age_
  -  _last analyze age_
  -  _last autoanalyze age_
- replication
  -  replication_standby_app_wal_lag
  -  replication_standby_app_wal_delta
  -  replication_slot_files
- catalog
  -  catalog_relation_count
  -  catalog_relation_size
- WAL (write ahead logging)
  -  wal_writes
  -  wal_files
  -  wal_archive_files
- checkpointer
  -  checkpoints
  -  checkpoint_time
  - _average checkpoint frequency_
  -  _write time_
  -  _sync time_
- background writer
  -  bgwriter_buffers_alloc
  -  bgwriter_buffers_written
  -  bgwriter_maxwritten_clean
  -  bgwriter_buffers_backend_fsync
- locks
  -  db_deadlocks
  -  db_locks_held
  -  db_locks_awaited

**Comment by shyamvalsan** [comment]
note that this is not the final vision for how these metrics should be organized. Eventually, once TOC can support extra layers of [nesting](https://github.com/netdata/netdata-cloud/issues/550) we should have sections per database name and each database would have nested sections underneath which preserve the organization so all per DB metrics don't get clubbed together. Charts that show up nested under a database, should be the same composite charts but filtered on that particular database by default.

Here's what the final organization structure should look like 

PostgreSQL 1
 - Summary
 - Cluster level metrics
 - DB X
	- DB level metrics
 - DB Y
	- DB level metrics
PostgreSQL 2
 - Summary
 - Cluster level metrics
 - DB X
	- DB level metrics
 - DB Y
	- DB level metrics

**Comment by shyamvalsan** [comment]
cc: @ilyam8 @vlvkobal @amalkov @sashwathn @ralphm @cakrit

**Comment by ilyam8** [comment]
Do you think that the number of databases and uptime are the most important metrics (top section)?

**Comment by shyamvalsan** [comment]
@ilyam8 they aren't - they are the least important to me, I really just want them to show in the summary section. But they didn't really match to put under any of the other sections and I do not want to see separate TOC menu sections for them. So my suggestion was to just have them after summary, but open to better suggestions

**Comment by thiagoftsm** [comment]
@shyamvalsan I agree with @ilyam8 . Probably on summary we could have:
- Active connections.
- Size
- Queries runnning.

**Comment by shyamvalsan** [comment]
let's discuss over a call @thiagoftsm @ilyam8 I will set something up.

**Comment by shyamvalsan** [comment]
Had a quick discussion with @thiagoftsm @vlvkobal @sashwathn 

- add something to the summary to indicate active connections, for now this will just be a pie chart, maybe in future we can show a trend line to add more context. 
- keep the db count in summary, as there's no other clean way of telling the user how many DBs are being monitored. Since we auto discover new DBs, there's no simple way to keep a tab on this number.
- define using dashboard_info.js which charts are to be displayed grouped by database, by default.
- team to address https://github.com/netdata/netdata/issues/13510 (adding pending metrics) first, and then address this ticket to organize the metrics appropriately.

**Comment by ilyam8** [comment]
> db_buffer_cache_hit_ratio
> db_blocks_read
> db_conflicts
> dead_rows_ratio
> hot updated rows
> db_temp_files
> db_temp_files_data

An organization when we have a lot of db scope charts or mixing db scope with global scope charts will be very hard to navigate on the local/single node dashboards.

Not a blocker, just saying.

**Comment by shyamvalsan** [comment]
@ilyam8 hopefully it will be alleviated when we get nested sections in TOC and the per db metrics move under the "performance" section each individual DB.

**Comment by shyamvalsan** [comment]
@ilyam8 for metrics you have already added, please use the following organization

- connections
  -  connnections_utilization
  -  connections_usage
  -  connections_state
  -  db_connections_utilization
  -  db_connections
- transactions
  -  db_transactions_ratio
  -  db_transactions
  -  oldest_transaction_xid
  -  percent_towards_txid_wraparound
  -  transactions_running_time_histogram
- throughput
  -  db_rows_fetched_ratio
  -  db_rows_read
  -  db_rows_written
- performance
  -  db_buffer_cache_miss_ratio
  -  db_io
  -  db_temp_files
  -  db_temp_files_data
- tables
  -  table_total_size
  -  table_rows
  -  table_dead_rows
  -  table_rows_operations
  -  table_scans
  -  table_scans_rows
  -  table_io_cache_miss_ratio
  -  table_io
  -  table_hot_updates
  -  table_hot_updates_ratio
- indexes
  - table_index_io_cache_miss_ratio
  - table_index_io
- queries
  -  queries_running_time_histogram
- vacuum & analyze
  -  autovauum_workers
  -  percent_towards_emergency_autovacuum
- replication
  -  replication_standby_app_wal_lag
  -  replication_standby_app_wal_delta
  -  replication_slot_files
  -  db_conflicts
  -  db_conflicts_stat
- WAL (write ahead logging)
  -  wal_writes
  -  wal_files
  -  wal_archive_files
- checkpointer
  -  checkpoints
  -  checkpoint_time
- background writer
  -  bgwriter_buffers_alloc
  -  bgwriter_buffers_written
  -  bgwriter_maxwritten_clean
  -  bgwriter_buffers_backend_fsync
- locks
  -  db_deadlocks
  -  db_locks_held
  -  db_locks_awaited
- details
  -  db_size
  -  databases_count
  -  catalog_relation_count
  -  catalog_relation_size

**Comment by shyamvalsan** [comment]
Added the pending metrics to the list


- connections
  -  connnections_utilization
  -  connections_usage
  -  connections_state
  -  db_connections_utilization
  -  db_connections
- transactions
  -  db_transactions_ratio
  -  db_transactions
  -  oldest_transaction_xid
  -  percent_towards_txid_wraparound
  -  transactions_running_time_histogram
- throughput
  -  db_rows_fetched_ratio
  -  db_rows_read
  -  db_rows_written
- performance
  -  db_buffer_cache_miss_ratio
  -  db_io
  -  db_temp_files
  -  db_temp_files_data
- tables
  -  table_total_size
  -  table_rows
  -  table_dead_rows
  -  table_rows_operations
  -  table_scans
  -  table_scans_rows
  -  table_io_cache_miss_ratio
  -  table_io
  -  table_hot_updates
  -  table_hot_updates_ratio
  - count of table columns which are entirely NULL
- indexes
  - table_index_io_cache_miss_ratio
  - table_index_io
  - unused indexes
- queries
  -  queries_running_time_histogram
- bloat
  - percentage of total table size that is bloated
  - total size of table bloat
  - percentage of total index size that is bloated
  - total size of index bloat
- vacuum & analyze
  -  autovauum_workers
  -  percent_towards_emergency_autovacuum
- replication
  -  replication_standby_app_wal_lag
  -  replication_standby_app_wal_delta
  -  replication_slot_files
  -  db_conflicts
  -  db_conflicts_stat
- WAL (write ahead logging)
  -  wal_writes
  -  wal_files
  -  wal_archive_files
- checkpointer
  -  checkpoints
  -  checkpoint_time
- background writer
  -  bgwriter_buffers_alloc
  -  bgwriter_buffers_written
  -  bgwriter_maxwritten_clean
  -  bgwriter_buffers_backend_fsync
- locks
  -  db_deadlocks
  -  db_locks_held
  -  db_locks_awaited
- details
  -  db_size
  -  databases_count
  -  catalog_relation_count
  -  catalog_relation_size

**Comment by shyamvalsan** [comment]
@ilyam8 made some minor updates above.

**Comment by ilyam8** [comment]
The organization seems confusing to me - e.g. "throughput" has db data, "cache" has both db and tables data, "tables" is catch-all for the rest of tables metrics, "size" has db size, but not table or index, etc.

I think we need to either have everything throughput-related or "db throughput" and "table throughput", at least that looks like a pattern I can understand.

I tried to follow 2nd approach in netdata/go.d.plugin#824, and the result:


<img width="226" alt="Screenshot 2022-09-13 at 13 08 12" src="https://user-images.githubusercontent.com/22274335/189874536-2ab5ea28-3390-4af7-b322-23ff5ceec7dd.png">

**Comment by ilyam8** [comment]
1st approach example would be:

- connections
- transactions
- queries
- throughput
- cache performance
- size & bloat
- vacuum & analyze
- maintenance
- replication
- wal
- buffers
- checkpointer
- bgwriter
- txid exhaustion
- locks
- relations
- uptime

buffers, checkpointer and bgwriter can be aggregated into one category (don't know how to name it.)
