### ISSUE TITLE
Can't disable "Discover the free benefits of Netdata Cloud" even though I compiled without cloud support.

### ISSUE THREAD

**Issue by accessiblepixel** [netdata/netdata#13556]
### Problem

Can't disable "Discover the free benefits of Netdata Cloud:" even though I have cloud enabled set to "no" and cloud base url set to something non public.

I have tried recompiling as there was a suggestion I found online that this would get rid of it, but it doesn't.

The version packaged for opnsense doesn't have this "Discover the benefits of netdata cloud". I tried out the cloud version and it's not something I really want, and I'd like to get rid of the nags for the "free cloud" at the top.

The only place I can find that information is in one of the javascript files in /usr/share/netplan/static/js/main.cc0e57d1.chunk.js (and the same file but .js.map

How do I get rid of it?

If I have put this in the wrong place, sorry I'm not very good at github.

### Description

Disable 'free cloud' nag at the top of the page.

### Importance

really want

### Value proposition

People will try and click it, or maybe even try and link it with cloud and it won't work.

### Proposed implementation

Hide that information if cloud enabled = no in cloud.conf

**Comment by MrZammler** [comment]
Hi @accessiblepixel !

We have this request from other users too, but currently there is no way as it seems to disable. Will update the ticket when we have more news.

cc @hugovalente-pm 

Thanks for your input!

**Comment by Dim-P** [comment]
Somewhat relevant: [[Feat]: Disable cloud sign-in dialog](https://github.com/netdata/netdata/issues/12654)

**Comment by stvhay** [comment]
Very awesome tool, team--but I must admit I could do with less of the screen real estate and buttons dedicated to selling the paid product. 

- The arrow button on the side causes an expansion of ~ 1/4 of the screen to ask for a cloud login. Please get rid of that.
- Status indicator "Connection to cloud." Please get rid of that.
- A whole horizontal bar "Discover the benefits of Netdata Cloud." Please remove.

**Comment by hugovalente-pm** [comment]
@ilyam8 I'm re-opening since the fix hasn't yet been merged
@AlexNti will let us know once it is merged and then it will be available on the next nightly

**Comment by ilyam8** [comment]
@hugovalente-pm it has been merged 2 hours ago. We usually don't wait for a nightly release when closing an issue. We follow merge = fixed => close.

**Comment by RonnyReporter** [comment]
This issue still persist and it quite annoying to solve. I have recompiled from source many times yet I'm still greeted with a popup and a non-removable bar at top of every single page. 

I installed using:

```
./netdata-kickstart.sh --build-only --local-build-options --disable-cloud --disable-telemetry
```

After install it even tells me cloud is disabled yet I still see these options. Creating a cloud.conf with cloud turned off also doesn't help. 

How do I get rid of this top bar? 

I understand you guys want to sell cloud services but it's really irritating it is so difficult to get rid of it. I'm familiar with coming from sources and I've tried this many times now. I'm going to use an alternative but til wanted to report that this annoying issue still persists using the latest kickstart.sh script.

```
The following warnings and non-fatal errors were encountered during the installation process:

  - Cloud explicitly disabled, ignoring --require-cloud.
```

I feel like I'm being trolled here.
![cloud-spam](https://user-images.githubusercontent.com/49481771/213947497-428093f2-95e6-48ca-9ca8-62983c9a7652.png)

**Comment by ilyam8** [comment]
@RonnyReporter, hi.

- created debian11 VM
- installed netdata using `./kickstart.sh --build-only --disable-cloud --disable-telemetry`.

I get no Cloud-related bars and pop-ups

<details>
<summary>screenshot</summary>

<img width="1704" alt="Screenshot 2023-01-23 at 11 13 49" src="https://user-images.githubusercontent.com/22274335/214002997-223da4f4-989a-4524-8284-6b3b9f0e3c14.png">

</details>
