### ISSUE TITLE
[Feat]: Monitor Btrfs device stats (btrfs device stats)

### ISSUE THREAD

**Issue by Forza-tng** [netdata/netdata#13561]
### Problem

Missing feature

### Description

Btrfs collects statistics on various types of errors it encounters. It would be great if  Netdata could monitor these and trigger alarms when they change.

`btrfs device stats` can be used on a mount point or on an individual device:

```
## On a single device
# btrfs device stats /dev/sdb3
[/dev/sdb3].write_io_errs    0
[/dev/sdb3].read_io_errs     0
[/dev/sdb3].flush_io_errs    0
[/dev/sdb3].corruption_errs  0
[/dev/sdb3].generation_errs  0

## On a mount point
# btrfs device stats /mnt/rootvol/
[/dev/sdb3].write_io_errs    0
[/dev/sdb3].read_io_errs     0
[/dev/sdb3].flush_io_errs    0
[/dev/sdb3].corruption_errs  0
[/dev/sdb3].generation_errs  0
[/dev/sda3].write_io_errs    0
[/dev/sda3].read_io_errs     0
[/dev/sda3].flush_io_errs    0
[/dev/sda3].corruption_errs  0
[/dev/sda3].generation_errs  0
```
Normally they should all be 0. If there is an IO error that causes an error the counters increase. They do not get reset, but accumulate over the filesystem lifetime. It is, however, possible to clear stats using `btrfs device stats -z`

It is also possible to have a simple bolean type output using `btrfs device stats -c /mnt/`. This returns non-zero if there has been a detected error.

### Importance

must have

### Value proposition

To date there is no automatic tool to monitor btrfs filesystem health. Many admins create cron scripts that monitor device stats output and trigger an email or similar on problems, but most simple don't monitor this at all. Netdata could add real value to peoples monitoring :)

**Comment by ilyam8** [comment]
Closed by accident.

Hi, @Forza-tng. Netdata gathers BTRFS metrics by reading files under `/sys/fs/btrfs/*`. Netdata doesn't use `btrfs` or any other executable. If the desired metrics can be found in the directory then we can add them. Can you check that? Using an executable is likely no-go (at least for the current btrfs collector implementation).
