### ISSUE TITLE
[Feat]: nvidia-smi should log also the pstate

### ISSUE THREAD

**Issue by mailinglists35** [netdata/netdata#13577]
### Problem

nvidia-smi can show the power state of the device (P0,P5,P8 etc - https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__gpupstate.html)

however the plugin does not seem to collect this metric, neither the doc mentions it (https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/nvidia_smi/)

it would be nice to also see this added to monitor.

nvidia-smi --format=csv --query-gpu=pstate
pstate
P8

related: I've read the related discussion in https://github.com/netdata/netdata/issues/10362 about xml vs csv. 
In my system, nvidia-smi does show the power state in xml mode, so this issue perhaps could easily be solved in current design of nvidia-smi plugin

I see		<power_readings>
			<power_state>P8</power_state>
in the xml output

But maybe could we have an option for the csv working mode of nvidia-smi? I see the xml produces a lot of unuseful output like a list of all supported clocks which imho is wasted resources every poll.

### Description

process also power_readings from /usr/bin/nvidia-smi -x -q -l 1

		<power_readings>
			<power_state>P8</power_state>

### Importance

nice to have

### Value proposition

1. ?
2.
3.
...

### Proposed implementation

I think I wrote everything in the begining :)

thanks

**Comment by ilyam8** [comment]
Hi, @mailinglists35. Unfortunately, I have no access to a server with Nvidia GPU.

> But maybe could we have an option for the csv working mode of nvidia-smi?

I plan to do that when I have access to a server with Nvidia GPU (and rewrite python=>go). Unfortunately, I have no at the moment.

**Comment by mailinglists35** [comment]
I see.
until then, would this xml output from current setup help you adjust the plugin to also log the power state?

it seem to be exposed in two places, but nonetheless they both reflect the current power state, tested with load and on idle, load P0, idle P8. grep for capital letter P to locate it in the output

[usr-bin-nvidia-smi-x-q.txt](https://github.com/netdata/netdata/files/9438335/usr-bin-nvidia-smi-x-q.txt)

**Comment by ilyam8** [comment]
@mailinglists35 can you test #13580?

**Comment by mailinglists35** [comment]
sure, in about 20 minutes

**Comment by ilyam8** [comment]
I made it a dimension per Power State, not just a dimension with 0-15 values because averaging (and aggregated view on the Netdata Cloud) would be misleading.

**Comment by mailinglists35** [comment]
works, thank you!

**Comment by mailinglists35** [comment]
![image](https://user-images.githubusercontent.com/2054302/187046579-2fc92317-3320-4839-8f57-a909af50c1dc.png)

**Comment by mailinglists35** [comment]
![image](https://user-images.githubusercontent.com/2054302/187046585-6f5cc0df-5d2f-49c1-89ce-929c3bfb58fe.png)

**Comment by ilyam8** [comment]
Thanks for testing, @mailinglists35 👍
