### ISSUE TITLE
[Feat]: save ML models to database

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#13585]
### Problem

Currently on agent restart all models are lost and user must wait until training is complete again.

### Description

We need to save the trained ml models to the database so that they can quickly be loaded on agent restart and scoring can begin asap.

### Importance

must have

### Value proposition

1. more robust and stable anomaly detection capabilities. 
...

### Proposed implementation

Save models to dbengine or metadata database. Load them back into memory on restart.

**Comment by MrZammler** [comment]
@andrewm4894 Hey Andy, this should be ok now? (with https://github.com/netdata/netdata/pull/14981).

**Comment by andrewm4894** [comment]
Yep, closing thanks
