### ISSUE TITLE
[Feat]: Anomaly detection - simplifly agent anomaly detector logic

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#13586]
### Problem

Existing logic is too complex and hard to maintain.

### Description

We need to simplifly the logic behind the `anomaly_detection.anomaly_detector` chart. 

### Importance

must have

### Value proposition

1. clearer logic for users to understand and reason about.
2. easier code to maintain with reduces overhead on agent.
...

### Proposed implementation

As discussed with @vkalintiris we will trigger anomaly events based on a simple rolling average of the node anomaly rate.

**Comment by vkalintiris** [comment]
@andrewm4894 I think we can close this now.

**Comment by andrewm4894** [comment]
agree
