### ISSUE TITLE
[Feat]: Anomaly Detection extend training window

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#13584]
### Problem

Following on from discussion here: https://github.com/netdata/netdata/discussions/12763

We need to, effectivley, extend the training window for the ML based anomaly detection. 

There are many ways to do this and what we have decided to do is save trained models to essentially achieve an extended training window. 

### Description

We have a branch here that implements our ideas

https://github.com/vkalintiris/netdata/tree/multiple-ml-models

### Importance

must have

### Value proposition

1. better anomaly detection quality
2. solve "6am cron job" problem of false positives
...

### Proposed implementation

https://github.com/vkalintiris/netdata/tree/multiple-ml-models

As we train models we hold onto them. Then at prediction time we score against a wider set of saved models that were trained on different slices of time.

**Comment by andrewm4894** [comment]
@vkalintiris do you think you can get back on this next week or week after?

**Comment by vkalintiris** [comment]
@andrewm4894 can you check https://github.com/vkalintiris/netdata/tree/multiple-ml-models? The branch has the entire logic for handling multiple models, except for serialization/deserialization to/from disk. If it works correctly, I can add this functionality next week.

**Comment by vkalintiris** [comment]
@andrewm4894 can you check https://github.com/vkalintiris/netdata/tree/multiple-ml-models? The branch has the entire logic for handling multiple models, except for serialization/deserialization to/from disk. If it works correctly, I can add this functionality next week.

**Comment by andrewm4894** [comment]
Will do, was just unsure if that branch needed to be rebased or anything with all other changes in agent recently. Will make a node today from it and test again.

**Comment by vkalintiris** [comment]
I rebased it on top of master 1-2 hours ago.

**Comment by vkalintiris** [comment]
@andrewm4894 can we close this and the associated discussion now?

**Comment by andrewm4894** [comment]
Yep - i'll close now and after upcoming release add link to the ml section in upcoming release notes that covers this and summarises a little.
