### ISSUE TITLE
[Bug]: httpcheck bad_status alert is not raised

### ISSUE THREAD

**Issue by solution-al** [netdata/netdata#13596]
### Bug description

Using `go.d/httpcheck.conf` does not raise any alarms on unsuccessful checks.

We have set up netdata on another server some time ago using version `v1.33.1-28-nightly` to check some HTTP endpoints and we confirmed just now that if check is unsuccessful an alarm will be raised. However, using similar conf on another machine with netdata version `v1.36.1` does not raise any alarms. We can see on the netdata httpcheck chart that `bad status` comes out of the request but no alarms or warnings will be raised.

Configuration itself is something similar to this:
```
$ cat /etc/netdata/go.d/httpcheck.conf
jobs:
  - name: endpoint
    url: http://localhost/health
    timeout: 3
    update_every: 10
    response_match: ^OK
```

We can verify that response is **not** OK:
```
$ curl localhost/health
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

No notifications will be sent and no alarms/warnings are visible on the netdata web dashboard. Only thing we see is that chart shows `bad status` instead of `success status`.

### Expected behavior

netdata shall raise an alarm and send out notifications as it does on our other machine using older version.

### Steps to reproduce

See "Bug description"

### Installation method

kickstart.sh

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.5 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.5 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.36.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

Only maybe relevant thing we see in the netdata error log regarding `httpcheck` plugin is the following line:
```
2022-08-31 08:16:56: netdata ERROR : PLUGINSD[go.d] : Health alarm 'httpcheck_endpoint.request_status.httpcheck_web_service_up' has update every 5, less than chart update every 10. Setting alarm update frequency to 10.
```

**Comment by MrZammler** [comment]
Hi @solution-al thank you for your report. We will try to reproduce it and update the ticket. Thanks.

**Comment by MrZammler** [comment]
Hi @solution-al . Indeed there is a problem with the alert and the dimensions of the chart.

The alert defines a lookup on dimension `bad_status` however the dimension on the chart is `bad status`, i.e. -> https://github.com/netdata/netdata/blob/a150694aa43b2a410a2c3f7d9f493eeb408ebf41/health/health.d/httpcheck.conf#L38

We will change the chart's dimension to be `bad_status` most likely (and of the other charts dimensions of that module), but this will appear in next stable release. Until then you can edit your installed alert file (in `/usr/lib/netdata/conf.d/health.d/httpcheck.conf`) and edit the above lookup line to be `lookup: average -5m unaligned percentage of bad status`.

Similar to the other alerts in that file if you need them.

On the next update this file will be overwritten and return to it's stock lookup entry, but at the same time the dimension name will be also updated and things should work ok.

**Comment by solution-al** [comment]
@MrZammler thank you for your reply.

Looking at the [commit](https://github.com/netdata/go.d.plugin/pull/788) made by @ilyam8 it seems that the solution is not the one you said to be most likely. What should we done with our current stable installation so that it would start work and would not break after updating netdata in the future?
