### ISSUE TITLE
[Bug]: when ML is enabled, all RRD structures are locked while detectOnce() is running

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#13605]
### Bug description

In ML, there is Mutex to protext a Map of dimensions to be detected:

https://github.com/netdata/netdata/blob/340d0e504c7ffd6637b420553d4e17ee510c37a8/ml/Host.cc#L423

This is the same Mutex used when adding a new dimension into the RRD structures:

https://github.com/netdata/netdata/blob/340d0e504c7ffd6637b420553d4e17ee510c37a8/ml/Host.cc#L269

So, while `detectOnce()` is working, no dimensions can be added to Netdata. If for example a container is started at that time, the entire cgroups.plugin may be locked for up to 30 seconds, until `detectOnce()` finishes the iteration.

In this screenshot we see that plugins.d is blocked for 30 seconds while adding dimensions:

![image](https://user-images.githubusercontent.com/2662304/187756687-9b16105b-b06e-4315-8406-42a221a32438.png)

And in this screenshot we see that ML detection uses 100% CPU utilization at the same time plugins.d is blocked:

![image](https://user-images.githubusercontent.com/2662304/187757154-e7e786fb-16e3-49ef-b6c0-1f1e79db8962.png)

### Expected behavior

Adding dimensions should never be blocked like this.

### Steps to reproduce

1. Run ML training
2. Generate dimensions during runtime (containers, interfaces, whatever)
3. If the dimensions are generated while ML training is running, the collector will be blocked.

### Installation method

from source

### System info

```shell
N/A
```

### Netdata build info

```shell
Latest master.
```

**Comment by ktsaou** [comment]
We can replace the Map and the Mutex with a dictionary.

The dictionaries have a REENTRANT lock mode while traversing them. In this mode, the traversal gets and releases a read lock between each iteration. This allows safe dictionary traversal while others are reading or even manipulating it. Even the current item can be deleted by others in a safe way (it uses a reference counter and a garbage collector to support this, so the current item is marked as deleted and it gets deleted when it is released).

**Comment by vkalintiris** [comment]
The detection step runs once per second and even on an rpi takes at most a couple msecs, ie. whichever other thread wants to create thousands of dimensions has ample time to do so. I suspect something else is going on here and makes the detection step to consume full CPU. Is this consistently reproducible?

**Comment by vkalintiris** [comment]
https://github.com/netdata/netdata/blob/544aef1fde6e79ac57d2dea85d3f063076d7f885/ml/Dimension.h#L120 is causing the issue. Following screenshot is from an agent without that update, running a plugin that creates 500 new charts with 10 dimensions every 60 seconds (compiled with -O0):

<img width="1388" alt="Screenshot 2022-09-05 at 10 46 33 AM" src="https://user-images.githubusercontent.com/25480816/188396884-88778d5c-b82a-45e1-85c8-17f670acce42.png">

This can be solved by using the tiered-db functionality.

**Comment by vkalintiris** [comment]
FWIW, the real culprit is: https://github.com/netdata/netdata/blob/544aef1fde6e79ac57d2dea85d3f063076d7f885/database/rrddim.c#L502. The performance degradation happens only when rrd context is enabled (again compiled with -O0):
<img width="1680" alt="Screenshot 2022-09-05 at 11 10 15 AM" src="https://user-images.githubusercontent.com/25480816/188401352-8528915e-68c2-4cd4-b554-2cb306523cd9.png">

**Comment by ktsaou** [comment]
This was revealed during a test of an agent with 30k charts, 10 dimensions each, all at the same context. We did changes in rrdcontexts to make them more performant in this case and the rrdcontext call from rrddim_set_by_pointer was later removed.

We will repeat the test to see if it still there.

**Comment by ktsaou** [comment]
I removed RRDCONTEXT processing from data collection, with PR https://github.com/netdata/netdata/pull/13629

Still, when ML is enabled, there are several issues at the agent, slowing down data collection.

Even 1 second latency to add dimensions to netdata is serious when the agent is processing 500k dimensions or more.
Let's discuss this tomorrow.

**Comment by Dim-P** [comment]
@ktsaou @vkalintiris Has this one been fixed?

**Comment by vkalintiris** [comment]
This has been fixed a while ago.
