### ISSUE TITLE
[Feat]: User-friendly tool to collect and submit debugging reports

### ISSUE THREAD

**Issue by Dim-P** [netdata/netdata#13610]
### Problem

Currently, there isn't a standardised way for users to collect and submit data and other critical information for debugging (e.g. buildInfo, error.log at minimum). This:

1. creates problems due to the bug templates varying depending on the platform the user is using to report a bug or an issue and
2. wastes time, as it often takes a couple of back and forth posts to request the necessary information from the user.

### Description

It could be implemented as a new script or as part of https://github.com/netdata/netdata/tree/master/cli. Build and system info alongside the error.log should be the minimum data provided (as a tarball). 

Next phase could include (automated) submission of such reports to a cloud object storage provided by Netdata. Log retention period could be set by the user when the tarball is uploaded. A unique token could then be automatically generated and passed on to the support team. Similar to the way[ Pihole debugging works](https://discourse.pi-hole.net/t/how-do-i-debug-my-pi-hole-installation/3104).

### Importance

really want

### Value proposition

1. Faster support.
2. Reduced time (and thus cost) spent on each ticket by the support team.
3. Universally standardised (and hopefully automated) way to debug agent issues.

**Comment by shyamvalsan** [comment]
A thing to keep in mind is that this tool should run near instantly (as far as feasible) - because the user is running it because they ran into a problem, and then making them wait even longer is not very user friendly. 

Maybe have a hard threshold, after which if the tool is still running then we cut our losses and end data collection with what we have so far.

**Comment by Dim-P** [comment]
> A thing to keep in mind is that this tool should run near instantly (as far as feasible) - because the user is running it because they ran into a problem, and then making them wait even longer is not very user friendly.
> 
> Maybe have a hard threshold, after which if the tool is still running then we cut our losses and end data collection with what we have so far.

I would think in the first place it would just collect data based on previous executions, not live data collection from a new session.

**Comment by Dim-P** [comment]
@shyamvalsan Is it OK to collect data from http://localhost:19999/api/v1/info into the tarball? I know we collect that through anonymous statistics by default, however in this case it won't be anonymised as we will know the user who submitted the data.

**Comment by shyamvalsan** [comment]
IMO since this is a user triggered action it should be OK to collect this @Dim-P and maybe hav a page in learn that lists everything this tool collects for full transparency.

**Comment by Dim-P** [comment]
Relevant: https://github.com/netdata/netdata/issues/6123
