### ISSUE TITLE
[Feat]: Add bloat metrics and other important low-fidelity metrics to PostgreSQL collector

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13639]
### Problem

Netdata does not monitor PostgreSQL bloat metrics.

### Description

It is crucial to understand bloat statistics regarding PostgreSQL tables and indexes

The following metrics should be collected - every hour (3600seconds).

~~- [ ]   [Percentage of tables with bloat](https://github.com/ioguix/pgsql-bloat-estimation/blob/master/table/table_bloat.sql)~~
- [x]   [Total size of table bloat](https://github.com/ioguix/pgsql-bloat-estimation/blob/master/table/table_bloat.sql)
- [x]   [Percentage of total table size that is bloated](https://github.com/ioguix/pgsql-bloat-estimation/blob/master/table/table_bloat.sql)
~~- [ ]   [Percentage of indexes with bloat](https://github.com/ioguix/pgsql-bloat-estimation/blob/master/btree/btree_bloat.sql)~~
- [x]   [Total size of index bloat](https://github.com/ioguix/pgsql-bloat-estimation/blob/master/btree/btree_bloat.sql)
- [x]   [Percentage of total index size that is bloated](https://github.com/ioguix/pgsql-bloat-estimation/blob/master/btree/btree_bloat.sql)

It is also important to collect the following metrics - at the listed granularity

Every hour
- [x] [Count of unused indexes](https://github.com/HariSekhon/SQL-scripts/blob/master/postgres_indexes_unused.sql)
   
Every 24 hours
- [x] [Count of table columns which are entirely NULL](https://github.com/HariSekhon/SQL-scripts/blob/master/postgres_columns_null.sql)
~~- [ ] [Count of table columns with only one value](https://github.com/HariSekhon/SQL-scripts/blob/master/postgres_columns_useless.sql)~~

### Importance

blocker

### Value proposition

1. Bloat statistics are crucial for PostgreSQL performance monitoring

**Comment by ilyam8** [comment]
Found this [beauty](https://github.com/bucardo/check_postgres/blob/9f536c724397906557585ecae4d1cb6c68db26f9/check_postgres.pl#L4336). We need to check, probably using it (one query vs 6) is better.

pgdash guys [use it](https://github.com/rapidloop/pgmetrics/blob/35516b55da71f8aa05b84f360032e9ca68b6d830/collector/collect.go#L3141-L3147).

**Comment by shyamvalsan** [comment]
@ilyam8 is the worst case scenario so bad? For the 1st two hours your bloat charts will not have data - but after that they will always have data. 

What am I missing here?

**Comment by ilyam8** [comment]
I decided to go with [this query](https://github.com/netdata/netdata/issues/13639#issuecomment-1239974698) (because it is one).

> Total size of table bloat
> Percentage of total table size that is bloated

I am confused by the total word. Do you mean global scope metrics or what? I added per table (table_bloat_size, table_bloat_size_perc).

**Comment by ilyam8** [comment]
Ok, I added 

> Count of table columns which are entirely NULL

I didn't add

> Count of table columns with only one value

The query counts the number of distinct values in a column. I tried but didn't find any rationale why collect the value. Is it a problem if it is only one distinct value? And not a problem if there are two!


> Percentage of tables with bloat
> Percentage of index with bloat

Ok, we have per table and per index bloat %. Are you suggesting calculating those two as global?

**Comment by ilyam8** [comment]
Btw there are [3 tables, index views](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ALL-TABLES-VIEW):
 - user
 - system
 - all (user + system)

I use only the user one when collecting table/index stats.

**Comment by shyamvalsan** [comment]
@ilyam8 I have removed some of the metrics from the ticket description for now - as they maybe overkill. 

The only pending one is unused indexes, if we can show the actual indexes themselves in this chart that is the best.

**Comment by shyamvalsan** [comment]
The query actually returns the list of unused indexes, so if we can have a chart where only unused indexes have a value that could work

```
SELECT
  relname AS table,
  indexrelname AS index,
  idx_scan,
  idx_tup_read,
  idx_tup_fetch,
  pg_size_pretty(pg_relation_size(indexrelname::regclass))
FROM
  pg_stat_all_indexes
WHERE
  schemaname = 'public'
    AND
  idx_scan = 0
    AND
  idx_tup_read = 0
    AND
  idx_tup_fetch = 0
ORDER BY
  pg_relation_size(indexrelname::regclass) DESC;
```

**Comment by ilyam8** [comment]
I added index_usage_status for every index

<details>
<summary>screenshot</summary>

<img width="1324" alt="Screenshot 2022-09-12 at 23 07 32" src="https://user-images.githubusercontent.com/22274335/189747528-a5dcbdf6-2769-4542-91b1-cc21f946c3fb.png">

</details>
