### ISSUE TITLE
[Bug]: Thread sanitizer errors with `-W dicttest`

### ISSUE THREAD

**Issue by vkalintiris** [netdata/netdata#13647]
### Bug description

The thread sanitizer reports errors when running the dictionary unit tests.

### Expected behavior

Ideally, not even false-negative reports from the sanitizer.

### Steps to reproduce

1. `CFLAGS='-Wall -Wextra -g -O0 -fsanitize=thread -fno-omit-frame-pointer' ./netdata-installer.sh --disable-ml --dont-wait --dont-start-it --install ~/opt/master/`
2. ./usr/sbin/netdata -W dicttest
...

### Installation method

other

### System info

```shell
Darwin <hostname> 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64 arm Darwin
ProductName:    macOS
ProductVersion: 12.5.1
BuildVersion:   21G83
```

### Netdata build info

```shell
N/A (master sha 9b493a3c1bb09d9debd2c54f6facebe97049f378)
```

### Additional info

Thread sanitizer logs: 
[log.txt](https://github.com/netdata/netdata/files/9524817/log.txt)

**Comment by ktsaou** [comment]
I addressed these issues.
I decided to keep one data race, since I don't see any problems with it.

**Comment by ktsaou** [comment]
I also removed the data race that I said above I decided to keep.
Now it should be 100% clean.
