### ISSUE TITLE
[Feat]: Change order of sections in K8s tab

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13663]
### Problem

The K8s containers section contains the map view which should be visible when a user enters the K8s tab - but instead it is the final section and can only be seen after user scrolls all the way down

### Description

Kuberentes containers should be on top so this view will be seen immediately

![image](https://user-images.githubusercontent.com/24860547/190140580-1edf175e-ee46-423f-83ac-5a3c106c0daa.png)

Currently it is at the bottom

![image](https://user-images.githubusercontent.com/24860547/190140657-867c805c-8eee-4fa7-8637-f1f0df3b0d2c.png)

### Importance

really want

### Value proposition

1. Improves usability of K8s tab

**Comment by shyamvalsan** [comment]
@cakrit assuming this is what you asked for yesterday - unless I am wrong.

**Comment by ilyam8** [comment]
The current order was requested in #5824

**Comment by ilyam8** [comment]
The fix is changing the hardcoded priority for k8s_kubeproxy, k8s_kubelet, and k8s_state charts. Am I right, @cakrit? Or there are some plans to overwrite the priority by the frontend?

**Comment by cakrit** [comment]
Sorry for not replying here, indeed we had agreed to do a hardcoded change in the FE which I see still hasn't been done.

**Comment by ilyam8** [comment]
I changed the collectors priority.
