### ISSUE TITLE
[Bug]: Node is shown as "offline" randomly

### ISSUE THREAD

**Issue by michaelweinold** [netdata/netdata#13676]
### Bug description

Netdata cloud dashboard shows node as "offline" sometimes. When I connect to the headless Raspberry Pi node via VNC and open the browser, the node comes back online in the Netdata cloud dashboard. When back online, the dashboard shows history also for the time during which the node was offline.

### Expected behavior

The node is online without interruption.

### Steps to reproduce

1. install using one-line-install-script
2. set up Netdata account for connection to cloud dashboard

### Installation method

kickstart.sh

### System info

```shell
Linux OMEGASERVER 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
```

### Netdata build info

```shell
Version: netdata v1.36.0-120-g4e57cd9be
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: armv7l
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

A restart of the node also seems to bring the node back online if it is being shown as "offline".

**Comment by MrZammler** [comment]
Hi @michaelweinold 

Can you grep your `error.log` file for `ACLK` ? It should show if there was any cases of disconnections or other problems with cloud connectivity. Thanks!

**Comment by michaelweinold** [comment]
I could't find the logs at `/var/log/netdata/`, [where they are supposed to be according to the documentation](https://learn.netdata.cloud/docs/configure/nodes).

Instead, the file was at `./opt/netdata/var/log/netdata/error.log`. Searching for `ACLK` gave:

📄 [error.log](https://github.com/netdata/netdata/files/9599632/error.log)

**Comment by MrZammler** [comment]
Indeed there are a lot of "Connection Error or Dropped" messages in the log... Can we assume that the network connection of the Raspberry is ok in general, i.e. you don't have any other network problems in general ?

(Your log file is in /opt/ since most likely you are running a pre-compiled static version of the agent).

Have you noticed this problem recently? Can you please also post the part from `http://raspberry_ip:19999/api/v1/info` under `mirrored_hosts_status` ?

Thanks!

**Comment by michaelweinold** [comment]
I've only been using Netdata for a day - so unfortunately, I don't have anything to compare the current intermittent connection against.

The Raspberry is on a stable wired network connection.

`http://localhost:19999/api/v1/info`: 📄 [api-info.log](https://github.com/netdata/netdata/files/9600842/api-info.log)

**Comment by MrZammler** [comment]
Thanks for this. We'll check to see if we can spot anything weird from the cloud side.

**Comment by hugovalente-pm** [comment]
for x-reference, this seems similar to this bug https://github.com/netdata/netdata-cloud/issues/329

**Comment by michaelweinold** [comment]
I now have the Netdata service running on a more powerful node also:
```
Ubuntu • 3.4 GHz • 32 Cores • x86_64 • 126 GiB RAM • 7.0 TiB HD
```
vs the Raspberry Pi, for which I opened this issue:
```
Raspbian GNU/Linux • 1.2 GHz • 4 Cores • armv7l • 923 MiB RAM • 1.8 TiB HD
```
So far no issues with the higher performance node. @MrZammler - any insights so far?

**Comment by MrZammler** [comment]
Sorry, not much yet... I'm a bit reluctant to suggest something with the static build, or the raspberry itself...

We've had another internal case, similar as yours, on a raspberry pi... I will try something and let you know.

**Comment by MrZammler** [comment]
Hi @michaelweinold 

Can you please check if with v1.36.0-183 things have somewhat improved for the cloud connection?

You can check by looking at the `ACLK/Cloud connection status` chart, in section `ACLK` under `Netdata Monitoring`.

Thanks!

**Comment by michaelweinold** [comment]
Issue seems to be fixed with `v1.36.0-183-g45ff154cb`. Chart below:

<img width="1180" alt="Screenshot 2022-10-07 at 15 12 15" src="https://user-images.githubusercontent.com/23102087/194562089-6c6c34aa-80c2-4381-ad8e-587e5021bf6d.png">

Many thanks for following up 🙏🏻

**Comment by andrewm4894** [comment]
Thanks @michaelweinold i was just confirming this today myself as i had similar issue with my own node. @MrZammler did a fix yesterday. 

Going to check it again on Monday but looking promising so far from what i can see.

**Comment by michaelweinold** [comment]
@MrZammler, my Raspberry node again is offline intermittently (until restarted manually). Can you confirm?
