### ISSUE TITLE
[Feat]: Connect to api.netdata.cloud by default

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata#13682]
### Problem

The domain used for the initial connection to Cloud is currently `app.netdata.cloud`. This should be changed to `api.netdata.cloud`.

### Description

The Agent uses the `env` endpoint to determine where to go for authentication and eventually connecting to Cloud via MQTT. This initial connection should be done to `api.netdata.cloud` instead of `app.netdata.cloud`.

### Importance

must have

### Value proposition

1. Clearly distinguish the Cloud frontend from where Agents connect
2. Allow for earlier rejection of very old versions of the agent, for which connection attempts will fail anyway at a later stage, to reduce load on Cloud.
3. Allow for eventually deprecating app.netdata.cloud in favour of another domain. 

### Proposed implementation

The default value for the Agent's `cloud base url` should be modified to `https://api.netdata.cloud`. This also goes for the base URL used for claiming Agents to Cloud, as well as various places in documentation. When making this change, make sure to distinguish references to the Cloud frontend (which will remain at https://app.netdata.cloud/ for now) from others.

This ticket relates to [earlier work](https://github.com/netdata/infra/issues/1273) being done in Cloud.

**Comment by underhood** [comment]
@ralphm is this still valid?
