### ISSUE TITLE
[Feat]: Add metrics to Redis go collector

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13687]
### Description

Add the following metrics to the Redis Go collector: 

- [x] Latency
  - Latency measures the average time in milliseconds it takes the Redis server to respond.
  - This metric is not available through the Redis info command. To see latency use:
`./redis-cli --latency -h ‘host’ -p ‘port’`
  - While	times	depend on your actual setup,	typical latency for a 1GBits/s network is	about	200	μs.
  - Other options to explore include [latency-monitor](https://redis.io/docs/reference/optimization/latency-monitor/) 

- [x] Time since last interaction 
  - Time in seconds since last interaction between replica and primary
  - Use `info replication` in Redis CLI to fetch this information

- [x] Time since link down 
  - Time in seconds since link between replica and primary went down
  - Use `info replication` in Redis CLI to fetch this information

- [x] Last rdb save time
   -  Use `info persistence` in Redis CLI to fetch this information

### Importance

must have

### Value proposition

1. More comprehensive and useful Redis monitoring

**Comment by ilyam8** [comment]
> Latency measures the average time in milliseconds it takes the Redis server to respond.
> ./redis-cli --latency -h ‘host’ -p ‘port’

We definitely not using `./redis-cli --latency` directly. Internally it just sends the PING command and measures the response (does it thousands of times). We can do the same but send just a few. It measures the latency between the client (go.d.plugin) and your Redis server. Not sure if that is something useful to monitor constantly, and should we go with min/avg/max or histogram?

As for latency-monitor, I wasn't able to get any latency data so far

> Only events that take longer than the specified threshold will be logged as latency spikes.

Even after setting the threshold to 1ms

**Comment by ilyam8** [comment]
@shyamvalsan I went with 5 PINGs and min/max/avg.

**Comment by ilyam8** [comment]
> Time in seconds since last interaction between replica and primary

What metric do you have in mind? Can you name it?

**Comment by shyamvalsan** [comment]
Yes and "Time since link down" is `master_link_down_since_seconds`
