### ISSUE TITLE
[Feat]: Add alerts for Redis metrics

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13691]
### Problem

Netdata Redis collector does not have any pre-configured alerts

### Description

The following metrics should have pre-configured alerts: 

1. [ ] **redis.mem_fragmentation_ratio**
   - The mem_fragmentation_ratio metric gives the ratio of memory used as seen by the operating system (used_memory_rss) to memory allocated by Redis (used_memory).
   - mem_fragmentation_ratio > 1.5 indicates excessive fragmentation (restarting Redis instance will allow the operating system to recover memory previously unusable due to fragmentation)
   - mem_fragmentation_ratio < 1 indicates Redis needs more memory than is available on your system, which leads to swapping. Swapping to disk will cause significant increases in latency. 
   -  Ideally, mem_fragmentation_ratio equal to 1 or slightly greater.

2. [x] **redis.connections.rejected**
   - If redis connections rejected is non-zero for a significant amount of time an alert should be raised 

3. [ ] **keyspace_lookup_hitrate**
   - If the hit rate is < 80% then a significant amount of the requested keys are evicted, expired, or do not exist at all. 
   - It is crucial to watch this metric while using Redis as a cache. Lower cache hit ratio results in larger latency as most of the requests are fetching data from the disk. It indicates that you need to increase the size of Redis cache to improve your application’s performance

4. [x] **Time since link down**
   - alert when this value > 0 
   - This value should not exceed zero, if it does it indicates primary and replica are not in constant communication

~~5.  **latency**
    - https://redis.io/docs/reference/optimization/latency/
    - We should have an alert for latency once the metric is added - I think we should set a reasonably high threshold for the alert (200ms?) and then leave it to the user if they want to reduce the threshold.~~

### Importance

must have

### Value proposition

1. Automated troubleshooting for Redis

### Proposed implementation

WIP

**Comment by ilyam8** [comment]
@shyamvalsan I don't think we are at the point where we can add anomaly alerts by default:

 - no tested.
 - no certain action from a user perspective (anomalous and what do I do?).

What makes you think we need anomaly alarms? Have we tested them and they proved to be useful?

**Comment by shyamvalsan** [comment]
@ilyam8 not done with this ticket, I am still working on it - maybe we won't need anomaly alerts for some of them. Assigned ticket to myself until its ready.

**Comment by shyamvalsan** [comment]
@ilyam8 I have updated the description - removed some alerts which were related (one triggering would mean the other would also trigger). There's nothing anomaly bit based for now.

**Comment by shyamvalsan** [comment]
OK Let's proceed without the Latency alert for now.

**Comment by ilyam8** [comment]
@sh I just started a few Redis containers (using official images, redis_version:7.0.4) and mem_fragmentation_ratio is 12-13 (no load at all).

**Comment by shyamvalsan** [comment]
> @shyamvalsan  I just started a few Redis containers (using the official image, redis_version:7.0.4) and mem_fragmentation_ratio is 12-13 (no load at all).

How is the ratio being calculated? Because ratio of 1.5 might imply 150%

**Comment by ilyam8** [comment]
It is used_rss / used_memory

```bash
docker run --name some-redis -d redis
docker exec some-redis redis-cli INFO MEMORY | grep fragmentation
```

**Comment by ilyam8** [comment]
@shyamvalsan ok, the description

> Note that this doesn't only includes fragmentation, but also other process overheads (see the allocator_* metrics), and also overheads like code, shared libraries, stack, etc.

So my understanding is that this is not a very accurate metric and is completely wrong when the process RSS overhead (code, shared libraries, stack, etc) is relatively high (like in my case, no data no load).

**Comment by ilyam8** [comment]
Added 2 and 4.

- mem_fragmentation: not an accurate metric according to my quick research. At the same time can't say that _allocator_frag_ratio_ is the way to go.
- **hit**rate: bites again: we need a miss rate. Hit is not applicable for an alarm for us.
- latency: can't use PING latency for a stock alarm.

**Comment by shyamvalsan** [comment]
@ilyam8 instead of hitrate we can use keyspace_misses directly as a metric to alert on. 

For mem_fragmentation let me think some more, do you have a system with redis running where I can login and check these metrics?

**Comment by ilyam8** [comment]
No, I have no. I used a Redis docker container on my VM 

```bash
# single
docker run -d --name some-redis -p 6379:6379 redis

# master/slave
docker run -d --name redis-master --network=host redis
docker run -d --name redis-slave0 --network=host redis --port 6380

docker exec -it redis-slave0 bash
redis-cli -p 6380
SLAVEOF 127.0.0.1 6379
```

You can start it and check.

**Comment by ilyam8** [comment]
> use keyspace_misses directly as a metric to alert on

- we don't collect keyspace_misses.
- if we do we can't really use (assuming collecting as-is (failed lookups), not percentage) - can you explain how? 

> misses * 100 / (misses + hits)

This would be the current value, I think we want an average over time.

**Comment by shyamvalsan** [comment]
Found this in DD [documentation ](https://www.datadoghq.com/blog/how-to-monitor-redis-performance-metrics/#metric-to-alert-on-keyspace_misses) but not sure if there's a way we can figure out whether Redis is being used as a cache or not. 

> A consistently nonzero value for this metric means that clients are attempting to find keys in your database which do not exist. If you are not using Redis as a cache, keyspace_misses should be at or near zero. Note that any blocking operation (BLPOP, BRPOP, and BRPOPLPUSH) called on an empty key will result in the keyspace_misses being incremented
