### ISSUE TITLE
[Feat]: Pass auto accept to package managers when using --non-interactive

### ISSUE THREAD

**Issue by MrZammler** [netdata/netdata#13693]
### Problem

This was requested by a user on discord. Assuming kickstart runs as root, could we extend when running kickstart with `--non-interactive` to pass similar flags (e.g. `-y` to to `apt-get`) to package managers to bypass install questions from them?

### Description

If kickstart is run as root, then when using `--non-interactive` it should also try to auto accept any package manager requests.

### Importance

nice to have

### Value proposition

1. Better automated installations

**Comment by Ferroin** [comment]
We currently do all of the following when running non-interactively, irrespective of running as root or not:

- Add `-n` to any invocations of `sudo` or `doas`, to make them throw an error if they would prompt.
- Add `-y` to any package manager invocations, to auto-accept any questions they would ask.
- Set `DEBIAN_FRONTEND=noninteractive`, to force debconf on Debian/Ubuntu systems to behave correctly and not prompt.
- Add appropriate options to any of our own scripts that we invoke to tell them to run non-interactively.

If we’re seeing things halting at any point during a non-interactive install at this point, then that’s a bug (albeit possibly an upstream bug, as is the case with handling of repository signing keys by Yum/DNF in some situations).

**Comment by zyxep** [comment]
ahh thx for clarifying this.

**Comment by MrZammler** [comment]
Didn't check to be honest (sorry), I should have, thanks @Ferroin !

**Comment by Ferroin** [comment]
@MrZammler It’s OK, despite being the person who wrote the code _I_ actually had to search through it to double check all of this myself.
