### ISSUE TITLE
[Feat]: Claiming should send some stats

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#13705]
### Description

During issue investigations we noticed we dont have data on agent/os version during claiming (for agents that never connect to cloud post claiming)

### Importance

must have

### Value proposition

1. as above it would be very useful in cases agent claim but never connect to diagnose what might be the issue
2.
3.
...

### Proposed implementation

- send more info in claiming process (at minimum agent version, more we can send better: os info, buildinfo (to be groomed))
- respect DO_NOT_TRACK

**Comment by ilyam8** [comment]
@underhood, hey 🙋 Is it only "agent/os version" or is the request ~~is WIP~~ will be updated later. Asking because "Proposed implementation" is to send _some_.

**Comment by underhood** [comment]
I see: reword would be send at least agent version and os version if possible, if we can send more... great

**Comment by Ferroin** [comment]
Already brought this up in Slack, but mentioning it here so it’s publicly visible:

Providing any stats at all will be much easier if we finally migrate the claiming code into the agent itself as I’ve suggested in https://github.com/netdata/netdata/discussions/12179, and IMO supporting sending arbitrary stats on claim that we already send as part of the regular anonymous statistics messages is another compelling reason to migrate the claiming code into the agent itself.

**Comment by underhood** [comment]
@Ferroin I agree with you about this topic. Ideally claiming is performed by agent not by external script.

**Comment by underhood** [comment]
For the record I am waiting with this mainly for the reason of planned claiming redesign.
When we do that "new claiming" I plan to do it internally from within the agent. Therefore I consider implementing this in current claim script wasted work.
