### ISSUE TITLE
[Feat]: Create a collector for Cassandra

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13700]
### Problem

Netdata does not currently monitor Cassandra metrics

### Description

Create a new collector for Cassandra

The following metrics should be collected and organized in the charts as per structure shown below:

- **Throughput** (available via JMX, Jconsole)
  - **Reads** (Read requests/second)
  - **Writes** (Write requests/second)
- **Latency** (available via nodetool, JMX, Jconsole)
  - Read latency (Read response time in microseconds)
  - Write latency (Write response time in microseconds)
- **Cache** (available via nodetool, JMX, Jconsole)
  - **Key cache hit rate** (Percentage of read requests for which key location was found in cache)
- **Disk usage** (available via nodetool, JMX, Jconsole)
  - **Load** (Disk space used on a node in bytes)
  - **Total disk space used** (Disk space used by column family, in btyes)
  - **Compaction tasks completed** (Total count of completed compaction tasks)
  - **Compaction tasks in queue** (Total count of pending compaction tasks in queue)
- **Garbage collection** (available via nodetool, JMX, Jconsole)
  - **ParNew count** (Number of young-generation collection)
  - **ParNew time** (Elpased time of young-generation collection in milliseconds)
  - **ConcurrentMarkSweep count** (Number of old-generation collection)
  - **ConcurrentMarkSweep time** (Elapsed time of old-generation collection in milliseconds)
- **Errors** (available via JMX, Jconsole)
  - **Exceptions** (Requests for which Cassandra encountered an error)
  - **Timeout exceptions** (Requests not unacknowledged within timeout window)
  - **Unavailable exceptions** (Requests for which required number of nodes was unavailable)
  - **Pending tasks** (Tasks in queue awaiting a thread for processing)
  - **Blocked tasks** (Tasks that have not yet ben queued for processing)

### Importance

must have

### Value proposition

1. Enable Cassandra users to rely on Netdata for their monitoring and troubleshooting needs.
2. More users and connected nodes for Netdata

### Proposed implementation

Some useful links: 

- [Cassandra stress testing tool](https://docs.datastax.com/en/cassandra-oss/3.x/cassandra/tools/toolsCStress.html)
- [Cassandra monitoring best practises](https://www.instaclustr.com/blog/cassandra-monitoring-best-practice-guide/)
- [Cassandra monitoring](https://cassandra.apache.org/doc/latest/cassandra/operating/metrics.html)

**Comment by ilyam8** [comment]
> we will use [prometheus/client_golang](https://github.com/prometheus/client_golang) (ping @ilyam8 ).

Why?

**Comment by thiagoftsm** [comment]
> Why? Can you explain why we need it? go.d.plugin has some collectors that parse prometheus format metrics. Why not use the same method?

@ilyam8 ,

We cannot collect [JMX](https://en.wikipedia.org/wiki/Java_Management_Extensions) directly, so we need a software that can expose the data for us. 

About `jmx_exporter`, I had a talk with our user, and this is one of the most used tool to expose metrics from `Apache` tools, so users are already have it installed. This will simplify users life.

I am thinking that instead a module exclusively for each one of the tools (Kafka, Cassandra, Zookeeper), probably it will be better to have a collector for `jmx` and inside this module we would have options to set what plugin will monitor. :thinking:

**Comment by ilyam8** [comment]
@thiagoftsm thanks for the explanation, but my question is not about JMX.

**Comment by thiagoftsm** [comment]
> @thiagoftsm thanks for the explanation, but my question is not about JMX.

All right, let me be more clear, because I was not with last comment. We expect something like this:

- Users will have an apache tool (Zookeeper/Kafka/Cassandra).
- Together these tools they will install the `jmx_exporter` that will expose metrics in `Prometheus` format.
- We will use `prometheus/client_golang` to access the endpoint and parse data for us.

This is the simplest road that I verified yesterday to have the data we need. I hope now it is more clear what I was trying to expose.

**Comment by ilyam8** [comment]
Ah, I see, it is not clear what I was asking about. The question was about the [quoted sentence](https://github.com/netdata/netdata/issues/13700#issuecomment-1255137049).

**Comment by thiagoftsm** [comment]
> Ah, I see, it is not clear what I was asking about. The question was about the [quoted sentence](https://github.com/netdata/netdata/issues/13700#issuecomment-1255137049).

ok, I will see the modules that are parsing these prometheus metrics. Remember I was 20 months without to touch `go.d.plugin`, so I completely forgot that we had this library. :(

**Comment by ilyam8** [comment]
Thanks. If this won't be a problem for you, please share Cassandra's metrics (jmx exporter) sample here.

**Comment by thiagoftsm** [comment]
@ilyam8 and @shyamvalsan studying Cassandra I found this [link](https://cassandra.apache.org/doc/latest/cassandra/operating/metrics.html) with some metrics it has.

**Comment by thiagoftsm** [comment]
I finally configured everything necessary to proceed, so I am sharing the configuration used with `jmx_exporter` and the metrics that I got:

| Software | Configuration | Metrics |
|--------------|-------------------|-----------|
|Cassandra | [cassandra_cfg.txt](https://github.com/netdata/netdata/files/9629703/cassandra_cfg.txt) | [cassandra.txt](https://github.com/netdata/netdata/files/9629706/cassandra.txt) | 
| Kafka | [kafka_cfg.txt](https://github.com/netdata/netdata/files/9629707/kafka_cfg.txt) | [kafka.txt](https://github.com/netdata/netdata/files/9629711/kafka.txt) |

**Comment by sashwathn** [comment]
@thiagoftsm : I am putting a quick comment based on our discussion right now.
The "Read Latency" and "Write Latency" metrics will need to be grouped by the "Keyspace" and "Scope" labels and we should also look at other metrics that need these or other labels.

Please add any other findings from your side into this issue.

**Comment by ilyam8** [comment]
@shyamvalsan @thiagoftsm I added some adjustments, you can check the latest version and add changes if needed.

**Comment by shyamvalsan** [comment]
Looks better @ilyam8 

can we rename:

- jvm gc --> garbage collection
- cassandra --> Cassandra

The compaction charts looks a bit confusing to me. Why are there multiple charts for pending compactions?

**Comment by thiagoftsm** [comment]
Hello @shyamvalsan ,

Two of the charts you wrote in the issue (task completed, task queued), the third has relationship with bytes compacted.

Best regards!

**Comment by ilyam8** [comment]
> can we rename:
> cassandra --> Cassandra

Can you clarify this? 🤔 

> jvm gc --> garbage collection

There are [more JVM metrics](https://cassandra.apache.org/doc/latest/cassandra/operating/metrics.html#jvm-metrics) (which can be added later). All of them are JVM runtime metrics. Do you still think that removing `jvm ` is a good idea?

**Comment by shyamvalsan** [comment]
@ilyam8 in that case if it really does stand out so much - the preferred option is to go with JVM runtime.

**Comment by ilyam8** [comment]
How it looks

<img width="218" alt="Screenshot 2022-10-18 at 20 39 48" src="https://user-images.githubusercontent.com/22274335/196504770-c1c3d337-cecb-4467-9a6f-85607ceeaf3a.png">

**Comment by shyamvalsan** [comment]
@ilyam8 I don't think that's too bad - doesn't look out of place to me.
