### ISSUE TITLE
[Bug]: Can't stop or restart netdata on WSL (no systemd)

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13714]
### Bug description

I was wondering why netdata wouldn't read an updated netdata.conf, until I realized that `service netdata restart` didn't actually restart it. In fact, `service netdata stop` doesn't work at all. I had to manually `killall` and run `service netdata start` again.

### Expected behavior

Proper netdata service implementation on WSL

### Steps to reproduce

1. Install netdata on WSL (we're working on a nice guide right now) 
2. Start it with the `service` command and try stopping/restarting it.

### Installation method

kickstart.sh

### System info

```shell
Linux DESKTOP-C7OKV71 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.36.0-141-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by Ferroin** [comment]
My gut instinct here is that this is not a Netdata bug, but an issue with WSL itself.

In fact, I’m not even sure why `service netdata start` works on WSL. They’re likely doing some hacky thing themselves to handle this without involving systemd.

**Comment by cakrit** [comment]
I shared our draft instructions with you @Ferroin , you can try it to see what you can make of it.

**Comment by Ferroin** [comment]
Indeed. It will probably take a while though, as the only Windows system I have readily available is part of a dual-boot setup on my laptop and I _really_ don’t do any development work there. Looks like it’s about time for me to finally try setting up a Windows 11 VM on my home server...

**Comment by cakrit** [comment]
We will actually need a windows server for a demo environment. I'll want to put on it IIS and SQL server too at some point. I'll see the best way to get one and give you access.

**Comment by Ferroin** [comment]
After some further digging, AFAICT, this is indeed an issue with WSL itself. The fact that `service start netdata` happens to work is almost certainly coincidental, as the `service` command should not (based on what I can tell from code inspection) work at all on WSL.

Note that this is also part of a more general issue, namely that ‘services’ in WSL are _not_ Windows services, and (should) get terminated when the WSL session closes. This makes it _very_ difficult for us to actually properly support WSL as anything but a demo environment, because there’s no good way to automate startup of the agent on system startup (and we cannot cleanly implement such a mechanism either, because of a huge number of limitations inherent in how WSL is designed).

**Comment by cakrit** [comment]
There is the option of demanding a [WSL2 version that supports systemd](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/) but I'm afraid that it won't be available on the majority of Windows Server OSs out there (they say in the linked page that you need windows 11 or newer etc. 

Let's dig a bit more on what's possible with WSL. I can't accept that there's no way to automatically start a process on a Linux system. It may not be an orthodox way, but I'm sure we'll find a solution.

**Comment by cakrit** [comment]
[This](https://www.how2shout.com/linux/how-to-start-wsl-services-automatically-on-ubuntu-with-windows-10-startup/) worked on my Windows 11

**Comment by Ferroin** [comment]
The issue is not that there’s no way to do it.

The problem is that there is no _clean_ (that is, guaranteed to work in an idempotent manner and not cause problems for users) way for us to automatically do it.

IOW, we can support this, but the user will have to do some extra steps themselves to make it work properly.

**Comment by cakrit** [comment]
WRT to the `service` command working/not working, I did some debugging and the only reason it didn't work perfectly was that /var/run/netdata did not exist as a directory, so /var/run/netdata/netdata.pid couldn't be created and therefore it couldn't be stopped. It started working after I manually created the directory. 

I don't know where/how we create /var/run/netdata. I see that  `/var/run` is a symlink to `/run` no idea if that is common.

**Comment by cakrit** [comment]
Ah, regarding the `clean` way, don't worry about it for now, let's at least find something that works. It's ok to have an extra couple of steps for now. Perhaps in the future we'll create a windows installer to do this, maybe a user will help us improve the process.

**Comment by Ferroin** [comment]
> WRT to the `service` command working/not working, I did some debugging and the only reason it didn't work perfectly was that /var/run/netdata did not exist as a directory, so /var/run/netdata/netdata.pid couldn't be created and therefore it couldn't be stopped. It started working after I manually created the directory.

Same results here.

> I don't know where/how we create /var/run/netdata.

It’s supposed to be created as part of the service startup. See https://github.com/netdata/netdata/blob/master/system/netdata.service.in#L18 for where it’s done with systemd services.

> I see that `/var/run` is a symlink to `/run` no idea if that is common.

That’s standard on Linux, and we should actually already be using `/run` instead of `/var/run` in most cases on Linux systems.

**Comment by cakrit** [comment]
Perhaps when you run kickstart for the first time on the windows server we'll have tomorrow, do it in debug mode and search for a failure in creating the directory. Very strange...

**Comment by Dim-P** [comment]
FWIW, I am using https://github.com/arkane-systems/genie . It's not perfect or ideal, but it's an option.

**Comment by Ferroin** [comment]
OK, I’ve figured out at least part of the issue: something is going wrong in our service install code, though I’m not certain what.

We’re going to at minimum need https://github.com/netdata/netdata/pull/13451 merged before I can actually fix this properly. AFAIK there’s only one outstanding issue before that can be merged, and I’m working right now on figuring that out.

**Comment by shyamvalsan** [comment]
Hey @Ferroin now that https://github.com/netdata/netdata/pull/13451 is merged, do we have a way forward here?

**Comment by Ferroin** [comment]
@shyamvalsan Currently, #13451 being merged means we’re refusing to install any service on WSL unless the user does so manually. In the short term:

- You can manually install what was getting installed before #13451 got merged by running `/usr/libexec/netdata/install-service.sh --type initd` after running the installer. This does not appear to work _exactly_ like it used to, but AFAICT it does mostly work. I plan to add handling to just do this automatically as part of #13774, though I have not added it there yet.
- #13774 will also add explicit autodetection support for Systemd in WSL setups.
- Assuming I can fix the current issues in #13774, I plan to have it merged in time for the upcoming v1.37.0 release of the agent.

I’m still trying to figure out _why_ things were working at all in WSL prior to the #13451 merge, because AFAICT they should not have worked at all, let alone in the way @cakrit was describing, but I have no ETA on that.

**Comment by cakrit** [comment]
Just to clarify, this is our major blocker for Windows Support. It will be amazing if we can have a working installation with the default kickstart command in 1.37.0. I'll do my best to put together an msi installer in paraller.

**Comment by Ferroin** [comment]
@cakrit Assuming #13774 gets merged in time for the release as is the current plan, we should have at least equivalent behavior to what we did prior to #13451 being merged, plus working support for systemd in WSL. It _might_ also resolve this issue (in traditional WSL setups, it will correctly prefer the LSB-style init script over the plain init.d style script we were previously installing, and I _think_ that should make things just work), but I have not had a chance to test that yet.

**Comment by Ferroin** [comment]
Just merged #13774. Based on testing of that, I _believe_ this issue is resolved, at least in some cases. At minimum, our WSL support should overall be better now than it was when this issue was opened, though there is still lots of room for improvement.

**Comment by cakrit** [comment]
Plz check tomorrow if it works properly on our windows server and if it does, close this issue. Thanks @Ferroin !

**Comment by Ferroin** [comment]
OK, this is a bit more complicated than I originally expected, and the `service` command is actually buggy.

The ‘quick’ workaround for non-systemd WSL setups is to just use the static build instead of native packages.

The more ‘correct’ workaround, that lets you continue using native packages, is to:

- Manually run (as root) `/usr/libexec/netdata/install-service.sh` after running the kickstart script (this will end up installing the _correct_ init script, but we can’t do this automatically because it will break things WRT the package manager if systemd is being used in WSL).
- Instead of using `service` to start and stop Netdata, directly invoke `/etc/init.d/netdata start` and `/etc/init.d/netdata stop`.

**Comment by cakrit** [comment]
Why can't we check if `systemd` is being used and run it automatically if it's not? It's extremely rare for systemd to be used anyway, you need a special version of WSL AFAIK. See the link below, we can do checks specific to WSL only to ensure we're doing the right thing:

https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/#how-can-you-get-systemd-on-your-machine


Using `/etc/init.d/netdata start/stop` is fine. Is there any way to guarantee that users will get an error if they use the `service` command?

**Comment by Ferroin** [comment]
> Why can't we check if `systemd` is being used and run it automatically if it's not? It's extremely rare for systemd to be used anyway, you need a special version of WSL AFAIK.

It’s more common than you might think, and it’s been possible for quite some time. MS finally adding official support has been in response to people complaining about needing third-party software to do it.

Actual usage is likely to increase as this moves from being functionally an open beta to being mature software, as a rather irritating number of things depend on systemd these days.

And detecting systemd reliably is actually rather complicated...

> See the link below, we can do checks specific to WSL only to ensure we're doing the right thing:
> 
> https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/#how-can-you-get-systemd-on-your-machine

That only works if using the official MS support. As mentioned above, there have been other ways to do this for quite some time now.
 
> Using `/etc/init.d/netdata start/stop` is fine. Is there any way to guarantee that users will get an error if they use the `service` command?

No, there is not. However, starting Netdata with the `service` command will not prevent it from being stopped by manually invoking the init script (when it’s actually doing the right thing, `service` is just calling the init script, it simply exists to provide a distro-agnostic way to do that).

**Comment by cakrit** [comment]
Ok, how about we focus on getting the steps right for our msi installer:
- The installer by default expects that there's no WSL and it will install the image that is built the way we want it.
- If the msi detects that a WSL distribution is already installed, it aborts and points the user to a page with more info on what they should do 

I just have no idea what they could possibly do then. I don't think we'll have a solution for someone to deploy en masse if they already use WSL, which is weird, because that should be easier than installing WSL with netdata.

**Comment by dfpr** [comment]
> Ok, how about we focus on getting the steps right for our msi installer:
> 
> * The installer by default expects that there's no WSL and it will install the image that is built the way we want it.
> * If the msi detects that a WSL distribution is already installed, it aborts and points the user to a page with more info on what they should do
> 
> I just have no idea what they could possibly do then. I don't think we'll have a solution for someone to deploy en masse if they already use WSL, which is weird, because that should be easier than installing WSL with netdata.

I am aiming to have the installer detect WSL as a Windows feature so will install it if not already installed or go to the next nextdata installation step if installed.

**Comment by cakrit** [comment]
@dfpr try the steps @Ferroin mentioned, manually running as root `/usr/libexec/netdata/install-service.sh` and then use the `/etc/init.d` commands directly. Haven't done it myself yet.

**Comment by Ferroin** [comment]
@cakrit Regarding the case of an existing WSL distro, that’s a non-issue. We just install our own alongside it and everything is fine. Each distro is it’s own container (irrespective of WSL1 versus WSL2).

**Comment by cakrit** [comment]
Closing this as https://github.com/netdata/netdata/issues/13933 is much more important.

**Comment by jhgorse** [comment]
> > Using `/etc/init.d/netdata start/stop` is fine. Is there any way to guarantee that users will get an error if they use the `service` command?
> 
> No, there is not. However, starting Netdata with the `service` command will not prevent it from being stopped by manually invoking the init script (when it’s actually doing the right thing, `service` is just calling the init script, it simply exists to provide a distro-agnostic way to do that).

For either called or forked processes from bash scripts, which `service` appears to be, there appear to be methods to detect the caller.
https://stackoverflow.com/questions/20572934/get-the-name-of-the-caller-script-in-bash-script
`PARENT_COMMAND=$(ps -o comm= $PPID)`
Replace comm= with args= to get the full command line (command + arguments). The = alone is used to suppress the headers.
Ref: http://pubs.opengroup.org/onlinepubs/009604499/utilities/ps.html

and https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html#index-caller

Cheers
