### ISSUE TITLE
[Bug]: Error fetching charts due to invalid encoded chart IDs

### ISSUE THREAD

**Issue by juacker** [netdata/netdata#13722]
### Bug description

We've detected, for some specific node IDs, that the cloud is returning a 500 error on the single node charts endpoint:

> "/api/v2/nodes/{nodeID}/charts?after=-900&before=0"

The problem is that the cloud cannot decode the response received from the agent.

When the cloud requests charts to the agent through `/api/v1/charts`, we're receiving these kind of `charts` entries:

```json
"charts" : {
	"wmi_EXCHANGE.logical_disk_C:\ExchangeData_utilization": {
			"id": "wmi_EXCHANGE.logical_disk_C:\ExchangeData_utilization",
			"name": "wmi_EXCHANGE.logical_disk_C__ExchangeData_utilization",
			"type": "wmi_EXCHANGE",
			"family": "disk",
			"context": "wmi.logical_disk_utilization",
			"title": "Utilization Disk C:/ExchangeData (wmi_EXCHANGE.logical_disk_C__ExchangeData_utilization)"                   
	  
	}
}
```

The chart ID field is not properly encoded (`\E` part ), so when the cloud tries to decode the response it fails with:

 > "direct node charts: node instance charts: invalid character 'E' in string escape code"

(playground: https://go.dev/play/p/rxJsfpAttlu)

We have detected this error on a single agent atm, the version of this agent is the latest nightly: 

```json
	"version": "v1.36.0-147-nightly"
```

### Expected behavior

Return node charts

### Steps to reproduce

1.

### Desktop

Browser Version [e.g. 22]

**Comment by juacker** [comment]
Currently, the cloud is returning a _500 status - Internal Server Error message_ if the agent response cannot be decoded. I'm wondering if we should return a different status code and/or a more descriptive error message to the user if this happens.

@papazach, @ralphm what do you think about it?

**Comment by ralphm** [comment]
I assume the Agent side of this, is that JSON is created by concatenation, causing the backslash to not be escaped.

On the Cloud side, unfortunately I see no way to somehow parse this more liberally, so we can't do much but reject the response. 

We should not have any `500` response codes. For this particular case, I think we should reply with a `502 Bad Gateway`. [Per the RFC](https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.3):

> The 502 (Bad Gateway) status code indicates that the server, while acting as a gateway or proxy, received an invalid response from an inbound server it accessed while attempting to fulfill the request.

Additionally, the response should have a payload that details what's going on. Either with a specific reason / semantic identifier or an opaque identifier that we can identify. The latter might be shown in the UI providing a way to let us know. In any case any user should be able to inspect in the browser's console log and while looking at the underlying HTTP protocol responses.

If the response to the browser is a compound of multiple Agent requests, the response should just be a 200 with a payload to represent the result from the other, valid responses, while listing the erroneous respons(es) with similar detailing with an application specific error code.

**Comment by juacker** [comment]
Thanks for your comment @ralphm, looking at the RFC description for the `502 Bad Gateway` I fully agree that this is the correct response code to return, we will update our service accordingly.

**Comment by MrZammler** [comment]
@ilyam8 Do you think this should be handled on the wmi module, or in the agent... ?

**Comment by ilyam8** [comment]
both?

**Comment by juacker** [comment]
A small update on this issue. We've detected a new case for errors unmarshaling agent's charts responses. In this case the problematic field is not the `charts` field, but the `hostname` field, as some users have the `"` character on their host names:

![Captura desde 2023-02-15 12-45-37](https://user-images.githubusercontent.com/2930882/219019488-6a3fd78e-07c4-4118-aafe-509dbde60dfa.png)
