### ISSUE TITLE
[Bug]: can't monitor haproxy 2.4.18

### ISSUE THREAD

**Issue by ced1check** [netdata/netdata#13723]
### Bug description

I've followed those 2 guides:
https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/haproxy
https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/haproxy

The later mentions using socket, but no matter what I do in debugging the issue it never uses the socket parameter.

The first uses an http URL which I've configured in haproxy and reports stats using curl, however the module keeps failing to decrypt the data.

### Expected behavior

I expect the haproxy plugin to monitor the data as documented.

### Steps to reproduce

1. Install haproxy
2. debug plugin as per documentation

### Screenshots

Here is the stats output using CSV mode (partial only):

```
ubuntu@ovh1:/usr/libexec/netdata/plugins.d$ curl 'http://127.0.0.1:8404/metrics;csv;norefresh'
# pxname,svname,qcur,qmax,scur,smax,slim,stot,bin,bout,dreq,dresp,ereq,econ,eresp,wretr,wredis,status,weight,act,bck,chkfail,chkdown,lastchg,downtime,qlimit,pid,iid,sid,throttle,lbtot,tracked,type,rate,rate_lim,rate_max,check_status,check_code,check_duration,hrsp_1xx,hrsp_2xx,hrsp_3xx,hrsp_4xx,hrsp_5xx,hrsp_other,hanafail,req_rate,req_rate_max,req_tot,cli_abrt,srv_abrt,comp_in,comp_out,comp_byp,comp_rsp,lastsess,last_chk,last_agt,qtime,ctime,rtime,ttime,agent_status,agent_code,agent_duration,check_desc,agent_desc,check_rise,check_fall,check_health,agent_rise,agent_fall,agent_health,addr,cookie,mode,algo,conn_rate,conn_rate_max,conn_tot,intercepted,dcon,dses,wrew,connect,reuse,cache_lookups,cache_hits,srv_icur,src_ilim,qtime_max,ctime_max,rtime_max,ttime_max,eint,idle_conn_cur,safe_conn_cur,used_conn_cur,need_conn_est,uweight,agg_server_check_status,-,ssl_sess,ssl_reused_sess,ssl_failed_handshake,h2_headers_rcvd,h2_data_rcvd,h2_settings_rcvd,h2_rst_stream_rcvd,h2_goaway_rcvd,h2_detected_conn_protocol_errors,h2_detected_strm_protocol_errors,h2_rst_stream_resp,h2_goaway_resp,h2_open_connections,h2_backend_open_streams,h2_total_connections,h2_backend_total_streams,
stats,FRONTEND,,,1,4,20000,12,1280,405388,0,0,0,,,,,OPEN,,,,,,,,,1,2,0,,,,0,1,0,1,,,,0,11,0,0,0,0,,1,1,12,,,0,0,0,0,,,,,,,,,,,,,,,,,,,,,http,,1,1,12,12,0,0,0,,,0,0,,,,,,,0,,,,,,,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
```

### Error Logs

This is the run when using documented csv parameters:

```
netdata@ovh1:/usr/libexec/netdata/plugins.d$ ./go.d.plugin -d -m haproxy
[ DEBUG ] main[main] main.go:113 plugin: name=go.d, version=v0.35.0
[ DEBUG ] main[main] main.go:115 current user: name=netdata, uid=119
[ INFO  ] main[main] agent.go:108 instance is started
[ INFO  ] main[main] setup.go:42 loading config file
[ INFO  ] main[main] setup.go:50 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:57 found '/usr/lib/netdata/conf.d/go.d.conf
[ INFO  ] main[main] setup.go:64 config successfully loaded
[ INFO  ] main[main] agent.go:112 using config: enabled 'true', default_run 'true', max_procs '0'
[ INFO  ] main[main] setup.go:69 loading modules
[ INFO  ] main[main] setup.go:88 enabled/registered modules: 1/70
[ INFO  ] main[main] setup.go:93 building discovery config
[ INFO  ] main[main] setup.go:123 looking for 'haproxy.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:139 found '/etc/netdata/go.d/haproxy.conf
[ INFO  ] main[main] setup.go:144 dummy/read/watch paths: 0/1/0
[ INFO  ] discovery[manager] manager.go:92 registered discoverers: [file discovery: [file reader]]
[ INFO  ] discovery[manager] manager.go:97 instance is started
[ INFO  ] run[manager] run.go:32 instance is started
[ INFO  ] build[manager] build.go:107 instance is started
[ INFO  ] discovery[file manager] discovery.go:73 instance is started
[ INFO  ] discovery[file reader] read.go:41 instance is started
[ INFO  ] discovery[file reader] read.go:42 instance is stopped
[ DEBUG ] build[manager] build.go:154 received config group ('/etc/netdata/go.d/haproxy.conf'): 1 jobs (added: 1, removed: 0)
[ DEBUG ] build[manager] build.go:303 building haproxy[local] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/haproxy.conf autodetection_retry:0 module:haproxy name:local priority:70000 update_every:1 url:http://127.0.0.1:8404/metrics;csv;norefresh]
[ ERROR ] haproxy[local] haproxy.go:80 unsupported character in float
[ ERROR ] haproxy[local] job.go:170 check failed
[ DEBUG ] run[manager] run.go:43 tick 0
^C[ INFO  ] main[main] agent.go:193 received interrupt signal (2). Terminating...
```

This is the output of the debug when using basic URL without CSV parameter:

```
netdata@ovh1:/usr/libexec/netdata/plugins.d$ ./go.d.plugin -d -m haproxy
[ DEBUG ] main[main] main.go:113 plugin: name=go.d, version=v0.35.0
[ DEBUG ] main[main] main.go:115 current user: name=netdata, uid=119
[ INFO  ] main[main] agent.go:108 instance is started
[ INFO  ] main[main] setup.go:42 loading config file
[ INFO  ] main[main] setup.go:50 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:57 found '/usr/lib/netdata/conf.d/go.d.conf
[ INFO  ] main[main] setup.go:64 config successfully loaded
[ INFO  ] main[main] agent.go:112 using config: enabled 'true', default_run 'true', max_procs '0'
[ INFO  ] main[main] setup.go:69 loading modules
[ INFO  ] main[main] setup.go:88 enabled/registered modules: 1/70
[ INFO  ] main[main] setup.go:93 building discovery config
[ INFO  ] main[main] setup.go:123 looking for 'haproxy.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:139 found '/etc/netdata/go.d/haproxy.conf
[ INFO  ] main[main] setup.go:144 dummy/read/watch paths: 0/1/0
[ INFO  ] discovery[manager] manager.go:92 registered discoverers: [file discovery: [file reader]]
[ INFO  ] discovery[manager] manager.go:97 instance is started
[ INFO  ] run[manager] run.go:32 instance is started
[ INFO  ] build[manager] build.go:107 instance is started
[ INFO  ] discovery[file manager] discovery.go:73 instance is started
[ INFO  ] discovery[file reader] read.go:41 instance is started
[ INFO  ] discovery[file reader] read.go:42 instance is stopped
[ DEBUG ] build[manager] build.go:154 received config group ('/etc/netdata/go.d/haproxy.conf'): 1 jobs (added: 1, removed: 0)
[ DEBUG ] build[manager] build.go:303 building haproxy[local] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/haproxy.conf autodetection_retry:0 module:haproxy name:local priority:70000 update_every:1 url:http://127.0.0.1:8404/metrics]
[ ERROR ] haproxy[local] haproxy.go:80 "INVALID" is not a valid start token
[ ERROR ] haproxy[local] job.go:170 check failed
[ DEBUG ] run[manager] run.go:43 tick 0
[ DEBUG ] run[manager] run.go:43 tick 1
^C[ INFO  ] main[main] agent.go:193 received interrupt signal (2). Terminating...
```

### Desktop

Browser Version [e.g. 22]

**Comment by Dim-P** [comment]
Hi @ced1check , thanks for reporting this issue and sorry for the delay in getting back to you.

I just tested this and it seems to be working find on my setup (you shouldn't need to change the mode to `CSV`, in fact, you shouldn't have to change the default configuration unless you are using a different port to expose the `/metrics` on). 

Let's try to find what's wrong. Can you please confirm the following for me:

1. Did you follow the instructions documented in [HAProxy Exposes a Prometheus Metrics Endpoint](https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/), about how to compile HAProxy with support for Prometheus exporter? More specifically this part:

```
sudo apt update
sudo apt install -y git ca-certificates gcc libc6-dev liblua5.3-dev libpcre3-dev libssl-dev libsystemd-dev make wget zlib1g-dev
git clone https://github.com/haproxy/haproxy.git
cd haproxy
make TARGET=linux-glibc USE_LUA=1 USE_OPENSSL=1 USE_PCRE=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1
sudo make install-bin
```

and then if necessary:
```
sudo systemctl stop haproxy
sudo cp /usr/local/sbin/haproxy /usr/sbin/haproxy
sudo systemctl start haproxy
```

2. Do you have a section like the following in your `haproxy.cfg` to expose the metrics (I guess you _do_ have that, based on the fact that you are getting a response when doing a `curl`) ?

```
frontend stats
   bind *:8404
   option http-use-htx
   http-request use-service prometheus-exporter if { path /metrics }
   stats enable
   stats uri /stats
   stats refresh 10s
```

4. Have you added any `backend` sections in your `haproxy.cfg` ? Can you please share the entire `haproxy.cfg` ? Feel free to redact any private information.

5. Finally, can you please share the output of both `haproxy -vv` and `netdata -W buildinfo` ?

**Comment by ced1check** [comment]
@Dim-P thanks for getting back to me on this.

I've not compiled anything for HAProxy, only installed the latest ubuntu version.

It appears to work on one of our server, while it fails like described on the other. I checked the various configuration for haproxy and netdata but couldn't find any differences.

On the server it now works I've tried many different options/settings, with no results whatsoever. However a few days later, it was working, eg haproxy metrics where listed on netdata cloud!?

This is what I have on both servers haproxy.cfg:

```
frontend stats
        bind localhost:8404
        stats enable
        stats uri /metrics
```

Running haproxy 2.4.18-0ubuntu1 2022/08/25

Running curl http://127.0.0.1:8404/metrics, returns similar output as expected.

In python.d/haproxy.conf :

```
local:
    name: local
    socket: '/run/haproxy/admin.sock'
```

In go.d/haproxy.conf :

```
jobs:
  - name: local
    url: http://127.0.0.1:8404/metrics;csv
```

Both servers are configured with the above, restarted netdata and haproxy, but doesn't make a difference one server doesn't show the haproxy metrics.

Here are the output of both haproxy -vv and netdata -W buildinfo (identical on both servers):

[haproxy.txt](https://github.com/netdata/netdata/files/9902183/haproxy.txt)
[netdata.txt](https://github.com/netdata/netdata/files/9902184/netdata.txt)

**Comment by ced1check** [comment]
Thanks for the suggestion. It didn't work or even make any differences.

FWIW, we have 6 servers, and both haproxy and netdata are installed on all of them, in the exact same way.

On server 1 (where it works), I also did this: 
`sudo usermod -a -G haproxy netdata`

Did the same on server 6 (the one I'm trying to activate), it's not working.

Just noticed it's working on server 3 now... which I barely messed with.

Not sure what exactly is different on those 2 servers, but sure enough it works on them and all configuration files I know of are the same!?

Something weird I noticed: on server 1 it says haproxy_local.<field> while on server 3 it says haproxy.<field>.

Any other setting somewhere that could impact this feature?

**Comment by Dim-P** [comment]
` sudo usermod -a -G haproxy netdata` <- I don't think this is required.

>    on server 1 it says haproxy_local. while on server 3 it says haproxy..

In this case, it may be using the Go Prometheus collector instead of the Haproxy one. I am not sure.

>    on server 3, haproxy doesn't even have the frontend stats section in its config!?

I believe it's something you need to add to `haproxy.cfg` manually, at least I had to on my system. 

@ilyam8 Any ideas here?

**Comment by ced1check** [comment]
Server 3 has no frontend stats section and it works fine as you can see in below screenshot.

When I ran initial tests to configure server 1, I had to run the usermod command otherwise netdata was unable to open the socket. After that I couldn't get any data out of it and gave up. The next day, to my surprise, it was working!?

Server 6 reported data with prometheus config, but there is no consistency in data names. 3 servers, 3 different names for the same element as you can see in the same screenshot.

![image](https://user-images.githubusercontent.com/104206200/199770707-2f048279-46e3-4712-92a8-bc41960f3eff.png)

Why is it so complicated to make it work? Why the same configuration doesn't work on 1 server out of 3?

This is so confusing, I'll end-up reactivating prometheus config if it still doesn't work with defaults on that server.

**Comment by ced1check** [comment]
Ok, I managed to get something consistent across all 3 servers (and configured 2 others) with this:

In haproxy.cfg:

```
global
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
```

In python.d/haproxy.conf:

`socket: '/run/haproxy/admin.sock'`

It would be nice to have that plugin/module fully documented, with both python.d and go.d plugins details. I went through all kind of configuration mixes using both but nothing was working.

**Comment by Dim-P** [comment]
@ced1check Good to hear you got it sorted in the end, although I'm still not sure what was the issue. 

Just to say by taking another look at your screenshot, it seems like Server 6 uses the Prometheus Go plugin instead of the HAProxy one. We are probably going to deprecate the HAProxy plugin in the future in favour of the Prometheus one.
