### ISSUE TITLE
[Feat]: Add more WMI (windows_exporter) collectors

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13726]
### Problem

The full list of collectors is at https://github.com/prometheus-community/windows_exporter
At a minimum we should have everything related to the system + IIS and SQL server. 

### Description

- 

### Importance

must have

### Value proposition

Windows support is still lacking and we want to improve it.

**Comment by thiagoftsm** [comment]
On a default Windows 11 installation I got [these metrics](https://github.com/netdata/netdata/files/9815498/iis_metrics.txt).

**Comment by thiagoftsm** [comment]
@cakrit before I proceed with IIS and SQL Server, I will complete the list of metrics that we are missing.

**Comment by cakrit** [comment]
- First do all the system ones, starting with what we already have (if they are missing metrics).
- Leave the applications last. 
- Do one PR for each "collector" in the table https://github.com/prometheus-community/windows_exporter#collectors
- Wherever possible, organize and name metrics and charts the same way with our Linux charts. 
- Wherever possible, take existing alerts we have for Linux and apply them to the Windows charts (e.g. if cpu and mem charts/dimensions are comparable, the alert logic and limits should be the same)

**Comment by thiagoftsm** [comment]
I observed that for CPU we are not collecting these metrics:

- windows_cpu_clock_interrupts_total : Total number of received and serviced clock tick interrupts (I am not sure if we should collect this)
- windows_cpu_processor_performance: Processor Performance is the average performance of the processor while it is executing instructions, as a percentage of the nominal performance of the processor. On some processors, Processor Performance may exceed 100%.

**Comment by thiagoftsm** [comment]
About Cache, to match what eBPF plugin shows we need to collect:

- windows_cache_async_fast_reads_total : Number of reads from the file system cache that bypass the installed file system and retrieve the data directly from the cache.
- windows_cache_copy_read_hits_total: Number of copy read requests that hit the cache, that is, they did not require a disk read in order to provide access to the page in the cache.
- windows_cache_data_flushes_total: Number of times the file system cache has flushed its contents to disk as the result of a request to flush or to satisfy a write-through file write request.
- windows_cache_dirty_pages: Number of dirty pages on the system cache.
- windows_cache_copy_reads_total - Number of reads from pages of the file system cache that involve a memory copy of the data from the cache to the application's buffer.

**Comment by thiagoftsm** [comment]
We have network, but we can also offer `TCP` info:

- windows_tcp_connection_failures_total: Number of times TCP connections have made a direct transition to the CLOSED state from the SYN-SENT state or the SYN-RCVD state, plus the number of times TCP connections have made a direct transition from the SYN-RCVD state to the LISTEN state
- windows_tcp_connections_active_total: Number of times TCP connections have made a direct transition from the CLOSED state to the SYN-SENT state
- windows_tcp_connections_established: Number of TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT.
- windows_tcp_connections_passive_total: Number of times TCP connections have made a direct transition from the LISTEN state to the SYN-RCVD state
- windows_tcp_segments_retransmitted_total: Total segments retransmitted. That is, segments transmitted that contain one or more previously transmitted bytes

**Comment by thiagoftsm** [comment]
Considering the list is too big, instead to write I will give link. I am years without to configure any windows server, but I cannot imagine any situation where we should not monitor [ADFS](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.adfs.md) and [AD](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.ad.md).

**Comment by cakrit** [comment]
We should monitor the services. See systemd units and do exactly same thing. Off by default, user decides what we monitor, we create groups of services etc.

**Comment by thiagoftsm** [comment]
Windows System also has metrics that needs to be added to collector:

```sh
# HELP windows_system_context_switches_total Total number of context switches (WMI source: PerfOS_System.ContextSwitchesPersec)
# TYPE windows_system_context_switches_total counter
windows_system_context_switches_total 2.82815945e+08
# HELP windows_system_exception_dispatches_total Total number of exceptions dispatched (WMI source: PerfOS_System.ExceptionDispatchesPersec)
# TYPE windows_system_exception_dispatches_total counter
windows_system_exception_dispatches_total 309788
# HELP windows_system_processor_queue_length Length of processor queue (WMI source: PerfOS_System.ProcessorQueueLength)
# TYPE windows_system_processor_queue_length gauge
windows_system_processor_queue_length 0
# HELP windows_system_system_calls_total Total number of system calls (WMI source: PerfOS_System.SystemCallsPersec)
# TYPE windows_system_system_calls_total counter
windows_system_system_calls_total 1.307128419e+09
# HELP windows_system_system_up_time System boot time (WMI source: PerfOS_System.SystemUpTime)
# TYPE windows_system_system_up_time gauge
windows_system_system_up_time 1.6645419945e+09
# HELP windows_system_threads Current number of threads (WMI source: PerfOS_System.Threads)
# TYPE windows_system_threads gauge
windows_system_threads 1125
```

**Comment by cakrit** [comment]
Actually, I need to reopen, because having process and service monitoring disabled from the installation time is extremely problematic and unfriendly to users. We need to find a better solution.

**Comment by ilyam8** [comment]
Taking into account that having/suggesting a predefined filter for processes and services does not look possible and collecting all processes/services metrics significantly increases CPU usage is unavoidable... I can only suggest reducing data collection frequency for processes and services. I see it is possible to [whitelist collectors during scraping](https://github.com/prometheus-community/windows_exporter#filtering-enabled-collectors).

**Comment by thiagoftsm** [comment]
As I described on slack and complementing what @ilyam8 wrote, when we have they enabled, 94,6% of metrics are from `services` and `CPU`:

```sh
bash-5.2$ wc -l ~/Netdata/WMI/windows_exporter_metrics.txt 
8935 /home/thiago/Netdata/WMI/windows_exporter_metrics.txt
bash-5.2$ grep windows_service ~/Netdata/WMI/windows_exporter_metrics.txt | wc -l
5884
bash-5.2$ grep windows_process ~/Netdata/WMI/windows_exporter_metrics.txt | wc -l
2571
bash-5.2$ bc -l 
(2571 + 5884)/8935
.94627867935086737548
```

The `windows_exporter` disabled them by default.

**Comment by cakrit** [comment]
We had an internal discussion and agreed that we will have them enabled by default, with a slower polling frequency that the other metrics, plus config options to make them even slower, if needed. The user will never see thousands of dimensions on a chart, they're already grouped.

**Comment by cakrit** [comment]
Closing this, if anything new comes up, we'll see.
