### ISSUE TITLE
[Feat]: Proper Windows Support via WSL and the windows_exporter collector

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13727]
### Problem

Officially support windows in the best way we can, without a windows agent.

### Description

Our solution will be based on Windows Subsystem for Linux 2 + the WMI collector, which currently processes the output of a few `windows_exporter` collectors. 

Blockers:
- [ ] #13933
- [x] #13716
- [x] #13726 
- [x] Prepare demo room with a monitored Windows Server (cloud SRE team). (DONE - Ask @cakrit for credentials)
- [x] #13843
- [x] ~~Produce a good installation guide (we will reduce the [steps described here](https://docs.google.com/document/d/1qdZiAG341GceX2baMpHnDvAS1QF6hBtIDfjpW8FK2Bg) to the bare minimum via this ticket and then write a much shorter one).~~
- [ ] Finalize https://github.com/netdata/msi-installer
- [ ] Improve the [documentation of the collector](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi)
- [ ] Improve the installer readme
- [x] Add to release notes
- [x] https://github.com/netdata/product/issues/3041 

Future:
- [ ] #13857 

### Importance

must have

### Value proposition

Windows support is in the top 5 user-requested features.

**Comment by Ferroin** [comment]
Reposting this here from Slack, as requested (minus one point which is already being taken care of internally):

A couple of observations regarding our decision to use WSL as a way to say we support Windows (after having thought on this over the weekend):
- We will never manage to have clean service handling in WSL unless MS decides to support handling WSL services as Windows services (not especially likely given that they are pushing it for development work, not production usage).  This is compounded by how WSL handles lingering processes (namely, it kills them all). IOW, the only way to start Netdata installed in WSL is by invoking WSL itself in some way, but you then need to leave the WSL instance running somehow or Netdata will be killed. We absolutely need to document this properly.
- The system info at the top of the dashboard is misleading if run under WSL, especially if it’s WSL2. In either case, `/proc` and `/sys` do not mirror the equivalents on Windows, so you’re never going to get complete information out of either. Actually getting accurate information requires setting up the WMI collector (but even then, the top of the dashboard will be misleading). This also absolutely needs to be documented clearly.
- We need to not be calling this ‘Windows support’. The limitations here are at odds with what 99% of users expect when software is said to support Windows, with the most glaring case being the above-mentioned service handling limitation and the lack of an actual Windows installer. Many users will accept this as a reasonable compromise for the time being, but long term there will be users who insist on native support.
- While I agree that this is a sensible stop-gap, trying to go ‘all in’ on this as our ‘Windows support’ option is just trading one set of development challenges (namely, getting things working cleanly in a non-POSIX environment) for a completely different set of development challenges (namely, service handling and useful metrics presentation), and I doubt we will ever manage to get a quality of UX this way that we could with proper native support.

**Comment by cakrit** [comment]
WRT to the comment on a "clean" solution, I answered [here](https://github.com/netdata/netdata/issues/13714#issuecomment-1261195569). I also mention there that we could also provide an installer if that's needed (not hard to do with some commercial SW). 

The system info is going away, our instructions are coming with a configuration specific to WSL. i.e. with every collector except `go.d` disabled. Perhaps we'll want to enable `python.d` as well, not sure at the moment.

The last point is understood, but we don't have the ability to offer anything else in the foreseeable future and our users keep asking for a solution. An "OK-ish" solution will be better than no solution at all. We've already identified several blockers even with WSL that we can remove, to make the experience an acceptable workaround.

**Comment by cakrit** [comment]
It turns out that WSL can't be used in production systems. The installer is available, with a couple of issues pending for improvements, but it can only be used for dev purposes, so we can't consider this the official windows support. 

The next thing we'll do other than improving the windows_exporter collector is to provide a way to show Windows nodes as nodes in the cloud, regardless of where netdata itself is running. This will be a different ticket.
