### ISSUE TITLE
[Bug]:  wrong path netdata cloud.d caused node cannot connecct to Cloud

### ISSUE THREAD

**Issue by AiryXu** [netdata/netdata#13739]
### Bug description

[Bug]:  wrong path netdata cloud.d caused node cannot connecct to Cloud

### Expected behavior

[Bug]:  wrong path netdata cloud.d caused node cannot connecct to Cloud

cp -r /var/lib/netdata/cloud.d/ /opt/netdata/var/lib/netdata/

restart netdata service works well 

### Steps to reproduce

OS  CentOS 7.9

1. yum remove netdata   -y   
 
2. rm -rf  /var/lib/netdata/registry/netdata.public.unique.id  
3. rm -rf /opt/netdata/var/lib/netdata/registry/netdata.public.unique.id  

4. wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token  "MY TOKE KEYS" --claim-url https://app.netdata.cloud  --install-version 1.36.0

if install newest 1.36.1  cannot start 

5. cp -r /var/lib/netdata/cloud.d/ /opt/netdata/var/lib/netdata/
6. systemctl restart netdata  &&  systemctl status netdata

### Installation method

kickstart.sh

### System info

```shell
Linux gha 4.14.129-bbrplus #1 SMP Tue Jun 25 12:23:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
Version: netdata v1.36.1
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

[Bug]:  wrong path netdata cloud.d caused node cannot connecct to Cloud

**Comment by MrZammler** [comment]
Hi @AiryXu thanks for your report! We will try to reproduce. It appears the agent before the update was from the package manager, then switched to a static build with kickstart.

Was the agent claimed to the cloud before the update?

**Comment by MrZammler** [comment]
I tried to re-produce (alas in Centos 8), but the following: `wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token "MY TOKE KEYS" --claim-url https://app.netdata.cloud/ --install-version 1.36.1` seems to install the static build and claim the agent correctly.

Tried a local build (could not install the netdata package due to a dependency), then uninstalled and installed a static build which was claimed correctly.

Can you please post any output from the kickstart process, or any error messages on the `error.log` ?

**Comment by MrZammler** [comment]
Hi @AiryXu, any update on this? Thanks!

**Comment by MrZammler** [comment]
Most likely, it was the `--install-version 1.36.0` that caused the issue.

This requested a specific version that we did not have a package for (we have for 1.36.1 which is the latest stable), so kickstart did a static install instead.

The static install (which lives under `/opt`) will not use the cloud information under `/var/lib/netdata/cloud.d`.
