### ISSUE TITLE
[Bug]: Installer doesn't recognize CloudLinux as being natively supported

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13748]
### Bug description

This is copied from a user:

```
The installer doesn't seem to recognize CloudLinux as being natively supported, and thus falls back to building from source. CloudLinux is a 1:1 fork of CentOS just like AlmaLinux, and so the package is indeed available over yum.
To get around this, I have to manually edit the kickstart file for it to recognize CloudLinux before it continues. No harm, but I'd personally rather use the package available through yum/dnf than the source one.
```

### Expected behavior

Since it's a CentOS fork, kickstart should work with the binary packages.

### Steps to reproduce

Obvious

### Installation method

kickstart.sh

### System info

```shell
-
```

### Netdata build info

```shell
-
```

### Additional info

I will ask the user to do a PR for this, since he mentioned he changed kickstart

**Comment by Pulseeey** [comment]
This is resolved by editing line 610 of the kickstart.sh (https://my-netdata.io/kickstart.sh) script.

`            almalinux|rocky|rhel)
`

to

`            cloudlinux|almalinux|rocky|rhel)
`

**Comment by ilyam8** [comment]
Hi, @Pulseeey. Are you willing to make a PR?

**Comment by Pulseeey** [comment]
> Hi, @Pulseeey. Are you willing to make a PR?

Took me a hot minute to work out how to do that (not a big Github user), but I believe I've managed to get one created.
