### ISSUE TITLE
[Bug]: dnsmasq collector fails if any of the stats queries are not supported.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#13766]
### Bug description

Not all dnsmasq installations provide all of the cache statistics queries that the dnsmasq plugin expects. In particular, the `auth.bind` query is only supported if dnsmasq has been built to support running as an authoritative name server. This, in turn, causes our dnsmasq collector to fail, as it requires _all_ of the stats queries it makes to succeed.

### Expected behavior

The collector works even if some endpoints are not supported, providing only the data that is actually available.

### Steps to reproduce

1. Build and install a copy of dnsmasq with support for operating as an authoritative DNS server disabled.
2. Attempt to run the dnsmasq collector from the go.d.plugin against this install of dnsmasq.

### Installation method

kickstart.sh

### System info

```shell
Linux home-one 5.19.11-gentoo #282 SMP Mon Sep 26 12:59:14 EDT 2022 x86_64 AMD Ryzen 9 3950X 16-Core Processor AuthenticAMD GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.9
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:VERSION_ID="2.9"
```

### Netdata build info

```shell
Version: netdata v1.36.0-174-g2b7a964d4
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: manual-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

Based on code inspection, we do not actually appear to even _use_ the results from the `auth.bind` query. In an ideal situation we would actually provide that data as well (AIUI, it counts the number of queries for which dnsmasq is the authoritative name server), but irrespective of that we should not be _requiring_ that query to work to provide the other data.

**Comment by ilyam8** [comment]
@Ferroin thanks for the report. I decided to remove auth.bind because, as you correctly noticed, the result is unused. I make a note to add a proper fix, but I think it is a low priority.
