### ISSUE TITLE
[Feat]: clang-format action

### ISSUE THREAD

**Issue by vkalintiris** [netdata/netdata#13769]
### Problem

Currently, we don't enforce a single formatting style in the codebase. The result is that each contributor uses their own preferred style which results in mentally context-switching through multiple styles when trying to understand various parts of the agent.

This issue is about creating a (non-required) check that will run clang-format through an action on every PR. The check should fail if there are formatting violations, and succeed otherwise. A quick search lead me to https://github.com/marketplace/actions/clang-format-check which most probably covers exactly what we need.

We want to cover the entire repo except for `libnetdata/libjudy/*` and `database/sqlite/sqlite3.{c,h}`.

Once we have this action up and running, we can discuss

1. the default formatting we want to have and/or reuse the existing `.clang-format` we have in the repository's top-level directory,
2. adding local post-commit git hooks, and
3. maybe running clang-format through the entire repository to start from a clean slate.

### Description

N/A

### Importance

must have

### Value proposition

N/A.

### Proposed implementation

N/A.

**Comment by Dim-P** [comment]
Absolutely agree with this and I would also say we _do_ want it to be a "required" and not "optional" check, otherwise it won't be enforced easily before merges to master.

Clang-format could be added locally as pre/post git commit hook as you suggested or as pre/post code build action.

**Comment by vkalintiris** [comment]
> I would also say we do want it to be a "required" and not "optional" check

Oh, it will become required.. :) I just want to make sure everyone has the proper setup/support from their choice of IDE.

**Comment by Ferroin** [comment]
After a bit more digging, this is not as easy as it sounds. We also need to figure out:

- What minimum version of clang-format we are requiring. I would vote for 13, as that at least allows for slightly saner syntax for the formatting configuration.
- How we want to handle submodules. In practice, we probably need to exclude them from the format list, but doing that ‘automatically’ without using a script to do the formatting is not easy.
- Whether we still want this for things other than C code. clang-format actually handles a _lot_ of different languages.
- What the _full_ list of excludes needs to be. For example, `web/gui/dashboard` also needs to be on the exclude list, because clang-format does handle JS, and those files are handled externally to this repo.

**Comment by vkalintiris** [comment]
> After a bit more digging, this is not as easy as it sounds

Sure, that's why I want us to get going with the a non-required check, ie. setup the boilerplate, figure out the corner cases and then discuss more how we want to proceed.

> What minimum version of clang-format we are requiring. I would vote for 13, as that at least allows for slightly saner syntax for the formatting configuration.

Let's pick 13 then.

> How we want to handle submodules. In practice, we probably need to exclude them from the format list, but doing that ‘automatically’ without using a script to do the formatting is not easy.

[I don't think we need to worry about this.](https://github.com/llvm-mirror/clang/blob/aa231e4be75ac4759c236b755c57876f76e3cf05/tools/clang-format/git-clang-format#L35)

> Whether we still want this for things other than C code. clang-format actually handles a lot of different languages.

Let's start with just *.c & *.h files, and we can extend the list later on if we find the tool useful.

> What the full list of excludes needs to be. For example, web/gui/dashboard also needs to be on the exclude list, because clang-format does handle JS, and those files are handled externally to this repo.

Right.. As I mentioned, let's consider only `C` code for the time being. I believe getting all the exclusions right at this point is not that important, ie. while the test is non-required.
