### ISSUE TITLE
[Bug]: Pihole plugin not using default web header config

### ISSUE THREAD

**Issue by milindpatel63** [netdata/netdata#13768]
### Bug description

I am running the latest version of netdata agent on Ubuntu 20.04

According to "web" package docs here: https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/pkg/web

Any plugin that uses that package should inherit all it's configuration option, "Having HTTP embedded your configuration inherits all [configuration options](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/pkg/web#configuration-options)"

And I can see in line 9 here: https://github.com/netdata/go.d.plugin/blob/master/modules/pihole/pihole.go
that pihole plugin uses that same package.

So, it should support setting custom HTTP headers for pihole URL.

My pihole is hosted on external server and secured via cloudflare access/zero trust. But I can bypass that by using these two headers in every request,
CF-Access-Client-Id
CF-Access-Client-Secret

I have set them like this in my go.d/pihole.conf file

  - name: PiholeExternal
    url: https://pihole.example.com
    password: xyz
    headers:
      CF-Access-Client-Id: someid
      CF-Access-Client-Secret: somesecret
    tls_skip_verify: yes

Still netdata cant access that pihole instance.

Using troubleshoot, i can see following error,

[ ERROR ] pihole[PiholeExternal] pihole.go:114 error on parsing response from https://pihole.example.com/admin/api.php?version&auth=xyz : invalid character '<' looking for beginning of value
[ ERROR ] pihole[PiholeExternal] job.go:188 check failed

Is anyone else using similar config or has experienced similar errors?

### Expected behavior

Netdata should be able to connect to pihole

### Steps to reproduce

1. Configure pihole config with custom http headers
2. throws error on troubleshoot

### Installation method

kickstart.sh

### System info

```shell
Linux Hostname 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.5 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.5 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.36.0-178-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by milindpatel63** [comment]
As a workaround for now, i am using "cloudflared" binary to create a proxy for that external pihole in my local network on the same server on which netdata is running.

I am running a systems service like below

```
[Unit]
Description= Cloudflared Netdata Pihole
After=network-online.target
StartLimitIntervalSec=10
StartLimitBurst=5

[Service]
Type=simple
ExecStart=/usr/bin/cloudflared access tcp --hostname pihole-external-tcp.example.com --url localhost:3125 --service-token-id access-service-token --service-token-secret token-secret
Environment=RUN_BY_SYSTEMD=1
Restart=always
RestartSec=60s

[Install]
WantedBy=multi-user.target
```

Since that external pihole is protected via cloudflare access, and I want to proxy it on a local server and not have to deal with authenticating it every time, I am using "Cloudflare Service Tokens" to authenticate it.
Also, I couldn't find a way to proxy HTTP app like this, so I created another name for "pihole-external-tcp.example.com" which points to "TCP://localhost:80" on my pihole server via their cloudflare tunnel, and I can then proxy that TCP connection to my local network like above.

Hope this helps someone.

**Comment by ilyam8** [comment]
Hi, @milindpatel63. There is an indentation problem in your config

```yaml
name: PiholeExternal
url: [pihole.example.com](https://pihole.example.com/)
password: xyz
headers:
CF-Access-Client-Id: someid
CF-Access-Client-Secret: somesecret
tls_skip_verify: yes
```

=>

```yaml
name: PiholeExternal
url: 'https://pihole.example.com'
password: xyz
headers:
  CF-Access-Client-Id: someid
  CF-Access-Client-Secret: somesecret
tls_skip_verify: yes
```

**Comment by milindpatel63** [comment]
> 

that's just indented wrong while copying and pasting in github...in my config, it is like below

```
jobs:
  - name: PiholeExternal
    url: https://pihole.example.com
    password: xyz
    headers:
        CF-Access-Client-Id: someid
        CF-Access-Client-Secret: somesecret
    tls_skip_verify: yes
```

**Comment by ilyam8** [comment]
@milindpatel63 the collector uses only 'url' from [HTTP request options](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/pkg/web#configuration-options), that is a bug.

**Comment by milindpatel63** [comment]
Can confirm that this is fixed, and i can use headers in my pihole. 👍
