### ISSUE TITLE
[Feat]: Combine IP statistics in one collector

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#13777]
### Description

The statistics in `/proc/net/netstat`, `/proc/net/snmp`, and `/proc/net/snmp6` is not really meaningfully divided between these files.

### Importance

really want

### Value proposition

We need to revisit all the charts and group metrics based on their meaning, not the files they come from.

**Comment by ilyam8** [comment]
The kernel maintains [ipv4/ipv6 stats for the following counters](https://github.com/torvalds/linux/blob/master/include/net/netns/mib.h#L7-L43):
 - ip
 - udp
 - udplite
 - icmp

TCP counters are not per IP address family.

- /proc/net/netstat
  - tcp_ext
  - ip_ext (v4)
- /proc/net/snmp
  - ip (v4)
  - icmp (v4)
  - icmpmsg (v4)
  - tcp
  - udp (v4)
  - udplite (v4)
- /proc/net/snmp6
  - ip (v6)
  - icmp (v6)
  - icmpmsg (v6)
  - udp (v6)
  - udplite (v6) 

As you can see ip (v4) and tcp (v4, v6) stats split between /proc/net/netstat and /proc/net/snmp.
