### ISSUE TITLE
[Feat]: /api/v1/allmetrics should return OpenMetrics compatible Content-Type

### ISSUE THREAD

**Issue by Dentrax** [netdata/netdata#13828]
### Problem

`/api/v1/allmetrics` endpoint returns Content-Type: `text/plain; charset=utf-8` but it's not an OpenMetrics standard. Instead it should return `application/openmetrics-text; version=1.0.0; charset=utf-8`

### Description

https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#overall-structure

Content-Type should be:
```
application/openmetrics-text; version=1.0.0; charset=utf-8
```

### Importance

nice to have

### Value proposition

1. To compatible with industry standards.
2.
3.
...

cc @anilmisirlioglu

**Comment by andrewm4894** [comment]
Thanks @Dentrax for the request, I think this is really important.

**Comment by ilyam8** [comment]
`/api/v1/allmetrics` format is not really OpenMetrics and `text/plain` is ok according to [Prometheus exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format).
