### ISSUE TITLE
[Bug]: Couldn't stop the agent on macOS (already running)

### ISSUE THREAD

**Issue by Dentrax** [netdata/netdata#13829]
### Bug description

Agent does not shutdown even I run `sudo /usr/local/netdata/usr/sbin/netdatacli shutdown-agent` command several times. I couldn't understand why it doesn't shutdown. When I run second time of the following command:
```
$ sudo /usr/local/netdata/usr/sbin/netdatacli shutdown-agent
uv_pipe_connect(): connection refused
Make sure the netdata service is running.
```

It says `Make sure the netdata service is running.`. But it's already running:

```
$ curl -s localhost:19999/api/v1/allmetrics
...

$ ps auxww | grep "netdata" | wc -l
      16
```

Why it throw `uv_pipe_connect(): connection refused` error? What does it mean? Why do I get the error 'Make sure the Netdata service is running' even when netdata is already running?

### Expected behavior

It should shutdown?

### Steps to reproduce

1.
```
$ sudo /usr/local/netdata/usr/sbin/netdatacli shutdown-agent
Password:
```
2. Jump to `:19999` and see it's still working. 

### Installation method

kickstart.sh

### System info

```shell
Darwin XXX 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
ProductName:    macOS
ProductVersion: 12.3.1
BuildVersion:   21E258
```

### Netdata build info

```shell
Version: netdata v1.36.0-220-nightly
Configure options:  '--prefix=/usr/local/netdata/usr' '--sysconfdir=/usr/local/netdata/etc' '--localstatedir=/usr/local/netdata/var' '--libexecdir=/usr/local/netdata/usr/libexec' '--libdir=/usr/local/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    NO
    cgroup Network Tracking: NO
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by MrZammler** [comment]
Hi @Dentrax 

The `uv_pipe_connect()` error I think comes from the fact that `netdatacli` can not communicate with the main `netdata` binary through a file in `/tmp/netdata-ipc`.

I've seen the error before, it could be as simple as a permissions error... I'll have a look again  and will let you know. Thanks!

**Comment by wojtekxtx** [comment]
@MrZammler 

By definition, `/tmp`folder ( in many modern OSes ) stores **temporal** data, so no wonder `netdatacli` cant communicate with files in it. All files in `/tmp` folder are "transparent"

**Comment by Dim-P** [comment]
@Dentrax Just to make sure, you don't possibly have another version of Netdata installed through a different method (such as a local build) ?

**Comment by Dentrax** [comment]
> @Dentrax Just to make sure, you don't possibly have another version of Netdata installed through a different method (such as a local build) ?

Correct, it was my first attempt to install netdata using kickstart.sh script.

**Comment by Dim-P** [comment]
@Dentrax I asked one of our team members to run `sudo /usr/local/netdata/usr/sbin/netdatacli shutdown-agent` on his macOS installation and he confirmed it works as expected. Not sure what the problem is with yours. Maybe if you try a clean uninstall / reinstall?

**Comment by wojtekxtx** [comment]
@Dim-P I also have Mac ( MacBook Air in my case ) and am also experiencing this.
