### ISSUE TITLE
[Feat]: Log to seperate log files per plugin/collector

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#13823]
### Problem

Making a feature request following this discussion on discord: https://discord.com/channels/847502280503590932/1027957189245157386

Problems: 
1. The netdata log files can be quite hard to read and understand as there is just lots of stuff in one place. 
2. A lot of error messages get thrown in the normal running of things that can make it harder to distinguish between "normal" error messages and those that might actually mean something. 

Feedback from a user:

> How do I discern between real netdata agent errors and what seems to be normal behaviour of plugins in error.log? This is a little confusing to me as lots of plugins logg ERROR when they can't find something to monitor (because I don't have that particular service)

### Description

1. A way to split log messages into seperate files a bit more meaningfully
2. A way to capture normal expected errrors in some way and clearly distinguish them from unexpected or non-normal error messages. 

### Importance

nice to have

### Value proposition

1. Help users more easily and quickly debug configuration and other issues with Netdata agents.
2.
3.
...

### Proposed implementation

Suggestion from user:

> My suggestion is to split out the error.log into several files. One for the main netdata instance, then a separate error.log per plugin - perhaps even per collector if debug loggin is enabled.

**Comment by thiagoftsm** [comment]
Hello @andrewm4894 ,

The PR https://github.com/netdata/netdata/pull/14309 will close this issue moving all collector logs for another log file, but we are not going to create a log per collector right now.

Best regards!
