### ISSUE TITLE
[Bug]: delay seems to be ignored

### ISSUE THREAD

**Issue by HolgerHees** [netdata/netdata#13831]
### Bug description

My alarm 10min_disk_backlog happens first time at 05:00:30. In my alarm log I see the state change at 05:02:02 from CLEAR to CRITICAL and at 05:12:02 back to CLEAR.

My Notification was send the first time at 05:02:03 and the second one at 05:12:03

My Alarm configuration delay looks like

delay: up 30m down 15m multiplier 1.2 max 1h

How is this possible, is there anything wrong in my configuration?

### Expected behavior

I would expect to get no notifications, because it is getting back to normal during my "up 30m" period.

### Steps to reproduce

happens every night during my heavy working backup job.

my notification is done via SYSLOG

`SEND_EMAIL="NO"

SEND_SYSLOG="YES"

DEFAULT_RECIPIENT_SYSLOG="netdata"

logger="/opt/netdata_helper/send_notification"
`

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux marvin 5.14.21-150400.24.21-default #1 SMP PREEMPT_DYNAMIC Wed Sep 7 06:51:18 UTC 2022 (974d0aa) x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="openSUSE Leap"
/etc/os-release:VERSION="15.4"
/etc/os-release:ID="opensuse-leap"
/etc/os-release:ID_LIKE="suse opensuse"
/etc/os-release:VERSION_ID="15.4"
/etc/os-release:PRETTY_NAME="openSUSE Leap 15.4"
/etc/os-release:ANSI_COLOR="0;32"
/etc/os-release:CPE_NAME="cpe:/o:opensuse:leap:15.4"
/etc/os-release:LOGO="distributor-logo-Leap"
```

### Netdata build info

```shell
Version: netdata v1.35.1
Configure options:  '--host=x86_64-suse-linux-gnu' '--build=x86_64-suse-linux-gnu' '--program-prefix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/lib' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-dependency-tracking' '--docdir=/usr/share/doc/packages/netdata-1.35.1' '--enable-plugin-nfacct' '--enable-plugin-freeipmi' '--enable-plugin-cups' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-suse-linux-gnu' 'host_alias=x86_64-suse-linux-gnu' 'CFLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g' 'CXXFLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     YES
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by HolgerHees** [comment]
found my configuration issues

**Comment by andrewm4894** [comment]
> found my configuration issues

Can you share if possible? Just in case useful to others for learning in future (and me :) )

**Comment by HolgerHees** [comment]
sure. Sorry for my short answer before. Normally I don't like this too :-)

I was implementing a script which synchronizes my alerts between netdata and alertmanager.

The script is triggered first by netdata as usual, but is also running as a cron job every 5 minutes to refresh alerts and mark them still as active, but also to creates missing or outdated alerts which can happen during restarts of netdata or alertmanager itself.

Inside this script I handle all errors and not only the ones which are the reason for the triggered action from netdata.

Working in this way I have to take care by my self about the "delay_up_to_timestamp" field to ignore alerts which are active but should not be notified because of a delay.

btw. this is my script

https://github.com/HolgerHees/smartserver/blob/master/roles/netdata/templates/opt/netdata_helper/send_notification

**Comment by andrewm4894** [comment]
Oh cool
