### ISSUE TITLE
[Bug]: pihole dns_queries_percentage export is wrong

### ISSUE THREAD

**Issue by nikobearrr** [netdata/netdata#13833]
### Bug description

Running the pihole go.d plugin to fetch metrics for pihole works very well. However there is a strange issue that the chart `pihole.dns_queries_percentage` is exactly the same as `pihole.dns_queries` when exported to graphite. No issue with any of the other graphs

### Expected behavior

I would expect that each chart is exported as seen on the netdata dahsboard

### Steps to reproduce

1. Run pihole
2. Use pihole go.d plugin
3. Fetch metrics in netdata
4. Export in graphite (perhaps all TSDB?)
5. Compare `pihole.dns_queries_percentage` vs `pihole.dns_queries`

### Installation method

docker

### System info

```shell
netdata 1.36.1 running in docker
```

### Netdata build info

```shell
chorba@chorbapc:~$ sudo docker exec -it netdata bash
bash-5.1# netdata -W buildinfo
Version: netdata v1.36.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: unknown
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
bash-5.1#
```

### Additional info

![image](https://user-images.githubusercontent.com/8693064/196044585-ba4496ca-c831-4171-b22a-8d3f331de90d.png)

![image](https://user-images.githubusercontent.com/8693064/196044603-97ad01dd-b677-4aa4-b75f-ca367d1c7ce0.png)

exporting.conf

```
[graphite:netdata]
enabled = yes
destination = host.docker.internal:2003
data source = as collected
prefix = netdata
update every = 1
buffer on failures = 10
timeout ms = 20000
send charts matching = sensors.* pihole.* cgroup_*.cpu* cgroup_*.io.* cgroup_*.mem_usage.* system.uptime* system.cpu* system.ram* system.net* time.* !*disk_space\._host_root_var_lib_docker_.* disk_space.* !*
send hosts matching = localhost *
send names instead of ids = yes
```

**Comment by ilyam8** [comment]
Hi, @nikobearrr. This is expected because of "as collected". The metrics are **collected as numbers** (that is why I mentioned "as collected") and we don't convert them into percentages during data collection (pihole collector). The conversion is done later by Netdata, the reason is [percentage-of-absolute-row dimension algorithm](https://github.com/netdata/go.d.plugin/blob/927cfd943f539abad8471463eb68aacaa93cf928/modules/pihole/charts.go#L50-L59).

> the % of this value compared to the total of all dimensions.

**Comment by ilyam8** [comment]
Despite the issue not being a bug, netdata/go.d.plugin#922 adds calculating percentage instead of using "percentage-of-incremental-row". It should fix the problem @nikobearrr
