### ISSUE TITLE
[Bug]: Issue with Centos Nodes Netdata Service is not starting 

### ISSUE THREAD

**Issue by tmbuthi** [netdata/netdata#13846]
### Bug description

I have installed Netdata using the Kickstart script and the service is not starting. 

### Expected behavior

I expected netdata to work properly once installed so I can monitor the node

### Steps to reproduce

1.
Created the .environment file but it is still now running the service. Seen a forum with a similar issue and followed steps to ending the netdata.service file and still no success. The Netdata admin said that this is a bug on their end. I will be creating a help ticket with netdata to further resolve this issue. 

Steps that I took to edit netdata. [Agent 1.33.0 won't start after successful installation](https://community.netdata.cloud/t/agent-1-33-0-wont-start-after-successful-installation/2477)

### Desktop

OS: CentOS 7

**Comment by hugovalente-pm** [comment]
@tmbuthi to speed-up the triage process could you provide the following information:
* Installation method
   Select installation method you used.
   Describe the method in the "Additional info" section if you chose "other".
 
![image](https://user-images.githubusercontent.com/82235632/196378378-4e60dc72-17c4-4e0b-bc40-59b04aa08f5c.png)

* System info
   Provide information about your system. To get this information, execute one of the following commands based on your OS:
 ```
# Linux
uname -a; grep -HvE "^#|URL" /etc/*release
# BSD
uname -a; uname -K
# macOS
uname -a; sw_vers
```

* Netdata build info
   Provide Netdata Agent version and build info. To get this information, execute:
```
netdata -W buildinfo
# If get "netdata: command not found", try (required running Netdata)
$(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
```

**Comment by tmbuthi** [comment]
Sounds good will do

**Comment by tmbuthi** [comment]
1. To Install I used the kickstart.sh 
2. System Info

# Linux 
[tmbuthi@webrelease01 ~]$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux webrelease01.alertinnovation.com 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.6.1810 (Core) 
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.6.1810 (Core) 
/etc/system-release:CentOS Linux release 7.6.1810 (Core) 

Netdata -W buildinfo 

Version: netdata v1.36.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-plugin-freeipmi' '--with-bundled-protobuf' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES

**Comment by MrZammler** [comment]
Seems similar to #13840

**Comment by tmbuthi** [comment]
I just tried the steps you suggested in https://github.com/netdata/netdata/issues/13840 and the directory /usr/lib/netdata does not exist. Neither does /usr/lib64/netdata

**Comment by MrZammler** [comment]
@tmbuthi 

Can you please run the kickstart script again, and provide it's output?

Also can you do a `yum repolist enabled` ?

**Comment by tmbuthi** [comment]
yum repolist enabled 
Loaded plugins: fastestmirror
Bad id for repo: CentOS-7 - SCLo sclo, byte =   8
Bad id for repo: InfluxDB Repository - RHEL 7, byte =   8
Repository 'pd-agent' is missing name in configuration, using id
Determining fastest mirrors
 * base: atl.mirrors.clouvider.net
 * centos-sclo-rh: mirror.metrocast.net
 * centos-sclo-sclo: mirror.vtti.vt.edu
 * centos_extra: mirrors.greenmountainaccess.net
 * epel: mirrors.mit.edu
 * updates: mirror.siena.edu
adoptopenjdk                                                            234/234
alert_internal_mirror                                                       7/7
duosecurity                                                               22/22
github_git-lfs                                                            50/50
netdata-edge                                                              54/54
netdata-repoconfig                                                          4/4
sensu                                                                   264/264
sensu_community                                                             3/3
repo id                        repo name                                  status
adoptopenjdk/7/x86_64          AdoptOpenJDK Repository                       234
alert_centos_mirror/7/x86_64   CentOS Mirror                                   0
alert_internal_mirror/7/x86_64 Alert Innovation private packages               7
base/7/x86_64                  CentOS-7 - Base                            10,072
!centos-sclo-rh/x86_64         CentOS-7 - SCLo rh                          8,137
!centos-sclo-sclo/x86_64       CentOS-7 - SCLo sclo                          816
!centos_extra/7/x86_64         Extra Packages for Enterprise Linux 7 - x8    515
!city_fan_repo/7/x86_64        City Fan repo                                 767
!docker-ce-stable/7/x86_64     Docker CE Stable - x86_64                     183
!duosecurity/7/x86_64          Duo Inc. officical repository                  22
epel/x86_64                    Extra Packages for Enterprise Linux 7 - x8 13,735
!github_git-lfs/x86_64         git-lfs repository                             50
icinga-snapshot-builds/7       ICINGA (snapshot builds for epel)           5,954
!influxdata/7/x86_64           InfluxData Repository - CentOS 7              278
!influxdb-repo/7/x86_64        InfluxDB Repository - RHEL 7                  278
!netdata-edge/7/x86_64         Netdata Edge                                   54
!netdata-repoconfig/7/x86_64   Netdata Repository Config                       4
!pd-agent                      pd-agent                                       22
!puppet6/x86_64                Puppet 6 Repository el 7 - x86_64             358
!puppetlabs-pc1/x86_64         Puppet Labs PC1 Repository el 7 - x86_64      192
!sensu/x86_64                  sensu                                         264
!sensu_community/x86_64        sensu_community                                 3
!updates/7/x86_64              CentOS-7 - Updates                          4,346
repolist: 46,291

**Comment by tmbuthi** [comment]
systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/usr/lib/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: inactive (dead) (Result: exit-code) since Mon 2022-10-24 15:48:47 EDT; 1 day 18h ago
  Process: 28042 ExecStart=/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D (code=exited, status=1/FAILURE)
  Process: 28038 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 28035 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 28032 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 28030 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 28042 (code=exited, status=1/FAILURE)

**Comment by MrZammler** [comment]
This appears to be the same as #13840 @tmbuthi do you mind if we continue there? There are also some suggestions there.
