### ISSUE TITLE
[Feat]: enable or install a collector from a GitHub url

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#13845]
### Problem

Can we make it easy for users to just enable a collector from a GitHub url. At the moment installing and enabling a custom collector is a little onerous or manual. Wondering if there could be a way we could just let users install/enable from source url in some way. So just automate the curl steps etc. 

### Description

Ability to enable a collector and tell netdata the url it lives at and that's where to pull the code from.

### Importance

nice to have

### Value proposition

1. Easy able for users to just use collectors from any GitHub url so long as they conform to some expected standards. Abstract any manual curl and install stuff for them.
2.
3.
...

**Comment by Ferroin** [comment]
This could probably be done using a relatively simple script.

The caveat is that if we want to do this, we need to define a ‘standard’ repo layout for third-party collectors, otherwise we have no way to ensure we get things put in place properly.

**Comment by shyamvalsan** [comment]
Let's just:
- create a standard repo layout as @Ferroin says
- create a script (netdata-install-collector) that is packaged with the agent
- running `netdata-install-collector <url>` should download the files, copy them to the right location and restart the netdata agent.
