### ISSUE TITLE
[Bug]: parsing of configuration files has issues with special characters in passwords

### ISSUE THREAD

**Issue by jacob-linode** [netdata/netdata#13855]
### Bug description

Hello,

I've noticed when configuring [postgres.conf](https://github.com/netdata/go.d.plugin/blob/master/config/go.d/postgres.conf) that some passwords do not work / are not parsed correctly. Particularly, I've noticed the # character seems to break things, as shown by the debug output:

```
[ DEBUG ] build[manager] build.go:303 building postgres[Database] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/postgres.conf autodetection_retry:0 dsn:postgres://postgres:Random#Password@192.168.1.10:5432/postgres module:postgres Database priority:70000 update_every:1]
[ ERROR ] postgres[Database] postgres.go:88 error on pinging the Postgres database [postgres://postgres:Random#Password@192.168.1.10:5432/postgres]: cannot parse `postgres://postgres:xxxxxx@192.168.1.10:5432/postgres`: failed to parse as URL (parse "postgres://postgres:Random": invalid port ":Random" after host)
```

Is this a limitation of netdata, go.d.plugin, or the DSN specification? Is there a list of special characters that cannot be used? Or can special characters be added in some way where the parser doesn't break when they're used?

I could not find any Github issues related to this issue, so apologies if it has been addressed before. 

### Expected behavior

I would expect the configuration file to be parsed correctly, assuming the password does not contain a @ character since that signifies the next token as the hostname to connect to

### Steps to reproduce

1. create a database user with a special character like # in the password
2. configure netdata to use this database, user, and password
3. `sudo -u netdata -s`
4. `cd /usr/libexec/netdata/plugins.d/`
5. `./go.d.plugin -d -m postgres`
6. observe error connecting to the database

### Installation method

kickstart.sh

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux localhost 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
netdata -W buildinfo
Version: netdata v1.36.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by ilyam8** [comment]
Hi, @jacob-linode. 

We use the [jackc/pgx](https://github.com/jackc/pgx#pgx---postgresql-driver-and-toolkit) library. It supports 2 ways to set DSN (follows [libpq connstring](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING)):
 - URL (URI).
 - connection string (key/word).

URLs (URIs) generally [RFC3986](https://www.rfc-editor.org/rfc/rfc3986). The jackc library internally uses golang std lib [url.Parse](https://pkg.go.dev/net/url#Parse). So there are 2 options:
 - golang std library has a problem (no).
 - your DSN in URI format doesn't follow RFC3986 (I think this is it, tho haven't checked).

Consider using the connection string method instead of URI.

**Comment by jacob-linode** [comment]
Hello @ilyam8, thanks for the help here. I seem to be having better luck with the connection string format:

`dsn: 'host=192.168.1.10 port=5432 dbname=postgres user=postgres password=Random#Password'`

Looks like that RFC doesn't allow for special characters like # in the URI format, so I will stick to the connection string.

Thanks again!
