### ISSUE TITLE
[Feat]: Add monitoring of Table_open_cache_overflows for mariadb/mysql

### ISSUE THREAD

**Issue by ced1check** [netdata/netdata#13858]
### Problem

Any Table_open_cache_overflows  will cause slowdown of the server. If part of a galera cluster this will possibly result in the whole cluster slowing down.

### Description

Table_open_cache_overflows is a good indicator of possible server slowdown.

### Importance

must have

### Value proposition

1.
Monitoring for non zero values could help pin-point configuraiton problems very easily. Changing ulimit for mariadb.service or mysql.service and setting table_open_cache option to higher values can solve this.

### Proposed implementation

As the value is constantly increasing, setting up an alarm based on increase would be enough to warn users of a problem.

**Comment by hugovalente-pm** [comment]
moving to the Agent repo, not sure if the recommendation here is to ask for a PR on https://github.com/netdata/netdata/blob/master/health/health.d/mysql.conf

wdyt @MrZammler ?

**Comment by ilyam8** [comment]
Added collecting "Table_open_cache_overflows" in netdata/go.d.plugin#936. I don't have experience/enough understanding to create an alarm. @ced1check if you are willing to help, please open a PR.
