### ISSUE TITLE
[Bug]: Cassandra latency values don't match expectation

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13888]
### Bug description

There appears to be a discrepancy in how latency is measured in the new Cassandra collector.

Cassandra collector reports latency in seconds, see below for read latency shown as 10 seconds

![image](https://user-images.githubusercontent.com/24860547/198024968-31ab88ff-2806-44b5-ae48-aa4f1af71cba.png)

However, the reported time period was when I was running cassandra-stress tool which gave the following results - even the max latency reported during the 3 minute test is just 234ms. 

```

Results:
Op rate                   :   36,223 op/s  [READ: 36,223 op/s]
Partition rate            :   36,223 pk/s  [READ: 36,223 pk/s]
Row rate                  :   36,223 row/s [READ: 36,223 row/s]
Latency mean              :    1.4 ms [READ: 1.4 ms]
Latency median            :    0.9 ms [READ: 0.9 ms]
Latency 95th percentile   :    3.8 ms [READ: 3.8 ms]
Latency 99th percentile   :   10.4 ms [READ: 10.4 ms]
Latency 99.9th percentile :   29.3 ms [READ: 29.3 ms]
Latency max               :  234.7 ms [READ: 234.7 ms]
Total partitions          :  6,520,418 [READ: 6,520,418]
Total errors              :          0 [READ: 0]
Total GC count            : 604
Total GC memory           : 187.719 GiB
Total GC time             :    3.9 seconds
Avg GC time               :    6.5 ms
StdDev GC time            :    6.0 ms
Total operation time      : 00:03:00
```

### Expected behavior

Latency numbers should be similar to results from cassandra-stress

10+ seconds of latency is unrealistically high for the workload that was executed. 

### Steps to reproduce

1. Execute following command on `thiago-cassandra` node

`cassandra-stress read duration=3m -rate threads=50`

2. Wait for test to finish to get results in the following format
```
Results:
Op rate                   :   36,223 op/s  [READ: 36,223 op/s]
Partition rate            :   36,223 pk/s  [READ: 36,223 pk/s]
Row rate                  :   36,223 row/s [READ: 36,223 row/s]
Latency mean              :    1.4 ms [READ: 1.4 ms]
Latency median            :    0.9 ms [READ: 0.9 ms]
Latency 95th percentile   :    3.8 ms [READ: 3.8 ms]
Latency 99th percentile   :   10.4 ms [READ: 10.4 ms]
Latency 99.9th percentile :   29.3 ms [READ: 29.3 ms]
Latency max               :  234.7 ms [READ: 234.7 ms]
Total partitions          :  6,520,418 [READ: 6,520,418]
Total errors              :          0 [READ: 0]
Total GC count            : 604
Total GC memory           : 187.719 GiB
Total GC time             :    3.9 seconds
Avg GC time               :    6.5 ms
StdDev GC time            :    6.0 ms
Total operation time      : 00:03:00
```

3. Now compare with what is reported in Netdata (cassandra.client_requests_latency)

### Installation method

kickstart.sh

### System info

```shell
$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux thiago-cassandra 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.36.0-234-gbfd9b3445
```

**Comment by ilyam8** [comment]
@shyamvalsan I think you missed the difference between total latency (all requests) vs a request min/max/avg latency.

**Comment by shyamvalsan** [comment]
Hmm - in that case maybe we are querying the wrong metric. Not sure how useful a "TotalLatency" counter is. 

org.apache.cassandra.metrics.ColumnFamily.ReadTotalLatency is a [Counter](http://metrics.dropwizard.io/2.2.0/apidocs/com/yammer/metrics/core/Counter.html) which gives the sum of all read latencies.

org.apache.cassandra.metrics.ColumnFamily.ReadLatency is a [Timer](http://metrics.dropwizard.io/2.2.0/apidocs/com/yammer/metrics/core/Timer.html) which gives insights about how long the reads are taking, it reports attributes like min, max, mean, 90percentile, 99percentile etc

**Comment by ilyam8** [comment]
I think those are different metrics. I assume ClientRequest includes network latencies whether ColumnFamily does not.

>  in that case maybe we are querying the wrong metric

Maybe, not a Cassandra specialist. ClientRequest's been taken because of https://www.datadoghq.com/blog/how-to-collect-cassandra-metrics/.

ColumnFamily and Table metrics are [filtered](https://github.com/netdata/go.d.plugin/blob/221262f5b5d03f2c1748b328dcac747031bd4d76/modules/cassandra/jmx_exporter.yaml#L4-L6).

> TotalLatency is a sum, why does it go up and down over time?

Because per second rate is calculated by Netdata

> incremental

the value increases over time, the difference from the last value is presented in the chart, the server interpolates the value and calculates a per-second figure

**Comment by shyamvalsan** [comment]
But aren't they (DD) querying both kinds of latency

![image](https://user-images.githubusercontent.com/24860547/198030597-7c66366f-ca80-437e-80f7-dc873c0f1ea7.png)

what is shown in their dashboard is definitely not the total we are querying

![image](https://user-images.githubusercontent.com/24860547/198030750-e18149d2-e846-409c-9c99-cfa445789562.png)

**Comment by ilyam8** [comment]
My understanding is that it is not a different kind of latency. 

- TotalLatency is the sum of read/write latencies.
- Latency is the sum of read/write requests.
-

**Comment by shyamvalsan** [comment]
So we should collect both and calculate the latency that should be displayed in chart?

**Comment by ilyam8** [comment]
@shyamvalsan our two charts show: the total number of read/write requests and the one below it total time it took to  (let's say) process all the read/write requests.

**Comment by shyamvalsan** [comment]
What I am saying is - can we query the actual latency (not the TotalLatency)

Being able to see for example the average, 95th and 99th percentile latency is more useful than seeing TotalLatency. If we need to split read latency and write latency into separate charts then we should do that but still get the actual useful data.

**Comment by ilyam8** [comment]
from [this blog](https://www.batey.info/cassandra-clientrequest-metrics.html) (I don't have that console tool)

<img width="886" alt="Screenshot 2022-10-26 at 17 23 07" src="https://user-images.githubusercontent.com/22274335/198052182-de192cbb-9b74-468e-aabd-c728db6eedf3.png">

average(mean), 95th, and 99th percentile latency are the latest calculated values. If we add them they will be changed if there are new requests. It means that they won't be zero if there are not requests.

**Comment by shyamvalsan** [comment]
My understanding is they are the average or percentile of all the requests that are received - so why would they be non-zero if there are zero requests?

**Comment by ilyam8** [comment]
ok, we show the requests as a rate. If there are no requests rate is 0. But the mean (95th, 99th, etc) latency is not 0, because it is the mean (95th, 99th, etc) latency for all previous requests.

**Comment by shyamvalsan** [comment]
But is that a problem - if the request rate remains at 0 for a considerable period of time then eventually all latencies will also show 0.

**Comment by ilyam8** [comment]
No, they will not. It doesn't matter if "request rate remains at 0" because the average or any other calculated value doesn't change. Example: calculate the average of 1+2+3 today and tomorrow morning. The result doesn't change if the input doesn't change.
