### ISSUE TITLE
[Feat]: Configure auto discovery

### ISSUE THREAD

**Issue by fayak** [netdata/netdata#13908]
### Problem

Sometimes a service being monitored by netdata crashes on our infra. From what I have understood of Netdata's behavior, once a datasource returns an error for x amount of times (I don't even know what x is), it is considered as dead and removed from netdata list of collectors. In this case, my service that crashed won't be monitored by Netdata anymore if it comes back alive after a certain amount of time.

This causes drops of metrics for some services, fixed only infrequently when manually detected and with a restart of Netdata, and also prevent us from running a new service after Netdata started and collect its metrics.

The only solution so far is to restart netdata, so auto discovery can run again and re-detect this service. Restarting is annoying, because it causes missing metrics, and seems sub-optimal.

### Description

From the problem given above, and if my assumptions are not wrong, here are the things I'd like:
- A way to configure auto discovery to keep on retrying on a given service if it worked at some point.
  It would help me by keeping on getting my crashed service metrics until it comes back alive without disabling the plugin

- A way to configure auto discovery to control how many times I want it to run and/or its frequency.
  I could configure it to keep on trying forever at some low frequency, to re-detect my crashed service after it's back alive and after a configurable amount of time
  
- A way to force a reset of auto discovery, with a signal, an API route or via `netdatacli`.
  I could use it to ask netdata to reload auto discovery and find my crashed-and-restored service again.

### Importance

must have

### Value proposition

1. Better understanding and control over auto discovery, which I reckon is a bit unclear to users
2. Avoid drops of useful metrics in case of a temporary service failure

**Comment by ilyam8** [comment]
Hi, @fayak 👋 

>  From what I have understood of Netdata's behavior, once a datasource returns an error for x amount of times (I don't even know what x is), it is considered as dead and removed from netdata list of collectors. 

What collector are you referring to? Because it is not the case, for instance, for python.d.plugin and go.d.plugin. Both of them never give up on trying to collect data, but gradually slow down attempts on consecutive data collection failures. As soon as data collection succeeds the penalty gets reset. The penalty is added for every 5th failed data collection.

<details>
<summary>Penalty example for a job with update_every 1</summary>

```
0
0
0
0
0
2
2
2
2
2
5
5
5
5
5
7
7
7
7
7
10
10
10
10
10
12
12
12
12
12
15
15
15
15
15
17
17
17
17
17
20
20
20
20
20
22
22
22
22
22
```

</details>

**Comment by fayak** [comment]
Hello @ilyam8 !

Sorry for the delay in the response.

In this case my deductions are wrong, but observed multiple times custom plugins under python.d.plugin that got disabled, likely because the plugin failed a few times, or because the underlying service died for some time. 

It happened to us a few times, and we didn't have much more information than that :/ Since it's not very frequent, and we failed to detect quickly the suddenly missing data, I'm not very helpful in describing the problem with details...

Do you know if anything could have caused this observed (and unfortunately not easily reproducible) issue ?

Sorry for bothering you if the cause if elsewhere

**Comment by ilyam8** [comment]
Closing because both python.d and go.d plugins have `autodetection_retry`.

```bash
# autodetection_retry sets the job re-check interval in seconds.
# The job is not deleted if the check fails.
# Attempts to start the job are made once every autodetection_retry.
# This feature is disabled by default.
# autodetection_retry: 0
```
