### ISSUE TITLE
[Bug]: cgroup-name.sh failure on Amazon EKS (kubernetes)

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13900]
### Bug description

We noticed that under certain conditions, the cloud kubernetes dashboard with the boxes for each container or pod fails and shows only a single container. The issue was traced to the lack of k8s_* labels from the cgroups collector. The root cause is the inability of [cgroup-name.sh to retrieve the container metadata from the kubernetes API](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh#L292)

The issue is currently visible on our public demo server, so we'll need to debug cgroup-name-.sh on it, to figure out what doesn't work. 

### Expected behavior

Properly identify containers and enrich them with the k8s metadata everywhere. 

### Steps to reproduce

See our demo server

### Installation method

kickstart.sh

### System info

```shell
Amazon EKS
```

### Netdata build info

```shell
Latest
```

**Comment by ilyam8** [comment]
We checked the issue and it was a misconfiguration problem - a lack of needed permissions to query K8s API.
