### ISSUE TITLE
[Bug]: Netdata can't be shut down gracefully in WSL1

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#13933]
### Bug description

Both `netdatacli shutdown-agent` and `killall netdata` just don't work and start creating a huge load on the windows machine. 
Things seem to work with WSL2, but not WSL1.

### Expected behavior

Gracefully shut down netdata

### Steps to reproduce

1. Run the msi-installer from github.com/netdata/msi-installer and ensure that it installed WSL1 
```
C:\Users\cakri>wsl -l -v
  NAME       STATE           VERSION
* Ubuntu     Stopped         2
  Netdata    Running         1
```

2. Try to kill netdata with netdatacli or killall.

### Installation method

other

### System info

```shell
wsl1
```

### Netdata build info

```shell
latest
```

**Comment by MrZammler** [comment]
Hi!

Just did a local build of master Netdata inside an Ubuntu running on wsl1, it appears shutdown either with `netdatacli` or `killall` works ok.

Will try using the installer.

**Comment by MrZammler** [comment]
Do we have an `error.log` from an affected system? Seems installer is currently not working...

**Comment by MrZammler** [comment]
I've imported as @Ferroin our image into wsl1, and indeed there is issue. It seems there is problem stopping threads, will investigate...

**Comment by dfpr** [comment]
I've just tested this but `killall netdata` still goes to max cpu usage using WSL1, I used the latest docker image, could it be the change would be applied tomorrow?

**Comment by Ferroin** [comment]
It should be in the current latest Docker image. They only get published once a day at around 01:00 UTC.

**Comment by MrZammler** [comment]
Hi @dfpr 

Have you perhaps tried a more recent nightly?

**Comment by dfpr** [comment]
> Hi @dfpr 
> 
> 
> 
> Have you perhaps tried a more recent nightly?

@MrZammler I tried last Friday and still had the issue, I'll try again today.

**Comment by cakrit** [comment]
@MrZammler can you check again here?

**Comment by MrZammler** [comment]
Yes, sorry, somehow missed that the check was with -344.

**Comment by MrZammler** [comment]
@dfpr 

Can you please try by using in `netdata.conf` -> section `[ml]` -> `enabled = no` ?

**Comment by dfpr** [comment]
@MrZammler 

> @dfpr
> 
> Can you please try by using in `netdata.conf` -> section `[ml]` -> `enabled = no` ?

@MrZammler I've just tested again with `netdata v1.36.0-397-nightly` without disabling machine learning and after `killall netdata` the process stays at high cpu usage for a few seconds before terminating so I guess it is fixed.

**Comment by Dim-P** [comment]
Closing as fixed. If it reappears, we will reopen it.
