### ISSUE TITLE
[Bug]: ACLK-available-is-false

### ISSUE THREAD

**Issue by garinichsan** [netdata/netdata#13964]
### Bug description

Cannot connect node to Netdata Cloud.
I was able to "claim" this done, but it is showing as unavailable in the netdata.cloud console.

### Expected behavior

Visualize node through Netdata Cloud.

### Steps to reproduce

1. Installed netdata
2. ran claim script from netdata.cloud

### Installation method

kickstart.sh

### System info

```shell
Linux tambora 4.15.0-194-generic #205-Ubuntu SMP Fri Sep 16 19:49:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.6 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.6 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

### Netdata build info

```shell
Version: netdata v1.36.0-326-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Info from /var/log/netdata/error.log

```
2022-11-09 19:37:55: netdata INFO  : ACLK_Main : Attempting connection now
2022-11-09 19:37:56: netdata ERROR : ACLK_Main : SSL_write Err: Unknown!!! (errno 104, Connection reset by peer)
2022-11-09 19:37:56: netdata ERROR : ACLK_Main : Couldn't write HTTP request header into SSL connection
2022-11-09 19:37:56: netdata ERROR : ACLK_Main : Couldn't process request
2022-11-09 19:37:56: netdata ERROR : ACLK_Main : Error trying to contact env endpoint
2022-11-09 19:37:56: netdata ERROR : ACLK_Main : Failed to Get ACLK environment
2022-11-09 19:37:56: netdata INFO  : ACLK_Main : Wait before attempting to reconnect in 0.124 seconds
```

It keeps repeating those lines

**Comment by MrZammler** [comment]
Hi @garinichsan thank you for the report, we will look into it asap.

Could you please send the error.log to manolis@netdata.cloud ?

Thanks.

**Comment by MrZammler** [comment]
Hi @garinichsan 

Just to check whether this is a Netdata problem, or a system one, is the machine there in general in ok shape, is it updated, does it show any other network issues? Are you perhaps behind a very restrictive firewall ? What does `curl https://api.netdata.cloud` from that machine?

Thanks

**Comment by garinichsan** [comment]
That may be the case. The machine is behind my university's firewall. Is there any port that I have to open to the public? So I can request my university to allow it.

> What does curl https://api.netdata.cloud return from that machine?

the result is `default backend - 404`

Thanks!

**Comment by MrZammler** [comment]
Hi @garinichsan 

You can check [this](https://learn.netdata.cloud/guides/troubleshoot/troubleshooting-agent-with-cloud-connection) regarding some info on troubleshooting the connection. I'm not sure there's need to open a specific port, as much maybe check if needed domains in that doc are permitted in general.

**Comment by MrZammler** [comment]
Hi @garinichsan 

There have been some fixes from our side as well, regarding some general connectivity issues, have you perhaps re-tried ?

**Comment by garinichsan** [comment]
Because of the long process that we have to spend to propose changes in the firewall rule to our campus, we decide to use a local monitoring system instead. That is currently enough for us.
Thank you for being so helpful.

**Comment by mathewmeconry** [comment]
Had the same issue.... disabling the internal IPv6 network resolved it.
I am not sure if it was my firewall or something on netdatas side. But a IPv6 connection didn't work eventho the DNS resolved to some IPv6 addresses on AWS

**Comment by MrZammler** [comment]
Indeed there have been some fixes lately related to the above, thanks @mathewmeconry .

@garinichsan feel free to try again. Also you could consider that the Netdata agent runs locally as well and is accessible through it's local dashboard if you need so.
