### ISSUE TITLE
[Bug]: I enabled prometheus collector but it does not seem to be doing ML on the metrics.

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#13972]
### Bug description

I enabled some prometheus data collection like this. 

Pulling from the [Prometheus demo site](https://demo.do.prometheus.io/) node exporter [endpoint](https://node.demo.do.prometheus.io/metrics): 

```yaml
jobs:
  - name: node_exporter_demo
    url: https://node.demo.do.prometheus.io/metrics
```

I can see all the expected prometheus metrics in netdata but they dont seem to be getting picked up for training for ML for the native anomaly detection within Netdata.

### Expected behavior

I would expect that as these new dimensions come into existence on the agent, netdata would just grow the training of the ml dimensions to cover them. 

### Steps to reproduce

1. enable prometheus collector, with above config, as per here: https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/prometheus
2. watch and see if more metrics start getting trained in anomaly detection charts. 
...

### Installation method

kickstart.sh

### System info

```shell
.
```

### Netdata build info

```shell
.
```

### Additional info

.

**Comment by andrewm4894** [comment]
@vkalintiris i think this one could potentially be a bug or something - could there be some reason that new charts and dims coming from enabling Prometheus exporter might not be getting picked up by ml for training and inference?

**Comment by vkalintiris** [comment]
Known limitation, ie. we only train metrics with the same collection frequency of the host. If I am not mistaken, this is 10 secs for prometheus vs 1 second by default for netdata. Ideally, the goal is to support this use case in the next release.

**Comment by ilyam8** [comment]
Correct, @vkalintiris, the [default is 10](https://github.com/netdata/go.d.plugin/blob/aa48bf112213b72141227debe8a04f9d9059d69d/modules/prometheus/prometheus.go#L17). So it is not a bug (unexpected behavior) and not prometheus specific.

**Comment by ilyam8** [comment]
>  Ideally, the goal is to support this use case in the next release.

@andrewm4894 @vkalintiris please open a new issue to track this change (if not exists/ if needed).
