### ISSUE TITLE
[Bug]: lost lxd conteneurs in dashboard

### ISSUE THREAD

**Issue by lds-lds** [netdata/netdata#13976]
### Bug description

Hello
since today I no longer see my lxd containers in the netdadta dashboard

my system is
- ubuntu focal
- lxd 4.0.9
- netdata v1.36.0-333-g6b62c18d9

### Expected behavior

view my container in dashboard

### Steps to reproduce

unknow

### Installation method

kickstart-static64.sh

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux xxxxx 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.5 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.5 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.36.0-333-g6b62c18d9
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by vlvkobal** [comment]
Please provide path/name for lxd containers that disappeared from the dashboard.

**Comment by ilyam8** [comment]
And let's see cgroup related logs

```
sudo cp /dev/null /opt/netdata/var/log/netdata/error.log && sudo systemctl restart netdata && sleep 60 && grep -i cgroup /opt/netdata/var/log/netdata/error.log
```

**Comment by cakrit** [comment]
Just to be sure, you are talking about the agent UI, not the cloud, correct?
Because I just responded to https://community.netdata.cloud/t/docker-containers-visible-in-agent-web-ui-but-not-netdata-cloud/959/5 about something similar, but it's specific to the change done in the single node view in the cloud

**Comment by lds-lds** [comment]
agent ui (blabla.bla.com:19999) and the cloud

**Comment by lds-lds** [comment]
@ilyam8 
Just INFO in grep -i cgroup /opt/netdata/var/log/netdata/error.log no ERRORS
I can't copy paste the result, it's private data, sorry

**Comment by lds-lds** [comment]
@ilyam8

here  an anonymized log entry

2022-11-10 18:20:25: cgroup-name.sh: INFO: cgroup 'lxc.payload.xxxxxxxxxxxxxxx' is called 'xxxxxxxxxxxxxxx'
2022-11-10 18:20:25: /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : running: exec /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/sys/fs
/cgroup/cpu,cpuacct/lxc.payload.xxxxxxxxxxxxxxx'
2022-11-10 18:20:25: cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/sys/fs/cgroup/cpu,cpuacct/lxc.payload.xxxxxxxxxxxxxxx'
2022-11-10 18:20:26: cgroup-name.sh: INFO: cgroup 'lxc.monitor.bm-dijon-planningb' is called 'lxc.monitor.bm-dijon-planningb'
2022-11-10 18:20:26: cgroup-name.sh: INFO: cgroup 'lxc.monitor.xxxxxxxxxxxxxxx' is called 'lxc.monitor.xxxxxxxxxxxxxxx'

**Comment by lds-lds** [comment]
@vlvkobal 
Hello :)
have you been able to progress on the correction of this bug because it is a real big problem for us

**Comment by ilyam8** [comment]
Hi, @lds-lds. The log lines you shared have no indication of any problem. What dashboard are you referring to? Cloud UI or local dashboard (accessible via 19999).

**Comment by lds-lds** [comment]
@ilyam8 
i have 19 servers with lxd
all containers disappeared from Cloud UI
everything is ok on local dashboard

**Comment by lds-lds** [comment]
I understood.
Now there is only one cgroup menu and for each entry "cpu ram etc" we can filter on the instances
So it's a reorganization of visualization
It's a big big big regression ....

**Comment by ilyam8** [comment]
> Now there is only one cgroup menu and for each entry "cpu ram etc" we can filter on the instances

Additionally, metrics for all containers are available in Top -> Containers-vms.
