### ISSUE TITLE
[Feat]: Add NGINX Plus metrics to our NGINX collector

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata#13982]
### Problem

Our current NGINX collector only collects metrics from the open source NGINX deployments and this should be extended to also collect metrics from NGINX plus which readily provides additional metrics.

### Description

NGINX Plus provides all the metrics available from NGINX and in addition some key metrics. NGINX Plus provides a JSON feed with much richer data. Read the companion post on [NGINX metrics collection](https://www.datadoghq.com/blog/how-to-collect-nginx-metrics/) for instructions on enabling metrics collection.

The list of the additional metrics are mentioned below:

- [ ] Connections / Activity Metrics - Accepted, Handled, Dropped (available by default), Active, Idle
<img width="867" alt="image" src="https://user-images.githubusercontent.com/96257330/201325163-bfb2d0f9-fa49-455b-91f7-e3d9109adaaf.png">
- [ ] Error Metrics - The status codes are automatically available through NGINX Plus
<img width="863" alt="image" src="https://user-images.githubusercontent.com/96257330/201325572-473c9aa2-f391-40c6-8819-b665aee01917.png">
- [ ] Performance metrics - Include request processing time which is extremely useful for debugging web server performance.
- [ ] Reverse Proxy metrics - One of the most common ways to use NGINX is as a [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy). The commercially supported NGINX Plus exposes a large number of metrics about backend (or “upstream”) servers, which are relevant to a reverse proxy setup.
<img width="863" alt="image" src="https://user-images.githubusercontent.com/96257330/201326097-c8eebb71-bcf0-48eb-81e0-5eed2a28be13.png">

### Importance

must have

### Value proposition

1. Provides monitoring capabilities for a commercial NGINX deployment
2. Provides completeness to our NGINX monitoring use case

### Proposed implementation

The better approach will be to introduce the new metrics as part of the existing NGINX collector and identify if the user has an open-source / commercial version and accordingly collect the relevant metrics.

**Comment by ilyam8** [comment]
@sashwathn it is paid, how do you expect us to implement it?

**Comment by sashwathn** [comment]
I will get a subscription for us to implement this.

**Comment by sashwathn** [comment]
@ilyam8 : We can get a 1 month free trial for NGINX Plus. Will that be sufficient for our implementation?
