### ISSUE TITLE
[Feat]: Show which guest is using most resources

### ISSUE THREAD

**Issue by shodanshok** [netdata/netdata#13986]
### Problem

It is currently difficult to identify which guests, from the ones running, is consuming resources. 

### Description

As stated above, it is currently difficult to identify which guests, from the ones running, is consuming resources. Take, for example, this graph:

![screenshot](https://user-images.githubusercontent.com/13137622/201486666-031cb4f1-b4cd-4a3c-b3b3-a26c513dbda2.JPG)

One of my guests fired at 16:36, but to discover *which one* I had to inspect all the libvirt/qemu registered guest one-by-one. This is trivial when running only a bunch of guests, but become unpractical when the running guest list grows.

Please note that the CPU graph was selected only as a simple example. For the record, the application graph shows the same collapsed information:

![screenshot2](https://user-images.githubusercontent.com/13137622/201486979-882b0d9c-42dd-41d3-9c0a-c781a483e2aa.JPG)

Note as all relevant data is hidden behind the `VM` label.

### Importance

really want

### Value proposition

1. when a host slow down, it is of key importance to identify which guest is causing the slowdown.
2. without this capability, one has to effectively use another reporting and graphical tools (ie: grafana) to extract the needed information.

### Proposed implementation

As we are doing for processes or IRQs, a short list of the most active guests can be presented to the user.

**Comment by aarushisoni** [comment]
I want to contribute to this issue . Kindly guide me .

**Comment by andrewm4894** [comment]
Thanks @shodanshok and @aarushisoni. @MrZammler or @stelfrag any idea if this actually could be a good example use case for the new "functions" functionality. 

More info on the functions functionality can be seen [here](https://github.com/netdata/netdata-cloud/issues/602). Still in fairly early development/conception but this issue seemed like could be a good example use case perhaps.

**Comment by andrewm4894** [comment]
@shodanshok i think there maybe is an easy way to see this in Netdata Cloud app that groups the individual charts.

For example on my node below i can see that the `airbyte-db...` and `airbyte-temporal...` containers spiked together.

![image](https://user-images.githubusercontent.com/2178292/201703712-aaa7f401-da9f-4db4-ab43-8718fa116277.png)

Is this the sort of thing you mean?

**Comment by shodanshok** [comment]
@andrewm4894 yeah, something similar, but not necessarily tied to cgroup and especially not to netdata cloud.

**Comment by ilyam8** [comment]
Container and VMs (cgroups) resource utilization is available in:
 - Top -> Containers-vms
 - Metrics -> Containers-vms

Both don't require Cloud.
