### ISSUE TITLE
[Bug]: ./configure --without-PACKAGE ?

### ISSUE THREAD

**Issue by vermaete** [netdata/netdata#13996]
### Bug description

When doing a `./configure --without-health` or `--without-perf` the configure script it failing with 

```
ERROR: netdata-1.36.1-r0 do_configure: QA Issue: netdata: configure was passed unrecognised options: --without-health [unknown-configure-option]
```
or 

```
ERROR: netdata-1.36.1-r0 do_configure: QA Issue: netdata: configure was passed unrecognised options: --without-perf [unknown-configure-option]
```

(well, the output comes from the do_configure step in Yocto)

Could it be the --help info of `./configure` is wrong or generated wrong with the autotools?

```
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
```

or is e.g. perf not a package?

### Expected behavior

I guess something not clear for me in the documentation of ./configure --help.
Or some generated code with autotools that could be disabled.

### Steps to reproduce

do_configure in yocto, what's the same as running ./configure

### Installation method

other

### System info

```shell
Yocto
```

### Netdata build info

```shell
1.36.1 from https://layers.openembedded.org/layerindex/recipe/50696/
```

**Comment by thiagoftsm** [comment]
Hello @vermaete ,

The `perf` is an internal plugin of netdata, while `health` is our notification thread, this is the motive you cannot disable both with the flags you are using.

Best regards!

**Comment by thiagoftsm** [comment]
An additional information, you can take a look in the available options looking for `--with-` in [this](https://github.com/netdata/netdata/blob/master/configure.ac) file.
