### ISSUE TITLE
[Feat]: Dont count idle disk io (e.g. raid scrub) towards health alarms

### ISSUE THREAD

**Issue by spinitron** [netdata/netdata#14008]
### Problem

Some of my Debian servers do a [monthly RAID scrub](https://raid.wiki.kernel.org/index.php/Scrubbing_the_drives) that triggers alarms from Netdata disk.util health check. The kernel does the scrub so I trust it to schedule that io at idle priority. And I observe no impact on performance of anything else the system does. So it's not a problem that the device is at 100% utilization for several hours.

### Description

I’d like not to get alarms for high io utilization if most of it is idle priority transactions. Basically I think the alarm should count only io traffic at higher than idle priority (or I’d like to be able to configure it thus). Is that feasible? Does the kernel provide stats that would allow Netdata to discriminate like this?

### Importance

really want

### Value proposition

1. Don't wake me up at night!
2. I like to sleep.
3. The alarm sound my phone makes when Netdata sends a critical causes PTSD-like symptoms.

### Proposed implementation

I don't even know if the kernel provides stats that allow you to discount idle priority disk io. Sorry.

**Comment by ilyam8** [comment]
Hi, @spinitron.

> Is that feasible? Does the kernel provide stats that would allow Netdata to discriminate like this?

No, it doesn't to my knowledge. Diskstats metrics come from `/proc/diskstats`. See the [stats description](https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats).

```cmd
$ cat -p /proc/diskstats
  11       0 sr0 9 0 3 1 0 0 0 0 0 16 1 0 0 0 0 0 0
   8       0 sda 14706 6728 1128854 4921 105321 40107 13503646 567276 0 276104 572198 0 0 0 0 0 0
   8       1 sda1 643 93 72176 82 9 1 38 30 0 132 113 0 0 0 0 0 0
   8       2 sda2 2 0 4 0 0 0 0 0 0 8 0 0 0 0 0 0 0
   8       5 sda5 14010 6635 1054322 4833 105312 40106 13503608 567245 0 276032 572079 0 0 0 0 0 0
 254       0 dm-0 20581 0 1049346 11520 141276 0 13503608 609500 0 275620 621020 0 0 0 0 0 0
```

Disk utilization is calculated using 

> 11  time spent writing (ms)

**Comment by ilyam8** [comment]
I think the only solution at the moment is to use Health Management API. If monthly raid scrub is executed by a script, you can update the script like:

 - silence disk.util
 - run raid scrub
 - unsilence disk.util


See [Disable or silence specific alarms](https://learn.netdata.cloud/docs/agent/web/api/health#disable-or-silence-specific-alarms) for details.

**Comment by spinitron** [comment]
Thanks @ilyam8 for the answer and for netdata which I find very useful.
