### ISSUE TITLE
[Bug]: Configure Netdata Postgresql 10 and PgAgent

### ISSUE THREAD

**Issue by rodrigobuch** [netdata/netdata#14036]
### Bug description

Error in scenario with PgAgent Postgresql 10

2022-11-22 15:55:25.242 -03 [2604435] netdata@postgres ERROR:  permission denied for schema pgagent
2022-11-22 15:55:25.242 -03 [2604435] netdata@postgres STATEMENT:
        SELECT current_database()                                   as datname,
               schemaname,
               relname,
               seq_scan,
               seq_tup_read,
               idx_scan,
               idx_tup_fetch,
               n_tup_ins,
               n_tup_upd,
               n_tup_del,
               n_tup_hot_upd,
               n_live_tup,
               n_dead_tup,
               EXTRACT(epoch from now() - last_vacuum)              as last_vacuum,
               EXTRACT(epoch from now() - last_autovacuum)          as last_autovacuum,
               EXTRACT(epoch from now() - last_analyze)             as last_analyze,
               EXTRACT(epoch from now() - last_autoanalyze)         as last_autoanalyze,
               vacuum_count,
               autovacuum_count,
               analyze_count,
               autoanalyze_count,
               pg_total_relation_size(quote_ident(schemaname) || '.' || quote_ident(relname)) as total_relation_size
        FROM pg_stat_user_tables;

### Expected behavior

The Netdata user has already been released in Postgresql:
GRANT pg_monitor TO netdata;

### Steps to reproduce

Default netdata configured

### Installation method

other

### System info

```shell
Linux BD02 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.36.0-380-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Verified on community forum by Shyam
Shyam Sreevalsan
netdata team

**Comment by ilyam8** [comment]
Hi @anayrat, @benoitdm-oslandia. Can you help with this issue?

How it works. Postgres collector discovers queryable databases using [this query](https://github.com/netdata/go.d.plugin/blob/d931ae4eed39e50b1caae09284b6cc3937fc9fad/modules/postgres/queries.go#L456):

```sql
SELECT datname
FROM pg_database
WHERE datallowconn = true
  AND datistemplate = false
  AND datname != current_database()
  AND has_database_privilege((SELECT CURRENT_USER), datname, 'connect');
```

Then it creates an additional connection for every queryable database and executes:

```sql
SELECT current_database()                                   as datname,
       schemaname,
       relname,
       seq_scan,
       seq_tup_read,
       idx_scan,
       idx_tup_fetch,
       n_tup_ins,
       n_tup_upd,
       n_tup_del,
       n_tup_hot_upd,
       n_live_tup,
       n_dead_tup,
       EXTRACT(epoch from now() - last_vacuum)              as last_vacuum,
       EXTRACT(epoch from now() - last_autovacuum)          as last_autovacuum,
       EXTRACT(epoch from now() - last_analyze)             as last_analyze,
       EXTRACT(epoch from now() - last_autoanalyze)         as last_autoanalyze,
       vacuum_count,
       autovacuum_count,
       analyze_count,
       autoanalyze_count,
       pg_total_relation_size(quote_ident(schemaname) || '.' || quote_ident(relname)) as total_relation_size
FROM pg_stat_user_tables;
```

The query fails with "permission denied for schema pgagent".

---

The question: is it possible to filter out tables/schemas for which we have no permissions to query in the query using WHERE?

**Comment by anayrat** [comment]
Maybe we should add an option to exclude database?  Thus, we could add a filter `AND datname NOT IN (...)`

**Comment by ilyam8** [comment]
Yes, that is always an option, @anayrat. I am wondering if there is a way to automatically exclude not queryable tables/schemas, etc. Like we do for databases by checking 'connect' privilege.

```sql
AND has_database_privilege((SELECT CURRENT_USER), datname, 'connect');
```

**Comment by anayrat** [comment]
Indeed, it is a solution!

**Comment by ilyam8** [comment]
Ok, I will set up Postgres + PgAgent and try to find a proper fix. Quick googling shows the following may help:

> 
has_schema_privilege(schema, privilege) | boolean | does current user have privilege for schema
-- | -- | --

> has_schema_privilege checks whether a user can access a schema in a particular way. Its argument possibilities are analogous to has_table_privilege. The desired access privilege type must evaluate to some combination of CREATE or USAGE.

**Comment by ilyam8** [comment]
Tested https://github.com/netdata/go.d.plugin/pull/1006 with Postgres 14.4. Seems to be working well with no more errors.
