### ISSUE TITLE
[Feat]: `api/v1/dataframe`

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#14040]
### Problem

I would like to get data from multiple charts in one simple api call to the agent.

### Description

I want to hit `api/v1/dataframe?chart_filter=apps.cpu*|apps.*mem&freq=30s&dimension_filter=ssh|cron&group=average&after=-3600&before=0&format=csv`

To get back a csv table of dimensions matching `ssh` or `cron` from all `apps.cpu*` and `apps.*mem` charts. Averaged to a frequency (`freq`) of `30s` (so use that to determine `points` - too hard for me as user to think of that).

### Importance

really want

### Value proposition

1. a proper and efficient /dataframe api will be very useful in opening up many data and ml featurse as i can get all data i need from agent in one call.
...

### Proposed implementation

An api endpoint that can have additional complexity layers on like pre and post proccessing steps etc that can be pushed down to the agent when/where makese sense.

**Comment by ktsaou** [comment]
Patterns already work:

```
http://localhost:19999/api/v1/data?chart=apps.cpu*,apps.*mem&dimension=ssh,cron&options=jsonwrap,unaligned
```

The only problem is the number of points, which you must give.
If you want averaging over 30s, give:

```
points = (before - after) / 30
````

For this to work, `before` and `after` need to be both absolute timestamps, or relative duration. That is, don't mix absolute and relative in the same query for this calculation. Also, make sure `(before - after)` is a multiple of 30, otherwise netdata may adjust it.

So, this request is only about adding to netdata an option to calculate the points based on the point duration given.

**Comment by ktsaou** [comment]
btw, netdata can also produce csv with `&format=csv` (remove the `jsonwrap` option if you want it raw, without a json header).

**Comment by andrewm4894** [comment]
oh cool - did not realise this.

Will play with it and try use it in [`netdata-pandas`](https://github.com/netdata/netdata-pandas) instead of making lots of async calls for each chart. 

Was also going to ask/explore at some stage ability to say `format=parquet` to get back an [apache parquet](https://parquet.apache.org/) file as that would be a lot smaller than sending csv or json back (i think - not really sure about how serialization works just that parquet becoming a standard almost and is quite good for time series data).

**Comment by andrewm4894** [comment]
hmm:

works: 

https://london.my-netdata.io/api/v1/data?chart=system.cpu&before=0&after=-600&format=csv

does not work:

https://london.my-netdata.io/api/v1/data?chart=system.*&before=0&after=-600&format=csv

**Comment by andrewm4894** [comment]
@ktsaou this seems to now work:

https://london.my-netdata.io/api/v1/data?chart=apps.*&before=0&after=-600&format=csv

One small issue is that the `labels` are no longer unique so ideally we could maybe have a new option to set something like `options=label_full_name` and then have labels be `<chart_context>|<chart_id>.<dim_name>` or something more sensible
