### ISSUE TITLE
[Bug]: plugin PROC[diskspace] cannot handle mount points with non-English charaters

### ISSUE THREAD

**Issue by Forza-tng** [netdata/netdata#14055]
### Bug description

The `diskspace` plugin fails to read the full path to a mount-point in a path containing the Swedish letter `ä`.

The error logged is
```
2022-11-28 11:17:06: netdata ERROR : PLUGIN[diskspace] : DISKSPACE: Cannot stat() mount point '/media/m' (disk '_media_m', filesystem 'nfs4', root '/'). (errno 2, No such file or directory)
```
There are two NFS mounts in the path `/media/mätrum/`, but netdata doesn't see them because it can't properly parse the `ä` character.

### Expected behavior

No errors logged.

### Steps to reproduce

1. Install netdata
2. create some mount points with non-ascii characters in the path (such as `å`, `ä`, `ö`)
3. run netdata
...

### Installation method

from git

### System info

```shell
#uname -a
Linux Ubuntu 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
(did also try with en_GB.UTF-8)
```

### Netdata build info

```shell
# /opt/netdata/usr/sbin/netdata -W buildinfo
Version: netdata v1.36.0-385-nightly
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-lto' '--enable-ml' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Ubuntu Server 22.04 LTS without GUI

**Comment by thiagoftsm** [comment]
Hello @Forza-tng ,

Thank you for more one report.
I created an environment to replicate this issue :

```sh
bash-5.2# dd if=/dev/zero of=/tmp/dev_ext4 bs=1024 count=256000
256000+0 records in
256000+0 records out
262144000 bytes (262 MB, 250 MiB) copied, 0.634124 s, 413 MB/s
bash-5.2# mkdir /tmp/mätrum/
bash-5.2# ls -lh /tmp/mätrum/
total 0
bash-5.2# mkfs.ext4 /tmp/dev_ext4 
mke2fs 1.46.5 (30-Dec-2021)
64-bit filesystem support is not enabled.  The larger fields afforded by this feature enable full-strength checksumming.  Pass -O 64bit to rectify.
Discarding device blocks: done                            
Creating filesystem with 256000 1k blocks and 64000 inodes
Filesystem UUID: 22244cd7-e219-4c0a-9b6e-99c083d405c9
Superblock backups stored on blocks: 
        8193, 24577, 40961, 57345, 73729, 204801, 221185

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done 

bash-5.2# mount /tmp/dev_ext4 /tmp/mätrum
bash-5.2# cat /proc/1/mountinfo | grep trum
74 26 7:0 / /tmp/mätrum rw,relatime - ext4 /dev/loop0 rw
```

and I had success to replicate it. Today I am busy with another collector, but I already observed the following: 

1. The function responsible to parse the line with UTF8 characters is called at this line https://github.com/netdata/netdata/blob/0c6181523125a4d73113c8664ed07b7dd39dd4c3/collectors/proc.plugin/proc_self_mountinfo.c#L271
2.  As you can see the functions has as argument with another function [call](https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_self_mountinfo.c#L144-L145) that duplicates the string .
3. When we call [strdupz](https://github.com/netdata/netdata/blob/0c6181523125a4d73113c8664ed07b7dd39dd4c3/libnetdata/libnetdata.h#L311-L331). Independent of the version we use ( [simpler](https://github.com/netdata/netdata/blob/0c6181523125a4d73113c8664ed07b7dd39dd4c3/libnetdata/libnetdata.c#L397-L401) or [with monitoring](https://github.com/netdata/netdata/blob/0c6181523125a4d73113c8664ed07b7dd39dd4c3/libnetdata/libnetdata.c#L295-L316) ]. We are assuming users were only using `ASCII` character. 

We apologize for the issue, and we will bring a solution ASAP.

**Comment by Forza-tng** [comment]
That was quick :) Thank you for explaining the issue too. It's not an urgent issue, and it is easy enough to make another mount using only US-ASCII paths.

**Comment by thiagoftsm** [comment]
All right @Forza-tng .
As soon I have an update I will bring it here.

**Comment by ilyam8** [comment]
@thiagoftsm do you plan to fix this issue?

**Comment by thiagoftsm** [comment]
Hello @ilyam8 ,

I talked with @stelfrag about this issue and we detected that a quick fix would not be enough. It is necessary to do some internal changes before I fix this issue.

@stelfrag do you have updates for us?

Best regards!

**Comment by ilyam8** [comment]
@thiagoftsm it’s been 1.5 year, any updates? What internal changes were you referring to?

**Comment by thiagoftsm** [comment]
> @thiagoftsm it’s been 1.5 year, any updates? What internal changes were you referring to?

The way we were storing the names. To store non-English characters, we cannot work only with ASCII, it is necessary to accept at least UTF-8. This is what I remember after to read again the issue.

**Comment by ilyam8** [comment]
Sorry, I don't understand your response - what do you mean by "storing the names"? What names? Storing where?

I see that the issue problem is in the profile parser

https://github.com/netdata/netdata/blob/0ee154f554d7d5640268dd4b8ad27f9752af0098/src/libnetdata/procfile/procfile.c#L333-L345


> /media/mätrum/

We treat `ä` as a separator.

If we update the code to

```c
else if(unlikely(isspace(i) || (!isprint(i) && !IS_UTF8_BYTE(i))))
```

we will be able to collect that mount point. But the next problem is sanitizing the chart ID - all non-ASCII characters are replaced with "_".
