### ISSUE TITLE
[Feat]: Windows services should be displayed under the service name, not under WMI

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#14050]
### Problem

Currently, all windows services monitored by Netdata (using WMI collector) all show up under WMI section in TOC. 

This is not ideal - an application or service being monitored should be listed under its own section. 

### Description

There are multiple problems of clubbing everything windows related under WMI. 

1. The current limitation in terms of nested sections means that some of the services (Eg: SQL Server) which have dozens of metrics have no separation at all and user has to scroll endlessly to find the metric they are looking for. Not a good user experience. 

2. As a windows admin, if I want to monitor SQL server or Active Directory or IIS - I expect there to be a section under than name where the metrics will be visualized. "WMI" does not mean a lot to me as it's just a way to query the metrics. 

The collector itself can remain just the one WMI collector, as long as on the Netdata UI the metrics are organized under the true services.

### Importance

must have

### Value proposition

1. Improved usability for Windows users

### Proposed implementation

Have a generic "Windows" section where the basic metrics from the Windows system are shown (disk, cpu, memory, apps etc)

For each of the other "services" that Netdata monitors using WMI list the metrics under a separate "service" section. Eg:
- MS SQL server
- IIS 
- Active Directory
- MS Exchange
- .NET framework

**Comment by thiagoftsm** [comment]
I will proceed with the working I am doing now with AD, and we finish it (I am missing two PRs), I will reorganize menus before to work with MS Exchange and .NET framework.
