### ISSUE TITLE
[Bug]: python.d/springboot && go.d/springboot2 - cannot be used

### ISSUE THREAD

**Issue by slyrack0** [netdata/netdata#14071]
### Bug description

I have a need to output metrics from the springboot software, but it is impossible to do it normally due to the lack of a normal implementation of springboot plugins (go.d and python.d).

**The problem with python.d/springboot** is that it needs python2, which in turn is not installed when installing netdata, which in turn requires additional configuration and further troubleshooting.
Python2 required by [this line](https://github.com/netdata/netdata/blob/ceec247bdd442a04609672c78d175b52a6d6b1ca/collectors/python.d.plugin/springboot/springboot.chart.py#L107) `data.iteritems()` - this method removed in python3.

**The problem with go.d/springboot2** is that it has no way to add custom charts at all. It is possible to display only the default metrics there and it works great, but it doesn't make sense.
[hardcoded go.d/springboot2 charts](https://github.com/netdata/go.d.plugin/blob/8993f650fc9361fd6fe09167d8bd90b87d587f66/modules/springboot2/springboot2.go#L52)

### Expected behavior

python.d/springboot migration on python3.
go.d/springboot2 implement of custom charts. 

### Steps to reproduce

not need

### Installation method

kickstart.sh

### System info

```shell
not need
```

### Netdata build info

```shell
not need
```

### Additional info

I apologize, the text was translated by google translate

**Comment by ilyam8** [comment]
Hi. Can you share an example of custom metrics?

**Comment by slyrack0** [comment]
> Hi. Can you share an example of custom metrics?

In java code or prometheus ?
Java variant:
```java
@Component
public class TestMetric {
    @Autowired
    private MeterRegistry meterRegistry;

    @PostConstruct
    public void register() {
        Gauge.builder("test.random.double", () -> ThreadLocalRandom.current().nextDouble())
                .tag("version", "v1")
                .description("Just random double")
                .register(meterRegistry);
    }
}
```

Prometheus variant:
```
# HELP test_random_double Just random double
# TYPE test_random_double gauge
test_random_double{version="v1",} 0.17517636271756964
```



In general, it would be great if the plugin itself parsed the additional charts, but I don't know how possible that is.
But it would be enough to be able to add them manually, as in python.d/springboot.

**Comment by ilyam8** [comment]
Hey, @slyrack0. Are you using nightly releases? If yes, consider using the [prometheus collector](https://github.com/netdata/go.d.plugin/tree/master/modules/prometheus#prometheus-endpoint-monitoring-with-netdata), it creates a [chart per time series](https://github.com/netdata/go.d.plugin/tree/master/modules/prometheus#time-series-grouping).

**Comment by ilyam8** [comment]
Closing because using prometheus collector is the way to go for custom metrics. The same issue was [addressed on the forum](https://community.netdata.cloud/t/springboot-metrics-data-does-not-appear-for-actuator-prometheus-endpoint/3634/4).
