### ISSUE TITLE
[Bug]: Graphite-Exporter does not work since v1.37.0

### ISSUE THREAD

**Issue by lukas-fichtner** [netdata/netdata#14084]
### Bug description

Since the last update, the graphite exporter no longer works for me.
I have a cronjob that checks daily for Netdata updates and installs them accordingly, yesterday morning it installed the update v1.37.0 and since then nothing works.

![grafik](https://user-images.githubusercontent.com/25111629/205376137-321c8dad-f044-4c85-a011-e7b32cfcebcf.png)
![grafik](https://user-images.githubusercontent.com/25111629/205376358-8c483458-56a7-4b8e-bff2-f41a977c6cf3.png)

It looks like the format has changed. I am not sure if this is intentional. 
Data from v1.37:
![grafik](https://user-images.githubusercontent.com/25111629/205445258-ef48df6b-2d71-413e-8be2-8dc9254aaf5a.png)

Data from v1.36:
![grafik](https://user-images.githubusercontent.com/25111629/205445133-ebc2063c-f1a2-483f-bd96-d563a227657a.png)

After downgrading to v1.36.1 everything works as it should again.

### Steps to reproduce

1. update to v1.37
2. watch with "nc -v -l -p 2003"

### Installation method

kickstart.sh

### System info

```shell
Linux pve 5.15.35-1-pve #1 SMP PVE 5.15.35-2 (Thu, 05 May 2022 13:54:35 +0200) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.37.0
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-cloud' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO (by user request)
    ACLK:                       NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by thiagoftsm** [comment]
Hello @lukas-fichtner ,

I tried to replicate the issue that you are reporting using latest Graphite docker image, but on my environment I had data exported, on the other hand, I observed that I am not sending names to `Graphite` independent to have or not `send names instead of ids = yes`, all my metrics are appearing inside `_target`.  Did you also have some unexpected data inside your `Metrics`?

Best regards!

**Comment by thiagoftsm** [comment]
Another thing that came in my mind right now, did you have any alert saying that exporting is failing to send data? Or that exporting is exporting a small rate of metrics?

**Comment by lukas-fichtner** [comment]
Hi @thiagoftsm :)

As described, I use the Netdata Graphite Exporter. On the other hand, I save to Influxdb with Graphite enabled.
I recorded the metrics described in the screenshot above on the Influxdb Server side using netcat. The differences between the received data from Netdata Graphite Exporter version 1.37 and version 1.36.1 are clearly visible. I did not include more data in the screenshot, because the schema is always the same.

I noticed the failure of metrics due to Grafana alerts. The data did reach Influxdb with v1.37, but apparently could not be saved due to the invalid format.

**Comment by thiagoftsm** [comment]
Thank you for additional information @lukas-fichtner !
Are you using Influx with TLS enabled?
I will try to recreate  the whole scenario described by you.

**Comment by lukas-fichtner** [comment]
InfluxDB actually has nothing to do with the problem. I recorded and compared the data above in the screenshots via netcat.
Nevertheless here is my InfluxDB Graphite Config:
```
[[graphite]]
  enabled = true
  database = "pve"
  bind-address = ":2003"
  protocol = "tcp"
```
With TLS enabled you probably mean the connection between InfluxDB and Grafana, but it actually has nothing to do with the problem, because the data is already sent by the Netdata exporter in a different or, as far as I know, wrong Graphite format.

This is my configuration on the Netdata side (exporting.conf):
```
[graphite:my_graphite_instance]
    enabled = yes
    type = graphite
    destination = x.x.x.x:2003
    data source = average
    prefix = Netdata
    hostname = pve.xxx.xxx
    update every = 10
    buffer on failures = 10
    timeout ms = 20000
    send names instead of ids = yes
```
I hope I was able to provide all missing information, if not just tag me again :) @thiagoftsm

**Comment by ilyam8** [comment]
The change was added in https://github.com/netdata/netdata/pull/13784.

Both `_is_ephemeral` and `_has_unstable_connection` labels src is config (RRDLABEL_SRC_CONFIG) and as the result, they get exported by default. The format is [correct](https://graphite.readthedocs.io/en/latest/tags.html#carbon)

> my.series;tag1=value1;tag2=value2

Not sure why exporting is broken then. Anyway, those labels two shouldn't be exported.

**Comment by ilyam8** [comment]
@lukas-fichtner a quick fix is to uncomment and set `send configured labels` to `no` in `exporting.conf`.

**Comment by thiagoftsm** [comment]
Thank you @lukas-fichtner ,

You added everything I need to check what is happening.
Also, please, take a look in [this](https://github.com/netdata/netdata/issues/14084#issuecomment-1341349846) comment.
