### ISSUE TITLE
[Feat]: expanded fping alerting

### ISSUE THREAD

**Issue by brettowe** [netdata/netdata#14083]
### Problem

Currently the fping plugin uses the collection of targets to ping and use that as a determination on if the host where the netdata daemon is hosted is loosing connectivity.

### Description

it needs to be expanded so one could provide a list of hosts/IPs that it alerts that those hosts/IPs are down and which one, instead of assuming the netdata host itself is offline/failing
to make this more descriptive the groups of hosts/IPs likely could use a name/short description variable to alert with

### Importance

really want

### Value proposition

1. Would allow for monitoring primary or secondary internet paths to know if that is failed/failing.
2. Also allows for monitoring devices/hosts external to the netdata node to alert when they stop responding to cover items that would only be noticed if the netdata node stops uploading data to the cloud (assuming cloud connection is used, and the internet path is working)
3. Gives more useful alerting as one can have a better idea of what has failed at a glance rather than having to review data of the node first.

**Comment by ilyam8** [comment]
Hi, @brettowe. Thanks for the request, but it's not clear to me what changes you want (the alalrms, or ping collector or both).

Can you please provide more examples or reword your request?

**Comment by brettowe** [comment]
lets say you have 3 IPs in the fping configuration of the current setup.
if you have 1 IP stop responding netdata alerts that itself is having issues, with no mention of what IP dropped.
Instead I want to see an option that would allow for better alerting.
so if that 1 IP stops responding the alert could say for example internet path degraded because "short name variable" is seeing 100% packet loss. 
the reason for "short name variable" is to allow for better ideas of what an alert means without having to refer to documentation as much, not everyone can memorize IPs and what they might mean (which is going to be worse off with the IPv6 address space) nor do all IPs always have a useful dns entry associated to them.

so another alerting group could be setup for devices with multi-home paths one could alert that part of the redundancy has been lost or degraded.

and another alerting group would want say individual IPs could given so you could alert when that IP (device) has gone offline.
so in this case you would have a group of IPs but each one is treated as a separate issue. where as the internet path example you would treat the group of IPs as a single idea and alert under the group's idea

**Comment by ilyam8** [comment]
> if you have 1 IP stop responding netdata alerts that itself is having issues, with no mention of what IP dropped.

We deprecate the fping plugin in favor of [go.d/ping](https://github.com/netdata/go.d.plugin/tree/master/modules/ping#ping-monitoring-with-netdata). It does the same job, but produces charts with 'host' label which we use in the alarms info line.

https://github.com/netdata/netdata/blob/c12b72e8af6d3e880327ef7e91d51011de52296f/health/health.d/ping.conf#L32

The `$label:host` part will be replaced with the actual host, e.g.:

> packet loss percentage to the network host 192.0.2.1 over the last 10 minutes
