### ISSUE TITLE
[Feat]: Extend the configuration to allow setting multiple OIDs

### ISSUE THREAD

**Issue by BigPines** [netdata/netdata#14096]
### Problem

I need to track the sum of SNMP In and Out OID data.

### Description

I need to be able to sum the value of two OIDs and display the total on a graph.

### Importance

really want

### Value proposition

Due to data caps or other throughput limitations, it is sometimes necessary to monitor data moving in both directions summed together (in and out). This solves that problem.

### Proposed implementation

Extend the configuration to allow multiple OIDs which will be summed:

dimensions:
name: “TotalTraffic”
oids: 
  - “1.3.6.1.2.1.2.2.1.10.3”
  - "1.3.6.1.2.1.2.2.1.16.3"

**Comment by ilyam8** [comment]
> I need to be able to sum the value of two OIDs and display the total on a graph.

Netdata's UI allows to do it by changing "Group by" to
