### ISSUE TITLE
[Feat]: support for Broadcom (ex LSI, ex Avago) RAID/HBA controllers (storcli)

### ISSUE THREAD

**Issue by k0ste** [netdata/netdata#14097]
### Problem

Currently, `netdata` support only MegaCli

### Description

MegaCli seems outdated, last release that I can find from 2014...
Current tool for all Broadcom RAID/HBA is [storcli](https://docs.broadcom.com/docs-and-downloads/host-bus-adapters/host-bus-adapters-common-files/sas_sata_nvme_12g_p25/STORCLI_SAS3.5_P25.zip)

### Importance

must have

### Value proposition

1. User have installed LSI/Broadcom HBA or RAID controller
2. User have monitoring of controller card

### Proposed implementation

`./storcli64 show nolog` - for get controllers
`./storcli64 /c0 show all nolog` - for get all controller info, easy to parse: drives, enclosures, temperature

The output for various vendor controllers:
[PERCH330Adapter.log](https://github.com/netdata/netdata/files/10174411/PERCH330Adapter.log)
[PERCH330Mini.log](https://github.com/netdata/netdata/files/10174412/PERCH330Mini.log)
[QS3216.log](https://github.com/netdata/netdata/files/10174413/QS3216.log)
[ROMB-QS-3516B.log](https://github.com/netdata/netdata/files/10174414/ROMB-QS-3516B.log)

**Comment by ilyam8** [comment]
Hi, @k0ste.

- Does it support JSON formatted output? If yes, then it really easy to parse.
- Needed permissions?

I did a [quick googling](https://www.thomas-krenn.com/en/wiki/StorCLI_commands#Information_on_the_Controller_and_Configuration):
 - `sudo storcli /cx show all`: information on the Controller and Configuration.
 - `sudo storcli /cx /eall /sall show all`:information on the existing hard drives and their status.
 - `sudo storcli /cx /vall show all`: information on the existing virtual drives and their status.

More questions:
 - Is `x` stands for a controller number? So `show nolog` is needed to get all controllers (IDs).
 - This seems to be the [official doc](https://docs.broadcom.com/doc/12352476). It is from 2013 and I couldn't find (CTRL-F) anything about what `nolog` is.

**Comment by k0ste** [comment]
> Does it support JSON formatted output? If yes, then it really easy to parse.

Ha-ha. It's enterprise! 😈

> Needed permissions?

Yes.

> Does x stand for a controller number? So show nolog is needed to get all controllers (IDs).

Yes, and the first controller is `zero`, in our internal firmware upgrade tool the function look like this:

```shell
function get_device_count() {
  local device_count

  if ! device_count="$(${VENDOR_BIN} show | \
    gawk 'match ($0, /^(Number of Controllers\s=\s)([0-9])$/, a) {print a[2]}')"
    then
      echo -e "${YELLOW}Failed to get ${VENDOR} controllers count${RESET}"
      exit 1
  else
      echo "${device_count}"
  fi
}


function outdated_firmware() {
  local device_count
  local device
  local device_model
  device_count="$(get_device_count)"

  if [[ "${device_count}" -gt 0 ]]
    then
      DEVICES=()
      # lower device count, because storcli device id starts from zero
      for device in $(seq 0 "$(( device_count - 1))")
        do
          device_model="$(get_device_model "${device}")"
          if check_device_firmware_version "${device}" "${device_model}"
            then
              DEVICES+=("${device}")
          fi
        done
    else
      echo -e "No ${VENDOR} controllers found"
      exit 0
  fi
}
```

> This seems to be the [official doc](https://docs.broadcom.com/doc/12352476). It is from 2013 and I couldn't find (CTRL-F) anything about what nolog is.

By default, without `nolog`, `storcli` will print all queries to `storcli.log`:

```
Note:
     1. Use 'page[=x]'as the last option in all the commands to set the page break.
        X=lines per page. E.g. 'storcli help page=10'
     2. Use 'nolog' option to disable debug logging. E.g. 'storcli show nolog'
```

**Comment by k0ste** [comment]
OMG!!!
In [libstorage](https://github.com/libstorage/libstoragemgmt/blob/ae05fe28d997cd941607dc4f4bccf5c9e8355af0/plugin/megaraid_plugin/megaraid.py#L435) I found that possible to set `J` flag for JSON formatting 🤩

```bash
[root@host]# ./storcli64 /c0 show all nolog J | jq '.Controllers[]."Response Data".HwCfg."Ctrl temperature(Degree Celsius)"'
45
```
🔝

**Comment by k0ste** [comment]
The data of JSON output
[show.json.txt](https://github.com/netdata/netdata/files/10175631/show.json.txt)
[c0_show_all.json.txt](https://github.com/netdata/netdata/files/10175630/c0_show_all.json.txt)

**Comment by ilyam8** [comment]
Hey, @k0ste. I plan to implement this. Can you please share

```bash
storcli64 /cALL show all J
```

and for MegaRAID controllers

```bash
storcli64 /cALL/eALL/sALL show all J
```

I see https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/master/storcli.py uses these 2 commands

**Comment by k0ste** [comment]
> Hey, @k0ste. I plan to implement this. Can you please share

It seems that @bocmanpy is already working on this as part of our contribution to netdata

**Comment by ilyam8** [comment]
I recently moved [adaptec (arrconf)](https://github.com/netdata/netdata/pull/17428) and [megacli](https://github.com/netdata/netdata/pull/17410) to go.

- storecli should be a go.d module.
- it is likely we will need to update [ndsudo](https://github.com/netdata/netdata/blob/master/src/collectors/plugins.d/ndsudo.c)

A user on Discord shared the output of those 2 commands with me. I will add an initial version tomorrow and you guys can improve/update it (PRs) when you have time.

**Comment by ilyam8** [comment]
Added initial version in #17454. I will add more metrics and alarms by Monday.
