### ISSUE TITLE
[Bug]: filecheck plugin chart variable backwards incompatible change?

### ISSUE THREAD

**Issue by solution-al** [netdata/netdata#14098]
### Bug description

We have running multiple netdata versions on different servers. On one server we have netdata v1.36.1 and another server we have v1.37.0. We have created a `filecheck` plugin alarm configuration for the version 1.36.1, which works as expected, but it stopped working with 1.37.0. The reason seems to be that chart variable names have changed and there is no clear way to specify new variables in alarm configuration.

For example, if `filecheck` plugin has a configuration for file path `/tmp/foo` then in v1.36.1 among chart variables will be a variable in format `_tmp_foo` where forward-slash characters are being replaced with an underscore. This can be accessed in alarm configuration as `$_tmp_foo`. However, with v1.37.0 the variable name is `/tmp/foo` and we cannot find a way to access that variable inside alarm configuration since `$/tmp/foo` does not work (there is an `has unparse-able expression` error in netdata error log).

Is there a way to access these variables with a new format?

### Expected behavior

Variable format should not be changed in a backwards incompatible way causing problems.

### Steps to reproduce

Use `filecheck` plugin and create an alarm for some file.

For example in `/etc/netdata/health.d/filecheck.conf`:
```
template: filecheck_tmp_foo_file_existence
      on: filecheck.file_existence
    calc: $/tmp/foo # how should this variable be referenced?
   every: 10s
    crit: $this != 1
    info: check existence of file
      to: webmaster
```

And in `/etc/netdata/go.d/filecheck.conf`:
```
jobs:
 - name: tmp-foo-file
   files:
     include:
       - '/tmp/backup-restoration-success-file'
```

### Installation method

kickstart.sh

### System info

```shell
Linux local 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Version: netdata v1.37.0
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
Hi, @solution-al. Thanks for reporting the problem. I confirm it, get [failed to parse expression error](https://github.com/netdata/netdata/blob/6a232de18b37c725143b5558c65c7ca7393b57aa/libnetdata/eval/eval.c#L1123-L1127) when using `$/path/to/file1`:

> 2022-12-07 12:07:01: netdata ERROR : HEALTH[pve-deb-work] : failed to parse expression '$/path/to/file1': remaining characters after expression at character 1 (i.e.: '$/path/to/file1'). (errno 17, File exists)

The fix is using the `${name}` syntax. The following alarm works for me:

```yaml
template: filecheck_tmp_foo_file_existence
      on: filecheck.file_existence
    calc: ${/path/to/file1}
   every: 10s
    crit: $this != 1
    info: check existence of file
      to: webmaster
```

<details>
<summary>screenshot</summary>

<img width="1097" alt="Screenshot 2022-12-07 at 12 29 43" src="https://user-images.githubusercontent.com/22274335/206155173-8480d545-19e6-456f-a72e-c1246894b9ae.png">

</details>
