### ISSUE TITLE
[Bug]: /tmp/netdata-kickstart.sh: 2251: shift: can't shift that many

### ISSUE THREAD

**Issue by hempy351** [netdata/netdata#14106]
### Bug description

After removing an old version (trying to update - didn't work, then tried to reinstall - didn't work either), I went to go and install the current version and I get the message "/tmp/netdata-kickstart.sh: 2251: shift: can't shift that many"

### Expected behavior

Expected to have the script run without errors.

### Steps to reproduce

1. netdata -W buildinfo | grep 'Install type:'
 (Install type: binpkg-deb)
2. apt install netdata
 (installs version 1.37.0.24-nightly)
3. apt remove netdata
 (removes netdata)
4. Run the wget netdata-kickstart.sh command with --install-prefix
5. Errored out
...

### Installation method

kickstart.sh

### System info

```shell
Linux warthog 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Last agent installed was netdata (1.37.0-24-nightly)
```

**Comment by ilyam8** [comment]
Hi, @hempy351.

> wget netdata-kickstart.sh command with --install-prefix

Did you add the prefix?

I get the same problem when I don't set the prefix

```bash
pve-deb-work ~ $ sudo ./kickstart.sh --build-only --install-prefix

./kickstart.sh: 2251: shift: can't shift that many
 ERROR  Installer exited unexpectedly (0-)
```

Not problem when

```bash
sudo ./kickstart.sh --build-only --install-prefix /opt
```

**Comment by hempy351** [comment]
When I try the --install prefix, I get the error “--install flag is deprecated and will be removed in a future version. Please use the --install-prefix instead.



Typing in “sudo ./kickstart.sh --build-only --install-prefix /opt” works, but it still shows the version being 1.37.0.24-nightly and it still ends up with the ‘binpkg-deb’ Install Type.

**Comment by ilyam8** [comment]
> Typing in “sudo ./kickstart.sh --build-only --install-prefix /opt” works

Great, so "2251: shift: can't shift that many" is _fixed_.

>  the version being 1.37.0.24-nightly

That is the current latest version.

> still ends up with the ‘binpkg-deb’ Install Type.

Can't reproduce. I get "Install type: kickstart-build" with  `--build-only --install-prefix /opt`. I suggest opening a new issue.
