### ISSUE TITLE
[Feat]: Ability to Aggregate Across Time in Chart

### ISSUE THREAD

**Issue by BigPines** [netdata/netdata#14102]
### Problem

I have a use case where I need to calculate the total bandwidth utilized on a gateway via SNMP over different times like daily, monthly, etc.

### Description

I would like to see a setting on the chart that would aggregate a dimension across time. We should be able to see the total value of all data points in the timeframe specified for that dimension.

### Importance

must have

### Value proposition

This would make Netdata much more valuable in certain use cases like monitoring data caps and verifying ISP billing.

Per Christopher_Akritid1, this a very common request, especially for network BW and number of requests.

### Proposed implementation

The chart should have an option to select aggregation across time or (sum of time period). This total should be displayed somewhere on the chart.

**Comment by andrewm4894** [comment]
Could also possibley be related to a feature request i rasied recently: https://github.com/netdata/netdata-cloud/issues/657

**Comment by cakrit** [comment]
Yes, they are very similar. @ktsaou mentioned the need to show the "Volume" in a highlighted area today, which is also related to these two.

**Comment by ilyam8** [comment]
Closing in favour of #18612
