### ISSUE TITLE
[Bug]: Docker Container Fails to Start with Read-Only Config Mount

### ISSUE THREAD

**Issue by owine** [netdata/netdata#14103]
### Bug description

https://github.com/netdata/netdata/commit/56e22c16e8de8ae63f58bca359351e6f10c15af5#commitcomment-92314474

Using a `:ro` bind mount of `/etc/netdata` in a Docker container no longer allows the container to start following the above update. The below logs are observed.

```
Creating docker group 1001
addgroup: group 'docker' in use
Could not add group docker with ID 1001, its already there probably
Assign netdata user to docker group 1001
/usr/sbin/run.sh: line 53: /etc/netdata/.container-hostname: Read-only file system
```

### Expected behavior

Docker container starts correctly

### Steps to reproduce

1. Provision container per https://learn.netdata.cloud/docs/agent/packaging/docker#host-editable-configuration with `/etc/netdata:ro` bind mount
2. Start container
3. Observe errors and container restart loop

### Installation method

docker

### System info

```shell
Linux owine 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Unable to provide as container will not start
```

### Additional info

Simply omitting `:ro` from the bind mount allows the container to function as expected, but this conflicts with the documentation.

**Comment by ilyam8** [comment]
Thanks for reporting the issue. Fixed in #14104.
