### ISSUE TITLE
[Bug]: postgres module in go.d plugin check wrong variable

### ISSUE THREAD

**Issue by agrimal** [netdata/netdata#14115]
### Bug description

In netdata 1.37.1, monitoring postgres 9.6 with the go.d plugin fails with the following message :
```
ERROR: column "backend_type" does not exists (SQLSTATE 42703)
```
Indeed this variable is implemented starting from postgres 10 :
- https://www.postgresql.org/docs/9.6/monitoring-stats.html -> no backend_type
- https://www.postgresql.org/docs/10/monitoring-stats.html -> backend_type

The netdata documentation says prerequisite is postgreSQL 9.4+ (https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/postgres)

This is a regression from python.d plugin.

### Expected behavior

Netdata can monitor postgres 9.6

### Steps to reproduce

Monitor postgres 9.6 with Netdata

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Ubuntu 20.04.5 LTS
Kernel 5.4.0-131-generic x86_64
```

### Netdata build info

```shell
netdata v1.37.1
```

**Comment by ilyam8** [comment]
Hi, @agrimal. You are correct, the column was [added in v10](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=fc70a4b0df38bda6a13941f1581f25fbb643c7f3). I see that [v9.6 is EOL](https://www.postgresql.org/support/versioning/), but I guess we need to fix "backend_type" issue.
