### ISSUE TITLE
[Bug]: Netdata consuming large amounts of CPU after several hours on Proxmox

### ISSUE THREAD

**Issue by nathenv** [netdata/netdata#14138]
### Bug description

We've been experiencing a sizable hit to the performance of one of our Proxmox nodes running Netdata for monitoring. After the host has been left running with a VM workload of approximately 50+ VMs, Netdata begins consuming 20% of the 256 vCPU host's capacity, every 10 seconds. 
![image](https://user-images.githubusercontent.com/59660529/207386927-a7b9a041-ea4b-4153-be3f-d5ddc6ea4fdb.png)

The issue is resolved if we restart the Netdata service on the host, and will remain in good state for several hours, until the issue reoccurs. This issue was observed on several versions of Netdata.
![image](https://user-images.githubusercontent.com/59660529/207387013-815f1cc4-6aea-4df6-9515-039fc86042ee.png)

![image](https://user-images.githubusercontent.com/59660529/207387252-53f4aefc-23f8-415c-8314-f1d0b242fb31.png)

The Specs of this host are:
Dell R7525
2x AMD EPYC 7H12 CPU
2TB Memory

### Expected behavior

Netdata should be "background noise" on a powerful host, not consuming 20% of available capacity. The performance hit of the Netdata agent is as expected when it starts and runs for several hours.

### Steps to reproduce

1. Start Netdata agent (v1.37.1) on host running Proxmox (v7.3-3)
2. Start VM workload of approximately 50 KVM-based VMs
3. Wait several hours, issue will begin to occur.
4. Issue will persist until Netdata service is restarted.
...

### Installation method

kickstart.sh

### System info

```shell
Linux bigiron-01 5.15.74-1-pve #1 SMP PVE 5.15.74-1 (Mon, 14 Nov 2022 20:17:15 +0100) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.37.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: unknown
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
Hi, @nathenv. I have a Proxmox server (7.3-3), 2x AMD EPYC 7453 with 30+ running VMs. No such issue.

Can you disable ebpf.plugin and see if that helps? I don't suggest it based on the provided screenshots, but we had a user with a similar problem, and disabling ebpf.plugin did help.

If that doesn't help, can you send me a [snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) to ilya@netdata.cloud?

**Comment by nathenv** [comment]
Hey @ilyam8, 

I've set my plugins as follows:

`[plugins]
	timex = yes
	idlejitter = no
	netdata monitoring = yes
	tc = no
	diskspace = no
	proc = yes
	cgroups = no
	enable running new plugins = yes
	check for new plugins every = 60
	slabinfo = no
	statsd = yes
	apps = no
	charts.d = yes
	ebpf = no
	fping = yes
	go.d = no
	ioping = yes
	nfacct = no
	perf = yes
	python.d = no`

I'll monitor and report back.

**Comment by thiagoftsm** [comment]
Hello @nathenv ,

Only to clarify, are you running one netdata instance per VM? 

Best regards!

**Comment by nathenv** [comment]
> 

One instance on the host itself, not on the VMs running on said host. 

Performance has been much better since disabling the ebpf plugin, continuing to monitor.

Thanks!

**Comment by thiagoftsm** [comment]
Thank you to answer @nathenv !

Due the fact you have different VMs and these VMs are requiring different resources on host, eBPF plugin was needing to use a lot of resources because we enable integration with apps by default and as consequence of this it needs to update different hash tables for each PID running.

I am on vacation, but tomorrow I will modify our documentation and disable integration with apps by default. This will allow users to have the minimum necessary information from eBPF.plugin without overload servers when they have scenarios like yours..

Best regards!
