### ISSUE TITLE
[Feat]: go.d/rabbitmq - add 'collect_queues_metrics' feature

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#14146]
### Problem

Python.d Netdata plugin has a feature of per-queue monitoring for RabbitMQ.
It's described in [collector description](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/rabbitmq), requires just one additional permission (read per queue) for monitoring user and works rather well, juts can be enabled with `collect_queues_metrics : 'yes'`.
Unfortunately, this feature is not implemented for the go.d plugin, so for per-queue monitoring only python.f plugin can be used.

### Description

Having the same functionality the python.d rabbitmq collector has would be probably sufficient.
The goal is to set an alarm notification on certain queue sizes in fact (but not overall as other queues are normally having much more messages)

### Importance

really want

### Value proposition

This and other features that are still missing on one of the plugins make both plugins needed. While most of the collectors have same features (and some collectors, like for mysql, are more advanced in go.d.plugin), this makes the necessity of running two plugins (thus additional process, additional resources) for just using features of one missing on another.

**Comment by ilyam8** [comment]
@ekexcello, hey. netdata/go.d.plugin#1047:

- adds `collect_queues_metrics` (default is no).
- adds global churn rate metrics (python version has 3 [churn rate charts](https://github.com/netdata/netdata/blob/6954b6f8885f3718f860aad07afafd453ea53eb1/collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py#L134-L155)).

---

- At the moment it is either all or nothing - I can add a queue selector/filter if needed.
- Found out that there is a [built-in Prometheus collector](https://www.rabbitmq.com/prometheus.html) since 3.8.0 and it is recommended over the (management plugin) HTTP API. I haven't checked the management plugin vs Prometheus metrics.

**Comment by ekexcello** [comment]
@ilyam8 unfortunately something still doesn't work.
With netdata 1.37.1 and go.d plugin 0.49.0 with adding
`collect_queues_metrics: yes`
to go.d/rabbitmq.conf, the queues are detected, but all the charts indicate are empty. From debug run:
```
BEGIN 'rabbitmq_local.queue_feed-refresher_vhost_/_message_count'
SET 'ready' = 0
SET 'unacknowledged' = 0
SET 'paged_out' = 0
SET 'persistent' = 0
END
```
While in the same time on the same server python.d charts for the same queue indicate there are messages in "ready" state. Rabbitmq credentials used are the same, this is not a permission problem. However, netdata doesn't log any error:
```
2023-01-10 17:02:10: go.d INFO: main[main] found '/etc/netdata/go.d/rabbitmq.conf
2023-01-10 17:02:10: go.d INFO: rabbitmq[local] check success
2023-01-10 17:02:10: go.d INFO: rabbitmq[local] started, data collection interval 1s
```
In the same time it was noticed that per-queue `...stats` contain some numbers that seems to be correct, and also global rabbitmq Messages (rabbitmq_local.messages_count) reflects correct RabbitMQ state and number of messages queued. So, only per-queue counts are not collected correctly.
Could you please advice?

**Comment by ilyam8** [comment]
@ekexcello there are problems with both vhosts and queues message stats, (I hope) fixed in netdata/go.d.plugin#1052

**Comment by ilyam8** [comment]
@ekexcello you can [test it](https://github.com/netdata/netdata/issues/14202#issuecomment-1373732901) right after the PR is merged.
