### ISSUE TITLE
[Feat]: change `https://my-netdata.io/kickstart.sh` to something like `https://get.netdata.cloud/kickstart.sh`

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#14157]
### Problem

https://my-netdata.io looks a bit unprofessional and not really like a proper netdata.cloud domain. 

We should try and replace it everywhere with something somewhere on the netdata.cloud domain to look more official. 

So users already have an aversion to downloading scripts and hosting it on https://my-netdata.io/ maybe does not help this. 

### Description

A more official or legitimate looking place from which the scripts are served. 

### Importance

really want

### Value proposition

1. 
2.
3.
...

### Proposed implementation

@Ferroin i know this is a more complex one than one might think. Just wanted to make this issue so we have one in netdata/netdata

**Comment by Ferroin** [comment]
Actually, this is, in theory, nowhere near as bad as it might sound. We would just need a new DNS entry in CloudFlare and a documentation update.

That said, this is _very_ brand-related, so it ideally needs to be discussed appropriately with marketing before we make such a change.
