### ISSUE TITLE
[Feat]: On `netdata.acklk_cloud_req_http_type` add a new dimension to track the requests for "functions"

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#14162]
### Problem

We should add a "functions" dim to the `netdata.acklk_cloud_req_http_type`. It helps understand the load being triggered for these type of requests.

Example, where functions were on auto-refresh for one node
![image](https://user-images.githubusercontent.com/82235632/208476334-b6b14e0e-8743-4d40-b0c3-3a9a6447ecec.png)

![image](https://user-images.githubusercontent.com/82235632/208476359-88339929-774b-4563-a99f-61de95053bf4.png)

### Description

_See above_ 

### Importance

nice to have

### Value proposition

1. Better understand the load on these "functions" requests

**Comment by underhood** [comment]
@hugovalente-pm great catch, thx
