### ISSUE TITLE
[Bug]: The "net" section in the cgroups container is picking the wrong / random interface name

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata#14170]
### Bug description

The net section under cgroups (container) adds a random interface to the sub-section name (probably from one of the containers).

### Expected behavior

The sub-section should only be named generically as "net".

### Steps to reproduce

1. Create multiple containers on the system with different virtual interfaces
2. Open the Cloud dashboard and look at the cgroups container section.

### Screenshots

<img width="245" alt="image" src="https://user-images.githubusercontent.com/96257330/203098975-06214466-c17c-414a-8d9d-9b3136d6bf31.png">

For example, the net eth0 section in the image should be named as "net" only - especially for cases where there are multiple virtual interfaces belonging to different containers.

### Desktop

This is agent independent.

**Comment by sashwathn** [comment]
Thanks @ilyam8 !

**Comment by ilyam8** [comment]
@sashwathn see https://github.com/netdata/netdata/pull/14174#issuecomment-1362710583
