### ISSUE TITLE
[Feat]: support `${label:name}` syntax for extracting label values in the alarm info line

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#14175]
### Problem

The [current syntax](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-info) is `$label:name`. It requires the expression to be surrounded by spaces, so any of the following don't work:

- `some text ($label:name) some text` 
- `some text $label:name1, $label:name2 some text`
- `some text datacenter=$label:datacenter, node=$label:node some text` 

### Description

Add support for `${label:name}` syntax for extracting label values in the alarm info line.

The syntax is [partially supported](https://github.com/netdata/netdata/issues/14098#issuecomment-1340725643) but not really documented.

### Importance

must have

### Value proposition

1. better alarm info line
2. less error prone

**Comment by MrZammler** [comment]
Hi Ilya, happy new year!

A couple of questions:

1) Should we also keep the old format?
2) Should we change it to ${chart_label:name} and maybe can have also host_labels ?

**Comment by ilyam8** [comment]
> Should we also keep the old format?

Up to you. As a user - I don't need it. Could be just me.

> Should we change it to ${chart_label:name} and maybe can have also host_labels ?

I think _label_ is ok.
