### ISSUE TITLE
[Bug]: Pi-hole stats fail to be collected

### ISSUE THREAD

**Issue by Isildur981** [netdata/netdata#14183]
### Bug description

Pi-hole stats aren't collected if the Pi-hole web interface password is enabled.  This appears to be caused by a recent change to the way Pi-hole implements their API as detailed in the announcement linked to below.  I edited the Pi-hole URL in the go.d/pihole.conf file to "http://127.0.0.1/admin/api.php?status&auth=", but this failed to solve the problem.  I removed the Pi-hole web interface password, changed the pihole.conf file back to its original settings, and confirmed that Netdata is now successfully collecting Pi-hole stats.  

[Upcoming changes: authentication for more API endpoints required](https://discourse.pi-hole.net/t/upcoming-changes-authentication-for-more-api-endpoints-required/59315)

### Expected behavior

I expect to be able to collect Pi-hole stats with the Pi-hole web interface password protection enabled. 

### Steps to reproduce

Install Pi-hole to version 5.14.2 and FTL to version 5.20 and restart Netdata.  

### Installation method

kickstart.sh

### System info

```shell
Linux 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.37.1
Configure options:  '--build=aarch64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/aarch64-linux-gnu' '--libexecdir=${prefix}/lib/aarch64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' '--disable-ebpf' 'build_alias=aarch64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: aarch64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
Hi, @Isildur981. Thanks for reporting the issue!

go.d/pihole does the following queries:

1. `/admin/api.php?version` (no auth).
2. `/admin/api.php?summaryRaw` (not auth).
3. `/admin/api.php?getQueryTypes&auth=xxx` (authenticated).
4. `/admin/api.php?getForwardDestinations&auth=xxx` (authenticated).

I installed 

```cmd
 pihole -v
  Pi-hole version is v5.14.2 (Latest: v5.14.2)
  AdminLTE version is v5.18 (Latest: v5.18)
  FTL version is v5.20 (Latest: v5.20)
```

Indeed, the `summaryRaw` endpoint requires authentication. `version` does not.

---

- After netdata/go.d.plugin#1037 all requests to the admin API will be authenticated (even the `version` - just in case).

- The change is scheduled to be released in a nightly release later this week (likely Friday).

- Since you are using stable release, you will need to build go.d.plugin manually.

**Comment by ilyam8** [comment]
> The change is scheduled to be released in a nightly release later this week (likely Friday).

This [PR](https://github.com/netdata/netdata/pull/14195) adds a new version of go.d.plugin (contains the pihole fix) to netdata/netdata, but I doubt that I will be able to find people to review it in the next few days.
