### ISSUE TITLE
[Feat]: elasticsearch default alert template

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#14184]
### Problem

It appeared that with switching Elasticsearch monitoring from python.d to go.d recent netdata setups are missing default health.d/elasticsearch.conf configuration.

### Description

As recent installations of netdata have go.d plugin collecting elasticsearch metrics instead of python.d, and types of variables changed with transition to new plugin, the old alarm configuration that used to work with python.d implementation silently stopped working, thus Elasticsearch "suddenly" became unmonitored. This appeared to be applicable for both gentoo (installation with portage) and debian (installation with kickstart script) setups.
As it worth an effort to create a new health.d/elasticsearch.conf from scratch, it might be very useful to ship one with netdata (or go.d plugin) installation by default.

### Importance

really want

### Value proposition

Alarms for at least following metrics are required and might be useful to have them preconfigured:
1. cluster_status (green/yellow/red, also it seems that netdata now processes this variable as non-integer (looking at [this](https://github.com/netdata/go.d.plugin/blob/master/modules/elasticsearch/metrics.go#L210) and [this](https://github.com/netdata/go.d.plugin/blob/master/modules/elasticsearch/charts.go#L456)).
2. node_indices_indexing_operations (ops per second) - this indicates node performance, should never fall to zero
3. node_indices_search_operations_time (average for last 10s, milliseconds). Normally this should not exceed 5000.

**Comment by ilyam8** [comment]
Hi, @ekexcello.

> cluster_status (green/yellow/red, also it seems that netdata now processes this variable as non-integer

It is an [integer value in the end](https://github.com/netdata/go.d.plugin/blob/2eb95bff93cefa09358c2bc3d83d99152cb4dbea/modules/elasticsearch/collect.go#L139-L150)

```go
func convertHealthStatus(status string) int64 {
	switch status {
	case "green":
		return 0
	case "yellow":
		return 1
	case "red":
		return 2
	default:
		return 2
	}
}
```

That is actually wrong because: 

- aggregation over time doesn't make sense.
- aggregation across several instances doesn't make sense.

I will change it to a dimension per status (green, yellow, red), 0/1 values, only one of them can be 1 at a time (the current active status).

**Comment by ilyam8** [comment]
@ekexcello I plan to add 1 and 3. As a non-ES user, I have a few questions:

> node_indices_indexing_operations (ops per second) - this indicates node performance, should never fall to zero

I think that is not the case for an idle ES instance. Right?

> node_indices_search_operations_time.
> Normally this should not exceed 5000

How did you get 5000? It is based on what? If based on ES documentation - please share the link, if based on your own experience with ES - can you elaborate a bit about it.

**Comment by ekexcello** [comment]
Hello.
Yes, for `node_indices_indexing_operations` - this is for the loaded ES node that all the time receives and index data. On idle this really can be zero. 

Search operation time... That's what set in our installation in fact assuming that in case average search request is finished in 5ms (measured, but this depends on load and hardware in fact), a 1000x value is critical. There's no default timeout for this parameter. Queries have socket timeout set to 30 seconds by default, so in fact reaching 1/2 of socket timeout for average search operation can be considered poor performance already...

**Comment by ilyam8** [comment]
@ekexcello, hey 🙋‍♂️

- cluster_status

[src](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html#cluster-health-api-desc)

> The cluster health status is: green, yellow or red. On the shard level, a red status indicates that the specific shard is not allocated in the cluster, yellow means that the primary shard is allocated but replicas are not, and green means that all shards are allocated. The index level status is controlled by the worst shard status. The cluster status is controlled by the worst index status.

Do we need an alarm for red status only?

- node_indices_search_operations_time

> (average for last 10s, milliseconds). Normally this should not exceed 5000.

The [chart](https://github.com/netdata/go.d.plugin/blob/fe76173bd3dc40bdb100d624dfae7768a151752e/modules/elasticsearch/charts.go#L171) has two dimensions: query and fetch.

Do you mean query + fetch time > 5s?

**Comment by ekexcello** [comment]
As for cluster state, a critical alert for "red" is for sure required.
As for "yellow", I would also add it. In case cluster is "always yellow", it means misconfiguration or some problems, while the cluster is operational. Normally it should not be yellow, so IMHO a warning on yellow state should be. For those who are lazy to configure Elasticsearch, it's always possible to comment it out.

As for node_indices_search_operations_time. Checked charts again. There was a case of disk drive misperformance and many charts built by Kibana dashboards. For over 5 minutes _node_indices_search_operations_time.query_ used to be within 0.5 - 1.5 _minutes._ _Fetch_ was about 5 seconds for ~25 seconds. Then the cluster returned to normal operation. During normal operation, _query_ is around 40ms, _fetch_ is around 0.5ms. But this is particular use case, however, it illustrates that query time can be much bigger than fetch time (in case query is waiting). Can't imagine the case when fetch is much bigger than query time.
Trying to summarize, it might be reasonable to have two alerts with different values:
* for query with warning on over 30s, no critical. This will be the case when cluster has too many parallel requests
* for fetch, with warning on 5s and critical on 30s. For the case the cluster can't either transfer the data quickly, or the value of the data is abnormally high. Doubt this should ever happen on normal cluster.
Initial configuration with (query + fetch time > 5s) is probably incorrect.

**Comment by ilyam8** [comment]
@ekexcello added in #14197 checking:

- cluster health status: yellow, red.
- index health status: (only) red.
- indices search time: query and fetch.

If you can test the alarms - that would be perfect!

**Comment by ekexcello** [comment]
Hope to test it within a couple of days

**Comment by ekexcello** [comment]
Cluster health alarm works perfectly, thank you!
