### ISSUE TITLE
[Bug]: When cross-compiling, configure tries to execute judyltablesgen on build system

### ISSUE THREAD

**Issue by nethershaw** [netdata/netdata#14185]
### Bug description

I'm trying to build netdata for an OpenWRT device (a WiFi AP) running the mipsel_24kc architecture. I am cross-compiling for mipsel on an x86_64 Gentoo Linux host. Usually not a problem.

As of 1.37.1, this happens during the configure phase:

```
make[4]: Entering directory '/home/me/Documents/git/openwrt/build_dir/target-mipsel_24kc_musl/netdata-standalone/netdata-1.37.1'
  CC       libnetdata/libjudy/src/JudyL/judyltablesgen-JudyLTablesGen.o
  CCLD     judyltablesgen
./judyltablesgen
./judyltablesgen: ./judyltablesgen: cannot execute binary file
make[4]: *** [Makefile:7850: JudyLTables.c] Error 126
```

Here, the makefile has instructed the toolchain to execute `judyltablesgen` on the build host after having instructed the toolchain to build `judyltablesgen` for the target architecture. Predictably doesn't go well.

### Expected behavior

Dependencies built to be executed on the build host should be built for the architecture of the build host, not the target host.

<rant>
Also, third-party libraries should not be bundled as a rule -- this always makes platform compatibility _harder not easier_ -- but that is a philosophical point well beyond the scope of this bug. You should probably expect this criticism from a Gentoo user; we always already have all the libraries available to build from source and we would _really rather not_ have to worry of those conflicting with your special redundant ones.
</rant>

### Steps to reproduce

1. Set up an OpenWRT build system.
2. Set up a local package feed using my [Makefile](https://github.com/netdata/netdata/files/10300898/Makefile.txt) to define the Netdata package.
3. Select a mipsel target like the Ubiquiti UniFi 6 Lite, maybe, or any target profile for which you can cross-compile whose binaries would obviously and trivially fail to execute on the build host.
4. Do `make package/netdata/compile V=sc`.
5. Realize you can probably also reproduce this by naively trying to cross-compile with any other toolchain you might have available.
6. At any rate, notice how the compiler called is the target's compiler (in my case, mipsel-openwrt-linux-musl-gcc) instead of the build host's compiler.
...

### Installation method

from source

### System info

```shell
Linux pygoscelis 5.10.156-gentoo-dist #1 SMP Wed Dec 7 14:36:01 EST 2022 x86_64 AMD Ryzen 7 2700X Eight-Core Processor AuthenticAMD GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.9
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:VERSION_ID="2.9"
```

### Netdata build info

```shell
Not built yet. Source is the v1.37.1 tag.
```

### Additional info

Where _should_ the correction be made?

Since you decided to bundle libjudy, and all the maintenance that comes with it, is it your responsibility to ensure the Makefile for libjudy calls out to the correct compiler when a cross-compiling toolchain is involved? How are _you_ building for other platforms?

Is it my responsibility, as someone who is trying to get a version of Netdata newer than 1.33 on their devices because the OpenWRT maintainers have abandoned it because _the myriad behaviors of all the bundled libraries it comes with have become impossible to manage,_ to patch out this behavior from, e.g., CMakeLists.txt or configure.ac, and diverge still further from upstream?

I don't know. I'm going to have to keep hacking at it to make progress, since I'm mostly unfamiliar with the structure of your makefiles with respect to this newly bundled library. If you can point me in the general direction of what I need to change, I'll contribute the difference back to you in a PR.

**Comment by nethershaw** [comment]
Oh hey, a build log I guess!

[compile.txt](https://github.com/netdata/netdata/files/10300986/compile.txt)

You may notice I'm applying a patch at the top. Ignore this.

It's this trivial thing:

```diff
--- a/configure.ac	2021-01-28 00:01:52.281630578 -0500
+++ b/configure.ac	2021-01-28 03:15:15.739835665 -0500
@@ -5,9 +5,7 @@
 AC_PREREQ(2.60)
 
 # We do not use m4_esyscmd_s to support older autoconf.
-define([VERSION_STRING], m4_esyscmd([git describe 2>/dev/null | tr -d '\n']))
-define([VERSION_FROM_FILE], m4_esyscmd([cat packaging/version | tr -d '\n']))
-m4_ifval(VERSION_STRING, [], [define([VERSION_STRING], VERSION_FROM_FILE)])
+define([VERSION_STRING], m4_esyscmd([cat packaging/version | tr -d '\n']))
 
 AC_INIT([netdata], VERSION_STRING[])
```

Turns out if I don't do this, Netdata (when it finally builds) will think its version is OpenWRT's version -- probably because `git describe` ends up describing the OpenWRT repository you're inside if you're using OpenWRT's build system.

**Comment by nethershaw** [comment]
Oh... for pity's sake. I see why you did this, now. Judy was no longer being maintained; its original developer never bothered to contemplate that anyone might want to cross-compile their software using any kind of standard build process, so naturally they wrote a bespoke script (_delightfully_ named `sh_build`) to have some code make a binary to make more code. Generators are fine, I guess, until someone forgets you're using one...

An original author [explains the fact of this decision](https://sourceforge.net/p/judy/mailman/message/27394308/) to a hapless developer in 2011, without justifying it, and wishes them good luck.

_Eleven years later..._

Another hapless developer tries to adapt libjudy by cross-compiling it for another embedded device, and [encounters the same problem I did yesterday](https://lists.yoctoproject.org/g/yocto/message/55821), which makes me hapless developer number three.

I'm not so familiar with CMake, and I'm seeing now that your preferred build system has shifted there, which maybe explains why 1.34.1 is the last functional netdata I was able to build for mips.

So, now I know I need to edit the CMakeLists.txt file in this repository so as to refer to a native binary produced in an earlier build phase when cross-compiling and looking for the executable it calls `judyltablesgen`. Native builds would just do what they normally do.

Which... probably looks something like this?

```diff
--- a/CMakeLists.txt    2022-12-27 02:08:26.523861392 -0500
+++ b/CMakeLists.txt    2022-12-27 02:08:06.726868044 -0500
@@ -394,8 +394,14 @@
 ADD_LIBRARY(judy STATIC
              ${LIBJUDY_SOURCES})
 
-ADD_EXECUTABLE(judyltablesgen
-    libnetdata/libjudy/src/JudyL/JudyLTablesGen.c)
+if(CMAKE_CROSSCOMPILING)
+    find_package(JudyLTablesGen)
+else()
+    ADD_EXECUTABLE(judyltablesgen
+        libnetdata/libjudy/src/JudyL/JudyLTablesGen.c)
+    export(TARGETS judyltablesgen FILE
+        "${CMAKE_BINARY_DIR}/JudyLTablesGen.cmake")
+endif()
 
 target_include_directories(judyltablesgen PUBLIC
     libnetdata/libjudy/src
```

Of course my Makefile also has to tell that initial native build of libnetdata/libjudy/src/ to happen and tell CMake where to find it, but you don't need to worry about that.

I'm not entirely sure this is the solution -- I'm still working through it -- but if you're taking up maintainership of this library, I figure someone else is eventually going to become hapless developer number four.

**Comment by vkalintiris** [comment]
> I'm not so familiar with CMake, and I'm seeing now that your preferred build system has shifted there

The preferred build system is autotools. CMake is mostly used by devs.

@underhood the right fix is to bundle the generated source files and pick the right one based on the target's word length, ie. 32/64 bits. Curious if the endianness plays a role, which would mean that we need to bundle four files in total, ie. {32,64}/{le,be}.

**Comment by Ferroin** [comment]
In addition to the above comment, the preferred method at the moment for building for a different architecture than the host system is to run the build under QEMU userspace emulation (ideally using a container if possible, as it makes this _so_ much easier to do).

We understand that this is less than ideal (believe me, it’s less than ideal for us too, because it means some parts of our CI take far longer than they really should), it’s just not been enough of a priority yet for us to fix it.

**Comment by nethershaw** [comment]
I was able to solve this problem with the following patches, which inform the build system via its makefiles of how to locate the correct compiler and build options for the JudyLTables.c target.

This has the result that the first thing built is the JudyLTables.c target _for the host_ using the host's compiler.

When compiling Netdata natively, the host and target compilers are identical and these patches make no difference.

In summary: the macro AX_PROG_CC_FOR_BUILD must be declared in configure.ac in order to populate variables e.g., CC_FOR_BUILD and BUILD_CFLAGS that are used in Makefile.am for the native compilation phase that precedes the cross phase.

```diff
--- a/configure.ac	2022-12-30 02:43:30.410957211 -0500
+++ b/configure.ac	2022-12-30 18:24:19.387495434 -0500
@@ -52,6 +52,8 @@
   AC_CHECK_TOOL([AR], [ar])
 fi
 
+AX_PROG_CC_FOR_BUILD
+
 # -----------------------------------------------------------------------------
 # configurable options
 
```

```diff
--- a/Makefile.am	2022-12-29 19:09:13.551159986 -0500
+++ b/Makefile.am	2022-12-30 20:11:43.788596871 -0500
@@ -525,12 +525,14 @@
 noinst_PROGRAMS = judyltablesgen
 
 judyltablesgen_SOURCES = libnetdata/libjudy/src/JudyL/JudyLTablesGen.c
-judyltablesgen_CFLAGS = $(LIBJUDY_CFLAGS) -DJUDYL -I$(abs_top_srcdir)/libnetdata/libjudy/src -I$(abs_top_srcdir)/libnetdata/libjudy/src/JudyCommon -Wno-sign-compare -Wno-implicit-fallthrough
+judyltablesgen_CFLAGS = $(LIBJUDY_CFLAGS) $(BUILD_CFLAGS) -DJUDYL -I$(abs_top_srcdir)/libnetdata/libjudy/src -I$(abs_top_srcdir)/libnetdata/libjudy/src/JudyCommon -Wno-sign-compare -Wno-implicit-fallthrough -Wno-format -Wno-format-security
+judyltablesgen_LDFLAGS = $(BUILD_LDFLAGS)
 
-$(builddir)/judyltablesgen$(EXEEXT) : CFLAGS += -Wno-format -Wno-format-security
+$(builddir)/judyltablesgen$(BUILD_EXEEXT) :
+	$(CC_FOR_BUILD) $(judyltablesgen_CFLAGS) $(judyltablesgen_LDFLAGS) $(judyltablesgen_SOURCES) -o judyltablesgen$(BUILD_EXEEXT)
 
-JudyLTables.c: $(abs_top_srcdir)/libnetdata/libjudy/src/JudyL/JudyLTablesGen.c $(builddir)/judyltablesgen$(EXEEXT)
-	$(builddir)/judyltablesgen$(EXEEXT)
+JudyLTables.c: $(abs_top_srcdir)/libnetdata/libjudy/src/JudyL/JudyLTablesGen.c $(builddir)/judyltablesgen$(BUILD_EXEEXT)
+	$(builddir)/judyltablesgen$(BUILD_EXEEXT)
 
 libjudy_a-JudyLTables.$(OBJEXT) : CFLAGS += -I$(abs_top_srcdir)/libnetdata/libjudy/src/JudyL
```

**Comment by underhood** [comment]
> I was able to solve this problem with the following patches, which inform the build system via its makefiles of how to locate the correct compiler and build options for the JudyLTables.c target.
> 
> This has the result that the first thing built is the JudyLTables.c target _for the host_ using the host's compiler.
> 
> When compiling Netdata natively, the host and target compilers are identical and these patches make no difference.
> 
> In summary: the macro AX_PROG_CC_FOR_BUILD (from [Autoconf Archive](https://www.gnu.org/software/autoconf-archive/ax_prog_cc_for_build.html)) must be declared in configure.ac in order to populate variables e.g., CC_FOR_BUILD and BUILD_CFLAGS that are used in Makefile.am for the native compilation phase that precedes the cross phase.
> 
> ```diff
> --- a/configure.ac	2022-12-30 02:43:30.410957211 -0500
> +++ b/configure.ac	2022-12-30 18:24:19.387495434 -0500
> @@ -52,6 +52,8 @@
>    AC_CHECK_TOOL([AR], [ar])
>  fi
>  
> +AX_PROG_CC_FOR_BUILD
> +
>  # -----------------------------------------------------------------------------
>  # configurable options
>  
> ```
> 
> ```diff
> --- a/Makefile.am	2022-12-29 19:09:13.551159986 -0500
> +++ b/Makefile.am	2022-12-30 20:11:43.788596871 -0500
> @@ -525,12 +525,14 @@
>  noinst_PROGRAMS = judyltablesgen
>  
>  judyltablesgen_SOURCES = libnetdata/libjudy/src/JudyL/JudyLTablesGen.c
> -judyltablesgen_CFLAGS = $(LIBJUDY_CFLAGS) -DJUDYL -I$(abs_top_srcdir)/libnetdata/libjudy/src -I$(abs_top_srcdir)/libnetdata/libjudy/src/JudyCommon -Wno-sign-compare -Wno-implicit-fallthrough
> +judyltablesgen_CFLAGS = $(LIBJUDY_CFLAGS) $(BUILD_CFLAGS) -DJUDYL -I$(abs_top_srcdir)/libnetdata/libjudy/src -I$(abs_top_srcdir)/libnetdata/libjudy/src/JudyCommon -Wno-sign-compare -Wno-implicit-fallthrough -Wno-format -Wno-format-security
> +judyltablesgen_LDFLAGS = $(BUILD_LDFLAGS)
>  
> -$(builddir)/judyltablesgen$(EXEEXT) : CFLAGS += -Wno-format -Wno-format-security
> +$(builddir)/judyltablesgen$(BUILD_EXEEXT) :
> +	$(CC_FOR_BUILD) $(judyltablesgen_CFLAGS) $(judyltablesgen_LDFLAGS) $(judyltablesgen_SOURCES) -o judyltablesgen$(BUILD_EXEEXT)
>  
> -JudyLTables.c: $(abs_top_srcdir)/libnetdata/libjudy/src/JudyL/JudyLTablesGen.c $(builddir)/judyltablesgen$(EXEEXT)
> -	$(builddir)/judyltablesgen$(EXEEXT)
> +JudyLTables.c: $(abs_top_srcdir)/libnetdata/libjudy/src/JudyL/JudyLTablesGen.c $(builddir)/judyltablesgen$(BUILD_EXEEXT)
> +	$(builddir)/judyltablesgen$(BUILD_EXEEXT)
>  
>  libjudy_a-JudyLTables.$(OBJEXT) : CFLAGS += -I$(abs_top_srcdir)/libnetdata/libjudy/src/JudyL
> ```

@nethershaw unfortunately using `judyltables.c` generated by `judyltablesgen` built for different architecture than target might lead to crashes and data corruption.
