### ISSUE TITLE
[Bug]: 1.37.1 intermittent "Page cache invalidation failure on direct I/O.  Possible data corruption due to collision with buffered I/O!"

### ISSUE THREAD

**Issue by lkraav** [netdata/netdata#14205]
### Bug description

`dmesg` gets  polluted with intermittent subject errors.

```
[20380647.932157] Page cache invalidation failure on direct I/O.  Possible data corruption due to collision with buffered I/O!
[20380647.932298] IPv4: martian source 192.168.1.1 from 127.0.0.1, on dev lo
[20380647.932319] ll header: 00000000: ff ff ff ff ff ff 00 00 00 00 00 00 08 00
[20380647.932331] File: /var/cache/netdata/dbengine/datafile-1-0000020692.ndf PID: 1785156 Comm: LIBUV_WORKER
```

### Expected behavior

Error free operation.

### Steps to reproduce

Not sure what specific configuration triggers this. Looking for help in diagnosing.

### Installation method

from source

### System info

```shell
$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux gusto 5.15.38-gentoo+ #8 SMP PREEMPT Wed May 11 11:05:01 EEST 2022 x86_64 AMD Ryzen 7 5700G with Radeon Graphics AuthenticAMD GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.9
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:VERSION_ID="2.9"
/etc/system-release:Gentoo Base System release 2.9
```

### Netdata build info

```shell
$ netdata -W buildinfo
Version: netdata v1.37.1
Configure options:  '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--datarootdir=/usr/share' '--disable-dependency-tracking' '--disable-silent-rules' '--docdir=/usr/share/doc/netdata-1.37.1' '--htmldir=/usr/share/doc/netdata-1.37.1/html' '--libdir=/usr/lib64' '--localstatedir=/var' '--with-user=netdata' '--without-bundled-protobuf' '--disable-cloud' '--enable-jsonc' '--enable-plugin-cups' '--enable-dbengine' '--disable-plugin-nfacct' '--disable-plugin-freeipmi' '--disable-exporting-kinesis' '--enable-lto' '--disable-exporting-mongodb' '--disable-exporting-prometheus-remote-write' '--disable-plugin-xenstat' '--enable-x86-sse' '--with-zlib' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CFLAGS=-march=core2 -O2 -pipe -Wl,-O1 -Wl,--as-needed' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'CXXFLAGS=-march=core2 -O2 -pipe -Wl,-O1 -Wl,--as-needed' 'PKG_CONFIG_PATH=/mnt/datapool/tmp/portage/net-analyzer/netdata-1.37.1/temp/python3.9/pkgconfig'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO (by user request)
    ACLK:                       NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by MrZammler** [comment]
Hi @lkraav 

What filesystem are you using?

**Comment by lkraav** [comment]
> What filesystem are you using?

This is btrfs in RAID 1 configuration.

**Comment by MrZammler** [comment]
Hi @lkraav thanks. Reason I asked was because I saw some such errors produced from e.g. mysql under btrfs. Not sure though why, if a problem with btrfs or netdata.

**Comment by Ferroin** [comment]
@lkraav Two requests:

- Would it be possible for you to keyword your kernel package for `~amd64`, update the kernel (you should end up with 6.1.3 currently), and re-test? If that happens to get rid of the issue, then it will tell us with reasonable certainty that it’s a BTRFS issue (or at least that it’s a kernel issue, but BTRFS specifically is more likely here), which I suspect to be the case given that I’m not seeing any issues like this running Netdata 1.37.1 in a similar setup on a 6.1.2 kernel.
- Irrespective of the first point, can you share the mount options for the volume that the files you’re getting these error messages for are on? You can redact any `subvol=` or `subvolid=` options if so desired, but the BTRFS-specific stuff may be relevant here.

**Comment by lkraav** [comment]
> Would it be possible for you to keyword your kernel package for ~amd64, update the kernel (you should end up with 6.1.3 currently), and re-test?

Not possible at this time, but I might be able to upgrade to a later 5.15 branch, which perhaps also brings some btrfs updates.

> Irrespective of the first point, can you share the mount options for the volume that the files you’re getting these error messages for are on?

```sh
$ mount | grep btrfs
/dev/mapper/luks-5098533e-7c91-zzzz-yyyy-xxxxxxxxxxxx on / type btrfs (rw,noatime,ssd,space_cache,subvolid=5,subvol=/)
```

**Comment by thiagoftsm** [comment]
Hello,

An additional information about this issue, I reported few minutes ago an issue with `LIBUV_WORKER` in this [PR](https://github.com/netdata/netdata/pull/14125#issuecomment-1373825745). 

I also have `dmesg` reporting the issue:

```sh
[10903.018265] LIBUV_WORKER[7914]: segfault at 20 ip 00007fc31ddb45c0 sp 00007fc2fdd285f8 error 4 in libc-2.36.so[7fc31dd45000+16b000]
[10903.018276] Code: 48 0f 44 f0 0f 11 47 10 0f 11 07 0f 11 47 20 8b 06 8b 56 04 89 47 30 31 c0 85 d2 0f 95 c0 89 47 1c 31 c0 c3 66 0f 1f 44 00 00 <8b> 57 18 64 8b 04 25 d0 02 00 00 39 c2 0f 84 0d 01 00 00 41 54 55
```

And all errors happened when on `ext4`.

Probably there are more issues  with the thread.

**Comment by Forza-tng** [comment]
Hi.

I am also having this same issue since I upgraded netdata to nightly version the other day. Previous version I used was installed maybe 1-2 months ago. It is compiled from git sources. I can not see anything logged in netdata error.log during the time for the LIBUV dmesg errors.

```
[203293.553765] Page cache invalidation failure on direct I/O.  Possible data corruption due to collision with buffered I/O!
[203293.553768] File: /var/cache/netdata/dbengine/datafile-1-0000000436.ndf PID: 5552 Comm: LIBUV_WORKER
```

I am using Alpine Linux v3.17.1 (musl and not glibc) with kernel 6.1.6. The backing storage is a dedicated nvme disk with Btrfs filesystem.

```
# btrfs fi us /var/cache/netdata/
Overall:
    Device size:                 931.51GiB
    Device allocated:             18.02GiB
    Device unallocated:          913.49GiB
    Device missing:                  0.00B
    Device slack:                    0.00B
    Used:                         14.65GiB
    Free (estimated):            915.11GiB      (min: 458.37GiB)
    Free (statfs, df):           915.11GiB
    Data ratio:                       1.00
    Metadata ratio:                   2.00
    Global reserve:               83.06MiB      (used: 0.00B)
    Multiple profiles:                  no

Data,single: Size:16.01GiB, Used:14.39GiB (89.87%)
   /dev/nvme0n1p1         16.01GiB

Metadata,DUP: Size:1.00GiB, Used:137.47MiB (13.42%)
   /dev/nvme0n1p1          2.00GiB

System,DUP: Size:8.00MiB, Used:16.00KiB (0.20%)
   /dev/nvme0n1p1         16.00MiB

Unallocated:
   /dev/nvme0n1p1        913.49GiB
```


```
# /opt/netdata/usr/sbin/netdata -W buildinfo
Version: netdata v1.37.0-182-nightly
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-lto' '--enable-ml' '--with-bundled-protobuf' 'CFLAGS=-O3 -march=native -pipe' 'LDFLAGS=-Wl,--as-needed -Wl,-O1 -Wl,--sort-common' 'CPPFLAGS=-O3  -march=native  -pipe' 'CXXFLAGS=-O3  -march=native -pipe'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ktsaou** [comment]
I also have a Gentoo box with btrfs that logs this.

I believe the problem is that we are writing with direct I/o but we are reading with mmap (buffered)

@stelfrag please check this...

**Comment by stelfrag** [comment]
> I also have a Gentoo box with btrfs that logs this.
> 
> I believe the problem is that we are writing with direct I/o but we are reading with mmap (buffered)
> 
> @stelfrag please check this...

yes probably switch to buffered I/O for writes -- I will test this

**Comment by Forza-tng** [comment]
> yes probably switch to buffered I/O for writes -- I will test this

Buffered I/O would be much nicer for Btrfs (and ZFS) than direct_io

**Comment by Ferroin** [comment]
Oh, wow, I had not realized that we were mixing direct IO and mmap. That is almost certainly the issue here. The question is why it’s only showing up on BTRFS (and why it’s not showing up on any of my systems, despite running on essentially the same setup myself).

**Comment by Ferroin** [comment]
> > Buffered I/O would be much nicer for Btrfs (and ZFS) than direct_io
> 
> The problem with buffer I/O is that Netdata is going to pollute the system buffers with its data and we write quite frequently now (we try to spread writes across time and do very small ones - to minimize the impact on other applications).
> 
> Generally, we are trying to have as little impact as possible on other applications, so we do our own caching and prefer direct I/O.
> 
> We merged that PR. It has direct I/O for both reads and writes. Most likely it will be on tomorrows nightly.
> 
> If you still prefer buffer I/O, we could probably add an option to netdata.conf for you to choose the method you like.

We _need_ a way to disable direct I/O, period. Some systems actually have broken direct I/O, and trying to use it on those systems will _destroy the filesystem_.

**Comment by vkalintiris** [comment]
> Some systems actually have broken direct I/O, and trying to use it on those systems will destroy the filesystem.

Curious about this one, do you have any links?

**Comment by Ferroin** [comment]
> > Some systems actually have broken direct I/O, and trying to use it on those systems will destroy the filesystem.
> 
> Curious about this one, do you have any links?

Not immediately available, but this was actually an issue with early (pre-4.0 vintage) BTRFS drivers, and I’m given to understand that very early implementations of direct IO on Linux had this issue in general.

**Comment by lkraav** [comment]
1.38.0 seems to have resolved this :pray: nice work :tada:

**Comment by ktsaou** [comment]
We have added an option to disable direct I/O:

```
[db]
	dbengine use direct io = yes
```

Setting this to `no` we will use buffered I/O.
