### ISSUE TITLE
[Feat]: have ml work on any `update_every`

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#14218]
### Problem

At the moment we only have anomaly detection for charts and dims with `update_every=1`. We need to extend this to any `update_every` or even a more realistic subset like `update_every` in [1,2,5,10] (we can use telemetry to try validate what a good set would be if we need to). 

### Description

The ML algo should just work regardless of the `update_every`. There is nothing in the ML side of things that depends on update_every of 1 sec. Each feature vector is just based on previous stored values whatever the window between them actually is in terms of timestamp does not matter.

### Importance

must have

### Value proposition

1. Will increase coverage of anomaly detection a lot.
2.
3.
...

### Proposed implementation

I think @vkalintiris has thought about this and has some ideas.

**Comment by vkalintiris** [comment]
> At the moment we only have anomaly detection for charts and dims with update_every=1

Nit-picking just so that we are on the same page: ML will/should work correctly even with an update_every != 1. Currently, we skip dimensions/charts whose update_every does not match the update_every of their host.

> @vkalintiris @MrZammler do you think we can start on this in next couple of weeks?

Yes, should not be difficult to implement.

**Comment by andrewm4894** [comment]
> Nit-picking just so that we are on the same page: ML will/should work correctly even with an update_every != 1. Currently, we skip dimensions/charts whose update_every does not match the update_every of their host.
> 

Maybe I should check or test this then - if i add a collector with update every of 5 for example - you are saying that ML should pick that up? If so, i can/should test this first to be sure.

**Comment by andrewm4894** [comment]
a few hours later and i dont see any of the 10s metrics trained but most of the 1s metrics are trained. 

so @vkalintiris this looks to me like the 10s are not getting picked up by the ML in this case - is this expected or unexpected? (just not 100% sure of expected case based on [this comment](https://github.com/netdata/netdata/issues/14218#issuecomment-1396881432))

![image](https://user-images.githubusercontent.com/2178292/214083637-4068ff68-5208-4cab-95db-0e0659c1348b.png)

**Comment by andrewm4894** [comment]
@vkalintiris i believe we can close this as done in here: https://github.com/netdata/netdata/pull/14567

am i correct?

**Comment by vkalintiris** [comment]
@andrewm4894 you're right, I'm closing this one.
