### ISSUE TITLE
[Feat]: persist trained ML models to db

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#14217]
### Problem

We need to store the trained ml models used as part of anomaly detection scoring. 

### Description

Save models just that if agent restarts or crashes, as soon as it comes back up the saved models can be used against to get anomaly detection scoring as soon as possible without having to wait to retrain all models.

### Importance

must have

### Value proposition

1. will make anomaly detection capabilities much more robust to restarts, updates, crashes etc.
2.
3.
...

### Proposed implementation

Store the models somewhere in the db.

**Comment by andrewm4894** [comment]
@vkalintiris @MrZammler hey - just made this issue for tracking work and discussions ahead of getting a PR in place.

**Comment by andrewm4894** [comment]
@vkalintiris @MrZammler do you think we can start on this in next couple of weeks?

**Comment by vkalintiris** [comment]
> @vkalintiris @MrZammler do you think we can start on this in next couple of weeks?

Yes, but it will have to wait until I finish migrating the ML code from C++ to C so that other people can make contributions as well.

**Comment by andrewm4894** [comment]
@vkalintiris why are we migrating it from C++ to C - will that not make adding new ml models from dlib even more difficult?

What are main benefits of migrating? Just that will be easier for others to help maintain and develop?

**Comment by vkalintiris** [comment]
> will that not make adding new ml models from dlib even more difficult?

No, it will not make it more difficult. Thin C wrapper code can be written on top of dlib to use any functionality we want.

> What are main benefits of migrating? Just that will be easier for others to help maintain and develop?

Correct.

**Comment by andrewm4894** [comment]
@vkalintiris do you think we can make a start on this in next week or two?

**Comment by vkalintiris** [comment]
> @vkalintiris do you think we can make a start on this in next week or two?

Yes, we'll start working on this next week.

**Comment by andrewm4894** [comment]
Currently testing this draft PR for this: https://github.com/netdata/netdata/pull/14810

**Comment by andrewm4894** [comment]
Related PR to resolve one issue we missed: https://github.com/netdata/netdata/pull/14920

**Comment by andrewm4894** [comment]
Closed as complete in PR above

**Comment by andrewm4894** [comment]
Actually wait, am reopening as is one follow on PR needed to loads the models from db as soon as possible after a restart.

**Comment by andrewm4894** [comment]
@vkalintiris just double checking my understanding on this one - we have one more PR to do on this to load the models from the DB on restart don't we?

**Comment by vkalintiris** [comment]
> @vkalintiris just double checking my understanding on this one - we have one more PR to do on this to load the models from the DB on restart don't we?

Correct, I'm testing my changes and if everything's fine I'll open the PR in a little bit.

**Comment by vkalintiris** [comment]
Fixed: https://github.com/netdata/netdata/pull/14981
