### ISSUE TITLE
[Feat]: Minimize resources utilization

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#14231]
### Problem

With PR #14125 we make a big step forward to minimize the memory footprint of Netdata agent and make sane use of system resources especially when the agent runs at scale (very busy parent nodes).

The following items are my observations to make the agent better:

## Threads

When the agent serves hundreds of nodes, it still wastes a lot of memory and cpu. The problem is mainly the number of threads we spawn. Today, for each child connecting to a parent we use 6 threads:

1. receiver, to get the metrics from the children
2. sender, to push the metrics to another parent
3. health, to check for alerts
4. ACLK sync, to connect to cloud
5. ML training, to train new models
6. ML detection

With a few hundreds of nodes, each thread needs stack memory (8MB on Linux) and it contributes significantly to context switches (which can grow up to 100k per second with a few hundreds of children).

All threads except the first should be eliminated:

1. sender, is mainly idle just dispatching data to a socket - we could have only 1 sender for all children.
2. health, is also mainly idle and even if there are thousands of alarms it is quite fast and the increased latency will not affect the quality of the result.
3. ACLK sync, can also become just 1 thread for all children.
4. ML training and ML prediction per child really kills performance. Users should be able to configure how many ML threads they want to serve all the children. This is probably the most complex to accomplish, because to get the full speed of the db with a single thread, queries need to be pipelined (like replication does in PR #14125 - replication actually cannot get better speed above 5 threads - the optimal is 5 to run at about 10 million points replicated per second).

## Memory Operations

`malloc()` is fast. But at scale there is huge contention on memory operations. Millions of them happen per second. In PR #14125 we cached everything that could be cached (the "buffers" chart in "dbengine memory" section) and dbengine2 now performs a lot better even at scale, but still memory operations are made.

ML and Judy are the main offenders for memory operations now.

For ML, I have asked @vkalintiris to eliminate all allocations.
For Judy I am experimenting with an alternative that could be used in dbengine2 (https://gist.github.com/ktsaou/a08bf8a06f4808b9a223ec5960337244 - I call it July for fun... - it has the same interface as Judy, its allocations can be cached, but it can only be good when items are appended to the hashtable, like dbengine2 does - otherwise it wastes a lot of cpu).

## Streaming

Now that the replication protocol is stable, we should switch streaming to push interpolated data to parents (like replication does), instead of collected metrics. This will be a huge improvement on CPU utilization on busy parents and it does not seem a big change.

## SQLite3

We use sqlite3 to have metadata survive across netdata restarts. But sqlite3 is extremely slow for the needs of netdata. Synchronously committing or loading data from SQL should be avoided when possible.

When data in sqlite3 are only needed on netdata restart, it is probably better to commit SQL statements to a text file which we will run on netdata startup to update sqlite3. 

### Description

See above.

### Importance

must have

### Value proposition

Described above.

**Comment by MrZammler** [comment]
We can revert health to single thread. But still do the health init not during host creation as to not delay it. Will check it.

We could also change the way REMOVED health entries work. Right now we create one such REMOVED event during shutdown for every alert. We could perhaps leave the decision of creating REMOVED until next startup and only create for those alerts that are not running again on the new session.

**Comment by Ferroin** [comment]
Just an observation, but we may want to consider allowing one sender _per upstream parent_. Having a single thread covering all the children does make sense, but on large scale deployments with hundreds of children and multiple upstream parent nodes above the current parent, I could easily see that sender thread being a bottleneck.

We may also want to reevaulate how we decide on default thread counts in other places as well. For example, on my home server I see:

- Six web server threads. Even when accessing the local dashboard, these sit idle about 99% of the time, so there’s not really any point to having six of them. We may want to consider an auto-scaling thread pool for this.
- Six ACLK query threads. These also spend a _lot_ of time idle, with the cumulative runtime of all six threads together over the past 72 hours being about five minutes. Again, we may want to consider an auto-scaling thread pool for this.
- Eighteen libuv workers. These also appear to be spending a lot of time idle, though they seem to be much more evenly spread out in terms of usage than the ACLK or web server threads, so I’m not sure if it makes sense to try and scale this at all.
- Thirty-two threads for the go.d plugin. This is technically expected given that the system has 32 logical CPUs, but at the same time it’s excessive given that I only have five jobs configured for the plugin. We probably want to cap this to the number of actual jobs being run by the plugin if it’s less than the total number of logical CPUs in the system (it appears to be possible to reconfigure GOMAXPROCS at runtime using the `runtime` package from the Go standard library).

**Comment by Forza-tng** [comment]
How about using io_uring on supported systems to minimise the connection costs and reduce context switches?

As for SQL/sqlite, perhaps redis could be an option? It keeps stuff in ram, but does persist things lazily to disk and guarantees contents to remain across redis restarts. It would increase dependencies, but for a large system, redis is probably already available.

**Comment by Ferroin** [comment]
> How about using io_uring on supported systems to minimise the connection costs and reduce context switches?

`readfile()`, once that’s finally widely available, is probably going to be a much bigger win for us than io_uring would be, but both would be good to look into.

**Comment by Forza-tng** [comment]
> > How about using io_uring on supported systems to minimise the connection costs and reduce context switches?
> 
> `readfile()`, once that’s finally widely available, is probably going to be a much bigger win for us than io_uring would be, but both would be good to look into.

I was thinking mostly on the network send/receive parts, especially if there are many connections of streaming data. But maybe readfile can do those too?

**Comment by Ferroin** [comment]
> > > How about using io_uring on supported systems to minimise the connection costs and reduce context switches?
> > 
> > 
> > `readfile()`, once that’s finally widely available, is probably going to be a much bigger win for us than io_uring would be, but both would be good to look into.
> 
> I was thinking mostly on the network send/receive parts, especially if there are many connections of streaming data. But maybe readfile can do those too?

Ah, I wasn’t thinking about the network side of things. There’s a definite possibility that would significantly improve things.

> Readfile should be great for /proc and /sys files and anything smallish like that.

This is what I was thinking of, especially in the context of the apps.plugin. On big systems, it’s not unusual for us to read thousands of small files each collection cycle.

**Comment by Forza-tng** [comment]
Libuv finally has implementated io_uring :)

**Comment by ilyam8** [comment]
There were a lot of optimizations... I think we can close this issue.
