### ISSUE TITLE
[Bug]: Netdata cannot start on Alpine 3.17.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#14237]
### Bug description

When attempting to start the agent nativelyon Alpine 3.17, the agent exits early in the initialization process with the following error log output:

```
2023-01-10 13:43:01: netdata INFO  : MAIN : TIMEZONE: using strftime(): 'UTC'
2023-01-10 13:43:01: netdata INFO  : MAIN : TIMEZONE: fixed as 'UTC'
2023-01-10 13:43:01: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
2023-01-10 13:43:01: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 4096, max = 4096
2023-01-10 13:43:01: netdata INFO  : MAIN : Out-Of-Memory (OOM) score is already set to the wanted value 0
2023-01-10 13:43:01: netdata ERROR : MAIN : Cannot adjust netdata scheduling policy to batch (3), with priority 0. Falling back to nice. (errno 38, Function not implemented)
2023-01-10 13:43:01: netdata ERROR : MAIN : Cannot get my current process scheduling policy. (errno 38, Function not implemented)
2023-01-10 13:43:01: netdata INFO  : MAIN : netdata started on pid 23851.
2023-01-10 13:43:01: netdata FATAL : netdata : Cannot create directory '/var/lib/netdata/registry'. # : Invalid argument

2023-01-10 13:43:01: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2023-01-10 13:43:01: netdata INFO  : MAIN : EXIT: cleaning up the database...
2023-01-10 13:43:01: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
2023-01-10 13:43:01: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
```

### Expected behavior

The agent starts correctly on Alpine 3.17

### Steps to reproduce

1. Build locally on Alpine 3.17
2. Attempt to start the agent.

### Installation method

kickstart.sh

### System info

```shell
/etc/alpine-release:3.17.1
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.17.1
/etc/os-release:PRETTY_NAME="Alpine Linux v3.17"
```

### Netdata build info

```shell
Version: netdata v1.37.0-110-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--with-bundled-protobuf' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

This is a hard blocker for us moving to Alpine 3.17 as a base for our Docker images and static builds, which in turn means it’s a blocker for a handful of improvements in both areas.

**Comment by Dim-P** [comment]
@Ferroin Can you check the `FATAL` directory permissions and try again? I just installed Netdata on an `Alpine 3.17.1` VM and it starts fine.

**Comment by Ferroin** [comment]
> @Ferroin Can you check the `FATAL` directory permissions and try again? 

The parent directory is owned by `netdata:netdata` with permissions of 0770.

> I just installed Netdata on an `Alpine 3.17.1` VM and it starts fine.

Was it a static build (this is what you will get by default with the kickstart script) or a local build? I’m only seeing the issue when building natively on Alpine 3.17, not when running the static builds there.

I have not, however, tested on a full install of Alpine, just in Podman containers on my laptop.

**Comment by Dim-P** [comment]
> > @Ferroin Can you check the `FATAL` directory permissions and try again?
> 
> The parent directory is owned by `netdata:netdata` with permissions of 0770.
> 
> > I just installed Netdata on an `Alpine 3.17.1` VM and it starts fine.
> 
> Was it a static build (this is what you will get by default with the kickstart script) or a local build? I’m only seeing the issue when building natively on Alpine 3.17, not when running the static builds there.
> 
> I have not, however, tested on a full install of Alpine, just in Podman containers on my laptop.

That was a local build using the latest master and no custom install prefix. Maybe someone else can try and confirm it's an issue indeed.

**Comment by thiagoftsm** [comment]
When I installed using only `./netdata-installer.sh --dont-wait --dont-start-it` on a VM created from scratch, I had the same warning for `OOM`, but I did not have issues to run netdata when the installation finished, all permissions were set properly.

**Comment by Ferroin** [comment]
OK, digging into this further, I can only reproduce it in containers myself, not in VMs.

FWIW, this exact issue is _why_ we did not migrate to Alpine 3.17 for our static builds and Docker images, the same issue was happening in CI as well when we first tried to migrate.

**Comment by Ferroin** [comment]
Further details, as discussed in the sync:

The systems I’ve reproduced this on locally have been running podman. Sample output of `podman info` on one of the systems I’ve reproduced this on (with private info redacted):

```yaml
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: app-containers/conmon-2.1.0
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.0, commit: v2.1.0'
  cpuUtilization:
    idlePercent: 82.24
    systemPercent: 9.7
    userPercent: 8.06
  cpus: 16
  distribution:
    distribution: gentoo
    version: "2.9"
  eventLogger: file
  hostname: ""
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.1.4-gentoo
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 3306913792
  memTotal: 15971794944
  networkBackend: cni
  ociRuntime:
    name: crun
    package: app-containers/crun-1.4.5
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: ""
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: app-containers/slirp4netns-1.2.0
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 27373596672
  swapTotal: 34359734272
  uptime: 1h 17m 5.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
  - registry.suse.com
store:
  configFile: ""
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: ""
  graphRootAllocated: 17179869184
  graphRootUsed: 4915122176
  graphStatus: {}
  imageCopyTmpDir: ""
  imageStore:
    number: 0
  runRoot: ""
  volumePath: ""
version:
  APIVersion: 4.3.1
  Built: 1673538476
  BuiltTime: Thu Jan 12 10:47:56 2023
  GitCommit: 814b7b003cc630bf6ab188274706c383f9fb9915
  GoVersion: go1.19.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

This has also been previously reproduced in our CI, using Docker on Ubuntu.

**Comment by Ferroin** [comment]
Just confirmed, this appears to have nothing to do with AppArmor or privileged versus unprivileged containers.

**Comment by Dim-P** [comment]
Thanks for the info @Ferroin . Tried various things on `Fedora 37` as host and kernel `6.1.6`, haven't managed to reproduce it (I am using AppArmor too, not SELinux). Tried both docker and podman. Priviledged or unpreviledged containers. No luck so far. I will try again using a different host.

**Comment by Ferroin** [comment]
@Dim-P Any chance you could try it on an up-to-date copy of Ubuntu 22.04? I’ve  managed toreproduce it on such a system as well, and that’s what our CI looked like when it was failing there.

**Comment by Forza-tng** [comment]
> When attempting to start the agent nativelyon Alpine 3.17, the agent exits early in the initialization process with the following error log output:

I don't use kickstart, but I use build form git method instead. There is no issue building there. Perhaps some issue with permissions etc? Alpine does not have the setcaps ability, for example. Also Alpine uses busybox and ash instead of bash by default, which can confuse some scripts.

My build script that I use on all my machines (Ubuntu, CentOS, Alpine and Gentoo)

```bash
#!/bin/bash

#CPUFLAGS="-march=x86-64-v3#
CPUFLAGS="-march=native"

export CFLAGS="-O3 $CPUFLAGS -pipe"
export LDFLAGS="-Wl,--as-needed -Wl,-O1 -Wl,--sort-common"
export CXXFLAGS="-O3  $CPUFLAGS -pipe"
export CPPFLAGS="-O3  $CPUFLAGS  -pipe"
export TMPDIR="/var/tmp/"

ND=`mktemp -d -p $TMPDIR netdata-build.XXXX` || exit 1
#ND="/mnt/tmp/netdata/netdata-build.tFKT"
echo  Working dir is: "$ND"
pushd "$ND" > /dev/null
read -p "Press any key to continue... "

echo "Going to clone  https://github.com/netdata/netdata.git"
read -p "Press any key to continue... "
git clone https://github.com/netdata/netdata.git --depth=100 --recursive "$ND"

echo "Going to run 'netdata-installer.sh -enable-lto --enable-ml --disable-telemetry  --install-prefix /opt --dont-start-it'"
read -p "Press any key to continue... "
#ls -laF
nice -n20 ./netdata-installer.sh --enable-lto --enable-ml --disable-telemetry  --install-prefix /opt --dont-start-it

read -p "All done! Press any key to exit. "
```

**Comment by Dim-P** [comment]
> @Dim-P Any chance you could try it on an up-to-date copy of Ubuntu 22.04? I’ve managed toreproduce it on such a system as well, and that’s what our CI looked like when it was failing there.

Just tried on an `Ubuntu 22.04` VM host and it builds and runs fine using `Alpine 3.17` :/ . Only thing I noticed was the shutdown problem that I believe @ilyam8 is looking into. 

@Forza-tng Thanks for looking into this!

**Comment by Dim-P** [comment]
Just reproduced this issue by accident on an `Ubuntu 22.04` VM, so not sure at all it has anything to do with `Alpine 3.17`.

**Comment by Ferroin** [comment]
> Just reproduced this issue by accident on an `Ubuntu 22.04` VM, so not sure at all it has anything to do with `Alpine 3.17`.

It may not, that just happens to be the only place I’ve been able to reproduce it.

**Comment by MrZammler** [comment]
Hi @Ferroin 

I remember seeing this randomly at some points in the past, but I tried with a latest alpine image (3.17.2) now, did a few kickstart builds, but I can't reproduce it. Also did some tests on 22.04 VM.

The error you're getting is really strange: `Invalid argument`. According to the man page: `The final component ("basename") of the new directory's pathname is invalid (e.g., it contains characters not permitted by the underlying filesystem).`

I'd be suprised if somehow the path we give to mkdir is corrupted. How reproducable is this in your case? Can we do some tests?

**Comment by Ferroin** [comment]
> Hi @Ferroin
> 
> I remember seeing this randomly at some points in the past, but I tried with a latest alpine image (3.17.2) now, did a few kickstart builds, but I can't reproduce it. Also did some tests on 22.04 VM.
> 
> The error you're getting is really strange: `Invalid argument`. According to the man page: `The final component ("basename") of the new directory's pathname is invalid (e.g., it contains characters not permitted by the underlying filesystem).`
> 
> I'd be suprised if somehow the path we give to mkdir is corrupted. How reproducable is this in your case? Can we do some tests?

I have not tested recently, but it was 100% reproducible when I was seeing it. I can re-check the case I was originally testing though and see if it’s still an issue.

**Comment by Ferroin** [comment]
I’m still seeing this for Docker images built using Alpine 3.17, albeit with a slightly different error message. It’s still failing on trying to create `/var/lib/netdata/registry` though.

However, I’ve stumbled across something new. The containers I’m ending up with from the build have really strange permissions on a number of things, including missing read/execute permissions for non-root users on a large number of files and directories. I suspect this is the root cause of the issue, and will start further investigating it.

**Comment by Ferroin** [comment]
Confirmed, it’s the bogus permissions that are the issue. I’ll put together a PR to handle fixing that and then look at finally getting the Docker base images updated to Alpine 3.17.

**Comment by com6056** [comment]
cross-posting from the PR: https://github.com/netdata/netdata/pull/14629#issuecomment-1566229876
