### ISSUE TITLE
[Bug]: Networking Stack metrics are not collected when IPv6 is disabled

### ISSUE THREAD

**Issue by wally007** [netdata/netdata#14235]
### Bug description

Hello,

We just installed Netdata 1.37 via EPEL on RHEL 8.6 (tested on RHEL 8.7 as well) on freshly installed OS and we are missing all of `Network Stack` graphs in the agent. Basically all metrics from `/proc/net/netstat` and `/proc/net/snmp` are missing when IPv6 is disabled on the system via grub.
I can see that both files are world readable and have statistics. Initially, we also tested running Netdata as root but it made no difference.

Then we looked at how our OS is deployed and found that the only playbook that we run before package installation was to disable IPv6 via grub `/etc/default/grub` and we insert this line: `GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"`
And I can confirm this is what breaks the Network Stack graphs.  
On one of the test systems when i removed the `ipv6.disable=1` from grub and rebuild/rebooted - all of the `Network Stack` graphs are there and working without any issues.

I noticed that there was some work on these plugin just few weeks ago [this GitHub commit](https://github.com/netdata/netdata/pull/13806), so most likely the issue was introduced there.

 Can you please let me know if this is bug or a feature ? We always disabled IPv6 and never had any issues with any other software - until now :-)
(we use `/proc/net/netstat` to monitor TCP retransmissions) 

### Expected behavior

We expected to have IPv4 TCP statistics even when IPv6 is disabled on the system (which it always is in our env. of 2000+ VMs and 300 bare metal RHEL servers)

### Steps to reproduce

1. Disabled IPv6 via GRUB 
add this line to `/etc/default/grub`
`GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"`
3. Rebuild grub `grub2-mkconfig -o /boot/efi/EFI/REDHAT/grub.cfg` (may have to change boot partition)
4. Reboot
5. Watch that all `Network Stack` graphs are missing from Netdata Agent Dashboard
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux cleaner 4.18.0-425.3.1.el8.x86_64 #1 SMP Fri Sep 30 11:45:06 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux"
/etc/os-release:VERSION="8.7 (Ootpa)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VERSION_ID="8.7"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
/etc/redhat-release:Red Hat Enterprise Linux release 8.7 (Ootpa)
/etc/system-release:Red Hat Enterprise Linux release 8.7 (Ootpa)
```

### Netdata build info

```shell
netdata -W buildinfo
Version: netdata v1.37.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-plugin-freeipmi' '--enable-plugin-cups' '--with-bundled-libJudy' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
Thanks for reporting, @wally007. Fixed in #14252.
