### ISSUE TITLE
[Bug]: Unable to connect to netdata cloud

### ISSUE THREAD

**Issue by smcoder0707** [netdata/netdata#14230]
### Bug description

Netdata agent is unable to connect to the netdata cloud

### Expected behavior

Netdata agent should be able to connect to the netdata cloud

### Steps to reproduce

1. Install as usual using the Kickstarter script
2. claim agent
3. Manually build openssl from sources using the following command
```
./config --openssldir=/etc/ssl -fPIC shared zlib-dynamic && \
sed -i "s/install: install_sw install_ssldirs install_docs/install: install_sw install_ssldirs/g" Makefile && \
make && \
make install
```
5. check netdatacli aclk-state

To get the netdata working simply install openssl using apt install -qy openssl

### Installation method

kickstart.sh

### System info

```shell
root@test:~# uname -a; grep -HvE "^#|URL" /etc/*release
Linux test 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Version: netdata v1.37.0-107-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

My issue is similar to this forum post - https://community.netdata.cloud/t/netdata-agent-is-unable-to-connect-with-netdata-cloud/3588

**Comment by smcoder0707** [comment]
UPDATE:

So, this issue was happening because I was manually compiling openssl and installing openssl from the default ubuntu repo fixes this issue.

Netdata somehow is hardcoded to one of the build parameters of the openssl package. I have updated the "Steps to reproduce
" section.

**Comment by MrZammler** [comment]
Hi @smcoder0707 and thanks for the update.

In general yes, packages typically expect other packages (such as openssl) being a specific version.

**Comment by smcoder0707** [comment]
> Hi @smcoder0707 and thanks for the update.
> 
> In general yes, packages typically expect other packages (such as openssl) being a specific version.

I think this issue is closed in hurry without inspecting the issue properly.

The issue is not with specific version of openssl. [As per your documentation](https://github.com/netdata/netdata/blob/381905e2fbd2f432e52544218efd99efe06a76c4/packaging/installer/methods/source.md), netdata can work on any openssl version 1.0.2 or newer.
I am using openssl 1.1.1s.

If you carefully check my logs posted [here ](https://community.netdata.cloud/t/netdata-agent-is-unable-to-connect-with-netdata-cloud/3588), you will see the following line which indicates missing root certificate but the root certificates are not missing.

`2022-12-03 03:25:03: netdata ERROR : ACLK_Main : Cert Chain verify error:num=20:unable to get local issuer certificate:depth=2:/C=US/O=Internet Security Research Group/CN=ISRG Root X1 (errno 2, No such file or directory)`

I'm not sure how netdata works internally or where it looks for root certs. So, If you can alteast provide some hint, I can get  this issues resolved

**Comment by MrZammler** [comment]
Ok, let's see, as first do you have ca-certificates package installed?

**Comment by smcoder0707** [comment]
> Ok, let's see, as first do you have ca-certificates package installed?

yes, I have that installed and certs are working perfectly. for example via curl or wget command.

I attempted to build netdata which failed on the first attempt because it was installing 'libssl-dev' package by default and I already had those libraries and header files installed manually during custom compilation of openssl.

I removed `libssl-dev` package and blocked it. Then the compilation was successful and everything was working fine i.e netdata cloud was able to connect to netdata cloud.

But the problem is that this feature is broken on netdata package from the official repo.

Also note that, I have been running custom compiled openssl for long a time and netdata never had any issue with it...but this issue appeared since last few updates of netdata.

**Comment by MrZammler** [comment]
I'm not sure how to recreate this issue...

So in an Ubuntu 22.04.1, with from packages openssl (3.0.2) and packaged netdata, things work.

I've compiled and installed openssl 1.1.1t and 3.0.8, but the don't not seem to interfere with netdata. Both are installed under `/usr/local/lib64/`, while the system openssl (and what netdata uses) is under `/lib/x86_64-linux-gnu/`. Do you install in system paths?

**Comment by MrZammler** [comment]
Closing this... @smcoder0707 if you can provide specific steps on how to reproduce, please let us know.
