### ISSUE TITLE
[Feat]: Can you add the multi -language and support the mobile platform(IOS Android)？

### ISSUE THREAD

**Issue by huanghe9527** [netdata/netdata#14234]
### Problem

Can you support multi -language(web netdata.cloud), such as traditional Chinese Japanese and Korean
And whether you can support Android or iOS APP clients, so that monitoring and inspection will be more convenient

### Description

just all

### Importance

really want

### Value proposition

1.
2.
3.
...

**Comment by ilyam8** [comment]
This is a valid request, but I think at the moment the answer is no - we don't have people working on it. The user interface will be in English only.
