### ISSUE TITLE
[Bug]:  High avg load on Proxmox host every ~90 minutes

### ISSUE THREAD

**Issue by CZAirwolf** [netdata/netdata#14250]
### Bug description

Too high avg load regularly. Similiar to https://github.com/netdata/netdata/issues/5234.

![image](https://user-images.githubusercontent.com/8327581/212022752-97428419-f2f8-4a35-89c6-c4fbe6fda740.png)
![image](https://user-images.githubusercontent.com/8327581/212022775-b56b73cb-8345-48e1-bf38-267d6d7257cd.png)
![image](https://user-images.githubusercontent.com/8327581/212022979-ee20161d-5198-4ebc-898c-44afccf85933.png)

Currently ~50-60 VMs (mainly non DBs) on the every Proxmox 7.x host in the cluster. I can "see" same regular spikes on VM directly but with very little impact. Maybe something about saving data? 

Comparison, but can "see" regular spikes with low impact;
Proxmox 6.x with ~20 VMs (mainly DBs, 4x Xeon Gold, total 96 cpu+ht cores)
![image](https://user-images.githubusercontent.com/8327581/212025446-6f4462f7-d26b-4966-b178-750b948bbf89.png)

### Expected behavior

Not such load impact.

### Steps to reproduce

1. stop netdata after some hours
2. start netdata after some hours
3. check cpu load graph to see when spikes appeared or disappeared

### Installation method

other

### System info

```shell
Linux pve-11 5.15.74-1-pve #1 SMP PVE 5.15.74-1 (Mon, 14 Nov 2022 20:17:15 +0100) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.37.1
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: manual-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Installed via netdata-latest.gz.run

Changes vs default netdata.conf:

```
[db]
 memory mode = dbengine
 dbengine multihost disk space = 256
 storage tiers = 1

[web]
 allow dashboard from = REDACTED

[plugins]
 enable cgroup docker = no
```

**Comment by ilyam8** [comment]
Hi, @CZAirwolf. 

- Can you check CPU/memory/disk pressure charts? load average doesn't say much (who knows if that is a CPU or IO-bound problem).
- Do you mean you have a high load avg only when Netdata is running?
- Did you check other charts? For instance, "Applications" section.

**Comment by CZAirwolf** [comment]
ad Q1] Yes, pressure's graphs aren't raised in spike time, anyway. I can upload snapshot, but prefer to not publicly (security).

ad Q2] Yes, only when netdata is running
![image](https://user-images.githubusercontent.com/8327581/212088848-808ea685-6b33-4620-ad01-e5cc2b668fbc.png)

Left side graph - netdata not running for hours. Right hole - around 9:45 there was netdata update 1.37.0 -> 1.37.1. There can be spotted lower system cpu time (green) for ~ 90 -120 minutes and then the spike came again with some delay.

ad Q3] Yes, checked a lot of graphs without success.

**Comment by ilyam8** [comment]
> pressure's graphs aren't raised in spike time

We will check load avg, but just letting you know - then there is no problem with system load if [PSI](https://docs.kernel.org/accounting/psi.html) charts don't indicate it.

**Comment by CZAirwolf** [comment]
![image](https://user-images.githubusercontent.com/8327581/216002645-528bb9f7-9908-421c-8bee-720f67ed700f.png)

![image](https://user-images.githubusercontent.com/8327581/216002470-2bd510a1-f146-44cd-af3a-9fa7c3fd3610.png)

**Comment by MrZammler** [comment]
@CZAirwolf Hi.

Is it possible please to update this issue with info from newer Netdata versions? The spike interval you mention could be linked to internal cleanups, but those have seen changes since 1.37.1

**Comment by ilyam8** [comment]
Load average doesn't indicate a problem, [PSI charts](https://github.com/netdata/netdata/issues/14250#issuecomment-1411726217) look good. I think we can close this issue.
