### ISSUE TITLE
Add table size threshold for postgres_table_bloat_size_perc

### ISSUE THREAD

**Issue by cuu508** [netdata/netdata#14271]
Would it be possible in the `postgres_table_bloat_size_perc` alarm template to specify the minimum table size threshold for an alarm to fire? 

Context: I'm getting alerts about index bloat for tiny tables, think 16KB table with 16KB index bloat. I would prefer to receive alerts only for tables above some size threshold, say, 100MiB.

_Originally posted by @cuu508 in https://github.com/netdata/netdata/issues/13671#issuecomment-1338988763_

**Comment by cuu508** [comment]
There was some discussion about this feature suggestion here: https://github.com/netdata/netdata/pull/13671#issuecomment-1338988763

I'm creating a separate issue so it doesn't get forgotten in a merged PR's commends.

**Comment by cuu508** [comment]
Awesome, thanks for looking into this so quickly!

Two followup questions:

* sorry for not mentioning earlier, but the postgres_index_bloat_size_perc metric and notifications have the same problem – I'm getting alerts about index bloat for tiny tables. Would it be possible to fix that one as well?
* would it be possible to also update the alert `templates postgres_table_bloat_size_perc` and `postgres_index_bloat_size_perc` in https://github.com/netdata/netdata/blob/master/health/health.d/postgres.conf?

**Comment by ilyam8** [comment]
I will update both templates

**Comment by ilyam8** [comment]
Updated in #14275

**Comment by cuu508** [comment]
I'm now running netdata v1.38.1 and go.d.plugin v0.50.0:

```
$ /usr/libexec/netdata/plugins.d/go.d.plugin --version
go.d.plugin, version: v0.50.0
```

Unfortunately I still see alarms about index bloat for small indexes, example:

![image](https://user-images.githubusercontent.com/661859/219008493-2a4f674a-a4d5-484f-9fb4-5903d0c0e059.png)

In this particular case, the table size is 490KiB and the  index size is 400KiB.

Do I also need to configure something on my end, to disable alerts table and index bloat for small tables and small indexes?

**Comment by ilyam8** [comment]
@cuu508 I think you are using an old version of `health.d/postgres.conf`. Did you change at some point (using `edit-config` script)? If so, I suggest you delete `/etc/netdata/health.d/postgres.conf` (and copy the updated version from the stock dir again if needed).

**Comment by cuu508** [comment]
Ah, indeed I had a `/etc/netdata/health.d/postgres.conf` – I guess at some point I was trying to fix this myself ;-) I removed it, restarted netdata, and the alerts appear to be gone.

Thank you for the assistance, appreciate it!
