### ISSUE TITLE
[Feat]: Add controls to restart and or update netdata from Netdata.cloud

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#14277]
### Problem

Currently you have to log into your server via SSH and use SytemCTL to restart a Netdata instance. 

If you see the notification that an updated version is available that you want to install before the next scheduled update, you need to remember exactly how to manually run the updater (which isn't quick and easy to remember, especially if you haven't done so for months without turning to the docs or your notes). 

By adding the ability to simply perform a restart of a Netdata instance, or inititate an update of a Netdata instance from the Netdata Cloud dashboard, it would make doing so much quicker and more convenient and both could honor the role/permissions system.

### Description

Add the ability to restart a Netdata instance, or update a Netdata instance from the Netdata Cloud dashboard.

### Importance

nice to have

### Value proposition

1. More convenient.
2. Simpler.
3. Still secure.
...

**Comment by HariVamsiK** [comment]
Hi @TheOldMan2000 I would like to work on this feature. It would be beneficial for me in my coursework. Could you please assign it to me?

**Comment by TheOldMan2000** [comment]
Thanks @HariVamsiK  that would be great but I think it would have to be one of the folks in charge, maybe @ilyam8 or @Ferroin

**Comment by MrZammler** [comment]
Hi @TheOldMan2000 

This is indeed (in my opinion) a nice idea. cc'ing @hugovalente-pm

**Comment by andrewm4894** [comment]
@HariVamsiK perhaps adding a `restart-agent` command to [netdatacli](https://learn.netdata.cloud/docs/agent/cli) could be something that could make a nice PR as part of some coursework. What do you think @Ferroin - or is it a bit more complex than i probably naively think?

In terms of triggering this from Netdata Cloud it would indeed be something we'd need to add - it touches a bit on "centralized netdata admin" which is a whole area we are looking to add more into Netdata Cloud so you can do a lot of what you need via the NC UI. This ability for remote restart maybe is a nice little first feature imo.

**Comment by Ferroin** [comment]
Unfortunately, none of this is actually possible with our current security model.

For the specific case of Docker, it is not possible, period. Updating requires updating the container image itself, which _cannot be done from inside the container_. Restarting requires restarting the entire container, which also _cannot be done from inside the container_.

For native installs, we run into a similar issue in that we need root access to update or restart properly, which we intentionally do not have for security reasons.

In theory, we could shift things to use an integrated supervisor process to allow us to restart the agent without running into those above issues, but there’s not any way we can securely solve this for updates, and taking the integrated supervisor process approach would require nontrivial amount of development work.

**Comment by TheOldMan2000** [comment]
Oh dear, that’s a shame. Thank you for explaining though.

**Comment by Ferroin** [comment]
To clarify a bit, I do think we should look into putting in the work to have our own supervisor process so that we can support remotely triggered restarts of the agent, especially since it should allow better error reporting and also make the agent more resilient against internal errors. It’s just going to take quite a bit of development work to actually achieve that, and therefore is not likely to happen in the near future.
