### ISSUE TITLE
[Bug]: memory leak on centos 9 stream

### ISSUE THREAD

**Issue by poi212003** [netdata/netdata#14288]
### Bug description

agent leaks memory - goes up to 1.4gb ram.
tried changing to child parent config - still the same.

### Expected behavior

should be around 100MB at most per your docs/forum

### Steps to reproduce

1. install agent.
2. start
3. leak happens almost immdiately.
...

### Installation method

kickstart.sh

### System info

```shell
/etc/centos-release:CentOS Stream release 9
/etc/os-release:NAME="CentOS Stream"
/etc/os-release:VERSION="9"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="9"
/etc/os-release:PLATFORM_ID="platform:el9"
/etc/os-release:PRETTY_NAME="CentOS Stream 9"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:LOGO="fedora-logo-icon"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:9"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
/etc/redhat-release:CentOS Stream release 9
/etc/system-release:CentOS Stream release 9
```

### Netdata build info

```shell
Version: netdata v1.37.0-158-gb9cafae62
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

```
running "service netdata status"
● netdata.service - Real time performance monitoring
     Loaded: loaded (/usr/lib/systemd/system/netdata.service; enabled; preset: disabled)
     Active: active (running) since Wed 2023-01-18 03:57:08 UTC; 7h ago
    Process: 532607 ExecStartPre=/bin/mkdir -p /opt/netdata/var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 532608 ExecStartPre=/bin/chown -R netdata /opt/netdata/var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 532609 ExecStartPre=/bin/mkdir -p /run/netdata (code=exited, status=0/SUCCESS)
    Process: 532611 ExecStartPre=/bin/chown -R netdata /run/netdata (code=exited, status=0/SUCCESS)
   Main PID: 532612 (netdata)
      Tasks: 78 (limit: 18660)
     Memory: 1.4G
        CPU: 10min 37.292s
     CGroup: /system.slice/netdata.service
             ├─532612 /opt/netdata/bin/srv/netdata -P /run/netdata/netdata.pid -D
             ├─532615 /opt/netdata/bin/srv/netdata --special-spawn-server
             ├─532774 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
             ├─532778 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
             ├─533185 /opt/netdata/usr/libexec/netdata/plugins.d/ebpf.plugin 1
             └─572289 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1

Jan 18 03:57:15 servicesdb02 systemd-coredump[532992]: [🡕] Process 532770 (ebpf.plugin) of user 986 dumped core.
Jan 18 03:57:27 servicesdb02 [533141]: Does not have a configuration file inside `/opt/netdata/etc/netdata/ebpf.d.conf. It will try to load stock file.
Jan 18 03:57:27 servicesdb02 [533141]: Cannot read process groups configuration file '/opt/netdata/etc/netdata/apps_groups.conf'. Will try '/opt/netdata/usr/lib/netdata/conf.d/app>
Jan 18 03:57:27 servicesdb02 [533141]: PROCFILE: Cannot open file '/proc/532770/status'
Jan 18 03:57:27 servicesdb02 [533141]: Cannot open /proc/532770/status
Jan 18 03:57:28 servicesdb02 systemd-coredump[533161]: [🡕] Process 533141 (ebpf.plugin) of user 986 dumped core.
Jan 18 03:57:41 servicesdb02 [533185]: Does not have a configuration file inside `/opt/netdata/etc/netdata/ebpf.d.conf. It will try to load stock file.
Jan 18 03:57:41 servicesdb02 [533185]: Cannot read process groups configuration file '/opt/netdata/etc/netdata/apps_groups.conf'. Will try '/opt/netdata/usr/lib/netdata/conf.d/app>
Jan 18 03:57:41 servicesdb02 [533185]: PROCFILE: Cannot open file '/proc/533141/status'
Jan 18 03:57:41 servicesdb02 [533185]: Cannot open /proc/533141/status
lines 1-29/29 (END)
```

**Comment by ilyam8** [comment]
Hi, @poi212003.

- Do you have any non-default configuration (e.g `netdata.conf->[db]`)?
- Can you send a [snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) to `ilya@netdata.cloud`? (when netdata uses 1gb+ mem)

**Comment by poi212003** [comment]
first used default config.
later did the parent setup and changed the child to the following (as you suggest):
```
[db]
   storage tiers = 1
   mode = alloc
   retention = 1800
[ml]
   enabled = no
[health]
   enabled = no
[web]
        mode = none
```
As to the snapshot - i dont see this option - i'm using the cloud version - should i still see it?

**Comment by Dim-P** [comment]
> first used default config. later did the parent setup and changed the child to the following (as you suggest):
> 
> ```
> [db]
>    storage tiers = 1
>    mode = alloc
>    retention = 1800
> [ml]
>    enabled = no
> [health]
>    enabled = no
> [web]
>         mode = none
> ```
> 
> As to the snapshot - i dont see this option - i'm using the cloud version - should i still see it?

@poi212003 Can you please update to the most recent nightly version and let us know if you are still experiencing this issue? 

I haven't managed to reproduce it, but I noticed the ebpf plugin is crashing on your system, so that could be a suspect, particularly if you have many cores on your machine. A snapshot will help, please follow the instructions [here](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) on how to take one using your local dashboard. It's not possible to do that through the cloud UI at the moment.

**Comment by Dim-P** [comment]
For future reference, this seems to be related to the `eBPF.plugin`. See linked forum topic.

**Comment by ilyam8** [comment]
Hi, @poi212003.

- We haven't been able to reproduce memory leaks on Centos9.
- As for high memory usage (1.4gb), it is kind of expected when using ebpf.plugin (enabled by default) on a host with a lot of CPU cores (e.g. on a server with 256 cores ebpf.plugin uses 3.6 GiB of RAM). I suggest you disable ebpf.plugin
  - open netdata.conf
  - go to `[plugins]`
  - uncomment `ebpf` and change its value to `no`
  - restart netdata service

**Comment by poi212003** [comment]
> Hi, @poi212003.
> 
> * We haven't been able to reproduce memory leaks on Centos9.
> * As for high memory usage (1.4gb), it is kind of expected when using ebpf.plugin (enabled by default) on a host with a lot of CPU cores (e.g. on a server with 256 cores ebpf.plugin uses 3.6 GiB of RAM). I suggest you disable ebpf.plugin
>   
>   * open netdata.conf
>   * go to `[plugins]`
>   * uncomment `ebpf` and change its value to `no`
>   * restart netdata service

We'll it's actually about 2 cores so it's not the cause... And the ram usage just leaks until the service crashes.
We've turned it off for now and it works fine.

@Dim-P I'll update the agent and do the snapshot
