### ISSUE TITLE
[Bug} Netdata updater breaks netdata.service if kickstart installs a static build (CentOS7)

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#14292]
After running the updater or letting it run natively, I found out that the SystemD Netdata.service was incorrectly configured and I couldn't restart Netdata at all. 

Produces constant errors:

> Unit netdata.service entered failed state.

and

> Job for netdata.service failed because a configured resource limit was exceeded. See "systemctl status netdata.service" and "journalctl -xe" for details.

By using:

`nano /usr/lib/systemd/system/netdata.service`

I found out these 2 lines inside should be:

`EnvironmentFile=/opt/netdata/etc/netdata/.environment`
`ExecStart=/opt/netdata/bin/netdata -D $EXTRA_OPTS`

They were both wrongly set to /etc/netdata/ and /usr/sbin/netdata both of which didn't exist on OS, because Netdata installed a static build in /opt/netdata.

After 1000's of nightly builds, it's still installing and configuring in varying directories, which causes nothing but problems and confusion.

Finally fixed the issue and when the updater runs, it breaks the Netadata service again!

```
# SPDX-License-Identifier: GPL-3.0-or-later
[Unit]
Description=Real time performance monitoring

# append here other services you want netdata to wait for them to start
After=network.target httpd.service squid.service nfs-server.service mysqld.service mysql.service named.service postfix.service chronyd$

[Service]
Type=simple
User=netdata
Group=netdata
RuntimeDirectory=netdata
CacheDirectory=netdata
StateDirectory=netdata
LogsDirectory=netdata
RuntimeDirectoryMode=0775
StateDirectoryMode=0755
CacheDirectoryMode=0755
LogsDirectoryMode=2750
#EnvironmentFile=-/etc/default/netdata <------ BAD!
EnvironmentFile=/opt/netdata/etc/netdata/.environment
#ExecStart=/usr/sbin/netdata -D $EXTRA_OPTS <--------- BAD!
ExecStart=/opt/netdata/bin/netdata -D $EXTRA_OPTS

# saving a big db on slow disks may need some time
TimeoutStopSec=150

# restart netdata if it crashes
Restart=on-failure
RestartSec=30

# Valid policies: other (the system default) | batch | idle | fifo | rr
# To give netdata the max priority, set CPUSchedulingPolicy=rr and CPUSchedulingPriority=99
CPUSchedulingPolicy=batch

# This sets the scheduling priority (for policies: rr and fifo).
# Priority gets values 1 (lowest) to 99 (highest).
#CPUSchedulingPriority=1

# For scheduling policy 'other' and 'batch', this sets the lowest niceness of netdata (-20 highest to 19 lowest).
Nice=19

[Install]
WantedBy=multi-user.target
```

_Originally posted by @TheOldMan2000 in https://github.com/netdata/netdata/discussions/14229#discussioncomment-4671973_
    

```
Build Info:

$(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
Version: netdata v1.37.0-158-gb9cafae62
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO


```

```
System Info:

uname -a; grep -HvE "^#|URL" /etc/*release
Linux vpsxxxxxx.hosting.com 3.10.0-1160.53.1.vz7.185.3 #1 SMP Tue Jan 25 12:49:12 MSK 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

**Comment by TheOldMan2000** [comment]
Unfortunately the Netdata Updater is still breaking the SystemD Netdata Service everytime it runs, by reseting the /usr/lib/systemd/system/netdata.service to look in the wrong locations causing Netdata to break.

I have to keep correcting these 2 lines every day and every time it runs:

```
#EnvironmentFile=-/etc/default/netdata
#ExecStart=/usr/sbin/netdata -D $EXTRA_OPTS
```
to:
```
EnvironmentFile=/opt/netdata/etc/netdata/.environment
ExecStart=/opt/netdata/bin/netdata -D $EXTRA_OPTS
```

Any chance of an urgent resolve? 

Thank you!

**Comment by MrZammler** [comment]
Hi @TheOldMan2000 sorry for this...

Do you have an `.environment` file under `/etc/netdata` or `/etc/default/netdata` ?

**Comment by TheOldMan2000** [comment]
Hi @MrZammler  
No sorry, I dont have the folders:

```
#ls -lha /etc/netdata
/bin/ls: cannot access /etc/netdata: No such file or directory
# ls -lha /etc/default/netdata
/bin/ls: cannot access /etc/default/netdata: No such file or directory
```

**Comment by TheOldMan2000** [comment]
Sure:

 ```
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --dry-run
--2023-01-25 15:28:38--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 172.67.156.192, 104.21.13.159, 2606:4700:3031::6815:d9f, ...
Connecting to my-netdata.io (my-netdata.io)|172.67.156.192|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

    [ <=>                                                                                          ] 81,172      --.-K/s   in 0.002s  

2023-01-25 15:28:38 (38.1 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [81172]


 --- Using /tmp/netdata-kickstart-DtHlpDx6dh as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- Found an existing netdata install at /opt/netdata, with installation type 'kickstart-static'. --- 
 --- Would attempt to update existing installation by running the updater script located at: /opt/netdata/usr/libexec/netdata/netdata-updater.sh --- 
 --- Successfully updated existing netdata install at /opt/netdata. --- 
 --- Not attempting to claim existing install at /opt/netdata (no claiming token provided). --- 
Official documentation can be found online at https://learn.netdata.cloud/docs/.

Looking to monitor all of your infrastructure with Netdata? Check out Netdata Cloud at https://app.netdata.cloud.

Join our community and connect with us on:
  - GitHub: https://github.com/netdata/netdata/discussions
  - Discord: https://discord.gg/5ygS846fR6
  - Our community forums: https://community.netdata.cloud/


```
```
root@vpsxxx [~]# wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh

--2023-01-25 15:32:40--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 172.67.156.192, 104.21.13.159, 2606:4700:3031::6815:d9f, ...
Connecting to my-netdata.io (my-netdata.io)|172.67.156.192|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

    [ <=>                                                                                          ] 81,172      --.-K/s   in 0.002s  

2023-01-25 15:32:40 (41.8 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [81172]


 --- Using /tmp/netdata-kickstart-qCUKkDBSZS as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- Found an existing netdata install at /opt/netdata, with installation type 'kickstart-static'. --- 
[/tmp/netdata-kickstart-qCUKkDBSZS]# /opt/netdata/usr/libexec/netdata/netdata-updater.sh --interactive --not-running-from-cron 
Wed Jan 25 15:32:40 GMT 2023 : INFO: netdata-updater.sh:  Checking if a newer version of the updater script is available.
Wed Jan 25 15:32:41 GMT 2023 : INFO: netdata-updater.sh:  Entering /tmp/netdata-updater-yp9FxKjM2c
Wed Jan 25 15:32:42 GMT 2023 : INFO: netdata-updater.sh:  Current Version: 00103700000182
Wed Jan 25 15:32:42 GMT 2023 : INFO: netdata-updater.sh:  Latest Version: 00103700000182
Wed Jan 25 15:32:42 GMT 2023 : INFO: netdata-updater.sh:  Newest version (current=00103700000182 >= latest=00103700000182) is already installed
Wed Jan 25 15:32:42 GMT 2023 : INFO: netdata-updater.sh:  Switching back to /tmp/netdata-kickstart-qCUKkDBSZS
 OK 

 --- Updated existing install at /opt/netdata --- 
 --- Successfully updated existing netdata install at /opt/netdata. --- 
 --- Not attempting to claim existing install at /opt/netdata (no claiming token provided). --- 
Official documentation can be found online at https://learn.netdata.cloud/docs/.

Looking to monitor all of your infrastructure with Netdata? Check out Netdata Cloud at https://app.netdata.cloud.

Join our community and connect with us on:
  - GitHub: https://github.com/netdata/netdata/discussions
  - Discord: https://discord.gg/5ygS846fR6
  - Our community forums: https://community.netdata.cloud/
root@vpsxxxx [~]# 

```

**Comment by MrZammler** [comment]
Thanks! Did this run break the systemd service file?

**Comment by TheOldMan2000** [comment]
Hi, no I checked and it was unchanged.

Thanks.

**Comment by TheOldMan2000** [comment]
Broken again today, updater must have run. 

```
$(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
Version: netdata v1.37.0-192-ge7f5028c7
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by TheOldMan2000** [comment]
If anyone else is having this issue with Netdata static build breaking itself every day, and is getting fed up of manually fixing the netdata.service file, I’m trying this to disable updates and hopefully keep it running:

`/opt/netdata/usr/libexec/netdata/netdata-updater.sh --disable-auto-updates`

**Comment by MrZammler** [comment]
@TheOldMan2000 Hi!

Could you please check if updates don't mess with the service file anymore? 

Thanks!

**Comment by TheOldMan2000** [comment]
Hi there, hope you’re well!

I just ran the updater and it updated Netdata. I checked the
Netdata.service file and it was pointing to the wrong locations, so I
corrected it.

I ran the updater again and it updated Netdata to the same version, I
checked the Netdata.service and this time it was still set to the correct
paths, so I reactivated auto updates. I’ll report back after a couple of
nights, see how it goes.

Many thanks.

**Comment by TheOldMan2000** [comment]
Still seeing this:

```
systemctl status -l netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/usr/lib/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2023-02-09 20:49:51 GMT; 23min ago
 Main PID: 26988 (netdata)
   CGroup: /system.slice/netdata.service
           └─26988 /opt/netdata/bin/srv/netdata -D

Feb 09 20:49:51 vps71163.inmotionhosting.com systemd[1]: Started Real time performance monitoring.
Feb 09 20:52:12 vps71163.inmotionhosting.com systemd[1]: [/usr/lib/systemd/system/netdata.service:13] Unknown lvalue 'CacheDirectory' in section 'Service'
Feb 09 20:52:12 vps71163.inmotionhosting.com systemd[1]: [/usr/lib/systemd/system/netdata.service:14] Unknown lvalue 'StateDirectory' in section 'Service'
Feb 09 20:52:12 vps71163.inmotionhosting.com systemd[1]: [/usr/lib/systemd/system/netdata.service:15] Unknown lvalue 'LogsDirectory' in section 'Service'
Feb 09 20:52:12 vps71163.inmotionhosting.com systemd[1]: [/usr/lib/systemd/system/netdata.service:17] Unknown lvalue 'StateDirectoryMode' in section 'Service'
Feb 09 20:52:12 vps71163.inmotionhosting.com systemd[1]: [/usr/lib/systemd/system/netdata.service:18] Unknown lvalue 'CacheDirectoryMode' in section 'Service'
Feb 09 20:52:12 vps71163.inmotionhosting.com systemd[1]: [/usr/lib/systemd/system/netdata.service:19] Unknown lvalue 'LogsDirectoryMode' in section 'Service'

```

**Comment by TheOldMan2000** [comment]
Hello @MrZammler 
Bad news, the auto updater has broken Netdata.service again. Exactly same issue as before.

Regards

**Comment by MrZammler** [comment]
Hi @TheOldMan2000 

Can you please paste the contents of `/usr/lib/systemd/system/netdata.service` ?

**Comment by TheOldMan2000** [comment]
Sure…

# SPDX-License-Identifier: GPL-3.0-or-later
[Unit]
Description=Real time performance monitoring

# append here other services you want netdata to wait for them to start
After=network.target httpd.service squid.service nfs-server.service mysqld.service mysql.service named.service postfix.service chronyd.service

[Service]
Type=simple
User=netdata
Group=netdata
RuntimeDirectory=netdata
CacheDirectory=netdata
StateDirectory=netdata
LogsDirectory=netdata
RuntimeDirectoryMode=0775
StateDirectoryMode=0755
CacheDirectoryMode=0755
LogsDirectoryMode=2750
EnvironmentFile=-/etc/default/netdata
ExecStart=/opt/netdata/usr/sbin/netdata -D $EXTRA_OPTS

# saving a big db on slow disks may need some time
TimeoutStopSec=150

# restart netdata if it crashes
Restart=on-failure
RestartSec=30

# Valid policies: other (the system default) | batch | idle | fifo | rr
# To give netdata the max priority, set CPUSchedulingPolicy=rr and CPUSchedulingPriority=99
CPUSchedulingPolicy=batch

# This sets the scheduling priority (for policies: rr and fifo).
# Priority gets values 1 (lowest) to 99 (highest).
#CPUSchedulingPriority=1

# For scheduling policy 'other' and 'batch', this sets the lowest niceness of netdata (-20 highest to 19 lowest).
Nice=0

[Install]
WantedBy=multi-user.target

**Comment by MrZammler** [comment]
Hmm, thanks! This appears though to have `ExecStart=/opt/netdata/usr/sbin/netdata` in there.. Did you change them yourself?

We didn't change `EnvironmentFile`...

**Comment by TheOldMan2000** [comment]
Hello there,

No, I haven't changed and the updater has run a few times since I reactivated.

It's getting confusing and so frustrating, I'm sorry (!), but if you look back at the very first post on this topic, the EnvironmentFile is still the same and what I assume is the incorrect path generated by NetdataUpdater when it runs.

`EnvironmentFile=-/etc/default/netdata `

because my environment file is actually located at: 
`EnvironmentFile=/opt/netdata/etc/netdata/.environment`
which is where the installer originally placed it, and where I had previously manually changed it to.
I haven't changed it for some time, I believe the NetdataUpdater has set it:
`EnvironmentFile=-/etc/default/netdata `

Re the second line, ExecStart, looking back at the first post, it was:
`ExecStart=/usr/sbin/netdata -D $EXTRA_OPTS`

I thought it should be which is what I previously set it to: 
`ExecStart=/opt/netdata/bin/netdata -D $EXTRA_OPTS`

but now it is this:
`ExecStart=/opt/netdata/usr/sbin/netdata -D $EXTRA_OPTS`
 
Hopefully, I'll be able to move to AlmaLinux9 soon, but I would like to get this fixed for others still on CentOS7.9 and Virtuozzo if they are experiencing this.

**Comment by ilyam8** [comment]
`/opt/netdata/usr/sbin` is a symlink to `/opt/netdata/bin/netdata` in static installation.

```
$ ls -l /opt/netdata/usr/
total 0
lrwxrwxrwx. 1 netdata netdata  6 Feb 14 12:55 bin -> ../bin
drwxrwxr-x. 3 netdata netdata 21 Feb 14 02:46 lib
drwxrwxr-x. 3 netdata netdata 21 Feb 14 02:43 libexec
lrwxrwxrwx. 1 netdata netdata  1 Feb 14 12:55 local -> .
lrwxrwxrwx. 1 netdata netdata  6 Feb 14 12:55 sbin -> ../bin
drwxr-xr-x. 3 netdata netdata 21 Feb 14 02:46 share
```

**Comment by TheOldMan2000** [comment]
Okay, thanks for the clarification.
This is what mine says:

```
ls -l /opt/netdata/usr/
total 20
drwxrwxr-x  5 netdata netdata 4096 Feb 14 03:29 ./
drwxrwxr-x 11 netdata netdata 4096 Feb 14 03:29 ../
lrwxrwxrwx  1 netdata netdata    6 Feb 14 03:29 bin -> ../bin/
drwxrwxr-x  3 netdata netdata 4096 Feb 14 00:46 lib/
drwxrwxr-x  3 netdata netdata 4096 Feb 14 00:43 libexec/
lrwxrwxrwx  1 netdata netdata    1 Feb 14 03:29 local -> ./
lrwxrwxrwx  1 netdata netdata    6 Feb 14 03:29 sbin -> ../bin/
drwxr-xr-x  3 netdata netdata 4096 Feb 14 00:46 share/
```

BTW, when I run the line:

`$(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo`

It says I'm running Version: netdata v1.38.0-73-g5bfc81f85

but Netdata Cloud says I'm running Netdata Agent:
v1.37.0-231-g0f6be9ac2

Is that correct?

**Comment by TheOldMan2000** [comment]
I think this is still an open bug.

**Comment by ilyam8** [comment]
@TheOldMan2000 it seems there is something else because the bug is fixed - `ExecStart` is correct now.

I tested the following on Centos 7.9.2009:

```bash
# install
sudo ./kickstart.sh --static-only

# run updater
sudo /opt/netdata/usr/libexec/netdata/netdata-updater.sh --no-updater-self-update --force-update
```

I checked Netdata status after every step and there were no problems - Netdata service was active and running.

---

I suggest you:

> **Warning** do it if you are ok with deleting your historical (db) data.

- ensure you have only one Netdata installation
- uninstall Netdata

```bash
# as root user
# answer `y` to everything
/opt/netdata/usr/libexec/netdata/netdata-uninstaller.sh --yes
```
- install netdata
```bash
sudo ./kickstart.sh --static-only
```

**Comment by TheOldMan2000** [comment]
> @TheOldMan2000 it seems there is something else because the bug is fixed - `ExecStart` is correct now.
> 
> I tested the following on Centos 7.9.2009:
> 
> ```shell
> # install
> sudo ./kickstart.sh --static-only
> 
> # run updater
> sudo /opt/netdata/usr/libexec/netdata/netdata-updater.sh --no-updater-self-update --force-update
> ```
> 
> I checked Netdata status after every step and there were no problems - Netdata service was active and running.
> 
> I suggest you:
> 
> > Warning do it if you are ok with deleting your historical (db) data.
> 
> * ensure you have only one Netdata installation
> * uninstall Netdata
> 
> ```shell
> # as root user
> # answer `y` to everything
> /opt/netdata/usr/libexec/netdata/netdata-uninstaller.sh --yes
> ```
> 
>  * install netdata
> 
> ```shell
> sudo ./kickstart.sh --static-only
> ```

Thanks, I’m not so sure I agree, the Netdata Updater broke 2 lines in Netdata.service not 1. The line for EnvironmentFile is still incorrect after the updater runs.

This is what the lines are after ran again overnight, usually around 0315.

```
EnvironmentFile=-/etc/default/netdata
ExecStart=/opt/netdata/usr/sbin/netdata -D $EXTRA_OPTS
```

The first line is still wrong but maybe that’s okay, I don’t know.
I appreciate you tried but couldn’t replicate 

I had awful problems just trying to get it to install in the first place…
https://github.com/netdata/netdata/discussions/14229 

… but I’m happy to uninstall it and not bothered about the historical stats at all.

**Comment by TheOldMan2000** [comment]
Out of interest I ran this:

```
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --dry-run


--2023-02-15 18:27:22--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 104.21.13.159, 172.67.156.192, 2606:4700:3036::ac43:9cc0, ...
Connecting to my-netdata.io (my-netdata.io)|104.21.13.159|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

    [ <=>                                                                    ] 82,071      --.-K/s   in 0.001s  

2023-02-15 18:27:22 (72.3 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [82071]


 --- Using /tmp/netdata-kickstart-IeVDreLYSk as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
Would run command:\n[/tmp/netdata-kickstart-IeVDreLYSk]# sh -c cat "/opt/netdata/etc/netdata/.install-type" > "/tmp/netdata-kickstart-IeVDreLYSk/install-type" 
 OK 

/tmp/netdata-kickstart.sh: line 877: /tmp/netdata-kickstart-IeVDreLYSk/install-type: No such file or directory
 ERROR  Installer exited unexpectedly (0-1)

This is almost certainly the result of a bug. If you have time, please report it at https://github.com/netdata/netdata/issues/new/choose.
Would run command:\n[/root]# rm -rf /tmp/netdata-kickstart-IeVDreLYSk 
 OK 
```

**Comment by TheOldMan2000** [comment]
```
install netdata
sudo ./kickstart.sh --static-only

```

`sudo: ./kickstart.sh: command not found`

**Comment by TheOldMan2000** [comment]
So, even though I uninstalled Netdata as per your commands earlier, and it was not showing in Systemctl afterwards and after I deleted a few remaining leftover folders and files, I just saw that Netdata Cloud was still receiving data from my VPS.

I looked at HTOP and there are these processes presumably still transmitting data to the cloud:

![A81E140B-B976-4E3C-A5E3-3B3AA50D9869](https://user-images.githubusercontent.com/13329789/219144652-1b721609-3c2a-4a27-855e-27b95253233d.png)

I’m assuming this is the reason why there were 2 versions I was asking about it earlier?
I don’t actually know how I got 2 installs, why there was no warning or even an alert from Netdata itself, either of them. There should be some kind of check in place?

**Comment by TheOldMan2000** [comment]
Thanks, @CZAirwolf  really appreciate knowing it's not just me. I've given up for now with Netdata and have been using Grafana, Grafana Cloud and Prometheus, if only for some experience.

**Comment by MrZammler** [comment]
Hi! The fix for the issue with the systemd unit file was included in 1.38.1.

@CZAirwolf can you please do an `/opt/netdata/bin/srv/netdata -W buildinfo` ?

**Comment by MrZammler** [comment]
> I don’t actually know how I got 2 installs, why there was no warning or even an alert from Netdata itself, either of them. There should be some kind of check in place?

Not sure how to explain this, it appears it has started twice...

Assuming it is currently uninstalled, am I correct? There should not be a service file, nor any files under /opt/netdata. If you'd like we could go through the installation again.

Even if the `EnvironmentFile` shows `-/etc/default/netdata`, it should start and work correctly.

**Comment by CZAirwolf** [comment]
> Hi! The fix for the issue with the systemd unit file was included in 1.38.1.
> 
> @CZAirwolf can you please do an `/opt/netdata/bin/srv/netdata -W buildinfo` ?

I am sorry, my fault when copying new source file to ansible. Can confirm, 1.38.1 over 1.38.0 is fixed.

**Comment by TheOldMan2000** [comment]
> Assuming it is currently uninstalled, am I correct? There should not be a service file, nor any files under /opt/netdata. If you'd like we could go through the installation again.

Hello, correct it’s no longer installed. Thanks for the offer, I do miss it but not the stress in either installing it or configuring it. I don’t know why Netdata state it requires no configuration, I think that’s perhaps true only for the absolute server basics. It actually requires a lot time and resources to configure and troubleshoot. 

However I will try it again at some point, as when it works, it’s nice to have although I’ve never in years solved any kind of performance issue with it like long Apache TTFB metrics.

**Comment by MrZammler** [comment]
@TheOldMan2000 Sorry to hear that. Indeed there can be installation issues at times, indeed there was an issue here that you helped us fix and we thank you!

Do let us know if we can help when you decide to try it again.
