### ISSUE TITLE
[Feat]: Organize windows services and applications properly, they should not be displayed inside WMI collector

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#14295]
### Problem

All services and applications that are being monitored using the WMI collector currently show up within the WMI section in the TOC - this is not very usable or intuitive. 

The other issue is also that since we don't have nested sub-sections in TOC currently, there is absolutely no way to organize this properly. This leads to: 
 - Having 1 WMI section with way too many sub sections
 - Having a MS SQL section (for example) with no sub sections but 20+ charts in an endless scroll. Navigating to and finding the right context or chart is impractically hard to do.

For example, mssql and iis (see below)

![image](https://user-images.githubusercontent.com/24860547/213394067-e0318b6b-a206-4775-a252-253ef0f8c2e6.png)

### Description

If there is a service such as MS SQL or IIS or MS Exchange or whatever else that is running on a Windows server and being monitored via WMI by Netdata. The charts from these services should be organized in separate section. 

For example there should be a separate section called "Microsoft SQL Server" with sub sections underneath which the metrics are arranged properly. This should not sit underneath WMI.

In fact here's how the entire thing should finally look like:

- The node metrics from the windows server (cpu, memory etc.) should show up under the existing CPU, Memory sections with the Windows server being treated as a separate node (This is a separate feature on the agent side - TBD, link to Github issue tracking this)

- Any service or application running on Windows and being monitored via WMI should be a separate section (Holds true for MS SQL Server, IIS or anything else we support in the future)

- There should still be a WMI section, but it should only (IMO) show the WMI collector related metrics such as `wmi.service_status` and `wmi.collector_status`

### Importance

must have

### Value proposition

1. Make Windows monitoring actually usable and user friendly - monitoring a service running on Windows should be just like the normal Netdata experience of monitoring a service. 

### Proposed implementation

This feature should implement the work required to move specific service and application metrics collected via WMI into separate sections with the service or application name. 

Sub sections should be added (like we do for other collectors) to organize metrics and make navigation possible for the user.

**Comment by ilyam8** [comment]
I added the needed functionality to go.d.plugin, @thiagoftsm will update iis/mssql/etc charts family/context.
