### ISSUE TITLE
[NotABug]: sudo validate error

### ISSUE THREAD

**Issue by PolluxAndCastor** [netdata/netdata#14291]
### Bug description

Hello,
After installing v1.37.1 (previously on 1.31), message in logs from every servers : 
`netdata : command not allowed ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=validate`

This is the same issue as #4473 and fixed in #4477

### Expected behavior

usage of sudo -n -l in https://github.com/netdata/netdata/blob/51565d55e92b6f814a09ca87d3c77a40acba576c/collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py#L173
and no error message 

### Steps to reproduce

1. Install v1.37.1
2. restart netdata
3. observe system logs

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
Version: netdata v1.37.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-bundled-protobuf' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-dependency-tracking' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Install type: binpkg-rpm
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
Hi, @PolluxAndCastor. I think just replacing `-n -v` with `-n -l COMMAND` won't do.

There was a reason I made [this commnit](https://github.com/netdata/go.d.plugin/pull/973/commits/1efd6067f0ac7aea3696c40cc1db3e8e080bfaa5) (run `-n -v` before `-n -l COMMAND`). I don't remember why, but I will check it.

**Comment by PolluxAndCastor** [comment]
> Do you use the collector? I'm not sure how this is possible given that the collector is disabled by default.

The whole python.d.plugin is enabled in `/etc/netdata/python.d.conf`, so that's probably why :
```
# Enable / disable the whole python.d.plugin (all its modules)
enabled: yes
```
But this is the default file that come with the standard installation.

**Comment by PolluxAndCastor** [comment]
Well, even setting this to `adaptec_raid: no` and restarting the service produce the same error in the logs.
Only allowing netdata to `sudo /sbin/arcconf` doesn't produce an error in the system log
```
Jan 19 08:44:22 sd01-l01-sds04.preprod.storage.s1.p.fti.net sudo:  netdata : TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=validate
```

**Comment by ilyam8** [comment]
adaptec_raid is [disabled by default](https://github.com/netdata/netdata/blob/c1908d3163185cf65a139edeb11a165a10eca1e9/collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py#L13) - python.d.plugin [skips disabled modules](https://github.com/netdata/netdata/blob/c1908d3163185cf65a139edeb11a165a10eca1e9/collectors/python.d.plugin/python.d.plugin.in#L619-L621) if they are not explicitly enabled (`name: yes`) in python.d.conf.

So it is either explicitly enabled in your config or it is not adaptec_raid.

**Comment by PolluxAndCastor** [comment]
That's where i'm at a lost.
Even if it's explicitely disabled in the conf (`adaptec_raid: no`), _something_ tries to validate `sudo arcconf` as seen in the system `/var/log/auth.log`.
The only reference to `arcconf` is in `python.d/adaptec_raid.chart.py`

```
[root@xxxxx  ~]# date && grep adaptec /etc/netdata/python.d.conf 
Thu Jan 19 11:38:00 CET 2023
adaptec_raid: no
[root@xxxxx ~]# grep adaptec /var/log/netdata/error.log
2023-01-19 11:32:57: netdata INFO  : HEALTH[xxxxx ] : Health configuration template 'adaptec_raid_ld_status' already exists for host 'xxxxx '.
2023-01-19 11:32:57: netdata INFO  : HEALTH[xxxxx ] : Health configuration template 'adaptec_raid_pd_state' already exists for host 'xxxxx '.
2023-01-19 11:32:59: python.d INFO: plugin[main] : [adaptec_raid] is disabled in the configuration file, skipping it
[root@xxxxx  ~]# grep validate /var/log/auth.log | tail -1
Jan 19 11:32:57 xxxxx  sudo:  netdata : TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=validate
```

**Comment by ilyam8** [comment]
> Jan 19 11:32:57 xxxxx  sudo:  netdata : TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=validate

This line doesn't say it is adaptec_raid. `arcconf` doesn't get executed when the collector is disabled. The only collector that uses `sudo` and is enabled by default is [nvme](https://github.com/netdata/go.d.plugin/tree/master/modules/nvme#nvme-devices-monitoring-with-netdata).

**Comment by PolluxAndCastor** [comment]
Thank you for your time and help in this matter @ilyam8, I'm just trying to understand what's going on here, not to be insolent.

The thing is :
The only reference to `sudo -v -l` or to `arcconf` that I can find in `/usr/libexec/netdata/` is from the file `python.d/adaptec_raid.chart.py`

If i have the `sudo arcconf` for netdata, no error.
If I don't have the sudo, then I have the error message with 
> sudo:  netdata : command not allowed

So I am to believe that it all come to this. Am I misled to a false route ? 

Any help to dig deeper is appreciated.

**Comment by ilyam8** [comment]
@PolluxAndCastor what I am saying is 

- neither `sudo` nor `arcconf` get executed by the adaptec_raid collector if it is disabled (default).
- I am not really sure why you keep saying that `adaptec_raid` is the cause. Can not be you haven't enabled it.

Try disabling the whole python.d.plugin and see if you still seeing that line.

**Comment by PolluxAndCastor** [comment]
@ilyam8 thanks it's clear now.
disabling nvme in go.d.conf stop the log message indeed
(disabling the whole python.d.plugin had no effect)

So it's the down to the nvme go.d plugin and the first link you posted, now I understand.

**Comment by PolluxAndCastor** [comment]
I will make the required changes to the deployment to avoid this issue.
Thank you for your time and effort.

**Comment by ilyam8** [comment]
@PolluxAndCastor a better approach is to allow netdata to execute `nvme` with `sudo` - Netdata will be able to track the performance and health of NVMe devices (and notify you if there are any problems).

**Comment by PolluxAndCastor** [comment]
> @PolluxAndCastor a better approach is to allow netdata to execute `nvme` with `sudo` - Netdata will be able to track the performance and health of NVMe devices (and notify you if there are any problems).

Yes, sorry it wasn’t clear but that’s exactly what I did.
Thanks again for your help in the matter and sorry for the inconvenience.
