### ISSUE TITLE
[Question]: Cannot install and use it without root

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/netdata#14308]
### Bug description

Hi thank for netdata! However, I fail to install/use it on a machine without root permission.

### Expected behavior

can use

### Steps to reproduce

install it with non-root user

### Installation method

kickstart.sh

### System info

```shell
ubuntu, but the main thing is that I want to install without root permission
```

### Netdata build info

```shell
n/a
```

**Comment by Dim-P** [comment]
Hi @fzyzcjy , thank you for reporting this issue!

You can install Netdata without root permissions, but it's a little bit more complicated than just using the `kickstart.sh` script. Please also see https://github.com/netdata/netdata/issues/3948#issuecomment-441292100 and https://github.com/netdata/netdata/issues/12427#issue-1170911127 . To re-iterate what's been said in the linked tickets:

1. Clone Netdata from Git: `git clone https://github.com/netdata/netdata.git netdata && cd netdata`
2. Initialize the (optional) Git submodules: `git submodule update --init --recursive`
3. Install the required packages: `./packaging/installer/install-required-packages.sh netdata`
4. Install Netdata on an `INSTALL_PATH` where you have the right permissions: `./netdata-installer.sh --install-prefix /INSTALL_PATH`

Some collectors that need to run with root permissions will not work, if you install it this way. 

Please let me know if this method works for you, so I can close the ticket.

**Comment by fzyzcjy** [comment]
That you so much! I will try it and feedback :)

**Comment by fzyzcjy** [comment]
Well, the install-required-packages still needs root :(

<details>

```
(jychen_main) jychen@rail-PR4764GW:/data/jychen/temp/netdata$ ./packaging/installer/install-required-packages.sh netdata
Loading /etc/os-release ...

/etc/os-release information:
NAME            : Ubuntu
VERSION         : 16.04.6 LTS (Xenial Xerus)
ID              : ubuntu
ID_LIKE         : debian
VERSION_ID      : 16.04

We detected these:
Distribution    : ubuntu
Version         : 16.04
Codename        : 16.04.6 LTS (Xenial Xerus)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 3 

Searching for distro_sdk ...
Searching for libatomic ...
 > Checking if package 'libatomic1' is installed...
Searching for autoconf_archive ...
 > Checking if package 'autoconf-archive' is installed...
Searching for autogen ...
 > Checking if package 'autogen' is installed...
dpkg-query: no packages found matching autogen
Searching for libz_dev ...
 > Checking if package 'zlib1g-dev' is installed...
Searching for libuuid_dev ...
 > Checking if package 'uuid-dev' is installed...
Searching for libmnl_dev ...
 > Checking if package 'libmnl-dev' is installed...
dpkg-query: no packages found matching libmnl-dev
Searching for json_c_dev ...
 > Checking if package 'libjson-c-dev' is installed...
dpkg-query: no packages found matching libjson-c-dev
Searching for libuv ...
 > Checking if package 'libuv1-dev' is installed...
Searching for lz4 ...
 > Checking if package 'liblz4-dev' is installed...
dpkg-query: no packages found matching liblz4-dev
Searching for openssl ...
 > Checking if package 'libssl-dev' is installed...
Searching for libelf ...
 > Checking if package 'libelf-dev' is installed...
dpkg-query: no packages found matching libelf-dev

The following command will be run:

NOTE: Running apt-get update and updating your APT caches ...
sudo apt-get update 
sudo apt-get install autoconf-archive autogen libelf-dev libjson-c-dev liblz4-dev libmnl-dev 


Press ENTER to run it > 
NOTE: Running apt-get update and updating your APT caches ...
```

**Comment by fzyzcjy** [comment]
Sure I know that. The problem is, I do not have root permission (i.e. no sudo) :(

**Comment by Dim-P** [comment]
> Sure I know that. The problem is, I do not have root permission (i.e. no sudo) :(

I am afraid I don't have an answer to that then. Can you not ask your system administrator to install the required packages for you? It's a one-off action (unless we add any further dependencies in future updates). 

Bear in mind you will be quite limited in what you can monitor if you don't install Netdata using superuser permissions anyway, so even if you manage to do that, not sure how useful it would be for your use case.

**Comment by fzyzcjy** [comment]
I see. Thank you!

**Comment by ChillarAnand** [comment]
> Bear in mind you will be quite limited in what you can monitor if you don't install Netdata using superuser permissions anyway, so even if you manage to do that, not sure how useful it would be for your use case.

Is it possible to monitor CPU/ram usage without sudo?
