### ISSUE TITLE
[Feat]: Updater should support ‘silent’ updates that only show output if there are errors.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#14343]
### Problem

Among some users, the it is strongly preferred for automation to be silent as long as everything is working. Currently, the updater script does not support operating like this without using an external wrapper.

### Description

The updater script should support running without producing any output unless errors are encountered.

### Importance

really want

### Value proposition

Users who only want to see emails from the updater when an update failed can do so.

**Comment by ilyam8** [comment]
I think this has already been implemented. The update script, if not running on a terminal/ci, logs to a file which, if the update is successful, is deleted (no output).
