### ISSUE TITLE
[Bug]: Kickstart.sh fails to pull static builds when using Busybox wget

### ISSUE THREAD

**Issue by Dim-P** [netdata/netdata#14346]
### Bug description

As the title says, `kickstart.sh` will fail if Busybox `wget` is used instead of GNU `wget` or `curl`. 

The problem seems to be this command here:
```
run sh -c "wget --max-redirect=0 ${url} 2>&1 | grep Location | cut -d ' ' -f2  | grep -o '[^/]*$'" || return 1
```

First, Busybox `wget` doesn't have the `--max-redirect=0` option and secondly, it doesn't return the correct output to `grep Location` from. It can be fixed like this, but not sure what the effect of removing `--max-redirect=0` is:

```
run sh -c "wget -S ${url} 2>&1 | grep Location | head -n 1 | sed 's/^[ \t]*//;s/[ \t]*$//' | cut -d ' ' -f2  | grep -o '[^/]*$'" || return 1
```

@netdata/agent-sre I would appreciate your input here if this is the correct approach to fix this and I can create a PR.

### Expected behavior

`kickstart.sh` should demonstrate identical  behaviour using any version of `wget`. 

### Steps to reproduce

1. Use Alpine or some other distribution that uses Busybox `wget` by default.
2. Run `kickstart.sh` without previously installing GNU `wget` or `curl`.
3. `kickstart.sh` will fail to download static builds.

### Installation method

kickstart.sh

### System info

```shell
Linux 9974c8ab6b55 6.1.6-203.fsync.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC TKG Thu Jan 19 19:16:07 UTC 2023 x86_64 Linux
/etc/alpine-release:3.17.1
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.17.1
/etc/os-release:PRETTY_NAME="Alpine Linux v3.17"
```

### Netdata build info

```shell
-
```

**Comment by Ferroin** [comment]
Semantically here, we’re specifically trying to get the target of the first redirect returned by the particular URL we’re checking. IOW, we need the semantic equivalent of `readlink`, not the semantic equivalent of `realpath`, which is why we had `--max-redirects=0`.

At the moment, this is only used to query specific URLs on GitHub, and all of those URLs appear to only use a single redirect, so removing that _should_ be fine, though it will require more than just using `-S` (we need to discard the page itself).

**Comment by Dim-P** [comment]
> Semantically here, we’re specifically trying to get the target of the first redirect returned by the particular URL we’re checking. IOW, we need the semantic equivalent of `readlink`, not the semantic equivalent of `realpath`, which is why we had `--max-redirects=0`.
> 
> At the moment, this is only used to query specific URLs on GitHub, and all of those URLs appear to only use a single redirect, so removing that _should_ be fine, though it will require more than just using `-S` (we need to discard the page itself).

Thanks for the explanation @Ferroin , I get it now. Adding `-O /dev/null` should do the job?
```
run sh -c "wget -S -O /dev/null ${url} 2>&1 | grep Location | head -n 1 | sed 's/^[ \t]*//;s/[ \t]*$//' | cut -d ' ' -f2  | grep -o '[^/]*$'" || return 1
```

**Comment by Ferroin** [comment]
> 
> Thanks for the explanation @Ferroin , I get it now. Adding `-O /dev/null` should do the job?
> 
> ```
> run sh -c "wget -S -O /dev/null ${url} 2>&1 | grep Location | head -n 1 | sed 's/^[ \t]*//;s/[ \t]*$//' | cut -d ' ' -f2  | grep -o '[^/]*$'" || return 1
> ```

I believe so.

**Comment by Dim-P** [comment]
On further investigation, seem like the updater doesn't work either with busybox `wget`, that will need to be fixed too.

**Comment by Ferroin** [comment]
> That seems to work but there is another issue here:
> 
> ```
> wget -q -O - --no-check-certificate \
>     --method POST \
>     --timeout=1 \
>     --header 'Content-Type: application/json' \
>     --body-data "${REQ_BODY}" \
>      "${TELEMETRY_URL}" > /dev/null
> ```

We cannot completely work around this, but we should probably try to use cURL from the static install if it exists.

> On further investigation, seem like the updater doesn't work either with busybox wget, that will need to be fixed too.

This should just be the same changes in the redirect handling.

**Comment by Dim-P** [comment]
> We cannot completely work around this, but we should probably try to use cURL from the static install if it exists.

Do we need `--no-check-certificate` ? What about:
```
wget -q -O - \
      -T 1 \
      --header 'Content-Type: application/json' \
      --post-data "${REQ_BODY}" \
      "${TELEMETRY_URL}" > /dev/null
```

`curl`  will be used anyway if it exists, as it is checked before the existence of `wget`.

**Comment by Ferroin** [comment]
> > We cannot completely work around this, but we should probably try to use cURL from the static install if it exists.
> 
> Do we need `--no-check-certificate` ? What about:
> 
> ```
> wget -q -O - \
>       -T 1 \
>       --header 'Content-Type: application/json' \
>       --post-data "${REQ_BODY}" \
>       "${TELEMETRY_URL}" > /dev/null
> ```

There was a particular reason we were specifically avoiding certificate checks, but I do not recall for certain what it was (I think it had something to do with reliability on old systems, keep in mind we are still stuck supporting systems that are more than a decade old).

> `curl` will be used anyway if it exists, as it is checked before the existence of `wget`.

If it’s in `$PATH`, but we should also be trying to use a copy from the static build if there is a static build installed and there is no system copy. That’s a separate issue though.

**Comment by Dim-P** [comment]
@Ferroin OK I see. I will just handle the BusyBox edge case then that fails anyway, and leave the existing `wget` call as is. If BusyBox `wget` fails only when there isn't a valid certificate, at least it's an improvement of what we have now. 

Re. `curl`, I wasn't aware we bundle our own copy with static builds, in which case what you say makes sense. But I agree that's a separate issue, not to be resolved as part of this.

**Comment by Ferroin** [comment]
> Re. `curl`, I wasn't aware we bundle our own copy with static builds, in which case what you say makes sense. But I agree that's a separate issue, not to be resolved as part of this.

Agreed, I’ve opened https://github.com/netdata/netdata/issues/14401 for that.
