### ISSUE TITLE
[Feat]: configuration option to disable INFO logs

### ISSUE THREAD

**Issue by km-manzm** [netdata/netdata#14388]
### Problem

Setting configuration to

```
[logs]
debug=none
error=/var/log/netdata/error.log
access=none
```

i assumed that only ERRORS are being written to the console. ( I am using the docker image) 
However many plugins are giving many info logs, which can also be seen on the console.

### Description

It would be nice if INFO logs wouldn't be handled like ERROR logs.

A new configuration option would be nice, e.g.

```
debug=none
access=none
**info=none**
error=/var/log/netdata/error.log
```

so i can mute all info logs from the plugins.

### Importance

must have

### Value proposition

1. only get ERROR logs, when only ERROR logs are enabled
2. Immediately see on the console if there is an ERROR running netdata; no need to scroll up and down because INFO logs are "hiding" the error logs

**Comment by ilyam8** [comment]
@thiagoftsm I think the proper solution here is to add a severity-level configuration option. I think we can start with error/info: info is the default, if error - no info level messages.

**Comment by andrewm4894** [comment]
Just wondering - can log level be configured separately for each collector? e.g say you want info on one collector only and error on everything else.

Just wondering if that is something we might think about here too or if too complex for this specific discussion?

**Comment by ilyam8** [comment]
If by this specific discussion, you mean this issue then it doesn't belong here. I suggest opening a GH discussion and if you decide to do so please provide several examples of when/why you need that. Looks very questionable to me overall.

**Comment by thiagoftsm** [comment]
> Just wondering - can log level be configured separately for each collector? e.g say you want info on one collector only and error on everything else.

Technically speaking it is completely possible.
The first commits I pushed I addressed only netdata core messages, now I am starting working with collectors and I am already considering this possibility for the future.

> Just wondering if that is something we might think about here too or if too complex for this specific discussion?

On the other hand, what @ilyam8 said looks like the more correct here, considering this issue will be closed as soon we merge the PR open yesterday.

**Comment by thiagoftsm** [comment]
@andrewm4894 for 9 external collectors and all internal collectors the option `severity-level` will allow users to select the level they want per collector, please, take  look in the PR (you are a reviewer) and verify if I already delivered what you want.

**Comment by ilyam8** [comment]
We added the `severity level` option to `[logs]`. Setting it to `error` (or `err`) will remove all INFO messages from `error.log` and `collector.log` (starting from tomorrow nightly).
