### ISSUE TITLE
[Feat]: Show UPS load in watts from nut

### ISSUE THREAD

**Issue by Ashrin0** [netdata/netdata#14396]
### Problem

Power consumption is listed as a percentage.  Would like to show in watts just as was done for data from APCUSD in [issue #12959](https://github.com/netdata/netdata/issues/12959).

### Description

Currently, Netdata graphs UPS load in percent (this is nut's ups.load value). It would be really handy to also see load in watts. 

Can be calculated by multiplying ups.load by ups.realpower.nominal 

### Importance

really want

### Value proposition

1. Ability to view actual server power draw, and track it over time
2. Easily use this data to track electricity costs to run a server

**Comment by kerukun** [comment]
upsc output:  
````
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 20
battery.mfr.date: CPS
battery.runtime: 2050
battery.runtime.low: 300
battery.type: PbAcid
battery.voltage: 13.6
battery.voltage.nominal: 12
device.mfr: CPS
device.model: ABST600
device.type: ups
driver.name: usbhid-ups
driver.parameter.bus: 003
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.productid: 0501
driver.parameter.synchronous: no
driver.parameter.vendorid: 0764
driver.version: 2.7.4
driver.version.data: CyberPower HID 0.4
driver.version.internal: 0.41
input.transfer.high: 140
input.transfer.low: 96
input.voltage: 120.0
input.voltage.nominal: 120
output.voltage: 120.0
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.delay.start: 30
ups.load: 20
ups.mfr: CPS
ups.model: ABST600
ups.productid: 0501
ups.realpower.nominal: 360
ups.status: OL
ups.test.result: No test initiated
ups.timer.shutdown: -60
ups.timer.start: 0
ups.vendorid: 0764

**Comment by ilyam8** [comment]
Hi, @Ashrin0. Can you test #14407?

**Comment by Ashrin0** [comment]
The new chart doesn't appear in netdata after building and running the branch.  I haven't done much with netdata besides running the ubuntu package. Are there any other steps besides pulling the branch and building it?  Any configuration to do?

**Comment by ilyam8** [comment]
There is no need to build that branch you can just:

```bash
# stop netdata service
systemctl stop netdata service
# download updated nut.chart.sh
wget https://raw.githubusercontent.com/ilyam8/netdata/nut_add_load_usage/collectors/charts.d.plugin/nut/nut.chart.sh
# make it executable
chmod +x nut.chart.sh
# replace nut script with updated version
cp nut.chart.sh /usr/libexec/netdata/charts.d/nut.chart.sh
# start netdata service
systemctl start netdata service
```

- Do you see load usage chart?
- If not, do you use the local dashboard or Cloud UI?
- Do other nut chart appear?

**Comment by Ashrin0** [comment]
Load usages appears now.  My install had the nut.chart.sh at /usr/lib/netdata/charts.d/ if that matters.  UPS Load Usage appears to have a math error.  Showing between 7,000 Watts and 8,600 Watts.  Variations track with UPS Load chart.  
![ups load](https://user-images.githubusercontent.com/3258475/216145715-4d9049ae-0078-43d7-98c6-b53bfbd0df07.PNG)

Local dashboard.  Charts appearing: UPS Load, UPS Load Usage, UPS Charge, UPS Runtime, UPS Battery Voltage, UPS Temperature, UPS Input Voltage, UPS Input Current, UPS Input Frequency, UPS Output Voltage.

**Comment by ilyam8** [comment]
@Ashrin0 fixed the value in https://github.com/netdata/netdata/pull/14407/commits/c53472eaeb329d1a96298344bd7850690041f898. [Try this again](https://github.com/netdata/netdata/issues/14396#issuecomment-1412572787) - should be ok.

**Comment by ilyam8** [comment]
Merged, will be in tomorrow's nightly release.
