### ISSUE TITLE
[Bug]: apps.pligin charts have gaps after recent updates.

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#14408]
### Bug description

Charts created by apps.plugin have gaps (like no data collected). In case of restart this sometimes get fixed, but in most cases it does not. No error printed into the log. Sometimes "Applications" group is not even available on Netdata web interface, and in case it is present, all the charts have gaps.
Same happens to versions 1.36 and newer. Removal of netdata cache, browser version change (both Firefox and Chrome) didn't help. With downgrade to 1.35.1 the problem appeared to be gone.
Notable that python and go plugins work without issues.

### Expected behavior

gap-less charts and stable apps.plugin

### Steps to reproduce

1. Install netdata 1.36 or newer
2. configure apps_groups.conf and start netdata 
3. open in browser and scroll to "Applications"

### Installation method

other

### System info

```shell
Linux 6.1.8-gentoo #1 SMP PREEMPT_DYNAMIC Fri Jan 27 20:40:53 CET 2023 x86_64 AMD EPYC 7451 24-Core Processor AuthenticAMD GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.9
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:VERSION_ID="2.9"
```

### Netdata build info

```shell
Version: netdata v1.37.1
Configure options:  '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--datarootdir=/usr/share' '--disable-dependency-tracking' '--disable-silent-rules' '--docdir=/usr/share/doc/netdata-1.37.1' '--htmldir=/usr/share/doc/netdata-1.37.1/html' '--libdir=/usr/lib64' '--localstatedir=/var' '--with-user=netdata' '--without-bundled-protobuf' '--disable-cloud' '--enable-jsonc' '--disable-plugin-cups' '--enable-dbengine' '--enable-plugin-nfacct' '--disable-plugin-freeipmi' '--disable-exporting-kinesis' '--enable-lto' '--disable-exporting-mongodb' '--disable-exporting-prometheus-remote-write' '--disable-plugin-xenstat' '--enable-x86-sse' '--with-zlib' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CFLAGS=-mtune=native -O2 -pipe' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'CXXFLAGS=-mtune=native -O2 -pipe' 'PKG_CONFIG_PATH=/var/tmp/portage/net-analyzer/netdata-1.37.1/temp/python3.10/pkgconfig'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO (by user request)
    ACLK:                       NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

lines from netdata log related to apps.plugin:
```
2023-02-01 21:53:23: netdata INFO  : PLUGINSD[apps] : connected to '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 36645
2023-02-01 21:53:23: apps.plugin ERROR : MAIN : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf' (errno 2, No such file or directory)
2023-02-01 21:53:23: apps.plugin INFO  : MAIN : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib64/netdata/conf.d/apps_groups.conf'
2023-02-01 21:53:23: apps.plugin INFO  : MAIN : Loaded config file '/usr/lib64/netdata/conf.d/apps_groups.conf'
2023-02-01 21:53:23: apps.plugin INFO  : MAIN : started on pid 36645
2023-02-01 21:53:23: apps.plugin INFO  : APPS_READER : set name of thread 36681 to APPS_READER
2023-02-01 21:53:24: apps.plugin INFO  : MAIN : Using now_boottime_usec() for uptime (dt is 5 ms)
```

**Comment by ekexcello** [comment]
A small update. After running smoothly for certain time, charts on 1.35 also started to be displayed with gaps.

**Comment by ilyam8** [comment]
Hi, @ekexcello. 

- Do you have this problem on other systems? (assuming you have Netdata installed on more than one host).
- Can you post a screenshot with gaps? Is it only apps.plugin?
- Can you post a screenshot "Netdata Monitoring => apps.plugin"?
- Is it possible to try the latest master?

**Comment by ekexcello** [comment]
Hello @ilyam8
Thank you for your quick reply.
The problem happens on several installations, kernel and software configurations are the very same.
The problem affects only apps plugin and also happens with latest master. The good point however is that it doesn't happen on absolutely all the installations, but nevertheless it happens on many of them.
Notable that after restart Application section disappear completely on at least two hosts while the plugin itself is visible in the process list.
Will provide screenshots later today.

**Comment by ekexcello** [comment]
Hello @ilyam8
Sorry for the delay. Without applications plugin troubleshooting takes much longer, netdata is a kind of instruments that is hard to replace.
So, the screenshots. It seems to be impossible to attach them here directly, so please find them with following these links:
[Apps.plugin - applications](https://railglorg.net/xaeteeyo0uo9Oighoi9ibikohc3Gaer4ach9lie7ooKiph2chohSaechaiy9ioKu/apps_resources.png)
[Apps.plugin - user groups](https://railglorg.net/xaeteeyo0uo9Oighoi9ibikohc3Gaer4ach9lie7ooKiph2chohSaechaiy9ioKu/apps_usergroups.png)
[Apps.plugin - users](https://railglorg.net/xaeteeyo0uo9Oighoi9ibikohc3Gaer4ach9lie7ooKiph2chohSaechaiy9ioKu/apps_users.png)
[netdata monitoring - apps.plugin](https://railglorg.net/xaeteeyo0uo9Oighoi9ibikohc3Gaer4ach9lie7ooKiph2chohSaechaiy9ioKu/apps_plugin.png)
[netdata monitoring - apps.plugin, from another server](https://railglorg.net/xaeteeyo0uo9Oighoi9ibikohc3Gaer4ach9lie7ooKiph2chohSaechaiy9ioKu/apps_plugin.server2.png)

**Comment by ilyam8** [comment]
@ekexcello the problem is that ~1.2 million open file descriptors by the `sql` group. It takes more than 1 second to read them. 

You can disable reading `/proc/PID/fd/` by adding `no-files`

```
[plugin:apps]
        # update every = 1
        command options = no-files
```

**Comment by ekexcello** [comment]
Thank you very much, this was really the reason.
Is it possible to exclude calculations of number of open files for some specific group (or daemon) only?

**Comment by ilyam8** [comment]
No, it is a global option.

**Comment by ekexcello** [comment]
Reasonable. This amount of open files is mariadbd issue and is abnormal in fact.
Thank you for your advise and help.
