### ISSUE TITLE
[Bug]: static build components are outdated

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#14404]
### Bug description

Static build components are outdated, there are new versions for:
 - bash
 - curl
 - ioping
 - openssl

### Expected behavior

The components listed above are updated to the latest stable at the moment. Special attention should be paid to updating openssl package - need to test TLS communication (web-server, streaming).

### Steps to reproduce

1. Check the version of the used component vs the available latest stable.

### Installation method

kickstart.sh

### System info

```shell
n/a
```

### Netdata build info

```shell
n/a
```

**Comment by Dim-P** [comment]
Can this one be closed as https://github.com/netdata/netdata/pull/14450 is merged, or are we waiting for bash to be updated too?

**Comment by ilyam8** [comment]
No, it is just `Fixes #12345` wasn't used.
