### ISSUE TITLE
dygraph sparklines should provide a method to merge the dimensions

### ISSUE THREAD

**Issue by RiaanBurger** [netdata/netdata#1446]
A CPU graph in gauge form nicely combines what seems to be all the dimensions for you.

```html
<div data-netdata="system.cpu"
  data-chart-library="gauge"
  data-title="CPU"
```

But how would one make a single-line dygraph sparkline of that combined set of dimensions (and output the single text value of it)?

----

```html
<div data-netdata="system.swap"
  data-chart-library="dygraph"
  data-dygraph-theme="sparkline"
  data-dimensions="used"
  data-append-options="percentage"
  data-show-value-of-used-at="swapused_value"
```

Shows a nice percentage value, but then:

```html
<span id="swapused_value"></span>
```

Shows a percentage (as desired) while one hover-moves over the sparkline, but when not hover-moving over the spakline it shows the actual value of the *used* dimension in MB. Is there a way to show the percentage used in text?

---

Thank you for an incredible piece of software to get to know these quiet holiday evenings!

**Comment by ktsaou** [comment]
Hm... you are right... it cannot be done with `dygraph`....

It can be done with `sparkline` or `piety` charts though... (check http://your.netdata.ip:19999/dashboard.html - it is my chart libraries testbed).

Hm... how did I manage to do it like that? I guess I was too excited that I managed to have a sparkline with dygraph... :)

I will leave this ticket open to fix it.

Merry Christmas to you too!

**Comment by RiaanBurger** [comment]
Thank you Costa. C-level, so well versed in actual development too and an unexpectedly prompt reply on a holiday night. An example for every company to strive for! Didn't know if I should be season specific, but I guess I can wish you a merry Christmas too now ;-)

**Comment by ktsaou** [comment]
@gmosx 	this issue is about flattening multiple dimensions into one. It is a nice feature for a few cases. The netdata query engine can do it, so we have to support it at the dashboard somehow.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
