### ISSUE TITLE
[Feat]/[BUG]: eBPF improvement

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#14477]
### Problem

When `eBPF.plugin` is loaded integrated with `apps` and `cgroups`, events like https://github.com/netdata/netdata/issues/14406#issuecomment-1416968648 are happening. 

To fix this issue we are going to add some charts and alerts to monitor plugin behavior. We are also going to modify the internal code to use `ARAL`, and load/unload eBPF programs during runtime.

### Description

- [x] Modify integration between eBPF and apps/cgroups. https://github.com/netdata/netdata/pull/14462
- [x] Modify threads not modified in first PR. https://github.com/netdata/netdata/pull/14591
- [x] RH modified kernel, so we also have to bring a fix. https://github.com/netdata/kernel-collector/pull/324
- [x] Separate Oracle kernels from "normal" kernels. https://github.com/netdata/kernel-collector/pull/326
- [x] Create helpers to count stats and  make charts to monitor memory allocated and size of hash tables (user ring). https://github.com/netdata/netdata/pull/14623
- [X] Modify legacy codes (Kernel-collector repo). https://github.com/netdata/kernel-collector/pull/327
- [ ] Modify CO-RE codes (ebpf-co-re repo). https://github.com/netdata/ebpf-co-re/pull/44
- [ ] Charts used to monitor number of elements inside hash tables and memory used (kernel ring).
- [ ] Alerts for ebpf.plugin
- [ ] Functions to deliver bandwidth per PID
- [ ] Modify the way eBPF parse arguments, because it is not matching other collectors

### Importance

must have

### Value proposition

1. eBPF will use less resource from host
2. Better monitoring of plugin behavior
3. Additional information per PID to cloud.

**Comment by ilyam8** [comment]
@thiagoftsm do we still need to keep this issue open?
