### ISSUE TITLE
[Bug]: remote write exporter to Thanos

### ISSUE THREAD

**Issue by chi-miel** [netdata/netdata#14482]
### Bug description

Hi,

I'm trying to send metrics to Thanos ([link](https://thanos.io/)), so I've set up an endpoint to receive the metrics via a prometheus remote write.

I saw that Netdata can send metrics via (https://learn.netdata.cloud/docs/agent/exporting/prometheus/remote_write).

It may not works properly (I see only my metrics Netdata health arriving in Thanos) but I have several metrics that are dropped(all other metrics).

After searching on the Thanos side, it turns out that Thanos expects to receive the metrics with sorted labels (on Thanos Github : https://github.com/thanos-io/thanos/issues/5499 and https://github.com/thanos-io/thanos/pull/5508).

I have this type of log coming into my Thanos:
`Feb 09 11:01:19 ******************************** thanos[58217]: level=warn name=******************************** -receive ts=2023-02-09T10:01:19.530954873Z caller=writer.go:167 component=receive component=receive-writer tenant=********* msg="Error on series with out-of-order labels" numDropped=2096`

The problem is my Netdata agent because when I put a Prometheus in remote write mode between my Netdata agent and my Thanos everything is fine.

Can you confirm that the Netdata agent does not sort the labels before sending the metrics and if so, is it possible to implement this feature?

Thank you

### Expected behavior

Netdata should sort the metrics before sending them.

### Steps to reproduce

1. set up Thanos with a receiver (https://thanos.io/tip/components/receive.md/)
2. set up Netdata Agent to export metrics with the remote write exporter (https://learn.netdata.cloud/docs/agent/exporting/prometheus/remote_write)
3. watch log from thanos receiver

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
/etc/centos-release:Rocky Linux release 8.7 (Green Obsidian)
/etc/os-release:NAME="Rocky Linux"
/etc/os-release:VERSION="8.7 (Green Obsidian)"
/etc/os-release:ID="rocky"
/etc/os-release:ID_LIKE="rhel centos fedora"
/etc/os-release:VERSION_ID="8.7"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
/etc/os-release:ANSI_COLOR="0;32"
/etc/os-release:LOGO="fedora-logo-icon"
/etc/os-release:CPE_NAME="cpe:/o:rocky:rocky:8:GA"
/etc/os-release:ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
/etc/os-release:ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Rocky Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
/etc/redhat-release:Rocky Linux release 8.7 (Green Obsidian)
/etc/rocky-release:Rocky Linux release 8.7 (Green Obsidian)
/etc/system-release:Rocky Linux release 8.7 (Green Obsidian)
```

### Netdata build info

```shell
Version: netdata v1.37.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-plugin-freeipmi' '--enable-plugin-cups' '--with-bundled-libJudy' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by chi-miel** [comment]
Hi,

some investigation, i can see the format of the metrics exposed by Netdata (and that Prometheus scrapes) via the url: http://localhost:19999/api/v1/allmetrics?format=prometheus

The output looks like this: 
`netdata_netdata_dictionaries_category_memory_bytes_average{chart="netdata.dictionaries.other.memory",family="dictionaries",dimension="structures"} 3264088.0000000 1676276953000
netdata_disk_space_GiB_average{chart="disk_space._",family="/",dimension="avail"} 23.1655650 1676276953000
netdata_disk_space_GiB_average{chart="disk_space._",family="/",dimension="used"} 5.1331097 1676276953000
netdata_disk_space_GiB_average{chart="disk_space._",family="/",dimension="reserved for root"} 0.0000000 1676276953000`


From what I understand the labels are not sorted alphabetically, hence the errors on my Thanos Receiver.

For me in the current state Netdata needs necessarily a Prometheus to send to a Thanos Receiver otherwise the sorting will not be done and the metrics will be dropped. 

Regards

**Comment by thiagoftsm** [comment]
Hello @chi-miel ,

Firstly we apologize for the delay to fix the issue.
Thank you very much for your investigation.

Best regards!
