### ISSUE TITLE
[Bug]: When installing netdata useradd reports netdata an existing netdata user but then tries to create it with adduser

### ISSUE THREAD

**Issue by iluvatar1** [netdata/netdata#14490]
### Bug description

Hi, when trying to install following the official instructions and some flags

`wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --non-interactive --auto-update`

the script tries to create the netdata user, using useradd, which in my case reports that the user already exists (so the script should skip creating the user)

```
Group 'netdata' already exists.
Adding netdata user account with home /opt/netdata ...                                                                                                                           
[/opt/netdata]# useradd -r -g netdata -c netdata -s /sbin/nologin --no-create-home -d /opt/netdata netdata 
useradd: user 'netdata' already exists
 FAILED  ''    
```                             

but for some reason it continues trying to create it, now using adduser 

```
[/opt/netdata]# adduser -h /opt/netdata -s /sbin/nologin -D -G netdata netdata                                                                                                   

Login name for new user: -h

```
And then the adduser command expects me to enter some info. The problem here IS NOT the error with the -n flag (which is another error maybe associated with my slackware distribution) but the fact that once useradd detects that the user already exists then the script should not take that as an error and try to create it using adduser but just continue. 

### Expected behavior

The script detects that the netdata user already exists and continues the installation instead of trying to recreate it

### Steps to reproduce

1. Have the user already existing
2. Install as shown in the beginning of this message.

### Installation method

kickstart.sh

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux sala16.salafis.net 5.17.2 #1 SMP PREEMPT Fri Apr 8 12:38:17 CDT 2022 x86_64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz GenuineIntel GNU/Linux
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="15.0"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=15.0
/etc/os-release:PRETTY_NAME="Slackware 15.0 x86_64 (post 15.0 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:15.0"
/etc/os-release:VERSION_CODENAME=current
```

### Netdata build info

```shell
I am just installing it
```

**Comment by MrZammler** [comment]
Hi @iluvatar1 thanks for the report, we will have a look on it!

**Comment by Ferroin** [comment]
It looks like there are actually two bugs here:

1. We’re not actually using `getent` to check for an existing Netdata user, which means we don’t detect one properly in a number of cases.
2. When we try to determine the command needed to add a user (or add a group) to the system, we try each one in sequence instead of only trying the first one we find.

I should have a PR to fix both issues up shortly.

**Comment by iluvatar1** [comment]
Hi, thanks for working on the fix :) I learned from reading the PR
Actually is great that you are using `getent` since it also works on my NIS setup (like `id`)
Have a good day
