### ISSUE TITLE
[Feat]: Enhanced stats for BTRFS.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#14494]
### Problem

BTRFS exposes quite a few metrics under `/sys/fs/btrfs` that we do not report, many of which are of potential interest to users.

Relevant metrics for the filesystem with a UUID of `[UUID]` are:

- `/sys/fs/btrfs/[UUID]/commit_stats`: This file covers a handful of metrics related to BTRFS commit behavior:
    - `commits`: Counts commits on this filesystem since it was mounted.
    - `last_commit_ms`: Indicates how long the last commit took, in milliseconds.
    - `max_commit_ms`: Tracks the largest value of `last_commit_ms` since the filesystem was mounted.
    - `total_commit_ms`: Tracks the total time taken by all commits since the filesystem was mounted.
- `/sys/fs/btrfs/[UUID]/devinfo/[DEVID]/error_stats`: Provides per-device error counters for `[DEVID]` (which will usually be a small integer number). More details on the exact counters here can be seen in https://github.com/netdata/netdata/issues/3341.
- `/sys/fs/btrfs/[UUID]/devinfo/[DEVID]/missing`: Indicates whether `[DEVID]` is actually present on the system or not. The relevant metric here is how many devices show a value other than 0 in this file for a given filesystem, which is a reliable proxy for whether the filesystem is operating in degraded mode or not (and is therefore something that we ideally should also have an alert for).
- `/sys/fs/btrfs/[UUID]/devinfo/[DEVID]/replace_target`: Indicates whether `[DEVID]` is being used as the target for a device replacement operation. Again, the relevant metric here is how many devices show a value other than 0 in this file for a given filesystem. If one or more devices are active replace targets, then there is an ongoing device replacement operation. This, on it’s own, is not super useful information, but it is useful to inform ML about more specific aspects of system behavior, and can also be used to make alerting a bit smarter if we can reliably map the device ID to the actual device path.

### Description

Collect the additional BTRFS metrics outlined above.

### Importance

really want

### Value proposition

Users will be able to better monitor performance, reliability, and status of their BTRFS volumes.

### Proposed implementation

Special handling may be needed to map device IDs to actual devices.

**Comment by Dim-P** [comment]
Related: https://github.com/netdata/netdata/issues/13561

Maybe we can close this one and add the description as a comment to the other PR?

**Comment by Ferroin** [comment]
> Related: #13561
> 
> Maybe we can close this one and add the description as a comment to the other PR?

### As a developer:

If we’re going for closing as dupes, then the correct approach is to reopen https://github.com/netdata/netdata/issues/3341 (the original request for this, dating back to _2018_, which got closed as part of ‘migrating feature requests to the forums’ that never happened), close this and #13561 as dupes of that.

### As an end user:

I could not care less how the open issues related to this get handled, provided _the feature actually gets implemented finally_. It’s been missing since day one of Netdata's support for BTRFS monitoring despite being arguably one of the most important parts of monitoring a BTRFS volume, it’s already been dropped once due to mishandling of issues around the forums being created, and people clearly want it. I am not an expert on the C code involved in data collection for BTRFS volumes, but based on what I do know about it, this should take maybe 30-60 minutes of time, tops, to implement for someone who actually understands the relevant parts of Netdata’s C code.

**Comment by Ferroin** [comment]
@Dim-P If you can get the C code written, I will be more than happy to dedicate time to testing, as well as helping write chart descriptions and default alerts for these metrics.

**Comment by Dim-P** [comment]
> @Dim-P If you can get the C code written, I will be more than happy to dedicate time to testing, as well as helping write chart descriptions and default alerts for these metrics.

That sounds good. I'll get on with it.

**Comment by Dim-P** [comment]
@Ferroin I did some testing by unplugging one of the devices I added previously to a BTRFS filesystem, and `missing` still reports `0` for that specific device (although `btrfs filesystem show` show that it's missing):

```
$ sudo btrfs filesystem show
Label: none  uuid: d5c93c6e-4acd-478b-bd54-d199140e6f40
        Total devices 2 FS bytes used 144.00KiB
        devid    1 size 3.75GiB used 536.00MiB path /dev/sdb1
        devid    2 size 0 used 0 path /dev/sdd1 MISSING
```

```
$ cat /sys/fs/btrfs/d5c93c6e-4acd-478b-bd54-d199140e6f40/devinfo/2/missing
0
```

Is there any way you could test it on your system and see if you get different results?

**Comment by Ferroin** [comment]
> @Ferroin I did some testing by unplugging one of the devices I added previously to a BTRFS filesystem, and `missing` still reports `0` for that specific device (although `btrfs filesystem show` show that it's missing):
> 
> ```
> $ sudo btrfs filesystem show
> Label: none  uuid: d5c93c6e-4acd-478b-bd54-d199140e6f40
>         Total devices 2 FS bytes used 144.00KiB
>         devid    1 size 3.75GiB used 536.00MiB path /dev/sdb1
>         devid    2 size 0 used 0 path /dev/sdd1 MISSING
> ```
> 
> ```
> $ cat /sys/fs/btrfs/d5c93c6e-4acd-478b-bd54-d199140e6f40/devinfo/2/missing
> 0
> ```
> 
> Is there any way you could test it on your system and see if you get different results?

Same behavior here, which is inconsistent with my understanding of the sysfs attribute. I’ll try and take some time tomorrow to dig into the kernel code that sets it to figure out what it actually means.

**Comment by Ferroin** [comment]
From a quick look at the relevant kernel code, it looks like this should be working, so I’m not sure why it isn’t working here, but IMO it’s not exactly critical to track this right now (even if it were working, it needs enough post-processing compared to the other stats that it’s probably not immediately useful for most users).
