### ISSUE TITLE
[Bug]: Prometheus charts not working anymore since 1.38.0 due to chart 'type.id' length over 200 chars

### ISSUE THREAD

**Issue by Tensibai** [netdata/netdata#14515]
### Bug description

Since the version 1.38.0 and the prometheus collector rework I've lost most of my traefik metrics as the id now becomes longer than 200 characters.

If I get it right it come from this kind of naming:

https://github.com/ilyam8/go.d.plugin/blob/master/modules/prometheus/collect.go#L84 
`id := mf.Name() + p.joinLabels(m.Labels())`

With Traefik it can become pretty long, for exemple (the count could be a bit off as I didn't check exactly when redacting the names, but it give the idea):

`[ WARN  ] prometheus[<ns>_traefik-<my_domain_tld>-prod-85687dbcf6-p2lgk] job.go:355 chart 'type.id' length (265) >= max allowed (200), the chart is ignored (prometheus_<ns>_traefik-<my_domain_tld>-prod-85687dbcf6-p2lgk.traefik_router_request_duration_seconds-code=200-method=GET-protocol=http-router=<entrypointname>-prod-app-<my_app_name>-<Host_in_traefik_rule>-<path_in_traefik_rule>@kubernetes-service=prod-<application_service>-80@kubernetes_count)`

### Expected behavior

I can try to save some characters my renaming the deployment and changing the entrypoints name, but it won't solve everything.

The only way I see without increasing the 200 char limit is providing a kind of "rewrite by regex" option in the prometheus plugin to allow users to redefine the chart id to keep it under 200 characters. 

What's your thoughts ?

### Steps to reproduce

Configure netdata to scrape Traefik metrics

### Installation method

other

### System info

```shell
Linux aks-worker-<rg_id>-vmss<sv_id> 5.4.0-1101-azure #107~18.04.1-Ubuntu SMP Tue Jan 10 21:14:56 UTC 2023 x86_64 Linux
/etc/alpine-release:3.16.3
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.16.3
/etc/os-release:PRETTY_NAME="Alpine Linux v3.16"
```

### Netdata build info

```shell
Version: netdata v1.38.0
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Relevant links: 
- https://github.com/netdata/go.d.plugin/pull/1004
- https://github.com/netdata/netdata/issues/10164
- https://github.com/netdata/netdata/blob/master/database/rrd.h#L171

**Comment by ilyam8** [comment]
Hi, @Tensibai. As a quick fix, I plan to add the ability (a config option) to not use label names in chart IDs. (at the moment it is a metric name + labels name + value). It will resolve the issue to some degree. I came across this problem working on the envoy collector.

See, it has long label names:
> envoy_cluster_update_empty{local_cluster="netdata",consul_source_service="netdata",consul_source_namespace="default",consul_source_partition="default",consul_source_datacenter="consul-sandbox-cluster-0159c9d3",envoy_cluster_name="consul-dataplane"} 0

But that fix probably won't work in your case (long label names vs long label values). Can you share an example of the `traefik_router_request_duration_seconds` time series?

**Comment by Tensibai** [comment]
If I got your request properly, the result from the metrics endpoint for one metric is as follow (I may have not used the exact same pattern for redaction, but should match anyway, prod and ops are the kubernetes namespaces here):

`# HELP traefik_router_requests_total How many HTTP requests are processed on a router, partitioned by service, status code, protocol, and method.
# TYPE traefik_router_requests_total counter
traefik_router_requests_total{code="200",method="GET",protocol="http",router="<entrypoint_name>-prod-<pod_name>-<host_domain>-<rule_path>@kubernetes",service="prod-<pod_name>-80@kubernetes"} 10337
traefik_router_requests_total{code="200",method="GET",protocol="http",router="ops-<pod2_name>-<host2_url>-b092ea17caf2668dd6e4@kubernetescrd",service="api@internal"} 48
traefik_router_requests_total{code="200",method="GET",protocol="http",router="ping@internal",service="ping@internal"} 60797
traefik_router_requests_total{code="200",method="GET",protocol="http",router="prometheus@internal",service="prometheus@internal"} 61129
traefik_router_requests_total{code="301",method="GET",protocol="http",router="external-to-443@internal",service="noop@internal"} 153
traefik_router_requests_total{code="301",method="GET",protocol="http",router="web-to-443@internal",service="noop@internal"} 84
traefik_router_requests_total{code="308",method="CONNECT",protocol="http",router="external-to-443@internal",service="noop@internal"} 7
traefik_router_requests_total{code="308",method="HEAD",protocol="http",router="external-to-443@internal",service="noop@internal"} 1
traefik_router_requests_total{code="308",method="POST",protocol="http",router="external-to-443@internal",service="noop@internal"} 28
traefik_router_requests_total{code="499",method="GET",protocol="http",router="<entrypoint_name>-prod-<pod_name>-<host_domain>-<rule_path>@kubernetes",service="prod-<pod_name>-80@kubernetes"} 116
traefik_router_requests_total{code="503",method="GET",protocol="http",router="<entrypoint_name>-prod-<pod_name>-<host_domain>-<rule_path>@kubernetes",service="prod-<pod_name>-80@kubernetes"} 19
`

**Comment by Tensibai** [comment]
@ilyam8 do you think creating a 'make_chart_id' function doing either:

1) Generating a predictable UUID for the too long name and adding a name label 

2) Using regexes matches on the whole name (an array to allow an easier configuration maybe ?) to make a custom shorter name would be ok ?
Something along the line of this (pseudo code)

```golang
func makeName(value string, match string, repl string) string {
    m := regexp.MustCompile(match)
    return m.ReplaceAllString(value, repl)
}

``` 

Responsibility to the user to provide a proper regex and repl like `match='prometheus_.*-(?<ns>[^@]+?)_(?<pod>[^@]+)_(?<port_name>[^@]*)_(?<proto>[^_]+)_(?<port>\d+)[.]'` and `repl='trk_${port_name}' ` (Took the TUID format from the prometheus job configuration in the agent service discovery as exemple)
