### ISSUE TITLE
[Feat]: New nvidia_smi go.d plugin is missing loop mode

### ISSUE THREAD

**Issue by vobruba-martin** [netdata/netdata#14522]
### Problem

I'm migrating from deprecated nvidia_smi (python.d) to new go.d version. Problem is that a single run of `nvidia-smi -q -x` (for XML output) or `nvidia-smi --help-query-gpu` (for CSV output) takes ~6 seconds for me and uses a lot of CPU. I guess that the reason behind this is that I use multiple GPUs in my servers.

![image](https://user-images.githubusercontent.com/6897988/218673476-6a9546fc-8da5-4c1b-902e-0c07b12dcc0e.png)

### Description

Just to make the plugin run I had to set `timeout: 10` in `nvidia_smi.conf` otherwise the process was being constantly killed by go.d plugin after 5 seconds. Now I would like to lower the CPU footprint. In python.d version it was possible to set `loop_mode: yes`, `poll_seconds: 1` and the problem was solved. This option is missing in go.d version.

From my tests if I run `nvidia-smi` in a loop mode (`nvidia-smi -q -x -l 1`) it takes half a second to return all values. It would be really helpful if you implement loop mode in go.d version.

Thank you!

### Importance

really want

### Value proposition

1. Faster data collection
2. Lower CPU utilization

**Comment by ilyam8** [comment]
Hi, @vobruba-martin. It is missing at the moment, yes. The reason I didn't implement so far is my tests - the average CPU utilization ~ is the same regardless of the mode (loop or not).

>  takes ~6 seconds

Does it take so long with `use_csv_format: true`? Should be much faster.

> Just to make the plugin run I had to set timeout: 10

Yes, the defaults are update_every 10 and timeout 5. I think will bump the timeout to 10 so it is equal to update_every.

**Comment by vobruba-martin** [comment]
Hi @ilyam8,

It looks like there is some inicialization process in Nvidia drivers which is run if the GPU is currently unused. I guess that this is why it is taking so long for me. Look at this chart. GPUs finished their work at 12:37:30.

![image](https://user-images.githubusercontent.com/6897988/218728674-46b99dc2-80f8-45c4-a27c-4e51fc31798a.png)

If I run `nvidia-smi -q -x -l 1` it takes ~6 seconds at start but after that I'm getting stats every second even if GPUs are unused.

> Does it take so long with `use_csv_format: true`? Should be much faster.

Yes.

**Comment by ilyam8** [comment]
@vobruba-martin can run `nvidia-smi -q -x -l 1 > /dev/null` from terminal and check `nvidia-smi` CPU usage (e.g. using Applications=>apps.cpu).

**Comment by vobruba-martin** [comment]
![image](https://user-images.githubusercontent.com/6897988/218741332-807f3c96-705e-4766-82c9-638a04a05827.png)

until 13:35:00 => working
13:35:00 - 13:36:20 => idle
13:36:20 - 13:38:00 => `nvidia-smi -q -x -l 10 > /dev/null` in terminal
13:38:00 - 13:39:30 => `nvidia-smi -q -x -l 1 > /dev/null` in terminal
13:39:30 - 13:40:10 => idle
13:40:10 - now => working

**Comment by vobruba-martin** [comment]
As a workaround I created  systemd unit which keeps running `nvidia-smi` in loop mode in background.

```ini
[Unit]
Description=NVIDIA-SMI in loop mode
Before=netdata.service

[Service]
ExecStart=/usr/bin/nvidia-smi -l 3600
Restart=on-failure
RestartSec=60

[Install]
WantedBy=multi-user.target
```

The CPU usage is now really low and now I'm able to collect data every 1s instead of 10s even when GPUs are idle.

![image](https://user-images.githubusercontent.com/6897988/220070755-1a1e727b-348b-453c-a2db-8f940477de00.png)

**Comment by rothgar** [comment]
I'm interested in implementing this but the docs are out of date. Can you provide your netdata config to use with this systemd service?

**Comment by vobruba-martin** [comment]
@rothgar I ended up collecting data every 2 seconds using this Netdata config.

`/etc/netdata/go.d/nvidia_smi.conf`:
```yaml
update_every: 2
autodetection_retry: 30

jobs:
  - name: nvidia_smi
    use_csv_format: no
    timeout: 10
```

**Comment by lukeadams** [comment]
@vobruba-martin I ran into a similar issue - for me, enabling nvidia persistenced solved it (iirc the driver would re-initialize every time you need it if not running)
https://docs.nvidia.com/deploy/driver-persistence/index.html

**Comment by ilyam8** [comment]
Sorry, guys, I forgot about this issue. I will fix it next week!
