### ISSUE TITLE
[Feat]: add vnodes/vnodes.conf to the stock configuration directory 

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#14546]
### Problem

This is a follow-up of https://github.com/netdata/netdata/pull/14464. Functionality has been added, but the configuration directory/file for virtual nodes is missing.

### Description

- Create `vnodes` directory in the stock config dir.
- Create `vnodes/vnodes.conf` file with sample config.

---

The file content is not relevant at the moment, will add it to the PR when the packaging side is ready.

### Importance

must have

### Value proposition

This is needed for using the Virtual Nodes feature (for configuring Virtual Nodes to be specific).the

**Comment by opalomogt** [comment]
Any news on this?

**Comment by gdoermann** [comment]
The bug https://github.com/netdata/netdata/issues/15207 may be in part because we do not treat vnodes.conf as any other config file.

**Comment by ilyam8** [comment]
Hey, @gdoermann 

> we do not treat vnodes.conf as any other config file.

What do you mean by that? I think we do.
