### ISSUE TITLE
[Bug]: Anomaly detector service incorrectly detects Python 3.10 as less-than version 3.6

### ISSUE THREAD

**Issue by Kurtoid** [netdata/netdata#14561]
### Bug description

Ran the anomaly detection setup steps described at https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/anomalies
Upon running `python.d.plugin anomalies debug trace nolock`, I see
```
python.d ERROR: anomalies[anomalies] : anomalies collector only works with Python>=3.6
```

### Expected behavior

Version check should recognize Python 3.10. If anomaly detection doesn't support Python>3.9, it should be stated.

### Steps to reproduce

1. Run the anomalies plugin in debug mode
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux kurtlaptop2 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID="Arch"
/etc/lsb-release:DISTRIB_RELEASE="rolling"
/etc/lsb-release:DISTRIB_DESCRIPTION="Arch Linux"
/etc/os-release:NAME="Arch Linux"
/etc/os-release:PRETTY_NAME="Arch Linux"
/etc/os-release:ID=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:LOGO=archlinux-logo
```

### Netdata build info

```shell
Version: netdata v1.38.1
Configure options:  '--prefix=/usr' '--sbindir=/usr/bin' '--sysconfdir=/etc' '--libexecdir=/usr/lib' '--localstatedir=/var' '--with-zlib' '--with-math' '--with-user=netdata' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/netdata/src=/usr/src/debug/netdata -flto=auto' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/netdata/src=/usr/src/debug/netdata -flto=auto'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Issue appears in https://github.com/netdata/netdata/blob/acca8c24f229da0ff0238921ebc4b30ddc7125ea/collectors/python.d.plugin/anomalies/anomalies.chart.py#L61

Casting '3.10' to float results in 3.1, and `3.1 < 6.3 == True`

Issue can be replicated on command line:
```
❯ python
Python 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> float('{}.{}'.format(sys.version_info[0], sys.version_info[1]))
3.1
>>> sys.version_info
sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
>>> 
```

**Comment by Kurtoid** [comment]
Probably low priority, since the recommended `pip install` line in the setup guide (https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/anomalies#requirements) doesn't work in Python 3.10 anyway

**Comment by andrewm4894** [comment]
thanks @Kurtoid - i'll have a look and see what i need to do to get it working on 3.10 as well.

**Comment by andrewm4894** [comment]
Seems to be related to needing to update pip for 3.10. 

Will dig more and see if can come up with clear instructions for 3.10. 

https://stackoverflow.com/questions/69503329/pip-is-not-working-for-python-3-10-on-ubuntu

**Comment by ilyam8** [comment]
@andrewm4894 the issue is **just** the warning message

> python.d ERROR: anomalies[anomalies] : anomalies collector only works with Python>=3.6


When using python 3.10+, because of there is a bug in here:

https://github.com/netdata/netdata/blob/2a581f1885f7cd0a17ca97eef5f1a42a22b13b52/collectors/python.d.plugin/anomalies/anomalies.chart.py#L61-L63

**Comment by andrewm4894** [comment]
Small pr to fix this issue: https://github.com/netdata/netdata/pull/14616

WE can make a fresh issue for the problem of getting the anomalies collector to work on python 3.10 as seems like a bigger issue.
