### ISSUE TITLE
[Feat]: ability to use a `$current_timestamp` type variable when defining alert logic 

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#14593]
### Problem

Users often report that they would like to silence alarms during specific windows of time or they would like to actually adjust the alert configuration to have it behave differently during different times of day. 

for example - a daily backup runs at specific time each day, as such i'd like to adjust my disk alerts to be much less sensitive during this period. 

you could even imagine that i actually want to lower my CPU alerts during a time when i expect that there really could be high cpu usage and so a low cpu usage is sign the workload did not occur as expected in that window. 

### Description

ideally as a user i'd be able to just use nested if or a case type statement in my alert configuration. 

### Importance

really want

### Value proposition

1. would make alert configs much more flexible and easier to work with for users who have "time dependant" alert needs 
2.
3.
...

### Proposed implementation

Some special variable like `$current_timestamp` and maybe one or two utility functions like `hour($current_timestamp)` etc.

Would also be nice if logic could be applied to silence too like this:

```
# silence if before 6am
to: hour($current_timestamp) < 6 ? 'silent' : 'sysadmin'
```

**Comment by ilyam8** [comment]
This is wontfix as requested. I plan to rewrite [alarm-notify.sh](https://github.com/netdata/netdata/blob/master/src/health/notifications/alarm-notify.sh.in) in golang. This will allow easy addition of silencing functionality (e.g. cron syntax). But there is no ETA for now.
