### ISSUE TITLE
[Feat]: Please let expand VMs label under Applications

### ISSUE THREAD

**Issue by shodanshok** [netdata/netdata#14648]
### Problem

CPU (and disk/mem) chart hides all running virtual machines under the VMs label. For example:

![image](https://user-images.githubusercontent.com/13137622/222514618-184b6ea9-fb80-49c1-a670-7aaa7de9c1d0.png)

Notice how all running virtual machines (over 10) are generically counted as "VMs" (orange label/area). It would be very useful to provide a mean to show individual virtual machines as separate processes (as they are), stacking them on the very same graph (a threshold can be implemented for, say, the top 5 or 10 VMs). At the moment one has to manually visit each cgroup chart to identify an "heavy" virtual machine.

### Description

Stacked virtual machines resource usage

### Importance

really want

### Value proposition

1. one can identify a potentially misbehaving VM by looking into a single graph

**Comment by MrZammler** [comment]
Hi @shodanshok ! (nice avatar btw).

Not sure if it will work in your case, but the grouping there is configured via the `apps_groups.conf` file. There is some more information here -> https://learn.netdata.cloud/docs/data-collection/monitor-anything/System%20Metrics/Application-monitoring#configuration

I'm not sure it will work unless your vm's appear as different processes (each with it's own process name), but you can have a try.

**Comment by shodanshok** [comment]
Hi @MrZammler and thanks for the suggestion.

Unfortunately, it does not work: commenting the "VMs" line results in all virtual machines being accounted as "other". After all, docs clearly states that 

> For the Applications section, only groups configured in this file are reported. All other processes will be reported as other

**Comment by Dim-P** [comment]
Hi @shodanshok . Not sure if you are using the cloud, but the `cgroups` section does exactly what you need (the cloud dashboard is much more advanced than the local one):

![Screenshot from 2023-03-20 16-17-11](https://user-images.githubusercontent.com/5953192/226403125-d6c47a5a-09d1-4864-80e1-d6f31dc009ad.png)

Just make sure to select `group by instance` instead of `group by dimension`.

**Comment by Dim-P** [comment]
> @Dim-P sure, and I am actually using the cloud dashboard board this very reason. However, I feel this is an important feature that should not be left out of local dashboard.

@shodanshok It is on our roadmap to match the cloud dashboard functionality in the local dashboard, so this particular feature will be implemented in the upcoming months.

**Comment by ilyam8** [comment]
I don't think it "expand VMs label under Applications" will be implemented in the upcoming months. 

Using cloud UI:

- all containers and VMs are under "cgroups" section (will be renamed to "Containers & VMs" soon).
- individual processes that fall into apps.plugin groups (apps_groups.conf) can be found in the "Functions" tab.

**Comment by Dim-P** [comment]
> I don't think that "expand VMs label under Applications" will be implemented in the upcoming months.
> 
> Using cloud UI:
> 
>     * all containers and VMs are under "cgroups" section (will be renamed to "Containers & VMs" soon).
> 
>     * individual processes that fall into apps.plugin groups (apps_groups.conf) can be found in the "Functions" tab.

Sorry, I meant the cgroups functionality of the cloud will be brought to the local dashboard.

**Comment by ilyam8** [comment]
>  It would be very useful to provide a mean to show individual virtual machines as separate processes (as they are)

Container and VMs (cgroups) resource utilization is available in:
 - Top -> Containers-vms
 - Metrics -> Containers & VMs

Both don't require Cloud.

**Comment by shodanshok** [comment]
> Container and VMs (cgroups) resource utilization is available in:
> 
>     * Top -> Containers-vms
> 
>     * Metrics -> Containers & VMs
> 
> 
> Both don't require Cloud.

Yes, the new local GUI provides the required feature. 

However, I can not see "Top" working without a netdata cloud connection (ie: it requires an authenticated client and a claimed host). Am I missing something?

Thanks.

**Comment by ilyam8** [comment]
Containers-vms doesn't require Cloud connection in the nightly version. If you are using stable you will have to wait until the next release.
