### ISSUE TITLE
[Feat]: go.d.plugin: Provide quick configuration of charts for commonly available metrics for the SNMP collector.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#14645]
### Problem

While many devices have a large number of extremely specific OIDs that they expose over SNMP, there are a handful of well defined MIBs that are reasonably widely implemented, which provide consistent information about certain basic system resources. 

Examples of such MIBs include:

- The Host Resources MIB and associated OIDs, as defined by [RFC 2790](https://www.rfc-editor.org/rfc/rfc2790), which can be parsed to collect information about user and process counts. This is available on a significant percentage of systems that provide management access over SNMP.
- The UC Davis MIB, as provided by standard installs of [Net-SNMP](http://www.net-snmp.org/), which is available on most UNIX-like systems and can be parsed to collect information about memory and swap utilization, load averages, CPU usage, interrupt rates, context switch rates, and a handful of other system statistics.

While it’s possible to utilize this data directly, doing so requires careful per-system configuration and often results in unintuitive presentation of the data (for example, the UC Davis MIB’s memory reporting lists total memory and available memory, but not memory in use, which makes interpreting the charts more difficult). However, these MIBs are designed specifically to allow for autodiscovery and automatic setup.

### Description

Suggested user-facing implementation is to have keys in each job definition to enable specific charts (for example `automatic-storage-charts: yes`). Suggested charts and associated OIDs are:

1. System processes: This one is just a basic pre-configured line chart, tracking the OID 1.3.6.1.2.1.25.6.0 from the Host Resources MIB, which tracks the number of currently active processes on the system.
2. System users: Same as above, but with OID 1.3.6.1.2.1.25.5.0, and tracking active users on the system.
3. System interrupts: Same as above, but with OID 1.3.6.1.4.1.2021.11.59.0 from the UC Davis MIB, which counts interrupts processed on the system. This should be handled incrementally, in which case it is functionally identical to our `system.intr` chart.
4. Context switches: Same as above, but with OID 1.3.6.1.4.1.2021.11.60.0 and counting context switches (if handled incrementally, it’s the same as our `system.ctxt` chart).
5. System memory usage: This can be tracked using two UC Davis OIDs, 1.3.6.1.4.1.2021.4.5.0 for total physical memory, and 1.3.6.1.4.1.2021.4.6.0 for available physical memory. Ideally, we would collect both and then compute free and used memory from them to present in a stacked chart like we do for regular system memory.
6. System swap usage: Same as the above system memory usage chart, but with OIDs 1.3.6.1.4.1.2021.4.3.0 (for total swap space) and 1.3.6.1.4.1.2021.4.4.0 (for available swap space) instead.
8. System load average: Uses the UC Davis OID 1.3.6.1.4.1.2021.10.1.3, which is a table with entries at indices at 1, 2, and 3 corresponding respectively to the 1, 5, and 15 minute load averages. Essentially identical to the `system.load` chart.
9. System CPU usage: This corresponds to a series of UC Davis OIDs all under the prefix 1.3.6.1.4.1.2021.11. All are measured in ‘ticks’ (generally 100ths of a second), and require incremental handling . Not all of them are present on all systems. The specific OIDs are as follows:
    - 1.3.6.1.4.1.2021.11.50.0: Time spent running user processes (equivalent to the `user` dimension in our `system.cpu` chart).
    - 1.3.6.1.4.1.2021.11.51.0: Time spent running low-priority processes (equivalent to the `nice` dimension in our `system.cpu` chart).
    - 1.3.6.1.4.1.2021.11.52.0: Time spent running system-level code (equivalent to the `system` dimension in our `system.cpu` chart).
    - 1.3.6.1.4.1.2021.11.53.0: Time spent idling (this is time spent _not_ in one of the other states mentioned in this list).
    - 1.3.6.1.4.1.2021.11.54.0: Time spent waiting on IO completion (equivalent to the `iowait` dimension in our `system.cpu` chart).
    - 1.3.6.1.4.1.2021.11.55.0: Time spent running in kernel mode (no equivalent for Linux in our `system.cpu` chart).
    - 1.3.6.1.4.1.2021.11.56.0: Time spent processing interrupts (equivalent to the `irq` dimension in our `system.cpu` chart).
    - 1.3.6.1.4.1.2021.11.61.0: Time spent processing soft interrupts (equivalent to the `softirq` dimension in our `system.cpu` chart).
    - 1.3.6.1.4.1.2021.11.64.0: Time spent waiting for the hypervisor to schedule virtual CPUs (equivalent to the `steal` dimension in our `system.cpu` chart).
    - 1.3.6.1.4.1.2021.11.65.0: Time spent running guest virtual CPUs (equivalent to the `guest` dimension in our `system.cpu` chart).
    - 1.3.6.1.4.1.2021.11.66.0: Time spent running low-priority guest virtual CPUs (equivalent to the `guest_nice` dimension in our `system.cpu` chart).

    We can also get a processor count for use as a chart variable by checking OID 1.3.6.1.4.1.2021.11.67.0

### Importance

really want

### Value proposition

The primary idea here is to allow usage of Net-SNMP as a remote data collection agent on platforms we either do not currently support, or systems where direct usage of the agent is not viable for some reason (for example, we use too much memory or CPU time). In essence, enabling something similar to what we’re doing with windows_exporter for collecting data from Windows systems, but for systems running UNIX-like platforms such as AIX or Solaris.

**Comment by shyamvalsan** [comment]
This is now done - updated SNMP collector does this.
