### ISSUE TITLE
[Feat]: Netdata config via forms in GUI

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#14663]
### Problem

Netdata currently lacks the option to easily configure an integration config like 'go.d/redis.conf' via the GUI dashboard. Current method is awkward and easier to break with a simple missing or extra space.

### Description

Please consider adding the ability to configure conf settings via the dashboard using forms, similar to how you can configure data sources in Grafana Cloud.

A simple form with annotations, form validation and links to any relevant documentation would although the admin to configure their Netdata instance quickly and with less chance of making a mistake that requires time and resources to track down via SSH.  
 

### Importance

blocker

### Value proposition

1. A form-based page for easier configuration of integrations requiring extra configuration like Redis, MySQL, PDNS Recursor etc
2. Provides guidance, hints and suggestions via an interactive form.
3. Removes dependence upon SSH to configure integrations.
4. Further promotes Netdata documentation and guides.
5. Increases awareness of Netdata's abilities.
...

### Proposed implementation

Something like this but designed for Netdata...

![image](https://user-images.githubusercontent.com/13329789/222769931-f5c04ca8-6ed7-49f6-ad73-36bf59a4e043.png)

**Comment by ilyam8** [comment]
This will be implemented.

**Comment by ilyam8** [comment]
This has been implemented. Dynamic configuration (beta) is available for Cloud users.

**Nodes** -> **Configure this node** (⚙️) -> **Collectors** -> (find) **Redis** -> **Add new**.

<details>
<summary>Screenshot</summary>

<img width="1561" alt="Screenshot 2024-03-22 at 15 19 46" src="https://github.com/netdata/netdata/assets/22274335/3122d941-08eb-4aec-b558-d3cdf568f3c4">

</details>

**Comment by TheOldMan2000** [comment]
Awesome, thank you @ilyam8 !
