### ISSUE TITLE
[Feat]: plugins: allow single json config

### ISSUE THREAD

**Issue by wmertens** [netdata/netdata#14682]
### Problem

Changing the go.d plugin config in NixOS is tedious, since the defaults are YAML and in multiple files.

More generally, this applies to the whole of the netdata configuration, including the health.d directory

### Description

Allow configuration via a single JSON file, or perhaps multiple files that get merged.
Note that YAML is a superset of JSON, so you could still allow people to write YAML if you like.

Ideally, there would also be some machine-parseable documentation like https://json-schema.org/. This could be used to provide automated checks on the configuration as well as nicely integrated user documentation. Right now configuration is hidden in comments in .conf files.

for example, a configuration could have these keys: `daemon`, `directories`, `logs`, `health`, `plugins`, etc.
Where the go plugin currently requires separate files for each service, those could just be under `plugins.go.services`.

Some configurations may need changes, for example the health.d alarms/templates will need a `template: boolean` field to discern alarm vs template.

In any case, any progress towards this is great, even if only the go plugin supports this.

### Importance

really want

### Value proposition

1. NixOS configuration will be a breeze and will have less bugs
2. Other distributions might like it too
3. Consistency makes for better products: better code reuse, less bugs

### Proposed implementation

See description, each part of netdata will need some tweaking.

**Comment by ilyam8** [comment]
Hi, @wmertens. Thanks for the request but I think it is wontfix, that is very unlikely we want to have a single JSON config for anything. We plan to switch all configs to YAML. Also, go.d.plugin supports a single (YAML) configuration file for all collectors, it is just not documented, e.g.

```YAML
- name: NAME
  module: apache
  url: URL
- name: NAME
  module: nginx
  url: URL
...
- name: NAME
  module: mysql
  dsn: DSN
```

**Comment by wmertens** [comment]
And what about providing a jsonschema for documentation?

(Note that JSON is valid yaml so no problem with you switching to that :))

Also, can you elaborate on the go config? Where does that array go? And how do you specify jobs?

**Comment by andrewm4894** [comment]
@wmertens thanks for the feature request - is similar to some other ones so good to see it coming from another user eg i had made [this](https://github.com/netdata/netdata/issues/14088) request as a maybe small incremental improvement on the way. Probably right way is to properly just do some yaml or more modern approach and try solve it proper.

> providing a jsonschema for documentation

Curious about this one - do you have any sort of examples of what you mean? I know we have [this](https://raw.githubusercontent.com/netdata/netdata/master/web/api/netdata-swagger.yaml) which i am pretty sure is [openapi json schema](https://swagger.io/specification/). So wondering what your idea of jsonshema for docs might look like or if any examples out there you have seen that illustrate what you mean.
