### ISSUE TITLE
[Bug]: Impossible to create alerts for some prometheus charts

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#14707]
### Bug description

A fairly recent change in the way charts and dimensions appear on the agent resulted in the possibility mentioned in https://community.netdata.cloud/t/extract-one-dimension-value-from-multi-dimension-graph/3957/2

The problem is that the `lookup` line uses comma as a delimiter between dimensions. The names we give to these dimensions, make it impossible to create an alert for them.

### Expected behavior

Either change the dimension name syntax for these cases to not include a comma, or the parser to properly handle single or double quotes around dimension names.

Note that if the choice is made to modify the dimension names, it may affect the cloud as well. 

### Steps to reproduce

Any prometheus endpoint with multiple labels for a single metric will do.
I replicated the behavior by adding a windows_exporter endpoint directly to the prometheus config, and trying to create an alert for `windows_cpu_cstate_seconds_total` , dimension `core=0,0,state=c1`. 

### Installation method

kickstart.sh

### System info

```shell
irrelevant
```

### Netdata build info

```shell
irrelevant
```

**Comment by ilyam8** [comment]
Hi, "Netdata build info" is very relevant. I believe you are using an old version of Netdata. We no longer have dimensions like "dimension core=0,0,state=c1" in latest stable.

**Comment by cakrit** [comment]
Indeed it's 1.37.xxx 
Can't update it right now, but closing it if we no longer have these dimensions.
