### ISSUE TITLE
[Bug]: Pod in kind-worker2 restarts spontaneously after 24hrs remains running without collecting metrics

### ISSUE THREAD

**Issue by Garahk** [netdata/netdata#14746]
### Bug description

I have kind multinode cluster, consisting of kind-control-plane, kind-worker and kind-worker2.

Using the helm chart I've deployed netdata in pods. Am seeing a behaviour where somewhere around after 24hrs to 48hrs, the pod in kind-worker2 starts restarting, in average 9 times. After it restarts, it will stay up apparently, but in the dashboard it will show as disconnected, and the collection of some of the plugins stops at all. I've seen this behaviour on version 1.37.1, and while I've tested in the same server the version 1.38.1 which has been up for more than 17days without issues, but consistently I've seen 1.37.1 have this restart/inestability behavior, which leads me to believe the problem is linked to version 1.37.1. I've also tried deleting the pod and let it get recreated, but with no success, still failing, it's only solved once I completely delete netdata, but it will start failing again after 24 to 48hrs.

I know there's not patching in older versions, however could you help me determine where the issue is? I have one server with 1.38.1 and one with 1.37.1, the latter has this problem and is not ready to be upgraded for at least a month.

I have logs I've retrieved from the server with version 1.37.1, please let me know where to share them.

### Expected behavior

All pods to remain stable.

### Steps to reproduce

1. Install netdata with helm chart
2. Monitor for 24 to 48hrs
3. Kind-worker2 pod starts restarting spontaneously, then remains in running state without collecting metrics
...

### Installation method

helmchart (kubernetes)

### System info

```shell
Linux 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Mar 25 21:21:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.9 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.9"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
/etc/system-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

### Netdata build info

```shell
Version: netdata v1.37.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
Old issues cleanup. @Garahk if you still using Netdata - try the latest stable (v1.44.1).
