### ISSUE TITLE
[Bug]: Infiniband bytes overreported by 4x

### ISSUE THREAD

**Issue by TimZaman** [netdata/netdata#14747]
### Bug description

A bandwidth test between nodes A and B reveals a speed of 52Gb/s, while Netdata reveals an excess of 200Gb/s. See https://github.com/prometheus/node_exporter/issues/573 - prometheus exporter made the same mistake, but you guys havent fixed it yet

Measured:
```
 #bytes     #iterations    BW peak[MB/sec]    BW average[MB/sec]   MsgRate[Mpps]
 65536      618880           0.00               6458.81		   0.103341
 ```
 6458MB/s = 52Gb/s

while Netdata overreports this by 4x:

![image](https://user-images.githubusercontent.com/7721540/225833185-dab0d8d3-b713-4a5d-b825-60073fecf6aa.png)

### Expected behavior

I expect a 4x smaller bandwidth to be reported.

### Steps to reproduce

1. On `node_a`, run `ib_read_bw -D 60 -b`
2. On `node_b`, run `ib_read_bw $NODE_A_ADDR -D 60 -b`
3. `BW average[MB/sec]` will now reveal a number lower than 4x Netdata.

### Installation method

kickstart.sh

### System info

```shell
Linux gamma 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Version: netdata v1.38.0-249-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

# Bad experience

I find this bugreport with 9 fields very developer unfriendly. It is really offputting, because I know exactly what the issue is here, and what to do. It is as simple as:

_You guys need to divide your number by 4, see the same mistake prometheus exporter was making: https://github.com/prometheus/node_exporter/issues/573_

**Comment by ilyam8** [comment]
@Saruspete hey, can you help us?

I see that you added `4` multiplier in https://github.com/netdata/netdata/pull/11994 _as per Kernel documentation_. This is the line:

https://github.com/netdata/netdata/blob/5e6755f539d5229c33c21e954abcba470f8e8124/collectors/proc.plugin/sys_class_infiniband.c#L541-L544

I think the problem is having both `4` and `port->width`.

https://github.com/netdata/netdata/blob/5e6755f539d5229c33c21e954abcba470f8e8124/collectors/proc.plugin/sys_class_infiniband.c#L468-L480


Am I correct? I think the fix is removing any of them.

**Comment by Saruspete** [comment]
Hello there,
Seems there's a mismatch with different drivers / configuration.
Originally, the driver was reporting values as expected, without the need to do a *4 in #14748 . 
By not having an available IB test environment at the time of that fix, it seems it broke other driver/configuration.

So maybe the output of `/sys/class/infiniband/*/rate` was not correctly reported or parsed at that time, and failed the usual *4.
It seems also the "always multiply by 4" rule reported for mlnx hca is not correct per se: it's dependent on the connector type and link used. While 99% of the time, we'll have a 4 lanes connection, there's also other rates and [connectors](https://docs.nvidia.com/networking/display/CABLEMANAGFAQ/Cable+and+Connector+Definitions): 1, 4 (QSFP), 8 (OSFP), 12. But [not only](https://en.wikipedia.org/wiki/InfiniBand#Performance): 

> Each link is duplex. Links can be aggregated: most systems use a 4 link/lane connector (QSFP). HDR often makes use of 2x links (aka HDR100, 100Gb link using 2 lanes of HDR, while still using a QSFP connector). 8x is called for with NDR switch ports using OSFP (Octal Small Form Factor Pluggable) connectors

But as we see in the kernel drivers, there's a lot more drivers than Mellanox: https://github.com/torvalds/linux/tree/master/drivers/infiniband/hw 

So, maybe we should remove that unconditionnal *4, leave the "port->width" multiplier, and add an override in the configuration to change the value of the "port->width"

@TimZaman can you please give us more details on your card, driver (modinfo, ibstatus) and content of  /sys/class/infiniband/*/rate

**Comment by ilyam8** [comment]
> So, maybe we should remove that unconditionnal *4, leave the "port->width" multiplier, and add an override in the configuration to change the value of the "port->width"

Probably set the width to `0` if we fail to read the file/parse and use `4` in this case otherwise use it.

**Comment by TimZaman** [comment]
kindly bumping

**Comment by Saruspete** [comment]
To be able to fix it correctly, @TimZaman can you please provide the requested details: card, driver (modinfo, ibstatus) and content of /sys/class/infiniband/*/rate ?

**Comment by TimZaman** [comment]
Okay, but ahouldnt we just adhere to the logic from prometheus which had
the same bug?

**Comment by Saruspete** [comment]
Because prometheus chose the easy way to blindly *4 doesn't mean it's the correct one. The bug you're reporting here seems to be a side-effect of #11994 where the values were 4* too low. And now it's 4* too high. I did fix it blindly having no IB setup available, and now we're in a ping-pong status.

The original code was already implementing this *4 by parsing the "rate" file to find the multiplier, and that seemed to work with mellanox and omnipath fabrics.

In the prometheus bug you reference, it's a 4* too low (not too high), and their [discussion](https://github.com/prometheus/node_exporter/issues/573#issuecomment-297064332) was about how it's a mellanox only feature, thus would be a Mellanox-only fix. and while they own like 99% of this market, other verdors doesn't seem to do the same thing, as per the kernel source:

drivers/infiniband/hw/mlx4/mad.c:
```
        pma_cnt_ext->port_xmit_data = cpu_to_be64(be64_to_cpu(cnt->tx_bytes) >> 2);
        pma_cnt_ext->port_rcv_data = cpu_to_be64(be64_to_cpu(cnt->rx_bytes) >> 2);
```
drivers/infiniband/hw/mlx5/mad.c:
```
    pma_cnt_ext->port_xmit_data = cpu_to_be64(MLX5_SUM_CNT(out, transmitted_ib_unicast.octets, transmitted_ib_multicast.octets) >> 2);
    pma_cnt_ext->port_rcv_data = cpu_to_be64(MLX5_SUM_CNT(out, received_ib_unicast.octets, received_ib_multicast.octets) >> 2);
```

drivers/infiniband/hw/hfi1/mad.c
```
    p->port_xmit_data = rsp.port_xmit_data;
    p->port_rcv_data = rsp.port_rcv_data;                                      
```

drivers/infiniband/hw/qib/qib_mad.c
```
    cntrs.port_xmit_data -= ibp->z_port_xmit_data;
    cntrs.port_rcv_data -= ibp->z_port_rcv_data;     
```

drivers/iiniband/hw/ocrdma/ocrdma_stats.c
```
    pma_cnt->port_xmit_data    = cpu_to_be32(ocrdma_sysfs_xmit_data(dev));
    pma_cnt->port_rcv_data     = cpu_to_be32(ocrdma_sysfs_rcv_data(dev));      
```

And as per my [previous comment](https://github.com/netdata/netdata/issues/14747#issuecomment-1473948468) we need to dig deeper to prepare for non-QSFP connectors like QSFP-DD or OSFP.


Waiting for you to provide the requested details.
