### ISSUE TITLE
[Bug]: Parent and child pod high memory usage

### ISSUE THREAD

**Issue by Garahk** [netdata/netdata#14757]
### Bug description

My setup is a multinode kind cluster with 3 nodes (kind-control-plane, kind-worker and kind-worker2). My netdata installation has been up for 18 days. I've seen that the parent pod and the child pod both located in the kind-worker2 have a high memory usage, notice below, the parent pod has an usage of 20GB while the child pod 4GB.

Parent pod:
![image](https://user-images.githubusercontent.com/99432183/225963441-2221f6b3-a03e-4416-aa8e-763df11dfe40.png)

Child pod:
![image](https://user-images.githubusercontent.com/99432183/225975226-5a899794-43ab-4305-82df-d4582f57d604.png)

I've customized the chart following the documentation on this sections:

Parent pod:
![image](https://user-images.githubusercontent.com/99432183/225988726-76586843-cc12-4ed2-a77a-0d77fc6aa69a.png)

Child pod:
![image](https://user-images.githubusercontent.com/99432183/225988984-75e97975-d221-421a-9eb6-663c1ccd22e3.png)
![image](https://user-images.githubusercontent.com/99432183/225989513-53dc112b-29b0-426c-bf2a-845cd651b1e8.png)

k8sState:
![image](https://user-images.githubusercontent.com/99432183/225989744-d9b04e83-76f9-4ccb-acf8-a86b9fa97d2d.png)

My cluster has 105 pods of my deployment, while the in total there are 129 pods (considering the system ones)

### Expected behavior

- Need to know whether this is expected (20GB in memory for parent pod, 4GB in memory for child pod in the kw2) or it's an issue?
- It's related to the customizations I've done, especially because am monitoring the health on the child pods? The reason behind it is because I need the statistics of the child's pods monitored, (CPU, Memory, RAM, Disk), did I do it incorrectly?
- Is there a way to optimize it? if so, what needs to be modified? am guessing the netdata.conf would need to be modified according to the [db] section and the tiers:

![image](https://user-images.githubusercontent.com/99432183/225995274-8b55b4bd-22ba-4321-8ef7-7a72be8bb6c4.png)

- Or would it be the section resources under each pod (parent/child/k8sState) limit the cpu and memory:

![image](https://user-images.githubusercontent.com/99432183/225994449-77e67e19-1ebf-4db0-913d-e343efa23815.png)

### Steps to reproduce

1. Installed netdata v1.38.1 with helm chart
2. System running for 18days
3. Verify the memory usage and it's 20GB in parent pod, 4GB in child pod (kind-worker2)
...

### Installation method

helmchart (kubernetes)

### System info

```shell
Linux 3.10.0-1160.76.1.el7.x86_64 #1 SMP Tue Jul 26 14:15:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.9 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.9"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
/etc/system-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

### Netdata build info

```shell
Version: netdata v1.38.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
Hi, @Garahk. 20G and 4G look a lot, can you for parent, k8sState, and (any) child:

 - change the timeframe to 7 days.
 - export a [snapshot](https://learn.netdata.cloud/docs/visualizations/agent-dashboard/import-export-and-print-a-snapshot#export-a-snapshot).
 
And send them to `ilya@netdata.cloud`?

**Comment by ilyam8** [comment]
@Garahk it is a configuration option, I mean the following (access to the local dashboard is needed)

<img width="1280" alt="Screenshot 2023-03-20 at 20 54 46" src="https://user-images.githubusercontent.com/22274335/226438736-d203e24f-fda0-4e03-8a06-2a82186f38dd.png">

**Comment by Garahk** [comment]
> @Garahk it is not a configuration option, I mean the following (access to the local dashboard is needed)
> 
> <img alt="Screenshot 2023-03-20 at 20 54 46" width="1280" src="https://user-images.githubusercontent.com/22274335/226438736-d203e24f-fda0-4e03-8a06-2a82186f38dd.png">

Apologies, I missunderstood what you were requesting, I've generated the snapshots and sent them to the address you provided.

Thanks.

**Comment by Garahk** [comment]
@ilyam8 Hello Ilya, wondering if there's been any finding on the issue, thank you.

**Comment by MrZammler** [comment]
Hi @Garahk, sorry for the late reply. Is it possible please to check with 1.39.0 if the problem persists? And we can pick it up from there?

Thanks

**Comment by Garahk** [comment]
> Hi @Garahk, sorry for the late reply. Is it possible please to check with 1.39.0 if the problem persists? And we can pick it up from there?
> 
> Thanks

@MrZammler I can deploy version 1.39.0 and see if the problem persists. However, could you help me find how to limit the resource usage? What would be the way to configure and limit the use of resources, and where, I suppose it would be at helm chart level? Please help me understand and achieve this part as well.

**Comment by ilyam8** [comment]
@Garahk hey, let's do the following:

- update to latest helmchart.
- check memory usage.
- If high, [send me a new snapshot](https://github.com/netdata/netdata/issues/14757#issuecomment-1474858301) (you will need to use `IP:19999/v1` endpoint for it).

**Comment by Garahk** [comment]
@ilyam8 ok, I'll do that and come back here.

**Comment by MrZammler** [comment]
Hi @Garahk just checking if there is a new update on this? 1.43.X also has some memory reduction fixes.
