### ISSUE TITLE
[Feat]: Provide a way to dump current `netdata.conf` without needing to use the REST API.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#14755]
### Problem

Right now, the only way to get a ‘default’ `netdata.conf` file is to start the agent and query the `/netdata.conf` API endpoint. This works well enough for checking the effective configuration of a running agent, but it also means that `edit-config netdata.conf` doesn’t work as users expect if there is no `netdata.conf` file, and that you can’t check the effective configuration if you have the web server disabled.

### Description

We should have a way to fetch the same data that is provided by the `/netdata.conf` endpoint.

In an ideal situation, this would be an option for the agent like `-W dumpconfig` which simply writes the same data to `stdout`.

In a less ideal situation, a similar command for `netdatacli` would also work, as that would still allow us to dump the configuration without needing to hit the API directly.

### Importance

really want

### Value proposition

1. Once actually implemented, this can be integrated with the `edit-config` script to better handle the case of a user going to edit `netdata.conf` when it does not already exist.
2. Users who do not have the web server enabled can still check the effective configuration locally.
3. If the `-W` option approach is taken, this can also be used as a primitive config validation tool for `netdata.conf`.

**Comment by get265** [comment]
Thanks
