### ISSUE TITLE
[Feat]: Add support for offline migration of a Netdata install

### ISSUE THREAD

**Issue by Dim-P** [netdata/netdata#14764]
### Problem

Currently, there is no automatic way to migrate a Netdata install to a new machine: [
How to migrate master to a new server and all the previously collected data? ](https://community.netdata.cloud/t/how-to-migrate-master-to-a-new-server-and-all-the-priviously-collected-data/3967)

### Description

There needs to be an automated way to do this, with minimal user intervention. Some suggestions from the linked thread:
> I expect to have one of the following way:
>
>  Ansible playbook that does it for me
>  documentation with clear steps so that no chances of losing the data
>  replication that does it seamlessly

Possibly `netdata-cli` could also be used for this purpose, to compress the directories from the old install and decompress them in the new one.

### Importance

must have

### Value proposition

Replication is not good enough for this, there needs to be an offline, reliable and fast way to migrate data to a new server. 

### Proposed implementation

See above.

**Comment by Ankk98** [comment]
I am willing to contribute to this.

**Comment by ilyam8** [comment]
>  reliable and fast way to migrate data to a new server

I think `rsync` will do.
