### ISSUE TITLE
[Bug]: database/engine/pagecache.c Segfault

### ISSUE THREAD

**Issue by CreeperFace00** [netdata/netdata#14887]
### Bug description

One of my systems has started encountering a segfault during agent startup, it appears to be related to streaming/replication.

Coredump: https://gist.github.com/CreeperFace00/ccd0801be1d6f77f0f9411598662ca4c
This crash does not occur when streaming is disabled on this node.
I also tried clearing this nodes /var/cache/netdata/* directory with the same results.

### Expected behavior

Agent does not crash when streaming is enabled.

### Steps to reproduce

1. Have one of my very temperamental systems
2. Start the agent with streaming enabled
3. Profit(?)

### Installation method

from git

### System info

```shell
[root@bcc-pve netdata]$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux bcc-pve 5.11.22-5-pve #1 SMP PVE 5.11.22-10 (Tue, 28 Sep 2021 08:15:41 +0200) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
[root@bcc-pve netdata]$ netdata -W buildinfo
Version: netdata v1.38.0-356-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O1 -ggdb -DNETDATA_INTERNAL_CHECKS=1' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Here's this systems error.log taken after a crash occurred: 
https://gist.github.com/CreeperFace00/65192c2f75ae4afd5fe1d8a0ff54b127

**Comment by stelfrag** [comment]
Hi @CreeperFace00 

Can you please fetch latest code, compile with  `-O0` to have a better idea of the optimized out variables when it core dumps again. 

So as I understand this is proxy parent. 

It crashes when itself connects to a parent but it will not when itself accepts incoming children connections. Please confirm.

**Comment by CreeperFace00** [comment]
Yes, this is a proxy parent. It only crashes when connecting to the main parent, and accepts children just fine.

I'll be able to compile with the flag you mentioned tomorrow. I'm currently out of the office at the moment.

**Comment by CreeperFace00** [comment]
Okay, I managed to reproduce a crash after compiling with that flag. Weirdly It does not crash consistently when compiling with `-O0` however it crashes every-time when compiling with `-O1`
Even stranger is that the output of the coredump is vastly different than the one I originally posted.

This one seems to point to ML being problematic: https://gist.github.com/CreeperFace00/3f860a3e4d5ea018466ad79a3b413103
This is a coredump generated after disabling ML, though this is a SIGABRT rather than a SIGSEGEV: https://gist.github.com/CreeperFace00/5814533c20942fed9f772dc8b9eb2baf

I compiled with the `--disable-ml` flag set and I haven't seen a crash occur since. I'll let you know if that changes in the meantime.

**Comment by MrZammler** [comment]
Hi Max! What was the version of netdata of the latest compile?

**Comment by CreeperFace00** [comment]
I am not sure what the build was on my last post, I forgot to look. The agent seems to have auto updated since then.
This is the latest compile:
```
[root@bcc-pve netdata]$ netdata -W buildinfo
Version: netdata v1.38.0-421-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
[root@bcc-pve netdata]$
```

This is the latest coredump I was able to reproduce. This was compiled with ML enabled, it is once again different from the last: https://gist.github.com/CreeperFace00/075af39ea75c3c3fb97597eaa66395b3
This took about 8 agent restarts to trigger with `-O0` set
 

Compiling with --disable-ml and restarting a few times results in the same crash. I am thinking the ML thing might be a separate bug entirely, though it's weird it's the only crash I could cause 3 days ago, so I am not sure.

I don't seem to be able to reproduce a crash after disabling child connections on the proxy parent.

**Comment by MrZammler** [comment]
Hi @CreeperFace00 is it possible to try this [patch](https://github.com/netdata/netdata/pull/14960) if it solves the issue ?

**Comment by CreeperFace00** [comment]
```
[root@bcc-pve netdata]$ netdata -W buildinfo
Version: netdata v1.38.0-432-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```
Seems to still happen after a couple restarts: https://gist.github.com/CreeperFace00/8edfe575f0f36c06760298e5dced3ec8
This one is a SIGABRT: https://gist.github.com/CreeperFace00/aeb0df0cf99c424249f135f2a976aff0

**Comment by CreeperFace00** [comment]
Just sent those over to you.

**Comment by MrZammler** [comment]
After a discussion on discord with @CreeperFace00 we're closing this since access to this particular machine is no longer available.
