### ISSUE TITLE
[Bug]:  ebpf.plugin - High CPU Usage (HARDIRQ thread)

### ISSUE THREAD

**Issue by proteus88** [netdata/netdata#14892]
### Bug description

After updating to "v1.38.0-366-nightly" ebpf.plugin is using 1 core at 100%

### Expected behavior

Lower CPU Usage

### Steps to reproduce

Update to 1.38.0-366-nightly

### Installation method

kickstart.sh

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu                                                                                          │1518587 root       20   0 21696  4976  4084 S  0.0  0.0  0:00.18 /lib/systemd/systemd-udevd
/etc/lsb-release:DISTRIB_RELEASE=20.04                                                                                      │   2067 wazuh      20   0  240M  4108  2440 S  0.0  0.0  0:42.19 /var/ossec/bin/wazuh-agentd
/etc/lsb-release:DISTRIB_CODENAME=focal                                                                                     │1529824 root       20   0 21696  2204  1312 S  0.0  0.0  0:00.01 /lib/systemd/systemd-udevd
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"                                                                   │1529896 root       20   0 13176  8448  7280 S  0.0  0.0  0:00.01 sshd: librariaroua [priv]
/etc/os-release:NAME="Ubuntu"                                                                                               │1527482 netdata    39  19  757M 51912 37240 S  0.0  0.1  0:00.37 /usr/libexec/netdata/plugins.d/go.d.plugin 1
/etc/os-release:VERSION="20.04.6 LTS (Focal Fossa)"                                                                         │1527412 netdata    39  19 1054M  131M 14724 S  0.0  0.2  0:02.62 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
/etc/os-release:ID=ubuntu                                                                                                   │1527577 netdata    39  19  757M 51912 37240 S  0.0  0.1  0:00.22 /usr/libexec/netdata/plugins.d/go.d.plugin 1
/etc/os-release:ID_LIKE=debian                                                                                              │    756 root       20   0 17720  6640  5536 S  0.0  0.0 13:04.95 /lib/systemd/systemd-logind
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.6 LTS"                                                                            │1527359 netdata    39  19 1054M  131M 14724 S  0.0  0.2  0:00.10 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
/etc/os-release:VERSION_ID="20.04"                                                                                          │1527662 netdata    39  19 51936 31700 10704 S  0.0  0.0  0:00.14 /usr/bin/python3 /usr/libexec/netdata/plugins.d/python.d.pl
/etc/os-release:VERSION_CODENAME=focal                                                                                      │3104523 mysql      20   0 17.2G 13.3G 41852 S  0.0 21.1 31:32.27 /usr/sbin/mysqld
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.38.0-366-nightly                                                                                        │1527506 root       39  19  770M 11004  4860 R 100.  0.0 20:25.18 /usr/libexec/netdata/plugins.d/ebpf.plugin 1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${│ 466324 www-data   20   0  854M  606M  190M S 13.2  0.9 31:36.83 php-fpm: pool www
prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-li│    978 mysql      19  -1 17.2G 13.3G 41852 S  6.0 21.1     114h /usr/sbin/mysqld
nux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libex│1477200 mysql      20   0 17.2G 13.3G 41852 S  6.0 21.1  1h05:42 /usr/sbin/mysqld
ecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-depend│   1232 root       20   0 2527M  132M 55004 S  2.6  0.2 13h59:01 /usr/bin/crowdsec -c /etc/crowdsec/config.yaml
ency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong │1527428 netdata    39  19  132M  8364  4284 S  0.7  0.0  0:15.26 /usr/libexec/netdata/plugins.d/apps.plugin 1
-Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'│   1301 nginx      20   0 20720 17808 15324 S  0.7  0.0 14:46.44 nginx: worker process
 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'          │1511079 root       20   0  8984  4900  3436 R  0.7  0.0  0:28.53 htop
Install type: binpkg-deb                                                                                                    │1527159 netdata    39  19 1055M  132M 14724 S  0.7  0.2  0:21.50 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
    Binary architecture: x86_64                                                                                             │   1274 root       20   0 2527M  132M 55004 S  0.7  0.2 57:22.40 /usr/bin/crowdsec -c /etc/crowdsec/config.yaml
    Packaging distro:                                                                                                       │   1275 root       20   0 2527M  132M 55004 S  0.7  0.2 54:35.91 /usr/bin/crowdsec -c /etc/crowdsec/config.yaml
Features:                                                                                                                   │1527412 netdata    39  19 1055M  132M 14724 S  0.7  0.2  0:02.71 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
    dbengine:                   YES                                                                                         │   1401 root       20   0 2527M  132M 55004 S  0.7  0.2 53:26.95 /usr/bin/crowdsec -c /etc/crowdsec/config.yaml
    Native HTTPS:               YES                                                                                         │   1240 root       20   0 2527M  132M 55004 S  0.7  0.2 56:25.29 /usr/bin/crowdsec -c /etc/crowdsec/config.yaml
    Netdata Cloud:              YES                                                                                         │2157000 mysql      20   0 17.2G 13.3G 41852 S  0.7 21.1 51:44.27 /usr/sbin/mysqld
    ACLK:                       YES                                                                                         │1527421 netdata    39  19 1055M  132M 14724 S  0.7  0.2  0:00.25 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
    TLS Host Verification:      YES                                                                                         │ 466317 www-data   20   0  848M  620M  187M S  0.0  1.0 33:38.29 php-fpm: pool www
    Machine Learning:           YES                                                                                         │ 699830 www-data   20   0  517M  289M  185M S  0.0  0.4 27:41.48 php-fpm: pool www
    Stream Compression:         YES                                                                                         │3104486 mysql      20   0 17.2G 13.3G 41852 S  0.0 21.1 31:59.50 /usr/sbin/mysqld
Libraries:                                                                                                                  │   1242 root       20   0 2527M  132M 55004 S  0.0  0.2 56:24.90 /usr/bin/crowdsec -c /etc/crowdsec/config.yaml
    protobuf:                YES (system)                                                                                   │  65581 root       20   0 2527M  132M 55004 S  0.0  0.2 57:01.96 /usr/bin/crowdsec -c /etc/crowdsec/config.yaml
    jemalloc:                NO                                                                                             │1527399 netdata    39  19 1055M  132M 14724 S  0.0  0.2  0:01.75 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
    JSON-C:                  YES                                                                                            │1527437 netdata    39  19  757M 52440 37240 S  0.0  0.1  0:03.93 /usr/libexec/netdata/plugins.d/go.d.plugin 1
    libcap:                  NO                                                                                             │1527418 netdata    39  19 1055M  132M 14724 S  0.0  0.2  0:01.53 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
    libcrypto:               YES                                                                                            │1527433 netdata    39  19 51936 31700 10704 S  0.0  0.0  0:01.02 /usr/bin/python3 /usr/libexec/netdata/plugins.d/python.d.pl
    libm:                    YES                                                                                            │1527447 netdata    39  19  757M 52440 37240 S  0.0  0.1  0:00.15 /usr/libexec/netdata/plugins.d/go.d.plugin 1
    tcalloc:                 NO                                                                                             │   1190 mysql      20   0 17.2G 13.3G 41852 S  0.0 21.1  0:18.46 /usr/sbin/mysqld
    zlib:                    YES                                                                                            │3104509 mysql      20   0 17.2G 13.3G 41852 S  0.0 21.1 28:05.64 /usr/sbin/mysqld
Plugins:                                                                                                                    │ 699845 www-data   20   0  465M  239M  189M S  0.0  0.4 26:25.07 php-fpm: pool www
    apps:                    YES                                                                                            │3104535 mysql      20   0 17.2G 13.3G 41852 S  0.0 21.1 24:23.28 /usr/sbin/mysqld
    cgroup Network Tracking: YES                                                                                            │   1233 root       20   0 2527M  132M 55004 S  0.0  0.2  6:42.31 /usr/bin/crowdsec -c /etc/crowdsec/config.yaml
    CUPS:                    YES                                                                                            │    727 messagebu  20   0  7496  4312  3380 S  0.0  0.0 14:42.87 /usr/bin/dbus-daemon --system --address=systemd: --nofork -
    EBPF:                    YES                                                                                            │1527484 netdata    39  19  757M 52440 37240 S  0.0  0.1  0:00.31 /usr/libexec/netdata/plugins.d/go.d.plugin 1
    IPMI:                    YES                                                                                            │   1309 nginx      20   0 20664 17752 15324 S  0.0  0.0 14:07.78 nginx: worker process
    NFACCT:                  YES                                                                                            │1527448 netdata    39  19  757M 52440 37240 S  0.0  0.1  0:00.39 /usr/libexec/netdata/plugins.d/go.d.plugin 1
    perf:                    YES                                                                                            │ 466309 www-data   20   0  471M  246M  189M S  0.0  0.4 33:46.63 php-fpm: pool www
    slabinfo:                YES                                                                                            │2648751 mysql      20   0 17.2G 13.3G 41852 S  0.0 21.1 34:48.69 /usr/sbin/mysqld
    Xen:                     NO                                                                                             │ 466323 www-data   20   0  850M  604M  194M S  0.0  0.9 34:14.82 php-fpm: pool www
    Xen VBD Error Tracking:  NO                                                                                             │2648898 mysql      20   0 17.2G 13.3G 41852 S  0.0 21.1 42:43.92 /usr/sbin/mysqld
Exporters:                                                                                                                  │1527413 netdata    39  19 1055M  132M 14724 S  0.0  0.2  0:01.51 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
    AWS Kinesis:             NO                                                                                             │1527475 netdata    39  19 1055M  132M 14724 S  0.0  0.2  0:00.51 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
    GCP PubSub:              NO                                                                                             │1527429 netdata    39  19 1055M  132M 14724 S  0.0  0.2  0:00.20 /usr/sbin/netdata -D -P /var/run/netdata/netdata.pid
    MongoDB:                 NO                                                                                             │1471443 root       20   0  8000  3848  2976 S  0.0  0.0  0:02.38 tmux
    Prometheus Remote Write: YES                                                                                            │   1194 mysql      20   0 17.2G 13.3G 41852 S  0.0 21.1  2:39.39 /usr/sbin/mysqld
Debug/Developer Features:                                                                                                   │   1206 mysql      20   0 17.2G 13.3G 41852 S  0.0 21.1  8:57.33 /usr/sbin/mysqld
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
@proteus88 @enclave-alistair thanks for reporting, guys!

- Do you have a non-default ebpf configuration? (ebpf.d.conf)
- @enclave-alistair Can you provide (some of) your systems info (`uname -a; grep -HvE "^#|URL" /etc/*release`)?

**Comment by enclave-alistair** [comment]
No files in `ebpf.d`.

Here's the system info:
```
Linux ip-172-0-9-201 5.15.0-1019-aws #23-Ubuntu SMP Wed Aug 17 18:33:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

**Comment by enclave-alistair** [comment]
Also, FYI, restarting netdata does not fix the problem.

**Comment by thiagoftsm** [comment]
Hello @enclave-alistair ,

Before last nightly update the plugin was crashing in environments like yours, but we merged a bug fix to remove the previous issue.
Now about the high CPU usage, let me do some questions for me try to recreate and fix the issue:

- Are you running a VM? If it is a VM, what is the VM?
- Is your computer a high loaded server? If yes, how many clients in average connects to it.
- I already observed issues on Ubuntu for specific kernel versions. Right now on my Ubuntu 20.04 VM I am running kernel `5.4.0-146-generic`, what is your current kernel version?

Best regards!

**Comment by kallioaleksi** [comment]
I have the same issue on an old EC2 instance running Ubuntu 20.04.4. Not a high-load server, kernel version `5.15.0-1033-aws`.

**Comment by enclave-alistair** [comment]
@thiagoftsm, the servers in question are AWS EC2 instances running Ubuntu 22.04, kernel version `5.15.0-1026-aws`. They are 2 vCPU, 4GB instances.  

These systems run docker, and a single docker container instance on each box is responsible for moving network traffic (and uses iptables to do so). An SNAT rule is defined to allow the docker container to function as a form of NAT device between a virtual network and the "real" one.

The docker container has no more than 11 open sockets, including listeners.

The presence of iptables certainly might indicate the relation to ebpf, but also possibly the presence of multiple network namespaces via docker?

**Comment by proteus88** [comment]
Not a VM, a dedicated PC/Server from Hetzner
AX41 - Ryzen 5 3600

Ubuntu 20.04.6 -  kernel: 5.4.0-146-generic
nginx/1.23.4
php7.4-fpm
zabbix agent 6.0.16
wazuh agent 4.4.1

APT history from this morning
Start-Date: 2023-04-12  06:49:59
Commandline: /usr/bin/unattended-upgrade
Upgrade: sudo:amd64 (1.8.31-1ubuntu1.4, 1.8.31-1ubuntu1.5)
End-Date: 2023-04-12  06:50:02

Start-Date: 2023-04-12  07:27:16
Commandline: apt-get --only-upgrade install -y netdata
Upgrade: netdata:amd64 (1.38.0-354-nightly, 1.38.0-366-nightly)
End-Date: 2023-04-12  07:27:30

History from the last 7 days

![image](https://user-images.githubusercontent.com/41756722/231462179-a66f5483-7508-44d5-baea-7a4e8efb21f8.png)

![image](https://user-images.githubusercontent.com/41756722/231463177-b7f98e0d-0b29-4a3b-9476-6e83e5e52db4.png)

**Comment by thiagoftsm** [comment]
Thank you very much to help us debug with information you are giving.

@kallioaleksi , @enclave-alistair and @proteus88 unless I missed something all of you are using Ubuntu kernels on different hardware and they are different versions. I will address the comments independently  and after this I will ask additional information for we fix ASAP:

- @kallioaleksi: eBPF plugin running kernels older than `5.10` will consume more resources, because it is forced to use `k(ret)probe` instead new `trampolines` and this always add overhead for each function call.
- @enclave-alistair : 
> The presence of iptables certainly might indicate the relation to ebpf, but also possibly the presence of multiple network namespaces via docker?
   Your conclusions are correct, but in normal situation we do not expect eBPF running inside docker containers. In the past this was disabled by default, and I am not sure they are allowing this nowadays. I was thinking in the possibility that socket could be the main source of issues, because `socket` stores data per socket open, so it needs more resources to process everything. And like `vfs` it is the thread that monitors more internal functions.
> @proteus88: what I described for @enclave-alistair is confirmed in your data, because PHP apps an mysql needs sockets to deliver data for your users.

Now I will require a small modification for all of you:

- Please, run the following commands:
```sh
# cd /etc/netdata/
# ./edit-config ebpf.d.conf
```
and disable socket:

```sh
[ebpf programs]
    socket = no
    network connections = no
```

After this restart netdata.
I am trying to replicate the issues here on my environment, but I did not have success. With your additional information I will try to create a scenario like yours. On the other hand, you have the issue already happened on your environment, if it is possible to give access trough `ssh` for your environment for us to help the debug and fix the issue, please, contact me using my email thiago@netdata.cloud.

**Comment by kallioaleksi** [comment]
@thiagoftsm For me, socket and network connections were already disabled. Restarting netdata causes `ebpf.plugin` to immediately consume 100% of CPU.

**Comment by proteus88** [comment]
The same for me, socket and network connections were already disabled.

**Comment by ilyam8** [comment]
Guys, can you check what thread uses 100%? I usually use `htop`:

- setup (F2) -> display options -> check tree view, show custom thread names.
- done (F10)
- search (F3) and just type `ebpf.plugin`


<img width="1426" alt="Screenshot 2023-04-12 at 16 35 03" src="https://user-images.githubusercontent.com/22274335/231474492-9c853041-10f1-4cb7-b319-a66db0ccbe57.png">

**Comment by enclave-alistair** [comment]
@ilyam, the thread is HARDIRQ:

![image](https://user-images.githubusercontent.com/67738909/231476258-c9a0a652-2b93-4763-bd9d-10836eedad3d.png)

re: @thiagoftsm's request, I already have the default config of socket and network connection **off**.

Afraid I will struggle to give you access to these VMs, they're production.  I can attempt to recreate  in a new VM with similar properties, see if the problem materialises there?

**Comment by proteus88** [comment]
![image](https://user-images.githubusercontent.com/41756722/231477339-a81b8cea-538a-4ed9-a11a-f3cea12dcd3d.png)

**Comment by ilyam8** [comment]
Thanks! We will disable the thread as a quick fix.

**Comment by ilyam8** [comment]
>  I can attempt to recreate in a new VM with similar properties, see if the problem materialises there?

@enclave-alistair this would help a lot!

**Comment by thiagoftsm** [comment]
> @enclave-alistair this would help a lot!

I agree with Ilya. 
`hardirq` events happen in a frequency that needs some times million of updates during the day depending on server, so we can confirm this and document properly.

**Comment by thiagoftsm** [comment]
As @ilyam8 said we are going to disable the thread, because it has a high frequency number of updates and as you showed us this impact direct hosts like `EC2` hosts.
I initially added changes for documentation, but I removed. I will bring another doc update when we finish the event investigation.

**Comment by Delaunay** [comment]
This also happens on bare bone Ubuntu server.

Since when are users used for testing the nightly builds ?
As far as I am concerned that feature should never have I made it to my server in that state.


```
Linux nas 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

**Comment by thiagoftsm** [comment]
> This also happens on bare bone Ubuntu server.
> 
> Since when are users used for testing the nightly builds ? As far as I am concerned that feature should never have I made it to my server in that state.

Hello,

We are seeing this happening on some `Debian` flavors and possible other servers depending of hardware it is running.
Now, about the selection between `nightly` and `stable`, this is an option selected during installation time as you can see in our [documenttation](https://learn.netdata.cloud/docs/getting-started/install-netdata#install-on-linux-with-one-line-installer). 

Best regards!

**Comment by willbrowningme** [comment]
You can run: 

```bash
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --disable-telemetry --reinstall
```

to move from `nightly` to `stable` releases.

**Comment by enclave-alistair** [comment]
@thiagoftsm, I've dropped you an email with access details for a fresh VM I've spun up that recreates the issue.

**Comment by thiagoftsm** [comment]
> @thiagoftsm, I've dropped you an email with access details for a fresh VM I've spun up that recreates the issue.

Thank you very much,  I am already debugging. :handshake:

**Comment by thiagoftsm** [comment]
> I really don't remember if I installed it with Kickstarter, how can I check ?

Inside `/etc/netdata/.install-type` you will have the method used to install netdata. 
If netdata is installed inside `/opt`, probably kickstart-static was the installation method.

**Comment by thiagoftsm** [comment]
> I really don't remember if I installed it with Kickstarter, how can I check ?

Inside `/etc/netdata/.install-type` you will have the method used to install netdata. 
If netdata is installed inside `/opt`, probably kickstart-static was the installation method.

**Comment by iamshaynez** [comment]
Thanks guys, diable hardirq helped the same issue on my VM. Ubuntu on 5.4.0-146-generic.

**Comment by thiagoftsm** [comment]
Hello guys,

I am reopening this issue, because I could debug better the issue with your help and @enclave-alistair VM.
The new PR is not finalized yet, because I observed other issue that was also only appearing on his VM, so as soon I finish the PR this issue will be properly closed.

Thank you everybody to report the issue and giving us additional data that help us to fix properly the issue.

Best regards!

**Comment by thiagoftsm** [comment]
Hello everybody,

We are now officially closing this issue.
I apologize for the issues created and I also would like to say thank you very much for your help that allow us to recreate the issue and fix it properly.

Best regards!
