### ISSUE TITLE
alarms based on statistical analysis, or even deep learning

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#1490]
Happy New Year!

I found today the excellent article of @ZygmuntZ at: http://fastml.com/bayesian-machine-learning/

I have spend quite some time reading statistics and deep learning algorithms, trying to figure out if we can add a better / smarter alarming mechanism to http://my-netdata.io

But, I am not a data scientist, so most of it is still confusing for me (yeah, I know).

What I read though in such articles, is really interesting.

For example, if we could somehow know the probability of the value we just collected, based on the history of each metric we have, we could have a lot smarter alarms. Alarms that could help us pinpoint the conditions under which our web servers a facing abnormally high or low traffic, that our databases are struggling to serve the load offered to them, that our systems are unreasonably throttling requests, etc.

If you understand the math and you are willing to help thousands of people monitor their servers in a better way, please join the discussion here and help me figure this out...

Thanks!

**Comment by ririsoft** [comment]
What kind of true alarm use cases are you looking for an improvement ?

I have one in mind: week on week: The activity of the current week is compared to the activity of the week before. This allows to eliminate alarms that raises during the week end or the night where the activity is lower.

**Comment by Ferroin** [comment]
I've been thinking about this one myself a bit recently.  There are some cases where this would be _really_ helpful for eliminating false positives (the netdev budget alarm immediately comes to mind). and it would be really neat to be able to automatically recognize and report usage spikes.  I think it might be possible to do both of those with some more creative usage of the existing interface (for example, comparing the current value to some threshold above the long-term average of the value) without needing any new code. I'll look into testing some of that and report back about how it goes (or open a PR referencing this issue if I can get it working well enough that it could reasonably be merged).

**Comment by ktsaou** [comment]
Ideally, we would like to have an algorithm for detecting outliers. netdata has already algorithms for exponential smoothing (eg. holtwinters), but on my tests, these are not that useful - a lot of false positives.

Another way may be to use deep learning (AI) methodology to detect outliers. This however may increase cpu usage significantly. I have found libfann that supports adaptive learning and seems pretty simple, but I need to do some testing with it: https://github.com/libfann/fann/issues/83

A more practical approach could be to apply some kind of dynamic heuristics. For example, netdata could maintain for each metric, the min, max and average (or median) for each hour of each named day (so a fixed array of 24 x 7 = 168 entries). The entries in this array could be dynamically be updated once per hour (ie "learned" as time goes) and then alarms could be triggered based on the last minute deviation from the min, max, average for the current hour.

The above could provide a self learning system and the means to trigger alarms based on thresholds the user could provide (the alarm configuration could state the time to examine and the thresholds to trigger warning and critical alarms).

**Comment by Ferroin** [comment]
Oh, I definitely agree it would be better to do proper detection of outliers.  It doesn't have to be fancy though, something as simple as assuming a normal distribution with independent positive and negative standard deviations, and then just count anything outside three standard deviations as outliers will work well enough for a vast majority of things here without needing a huge amount of processing power.

However, there are cases where a reasonable approximation can be done by just marking values that are beyond some percentage of the average away from the average as outliers.  I'm fairly certain that the netdev budget alarm _should_ be a case like this.

The problem here is that with what netdata currently provides, it's only possible to detect spikes or drops in usage this way, not unusually high or low long-term usage, and you can't know for certain whether the alarm cleared because the spike is gone, or because it normalized to the new higher (or lower) value.

**Comment by ririsoft** [comment]
> However, there are cases where a reasonable approximation can be done by just marking values that are beyond some percentage of the average away from the average as outliers. I'm fairly certain that the netdev budget alarm should be a case like this.

`netdev budget` is a total mystery to me. I did not find any tunable that make such spikes disappear. For this case I believe netdata's current alerting threshold system is enough, until I truly understand its behavior.

> A more practical approach could be to apply some kind of dynamic heuristics. For example, netdata could maintain for each metric, the min, max and average (or median) for each hour of each named day (so a fixed array of 24 x 7 = 168 entries). The entries in this array could be dynamically be updated once per hour (ie "learned" as time goes) and then alarms could be triggered based on the last minute deviation from the min, max, average for the current hour.
> 
> The above could provide a self learning system and the means to trigger alarms based on thresholds the user could provide (the alarm configuration could state the time to examine and the thresholds to trigger warning and critical alarms).

I would definitely explore this before going to deep learning. However there are cases which fail with an heuristic approach (that deep learning could solve) : bank holidays, black friday, world cup for instance. But still what you suggest would be a major improvement.

Another issue you have is when the trend constantly changes within the allowed deviation. After a period of time you end with, for instance, transaction elapse time doubled without noticing. To prevent this you have to specify a global maximum value.

**Comment by Ferroin** [comment]
> netdev budget is a total mystery to me. I did not find any tunable that make such spikes disappear. For this case I believe netdata's current alerting threshold system is enough, until I truly understand its behavior.

The actual value being tracked by the alerts is partially influenced by a couple of tunables in `/proc`, but most of it is a function of how fast your system can process packets and how many packets are coming in.  It's almost impossible to manually eliminate alerts for this.  As an example, my big Ryzen 7 home server rarely goes above single digits for overruns even with rather large amounts of traffic (saturating multiple network links simultaneously), while the two dinky little VPS nodes I'm contributing to the pool.ntp.org project regularly are in the low triple digits.

Realistically though, provided you have mostly consistent rates of inbound packets, you will have a reasonably constant value for the number of overruns, and it's sudden spikes that matter (and usually translate to lost packets).

**Comment by ktsaou** [comment]
@cakrit 	smarter alarms is on our roadmap.
We have already added a lot statistical algorithms to the query engine, but we need to work more for providing a smarter, automated engine for detecting anomalies.

**Comment by cakrit** [comment]
Automatic anomaly detection is in the roadmap, will discuss with @gmosx

**Comment by FedericoCeratto** [comment]
Having worked with large proprietary metric analysis platforms, few thoughts:
- never use or show minimum/maximum/average values: they are often misleading. Use percentiles, typically 1,5,10,50,90,95,99
- you should not trust a host to monitor itself and take remedial actions
- don't average/min/max across different (identical) hosts running the same workload: there are often outlier hosts on any large fleet. Look for 95p.
- yearly patterns are often more relevant than monthly and weekly
- different metrics often correlate in some way (think scatterplot) during normal uptime but stop correlating during failures. E.g. network traffic, memory usage and disk I/O for a certain process move together during most days unless the process reach a bottleneck.
- ...is Netdata the right place to do long term metric storage and analysis or perhaps a tool that feeds from it?

**Comment by ktsaou** [comment]
@FedericoCeratto 	you are opening a large discussion.

> * never use or show minimum/maximum/average values: they are often misleading. Use percentiles, typically 1,5,10,50,90,95,99

Of course.

> * you should not trust a host to monitor itself and take remedial actions

Then, you should not trust anything, since the host collects and exposes the metrics. If the collection is wrong, everything will be wrong - no matter where it is located.

My experience with netdata, is exactly the opposite. The network may be lost, the disks may fail, but netdata will still run collecting metrics.

The only thing you can't do from the host itself, is monitor its availability (i.e. is the host running?). Everything else is better to be done on the host itself.

> * don't average/min/max across different (identical) hosts running the same workload: there are often outlier hosts on any large fleet. Look for 95p.

Of course.

> * yearly patterns are often more relevant than monthly and weekly

This is for capacity planning, not performance troubleshooting. Even minute patterns are useless for performance troubleshooting.

This is why netdata is aligned to the second.

> * different metrics often correlate in some way (think scatterplot) during normal uptime but stop correlating during failures. E.g. network traffic, memory usage and disk I/O for a certain process move together during most days unless the process reach a bottleneck.

Of course.

> * ...is Netdata the right place to do long term metric storage and analysis or perhaps a tool that feeds from it?

Is it practical to do it anywhere else?

In my experience performance troubleshooting is impossible with 10s granularity metrics. You cannot troubleshoot an SLA of 2s, with metrics of 10s. It is just not technically possible.

If you check the monitoring industry, they all want to do 1s. But they can't. Either it is just too expensive for them, for it does not scale.

**Comment by FedericoCeratto** [comment]
>> you should not trust a host to monitor itself and take remedial actions

> The only thing you can't do from the host itself, is monitor its availability (i.e. is the host running?). 

That's the problem. When sending metrics to an external monitoring system, silence is treated as an error condition. If a host becomes unreachable for any reason a remedial action can be taken.
If the host itself it generating alerts for itself silence means that everything is good, and this leads to false negatives.
On large scale systems this also leads to split brain scenarios and/or cascading failures, typically when there are routing issues on the network or partial network outages.
I'm talking about availability, not performance monitoring in this context.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
