### ISSUE TITLE
Bitcoin Bitmain Node/Miner Collector

### ISSUE THREAD

**Issue by Exohayvan** [netdata/netdata#14926]
### Description

Looking for a collector for the Bitmain Node/Miners to check watch Hashrate/CPU usage and so on.

### Importance

must have

### Value proposition

1. Would help others have a monitor theirs.
2. Would really make netdata a one in all service
3. Would allow others that are in the same boat be able to combine into one service.
...

### Proposed implementation

Willing to sponsor collector with the knowledge I have.

**Comment by cakrit** [comment]
https://github.com/ckolivas/cgminer/blob/master/API-README is how we get the data

**Comment by Exohayvan** [comment]
Found this monitoring that’s been made already? https://github.com/romdr/cgminer-monitor

**Comment by Exohayvan** [comment]
PR - https://github.com/netdata/go.d.plugin/pull/1173
