### ISSUE TITLE
[Feat]: Add node OS and type to Alert information

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#14923]
### Problem

We need to provide customized troubleshooting instructions per alert - and having the OS and type (container, kubernetes, bare metal etc.) information would allow us to do this accurately.

### Description

Adding the following fields (listed here from node info json) as part of alert `info` would enable troubleshooting instructions to be customized.

```
"os"
"_container"
"_container_detection"
```

### Importance

must have

### Value proposition

1. Empower users to troubleshoot alerts

**Comment by MrZammler** [comment]
Hi @shyamvalsan !

Could you please elaborate a bit more on this? You mean to have a way to put e.g. OS in the info field of an alert configuration? 

For example, define the `info` in `10min_cpu_usage` as `average CPU utilization over the last 10 minutes (excluding iowait, nice and steal) for ${host_label:_container}` or similar?

**Comment by shyamvalsan** [comment]
Hi @MrZammler let me try and explain a bit better. 

The Alerts API currently returns the following for `/api/v2/spaces/{spaceID}/rooms/{roomID}/alarms/{alarm}/nodes/{nodeID}/charts/{chart}`

```
{
	"hostname": "ip-10-200-142-160.ec2.internal",
	"id": "netdata.execution_time_of_coredns_coredns-kube-system_coredns-66cb55d4f4-zdklb_coredns_tcp_9153.go.d_job_last_collected_secs",
	"alarm": "go.d_job_last_collected_secs",
	"chart": "netdata.execution_time_of_coredns_coredns-kube-system_coredns-66cb55d4f4-zdklb_coredns_tcp_9153",
	"chartContext": "netdata.go_plugin_execution_time",
	"info": "number of seconds since the last successful data collection",
	"class": "Error",
	"type": "Netdata",
	"component": "go.d.plugin",
	"family": "",
	"calculationExpr": "$now - $last_collected_t",
	"warningExpr": "$this > (($status >= $WARNING) ? ($update_every) : ( 5 * $update_every))",
	"criticalExpr": "$this > (($status == $CRITICAL) ? ($update_every) : (60 * $update_every))",
	"updateEvery": 10,
	"delay": "down 5m multiplier 1.5 max 1h",
	"lookupDimensions": "",
	"lookupMethod": "",
	"lookupOptions": "",
	"lookupAfter": 0,
	"lookupBefore": 0,
	"status": "CRITICAL",
	"nodeInstances": [
		{
			"parentID": "054b5fee-a743-473c-b0d2-8d394c43a333",
			"parentHostname": "netdata-parent-latest",
			"status": "CRITICAL",
			"value": 67,
			"units": "seconds ago",
			"transitionAt": "2023-04-11T06:15:40Z"
		}
	]
}
```


What I am looking for is a way to add the node's OS and type to this list (and I'm assuming Anomaly Rate will be available soon as well). 

What this enables is for the new automated alert troubleshooting feature to give very specific troubleshooting steps to the user instead of generic directions.

**Comment by MrZammler** [comment]
Ok, so pinging @car12o since this is a backend json. We could transmit the OS with alert events, or I believe if the backend already has the os and containers data, it could include it there maybe?

**Comment by car12o** [comment]
We already have an endpoint that returns the data you need and even more, why do you want to couple it with alerts?
```
Request URL: https://app.netdata.cloud/api/v1/nodes/3a10ed4e-65e4-49e3-a7f8-fa5a6550cefc/info

```
