### ISSUE TITLE
Zcash Bitmain Node/Miner Collector

### ISSUE THREAD

**Issue by Exohayvan** [netdata/netdata#14925]
### Description

Looking for a collector for the Bitmain Node/Miners to check watch Hashrate/CPU usage and so on.

### Importance

must have

### Value proposition

1. Would help others have a monitor theirs.
2. Would really make netdata a one in all service
3. Would allow others that are in the same boat be able to combine into one service.
...

### Proposed implementation

Willing to sponsor collector with the knowledge I have.

**Comment by cakrit** [comment]
For this one I see there's a prometheus endpoint: https://github.com/zcash/zcash/blob/master/doc/book/src/user/metrics.md

Please see first what you get by reading that document to prepare your node and then configuring our [generic Prometheus collector](https://learn.netdata.cloud/docs/data-collection/monitor-anything/Any%20Application%20-%20Generic%20Collectors/Prometheus-endpoints)

**Comment by Exohayvan** [comment]
I will look into this, thank you
