### ISSUE TITLE
[Feat]: zswap monitoring

### ISSUE THREAD

**Issue by Forza-tng** [netdata/netdata#14927]
### Problem

ZSwap is used by default on many Linux distributions. I think it would be good to monitor the efficiency of ZSwap and the settings, for example what compression algo is used, etc.

### Description

Add a collector that scrapes the sysfs interfaces for ZSwap information.

There are two sysfs paths related to ZSwap:
```
#  grep . /sys/module/zswap/parameters/*
/sys/module/zswap/parameters/accept_threshold_percent:90
/sys/module/zswap/parameters/compressor:lzo
/sys/module/zswap/parameters/enabled:Y
/sys/module/zswap/parameters/max_pool_percent:20
/sys/module/zswap/parameters/non_same_filled_pages_enabled:Y
/sys/module/zswap/parameters/same_filled_pages_enabled:Y
/sys/module/zswap/parameters/zpool:zbud
```
and
```
# grep . /sys/kernel/debug/zswap/*
/sys/kernel/debug/zswap/duplicate_entry:0
/sys/kernel/debug/zswap/pool_limit_hit:0
/sys/kernel/debug/zswap/pool_total_size:2988941312
/sys/kernel/debug/zswap/reject_alloc_fail:0
/sys/kernel/debug/zswap/reject_compress_poor:1748617
/sys/kernel/debug/zswap/reject_kmemcache_fail:0
/sys/kernel/debug/zswap/reject_reclaim_fail:0
/sys/kernel/debug/zswap/same_filled_pages:259913
/sys/kernel/debug/zswap/stored_pages:1707813
/sys/kernel/debug/zswap/written_back_pages:0
```

I am thinking that netdata should monitor;
* raw values from debug interface
* compressor type and zpool type
* calculation of efficiency:
Raw Size:        6465.7 MiB
Comp Size:       2769.0 MiB
Ratio:           42.8 %

### Importance

nice to have

### Value proposition

* Determine the efficiency of zswap, compression type and zpool type (zbud, z3fold, zsmalloc)

### Proposed implementation

Page size for the system needs to be taken into account when calculating space usage and savings (`stored_pages`). On x86 it is 4096 bytes, but other systems may have different page sizes.

**Comment by ilyam8** [comment]
> raw values from debug interface

[debugfs](https://docs.kernel.org/filesystems/debugfs.html) is available only to the root user by default.

**Comment by Ferroin** [comment]
> > raw values from debug interface
> 
> [debugfs](https://docs.kernel.org/filesystems/debugfs.html) is available only to the root user by default. This means that it cannot be implemented as a proc.plugin module. Only as an external plugin.

There are, arguably, other things we may want to monitor under debugfs. KVM, for example, exposes some potentially interesting metrics there, so I can see some value in just preparing such an external plugin.

**Comment by Forza-tng** [comment]
Can we use Linux Capabilities to control access, or use suid on a wrapper, like with cgroups or the slabinfo plugins? Or maybe debugfs info can be made available to netdata user by bind mounts or similar?

**Comment by ilyam8** [comment]
> Raw Size: 6465.7 MiB
> Comp Size: 2769.0 MiB
> Ratio: 42.8 %

@Forza-tng we did compression ratio as  `Raw Size` / `Comp Size`, so it is 2.33 in your case.

**Comment by Forza-tng** [comment]
> > Raw Size: 6465.7 MiB
> > Comp Size: 2769.0 MiB
> > Ratio: 42.8 %
> 
> @Forza-tng we did compression ratio as `Raw Size` / `Comp Size`, so it is 2.33 in your case.

Works too. It's just a matter of preference of the user I think. :)
