### ISSUE TITLE
[Feat]: Monitor Intel igpu

### ISSUE THREAD

**Issue by bluej007** [netdata/netdata#14931]
### Description

Add monitoring for integrated graphics on Intel CPUs

### Importance

really want

### Value proposition

1. Provides monitoring of GPU metrics

**Comment by kmoore134** [comment]
Agreed, we've got a bunch of users on TrueNAS who'd love to see this working.

**Comment by Luigi-Pizzolito** [comment]
Would be great for NetData on small home servers that have Intel iGPU only.

**Comment by kristoferen** [comment]
Now that AMD/NVIDIA stats in the Dashboard of ElectricEel is in the plan, does that mean Intel monitoring will come too?

**Comment by bshimmy** [comment]
Would also love iGPU support!

**Comment by ilyam8** [comment]
Can you share the output?

```bash
intel_gpu_top -J -s 1000 
```

**Comment by bluej007** [comment]
> Can you share the output?
> 
> ```shell
> intel_gpu_top -J -s 1000 
> ```

I grabbed the last entry after about 10 seconds.
{
        "period": {
                "duration": 1000.209664,
                "unit": "ms"
        },
        "frequency": {
                "requested": 1299.727494,
                "actual": 1099.769418,
                "unit": "MHz"
        },
        "interrupts": {
                "count": 1712.640921,
                "unit": "irq/s"
        },
        "rc6": {
                "value": 0.000000,
                "unit": "%"
        },
        "power": {
                "GPU": 6.265776,
                "Package": 17.078023,
                "unit": "W"
        },
        "engines": {
                "Render/3D/0": {
                        "busy": 100.000000,
                        "sema": 8.023034,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "Blitter/0": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "Video/0": {
                        "busy": 13.622639,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "Video/1": {
                        "busy": 14.530594,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "VideoEnhance/0": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                }
        }
}

**Comment by ilyam8** [comment]
1. I will wait samples from more people just to compare if there is any difference. It's unlikely, but I want to have at least 2.
2. @bluej007 what metrics are you interested in? Frequency and power? What else?
3. Can you leave it running and check its CPU usage over time? We need to know this to decide whether the collector will be enabled/disabled by default. You can do it by:
  - using top/htop
  - using Netdata (add `intel_gpu_top: *intel_gpu_top*` in `apps_groups.conf` and restart Netdata).

**Comment by kmoore134** [comment]
Here's a couple samples, one idle and one busy.


```
{
	"period": {
		"duration": 15.260221,
		"unit": "ms"
	},
	"frequency": {
		"requested": 0.000000,
		"actual": 0.000000,
		"unit": "MHz"
	},
	"interrupts": {
		"count": 0.000000,
		"unit": "irq/s"
	},
	"rc6": {
		"value": 100.000000,
		"unit": "%"
	},
	"power": {
		"GPU": 0.000000,
		"Package": 12.010873,
		"unit": "W"
	},
	"engines": {
		"Render/3D/0": {
			"busy": 0.000000,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		},
		"Blitter/0": {
			"busy": 0.000000,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		},
		"Video/0": {
			"busy": 0.000000,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		},
		"Video/1": {
			"busy": 0.000000,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		},
		"VideoEnhance/0": {
			"busy": 0.000000,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		}
	},
	"clients": {

	}
}
```

```
{
	"period": {
		"duration": 1055.794145,
		"unit": "ms"
	},
	"frequency": {
		"requested": 1449.146131,
		"actual": 1253.085184,
		"unit": "MHz"
	},
	"interrupts": {
		"count": 1757.918443,
		"unit": "irq/s"
	},
	"rc6": {
		"value": 0.000000,
		"unit": "%"
	},
	"power": {
		"GPU": 3.233528,
		"Package": 16.658620,
		"unit": "W"
	},
	"engines": {
		"Render/3D/0": {
			"busy": 96.092944,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		},
		"Blitter/0": {
			"busy": 0.000000,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		},
		"Video/0": {
			"busy": 72.950675,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		},
		"Video/1": {
			"busy": 77.402254,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		},
		"VideoEnhance/0": {
			"busy": 0.000000,
			"sema": 0.000000,
			"wait": 0.000000,
			"unit": "%"
		}
	},
	"clients": {
		"4292239459": {
			"name": "ffmpeg",
			"pid": "2727837",
			"engine-classes": {
				"Render/3D": {
					"busy": "101.396726",
					"unit": "%"
				},
				"Blitter": {
					"busy": "0.000000",
					"unit": "%"
				},
				"Video": {
					"busy": "159.292435",
					"unit": "%"
				},
				"VideoEnhance": {
					"busy": "0.000000",
					"unit": "%"
				}
			}
		}
	}
}
```

**Comment by bluej007** [comment]
> 1. I will wait samples from more people just to compare if there is any difference. It's unlikely, but I want to have at least 2.
> 2. @bluej007 what metrics are you interested in? Frequency and power? What else?
> 3. Can you leave it running and check its CPU usage over time? We need to know this to decide whether the collector will be enabled/disabled by default. You can do it by:
> 
> * using top/htop
> * using Netdata (add `intel_gpu_top: *intel_gpu_top*` in `apps_groups.conf` and restart Netdata).
2. Frequency, power, and utilization of each engine
3. I let the command run for about 15 minutes and both htop and Netdata registered the process as 0.0% CPU and less than 0.01 GiB memory, so it was very minimal on my system.

**Comment by ilyam8** [comment]
@bluej007 

> I grabbed the last entry after about 10 seconds.

Can you share again all the data this time? I need the whole data stream.

**Comment by bluej007** [comment]
> @bluej007
> 
> > I grabbed the last entry after about 10 seconds.
> 
> Can you share again all the data this time? I need the whole data stream.

Not certain what you mean by whole data stream. Here are more samples for Idle and Busy. I'm not sure why my output doesn't have the "clients" section.

<details>
<summary>Idle</summary>

```json
{
        "period": {
                "duration": 0.005473,
                "unit": "ms"
        },
        "frequency": {
                "requested": 0.000000,
                "actual": 0.000000,
                "unit": "MHz"
        },
        "interrupts": {
                "count": 0.000000,
                "unit": "irq/s"
        },
        "rc6": {
                "value": 100.000000,
                "unit": "%"
        },
        "power": {
                "GPU": 0.000000,
                "Package": 0.000000,
                "unit": "W"
        },
        "engines": {
                "Render/3D/0": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "Blitter/0": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "Video/0": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "Video/1": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "VideoEnhance/0": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                }
        }
}
```

</details>



<details>
<summary>Busy</summary>

```json
{
        "period": {
                "duration": 1000.348532,
                "unit": "ms"
        },
        "frequency": {
                "requested": 1299.547066,
                "actual": 1099.616748,
                "unit": "MHz"
        },
        "interrupts": {
                "count": 1903.336626,
                "unit": "irq/s"
        },
        "rc6": {
                "value": 0.067688,
                "unit": "%"
        },
        "power": {
                "GPU": 4.389583,
                "Package": 8.767147,
                "unit": "W"
        },
        "engines": {
                "Render/3D/0": {
                        "busy": 99.871089,
                        "sema": 3.501085,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "Blitter/0": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "Video/0": {
                        "busy": 20.276973,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "Video/1": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                },
                "VideoEnhance/0": {
                        "busy": 0.000000,
                        "sema": 0.000000,
                        "wait": 0.000000,
                        "unit": "%"
                }
        }
}
```

</details>

**Comment by ilyam8** [comment]
I was under the impression that `intel_gpu_top` continuously prints data every second (`-s 1000`) until you interrupt it (CTRL-C). You said "I grabbed the last entry" - asking for all entries.

**Comment by bluej007** [comment]
Gotcha. Do you want 10 seconds of output or longer?

**Comment by ilyam8** [comment]
5 is ok

**Comment by Moorsy-AU** [comment]
100% would love this, I know my igpu is working via Plex (hw) during transcodes, I'd love to be able to see stat's during remote users sessions see how it's handling. I'm no coder by any means but if windows can do it id assume anyone can... :)

**Comment by ilyam8** [comment]
A note: I see that `intel_gpu_top` works only:

- under root or
- with CAP_PERFMON when running as a normal user

I think it should work if we add `cap_perfmon=+ep` to the plugin that will use `intel_gpu_top` but I'm not 100% sure.

**Comment by ilyam8** [comment]
@bluej007, hey. Did you [remove the comma after the last sample](https://github.com/netdata/netdata/issues/14931#issuecomment-2032965797)?

Does it work like this?

```bash
{
  data ... 
},
# wait for refresh period (-s)...
{
  data ... 
},
# wait for refresh period (-s)...
{
  data ... 
},
```

I'm asking because your last sample doesn't have a comma.

**Comment by bluej007** [comment]
> @bluej007, hey. Did you [remove the comma after the last sample](https://github.com/netdata/netdata/issues/14931#issuecomment-2032965797)?
> 
> Does it work like this?
> 
> ```shell
> {
>   data ... 
> },
> # wait for refresh period (-s)...
> {
>   data ... 
> },
> # wait for refresh period (-s)...
> {
>   data ... 
> },
> ```
> 
> I'm asking because your last sample doesn't have a comma.

No, I didn't remove a comma from the end. When I cancel the command, the last line looks like this:
```
}^C<user>@<system>:~$
```

**Comment by ilyam8** [comment]
Guys, I added an initial version in #17344 - it will be available in the next nightly release (tomorrow ). I don't have access to hardware with Intel integrated GPU, so I need your help to test it.

- **configure data collection job**

```bash
cd /etc/netdata/netdata
# copy go.d/intelgpu.conf and uncomment the job
sudo ./edit-config go.d/intelgpu.conf
```

Should look like this

```bash
$ cat go.d/intelgpu.conf
## All available configuration options, their descriptions and default values:
## https://github.com/netdata/netdata/tree/master/src/go/collectors/go.d.plugin/modules/intelgpu#readme

jobs:
  - name: intelgpu
    binary_path: /usr/bin/intel_gpu_top
```

- **Run the collector from your terminal as `root` user**

As `root` user because we want to test just using the `intel_gpu_top` binary and parsing its output

```bash
/usr/libexec/netdata/plugins.d/go.d.plugin -m intelgpu
```




- **If previous step worked: add PERFMON to go.d.plugin, check the charts** 


```bash
sudo systemctl stop netdata
sudo setcap cap_dac_read_search,cap_net_admin,cap_perfmon,cap_net_raw=eip /usr/libexec/netdata/plugins.d/go.d.plugin
sudo systemctl start netdata
```

If all is good you will see the `intelgpu` section on the dashboard.

---

I'll enable the collector and add PERFMON if the ^^ tests pass.

**Comment by ilyam8** [comment]
> If the previous step worked: add PERFMON to go.d.plugin

This does not work, unfortunately. Capabilities apply only to a specific executable file. They are not automatically inherited by other executables that the main executable may call.

So you need to add PERFMON to `intel_gpu_top`.

```bash
sudo setcap cap_perfmon=eip /usr/bin/intel_gpu_top
```

**Comment by bluej007** [comment]
> > If the previous step worked: add PERFMON to go.d.plugin
> 
> This does not work, unfortunately. Capabilities apply only to a specific executable file. They are not automatically inherited by other executables that the main executable may call.
> 
> So you need to add PERFMON to `intel_gpu_top`.
> 
> ```shell
> sudo setcap cap_perfmon=eip /usr/bin/intel_gpu_top
> ```

When I run /usr/libexec/netdata/plugins.d/go.d.plugin -m intelgpu, I'm only seeing the below. If my netdata runs in a container, are there different steps I need to take to enable the correct cap settings for perfmon?

```shell
INF env HTTP_PROXY '', HTTPS_PROXY '' component=agent
INF instance is started component=agent
INF loading config file component=agent
INF found '/usr/lib/netdata/conf.d/go.d.conf component=agent
INF config successfully loaded component=agent
INF using config: enabled 'true', default_run 'true', max_procs '0' component=agent
INF loading modules component=agent
INF enabled/registered modules: 1/78 component=agent
INF building discovery config component=agent
INF dummy/read/watch paths: 0/1/0 component=agent
INF registered discoverers: [file discovery: [file reader] service discovery] component="discovery manager"
INF found '/usr/lib/netdata/conf.d/vnodes' (0 vhosts) component=agent
INF instance is started component="discovery manager"
INF instance is started component="functions manager"
INF instance is started component="job manager"
CONFIG go.d:collector:intelgpu create accepted template /collectors/jobs internal 'internal' 'add schema enable disable test' 0x0000 0x0000

INF instance is started component="service discovery"
INF instance is started component=discovery discoverer=file
INF instance is started component=discovery discoverer=file
WRN parse '/etc/netdata/go.d/intelgpu.conf': unknown file format: '/etc/netdata/go.d/intelgpu.conf' component=discovery discoverer=file
INF instance is stopped component=discovery discoverer=file
INF instance is started component="service discovery" pipeline=docker
INF instance is started component="service discovery" discoverer=docker
INF instance is started component="service discovery" pipeline="network listeners"
INF instance is started component="service discovery" discoverer=net_listeners
```
