### ISSUE TITLE
[Bug]: ML seems to be training very slowly

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#14946]
### Bug description

We have 2 parent servers, each collecting 1.3M metrics per second.

At the Netdata Monitoring section, at the ML Training workers section, we see that:

1. There are 4 threads, all of which are 100% busy.
2. CPU utilization on these 4 threads is only 2.5%.
3. `load models` is using 3950 ms on the average (cap is 4000 ms for 4 threads).
4. Training proceeds with just 15 jobs per second.

So, to train 1.3M dimensions, the time needed is `1.3M / 15 = 86666 seconds`, that is, a little more than a day!

On another server with 150k metrics per second, ML has a slightly different behavior, but still very slow:

1. 4 threads, 10% busy.
2. CPU utilization is 10% on the average.
3. `load models` is using 1/4th of time of `kmeans`, although there are rare spikes of a few seconds that it uses all the time.
4. Training proceeds with just 4 jobs per second.

Again very slow. About half a day to train a model for all the metrics.

### Expected behavior

Training should fully utilize the cpu of the 4 threads, to train all as many of the metrics within an hour (the default configuration is to train every metric, every hour).

### Steps to reproduce

Just sit and observe...

### Installation method

from source

### System info

```shell
Linux lab-nd-dev-parent1 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.38.0-415-ge53497568
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -g -Wall -Wextra -Wformat-signedness -Wformat-truncation=2 -Wunused-result -fno-omit-frame-pointer -DMAX_DATAFILE_SIZE=104857600LU' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

cc: @vkalintiris

**Comment by ktsaou** [comment]
One of the 2 nodes with 1.3M metrics per second:

![image](https://user-images.githubusercontent.com/2662304/233746592-e5ef8308-e9e1-434c-8a12-a262fc7ef19d.png)

**Comment by ktsaou** [comment]
One node that collects 150k metrics per second:

![image](https://user-images.githubusercontent.com/2662304/233746732-d7d687d1-6b2e-46e3-993a-7da15f0561a6.png)

**Comment by ktsaou** [comment]
And this is my laptop (note that `pop queue` is now using all the time):

![image](https://user-images.githubusercontent.com/2662304/233746876-709d227a-4156-4dac-a5bb-98be58a1197e.png)

**Comment by ktsaou** [comment]
And this is my desktop (again `pop queue` is using most time):

![image](https://user-images.githubusercontent.com/2662304/233747117-eba440fa-9c5a-4a43-9c71-e4a8d5d5365c.png)

**Comment by andrewm4894** [comment]
I believe we had an earlier approach that tried to get through as many models that need training as soon as possible but we then decided that in more typical scenarios we should take advantage of having a full training window across which to spread the cpu cost. So trading off an initial peak and dip for a more amortized approach that tries to spread it out.

Thats my understanding but Vasillis obviously knows more the details. 

Wonder if might be that sometimes a user might want "eager" training while other times maybe a user might want "lazy" training so wonder if could potentially be another config param?

One thing that i think will change is the default training every hour - there really is not any need (world does not change that much hour to hour) - am hoping to move defaults to be [something more like this](https://github.com/netdata/netdata/pull/14222) once all the DB and model persistence work done. Just in case of relevance here.

**Comment by vkalintiris** [comment]
@ktsaou

1. Interpret busy time of `pop queue` as idle time, there's a condition variable that waits for new work to arrive in the thread's training queue, I should set the worker as idle to reflect that. 
2. The real culprit is the sqlite statements we are executing to load/save/delete models. We'll have to use the metadata thread instead of doing these operations within a training thread (and ideally, only once when a dimension is created/deleted).

Managed to notice the same results you shared by spawning a parent with ~100 children.

**Comment by vkalintiris** [comment]
Fixed: https://github.com/netdata/netdata/pull/14981.
