### ISSUE TITLE
[Bug]: ML is crashing

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#14941]
### Bug description

![image](https://user-images.githubusercontent.com/2662304/233590053-c9688377-f471-49b0-aee4-b9448544b909.png)

### Expected behavior

Not crash

### Steps to reproduce

Happens on a parent, during the night, I believe due to children being updated and restarted.

### Installation method

from source

### System info

```shell
Linux costa-desktop 6.1.25-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Apr 20 13:48:36 UTC 2023 x86_64 GNU/Linux
/etc/arch-release:Manjaro Linux
/etc/lsb-release:DISTRIB_ID=ManjaroLinux
/etc/lsb-release:DISTRIB_RELEASE=22.1.0
/etc/lsb-release:DISTRIB_CODENAME=Talos
/etc/lsb-release:DISTRIB_DESCRIPTION="Manjaro Linux"
/etc/manjaro-release:Manjaro Linux
/etc/os-release:NAME="Manjaro Linux"
/etc/os-release:PRETTY_NAME="Manjaro Linux"
/etc/os-release:ID=manjaro
/etc/os-release:ID_LIKE=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="32;1;24;144;200"
/etc/os-release:LOGO=manjarolinux
```

### Netdata build info

```shell
Version: netdata v1.38.0-409-gc3d70ffcb
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=costa' '--with-bundled-protobuf' 'CFLAGS=-O0 -g -Wall -Wextra -Wformat -Wformat-signedness -Wunused-result -fno-omit-frame-pointer -Wunused-result -DNETDATA_DEV_MODE=1 -DFSANITIZE_ADDRESS=1' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

cc @vkalintiris

**Comment by vkalintiris** [comment]
@ktsaou Unless I'm missing something, I don't think this is related to ML. Everything that happens within `ml_acquired_dimension_train` operates on an _acquired_ dimension, ie. the dimension's gets freed while we've acquired it, which should not happen, AFAICT.

- Before `ml_acquired_dimension_train`, we are looking up & acquiring the `RRDDIM`:
```
    // in ml_acquired_dimension_get()
    // ...
    RRDHOST *rh = rrdhost_find_by_hostname(string2str(host_id));
    if (rh) {
        RRDSET *rs = rrdset_find(rh, string2str(chart_id));
        if (rs) {
            acq_rd = rrddim_find_and_acquire(rs, string2str(dimension_id));
            if (acq_rd) {
                RRDDIM *rd = rrddim_acquired_to_rrddim(acq_rd);
```

- Within `ml_acquired_dimension_train()` we are accessing the necessary fields of `RRDDIM` (crash happens here).

- After `ml_acquired_dimension_train`, we simply release the `RRDDIM`:
```
   // in ml_acquired_dimension_release()
   // ...
   rrddim_acquired_release(acq_dim.acq_rd);
```

FWIW, I could not reproduce this locally with a big number of connecting/disconnecting children and with the two host/chart cleaning up options set to `1s` (overriden by hard-coding the value in the parent agent's source code).

**Comment by ktsaou** [comment]
Yes, this is the interesting part.

The dimension has been deleted, but because it was acquired it was not be freed.
But the chart was not acquired and was deleted and freed...

**Comment by ktsaou** [comment]
So, I think we should provide an `rrdset_find_and_acquire()`.

**Comment by vkalintiris** [comment]
> So, I think we should provide an `rrdset_find_and_acquire()`.

Created https://github.com/netdata/netdata/pull/14945, but I don't have any way to verify it resolves the issue because I can't reproduce it on my end.
