### ISSUE TITLE
[Bug]: claiming script failed with exit code 7

### ISSUE THREAD

**Issue by Rexator3000** [netdata/netdata#14989]
### Bug description

Base URL: https://app.netdata.cloud
Id: 4674502e-e484-11ed-b037-005056902263
Rooms:
Hostname: premair
Proxy:
Netdata user: netdata
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 1 failed. Retry in 1s.
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 2 failed. Retry in 2s.
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 3 failed. Retry in 3s.
grep: /opt/netdata/var/lib/netdata/cloud.d/tmpout.txt: No such file or directory
grep: /opt/netdata/var/lib/netdata/cloud.d/tmpout.txt: No such file or directory
**Failed to claim node with the following error message:"Unknown HTTP error message"**

The following non-fatal warnings or errors were encountered:

  - Command "/opt/netdata/bin/netdata-claim.sh -token=fJIvrD6vwUy0JD7k_49y8YIJ1GYe1_HCCrt4wCB5dkW2wsZ44YzDY0F4wE7uRsXpyZUJXo5fjFXkn-StrQS5oYT2sszAMS3dMWqylO5YxgchzvtzM5jTqV2-nV4uhyuVeoTTn1U -rooms= -url=https://app.netdata.cloud" failed with exit code 7.

### Expected behavior

I expected agent to install successfully

### Steps to reproduce

1.
2.
3.
...

### Installation method

kickstart.sh

### System info

```shell
Linux premair 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="9"
/etc/os-release:VERSION="9 (stretch)"
/etc/os-release:VERSION_CODENAME=stretch
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.38.0-450-g2d678553f
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -I/libnetfilter-acct-static/include/libnetfilter_acct -I/usr/include/libmnl -pipe' 'LDFLAGS=-static -L/openssl-static/lib -L/libnetfilter-acct-static/lib -lnetfilter_acct -L/usr/lib -lmnl' 'PKG_CONFIG=pkg-config --static' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig:/libnetfilter-acct-static/lib/pkgconfig:/usr/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by Rexator3000** [comment]
The following non-fatal warnings or errors were encountered:

  - Command "/opt/netdata/bin/netdata-claim.sh -token=fJIvrD6vwUy0JD7k_49y8YIJ1GYe1_HCCrt4wCB5dkW2wsZ44YzDY0F4wE7uRsXpyZUJXo5fjFXkn-StrQS5oYT2sszAMS3dMWqylO5YxgchzvtzM5jTqV2-nV4uhyuVeoTTn1U -rooms= -url=https://app.netdata.cloud" failed with exit code 7.

**Comment by Rexator3000** [comment]
status netdata:

Apr 30 17:00:16 premair [1288]: Loaded config file '/opt/netdata/usr/lib/netdata/conf.d/apps_groups.conf'
Apr 30 17:00:16 premair [1288]: started on pid 1288
Apr 30 17:00:16 premair [1288]: set name of thread 1341 to APPS_READER
Apr 30 17:00:16 premair [1291]: Does not have a configuration file inside `/opt/netdata/etc/netdata/ebpf.d.conf. It will try to load stock file.
Apr 30 17:00:16 premair [1291]: Your environment does not have BTF file /sys/kernel/btf//vmlinux. The plugin will work with 'legacy' code.
Apr 30 17:00:16 premair [1291]: Cannot read process groups configuration file '/opt/netdata/etc/netdata/apps_groups.conf'. Will try '/opt/netdata/usr/lib/netdata/conf.d/apps_groups.conf'
Apr 30 17:00:16 premair [1291]: The current collector cannot run on this kernel.
Apr 30 17:00:17 premair [1288]: Using now_boottime_usec() for uptime (dt is 2 ms)
Apr 30 17:00:46 premair [1282]: heartbeat clock: woke up 866810 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
Apr 30 17:00:46 premair [1288]: heartbeat clock: woke up 866836 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).

**Comment by MrZammler** [comment]
Hi @Rexator3000 

The error `return code 60` likely refers to an SSL cerfiticate issue. Can you check on your environment that you have the latest `ca-certificates` ?

But in general Debian 9 has been EOL'ed since June 2022...

**Comment by MrZammler** [comment]
Closing this since it's been a while. @Rexator3000 do let us know with a new issue if the problem persists.
