### ISSUE TITLE
[Feat]: Move claiming process into core agent.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#15019]
### Problem

The current claiming process involves a number of external tools invoked through a script, and is largely decoupled from the agent itself.

This leads to a number of issues with claiming:

- It’s easily possible for an agent to be ‘claimed’ but never actually connect to the Cloud. For example, a k8s pod configured to claim on startup spinning up but getting killed before the agent itself can connect to the Cloud.
- Cloud support has additional, non-obvious, dependencies due to using a script for the claiming process.
- It’s very difficult to prepare a system image that connects to the Cloud on startup, because you need to manually set up a one-shot startup script to claim the node.

### Description

Given that we already have essentially everything we need for the claiming process built into the agent itself, we should update the claiming process to work as follows:

- The claiming script writes out the claiming parameters to some ‘well-known’ location and exits.
- On startup, the agent checks that location, and if claim parameters are present and the agent is not claimed, the agent uses those parameters to claim itself and then immediately connect to the Cloud.

### Importance

must have

### Value proposition

1. The possibility of a node being claimed but not connecting to the Cloud will be significantly reduced (it’s _technically_ still possible even if we do this, but the probability of it happening will be _significantly_ lower).
2. Cloud support will be less dependent on what tools are installed on the system.
3. It will become trivial to set up a system image with the agent that will be claimed on startup of the image.
4. Long-term, installer and packaging code surrounding the claiming process can be made _exponentially_ simpler.

---

Based on discussion with @cakrit, @ralphm, @ktsaou, and @papazach.

**Comment by ilyam8** [comment]
This is done.
