### ISSUE TITLE
[Bug]: Systemd services monitoring not working in official docker image

### ISSUE THREAD

**Issue by jeffka11** [netdata/netdata#15022]
### Bug description

I'm getting the following error in my logs. As a result, I don't see systemd services on the default dashboard.

> [ DEBUG ] build[manager] build.go:164 received config group ('/etc/Netdata/go.d/systemdunits.conf'): 2 jobs (added: 2, removed: 0)
[ DEBUG ] build[manager] build.go:313 building systemdunits[service-units] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/systemdunits.conf autodetection_retry:0 include:[*.service] module:systemdunits name:service-units priority:70000 update_every:10]
[ DEBUG ] systemdunits[service-units] systemdunits.go:74 unit names patterns: [*.service]
[ DEBUG ] systemdunits[service-units] systemdunits.go:75 timeout: 2s
**[ ERROR ] systemdunits[service-units] systemdunits.go:90 error on creating a connection: read unix @->/run/dbus/system_bus_socket: recvmsg: connection reset by peer
[ ERROR ] systemdunits[service-units] job.go:205 check failed**

### Expected behavior

I see systemd information on the dashboard and no errors in the logs

### Steps to reproduce

1. Use the latest image. I trimmed some personal and unrelated stuff from the docker-compose below, it should show that I'm mounting all the bind mounts per [the docs](https://learn.netdata.cloud/docs/installation/installation-methods/docker).
2. tail the logs to find the message in the description.

Below is my docker-compose.yml

    netdata:
        pid: host
        image: netdata/netdata:latest
        hostname: milkyway

    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - NET_RAW

    security_opt:
      - "apparmor:unconfined"

    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
      replicas: 1

    networks:
      - 'proxy'
      - 'netdata_default'

    volumes:
      - type: volume
        source: netdata_cache
        target: /var/cache/netdata

      - type: volume
        source: netdata_lib
        target: /var/lib/netdata

      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log/smartd:/var/log/smartd:ro

      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      - /run/systemd/private:/run/systemd/private:ro
      - /etc/hostname:/etc/hostname:ro
      - /etc/ssmtp:/etc/ssmtp:ro
      - /etc/msmtprc:/etc/msmtprc:ro
      - /etc/msmtpaliases:/etc/msmtpaliases:ro

    env_file:
      - ./.env

    volumes:
      netdata_lib:
      netdata_cache:

### Installation method

docker

### System info

```shell
Linux milkyway 6.1.0-7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1 (2023-03-19) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux bookworm/sid"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_CODENAME=bookworm
/etc/os-release:ID=debian
```

### Netdata build info

```shell
milkyway:/$ netdata -W buildinfo                                                                                                                                                              
Version: netdata v1.38.0-470-nightly                                                                                                                                                          
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bu
ndled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='                                                                                                
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
lugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

(edit here) I forgot to include my systemdunits.conf file in go.d/. That is below.

    jobs:
      - name: service-units
        include:
          - '*.service'
    
      - name: docker-compose-autostart
        include:
          - 'docker_compose_autostart*.service'

**Comment by Dim-P** [comment]
Hi @jeffka11 , I can reproduce this, we are looking into it.

**Comment by Dim-P** [comment]
@jeffka11 Can you please try mounting the whole `dbus` directory and see if that works for you:
```
volumes:
   - /var/run/dbus:/var/run/dbus:ro
```

This resolved the issue for me.

**Comment by jeffka11** [comment]
Hi @Dim-P , sorry but I'm still seeing it - same message as above.

```
jeff@milkyway /opt/docker/netdata master* ❯ docker image ls | grep netdata                                                                                                                                                          jeff@milkyway 05:11:50 PM
netdata/netdata                          latest                  6d63b0944ee8   21 hours ago    358MB
```


```
[ DEBUG ] build[manager] build.go:164 received config group ('/etc/netdata/go.d/systemdunits.conf'): 2 jobs (added: 2, removed: 0)
[ DEBUG ] build[manager] build.go:313 building systemdunits[service-units] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/systemdunits.conf autodetection_retry:0 include:[*.service] module:systemdunits name:service-units priority:70000 update_every:10]
[ DEBUG ] systemdunits[service-units] systemdunits.go:74 unit names patterns: [*.service]
[ DEBUG ] systemdunits[service-units] systemdunits.go:75 timeout: 2s
[ ERROR ] systemdunits[service-units] systemdunits.go:90 error on creating a connection: read unix @->/run/dbus/system_bus_socket: recvmsg: connection reset by peer
[ ERROR ] systemdunits[service-units] job.go:205 check failed
[ DEBUG ] build[manager] build.go:313 building systemdunits[docker-compose-autostart] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/systemdunits.conf autodetection_retry:0 include:[docker_compose_autostart*.service] module:systemdunits name:docker-compose-autostart priority:70000 update_every:10]
[ DEBUG ] systemdunits[docker-compose-autostart] systemdunits.go:74 unit names patterns: [docker_compose_autostart*.service]
[ DEBUG ] systemdunits[docker-compose-autostart] systemdunits.go:75 timeout: 2s
[ ERROR ] systemdunits[docker-compose-autostart] systemdunits.go:90 error on creating a connection: read unix @->/run/dbus/system_bus_socket: recvmsg: connection reset by peer
[ ERROR ] systemdunits[docker-compose-autostart] job.go:205 check failed

```

**Comment by ilyam8** [comment]
I googled and my findings so far:

- privileged +
- mounting /var/run/dbus/system_bus_socket

should be enough, but it doesn't work for me. I don't know how to get systemdunits working inside a container. I'll try to see if this is possible.

**Comment by Dim-P** [comment]
I tried that on Fedora but I can't see an obvious reason why it would give different results on Debian.

**Comment by ilyam8** [comment]
Hey, @jeffka11.

#15180 will fix the problem. It works for me (using image built from #15180 branch)

- mount `/run/systemd/private:/run/systemd/private:ro`
- enable systemdunits in go.d.conf
- profit!
