### ISSUE TITLE
[Bug]: go.d.plugin requires ownership change on MacOS for httpcheck functionality

### ISSUE THREAD

**Issue by mtrdoo** [netdata/netdata#15028]
### Bug description

I was unable to get the httpcheck function to work properly without changing ownership of the go.d.plugin to user 'netdata' on MacOS. Prior to this it would fail with an error similar to: "netdata ERROR : PD[go.d] : child pid 97592 exited with code 126."

Fix was `chown -u netdata go.d.plugin`

### Expected behavior

go.d.plugin should be installed with correct ownership or privileges should be changed such that it can run as previously installed. 

### Steps to reproduce

1. Enable go.d.plugin to perform some action on MacOS after fresh install & check error logs

...

### Installation method

kickstart.sh

### System info

```shell
Darwin zmike2.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a
```

### Netdata build info

```shell
Version: netdata v1.38.0-474-nightly
Configure options:  '--prefix=/usr/local/netdata/usr' '--sysconfdir=/usr/local/netdata/etc' '--localstatedir=/usr/local/netdata/var' '--libexecdir=/usr/local/netdata/usr/libexec' '--libdir=/usr/local/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    NO
    cgroup Network Tracking: NO
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by mtrdoo** [comment]
After modification: '-rwxr-x---  1 netdata  netdata'
Before modification '-rwxr-x---  1 root  netdata'

**Comment by ilyam8** [comment]
What user Netdata is running as? I see it is executable by the `netdata` group => executable by the `netdata` user.

**Comment by mtrdoo** [comment]
netdata (both netdata & go.d plugin)

**Comment by ilyam8** [comment]
That is strange, `-rwxr-x--- 1 root netdata'` is correct perm/ownership. @Ferroin any ideas?

**Comment by Ferroin** [comment]
Unfortunately no idea here, but I also don’t have a complete understanding of what permissions model macOS uses beyond the traditional UNIX DAC mechanisms.

**Comment by ilyam8** [comment]
Can't reproduce this issue, I think it was fixed at some point.
