### ISSUE TITLE
[Bug]: 'install-required-packages.sh' should not "run_as_root" for MacOS installs

### ISSUE THREAD

**Issue by mtrdoo** [netdata/netdata#15027]
### Bug description

Line 1685 of the kickstart.sh script calls 'install-required-packages.sh' as root and this causes the below behavior:

 --- Running downloaded script to install required build dependencies... --- 

Root privileges required to run /usr/local/bin/bash /var/folders/pj/l0270kmx60s45q2qqj5cwt6w0000gn/T/netdata-kickstart-XXXXXXXXXX.e5A5LJWP/install-required-packages.sh netdata

[/var/folders/pj/l0270kmx60s45q2qqj5cwt6w0000gn/T/netdata-kickstart-XXXXXXXXXX.e5A5LJWP]$ sudo /usr/local/bin/bash /var/folders/pj/l0270kmx60s45q2qqj5cwt6w0000gn/T/netdata-kickstart-XXXXXXXXXX.e5A5LJWP/install-required-packages.sh netdata 

Password:

This script does not support running as EUID 0 on macOS. Please run it as a regular user.

 FAILED 

 WARNING  Failed to install all required packages, but installation might still be possible.

### Expected behavior

kickstart.sh should understand if it is operating on MacOS & then call the script in question as the current user. 

### Steps to reproduce

1. Attempt kickstart install as directed by netdata.cloud on any Mac (curl https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh --nightly-channel --claim-token <TOKEN> --claim-url https://app.netdata.cloud)

...

### Installation method

kickstart.sh

### System info

```shell
Tried on 3 systems w/ same results:
System 1:
Darwin zmike2.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a

System 2:
Darwin mini.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64
ProductName:	macOS
ProductVersion:	12.6.5
BuildVersion:	21G531

System 3:
Darwin mbook.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a
```

### Netdata build info

```shell
From System 3:
Version: netdata v1.38.0-476-nightly
Configure options:  '--prefix=/usr/local/netdata/usr' '--sysconfdir=/usr/local/netdata/etc' '--localstatedir=/usr/local/netdata/var' '--libexecdir=/usr/local/netdata/usr/libexec' '--libdir=/usr/local/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   NO
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    NO
    cgroup Network Tracking: NO
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ChillarAnand** [comment]
Any updates on this? I am facing this issue on Mac M1.
