### ISSUE TITLE
[Bug]: Could not build rpm with contrib script

### ISSUE THREAD

**Issue by l2dy** [netdata/netdata#15033]
### Bug description

Could not build rpm with `contrib/rhel/build-netdata-rpm.sh`.

```
FAILED  Cannot find the generated SRPM file 'SOURCE_DATE_EPOCH=1679356800
/root/rpmbuild/SRPMS/netdata-v1.39.0-1.el9.src.rpm'
```

Value of the variable comes from:

```
# rpmbuild -ts netdata-v1.39.0.tar.gz 2>/dev/null
setting SOURCE_DATE_EPOCH=1679356800
Wrote: /root/rpmbuild/SRPMS/netdata-v1.39.0-1.el9.src.rpm
```

### Expected behavior

OK

### Steps to reproduce

1. Download netdata-v1.39.0.tar.gz and extract
2. Run `./contrib/rhel/build-netdata-rpm.sh`
3. Get an error.

### Installation method

from source

### System info

```shell
Linux 605be1636406 5.15.0-100.96.32.el9uek.aarch64 #2 SMP Tue Mar 28 18:07:53 PDT 2023 aarch64 aarch64 aarch64 GNU/Linux
/etc/oracle-release:Oracle Linux Server release 9.1
/etc/os-release:NAME="Oracle Linux Server"
/etc/os-release:VERSION="9.1"
/etc/os-release:ID="ol"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="9.1"
/etc/os-release:PLATFORM_ID="platform:el9"
/etc/os-release:PRETTY_NAME="Oracle Linux Server 9.1"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:oracle:linux:9:1:server"
/etc/os-release:
/etc/os-release:ORACLE_BUGZILLA_PRODUCT="Oracle Linux 9"
/etc/os-release:ORACLE_BUGZILLA_PRODUCT_VERSION=9.1
/etc/os-release:ORACLE_SUPPORT_PRODUCT="Oracle Linux"
/etc/os-release:ORACLE_SUPPORT_PRODUCT_VERSION=9.1
/etc/redhat-release:Red Hat Enterprise Linux release 9.1 (Plow)
/etc/system-release:Oracle Linux Server release 9.1
```

### Netdata build info

```shell
N/A
```

**Comment by Ferroin** [comment]
I’m honestly not actually sure why the script is still around, and am kind of surprised that it’s been working at all over the past few months.

The current recommended method for building native DEB or RPM packages of Netdata locally is documented [here](https://github.com/netdata/netdata/blob/master/packaging/building-native-packages-locally.md).

**Comment by ilyam8** [comment]
> The current recommended method for building native DEB or RPM packages

@Ferroin we need to update (or remove?) https://github.com/netdata/netdata/blob/master/contrib/README.md

**Comment by Ferroin** [comment]
I think we need to just reevaluate the entire contrib directory. I’m not sure the rhel stuff is useful anymore, and the debian directory should ideally be in the root of the source tree (IOW, where it needs to be when actually building the packages).

**Comment by ilyam8** [comment]
`build-netdata-rpm.sh` removed in #16672
