### ISSUE TITLE
[Bug]: claiming fails when installing static version (kickstart.sh) as a regular user 

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#15036]
### Bug description

Claiming fails when:
 - installing static version
 - as a regular user (not root)

with the following error:

```bash
 --- Attempting to claim agent to https://api.netdata.cloud ---
 ABORTED  /opt/netdata/bin/netdata-claim.sh does not exist.
```

The file exists but these checks fail:

https://github.com/netdata/netdata/blob/385fbb3a36ba908a36682c7d7c8d68f353b5c19c/packaging/installer/kickstart.sh#L1142-L1147

because a regular user has no read permissions (can't see the contents of the directory).

The dir permissions:

```bash
$ ls -l /opt/ | grep netdata
drwx------ 10 netdata netdata 4096 May  9 21:55 netdata
```

### Expected behavior

The claiming script is executed.

### Steps to reproduce

1. run `./kickstart.sh --static-only --claim-token TOKEN`

### Installation method

kickstart.sh

### System info

```shell
n/a
```

### Netdata build info

```shell
netdata v1.39.0-6-g385fbb3a3
```

**Comment by ilyam8** [comment]
Should `/opt/netdata` be 755? If so the fix is just add a line here

https://github.com/netdata/netdata/blob/385fbb3a36ba908a36682c7d7c8d68f353b5c19c/packaging/makeself/install-or-update.sh#L204-L207

**Comment by Ferroin** [comment]
That was probably the intent actually.

**Comment by ilyam8** [comment]
The same problem with enabling auto-updates

https://github.com/netdata/netdata/blob/385fbb3a36ba908a36682c7d7c8d68f353b5c19c/packaging/installer/kickstart.sh#L1194-L1199

**Comment by Ferroin** [comment]
OK, it’s actually more complicated to fix this than it initially seems, as we appear to have bad permissions on _all_ of our directories...

**Comment by ktsaou** [comment]
How did a non-root user created `/opt/netdata` ?

Debian, Arch:

```sh
# ls -ld /opt
drwxr-xr-x 4 root root 4096 Nov 19 18:40 /opt
```

**Comment by Ferroin** [comment]
> How is it possible for a non-root user to create `/opt/netdata` ?
> 
> Debian, Arch:
> 
> ```shell
> # ls -ld /opt
> drwxr-xr-x 4 root root 4096 Nov 19 18:40 /opt
> ```
> 
> So, netdata was installed as root.
> 
> If the installer run as root, then why it cannot also execute claiming while it is root?

Because only the extraction runs as root, not the whole kickstart script. We make a point of only elevating privileges when we actually need to do so.
