### ISSUE TITLE
[Feat]: Deprecate `family` attribute on the alerts domain 

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#15030]
### Problem

There is the need to deprecate the `family` attribute across Netdata. The alerts domain uses this in a couple of places:
* filter on `families` for alert configurations, e.g. [net.conf example](https://github.com/netdata/netdata/blob/ffe063bfe47e9b5e6244e2e4807ccdebc26afadf/health/health.d/net.conf#L90-L105) or [mdstat.conf example](https://github.com/netdata/netdata/blob/ffe063bfe47e9b5e6244e2e4807ccdebc26afadf/health/health.d/mdstat.conf#L27-L39)
* Review the Health API on Agent to allow actions using labels and remove family
* Replace the `family` with labels on our alert notification templates
* Update alert config and Health API documentation

### Description

As a detailed ticket focus on agent work linked to https://github.com/netdata/product/issues/3118, move from a dependency on the `family` attribute into specific chart `labels`

See details above

### Importance

must have

### Value proposition

Have the chart labels as driving of multiple features and functionality across Netdata.

**Comment by ilyam8** [comment]
@hugovalente-pm 

- [chart labels](https://learn.netdata.cloud/docs/alerts-and-notifications/health-configuration-reference#alarm-line-chart-labels) added.
- our stock alerts no longer use the `family` filter.

**Comment by MrZammler** [comment]
Closing this, should be ok since https://github.com/netdata/netdata/pull/16025
