### ISSUE TITLE
[Feat]: Lightweight agent version

### ISSUE THREAD

**Issue by Dim-P** [netdata/netdata#15037]
### Problem

The agent installation disk space requirements have grown too big (>150MB for static installs) and are prohibitive for certain use cases, such as when [attempting to install it on low-spec routers](https://github.com/netdata/netdata/pull/14994#discussion_r1183239926) or other embedded Linux / *BSD systems.

### Description

There needs to be a lightweight version of the agent, where only absolutely core features are enabled.

Some suggestions up for discussion about what can be stripped off:

- eBPF plugin
- Go plugin
- Python plugins
- Cloud support
- ML
- Local dashboard
- Disabled `dbengine`
- Unnecessary linking to libraries

For comparison, [OpenWrt's Netdata package](https://github.com/openwrt/packages/tree/master/admin/netdata) is only 7785kB big (albeit it is a much older version, `v1.33.1`). 

### Importance

really want

### Value proposition

1. Wider range of supported hardware, as it will be possible to install Netdata on more resource-constrained devices.  
2. Easier support and maintenance of Netdata packages by 3rd-party maintainers. 
3. Out-of-the-box reduced resource usage (not only disk space, but CPU, RAM, I/O as well) for users who don't need a full-fledged version.

**Comment by ilyam8** [comment]
@Dim-P, hey. Do you suggest we building/publishing some lightweight agent version? I am asking because I believe it is already possible to build a lightweight agent version using configure/install options.

We don't really know why OpenWrt guys stopped updating the Netdata package - due to packaging problems (can't build Netdata w/o X and X is too big) or just because there is no person interested in that.

**Comment by ilyam8** [comment]
And I think the lightweight part And I think the easy part only refers to the total size on the disk, right? Because almost all the components can be disabled/memory mode can be changed.

**Comment by Dim-P** [comment]
> Do you suggest we building/publishing some lightweight agent version?

I am suggesting to start publishing a distributable version of the agent which is more lightweight than the current one, so that people don't have to (cross-)compile it themselves, particularly for constrained environments where local builds is not an option (and cross-compiling requires additional work). Probably through static builds, for example it could be a new option like: 
```
./kickstart.sh --static-only-lightweight
```

> And I think the lightweight part only refers to the total size on the disk, right? Because almost all the components can be disabled/memory mode can be changed.

Primarily, but it would provide additional benefits, such as reduce resource usage out-of-the-box, for users who cannot / don't want to dive into what components are resource-hungry, see value prop points.

> If so, I think we need to narrow down the use case, because "lightweight" for one person can be just "base", for another person "base + X" (still lightweight!). And we would have to hardcode included features/components.

I agree, thus why this ticket.

**Comment by Ferroin** [comment]
My suggestion would be to look at the linking thing first. That will have benefits for _all_ users, not just lightweight installs, and while it’s far from the easiest thing to fix, it’s something we have had complaints about before.

**Comment by ilyam8** [comment]
I think this issue has served its purpose (discussion), closing.
