### ISSUE TITLE
[Bug]: nvidia-smi plugin not working with multiple GPUs

### ISSUE THREAD

**Issue by denbonte** [netdata/netdata#15057]
### Bug description

Thanks for the fantastic work on everything Netdata. I have been using it for years now, and I have been loving it.

I work at a computational research lab, and I used to do most of the sysadmin on several nodes for a number of fellow researchers. We have various nodes equipped with single GPUs, but most of them have multiple GPUs (e.g., 2x or 4x TITAN RTX, A6000, RTX8000, and so on). For a few months now, on those nodes, Netdata has struggled to retrieve information on GPU usage. In some cases, the agent manages to retrieve information, but in the dashboard, it shows up as a single GPU:

<img width="183" alt="image" src="https://github.com/netdata/netdata/assets/31729248/1b87ef8f-5d0d-495b-979b-b7162c410167">

In some other cases, however, the `nvidia-smi` plug-in doesn't appear on the dashboard. All of the nodes report no issues, are configured following the [NVidia GPU collector configuration guide](https://learn.netdata.cloud/docs/data-collection/monitor-anything/hardware/nvidia_smi-python.d.plugin), and run Netdata `v1.39.0-23-nightly`. Running the [troubleshooting procedure](https://learn.netdata.cloud/docs/data-collection/monitor-anything/hardware/nvidia#troubleshooting) on all of the nodes (i.e., the ones where only a GPU shows up and the ones where the `nvidia-smi` tab is missing in the dashboard) returns outputs that make total sense (i.e., I can see it's picking up information relative to everything that should be monitored, on all of the GPUs).

I've waited for so much to open this issue because I was pretty convinced this was a one-off, or maybe due to a particular driver version messing something up in the data collection phase (although I know that's done through `nvidia-smi`, and that has always been working on the nodes).

### Expected behavior

When a node has multiple GPUs and the `nvidia-smi` plug-in is enabled, Netdata should collect and display information regarding the different GPUs running on the system.

### Steps to reproduce

1. Update Netdata to the latest client and enable the `nvidia-smi` plugin by running
```
cd /etc/netdata  
sudo ./edit-config python.d.conf
```
2. Run Netdata on a node with multiple GPUs
3. Check the Dashboard

### Installation method

kickstart.sh

### System info

```shell
Linux W2-S1 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.5 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.5 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.39.0-30-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

I didn't see any problems running the debugger:

```
netdata@nodeXYZ:/usr/libexec/netdata/plugins.d$ ./go.d.plugin -d -m nvidia_smi

```

**Comment by moliqingwa** [comment]
+1

**Comment by moliqingwa** [comment]
I use this docker `d34dc3n73r/netdata-glibc` and it seems ok

**Comment by denbonte** [comment]
Hey @moliqingwa,

> I use this docker d34dc3n73r/netdata-glibc and it seems ok

Thanks! Maybe this can help the devs narrow down what the issue is.

However, unfortunately, on some nodes Docker is not an option for us!

**Comment by denbonte** [comment]
Hey @ilyam8,

> Are you referring to the Cloud dashboard?

Yes! Apologies if I opened the issue in the wrong place 😕

**Comment by Dim-P** [comment]
@denbonte Apologies for the delay in getting back to you, the collector seems to be working fine based on some internal testing we did, but that's only with a single GPU. 

However, I think we know what's causing the problem and it's related to how metrics are grouped using families. Can you please check if the issue persists when you use your local dashboard?

**Comment by Dim-P** [comment]
@denbonte Do you happen to have an update on this? Does it work properly when using the local dashboard?

**Comment by denbonte** [comment]
Hey @Dim-P,

> Can you please check if the issue persists when you use your local dashboard? 

So sorry I didn't get back to you sooner - I checked the local dashboard after you posted the previous message, but I forgot to update you here.

> However, I think we know what's causing the problem and it's related to how metrics are grouped using families.

The nvidia collector does not show up in the **local** dashboard at all. 

Not sure if this information helps. I'm more than happy to help you debug this, if you have any further questions!

**Comment by Dim-P** [comment]
> Hey @Dim-P,
> 
> > Can you please check if the issue persists when you use your local dashboard?
> 
> So sorry I didn't get back to you sooner - I checked the local dashboard after you posted the previous message, but I forgot to update you here.
> 
> > However, I think we know what's causing the problem and it's related to how metrics are grouped using families.
> 
> The nvidia collector does not show up in the **local** dashboard at all.
> 
> Not sure if this information helps. I'm more than happy to help you debug this, if you have any further questions!

Thanks for the update. Not sure what's wrong to be honest, as we can't seem to be able to reproduce the issue and from your description, the plugin seems to be working fine.

@ilyam8 Do you have any ideas on what could be going wrong here?

**Comment by vtone-tkay** [comment]
I think the issue is that in (latest version I could check) 1.33.1-1 nvidia_smi  enumerated the GPU and had 1 set of stats per GPU:
```
nvidia-smi
   gpu0 T4
   gpu1 RTX 2070 Super
   gpu2 GTX 1080Ti
   gpu3 P100
```
etc. From 1.41 onwards the section for the same host may have:
```
nvidia-smi
   gpu3 P100 
   gpu2 GTX 1080Ti
```
or may show 
```
nvidia-smi
  gpu1 RTX 2070 Super
  gpu[x] P100
```
or even
```
nvidia-smi
   gpu[x]
   gpu[x] RTX 2070 Super
   fan speed
   gpu utilization
   clocks
```

The CHART output from the go plugin looks OK and, aside from the final block above, it is possible to view the data in charts via group by instance but (eg) the sum of clock speeds of the 4 discrete GPU is not a useful view.
