### ISSUE TITLE
[Feat]: OpenSSF Best Practices Silver and Gold badges

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#15069]
### Problem

Try to achieve silver and if possible gold badges at https://bestpractices.coreinfrastructure.org/en/projects/2231

I'm filling in what I can, some areas need to be filled in by others, which I'll mention here. 
Other areas require work for the criteria to be met, trying to also identify those

### Basics
- [x] **Project oversight - Governance model** : We need a short document from @ktsaou. Perhaps something based on https://docs.google.com/document/d/1neg9ICnJzm5jMCLT7CRnDA8MSoYo9T7DII5y31qKtJs/
- [x] **Accessibility and internationalization** : Both are "SHOULD", I expect we will continue to leave them unmet @ktsaou 

### Quality
- [ ] **Working build system and Installation System** : @Ferroin / @tkatsoulas I completed what I could, but I'm not sure about the rest. Please check and update.
- [ ] **Automated test suite** : @ktsaou we can't realistically expect to meet these criteria any time soon, I see one of the 3 as possible.
- [ ] **New functionality testing** : @ktsaou This might be feasible, with some investment in automated testing. It specifically mentions "Major" changes, where we already do a lot of tests, but adding them to an automated test suite is a few more steps.

### Security
- [ ] **Use basic good cryptographic practices** : HTTP off by default is unmet by design @ktsaou. I'm not 100% sure about the certificate validation before sending HTTP headers, but set it to met. 
- [ ] **Secure release** : @Ferroin I don't understand how I can check whether we cryptographically sign the  release tags, you should be able to answer the two questions here.
- [ ] **Other security issues** : @stelfrag I'm not aware of the "hardening mechanisms" mentioned in the 2nd question. @ktsaou for the third question I don't know if the security design is enough. Sounds like something the security auditors could help with. 

### Basics
- [ ] **Other** : We have the license statement in each source file, but not the copyright statement. Should be easy to add the copyright statement as well @stelfrag 

### Change control
- [ ] **Public version-controlled source repository** : The last criterion requires a company policy that forbids Github 2FA via SMS. @ktsaou can decide to announce this policy, but I see no way of enforcing it, given that Github just says  "Two-factor security enabled", without any more details. 

### Quality
- [ ] **Coding standards** : @stelfrag I'm almost certain we have some info on code review requirements somewhere, but I don't know where. It may have been an internal document only, that I can't find. We could write something based on https://docs.google.com/document/d/1neg9ICnJzm5jMCLT7CRnDA8MSoYo9T7DII5y31qKtJs perhaps, but it should be a new markdown document on our repo. 
- [ ] **Working build system** : @Ferroin / @tkatsoulas I believe our builds are reproducible, but  we need the detailed justification. 
- [ ] **Automated test suites** : @ktsaou even more stringent requirements than for the silver badge here, the implemented unit tests are too trivial to consider any of the criteria met. 

### Security
- [ ] **Other security issues** : @ktsaou one question requires a security review, which we're getting. @stelfrag the other question is again about the hardening mechanisms (see silver)

### Analysis
- [ ] **Dynamic code analysis** : @ktsaou / @stelfrag a [fuzzer](https://github.com/netdata/netdata/blob/master/tests/api/fuzzer.py) was built 4 years ago, but I don't know how well it worked and of course it hasn't been updated. 

### Importance

really want

### Value proposition

Increase user confidence in the quality and security of the Netdata agent.

**Comment by Ferroin** [comment]
> @Ferroin I don't understand how I can check whether we cryptographically sign the  release tags, you should be able to answer the two questions here.

We don’t do cryptograhpic signing of release tags. The only release signing we have currently is signing of native DEB/RPM packages.

> @stelfrag I'm not aware of the "hardening mechanisms" mentioned in the 2nd question. 

For the agent code, this is mostly stuff like stack-smashing protection, `-D_FORTIFY_SOURCE` (needs special handling on non-glibc systems). I’ve been planning to look into enforcing a number of these for some time now, it’s just never been an exceptionally high priority. That said, _most_ of our pre-built packages include these options by default anyway, because the toolchains being used enable them by default.

For the cloud and the dashboard, this is stuff like https://github.com/netdata/infra/issues/1516 or https://github.com/netdata/infra/issues/1515.

> @Ferroin / @tkatsoulas I believe our builds are reproducible, but we need the detailed justification.

They are not currently reproducible AFAIK. Some parts of this are relatively easy, some are not, but we’re missing a lot of the required aspects.

**Comment by ilyam8** [comment]
I'm closing because it doesn't look like there is/will be any work on this topic. Please reopen if you plan to work on it.
