### ISSUE TITLE
[Bug]: prometheus_remote_writer not working in windows operating system

### ISSUE THREAD

**Issue by devopsusr-tech** [netdata/netdata#15077]
### Bug description

I have a prometheus server running and trying to write some data on it via netdata. There is one linux and one windows server. When configuring _prometheus_remote_write_ on Linux it successfully sends the data to prometheus but the Windows not. Both servers use the identical config

```
[prometheus_remote_write:https:my_instance]
enabled = yes
destination = hostname:443
username = username
password = password
remote write URL path = /api/v1/write

[exporting:global]
    enabled = yes

[prometheus:exporter]
```

and the following error in the logs
```

2023-05-19 16:58:49: netdata INFO  : EXPORTING : enabled exporting of host 'localhost' for instance 'my_instance'
2023-05-19 16:58:49: netdata ERROR : EXPORTING : Cannot resolve host 'hostname', port '443': Name does not resolve (errno 11, Resource temporarily unavailable)
2023-05-19 16:58:49: netdata ERROR : EXPORTING : EXPORTING: failed to update 'hostname:443'
```

### Expected behavior

Be able to see the data in the remote prometheus server

### Steps to reproduce

1. Download and install netdata for windows
2. On the _C:\Netdata\rootfs\etc\netdata_ add the _exporting.conf_ and insert the above mentioned configuration
3. Start netdata
...

### Installation method

from git

### System info

```shell
windows 10
```

### Netdata build info

```shell
latest
```

**Comment by ilyam8** [comment]
> 2023-05-19 16:58:49: netdata ERROR : EXPORTING : Cannot resolve host 'hostname', port '443': Name does not resolve (errno 11, Resource temporarily unavailable)


This is a name resolution problem. Netdata cannot resolve hostname to IP address, check DNS settings or try using IP address.
