### ISSUE TITLE
[Feat]: add chart labels to Prometheus export

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#15089]
### Problem

Netdata doesn't add chart labels when [exporting metrics in Prometheus format](https://learn.netdata.cloud/docs/exporting-data/prometheus/#querying-metrics).

### Description

The chart labels should show up in the Prometheus export.

### Importance

must have

### Value proposition

1. 
2.
3.
...

### Proposed implementation

I think we should skip labels that start with "_". E.g. "_collect_plugin", "_collect_module".

For instance, the following 

```cmd
netdata_net_net_total{chart="net.ens18",family="ens18",dimension="received"} 9973273 1684854547294
netdata_net_net_total{chart="net.ens18",family="ens18",dimension="sent"} 10915501 1684854547294
```

should be

```cmd
netdata_net_net_total{chart="net.ens18",family="ens18",dimension="received",interface_type="real",device="ens18"} 9973273 1684854547294
netdata_net_net_total{chart="net.ens18",family="ens18",dimension="sent",interface_type="real",device="ens18"} 10915501 1684854547294
```

Probably this should be an (exporting engine) configuration option and disabled by default. If this is a breaking change (i am not sure) this can be disabled initially.

**Comment by thiagoftsm** [comment]
@ilyam8, we already have ["send configured labels" and "send automatic labels"](https://learn.netdata.cloud/docs/exporting-data/exporting-reference#options) for host labels. In my understanding we need to rename them to "send configured host labels" and "send automatic host labels", and after this to create analogous options for chart labels.

**Comment by thiagoftsm** [comment]
After an internal meeting we have decided that we will have a new option `send chart labels` that initially will be disabled by default, because we are evaluating impacts on Thanos.
