### ISSUE TITLE
[Bug]: Connection Problem [To access Cloud install again your agent via the kickstart script] in webUI after --disable-cloud and not enough good confirmation on CLI

### ISSUE THREAD

**Issue by slrslr** [netdata/netdata#15083]
### Bug description

At first, I have installed netdata using Debian 11 stable package, then i have used [one-line-installer-kickstart.sh](https://learn.netdata.cloud/docs/installation/installation-methods/one-line-installer-kickstart.sh) to install nightly version from netdata-repo-edge.

Then apt package manager wanted to download 25MB of update which i consider too much for frequent updates so i ran kickstat again with --stable-channel and **it not worked** - i remained on Nightly (per Netdata version number inside web UI).

but what worked was to reinstall: sh /tmp/netdata-kickstart.sh --stable-channel --disable-cloud --reinstall --disable-telemetry

`--disable-cloud: For local builds, don’t build any of the cloud code at all. For native packages and static builds, use runtime configuration to disable cloud support.`

yet **problem** is that
1) the --disable-cloud switch IMO not shown any apparent message confirming removal of cloud.
2) inside web UI http://localhost:19999 i always on reload seeing bottom-left corner red popup:
> Connection Problem [To access Cloud install again your agent via the kickstart script](https://learn.netdata.cloud/docs/agent/packaging/installer#automatic-one-line-installation-script)

### Expected behavior

works

### Steps to reproduce

above

### Installation method

kickstart.sh

### System info

```shell
Linux hn 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
1.39.1 [buildinfo](https://bin.disroot.org/?f06df6efa3ac5c7e#AD6HifmQ4K8VxaQ7WQdHxWkpX6VFxYyrVB98mNhNSas6)
```

### Additional info

Thank you

**Comment by MrZammler** [comment]
Hi @slrslr 

Well, indeed the `--disable-cloud` option does not work if you install a binary package. This option is a build option, meaning that you would need to actually compile from source and it would disable any cloud related code. However, our binary packages ship with cloud code compiled in.

We'll check point 2 though.

**Comment by MrZammler** [comment]
Hi @slrslr 

Was this agent ever claimed to the cloud?

**Comment by slrslr** [comment]
> If it was, try removing or renaming `/var/lib/netdata/cloud.d/claimed_id` to see if that removes the popup banner as well.

It removed the popup...
`sudo mv /var/lib/netdata/cloud.d/claimed_id /var/lib/netdata/cloud.d/claimed_id_ && systemctl restart netdata`

Maybe the  --disable-cloud switch or such may get rid of it automatically or the popup be handled different way so user does not need to spend time searching and finding this workaround. Disabling cloud should be more user friendly when using kickstart .sh script IMO.

**Comment by MrZammler** [comment]
Agree, yes. We just need to check the way to return it to a connected agent.

**Comment by ilyam8** [comment]
Just tested and `--disable-cloud` worked as expected

>   For local builds, don’t build any of the Netdata Cloud code at all. For native packages and static builds, use runtime configuration to disable Netdata Cloud support.

I think this issue is no longer relevant.
