### ISSUE TITLE
[Feat]: `/api/v2/alerts`

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#15081]
### Problem

We need to unify alerts API across agent and cloud.

### Description

1. Support the same scope parameters as all `/api/v2` calls.
2. Support the same common response fragments as all `/api/v2` calls.
3. Once our work on the agent is ready, cloud will port their endpoints to produce exactly the same result, so that the dashboard can hit either a parent agent or the cloud.

### Importance

blocker

### Value proposition

Allow both the agent and the cloud to have the same API responses for alerts.

## all `/api/v2` endpoints

1. Support `options=minify`.
2. Return multi-node data, supporting `scope_nodes`, `scope_contexts` to limit the response to some of them.
3. Support `request` analysis.
4. Support `agents` analysis (the responding agent(s), not nodes).
5. Support `versions` with hashes about state changes.

## `/api/v2/alerts`

Returns all running alerts, per node.

options:

- `active` to return only the raised alerts, otherwise all the configured alerts
- `config` to return status, values and configuration, otherwise only the status and current values of the alerts
- `alert={alert_name}/{chart}@{host}` to fetch the specific alert (`host` can be `ni`, `mg`, or `nm`, `{chart}@{host}` is the instance fqdn).

Response:

```js
{
   "api": 2,
   "request": {
   ... describe the request ...
   },
   "agents": [{
      ... describe the agent responding ...
   }],
   "versions": {
      ... hashes for everything ...
   },
   "nodes": [{
      ... description of the node...
      "alerts": [{
      }]
   }]
}
```

## `/api/v2/alerts_log`

1. universal alert log entry ID (`alertLogID`) for all alert transitions (cross node), which is a timestamp in microseconds, so that 2 alerts cannot have the same. If cloud can provide a unique sequence ID for all alert transitions, then we should all use such an auto-increment id.
2. `since={alertLogID}` to return all the new entries since the given `alertLogID`.
3. `alert={alert_name}/{chart}@{host}` to fetch the log of a specific alert (`host` can be `ni`, `mg`, or `nm`, `{chart}@{host}` is the instance fqdn).
4.

**Comment by stelfrag** [comment]
#### Selectors

- Alert name
- Transition ID
- Alert id
- Config (hash)
- Transition after / before (full transition log)

Options
- Config / transitions

How to identify a unique transition (on a alert)
