### ISSUE TITLE
[Feat]: Migrate UPS monitoring collectors (APCUPSD and NUT) to go.d.plugin.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#15115]
### Problem

UPS monitoring is one of the last few widely used data collection tasks in the charts.d plugin (specifically, the APCUPSD and NUT collectors).

### Description

These collectors should be migrated to be part of the Go plugin.

### Importance

really want

### Value proposition

1. Fewer users will need the charts.d plugin (relevant for: https://github.com/netdata/netdata/pull/13927).
2. Data collection from UPS devices will be less resource intensive.

### Proposed implementation

There appear to already be somewhat minimal packages for interacting with apcupsd and NUT from Golang:
- https://pkg.go.dev/github.com/mdlayher/apcupsd
- https://pkg.go.dev/github.com/robbiet480/go.nut

**Comment by ilyam8** [comment]
@Ferroin the only blocker is the lack of UPSs to test. We can add go versions that use that library but we surely need to test before suggesting to use them. Do you have any?

**Comment by Ferroin** [comment]
> @Ferroin the only blocker is the lack of UPSs to test. We can add go versions that use that library but we surely need to test before suggesting to use them. Do you have any?

I unfortunately do not. The main goal in creating this issue was to make a clear record that we want to do this and hopefully get some user interest.

That said, I was actually planning on reaching out on Discord to see if any of our users who are using these collectors would be interested in helping with testing once the code is written (I have some interest in seeing this happen because it will mean fewer users need the charts plugin, which in turn means fewer users will need to _install_ the charts plugin package, which should cut down on data usage of our native package repos a bit).

**Comment by ilyam8** [comment]
Add upsd (nut) collector in netdata/go.d.plugin#1341

**Comment by Forza-tng** [comment]
> @Ferroin the only blocker is the lack of UPSs to test. We can add go versions that use that library but we surely need to test before suggesting to use them. Do you have any?

I have a Eaton UPS. I often have issues with netdata loosing connection to it, so it would be interesting for me to test the new go collector.
