### ISSUE TITLE
[Bug]: Kickstart installs overwrite pre-existing Netdata system service scripts.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#15138]
### Bug description

When installing Netdata using the kickstart script, any existing system service script is unconditionally overwritten during the install process.

### Expected behavior

Existing system service scripts are not overwritten unless the user forces it. If they are found, a warning should be printed.

### Steps to reproduce

1. Install Netdata using a third-party installation method (such as using a copy from the system package manager.
2. Install again with the kickstart script without removing the original install.

### Installation method

kickstart.sh

### System info

```shell
n/a (affects all platforms)
```

### Netdata build info

```shell
n/a (affects all supported versions of Netdata)
```

### Additional info

Created based on [user submitted feedback on our Discord server](https://discord.com/channels/847502280503590932/851461027229073428/1114770965423996978).

**Comment by MikeJakubik** [comment]
This is just in case someone wants to try a master build or a diff version and already has Netdata installed via ports. The two may attempt writing in the same /usr/local prefix, as per FreeBSD hier(7). Though the rc.d script is hardcoded to /usr/local/etc/rc.d. But if this script continues to work and can do updates then that's great, as the maintainer of the port isn't always up to speed on Netdata releases.

**Comment by MikeJakubik** [comment]
You can check if the port is installed using pkg, i.e. "pkg info netdata" will return "pkg: No package(s) matching netdata" if it is not installed.

**Comment by Pingger** [comment]
> When installing Netdata using the kickstart script, any existing system service script is unconditionally overwritten during the install process.

According to the systemd documentation, service files in `/usr/lib/systemd` are to be expected to be overwritten. Users who don't want their service files overwritten are encouraged to use `/etc/systemd/`, or the edit command `systemctl edit <unit-file>` (which creates the override file in `/etc/systemd/system/<unit-file>.d/override.conf`

According to this, I would not consider this a bug.

See the manpage: https://manpages.ubuntu.com/manpages/lunar/en/man5/systemd.unit.5.html#unit%20file%20load%20path

**Comment by Ferroin** [comment]
@Pingger The systemd case is indeed not really a bug here.

We do have an issue though on most other init systems in that we blindly overwrite any existing init script for the agent, because they do not have the same split of distro/user provided service files that systemd does.

**Comment by MikeJakubik** [comment]
@ilyam8 What do you mean by the label "wontfix?. Why not, this should be simple. One of the main reasons I contributed to, advocated for, and financially supported Netdata is that it was portable and not Linux centric, is this not the case anymore? Not every UNIX like OS uses systemd, there is a good reason for this.

**Comment by MikeJakubik** [comment]
@ilyam8 What do you mean by the label "wontfix?. Why not, this should be simple. One of the main reasons I contributed to, advocated for, and financially supported Netdata is that it was portable and not Linux centric, is this not the case anymore? NOt every UNIX like OS uses systemd.

**Comment by ilyam8** [comment]
You're right, I see I focused too heavily on the systemd case - the issue description is not super specific so as it is - wontfix. In my opinion, overwriting service scripts during reinstall/update can be a valid approach, depending on the context. And closing doesn't mean deleting. Quite often it is even useful to close issues to resume a stale discussion 😄
