### ISSUE TITLE
[Bug]: Lost Metric Windows 

### ISSUE THREAD

**Issue by Bullote** [netdata/netdata#15137]
### Bug description

Since the agent version update on Monday night all our windows metrics have stopped working, the same happens with the functions even though they are activated. We have updated all the agents as of today but everything remains the same.

### Expected behavior

That everything works as before the update

### Steps to reproduce

1. nothing

### Installation method

kickstart.sh

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.2 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Version: netdata v1.39.0-89-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by tkatsoulas** [comment]
Hello @Bullote, could you double down on the [configurations](https://learn.netdata.cloud/docs/data-collection/windows-systems#configuration) of the Agent about the Windows machines you are monitoring? Are they still there/active?

**Comment by ilyam8** [comment]
@Bullote and please show `ls -l /usr/libexec/netdata/plugins.d/`

**Comment by Bullote** [comment]
Hi,
this is


-rwxr-xr-x 1 root netdata   4873 jun  2 00:19 acl.sh
-rwxr-xr-x 1 root netdata    154 jun  2 00:19 alarm-email.sh
-rwxr-xr-x 1 root netdata 142068 jun  2 00:19 alarm-notify.sh
-rwxr-xr-x 1 root netdata   2143 jun  2 00:19 alarm.sh
-rwxr-xr-x 1 root netdata    301 jun  2 00:19 alarm-test.sh
-rwxr-xr-x 1 root netdata   8076 jun  2 00:19 anonymous-statistics.sh
-rwxr-xr-x 1 root netdata  21691 jun  2 00:19 cgroup-name.sh
-rwsr-x--- 1 root netdata 742240 jun  2 00:19 cgroup-network
-rwxr-xr-x 1 root netdata   8768 jun  2 00:19 cgroup-network-helper.sh
drwxr-xr-x 2 root netdata  81920 may 31 06:57 ebpf.d
-rwxr-xr-x 1 root netdata   2139 jun  2 00:19 get-kubernetes-labels.sh
-rwxr-xr-x 1 root netdata   7318 jun  2 00:19 health-cmdapi-test.sh
-rwxr-xr-x 1 root netdata   5380 jun  2 00:19 ioping.plugin
-rwxr-xr-x 1 root netdata   6860 jun  2 00:19 loopsleepms.sh.inc
-rwxr-xr-x 1 root netdata  11020 jun  2 00:19 request.sh
-rwxr-xr-x 1 root netdata  22259 jun  2 00:19 system-info.sh
-rwxr-xr-x 1 root netdata   7334 jun  2 00:19 tc-qos-helper.sh
-rwxr-xr-x 1 root netdata   2903 jun  2 00:19 template_dim.sh



Regards

[https://www.plexus.es/mail/dark/sm2plx.png]

Javier Boullosa García
Infraestructura y Sistemas
Móv. 615 264 564<tel:+34615264564>
Tel. 971 750 324 ext 0000<tel:+34971750324>

[https://www.plexus.es/mail/dark/i-_0003_linkedin.png]<https://www.linkedin.com/company/2650298/admin/>| [https://www.plexus.es/mail/dark/i-_0002_instagram.png] <https://www.instagram.com/plexus.tech/> | [https://www.plexus.es/mail/dark/i-_0001_facebook.png] <https://www.facebook.com/Plexus.Techno/?modal=admin_todo_tour> | [https://www.plexus.es/mail/dark/i-_0000_twitter.png] <https://twitter.com/Plexology_>
plexus.es<https://www.plexus.es/>

La información contenida en el presente mensaje podría ser confidencial. Si recibe este mensaje por error, le rogamos nos lo comunique de inmediato y lo elimine sin conservar copia del mismo ni de sus documentos adjuntos. Asimismo, le comunicamos que la distribución, copia o utilización de este mensaje, o de cualquier documento adjunto al mismo, cualquiera que fuera su finalidad, están prohibidas por la ley.


De: Ilya Mashchenko ***@***.***>
Enviado el: viernes, 2 de junio de 2023 11:36
Para: netdata/netdata ***@***.***>
CC: Javier Boullosa García ***@***.***>; Mention ***@***.***>
Asunto: Re: [netdata/netdata] [Bug]: Lost Metric Windows (Issue #15137)


@Bullote<https://github.com/Bullote> and please show ls -l /usr/libexec/netdata/plugins.d/

**Comment by Bullote** [comment]
ii  netdata                               1.39.0-89-nightly                       amd64        real-time charts for system monitoring
ii  netdata-repo-edge                     2-1                                     all          Configuration for the official Netdata Edge package repository.

**Comment by ilyam8** [comment]
@Bullote can you do the following:

```
apt-get update
apt-get install netdata-ebpf-code-legacy netdata-plugin-apps netdata-plugin-debugfs netdata-plugin-ebpf netdata-plugin-go netdata-plugin-pythond
systemctl restart netdata
```

**Comment by Bullote** [comment]
Fixed

Thank you so much
