### ISSUE TITLE
[Bug]: netdata-updater exited with return code 1

### ISSUE THREAD

**Issue by krosseyed** [netdata/netdata#15176]
### Bug description

When updating via APT on Debian, I get a cryptic code 1 return error.

### Expected behavior

For apt to update Netdata and to get on with life

### Steps to reproduce

1. Wait for CRON to run apt upgrade-y
2. Get an email saying Netdata cannot be updated
3. Profit

### Installation method

kickstart.sh

### System info

```shell
Linux node01 5.4.106-1-pve #1 SMP PVE 5.4.106-1 (Fri, 19 Mar 2021 11:08:47 +0100) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.39.0-108-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

```bash
/etc/cron.daily/netdata-updater:
Sat 10 Jun 2023 06:54:54 AM CDT : INFO: netdata-updater:  Checking if a newer version of the updater script is available.
Hit:1 http://repo.netdata.cloud/repos/edge/debian buster/ InRelease
Hit:2 http://repo.netdata.cloud/repos/repoconfig/debian buster/ InRelease
Hit:3 http://security.debian.org/ buster/updates InRelease
Hit:4 http://ftp.us.debian.org/debian buster InRelease
Hit:5 http://ftp.us.debian.org/debian buster-updates InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
netdata-repo-edge is already the newest version (2-1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
Hit:1 http://security.debian.org/ buster/updates InRelease
Hit:2 http://repo.netdata.cloud/repos/edge/debian buster/ InRelease
Hit:3 http://repo.netdata.cloud/repos/repoconfig/debian buster/ InRelease
Hit:4 http://ftp.us.debian.org/debian buster InRelease
Hit:5 http://ftp.us.debian.org/debian buster-updates InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
 netdata-plugin-cups netdata-plugin-freeipmi
The following packages will be upgraded:
 netdata
1 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Need to get 10.2 MB of archives.
After this operation, 46.1 kB of additional disk space will be used.
Get:1 http://repo.netdata.cloud/repos/edge/debian buster/ netdata 1.39.0-116-nightly [10.2 MB]
apt-listchanges: Reading changelogs...
Fetched 10.2 MB in 0s (26.8 MB/s)
dpkg: regarding .../netdata_1.39.0-116-nightly_amd64.deb containing netdata:
netdata conflicts with netdata-base
 netdata-base (version 1.39.0-108-nightly) is present and installed.

dpkg: error processing archive /var/cache/apt/archives/netdata_1.39.0-116-nightly_amd64.deb (--unpack):
conflicting packages - not installing netdata
Errors were encountered while processing:
/var/cache/apt/archives/netdata_1.39.0-116-nightly_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Sat 10 Jun 2023 06:55:01 AM CDT : FATAL: netdata-updater: FAILED TO UPDATE NETDATA:  Failed to update Netdata package.
run-parts: /etc/cron.daily/netdata-updater exited with return code 1
```

**Comment by tkatsoulas** [comment]
Hello @krosseyed, you can ignore it for now if you don't face any other issue. There is a fix https://github.com/netdata/netdata/pull/15170 pipelined to be shipped with Mondays (midnight) nightly builds. Then the update will be seamless. 

If you want you can manually remove the netdata-base image (it was an interim package we shipped to seamless update due to the recent netdata packaging changes) and update to the latest nightly.

**Comment by krosseyed** [comment]
@tkatsoulas,

Thank you for the update, and I will sit tight for Monday. This is not bothering me as I was able to log into the servers and dpkg --configure -a to get around this issue for now.

**Comment by tkatsoulas** [comment]
Could you verify that the issues still persist?

**Comment by krosseyed** [comment]
@tkatsoulas,

Looks like its working now. Thank you for checking on this!

**Comment by krosseyed** [comment]
Looks like there is another issue:

`
root@node01:/# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  netdata-base
Use 'apt autoremove' to remove it.
The following packages will be upgraded:
  netdata netdata-ebpf-code-legacy netdata-plugin-apps netdata-plugin-chartsd
  netdata-plugin-debugfs netdata-plugin-ebpf netdata-plugin-go netdata-plugin-nfacct
  netdata-plugin-perf netdata-plugin-pythond netdata-plugin-slabinfo
11 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 258 kB/27.2 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://repo.netdata.cloud/repos/edge/debian buster/ netdata-plugin-pythond 1.39.0-125-nightly [226 kB]
Err:1 http://repo.netdata.cloud/repos/edge/debian buster/ netdata-plugin-pythond 1.39.0-125-nightly
  File has unexpected size (226322 != 226318). Mirror sync in progress? [IP: 172.67.72.170 80]
  Hashes of expected file:
   - SHA256:a09d2d88b61b5f4a765427944e26583d39d2833d4bf3843853faf5ccf439b00f
   - SHA1:7d1dc198c7ae2eeeb01d6881ccb281c6ca5ed753 [weak]
   - MD5Sum:496efaffe0ded9f33c839bbcd3bdfc98 [weak]
   - Filesize:226318 [weak]
Get:2 http://repo.netdata.cloud/repos/edge/debian buster/ netdata-plugin-chartsd 1.39.0-125-nightly [31.5 kB]
Err:2 http://repo.netdata.cloud/repos/edge/debian buster/ netdata-plugin-chartsd 1.39.0-125-nightly
  File has unexpected size (31486 != 31482). Mirror sync in progress? [IP: 172.67.72.170 80]
  Hashes of expected file:
   - SHA256:0ae6e3b2c991a7d9fb497a90313fba02eb752c00e2f04229796413ee2981c6e3
   - SHA1:1f4ab649a466989a218a64d4533bae2c6a021c0a [weak]
   - MD5Sum:e723caba937f557510fecf9d1810328d [weak]
   - Filesize:31482 [weak]
E: Failed to fetch http://repo.netdata.cloud/repos/edge/debian/buster/netdata-plugin-pythond_1.39.0-125-nightly+debian10_all.deb  File has unexpected size (226322 != 226318). Mirror sync in progress? [IP: 172.67.72.170 80]
   Hashes of expected file:
    - SHA256:a09d2d88b61b5f4a765427944e26583d39d2833d4bf3843853faf5ccf439b00f
    - SHA1:7d1dc198c7ae2eeeb01d6881ccb281c6ca5ed753 [weak]
    - MD5Sum:496efaffe0ded9f33c839bbcd3bdfc98 [weak]
    - Filesize:226318 [weak]
E: Failed to fetch http://repo.netdata.cloud/repos/edge/debian/buster/netdata-plugin-chartsd_1.39.0-125-nightly+debian10_all.deb  File has unexpected size (31486 != 31482). Mirror sync in progress? [IP: 172.67.72.170 80]
   Hashes of expected file:
    - SHA256:0ae6e3b2c991a7d9fb497a90313fba02eb752c00e2f04229796413ee2981c6e3
    - SHA1:1f4ab649a466989a218a64d4533bae2c6a021c0a [weak]
    - MD5Sum:e723caba937f557510fecf9d1810328d [weak]
    - Filesize:31482 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

**Comment by tkatsoulas** [comment]
cc @Ferroin

**Comment by krosseyed** [comment]
@tkatsoulas + @Ferroin,

Looks like it is all working again. Thanks!

**Comment by audioscavenger** [comment]
i am unable to update anything because of this error. 
```
Get:1 http://repo.netdata.cloud/repos/edge/ubuntu focal/ netdata-plugin-pythond 1.45.0-109-nightly [215 kB]
Err:1 http://repo.netdata.cloud/repos/edge/ubuntu focal/ netdata-plugin-pythond 1.45.0-109-nightly
  File has unexpected size (214722 != 214682). Mirror sync in progress? [IP: 104.26.8.141 80]
  Hashes of expected file:
   - SHA256:ba8915dd0a979482970c7834a8333f13928d7bfa590bfb893c719df90f8cf25e
   - SHA1:77e0c8ec5729df44f9c5981572fed9a4addf6de2 [weak]
   - MD5Sum:8491c9e95b9bcbf9400c5a412b3ec294 [weak]
   - Filesize:214682 [weak]
Get:2 http://repo.netdata.cloud/repos/edge/ubuntu focal/ netdata-plugin-chartsd 1.45.0-109-nightly [19.4 kB]
Err:2 http://repo.netdata.cloud/repos/edge/ubuntu focal/ netdata-plugin-chartsd 1.45.0-109-nightly
  File has unexpected size (19446 != 19442). Mirror sync in progress? [IP: 104.26.8.141 80]
  Hashes of expected file:
   - SHA256:c29d2b0a54d21e3178bfe689808a6731b1b88afdff4c87a33db3bc1ed6f8052a
   - SHA1:2b2d4faad28f6f8e6b4f1b8cfe04c9fbc5b19af9 [weak]
   - MD5Sum:2df862a94ead567544d2d54260440749 [weak]
   - Filesize:19442 [weak]
E: Failed to fetch http://repo.netdata.cloud/repos/edge/ubuntu/focal/netdata-plugin-pythond_1.45.0-109-nightly+ubuntu20.04_all.deb  File has unexpected size (214722 != 214682). Mirror sync in progress? [IP: 104.26.8.141 80]
   Hashes of expected file:
    - SHA256:ba8915dd0a979482970c7834a8333f13928d7bfa590bfb893c719df90f8cf25e
    - SHA1:77e0c8ec5729df44f9c5981572fed9a4addf6de2 [weak]
    - MD5Sum:8491c9e95b9bcbf9400c5a412b3ec294 [weak]
    - Filesize:214682 [weak]
E: Failed to fetch http://repo.netdata.cloud/repos/edge/ubuntu/focal/netdata-plugin-chartsd_1.45.0-109-nightly+ubuntu20.04_all.deb  File has unexpected size (19446 != 19442). Mirror sync in progress? [IP: 104.26.8.141 80]
   Hashes of expected file:
    - SHA256:c29d2b0a54d21e3178bfe689808a6731b1b88afdff4c87a33db3bc1ed6f8052a
    - SHA1:2b2d4faad28f6f8e6b4f1b8cfe04c9fbc5b19af9 [weak]
    - MD5Sum:2df862a94ead567544d2d54260440749 [weak]
    - Filesize:19442 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by jmakov** [comment]
Same here.
