### ISSUE TITLE
[Feat]: Increase granularity on install prefix CLI option for `netdata-installer.sh`

### ISSUE THREAD

**Issue by petecooper** [netdata/netdata#15175]
### Problem

Providing a `--install-prefix <path>` option on the CLI affects _all_ the component install locations. This isn't always desirable. A more granular approach to each of the components would be more desirable, and useful for folks who follow / interpret [FSH](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) to a greater extent.

Running `netdata-installer.sh` without options gives the following component locations:

```
   - the daemon     at /usr/sbin/netdata
   - config files   in /etc/netdata
   - web files      in /usr/share/netdata
   - plugins        in /usr/libexec/netdata
   - cache files    in /var/cache/netdata
   - db files       in /var/lib/netdata
   - log files      in /var/log/netdata
   - pid file       at /var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata
```

The help states:

```
--install-prefix <path>    Install netdata in <path>. Ex. --install-prefix /opt will put netdata in /opt/netdata.
```

Supplying that directive gives the following component locations:

```
   - the daemon     at /opt/netdata/usr/sbin/netdata
   - config files   in /opt/netdata/etc/netdata
   - web files      in /opt/netdata/usr/share/netdata
   - plugins        in /opt/netdata/usr/libexec/netdata
   - cache files    in /opt/netdata/var/cache/netdata
   - db files       in /opt/netdata/var/lib/netdata
   - log files      in /opt/netdata/var/log/netdata
   - pid file       at /opt/netdata/var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata
```

Most (not all) the locations are prepended with `/opt/netdata` per the help, but the components are much more 'centralised' than before, which may add complexity to permissions maintenance, and other administration considerations.

### Description

Extend CLI options to each of the components, either `prefix` or `path`, or similar:

```
--daemon-prefix
--config-prefix
--web-files-prefix
--plugins-prefix
--cache-files-prefix
--db-files-prefix
--log-files-prefix
--pid-prefix
--logrotate-prefix
```

Nginx uses a similar granular approach in their `configure` options: https://www.nginx.com/resources/wiki/start/topics/tutorials/installoptions/

### Importance

nice to have

### Value proposition

1. Added flexibility for server mavericks & FSH nerds, which could bring in more users.
2. Reduced maintenance burden for permissions if only some components are relocated.

### Proposed implementation

I have no insight into how viable this is, but thank you for your considerations. Netdata is excellent, and I recommend it to as many people as I can.

**Comment by ilyam8** [comment]
I think this is wontfix, we don't plan to add `dirname-prefix` for every directory - it complicates installation/uninstallation a lot. And installing from the source is not a recommended way, we don't actively support it. cc @netdata/agent-sre
