### ISSUE TITLE
[Feat]: Enable Build for opensuse 15 SP5

### ISSUE THREAD

**Issue by Pihaar** [netdata/netdata#15188]
### Description

Opensuse has released the latest service package 15.5 on 7th of June 2023. 
Therefore I request that builds for this version are enabled and pushed to: 
https://repo.netdata.cloud/repos/edge/opensuse/15.5/

Same for the repo config: 
https://repo.netdata.cloud/repos/repoconfig/opensuse/15.5/

### Importance

really want

### Value proposition

Prebuilt packages can be used instead of having to compile it for every new update

**Comment by tkatsoulas** [comment]
Hello @Pihaar, if there is no extra work needed to be done/ any other roadblock, you would probably have the packages by tomorrow.

Have a good day

**Comment by tkatsoulas** [comment]
@Pihaar A small change of plan, we will release today v1.40. So the native packages for the stable will be available in aprox 7hours and the native packages for nightly channel tomorrow (June 15) aprox 6 am UTC

**Comment by Pihaar** [comment]
@tkatsoulas Thank you for the great and quick work! Highly appreciated.
