### ISSUE TITLE
[Bug]: `libnetdata/buffer/buffer.h:10:10: fatal error: h2o/memory.h: No such file or directory`

### ISSUE THREAD

**Issue by petecooper** [netdata/netdata#15199]
### Bug description

Netdata 1.40.0 installer fails with error. Netdata 1.39.1 installer completes without issue.

```
make[2]: Leaving directory '/home/pete/netdata-source/netdata-1.40.0/claim'
Making all in spawn
make[2]: Entering directory '/home/pete/netdata-source/netdata-1.40.0/spawn'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/pete/netdata-source/netdata-1.40.0/spawn'
make[2]: Entering directory '/home/pete/netdata-source/netdata-1.40.0'
  CC       libnetdata/os.o
make[2]: *** No rule to make target 'httpd/h2o/deps/cloexec/cloexec.c', needed by 'httpd/h2o/deps/cloexec/libh2o_a-cloexec.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
In file included from libnetdata/libnetdata.h:635,
                 from libnetdata/os.h:6,
                 from libnetdata/os.c:3:
libnetdata/buffer/buffer.h:10:10: fatal error: h2o/memory.h: No such file or directory
   10 | #include "h2o/memory.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:7060: libnetdata/os.o] Error 1
make[2]: Leaving directory '/home/pete/netdata-source/netdata-1.40.0'
make[1]: *** [Makefile:9410: all-recursive] Error 1
make[1]: Leaving directory '/home/pete/netdata-source/netdata-1.40.0'
make: *** [Makefile:4170: all] Error 2
 FAILED  ''

 ABORTED  Failed to build Netdata. 
```

### Expected behavior

Netdata 1.40.0 compiles and launches without issue.

### Steps to reproduce

1. Run `netdata-installer.sh` from v1.40.0 release:

```
sudo bash ~/netdata-source/netdata-$netdata_source_version/netdata-installer.sh \
--disable-cloud \
--disable-telemetry \
--dont-wait \
--enable-lto \
--stable-channel
```

3. Note the error:4. 

```
make[2]: Leaving directory '/home/pete/netdata-source/netdata-1.40.0/claim'
Making all in spawn
make[2]: Entering directory '/home/pete/netdata-source/netdata-1.40.0/spawn'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/pete/netdata-source/netdata-1.40.0/spawn'
make[2]: Entering directory '/home/pete/netdata-source/netdata-1.40.0'
  CC       libnetdata/os.o
make[2]: *** No rule to make target 'httpd/h2o/deps/cloexec/cloexec.c', needed by 'httpd/h2o/deps/cloexec/libh2o_a-cloexec.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
In file included from libnetdata/libnetdata.h:635,
                 from libnetdata/os.h:6,
                 from libnetdata/os.c:3:
libnetdata/buffer/buffer.h:10:10: fatal error: h2o/memory.h: No such file or directory
   10 | #include "h2o/memory.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:7060: libnetdata/os.o] Error 1
make[2]: Leaving directory '/home/pete/netdata-source/netdata-1.40.0'
make[1]: *** [Makefile:9410: all-recursive] Error 1
make[1]: Leaving directory '/home/pete/netdata-source/netdata-1.40.0'
make: *** [Makefile:4170: all] Error 2
 FAILED  ''

 ABORTED  Failed to build Netdata.
```

### Installation method

from source

### System info

```shell
$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux haggis 6.1.0-9-arm64 #1 SMP Debian 6.1.27-1 (2023-05-08) aarch64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="12"
/etc/os-release:VERSION="12 (bookworm)"
/etc/os-release:VERSION_CODENAME=bookworm
/etc/os-release:ID=debian
```

### Netdata build info

```shell
n/a
```

### Additional info

Netdata build info cannot be provided as compilation fails.

**Comment by petecooper** [comment]
Same error confirmed on Ubuntu 20.04 (amd64):

$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux donald 5.4.0-149-generic #166-Ubuntu SMP Tue Apr 18 16:51:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.6 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.6 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

**Comment by ilyam8** [comment]
@petecooper I think you need to update git submodules, do `git submodule update --recursive --init`

**Comment by tkatsoulas** [comment]
cc @Ferroin

**Comment by tkatsoulas** [comment]
Yes it's a plain folder not a git tracked.

**Comment by Ferroin** [comment]
Just confirming: you're trying to use one of the archives labelled 'Source Code' from the release page, correct?

Those are provided by GitHub, not by us, and are known to not work at all because they don't include any submodules. If you wish to build from source using a source archive instead of a git checkout, you'll need to use the `netdata-v1.40.0.tar.gz` archive on the release instead (which is provided by us, and does include all the submodules).

**Comment by petecooper** [comment]
> Just confirming: you're trying to use one of the archives labelled 'Source Code' from the release page, correct?

No. I am using a tracked, version'd release – in this case `[netdata-v1.40.0.tar.gz](https://github.com/netdata/netdata/releases/download/v1.40.0/netdata-v1.40.0.tar.gz)`. Here's my full get-and-run script:

```
netdata_source_version="1.40.0" \
&& cd ~ \
&& sudo rm -rf \
~/netdata-source \
~/netdata-source.tar.gz \
&& mkdir -p ~/netdata-source \
&& curl -Lo ~/netdata-source.tar.gz https://github.com/netdata/netdata/archive/v$netdata_source_version.tar.gz \
&& tar xzvf ~/netdata-source.tar.gz -C ~/netdata-source \
&& cd ~/netdata-source/netdata-$netdata_source_version/ \
&& sudo bash ~/netdata-source/netdata-$netdata_source_version/netdata-installer.sh \
--disable-cloud \
--disable-telemetry \
--dont-wait \
--enable-lto \
--stable-channel \
&& echo -e 'Checking Netdata version...' \
&& /usr/sbin/netdata -v \
&& cd ~ \
&& sudo rm -rf \
~/netdata-source \
~/netdata-source.tar.gz \
&& sudo rm -f /netdata-updater.log.* \
&& echo -e '***************************' \
&& echo -e '* Netdata core installed. *' \
&& echo -e '***************************' \
&& echo -e $(date --iso-8601=seconds)' Netdata core '$netdata_source_version >> /var/log/build/231-build-netdata.log
```

I've used this approach for 3+ years without any obvious issue, and it works perfectly for v1.39.1 (and prior versions).

Thank you for your attention and assitance with this, it is greatly appreciated.

**Comment by ilyam8** [comment]
@petecooper switch to 

```bash
netdata_source_version=v1.40.0
https://github.com/netdata/netdata/releases/download/$netdata_source_version/netdata-$netdata_source_version.tar.gz
```

`https://github.com/netdata/netdata/archive/v1.40.0.tar.gz` downloads the source code archive.

**Comment by petecooper** [comment]
Thank you @ilyam8. I have used your replacement suggestion – that resolves the issue.

I have no idea why my (incorrect) approach was working for so long, but I am most grateful for your time, assistance and guidance.
