### ISSUE TITLE
[Bug]: lighttpd errors with "cannot execute binary file: Exec format error"

### ISSUE THREAD

**Issue by LunarTwilight** [netdata/netdata#15194]
### Bug description

When I run `./go.d.plugin -d -m lighttpd` I get `./go.d.plugin: cannot execute binary file: Exec format error`

### Expected behavior

Plugin works

### Steps to reproduce

I attempted to follow the steps in https://github.com/netdata/go.d.plugin/tree/master/modules/lighttpd#troubleshooting which are:
1. `cd /usr/libexec/netdata/plugins.d/`
2. `sudo -u netdata -s`
3. `./go.d.plugin -d -m lighttpd`

### Installation method

kickstart.sh

### System info

```shell
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.39.0-125-nightly
Configure options:  '--build=i686-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/i386-linux-gnu' '--libexecdir=${prefix}/lib/i386-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' '--disable-ebpf' 'build_alias=i686-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    debugfs:                 YES
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by thiagoftsm** [comment]
Hello @LunarTwilight ,

I observed that you are running netdata compiled with some options for `i686` ( `--build=i686-linux-gnu`, 'build_alias=i686-linux-gnu', '--libdir=${prefix}/lib/i386-linux-gnu'), but on your host arch I see `Binary architecture: x86_64`, so I have few questions before to help you:

- How did you install netdata on your host?
- When you run commands `file /usr/sbin/netdata`, `file /usr/libexec/netdata/plugins.d/go.d.plugin` and `uname -m`, what are the outputs? I have the follow on my host:
```sh
root@hades:/home/thiago/Netdata/netdata# file /usr/sbin/netdata
/usr/sbin/netdata: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, with debug_info, not stripped
root@hades:/home/thiago/Netdata/netdata# file /usr/libexec/netdata/plugins.d/go.d.plugin
/usr/libexec/netdata/plugins.d/go.d.plugin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=q1dATN6v4042Pe7asrMV/93cfl54qS_bki-PcZozx/Ja8W5YIp8PMNOoD9uOTD/1cpmS3onWanwbFmMy6xu, stripped
root@hades:/home/thiago/Netdata/netdata# uname -m
x86_64

```

Best regards!

**Comment by LunarTwilight** [comment]
I don't remember as it was a long time ago, but I think I ran the kickstart script? If I remember correctly I also ran the kickstart script a while after that to fix some issue or something.
```
/usr/sbin/netdata: ELF 32-bit LSB pie executable, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=0e2b33e1f24c758f97460aaee8b8f97ba8b5cccb, for GNU/Linux 3.2.0, stripped
```
```
/usr/libexec/netdata/plugins.d/go.d.plugin: regular file, no read permission
```
```
i686
```

If it explains anything, I ran the commands in the initial report as the `netdata` user, but the command I just ran I ran as myself (the account I regularly use)

**Comment by ilyam8** [comment]
@LunarTwilight somehow you ended up with the go.d.plugin binary built not for your architecture. I think you need to uninstall/install again.

**Comment by LunarTwilight** [comment]
> @LunarTwilight somehow you ended up with the go.d.plugin binary built not for your architecture. I think you need to uninstall/install again.

Yeah I was kinda thinking that. I uninstalled (using the kickstart script) and reinstalled (using the kickstart script) and I still have the error, and .install-type still has `PREBUILT_ARCH='x86_64'` (which is where I assume my earlier commands were referencing?)

**Comment by ilyam8** [comment]
@netdata/agent-sre somehow (both stable and nightly)

```bash
ii  netdata-plugin-go             1.40.0                         i386         The go.d metrics collection plugin for the Netdata Agent
```

contains go.d.plugin binary for x86-64

**Comment by ilyam8** [comment]
Thanks for reporting, @LunarTwilight!  Should be fixed in the next nightly release.

**Comment by LunarTwilight** [comment]
> Thanks for reporting, @LunarTwilight! Should be fixed in the next nightly release.

Ah cool, thanks. Do I need to reinstall netdata or will it sort itself out?

**Comment by LunarTwilight** [comment]
> If you don't have auto-updating enabled - you need to update Netdata manually. The latest nightly release (v1.40.0-24-nightly) has no problem.

ah cool, I'll let it automatically update then, thanks
