### ISSUE TITLE
[Bug]: Netdata parent v1.40.0 behind Nginx TCP stream/upstream/server isn't collecting metrics from any child

### ISSUE THREAD

**Issue by marcelmfs** [netdata/netdata#15197]
### Bug description

Just now checked out the latest tag, building it via `./netdata-installer.sh` didn't work out of the box, clean repo clone, fails on h2o (even after `git submodule update --init --recursive --force`): 
```
make: *** No rule to make target `httpd/h2o/lib/http2/.deps/libh2o_a-stream.Po'.  Stop.
 FAILED  ''
```
Then I tried downloading the [pre-built package](https://github.com/netdata/netdata/releases/download/v1.40.0/netdata-x86_64-v1.40.0.gz.run) - went on and installed it, replaced configuration files, parent works fine, but no children updates. All of them are OFF. Updating the children with the exact same version does not fix the issue. Grep error.log entry:
```
2023-06-15 09:49:01: netdata ERROR : STATS_GLOBAL : STREAM netdata-child-1 [send]: not ready - collected metrics are not sent to parent.
```
Community post reports an issue [with same error](https://community.netdata.cloud/t/agent-with-windows-virtual-node-crashes-when-streaming-to-a-parent/4276), but for Windows, with Virtual Node. I'm using SNI with Nginx, maybe it's correlated. But I couldn't build the master branch, with the h2o submodule build issue mentioned earlier also for the default branch. 

Downgrading to 1.39.1 also doesn't fix the issue.

I'm trying to figure out where this issue was introduced.

### Expected behavior

No problems with the communication between Children and Parents

### Steps to reproduce

1. Set up Nginx in front of Netdata Parent Agent with TCP/stream/upstream/server/SSL termination with proxy_ssl
2. Install pre-built x86_64 v1.40.0 from last release
3. Same on Child agents, set up streaming from Children to Parent with previous configuration file
...

### Installation method

other

### System info

```shell
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
# $(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
Version: netdata v1.40.0
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -I/libnetfilter-acct-static/include/libnetfilter_acct -I/usr/include/libmnl -pipe' 'LDFLAGS=-static -L/openssl-static/lib -L/libnetfilter-acct-static/lib -lnetfilter_acct -L/usr/lib -lmnl' 'PKG_CONFIG=pkg-config --static' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig:/libnetfilter-acct-static/lib/pkgconfig:/usr/lib/pkgconfig'
Install type: manual-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by MrZammler** [comment]
Hi @marcelmfs 

There have been some changes on SSL streaming from 1.39.1 -> 1.40.0. What is weird is that 1.39.1 doesn't work as well.

Is this a new setup? Was it working and stopped streaming when updated to 1.40.0?

**Comment by ilyam8** [comment]
Hey, @marcelmfs.

> Set up Nginx in front of Netdata Parent Agent with TCP/stream/upstream/server/SSL termination with proxy_ssl

Can you provide detailed step-by-step instructions on how to do that? It will allow us to debug the problem much faster.

**Comment by marcelmfs** [comment]
Hi Ilya, 

All was fine until several days ago when I noticed some degradation in my grafana plots:
![image](https://github.com/netdata/netdata/assets/5718899/e84782cf-790a-4679-a90c-6fed017b012f)
I don't allow the auto-updater to run on the parent so this was coming from somewhere else, maybe from automatic updates or patch management from GCP.

Instead of investigating what could be causing this, I started straight by build upgrading the parent to latest stable but that didn't help, only created moar issues. I've build many different versions and setup combinations in the past few days that I kinda lost track, and decided to stop all children to finally drill down to a working setup. 

I had 41 children in a plethora of different agent versions sending metrics to one parent, I have some development servers with nightly builds ranging from v1.25.0-53-nightly (some dev servers have since lost internet access due to client on-premises restrictions) to v1.39.0-125-nightly, and some production servers with stable-channel builds (that don't update automatically) from v1.35.1 to v1.38.1 and a couple of proxy servers running netdata-push-service on 1.9.0.

With v1.37.1 built on both parent and one child I can't reproduce the issue, through v1.38.1 and v1.39.1 I could (haven't tried with their .0 counterparts). But I'm still getting this:
```
netdata ERROR : STREAM_SENDER[netdata-child-1] : STREAM netdata-child-1 [send to tcp:netata-parent-ip:19999]: buffer full (10485760-bytes) after 4020432 bytes. Restarting connection
```
And my graphs are looking like this:
![image](https://github.com/netdata/netdata/assets/5718899/04b35440-5433-4413-bac1-a748b0d1e334)

I guess I'll have to play a bit again with the buffer directive values.

My nginx config is quite complex, I split `tcp:19999` and `https:19999` traffic between different vhosts. So I'll have streaming coming to port 4443 and all HTTPS traffic coming through ssl:443. I wish netdata entrypoints could be set up in a simpler manner dealing with different ports for different purposes. The whole 19999 for streaming TCP & HTTP(s) is a bit confusing. This case of configuring it with a one liner adds a bit of complexity to split the different traffic between different services. But, voilá.

Basically I have the following (edited for length):

```
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;
include /usr/share/nginx/modules/*.conf;
events {
    worker_connections 1024;
}
stream {
  log_format proxy '$proxy_protocol_addr $remote_addr [$time_local] '
  '$protocol $status $bytes_sent $bytes_received '
  '$session_time "$upstream_addr" '
  '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';

  access_log /var/log/nginx/stream-access.log proxy;
  error_log /var/log/nginx/stream-error.log warn;
  upstream netdata {
    server 127.0.0.1:1999; #netdata tcp stream
  }
  server {
    listen 10.132.0.4:4443 so_keepalive=on;
    proxy_pass netdata;
    proxy_socket_keepalive on;
    proxx_connect_timeout 30s;
    proxy_timeout 60s;
  }
}

http {
  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
  access_log  /var/log/nginx/access.log  main;
  sendfile            on;
  tcp_nopush          on;
  tcp_nodelay         on;
  keepalive_timeout   65;
  types_hash_max_size 2048;
  gzip on;
  gzip_types text/html text/plain application/xml;
  gzip_proxied    no-cache no-store private expired auth;
  gzip_min_length 1000;
  include             /etc/nginx/mime.types;
  default_type        text/html;
  include /etc/nginx/conf.d/*.conf;
  proxy_cache_path  /etc/nginx/cache  levels=1:2    keys_zone=STATIC:1m inactive=24h  max_size=1g;

  server {
    listen  443 ssl http2;
    listen  [::]:443 ssl http2;
    server_name netdata.rianet.io;

    ssl_certificate         /etc/letsencrypt/live/exmple.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;

    add_header Strict-Transport-Security "max-age=63072000";
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    ssl on;
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 216.146.35.35 216.146.36.36 valid=300s;
    resolver_timeout 3s;
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout 24h;
    ssl_session_tickets on;
    ssl_session_ticket_key /etc/nginx/ssl/ticket.key;
    ssl_dhparam ssl/dhparams.pem;
    ssl_ecdh_curve secp384r1;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDH+AESGCM256:DH+AESGCM256:ECDH+AES256:SH+AES256:RSA+AESGCM256:RSA+AES256:!aNULL:!MD5:!kEDH';

    location / {
      proxy_pass https://127.0.0.1:19999; #netdata http server 
      proxy_buffering        on;
      proxy_cache            STATIC;
      proxy_cache_valid      200  1m;
      proxy_cache_use_stale  error timeout invalid_header updating http_500 http_502 http_503 http_504;
    }
    error_page 404 /404.html;
      location = /40x.html {
    }
    error_page 500 502 503 504 /50x.html;
      location = /50x.html {
    }
  }
}
```

**Comment by MrZammler** [comment]
Hi @marcelmfs 

Can you please forward the error.log of both the parent and the child to manolis@netdata.cloud ?

Thanks.

**Comment by ilyam8** [comment]
@MrZammler there are children of different version and some of them a pretty old. They don't support replication and gaps are expected if there are any problems (e.g. "buffer full (10485760-bytes) after 4020432 bytes. Restarting connection").

@marcelmfs I am confused about the problem:

 - the title said "parent isn't collecting metrics from any child".
 - in the description you say (and screenshots confirm that) that you have gaps.

> some dev servers have since lost internet access due to client on-premises restrictions

If possible, I suggest to download static build and install it. It can be very trick to find a problem (if any) when there are a lot of Agents with different old versions.

**Comment by marcelmfs** [comment]
Hi Ilya,

The graphs with gaps are from parent's netdata dashboard https://parent-ip/host/netdata-child-1 after downgrading both parent and child to v1.37.1.

The grafana screenshot is from the parent only.

The thing is that even with older versions of the agent running on the children all was fine up until a few days ago.

I'm in the process of converging all of the children to v1.37.1.

But remains to be tested why with only one child and one parent both running v1.40.0 with the parent behind Nginx TCP stream, the child still gets registered, it replays some metrics (I see the right navigation pane populated with lots of graphs, but the error:
```
2023-06-15 09:49:01: netdata ERROR : STATS_GLOBAL : STREAM netdata-child-1 [send]: not ready - collected metrics are not sent to parent.
```
Still shows and the child graphs aren't updated, with the child status set to OFF in the left navigation pane in the parent dashboard.

**Comment by marcelmfs** [comment]
@MrZammler I'll collect the relevant error.logs and send to you for the issue with v1.40.0.
