### ISSUE TITLE
[Bug]: After updating netdata, prometheus mysql_exporter metrics not collected

### ISSUE THREAD

**Issue by martin-fiedler** [netdata/netdata#15207]
### Bug description

Sadly I cant remember what netdata version I was on before I updated to v1.40.0 (but it was at least >1.30.0)

The metrics from the prometheus mysql_exporter are no longer collected, if I try to curl localhost:9104/metrics I get the metrics from the exporter I also checked the prometheus plugin via the troubleshooting section of this [guide](https://learn.netdata.cloud/docs/data-collection/apm/openmetrics-endpoints), but the logs show no errors.
```bash
bash-4.2$ ./go.d.plugin -d -m prometheus
[ DEBUG ] main[main] main.go:115 plugin: name=go.d, version=v0.53.2
[ DEBUG ] main[main] main.go:117 current user: name=netdata, uid=995
[ INFO  ] main[main] main.go:121 env HTTP_PROXY '', HTTPS_PROXY '' (both upper and lower case are respected)
[ INFO  ] main[main] agent.go:140 instance is started
[ INFO  ] main[main] setup.go:43 loading config file
[ INFO  ] main[main] setup.go:51 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:58 found '/etc/netdata/go.d.conf
[ INFO  ] main[main] setup.go:65 config successfully loaded
[ INFO  ] main[main] agent.go:144 using config: enabled 'true', default_run 'true', max_procs '0'
[ INFO  ] main[main] setup.go:70 loading modules
[ INFO  ] main[main] setup.go:89 enabled/registered modules: 1/79
[ INFO  ] main[main] setup.go:94 building discovery config
[ INFO  ] main[main] setup.go:141 looking for 'prometheus.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:157 found '/usr/lib/netdata/conf.d/go.d/prometheus.conf
[ INFO  ] main[main] setup.go:162 dummy/read/watch paths: 0/1/0
[ INFO  ] discovery[manager] manager.go:92 registered discoverers: [file discovery: [file reader]]
[ INFO  ] main[main] setup.go:176 looking for 'vnodes/' in [/etc/netdata /usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:188 found '/usr/lib/netdata/conf.d/vnodes' (0 vhosts)
[ INFO  ] discovery[manager] manager.go:97 instance is started
[ INFO  ] run[manager] run.go:32 instance is started
[ INFO  ] build[manager] build.go:117 instance is started
[ INFO  ] discovery[file manager] discovery.go:73 instance is started
[ INFO  ] discovery[file reader] read.go:41 instance is started
[ INFO  ] discovery[file reader] read.go:42 instance is stopped
[ DEBUG ] run[manager] run.go:43 tick 0
[ DEBUG ] run[manager] run.go:43 tick 1
```
The prometheus plugin is also enabled, checked via `sudo ./edit-config go.d.conf`
The conf for the prometheus plugin shows also the correct ports and addresses.

I left everything default installed the nightly build -> uninstalled -> installed the stable build -> same result

### Expected behavior

The metrics should be available in netdata as a graph in the ui and when requesting them via `1xxx.xxx.xxx.xxx:19999/api/v1/allmetrics?format=prometheus&source=as-collected`
like they where before.

### Steps to reproduce

1. install and configure mysql_exporter from prometheus
2. install netdata via the kickstart script

### Installation method

kickstart.sh

### System info

```shell
Linux ip-1xx-xxx-xxx-xxx.eu-central-1.compute.internal 4.14.314-238.539.amzn2.x86_64 #1 SMP Tue May 23 16:44:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Amazon Linux"
/etc/os-release:VERSION="2"
/etc/os-release:ID="amzn"
/etc/os-release:ID_LIKE="centos rhel fedora"
/etc/os-release:VERSION_ID="2"
/etc/os-release:PRETTY_NAME="Amazon Linux 2"
/etc/os-release:ANSI_COLOR="0;33"
/etc/os-release:CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
/etc/system-release:Amazon Linux release 2 (Karoo)
```

### Netdata build info

```shell
Version: netdata v1.40.0
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-bundled-protobuf' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-dependency-tracking' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Install type: binpkg-rpm
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

No errors in the netdata logs regarding problems with the prometheus plugin.

**Comment by ilyam8** [comment]
Hi, @martin-fiedler. Is mysql_exporter on a remote host? If so, it looks like you have no `prometheus.conf` in `/etc/netdata/go.d`. Or the file is not readable by `netdata` user.

**Comment by martin-fiedler** [comment]
Hi @ilyam8 , the mysql_exporter is on the same machine as netdata.
Where in the logs does it say it has problems loading the prometheus.conf ?
Is it because the `config successfully loaded` is missing after the prometheus.conf was found ?

**Comment by ilyam8** [comment]
it doesn't say it has problems, it just doesn't say the user config (in /etc/netdata) was found

```
[ INFO  ] main[main] setup.go:141 looking for 'prometheus.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:157 found '/usr/lib/netdata/conf.d/go.d/prometheus.conf
```

**Comment by martin-fiedler** [comment]
I have copied the folder to /etc/netdata, but no difference, also doesn't seem right to copy them over there when he found them in the default folder or at least the folders and files the installer gave me.
It looks like netdata only collect build in metrics, not a single external plugin works, I have fail2ban also installed and no metrics are collected.

Seems the installer is broken.

```
bash-4.2$ ./go.d.plugin -d -m prometheus
[ DEBUG ] main[main] main.go:115 plugin: name=go.d, version=v0.53.2
[ DEBUG ] main[main] main.go:117 current user: name=netdata, uid=995
[ INFO  ] main[main] main.go:121 env HTTP_PROXY '', HTTPS_PROXY '' (both upper and lower case are respected)
[ INFO  ] main[main] agent.go:140 instance is started
[ INFO  ] main[main] setup.go:43 loading config file
[ INFO  ] main[main] setup.go:51 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:58 found '/etc/netdata/go.d.conf
[ INFO  ] main[main] setup.go:65 config successfully loaded
[ INFO  ] main[main] agent.go:144 using config: enabled 'true', default_run 'true', max_procs '0'
[ INFO  ] main[main] setup.go:70 loading modules
[ INFO  ] main[main] setup.go:89 enabled/registered modules: 1/79
[ INFO  ] main[main] setup.go:94 building discovery config
[ INFO  ] main[main] setup.go:141 looking for 'prometheus.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:157 found '/etc/netdata/go.d/prometheus.conf
[ INFO  ] main[main] setup.go:162 dummy/read/watch paths: 0/1/0
[ INFO  ] discovery[manager] manager.go:92 registered discoverers: [file discovery: [file reader]]
[ INFO  ] main[main] setup.go:176 looking for 'vnodes/' in [/etc/netdata /usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:188 found '/usr/lib/netdata/conf.d/vnodes' (0 vhosts)
[ INFO  ] discovery[manager] manager.go:97 instance is started
[ INFO  ] build[manager] build.go:117 instance is started
[ INFO  ] run[manager] run.go:32 instance is started
[ INFO  ] discovery[file manager] discovery.go:73 instance is started
[ INFO  ] discovery[file reader] read.go:41 instance is started
[ INFO  ] discovery[file reader] read.go:42 instance is stopped
[ DEBUG ] run[manager] run.go:43 tick 0
[ DEBUG ] run[manager] run.go:43 tick 1
[ DEBUG ] run[manager] run.go:43 tick 2
[ DEBUG ] run[manager] run.go:43 tick 3

```

**Comment by ilyam8** [comment]
@martin-fiedler I'm out of ideas other than that something is wrong with your prometheus.conf. Have you made any modifications? If yes, can you show the content?

**Comment by martin-fiedler** [comment]
@ilyam8,
I didn't touch any configs
Just installed the newest version that's it.

Who else can be involved ?
As I don't know what can be done.

Left everything as is.
Installed with the script from the installation guide.
Worked before the update.

**Comment by gdoermann** [comment]
I have had the same issue, twice now I have had my vnodes.conf file overwritten (maybe on update?).

File: /opt/netdata/usr/lib/netdata/conf.d/vnodes/vnodes.conf

I have 12 vnodes setup in that file and it keeps getting cleared.  I checked it just now and it is back to the stock config:
```
## This file is in YAML format.
##
## It contains a list of virtual nodes. Virtual node, defined with the following parameters:
##
##  1. hostname
##     The hostname of the virtual node. String. Required.
##  2. guid
##     Uniquely identifies the node. String. Required.
##  3. labels
##     The virtual node host labels. Dictionary in the form key: value. Optional.
##     Special labels that are used to set virtual host system information:
##     https://learn.netdata.cloud/docs/improving-netdata---developers/external-plugins#host_label
##
## You can create GUIDs online: https://www.guidgen.com/
## or generate with the linux command: uuidgen
##
## ---------------------------------------------------------------------------------------------------------------------

#- hostname: HOSTNAME1
#  guid: GUID1
#
#- hostname: HOSTNAME2
#  guid: GUID2
```

Looking in the logs I found the following:
```
collector.log.1:2023-06-21 14:48:11: go.d INFO: main[main] found '/opt/netdata/usr/lib/netdata/conf.d/vnodes' (13 vhosts)
collector.log.1:2023-06-21 14:48:28: go.d WARNING: build[manager] couldn't build windows[OLDVNODE]: vnode 'OLDVNODE' is not found
collector.log.2.gz:2023-06-20 07:45:25: go.d INFO: main[main] looking for 'vnodes/' in [/opt/netdata/etc/netdata /opt/netdata/usr/lib/netdata/conf.d]
collector.log.2.gz:2023-06-20 07:45:25: go.d INFO: main[main] found '/opt/netdata/usr/lib/netdata/conf.d/vnodes' (0 vhosts)
collector.log.2.gz:2023-06-20 07:45:32: go.d INFO: main[main] looking for 'vnodes/' in [/opt/netdata/etc/netdata /opt/netdata/usr/lib/netdata/conf.d]
collector.log.2.gz:2023-06-20 07:45:32: go.d INFO: main[main] found '/opt/netdata/usr/lib/netdata/conf.d/vnodes' (0 vhosts)
collector.log.2.gz:2023-06-20 07:45:33: go.d WARNING: build[manager] couldn't build windows[MYVNODE]: vnode 'MYVNODE' is not found
```

So you can see there were 13 vhossts in the file at 2 pm yesterday - and then suddenly at 7:45 am this morning there are 0. No changes made to the server. 

The cron.daily ran about 30 min before that log message.

**Comment by gdoermann** [comment]
So, apparently you CAN edit the vnodes as a regular config file but the docs were not updated.  @martin-fiedler if you just create your vnodes using the edit-config script they will stick around!
```
sudo ./edit-config vnodes/vnodes.conf
```

**Comment by martin-fiedler** [comment]
In my case I didn't adjust the vnodes in the past, the machine is a single ec2 instance with mysql, netdata, fail2ban and mysql_exporter.
So I don't understand why vnodes would be needed or did I miss read/miss understood something ?

**Comment by martin-fiedler** [comment]
With a lot of uninstalling and installing and also delete everything that Netdata has created or touched removed.
I got the following error in the prometheus plugin 
`[ ERROR ] prometheus[mysqld_exporter_local] prometheus.go:89 'http://127.0.0.1:9104/metrics' num of time series (2060) > limit (2000) `

**Comment by martin-fiedler** [comment]
I fixed it.
If anyone encounters the same problem, check if you reaching any time series limit, for me 2000 was not enough for the mysql_exporter from prometheus.

`/etc/netdata/~ sudo ./edit-config go.d/prometheus.conf`
```yaml
jobs:
  - name: mysqld_exporter_local
    url: 'http://127.0.0.1:9104/metrics'
    max_time_series: 3000
```

**Comment by martin-fiedler** [comment]
Need to reopen this, as not all metrics are collected.
via `curl localhost:9104/metrics `I can see all metrics
Netdata itself only retrieves some of the metrics, all slave status metrics are missing in netdata ...etc

**Comment by martin-fiedler** [comment]
`mysql_slave_status_sql_delay` metrics like this are completely missing from netdata, but are available via the 127.0.0.1:9104 endpoint and Netdata does receive some metrics from the mysqld_exporter

**Comment by ilyam8** [comment]
> are available via the 127.0.0.1:9104 endpoint 

Can you upload a sample of metrics to https://pastebin.com/ and share the link?

**Comment by martin-fiedler** [comment]
@ilyam8 ,
metrics Netdata gets:
`curl http://45.XXX.XXX.XXX:19999/api/v1/allmetrics?format=prometheus&source=as-collected`
https://pastebin.com/JfHv0Pxv
metrics mysqld_exporter provides
`curl localhost:9104/metrics`
https://pastebin.com/vEYA9sX9

**Comment by martin-fiedler** [comment]
Can I configure something on my end or must there be a code change ?

**Comment by ilyam8** [comment]
> or must there be a code change

This. The problem with this approach we will be guessing if the metric is a counter or gauge. And if there is guessing involved there will be mistakes. But I think it is better than nothing.

**Comment by martin-fiedler** [comment]
Was that something that was changed ?
Because it worked before. (was a 1.3x version if I remember correctly)
Would maybe another approach be to allow in the job section besides filters and so on a set type for metrics matching regex be better or would that not be possible as the metrics are ignored before it even gets to the job part.

**Comment by martin-fiedler** [comment]
something like this
```yaml
jobs:
  # https://github.com/prometheus/prometheus/wiki/Default-port-allocations
  #  - name: node_exporter_local
  #    url: 'http://127.0.0.1:9100/metrics'
  - name: mysqld_exporter_local
    url: 'http://127.0.0.1:9104/metrics'
    max_time_series: 6000
    set_fallback_type:
      gauge:
        - mysql_slave_status_exec_master_log_pos
      counter:
        - ^mysql_slave.*retry_count
```

**Comment by ilyam8** [comment]
Hey, @gdoermann. Added [fallback_type](https://github.com/netdata/go.d.plugin/blob/c8435be88ae1530174171830587e751cd555fd63/config/go.d/prometheus.conf#L76C6-L86) in netdata/go.d.plugin#1225. Will be available in tomorrow's nightly.
