### ISSUE TITLE
[Bug]: No data from vsphere plugin showing on dashboard 

### ISSUE THREAD

**Issue by AlexeiKlimenko** [netdata/netdata#15228]
### Bug description

Good day.
Have deployed netdata on debian on-premises with script.
Info about VM with netdata in currently shown on dashboard. Then configured vsphere plugin, using debug mode we succeeded in information from vCenter is really obtaining and collecting (no ERR or WARN) but problem is that we're not able found out any information about vCenter on dashboard. 
Every click on dash (for instance "Node view") offers to Sign In to Netdata.
Is it really required to "Sign In" step just to show info about vcenter on dashboard on-prem? If not how to troubleshoot this issue? 

### Expected behavior

Info about vcenter is shown on dash.

### Steps to reproduce

1.
2.
3.
...
Look at bug description.

### Installation method

kickstart.sh

### System info

```shell
Linux msk-netdata 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.40.0
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -I/libnetfilter-acct-static/include/libnetfilter_acct -I/usr/include/libmnl -pipe' 'LDFLAGS=-static -L/openssl-static/lib -L/libnetfilter-acct-static/lib -lnetfilter_acct -L/usr/lib -lmnl' 'PKG_CONFIG=pkg-config --static' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig:/libnetfilter-acct-static/lib/pkgconfig:/usr/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO

We have case "netdata: command not found"
```

**Comment by AlexeiKlimenko** [comment]
Thanks for assistance,
Log is empty, it seems to me that we have manually execute this plugin somehow?

Previously we've configured plugin using /etc/netdata/go.d/vsphere.conf then checking with debug "/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin -d -m vsphere"

**Comment by ilyam8** [comment]
> Install type: kickstart-static

The static build has `/opt/netdata/` installation prefix, so it should be `/opt/netdata/etc/netdata/go.d/vsphere.conf`.


> Then configured vsphere plugin, using debug mode we succeeded in information from vCenter is really obtaining and collecting

Did you switch to `netdata` user? Can you show the debug output?

Also if it works in the debug mode it should work in normal mode too. If it doesn't:

 - ensure go.d.plugin process is running (ps aux | grep go.d.plugin)
 - if yes, then the only place to check is the collector.log

**Comment by AlexeiKlimenko** [comment]
1. /opt/netdata/etc/netdata/go.d/vsphere.conf also contains our vsphere config (/etc/netdata has been created via copying /opt/netdata)
2. We didn't switch to netdata user (debug was running under root). Does it matter?
3. "go.d.plugin" isn't running (not shown in ps). Perhaps this is a root cause. How to activate and run it properly?

**Comment by ilyam8** [comment]
>  (debug was running under root). Does it matter?

Yes, it does. Because the config file can be readable by `root` and not readble by `netdata`.

> "go.d.plugin" isn't running
> How to activate and run it properly?

It is enabled by default. 

- Check `grep go.d /opt/netdata/var/log/netdata/error.log`.
- also show `ps aux | grep netdata`

**Comment by AlexeiKlimenko** [comment]
Under netdata debug is failed with permission issue
`bash: /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin: Permission denied`

ps aux | grep netdata
`netdata     5196  0.8  2.0 342600 81588 ?        SNsl 15:04   0:22 /opt/netdata/bin/srv/netdata -P /run/netdata/netdata.pid -D
netdata     5199  0.0  0.0  20676  3936 ?        SNl  15:04   0:00 /opt/netdata/bin/srv/netdata --special-spawn-server
netdata     5386  0.0  0.0   1928  1484 ?        SN   15:04   0:01 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
root        5399  0.0  0.0   5120     4 ?        SN   15:04   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/nfacct.plugin 1
root        5402  0.0  0.1  49168  7388 ?        SNl  15:04   0:01 /opt/netdata/usr/libexec/netdata/plugins.d/ebpf.plugin 1
root        5591  0.0  0.0   6216   704 pts/0    S+   15:50   0:00 grep netdata`

ERROR.LOG
`2023-06-21 15:04:30: netdata INFO  : PD[go.d] : thread created with task id 5375
2023-06-21 15:04:30: netdata INFO  : PD[go.d] : set name of thread 5375 to PD[go.d]
2023-06-21 15:04:30: netdata INFO  : PD[go.d] : PLUGINSD: 'host:netdata' connected to '/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin' running on pid 5405
2023-06-21 15:04:30: netdata ERROR : PD[go.d] : PARSER: read failed: POLLHUP.
2023-06-21 15:04:30: netdata INFO  : PD[go.d] : PLUGINSD: 'host:netdata', '/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 5405) disconnected after 0 successful data collections (ENDs).
2023-06-21 15:04:30: netdata ERROR : PD[go.d] : child pid 5405 exited with code 126.
2023-06-21 15:04:30: netdata ERROR : PD[go.d] : PLUGINSD: 'host:netdata', '/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 5405) exited with error code 126 and haven't collected any data. Disabling it. (errno 22, Invalid argument)
2023-06-21 15:04:30: netdata INFO  : PD[go.d] : thread with task id 5375 finished`

**Comment by ilyam8** [comment]
Wait, did you do `ls -l /opt/netdata/usr/libexec/netdata/plugins.d/`? What were go.d.plugin ownership/permission before adjusting?

**Comment by AlexeiKlimenko** [comment]
Before adjusting permissions were
-rwxr-x--- 1 root me 62M Jun 13 13:08 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin

Also faced with another issue about status of vcsa (overall system health as described here - https://github.com/netdata/go.d.plugin/blob/master/modules/vcsa/README.md#global) is not shown. We're getting data per hosts and per VMs but not the overall status

**Comment by ilyam8** [comment]
Thanks, @AlexeiKlimenko. That is a (packaging) bug. I confirm it:

- (optional) delete `netdata` user if exists.
- install static build (stable or nightly, doesn't matter)
- check `plugins.d/*` files permissions. Some plugin don't work because of the wrong ownership

```
.rwsr-x--- 7.4M root cm      14 Jun 11:14 apps.plugin
.rwxr-x--- 8.8k root cm      14 Jun 11:14 cgroup-network-helper.sh
.rwxr-x---  20k root cm      14 Jun 11:14 charts.d.plugin
.rwsr-x--- 7.2M root cm      14 Jun 11:14 debugfs.plugin
.rwxr-x---  64M root cm      13 Jun  6:08 go.d.plugin
.rwxr-x--- 5.4k root cm      14 Jun 11:14 ioping.plugin
.rwxr-x--- 7.2M root cm      14 Jun 11:14 perf.plugin
.rwxr-x---  27k root cm      14 Jun 11:14 python.d.plugin
.rwxr-x--- 7.2M root cm      14 Jun 11:14 slabinfo.plugin
```

**Comment by AlexeiKlimenko** [comment]
ok, what about showing overall health status as mentioned here (https://github.com/netdata/go.d.plugin/blob/master/modules/vcsa/README.md#global) ?
