### ISSUE TITLE
[Feat]: add TARGET_INSTALL_VERSION to install telemetry events

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#15242]
### Problem

at the moment i think we have INSTALL_VERSION in the install telemetry events only when its passed as a flag. 

its would be good if instead we had something like TARGET_INSTALL_VERSION for all install events as that will be useful to ensure we can break out things like increase in install errors or failures etc by the target netdata version that was trying to be installed. 

### Description

add something like TARGET_INSTALL_VERSION to the event. 

or even maybe would be ok to try add INSTALL_VERSION even when not passed via the flags such that we, as much as possible, always have an idea of what netdata version was being installed by the script. 

### Importance

really want

### Value proposition

1. better ability to differentiate between installer issues that maybe are specific to different netdata versions etc since many users can be installing many different versions at the same time.
2.
3.
...

### Proposed implementation

@Ferroin does something like this make sense and seem feasible?

**Comment by Ferroin** [comment]
Actually doing this is not exactly trivial, as without an explicitly specified install version, we default to whatever the latest version is, and we don’t know what that is until relatively late in the install process.
