### ISSUE TITLE
[Bug]: Docker plugin charts from ephemeral containers never get cleaned up and leak memory

### ISSUE THREAD

**Issue by jaroslawr** [netdata/netdata#15268]
### Bug description

Charts generated by the docker plugin never disappear, even when the container they describe is long gone. Metrics collected by the cgroup plugin for the same container get cleaned up correctly.

### Expected behavior

Charts should be cleaned up correctly.

### Steps to reproduce

(I investigated this because of a production issue but describe a convenient local reproduction)

1. Configure netdata for eager metrics cleanup
``` 
[db]
        retention = 60
        cleanup obsolete charts after secs = 10
```
2. Start netdata
3. Run some ephemeral containers:
```
docker run --name test_$(date +%d_%m_%Y_%H_%M_%S) --rm ubuntu bash -c 'sleep 10'
```
4. See charts get created and never cleaned up:
```
curl -v -v localhost:19999/api/v1/allmetrics -o- 2>/dev/null | grep docker_local | grep container_test
# chart: docker_local.container_test_28_06_2023_11_47_05_state (name: docker_local.container_test_28_06_2023_11_47_05_state)
# chart: docker_local.container_test_28_06_2023_11_47_05_health_status (name: docker_local.container_test_28_06_2023_11_47_05_health_status)
# chart: docker_local.container_test_28_06_2023_11_47_07_state (name: docker_local.container_test_28_06_2023_11_47_07_state)
# chart: docker_local.container_test_28_06_2023_11_47_07_health_status (name: docker_local.container_test_28_06_2023_11_47_07_health_status)
# chart: docker_local.container_test_28_06_2023_11_47_08_state (name: docker_local.container_test_28_06_2023_11_47_08_state)
# chart: docker_local.container_test_28_06_2023_11_47_08_health_status (name: docker_local.container_test_28_06_2023_11_47_08_health_status)
...
```

I debugged this and I noticed two problems in the code:

1. In `daemon/service.c` in the method `svc_rrdset_archive_obsolete_dimensions` the following condition is never fulfilled preventing the charts from being cleaned up (https://github.com/netdata/netdata/blob/master/daemon/service.c#L93):
```
if(dictionary_acquired_item_references(rd_dfe.item) == 1) {
```

2. In the same file in the method `svc_rrd_cleanup_obsolete_charts_from_all_hosts` this part seems just wrong to me:
```
        if(rrdhost_flag_check(host, RRDHOST_FLAG_PENDING_OBSOLETE_CHARTS|RRDHOST_FLAG_PENDING_OBSOLETE_DIMENSIONS)) {
            rrdhost_flag_clear(host, RRDHOST_FLAG_PENDING_OBSOLETE_CHARTS|RRDHOST_FLAG_PENDING_OBSOLETE_DIMENSIONS);
            svc_rrdhost_cleanup_obsolete_charts(host);
        }
```
The problem with this is that the flags are cleared always, unconditionally, but svc_rrdhost_cleanup_obsolete_charts does not always suceed in cleaning up all obsolete charts because it uses a time based critertion to check for each chart whether to do the cleanup or not. It seems to me that the flags should be cleared only if svc_rrdhost_cleanup_obsolete_charts really did cleanup all obsolete charts, otherwise svc_rrdhost_cleanup_obsolete_charts has to keep running and rechecking if the obsolete chart cleanup timeout has passed or not. Currently old obsolete charts will get cleaned up only if new obsolete charts are generated all the time.

### Installation method

from git

### System info

```shell
Linux silentium 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="12"
/etc/os-release:VERSION="12 (bookworm)"
/etc/os-release:VERSION_CODENAME=bookworm
/etc/os-release:ID=debian
```

### Netdata build info

```shell
root@silentium:/home/work# netdata -W buildinfo
Version: netdata v1.40.0-34-g8b384e402
Configure options:
Install type: custom
Features:
    dbengine:                   NO
    Native HTTPS:               YES
    Netdata Cloud:              NO
    ACLK:                       NO
    TLS Host Verification:      YES
    Machine Learning:           NO
    Stream Compression:         NO
    HTTPD (h2o):                NO
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  NO
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
Step 4 (_See charts get created and never cleaned up:_) from OP is expected because we indeed don't delete them but archive them. Is this correct, @stelfrag?

Shouldn't we write the name of the diagram here if it has been archived?

https://github.com/netdata/netdata/blob/55016fd5104e0f296cda84763edfa90034077546/web/api/exporters/shell/allmetrics_shell.c#L39-L40
