### ISSUE TITLE
[Feat]: Support node stats for remote Elasticsearch clusters

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata#15263]
### Problem

The Elasticsearch collector currently only supports getting node statistics from the _local_ node, but not _all_ nodes at the same time. 

### Description

The collector uses the `/_nodes/_local/stats` API endpoint. For ES deployments where the Netdata Agent cannot be located on every ES node, API requests would be redirected to a proxy, causing one of the nodes to respond with its own local statistics, resulting in unrelated measurements. A prime example is Elasticsearch deployments in Elastic Cloud.

### Importance

must have

### Value proposition

1. Allows monitoring node statistics in remote Elasticsearch deployments.

### Proposed implementation

The suggestion is to let the user configure to either fetch the local stats (default) _or_ the stats for all nodes, similar to the Prometheus ES exporter. In the latter case, it would use the `/_nodes/stats` API.

For both modes, the response is structured the same, which each node represented by a mapping from _node_id_ to each node's statistics. In that structure, there's also a property for the human-readable `name`, which should be turned into a label.

Other useful labels include:

- `cluster_name` (from the top-level response body)
- `attributes` (these are ES node attributes as an object)
- `roles` (these probably have to be mapped to a label per role, only present when included in the array)

**Comment by ilyam8** [comment]
> attributes (these are ES node attributes as an object)

This will result in the same metrics with different labels, e.g.

```
elasticsearch.node_indices_indexing{logical_availability_zone="zone-0", availability_zone="us-east-1a", ...} 1
elasticsearch.node_indices_indexing{transform.node="true", ml.max_open_job="20", ...} 1
```

is that ok?

**Comment by ralphm** [comment]
What do you mean with _same metrics with different labels_? Is it a problem if this set of attributes is user defined and that the resulting labels may not always be present?

There is an [long pending PR](https://github.com/prometheus-community/elasticsearch_exporter/pull/266) that implements support for attribute labels in ES exporter. The idea is that, indeed, not all nodes in a cluster will have the same set of node attributes (hot/warm/cold tiers, AZs, etc.) and that this makes filtering possible.

The host label is a bit of an odd one. Ideally we'd have these metrics on virtual nodes, I suppose, but may be complicated (?). Let's just add them. The node name can be different from the host name and you can have multiple nodes on the same host, so that's needed, too.

As for node roles, I'm not sure why ES exporter limits them. Can we not just have `es_node_role_xxx`?

Cluster name is useful, too. Unfortunately, in Elastic Cloud, they are opaque IDs.
