### ISSUE TITLE
SPECS: Central netdata Health Monitoring Server

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#1527]
I plan to add a central netdata health server.

These are the high level requirements, as I think of them. Feel free to comment.

## each netdata

1. Each netdata will be configured to communicate with one netdata health server.

2. Each netdata will update the health server periodically, at fixed intervals (e.g. every 30 seconds).

3. Each netdata will propagate all alarm status changes to the health server, as they happen (i.e. immediately, without any hysteresis).

---

## the users

1. Users are known at the health server.

2. Each user should be able to set the alarm notification methods he/she likes for each alarm role, individual alarms, and alarm level (`CRITICAL`, `WARNING`, `CLEAR`).

   So, user A could say that he wants to receive emails for `dba` alarms, twilio messages for `sysadmin` alarms, no notification for `proxyadmin` alarms and especially for alarm `X` from host `H` a slack notification for warnings and a pagerduty notification if it is critical.

---

## the health server

1. The health server will maintain a small database for each of the servers it monitors.

2. The health server will send alarm notifications to users according to their settings. This means each alarm may notify many users with different settings each.

3. The health server will provide a dashboard featuring all netdata servers the user knows. So, a high level overview of all the netdata a user knows, will be available at the health server (each netdata could also provide a link on their dashboards).

4. The health server will provide the following additional alarms for all servers monitored:

   - server down/unreachable
   - server rebooted/restarted
   - netdata restarted

---

## Notes

1. As I see it, this central health monitoring system is highly related to the netdata registry. Probably the registry is best suited for this additional functionality.

2. I would really like to have this functionality available for everyone that has installed netdata, even for IoT devices, or single server installations. Like a **global public netdata health monitoring server** !

3. To understand my view: at some point in future I would love to have alarms configured from the users themselves, directly on the netdata dashboards. This will allow each user to have his/her own alarms, without bothering other users. So, netdata alarms could become **personalized** and completely dynamic.

**Comment by l2isbad** [comment]
Would be cool if we can chart 'health summary' on health monitoring server (number of monitored instances (in up, down state), number of alarms in WARN/CRIT state)).
it will be easy to do if there will be additional api calls (kinda returns all the currently raised alarms for all monitored instances).

**Comment by emagaliff** [comment]
This could be very helpful for #505

**Comment by ktsaou** [comment]
> This could be very helpful for #505

yes, it could! The only problem with ephemeral nodes is how the health server / registry will cleanup, to remove servers that are now offline.

**Comment by emagaliff** [comment]
I don't think they should automatically clean up - that should be up to a server administrator to do when needed. Servers can be down for a variety of reasons and triggering an automatic cleanup can remove servers that are only down temporarily.

**Comment by ktsaou** [comment]
You are right, but check #1311 for another view of the same problem... :)

**Comment by gamefundas** [comment]
@ktsaou I think as long as there is means to register and deregister through a REST API we should be good and most cloud infrastructures have instance creation and termination hooks. Alternately this can be scripted by using curl commands. 

I am yet to get working on the idea proposed in #1311 but love the fact that the concept of health server will eventually make things lot easier.

**Comment by paulkatsoulakis** [comment]
Forgive me if this is already in place partially or fully and i haven't spotted it yet:

Since we are going for a centralized health server, would be awesome if we can have server groups (custom "My Random Servers" and stock/automatic ones like "Web servers", "FTP Servers" etc) and then make alarms on the groups in various forms like for example "When X out of total servers in the group are down, alert" or "when X% of the servers in the group are down, alert" and so on.

**Comment by gmosx** [comment]
That's an interesting idea.

**Comment by cakrit** [comment]
A lot of this is coming in the new version of netdata.cloud. Closing it here.
