### ISSUE TITLE
[Bug]: go.d snmp stopped fetching data from device

### ISSUE THREAD

**Issue by nikobearrr** [netdata/netdata#15316]
### Bug description

I have a device named `host333` which has been running for a while (uptime 2y+) and I have been using the old snmp and then the new (go.d) snmp to monitor it. So far I have not had any issue with that. However, since yesterday only a number of OID/charts are being able to be collected. Nothing has changed in the netdata configuration/version and/or the device configuration/version.

### Expected behavior

I should be able to collecta all SNMP/OID as specified

### Steps to reproduce

So the issue becomes even more strange because I have a yaml file with the snmp config looking similar to this:

```

update_every: 10
autodetection_retry: 0
priority: 70000
jobs:
  - name: host333
    update_every: 10
    hostname: "host333"
    charts:

      - id: "status"
        units: "status"
        family: "status"
        title: "Status"
        dimensions:
          - name: "system"
            oid: "1.3.6.1.4.1.11.2.6.0"
```

With not that many more items to be collected (compared to some of my other jobs).

If I only leave this one - it works. However, when I have the full amount of OIDs then it won't work and goes with the error:

```
[ DEBUG ] snmp[host333] collect.go:49 skipping OID '1.3.6.1.4.1.11.2.6.0' (unsupported type 'NoSuchInstance')
```

at the exact same time as this is printed I can snmpwalk it and get the OID data

```
user@server:~$ snmpwalk -v 2c -c public host333 1.3.6.1.4.1.11.2.6.0
iso.3.6.1.4.1.11.2.6.0 = INTEGER: 3
```

When I have my full configuration it will fetch only some. A lot of them it won't fetch. And it literally stopped working overnight. No idea what could have happened. I use the snmp of go.d to monitor many more things and they all work fine.

### Installation method

docker

### System info

```shell
user@server:~$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux server 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
user@server:~$
```

### Netdata build info

```shell
bash-5.1$ netdata -W buildinfo
Version: netdata v1.38.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
bash-5.1$
```

### Additional info

I run the snmpwalk on the same host as the netdata docker runs.

**Comment by nikobearrr** [comment]
Actually I found out what is wrong but it doesn't really make sense. Maybe it makes sense in the internals of the go.d snmp plugin. But here is the actual issue:

I have some temperature stats from `controller1` and `controller2`. #1 has 10 metrics and #2 has 5. The metrics for controller #1 are something like `1.1.1.x.x.x.x.ZZZZ.y.y` and for #2 they are `1.1.1.x.x.x.x.ZZZZ.y.y` where the `ZZZZ` is either `1` or `2`. However, it seems like the controllers have switched roles (first time I see this) and now controller1 has 5 metrics but controller2 has 10 metrics. Thus I was trying to fetch invalid OIDs. But the one above `1.3.6.1.4.1.11.2.6.0`  which I was trying to get existed and still exists. So I would expect that it should be fetched.

Let me know if I should keep or close this issue.

**Comment by ilyam8** [comment]
Hi, @nikobearrr. 

- go.d/snmp queries all OIDs set in the configuration file on every data collection.
- [collects all counter variables in response](https://github.com/netdata/go.d.plugin/blob/0acad928d9f67af4d077965bca87e132a233376b/modules/snmp/collect.go#L37-L49) and it skips everything that is not a counter (including "NoSuchInstance").

> at the exact same time as this is printed I can snmpwalk it and get the OID data

I'm not sure how/why this happens. As you can see the code is pretty simple (uses [github.com/gosnmp/gosnmp](https://github.com/gosnmp/gosnmp) package): 
- [do snmp.Get for every max_request_size OIDs](https://github.com/netdata/go.d.plugin/blob/0acad928d9f67af4d077965bca87e132a233376b/modules/snmp/collect.go#L19-L26).
- read the response.

The response contains the same number of variables as the number of OIDs requested, and in the same order - probably this wasn't true in your case (just a guess).

Unfortunately, I don't know how to solve this problem because it's not reproducible.
