### ISSUE TITLE
[Bug]: Disk space utilization alarms not triggered for MonetDB partition

### ISSUE THREAD

**Issue by Garahk** [netdata/netdata#15391]
### Bug description

Based on the discussion #13425 I've configured my helm chart to moun the entire `/` so that all mounted units are shown in netdata's disks section. Thus I now have the following units:

![image](https://github.com/netdata/netdata/assets/99432183/64c25b0d-e0af-4e39-9516-5b01bdbbb933)

Am testing the thresholds of the disks.conf alarm file, in such a way that the warning threshold is very low, this in order to see whether all mounted units trigger an alarm. During this process I noted that only certain units trigger an alarm if beyond the threshold. The below example happens with the partition MonetDB

![image](https://github.com/netdata/netdata/assets/99432183/3d456952-5c70-4cd7-a463-20b6674d2942)

I modified an alarm, nothing complex, just tweaked the thresholds:

```
 template: disk_space_usage_custom
       on: disk.space
    class: Utilization
     type: System
component: Disk
       os: linux freebsd
    hosts: *
 families: !/dev !/dev/* !/run !/run/* *
     calc: $used * 100 / ($avail + $used)
    units: %
    every: 1m
     warn: $this > (($status >= $WARNING ) ? (2) : (15))
     crit: $this > (($status == $CRITICAL) ? (15) : (98))
    delay: up 1m down 15m multiplier 1.5 max 1h
     info: disk ${label:mount_point} space utilization
       to: sysadmin
```

However as seen in the previous screenshot, there's no alarm triggered.
 

### Expected behavior

Get an alarm for any disk's usage gone above the threshold

### Steps to reproduce

1. Modify the helm chart to mount all in `\`
2. Create a custom alarm and lower the thresholds to test alert in all mounted units
3. Execute netdatacli reload-health and verify the alarms
...

### Installation method

helmchart (kubernetes)

### System info

```shell
Linux <server_name> 3.10.0-1160.76.1.el7.x86_64 #1 SMP Tue Jul 26 14:15:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.9 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.9"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
/etc/system-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

### Netdata build info

```shell
Version: netdata v1.38.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment]
Hi, @Garahk. The alarm values are lower than the warning threshold (either 15 or 90). I think you got confused with the conditional operator, see [docs](https://learn.netdata.cloud/docs/alerting/health-configuration-reference#special-use-of-the-conditional-operator).

**Comment by Garahk** [comment]
> Hi, @Garahk. The alarm values are lower than the warning threshold (either 15 or 90). I think you got confused with the conditional operator, see [docs](https://learn.netdata.cloud/docs/alerting/health-configuration-reference#special-use-of-the-conditional-operator).

Oh I see, thought I had understood the conditional operator, apologies, and thank you for the guidance.
