### ISSUE TITLE
[Feat]: Let alert history be queryable / log alerts to file

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/netdata#15399]
### Problem

Hi thanks for the tool, I wonder whether we can let alert history be queryable / log alerts to file? Because for those non-important alerts, blogs like https://docs.google.com/document/d/199PqyG3UsyXlwieHaqbGiWVa8eMWi8zzAn0YfcApr8Q/edit and https://www.datadoghq.com/blog/monitoring-101-alerting/ suggest me to only record it instead of immediately fire a notification.

I guess one way is that, I can use custom endpoint to write to a file, and then create another container (I am using k8s) to tail that file.
However, given that this looks like a frequent feature, I wonder whether there are built-in ways?

### Description

-

### Importance

really want

### Value proposition

1.
2.
3.
...

**Comment by fzyzcjy** [comment]
@MrZammler Hi thanks for the information, it looks promising, I will have try!

**Comment by MrZammler** [comment]
Closing this, @fzyzcjy if you need something more, please let us know!
