### ISSUE TITLE
[Feat]: Monitor remaining file descriptors

### ISSUE THREAD

**Issue by withinboredom** [netdata/netdata#15411]
### Problem

As filed [on the helm chart repo](https://github.com/netdata/helmchart/issues/372), (some aspect) of netdata can repeatedly open files in an infinite loop. It appears netdata doesn't monitor this, so it can [silently corrupt data](https://withinboredom.info/2023/07/15/how-to-kill-a-kubernetes-cluster-in-one-easy-step/) on the node.

### Description

Monitor and alarm by default if a node is close to using all available file descriptors.

Currently, it only shows how many files are open per application, but doesn't show how close it is to being 'too much.'

### Importance

must have

### Value proposition

1. Most software doesn't know how to properly handle being out of file descriptors (a very rare event).
2. Software that handles it incorrectly, behaves erratically.

**Comment by thiagoftsm** [comment]
Hello @withinboredom ,

I loved your idea.
Netdata already monitors files that are open and closed per process, but right now we are grouping them by apps group.
We are right now modifying our eBPF.plugin to expose more detailed information about processes we are monitoring, the first thread to be modified will be sockets and I am pinging our product team (ping @shyamvalsan and @sashwathn ) to study this useful suggestion.

Best regards!

**Comment by ktsaou** [comment]
Nice idea @withinboredom !

PR #15417 adds this functionality to apps.plugin.

**Comment by ktsaou** [comment]
PR #15417 adds also the ability to monitor the global file descriptors used by the system
