### ISSUE TITLE
[Feat]: Build optimization for netdata native packages

### ISSUE THREAD

**Issue by tkatsoulas** [netdata/netdata#15436]
### Problem

Following up on the https://github.com/netdata/netdata/issues/15338

### Description

We want also to include optimization flags for the native packages. 

### Importance

nice to have

### Value proposition

1. Smaller native packages
2. Performance increase of the Agent

**Comment by tkatsoulas** [comment]
Closed by https://github.com/netdata/netdata/pull/15381

**Comment by ilyam8** [comment]
Fixed in #16641. We don't need an issue for native after the CMake PR (because all builds don't have optimizations/hardening options).
