### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by robtoll** [netdata/netdata#15439]
### Bug description

Centos 7, apache 2. install doesn't work, then uninstall doesn't work.
This process used to be smooth and easy, now it doesn't work at all.
I have 3 centos servers. Had real trouble getting 1 of them setup recently, but got through it after hours of messing about.
Today I tried to get it setup on another centos, and I'm hitting issues again.
I'm looking for an alternative now because I can't rely on NetData any more.

### Expected behavior

I expect the installer and uninstaller to work. both fail. Centos 7, apache 2

### Steps to reproduce

1. run the install;er.
2. run the uninstaler

### Installation method

kickstart.sh

### System info

```shell
(Y)
```

### Netdata build info

```shell
(Y)
```

**Comment by robtoll** [comment]
heres a dump of some data for you. I don't have time to persue this any further I'm afraid. perhaps this info will help.
It just doesn't install and work smoothly like it did before. and it won't unintsll after that. very frustrating...


[t@localhost ~]$ sudo systemctl restart netdata
Job for netdata.service failed because the control process exited with error code. See "systemctl status netdata.service" and "journalctl -xe" for details.
[t@localhost ~]$ sudo systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/usr/lib/systemd/system/netdata.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2023-07-18 13:04:11 UTC; 12s ago
  Process: 63234 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=217/USER)

Jul 18 13:04:11 localhost systemd[1]: netdata.service: control process exited, code=exited status=217
Jul 18 13:04:11 localhost systemd[1]: Failed to start Real time performance monitoring.
Jul 18 13:04:11 localhost systemd[1]: Unit netdata.service entered failed state.
Jul 18 13:04:11 localhost systemd[1]: netdata.service failed.
[t@localhost ~]$ wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --uninstall
--2023-07-18 13:04:46--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 104.21.13.159, 172.67.156.192, 2606:4700:3031::6815:d9f, ...
Connecting to my-netdata.io (my-netdata.io)|104.21.13.159|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

    [ <=>                                                                                                                                                                                                ] 84,354      --.-K/s   in 0.008s

2023-07-18 13:04:46 (10.1 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [84354]


 --- Using /tmp/netdata-kickstart-pNYMsHTIcq as a temporary directory. ---
 --- Checking for existing installations of Netdata... ---
 --- Downloading netdata-uninstaller ... ---
[/tmp/netdata-kickstart-pNYMsHTIcq]$ /usr/bin/curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-pNYMsHTIcq/netdata-uninstaller.sh https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-uninstaller.sh
 OK

[/tmp/netdata-kickstart-pNYMsHTIcq]$ sudo /tmp/netdata-kickstart-pNYMsHTIcq/netdata-uninstaller.sh --yes
/tmp/netdata-kickstart-pNYMsHTIcq/netdata-uninstaller.sh: line 711: /etc/netdata/.environment: No such file or directory

Tue Jul 18 13:04:47 UTC 2023 : FATAL: netdata-uninstaller.sh: FAILED TO UNINSTALL NETDATA:  Failed to completely remove Netdata from this system.
 FAILED

Finished uninstalling the Netdata Agent.The following non-fatal warnings or errors were encountered:

  - Command "sudo /tmp/netdata-kickstart-pNYMsHTIcq/netdata-uninstaller.sh --yes" failed with exit code 1.

Root privileges required to run rm -rf /tmp/netdata-kickstart-pNYMsHTIcq
[/home/t]$ sudo rm -rf /tmp/netdata-kickstart-pNYMsHTIcq

**Comment by ilyam8** [comment]
@robtoll you seem to have installed Netdata. What is the problem - Netdata doesn't work or you can't uninstall it?
