### ISSUE TITLE
[Bug]: Automatically add the license of the web gui v2

### ISSUE THREAD

**Issue by tkatsoulas** [netdata/netdata#15454]
### Bug description

For the release we manually hardcoded the license https://github.com/netdata/netdata/pull/15453, this should be automated by `bundle_dashboard_v2.py` script

**Comment by ilyam8** [comment]
I think the fact that we had no web/gui/v2/LICENCE.md means that this file was not in the [agent.tar.gz](https://github.com/netdata/netdata/blob/d790c0d2f509ccc9203ccf6e95e41bc73be79d54/web/gui/bundle_dashboard_v2.py#L23).
