### ISSUE TITLE
[Bug]: Dimension templates do not seem to work.

### ISSUE THREAD

**Issue by aldem** [netdata/netdata#15472]
### Bug description

Looks like dimension templates in alarms do not seem to work as documented.

I used the following example from the the [documentation](https://learn.netdata.cloud/docs/alerting/health-configuration-reference#using-a-netdata-simple-pattern-in-foreach):

```
 alarm: app_cpu
    on: apps.cpu
lookup: average -10m percentage foreach *
 every: 1m
  warn: $this > 50
  crit: $this > 80
```

According to the documentation, _This entity will now create alarms for every dimension in the apps.cpu chart._ - however, this is not the case - it creates a single alarm and explicitly describes it as `db lookup | average of *all values* , of chart apps.cpu, starting 30 secs ago and up to now, with options percentage.` , like there is no `foreach *` at all.

### Expected behavior

Sure I would expect it to work as documented, i.e. such an alarm defintion will create one alarm for every dimension in a chart.

### Steps to reproduce

1. Create an alarm as above
2. Look at the alarm definitions in dashboard

### Installation method

kickstart.sh

### System info

```shell
The behavior is system independent, it is the same across different kinds of systems.
```

### Netdata build info

```shell
I tried versions from 1.39.0 to 1.41.0 - it does not work in any, thus I believe that exact build data is irrelevant.
```

**Comment by ilyam8** [comment]
Hi. Use 'template' instead of 'alarm'.

**Comment by andrewm4894** [comment]
I guess we need to update the docs here 

https://learn.netdata.cloud/docs/alerting/health-configuration-reference#using-a-netdata-simple-pattern-in-foreach

I was not aware of any difference between using 'alarm' and 'template' so if there is one for some reason we should update the docs (I can do once I understand it).

**Comment by ilyam8** [comment]
> I was not aware of any difference between using 'alarm' and 'template' 

You can find it in the [health reference doc](https://learn.netdata.cloud/docs/alerting/health-configuration-reference#alarm-line-on) if interested.

**Comment by aldem** [comment]
Indeed, it works when I use `template`. Then this is not a bug but a documentation problem.
