### ISSUE TITLE
[Bug]: Database lookups on parent nodes produce incorrect results

### ISSUE THREAD

**Issue by aldem** [netdata/netdata#15482]
### Bug description

Looks like when using streaming with the most recent v1.41 alarms configured on parent use incorrect calculation on db lookups - in particular, the value fetched from the database seems to be divided by number of childs.

I have one parent and one child, both were upgraded to 1.41 recently, and while testing I noticed that one of my alarms is not producing alert when it should.

Configuration of both instances is equal, both use local db & alarm processing, the only difference in configuration is that the child streams to the parent.

The test was with apps.cpu alarm:

```
   alarm: app_cpu
      on: apps.cpu
  lookup: average -30s percentage
   every: 5s
    warn: $this > 75
    crit: $this > 90
```

Normally it would produce an alert on a parent when I run something CPU consuming (like `openssl speed rsa`) as single CPU is used for 100%, and it works like expected in v1.39.1, but in v1.41.0 there is no alarm as its calculated value is about 50% only when I check it on the parent.

Running `openssl speed -multi 2 rsa` on the parent actually triggered the alarm as the CPU usage jumped to 200% - this triggered the alarm but its value was about 100% (while the actual usage was about 200%).

Making CPU load on the child didn't contribute to calculation though - the value of parent's alarm didn't change at all, though it triggered the alarm on the child (as expected) and it was visible in `Events`.

I could not find any hints about this behavior in the documentation thus I consider it a bug, especially taking into account that it works as expected in preceding version.

### Expected behavior

Database lookups in alarms should use actual values for a single node.

### Steps to reproduce

1. Create two instances with equal configuration, both should use local db (dbengine) and alarm processing
2. Make one of the streaming to the other
3. Define alarm for apps.cpu (it is easy to test)
4. Make 100% CPU load on the parent and see what happens with alarms

### Installation method

kickstart.sh

### System info

```shell
I doubt this is relevant but I will provide it if necessary.
```

### Netdata build info

```shell
v1.41.0 stable
```

### Additional info

Maybe this is actually desired or planned behavior starting with v1.41 (aggregation/averaging of values from all nodes) but anyway it does not work as one would expect and if it did it should not be the default. And there should be a way to configure alarms in a way that only single node data is considered.

**Comment by ilyam8** [comment]
Hi, @aldem. I think you don't need the `percentage` option in the alarm.

**Comment by aldem** [comment]
@ilyam8 On v1.39.1 it works as expected with `percentage` set, though it behaves strange - it does not matter if I have one or more processes running - it is always around 100%.

Regardless of this, I would say that this a bit counter-intuitive behavior - alarm set for specific dimension on specific host is not expected to count other hosts, or I am wrong? But even if it does, then why I don't the child's "contribution" to this metric?

**Comment by ilyam8** [comment]
It behaves according to [docs](https://learn.netdata.cloud/docs/rest-api/netdata-badges)

> **percentage**, instead of returning the value, calculate the percentage of the sum of the selected dimensions, versus the sum of all the dimensions of the chart. This also sets the units to %.

The sum of all is 100% if using `percentage`.

**Comment by aldem** [comment]
And the "all" is...?

**Comment by ilyam8** [comment]
The sum of all dimensions. This is your example


```
   alarm: app_cpu
      on: apps.cpu
  lookup: average -30s percentage
   every: 5s
    warn: $this > 75
    crit: $this > 90
```

The value will be 100%.

**Comment by aldem** [comment]
Ok, lets' do it for one specific dimension. I created a process group for openssl (`openssl: openssl`) and two "dedicated" alarms (all this on v1.41.0 stable instance):

```
   alarm: openssl_cpu
      on: apps.cpu
  lookup: average -30s unaligned of openssl
   units: %
   every: 5s
    warn: $this > 60
    crit: $this > 90

   alarm: openssl_cpu_perc
      on: apps.cpu
  lookup: average -30s unaligned percentage of openssl
   units: %
   every: 5s
    warn: $this > 60
    crit: $this > 90
```

Now I run `openssl speed rsa` and check alarms in 60s. First one (without `percentage`) is producing expected value close to 100%, but the second one - close to 70% (and it is stable over time). Sum or not, now we have _one_ dimension thus both must be equal (within 1-2% at least), or do I get it wrong?

And now lets runs openssl with 2 processes: `openssl speed -multi 2 rsa`, wait 60 seconds... Well-well, the first one is producing expected value close to 200%, but the second one - only 85%.

Now the question is - do I get it wrong or there is a real problem?

**Comment by ilyam8** [comment]
`percentage of` is always within 0-100%, because of how it works 

> percentage, **instead of returning the value**, calculate the percentage of the sum of the selected dimensions, versus the sum of all the dimensions of the char

**Comment by aldem** [comment]
Oh. _Now_ I got it, thank you (for patience too)! :)

**Comment by aldem** [comment]
It is the "versus" part that lead me to think that those two entities are unrelated.

Perhaps it would be more clear to document it as "calculate the percentage of the sum of the selected dimensions relative to the sum of all dimensions in the chart."

**Comment by ilyam8** [comment]
@aldem you are right, updated the description in #15492
