### ISSUE TITLE
[Bug]: When alarm or template does not have "class" attribute dashboard's Alerts tab fails with "oops"

### ISSUE THREAD

**Issue by aldem** [netdata/netdata#15489]
### Bug description

I had an alarm which had no "class" attribute set and it led to "oops" in the new dashboard: "Oops, something unexpected happened!". Most (if not all) shipped alarms have it thus this kind of problem is hard to notice.

According to the documentation this attribute is not required, and its absence made no issues (visible at least) in v1 dashboard, though after inspecting the browser console I found periodic errors repeating every few seconds while alarms are open:

![image](https://github.com/netdata/netdata/assets/754722/6fa74e81-8635-4f19-8dfc-ea6c0364cc36)

v2 dashboard also shows couple errors but then just oops:

![image](https://github.com/netdata/netdata/assets/754722/76f87fb5-1955-4d30-818d-3ea6556e8ec9)

Both messages are from Microsoft Edge's console (most recent).

### Expected behavior

Either "class" attribute must be described as required or default value must be assigned so dashboard works without issues.

If it is actually required then probably netdata must not start at all if some alarms do not have it.

### Steps to reproduce

1. Create alarm which has no "class" attribute.
2. Trigger it and wait while it is raised.
3. Open Alerts tab in v2 and see what happens.
4. Open alerts in v1 and check the browser console.
...

### Installation method

kickstart.sh

### System info

```shell
Irrelevant
```

### Netdata build info

```shell
v1.41.0 stable
```

### Additional info

I also tried Firefox (113.0.1) - the error is reproducible too though in Firefox produces different messages in v2 and no messages in v1.

While in v1 it makes no harm (just cluttering the console and probably leaking some RAM while alerts are opened in Edge), v2 Alerts tab is just unusable while any alarm without "class" is raised.

**Comment by aldem** [comment]
Looks like if `to:` is not speicified (also not marked as required) it fails too.

**Comment by nodiscc** [comment]
I can confirm this bug on netdata 1.41.0 installed from packagecloud/.deb packages

![image](https://github.com/netdata/netdata/assets/3950390/2ded3ba6-03b1-463f-9769-610c5854171f)

The workaround mentioned by @aldem (ensure that all alarm definitions have `class:` and `to:` attributes) fixed the problem for me (thank you!). The documentation at https://learn.netdata.cloud/docs/alerting/health-configuration-reference#entity-format states that these attributes are not required, which is currently incorrect.

**Comment by ilyam8** [comment]
Fixed in [ui v6.23.0](https://github.com/netdata/netdata/pull/15629)
