### ISSUE TITLE
[Bug]: app.socket dashboard has suddenly stopped working

### ISSUE THREAD

**Issue by martinohubble** [netdata/netdata#15523]
### Bug description

app.socket dashboard has suddenly stopped working

### Expected behavior

display number of sockets

### Steps to reproduce

1.

### Desktop

OS: Windows 11	
Browser Edge	
Browser Version 114.0.1823.86

**Comment by hugovalente-pm** [comment]
@martinohubble could you provide some extra details please?

1. Installation method
>Select installation method you used.
> Describe the method in the "Additional info" section if you chose "other".
![image](https://github.com/netdata/netdata/assets/82235632/ede7dfa1-31b9-4f31-8cb5-8c2f17c34885)

2. System info
> Provide information about your system. To get this information, execute one of the following commands based on your OS:
```
# Linux
uname -a; grep -HvE "^#|URL" /etc/*release
# BSD
uname -a; uname -K
# macOS
uname -a; sw_vers
```

**Comment by hugovalente-pm** [comment]
Also noticed that in our documentation on https://learn.netdata.cloud/docs/data-collection/apm/application-monitoring#application-badges we have some badges and there are some _broken_ badges there where one is **Open Sockets (apps.sockets)**

![image](https://github.com/netdata/netdata/assets/82235632/dd640dc1-d99f-4e85-9fe9-a0e152f56126)

**Comment by hugovalente-pm** [comment]
looking more into this and correlating this with the [Netdata Detects FDs Leaking](https://github.com/netdata/netdata/releases/tag/v1.41.0#v1410-netdata-apps) mentioned on v1.41.0 it seems we introduced new charts that replace those:
* Apps Open Sockets • apps.fds_sockets
* Apps Open Files • apps.fds_files
* Apps Pipes • apps.fds_pipes

let's see if someone from the @netdata/agent confirms

**Comment by ilyam8** [comment]
> we have some badges

Chart ids/families were changed in #15437. All apps fds metrics are in "Applications->fds" now.

**Comment by ilyam8** [comment]
`apps.socket` is `apps.fds_sockets` in the latest.
