### ISSUE TITLE
[Bug]: C++14 as the minimun support version for netdata

### ISSUE THREAD

**Issue by tkatsoulas** [netdata/netdata#15552]
### Bug description

During the period of  [Last CI checks of this PR#14692](https://github.com/netdata/netdata/pull/14692), time we merged it there was a development with  the tumbleweed protobuf packages (they have a more aggresive policy on shipping latest packages than other distros).  The new packages are [c++14]( https://github.com/protocolbuffers/protobuf/blob/main/cmake/README.md#c-version) or even c++14> compatible.  At the moment our minimum required version to compile netdata is c++11. We need to enforce this requirements because protobuf is a core component in the Agent.  Tumbleweed was the first distro that we faced this limitation but rest assured wont be the only and can't estimate a timeline, that's why placing this as high priority.  

### Installation method

from source

**Comment by ilyam8** [comment]
@tkatsoulas is it still a problem? If yes, what would be the fix? I see the issue has high-priority labels but there have been no developments.

**Comment by Ferroin** [comment]
Actually, this is resolved now.
