### ISSUE TITLE
[Feat]: Dashboard v2 trough H2O

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#15663]
### Problem

Dashboard v2 seems not working with h2o webserver. H2o was probably forgoten or ignored during dashboard v2 development.

### Description

...

### Importance

must have

### Value proposition

1. We need feature parity with h2o and in future take it more seriously otherwise h2o will always be lagging behind feature wise and thus will never be able to become main webserver.
2.
3.
...

**Comment by diizzyy** [comment]
Out of curisity, can't this be done in another without bundling 3rd party software which would help packaging a lot and also reduce work on your end?

**Comment by underhood** [comment]
@diizzyy i am sorry but I do not get what exactly you are asking for? Do you mean another library (alternative to h2o?)

**Comment by diizzyy** [comment]
I'm not sure if it would be viable from a design point of view but perhaps a module for an external webserver or at least link h2o externally?
