### ISSUE TITLE
[Bug]: PROCFILE: Cannot open file '/host/proc/pressure/irq' (errno 2, No such file or directory)

### ISSUE THREAD

**Issue by pwsnla** [netdata/netdata#15729]
### Bug description

I started getting hundreds of "PROCFILE: Cannot open file '/host/proc/pressure/irq' (errno 2, No such file or directory)" in netdata logs.

I am running Netdata Agent v1.41.0-272-nightly  (docker) on Ubuntu 22.04.02 LTS

Is there a way to fix this or at least prevent this error from logging short  of disabling /proc/pressure altogether?
Docs only mention cpu,memory,io for /proc/pressure and those directories I have on my host and netdata is collecting them. Not sure what do about the irq. 

### Expected behavior

No error messages logged for /host/proc/pressure/irq as it's not available.

### Steps to reproduce

1.
2.
3.
...

### Installation method

docker

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.2 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
v1.41.0-272-nightly
```

**Comment by ilyam8** [comment]
Hey, @pwsnla. Pressure IRQ was added in https://lwn.net/Articles/902016/ (21 Jul 2022) to the Linux kernel. You are right, those are not errors and we shouldn't log them.

**Comment by pwsnla** [comment]
> Hey, @pwsnla. Pressure IRQ was added in https://lwn.net/Articles/902016/ (21 Jul 2022) to the Linux kernel. You are right, those are not errors and we shouldn't log them.

Hi @ilyam8 . Thank you for the quick reply! It would great to suppress these messages. Currently this condition generates two lines of text every 2-3 seconds, so it's a lot of spam in the log file.
