### ISSUE TITLE
[Feat]: By default all the netdata local dashboard to be password protected

### ISSUE THREAD

**Issue by tkatsoulas** [netdata/netdata#15740]
### Problem

We serve a decent amount of information at the moment for a system in the local dashboard. I think that the local webserver should be password-protected out of the box.

### Importance

nice to have

### Value proposition

1.
2.
3.
...

### Proposed implementation

Suggested workflow:

1. During installation; after a successful installation the last message could be something like

```
Now you can monitor your server via the app.netdata.cloud  (if claimed) or via the local dashboard

localhost:19999 or <IP_of_binded_interface>|<public_IP>:19999 

default_username: netdata
default_password: <uuid_gen>
```

2. You can also `netdatacli print-webserver-info` to receive a similar message.

**Comment by ktsaou** [comment]
@tkatsoulas how this will help the distributed nature of netdata?

Netdata is not one server. Is dozens, hundreds, or thousands or servers. 

And what will happen about multiple users?

And how users are going to manage the passwords when a team member leaves?

This is a problem Netdata cloud should solve. You connect the agents to the cloud and the cloud does all user management, like an oauth provider for all the agents you have.
