### ISSUE TITLE
[Bug]: Can't upgrade from v1.38.0-333-nightly even after complete uninstall+reinstall on Ubuntu 18.04

### ISSUE THREAD

**Issue by josephrocca** [netdata/netdata#15756]
### Bug description

I've been getting an error in the netdata cloud dashboard telling me to upgrade the netdata version on one of my machines. I checked the version and it's `netdata v1.38.0-333-nightly`. So I tried the [one-line update](https://learn.netdata.cloud/docs/maintaining/update-netdata-agents#updates-for-most-systems) command, and upon checking the version again, it hadn't changed. So I tried the one-line reinstall command, and that didn't increase the version either. So I then completely uninstalled it with the one-line uninstall command, and confirmed that `netdata` didn't exist anymore. I rebooted the machine, and then ran the one-line install command, and once again, it installed `netdata v1.38.0-333-nightly`.

The dashboard still complains that I should be on v1.39.1

### Expected behavior

Update/reinstall and uninstall+install should update to latest version.

### Steps to reproduce

Seems like this is a very specific and weird problem related to upgrading from an old version. Not sure how minimally-reproducible it is.

### Installation method

kickstart.sh

### System info

```shell
Linux insecure-mongodb-sfo2 4.15.0-197-generic #208-Ubuntu SMP Tue Nov 1 17:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.1 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.1 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

### Netdata build info

```shell
Version: netdata v1.38.0-333-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

IIRC the only change I made to the initial install command was to remove the anonymous telemetry.

**Comment by ilyam8** [comment]
Hi, @josephrocca. You need 

- to uninstall Netdata and 
- install static build (`use ./kickstart.sh --static-only`)

Ubuntu 18.04 is EOL, we don't support it and we don't build native packages for it.

**Comment by josephrocca** [comment]
Ah thanks - I'd have expected the installer to warn me that my OS is EOL and hence latest version could not be installed, so I've opened a feature request here:

 * https://github.com/netdata/netdata/issues/15757

And one for the dashboard error/warning banner to be more informative:

 * https://github.com/netdata/netdata-cloud/issues/900
