### ISSUE TITLE
docker host edit-config container id missing

### ISSUE THREAD

**Issue by JuttDB** [netdata/netdata#15752]
**new image is pulled today so it should be fine.**

`Ubuntux@ubuntu:~/netdataconfig/netdata$ ./edit-config list

Autodetected containerized Netdata instance. Attempting to autodetect container ID.
ERROR: Could not autodetect container ID. It must be supplied on the command line with the --container option.

**According to above error.  --container  is added with container id** 

Ubuntux@ubuntu:~/netdataconfig/netdata$ ./edit-config list --container 9daf1ebe67eb49d8f8d64a
ERROR: Unrecognized option list.`

_Originally posted by @JuttDB in https://github.com/netdata/netdata/discussions/15636#discussioncomment-6644533_

**Comment by ilyam8** [comment]
Hi, @JuttDB. We can continue at https://github.com/netdata/netdata/discussions/15636. If you want to open an issue please use [bug template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2Cneeds+triage&projects=&template=BUG_REPORT.yml&title=%5BBug%5D%3A+).
