### ISSUE TITLE
[Bug]: v2 dashboard bundling should use a versioned url

### ISSUE THREAD

**Issue by vkalintiris** [netdata/netdata#15754]
### Bug description

The url used in `bundle_dashboard_v2.py` does not contain any identifier to denote the version of the dashboard:
[URLSRC = 'https://app.netdata.cloud/agent.tar.gz'](https://github.com/netdata/netdata/blob/483d8481a5a5edf72630068534feb1a4d228ed0b/web/gui/bundle_dashboard_v2.py#L23)

We need something like: `https://app.netdata.cloud/agent-vX.X.X.tar.gz`

### Expected behavior

N/A

### Steps to reproduce

N/A

### Installation method

other

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

**Comment by ilyam8** [comment]
Hey, @vkalintiris. Why do we need this? You didn't write why.

**Comment by vkalintiris** [comment]
> Hey, @vkalintiris. Why do we need this? You didn't write why.

In general, _everything_ that ends up in a git repository from external sources should be traceable to a specific version.

In my case, I added support for bundling the dashboard repository with cmake and  (due to this issue) I got newer files.

**Comment by ilyam8** [comment]
I think we can close this:

- Yes, during development in PR cmake there was a small (cosmetic) problem, but this work has already been done.
- the bundling script is not important. Most users do not use the bundled version. We usually only run this script before Netdata is released or when we need to update the `regitry-*.html` files - quite rare and never required to get a specific version.
