### ISSUE TITLE
[Bug]: system.swap not working after latest update.

### ISSUE THREAD

**Issue by blkbrd12** [netdata/netdata#15790]
### Bug description

system.swap chart stopped working on custom dashboard after installing latest update. (Docker container)

system.swap: chart not found on url "/api/v1/chart?chart=system.s

### Expected behavior

Chart should load normally.

### Steps to reproduce

1. Updated to latest version
2.
3.
...

### Installation method

other

### System info

```shell
Docker
```

### Netdata build info

```shell
Docker
```

**Comment by ilyam8** [comment]
Hi, @blkbrd12. It was renamed to `mem.swap`.

**Comment by blkbrd12** [comment]
Thank you very much for your reply. I will update my dashboard with that.

**Comment by ildar170975** [comment]
Some time ago 2 metrics were available in `system.swap`: `free` & `used`.
No I see in `mem.swap` only `free`.
Where can I get the `used` data?
