### ISSUE TITLE
[Feat]: Suppress "NFACCT process exiting" message in log

### ISSUE THREAD

**Issue by Chocobo1** [netdata/netdata#15797]
### Problem

Occasionally I'm seeing the following message pops up in my system log. The number of it isn't much, about ~10 for a day but it is still noticeable. I would like to have it suppressed as the message doesn't convoy any important event of the app/system nor does it prompts user for further actions.
```
Aug 13 08:54:04 Server1 nfacct.plugin[381566]: NFACCT process exiting
```

### Description

Suppress "NFACCT process exiting" message in log. The message doesn't convoy any important event of the app/system nor does it prompts user for further actions.

Observed on netdata 1.42.0.

### Importance

really want

### Value proposition

1. The system log will be clear of repetitive unimportant messages.
2.
3.

### Proposed implementation

Probably originated from here: https://github.com/netdata/netdata/blob/93c55cca5008e7c3cf213715ea9ba97c7fc388ba/collectors/nfacct.plugin/plugin_nfacct.c#L886
Maybe just delete it.

Also probably a good idea to review all usages of `collector_info()` and remove the redundant, uninteresting ones (such as `cleaning up...`)
https://github.com/search?q=repo%3Anetdata%2Fnetdata+collector_info%28&type=code

**Comment by ilyam8** [comment]
Hi, @Chocobo1. and I think it's fine as long as we keep this functionality - exit every N seconds (the reason for this is to "fix" potential memory leaks in the plugin, if any). I increased the restart time from 4 to 24 hours in #15801, so it will be one info message per day.
