### ISSUE TITLE
[Feat]: IPv6 Support for installer

### ISSUE THREAD

**Issue by ukd1** [netdata/netdata#15816]
### Problem

Netdata isn't installable on a machine with only IPv6 connections, as a bunch of the endpoints y'all have don't have that configured.

### Description

Add IPv6 AAAA records to `app.netdata.*` and anything else needed to run, and install the product. Related to #10070, which is more about it actually running - but for me it won't even install.

```bash
~# wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --nightly-channel --claim-token xxxxxxxxxxxxxxxxI --claim-rooms b25805b9-16f3-45ca-bd31-cbe5c532a673 --claim-url https://app.netdata.cloud 
--2023-08-16 06:12:00--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 2a06:98c1:3120::, 2a06:98c1:3121::, 188.114.96.0, ...
Connecting to my-netdata.io (my-netdata.io)|2a06:98c1:3120::|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

/tmp/netdata-kickstart.sh                               [ <=>                                                                                                                ]  83.10K  --.-KB/s    in 0.002s  

2023-08-16 06:12:00 (39.0 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [85097]


 --- Using /tmp/netdata-kickstart-proASKpLiL as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
[/tmp/netdata-kickstart-proASKpLiL]# sh -c cat "//etc/netdata/.install-type" > "/tmp/netdata-kickstart-proASKpLiL/install-type" 
 OK 

 --- Found an existing netdata install at /, with installation type 'binpkg-deb'. --- 
[/tmp/netdata-kickstart-proASKpLiL]# test -x //usr/libexec/netdata/netdata-updater.sh 
 OK 

[/tmp/netdata-kickstart-proASKpLiL]# //usr/libexec/netdata/netdata-updater.sh --interactive --not-running-from-cron 
Wed Aug 16 06:12:01 UTC 2023 : INFO: netdata-updater.sh:  Checking if a newer version of the updater script is available.
curl: (28) Connection timeout after 10001 ms
curl: (28) Connection timeout after 10000 ms
.........
```

### Importance

blocker

### Value proposition

1. Some hosts are IPv6, as it's cheaper
2. This stops a bunch of people being abla to use your product 
3. It's 2023 and IPv6 support should be normal

### Proposed implementation

Do the ops / infra work 😇

**Comment by Ferroin** [comment]
Interesting. The place it’s failing is a request against GitHub’s public API, which not only definitely has IPv6 support, but is also generally very reliable . My gut instinct here is that _something_ is going wrong with IPv6 routing and causing the issue (because that _always_ seems to be the problem when it comes to IPv6 between two arbitrary sites not working correctly), but it’s hard to say.

The effective `curl` command that’s being run here is:

```
curl -sSL --connect-timeout 10 --retry 3 https://api.github.com/repos/netdata/netdata/commits?path=packaging%2Finstaller%2Fnetdata-updater.sh&page=1&per_page=1 > /dev/stdout
```

Can you try running that locally on the system where things are failing and see what you get?

**Comment by ukd1** [comment]
After fixing the lack of quotes;

```bash
~# curl -sSL --connect-timeout 10 --retry 3 "https://api.github.com/repos/netdata/netdata/commits?path=packaging%2Finstaller%2Fnetdata-updater.sh&page=1&per_page=1" > /dev/stdout
curl: (28) Connection timeout after 10001 ms
curl: (28) Connection timeout after 10001 ms
curl: (28) Connection timeout after 10000 ms
curl: (28) Connection timeout after 10001 ms
```

Some extra stuff:

```bash
~# dig api.github.com

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> api.github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14409
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;api.github.com.                        IN      A

;; ANSWER SECTION:
api.github.com.         41      IN      A       140.82.121.6

;; Query time: 4 msec
;; SERVER: 2606:4700:4700::1111#53(2606:4700:4700::1111) (UDP)
;; WHEN: Thu Aug 17 01:26:11 UTC 2023
;; MSG SIZE  rcvd: 59

~# dig -t aaaa api.github.com

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> -t aaaa api.github.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49314
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;api.github.com.                        IN      AAAA

;; AUTHORITY SECTION:
github.com.             608     IN      SOA     ns-1707.awsdns-21.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 0 msec
;; SERVER: 2606:4700:4700::1111#53(2606:4700:4700::1111) (UDP)
;; WHEN: Thu Aug 17 01:26:16 UTC 2023
;; MSG SIZE  rcvd: 127

```

So it looks like it might be resolving the IPv4 addresses before / in preference of the IPv6 addresses...?

**Comment by vobruba-martin** [comment]
As far as I know GitHub supports IPv6 on GitHub Pages (`*.github.io`) only.

**Comment by ilyam8** [comment]
Thanks, @vobruba-martin, you are right! I think this is upstream problem and nothing we can do.

**Comment by ukd1** [comment]
> Thanks, @vobruba-martin, you are right! I think this is upstream problem and nothing we can do.

The lack of `AAAA` for that endpoint was confirmed by the dig I posted in the original reply, btw.

However, @ilyam8 at least from what I can see your reply is incorrect, there are things you can do. You don't have to use the github api for this. If you won't fix it as you don't want to change, and don't care about the folks that have this issue, that's different to "nothing we can do" imho.

I guess you could file a ticket about this issue with them about their lack of IPv6 for the API?

I can move on, and not use netdata, but I wonder how many other folks think it's just broken and never open a ticket. Likely I'm the few that could be bothered to try tell y'all, and help figure out the issue.

"Nothing we can do", I guess! ✌️🤯

**Comment by ilyam8** [comment]
<details>
<summary>We download a lot of things from GH</summary>

```bash
$ grep github.com netdata-installer.sh
"https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_PACKAGE_VERSION}/${PROTOBUF_PACKAGE_BASENAME}" \
    "https://github.com/json-c/json-c/archive/${JSONC_PACKAGE_BASENAME}" \
    "https://github.com/yaml/libyaml/releases/download/${YAML_PACKAGE_VERSION}/${YAML_PACKAGE_BASENAME}" \
    "https://github.com/netdata/libbpf/archive/${LIBBPF_PACKAGE_BASENAME}" \
    "https://github.com/netdata/ebpf-co-re/releases/download/${CORE_PACKAGE_VERSION}/${CORE_PACKAGE_BASENAME}" \
    download_go "https://github.com/netdata/go.d.plugin/releases/download/${GO_PACKAGE_VERSION}/${GO_PACKAGE_BASENAME}" "${tmp}/${GO_PACKAGE_BASENAME}"
    download_go "https://github.com/netdata/go.d.plugin/releases/download/${GO_PACKAGE_VERSION}/config.tar.gz" "${tmp}/config.tar.gz"
    "https://github.com/netdata/kernel-collector/releases/download/${EBPF_VERSION}/${EBPF_TARBALL}" \


$ grep github.com packaging/installer/netdata-updater.sh
NETDATA_STABLE_BASE_URL="${NETDATA_BASE_URL:-https://github.com/netdata/netdata/releases}"
NETDATA_NIGHTLY_BASE_URL="${NETDATA_BASE_URL:-https://github.com/netdata/netdata-nightlies/releases}"
  commit_check_url="https://api.github.com/repos/netdata/netdata/commits?path=packaging%2Finstaller%2Fnetdata-updater.sh&page=1&per_page=1"


$ grep github.com packaging/installer/kickstart.sh
AGENT_BUG_REPORT_URL="https://github.com/netdata/netdata/issues/new/choose"
CLOUD_BUG_REPORT_URL="https://github.com/netdata/netdata-cloud/issues/new/choose"
DISCUSSIONS_URL="https://github.com/netdata/netdata/discussions"
NETDATA_TARBALL_BASEURL="${NETDATA_TARBALL_BASEURL:-https://github.com/netdata/netdata-nightlies/releases}"
      export NETDATA_STATIC_ARCHIVE_URL="https://github.com/netdata/netdata/releases/download/v${INSTALL_VERSION}/netdata-${arch}-v${INSTALL_VERSION}.gz.run"
      export NETDATA_STATIC_ARCHIVE_OLD_URL="https://github.com/netdata/netdata/releases/download/v${INSTALL_VERSION}/netdata-v${INSTALL_VERSION}.gz.run"
      export NETDATA_STATIC_ARCHIVE_CHECKSUM_URL="https://github.com/netdata/netdata/releases/download/v${INSTALL_VERSION}/sha256sums.txt"
      latest="$(get_redirect "https://github.com/netdata/netdata/releases/latest")"
      export NETDATA_STATIC_ARCHIVE_URL="https://github.com/netdata/netdata/releases/download/${latest}/netdata-${arch}-latest.gz.run"
      export NETDATA_STATIC_ARCHIVE_CHECKSUM_URL="https://github.com/netdata/netdata/releases/download/${latest}/sha256sums.txt"
      export NETDATA_SOURCE_ARCHIVE_URL="https://github.com/netdata/netdata/releases/download/v${INSTALL_VERSION}/netdata-v${INSTALL_VERSION}.tar.gz"
      export NETDATA_SOURCE_ARCHIVE_CHECKSUM_URL="https://github.com/netdata/netdata/releases/download/v${INSTALL_VERSION}/sha256sums.txt"
      latest="$(get_redirect "https://github.com/netdata/netdata/releases/latest")"
      export NETDATA_SOURCE_ARCHIVE_URL="https://github.com/netdata/netdata/releases/download/${latest}/netdata-${latest}.tar.gz"
      export NETDATA_SOURCE_ARCHIVE_CHECKSUM_URL="https://github.com/netdata/netdata/releases/download/${latest}/sha256sums.txt
```

</details>


Do you have alternatives in mind? If so, please share!

And there is a related [issue/discussion](https://github.com/orgs/community/discussions/10539) with a lot of participants/upvotes.

**Comment by ilyam8** [comment]
@netdata/agent-sre if you think this issue is fixable and plan to do so - please reopen and implement.

**Comment by Ferroin** [comment]
We could theoretically fix a significant percentage of it, but the GitHub API access part we cannot really work around, and at that point it makes little sense for us to try to change any of the other parts. Our repos are on GitHub, that is unlikely to ever change short of GitHub shutting down (and even if it does change, it won’t be any time within the next few years), so the only options we have to avoid using the GitHub API involve _us_ dedicating resources and infrastructure to this, and we quite simply do not have the resources to spare to run a properly secure and abuse-resistant API gateway to resolve this.

Believe me, I’m not happy about GitHub dragging their feet on this, and lots of other people are not either (see for example https://github.com/orgs/community/discussions/10539).

That said, there should be no reason that _individual users_ cannot utilize a NAT64 gateway (either provided by their ISP, self-hosted, or some public service such as https://nat64.net/) to work around this. GitHub is unfortunately not the only major site that still lacks proper IPv6 support, so having such a setup available is likely to be useful for other reasons as well.

**Comment by ukd1** [comment]
@Ferroin - thanks for the reply; I didn't know about nat64, so thanks - I'll try it.

Could that be used as a fallback in the installation? i.e. if you can't resolve or connect ipv4 github api, use nat64 - I assume if you check the ssl cert from the api this would still be pretty safe?

**Comment by ukd1** [comment]
FYI, that worked totally fine - @Ferroin thanks again for the suggestion 💪

**Comment by Ferroin** [comment]
> Could that be used as a fallback in the installation? i.e. if you can't resolve or connect ipv4 github api, use nat64 - I assume if you check the ssl cert from the api this would still be pretty safe?

Unfortunately doing so would require us to do some less than desirable things with DNS resolution. There’s not really any portable, reliable, way to override what DNS servers to use for a given command on Linux, so we would have to temporarily modify `/etc/resolv.conf`, which is _really_ risky for a number of reasons.

That said, this definitely deserves an entry in the documentation to mention this limitation.
