### ISSUE TITLE
[Feat]: Typesense Collector

### ISSUE THREAD

**Issue by MarcErdmann** [netdata/netdata#15844]
### Description

I would love to see a collector for Typesense (https://typesense.org/). Typesense exposes two endpoints ("/metrics" and "/stats") which expose metrics in JSON format (https://typesense.org/docs/guide/running-in-production.html#monitoring).

### Importance

really want

### Value proposition

1. I can rely on Netdata to monitor all my services

**Comment by andrewm4894** [comment]
In the meantime I think you could maybe look and see if the pandas collector could potentially do this as it can just read from anything pandas can. Here is an example of using it to just read some local Jason from and endpoint. 

https://github.com/netdata/netdata/blob/c26af4455223d7d0f8964e408d4ca02e78b710df/collectors/python.d.plugin/pandas/pandas.conf#L154

Looking at the typesense metrics endpoint it seems like would be fairly straightforward.

https://learn.netdata.cloud/docs/data-collection/generic-data-collection/structured-data-pandas

**Comment by andrewm4894** [comment]
@ilyam8 any idea if we have any other options?

Wondering if some sort of generic http json collector in Go could be a general solution for http endpoints with reasonable json and be a bit more lightweight than the pandas approach above (which means need to install pandas library).

I had a look and does not look like typesense api has Prometheus format so don't think that's an option either.

**Comment by andrewm4894** [comment]
@MarcErdmann if you familiar with python then you could make a custom collector for typesense easy enough I think (I could help review etc). https://learn.netdata.cloud/docs/data-collection/external-plugins/python.d.plugin/develop-a-custom-data-collector-in-python

Or if familiar with Go then that's the best option https://github.com/netdata/go.d.plugin/blob/master/docs/how-to-write-a-module.md

You can also use bash too: https://github.com/netdata/netdata/blob/master/collectors/charts.d.plugin/README.md

**Comment by MarcErdmann** [comment]
Thanks @andrewm4894! I will check the resources shared by you

**Comment by MarcErdmann** [comment]
@andrewm4894 I will not have the time to implement the collector myself.
