### ISSUE TITLE
[Feat]: How to keep "Force Play" even after refreshing the page on new netdata 1.42.x

### ISSUE THREAD

**Issue by chuwza** [netdata/netdata#15852]
Hi, on netdata 1.42.1，when I selected "force play", after refreshing the page, it automatically switched to "playing". 
![屏幕截图(271)](https://github.com/netdata/netdata/assets/30049891/9c2fe6d5-d978-45b7-b485-406f9725b722)
![IMG_20230821_163113](https://github.com/netdata/netdata/assets/30049891/463c5892-39b8-4082-aad2-8d12f38d7909)

Is there any way to keep "force play"? This worked on older versions of netdata, such as netdata 1.33, it won't automatically switched to "playing", it will remembers my choices
![屏幕截图(277)](https://github.com/netdata/netdata/assets/30049891/bc05a04b-8392-46f5-ba8c-ab5181b8b377)
![IMG_20230821_165710](https://github.com/netdata/netdata/assets/30049891/159cf001-d436-41ce-8f30-9c36a6471a71)

**Comment by ilyam8** [comment]
@chuwza can you please explain/elaborate why you need the page constantly to be in "force play"? I was told that the reset on update is not a bug, but an intended behavior.

**Comment by chuwza** [comment]
> @chuwza can you please explain/elaborate why you need the page constantly to be in "force play"? I was told that the reset on update is not a bug, but an intended behavior.

Thank you for you reply.😀

OK, I think the usage scenario of netdata is pc (for phones, a light app is more suitable), and it is impossible for pc to focus on such a monitoring page as netdata all the time. I need to do many other operations on my pc, when I need netdata, take a look, the time may be 10s, or 1 minute

And the automatic switch to "playiny" sucks for me, whenever I want to watch netdata, I watch it for a few seconds, only to find that the data has not changed...😥

And the old version of netdata, such as v1.33, you have indeed made this function, I Really hope you can add this function back to new netdata.

**Comment by ilyam8** [comment]
Fixed.

**Comment by chuwza** [comment]
> Fixed.

OK, thank you
