### ISSUE TITLE
[Feat]: How to change units from "kilobits/s" to "KiB/s" on new netdata 1.42.x?

### ISSUE THREAD

**Issue by chuwza** [netdata/netdata#15888]
On old netdata 1.33, I can change units by edit /etc/netdata.conf, such as
```
[system.net]
        units = KiB/s
        dim InOctets multiplier = 1
	dim InOctets divisor = 1024
	dim OutOctets multiplier = -1
        dim OutOctets divisor = 1024
```

But on new netdata 1.42.1, I can't found these in /etc/netdata.conf, I also edit the conf, And it didn't work.

Has this feature been removed on new netdata?

**Comment by vkalintiris** [comment]
> Has this feature been removed on new netdata?

It has been removed for more than one year now:

- https://github.com/netdata/netdata/pull/12209
- https://github.com/netdata/netdata/pull/12728

In short this was done for performance reasons and due to lack of demand for such functionality.
