### ISSUE TITLE
[Feat]: Allow calculation between metric in charts

### ISSUE THREAD

**Issue by Creling** [netdata/netdata#15884]
### Problem

Compared with HOW MUCH ram is used, I prefer HOW PERCENTAGE ram is used. However, I cannot add a chart to show the latter one.

### Description

I hope we can have something as following when creating charts:

```
$system.ram.used * 100 / ($system.ram.used + $system.ram.cached + $system.ram.free + $system.ram.buffers)
```

### Importance

really want

### Value proposition

1. Give users more flexibility to show their metrics.
2. Some counterparts like NewRelic has implemented it.

**Comment by VIRAT9358** [comment]
I am willing to work on this feature. Can you suggest the folder I need to look into.
