### ISSUE TITLE
[Bug]: RPi 3B+ - no "sensors" available

### ISSUE THREAD

**Issue by ildar170975** [netdata/netdata#15907]
### Bug description

I have two Raspberry Pi 3B+ (LibreELEC 9.x).
Latest Netdata in Docker.

A week ago a “sensors.temperature” data disappeared in one machine (call it "RPi-1"), the 2nd machine (call it "RPi-2") still has these data.
Nothing I changed with this machine - even was not home these days.

What I tried:
-- restarted netdata conatiner,
-- removed & re-installed netdata in container,
none of these helped.

Both machine have SAME hardware & sofware config, on both netdata was installed with SAME command (difference in hostnameonly):
```
docker run -d --name=netdata \
--pid=host \
--network=host \
--hostname=netdata_rpi_1 \
-v netdataconfig:/etc/netdata \
-v netdatalib:/var/lib/netdata \
-v netdatacache:/var/cache/netdata \
-v /etc/passwd:/host/etc/passwd:ro \
-v /etc/group:/host/etc/group:ro \
-v /proc:/host/proc:ro \
-v /sys:/host/sys:ro \
-v /etc/os-release:/host/etc/os-release:ro \
-v /var/run/docker.sock:/var/run/docker.sock:ro \
--restart unless-stopped \
--cap-add SYS_PTRACE \
--cap-add SYS_ADMIN \
--security-opt apparmor=unconfined \
-e NETDATA_CLAIM_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxx \
-e NETDATA_CLAIM_URL=https://app.netdata.cloud \
-e NETDATA_CLAIM_ROOMS=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
netdata/netdata:edge
```
Noticed that RPi-2 (which provides a temperature) has this section:
![cc4cf2cb947b9c2cb444d10ee62bfb1083e235a2](https://github.com/netdata/netdata/assets/71872483/f0f588c2-5ae6-4d33-b3ea-f667f9c73538)
and RPi-1 does not.

Version info:
RPi w/o temperature:
![6ba0d5395342aa7eccca7706de1e803a38270f50](https://github.com/netdata/netdata/assets/71872483/64f3fd42-194f-41f1-8da9-b887b2fc98d9)
RPi with temperature:
![e9f48b6684e4a41a02f725b0a88b2994fb2bf872](https://github.com/netdata/netdata/assets/71872483/a1baa24f-4c8a-4391-a8ed-b7ebd5817693)

Did what was proposed [here](https://community.netdata.cloud/t/monitoring-cpu-temps-on-rpix/2895/23?u=rodrigo2):
1. Run `./edit-config python.d.conf`.
2. It has this:
```
# sensors: yes
```
3. Uncomment this line.
4. Restart: `docker restart netdata`
5. But still no sensors.

### Expected behavior

as above

### Steps to reproduce

as above

### Installation method

docker

### System info

```shell
/etc/os-release:NAME="LibreELEC"
/etc/os-release:VERSION="9.2.8"
/etc/os-release:ID="libreelec"
/etc/os-release:VERSION_ID="9.2"
/etc/os-release:PRETTY_NAME="LibreELEC (official): 9.2.8"
/etc/os-release:BUILD_ID="2282c381ee597a3ca6a6cf3836b5681049f7b81b"
/etc/os-release:OPENELEC_ARCH="RPi2.arm"
/etc/os-release:LIBREELEC_ARCH="RPi2.arm"
/etc/os-release:LIBREELEC_BUILD="official"
/etc/os-release:LIBREELEC_PROJECT="RPi"
/etc/os-release:LIBREELEC_DEVICE="RPi2"
/etc/release:RPi2.arm-9.2.8
```

### Netdata build info

```shell
see screenshots above
```

**Comment by MrZammler** [comment]
Hi @ildar170975 

Although this is a docker and might have some differences, is lm-sensors installed on both machines?

**Comment by ildar170975** [comment]
I haven't done anything about lm-sensors...
These machines have same configuration, and a few days ago one machine stopped giving temperature data.

**Comment by MrZammler** [comment]
I did a small test on a Rpi4 here, not sure of the differences between it and 3, but the only way I got temperature readings (from the python plugin) was when I installed the lm-sensors package.

I'm not sure how to do it from inside the docker container, but is it possible to run `sudo /usr/libexec/netdata/plugins.d/python.d.plugin sensors debug trace` ?

**Comment by Ferroin** [comment]
> I'm not sure how to do it from inside the docker container

See https://learn.netdata.cloud/docs/installing/docker#adding-extra-packages-at-runtime

**Comment by MrZammler** [comment]
I'm not sure. We haven't changed something as far as I can see recently in regards to the python.d.plugin and the sensors module.

The Rpi's AFAIK (and I don't know much) are indeed a bit weird on how their onboard sensors work.

Have you tried the debug run of python.d.plugin? It should show what's happening.

**Comment by ildar170975** [comment]
Wth this issue is closed???

**Comment by ildar170975** [comment]
@ilyam8
You did nothing to solve the issue - but you closed it, explain yourself.

**Comment by MrZammler** [comment]
> @ilyam8 You did nothing to solve the issue - but you closed it, explain yourself.

Hi @ildar170975 it was a joined decision to close it. I assumed by lack of feedback that it was solved, apologies. We'll continue on the new one.

**Comment by ildar170975** [comment]
> t was a joined decision to close it. I assumed by lack of feedback that it was solved, apologies

I am not an experienced Netdata user, so I need to time to learn...
Also I apologize for offensive words.
