### ISSUE TITLE
[Feat]: Tip on how to access the local dashboard after successfully instaling the agent

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#15924]
### Problem

From the feedback on [this ticket ](https://github.com/netdata/netdata-cloud/issues/912) it seems to make sense to add some information on how to access the local dashboard, besides providing the tip to look into Netdata Cloud.

### Description

After installing the agent users should be able to easily understand that they can access the local dashboard 

An extract of what we have on [this page](https://learn.netdata.cloud/docs/visualizations/legacy-agent-dashboard)
> By default, Netdata starts a web server for its dashboard at port 19999. Open up your web browser of choice and navigate to http://NODE:19999, replacing NODE with the IP address or hostname of your Agent. If you're unsure, try http://localhost:19999 first.

### Importance

nice to have

### Value proposition

1. Users can immediately understand they can access the local dashboard

**Comment by hugovalente-pm** [comment]
@Ferroin I believe we had that information at some point, probably we should think of adding it again

**Comment by ilyam8** [comment]
@hugovalente-pm added a tip to the kickstart's success banner in #16673. Is that what you want?
