### ISSUE TITLE
[Feat]: Allow configuration of ntfy access for notifications

### ISSUE THREAD

**Issue by miversen33** [netdata/netdata#15927]
### Problem

With the addition of #14875 we have ntfy support which is fantastic! However, it appears to not support [access tokens](https://docs.ntfy.sh/config/?h=token#access-tokens). This means that we either have to ["ensure the topic is unique enough using a long, randomly generated ID"](https://learn.netdata.cloud/docs/alerting/notifications/netdata-agent-notifications/ntfy#warning) or accept that our notifications are publicly accessible.

The change _should_ be pretty minor, basically just modify the curl request to provide user credentials in in the request if they are provided in the notification configuration.

Some examples of this can be found [here](https://github.com/nickexyz/ntfy-shellscripts/)

### Description

It would be great if we could secure notifications when sent to an ntfy server

### Importance

really want

### Value proposition

I would argue that the ability to securely transmit your data should be incredibly important to both the netdata project and its users. Of course, this is only a thing related to a single notification platform, however knowing that ntfy supports access tokens and that this project doesn't support using them is more than a bit of a bummer.

### Proposed implementation

This seems like it would be as simple as updating the `ntfy_send` function in [alarm-notify.sh.in](https://github.com/netdata/netdata/blob/master/health/notifications/alarm-notify.sh.in#L2431-L2475) to utilize a few new configuration options would do it. Something like

```bash
  # Adding ntfy header generation logic
  # Heavily inspired by https://github.com/nickexyz/ntfy-shellscripts/blob/main/sabnzbd.sh
  ntfy_auth_header=""
  if [[ -n "${ntfy_username}" ]] && [[ -n "${ntfy_password}" ]]; then
    ntfy_base64=$( echo -n "$ntfy_username:$ntfy_password" | base64 )
    ntfy_auth_header="-H Authorization: Basic ${ntfy_base64}"
  elif [ -n "${ntfy_token}" ]; then
    ntfy_auth_header="-H Authorization: Bearer $auth"
  fi
```

and then updating the `httpcode` section to 
```bash
    httpcode=$(docurl -X POST \
                      "${ntfy_auth_header}" \
                      -H "Icon: https://raw.githubusercontent.com/netdata/netdata/master/web/gui/dashboard/images/favicon-196x196.png" \
                      -H "Title: ${host}: ${name//_/ }" \
                      -H "Tags: ${emoji}" \
                      -H "Priority: ${priority}" \
                      -H "Actions: view, View node, ${goto_url}, clear=true;" \
                      -d "${msg}" \
                      ${recipient})
```

I have no idea how to add new configuration options otherwise I would offer to open a PR :)

Also note, this has not been tested but IMO is a very solid starting place

**Comment by ilyam8** [comment]
Hey, @miversen33. I think you can add `NTFY_*` options after 

https://github.com/netdata/netdata/blob/31924c0eb2fb245bdf047a5f4fe9f5ef10baf24e/health/notifications/health_alarm_notify.conf#L860-L862

**Comment by ilyam8** [comment]
You can 
- build from source using `netdata-installer.sh`
- create a docker image `docker build -t SOME_NAME .`

**Comment by miversen33** [comment]
It seems someone will have to teach me how to fish here :(

I pulled down the repo, made my changes in the container and started the service. I can access the service on port 19999 on my localhost machine, however it _seems_ that all the notification related things are pulling from `app.netdata.cloud` and thus none of my notification changes are reflecting in the UI in anyway. Am I missing something or will I be unable to "test" my changes here?
