### ISSUE TITLE
[Bug]: RPi 3B+ - no "sensors" available

### ISSUE THREAD

**Issue by ildar170975** [netdata/netdata#15962]
### Bug description

Have to REOPEN my issue - the 1st one was closed.

------------------

Here is my issue: https://github.com/netdata/netdata/issues/15907

I have two Raspberry Pi 3B+ (LibreELEC 9.x).
Latest Netdata in Docker.

A week ago a “sensors.temperature” data disappeared in one machine (call it "RPi-1"), the 2nd machine (call it "RPi-2") still has these data.
Nothing I changed with this machine - even was not home these days.

What I tried:
-- restarted netdata conatiner,
-- removed & re-installed netdata in container,
none of these helped.

Both machine have SAME hardware & sofware config, on both netdata was installed with SAME command (difference in `hostnameonly`):
```
docker run -d --name=netdata \
--pid=host \
--network=host \
--hostname=netdata_rpi_1 \
-v netdataconfig:/etc/netdata \
-v netdatalib:/var/lib/netdata \
-v netdatacache:/var/cache/netdata \
-v /etc/passwd:/host/etc/passwd:ro \
-v /etc/group:/host/etc/group:ro \
-v /proc:/host/proc:ro \
-v /sys:/host/sys:ro \
-v /etc/os-release:/host/etc/os-release:ro \
-v /var/run/docker.sock:/var/run/docker.sock:ro \
--restart unless-stopped \
--cap-add SYS_PTRACE \
--cap-add SYS_ADMIN \
--security-opt apparmor=unconfined \
-e NETDATA_CLAIM_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxx \
-e NETDATA_CLAIM_URL=https://app.netdata.cloud \
-e NETDATA_CLAIM_ROOMS=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
netdata/netdata:edge
```

Noticed that RPi-2 (which provides a temperature) has this section:
![265651529-f0f588c2-5ae6-4d33-b3ea-f667f9c73538](https://github.com/netdata/netdata/assets/71872483/49fe403d-69c9-4741-b6cd-1a04633ffa02)
and RPi-1 does not.

Version info:
RPi w/o temperature:
![265651991-64f3fd42-194f-41f1-8da9-b887b2fc98d9](https://github.com/netdata/netdata/assets/71872483/92068918-427b-49df-8ef0-f5f7962b630d)

RPi with temperature:
![265652143-a1baa24f-4c8a-4391-a8ed-b7ebd5817693](https://github.com/netdata/netdata/assets/71872483/c1f80d2a-25c4-470e-8f46-6ccc8d362995)

Did what was proposed [here](https://community.netdata.cloud/t/monitoring-cpu-temps-on-rpix/2895/23?u=rodrigo2):
1. Run ./edit-config python.d.conf.
2. It has this:
`# sensors: yes`
3. Uncomment this line.
4. Restart: `docker restart netdata`
5. But still no sensors.

### Expected behavior

as above

### Steps to reproduce

as above

### Installation method

docker

### System info

```shell
/etc/os-release:NAME="LibreELEC"
/etc/os-release:VERSION="9.2.8"
/etc/os-release:ID="libreelec"
/etc/os-release:VERSION_ID="9.2"
/etc/os-release:PRETTY_NAME="LibreELEC (official): 9.2.8"
/etc/os-release:BUILD_ID="2282c381ee597a3ca6a6cf3836b5681049f7b81b"
/etc/os-release:OPENELEC_ARCH="RPi2.arm"
/etc/os-release:LIBREELEC_ARCH="RPi2.arm"
/etc/os-release:LIBREELEC_BUILD="official"
/etc/os-release:LIBREELEC_PROJECT="RPi"
/etc/os-release:LIBREELEC_DEVICE="RPi2"
/etc/release:RPi2.arm-9.2.8
```

### Netdata build info

```shell
see screenshots above
```

**Comment by ilyam8** [comment]
Hey, @ildar170975. Have you tried 

- [debug mode](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/sensors#troubleshooting)?
- running `sensors` inside the container?

**Comment by ildar170975** [comment]
@ilyam8 
Hi!


> * [debug mode](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/sensors#troubleshooting)?
What I did is (according to that link):
```
cd /usr/libexec/netdata/plugins.d/
su -s /bin/bash netdata
```
Output:
```
netdata_rpi_1:/usr/libexec/netdata/plugins.d$ ./python.d.plugin sensors debug trace
2023-09-13 20:59:05: python.d INFO: plugin[main] : using python v3
2023-09-13 20:59:05: python.d DEBUG: plugin[main] : looking for '/etc/netdata/python.d.conf'
2023-09-13 20:59:05: python.d DEBUG: plugin[main] : '/etc/netdata/python.d.conf' is loaded
2023-09-13 20:59:05: python.d DEBUG: plugin[main] : looking for '/usr/lib/netdata/conf.d/python.d.conf'
2023-09-13 20:59:05: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2023-09-13 20:59:05: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2023-09-13 20:59:05: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/./python.d.plugin", line 583, in load_job_statuses
    statuses = JobsStatuses().from_file(abs_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/libexec/netdata/plugins.d/./python.d.plugin", line 413, in from_file
    data = json.load(f)
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/./python.d.plugin", line 921, in <module>
    main()
  File "/usr/libexec/netdata/plugins.d/./python.d.plugin", line 912, in main
    if not p.setup():
           ^^^^^^^^^
  File "/usr/libexec/netdata/plugins.d/./python.d.plugin", line 653, in setup
    statuses = self.load_job_statuses()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/libexec/netdata/plugins.d/./python.d.plugin", line 586, in load_job_statuses
    module_name, ' '.join([v.strip() for v in str(error).split('\n')])))
    ^^^^^^^^^^^
NameError: name 'module_name' is not defined
```

> * running `sensors` inside the container?

I do not know what is this... Could you explain this to me?

Since I am not a really experienced Netdata user, most of things I have to learn 1st time in my life, it takes time...
Issues should not be closed just w/o any warning.

----

And I still wonder why:
-- two SAME devices
-- SAME netadata config
-- and one lost an ability to show sensors
?

**Comment by MrZammler** [comment]
Hi @ildar170975 

Could you please show the contents of `/var/lib/netdata/pythond-jobs-statuses.json` ?

**Comment by ildar170975** [comment]
> Could you please show the contents of `/var/lib/netdata/pythond-jobs-statuses.json` ?

It seems to be empty:
![image](https://github.com/netdata/netdata/assets/71872483/5ee5231e-ee48-4eb1-ac48-e86f303cce5e)

**Comment by ildar170975** [comment]
Thanks for fixing!
Shall I wait for a new version of Netdata?

**Comment by ilyam8** [comment]
This will be fixed in the next nightly release.
