### ISSUE TITLE
[Feat]: 

### ISSUE THREAD

**Issue by aphex23** [netdata/netdata#15986]
### Problem

Feature Request

### Description

Please add the ability to use the dials/gauges  in the custom dashboard not just the graphs

### Importance

really want

### Value proposition

1. Easier to see real time info like data usage in and out of network than a graph
2. Would save the step of having to setup some sort of dashboard in something such as Grafana
3.
...

**Comment by ilyam8** [comment]
Hey, @aphex23. Can you please update the title and elaborate more about the requested feature? What are dials?
