### ISSUE TITLE
[Bug]: Netdata uninstall does not remove cron job daily file

### ISSUE THREAD

**Issue by cholzer79** [netdata/netdata#15993]
### Bug description

Uninstall does not clean up all files. It leaves behind a file under /etc/cron.daily among other files.

### Expected behavior

Uninstall removes all files and folders created by the installer.

### Steps to reproduce

1. install netdata wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
2. uninstall netdata wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --uninstall
3. do a search for netdata and find what uninstall missed
...

### Installation method

kickstart.sh

### System info

```shell
Linux pve 6.2.16-3-pve #1 SMP PREEMPT_DYNAMIC PVE 6.2.16-3 (2023-06-17T05:58Z) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="12"
/etc/os-release:VERSION="12 (bookworm)"
/etc/os-release:VERSION_CODENAME=bookworm
/etc/os-release:ID=debian
```

### Netdata build info

```shell
I allready uninstalled netdata.
```

**Comment by ilyam8** [comment]
I think this is fixed. I see that we remove `/etc/cron.daily/netdata-updater` in uninstaller

https://github.com/netdata/netdata/blob/3af70c8f9ea269d7324a5be7ebc4dd69eb0495b3/packaging/installer/netdata-uninstaller.sh#L718-L733
