### ISSUE TITLE
High contrast dark theme

### ISSUE THREAD

**Issue by koraa** [netdata/netdata#1600]
I like dark themes, but I  have really trouble seeing anything in this :)

**Comment by ktsaou** [comment]
Why don't you switch to the white theme?

**Comment by koraa** [comment]
Well, I did for now because I couldn't see a thing. I generally prefer dark themes though, because they are not as hard on my eyes.

**Comment by ktsaou** [comment]
Can you help me build one?

The chart colors for the dark theme are here:

https://github.com/firehol/netdata/blob/8b09b30e0321de42660bd96784841714330c68a9/web/dashboard.js#L143-L164

Page background or the font color are controlled by bootstrap, so any bootstrap v3 theme will do.

**Comment by ktsaou** [comment]
The general idea for chart colors is that they are in pairs: positive, negative, positive, negative, ...

So, positive are green or blue, negative are red, orange or brown...

**Comment by koraa** [comment]
Sure thing about the negatives!

I should probably have included some new details; It was night and I had just given up trying to set up icinga with graphs after five hours torment and to my great delight it worked extremely well and I just went to sleep.

By now I am also on my better display again and the charts are more clear!

Generally I would recommend sticking to the W3C accessibility standards (https://www.w3.org/TR/WCAG20/). This thing can help checking: http://webaim.org/resources/contrastchecker/.

The basic font/background combination does pass this requirment. Some of the smaller design elements (greens in the graphs, graph lines, graph axis numbers) fail this requirement.
Thus I would actually suggest getting the default dark theme to a higher level of contrast (personally I'd make it even higher than necessary for the standard).

A true accessibility-focused high contrast theme should probably be even more extreme than that (as in #fff white and #000 black) and it should probably also be optimized for color blindness.

Of course I can adapt the settings to a level that will fit me (in the default theme or a high contrast one), so I'd be happy to do a PR for that. I won't however have much time do to fine tuning and intricate design work I am afraid.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
