### ISSUE TITLE
[Feat]: Windows_Exporter Events Logs

### ISSUE THREAD

**Issue by EX0LUXER** [netdata/netdata#16051]
### Problem

Dear all,

I have a problem with Windows Exporter and I can't see any metrics. I can the metrics when I click on the server and I check in but I can see previous metrics. 
![image](https://github.com/netdata/netdata/assets/146076807/0a794263-f616-448d-84d6-759234ca2cc3)

When I check my Windows server I see errors in event logs like this:

- error failed collecting iis metrics: <nil> counter not found
- failed collecting thermalzone metrics: <nil> Empty results set for collector
- mssql class collector XXX failed after 0.0000000s: counter not found
![image](https://github.com/netdata/netdata/assets/146076807/6c947281-69ce-4f0c-aafc-ece541fd1747)

Can someone help me with this?

Thanks!!

### Description

What I need is see all the metrics in the Overview and solve all the event errors.

### Importance

really want

### Value proposition

1. All users what are using this software can solve a new issue.
2. Try to solve this with new parch.

**Comment by ilyam8** [comment]
Duplicate of #15501
