### ISSUE TITLE
[Feat]: Custom prometheus stats via windows exporter

### ISSUE THREAD

**Issue by gdoermann** [netdata/netdata#16087]
### Problem

Our current feature request is aimed to resolve the issue of custom stats not being processed in NetData for Windows vNodes. As it stands, despite these custom stats being visible on the vNode's metrics page and being sent to the Netdata server, they fail to be processed and stored in the database. As a result, users are unable to graph these stats, limiting the data tracking and analytic capabilities of our current setup.

Original request (posted as a bug): https://github.com/netdata/netdata/issues/15715

### Description

We need a new feature for NetData that will allow custom windows exporter stats. This feature will allow NetData to process and store custom stat data from Windows vNode's exporter, and make it accessible for graphing and analysis within the NetData interface.

### Importance

must have

### Value proposition

1. **Enhanced Customizability**: This feature will allow users to tailor their data analysis according to their specific needs. This increased flexibility is key to assisting unique use cases and improving overall product satisfaction.

2. **Increased Utility**: By facilitating the collection, processing, and graphing of custom stats, the overall utility and functional range of Netdata is significantly improved for Windows users.

3. **Boosted User Satisfaction**: With an improved feature set that now includes the ability to graph custom stats, end-users will enjoy greater satisfaction and efficiency while using the platform.

4. **Expanded User Base**: This added functionality might appeal to new users who require this feature, potentially leading to an increase in user adoption, thereby expanding the Netdata community.

### Proposed implementation

A possible way to implement this feature could be to add a new processing procedure within the data collection process, specifically for handling custom stat data from Windows vNodes. This procedure will identify the custom stats, process the data, and store it in the database where it will be available for graphing and analysis. Depending on implementation complexity, it could be considered to decouple the custom metrics function and gradually integrate with the main metrics path for easier testing and debugging.

An alternative approach we can take to implement this feature is to build it into the in-progress NetData Windows client [msi-installer](https://github.com/netdata/msi-installer#instructions). This approach would involve integrating a new module or function into the Windows client to handle the collection, processing, and storage of custom stat data. This data could then be sent to the Netdata server, where it can be accessed for graphing and analysis.

This solution would be particularly suitable as it allows the handling of custom stats to be built directly into the client designed for the platform that the custom stats originate from. Consequently, it might provide a more streamlined and efficient process for managing custom stats and facilitate an easier setup for Windows users.

**Comment by ilyam8** [comment]
Closing as Windows will be covered by Netdata Agent. We do not plan to update go.d/windows and it will likely be removed after the release of Netdata Windows Agent.
