### ISSUE TITLE
[Feat]: Better display of disk usage time with SMART metrics

### ISSUE THREAD

**Issue by angarod** [netdata/netdata#16118]
### Problem

As seen in the screenshot, the units in seconds on the `smartd_log.power_on_hours_count` metric are in hours. This can be problematic or incomprehensible for drives reaching several years of age. In the example, my disks are 7 years old, i.e. 60,000 hours.
![Capture d’écran du 2023-10-03 22-25-54](https://github.com/netdata/netdata/assets/24314602/4bc892fb-8568-4236-9580-67ebf27e2e0d)

### Description

The functionality I'm proposing is to enable the `smartd_log.power_on_hours_count` metric to be displayed in days when disk usage exceeds 100 hours, and then in years when usage exceeds 365 days, for example.

### Importance

nice to have

### Value proposition

1. a better understanding of how long the customer's disks will be in use
2. a time-consuming conversion step could be skipped

**Comment by ilyam8** [comment]
This is implemented.

<img width="1191" alt="Screenshot 2024-09-12 at 21 55 12" src="https://github.com/user-attachments/assets/254565d0-3988-4581-ab69-db8f81a2d336">
