### ISSUE TITLE
UI: Jumping to dates and time periods.

### ISSUE THREAD

**Issue by koraa** [netdata/netdata#1614]
Hi,

I was just trying to compare today's and yesterday's loads on my server. I had to click `-` a lot of times.

It would be nice to have buttons & input fields to quickly set the period of the time being graphed and to jump in time ("show me the data from a week ago").

**Comment by ktsaou** [comment]
You are right.

For the moment, you can use:

1. SHIFT + mousewheel, to zoom out and SHIFT + right click to select the area of the chart you need.
2. The legend buttons allow you to fine tune the size of the jump with SHIFT and CONTROL.

The fastest though is the mousewheel.

**Comment by koraa** [comment]
Thanks for the tip!

**Comment by ktsaou** [comment]
@cakrit 	this is on our roadmap.
I found a couple of similar other issues too.
