### ISSUE TITLE
[Feat]: Split out disks/storage per node

### ISSUE THREAD

**Issue by brodonalds** [netdata/netdata#16160]
### Problem

At the moment, the disk tab shows how much is free on the host by default. It is only by selecting which disks can you view the space of a single mount/disk. 

### Description

By default, each "disk" should be shown under the disk header with its free and used space so that at a glance you can determine how a given drive is doing as total storage across a host is rarely needed to be monitored instead of each disk.

### Importance

nice to have

### Value proposition

1. Users can better track given disks and understand alerts easier
2. Per disk visibility by default is more likely to be what is needed over aggregating space.

**Comment by ilyam8** [comment]
Closing because the Mount-points function does the job and it doesn't require Cloud connection (nightly only at the moment).

**Comment by ilyam8** [comment]
I agree, it would be nice to have a similar “split” view in the Metrics tab. And I believe that that is planned.
