### ISSUE TITLE
[Bug]: netdata.service: Failed with result 'core-dump'.  Version: 1.41.0

### ISSUE THREAD

**Issue by enkrypt3d** [netdata/netdata#16163]
### Bug description

    Process: 1296 ExecStart=/usr/sbin/netdata -D $EXTRA_OPTS (code=dumped, signal=SEGV)
   Main PID: 1296 (code=dumped, signal=SEGV)
        CPU: 8ms

Oct 10 21:14:44 prod-mon01 systemd[1]: netdata.service: Main process exited, code=dumped, status=11/SEGV
Oct 10 21:14:44 prod-mon01 systemd[1]: netdata.service: Failed with result 'core-dump'.

kernel: [  126.417977] netdata[1296]: segfault at 2d0 ip 00007ff4e1e8d79d sp 00007ffd807ac0f0 error 4 in libc.so.6[7ff4e1e22000+178000]
2023-10-10T21:14:44.136414+00:00 prod-mon01 kernel: [  126.417989] Code: 03 00 00 e8 c5 a6 00 00 0f 1f 44 00 00 f3 0f 1e fa 53 48 81 ec a0 00 00 00 64 48 8b 04 25 28 00 00 00 48 89 84 24 98 00 00 00 <8b> 87 d0 02 00 00 85 c0 75 29 48 8b 84 24 98 00 00 00 64 48 2b 04
2023-10-10T21:14:44.247460+00:00 prod-mon01 systemd[1]: netdata.service: Main process exited, code=dumped, status=11/SEGV
2023-10-10T21:14:44.247544+00:00 prod-mon01 systemd[1]: netdata.service: Failed with result 'core-dump'.
2023-10-10T21:15:01.114696+00:00 prod-mon01 CRON[1304]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
2023-10-10T21:15:14.375489+00:00 prod-mon01 systemd[1]: netdata.service: Scheduled restart job, restart counter is at 5.
2023-10-10T21:15:14.375696+00:00 prod-mon01 systemd[1]: Stopped netdata.service - Real time performance monitoring.
2023-10-10T21:15:14.380399+00:00 prod-mon01 systemd[1]: Started netdata.service - Real time performance monitoring.
2023-10-10T21:15:14.386406+00:00 prod-mon01 kernel: [  156.662334] netdata[1310]: segfault at 2d0 ip 00007f59a1e8d79d sp 00007ffd2a37ef70 error 4 in libc.so.6[7f59a1e22000+178000]
2023-10-10T21:15:14.386413+00:00 prod-mon01 kernel: [  156.662344] Code: 03 00 00 e8 c5 a6 00 00 0f 1f 44 00 00 f3 0f 1e fa 53 48 81 ec a0 00 00 00 64 48 8b 04 25 28 00 00 00 48 89 84 24 98 00 00 00 <8b> 87 d0 02 00 00 85 c0 75 29 48 8b 84 24 98 00 00 00 64 48 2b 04
2023-10-10T21:15:14.492698+00:00 prod-mon01 systemd[1]: netdata.service: Main process exited, code=dumped, status=11/SEGV
2023-10-10T21:15:14.492821+00:00 prod-mon01 systemd[1]: netdata.service: Failed with result 'core-dump'.

### Expected behavior

Netdata agent should start without issue.

### Steps to reproduce

1. service netdata start
2. service netdata status
3.

Running this on ubuntu 23.04. Tried it with many versions of kernel with no luck. Also noticed that the upgrade script only upgrades it to 1.41.0 and not 1.42.0? 
...

### Installation method

kickstart.sh

### System info

```shell
root@prod-mon01:~# uname -a; grep -HvE "^#|URL" /etc/*release
Linux prod-mon01 6.0.10-x86_64-linode158 #1 SMP PREEMPT_DYNAMIC Thu Dec 1 13:16:43 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=23.04
/etc/lsb-release:DISTRIB_CODENAME=lunar
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 23.04"
/etc/os-release:PRETTY_NAME="Ubuntu 23.04"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="23.04"
/etc/os-release:VERSION="23.04 (Lunar Lobster)"
/etc/os-release:VERSION_CODENAME=lunar
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=lunar
/etc/os-release:LOGO=ubuntu-logo
```

### Netdata build info

```shell
command does not work

-bash: syntax error near unexpected token `-W'
```

**Comment by ilyam8** [comment]
Hi, @enkrypt3d. Update your post with the buildinfo. It is `/opt/netdata/usr/sbin/netdata -W buildinfo` or `/usr/sbin/netdata -W buildinfo` depends on your install prefix.

>  Also noticed that the upgrade script only upgrades it to 1.41.0 and not 1.42.0?

Share the script output.

Marking this issue as a question until we reproduce the problem in [the latest stable](https://github.com/netdata/netdata/releases/latest).

**Comment by enkrypt3d** [comment]
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
/dev/fd/63: line 26: cd: pipe:[28835]: No such file or directory

 --- Using /tmp/netdata-kickstart-KjYv18wU37 as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- Found an existing netdata install at /, with installation type 'binpkg-deb'. --- 
[/tmp/netdata-kickstart-KjYv18wU37]# test -x //usr/libexec/netdata/netdata-updater.sh 
 OK 

[/tmp/netdata-kickstart-KjYv18wU37]# //usr/libexec/netdata/netdata-updater.sh --interactive --not-running-from-cron 
Tue Oct 10 09:28:43 PM UTC 2023 : INFO: netdata-updater.sh:  Checking if a newer version of the updater script is available.
Tue Oct 10 09:28:44 PM UTC 2023 : INFO: netdata-updater.sh:  Downloading newest version of updater script.
Hit:1 http://mirrors.linode.com/ubuntu lunar InRelease
Hit:2 http://mirrors.linode.com/ubuntu lunar-updates InRelease
Hit:3 http://mirrors.linode.com/ubuntu lunar-backports InRelease
Hit:4 http://repo.netdata.cloud/repos/stable/ubuntu kinetic/ InRelease
Hit:5 http://repo.netdata.cloud/repos/repoconfig/ubuntu kinetic/ InRelease
Hit:6 http://security.ubuntu.com/ubuntu lunar-security InRelease
Reading package lists... Done                              
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
netdata-repo is already the newest version (2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://mirrors.linode.com/ubuntu lunar InRelease
Hit:2 http://mirrors.linode.com/ubuntu lunar-updates InRelease                    
Hit:3 http://mirrors.linode.com/ubuntu lunar-backports InRelease                  
Hit:4 http://repo.netdata.cloud/repos/stable/ubuntu kinetic/ InRelease            
Hit:5 http://security.ubuntu.com/ubuntu lunar-security InRelease                  
Hit:6 http://repo.netdata.cloud/repos/repoconfig/ubuntu kinetic/ InRelease
Reading package lists... Done                 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
netdata is already the newest version (1.41.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package netdata-plugin-systemd-journal
E: Unable to locate package netdata-plugin-systemd-journal
E: No packages found
 OK 

 --- Updated existing install at / --- 
 --- Successfully updated existing netdata install at /. --- 
 --- Not attempting to claim existing install at / (no claiming token provided). --- 
Official documentation can be found online at https://learn.netdata.cloud/docs/.

Looking to monitor all of your infrastructure with Netdata? Check out Netdata Cloud at https://app.netdata.cloud.

Join our community and connect with us on:
  - GitHub: https://github.com/netdata/netdata/discussions
  - Discord: https://discord.gg/5ygS846fR6
  - Our community forums: https://community.netdata.cloud/
[/root]# rm -rf /tmp/netdata-kickstart-KjYv18wU37 
 OK

**Comment by tkatsoulas** [comment]
From what I see you face the following issue; 

You updated your distro from Kinetic->Lunar. During the dist upgrade all the (predefault) repos are updated to match the new dist, for custom repos, the dist-upgrader do not know what to do. So the repo is looking for lunar packages. What you need is to update/edit your netdata repo source (possible under `/etc/apt/sources.list.d/netdata*` to match our lunar repo. This https://learn.netdata.cloud/docs/installing/native-linux-distribution-packages#manual-setup-of-deb-packages guide might help you , If you need further assistance with that feel free to ping us again here

**Comment by enkrypt3d** [comment]
uninstalling the agent and reinstalling fixed the core dump issue....
