### ISSUE TITLE
[Bug]: Postgres – pg_last_wal_receive_lsn() is used where it should be pg_last_wal_replay_lsn() 

### ISSUE THREAD

**Issue by NikolayS** [netdata/netdata#16175]
### Bug description

Checking how Postgres lag is measured in https://github.com/netdata/netdata/blob/9edcad92d83dba359f5eb6c06d0741b50030edcf/collectors/python.d.plugin/postgres/postgres.chart.py#L486, I've noticed that for replicas, pg_last_wal_receive_lsn() is used to determine the LSN position if we perform this analysis on a standby leader, not primary (the case with cascaded replication):

```
    pg_wal_lsn_diff(
      CASE pg_is_in_recovery()
        WHEN true THEN pg_last_wal_receive_lsn()
        ELSE pg_current_wal_lsn()
      END,
    replay_lsn) AS replay_delta
```

This looks strange – I would expect `pg_last_wal_replay_lsn()` here.

### Expected behavior

```
    pg_wal_lsn_diff(
      CASE pg_is_in_recovery()
        WHEN true THEN pg_last_wal_replay_lsn()
        ELSE pg_current_wal_lsn()
      END,
    replay_lsn) AS replay_delta
```

and so on for all other snippets

### Steps to reproduce

1.
2.
3.
...

### Installation method

kickstart.sh

### System info

```shell
n/a
```

### Netdata build info

```shell
n/a
```

**Comment by ilyam8** [comment]
Hey, @NikolayS. Thanks for the report!

A few things:

- You provided the link to the python Postgres collector. It was deleted a long time ago and is no longer in the repository.
- It was replaced by [go.d/postgres](https://github.com/netdata/go.d.plugin/tree/master/modules/postgres#postgresql). This is the link to the [file with queries](https://github.com/netdata/go.d.plugin/blob/master/modules/postgres/queries.go). Can you take a look?
