### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by targetdevos** [netdata/netdata#16178]
### Bug description

how to configure email alert with prometheous metrics graph  on grafana 10  linux 

### Expected behavior

how to configure email alert with prometheous metrics graph  on grafana 10  linux 

### Steps to reproduce

1.
2.
3.
...
how to configure email alert with prometheous metrics graph  on grafana 10  linux 

### Installation method

kickstart.sh

### System info

```shell
kk
```

### Netdata build info

```shell
please share doc
```

**Comment by ilyam8** [comment]
Hi, @targetdevos. This looks like a question, not a bug. Consider using GH discussion or Discord, see [Community](https://github.com/netdata/netdata/tree/v1.42.4#tada-community).
