### ISSUE TITLE
[Bug]: potential memleak in daemon/unit_test.c

### ISSUE THREAD

**Issue by icy17** [netdata/netdata#16174]
### Bug description

Potential memory leak in [sqlit3_open.](https://github.com/netdata/netdata/blob/master/daemon/unit_test.c#L1641) After calling sqlite3_open, the db_meta should be released before 1644 return statement.

### Expected behavior

use sqlite3_close to free the object before return.

### Steps to reproduce

None

### Installation method

other

### System info

```shell
None
```

### Netdata build info

```shell
None
```

**Comment by ilyam8** [comment]
Hey, @icy17. Thanks for reporting, but it doesn't look like a problem. Closing as wontfix. cc @stelfrag
