### ISSUE TITLE
[Bug]: Preventing access to locally installed instance if DNT flag enabled

### ISSUE THREAD

**Issue by stiray** [netdata/netdata#16206]
### Bug description

You are explicitly forbidding using of DNT flag with a false claim that the registry needs persistent cookies on browser to work. 

```Your web browser is sending 'DNT: 1' (Do Not Track). The registry requires persistent cookies on your browser to work.```

This is an obvious lie, there is no difference in per-session and persistent cookies.

I would like to mention, that you are on a very thin ground here: GDPR explicitly forbids trading users privacy for benefits and you are trying (quite badly if I may say) to blatantly step on user privacy rights.

It is perfectly understandable, that you are running into monetization where you will try to force non paying users to pay, but I must say that from all attempts I have seen in the past, you are really bad with this. Trying to violate GDPR to steal customers data, proving to potential future customers that you are unreliable and you might break in next update, you are becoming more and more unstable with over-complicated configurations (they have become a complete mess), telling potential customers lies about "permanent" cookies... I think it is a bad idea but its your product.

You should really rethink what you are doing, you don't need to burn down all the bridges to normal users, to get to corporate customers and monetize on them.

### Expected behavior

Behavior should not be broken without a warning and based on a lie.

### Steps to reproduce

Not relevant.

### Installation method

kickstart.sh

### System info

```shell
Not relevant.
```

### Netdata build info

```shell
Not relevant.
```

### Additional info

Not relevant.

**Comment by ktsaou** [comment]
@stiray this is not intentional. You can also install your own registry if you want. The Netdata agent can be a registry if you configure it.

Let's investigate what is happening...

**Comment by ilyam8** [comment]
<img width="1711" alt="Screenshot 2023-10-15 at 21 51 37" src="https://github.com/netdata/netdata/assets/22274335/e28c5866-f608-49c6-a59e-e72fa20ee961">

**Comment by ktsaou** [comment]
Thanks @ilyam8 

So, it seems that although the registry is sending an error (400, Bad Request), the UI tried to parse it as JSON and it crashed.

This is the bug.

**Comment by ktsaou** [comment]
@novykh please have a look.

**Comment by stiray** [comment]
> @stiray this is not intentional. You can also install your own registry if you want. The Netdata agent can be a registry if you configure it.
> 
> Let's investigate what is happening...

I have done my investigation. Gravatar, really? Now explain me how should anyone trust you previous "non deliberate" sending data to netdata domain and gravatar in UI? Are those cents that you get really worth doing that?

proxy_set_header DNT "";
sub_filter_types text/html application/json application/javascript;
sub_filter 'app.netdata.cloud'  '127.0.0.1';
sub_filter 'registry.my-netdata.io'  '127.0.0.1';
sub_filter 'netdata-news.cdn.prismic.io'  '127.0.0.1';
sub_filter 'www.gravatar.com'  '127.0.0.1';
sub_filter_once on;

**Comment by ktsaou** [comment]
@stiray intentional is only our will to have analytics enabled by default.

Bug is when we somehow fail to be transparent about this, or fail to provide an easy way to disable these analytics.

So, if for any reason, you want analytics disabled but you can't do it, or it is too complex to do it, we have a severe bug and we need to fix it asap, as we just did with the issue you were facing.

Thank you.
