### ISSUE TITLE
[Bug]: Kickstart script parameter '--auto-update-type' is not parsed

### ISSUE THREAD

**Issue by qrmt** [netdata/netdata#16226]
### Bug description

In the [kickstart script](https://github.com/netdata/netdata/blob/master/packaging/installer/kickstart.sh), script documentation on line [181](https://github.com/netdata/netdata/blame/fc465e0bf654c21858e4290b5bc927c645b58bcb/packaging/installer/kickstart.sh#L181) tells that it's possible to specify the type of auto update with `--auto-update-type`. 

However, this option is not parsed and results in fatal install script error `Unrecognized option --auto-update-type`. Instead, the script attempts to parse `--auto-update-method` on line [2137](https://github.com/netdata/netdata/blame/fc465e0bf654c21858e4290b5bc927c645b58bcb/packaging/installer/kickstart.sh#L2137).

### Expected behavior

Specifying `--auto-update-type` would be parsed correctly and install to succeed.

### Steps to reproduce

1. Download latest kickstart.sh script
2. Run the script with `--auto-update-type crontab`
3. Script fails due to unrecognized option

### Installation method

kickstart.sh

### System info

```shell
-
```

### Netdata build info

```shell
Applies to install script in latest master
```

**Comment by ilyam8** [comment]
Hey, the actual name is `--auto-update-method`. Try `--auto-update-method crontab` - will work now. But thanks for the report, we rename it to `--auto-update-type` in #16226.
