### ISSUE TITLE
[Feat]: systemd-journal UX issues

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#16223]
### Problem

Various improvements needed to systemd-journal.

### Description

- [ ] When in PLAY mode, the first click on the chart does a full query (no `data_only:false`). In slow big queries this is a problem, because on first click you need to wait again for a full query.
- [ ] When in PLAY mode, if the window loses focus for about 30 seconds, when it gets focus back, sometimes it does a full data refresh. This is again a problem on slow queries.
- [ ] When in PLAY mode, if the window loses focus for enough time so that the entire timeframe is now obsolete, it does `tail` request, resulting in wrong data rendered in the histogram. It should do a full query in this case (`anchor < after`).

### Importance

must have

### Value proposition

1. Do not unecessarily query the db
2. Always provide consistent and reliable data views

### Proposed implementation

@novykh

**Comment by ilyam8** [comment]
@ktsaou @novykh has this been fixed?
