### ISSUE TITLE
[Bug]: Slack alerts have an invalid link

### ISSUE THREAD

**Issue by plaidgravy** [netdata/netdata#16238]
### Bug description

Slack alerts have an invalid link.

Example link:
https://app.netdata.cloud/alarms/redirect?agentId=XXXXXXXXX&host=MYHOSTNAME&chart=mysql_local.connections_active&family=connections&alarm=mysql_connections&alarm_unique_id=1632861941&alarm_id=1667106716&alarm_event_id=73&alarm_when=1697191937&alarm_status=WARNING&alarm_chart=mysql_local.connections_active&alarm_value=70.8%25

I replaced the agentId and hostname in the example above, but they looked valid.

I end up on a page with:
404 Not Found
nginx

### Expected behavior

To be taken to my alert.

### Steps to reproduce

1.Get an alert, click on the link.

### Screenshots

![image](https://github.com/netdata/netdata-cloud/assets/1435193/42313dc2-4066-4f65-ae9f-da14ac398d5b)

### Desktop

Browser Version [e.g. 22]

**Comment by MrZammler** [comment]
Hi @plaidgravy 

What version of the agent are you running? Is your agent claimed to the cloud?

**Comment by ilyam8** [comment]
I think this issue has been fixed, closing. @plaidgravy, let us know if the problem still exists.
