### ISSUE TITLE
[Bug]: netdata uses obsoleted distutils module (removed since python 3.12)

### ISSUE THREAD

**Issue by vitlav** [netdata/netdata#16254]
### Bug description

netdata uses obsoleted distutils module

«Code that imports distutils will no longer work from Python 3.12.»

See https://peps.python.org/pep-0632/

### Expected behavior

Use other way to get module version

### Steps to reproduce

```
$ grep distutils collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py 
from distutils.version import StrictVersion as version
```

### Installation method

from source

### System info

```shell
$ name -a; grep -HvE "^#|URL" /etc/*release
bash: name: команда не найдена
/etc/altlinux-release:ALT Regular Sisyphus
```

### Netdata build info

```shell
$ sudo netdata -W buildinfo
Packaging:
    Netdata Version ____________________________________________ : v1.43.0
```

**Comment by MrZammler** [comment]
Hi @vitlav . Thanks for the report! I've opened a small PR to replace it.
