### ISSUE TITLE
[Bug]: netdata-go not found: create zip: modules/prometheus/integrations/cs:go.md: malformed file path "modules/prometheus/integrations/cs:go.md": invalid char ':'

### ISSUE THREAD

**Issue by driesmp** [netdata/netdata#16275]
### Bug description

In FreeBSD we use the following link to allow for an easy port installation. Going from v0.56.0 to v0.56.1 it stopped working.
The following error is displayed when trying to fetch from this location: 

> not found: create zip: modules/prometheus/integrations/cs:go.md: malformed file path "modules/prometheus/integrations/cs:go.md": invalid char ':'

https://[proxy.golang.org/github.com/netdata/go.d.plugin/@v/v0.56.1.mod](https://proxy.golang.org/github.com/netdata/go.d.plugin/@v/v0.56.1.mod)

https://[proxy.golang.org/github.com/netdata/go.d.plugin/@v/v0.56.0.mod](https://proxy.golang.org/github.com/netdata/go.d.plugin/@v/v0.56.0.mod)

### Expected behavior

The fetch link works as expect; and higher verisons:
https://[proxy.golang.org/github.com/netdata/go.d.plugin/@v/v0.56.1.mod](https://proxy.golang.org/github.com/netdata/go.d.plugin/@v/v0.56.1.mod)

### Steps to reproduce

Open in webbrowser and display error message

### Installation method

from source

### System info

```shell
[/usr/ports/net-mgmt/netdata-go] git:(main*)$ uname -a
FreeBSD freebsd.vm 15.0-CURRENT FreeBSD 15.0-CURRENT #0 main-n265954-fc9f1d2c6391: Sun Oct 15 18:05:08 CEST 2023     dries@freebsd.vm:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64

[/usr/ports/net-mgmt/netdata-go] git:(main*)$ uname -K
1500001
```

### Netdata build info

```shell
Irrelevant, this bug is with fetching sources.
```

**Comment by Ancairon** [comment]
Hey @driesmp, sorry for the inconvenience, I added the proper fix in the above-mentioned PR!

**Comment by driesmp** [comment]
No problem thanks for the fix! When will the links work again, eg
https://proxy.golang.org/github.com/netdata/go.d.plugin/@v/v0.56.3.mod

**Comment by ilyam8** [comment]
@driesmp https://proxy.golang.org/github.com/netdata/go.d.plugin/@v/v0.56.4.mod
