### ISSUE TITLE
Misaligned option points of REST API v1 endpoint data

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#1628]
http://localhost:19999/api/v1/data?chart=system.load?points=1 returns
```
{
 "labels": ["time", "load1", "load5", "load15"],
    "data":
 [

  ]
}
```
but should return 
```
{
 "labels": ["time", "load1", "load5", "load15"],
    "data":
 [
      [ new Date(2017,0,24,8,30,0), 3.21004, 4.08258, 4.61621]
  ]
}
```
which is the output of http://localhost:19999/api/v1/data?chart=system.load?points=2

Can somebody reproduce this?

**Comment by ktsaou** [comment]
Add `&options=unaligned`

Check: https://github.com/firehol/netdata/pull/253#issuecomment-214519674 by this is needed and why it is not enabled by default.

**Comment by simonnagl** [comment]
Thank you. That makes sense. But I think having this only documented in an closed issue is not what we want. If you leave that open after finishing the work on the `doxygen` branch I could continue there.

**Comment by ktsaou** [comment]
perfect!

**Comment by cakrit** [comment]
Todo: add info from #253 to docs, so that this can be closed.
