### ISSUE TITLE
[Feat]: go.d: add version to go.d.plugin config.tar.gz artifact

### ISSUE THREAD

**Issue by k0ste** [netdata/netdata#16280]
### Problem

Current naming of `config.tar.gz` file is lack of unique file name

### Description

The configs artifact provided like: https://github.com/netdata/go.d.plugin/releases/download/v0.56.3/config.tar.gz

### Importance

really want

### Value proposition

In some build cases it caused problems with local artifacts cache (in gitlab, for example). Where, between builds, the new version of package may have non-unique file name from previous build

### Proposed implementation

Provide file name with version number, like:
`https://github.com/netdata/go.d.plugin/releases/download/v0.56.3/go.d.plugin-config-v0.56.3.tar.gz` for example

**Comment by ilyam8** [comment]
starting from [v0.56.4](https://github.com/netdata/go.d.plugin/releases/tag/v0.56.4) there will be `go.d.plugin-config-{VERSION}.tar.gz`.

**Comment by k0ste** [comment]
> starting from [v0.56.4](https://github.com/netdata/go.d.plugin/releases/tag/v0.56.4) there will be `go.d.plugin-config-{VERSION}.tar.gz`.

Thanks for fast resolution 🤝
