### ISSUE TITLE
[Feat]: netdata should log to journal by default

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#16339]
### Problem

Today, Netdata logs to text files.

We should by default log to systemd-journal on systemd systems.

### Description

Netdata should be using the `sd_journal_send()` family of functions to push structured logs to systemd-journal. Structured are logs that have custom fields in them, annotating the main log message with additional information.

Such fields should be like:

- `ND_HOSTNAME`: the hostname of the host this log refers to
- `ND_INSTANCE`: the chart id this log refers to
- `ND_DIMENSION`: the dimension id this log refers to
- `ND_WORKER_KIND`: the kind of the thread logging this
- `ND_WORKER_NAME`: the unique identifier of the thread logging this
- `ND_PLUGIN`: the plugin name that logs this, such as `web_server`, `health`, `dbengine`, `P[go.d]`, etc.
- `ND_MODULE`: the module that this log entry is about, depending on the plugin that logs it.
- `ND_JOB`: the job identifier (if any)

External plugins and commands should push their messages to Netdata via a 3rd pipe (stderr), which then a worker in Netdata should get and annotate.

Our own logs should be in `logfmt` format, so that all annotations are always available.

### Importance

nice to have

### Value proposition

1. Netdata logs should be accessible via the systemd-journal

**Comment by ilyam8** [comment]
Implemented in #16357
