### ISSUE TITLE
Support OpenTSDB back-end via HTTP(S) API

### ISSUE THREAD

**Issue by rickatnight11** [netdata/netdata#1642]
I'd love to use `netdata` as a replacement metric collector to `tcollector` in my production environment, shipping metrics to an OpenTSDB cluster, while also gaining the benefit of better real-time metrics for my users.

Today `netdata` only supports the OpenTSDB telnet API for submitting metrics, which offers no encryption, authentication, or verification. That's a non-starter for any production environment, especially when the archival metric cluster is on the other side of a network boundary.

Supporting the HTTP(S) OpenTSDB API would greatly increase `netdata` traction in the metrics community.

**Comment by ktsaou** [comment]
nice. ok. This would require to link netdata with libcurl. We need this for a dozen of reasons and I have postponed it so far.

So, it might be time to do it...

**Comment by rickatnight11** [comment]
I'm happy to provide requirements and testing.  Just let me know what you need.  Some requirements off the top of my head:

* HTTP and HTTPS support
* Support for HTTP Basic Auth
* Ability to specify CA cert / truststore to explicitly trust OpenTSDB server
* Ability to specify TLS protocol (i.e. 1.2 only)
* Ability to specify supported ciphers and preference order

**Comment by ktsaou** [comment]
ok. weekend project then...

**Comment by Joshua2504** [comment]
Pls, implement this...

**Comment by DerDanilo** [comment]
Are we going somewhere? 

 "# This communication is not HTTP (it cannot be proxied by web proxies)."
https://github.com/netdata/netdata/blob/339d3341292aa6b46114a8ee8dc6eb69ecff80b7/streaming/stream.conf#L30

Communication should be encrypted and support https communication or other forms of encrypted communication. 
We'd love to use netdata for several projects but not being able to stream data protected is a huge blocker for those projects that are running in multiple data center, while having to route their traffic through public networks.

**Comment by cakrit** [comment]
@thiagoftsm please look into this one as well for the PR on https support.

**Comment by thiagoftsm** [comment]
This is officially a working in progress.

**Comment by thiagoftsm** [comment]
Hi @rickatnight11 and @DerDanilo , I finished to write the communication using HTTP API now, but while I was reading the official documentation of OpenTSDB I could not find direct support for SSL there on the other hand, I could see that OpenTSDB Proxy is used to authenticate users and to support SSL connections, so I am thinking to create a communication trought OpenTSDB Proxy for netdata uses encryptation when communicate with OpenTSDB. Tomorrow I will analyse another possibilites, but right now this looks like the better road to use.

Best Regards!

**Comment by rickatnight11** [comment]
Hey, @thiagoftsm!  We've long since switched to another metrics solution, but when we used OpenTSDB, we did, indeed, use a separate process to terminate HTTPS and reverse-proxy to OpenTSDB, which does not natively support HTTPS.  I believe this is standard practice in the industry.

**Comment by thiagoftsm** [comment]
Hi @rickatnight11 , I could see this! After to develop the functions to use the HTTP API, I am working with proxies to test the SSL. 
I cannot confirm this is "standard pratice" as you defined, but after to bring the HTTPS to Netdata, I can say for you that the documentation of the libraries to TLS in normal situation is not good, so this postpone the implementation.

Best regards!

**Comment by rickatnight11** [comment]
Understood. If it helps, any reverse-proxy implementation (like Nginx or even an AWS ELB) should do it.

**Comment by thiagoftsm** [comment]
Thank you! We used the nginx as reverse-proxy and our tests worked fine, now the code will be test by other coworkers and probably the next version will have the support to HTTP(S) already there.
