### ISSUE TITLE
[Feat]: Configure Alert Notifications，support dingtalk .

### ISSUE THREAD

**Issue by skycyan** [netdata/netdata#16468]
### Description

It is hoped that dingtalk[aliyun dingtalk] can be supported in alarm notifications.

**Comment by ilyam8** [comment]
Hi, @skycyan. Thanks for the feature request. But please open it using [Feature Request](https://github.com/netdata/netdata/issues/new?assignees=&labels=feature+request%2Cneeds+triage&projects=&template=FEAT_REQUEST.yml&title=%5BFeat%5D%3A+) template.
