### ISSUE TITLE
[Bug]: Sources disagree on hashes for supposely identical version '2-2' of 'netdata-repo:amd64'

### ISSUE THREAD

**Issue by Nantris** [netdata/netdata#16549]
### Bug description

https://repo.netdata.cloud/repos/repoconfig/debian/bullseye/ and https://repo.netdata.cloud/repos/stable/debian/bullseye/ have differing hashes for `netdata-repo_2-2+debian11_all.deb`

### Expected behavior

Identical hashes

### Steps to reproduce

`apt upgrade`

### Installation method

other

### System info

```shell
Linux computername 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
n
```

**Comment by tkatsoulas** [comment]
Q: did the package manager complain or did you perform a manual checksum? 

CC @Ferroin

**Comment by Slapbox** [comment]
Thanks for your reply. Both. And across two separate machines with regards to the package managers.

**Comment by tkatsoulas** [comment]
Yes we have a problem with the packages, we will resolve this asap

**Comment by Slapbox** [comment]
Any update @tkatsoulas? I thought this was resolved but today when I went to actually upgrade it appears to be back.

**Comment by Ferroin** [comment]
@Slapbox Sorry about the lack of further updates on this.

What you’re seeing is a result of how we handle repository signatures on packages (effectively, the code handling that ‘sees’ a different instance of a package for each repository it’s in, and each of those instances gets signed separately, so the signed files end up being different).

We had updated the repository handling code to only publish the repository config packages in the `repoconfig` repository, but apparently had forgotten to clean up the old copies of them that were already in the other repositories, hence why you’re still seeing the issue.

I’ve now cleaned up those old packages, so you should no longer see any issues.

**Comment by Slapbox** [comment]
I think it's looking good now. Thanks for your help @Ferroin!

**Comment by Slapbox** [comment]
@Ferroin I'm seeing the same issue again. I already tried cleaning our local caches, but still, `W: Sources disagree on hashes for supposely identical version '2-2' of 'netdata-repo:amd64'.`

**Comment by Nantris** [comment]
This issue is ongoing and it's extremely tedious to still need to be holding this package back every time we upgrade the system. It's been going on for nearly 4 months now.

@Ferroin @tkatsoulas will there be a resolution to this?

**Comment by ilyam8** [comment]
Hey, @Nantris, is the problem still occurring?

**Comment by Nantris** [comment]
I don't believe so. I'll re-open if I find otherwise. Thank you all for getting this resolved.

**Comment by Ferroin** [comment]
@Nantris Sorry about the long and recurring lack of attention on this. It should be well and truly fixed now since we’ve switched from archive signing DEB packages on the repository host itself to origin signing them as part of the CI jobs that build and publish them, so the signatures should be identical for a given version no matter what repo or host it’s being served from.
