### ISSUE TITLE
[Feat]: May I ask if it is possible to automatically monitor the k8s cluster like Prometheus+Consul

### ISSUE THREAD

**Issue by cfy3133** [netdata/netdata#16550]
### Description

Distributed and service-oriented systems provide services for service registration, service discovery, and configuration management, offering functions such as service registration/discovery, health checks, key/value storage, multiple data centers, and distributed consistency assurance.

### Importance

nice to have

### Value proposition

1. Reduce the main configuration file to prevent it from becoming too bulky
2. Decoupling services through files facilitates dynamic service changes

**Comment by ilyam8** [comment]
Hey, @cfy3133. Thanks for the feature request, but I suggest being more specific. It is not clear what "automatically monitor the k8s cluster like Prometheus+Consul" is. The description you provided looks like a copy/paste from Consul website. I suggest to open a GH discussion and there we discuss the subject.
