### ISSUE TITLE
[Feat]: Add support for ups.realpower from NUT

### ISSUE THREAD

**Issue by etienn01** [netdata/netdata#16619]
### Problem

  https://github.com/netdata/netdata/issues/14396 added support for UPS load in watts, based on `ups.load` and `ups.realpower.nominal`, but my UPS does not report `ups.realpower.nominal`.

### Description

The UPS I'm running (Eaton Ellipse PRO 850) does not report `ups.realpower.nominal` and the `upsd.ups_load_usage` graph is empty; but it reports `ups.realpower` "Current value of real power (Watts)" which is the load in watts as reported by the UPS itself.

⚠️ Not to be confused with `ups.power` which is the "Current value of apparent power (Volt-Amps)".
  
  <details>
  <summary>upsc output</summary>
  
  ```
  battery.charge: 100
  battery.charge.low: 20
  battery.runtime: 3328
  battery.type: PbAc
  device.mfr: EATON
  device.model: Ellipse PRO 850
  device.serial: P357H28RG3
  device.type: ups
  driver.name: usbhid-ups
  driver.parameter.pollfreq: 5
  driver.parameter.pollinterval: 2
  driver.parameter.port: auto
  driver.parameter.synchronous: auto
  driver.version: 2.8.0
  driver.version.data: MGE HID 1.46
  driver.version.internal: 0.47
  driver.version.usb: libusb-1.0.26 (API: 0x1000109)
  input.frequency: 50.0
  input.transfer.high: 285
  input.transfer.low: 165
  input.voltage: 237.0
  input.voltage.extended: no
  outlet.1.desc: PowerShare Outlet 1
  outlet.1.id: 2
  outlet.1.status: on
  outlet.1.switchable: no
  outlet.2.desc: PowerShare Outlet 2
  outlet.2.id: 3
  outlet.2.status: on
  outlet.2.switchable: no
  outlet.desc: Main Outlet
  outlet.id: 1
  outlet.switchable: no
  output.frequency: 50.0
  output.frequency.nominal: 50
  output.voltage: 238.0
  output.voltage.nominal: 230
  ups.beeper.status: enabled
  ups.delay.shutdown: 20
  ups.delay.start: 30
  ups.firmware: 01.16.0020
  ups.load: 9
  ups.mfr: EATON
  ups.model: Ellipse PRO 850
  ups.power: 81
  ups.power.nominal: 850
  ups.productid: ffff
  ups.realpower: 43
  ups.serial: P357H28RG3
  ups.status: OL
  ups.timer.shutdown: -1
  ups.timer.start: -1
  ups.vendorid: 0463
  ```
  </details>

### Importance

really want

### Value proposition

  1. Increased compatibility of power reporting for a wider range of UPS models
  2. Enhanced accuracy: when available, the `ups.realpower` metric provides the actual power load in watts as reported by the UPS

### Proposed implementation

Maybe give priority to `ups.realpower` for the `upsd.ups_load_usage` metric and, if not available, fallback to computing the value based on `ups.load` and `ups.realpower.nominal`.

**Comment by ilyam8** [comment]
Hi, @etienn01. Thanks for the request! Implemented in netdata/go.d.plugin#1444. Will be available in the nightly next week.
