### ISSUE TITLE
[Feat]: Create `systemd-journal` group in Docker container

### ISSUE THREAD

**Issue by marvinruder** [netdata/netdata#16612]
### Problem

On a Fedora-flavored host server, the journal logs have the access rights

```
-rw-r-----+ 1 root systemd-journal
```

making them readable only for users in the `systemd-journal` group. This group does not exist in the Netdata Docker container, so the `netdata` user cannot access them and no log lines are shown in the Netdata Cloud UI.

### Description

Create the user group `systemd-journal` (with `gid 190`) and add the user `netdata` (with `gid 201`) to it as part of the Docker image creation.

### Importance

nice to have

### Value proposition

1. Users can access journal logs without having to tinker with the access rights of their journal files.

### Proposed implementation

Add to the Dockerfile: 

```
RUN echo "systemd-journal:x:190:netdata" > /etc/group
```

Alternatively, run the appropriate `groupadd` command in the Dockerfile:

```
RUN groupadd -g 190 -U netdata systemd-journal
```

**Comment by ilyam8** [comment]
Hey, @marvinruder. This is not necessary, the systemd-journal plugin has the setuid bit set inside Docker. Journal data is readable by members of the `systemd-journal` group on all systems. Systemd-journal plugin works in Docker if you mount `/var/log` to `/host/var/log` (or `/run/log/` to `/host/run/log` if journald storage mode is not persistent).

**Comment by marvinruder** [comment]
Apologies, after your comment I checked again and found that `setuid` did not work because of the `security-opt=no-new-privileges` being set on the container. It works fine after removing that option.
