### ISSUE TITLE
alarms: min/max and flood prevention

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#1663]
1. When an alarm is CLEARed, we already know the time it was raised. It would be nice to also know the min and max value (i.e. the range) of value it had.

2. When multiple alarms are triggered together (i.e. last collected), it would be nice to have a threshold to delay the notifications for an iteration or two. It would also be nice if we could receive a combo alarm, stating all of the raised alarms together.

**Comment by ktsaou** [comment]
@cakrit this is about providing more meaningful and useful alarm notifications.
I am closing it, but please add it together with the other alarm features.

**Comment by cakrit** [comment]
No reason to close it then, assigning to me for now.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
