### ISSUE TITLE
Add macOS and freeBSD to travis.

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#1667]
As we now official support macOS and freeBSD we should add at least build tests to travis to prevent breaking things with new changes.

**Comment by vlvkobal** [comment]
While it is possible for macOS, I can't find easy ways to implement FreeBSD build tests. I might be wrong. I don't have any experience with travis. Here is some information I found:
https://github.com/travis-ci/travis-ci/issues/6671
http://erouault.blogspot.com/2016/09/running-freebsd-in-travis-ci.html

**Comment by simonnagl** [comment]
You are right. Travis does not support FreeBSD. I could not find a workaround with travis too. Maybe someone else knows an CI tool supporting FreeBSD.

**Comment by ktsaou** [comment]
@simonnagl check this log: http://pastebin.com/6XP6xsp5

macos builds netdata twice and gives way too many errors...

**Comment by ktsaou** [comment]
on travis I meant...

**Comment by simonnagl** [comment]
> travis builds macOS twice

Yes, it does this for linux too. Once with `./autogen.sh && ./configure && make -j4 and then `./netdata-installer.sh --install $HOME --dont-wait --dont-start-it`.
I think it is OK.

Do you mean this errors?
```
$ for i in *.tar.*; do md5sum -b $i > $i.md5; sha512sum -b $i > $i.sha; done
/Users/travis/build.sh: line 59: md5sum: command not found
/Users/travis/build.sh: line 59: sha512sum: command not found
/Users/travis/build.sh: line 59: md5sum: command not found
/Users/travis/build.sh: line 59: sha512sum: command not found
/Users/travis/build.sh: line 59: md5sum: command not found
/Users/travis/build.sh: line 59: sha512sum: command not found
```
This is an after success hook generating hashes of the generated binaries. These commands have different names on macOS. Because of this the next command fails too. We only deploy the linux gcc build binaries so this is OK. If you want me to remove the post builds steps from the macOS travis builds please tell me. I can try.

**Comment by ktsaou** [comment]
> ./autogen.sh && ./configure && make -j4 and then./netdata-installer.sh --install $HOME --dont-wait --dont-start-it

Why don't we run just the installer?

> If you want me to remove the post builds steps from the macOS travis builds please tell me. I can try.

it is ok, if this is intentional.

**Comment by simonnagl** [comment]
> Why don't we run just the installer?

I do not know. This was already there and I expected there is a reason for it.

**Comment by ktsaou** [comment]
I think there was no reason. It is probably a left-over from the time the installer was not compiling netdata...

**Comment by ktsaou** [comment]
I removed the duplicate compilation at #1771

**Comment by ktsaou** [comment]
MacOS is already in travis.
FreeBSD is not supported by travis.

So, I am closing this.
