### ISSUE TITLE
[Feat]: Add option of alert to logs section

### ISSUE THREAD

**Issue by roysG** [netdata/netdata#16670]
### Problem

I need to add some alert notification in case there is an error message or some message that i want to check if shown
Today i do not have any option like that

### Description

It will makes an easier life in case i will have an alert button to make on speicifc text i need to know about that.
Same as you added now for the monitor

### Importance

nice to have

### Value proposition

 When some problem is happened, it will be much easier to track it also by specific text alert we decide

**Comment by ilyam8** [comment]
@roysG Thanks for the request, but could you please clarify and provide more details - it's unclear what your request is about.

> need to add some alert notification in case there is an error message

Are you referring to your application logs? error message where? What do you use to monitor them?

> option of alert to logs section

`[logs]` in `netdata.conf` is [Netdata logging](https://github.com/netdata/netdata/tree/master/libnetdata/log), it has nothing to do with alerting. If you mean this section - no, we can't add some alert option to it.
