### ISSUE TITLE
Ceph support

### ISSUE THREAD

**Issue by hameno** [netdata/netdata#1673]
I'm currently playing with a simple 3-node Proxmox cluster with ceph shared storage. 
I think it would be great to have charts for ceph, e.g. pg statistics, read / write bandwidth, iops, used / free, osd counts (in/out,down/up), monitors, pools and more.

I'm fairly new to ceph so I probably cannot help much, but I can help testing. Maybe someone with more ceph / netdata knowledge could help creating a plugin...

Some links that may be useful:
* http://docs.ceph.com/docs/master/rados/operations/monitoring/
* http://docs.ceph.com/docs/master/rados/operations/monitoring-osd-pg/
* http://crapworks.de/post/ceph-monitoring/

**Comment by l2isbad** [comment]
If nobody willing to do it i can try.
The main problem is 

> Maybe someone with more ceph / netdata knowledge

Literally zero ceph knowledge :cold_sweat:

So i need a time to setup a lab, to read about ceph infrastructure, see how it is implemented in other monitoring systems. This weekend probably!

**Comment by martijn-dekkers** [comment]
@l2isbad I have some ceph knowledge, and a working cluster. However, not much netdata knowledge. Maybe we can work together?

**Comment by l2isbad** [comment]
>  I have some ceph knowledge, and a working cluster.

Great! 

According 
http://docs.ceph.com/docs/master/rados/operations/monitoring/
and
http://docs.ceph.com/docs/hammer/rados/operations/monitoring-osd-pg/

We have to execute a lot of different commands to monitor ceph cluster/osds/pgs..
Do we need all of them?

Still.. i need to setup a lab 😄

**Comment by martijn-dekkers** [comment]
@l2isbad Awesome. This is some basic info about monitoring: https://sysdig.com/blog/monitor-ceph-top-5-metrics-watch/#builtin which might be a good place to start. If you want, you can access my Ceph cluster.

**Comment by CrackerJackMack** [comment]
I have a ceph cluster (using a non-default 'ceph' cluster name) for my own home use...it's a horrible addiction.  I also have a salt formula I've smashed together so I can build from git.   I have netdata set up on everything already streaming to a single "master" and everything works swimmingly.  Please feel free to reach out to me if have any additional questions about ceph or if you want certain data command outputs from a running ceph cluster.

This is all non-work related so nothing other than the IPv6's of my hosts would result in data leakage.

```
    cluster f9e6d318-c3e3-4971-b569-b7492c1f921b
     health HEALTH_OK
     monmap e3: 3 mons at {hatter=[2001:xxx:xxx:ceff::18]:6789/0,sulley=[2001:xxx:xxx:ceff::10]:6789/0,willow=[2001:xxx:xxx:ceff::16]:6789/0}
            election epoch 46, quorum 0,1,2 sulley,willow,hatter
      fsmap e35: 1/1/1 up {0=sulley=up:active}, 2 up:standby
     osdmap e1217: 13 osds: 13 up, 13 in
            flags sortbitwise,require_jewel_osds
      pgmap v3793675: 1288 pgs, 4 pools, 12255 GB data, 3595 kobjects
            12271 GB used, 29391 GB / 41663 GB avail
                1288 active+clean
  client io 23772 B/s rd, 21355 B/s wr, 1 op/s rd, 4 op/s wr
```

```
-1 40.68640 root default
-2 11.70558     host willow
 0  2.69910         osd.0        up  1.00000          1.00000
 1  2.69910         osd.1        up  1.00000          1.00000
 2  3.60829         osd.2        up  1.00000          1.00000
 4  2.69910         osd.4        up  1.00000          1.00000
-3 10.79639     host sulley
 5  2.69910         osd.5        up  1.00000          1.00000
 6  2.69910         osd.6        up  1.00000          1.00000
 7  2.69910         osd.7        up  1.00000          1.00000
 3  2.69910         osd.3        up  1.00000          1.00000
-4 18.18443     host hatter
 8  3.63689         osd.8        up  1.00000          1.00000
 9  3.63689         osd.9        up  1.00000          1.00000
10  3.63689         osd.10       up  1.00000          1.00000
11  3.63689         osd.11       up  1.00000          1.00000
12  3.63689         osd.12       up  1.00000          1.00000
```

**Comment by k0ste** [comment]
Better to use rados python lib to get HEALTH status of cluster.
Actually, some things netdata can grab from this project [Crapworks/ceph-dash](https://github.com/Crapworks/ceph-dash).

**Comment by lets00** [comment]
I am writting a ceph plugin to netdata. This is the actual progress: https://github.com/firehol/netdata/pull/3166 and I am currently using it in production. If anyone can test or suggest tips/improvements, I'd be really grateful.
