### ISSUE TITLE
[Bug]: Error compiling netdata 1.44.1

### ISSUE THREAD

**Issue by tiagogaspar8** [netdata/netdata#16785]
### Bug description

I'm trying to update OpenWrt's netdata package to version 1.44.1.
Also, for version 1.43.2, it compiles with the same makefile, but netdata's logs don't show up in syslog.

### Expected behavior

Netdata should build.

### Steps to reproduce

1. Update the makefile version
2. Compile
3. Build fails

### Installation method

from source

### System info

```shell
This is the information from the build system:
$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux fedora 6.6.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan  1 20:05:54 UTC 2024 x86_64 GNU/Linux
/etc/fedora-release:Fedora release 39 (Thirty Nine)
/etc/os-release:NAME="Fedora Linux"
/etc/os-release:VERSION="39 (Workstation Edition)"
/etc/os-release:ID=fedora
/etc/os-release:VERSION_ID=39
/etc/os-release:VERSION_CODENAME=""
/etc/os-release:PLATFORM_ID="platform:f39"
/etc/os-release:PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
/etc/os-release:ANSI_COLOR="0;38;2;60;110;180"
/etc/os-release:LOGO=fedora-logo-icon
/etc/os-release:CPE_NAME="cpe:/o:fedoraproject:fedora:39"
/etc/os-release:DEFAULT_HOSTNAME="fedora"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Fedora"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=39
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Fedora"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION=39
/etc/os-release:SUPPORT_END=2024-11-12
/etc/os-release:VARIANT="Workstation Edition"
/etc/os-release:VARIANT_ID=workstation
/etc/redhat-release:Fedora release 39 (Thirty Nine)
/etc/system-release:Fedora release 39 (Thirty Nine)
~
```

### Netdata build info

```shell
This is the error that I get when building netdata:
make[5]: Entering directory '/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1'
aarch64-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I.   -DVARLIB_DIR="\"/var/lib/netdata\"" 	-DCACHE_DIR="\"/var/cache/netdata\"" 	-DCONFIG_DIR="\"/etc/netdata\"" 	-DLIBCONFIG_DIR="\"/usr/lib/netdata/conf.d\"" 	-DLOG_DIR="\"/var/log/netdata\"" 	-DPLUGINS_DIR="\"/usr/lib/netdata/plugins.d\"" 	-DRUN_DIR="\"/var/run/netdata\"" 	-DWEB_DIR="\"/usr/share/netdata/web\""    -I/mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/include/uuid           -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1=netdata-v1.44.1 -ffunction-sections -fdata-sections -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -O3  -fexceptions         -I/mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/include/uuid                         -I /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1/libnetdata/libjudy/src          -fstack-clash-protection -mbranch-protection=standard -c -o aclk/aclk_util.o aclk/aclk_util.c
aclk/aclk_util.c: In function 'base64_encode_helper':
aclk/aclk_util.c:466:5: error: unknown type name 'EVP_ENCODE_CTX'
  466 |     EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();
      |     ^~~~~~~~~~~~~~
aclk/aclk_util.c:466:27: warning: implicit declaration of function 'EVP_ENCODE_CTX_new' [-Wimplicit-function-declaration]
  466 |     EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();
      |                           ^~~~~~~~~~~~~~~~~~
aclk/aclk_util.c:466:27: warning: initialization of 'int *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
aclk/aclk_util.c:467:5: warning: implicit declaration of function 'EVP_EncodeInit' [-Wimplicit-function-declaration]
  467 |     EVP_EncodeInit(ctx);
      |     ^~~~~~~~~~~~~~
aclk/aclk_util.c:468:5: warning: implicit declaration of function 'EVP_EncodeUpdate' [-Wimplicit-function-declaration]
  468 |     EVP_EncodeUpdate(ctx, str, outl, in, in_len);
      |     ^~~~~~~~~~~~~~~~
aclk/aclk_util.c:470:5: warning: implicit declaration of function 'EVP_EncodeFinal' [-Wimplicit-function-declaration]
  470 |     EVP_EncodeFinal(ctx, str, &len);
      |     ^~~~~~~~~~~~~~~
aclk/aclk_util.c:482:5: warning: implicit declaration of function 'EVP_ENCODE_CTX_free' [-Wimplicit-function-declaration]
  482 |     EVP_ENCODE_CTX_free(ctx);
      |     ^~~~~~~~~~~~~~~~~~~
make[5]: *** [Makefile:8372: aclk/aclk_util.o] Error 1
make[5]: Leaving directory '/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1'
make[4]: *** [Makefile:10843: all-recursive] Error 1
make[4]: Leaving directory '/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1'
make[3]: *** [Makefile:5092: all] Error 2
make[3]: Leaving directory '/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1'
make[2]: *** [Makefile:109: /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1/.built] Error 2
make[2]: Leaving directory '/mnt/openwrt/ss_mod/feeds/packages/admin/netdata'
time: package/feeds/packages/netdata/compile#12.06#3.41#15.39
    ERROR: package/feeds/packages/netdata failed to build.
```

### Additional info

Makefile:
```
#
# Copyright (C) 2008-2016 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=netdata
PKG_VERSION:=1.43.2
PKG_RELEASE:=1

PKG_MAINTAINER:=Josef Schlehofer <pepe.schlehofer@gmail.com>, Daniel Engberg <daniel.engberg.lists@pyret.net>
PKG_LICENSE:=GPL-3.0-or-later
PKG_LICENSE_FILES:=COPYING
PKG_CPE_ID:=cpe:/a:my-netdata:netdata

PKG_SOURCE:=$(PKG_NAME)-v$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://github.com/netdata/netdata/releases/download/v$(PKG_VERSION)
PKG_HASH:=d4a7ea2717ac7c8f04865f18e13aeaa0a36784156059f1b5ced75a44f74afc4d
PKG_BUILD_DIR=$(BUILD_DIR)/$(PKG_NAME)-v$(PKG_VERSION)

PKG_INSTALL:=1
PKG_BUILD_PARALLEL:=1
PKG_FIXUP:=autoreconf
PKG_BUILD_FLAGS:=no-mips16 gc-sections

include $(INCLUDE_DIR)/package.mk

define Package/netdata
  SECTION:=admin
  CATEGORY:=Administration
  DEPENDS:=+zlib +libuuid +libuv +libmnl +libjson-c +libyaml +libstdcpp +libatomic
  TITLE:=Real-time performance monitoring tool
  URL:=https://www.netdata.cloud/
endef

define Package/netdata/description
  netdata is a highly optimized Linux daemon providing real-time performance
  monitoring for Linux systems, applications and SNMP devices over the web.

  If you want to use Python plugins install python3, python3-yaml and
  python3-urllib3
endef

TARGET_CFLAGS := $(filter-out -O%,$(TARGET_CFLAGS)) -O3

CONFIGURE_ARGS += \
	--with-math \
	--without-libcap \
	--disable-cloud \
	--disable-dbengine \
	--disable-ebpf \
	--disable-h2o \
	--disable-ml \
	--disable-openssl \
	--disable-plugin-cups \
	--disable-plugin-freeipmi \
	--disable-plugin-nfacct \
	--disable-plugin-xenstat \
	--disable-unit-tests \
	--disable-x86-sse \

define Build/Configure
	$(SED) 's/m4_esyscmd(\[git describe .*\])/$(PKG_VERSION)/' $(PKG_BUILD_DIR)/configure.ac
	$(Build/Configure/Default)
endef

define Package/netdata/conffiles
/etc/netdata/
endef

define Package/netdata/install
	$(INSTALL_DIR) $(1)/usr/sbin
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/sbin/netdata $(1)/usr/sbin

	$(INSTALL_DIR) $(1)/etc/netdata
	$(CP) $(PKG_INSTALL_DIR)/etc/netdata $(1)/etc
	$(INSTALL_DATA) ./files/netdata.conf $(1)/etc/netdata
	touch $(1)/etc/netdata/.opt-out-from-anonymous-statistics

	$(INSTALL_DIR) $(1)/etc/init.d
	$(INSTALL_BIN) ./files/netdata.init $(1)/etc/init.d/netdata

	$(INSTALL_DIR) $(1)/usr/lib
	$(CP) $(PKG_INSTALL_DIR)/usr/lib/netdata $(1)/usr/lib

	$(INSTALL_DIR) $(1)/usr/share/netdata
	$(CP) $(PKG_INSTALL_DIR)/usr/share/netdata $(1)/usr/share
	rm $(1)/usr/share/netdata/web/demo*html
	rm $(1)/usr/share/netdata/web/fonts/*.svg
	rm $(1)/usr/share/netdata/web/fonts/*.ttf
	rm $(1)/usr/share/netdata/web/fonts/*.woff
	rm $(1)/usr/share/netdata/web/images/*.png
	rm $(1)/usr/share/netdata/web/images/*.gif
	rm $(1)/usr/share/netdata/web/images/*.ico
	rm -rf $(1)/usr/share/netdata/web/old
endef

$(eval $(call BuildPackage,netdata))
```

As for patches, I'm using the patches from this PR, which is for an older version:
https://github.com/openwrt/packages/pull/22677

**Comment by tkatsoulas** [comment]
@tiagogaspar8  this is not an easy-to-resolve issue. But I would love to elaborate on solving that to pave the road and help the openWRT (upstream) contributors at some point to update the package to the latest. 

First of all, is your openWRT device strong enough to handle our static builds? if yes, install those and you are ok, still netdata may be your biggest resource utilization software on the node in question, which is not optimal.

Otherwise, a good starting point is to check how the openWRT community packaged netdata until a* point. 

https://github.com/openwrt/packages/blob/openwrt-22.03/admin/netdata/Makefile, especially the configure options and the patches https://github.com/openwrt/packages/tree/openwrt-22.03/admin/netdata/patches

Now to give you an example of what will never work in a thin client deployment with openWRT.

- v2 dashboard
- db engine
- ACLK (for cloud)
- ML capabilities
- functions
- We switch to CMake build system, this may be a roadblock too

Certainly, I forget a lot.

In my honest opinion, you lose so much from the Netdata even if you build a package  UNLESS you manage to enable streaming. 

With streaming you can use a thin deployment of Netdata (openWRT package) on your openWRT devices and stream metrics to a centralized parent. Then you can even utilize cloud capabilities.

**Comment by tiagogaspar8** [comment]
Hi @tkatsoulas,

Sorry for my delay, I may take time but I always answer! 😄 

> this is not an easy-to-resolve issue. But I would love to elaborate on solving this to pave the road and help the openWRT (upstream) contributors at some point to update the package to the latest.

Oof, getting scared ahaha

> This is because we change our build system to CMake only.

What does this mean? I can adapt to it if I have an example. From the openwrt packages repo do you know of any package that is CMake only?

> Second, is your openWRT device strong enough to handle our static builds? if yes, install those and you are ok, still netdata may be your biggest resource utilization software on the node in question, which is not optimal.

This is actually not a concern, because I ultimately want to create variants, with more and fewer features, for example, metadata-full and netdata-tiny, for now, I just want to be able to build netdata, later I will give users the power to adapt netdata capabilities to their devices.

> Now to give you an example of what will never work in a thin client deployment with openWRT.

Why do you say this?

> With streaming you can use a thin deployment of Netdata (openWRT package) on your openWRT devices and stream metrics to a centralized parent. Then you can even utilize cloud capabilities.

How do I enable that?
That is a good idea, but I need to be able to build a full nedtata version.

In this case, I want to mimic the package that was available previously, it needs to remove every "extra" feature (openssl, ml, dbengine, etc.) except the web interface.

With these disabled, I am facing an error as you see, and I think that is because that section of the code is not commented out as it's supposed to be (?) not sure really.

**Comment by ilyam8** [comment]
@tiagogaspar8 can you please update "Steps to reproduce"? We need all commands to see what you were doing and try to replicate it, including the steps you do to get Netdata source code. As it is now - I can't reproduce, Netdata build doesn't fail for me.

**Comment by ilyam8** [comment]
> This is because we change our build system to CMake only.

The CMake change is not in v1.44.1, it will be in v1.45.0.

**Comment by tiagogaspar8** [comment]
Hi @ilyam8,

If you check out the link I posted to my current OpenWRT pull request you can see that I tagged the developers and they are aware that I'm doing this, also, if they were able to update netdata they would.

We are indeed building for OpenWRT, inside its building environment, and it is failing with version 1.44.1, while 1.43.2 builds fine.


From the build log, I can see that the function `EVP_ENCODE_CTX` is being referenced.
After some searching it seems that this is an openssl feature and I have passed the `--disable-openssl`, so it should not be called.

Going to the file I can see that there is a `#if defined(OPENSSL_VERSION_NUMBER) && OPENSSL_VERSION_NUMBER < OPENSSL_VERSION_110` but it ends right after this function starts, which is probably not correct?

Maybe I'm wrong, but why does this `EVP_ENCODE_CTX` function from OpenSSL get called when `--disable-openssl` is passed?

In the end I think this commit broke the build:
https://github.com/netdata/netdata/commit/db8bde8e5af3b8fa856f4263bc9c368c8aea57d6
