### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SigmaEnterprise** [netdata/netdata#16796]
### Bug description

Cannot install on windows

Get this error when trying to install

out-file : Could not find a part of the path 'C:\tmp\netdata-kickstart.sh'.
At line:1 char:1
+ curl https://get.netdata.cloud/kickstart.sh > /tmp/netdata-kickstart. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

### Expected behavior

Download installer

### Steps to reproduce

Cannot install on windows

Get this error when trying to install

out-file : Could not find a part of the path 'C:\tmp\netdata-kickstart.sh'.
At line:1 char:1
+ curl https://get.netdata.cloud/kickstart.sh > /tmp/netdata-kickstart. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

### Installation method

kickstart.sh

### System info

```shell
Windows
```

### Netdata build info

```shell
not running
```

### Additional info

I am reaching out to seek your expertise and assistance with installing Netdata on my Windows machine.

I have encountered challenges using 'wget' or 'curl' commands for installation, and I am unsure of the appropriate steps to proceed with the installation on a Windows environment.

If you could provide guidance on the correct installation process or recommend alternative methods suitable for Windows, I would be immensely grateful.

I value your expertise and am confident that with your assistance, I can successfully set up Netdata on my machine.

Thank you very much for considering my request. I look forward to your guidance and appreciate your time and support.

**Comment by tkatsoulas** [comment]
Hello @SigmaEnterprise. I'm afraid that this is not possible. Netdata Agent deployment  itself (installation) is not available on Windows machines, but you have a way to monitor them. Please consult this guide https://www.netdata.cloud/windows-monitoring/ to better understand how you can achieve this.


There is also a second way that you may bump into (deploy a netdata instance/Agent on WSL2, https://github.com/netdata/msi-installer) in our docs but I would advise you not to go down this road.

**Comment by tkatsoulas** [comment]
Closing this issue. If you find any gap in our docs while setting up monitoring for your windows instances feel free to reopen it.

**Comment by SigmaEnterprise** [comment]
Thanks so much , I understand the use-case now.
