### ISSUE TITLE
[Question] Federating Netdata metrics via Prometheus /federate API (gone AWOL after changing Netdata Streaming)

### ISSUE THREAD

**Issue by AidanMcP** [netdata/netdata#16801]
### Bug description

Hi folks, Apologies for the high-level question, which isn’t perhaps a Netdata problem, but I’ve had some great guidance from this community in the past, and although the problem appears in Prometheus, I ask my question here as the Netdata setup is the variable between OK and not-OK ! I think is is unlikely to be a bug - more likely a setup or understanding issue

Basically, I’ve having problems with streaming Netdata metrics through [Prometheus Federate API ](https://prometheus.io/docs/prometheus/latest/federation/)after changing 2 things in Netdata. I appreciate the versions are very old, but the question is around setup, and what am I missing!? 

**Before**
Netdata 1.31.0 child nodes streaming application metrics to Netdata parent node
Prometheus-A scraping from parent Netdata node – all OK
Prometheus-B successfully scraping metrics from Prometheus-A  via federate API – all OK

**After:**
Netdata 1.34.1 nodes publishing application metrics (no Netdata streaming)
Prometheus-A scraping from individual child nodes (approx. 20 nodes) – all OK
Grafana reading from Prometheus-A – all OK
Prometheus-B scraping metrics from Prometheus-A via federate API – NOT OK

Can see this via curl – the application metrics have gone **AWOL**:

curl -s -k --globoff [http://<host>:9090/federate?'match[]={job=~"netdata-scrape"}](http://%3chost%3e:9090/federate?'match%5b%5d=%7bjob=~%22netdata-scrape%22%7d)'

and I only see:
1 netdata_host_tags_info
2 scrape_duration_seconds
3 scrape_samples_post_metric_relabeling
4 scrape_samples_scraped
5 scrape_series_added
6 up

Question

- Has anyone any ideas, why changing Netdata setup, could mess up Prometheus Federate API, but not mess up the metrics as called via: api/v1/query_range/

i.e.
curl   "http://<host>:<port>/api/v1/query_range?query=netdata_my_missing_metrics&start=`date --date='-1 min' +%s`&end=`date +%s`&step=60s" | python -m json.tool | more

is OK

Having read some articles stating that Prometheus Federate API, was ‘flaky’ / ‘brittle’,  I moved to latest stable version, 2.45.2, so I don't think this is a Prometheus problem

Any hints or suggestions from this community would be really appreciated!!!

Thanks!!
Aidan

### Expected behavior

metrics to be available in 

curl -s -k --globoff [http://<host>:9090/federate?'match[]={job=~"netdata-scrape"}]

### Steps to reproduce

1.
2.
3.
...

### Installation method

manual setup of official DEB/RPM packages

### System info

```shell
Linux ems01 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Mon Jan 17 07:06:06 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

on k8s
```

### Netdata build info

```shell
[opwv@ems01 /]$ netdata -W buildinfo
Version: netdata v1.34.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-bundled-libJudy' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Install type: binpkg-rpm
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by ilyam8** [comment]
Hi, @AidanMcP. I am not sure we can help you with this issue. I think it's better to ask on resources related to Prometheus.

**Comment by ilyam8** [comment]
Not really a forum, we use GitHub issues for Netdata bugs/feature requests. We use [Discord, and GH discussions](https://github.com/netdata/netdata#tada-community) for questions. And I think it is not a Netdata niche question, I believe you will get an answer if you ask people from the Prometheus community.

**Comment by AidanMcP** [comment]
In the unlikely event anyone stumbles into this via a search, I'll add a root-cause - it had nothing to do with Netdata! 

It seems the issue is the relative values between 2 Prometheus fields/config options
 - scrape_interval : How frequently to scrape targets
 - query.lookback-delta : Used in calculation of ‘staleness’

So it transpires that a rather innocuous changing of scrape_interval (from 1s to 5s) can break the availability for metrics  Prometheus Federate API, without an accompanying change (increase) to query.lookback-delta
