### ISSUE TITLE
Heatmap overview for high device counts

### ISSUE THREAD

**Issue by drMspamy** [netdata/netdata#1682]
Hi,

I have been playing around with netdata and it looks very promising.

One thing I think this could need is an improved support for systems with many CPU cores. Think of what is possible with todays 4 socket servers with each having e.g.: an Intel E7-8890v4 + Hyperthreading in each socket or systems with very many (SAN attached) diskdrives/LUNs. The individual stats look fine for me now but I'd like to suggest an overview in form of a heatmap in addition for this particular usecase.

Aim is to see in one simple view that e.g. 10 of 100 devices (disk/cpu) are regularly saturated by them being highlighted. The hot devices should be clickable and link to the deteil view of the device, that you already have.

**Comment by ktsaou** [comment]
nice idea!

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
