### ISSUE TITLE
[Feat]: go.d collector for vcenter to include names of host again

### ISSUE THREAD

**Issue by nikobearrr** [netdata/netdata#16840]
### Problem

When I use netdata 1.44.1 with vsphere it only shows the VM ID in the charts. Thus I do not know which VM that is.

### Description

Using previous version, the go.d vsphere plugin was returning custom configuration. It seems to have changed here: https://github.com/netdata/go.d.plugin/commit/c994cd5bfc1f0fa98f5c97e9b0690880e382ee4f

Before I could get metrics like `vm_144_name_netdata01_overall_status` which now is `vm_144_overall_status`. In order to check the VM I am looking for I need to log into vCenter appliance to find the ID of the VM then go back to netdata and find it there.

The above commit seems to change things only for good for the UI v2. If you:
1) use v1 UI
2) use v2 UI
3) export metrics

they do not contain names. Actually even when looking at the UI v2 under the vSphere plugin, when I select the dropdown of `vms` or `Instances` popup I do not see names - only ID. That seems counter-intuitive to me as I do not know which VM I am looking for.

I assume one of the reason to not include the name in the metric is that a VM can change its name and it can create multiple charts. I cannot say for other people's use-case if that is an issue or not, but for my own case that is perfectly fine.

### Importance

must have

### Value proposition

1. Be able to see which VM the chart is for

**Comment by ilyam8** [comment]
Hi, @nikobearrr. 

> Thus I do not know which VM that is

We added labels to [hosts](https://learn.netdata.cloud/docs/data-collection/containers-and-vms/vmware-vcenter-server#per-host) and [VMs](https://learn.netdata.cloud/docs/data-collection/containers-and-vms/vmware-vcenter-server#per-virtual-machine) metrics.

>  I do not know which VM I am looking for.

Use labels (Group By). Later I plan to add a function that will provide a similar view to Top->Containers-vms for vsphere hosts and vms.

> export metrics

If you use Prometheus exporter set `send automatic labels` to `yes.
