### ISSUE TITLE
[Bug]: FreeBSD Jail is categorized as Bare Metal

### ISSUE THREAD

**Issue by insolentgeek** [netdata/netdata#16852]
### Bug description

A FreeBSD Jail is being displayed as bare metal, it should be a container.

### Expected behavior

When sysctl security.jail.jailed is 1, the system is a container; if the value is 0, the system is bare metal.

### Steps to reproduce

1. create and start a FreeBSD jail
2. install netdata and connect it to a cloud room
3. observe the system type in the nodes list as bare metal

### Additional context

While I noticed the issue with a FreeBSD jail running 14.0, the issue is also present on a 13.1 jail.

**Comment by ilyam8** [comment]
@insolentgeek is there are any `JAIL_*` env variables set inside jails?

**Comment by Ferroin** [comment]
More concretely, is there a way for a given process to reliably detect that it is running in a jail?

**Comment by insolentgeek** [comment]
Unfortunately, my life is too busy at the moment to tinker with the script and submit a PR; perhaps in a month or two I can, if it's not resolved by then.

As stated, the security.jail.jailed sysctl is how you detect the jailed state.
>      The read-only entry security.jail.jailed can be used to determine if a
>     process is running inside a jail (value is one) or not (value is zero).
https://www.freebsd.org/cgi/man.cgi?jail(8)
