### ISSUE TITLE
[Feat]: Custom HTML dashboard v2

### ISSUE THREAD

**Issue by lyc8503** [netdata/netdata#16918]
### Description

Hi. I've recently been trying to define my own Dashboard in Netdata, and the problem I'm having is that I can't aggregate the information in the same table (as mentioned in #2359). However the issue seems to have eventually been closed without being resolved.

The latest way to customize the Netdata Dashboard now seems to be to use the Netdata Cloud's services, and in the new Netdata Agent UI I can't seem to customize the Dashboard without logging in (and even after logging in the custom dashboards seem to have limited functionality), and in the end I've only found this in the v1 release: https://learn.netdata.cloud/docs/miscellaneous/build-a-custom-dashboard-html-page

Is it possible to update dashboard.js to use the newer v2 API so that I can use the new data sources in the v2 version? (e.g. `Maximum Memory Utilization (within limit) per cgroup`)

![image](https://github.com/netdata/netdata/assets/36782264/66da1ef5-9b24-495d-a858-6068ece48b61)

It would be great if you could also add the data aggregation feature mentioned above!

### Importance

really want

### Value proposition

More powerful customizable dashboards, no need to export data to use third-party dashboards or write your own javascripts

1. Ease of use and ease of coding
2. Save resources to avoid additional overhead
3. Meet the needs of more advanced users

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks!

**Comment by ilyam8** [comment]
Yes. I think there are no plans to implement this. At least for now. To create a custom dashboard use the "Dashboards" tab.

**Comment by fzyzcjy** [comment]
@ilyam8 Thank you, but it seems the "Dashboard" tab is very limited...

**Comment by lyc8503** [comment]
> Yes. I think there are no plans to implement this. At least for now. To create a custom dashboard use the "Dashboards" tab.

Is it possible to customise dashboard without logging in?
