### ISSUE TITLE
[Feat]: add CE & UE counter for EDAC collector

### ISSUE THREAD

**Issue by k0ste** [netdata/netdata#16969]
### Problem

Current EDAC collector implementation (#15473 by @ktsaou) is designed for high error rate metrics (gauge)
Actually for servers, at least with DDR4 LRDIMM memory the high error rate is very unlikely

### Description

The [RAS](https://www.kernel.org/doc/html/latest/admin-guide/ras.html) Kernel provide dimm_ue_count & dimm_ce_count files for each DIMM module. This is counters, and only can be incremented
This counters are never decreased until kernel reboot

Netdata should provide this counters as total (since boot) errors
![Screenshot 2024-02-08 at 10 51 22](https://github.com/netdata/netdata/assets/7759548/846dcb35-132e-45b7-a44c-7750e68c8c99)
![Screenshot 2024-02-08 at 11 04 18](https://github.com/netdata/netdata/assets/7759548/72f54a69-17ec-4f71-939f-55642a5fd6f5)

### Importance

must have

### Value proposition

When memory errors occur there are different ways depending on the site. For example, if this is a "local" data center with shareware engineers, then it is quite possible that the memory will be replaced on the same day

If the site is remote, money comes into play. For example, some data centers have a minimum cost for the service (quant). For example, $100 minimum for a hour. Therefore, it is important to have a metric for the number of errors in order to accumulate knowledge about how much memory needs to be changed in how many servers. How many servers need to be maintained, how much downtime to plan, how many spare parts required

### Proposed implementation

The existence of a metric that is reset only by rebooting the server, for example `mem_edac_mc_dimm_errors_count`

**Comment by ilyam8** [comment]
> add CE & UE counter 

Changed existing to absolute in #16970. I think we don't need rates ever, right? Keep in mind that I had to rename metrics, see the PR description.

**Comment by k0ste** [comment]
> Changed existing to absolute in #16970. I think we don't need rates ever, right? Keep in mind that I had to rename metrics, see the PR description.

I don't think some real possibility to computer continue works with high memory error rate. Especially with uncorrectable ones. I mentioned the PR author especially for a case of description, if this implementation was reasonable
