### ISSUE TITLE
[Bug]: Dead links on "Data Collection" sub pages for alerts on the website

### ISSUE THREAD

**Issue by AlwinAntreich** [netdata/netdata#16961]
### Bug description

When you look at: https://learn.netdata.cloud/docs/data-collection/synthetic-checks/x.509-certificate
The links for alerts point directly to master: https://github.com/netdata/netdata/blob/master/health/health.d/x509check.conf
But probably should point to: https://github.com/netdata/netdata/blob/master/src/health/health.d/x509check.conf

### Expected behavior

working link ;)

### Steps to reproduce

N/A

### Installation method

other

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

**Comment by tkatsoulas** [comment]
Yes @AlwinAntreich this is correct. We are in the process of moving any Netdata Agents's code under /src. Pipelines like updating the learn website are updating async and need some manual work. 

Closing this issue because besides it's indeed a problem we anticipate resolving it asap.
