### ISSUE TITLE
[Bug]: Source build fails

### ISSUE THREAD

**Issue by Rush** [netdata/netdata#17007]
### Bug description

I checked out v1.44.3 and tried to do `docker build .` but the build fails.

### Expected behavior

Expected build to succeed.

### Steps to reproduce

1. Clone empty repo from the v1.44.3 branch
2. Run docker build . -t v1.44.3
12.40 libnetdata/buffer/buffer.h:10:10: fatal error: h2o/memory.h: No such file or directory
12.40    10 | #include "h2o/memory.h"
12.40       |          ^~~~~~~~~~~~~~
12.40 compilation terminated.

...

### Installation method

from source

### System info

```shell
/etc/lsb-release:LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64"
/etc/os-release:NAME="openSUSE Tumbleweed"
/etc/os-release:ID="opensuse-tumbleweed"
/etc/os-release:ID_LIKE="opensuse suse"
/etc/os-release:VERSION_ID="20240126"
/etc/os-release:PRETTY_NAME="openSUSE Tumbleweed"
/etc/os-release:ANSI_COLOR="0;32"
/etc/os-release:CPE_NAME="cpe:/o:opensuse:tumbleweed:20240126"
/etc/os-release:LOGO="distributor-logo-Tumbleweed"
```

### Netdata build info

```shell
It's not relevant.
```

**Comment by ilyam8** [comment]
@Rush can you please provide the exact command you did instead of "Clone empty; Run docker build"?

**Comment by ilyam8** [comment]
I think you didn't do

```
git submodule update --recursive --init
```

after checking out to v1.44.3
