### ISSUE TITLE
[Feat]: VM and container accounting via /proc/pid rather than cgroups

### ISSUE THREAD

**Issue by shodanshok** [netdata/netdata#17055]
### Problem

When using ZFS, cgroups do not correctly account for written data (and, possibly, prefetched read data). Give a look here:

![screenshot](https://github.com/netdata/netdata/assets/13137622/3cb71e28-4664-4eb3-a7cf-d9cb39f53536)

This could be fixed by using normal `/proc/pid` stats rather than cgroups for gathering these info.

### Description

Use classical `/proc/pid` stats for VM and container statistics.

### Importance

really want

### Value proposition

1. not depending of cgroups for accounting data is going to help with ZFS

**Comment by ilyam8** [comment]
Hey, @shodanshok. Do you have `DefaultIOAccounting=yes` in `/etc/systemd/system.conf`? This fixed the problem for me on my Proxmox servers with ZFS.

After enabling IO accounting:

```bash
sudo systemctl daemon-reexec
```

**Comment by ilyam8** [comment]
I think this request is wontfix because it will not work for qemu VMs.

**Comment by shodanshok** [comment]
> Hey, @shodanshok. Do you have `DefaultIOAccounting=yes` in `/etc/systemd/system.conf`? This fixed the problem for me on my Proxmox servers with ZFS.

@ilyam8 yes, I tried `DefaultIOAccounting=yes` (and `systemctl daemon-reexec` + `reboot`) but nothing changed on my Rocky Linux 9.4. Any idea?

Accounting via `/proc/[pid]` should work for qemu VMs: while IO is done a dedicated threads, the counters under `/proc/[pid]/io`seem to account for them.
