### ISSUE TITLE
[Feat]: Self hosting multiple servers?

### ISSUE THREAD

**Issue by Martimrv** [netdata/netdata#17065]
### Description

We have multiple servers at different locations, would the cloud in this instance be a service provided by netdata (with a cost) or can this be self-hosted? 

### Importance

really want

### Value proposition

1.We are gathering information about netdata to conclude if it's an advantage to use it inside our company.
2.
3.
...

**Comment by ilyam8** [comment]
Hi, @Martimrv. For questions, please, consider using [Discord, forum, or GH discussions](https://github.com/netdata/netdata#tada-community).
