### ISSUE TITLE
[Bug]: No x86_64 Static Builds found

### ISSUE THREAD

**Issue by MatthewABrantley** [netdata/netdata#17068]
### Bug description

I recently uninstalled the outdated Ubuntu Bionic netdata agent and used Ansible to run the kickstart script to install a fresh static build on ~200 servers to get them to the latest version. 

It worked on all of them but one, where it tells me that there are no x86_64 static build available. Something is going wrong, as I just successfully installed and downloaded ~200 x86_64 static builds. 

### Expected behavior

When using x86_64, it should download the correct binary/package. 

### Steps to reproduce

1. Run kickstart.sh
2. It fails

### Installation method

kickstart.sh

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.2 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.2 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

### Netdata build info

```shell
Netdata is currently uninstalled, N/A
```

### Additional info

**lscpu:**

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  2
Core(s) per socket:  6
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz

**Kickstart Output:**

```
./kickstart.sh --non-interactive --static-only --claim-token *censored*

 --- Using /tmp/netdata-kickstart-YzCh2c8vPa as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- No existing installations of netdata found, assuming this is a fresh install. --- 
[/tmp/netdata-kickstart-YzCh2c8vPa]# sh -c /usr/bin/curl https://github.com/netdata/netdata-nightlies/releases/latest -s -L -I -o /dev/null -w '%{url_effective}' | grep -Eo '[^/]+$' 
 OK 

 --- Attempting to install using static build... --- 
 WARNING  There is no static build available for x86_64 CPUs. This usually means we simply do not currently provide static builds for x86_64 CPUs.

The following non-fatal warnings or errors were encountered:

  - There is no static build available for x86_64 CPUs. This usually means we simply do not currently provide static builds for x86_64 CPUs.

 ABORTED  Could not install static build.

For community support, you can connect with us on:
  - GitHub: https://github.com/netdata/netdata/discussions
  - Discord: https://discord.gg/5ygS846fR6
  - Our community forums: https://community.netdata.cloud/
```

**Comment by tkatsoulas** [comment]
Hey yeap seems strange, 

Q1: Does this node has access to Github API? 
Q2: What's the result of the `uname -m`

**Comment by MatthewABrantley** [comment]
Actually I've discovered the clients network this node is in is experiencing serious DNS issues and that's where I imagine this script is failing as well. I'm closing this, as you cannot do anything about that.

**Comment by ilyam8** [comment]
>  There is no static build available for x86_64 CPUs. This usually means we simply do not currently provide static builds for x86_64 CPUs.


The message is very misleading. We should somehow distinguish between network errors and the absence of a static build. This is not the first time I have seen a user confused because of the message cc @netdata/agent-sre
