### ISSUE TITLE
[Feat]: Add notification on child node going stale

### ISSUE THREAD

**Issue by mkesper** [netdata/netdata#17070]
### Problem

Two nodes configured, one as child and one as parent. Configured alerts and notifications are working properly. No alert is triggered when the child cannot reach the parent, though.

### Description

An alert should be triggered by default when a child agent vanishes as then this node will go completely unmonitored! Overriding to ignore ephemeral nodes should be added.

### Importance

must have

### Value proposition

1. Without this feature, relying on netdata agent for node monitoring is misleading (No data sent -> no alert)
2. Not having this feature would require adding further external checks, complicating the setup.

### Proposed implementation

Check every minute (by default) whether child nodes are live. If not, go into alarm.

**Comment by wmertens** [comment]
I believe this could be addressed by #17539

**Comment by ilyam8** [comment]
Closing in favor of #18436
