### ISSUE TITLE
When is the android app coming out?

### ISSUE THREAD

**Issue by Whisper22X** [netdata/netdata#17105]
### Description

We've been working on a surveillance platform

### Importance

nice to have

### Value proposition

1.
2.
3.
...

**Comment by tkatsoulas** [comment]
Hello the app is available on https://play.google.com/store/apps/details?id=cloud.netdata.android&hl=en_US&pli=1 Google play store. Keep in mind it's only for alerts. If you want  Charts, I am not sure that we have this in the roadmap

cc @netdata/product

**Comment by tkatsoulas** [comment]
Closing this issue, feel free to start a [Github discussion](https://github.com/netdata/netdata/discussions) if you need a specific feature in the app
