### ISSUE TITLE
[Feat]: one of the most important alerts of one system are "silenced" by default!!!!

### ISSUE THREAD

**Issue by nicknaychov** [netdata/netdata#17178]
### Problem

one of the most important alerts of one system are "silenced" by default!!!!
talking for /health.d/cpu.conf and health.d/load.conf

### Description

Our system was almost not functional for about 5 hours and no single email alert from Netdata. Thus we were not aware untill customers started to complain. When I check further it turns out those alarms were silenced by default!!!
How come one of the most important alarms of one system are silenced by default????
And now you want money for this product. People would expect then such a serious flows to be fixed. 

### Importance

nice to have

### Value proposition

So they can use your system to get alerts when something is wrong. Otherwise pretty graphs are nothing.

**Comment by Forza-tng** [comment]
I'd be very annoyed at having alarms on CPU load etc. It would spam a lot. Anyway, maybe such metrics are highly dependent on the specific servers normal workload. Hopefully the ML/AI parts will help detect unusual activity after a while.

**Comment by ilyam8** [comment]
Hey, guys. I agree about the CPU % alarm. I think we will _unsilence_ it. The system load one will remain silent - that is a very questionable metric, and shouldn't be used at all on systems with [PSI](https://docs.kernel.org/accounting/psi.html)

**Comment by ilyam8** [comment]
@Forza-tng 

> I'd be very annoyed at having alarms on CPU load etc.

Did you mean system load average (health.d/load.conf)?
