### ISSUE TITLE
[Feat]: disable query log in go.d.plugin mysql collector

### ISSUE THREAD

**Issue by Forza-tng** [netdata/netdata#17179]
### Problem

I have query log and slow query logs activated for my mariadb instances. Since netdata is querying the same thing over and over, it would be good to disable query logging for the netdata session. 

### Description

Add a configuration option to disable query logging.

https://github.com/netdata/go.d.plugin/blob/master/modules/mysql/

### Importance

nice to have

### Value proposition

To me it reduces log traffic, especially on databases with infrequent queries. 

### Proposed implementation

* Option 1:  a toggle in go.d/mysql.conf
* Option 2: allow custom sql clauses to be executed when the connection first is made. This would allow users to customise for their specific database version. 

In MariaDB you'd use:
```sql
SET SESSION SQL_LOG_OFF=1;
SET SESSION slow_query_log=0; 
```
Relevant documentation:
* https://mariadb.com/kb/en/general-query-log/#disabling-the-general-query-log-for-a-session
* https://mariadb.com/kb/en/slow-query-log-overview/#disabling-the-slow-query-log-for-a-session

**Comment by ilyam8** [comment]
@Forza-tng, hey. I think that's a good request, thank you. We'll add it. But keep in mind that `SQL_LOG_OFF` requires [super](https://mariadb.com/kb/en/grant/#super).

**Comment by ilyam8** [comment]
@Forza-tng implemented in #17219

- I decided not to add it as an option until someone requested it. The plugin will always try to disable session query and slow query logging.
- Disabling session query logging (`sql_log_off`) requires SUPER privilege.

And I think MySQL and MariaDB syntax have the same.
