### ISSUE TITLE
[Bug]: Agent Registration via Key Fails

### ISSUE THREAD

**Issue by AlphaOmega2020** [netdata/netdata#17200]
### Bug description

Trying to register an agent using the random key generator process fails with `unknown http error response`

https://media.discordapp.net/attachments/1219669063270138037/1219669063652085881/image.png?ex=660c2455&is=65f9af55&hm=6aa4e6bb71d7e7c321b263c48035f68f519cf04c3aced408a8d847744e96fbf6&=&format=webp&quality=lossless&width=1184&height=563

Agent is running fine locally but want data present in cloud dashboards

### Expected behavior

agent reregistration successful. 

### Steps to reproduce

1. install netdata agent
2. browse to local web interface on port 19999
3. click "connect tto netdata"
4. choose space
5. run "sudo cat /opt/netdata/var/lib/netdata/netdata_random_session_id"
6. copy key into webform
7. click claim agent
8. it pauses for a fee seconds then gives the "unknown http error response" response

### Installation method

other

### System info

```shell
Linux Nexus-Media 4.2.8 #1 SMP Wed Jan 31 03:41:07 CST 2024 x86_64 GNU/Linux
```

### Netdata build info

```shell
~# netdata -W buildinfo
-sh: netdata: command not found

~#  $(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
-sh: qpkg/NetData/bin/srv/netdata: No such file or directory
```

**Comment by ilyam8** [comment]
Hi, @AlphaOmega2020. You need to provide more info:

- How did you install Netdata?
- We need buildinfo. It is `/opt/netdata/usr/sbin/netdata -W buildinfo`. The path may be different, you can find it using `ps faxu | grep [n]etdata`.

**Comment by AlphaOmega2020** [comment]
> * /opt/netdata/usr/sbin/netdata -W buildinfo

`    Netdata Version ____________________________________________ : v1.44.2
    Installation Type __________________________________________ : manual-static
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ :  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-math' '--with-user=netdata' '--disable-exporting-mongodb' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' '--enable-lto' 'CFLAGS=-ffunction-sections -fdata-sections -static -O2 -funroll-loops -I/openssl-static/include -I/libnetfilter-acct-static/include/libnetfilter_acct -I/curl-local/include/curl -I/usr/include/libmnl -pipe' 'LDFLAGS=-Wl,--gc-sections -static -L/openssl-static/lib64 -L/libnetfilter-acct-static/lib -lnetfilter_acct -L/usr/lib -lmnl -L/usr/lib -lzstd -L/curl-local/lib' 'PKG_CONFIG=pkg-config --static' 'PKG_CONFIG_PATH=/openssl-static/lib64/pkgconfig:/libnetfilter-acct-static/lib/pkgconfig:/usr/lib/pkgconfig:/curl-local/lib/pkgconfig'
Default Directories:
    User Configurations ________________________________________ : /opt/netdata/etc/netdata
    Stock Configurations _______________________________________ : /opt/netdata/usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /opt/netdata/var/cache/netdata
    Permanent Databases ________________________________________ : /opt/netdata/var/lib/netdata
    Plugins ____________________________________________________ : /opt/netdata/usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /opt/netdata/usr/share/netdata/web
    Log Files __________________________________________________ : /opt/netdata/var/log/netdata
    Lock Files _________________________________________________ : /opt/netdata/var/lib/netdata/lock
    Home _______________________________________________________ : /opt/netdata/var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 4.2.8
    Operating System ___________________________________________ : unknown
    Operating System ID ________________________________________ : unknown
    Operating System ID Like ___________________________________ : unknown
    Operating System Version ___________________________________ : unknown
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : unknown
Hardware:
    CPU Cores __________________________________________________ : 4
    CPU Frequency ______________________________________________ : 3300000000
    RAM Bytes __________________________________________________ : 16681238528
    Disk Capacity ______________________________________________ : 68374644399616
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : unknown
    Virtualization Detection ___________________________________ : none
Container:
    Container __________________________________________________ : unknown
    Container Detection ________________________________________ : none
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    map ________________________________________________________ : YES
    save _______________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Judy (high-performance dynamic arrays and hashtables) ______ : YES (bundled)
    dlib (robust machine learning toolkit) _____________________ : YES (bundled)
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libm (mathematical functions) ______________________________ : YES
    jemalloc ___________________________________________________ : NO
    TCMalloc ___________________________________________________ : NO
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : NO
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : YES
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : NO
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
`

**Comment by ktsaou** [comment]
@AlphaOmega2020 is it possible for you to use the latest version of Netdata? There are have been some changes in the claiming process and the latest Netdata may work out of the box.

What to do if it still does not work?

You have 2 options:

1. Use the claiming script directly (from the console) to see the full error report. The Linux system you use seems pretty old and there may be issues all over the place. I can provide instructions on how to do this.

2. Use any other Netdata as a Parent. So, edit `stream.conf` (in both servers) and push the metrics of this Netdata to the other Netdata, that is already claimed to Netdata Cloud. This way, this Netdata will appear in the cloud dashboards.

Which method you prefer?

**Comment by daNutzzzzz** [comment]
Hi,

Thanks for the response, im happy to try both options, starting with number one first.

**Comment by AlphaOmega2020** [comment]
FYI im now on v1.45 and same issue

**Comment by ilyam8** [comment]
> it pauses for a fee seconds then gives the "unknown http error response" response

Netdata logs a message when failing to claim, did you happen to check the logs?

Try executing the claiming script directly:

```bash
cd /opt/netdata/usr/sbin/
# become netdata user
sudo su -s /bin/bash netdata
# execute the script, add your token
VERBOSE=1 ./netdata-claim.sh -token=TOKEN -url=https://app.netdata.cloud
```

**Comment by AlphaOmega2020** [comment]
> > it pauses for a fee seconds then gives the "unknown http error response" response
> 
> Netdata logs a message when failing to claim, did you happen to check the logs?
> 
> Try executing the claiming script directly:
> 
> ```shell
> cd /opt/netdata/usr/sbin/
> # become netdata user
> sudo su -s /bin/bash netdata
> # execute the script, add your token
> VERBOSE=1 ./netdata-claim.sh -token=TOKEN -url=https://app.netdata.cloud
> ```

Apologies for the late response. 

Its failing with the same response in GUI

`./netdata-claim.sh -token=HbpE5A_guQk8B6YFzx9fDYe6QTR5UZYjet9OmdWjKh_69mAy3Y3Ogg2FvAT_W_mE8yuIMRnibvD52zM3idR_Qju2oD_TjHp0D-NBYIuYf1YKVdS4BQ_aGbar661ch-lH-SPqvdM -url=https://app.netdata.cloud
Token: ****************
Base URL: https://app.netdata.cloud
Id: 55c3fa72-e5f8-11ee-97d5-7adf7f5035f3
Rooms:
Hostname: Nexus-Media
Proxy:
Netdata user:
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 1 failed. Retry in 1s.
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 2 failed. Retry in 2s.
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 3 failed. Retry in 3s.
Failed to claim node with the following error message:"Unknown HTTP error message"
`

I ran some basic connectivity tests:
```
[/] # ping app.netdata.cloud
PING app.netdata.cloud (44.196.50.41): 56 data bytes
```
```
[/] # curl app.netdata.cloud:443
curl: (52) Empty reply from server
```

I get the same connectivity results on servers that do connect.

**Comment by hugovalente-pm** [comment]
@AlphaOmega2020 this issue seems similar (or maybe the same) as reported on this thread, could you check the last 2 posts and see if it helps?
https://community.netdata.cloud/t/unable-to-claim-node-error-is-failed-to-connect-to-https-app-netdata-cloud-return-code-60/3989/6

**Comment by ilyam8** [comment]
I think @hugovalente-pm is correct. Unfortunately, there is nothing we can do if the certificates on your system have expired. Check the link to find out how to fix the problem.

**Comment by zhwllq** [comment]
I had the same problem. How was it solved？
