### ISSUE TITLE
[Bug]: CGROUP: cannot read directory

### ISSUE THREAD

**Issue by setupgr** [netdata/netdata#17223]
### Bug description

CGROUP: cannot read directory '/sys/fs/cgroup/memory'
CGROUP: cannot read directory '/sys/fs/cgroup/blkio'
CGROUP: cannot read directory '/sys/fs/cgroup/cpu,cpuacct'

### Expected behavior

No such errors in logs should occur

### Steps to reproduce

1. View logs

### Desktop

Browser Version [e.g. 22]

**Comment by ilyam8** [comment]
Please reopen using [bug report template](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2Cneeds+triage&projects=&template=BUG_REPORT.yml&title=%5BBug%5D%3A+).
