### ISSUE TITLE
[Feat]: Ubuntu 24.04 Support

### ISSUE THREAD

**Issue by dgibbs64** [netdata/netdata#17563]
### Description

Ubuntu 24.04 is not currently available in the netdata repo http://repo.netdata.cloud/repos/stable/ubuntu/noble/. Ubuntu 24.04 was released April 25, 2024. Please can a deb package be built add added to the repo

### Importance

blocker

### Value proposition

A new ubuntu LTS release was just released but the deb package is not currently available.

**Comment by Ferroin** [comment]
We’re already publishing packages for Ubuntu 24.04 (and Fedora 40) in our nightly builds, they just haven’t quite made it to stable releases yet. We currently have plans for a patch release some time next week that will include packages for both of these platforms, as well as a few other fixes.
