### ISSUE TITLE
[Bug]: build-static.sh x86_64 fails

### ISSUE THREAD

**Issue by dave818** [netdata/netdata#17586]
### Bug description

I'm attempting to build a static binary following these instructions:  https://learn.netdata.cloud/docs/netdata-agent/installation/linux/static-binary-linux-packages

The build consistently fails, I've tried with docker and podman on RHEL 7 and 8, and Ubuntu 22.  It failed at the same point in every case.  I'm using the latest commit, which at this time is: 5d91178f784053d883ea20f0248fec10f23d5e33

It appears to be failing due to: `Cannot find source file: src/web/server/h2o/libh2o/deps/cloexec/cloexec.c`

Here is what's run right leading up to the failure:

> --- running jobs/70-netdata-git.install.sh ---
> 
> --- Updating tags in git to ensure a consistent version number ---
> [/usr/src/netdata]# git fetch -t
>  OK  ''
> 
> 
> ::group::Configuring Netdata.
> Netdata user and group set to: netdata/netdata
> [/usr/src/netdata]# /usr/bin/cmake -S ./ -B ./build/ -G Ninja -DCMAKE_INSTALL_PREFIX=/opt/netdata -DNETDATA_USER=netdata -DENABLE_PLUGIN_GO=On -DENABLE_BUNDLED_PROTOBUF=Off -DENABLE_PLUGIN_SYSTEMD_JOURNAL=Off -DENABLE_PLUGIN_CUPS=Off -DENABLE_PLUGIN_DEBUGFS=On -DENABLE_PLUGIN_PERF=On -DENABLE_PLUGIN_SLABINFO=On -DENABLE_PLUGIN_CGROUP_NETWORK=On -DENABLE_PLUGIN_LOCAL_LISTENERS=On -DENABLE_PLUGIN_NETWORK_VIEWER=On -DENABLE_PLUGIN_EBPF=On -DENABLE_PLUGIN_LOGS_MANAGEMENT=Off -DENABLE_LOGS_MANAGEMENT_TESTS=Off -DENABLE_ACLK=On -DENABLE_CLOUD=On -DENABLE_BUNDLED_JSONC=Off -DENABLE_DBENGINE=On -DENABLE_H2O=On -DENABLE_ML=On -DENABLE_PLUGIN_APPS=On -DENABLE_EXPORTER_PROMETHEUS_REMOTE_WRITE=On -DENABLE_EXPORTER_MONGODB=Off -DENABLE_PLUGIN_FREEIPMI=Off -DENABLE_PLUGIN_NFACCT=On -DENABLE_PLUGIN_XENSTAT=Off -DBUILD_SHARED_LIBS=Off
> 

And here's the output immediately before the error:

> -- Checking for module 'libpcre2-8'
> --   Found libpcre2-8, version 10.42
> -- Configuring done (24.6s)
> CMake Error at CMakeLists.txt:1431 (add_library):
>   Cannot find source file:
> 
>     src/web/server/h2o/libh2o/deps/cloexec/cloexec.c
> 
> 
> CMake Error at CMakeLists.txt:2140 (add_executable):
>   Cannot find source file:
> 
>     src/ml/dlib/dlib/all/source.cpp
> 
> 
> CMake Error at CMakeLists.txt:1431 (add_library):
>   No SOURCES given to target: h2o
> 
> 
> CMake Error at CMakeLists.txt:2140 (add_executable):
>   No SOURCES given to target: netdata
> 
> 
> CMake Generate step failed.  Build files cannot be regenerated correctly.
>  FAILED  ''
> 
>  ABORTED  Failed to configure Netdata sources.
> 
> 
>   ^
>   |.-.   .-.   .-.   .-.   .-.   .  netdata  .-.   .-.   .-.   .-.   .-.   .-
>   |   '-'   '-'   '-'   '-'   '-'               '-'   '-'   '-'   '-'   '-'
>   +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->
> 
>  ABORTED  Netdata failed to build for an unknown reason.
> 
> Build failed.
> 

### Expected behavior

A file named netdata-vX.X.X-gGITHASH-x86_64-DATE-TIME.run should be created in the current directory.

### Steps to reproduce

1. Have docker or podman installed on a Linux server
2. git clone https://github.com/netdata/netdata.git
3. cd netdata
4. ./packaging/makeself/build-static.sh x86_64

Observe that it fails.

### Installation method

other

### System info

```shell
/etc/os-release:NAME="Red Hat Enterprise Linux"
/etc/os-release:VERSION="8.9 (Ootpa)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VERSION_ID="8.9"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux 8.9 (Ootpa)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=8.9
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
/etc/redhat-release:Red Hat Enterprise Linux release 8.9 (Ootpa)
/etc/system-release:Red Hat Enterprise Linux release 8.9 (Ootpa)
```

### Netdata build info

```shell
N/A - this Issue is for building a static netdata binary
```

### Additional info

I'm looking to build a static binary package that could be used to install netdata on RHEL 6.

**Comment by ilyam8** [comment]
> git clone [netdata/netdata.git](https://github.com/netdata/netdata.git)

@dave818 I think you didn't do a recursive clone

```
git clone --recursive https://github.com/netdata/netdata
```

**Comment by dave818** [comment]
@ilyam8 that was exactly it, thank you!
