### ISSUE TITLE
[Bug]: Table chart renders empty for custom dashboard

### ISSUE THREAD

**Issue by ohlr** [netdata/netdata#17700]
### Bug description

Table chart renders empty for custom dashboard

When adding in to the dashboard it can no longer be deleted because only drag + drop button renders

### Expected behavior

Render table chart + always allow to delete even if rendering is broken

### Steps to reproduce

Reproduce:
1. Add table chart to dashboard
![image](https://github.com/netdata/netdata/assets/26937880/f98c6d84-4858-4502-a443-2b1f145724c8)

2. Notice nothing is displayed anymore but click add to dashboard anyway
![image](https://github.com/netdata/netdata/assets/26937880/0697f13e-9713-4a14-8312-be8e564a5499)

3. Now you have a empty card that can be resized but not moved or deleted
![image](https://github.com/netdata/netdata/assets/26937880/3c1f6abd-5979-497c-9520-1e2fb296abb4)

### Installation method

docker

### System info

```shell
docker compose - netdata/netdata:stable - V1.45.3
```

### Netdata build info

```shell
docker compose - netdata/netdata:stable - V1.45.3
```

**Comment by ilyam8** [comment]
Table chart is a new type of chart that is in development. It shouldn't have been added to the menu for now. We will remove it.

**Comment by ilyam8** [comment]
I don't know how to remove them. I think recreating the dashboard is the only way to go.
