### ISSUE TITLE
[Feat]: Ability to better filter systemd units (transient podman healthchecks)

### ISSUE THREAD

**Issue by adrienkohlbecker** [netdata/netdata#17723]
### Problem

Hi,

I've been using the systemd integration to monitor the health of all units running on my host, by setting:
```yaml
    include:
      - '*'
```

It turns out, however, that every `podman` container's healthcheck is a transient systemd unit, randomly named after the ephemeral container that executed the command. When the healthcheck fails, the associated systemd unit (marked as `transient`) still exists in a failed state, and netdata raises an alert, which is not cleared until the host reboots. 

In case of long term problems, these healthcheck failures can happen a couple times per minute, which of course makes netdata send a lot of notifications, and pollutes the web UI.

```
❯ systemctl status 1813ea95707b258d21bcb5ac28812e2c3854171c698233f8070af21a569afb09.service
× 1813ea95707b258d21bcb5ac28812e2c3854171c698233f8070af21a569afb09.service - /usr/bin/podman healthcheck run 1813ea95707b258d21bcb5ac28812e2c3854171c698233f8070af21a569afb09
     Loaded: loaded (/run/systemd/transient/1813ea95707b258d21bcb5ac28812e2c3854171c698233f8070af21a569afb09.service; transient)
  Transient: yes
     Active: failed (Result: exit-code) since Tue 2024-05-21 14:10:55 UTC; 15min ago
   Main PID: 2303080 (code=exited, status=125)
        CPU: 38ms

May 21 14:10:55 lab systemd[1]: Started /usr/bin/podman healthcheck run 1813ea95707b258d21bcb5ac28812e2c3854171c698233f8070af21a569afb09.
May 21 14:10:55 lab podman[2303080]: Error: container 1813ea95707b258d21bcb5ac28812e2c3854171c698233f8070af21a569afb09 is not running
May 21 14:10:55 lab systemd[1]: 1813ea95707b258d21bcb5ac28812e2c3854171c698233f8070af21a569afb09.service: Main process exited, code=exited, status=125/n/a
May 21 14:10:55 lab systemd[1]: 1813ea95707b258d21bcb5ac28812e2c3854171c698233f8070af21a569afb09.service: Failed with result 'exit-code'.
```

Here is an example from my host's dashboard:

<img width="1703" alt="Screenshot 2024-05-21 at 16 43 43" src="https://github.com/netdata/netdata/assets/70469/9c633b39-5415-4b49-981c-37d55d1c8959">

### Description

It would be great if netdata was able to filter out these units. As you can see from the name randomization done by podman, it is not possible to use the current `include` filter to do that.

### Importance

must have

### Value proposition

Until this feature is implemented, `podman` users wishing to monitor `systemd` units on their hosts are unable to do so. 

### Proposed implementation

Add a boolean setting to ignore `transient` systemd units.

**Comment by ilyam8** [comment]
Hi.

> As you can see from the name randomization done by podman, it is not possible to use the current include filter to do that.

Understood. We can't change the syntax of `include` because it is passed directly to systemd for server-side filtering. It is glob pattern, from [man systemctl](https://manpages.debian.org/stretch/systemd/systemctl.1.en.html#Parameter_Syntax)

> Glob patterns use [fnmatch(3)](https://manpages.debian.org/stretch/manpages-dev/fnmatch.3.en.html), so normal shell-style globbing rules are used, and "*", "?", "[]" may be used. See [glob(7)](https://manpages.debian.org/stretch/manpages/glob.7.en.html) for more details.

We can add a regular expression filter to do additional filtering on the client side (go.d.plugin). Is that what you want, @adrienkohlbecker?

**Comment by ilyam8** [comment]
What I didn't mention is that after the query we don't know if the unit is transient or not, so we can't just add an option to ignore transient units.

**Comment by ilyam8** [comment]
> What I didn't mention is that after the query we don't know if the unit is transient or not, so we can't just add an option to ignore transient units.

I found a way to do this, but it requires a per-device query (getting the Transient property), which I think may increase CPU usage on start/restart. The result will be cached until the next Netdata restart.

The default "skip_transient" is "no", you will need to enable it, @adrienkohlbecker.

**Comment by adrienkohlbecker** [comment]
Thank you for the quick turnaround! Seems like a great solution, happy to trade some cycles at start to cache this property.
