### ISSUE TITLE
[Feat]: Netdata needs a new and improved SNMP collector

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#17727]
### Problem

The current SNMP collector requires the MIB and OID discovery and configuration to be done manually. This is not viable or feasible in large production environments. 

### Description

The suggestion is to use (or port) what the [SNMP exporter](https://github.com/prometheus/snmp_exporter) does so that the collector will be easier to setup for users and will save a lot of time.

### Importance

blocker

### Value proposition

1. This is a blocker for many customers/users who are trying to add SNMP monitoring to their Netdata stack.

**Comment by Raptus1** [comment]
+1 for more auto discovery. would be amazing to be able to have some device discovery that could be used together with a type of filter.

**Comment by Raptus1** [comment]
@shyamvalsan Does the merged PR deal properly with your request?

I have not tested the merged code/functionality. PR is not listed in any change requests but got merged into main over a month ago.

**Comment by ilyam8** [comment]
Hey, @Raptus1, what do you mean by "PR is not listed in any change requests"? 

>  have not tested the merged code/functionality

Added functionality is described in the PR description. There is a [short video (Discord)](https://discord.com/channels/847502280503590932/847502280503590935/1256168041784279060).

**Comment by Raptus1** [comment]
Sorry, I was thinking about release notes, not change requests.

I cannot check the video as I do not have discord account.

Really looking forward to test this when I have the time though. The network team I work with ended up jumping onto LibreNMS because Netdata snmp monitoring became way to time-consuming. At first glance, this is promising though!

Thanks for the work you have done!

**Comment by ilyam8** [comment]
<details>
<summary>Video</summary>

https://github.com/user-attachments/assets/c27284fc-a2e0-4623-84e7-0f715185df00

</details>

**Comment by Raptus1** [comment]
This looks amazing! Can't wait to try it!
