### ISSUE TITLE
[Feat]: Automatically update vnodes.conf when user defines a vnode in collector conf 

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#17741]
### Problem

The user having to update two files (collector conf file + vnodes.conf) and having to run `uuidgen `every time they want to add a vnode is unnecessarily cumbersome. 

### Description

Configuring vnodes should be a smooth and simple process. 

Here's how it should work ideally:
- User adds `vnode` parameter to the collector `.conf` file in dyncfg and submits 
- Internally, Netdata should add the vnode entry and guid (auto generated) to vnodes.conf before restarting the agent

### Importance

really want

### Value proposition

1. Make netdata more user friendly

**Comment by shyamvalsan** [comment]
@Ferroin I agree, that makes a lot of sense.

**Comment by ilyam8** [comment]
This is not needed anymore. 

- The primary and only use of Vnodes was `go.d/windows`, and it will be replaced by the native Windows agent support.
- `go.d/snmp` can automatically create Vnodes (`create_vnode: yes/no` config option).
