### ISSUE TITLE
[Feat]: support json format weblog

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#17747]
### Problem

Now JSON is a very common format to store log.
But weblog module supprts CSV (CLF) and LTSV, but don't support JSON.

### Description

Let's support JSON format log.

### Importance

must have

### Value proposition

1. Now JSON is a very common format to store log.

**Comment by ilyam8** [comment]
Hey, @Wing924. weblog [supports parsing JSON logs](https://github.com/netdata/netdata/tree/master/src/go/collectors/go.d.plugin/modules/weblog#parserlog_type).
