### ISSUE TITLE
Config option at dashboard: Version check against rolling or major version

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#1776]
Just an idea.

We could add a config option to the dashboard to switch to only check for major releases instead of new commits to master.

**Comment by simonnagl** [comment]
If we add this we must check the major release version over the version string.
This would also fix all issues of https://github.com/firehol/netdata/issues/614

**Comment by ktsaou** [comment]
I think the whole updating mechanism will be rewritten, when we will have our packages.
So, I am closing this.
