### ISSUE TITLE
[Feat]: Netdata to keep previous stable versions

### ISSUE THREAD

**Issue by yt** [netdata/netdata#17767]
### Problem

We are using Netdata to power a mission and safety critical system (automated public vehicles) where updates are relatively scarse, well tested and documented. The older stable packages getting deleted on public archives is a huge problem. 

### Description

This choice to delete old packages leads to users like us to implement a mirror server to mirror old releases and use our own custom package repositories. Huge hustle. 
This feature also helps us to replicate errors on new versions and compare them to easily switchable old versions.
At the kickstart script, if specified version is not found (which it mostly can't) it defaults to latest without input. This creates confusion and mistrust. `Selected release channel does not match this version and it will be changed automatically.`

### Importance

really want

### Value proposition

1. Enable consistent agent deployments for multiple servers
2. Enable easy version chage for troubleshooting
3. More trust by the community & enterprises

### Proposed implementation

- Edit packagecloud github action to not delete older "stable" versions.
- At the kickstart script, if specified version is not found, exit.

**Comment by ilyam8** [comment]
Hey, @yt. Have you considered using static builds? Static builds are located on GitHub and can be found among the assets of any release.

**Comment by yt** [comment]
Hi @ilyam8. 
Yes, for debug purposes,static builds are good. With the {version}.tar.gz file I download the static files and can create my own deb files with the docker package-builders. 
Still the problem persists which I have to maintain my own package repository. 
For our case, assume need to keep the devices on the field with netdata version v1.35.0 until the next big release. We have to have a mirror package repository where we either copy the original deb file from the official ubuntu archives, or create a new artifact from the static files and put it to our mirror package repository.
This is totally feasible and we are doing it, but it is inconvenient as often we want to switch between versions as easy as `apt install netdata=1.44.5`.
It would definately add value as it will make the system work just like any other packages they have to maintain in their application.
Do you guys have a reason why you only keep last 5 minor versions on distro repositories?

**Comment by Ferroin** [comment]
>  Do you guys have a reason why you only keep last 5 minor versions on distro repositories?

Storage costs mostly, and to a lesser extent scalability issues in how we need to handle repository metadata generation.

**Comment by ilyam8** [comment]
As far as I understand, this is wontfix. We will not keep old versions forever.


> until the next big release

What is a big release? There are a huge number of changes v1.35.0 -> v1.45.5.
