### ISSUE TITLE
[Feat]: Current cloud-only features to also be available for child-parent environment with locally implemented security.

### ISSUE THREAD

**Issue by Raptus1** [netdata/netdata#17833]
### Problem

Using Netdata with streaming on a environment that have traefik to secure access to parent should allow for the ability to view features like top (functions?) and logs, but is instead arbitrarily limited and not possible to activate at own risk.

### Description

These are features that are available on the agent side regardless, so would be very nice to allow these features to also be enabled in environments that have additional security features in place locally instead of needing to go to cloud.

Since starting working with this (amazing) product all the new and sweet features that would make this product perfect are artificially limited in the false name of security without allowing custom implementation for those that can set up local security of the services.

### Importance

blocker

### Value proposition

Create a variable in the helm chart or similar that can be used to enable the features mentioned above and to acknowledge that the risk of data exposure bu not using netdata cloud is accepted.

### Proposed implementation

streaming: unfiltered 

..or something similar could be a variable that would allow streaminf of the types of metrics and charts that are currently only for Netdata Cloud.

**Comment by ilyam8** [comment]
Hi, @Raptus1. We don’t man to do this in the nearest feature.

**Comment by Raptus1** [comment]
No shocker there, as it would obviously mess up with your business incentives.

It is just a shame that you went this path recently. You started out so promising..
