### ISSUE TITLE
[Feat]: Adds GreptimeDB to the exporting external time-series databases list

### ISSUE THREAD

**Issue by killme2008** [netdata/netdata#17841]
### Problem

Hi, team

Netdata stands out as a remarkable project within the observability domain, all credit to the dedicated team and supportive community.

I am a creator of [GreptimeDB](https://github.com/GreptimeTeam/greptimedb), an open-source, cloud-native, distributed time-series database with PromQL/SQL support. It supports InfluxDB line protocol and Prometheus remote write, making it a potential external time-series database for netdata as well.

So, May I create a document pull request for it? Just like https://github.com/netdata/netdata/blob/master/src/exporting/prometheus/integrations/prometheus_remote_write.md 

Thank you.

### Description

Create a document for GreptimeDB as the external time-series database for netdata.

### Importance

nice to have

### Value proposition

1. An open-source, distributed, and cost-effective external time-series database for long-term data storage.
2. Enrich the Netdata project ecosystem.
3.
...

### Proposed implementation

I'd like to create the document.

**Comment by ilyam8** [comment]
Hey, @killme2008. Sure, go ahead. You will need to update https://github.com/netdata/netdata/blob/master/src/exporting/prometheus/metadata.yaml.

**Comment by killme2008** [comment]
> Hey, @killme2008. Sure, go ahead. You will only need to update one file - https://github.com/netdata/netdata/blob/master/src/exporting/prometheus/metadata.yaml.

Cool, thank you for your quick reply, I'll try it.
