### ISSUE TITLE
[Feat]: Improve documentation about recommended mount points for docker for zram

### ISSUE THREAD

**Issue by powerman** [netdata/netdata#17891]
### Problem

[Install Netdata with Docker / Recommended way](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#recommended-way) does not list all required mount points (and so is "Mounts" section just above it) for metrics enabled by default: zram. This result in losing a lot of time to debug this issue for new users.

### Description

I want zram metrics work out-of-box in a docker configured in recommended way.

### Importance

really want

### Value proposition

1. New "Netdata with Docker" users will have better first time experience.
2. These users won't lose a lot of time trying to make zram metrics work.

### Proposed implementation

Add extra mount point `/dev:/host/dev:ro` to make zram metrics work.
Details: https://github.com/netdata/netdata/issues/14758#issuecomment-1474854112

**Comment by ilyam8** [comment]
Hey, @powerman. Please open one issue with all your suggestions.
