### ISSUE TITLE
[Bug]: Install Netdata with Docker "With SSL/TLS enabled HTTP Proxy" is not compatible with "Recommended way"

### ISSUE THREAD

**Issue by powerman** [netdata/netdata#17893]
### Bug description

[Install Netdata with Docker / Recommended way](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#recommended-way) uses `network_mode: host`, but Caddy setup in [Install Netdata with Docker / With SSL/TLS enabled HTTP Proxy](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#with-ssltls-enabled-http-proxy) won't work this way (it's outdated and expect Netdata is running in same docker bridge network as Caddy).

### Expected behavior

Documentation should provide working and compatible recommentations.

### Steps to reproduce

1. Run both Netdata and Caddy containers using examples from documentation.
2. Try to access Netdata from Caddy.

### Installation method

docker

### System info

```shell
Not applicable.
```

### Netdata build info

```shell
Not applicable.
```

### Additional info

Not sure is this the only possible solution or there are some (better) ones, but this one works for me:

1. Update `netdata.conf` to bind on `docker0` interface. Not sure is simple `bind to = docker0` will do the trick, I've used concrete IP: `bind to = 127.0.0.1 172.17.0.1`.
2. Run Caddy container with (compose syntax): `extra_hosts: ["host.docker.internal:host-gateway"]`.
3. Modify `Caddyfile` to use `reverse_proxy host.docker.internal:19999`.

**Comment by ilyam8** [comment]
Hi. It is known and there is no way around it to my knowledge. "With SSL/TLS enabled HTTP Proxy" != "Recommended way".
