### ISSUE TITLE
[Feat]: Improve documentation about recommended mount points for docker for disk usage

### ISSUE THREAD

**Issue by powerman** [netdata/netdata#17892]
### Problem

[Install Netdata with Docker / Recommended way](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#recommended-way) does not list all required mount points (and so is "Mounts" section just above it) for metrics enabled by default: disk usage. This result in worse first time experience for new users.

### Description

It would be nice to mention in the doc needs to mount extra mount points which needs to be monitored for disk usage.

### Importance

really want

### Value proposition

1. New "Netdata with Docker" users will have better first time experience.

### Proposed implementation

Actual mount point depends on user setup so we can't show concrete instruction, but doc can at least mention this option and show example like `/mnt:/host/mnt:ro`.

**Comment by powerman** [comment]
Also adding `/boot:/boot:ro` can be useful by default (or as example) too.

**Comment by ilyam8** [comment]
Hey, @powerman. Please open one issue with all your suggestions.
