### ISSUE TITLE
[Feat]: Improve doc "Install Netdata with Docker"

### ISSUE THREAD

**Issue by powerman** [netdata/netdata#17899]
### Problem

1. [Install Netdata with Docker / Recommended way](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#recommended-way) does not list all required mount points (and so is "Mounts" section just above it) for metrics enabled by default: zram. This result in losing a lot of time to debug this issue for new users.
2. [Install Netdata with Docker / Recommended way](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#recommended-way) does not list all required mount points (and so is "Mounts" section just above it) for metrics enabled by default: disk usage. This result in worse first time experience for new users.
3. [Install Netdata with Docker / Recommended way](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#recommended-way) uses `network_mode: host`, but Caddy setup in [Install Netdata with Docker / With SSL/TLS enabled HTTP Proxy](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#with-ssltls-enabled-http-proxy) won't work this way (it's outdated and expect Netdata is running in same docker bridge network as Caddy).

Note: this is a combined issue, as requested by @ilyam8 in https://github.com/netdata/netdata/issues/17890#issuecomment-2167866214

### Description

1. It would be nice to have zram metrics work out-of-box in a docker configured in recommended way.
2. It would be nice to mention in the doc needs to mount extra mount points which needs to be monitored for disk usage.
3. It would be nice to have Caddy setup example working out-of-box with recommended Netdata setup.

### Importance

nice to have

### Value proposition

1. New "Netdata with Docker" users will have better first time experience.
2. These users won't lose a lot of time trying to make zram metrics work.
3. These users won't lose a lot of time trying to make Caddy work as reverse proxy to Netdata.

### Proposed implementation

1. Add extra mount point `/dev:/host/dev:ro` to make zram metrics work. Details: https://github.com/netdata/netdata/issues/14758#issuecomment-1474854112
2. Actual mount point depends on user setup so we can't show concrete instruction, but doc can at least mention this option and show example like `/mnt:/host/mnt:ro`.
3. Needs several changes:
3.1. Update `netdata.conf` to bind on `docker0` interface. Not sure is simple `bind to = docker0` will do the trick, I've used concrete IP: `bind to = 127.0.0.1 172.17.0.1`.
3.2. Run Caddy container with (compose syntax): `extra_hosts: ["host.docker.internal:host-gateway"]`.
3.3. Modify `Caddyfile` to use `reverse_proxy host.docker.internal:19999`.

**Comment by ilyam8** [comment]
Hi. About 3 - if you are willing to help you can make a PR with the changes and we will review them. We don't recommend using Caddy and don't consider this case important. A user contributed this example.

**Comment by ilyam8** [comment]
`1.` fixed in #17900. `2.` will be a documentation change I think, it won't be a default mount.

**Comment by ilyam8** [comment]
> does not list all required mount points (and so is "Mounts" section just above it) for metrics enabled by default: disk usage.

Fixed in #18035. I added `-v /:/host/root:ro,rslave` to default mounts.
