### ISSUE TITLE
[Bug/Feat]: "Local" pseudo-space name can become unreadable with FQDNs

### ISSUE THREAD

**Issue by intelfx** [netdata/netdata#17904]
### Problem

When netdata is used in local-only mode without any cloud features, it creates a local pseudo-space name using the node hostname.

However, when the node has a long hostname (e.g. a FQDN), this space name may become too long to the point of unreadability and breaking the UI in some places.

E.g. with a hostname of `anystation.nexus.i.intelfx.name`, this is the space URL: `https://anystation.nexus.i.intelfx.name/netdata/spaces/anystationnexusiintelfxname`.

### Description

I'd like if it was possible in Netdata to rename the auto-generated "pseudo-space" via the config.

### Importance

middle-ground between "nice to have" and "really want"

### Value proposition

1. Better UX in "local" mode for nodes whose hostname is a FQDN

### Proposed implementation

I want Netdata to have a separate configuration option that controls the local space name, ideally with any custom string, less ideally as a boolean option to ignore the domain part of the hostname:

- ideal: `anystationnexusiintelfxname` -> `myname`
- less ideal: `anystationnexusiintelfxname` -> `anystation`

**Comment by ilyam8** [comment]
Hi, @intelfx.

> this space name may become too long to the point of unreadability and **breaking the UI in some places**

What places? What do you mean by breaking?

**Comment by ilyam8** [comment]
Hey, @intelfx.

This has been fixed:

- very long space name obscures the "hide" button
- horizontal scrollbar

We don't plan to add a configuration option that controls the local space name.
