### ISSUE TITLE
[Feat]: dm-cache monitoring collector

### ISSUE THREAD

**Issue by ionoci** [netdata/netdata#17929]
### Problem

Hi Netdata,
I'd like to monitor the cache statistics of dm-cache logical volumes, but there is no collector for this. For evaluating the effectiveness of a dm-cache device one need statistics gathered. I think netdata is the right place for this.
This feature had been addressed in #4873 previously.
I got some code written with python, but it need suid-rights to dmsetup, which I don't like.

### Description

Features/metrics I'd like to have per cache volume:

- mdblk_rate - rate in blocks/sec at which metadata device blocks are being consumed (freed if negative)
- used_cblk_rate - rate in blocks/sec at which fast device (cache) blocks are being consumed (or freed if negative)
- rd_hit_rate - rate in hits/sec at which dm-cache is getting cache hits for this volume
- wr_hit_rate - rate in hits/sec at which dm-cache is getting cache hits for this volume
- demotion_rate - rate in blocks/sec at which dm-cache is demoting blocks from fast to slow device
- promotion_rate - rate in blocks/sec at which dm-cache is promoting blocks from slow to fast device
- dirty_rate - rate in blocks/sec at which dm-cache is adding/removing dirty blocks
- md_usage - usage in percent of the metadata
- cache_usage - usage in percent of the cache volume

### Importance

nice to have

### Value proposition

1. dm-cache is a widely used caching system on lots of linux servers. administrators like to see how nice it works.
2. some other monitoring tools got plugins for this already (p.e. munin dm_cache_statistics_)
3. a collector for this will round up the linux support of netdata

### Proposed implementation

I wrote some code, but I'm new to python
The collector does not yet provide the metrics I'd like and need suid on dmsetup :(
How should I submit the code?

**Comment by ionoci** [comment]
Hi, @ilyam8 

- There are two type of dm-cache, I used cachevol. Steps for creating a dm-cache are:
  - create a slow(spinning) pv `pvcreate /dev/hdd` and a fast(ssd) pv `pvcreate /dev/ssd`
  - create a volumegroup with both pv `vgcreate vg-cache-test /dev/hdd /dev/ssd`
  - create logical volumes:
    - data(slow) `lvcreate --name lv-data --extents 100%FREE vg-cache-test /dev/hdd`
    - cache(fast) `lvcreate --name lv-cache --extents 100%FREE vg-cache-test /dev/ssd`
  - attach cachevol to data volume `lvconvert --type cache --cachevol lv-cache  vg-cache-test/lv-data`
  - documentation for this https://man7.org/linux/man-pages/man7/lvmcache.7.html
 
- output of `dmsetup status --target cache` on one of my servers is:
`vg_raid1_md21-media: 0 2404139008 cache 8 2368/10240 4096 189024/786216 82870357 5499462 26280342 8017854 0 22905 0 3 metadata2 writethrough no_discard_passdown 2 migration_threshold 32768 mq 10 random_threshold 0 sequential_threshold 0 discard_promote_adjustment 0 read_promote_adjustment 0 write_promote_adjustment 0 rw - `

**Comment by ilyam8** [comment]
> vg_raid1_md21-media: 0 2404139008 cache 8 2368/10240 4096 189024/786216 82870357 5499462 26280342 8017854 0 22905 0 3 metadata2 writethrough no_discard_passdown 2 migration_threshold 32768 mq 10 random_threshold 0 sequential_threshold 0 discard_promote_adjustment 0 read_promote_adjustment 0 write_promote_adjustment 0 rw -

I guess this is [Cache Status](https://www.kernel.org/doc/html/next/admin-guide/device-mapper/cache.html#status)

0. device: `vg_raid1_md21-media`
1. ?: `0`
2. ?: `2404139008`
3. target: `cache`
4. metadata block size: `8`
5. used metadata blocks/total metadata blocks: `2368/10240`
6. cache block size: `4096`
7. used cache blocks/total cache blocks: `189024/786216`
8. read hits: `82870357`
9. read misses: `5499462`
10. write hits: `26280342`
11. write misses: `8017854`
12. demotions: `0`
13. promotions: `22905`
14. dirty: `0`

**Comment by ionoci** [comment]
Right, it's cache status.
1. First sector, may be ignored for the collector
2. Last sector, may be ignored for the collector 
3. ignore
4. ignore
5. metadata usage
6. ignore
7. cache usage
8. read hits/poll interval -> rd_hits/s would be nice. I don't know how to do this, because I would need the previously polled value for calculation.
9. read misses/poll interval -> rd_misses/s
10. write hits/poll interval -> wr_hits/s. same as before
11. write misses/poll interval -> wr_misses/s. same as before
12. demotions/poll interval -> demotion rate. same as before
13. promotions/poll interval -> promotion rate. same as before
14. dirty/poll interval -> dirty rate. same as before

for some interessting values see also none working python script https://github.com/bengland2/dmcache-stat/tree/master.

**Comment by ionoci** [comment]
Hi @ilyam8,
really fast :+1:  does the close of this issue and #17947 mean, there will be a go dmcache collector in one of the next releases?

**Comment by ilyam8** [comment]
It's already in the nightly release.

**Comment by ionoci** [comment]
Thanks a lot. I can't use nightly in our environment, so I'll have to wait a bit.

**Comment by ilyam8** [comment]
Wey, @ionoci. We released v1.46.0 yesterday and plan to release v1.46.1 tomorrow. If you find any problems with go.d/dmcache by then, I may be able to include fixes in the patch release.

**Comment by ionoci** [comment]
@ilyam8 Works like a charme. Thanks for the prompt implementation :D
