### ISSUE TITLE
[Bug]: `apt upgrade` - File has unexpected size

### ISSUE THREAD

**Issue by GrantBirki** [netdata/netdata#17941]
### Bug description

When trying to upgrade the version of netdata via `apt` the following error appears:

```console
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  cloud-init netdata netdata-plugin-apps netdata-plugin-chartsd netdata-plugin-debugfs netdata-plugin-ebpf
  netdata-plugin-go netdata-plugin-network-viewer netdata-plugin-nfacct netdata-plugin-perf
  netdata-plugin-pythond netdata-plugin-slabinfo netdata-plugin-systemd-journal snapd
14 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 298 kB/68.6 MB of archives.
After this operation, 281 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y 
Get:1 http://repo.netdata.cloud/repos/edge/ubuntu mantic/ netdata-plugin-pythond 1.45.0-631-nightly [277 kB]Err:1 http://repo.netdata.cloud/repos/edge/ubuntu mantic/ netdata-plugin-pythond 1.45.0-631-nightly
  File has unexpected size (277196 != 277246). Mirror sync in progress? [IP: 2606:4700:20::681a:98d 80]
  Hashes of expected file:
   - SHA256:8bda83706f1bb7c51dd522e985067e2104ff05f1e229952edb3346e91ad2affc
   - SHA1:900f68b9baf98e88af9ef47de3a56d0eaca7102f [weak]
   - MD5Sum:e123314d0687c42fde49fcd28e196b82 [weak]
   - Filesize:277246 [weak]
Get:2 http://repo.netdata.cloud/repos/edge/ubuntu mantic/ netdata-plugin-chartsd 1.45.0-631-nightly [21.2 kB]
Err:2 http://repo.netdata.cloud/repos/edge/ubuntu mantic/ netdata-plugin-chartsd 1.45.0-631-nightly
  File has unexpected size (21182 != 21176). Mirror sync in progress? [IP: 2606:4700:20::681a:98d 80]
  Hashes of expected file:
   - SHA256:ebbd8734c9a8ea74b7b39b6955c4bd061fe0394671d4eadf985281b9798825eb
   - SHA1:e5ae66624ede505e6cd4198c579d604a64a05c9e [weak]
   - MD5Sum:844c6bb3846212f596efd3fd5bf2f739 [weak]
   - Filesize:21176 [weak]
E: Failed to fetch http://repo.netdata.cloud/repos/edge/ubuntu/mantic/netdata-plugin-pythond_1.45.0-631-nightly%2bubuntu23.10_all.deb  File has unexpected size (277196 != 277246). Mirror sync in progress? [IP: 2606:4700:20::681a:98d 80]
   Hashes of expected file:
    - SHA256:8bda83706f1bb7c51dd522e985067e2104ff05f1e229952edb3346e91ad2affc
    - SHA1:900f68b9baf98e88af9ef47de3a56d0eaca7102f [weak]
    - MD5Sum:e123314d0687c42fde49fcd28e196b82 [weak]
    - Filesize:277246 [weak]
E: Failed to fetch http://repo.netdata.cloud/repos/edge/ubuntu/mantic/netdata-plugin-chartsd_1.45.0-631-nightly%2bubuntu23.10_all.deb  File has unexpected size (21182 != 21176). Mirror sync in progress? [IP: 2606:4700:20::681a:98d 80]
   Hashes of expected file:
    - SHA256:ebbd8734c9a8ea74b7b39b6955c4bd061fe0394671d4eadf985281b9798825eb
    - SHA1:e5ae66624ede505e6cd4198c579d604a64a05c9e [weak]
    - MD5Sum:844c6bb3846212f596efd3fd5bf2f739 [weak]
    - Filesize:21176 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Expected behavior

I would expect `sudo apt upgrade` to not fail

### Steps to reproduce

1. `sudo apt upgrade`

That's all

### Installation method

manual setup of official DEB/RPM packages

### System info

$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux vps-d2fefb92 6.5.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:55:15 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=23.10
/etc/lsb-release:DISTRIB_CODENAME=mantic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 23.10"
/etc/os-release:PRETTY_NAME="Ubuntu 23.10"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="23.10"
/etc/os-release:VERSION="23.10 (Mantic Minotaur)"
/etc/os-release:VERSION_CODENAME=mantic
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=mantic
/etc/os-release:LOGO=ubuntu-logo

### Netdata build info

$ netdata -W buildinfo
Packaging:
    Netdata Version ____________________________________________ : v1.45.0-615-nightly
    Installation Type __________________________________________ : binpkg-deb
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ : ubuntu 23.10
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 6.5.0-41-generic
    Operating System ___________________________________________ : Ubuntu
    Operating System ID ________________________________________ : ubuntu
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 23.10 (Mantic Minotaur)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 4
    CPU Frequency ______________________________________________ : 2645000000
    RAM Bytes __________________________________________________ : 3995414528
    Disk Capacity ______________________________________________ : 85899345920
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : kvm
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine (compression) _____________________________________ : YES (zstd lz4)
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : NO
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : YES
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : YES
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : YES
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO

### Additional info

related: https://github.com/netdata/netdata/issues/17347

**Comment by ilyam8** [comment]
Hey, @GrantBirki. Can you retry?

**Comment by GrantBirki** [comment]
@ilyam8 Cool it works now! 🎉 

What did you do?

**Comment by ilyam8** [comment]
Nothing! I guess it was just bad timing. We publish packages every day at night and you may encounter this “File has unexpected size. Mirror sync in progress?" issue if the update starts a short time after publishing. cc @Ferroin

**Comment by Ferroin** [comment]
> I guess it was just bad timing. We publish packages daily and you may encounter this “File has unexpected size. Mirror sync in progress?" issue if the update starts a short time after publishing.

Most likely part of the repository metadata from before the update was still in CloudFlare’s cache. It’s generally pretty rare that it happens, and it’s a bit expensive and quite a bit of work to fix it completely, so it’s not been a priority for us to work on.

We should probably make an explicit mention in the documentation about this though.

**Comment by ktsaou** [comment]
@GrantBirki I noticed you work at Github. You use Netdata at Github, or at home?
If you use Netdata at Github, we would love to discuss about your use case...

**Comment by GrantBirki** [comment]
👋 Hey @ktsaou! I'm currently just using `netdata` on a few personal projects to monitor VMs and containers (https://github.com/the-hideout)

**Comment by jmakov** [comment]
Have the same issue for hours, can't update anything...

**Comment by troykelly** [comment]
This is also an ongoing issue here. We've tried a heap of different times to schedule the updates, but it's _always_ 

```
Failed to fetch http://repo.netdata.cloud/repos/edge/debian/bookworm/netdata-plugin-pythond_1.46.0-236-nightly%2bdebian12_all.deb  File has unexpected size (270434 != 270420). Mirror sync in progress?
```

A separate issue, but I'm also concerned that these are http not https.

**Comment by SuperBenji99** [comment]
Just wanted to comment that I've run into the issue (running on Proxmox 8.2.4:

`apt dist-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  proxmox-kernel-6.2 proxmox-kernel-6.2.16-10-pve proxmox-kernel-6.2.16-12-pve proxmox-kernel-6.2.16-15-pve proxmox-kernel-6.2.16-19-pve proxmox-kernel-6.2.16-20-pve proxmox-kernel-6.5.11-4-pve-signed
  proxmox-kernel-6.5.11-7-pve-signed proxmox-kernel-6.5.13-1-pve-signed proxmox-kernel-6.5.13-5-pve-signed proxmox-kernel-6.8.4-2-pve-signed proxmox-kernel-6.8.4-3-pve-signed pve-kernel-5.15.107-2-pve pve-kernel-6.2
  pve-kernel-6.2.16-3-pve telnet
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  proxmox-kernel-6.8.12-2-pve-signed
The following packages will be upgraded:
  libexpat1 libnvpair3linux libproxmox-rs-perl libpve-rs-perl libpve-storage-perl libssl3 libuutil3linux libzfs4linux libzpool5linux netdata netdata-plugin-apps netdata-plugin-chartsd netdata-plugin-debugfs netdata-plugin-ebpf
  netdata-plugin-go netdata-plugin-network-viewer netdata-plugin-nfacct netdata-plugin-perf netdata-plugin-pythond netdata-plugin-slabinfo netdata-plugin-systemd-journal novnc-pve openssl proxmox-kernel-6.8 pve-container
  pve-esxi-import-tools pve-firmware pve-i18n pve-manager pve-qemu-kvm spl zfs-initramfs zfs-zed zfsutils-linux
34 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 201 kB/326 MB of archives.
After this operation, 587 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://repo.netdata.cloud/repos/edge/debian bookworm/ netdata-plugin-pythond 1.99.0-182-nightly [186 kB]
Err:1 http://repo.netdata.cloud/repos/edge/debian bookworm/ netdata-plugin-pythond 1.99.0-182-nightly
  File has unexpected size (185788 != 185798). Mirror sync in progress? [IP: 104.26.9.141 80]
  Hashes of expected file:
   - SHA256:9ad1a00c39d7507578ed1aaa761ec683455cb47efaadb365234cc86c0032e191
   - SHA1:5fb6867b996a87d1aa7bb9f224a6c16b2e0ff14c [weak]
   - MD5Sum:25a18dcf7bdc5570a29bf9a0150c3232 [weak]
   - Filesize:185798 [weak]
Get:2 http://repo.netdata.cloud/repos/edge/debian bookworm/ netdata-plugin-chartsd 1.99.0-182-nightly [15.1 kB]
Err:2 http://repo.netdata.cloud/repos/edge/debian bookworm/ netdata-plugin-chartsd 1.99.0-182-nightly
  File has unexpected size (15086 != 15090). Mirror sync in progress? [IP: 104.26.9.141 80]
  Hashes of expected file:
   - SHA256:0d49243eecf12b02310066b45c6600688a71fd000c2a4df90a2cbe593d07bd35
   - SHA1:3315f8e33cf6fd7e190526db2313fcdb0ee52015 [weak]
   - MD5Sum:d8b836f731421b92ae404bd5f6d699ec [weak]
   - Filesize:15090 [weak]
E: Failed to fetch http://repo.netdata.cloud/repos/edge/debian/bookworm/netdata-plugin-pythond_1.99.0-182-nightly%2bdebian12_all.deb  File has unexpected size (185788 != 185798). Mirror sync in progress? [IP: 104.26.9.141 80]
   Hashes of expected file:
    - SHA256:9ad1a00c39d7507578ed1aaa761ec683455cb47efaadb365234cc86c0032e191
    - SHA1:5fb6867b996a87d1aa7bb9f224a6c16b2e0ff14c [weak]
    - MD5Sum:25a18dcf7bdc5570a29bf9a0150c3232 [weak]
    - Filesize:185798 [weak]
E: Failed to fetch http://repo.netdata.cloud/repos/edge/debian/bookworm/netdata-plugin-chartsd_1.99.0-182-nightly%2bdebian12_all.deb  File has unexpected size (15086 != 15090). Mirror sync in progress? [IP: 104.26.9.141 80]
   Hashes of expected file:
    - SHA256:0d49243eecf12b02310066b45c6600688a71fd000c2a4df90a2cbe593d07bd35
    - SHA1:3315f8e33cf6fd7e190526db2313fcdb0ee52015 [weak]
    - MD5Sum:d8b836f731421b92ae404bd5f6d699ec [weak]
    - Filesize:15090 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by troykelly** [comment]
@SuperBenji99 if you move off edge and to stable (`--stable-channel`), you will see a lot less of these errors. I get the impression that the edge repo is updated so often it's just _never_ in sync.

So:
```bash
wget -O /tmp/netdata-kickstart.sh https://get.netdata.cloud/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --disable-telemetry
```
