### ISSUE TITLE
[Bug]: netdata fails to found Wireguard

### ISSUE THREAD

**Issue by bukiru** [netdata/netdata#18007]
### Bug description

FreeBSD 13.2, wireguard-go, netdata-1.43.2 and netdata-go-0.58.1 installed and running well
wireguard server and peers configured and running well

netdata can't find Wireguard device.

/usr/local/libexec/netdata/plugins.d/god.plugin -d -m wireguard
...
INF wireguard/collect.go:29 no WireGuard devices found on the host system collector=wireguard job=wireguard
ERR module/job.go:229 check failed collector=wireguard job=wireguard
...

### Expected behavior

expect that netdata could monitor wireguard server and peers, as it says on https://learn.netdata.cloud/docs/collecting-metrics/vpns/wireguard

### Steps to reproduce

1.Install Wireguard-go, netdata and netdata-go
2.follow instruction on https://learn.netdata.cloud/docs/collecting-metrics/vpns/wireguard
3.go.d.pluging says, that wireguard can't be found
...

### Installation method

pkg install netdata netdata-go

### System info

```shell
FreeBSD 13.2-RELEASE-p11 FreeBSD 13.2-RELEASE-p11 GENERIC amd64
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v1.43.2
    Installation Type __________________________________________ : custom
```

**Comment by ilyam8** [comment]
Hi, @bukiru. Unfortunately, can't help you with the issue. We:

- don't support v1.43.2. The latest stable is [v1.46.1](https://github.com/netdata/netdata/releases/tag/v1.46.1).
- "netdata-go" is not maintained by us. I don't know what that package is.

**Comment by bukiru** [comment]
but in FreeBSD repo still no 1.46.1 version
netdata-go is External netdata collection plugin written in Go, just read this - https://www.freshports.org/net-mgmt/netdata-go/

**Comment by ilyam8** [comment]
My points remain - both Netdata and go.d.plugin (netdata-go) are old. v1.43.2 is Oct 30, 2023. I don't know why the package maintainers don't update the package. We (the Netdata team) did not create and maintain it.

> Install Wireguard-go

This is not needed.

The error message you get it is

>  no WireGuard devices found on the host system

go.d.plugin (using https://github.com/WireGuard/wgctrl-go) didn't find any WireGuard network interfaces on your system. Have you configured WireGuard on your host? Do you see wg* devices?

**Comment by bukiru** [comment]
yes, and I wrote it in description: wireguard server and peers configured and running well
