### ISSUE TITLE
[Bug]: fails to build: implicit declaration of function 'LZ4_decompress_safe'

### ISSUE THREAD

**Issue by pva** [netdata/netdata#18012]
### Bug description

I'm trying to build netdata on Gentoo and it failed with the following error:

```
FAILED: CMakeFiles/logs-management.plugin.dir/src/logsmanagement/unit_test/unit_test.c.o 
/usr/bin/x86_64-pc-linux-gnu-gcc -D_GNU_SOURCE -I/usr/include/uuid -I/var/tmp/portage/portage/net-analyzer/netdata-1.46.1/work/netdata-v1.46.1_build -I/var/tmp/portage/portage/net-analyzer/netdata-1.46.1/work/netdata-v1.46.1/src -I/usr/include/json-c -I/var/tmp/portage/portage/net-analyzer/netdata-1.46.1/work/netdata-v1.46.1/src/libnetdata/libjudy/src -I/var/tmp/portage/portage/net-analyzer/netdata-1.46.1/work/netdata-v1.46.1/src/libnetdata/libjudy/src/JudyCommon  -O2 -pipe -march=haswell -mtune=skylake -fno-strict-aliasing -std=gnu11 -fstack-protector-strong -fstack-clash-protection -fcf-protection=full -ffunction-sections -fdata-sections -Wno-builtin-macro-redefined -fexceptions -MD -MT CMakeFiles/logs-management.plugin.dir/src/logsmanagement/unit_test/unit_test.c.o -MF CMakeFiles/logs-management.plugin.dir/src/logsmanagement/unit_test/unit_test.c.o.d -o CMakeFiles/logs-management.plugin.dir/src/logsmanagement/unit_test/unit_test.c.o -c /var/tmp/portage/portage/net-analyzer/netdata-1.46.1/work/netdata-v1.46.1/src/logsmanagement/unit_test/unit_test.c
/var/tmp/portage/portage/net-analyzer/netdata-1.46.1/work/netdata-v1.46.1/src/logsmanagement/unit_test/unit_test.c: In function 'test_compression_decompression':
/var/tmp/portage/portage/net-analyzer/netdata-1.46.1/work/netdata-v1.46.1/src/logsmanagement/unit_test/unit_test.c:138:41: error: implicit declaration of function 'LZ4_compressBound'; did you mean 'compressBound'? [-Wimplicit-function-declaration]
  138 |     size_t required_compressed_space  = LZ4_compressBound(item.text_size);
      |                                         ^~~~~~~~~~~~~~~~~
      |                                         compressBound
/var/tmp/portage/portage/net-analyzer/netdata-1.46.1/work/netdata-v1.46.1/src/logsmanagement/unit_test/unit_test.c:151:33: error: implicit declaration of function 'LZ4_compress_fast' [-Wimplicit-function-declaration]
  151 |     item.text_compressed_size = LZ4_compress_fast(  item.data, item.text_compressed,
      |                                 ^~~~~~~~~~~~~~~~~
/var/tmp/portage/portage/net-analyzer/netdata-1.46.1/work/netdata-v1.46.1/src/logsmanagement/unit_test/unit_test.c:160:8: error: implicit declaration of function 'LZ4_decompress_safe' [-Wimplicit-function-declaration]
  160 |     if(LZ4_decompress_safe( item.text_compressed,
      |        ^~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

### Expected behavior

Successful build.

### Steps to reproduce

# emerge --info net-analyzer/netdata
Portage 3.0.65 (python 3.11.9-final-0, default/linux/amd64/23.0/split-usr/desktop, gcc-14, glibc-2.39-r6, 6.1.69 x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-6.1.69-x86_64-Intel-R-_Xeon-R-_CPU_E5-2680_v3_@_2.50GHz-with-glibc2.39
KiB Mem:   131880644 total,  10239064 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Tue, 25 Jun 2024 13:15:00 +0000
Head commit of repository gentoo: b6c3151c24cde5da3d11f744c6d4d8d918b6f98f
Timestamp of repository guru: Tue, 25 Jun 2024 12:33:59 +0000
Head commit of repository guru: 940f35e50b32520090e47497351d4ec9cb9d66f0

Timestamp of repository plex-overlay: Fri, 21 Jun 2024 07:04:04 +0000
Head commit of repository plex-overlay: 0caaae37011375d165da1377cfd8c31802fdee64

Head commit of repository pouch: a7e7210b9de87efcb1b999db73d771231d99388e

Timestamp of repository steam-overlay: Mon, 17 Jun 2024 09:48:55 +0000
Head commit of repository steam-overlay: 35b2e4df390d79636ff6480e802f556814085aa2

sh bash 5.2_p26-r5
ld GNU ld (Gentoo 2.42 p3) 2.42.0
ccache version 4.10 [disabled]
app-misc/pax-utils:        1.3.7::gentoo
app-shells/bash:           5.2_p26-r5::gentoo
dev-build/autoconf:        2.13-r8::gentoo, 2.71-r7::gentoo
dev-build/automake:        1.16.5-r2::gentoo
dev-build/cmake:           3.28.5::gentoo
dev-build/libtool:         2.4.7-r4::gentoo
dev-build/make:            4.4.1-r1::gentoo
dev-build/meson:           1.4.1::gentoo
dev-java/java-config:      2.3.3-r1::gentoo
dev-lang/perl:             5.38.2-r3::gentoo
dev-lang/python:           3.10.14_p1-r1::gentoo, 3.11.9-r1::gentoo, 3.12.3-r1::gentoo
dev-lang/rust:             1.79.0::gentoo
dev-util/ccache:           4.10-r1::gentoo
sys-apps/baselayout:       2.15::gentoo
sys-apps/sandbox:          2.38::gentoo
sys-apps/systemd:          254.13::gentoo
sys-devel/binutils:        2.42-r1::gentoo
sys-devel/binutils-config: 5.5::gentoo
sys-devel/clang:           17.0.6::gentoo, 18.1.8::gentoo
sys-devel/gcc:             14.1.1_p20240622::gentoo
sys-devel/gcc-config:      2.11::gentoo
sys-devel/lld:             17.0.6::gentoo, 18.1.8::gentoo
sys-devel/llvm:            17.0.6::gentoo, 18.1.8::gentoo
sys-kernel/linux-headers:  6.9::gentoo (virtual/os-headers)
sys-libs/glibc:            2.39-r6::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.ru.gentoo.org/gentoo-portage/
    priority: -1000
    volatile: True
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-jobs: 1
    sync-rsync-extra-opts: 
    sync-rsync-verify-max-age: 3

guru
    location: /var/db/repos/guru
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/guru.git
    masters: gentoo
    volatile: False

plex-overlay
    location: /var/db/repos/plex-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/plex-overlay.git
    masters: gentoo
    volatile: False

pouch
    location: /portage/overlays/pouch
    sync-type: git
    sync-uri: https://github.com/pva/pouch
    masters: gentoo
    volatile: True

steam-overlay
    location: /var/db/repos/steam-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/steam-overlay.git
    masters: gentoo
    volatile: False

anyc
    location: /var/lib/layman/anyc
    masters: gentoo
    priority: 50
    volatile: True

booboo
    location: /var/lib/layman/booboo
    masters: gentoo
    priority: 50
    volatile: True

sheep-box
    location: /usr/local/sheep-box
    masters: gentoo
    priority: 50
    volatile: True

xdch47
    location: /var/lib/layman/xdch47
    masters: gentoo
    priority: 50
    volatile: True

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="@FREE"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -march=haswell -mtune=skylake"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /opt/cxoffice/etc/cxoffice.conf /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/easy-rsa /usr/share/gnupg/qualified.txt /usr/share/maven-bin-3.9/conf"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -pipe -march=haswell -mtune=skylake"
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--keep-going --jobs=2 --with-bdeps=y --autounmask=n --read-news=n 	--verbose-slot-rebuilds --verbose-conflicts"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GDK_PIXBUF_MODULE_FILE GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance buildpkg buildpkg-live candy compressdebug config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync merge-wait multilib-strict network-sandbox news parallel-fetch pid-sandbox pkgdir-index-trusted preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms sign splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://gentoo.bloodhost.ru/"
LANG="POSIX"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs"
LEX="flex"
LINGUAS="ru en en_GB en_US"
MAKEOPTS="-j40"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp/portage"
SHELL="/bin/bash"
USE="X a52 aac acl acpi alsa amd64 amr archive audit avif blake2 bluetooth bluray bpf branding btrfs bzip2 cairo caps cdda cddb cdr cet chromaprint colord crypt cryptsetup cups curl dav1d dbus device-mapper dga dist-kernel djvu dnssec dri dri3 drm dts dv dvd dvdr dvi eds egl enchant encode evdev exif fam fdk ffmpeg fftw flac fluidsynth fontconfig fprint gdbm gdk-pixbuf gif gimp glib gnome-keyring gnome-online-accounts google googledrive gpg gphoto2 graphviz gsm gstreamer gtk gtk3 gui harfbuzz heif highlight http2 iconv icu id3tag idn imagemagick introspection ios ipmi iproute2 ipv6 jbig jit jpeg jpeg2k kf6compat kms latex lcms libass libnotify libtirpc lm-sensors lto lvm lzma lzo mad matroska midi mng modemmanager modplug mp3 mp4 mpeg mtp multilib musepack nautilus ncurses netlink networkauth networkmanager nls nsplugin ocr ofx ogg opengl openmp opus osc pam pango pcap pcre pdf pgo pipewire plotutils png policykit postscript ppds pulseaudio python qml qt6 rav1e raw rdp readline scanner sdl seccomp smi snappy sound speex spell spice split-usr sqlite srt ssl startup-notification stemmer svg svt-av1 systemd t1lib taglib test-rust theora threads tiff tracker truetype twolame udev udisks unicode upower urandom usb user-session vaapi vcd vim-syntax visio vlc vorbis vpx vulkan wavpack wayland webchannel webkit webp widgets wifi wmf wxwidgets x264 x265 xattr xcb xetex xft xkb xml xmp xpm xps xv xvid zlib zstd" ABI_X86="64" ADA_TARGET="gcc_12" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_anon authn_dbm authn_file authz_dbm authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir env expires ext_filter file_cache filter headers include info log_config logio mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 ntrip navcom oceanserver oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 tsip tripmate tnt ublox" GRUB_PLATFORMS="efi-64 pc" INPUT_DEVICES="evdev" KERNEL="linux" L10N="ru en en_GB en_US" LCD_DEVICES="bayrad cfontz glk hd44780 lb216 lcdm001 mtxorb text" LIBREOFFICE_EXTENSIONS="scripting-javascript wiki-publisher" LLVM_SLOT="18" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php8-2" POSTGRES_TARGETS="postgres15" PYTHON_SINGLE_TARGET="python3_10" PYTHON_TARGETS="python3_11 python3_10" RUBY_TARGETS="ruby31" VIDEO_CARDS="intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipp2p iface geoip fuzzy condition tarpit sysrq proto logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LFLAGS, LIBTOOL, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, PYTHONPATH, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

=================================================================
                        Package Settings
=================================================================

net-analyzer/netdata-1.45.4::gentoo was built with the following:
USE="python systemd -aclk -bpf -cloud -cups -dbengine -filecaps -ipmi -mongodb -mysql -nfacct -nodejs -postgres -prometheus -tor -xen" ABI_X86="(64)" PYTHON_SINGLE_TARGET="python3_10 -python3_11 -python3_12"
CFLAGS="-O2 -pipe -march=haswell -mtune=skylake -fno-strict-aliasing"
CXXFLAGS="-O2 -pipe -march=haswell -mtune=skylake -fno-strict-aliasing"

### Installation method

from source

### System info

```shell
# uname -a; grep -HvE "^#|URL" /etc/*release
Linux b612-dev3-desktop 6.1.69 #1 SMP PREEMPT_DYNAMIC Tue Jan  9 20:28:38 UTC 2024 x86_64 Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz GenuineIntel GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.15
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:VERSION_ID="2.15"
```

### Netdata build info

```shell
After applying patch I'll paster here build, netdata buildinfo is the following:
# netdata -W buildinfo
Packaging:
    Netdata Version ____________________________________________ : v1.46.1
    Installation Type __________________________________________ : custom
    Package Architecture _______________________________________ : unknown
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 6.1.69
    Operating System ___________________________________________ : unknown
    Operating System ID ________________________________________ : unknown
    Operating System ID Like ___________________________________ : unknown
    Operating System Version ___________________________________ : unknown
    Operating System Version ID ________________________________ : 2.15
    Detection __________________________________________________ : unknown
Hardware:
    CPU Cores __________________________________________________ : 48
    CPU Frequency ______________________________________________ : 3300000000
    RAM Bytes __________________________________________________ : 135045779456
    Disk Capacity ______________________________________________ : 20324008083456
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : lxc
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : Gentoo
    Container Operating System ID ______________________________ : gentoo
    Container Operating System ID Like _________________________ : unknown
    Container Operating System Version _________________________ : 2.15
    Container Operating System Version ID ______________________ : 2.15
    Container Operating System Detection _______________________ : Mixed
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : NO (unavailable)
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip brotli)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine (compression) _____________________________________ : NO
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : NO
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : YES
    protobuf (platform-neutral data serialization protocol) ____ : NO
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : YES
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : NO
    freeipmi (monitor enterprise server H/W) ___________________ : NO
    nfacct (gather netfilter accounting) _______________________ : NO
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : YES
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : NO
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : NO
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

### Additional info

Following patch fix issue for me.

**Comment by ilyam8** [comment]
Fixed in #18002
