### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mcusee** [netdata/netdata#18071]
### Bug description

The openwrt log keeps appearing and I don’t do anything.

### Expected behavior

Wed Jul  3 18:38:00 2024 daemon.info netdata[10913]: PARSER ended
Wed Jul  3 18:38:00 2024 daemon.err netdata[10913]: '/usr/lib/netdata/plugins.d/charts.d.plugin' (pid 9689) disconnected after 35785 successful data collections (ENDs).
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: connected to '/usr/lib/netdata/plugins.d/charts.d.plugin' running on pid 13258
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone0_thermal_thermal_zone0' on host 'OpenWrt' already exists.
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone0_hwmon_hwmon1' on host 'OpenWrt' already exists.
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone1_thermal_thermal_zone1' on host 'OpenWrt' already exists.
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone1_hwmon_hwmon2' on host 'OpenWrt' already exists.
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'netdata.plugin_chartsd_sensors' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:05 2024 daemon.err netdata[10913]: read failed: end of file
Wed Jul  3 22:38:05 2024 daemon.info netdata[10913]: PARSER ended
Wed Jul  3 22:38:05 2024 daemon.err netdata[10913]: '/usr/lib/netdata/plugins.d/charts.d.plugin' (pid 13258) disconnected after 35785 successful data collections (ENDs).
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: connected to '/usr/lib/netdata/plugins.d/charts.d.plugin' running on pid 16602
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone0_thermal_thermal_zone0' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone0_hwmon_hwmon1' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone1_thermal_thermal_zone1' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone1_hwmon_hwmon2' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'netdata.plugin_chartsd_sensors' on host 'OpenWrt' already exists.
Thu Jul  4 02:38:10 2024 daemon.err netdata[10913]: read failed: end of file

### Steps to reproduce

1.
2.
3.
...
            

### Installation method

kickstart.sh

### System info

```shell
Wed Jul  3 18:38:00 2024 daemon.info netdata[10913]: PARSER ended
Wed Jul  3 18:38:00 2024 daemon.err netdata[10913]: '/usr/lib/netdata/plugins.d/charts.d.plugin' (pid 9689) disconnected after 35785 successful data collections (ENDs).
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: connected to '/usr/lib/netdata/plugins.d/charts.d.plugin' running on pid 13258
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone0_thermal_thermal_zone0' on host 'OpenWrt' already exists.
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone0_hwmon_hwmon1' on host 'OpenWrt' already exists.
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone1_thermal_thermal_zone1' on host 'OpenWrt' already exists.
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone1_hwmon_hwmon2' on host 'OpenWrt' already exists.
Wed Jul  3 18:38:02 2024 daemon.info netdata[10913]: RRDSET: chart name 'netdata.plugin_chartsd_sensors' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:05 2024 daemon.err netdata[10913]: read failed: end of file
Wed Jul  3 22:38:05 2024 daemon.info netdata[10913]: PARSER ended
Wed Jul  3 22:38:05 2024 daemon.err netdata[10913]: '/usr/lib/netdata/plugins.d/charts.d.plugin' (pid 13258) disconnected after 35785 successful data collections (ENDs).
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: connected to '/usr/lib/netdata/plugins.d/charts.d.plugin' running on pid 16602
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone0_thermal_thermal_zone0' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone0_hwmon_hwmon1' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone1_thermal_thermal_zone1' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'sensors.temp_thermal_zone1_hwmon_hwmon2' on host 'OpenWrt' already exists.
Wed Jul  3 22:38:07 2024 daemon.info netdata[10913]: RRDSET: chart name 'netdata.plugin_chartsd_sensors' on host 'OpenWrt' already exists.
Thu Jul  4 02:38:10 2024 daemon.err netdata[10913]: read failed: end of file
```

### Netdata build info

```shell
LEDE openwrt
```

**Comment by ilyam8** [comment]
Hi. These logs don’t indicate an issue.
