### ISSUE TITLE
[O365/Teams Connector EOL]: O365 connectors within Teams will be deprecated and notifications from this service will stop.

### ISSUE THREAD

**Issue by Raptus1** [netdata/netdata#18098]
### Bug description

This is included in all the alerts that Netadata sends to Teams:

Action Required: O365 connectors within Teams will be deprecated and notifications from this service will stop. [Learn more](https://aka.ms/O365ConnectorDeprecation) about the timing and how the Workflows app provides a more flexible and secure experience. If you want to continue receiving these types of messages, you can use a workflow to post messages from a webhook request. [Set up workflow](https://teams.microsoft.com/l/task/c3a1996d-db0f-4857-a6ea-7aabf0266b00?url=https://make.powerautomate.com/teams/store/flowCreation?templateId=d271a6f01c2545a28348d8f2cddf4c8f)

### Expected behavior

MS to not suck

### Steps to reproduce

set up teams webhook in netdata config

### Installation method

helmchart (kubernetes)

### System info

```shell
not sure where else to add this incoming issue
```

### Netdata build info

```shell
N/A
```

**Comment by ilyam8** [comment]
Hi, @Raptus1. Can you please elaborate?

> O365 connectors within Teams will be deprecated

I see that Netdata sends notifications to Microsoft Teams via [Webhook](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/what-are-webhooks-and-connectors#incoming-webhooks). Is that deprecated? Or is the [message format](https://github.com/netdata/netdata/blob/e78d0512fd303f33baf3c70c62b79e0ed3143d88/src/health/notifications/alarm-notify.sh.in#L1574-L1592) outdated? What is O365 connectors within Teams?

**Comment by Petemir** [comment]
@ilyam8 Yes, Webhooks (which apparently belong to the class of "O365 connectors") are [deprecated](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/). In theory, they cannot be created anymore, and current ones will stop working in December '24 (with manual action, they'll continue working until December '25).

Microsoft's now requires the use of "Power Automate workflows" and they have two templates that I think could be used by Netdata, namely
1. [Post to a channel when a webhook request is received](https://make.preview.powerautomate.com/galleries/public/templates/d271a6f01c2545a28348d8f2cddf4c8f/post-to-a-channel-when-a-webhook-request-is-received)
2. [Post to a chat when a webhook request is received](https://make.preview.powerautomate.com/galleries/public/templates/34ac6c11796143e1807d6e16c4c28050/post-to-a-chat-when-a-webhook-request-is-received)
