### ISSUE TITLE
RocketChat notifications

### ISSUE THREAD

**Issue by sulian** [netdata/netdata#1811]
Like Slack notifications, can you provide an adapter for Rocket.Chat ?

**Comment by ktsaou** [comment]
[It a shell script](https://github.com/firehol/netdata/blob/master/plugins.d/alarm-notify.sh). Can you give it a try and make a PR?

**Comment by tl87** [comment]
I would also like for this to happen. I know the **LibreNMS** has a working integration for Rocket.Chat (https://github.com/librenms/librenms/blob/master/doc/Alerting/Transports.md#rocketchat)

**Comment by Hermsi1337** [comment]
I created a PR integrating Rocket.chat today:   
https://github.com/firehol/netdata/pull/3777

Hope to hear feedback soon (=

**Comment by ktsaou** [comment]
this has been merged.
thank you!
