### ISSUE TITLE
[Bug]: Linux bridge traffic counted twice toward "total" bandwidth

### ISSUE THREAD

**Issue by infinisean** [netdata/netdata#18185]
### Bug description

Title says it all... traffic egressing an interface (i.e. eth0) which is part of a bridge (i.e. br0) shows up on both, and is combined such that "total" bandwidth is the sum of both, but this is not correct... it should only be counted once, since the bridge interface is just a logical construct, as opposed to a real interface.

### Expected behavior

bridge interface traffic should not be counted toward "total" traffic count.

### Steps to reproduce

1. view eth0
2. view br0
3. view total
4. 1+1  != 2 (in this case) 

### Desktop

Browser Version [e.g. 22]

**Comment by ilyam8** [comment]
Hey. What are you referring to when saying "total"? What total?

**Comment by ilyam8** [comment]
There is no bug. @infinisean if you need aggregated traffic only for physical interfaces use:

- system.net (System overview -> network)
- or select "interface_type" "real" when viewing network interfaces traffic

    <img width="1659" alt="Screenshot 2024-07-16 at 19 11 23" src="https://github.com/user-attachments/assets/c9902a10-6079-46b6-a31f-15baf8eb997b">
