### ISSUE TITLE
[Feat]: Enhance Parent servers to be a proxy for agent auto-updates

### ISSUE THREAD

**Issue by mgalloway-cac** [netdata/netdata#18194]
### Problem

When using NetData in a Parent/Child configuration, child agents lose the ability to auto update as they do when talking directly to netdata.cloud

### Description

Add an option for nodes set as to be Parents to act as a proxy for child nodes to pull agent updates automatically.

### Importance

nice to have

### Value proposition

Main value proposition is to provide the same "ease of management" benefit for those running Netdata in a Parent/Child configuration and when the Parent(s) is acting as the main communication ingress/egress with netdata.cloud.

**Comment by ilyam8** [comment]
I think this is technically impossible to implement.
