### ISSUE TITLE
[Feat]: Documentation and/or Netdata changes to offer safe upgrade paths

### ISSUE THREAD

**Issue by solution-al** [netdata/netdata#18239]
### Problem

We've been using Netdata for years and it has been working great generally. Thanks for that!

During these years we have created some non-default configurations for different collectors and alarms. However, even when during the initial configuration creation we test these alerts thoroughly then after updating Netdata (usually via installing it on a new server and getting a newer version of it via package manager) these configurations might stop working (see https://github.com/netdata/netdata/issues/13596, https://github.com/netdata/netdata/issues/14098 and https://github.com/netdata/netdata/issues/18228 for some examples).

Worst part is that these problems are not visible in any way and only come out if we manually try to replicate all the problems. This is kinda scary since we're talking about a monitoring system and if that does not work as expected then it might give us some sleepless nights.

What is the best practice to update Netdata? Is there some documentation available somewhere about all the steps to minimize configuration breakage risks? Would enabling debug mode after initial installation (which might be a newer version of Netdata than has been used before) help in anyway to detect that kind of problems? Or is there a way to always install a specific version of Netdata which would minimize these risks, but would of course might bring another problems?

### Description

Either a documentation about "best practices" when installing/updating Netdata to make sure that all the configurations are correct or some way to reliably check any Netdata logs for possible problems.

### Importance

really want

### Value proposition

Users have a clear way to make sure that monitoring set up with Netdata works as it has been working with previous versions.

**Comment by ilyam8** [comment]
Hi, @solution-al. Just follow release changes. I add all info to the “deprecation notice” section.

**Comment by jarmo** [comment]
@ilyam8 thank you for your reply. Can you point to some link where release changes are?
