### ISSUE TITLE
Embed charts -> CSS rules are overwritten

### ISSUE THREAD

**Issue by t-h-e** [netdata/netdata#1829]
When embeding charts in another web application, dashboard.js loads an additional css file. All of the css rules, except one, use a class selector which works fine.

The only rule that does not do that is this one: https://github.com/firehol/netdata/blob/master/web/dashboard.css#L1-L7
The dark theme even changes the `color` property: https://github.com/firehol/netdata/blob/master/web/dashboard.slate.css#L7

I'm aware that this rule is required for the default dashboards provided by netdata and that the font and color properties ensure that the charts have a consisten look.

The problem is just that this rule might override existing rules, which it does in my case. So additional css rules have to be added to an existing web application to overwritte rules that are loaded to embed charts.

I was wondering if there is a better way to set these properties and maybe not load them with `dashboard.js`. For example, set these properties only for the charts?

I'm not a css expert, so I'm open to any suggestions ;)

**Comment by ktsaou** [comment]
hm... I am not that strong in CSS either.

What if I add an option to `dashboard.js` to disable loading these css files?

**Comment by t-h-e** [comment]
An option to disable loading the css would kind of fix the problem but would be inconvenient, because then you have to load the css somewhere else yourself to display the charts corretly. But this still requires you to change those rules manually before you can embed the css. Also you have to make sure that the css and the javascript you have are from a compatible version.

Maybe the `dashboard.js` should only load a minimal version of the css that is required to display the charts. A css file with the following rules: `.netdata-*` `.dygraph-*` `.easyPieChart*` `.gaugeChart*` etc.
The `color` property for the dark theme might have to be added in a more specific rule than `html` and `body`.

Rules that are not required by the charts themselves could be in a separate css that is added to the `index.html`, `tv.html` etc. or loaded if a certain option is set for `dashboard.js`.

So my idea would be to have two css files. One for the charts and one for netdata web pages.

**Comment by ktsaou** [comment]
hm... so all custom dashboards would need to set body colors and fonts manually...

I think we need an option to disable them, not an option to enable them. This way, all dashboards will work like they do, and you will have the option to disable them if you need to.

Are you sure you cannot overwrite them with `!important` ? I think you should be able to do this.

**Comment by t-h-e** [comment]
Using `!important` is in general no good idea and I think in this case it doesn't even help.

If I would set `color: black !important;` in my stylesheet, it would definitely overwrite the rule in `dashboard.css`. But then even the text in the charts would be black, which would make the text barely readable in the dark theme.

It is a little bit different with the font. There it depends if you want to use the font of the website, in which you embed the charts, or use the fonts specified by netdata. I wouldn't mind either way.

How about removing the rule `html, body` from `dashboard.css` and dynamically adding a new class to all embeded charts `.netdata-font` which contains `font-family`, `font-style`, `font-variant` and `color` (for the dark theme)?

**Comment by t-h-e** [comment]
I had a look at dynamically changing css rules. This works with [CSSStyleSheet](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet) in javascript. But the limitation is, that if the css style sheet is loaded from a different domain (which might be the case, if you embed charts), you do not have access to the css rules in javascript.

I still think the netdata stylesheet should not style the whole document (like `html, body`), but only its own elements (like `.netdata-container` and `.netdata-container-with-legend`). `html, body` rules should be put in a different stylesheet.

**Comment by ktsaou** [comment]
You are probably right. I need to spend some time on this to fix it.

**Comment by timwhite** [comment]
As @t-h-e has stated, netdata should only style it's elements, and not `body` and `html`. @ktsaou Have you had a chance to look at this? @VLegakis ?

**Comment by cakrit** [comment]
@jacekkolasa plz take this into account while refactoring. Of course we need to take into account backwards compatibility as wel..

**Comment by jacekkolasa** [comment]
I agree, that's not the way to move forward, dashboard.js should be isolated. @timwhite we're doing heavy refractor now, after which we can add a way to optionally remove global styles, via some `window.netdata...` flag

**Comment by jacekkolasa** [comment]
I'm setting it as low-priority because i'm not sure how needed is this feature in 2020. During refactoring i didn't had to change css, so "dashboard.js" part is still not isolated.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
