### ISSUE TITLE
[Feat]: openrc

### ISSUE THREAD

**Issue by vermaete** [netdata/netdata#18309]
### Problem

Could it be possible to bring the support of OpenRC under a condition during configuration (in CMake)?

The Yocto image (WIC) is failing on it now:
```
ERROR: netdata-1.46.3-r0 do_package_qa: QA Issue: /usr/lib/netdata/system/openrc/init.d/netdata contained in package netdata requires /sbin/openrc-run, but no providers found in RDEPENDS:netdata? [file-rdeps]
ERROR: netdata-1.46.3-r0 do_package_qa: Fatal QA errors were found, failing task.
```

Although there seems to be support of OpenRC in some meta layer of Yocto, it's not common used.

br

PS: I assume the same for LSB and others.

**Comment by ilyam8** [comment]
Hey, @vermaete. Please ask a question in [GH Discussions](https://github.com/netdata/netdata/discussions) or open a feature request using the template.
