### ISSUE TITLE
Data collection from Waveshare UPS

### ISSUE THREAD

**Issue by Fany-f** [netdata/netdata#18331]
### Description

Hello everyone, I bought a Waveshare UPS HAT (C) for my Raspberry, on which Netdata runs.

If I type in the terminal:
```
cd UPS_HAT_C
python3 INA219.py
```

I get from UPS these data in terminal:
```
Load Voltage:   4.116 V
Current:        0.000 A
Power:          0.000 W
Percent:       93.0%
```

I want to ask, is there a way to get this data into the Netdata dashboard? I would be very happy. Now for these values ​​I have to go to the terminal and type the above command. Otherwise I don't know how to access the data more comfortable way.

Here is full Python code link from Waveshare:
[https://files.waveshare.com/upload/4/40/UPS_HAT_C.7z](https://files.waveshare.com/upload/4/40/UPS_HAT_C.7z)

Thank you very much for your help.

### Importance

nice to have

### Value proposition

1. A convenient overview of the current charge status on one dashboard
2. See Pi electric consumption in the past thanks Netdata

**Comment by ilyam8** [comment]
Hi, @Fany-f. We don't plan to implement this collector:

- very niche request.
- I don't own any such devices, and can't write and maintain collectors for them.

---

The good news is that it is very easy to write a custom Python collector:

 - call "binaryName".
 - parse the output.

ChatGPT will help you if you don't know Python. Use [python.d/exim](https://github.com/netdata/netdata/blob/v1.46.3/src/collectors/python.d.plugin/exim/exim.chart.py) as an example.

1. Change https://github.com/netdata/netdata/blob/1525e866e4ba3d00d122a8c6928c5058a7fde7b7/src/collectors/python.d.plugin/exim/exim.chart.py#L8 to whatever command you are using.
2. Update [charts](https://github.com/netdata/netdata/blob/1525e866e4ba3d00d122a8c6928c5058a7fde7b7/src/collectors/python.d.plugin/exim/exim.chart.py#L14).
3. Write parsing (`self._get_raw_data()` returns the same data you see on the terminal)
https://github.com/netdata/netdata/blob/1525e866e4ba3d00d122a8c6928c5058a7fde7b7/src/collectors/python.d.plugin/exim/exim.chart.py#L37C35-L37C55
