### ISSUE TITLE
[Feat]: sort applications tooltip / popover not by AR if that is not even available

### ISSUE THREAD

**Issue by eMPee584** [netdata/netdata#18346]
### Problem

Hard to figure out which applications are using most resources on a local agent.

### Description

Right now, hovering over the applications chart on a local agent will not show the highest value entries first ~~because the AR column is the active sort method (although all values in there are empty)~~, instead it seems sorted alphabetically. To figure out what the actual applications using resources are, one has to change the sort order of the chart legend to "Sort by value Max→Min".

![Screenshot 2024-08-16 at 11-02-44 LoetRechner Netdata Agent Console](https://github.com/user-attachments/assets/29385bb9-eacb-4869-90b3-b2da7d0f9f04)

### Importance

really want

### Value proposition

1. less user annoyance
2. usefulness of applications section increased
3. leaves a more professional impression
...

**Comment by ilyam8** [comment]
Hey, @eMPee584. It is sorted by value. 
https://github.com/user-attachments/assets/03bd25e9-c70b-490c-95c8-27e700fbb2bb

**Comment by eMPee584** [comment]
@ilyam8 Well it is not under debian bookworm and ubuntu 24.04, maybe you can help me find out why?

**Comment by ilyam8** [comment]
@eMPee584 It looks like it's an old UI. I assume you're using Netdata, not the one we packaged. So either switch to the official Netdata packages or ask whoever created the package you're using.
