### ISSUE TITLE
[Bug]: Windows Beta Agent does not calculate ram correctly

### ISSUE THREAD

**Issue by ss-mbrancato** [netdata/netdata#18468]
### Bug description

![image](https://github.com/user-attachments/assets/22f679db-73ef-4da3-9a2d-47d66eb6830b)
Host shows 16MB of ram when it has 16GB

### Expected behavior

Report installed value

### Steps to reproduce

1. Install beta windows agent
2. view agent in Cloud nodes dashboard
3.

### Installation method

from source

### System info

```shell
Not linux
```

### Netdata build info

```shell
Current windows beta
```

**Comment by thiagoftsm** [comment]
Hello @ss-mbrancato ,

Could you please access the URL http://localhost:19999/api/v1/info on your host and provide us with the `ram_total` value?

Additionally, I have a question regarding your System Info. On my end, using Windows 11 Home, the values appear correctly, so I suspect there might be an issue with a specific version of Microsoft Windows. Could you please share your Windows version?

If you prefer not to share this information here on GitHub, feel free to send it via email to thiago@netdata.cloud.

Best regards!

**Comment by ilyam8** [comment]
> On my end, using Windows 11 Home, the values appear correctly

Can you show?
