### ISSUE TITLE
[Feat]: Windows Event Logs in Netdata 

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#18462]
### Problem

Users and Windows Admins need a way to visualize and explore Windows Event Logs using Netdata

### Description

Netdata should support Windows Event Log monitoring - and these logs should be available in logs tab on Netdata dashboard.

### Importance

must have

### Value proposition

1. Windows Event logs are crucial and critical for effective windows monitoring

**Comment by shyamvalsan** [comment]
This is the [API ](https://learn.microsoft.com/en-us/windows/win32/eventlog/using-event-logging)

**Comment by ilyam8** [comment]
Initial version was added in #18483
