### ISSUE TITLE
[Feat]: SNMP improvements

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#18500]
### Problem

- SNMP devices are not automatically added as virtual nodes, doing this manually is cumbersome
- Netdata does not expose the SNMP device vendor (manufacturer) and model (product)
- Netdata does not offer a summary dashboard for SNMP monitoring

### Description

- [x] Automatically add as virtual node
- [x] Add vendor 
- [ ] Add model/product - where available from vendor
- [ ] Add table to summary dashboard for SNMP section

### Importance

blocker

### Value proposition

1. Make SNMP network device monitoring truly usable

**Comment by ilyam8** [comment]
While I'm planning on creating a standalone SNMP plugin, I've decided to implement a subset of the requested features within the existing collector.

---

#### Automatically create a Virtual Node

- Added as an option, off by default. 
- Vnode GUID generated from the SNMP device IP address.
- Added the "Vnode" section to the SNMP Dyncfg configuration.

<details>
<summary>Dyncfg SNMP Vnode</summary>

<img width="1104" alt="Screenshot 2024-09-12 at 12 00 26" src="https://github.com/user-attachments/assets/757c7b4b-5ed4-49d2-873d-9b5fc634d6e0">

</details>

#### Add vendor

- Added Organization value from [IANA Private Enterprise Numbers](https://www.iana.org/assignments/enterprise-numbers.txt) as a **host label** and **chart label**.

This is probably not 100% vendor but close to it.

#### Add model/product

This is not added.

Unfortunately, there's currently no easy way to automatically extract this information. However, it can potentially be retrieved by parsing the system description ([_sysDescr_](https://oidref.com/1.3.6.1.2.1.1.1)).

> This value should include the full name and version identification of the system's hardware type, software operating-system, and networking software.

Note "should" and not "must".

I checked a few tools and they parse _sysDescr_.

- [mtoshi/sysdescrparser](https://github.com/mtoshi/sysdescrparser)
- [librenmns](https://github.com/librenms/librenms/tree/master/LibreNMS/OS). A lot of PHP code, parsing _sysDescr_ + more additional heuristics.


Solution: extract OS, model (hardware) and software version from _sysDescr_. We will ask users to provide their _sysDescr_ and update included parsers (regular expressions). These extract logic will be in the configuration file, so people don't need to wait for a new version.

#### Add table to summary dashboard for SNMP section

What table? I think the UI in general needs to be adjusted for network SNMP devices (frontend feature, not Agent).
