### ISSUE TITLE
[Feat]: Netdata Windows Agent should be packaged as an MSI installer

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#18521]
### Problem

Windows SysAdmins prefer MSI installers to EXE files due to reasons such as:
- MSI packages can be installed “quietly,” without the need for users to provide any input or be involved in the process
- MSI packages can be rolled out and administered across entire infrastructures smoothly.
- MSI packages offer finer grained control of the installation/uninstallation
- MSI packages support better handling of UAC and privilege elevation

Currently the Netdata windows agent installer is available only as an EXE file.

### Description

Package the Netdata Windows Agent Installer as an MSI

### Importance

must have

### Value proposition

1. This has been requested by beta users already -- and it will be necessary for wide spread adoption across large windows env.

**Comment by Ferroin** [comment]
A couple of quick observations based on cursory searching:

- This can’t be done directly with NSIS, the way it works is fundamentally at odds with MSI packaging. The closest we could theoretically get is wrapping the NSIS executable in an MSI, but that won’t actually get us most of the benefits of using an MSI, so users are unlikely to be happy with that.
- It is _very_ unlikely that we can find anything that runs under MSYS itself to do this, it will essentially _have_ to be Windows native.
- [WiX](https://wixtoolset.org/) seems like the most likely option here, it’s free, is well supported, has an associated CPack generator, and is already included or easily installable in the GHA Windows runners.
