### ISSUE TITLE
[Feat]: Install time flags for windows agent installer

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#18533]
### Problem

- There MUST be a way for performing silent *nothing pops up on the UI) installs of the Netdata windows agent
- There MUST be a way to install the Netdata windows agent and claim it to a space and room from command line, in one command

### Description

- Install time flag "silent" is required to mark the installation as silent so it happens without any UI interaction being required by the user
- Install time flag "token" is required to pass the space token as part of the agent installation
- Install time flag "room" is required to pass the room id as part of the agent installation

All these flags are optional flags.

Currently, passing token and room ID works via `NetdataClaim.exe /T Token /R room` but this is a separate exe that is only available post install. The request here is to make sure this happens with the WindowsAgentInstaller directly. 

Also, in the future when the installer is present as an MSI, these install time flags MUST continue to be supported.

### Importance

must have

### Value proposition

1. Make the windows agent more usable for windows admins.

**Comment by shyamvalsan** [comment]
@thiagoftsm @stelfrag can we prioritize this in one of the upcoming nightlies?

**Comment by thiagoftsm** [comment]
> @thiagoftsm @stelfrag can we prioritize this in one of the upcoming nightlies?

Yes, it is possible. I am investigating it now.
