### ISSUE TITLE
[Feat]: Combined line chart with min, max and average

### ISSUE THREAD

**Issue by Forza-tng** [netdata/netdata#18550]
### Problem

The normal charts averages the measured data points across plotted points. It means when the scale is in order of hours or days, spikes in the data will be averaged out and lost.

It is possible to choose different aggregation methods such as min and max. However they also don't show the "true" data.

![Screenshot_20240914_141848_RVNC Viewer](https://github.com/user-attachments/assets/c1367e57-ac05-4386-b165-84a94a650c6a)

### Description

What I would like to see is a chart that plots the average, just like today, but with the addition of minimum and maximum lines, showing for each plotted average point what the minimum and maximum  was for that specific aggregate period. These additional lines are only visible when the display resolution mandate aggregate plotting. 

This will make it possible to zoom out and still see spikes and other abnormal behaviour.

![min-max-excel-chart-example-1331061591](https://github.com/user-attachments/assets/bea59115-7ead-4d98-9a71-e30fd96a6cb2)

I would really like to see this type of chart for all types of bandwidth and I/O charts, though it would be useful where ever normal line/area charts are used. 

### Importance

really want

### Value proposition

1. This will allow users to quickly see areas of importance by having a long time span and still see real min/max data during the period. 
2.
3.
...

### Proposed implementation

There are many ways this can be implemented. I find the smokeping/rrdtool way pretty good.

![rb29_mini](https://github.com/user-attachments/assets/a9b4dac2-3ffa-4a28-b6b6-e24efd50dd97)

Here we have a shaded area around the main line showing the min/max. 
![DNS-209_4_mini-1734369300](https://github.com/user-attachments/assets/2c1ef871-e3ff-427b-bcbe-f2b2b7192049)

In these charts we shaded bars. The shade intensity indicates how frequently values reach that level. 
![smokeping-3849001184](https://github.com/user-attachments/assets/8b134996-7367-4889-9953-b1da2aabf0f1)
![SmokePing-example-3328497237](https://github.com/user-attachments/assets/3f9d73a3-5ea0-47a2-b0ca-ffd547229eb7)

**Comment by ilyam8** [comment]
1. You can select the time aggregation function (min, avg, max, etc) for any chart now.

> However they also don't show the "true" data.

They do show. If you find a problem with it, please don't hesitate to create a bug report. But I can't confirm the bug (checked my ND instances).

2. Combined line chart with min, max and average

I think this is wontfix because many charts have multiple dimensions and showing  + min/max for every will be very noisy.

Also, it is possible to see min/max value for all dimensions for the selected timeframe by clicking on the dimension selector:

<img width="1634" alt="Screenshot 2024-09-14 at 18 08 31" src="https://github.com/user-attachments/assets/ea239ecf-a638-46f5-911d-9603ce7a04fc">

**Comment by ilyam8** [comment]
cc @shyamvalsan @sashwathn check this feature request and reopen it if needed.

**Comment by Forza-tng** [comment]
> 1. You can select the time aggregation function (min, avg, max, etc) for any chart now.
> 
> > However they also don't show the "true" data.
> 
> They do show. If you find a problem with it, please don't hesitate to create a bug report. But I can't confirm the bug (checked my ND instances).

Yes while you can set either min or max, it is difficult to determine how much of the time was at max. 

> 
> 2. Combined line chart with min, max and average
> 
> I think this is wontfix because many charts have multiple dimensions and showing + min/max for every will be very noisy.

Could we not have this as a type of selectable chart, like we have with stacked, area, line, heat map, etc? 

> 
> Also, it is possible to see min/max value for all dimensions for the selected timeframe by clicking on the dimension selector:
> 
> <img alt="Screenshot 2024-09-14 at 18 08 31" width="1634" src="https://private-user-images.githubusercontent.com/22274335/367524015-ea239ecf-a638-46f5-911d-9603ce7a04fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjg4MDksIm5iZiI6MTcyNjMyODUwOSwicGF0aCI6Ii8yMjI3NDMzNS8zNjc1MjQwMTUtZWEyMzllY2YtYTYzOC00NmY1LTkxMWQtOTYwM2NlN2EwNGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE1NDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZTM0NjA5YmE3ODYwMTdlOWIxNDdjMDUzODc1OTNjYjNlODlkYjM0YWY0YzA1OTVhN2JmYzQ3ZGRmMzAxNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.llERyIDbf-UajuV8L2M_ieJqv4z5z-k0b0Y3rAm7B50">

Thanks. While it is true, it is still difficult to find where outliers are. It means to actively switch between the settings and scan across time. That's comparatively difficult and time consuming.
