### ISSUE TITLE
[Feat]: Improve process manager configuration in apps.plugin

### ISSUE THREAD

**Issue by xd003** [netdata/netdata#18663]
### Problem

Currently, while configuring [app.plugin](https://github.com/netdata/netdata/tree/master/src/collectors/apps.plugin#configuration) in Netdata, it requires us to edit the  `/etc/netdata/apps_groups.conf` file wherein process managers are defined using process names (ie. executable) limiting flexibility. For instance, multiple processes with the same executable name (e.g., `bash script1.sh` and `bash script2.sh`) cannot be distinctly managed. Defining a process manager as `scripts: bash` would group both scripts under the same manager, making it impossible to isolate specific processes.

### Description

Introducing the ability to define process managers not only by process name but also by the full command (i.e., executable + arguments) would enable more precise control over process grouping. For example, this would allow managing individual scripts separately:
```
script1: 'bash script1.sh'
script2: 'bash script2.sh'
python-script1: `python3 script1.py`
python-script2: `python3 script2.py`
bash-scripts: bash (group all processes with executable `bash` as bash-scripts) #currently possible
python-scripts: python3 (group all processes with executable `python3` as python-scripts) #currently possible
sometask: 'full command1' 'full command2'
```
### Importance

must have

### Value proposition

1. Enhanced Precision: Allowing full command-based grouping increases granularity, enabling users to isolate and manage specific processes, even if they share the same executable.
2. Improved Flexibility: Users can define custom process managers for different scripts or commands, offering more control in complex environments with multiple similar processes.
3. User-Friendly Process Management: By offering additional ways to define process managers with full command, Netdata makes process grouping more intuitive and less prone to errors, enhancing overall usability.

**Comment by xd003** [comment]
Just to confirm, what is the default internal list of interpreters that is currently being shipped with the plugin on linux ?
I am asking because i still see `bash` as one of the app groups

**Comment by ilyam8** [comment]
Did you read https://github.com/netdata/netdata/tree/master/src/collectors/apps.plugin#configuring-interpreters?

> To address this, `apps.plugin` allows you to configure interpreters and specify that the actual process name can be found in one of the command-line parameters of the interpreter.

Interpreter is not a manager. Netdata doesn't monitor its children processes.

**Comment by xd003** [comment]
> Interpreter is not a manager. Netdata doesn't monitor its children processes.

Thanks for revising the docs, its much easier to understand now. Although i can't seem to get the app group to work as intended

![image_2024-10-07_19-19-21](https://github.com/user-attachments/assets/173de96d-a41e-454d-8429-643a840f87a5)
Here is the process tree of the process i want to group as `emby`

`cat /proc/80326/cmdline | tr '\0' ' '` returns `bash start.sh` as expected
The `apps_group.conf` file contains just a single line - `emby: *'bash start.sh'*`

Netdata still categorizes this process as `bash`
![image_2024-10-07_19-21-18](https://github.com/user-attachments/assets/fc85f155-15a0-406b-9fdf-5e844579c812)

**Comment by xd003** [comment]
> '*bash start.sh*'

It's still categorized as `bash`. If you need any more info, please do let me know.

**Comment by ilyam8** [comment]
Works for me.

<details>
<summary>ps tree</summary>

```
root       10796  0.0  0.0 1537572 24580 ?       Sl   Oct06   0:12 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 961a2dd3ef6cc52ab27703d55c7ca05227755640d72f146031f
54321      10816  0.0  0.0  11708  2780 ?        Ss   Oct06   0:00  \_ /bin/bash /opt/oracle/runOracle.sh
54321      10897  0.0  0.1 144188 30208 ?        Ss   Oct06   0:00      \_ /opt/oracle/product/21c/dbhomeXE/bin/tnslsnr LISTENER -inherit
54321      10938  0.0  0.3 2082272 80812 ?       Ss   Oct06   0:05      \_ xe_pmon_XE
54321      10942  0.0  0.2 2082268 67448 ?       Ss   Oct06   0:01      \_ xe_clmn_XE
54321      10946  0.0  0.2 2082400 67724 ?       Ss   Oct06   0:12      \_ xe_psp0_XE
54321      10950  0.0  0.3 2099588 74124 ?       Ss   Oct06   0:19      \_ xe_vktm_XE
54321      10956  0.0  0.3 2100108 85100 ?       Ss   Oct06   0:05      \_ xe_gen0_XE
54321      10960  0.0  0.3 2082272 79460 ?       Ss   Oct06   0:02      \_ xe_mman_XE
54321      10966  0.0  0.4 2204992 110008 ?      Ssl  Oct06   0:18      \_ xe_gen1_XE
54321      10968  0.0  0.2 2082268 65980 ?       Ss   Oct06   0:01      \_ xe_gen2_XE
54321      10973  0.0  0.2 2082268 66472 ?       Ss   Oct06   0:01      \_ xe_vosd_XE
54321      10975  0.0  0.2 2082380 68184 ?       Ss   Oct06   0:03      \_ xe_diag_XE
54321      10977  0.0  0.3 2206028 96968 ?       Ssl  Oct06   0:02      \_ xe_ofsd_XE
54321      10979  0.0  0.4 2102032 119988 ?      Ss   Oct06   0:24      \_ xe_dbrm_XE
54321      10983  0.3  0.2 2082268 70520 ?       Ss   Oct06   4:18      \_ xe_vkrm_XE
54321      10985  0.0  0.2 2086364 71640 ?       Ss   Oct06   0:03      \_ xe_svcb_XE
54321      10987  0.0  0.2 2082272 68680 ?       Ss   Oct06   0:10      \_ xe_pman_XE
54321      10992  0.1  0.4 2093344 103732 ?      Ss   Oct06   1:25      \_ xe_dia0_XE
54321      10994  0.0  0.5 2091232 145808 ?      Ss   Oct06   0:03      \_ xe_dbw0_XE
54321      10996  0.0  0.5 2090204 143140 ?      Ss   Oct06   0:03      \_ xe_dbw1_XE
54321      10998  0.0  0.3 2100620 87524 ?       Ss   Oct06   0:03      \_ xe_lgwr_XE
54321      11000  0.0  0.3 2082280 94100 ?       Ss   Oct06   0:14      \_ xe_ckpt_XE
54321      11004  0.0  0.4 2083704 119512 ?      Ss   Oct06   0:01      \_ xe_smon_XE
54321      11006  0.0  0.2 2082272 69460 ?       Ss   Oct06   0:05      \_ xe_smco_XE
54321      11008  0.0  0.3 2410312 80972 ?       Ssl  Oct06   0:07      \_ xe_bg00_XE
54321      11014  0.0  0.3 2083616 91212 ?       Ss   Oct06   0:00      \_ xe_reco_XE
54321      11018  0.0  0.4 2091356 114120 ?      Ss   Oct06   0:02      \_ xe_lreg_XE
54321      11026  0.0  0.2 2082272 66196 ?       Ss   Oct06   0:01      \_ xe_pxmn_XE
54321      11030  0.0  0.9 2111400 243600 ?      Ss   Oct06   0:13      \_ xe_mmon_XE
54321      11033  0.0  0.3 2082560 89924 ?       Ss   Oct06   0:02      \_ xe_mmnl_XE
54321      11038  0.0  0.3 2410312 80028 ?       Ssl  Oct06   0:07      \_ xe_bg01_XE
54321      11046  0.0  0.4 2083320 118872 ?      Ss   Oct06   0:01      \_ xe_w000_XE
54321      11048  0.0  0.2 2084780 66004 ?       Ss   Oct06   0:01      \_ xe_d000_XE
54321      11050  0.0  0.3 2082020 74000 ?       Ss   Oct06   0:02      \_ xe_lg00_XE
54321      11052  0.0  0.2 2083564 61228 ?       Ss   Oct06   0:00      \_ xe_s000_XE
54321      11054  0.0  0.5 2084520 126612 ?      Ss   Oct06   0:01      \_ xe_w001_XE
54321      11056  0.0  0.2 2082268 66972 ?       Ss   Oct06   0:00      \_ xe_tmon_XE
54321      11058  0.0  0.2 2082024 73120 ?       Ss   Oct06   0:01      \_ xe_lg01_XE
54321      11062  0.0  0.3 2104612 77968 ?       Ss   Oct06   0:00      \_ xe_tt00_XE
54321      11064  0.0  0.3 2083472 91728 ?       Ss   Oct06   0:00      \_ xe_tt01_XE
54321      11066  0.0  0.2 2082008 65780 ?       Ss   Oct06   0:02      \_ xe_tt02_XE
54321      11075  0.0  1.2 2089588 317940 ?      Ss   Oct06   1:06      \_ xe_m000_XE
54321      11077  0.0  0.2 2082264 65652 ?       Ss   Oct06   0:02      \_ xe_rcbg_XE
54321      11086  0.0  0.3 2082584 81364 ?       Ss   Oct06   0:00      \_ xe_aqpc_XE
54321      11090  0.0  0.2 2081492 59636 ?       Ss   Oct06   0:03      \_ xe_p000_XE
54321      11139  0.0  0.4 2083112 108724 ?      Ss   Oct06   0:01      \_ xe_w002_XE
54321      11441  0.1  0.6 2104168 152700 ?      Ss   Oct06   1:30      \_ xe_cjq0_XE
54321      11470  0.0  0.0   4420   664 ?        S    Oct06   0:02      \_ tail -f /opt/oracle/diag/rdbms/xe/XE/trace/alert_XE.log
54321      11635  0.0  0.9 2092872 230044 ?      Ss   Oct06   1:05      \_ xe_m001_XE
54321      11637  0.0  0.8 2086724 219776 ?      Ss   Oct06   1:04      \_ xe_m002_XE
54321      11659  0.0  0.7 2084492 192248 ?      Ss   Oct06   1:04      \_ xe_m003_XE
54321      11670  0.0  0.4 2083360 101088 ?      Ss   Oct06   0:01      \_ xe_w003_XE
54321      11713  0.0  0.3 2083080 89512 ?       Ss   Oct06   0:01      \_ xe_w004_XE
54321      11761  0.0  0.2 2082008 70088 ?       Ss   Oct06   0:00      \_ xe_qm02_XE
54321      11763  0.0  0.5 2090716 125264 ?      Ss   Oct06   0:01      \_ xe_q001_XE
54321      11767  0.0  0.4 2084444 105100 ?      Ss   Oct06   0:00      \_ xe_q003_XE
54321      13596  0.0  0.2 2082004 66324 ?       Ss   Oct06   0:01      \_ xe_cl00_XE
54321      13598  0.0  0.2 2082008 65228 ?       Ss   Oct06   0:01      \_ xe_cl01_XE
54321      13600  0.0  0.2 2082004 65204 ?       Ss   Oct06   0:01      \_ xe_cl02_XE
54321      13602  0.0  0.2 2082012 65156 ?       Ss   Oct06   0:01      \_ xe_cl03_XE
54321      13604  0.0  0.2 2082008 65024 ?       Ss   Oct06   0:01      \_ xe_cl04_XE
54321      34998  0.0  0.3 2083116 91584 ?       Ss   Oct06   0:01      \_ xe_w005_XE
54321      35021  0.0  0.4 2083316 118132 ?      Ss   Oct06   0:01      \_ xe_w006_XE
54321      35044  0.0  0.3 2083080 89976 ?       Ss   Oct06   0:01      \_ xe_w007_XE
54321      35109  0.0  0.4 2083108 109244 ?      Ss   Oct06   0:01      \_ xe_w008_XE
54321      35147  0.0  0.4 2083112 108248 ?      Ss   Oct06   0:01      \_ xe_w009_XE
54321      35182  0.0  0.4 2082084 108628 ?      Ss   Oct06   0:01      \_ xe_w00a_XE
54321      35246  0.0  0.4 2083112 108740 ?      Ss   Oct06   0:01      \_ xe_w00b_XE
54321      35269  0.0  0.3 2082056 90488 ?       Ss   Oct06   0:01      \_ xe_w00c_XE
54321      35292  0.0  0.3 2082060 89212 ?       Ss   Oct06   0:01      \_ xe_w00d_XE
54321      35315  0.0  0.3 2083080 92872 ?       Ss   Oct06   0:01      \_ xe_w00e_XE
54321      35380  0.0  0.3 2083080 89060 ?       Ss   Oct06   0:01      \_ xe_w00f_XE
54321      35401  0.0  0.3 2083348 97940 ?       Ss   Oct06   0:01      \_ xe_w00g_XE
54321      35424  0.0  0.3 2083084 92096 ?       Ss   Oct06   0:01      \_ xe_w00h_XE
54321      35488  0.0  0.3 2083084 88960 ?       Ss   Oct06   0:01      \_ xe_w00i_XE
54321      35512  0.0  0.4 2083104 108240 ?      Ss   Oct06   0:01      \_ xe_w00j_XE
54321      35535  0.0  0.4 2082084 107472 ?      Ss   Oct06   0:01      \_ xe_w00k_XE
54321      35598  0.0  0.4 2083104 108920 ?      Ss   Oct06   0:01      \_ xe_w00l_XE
54321      35621  0.0  0.3 2082056 92428 ?       Ss   Oct06   0:01      \_ xe_w00m_XE
54321      35696  0.0  0.3 2083080 90692 ?       Ss   Oct06   0:01      \_ xe_w00n_XE
54321      35719  0.0  0.4 2083104 106068 ?      Ss   Oct06   0:01      \_ xe_w00o_XE
54321      35784  0.0  0.3 2083084 90672 ?       Ss   Oct06   0:01      \_ xe_w00p_XE
54321      35807  0.0  0.3 2083080 90768 ?       Ss   Oct06   0:01      \_ xe_w00q_XE
54321      35830  0.0  0.4 2083108 107528 ?      Ss   Oct06   0:01      \_ xe_w00r_XE
54321      35895  0.0  0.4 2083108 106928 ?      Ss   Oct06   0:01      \_ xe_w00s_XE
54321      35918  0.0  0.4 2083108 108700 ?      Ss   Oct06   0:01      \_ xe_w00t_XE
54321      35949  0.0  0.4 2083104 107592 ?      Ss   Oct06   0:01      \_ xe_w00u_XE
54321      36014  0.0  0.3 2083084 89684 ?       Ss   Oct06   0:01      \_ xe_w00v_XE
54321      40900  0.0  1.1 2105580 294244 ?      Ss   Oct06   1:06      \_ xe_m005_XE
54321    1228339  8.9  0.4 2086228 106944 ?      Ss   18:27   0:06      \_ oracleXE (LOCAL=NO)
54321    1228388  9.0  0.4 2086232 106916 ?      Ss   18:27   0:06      \_ oracleXE (LOCAL=NO)
```

</details>


```
$ cat -p /opt/netdata/etc/netdata/apps_groups.conf
myOracle: '*/bin/bash /opt/oracle/runOracle.sh*'
```

<img width="1300" alt="Screenshot 2024-10-07 at 18 29 20" src="https://github.com/user-attachments/assets/feb2bff8-ba40-452a-bdc2-b0deb332f35a">

**Comment by xd003** [comment]
> Works for me.

Just to confirm, the `/opt/oracle/runOracle.sh` is executed on your host machine right ? Maybe this thing doesn't work for processes inside the docker container/processes started by a manager

Nvm I just ran a simple loop script on my host name try.sh, `apps_group.conf` entry being - `try: '*bash try.sh*'`
For some weird reason, this process has been categorized as the comm of its parent process

![image](https://github.com/user-attachments/assets/330f12ab-3144-451b-920b-8c487e9ce76c)

**Comment by ilyam8** [comment]
No, in the docker container.

**Comment by xd003** [comment]
It's seems like netdata is not reading my apps_groups.conf file or something. Maybe editing the mapped docker volume on host and force recreating netdata container is not the ideal way to go about this. Once i have docker exec into netdata container, is there a way to verify if Netdata has recognised and loaded my custom `apps_group.conf` ?

**Comment by ilyam8** [comment]
Yes, by checking logs.

- See [With host-editable configuration](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#with-host-editable-configuration).
- Ensure you don't use an old image.

**Comment by xd003** [comment]
> Yes, by checking logs.
> 
>     * See [With host-editable configuration](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#with-host-editable-configuration). This doesn't require recreating, just `docker restart`.
> 
>     * Ensure you don't use an old image.

I am already using bind mount in netdata container running the latest image - `netdata/netdata:edge`
I couldn't find anything on searching for apps_group.conf in the docker log of netdata. Not quite sure which else to search for having no idea what is it supposed to be

**Comment by ilyam8** [comment]
I don’t know either. Works for me. If you can provide exact step by step to reproduce the problem (so I can just copy paste) - I will give it a try.

**Comment by ilyam8** [comment]
And what we were discussing was unrelated to the op request. Consider using GH discussion or Didcord.
