### ISSUE TITLE
[Feat]: Get "squidlog" plugin logs from syslogs

### ISSUE THREAD

**Issue by JGoutin** [netdata/netdata#18752]
### Problem

Squid can output logs in syslogs (So also journald on systemd based OS), but the "squidlog" plugin only supports logs in files.

For instance, Squid can be configured using the following configuration : `access_log syslog:user.info` (Ref https://www.squid-cache.org/Doc/config/access_log/)

### Description

The "squidlog" may support getting logs directly from syslog or journald, and not only from a log file.

### Importance

really want

### Value proposition

If already using journald/syslog for Squid, we need to setup a log file as second log target in Squid for Netdata. Creating duplicated data, duplicated I/O, ...

**Comment by ilyam8** [comment]
Hi. There is no plan to add support reading logs from journal to squidlog.  There is no pure go library for it.
