### ISSUE TITLE
[Feat]: Capture per NUMA node memory information

### ISSUE THREAD

**Issue by johnzielke** [netdata/netdata#18818]
### Problem

AFAIK netdata currently only captures memory statistics, but does not show per-node memory usage info.
This leads to situations where a system shows memory pressure with a lot of free memory remaining (but on other nodes).

### Description

Capture the data under /sys/devices/system/node/node*/meminfo allowing to group by the node.

### Importance

really want

### Value proposition

1. Analyze the memory usage across NUMA nodes, allowing for better distribution of workloads
2. Debug memory pressure with a lot of total free memory remaining

**Comment by ilyam8** [comment]
Added in #18822
