### ISSUE TITLE
[Feat]: Using gpu id in nvidia-smi plugin .

### ISSUE THREAD

**Issue by HLSS-Hen** [netdata/netdata#18832]
### Problem

In the previous version, the nvidia-smi plugin using `python.d` collected data using `gpu_instance_id` instead of the `uuid`. Now, after switching to the `go.d` version, the use of `uuid `has resulted in reduced readability.

### Description

Using `gpu_instance_id` instead of `uuid`.

### Importance

really want

### Value proposition

Using `gpu_instance_id` instead of `uuid`.

**Comment by ilyam8** [comment]
Hi, @HLSS-Hen. I don't plan to change the id back.

**Comment by ilyam8** [comment]
> has resulted in reduced readability.

Readability where?

**Comment by HLSS-Hen** [comment]
![QQ20241021-170934](https://github.com/user-attachments/assets/12a47bb5-4773-4a01-919a-50233d77b22e)

Just like this, if I want to know the utilization of a certain GPU, I have to query the corresponding UUID.

Perhaps I can only set up a bunch of custom charts.

**Comment by ilyam8** [comment]
@HLSS-Hen 

- I added the "index" label. You will be able to group by index + product_name.

<img width="1489" alt="Screenshot 2024-10-21 at 14 06 35" src="https://github.com/user-attachments/assets/9daef4e8-94f1-4111-b3b3-1e31b44597f3">

- I added a table view

<img width="1280" alt="Screenshot 2024-10-21 at 14 06 21" src="https://github.com/user-attachments/assets/e3781fa3-4dd7-4301-af3a-b54cf0b9e3ec">
