### ISSUE TITLE
[Feat]: Way to change data retention on UNRAID Docker image?

### ISSUE THREAD

**Issue by jakabo27** [netdata/netdata#18840]
### Problem

There doesn't appear to be a persistent way to edit the data retention time for Netadata when running it as a docker container in UNRAID

### Description

It would be nice if this could be configured within Netdata itself, or as a parameter passed through when editing the container.  Just some way to change it from the default 256MB in a way that will persist across restarts.  

### Importance

nice to have

### Value proposition

1. Better UNRAID user experience and capabilities (longer logging)
2. UNRAID servers often have many TB of storage, so 256MB is nothing to them

### Proposed implementation

Docker tags editable within unraid, or configuration within Netdata

**Comment by ilyam8** [comment]
Hi. The default is not 256. You can change the retention in netdata.conf.

**Comment by jakabo27** [comment]
Hello, how do I edit netdata.conf when using Docker+Unraid though?  I only have been able to get through it via the container's console.  And I believe if I edit it that way then any time I install an update to the container it will get overwritten and go back to the default value.

**Comment by ilyam8** [comment]
I don't know about Unraid (never used it), but [volume mounting](https://docs.docker.com/engine/storage/volumes/) is used to preserve data across redeployments in Docker. Our [recommended way](https://learn.netdata.cloud/docs/netdata-agent/installation/docker#recommended-way) to install Netdata in Docker has 3 of them:
- `/etc/netdata`
- `/var/lib/netdata`
- `/var/cache/netdata`

These are the directories you want to persist.

>  how do I edit netdata.conf when using Docker+Unraid though

If you have access to the terminal you can use `docker -it exec netdata bash` to get a shell into the netdata container. Then you go to `/etc/netdata` and edit `netdata.conf`.
