### ISSUE TITLE
[HELP]: HOW TO INSTALL NETDATA ON WINDOWS

### ISSUE THREAD

**Issue by blue-eyed-g** [netdata/netdata#18844]
### Bug description

hi, i want to install natdata on windows10 or windows docker desktop. What should i do? I can't find the relevant installation package in the release. thanks!

### Expected behavior

1

### Steps to reproduce

1.
2.
3.
...1

### Installation method

docker

### System info

```shell
1
```

### Netdata build info

```shell
1
```

**Comment by ilyam8** [comment]
Hi, @blue-eyed-g. We will add documentation when Netdata Windows Agent becomes officially available.
