### ISSUE TITLE
[Feat]: 启用syncookies的时候，不应该报警tcp_accept_queue和tcp_syn_queue

### ISSUE THREAD

**Issue by 1265578519** [netdata/netdata#18867]
### Description

启用syncookies的时候，不应该报警tcp_accept_queue和tcp_syn_queue

### Importance

nice to have

### Value proposition

启用syncookies的时候，不应该报警tcp_accept_queue和tcp_syn_queue
设置syncookies值为1时，net.ipv4.tcp_max_syn_backlog将不会在有效，会始终发送syncookies

**Comment by ilyam8** [comment]
@1265578519 please use English.

**Comment by 1265578519** [comment]
@ilyam8 居然又是沙雕网友
