### ISSUE TITLE
[Feat]: Fedora 41 support

### ISSUE THREAD

**Issue by JGoutin** [netdata/netdata#18926]
### Description

Fedora 41 was released this week, but is not yet available on Netdata RPM repository.

### Importance

must have

### Value proposition

Support the latest version of Fedora, as the previous ones were supported.

### Proposed implementation

There is a merged PR about this here : https://github.com/netdata/netdata/pull/18753
The repository directory exists but is empty https://repo.netdata.cloud/repos/stable/fedora/41/x86_64/

**Comment by ilyam8** [comment]
@JGoutin stable version will be added after the next non-patch release.

**Comment by JGoutin** [comment]
@ilyam8 OK, thank you for the information.
