### ISSUE TITLE
[Bug]: Local Installation requires me to disable nodes

### ISSUE THREAD

**Issue by Pingger** [netdata/netdata#18978]
### Bug description

I am running a local netdata agent with, installed with the flags `--interactive --stable-channel --auto-update --disable-telemetry --reinstall --disable-cloud --build-only`. I have 6 Nodes with the same flags, that stream to that central node. 
My local dashboard is now forcing me to disable 2 of those nodes.

What happened to your promise, that self-hosted installations and the local dashboard will always be unlimited?!

### Expected behavior

no limit on local nodes

### Steps to reproduce

1. Install Netdata on a host with `--disable-cloud`
2. Install Netdata on a host with `--disable-cloud`
3. Install Netdata on a host with `--disable-cloud`
4. Install Netdata on a host with `--disable-cloud`
5. Install Netdata on a host with `--disable-cloud`
6. Install Netdata on a host with `--disable-cloud`
7. Install Netdata on a host with `--disable-cloud`
8. Setup 6 of those nodes to stream to a central node
9. access dashboard of that central node
10. be greeted with this screen:
![image](https://github.com/user-attachments/assets/e7cc7343-070b-495d-b5a9-ebab4b03b30e)

### Installation method

kickstart.sh

### System info

```shell
Linux iskariot.info 5.4.0-176-generic #196-Ubuntu SMP Fri Mar 22 16:46:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.6 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.6 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v2.0.0
    Installation Type __________________________________________ : binpkg-deb
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ : ubuntu 20.04
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 5.4.0-176-generic
    Operating System ___________________________________________ : Ubuntu
    Operating System ID ________________________________________ : ubuntu
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 20.04.6 LTS (Focal Fossa)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 8
    CPU Frequency ______________________________________________ : 1996000000
    RAM Bytes __________________________________________________ : 33659752448
    Disk Capacity ______________________________________________ : 858993459200
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : kvm
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine (compression) _____________________________________ : YES (zstd lz4)
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : NO
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
    libmnl (library for working with netfilter) ________________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : YES
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : YES
    Xen VBD Error Tracking _____________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : YES
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

### Additional info

It seems, that the updater has changed the installation method from kickstart-build to the package repository variant, which I explicitly don't want! (as that would explain, why I recently had issues with some collectors stopping to work!)

This after it was suggested, that going from nightly to stable would save me from issues like this in the future. The future is now, the issues got more severe.

**Comment by Pingger** [comment]
Apparently I am lucky, that my netdata.conf survived, based on the new `netdata.conf.dpkg-dist` file in `/etc/netdata`

**Comment by ilyam8** [comment]
Hi @Pingger, this is expected since 2.0.0 and was announced way in advance. cc @shyamvalsan

**Comment by Pingger** [comment]
I see:
- changing local build to package repositories, thus breaking collectors was expected
- removing collectors was expected
- reneging on the "local will always be free" terms also expected.

Well @ilyam8 ... it seems I will have to look for a new monitoring solution then.

But more likely just stop monitoring my NAS using an ok solution at all (and go back to "crond-monitoring").

Since I can't trust your promises, that does include the previously paid one we have rolled out in our company. Our previous solution there is cheaper, as they have not yet pulled a Darth Vader "I have altered the deal! Pray I don't alter it further!"

I have also now checked the announcements I received over the last few months, specifically the release notes for:
1.45.4 - 2024-05-08
1.45.5 - 2024-05-21
1.45.6 - 2024-06-05
1.46.0 - 2024-06-19
1.46.1 - 2024-06-21
1.46.2 - 2024-07-10
1.46.3 - 2024-07-23
1.47.0 - 2024-08-22
1.47.1 - 2024-09-10
1.47.2 - 2024-09-24
1.47.3 - 2024-10-02
1.47.4 - 2024-10-09
1.47.5 - 2024-10-24
2.0.0 - 2024-11-07

**__NONE OF THESE MENTION ANYTHING OF THE SORT__** So pray tell, WHERE WAS THIS ANNOUNCED?!

**Comment by Pingger** [comment]
And just to reiterate: No cloud! Fully local, no login! Reproducible without even connecting to the internet.

**Comment by ralphm** [comment]
Hi @Pingger,

You mention several issues, and I will address them below.

### Self-hosted installations and local dashboard

We [announced](https://www.netdata.cloud/blog/important-changes-to-the-netdata-agent-dashboard/) back in August that we would align the local Agent dashboard to the Community Plan in Cloud. This is also referenced in the release notes of 1.47.0, in the section titled [Upcoming changes for Netdata v2.0](https://github.com/netdata/netdata/releases/tag/v1.47.0#user-content-v1470-v2):

> Without logging into Netdata Cloud, the new v3 UI will continue to be usable as a fallback, with reduced functionality, similar to v2 and aligned with our Community Plan.

In practice this means that you can continue to use the local dashboard on each of your Agents, showing all the data for the local node as always. The dashboard on **parent** Agents will be limited to viewing the 5 selected nodes (as well as the local node if that one is not selected).

We understand that it may be disappointing that the UI is now constrained for Parent-Child setups. Our continued development of Netdata, however, requires that the company receives revenue for its use in commercial (like) setups, including multi-node dashboards. For homelab use, we have provided the Homelab plan for a modest fee that lifts that limit. You *do not* have to actually claim your nodes to Cloud for this to work. You will be required to log into Cloud as a user of the UI. All the subsequent requests will continue to go to your own machines directly.

We did make the `--disable-cloud` flag a no-op. This means that all builds have the code to use Cloud, but it does not mean that it will automatically claim Agents.

### Netdata in Containers on the same host
 
You mention that you are running 4 Agents in containers on the same machine. Can you expand on this setup? Are you using Netdata as a side car?

We generally recommend running one Agent per host, in an isolation strategy that allows it access to the host's resources. For Kubernetes setups specifically that means that our Helm chart sets up the Agent to run in a DeamonSet.

### Change in installation method through the upgrader

This sounds like a bug. If you install Netdata with the command line from the initial summary including `--build-only`, can you share the contents of `/etc/netdata/.install-type`?

### Disappearing collectors

Are you saying that `/etc/netdata/netdata.conf` got overwritten by the automatic update? This should never happen with apt. Both the kickstart and updater scripts [specify](https://github.com/netdata/netdata/blob/3a1cfc49e5d0d8b47838629f61e7a7dcba784182/packaging/installer/netdata-updater.sh#L927) `--force-confdef` and `--force-confold` to prevent this when running non-iteractively. Do you have `--force-confnew` anywhere in your `/etc/apt/`?


I hope the above helps. If you have additional questions, please let us know.

**Comment by Pingger** [comment]
Retroactively editing an announcement and adding significant features without notifying users about that change does not constitute "prior notice", as has previously been ruled in several courts in many countries. For your reference I have attached the announcement as I have received it 
[[netdata_netdata] Release v1.47.0 - v1.47.0 - Netdata bot <notifications@github.com> - 2024-08-22 1724.eml.txt](https://github.com/user-attachments/files/17704525/netdata_netdata.Release.v1.47.0.-.v1.47.0.-.Netdata.bot.notifications%40github.com.-.2024-08-22.1724.eml.txt)

# Containers on the same Host
The host is running netdata.
The host is running about 20 containers.
1 Container is a netdata backup container. The host streams to the backup container, the backup container to the host (as I have previously lost, at times, several weeks of data on restarts)
1 Container is a mail server that, for security reasons, is running a seperate netdata instance that can access some specific data, that are not easily available from the host without breaching security
1 Container is running game servers in sub-containers. I don't trust most game servers, so seperate netdata
1 Container is a specialized web-monitor, that holds only a very limited amount of metrics, but those metrics are supposed to have a much longer history (multiple years with second granularity), than other metrics, so that netdata instance has its own storage.

All those instances stream to the publicly accessible host port.

# Change in installation method
Will check as soon as I can.

# Disappearing collectors
I have written a few collectors in /usr/libexec/netdata for specific use cases (e.g. a last modified monitor for remote `borg` instances, and storage monitoring of an `rclone` mount).
Those collectors were just plain deleted from that directory. From snapshots and backups it seems, that the unannounced change from build-only to package distribution has deleted and recreated that folder.

**Comment by ralphm** [comment]
> Retroactively editing an announcement and adding significant features without notifying users about that change does not constitute "prior notice", as has previously been ruled in several courts in many countries. For your reference I have attached the announcement as I have received it [[netdata_netdata] Release v1.47.0 - v1.47.0 - Netdata bot ](https://github.com/user-attachments/files/17704525/netdata_netdata.Release.v1.47.0.-.v1.47.0.-.Netdata.bot.notifications%40github.com.-.2024-08-22.1724.eml.txt)[notifications@github.com](mailto:notifications@github.com) - 2024-08-22 1724.eml.txt

We did not retroactively change the announcement as you suggest. The quote above is present verbatim in the file you uploaded.

Thank you for adding more context about your setup. It seems that you can view this described infrastructure by selecting the nodes that run in containers and not the host node, even with the Community Plan. I'll check with the team if they have any suggestions for the issues you found, but having the requested information about the install method and the overwritten config files would surely help.

**Comment by Pingger** [comment]
It appears that I am blind, sorry for that. I still fail to see any mention of the node limit for non-cloud / cloud-disabled setups. The closest I can see is this:

> Without logging into Netdata Cloud, the new v3 UI will continue to be usable as a fallback, with reduced functionality, similar to v2 and **aligned with our Community Plan**.

Something that, imho, does not even remotely adequately address the node limit. So I am asking again: **Were was the sudden local node limit announced?!**

## Containers on same host
Forgot to mention: I also have portable devices of my family members set up to stream their data to my publicly accessible netdata parent. Made family telephone tech-support easier, until I made said notebooks open a reverse ssh-tunnel for me.

## Change in installation method
Backup-State just before collectors disappeared:
```
INSTALL_TYPE='kickstart-build'
```

Current State:
`.install-type`
```
INSTALL_TYPE='binpkg-deb'
PREBUILT_ARCH='x86_64'
PREBUILT_DISTRO='ubuntu 20.04'
```
`.install-type.dpkg-old`
```
INSTALL_TYPE='kickstart-build'
```



Current State on one of my nodes (Manjaro), that gave me a WTF moment:
```
INSTALL_TYPE='custom'
```

## Disappearing collectors
Affected collectors were all in `/usr/libexec/netdata/python.d/`:
- minecraft.chart.py -> reset to distribution default (I changed some regex, because of custom MC server)
- ts3.chart.py -> reset to distribution default (Was experimenting with allowing more stats, like traffic stats and channel usage, intended to open a PR for that, once I got it to a state I wanted it in)
- borg.chart.py -> deleted entirely (as explained custom project for monitoring borgbackup repos)
- rclone.chart.py -> deleted entirely (as explained custom project for monitoring space usage of rclone mount, since rclone-fuse3 mount shows 2 PiB as capacity which is wrong and an rclone bug)

To be clear: The configs in `/etc/netdata/python.d` are still were they are supposed to be. The `netdata.conf` also was left untouched and a new `netdata.conf.dpkg-dist` appeared alongside it. On the other hand, `edit-config` was renamed to `edit-config.dpkg-old` and then replaced with the distribution version. No changes were made to it.
Current state of `/etc/netdata`. Distribution package behaved correctly.
![image](https://github.com/user-attachments/assets/22cb6950-9cdb-4c8f-8b97-1ee598d94598)

Current state of `/usr/libexec/netdata/python.d`. Distribution package wiped it out and reset everything. Also interesting permission inconsistencies...
![image](https://github.com/user-attachments/assets/19c219cc-2174-485e-98af-fffdd359f13b)

**Comment by ralphm** [comment]
> It appears that I am blind, sorry for that. I still fail to see any mention of the node limit for non-cloud / cloud-disabled setups. The closest I can see is this:
> 
> > Without logging into Netdata Cloud, the new v3 UI will continue to be usable as a fallback, with reduced functionality, similar to v2 and **aligned with our Community Plan**.
> 
> Something that, imho, does not even remotely adequately address the node limit. So I am asking again: **Where was the sudden local node limit announced?!**

That highlighted part exactly pertains to the node limit, as this plan has had a node limit [since](https://www.netdata.cloud/blog/netdata-plan-changes/) November 2023. We also published a [blog post](https://www.netdata.cloud/blog/important-changes-to-the-netdata-agent-dashboard/) (linked above as well) that explicitly calls out the node limit for v2, three months ahead of the stable release. The nighties (`1.99.0-nightly`) have included this since for a while prior.

As for your plugin install issues, I'll work with our Agent team to look into this, particularly for those custom Python modules that are not shipped by us. For those that do, though, it is entirely expected that they'd be overridden by updates as they are just part of the package.

**Comment by Pingger** [comment]
@ralphm 
Thank you for looking into the other issues I experienced and also thank you for expla

While I still think that local node limit could have been communicated (much) better, I still am quite miffed about netdata walking back on their promise anf commitment for self hosted installations.
"Monitor everything in real time. For free." - Netdata 2021

Netdata 2022:
![image](https://github.com/user-attachments/assets/2d380d06-2282-451d-bf9c-2199596fb651)

Especially notice this paragraph:

> Both our [open source Agent](https://www.netdata.cloud/agent/) and [Cloud SaaS solution](https://www.netdata.cloud/cloud/) provide unlimited monitoring—no restrictions as to number of nodes, users, notifications, anything—with no strings attached. At Netdata, we believe monitoring should be both feature-rich and free to everyone.

"no restrictions as to number of nodes"

I also like that archived page, because it informs me, that I don't need an account or use the cloud for that feature-set ...

So in the end I still feel extremely betrayed, after recommending the product to quite a lot of people and the company I work in. Decisions like this are what disqualified other solutions for me and many others I have talked with. Seeing netdata go down that road is extremely disappointing to me personally, as I also have invested quite a lot of time to tailor it to my and my companies requirements.  
I will probably look back at the project in the future, but I don't believe that I will continue the projects of the collectors I have been working on, and thus also no longer update the repositories on my gitea with said collectors.  
It pains me to end most of my relationship with netdata, but I can't condone this behaviour.

I do wish you (the entire Netdata Team) the best and hope you find the integrity I liked so much about you.

For now 
Farewell

**Comment by constantinenikitiadis** [comment]
Hi @vaunus , I am with Netdata.
We treat micro nodes such as IoT devices or even very small VMs differently. If you are interested, please fill out this form and we will get in touch as soon as possible [](https://www.netdata.cloud/contact-us/)

**Comment by Pingger** [comment]
Nothing really useful. I have dusted off my old custom monitoring. Works, but doesn't have fancy graphs. But those were always just a plus.
I also have migrated my web monitoring node to uptime kuma, which accidentally also solved the game server monitoring. The last thing is logging using just plain old syslog. 
The result is surprisingly helpful. I get more concise monitoring data, where I need it with graphs (uptime kuma and "excel" sheets), whilr actually taking far less time in maintenance. Netdata always had the issue, that there were those small things that didn't work properly or randomly stopped working, it also often was a bit trigger happy for some default alerts. Now with my alternatives, while they aren't a singular solution, I have yet to receive a "trigger happy" warning and maintenance also went down a lot.
I basically traded "ease of setup, annoying maintenance" (netdata) with "annoying setup, ease of maintenance".

I'm actually quite happy with netdata having forced me to get rid of it.

**Comment by vaunus** [comment]
> [@vaunus](https://github.com/vaunus) I am in a similar boat with you and [@Pingger](https://github.com/Pingger) and likewise very disappointed by the rug-pull on _"Free, Unlimited Monitoring Forever"._ I was utilizing a completely-local Netdata install, and it is now crippled by the enforcement of "pick 5 nodes" even on a local dashboard.
> 
> Do you have any alternative monitoring solutions in mind?
> 
> In the meantime, does anybody know if it's possible to downgrade (and pin) the Netdata parent node to a release _without_ the restriction? (The fact that this happened via auto-update is especially irritating.)

Am considering a Prometheus + Grafana type of setup but really have not had time to progress that whatsoever or research further.

**Comment by ralphm** [comment]
Thank you everyone for your perspectives.  We have explained here and in other places why we made these changes and understand that you may not agree. However, I also think that it is not reasonable to expect us to host discussions on circumvention or alternative solutions. I hope you understand.
