### ISSUE TITLE
[Bug]: Memory leak by Netdata agent

### ISSUE THREAD

**Issue by Iliya5digital** [netdata/netdata#18984]
### Bug description

I have a memory problem related to your agent. After installing the agent, the memory consumption was 5.9 MB, then 105 MB then 107.7 MB and now memory use 109.4 MB.

### Expected behavior

netdata agent should not consume so much memory in RAM and should use at least 5 MB no more. 5 MB for agent is the limit of memory usage

### Steps to reproduce

1. Install Netdata via MSI
2. Activate Netdata
3. Open Task Manager (Windows Only)
4. Find background task named as "netdata"
5. Watch the netdata process during the day and you should find that the netdata process memory increases over time

### Installation method

other

### System info

```shell
Microsoft Windows [Version 10.0.22631.4317]
```

### Netdata build info

```shell
2.0.0.0
```

**Comment by ilyam8** [comment]
Hi. This is expected. Netdata can’t use only 5 mb. Memory usage will stabilize (stop grow).

**Comment by Khang-NT** [comment]
@ilyam8 Is it normal when the memory consumption of netdata agent + go.d plugin > 200MB (100MB each)? I just installed Netdata (v2.0.0) a few days ago, and all the configurations were untouched.

**Comment by ilyam8** [comment]
Yes it is normal and depends on your setup (Parents use more memory)/the number of collected metrics.
