### ISSUE TITLE
[Feat]: disable Netdata cloud sign-in splash

### ISSUE THREAD

**Issue by kylrth** [netdata/netdata#19007]
### Problem

After upgrading to v2.0.0, the dashboard now displays an unhelpful splash page:

![splash page](https://github.com/user-attachments/assets/b73957e9-204c-41fe-8e09-a9211dcd1cea)

This splash page allows you to "skip" sign-in and use the dashboard "anonymously", but this option is provided using a [dark pattern](https://en.wikipedia.org/wiki/Dark_pattern) and must be clicked every time I navigate to the dashboard.

### Description

I understand that you want to get people to use the cloud, but there needs to be a way to disable what basically amounts to a full-page ad for your cloud service.

### Importance

must have

### Value proposition

I know there is a history (https://github.com/netdata/dashboard/issues/429, #5881, #9362, #12654, [community discussion 1](https://community.netdata.cloud/t/disable-cloud-nags/2985), [community discussion 2](https://community.netdata.cloud/t/netdata-container-and-disabling-cloud-connectivity/624)) of privacy-conscious, local-only Netdata users having to continually find out how to disable various new cloud features and prompts as they are added. I've struggled to find them all myself. I think it's reasonable to use the community edition to push your related products, but this splash is simply too annoying.

### Proposed implementation

I need to be able to disable this in the agent, using a config or environment variable, not as a build option.

**Comment by ilyam8** [comment]
Hi, @kylrth. This is expected. If you want to skip the splash screen, you have a few options:

 - sign-in
 - use `/v3` endpoint

**Comment by kylrth** [comment]
Thanks for the information. I'll have my reverse proxy redirect from the homepage to `/v3`.

**Comment by rdbisme** [comment]
Thanks! Let me also preach against this dark pattern. I understand the business side of this, but this really doesn't make me happy :). 

No problem in advertising your cloud offering, but please don't hide so much the way to skip that for people which are not interested. I'm not entirely convinced that forcing the cloud service down to my throat will make me give up and sign in. Possibly the contrary.

I'm a huge fan of your product, so... just saying :)

**Comment by ilyam8** [comment]
I don't like it either, but it's not my decision 🤷‍♂️

**Comment by balajeek** [comment]
Me too don't like it, I run it on a screen side by just for dashboard like this, and I had to click skip every time.
Also what I noticed, even with self hosting it seem my internet is down the other day and I couldn't access net data ! is that true ?

**Comment by DocMAX** [comment]
so, what's the solution??

**Comment by rdbisme** [comment]
@DocMAX the solution is to go to this url: http://<your_host>:19999/v3 should automatically redirect to the dashboard after a slow show of the splash page.

**Comment by rdbisme** [comment]
I just installed the windows version: 
![image](https://github.com/user-attachments/assets/d3d78c80-9c15-42a7-9fbb-64269019aae0)


It says it's not allowed to see the dashboard anonymously?! 

This is not true, If I redirect to localhost:19999/v3 I can still see it.
