### ISSUE TITLE
Enhancement: Request for host tagging at the registry and my-netdata menu

### ISSUE THREAD

**Issue by samof76** [netdata/netdata#1900]
For consolidation, of monitoring it would be a nice feature if the a node/instances can be identified, by multiple tags, so we could refine out custom dashboard if any based on the those tags. This is in a important feature, if you are running 100s of instances where you could bucket the instances by type, stack, layer etc.

**Comment by ktsaou** [comment]
ok, let's assume we could tag them. How would like to use this feature? I mean is this some functionality you expect at the my-netdata menu? At another window/tab/page where you could search for hosts?

A user story would be awesome for this...

**Comment by samof76** [comment]
> I still cannot narrow down to 1 function the "group of nodes". I have understood you need to tag/group them somehow, but I still cannot figure out how you expect to use this information. I mean, you have a UI in mind that does something with them. Could you please describe in #1900

Yes, this from the perspective of easy grouping on instances based on their character. And yes I am trying build an UI, that would use grouping as central them so if i chose a group/tag and select a metric it would list all graphs for instances in that group/tag.

**Comment by ktsaou** [comment]
So, you imagize a search box (possibly in `my-netdata` menu) where hosts are filtered based on tag?

**Comment by samof76** [comment]
> ok, let's assume we could tag them. How would like to use this feature? I mean is this some functionality you expect at the my-netdata menu? At another window/tab/page where you could search for hosts?


How would like to use this feature?

Say, now that I have grouped my instances or nodes that are running netdata with tags. For example, I am rails shop, with multiple layers in my stack, haproxy servers(tag: lb), rails app servers(tag: rails), memcached servers(tag: memcached), redis servers(tag: redis), sidekiq servers(tag: sidekiq). Now, If i have to see the metrics of all instance under one layer, how would i do that? But if you have tags, we would be able get all instances(one or more metrics) in that layer, on a single page. Even better if we can overlay them.

I mean is this some functionality you expect at the my-netdata menu?

What I had in mind a provision in the API to give the list of instances or nodes for a paticular tag. But having it on my-netdata menu would  be great as well. But to answer your next question here, another window too would be a good option, spefically for viewing groups or consolidated graphs.

**Comment by ktsaou** [comment]
ok, I see. So:

1. We should provide a method to add/edit multiple tags to nodes. Will these be "per user" or "per system"? If they are "per user", the tags should be web editable and saved at the registry. If they are "per system" they should be configured in `netdata.conf`.

2. Then we could have either at the `my-netdata` menu or another page, a search box where systems can be filtered based on name or tags.

**Comment by gamefundas** [comment]
Essentially it would be nice to see the netdata slaves appear in logical groups in the my-nedata menu. Currently its a long list of host-names. To begin with if there is a property, "group-name" that I can specify in the slave netdata.conf then the master can use that to at least create a menu-group. This will be one step towards achieving a single tag feature.

**Comment by samof76** [comment]
> We should provide a method to add/edit multiple tags to nodes. Will these be "per user" or "per system"? If they are "per user", the tags should be web editable and saved at the registry. If they are "per system" they should be configured in netdata.conf.

I would ideally think the tags should be published from the nodes that way, it is better for automation's sake. Whether that should editable, may while we reconfigure netdata on the servers, but not manually on the dashboard. But from user level, groupings can be different level of categorization and not the same as tags.

> Then we could have either at the my-netdata menu or another page, a search box where systems can be filtered based on name or tags.

A search box could be nice and remove clutter from the my-netdata menu.

**Comment by ktsaou** [comment]
ok, server side then.

I have 2 questions though.

1. One or many tags per node?
2. I guess you don't need tags just for the services running. This could easily be discoverable without tags. You need tags to group the hosts in farms because they have something in common (i.e. "service A" or "service B"), other than the metrics collected (i.e. we could query the servers to find the ones running mysql, so having a tag "mysql" is not that useful). Right?

**Comment by gamefundas** [comment]
In our case we need the ability to group our multi-node clusters, 
Kafka - 
   -> Server 1
   -> Server 2
   -> Server 3
   -> Server 4
   -> Server 5
Zookeeper
   -> Server 1
   -> Server 2
   -> Server 3
Elasticsearch
   -> Server 1
   -> Server 2
   -> Server 3
Database
   -> Postgres DB
   -> MySQL
Application A (Standalone)
Application B (Standalone)
Data Service
   -> Server 1
   -> Server 2
   -> Server 3

and so on....

Essentially the clustered ones require some sort of logically grouping, while standalone's don't.

**Comment by samof76** [comment]
>  One or many tags per node?

Many tags, it could like ...

    "tags": {"name": "webserver1", "stack": "production", "layer": "web", "region": "us"}

>    I guess you don't need tags just for the services running. This could easily be discoverable without tags. You need tags to group the hosts in farms because they have something in common (i.e. "service A" or "service B"), other than the metrics collected (i.e. we could query the servers to find the ones running mysql, so having a tag "mysql" is not that useful). Right?

But how else would you know its mysql if your are running hybrid environment running both mysql and postgresql?

**Comment by sarlalian** [comment]
If this makes it in, it would be amazing if metrics coming  out of the opentsdb / prometheus endpoints could contain those tags as well.  It would make it easier to create host dashboards in those ecosystems as well.

**Comment by ktsaou** [comment]
hm... this is probably already implemented:

```
[backend]
	host tags = 
```

They are propagated with metrics streaming from netdata to netdata. They work with opentsdb (I don't know how to set host tags on prometheus).

This request is to make them work on the netdata registry too.

**Comment by sarlalian** [comment]
Excellent, thank you!

**Comment by springerst94** [comment]
It would be helpful if the ability to add tags to users and cgroups existed - than using opentsdb or influxdb - grafana could use variables to select containers and pods or kubes of interest instead of having to graph all that exist.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
