### ISSUE TITLE
Improve how splash screen presents information (especially related to retention)

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#19051]
### Problem

Agent splash screen is the first thing new users see after installing Netdata - and it is very important all of the information is meaningful and presented in an intuitive and easy to understand way. Currently this is not true.

### Description

This is how the splash screen currently shows info

<img width="815" alt="Screenshot 2024-11-20 at 22 30 16" src="https://github.com/user-attachments/assets/a1bfc093-c72e-4dfa-808d-f538228ab14c">

- New users will not know what Tier 0, Tier 1, Tier 2 means 
- Metrics and samples are somewhat self explanatory but "Disk size" and  "Used" might have a different connotation for them, and on fresh installs this will always say zero used.
- Expecting users to go read our docs and understand what all of this means is not ideal as a user journey.

### Importance

must have

### Value proposition

1. Make Netdata easier to use and understand for new users.

### Proposed implementation

To present data retention let us just have "Data retention" as the heading + a tabular view. See example [suggested](https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1728896287107779) by @ilyam8  below

![image](https://github.com/user-attachments/assets/125ea8a0-a0a7-41c1-ae28-ca85a127ec6a)

Additionally, Metrics, Samples and current oldest sample could be additional fields in the table.

**Comment by ilyam8** [comment]
@shyamvalsan The "Saving Data" table was not a suggestion on how to present it, but a clear example that a tabular view is much easier to read. I will post my suggestion tomorrow.

**Comment by ilyam8** [comment]
@shyamvalsan here you go

<table class="w-full border-collapse">
  <thead>
    <tr>
      <th class="p-2 border" rowspan="2">Tier</th>
      <th class="p-2 border" rowspan="2">Resolution</th>
      <th class="p-2 border" rowspan="2">Metrics</th>
      <th class="p-2 border" rowspan="2">Samples</th>
      <th class="p-2 border text-center" colspan="3">Retention</th>
      <th class="p-2 border text-center" colspan="2">Disk</th>
    </tr>
    <tr>
      <th class="p-2 border">Current</th>
      <th class="p-2 border">Expected</th>
      <th class="p-2 border">Configured</th>
      <th class="p-2 border">Used</th>
      <th class="p-2 border">Configured</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="p-2 border">0</td>
      <td class="p-2 border">1s</td>
      <td class="p-2 border text-right">11,713</td>
      <td class="p-2 border text-right">2.4B</td>
      <td class="p-2 border text-right">5d</td>
      <td class="p-2 border text-right">6d</td>
      <td class="p-2 border text-right">14d</td>
      <td class="p-2 border text-right">1 GB (100%)</td>
      <td class="p-2 border text-right">1 GB</td>
    </tr>
    <tr>
      <td class="p-2 border">1</td>
      <td class="p-2 border">1m</td>
      <td class="p-2 border text-right">9,554</td>
      <td class="p-2 border text-right">65.7M</td>
      <td class="p-2 border text-right">9d</td>
      <td class="p-2 border text-right">30d</td>
      <td class="p-2 border text-right">90d</td>
      <td class="p-2 border text-right">303 MB (30%)</td>
      <td class="p-2 border text-right">1 GB</td>
    </tr>
    <tr>
      <td class="p-2 border">2</td>
      <td class="p-2 border">1h</td>
      <td class="p-2 border text-right">8,139</td>
      <td class="p-2 border text-right">923K</td>
      <td class="p-2 border text-right">9d</td>
      <td class="p-2 border text-right">254d</td>
      <td class="p-2 border text-right">730d</td>
      <td class="p-2 border text-right">36 MB (4%)</td>
      <td class="p-2 border text-right">1 GB</td>
    </tr>
  </tbody>
</table>

**Comment by shyamvalsan** [comment]
Looks good @ilyam8 

@kapantzak can you use this to update the splash screen?

**Comment by ilyam8** [comment]
@kapantzak We need to implement scaling for metrics and samples.

We show them like this now:
<img width="371" alt="Screenshot 2024-11-21 at 23 09 10" src="https://github.com/user-attachments/assets/542dc21a-f939-43ca-8e78-3ef7aeddd0e4">

If we need exact values, it should be in a tooltip.
