### ISSUE TITLE
MySQLService (or DatabaseService) for python.d

### ISSUE THREAD

**Issue by skwerlman** [netdata/netdata#1906]
I am currently looking at writing a chart which displays some stats about a [Cockatrice](https://github.com/Cockatrice/Cockatrice/) server. To do this, I need to get some info from a MySQL database, but there does not seem to be a simple way to accomplish this.

From what I read in the docs, it looks like I'd need to create a SimpleService, tell it how to find and connect to the database, grab the info I want, and then turn it into data which is usable by netdata.

It'd be nice if there was a MySQLService (or a generic DatabaseService) which would handle finding and connecting to the database for me.

**Comment by ktsaou** [comment]
It should be very easy.
Have you checked the [mysql module](https://github.com/firehol/netdata/blob/master/python.d/mysql.chart.py)? This more complicated because it renders a lot of charts, but the idea should be pretty simple.

cc: @l2isbad

**Comment by ktsaou** [comment]
As I see it, a lot of folks may need "a simple mysql" plugin. So, providing a MySQLService may make sense. @l2isbad your call...

**Comment by l2isbad** [comment]
got it 😄

**Comment by l2isbad** [comment]
Ok, i made the initial version

**How it works:**

- User have to specified all custom queries in dict format

ex.:
```python
 self.queries = dict(guys='select * from newdatabase.users',
                     turtles='select * from newdatabase.users2')
```

- That is all!

_get_raw_data() returns data in dict format
```python
{name: query result, name2: query result2, ...}
```

**_get_raw_data() current implementation**

```python
    def _get_raw_data(self, description=None):
        """
        Get raw data from MySQL server
        :return: list (fetchall() result) or (fetchall(), description)
        """

        if not self.connection:
           self.connection, error = self._connect()
           if error:
                return None

        raw_data = dict()
        try:
            with self.connection as cursor:
                for name, query in self.queries.items():
                    try:
                        cursor.execute(query)
                    except MySQLdb.ProgrammingError as error:
                        self.error('Removed query: %s[%s]. Error: %s'
                                   % (name, query, error))
                        self.queries.pop(name)
                        continue
                    if description:
                        raw_data[name] = (cursor.description, cursor.fetchall())
                    else:
                        raw_data[name] = cursor.fetchall()
            self.connection.commit()
        except (MySQLdb.MySQLError, TypeError):
           self.connection.close()
           self.connection = None
           return None
        else:
           return raw_data or None

```

**Custom MySQLService plugin example:**

```python
class Service(MySQLService):
    def __init__(self, configuration=None, name=None):
        MySQLService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.configuration['user'] = 'root'
        self.configuration['pass'] = '321'
        self.queries = dict(guys='select * from newdatabase.users',
                            turtles='select * from newdatabase.users2')

    def _get_data(self):
        """
        Format data received from shell command
        :return: dict
        """
        data = self._get_raw_data()
        if not data:
            return None
        else:
            to_netdata = dict()
            if 'guys' in data:  # always check this! _get_raw_data will remove query if query fails (ex - table has been deleted)
                to_netdata.update(dict([(y, z) for x, y, z in data['guys']]))
            if 'turtles' in data: # always check this! _get_raw_data will remove query if query fails
                to_netdata.update(dict([(y, z) for x, y, z in data['turtles']]))

            return to_netdata or None
```

![screenshot_20170309_002835](https://cloud.githubusercontent.com/assets/22274335/23710239/5f2917aa-045f-11e7-833e-ec268ccdf5ef.png)

Am i missing something?

**Comment by skwerlman** [comment]
That is exactly the sort of simple API I was hoping for, thank you! For my use case at least, I can't think of anything else I'd need from it.

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/pull/1916

**Comment by l2isbad** [comment]
@skwerlman 
You can test your custom mysql plugin using my PR.

[ _get_raw_data()](https://github.com/l2isbad/netdata/blob/MySQLService_class/python.d/python_modules/base.py#L1060). If you need not only `cursor.fetchall()` but `cursor.description` call _get_raw_data(description=True).

New [mysql_plugin](https://github.com/l2isbad/netdata/blob/MySQLService_class/python.d/mysql.chart.py#L404-L438)

If i need to add something or you have any question just ask

**Comment by l2isbad** [comment]
Queries can be defined in the module configuration file.

```yaml
test1:
  name     : 'Users'
  user     : 'root'
  pass     : '321'
  queries  :
      query1: 'select ....'
      query2: 'select ....'

test2:
  name     : 'Users2'
  user     : 'root'
  pass     : '321'
  queries  :
      query1: 'select ....'
      query2: 'select ....'
```

**Comment by l2isbad** [comment]
Actually if custom query returns `name: value`  we can add `mysql_custom.chart.py` or upgrade `mysql.chart.py `  to create charts automatically based on values. 
Queries in the configuration file - boom! Charts are created! (we can check number of dimension and if number > 20 module will fail (check can be disabled in the config))

@ktsaou @skwerlman  ?

**Comment by ktsaou** [comment]
I like it! I don't know if we should also provide a method for custom charts out of many queries.

**Comment by l2isbad** [comment]
> I don't know if we should also provide a method for custom charts out of many queries.

What do you mean? 

@skwerlman can you provide us an example queries/output you want to use?

**Comment by ktsaou** [comment]
> What do you mean?

Well, I understand people may need the cherry picks metrics from many queries to build the dimensions of a single chart. I am not an expert though, so whatever you believe guys...

**Comment by l2isbad** [comment]
> may need the cherry picks metrics from many queries to build the dimensions of a single chart

yeah, you are right.

**Comment by l2isbad** [comment]
MySQLService is ready but i want some feedback from the one who requested it before merge. Is it what he wants or any other functionality has to be added.

**Comment by skwerlman** [comment]
Hi, sorry for late reply; I'm writing the plugin today, and will report back with how it goes.

The query I'm using for this:
```SQL
SELECT * FROM cockatrice_uptime ORDER BY timest DESC LIMIT 1;
```
where a result looks like
```
+-----------+---------------------+--------+-------------+-------------+----------+----------+
| id_server | timest              | uptime | users_count | games_count | rx_bytes | tx_bytes |
+-----------+---------------------+--------+-------------+-------------+----------+----------+
|         1 | 2017-03-10 16:26:33 | 250425 |           2 |           1 |      680 |     2199 |
+-----------+---------------------+--------+-------------+-------------+----------+----------+
```

**Comment by l2isbad** [comment]
[Additional connection properties](https://github.com/l2isbad/netdata/blob/MySQLService_class/python.d/python_modules/base.py#L976-L977)

So if you need to change cursor class.

```python
from MySQLdb.cursors import DictCursror
.
.
def __init__(..
    self.extra_conn_properties = dict(cursorclass=DictCursor)
```

**Comment by l2isbad** [comment]
implemented
