### ISSUE TITLE
[Feat]: Add monitoring of /var/run/reboot-required

### ISSUE THREAD

**Issue by fayak** [netdata/netdata#19106]
### Problem

OSes create a file in `/var/run/reboot-required` whenever a reboot is required, for example after an update of the kernel, to notify users that a reboot is needed to fully apply updates. I believe it'd a good idea to have the existence of this file monitored by netdata to provide some sort of a boolean value

### Description

Add a plugin or a feature to an existing plugin to monitor the existence of `/var/run/reboot-required`

### Importance

really want

### Value proposition

1. know if a machine needs a reboot from its metrics, without having to login
2. This file might be created automatically after an upgrade by unattended-upgrades for example, so it's nice to be warned when it's needed when it's not directly after an ops intervention 
...

**Comment by ilyam8** [comment]
> Add a plugin or a feature to an existing plugin to monitor the existence of /var/run/reboot-required


Hey, @fayak. You can check this file using [Filecheck](https://learn.netdata.cloud/docs/collecting-metrics/other/files-and-directories).

**Comment by fayak** [comment]
That's actually neat ! I don't know if it make sense to change its default configuration to include the monitoring of this file for everyone, probably not, but it easily solves my issue at least. Cheers @ilyam8 :)

**Comment by ilyam8** [comment]
@fayak added collector + alert in #19109

**Comment by fayak** [comment]
Awesome !
