### ISSUE TITLE
Move ebpf code out of libnetdata.

### ISSUE THREAD

**Issue by vkalintiris** [netdata/netdata#19119]
AFAICT, the code under [src/libnetdata/ebpf](https://github.com/netdata/netdata/tree/fa0e45d5397758e1e7e916f827eced10d4909d73/src/libnetdata/ebpf) is used only by the `ebpf.plugin`.

If this is the case and there are no other users of that code, we should move the code outside of `libnetdata` and into the `ebpf.plugin`.

I'm opening this issue because it's not only a cosmetic change, it will also express our dependencies accurately and simplify CMakeLists.txt a lot (which I plan to do once this issue is resolved).

**Comment by vkalintiris** [comment]
@thiagoftsm this is not a high-priority issue, but it's still an issue which we'll have to resolve at some point.

**Comment by thiagoftsm** [comment]
All right @vkalintiris !

I will take a look on this today.
