### ISSUE TITLE
[Bug]: release channel stable is same as nightly

### ISSUE THREAD

**Issue by copolycube** [netdata/netdata#19144]
### Bug description

sh /tmp/netdata-kickstart.sh --stable-channel
or 
sh /tmp/netdata-kickstart.sh --release-channel stable

try to download the same (failed) nightly build 

In all cases, this results in :
```
 ABORTED  Failed to update existing Netdata install at /opt/netdata: Cannot download https://github.com/netdata/netdata-nightlies/releases/download/v2.0.0-163-nightly/sha256sums.txt
```

### Expected behavior

stable should point to a stable validated version

### Steps to reproduce

1.sh /tmp/netdata-kickstart.sh --stable-channel
2. observe the logs...

### Installation method

kickstart.sh

### System info

```shell
not relevant

Linux pariscnet-rolling 6.8.0-1017-gcp #19-Ubuntu SMP Tue Oct 15 19:02:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=24.04
/etc/lsb-release:DISTRIB_CODENAME=noble
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 24.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="24.04"
/etc/os-release:VERSION="24.04.1 LTS (Noble Numbat)"
/etc/os-release:VERSION_CODENAME=noble
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=noble
/etc/os-release:LOGO=ubuntu-logo
```

### Netdata build info

```shell
ko, cannot download
```

**Comment by ilyam8** [comment]
@copolycube, hi.

I believe this isn't a bug.

Since you're using the nightly build, running kickstart initiates an update process (while the previous failure you encountered has since been resolved).

Note that kickstart cannot be used to switch between nightly and stable versions. To move from nightly to stable:

1. Use your system's package manager to install `netdata-repo`.
2. This will automatically remove `netdata-repo-edge`.

cc @Ferroin

**Comment by copolycube** [comment]
> previous failure you encountered has since been resolved
indeed, nightly release channel seems back 


> kickstart cannot be used to switch between nightly and stable versions
I'd rather use the stable version, how can I proceed to change the fleet of servers I'm using ? (deploying through ansible using your netdata-quickstart example role, copied locally )


Thanks !
