### ISSUE TITLE
generate PNGs directly from netdata, for badges and possibly graphs

### ISSUE THREAD

**Issue by GitStoph** [netdata/netdata#1921]
Tried adding font-size to the HTML <div> but that didn't work of course. Realized after some digging that there's a resize variable running from the dashboard.js or the svg? Is there a way I can manually increase the size of the font and/or the dimensions of the badges?

**Comment by ktsaou** [comment]
Well, this the downside of pure `C` programming. netdata has everything about badges [embedded in C code](https://github.com/firehol/netdata/blob/d054d68acfd1d6a24b6f4904cb3c97a656836dee/src/web_buffer_svg.c#L762-L782), because the width of the badge needs to be calculated server-side, which it done using [a few unbelievable heuristics on verdana 11px](https://github.com/firehol/netdata/blob/d054d68acfd1d6a24b6f4904cb3c97a656836dee/src/web_buffer_svg.c#L12-L269) (yes, I calculated all the widths of verdana 11px using a node.js script, which I hardcoded into `C` code).

If you know any other/better to do it, I would be glad to do it...

**Comment by GitStoph** [comment]
As a netadmin, I'm afraid I have little to offer in this field. Did I understand correctly that shield.io has a process to return the badge back in an image format? Could that be done, then we could just figure out how to have the image stretch to the <div> container size? I imagine that wouldn't be as performance friendly, but for the select use-case scenario that'd prefer to use that method, it could be nice?

**Comment by ktsaou** [comment]
Yes, that would be nice. Unfortunately this would require netdata to be linked with imaging libraries, which would really explode the number of dependencies it has...

I tried to do that to support sending PNG charts with alarms (which would be wow!), but I gave up when I realized how many dependencies this would need.

I will leave your request open as an enhancement. I would really love to have netdata return PNGs...

**Comment by ccremer** [comment]
If this is still relevant, I managed to create a scaled badge using the style attribute in the img tag. e.g.
```html
<img class="netdata-badge" src="http://localhost:19999/api/v1/badge.svg?chart=whatever"
     style="height: 100px"
```
Worked for me in Firefox. Unfortunately, this does not auto refresh. To enable that you'll still need this snippet
```html
<script>
    var NETDATA_BADGES_AUTOREFRESH_SECONDS = 5;
    function refreshNetdataBadges() {
      var now = new Date().getTime().toString();
      $('.netdata-badge').each(function() {
        this.src = this.src.replace(/\&_=\d*/, '') + '&_=' + now;
      });
      setTimeout(refreshNetdataBadges, NETDATA_BADGES_AUTOREFRESH_SECONDS * 1000);
    }
    setTimeout(refreshNetdataBadges, NETDATA_BADGES_AUTOREFRESH_SECONDS * 1000);
</script>
```

**Comment by ktsaou** [comment]
hm... scaling badges...

in PR #3474 - now you can append `&scale=X`, where X >= 100 and netdata will returned a scaled badge.

**Comment by ktsaou** [comment]
Generating PNGs from the netdata server, would allow us to embed such charts in emails and notifications.

I would love to have this as part of the netdata hub.
So, it would be nice to discuss this a bit.

@cakrit 	@gmosx

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
