### ISSUE TITLE
Feature Request: Netflow Support

### ISSUE THREAD

**Issue by GitStoph** [netdata/netdata#1922]
ie: Ntopng, Flowviewer, etc.

NetFlow is virtually OS agnostic and can collect and classify so many different types of useful data which naturally could be monitored live. It also supports many router OS's from Cisco to MicroTik. Example configs may include:
- monitoring src IP's of all incoming to your machine's /32. 
* Break down destinations/src's even further by subnet. ie: 10.101.0.0/24 = reqs = total traffic MB.
* Break down subnets of dest/src by port range, etc. 

I understand that FireQOS can do a lot of this. However, FireQOS is limited to Linux/some Unix. Also setting up all of the rules to monitor & classify in different ways gets messy. 
ie: internal 10.0.0.0/16 broken into 36 different /24's, which is broken into a couple /26's. This could potentially require over 100 classifications in FireQOS and wouldnt even touch port matching. (unless someone knows a better way?)

Just a thought. Thanks!

**Comment by ktsaou** [comment]
nice request! I don't have a clue how to do this though... Any directions? Which programs do you use to get such information?

Keep in mind there is another way in Linux: the netfilter connection tracker. There is an option in netfilter connection tracker to do per connection/socket bandwidth accounting and there is libmnl that exposes all this information.

I want to support this connection tracker info mainly because it will allow netdata to present a chart like the following, without actually installing or using anything else:

![image](https://cloud.githubusercontent.com/assets/2662304/23772392/72581a28-0523-11e7-9469-9fa88aec16fe.png)

Of course, it will be Linux specific...

So, if you can help me find out what needs to be done, would be great...

**Comment by ktsaou** [comment]
oh... I just saw... flowviewer... let me check it.

**Comment by ktsaou** [comment]
Which depends on [SiLK](http://tools.netsa.cert.org/silk/index.html). It seems that SiLK does all the magic... I see it is written in C, so I will need to study this a bit...

**Comment by sarlacpit** [comment]
I use NFDump as a collector to receive the flows in both IPFIX & Netflow v9 and have a NFsen webGUI. It'd be nice to see the collected flows stacked.

**Comment by BobVul** [comment]
[ElastiFlow](https://github.com/robcowart/elastiflow) does this via Logstash; unfortunately ElastiFlow is not under a FOSS licence. Apparently an earlier version was contributed as a [Logstash module](https://github.com/elastic/logstash/tree/master/modules/netflow), which should be under [Apache 2.0 as per the mail LICENSE.txt](https://github.com/elastic/logstash/blob/master/LICENSE.txt).

In any case, both seem to rely on the [Logstash NetFlow codec](https://github.com/logstash-plugins/logstash-codec-netflow), which is [fully under Apache 2.0](https://github.com/logstash-plugins/logstash-codec-netflow/blob/master/LICENSE). Perhaps that would be useful as a starting point for a Netdata collector.

If this can be done without the huge memory requirements of the ELK stack (4 GB min recommended; I've gotten it down to ~3 GB before Logstash ... gets unhappy), that would be amazing.

**Comment by dlonghi** [comment]
[https://github.com/cloudflare/goflow](url)

**Comment by RubenKelevra** [comment]
> [ElastiFlow](https://github.com/robcowart/elastiflow) does this via Logstash; unfortunately ElastiFlow is not under a FOSS licence. Apparently an earlier version was contributed as a [Logstash module](https://github.com/elastic/logstash/tree/master/modules/netflow), which should be under [Apache 2.0 as per the mail LICENSE.txt](https://github.com/elastic/logstash/blob/master/LICENSE.txt).
> 
> In any case, both seem to rely on the [Logstash NetFlow codec](https://github.com/logstash-plugins/logstash-codec-netflow), which is [fully under Apache 2.0](https://github.com/logstash-plugins/logstash-codec-netflow/blob/master/LICENSE). Perhaps that would be useful as a starting point for a Netdata collector.
> 
> If this can be done without the huge memory requirements of the ELK stack (4 GB min recommended; I've gotten it down to ~3 GB before Logstash ... gets unhappy), that would be amazing.

Why not use nftables to count the traffic/packages?

Sure it would require a huge amount of filter rules, if you want to do AS-Network resolutions etc. but it's designed for exactly this task and does this very efficient.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
