### ISSUE TITLE
Adding RedisService for collecting Redis-based metrics

### ISSUE THREAD

**Issue by alibo** [netdata/netdata#1931]
Hi,

I saw the PR #1916 for MysqlService, and I think a RedisService also can be a good option. 
I wrote something simple for our Redis-backed queue jobs (Laravel Queue, Resque, ...) to collect these:

- Waiting jobs
- Failed Jobs
- Reserved Jobs
- Delayed Jobs
- Processed Jobs

But it can be used for other Redis-based metrics such as logins, reset-passwords, sign-ups, the number of connected clients, the number of chat messages and so on.

**Comment by l2isbad** [comment]
Yo @alibo 
Can you describe how RedisService supposed to work? The same as MySQLService works?

1. define in config/module
```python
 requests = dict(req1: 'request1', req2: 'request2', req3: 'request3')
```
2. get from _get_raw_data
```python 
 dict(req1='req1 result', req2='req2 result', req3='req3 result')
```

**Comment by alibo** [comment]
I think the same as MySQLService is fine.

Let me give you an example of mine:

```python
CHARTS = {
    'jobs': {
        'options': [None, 'Queue Jobs', 'jobs/s', 'jobs', 'laravel_redis_queue.jobs', 'line'],
        'lines': [
            ['waiting', 'waiting', 'absolute'],
            ['delayed', 'delayed', 'absolute'],
            ['reserved', 'reserved', 'absolute'],
            ['failed', 'failed', 'incremental'],
            ['processed', 'processed', 'incremental']
        ]},
}

LARAVEL_QUEUE_COMMANDS = ("LLEN laravel:queue:default\r\n"
                          "ZCARD laravel:queue:default:delayed\r\n"
                          "ZCARD laravel:queue:default:reserved\r\n"
                          "GET laravel:queue:default:processed\r\n"
                          "GET laravel:queue:default:failed\r\n")

```

But, if we use tcp socket, like `redis.chart.py`, processing its response would be hard, especially when it has multiple commands which are sent together (pipeline).

**Comment by l2isbad** [comment]
Do we really need RedisService?

Never used redis but this should work with current `SocketService` implementation (which looks not ok for me but it works :smile:):

The idea is to change self.requests before run _get_raw_data(). That is all.

```python
QUERIES =dict(query1='sdfsdfsdf', query2='sdfsdfsdf', query3='sdfsdfsdf')

ORDER = ...
CHARTS = ...

class Service(SocketService):
    def __init__(self, configuration=None, name=None):
        SocketService.__init__(self, configuration=configuration, name=name)
        ...
        ...

   def _get_data(self):
       raw_data = dict()
       for name, query in QUERIES.items():
           self.request = query.encode()
           response = self._get_raw_data()
           if response:
               raw_data[name] = response
          ....
          ....

    def _check_raw_data(self, data):
    # same as in redis.chart.py if first line always contains message length
```

**Comment by alibo** [comment]
The hard part is parsing Redis response :D 

Request:

```bash
echo \
"GET test-get-exists\r\n" \
"GET test-get-doesnt-exist\r\n" \
"GET test-get-exists-2\r\n" \
"LLEN test-list-exists\r\n" \
"LLEN test-list-doesnt-exist\r\n" \
"SCARD test-set-exists\r\n" \
"SCARD test-set-doesnt-exists\r\n" \
"HGET test-hash-exists key-exists\r\n" \
"HGET test-hash-exists key-doesnt-exists\r\n" \
"HGET test-hash-doesnt-exists key-doesnt-exists\r\n" \
"UNKNOWN_COMMAND 1\r\n" | nc 127.0.0.1 6379
```

Response:
```bash
$4
1234
$-1
$4
4321
:8
:0
:6
:0
$3
333
$-1
$-1
-ERR unknown command 'UNKNOWN_COMMAND'
```

A Redis client such as `redis-py` or `hiredis-py` can easily solve this issue.

**Comment by l2isbad** [comment]
Back to this, i am maybe be wrong, but it looks to me that `SocketService` is enough for custom Redis-like modules.

> The hard part is parsing Redis response

FrameworkService is responsible for getting raw data, not parsing it :thinking: 

Or it should work like this
 * user defines list of commands

```python
LARAVEL_QUEUE_COMMANDS = ("LLEN laravel:queue:default\r\n"
                          "ZCARD laravel:queue:default:delayed\r\n"
                          "ZCARD laravel:queue:default:reserved\r\n"
                          "GET laravel:queue:default:processed\r\n"
                          "GET laravel:queue:default:failed\r\n")
```

 * Framework service executes all commands and returns `{reqeusts': response, ...}` dict

?

**Comment by alibo** [comment]
> FrameworkService is responsible for getting raw data, not parsing it 🤔

@ilyam8 You're right, but we already have `MysqlService` which also parses the response of mysql. 

> user defines list of commands

Probably without `\r\n` :D 

> Framework service executes all commands and returns {reqeusts': response, ...} dict

Yes 👍(You probably needs a redis module for this :) )

**Comment by ilyam8** [comment]
Well, that makes sense

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
