### ISSUE TITLE
Oracle monitoring

### ISSUE THREAD

**Issue by jurgenhaas** [netdata/netdata#1996]
Saw this commit https://github.com/firehol/netdata/commit/9ff05473bc996100456a3f38f883fa3a3bb1bbd3 which looks like there is some reference to Oracle but I'm not sure if that is the Oracle DB or refers to MySQL from the Oracle company.

In any case, I'm wondering if an Oracle database can be monitored already or if there are any plans for a plugin.

**Comment by ktsaou** [comment]
Well, I don't have a clue how to connect to oracle to read performance metrics. I guess there will be a lot of them though...

The PR you mention is only for monitoring the oracle processes (cpu, ram, disk I/O, etc).

Can you help us find how to connect, what is available and what would be interesting to show in netdata? As @l2isbad frequently says, the actual development work of data collection, is the easy part. The research/preparation (i.e. find out what is there, how to get it, how to present it, etc) is probably the hardest.

**Comment by jurgenhaas** [comment]
Back when I used ServerDensity I had written a plugin to monitor the Oracle table spaces and I've uploaded that as a [Gist](https://gist.github.com/jurgenhaas/da4e72a013f0099f1386ec106a8810ed). The Python script executes a shell script to connect to Oracle and then execute a SQL statement piped in from a SQL file. The output is then processed in Python.

Not sure though if and how this could be generalized, but maybe it's a good starting point.

**Comment by l2isbad** [comment]
http://www.oracle.com/technetwork/articles/dsl/prez-python-queries-101587.html

`pip search cx_Oracle`
cx_Oracle (5.3)                 - Python interface to Oracle

**Comment by ktsaou** [comment]
nice!

ok. this means we can connect to it.
then we come to the question: what do we need to collect?

@jurgenhaas I saw the gist. Is this query something generally needed or specific for your need?

**Comment by jurgenhaas** [comment]
@ktsaou that's a good question. First, I would assume that collecting similar data as for mysql, mongodb and postgres is probably useful. Also, looking into the table size which I demonstrated in the gist, might be helpful generally as Oracle doesn't seem to auto-resize its table space and that's what needs the sysop's attention when you get to something like more than 80% utilization for one of the table spaces.

**Comment by skibbipl** [comment]
Hello,
I'm working on some Oracle monitoring with zabbix, and I use this:
https://github.com/anetrusov/ZabbixDBA/blob/master/conf/query.props.pl
Perhaps it's a good start for netdata plugin?

**Comment by ktsaou** [comment]
@skibbipl nice! thanks!
I see way too many queries. Many look "heavy", meaning that they probably sum a lot of rows. Is this fast? How often do you run these queries?

**Comment by skibbipl** [comment]
I'm still evaluating this solution in Zabbix, but from what I saw, queries were executed quite fast on the Oracle databases I used. But I'm working on non-production databases. By default queries are executed by zabbix every 30 seconds.

**Comment by ktsaou** [comment]
@l2isbad 	this is on our roadmap (monitor the performance of Oracle databases).

**Comment by cakrit** [comment]
Hi @jurgenhaas,

(https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

Would you be willing/able to play this role?

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by jurgenhaas** [comment]
@cakrit I'd be happy to take on the sponsor role as you described it above. Just want to mention that I'm neither an Oracle expert nor do I manage large Oracle installations. Only one of my clients is running 5 small Oracle hosts and from a monitoring perspective my knowledge is limited to what ServerDensity does which we used before we migrated over to NetData. However, if that's sufficient for this sponsorship, count on me.

**Comment by ldod-lle** [comment]
I can sponsor, we have several test and production Oracle databases in the house, and some DBAs to assist as well :smile: 

I'll forward the requested info on to them, and post feedback in this thread.

**Comment by ilyam8** [comment]
@ldod-lle this is very nice!

I see @kataras [silently working on it](https://github.com/netdata/go.d.plugin/pull/102).

And we need help. Mainly on grouping data to charts.

@ldod-lle @jurgenhaas 

have a look at charts
https://github.com/netdata/go.d.plugin/blob/oracledb/modules/oracledb/charts.go

All of them looks ok to me except these two:
 *  `Tablespace Size`
 *  `System Metrics`

## Tablespace Size

<details><summary>QUERY</summary>
<p>

```sql
SELECT
  Z.name,
  Z.bytes,
  Z.max_bytes,
  Z.free_bytes
FROM
(
  SELECT
    X.name                   as name,
    SUM(nvl(X.free_bytes,0)) as free_bytes,
    SUM(X.bytes)             as bytes,
    SUM(X.max_bytes)         as max_bytes
  FROM
    (
      SELECT
        ddf.tablespace_name as name,
        ddf.bytes as bytes,
        sum(coalesce(dfs.bytes, 0)) as free_bytes,
        CASE
          WHEN ddf.maxbytes = 0 THEN ddf.bytes
          ELSE ddf.maxbytes
        END as max_bytes
      FROM
        sys.dba_data_files ddf,
        sys.dba_tablespaces dt,
        sys.dba_free_space dfs
      WHERE ddf.tablespace_name = dt.tablespace_name
      AND ddf.file_id = dfs.file_id(+)
      GROUP BY
        ddf.tablespace_name,
        ddf.file_name,
        ddf.bytes,
        ddf.maxbytes
    ) X
  GROUP BY X.name
  UNION ALL
  SELECT
    Y.name                   as name,
    MAX(nvl(Y.free_bytes,0)) as free_bytes,
    SUM(Y.bytes)             as bytes,
    SUM(Y.max_bytes)         as max_bytes
  FROM
    (
      SELECT
        dtf.tablespace_name as name,
        dtf.bytes as bytes,
        (
          SELECT
            ((f.total_blocks - s.tot_used_blocks)*vp.value)
          FROM
            (SELECT tablespace_name, sum(used_blocks) tot_used_blocks FROM gv$sort_segment WHERE  tablespace_name!='DUMMY' GROUP BY tablespace_name) s,
            (SELECT tablespace_name, sum(blocks) total_blocks FROM dba_temp_files where tablespace_name !='DUMMY' GROUP BY tablespace_name) f,
            (SELECT value FROM v$parameter WHERE name = 'db_block_size') vp
          WHERE f.tablespace_name=s.tablespace_name AND f.tablespace_name = dtf.tablespace_name
        ) as free_bytes,
        CASE
          WHEN dtf.maxbytes = 0 THEN dtf.bytes
          ELSE dtf.maxbytes
        END as max_bytes
      FROM
        sys.dba_temp_files dtf
    ) Y
  GROUP BY Y.name
) Z, sys.dba_tablespaces dt
WHERE
  Z.name = dt.tablespace_name
```

</p>
</details>
<br/>

 **Chart**

```go
	{
		ID:    "tablespace",
		Title: "Tablespace Size",
		Ctx:   "oracledb.tablespace",
		Units: "KiB",
		Type:  modules.Stacked,
		Dims: Dims{
			{ID: "tablespace_max_bytes_system", Name: "system: max bytes", Div: 1024 * 100000},
			{ID: "tablespace_max_bytes_sysaux", Name: "sysaux: max bytes", Div: 1024 * 100000},
			{ID: "tablespace_max_bytes_users", Name: "users: max bytes", Div: 1024 * 100000},
			{ID: "tablespace_max_bytes_temp", Name: "temp: max bytes", Div: 1024 * 100000},

			{ID: "tablespace_free_bytes_system", Name: "system: free bytes", Div: 1024 * 100000},
			{ID: "tablespace_free_bytes_sysaux", Name: "sysaux: free bytes", Div: 1024 * 100000},
			{ID: "tablespace_free_bytes_users", Name: "users: free bytes", Div: 1024 * 100000},
			{ID: "tablespace_free_bytes_temp", Name: "temp: free bytes", Div: 1024 * 100000},

			{ID: "tablespace_bytes_system", Name: "system: bytes", Div: 1024 * 100000},
			{ID: "tablespace_bytes_sysaux", Name: "sysaux: bytes", Div: 1024 * 100000},
			{ID: "tablespace_bytes_users", Name: "users: bytes", Div: 1024 * 100000},
			{ID: "tablespace_bytes_temp", Name: "temp: bytes", Div: 1024 * 100000},
		},
	},
```

Do we need `max bytes`? Maybe `free bytes` is enough? What do you think?

## System metrics


```sql
SELECT METRIC_NAME, VALUE FROM GV$SYSMETRIC ORDER BY BEGIN_TIME
```

collected metrics and all of them in one chart currently

```go
var systemMetricsKeys = map[string]string{
	"Buffer Cache Hit Ratio":          "system_buffer_cachehit_ratio",
	"Cursor Cache Hit Ratio":          "system_cursor_cachehit_ratio",
	"Library Cache Hit Ratio":         "system_library_cachehit_ratio",
	"Shared Pool Free %":              "system_shared_pool_free",
	"Physical Reads Per Sec":          "system_physical_reads",
	"Physical Writes Per Sec":         "system_physical_writes",
	"Enqueue Timeouts Per Sec":        "system_enqueue_timeouts",
	"GC CR Block Received Per Second": "system_gc_cr_block_received",
	"Global Cache Blocks Corrupted":   "system_cache_blocks_corrupt",
	"Global Cache Blocks Lost":        "system_cache_blocks_lost",
	"Logons Per Sec":                  "system_logons",
	"Average Active Sessions":         "system_active_sessions",
	"Long Table Scans Per Sec":        "system_long_table_scans",
	"SQL Service Response Time":       "system_service_response_time",
	"User Rollbacks Per Sec":          "system_user_rollbacks",
	"Total Sorts Per User Call":       "system_sorts_per_user_call",
	"Rows Per Sort":                   "system_rows_per_sort",
	"Disk Sort Per Sec":               "system_disk_sorts",
	"Memory Sorts Ratio":              "system_memory_sorts_ratio",
	"Database Wait Time Ratio":        "system_database_wait_time_ratio",
	"Session Limit %":                 "system_session_limit_usage",
	"Session Count":                   "system_session_count",
	"Temp Space Used":                 "system_temp_space_used",
}
```

We need to split it to several charts (all dimension should have same units). 

If you can please help with this one too.

**Comment by ldod-lle** [comment]
Sure - can someone give me the quick 'n' dirty on how to install/enable the plugins (I see we need the go plugin on top of Oracle plugin) to the stock Netdata install, I'll get this going.

**Comment by ilyam8** [comment]
@ldod-lle let's agree on charts, @kataras will fix them and then you will be able to test it.

Let's start from `Tablespace size`.

Response
```
		   [tablespace_free_bytes_system] = [10420224]
		   [tablespace_max_bytes_undotbs1] = [34359721984]
		   [tablespace_bytes_temp] = [34603008]
		   [tablespace_max_bytes_users] = [34359721984]
		   [tablespace_bytes_users] = [5242880]
		   [tablespace_max_bytes_sysaux] = [34359721984]
		   [tablespace_free_bytes_sysaux] = [23658496]
		   [tablespace_bytes_sysaux] = [545259520]
		   [tablespace_free_bytes_undotbs1] = [4194304]
		   [tablespace_max_bytes_temp] = [34359721984]
		   [tablespace_free_bytes_temp] = [34603008]
		   [tablespace_free_bytes_users] = [4194304]
		   [tablespace_max_bytes_system] = [34359721984]
		   [tablespace_bytes_system] = [880803840]
		   [tablespace_bytes_undotbs1] = [335544320]
```

So we have `max_bytes`, `free_bytes` and `bytes`.

I am trying to understand which one we need and how to group the data into charts.

I am not an oracledb user but from what i read on the internet we don't need to chart `max_bytes`. Am i wrong?

**Comment by ldod-lle** [comment]
Here's what I got back from our DBAs:
"What we look at now is tablespace size, freespace and % used. Max size is important in that it is the limit the tablespace can expand via auto extend feature."
