### ISSUE TITLE
Get logs from systemd-journald

### ISSUE THREAD

**Issue by Yamakaky** [netdata/netdata#1999]
I'm thinking a base class as a wrapper around https://www.freedesktop.org/software/systemd/python-systemd/journal.html#systemd.journal.Reader. It would get the native metadata (severity, datetime...) and maybe/optionally run a callback on the entries. I can try, since I want to do a murmur plugin anyway ^^

**Comment by l2isbad** [comment]
[Good article ](https://www.g-loaded.eu/2016/11/26/how-to-tail-log-entries-through-the-systemd-journal-using-python/) (thx to @pschiffe)

**Comment by Yamakaky** [comment]
Yeah, I already found it ;)

**Comment by l2isbad** [comment]
@Yamakaky 
I write initial version of JournaldService class.
It uses get_next() method to get the data.

How it works:
1. Seek to tail when start
2. Match. If not match timestamp = current time. If match timestamp = timestamp from the last entry + 1 microsecond. Next iteration seek to the timestamp and 2 again.
3. Returns list of entries (default entry is a dict)

Not sure about exceptions we need 😄 

What do you think?

```python
class JournaldService(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.__journal = None
        self.__seek = None
        self.add_match = dict()

    def check(self):
        if not PYSYSTEMD:
            self.error('\'python-systemd\' module is needed to use \'journal\' plugin')
            return False

        if not (self.add_match and isinstance(self.add_match, dict)):
            self.error('Match to filter journal log entries is not defined')
            return False

        conn = self.__connect()
        if not conn['result']:
            self.error(conn['error'])
            return False

        if not self.__journal.get_usage():
            self.__journal.close()
            self.error('Not enough privileges to read journal files')
            return False
        else:
            return True

    def _get_raw_data(self):
        conn = self.__connect()

        if conn['error']:
            return None

        raw_data = list()

        try:
            if self.__seek:
                self.__journal.seek_realtime(self.__seek)
            else:
                self.__journal.seek_tail()

            while True:
                match = self.__journal.get_next()
                if not match:
                    break
                raw_data.append(match)
        except Exception:
            self.__journal.close()
            self.__journal = None
            self.__seek = None
            return None

        if not raw_data:
            self.__seek = datetime.datetime.now()
            return None
        else:
            self.__seek = raw_data[-1]['__REALTIME_TIMESTAMP'] + datetime.timedelta(0, 0, 1)
            return raw_data

    def __connect(self):
        if not self.__journal:
            try:
                self.__journal = journal.Reader()
                self.__journal.log_level(journal.LOG_INFO)
                self.__journal.this_boot()
                self.__journal.this_machine()
                self.__journal.add_match(**self.add_match)
            except Exception as error:
                self.__journal.close()
                self.__journal = None
                return {'result': False, 'error': str(error)}
        return {'result': True, 'error': False}
```

**Comment by Yamakaky** [comment]
In fact, I'm thinking a bigger refactoring would be beneficial, instead of doing a class by service-backend combination.

We would have:
- charts definition using a generic dict format, something like https://github.com/firehol/netdata/blob/master/python.d/apache.chart.py#L23
- collectors (log file, syslog, journald...) whose job is to provide a stream of lines, with generic metadata like timestamp, severity, message...
- a service-specific mapper which parses the message
- a service-specific aggregator which converts the line to the chart format. Since some operations are common like counting the lines for each categories, some generic functions could allow to factor part or all of this stage
- last stage which sends the data to netdata

So it would be something like `send(aggregator(map(mapper, get_input())))` (simplified). The config file of the plugin would have a `collector` key with `journald`... as value, and collector-specific keys like the journald unit name.

What do you think?

**Comment by l2isbad** [comment]
Not sure about `beneficial` part. The current logic straight and simple (@paulfantom did all the work) - framework class gets data and returns it without any modification (raw data), handles retries, exceptions, etc. That is all. Code is simple and easy to maintain.

**Comment by Yamakaky** [comment]
But each service is bound to a collector. For example, I have the nginx logs in journald, which isn't supported by the current web log plugin.

**Comment by Yamakaky** [comment]
Example with hardcoded input: https://0bin.net/paste/EUbM8k17RDXN1gXB#5U0HiHA5kPd-d1l1lrAmc9QK54rIqQpNC50ZvQOc0QS

**Comment by l2isbad** [comment]
> nginx logs in journald, which isn't supported by the current web log plugin

It's `web_log` problem. Not a big deal to add journald support. Actually logic the same - get data from _get_raw_data. Then parse. 

[haproxy plugin](https://github.com/firehol/netdata/blob/master/python.d/haproxy.chart.py#L61-L67)

**Comment by Yamakaky** [comment]
Yeah, it's not a lot, but you have to do it in all the classes.

**Comment by yohanboniface** [comment]
A generic service class to read from systemd journal would be really handy.
Any thing I can do to help?

**Comment by ktsaou** [comment]
@l2isbad check this ^^

**Comment by l2isbad** [comment]
@yohanboniface 
i see https://github.com/firehol/netdata/issues/1999#issuecomment-288837083
can you check if it work? (you need to define [add_match](https://www.freedesktop.org/software/systemd/python-systemd/journal.html#systemd.journal._Reader.add_match) in custom plugin)

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
