### ISSUE TITLE
Netdata Mobile App

### ISSUE THREAD

**Issue by techc0de** [netdata/netdata#2031]
Hello,

Netdata is very useful for admin to view server's info and other performance.
Currently when I view Netdata on my iPhone, it isn't friendly as on the browser.

It would be awesome if somebody can develop an app for iOS and Android.
We, users, can pay for the app for your support.
Maybe $.99 or $1.99 for the app.

**Comment by ktsaou** [comment]
nice! yes, that would be nice!

But I have it in my roadmap, after we have:

1. central health monitoring
2. authentication

**Comment by kmonsoor** [comment]
i second this. i'm also very interested on this, as i have some Android-related experience.

@ktsaou any further pointers would be highly helpful.

for who are interested (also to my future self):
 * the API `Netdata` provides: https://github.com/firehol/netdata/blob/master/web/netdata-swagger.json
 * there are some good Android library to handle the graphing e.g. 
   * [list on `Awesome-Android-UI`](https://github.com/wasabeef/awesome-android-ui/blob/master/pages/Graph.md)
   * [list on `awesome-android`](https://github.com/JStumpp/awesome-android#charts)

This future app can be 
 * supported as Donation-ware
 * ad-supported
 * [freemium](https://en.wikipedia.org/wiki/Freemium) model

**Comment by Fieel** [comment]
Or some simple mobile-responsive html/css dashboards should do the trick, or am i missing something? It's usable on mobile, just not really mobile friendly.

**Comment by kadukeitor** [comment]
Hello,

A few weeks ago I published [NetData App](https://netdata.kpots.com). The project is a mobile app to consume the Rest API of NetData.
I created the app because I found myself trying to check the metrics of my servers in situations where I don’t have a computer. To prevent any kind of confusion I added the header:

> NetData App is an unofficial app of NetData.

 The app have pretty much the same features of the web interface.

I would appreciate (if it’s possible) any feedback about the app.

Thanks

**Comment by jasongeng** [comment]
@kadukeitor Just tried your app. Very cool and helpful. Thanks a lot!

Regarding the refreshing interval, the minimum allowable is 5 seconds. Any chance of reducing it to shorter like 2s?

**Comment by kmonsoor** [comment]
thank you so much @kadukeitor. It is simple, but very useful design. Please keep it up.
However, for my use-case, I felt for a feature. It's the ability to use SSH, by ssh-tunneling, **using a PEM file** to access the instance. Please give it a thought.

**Comment by Fieel** [comment]
@kadukeitor that's really cool! I'd also love an option for ssh tunneling so i can use it when i'm not in the same LAN.

**Comment by tx7** [comment]
Hello Jorge,

That’s cool app.
My concern is that according to privacy agreement the app collects user’s phone info such as IP, location...

How often it collects?

**Comment by paulfantom** [comment]
@kadukeitor is your application code open-sourced somewhere?

**Comment by WoLpH** [comment]
When using a single netdata instance to gather all information its certainly a bit broken with both the site and the app (on android at least). Neither allows selection of the hosts which means it's completely unusable :(

**Comment by gentarro** [comment]
@kadukeitor Thanks you for your working ! :)
👍

**Comment by gmosx** [comment]
> Neither allows selection of the hosts which means it's completely unusable :(

You mean streaming hosts? Can you elaborate?

**Comment by WoLpH** [comment]
Yes, exactly. To have a single centralized endpoint I stream everything to a main netdata instance. I only have to arrange proxying and authentication for that one and the rest is firewalled

**Comment by lukasmrtvy** [comment]
@kadukeitor  is NetData App unmaintained ? I am missing few metrics..  And last update of applications is 19/05/2018
Thanks

**Comment by cakrit** [comment]
I'm closing this one, since the app isn't maintained by Netdata. As mentioned on the[app page](https://netdata.kpots.com/), you may contact hi@kpots.com for any issue or suggestion.

**Comment by unixfox** [comment]
Why closing this issue? Initially this feature request was for netdata itself and it's still for netdata even though someone made an unofficial mobile app for the community.

**Comment by cakrit** [comment]
Sure @unixfox, that makes sense. So we're keeping this for the feature request of an official netdata app.

**Comment by thefiredragon** [comment]
Official App would be great which would be also integreate the netdata cloud instance.
There are some apps in place from unkown like this:

https://apps.apple.com/us/app/netdata-server-monitoring/id1525322870

Would be a nice feature, best Regards

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
