### ISSUE TITLE
add a global time-frame selector on the dashboard

### ISSUE THREAD

**Issue by rankun203** [netdata/netdata#205]
First thank the team for the cool and great tool for us to have a completely sense of our servers.

I'm using my server as a port-forwarding mid-tier server for several people, and I want to see how's the traffic amount each person used, can I do that with netdata?

Thanks.

**Comment by ktsaou** [comment]
Thanks!

You already have a chart that shows the bandwidth per user per second and you want to know the volume of the data in any given duration?

or you want to to create such a chart?

**Comment by rankun203** [comment]
Yes, exactly, I want to know **the volume of the data in any given duration** like who used how much MB in the given duration.

**Comment by ktsaou** [comment]
Hm... nice!

It can be done, but it is not already on the dashboard. It would be nice to have a button per chart to show this info for the visible area.

Until it is done, you can do it by hand using this procedure:

1. On your browser hit F12 to open the console and switch to Network view.
2. On the chart you are interested , zoom to the area in question
3. Find the URL the dashboard send to the server. It will be something like this:

 ```
http://netdata.firehol.org/api/v1/data?chart=netdata.net&format=json&points=600&group=average&options=ms|flip|jsonwrap|nonzero&after=1460277797&before=1460283891&_=1460281505049
```

 Pay attention to `chart=XXXX`, it should be your chart. Copy this URL.

4. In this URL, set `points=1` and hit it with your browser

5. netdata will respond with something like this

 ```
{
	"api": 1,
	"id": "netdata.net",
	"name": "netdata.net",
	"view_update_every": 6093,
	"update_every": 1,
	"first_entry": 1460197848,
	"last_entry": 1460284248,
	"before": 1460280844,
	"after": 1460274751,
	"dimension_names": ["in", "out"],
	"dimension_ids": ["in", "out"],
	"latest_values": [193.9101, -448.5376],
	"view_latest_values": [133.43144, -238.54031],
	"dimensions": 2,
	"points": 1,
	"format": "json",
	"result": {
	"labels": ["time", "in", "out"],
	"data":
	[
		[ 1460280844000, 133.43144, -238.54031]
	]
},
	"min": -238.54031,
	"max": 133.43144
}
```

6. The duration of the visible area is shown as `view_update_every`.

7. Then for each dimension you have the average per second for each dimension. So:

 ```
 in volume = 6093 seconds * 133.43144 kbps = 812997.76392 KB
out volume = 6093 seconds * 238.54031 kbps = 1453426,10883 KB
```

I'll add it to a button on the dashboard.

**Comment by rankun203** [comment]
Thanks, you solved my problem, to collect the data volume of the period.

I see the duration can't be set to like 1 month, and I noticed netdata is designed to show everything happening right now, so I guess right now netdata only store the most recent data like 1 day?

**Comment by ktsaou** [comment]
You configure it. By default it is just an hour. Read the wiki about memory requirements. Netdata is a real-time performance monitoring, designed to troubleshoot real-time issues. Of course, many people ask for more (like statistics, alerts, etc). Patience, we are working on it...

**Comment by rankun203** [comment]
:+1: Thanks.

**Comment by aadityabagga** [comment]
Hi @ktsaou ,

Did you add the button?

I want to check how much data is being sent by my server per day, and currently do not see a chart for it in netdata. If possible, please add it as a metric and send to backend server, something like `netdata.system.ipv4.received_total` and `netdata.system.ipv4.sent_total`.

This way we will be able to check how much network usage is happening on server, as lots of providers bill for extra network traffic.

Thanks.

**Comment by aadityabagga** [comment]
@ktsaou thank you.

i am visualizing netdata backend data via influxdb -> grafana. will check how to get the required data via badge and try to export it as netdata backend metric, so it can be viewed in grafana.

**Comment by paulfantom** [comment]
Netdata states that it is `distributed real-time performance and health monitoring`, not long-term storage and analysis system. You can argue that 24h isn't a problem, but "period of time" can mean 1h as well as 5 years and how will you solve a problem of processing 5 years of data with 1s resolution? You need to draw a line somewhere.
And no, you cannot do both "long-term analysis" and "real-time monitoring" due to too much data. There are reasons why graphite reduces precision with time and prometheus docs warn people against holding more than couple of months of data.

And when we are on time-series data handling side, are we using [Gorilla](https://www.vldb.org/pvldb/vol8/p1816-teller.pdf)?

**Comment by ktsaou** [comment]
@gmosx 	is is on our roadmap.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
