### ISSUE TITLE
Netdata - Spring boot plugin

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#2074]
Currently we have tomcat plugin that is sort of limited in context. It would be nice to support Spring boot as this will give insight in to the JVM, current heap utilization levels, GC times, cache hits, DB query times, custom application metrics etc. 

In order to access this information currently Spring boot applications have a metrics endpoint through Actuator which can be polled at regular intervals to fetch all the configured/custom metrics. Prometheus uses this mechanism to capture Spring boot metrics. 

Alternately there is jolokia which exposes metrics on a JMX endpoint. Telegraf favors jolokia as input. 

It would be nice to have Netdata support one of these to pull Spring boot metrics in to its dashboard.

**Comment by ktsaou** [comment]
Can we do this with python? Can you point some documentation?

**Comment by gamefundas** [comment]
Jolokia endpoints basically exposes the application server's JMX beans as Http endpoints.
https://jolokia.org/tutorial.html

For example the following gives heap memory usage
http://localhost:8080/jolokia/read/java.lang:type=Memory/HeapMemoryUsage/used

Example response

`{
   "value":{
             "init":134217728,
             "max":532742144,
             "committed":133365760,
             "used":19046472
           },
   "status":200,
   "timestamp":1244839118,
   "request":{
               "mbean":"java.lang:type=Memory",
               "type":"read",
               "attribute":"HeapMemoryUsage"
             },
   "history":[{"value":{
                         "init":134217728,
                         "max":532742144,
                         "committed":133365760,
                         "used":18958208
                       },
               "timestamp":1244839045
             }, ....
             ]
 }`
In case of Actuator all metrics can be gathered by invoking the following endpoint
http://appserver/metrics 

An example response from actuator looks like...
`{
    "counter.status.200.root": 20,
    "counter.status.200.metrics": 3,
    "counter.status.200.star-star": 5,
    "counter.status.401.root": 4,
    "gauge.response.star-star": 6,
    "gauge.response.root": 2,
    "gauge.response.metrics": 3,
    "classes": 5808,
    "classes.loaded": 5808,
    "classes.unloaded": 0,
    "heap": 3728384,
    "heap.committed": 986624,
    "heap.init": 262144,
    "heap.used": 52765,
    "nonheap": 0,
    "nonheap.committed": 77568,
    "nonheap.init": 2496,
    "nonheap.used": 75826,
    "mem": 986624,
    "mem.free": 933858,
    "processors": 8,
    "threads": 15,
    "threads.daemon": 11,
    "threads.peak": 15,
    "threads.totalStarted": 42,
    "uptime": 494836,
    "instance.uptime": 489782,
    "datasource.primary.active": 5,
    "datasource.primary.usage": 0.25
}`

**Comment by l2isbad** [comment]
> http endpoints and json responses 

ElasticSearch plugin do exactly the same. http req - response in json.

**Comment by gamefundas** [comment]
Alright let me host a sample spring boot application in AWS and then get back to you.

**Comment by simonnagl** [comment]
#2663 (Java Plugin with JMX module) will provide

> insight in to the JVM, current heap utilization levels, GC times, cache hits, DB query times, custom application metrics

Well, this is not true. The fist version will be limited to JMX MBeans exposing number attributes but I hope we can extend it soon.

Spring Boot Actuator endpoint can be queried through JMX too, but I am not sure if it would be sufficient to query them with the module or it might be better to provide another module (maybe python) which queries the HTTP endpoints.

Having it in the JMX module would be great because it already might have an open connection to the java process and this connection might be faster than HTTP.

The downside is that the JMX module should stay very configurable and I currently have no clue how to extend the JMX plugin configuration with the ability of monitoring endpoints returning JSON. This might be quite some work.

**Comment by bjoernw** [comment]
Would really like this as well

**Comment by cakrit** [comment]
We do have a [springboot collector](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/springboot) now, so closing.

**Comment by simonnagl** [comment]
The current springboot collector uses Spring Boot Actuator. Spring introduced another system for metrics, [Micrometer](https://docs.spring.io/spring-boot/docs/2.1.0.RELEASE/reference/htmlsingle/#production-ready-metrics), which provides a simple facade over the instrumentation clients for the most popular monitoring systems. This may be used to collect even more Spring Boot Metrics.

I do not want to reopen this issue or requesting something. Just letting you know.
