### ISSUE TITLE
add option to change the averaging method of zoomed-out charts

### ISSUE THREAD

**Issue by archuserr** [netdata/netdata#2093]
First, I want to vote for issue #1884 to disable auto-scaling for the CPU and RAM graphs.

Second, some graphs measure things that cannot be fractions. Number of open files. Number of connections. I wish the scale on these graphs would only display whole numbers.

Screenshot attached showing useless labels.

![graph labels](https://cloud.githubusercontent.com/assets/27189844/25067408/8dec205e-21f7-11e7-9957-f78891fc5701.PNG)

**Comment by ktsaou** [comment]
Hi,

I understand autoscaling should be an option, since many people prefer it differently.

The second point about fractional charts, I think is not right. On my system `users.files` is always an integer. In your case, you have zoomed out the chart, which calculates the average over a longer duration. At this scale, every point on the chart is many seconds. This number, the average of many points, can be fractional. For example, for one second it was 10, the next one it was 5. The average of the 2 seconds is 7.5 ...

**Comment by archuserr** [comment]
This is interesting: When I zoom out, it averages multiple data points together. Is that the best approach? I'm using netdata to catch abnormal behavior in my system. Averaging multiple values together can hide what I'm looking for. When I zoom out, maybe it should display the maximum value, not an average.

**Comment by ktsaou** [comment]
You are right. The server can do min, max and average. I have to add a few buttons on the dashboard to let us pick...

With average I tried to emulate what all other systems do (i.e. what you would get if data collection did not happen per second).

**Comment by maletin** [comment]
i prefer a fat line, that spans from the min-value to the max-value.
at x=12 the value for y ranges from 0.9 to 1.1
![fatline](https://user-images.githubusercontent.com/36396/43887514-60187ca2-9bbf-11e8-861a-d38da6e82d68.png)

**Comment by ktsaou** [comment]
nice.

dygraphs (that we use), support something like this:

![image](https://user-images.githubusercontent.com/2662304/45420513-01b6b900-b693-11e8-825a-5f563ad5aada.png)

which I find a bit more insightful. Though this can be automatically be triggered when the dashboard is doing the aggregation / averaging. We will have to check how we can push from the server data to be triggered like this.

**Comment by ktsaou** [comment]
@gmosx 	this is on our roadmap.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
