### ISSUE TITLE
macOS alarms-notify.sh show stopper

### ISSUE THREAD

**Issue by ronlipke** [netdata/netdata#2095]
So I've been playing around with netdata in my homelab the last few days and really love it.  Got it up and running on a few macs of various vintage and ran into a pretty significant issue - the alarms-notify.sh script requires bash > 4.0.  Current system bash on `10.12.4` is `3.2.57(1)`.
I'm able to get alarms by homebrew-ing current bash and prepending the netdata user's `PATH` with `/usr/local/bin:/usr/local/sbin`, but don't think this is a sustainable solution. 

Are there plans to bundle netdata as a complete binary with static links?  As I get time this week I'm going to try and refactor alarms-notify.sh to detect bash <4 and act accordingly instead of just failing.

**Comment by ktsaou** [comment]
> Are there plans to bundle netdata as a complete binary with static links?

@l2isbad another use case for embedded python...

> As I get time this week I'm going to try and refactor alarms-notify.sh to detect bash <4 and act accordingly instead of just failing.

Well, refactoring the bash version without bash version 4+ will be tricky. Bash v4+ is required for its associative arrays. Version 3 does not provide them.

bash v4 has been [released February 2009](http://tldp.org/LDP/abs/html/bashver4.html). It is also pretty simple to [compile it statically](https://github.com/firehol/netdata/blob/master/makeself/jobs/50-bash-4.4.install.sh). So, it is pretty strange MacOS provides bash v3...

**Comment by sarlalian** [comment]
Apple specifically avoids GPL v3 software.  Bash switched to GPL v3 with Bash 4.x, so they will never include bash 4.x, and continue to ship a 10 year old version of bash.

**Comment by ktsaou** [comment]
Wow! Interesting!

Since you compile netdata, I think it would be pretty simple to compile bash v4 too.

You can also replace `alarm_notify.sh` with a script of yours to do whatever you like. You can configure it like this, in netdata.conf:

```
[health]
	script to execute on alarm = /usr/libexec/netdata/plugins.d/alarm-notify.sh
```

Unfortunately, without bash v4 alarm_notify.sh will become quite big and complex. It would be probably better to write it in python or split the logic to handle the configuration inside netdata and have many different scripts for each notification method.

**Comment by ktsaou** [comment]
eventually, alarms will be dispatched centrally by netdata hub.

So, although we do not plan to rewrite `alarm-notify.sh`, we will provide a much better alternative: a free service to dispatch alarm notifications centrally.

So, I am  closing this.

cc: @gmosx 	@cakrit
