### ISSUE TITLE
Support AWS SQS as a back-end

### ISSUE THREAD

**Issue by rickatnight11** [netdata/netdata#2099]
Semi-related to https://github.com/firehol/netdata/issues/1642, but we're looking to revamp our metric infrastructure, and it'd be wonderful for `netdata` to dump metrics into an [AWS SQS queue](https://aws.amazon.com/sqs/) to handle the transport and buffering of metrics to the upstream back-end (OpenTSDB in our case).

I'm not sure what the collector on the other end would look like, but I at least wanted to throw this out there as an idea to get the conversation going.

**Comment by ktsaou** [comment]
Hi,

hm... I see amazon has no C SDK. But hopefully they provide a C++ one which could be used to link netdata against it.

Another way could be to embed python into netdata and provide a way to send metrics to backends via python. Actually, I can find quite a few use cases for a feature like this (cc: @l2isbad ).

**Comment by rickatnight11** [comment]
It'd be a pretty cool transport mechanism for "headless collector" --> "central netdata", too!

**Comment by ktsaou** [comment]
This is nice!

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
