### ISSUE TITLE
Count TCP connections per port

### ISSUE THREAD

**Issue by povesteam** [netdata/netdata#2174]
Is it possible to extract number of connections per listening port?

For example, something similar with this graph, but with 4 lines (labeled 22, 80, 443, 3000) if there are processes listening for ssh, http, https and one node.

![image](https://cloud.githubusercontent.com/assets/506532/25898935/aba071c4-3596-11e7-88dc-43585b7dc649.png)

**Comment by ktsaou** [comment]
Hi.

Unfortunately no. But there is something similar (and probably more useful):

![image](https://cloud.githubusercontent.com/assets/2662304/25917017/624a6064-35cf-11e7-8db4-1659adbed343.png)

This chart shows the number of sockets open per application group. There are also similar charts for Users and Groups.

You can control the application groups, by editing `apps_groups.conf`.

**Comment by ktsaou** [comment]
The reason for not being able to do it per port, is that netdata will have read all the system sockets, which as you may understand there may be several thousands of them.

This is a CPU intensive operation I am trying to avoid. Though, this is a quite common request, so probably at some point we will have to do it, with the ability to enable or disable it as needed.

**Comment by ktsaou** [comment]
Also, keep in mind the chart I posted counts also the listening sockets.

**Comment by povesteam** [comment]
Hi @ktsaou, thank you for explaining and providing alternative.
I will try to configure `apps_groups.conf` and come back here with the result.

**Comment by povesteam** [comment]
It works when I add `node: node` to `apps_groups.conf`, but it counts all connections to those processes, including listen, incoming and outgoing.

I would want to count only established connections on the listening port.
In this example, I would want to see **4** connections for port 4000 and **7** connections for port 4001 (even the total of **11** would be ok).

Current behaviour includes outgoing database connections and the listening socket that you told me about, which gives a total of **16**.

```
tcp        0      0 0.0.0.0:4000            0.0.0.0:*               LISTEN      8852/node
tcp        0      0 127.0.0.1:4000          127.0.0.1:36320         ESTABLISHED 8852/node
tcp        0      0 127.0.0.1:4000          127.0.0.1:48075         ESTABLISHED 8852/node
tcp        0      0 127.0.0.1:4000          127.0.0.1:33103         ESTABLISHED 8852/node
tcp        0      0 127.0.0.1:4000          127.0.0.1:36921         ESTABLISHED 8852/node
tcp        0      0 127.0.0.1:4001          127.0.0.1:56316         ESTABLISHED 10744/node
tcp        0      0 127.0.0.1:4001          127.0.0.1:34597         ESTABLISHED 10744/node
tcp        0      0 127.0.0.1:4001          127.0.0.1:36214         ESTABLISHED 10744/node
tcp        0      0 127.0.0.1:4001          127.0.0.1:41623         ESTABLISHED 10744/node
tcp        0      0 127.0.0.1:4001          127.0.0.1:36032         ESTABLISHED 10744/node
tcp        0      0 127.0.0.1:4001          127.0.0.1:56402         ESTABLISHED 10744/node
tcp        0      0 127.0.0.1:4001          127.0.0.1:36042         ESTABLISHED 10744/node
tcp        0      0 172.30.1.79:48881       172.30.4.20:27017       ESTABLISHED 8852/node
tcp        0      0 172.30.1.79:58490       172.30.4.20:27017       ESTABLISHED 8852/node
tcp        0      0 172.30.1.79:48236       172.30.4.20:27017       ESTABLISHED 10744/node
tcp        0      0 172.30.1.79:48246       172.30.4.20:27017       ESTABLISHED 10744/node
```

On production servers the difference is even bigger: netdata reports **517** connections for `node`, but the real number is only **479**.

I used this command `netstat -tlnpau | grep ESTABLISHED | grep /node | grep '0 127.0.0.1:400' | wc -l`

My connections are fairly constant, the application is websocket-based and the clients rarely disconnect, and I want to monitor this counter and trigger alerts on it.

Thank you!

**Comment by ktsaou** [comment]
ok, I marked this as enhancement.

**Comment by ktsaou** [comment]
Keep in mind that until this is a standard feature of netdata, you can create a very simple bash based plugin to execute the commands you are interested and push these metrics to netdata.

Check: 

- docs: https://github.com/firehol/netdata/wiki/General-Info---charts.d
- example: https://github.com/firehol/netdata/blob/master/charts.d/example.chart.sh

**Comment by povesteam** [comment]
I already created a bash plugin, and it works correctly, but in the docs you don't recommend forking and piping, this is why I proceeded with this issue. 😄 

Can you point me in the right direction, where in the code I might start to implement the feature myself, and to create a pull request with it?

**Comment by l2isbad** [comment]
@povesteam 
I think 1 grep is enough.
(ipv4 ssh established 22 port)

```bash
sudo netstat -tlnpau | grep --count -E "0 [0-9]{1,3}(\.[0-9]{1,3}){3}:22.+ESTABLISHED.+ssh"
5
```

**Comment by ktsaou** [comment]
It needs a little bit of thinking.

Allowing netdata to parse each socket of the system opens a new world of possibilities.

Several network statistics are already exposed by the kernel with `/proc/net/snmp`, `/proc/net/snmp6`, `/proc/net/netstat`, etc. However, access to each socket allows netdata to provide many of the system-wide metrics, per process, application group, user, group, cgroup, container, systemd service, etc.

So, my scope is not just to count the sockets per port, but to find a way of providing a totally new way of monitoring network apps.

---

For your specific case, extending @l2isbad suggestion, you can avoid another fork with this:

```sh
# do these once
port=4001
hex_port=$(printf "%04X" $port)

# do this for every iteration to find the number of sockets to this port
# the last "01" = ESTABLISHED
established=$(grep --count -E "^[[:space:]]*[[:digit:]]+: [0-9A-F]+:${hex_port} [0-9A-F]+:[0-9A-F]+ 01 " </proc/net/tcp)
```

So, just 1 fork, no sudo.

**Comment by povesteam** [comment]
Thank you @ktsaou and @l2isbad, this is a much better way of counting.

I will be following this thread and please let me know if I can be of any help regarding testing or implementation.

**Comment by ktsaou** [comment]
This could probably be implemented with eBPF.

**Comment by Saruspete** [comment]
Hello,

Would be a parsing of `/proc/net/tcp` be useful ? You have all required metrics there for per-user (uid) / per-status (per-app would need parsin & finding the inode, too expensive).

It's more standard and readily available than eBPF.

I can try to work on it for tcp & udp if you want.

**Comment by mfundul** [comment]
> 
> 
> Hello,
> 
> Would be a parsing of `/proc/net/tcp` be useful ? You have all required metrics there for per-user (uid) / per-status (per-app would need parsin & finding the inode, too expensive).
> 
> It's more standard and readily available than eBPF.
> 
> I can try to work on it for tcp & udp if you want.

The problem with `/proc/net/tcp` is that it can contains thousands of lines and it's going to be too heavy to parse. This is why we're considering eBPF or something else more lightweight (e.g. SystemTap.

**Comment by Saruspete** [comment]
production-wise, I don't expect a monitoring tool to modify the kernel in any way. So, I wouldn't allow eBPF (even less systemtap)  to run on my server without my explicit agreement & script validation.

For servers being under support, a custom kernel mod (like systemtap does) taint the kernel.
eBPF is not readily available on older kernel versions.
`Iptables -J ULOG` is nice but I explicitly disable iptables on some of my latency sensivite servers. 

Also note that compiler & development tools are not always available on the monitored servers.
tcpdump is too heavyweight for just header processing.

Maybe providing multiple features would require more work, but leave more choices to the user, depending on their situation:
- Production stable, but higher processing cost: parsing `/proc/net/tcp` & variants
- Prodcution stable, but for newer kernel & compiler: eBFP
- Production stable, but need more configuration / integration: `iptables -J ULOG` (using netdev)
- Less stable, and needs compiler and special package & compiler: systemtap

Maybe `|ftrace](https://www.kernel.org/doc/html/latest/trace/ftrace.html)` would be a nice way to find it too, but it may collide with parallel usage

**Comment by mfundul** [comment]
We are considering eBPF cause it's already being used for monitoring by Sysdig, cloudflare, datadog etc.

We are also considering Systemtap because with the new [stapbpf](https://developers.redhat.com/blog/2017/12/13/introducing-stapbpf-systemtaps-new-bpf-backend/) backend it allows the user to choose between running a Systemtap script via eBPF for extra security or via kernel module for extra performance.

`/proc/net/tcp` has been initially rejected in our discussions internally, but I agree that it's good to give options to the users. We should discuss some more.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
