### ISSUE TITLE
perf_events, flamegraph support?

### ISSUE THREAD

**Issue by juju4** [netdata/netdata#2176]
Hello,

I recently discovered netdata and find it great.
One of the thing I'm missing would be perf_events data and be able to generate flamegraph as exposed here
http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html

any plan?

Thanks

**Comment by ktsaou** [comment]
Hi,

thanks! flame graphs are wow!

However, do you have any ideas how we could use them? They require performance tracing information that is:

1. "expensive" to be collected (CPU hungry)
2. require admin privileges (this would require netdata running as root)
3. cannot be running all the time (i.e. you start a program to get performance events for a few seconds, which you visualize later with flame graphs).

If we can find a use case, I would love to add it.

**Comment by juju4** [comment]
The goal for me of perf_event/flamegraph is to locate overload in functions and syscalls of program to trace and fix.

As for constraint
1. yep, seems so. vector/pcp tool has similar work http://vectoross.io/docs/cpu-flame-graphs.html
2. clearly not the idea. at minimal use sudo or better privilege separated daemons to do so.
3. if it's too expensive, can only be on demand. as for vector, great if it can be done directly in web ui. if it is not, can render as a film. Work to render flamegraph with d3.js

- https://github.com/spiermar/d3-flame-graph
- https://github.com/cimi/d3-flame-graphs

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.

**Comment by redbaron** [comment]
Just to add some datapoints.

[parca](https://www.parca.dev/)  implements continuous profiling with their agent (push model). They also support pull model where parca connects to Go with `pprof` endpoint enabled and take traces there.

Their agent uses `ebpf` for tracing , maybe natdata's own ebpf plugin can be extended to support it as well?
