### ISSUE TITLE
Add multi-language support(such as Chinese)

### ISSUE THREAD

**Issue by darrentangdt** [netdata/netdata#219]
Hi, Thanks a lot for your hard work!
Do you have any plan  to add multi-language support for this project? such as Chinese?  I'll translates into Chinese.

**Comment by ktsaou** [comment]
Nice request.

I have done some work to decouple the dashboard content (menus and info text) from the html. They are already defined in 2-3 JSON arrays in the dashboard. But it needs some more work to make it properly.

**Comment by darrentangdt** [comment]
that sounds great.thanks ! 
when it is done, i'll translates it.

**Comment by ktsaou** [comment]
Check #279

**Comment by No9012** [comment]
Also good for me, Thanks

**Comment by ktsaou** [comment]
@gmosx this is on our roadmap, low priority though.

**Comment by gmosx** [comment]
@ktsaou I think we could add some code from Google Translate to automatically handle this for web/gui.

**Comment by ktsaou** [comment]
> @ktsaou I think we could add some code from Google Translate to automatically handle this for web/gui.

If we provide the strings in a file and we load the right language on demand, I am sure contributors will be very keen to translate them in all possible languages.

**Comment by paulfantom** [comment]
Or use sth like [babel](http://babel.pocoo.org/en/latest/)

**Comment by gmosx** [comment]
> If we provide the strings in a file and we load the right language on demand, I am sure contributors will be very keen to translate them in all possible languages.

I would prefer to leave this for hub.

**Comment by ktsaou** [comment]
> I would prefer to leave this for hub.

You will not be getting contributions then... I would open-source these files to let people help.

**Comment by ktsaou** [comment]
But we have plenty of time to discus this later.

**Comment by cakrit** [comment]
Done in #5197
