### ISSUE TITLE
web_log: support squid logs

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#2235]
@l2isbad would it be relatively simple for the web_log plugin to also monitor squid access.log?

The log format is here: http://wiki.squid-cache.org/Features/LogFormat

What is really missing from the squid charts in netdata is timing information and probably break down of requests per status.

**Comment by l2isbad** [comment]
i like the idea.
Also we can move apache_cache plugin to the web_log

**Comment by ktsaou** [comment]
yes, nice!

**Comment by l2isbad** [comment]
@ktsaou 
What charts do we need?

Here some logs from my local proxy
```
1495973309.909   1064 10.4.23.199 TCP_MISS/200 1958 GET http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml - HIER_DIRECT/23.78.126.5 text/xml
1495973310.300   1724 10.4.23.199 TCP_REFRESH_UNMODIFIED/200 13153 GET http://www.squid-cache.org/Artwork/SN.png - HIER_DIRECT/173.209.34.163 image/png
1495973310.327      0 10.4.23.199 TCP_DENIED/403 3915 GET http://observium.somedomain.lan/favicon.ico - HIER_NONE/- text/html
1495973312.177    877 10.4.23.199 TCP_MISS/200 1875 GET http://isrg.trustid.ocsp.identrust.com/MHEwbzBNMEswSTAJBgUrDgMCGgUABBRv9GhNQxLSSGKBnMArPUcsHYovpgQUxKexpHsscfrb4UuQdf%2FEFWCFiRACEAoBQUIAAAFThXNqC4XspwiiHjAcMBoGCSsGAQUFBzABBAQNMAsGCSsGAQUFBzABAQ%3D%3D - HIER_DIRECT/192.35.177.195 application/ocsp-response
```

1. **duration** (min, avg, max)
2. **clients** 
3. **[squid result codes](http://www.comfsm.fm/computing/squid/FAQ-6.html#cache-result-codes)**
4. **http result codes**
5. **bytes** 
6. **request method**

?

**Comment by ktsaou** [comment]
the seem nice!

Additionally:

- I don't know how squid logs authenticated users. If this is logged, a chart with them would be nice (I don't use this feature, so I can't tell).

- `HIER_DIRECT`, `HIER_NONE`, etc could also be in a chart.

- mime types could also be in a chart.

(I really like this log charting feature - a lot of useful information without any application support)

**Comment by l2isbad** [comment]
implemented
