### ISSUE TITLE
fping plugin feature request for host lists

### ISSUE THREAD

**Issue by efaden** [netdata/netdata#2273]
It would be nice if the fping plugin could take an array of (hostname, ip) key value pairs instead of having to go update the system hosts file.

**Comment by ktsaou** [comment]
Yes, it would be nice. However this is controlled by fping, not netdata.
Let me think of alternatives... it bothers me too...

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
