### ISSUE TITLE
dashboard with thousands of charts

### ISSUE THREAD

**Issue by yoorshop** [netdata/netdata#2275]
See screenshot enclosed, with last updated version

![netdatjs](https://cloud.githubusercontent.com/assets/10398236/26725390/a2806684-479e-11e7-80ab-9501f3ea5510.png)

Did we miss something in last updates ?

**Comment by venkatesh6114** [comment]
This error may happen when bug in script , or new extension installed or issue in firefox itself. So can you please check where the issue using [this](https://support.mozilla.org/en-US/kb/warning-unresponsive-script)

**Comment by yoorshop** [comment]
Issue is of course in chrome too... or i would have mentionned it

**Comment by ktsaou** [comment]
As you can see the script reported to be busy is jquery.

Can you verify the installed file is not corrupt? This is mine:

```sh
# md5sum /usr/share/netdata/web/lib/jquery-2.2.4.min.js 
2f6b11a7e914718e0290410e85366fe9  /usr/share/netdata/web/lib/jquery-2.2.4.min.js
```

Try also to fetch it from it netdata:

```sh
# curl -Ss 'http://localhost:19999/lib/jquery-2.2.4.min.js' | md5sum 
2f6b11a7e914718e0290410e85366fe9  -
```

You should have the same hashes.

**Comment by yoorshop** [comment]
[root@web1 ~]# curl -Ss 'http://localhost:19999/lib/jquery-2.2.4.min.js' 
| md5sum 2f6b11a7e914718e0290410e85366fe9
md5sum: 2f6b11a7e914718e0290410e85366fe9: No such file or directory
curl: (23) Failed writing body (0 != 16058)
[root@web1 ~]#

but file exist in :
/root/netdata/web/lib

Then
cd /root/netdata/web/lib

[root@web1 lib]# md5sum jquery-2.2.4.min.js
2f6b11a7e914718e0290410e85366fe9  jquery-2.2.4.min.js
[root@web1 lib]#

**Comment by ktsaou** [comment]
Could you please retry this:

```
curl -Ss 'http://localhost:19999/lib/jquery-2.2.4.min.js' | md5sum
```

**Comment by ktsaou** [comment]
ok,I think this is not the problem. I just noticed this:

![image](https://cloud.githubusercontent.com/assets/2662304/26751865/11378ffa-484c-11e7-9eb0-af87068c0620.png)

and this (the scrollbar of your browser):

![image](https://cloud.githubusercontent.com/assets/2662304/26751878/6530f2f4-484c-11e7-865c-d17e7ffb2f77.png)

So, I think your netdata finds a hell a lot of cgroups in this system, which results in probably several thousands of charts.

Please post the output of these commands:

```sh
uname -a
cat /etc/os-release
tree /sys/fs/cgroup/ 
```

The last one will have a long output, so please upload it as txt file to this issue.

**Comment by yoorshop** [comment]
Not home now, true a lot of cgroups are there, and not before
Server is centos with Cl cagefs

**Comment by ktsaou** [comment]
ok. I would need the output of `tree /sys/fs/cgroup/` to understand how cgroups should be grouped or enabled/disabled.

**Comment by ktsaou** [comment]
Normally this is just configuration, but I would prefer to have your help to ship netdata with proper defaults even for this case.

**Comment by yoorshop** [comment]
see enclosed file requested
[cgroups-tree.txt](https://github.com/firehol/netdata/files/1049674/cgroups-tree.txt)

**Comment by ktsaou** [comment]
hm... 459 cgroups * 5-10 charts per cgroup, gives 2.200 to 4.500 charts... This is the reason - the dashboard has to generate html for all these charts and this takes some time...

The interesting part is that these cgroups are just number named. Which program generates them? Is there anything that can map numbers to names or you don't care are about this? In general, they should use a sub-directory to create them, since now it is impossible to match them without matching others containers (docker, lxc, etc).

So, to disable them you will need to edit `netdata.conf`, find the `[plugin:cgroups]` section and set `enable by default cgroups matching = !*`. Unfortunately this will disable all cgroups.

I will try to improve the performance of the dashboard when thousands of charts are available.

**Comment by yoorshop** [comment]
LVE from CL generates these

I use netdata for 2 months, there was no issue before last updates

**Comment by yoorshop** [comment]
ok, fixed

**Comment by ktsaou** [comment]
ok, nice. I don't think anything changed in netdata in this area during the last 2 months (after v1.6).

Probably they decided to create a few more cgroups and they did it at the root cgroups directory, so netdata found them and added them.

Anyway, I consider this a bug in netdata. The dashboard should not need that much time to load with a few thousand charts...

**Comment by yoorshop** [comment]
LVE has evolved surely then...

Considering cagesfs, and fact thzt in past netdata needed to be ajusted 
to belong to correct group to get IO informations, I think this is the 
kind of issue with cgroups

**Comment by yoorshop** [comment]
I spoke too fast, after restart it was ok, and after some F5, and 
browser testing, cgroups has re-eappeard, and big loading speed issue 
like before

**Comment by ktsaou** [comment]
ok, fetch `http://your.netdata.ip:19999/netdata.conf` and post here the section `[plugin:cgroups]`.

**Comment by yoorshop** [comment]
[plugin:cgroups]
	# cgroups plugin resource charts = yes
	# update every = 1
	# check for new cgroups every = 10
	# enable cpuacct stat (total CPU) = auto
	# enable cpuacct usage (per core CPU) = auto
	# enable memory (used mem including cache) = auto
	# enable detailed memory = auto
	# enable memory limits fail count = auto
	# enable swap memory = auto
	# enable blkio bandwidth = auto
	# enable blkio operations = auto
	# enable blkio throttle bandwidth = auto
	# enable blkio throttle operations = auto
	# enable blkio queued operations = auto
	# enable blkio merged operations = auto
	# recheck zero blkio every iterations = 10
	# recheck zero memory failcnt every iterations = 10
	# recheck zero detailed memory every iterations = 10
	# enable systemd services = yes
	# enable systemd services detailed memory = no
	# report used memory without cache = yes
	# path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpuacct
	# path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
	# path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
	# path to /sys/fs/cgroup/devices = /sys/fs/cgroup/devices
	# max cgroups to allow = 500
	# max cgroups depth to monitor = 0
	# enable new cgroups detected at run time = yes
	# enable by default cgroups matching = !*.
	# search for cgroups in subpaths matching =  !*-qemu  !/init.scope  
!/system  !/systemd  !/user  !/user.slice  *
	# script to get cgroup names = 
/opt/netdata/usr/libexec/netdata/plugins.d/cgroup-name.sh
	# run script to rename cgroups matching =  *docker*  *lxc*  !/  
!*.mount  !*.partition  !*.scope  !*.service  !*.slice  !*.swap  !*.user 
  *
	# cgroups to match as systemd services =  !/system.slice/*/*.service  
/system.slice/*.service

**Comment by ktsaou** [comment]
ok, uncomment the setting and remove the `.`

Like this:

```
enable by default cgroups matching = !*
```

**Comment by yoorshop** [comment]
sorry for that. I'm tired, i had a terrific week

**Comment by ktsaou** [comment]
no problem... these things happen...

**Comment by ktsaou** [comment]
so work for optimizing netdata dashboards when there are too many charts in pr #2281 
still a work in progress...

**Comment by ktsaou** [comment]
I made a lot of optimizations in PR #2281 
Loading the dashboard is now 50-70% faster.

**Comment by ktsaou** [comment]
merged it

**Comment by yoorshop** [comment]
Hi,

I re-open this ticket nin relation with cloudlinux servers, i still get back all lve entries

I do
wget -O /opt/netdata/etc/netdata/netdata.conf "http://localhost:19999/netdata.conf"

edit /opt/netdata/etc/netdata/netdata.conf 

and modify line with this 
default cgroups matching = !*
or
#default cgroups matching = !*

i restart netdata, immediately is ok, but after 2 minutes all is back again

something is overriding settings edited in your last versions

**Comment by ktsaou** [comment]
@yoorshop could you please fetch http://your.netdata.ip:19999/netdata.conf and post here the section [plugin:cgroups] when this happens?

**Comment by yoorshop** [comment]
here it is, as you can see, my edit is reverted automatically after 5-10 minutes

File /opt/netdata/etc/netdata/netdata.conf is currently 0 octets

This issue is on all CL servers where i use netdata

[plugin:cgroups]
	# cgroups plugin resource charts = yes
	# update every = 1
	# check for new cgroups every = 10
	# enable cpuacct stat (total CPU) = auto
	# enable cpuacct usage (per core CPU) = auto
	# enable memory (used mem including cache) = auto
	# enable detailed memory = auto
	# enable memory limits fail count = auto
	# enable swap memory = auto
	# enable blkio bandwidth = auto
	# enable blkio operations = auto
	# enable blkio throttle bandwidth = auto
	# enable blkio throttle operations = auto
	# enable blkio queued operations = auto
	# enable blkio merged operations = auto
	# recheck zero blkio every iterations = 10
	# recheck zero memory failcnt every iterations = 10
	# recheck zero detailed memory every iterations = 10
	# enable systemd services = yes
	# enable systemd services detailed memory = no
	# report used memory without cache = yes
	# path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpu,cpuacct
	# path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
	# path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
	# path to /sys/fs/cgroup/devices = /sys/fs/cgroup/devices
	# max cgroups to allow = 1000
	# max cgroups depth to monitor = 0
	# enable new cgroups detected at run time = yes
	# enable by default cgroups matching =  !*/init.scope  !/system.slice/run-*.scope  *.scope  /machine.slice/*.service  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.socket  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/*  !/machine  !/qemu  !/system  !/systemd  !/user  * 
	# search for cgroups in subpaths matching =  !*/init.scope  !*-qemu  !*.libvirt-qemu  !/init.scope  !/system  !/systemd  !/user  !/user.slice  !/lxc/*/*  * 
	# script to get cgroup names = /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-name.sh
	# script to get cgroup network interfaces = /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network
	# run script to rename cgroups matching =  !/  !*.mount  !*.socket  !*.partition  /machine.slice/*.service  !*.service  !*.slice  !*.swap  !*.user  !init.scope  !*.scope/vcpu*  !*.scope/emulator  *.scope  *docker*  *lxc*  *qemu*  *kubepods*  *.libvirt-qemu  * 
	# cgroups to match as systemd services =  !/system.slice/*/*.service  /system.slice/*.service 
	# enable cgroup / = no
	# search for cgroups under / = yes
	# enable cgroup lve1000 = yes
	# enable cgroup lve1661 = yes
	# enable cgroup lve1044 = yes
	# enable cgroup lve1004280 = yes
	# enable cgroup lve1030771 = yes
	# enable cgroup lve1388 = yes
	# enable cgroup lve1001 = yes
	# enable cgroup lve10300771 = yes
	# enable cgroup lve1040 = yes
	# enable cgroup lve1028822 = yes
	# enable cgroup lve99 = yes
	# enable cgroup lve837 = yes
	# enable cgroup lve99007 = yes
	# enable cgroup lve99005 = yes
	# enable cgroup lve1076 = yes
	# enable cgroup lve1592 = yes
	# enable cgroup lve1204 = yes
	# enable cgroup lve1011 = yes
	# enable cgroup lve1203 = yes
	# enable cgroup lve51736 = yes
	# enable cgroup lve660 = yes
	# enable cgroup lve1171 = yes
	# enable cgroup lve1032850 = yes
	# enable cgroup lve10000 = yes
	# enable cgroup lve1292 = yes
	# enable cgroup lve1290 = yes
	# enable cgroup lve5 = yes
	# enable cgroup lve3 = yes

**Comment by ktsaou** [comment]
Do you want all these `lve` cgroups monitored?

If not, please prefix this:

```
enable by default cgroups matching = !lve* whatever is already there
```

What are all those? If they are common, we could exclude them in netdata by default.

**Comment by yoorshop** [comment]
Of course no...

as explained earlier, my setting will be overriden

tested now again, same issue

**Comment by ktsaou** [comment]
Please post this:

```
sudo grep "enable by default cgroups matching" /etc/netdata/netdata.conf
```

and this:

```
curl -Ss 'http://localhost:19999/netdata.conf' | grep "enable by default cgroups matching"
```

**Comment by yoorshop** [comment]
we use opt folder, and centos7 :
grep "enable by default cgroups matching" 
/opt/netdata/etc/netdata/netdata.conf

[root@web6 ~]# grep "enable by default cgroups matching" 
/opt/netdata/etc/netdata/netdata.conf
         # enable by default cgroups matching = !lve*
[root@web6 ~]#

[root@web6 ~]# curl -Ss 'http://localhost:19999/netdata.conf' | grep 
"enable by default cgroups matching"
         # enable by default cgroups matching =  !*/init.scope  
!/system.slice/run-*.scope  *.scope  /machine.slice/*.service  !*/vcpu*  
!*/emulator  !*.mount  !*.partition  !*.service  !*.socket  !*.slice  
!*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/*  !/machine  
!/qemu  !/system  !/systemd  !/user  *
[root@web6 ~]#

**Comment by ktsaou** [comment]
Please uncomment it in `netdata.conf` and don't throw away the rest of the patterns.
So:

1. uncomment it
2. prefix the parameter list with `!lve*`
3. restart netdata

**Comment by yoorshop** [comment]
no more issue so far

thanks Mate !

**Comment by yoorshop** [comment]
Hello,
Issue is back after upgrade, setting was overwritten  on all our CL servers 
 # enable by default cgroups matching =  !*/init.scope  !/system.slice/run-*.scope  *.scope  /machine.slice/*.service  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.socket  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/*  !/machine  !/qemu  !/system  !/systemd  !/user  *

**Comment by ktsaou** [comment]
well, netdata or the installer does not write `netdata.conf`. It only reads it.

How did you install netdata? If you use a package distributed by third parties, then probably that package overwrote your `netdata.conf`.
