### ISSUE TITLE
UI for editing alarms

### ISSUE THREAD

**Issue by Elitric** [netdata/netdata#2296]
Hey, 

Question/feature request - is it possible to edit alarm settings on the fly from netdata's web interface? Or should I go into files and edit numbers there? If not, are you planning on adding this feature?

**Comment by ktsaou** [comment]
Hi, no you cannot currently edit anything on a netdata dashboard. The dashboard is read-only.
This feature requires authentication to be implemented.

**Comment by Elitric** [comment]
Thanks for the reply, then I have work to do :) Thanks for this great tool btw!

**Comment by tve** [comment]
I have to say that the damn alarms is the primary reason I'm reluctant to installing netdata on more machines. They're just way, way, way too noisy. With the std config I get >20 emails/day and that's just ridiculous. I don't want to receive an alert because the CPU is busy: I'm using the CPU! Etc.
Having some easy way in the UI to enable/disable various groups of alerts would be really, really useful.

**Comment by ktsaou** [comment]
Hi,

Why you don't disable the ones you don't need?

Generally, I try to supply alarms for many things: alarms are easier to remove/adapt than create. So, the easiest for most users (and the hardest for me) is to supply many alarms, for everything imaginable, and for the users to remove/disable/adapt the ones that bother them.

Also, if you believe an alarm is wrong and provides a lot of fault positives, then just open an issue and let's discuss what the right thresholds should be by default.

Of course, I am open to any other ideas you may have...

**Comment by ktsaou** [comment]
@tve, I forgot to mention this about the CPU utlization alarms:

in general server systems that have constant CPU utilization above 60-70%, over long durations, are prone to performance issues. netdata triggers these alarms above 90% and excludes `nice`, to allow us run batch jobs during the night, without triggerring the alarms. So, if you have heavy computational tasks, either disable the CPU alarms, or renice these processes.

Of course, if there are more alarms that bother you, let's discuss them.

**Comment by Elitric** [comment]
@ktsaou, I don't necessarily think that defaults are wrong, we can all agree it depends on your setup. As an example, I don't need packet storm warning on certain machines because I do network testing there, so I would disable that alarm on them. 

Alarms that bother me the most are disk backlog, disk utilization and cpu iowait (and you can probably guess all of them are related). I get a ton of alarms when we are doing backups and other cron-related task so I know that time window. It would be nice to disable alarming at that time - that way more preferable to disabling it outright! Although that conflicts with realtime monitoring in general.

**Comment by ktsaou** [comment]
@gmosx 	this is on our roadmap.

**Comment by cakrit** [comment]
We will address this request in #2673, though not via a UI. Combined with #3187, we will be able to resolve these issues. Features for alarm & notification management via a UI will be provided by the hub.
