### ISSUE TITLE
More layouts for the dashboard

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#2302]
Any plans of featuring additional layouts for the dashboard? For instance a two column layout can show more graphs in one view.

**Comment by ktsaou** [comment]
Such things are pretty easy to do (plain javascript code).
The original netdata dashboard had 3 views. Check `http://your.netdata.ip:19999/old/`. It is slow since it is based on google charts, but you will get the idea.

So, PR guys... anyone willing to work on this, is welcome to make PRs...

**Comment by RicardoJSTeixeira** [comment]
/old saved me from the new legend view. Thanks

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
