### ISSUE TITLE
Long hostnames cause alignment issues in my-netdata

### ISSUE THREAD

**Issue by bh9** [netdata/netdata#2335]
The my-netdata menu assumes each hostname will fit onto one line. If they don't, the buttons on the right no longer line up with the name they correspond to. This is only really an issue when trying to delete hosts from your personal list (as otherwise you can just click the name)
I am observing this with 50 character hostnames.

```
netdata -v
netdata 1.6.0-532-g58a5c2e_rolling
```
![my-netdata_shift](https://user-images.githubusercontent.com/23195777/27142467-075d80fe-5123-11e7-9c81-37e8310ca446.png)

**Comment by ktsaou** [comment]
oops! that's a bug....

**Comment by gmosx** [comment]
I believe this issue is fixed in the baster branch. Will close the issue.
