### ISSUE TITLE
Drawing donut or pie charts for metrics with multiple components

### ISSUE THREAD

**Issue by elfgoh** [netdata/netdata#2339]
Looking at the [demo dashboard]( https://github.com/firehol/netdata/blob/master/web/dashboard.html), it seems like it isnt possible to use represent certain metrics like `system.ram`(free, used, cached, buffers) in netdata. 

I see that Piety and Google Charts have the capability to do it though.

Is there a way to do it currently?

**Comment by ktsaou** [comment]
currently no. But I think this would be a very nice addition...

**Comment by ktsaou** [comment]
Now, there is a `d3pie` chart in netdata. It is not currently used by the dashboard, though you can use it in custom dashboards.

It is very fast (optimized by me) and very silk.

![peek 2018-11-23 15-05](https://user-images.githubusercontent.com/2662304/48944961-58612e80-ef31-11e8-8c6d-6e58480544c7.gif)

**Comment by fti-dpogra** [comment]
Can you give me a simple example code of d3pie chart as mentioned above?

**Comment by gmosx** [comment]
You can find examples here:

```
https://github.com/netdata/netdata/blob/master/web/gui/dashboard.html
```

For example:

```
<div data-netdata="system.cpu"
     data-chart-library="d3pie"
     data-width="100%"
     data-height="300px"
     data-after="-60"
     data-points="60"
     data-dt-element-name="time902"
></div>
```
