### ISSUE TITLE
Howto set light theme by default?

### ISSUE THREAD

**Issue by n0guest** [netdata/netdata#2347]
Hi.

Is there a way to set light theme by default? I've looked into conf and didn't find anything related to theme. As i see, it's totally in HTML/JS/CSS and can't be overrided via settings from conf?

PS: Thaks for great product.

**Comment by ktsaou** [comment]
Just set it once on each netdata and it will remember it (saved on browser local storage).
It is also propagated from netdata server to netdata server, if you move around with the `my-netdata` menu.

**Comment by n0guest** [comment]
> Just set it once on each netdata and it will remember it (saved on browser local storage).

Thanks, i know that it can be made "per browser" basis. But in our case we have many servers and few team members. In result you'll have almost endless number of situations, where it need to be chosen "manually". That's why i asked about setting "default" via conf file.

> It is also propagated from netdata server to netdata server, if you move around with the my-netdata menu.

Another our specifics - most of servers doesn't have any relations (belong to different customers). So, we're searching a solution to propagete our "default setup".

Is it possible to include such feature request in your roadmap? It would be great to have such feature one day.

**Comment by Ferroin** [comment]
Actually, it would be kind of nice to be able to set defaults for the client-side settings in netdata.conf (I like the dark theme, but I do prefer to not have spline-smoothed lines on the charts, as well as disabling the help).  With that, maybe add an option to the settings dialog to revert to the default settings?

**Comment by ktsaou** [comment]
Well, there is way...

In netdata.conf there is this setting:

```
[web]
	custom dashboard_info.js = file.js
```

`file.js` is any filename you like in `/usr/share/netdata/web/`. This was developed to allow us have custom information on the dashboard (overwrite or add texts and labels). There is an example supplied by netdata: https://github.com/firehol/netdata/blob/master/web/dashboard_info_custom_example.js

It is a javascript file, so unless I find some strange problem, I could provide a few commented examples to change default dashboard settings (like help, theme, etc).

How does that sound?

**Comment by n0guest** [comment]
> It is a javascript file, so unless I find some strange problem, I could provide a few commented examples to change default dashboard settings (like help, theme, etc).

It would be great to have such sample. In our case we will include custom js-file in our rpm/deb builds of netdata. And having this customized js-file within installed package, we should change only one line in netdata.conf to apply it.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).

**Comment by ms-jpq** [comment]
Put this in your custom js

```javascript
(() => {
  const key = "netdataTheme";
  if (!localStorage.getItem(key)) {
    localStorage.setItem(key, "White");
    location.reload();
  }
})();

```
