### ISSUE TITLE
support filtering dimensions at backends

### ISSUE THREAD

**Issue by hereTac** [netdata/netdata#2373]
here is my config
![qq 20170622004412](https://user-images.githubusercontent.com/8244097/27396056-7ce4a9f8-56e4-11e7-9a16-dabb8af72c6f.png)
```
[backend]
         host tags = testcluster
         enabled = yes
         data source = average
         type = graphite
         destination = tcp:node3:2003
         prefix = netdata
         hostname = node3
         update every = 10
         buffer on failures = 10
         timeout ms = 20000
         send charts matching = !*yarn users.*
```
then i start my netstat an d wait for a while  . query in the influxdb
![qq 20170622004415](https://user-images.githubusercontent.com/8244097/27396169-d7c7896c-56e4-11e7-8119-bced71c37256.png)

```
[root@node3 ~]#  influx -execute 'select * from "netdata.node3.users.vmem.root"' -database "graphite"|less|wc -l
386
[root@node3 ~]#  influx -execute 'select * from "netdata.node3.users.vmem.yarn"' -database "graphite"|less|wc -l
386
[root@node3 ~]#  influx -execute 'select * from "netdata.node3.users.vmem.root"' -database "graphite"|less|wc -l
390
[root@node3 ~]#  influx -execute 'select * from "netdata.node3.users.vmem.yarn"' -database "graphite"|less|wc -l
390
[root@node3 ~]# 
```

so .why the metric "netdata.node3.users.vmem.yarn" still be sended to the influxdb
(i use the master and build the project. that is no doubt about the project version)
@ktsaou 
hope your help. thanks u

**Comment by ktsaou** [comment]
Hi,

let me check:

```sh
# netdata -W simple-pattern '!*yarn users.*' 'users.vmem.yarn'
RESULT: NOT MATCHED - pattern '!*yarn users.*' does not match 'users.vmem.yarn'

# netdata -W simple-pattern '!*yarn users.*' 'users.vmem.hello'
RESULT: MATCHED - pattern '!*yarn users.*' matches 'users.vmem.hello'
```

So, it works (it is exactly the same code - this match is executed internally before prepending `netdata.hostname.` to the metric).

To verify that netdata **really** does not send the metrics, do this:

1. In the contrib directory there is the script `nc-backend.sh`.
2. Run it like this: `./contrib/nc-backend.sh start 2003` and leave it running on a terminal.
3. Instruct netdata to send metrics to `127.0.0.1:2003`
4. Restart netdata

The command you have left open on a terminal starts dumping the metrics netdata sends. Do they include `*yarn`?

**Comment by zhangxin0112** [comment]
ye . i try it 
open a terminal and leave it running
[root@node3 ~]# nc -n 192.168.33.203 -lk 2003 >>test7 

conf my netdata.conf
[backend]
         host tags = testcluster
         enabled = yes
         data source = average
         type = graphite
         destination = node3:2003
         prefix = netdata
         hostname = node3
         update every = 10
         buffer on failures = 10
         timeout ms = 20000
         send charts matching = !*yarn users.*

then i check the file test7
![qq 20170622094318](https://user-images.githubusercontent.com/8244097/27413641-3cb1253c-572f-11e7-99d0-df95ce33c32d.png)


i check your simple-pattern it show the right result what i want.
![qq 20170622094632](https://user-images.githubusercontent.com/8244097/27413714-b17ca6de-572f-11e7-90db-b6cb22b7d9cf.png)


but use `netdata` it still not working . it still send all the data.

**Comment by zhangxin0112** [comment]
the code last commit is merge the #2363 to the master

[root@node3 netdata]# git log|head -n 9
commit 4bbcb17504d8296ebe08c1554ea095e333e0a127
Merge: b419ed3 2d2adb2
Author: Costa Tsaousis <costa@tsaousis.gr>
Date:   Tue Jun 20 02:15:40 2017 +0300

    Merge pull request #2363 from efaden/master
    
    Fixing missing "[".

[root@node3 netdata]#

**Comment by ktsaou** [comment]
this gets interesting...
Let me try to reproduce it...

**Comment by ktsaou** [comment]
ok, I found it.

The setting says `send charts matching`, **charts**, the whole of them.

You are trying to filter dimensions of a chart. This is not supported currently. Once the chart is matched, the whole chart (all dimensions of it) are sent.

**Comment by zhangxin0112** [comment]
ye.
i noticed that too.
expect the filtration will be more power . to filter dimensions of a chart.

**Comment by ktsaou** [comment]
ok, I marked this as enhancement

**Comment by zhangxin0112** [comment]
Ye . thank u

**Comment by ktsaou** [comment]
@cakrit 	this is on our roadmap. But low priority.
I would also add: support emulating other collectors too.

**Comment by cakrit** [comment]
Emulating other collectors will be covered in #2689. I suggest we keep this focused on dimension filtering.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
