### ISSUE TITLE
Doc/Faq : How I can disable alarms for specific target?

### ISSUE THREAD

**Issue by heikkis** [netdata/netdata#2391]
If I eg. net_packets.eno50 plugin alarms are flooding the slack channel and I would like disable this alarm. I tried plugin configuration events = no configuration without any affect.

```
[plugin:proc:/proc/net/dev:eno50]
        events = no
```

Simple problem but could not find solution.

**Comment by ktsaou** [comment]
Hi, you need to edit the alarm (the notifications state the alarm file and line). There will be `families: *` line. Make it: `families: !eno50 *`, so you will still receive this alarm for all interfaces, except `eno50`.

To disable this alarm for all interfaces, make it `families: !*`, or set `to: disabled`.

The first (`families: !*`) will disable the alarm completely
The second (`to: disabled`) will run the alarm (the dashboard will show notifications and the alarm will be active), but you will receive no external notifications for this alarm.

**Comment by ktsaou** [comment]
btw, the `events = no` config you expected, is nice. I'll try to add it.

**Comment by heikkis** [comment]
@ktsaou Thanks!

I will edit /etc/netdata/health.d/net.conf file then.

**Comment by cutalion** [comment]
Hi! Similar question. How to disable all alarms for master in master-slave setup? Or how to disable them for a specific host?

**Comment by cakrit** [comment]
> Hi! Similar question. How to disable all alarms for master in master-slave setup? Or how to disable them for a specific host?

Does [this](https://github.com/netdata/netdata/tree/master/health#alarm-line-hosts) help you?

**Comment by cutalion** [comment]
@cakrit Oh, how did I miss it? Thank you!

**Comment by cutalion** [comment]
Hm.. tried to add it to global `[health]` section in `netdata.conf`. Did not work.
Should I add this to every health.d config?

**Comment by cakrit** [comment]
hosts and families can only be specified in the individual conf files under health.d, so I don't know of another way to do it. It could just be a copy and a sed command to  add it to all of them anyway though.

**Comment by cakrit** [comment]
I am closing this, please reopen if you have additional questions/issues.
