### ISSUE TITLE
possible to make a dashboard for all configured hosts?

### ISSUE THREAD

**Issue by perfecto25** [netdata/netdata#2403]
application looks great, was wondering if its possibel to setup a dashboard that has a summary of all your configured hosts, maybe by uptime or cpu load or whatever, something like a quick overview of your env. Is that something that can be done at this time? Thanks.

**Comment by rgcamus** [comment]
@perfecto25  I'm trying something [here](https://github.com/rgcamus/netdatarama) ?
(v0.0.1 from a "rails" newbie...  don't be cruel)

**Comment by ktsaou** [comment]
Currently this can be done only with custom dashboards.
But we are developing the netdata hub, a free service that will provide such a network overview.

So, I am closing this.
