### ISSUE TITLE
global overview for netdata servers

### ISSUE THREAD

**Issue by cgoze** [netdata/netdata#2405]
Hi,
I've installed netdata on a group of computers. I configured them to send their metrics to a master (as explained here https://github.com/firehol/netdata/wiki/Monitoring-ephemeral-nodes).
But I was wondering if something exists yet to display on the master's dashboard a view of the global state of the slaves, as for example a global cpu or RAM ?
Thanks :)

**Comment by ktsaou** [comment]
Hi, not yet.
I plan to add this in v1.8 (the current netdata will be released as v1.7, so the next one).

**Comment by peterrus** [comment]
You might be able to query the rest api as described here and then foreach returned hostname entry do a lookup for those specific metrics. Not a turnkey solution of course ;)

**Comment by ktsaou** [comment]
This will be part of the netdata hub we are developing.
