### ISSUE TITLE
Number of users

### ISSUE THREAD

**Issue by Paarsch** [netdata/netdata#2415]
Would it be posible to show a gauge with the number of users on a given server?
For a couple of webservers i want to be able to see how many websites (users) are residing on a host. I can see a number of dimensions under for example users.cpu, but i have yet to get this translated to a number usable in a gauge or piechart.

Any idea's?

**Comment by ktsaou** [comment]
You are right. This is missing.

**Comment by ktsaou** [comment]
This has been implemented in a couple of ways.
So, I am closing it.
