### ISSUE TITLE
[Feature]TimescaleDB support

### ISSUE THREAD

**Issue by elfgoh** [netdata/netdata#2423]
I would like to request support for [TimescaleDB](http://www.timescale.com/index.html) as netdata backend, which is an extension on top of Postgres. Thanks!

**Comment by elfgoh** [comment]
This is beyond me, but I suspect that it may be useful as a reference for someone interested: https://github.com/timescale/pg_prometheus

**Comment by elfgoh** [comment]
Found #1380 which is informative

**Comment by ktsaou** [comment]
@elfgoh for this to be implemented, some analysis has to be made, to understand how it will work.

netdata has hosts, containing charts, containing dimensions / metrics. Each metric has an algorithm (incremental, absolute, etc).

I read that timeseriesdb has tables and the insert statement is something like this: http://docs.timescale.com/api#insert

```sql
CREATE TABLE conditions (
 time        TIMESTAMPTZ       NOT NULL,
 location    TEXT              NOT NULL,
 temperature DOUBLE PRECISION  NULL
);

INSERT INTO conditions(time, location, temperature, humidity)
  VALUES (NOW(), 'office', 70.0, 50.0);
```

I am not yet sure how netdata should push metrics to it. Shall we create a table per host and then add metrics as `chart, dimension, value`?

I mean, I could spend some time to link netdata with `libpq` and somehow execute `INSERT` statements from the backends functionality. The question is: can you prepare everything else?

**Comment by elfgoh** [comment]
> I mean, I could spend some time to link netdata with libpq and somehow execute INSERT statements from the backends functionality. The question is: can you prepare everything else?

What constitutes "everything else"? I am not sure if I am up to it myself skills wise but I can try. I can also give a shoutout to the timescaledb follks/community

**Comment by mahlonsmith** [comment]
After toying a bit (and coming away fairly impressed) with Timescale, here's a proposal for a super simple schema layout, that leaves the heavy lifting to PostgreSQL as nature intended:

```sql
CREATE TABLE netdata (
    time timestamptz default now() not null,
    host text not null,
    metrics jsonb default '{}'::jsonb not null
);
```
Inserts then of course just being:

```sql
INSERT INTO netdata ( host, metrics ) VALUES ( 'hostname', '<<JSON BLOB>>' );
```

I think there are some advantages to this worth calling out:

  - Timescale is not necessarily required for storing metrics here, if someone has a lesser storage need, or is already doing their own declarative (or trigger based) partitioning.  Timescale can be added at any point afterwards via:
```sql
ALTER TABLE netdata RENAME TO netdata_old;

CREATE TABLE netdata (LIKE netdata_old INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES);

SELECT create_hypertable( 'netdata', 'time', 
    chunk_time_interval => 86400000000,
    partitioning_column => 'host',
    number_partitions => 10
);   # or whatever

INSERT INTO netdata ( SELECT * FROM netdata_old );
DROP TABLE netdata_old;
```
 - Netdata doesn't need to create tables, indexes, nor concern itself with columns per metric - dump it all into a json blob without worrying about schema.  You still benefit from all of the goodies described [here](http://docs.timescale.com/v0.8/introduction/data-model).
 - Indexing specific metrics is left entirely to how the consumer wants to use the data, and can be adjusted anytime afterwards based on SELECT usage.  As an example, indexing 1 minute load might look something like this (depending on data structure, I'm just pretending it looks like `/api/v1/allmetrics?format=json`):
```sql
CREATE INDEX load1 on netdata using btree ( ((metrics->'system.load'->'dimensions'->'load1'->>'value')::real) );
```
  There's some more on this in the Timescale docs [here](http://docs.timescale.com/v0.8/using-timescaledb/schema-management#json).
  - After index tuning, more traditional "column" layouts can be easily created with SQL views, making longer term trending / graph building with Grafana significantly easier.

Coupled with the JSON filtering discussed in #3198, I think this setup allows the most flexibility for longer term trending.  (And yeah, the thought of answering questions like "what were memory stats across the farm during the 500 errors?" in a single SQL report is really attractive.)

**Comment by ktsaou** [comment]
@mahlonsmith so you suggest that netdata should execute 1 insert per iteration with all the metrics in one json? This json will be big. Are you sure this will be efficient?

**Comment by mahlonsmith** [comment]
With defaults, (and the multitude of scale) - likely not.  But with judicious use of `update every` and `send charts matching`, alongside sensible PostgreSQL connection scaling (pgbouncer, etc):  My hunch is that it's do-able.

I'll work up some benchmarks for some real-world numbers.

**Comment by mahlonsmith** [comment]
This might also be better served entirely outside of core netdata, and rather separate small parts - using the netdata json backend to send to a (currently imaginary) netdata->postgres abstraction.

**Comment by mahlonsmith** [comment]
I've worked up a experimental abstraction/glue daemon, and have started testing it in our environment. (400 netdata daemons sending to it concurrently, soon to be around 1200 once I get v1.9 everywhere...)

https://bitbucket.org/mahlon/netdata-tsrelay/src

Doing the job so far without fiddling with netdata directly.  If nothing else I think this convinced me that direct storage to PostgreSQL or integration with Timescale _probably_ doesn't belong in core netdata, given its 'zero config' philosophy.  I can't envision how you'd send things in a way that wouldn't either be wasteful or inflexible, without having things filtered and sent as a single json blob.  (And of course even that's not zero config effort on the PostgreSQL side of things either - consuming that data could be potentially terrible without tuning.)  Schema migrations, indexing, convenience view creations, optional timescale... etc.  Seems better suited to "small parts" elsewhere -- the netdata json stream feels perfectly sufficient for bridging to glue code.

**Comment by emanzx** [comment]
+1 for this feature

**Comment by cakrit** [comment]
Increasing the priority here, as several people want this.

**Comment by cakrit** [comment]
TimescaleDB has just published a [blog post](https://blog.timescale.com/blog/writing-it-metrics-from-netdata-to-timescaledb/amp/) for @mahlonsmith 's [tool](https://bitbucket.org/mahlon/netdata-tsrelay/src). Since we haven't progressed with this anyway, we should just update our docs and point to that implementation. @joelhans, everything is described very well in those two posts, so I expect we don't need to copy anything, just a link to [https://bitbucket.org/mahlon/netdata-tsrelay/src](https://bitbucket.org/mahlon/netdata-tsrelay/src) and obviously update the list of integrations.

You have our apologies for not investigating what you did @mahlonsmith, we keep working on improving our response & resolution times.

**Comment by mahlonsmith** [comment]
No apologies necessary!  I see somewhere along the way there was also a blurb added to https://docs.netdata.cloud/backends/ for longer term storage to PostgreSQL using Prometheus Remote Write -- seems people have some choices now.  All good.

**Comment by runejuhl** [comment]
Got notifications on this issue as I'm tracking it, and just wanted to mention that I have a complete demo project with Netdata, TimescaleDB, @mahlonsmith's [netdata-tsrelay](https://bitbucket.org/mahlon/netdata-tsrelay/src) and a Grafana dashboard to match that I created to play around with TimescaleDB together with Netdata.

Find it here: https://github.com/runejuhl/grafana-timescaledb.

**Comment by mahlonsmith** [comment]
To anyone that might be using or interested in the relay tool, just a heads up that I'm abandoning BitBucket, and moved the repository here to GitHub.

https://github.com/mahlonsmith/netdata-timescale-relay

**Comment by cakrit** [comment]
@joelhans lets get the documentation page up and updated with the github link that @mahlonsmith sent. Of course we should also mention @runejuhl 's project as well.
