### ISSUE TITLE
alarms for specific hosts on central netdata server

### ISSUE THREAD

**Issue by Jetman80** [netdata/netdata#2427]
Hi!
I have health checks enabled only on my central netdata server. And I am trying to add a new alarm to override standard check by template. Can't understand how this should be done. For example:
```
:19999/netdata.conf part from the central server:
...
[736bfe1c-4c76-11e7-9b94-0cc47a6bd554/disk_backlog.dm-2]
        # history = 86940
        # enabled = yes
...
```
that is exact chart name I am trying to catch.

Then I add the following to the health.d/custom/disks.conf (copy-paste of template, 10m->5m just as example):
```
   alarm: 5min_disk_backlog
      on: 736bfe1c-4c76-11e7-9b94-0cc47a6bd554/disk_backlog.dm-2
  lookup: average -5m unaligned
   units: ms
   every: 1m
   green: 2000
     red: 5000
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1))
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1))
   delay: down 15m multiplier 1.2 max 1h
    info: average of the kernel estimated disk backlog, for the last 5 minutes
      to: sysadmin

```
Then killall -USR2 netdata

Then I check the output of 
:19999/host/my_slave_host/api/v1/alarms?all

And cant find any mention of 5min alarm at all.
Tried to add that alarm directly on slave - no luck.
I guess that I cannot reference "on: " with the "host_id/chart_id" value, as it is named in resulting netdata.conf?

Thanks in advance for answer and, btw, netdata - is just awesome piece of work.

**Comment by ktsaou** [comment]
Hi, it seems I missed this issue. Sorry...

Unfortunately, alarms are global not per host (how did I forgot to provide something for this)?

So, currently you can add an alarm on `disk_backlog.dm-2` which will be applied to all hosts, for the same disk (keep in mind recent commits convert `dm-2` to a name as shown in `/dev/mapper`).

**Comment by Jetman80** [comment]
Hi! Thanks for reply.
Dm-2 disk name is widely used on my servers, so no sense doing such way.
For now I switched back to alerts from slave servers and waiting for 1.8 release :)

**Comment by ktsaou** [comment]
Somehow I forgot to update this.

Netdata now supports `hosts: host1 host2 host* !host4 ...` in alarms, so you can configure each alarm to be applied to one or more netdata hosts.

I am closing this. But if you believe something is still missing, just post.
