### ISSUE TITLE
Using SNMP to monitoring remote servers

### ISSUE THREAD

**Issue by darthjuanan** [netdata/netdata#2442]
Hi!

I'm trying snmp.conf plugin in node.d to test a few elements of external servers:

- load average
- disk size and available space
- network interfaces
- memory use
- cpu use

But I'm looking for a snmp.conf sample to this task, and I did'nt found.

Has anybody a sample snmp.conf to this task? I'm using stardard OIDs for SNMP.

Thanks in advance.

**Comment by ktsaou** [comment]
I haven't this ready, but if you want we could build this together... In the process I will show you how to do it, and if the result is good for most people here, we could include it in netdata to help more people.

**Comment by ilyam8** [comment]
Netdata's snmp collector is very basic, it requires to set exact OIDs/OIDs ranges.

Suggested way to monitor remote servers is to install Netdata agent on them 😉
