### ISSUE TITLE
Question: Is netdata capable of monitoring openVZ containers?

### ISSUE THREAD

**Issue by nadeem2001** [netdata/netdata#2474]
We see that netdata is good for monitoring LXD containers but having googled for a while we cannot see if it is possible for us to monitor OpenVZ containers.

If this is the case then is there a guide or tutorial as to how this is done? We'd really like to use your system as it appears head and shoulders above the others in terms of usability (in terms of end user as well as from our developers point of view).

Sorry, not sure how to tags this as a question.

**Comment by ktsaou** [comment]
Hi,

If OpenVZ uses cgroups (most likely it does), so yes netdata can monitor OpenVZ containers too.

If you install netdata on a host running OpenVZ containers and they don't show up, it is most likely a configuration problem. If you help me figure out the settings, I could add them to the netdata defaults so that OpenVZ containers are enabled by default.

So, to check if OpenVZ uses cgroups, open a terminal on a host with OpenVZ containers running and execute `systemd-cgtop` (run it at the host, not inside a container). If it shows your containers, netdata will be able to get them too - it might need some configuration tweaking though.

**Comment by ktsaou** [comment]
Cleaning up. If you need further help, just post here.

**Comment by yoorshop** [comment]
Hello,

I installed netdata on node openvz 7 (default with no custom anything), but in netdata, in users section, the IDs are not correct (not equal to user VPS ID, or VID)

However, i get a good an accurate ouput in this command : systemd-cgtop

I sent you report from GUI netdata quoting : https://github.com/netdata/netdata/issues/2474

Config default 👍 
# cgroups = yes

	# max cgroups to allow = 1000
	# max cgroups depth to monitor = 0
	# enable new cgroups detected at run time = yes
	# enable by default cgroups matching =  !*/init.scope  !/system.slice/run-*.scope  *.scope  /machine.slice/*.service  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.socket  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/*  !/machine  !/qemu  !/system  !/systemd  !/user  * 
	# search for cgroups in subpaths matching =  !*/init.scope  !*-qemu  !*.libvirt-qemu  !/init.scope  !/system  !/systemd  !/user  !/user.slice  !/lxc/*/*  * 
	# script to get cgroup names = /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-name.sh
	# script to get cgroup network interfaces = /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network
	# run script to rename cgroups matching =  !/  !*.mount  !*.socket  !*.partition  /machine.slice/*.service  !*.service  !*.slice  !*.swap  !*.user  !init.scope  !*.scope/vcpu*  !*.scope/emulator  *.scope  *docker*  *lxc*  *qemu*  *kubepods*  *.libvirt-qemu  * 
	# cgroups to match as systemd services =  !/system.slice/*/*.service  /system.slice/*.service 
	# enable cgroup / = no
	# search for cgroups under / = yes
	# enable cgroup user.slice = no
	# enable cgroup system.slice = no
	# search for cgroups under /system.slice = yes
	# enable cgroup system.slice/system-getty.slice = no

**Comment by yoorshop** [comment]
I just enabled for test prupose  	enable cgroup / = yes
	search for cgroups under / = yes
	enable cgroup user.slice = yes
	enable cgroup system.slice = yes
	search for cgroups under /system.slice = yes
	enable cgroup system.slice/system-getty.slice = yes

But same result....

**Comment by ktsaou** [comment]
Could you please post a couple of screenshots and mention the IDs shown by netdata, versus the right ones?

**Comment by yoorshop** [comment]
The right ones 👍

[root@vps ~]#  systemd-cgtop

Path                                                           Tasks   %CPU   Memory  Input/s Output/s

/                                                                563 1163.0    84.6G        -        -
/machine.slice                                                     - 1058.3    89.1G        -        -
/machine.slice/537                                               402  688.1    15.0G        -        -
/machine.slice/490                                                82  120.4     9.9G        -        -
/machine.slice/494                                                 3   97.3    14.1G        -        -
/machine.slice/494/system.slice                                    -   97.3     9.9G        -        -
/machine.slice/519                                                95   80.5     7.3G        -        -
/system.slice                                                     60   29.5     4.4G        -        -
/machine.slice/521                                                54   28.6     1.9G        -        -
/machine.slice/503                                                42   25.0     1.4G        -        -
/user.slice                                                        3    6.6   358.0M        -        -
/machine.slice/496                                                 3    4.1     5.9G        -        -
/machine.slice/496/system.slice                                    -    4.0     3.2G        -        -
/machine.slice/531                                                63    2.8     7.7G        -        -
/machine.slice/522                                                25    1.8     1.2G        -        -
/machine.slice/504                                                25    1.3     2.1G        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope                   2    0.8     1.1G        -        -
/machine.slice/498                                                16    0.8   114.8M        -        -
/machine.slice/512                                                 9    0.8    46.4M        -        -
/machine.slice/502                                                56    0.5   736.1M        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope/vcpu3             1    0.2        -        -        -
/machine.slice/509                                                29    0.2     1.9G        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope/vcpu5             1    0.2        -        -        -
/machine.slice/514                                                53    0.2     3.7G        -        -
/machine.slice/513                                                29    0.2   238.2M        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope/vcpu4             1    0.1        -        -        -
/machine.slice/491                                                 2    0.1   768.4M        -        -
/machine.slice/491/system.slice                                    -    0.1   296.7M        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope/vcpu2             1    0.1        -        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope/vcpu1             1    0.1        -        -        -
/machine.slice/511                                                29    0.1     5.1G        -        -
/machine.slice/515                                                27    0.0   189.1M        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope/vcpu0             1    0.0        -        -        -
/machine.slice/516                                                20    0.0   163.0M        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope/vcpu7             1    0.0        -        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope/vcpu6             1    0.0        -        -        -
/machine.slice/523                                                22    0.0    98.2M        -        -
/machine.slice/505                                                22    0.0    93.7M        -        -
/machine.slice/527                                                22    0.0   350.9M        -        -
/machine.slice/machine-qemu\x2d26\x2dv1004.scope/emulator          2    0.0        -        -        -
/machine.slice/529                                                22    0.0    93.2M        -        -
/machine.slice/506                                                20    0.0    87.3M        -        -
/machine.slice/530                                                26    0.0   136.9M        -        -
/machine.slice/532                                                30    0.0   388.0M        -        -
/machine.slice/487                                                16    0.0   341.7M        -        -
/machine.slice/488                                                31    0.0     2.0G        -        -
/machine.slice/486                                                12    0.0   314.1M        -        -
/machine.slice/517 

Netdata shows PID process numbers instead, no relation with VM ID or VID

I'm unable to copy ouput of netdat by copy paste

**Comment by ktsaou** [comment]
This is what netdata does to get the container names: https://github.com/netdata/netdata/blob/29e52f92b6b3dcb1988cf67ea93fd57c42987ce7/collectors/cgroups.plugin/cgroup-name.sh.in#L167-L188

Can you check it?

You should be able to run this script by hand, providing one the cgroup path as parameter.

**Comment by yoorshop** [comment]
Re,

The container config files are in /etc/vz/conf and the virtualization 
type is OpenVZ (7) and not LXC

Basically, the code is catering to Proxmox only and you should patch it 
to add support for OpenVZ containers too
>

**Comment by ktsaou** [comment]
Unfortunately I don't have access to OpenVZ.
Can you provide the commands to get the container name, given the path to a cgroup?

**Comment by yoorshop** [comment]
############################
For cgroup /machine.slice/585

]# grep HOSTNAME /etc/vz/conf/485.conf
HOSTNAME="xyz.example.com"
############################

**Comment by ktsaou** [comment]
For cgroup `585` you used file `485.conf`?

**Comment by yoorshop** [comment]
sorry typo mistake on last answer :

modified :

############################
For cgroup /machine.slice/485

]# grep HOSTNAME /etc/vz/conf/485.conf
HOSTNAME="xyz.example.com"
############################

**Comment by ktsaou** [comment]
I created PR #4909 with this fix.
Can you try it?

**Comment by cakrit** [comment]
This shouldn't have been closed, it's because it was incorrectly marked as a question. Reopening.

**Comment by cakrit** [comment]
@vlvkobal check the linked PR, it contains feedback on some changes @ktsaou had made, trying to get this working.

**Comment by ilyam8** [comment]
hey @yoorshop 

> I installed netdata on node openvz 7 (default with no custom anything), but in netdata, in users section, the IDs are not correct (not equal to user VPS ID, or VID)

Are you still using openVZ? If so please share a screenshot. It is not clear what that _users section_ you are referring to.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
