### ISSUE TITLE
FreeSwitch Monitoring

### ISSUE THREAD

**Issue by hmmxp** [netdata/netdata#2495]
Dear All,

Are there available plugins to monitor FreeSwitch environment and do call quality monitoring like MOS?

Thank You In Advance

**Comment by ktsaou** [comment]
Not currently.

I see that [MOS can be monitored](https://github.com/chanon-m/Call-Quality-Monitoring/blob/master/mos.pl) if you place freeswitch CDRs to a database and query that database.

This is can be pretty simple to do with a custom python or a BASH plugin in netdata.

**Comment by ketan-kothari** [comment]
@ktsaou 

When can we expect FreeSWITCH plugin?  In waiting for it.

**Comment by ktsaou** [comment]
Hi,

for a plugin to be implemented, these are the steps:

1. find the data source and the way to connect to it
2. find the useful info and group collected metrics in charts and dimensions, ensuring the result will be meaningful
3. implement the code to do it
4. test it
5. document it (wiki page, information on the dashboard, hooks at various places to let other people we support this plugin, etc)
6. support other people willing to use this plugin

Point No 3 (the code) is just a small percentage of the work to be done. @l2isbad, me and probably more people can take care of it (it is not that hard, if you know what you need to do).

So, if you really need this plugin, I suggest to take care of all the points except 3, i.e. become a sponsor of the freeswitch plugin. We will glad to implement it asap.

**Comment by cakrit** [comment]
Hi @hmmxp and @ketan-kothari 

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

Would one of you be willing/able to play this role?

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by badcrc** [comment]
Hi,

I've made a plugin for getting metrics from FreeSwitch, we are using it to get the number of registrations and active calls. 

Seems to be stable (I've it running on several servers for some months now). 

I'll try to make a PR this week so someone can review it. I'll need some help with the alarms as we don't use netdata's alarm system.

**Comment by EnzoAkira** [comment]
> Hi,
> 
> I've made a plugin for getting metrics from FreeSwitch, we are using it to get the number of registrations and active calls.
> 
> Seems to be stable (I've it running on several servers for some months now).
> 
> I'll try to make a PR this week so someone can review it. I'll need some help with the alarms as we don't use netdata's alarm system.

Hi there! 
I can help you with the alarms if you want! And in return, you help me implement your plugin (we also used freeswicth and we had plans to develop a pluing)

**Comment by ilyam8** [comment]
Closing this feature request and moving it to [our community forum](https://community.netdata.cloud/) for further discussion (link will be posted soon).
