### ISSUE TITLE
add temperature gauges

### ISSUE THREAD

**Issue by ccremer** [netdata/netdata#2550]
It would be nice to have temperature gauges for custom dashboards.

A quick google search yields the following results as for possible libraries
* [jQuery TempGauge](https://github.com/akumagamo/jquery-plugin-tempgauge)
* [Fusion charts Thermometer Gauge](http://www.fusioncharts.com/dev/gauge-and-widgets-guide/thermometer-gauge/introduction.html)

What do you think?

**Comment by paulfantom** [comment]
I don't agree with this. Netdata is a software for generic systems monitoring not for HVAC. If we start adding things like specialized gauges for temperature, there will be an influx of other requests to add other specialized ways to display graphs.

**Comment by ccremer** [comment]
It's ok, I don't need it anymore. Still, I think a generic vertical and/or horizontal bar with color gradients would be enough. I know we could use gauges, but a little "change of scene" is appreciated. Right now, all charts are either gauges, dygraph or easypiechart.

Philosophical question: Why saying netdata's not for HVAC if there already a number of modules specifically for this: sma_webbox, fronius, stiebeleltron.
There's also spigotmc, which is for monitoring minecraft.

Closing it as I won't be the one implementing it.
