### ISSUE TITLE
Implement web caching for static ressources

### ISSUE THREAD

**Issue by Komic** [netdata/netdata#2553]
(My apologies if the following is that way by design)
Currently, netdata will always answer requests with a 200 and the full content. This is of course fine for the API, however serving a `Last-Modified` and/or `ETag` header and implementing the 304 Not Modified HTTP status accordingly could improve the user experience.
Alternatively, and possibly a simpler implementation, netdata could generate unique filenames for static content during deployment, and simply serve a `public, max-age=31536000, immutable` header.

**Comment by ktsaou** [comment]
Hi,

netdata responds with 2 types of responses:

1. cache-able, ie static content

    It adds `Cache-Control: public` and sets `Expires: DATE` (normally 86400 seconds from now)

2. not-cache-able, ie dynamic content (chart data)

   It adds `Cache-Control: no-cache` and sets `Expires: DATE` (normally to the update frequency of the content in question, ie the update frequency of the chart data).

I understand the current implementation is very basic.
So, yes this should be enhanced a bit.

**Comment by Komic** [comment]
I actually managed to miss the current header somehow. If you think a more advanced implementation is relevant I'll leave this open though.

**Comment by gmosx** [comment]
This is an issue of the daemon (web server) not the GUI.

**Comment by amoss** [comment]
It appears that the easy case is (1) above, setting `Last-Modified` to the file creation date and then checking for `If-Modified-Since` or `If-None-Match` to allow the 304 response. 

Is there anything else would be useful here?

**Comment by amoss** [comment]
I had a closer look at this and the code in web_client.c is easy to change, but it does not seem to be necessary. With the existing cache headers there are no requests being sent to the server that would generate 304s. 

![screen](https://user-images.githubusercontent.com/1043609/63944339-a03d5500-ca71-11e9-92be-245f20c717c3.jpg)

Are there more specific enhancements that should be made to the handling of static content, or should the issue be closed?

**Comment by cakrit** [comment]
Closing and will reopen if anyone else thinks we need to do something different here. Thanks @amoss!
