### ISSUE TITLE
Feature Request: Linux zram device statistics.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#2578]
Linux has support for transparently compressed RAM disks usually called zram devices.  Most major distros support this (although it's a loadable module).  The inner workings of the driver are actually somewhat ingenious and make it very well suited to use as swap space.  In short, for each page that gets written to the device, the page gets compressed (using LZO by default, but LZ4 is also supported), and then stored.  Space for storage is allocated on-demand, and the devices also support the DISCARD ioctl, so it can be freed on-demand too.

Because the allocations are done on-demand, the compression ratio varies (I see anywhere from 0.5 to about 0.2 depending on what's being stored), and there is the possibility of deduplication in the works upstream, tracking memory usage of zram devices is currently non-trivial.

Currently, netdata sees them as regular disks, and tracks regular disk utilization metrics.  It would be really awesome if netdata could also track things like actual memory usage, compression ratio, and stored data.  Unfortunately, I'm not 100% certain how the zramctl command finds this data (there are sysfs files for total device size and currently stored data, but not exact memory usage or the compressed size of the data as far as I can tell).  From what I can tell, it looks like 252 is the standard block major number of zram devices, but I'm not certain on that either (there isn't one officially listed upstream as reserved for zram devices).

Unfortunately, I don't have the time at the moment to dig much further into this myself, so I'm hoping that somebody with some interest and more time (and possibly more experience with netdata coding) than me might be able to pick this up.

**Comment by ktsaou** [comment]
According to https://www.kernel.org/doc/Documentation/blockdev/zram.txt

The file `/sys/block/zram<id>/mm_stat` has all the info you need:

```
The stat file represents device's mm statistics. It consists of a single
line of text and contains the following stats separated by whitespace:
 orig_data_size   uncompressed size of data stored in this disk.
		  This excludes same-element-filled pages (same_pages) since
		  no memory is allocated for them.
                  Unit: bytes
 compr_data_size  compressed size of data stored in this disk
 mem_used_total   the amount of memory allocated for this disk. This
                  includes allocator fragmentation and metadata overhead,
                  allocated for this disk. So, allocator space efficiency
                  can be calculated using compr_data_size and this statistic.
                  Unit: bytes
 mem_limit        the maximum amount of memory ZRAM can use to store
                  the compressed data
 mem_used_max     the maximum amount of memory zram have consumed to
                  store the data
 same_pages       the number of same element filled pages written to this disk.
                  No memory is allocated for such pages.
```

**Comment by ktsaou** [comment]
Also `/proc/devices` has a map of devices and major device numbers.

**Comment by Ferroin** [comment]
Can't believe I forgot about `/proc/devices` and didn't think to read the kernel documentation...

Given that, I might have some time to work on this myself in the near future.

**Comment by mikebkk** [comment]
### BUG IN zram.sh? Here is what I did
After following the setup-instructions there was no effect so I had to modify /usr/bin/zram.sh to make it work on a Raspberry 2B, **replacing** 'let' and using 'bc + scale' in the bash calculation

**cat /proc/cpuinfo:**
Hardware: BCM2835, Revision: 1a01041

**cat /sys/firmware/devicetree/base/model:**
Raspberry Pi 2 Model B Rev 1.1

**cat /usr/bin/zram.sh:**
```#!/bin/bash
cores=$(nproc --all)
modprobe zram num_devices=$cores
swapoff -a
totalmem=`free | grep -e "^Mem:" | awk '{print $2}'`
mem=$(echo "scale=0;2048*($totalmem/$cores)" | bc)
# I doubled the default value 1024 , with that default setting Chromium-browser was dragging!
# zram.sh creates 4 x 463 MiB with this setting
core=0
while [ $core -lt $cores ]; do
    echo $mem > /sys/block/zram$core/disksize
    mkswap /dev/zram$core
    swapon -p 5 /dev/zram$core
    core=$((core+1))
done
```
___________________________________________
**MY SYSTEM**
Stretch 4.14.79-v7+
KDE Plasma 5.8.6
**special settings**
core_freq=500
sdram_freq=500
over_voltage=2
gpu-mem commented
dtoverlay=vc4-fkms-v3d and Opengl selected in KDE

- All settings in /etc/dphys-swapfile commented
- /etc/init.d/dphys-swapfile removed.
- /etc/X11/Xsession modified 
    exec **>>**"$ERRFILE" 2>&1 in exec **>**"$ERRFILE" 2>&1
- chromium-browser, hardware acceleration disabled

Hardware:
powered USB-hub with
- Internet via Edimax to a hotspot, driver 8192cu
- AP with TP-Link TL-WN 725N , driver 8188eu
- 2 USB-Drives, most partitions ext4, one partition ntfs for Windows-backups
- Raspicomm with RealTimeClock

Software
Samba, Apache and isc-dhcp-server
mysql, phpmyadmin, mariadb
SSH
Bluetooth

I have to admit that the setup was kind of trial and error and took time. Getting KDE running was quite demanding but it is fully operational now. For some weeks the system runs stable.
The internet speed is not breathtaking but I care more about reliability and accessibility.

These hints may others help to save some time
