### ISSUE TITLE
InfiniBand monitoring

### ISSUE THREAD

**Issue by bkovalev** [netdata/netdata#2620]
Can I monitor InfiniBand traffic and how ?

**Comment by ktsaou** [comment]
Can you get the traffic with a command line tool?
Please post the command and sample output here. Most probably you can easily turn this into a chart.

**Comment by ktsaou** [comment]
Cleaning up. If you need this implemented, you will have to help us a bit. We don't have access to infiband to develop this.

**Comment by diched** [comment]
perfquery would be the command-line tool to collect information on (certain) infiniband cards. 
Can this be implemented in netdata ?

**Comment by ilyam8** [comment]
@diched i think yes

 - do we need root privileges to invoke `perfquery`?
 - i see it has [a lot of counters](https://linux.die.net/man/8/perfquery), which do you think are most important? (i guess `-e show send and receive errors (timeouts and others)` ?)
 - please share the output of `perfquery ...`
 - please do `time perfquery ...`

___ 
all perf query counters

https://github.com/weiny2/infiniband-diags/blob/de6c39715552254e56fecae75fdcedf68f1677c1/src/perfquery.c#L55-L105

**Comment by diched** [comment]
thanks for quick response!
- root privileges are required AFAIK (I assume netdata user can be added to a certain group with special privileges)
- I guess -e is a good start, for monitoring in general I personally would be interested in all counters that start with "Port*" 
- here's the output of time perfquery -v :

# Port counters: Lid 21 port 1 (CapMask: 0x1600)
PortSelect:......................1
CounterSelect:...................0x0000
SymbolErrorCounter:..............0
LinkErrorRecoveryCounter:........0
LinkDownedCounter:...............0
PortRcvErrors:...................0
PortRcvRemotePhysicalErrors:.....0
PortRcvSwitchRelayErrors:........0
PortXmitDiscards:................0
PortXmitConstraintErrors:........0
PortRcvConstraintErrors:.........0
CounterSelect2:..................0x00
LocalLinkIntegrityErrors:........0
ExcessiveBufferOverrunErrors:....0
VL15Dropped:.....................0
PortXmitData:....................4294967295
PortRcvData:.....................4294967295
PortXmitPkts:....................1019153937
PortRcvPkts:.....................1876526258
PortXmitWait:....................19078

real    0m0.085s
user    0m0.004s
sys     0m0.017s

**Comment by ilyam8** [comment]
> I personally would be interested in all counters that start with "Port*"

Port* from the source code

```
26 ilyam:~ $ grep -E -o ' "Port[^ ,]+' perfquery.c
 "PortXmitDataSL"
 "PortRcvDataSL"
 "PortXmitDiscardDetails"
 "PortRcvErrorDetails"
 "PortExtendedSpeedsCounters
 "PortExtendedSpeedsCounters"
 "PortOpRcvCounters"
 "PortFlowCtlCounters"
 "PortVLOpPackets"
 "PortVLOpData"
 "PortVLXmitFlowCtlUpdateErrors"
 "PortVLXmitWaitCounters"
 "PortRcvConCtrl"
 "PortSLRcvFECN"
 "PortSLRcvBECN"
 "PortXmitConCtrl"
 "PortVLXmitTimeCong"
```

Please check the man and choose all options we need to get Port* metrics

**Comment by diched** [comment]
I'm not sure such options exist. I used to grep stuff I'm interested in, which would be roughly the following:

PortXmitData:....................10023793673
PortRcvData:.....................1830252451427
PortXmitPkts:....................1035481804
PortRcvPkts:.....................1907513711
PortUnicastXmitPkts:.............1035481858
PortUnicastRcvPkts:..............1907508762
PortMulticastXmitPkts:...........40
PortMulticastRcvPkts:............4936
PortRcvErrors:...................0
PortXmitDiscards:................0

A snippet from man page, possibly important:

> Note: In PortCounters, PortCountersExtended, PortXmitDataSL, and PortRcvDataSL, components that represent Data (e.g. PortXmitData and PortRcvData) indicate octets divided by 4 rather than just octets.

**Comment by ilyam8** [comment]
> https://linux.die.net/man/8/perfquery

> -x, --extended
show extended port counters rather than (basic) port counters. Note that extended port counters attribute is optional.
-X, --xmtsl
show transmit data SL counter. This is an optional counter for QoS.
-S, --rcvsl
show receive data SL counter. This is an optional counter for QoS.
-D, --xmtdisc
show transmit discard details. This is an optional counter.
-E, --rcverr
show receive error details. This is an optional counter.
-D, --xmtdisc
show transmit discard details. This is an optional counter.
-T, --extended_speeds
show extended speeds port counters. This is an optional counter.
--oprcvcounters
show Rcv Counters per Op code. This is an optional counter.
--flowctlcounters
show flow control counters. This is an optional counter.
--vloppackets
show packets received per Op code per VL. This is an optional counter.
--vlopdata
show data received per Op code per VL. This is an optional counter.
--vlxmitflowctlerrors
show flow control update errors per VL. This is an optional counter.
--vlxmitcounters
show ticks waiting to transmit counters per VL. This is an optional counter.
--swportvlcong
show sw port VL congestion. This is an optional counter.
--rcvcc
show Rcv congestion control counters. This is an optional counter.
--slrcvfecn
show SL Rcv FECN counters. This is an optional counter.
--slrcvbecn
show SL Rcv BECN counters. This is an optional counter.
--xmitcc
show Xmit congestion control counters. This is an optional counter.
--vlxmittimecc
show VL Xmit Time congestion control counters. This is an optional counter.

**Comment by ilyam8** [comment]
> PortXmitData:....................10023793673
PortRcvData:.....................1830252451427
PortXmitPkts:....................1035481804
PortRcvPkts:.....................1907513711
PortUnicastXmitPkts:.............1035481858
PortUnicastRcvPkts:..............1907508762
PortMulticastXmitPkts:...........40
PortMulticastRcvPkts:............4936
PortRcvErrors:...................0
PortXmitDiscards:................0

So we have these counter w/o any option? just `perfquery`?

**Comment by diched** [comment]
-e -x should do

**Comment by ilyam8** [comment]
> -e -x should do

ok, please do `time perfquery -e -x` and share the output

**Comment by diched** [comment]
real    0m0.093s
user    0m0.003s
sys     0m0.017s

**Comment by ilyam8** [comment]
Well, where is data? 😅

like there (from `perfquery -v`)
> https://github.com/netdata/netdata/issues/2620#issuecomment-521940929

**Comment by diched** [comment]
# Port extended counters: Lid 21 port 1 (CapMask: 0x1600 CapMask2:
0x0000000)
PortSelect:......................1
CounterSelect:...................0x0000
PortXmitData:....................13672645927
PortRcvData:.....................2341975277576
PortXmitPkts:....................1352112415
PortRcvPkts:.....................2467501178
PortUnicastXmitPkts:.............1352112493
PortUnicastRcvPkts:..............2467494386
PortMulticastXmitPkts:...........40
PortMulticastRcvPkts:............6779
CounterSelect2:..................0x00000000
SymbolErrorCounter:..............0
LinkErrorRecoveryCounter:........0
LinkDownedCounter:...............0
PortRcvErrors:...................0
PortRcvRemotePhysicalErrors:.....0
PortRcvSwitchRelayErrors:........0
PortXmitDiscards:................0
PortXmitConstraintErrors:........0
PortRcvConstraintErrors:.........0
LocalLinkIntegrityErrors:........0
ExcessiveBufferOverrunErrors:....0
VL15Dropped:.....................0
PortXmitWait:....................0
QP1Dropped:......................0

real    0m0.085s
user    0m0.000s
sys     0m0.020s

**Comment by ilyam8** [comment]
@diched we need per port statistics and not summary, right?

**Comment by ilyam8** [comment]
@diched i see in the [man](https://linux.die.net/man/8/perfquery)

> When no IB device or port is specified, the port to use is selected by the following criteria:

> 1. the first port that is ACTIVE.

> 2. if not found, the first port that is UP (physical link up).

> If a port and/or CA name is specified, the user request is attempted to be fulfilled, and will fail if it is not possible.

it looks like `perfquery -e -x` is not enough. What do you think?

**Comment by diched** [comment]
Hi Ilya,

Sorry, can't tell, lack of expertise in that field. Basically my intention
was to monitor the traffic through the interface in a nice convenient
netdata way. Otherwise one can of course pipe it to grafana, too...
I will however be glad to act as a test user!

Cheers
Eduard

**Comment by ilyam8** [comment]
I see there are 2 options:
 - retrieve summary statistics

> Providing a port value of 255 ensures that the operation is performed on all ports.

 - retrieve per lid per port statistics

>  perfquery 24 8
  Port counters: Lid 24 port 8
PortSelect:......................8
CounterSelect:...................0x1b01
SymbolErrors:....................0
LinkRecovers:....................0
LinkDowned:......................0
RcvErrors:.......................0
RcvRemotePhysErrors:.............0
RcvSwRelayErrors:................0
XmtDiscards:.....................0
XmtConstraintErrors:.............0
RcvConstraintErrors:.............0
LinkIntegrityErrors:.............0
ExcBufOverrunErrors:.............0
VL15Dropped:.....................0
XmtData:.........................75384
RcvData:.........................87696
XmtPkts:.........................1047
RcvPkts:.........................1218

___

If we use `perfquery` thing w/o specific lid/port   

> When no IB device or port is specified, the port to use is selected by the following criteria:
> - the first port that is ACTIVE.
> - if not found, the first port that is UP (physical link up).


I am trying to understand what parameters we need.

Since you have this thing please do some research how it works:
 - w/o lid/port
 - is it possible to retrieve data for several ports in one query

**Comment by diched** [comment]
Hi,



On Wed, Aug 21, 2019 at 9:37 AM Ilya Mashchenko <notifications@github.com>
wrote:

> I see there are 2 options:
>
>    - retrieve summary statistics
>
> Providing a port value of 255 ensures that the operation is performed on
> all ports.
>
> When I specify port 255 it complains with
perfquery: iberror: failed: AllPortSelect not supported
the -a option however that is expected to provide aggregated statistics
does the job. I can't however tell exactly if that's correct or not as we
use only one (physical) port - I realized there's a heavy misuse of the
word "port" in this context...

>
>    - retrieve per lid per port statistics
>
> perfquery 24 8
> Port counters: Lid 24 port 8
> PortSelect:......................8
> CounterSelect:...................0x1b01
> SymbolErrors:....................0
> LinkRecovers:....................0
> LinkDowned:......................0
> RcvErrors:.......................0
> RcvRemotePhysErrors:.............0
> RcvSwRelayErrors:................0
> XmtDiscards:.....................0
> XmtConstraintErrors:.............0
> RcvConstraintErrors:.............0
> LinkIntegrityErrors:.............0
> ExcBufOverrunErrors:.............0
> VL15Dropped:.....................0
> XmtData:.........................75384
> RcvData:.........................87696
> XmtPkts:.........................1047
> RcvPkts:.........................1218
>
> ------------------------------
>
> If we use perfquery thing w/o specific lid/port
>
> When no IB device or port is specified, the port to use is selected by the
> following criteria:
>
>    - the first port that is ACTIVE.
>    - if not found, the first port that is UP (physical link up).
>
> I am trying to understand what parameters we need.
>
> Since you have this thing please do some research how it works:
>
>    - w/o lid/port
>
> Without lid/port (aka perfquery -e -x) it returns the values for lid 21
port 1. I can change the lids (aka perfquery -e -x 1 1) within the range
1..45 (with some gaps), keeping the port=1, everytime receiving different
values for transmitted/received data.


>
>    - is it possible to retrieve data for several ports in one query
>
> Several ports apparently should be doable (either with -a option or
specifying a port list or range with "perfquery 1 1-10" - this fails for me
as port can only be one in my setup apparently), several lids - no.

Seems more complicated than I thought :(

**Comment by ilyam8** [comment]
Yes, it is not that simple. I found that `collectl` support infiniband monitoring

> http://collectl.sourceforge.net/Infiniband.html

It looks like it uses `perfquery` and reads some stuff from `/sys/class/infiniband`

> The OFED stack can be identified by the presence of the /sys/class/infiniband directory. If there, collectl looks inside to find which HCAs are present and which ports are active. This information is then used to query the HCA via the perfquery utility.

**Comment by ilyam8** [comment]
https://github.com/influxdata/telegraf/pull/6631

**Comment by cakrit** [comment]
I'm not sure on what the next action is here. Let's discuss and decide how we proceed.

**Comment by ilyam8** [comment]
I see there a way to collect metrics w/o `perfquery` tool

Devices can be found in:

- /sys/class/infiniband/

Their metrics:

- `/sys/class/infiniband/<dev>/<port>/hw_counters`
- /`sys/class/infiniband/<dev>/<port>/counters`

**Comment by ilyam8** [comment]
Looks like we need an internal plugin.

**Comment by Saruspete** [comment]
Greetings everyone !

I need this feature. Is any work already in progress, or may I start working on it ?

Cheers

**Comment by amoss** [comment]
Hi, nobody on the team is currently scheduled to work on this and we would love to see a contribution here.

**Comment by Saruspete** [comment]
Perfect, I've started working on it, based on `proc.plugin/proc_net_dev.c`.

From `Documentation/infiniband/sysfs.txt`, there's no procfile that would list the interfaces, so I got to list folders in `/sys/class/infiniband/`. Is there any helper to do so, like `procfile_open`, or do we need to do the glob/opendir ?

**Comment by ilyam8** [comment]
@Saruspete 

i dont know if it helps but there is a go lib to get infiband metrics

https://github.com/Mellanox/rdmamap

**Comment by Saruspete** [comment]
Nice find @ilyam8 ! Seems this lib is scanning the /sys/class/infiniband/ path too. It uses the same place & uint64 as i did (put kernel struct' reference in the code for completeness):
```
	HwStats []RdmaStatEntry /* /sys/class/infiniband/<dev>/<port>/hw_counters */
	Stats   []RdmaStatEntry /* /sys/class/infiniband/<dev>/<port>/counters */
```

I was hoping to find some mapping & detail about the metrics, but it's just plain values, no hint / naming.

Currently, the PR provides parsing for "counters". Link speed & "hw_counters" still need to be done. Checking the kernel drivers of different vendors to see common patterns and generation.

**Comment by Saruspete** [comment]
Greetings,

Would some people interested here to test the PR on their hardware, and give me some feedback ?

Thanks,

**Comment by diched** [comment]
Hi Adrien,

I could do it, sure.
Please send me instructions what to install and how.

Cheers
Eduard

**Comment by ilyam8** [comment]
@diched 

you need to intall `Saruspete:collector_infiniband` branch

```cmd
git clone https://github.com/Saruspete/netdata --branch collector_infiniband netdata_infiniband

cd  netdata_infiniband

<install>
```

**Comment by Saruspete** [comment]
I've tested with a 2 ports 

@diched : The full command list for local installation (in `/opt/netdata.ib` for testing) would be:

```
# Clone repo
git clone https://github.com/Saruspete/netdata --branch collector_infiniband netdata_infiniband
cd  netdata_infiniband
# Configure and compile
autoreconf -ivf
./configure --prefix /opt/netdata.ib
sudo make install
# Copy service script for auto-startup
sudo cp system/netdata.service /usr/lib/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable --now netdata.service
```

Should be ok

**Comment by ilyam8** [comment]
thx @Saruspete
