### ISSUE TITLE
[question] Screen updates on non default zoom

### ISSUE THREAD

**Issue by alekc** [netdata/netdata#2631]
A bit of a duplicate of https://github.com/firehol/netdata/issues/1124

@ktsaou a year ago you said 

> When you pan or zoom the charts, automatic refreshing stops. This is by design.
> 
> When the dashboard starts, it calculates the maximum visible duration of the charts by giving 3 pixels width per point and per second refreshes.
> 
> If you start full screen and then resize the window horizontally, the dashboard will request from the netdata server to reduce the data (i.e. combine several points together), maintaining 3 pixes per point, the same visible duration, but lower update frequency (it will still have auto-refreshing on, but at a lower rate - since it would be meaningless to do shorter updates).
> 
> What would be nice, is a global menu to set the visible duration of the charts, e.g. auto (the one we have now), 5min, 10min, 15min, 30min, 1hour, etc in auto-refreshing mode

Regarding the point of global menu, was that idea abandoned or implemented in a different way?
It would be nice indeed to have a similar system to graylog time periods with predefined values

![image](https://user-images.githubusercontent.com/302807/29713965-ed27394c-8998-11e7-9d6b-7f919bb9e65b.png)

like 

- 15 min 1 sec update
- 60 min 5 sec update
- etc

**Comment by ktsaou** [comment]
> Regarding the point of global menu, was that idea abandoned or implemented in a different way

No it is not abandoned. It was just a crazy year... too many features added... too many yet to come...

I like your proposal. Something like this is indeed what is needed.

**Comment by ktsaou** [comment]
@gmosx 	this is on our roadmap

**Comment by ilyam8** [comment]
> What would be nice, is a global menu to set the visible duration of the charts, e.g. auto (the one we have now), 5min, 10min, 15min, 30min, 1hour, etc in auto-refreshing mode

Implemented.
