### ISSUE TITLE
Use libuv, for performance and portability

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#2637]
Today, netdata is heavily dependant on Posix threads, locks, socket I/O, etc.

We could replace all this code with libuv (https://github.com/libuv/libuv). libuv is used by node.js and is highly portable.

This means porting netdata to more operating systems (like Windows) will be a lot easier.

Also, since libuv is highly optimized on each operating system, netdata will also be faster.

**Comment by ktsaou** [comment]
@cakrit 	this is required for porting netdata to windows.

**Comment by cakrit** [comment]
No one to pick it up right now, leaving it on me until we get someone to work on windows support.

**Comment by ktsaou** [comment]
I just found this: https://github.com/h2o/h2o/

It is an http 1.1 and http2 web server, which also uses libuv when it is built as a library. It also supports SSL/TLS. Licensed under MIT.

Too good to be true. We could drop the internal web server(s) entirely, and at the same time gain SSL/TLS, http2 support and move to libuv !

**Comment by ktsaou** [comment]
It also supports websocket...

**Comment by Ferroin** [comment]
We might have to change the streaming protocol to support it though, but that might not be a bad thing (making the streaming use websockets or real HTTP would be awesome).

**Comment by paulfantom** [comment]
> making the streaming use websockets or real HTTP would be awesome

I couldn't agree more!

**Comment by cakrit** [comment]
I read a bit about h2o/h2o and it does seem like the way to go. It will require a major rewrite, but it will be worth it.

**Comment by ktsaou** [comment]
The `static` web server should not be that hard to be ported. It is already implemented with an event loop and the functions may change significantly, but the logic is pretty close.
