### ISSUE TITLE
New documentation [bounty]

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#2638]
Netdata has grown quite a lot. It needs better documentation.

## why bother?

Documentation serves quite a few purposes:

1. Describe the feature set - let the users know what they can do with netdata.

2. Give step-by-step instructions on how to achieve things, describe all options available and their meaning.

3. Educate sysadmins / devops on monitoring their systems and applications.

4. Give SEO juice to netdata, which is required for growing the netdata community faster.

Unfortunately this task to too big for me. I know that even if someone else handles this, I will spend quite some time on it, so I prefer to **hire a technical writer** to handle all the details. Of course, I will supervise the task and ensure the result is of high quality.

## so what?

_**I am donating 1000 Euro to netdata for this cause**_. I know the task is bigger than that, but I hope more people will join in and donate money.

So, if you are a professional technical writer, or a student willing to get hands-on experience in technical writing (I will mentor you), post here.

If you want to donate money for this cause, post too. If there are many donations, I'll setup an account somewhere to track them.

If you know someone who might be willing to handle this task, please spread the word.

## Donations so far

who | how much
----|--------
@ktsaou | 1000 Euro

Come one guys... will I be left alone?

## Contributors so far

who | paid or free | role | time allocated
:--:|:------------:|-----|-------
@ktsaou| free | review docs, help authors, extract info from code, test things, etc. | 10h per week
@5car1z|flexible|write, proofread, editing, writing best practices|10h per week
@hmmxp|paid|write, proofread|12h per week
@kmonsoor|paid|proofreading, editing, testing|??

Can you help? **Join the team!**

---

For those wondering: netdata is not backed up by a company. It is purely community based and there is no revenue direct or indirect related to it. I created it and maintain it, and several folks have contributed significant parts of it (e.g. the python part is entirely not mine, it was started by @paulfantom and has been significantly extended and now maintained by @l2isbad. Freebsd and macOS support has been entirely written by @vlvkobal, etc ). 

**netdata is and will always be free, open-source software**. We all have a leaving, without netdata. But, as the project matures and the amount of work required is above our strengths, it is important to find ways to deliver better results, faster. This bounty in exactly that. Get better documentation, faster.

So, if you would like to have better netdata documentation, support this cause...

**Comment by hmmxp** [comment]
Can I help?

**Comment by ktsaou** [comment]
> Can I help?

Of course. Are you interested in undertaking the whole of it? It would be helpful to present yourself and your skills a bit so that I can combine the skills and the time of the folks willing to help.

**Comment by hmmxp** [comment]
I am a self proclaimed geek who is interested to research and learn new technology, i have some experience in Linux, Windows Server, VMware. My day job is as a system adminsitrator

But my willingness to learn, write and to help others is my strength which i find that through writing or editing technical document it will not only enhance my technical skill set but can others as well

**Comment by ktsaou** [comment]
> But my willingness to learn, write and to help others is my strength which i find that through writing or editing technical document it will not only enhance my technical skill set but can others as well

That is very nice!

So, would you like to prepare a scope of work while waiting for others to join?

**Comment by ktsaou** [comment]
> So, would you like to prepare a scope of work while waiting for others to join?

What I mean, is that I have a few ideas on how to organize it, but before discussing them, I would prefer to know your thoughts. How do you believe we can organize netdata documentation to help users the most?

**Comment by nixcraft** [comment]
You should use wiki software (mediawiki) so that everyone can collaborate. Not everyone understand git. mediawiki is perfect for SEO and other stuff.

**Comment by ktsaou** [comment]
Thanks @nixcraft !

The github wiki of netdata is open for anyone to edit. But still, documentation is not homogeneous and generally sub-optimal. It needs a re-organization.

**Comment by hmmxp** [comment]
My Suggestion Is To Use GitBook and Re-Organize The Entire Documentation Into The Following

1. Introduction (What Is NetData, Architecture etc.)
2. Installation
3. Plugins
4. Tutorials (Tutorials relating to configuration, tuning netdata etc.)
5. Development (Extending NetData,  API etc.)
6. Practical Experience (Area for users to share expereince etc.)

**Comment by Ferroin** [comment]
Even without GitBook, that's probably the best way to organize things.

**Comment by 5car1z** [comment]
I wrote the [Digital Ocean article on Netdata](https://www.digitalocean.com/community/tutorials/how-to-set-up-real-time-performance-monitoring-with-netdata-on-ubuntu-16-04) at the end of last year. If you liked the way this was presented and written, I'd be happy to help write some of the content in the new wiki/docs. 

Although I must admit I haven't used Netdata that much since the article, but I could probably get back into working with it - if I ended up contributing. 

I can at least help with proofreading, editing, and writing best practices if you like. 

Also GitBook seems like a nice choice.  :+1:

**Comment by kmonsoor** [comment]
I'd like to request to have a look at the docs of InfluxData ( [InfluxDB](https://docs.influxdata.com/influxdb/), Chronograf etc.). The docs repo is on Github: https://github.com/influxdata/docs.influxdata.com

The docs are statically built on [Hugo](https://gohugo.io/) and the output(final site) looks amazing.

**Comment by ktsaou** [comment]
@5car1z nice! Of course you can help. Thank you for that article too. It is great!

@kmonsoor thanks! However, I suggest to focus first on the content itself. Most of these tools use markdown, so I guess we will be able to switch tools easily.

---

I have updated the description with this:

## Donations so far

who | how much
----|--------
@ktsaou | 1000 Euros

Come one guys... will I be left alone?

## Contributors so far

who | paid or free | role | time allocated
:--:|:------------:|-----|-------
@ktsaou| free | review docs, help authors, extract info from code, test things, etc. | 10h per week
@hmmxp|paid|author|???
@5car1z|paid|author, or proofreading, editing, writing best practices|???

Can you help? **Join the team!**

---

@hmmxp and @5car1z please review it and fill the gaps.

I think this project will be quite big. I am prepared to go more aggressively to attract more money and contributors (ie add this on the home page, post it on all social channels, etc).

How do you suggest to proceed? I think we could prepare the whole table of contents, try to estimate the effort needed and the budget required and then go out and call people to join either with money or work.

@hmmxp and @5car1z, what do you think?

**Comment by hmmxp** [comment]
@ktsaou  I can contribute 12 hours per week to help write and proof read

Next Step
- Establish communication channel (Group chat using Telegram or WhatsApp)
- Set expectation and goals
- Come out with the structure of the documentation
- Slowly roll-out the new documentation

**Comment by kmonsoor** [comment]
@ktsaou yeah, that's cool. Markdown is quite helpful for moving around.

Anyway, I can help with proofreading, editing as well as testing of the contents. Please count me in.

**Comment by ktsaou** [comment]
@hmmxp @kmonsoor I have added you. Check the first comment on this issue.

I have assumed all contributors will have to get paid. If someone is willing to contribute without getting paid for it, let me know to edit it.

Let's try real-time communication, although it is not the best for me. I have a very tight daily schedule and I can only get irregular short intervals to do things, that are not easily predictable. I have a good contiguous block of time later at night (GMT+3).

But, let's try it. I have a slack team called `firehol` that I have used from time to time and my people at work use slack too, so I have it open most of the time. The problem is that slack is invite based. So, to join, send me an email at costa@tsaousis.gr with your email, and I'll invite you. Or we can use anything you like. If someone has a strong opinion about it, please coordinate it.

@hmmxp I think that expectations and goals are tightly integrated into the table of contents. Each section has its own expectations and goals.

So, we need to discuss on the table of contents a bit more. 

I suggest that the key sections are something like this:


### netdata installation
  - Linux
     - from source
     - binary packages
     - building RPMs
     - building DEBs
  - FreeBSD
  - MacOS
  - netdata in a docker container to monitoring the host
  - netdata tuning for IoT
  - netdata tuning for performance
  - netdata security
  - netdata behind a web server

### Configuration Reference
  - overview of netdata configuration methods
  - command line options
  - netdata.conf
  - netdata registry (`my-netdata` menu)
  - netdata simple patterns
  - ...

### Monitoring HowTos
  **I strongly believe this is the key section of netdata documentation. These should be "fat" sections, meaning that they should combine all available plugins to get the desired result. Each of these sections should be considered an _entry point_ to documentation (and yes, I plan to advertise/promote these sections as stand alone)**
  - monitoring system resource usage (CPU, RAM, Disk)
  - monitoring systemd services
  - monitoring arbitrary processes
  - monitoring web applications and web APIs
  - monitoring containers from the host
  - monitoring virtual machines from the host
  - monitoring SNMP devices
  - monitoring network latency and availability
  - monitoring hardware sensors
  - monitoring mysql servers
  - monitoring postgres servers
  - monitoring ...

### Data collection plugins reference
  **this should mainly be used as a reference / link from all other places for common configuration options related to each plugin**
  - Linux system monitoring
  - Linux cgroups monitoring
  - FreeBSD system monitoring
  - MacOS system monitoring
  - apps.plugin
  - python.d.plugin (python)
  - node.d.plugin (node.js)
  - chart.d.plugin (bash)
  - freeipmi.plugin
  - fping.plugin

### Statsd

  ...

### Health monitoring / alarms and notifications

  ...

### Replication / Streaming of metrics

  ...

### Archiving metrics to time-series DBs / backends

  ...

### API

  ...

### Custom Dashboards

  ...

---

Is anyone willing to make a complete the table of contents, up to the 2nd level (section / subsection)?

**Comment by hmmxp** [comment]
**Introduction**
- -	History
- -	What Is NetData
- -	Why NetData
- -	Road Map
- -	Release Note
- -	Demo Sites

**Installation**

- Linux
-- From source
-- Binary packages
-- Building RPMs
-- Building DEBs
- FreeBSD
- MacOS
- Docker

**Comment by 5car1z** [comment]
@ktsaou is https://gitter.im/ a suitable choice for communication? Or does it need to be something more private. Either way I'm good to join the Slack - sent you an email. 

10 hours seems like a reasonable estimate for time contribution. The money is most appreciated but not a complete necessity for me.

**Comment by kmonsoor** [comment]
i'll second about gitter.im. Open-source discussion better be on a open space.

looks like there's already a channel for Netdata there. https://gitter.im/firehol/netdata

**Comment by simonnagl** [comment]
I just want to say something to the communication discussion here.
In my opinion it should be something which at least everybody can read.
If somebody willing to join can see the whole process done so far in a transparent way and likes the way people communicate etc. he joins more likely.
Also, not making discussion etc. public might need to a loose of information somehow. This will lead to additional work. 

I think chats are a beautiful thing. But please don't make them closed.

**Comment by ktsaou** [comment]
@5car1z thanks! I updated you like this:

who | paid or free | role | time allocated
:--:|:------------:|-----|-------
@5car1z|flexible|write, proofread, editing, writing best practices|10h per week

@simonnagl of course. Actually I was trying to make the slack channel public somehow. I found this that seems to use a public slack channel: https://github.com/wakatime/slack-demo-chat - but I haven't tried it yet.

We could use gitter like @kmonsoor suggests. I am fine with it.

---

Regarding the tree @hmmxp suggested above: mine and his versions have a few differences.

I think we need something we will use as the **reference** for all available options, all available settings, etc. This should not tell any story. It should just state and describe every option out there. So, we will all know that once we add a setting, or we change the meaning of a setting, it will have to be documented there.

We have 2 options for this:

i. Have a master section called `Netdata Configuration Reference`, where all settings will be documented. It will be large though, like the whole book is duplicated under a single chapter of the whole book (i.e. most 1st level sections, will appear under the configuration reference section too).

or

ii. Have a special chapter in all sections, called `Configuration Reference`. For example, we may have a section called `Alarms`, which among other chapters, will include one named `Configuration Reference`. Similarly for `Streaming / Replication`, `Statsd`, etc. This will be like the whole documentation is a collection of smaller books.

I think I prefer the second option. I believe the first will result in a lot of duplication and complication. It will be quite complicated to find the options for `statsd` in a completely different section. I would prefer to have a section called `statsd` and in that section I find everything about it. 

---

Then we have another problem of context and hierarchy. I would tell netdata is:

1. a set of data collection features
2. a set of health monitoring features
3. an API that exposes the collected metrics and the alarms
4. a daemon that provides a set of features (like a database, streaming / replication, etc)
5. a platform to help you develop monitoring dashboards

Tutorials should be something that combine all the above, to provide a solution to a problem. For example, to effectively monitor a web server, you may combine a web server plugin (`nginx`, `apache`, etc), `web_log` to monitor the logs, `apps.plugin` to monitor the process itself, and alarms. The tutorial should tell you how to combine all these, with references to the rest of the documentation.

Regarding data collection, I would say that the different languages we have used for monitoring applications is not of any interest. Most people get confused by that. The right way would be to say:

- Data Collection
  - Monitoring mySQL
  - Monitoring postgreSQL
  - etc

People do not care if mySQL is monitored with python, node.js, or whatever. Actually each of these pages should state that "we provide 2 options for monitoring X: a python module and a bash module". Similarly, people do not care if we monitor network latency with fping. What they do care, is that monitor network latency and availability.

So, I vote for:

- a documentation that will be a collection of little books (data collection, alarms, metrics archiving, replication / streaming, custom dashboards, etc), each should cover everything about itself (features, configuration reference, examples, troubleshooting, etc)

- organize everything in a way to help users use it, independently of the underlying details. So, we should organize the content in a way people not knowing the internal details of netdata, would be able to use it effectively, without confusion.

What do you think?

**Comment by 5car1z** [comment]
Has there been a decision on the structure and table of contents discussed previously? It would be great to get started with the actual writing.

**Comment by ktsaou** [comment]
I will come back with a specific TOC within the weekend.

**Comment by ktsaou** [comment]
ok, here is what I think. I tried to include all the content the existing wiki has, but I tried to organize on a more user-friendly way (based on what I believe people seek info for):

---

# netdata handbook

## Welcome

---

## Installation
#### Linux
#### FreeBSD
#### pfSense
#### macOS

#### Netdata Compilation Guide
> step by step guide for compiling and installing netdata by hand.

#### Netdata Runtime Requirements & Directories
> information mainly for packagers and integrators, to learn what netdata needs to run, what are the various directories used for, etc.

---

## Getting Started with Netdata
> I installed netdata! Now what?

#### Netdata Startup
#### Log files

#### Configuration Basics
##### netdata.conf
##### Simple Patterns

#### Plugins Configuration
> this should include plugin debugging info (how to run it by hand, etc)
##### python.d.plugin
##### node.d.plugin
##### chart.d.plugin (bash)
##### other plugins (apps, fping, freeipmi, etc)

#### CPU Requirements & Tuning
#### Memory Requirements & Tuning
#### Disk Requirements & Tuning

#### Netdata Command Line Options

---

## Netdata Security
#### Overview
#### Authentication & Single Sign On
#### Running behind nginx
#### Running behind apache
#### Running behind lighttpd
#### Running behind caddy

---

## System Monitoring

> describe what netdata monitors on each system (cpu, ram, disks, mount points, cgroups, network interfaces, etc) and provide instructions for letting the users know where they can find related configuration options.

#### Linux
##### Systemd Monitoring
##### (state the various plugins: CPUs, cores, cpufreq, cpuidle, turbostat, etc)

#### FreeBSD
#### macOS

#### ZFS monitoring (Linux and FreeBSD)

---

## Network Monitoring
#### Network Interfaces
#### Network Latency and Packet Loss with `fping`
#### Network QoS with `tc` or `fireqos`

---

## Monitoring Containers and VMs
#### Overview of CGROUPS Monitoring
#### Running netdata at the host
#### Running netdata inside the containers and the VMs
#### Monitoring ephemeral containers and VMs

---

## Monitoring Processes
#### Configuring process groups
#### Comparison with `top` and other console tools
#### Writing alarms to monitor processes

---

## Hardware Monitoring
#### Hardware Sensors with `lm-sensors`
#### IPMI with `freeipmi`

---

## Monitoring Web Servers
#### nginx
#### apache
#### Monitoring Web Server Logs

---

## Monitoring Database Servers
#### mySQL
#### postgreSQL
#### memcached
#### redis
#### ... more DBs to monitor ...

---

## Applications Monitoring
#### named
#### squid
#### ... a long list of more apps to monitor ...

---

## Monitoring SNMP Devices

---

## Monitoring your Applications (APM)
#### Netdata Statsd
#### Monitor Go applications with `expvar`
#### Monitor Java applications with `jmx`
#### Write a custom netdata plugin (native API, or a module for `charts.d.plugin`, `python.d.plugin`, `node.d.plugin`)

---

## Health Monitoring, Alarms & Notifications
#### Overview
#### Alarms Configuration Examples
#### Alarm Notifications
#### Alarms Configuration Reference

---

## Netdata Streaming & Replication
#### Overview
#### Netdata Slaves
#### Netdata Proxies
#### Netdata Masters + tuning guide for masters

---

## Netdata Backends & Grafana Integration
#### Overview
#### Prometheus
#### Graphite & Compatibles
#### OpenTSDB & Compatibles
#### JSON Backends
#### Walkthrough: netdata + prometheus + grafana

---

## Netdata Web API Reference
#### Charts
#### Chart Data Formats (`json`, `csv`, `tsv`, `html`, etc)
#### Receiving Metrics on Shell Scripts

---

## Netdata Standard Dashboards
#### Netdata Registry: `my-netdata` menu
#### Customizing the Standard Dashboard

---

## Custom Dashboards
#### Multi-Server Dashboards
#### Google Charts
#### Netdata Badges

**Comment by ktsaou** [comment]
Join gitbook here: https://www.gitbook.com/invite?org=firehol&sig=QAyAfmvRoIYujj4BIf5Jg8vPxWM

I'll give you write access once you join.

I tried to implement this TOC on gitbook, but it seems the multi-level menu is not that straightforward. I see there are other gitbooks with multi-level menus, like [this gitbook](https://handbook.enspiral.com/) linked to [this repo](https://github.com/enspiral/handbook), but I couldn't figure out how to create such a TOC from the gitbook UI.

So, I think the first step is to assign gitbook management to someone.
Who is willing to take care of that?

**Comment by ktsaou** [comment]
And I created https://github.com/firehol/netdata-gitbook and linked it with a gitbook.

**Comment by ktsaou** [comment]
Gitbook link: https://www.gitbook.com/book/firehol/netdata-gitbook/details

**Comment by 5car1z** [comment]
@ktsaou Joined the GitBook org via the link. 

I've written personal docs with GitBook before in the past so I could create the multi TOC and maintain the repo/book in general, if that sounds good?

**Comment by ktsaou** [comment]
> I've written personal docs with GitBook before in the past so I could create the multi TOC and maintain the repo/book in general, if that sounds good?

perfect. I have given you access.

**Comment by kmonsoor** [comment]
just joined as: https://www.gitbook.com/@kmonsoor

**Comment by ktsaou** [comment]
> just joined as: https://www.gitbook.com/@kmonsoor

I have given access to you too.

**Comment by 5car1z** [comment]
@ktsaou Thanks. 

Give me some time to setup all the groundwork (GitBook plugins, files, etc) and then people can start filling out each of the sections with their content.

**Comment by 5car1z** [comment]
The basic layout for the GitBook repo is mostly ready if you anyone wants to start making an attempt at writing. 

> https://github.com/firehol/netdata-gitbook

I'll keep adding in the rest of the entries to the table of contents as time goes on. GitHub pull requests to the above repo are okay too, outside of GitBook write access. 

Here's the link for the website on GitBook's end:

> https://firehol.gitbooks.io/netdata-gitbook/

**Comment by ktsaou** [comment]
Great work @5car1z !

Does anyone know any good guidelines, of another project, for us to follow? A final example of the such guides would also be nice. Any pointers?

**Comment by 5car1z** [comment]
I was looking at [this one](https://docs.duckduckhack.com/welcome/determining-ia-type.html) for design purposes, but didn't check what the content was like. 

I'll continue with the GitBook repo again towards the end of the week.

**Comment by radhikasundararaman24** [comment]
Hello: I'd like to pitch in and help the community with some documentation support. 

Are you looking for some doc help?

**Comment by ktsaou** [comment]
of course, I always do.
There has been some progress above. Can you help?

**Comment by ktsaou** [comment]
Well, there is plenty of documentation already in the github wiki. You could start by re-organizing things under a new TOC.

I strongly believe the heart of the documentation are the applications monitored and specific tasks someone wants to achieve (like setup database replication, configure alarms, or notifications, etc). The rest of the documentation is just supporting for these.

So, I would start by mapping the existing documentation into a TOC.

**Comment by cakrit** [comment]
Closing, tracked under #4196
