### ISSUE TITLE
sync charts properly after being panned to whitespace

### ISSUE THREAD

**Issue by pjlegato** [netdata/netdata#265]
On Chrome/Mac and Chrome/Safari (at least), panning a chart on the demo dashboard does not cause the other charts to mirror the pan. That is, only the chart being directly manipulated pans; all others remain at their original pan.

The "Sync Pan and Zoom" setting is on.
Zoom does sync across charts.

**Comment by ktsaou** [comment]
Hi, I don't have access to a Mac. 

If you press F12 to open the console, do you have any errors?

**Comment by pjlegato** [comment]
No, there are no errors.

**Comment by ktsaou** [comment]
Can you give me versions?

I use browserstack.com and I see panning works on latest chrome version from snow leopard to el capitan.

Also, I see it works on safari 7.1 on Maverics.

**Comment by pjlegato** [comment]
Sure, it's Safari 9.0.1 and Chrome 49.0.2623.112, both on El Capitan (10.11.1)

**Comment by pjlegato** [comment]
It seems that the panning only doesn't work if you pan the chart into the future -- that is, click and drag to the left, so that there is whitespace on the right side of the chart.

**Comment by pjlegato** [comment]
My custom dashboard doesn't sync at all when panned either way. 
The demo at http://netdata.firehol.org syncs only if panned into the past.

**Comment by ktsaou** [comment]
oh! I see. Panning to the future is disabled by design.
Your dashboard should behave the same.

**Comment by pjlegato** [comment]
My custom dashboard doesn't sync either way (past or future). I suppose that's a seperate problem.

Would it be possible to prevent the user from panning into the future entirely?

**Comment by ktsaou** [comment]
Well, I have tried that but it was not nice. Panning is handled by the charting library and unfortunately dygraphs do not have this feature. When I implemented, the chart was jumping back... it was ugly, so I let it do it.

Regarding your dashboard, can you go to your netdata `/tv.html` url? Is it working there?

**Comment by pjlegato** [comment]
The tv.html served from my local system does pan properly. Is there some setting I'm missing that's required to group the charts, maybe?

**Comment by ktsaou** [comment]
Only the settings on the dashboard. There is a "reset" link at its top. This is saved in browser storage, so it will work for the tv.html too.

**Comment by pjlegato** [comment]
I have 1 hour of data in the server, and the charts also all show 1 hour by default, so if you pan into the past it is showing whitespace.

Would this prevent the sync code from running?

**Comment by pjlegato** [comment]
I think that's it... if I first zoom in and then pan, the charts do sync.

It seems that panning any chart into whitespace will successfully pan that chart, but no others.

If we can't prevent users from panning into whitespace nicely, can we make it sync so that all the charts pan into whitespace?

**Comment by ktsaou** [comment]
I'll have a look.
1 hour of data on your dashboard? What resolution do you have?
If you have enough RAM edit netdata.conf and set `history` higher...

**Comment by pjlegato** [comment]
What resolution of what?

I picked 1 hour as a fairly arbitrary starting value, just to get something to start using quickly. I'll turn up the history on the server, but the same issue will come up when the user eventually tries to pan into whitespace a little farther back.

**Comment by ktsaou** [comment]
The default dashboard shows 1 point (second) every 3 pixels of the screen. So to have 1 hour of data on the dashboard, you will need 3600 * 3 = 10800 pixels just for the chart, without the menu, the border, etc.

**Comment by ktsaou** [comment]
Probably the server is still collecting data. You don't have 1 hour of data yet.

**Comment by pjlegato** [comment]
Ah. My chart is set to 100% of its enclosure, which works out to 846 pixels wide at the moment.

The server's been running for over a week, with the default setting of history = 3600.

**Comment by ktsaou** [comment]
I am not sure this is still valid.
So, I am closing it. If the problem remain, please post a few screenshots to understand the issue better.
