### ISSUE TITLE
Add ability to use multiple metrics in one custom chart

### ISSUE THREAD

**Issue by kellabyte** [netdata/netdata#2650]
I would like to be able to chart multiple metrics on one chart.

**Comment by cobrafast** [comment]
It's been over a year, any progress on this?

**Comment by paulfantom** [comment]
No and it is not high in priorities list right now. However we are more than happy to accept PRs :smile:

**Comment by ktsaou** [comment]
There is a PR: https://github.com/firehol/netdata/pull/3828
A little bit more patience. I think we will have a lot of help in this area soon.

**Comment by ilyam8** [comment]
Duplicate of #2359
