### ISSUE TITLE
Add percentage axis to custom graphs

### ISSUE THREAD

**Issue by kellabyte** [netdata/netdata#2651]
I have to create a separate graph just to display % of change. It would be nice to be able to place this on the right axis since the left axis is taken by the value.

**Comment by ktsaou** [comment]
Hi,

netdata does not support multiple axes per chart. This is a nice enhancement though. It will be helpful in a many cases.

**Comment by magao** [comment]
I've looked into this a little bit. It appears that for a dygraph an axis will only be displayed if a series is assigned to it. So it would be possible to display the y2 axis, but it would need a dummy series assigned (I'm not sure if that series could be invisible or not).

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
