### ISSUE TITLE
web_log with defaults

### ISSUE THREAD

**Issue by kisst** [netdata/netdata#2654]
On Debian the best practice is to log into separated log files per vhost, in the log-format called combined look like this:
`LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined`

However the  [default config](https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf#L125-L128)  in netdata does not include `/var/log/apache2/*access.log`, and expect the custom logformat. 

I think the idea with netdata is to discover as much as possible, and monitor things by default, so I would like to suggest the change of default, or at least in the [docs header](https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf#L78-L79) provide a more common use-cases as example,but if not at least the format of the `pattern`

**Comment by ktsaou** [comment]
nice request!

The combined format should be trivial to be supported. @kisst if you can provide the custom log regex required we could add it in the plugin [quite easily](https://github.com/firehol/netdata/blob/d5e6ad1a66e2fd0ccb9d1803c44d6c8ad3258fd9/python.d/web_log.chart.py#L568-L575).

For the multiple filenames, we have to create a job for each of them, so that each log file will get its own set of charts. I guess the name of the job should whatever the ` * ` matches of the filename.

I think python.d.plugin does not support dynamic job creation, so we may have to think a bit how this should work.

@l2isbad your call...

**Comment by l2isbad** [comment]
@ktsaou 
Can you explain how works 'obsolete' chart option?
To mark a chart `obsolete` i have to send
`CHART uptime_custom.uptime 'hello_world' 'System uptime' 'uptime' 'uptime_my 'uptime' stacked 60000 1 'obsolete'`

?

**Comment by ktsaou** [comment]
Yeap, just append `obsolete`. If you add data to it, the flag will be removed.

The chart will be removed only after `[global].cleanup obsolete charts after seconds = 3600`. If you fetch it (scroll down to the chart), the timer refreshes. So the timer starts from the last time it was read or written.

I think however, that if you sent the `obsolete` option, the chart will not be shown on the next dashboard viewer (so, reads count on users that already have a dashboard open with that chart present).

**Comment by l2isbad** [comment]
works, thx
```
2017-10-06 16:22:22: netdata INFO : Deleting chart 'system.uptime_custom2' ('system.hello_world') from disk...
2017-10-06 16:22:22: netdata INFO : Deleting chart header file '/opt/netdata/var/cache/netdata/system.uptime_custom2/main.db'.
2017-10-06 16:22:22: netdata INFO : Deleting dimension file '/opt/netdata/var/cache/netdata/system.uptime_custom2/minutes2.db'.
2017-10-06 16:22:22: netdata INFO : Deleting dimension file '/opt/netdata/var/cache/netdata/system.uptime_custom2/hours2.db'.
2017-10-06 16:22:22: netdata INFO : Deleting dimension file '/opt/netdata/var/cache/netdata/system.uptime_custom2/days2.db'.
2017-10-06 16:22:22: netdata INFO : Deleting empty directory '/opt/netdata/var/cache/netdata/system.uptime_custom2'
```

**Comment by l2isbad** [comment]
@ktsaou 
Have a look

Two different charts (`type.id`) but same `type.name` - `system.hello_world`

```
CHART system.uptime_custom 'hello_world' 'System uptime' 'uptime' 'uptime' 'uptime' stacked 60000 1
DIMENSION 'minutes' 'minutes' absolute 1 1 ''
DIMENSION 'hours' 'hours' absolute 1 1 ''
DIMENSION 'days' 'days' absolute 1 1 ''

CHART system.uptime_custom2 'hello_world' 'System uptime' 'uptime' 'uptime' 'uptime' stacked 60001 1
DIMENSION 'minutes2' 'minutes2' absolute 1 1 ''
DIMENSION 'hours2' 'hours2' absolute 1 1 ''
DIMENSION 'days2' 'days2' absolute 1 1 ''
```

Plugin updates the first one

```
BEGIN system.uptime_custom 1000875
SET 'minutes' = 40
SET 'hours' = 1
SET 'days' = 6
END

BEGIN system.uptime_custom 998786
SET 'minutes' = 40
SET 'hours' = 1
SET 'days' = 6
END

BEGIN system.uptime_custom 1000029
SET 'minutes' = 40
SET 'hours' = 1
SET 'days' = 6
END

BEGIN system.uptime_custom 999683
SET 'minutes' = 40
SET 'hours' = 1
SET 'days' = 6
END
```

On dashboard:

![screenshot_20171006_205917](https://user-images.githubusercontent.com/22274335/31276989-a115de52-aad9-11e7-9be9-b7d9033e4980.png)

**Comment by ktsaou** [comment]
could you please post the output of `/api/v1/charts` for these 2 charts?

**Comment by l2isbad** [comment]
```json
"system.uptime_custom2": 		{
			"id": "system.uptime_custom2",
			"name": "system.hello_world",
			"type": "system",
			"family": "uptime",
			"context": "uptime",
			"title": "System uptime (system.hello_world)",
			"priority": 60001,
			"enabled": true,
			"units": "uptime",
			"data_url": "/api/v1/data?chart=system.hello_world",
			"chart_type": "stacked",
			"duration": 3996,
			"first_entry": 0,
			"last_entry": 0,
			"update_every": 1,
			"dimensions": {
				"minutes2": { "name": "minutes2" },
				"hours2": { "name": "hours2" },
				"days2": { "name": "days2" }
			},
			"green": null,
			"red": null
		},
		"system.uptime_custom": 		{
			"id": "system.uptime_custom",
			"name": "system.hello_world",
			"type": "system",
			"family": "uptime",
			"context": "uptime",
			"title": "System uptime (system.hello_world)",
			"priority": 60000,
			"enabled": true,
			"units": "uptime",
			"data_url": "/api/v1/data?chart=system.hello_world",
			"chart_type": "stacked",
			"duration": 3996,
			"first_entry": 1507289445,
			"last_entry": 1507293441,
			"update_every": 1,
			"dimensions": {
				"minutes": { "name": "minutes" },
				"hours": { "name": "hours" },
				"days": { "name": "days" }
			},
			"green": null,
			"red": null
		}
```

**Comment by ktsaou** [comment]
hm... it should have rejected that name for the second chart...
I'll check the code later today...

**Comment by l2isbad** [comment]
from error.log
`2017-10-06 21:37:21: netdata ERROR: RRDSET: INTERNAL ERROR: attempted to index duplicate chart name 'system.hello_world'
`

**Comment by ktsaou** [comment]
I think I fixed it with PR #2852 
It now rejects the duplicate name, and logs an error about it.
Can you check it?

**Comment by l2isbad** [comment]
It works.

![screenshot_20171007_121159](https://user-images.githubusercontent.com/22274335/31304311-e31b08f6-ab59-11e7-8966-a1703a583125.png)

`2017-10-07 12:12:27: netdata ERROR: RRDSET: chart name 'system.hello_world' on host 'ttk-work' already exists.`

**Comment by ktsaou** [comment]
thanks!

**Comment by l2isbad** [comment]
> For the multiple filenames, we have to create a job for each of them, so that each log file will get its own set of charts. I guess the name of the job should whatever the * matches of the filename.

> I think python.d.plugin does not support dynamic job creation, so we may have to think a bit how this should work.

Sounds complicated to me. I don't think we need to implement it inside plugin.

Easier to write a script that will generate a configuration file based on log dir content. 

I suggest to close this
@ktsaou @Ferroin
