### ISSUE TITLE
allow charts to be renamed for backends

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#2689]
Check this: https://github.com/firehol/netdata/issues/2678#issuecomment-327208384

I think there might be a way to support this in netdata. We could attach a few settings to all charts to send them to backends under a different name, possibly with a few static tags attached.

This way `cpu.cpu0` could become `system.cpu{cpu="0"}` when sent to backends.

It seems simple enough to implement but it requires a few more work to support this in external plugins, streaming, etc.

**Comment by ktsaou** [comment]
@cakrit 	this feature could also allow netdata to emulate other data collectors.
So, we could provide a config file that will allow netdata to emulate `collectd` or `telegraf`, or `node.exporter`, etc.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
