### ISSUE TITLE
allow netdata to know the plugin that collects each chart

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#2692]
Today, netdata does not keep track of the plugin that collects each chart.

Ideally there should be a `plugin` and a `module` defined with each `CHART`.

This would allow netdata to:

1. set a different `history` of the charts of a specific plugin or module.
2. show this information on the dashboard to let the user know where to look for configuration.
3. enable / disable modules

**Comment by Redsandro** [comment]
It would be interesting to see a settings page listing each 'group' (as grouped by the urn `#menu_<group_name>`) with an _"enable/disable this group"_ checkbox.

**Comment by ktsaou** [comment]
The netdata daemon already tracks the plugin and module of each chart.
So, what we miss now is configuration:

1. set a different history of the charts of a specific plugin or module
2. centrally control which modules should be run
