### ISSUE TITLE
automatically suggest applications found running that can be monitored by netdata

### ISSUE THREAD

**Issue by GitStoph** [netdata/netdata#2736]
Good afternoon!

So it occurred to me today while doing some work on my LibreNMS server cluster that I wasn't monitoring nginx while i was in fact running nginx.. A quick glance at config files and I easily corrected the issue by setting the web_log.conf accordingly, but it made me wonder. What other servers am I monitoring that I potentially didn't get 100% configured to monitor everything on accident? So here's where the feature request comes in:

Can we create a script to automatically check cgroup accounting, check running processes, etc and correlate back to the running netdata to see if it's actually currently being monitored? Perhaps something that just sat in the git clone directory that users would manually run to sanity check that they've configured everything in totality? The output could be an alarm if someone really wanted to be fancy, but a simple text output along the lines of "<hostname> is currently running nginx. Netdata can monitor that! <link to plugin wiki> to learn more!" would be certainly helpful.

There could be people out there not fully utilizing the full brilliance of this tool. It may help them discover something they didn't know they were missing/appreciating? 

Probably a low priority, but just a thought to maybe blip your radar. I know I'd appreciate it. Thanks!!

**Comment by Ferroin** [comment]
While it might end up being a low priority, I do think it's a great idea, especially if the script could correlate to what plugins you need to monitor whatever service (and possibly add some hints for the configuration, some of the plugins that aren't 100% automatic are non-trivial to configure).

**Comment by ktsaou** [comment]
This is nice.
I was also thinking of a tool to confirm netdata is installed properly (like an audit tool).

I think however that starting with a guide would also be nice (a **netdata getting started guide** ).

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
