### ISSUE TITLE
Web Push Notifications

### ISSUE THREAD

**Issue by Komic** [netdata/netdata#2737]
https://www.w3.org/TR/push-api/
Currently, notifications can only be delivered to remote devices via third-party proprietary services or email. Supporting push and using that instead of [normal web notifications](https://github.com/firehol/netdata/wiki/web-browser-notifications) would mean creating a one-click experience for health monitoring from your smartphone which would, IMO, be a fantastic addition to netdata.

**Comment by ktsaou** [comment]
Thanks!

The last time I checked, this required registering your netdata with a push service. So, the push service will consider you are an application developer willing to push metrics to them and this will have to be done by all netdata users.

Ideally a public central netdata health service would solve the problem. So the central netdata will be registered at the push service and each netdata server will just push their alarms through the central netdata.

**Comment by Komic** [comment]
> this required registering your netdata with a push service.
Not sure why this would require such a central public server. I think you wouldn't have to register anything as a netdata instance owner, you'd just have to generate a VAPID key pair during deployment. Once a browser is subscribed, netdata would push alarms to the right endpoint (e.g. a FCM one if that browser is Chrome), what's behind the endpoint then handles the delivery.
https://github.com/web-push-libs/webpush-java/blob/master/doc/UsageExample.md looks like a pretty good introduction to Push Notifications, there's also [this](https://serviceworke.rs/push-rich.html) from the Mozilla Service Worker Cookbook.

**Comment by ktsaou** [comment]
@gmosx 	I think this should be part of the hub.

**Comment by infectormp** [comment]
FYI.
[gotify ](https://gotify.net/) is a simple, open source server for sending and receiving messages in real-time per web socket (it can be self-hosted). 

**Features**
- send messages via REST-API
- receive messages via web socket
- CLI for sending messages
- Plugins
- Web-UI
- Android-App

**Comment by cakrit** [comment]
We have support for:
- [Amazon SNS](https://docs.netdata.cloud/health/notifications/awssns/#amazon-sns)
- [Prowl](https://docs.netdata.cloud/health/notifications/prowl/#prowl)
- [Pushover](https://docs.netdata.cloud/health/notifications/pushover/#pushover)

**Comment by Komic** [comment]
@cakrit with all due respect, webpush is the one universal [standard](https://datatracker.ietf.org/wg/webpush/documents/) for push notifications, shoehorning external actors into this is disappointing.

**Comment by cakrit** [comment]
Reopening then! We don't want to disappoint anyone, it's just that this ticket was way too old and forgotten!

**Comment by cakrit** [comment]
Actually, can we have a concrete decision on how to progress here? 
Are there any commonly used binaries in Linux we can call? Any libraries that we can use? We obviously don't want to implement a protocol from scratch, if we can avoid it (reminder that alarm notifications are sent by a `sh` script today, we'll probably find some ready service to do it on the cloud).

**Comment by Komic** [comment]
https://github.com/web-push-libs/ecec looks like the most turnkey solution out there. The network logic should be fairly easy to implement on top of that?

**Comment by cakrit** [comment]
That's a good pointer, but what I'm saying is that the current method of sending alarm notifications is to pass all the arguments to https://github.com/netdata/netdata/blob/master/health/notifications/alarm-notify.sh.in and let it either execute a binary, or issue an http(s) request to some endpoint. We've been talking about eliminating that script and doing something better inside the daemon for a while. I suppose we could consider doing an implementation just for these push notifications and then extending it to gradually remove email and other methods from the script, until there's nothing left there, except the occasional custom sender, that we'd definitely want to keep, for ease of use. 

Let's see what others say as well.

**Comment by Komic** [comment]
Hi guys, I hope you don't mind me bumping this one. Keep it up! 💯

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
