### ISSUE TITLE
configure external commands (python, node.js, etc) in netdata.conf

### ISSUE THREAD

**Issue by magao** [netdata/netdata#2781]
The command necessary to run a plugin may not be on the path, or you may want to override the default (e.g. use `python3` in preference to `python`, or possibly `pypy`).

I would suggest another option for each plugin:

```
[plugin:python.d]
	# command =
```

which gets passed to the plugin somehow. Don't really want to change the command line, so maybe set an environment variable. If non-empty, the plugin should try to use it before the default commands. For example, for `python.d`:

```
#!/usr/bin/env bash
'''':; exec "$(command -v "${NETDATA_PLUGIN_PYTHOND_COMMAND}" || command -v python || command -v python3 || command -v python2 || echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''
```

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/1731#issuecomment-277767601

**Comment by magao** [comment]
Whilst that method works, it's pretty cumbersome, especially if you're changing it fairly commonly (e.g. testing against various python versions). Using a dedicated environment variable I can just do:

`NETDATA_PLUGIN_PYTHOND_COMMAND=python3 /opt/NetData/libexec/netdata/plugins.d/python.d.plugin myplugin.chart.py debug`

to test against python3.

**Comment by l2isbad** [comment]
> if you're changing it fairly commonly (e.g. testing against various python versions)

Well, is such cases better will be (not supported by current python.d.plugin but it's easy to fix)

`python2.7 python.d.plugin debug 1 myplugin.chart.py`
`python3.4 python.d.plugin debug 1 myplugin.chart.py`

**Comment by ktsaou** [comment]
We could add a few `netdata.conf` for `python`, `node.js`, `bash`, `curl`, `fping`, `sendmail`, etc and set a few environment variables for all the plugins to use the netdata.conf configured ones.

I think we will eventually need this functionality, especially if we move certain features of the external scripts into netdata.

I'll leave this as enhancement.

**Comment by ktsaou** [comment]
@cakrit 	another one for controlling external plugin modules from `netdata.conf`.
The idea of having a `netdata.conf` called `[environment]` to allow configuring external plugins env variables is also nice (today, such variables are scattered in netdata.conf).

**Comment by cakrit** [comment]
Leaving it on me until we have someone to work on this.

**Comment by ilyam8** [comment]
This is fixed for `python.d` in https://github.com/netdata/netdata/pull/6781

And this request actually for `python.d`. I think can close the issue @cakrit

**Comment by ilyam8** [comment]
fixed for python, i see no value to add it to the nodejs
