### ISSUE TITLE
Summary Charts for Java Processes

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#2789]
We may provide one chart for every chart of the JMX module of the java plugin with only one dimension which has one dimension per java process.

For example we could provide a chart `jmx.cpu` with one dimension for each monitored java process.
This can be used to compare the CPU usage of java applications.

Similar could be done for `load`, `compilation`, and eventually `uptime` and `threads_started`

This is just a proposal and no needed feature for my personal use case. Please comment or add a thumb up if you would like this.

This issue was migrated from [netdata-plugin-java-daemon](https://github.com/simonnagl/netdata-plugin-java-daemon) and closes [#46](https://github.com/simonnagl/netdata-plugin-java-daemon/issues/46)

**Comment by ktsaou** [comment]
So, you suggest to provide something similar to the charts `apps.plugin` provides, for java applications. Right?

I am not sure this would be the more efficient for java apps. `apps.plugin` does this, because it is able to provide an overview of the whole system.

I mean, users are expected to monitor java application A and java application B. Of course there will be several metrics that are common (cpu, memory, garbage collector metrics, etc), but most probably users will be willing more than just that, including custom metrics for each specific application. These custom metrics will most probably create a chaotic section...

If you are sure the metrics will be homogeneous, then go for it, But, as we add java apps, if the each application contributes custom charts to a common pull of charts, there will be a mess.

**Comment by simonnagl** [comment]
> to provide something similar to the charts apps.plugin provides, for java applications. Right?

Yes. But I would only do it if somebody else finds it useful.
I was just thinking of it and writing my thoughts down in an issue.
For example macOS does not support `apps.plugin` yet. Am I right? So for this port this might be useful.

> if the each application contributes custom charts to a common pull of charts, there will be a mess.

I am not sure if I understand what you mean. If you mean that we should not provide two or more charts monitoring the same metrics we already have in an other chart. If this is what you mean I agree with you!

**Comment by gamefundas** [comment]
In the past I have been thinking of few different ways to do this for Java applications. There is already an issue open #2074 that speaks about a Spring boot plugin. If a Netdata plugin can query the JMX/Jolokia via HTTP or Actuator endpoints to pull these metrics on some configured interval then these can be made available in Netdata. Any custom metrics can be supplied by implementing them on the server side using dropwizard etc.

Besides this the other way of doing this a little seamlessly is if the Java process or Spring boot application can send the metrics to the StatsD server which is available in Netdata 1.7+. This is easy to implement again using MetricRegistry/Writer on the Java side. Will work for any custom metrics too as Netdata will simply generate charts for StatsD metrics in real time.

I haven't developed this yet, but this is what I have in mind for now.

**Comment by simonnagl** [comment]
Hi @gamefundas,

please check #2663 which will provide a module to connect directly to JMX servers and monitor it's metrics. With this using the Jolokia and HTTP overhead will not be needed any more for collecting any values of MBean.

_(Well, this is not true because the pull request version has very limited support of datatypes which can be collected but I have plans to add quite more.)_

The pull request will also currently only support charts with metrics of ONE java process and no summary charts. I created this issue to discuss if summary charts comparing values of all monitored java processes are useful or misleading.

I know Spring boot also exposes it's actuator endpoints over MBeans. I am not sure if this is useful. To not spam this thread I will post my arguments at #2074.

I would be very happy seeing you contributing with comments or code to that plugin in the future.

**Comment by ilyam8** [comment]
Closing it because `netdata-plugin-java-daemon` is not part of the Netdata project.
