### ISSUE TITLE
Documentation for each chart on the dashboard

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#279]
## Why?

By adding more information about the charts and their values, a lot more users will understand what they are seeing, how to interpret and charts and what they can do to optimize their systems.

If the information we add has references to other sites with more detailed information about each metric, the netdata dashboard will effectively get another important role: **it will become a reference for acquiring information about system and applications performance optimization**.
## How?

Netdata allows us to write information about each chart on the dashboard. It supports 3 types of info:
1. **Per menu information**
   
   **[link to the point in the code here](https://github.com/firehol/netdata/blob/78170f6861d49123f69022fdd130dea9b6c03f91/web/index.html#L897)**
2. **Per submenu information**
   
   **[link to the point in the code here](https://github.com/firehol/netdata/blob/78170f6861d49123f69022fdd130dea9b6c03f91/web/index.html#L992)**
3. **Per chart information**
   
   **[link to the point in the code here](https://github.com/firehol/netdata/blob/78170f6861d49123f69022fdd130dea9b6c03f91/web/index.html#L1014)**

The list appearing in the source today is not complete. I have just added the entries I wrote some information for. All charts, submenus and menus can be added.
## Your role

I need help to collect all this information and add it to the dashboard.

**Can you help?**

If yes, please fork the repo, and modify index.html by adding information about charts. Then make pull requests to have your work merged into netdata and available for everyone to see.
## What is next?

Once we have enough such information in English, other users will translate it to other languages. I have already got an open-source license at cowdin here: https://crowdin.com/project/netdata to allow others do the translation. And there are already users willing to do translations, check: #219

**Comment by glensc** [comment]
please use permalinks to your links to file lines in repository. using `master` may move the line numbers making them incorrect over time. use some tag or commit hash instead, also use markdown links so they don't look ugly: `[LINK TITLE](LINK URL)`

**Comment by ktsaou** [comment]
> please use permalinks

thanks!

**Comment by elcangri2124** [comment]
@ktsaou can you add the files at https://crowdin.com/project/netdata so I can start translating some of it? thank you.

**Comment by shadycuz** [comment]
@ktsaou How happy are you with this or would you like more documentation like the type you find under "cpu" and "load"

**Comment by ktsaou** [comment]
I would like a lot more documentation. Most people do not understand what they see, so there should be a lot more information.

I have already split all the information to a separate file that can also be uploaded for translation: https://github.com/firehol/netdata/blob/master/web/dashboard_info.js

However is still very basic.

**Comment by shadycuz** [comment]
I'll look into it tonight and see what I can do

**Comment by shadycuz** [comment]
@ktsaou #1208 Worked on a small part just to make sure this is what you were looking for, I can do more sections in the upcoming days or until you find a better use of my time. 

Thanks,
Levi

**Comment by bclicn** [comment]
Hi, I would like to help to translate  [https://github.com/firehol/netdata/blob/master/web/dashboard_info.js](https://github.com/firehol/netdata/blob/master/web/dashboard_info.js) to Chinese, but there's no file at [https://crowdin.com/project/netdata/zh-CN#](https://crowdin.com/project/netdata/zh-CN#). 
Where should I submit the translation? Or should I wait for people to add more content to it?
Thanks, Beichen Li

**Comment by shadycuz** [comment]
@ktsaou Some one else asked as well <https://crowdin.com/project/netdata/discussions/1/0/home>

**Comment by ktsaou** [comment]
It is still very primitive.
Can you help adding content before translating it?

**Comment by bclicn** [comment]
I'm not a system administrator so I'm not sure if the information I provide will be 100% correct. But if you need my, help I will do my best.

**Comment by ktsaou** [comment]
> I'm not a system administrator so I'm not sure if the information I provide will be 100% correct. But if you need my help, I will do my best.

In most of the cases, wikipedia is very helpful. In general, if you try to understand what you see and write it down, with a link to the references you found, it will be perfect.

If you can make PRs, I'll join to discuss everything in detail.

So, yes I need help...

**Comment by asiabet4dd** [comment]
wow this is sooo niceee,, i will ready all your articel until i die because so awesome and come to mine too <a href="http://www.roket4d.info/">Agen Bola Terpercaya</a> thanks.

**Comment by cakrit** [comment]
@asiabet4dd blocked and abuse (spam) reported.

**Comment by cakrit** [comment]
We've had no contributions here, closing.
