### ISSUE TITLE
Use a (shorter) timeout when making JMX connections 

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#2790]
This is a bug report.

Currently if the JMX module of the java plugin tries to make a connection to a java server and the requests does not finish this may block the initialization of the plugin for a long time.

We should add a shorter, maybe configurable, timeout when making this connections.
Additional we may need to use a thread pool for making the connections.

This issue was migrated from [netdata-plugin-java-daemon](https://github.com/simonnagl/netdata-plugin-java-daemon) and closes [#46](https://github.com/simonnagl/netdata-plugin-java-daemon/issues/45)

**Comment by ilyam8** [comment]
Closing it because `netdata-plugin-java-daemon` is not part of the Netdata project.
