### ISSUE TITLE
Configuration option to disable JMX module

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#2791]
Currently the JMX module (part of the java plugin) cannot be disabled. This is not fatal because it is currently the only module of the java plugin. Nevertheless we should provide a configuration option to disable java plugin modules.

This issue was migrated from [netdata-plugin-java-daemon](https://github.com/simonnagl/netdata-plugin-java-daemon) and closes [#38](https://github.com/simonnagl/netdata-plugin-java-daemon/issues/38)

**Comment by ilyam8** [comment]
> This issue was migrated from netdata-plugin-java-daemon 

Closing it because this issue doesn't belong to the netdata project.
