### ISSUE TITLE
Optimize JMX data collection

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#2792]
The JMX API supports to query multiple attributes of one MBean in one request.

Currently the JMX Module of the java plugin uses one call per attribute per chart.

In a first step we can optimize this using one call per attribute. In a second step we can optimize this further using one call per MBean.

__Some thoughts on the changes needed:__

- Extend MBeanQueryInfo: MBeanQueryInfo should contain information about the MBean and a list of Attributes to collect and where to store them.
- Change initialization of MBeanServerCollector to fit.
- Change data collection of MBeanServerColletor to fit.

This issue was migrated from [netdata-plugin-java-daemon](https://github.com/simonnagl/netdata-plugin-java-daemon) and closes [#37](https://github.com/simonnagl/netdata-plugin-java-daemon/issues/37)

**Comment by cakrit** [comment]
@simonnagl 	are you still working on this?

**Comment by simonnagl** [comment]
I think this is patly implemented. Currently I am not working on this. If you want I can check the state of this issue.

**Comment by cakrit** [comment]
It's just one of several issues linked to #2663. Since a lot of work was already done, we could ask others in the community to assist, if you are not able to move it forward.

**Comment by ilyam8** [comment]
Closing it because `netdata-plugin-java-daemon` is not part of the Netdata project.
