### ISSUE TITLE
[JMX module] Mark charts of dead java processes obsolete

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#2798]
Currently, if a monitored java process quits we stop collecting it's values. The chart stays empty.

This is not sufficient. We should mark charts of dead auto-detected java processes as obsolete. We do not want to spam the `netdata` dashboard creating new charts and not removing old ones. For especially configured and named processes this is not needed.

This issue was migrated from [netdata-plugin-java-daemon](https://github.com/simonnagl/netdata-plugin-java-daemon) and closes [#36](https://github.com/simonnagl/netdata-plugin-java-daemon/issues/36)

**Comment by ilyam8** [comment]
> This issue was migrated from netdata-plugin-java-daemon 

Closing it because this issue doesn't belong to the netdata project.
