### ISSUE TITLE
Support monitoring array size of MBean attributes

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#2799]
We should support monitoring the size of arrays returned by MBean attributes. This enables us adding/extending the following charts:

- Add dimension java.lang:type=Threading DeadlockedThreads to threading chart.

This issue was migrated from [netdata-plugin-java-daemon](https://github.com/simonnagl/netdata-plugin-java-daemon) and closes [#29](https://github.com/simonnagl/netdata-plugin-java-daemon/issues/29)

**Comment by ilyam8** [comment]
Closing it because `netdata-plugin-java-daemon` is not part of the Netdata project.
