### ISSUE TITLE
JMX Module chart request: CPU usage per thread

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#2806]
For Java Processes monitored by the JMX Module we should add a chart with CPU usage per thread. Mean `from: java.lang:type=Threading` provides `AllThreadIds` for which we could find names and query `ThreadCpuTime` and `ThreadUserTime` with the thread ID.

We need to disc

1. Find thread IDs: AllThreadIds
2. (find names to ids?)
3. Query ThreadCpuTime and maybe ThreadUserTime for every thread.

We need to find a way to configure this type of collection.

This issue was migrated from [netdata-plugin-java-daemon](https://github.com/simonnagl/netdata-plugin-java-daemon) and closes [#28](https://github.com/simonnagl/netdata-plugin-java-daemon/issues/28)

**Comment by ilyam8** [comment]
> This issue was migrated from netdata-plugin-java-daemon 

Closing it because this issue doesn't belong to the netdata project.
