### ISSUE TITLE
Add health alarms for JMX module

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#2807]
For the charts of the default configuration of the JMX module of the java plugin we should provide [health configurations](https://github.com/firehol/netdata/wiki/health-configuration-reference).

There I need some help of someone more experienced in monitoring java applications. What are values `netdata` should warn about? If someone could provide descriptions when to trigger alarms in any form it might be quite easy to write the configuration for it.

This issue was migrated from [netdata-plugin-java-daemon](https://github.com/simonnagl/netdata-plugin-java-daemon) and closes [#19](https://github.com/simonnagl/netdata-plugin-java-daemon/issues/19)

**Comment by simonnagl** [comment]
@ktsao The your help neded Label would be appropriare here too.

**Comment by ktsaou** [comment]
How can I help?

**Comment by simonnagl** [comment]
> There I need some help of someone more experienced in monitoring java applications. What are values netdata should warn about? If someone could provide descriptions when to trigger alarms in any form it might be quite easy to write the configuration for it.

**Comment by ktsaou** [comment]
ok, I am not "experienced in monitoring java apps". Let's wait for someone to join.

**Comment by ilyam8** [comment]
> This issue was migrated from netdata-plugin-java-daemon 

Closing it because this issue doesn't belong to the netdata project.
