### ISSUE TITLE
Install script does not (correctly) check for “libtoolize”

### ISSUE THREAD

**Issue by casperklein** [netdata/netdata#2918]
I just installed netdata on Ubuntu 11.10 using ``bash <(curl -Ss https://my-netdata.io/kickstart.sh)``

When installation finished, I saw:

```
[/usr/src/netdata.git]# /opt/netdata/usr/sbin/netdata
 OK

OK. NetData Started!

```

But netdata was not running. Starting in foreground with -D didn't show any error and netdata immediately closes.
When scrolling up viewing the installation/build steps, I noticed an error message about "libtoolize" was missing. 
After installing 'libtool' package and reinstalling netdata it worked.

**Comment by paulfantom** [comment]
Is this still an issue?

**Comment by casperklein** [comment]
I haven't tried it again since then, as installing the "libtool" package before fixed it for me.

**Comment by paulfantom** [comment]
I am closing this as it is no longer an issue to original author.
