### ISSUE TITLE
Feature: UKSM support

### ISSUE THREAD

**Issue by drdeimos** [netdata/netdata#2994]
It's possible to add uksm monitoring charts?
https://github.com/dolohow/uksm

Like KSM but more effectivity

**Comment by ktsaou** [comment]
interesting!

If I understand this right, UKSM is an extension of KSM. It replaces the core algorithm of it, but everything else remains the same.

So, netdata already monitors it. Just enable KSM and UKSM and you will have charts like these:

![screenshot from 2017-11-10 22-53-43](https://user-images.githubusercontent.com/2662304/32678179-076a0f88-c66a-11e7-9130-b2a212cb58a0.png)

**Comment by drdeimos** [comment]
It use another `/proc` directory for metrics but similar file names:
```
$ ll /sys/kernel/mm/uksm/
total 0
-rw-r--r-- 1 root root 4.0K Nov 12 03:58 abundant_threshold
-rw-r--r-- 1 root root 4.0K Nov 12 03:58 cpu_governor
-rw-r--r-- 1 root root 4.0K Nov 12 03:58 cpu_ratios
-r--r--r-- 1 root root 4.0K Nov 12 03:58 ema_per_page_time
-rw-r--r-- 1 root root 4.0K Nov 12 03:58 eval_intervals
-r--r--r-- 1 root root 4.0K Nov 12 03:58 full_scans
-r--r--r-- 1 root root 4.0K Nov 12 03:58 hash_strength
-rw-r--r-- 1 root root 4.0K Nov 12 03:58 max_cpu_percentage
-r--r--r-- 1 root root 4.0K Nov 12 03:56 pages_scanned
-r--r--r-- 1 root root 4.0K Nov 12 03:56 pages_shared
-r--r--r-- 1 root root 4.0K Nov 11 21:28 pages_sharing
-r--r--r-- 1 root root 4.0K Nov 12 03:56 pages_unshared
-rw-r--r-- 1 root root 4.0K Nov 12 03:58 run
-rw-r--r-- 1 root root 4.0K Nov 12 03:58 sleep_millisecs
-r--r--r-- 1 root root 4.0K Nov 12 03:58 sleep_times
-rw-r--r-- 1 root root 4.0K Nov 12 03:58 thrash_threshold
```

**Comment by ktsaou** [comment]
At netdata.conf:

```
[plugin:proc:/sys/kernel/mm/ksm]
	# /sys/kernel/mm/ksm/pages_shared = /sys/kernel/mm/ksm/pages_shared
	# /sys/kernel/mm/ksm/pages_sharing = /sys/kernel/mm/ksm/pages_sharing
	# /sys/kernel/mm/ksm/pages_unshared = /sys/kernel/mm/ksm/pages_unshared
	# /sys/kernel/mm/ksm/pages_volatile = /sys/kernel/mm/ksm/pages_volatile
	# /sys/kernel/mm/ksm/pages_to_scan = /sys/kernel/mm/ksm/pages_to_scan
```

uncomment them too.

**Comment by ktsaou** [comment]
If it works, I'll make netdata lookup for it.

**Comment by drdeimos** [comment]
Uncommented this section and set new paths for pages_shared, pages_sharing, pages_unshared.
pages_volatile and pages_to_scan set  to **wrong** files because without it netdata does now show Memory Deduper menu and this metrics non exist in UKSM:
```
[plugin:proc:/sys/kernel/mm/ksm]
        /sys/kernel/mm/ksm/pages_shared = /sys/kernel/mm/uksm/pages_shared
        /sys/kernel/mm/ksm/pages_sharing = /sys/kernel/mm/uksm/pages_sharing
        /sys/kernel/mm/ksm/pages_unshared = /sys/kernel/mm/uksm/pages_unshared
        /sys/kernel/mm/ksm/pages_volatile = /sys/kernel/mm/uksm/thrash_threshold # WRONG
        /sys/kernel/mm/ksm/pages_to_scan = /sys/kernel/mm/uksm/pages_scanned #WRONG
```
and get this (see screenshot): 
![979935d184e582f35cb14731751c4ec8958f899c](https://user-images.githubusercontent.com/3472810/32698360-8f4c68be-c7b5-11e7-8cae-59da2322a57d.png)

**Comment by drdeimos** [comment]
On screen shot i've get "Saved 47 Mb". But
`/sys/kernel/mm/uksm/pages_sharing` = 18080 pages.
18080 pages with PAGESIZE 4096 byte  =~ 70 Mbyte saved
`18080*4096/1024/1024 = 70.625`

**Comment by ktsaou** [comment]
You have to subtract `pages_shared` to find the savings. `sharing` pages have reduced to `shared`, so their diff is the savings.

ok, I can make a PR with this...

**Comment by drdeimos** [comment]
On [official website doc](http://kerneldedup.org/en/projects/uksm/uksmdoc/usage/usage0-1-2/):
 - pages_shared: how many pages has been mapped by different page table entries, i.e. shared by different processes.
- pages_sharing: this is roughly the number of redundant pages you have saved, with uksm.

**Comment by ktsaou** [comment]
I think the key here is the word "roughly".

The redundant pages (`sharing`) have been merged into a smaller set of pages (`shared`). So the actual savings is their difference.

So, If you have 1000 `sharing` into 500 `shared`, you have 50% savings.
But, if you have 1000 `sharing` into 10 `shared`, you have 99% savings.

**Comment by drdeimos** [comment]
Ok. Thank you

**Comment by ktsaou** [comment]
It seems I was wrong here.
Issue #3304 describes it in detail and PR #3318 fixes it.

**Comment by cakrit** [comment]
Seems fixed. Please reopen if necessary.
