### ISSUE TITLE
[JMX Module] Recheck for new or restarted JMX Servers

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#3047]
@h0lzi wrote at #364:

> One thing I notice. If I restart the tomcat the plugin will not reconnect.
I'm not sure what the best way to handel that is. Maybe if there was a connection try every x seconds for y minutes.
(Make that a config option?). Off cause it needs to bail out eventually.
But besides that basic stuff seems to work for me.

He is right. We need an option to periodically recheck if the configured JMX servers are there and rerun auto detection if it is on.

**Comment by ilyam8** [comment]
Closing it because netdata-plugin-java-daemon is not part of the Netdata project.
