### ISSUE TITLE
network overview

### ISSUE THREAD

**Issue by talkyy** [netdata/netdata#3071]
Hi , 
I am monitoring about 30 switches by netdata. I think the present dashboard is difficult to have an overview of the system (swicthes have many ports, many information and many status). I want to make it becomes easier. So I have some things to know:
1. When I add a new switch to netdata, I have to edit `snmp.conf` and the file is too many lines now. Is it possible if we make a switch into a file? (I mean if we have 30 switches we will have 30 files `.conf` instead of 30 switches in a file). 
2. If I make a custom dashboard, how can I make the dashboard auto generates chart when I add a new switch?
3. I have a look to Nagios dashboard. It can group the services of system (example ping service, ldap service, etc.). Could netdata do it?

I am looking forward to hearing from you soon.
Thanks.

**Comment by Ferroin** [comment]
On the note of the first point about `snmp.conf`, I think taking an approach like `health.d`, `charts.d` and similar would be the best option here, provided that it isn't already the case of course.

**Comment by l2isbad** [comment]
Actually
https://github.com/firehol/netdata/issues/1126

**Comment by ktsaou** [comment]
For sure we have to fix that. The way it is now is totally unmanageable at this scale.

**Comment by ktsaou** [comment]
Ideally we should provide some kind of SNMP templates and then configure only credentials and IPs for each template.

**Comment by talkyy** [comment]
Well, this work will need many help of people to get information of switch. 
One more thing, I am making a custom dashboard. Can I add web notification to custom dashboard?
Thanks.

**Comment by ktsaou** [comment]
> Can I add web notification to custom dashboard?

yes, set `var netdataShowAlarms = true` before loading `dashboard.js`. This is currently single server though. You cannot have web notifications from multiple servers at the same time.

**Comment by ktsaou** [comment]
@cakrit 	a network view will be provided with netdata hub.

**Comment by cakrit** [comment]
Closing in favor of #5062
