### ISSUE TITLE
Gathering server values as text

### ISSUE THREAD

**Issue by damsku** [netdata/netdata#3086]
Hi,

I am looking into gathering various info from the servers on a custom dashboard such as current CPU count, amount of RAM, disk space used and available... but as text rather than graphs. Being VMs, these tend to change quite regularly depending on the needs.
I could not find a way to access that kind of values from the charts REST API, the best that I seem to be able to do at the moment is to extract dimension values or use badges which either are not quite the same thing.
Am I missing something? Or is that something that will require a plugin to be made? If so, do you have any pointer where should I start from?

Cheers

**Comment by ktsaou** [comment]
The netdata API can provide metrics in many formats:

1. `json` [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=json)
2. `jsonp` [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=jsonp)
3. `datatable` (google visualization data provider) [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=datatable)
4. `datasource` (google visualization data provider) [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=datasource)
5. `csv` (comma separated table) [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=csv)
6. `tsv` (tab separated table) [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=tsv)
7. `ssv` (space separated list of values, all dimensions merged) [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=ssv)
8. `ssvcomma` (comma separated list of values, all dimensions merged) [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=ssvcomma)
9. `array` (javascript array, all dimensions merged) [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=array)
10. `html` (a table formatted in html) [example](http://london.my-netdata.io/api/v1/data?chart=system.cpu&after=-60&format=html)

Use the `format` parameter with any of the above. You can also use the other API parameters to select the time-frame, the dimensions to be returned, etc.

**Comment by damsku** [comment]
Thank you Costa for your answer! This does make the data more accessible and is definitely powerful.
However, I was more looking into something in the spirit of https://github.com/firehol/netdata/wiki/Custom-Dashboards#extracting-dimension-values that would already deal with refreshing in a custom dashboard but without having to also render a graph to poll data as text and being able to read other things in the JSON response than only the content of the dimensions. (Does this make sense?)
I have very little knowledge using jQuery and whatnot html/js/css magic and I am looking for a reasonable way to reach my goal time-wise.
I unfortunately get the feeling rendering the JSON data as you mentioned in your answer, in realtime and in the form of text is a tremendous amount of work for something that seems quite basic compared to the advanced graphs netdata supports so I was hoping I was just missing something obvious :)

**Comment by ktsaou** [comment]
hm... so you say a chart that is a table... nice idea...

**Comment by damsku** [comment]
Kinda like that, yea. For example, this is what I wanted to get on my dashboard: 
![image](https://user-images.githubusercontent.com/19593917/33605799-cd9d95aa-d9c3-11e7-8f61-05858514b831.png)
Right now, I need to do some silly jqueries in order to get that data, so yes, the charts API with json format is super handy but the entire system the graphs rely on so they don't update offscreen, get their units automatically converted/scaled and so forth is lost and there is no straight forward way (that I could find) to achieve this on top of the awesome graph system. Additionally, there are some things the API does not help with (i.e listing the available disks doesn't seem possible, so unless using some conventions with the mount names between servers and tolerating 404s for some queries, it is a ton of work to get remotely close to the performance and flexibility you have achieved with the rest).

**Comment by cakrit** [comment]
@damsku I believe that the specific use case you mentioned is covered in PR #5971 (issue #5578).
Can you verify? If it does cover the need, then we should close this and start a new issue from https://github.com/netdata/netdata/issues/531#issuecomment-227112338 to clearly specify "table charts", that are not based on time-series data.
