### ISSUE TITLE
Cassandra DB/Cluster monitoring

### ISSUE THREAD

**Issue by jeremyjpj0916** [netdata/netdata#3101]
I see Netdata supporting a good number of popular data stores, but one of the most up and coming enterprise db's apache cassandra has no exposure in netdata. Would love a way to run netdata on one of my cluster nodes and netdata do what it does best and start magically exposing db connection info, health, memory and size metrics if I gave it connection credentials localhost to login to csqlsh with or nodetool command results might help. I am still fairly new to Cassandra myself but it would be a neat feature. Just something to think about for the future 👍  .

**Comment by ktsaou** [comment]
Hi,

hm... probably something the JMX netdata plugin could take care of.

I see there is already some work for extracting cassandra metrics via JMX: https://github.com/ezbz/jmxtrans-lib/blob/master/cassandra/output/mycass01-cassandra.json

@simonnagl what do you think?

---

@jeremiah keep in mind netdata is a statsd server. So, you may be able to get the metrics into netdata by adapting that jmxtrans file to send metrics to statsd instead of graphite and then use a netdata synthetics statsd charts to compose nice looking charts from statsd metrics.

**Comment by simonnagl** [comment]
Hello,

I see there is a  [JmxInterface of Cassandra](https://wiki.apache.org/cassandra/JmxInterface#org.apache.cassandra.service.StorageProxy.Attributes.RecentRangeLatencyMicros). It will be quite easy to extend the configuration of the imx plugin to collect Cassandra metrics. As always it is the most work to specify which value should go into which chart. If someone does this work I can write the configuration.

Also I tried to run Cassandra in a docker container and connect to it via JMX but failed. I do not think this will be necessary to write the configuration for the metrics but would be helpful for testing. @jeremyjpj0916 if you know how to start a docker-container which exposes a JMX port without authentication please do so.

A restriction of the current JMX plugin is that it does not support authentication. For locally running instances this might not be an issue.

**Comment by jeremyjpj0916** [comment]
I personally have never worked with JMX before, it all sounds really interesting though. So JMX provides kinda a real time snapshot of applications running ontop of Java correct and at this point you just need to know how to translate the JMX values C* exposes into nice visuals?

**Comment by cakrit** [comment]
Hi @jeremyjpj0916,

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

Would you be willing/able to play this role?

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by Avik1993** [comment]
Hi, @jeremyjpj0916 were you able to make this work? 
I too am looking for something similar.

**Comment by phact** [comment]
I took a stab at this a few years ago. I was using DSE at the time but the same approach should work with C* given that it was just using JMX.

https://github.com/phact/dse-netdata-agent

Something to consider: cassandra has thousands of metrics and hitting jmx every second (to get the realtime benefits of netdata) may affect cluster performance. The statsd approach may be more performant if we can make it work.

**Comment by cakrit** [comment]
We probably need to start discussing this again, because we don't have a clear way forward. Perhaps investigate what other solutions are doing with Cassandra monitoring? Do we want to talk about `statsd` only, i.e. providing some default synthetic charts that people can customize?.

**Comment by ilyam8** [comment]
[Telegraf suggests](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cassandra) to use [`jolokia`](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/jolokia2) (JMX metrics via HTTP endpoint) plugin to get `Cassandra` metrics.

`Cassandra` metrics:

> http://cassandra.apache.org/doc/latest/operating/metrics.html

**Comment by ilyam8** [comment]
Closing this feature request and moving it to [our community forum](https://community.netdata.cloud/) for further discussion (link will be posted soon).
