### ISSUE TITLE
web_log: charts per URL

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#3111]
@l2isbad I think we should add an option to web_log plugin to support a limited number of charts per URL pattern (category).

In many cases, I need to setup alarms for each URL pattern about http error codes and timings.

So I suggest to add an option: `per_category_charts: true/false`.

When set to `true`:

1. a new family `url NAME` should be added per category (url pattern), with the following charts:
2. `web_log_XXX.url_YYY_detailed_response_codes` with context `web_log.url_detailed_response_codes`
3. `web_log_XXX.url_YYY_response_time` with context `web_log.url_response_time`
4. `web_log_XXX.url_YYY_bandwidth` with context `web_log.url_bandwidth`

Without this feature, to add alarms per URL, we have to use filtering, which multiplies the log file parsing resources.

What do you think? Is it something that can be done easily?

**Comment by ktsaou** [comment]
@l2isbad what do you think?

**Comment by l2isbad** [comment]
not sure about easily or not but i like the idea

**Comment by ktsaou** [comment]
looking forward for it...

**Comment by l2isbad** [comment]
in the first place will be added to the `go` version

**Comment by l2isbad** [comment]
This feature will be in `go` version (i added it already, but `web_log` should be rewritten to supprt high load, to it will take some time), `python` version will be dropped

**Comment by ilyam8** [comment]
implemented in https://github.com/netdata/go.d.plugin/pull/74

won't be added to python version

**Comment by mustasj** [comment]
Is there any documentation on how to use this? cant find it anywhere if it exist.

**Comment by ilyam8** [comment]
it is in go version, but i don't recommend to use it until https://github.com/netdata/go.d.plugin/pull/141 is merged

**Comment by mustasj** [comment]
Nice, the documentation will be located [here](https://docs.netdata.cloud/collectors/go.d.plugin/modules/weblog/) then?
Any eta on that?

**Comment by ilyam8** [comment]
> Nice, the documentation will be located [here](https://docs.netdata.cloud/collectors/go.d.plugin/modules/weblog/) then?

yes

> Any eta on that?

soon, i'll ping you
