### ISSUE TITLE
badge do not suppport other language

### ISSUE THREAD

**Issue by hhgzxn** [netdata/netdata#3117]
I used the label option with an non-english character, the badge did not appear the character.

**Comment by ktsaou** [comment]
Hi,

yes, you are right.

According to the badges API, the application server is required to know the width of the badge. To do this, netdata has a few heuristics: it knows the width of each character of the `verdana` font that is used by the badge.

It seems that we need to regenerate [this array of character widths](https://github.com/ktsaou/netdata/blob/fa98f961b828e58912aefd95c067b2a66075415f/src/web_buffer_svg.c#L12-L269) for more characters...

**Comment by cakrit** [comment]
@gmosx if you can help on how to get this, modifying the array shouldn't be an issue.
