### ISSUE TITLE
alarm when number of open files is getting near limit?

### ISSUE THREAD

**Issue by ChrisEt** [netdata/netdata#3202]
Hi,
we are having the problem that our (Java) server process is losing file handles. Depending on its workload, it takes a few weeks until it runs out of file descriptors and stops responding. Is there a way to detect this condition with a netdata alarm?
I found out that with `cat /proc/<PID>/limits` one can find out the current limits for a process (https://unix.stackexchange.com/questions/230346/how-to-check-ulimit-usage). I think the app plugin is running through the process tree and collecting the number of open files, so in theory it should be possible to create an alarm that goes off at 80% for example. However, I am not so deep into the netdata internals, so I don't know if such an alarm would be easy or difficult to implement. What do you think?
Kind regards,
Chris

**Comment by cig0** [comment]
Hi @ChrisEt, not directly related to your question but hopefully still helpful: assuming you're running a GN+Linux flavor, these links might prove useful for you guys:

https://unix.stackexchange.com/questions/139011/how-do-i-configure-logging-for-ulimits
http://www.linuxhowtos.org/tips%20and%20tricks/ulimit.htm
https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

HTH!

**Comment by ktsaou** [comment]
Hi,

Yes this feature would be nice.

**Comment by ChrisEt** [comment]
I investigated this a bit deeper:

The apps plugin at the moment only counts file descriptors that are actually files - no sockets, pipes, etc. This code can be found [here](https://github.com/firehol/netdata/blob/a769a134d9e94f89285863d5ebf72fa4808ee9cc/src/apps_plugin.c#L1679)

On the other hand, what counts against the total limit is the sum of _all_ file descriptors, I believe. netdata doesn't record this at the moment, I believe.

**Comment by ktsaou** [comment]
apps.plugin has many charts and counts all file descriptors.

The problem is somewhat different: apps.plugin cannot expose the number of metrics directly to netdata. they will be useless.

apps.plugin will have to calculate the percentage of fds used per process, and report to netdata the max percentage among the processes grouped to a target (chart dimension).

Then, netdata will provide an alarm, using the percentage already calculated by apps.plugin.

**Comment by jmunson** [comment]
Are there any plans to do what you just outlined so that an alarm can be created to send a warning before FDs get exhausted?

**Comment by sinshaamagi** [comment]
I am also getting the same error and netdata got stopped:

netdata ERROR : WEB_SERVER[static1] : POLLFD: LISTENER: too many open files - sleeping for 1ms - used by this thread 2, max for this thread 256 (errno 24, No file descriptors available)

**Comment by emper0r** [comment]
Could be help ?

[emper0r@devops ~]$ for x in /proc/[0-9]*
>   do fds=0
>      max=`awk '/^Max open files/ {print $4}' $x/limits 2>/dev/null` &&
>        for t in $x/fd/*; do fds=$((fds+1)); done &&
>        echo $((fds*100/max)) ${x##*/}
>   done | sort -rn | while read l
>   do pid=${l##* }; echo "$l `readlink /proc/$pid/exe`"; break; done

Result:  0 97

**Comment by vlvkobal** [comment]
Implemented in #10192.
