### ISSUE TITLE
About the OID

### ISSUE THREAD

**Issue by FANGXIANGQUAN** [netdata/netdata#3209]
Hi,
   When I configured the 64-bit OID in SNMP. Conf, the error. Log file indicated "NoSuchName", and then I changed to 32-bit OID. Is netdata currently not supported for 64-bit OID?

**Comment by ktsaou** [comment]
64bit counters are supported.
Could you please run the plugin in debug mode and post here the output?

**Comment by cakrit** [comment]
`noSuchName` is a standard SNMP response, meaning that an `snmpget` on that OID can't return a value. It could be a wrong OID or a [device issue](https://stackoverflow.com/questions/18595018/snmpget-returns-nosuchname-but-snmpwalk-works-not-a-instance-number-issue) . You can verify the validity of the OID via a simple SNMP GET. Please comment if you get a value from SNMP GET but not from Netdata.
