### ISSUE TITLE
Munin-like use case

### ISSUE THREAD

**Issue by FedericoCeratto** [netdata/netdata#3235]
Munin is somewhat aligned with Netdata's use case: quick deployment, lightweight enough to run on every host and on low power devices, zero maintenance and no RDBMS.
Yet it's also complementary to Netdata:
- Security: charts can be published as a static site.
- This also allows rsyncing charts from firewalled hosts to a public server without allowing any incoming connection.
- Long-term metrics, neatly divided in daily/weekly/monthly/yearly charts
- Metrics from multiple hosts
- Ability to hot-link images from HTML pages, dashboards, wikis, github etc without requiring js

Would you consider options like having a Munin exporter as part of Netdata or even having Netdata itself generate static sites natively or using a plugin? Thanks

Related to #397 and PNG graph generation in #1921 and #217

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.

**Comment by FedericoCeratto** [comment]
Related to #309 #397
