### ISSUE TITLE
netdata init.d script for SLES11SP4

### ISSUE THREAD

**Issue by idsecurity** [netdata/netdata#3246]
Hi,

I need some tips for getting netdata working.

I'm trying to get netdata running on a "soft appliance" running SUSE Linux Enterprise Server 11 SP4.

I've downloaded `kickstart-static64.sh` using another machine since I couldn't do it from the SLES11 machine since it has an old OpenSSL (0.9.8) version and it can't connect to the https://my-netdata.io site.

Anyway, I ran it with `bash kickstart-static64.sh`.

Afterwards I did the following:

1. `cp netdata-lsb /etc/init.d/netdata`
1. `chmod +x /etc/init.d/netdata`
1. `chkconfig netdata on`
1. I got this error:

    insserv: FATAL: service named has to be enabled to use service netdata
    insserv: FATAL: service apache2 has to be enabled to use service netdata
    insserv: FATAL: service httpd has to be enabled to use service netdata
    insserv: FATAL: service squid has to be enabled to use service netdata
    insserv: FATAL: service nginx has to be enabled to use service netdata
    insserv: FATAL: service mysql has to be enabled to use service netdata
    insserv: FATAL: service opensips has to be enabled to use service netdata
    insserv: FATAL: service upsd has to be enabled to use service netdata
    insserv: FATAL: service hostapd has to be enabled to use service netdata
    insserv: FATAL: service lm_sensors has to be enabled to use service netdata 

1. So I edited `/etc/init.d/netdata` and changed it to just require postfix:
   1. `# Required-Start:    $local_fs $remote_fs $network $named $time postfix`
   1.  `# Required-Stop:     $local_fs $remote_fs $network $named $time postfix`
1. Next I tried again: `chkconfig netdata on`, no errors
1. Tried to start it: `/etc/init.d/netdata start`
    1. Got: `/etc/rc.status: line 41: REDIRECT: unbound variable`
1. Edited `/etc/init.d/netdata` again, commented out `#set -u`
1. New try: `/etc/init.d/netdata start`
    1. I get: `/etc/init.d/netdata: line 34: log_daemon_msg: command not found`

I'm sure I can make an ugly hack and make it run but I rather have a supported way that can work on other machines as well.
Thanks.

This is the `/lib/lsb/init-functions`  file from the machine:

```
#
# Define init LSB shell functions
#

#
# Source SuSE's rc functions
#
. /etc/rc.status

#
# Be sure that  start_daemon, killproc, and
# pidofproc will be script functions.
#
function start_daemon ()
{
    /sbin/start_daemon ${1+"$@"}
}

function killproc ()
{
    /sbin/killproc ${1+"$@"}
}

function pidofproc ()
{
    /sbin/pidofproc ${1+"$@"}
}

#
# Logging of succes messages
#
function log_success_msg ()
{
    echo -en "$@"
    echo -e  "$rc_done"
}

#
# Logging of failure messages
#
function log_failure_msg ()
{
    echo -en "$@"
    echo -e  "$rc_failed"
}

#
# Logging of warn messages
#
function log_warning_msg ()
{
    echo -en "$@"
    echo -e  "${stat}${attn} warning${norm}"
}
```

**Comment by veksh** [comment]
Better write your own init script, it is easy :)

[netdata.init.d.txt](https://github.com/firehol/netdata/files/1957472/netdata.init.d.txt)

BTW to make openssl work again in sles 11 you need one from
 [security module](https://www.suse.com/documentation/suse-best-practices/singlehtml/securitymodule/securitymodule.html)

**Comment by ktsaou** [comment]
If you solved this, you can make a PR to add this into netdata.

Just for completeness, I have tried twice to get a free SLES license from SuSe to integrate netdata with SLES myself. SuSe people offered only one option: buy it.

I won't of course. I refuse to buy it. It is not about the cost, but I don't like this attitude. Open source is their business and they refuse to support open-source developers! 

In the contrary, RedHat has a developer program and has provided enough free licenses for all version of its OS.

So, I can't support SLES myself, until they decide to provide free developer licenses. Until then, for SLES support I can only accept PRs...

**Comment by veksh** [comment]
I've just pushed a [repo](https://github.com/veksh/netdata-sles11) with RPM spec to build SLES11 packages (missed init is not an only problem there). I could a PR from that if you wish.

**Comment by veksh** [comment]
BTW centos RPM was broken too last time I've checked (requires unresolvable "shadow" package).

**Comment by ktsaou** [comment]
> I could make a PR from that if you wish.

yes, this would be nice.

> BTW centos RPM was broken too last time I've checked (requires unresolvable "shadow" package).

can you post the commands you used to create it?

**Comment by veksh** [comment]
>> BTW centos RPM was broken too last time I've checked (requires unresolvable "shadow" package).

> can you post the commands you used to create it?

Cannot remember exactly -- maybe it was my fault; pre-built packages on https://packagecloud.io/netdata/netdata seem to be OK

**Comment by veksh** [comment]
> > I could make a PR from that if you wish.

> yes, this would be nice.

Ok, I'll try to do it today.

**Comment by cakrit** [comment]
Our RPMs still have issues and we're working on resolving them. Once they're ok, we'll update #6722 
Do we still have the bug with `kickstart-static64.sh` that you identified? Could you perhaps do a PR for that?

**Comment by Ferroin** [comment]
There's been no further response on this since @cakrit commented last year, and SLES11 is out of general support as of the end of this month.

Closing this for now. If it's still an issue, please comment and we'll reopen it.
