### ISSUE TITLE
Issue with "multiply_range" in snmp.conf

### ISSUE THREAD

**Issue by talkyy** [netdata/netdata#3255]
Hi, I am monitoring bandwidth of some switches via `snmp.conf`. One of them have 180 ports but there are some ports which I don't use (I use snmpwalk for these ports and no result). The ports that have no result with snmpwalk are 90 to 94. I set `"multiply_range" : [1 , 180]` and after restart netdata, many ports (88 to 89 and 95 to 106) not have value. Is there any way to use `multiply_range` except ports 90 to 94?
Thank you for your time!

**Comment by ktsaou** [comment]
Hi,

unfortunately there is no option to hide these charts yet.
I mark this as enhancement, to modify the snmp plugin to do it.
