### ISSUE TITLE
enable system alarms on freebsd

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#3267]
netdata supports many system alarms. However these alarms are only applied to linux by default.

it would be nice to verify the alarms that work on freebsd too.

This is a simple job:

Each alarm has this little line: https://github.com/firehol/netdata/blob/092f260d7ea1256d2802dc49ed6f71004a2029af/conf.d/health.d/disks.conf#L14

If the alarm works on freebsd, it should be changed to:

```
   os: linux freebsd
```

of course, to do so, we need to verify the alarms do work on freebsd. This is also simple: install netdata on freebsd, add `freebsd` on all those `os` lines and check the alarms modal.

There may be cases that the chart dimensions the alarm needs, are different under freebsd. In this case we should copy and paste the alarm and adapt it a bit, to work on freebsd.

> I won't do this work. If anyone is willing to spare some time on it, please do so. If you need help, just post here.

**Comment by Ferroin** [comment]
I can't exactly double check things (while I have a FreeBSD test system, I don't have the time or patience to set up tests for all the existing alarms), but I've got a pretty good idea of what alarms are likely to work as-is on FreeBSD.  In particular, I would expect the following pre-bundled alarms to just work:

* Apache
* Netdata backend checks
* Beanstalkd
* BIND rndc
* CouchDB
* Elasticsearch
* HAProxy
* ISC DHCPD
* LightHTTPD
* Memcached
* MongoDB
* MySQL
* named
* NGinx
* PostgreSQL
* Redis
* Squid
* Varnish
* web_log

I would expect FPing, IPFS and Retroshare to work if they have working FreeBSD ports (I'm not sure if they do or not).

I would expect BTRFS and mdstat to never work (I doubt the underlying software they care about will ever get a FreeBSD port).  Similar with netfilter, QoS, and the softnet stuff, as netfilter and softnet interrupts are really Linux things and the QoS data collection is rather system specific (it might be possible to write up a pf module for netdata though, and similar logic could then be used for these).

I would expect ZFS to probably work fine if it's collecting data through the normal ZFS API's (I think it is, but I have near zero experience with ZFS outside of using FreeNAS, so i don't know for certain).

As far as the core system metrics, it really just depends on the required metrics being collected.  The CPU usage and wait alarms should work fine out of the box, as should the RAM usage alarms and most of the disk alarms.

**Comment by ktsaou** [comment]
The following alarms are currently only for Linux:

```sh
# cd /etc/netdata/health.d
# grep -l "os: \?linux" *.conf
cpu.conf
disks.conf
entropy.conf
ipc.conf
memory.conf
net.conf
netfilter.conf
qos.conf
ram.conf
softnet.conf
swap.conf
tcp_conn.conf
tcp_listen.conf
tcp_mem.conf
tcp_orphans.conf
tcp_resets.conf
udp_errors.conf
```

of course, a few of them are linux specific (btrfs, netfilter, qos, etc). But the majority of them should also work on freebsd (@vlvkobal did a very nice job to use the same chart dimension names when possible).

**Comment by ktsaou** [comment]
This is implemented by @arch273 
Closing it.
