### ISSUE TITLE
Master node not work properly behind nginx when receiving stream from slave nodes

### ISSUE THREAD

**Issue by youyaochi** [netdata/netdata#3311]
I'm trying to run a netdata master node behind nginx following this [guide](https://github.com/firehol/netdata/wiki/Running-behind-nginx), but nginx seems block stream from slave node, and return 404:  

`192.168.1.135 - - [19/Jan/2018:03:33:39 +0000] "STREAM key=XXXXXXXXXXXX&hostname=135&registry_hostname=135&machine_guid=2f123e88-fb31-11e7-92e9-000c29b74c3c&update_every=1&os=linux&timezone=Asia/Harbin&tags= HTTP/1.1" 400 173 "-" "-" "-"`

And slave node output:  
`2018-01-19 11:51:39: netdata ERROR : STREAM_SENDER[135] : Failed to connect to '192.168.1.103', port '9998' (errno 111, Connection refused)`

BTW, i'm using `netdata 1.8.0-605-g0606aec_rolling` for master and slaves.

**Comment by ktsaou** [comment]
Sorry for the long delay in this response.

Netdata streaming is not HTTP. So, it cannot be proxies.
We are working on a new version of the streaming protocol that will use  websockets and will be HTTP proxy friendly.

**Comment by Ferroin** [comment]
More accurately, you can't proxy it via an HTTP proxy.  The stream proxy support in NGinx works fine for it, though that of course loses you most of the benefits of proxying it over just exposing it directly.
