### ISSUE TITLE
data-common-max and data-common-min sync delay

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#3319]
When charts on custom dashboards have `data-common-min` or `data-common-max`, they get aligned once they are refreshed.

For charts with an update frequency of a few seconds, this is acceptable.
However, for charts will delayed updates, this is annoying. The feature is effectively not there.

We should find a way to re-draw the visible charts when the common min or max changes.

**Comment by ktsaou** [comment]
@gmosx 	if you can't figure out the problem, based on the description above, ping me to explain it a bit more.

**Comment by cakrit** [comment]
@jacekkolasa do you get what this is? Can you add a prio please?

**Comment by jacekkolasa** [comment]
@cakrit i think it's even less than priority/low. This is not an issue in new dashboard, i think the problem exists only in old dashboard.js, but i'll double check that.

**Comment by ilyam8** [comment]
Closing this issue. @jacekkolasa, please reopen if have doublechecked this and it appears to be a problem in the new dashboard as well.

**Comment by jacekkolasa** [comment]
@ilyam8 thanks for closing, i confirm this is not happening anymore
