### ISSUE TITLE
Switch KSM metrics to being stacked instead of overlaid?

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#3327]
This is a followup to #3304.

Currently, on the low-level metrics graph for KSM, the `pages_shared` and `pages_sharing` metrics are displayed as overlaid transparent area graphs above zero, while `pages_unshared` and `pages_volatile` are displayed similarly below zero.

Given that none of these four metrics actually overlap, and that they aren't displaying direct variance of the same value (like the idle jitter metrics or the timing info provided by the `web_log` plugin), this method of displaying them really doesn't make much sense, and I propose that these be changed to instead be stacked graphs like the global CPU and RAM graphs are, as the change in the total value of each pair of metrics actually is relevant for some users.

**Comment by ktsaou** [comment]
That would be nice.

However, dygraphs does not support positive and negative numbers on the same stacked charts. Either positive, or negative, but not both on the same chart.

So, we have 3 solutions:

1. keep them as they are
2. turn all dimensions positive
3. split `mem.ksm` in 2 charts, one have only the positive dimensions and another having only the negative ones

What do you think?

**Comment by ktsaou** [comment]
btw, you can test it yourself. Edit `netdata.conf`, seach for `mem.ksm` and set `chart type = stacked`. netdata will do it, but the chart will be wrong.

**Comment by Ferroin** [comment]
Hmm, I'm really not sure.  I mean, ideally dygraphs would add support for this (I kind of understand why they don't have it though, it's a pretty unusual use-case), but I get that that's probably a much longer shot than anything we do locally.

Of the two options other than leaving things as they are, I think I like splitting them better (and having a little explanation of what each pair of metrics means, with the caveat that if split there's not really any point in having either chart be negative).

**Comment by cakrit** [comment]
Let's go with splitting them into two graphs. It's not web though, it should be done at the collector.
