### ISSUE TITLE
Add bluetooth metrics

### ISSUE THREAD

**Issue by bsphere** [netdata/netdata#3332]
can be very useful for IoT and embedded devices to get metrics like RSSI, tx/rx data, timeouts, connection drops, ...

**Comment by ktsaou** [comment]
Hi, yes it would be nice.

Any ideas how these can be collected? Are such metrics exposed by the kernel?

**Comment by bsphere** [comment]
maybe with bluez utils - https://wiki.archlinux.org/index.php/bluetooth#Troubleshooting

**Comment by ktsaou** [comment]
ok,

bandwidth is already there - this would include packet drops and other network interface level charts that are handled by netdata for all interfaces:

![screenshot from 2018-02-01 01-18-12](https://user-images.githubusercontent.com/2662304/35652791-e500a6c2-06ed-11e8-92dd-2d240fcf10e9.png)

I found the following commands:

```sh
# hcitool rssi DC:37:14:E7:14:1E
RSSI return value: -12

# hcitool lq DC:37:14:E7:14:1E
Link quality: 255

# hcitool tpl DC:37:14:E7:14:1E
Current transmit power level: 10
```

How can I get timeouts and connection drops?

**Comment by bsphere** [comment]
`hciconfig` show the number of TX/RX bytes, events and errors for each controller.

for doing something more efficient than running cli tools, the kernel has a Bluetooth Management API - https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt

it requires CAP_NET_ADMIN (root would have this) and can be used for:
1. information about open connections - https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt#n903

2. information about a specific connection (RSSI, TX_POWER) - https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt#n1911

3. device connected event - https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt#n3217

4. device disconnected event - https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt#n3250

5. device found event (scan) - https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/mgmt-api.txt#n3396

**Comment by l2isbad** [comment]
> for doing something more efficient than running cli tools

:+1: 

@vlvkobal  please [have a look](https://github.com/netdata/netdata/issues/3332#issuecomment-437761967). I looks like you can help there :smile:

**Comment by ktsaou** [comment]
I added "help wanted" and "priority/low".
Unless I am mistaken, this is not on our roadmap. So, let's wait for a contributor to take it over.

**Comment by cakrit** [comment]
Closing due to no interest/sponsor.
