### ISSUE TITLE
[Feature Request] BTRFS: Track filesystem error counter values for BTRFS volumes.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#3341]
So, one of the really neat things about BTRFS is that it provides counters that track the number of various types of errors that have occured for a given volume   In particular, it tracks five different types of errors per-device:

* Read Errors: Pretty self explanatory, if the device throws a read error, this counter gets incremented.
* Write Errors: Also pretty self explanatory.
* Flush I/O Errors: Not quite sure about this one myself, I've never seen it incremented on any filesystems I've dealt with, but it is there.
* Corruption Errors: BTRFS checksums all blocks on the filesystem by default.  This tracks checksum mismatches (though there may not be an associated -EIO sent to userspace when this gets incremented, BTRFS is smart enough to fall back to a backup copy if one exists).
* Generation Errors: Because it's a COW filesystem, BTRFS does generation tracking for each node in each of the various internal tree structures.  This tracks cases where an item has had what appears to be an invalid generation given the state of it's parent node.

It would be really awesome if netdata could track these values (bonus points if it shows both the current values, and 'current' error-rates), as that would make monitoring of BTRFS volumes exponentially easier.

I would work on this personally myself, but the it requires using an ioctl to fetch the data, and is a lot more involved than I'm comfortable working on considering the existing BTRFS data collection is done in C.  For reference for anyone who wants to implement this, the relevant code in the official BTRFS tools  for fetching this data is located in the `cmd_device_stats` function in [cmds-device.c](https://git.kernel.org/pub/scm/linux/kernel/git/kdave/btrfs-progs.git/tree/cmds-device.c) in the btrfs-progs source code.  I'll be more than happy to help out with testing and writing up the graph description.

**Comment by ktsaou** [comment]
nice!

Can you check if a non-root user can query these? If this is supported, this can be embedded in netdata. Otherwise it has to be an external setuid plugin.

**Comment by Ferroin** [comment]
The ioctl itself is root only (which I actually hadn't realized until you had asked), though it might work to just give the binary a particular capability instead of needing to make it SUID root.

**Comment by Ferroin** [comment]
Just double checked, the exact permissions check checks for either EUID=0 or CAP_SYS_ADMIN.

**Comment by Psykar** [comment]
Started having a bit of a look at this and I believe we can adapt https://github.com/knorrie/python-btrfs
(LGPL-3 licensed so should be OK)

I tested this as non root to get device stats standalone and it worked OK - so shouldn't be too difficult.

**Comment by ilyam8** [comment]
Closing this feature request and moving it to [our community forum](https://community.netdata.cloud/) for further discussion (link will be posted soon).
