### ISSUE TITLE
opensuse - installation by hand issues due to hardcoded libexec in netdata-installer.sh

### ISSUE THREAD

**Issue by c-ney** [netdata/netdata#3346]
When installing on opensuse via `netdata-installer.sh`, the ownership/permissions steps for the libexecdir fail. This is because the default libexecdir on opensuse is `/usr/lib`, which the `configure.ac` script adheres to, while in `netdata-installer.sh` it is hardcoded to `/usr/libexec`.

For my case, I just added `--libexecdir="${NETDATA_PREFIX}/usr/libexec" \` to the configure step. But I'm not sure if this is the *correct* way for everyone.

The output from the installation procedure showing the failures:

```
/home/user/devel/netdata % sudo ./netdata-installer.sh --dont-start-it --install /opt
...
[/home/user/devel/netdata]# chown -R root /opt/netdata/usr/libexec/netdata
chown: cannot access '/opt/netdata/usr/libexec/netdata': No such file or directory
 FAILED

[/home/user/devel/netdata]# find /opt/netdata/usr/libexec/netdata -type d -exec chmod 0755 \{\} \;
find: '/opt/netdata/usr/libexec/netdata': No such file or directory
 FAILED

[/home/user/devel/netdata]# find /opt/netdata/usr/libexec/netdata -type f -exec chmod 0644 \{\} \;
find: '/opt/netdata/usr/libexec/netdata': No such file or directory
 FAILED

[/home/user/devel/netdata]# find /opt/netdata/usr/libexec/netdata -type f -a -name \*.plugin -exec chmod 0755 \{\} \;
find: '/opt/netdata/usr/libexec/netdata': No such file or directory
 FAILED

[/home/user/devel/netdata]# find /opt/netdata/usr/libexec/netdata -type f -a -name \*.sh -exec chmod 0755 \{\} \;
find: '/opt/netdata/usr/libexec/netdata': No such file or directory
 FAILED

[/home/user/devel/netdata]# setcap cap_dac_read_search\,cap_sys_ptrace+ep /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin
Failed to set capabilities on file `/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin' (No such file
or directory)
usage: setcap [-q] [-v] (-r|-|<caps>) <filename> [ ... (-r|-|<capsN>) <filenameN> ]

 Note <filename> must be a regular (non-symlink) file.
 FAILED

[/home/user/devel/netdata]# chown root /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin
chown: cannot access '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin': No such file or directory
 FAILED

[/home/user/devel/netdata]# chmod 4755 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin
chmod: cannot access '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin': No such file or directory
 FAILED
...
```

**Comment by paulfantom** [comment]
Installer uses "${NETDATA_PREFIX}" for every path now. Seems that this is fixed. Please reopen if the bug still persist.

**Comment by RobDean69** [comment]
This bug appears to have re-occurred. When running the installer on an opensuse leap system I get:

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# chown -R root:netdata /usr/libexec/netdata 
chown: cannot access '/usr/libexec/netdata': No such file or directory
 FAILED   

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# find /usr/libexec/netdata -type d -exec chmod 0755 \{\} \; 
find: '/usr/libexec/netdata': No such file or directory
 FAILED   

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# find /usr/libexec/netdata -type f -exec chmod 0644 \{\} \; 
find: '/usr/libexec/netdata': No such file or directory
 FAILED   

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# find /usr/libexec/netdata -type f -a -name \*.plugin -exec chmod 0750 \{\} \; 
find: '/usr/libexec/netdata': No such file or directory
 FAILED   

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# find /usr/libexec/netdata -type f -a -name \*.sh -exec chmod 0755 \{\} \; 
find: '/usr/libexec/netdata': No such file or directory

and also:

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# mv /tmp/netdata-go-r04XEL/go.d.plugin-v0.5.0.linux-amd64 /usr/libexec/netdata/plugins.d/go.d.plugin 
mv: cannot move '/tmp/netdata-go-r04XEL/go.d.plugin-v0.5.0.linux-amd64' to '/usr/libexec/netdata/plugins.d/go.d.plugin': No such file or directory
 FAILED   

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# chown root:netdata /usr/libexec/netdata/plugins.d/go.d.plugin 
chown: cannot access '/usr/libexec/netdata/plugins.d/go.d.plugin': No such file or directory
 FAILED   

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# chmod 0750 /usr/libexec/netdata/plugins.d/go.d.plugin 
chmod: cannot access '/usr/libexec/netdata/plugins.d/go.d.plugin': No such file or directory
 FAILED   
I get similar errors when running the cron auto-updater.
