### ISSUE TITLE
Zoom and Pan Function Not Work in Self Develop Plug In

### ISSUE THREAD

**Issue by AllanYauCl** [netdata/netdata#3361]
In netdata the default update_every was 1 second.  I have write a plug-in for like following, **just this plug-in update every 60 seconds** and other charts using 1 sec. 

> cat hosts1min.chart.sh 
> :
> hosts1min_update_every=60
> :
> 

The plug-in was work, but  X-axis **can't zoom in/out Pan left/Right.** I suppose if update every 1 min, the X-axis can keep around 2.7 days data. However X-axis just display last 10 mins data. 

P.S.  Other charts zoom and pan was work. 

Does any setting or configure was miss?  

![image](https://user-images.githubusercontent.com/35894672/35483567-acbbaa44-047e-11e8-970d-334ef6d797ed.png)

**Comment by ktsaou** [comment]
This seems like a bug... I need to reproduce it.

**Comment by cakrit** [comment]
If this was a problem, it works fine now. The first two charts on the default dahsboard are system.cpu (with 1 sec update every) and system.load (with 5 sec update every). Panning/zooming works fine.
