### ISSUE TITLE
fping and influxdb measurement name

### ISSUE THREAD

**Issue by wccropper** [netdata/netdata#3378]
I currently have each client push data to an influxdb. I then graph the influxdb data in grafana. I have built a nice dashboard where it provides a multi-choice dropdown for all of the hosts whihc are templated variables from the tag value 'host'. I just added fping to my netdata install on my grafana server and configured several servers to be monitored.

The issue I have is due to the way the fping setup is installed, all measurements are stored with the hostnames in the measurements and with tag value equal to the grafana server running the fping. I have not been able to derive any variable from these measurement names within Grafana to create a multi-choice host option. is it possible to have netdata add a secondary tag value for the name of the host being pinged? I would see this as a feature request, but if someone can point me to the lace to add this myself I would be happy to do so.

EDIT: i actually would like to see if the measurement can be fping.latency.average, etc. with tags for all of the data by the pinged host. This would be the easiest way to integrate this right into the dashboard i already have in Grafana.

**Comment by ktsaou** [comment]
You are right - netdata cannot do this currently.
We should support this when we implement #807

Keep in mind though, that many people use the fping plugin in a mesh, so all servers ping all other servers. In these cases the observer is important.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
