### ISSUE TITLE
Simple way to disable alerts

### ISSUE THREAD

**Issue by andreyradygin** [netdata/netdata#3414]
I think it would be useful, if there was such option - through which, admin could disable any alert.
For example via template name for alert:

alerts to disable = *last_collected_secs inbound_packets_dropped *dropped_ratio

Of course glob should be supported as "for send charts matching" options for example.

**Comment by ktsaou** [comment]
You can edit the alarm and change the `to` line to `silent`. The emails sent and the dashboard, say the exact file and line for each alarm.

This will still run the alarm on the dashboard, but disable all notifications for it.

I usually not remove the alarms entierly. When I browse the dashboard I like to see that netdata has detected something, even if I don't want to be notified about it.

**Comment by andreioss** [comment]
Hmm, I see. This is an option!
Thanks for the help!

PS
And of course I found it on wiki, after you've told me :(

**Comment by clinta** [comment]
I think this kind of feature would still be helpful. I don't want emails for any of the `_last_collected` alarms. But to do this I need to copy each conf file that contains a last_collected alarm to modify it. And if I do that, I lose out on new alarms that are created as netdata is updated.

**Comment by cakrit** [comment]
I know it's not exactly what you need, but please look at https://docs.netdata.cloud/web/api/health/#health-management-api
Disabling alarms that way is not permanent (i.e. netdata will reset the disable at the next restart), but there may be a way to automatically issue a disable command every time netdata starts. It's just a workaround for now. We could possibly add an extension to use the same basic code to read disable or silence commands from the configuration as well.

**Comment by Ferroin** [comment]
@cakrit On that note, perhaps we should look into having the option of making the list of alarms disabled through the API persist across restarts?

**Comment by cakrit** [comment]
Hm, maybe a `save` health mgmt API command, to generate that config file. Though I'm not very comfortable with the daemon writing to the user config directory. Perhaps a 'show' that gives a plain text of the current configuration so the user can put it there themselves, similar to how we show netdata.conf?

**Comment by Ferroin** [comment]
@cakrit I was thinking more along the lines of having the state stored in `/var/lib/netdata` (or the equivalent), and just adding a command to the API to explicitly make the disabled state persistent (along with one to list which ones are in which state if we don't already have that).

**Comment by cakrit** [comment]
Sounds good to me. A `save` and a `list/show` it is

**Comment by cakrit** [comment]
@Ferroin I wrote the LIST, but I've reconsidered the SAVE command. It seems more natural to persist the configuration across restarts, so I will have netdata save it every time a command is issued. As a result, no SAVE is needed. The RESET command will explicitly restore to the default, clearing all silencers. It's much more user friendly this way, this setting has no reason to be affected by a restart.

**Comment by cakrit** [comment]
As part of this, we're making a bigger addition, putting in a JSON parser. Unfortunately I used some old wrappers that worked with a much older version of JSMN, so I'll throw away all the code in libnetdata/json/json.c and rewrite it with a new jsmn.c. Moving it to the next sprint for completion.
