### ISSUE TITLE
Plugin suggestion : nc

### ISSUE THREAD

**Issue by Vartkat** [netdata/netdata#3426]
Hi Costas,

A few days ago you give me the advice to use the fping plugin to monitor a remote machine. 
I succeeded in using it and it's a good solution but I faced a problem : some of my remote machines are behind NAT routers, and as the routers are proprietary I don't have any settings for telling the it to map an external ping to an inside server (I can't map ICMP). Here came the idea : would it be difficult to make an nc (nectat) plugin. 

If you never used it you can see (http://www.admin-magazine.com/Articles/Netcat-The-Admin-s-Best-Friend) how nectat is able to probe a port and return a "succeed" value. This would be a binary test, the remote machine is either alive or dead (no other info as answer delay and so on), but nc with mapped TCP or UDP port to a inside NAT machine can probe if the machine is alive even if the machine is behind NAT. It can even probe several servers behind the NAT asa far as each server as its own NAT external port mapped to it.

I took a look into the fping plugin code but I'm not a coder nor good enough with bash to do it.

Tanks for reading

Regards

V.

**Comment by l2isbad** [comment]
@Vartkat 
https://github.com/firehol/netdata/issues/3408#issuecomment-364659461

> I am also thinking of adding a tcp-ping plugin, that will connect to any tcp port and disconnect immediately, so that it will monitor any tcp service you like

.

**Comment by Vartkat** [comment]
@l2isbad 

Hi Iliya,

I didn't know tcpping so I dug a bit, discovered that there's a few utilities doing the same thing, i.e. sending SYN, waiting for SYN/ACK and sending RST so that the connection is not established. This seems to be the most elegant way to probe if someone is answering on a port, forget about wget or curl solutions.

I'm no expert bu I discovered that tcpping is more or less a script wrapped around tcptraceroute.
see http://www.darkskies.za.net/~norman/scripts/tcpping
and http://www.vdberg.org/~richard/tcpping.html
(perhaps that's not the tcpping you're about).

If this is what you were talking about, I see one problem, tcptraceroute is hopping on every router on the path which makes it slower than netcat. 

During my research I also found hping (but it's no longer maintained), and of course Nmap which is too heavy for what we ant to achive and which has its own implementation of netcat named Ncat. 
 
 From http://www.admin-magazine.com/Articles/Netcat-The-Admin-s-Best-Friend
 $ nc -v -z host port
 seems to me to be a good solution. The only thing is we have to find the word "succeeded!" or "timed out".

**Comment by l2isbad** [comment]
@Vartkat Oh, it was not my words. It's @ktsaou quote. He will implement it in C i believe.

**Comment by ktsaou** [comment]
yes, I'll do it inside netdata so that it will be available by default without any dependencies.

**Comment by ktsaou** [comment]
this is already implemented with:

- fping
- tcp_check
- http_check
