### ISSUE TITLE
cgroups: new UI required for containers

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#345]
After reading https://libvirt.org/cgroups.html, http://man7.org/linux/man-pages/man5/systemd.cgroup.5.html, etc. I understand systemd is using cgroups for controlling the resources per process, service, etc.

Today, netdata attempts to disable by default various cgroups. However this is not right. We have to invent a new UI for presenting all the system cgroups properly.

**Comment by ktsaou** [comment]
https://lists.freedesktop.org/archives/systemd-devel/2015-September/034177.html


 * systemd now optionally supports the new Linux kernel
          "unified" control group hierarchy. If enabled via the kernel
          command-line option 'systemd.unified_cgroup_hierarchy=1',
          systemd will try to mount the unified cgroup hierarchy
          directly on /sys/fs/cgroup. If not enabled, or not
          available, systemd will fall back to the legacy cgroup
          hierarchy setup, as before. Host system and containers can
          mix and match legacy and unified hierarchies as they
          wish. nspawn understands the $UNIFIED_CROUP_HIERARCHY
          environment variable to individually select the hierarchy to
          use for executed containers. By default, nspawn will use the
          unified hierarchy for the containers if the host uses the
          unified hierarchy, and the legacy hierarchy otherwise.
          Please note that at this point the unified hierarchy is an
          experimental kernel feature and is likely to change in one
          of the next kernel releases.  Therefore, it should not be
          enabled by default in downstream distributions yet. The
          minimum required kernel version for the unified hierarchy to
          work is 4.2. Note that when the unified hierarchy is used
          for the first time delegated access to controllers is
          safe. Because of this systemd-nspawn containers will get
          access to controllers now, as will systemd user
          sessions. This means containers and user sessions may now
          manage their own resources, partitioning up what the system
          grants them.

**Comment by ktsaou** [comment]
https://lists.freedesktop.org/archives/systemd-devel/2016-May/036583.html

The unified cgroup hierarchy added in Linux 4.5 is now supported.
          Use systemd.unified_cgroup_hierarchy=1 on the kernel command line to
          enable. Also, support for the "io" cgroup controller in the unified
          hierarchy has been added, so that the "memory", "pids" and "io" are
          now the controllers that are supported on the unified hierarchy.

          WARNING: it is not possible to use previous systemd versions with
          systemd.unified_cgroup_hierarchy=1 and the new kernel. Therefore it
          is necessary to also update systemd in the initramfs if using the
          unified hierarchy. An updated SELinux policy is also required.

**Comment by MelkorLord** [comment]
Hi,

With NetData 1.4 on Ubuntu 14.04, I'm using libvirt to manage a single VM named "vdesk". The display of the right menu bar on NetData is really weird compared to the very clean and organized LXC VMs : 
```
machine vdesk.libvirt-qemu
  +- cpu
  +- mem
  +- disk

machine vdesk.libvirt-qemu emulator
  +- cpu

machine vdesk.libvirt-qemu vcpu0
  +- cpu

machine vdesk.libvirt-qemu vcpu1
  +- cpu

machine vdesk.libvirt-qemu vcpu2
  +- cpu

machine vdesk.libvirt-qemu vcpu3
  +- cpu
```
Why so many sections?

For info, here is the part about the CPU in `vdesk.xml` 
```
  <cpu mode='host-passthrough'>
    <topology sockets='1' cores='4' threads='1'/>
  </cpu>
```

It would be nice to get the libvirt VMs organized as cleanly as the LXC VMs are :-)

**Comment by ktsaou** [comment]
this is very strange...

Can you post your `find /sys/fs/cgroup/ -type d` ?

**Comment by MelkorLord** [comment]
Sorry for the delay, busy life :-)

So here's your output. The same machine also hosts LXC VMs but they were stripped out for readability.
```
/sys/fs/cgroup/
/sys/fs/cgroup/systemd
/sys/fs/cgroup/systemd/user
/sys/fs/cgroup/systemd/user/0.user
/sys/fs/cgroup/systemd/user/0.user/52.session
/sys/fs/cgroup/hugetlb
/sys/fs/cgroup/hugetlb/user
/sys/fs/cgroup/hugetlb/user/0.user
/sys/fs/cgroup/hugetlb/user/0.user/52.session
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/perf_event/machine
/sys/fs/cgroup/perf_event/machine/vdesk.libvirt-qemu
/sys/fs/cgroup/perf_event/user
/sys/fs/cgroup/perf_event/user/0.user
/sys/fs/cgroup/perf_event/user/0.user/52.session
/sys/fs/cgroup/blkio
/sys/fs/cgroup/blkio/machine
/sys/fs/cgroup/blkio/machine/vdesk.libvirt-qemu
/sys/fs/cgroup/blkio/user
/sys/fs/cgroup/blkio/user/0.user
/sys/fs/cgroup/blkio/user/0.user/52.session
/sys/fs/cgroup/freezer
/sys/fs/cgroup/freezer/machine
/sys/fs/cgroup/freezer/machine/vdesk.libvirt-qemu
/sys/fs/cgroup/freezer/user
/sys/fs/cgroup/freezer/user/0.user
/sys/fs/cgroup/freezer/user/0.user/52.session
/sys/fs/cgroup/devices
/sys/fs/cgroup/devices/machine
/sys/fs/cgroup/devices/machine/vdesk.libvirt-qemu
/sys/fs/cgroup/devices/user
/sys/fs/cgroup/devices/user/0.user
/sys/fs/cgroup/devices/user/0.user/52.session
/sys/fs/cgroup/memory
/sys/fs/cgroup/memory/machine
/sys/fs/cgroup/memory/machine/vdesk.libvirt-qemu
/sys/fs/cgroup/memory/user
/sys/fs/cgroup/memory/user/0.user
/sys/fs/cgroup/memory/user/0.user/52.session
/sys/fs/cgroup/cpuacct
/sys/fs/cgroup/cpuacct/machine
/sys/fs/cgroup/cpuacct/machine/vdesk.libvirt-qemu
/sys/fs/cgroup/cpuacct/machine/vdesk.libvirt-qemu/emulator
/sys/fs/cgroup/cpuacct/machine/vdesk.libvirt-qemu/vcpu3
/sys/fs/cgroup/cpuacct/machine/vdesk.libvirt-qemu/vcpu2
/sys/fs/cgroup/cpuacct/machine/vdesk.libvirt-qemu/vcpu1
/sys/fs/cgroup/cpuacct/machine/vdesk.libvirt-qemu/vcpu0
/sys/fs/cgroup/cpuacct/user
/sys/fs/cgroup/cpuacct/user/0.user
/sys/fs/cgroup/cpuacct/user/0.user/52.session
/sys/fs/cgroup/cpu
/sys/fs/cgroup/cpu/machine
/sys/fs/cgroup/cpu/machine/vdesk.libvirt-qemu
/sys/fs/cgroup/cpu/machine/vdesk.libvirt-qemu/emulator
/sys/fs/cgroup/cpu/machine/vdesk.libvirt-qemu/vcpu3
/sys/fs/cgroup/cpu/machine/vdesk.libvirt-qemu/vcpu2
/sys/fs/cgroup/cpu/machine/vdesk.libvirt-qemu/vcpu1
/sys/fs/cgroup/cpu/machine/vdesk.libvirt-qemu/vcpu0
/sys/fs/cgroup/cpu/user
/sys/fs/cgroup/cpu/user/0.user
/sys/fs/cgroup/cpu/user/0.user/52.session
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpuset/machine
/sys/fs/cgroup/cpuset/machine/vdesk.libvirt-qemu
/sys/fs/cgroup/cpuset/machine/vdesk.libvirt-qemu/emulator
/sys/fs/cgroup/cpuset/machine/vdesk.libvirt-qemu/vcpu3
/sys/fs/cgroup/cpuset/machine/vdesk.libvirt-qemu/vcpu2
/sys/fs/cgroup/cpuset/machine/vdesk.libvirt-qemu/vcpu1
/sys/fs/cgroup/cpuset/machine/vdesk.libvirt-qemu/vcpu0
/sys/fs/cgroup/cpuset/user
/sys/fs/cgroup/cpuset/user/0.user
/sys/fs/cgroup/cpuset/user/0.user/52.session
```
If you need further info, this is a Ubuntu Server 14.04 host using the following relevant packages:
```
libvirt-bin         1.2.2-0ubuntu13.1.17
libvirt0            1.2.2-0ubuntu13.1.17
qemu-keymaps        2.0.0+dfsg-2ubuntu1.28
qemu-kvm            2.0.0+dfsg-2ubuntu1.28
qemu-system-common  2.0.0+dfsg-2ubuntu1.28
qemu-system-x86     2.0.0+dfsg-2ubuntu1.28
qemu-utils          2.0.0+dfsg-2ubuntu1.28
```

**Comment by ktsaou** [comment]
well, libvirt creates these cgroups. I pushed a commit that disables them by default.

**Comment by ktsaou** [comment]
@gmosx 	this is on our roadmap: provide a better dashboard menu for handling kubernetes and and hierarchical (nested) containers.

**Comment by cakrit** [comment]
We are working with high priority on a different implementation for Kubernetes monitoring, which means that there will be very little need for a cgroups hierarchy.
