### ISSUE TITLE
Update health reference documentation

### ISSUE THREAD

**Issue by ccremer** [netdata/netdata#3468]
I am writing alarm templates for new plugins. However, the health configuration [wiki page](https://github.com/firehol/netdata/wiki/health-configuration-reference) is missing some stuff. Namely:
* `units`: Missing completely. Specifically `up/down` documentation. When is it `up` or `down`? What about negative values? Can it be reversed? e.g. `down/up` or `!up/down`
* `options`: What are the options? Looking for inspiration I see one in the net template:
* special variables: In the example below there is `$1m_received_packets_rate`, but the dimension is `received_packets_rate`. What is `1m_` and what are the other options?
```
template: 10s_received_packets_storm
      on: net.packets
      os: linux freebsd
.... 
    calc: $this * 100 / (($1m_received_packets_rate < 1000)?(1000):($1m_received_packets_rate))    # <---$1m_xxx ?
    crit: $this > (($status >= $WARNING)?(5000):(6000))
 options: no-clear-notification                      # <---- this line
    info: the % of the rate of received packets in the last 10 seconds, compared to the rate of the last minute (clear notification for this alarm will not be sent)
      to: sysadmin
```

**Comment by ktsaou** [comment]
You are right. I should update the wiki...
