### ISSUE TITLE
netdata service fails to start - pfsense

### ISSUE THREAD

**Issue by JTT-JustTheTip** [netdata/netdata#3469]
Followed the guide for installation, used most recent packages etc 

Everytime I go to start netdata it fails with this output
`[2.4.2-RELEASE][admin@pfSense.localdomain]/root: service netdata start
Starting netdata.
Bad -c option
/usr/local/etc/rc.d/netdata: WARNING: failed to start netdata
[2.4.2-RELEASE][admin@pfSense.localdomain]/root:
`

No idea whats causing the issue, a bug?

**Comment by ktsaou** [comment]
hm... the startup script is for FreeBSD. Is pfsense different?

Until we figure this out, you can just run netdata directly and kill it when you want to stop it.

**Comment by JTT-JustTheTip** [comment]
How would I go about doing that? I'm only familiar with the standard service start and stop commands, I'm not the best with FreeBSD and Linux etc ahaha

Thanks

**Comment by sarlalian** [comment]
To run it on FreeBSD ... probably the same on pfsense
```bash
/usr/local/sbin/netdata -u netdata -P /var/db/netdata/netdata.pid
```

**Comment by Agent6-6-6** [comment]
I had the exact same issue a few days back installing netdata on pfSense 2.4.2. 

The `service netdata start` command threw up the same error. I did a lot to try work around it so unsure if I did something else which made it work using the following method:-

One thing I'd point out was that the versions of the prerequisite files noted on the wiki do not exist at the links noted. Some files have been deprecated to earlier versions, some are just missing as far as I can tell (newbie on linux so not 100% sure). 

I found the exact versions in other freeBSD repositories and used those (I flipped between versions to see if this was causing the error). I think in the end I went with the exact versions noted in the wiki. But I think I still got this error.

Also related is the instructions for modifying `rc.conf` to restart after each boot does not work on latest version 2.4.2 (unsure about earlier versions as have only just discovered netdata). Inside this file it notes this is not parsed or words to that effect.

The way I got it working with the `service netdata start` command was to add it as a shell command in the pfSense web interface and then reboot so it runs on starting pfSense. This seemed to make it work, but like I said I played around with a lot of things to try get it working, so may have unadvertenly done something else to get it going via this method.

JTT, under services>shellcmd add the following to see if it works for you as well, if it does wiki instructions might need to be reviewed?
![image](https://user-images.githubusercontent.com/36808164/36930790-4db3aa84-1f0d-11e8-8752-cdc08bb7207c.png)

**Comment by ktsaou** [comment]
hm... I understand we need someone that knows pfsense to provide proper instructions for installing netdata to it.

Any help, is really appreciated...

**Comment by Agent6-6-6** [comment]
I'll been testing a few things on a fresh install and will update here with some proposed changes to the wiki for comments (I'm no expert though on pfSense, but hopefully clearing up the instructions will help a few people). (note didn't seem to get the original posters error when running it in a VM, not sure if this is relevant)

I note that [https://doc.pfsense.org/index.php/Installing_FreeBSD_Packages](url) refers to the following text, noting as I've noted previously that rc.conf is not used on pfSense (still seems to be relevant on version 2.4 also).

> The usual rc.d scripts added to /usr/local/etc/rc.d/ will not function on a pfSense system. There is no rc.conf and one cannot be created as it will be deleted. A custom startup script must be created in /usr/local/etc/rc.d/ and its name must end with .sh and it must be marked executable (chmod +x), and it will run at boot time. Alternatively if it's something that can be started with a single command then it can easily be added as a <shellcmd> in config.xml.

So it would seem the easiest way is to simply do what I proposed adding it as a shellcmd in the GUI as netdata can be started with a single command if a user wants it to start on startup. This has the added benefit of also being backed up with your pfSense configuration for ease of deployment on alternative hardware.

I note one output error that I came across when trying the `service netdata start` command was as follows which referred to adding to rc.conf which appears to be incorrect on pfSense (I am assuming this is coming from netdata and would need to be tweaked within the netdata code for installs on pfSense as its misleading, probably referring to the procedure quoted above, or referring to adding it within the GUI as a shellcmd)
![image](https://user-images.githubusercontent.com/36808164/37057611-cfd734d6-21ec-11e8-8159-f4f99ddca46f.png)

**Comment by Agent6-6-6** [comment]
Draft changes to wiki for comment, appreciate if someone could follow the instructions and confirm this works for them also before wiki is altered:-
________________________________________________
To install netdata on pfSense run the following commands (within a shell or under Diagnostics/Command Prompt within the pfSense web interface).

Change platform (i386/amd64, etc) and FreeBSD versions (10/11, etc) according to your environment and change netdata version (1.9.0_1 in example) according to latest version present within the FreeSBD repository:-
Note first three packages are downloaded from the pfSense repository for maintaining compatibility with pfSense, netdata is downloaded from the FreeBSD repository.
```
pkg install pkgconf
pkg install bash
pkg install e2fsprogs-libuuid
pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/netdata-1.9.0_1.txz
```
To start netdata manually run `service netdata onestart`

To start netdata automatically at each boot add `service netdata start` as a Shellcmd within the pfSense web interface (under Services/Shellcmd). Shellcmd Type should be set to `Shellcmd`. Alternatively more information can be found in https://doc.pfsense.org/index.php/Installing_FreeBSD_Packages, for achieving the same via the command line and scripts.  

If you experience an issue with `/usr/bin/install` absense on pfSense 2.3 or earlier, update pfSense or use workaround from [https://redmine.pfsense.org/issues/6643](https://redmine.pfsense.org/issues/6643)
________________________________________________

**Comment by jkoopmann** [comment]
Hi,

how does this mitigate the

Bad -c option

problem on service start and service stop? Or does this not happen during startup (for a reason totally beyond me).


Regards,
   JP

**Comment by Agent6-6-6** [comment]
Hi, 

When I was getting the `Bad -c option` warning like the original poster, netdata would not start. However, using the same command during the boot process seemed to work (for me at least). 

No idea why either, suspect due to it being compiled for FreeBSD and happening to work on pfSense (which is based on FreeBSD) that there are small differences between the two which possibly cause the error.

Alternatively the other command noted in the current wiki does work for a one time start that is not persistent at startup. I suspect most people will want it to automatically start though at boot.

**Comment by JTT-JustTheTip** [comment]
I was unable to access netdata on 192.168.2.1:19999 after following the new instructions, not sure if the service is active or not, is there a simple way to check?

**Comment by jkoopmann** [comment]
Check if the process is running with ps. And the default config file has it listening on 127.0.0.1 only which also might be an explanation.

**Comment by JTT-JustTheTip** [comment]
Yeh netdata is running, how would i go about changing the config? or working around the issue?

**Comment by jkoopmann** [comment]
Find netdata.conf and adjust the appropriate line. Then restart the service. Probably /usr/local/etc/netdata

**Comment by JTT-JustTheTip** [comment]
Yes that worked, might be worth noting that in the docs, the binding IP needs changing, thanks for the help and the fix on this one guys.

**Comment by JTT-JustTheTip** [comment]
One thing to note is that the instance of netdata on pfsense is unable to detect my other instances of netdata in my network, this is the same with my freenas system too, is this a FreeBSD Netdata issue or a config issue on my part?

**Comment by Agent6-6-6** [comment]
I've got the same thing, also checking for updates doesn't seem to resolve (just does nothing, other instances on the network within docker containers tell me there are new commits). 

Could be something with the firewall itself blocking access? Has anyone resolved this aspect?

**Comment by Agent6-6-6** [comment]
Hi All

I've updated the wiki with the edits noted above regarding pfSense install.

If anyone has solved the detection of other Netdata instances and/or getting update checks to work on pfSense please provide instructions, so the wiki can be further updated. 

I'm not sure if its a firewall issue (needing saomething unblocked specifically when Netdata is running directly on the firewall hardware or a bug in Netdata on pfSense. Happy to try out any suggestions.

**Comment by dudleynyc** [comment]
It looks like there is a much simpler answer to this problem. The netdata rc.d script is calling netdata with the "-c" option which is used to specify a config file:

```
: netdata -h 
Options:
  -c filename        Configuration file to load.
                     Default: /usr/local/etc/netdata/netdata.conf
```


The problem, as you can see, is that the startup script doesn't provide the required filename argument for the -c option:
`command_args="-c -f ${procname} -u ${netdata_user} -P ${pidfile} ${netdata_args}"`

I simply added the required argument to resolve this problem:
`configfile="/usr/local/etc/netdata/${name}.conf"
command_args="-c ${configfile} -f ${procname} -u ${netdata_user} -P ${pidfile} ${netdata_args}"`

After this fix, netdata can be started and stopped with "netdata onestart" and "netdata onestop."

**Comment by netblues** [comment]
Version | 2.4.3-RELEASE 				(amd64) 				 				built on Mon Mar 26 18:02:04 CDT 2018 							 				FreeBSD 11.1-RELEASE-p7
-- | --


Doesn't seem to run.

Wiki needs update to
/root: pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/netdata-1.10.0.txz
Fetching netdata-1.10.0.txz: 100%    2 MiB 574.1kB/s    00:03    

BUT
 pkg install e2fsprogs-libuuid
Updating pfSense-core repository catalogue...
pfSense-core repository is up to date.
Updating pfSense repository catalogue...
pfSense repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        e2fsprogs-libuuid: 1.44.0 [pfSense]

Number of packages to be installed: 1

34 KiB to be downloaded.

Proceed with this action? [y/N]: y
[1/1] Fetching e2fsprogs-libuuid-1.44.0.txz: 100%   34 KiB  34.5kB/s    00:01    
Checking integrity... done (0 conflicting)
[1/1] Installing e2fsprogs-libuuid-1.44.0...
Extracting e2fsprogs-libuuid-1.44.0: 100%
ldconfig: warning: /usr/local/lib/e2fsprogs: No such file or directory

Might be unrelated though
added required argument as suggested above..
but I still get
service netdata onestart
Starting netdata.
Bad -c option
/usr/local/etc/rc.d/netdata: WARNING: failed to start netdata

and yes, the config file is there... 

Any ideas more than welcome

**Comment by jbridgma** [comment]
I tried to install Netdata on my actual pfSense system, and I ran into a hiccup where I had to map the ports around in netdata.conf in order to actually get routerip:19999 to resolve, but otherwise, it worked for me.
 
However, when I spun up a fresh new pfSense VM and tried installing Netdata on that, I ran into both of the errors described in the previous comment (with e2fsprogs-libuuid install and service netdata onestart).

I've got fairly extensive configs on my actual router, but most of them are firewall-type rules that I wouldn't think would have an impact on installing Netdata. The only packages I have installed are darkstat, openvpn-client-export, and pfBlockerNG.

I'll be trying to figure out if I can track down the difference between my actual router and the fresh VM that allowed the Netdata install to work. If there are any suggestions on how I can narrow that down, I'd welcome them.

**Comment by netblues** [comment]
Do you mean that by installing darkstat openvpn-client-export and pfblockerng netdata actually runs on a fresh install?

**Comment by jbridgma** [comment]
I meant that was the first test I was going to run unless somebody had a better idea. There must be _something_ about my router config that allowed Netdata to work on it, something that isn't configured on a fresh install - and I have a hard time imagining it's a firewall rule, so my first thought was to check the installed packages.

Unfortunately I have now completed that test, and still couldn't get Netdata to install. Spun up a fresh pfSense VM, installed darkstat/openvpn-client-export/pfblockerng, tried to install Netdata, and error'd out on e2fsprogs-libuuid and service netdata onestart.

I'll keep trying to track down the config difference here, but let me know if there are any suggestions on what else I should test for or how else to locate config differences.

**Comment by Agent6-6-6** [comment]
I ran into the same error `ldconfig: warning: /usr/local/lib/e2fsprogs: No such file or directory` when installing it a while back.

I can't remember exactly but I might have created that directory and tried a reinstall. Or I simply removed and reinstalled that package and it worked 2nd time round (I did a lot of things that may or may not have contributed to my final success in getting it working). 

Either way I got it working after that error, sorry I cannot be of more help.

I still have not solved getting the netdata instance to check for updates when on pfSense, anyone solved this?

**Comment by jbridgma** [comment]
I tried going to `/usr/local/lib/` on the router that I successfully installed Netdata on, and there is **not** an e2fsprogs directory in it.

This leads me to believe that the e2fsprogs warning isn't actually related to Netdata's `Bad -c option` error, but for the life of me I still can't find anything on the router where Netdata works that's different from the VM where it doesn't. I tried comparing the `netdata.conf` file to no avail.

**Comment by gannon145** [comment]
I'm having the same problem with the >Bad -c  option> . No idea how to fix it. I can get netdata running as a service using shellcmd, but cant stop or start after that. Also cant access ui or data.

**Comment by jbridgma** [comment]
> I can get netdata running as a service using shellcmd, but cant stop or start after that.

Can you provide some additional details on how you got it started using shellcmd? I'm not very familiar with shellcmd but as far as I can tell it appears to be intended for commands to run during boot up, and Netdata isn't starting for me on boot even with the suggested `service netdata start` added to shellcmd.

> Also cant access ui or data.

I actually had that problem as well, let's see if my fix works for you - I went to the `netdata.conf` file and added this block to the bottom (replace 192.168.0.1 address with your pfSense IP):

```
[web]
     bind to = 192.168.0.1:19999 127.0.0.1:19999
```

You might need to restart Netdata to get it to take though, which could be a pain considering it's not responding to stop/start commands for you.

**Comment by shinebayar-g** [comment]
Hello, I couldn't access Netdata dashboard after PfSense installation.
After come here, I've edited my ` file in `/usr/local/etc/netdata/netdata.conf` and changed binding IP 127.0.0.1 to PfSense IP. (192.168.0.1)

However Netdata didn't seem running. (Yes, I installed Shellcmd and saved that `service netdata start` command.)

Then I went to **Diagnostic/Command Prompt** and executed `service netdata start` and it gives `Cannot 'start' netdata. Set netdata_enable to YES in /etc/rc.conf or use 'onestart' instead of 'start'.`
(I am not sure editing that file is good idea, or should I?)

Netdata is running successfully by running `service netdata onestart` command.
How do make it run at startup.?

**Comment by tvories** [comment]
I am having this issue as well.  Any suggestions?

**Comment by shinebayar-g** [comment]
Hi @tvories edit /etc/rc.conf file manually and add `netdata_enable=YES`

**Comment by tvories** [comment]
The /etc/rc.conf file did not exist.  I created it and just tried to run it using `service netdata start` and `service netdata onestart` and neither worked.  I have not restarted the router yet.

**Comment by shinebayar-g** [comment]
I'm not at my PfSense box at the moment, but if your version is latest it was working for me following my approach. 2.4.3 Looks good maybe mine was similar.

First follow [this instruction](https://github.com/firehol/netdata/wiki/Installation#pfsense) on wiki page. Then try above steps.

**Comment by tvories** [comment]
That's where I started.  I followed those instructions exactly and still end up with the Bad -c option.

**Comment by tvories** [comment]
So, I uninstalled everything, set the binding to my router internal IP address, edited the /etc/rc.d.conf, and restarted.  It's working now!  Thanks for the help.  It only worked from the shellcmd plugin calling it at start.

**Comment by shinebayar-g** [comment]
Glad it worked!

**Comment by kachunkachunk** [comment]
I haven't been able to get Netdata to start (or remain started) on a Netgate SG-3100. It has an ARM Cortex-A9 (armv6) so some changes were needed to the typical package install instructions - basically, pick FreeBSD 11, armv6 branch, quarterly (since it's the only one updated), then All.

Note that this is my... n'th attempted at it, so I did not get errors following the e2fsprogs-libuuid install. But that may not actually matter, too. Still, I satisfied the warning by creating /usr/local/lib/e2fsprogs, just for good measure.

Anyhow, a runonce shows Netdata starting, but it appears to fail after about five seconds. The error.log file cites a lot of missing modules, commands, and general dependencies for functions, so I wonder if these are areas of interest before it's properly viable, too. I know a lot of these will be optional, but I don't know which ones are fatal, too. Are any fatal? I suspect Python was pretty unhappy and was last to die, and thus of particular interest.

A full error log is here: https://pastebin.com/3WVPvd6x
And here is a snippet of interest, at the bottom:
```
2018-09-01 00:48:31: python.d ERROR: plugin: main: module load source: 'cpuidle' => [FAILED]
2018-09-01 00:48:31: python.d ERROR: plugin: main: load source error : Shared object "libc.so.6" not found, required by "python2"
2018-09-01 00:48:33: python.d ERROR: plugin: main: module load source: 'sensors' => [FAILED]
2018-09-01 00:48:33: python.d ERROR: plugin: main: load source error : Undefined symbol "libsensors_version"
2018-09-01 00:48:34: python.d INFO: apache: localhost: check() => [FAILED]
2018-09-01 00:48:34: python.d INFO: apache: localipv4: check() => [FAILED]
2018-09-01 00:48:34: python.d ERROR: apache: localipv6: Url: None. Error: Failed to parse: ::1
2018-09-01 00:48:34: python.d INFO: apache: localipv6: check() => [FAILED]
2018-09-01 00:48:34: python.d ERROR: beanstalk: beanstalk: 'beanstalkc' module is needed to use beanstalk.chart.py
2018-09-01 00:48:34: python.d INFO: beanstalk: beanstalk: check() => [FAILED]
2018-09-01 00:48:34: python.d ERROR: bind_rndc: bind_rndc: Can't locate "rndc" binary or binary is not executable by netdata
2018-09-01 00:48:34: python.d INFO: bind_rndc: bind_rndc: check() => [FAILED]
2018-09-01 00:48:34: python.d ERROR: ceph: ceph: rados module is needed to use ceph.chart.py
2018-09-01 00:48:34: python.d INFO: ceph: ceph: check() => [FAILED]
2018-09-01 00:48:36: python.d ERROR: couchdb: localhost: Url: http://127.0.0.1:5984/_node/couchdb@127.0.0.1/_stats. Error: HTTPConnectionPool(host='127.0.0.1', port=5984): Max retries exceeded with url: /_node/couchdb@127.0.0.1/_stats (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x2176dbd0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1)'))
2018-09-01 00:48:36: python.d ERROR: couchdb: localhost: Url: http://127.0.0.1:5984/_active_tasks. Error: HTTPConnectionPool(host='127.0.0.1', port=5984): Max retries exceeded with url: /_active_tasks (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x216b4e70>, 'Connection to 127.0.0.1 timed out. (connect timeout=1)'))
2018-09-01 00:48:36: python.d ERROR: couchdb: localhost: Url: http://127.0.0.1:5984/_node/couchdb@127.0.0.1/_system. Error: HTTPConnectionPool(host='127.0.0.1', port=5984): Max retries exceeded with url: /_node/couchdb@127.0.0.1/_system (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x216b4f50>, 'Connection to 127.0.0.1 timed out. (connect timeout=1)'))
2018-09-01 00:48:36: python.d ERROR: couchdb: localhost: _get_data() returned no data or type is not <dict>
2018-09-01 00:48:36: python.d INFO: couchdb: localhost: check() => [FAILED]
2018-09-01 00:48:36: python.d ERROR: cpufreq: cpufreq: couldn't find a method to read cpufreq statistics
2018-09-01 00:48:36: python.d INFO: cpufreq: cpufreq: check() => [FAILED]
2018-09-01 00:48:36: python.d ERROR: dns_query_time: dns_query_time: 'python-dnspython' package is needed to use dns_query_time.chart.py
2018-09-01 00:48:36: python.d INFO: dns_query_time: dns_query_time: check() => [FAILED]
2018-09-01 00:48:36: python.d ERROR: dnsdist: dnsdist: URL is not defined or type is not <str>
2018-09-01 00:48:36: python.d INFO: dnsdist: dnsdist: check() => [FAILED]
2018-09-01 00:49:51: python.d ERROR: dovecot: localhost: Failed to connect to "::1", port 24242, error: [Errno 60] Operation timed out
2018-09-01 00:51:06: python.d ERROR: dovecot: localhost: Failed to connect to "127.0.0.1", port 24242, error: [Errno 60] Operation timed out
2018-09-01 00:51:06: python.d INFO: dovecot: localhost: check() => [FAILED]
2018-09-01 00:52:21: python.d ERROR: dovecot: localipv4: Failed to connect to "127.0.0.1", port 24242, error: [Errno 60] Operation timed out
2018-09-01 00:52:21: python.d INFO: dovecot: localipv4: check() => [FAILED]
```

Pretty sure there are unmet dependencies on my part right now, but I'd love some help and don't want to experiment _too much_ with the SG-3100 since it's my daily driver. I also have not rebooted the unit yet. I've considered it but felt I should share the stuff above first.

If I don't update again, the eventual reboot tonight did not help.

Hopefully this helps in this report, and... hopefully someone knows what's up.

**Comment by ktsaou** [comment]
@kachunkachunk did you solve it?

**Comment by kachunkachunk** [comment]
I was unfortunately unable to, no. Is there anything else I can provide, or try?

**Comment by ktsaou** [comment]
Unfortunately I don't know.
Any FreeBSD users watching this? Please help...

**Comment by xciter327** [comment]
On first look, I'm missing pf statistics, CARP statistics, IPSec monitoring does not seem, DHCP, DNS, NTP. Traffci shaper monitoring would be awesome to have too.

**Comment by ascl00** [comment]
For anyone else reading this and trying to resolve, the issue with the 'bad -c option' is not an error generated by the netdata binary itself, but rather from the sh command:
```bash
+ limits -C daemon su -m netdata -c 'sh -c "/usr/sbin/daemon  -c -f /usr/local/sbin/netdata -u netdata -P /var/db/netdata/netdata.pid "'
Bad -c option
```
The 'su' command is the one that generates this failure message:
```bash
: su -m netdata -c 'sh -c "kill -TERM 27751"'
Bad -c option
```
This makes no sense to me, the system scripts should work, and according to the man page, su -c takes a "class" argument, not a command argument.

That said, netdata has an option to run as a user, so we should be able to rely on that rather than having to use su, so a quick modification to the rc script and we are away:
```bash
: ps -aux | grep netdata
netdata 52010   4.7  2.9 268180 235356  -  SN   09:36        0:00.17 /usr/local/sbin/netdata -c /usr/local/etc/netdata/netdata.conf -u netdata -P /var/db/netdata/netdata.pid
netdata 52209   0.9  0.0   8896   3664  -  SN   09:36        0:00.12 /usr/local/libexec/netdata/plugins.d/apps.plugin 1
```

Note that I did need to edit /usr/local/etc/netdata/netdata.conf to change the "bind to" option to allow access from a different system.

So, the final rc script I ended up with is:
```bash
#!/bin/sh
#
# $FreeBSD: head/net-mgmt/netdata/files/netdata.in 488332 2018-12-25 17:16:06Z mmokhi $
#

# PROVIDE: netdata
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following line to /etc/rc.conf to enable netdata:
# netdata_enable (bool):        Set to "NO" by default.
#                               Set it to "YES" to enable netdata.
# netdata_args (str):           Custom additional arguments to be passed
#                               to netdata (default empty).
#

. /etc/rc.subr

name="netdata"
rcvar=netdata_enable

load_rc_config $name

: ${netdata_enable="NO"}

user="netdata"
pidfile="/var/db/netdata/${name}.pid"
procname="/usr/local/sbin/${name}"
command="/usr/sbin/daemon"
configfile="/usr/local/etc/netdata/${name}.conf"
command_args="${procname} -c ${configfile} -u ${user} -P ${pidfile} ${netdata_args}"

required_files="/usr/local/etc/netdata/${name}.conf"
run_rc_command "$1"
```


I am not a BSD guy, so if there are issues with this, please let me know! I just followed the shell scripts... anyway, hope this helps someone.

**Comment by JoelSlowik** [comment]
Hello,

I took @ascl00 comment one step further and simply ran at the shell prompt what the rc script is supposedt to do:

`/usr/local/sbin/netdata -c /usr/local/etc/netdata/netdata.conf -u netdata -P /var/db/netdata/netdata.pid`

This starts netdata up right away. However, simply adding the above command into a 'shellcmd' to run at startup does not have any effect on my machine. That's too bad. 

I then ran into these (relation being bad c option for a shell command):
https://forum.netgate.com/topic/121795/bad-c-option

> Thank you so much. But, If admin is also a kind of (and actually is) root user (it has 0 id) why couldn't admin able to run this command?

...

> The "admin" account shell is locked into the menu, it can't run commands like that (nor can it do scp)

https://unix.stackexchange.com/questions/427586/new-mysql-installation-on-pfsense-returns-bad-c-option-when-started?rq=1

> The error is because of some kind of bad escaping method in the freebsd service shell scripts. It tries to su -c 'sh -c "..."' when you specify a specific user to run a service as, and mysql seems to cause problems with this.
> 
> I went into /usr/local/etc/rc.d/mysql-server and commented out line 54 mysql_user="mysql" and changed line 55 to mysql_limits_args="-e" and now mysql starts properly because the aforementioned code is not executed.

so in the rc script i updated `user="netdata"` to `user="root"`. Now `service netdata start` works out of the gate, but shellcmd is still not starting the service on boot. still investigating this last piece.

**Comment by JoelSlowik** [comment]
@JTT-JustTheTip 

> 
One thing to note is that the instance of netdata on pfsense is unable to detect my other instances of netdata in my network, this is the same with my freenas system too, is this a FreeBSD Netdata issue or a config issue on my part?

I have this same issue. I'm guessing it has something to do with how freebsd jails work where netdata cannot send a signal to the registry? just a guess so far

**Comment by triDcontrols** [comment]
Tried it today, and get the same "Bad -c Option" on 2.4.4 P2 Release. Any success?

**Comment by dollarlongnecks** [comment]
I just ran into the "Bad -c Option" the other day, and I fixed it in 2 steps with info in this thread:

Change the binding IP in the config to match your pfSense LAN IP
Put 'service netdata **one**start' into Shellcmd and reboot

**Comment by Joshndroid** [comment]
> 
> 
> I just ran into the "Bad -c Option" the other day, and I fixed it in 2 steps with info in this thread:
> 
> Change the binding IP in the config to match your pfSense LAN IP
> Put 'service netdata onestart' into Shellcmd and reboot

Can confirm on installing nano package, changing bind address from 127.0.0.1 to my LAN IP and running second command even without reboot netdata was accessible and working

**Comment by cakrit** [comment]
@paulkatsoulakis let's get a VM set up with pfsense so we can replicate the issues here and provide fixes, based on the OS. 

@ilyam8, for https://github.com/netdata/netdata/issues/3469#issuecomment-438843055 we should probably get one or more separate issues created.

**Comment by ilyam8** [comment]
> I'm missing pf statistics, CARP statistics, IPSec monitoring does not seem to work, DHCP, DNS, NTP

> IPSec

netdata has [libreswan](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/libreswan) bash collector

> DHCP, DNS, NTP

python collecotrs.


> CARP statistics

What statistics? @xciter327 

> pf statistics

What statistics? @xciter327

**Comment by Fohdeesha** [comment]
@Joshndroid how did you install python36 in pfsense? Did it break anything? As you noted, the latest netdata installer errors out with: 

```
Installing netdata-1.13.0...
pkg: Missing dependency 'python36'
```

Also as he noted, the netdata install instructions on the netdata docs is incorrect, it says:
`pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/netdata-1.11.0.txz`

however you get a 404 as `netdata-1.11.0.txz` no longer exists. Looking in the directory the current file is `netdata-1.13.0.txz`.

**Comment by Fohdeesha** [comment]
The solution to installing the required python36 was obvious, I just looked in the same freebsd release dir:
`pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/python36-3.6.8_2.txz`

netdata installs and works fine now. However adding `service netdata start` to shellcmd as the netdata docs describe does not work, it errors out. I had change the shellcmd command to `service netdata onestart` and now it starts on boot succesfully.

**Comment by cakrit** [comment]
> However adding `service netdata start` to shellcmd as the netdata docs describe does not work, it errors out. I had change the shellcmd command to `service netdata onestart` and now it starts on boot successfully.

Can you please point to the documentation file that has the wrong instruction, or even better do a PR to fix it?

**Comment by Fohdeesha** [comment]
PR created: https://github.com/netdata/netdata/pull/5982

**Comment by cakrit** [comment]
PR merged. Thank you @Fohdeesha !
