### ISSUE TITLE
Web_log stops collecting data after logrotate.

### ISSUE THREAD

**Issue by vaheminasyan** [netdata/netdata#3492]
Hi.
I have configured web_log plugin to collect data from our nginx logs.
But every day after log rotate it stops collecting data until I restart netdata explicitly.
Is there any solution for this?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf#L70

**Comment by l2isbad** [comment]
I tested it and i see no "web_log stops collecting data after logrotate" problem in my case.

What i did (squid3):
1. run `web_log` in debug mode
2. sudo logrotate -f /etc/logrotate.d/squid3`
3. log file was rotated, `web_log` continued to work

**Comment by vaheminasyan** [comment]
Could you please tell me how to run web_log in debug mode. Maybe It'll help me to find the problem.

**Comment by l2isbad** [comment]
[mysql debug example](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins)

**Comment by l2isbad** [comment]
what's your log file name? `access.log`? without date or smth?

**Comment by vaheminasyan** [comment]
It's name is 

> api.access.log

**Comment by l2isbad** [comment]
I wanted to clarify whether the name remains the same after rotating. If yes it should work with default config.

**Comment by vaheminasyan** [comment]
Though it doesn't.
I've added a netdata restart command to nginx logrotate script. It shuld work I think.

**Comment by l2isbad** [comment]
Actually not. It will mask the problem.  ```LogService``` open `logfile` on every iteration. 

I suggest to https://github.com/firehol/netdata/issues/3492#issuecomment-369507338

and see if it fails and if yes post the debug here

**Comment by paulfantom** [comment]
@vaheminasyan did you manage to solve your problem?

**Comment by vaheminasyan** [comment]
Hi.
Sorry, I've changed my job and don't use netdata anymore.
Though I'll start using  sometime.

**Comment by paulfantom** [comment]
@vaheminasyan please reopen if needed.
