### ISSUE TITLE
Sophos UTM packet discarded every 1 second

### ISSUE THREAD

**Issue by ccremer** [netdata/netdata#3498]
Netdata is having a constant alarm. IPv4 packet loss, 600 packets in last 10 minutes = 1 per second.

This is likely the drop that `tcpdump -i vmbr456 port not 22` shows, as its pretty much once per second. Every other traffic looks OK.
```
17:48:53.186953 06:9f:00:eb:2c:07 (oui Unknown) > Broadcast, ethertype 802.1Q (0x8100), length 64:
        0x0000:  4153 4703 33d9 822b 37e1 7aa2 6c48 76dd  ASG.3..+7.z.lHv.
        0x0010:  6222 08de 0c00 0000 0000 0000 0000 0000  b"..............
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............
```
This happens on all 3 servers. Any ideas?

**Comment by ktsaou** [comment]
If you get a `.pcap` and open it on wireshark, does it identify this packet?
In general wireshark can provide a lot more information.

**Comment by ccremer** [comment]
I'm in the process of moving to another apartment. I won't have time to test stuff for a few weeks now...

**Comment by ccremer** [comment]
I finally figured out the source of this packet. It's none other than Sophos UTM. Since I have two boxes in active-passive high availability, they need a dedicated interface where they can talk to each other and keep the connection states in sync.

The packet described in the first comment is sent every 1 second. Thats why there is constantly an alarm triggered (the same one as in #1076). I think they are all being discarded.

I recently switched to openvswitch instead of linux bonding/bridge, but the issue persists.

Now Sophos UTM generally is deployed as hardware appliance. They specifically require that `eth3` is needed for HA sync and in physical, the cable is directly going from one appliance to the other underneath, no switch between. Same requirement applies to virtual appliance, but obviously there is a difference. Is it possible that the VM is additionally tagging on that iface? I have almost no control over that interface in the VM. The interface provided by openvswitch is tagging the traffic. But maybe it's better to leave it untagged? Is it being double tagged? 
Here is a screenshot of the interfaces:
![sophos_eth3](https://user-images.githubusercontent.com/12159026/43344165-183efe9a-91e9-11e8-9f30-45bbbaabe9c5.png)

@Ferroin Do you have an idea?

HA sync/failover works nonetheless, countless times proven.

**Comment by ccremer** [comment]
## This is what the help page provides:

The Interfaces & Routing > Interfaces > Hardware tab lists all configured interfaces showing information such as the Ethernet mode of operation or the MAC address. On Sophos UTM hardware devices, for each interface, auto negotiation can be enabled or disabled.

Auto Negotiation: Usually, the Ethernet mode of operation (1000BASE-T full-duplex, 100BASE-T full-duplex, 100BASE-T half-duplex, 10BASE-T full-duplex, 10BASE-T half-duplex, and so on) between two network devices is automatically negotiated by choosing the best possible mode of operation supported by both devices, where higher speed (e.g. 1000 Mbit/sec) is preferred over lower speed (e.g. 100 Mbit/sec), and full duplex is preferred over half duplex at the same speed.

Caution – For proper 1000 Mbit/sec operation, auto negotiation is always required and mandatory by IEEE Std 802.3ab. Thus, be careful to never switch Auto Negotiation off for any interface with Link mode 1000BASE-T. The timing of your network link may fail, causing service degradation or failure. For 100 Mbit/sec and 10 Mbit/sec operation, auto negotiation is optional, but still recommended for use whenever possible.

Auto negotiation is enabled by default. In the rare case that you need to switch it off, click the Edit button of the corresponding interface card and change the setting in the appearing dialog box Edit NIC Parameters via the drop-down list Link Mode. Note that the drop-down list is only available with Sophos UTM hardware devices. Click Save to save your changes.

Caution – Be careful when disabling auto negotiation, as this might lead to mismatches, resulting in a significant performance decrease or even disconnect. If the respective network interface card is your interface to WebAdmin you may lose access to WebAdmin!

In case one of your interfaces lost its network link due to manipulation of auto negotiation or speed settings, just changing the settings back will typically not bring the interface back to normal operation: Changing auto negotiation or speed settings on disconnected interfaces is not reliable. Therefore first switch on auto negotiation and then reboot Sophos UTM to bring back normal operation.

HA Link Monitoring: If high availability is enabled, all configured interfaces are monitored for link status. In case of a link failure, a takeover is triggered. If a configured interface is not always connected (e.g. management interface) please disable HA link monitoring for the corresponding interface. Otherwise all HA nodes will stay in status UNLINKED. To disable HA link monitoring click the Edit button of the corresponding interface card and change the setting in the appearing dialog box Edit NIC Parameters. Click Save to save your changes.

Set Virtual MAC: Sometimes it is useful to be able to change the MAC address of a device. For example, there are some ISPs where the modem must be reset when the device connected to it changes and by that the MAC address of that device. By setting the MAC address to the value of the former device, a reset of the modem can be avoided.

Sophos UTM, however, does not overwrite the original MAC address of the device but instead sets a virtual MAC address. To do so, click the Edit button of the corresponding interface card. In the appearing dialog box Edit NIC Parameters, select the checkbox Set Virtual MAC and enter a valid MAC address. Click Save to save your changes.

To restore the original MAC address, click the Edit button of the corresponding interface card. In the appearing dialog box Edit NIC Parameters, unselect the checkbox Set Virtual MAC. Click Save to save your changes.

Enable Power over Ethernet (PoE): This option is only available if the configured interfaces support PoE. If enabled, you can provide connected access points with electric power and data through one Ethernet cable.

**Comment by ccremer** [comment]
I can only assume that Sophos is doing something wonky with its HA setup. Once I disabled HS, the packet loss is almost gone.
So, closing this one.
