### ISSUE TITLE
Kubernetes Monitoring Improvement Ideas

### ISSUE THREAD

**Issue by geekhead** [netdata/netdata#3520]
First of all thanks for a great piece of software and the willingness to make it better. We currently have multiple Kubernetes clusters in our environment and wanted to share some improvements I would like to see in how netdata detects and monitors Kubernetes/docker containers and how that relates to cgroups.

First improvement I believe is that netdata should have it's own "Kubernetes" application section in the UI with sub groups/charts for PODs and containers and not pollute the right side menu bar. There is also enough concept differences between Docker and Docker running on K8s that warrants this as well in my opinion. So the way I see it working is you would have a K8s application, under that you have a list of POD names, and then under the PODs you have your list of containers. I'm not sure if netdata can support this or not.  

Second improvement is netdata adds unnecessary containers/PODs that do not need to be monitored and pollutes the UI as well as external systems like prometheus that pulls data from it.

Third improvement revolves around how netdata is naming K8s objects (PODs, containers, etc).

### CGROUP and K8s PODs/Containers
So when correlating containers/pods to cgroups, it's important to understand [QoS classes](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#qos-classes) that K8s assigns to PODs: Guaranteed, Burstable, or BestEffort. This directly relates to the full path a containers cgroup will live in. For example, let's assume I'm in the following working directory `/sys/fs/cgroup/cpu/kubepods` and I do an `ls`:

```
drwxr-xr-x. 2 root root 0 Mar  2 15:31 besteffort
drwxr-xr-x. 5 root root 0 Mar  8 10:38 burstable
-rw-r--r--. 1 root root 0 Mar  2 15:17 cgroup.clone_children
-rw-r--r--. 1 root root 0 Mar  2 15:17 cgroup.procs
-r--r--r--. 1 root root 0 Mar  2 15:17 cpuacct.stat
-rw-r--r--. 1 root root 0 Mar  2 15:17 cpuacct.usage
-r--r--r--. 1 root root 0 Mar  2 15:17 cpuacct.usage_percpu
-rw-r--r--. 1 root root 0 Mar  2 15:17 cpu.cfs_period_us
-rw-r--r--. 1 root root 0 Mar  2 15:17 cpu.cfs_quota_us
-rw-r--r--. 1 root root 0 Mar  2 15:17 cpu.rt_period_us
-rw-r--r--. 1 root root 0 Mar  2 15:17 cpu.rt_runtime_us
-rw-r--r--. 1 root root 0 Mar  6 13:12 cpu.shares
-r--r--r--. 1 root root 0 Mar  2 15:17 cpu.stat
-rw-r--r--. 1 root root 0 Mar  2 15:17 notify_on_release
drwxr-xr-x. 4 root root 0 Mar  8 09:41 pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec
drwxr-xr-x. 4 root root 0 Mar  8 09:41 pod87bbe673-1e6a-11e8-ab3b-06a6795d02ec
drwxr-xr-x. 5 root root 0 Mar  2 15:31 pod9cb7c6f6-029b-11e8-8ba7-063fdff58aa0
drwxr-xr-x. 4 root root 0 Mar  8 09:41 podffedb595-22dd-11e8-be53-06a6795d02ec
-rw-r--r--. 1 root root 0 Mar  2 15:17 tasks
```
You'll notice the two directories besteffort and burstable and any `pod[a-f][0-9]` sub-directories under those have that QoS class applied to it. Any pod directories currently listed in the output above have the guaranteed QoS applied to it. 

**Issue 1:** The issue right now is that netdata adds besteffort and burstable as a container to monitor and that should not be the case. We only care about the POD's and the containers that live under them and that's it. So what we want to do is monitor the cgroup folders with just `pod[a-f][0-9]` in the folder name which gives us an aggregated view of performance of all containers running under that pod and then the container ID's in sub-folders gives us the actual metrics for those specific containers. 

So let's `cd` into the burstable directory and see if we have any pod directories in there:
```
-rw-r--r--. 1 root root 0 Mar  2 16:51 cgroup.clone_children
-rw-r--r--. 1 root root 0 Mar  2 16:51 cgroup.procs
-r--r--r--. 1 root root 0 Mar  2 16:51 cpuacct.stat
-rw-r--r--. 1 root root 0 Mar  2 16:51 cpuacct.usage
-r--r--r--. 1 root root 0 Mar  2 16:51 cpuacct.usage_percpu
-rw-r--r--. 1 root root 0 Mar  2 16:51 cpu.cfs_period_us
-rw-r--r--. 1 root root 0 Mar  2 16:51 cpu.cfs_quota_us
-rw-r--r--. 1 root root 0 Mar  2 16:51 cpu.rt_period_us
-rw-r--r--. 1 root root 0 Mar  2 16:51 cpu.rt_runtime_us
-rw-r--r--. 1 root root 0 Mar  8 10:49 cpu.shares
-r--r--r--. 1 root root 0 Mar  2 16:51 cpu.stat
-rw-r--r--. 1 root root 0 Mar  2 16:51 notify_on_release
drwxr-xr-x. 4 root root 0 Mar  2 17:38 pod6a837235-1e6a-11e8-ab3b-06a6795d02ec
drwxr-xr-x. 5 root root 0 Mar  8 10:38 podb7d6aa9f-22e6-11e8-be53-06a6795d02ec
-rw-r--r--. 1 root root 0 Mar  2 16:51 tasks
```
So we have two pod directories `pod6a837235-1e6a-11e8-ab3b-06a6795d02ec` and `podb7d6aa9f-22e6-11e8-be53-06a6795d02ec` so let's cd into `pod6a837235-1e6a-11e8-ab3b-06a6795d02ec`:
```
drwxr-xr-x. 2 root root 0 Mar  8 10:56 98a2905a85d282046fb5c65580c6e066044bd5be740c3909132607763a9eaf1b
-rw-r--r--. 1 root root 0 Mar  8 09:59 cgroup.clone_children
-rw-r--r--. 1 root root 0 Mar  8 09:59 cgroup.procs
-r--r--r--. 1 root root 0 Mar  8 09:59 cpuacct.stat
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpuacct.usage
-r--r--r--. 1 root root 0 Mar  8 09:59 cpuacct.usage_percpu
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpu.cfs_period_us
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpu.cfs_quota_us
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpu.rt_period_us
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpu.rt_runtime_us
-rw-r--r--. 1 root root 0 Mar  2 17:38 cpu.shares
-r--r--r--. 1 root root 0 Mar  8 09:59 cpu.stat
drwxr-xr-x. 2 root root 0 Mar  8 10:56 e0407748d982456c509fc579676ada5a5953c48507c40642d1c67df788d63e7d
-rw-r--r--. 1 root root 0 Mar  8 09:59 notify_on_release
-rw-r--r--. 1 root root 0 Mar  8 09:59 tasks
```
So we have two containers running in this POD identified by `98a2905a85d282046fb5c65580c6e066044bd5be740c3909132607763a9eaf1b` and `e0407748d982456c509fc579676ada5a5953c48507c40642d1c67df788d63e7d`. These are the actual IDs for the containers and should be used when calling the K8s api or the docker sock and brings up multiple issues with how netdata implements this:

- **Issue 1:** Netdata by default uses the docker classic call to try to retrieve information about a container and this should never happen when dealing with K8s docker containers. We need to change this so that whenever *kubepods* is in the cgroup file path or some other method to detect it's a k8s container, that it always uses the API/docker sock like you have defined. 
  - More logic needs to be defined here so that kubepod overrides this even if the docker command exists: https://github.com/firehol/netdata/blob/master/plugins.d/cgroup-name.sh#L99
  - To validate this I changed the following line: https://github.com/firehol/netdata/blob/master/plugins.d/cgroup-name.sh#L138 to `docker_get_name_api "${DOCKERID}"`. 
- **Issue 2:** The evaluation expression here, https://github.com/firehol/netdata/blob/master/plugins.d/cgroup-name.sh#L129, does not work for all names. I added `set -x` to the top of that script and ran the following:

**This works:**
```
[root@localhost] /usr/libexec/netdata/plugins.d/cgroup-name.sh kubepods_burstable_pod6a837235-1e6a-11e8-ab3b-06a6795d02ec_51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55

+ CGROUP=kubepods_burstable_pod6a837235-1e6a-11e8-ab3b-06a6795d02ec_51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55
+ NAME=
+ '[' -z kubepods_burstable_pod6a837235-1e6a-11e8-ab3b-06a6795d02ec_51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55 ']'
+ '[' -f /usr/libexec/netdata/plugins.d/../../../../etc/netdata/cgroups-names.conf ']'
+ '[' -z '' ']'
+ [[ kubepods_burstable_pod6a837235-1e6a-11e8-ab3b-06a6795d02ec_51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55 =~ ^.*docker[-_/\.][a-fA-F0-9]+[-_\.]?.*$ ]]
+ [[ kubepods_burstable_pod6a837235-1e6a-11e8-ab3b-06a6795d02ec_51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55 =~ ^.*kubepods[_/].*[_/]pod[a-fA-F0-9-]+[_/][a-fA-F0-9]+$ ]]
++ echo kubepods_burstable_pod6a837235-1e6a-11e8-ab3b-06a6795d02ec_51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55
++ sed 's|^.*kubepods[_/].*[_/]pod[a-fA-F0-9-]\+[_/]\([a-fA-F0-9]\+\)$|\1|'
+ DOCKERID=51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55
+ echo DOCKERID=51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55
DOCKERID=51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55
+ '[' '!' -z 51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55 -a '(' 64 -eq 64 -o 64 -eq 12 ')' ']'
+ docker_get_name_api 51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55
+ local id=51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55
```
**This Does Not Work:**
```
[root@localhost] /usr/libexec/netdata/plugins.d/cgroup-name.sh kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166

+ CGROUP=kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166
+ NAME=
+ '[' -z kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166 ']'
+ '[' -f /usr/libexec/netdata/plugins.d/../../../../etc/netdata/cgroups-names.conf ']'
+ '[' -z '' ']'
+ [[ kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166 =~ ^.*docker[-_/\.][a-fA-F0-9]+[-_\.]?.*$ ]]
+ [[ kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166 =~ ^.*kubepods[_/].*[_/]pod[a-fA-F0-9-]+[_/][a-fA-F0-9]+$ ]]
+ [[ kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166 =~ machine.slice[_/].*\.service ]]
+ [[ kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166 =~ machine.slice_machine.*-qemu ]]
+ [[ kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166 =~ machine_.*\.libvirt-qemu ]]
+ [[ kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166 =~ qemu.slice_([0-9]+).scope ]]
+ [[ kubepods_pod69ef92e5-1e6a-11e8-ab3b-06a6795d02ec_70494ddb81ed7f0833570af95ef6fd584694b73b54cc472e1ab3b4bef9732166 =~ lxc_([0-9]+) ]]
```
- **Issue 3:** When you are calling the api, https://github.com/firehol/netdata/blob/master/plugins.d/cgroup-name.sh#L93, using the `.Name` field is not the best one to use and I make suggestions below in my "POD and Container Naming" section   

### Filtering out the pause container
So when detecting cgroups and k8s containers, there's one container type that needs to be filtered out from being detected and monitored and that's the K8s pause container. More information about it can be found here https://www.ianlewis.org/en/almighty-pause-container. In summary, the pause container in K8s serves as the "parent container" for all of the containers in your pod. It's basically the PID 1 for each pod and reaps zombie processes, that's it. We do not want to monitor it and only adds confusion to the list of containers in netdata. 

So using an example, here's how you would detect this. Let's assume we are still currently in the `pod6a837235-1e6a-11e8-ab3b-06a6795d02ec` cgroup directory:
```
drwxr-xr-x. 2 root root 0 Mar  8 10:56 98a2905a85d282046fb5c65580c6e066044bd5be740c3909132607763a9eaf1b
-rw-r--r--. 1 root root 0 Mar  8 09:59 cgroup.clone_children
-rw-r--r--. 1 root root 0 Mar  8 09:59 cgroup.procs
-r--r--r--. 1 root root 0 Mar  8 09:59 cpuacct.stat
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpuacct.usage
-r--r--r--. 1 root root 0 Mar  8 09:59 cpuacct.usage_percpu
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpu.cfs_period_us
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpu.cfs_quota_us
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpu.rt_period_us
-rw-r--r--. 1 root root 0 Mar  8 09:59 cpu.rt_runtime_us
-rw-r--r--. 1 root root 0 Mar  2 17:38 cpu.shares
-r--r--r--. 1 root root 0 Mar  8 09:59 cpu.stat
drwxr-xr-x. 2 root root 0 Mar  8 10:56 e0407748d982456c509fc579676ada5a5953c48507c40642d1c67df788d63e7d
-rw-r--r--. 1 root root 0 Mar  8 09:59 notify_on_release
-rw-r--r--. 1 root root 0 Mar  8 09:59 tasks
```
Using the docker.sock, we are going to make an api call and return the `.Config.Image` json value for container id `98a2905a85d282046fb5c65580c6e066044bd5be740c3909132607763a9eaf1b`:
```
echo -e "GET /containers/98a2905a85d282046fb5c65580c6e066044bd5be740c3909132607763a9eaf1b/json HTTP/1.0\r\n" | nc -U /var/run/docker.sock |grep '^{.*' | jq '.Config.Image'
"gcr.io/google_containers/pause-amd64:3.0"
```
Any container that contains this Image name needs to be filtered out and prevented from being monitored by netdata. 

### POD and Container Naming
It appears that you are trying to use the .Name json field for the container name but I would suggest a slightly better alternative. Using the container ID in our previous examples, here's the `.Name` field that netdata tries to use:
```
echo -e "GET /containers/51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55/json HTTP/1.0\r\n" | nc -U /var/run/docker.sock |grep '^{.*' | jq '.Name'
"/k8s_app_example-app-5b8d7c86f8-ht678_example-app_6a837235-1e6a-11e8-ab3b-06a6795d02ec_32"
```

This name field is fine for the chart label but not for the actual container name as it's too long and confusing when viewing in the netdata UI. Let's look at the `.Config.Labels`:
```
echo -e "GET /containers/51dfbb5816137555bbe237aec3ceaf54f1e7e570bd9c0005b79e1b3d93278c55/json HTTP/1.0\r\n" | nc -U /var/run/docker.sock |grep '^{.*' | jq '.Config.Labels'
{
  "annotation.io.kubernetes.container.hash": "87d9370c",
  "annotation.io.kubernetes.container.preStopHandler": "{\"exec\":{\"command\":[\"sleep\",\"15\"]}}",
  "annotation.io.kubernetes.container.restartCount": "32",
  "annotation.io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
  "annotation.io.kubernetes.container.terminationMessagePolicy": "File",
  "annotation.io.kubernetes.pod.terminationGracePeriod": "60",
  "build-date": "20180107",
  "io.kubernetes.container.logpath": "/var/log/pods/6a837235-1e6a-11e8-ab3b-06a6795d02ec/app_32.log",
  "io.kubernetes.container.name": "app",
  "io.kubernetes.docker.type": "container",
  "io.kubernetes.pod.name": "example-app-5b8d7c86f8-ht678",
  "io.kubernetes.pod.namespace": "example-app",
  "io.kubernetes.pod.uid": "6a837235-1e6a-11e8-ab3b-06a6795d02ec",
  "io.kubernetes.sandbox.id": "98a2905a85d282046fb5c65580c6e066044bd5be740c3909132607763a9eaf1b",
  "license": "GPLv2",
  "name": "CentOS Base Image",
  "vendor": "CentOS"
}
```
Let's break this down into the different names we need:

1. **POD Name:** When showing a POD name in the UI it should be using the `"io.kubernetes.pod.name"`. We also need `"io.kubernetes.pod.uid"` but that should only get included in the chart label for prometheus.
1. **Namespace Name:** This is obviously the `"io.kubernetes.pod.namespace"` field. This needs to be added to the chart label for prometheus.
1. **Container Name:** Use the `"io.kubernetes.container.name"` field.  

The `.Name` field is actually a combination of these with a prefix of `k8s`. So for example, this is how netdata currently is naming things from a prometheus viewpoint in the chart label:
```
netdata_cgroup_mem_usage_MB_average{chart="cgroup_kubepods_pod87bbe673_1e6a_11e8_ab3b_06a6795d02ec.mem_usage",family="mem",dimension="ram"}
```
What I would like to see for the chart label is more like this: `{container_name}_{pod_name}_{namespace}_{pod_uid}`
Which would then translate to:
`app_example-app-5b8d7c86f8-ht678_example-app_6a837235-1e6a-11e8-ab3b-06a6795d02ec` 

We also need to change the metric name as well if we are going to create a netdata application for K8s. So the full metric name with prometheus labels would look something like this:
```
netdata_k8s_mem_usage_MB_average{chart="app_example-app-5b8d7c86f8-ht678_example-app_6a837235-1e6a-11e8-ab3b-06a6795d02ec",family="mem",dimension="ram"}
```
If for some unknown reason to me that changing the metric name is not feasible, than I would suggest pre-fixing the chart name with a `k8s` which gets us back to what the `.Name` field almost provides us minus the `"annotation.io.kubernetes.container.restartCount"` at the end:
```
netdata_cgroup_mem_usage_MB_average{chart="k8s_app_example-app-5b8d7c86f8-ht678_example-app_6a837235-1e6a-11e8-ab3b-06a6795d02ec",family="mem",dimension="ram"}
```

I know this is a lot of information and hopefully most of it makes sense. Please let me know if you need any additional information and would love to work with you in making netdata better about monitoring K8s. Thanks!

**Comment by ktsaou** [comment]
ok, this is nice! Thank you for taking the time to help me with this.

So, we have 4 problems:

1. Select the right cgroups for monitoring
2. Give them proper names
3. Present them with the right hierarchy on the dashboard
4. Providing special information to backends (ie prometheus)

Allow me to deal with them, one by one:

## cgroups matching k8s containers

From your description, I understand that valid k8s containers are:

- `/kubepods/pod<GUID>/<docker_id_64_hex_characters>`, the guarranteed containers
- `/kubepods/burstable/pod<GUID>/<docker_id_64_hex_characters>`, the bustable containers
- `/kubepods/besteffort/pod<GUID>/<docker_id_64_hex_characters>`, the besteffort containers

Any other container under `/kubepods/` should be ignored.

Additionally all containers matched by the above rules, but with the substring `/pause` in their name should also be permanently ignored. IMPORTANT: I assume here that the containers that contain `/pause` in their name are fixed, ie. a paused container is always paused for its entire lifetime.

Do you agree with the container matches?

If yes, this is the plan:

- [ ] add support for regular expressions in netdata simple patterns (this is required because the inner cgroup is completely random - it should have a prefix to make our lifes easier)
- [ ] change the netdata defaults to match the above paths (and exclude everything else under `/kubepods/`)
- [ ] change the API of `cgroup-name.sh` to support also the keywork `DISABLE` to disable the paused containers

---

## naming k8s containers

I think is relatively simple to support the naming you propose:

- [ ] adapt the `cgroup-name.sh` to extract the information needed.

## 3-level hierarchy on the dashboard

If I have understood it right, the hierarchy should be:

- `kubernetes`
   a section for all k8s (everything about k8s will appear under this)

  - `applicationX`
      a section for each k8s application (all containers of the application will appear under this)

      - `containerX`
         a section for each container, much like it is today

I have to think a bit about this. I'll come with a solution.

---

## special info at the backends

netdata sends information to backends using as source the information of the charts. We need to discuss this a bit more. I need to find a universal way of supporting the additional info.

---

So, the key question now is if my description of the container matches is right. Let's build this, step by step...

**Comment by geekhead** [comment]
Sounds like a good start. Couple comments/suggestions:

### cgroups matching k8s containers
- When detecting the pause container, I would search for the full text `gcr.io/google_containers/pause` and not `pause` just in case people have the word `pause` in their container names for whatever reason, I'm sure there's some out there :). 
- The other logic you defined looks good

### 3-level hierarchy on the dashboard
The more I think about this, it might make things simpler to just do a 2-level hierarchy where it would look like this:
`Kubernetes` -> `POD Name` and `POD Name + Container Name` -> `cpu/mem graphs`

So it would look something like this:
- Kubernetes
  - example-app-5b8d7c86f8-ht678
    - cpu
    - mem
  - example-app-5b8d7c86f8-ht678 - app
    - cpu
    - mem
  - example-app-5b8d7c86f8-ht678 - web
    - cpu
    - mem
  - example-redis-1234
    - cpu
    - mem
  - example-redis-1234 - twemproxy
    - cpu
    - mem
  - example-redis-1234 - redis_6389
    - cpu
    - mem

Would doing it this way also make sending the chart information to the backends easier as well?

**Comment by geekhead** [comment]
@ktsaou Does my previous post make sense? Do you need any additional info from me? Thanks

**Comment by ktsaou** [comment]
It makes perfectly sense. The 3-level menu is probably the hardest, since it is not there already. But I think we will live with 2 levels until this is done in the dashboard.

To settle the other issues, I just need to get access to a kubernetes system to implement/try/test the changes. The changes do not seem that complicated. So, give me some time to get familiar with kubernetes... If you have a test system I can get access to for a few hours, it would save me a lot of time...

**Comment by geekhead** [comment]
I have multiple kubernetes systems but unfortunately I can't provide outside access to them but I can validate any code changes and PRs pretty quickly if you need feedback. Thanks

**Comment by shadycuz** [comment]
@geekhead until I get a dev environment up could you test this simple fix for issue 2? The regex that failed to catch cgroups with "burstable" in the name? 

https://github.com/shadycuz/netdata/commit/a8748acfa50ebc141ae65d21f6e46907abcd9076

**Comment by Ferroin** [comment]
@shadycuz  From what you were proposing in #3918, I don't think you're going to need to edit anything but HTML, JavaScript, and CSS.  The dashboard is a web application, but it's literally almost entirely client-side, and in theory, the dashboard is the only place code will need to change at all.

**Comment by cakrit** [comment]
As a first step to improve the support for Kubernetes we will implement a new collector that will utilize the available API, instead of cgroups. This issue will be  focused on the implementation of the new collector.

**Comment by shadycuz** [comment]
@cakrit I would still like to help on this feature. If I understand this right then a collector is a Netdata object to collect data and turn it into a format that can be rendered into charts/graphs. When you say available API I presume you mean the Kubelet on each node? and the last question which will determine how much I can help, is this collector going to be written in C? It's a weak point of mine 🤣

**Comment by shadycuz** [comment]
@cakrit @ktsaou Are you guys at re:invent in vegas? We could meet up.

**Comment by cakrit** [comment]
> I would still like to help on this feature. If I understand this right then a collector is a Netdata object to collect data and turn it into a format that can be rendered into charts/graphs. When you say available API I presume you mean the Kubelet on each node? and the last question which will determine how much I can help, is this collector going to be written in C? It's a weak point of mine 

Thanks @shadycuz we will definitely need a sponsor/power user to help us with meaningful presentation. @ilyam8 and @paulfantom will be discussing with you in this thread. The new collector will be either in Go or in Python.

**Comment by ktsaou** [comment]
> @cakrit @ktsaou Are you guys at re:invent in vegas? We could meet up.

hm... we missed this year. But next year we will be for sure.

**Comment by paulfantom** [comment]
> The new collector will be either in Go or in Python.

Preferably in go as this language has the best support for k8s.

**Comment by ilyam8** [comment]
I believe we agreed on renting server and installing/setting kubernetes there. It is hard to proceed on this without it.

@cakrit @paulfantom

**Comment by cakrit** [comment]
@paulfantom what do you think about doing it with GCE? https://kubernetes.io/docs/setup/turnkey/gce/
Should be really easy like this...

**Comment by paulfantom** [comment]
If you want to put an app into k8s, then GKE is fine. If you want full access, then you need to setup k8s cluster (preferably with kubeadm). I was already explaining that.

**Comment by cakrit** [comment]
I started the process in GKE, but it demands a billing account and we couldn't link it to our existing one because we reached the limit of linked projects. I submitted a request to increase the quota and we'll hear from Google in a couple of days. 

In the meantime, you can start Ilya with a local installation, with one of the methods here: https://kubernetes.io/docs/setup/pick-right-solution/#local-machine-solutions

**Comment by paulfantom** [comment]
If you want local development environment use either minikube or k-in-d (https://github.com/kubernetes-sigs/kind). If you have access to more computing power, just set up 3 VMs and use kubeadm: https://kubernetes.io/docs/setup/independent/install-kubeadm/

**Comment by gmosx** [comment]
Hmm, docker installations also include k8s these days. Not exactly sure how useful it's for development.

**Comment by paulfantom** [comment]
docker installations on Mac, linux doesn't come with k8s.

**Comment by ilyam8** [comment]
Ok, monitoring kubernetes cluster is a very complex task. This issue is about moniroing pods/containers (title is a little bit misleading).


> As a first step to improve the support for Kubernetes we will implement a new collector that will utilize the available API, instead of cgroups.

I installed `minnikube` and added some pods.

I see kubelet exposes all pods/containers metrics via `/stats/summary` endpoint (healthz server).

@geekhead Hi, i need your help here.

</br>
<details><summary>pod data</summary>
<p>

```json
{
    "podRef": {
        "name": "nginx-5c7588df-bn6br",
        "namespace": "default",
        "uid": "ca1a29f5-2e05-11e9-91f9-0800271a908f"
    },
    "startTime": "2019-02-11T14:03:21Z",
    "containers": [
        {
            "name": "nginx",
            "startTime": "2019-02-11T14:03:24Z",
            "cpu": {
                "time": "2019-02-11T19:16:50Z",
                "usageNanoCores": 0,
                "usageCoreNanoSeconds": 20713304
            },
            "memory": {
                "time": "2019-02-11T19:16:50Z",
                "usageBytes": 2375680,
                "workingSetBytes": 2314240,
                "rssBytes": 1409024,
                "pageFaults": 1155,
                "majorPageFaults": 19
            },
            "rootfs": {
                "time": "2019-02-11T19:16:50Z",
                "availableBytes": 13237149696,
                "capacityBytes": 17293533184,
                "usedBytes": 65536,
                "inodesFree": 9658751,
                "inodes": 9732096,
                "inodesUsed": 14
            },
            "logs": {
                "time": "2019-02-11T19:16:50Z",
                "availableBytes": 13237149696,
                "capacityBytes": 17293533184,
                "usedBytes": 28672,
                "inodesFree": 9658751,
                "inodes": 9732096,
                "inodesUsed": 73345
            },
            "userDefinedMetrics": null
        }
    ],
    "cpu": {
        "time": "2019-02-11T19:16:38Z",
        "usageNanoCores": 0,
        "usageCoreNanoSeconds": 40964297
    },
    "memory": {
        "time": "2019-02-11T19:16:38Z",
        "usageBytes": 2789376,
        "workingSetBytes": 2727936,
        "rssBytes": 1449984,
        "pageFaults": 0,
        "majorPageFaults": 0
    },
    "network": {
        "time": "2019-02-11T19:16:40Z",
        "name": "eth0",
        "rxBytes": 4594,
        "rxErrors": 0,
        "txBytes": 2652,
        "txErrors": 0,
        "interfaces": [
            {
                "name": "eth0",
                "rxBytes": 4594,
                "rxErrors": 0,
                "txBytes": 2652,
                "txErrors": 0
            },
            {
                "name": "sit0",
                "rxBytes": 0,
                "rxErrors": 0,
                "txBytes": 0,
                "txErrors": 0
            }
        ]
    },
    "volume": [
        {
            "time": "2019-02-11T14:04:14Z",
            "availableBytes": 1043763200,
            "capacityBytes": 1043775488,
            "usedBytes": 12288,
            "inodesFree": 254819,
            "inodes": 254828,
            "inodesUsed": 9,
            "name": "default-token-gk662"
        }
    ],
    "ephemeral-storage": {
        "time": "2019-02-11T19:16:50Z",
        "availableBytes": 13237149696,
        "capacityBytes": 17293533184,
        "usedBytes": 94208,
        "inodesFree": 9658751,
        "inodes": 9732096,
        "inodesUsed": 14
    }
}
```

</p>
</details>

</br>

___ 

## Pod data consists of 2 parts:
**Summary metrics**:
  * cpu
  * memory
  * netowrk
    * summary
    * per iface 
  * volume
    * per volume
  * ephemeral-storage

**Per container metrics**:
  * cpu
  * memory
  * logfs
  * rootfs
 
__

@geekhead 

1. Some sections may be missing because it is clean install, please compare with yours.
2. Do we need per pod or per pod per container charts? Both?

**Comment by ilyam8** [comment]
i need to understand:
 * what should we chart
 * which parts are dynamic (can be added/removed during pod/container lifetime) if there is any

**Comment by shadycuz** [comment]
@ilyam8 

At min you need the pod, but charting both gives a better picture. For example say you got `Pod-A` and its running 2 containers. You look at the memory of `Pod-A` its many times higher than what it should be, but which container is causing the problem? 

It's all dynamic 😉 I mean... The pod could be created/destroyed at any time. It could also be moved to another node in the cluster. The list of containers for any given pod are immutable per https://github.com/kubernetes/kubernetes/issues/37838

**Comment by ilyam8** [comment]
Hi @shadycuz 

> At min you need the pod, but charting both gives a better picture.

I totally agree, but we are limited by netdata 2 level dashboard menu.

> It's all dynamic

I understand it, i meant what section of pod are dynamic (new iface added, new volume added, something else added/removed).

**Comment by ilyam8** [comment]
> I understand it, i meant what section of pod are dynamic (new iface added, new volume added, something else added/removed).

ok, it is safe to assume that all things in pod are immutable (number of containers, number of volumes, number of nics).

thanks to @paulfantom

**Comment by ilyam8** [comment]
Ok.

Pod metrics:

**Summary metrics**:
  * cpu
  * memory
  * netowrk
    * summary
    * per iface 
  * volume
    * per volume
  * ephemeral-storage

**Per container metrics**:
  * cpu
  * memory
  * logfs
  * rootfs


1. I guess we don't need per iface metrics, summary network is enough. Am i right?
2.  Do we need ephemeral-storage metrics?
3. Do we need container logfs metrics?
4. Do we need container rootfs metrics?

**Comment by shadycuz** [comment]
I'm not sure it's completely safe to assume they never change. 

At first, I did agree 💯%.

Then I found an example of using the patch command on [pods](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#patching-resources).

But I thought to my self, no one really used pods as a stand alone, most people only use deployments. 

Then I remembered statefulsets. 

With a stateful set you will always have the same pod name, but that pod will change if the user updates the statefulset. You should rely on the `"uid": "ca1a29f5-2e05-11e9-91f9-0800271a908f"` of the pod.

I'm just supplying some ideas for you =). I would still keep going down the path you are taking.

**Comment by ilyam8** [comment]
ok, closing this in favor of #5387

**Comment by ilyam8** [comment]
I see that this issue has `area/web` label and 5387 doesn't resolve it, but that is the huge problem in general, not specific to kubernetes

**Comment by cakrit** [comment]
I'm reopening this one, as the cgroup filtering and naming is precisely what I'm currently working on.

**Comment by cakrit** [comment]
Leaving aside the presentation issue for the moment, the solution in #5576 is much simpler. 
When running in a kubernetes pod (which will be the only supported option), netdata will use the k8s `pod` API to convert cgroup directory paths to names. If an identifier is not returned by the API, `cgroup-name.sh` will exit with code 3 and netdata will disable the cgroup. The code currently in the PR is a working prototype, it will just need more testing and covering of certain cases.

I'll be adding more to the chart names than just the metdata name, by working on the jq of the following command, which returns the same data as the API. 
`kubectl get pods --all-namespaces -o json | jq -r '.items[].status.containerStatuses[0] | "\(.name) \(.containerID)"'`

**Comment by cakrit** [comment]
@geekhead and all, are we certain we need that name to be so long? 

See the following:
```
2019-03-07 00:08:08: cgroup-name.sh: INFO: k8s containerID 'e8426644f84f4e045c392c39b59f7bec4f49e590e14121a15916da513d6b2fdf' has chart name (namespace_podname_poduid_containername) 'k8s_default_foolhardy-seal-mysql-65988b95dc-8k267_ff4fb94a-3f42-11e9-92f9-dc6b03db3344_foolhardy-seal-mysql'
```

![Screenshot from 2019-03-11 13-04-34](https://user-images.githubusercontent.com/43294513/54123060-fef90e80-43fe-11e9-97a9-d264c3b20009.png)

Of course we could leave it like this until we update the UI to show something nicer and hierarchical.
