### ISSUE TITLE
Mobile Responsive Dashboards

### ISSUE THREAD

**Issue by Fieel** [netdata/netdata#3536]
Hello,

couldn't find a similar suggestion so here i am, what about the implementation of a mobile-friendly responsive dashboard? Wouldn't some html+css do the trick?

**Comment by Kiousis** [comment]
The dashboard is mobile friendly based on bootstrap v3.3 I think.

**Comment by Ferroin** [comment]
@Kiousis It tries to be mobile friendly, and IMO it does a far better job than many things do, but there are still a number of things that could greatly improve the UX on small touch-based devices.

Just off the top of my head:

* Being able to hide the chart descriptions completely would help the UX significantly.  Most aren't too bad, but some spots have enough text that it ends up taking up half the screen on my Nexus 6P, which makes it very difficult to look at and correlate data between adjacent charts.  I'd actually rather like to have this on the desktop version too, as I already know pretty much all of the info given by the chart descriptions.
* The chart legends hijacking scroll inputs even when they aren't long enough to need to be scrolled is a serious pain in the arse (I actually wish this wasn't the case on the desktop too, but it's less of an issue there).
* There's not any easy way to jump to a specific chart in the mobile layout.  Having something in the menu for this would greatly improve usability for people responding to complaints about a specific service on the system being monitored, as it's pretty common to just jump straight to the chart associated with that service.
* The menu with stuff like settings and alarm items taking up the whole screen is weird, it would be a lot nicer looking if it just panned in from the side while defocusing the rest of the page.  Not really bad UX, but presentation is important.

Note that I don't think a full redesign is needed, just some polish and a handful of usability improvements.

**Comment by l2isbad** [comment]
> There's not any easy way to jump to a specific chart in the mobile layout.

this is very annoying :cry:

**Comment by Kiousis** [comment]
Maybe a way users can share their custom dashboards gives back ideas for improvements in default dashboard too.

**Comment by ktsaou** [comment]
I agree, the mobile version needs some usability improvements.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
