### ISSUE TITLE
IRC notifications do not work

### ISSUE THREAD

**Issue by Rafi594** [netdata/netdata#3594]
Hello

I tried to add IRC notifications but they do not work. I have tried in several channels in freenode but I get no messages. I filled in the configuration with the documentation given in the wiki.

Thank you in advance for your help

**Comment by ktsaou** [comment]
@manosf please check this.

**Comment by manosf** [comment]
Hello @Rafi594,
I'd like some more information. Did you fill out every config option? Did you write the name of the channels with a `#` in front?
Also, could you provide an error message if there are any?

**Comment by Rafi594** [comment]
I tried with the # and without but no change I have no message that appears on the IRC channel. I just have this in the logs 
`alarm-notify.sh: INFO: sent notification for: server system.cpu.10min_cpu_iowait is WARNING to '#irc_channel'`

**Comment by manosf** [comment]
That's weird, test messages are appearing for me on both irssi and irccloud. Are you connecting to IRC through a dedicated client or via an app such as Riot.im?

**Comment by Rafi594** [comment]
I use irccloud but I also tried with irssi but still no notification

**Comment by Rafi594** [comment]
I just tried to connect to IRC with this command and I
```
nc chat.freenode.net 6667
: verne.freenode.net NOTICE *: *** Looking up your hostname ...
: verne.freenode.net NOTICE *: *** Checking Ident
: verne.freenode.net NOTICE *: *** Found your hostname
: verne.freenode.net NOTICE *: *** No Ident response
ERROR: Closing Link: 127.0.0.1 (Connection timed out)
```

**Comment by manosf** [comment]
This is because you have to provide every single field in order to connect to a network and join a channel.
Could you try setting the fields you want inside `/usr/libexec/netdata/plugins.d/alarm-notify.sh`  in these lines https://github.com/firehol/netdata/blob/master/plugins.d/alarm-notify.sh#L323-#L327?
I'm trying to identify where this is going wrong.

**Comment by manosf** [comment]
I seem to not find the problem unfortunately, every test works for me, both script and bash oneliners.
@ktsaou Could you run a test of this too according to the wiki, please? I'm really curious about what might be causing this problem.

**Comment by Rafi594** [comment]
I have tested in a second server and same problem. Telegram notifications work fine though

**Comment by cakrit** [comment]
Hi @Rafi594, if you still have a problem, let's try to see if we can help. Can you please follow the instructions [here](https://docs.netdata.cloud/health/notifications/#testing-notifications)?
