### ISSUE TITLE
Defining and displaying recurring tasks

### ISSUE THREAD

**Issue by Komic** [netdata/netdata#3600]
I would really like to be able to setup netdata to quickly identify recurring tasks happening on my machine directly from the dashboard; stuff like weekly S.M.A.R.T. self-tests, daily backups, that have an expected start time, duration, and impact.
Maybe those recurring tasks could also "disarm" alarms for a defined period of time, allowing admins to filter out useless noise? Is this something you would consider useful?

**Comment by Komic** [comment]
@cakrit Well, by defining periods of expected activity on the server in advance, we could both add a new layer of information to the netdata dashboard (what happens and when), and make already existing alarms more relevant (I don't care about my iowait metrics going up during a backup, for example).
Even better, by implementing some kind of API, whatever runs on the server could send a "hey, I'm starting this, ETA 2h/I'll ping you when I'm done" request to netdata, which could then display that stuff in real-time.

**Comment by paulfantom** [comment]
So this is essentially extending concept of silencing alarms (issues #2673 and #3187) with data analysis and forecasting.

**Comment by ktsaou** [comment]
This is also related to #312 	(annotations).
It is interesting approach to have annotations influence the alarms...

**Comment by cakrit** [comment]
Yes, this is a very good area for improvement and we can do a lot with it, by linking the various issues together and looking at them holistically. I'll try to group them together and get a design discussion together.

**Comment by cakrit** [comment]
Will follow up in #3187, closing this one as duplicate.
