### ISSUE TITLE
Apache Traffic Server(ATS) monitoring

### ISSUE THREAD

**Issue by jedblack** [netdata/netdata#3603]
First, allow me to say, thank you! -- what a simple, and effective platform for monitoring/telemetry.

We use ATS extensively and I'm wondering if there has been and thought or effort on an ATS plugin?

Its exposed via CLI or HTTP much in the same manner as mod_status or haproxy.  The data is formatted in JSON.

I can help test and provide the ATS infra to help drive the plugin development if that helps.

https://docs.trafficserver.apache.org/en/latest/admin-guide/monitoring/statistics/accessing.en.html

**Comment by l2isbad** [comment]
@jedblack hi

> I can help test and provide the ATS infra

It this still true?

**Comment by cakrit** [comment]
To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by cakrit** [comment]
Closing due to no sponsor.
