### ISSUE TITLE
OSSEC monitoring

### ISSUE THREAD

**Issue by Avamander** [netdata/netdata#3609]
Is there a way to get netdata could displaying the amount of events (banned hosts, event count) from  OSSEC's `active-response.log` and `ossec.log`?

Snippet from `active-response.log`:

```
N apr    5 22:00:00 EEST 2018 Unable to run (iptables returning != 1): 5 - /var/ossec/active-response/bin/firewall-drop.sh delete - [Censored IP] 1522956334.224182 31151
N apr    5 23:00:00 EEST 2018 /var/ossec/active-response/bin/host-deny.sh delete - [Censored IP] 1522956334.224182 31151
```

Snippet from `ossec.log` (trimmed a bit because there are a lot of repeating lines and it contains a lot of private information):
```
2018/04/05 00:00:00 ossec-monitord(1225): INFO: SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/04/05 00:00:00 ossec-logcollector(1225): INFO: SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/04/05 00:00:00 ossec-remoted(1225): INFO: SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/04/05 00:00:00 ossec-syscheckd(1225): INFO: SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/04/05 00:00:00 ossec-analysisd(1225): INFO: SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/04/05 00:00:00 ossec-maild(1225): INFO: SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/04/05 00:00:00 ossec-execd(1314): INFO: Shutdown received. Deleting responses.
2018/04/05 00:00:00 ossec-execd(1225): INFO: SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/04/05 00:00:00 ossec-syscheckd: INFO: Started (pid: 23497).
2018/04/05 00:00:005 ossec-rootcheck: INFO: Started (pid: 23497).
2018/04/05 00:00:00 ossec-syscheckd: INFO: Monitoring directory: '/folder', with options perm | size | owner | group | md5sum | sha1sum.
[Repeats per monitored directory]
2018/04/05 00:00:00 ossec-syscheckd: INFO: ignoring: '/folder'
[Repeats per ignored folder]
2018/04/05 00:00:00 ossec-logcollector(1950): INFO: Analyzing file: '/logfile'.
[Repeats per logfile]
2018/04/05 00:00:00 ossec-logcollector: INFO: Monitoring output of command(360): df -P
[Repeats per command output]
2018/04/05 00:00:00 ossec-logcollector: INFO: Started (pid: 23487).
2018/04/05 00:00:00 INFO: Connected to [Censored hostname]. at address [Censored IPv6 IP], port 25
2018/04/05 00:00:00 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2018/04/05 00:00:00 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2018/04/05 00:00:00 INFO: Connected to [Censored hostname]. at address [Censored IPv6 IP] port 25
```

**Comment by cakrit** [comment]
Apologies for the late response @Avamander. As Netdata is all about meaningful presentation, could you [help the developers understand what they have to do]( https://docs.netdata.cloud/contributing/#help-the-developers-understand-what-they-have-to-do)?

**Comment by Avamander** [comment]
@cakrit 

The way OSSEC data could be meaningfully displayed is displaying every alert level's count in a specified timeframe. Just like the nginx plugin shows the amount of 2xx and 4xx codes, the OSSEC plugin could show "alert level [0-13]" count. An additional metric would be the amount of "active response"-s. For example an increased amount of active responses indicates increased attempts at probing.

**Comment by l2isbad** [comment]
@Avamander 

Since you are the only `OSSEC` user here, please provide more details on logs.

Do we need to read both of this files? 
Which lines in `active-response.log`/`ossec.log`  are interesting to us?

**Comment by cakrit** [comment]
Hi again @Avamander 

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

Would you be willing/able to play this role?

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by Shellcat-Zero** [comment]
More broadly, I would love to see netdata supplant [OSSIM](https://en.wikipedia.org/wiki/OSSIM) for security information management.

**Comment by cakrit** [comment]
We need more active participation, in order to move forward with this collector. It's been stale for a long time, so closing until we get another comment here, indicating interest to become a sponsor.
