### ISSUE TITLE
Mosquitto Monitoring

### ISSUE THREAD

**Issue by vrst37** [netdata/netdata#3611]
Hello guys, I would like to monitor mosquitto (https://mosquitto.org/) server. Mosquitto is an open sourced MQTT broker that is going to be very popular when IOT hits the full cycle. I think having a feature to monitor mosquitto MQTT broker would be very nice. 

Is there existing support for mosquitto or is there a plan for it?

**Comment by cakrit** [comment]
Hi @vrst37. To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

Would you be willing/able to play this role?

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by ilyam8** [comment]
@LeenX :smile:

**Comment by LeeNX** [comment]
I have MQTT and mosquitto server ... Some Raspberry Pis ... Love ```netdata```, so quite willing to help where I can ... But don't know what we would monitor for mosquitto server ... ;-)  
  
Can docker the hell out of stuff, so point me at anything that I stumble throu and give feedback!

**Comment by vrst37** [comment]
Hi @cakrit thanks for such a welcoming response. It will be my pleasure to act as a sponsor.

I would recommend a python plugin for this would be very easy to write. The library to use in this case is **https://github.com/eclipse/paho.mqtt.python** 

**Specify the metrics required and how they should be presented in charts**:
We should take all the metrics (except version) presented to us in the broker status page at https://mosquitto.org/man/mosquitto-8.html
All of the plots will be line plots.

**Specify the alarms that would make sense for each metric.**: After the implementation, I will work on getting some alarms set up. However, this will vary from user to user. 

**When the implementation passes QA, test the implementation in production.**: More than happy to support anyone on this.

Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.: Already doing this

**Comment by vrst37** [comment]
I already have a monitoring system that is using the netdata's internal statsd client for uploading all the data to netdata and I have charts in netdata. However I think it will be better to have a native python client. Would you like to see that implementation? I think it will help a lot.

**Comment by vrst37** [comment]
Here is the implementation I have created:

https://github.com/vrst37/mqtt_netdata_plugin

**Comment by ilyam8** [comment]
>  and I have charts in netdata

please post them here

**Comment by vrst37** [comment]
Here are the screen shots

Number of bytes sent/received etc
![bytes](https://user-images.githubusercontent.com/34431050/49481280-1bbdee80-f7df-11e8-9139-49714ac08dcf.png)

Various status of clients for the broker
![clients_1](https://user-images.githubusercontent.com/34431050/49481281-1f517580-f7df-11e8-91fa-6a716bcbc21b.png)
![clients2](https://user-images.githubusercontent.com/34431050/49481284-211b3900-f7df-11e8-828b-9bb5c3865e7e.png)

Average number of connections to the broker
![connections](https://user-images.githubusercontent.com/34431050/49481288-24162980-f7df-11e8-8249-4c094ce735f7.png)

Number of retain messages and subscriptions on the broker
![counts](https://user-images.githubusercontent.com/34431050/49481291-26788380-f7df-11e8-85b1-a27d9a0ca5d3.png)

Number of messages sent, etc
![messages1](https://user-images.githubusercontent.com/34431050/49481294-28dadd80-f7df-11e8-991a-f5a8661e2163.png)
![messages2](https://user-images.githubusercontent.com/34431050/49481296-2aa4a100-f7df-11e8-990d-25ed9ffef338.png)

How many publishes have been done on this broker
![publishes1](https://user-images.githubusercontent.com/34431050/49481300-2d06fb00-f7df-11e8-8cd2-5c0a5345c852.png)
![publishes2](https://user-images.githubusercontent.com/34431050/49481304-2f695500-f7df-11e8-9d86-1da5e775789d.png)

This chart shows how many sockets are opened and what is the broker uptime
![sockets_and_uptime](https://user-images.githubusercontent.com/34431050/49481309-31331880-f7df-11e8-9657-83a8a356da21.png)

This is how the thing should show up in the side bar of the netdata monitoring page
![sidebar](https://user-images.githubusercontent.com/34431050/49481312-33957280-f7df-11e8-932e-248d7c26a763.png)

**Comment by vrst37** [comment]
Let me know if you want higher quality graphs, and I will generate them for you.

**Comment by ktsaou** [comment]
May I suggest a new grouping?

- Family `Bytes` should by `traffic`
- `bytes_received` and `bytes_sent` should be on the same `area` chart, with `bytes_sent` having a multiplier of `-1` (to be negative)

- I am not sure if `Clients` are counters or gauges. If they are counters, they refer the rates, not absolute numbers (i.e. `connected/s`, `expired/s`, etc). In all cases, the 3 first charts could be combined to one (connected, disconnected, expired).

- etc

Generally:

- we should group metrics into charts based on their meaning and units and then charts into families with their function. So, `Bytes` and `Counts` are bad grouping, but `traffic`, `clients`, `connections`, `messages`, `publishes`, etc are good ones.

- Also, counters in netdata should be presented as `rates`.

Let me know if you need more help with this.

In the charts I see the values are updated every 5 or 10 seconds. I don't know if this is how the plugin collects them, or if the server updates its statistics less frequently. Can you check collected metrics vary per second?

**Comment by vrst37** [comment]
@ktsaou 

Quoting from mosquitto configuration page:

> Clients can find information about the broker by subscribing to topics in the $SYS hierarchy as follows. Topics marked as static are only sent once per client on subscription. All other topics are updated every sys_interval seconds. If sys_interval is 0, then updates are not sent.

So update rates can be different for different users (as per their config file). How do you propose we handle this for mosquitto?

**Comment by vrst37** [comment]
I agree with the grouping comment made by @ktsaou . I think it makes more sense.

So are we planning to take the statsd route? (I really hope not).

**Comment by ilyam8** [comment]
@vrst37 do you familiar with `go`?

We are working on [go.d.plugin](https://github.com/netdata/go.d.plugin). It has stable API for new modules. If you are willing to wrote the module please do. I can help you with it.

**Comment by vrst37** [comment]
Hi @ilyam8 I have never developed a code in Golang. I can give it a shot if you guys like. But is there any problem with Python? Most of the code is already developed in python. We just have to go through some refactoring (I think).

**Comment by ilyam8** [comment]
> I have never developed a code in Golang

If you can do it in `python` please do, it's ok too.

We have a plan to move `python` stuff to `go` (no dependencies, one binaray, etc etc) but this is not asap.

**Comment by ilyam8** [comment]
And no `statsd` way please :smile:

**Comment by ilyam8** [comment]
if you need any help feel free to ask, if you want to have a chat with me  and you have [telegram](https://telegram.org/) you can find me there (`ilyam8`)

**Comment by ilyam8** [comment]
@vrst37 do you still have plans to work on the module?

**Comment by vrst37** [comment]
yes

**Comment by cakrit** [comment]
We're picking this up. Part of our new cloud infrastructure as well.

**Comment by ilyam8** [comment]
Ok, so there is [`$SYS/#`](https://github.com/mqtt/mqtt.github.io/wiki/SYS-Topics) topic we can subscribe and count events.

It doesnt sound difficult, just subscribe and increment counters based on topic.

**Comment by ilyam8** [comment]
I see `priority/high` label, i think i will try to implement it next sprint.

**Comment by jamesbiederbeck** [comment]
What's the current state of this? I'd be happy to test anything currently in progress.

**Comment by dannysauer** [comment]
Is there code in a branch somewhere that someone interested could perhaps contribute to, @ilyam8?  Is the plan to start anew in go, or iterate on https://github.com/vrst37/mqtt_netdata_plugin?  Maybe lifting some code from the Prometheus exporter work done at https://github.com/sapcc/mosquitto-exporter?

**Comment by OdysLam** [comment]
Hey @dannysauer, 

We are under internal deliberations for improving our collector coverage. In general, the best approach would be to implement in Golang using the python collector as a basis for how to gather data and organize metrics into charts. 

We are actively looking for contributors, so if you take a whack at it, we will be able to actively help you. We have a whole community category dedicated to this:
https://community.netdata.cloud/c/agent-development/9

**Comment by ilyam8** [comment]
Closing this feature request and moving it to [our community forum](https://community.netdata.cloud/) for further discussion (link will be posted soon).

**Comment by jhgorse** [comment]
Where is this conversation continued?

The use cases of interest are:
1) MQTT as a transport with a generic collector on the other end. Spec the schema for generic real-time data collection, point it at the topic(s), profit.
2) Subscribe to raw data feed via MQTT. Parse raw data into above schema then push the data to netdata.

Cheers,
Joe

**Comment by Idun0** [comment]
> Closing this feature request and moving it to [our community forum](https://community.netdata.cloud/) for further discussion (link will be posted soon).

Where's the link to the community forum for this discussion?

**Comment by ww7** [comment]
@ilyam8 support for MQTT still planned?

Forum discussion is not existing
