### ISSUE TITLE
[Feature] MySQL - mysql connection total & per user graphs

### ISSUE THREAD

**Issue by gdelafond** [netdata/netdata#3620]
Hello,

I think it could be nice to have the following graphs : 
- number of current connection number (absolute not incremental like the current graph "mysql Connections")
- number of current connection number by user (absolute)
- connection/s by user

Request to get the current connected user list :  `SELECT USER FROM information_schema.processlist`

And an alert on the "current connection number" may be nice too (the max is handle by the  `max_connections` MySQL variable).

Beware it will need the "PROCESS" privilege to have all process infos (if you do not have this privilege, you will only see the current user processlist).

With the information in `information_schema.processlist`, we could also have graph for 
- number of connection by databases (`SELECT DB FROM information_schema.processlist`)
- number of connection by hosts (`SELECT HOST FROM information_schema.processlist`)
- current connection command type (`SELECT COMMAND FROM information_schema.processlist`)
- current command state (`SELECT STATE FROM information_schema.processlist`)

Do you think that it is something that can be implemented ?

Thank you.

**Comment by l2isbad** [comment]
Well, this requests adds additional queries to mysql and most of them `need the "PROCESS" privilege to have all process infos`.

Before adding it to roadmap we have to make sure this is needed.

I am not a mysql user myself.

@Ferroin what do you think? @ktsaou

**Comment by ktsaou** [comment]
Generally, the more the better.
But we need to prioritize it a bit. I would suggest to wait for a few likes at the original post before  adding it to our roadmap.

Of course any contributor could work on it. But @l2isbad 	make sure all these are added in a non breaking way (i.e. if the module fails to collect these due to permissions, do not abort the whole module - continue to collect whatever is available).

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.

**Comment by ilyam8** [comment]
We execute [SHOW USER_STATISTICS](https://mariadb.com/kb/en/show-user-statistics/), but use only the following metrics from the output:

- Cpu_time
- Rows_read
- Rows_sent
- Rows_deleted
- Rows_inserted
- Rows_updated
- Select_commands
- Update_commands
- Other_commands

@gdelafond take a look at [information_schema.USER_STATISTICS](https://mariadb.com/kb/en/information-schema-user_statistics-table/) table, we can easily add info info from there as charts.

**Comment by ilyam8** [comment]
> number of current connection number

We have it, it is [`Active Connections`](https://github.com/netdata/go.d.plugin/blob/f90d7ff39d052e3d8adb527ad6f4d68e07c71562/modules/mysql/charts.go#L140-L150) chart (`Threads_connected` metric).

**Comment by ilyam8** [comment]
> number of current connection number by user (absolute)

Yeah, it looks like we need [SHOW [FULL] PROCESSLIST](https://mariadb.com/kb/en/show-processlist/).

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
