### ISSUE TITLE
refresh-badges.js - timestamp of update

### ISSUE THREAD

**Issue by sereeds** [netdata/netdata#3624]
I am using the refresh-badges.js, works great, thank you.
I notice there is an example in the file, commented out, to show refresh countdown etc.  It populates a DIV with ID of "pageliveinfo", which works good.
I would like to populate the div with only the date and time the data was refreshed.  Similar to how the timestamp is shown in the legend of charts, upon each update of the chart.

Perhaps it is an easy piece of javascript?

**Comment by sereeds** [comment]
I have a custom dashboard, most charts 1sec referesh.  However at the bottom, I have a printer status, that is only updated every 30 seconds (using your SNMP plugin).  I'd love to display a badge, or even a DIV that updates with the timestamp.

Idea.  Perhaps we could retrieve the timestamp as another dimension?
 <img class="netdata-badge" src="http://x.x.x.x:19999/api/v1/badge.svg?chart=snmp_toshiba2555.pagecount&label=Updated&dimensions=time"/>

Where/how do you get the timestamp from on the charts?

![image](https://user-images.githubusercontent.com/36478705/39014506-ccba80a2-43d7-11e8-874a-2b3aeef7a408.png)

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
