### ISSUE TITLE
Docker stats

### ISSUE THREAD

**Issue by crouthamela** [netdata/netdata#3627]
Is it possible to view per-container stats with netdata? As one would see with the `docker stats` command? [Glances ](https://github.com/nicolargo/glances) currently does this, which I find very useful.

**Docker stats output:**
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
4c1098c76c48        netdata             13.17%              0B / 0B             0.00%               0B / 0B             26.4MB / 0B         0
9fb748e8b8c0        nextcloudpi         1.60%               0B / 0B             0.00%               0B / 0B             2.63GB / 15.2GB     0
2a0b46042695        openvpn             0.01%               0B / 0B             0.00%               76.6MB / 46.4MB     74.9MB / 0B         0
2343f66aaa63        plex                1.21%               0B / 0B             0.00%               0B / 0B             3.47GB / 857MB      0
```

**Comment by ktsaou** [comment]
It already does:

1. netdata needs to run at the host

or

2. netdata runs in a container but it is given access to `/proc/`, `/sys` and `docker.sock` from the host

Have you tried any of these?

To check the result, see https://stackscale.my-netdata.io/ (it runs 30+ lxc containers - you will get the same with docker).

netdata monitors CPU, Memory, Disk I/O and network traffic per container. For all these, it provides a lot of charts (eg. memory activity, disk bandwidth and operations, etc).

**Comment by crouthamela** [comment]
Oh nice. How do I expose `docker.sock`?

I'm currently suing the following run command to expose `/proc` and `/sys` already:

`docker run -d --network=host --restart unless-stopped -v /etc/hosts:/etc/hosts:ro -v /etc/localtime:/etc/localtime:ro -v /proc:/host/proc:ro -v /sys:/host/sys:ro --name netdata firehol/netdata:armv7hf`

**Comment by ktsaou** [comment]
I believe this is done by adding the following to the `docker` command:

```
docker ... -v /var/run/docker.sock:/var/run/docker.sock ...
```

`docker.sock` is only used for fetching container names. Without it netdata will show the containers, but their DOCKERID will be shown instead of their name.

I think you also need to tell netdata about `/host`. This is normally done in netdata.conf by setting:

```
[global]
    host access prefix = /host
```

or by running netdata like this:

```sh
netdata -W set global 'host access prefix' '/host'

# or

netdata -s /host
```

I see https://github.com/firehol/netdata/blob/master/Dockerfile.armv7hf adds `-s /host`.

You could check it. Fetch `http://your.netdata.ip:19999/netdata.conf` and check if `host access prefix` has the right value.

Once you restart netdata, give it 10 secs to check for containers and then refresh the dashboard.

**Comment by crouthamela** [comment]
> give it 10 secs to check for containers and then refresh the dashboard.
Oops, that was part of my problem. I didn't see the containers show up at all, but a refresh brought them up.

The `netdata.conf` looks good, has the `/host` prefix. I added `docker.sock` as described, but have no luck on getting the names. It does show the DOCKERID of each and stats. I checked, and my system does have `docker.sock` in `/var/run`. I also tried mounting it into the container at `/host/var/run` to see if that made a different, but no luck yet.

Any ideas?

Thank you for the help, and very descriptive answers. (And making netdata! What a nice utility.)

**Comment by crouthamela** [comment]
@titpetric any ideas? I read through your readme as well.

**Comment by paulfantom** [comment]
@crouthamela we updated our docker images (not titpetric ones) and also created a wiki page about containerized netdata installation here: https://github.com/netdata/netdata/wiki/Install-netdata-with-Docker.

**Comment by crouthamela** [comment]
Thanks, I'll check it out later and comment.

**Comment by crouthamela** [comment]
Per the new documentation I've updated to the latest `armhf` release, and passed the container the PGID value for my system with `-e PGID=996`. It appears to be resolving the container names properly now, thank you!
