### ISSUE TITLE
[JMX module] inconsistent use of chart properties 'family' and 'context'

### ISSUE THREAD

**Issue by illes** [netdata/netdata#3632]
The usage of `family` and `context` in the charts generated by the `java.d` JMX module does not follow recommendations that may lead to inconsistent UI appearance and inconvenience when integrating with 3rd party tools. 

The code at [MBeanServerCollector.java#L198](https://github.com/simonnagl/netdata/blob/feature/java-plugin/java.d/src/main/java/org/firehol/netdata/module/jmx/MBeanServerCollector.java#L198) does not seem to follow guidelines set forth in the wiki: https://github.com/firehol/netdata/wiki/External-Plugins#chart

The property `family` could rather be the identifier of the monitored JVM (`serverConfiguration.getName()`, the PID by default), and the `context` some constant across the same charts for different JVMs.

**Comment by ilyam8** [comment]
> This issue was migrated from netdata-plugin-java-daemon 

Closing it because `netdata-plugin-java-daemon` is not part of the Netdata project.
