### ISSUE TITLE
Python latest version

### ISSUE THREAD

**Issue by Nirjonadda** [netdata/netdata#3636]
Blocks: #4322 

Please add support can install python latest version. The code below only install Python 2.7.14 but can be install Python 3.6.5 ?

````
# CentOS / Red Hat Enterprise Linux
yum install autoconf automake curl gcc git libmnl-devel libuuid-devel lm-sensors make MySQL-python nc pkgconfig python python-psycopg2 PyYAML zlib-devel
````

**Comment by cakrit** [comment]
Apologies for not replying this far. Netdata supports versions 2 and 3. Whether your distribution supports either or how to install it is something best asked of the particular community.
