### ISSUE TITLE
JMX collector

### ISSUE THREAD

**Issue by panda87** [netdata/netdata#364]
JVM based application are widely used so be able to monitor their stats can be very useful

**Comment by ktsaou** [comment]
If someone can provide the basics (i.e. connect to JVM, get the metrics of interest, etc), I can turn it into a netdata plugin. It can be written in any language (java included).

**Comment by jasonwbarnett** [comment]
A cheap thing might be to just copy the overall design that scout app uses and just port it to netdata.

- requires [Jmxterm][1]
- [scoutapp jmx source][2]

[1]: http://wiki.cyclopsgroup.org/jmxterm/
[2]: https://github.com/scoutapp/scout-plugins/blob/master/jmx_agent/jmx_agent.rb

**Comment by ktsaou** [comment]
@paulfantom this seems python too...

**Comment by paulfantom** [comment]
@ktsaou already added to my list. Right after HAProxy and ElasticSearch.

**Comment by ktsaou** [comment]
perfect! Please add redis too..

**Comment by paulfantom** [comment]
Ok, added.

**Comment by paulfantom** [comment]
Back to this.

Basically: JMX + python = No-go
But there is a solution to this (adopted for example by [telegraf](https://github.com/influxdata/telegraf) ). It is called [jolokia](https://jolokia.org/) and it provides JMX-HTTP bridge and is agent based.

Also I don't think this module can have autodetection, it will need to be configured by user.

I need to know if I can start working on jolokia module or maybe someone have better approach?

**Comment by ktsaou** [comment]
So JMX can be directly accessed by what? java?

**Comment by paulfantom** [comment]
There is something that is called `jpype` which should act as a python-java bridge. But I cannot get it working.

JMX is written in such way that it is very easy to be accessed by java, but it is almost impossible to be accessed by anything else. At least that is what I found.

**Comment by wojciechszela** [comment]
I second Jolokia. We have our own in-house metrics collector made in Scala (JVM), developed before telegraf was a thing, and we do use Jolokia instead of JMX. It's very easy to add Jolokia to any JVM based project (it's a JAR drop-in) and extra benefit is that it open tons of options in terms of metrics collections, monitoring, alerting... I doubt any JVM admin would object in using Jolokia.

**Comment by jasonwbarnett** [comment]
never seen or heard of Jolokia, but conceptually on board with this sort of thing. Seems like a great option.

Of course there is always alternatives that can be entertained down the road.

**Comment by toddiuszho** [comment]
If the Jolokia agents have [discovery enabled](https://jolokia.org/reference/html/protocol.html#discovery), we can have auto-discovery.

**Comment by sanketplus** [comment]
Found something much simpler compared to Jolokia. [JMXProxy](https://github.com/mk23/jmxproxy) 

Just get the jar running anywhere and query it with host and JMX port for said Java process and get JSON full of metrics.

**Comment by johntdyer** [comment]
Big fan of Jolokia !

**Comment by simonnagl** [comment]
I took a look at this too...

Yes, it would be possible to use Jolokia / JMXProxy. But I do not see the need adding an layer. When using such a program the data flow would be
`Java Application -> Jolokia -> Netdata Plugin -> netdata`

It is possible to write an custom JMX client which connects to a JVM and works as a netdata plugin.
`Java Application -> Netdata JMX Client (plugin) -> netdata`.

This may be faster but requires adding a java plugin to netdata.

**Comment by zhangxin0112** [comment]
hope anybody's work about monitor jvm on netdata.

**Comment by ktsaou** [comment]
I am not (sorry). If anyone is working on this, please let us know of your progress.

I would also love to have this plugin. Keep in mind it can be written in any language (including java). We just need someone willing to spend some time to model the basics. If we have the basic structure, I think a lot of people will step in (including me).

**Comment by simonnagl** [comment]
I am currently working on a Netdata Java Plugin Daemon and I added an initial JMX Plugin.
There are many things to do...

https://github.com/simonnagl/netdata-plugin-java-daemon

**Comment by ktsaou** [comment]
@simonnagl wow!
Is it working? If you manage to make it publish at least one chart, more people (including me) could step in and start adding things.
Since it is a deamon, how does it connect to netdata?

**Comment by simonnagl** [comment]
Yes, this is working. It publishes one chart to netdata, monitoring the loaded java classes of the deamon itself. More configuration can be added to collect other Simple Managed Beans getters which return Long or Integer.
The daemon is a [Netdata External Plugin](https://github.com/firehol/netdata/wiki/External-Plugins) which can be started of netdata and sends metrics to STDOUT and log messages to STDERR.

**Comment by archenroot** [comment]
I will give it a try as I am installing today NetData

**Comment by simonnagl** [comment]
Great, if you need help or somethings not working just ask. Remember I not yet released 1.0.0 so it can be considered beta.

**Comment by waykar-prashant** [comment]
I configured the netdata app to use the java jmx plugin. Not sure how it is supposed to behave and how do i see the charts? 
Please suggest

**Comment by simonnagl** [comment]
Have you done those steps?

```sh
git clone https://github.com/simonnagl/netdata-plugin-java-daemon.git
cd netdata-plugin-java-daemon
mvn package
cp src/main/sh/java.d.plugin /your/netdata/plugin/dir # Most likely /usr/libexec/netdata/plugins.d/
cp -r config/* /your/netdata/config/dir # Most likely /etc/netdata
cp target/java-daemon-0.1.0-SNAPSHOT.jar /tmp
```

After a restart of netdata you should as least see the metrics of the plugin itself. (Section jmx)
To collect other java processes you need to edit `imx.conf`. This is not very well tested.

As more users are interested in trying this plugin I will write a proper installer which works like `./netdata-installer.sh`. One command that sets up everything. I'll post here when it is done.

**Comment by waykar-prashant** [comment]
/opt/netdata/netdata-configs/java.d/java.d
/opt/netdata/netdata-configs/java.d/jmx.conf
/opt/netdata/netdata-plugins/java.d/java.d.plugin
Are these correct?

**Comment by simonnagl** [comment]
How did you install metadata? `sudo ./netdata-installer.sh` without any arguments?

Then the files you mentioned should go there:
```
/etc/netdata/jmx.conf
/etc/netdata/java.d/java.d.plugin
```

**Comment by mmohrwinkel** [comment]
Hi, I just tried this on a vagrant box. I had to chmod +x the file "mvnw" first to get the installer to fully run. After that I saw the following:
![image](https://user-images.githubusercontent.com/8159296/32824959-57fe5a4a-c9e3-11e7-8229-35a9f4b29c08.png)
How can I proceed to get metrics on memory consumption, garbage collection etc. ?

Thank you for your work!

**Comment by h0lzi** [comment]
@simonnagl Thank you for the work.
I did not try it yet. Just looked thought the jmx.conf and did not see anything about heap size.(Might be blind though)
 So I think current max/min should also be collected in the first version. Because exploding heaps are one of the main problems :)

**Comment by simonnagl** [comment]
@mmohrwinkel: Here is the current JmxPluginConfiguration of #2663. Where did you find the dead link? I will need to fix it after #2663 got merged.

@mmohrwinkel & @h0lzi: Memory consumption including heap size is not implemented yet because it is exposed via values returning CompositeData. (#2808). I planned to implement it after #2663 was merged which hags for a while. If someone is using the MR yet I can continue implementing things into the MR. Having testers for the MR would also be great, because it would make it more save to be merged.

I will continue adding features to the MR soon and notify you here. I will start working on support CompositeData. Thank you for the feedback.

**Comment by h0lzi** [comment]
@simonnagl ah ok makes sense.

Ok startet some testing with the PR.
It works for my test tomcat. Added jmx server in jmx.conf and works fine.
with: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9000

adding authentication and ssl (did not test) might be something for the future if it's not in the plugin yet?

One thing I notice. If I restart the tomcat the plugin will not reconnect.
I'm not sure what the best way to handel that is. Maybe if there was a connection try every x seconds  for y minutes.
(Make that a config option?). Off cause it needs to bail out eventually.
But besides that basic stuff seems to work for me.

**Comment by simonnagl** [comment]
@h0lzi Thank you for the feedback again. You are absolutely right. I put your two points into separated issues. (#3046 and #3047)

**Comment by mmohrwinkel** [comment]
Hi @simonnagl , I found the dead link on the page https://github.com/simonnagl/netdata-plugin-java-daemon under Configuration. There is a link "JmxPluginConfiguration" in the table under "Schema" and it 404s.

#2808 sounds very promising, I'll try it out as soon as it is ready and give you feedback!

**Comment by simonnagl** [comment]
Hi @mmohrwinkel. This link will be dead until #2808 got merged.

**Comment by corporate-gadfly** [comment]
@simonnagl: Your solution for gathering JMX statistics spawns a _side-by-side_ JVM which then connects with the _target_ JVM.

What is the overhead of running an extra JVM vs. using the earlier proposed jolokia solution?

Thanks for your work, BTW.

**Comment by simonnagl** [comment]
Sorry for the late answer.
I was not able to measure it but I would say it depends.
jolokia needs an agent installed in the JVM (i.e. a application server) to do JMX for you. It can also be a proxy agent, which the is also a extra JVM.
If we assume that we monitor the "netdata way" which means only collecting local services I think using jolokia vs. a side-by-side JVM produces way the same overhead.

**Comment by cosmix** [comment]
@ilyam8 kind reminder, please update this issue (and/or close it) when we're ready to proceed with a Golang-based module for JMX monitoring.

**Comment by simonnagl** [comment]
@cosmix ist there a plan to implement a golang-based module for JMX? Do you want to build this based on Jolokia?

**Comment by cosmix** [comment]
@simonnagl hello, yes there is a plan to build a Golang-based collector for JMX. We are still exploring the potential solution space as to how to do it; most likely we won’t be requiring Jolokia.

**Comment by ki0** [comment]
Is this stopped? any updates?

**Comment by Thrameos** [comment]
@paulfantom I know this is belated, but what issue were you having with getting JPype running?   As far as I am aware JPype should be able to talk to JMX.  Though we currently can't extend a Java class it is possible to implement an interface.  And simply calling Java methods should be no issue at all.

**Comment by paulfantom** [comment]
@Thrameos sorry, I don't remember. My last take on this was over 4 years ago and I no longer use nor work on the project.

**Comment by ilyam8** [comment]
Closing this feature request and moving it to [our community forum](https://community.netdata.cloud/) for further discussion (link will be posted soon).
