### ISSUE TITLE
Import snapshots from a URL

### ISSUE THREAD

**Issue by mhowell-ims** [netdata/netdata#3643]
Right now you can only import snapshots from a local file. It would be handy to be able to import snapshots from a URL as well. This would allow you to e.g. store snapshots centrally and access them in a more convenient form than a shared remote mount.

**Comment by ktsaou** [comment]
@cakrit 	this is a nice feature. It would allow even blogs to be created for hands on experience on performance troubleshooting with netdata.

**Comment by cakrit** [comment]
Doesn't this URL need to point to a cloud service with the appropriate permission handling schema? Sound a lot like a very good feature for the hub.

**Comment by ktsaou** [comment]
> Doesn't this URL need to point to a cloud service with the appropriate permission handling schema? Sound a lot like a very good feature for the hub.

Yeap it could be.

**Comment by cakrit** [comment]
I am closing this and including it as a requirement of #3973. I will request feedback for the design that I have in mind there.
