### ISSUE TITLE
sphinxsearch monitoring

### ISSUE THREAD

**Issue by bbaronSVK** [netdata/netdata#3648]
Is it possible to make monitoring of this search engine www.sphinxsearch.com

**Comment by cakrit** [comment]
To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by cakrit** [comment]
Closing due to no sponsor.
