### ISSUE TITLE
True histogram support with prometheus compatibility

### ISSUE THREAD

**Issue by geekhead** [netdata/netdata#3652]
I know histograms are a complex beast but would love to see the ability to create histograms with configurable bucket size widths or dynamically figure out the proper bucket sizes for a configurable time for any StatsD timing metrics, metrics that deal with latency like web response times, or any other metric that makes sense for SLA calculations based on percentiles/quantiles. Histograms gives us much better visibility into our metrics and allows us to visualize the distribution and calculate properly arbitrary quantile/percentile estimations.

I could see this being defined in netdata.conf and enabling it on a per chart basis that had data that could be put into histogram buckets which would then create another chart/graph in the UI. The time period used to generate these histograms would by default use the `history` parameter defined in netdata.conf or could be configurable. 

The biggest issue are the bin widths and there are a lot of blog posts and math that show how manually defining bucket size widths is wrong and provides inaccurate quantile estimations etc. How can you properly and accurately define your bin widths when you don't have your data yet is the argument and can produce a high error rate in your estimations if you define them wrong. Other histogram implementations available that do it better use a "log-linear" approach to bin widths in histograms. One such example is [HdrHistorgram](https://hdrhistogram.github.io/HdrHistogram/) and they have a port of it to native python, https://github.com/HdrHistogram/HdrHistogram_py, that maybe could be utilized within netdata.  

For prometheus to properly scrape these, the histogram has a specific text format which can be found here https://prometheus.io/docs/instrumenting/exposition_formats/#historical-versions

**Comment by cakrit** [comment]
@ktsaou and @vlvkobal I think that histograms will be a good addition. Putting it in our roadmap so we can investigate if/when/how we can pick this up.

**Comment by ktsaou** [comment]
this is good, yes.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
