### ISSUE TITLE
hide one axis in dygraph

### ISSUE THREAD

**Issue by raviteja83** [netdata/netdata#3654]
I saw that there is an option to hide both Axis but not single Axis. How can i accomplish this? I tried setting data-dyrgaph-ylabelwidth="0" but didn't work.

**Comment by ktsaou** [comment]
If you don't need the legend, you can set `data-dygraph-theme="sparkline"`.
If you need the legend, then you probably have to set:

```
data-dygraph-drawaxis="false"`
data-dygraph-ylabel=""
data-dygraph-ylabelwidth="0"
```

**Comment by raviteja83** [comment]
@ktsaou Thanks for the reply. What i wanted to do is only hide or reduce the width of yAxis ticks while showing the xAxis. But with drawaxis set to false, it hides xAxis as well.

**Comment by ktsaou** [comment]
ok, I added 2 more options with PR #3663
Can you test it?

**Comment by ktsaou** [comment]
merged it.
If it does not work for you, please post here.

**Comment by ktsaou** [comment]
hm... let me check:

This page:

```html
<html>
<script src="dashboard.js"></script>
<body>

The original:<br/>
<div
        data-netdata="system.cpu"
        data-width="100%"
        data-height="200px"
></div>

<br/>&nbsp;<br/>
Hide Y Axis:<br/>
<div
        data-netdata="system.cpu"
        data-width="100%"
        data-height="200px"
        data-dygraph-drawyaxis="false"
        data-dygraph-title=""
></div>

<br/>&nbsp;<br/>
Hide X Axis:<br/>
<div
        data-netdata="system.cpu"
        data-width="100%"
        data-height="200px"
        data-dygraph-drawxaxis="false"
></div>

</body>
</html>
```

produces this:

![screenshot_2018-05-10_11-56-08](https://user-images.githubusercontent.com/2662304/39861409-27a6f05a-5449-11e8-82df-a872a8335b3e.png)

So, it works...

**Comment by ushuz** [comment]
These two options doesn't work.

```
data-dygraph-ylabel=""
data-dygraph-ylabelwidth="0"
```

And what's the relation between `data-dygraph-ylabelwidth` and `data-dygraph-yaxislabelwidth`?
