### ISSUE TITLE
[Java Plugin] Decide handling of failing modules/charts

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#3669]
@illes suggested at https://github.com/simonnagl/netdata/pull/6 to decide 
> what we want to do with failing modules/charts, which should be ignorable, and which should allow java.d plugin to continue with the rest of the functionality?

Here are some thoughts of mine:

- java modules which fail with an exception should stop but not influence other modules.
- in modules (i.e. the JMX Module) if charts cannot be initialized (i.e. because a JMX Server does not have all MBeans defined in configuration) we should log the fact and continue without these charts.
- in modules (i.e. the JMX Module), if collection of values fail, we should stop collecting these values.
- We should rerun the initialization for some modules (i.e. the JMX Module) in a configurable interval (i.e. every 30 seconds). This will enable detecting new Java Processes on the fly.

**Comment by ktsaou** [comment]
I totally agree, with the following notes:

> in modules (i.e. the JMX Module), if collection of values fail, we should stop collecting these values.

I would be nice to also check less frequently if they come up after some time.

**Comment by ilyam8** [comment]
Closing it because `netdata-plugin-java-daemon` is not part of the Netdata project.
