### ISSUE TITLE
make prometheus label better

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#3693]
# Problem
Currently, the prometheus label `chart` format is `{plugin-name}_{job-name}.{chart-name}`. The only way to get `{job-name}` is use `label_replace` function like:
```bash
label_replace(netdata_web_log_detailed_response_codes_requests_persec_average, "name", "$1", "chart", "web_log_(.*)\\.detailed_response_codes")
```
And if we want to get all metrics related to the job, we need to query like:
```bash
netdata_web_log_detailed_response_codes_requests_persec_average{chart=~"web_log_$myjob\\..*"}
```
They are a hack way and not natural.

# Suggestion
I suggest rename the label:
AS IS:
* `chart="{plugin-name}_{job-name}.{chart-name}"`

TO BE:
* `chart="{chart-name}"`
* `jobname="{job-name}"`

*PS: Since `{plugin-name}` is already included in metrics prefix, we don't need that in label.*

# Example
AS IS:
```bash
# COMMENT netdata_web_log_detailed_response_codes_requests_persec_average: dimension "400", value is requests/s, gauge, dt 1525745823 to 1525745832 inclusive
netdata_web_log_detailed_response_codes_requests_persec_average{chart="web_log_myweb.detailed_response_codes",family="responses",dimension="400"} 0.0000000 1525745832000
```
TO BE:
```bash
# COMMENT netdata_web_log_detailed_response_codes_requests_persec_average: dimension "400", value is requests/s, gauge, dt 1525745823 to 1525745832 inclusive
netdata_web_log_detailed_response_codes_requests_persec_average{chart="web_log.detailed_response_codes", name="myweb",family="responses",dimension="400"} 0.0000000 1525745832000
```

**Comment by ktsaou** [comment]
This would be nice.

However, the job name as it is encoded in netdata charts is wrong. It depends on the chart (disks for example have it after the `.`), so it can only be done with heuristics.

Ideally, this should be solved with #807

**Comment by ktsaou** [comment]
@cakrit 	another breaking change that depends on #807

**Comment by cakrit** [comment]
This one could be delivered with #4986. We will need to discuss that one together with #807 to plan them.

**Comment by ilyam8** [comment]
easypiechart graphic
