### ISSUE TITLE
[SNMP Plugin] Issue with Opaque:Float value

### ISSUE THREAD

**Issue by Shini31** [netdata/netdata#3703]
Hello,

The snmp plugin cannot retrieve Opaque:Float value:
```
/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp
CHART "snmp_ups.load" "ups.load" "UPS load" "percentage" "UPS" "" "line" 50030 10
DIMENSION "load_ups" "load_ups" "absolute" 1 1 
BEGIN ups.load 
SET load_ups = �xB�0
END
```

Here is the snmpwalk response:
```
snmpwalk -On 127.0.0.1 -c public -v2c .1.3.6.1.4.1.6574.4.3.1.1.0
.1.3.6.1.4.1.6574.4.3.1.1.0 = Opaque: Float: 100.000000 Percent
```

And the `snmp.conf` file:
```
{
  "enable_autodetect": false,
  "update_every": 5,
  "max_request_size": 50,
  "servers": [
    {
      "hostname": "192.168.1.200",
      "community": "netdata",
      "update_every": 10,
      "options": { "timeout": 10000, "version": 1 },
      "charts": {
        "snmp_ups.charge": {
          "title": "UPS charge",
          "units": "seconds",
          "type": "line",
          "priority": 40,
          "family": "UPS",
          "dimensions": {
            "load_ups": {
              "oid": ".1.3.6.1.4.1.6574.4.3.6.1.0",
              "algorithm": "absolute",
              "multiplier": 1,
              "divisor": 1,
              "offset": 0
            }
          }
        }
      }
    }
  ]
} 
```

Regards.

PS: Sorry for the flood of issue/question

**Comment by Shini31** [comment]
Hello,

I check in `net-snmp.js` and Object Type Opaque seems to be present. 
With debug, i can retrieve the buffer value:
```
2018-05-11 16:41:51: node.d.plugin: DEBUG: snmp: 127.0.0.1: found snmp value of OIDs 1.3.6.1.4.1.6574.4.3.1.1.0, ObjectType Opaque (68), typeof(object), in JSON: <Buffer 9f 78 04 42 c8 00 00>, value = �xB� (parsed as number)
```

Any idea ?
Regards.

**Comment by ktsaou** [comment]
hm... I think this is a bug. I have tested net-snmp buffer values with 64bit integers, but never with float values. Unfortunately I don't have an snmp device that returns float values.

If anyone can help, please do so.

**Comment by Shini31** [comment]
If you give me all the commands, I can test everything on my infrastructure

**Comment by ktsaou** [comment]
Well, it is not a matter of commands. let me check if I can manage to adapt the node.js code of the netdata plugin to handle floats too. Then I'll give you a few commands to test it.

**Comment by ktsaou** [comment]
I don't know how to convert the buffer returned by net-snmp.js to float. I asked them https://github.com/nospaceships/node-net-snmp/issues/40

In general the solution should be simple. At this point: https://github.com/ktsaou/netdata/blob/e8915e26537615282003d6baf094d59712c9b4f1/node.d/snmp.node.js#L289 we have to add a case statement for `Opaque` values too. But we need to convert the received buffer to a number or even a hex representation we will pass to netdata to convert.

**Comment by Shini31** [comment]
I had tested this solution on my side but I did not manage to convert the raw data.

Thanks for the job!
