### ISSUE TITLE
web_log squid custom regex support

### ISSUE THREAD

**Issue by veksh** [netdata/netdata#3730]
Range `[\da-f.:]+` is obviously wrong for matching hostnames, need `[\da-z.:-]+`; I'll make a merge request shortly

**Comment by l2isbad** [comment]
Well, `[\da-f.:]+` is regex for matching ip addresses (ipv4, ipv6)

**Comment by l2isbad** [comment]
https://wiki.squid-cache.org/Features/LogFormat

```

**Comment by veksh** [comment]
Yes, you are right -- it turns out that I'm using non-default log format :)

```
logformat squid_fqdn %ts.%03tu %6tr %>A %Ss/%03>Hs %<st %rm %ru %un %Sh/%<A %mt
access_log /apps/squid/logs/access.log squid_fqdn
```

The only deviation from defaults that host name is logged instead of IP; it is way more convenient to have human-readable host names in logs

```
1526561659.621   2064 kadr20.m1.maxidom.ru TCP_MISS/200 5964 CONNECT browser.pipe.aria.microsoft.com:443 - FIRST_UP_PARENT/relay-ra -
```

So it is more of a feature request - maybe extending characters range to include `[\dA-Za-z.:_-]+` will not hurt anyone?

**Comment by l2isbad** [comment]
> maybe extending characters range to include [\dA-Za-z.:_-]+ will not hurt anyone?

No. 

This is wrong in case of `hostnames`

https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L872-L882

Keep in mind i am not an expert :smile: 

I think we need custom log format feature for squid_log.

And we can add a list of regexes like in web_log: https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L530-L567
Module will chose the first that matches.

Do we need requests per hostname chart? What do you think @veksh

**Comment by veksh** [comment]
> This is wrong in case of hostnames

Turns out that in that case two wrongs (almost) make a right :)

By matching "." in hostname it treats hostnames as ipv4 addresses, and rest of code is quite OK with keeping count of unique hostnames.
<img width="1365" alt="clients" src="https://user-images.githubusercontent.com/3881519/40182632-7eb04d46-59f4-11e8-9a34-41a585fdf95b.png">

**Comment by l2isbad** [comment]
Still wrong :smile:

**Comment by veksh** [comment]
> Do we need requests per hostname chart?

What do you mean -- something like number of requests for each client hostname? That would be interesting, but clients cardinality could get quite high

**Comment by veksh** [comment]
> Still wrong

Maybe "misnamed" -- "unuque client hosts" would be better name in that case. Is there any reason to keep separate count for IPv4 vs IPv6 clients?

**Comment by l2isbad** [comment]
> Is there any reason to keep separate count for IPv4 vs IPv6 clients?

Not sure, but if it's there this should not be changed.

> That would be interesting, but clients cardinality could get quite high

Yes, this is a problem.

I think

> And we can add a list of regexes like in web_log: 

is what we need here.

**Comment by l2isbad** [comment]
> so detection at startup would be unreliable

Order is a thing :smile: 

Regex with hostname will match even when there is IP instead of hostname.

lets summon @Ferroin . What do you think @Ferroin ?

**Comment by l2isbad** [comment]
> after restart squid 

i see `web_log` uses [read_last_line](https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/collection.py#L75-L83) function which literally reads last line from the logfile to chose from predefined regexes.

**Comment by veksh** [comment]
> regex with hostname will match even when there is IP instead of hostname.

My point is this will not break anything except keeping count of distinct IPv4/v6 clients, and even that became only cosmetically wrong (metric is named ".ipv4" but is actually counting unique hostnames). Only way to fix that is to add another metric named like ".hostnames" in addition to ".ipv4" and ".ipv6"; run-time selection of log regexp will not change anything in that regard.

**Comment by veksh** [comment]
> i see web_log uses read_last_line function which literally reads last line from the logfile to chose from predefined regexes

Ok, but why chose? Wider character set for IP + hostname is better in every regard: it with work with default log format (so nothing is broken) and will work sufficiently well with custom "hostnames instead of IP" log, so it seems to be superior in all regards :)

**Comment by l2isbad** [comment]
> Wider character set for IP + hostname is better in every regard

i don't agree
@ktsaou @Ferroin

**Comment by veksh** [comment]
>> Wider character set for IP + hostname is better in every regard

> i don't agree

Care to elaborate why? :) 
And is there any acceptable way of having hostnames in squid logs (instead of IPs), in your opinion?

**Comment by ktsaou** [comment]
hm...

1. I agree that netdata should allow configuring the squid regex
2. I agree that IPv4 / IPv6 reporting is important - we need it.
3. I agree that IPv4 / IPv6 matching by searching for a ` . ` is oversimplified and since we will support custom regex, we should do a better match. If we use a regex, this may have a performance hit, so we need to be sure it will be fast enough to support very busy sites.
4. I agree that another dimension is needed, called `hostnames` or `other` for all clients that do not match IPv4 and IPv6, so that a custom log will not make netdata report hostnames as IPv4.

**Comment by ktsaou** [comment]
> I believe we need another set of charts for hostname, not dimension to existing chart

hm... I am missing something probably... What would these charts show?

**Comment by l2isbad** [comment]
Well, i don't know. `unique hostnames per iteration` and `unique hostnames since start` for example or any other.

I dont't get why do you suggest to add `hostnames` dimension to `Current Poll Unique Client IPs` chart.

**Comment by l2isbad** [comment]
@veksh guy uses custom log format. He replaced `client address` (which is always IP address) with `hostname`. It is an additional field which should have it's own charts/parse logic.

**Comment by ktsaou** [comment]
hm... I still don't get it. Help me understand.

You have a client address. Today it can be:

1. IPv4 address
2. IPv6 address

To count the uniques, you have for each of the above, one set for the uniques since the beginning that is never emptied and another set that you empty between iterations (for counting unique per iteration). Both of these sets are just strings.

One solution could be to assume you can have another type of client address:

3. hostname

This would allow you to have a 3rd dimension in the existing charts.

Of course, if people want to use custom format with exotic attributes, things can break. But the above seems pretty simple and straight forward to me.

Isn't it? (I may be missing something - sorry)

**Comment by l2isbad** [comment]
> One solution could be to assume you can have another type of client address

Ok.

Still this should be implemented not just by changing the `client address` regular expression part, but adding a new one because log format may have both `client address` and `hostnames`

**Comment by ktsaou** [comment]
Sure, yes.
