### ISSUE TITLE
Tracking open files for systemd services?

### ISSUE THREAD

**Issue by wavded** [netdata/netdata#3745]
Wonder if this has been discussed or is possible. I see there is an apps plugin but this would be nice to pull in, in addition to the other stats we pull for systemd services (cgroup) already.  Thoughts?

**Comment by ktsaou** [comment]
hm... interesting...

cgroups do not provide this information, but apps.plugin could just group running processes by systemd cgroup and then report the result to netdata...

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
