### ISSUE TITLE
Split NFACCT handling to a dedicated helper program.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#3749]
This has been mentioned before in a couple of issues, but I didn't see one open specifically for this, so I'm opening this so that it's more publicly visible.

Netdata actually has support for tracking counters for Linux firewall rules, but it only works if you run Netdata as root (or possibly with the CAP_NET_ADMIN capability, I'm not sure about this though).

Ideally, this needs to be split out to a SUID helper program or just made into a binary module (like apps.plugin or the fping plugin) so that Netdata can be run as a normal user and still collect this data.

Relevant code is currently in [src/plugin_nfacct.c](https://github.com/firehol/netdata/blob/master/src/plugin_nfacct.c) and [src/plugin_nfacct.h](https://github.com/firehol/netdata/blob/master/src/plugin_nfacct.h), though the conntrack stuff in there too can just be kept as-is (it works as a non-root user).

**Comment by ktsaou** [comment]
Yes, we should do this.
