### ISSUE TITLE
Netdata's cgroup tracking does not work with version 2 cgroups.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#3750]
cgroup v2 setups preferentially use a unified hierarchy (which Netdata can easily be adapted to by just pointing all the controllers at the root), and additionally changed the names and contents of some of the files:

* The `blkio` controller is called `io` in cgroup v2, and now uses a single `io.stat` file instead of the various `blkio.*.io_service*` files.
* The `cpu` and `cpuacct` controllers got unified into one controller in cgroup v2, and now has a single file `cpu.stat` that contains both the fields from the old `cpu.stat` file, as well as microsecond resolution usage counters for total, system, and user time.
* The `memory` controller has changed enough about the data format that it needs a different parser (but now has a lot more info that can be parsed, including info on the types of allocations for the cgroup, and swap usage.
* The `devices` controller is gone (because there are better ways no to handle what it was trying to do).

**Comment by ktsaou** [comment]
This is nice info! Thank you for tracking the changes.
Any ideas how to have a real container with cgroup v2? I would love to support this asap...

**Comment by Ferroin** [comment]
Controllers get enabled for the given cgroup either through inheritance, or by enabling them prior to adding tasks.  Once controllers are enabled, the associated files appear, and you can add tasks and manipulate limits.  Full official documentation can be found [in the kernel sources](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/plain/Documentation/cgroup-v2.txt).

If you want a reasonably quick and easy way to test this without having to fight with systemd (which preferentially uses cgroup v2 by default, though many distros have overridden this), Gentoo's OpenRC init system supports version 2 cgroups in recent versions, so you could just set up a Gentoo VM, and then make the following 2 changes to `/etc/rc.conf` and reboot:
 
* Update `rc_cgroup_mode` to `unified`.
* Update `rc_cgroup_controllers` to contain at least `io`, `cpu`, and `memory` (and possibly `pids`, as that would let Netdata count tasks in the cgroup without needing to read out the list of tasks).

**Comment by intelfx** [comment]
Any progress?

@ktsaou You can have a container with unified cgroup hierarchy only if the host is configured in such mode as well. In addition to @Ferroin's, I will suggest a systemd-based solution:

- To get a fully v2 setup, boot any distro with a fairly recent version of systemd passing `systemd.unified_cgroup_hierarchy=1` to the kernel command line.

- To get a hybrid setup (systemd's cgroup tree uses cgroups v2, device controllers use cgroups v1), boot with `systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller=0`.

**Comment by ktsaou** [comment]
No I didn't have the time to work on this.

Could you please post one of each of the files mentioned by @Ferroin . I would like to have a quick estimation of the work needed to get this done.

Also, is there any system shipping cgroups v2 by default, in either unified or hybrid mode? To implement this, we will need to provide heuristics for the location of the files, etc., much like the dozens of defaults we have already added in netdata: https://github.com/firehol/netdata/blob/381c2174d0d2dc36dcbd05b4d8f17620f00112ff/src/sys_fs_cgroup.c#L151-L237

**Comment by intelfx** [comment]
> Could you please post one of each of the files mentioned by @Ferroin . I would like to have a quick estimation of the work needed to get this done.

Sure. What follows is the dump of all files inside the `/system.slice` cgroup on an up-to-date Arch Linux installation booted in the unified cgroups mode:
* `cgroup.controllers`:
  ```
  cpu io memory pids
  ```

* `cgroup.events`:
  ```
  populated 1
  ```

* `cgroup.max.depth`:
  ```
  max
  ```

* `cgroup.max.descendants`:
  ```
  max
  ```

* `cgroup.procs`:
  ```
  ```

* `cgroup.stat`:
  ```
  nr_descendants 115
  nr_dying_descendants 123
  ```

* `cgroup.subtree_control`:
  ```
  cpu io memory pids
  ```

* `cgroup.threads`:
  ```
  ```

* `cgroup.type`:
  ```
  domain
  ```

* `cpu.max`:
  ```
  max 100000
  ```

* `cpu.stat`:
  ```
  usage_usec 47463760172
  user_usec 37177226073
  system_usec 10286534099
  nr_periods 0
  nr_throttled 0
  throttled_usec 0
  ```

* `cpu.weight`:
  ```
  100
  ```

* `cpu.weight.nice`:
  ```
  0
  ```

* `io.bfq.weight`:
  ```
  100
  ```

* `io.low`:
  ```
  ```

* `io.max`:
  ```
  ```

* `io.stat`:
  ```
  254:3 rbytes=165067849728 wbytes=3391488 rios=11210031 wios=196
  254:2 rbytes=165358473216 wbytes=0 rios=11233161 wios=0
  254:1 rbytes=165278396416 wbytes=3244032 rios=11223523 wios=187
  254:0 rbytes=166539722752 wbytes=6635520 rios=11309997 wios=383
  8:48 rbytes=165358790656 wbytes=0 rios=11233206 wios=0
  8:16 rbytes=165068167168 wbytes=0 rios=11210076 wios=0
  8:32 rbytes=165278717952 wbytes=0 rios=11223569 wios=0
  8:64 rbytes=166540044288 wbytes=0 rios=11310043 wios=0
  8:0 rbytes=79881895424 wbytes=112910946304 rios=3560676 wios=6439291
  ```

* `io.weight`:
  ```
  default 100
  ```

* `memory.current`:
  ```
  7161962496
  ```

* `memory.events`:
  ```
  low 0
  high 0
  max 0
  oom 0
  oom_kill 0
  ```

* `memory.high`:
  ```
  max
  ```

* `memory.low`:
  ```
  0
  ```

* `memory.max`:
  ```
  max
  ```

* `memory.min`:
  ```
  0
  ```

* `memory.stat`:
  ```
  anon 3153362944
  file 3652247552
  kernel_stack 8798208
  slab 284082176
  sock 27570176
  shmem 147038208
  file_mapped 267632640
  file_dirty 1757184
  file_writeback 270336
  inactive_anon 1798438912
  active_anon 1489944576
  inactive_file 2601517056
  active_file 895827968
  unevictable 0
  slab_reclaimable 194772992
  slab_unreclaimable 89309184
  pgfault 99750222
  pgmajfault 116358
  pgrefill 21927382
  pgscan 187234211
  pgsteal 182370946
  pgactivate 4345968
  pgdeactivate 21549087
  pglazyfree 23227314
  pglazyfreed 123222
  workingset_refault 19641270
  workingset_activate 3902052
  workingset_nodereclaim 631653
  ```

* `memory.swap.current`:
  ```
  284700672
  ```

* `memory.swap.events`:
  ```
  max 0
  fail 0
  ```

* `memory.swap.max`:
  ```
  max
  ```

* `pids.current`:
  ```
  447
  ```

* `pids.events`:
  ```
  max 0
  ```

* `pids.max`:
  ```
  max
  ```

**Comment by intelfx** [comment]
That was a non-leaf cgroup. Here is a sample for `/init.scope` which is a leaf cgroup:

* `cgroup.controllers`:
  ```
  cpu io memory pids
  ```

* `cgroup.events`:
  ```
  populated 1
  ```

* `cgroup.max.depth`:
  ```
  max
  ```

* `cgroup.max.descendants`:
  ```
  max
  ```

* `cgroup.procs`:
  ```
  1
  ```

* `cgroup.stat`:
  ```
  nr_descendants 0
  nr_dying_descendants 0
  ```

* `cgroup.subtree_control`:
  ```
  ```

* `cgroup.threads`:
  ```
  1
  ```

* `cgroup.type`:
  ```
  domain
  ```

* `cpu.max`:
  ```
  max 100000
  ```

* `cpu.stat`:
  ```
  usage_usec 31008561
  user_usec 19980610
  system_usec 11027951
  nr_periods 0
  nr_throttled 0
  throttled_usec 0
  ```

* `cpu.weight`:
  ```
  100
  ```

* `cpu.weight.nice`:
  ```
  0
  ```

* `io.bfq.weight`:
  ```
  100
  ```

* `io.low`:
  ```
  ```

* `io.max`:
  ```
  ```

* `io.stat`:
  ```
  8:64 rbytes=114688 wbytes=0 rios=7 wios=0
  254:0 rbytes=114688 wbytes=0 rios=7 wios=0
  8:0 rbytes=15093760 wbytes=163840 rios=432 wios=9
  ```

* `io.weight`:
  ```
  default 100
  ```

* `memory.current`:
  ```
  15630336
  ```

* `memory.events`:
  ```
  low 0
  high 0
  max 0
  oom 0
  oom_kill 0
  ```

* `memory.high`:
  ```
  max
  ```

* `memory.low`:
  ```
  0
  ```

* `memory.max`:
  ```
  max
  ```

* `memory.min`:
  ```
  0
  ```

* `memory.stat`:
  ```
  anon 2621440
  file 5529600
  kernel_stack 835584
  slab 6569984
  sock 0
  shmem 0
  file_mapped 4595712
  file_dirty 0
  file_writeback 0
  inactive_anon 1576960
  active_anon 1372160
  inactive_file 1404928
  active_file 3854336
  unevictable 0
  slab_reclaimable 3252224
  slab_unreclaimable 3317760
  pgfault 42999
  pgmajfault 330
  pgrefill 103252
  pgscan 13724
  pgsteal 10962
  pgactivate 2574
  pgdeactivate 35524
  pglazyfree 0
  pglazyfreed 0
  workingset_refault 6435
  workingset_activate 2607
  workingset_nodereclaim 0
  ```

* `memory.swap.current`:
  ```
  3784704
  ```

* `memory.swap.events`:
  ```
  max 0
  fail 0
  ```

* `memory.swap.max`:
  ```
  max
  ```

* `pids.current`:
  ```
  1
  ```

* `pids.events`:
  ```
  max 0
  ```

* `pids.max`:
  ```
  max
  ```

**Comment by intelfx** [comment]
> Also, is there any system shipping cgroups v2 by default, in either unified or hybrid mode?

Arch Linux boots into hybrid mode by default. Not sure about other systems, although Fedora likely does that too. Nothing boots into unified mode by default insofar I am aware.

> To implement this, we will need to provide heuristics for the location of the files, etc., much like the dozens of defaults we have already added in netdata

I believe _those_ heuristics do not need to change in any way. At least with systemd, the actual cgroups organization hierarchy stays the same no matter which version of cgroups controllers is in use.

As for locations of cgroups files, you should be able to infer which cgroups versions and hierarchies are in use just by looking at mtab — no heuristics needed.

**Comment by ktsaou** [comment]
@cakrit 	this is important. It affects everything about containers.

**Comment by cakrit** [comment]
We are working with high priority on a new implementation for Kubernetes monitoring, which means that there will be little need for supporting hierarchical cgroups. I am leaving this one open in case someone in the community would like to assist with the v2 support.

**Comment by Ferroin** [comment]
I disagree that we don't need to support hierarchical cgroups.  Not needing support for them for k8s is one thing, but there are many other applications of them than just k8s.  systemd-nspawn comes to mind as one example, but it's also not a unique case.

**Comment by Ferroin** [comment]
Also, I don't have time personally to learn the C code responsible for this right now, but if someone wants to work on it let me know and I'll be happy to help with the testing side of things.

**Comment by Ferroin** [comment]
My second comment was more about the cgroups-v2 support in general than the UI specifically.

**Comment by skrzyp1** [comment]
I'm  willing to work on this issue.
I need some guidance on how we want to resolve it.
Is it better to: detect which cgroup version is in use in run time with `sys_fs_cgroup.c`,
or: let it be predefined by user in `netdata.conf`as new field in `[plugin:cgroups]` section.

**Comment by intelfx** [comment]
@skrzyp1 Both cgroup2 and legacy cgroups may be active at the same time, in any possible combination. I'd say there is no correct way other than detect at runtime.

**Comment by skrzyp1** [comment]
I need some more info how we want to resolve this.
[Cgroup structure](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/sys_fs_cgroup.c#L373) is now designed to hold data from non unified cgroups.
Do we want to:
Modify current cgroup structure: if unified cgroups are selected different files are bound  in [find_all_cgroups](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/sys_fs_cgroup.c#L1265), and different (new) functions are invoked in [cgroup_read](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/sys_fs_cgroup.c#L759) to update existing fields.
This should work fine assuming all fields currently used by netdata are also present in unified cgroups files.
Or:
Create new structure for unified cgroups (this is a lot of work and brings many complications - e.g. keeping two lists of two structure types).

Maybe somebody has different idea?

**Comment by ilyam8** [comment]
@vlvkobal please ^^

**Comment by vlvkobal** [comment]
Modifying the existing cgroup structure is OK. So, proceed with the first approach.

**Comment by skrzyp1** [comment]
I created WiP pull request [here](https://github.com/netdata/netdata/pull/5407/files) so we can discuss changes.
To test add:
```
use unified cgroups = yes
path to unified cgroups = /sys/fs/cgroup
``` 
(or whatever path to cgroups you have)
to `[plugin:cgroups]` section of `netdata.conf`
System must be running in unified cgroup mode.
Cgroup detection should work fine.
So far i added support for one `io` file. It reports below zero write values as of now.

**Comment by vlvkobal** [comment]
Hi @skrzyp1, how is it going with #5407?

**Comment by skrzyp1** [comment]
I had some downtime last month, but will finish this shortly.
i have following concern: how does `rss, cache, rss_huge` correspond to new `memory.stat` values/labels: `anon, kernel_stack, slab, sock, shmem` I'm not sure if can find equivalent values i new stat file.
`pgpgin, pgpout` seem to be missing too.

**Comment by Ferroin** [comment]
@skrzyp1 As far as I know, they don't.  The `cache` counter was misleading at best and just plain wrong at worst.  The `rss` counters were also somewhat misleading because of how they interacted with shared memory, and the same applies for the page in and page out counters (though they are arguably less so).  I think a different set of charts are probably needed in this case for memory if using v2 cgroups.

**Comment by skrzyp1** [comment]
@vlvkobal I think my changes are ready for review and testing.
See https://github.com/netdata/netdata/issues/3750#issuecomment-464507750 for config changes that are required for a switch to unified cgroups.
I will add some questions / comments to pull request tomorrow.
Anyone who can test my changes please do so here is branch with changes: https://github.com/skrzyp1/netdata/tree/unified-cgroups-support
