### ISSUE TITLE
netdata like monitor screen

### ISSUE THREAD

**Issue by InfinitumForm** [netdata/netdata#3751]
Hi, I trying to setup netdata to constantly monitor happenings on my local server. local server use pure command line Debian Jessie with no GUI.

I want to display netdata on my monitor while server running. Is that possible?

**Comment by KipourosV** [comment]
You can try this:

https://linuxconfig.org/how-to-run-x-applications-without-a-desktop-or-a-wm

**Comment by ktsaou** [comment]
@CreativForm you can't access http://your.server.ip:19999/ from your personal computer?

generally, netdata can export its metrics in a shell friendly way using this:

```sh
curl http://localhost:19999/api/v1/allmetrics
```

To use them in scripts you can do:

```sh
eval "$(curl -Ss http://localhost:19999/api/v1/allmetrics)"

echo $NETDATA_SYSTEM_CPU_VISIBLETOTAL
echo $NETDATA_SYSTEM_IO_IN
echo $NETDATA_SYSTEM_IO_OUT

# etc
```

But we don't have a nice shell UI for that. Of course, feel free to create one.

**Comment by CreativForm** [comment]
Thanks a lot
