### ISSUE TITLE
RSS feed for alarms

### ISSUE THREAD

**Issue by aapis** [netdata/netdata#3774]
I think it would be nice to be able to subscribe to an RSS feed for alarms, available updates, or maybe even some metrics.  Not sure how viable this is, but it would be handy for those of us who still use it.

**Comment by Ferroin** [comment]
Actually, I'd argue that it makes more sense to just not worry about centralizing it, at least for an initial implementation.  I mean, that's kind of the point of having an RSS reader, isn't it?

**Comment by aapis** [comment]
It would make the early implementation simpler to let the RSS reader serve as the aggregator.  Either way is fine with me though!

**Comment by Ferroin** [comment]
This might be useful to whoever implements this, assuming it ends up in `alarm-notify.sh`:
https://sourceforge.net/projects/rsstool/

**Comment by ktsaou** [comment]
> This might be useful to whoever implements this, assuming it ends up in alarm-notify.sh:
> https://sourceforge.net/projects/rsstool/

hm... I was thinking to provide an RSS format for the API.

@aapis if you can provide the exact RSS format netdata should output, it will be a great help to have this implemented.

**Comment by aapis** [comment]
I haven't forgotten about this, just haven't had time to provide a spec yet.

**Comment by Charanjet** [comment]
Hi,
i am newbie to natdata and likes it so much ,
can anyone please solve this issue 
https://github.com/netdata/netdata/issues/4499
Thanks in advance

**Comment by Ferroin** [comment]
@aapis Do you still have interest in this?  If so, some feedback on how you think the feed should look would be helpful.

**Comment by aapis** [comment]
@Ferroin I do but right now I don't have a lot of time to think about it.  I'll see about dedicating some time this/next week.

**Comment by Ferroin** [comment]
@aapis Given that you seem to be the one who's most interested in this, I think it really does make sense to wait to see what you come up with.  I think this is an awesome idea though, although figuring out exactly how to implement it sanely may not be as easy as had been initially hoped.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interesed in having this implemented, please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
