### ISSUE TITLE
[REQUEST] Prowl integration for iOS users?

### ISSUE THREAD

**Issue by P3PSIE** [netdata/netdata#3788]
Hi, 
I was wondering if you could possibly implement Prowl as an option for the alarms system in NetData? I know Pushbullet and stuff are already there, but Prowl is brilliant for iOS users and is the platform I generally use. Either way thanks for your time.
Thanks

**Comment by Ferroin** [comment]
API documentation can be found at: https://www.prowlapp.com/api.php

Unfortunately, the documentation doesn't appear to be very good and leaves some rather important things (like how you're supposed to send the parameters in an API call) unanswered.

**Comment by ktsaou** [comment]
> like how you're supposed to send the parameters in an API call

I think it is says `POST`, so just standard name-value pairs, like a web form.

@P3PSIE could you please post a few `curl` commands to send notifications to powl?

**Comment by cakrit** [comment]
@P3PSIE the linked PR #5132 is ready to be merged. Could you try it out?
