### ISSUE TITLE
There is no communication channel advertised on the website or the wiki

### ISSUE THREAD

**Issue by COLABORATI** [netdata/netdata#3797]
I did not find any communication channel for user-self-support and communication about net data - that seems to be something very fundamental missing. I do not like to pollute the issue tracker with my questions, but when there is no communication channel, where should one discuss things?

**Comment by Ferroin** [comment]
@ktsaou can correct me if I'm wrong, but AFAIK, the issue tracker is the current location for support.

**Comment by ktsaou** [comment]
Well, the github issue tracker is the only channel. Feel free to open issues for anything related to netdata. It does not have to be a bug. A lot of folks here are keen to help.
