### ISSUE TITLE
Prometheus 2 support

### ISSUE THREAD

**Issue by COLABORATI** [netdata/netdata#3798]
There is some wiki entry that covers prometheus 1 - is there also support for prometheus 2? The db backend format changed in that version.

**Comment by ktsaou** [comment]
Did they change the scraping format? If they did not, we don't have anything to do. Already works.

In their migration guide, I don't see any changes for client libraries: https://prometheus.io/docs/prometheus/2.0/migration/ - so I understand netdata already works with prometheus v2.

**Comment by paulfantom** [comment]
Nothing changed in scraping between 1.x and 2.x, apart from ditching protobuf.

@ktsaou I see there are many issues regarding prometheus integration and I can help with those, but I don't really track what new issues are flowing in. Could you add some label which says that an issue is about prometheus or tag me in it? I don't have much time to contribute code, but I can answer questions :smile:

**Comment by paulfantom** [comment]
Closing as it we are already supporting prometheus 2. Feel free to reopen if needed.
