### ISSUE TITLE
TODO: lower memory requirements

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#38]
Today, netdata keeps in memory a round robin database for dimension values, even for dimensions that permanently have a fixed value.

Check for example, the errors, collisions, events for network interfaces, or cpu interrupts that never used at a specific CPU core, etc.

A relatively easy fix, is to tweak netdata so that while a dimension has a fixed value, the round robin database will not be allocated.

Issues:
1. This will prevent netdata from knowing that for a certain period for example, data collection for the not-allocated dimension, did not happen.
2. If a different value is entered in the round robin database just once, and after some time it leaves the round-robin database, can netdata figure out that again the round-robin database is storing a fixed value to de-allocate it entirely?

**Comment by ktsaou** [comment]
I did a test with kernel [KSM](https://www.kernel.org/doc/Documentation/vm/ksm.txt).

KSM finds duplicate memory pages and merges them.

Of course, I changed netdata source code to allow this, then run this little monitoring script:

```
cd /sys/kernel/mm/ksm
watch 'for f in *; do echo -n $f: ; cat $f; done'
```

Here are the results:

```
full_scans:42
merge_across_nodes:1
pages_shared:379
pages_sharing:16982
pages_to_scan:100
pages_unshared:18940
pages_volatile:2839
run:1
sleep_millisecs:20
```

According to KSM docs:

```
pages_shared     - how many shared pages are being used
pages_sharing    - how many more sites are sharing them i.e. how much saved
pages_unshared   - how many pages unique but repeatedly checked for merging
pages_volatile   - how many pages changing too fast to be placed in a tree
full_scans       - how many times all mergeable areas have been scanned
```

So, this means KSM, out of the (18940 + 16982 + 2839 =) 38761 pages offered by netdata, it  managed to merge 16982 pages to 379 pages. So it saved 16982 - 379 = 16603 pages, or 16603 / 38761 = 42.8%.

Interesting!
We can use 43% less memory!

**Comment by ktsaou** [comment]
ok, here it is.
enabled by default too.

**Comment by ktsaou** [comment]
And the unbelievable result.

On netdata.firehol.org I have put 86400 seconds of history. A day.

Here is its ksm performance:

```
full_scans:6
merge_across_nodes:1
pages_shared:395
pages_sharing:82462
pages_to_scan:100
pages_unshared:22885
pages_volatile:2446
run:1
sleep_millisecs:20
```

around 80% less memory!

**Comment by ktsaou** [comment]
KSM has to be enabled on your system.
This is done with:

```
sudo echo 1 >/sys/kernel/mm/ksm/run
```

**Comment by ktsaou** [comment]
You may want to lower also ksmd frequency. It is CPU hungry...

I use these:

```sh
echo 1 >/sys/kernel/mm/ksm/run
echo 1000 >/sys/kernel/mm/ksm/sleep_millisecs
```

This will make it run once per second and evaluate just 100 pages (the default).
Using these values, it is totally ignorable.

**Comment by ktsaou** [comment]
KSM in action:

![image](https://cloud.githubusercontent.com/assets/2662304/11998786/eb23ae54-aab6-11e5-94d4-e848e8a5c56a.png)

**Comment by ktsaou** [comment]
from netdata.firehol.org:

![image](https://cloud.githubusercontent.com/assets/2662304/11998808/bf1f1298-aab7-11e5-8a13-a16affcdc529.png)

56% memory savings...

**Comment by koraa** [comment]
Hi,

JFYI I am using transparent compression on my fs achieving a 12.68x compression rate.
Taring /var/cache/netdata/ (which seems to contain the time series data) and compressing it with lzma yields a 878.93 compression rate (not joking here, I was quite surprised too).

**Comment by ktsaou** [comment]
These files are empty until you restart netdata. Even then, you need to let netdata run enough time to fill them.

**Comment by ktsaou** [comment]
Normally, you will get 50% less due to deduplication and 50% more due to compression. So, the files will compress to around 25% of their expanded size.

**Comment by koraa** [comment]
oh, nevermind then!

**Comment by koraa** [comment]
OK nevermind. Restarted, and it's less extreme!

**Comment by paulfantom** [comment]
We are constantly aiming to lower memory requirements and make netdata perform faster so I am closing this issue. Reopen if needed.
