### ISSUE TITLE
[Suggestion]: Support brotli compression in the web server.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#3810]
This isn't really a feature request per-se, just something I think would be nice to have.

Brotli is a newer compression codec designed by Google specifically for use with HTTP compression.  The official upstream implementation can be found at https://github.com/google/brotli.

Overall, for the type of data Netdata is typically serving (almost entirely HTML, XML, and JSON) and using the lowest compression levels, brotli produces marginally worse compression ratios than gzip while providing significantly better performance, while compressing far better than gzip but still maintaining significantly better performance when using the highest compression levels.  All major browsers (Chrome, Firefox, Opera, Safari, and Edge) have supported it since late 2017.

In my own testing, done using approximately 50 MB of assorted data retrieved from the netdata API on one of my systems (including chart definitions, javascript code, rendered SVG's of charts, HTML and CSS files), brotli with compression level 1  produced a result that was approximately 1.3% larger than using gzip with compression level 1, but did so in only 33% of the time.

Using the same test data, but compression level 9, brotli produced a result that was only 0.2% of the size of the gzipped result (gzip gave a roughly 3MB file, brotli spit out a 23k file), in less than _5%_ of the time.

Based on this, it looks like this might be an easy option to significantly improve netdata's server-side performance and resource usage while people are accessing the dashboard.

**Comment by ktsaou** [comment]
Do you know how the web server knows if it can use brotli or gzip?
Will this work when netdata is proxied via another web server?

**Comment by Ferroin** [comment]
The Wikipedia page on [HTTP compression](https://en.wikipedia.org/wiki/HTTP_compression) is a reasonable starting point, and has links to the various relevant RFC's at the end.

In short, the client sends an `Accept-Encoding` header, specifying a list of encodings (in arbitrary order, though most usually list them in preferred order), with an optional preference indication (which AFAIK nobody actually pays attention to).  The server is then supposed to pick one from that list, and use that, while making sure the `Content-Encoding` header is set correctly.  Note that the server is under no obligation to honor this list, though it is generally expected that it won't pick something _not_ on this list, with the notable exception of the `identity` encoding, which is always allowed, and means that no encoding method has been used.  The same methodology is also used for the transfer encoding (though the header there is called `TE`), though we can probably safely ignore that (though supporting the `chunked` transfer encoding might provide a speed boost to proxies that are serving HTTP/2).

As far as proxying, it is dependent on the proxy implementation and configuration.  If the proxy is configured to just pass the body through unmodified, then it will work fine.  If the proxy needs to parse it at all, then there might be issues, but only if the proxy software does not support (or is not configured to handle).  Nginx needs a third-party module for any brotli support, though it's easy to install in most cases.  Apache has native support provided you build it with the correct module.  Not sure about any others.  However, if actual negotiation as described above is implemented, it shouldn't matter.

**Comment by ktsaou** [comment]
I think a few systems support `libbrotli-dev` or `libbrotli-devel`. Unfortunately not all (arch for example does not have this).

We have 2 options:

1. copy the source of brotli into netdata - it will be a bit of work, because the brotli devs decided to use cmake. It seems like `autotools` but I am not sure how easy it will be to include it in netdata.

2. depend on `libbrotli` (and the header files) being available on the target system.

What do you think?

**Comment by Ferroin** [comment]
I think depending on libbrotli and the headers is fine.  Arch _should_ have it by now, they just don't for some reason I can't fathom (I mean, it came out 2 years ago, that much delay is kind of insane for Arch).

It would be nice however to include it in the static 64-bit build.  I don't use this build myself, _but_ having as many of the features as reasonably possible in it seems to be the intent.

If you do a PR with this, tag me on it, I can check the build against a bunch of different Linux distributions for you (I've got VM's set up for development reasons running stable and development versions of debian and OpenSUSE, current and LTS versions of Ubuntu, the ,most recent stable Fedora release, and Arch and Alpine that I can check things against).

**Comment by jmunson** [comment]
If this gets added to the webserver, would the streaming of metrics from one netdata to another take advantage of it?

**Comment by Ferroin** [comment]
Probably not without some changes to how the streaming protocol works.  As of right now, the streaming protocol looks like HTTP, but it isn't really, and it's different enough that you can't reasonably proxy it through an HTTP server.

That said, there are a handful of useful things that would be possible if the streaming were to support HTTP (proxying for one, which would allow actual authentication, encrypted streaming, and a whole slew of other things that would not be easy to implement natively in netdata), so it may be possible for some future version of netdata.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
