### ISSUE TITLE
Add an option for time to be 12-hour based

### ISSUE THREAD

**Issue by cwoodwar6** [netdata/netdata#3814]
As mentioned in https://github.com/firehol/netdata/issues/64, the browser locale should be changing the clock in the legend to 12hr for U.S. English. Having an option to set this would be more ideal incase this is a problem with the locale.

It would be nice if that option applied to all time references (particularly on the x-axis of the chart) but it appears that wouldn't be feasible due to spacing limitations.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
