### ISSUE TITLE
More intelligent alerting when ZFS space is filling up

### ISSUE THREAD

**Issue by candlerb** [netdata/netdata#3833]
I have a container host with many ZFS datasets, but all in the same zpool.

When the disk usage jumps up for some reason, I get separate alert E-mails for every single dataset:

* `disk_space._var_lib_lxd_containers_netbox.zfs` - out of disk space time = 1h
* `disk_space._var_lib_lxd_containers_smtp.zfs` - out of disk space time = 1h
* `disk_space._var_lib_lxd_containers_unifi.zfs` - out of disk space time = 1h
* etc

That's because netdata sees them all as separate filesystems filling up; but they all draw space from the same underlying zpool.  So it would be great if I could get a single alert (relating to the free space in the zpool) rather than separate alerts for every filesystem.

Admittedly this is complicated somewhat if zfs reservations and/or quotas are being used. It's possible that one particular filesystem *could* fill up before the others.

In my case, I'd be happy to disable all the zfs filesystem alerts, and just have an alert on the zpool free space filling up.  Possibly related: #3089 

Workaround: the zpool is called "zfs" and I do get an alert for `disk_space._zfs` as well. So I think the following should suppress the alerts for the child datasets (some of which are not mounted on `/zfs`):

```
template: out_of_disk_space_time
...
families: /zfs !/zfs/* !/var/lib/lxd* *
```

**Comment by ktsaou** [comment]
Thanks. Unfortunately I don't know how to find this information using data exposed the zfs kernel module. If anyone knows, please give us a few directions.

**Comment by cakrit** [comment]
@mfundul can you help with this one?

**Comment by mfundul** [comment]
This is related to [#3089](https://github.com/netdata/netdata/issues/3089). We should decide whether we want to maintain our own customized low overhead high maintenance ZFS IOCTL support or just use the zfs and zpool utilities.

**Comment by candlerb** [comment]
`zfs list` and `zpool get` have `-H` and `-p` flags to make parsing the output easier.

Before:

```
root@nuc1:~# zfs list | head -5
NAME                                                                                      USED  AVAIL  REFER  MOUNTPOINT
zfs                                                                                      54.1G  7.92G    96K  /zfs
zfs/liblxd                                                                               1.37M  7.92G  1.37M  /var/lib/lxd
zfs/lxd                                                                                  32.9G  7.92G    96K  none
zfs/lxd/containers                                                                       30.6G  7.92G    96K  none
```

After:

```
root@nuc1:~# zfs list -Hp | head -5
zfs	58067845120	8504147968	98304	/zfs
zfs/liblxd	1437696	8504147968	1437696	/var/lib/lxd
zfs/lxd	35352010752	8504147968	98304	none
zfs/lxd/containers	32881582080	8504147968	98304	none
zfs/lxd/containers/builder	10129408	8504147968	396185600	/var/lib/lxd/storage-pools/default/containers/builder
```

`zpool list` and `zpool events` support `-H` but not `-p`. Unfortunately `zpool status` has neither.

However, `zpool get -Hp all` or `zpool get -Hp size,allocated,free,health,dedupratio,fragmentation` would be a reasonable way of checking the zpool status, I think.

**Comment by ilyam8** [comment]
Closing in favor of #3089 Basically the same problem - https://github.com/netdata/netdata/issues/3833#issuecomment-442882312

@candlerb found a workaround and updated OP
