### ISSUE TITLE
email schemas

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#3853]
gmail (and possible other mail clients) support schemas to provide nice buttons like this:

![image](https://user-images.githubusercontent.com/2662304/41662315-8025aa98-74a9-11e8-8e96-f92a3aff3ccc.png)

Based on [the docs](https://developers.google.com/gmail/markup/reference/go-to-action), something like this is needed:

```html
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "EmailMessage",
  "potentialAction": {
    "@type": "ViewAction",
    "target": "${goto_url}",
    "url": "${goto_url}",
    "name": "View netdata"
  },
  "description": "View '${host}' netdata dashboard"
}
</script>
```

at this place (just after `<body>`): https://github.com/firehol/netdata/blob/899c3d93f93dbaebd8d1678306b57679991790f7/plugins.d/alarm-notify.sh#L2093

However, gmail has some kind of authentication that I cannot fullfil.
Any help is appreciated!

**Comment by Ferroin** [comment]
What exactly do you mean by 'some kind of authentication'?  DMARC? DKIM? Something else?

**Comment by ktsaou** [comment]
Check this: https://developers.google.com/gmail/markup/testing-your-schema

It says DKIM and SPF...

**Comment by Ferroin** [comment]
OK, so they do (functionally) want DMARC equivalent validation.  If you're sending from your own Gmail account, it should automatically meet these requirements as all outbound messages sent via Gmail are automatically have valid DKIM signatures, meet the requirements Google's SPF records lay out, and pass DMARC verification.

The issue that arises here is that it will only work for users who are doing things in such that:

* Their sender domain and mailserver both have DKIM properly configured.
* Their DNS records lay out correct SPF policies and the outbound mail complies with those policies.

Realistically, both situations are likely to be the case unless the user is running a private email server, and even then it's not hard to meet the second requirement and not prohibitively difficult to meet the first.

**Comment by Ferroin** [comment]
The really tricky part here is going to be the registration.  It assumes a number of things about the use case that do not apply to Netdata currently, some of which are likely to never apply (for example, the final point about Go-To actions [here](https://developers.google.com/gmail/markup/registering-with-google) will strictly speaking never apply to netdata).

However, that shouldn't matter for individual users who are piggybacking on their GMail account for netdata alerts, as even unregistered cases are displayed for cases where the sender and recipient are the same address.

**Comment by ktsaou** [comment]
hm... this feature would be nice when we centralize all notifications. So, the server sending all notifications could meet these requirements.

Also, since the next version of the registry will require some kind of email validation, it would be helpful to add such action buttons to the emails sent by the registry.

Can you help me setup DKIM and SPF for the netdata demo sites?

I have the following domains for netdata:

- my-netdata.io
- mynetdata.io
- netdata.cloud
- netdata.rocks

And this is the default email config on all these hosts: https://github.com/firehol/netdata-demo-site/blob/fca7954eacef14337eab17001df16c4b3f194e2f/install.sh#L249-L280

**Comment by Ferroin** [comment]
For SPF, actual setup is reasonably easy.  It just involves adding a TXT record for each domain to your DNS configuration.  The [Wikipedia page](https://en.wikipedia.org/wiki/Sender_Policy_Framework) has one of the better explanations for how it all works, though is unfortunately a bit lacking in exact detail. The most basic policy that should work for a locally hosted mail server looks like this:

    "v=spf1 +mx ~a -all"

That says that whatever systems show up in your MX records are valid senders, systems for which you have address records (A or AAAA, or CNAME records that point to a valid A or AAAA record) are not valid but should still be accepted, and everything else is invalid.  if you've got an external mail hosting provider, they usually provide an SPF record that you can include in your policy (and typically include instructions on how to do so).

DKIM on the other hand is a lot more complicated to set up.  At its core, it's a means of providing cryptographic verification of certain email headers (most importantly the `From:` header, and like with anything involving public key cryptography, it's not exactly simple.  I don't think there's support natively in Postfix for it, but there is an outbound mail filter program called [OpenDKIM](http://opendkim.org) that works with Postfix through the milter interface, however, I've never used it, so I won't likely be much help setting it up.  The official DKIM website (http://dkim.org/) has some resources though that will probably help with the setup.

**Comment by dpointk** [comment]
I will be happy to assist on the matter. We do this on a daily basis for our customers.

Where are your sending the emails from today? DKIM with postfix should be configured on that server. If you are using Google’s G Suite there’s and option to set it up from there too.

**Comment by ktsaou** [comment]
Wow! @dpointk thank you!

I am using digital ocean and many other hosting providers that donate VMs to netdata.
So, I am afraid I'll have to set it up manually.

**Comment by dpointk** [comment]
It’s a matter of installing it and setting it up. We have one of the servers that are donated to the project here at Octopus. 
If I can play with it. I will set it up and arrange the script for you to output the needed changes for the domain (for DKIM etc.)

**Comment by cakrit** [comment]
@dpointk can you help us with this?
@gmosx this is very interesting for the hub

**Comment by cakrit** [comment]
We added DKIM and SPF to netdata.cloud last week.
