### ISSUE TITLE
[bug]some metrics don't report to /allmetrics endpoint with prometheus format

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#3866]
# What I did

1. installed memcached and start it
1. installed netdata and start it

# What I see

* memcached charts showed on dashboard
* memcached metrics showed on `/api/v1/allmetrics?format=shell`
```bash
# chart: memcached_11211.delete (name: memcached_11211.delete)
NETDATA_MEMCACHED_11211_DELETE_HITS="0"      # requests
NETDATA_MEMCACHED_11211_DELETE_MISSES="0"      # requests
NETDATA_MEMCACHED_11211_DELETE_VISIBLETOTAL="0"      # requests
```
* memcached metrics didn't show on `/api/v1/allmetrics?format=prometheus&help=yes`
  * only comment, no metrics
  * `help=yes` or absent don't affect the results
```bash
# COMMENT homogeneus chart "memcached_11211.delete", context "memcached.delete", family "delete ops", units "requests"

# COMMENT homogeneus chart "memcached_11211.set_rate", context "memcached.set_rate", family "set ops", units "requests/s"

# COMMENT homogeneus chart "memcached_11211.net", context "memcached.net", family "network", units "kilobits/s"
```
* After I restart the netdata, all goes well.

*I have 2 servers have the same problem. I restarted one and recovered and left the other as is to debug.*

**Comment by ktsaou** [comment]
The only condition I see in the code, is if the dimensions of the chart are having successful collections.

In detail:

The COMMENT lines you posted are here: https://github.com/firehol/netdata/blob/e8915e26537615282003d6baf094d59712c9b4f1/src/backend_prometheus.c#L196-L203

There is a condition per dimension here to ensure we have collected some metrics for the dimension:
https://github.com/firehol/netdata/blob/e8915e26537615282003d6baf094d59712c9b4f1/src/backend_prometheus.c#L207-L208

And when you use `average` for the metrics, there is another here, to ensure we have some value to send (`nan` and `inf` are gaps on the chart): https://github.com/firehol/netdata/blob/e8915e26537615282003d6baf094d59712c9b4f1/src/backend_prometheus.c#L346

So, the question is: do the memcached charts on the netdata dashboard roll with values?

**Comment by ktsaou** [comment]
btw, @Wing924 please sign the contributors license agreement. We need this to switch the license of netdata. Find more information here: https://github.com/firehol/netdata/blob/master/CONTRIBUTORS.md. It is simple: you just need to make a PR with your name in that file.

If you have any questions, I'll be glad to answer them.

**Comment by Wing924** [comment]
@ktsaou I don't whether this is a bug or specification. 
Prometheus backend with `average` mode don't report values with all `0` if the row type is `percent-of-absolute-row`.
because it's hard for backend to determine whether data is zero or missing, I suggest report those values to backend.

**Comment by ktsaou** [comment]
hm...this shouldn't be happening.
 let me try to reproduce it...

**Comment by Buravchik** [comment]
Have same problem since recently.

**Comment by vlvkobal** [comment]
I can't reproduce it on Manjaro **18.0** and Ubuntu **18.10** with Netdata **1.12.1-6ef4097**. Does anybody still have this issue with recent Netdata? @Wing924, @Buravchik, do you still come across the problem?

**Comment by Wing924** [comment]
Since it's very rare bug. I can't tell if it happened again.
I'll close it. If kit happen again, I'll reopen it.
