### ISSUE TITLE
Improve "Non Zero" behaviour

### ISSUE THREAD

**Issue by arnowelzel** [netdata/netdata#3868]
I got quite confused when trying a new plugin (see https://github.com/coraxx/netdata_ts3_plugin/issues/12) and thought there is a bug because single dimensions in a chart just disappeared sometimes and I did not understand why. Then I learned the meaning of the "Non Zero" option in the settings.

First problem: You never know if the visible legends are all the available dimensions or if there may be more dimenions which are just hidden because of the "Non Zero" setting.

Second problem: If all dimensions are zero then all legends and zero lines are displayed again - a bit illogical, if an option is intended to hide zero values.

So I propose an change like this:

1) Always display all legends, but those which belong to hidden dimensions get dimmed or greyed out to make it clear that the dimensions his hidden intentionally and the missing line is not a bug.

2) Hide zero dimensions always and not only if there is at least one dimension with non-zero values.

**Comment by ktsaou** [comment]
Point 1 needs some work to make it properly (it should sort the dimensions so that the zero dims are at the bottom - this sorting should happen on every update, if the zero/non-zero dims changed).

Point 2 is somewhat problematic. If everything is zero, an empty chart will be the result.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
