### ISSUE TITLE
[Feature] Gnocchi backend support?

### ISSUE THREAD

**Issue by skibbipl** [netdata/netdata#3870]
I've been looking for some good time series database for storing historical data from netdata for multiple servers. It seems [Gnocchi](https://github.com/gnocchixyz/gnocchi) matches my needs. Can netdata support this backend in the future? Unfortunately I'm not that good in C to make the support by myself.

**Comment by ktsaou** [comment]
Generally netdata can and we accept PRs. It would be simpler for them to accept graphite and opentsdb protocols though. These are pretty simple to implement and widely used.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interesed in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
