### ISSUE TITLE
How can i run netdata with an existing HTTP Server ?

### ISSUE THREAD

**Issue by wemersonrv** [netdata/netdata#3883]
Hi,

There is a way to run netdata webserver part on to be served with an existing NGINX or Apache server? So, i do not need to install two webservers apps on the same VPS.

**Comment by arnowelzel** [comment]
Personally I just use a reverse proxy in Apache to handle all the requests from outside (and provide HTTPS as well). Yes, then you still have netdata itself as a second web server, but from outside you only need to access one service. Also see https://github.com/firehol/netdata/wiki/netdata-security for more options how to protect netdata against access from outside.

**Comment by wemersonrv** [comment]
@arnowelzel Tx, it's a great tip.

I`m use NginX and will make a reverse proxy and your tip is great. Tx a lot my friend.

I am looking about **install all your netdata in headless data collector mode**  option to use only one netdata server to access metrics of all my servers... How many resources i need to compute per server in this situation ?

**Comment by arnowelzel** [comment]
According to https://github.com/firehol/netdata/wiki/Replication-Overview each collector needs 5 MB of RAM on the slaves. But I'm not sure, how much the server would need to handle the data from each collector. Maybe you just try it. The memory consumption of the server is also displayed in the web UI at the end of the navigation menu. A standalone server with web UI uses about 64 MB on my server for 3.967 metrics, 338 charts and and 83 alarms.

**Comment by Ferroin** [comment]
The short but somewhat imprecise answer is that you can just add together the space used on each slave, plus the space the master uses without anything streaming to it, plus a few percent of extra space, and that should give you a good idea of the expected worst case space usage.

That said, the master system is likely to see significant benefits from using memory deduplication.  To do that, follow the general instructions [here](https://github.com/firehol/netdata/wiki/Memory-Deduplication---Kernel-Same-Page-Merging---KSM), and then make sure you're using either `memory mode = ram` (the default) or `memory mode = save` for Netdata's database.  The exact savings will vary, but if you have a lot of slaves with very similar system configurations, you may get in excess of 50-60% memory savings.

Also, if you don't intend to look at dashboards on the individual slaves, you can cut memory usage there significantly by configuring them to use `memory mode = none`, which tells Netdata to not store any data locally, and just send it directly to the master node.

**Comment by cakrit** [comment]
This appears to be answered, please reopen if there are any more questions.
