### ISSUE TITLE
Netdata api (format=prometheus_all_hosts) missing hosts

### ISSUE THREAD

**Issue by timothynfarmer** [netdata/netdata#3891]
I've got 8 slaves pointing to a master. New slaves seem to not be able to be scraped by prometheus. If I locally curl/wget I'm only get 15021 lines. I grep for the particular hosts and see lines see the below.

`netdata_info{instance="hostname",application="netdata",version="1.10.0-308-g9598db2_rolling"} 1 1530016287542`

If I grep for the version, I see 4 of my hosts in prometheus & grafana. If I grep for the version above I see 4 hosts I'm missing. Grepping for the count of a particular hostname that's missing yields only the result above.

**Comment by timothynfarmer** [comment]
Stream.conf

```
[stream]
    enabled = no
    destination =
    api key =
    timeout seconds = 60
    default port = 19999
    buffer size bytes = 1048576
    reconnect delay seconds = 5
    initial clock resync iterations = 60
[MY_API_KEY]
    enabled = yes
    allow from = *
    default history = 3600
    default memory mode = ram
    health enabled by default = auto
    default postpone alarms on connect seconds = 60
    multiple connections = allow
[MACHINE_GUID]
    enabled = no
    allow from = *
    history = 3600
    memory mode = ram
    health enabled = auto
    postpone alarms on connect seconds = 60
    multiple connections = allow
```

prometheus.yml
```global:
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'netdata'
    metrics_path: /api/v1/allmetrics
    params:
      format: [ prometheus_all_hosts ]
    static_configs:
      - targets: ['localhost:19999']
```

**Comment by timothynfarmer** [comment]
I'm now wondering if this is because the utilization of these servers is so low that netdata essentially doesn't think anything is going on when prometheus scrapes it.

**Comment by ilyam8** [comment]
@timothynfarmer, hi. We tried to reproduce this issue using v1.31.0, but there is no problem. The parent instance exposes metrics for all its children.
