### ISSUE TITLE
Alpine package is broken

### ISSUE THREAD

**Issue by develar** [netdata/netdata#3897]
All python plugins are disabled as result:

```
:/root$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace nginx
Traceback (most recent call last):
  File "/usr/libexec/netdata/plugins.d/python.d.plugin", line 31, in <module>
    from bases.loaders import ModuleAndConfigLoader
ImportError: No module named bases.loaders
```

As result, local nginx is not discovered, docker is not discovered. 

Solution (thanks for awesome docs) — do not use package, but installer:
```
curl https://my-netdata.io/kickstart-static64.sh >/tmp/kickstart-static64.sh
sh /tmp/kickstart-static64.sh
```

Reproduced on 2 clean machines (scaleway).

4.9.65-1-hardened Alpine 3.7

repo:

```
http://nl.alpinelinux.org/alpine/edge/main
http://nl.alpinelinux.org/alpine/edge/community
http://nl.alpinelinux.org/alpine/edge/testing
```

PS. Netdata is awesome. So easy to install and so amazing defaults. First impression was not good due to broken package, but one-click installation instead of alpine package  works great.

**Comment by ktsaou** [comment]
hm... interesting. I don't know who is the alpine maintainer for netdata. See #651
If anyone knows please invite him here and at #651

**Comment by cakrit** [comment]
Closing since we've had no comments in a while. Please comment if needed.
