### ISSUE TITLE
Use Liberapay to get recurring funding

### ISSUE THREAD

**Issue by davidak** [netdata/netdata#3900]
While i like what Open Collective is doing, i don't like their 10% fee. Also they only support Credit Card, what very few people in europe have. I know they work on PayPal integration, but PayPal has again also high fees! At the end, you would get less money than you should!

Liberapay is like Patreon, but without fees (only from payment provider https://liberapay.com/about/faq#fees). It is free software maintained by a non-profit organization that funds itself on their own platform. I use it to support many free software projects i use and would like to support you there!

**Comment by paulfantom** [comment]
Thanks for an idea but we have no need for it :smile:
