### ISSUE TITLE
Feature: New Dashboard for monitoring Kubernetes Clusters.

### ISSUE THREAD

**Issue by shadycuz** [netdata/netdata#3918]
I'm not sure what the move to CNCF will mean for Netdata but I feel like having better support for Kubernetes would be a great enhancement. I'm putting this issue together to discuss possible implementations. 

What I'm proposing would most likely be a new repo containing a new frontend just for kubernetes. This front end would use the Kubernetes API to discover the Netdata pod running on each master and worker node. Once the Netdata pods were discovered it would then use the Netdata API to retrieve monitoring information for the host and the containers running on that host. It would then display a "Cluster" level view of all hosts and scheduled pods. 

While we could change the current Netdata to do the same thing I find a couple issues with that approach.

1. For each node in the cluster, you increase the number of requests as each node is querying the other nodes for its information.

2. Typically something that needs to be scheduled on each node is ran as a dameonset. It's uncommon to make these available externally through a ingress and they don't have the option to scale up and down.

3. It also could do weird things with "my-netdata". Ideally, we would only want one item in "my-netdata" and clicking on that would reveal the cluster dashboard.

We have other options as well. We could build a flag into Netdata so it runs in "dashboard" only mode and we could also have a flag so we can list where Netdata is running. This means we could possibly support other things like AWS fargate, EC2 (ASG's), Docker Swarm etc. 

While we are deciding on what is the best approach we can implement #3520 first.

**Comment by Ferroin** [comment]
I'm not exactly an expert on the dashboard, but from what I do know, it looks to me like there's only two tricky parts here:

1. Actual discovery of the target nodes.  Unless I'm mistaken, this could probably be integrated into the dashboard itself as part of item 2 by just telling it what API to query where.
2. Support in the existing dashboard code to pull and collate metrics from multiple systems.

Realistically, all that should be needed for this once the above are implemented is a dead-simple web server (like, `python -m http.server 80 --directory /wherever` simple, as it just has to serve a bunch of static files) and somewhere to keep a copy of the (configured)  dashboard.

**Comment by ktsaou** [comment]
@cakrit 	k8s monitoring is very important for netdata. Add it to our roadmap please.

**Comment by cakrit** [comment]
Blocked by #3520, which will provide the new Kubernetes collector.

**Comment by cakrit** [comment]
@rduffield and @manos-saratsis, this issue contains some suggestions for a cloud-based k8s dashboard. With the addition of labels we're getting closer to this, but we'll need a proper ideation phase, that won't happen in this issue. So please close when you have created a relevant epic in the cloud repo.

**Comment by ilyam8** [comment]
Not Netdata Agent feaute, being implemented as Netdata Cloud feature.
