### ISSUE TITLE
Badges: Specify Label & Value sizes and Alignment

### ISSUE THREAD

**Issue by ccremer** [netdata/netdata#3925]
Hi, it's me ;)

I just wanted to know whether it's possible to set a fixed label and value width for the netdata badges. As I'm currently developing a custom dashboard where i use badges in a widget. However, visually they do not look misaligned.

Would it be possible to specify the desired label and value length, so that ordering multiple badges vertically would make more sense? Take the screenshot below for example. I would like to set the red line as the alignment reference. Expand the left side so that it ranges from left to red line (grey arrows), while the right (green) part takes the rest of the width.
![badges](https://user-images.githubusercontent.com/12159026/42202987-b4c9f0a8-7e9d-11e8-843a-5060ef7dcc5b.png)

Ideally, the label (& value) can be aligned left, center or right.

**Comment by underhood** [comment]
@cakrit I will take care of this

**Comment by ilyam8** [comment]
fixed in #6903
