### ISSUE TITLE
Metric formula for alert

### ISSUE THREAD

**Issue by petarkozic** [netdata/netdata#3926]
Hi,
I have installed netdata on about 30 VPS servers and several bare-metal servers. Primary using netdata as collector for my prometheus cluster.
For now I scrape metric but I need to start to write alert rules for prometheus alerting.
I have some own API for notification and because I want to use prometheus, also in Prometheus I have retention of metrics about 100 days.

I need info, where can I found formula metrics for netdata alert rule ? Is that somewhere hardcoded or in some conf files ?
In health.d folder I can see that rules but some variables I don't understand, as:

On example for disk fill:
I understand metrics and what do but some variables I don't know what means

($this - $avail) / (($now - $after) / 3600)

$this - that is current state
$avail - I supposed available space
$now - I don't know ?
$after - I don't know ?
3600 - I understand this, this is in one hour.

Or on example nginx.conf in health.d

$now - $last_collected_t

What is $now, what is $last_collected_t

Can I found somewhere what this variable was ?

Thank's for your help.

**Comment by ktsaou** [comment]
Here is the netdata health configuration reference: https://github.com/firehol/netdata/wiki/health-configuration-reference

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/blob/master/conf.d/health.d/ram.conf#L4-L10

**Comment by petarkozic** [comment]
@l2isbad 
Ok, I saw that. Please tell me if you know, if I open:
https://registry.my-netdata.io/api/v1/alarm_variables?chart=system.cpu

I can see all that variable, can I use them somehow in prometheus rules ?
Thanks !

**Comment by l2isbad** [comment]
i am not familiar with prometheus rules unfortunately

**Comment by petarkozic** [comment]
@l2isbad 
thank you in any way

**Comment by petarkozic** [comment]
Thank you @ktsaou I'm trying to do that :)

**Comment by ktsaou** [comment]
Closing this, but if you need help, post here.
