### ISSUE TITLE
netdata does not appear to send host tags via graphite backend

### ISSUE THREAD

**Issue by oskapt** [netdata/netdata#3936]
I have remote netdata systems configured with tags for grouping stats together. This has been working well with InfluxDB via the opentsdb backend.

I switched from opentsdb to graphite today, and graphite isn't showing tags that were available in InfluxDB. I dumped the datastream between netdata and graphite, and it doesn't appear to be sending host tags.

Tags are a relatively new feature in graphite - does netdata support them?

**Comment by ktsaou** [comment]
hm... no, I didn't know they supported tags.
Can you point the relevant documentation?

**Comment by oskapt** [comment]
sorry for the late reply - i wasn't getting notifications from github.

documentation is [here](https://graphite.readthedocs.io/en/latest/tags.html). it's a little clunky within graphite, but from the netdata side, it's as easy as sending the data to the metric and then appending tags afterward, separated by semi-colon: `netdata.some.metric.graph;key1=value1;key2=value2`

**Comment by ktsaou** [comment]
ok, it is in PR #3992 
Can you test it?

**Comment by ktsaou** [comment]
@oskapt the feature you requested has been implemented, but I don't want to merge it without testing it first.
Would you like to checkout this PR and test it? If it works, I'll merge it.

**Comment by ktsaou** [comment]
@oskapt I cannot merge this, until someone confirms it works.
Could you please test it?

**Comment by oskapt** [comment]
Once again, I was having issues with Github notifications. My mailserver uses [greylisting](https://en.wikipedia.org/wiki/Greylisting) as an anti-spam measure, and Github wasn't resending mails that the greylisting engine temporarily rejected. They just stop sending me emails. I've whitelisted the domain, so it shouldn't be a problem anymore.

I will schedule a test of this. I'll have to build a separate environment for it, since I'm only running netdata in production. I'll replicate what I have, test it, and get back to you.

**Comment by ktsaou** [comment]
ok, thanks!

**Comment by paulfantom** [comment]
Closing as this should be fixed now. Please reopen if this is still valid.

**Comment by oskapt** [comment]
Tested and working. Thanks for implementing this!
