### ISSUE TITLE
is it possible to start netdata using supervisor or running without root/sudo permission ?

### ISSUE THREAD

**Issue by changchichung** [netdata/netdata#3948]
I want to install netdata in a ubuntu machine for my develop env, but I dont have the root/sudo permission to start netdata service. the sysadmin install the netdata for me , but I modify the config alot to fit my req.
is there anyway to run netdata without sudo/root permission ? or is that possible to run with supervisor ?

**Comment by ktsaou** [comment]
Sorry for the long delay in this question.

You can install netdata as non-root. Netdata will run, although a few plugins will not work.

Follow this guide: https://github.com/netdata/netdata/tree/master/installer#install-netdata

You will need to pass the parameter `--install ~/` to `netdata-installer.sh` to install netdata in your home. Other than that, everything is the same.

**Comment by 161134050** [comment]
> Sorry for the long delay in this question.
> 
> You can install netdata as non-root. Netdata will run, although a few plugins will not work.
> 
> Follow this guide: https://github.com/netdata/netdata/tree/master/installer#install-netdata
> 
> You will need to pass the parameter `--install ~/` to `netdata-installer.sh` to install netdata in your home. Other than that, everything is the same.

That link 404's

**Comment by prologic** [comment]
Please use this link: https://docs.netdata.cloud/packaging/installer/
