### ISSUE TITLE
How to enable sensor plugin?

### ISSUE THREAD

**Issue by axi92** [netdata/netdata#3953]
I have installed netdata on my Pi and cant find the sensor section?
Is it not working on the Pi3?

I can get for example the temp with either:
`/opt/vc/bin/vcgencmd measure_temp`
or this
`cat /sys/class/thermal/thermal_zone*/temp`

**Comment by Ferroin** [comment]
The `sensors` plugin makes use of a library provided by the `lm_sensors` package.  Most likely, that package just isn't installed on your Pi (it generally does not come as part of the standard install on most Linux distributions), and installing it should fix things (make sure to restart netdata after installing it, otherwise the plugin won't see that it's there).

**Comment by axi92** [comment]
It seems like the lm_sensors don't support rPi
https://github.com/groeck/lm-sensors/issues/30

**Comment by Ferroin** [comment]
No, it does support it, it's just that the `sensors-detect` tool doesn't see it (that tool exists to help you figure out what modules you need to load for your hardware, because sensor chips aren't exactly standardized).  The `sensors` command provided by `lm_sensors` works fine, provided the system is configured correctly (and it appears as per raspberrypi/linux#2182 that it still is not by default).

**Comment by ktsaou** [comment]
Hi.

This is documented. Netdata can monitor RPi temperatures.
Check this: https://github.com/netdata/netdata/wiki/netdata-for-IoT#8-monitoring-rpi-temperature

**Comment by tbarbette** [comment]
Dead link. It's now https://learn.netdata.cloud/docs/agent/netdata-for-iot/#monitoring-rpi-temperature

**Comment by rodrigoferrazazevedo** [comment]
Netdata cannot monitor the voltage of Raspberry Pi? Anyone here done this?

**Comment by ilyam8** [comment]
I see it should collect voltage data

https://github.com/netdata/netdata/blob/d568a47c6bb7c2096d4dc534cd7775923bd5adfa/collectors/charts.d.plugin/sensors/sensors.chart.sh#L151-L158

**Comment by rodrigoferrazazevedo** [comment]
Thanks, ilyam8, but in my laptop the sensor data is enabled but in my Raspberry Pi only the temperature sensor is showed. I searched in the documentation but don't able to enable this in Raspberry.

**Comment by ilyam8** [comment]
Could be there are no other sensors in `/sys/devices`

https://github.com/netdata/netdata/blob/d568a47c6bb7c2096d4dc534cd7775923bd5adfa/collectors/charts.d.plugin/sensors/sensors.chart.sh#L16-L17

https://github.com/netdata/netdata/blob/d568a47c6bb7c2096d4dc534cd7775923bd5adfa/collectors/charts.d.plugin/sensors/sensors.chart.sh#L47-L55

https://github.com/netdata/netdata/blob/d568a47c6bb7c2096d4dc534cd7775923bd5adfa/collectors/charts.d.plugin/sensors/sensors.chart.sh#L39-L44

https://github.com/netdata/netdata/blob/d568a47c6bb7c2096d4dc534cd7775923bd5adfa/collectors/charts.d.plugin/sensors/sensors.chart.sh#L35-L37


```cmd
[ilyam@karasik devices]$ pwd
/sys/devices
[ilyam@karasik devices]$ find . -maxdepth 10 -name \*_input
./platform/coretemp.0/hwmon/hwmon2/temp6_input
./platform/coretemp.0/hwmon/hwmon2/temp3_input
./platform/coretemp.0/hwmon/hwmon2/temp7_input
./platform/coretemp.0/hwmon/hwmon2/temp4_input
./platform/coretemp.0/hwmon/hwmon2/temp1_input
./platform/coretemp.0/hwmon/hwmon2/temp5_input
./platform/coretemp.0/hwmon/hwmon2/temp2_input
./pci0000:00/0000:00:1d.0/0000:04:00.0/hwmon/hwmon1/temp1_input
./virtual/thermal/thermal_zone0/hwmon0/temp1_input

```

**Comment by rodrigoferrazazevedo** [comment]
Thanks. My terminal listed only the thermal sensor in devices/virtual.

**Comment by OdysLam** [comment]
@rodrigoferrazazevedo, so the Rpi has not enabled or doesn't have a voltage sensor?

BTW, welcome to our community! If you have any other questions please create an issue or even better create a post at our [forums](https://community.netdata.cloud)! :)

**Comment by Ferroin** [comment]
> @rodrigoferrazazevedo, so the Rpi has not enabled or doesn't have a voltage sensor?

Most likely, the kernel itself does not have a driver for the voltage sensor (whether this is due to lack of availability of such a driver, or just that kernel build not having it enabled I don’t know). The SoC itself should have a voltage sensor.
