### ISSUE TITLE
I can't increase the storage time.

### ISSUE THREAD

**Issue by T1MOXA** [netdata/netdata#3961]
I tried
```
[global]
history = 1200
#update every = 1
low rate history = 5760
low rate update = 30
# keep last 600 history entries and then start to clean older history
clean history after = 1200
# keep one history entry every 60 and delete other 59  
keep one data every = 30
```
and
```
[global]
history = 84200
```

After that I tried to restart the service in two ways.
`sudo service netdata restart`
`sudo killall netdata; sleep 10; sudo netdata`

![image](https://user-images.githubusercontent.com/19938629/42697512-fb8a7dd6-86c3-11e8-9e71-f22c7cc2295c.png)

**Comment by cakrit** [comment]
Hi @T1MOXA and apologies for the delayed response. Do you still face this issue? If so, we'd like to help you resolve it by getting some more information.

**Comment by T1MOXA** [comment]
Not anymore, I managed to remove the monitoring and put it back after some time, and now there is no problem.

**Comment by cakrit** [comment]
Ok, thanks.
