### ISSUE TITLE
[RFC] Split packaging

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#3969]
From what I see netdata is currently packaged in all-or-nothing model, but what if it wasn't? Would it somehow help with getting packages into official repositories?
I mean, if there was something like:

- `netdata` - metapackage with everything
- `netdata-core` - package with only core functionality (code in C and in bash)
- `netdata-python` - python plugin and modules, dependant on netdata-core
- `netdata-SOMETHING` - some other package with more functionality also dependant on netdata-core

I am trying to understand why it is so hard to ship netdata as a package from official repo and why after 2 years there is still no package for redhat distros.

This is a question mostly to package maintainers, so @svenstaro, @sanskritfritz, @candrews, @lhw, @FedericoCeratto, @willysr, @gslin please chime in and correct me when I'm wrong.

**Comment by candrews** [comment]
Gentoo uses use flags for that kind of functionality. And there are already use flags for net-analyzer/netdata: https://packages.gentoo.org/packages/net-analyzer/netdata Suggestions (and especially pull requests!) for further use flags are welcome.

**Comment by Ferroin** [comment]
Debian also has a split package, they have one package called `netdata`, which contains all the compiled code, and one called `netdata-data`, which contains all the architecture independent data files (the web UI, python/node/shell plugins, etc).  Such a split is really common in a lot of distros that have significant manpower and also provide multi-arch support (Debian does this quite regularly, and a lot of stuff on Fedora and SuSE is done similarly), and providing native support for it in the netdata build process would probably be of helpful for package maintainers.

On the note of the Gentoo package, the use flags there are mostly dependency triggers (IOW, set this if you want all the stuff needed by feature X to be installed) and don't prevent installation of the files (which is kind of nice, I've done some stuff that needed mysql on a couple of occasions, and it was helpful not to have to rebuild netdata just to include the mysql plugin to monitor things).

That said, as a user, I actually _like_ the fact that it's essentially all or nothing and there are almost no hard dependencies.  It means that I don't have to install dozens of packages to get everything I want, I don't have to pull in bunches of dependencies I don't care about (I don't use the node plugins, and I don't need node for anything else on my systems, so not having to install it is rather nice), I can get support for most things I'm not monitoring already by just installing the API's I already would be if I were using them, and when I'm developing plugins I don't have to go through half a dozen packages to make sure the environment looks like it will from an upstream build.

Looking at this from a developer perspective, I wouldn't say netdata is any more or less difficult to package than almost anything else using an autotools build system (so, not too bad, but not exactly trivial in most cases either).  I think the lack of a package for RHEL itself may be a political issue more than an engineering one, and lack of Fedora support is probably just fallout from that.

**Comment by paulfantom** [comment]
Since we already agreed on keeping go.d.plugin in a separate repo and maybe later extracting other external plugins into their respective repositories I am coming back to this issue.
I was thinking that we could reflect distributed nature of our repositories also in packaging. This way user would have a choice what to install. My idea is to create packages in a way so they align with following dependency graph: 
![deps](https://user-images.githubusercontent.com/3531758/51280688-9d10bf80-19e0-11e9-8b86-0b277416b407.png)

This way we have an easy installation of everything by using `netdata` metapackage while still allowing users some level of customizability.

**Comment by paulfantom** [comment]
@lhw maybe I could meet somehow with that team so we could figure it out together? I could give you more insight into what is planned in next weeks. I would suggest a video-conference call or IRC discussion or maybe a short in-person meeting at FOSDEM? :)

**Comment by FedericoCeratto** [comment]
We are on #debian-netdata on OFTC

**Comment by Ferroin** [comment]
FWIW, I like the idea of having the web fronted as an optional separate package.  It's not really needed if you don't care about the dashboard (for example, if you're dealing with tiny IoT devices that will only be streaming metrics to a central system).

**Comment by cakrit** [comment]
Gents, let's be a bit careful about a couple of things:
- We have 11 "internal plugins" that would probably need to part of the netdata-core, as @paulfantom calls it. They are not really part of the "daemon", but I can't see them split. Same for plugins.d, which is what python, go etc. need
- The fping and freeipmi plugins are a bit special, as they are "external plugins" that don't fall neatly into the other packages. Not sure what we should do with those. 
-  node.js may be on its way out, but we haven't planned when we'll be able to make it obsolete.
- We should always have an easy, single-step process for a default installation of that metapackage.

I like the idea of beign able to separate the web front end  and the idea of sample/default proxy configurations for apache and nginx.  

However, the way we package the solution doesn't necessarily need to be aligned to the repositories we have. I don't see a hard dependency here and splitting the code to multiple repos does have its disadvantages from both a user and a contributor perspective (just a silly example, I create an issue in one repo and it ends up being an issue with code in another repo). I'd rather focus the discussion on packaging and consider adding repositories only when there are really compelling reasons to do so.

**Comment by paulfantom** [comment]
> We have 11 "internal plugins" that would probably need to part of the netdata-core

No one is talking about those. First step is to extract "external" plugins.

> The fping and freeipmi plugins are a bit special, as they are "external plugins" that don't fall neatly into the other packages. Not sure what we should do with those.

As for now they are staying where they are. There is no benefit in separating them. There would be a benefit of separating freeipmi if we had a client-server communication model as then we could run it with different privileges.

> node.js may be on its way out, but we haven't planned when we'll be able to make it obsolete.

Only thing we need to deprecate node.js is to rewrite couple (2 or 3) modules into golang. Apart from that this is fairly easy to migrate it out of netdata/netdata repository into another one and do installation in the same way we are trying to do with go.d.plugin. It is even simpler as this is an interpreted language, so we just need to pack/unpack a couple of files into proper directories.
Same installation path can be adopted for python and bash plugins.

> sample/default proxy configurations for apache and nginx.

That's what documentation is for and not packaging. Unless we create `netdata-doc` package, but I don't see this happening any time soon.

> We should always have an easy, single-step process for a default installation of that metapackage.

That's what metapackages are for.

**Comment by Ferroin** [comment]
> As for now they are staying where they are. There is no benefit in separating them. There would be a benefit of separating freeipmi if we had a client-server communication model as then we could run it with different privileges.

I disagree.  I see three benefits to having both the freeipmi and the fping plugins separate:

* They won't be taking up space on systems where they are unneeded.  It's not a lot of space saved, but even a few hundred kB matters when you're dealing with systems with highly limited storage (think for example of some of the SBC's out there that only provide 4GB of space on an eMMC for storage).
* It will make securing systems that use Netdata a bit easier.  Less code equals easier auditing, and usually also a smaller attack surface.
* When we actually get to packaging them, we can have them actually depend on freeipmi and fping respectively without adding those as dependencies of the main package.  This will simplify things for users who want to use them.

**Comment by daniel-baumann** [comment]
I suggest looking at this:
https://salsa.debian.org/debian/netdata/blob/master/debian/control

We're doing netdata-core, netdata-core-no-sse (i386 only), netdata-web and netdata-plugins-{bash,nodejs,python}; netdata is a meta-package depending on netdata-core (or netdata-core-no-sse) and netdata-plugins-bash, the nodejs and python plugins are in recommends.

Regards,
Daniel
