### ISSUE TITLE
[Question] How to set up a master/slave connection via Unix sockets

### ISSUE THREAD

**Issue by sgsunder** [netdata/netdata#3971]
Hi,

The comments on [stream.conf](https://github.com/firehol/netdata/blob/master/conf.d/stream.conf) suggest that you can use Unix sockets to communicate between a master and slave.

My setup: I'm running this on a Debian server. I want to run a slave instance of netdata on bare metal in which metrics are collected, then forward this into a netdata Docker container running on the same machine, which serves the web frontend out to the public (through a reverse proxy).

Using a TCP socket doesn't seem to be viable. The containers themselves have dynamic IP addresses, and don't seem to have accessible hostnames that can be called from the parent OS. It seems like the only way to get the IP programatically is through parsing JSON from the `docker inspect` command.

If I use a Unix socket instead, then I can just bind mount the socket when the container is started without needing to know any IP addresses and maintain a secure connection without even worrying about `iptables` rules to hide ports. Something like `docker run -v /var/run/netdata.sock:/var/run/netdata.sock:ro ... firehol/netdata`

Problem is, I don't really understand how to go about this.

On my slave side config, I assume I would need to do something like: 

```
[slave]
      enabled = yes
      destination = unix://var/run/netdata.sock
      api key = <example>
      timeout seconds = 60
      default port = 19999
      buffer size bytes = 1048576
      reconnect delay seconds = 5
      initial clock resync iterations = 60
```

although I don't see any file called `/var/run/netdata.sock` being created when I restart the service, and `netstat -a -p --unix | grep -i netdata` returns nothing either.

And on the master side, I'm even more confused cause I don't know how to specify where to look for a socket file. Should it be in `allow from`?

**Comment by cakrit** [comment]
@paulfantom can you help with this?

**Comment by cakrit** [comment]
I did play a little bit with Unix sockets last month, I will try to do a setup between two VMs to see if I can help.

**Comment by cakrit** [comment]
I went through the OP again. The master doesn't initiate a connection with the slaves, so you have no problem whatsoever using normal TCP sockets. Read through the documentation, you'll see that master is only told which ip ranges to accept requests from. It's the slaves that need the master IP and port to work. 

I did do some more research though for the sockets (using Docker, not VMs as I said in the last comment). It looks like the following article would help you do precisely what you need: https://www.jujens.eu/posts/en/2017/Feb/15/docker-unix-socket/

**Comment by thiagoftsm** [comment]
Hi @sgsunder , I was reading a paper during this days from Redhat ( https://developers.redhat.com/blog/2019/05/30/accessing-unix-sockets-remotely-from-net/ ), where they were teaching how to access unix socket remotely, I could not test yet, but it looks like a solution for what you want.
