### ISSUE TITLE
Anchor to statsd metrics in URL

### ISSUE THREAD

**Issue by FedericoCeratto** [netdata/netdata#3983]
Netdata URLs can link to statsd gauges and counters using e.g. "#menu_statsd_submenu_counters" 

When many statsd metrics are present it would be useful to link to a specific metric e.g. "#menu_statsd_submenu_counters_x.y.z"

**Comment by ktsaou** [comment]
This is nice.
So you actually say to provide a way to support a URL pointing to a specific chart (any chart).

**Comment by ilyam8** [comment]
> So you actually say to provide a way to support a URL pointing to a specific chart (any chart).

This is implemented. An example: `http://pc:19999/#;chart=netdata.uptime`
