### ISSUE TITLE
Netdata looks in ../../../../ to get it's config

### ISSUE THREAD

**Issue by roedie** [netdata/netdata#3988]
On Debian Netdata looks at /usr/lib/x86_64-linux-gnu/netdata/plugins.d/../../../../etc/netdata/python.d/postgres.conf to get the config. As you can see this is one ../ too short and it ends up in /usr.

Since the idea is to find the config in /etc/netdata anyway why not use the direct path of /etc/netdata?

I've create PR #3987 for this.

**Comment by Wing924** [comment]
static build use `/opt/netdata/etc/netdata`...

**Comment by roedie** [comment]
Hmmm, not sure where this should be fixed then. I also created a bug with the Debian maintainer, so this patch could be used while packaging.

**Comment by ktsaou** [comment]
merged the fix!
