### ISSUE TITLE
mod_pagespeed monitoring

### ISSUE THREAD

**Issue by antons-** [netdata/netdata#3996]
I just recently installed mod_pagespeed on one of our servers - the first thing I did was check if netdata supported it (sadly not)! It would be awesome if we could feed mod_pagespeed stats into netdata.

https://developers.google.com/speed/pagespeed/module/
https://www.modpagespeed.com/

An example of the stats that mod_pagespeed provides https://www.modpagespeed.com/pagespeed_global_admin

**Comment by paulfantom** [comment]
@antons- one of good ways to really know how some software works is to write a monitoring plugin for it! :smile:

**Comment by cakrit** [comment]
Hi @antons- 	

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

Would you be willing/able to play this role?

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by antons-** [comment]
Hi @cakrit, unfortunately I do not fully understand the metrics in mod_pagespeed as there is so many of them, which was why I initially asked for a Netdata plugin - Netdata just seems makes things simple to digest.

**Comment by cakrit** [comment]
Closing due to no sponsor.
