### ISSUE TITLE
Send alerts to home assistant

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#3997]
[Home Assistant](https://www.home-assistant.io) already allows to install [netdata as a component](https://www.home-assistant.io/components/sensor.netdata/). Why not leverage this and allow users to send alerts/notifications via Home Assistant? It provides us with a lot of integration options (Alert on your TV? Spoken alert via Google Assistant or Amazon Alexa?)

**Comment by ktsaou** [comment]
Do you use it?

**Comment by paulfantom** [comment]
Home Assistant? Yes.

**Comment by ktsaou** [comment]
ok then, you just want to send alerts to it? I mean, netdata could provide more...

**Comment by paulfantom** [comment]
I don't see anything more that would be useful. Netdata already can be installed as a plugin and home assistant already have some monitoring integrated.

**Comment by ktsaou** [comment]
ok, then you just need to adapt alarm-notify.sh to do it.
There is a PR for alarm-notify.sh by @Ferroin to simplify it: https://github.com/firehol/netdata/pull/3960 - I am just afraid to merge it - we need to test it a bit more...

**Comment by cakrit** [comment]
@Ferroin any chance you can look into this after #3960 is merged?

**Comment by Ferroin** [comment]
Yes.
