### ISSUE TITLE
[Feature Request] Support for Yoctopuce USB sensor modules.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#4002]
[Yoctopuce](http://www.yoctopuce.com/) produces a line of very well made and rather inexpensive USB connected devices, including a wide range of sensor interfaces.  It would be awesome if Netdata supported reading and charting data from these.

------

This isn't as much a feature request as it is me saying I'm planning on working on this.  I don't currently have hardware I can test with, but I will be purchasing one of their meteorological sensor modules (and possibly an an ALS and thermocouple module too) in the next few weeks, which will give a reasonable base to test the basic code with.

My plan is to write up a python.d module that interfaces with their [VirtualHub](http://www.yoctopuce.com/EN/virtualhub.php) software, which is generally considered to be the correct way for generic projects to access their modules (because their native interfaces are not safe for concurrent access).

**Comment by Ferroin** [comment]
Marked as low priority because I so far seem to be the only person who wants this, and I've been having serious issues getting it tested properly.

**Comment by prologic** [comment]
@Ferroin This issue was created over 2 years ago. I don't see this getting done any time soon. Can we close it please or un-assign yourself and add "help wanted" and leave it up to the community?

**Comment by Ferroin** [comment]
Short term, yes, tagging as help-wanted.

Longer term, I do intend to get this working properly.

**Comment by ilyam8** [comment]
Closing in favor of #6158
