### ISSUE TITLE
Runfile installation doesn't fix earlier incorrect netdata init script

### ISSUE THREAD

**Issue by mikeweilgart** [netdata/netdata#4009]
The run script (https://github.com/firehol/binary-packages) should fix an out-of-date or incorrect init script as part of upgrading the netdata installation.

------

**Full detail, observed today on a RHEL 6 system:**

The command `service netdata status` returned an error.  Investigation revealed that the script `/etc/init.d/netdata` failed after attempting to source `/lib/lsb/init-functions`, which did not exist on that server.  However, the netdata binary was running (shown by `ps -ef | grep netdata`), and the version (shown by `/opt/netdata/bin/netdata -version`) showed the expected value:

    netdata 1.9.0-368-ged581b53_rolling

Another RHEL 6 host was checked, and `rpm -qf /lib/lsb/init-functions` showed that that file is provided by the `redhat-lsb` package, which was missing from the host with errors.  However, other RHEL 6 hosts were checked and found to be missing the `redhat-lsb` package but running `service netdata status` just fine.  On such servers the init script `/etc/init.d/netdata` was found to be sourcing `/etc/rc.d/init.d/functions` rather than the non-existent `/lib/lsb/init-functions`.

On the host with the error, the run script for netdata installation (which was [downloaded here](https://github.com/firehol/binary-packages/blob/master/netdata-v1.9.0-368-ged581b53-x86_64-20180203-052825.gz.run)) was re-run (after killing the netdata process).  Result: no change in the init script.

The init script was then deleted and the `/opt/netdata` directory was moved aside.  (This latter step was probably unnecessary.)  The run script was re-run.  This time, the init script contained the correct command to source `/etc/rc.d/init.d/functions`, and `service netdata status` worked correctly.

SUPPOSITION: I believe that an earlier version of netdata was installed on that host (probably incorrectly) before the runfile was ever run for the first time—hence the init script with the bad source command in it.

-------

**Additional notes:**

I know this is an older version of netdata (1.9.0-368), but as I couldn't find this issue mentioned anywhere in the bug tracker, I am reporting it.  If it's already been fixed (i.e. the latest netdata runfile installer will overwrite `/etc/init.d/netdata` as needed) then please close this issue and advise on which version first contains the fix.  :)

(Note: I couldn't find LSB in the changelog, but it looks like this host had its `/etc/init.d/netdata` as a copy of https://github.com/firehol/netdata/blob/master/system/netdata-lsb.in rather than as a copy of https://github.com/firehol/netdata/blob/master/system/netdata-init-d.in.)

**Comment by mikeweilgart** [comment]
Note: I have two or three other servers with the same issue that I have NOT fixed by reinstalling, in case there is any further data I could supply that would help in designing the fix for the installer.  Please let me know in the next week or so if there's anything I can provide from these hosts before I fix them—the sooner the better.  :)

**Comment by paulfantom** [comment]
We also moved everything to `/usr` to have the ability to update installed files which weren't modified by a user.

If this issue is still present please reopen it.

**Comment by atsaloli** [comment]
Hi @paulfantom   I work with @mikeweilgart  Thanks for your reply.  We see this issue with netdata 1.10.

I see 1.11 has the `/usr` change:

> stock config files should be in `/usr/lib/netdata/` #4182

I found https://github.com/netdata/netdata/releases which says 1.11.1 is the current version, and also this: release 1.11 of Netdata is the most secure Netdata so far. All users are advised to update to this version asap.

So I'm planning to update from 1.10 to 1.11.1 -- should we expect that to fix the issue we are seeing on some hosts where netdata doesn't start?  The error we get is:

```
/etc/init.d/netdata: line 64: status_of_proc: command not found
```
Will upgrading to 1.11.1 give us a working `/etc/init.d/netdata`?

Our users _love_ netdata!  :)  Congratulations on the project's success, keep it going!  :)

**Comment by paulfantom** [comment]
You can "watch" this repository for new releases. [Github has this feature now](https://help.github.com/articles/watching-and-unwatching-releases-for-a-repository/).

Current version sources `/etc/rc.d/init.d/functions` so there should be no problems after upgrade.

**Comment by cakrit** [comment]
We also have communication channels for announcements see [here](https://docs.netdata.cloud/#community).

**Comment by atsaloli** [comment]
Yay! Thanks @paulfantom and @cakrit 

I got all that.  Appreciate your help!  :)
