### ISSUE TITLE
[Question]Create Custom dashboard easypiechart that has dynamic max

### ISSUE THREAD

**Issue by CaptiveCreeper** [netdata/netdata#4033]
I am trying to make a easy pie chart gauge (like the ones in the system overview section of the normal netdata dashboard) for my custom dashboard with the data point disk_space._{name of drive}. I can get it to show either the used or available space on that drive but I cant figure out how to make the max be the total size of the drive.

Here is the html that I am using for the gauge. (With name of drive and netdata host url pulled out)
`      <div data-netdata="disk_space.{name of drive}"
                     data-host="{url of my netdata}"
                     data-title="Available disk space for /"
                     data-decimal-digits="3"
                     data-dimensions="avail"
                     data-chart-library="easypiechart"
                     data-easypiechart-max-value="used|avail"
                     data-width="9%"
                     data-before="0"
                     data-after="-720"
                     data-points="720"
                     data-common-units="system.io.mainhead"></div>`

**Comment by cakrit** [comment]
From what I've seen, I don't think that this is possible. Marking it as a feature request, until a web developer can look into it.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
