### ISSUE TITLE
Strange postgres module problem, kills LDAP auth

### ISSUE THREAD

**Issue by ntlug** [netdata/netdata#4040]
So, if we configure the postgresql module, all of our logins fail to the database:

    $ psql -U postgres

    psql: FATAL:  LDAP authentication failed for user "postgres"

When we disable the postgres module in netdata, we can restart the db and everything is ok again.  I've had this happen on two different postgresql servers so far.

Not sure if I'll be able to spend much time troubleshooting this... but in case others have seen this.

**Comment by paulfantom** [comment]
@anayrat can you help?

**Comment by anayrat** [comment]
Hello, it seems it is a pg_hba.conf rule issue. You have to configure your pg_hba.conf to accept netdata's connection.

**Comment by ntlug** [comment]
Perhaps so, but why does it prevent us from using postgres?  When it's configured and up, our postgres loses all ability to hit our LDAP server (causing our DBA much grief).

**Comment by anayrat** [comment]
Could you provide postgre's logs?

**Comment by ntlug** [comment]
There's not much in the logs.  Working, then suddenly:
    2018-08-09 15:51:07.512 GMT [20075]: [1-1] [trx_id=0] user=postgres,db=postgres,host=localhost LOG:  LDAP login failed for user "DOMAIN\postgres" on server "l
dap.domain.com": Can't contact LDAP server

And you get something similar from the command line when doing "psql -U postgres" as the postgres user.  Once we bounce postgres, the problem is resolved.  We're actively trying to recreate this.  But having difficulty.  Seems we see this on initial deploy of netdata (full compile including requistite rpms install and default postgres discovery because default isntall starts netdata automatically)  We're using the "curl" method of installation.

We've tried to recreate the scenario, but without success.  I've tried looking the rpm list of the requisites it installs (since we're not trying to reproduce that), but I don't see anything strange.

We know one way to make it happen (but possibly not always) and that is to deploy onto one our postgres db VMs with a 1st time netdata install.

I'll try to post more as we learn more.

**Comment by anayrat** [comment]
I dont see how it could be related to netdata. Did you try by specifying the ip address of ldap serveur instead of fqdn?

**Comment by ntlug** [comment]
You'd think netdata wouldn't cause this at all.  But since this has now happened 3 times to us (and once in production... I will not live that one down)....

It's hard to troubleshoot this since it seems to happen in cases  where netdata has never been on the host before.

**Comment by ktsaou** [comment]
@ntlug did you manage to solve this?

**Comment by ntlug** [comment]
Sadly, this is going to take a LOT of my time to try to determine what is going on, and I have other fires.  However, I am taking the problem seriously and we have put a moratorium on all netdata installs on our DB servers.

**Comment by ktsaou** [comment]
ok, I would love to know what causes this.
Do you know if this happens on a specific O/S version? It may be a python library or something supplied by the O/S.

Generally I am very keen to fix such issues, or at least work around them if the problem is not netdata, but until we have something more concrete I am not sure I can decide on the direction we should take.

**Comment by ktsaou** [comment]
I mark this as bug that needs reproduction, but we are actually waiting for you.
