### ISSUE TITLE
Organize netdata slaves on the my-netdata menu

### ISSUE THREAD

**Issue by finasfinas** [netdata/netdata#4042]
I've created a master slave configuration where the master is the also the registry and the slaves all stream to this master. I have three different infrastructures and would like to have a way of grouping machines belonging to those infrastructures together under one submenu for ease of management. Lets say I have 10 machines in the production infrastructure, 15 on development and 20 on testing. Right now they all appear bellow the registry server mixed together. is there a way to make them belong to "families" so that they apear together inside sub-menus, or at least sequentially on the main menu. the sub-menu option seems more sane, as let's say I have 200 machines, it would be easier to have them inside sub-menus or even sub-sub-menus.

is this possible?

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/3990

**Comment by ktsaou** [comment]
Let's discuss this on #3990 
I am closing this.
