### ISSUE TITLE
Monitor Speed/Duplex

### ISSUE THREAD

**Issue by animosity22** [netdata/netdata#4047]
I have a FreeBSD based router (pfSense) that occasionally grabs a link of 100 full instead of 1000 full. I'm going through and replacing the cable at some point.

Is there a spot in netdata to turn on capturing the speed / duplex of an interface?

**Comment by ktsaou** [comment]
We have added this information already:

![image](https://user-images.githubusercontent.com/2662304/48970784-21664800-f019-11e8-815b-d86373bbbc2b.png)

You can edit the files shown to setup your own alarms.

If you need more help, post here.
