### ISSUE TITLE
Docker Fire QoS for S905 on LibreElec Android Box

### ISSUE THREAD

**Issue by siliconhippy** [netdata/netdata#4050]
Hi !

Looks like a great job, exactly what I wanted !

1. Is there an Alpine or Debian ARM 64 base Docker for FireQoS?

2. Or is it possible to load FireQoS on a LibreElec distro (see below)?

So I have LibreElec-Kodi (https://libreelec.tv) running on my generic arm64v8A Amlogic S905x/w Android Box.

If install the pi-hole.net add-on via Docker Debian, it then gives me DNS, DHCP and nginx (in lieu of lighttpd from dnsmasq) server plus ad blocking.

So the only thing I am missing is QoS to make my Box a combo media player + home router.

*That's where FireQoS comes in !*

Unluckily LibreElec is a minimal OS (JeOS) that only runs KODI and can only have Docker (Debian or Alpine base) containers installed besides its add-ons via the LibreElec Kodi main Add-on interface:

https://libreelec.wiki/add-ons

But addons like system tools or Network Tools, from what I see above, only monitor: they can't give me QoS settings like simple Kodi box streaming priority over downloads/torrents by home PC/phones connected to the Box via LibreElec tether WiFi AP. 

Neither can I do anti bloat like LuCI cake-sqm as in OpenWrt.

Any insights are highly appreciated 👻👻👻

Cheers,
Shippy

**Comment by paulfantom** [comment]
Closing as this isn't related to netdata. Please go to https://github.com/firehol/firehol/wiki/FireQOS to get more information.
