### ISSUE TITLE
Create a custom plugin using pyhton and a new address

### ISSUE THREAD

**Issue by raven84** [netdata/netdata#4077]
Hi,

Saw that netdata can be useful to something I am doing.
I want to display my custom stats from a service I am developing.

1. I want to create a unique address like http://10.0.1.1:19999/my_unique_address
2. How do I configure this address to pick my stats?

Sorry if this is already mentioned somewhere, you can point me to the appropriate link if available..

Thanks

**Comment by raven84** [comment]
Guess I forgot to mention that I want to update/populate my stats via python.

**Comment by ktsaou** [comment]
This was a question. So, I am closing it.
If you need help, just post.
