### ISSUE TITLE
Disable specific Python plugins?

### ISSUE THREAD

**Issue by L1Cafe** [netdata/netdata#4079]
After searching the web for a while I couldn't find a way to disable Nginx, web_log and Postfix plugins. I already added to /etc/netdata/python.d.conf postfix:no, nginx:no and web_log:no, but the chart is still there, and alerts keep popping up.

**Comment by ktsaou** [comment]
Just tested this and it works. Is it possible that you have multiple versions of netdata installed at different directories?

**Comment by paulfantom** [comment]
And make sure you have valid yaml config.

**Comment by L1Cafe** [comment]
Thanks for responding! I definitely do not have multiple versions of Netdata. Just to be completely sure: is there any log I could check to see if Netdata is effectively disabling plugins? Any log that would output a "xyz plugin disabled: skipping", or something similar?

**Comment by ktsaou** [comment]
You can run the python.d.plugin by hand as explained here: https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins

It will not run disabled modules, even if you instruct it to run it on the command line.

**Comment by ktsaou** [comment]
This was a question.
So, I am closing it.
If you still need help, just post here.
