### ISSUE TITLE
Postqueue from lxc container

### ISSUE THREAD

**Issue by WoozyMasta** [netdata/netdata#4085]
When I try to get a postfix message queue from an lxc container, I get an error

```
python.d ERROR: postfix: local: _get_data() failed. Command: ['/usr/bin/lxc', 'exec', 'mail', '--', '/usr/sbin/postqueue', '-p']. Error: 'NoneType' object has no attribute '__getitem__'
```

To get the queue, I changed the command in the config `/etc/netdata/python.d/postfix.conf`
```
local:
  command: 'lxc exec mail -- /usr/sbin/postqueue -p'
```
How can properly parse the output of commands from the container?

**Comment by ilyam8** [comment]
Hey @WoozyMasta 

Please run `python.d.plugin` in debug mode

```
opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin postfix debug trace
```

**Comment by ilyam8** [comment]
edited

**Comment by orgoj** [comment]
Try: lxc-attach -n mail -- postqueue -p
