### ISSUE TITLE
Postgres plugin lock output incorrect

### ISSUE THREAD

**Issue by roedie** [netdata/netdata#4090]
While running the postgres plugin I noticed the out of the locks was incorrect. While running the query of the plugin as my netdata user by hand I get the output:

```
some_db | AccessExclusiveLock      |           2
some_db | AccessShareLock          |         167
some_db | RowExclusiveLock         |          18
some_db | ShareLock                |           1
some_db | ShareUpdateExclusiveLock |           3
```

But the output when running in debug mode is different:

```
BEGIN postgres_local.some_db_locks 0
SET 'some_db_ExclusiveLock' = 0
SET 'some_db_RowShareLock' = 0
SET 'some_db_SIReadLock' = 0
SET 'some_db_ShareUpdateExclusiveLock' = 3
SET 'some_db_AccessExclusiveLock' = 0
SET 'some_db_AccessShareLock' = 0
SET 'some_db_ShareRowExclusiveLock' = 0
SET 'some_db_ShareLock' = 0
SET 'some_db_RowExclusiveLock' = 0
END
````

Only the ShareUpdateExclusiveLock seems to be correct, All other values are (almost) always 0.

**Comment by ktsaou** [comment]
@l2isbad @facetoe please check this.

**Comment by ktsaou** [comment]
If you can reproduce this, please let me know to mark this as bug.

**Comment by anayrat** [comment]
I will look, maybe next week.

**Comment by roedie** [comment]
@anayrat Please let me know if you need any more info.

**Comment by anayrat** [comment]
Sorry, I forgot this issue. locks can be taken for a very short time, it is possible that value changes quickly. I looked at the code and I don't see how you can have different results between netdata and manually run the query. Did you run with the same user?

**Comment by roedie** [comment]
Yes, I've ran the query with the same user. At this moment the load on our platform is not high enough, but I can send you a screenshot of the netdata graph and from my munin graph so you can see the difference.

**Comment by ktsaou** [comment]
> I can send you a screenshot of the netdata graph and from my munin graph so you can see the difference.

Please do...

**Comment by anayrat** [comment]
I am waiting for the screenshot.

**Comment by roedie** [comment]
Sorry about that. It looked like it was somehow a bit fixed so I was investigating that. But no.. So, here are the screenshots.

<img width="1195" alt="screenshot 2018-11-30 at 13 22 14" src="https://user-images.githubusercontent.com/1014038/49289422-0590f500-f4a4-11e8-8510-8643b93113f1.png">
<img width="904" alt="screenshot 2018-11-30 at 13 22 24" src="https://user-images.githubusercontent.com/1014038/49289424-09bd1280-f4a4-11e8-9301-541028c49508.png">

**Comment by anayrat** [comment]
Thanks, I am pretty sure the issue is here : 
https://github.com/netdata/netdata/blob/376bd7de8f8a716e40fa4d922588afe926bb0191/collectors/python.d.plugin/postgres/postgres.chart.py#L706

But i don't kown how to fix it, it is pure python problem.

**Comment by anayrat** [comment]
The lock query return a table, and you have to read each row to populate chart : 
```
 database_name |        mode         | locks_count 
---------------+---------------------+-------------
 bench         | AccessExclusiveLock |           4
 bench         | AccessShareLock     |          10
```
It seems netdata only fetch one value and put 0 for other one.
If I change:
```python
 self.data[dimension_id] = row['locks_count'] if metric == row['mode'] else 1
```

I got one line with the good value, and all other got 1.

**Comment by ilyam8** [comment]
@anayrat 

try to change
https://github.com/netdata/netdata/blob/376bd7de8f8a716e40fa4d922588afe926bb0191/collectors/python.d.plugin/postgres/postgres.chart.py#L706

to

```python
if metric == row['mode']:
    self.data[dimension_id] = row['locks_count']
```

**Comment by ilyam8** [comment]
Ok, thats how it works right now

1. Zero all locks on every iteration
https://github.com/netdata/netdata/blob/376bd7de8f8a716e40fa4d922588afe926bb0191/collectors/python.d.plugin/postgres/postgres.chart.py#L676

2. Execute query

3. Update locks values with data from query

```python
        for row in cursor:
```

On clean install i have only this
```
# <class 'psycopg2.extras.DictRow'>
# ['database_name', 'mode', 'locks_count', ]
['postgres', 'AccessShareLock', 1L]
```

Then

```python
# metric = [
#        'ExclusiveLock',
#        'RowShareLock',
#        'SIReadLock',
#        'ShareUpdateExclusiveLock',
#        'AccessExclusiveLock',
#        'AccessShareLock',
#        'ShareRowExclusiveLock',
#        'ShareLock',
#       'RowExclusiveLock'
#   ],
#
for metric in metrics:
    self.data[dimension_id] = row['locks_count'] if metric == row['mode'] else 0
```

This is wrong, because it sets zero value for every lock except the one that is in current row (`['postgres', 'AccessShareLock', 1L]`)

That's why my code above should fix it. I may be missing something.

**Comment by ilyam8** [comment]
@roedie 

if you have time please try [this](https://github.com/netdata/netdata/issues/4090#issuecomment-443503022) too

**Comment by roedie** [comment]
@ilyam8 

I've just tested it and it seems to produce logical numbers now. It is only running for 10 minutes so I cannot compare it to my munin graphs yet, but it definitely looks promising.

**Comment by ilyam8** [comment]
@roedie ok keep me in the loop, i will do a PR if it works

**Comment by roedie** [comment]
@ilyam8 It's been running for some hours now. I've lined up my netdata graph with the munin graph and they look quite the same. Except for the granularity of course ;-)

I'd say you can merge the PR. Thanks!
