### ISSUE TITLE
Disabling pan and zoom syncing breaks chart history

### ISSUE THREAD

**Issue by Komic** [netdata/netdata#4091]
Chart history (zooming out, scrolling) seems to be broken if _Sync pan and zoom on all charts?_ is set to _Don't Sync_ (in my case for performance reasons). Running on master, https://github.com/firehol/netdata/commit/2087ce00f68a18376db7894e3a5d3938be88012a.

**Comment by ktsaou** [comment]
You are right. This is a bug.
Thank you for reporting it.

**Comment by Komic** [comment]
my pleasure, thanks for taking a look (:

**Comment by jacekkolasa** [comment]
It's fixed now, with new dashboard version
