### ISSUE TITLE
too many metrics in proxmox

### ISSUE THREAD

**Issue by papage** [netdata/netdata#4108]
Hi all,

I have installed netdata on a proxmox host. It reports that it collects 42K metrics, while on a typical VM I have about 2K-3K.
It seems that it produces metrics for my cores, interrupts, driver, card and something else...
Here is an example of :
netdata.cpu.cpu39_interrupts.i40e_enp94s0f2_TxRx_41_692
netdata.cpu.cpu39_interrupts.i40e_enp94s0f2_TxRx_42_693
netdata.cpu.cpu39_interrupts.i40e_enp94s0f2_TxRx_43_694
netdata.cpu.cpu39_interrupts.i40e_enp94s0f2_TxRx_44_695

I guess this is normal, but on the same time it might be too much for most use cases (too much info). So, would it be possible to aggregate to something more useful? 
I am mainly concerned because i am sending the data to influxdb without filtering.

Thanx,
Sp

**Comment by ktsaou** [comment]
We have fixed a number of bugs in interrupts parsing and also cleaned up a lot the generated metrics for interrupts.

So, I think your issue should have been fixed.
If it does not, please post here.
