### ISSUE TITLE
No Ceph metrics displayed

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#4114]
Hi,
I followed the [instructions](https://github.com/firehol/netdata/tree/master/python.d#ceph) and setup ceph plugin.

However after restarting netdata service there's no relevant metrics displayed although the service started w/o errors:
```
root@ld4257:~# service netdata status
● netdata.service - Real time performance monitoring
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-09-06 09:33:46 CEST; 2s ago
  Process: 408659 ExecStartPre=/bin/chown -R netdata:netdata /opt/netdata/var/cache/netdata (code=exited
  Process: 408650 ExecStartPre=/bin/mkdir -p /opt/netdata/var/cache/netdata (code=exited, status=0/SUCCE
 Main PID: 408667 (netdata)
    Tasks: 38 (limit: 8601)
   Memory: 506.6M
      CPU: 2.494s
   CGroup: /system.slice/netdata.service
           ├─408667 /opt/netdata/bin/srv/netdata -P /run/netdata/netdata.pid -D
           ├─408682 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
           ├─408697 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
           └─408700 /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1

Sep 06 09:33:46 ld4257 systemd[1]: Starting Real time performance monitoring...
Sep 06 09:33:46 ld4257 systemd[1]: Started Real time performance monitoring.
lines 1-17/17 (END)

```

Then I started to debug the plugin, and it looks like that no metrics are collected:
```
root@ld4257:~# su -s /bin/bash netdata
netdata@ld4257:/root$ /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace ceph
2018-09-06 09:32:45: python.d INFO: plugin: main: Using python 2
2018-09-06 09:32:45: python.d DEBUG: plugin: main: module load source: 'ceph' => [OK]
2018-09-06 09:32:45: python.d DEBUG: plugin: main: module load config: 'ceph' => [OK]
2018-09-06 09:32:45: python.d DEBUG: plugin: main: job initialization: 'ceph ceph' => ['OK']
2018-09-06 09:32:45: python.d DEBUG: plugin: main: module status: 'ceph' => [OK] (jobs: 1)

```
Actually I cannot stop debug but must kill the relevant process.

In the netdata error log are no entries pointing to the issue:
```
root@ld4257:~# tail -f /opt/netdata/var/log/netdata/error.log
2018-09-06 09:33:57: netdata INFO  : PLUGIN[cgroup] : Initializing file /opt/netdata/var/cache/netdata/cgroup_qemu_vm107_devsles12sp3btrfs.cpu_per_core/cpu10.db.
2018-09-06 09:33:57: netdata INFO  : PLUGIN[cgroup] : Initializing file /opt/netdata/var/cache/netdata/cgroup_qemu_vm107_devsles12sp3btrfs.cpu_per_core/cpu11.db.
2018-09-06 09:33:57: netdata INFO  : PLUGIN[cgroup] : Initializing file /opt/netdata/var/cache/netdata/cgroup_qemu_vm107_devsles12sp3btrfs.cpu_per_core/cpu12.db.
2018-09-06 09:33:57: netdata INFO  : PLUGIN[cgroup] : Initializing file /opt/netdata/var/cache/netdata/cgroup_qemu_vm107_devsles12sp3btrfs.cpu_per_core/cpu13.db.
2018-09-06 09:33:57: netdata INFO  : PLUGIN[cgroup] : Initializing file /opt/netdata/var/cache/netdata/cgroup_qemu_vm107_devsles12sp3btrfs.cpu_per_core/cpu14.db.
2018-09-06 09:33:57: netdata INFO  : PLUGIN[cgroup] : Initializing file /opt/netdata/var/cache/netdata/cgroup_qemu_vm107_devsles12sp3btrfs.cpu_per_core/cpu15.db.
2018-09-06 09:33:57: netdata INFO  : PLUGIN[cgroup] : Initializing file /opt/netdata/var/cache/netdata/cgroup_qemu_vm107_devsles12sp3btrfs.cpu_per_core/cpu16.db.
2018-09-06 09:33:57: netdata INFO  : PLUGIN[cgroup] : Initializing file /opt/netdata/var/cache/netdata/cgroup_qemu_vm107_devsles12sp3btrfs.cpu_per_core/cpu17.db.
2018-09-06 09:33:57: netdata INFO  : PLUGIN[cgroup] : Initializing file /opt/netdata/var/cache/netdata/cgroup_qemu_vm107_devsles12sp3btrfs.cpu_per_core/cpu18.db.
2018-09-06 09:33:57: netdata Too many logs (201 logs in 11 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 1189 seconds.
2018-09-06 09:40:56: alarm-notify.sh: INFO: sent email notification for: ld4257 net_fifo.ens4d1.10min_fifo_errors is WARNING to 'root'
2018-09-06 09:40:56: alarm-notify.sh: INFO: sent email notification for: ld4257 net_drops.ens4d1.inbound_packets_dropped is WARNING to 'root'
2018-09-06 09:40:56: alarm-notify.sh: INFO: sent email notification for: ld4257 net_fifo.bond0.10min_fifo_errors is WARNING to 'root'
2018-09-06 09:40:56: alarm-notify.sh: INFO: sent email notification for: ld4257 net_drops.bond0.inbound_packets_dropped is WARNING to 'root'

```
What's causing this issue?

THX

**Comment by ktsaou** [comment]
hm... from the following:

```
etdata@ld4257:/root$ /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace ceph
2018-09-06 09:32:45: python.d INFO: plugin: main: Using python 2
2018-09-06 09:32:45: python.d DEBUG: plugin: main: module load source: 'ceph' => [OK]
2018-09-06 09:32:45: python.d DEBUG: plugin: main: module load config: 'ceph' => [OK]
2018-09-06 09:32:45: python.d DEBUG: plugin: main: job initialization: 'ceph ceph' => ['OK']
2018-09-06 09:32:45: python.d DEBUG: plugin: main: module status: 'ceph' => [OK] (jobs: 1)
```

and the fact that it does not output any metrics and you have to kill it to stop it, I understand there is an issue with ceph communication.

@lets00 any ideas?

**Comment by lets00** [comment]
Hi @ktsaou ,
I will investigate it better. Maybe there is an issue with the ceph communication, but I need bring up a test environiment to see what is happen.

**Comment by 74cmonty** [comment]
If you need any data / information from my side please don't hesitate.
I'm running a 3-node cluster based on Proxmox VE (with Debian 9).

**Comment by lets00** [comment]
Well,
I brought up a ceph luminous environiment and install/configure the new version of netdata.
The ceph data is collected and show it below:
```
root@ceph-mon:~# /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace ceph > debug
2018-09-09 23:23:36: python.d INFO: plugin: main: Using python 2
2018-09-09 23:23:36: python.d DEBUG: plugin: main: module load source: 'ceph' => [OK]
2018-09-09 23:23:36: python.d DEBUG: plugin: main: module load config: 'ceph' => [OK]
2018-09-09 23:23:36: python.d DEBUG: plugin: main: job initialization: 'ceph local' => ['OK']
2018-09-09 23:23:36: python.d DEBUG: plugin: main: module status: 'ceph' => [OK] (jobs: 1)
2018-09-09 23:23:36: python.d INFO: ceph: local: check() => [OK]
2018-09-09 23:23:36: python.d DEBUG: ceph: local: create() => [OK] (charts: 14)
2018-09-09 23:23:36: python.d DEBUG: ceph: local: started, update frequency: 10, retries: 60
2018-09-09 23:23:36: python.d DEBUG: ceph: local: sleeping for 3.371166004 to reach frequency of 10 sec
2018-09-09 23:23:39: python.d DEBUG: ceph: local: update => [OK] (elapsed time: 10, retries left: 60)
```
and cat in file:
```
$ cat debug
CHART netdata.runtime_ceph_local '' 'Execution time for ceph_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 10
DIMENSION run_time 'run time' absolute 1 1

CHART ceph_local.osd_usage '' 'Ceph OSDs' 'KB' 'osd' 'ceph.osd_usage' line 60011 10 '' 'python.d.plugin' 'ceph'
DIMENSION 'osd.0' 'osd.0' absolute 1 1 ''
DIMENSION 'osd.1' 'osd.1' absolute 1 1 ''
DIMENSION 'osd.2' 'osd.2' absolute 1 1 ''
DIMENSION 'osd.3' 'osd.3' absolute 1 1 ''

BEGIN ceph_local.osd_usage 0
SET 'osd.0' = 133496
SET 'osd.1' = 113964
SET 'osd.2' = 113836
SET 'osd.3' = 133368
END

CHART ceph_local.general_usage '' 'Ceph General Space' 'KB' 'general' 'ceph.general_usage' stacked 60000 10 '' 'python.d.plugin' 'ceph'
DIMENSION 'general_available' 'avail' absolute 1 1024 ''
DIMENSION 'general_usage' 'used' absolute 1 1024 ''

BEGIN ceph_local.general_usage 0
SET 'general_available' = 37208936
SET 'general_usage' = 494664
END

CHART ceph_local.general_objects '' 'Ceph General Objects' 'objects' 'general' 'ceph.general_objects' area 60001 10 '' 'python.d.plugin' 'ceph'
DIMENSION 'general_objects' 'cluster' absolute 1 1 ''

BEGIN ceph_local.general_objects 0
SET 'general_objects' = 1
END
....
```
But, indeed, the graph does not appear in web view. I will investigate it better and see why graph does not appear anymore.

**Comment by ktsaou** [comment]
Thank you @lets00 !

**Comment by lets00** [comment]
@74cmonty ,
Are you try to set read permission on ceph key?
E.g:
```
# chmod 640 /etc/ceph/cep.client.admin.keyring
```
when I define this permission, the graph appear in web.

**Comment by lets00** [comment]
See #4102

**Comment by ktsaou** [comment]
Thank you @lets00 
I marked it as question.
Is there something we can do, a log to print, or something that could help the users find this out?

**Comment by 74cmonty** [comment]
Hello!
I confirm that I have modified permissions of _/etc/ceph/ceph.client.admin.keyring_ to 644 according to the instructions.
Furthermore I added netdata to group ceph.

However there is no graph available.

I you share some instructions I would continue with debugging.
Unfortunately I have not dumped the debug command _/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace ceph_ in a file for review... I will update here once this is available.

Independant of this I think it could make sense to create a dedicated keyring for netdata in ceph instead of using the admin keyring. I will evaluate this and update here, too.

THX

**Comment by ktsaou** [comment]
Just merged PR #4177.
Using this PR netdata prints the file missing or the file does not have permissions to use.

**Comment by ktsaou** [comment]
> Furthermore I added netdata to group ceph.

Do we need this to be done at `netdata-installer.sh`?

**Comment by lets00** [comment]
> Do we need this to be done at netdata-installer.sh?
This is done in installer/functions.sh

**Comment by ktsaou** [comment]
ok, thanks!
So, somehow this was not done for @74cmonty 
I understand the only way for this to be skipped by the installer, is to install netdata before ceph.
@74cmonty is that the case?

**Comment by 74cmonty** [comment]
Actually no!
I found netdata later after installation and configuration of multinode Proxmox VE cluster using Ceph was completed.
This means netdata was recently installed on the 3-node-cluster.

**Comment by ktsaou** [comment]
No it is ok. Keep going.
I'll check the installer to find out why user `netdata` was not added to group `ceph`.

**Comment by lets00** [comment]
Hi @ktsaou,
In my ceph luminous environment (ubuntu 17.04):
```
$ grep netdata /etc/group
adm:x:4:syslog,ubuntu,netdata
proxy:x:13:netdata
ceph:x:64045:netdata
netdata:x:999:
```
The user was added to ceph group. So I don't think that there is a bug in ```installer/functions.sh```.

@74cmonty, lets go some test to verify if there is a problem with your ceph environment (maybe, the ceph plugin does not reply metrics because your ceph key does not permission to access some informations about your cluster). First, execute the commands below:
```
$ sudo su -s /bin/bash netdata
$ ceph df --format json
$ ceph osd df --format json
$ ceph osd perf --format json
$ ceph osd pool stats --format json
```

If any command returns error, your ceph is with some configuration problem (user netdata does not correct access to ceph cli).

**Second test** (verify if key have correct permission to access ceph cluster):
```
$ sudo su -s /bin/bash netdata
$ python
>>> import rados, json
>>> cluster = rados.Rados(conffile='/etc/ceph/ceph.conf', conf=dict(keyring='/etc/ceph/ceph.client.admin.keyring'))
>>> cluster.connect()
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), '')[1])
```
This command must return some like (please, show us your output):

```
{u'pools': [{u'stats': {u'objects': 10, u'bytes_used': 1048576000, u'max_avail': 24173815808, u'percent_used': 1.43, u'kb_used': 1024000}, u'name': u'asdf', u'id': 4}], u'stats': {u'total_used_bytes': 7628685312, u'total_bytes': 85475639296, u'total_avail_bytes': 77846953984}}
```
After that, please execute this commands to verify the others output:
```
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), '')[1])
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1])
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'osd perf', 'format': 'json'}), '')[1])
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'osd pool stats', 'format': 'json'}), '')[1])
```
Each command must return a JSON with the ceph properties (osd, pool, etc). Please, show us your output.

Sorry for delay.

**Comment by 74cmonty** [comment]
Hi guys,
sorry for responding late... I had no chance to access the server in the past days. But now we can continue trouble-shooting this issue.

In the meantime I have updated netdata using /usr/src/netdata.git/netdata-updater.sh; this command finished on all servers belonging to the cluster.
However this is solving the issue.

So I will continue providing the output requested.
```
root@ld4257:~# ls -l /etc/ceph/
insgesamt 12
-rw-r----- 1 ceph ceph 159 Jul 19 11:53 ceph.client.admin.keyring
lrwxrwxrwx 1 root root  18 Jul 19 11:33 ceph.conf -> /etc/pve/ceph.conf
-rw-r----- 1 root root 633 Jul 20 13:44 ceph.conf.original
-rw-r--r-- 1 root root 158 Aug  8 17:51 rbdmap

root@ld4257:~# grep netdata /etc/group
adm:x:4:netdata
proxy:x:13:netdata
www-data:x:33:netdata
ceph:x:64045:netdata
netdata:x:999:

root@ld4257:~# sudo su -s /bin/bash netdata
netdata@ld4257:/root$ ceph df --format json
2018-09-24 16:30:16.116167 7fdca78ad700 -1 auth: unable to find a keyring on /etc/pve/priv/ceph.client.admin.keyring: (13) Permission denied
2018-09-24 16:30:16.116177 7fdca78ad700  0 librados: client.admin initialization error (13) Permission denied
[errno 13] error connecting to the cluster
netdata@ld4257:/root$ ceph osd df --format json
2018-09-24 16:31:06.766597 7f5fa7b97700 -1 auth: unable to find a keyring on /etc/pve/priv/ceph.client.admin.keyring: (13) Permission denied
2018-09-24 16:31:06.766610 7f5fa7b97700  0 librados: client.admin initialization error (13) Permission denied
[errno 13] error connecting to the cluster
netdata@ld4257:/root$ ceph osd perf --format json
2018-09-24 16:31:19.149579 7f78468f8700 -1 auth: unable to find a keyring on /etc/pve/priv/ceph.client.admin.keyring: (13) Permission denied
2018-09-24 16:31:19.149591 7f78468f8700  0 librados: client.admin initialization error (13) Permission denied
[errno 13] error connecting to the cluster
netdata@ld4257:/root$ ceph osd pool stats --format json
2018-09-24 16:31:37.426080 7f14c4761700 -1 auth: unable to find a keyring on /etc/pve/priv/ceph.client.admin.keyring: (13) Permission denied
2018-09-24 16:31:37.426087 7f14c4761700  0 librados: client.admin initialization error (13) Permission denied
[errno 13] error connecting to the cluster
```

This verification is clearly pointing to an issue with missing authorisation of user netdata.

**Comment by 74cmonty** [comment]
Would it make sense to create a dedicated ceph keyring for user netdata (according to [this](http://docs.ceph.com/docs/master/man/8/ceph-authtool/) docu) instead of using the admin keyring?

**Comment by lets00** [comment]
```
root@ld4257:~# grep netdata /etc/group
...
ceph:x:64045:netdata
...
```
Netdata user is added on ceph group. That is ok and there is no issue about missing authorization.
But, your client is using this key **/etc/pve/priv/ceph.client.admin.keyring**

```
netdata@ld4257:/root$ ceph df --format json
2018-09-24 16:30:16.116167 7fdca78ad700 -1 auth: unable to find a keyring on /etc/pve/priv/ceph.client.admin.keyring: (13) Permission denied
2018-09-24 16:30:16.116177 7fdca78ad700  0 librados: client.admin initialization error (13) Permission denied
```
Are you try to set read permission on ceph key? 
Please, run:
```
$ ls -larth /etc/pve/priv/ceph.client.admin.keyring
```
Verify if this key is in ceph group. If yes, please execute:
```
$ chmod 640 /etc/pve/priv/ceph.client.admin.keyring
```
If not, you need add this key to ceph group.
If this key did not have permission to access your ceph environment, you have use a key that can access information about your cluster (admin key, for example). 

But this is not a issue about netdata or ceph plugin.

**Comment by 74cmonty** [comment]
True, based on the current findings this is not an issue with netdata.

However, I can execute a few of the python commands:
```
netdata@ld4257:/root$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rados, json
>>> cluster = rados.Rados(conffile='/etc/ceph/ceph.conf', conf=dict(keyring='/etc/ceph/ceph.client.admin.keyring'))
>>> cluster.connect()
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), '')[1])
{u'pools': [{u'stats': {u'objects': 6205, u'bytes_used': 26006769700, u'max_avail': 22768049455104, u'percent_used': 0.11, u'kb_used': 25397237}, u'name': u'benchmark', u'id': 16}, {u'stats': {u'objects': 20299, u'bytes_used': 84786892836, u'max_avail': 3253423570944, u'percent_used': 2.54, u'kb_used': 82799701}, u'name': u'fio', u'id': 19}, {u'stats': {u'objects': 5985, u'bytes_used': 25082851364, u'max_avail': 3253423570944, u'percent_used': 0.77, u'kb_used': 24494973}, u'name': u'hddlocal-benchmark', u'id': 20}, {u'stats': {u'objects': 10191, u'bytes_used': 42220010714, u'max_avail': 3253423570944, u'percent_used': 1.28, u'kb_used': 41230480}, u'name': u'pve', u'id': 21}, {u'stats': {u'objects': 209, u'bytes_used': 785080356, u'max_avail': 3253423570944, u'percent_used': 0.02, u'kb_used': 766681}, u'name': u'iso', u'id': 22}, {u'stats': {u'objects': 0, u'bytes_used': 0, u'max_avail': 3253423570944, u'percent_used': 0.0, u'kb_used': 0}, u'name': u'backup', u'id': 24}], u'stats': {u'total_used_bytes': 370088951808, u'total_bytes': 55198724407296, u'total_avail_bytes': 54828635455488}}
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), '')[1])
{u'pools': [{u'stats': {u'objects': 6205, u'bytes_used': 26006769700, u'max_avail': 22768049455104, u'percent_used': 0.11, u'kb_used': 25397237}, u'name': u'benchmark', u'id': 16}, {u'stats': {u'objects': 20299, u'bytes_used': 84786892836, u'max_avail': 3253423570944, u'percent_used': 2.54, u'kb_used': 82799701}, u'name': u'fio', u'id': 19}, {u'stats': {u'objects': 5985, u'bytes_used': 25082851364, u'max_avail': 3253423570944, u'percent_used': 0.77, u'kb_used': 24494973}, u'name': u'hddlocal-benchmark', u'id': 20}, {u'stats': {u'objects': 10191, u'bytes_used': 42220010714, u'max_avail': 3253423570944, u'percent_used': 1.28, u'kb_used': 41230480}, u'name': u'pve', u'id': 21}, {u'stats': {u'objects': 209, u'bytes_used': 785080356, u'max_avail': 3253423570944, u'percent_used': 0.02, u'kb_used': 766681}, u'name': u'iso', u'id': 22}, {u'stats': {u'objects': 0, u'bytes_used': 0, u'max_avail': 3253423570944, u'percent_used': 0.0, u'kb_used': 0}, u'name': u'backup', u'id': 24}], u'stats': {u'total_used_bytes': 370088951808, u'total_bytes': 55198724407296, u'total_avail_bytes': 54828635455488}}
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'osd df', 'format': 'json'}), '')[1])
^C^C^C^CGetötet
```

As you can see I must kill any command related to osd... these commands are running endless.

Can you please advise why /etc/pve/priv/ceph.client.admin.keyring is used with user netdata?
Actually there are similar keyring files in different directories; I assume this is related to Proxmox VE.
```
root@ld4257:~# ls -larth /etc/pve/priv/ceph.client.admin.keyring
-rw------- 1 root www-data 63 Jul 19 11:53 /etc/pve/priv/ceph.client.admin.keyring
root@ld4257:~# ls -larth /etc/ceph/ceph.client.admin.keyring
-rw-r----- 1 ceph ceph 159 Jul 19 11:53 /etc/ceph/ceph.client.admin.keyring
root@ld4257:~# ceph-authtool -l /etc/pve/priv/ceph.client.admin.keyring
[client.admin]
        key = AQCxX1BbWuroJBAA970Lfj6RZlrwD/b5Pj1tCw==
root@ld4257:~# ceph-authtool -l /etc/ceph/ceph.client.admin.keyring
[client.admin]
        key = AQCxX1BbWuroJBAA970Lfj6RZlrwD/b5Pj1tCw==
        auid = 0
        caps mds = "allow"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"
```

However, I cannot modify any file in _/etc/pve/priv_; this is prohibited by Proxmox.

And what do you think of creating a dedicated keyring for netdata?

**Comment by lets00** [comment]
> As you can see I must kill any command related to osd... these commands are running endless.

Probally your key does not permission to access osd options. You can generate a new key with access.

> Actually there are similar keyring files in different directories; I assume this is related to Proxmox VE.

I assume that too.  But ceph plugin use the key that you pass on ceph.conf.

```
config_file: '/etc/ceph/ceph.conf'
keyring_file: '/etc/ceph/ceph.client.admin.keyring'
```

> And what do you think of creating a dedicated keyring for netdata?

You can create a new key with admin permission (to access osd, pool, etc) and add the correct permissions.

**Comment by 74cmonty** [comment]
OK.
I personally think it's a good idea to create a dedicated key for any application accessing Ceph.
Hereby I don't need to share the admin key with an application that probably does not need admin rights.

I also understand that this ceph plugin is taking the keyring based on the parameters defined in _/etc/ceph/ceph.conf_.
In this scenario this is a "trap" because Proxmox VE defines this in _/etc/ceph/ceph.conf_:
```
root@ld4257:/# more /etc/ceph/ceph.conf
[global]
         auth client required = cephx
         auth cluster required = cephx
         auth service required = cephx
         cluster network = 192.168.100.8/29
         fsid = fda2f219-7355-4c46-b300-xxxxxxxxxxxx
         keyring = /etc/pve/priv/$cluster.$name.keyring
         mon allow pool delete = true
         osd journal size = 5120
         osd pool default min size = 2
         osd pool default size = 3
         public network = 10.97.xxx.x/24

[osd]
         keyring = /var/lib/ceph/osd/ceph-$id/keyring
         osd crush update on start = false
         osd mkfs type = xfs
         osd mkfs options xfs = -f -i size=2048
         osd mount options xfs = noatime,largeio,inode64,swalloc
         osd journal size = 10240
         cluster_network = 192.168.100.8/29
         public_network = 10.97.xxx.x/24
         filestore_queue_max_ops = 500
         filestore_op_threads = 8
         filestore_max_sync_interval = 10
         filestore_wbthrottle_xfs_bytes_start_flusher = 1073741824
         osd_op_threads = 8
         osd_enable_op_tracker = False

```
This means the keyring is expected in _/etc/pve/priv/_, and I cannot modify any file stored in this directory (due to Proxmox VE mounting 
`/dev/fuse on /etc/pve type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)`)

Therefore I would propose that Netdata ceph plugin

- uses a dedicated keyring
- does not refer to /etc/ceph/ceph.conf

Actually I have created another keyring with this syntax:
ceph auth get-or-create client.netdata mon 'allow *' osd 'allow *' -o /etc/ceph/netdata.keyring

This is the verification of the newly created keyring:
```
root@ld4257:/# ceph-authtool -l /etc/ceph/netdata.keyring
[client.netdata]
        key = AQBOKKlbEWwPJRAAVR/kNYPs5zZVmv2HUtBF/w==
        caps mon = "allow *"
        caps osd = "allow *"

```
But this keyring is not working when validating with the python coding:
```
netdata@ld4257:/$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rados, json
>>> cluster = rados.Rados(conffile='/etc/ceph/ceph.conf', conf=dict(keyring='/etc/ceph/netdata.keyring'))
>>> cluster.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rados.pyx", line 884, in rados.Rados.connect (/mnt/npool/a.antreich/ceph/ceph-12.2.8/obj-x86_64-linux-gnu/src/pybind/rados/pyrex/rados.c:11620)
rados.InvalidArgumentError: [errno 22] error connecting to the cluster
>>>

```

**Comment by lets00** [comment]
Hi @74cmonty ,

> uses a dedicated keyring

You can create, but this is not necessary in many local (if you use proxmox with ceph, you need create a another key because the environment is adapted to work in this way). In fact, this step does not necessary in another environments (installing ceph using repository packages, or via source code, or via ceph-deploy, or via ceph-ansible). In some environment, its dangerous have 2 keys with admin permission.
The documentation does not limit you to need create a new key. But, if you need, you create it. Others plugins in others projects (e.g openstack monasca, telegraph) too use the admin key as default (but too does not limit only this option) 

>    does not refer to /etc/ceph/ceph.conf

Rados lib needs ceph.conf to obtain the monitors list (and others informations). All ceph client must be know what the monitors are and this information (this is how ceph works).

> But this keyring is not working when validating with the python coding:

Your new key is in ceph group? It haves read permission? Please confirm this.

**Comment by 74cmonty** [comment]
Shame on me... the keyring is not working because I didn't set the correct owner and permission.
After creating the keyring it is owned by root.

Now, let's focus on this Proxmox VE specific Ceph configuration:
1. In _/etc/ceph/ceph.conf_ the parameter keyring = /etc/pve/priv/$cluster.$name.keyring is set in section global.
2. Directory _/etc/pve/priv/_ is very restrictive defined by a FUSE mount: 
`/dev/fuse on /etc/pve type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)` 

In my opinion it **makes no sense** to use 2 different ceph configurations by copying the main config and modify the keyring-parameter in the copy. There should be only 1 version of ceph.conf!

This means any keyring used by Netdata must be located in _/etc/pve/priv_.
When I copy the keyring to this directory the permissions are set to 600 and ownership is root:www-data.

A potential solution would be to change file permissions to 640 and change file ownership to root:ceph.
How can I make this change with this FUSE mount?

I will ask Proxmox VE developers why they define a non-standard keyring parameter in _/etc/ceph/ceph.conf_.

**Comment by 74cmonty** [comment]
No, the metrics won't be collected because Ceph is expecting keyring in _/etc/pve/priv_ and I cannot modify any file in that directory. (This is why I said I'm caught in a trap.)

A potential solution would be to comment out parameter "keyring" in _/etc/ceph/ceph.conf_, however I don't know the impact on Proxmox VE + Ceph.

(Currently I consider the benefits of Proxmox VE + Ceph higher than this downside with Netdata. Therefore I will not build back the combination Proxmox VE + Ceph.)

Last question:
Which capabilities must be associated with the keyring for Netdata collecting all stats when creating a dedicated keyring?
I assume permission for MDS and MON is not required.

**Comment by ilyam8** [comment]
@74cmonty are there any problems we need to help with? Or can we close the issue?

**Comment by 74cmonty** [comment]
Hi,
I want to share with you the current status.
Netdata vv1.12.0-rc2-51-nightly is installed on a 3-node-cluster running Ceph.

Although the servers are identical with regards to software deployment and configuration, netdata does **not** show Ceph metrics on one node.
The other two nodes provide ceph cluster server statistics.

What is needed to analyse the issue on the specific node showing the failure?

THX

**Comment by ilyam8** [comment]
@74cmonty 

1. check error.log  - `grep ceph error.log`
2. python.d.plugin has debug mode, try it - `./python.d.plugin debug trace ceph` (as netdata user)

**Comment by 74cmonty** [comment]
```
netdata@ld4257:/usr/libexec/netdata/plugins.d$ ./python.d.plugin debug trace ceph
2019-01-23 15:47:35: python.d INFO: plugin: main: Using python 2
2019-01-23 15:47:35: python.d DEBUG: plugin: main: loading '/usr/local/etc/netdata/python.d.conf'
2019-01-23 15:47:35: python.d ERROR: plugin: main: cannot load '/usr/local/etc/netdata/python.d.conf': [Errno 2] No such file or directory: '/usr/local/etc/netdata/python.d.conf'. Will try stock version.
2019-01-23 15:47:35: python.d DEBUG: plugin: main: loading '/usr/local/lib/netdata/conf.d/python.d.conf'
2019-01-23 15:47:35: python.d ERROR: plugin: main: cannot load '/usr/local/lib/netdata/conf.d/python.d.conf': [Errno 2] No such file or directory: '/usr/local/lib/netdata/conf.d/python.d.conf'
2019-01-23 15:47:35: python.d DEBUG: plugin: main: module load source: 'ceph' => [OK]
2019-01-23 15:47:35: python.d DEBUG: plugin: main: loading '/usr/local/etc/netdata/python.d/ceph.conf'
2019-01-23 15:47:35: python.d ERROR: plugin: main: cannot load '/usr/local/etc/netdata/python.d/ceph.conf' : [Errno 2] No such file or directory: '/usr/local/etc/netdata/python.d/ceph.conf'. Will try stock version.
2019-01-23 15:47:35: python.d DEBUG: plugin: main: loading '/usr/local/lib/netdata/conf.d/python.d/ceph.conf'
2019-01-23 15:47:35: python.d ERROR: plugin: main: cannot load '/usr/local/lib/netdata/conf.d/python.d/ceph.conf': [Errno 2] No such file or directory: '/usr/local/lib/netdata/conf.d/python.d/ceph.conf'
2019-01-23 15:47:35: python.d DEBUG: plugin: main: job initialization: 'ceph ceph' => ['OK']
2019-01-23 15:47:35: python.d DEBUG: plugin: main: module status: 'ceph' => [OK] (jobs: 1)
2019-01-23 15:47:35: python.d ERROR: ceph: ceph: config_file and/or keyring_file is not defined
2019-01-23 15:47:35: python.d INFO: ceph: ceph: check() => [FAILED]
2019-01-23 15:47:35: python.d INFO: plugin: main: FINISHED

```

**Comment by ilyam8** [comment]
> 2019-01-23 15:54:06: python.d ERROR: ceph: ceph: config_file and/or keyring_file is not defined
2019-01-23 15:54:06: python.d INFO: ceph: ceph: check() => [FAILED]


https://github.com/netdata/netdata/blob/2c01d9f5165e6c0a37414bf53898f9027dd2b5c4/collectors/python.d.plugin/ceph/ceph.chart.py#L115-L121

https://github.com/netdata/netdata/blob/2c01d9f5165e6c0a37414bf53898f9027dd2b5c4/collectors/python.d.plugin/ceph/ceph.chart.py#L131-L133

**Comment by 74cmonty** [comment]
This is the content of _/usr/src/netdata.git/collectors/python.d.plugin/ceph/ceph.chart.py_:
```
class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.config_file = self.configuration.get('config_file')
        self.keyring_file = self.configuration.get('keyring_file')

    def check(self):
        """
        Checks module
        :return:
        """
        if not CEPH:
            self.error('rados module is needed to use ceph.chart.py')
            return False
        if not (self.config_file and self.keyring_file):
            self.error('config_file and/or keyring_file is not defined')
            return False

```

**Comment by ilyam8** [comment]
> 2019-01-23 15:54:06: python.d ERROR: ceph: ceph: config_file and/or keyring_file is not defined
2019-01-23 15:54:06: python.d INFO: ceph: ceph: check() => [FAILED]

check your configuration file, according error log and code you haven't set 'config_file' and 'keyring_file'

**Comment by 74cmonty** [comment]
True, the error message is pointing to Ceph config and keyfile.
However, the same error is reported on the server ld4465 where netdata is displaying Ceph metrics correctly.
Again, the faulty server ld4257 and the working server ld4465 are identical with regards to software stack, OS, etc.

The root cause for the error on ld4257 must be something different.
