### ISSUE TITLE
zfs charts appear, even when they are zero

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#4115]
Hello!
My monitor shows metrics for "ZFS filesystem" (see attached screenshot).
![2018-09-06_10-06-39](https://user-images.githubusercontent.com/12523591/45144065-56eb5a00-b1bd-11e8-8da4-ee808630c4dc.png)

However there's no ZFS filesystem installed on this server.

Maybe this issue is related to [this](https://github.com/firehol/netdata/issues/4114)?

THX

**Comment by Ferroin** [comment]
Do you have any ZFS kernel modules loaded?  Even if you have no ZFS storage pools, the kernel modules still expose some global metrics which Netdata tracks.

**Comment by 74cmonty** [comment]
True.
On this server ZFS kernel modules are loaded (on other servers not).
```
root@ld4257:~# lsmod | grep zfs
zfs                  3448832  0
zunicode              331776  1 zfs
zavl                   16384  1 zfs
icp                   258048  1 zfs
zcommon                69632  1 zfs
znvpair                77824  2 zcommon,zfs
spl                   106496  4 znvpair,zcommon,zfs,icp

```

**Comment by Ferroin** [comment]
@ktsaou This sounds to me like a potential area for improvement.  Most of the other FS or block related stuff doesn't show up if it's not actually in-use, so it would make sense for ZFS stats to behave the same way if there are no zpools on the system.

**Comment by ktsaou** [comment]
ZFS should follow the same principle netdata follows for everything. If the collected values are zero, then nothing should be done.

I see in the code, that it renders charts unconditionally. So, it is a bug and should be fixed.
