### ISSUE TITLE
apt-get packages installer failed

### ISSUE THREAD

**Issue by celliott113** [netdata/netdata#4118]
The package installer failed with the following information.

This is what it says:

celliott@hclus1-dev1-satx-us28:~$ sudo apt install netdata
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package netdata
celliott@hclus1-dev1-satx-us28:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
celliott@hclus1-dev1-satx-us28:~$

please paste your screen here

![image](https://user-images.githubusercontent.com/20377983/45157598-3b755480-b1a7-11e8-9274-be1ef0edcea4.png)

**Comment by ktsaou** [comment]
Hi,

most probably you need to enable the universe repository, by adding the following to `/etc/apt/source.lst`:

```
deb http://archive.ubuntu.com/ubuntu/ bionic universe
deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe
```

btw, the netdata version they install is 1.9, which is quite old.
It would be probably better to install the latest version with this:

```sh
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

**Comment by ktsaou** [comment]
We are working on providing our own packages.
So, I think we can close this.
