### ISSUE TITLE
No netdata-updater.sh in cron.daily after installing with kickstart-static64.sh

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#4122]
Hi,
I have successfully installed netdata on different Linux (SLES 12, Debian 9) with _kickstart-static64.sh_.

However, there's no file _netdata-updater.sh_ to update this installation.

Question:
How should I update netdata when installing with _kickstart-static64.sh_?

**Comment by ktsaou** [comment]
You are right, this is missing.

> How should I update netdata when installing with kickstart-static64.sh?

Running `kickstart-static64.sh` again will update your installation. The only problem we have not supplied an updater, is that the daily snapshot of the static build, is updated even when there is nothing new to compile.

So, this is a bug.

**Comment by ktsaou** [comment]
I edited my response above, so read it on github.

**Comment by Ferroin** [comment]
Hmm...

Not quite sure from looking at the build system, but does Netdata support reproducible builds?  If so, then one possibility is to update the build system such that if the code does not change, the hash of the static build does not change, and then the install can store the hash of the build it's installing somewhere, and the updater can compare the two hashes (if they match, there's no need to update).

**Comment by ktsaou** [comment]
This one builds the latest netdata: https://github.com/firehol/binary-packages/blob/master/build-latest.sh
It is just a daily cron job. Can you adapt it to not rebuild if the tag is the same?

If we fix that, we can then provide an updater for the static build too.

**Comment by cakrit** [comment]
I looked at this, it should be a couple of lines only. I'll pick it up as soon as I get my environment straightened out.

**Comment by jghaanstra** [comment]
Is there any news on this or at least a work around to solve this bug? I installed Netdata with the kickstart-static64.sh script on my CentOS7 VPS and it installed fine in /opt/netdata/ but there is no netdata-updater.sh in either /etc/cron.daily/  or /etc/periodic/ or even somewhere in the Netdata install directory as far as I can tell.

Of course manually running kickstart-static64.sh will update the install but I would like to have auto-updates.

**Comment by cakrit** [comment]
Apologies @jghaanstra, we've been very busy with the new binary distributions. We'll get to it soon.

**Comment by paulkatsoulakis** [comment]
Hi @jghaanstra would you mind sharing why you chose static64 instead of the normal kickstart.sh install? CentOS-7 is fully supported from all installation methods

I 'll be taking a look at the issue though regardless of the above

**Comment by jghaanstra** [comment]
I followed instructions from my hosting company which contains the command for kickstart-static64.sh. Did not really think about it at the time of installing.

Instructions can be found here: https://community.time4vps.com/discussion/352/netdata-get-ready-with-server-monitoring

**Comment by paulkatsoulakis** [comment]
Hi @jghaanstra, just to get you started, i would recommend to follow [Netdata's instructions](https://docs.netdata.cloud/packaging/installer/#one-line-installation) for installing netdata on a server.

We are in the process of documenting in detail our distribution support matrix too, so that our users can tell what are netdata's capabilities per distribution.  I already contacted the author of the above article, so that we get that content aligned with our latest practices too.

Now regarding the static64 installer, we still do need to have a way to keep this up to date.
I 'll keep this issue as development issue to provide auto-update on static64 installer

**Comment by jghaanstra** [comment]
Ok, thanx for the info. Can I just run the default installer to overwrite my current install or are there more steps to take to continue with the default installer method?

**Comment by paulkatsoulakis** [comment]
> Ok, thanx for the info. Can I just run the default installer to overwrite my current install or are there more steps to take to continue with the default installer method?

The clean approach is to first remove the static64 version (you can keep any configs you had done), then run the one-liner kickstart.sh and re-instate your customised configs (if any) on the new paths.

**Comment by jghaanstra** [comment]
Ok, but what would be the correct approach for removing the static64 version. I have not looked at the script what it does exactly but is it as simple as removing the installation directory or do I also have to do other stuff like remove the netdata user and user group?

**Comment by paulkatsoulakis** [comment]
you will find the respective uninstaller `/opt/netdata/usr/libexec/netdata-uninstaller.sh` and you can use that. It will attempt to clean everything up
