### ISSUE TITLE
allow dedicated port for streaming

### ISSUE THREAD

**Issue by xxorax** [netdata/netdata#4126]
If you are using the replication feature, the slaves->master communication use an HTTP STREAM method (see https://github.com/firehol/netdata/issues/3802, which is not an acceptable HTTP method). This way Nginx (and probably others HTTP proxies) cannot handle it.

Nginx return a 400 Bad Request error for every STREAM requests.

Related issues : https://github.com/firehol/netdata/issues/3311 https://github.com/firehol/netdata/issues/2231

My goal is to restrict the Netdata frontend only, because the slave->master communication is already restrcited by the API key. To secure netdata frontend, you need Nginx, and the [actual documentation](https://github.com/firehol/netdata/wiki/Running-behind-nginx) does not handle communications with slaves.

So I do not see any possibility to do it without putting everything behind firewall.

Note that the communication works using the stream module of Nginx, here an example:
```
stream {
        server {
                listen 1.2.3.4:81;
                proxy_pass 10.0.0.1:20001;
        }
}
```
But in this case, you cannot restrict the front only (because you cannot apply any HTTP function in the stream{} context).

The best way I see to fix it is to use an other port for the slave communication only.

Thanks

**Comment by ktsaou** [comment]
Yes, this is needed to make our lives easier.
However, keep in mind you can filter by IP at `netdata.conf`:

```
[web]
        allow streaming from = *
```

You can also filter by IP per API key in `stream.conf`:

```
[API_KEY] 
   allow from = *
```

Generally, netdata provides `allow from` config options for many things (at the `[web]` section of `netdata.conf`), so you should be able to allow what you need, without a firewall.

For example, if you want port 19999 to be accessible by your nginx and your slaves only, you could use something like this in `netdata.conf`:

```
[web]
   allow connections from = localhost 10.*
   allow streaming from = 10.*
```

I assumed nginx is at `localhost` and all your slaves at `10.*`. With this config, any other connection on the netdata port will just be closed immediately and nginx will not be allowed to stream metrics.

**Comment by xxorax** [comment]
I don't want to restrict the slaves by IP.

Is it possible to restrict by IP the netdata frontend only ?

It could be a workaround, we could allow only the IP of Nginx to connect to the frontend (and the slaves will connect to netdata directly).

**Comment by cakrit** [comment]
This was actually resolved with @ktsaou's answer.
