### ISSUE TITLE
httpcheck support for HTTP methods  (e.g. GET, OPTIONS, HEAD, etc...)

### ISSUE THREAD

**Issue by Ryuzavi** [netdata/netdata#4127]
Hey

I'm currently evaluating Netstat for monitoring on our systems and have been quite impressed so far.  

We're interested in the new httpcheck plugin in paticular.  Is there any way to specify the http method it uses when making the call?  We typically used HEAD & OPTIONS instead of GET where possible.

Cheers,
R.

**Comment by ccremer** [comment]
Currently, netdata does not support changing the method, the `get` method is hardcoded, see here:
https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/FrameworkServices/UrlService.py#L106-L121
While other headers are possible, the method is an exception as of now.
Maybe @l2isbad is willing to extend the UrlService so it can be configured with other methods. Should be easy enough IMO.

**Comment by Ryuzavi** [comment]
Ah cool.  No rush or anything, was more just curious.  

We were specifically looking at it to do these checks and export them out to Prometheus but we'd also want to add more labels to the metrics so we're continuing to look elsewhere.  Great software though!

**Comment by l2isbad** [comment]
> Maybe @l2isbad is willing to extend the UrlService so it can be configured with other methods.

Sure :+1:
