### ISSUE TITLE
SpigotMC Chart won't show

### ISSUE THREAD

**Issue by alsoGAMER** [netdata/netdata#4131]
I don't know why but spigotmc chart won't show on netdata's dashboard..
Here screenshot of dashboard, configuration of spigotmc server and chart, also the log of the spigot and netdata server.

![screenshot_2018-09-07 get control of your linux servers simple effective awesome](https://user-images.githubusercontent.com/35269770/45239030-1f2b0200-b2e4-11e8-9281-5366a3286988.png)
[error.log](https://github.com/firehol/netdata/files/2362254/error.log)
[latest.log](https://github.com/firehol/netdata/files/2362255/latest.log)
[config file.zip](https://github.com/firehol/netdata/files/2362259/config.file.zip)

**Comment by Komic** [comment]
`enable-query` needs to be set to `true` (that's a server.properties setting). Restart Spigot then netdata after that.

**Comment by Ferroin** [comment]
Based on the config, everything looks correct to me.  The error log indicates that the module's check method failed, which means that it could not connect for some reason, but the usual reasons (mismatched password, port, or hostname, or `rcon-enable` being false), so I'm not quite sure exactly what is going on here.  I'm going to look into throwing together a version of the module with better debugging info so we can hopefully figure out exactly why this is failing.

In the meantime, feel free to try @Komic's suggestion, though I would be surprised if it works (we don't use the GameSpy4 interface for querying the server, so if it does fix things, that means that the meaning of that option has changed and the Minecraft documentation needs updated).

**Comment by Komic** [comment]
Oh my bad! I thought 25575 was the query port for some reason, please ignore my previous comment. @alsoGAMER, did you make sure to edit `/etc/netdata/python.d/spigotmc.conf` properly?

**Comment by Ferroin** [comment]
#4148 adds some extra logging to the spigotmc module that should hopefully help track down exactly what is wrong here (at minimum, it will tell us if it's a socket error or a protocol error).

@alsoGAMER If you want to test with the updated module without having to go through installing a test build of Netdata, you can fetch the module file with the changes from [here](https://raw.githubusercontent.com/Ferroin/netdata/spigotmc-extra-debugging/python.d/spigotmc.chart.py) and just drop it in `/usr/libexec/netdta/python.d` and restart netdata (and when you're done checking, you can revert it by just updating or reinstalling netdata however you normally would).

**Comment by alsoGAMER** [comment]
And nothing...
![2018-09-11-084615_1331x616_scrot](https://user-images.githubusercontent.com/35269770/45343315-d2278400-b5a0-11e8-9d81-c0105b7b3b50.png)
![screenshot_2018-09-11 get control of your linux servers simple effective awesome](https://user-images.githubusercontent.com/35269770/45343317-d2278400-b5a0-11e8-9cc9-7fc2d98bb2e2.png)
[error.log](https://github.com/firehol/netdata/files/2369674/error.log)
[spigotmc.conf.zip](https://github.com/firehol/netdata/files/2369679/spigotmc.conf.zip)

**Comment by alsoGAMER** [comment]
`[10:05:07 INFO]: This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

`[10:05:43 INFO]: TPS from last 1m, 5m, 15m: 19.91, 19.97, 19.99`

user command doesn't work, i've used online that is the same thing, here the output
```
[10:06:46 INFO]: CONSOLE issued server command: /online 
[10:06:46 INFO]: There are 0 players online on a maximum of 50.
```
additionally, here the output of plugins command
`[10:09:04 INFO]: Plugins (15): CoreProtect, LuckPerms, SkinsRestorer, eZProtector, MaxBans, Essentials, EssentialsGeoIP, PlaceholderAPI, EssentialsChat, LabyModAPI, StaffPlus, EssentialsSpawn, ProtocolLib, NoCheatPlus, AuthMe`

**Comment by Ferroin** [comment]
> user command doesn't work, i've used online that is the same thing, here the output

I think this  what the issue is.  Could you post the error message you get when you try to run the `users` command?  The module is choking on that error message, and the error handling isn't as robust as it should have been in this case.  I'm going to try and update things so it works with the `online` command too (and just auto-detects whether to use that or `users`), but it may take a while.

**Comment by Ferroin** [comment]
OK, just updated #4148 to properly catch and report errors parsing the output of the console commands the module is calling.  If you can test that and look for 'Unable to process TPS values.' and/or 'Unable to process user counts.' in the error logs, that should tell us for certain whether it's a parsing issue or not.

**Comment by alsoGAMER** [comment]
> Just realized, I meant to say `list`, not `users`. The `list` command _should_ work, but the formatting may be off and causing this issue.

```
[17:29:24 INFO]: CONSOLE issued server command: /list 
[17:29:24 INFO]: There are 0 players online on a maximum of 50.
```

**Comment by alsoGAMER** [comment]
>look for 'Unable to process TPS values.' and/or 'Unable to process user counts.'
Search string not found
[error.log](https://github.com/firehol/netdata/files/2375890/error.log)

**Comment by Ferroin** [comment]
Sorry about the lack of response @alsoGAMER.  I'm going to be setting up a new Minecraft server at some point today so I can hopefully reproduce this issues you're seeing and get this fixed.

**Comment by alsoGAMER** [comment]
yes @cakrit of course is it

**Comment by cakrit** [comment]
Thanks @alsoGAMER 
@Ferroin, @l2isbad could you please see if you can help? This is a bug.

**Comment by Ferroin** [comment]
@alsoGAMER Sorry about not getting back with you on this, I got sidetracked by something else, and the issue got lost in the shuffle.  I never did get around to actually trying to reproduce it, so I'll get on attempting to do so ASAP.

**Comment by Ferroin** [comment]
@alsoGAMER Sorry, again, about not staying on top of this.  I finally got around to trying to reproduce this over the holidays, and was unable to get it to reproduce.  At this point, I'm unfortunately stumped.

Between this and some of the other issues that have come up with the modules I've written, I'm starting to suspect my code is doing _something_ wrong with the Netdata API's, but for the life of me I can't figure out what.

**Comment by ilyam8** [comment]
@alsoGAMER 	have you resolved the issue?

**Comment by alsoGAMER** [comment]
Can't check right now

**Comment by ilyam8** [comment]
in the [error.log](https://github.com/netdata/netdata/issues/4131#issuecomment-420168405) i see

```
2018-09-11 08:55:37: python.d ERROR: spigotmc: spigotmc: update() unhandled exception: list index out of range
2018-09-11 08:55:42: python.d ERROR: spigotmc: spigotmc: update() unhandled exception: list index out of range
2018-09-11 08:55:47: python.d ERROR: spigotmc: spigotmc: update() unhandled exception: list index out of range
2018-09-11 08:56:04: python.d ERROR: spigotmc: spigotmc: update() unhandled exception: list index out of range
```

please run python.d.plugin in debug mode with trace flag

```
./python.d.plugin spigotmc debug trace
```

**Comment by alsoGAMER** [comment]
Ok guys, i've good news.. i've tried to run a spigotmc server on my raspberry pi3 with netdata and now seems it work correctly

netdata version is v1.12.1-10-nightly
![image](https://user-images.githubusercontent.com/35269770/53351964-44f3a400-3922-11e9-90b7-34f5016ade2b.png)

![image](https://user-images.githubusercontent.com/35269770/53351987-5046cf80-3922-11e9-8aa2-84064abe4066.png)

**Comment by alsoGAMER** [comment]
Btw i can't test on the "mctime" server cause is now a production server and i can't make random stuff

**Comment by ilyam8** [comment]
@Ferroin please take a look 
https://github.com/netdata/netdata/issues/4131#issuecomment-467054006

**Comment by Ferroin** [comment]
I just realized I (somehow) completely missed https://github.com/netdata/netdata/issues/4131#issuecomment-420692108 this whole time.  It looks like something (not sure if it's a plugin for the MC server, or a change in MC itself) changed the format of the `list` console command, which in turn broke the rather fragile parsing being done by this module.  I'll look into finding a way to sanely parse both this new format and the old one mentioned in a comment in the code itself (and add `IndexError` to the stuff being caught, I somehow forgot it when I created #4148).

**Comment by Ferroin** [comment]
@alsoGAMER I've just opened a PR that should (hopefully) fix this finally at #5507.  I unfortunately can't test it myself, but if you could verify that charts show up properly with it, that would be good.  Even testing on the Pi you set up to re-check this bug would be useful, because it's a complete change to the parsing code, and I'd like to make sure it doesn't break on systems that already work with the existing code.

**Comment by ilyam8** [comment]
@alsoGAMER 	if you have time please test, this is an old issue, i would like to have it fixed

**Comment by alsoGAMER** [comment]
I'll try today

**Comment by elfhack** [comment]
This is closed, so I don't know if someone will notice, but this chart now seems to require python3, which is not used on the netdata docker images. Furthermore, I still get the Unable to process errors after remove the re.A calls
