### ISSUE TITLE
Include tests in CI pipeline

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4133]
List of things which could be executed in CI pipeline:

- [ ] cppcheck.sh
- [ ] everything from `tests` directory
- [ ] linters

**Comment by ktsaou** [comment]
nice.
netdata daemon also has some unit tests for its core. We should provide a simple command line to run them all.

**Comment by ktsaou** [comment]
If I recall correctly, several node.js plugins also have tests.

**Comment by simonnagl** [comment]
If I recall correctly, there was a PR including some javascript tests. I am not sure if it was merged.
