### ISSUE TITLE
sensors.chart.py ignores fans running at 0 RPM when netdata was started

### ISSUE THREAD

**Issue by cobrafast** [netdata/netdata#4158]
I know this is is somewhat by design to remove unused fan readings from the graph, but my fans are designed to stop when all temperatures are low enough and there is no real need for them to run, so depending on when I (re)start netdata I am missing some or all fans from my graphs and they don't come back once they spin up again.

https://github.com/firehol/netdata/blob/master/charts.d/sensors.chart.sh#L70 seems to be the culprit.

Maybe there could be an option to always include zero-RPM fans anyways?

**Comment by cobrafast** [comment]
Turns out it's actually the python script, but I'm having trouble modifying it to do what I want.

**Comment by paulfantom** [comment]
@cobrafast I think that if you remove those two lines you will get 0 RPM readings in netdata (also other readings with 0 value will be present):
https://github.com/firehol/netdata/blob/ce47945b460ad324a67f968a769b5fd99f7d3742/python.d/sensors.chart.py#L114-L115

**Comment by paulfantom** [comment]
However changing those lines to sth like:
```py
if vals[0] == 0 and feature.type != 1:
    continue
```
will affect only fan readings.

**Comment by paulfantom** [comment]
I am not sure as I don't exactly remember that, but it might work by changing those lines:
https://github.com/firehol/netdata/blob/ce47945b460ad324a67f968a769b5fd99f7d3742/python.d/sensors.chart.py#L114-L115

into:
```py
if vals[0] == 0 and feature.type !=1:
    continue
```

Worth a shot, but I cannot guarantee anything.

**Comment by cobrafast** [comment]
@paulfantom Thanks I think I've got it together now.

**Comment by ktsaou** [comment]
@l2isbad 	I think I have seen this on my laptop too.
On boot, netdata does not provide metrics about fans.
But if netdata is restarted once the machine completes booting, fans are collected and reported.

So, I am marking this as a bug.
