### ISSUE TITLE
Lint python code (PEP8 standard)

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4167]
Lint following files:
- [x] plugins.d/python.d.plugin
- [x] python.d/python_modules/base.py
- [x] python.d/python_modules/base/*.py
- [x] python.d/[a-c]*.py
- [x] python.d/[d-h]*.py
- [x] python.d/[i-l]*.py
- [x] python.d/m*.py
- [x] python.d/[n-o]*.py
- [x] python.d/[p-r]*.py
- [x] python.d/[s-z]*.py

**Comment by Ferroin** [comment]
How picky do we want to be about line lengths?  The `ORDER` and `CHARTS[*]['options']` lines quite often end up being very long (they appear to account for a vast majority of the line-length violations of PEP 8 in our code), but we have conventionally represented them as single-line statements (for logical grouping reasons I assume).

**Comment by Ferroin** [comment]
And, actually, on further inspection, line length appears to account for a decent percentage of where we deviate from PEP 8.

**Comment by paulfantom** [comment]
maybe 120 characters?

**Comment by Ferroin** [comment]
For _just_ the top-level stuff in python.d, that brings us down to 25 lines that need reformatted compared to a few hundred for 79 character lines.

Alternatively, we could just convert the two big offenders (`ORDER` and `CHARTS[*]['options']`) to being multi-line in all-places, and eliminate a vast majority of the excessively long lines there.  The question then would become whether we just want minimal splitting to get within whatever limit, or one-item-per-line.  Pulling an example from `dnsdist.chart.py` (the current worst line in our whole Python codebase), that would be asking about converting:

    ORDER = ['queries', 'queries_dropped', 'packets_dropped', 'answers', 'backend_responses', 'backend_commerrors', 'backend_errors', 'cache', 'servercpu', 'servermem', 'query_latency', 'query_latency_avg']

To either:
 ```
ORDER = ['queries', 'queries_dropped', 'packets_dropped', 'answers', 'backend_responses', 
         'backend_commerrors', 'backend_errors', 'cache', 'servercpu', 'servermem', 
         'query_latency', 'query_latency_avg']
```
or:
```
ORDER = [
    'queries',
    'queries_dropped',
    'packets_dropped',
    'answers',
    'backend_responses',
    'backend_commerrors',
    'backend_errors',
    'cache',
    'servercpu',
    'servermem',
    'query_latency',
    'query_latency_avg'
]
```

**Comment by Ferroin** [comment]
Input from @l2isbad on this would probably be a good thing too.

**Comment by paulfantom** [comment]
I like this one:
```py
ORDER = [
    'queries',
    'queries_dropped',
    'packets_dropped',
    'answers',
    'backend_responses',
    'backend_commerrors',
    'backend_errors',
    'cache',
    'servercpu',
    'servermem',
    'query_latency',
    'query_latency_avg'
]
```

**Comment by l2isbad** [comment]
I suggest

> line length

120 characters

> ORDER

```python
ORDER = [
    'queries',
    'queries_dropped',
    'packets_dropped',
    'answers',
```

> Do we want to make this the standard style for the ORDER and CHARTS[*]['options']

No. It's even looks bad and doesn't make much sense (unlike ORDER).

**Comment by Ferroin** [comment]
OK, I'll look into getting some of the python.d data collection modules done today then (I've got the a-c stuff mostly ready other than actually pushing the branch).

**Comment by paulfantom** [comment]
Current status:
```
python.d/web_log.chart.py:505:32: E128 continuation line under-indented for visual indent
python.d/memcached.chart.py:9:1: E265 block comment should start with '# '
python.d/postgres.chart.py:93:121: E501 line too long (134 > 120 characters)
python.d/postgres.chart.py:188:121: E501 line too long (140 > 120 characters)
python.d/postgres.chart.py:189:121: E501 line too long (142 > 120 characters)
python.d/postgres.chart.py:190:121: E501 line too long (142 > 120 characters)
python.d/postgres.chart.py:191:121: E501 line too long (143 > 120 characters)
python.d/postgres.chart.py:236:121: E501 line too long (142 > 120 characters)
python.d/postgres.chart.py:250:121: E501 line too long (140 > 120 characters)
python.d/postgres.chart.py:295:121: E501 line too long (121 > 120 characters)
python.d/postgres.chart.py:361:121: E501 line too long (136 > 120 characters)
python.d/postgres.chart.py:366:121: E501 line too long (136 > 120 characters)
python.d/postgres.chart.py:376:121: E501 line too long (135 > 120 characters)
python.d/fail2ban.chart.py:29:21: E131 continuation line unaligned for hanging indent
python.d/beanstalk.chart.py:118:5: E124 closing bracket does not match visual indentation
python.d/python_modules/__init__.py:1:1: W391 blank line at end of file
python.d/python_modules/__init__.py:1:1: W293 blank line contains whitespace
```

**Comment by paulfantom** [comment]
Seems like we only need those to be fixed and we could make PEP8 as a hard requirement:
```
python.d/postgres.chart.py:93:121: E501 line too long (134 > 120 characters)
python.d/postgres.chart.py:188:121: E501 line too long (140 > 120 characters)
python.d/postgres.chart.py:189:121: E501 line too long (142 > 120 characters)
python.d/postgres.chart.py:190:121: E501 line too long (142 > 120 characters)
python.d/postgres.chart.py:191:121: E501 line too long (143 > 120 characters)
python.d/postgres.chart.py:236:121: E501 line too long (142 > 120 characters)
python.d/postgres.chart.py:250:121: E501 line too long (140 > 120 characters)
python.d/postgres.chart.py:295:121: E501 line too long (121 > 120 characters)
python.d/postgres.chart.py:361:121: E501 line too long (136 > 120 characters)
python.d/postgres.chart.py:366:121: E501 line too long (136 > 120 characters)
python.d/postgres.chart.py:376:121: E501 line too long (135 > 120 characters)
```

**Comment by Ferroin** [comment]
With #4298 being merged, all the code should now be PEP 8 compliant.
