### ISSUE TITLE
[project management] Disable merging without squashing

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4171]
Github allows to configure behavior of Merge button. Let's disable plain "Merge" an "use "Squash and merge". This will give us much cleaner git history.

More: https://help.github.com/articles/configuring-pull-request-merges/

**Comment by ktsaou** [comment]
I like this.
Let me use "Squash" for some time before disabling "Merge".

**Comment by ktsaou** [comment]
let's do it. You would enable it?

**Comment by paulfantom** [comment]
Done
