### ISSUE TITLE
[Question] postgres monitor permissions

### ISSUE THREAD

**Issue by HazCod** [netdata/netdata#4187]
Hello,

the documentation does not state what tables the postgres plugin needs access to.
Is this every table, or only postgres-internal ones?

**Comment by ktsaou** [comment]
hm... I understand the postgres internal ones, but have a look here: https://github.com/firehol/netdata/blob/5c1a47c9366401c2bddecbb3425eec46400ae860/python.d/postgres.chart.py#L84-L239

**Comment by HazCod** [comment]
To be tested: `GRANT pg_monitor to myuser;`

**Comment by ktsaou** [comment]
I am closing this.
If you still need help, just post.
