### ISSUE TITLE
netdata master stops every 3 days 

### ISSUE THREAD

**Issue by amoldighe** [netdata/netdata#4198]
netdata is an amazing real time monitoring tool, we are using it in production to gather a metrics from 23 host VM's. Since past month we have noticed that the netdata master stops with the following message log:

2018-09-13 17:28:53: netdata FATAL : WEB_SERVER[static4] :Cannot allocate 37264 bytes of memory. # : Cannot allocate memory

2018-09-13 17:28:53: netdata INFO  : WEB_SERVER[static4] : EXIT: netdata prepares to exit with code 1...
2018-09-13 17:28:53: netdata INFO  : WEB_SERVER[static4] : EXIT: cleaning up the database...
2018-09-13 17:28:53: netdata INFO  : WEB_SERVER[static4] : Cleaning up database [23 hosts(s)]...
2018-09-13 17:28:53: netdata INFO  : WEB_SERVER[static4] : Cleaning up database of host'...
2018-09-13 17:28:53: netdata INFO  : STREAM_RECEIVER,[192.168.15.11]:45890] : EXIT: removing netdata PID file '/var/run/netdata.pid'...
2018-09-13 17:28:53: netdata ERROR : STREAM_RECEIVER,[192.168.15.11]:45890] : EXIT: cannot unlink pidfile '/var/run/netdata.pid'. (errno 13, Permission denied)
2018-09-13 17:28:53: netdata INFO  : STREAM_RECEIVER,[192.168.15.11]:45890] : EXIT: all done - netdata is now exiting - bye bye...
2018-09-13 17:29:00: python.d INFO: plugin: main: FINISHED

The system memory and swap usage on netdata master during the timestamp when the memory allocation message appeared has been consistent as per sar reports
17:00:01    kbmemfree kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
17:05:01      5283564   3105044     37.02         0   1555412  42831428    455.04   2973320    131448       356
17:10:01      5283656   3104952     37.01         0   1555428  42862808    455.38   2973344    131444       276
17:15:01      5283048   3105560     37.02         0   1555716  42892876    455.70   2973616    131712       312
17:20:01      5283068   3105540     37.02         0   1555740  42898752    455.76   2973668    131712       344
17:25:01      5282912   3105696     37.02         0   1555760  42812472    454.84   2973664    131712       384
17:30:01      5282776   3105832     37.02         0   1555804  43025828    457.11   2973896    131664       376

Few stats of the netdata master : 
* running on a VM with 8 GB RAM. 
* metric collected from 23 VM's
* each host maintains an history of 15984 i.e. 4 hours of data
* 2903 metric collected per second
* netdata master is on version - netdata 1.10.0-650-g46f715f_rolling

I have attached the snippet of the error.log when the memory allocation message started appearing.

Any help would be appreciated to fix this issue on my production setup.

**Comment by ktsaou** [comment]
Hi,

The following error is a system error:

```
2018-09-13 17:28:53: netdata FATAL : WEB_SERVER[static4] :Cannot allocate 37264 bytes of memory. # : Cannot allocate memory
```

So, the system refused to give netdata 37KB to serve a web request. When this happens, netdata exits.

Normally, the kernel's OOM (Out Of Memory) killer should have kicked in. Do you have such logs in kernel log?

What you do after that? You restart netdata or reboot?

To find which app is leaking memory, I suggest to start netdata, wait a few minutes for all the slaves to connect and start mirroring data, and take a snapshot of its dashboard (of the host, not a mirrored one). Then in 2 days (1 day before it stops), take another snapshot.

Could you please share these 2 snapshots with me? If you have private info, send them to costa@tsaousis.gr

**Comment by ktsaou** [comment]
Also, could you please run this:

```sh
du -s -h /var/cache/netdata
```

The files netdata saves there, are `mmap()`'d to RAM. So, this would tell us the max memory netdata ever used due to its mirrors (there may be a obsolete files there, so this would be above the max - but let's see how much it is).

**Comment by roedie** [comment]
I'm not sure if this is of any use, I saw the same on my install and fixed it by setting vm.max_map_count to a higher value. Or come to think of it, it might be mitigated now by that setting....

**Comment by ktsaou** [comment]
> I'm not sure if this is of any use, I saw the same on my install and fixed it by setting vm.max_map_count to a higher value. Or come to think of it, it might be mitigated now by that setting....

I think you are right. This can lead to a an out of memory message. So netdata calls `mmap()` to get memory and it is being rejected.

**Comment by ktsaou** [comment]
This was a question. So, I am closing it.
If you still have issues with your master, just post here.
