### ISSUE TITLE
Add a module for MTProxy

### ISSUE THREAD

**Issue by alsoGAMER** [netdata/netdata#4199]
I own an mtproxy server but the stats mtproxy provides aren't good looking and easy to read, sometimes impossible due to lack of ssh connection

For more info => https://github.com/TelegramMessenger/MTProxy

**Comment by cakrit** [comment]
Apologies for the late response @alsoGAMER 
As Netdata is all about [meaningful metrics](https://docs.netdata.cloud/contributing/#meaningful-metrics), we will need you to [help developers understand what they have to do](https://docs.netdata.cloud/contributing/#help-the-developers-understand-what-they-have-to-do).

Could you please provide some more detailed info on what exactly you want to see and the alarms you expect would be useful?

**Comment by alsoGAMER** [comment]
@cakrit I do not know what details to provide, I sent the link to the software source .. but more than that I can not say

**Comment by cakrit** [comment]
Closing due to no sponsor.
