### ISSUE TITLE
[project management] Activate LGTM.com integration

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4203]
LGTM.com provides static code analysis for languages used in our project, mainly C, Python and JavaScript. It can be used in similar fashion to CI system and analyze every PR.

@ktsaou you can do it by going to https://lgtm.com/projects/g/firehol/netdata/ci/ and following instructions from "Pull requests" section.

**Comment by paulfantom** [comment]
More on how lgtm.com analyses code: https://lgtm.com/help/lgtm/lgtm-analysis

**Comment by ktsaou** [comment]
ok, I activated it.

**Comment by ktsaou** [comment]
I think we need to configure it.

For example, in C it gives all FIXME comments as errors. It should not. These are there for a reason and they cannot be fixed now.

**Comment by ktsaou** [comment]
Also third party files should be ignored.

**Comment by ktsaou** [comment]
Also this report is completely wrong: https://lgtm.com/projects/g/firehol/netdata/snapshot/9e8c5afa960c6e960a5c655687783edbe8c953a3/files/src/popen.c?#x5783c71373da51c8:1

![image](https://user-images.githubusercontent.com/2662304/45601822-c9f59b80-ba1b-11e8-970f-0a4153993147.png)

In all 4 cases, first we open the pipe and then we read the output of the program we executed. But LGTM thinks it is the other way around (it believes we read the filename to run with `fgets()`. But we read the output of the program we just run).

**Comment by ktsaou** [comment]
@paulfantom I'll need your help with LGTM. We need to exclude third party libraries from the checks. Today, their report is full of noise.

I fixed all C and many js issues identified by them.
There are 2 issues that are annoying:

1. The one I posted above above popen. Normally, we should file a bug for it. Something is wrong in their code.

2. the `FIXME` lines should not be detected as alerts. They are not. If we can't disable this alert, I think it would be better to search/replace them.

**Comment by paulfantom** [comment]
> Normally, we should file a bug for it

Do it then, what is blocking you?

Created a skeleton config in #4203

**Comment by paulfantom** [comment]
Also comments on PRs from LGTM.com should be posted by some bot account, not from your account.

**Comment by paulfantom** [comment]
Also it seems that LGTM tracks alert changes not overall alert number. So it will only fail if a PR is introducing new alerts.

**Comment by ktsaou** [comment]
> Do it then, what is blocking you? But read this before: https://lgtm.com/rules/2152620561/

The definition of this is right. The detection in netdata is wrong.

**Comment by ktsaou** [comment]
filed a bug report here: https://github.com/Semmle/ql/issues/199

**Comment by paulfantom** [comment]
Seems like you cannot change LGTM account for commenting.

> When all LGTM analysis is complete, and if there are alert changes, LGTM automatically adds a single comment to each pull request, along with a detailed summary. The comment lists the names and counts for new and fixed alerts in the pull request. It's posted by the LGTM account on Bitbucket and uses your account on GitHub or GitLab (where robot accounts are strongly discouraged)

I propose to leave it as is for now. However after we move to another repo this integration will need to be reenabled, so let's do it from a bot account. This way automatic task will be handled by a bot as it should be done. Such account will be also useful to create releases and generate changelog from CI system. Such account should have a very strong password (and preferably TFA) as it will probably need administrator privileges (for example to push changelog to protected master branch). All integrations of such account should be handled either by OAuth or via tokens, never with password.

**Comment by philwhineray** [comment]
I've mailed the existing firehol-automation user credentials to @ktsaou in GPG-encrypted form. Password is pretty strong (20 chars entirely random from Keepass) but no 2FA, since I'm not sure how one would go about sharing that.

This is the account used to push the output of Travis builds currently so is a decent candidate for creating and managing other tokens for integration.

**Comment by ktsaou** [comment]
ok got them. Thanks.
However, LGTM says `firehol-automation` is not owner/admin of netdata.
How can I added it. I can't find anywhere a setting for this.

**Comment by ktsaou** [comment]
Could this be the issue?

![image](https://user-images.githubusercontent.com/2662304/45645380-eac7fa80-bac8-11e8-8e4b-91dfb495da4f.png)

So, `firehol-automation` does not have enough permissions on the `firehol` organization?

**Comment by ktsaou** [comment]
hm... probably:

![image](https://user-images.githubusercontent.com/2662304/45645424-12b75e00-bac9-11e8-91f8-2cd234088806.png)

I don't have the same limitation.

**Comment by paulfantom** [comment]
Guys, there is no point in doing this now as we want to move whole repo to new organization.

**Comment by ktsaou** [comment]
hm... probably right. @philwhineray keep in mind a made `firehol-automation` and owner of `firehol` organization and then demoted it back to member. It seems it kept all the settings.

I also restored write access to the automation group for netdata.

**Comment by ktsaou** [comment]
btw, somehow during the retries I made, LGTM does not associate the "firehol-automation" LGTM username with the `firehol-automation` github username. I don't know why. At some point it started complaining that `firehol-automation` on LGTM is occupied...

**Comment by paulfantom** [comment]
That won't matter after moving to new org.
