### ISSUE TITLE
support gauges without a needle

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4206]
Containerized netdata shows very misleading gauge with memory utilization (pink circle on picture below). This gauge doesn't have a maximum value and is adapting to current value, therefore "arrow" can be at different angles, but still show the same value.

![screenshot_20180916_155607](https://user-images.githubusercontent.com/3531758/45597305-7018b580-b9ca-11e8-8816-35d10df7c2ae.png)

**Comment by ktsaou** [comment]
This happens for most gauges the `max` is dynamic. So, we can't know the `max` to adapt it.

In general "memory" in Linux is virtually infinite. You can never know how much is the max, because there swap, swap with compression, ballooning, etc. So, you can't really say "this is the max".

Keep in mind, that the kernel in order to help people understand memory pressure, provide a very nice metric. This one:

![image](https://user-images.githubusercontent.com/2662304/45599274-5ccd1080-b9f1-11e8-8237-fd5d1fb538ef.png)

The above says how much real memory (RAM) is available, before the system uses swap.

There is something pending for netdata in this area. CGROUPS allows configuring thresholds for all resources (except CPU). So, once this is set for memory, netdata could use it as the maximum, and it could actually set alarms based on this information too.

**Comment by ktsaou** [comment]
The gauge's needle shows the current % for the visible time-frame.

**Comment by paulfantom** [comment]
It shows a percent where 100% is a maximum consumption reached at some point in time. This has no use and is misleading when browsing through multiple similar gauges. It causes to think that there is a very high memory consumption due to having a needle 
constantly oscillating near a maximum value where in fact memory consumption isn't that high.

**Comment by ktsaou** [comment]
I am open to suggestions.... Possibly not a gauge then. Just a presentation of the current memory usage (i.e. a gauge without the needle).

**Comment by paulfantom** [comment]
Maybe just a number with unit?

**Comment by ktsaou** [comment]
Yes, we can do this...

**Comment by ktsaou** [comment]
I am thinking of new chart type that has a big number and an interactive sparkline bellow it, everything in a square box with slightly different background.

**Comment by ktsaou** [comment]
Like this (without the coffee and the dollar sign :)

![image](https://user-images.githubusercontent.com/2662304/45601515-a9771280-ba16-11e8-8a84-93a1fdf79713.png)

**Comment by paulfantom** [comment]
No, leave a coffee sign :smile: /joking

I don't know what would be the use case for such chart design. But I don't know much about design :stuck_out_tongue:

**Comment by ktsaou** [comment]
It will show a little history on the gauge chart, so in our example, you will know if memory is stable, increases or decreases...

**Comment by paulfantom** [comment]
That is exactly what a usual chart is for.

**Comment by cakrit** [comment]
I think that showing the gauge with the max being the RAM available before going to swap is a bit more useful at this bird's eye view. You do want to know when you're going into swap. An alternative would be to have gauges with green/amber/red areas (which generally nice to have). For this example, green would always be the RAM before we hit swap and it could scale, so you show a smaller and smaller green area as you approach infinity :)

**Comment by ktsaou** [comment]
> I think that showing the gauge with the max being the RAM available before going to swap is a bit more useful at this bird's eye view.

hm... showing this at each container will be misleading. The available RAM is system-wide.

I think we should show free memory for a single container, only when we know exactly how much this container can use. So, it should be tight to the container context. If we can't know this, I prefer not to show it at all.

**Comment by paulfantom** [comment]
> I think we should show free memory for a single container, only when we know exactly how much this container can use. So, it should be tight to the container context. If we can't know this, I prefer not to show it at all.


I agree with that. That would be great.

**Comment by ktsaou** [comment]
> I agree with that. That would be great.

which part? because this is how it is today (we don't know it).
So you think we should know it. Right?

Do you know if docker/k8s can set limits on the memory footprint of containers?

**Comment by paulfantom** [comment]
> which part? because this is how it is today (we don't know it).

No it is not. We are showing full gauge with a needle when we don't know what is a maximum available memory. I agree that we should only show gauge when we know what is the maximum available memory and do not show it (maybe show just a number) when we don't know max.

> Do you know if docker/k8s can set limits on the memory footprint of containers?

Yes, it uses cgroups for that.

**Comment by ktsaou** [comment]
I thought CPU limits are not supported in CGROUPS. You can only contrain it in full cores, but not part of it. Has this changed?

**Comment by paulfantom** [comment]
You can limit CPU shares in cgroups. 

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/resource_management_guide/sec-cpu_and_memory-use_case

https://kernel.googlesource.com/pub/scm/linux/kernel/git/glommer/memcg/+/cpu_stat/Documentation/cgroups/cpu.txt

**Comment by cakrit** [comment]
Keeping it on me until the new issue is created and triaged.

**Comment by cakrit** [comment]
cgroups limits have been implemented and the gauges updated
