### ISSUE TITLE
Functional testing framework.

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4222]
Currently we are testing almost everything manually and this is does not scale well. Maybe we could somehow use some testing framework to implement simple test scenarios.

I had something like this in mind:
1) Create a simple service exposing static metrics imitating for example nginx stats
2) Run plugin which should connect to it automatically
3) Check if data gathered by plugin is valid

This could be later implemented in CI pipeline.

**Comment by l2isbad** [comment]
> Currently we are testing almost everything manually and this is does not scale well. Maybe we could somehow use some testing framework to implement simple test scenarios.

This is so true!

**Comment by ktsaou** [comment]
This is very nice, yes.

We need to also build tests for the netdata core. Thankfully there are already unit tests for the metrics database and interpolation, but we need a lot more. Some functions of netdata require a ninja to be done right. So, this will definitely help significantly.

**Comment by paulfantom** [comment]
Docker all the way! :smile::whale::whale::whale:

I would propose sth similar, but with more separation between unit/integration/e2e:
1) Use mock data (instead of full app) to unit/integration test. This will allow to use assertions and just test a module instead of going through whole netdata app
2) Use some intelligent scheduler, so we will run only tests on files which were changed and not all of them. however this is not that important when used with mocked data
3) Integration/e2e test should run couple of services, not all, for example containerized redis with some data and check if that is shown in netdata API. No data assertion here.
4) This testing scheme should be as much parallelized as possible, for example by using sth like tox.

Also we need to remember, that most CI systems don't allow to move build artifacts from job/stage to next job/stage, so we need to build and push such artifact somewhere (s3/registry/other).

**Comment by ccremer** [comment]
Well, I agree on the separation. But where exactly do you see the borders between unit/integration and integration/e2e in netdata context?

1. Fully agree
2. Likely difficult to implement, but I agree, not so important
3. The more we cover, the better. But I think each each test should be implemented isolated, so that they do not depend on each other. this will happen over time I guess.
4. Fully agree

Yeah, I know. We could also just build it again (in amd64 dockerfile) without linting/unit tests, before running the tests in the same stage.

**Comment by paulfantom** [comment]
> But where exactly do you see the borders between unit/integration and integration/e2e in netdata context?

Fairly simple:
- if it can run by executing `python.d.plugin` or alike - then it is unit/integration
- if it needs core netdata with everything then it is integration/e2e

This allows to run unit/integration tests without compiling netdata as currently all plugins are written in interpreted languages.

I write "unit/integration" and "integration/e2e" because I am still not convinced about naming scheme since it is possible to write even more granular tests and those should probably be named "unit" ones.

All tests need to be fairly fast as they will be running on all PRs. This means that the best test coverage in function of time can be achieved by running unit/integration against a mock of all (preferably only changed) modules. And integration/e2e should be executed against only a couple real services (like redis), preferably one of each type of `*Service` class.

**Comment by paulfantom** [comment]
>  we would need to create an interface for the external service, so it can be stubbed with a "in-memory-fake" service.

Yeah, that's exactly what a "mock" is.

I don't have any strong opinion on test naming schema, it can be unit, integration, whatever.

> This approach however doesn't solve testing the real classes that actually call the external services or hardware.

CI won't be able to test different hardware as it is run in cloud on x64 CPUs.

Overall we can have integration tests with mocks for *all* modules and test *some* with real scenarios in e2e test. Modules which need real hardware cannot be tested in automated fashion in "real" scenarios.

> I think we should prioritize integration testing and get some experience with spinning up some external services.

What experience? How to run docker containers? To spin up mysql you do `docker run -d -p 3306:3306 --name mysql mysql` or in python:
```py
import docker
client = docker.from_env()
client.containers.run('mysql', port={'3306/tcp': 3306}, detach=True, name="mysql") 
```
There is not much to learn about that. Probably more to it is how to use pytest, how to [create mocks in python](https://realpython.com/testing-third-party-apis-with-mock-servers/) etc.

**Comment by ccremer** [comment]
No, not that kind of experience. More like creating tests for some modules and then see whether those work ok-ish or are there issues and where to go next. To find out whether it's the correct approach ;)

**Comment by paulfantom** [comment]
> It could be that we decide to do integration tests in nightlies 

No one looks at those.

**Comment by gmosx** [comment]
We should also have mechanism for automatically testing the UI, e.g. https://www.seleniumhq.org/

**Comment by paulfantom** [comment]
Since it would be unwise to settle for one framework as those are mostly language specific, I have started implementing tests in [BATS](https://github.com/bats-core/bats-core) when it comes to bash scripts. First one is a lifecycle test which is already used on master branch: https://github.com/netdata/netdata/blob/master/tests/lifecycle.bats

**Comment by paulfantom** [comment]
Due to lack of progress and implementation of BATS for testing parts written in bash I am closing this. If needed please open new issue targeting usage of specific framework.
