### ISSUE TITLE
How to stop some metrics to save bandwidth

### ISSUE THREAD

**Issue by alivxlive** [netdata/netdata#4223]
Is there a way to stop some metrics in netdata slave. 
the reason for this action to save bandwidth between master and slave nodes.

**Comment by alivxlive** [comment]
Yes, adding a filter to reduce network bandwidth usage will be a great idea. and as you said if netdata public will be great to limit metrics.

**Comment by Telvary** [comment]
We also have the use case where we want to collect everything on every slaves (debug purpose) but only stream useful data for dashboards/alerts/reports. We currently have ~60 slaves and it generates ~90Mb/s.

**Comment by ktsaou** [comment]
hm... we should probably add compression to that protocol too.

**Comment by alivxlive** [comment]
Yes, good idea to add compression feature to netdata, but I have a concern will that feature will effect netdata master/slave performance. 
also, the metrics filter between slave > master ...etc.

**Comment by Ferroin** [comment]
Performance impacts from compression are probably not going to be a major issue.  The data being streamed should compress relatively well even on the lowest settings from most algorithms, and there are algorithms such as brotli that are designed for high performance when streaming data.

Filtering would still be good, but I doubt that it will be quite as critical if we can get good compression in place for the streaming protocol.

**Comment by ktsaou** [comment]
filtering charts during streaming is implemented with https://github.com/netdata/netdata/pull/4361
