### ISSUE TITLE
Logind bug

### ISSUE THREAD

**Issue by ShagoY** [netdata/netdata#4230]
Hi :)

I'm on 1.10.0-674-ge6c118d2 (I can't update to the lastest cause i use https://my-netdata.io/kickstart-static64.sh)

I have no problem with the Logind plugin except when there is more connection (logind.sessions or logind.users <= 1)

Error message :
`python.d` ERROR: logind: logind: update() unhandled exception: 'NoneType' object is not `iterable`

**Comment by l2isbad** [comment]
@Ferroin 

https://github.com/firehol/netdata/blob/e2097ea16a1ec8e29c1316d8d2f6e83802ef47c9/python.d/logind.chart.py#L58-L60

**Comment by Ferroin** [comment]
And of course the one case I didn't think to check doesn't work.

I'll have a PR with a fix posted shortly.

**Comment by ShagoY** [comment]
Hi @Ferroin :)

I just try your fix, it's work for "logind.sessions" but i lost "logind.users & logind.seats" when < 0

Note : I just updated the python file and clear the cache
My netdata commit: e2097ea

**Comment by Ferroin** [comment]
@ShagoY Can you recheck with PR #4346 instead?  That fixes the underlying issue in the API the module is using that caused this in the first place.

**Comment by Ferroin** [comment]
Glad to hear it!
