### ISSUE TITLE
writing bash script plugins to netdata

### ISSUE THREAD

**Issue by alivxlive** [netdata/netdata#4232]
Hello,
Is it possible to write plugins works with netdata to serve some statics, if possible can you please guide me?

Thanks.

**Comment by ktsaou** [comment]
Hi.

Pick any of these https://github.com/firehol/netdata/tree/master/charts.d

1. copy it, but make sure it is named `ABCD.chart.sh`
2. in the script, search and replace its name with `ABCD` everywhere

So, if you copy `example` and you want to name it `test1`:

1. copy `example.chart.sh` to `test1.chart.sh`
2. edit the `test1.chart.sh` and replace all occurences of `example` with `test1`.
3. adapt the 4 functions to do whatever you like

More information can be found here: https://github.com/firehol/netdata/wiki/General-Info---charts.d

**Comment by ktsaou** [comment]
This was a question. So I am closing.
If you need help, just post.
