### ISSUE TITLE
Synthetic chart template

### ISSUE THREAD

**Issue by bullno1** [netdata/netdata#4235]
We have a bunch of statsd metrics like: `subject_a.metric_a`, `subject_a.metric_b`, `subject_b.metric_a`, `subject_b.metric_b`... While the number of `metric_x` is fixed, the number of subjects: `subject_x` is dynamic.

We want to alert on certain metrics for all subjects. AFAIK, in order to reassign the context of those metrics for alarms, we need synthetic charts. Ideally, each subject should have its own set of charts (like how postgresql plugin creates one chart set for each db).

From what I gathered from the documentation, synthetic charts have to be configured one by one and pattern is only allowed for dimension. The same metric can vary greatly between subjects and thus, is not very useful to see in a single chart.

Is it currently possible to create template for charts or should I create a generator script for synthetic chart?

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
