### ISSUE TITLE
CII best practices badge

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4256]
https://bestpractices.coreinfrastructure.org/en/projects/2231

We are short in these:

Total: 88/100
Update 29/5: Total: 92/100

- [x] The information on how to contribute **SHOULD** include the requirements for acceptable contributions (e.g., a reference to any required coding standard). (URL required) `contribution_requirements` - Update 29/5: https://github.com/netdata/netdata/blob/master/CONTRIBUTING.md#contributions-ground-rules contains the markdown version, https://docs.netdata.cloud/contributing/#contributions-ground-rules contains the generated HTML version

- [x] The project **MUST** publish the process for reporting vulnerabilities on the project site. (URL required) `vulnerability_report_process` E.g., a clearly designated mailing address on https://PROJECTSITE/security, often in the form security@example.org. This MAY be the same as its bug reporting process. Vulnerability reports MAY always be public, but many projects have a private vulnerability reporting mechanism. Update 29/5 - Fixed in #6163 and #6166

- [x] If private vulnerability reports are supported, the project **MUST** include how to send the information in a way that is kept private. (URL required) `vulnerability_report_private` Examples include a private defect report submitted on the web using HTTPS (TLS) or an email encrypted using OpenPGP. If vulnerability reports are always public (so there are never private vulnerability reports), choose "not applicable" (N/A). Update 29/5 - Fixed in #6163 and #6166

- [ ] It is **SUGGESTED** that the test suite cover most (or ideally all) the code branches, input fields, and functionality. `test_most`

- [ ] We miss the whole "New functionality testing" section. It is related to automated test suite (2 **MUST**, 1 **SUGGESTED**)

- [ ] It is **SUGGESTED** that at least one dynamic analysis tool be applied to any proposed major production release of the software before its release. `dynamic_analysis` A dynamic analysis tool examines the software by executing it with specific inputs. For example, the project MAY use a fuzzing tool (e.g., American Fuzzy Lop) or a web application scanner (e.g., OWASP ZAP or w3af). In some cases the OSS-Fuzz project may be willing to apply fuzz testing to your project. For purposes of this criterion the dynamic analysis tool needs to vary the inputs in some way to look for various kinds of problems or be an automated test suite with at least 80% branch coverage. The Wikipedia page on dynamic analysis and the OWASP page on fuzzing identify some dynamic analysis tools. The analysis tool(s) MAY be focused on looking for security vulnerabilities, but this is not required.
Update 29/5: netdata was accepted in OSS-Fuzz, but we need to create fuzz targets. #6162 was created to implement this (a lot of work).

**Comment by paulfantom** [comment]
> The project MUST publish the process for reporting vulnerabilities on the project site. 

>  If private vulnerability reports are supported, the project MUST include how to send the information

Just add info similar to k8s one: https://kubernetes.io/docs/reference/issues-security/security/#report-a-vulnerability in wiki under "security" page.

> We miss the whole "New functionality testing" section

See https://github.com/netdata/netdata/issues/4222

**Comment by ktsaou** [comment]
Check it: https://github.com/netdata/netdata/wiki/Netdata-Security-and-Disclosure-Information

**Comment by ktsaou** [comment]
@paulfantom we need a way to accept private (encrypted) security reports. Can you help? The kubernetes team provides public keys, so that only them can decrypt it.

**Comment by paulfantom** [comment]
Seems like we have an email address, so now we can provide public GPG key and do the same.

**Comment by cakrit** [comment]
We need a test framework either integrated with Travis CI, or not. We already have a few tests that are not automatically executed and we will certainly be spending a lot more time on adding automated regression tests. 
- [ ] Investigate available solutions
- [ ] Incorporate the tests we already have
- [ ] Ensure regression tests are executed on each PR
- [ ] Provide guidelines/process to add more tests

**Comment by prologic** [comment]
This was added some time ago. Closing.

<img width="600" alt="Screen Shot 2020-03-05 at 09 46 52" src="https://user-images.githubusercontent.com/1290234/75933670-486f2300-5ec6-11ea-953e-ea5f3d921723.png">
