### ISSUE TITLE
netdata startup order on boot (systemd)

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4266]
systemd allows setting the priority services are started using this line: https://github.com/netdata/netdata/blob/ba2e5827a39c03099f8e07a603594cb259cda078/system/netdata.service.in#L4

We should find all the systemd services netdata should depend upon, so that netdata users will not have configure this on their own.

This is a `good first issue` for anyone willing to contribute.

So the list could be found with a procedure like this:

1. find the list of all netdata plugins. This a good start: https://github.com/netdata/netdata/tree/master/python.d - but you can also use this: https://github.com/netdata/netdata/wiki/Add-more-charts-to-netdata

2. For debian/ubuntu and fedora/redhat/centos find the service name (`XXX.service`) for each of the netdata supported application

3. Alter this file: https://github.com/netdata/netdata/blob/master/system/netdata.service.in to add the relative services at the `After=` line.

I would also check if systemd supports multiple `After=` lines, or how it allows multi-line parameters, so that people will see a nice list on multiple lines, instead of a very long line.

**Comment by paulfantom** [comment]
> I would also check if systemd supports multiple After= lines

It does. For example fedora ships with `/etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service` which looks like this:
```
[Unit]
Description=firewalld - dynamic firewall daemon
Before=network-pre.target
Wants=network-pre.target
After=dbus.service
After=polkit.service
Conflicts=iptables.service ip6tables.service ebtables.service ipset.service
Documentation=man:firewalld(1)

[Service]
EnvironmentFile=-/etc/sysconfig/firewalld
ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS
ExecReload=/bin/kill -HUP $MAINPID
# supress to log debug and error output also to /var/log/messages
StandardOutput=null
StandardError=null
Type=dbus
BusName=org.fedoraproject.FirewallD1
KillMode=mixed

[Install]
WantedBy=multi-user.target
Alias=dbus-org.fedoraproject.FirewallD1.service
```

**Comment by SuperSandro2000** [comment]
Just out of curiosity: wouldn't be multiuser.target enough?

**Comment by roedie** [comment]
@SuperSandro2000 No, because multiuser.target is reached when its dependencies are started. Which are dbus, getty, logind to name some on my systemd.

So stuff like mysql might not even be started and netdata will fail to monitor it when it starts before.

**Comment by shreyabhandare** [comment]
Can i try this, unless someone is working on it?

**Comment by paulfantom** [comment]
@shreyabhandare go for it! :+1:

**Comment by ilyam8** [comment]
> netdata startup order on boot

Current idea is start netdata as soon as possible, netdata shouldnt depend on any sevice to start

So closing this in favor of #6295
