### ISSUE TITLE
Change GPL-3.0+ to GPL-3.0-or-later in all SPDX headers

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4274]
There is no `GPL-3.0+` type in SPDX according to https://spdx.org/licenses/.

This is causing FOSSA to complain.

**Comment by ktsaou** [comment]
nice catch...

**Comment by paulfantom** [comment]
That's fairly easy, but I didn't have time to check what is the difference between `GPL-3.0-or-later` and ` GPL-3.0-only` and that's worth checking before completing this issue.

**Comment by Ferroin** [comment]
Unless I'm mistaken, it's just a case of whether or not the code can be re-licensed by a third-party under a later version of the GPL or not.  The license badge in README.md indicates that we're `GPL-3.0-or-later` (that's what `GPL-3.0+` means), and the original LICENSE and LICENSE.md indicated as well that we're `GPL-3.0-or-later` (see https://github.com/netdata/netdata/blob/1c4ac67196b39ca78bcc452df278f6483490714b/LICENSE.md).

**Comment by cakrit** [comment]
Mind if we remove the "documentation" label here? The main issue here is FOSSA.

**Comment by paulfantom** [comment]
Or we could you fix it.
