### ISSUE TITLE
MegaCli Plugin fails to parse

### ISSUE THREAD

**Issue by stefnats** [netdata/netdata#4278]
I tried activating the MegaCli plugin but without success.
These are the outputs:

    netdata@server:/home/stefan$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace megacli
    2018-09-24 12:12:58: python.d INFO: plugin: main: Using python 2
    2018-09-24 12:12:58: python.d DEBUG: plugin: main: module load source: 'megacli' => [OK]
    2018-09-24 12:12:58: python.d DEBUG: plugin: main: module load config: 'megacli' => [OK]
    2018-09-24 12:12:58: python.d DEBUG: plugin: main: job initialization: 'megacli megacli' => ['OK']
    2018-09-24 12:12:58: python.d DEBUG: plugin: main: module status: 'megacli' => [OK] (jobs: 1)
    2018-09-24 12:12:58: python.d ERROR: megacli: megacli: failed to parse "/usr/bin/sudo -n /sbin/megacli -LDPDInfo -aAll -NoLog" output
    2018-09-24 12:12:58: python.d INFO: megacli: megacli: check() => [FAILED]
    2018-09-24 12:12:58: python.d INFO: plugin: main: FINISHED

and:

    netdata@server:/home/stefan$ /usr/bin/sudo -n /sbin/megacli -LDPDInfo -aAll -NoLog
    
    Adapter #0
    
    Number of Virtual Disks: 1
    Virtual Disk: 0 (Target Id: 0)
    Name:
    RAID Level: Primary-1, Secondary-0, RAID Level Qualifier-0
    Size:893.75 GB
    State: Optimal
    Stripe Size: 256 KB
    Number Of Drives:2
    Span Depth:1
    Default Cache Policy: WriteThrough, ReadAhead, Direct, No Write Cache if Bad BBU
    Current Cache Policy: WriteThrough, ReadAhead, Direct, No Write Cache if Bad BBU
    Access Policy: Read/Write
    Disk Cache Policy: Enabled
    Encryption Type: None
    Number of Spans: 1
    Span: 0 - Number of PDs: 2
    PD: 0 Information
    Enclosure Device ID: 252
    Slot Number: 0
    Device Id: 5
    Sequence Number: 2
    Media Error Count: 0
    Other Error Count: 0
    Predictive Failure Count: 0
    Last Predictive Failure Event Seq Number: 0
    PD Type: SATA
    Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
    Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
    Coerced Size: 893.75 GB [0x6fb80000 Sectors]
    Firmware state: Online
    SAS Address(0): 0x4433221103000000
    Connected Port Number: 2(path0)
    Inquiry Data: S2TZNX0J902464      SAMSUNG MZ7LM960HMJP-00005              GXT5204Q
    FDE Capable: Not Capable
    FDE Enable: Disable
    Secured: Unsecured
    Locked: Unlocked
    Foreign State: None
    Device Speed: Unknown
    Link Speed: Unknown
    Media Type: Solid State Device
    
    PD: 1 Information
    Enclosure Device ID: 252
    Slot Number: 1
    Device Id: 6
    Sequence Number: 2
    Media Error Count: 0
    Other Error Count: 0
    Predictive Failure Count: 0
    Last Predictive Failure Event Seq Number: 0
    PD Type: SATA
    Raw Size: 894.252 GB [0x6fc81ab0 Sectors]
    Non Coerced Size: 893.752 GB [0x6fb81ab0 Sectors]
    Coerced Size: 893.75 GB [0x6fb80000 Sectors]
    Firmware state: Online
    SAS Address(0): 0x4433221102000000
    Connected Port Number: 1(path0)
    Inquiry Data: S2TZNX0J900856      SAMSUNG MZ7LM960HMJP-00005              GXT5204Q
    FDE Capable: Not Capable
    FDE Enable: Disable
    Secured: Unsecured
    Locked: Unlocked
    Foreign State: None
    Device Speed: Unknown
    Link Speed: Unknown
    Media Type: Solid State Device
    
    
    Exit Code: 0x00

**Comment by l2isbad** [comment]
Hi @stefnats 

Please replace
https://github.com/netdata/netdata/blob/ece7ab755275017038165195c9b11cb93462afe3/python.d/megacli.chart.py#L96

with

```python
r'Adapter #([0-9]+) State(?:\s+)?: ([a-zA-Z]+)' 
```

and check if it works

**Comment by stefnats** [comment]
Hi @l2isbad - Works! Thanks :)
