### ISSUE TITLE
Best practices for utilizing netdata in docker swarm mode?

### ISSUE THREAD

**Issue by jmunson** [netdata/netdata#4293]
I was curious if anyone could share their experience using netdata for monitoring a docker network.

Using this in docker-compose.yml
       deploy:
      mode: global

gets me a copy of netdata running on each worker node, which is what I want. Passing in volume mountsgives me enough access to the host system to start monitoring its resources.  Where I run into problems though is in monitoring other containers inside of the host.

If I were running netdata directly on the host machine, this is where I would for example have it scrape http://localhost/stats to gather information from the local webserver.  Inside of docker however localhost:80 does not route to my nginx image.

I can use dockers dns based service discovery to instead do something like http://nginx/stats,  but as I understand it then doing this could in theory be scraping any nginx instance on the whole network. or at the very least, even if it is properly preferring the local one, then if I bring the local nginx down my stats would just start pulling from whatever one is still up, giving me inconsistent results.

Does anyone have any advice on best practices here? I'm tempted to just keep deploying netdata out-of-band as part of my process of bringing a new machine into the docker network, but I'd rather have as much of what I'm running documented and deployed automatically from docker-compose.yml files.  The other possible option I have is in forgoing as much network-based scraping as possible and instead relying on volume mounting sockets. This seems more reliable in that I know it won't leave the host machine, but I'm not sure it's always an option so a solution that works for network-based scraping might still be needed.

**Comment by Ferroin** [comment]
If you want to monitor the host system and the containers, you essentially have two choices:

1. Run Netdata on the host.  This will get all the data on all the containers as well as the host system.  It can then be proxied through a web server or web proxy running in one of the containers (using Netdata's support for listening on a UNIX socket is probably the best approach for passing it to the container doing the proxying).  This has the low overhead in terms of both setup and continued management, but can only track data on the containers that Docker itself exposes.
2. Run Netdata in each container, use a dedicated container with Netdata in it to monitor the host stats, and then stream data from all the other containers to that dedicated one.  This will get you highly detailed data from each container, including some stuff you can't get through Docker, but it's a bit of a pain to set up and manage.
