### ISSUE TITLE
Application metrics directly to netdata

### ISSUE THREAD

**Issue by olivierlambert** [netdata/netdata#4296]
I'd like to modify an existing app to send some internal metrics to Netdata. I don't want to create a Netdata plugin that fetches metrics to my app: I'd like my app directly sending/writing to Netdata.

Is it possible? If yes, what's the best approach?

**Comment by Ferroin** [comment]
Making use of Netdata's statsd interface is probably your best bet.

Detailed information can be found in [the statsd page on the wiki](https://github.com/netdata/netdata/wiki/statsd).

**Comment by olivierlambert** [comment]
That's indeed the most promising way to do so. I just reached the same conclusion just before reading your post. Closing, thanks!
