### ISSUE TITLE
new custom Gauges disappearing on every update 

### ISSUE THREAD

**Issue by setupgr** [netdata/netdata#4311]
Hello,

First of all, this is an outstanding work of art!

I need to see on the very start (main heading - System overview) some extra
gauges to show available disk space of main partitions/disks
I have root, home & home2.

I just copy-paste the lines of code you make for "used swap" & it works like a charm, but,
after every update I need to paste these lines of code every time in the index.html file.

Is there any workaround for this?

The extra code I use:

                head += '<div class="netdata-container" style="margin-right: 10px;" data-netdata="disk_space._"'
                    + ' data-dimensions="used"'
                    + ' data-append-options="percentage"'
                    + ' data-chart-library="easypiechart"'
                    + ' data-title="Root"'
                    + ' data-units="%"'
                    + ' data-easypiechart-max-value="100"'
                    + ' data-width="9%"'
                    + ' data-before="0"'
                    + ' data-after="-' + duration.toString() + '"'
                    + ' data-points="' + duration.toString() + '"'
                    + ' data-colors="#DD4400"'
                    + ' role="application"></div>';
					
                head += '<div class="netdata-container" style="margin-right: 10px;" data-netdata="disk_space._home"'
                    + ' data-dimensions="used"'
                    + ' data-append-options="percentage"'
                    + ' data-chart-library="easypiechart"'
                    + ' data-title="Home"'
                    + ' data-units="%"'
                    + ' data-easypiechart-max-value="100"'
                    + ' data-width="9%"'
                    + ' data-before="0"'
                    + ' data-after="-' + duration.toString() + '"'
                    + ' data-points="' + duration.toString() + '"'
                    + ' data-colors="#DD4400"'
                    + ' role="application"></div>';

                head += '<div class="netdata-container" style="margin-right: 10px;" data-netdata="disk_space._home2"'
                    + ' data-dimensions="used"'
                    + ' data-append-options="percentage"'
                    + ' data-chart-library="easypiechart"'
                    + ' data-title="Home2"'
                    + ' data-units="%"'
                    + ' data-easypiechart-max-value="100"'
                    + ' data-width="9%"'
                    + ' data-before="0"'
                    + ' data-after="-' + duration.toString() + '"'
                    + ' data-points="' + duration.toString() + '"'
                    + ' data-colors="#DD4400"'
                    + ' role="application"></div>';

Also perhaps I should put them in a second row of gauges, beneath the first one.
Can you please show me how to do it? 

Thanks!

**Comment by setupgr** [comment]
I copied the whole web directory to a folder: myweb and changed netdata.conf to look there for the web pages.

There is no option in netdata.conf to make it look for a file 
(only index.html works. The directory conf won't work adding in the end the name i.e. custom.html.)
(Iam running netdata with the hostname and port).

So in this way perhaps I miss the later updates in the web folder.

**Comment by gmosx** [comment]
Converting this to a feature-request.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
