### ISSUE TITLE
Error message: Cannot open file stream.conf

### ISSUE THREAD

**Issue by jcormier** [netdata/netdata#4341]
With the latest changes this past weekend, netdata now reports an error about not finding stream.conf.  This showed up on all our servers over the weekend.  The server appears to be running so its unclear if this should be considered an Error.

Possibly related to #4283

```
Oct  1 06:32:12 wanda netdata: CONFIG: cannot open file '/etc/netdata/stream.conf'
Oct  1 06:32:12 wanda netdata[11765]: 2018-10-01 06:32:12: netdata ERROR : MAIN : CONFIG: cannot open file '/etc/netdata/stream.conf' (errno 2, No such file or directory)
```

**Comment by ktsaou** [comment]
ok, convert them to `INFO` and improved the messages with #4342
