### ISSUE TITLE
Removing slave databases from a former master

### ISSUE THREAD

**Issue by andyforceno** [netdata/netdata#4343]
How can I remove slave databases on a former master? I switched a master and a slave, and when I visit the former-master's Netdata page, it still lists the databases available on the host.

**Comment by ktsaou** [comment]
It will auto-clean in an hour.

**Comment by ktsaou** [comment]
You can control the time in `netdata.conf`:

```
[global]
	# cleanup orphan hosts after seconds = 3600
	# delete obsolete charts files = yes
	# delete orphan hosts files = yes
```

**Comment by ktsaou** [comment]
If you restart netdata though, after the slave disconnected, the slaves files on disk will remain. You will have to clean them yourself.

They are `/var/cache/netdata/MACHINE_GUID/`, where `MACHINE_GUID` is the unique id of the slave. You can find the slave MACHINE_GUID **on the slave**, at `/var/lib/netdata/registry/netdata.public.unique.id`.

**Comment by andyforceno** [comment]
Thank you, perfect. This is just what I was looking for.
