### ISSUE TITLE
Configuration Lost

### ISSUE THREAD

**Issue by alivxlive** [netdata/netdata#4351]
Hello,
I have an issue with netdata version "1.10.0-755-g843e236b_rolling", in some time the configuration lost from "/etc/netdata/orig/stream.conf"
It's happened two times during the last  24 hours.
It's a critical issue.
Any Idea for what happened.

*Case happen in the slave nodes, and master node.

**Comment by ktsaou** [comment]
Hi,

You mean you had edited `stream.conf` and is now lost?

To improve packaging of netdata, we have moved stock config files to `/usr/lib/netdata/conf.d` and if the files found at `/etc/netdata` are the same with the stock versions they were deleted.

The installer, to delete a file, applied the same check it was applying to overwrite it.

Now to edit a config, you have to run `/etc/netdata/edit-config FILENAME`. If you omit the `FILENAME` it will tell you which stock config files are available.

So, to edit `stream.conf` you need to run `/etc/netdata/edit-config stream.conf`.

**Comment by alivxlive** [comment]
Thank you @ktsaou
