### ISSUE TITLE
Using non-default registry in LAN fails: failed to contact the registry

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#4359]
Hi,
I have setup netdata on a tiny server (LXC) running Alpine Linux 3.8. This server is supposed to be the non-default registry in LAN.
Therefore I configured this _/etc/netdata/netdata.conf_:
```
[web]
bind to = 192.168.100.119:19999 localhost:19999

[registry]
        enabled = yes
        # registry db directory = /var/lib/netdata/registry
        # netdata unique id file = /var/lib/netdata/registry/netdata.public.unique.id
        # registry db file = /var/lib/netdata/registry/registry.db
        # registry log file = /var/lib/netdata/registry/registry-log.db
        # registry save db every new entries = 1000000
        # registry expire idle persons days = 365
        registry domain = biszumbitterenen.lan
        registry to announce = https://netdata.whl.biszumbitterenen.lan:19999
        registry hostname = Container - netdata Registry
        # verify browser cookies support = yes
        # max URL length = 1024
        # max URL name length = 50
        allow from = 192.168.*
```

However when I open netdata WebUI - my-netdata I can see this:
failed to contact the registry...
<a list of global registry servers>

![2018-10-05_08-57-40](https://user-images.githubusercontent.com/12523591/46520632-024f0380-c87d-11e8-8ea7-a035625acc1a.png)

Can you please advise how to fix this?

THX

**Comment by ktsaou** [comment]
Hi,

```
registry to announce = https://netdata.whl.biszumbitterenen.lan:19999
```

netdata port 19999 is not https. It is http.
You can proxy netdata via another web server to make it https.

To debug such issues, press F12 on your browser (chrome, firefox) and check the console and the network tabs. They should reveal the issue.

**Comment by 74cmonty** [comment]
I hate these kind of mistakes.
Making me look stupid.

**Comment by 74cmonty** [comment]
I hate these kind of mistakes.
Making me look stupid.
