### ISSUE TITLE
Question: bandwidth of network

### ISSUE THREAD

**Issue by defixje** [netdata/netdata#4368]
Hi. i really want a alarm if my bandwidth is above X last 5 minutes.

I don't see how i get this done, can someone please help me?

As a test i placed this in the `health.d/net.conf`

>    alarm: high_bandwidth
>       on: net.ens3
>       os: linux freebsd
>    hosts: *
> families: *
>   lookup: average -1m of recieved
>    units: bandwidth
>     warn: $this > 0
>    every: 10s
>     info: High bandwidth
>       to: sysadmin

_fyi: i get already error messages of other criticals, so thats not my question about_

**Comment by defixje** [comment]
Yes! Thank you, this works like a charm.

One question left, what is abou the `up 30s down 1m miltiplier 2 max 1h` how must i read that?

**Comment by ktsaou** [comment]
> One question left, what's about the `up 30s down 1m miltiplier 2 max 1h` how must i read that?

it says:

- When the alarm arms, wait 30 seconds before sending the notification (`up 30s`). This will avoid a notification if the alarm triggers for just 5 seconds.

- When the alarm disarms, wait 1 minute before sending the notification (`down 1m`). This will avoid a flip-flop of the notifications if the alarm disarms for 5 seconds and then arms again.

- If the alarm changes state during the above period, multiply the above durations by 2 (`multiplier 2`). So, if it flips-flops too fast, increase the above durations (x2 is a bit aggressive - probably 1.5 is better).

- But never delay a notification more than 1 hour (`max 1h`). So, matter how frequently this thing flips-flops you will get an alarm per hour.

btw, these delays are intentionally not respected for the web notifications your get on the dashboard. The dashboard shows all alarms immediately.

**Comment by ktsaou** [comment]
Keep also in mind that netdata has another mechanism for working with thresholds.

So instead of:

```
warn: $this > 1000
```

You can say:

```
warn: $this > (($status >= WARNING) ? 500 : 1000)
```

This says, that if the alarm is disarmed, it will armed above 1000.
But if the alarm is armed, it will disarm below 500.

This is probably better than `up`, `down`.

**Comment by ktsaou** [comment]
And you can also have a rolling window. So, if you don't want to have the trigger fixed at 1000, you can compare 2 timeframes:

- the average rate last minute, like you do
- with the average rate of the last 10 minutes

So, you can say: trigger the alarm if the rate of the last 1 minute is twice or half the rate of the last 10 minutes.

**Comment by nimaDevX** [comment]
> Try this:
> 
> ```
>  alarm: inbound_traffic_on_ens3
>     on: net.ens3
> lookup: average -1m abs unaligned of received
>  units: kbps
>   warn: $this > 1000
>  every: 10s
>  delay: up 30s down 1m multiplier 2 max 1h
>   info: hey, we reached 1Mbps on ens3
>     to: sysadmin
> ```
> 
> If you want to apply this to multiple interfaces, you can try this:
> 
> ```
> template: inbound_traffic
>       on: net.net
> families: ens3 ens4
>   lookup: average -1m abs unaligned of received
>    units: kbps
>     warn: $this > 1000
>    every: 10s
>     info: high inbound traffic detected
>    delay: up 30s down 1m multiplier 2 max 1h
>       to: sysadmin
> ```
> 
> The `delay` is used to prevent notification floods when the alarm flip-flops because the bandwidth is close to the threshold set.
> 
> If it still does not work for you, I would like you to post an alarm screenshot, as shown on the alarms modal of the dashboard.

Hi
I want to compare the last 10m average bandwidth with the current bandwidth and detect if the traffic has a significant reduction. I don't know how to get the current(latest) bandwidth so I've used the average of last 5s bandwidth.
I tried this:

`template: 5s_inbound_traffic_on_enp3s0
    on: net.enp3s0
lookup: average -5s unaligned of received
 every: 10m
 info: the average of the last 5s traffics


 alarm: inbound_traffic_on_enp3s0
    on: net.enp3s0
lookup: average -10m abs unaligned of received
calc: $5s_inbound_traffic_on_enp3s0 < ($this/3) ? 1 : 0
 crit: $this != 0
 every: 10m
delay: up 10s down 1m multiplier 2 max 1h
info:  -_-
to: sysadmin`

but the problem is that $5s_inbound_traffic_on_enp3s0 is always 0. how can I implement this logic?
thanks for your help

**Comment by ilyam8** [comment]
> I don't know how to get the current(latest) bandwidth

@nimaDevX 

see, just use `$sent` or `$received` in `calc`

```
 alarm: net_enp0s8_tx
       on: net.enp0s8
     calc: $sent
    units: kilobits/s
    every: 10s
     info: enp0s8 current tx usage
```

**Comment by nimaDevX** [comment]
> > I don't know how to get the current(latest) bandwidth
> 
> @nimaDevX
> 
> see, just use `$sent` or `$received` in `calc`
> 
> ```
>     alarm: net_enp0s8_tx
>        on: net.enp0s8
>      calc: $sent
>     units: kilobits/s
>     every: 10s
>      info: enp0s8 current tx usage
> ```

thank you so much.
