### ISSUE TITLE
Auth problem with Tomcat

### ISSUE THREAD

**Issue by AndyLDEX** [netdata/netdata#4369]
Hi,

  I'm trying to setup Tomcat monitoring, I've test that curl works ok:

`curl -u tomcat:tomcat2293654 http://localhost:8080/manager/status?XML=true`

I've set the Netdata config as follows:

```
localhost:
  name : 'local'
  url  : 'http://localhost:8080/manager/status?XML=true'
  user : 'tomcat'
  pass : 'tomcat2293654'
```

This command:

`usr/libexec/netdata/plugins.d/python.d.plugin  1 tomcat`

Gives me a rolling output like:

```
BEGIN tomcat_local.jvm_tenured 999980
SET 'tenured_used' = 1667178880
SET 'tenured_committed' = 12233736192
SET 'tenured_max' = 12233736192
END
```

My error log is empty, but in the Netdata GUI I don't see anything Tomcat related.
Am I missing something or is there some other debugging steps I can do to check where the issue is?

thanks! Andy.

**Comment by l2isbad** [comment]
Hi @AndyLDEX 
Why do you think it's `Auth` problem?

> usr/libexec/netdata/plugins.d/python.d.plugin 1 tomcat

Did you run it as `netdata` user?

**Comment by AndyLDEX** [comment]
> Why do you think it's `Auth` problem?

I've no idea what the problem is, I was just running as many tests as I could (that I'd found googling).

> Did you run it as `netdata` user?

I just tried, works same as with root, ie seems to me to work (I'm a new user to Netdata though!)

**Comment by l2isbad** [comment]
> I've no idea what the problem is
i was asking because of `Auth problem with Tomcat`

> I just tried

Did you try to restart netdata service?

**Comment by AndyLDEX** [comment]
> Did you try to restart netdata service?

Yep.

**Comment by l2isbad** [comment]
> My error log is empty

How did you check? `grep tomcat logfile` ?

**Comment by AndyLDEX** [comment]
> How did you check? `grep tomcat logfile` ?

Which log file do you mean? As mentioned, my Netdata error.log is empty (just noticed there is also a debug.log, also emty). Only log containing anything is access.log but it has nothing matching "tomcat"...

**Comment by l2isbad** [comment]
i meant `error.log`.

> As mentioned, my Netdata error.log is empty

@ktsaou 

any ideas?

**Comment by AndyLDEX** [comment]
I've just noticed that the access log is also empty, however there are old rotated logs from a few days ago that contain entries. I'm guessing that this is bad? Ie I should always have something in the access.log?

I just tried reinstalling via: `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` but still nothing in the logs....

**Comment by AndyLDEX** [comment]
OK! found the problem! Initially I installed a precompiled version which installed under /opt, when I realised this didn't have the plugins for MySQL etc I ran the kickstart,sh install and didn't realise it had installed to a different path! I guess I won't have any issues configuring Tomcat now, sry about that!

thanks, Andy.
