### ISSUE TITLE
API documentation cannot be read

### ISSUE THREAD

**Issue by derTuca** [netdata/netdata#4371]
The Swagger links provided on that page do not work, with the Swagger Editor going to its default project, and Swagger UI saying that the file could not be found.

EDIT: The page is visible in the sidebar, I missed it.

**Comment by paulfantom** [comment]
@derTuca so they work or they do not?

**Comment by derTuca** [comment]
No. The page in the wiki is visible, but the Swagger links do not work.
________________________________

**Comment by ktsaou** [comment]
Fixed them.
