### ISSUE TITLE
Netdata will support oracle db to collect  the sql query o/p stats 

### ISSUE THREAD

**Issue by nandhyala** [netdata/netdata#4374]
Hi,

Is there any way can i connect oracle database and collect  stats using sql from netdata tool.

Is there any plugins is available on netdata to support oracle db connections

**Comment by l2isbad** [comment]
@nandhyala unfortunately no

please post here stats query result ([collapsible mardown syntax](https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f))

**Comment by l2isbad** [comment]
Oh, @nandhyala
