### ISSUE TITLE
Missing chart data for ipv4 since September 28th update

### ISSUE THREAD

**Issue by wccropper** [netdata/netdata#4376]
On September 28th, the update caused issue #4312. Since then, I have no ipv4 data stored in my influxdb and my grafana graphs are empty. I see data for ipv6 (empty as this is disabled at OS) but there is data for graphing. I can see data from the netdata monitoring page. Did something change?

**Comment by ktsaou** [comment]
Sorry for the late reply.

Many of the `ipv4.*` metrics are actually metrics of the whole IP stack of the Linux kernel (ipv4 + ipv6). So, we have renamed them to `ip.*`.

**Comment by wccropper** [comment]
Thanks, Yes I found the renamed items recently and forgot I to update this.
