### ISSUE TITLE
dpkg-checkbuilddeps: error: Unmet build dependencies: linux-headers

### ISSUE THREAD

**Issue by 12nick12** [netdata/netdata#4377]
I get the error "dpkg-checkbuilddeps: error: Unmet build dependencies: linux-headers" when trying to install on Debian 9.5

**Comment by paulfantom** [comment]
I need more info. What are you trying to do? Are you using our installer script?

Confirmed: Debian 9.5 doesn't ship with meta package `linux-headers`.

**Comment by 12nick12** [comment]
No i did the normal readme for debian. linux-headers$(uname -r) are already installed

**Comment by paulfantom** [comment]
That's strange as we don't have `linux-headers` dependency anywhere.

**Comment by 12nick12** [comment]
I was able to get it working using the default vsl driver. Thank you
