### ISSUE TITLE
uniform reporting of plugins and modules and their configuration guide

### ISSUE THREAD

**Issue by konstheod** [netdata/netdata#4379]
Hello,
First of all you have done amazing job with the netdata.
My question is where can I found a documentation with all the metrics names, titles and units netdata exposes?
Τhe perfect scenario would be to have in a chart first of all the plugins with its modules, if any, and for each module the metrics names, titles and units that exposes. Also, it could be awesome if we documented how we can enable/disable those modules and  which of those modules are by default enabled.

Thank you beforehand.

**Comment by paulfantom** [comment]
I don't think we have such documentation, only place where you can get that info is from code modules, example:
https://github.com/netdata/netdata/blob/a441c0a2c8726b145c0a3fe62319d6fed71269a1/python.d/apache.chart.py#L25-L30

**Comment by konstheod** [comment]
First of all, thank you for the quick reply.

Yes I can extract them from the source  code  for each of the modules, but I thing that you can understand, this extraction can be done only if I go through each module and do it by hand, and in a case that some metrics change in a new update, it would be catastrophic for me! 
Do we have, at least a documentation for the default enabled metrics?

**Comment by Ferroin** [comment]
An alternative option if you only care about metrics on a particular configuration would be to query the API directly.  I forget the exact endpoint that you would need to query, but there's one that will return all the metrics and chart variables in one big JSON object when called without any parameters (this is what the dashboard uses to get the metrics).

**Comment by konstheod** [comment]
@ktsaou 
Maybe I was not so clear and sorry for the misconception. I'm using the netdata with prometheus. so in prometheus I get some metrics from the netdata per plugin and module in the well known format. 
My request is somehow to make a match between the metrics that I get in the prometheus with the netdata modules. After this I want to know how each module and plugin can be disabled. Going around the netdata.conf I see that lets say for the proc I should go to [plugin:proc] and enable/disable the according module, but for some other is not so straight forward.

About the second issue, the proc was just an example, there are more modules that is hard to find how to enable/disable them. For instance /net/stat/nf_conntrack module  of the proc plugin, or the stats of the web plugin and so on.

Another thing that I found is that in the json that you reported, there is a plugin called cgroup, but in the netdata.conf the plugin is called cgroup**s**

**Comment by konstheod** [comment]
Also the ipc module of the proc plugin is reported as module of the linux plugin which doesn't exists

**Comment by ktsaou** [comment]
ok, we need to fix all these and provide a guide on how to enable disable plugins and their modules.

**Comment by konstheod** [comment]
@ktsaou  Thank you very much!

**Comment by ktsaou** [comment]
PR #4387 unifies all the plugin and module names reported by netdata.

There is another pending task: document the way plugins and modules are enabled and disabled.

There was some documentation already here: https://github.com/netdata/netdata/wiki/Add-more-charts-to-netdata#configuring-plugins

I just added a lot more about all plugins.
For sure we need to work a bit. Currently it is too complex - too many files...

**Comment by ktsaou** [comment]
ok, merged the fix too.
