### ISSUE TITLE
Normalize data to use standard units

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4380]
OpenMetrics format expects data to be in standard units (not Mb, Gb, etc.) we could do the same in modules and just send data in normalized format.

WDYT?

**Comment by alivxlive** [comment]
Hello,
I guess the idea for normalizing data to use standard units such as MB or GB ..etc for all metrics it's will be good future and will give the user able to read matrics faster or for any other usages.

**Comment by ktsaou** [comment]
> Essentially if it has a prefix (like "kilo", "mega", "nano", etc.) then it is not a standard unit.

hm... another breaking change to be implemented with #807 and its friends...
