### ISSUE TITLE
Custom notifications on some slaves

### ISSUE THREAD

**Issue by Metrakit** [netdata/netdata#4381]
Hi! First of all, thanks for your awesome tool ! It help me a lot to monitor our infra.

I have a little question, I have setup a master with around 10 slaves. And on some slaves I have put a custom module for check the uptimes of our websites where I want send an alert when I'm receiving a status code different from 200 (500 or 400 by example) so it's why i have wrote a custom module for that in python.

On the screenshot below we can see my custom metric is called `websites.http_codes` : 
![capture d ecran 2018-10-11 a 15 17 50](https://user-images.githubusercontent.com/3305600/46806889-0a211300-cd69-11e8-9b49-8469cb2da2ad.png)

So I have tried my best to create a custom notification on one slave for have a try, it's look like this (it's a minimal configuration for a test purpose) : 

```yml
template: websites_uptime
      on: websites.http_codes
   every: 10s
    warn: $this > 0 # only for test
    crit: $this > 0 # only for test
    info: Test notification
      to: sysadmin
```

And I have put it in `/etc/netdata/health.d/websites.conf` but it's doesnt work, I receive nothing, there's nothing in the alarms modal on my dashboard (slave) and I dont know how to debug this (I found nothing in the documentation).

So first of all, it's possible to set custom notification based on a custom module in only some slaves ?
And if its possible, what im doing wrong ?

Thanks a lot for your help and thanks again to help me monitor our infra like a boss 😎

**Comment by Metrakit** [comment]
Ok, i use the wrong key, instead of `template:` i have used `alarm:` and its nearly working

**Comment by ktsaou** [comment]
ok, keep in mind that we provide an `http_check` plugin that does pretty much the same and also collects timings and can also check the contents of the responses.

On the alarms you can use a `hosts: *` line to configure the same alarm for different hosts.

**Comment by Metrakit** [comment]
Hi @ktsaou,

Thanks for your reply.

OMG, I think i have waste time to make my own pugin for doing the same job. I havent see clearly your doc I think. My bad.

Big thanks !
