### ISSUE TITLE
Alarms on specific processes with the apps plugin

### ISSUE THREAD

**Issue by alivxlive** [netdata/netdata#4385]
Hello,
Below some question in mind and I can't apply it to the current netdata.
1.How I can monitor app via using pid file such /var/run/serverX.pid in 'apps_groups.conf'?
2. Is it possible to monitor such as timestamps changes or checksum changes or size changes for some file( for security reasons)? 
3.creating custom config file for special application running do the following action:
-  monitor CPU, Memory, Disk, Network, Uptime, Service IF running or stoped only.
- Take special action/alerts if some metric exceeded the limit as configured.

Thanks

imaginary configuration:
```
check process serverx-dev with pidfile /var/run/serverx.pid
  if cpu > 95% for 2 check then alert adminGroup
  if mem  > 1024 MB for 5 check then alert adminGroup
  if failed host localhost port 443 then alert adminGroup
  if failed host localhost port 80 then alert [adminGroup,managmentGroup]  and then reset 

alertList:
    adminGroup:
        email@exmaple.com
    managmentGroup:
        email2@exmaple.com

Action:
    reset:
        /usr/bin/serverx restart
    stop:
        /usr/bin/serverx stop
```

**Comment by alivxlive** [comment]
any update on this

**Comment by Ferroin** [comment]
> 1.How I can monitor app via using pid file such /var/run/serverX.pid in 'apps_groups.conf'?

As far as I know you currently can't.

> 2. Is it possible to monitor such as timestamps changes or checksum changes or size changes for some file( for security reasons)?

Also currently no (though I know this one for sure).

> 3.creating custom config file for special application running do the following action:
> * monitor CPU, Memory, Disk, Network, Uptime, Service IF running or stoped only.
> * Take special action/alerts if some metric exceeded the limit as configured.

Again, as far as I know this is also currently not possible.

That said, as much as I hate to recommend a different monitoring solution, you might want to look into [monit](https://mmonit.com/monit/).  It can do everything you're asking about, and while it has it's own notification system (email only unfortunately), there is a netdata module for tracking the state of things monitored by monit.

**Comment by cakrit** [comment]
Closing it, please comment if you need any more help.
