### ISSUE TITLE
Collectors README and list of plugins/modules

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#4415]
Caused by: #4394 
> https://github.com/netdata/netdata/tree/master/collectors/README.md
will say how to add new internal plugins i.e. anything that does NOT use plugin.d. For external plugins, it will link to https://github.com/netdata/netdata/tree/master/collectors/plugins.d/README.md

collectors/README should be used to replace the equivalent of https://github.com/netdata/netdata/wiki/Add-more-charts-to-netdata
in the generated documentation. 

In addition to moving some info from the wiki page to the README, a script is needed to dynamically generate the tables with the lists of all collectors (plugins and modules). The output of this script won't be impressive, until all plugins and modules have README files that follow the templates in #4394 
So I'm thinking about one or more of the following:
- Temporarily add the lists as we have them today (i.e. just grab them from the wiki and put them in a separate, static file under collectors, that contains nothing else)
- Have the script just generate the less impressive version of the structure, with a config file to tell it what  what goes where (not difficult with the new structure to just create a hierarchy, but we need other metadata like Category/SubCategory to organize the plugins into more meaningful categories).

I don't think that the generated list belongs in github though. This script could perhaps be part of the build process, if we want this list in netdata/netdata itself, or the list could be added just in the generated static site. 

Thoughs welcome of course.

**Comment by ktsaou** [comment]
Add more charts to netdata, is used by the agent:

![image](https://user-images.githubusercontent.com/2662304/47048864-52469800-d1a4-11e8-8118-3df0ef40c46f.png)

@cakrit this page should be replaced with the URL that we will present all the collectors and their modules to end users.

CNCF generates this page https://landscape.cncf.io/grouping=no&sort=stars which is very similar to what we want for the end-user presentation of our collectors, using PRs. So I think their list is fully automated.

Check also the "LANDSCAPE" and the "SERVERLESS" tabs. I find this presentation for data collection, quite impressive!

Their repo is this: https://github.com/cncf/landscape

I would love to have something similar for end users.

**Comment by ktsaou** [comment]
btw, they run it on netlify:

> The Netlify build server runs easy mode, which makes it possible to just commit a change to landscape.yml and have the results reflected in production. Run with yarn fetch.

here: https://github.com/cncf/landscape/blob/master/INSTALL.md

**Comment by ktsaou** [comment]
So, the idea is that they have a bot that fetches the data, produces 2 files and done. The site is up.

**Comment by cakrit** [comment]
This one will progress as described in the spike #5045.
- [ ] Build prototype in one sprint
- [ ] Publish final version in a second sprint

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
