### ISSUE TITLE
Documentation links sanity checker

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#4416]
Internal links to other documentation artifacts are a nightmare to maintain. Different directory structures and naming conventions don't help very much. Need to write something to find the links, identify broken links  and probably convert them if the same structure or naming can't be maintained. 

Applies also to external links to code, wiki etc.

**Comment by ktsaou** [comment]
https://github.com/tcort/markdown-link-check

running it now on the wiki

**Comment by ktsaou** [comment]
fixed all links on the wiki

**Comment by ktsaou** [comment]
This issue is about finding a permanent solution. So, I leave it open.

**Comment by paulfantom** [comment]
We can implement it later in travis. But first we need to move docs to other repo.

**Comment by paulfantom** [comment]
Probably most widely used tool for that sort of thing is the awesome-bot used in most "awesome <something>" repositories: https://github.com/dkhamsing/awesome_bot.

It can be even coupled with [Danger](https://github.com/dkhamsing/awesome_bot#danger) to post comments with expired/invalid links

**Comment by cakrit** [comment]
I'm not yet clear on how it will work. 
- We need internal and external links in the markdown files that reside in the netdata project. There are already some README.md that reference other README.md files, given the current directory structure. 
- We also need internal and external links in the generated static site. The internal ones will need to be translated from the external ones. 
- Whether an internal link works or not depends on the quirks of our static site generator. e.g. mkdocs has two ways of structuring content, I found the default one with the directories to make internal linking much easier https://www.mkdocs.org/user-guide/configuration/#use_directory_urls

> first we need to move docs to other repo
I need to get this done to be able to ensure that the generated static site doesn't contain broken links. I will explain the steps in #4196

**Comment by ktsaou** [comment]
hm... just saw that the infographic has broken links...
I have to fix that too...

**Comment by ktsaou** [comment]
The wiki and the `.md` files in the repo have been checked and all links have been fixed.
Check also #4433

**Comment by cakrit** [comment]
Internal links in the repo work, but I'm urgently writing the sanity checker because many links don't work when we build the static site. It will also help with #4650
