### ISSUE TITLE
Script(s) to facilitate adding charts (i.e. collectors)

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#4431]
##### Feature idea summary
Add one or more scripts to help contributors add collector plugins and modules, by initiating the process and creating stubs, helping them test their collector and close the process with a PR. 

###### Expected behavior
1. collector-add <language> <collector identifier> <collector name> [category] [subcategory]
language: python, node, bash, c, jmx, [other?]
collector identifier: short, lower case identifier to be used in filenames (e.g. nginx)
collector name: Max two-three words. Goes to readmes, auto-generated comments etc. 
category: e.g. Web
subcategory: e.g. nginx

- Does git pull and creates a branch called <collector identifier> 
- Prepares a fully functional hello world plugin 
 - Depending on "language", creates directories and required files in the appropriate place under collectors  e.g. if "language" is python, adds folder "collector identifier".d under python.d.plugin and creates a .py with the essential parts/stubs already there. 
 - Creates a default config file, in the appropriate location
 - Adds the plugin to netdata.conf
 - Adds makefile entries?
 - Possibly compiles and restarts netdata
- Creates a README.md, with some parameters already filled in
- Informs the user of the next steps

2. collector-test <collector identifier>
- Finds the collector in the appropriate directory
- Validates (not sure how) that it passes basic tests, functions properly and perhaps meets some standards. 
I'm pretty sure that something like this already exists, but haven't looked. This one would be user-friendly and let the user know that s/he is ready to commit.

3. This one is probably nice to have - collector-commit 
Executes collector-test to ensure it's good to go.
Perhaps asks some Y/N questions, to ensure that non-automated things are done?
Creates a PR to merge the branch.

**Comment by cakrit** [comment]
Didn't mean to assign it myself, but at work we only have Internet Explorer and I can't correct it now :P

**Comment by cakrit** [comment]
We will also need to incorporate helpers to fill in the README.md as much as possible, like the python one @Ferroin offered to create for the Charts section of the README files in https://github.com/netdata/netdata/issues/4394#issuecomment-430726322

**Comment by cakrit** [comment]
Related to #4146 as well, as it will greatly facilitate new collector contributions.

**Comment by ktsaou** [comment]
We could provide a `_skeleton` directory inside all plugin orchestrators with all the files needed for this.
I would restrict the script to just provide the new directory, hook it to the build system (`Makefile.am` of the parent currently) and add the new files to git.

I wouldn't touch anything more, as this would require the script to have a lot of assumptions. Anything else needed (e.g. re-install netdata), would go to `README.md`.

**Comment by cakrit** [comment]
> the auto-generation script for the Python modules will either need an addition to the Python module API, or it won't be usable with modules that dynamically generate dimensions/charts at runtime

It might be overkill, but it's up to you: How much time it would take to do it like this, vs finding how many modules do generate dimensions at runtime and updating the READMEs just for those. I must say though, it's a very cool feature for new contributors, to see their README include even runtime info.

**Comment by Ferroin** [comment]
I can trivially figure out which ones generate dimensions at runtime (they all have either an empty `lines` entry in at least one chart entry, or no chart entries).  The big thing here in terms of the API change would be essentially embedding the dimension documentation as part of the code instead of making them fight with markdown and try to get it right.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
