### ISSUE TITLE
Icecast module not working

### ISSUE THREAD

**Issue by tommybuck** [netdata/netdata#4432]
Finally got round to sorting out my firewall. However the original issue still remains. I have figured out the issue though I think.

The test server you have been using has multiple source arrays in the json.
[http://192.99.34.205:8443/status-json.xsl](url)
![image](https://user-images.githubusercontent.com/22301046/47145344-67fdaf80-d2c1-11e8-86f9-91ff6e505ad0.png)

Where as mine doesnt have any source arrays just the data.
![image](https://user-images.githubusercontent.com/22301046/47145555-e9edd880-d2c1-11e8-9cfb-49b80129a5e3.png)

Can you take another look please?

_Originally posted by @tommybuck in https://github.com/netdata/netdata/issues/3715#issuecomment-430943917_

**Comment by l2isbad** [comment]
Please change
https://github.com/netdata/netdata/blob/15408ace0c2a81986026dd66446bb216c9b96eb6/collectors/python.d.plugin/icecast/icecast.chart.py#L93

to
```python
sources = data['icestats'].get('source')
if not sources:
    return None

return sources if isinstance(sources, list) else [sources]
```

should be fixed after that

**Comment by tommybuck** [comment]
I have changed that bit of code and can confirm it works!!!

Had to restart the netdata service after the change. After that it showed up on the main page.

**Comment by l2isbad** [comment]
Nice! Glad to help :smiley:

**Comment by ktsaou** [comment]
merged it
