### ISSUE TITLE
RethinkDB Plugin: Tables stats support

### ISSUE THREAD

**Issue by mani-keerthi** [netdata/netdata#4434]

**Comment by mani-keerthi** [comment]
I don't find an option to enable and monitor RethinkDB table stats like server and cluster. Is there any plan to add it in near future?

**Comment by mani-keerthi** [comment]
Hi @l2isbad 

I was out sick that's why I was not able to reply immediately.

You might noticed in RethinkDB's dashboard, they are stats at Server, DB, and Table level.

**Comment by mani-keerthi** [comment]
Hi,

      I reviewed your code, where you filter the stats with id 'server'. It might be the reason why are not getting the table stats.

https://github.com/netdata/netdata/blob/5b78382f7029f52016224bcc127be6bff94f91b1/collectors/python.d.plugin/rethinkdbs/rethinkdbs.chart.py#L186https://github.com/netdata/netdata/blob/5b78382f7029f52016224bcc127be6bff94f91b1/collectors/python.d.plugin/rethinkdbs/rethinkdbs.chart.py#L186

**Comment by l2isbad** [comment]
Well, i did it for some reason.
It seems i need to set up a vm with rethinkdb.

**Comment by l2isbad** [comment]
@mani-keerthi 

i've installed rethinkdb (deb8, rethinkdb 2.3.6)

`r.db("rethinkdb").table("stats").run(conn, callback);`

returns

```python
[{u'id': [u'cluster'],
  u'query_engine': {u'client_connections': 1,
                    u'clients_active': 1,
                    u'queries_per_sec': 0,
                    u'read_docs_per_sec': 0,
                    u'written_docs_per_sec': 0}},
 {u'id': [u'server', u'ec72e0c1-409f-4953-8674-74fd5effb730'],
  u'query_engine': {u'client_connections': 1,
                    u'clients_active': 1,
                    u'queries_per_sec': 0,
                    u'queries_total': 0,
                    u'read_docs_per_sec': 0,
                    u'read_docs_total': 0,
                    u'written_docs_per_sec': 0,
                    u'written_docs_total': 0},
  u'server': u'debian8_gvl'}]
```

I see no table stats.
I am not a rethinkdb user, so please guide me.

Should i create some tables? Use another queries?

**Comment by mani-keerthi** [comment]
@l2isbad 

Yes, you have to create a database and tables and feed some data and read it.

**Comment by l2isbad** [comment]
ok, i added some tables

```python
>>> pprint(data[2])
{u'db': u'test',
 u'id': [u'table', u'4b9633a4-76f6-4f38-9edf-b2dcc2b3480f'],
 u'query_engine': {u'read_docs_per_sec': 0, u'written_docs_per_sec': 0},
 u'table': u'authors'}
>>> pprint(data[3])
{u'db': u'test',
 u'id': [u'table_server',
         u'4b9633a4-76f6-4f38-9edf-b2dcc2b3480f',
         u'ec72e0c1-409f-4953-8674-74fd5effb730'],
 u'query_engine': {u'read_docs_per_sec': 0,
                   u'read_docs_total': 0,
                   u'written_docs_per_sec': 0,
                   u'written_docs_total': 3},
 u'server': u'debian8_gvl',
 u'storage_engine': {u'cache': {u'in_use_bytes': 50456},
                     u'disk': {u'read_bytes_per_sec': 0,
                               u'read_bytes_total': 74752,
                               u'space_usage': {u'data_bytes': 2097152,
                                                u'garbage_bytes': 0,
                                                u'metadata_bytes': 0,
                                                u'preallocated_bytes': 2097152},
                               u'written_bytes_per_sec': 0,
                               u'written_bytes_total': 92672}},
 u'table': u'authors'}
```

I know nothing about `rethinkdb` :cry: 

We have:

- N servers
- Every server has N databases
- Every database has N tables

So we need:

- Per server per database stats
- Per server per database per table stats

?

**Comment by mani-keerthi** [comment]
@l2isbad,

In RethinkDB, they provide an option to enable sharding and replication, so we can replicate tables across servers. But their stats table provide us the information about reads per table and database. I hope we don't need at "Per server per database per table stats", 

We just need 

- Per Database stats 
- Per Database Per Table stats

Meaning, we need overall read/write per second on a particular database/table.

make sense?

**Comment by l2isbad** [comment]
It will take some time. I won't be able to do it until next week

**Comment by l2isbad** [comment]
> you can review their dashboard at localhost:8080.

somehow i missed that, thx for the info

**Comment by l2isbad** [comment]
@mani-keerthi 

> read/write per second 

read/write docs or read/write bytes or both?

> We just need
Per Database stats
Per Database Per Table stats

`db dbName family`
* 1st chart read/write per db
* 2-n charts read/write per table of this db

?

And we need to support adding/deleting tables and databases in runtime..

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
