### ISSUE TITLE
Modify collector plugin READMEs to align to the README templates

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#4438]
##### Feature idea summary

PR #4436 added the README templates discussed in issue #4436.
All current plugin/module README.md files now need to align to these templates. 

###### Expected behavior
We need to convert the content of each README.md to the new template. There are over 100 of them - god bless them - so we will need some scripts to autogenerate as much content as possible (e.g. Charts table and most of the header table) at least. 

However, we will also need to manually work on each file as well, to normalize the structure and contents as per the template. 

For the purpose of this issue, the scripts to add content will be executed only once for each README.md to append or prepend content and merge the result. 
Contributors are also needed for the manual task of rearranging existing content.

**Comment by paulfantom** [comment]
> so we will need some scripts to autogenerate as much content as possible

> we will also need to manually work on each file as well

Automation is good when it saves time, but in this case it looks like someone will need to spend more time to create a script and then manually go through all files. It might be faster to just go through all files in the first place.

Relevant XKCD: https://xkcd.com/1319/

**Comment by cakrit** [comment]
Reassigned this, gents please close if you don't think we need it any more.
