### ISSUE TITLE
Adding available distribution packages to readme/installation guid

### ISSUE THREAD

**Issue by simonnagl** [netdata/netdata#444]
I will give you a scenario.

Someone finds `netdata` somewhere in the web. This leads him to the project home at `github`. There he will look for installation methods. At this point he only finds the automatic installer.

I think it would be nice to have a list of distributions which offer `netdata` in their package manager.

Why I think this should be made more clear.
1. More easy to configure and install.
2. No need to install build tools.
3. No need to configure systemd, init.d, ect. manual.
4. No extra steps for updating netdata.

**Comment by ktsaou** [comment]
First we have to find the list of distributions that offer netdata natively. I know Arch Linux does, so I have added it to the installation page. Any others?

**Comment by paulfantom** [comment]
Currently I am getting my way around [OBS](https://build.opensuse.org/) and connecting it with this repository for automated builds on major linux distributions. This way we could provide repositories with ready to install binary packages.
My dream is to have it made into two branches:
- 'stable'
- 'here be dragons' with something like nightly builds.

However this isn't something someone can properly do overnight. 

Also right now my main focus is on rewriting some slow bash plugins to python.

**Comment by ktsaou** [comment]
Not relevant any more.
