### ISSUE TITLE
at each update of netdata my netdata.service file is modified

### ISSUE THREAD

**Issue by Cisco30** [netdata/netdata#4441]
Hello
when I edit the netdata service file /etc/systemd/system/multi-user.target.wants/netdata.service to add seafile-server.service
`After = network.target httpd.service squid.service nfs-server.service mysqld.server mysql.service named.service postfix.service chronyd.service seafile-server.service`
when updating netdata the file is changed and my changes clear.
how to make seafile-server.service remain persistent?
thank

**Comment by paulfantom** [comment]
@Cisco30 you shouldn't edit systemd files located in `*.wants/` directories as this is where symlinks should live. If you want to overwrite default service file, put it into `/etc/systemd/system/`

@ktsaou Just checking, we are putting systemd service file in `/usr/lib/systemd/system/netdata.service`, right?

**Comment by Cisco30** [comment]
I followed your advice by putting the netdata.service file in / etc / systemd / system /. I'll tell you at the next update if it works;
thank you

**Comment by ktsaou** [comment]
ok, I am closing this, but if  you have still problem, just post here.
