### ISSUE TITLE
postfix ignored in python.d.conf

### ISSUE THREAD

**Issue by wcallgair** [netdata/netdata#4446]
##### Bug report summary
Ive browsed around a bit and have not seen any other complaints about this and im stumped.

'postfix: no' seems to be ignored in /etc/netdata/python.d/python.d.conf

Copying https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python.d.conf and setting 'postfix: no' did not work. Ive also tried ruling out erroneous characters by just having 'postfix: no' alone, but the error still persisted. Out of desperation I have even tried setting the permissions to 755 with out any luck.

```
[root@lab]$ ls -lah /etc/netdata/python.d/python.d.conf
-rw-r--r-- 1 root root 12 Oct 19 23:51 /etc/netdata/python.d/python.d.conf

[root@lab$ cat /etc/netdata/python.d/python.d.conf
postfix: no
```
![netdata dash](https://i.imgur.com/DgU37cz.png)

###### OS / Environment
Centos 7.4.x with netdata-1.10.1-1.el7.centos.x86_64 (built from source) with some simple netdata.conf edits.

##### Component Name
postfix, but may be an issue with other python.d plugins

##### Steps To Reproduce
Test1:
- wget/curl or paste https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python.d.conf to /etc/netdata/python.d
- set postfix: no in /etc/netdata/python.d/python.d.conf
- chmod 644 /etc/netdata/python.d/python.d.conf
- restart netdata
- wait 30 seconds, postfix will appear in gui

Test2:
- Let postfix: no be the only entry in /etc/netdata/python.d/python.d.conf
- chmod 644 /etc/netdata/python.d/python.d.conf
- restart netdata
- wait 30 seconds, postfix will appear in gui

###### Expected behavior
postfix: no should not allow graphing in the webgui

Thanks

**Comment by l2isbad** [comment]
Hi @wcallgair 

> /etc/netdata/python.d/python.d.conf

should be `etc/netdata/python.d.conf`

**Comment by wcallgair** [comment]
That did it! Thanks
