### ISSUE TITLE
Is configs.signatures still needed?

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4450]
##### Question summary

Do we still need to validate file checksums in /etc/netdata when we are not putting files there due to changed place of storing configuration files?

###### OS / Environment

All

##### Component Name

Installer

##### Expected results

No checksum validation of files we don't own.

**Comment by ktsaou** [comment]
No need to update `configs.signatures` any more.
We need to keep it though, as a migration for users updating their netdata with newer versions that install stock config files in `/usr/lib/netdata/conf.d`.
