### ISSUE TITLE
Wrong logos in infographic

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4455]
##### Bug report summary

- [x] Logo for grafana needs an update as [this](https://upload.wikimedia.org/wikipedia/commons/9/9d/Grafana_logo.png) is a new logo.
- [x] We don't support Red Hat Linux (which had last release in 2003) and this should probably be updated to RHEL (Red Hat Enterprise Linux).
- [x] "elastic" logo is a company logo and not a logo for elasticsearch
- [x] InfluxDB has only a semi-oficial logo as it mostly uses influxdata company logo. However [this](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Influxdb_logo.svg/1200px-Influxdb_logo.svg.png) one is frequently used on stickers and on wikipedia.
- [x] Prometheus uses [this](https://www.cncf.io/wp-content/uploads/2018/02/prometheus-horizontal-color.png) as a logo with a name.

##### Component Name

Documentation

##### Steps To Reproduce

Go to https://my-netdata.io/infographic.html or look at main README.md file.

##### Expected behavior

Logos are up to date.

#### :warning: IMPORTANT!
Netdata infographic **is** using at least some of the logos not in a way they are meant to be used. For example mongodb logo needs some white space around it (as probably most of the logos since this is a common practice) [[source](https://www.mongodb.com/brand-resources)].

Also, do we even have permission to use those logos? From mongoDB trademark standards for use:
> Prior to any use of any MongoDB, Inc. trademarks, you must submit the proposed use for MongoDB, Inc.’s prior written approval. MongoDB, Inc. may, in its sole discretion, approve or reject such use, and MongoDB, Inc. will notify you promptly of the approval or rejection.

**Comment by paulfantom** [comment]
It is even worse for mysqldb logo: https://www.mysql.com/about/legal/trademark.html

> no Oracle or MySQL Conditional Use Logo may be used on any product packaging or documentation, such as (without limitation) on CD-ROM or diskette labels or packaging, books or other publications. Any such use must be expressly authorized by Oracle in a signed, written agreement;

README.md is a part of documentation.

**Comment by cakrit** [comment]
@ktsaou please check/correct the following and I'll send it to trademar_us@oracle.com

(a) your name and your company's name; 

Christoforos Akritidis
NetData, Inc., a Delaware corporation with a mailing address of 2035 Sunset Lake Road, Suite B-2, 19702, Delaware, US

(b) contact information including phone number, fax number, email address and mailing address; 

Phone: +31 684435338
Email: chris@netdata.cloud
Mailing Address: 
C. Akritidis
Purpervlinderstraat 21
3544VZ, Utrecht
Netherlands

(c) the specific Oracle logo that you wish to use; 

Please see https://my-netdata.io/infographic.html second set of logos. Open to use any other approved logos.  e.g. https://www.mysql.com/common/logos/powered-by-mysql-125x64.png 

(d) background information on your company, detailing any relationship with Oracle; 

The company maintains an open-source performance monitoring software called netdata (https://github.com/netdata/netdata/). The software includes a plugin that collects information from a running mysql instance.

(e) the names of any Oracle contacts;

No contacts 

(f) a description of your proposed use of the logo, including why you want to use the logo, where the logo would appear, the duration and geographical extent of the proposed use, how the logo would be displayed relative to your corporate name and logo, and whether the Oracle logo would be one of various logos appearing; 

We would like to use the logo in a list of several other logos, to indicate the applications monitored by our software. The logo would appear in pages listing the plugins built by our company and any other contributors such as https://my-netdata.io/infographic.html and https://github.com/netdata/netdata/wiki/Add-more-charts-to-netdata
No time limit and no specific geographical region. 
(g) a description of Oracle's involvement in any program or project in association with which you propose to use the Oracle logo; and 

No involvement

(h) any previous correspondence you have had with Oracle regarding this logo request.

No previous correspondence

**Comment by cakrit** [comment]
TODO: Create list of all logos, with name, img URL and approval status. 
@ktsaou: I decoded /diagrams/netdata-overview.xml and can try to extract the first two columns we need from it directly, but is there an easier way to get the list?

**Comment by ktsaou** [comment]
Elasticsearch logo:

![image](https://user-images.githubusercontent.com/2662304/47609507-8d6c8500-da48-11e8-9556-0cebef6862f2.png)

source: https://www.elastic.co/brand

**Comment by ktsaou** [comment]
Grafana logo:

![image](https://user-images.githubusercontent.com/2662304/47609535-4206a680-da49-11e8-80bb-793dc9a783dd.png)

**Comment by ktsaou** [comment]
influxdb logo:

![image](https://user-images.githubusercontent.com/2662304/47609552-9f025c80-da49-11e8-8deb-b819b4dd0ce7.png)

**Comment by ktsaou** [comment]
Prometheus

![image](https://user-images.githubusercontent.com/2662304/47609572-2354df80-da4a-11e8-9121-49d3f1a74fce.png)

**Comment by ktsaou** [comment]
AWS SNS:


![image](https://user-images.githubusercontent.com/2662304/47609620-26040480-da4b-11e8-8ac3-c1b6a209619f.png)

**Comment by ktsaou** [comment]
rocket.chat:

![image](https://user-images.githubusercontent.com/2662304/47609674-ec7fc900-da4b-11e8-84cd-ff47fe586f84.png)

**Comment by ktsaou** [comment]
wip at https://github.com/netdata/netdata/pull/4511

**Comment by ktsaou** [comment]
@gmosx 	I would like to add a netdata to the infographic.
So, I'll wait for you before merging it.

**Comment by ktsaou** [comment]
adaptec logo:

![image](https://user-images.githubusercontent.com/2662304/47609913-17b8e700-da51-11e8-8828-dadf97b32a99.png)

**Comment by ktsaou** [comment]
boinc logo:

![image](https://user-images.githubusercontent.com/2662304/47609954-c0674680-da51-11e8-9e7f-d2f0425c0c94.png)

**Comment by ktsaou** [comment]
hddtemp logo:

![image](https://user-images.githubusercontent.com/2662304/47610043-2228b000-da54-11e8-9ce3-ca7e11207cf3.png)

**Comment by ktsaou** [comment]
litespeed web server

![image](https://user-images.githubusercontent.com/2662304/47610070-df1b0c80-da54-11e8-823f-d50b3ec97d42.png)

**Comment by ktsaou** [comment]
monit logo:

![image](https://user-images.githubusercontent.com/2662304/47610128-25bd3680-da56-11e8-9776-8b463033141e.png)

**Comment by ktsaou** [comment]
proxysql

![image](https://user-images.githubusercontent.com/2662304/47610153-b3008b00-da56-11e8-8eec-73cfdbf2dc54.png)

**Comment by ktsaou** [comment]
puppet logo:

![image](https://user-images.githubusercontent.com/2662304/47610163-f5c26300-da56-11e8-8317-980c5e20659e.png)

**Comment by ktsaou** [comment]
samba logo:

![image](https://user-images.githubusercontent.com/2662304/47610269-c3663500-da59-11e8-825d-28a63ba34c9d.png)

**Comment by ktsaou** [comment]
spigotmc logo:

![image](https://user-images.githubusercontent.com/2662304/47610289-2788f900-da5a-11e8-89d0-0406cee9defa.png)

**Comment by ktsaou** [comment]
uwsgi logo:

![image](https://user-images.githubusercontent.com/2662304/47610328-3b812a80-da5b-11e8-9488-2277ce3bca10.png)

**Comment by ktsaou** [comment]
done.

Generally, we don't want to abuse anyone's logo. Still, we need a single page inforgraphic with all of them...

So, they will either overlap a bit at their whitespace, or they will be too small.

I tried to have balance. Avoid all whitespace overlaps when possible. If this is not good for someone, the only solution is to make their logo even smaller.

btw, Red Hat is not shown without the... red hat... I can't help it. This is what they chose for their RHEL logo...

![image](https://user-images.githubusercontent.com/2662304/47610427-b1869100-da5d-11e8-9b10-ad269e3b8aa5.png)

**Comment by ktsaou** [comment]
netdata logo

![image](https://user-images.githubusercontent.com/2662304/47668573-7b5a2600-dbb1-11e8-8fb5-ed698c78c3fd.png)

**Comment by ktsaou** [comment]
merged!

**Comment by ktsaou** [comment]
A few infographics, are really dense:

https://cdn.chiefmartec.com/wp-content/uploads/2018/04/marketing_technology_landscape_2018_slide.jpg?fbclid=IwAR20PVdnpF0FGLNMwCYTfvf0UCNYVju3fqgJJYnoO31a6JFa3F7QgaWOvBQ
