### ISSUE TITLE
web console not responding

### ISSUE THREAD

**Issue by droidus** [netdata/netdata#4457]
I have iptables running on my linux server, and I can not figure out what iptables for input I need to allow for.  I did a "allow all input from interface", and it worked, but when I block that, and add these rules, it fails to work:
`-A INPUT -i eth0 -p tcp -m tcp --dport 19999 -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -o etn0 -p tcp -m tcp --sport 19999 -m state --state NEW,ESTABLISHED -j ACCEPT`
Is there another input rule that I need to add, or modify?

**Comment by ilyam8** [comment]
i am sure the problem is resolved, but still
 - use `conntrack` instead of `state`
 - rules should be something like

> -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
>...
>...
> -A INPUT -i eth0 -p tcp -m tcp --dport 19999 -m conntrack --ctstate NEW -j ACCEPT -m comment --comment netdata
