### ISSUE TITLE
Registry domain and chart URLs

### ISSUE THREAD

**Issue by andyforceno** [netdata/netdata#4458]
Apologies for another registry question, I know this has been covered quite a bit. I thought I had read in the wiki or in an issue that when the registry domain is changed, the chart URLs sent out in notifications will be updated to reflect that change, but I can't locate that now. Is that correct?

I changed the `registry domain` in `netdata.conf` but I still get URLs that point to `registry.my-netdata.io`, and when I try to access them I get an error that my account is not linked to any servers with that name (which I think makes sense if I'm no longer using the global registry, right?)

**Comment by cakrit** [comment]
To affect those URLs, you will need to uncomment the following line in `/etc/netdata/netdata.conf` and provide the URL of your own registry.

```
[registry]
        # registry to announce = https://registry.my-netdata.io
```

Then restart netdata and you'll be fine. 
Please close the issue if this fixes it for you.
