### ISSUE TITLE
Netdata & custom dashboard ?

### ISSUE THREAD

**Issue by titirino159** [netdata/netdata#4459]
Hello,

I retrieved the dashboard example of this link https://my-netdata.io/#demosites

I tried to edit the requests/s https://img.lght.pics/2MTV.png to put the incoming web requests (system.net / received) but the number of requests disappears :( Example : https://lightpics.net/i/2MTc

Do you know why ? The original code :

`                      <div class="mysparkline">
                            <div class="mysparkline-overchart-label2">
                                requests/s
                            </div>
                            <div class="mysparkline-overchart-value" id="octopuscs.requests.netdata" >
                            </div>
                            <div data-netdata="netdata.requests"
                                 data-dimensions="requests"
                                 data-host="//octopuscs.my-netdata.io"
                                 data-common-max="top-gauges"
                                 data-decimal-digits="0"
                                 data-chart-library="dygraph"
                                 data-dygraph-theme="sparkline"
                                 data-dygraph-type="area"
                                 data-width="100%"
                                 data-height="100%"
                                 data-after="-300"
                                 data-colors="#4BFF91"
                                 data-show-value-of-requests-at="octopuscs.requests.netdata"
                            ></div>
                        </div>`

My code :

`                        <div class="mysparkline">
                            <div class="mysparkline-overchart-label2">
                                requests/s
                            </div>
                            <div class="mysparkline-overchart-value" id="stackscale.requests.netdata" >
                            </div>
                            <div data-netdata="system.net"
                                 data-dimensions="received"
								data-host="//51.75.143.193:19999"
                                 data-common-max="top-gauges"
                                 data-decimal-digits="0"
                                 data-chart-library="dygraph"
                                 data-dygraph-theme="sparkline"
                                 data-dygraph-type="area"
                                 data-width="100%"
                                 data-height="100%"
                                 data-after="-300"
                                 data-colors="#5555AA"
                                 data-show-value-of-requests-at="octopuscs.requests.netdata"
                            ></div>
                        </div>`

Any idea to display the req/s from the system.net received data ?

Thank you

**Comment by Charanjet** [comment]
Hi,
can you please solve this issue 
https://github.com/netdata/netdata/issues/4499
Thanks in advance

**Comment by cakrit** [comment]
Closing, please comment if you need more help.
