### ISSUE TITLE
Hdd temperature monitoring on FreeBSD

### ISSUE THREAD

**Issue by sonicaj** [netdata/netdata#4463]
##### **Feature idea summary**
Currently we have monitoring of hdd temperatures via hddtemp daemon. This however does not work in FreeBSD. I suggest that I can write a plugin which can use smartctl to get hdd temperatures in FreeBSD and you can review it then. Looking forward to hearing your thoughts on this. Thank you

##### **Expected behavior**
I expect that after the plugin has been integrated, it will display us hdd temperature statistics

**Comment by sonicaj** [comment]
Hello, any updates on whether you think this is the best route forward and I can start writing a plugin for you to review regarding this ?

**Comment by sonicaj** [comment]
Relevant issue - https://redmine.ixsystems.com/issues/47833

**Comment by sonicaj** [comment]
Thank you for reaching out. Any idea when we can have this PR merged ? And is this in realtime ? Apologies for the lack of knowledge in this regard

**Comment by paulfantom** [comment]
@sonicaj log parser never will be realtime :)

**Comment by sonicaj** [comment]
I had similar opinions but wanted to be sure :P So what do you suggest we should do in this case ? I would strongly recommend that you should provide support in real time for FreeBSD as well. There are a lot of people who love netdata (myself inclusive :D ) and use FreeBSD

**Comment by l2isbad** [comment]
> And is this in realtime ? 

It depends how often `smartd` dumps logs. It is user configurable value. But keep in mind that `smartd` *appends* logs (use logrotate!).

Do you really need to measure temperature in real time (every seconds)? If you *really* need it then `smartd_log` will not work for you, sorry.

**Comment by l2isbad** [comment]
> There are a lot of people who love netdata (myself inclusive :D ) and use FreeBSD

I see `FreeBSD` i summon @vlvkobal

**Comment by sonicaj** [comment]
I think yes. That is what our users would be expecting. Kindly let me know your thoughts @l2isbad @paulfantom @vlvkobal on how best to handle this scenario for FreeBSD ? Many thanks for the swift response

**Comment by l2isbad** [comment]
> it doesn't invoke smartctl directly, but parses smartd logs.

btw @sonicaj 

https://github.com/netdata/netdata/pull/1679

https://github.com/netdata/netdata/pull/1679#issuecomment-276058411

invoking `smnartcl` every second is very expensive

**Comment by l2isbad** [comment]
Ha, `smartd` doesn't support 1 seconds interval, minimum is 10

```
ноя 06 00:08:30 homePC systemd[1]: Started Self Monitoring and Reporting Technology (SMART) Daemon.
ноя 06 00:08:30 homePC smartd[23100]: smartd 6.6 2017-11-05 r4594 [x86_64-linux-4.14.78-1-MANJARO] (local build)
homePC smartd[23100]: Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org
homePC smartd[23100]: ======> INVALID INTERVAL: 1 <=======
homePC smartd[23100]: ======> INTERVAL MUST BE INTEGER BETWEEN 10 AND 2147483647 <=======
```

**Comment by sonicaj** [comment]
That truly is resource expensive. Could you kindly tell me about what interval value we have when we parse logs ?

**Comment by Ferroin** [comment]
Whatever interval you have smartd configured to use.  The log parsing code picks up new lines fast enough that it's literally just dependent on when smartd puts the line in the log.  I think (I'm not 100% certain) that smartd defaults to something like once every 30 minutes for checking values from disks.

**Comment by l2isbad** [comment]
> Could you kindly tell me about what interval value we have when we parse logs ?

It is up to you. 

As you can see minimum is 10

```
homePC smartd[23100]: ======> INTERVAL MUST BE INTEGER BETWEEN 10 AND 2147483647 <=======
```

I think 10 is ok, but don't forget to set up logrotate.

Python module is very lightweight. It reads one line (last one) per iteration, and do it only if file was changed

**Comment by Ferroin** [comment]
Also, as far as the resource efficiency, smartd is only minimally better than smartctl.  Most of the issue is inherent to the SATA, AHCI, and the disk controllers.  You can reduce it a bit by using a SAS HBA instead of an AHCI SATA controller, but that won't completely eliminate it.

And even aside from the CPU intensive nature of things, you have to keep in mind that when you issue a SMART command to an ATA storage device, the device pretty much has to pause processing of all other commands, which means that the more often you poll a device for SMART status (or temperature info), the worse the device will perform for other things.

**Comment by sonicaj** [comment]
Thank you so much for your keen support. As the ideal solution in this case is tightly coupled with how smartd works, it is not ideal in our system unfortunately to use this. Thanks again, closing this issue
