### ISSUE TITLE
Systemd not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by Nani-o** [netdata/netdata#4465]
##### Bug report summary
With the fix that closes #4421, the installer is effectively now detecting the presence of systemd, but for whatever reason the unit file in `/lib/systemd/system/` seems not detected on Ubuntu 14.04.

```SHELL
root@test-netdata:/usr/local/src/netdata# systemctl status netdata
netdata.service
   Loaded: error (Reason: No such file or directory)
   Active: inactive (dead)
root@test-netdata:/usr/local/src/netdata# ll /lib/systemd/system/netdata.service 
-rw-rw-r-- 1 root root 1837 Oct 23 07:52 /lib/systemd/system/netdata.service
```

I’ve tried to replace the install path in `installer/functions.sh` with `/etc/systemd/system` and it seems to work : 

```SHELL
root@test-netdata:/usr/local/src/netdata# systemctl status netdata.service
netdata.service - Real time performance monitoring
   Loaded: loaded (/etc/systemd/system/netdata.service; enabled)
   Active: active (running) since Tue 2018-10-23 07:40:39 UTC; 20s ago
  Process: 19193 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 19192 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 19191 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 19190 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 19194 (netdata)
```

I don’t know what is the best practice, or why `/lib/systemd/system` works on most systems and not Ubuntu 14.04. I’ve always have put my services files in `/etc/systemd/system` without asking myself if it was the right place.

##### OS / Environment
Ubuntu 14.04

##### Component Name
Systemd installer

##### Steps To Reproduce
Install netdata on an Ubuntu 14.04, then try to run `systemctl` commands against.

##### Expected behavior
I should be able to control netdata service with systemctl commands.

**Comment by Nani-o** [comment]
I think I’ve found the reason, thoses informations are extracted from man pages on Ubuntu 14 and 16.

###### Ubuntu 14
```
       Table 1.  Load path when running in system mode (--system).
       ┌──────────────────────────────┬──────────────────────────────┐
       │Path                          │ Description                  │
       ├──────────────────────────────┼──────────────────────────────┤
       │/run/systemd/generator.early  │ Generated units (early)      │
       ├──────────────────────────────┼──────────────────────────────┤
       │/etc/systemd/system           │ Local configuration          │
       ├──────────────────────────────┼──────────────────────────────┤
       │/run/systemd/systemd          │ Volatile units               │
       ├──────────────────────────────┼──────────────────────────────┤
       │/run/systemd/generator        │ Generated units (middle)     │
       ├──────────────────────────────┼──────────────────────────────┤
       │/usr/local/lib/systemd/system │ Units for local packages     │
       ├──────────────────────────────┼──────────────────────────────┤
       │/usr/lib/systemd/system       │ Units for installed packages │
       ├──────────────────────────────┼──────────────────────────────┤
       │/run/systemd/generator.late   │ Generated units (late)       │
       └──────────────────────────────┴──────────────────────────────┘
```

###### Ubuntu 16
```
       Table 1.  Load path when running in system mode (--system).
       ┌────────────────────┬─────────────────────────────┐
       │Path                │ Description                 │
       ├────────────────────┼─────────────────────────────┤
       │/etc/systemd/system │ Local configuration         │
       ├────────────────────┼─────────────────────────────┤
       │/run/systemd/system │ Runtime units               │
       ├────────────────────┼─────────────────────────────┤
       │/lib/systemd/system │ Units of installed packages │
       └────────────────────┴─────────────────────────────┘
```

**Comment by Nani-o** [comment]
I just checked, there is indeed a `/usr/lib/systemd` folder on Ubuntu 14 but no `/usr/lib/systemd/system`. Even after creating the folder, installing the unit file, execute a daemon-reload, the service is not seen by systemd.

Lurking around the web ([here](
https://askubuntu.com/questions/490946/is-ubuntu-14-04-using-systemd#490963)) it seems the Ubuntu 14 systemd is only partial and still relies on init.

Trying to install some packages like `nginx` or `apache` leads to an init.d style script installation.

So I don’t even know what is expected right there ... I’ve always thought Ubuntu 14 has systemd support since I was using exclusively `/etc/systemd/system` for storing my services. So perhaps the fix for this issue is « simply » to detect that systemd is installed but not used as init and to fall back to the « old » style service file.

**Comment by paulfantom** [comment]
So it seems like #4423 was not needed and ubuntu 14.04 is using init so it should install init scripts and not systemd ones. 

Thus #4423 should probably be reverted as now it breaks installation on ubuntu 14.04.

**Comment by ktsaou** [comment]
hm... probably we should check the existence of `/usr/lib/systemd/system` additionally to what PR #4423 does.

The check we enabled with PR #4423 is probably useful. Prior to that PR, the only way to detect `systemd` was if pid 1 is linked to a filesystem file named `systemd`. I am not sure this is the only way, so checking additionally that a process named `systemd` runs, seems safe enough (the PR also checks if the process named `systemd` is run at the same process namespace as the host, so it should not give any false positive due to containers). But still this is just rational. I don't know if this is the right way.

What is interesting in this case, is if a systemd `.service` file works when installed under `/etc/systemd/system`. If it works, I am not sure what would be the right move: Fallback to `init` or install it in `/etc/systemd/system/`?

In all cases, checking for the existence of `/usr/lib/system/system` is probably a nice addition to the installer.

Our primary goal here is to allow netdata use the optimal way for each system. So, if ubuntu suggests systemd services for ubuntu 14.04, we should that, even if this means we have to install `netdata.service` somewhere else. If they suggest init, we should go that way.

So, @paulfantom please take this decision. I trust you will do the best.

**Comment by paulfantom** [comment]
https://github.com/netdata/netdata/pull/4643 was bringing back check for systemd directory so this should be fixed now. @Nani-o please reopen if this problem still persists.
