### ISSUE TITLE
duplicate name in cgroup if dash present in container name

### ISSUE THREAD

**Issue by mvivaldi** [netdata/netdata#4468]
##### Bug report summary
I have some lxd container and if the container name has one or more dash the metric name will show a duplicated name: 
example:
container name: node-red
cpu metric: cgroup_lxc_node_red.cgroup_lxc_node_red.cpu

if the container name doesn't have a dash this problem is not present
example:
container name: db
cpu metric: cgroup_lxc_db.cpu

##### OS / Environment
ubuntu 18.04/ ubuntu 16.04

**Comment by ktsaou** [comment]
Are you using the latest version of netdata?
There was an issue like that some time ago and it was fixed, so it would be nice to know if you are using the latest git version of netdata before tracing it.

**Comment by mvivaldi** [comment]
Yes I use the last version of netdata.... but I found something:
usually I collect data from the LXD host and send the metrics to my main netdata (using stream.conf), if I use the netdata directly on the LXD host the metrics are ok, but on the main netdata (that is configured to send all the metric to influxdb) I have the problem of the duplicated name.

**Comment by mvivaldi** [comment]
Hi, I use the netdata-update.sh script every week.
In the MAIN netdata the version is:
 
Your netdata version: 1.10.0-809-gb85833f0_rolling
Your netdata commit: b85833f 

this is the version on LXD host:

Your netdata version: 1.10.0-809-gb85833f0_rolling
Your netdata commit: b85833f

**Comment by mvivaldi** [comment]
Another info (I don't know if it is important) I installed netdata last year, and then I updated it with netdata-updater.sh without touching the configuration. So the configuration files are old.

**Comment by ktsaou** [comment]
Fixed in PR #4508

**Comment by ktsaou** [comment]
merged the fix.
Please update first the slave and then the master.

**Comment by mvivaldi** [comment]
Ok thank you! It's working!

**Comment by Ehekatl** [comment]
ah ha, so I was have the same issue in #4045
dash is the problem, later on I stopped using dash in statsd metric, and I thought that was fixed.
