### ISSUE TITLE
netdata custom dashboard auth

### ISSUE THREAD

**Issue by Dec64** [netdata/netdata#4469]
I'm trying to setup a netdata custom dashboard. All is nearly working except it get's 401'd when loading the data.

 `system.cpu: data download failed for url: https://netdata.domain.co.uk/api/v1/data?chart=system.cpu&format=json&points=207&group=average>ime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-300`

`status: 401
www-authenticate: Basic realm="Restricted netdata.domain.co.uk"`

getting charts works fine.

`https://netdata.domain.co.uk/api/v1/chart?chart=system.cpu&_=1540306318539`

I'm running nginx in a docker container with 'dashboard.js', 'custom.html' and 'dashboard.slate.css' in the root. With netdata in docker container. At a bit of a loss what's going on

**Comment by bullno1** [comment]
Can you post your nginx configuration?

**Comment by Dec64** [comment]
`## Version 2018/08/16 - Changelog: https://github.com/linuxserver/docker-baseimage-alpine-nginx/commits/master/root/defaults/nginx.conf

user abc;
worker_processes 4;
pid /run/nginx.pid;
include /etc/nginx/modules/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	client_max_body_size 0;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# Logging Settings
	##

	access_log /config/log/nginx/access.log;
	error_log /config/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# nginx-naxsi config
	##
	# Uncomment it if you installed nginx-naxsi
	##

	#include /etc/nginx/naxsi_core.rules;

	##
	# nginx-passenger config
	##
	# Uncomment it if you installed nginx-passenger
	##

	#passenger_root /usr;
	#passenger_ruby /usr/bin/ruby;

	##
	# Virtual Host Configs
	##
	include /etc/nginx/conf.d/*.conf;
	include /config/nginx/site-confs/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
#
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}
daemon off;`

**Comment by Dec64** [comment]
~/site-confs/default is:

```server {
	listen 80 default_server;

	listen 443 ssl;

	root /config/www;
	index index.html index.htm index.php;

	server_name _;

	ssl_certificate /config/keys/cert.crt;
	ssl_certificate_key /config/keys/cert.key;

	client_max_body_size 0;

	location / {
		try_files $uri $uri/ /index.html /index.php?$args =404;
	}

	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		# With php5-cgi alone:
		fastcgi_pass 127.0.0.1:9000;
		# With php5-fpm:
		#fastcgi_pass unix:/var/run/php5-fpm.sock;
		fastcgi_index index.php;
		include /etc/nginx/fastcgi_params;

	}
        # CUSTOM NETDATA
        location /netdata {
        #auth_request /auth-user;
        root /config/www/;
        index custom.html;
}
}```

**Comment by bullno1** [comment]
If I understand correctly, authentication is handled by `/auth-user` in your PHP. That is where the problem is. Does it use password or cookie?

Try inspecting and diffing the 200 vs 400 requests to see if they contain the same set of headers?

**Comment by bullno1** [comment]
Please ignore my previous deleted comment.

Which port are you running netdata on? There is nothing in that config that seems to point to it.
The config should be something like this: https://github.com/netdata/netdata/wiki/Running-behind-nginx

**Comment by Dec64** [comment]
uses user/password auth i think, which it does pop up and ask for. The obvious different between chart api call and data api call is the request headers on Data is not sending cookies. I assume this is the issue?

**Comment by bullno1** [comment]
@Dec64 deleted and repost because I made a mistake.

Is netdata on port 19999 or 9000? It's just a http server, not fastcgi.

**Comment by Dec64** [comment]
@bullno1 
Running in a docker container, still on 19999 though. All passed thru nginx-proxy docker container for reverse proxy

**Comment by bullno1** [comment]
So what is the file that forward request to port 19999? If you use some sort of config generator, can you get the generated config file?

**Comment by Dec64** [comment]
Honestly, unsure about how it works but there is no config you start the docker container with ```docker run -e VIRTUAL_HOST=foo.bar.com``` and it set's it up for you.

[https://github.com/jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy)

```

VIRTUAL_PORT | 19999
-- | --
LETSENCRYPT_HOST | netdata.domain.co.uk
LETSENCRYPT_EMAIL | admin@domain.co.uk
VIRTUAL_HOST | netdata.domain.co.uk
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NETDATA_PORT | 19999
SMTP_TLS | on
SMTP_STARTTLS | on
SMTP_SERVER | smtp.gmail.com
SMTP_PORT | 587
SMTP_FROM | localhost
```

**Comment by bullno1** [comment]
It will generate the config file, you just have to `docker exec` into it and dig it out.

**Comment by Dec64** [comment]
yeah but it holds no direct mention of any of the reverse proxys.

this is nginx.conf from the proxy container

```user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
daemon off;```

**Comment by Dec64** [comment]
never mind, I found the section in question

```# netdata.domain.co.uk
upstream netdata.domain.co.uk {
				## Can be connected with "cloudbox" network
			# netdata
			server x.x.x.x:19999;
}
server {
	server_name netdata.domain.co.uk;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name netdata.domain.co.uk;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
	ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/netdata.domain.co.uk.crt;
	ssl_certificate_key /etc/nginx/certs/netdata.domain.co.uk.key;
	ssl_dhparam /etc/nginx/certs/netdata.domain.co.uk.dhparam.pem;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/nginx/certs/netdata.domain.co.uk.chain.pem;
	add_header Strict-Transport-Security "max-age=31536000" always;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://netdata.domain.co.uk;
		auth_basic	"Restricted netdata.domain.co.uk";
		auth_basic_user_file	/etc/nginx/htpasswd/netdata.domain.co.uk;
	}
}```

**Comment by bullno1** [comment]
Nothing seems wrong with this.

For basic auth, you only need the `Authorization` header and browser will cache that after you get a 200 anyway. If both the 200 and 401 requests have the same `Authorization` headers then the problem is server-side.

nginx can default to 401 if it cannot read the password file so try checking if you can `cat /etc/nginx/htpasswd/netdata.domain.co.uk` from inside the nginx container.

**Comment by Dec64** [comment]
`cat /opt/nginx-proxy/htpasswd/netdata.domain.co.uk` returns data so that's all fine.

Data request that gets rejected's headers:

```:authority: netdata.domain.co.uk
:method: OPTIONS
:path: /api/v1/data?chart=system.io&format=array&points=300&group=average&gtime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-300&dimensions=out&_=1540463406080
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
access-control-request-headers: cache-control,pragma
access-control-request-method: GET
origin: https://web.domain.co.uk
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36```


Chart request that gets accepted:

```:authority: netdata.domain.co.uk
:method: GET
:path: /api/v1/chart?chart=system.ram&_=1540463588125
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
authorization: Basic xxxxxxxxxx==
cookie: some data
origin: https://web.domain.co.uk
referer: https://web.domain.co.uk/netdata/custom.html
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36```

**Comment by bullno1** [comment]
There's a cross domain request here. Not sure about netdata internal but you need to send credentials along with the preflight request. And I'm also not sure if netdata responses to `OPTIONS`.

Check their javascript or something. Can you host the custom.html in the same domain?

**Comment by cakrit** [comment]
I think that the trouble starts with this:
> I'm running nginx in a docker container with 'dashboard.js', 'custom.html' and 'dashboard.slate.css' in the root

You're essentially trying to do two things at the same time:
- Create a small "site" that contains your custom dashboard and serve it via nginx.
- Proxy netdata via nginx

I'm sure it can be done with careful nginx configuration, but for this use case, I'd just put the custom.html under the netdata web directory (i.e. where dashboard.js and tv.html are). That's because you seem to want the exact same access rights and URL, so it makes little sense to put that custom dashboard elsewhere. This will greatly simplify things and I'm sure it will resolve your issue.
