### ISSUE TITLE
Logcheck security alert: netdata : command not allowed ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=validate

### ISSUE THREAD

**Issue by lichtamberg** [netdata/netdata#4473]
3 hours ago nearly all of our servers produced a security alert, which contained following information:

`
Oct 24 06:25:50 : netdata : command not allowed ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=validate
`
Since I'm pretty sure our servers haven't been hacked, I think it's more a bug somehow? 
Did netdata update itself and try to execute something with sudo? Any hints appreciated.

Our netdata configuration has not been changed in the last weeks/months, so I'm a bit curious why this happens now?

**Comment by ktsaou** [comment]
Probably your netdata was updated and restarted.

A few netdata plugins execute a `sudo` with validate option to check if they can collect data.

This is needed for:

```sh
# grep -l sudo $(find collectors -name \*.py -o -name \*.js -o -name \*.sh)
collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py
collectors/python.d.plugin/samba/samba.chart.py
collectors/python.d.plugin/megacli/megacli.chart.py
collectors/charts.d.plugin/libreswan/libreswan.chart.sh
```

The adaptec module was added yesterday. So, you probably have netdata auto-updated via cron, it updated itself yesterday and the new adaptec module tried to see if it is able to run.

If you don't want this autodetection, you can disable the `adaptec` plugin by editing `python.d.conf` using `/etc/netdata/edit-config python.d.conf`.

@l2isbad I suggest all plugins that require `sudo` to be disabled by default. So, they should run only if the user has explicitly enabled them. Another solution could be to check something else before running `sudo`. For example, libreswan checks that the command `ipsec` is available before running it: https://github.com/netdata/netdata/blob/e5aca2581e137337f384dc5d48ae86593b808bd3/collectors/charts.d.plugin/libreswan/libreswan.chart.sh#L87

Could you please do this?

**Comment by ktsaou** [comment]
I marked this a bug. We should fix this. It is not nice for people to receive such alerts without being aware of why this is needed, or without being obvious that they would need to allow `sudo` for netdata data collection modules.

**Comment by ktsaou** [comment]
Also the adaptec module page does not say anything about this: https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/adaptec_raid

It should state this plugin needs `sudo` and it should also provide detailed instructions for enabling `sudo` just for the command needed, to help people do it in the safest way.

@l2isbad please fix this too.

**Comment by ktsaou** [comment]
@lichtamberg 	thank you for reporting this!

**Comment by l2isbad** [comment]
> It should state this plugin needs sudo and it should also provide detailed instructions for enabling sudo just for the command needed, to help people do it in the safest way.

in README
> Requirements:
> netdata user needs to be able to sudo the arcconf program without password

in conf
https://github.com/netdata/netdata/blob/866170672aee2c6dbeed5f79caf18755d850c32c/collectors/python.d.plugin/adaptec_raid/adaptec_raid.conf#L57-L59

**Comment by lichtamberg** [comment]
Not sure how to proceed here, getting security warnings due to auto updates is a bit concerning... Maybe my only option is to disable the updates at all.. :/

**Comment by ktsaou** [comment]
Merged the fix.

> Not sure how to proceed here, getting security warnings due to auto updates is a bit concerning... Maybe my only option is to disable the updates at all.. :/

Well... either you want automatic updates, or your don't.
Generally we try hard to have a workflow that will prevent "accidents" (code reviews, automated tests, etc).

But yes, we add features and fix issues every day... netdata evolves...

This also has the opposite effect. We also fix security related issues. You should generally want get these updates...

So, it is up to you to decide if you want your netdata updated or not.

**Comment by uselessfire** [comment]
This behavior is not specific to netdata, but i spend a long time to fix this, so found necessary to post solution here.
It happens when a script uses a command that in _NOPASSWD_ field of _/etc/sudoers_ and simultaneously loop sudo timeout by running `sudo -v`, which asks password by default.
According to [sudoers manual](https://www.sudo.ws/man/1.8.0/sudoers.man.html#verifypw) we can add `Defaults verifypw = any` to _/etc/sudoers_ and it prevents sudo to ask password during `sudo -v` when the script uses commands from _NOPASSWD_.

**Comment by prologic** [comment]
@joelhans ☝️Are you able to put this somewhere in our docs?

**Comment by ilyam8** [comment]
Some modules do `sudo -n -v` and it seems is not a good way to check if module is able to use sudo, better check is `sudo -n -l COMMAND`. And we need to replace all `-n -v` checks with `-n -l COMMAND`.

___

`sudo -n -v` example

https://github.com/netdata/netdata/blob/d5d1865469b63385d70645f710728482aed0f23d/collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py#L166-L174

`sudo -n -l COMMAND` example

https://github.com/netdata/netdata/blob/d5d1865469b63385d70645f710728482aed0f23d/collectors/python.d.plugin/samba/samba.chart.py#L120-L125

**Comment by prologic** [comment]
I agree with @illes 

```
       -l, --list  If no command is specified, list the allowed (and forbidden) commands for the invoking user (or the user specified by the -U
                   option) on the current host.  A longer list format is used if this option is specified multiple times and the security policy
                   supports a verbose output format.

                   If a command is specified and is permitted by the security policy, the fully-qualified path to the command is displayed along
                   with any command line arguments.  If a command is specified but not allowed by the policy, sudo will exit with a status value
                   of 1.
```

I wasn't actually aware of the `-l` option. @Ferroin I _think_ this is something we can fix globally everywhere. What do you think?
