### ISSUE TITLE
Need some help with using /etc/netdata/edit-config

### ISSUE THREAD

**Issue by ovizii** [netdata/netdata#4475]
##### Question summary
I found the explanation here: https://github.com/netdata/netdata/tree/master/health 

I quote:

> Stock netdata health configuration is in /usr/lib/netdata/conf.d/health.d. These files can be overwritten by copying them and editing them in /etc/netdata/health.d (run /etc/netdata/edit-config to edit them).
> 
> In /etc/netdata/health.d you can also put any number of files (in any number of sub-directories) with a suffix .conf to have them processed by netdata.

##### OS / Environment
Debian 9, latest Netdata installed per installation instructions.

How do I use /etc/netdata/edit-config?

here is what I expected but the result differs. I want to customize RAM warnings so: 
`cp /usr/lib/netdata/conf.d/health.d/ram.conf /etc/netdata/health.d/` 

without parameters, I see a list of all available .conf files:
```
/etc/netdata/edit-config

USAGE:
  /etc/netdata/edit-config FILENAME

  Copy and edit the stock config file named: FILENAME
  if FILENAME is already copied, it will be edited as-is.

  The EDITOR shell variable is used to define the editor to be used.

  Stock config files at: '/usr/lib/netdata/conf.d'
  User  config files at: '/etc/netdata'

  Available files in '/usr/lib/netdata/conf.d' to copy and edit:

```

so I tried: 
```
/etc/netdata/edit-config ram.conf
File 'ram.conf' is not found in '/usr/lib/netdata/conf.d'
```

do I need to do: 
` /etc/netdata/edit-config health.d/ram.conf`

or rather 
` /etc/netdata/edit-config /etc/netdata/health.d/ram.conf`

**Comment by Ferroin** [comment]
It should just be the path relative to the configuration directory, so in your case:

    /etc/netdata/edit-config health.d/ram.conf

**Comment by ovizii** [comment]
Thanks!
