### ISSUE TITLE
Measuring and displaying data in the sub-second range

### ISSUE THREAD

**Issue by koppi** [netdata/netdata#449]
Hi @ktsaou, thank's for netdata.

I have a CNC mill which is driven by [LinuxCNC](http://linuxcnc.org/) / [Machinekit](http://www.machinekit.io/). There are [about 50 real-time process values](https://github.com/koppi/mk/blob/master/Machinekit-Xenomai-Thinkpad-X200.md#hal-graph-visualisierung) I want to visualize. These process values get generated at a rate of 20kHz and the measurement (with min, max and avg calculations) happens at a rate of 1kHz.

I'm currently using Grafana:
![Graphana on Machinekit](https://raw.githubusercontent.com/koppi/mk/master/pics/20150607-001.png)
But unfortunately Grafana does not (yet?) support visualization of sub-seconds measuring intervals, too.

I'd like to record and stream those real-time measurement values via netdata and make some nice rrd graphs. – Is this possible with the current netdata release? – Or can you point me to the relevant source code locations to make this high measurement rate possible in the rrd and plugins codebase?

**Comment by ktsaou** [comment]
wow! and I thought netdata had too much data!

Well, what exactly is your need? Measure it 1000 times per second? Visualize it with that detail?

Probably what is best for your case is this:

1. Measure it as frequent as you like, 1.000/sec, 10.000/sec, does not matter. You just need to write a plugin to collect the values at this frequency.

2. Every second calculate:

  - the average per second
  - the minimum per second
  - the maximum per second
  - the standard deviation per second (https://en.wikipedia.org/wiki/Standard_deviation)

  Then visualize per second these four metrics per motor. Having these four metrics should enough for knowing what is happening at millisecond level.

If you still want to have millisecond detail in the data, you could adapt netdata to do it, but it would require some work. It might actually be quite simple to do it (there is an `update_every` variable in the code that we have assumed it is `seconds` - we could assume it is `milliseconds` and adapt all its uses to reflect that - but this is somewhat niche to be done in the standard netdata code).

**Comment by koppi** [comment]
I'm already doing a ```min```, ```max``` and ```avg``` calculation in a realtime kernel module (– this happens at a rate of 20kHz – so the 1kHz values are aleady interpolated), see: [[1](https://github.com/koppi/mk/blob/master/linuxcnc/configs/koppi-cnc/ownanalytics.icomp)], [[2](https://www.youtube.com/watch?v=NuxXcNMVCuM)] and [[3](https://www.youtube.com/watch?v=Aq9YJkyT15E)]. So right now in netdata the ```update_every``` variable is ```int``` and assumed to be ```seconds```.

What do you think is simpler / cleaner?
  * **1** – Turn ```update_every``` from ```int``` into ```double``` and allow fractions of a second (```0.1```, ```0.01```, etc.).
  * **2** – Don't change the type of ```update_every``` but assume ```update_every``` not to be ```seconds``` but ```milliseconds``` and change all plugin code accordingly.

**1** or **2** ?

**Comment by ktsaou** [comment]
I think 2 is a lot more simpler.

netdata internally interpolates values at second boundary using nanosecond operations. it is much simpler to assume `update_every` is milliseconds and change the divider from 1.000.000 (second -> nanosecond) to 1.000 (millisecond -> nanosecond).

netdata also has reduce functions embedded (today, although the data are per second, charts can be rendered per 2 seconds, or per minute or whatever), so the default view could remain per second with the ability to zoom-in up to millisecond detail.

Of course these require some work and you have to know C, but it is doable.

**Comment by ktsaou** [comment]
added a few more info in my last response.

**Comment by ktsaou** [comment]
Actually, the fact that all internal operations of netdata are already at nanosecond, makes me think that I would accept a PR that properly uses a configuration variable for the detail required, in nanoseconds.

So, we could assume that today `database detail = 1000000`. If you properly adapt all the calculations and `dashboard.js` to work with `database detail = 1000`, I would accept to merge it in netdata.

**Comment by koppi** [comment]
I need some more help to get started with the coding of this.

Can you put together a list of files that need to be changed or create a quick branch to get me started with writing code for this feature? So far I have found:

* https://github.com/firehol/netdata/blob/master/src/rrd.h#L285
* https://github.com/firehol/netdata/blob/master/src/rrd.c#L784-L808

Where do I need to dd the ```database detail``` setting in the code?

**Comment by gandavar** [comment]
Any update on this issue?

**Comment by koppi** [comment]
@gandavar, I did'nt have any time / expertise to modify the source code to implement this feature. If you or @ktsaou could help out I'd be very happy to test and give feedback.

**Comment by ktsaou** [comment]
Well, if you have the time to do it, I can help.

But please don't expect this to be implemented by me. Unfortunately, this is niche and not a priority for me (actually, I don't need it anywhere).

So, if you are prepared to read and understand the code, and make changes to it towards this direction, I can help (and I can maintain it in future releases). But you will have spend enough hours on it to make it happen. If you don't plan to give it enough time, it would be better for all of us to wait until someone is prepared to do it.

**Comment by youngker** [comment]
Hi all
Here is the millisecond support version.
https://github.com/youngker/netdata4android/commit/fd360ed270ad083deb987f05acdcb57587a37953

@ktsaou but I can not pass unittest14c, could you give me some advice?
```    
    test14c stored 8 entries, but we were expecting 9, ### E R R O R ###
    test14c/dim1: checking position 1 (at 28249111 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 2 (at 58249111 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 3 (at 88249111 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 4 (at 118249111 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 5 (at 148249111 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 6 (at 178249111 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 7 (at 208249111 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 8 (at 238249111 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
```

**Comment by ktsaou** [comment]
wow! nice!

I compile with this:

```sh
CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1" ./netdata-installer.sh
```

Once you do this, you get additional error and info line logged. This is unit test 14c with the latest commit on netdata:


```sh
# ./src/netdata -W unittest

Running test 'test14c':
issue #981 with dummy data, checking for late start
    > test14c: feeding position 1
       >> dim1 with value 29000000
2016-12-11 14:29:49: netdata: INFO: netdata.unittest_test14c is collected in the same interpolation point: short by 29500000 microseconds
    > test14c: fixing first collection time to be 29000000 microseconds to second boundary
    > test14c: feeding position 2, after 1.000 seconds (1.000 seconds from start), delta 1000000.0000000, rate 1000000.0000000
       >> dim1 with value 30000000
    > test14c: feeding position 3, after 30.000 seconds (31.000 seconds from start), delta 30000000.0000000, rate 1000000.0000000
       >> dim1 with value 60000000
    > test14c: feeding position 4, after 30.000 seconds (61.000 seconds from start), delta 30000000.0000000, rate 1000000.0000000
       >> dim1 with value 90000000
    > test14c: feeding position 5, after 30.000 seconds (91.000 seconds from start), delta 30000000.0000000, rate 1000000.0000000
       >> dim1 with value 120000000
    > test14c: feeding position 6, after 30.000 seconds (121.000 seconds from start), delta 30000000.0000000, rate 1000000.0000000
       >> dim1 with value 150000000
    > test14c: feeding position 7, after 30.000 seconds (151.000 seconds from start), delta 30000000.0000000, rate 1000000.0000000
       >> dim1 with value 180000000
    > test14c: feeding position 8, after 30.000 seconds (181.000 seconds from start), delta 30000000.0000000, rate 1000000.0000000
       >> dim1 with value 210000000
    > test14c: feeding position 9, after 30.000 seconds (211.000 seconds from start), delta 30000000.0000000, rate 1000000.0000000
       >> dim1 with value 240000000
    > test14c: feeding position 10, after 30.000 seconds (241.000 seconds from start), delta 30000000.0000000, rate 1000000.0000000
       >> dim1 with value 270000000
    test14c/dim1: checking position 1 (at 18446744073709551597 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 2 (at 11 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 3 (at 41 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 4 (at 71 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 5 (at 101 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 6 (at 131 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 7 (at 161 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 8 (at 191 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
    test14c/dim1: checking position 9 (at 221 secs), expecting value 1000000.0000000, found 1000000.0000000, OK
```

Can you print the whole of it on your version?

**Comment by ktsaou** [comment]
Keep in mind PR #1313 is almost ready to be merged (probably will be merged today). It will break quite a few of your changes (if not all). Sorry for that...

Also, it would really be helpful, to invite @rlefevre too to review your changes, so it might be best to wait for #1313 to be merged and then create a PR.

**Comment by paulfantom** [comment]
Is this still on our roadmap?

**Comment by paulfantom** [comment]
--sort-ascending

**Comment by cakrit** [comment]
Sub-second is still on the roadmap, I'm just not sure if we have a duplicate somewhere.

**Comment by ridwannaibi** [comment]
@ktsaou I need sub-second polling. I am using netdata to collect metrics in my project, however, I lack the expertise required but I am willing to put in the hours to level up. I can see that you are willing to offer help with directions.   Can you still offer help ?

**Comment by paulfantom** [comment]
@ridwannaibi you can have this already with [telegraf](https://github.com/influxdata/telegraf) (as a collector), [InfluxDB](https://github.com/influxdata/influxdb) (as a store), and grafana or [chronograph](https://github.com/influxdata/chronograf) (as a display). All those support millisecond precission.

**Comment by ridwannaibi** [comment]
@paulfantom Thank you

**Comment by lab-w** [comment]
I'm also interested in displaying measurements with millisecond / sub-millisecond granularity. netdata is a great framework and I really would like to use it for live-plotting of my data too. Am I right that this is still not possible with netdata?
Before trying to fix it on my own I'd like to know if there's anyone else working on this already. What happened to the code by @youngker? Is there a plan to merge this to netdata?

**Comment by thiagoftsm** [comment]
Hi @lab-w ,

Netdata right now works with second granularity, but in the last release 1.20 we started to work with eBPF that will help us to move in the direction to have milliseconds or microseconds granularity. 

For sure it is in our plan for the future to reduce this granularity level.

Best regards!

**Comment by lab-w** [comment]
Hi @thiagoftsm ,

thank you for your answer. Is currently the measurement frequency equal to the update frequency in the browser or can I set it to different rates? If I try to modify the current version to measure with sub-millisecond resolution I don't want to refresh the graph in the browser with that rate to reduce system load. My plan is to measure every 500 us and update the live graph in the browser every second with 2000 new values (1 second / 500 us). Do you think this is possible with moderate modifications in the source code?

Best regards.

**Comment by thiagoftsm** [comment]
Hi @lab-w ,

I will give some tips for you here, but I never tested this before. I am giving these tips based in the previous knowledge that I have when I wrote few collectors.
The minor value that you can set on netdata.conf is 1 second (https://docs.netdata.cloud/docs/configuration-guide/#reduce-the-data-collection-frequency ) in normal situation this is controlled because we multiply this default second for the default value `USEC_PER_SEC`, but this variable probably does not affect only the collectors. 
About the browser resolution, this is something that I cannot answer. @jacekkolasa is there any possibility of the browser time resolution to be different of the data collection resolution?

Best regards!

**Comment by cakrit** [comment]
It won't be moderate configuration if we are to store and graph data at this resolution, it needs work on multiple parts of the daemon, especially if we try to go below 1msec. I believe @ktsaou started on it a while back, but it hasn't been a priority and the code has moved significantly since.

I believe we'd need significant interest in this, before we talk seriously about doing it.

**Comment by lab-w** [comment]
Thanks @cakrit and @thiagoftsm , think you are right that there are some more things to change...

Anyway, since I still need a sub-millisecond data visualisation I've tried in a first step to test if it is possible to feed that much data into the database - fast enough.
In my test I've used a bash plugin (charts.d) that is updated every second. in the update function I call a c programm that prints 10000 times the "BEGIN ... END" statement to stdout. That way it was possible to feed every second 10000 data points to a graph (not with the right time label - but anyway). One issue with this kind of database interface is the enourmous overhead that limits the update rate. Is that currently the only interface to get the data from a plugin inside the netdata database?

**Comment by mfundul** [comment]
Right now the only interface to get data from a plugin is the text protocol of the `Plugins.D` language which also has to go through a pipe. As a result, the overhead is what it is.

The other way to interact with the database is to write a native collector, that does not have to go through this interface. You can check out the `/proc` collectors or the `statsd` collector. This is bound to be much faster.

**Comment by lab-w** [comment]
Thanks @mfundul , I'll check that out.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
