### ISSUE TITLE
Diskspace plugin accesses excluded filesystem and stalls netdata process

### ISSUE THREAD

**Issue by mind-code** [netdata/netdata#4491]
##### Bug report summary
Netdata, more precicly the diskspace plugin, tries to stat() a mountpoint I explicitly try it not to touch at all.

We already had a simmilar problem in the past -> https://github.com/netdata/netdata/issues/1834

I have a cifs,kerberized, multiuser mount:

**/etc/fstab**
`//dfspath   /mnt/test  cifs  _netdev,noauto,x-systemd.automount,x-systemd.idle-timeout=10,sec=krb5i,multiuser,noserverino,vers=3.02  0   0`

The works perfectly, but each accessing process needs a kerberos ticket valid for the uid of that process. The netdata process obviously does not posess such a ticket. I dont need statistics for this mount and want netdata to just ignore it.

The parameters **exclude space metrics on filesystems** and **exclude space metrics on paths** dont seem to block all stat() requests. When nobody has accessed the mountpoint everything is fine, but once somebody has accessed it sooner or later a netdata process with uid 999 wants to stat() the mount:

**journalctl output**
```
Oct 25 17:44:16 servername cifs.upcall[2290]: key description: cifs.spnego;0;0;39010000;ver=0x2;host=DFSROOT01;ip4=10.15.144.193;sec=krb5;uid=0x3e7;creduid=0x3e7;pid=0              x432
Oct 25 17:44:16 servername cifs.upcall[2290]: ver=2
Oct 25 17:44:16 servername cifs.upcall[2290]: host=DFSSERVERNAME
Oct 25 17:44:16 servername cifs.upcall[2290]: ip=xxx.xxx.xxx.xxx
Oct 25 17:44:16 servername cifs.upcall[2290]: sec=1
Oct 25 17:44:16 servername cifs.upcall[2290]: uid=999
Oct 25 17:44:16 servername cifs.upcall[2290]: creduid=999
Oct 25 17:44:16 servername cifs.upcall[2290]: pid=1074
Oct 25 17:44:16 servername cifs.upcall[2290]: get_cachename_from_process_env: pathname=/proc/1074/environ
Oct 25 17:44:16 servername cifs.upcall[2290]: get_existing_cc: default ccache is FILE:/tmp/krb5cc_999
Oct 25 17:44:16 servername cifs.upcall[2290]: get_tgt_time: unable to get principal
Oct 25 17:44:16 servername cifs.upcall[2290]: Exit status 1
Oct 25 17:44:17 servername kernel: CIFS VFS: Send error in SessSetup = -126
```

I added /mnt/* to exclude space metrics on paths and cifs to exclude space metrics on filesystems, but nothing works. Its definetly the diskspace plugin, because once its deactivated the behavious dissappears. Once this attempted access happens one of the netdata threads is using 100% and will become a Zombie upon netdata restart.

**/proc/mounts after boot and untriggered mount**
```
systemd-1 /mnt/test autofs rw,relatime,fd=29,pgrp=1,timeout=10,minproto=5,maxproto=5,direct,pipe_ino=12003 0 0
```

**/proc/mounts once its triggered**
```
systemd-1 /mnt/test autofs rw,relatime,fd=29,pgrp=1,timeout=10,minproto=5,maxproto=5,direct,pipe_ino=12003 0 0
//cifspath /mnt/test cifs rw,relatime,vers=3.02,sec=krb5i,cache=strict,multiuser,uid=0,noforceuid,gid=0,noforcegid,addr=10.15.144.193,file_mode=0755,dir_mode=0755,soft,nounix,mapposix,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1 0 0
... (multiple more like the line above, its a DFS tree and if a subfolder is on a different fileserver it gets a differnt mount)
```

If the mount is already triggered and netdata is started I get the following debug out:
`netdata[1060]: 2018-10-25 17:10:55: netdata ERROR : PLUGIN[diskspace] : DISKSPACE: Cannot stat() mount point '/mnt/test' (disk '_mnt_test', filesystem 'cifs', root '/'). (errno 13, Permission denied)`

I just noticed something. When the user triggers the mount just on the first level so (cd /mnt/test) only the 1 line appears in /proc/mountinfo like above and netdata does not appear to try to stat. Once the user starts to move in the mount and triggers cifs.upcall to mount additional mounts like:

```
//cifspath2 /mnt/test/subfolder1 cifs rw,relatime,vers=3.02,sec=krb5i,cache=strict,multiuser,uid=0,noforceuid,gid=0,noforcegid,addr=10.15.144.193,file_mode=0755,dir_mode=0755,soft,nounix,mapposix,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1 0 0
//cifspath3 /mnt/test/subfolder2 cifs rw,relatime,vers=3.02,sec=krb5i,cache=strict,multiuser,uid=0,noforceuid,gid=0,noforcegid,addr=10.15.144.193,file_mode=0755,dir_mode=0755,soft,nounix,mapposix,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1 0 0
```

then netdata appears to try to stat. Can it be, that the exception (/mnt/*) is limited to that toplevel and not recursive if happen to mount something to /mnt/test/XXX?

##### OS / Environment
Debian 9 Stretch
Kernel 4.18
VMware virtual machine

Tested with netdata 1.10.0 and current git.master

Mountpoint is a Windows DFS Tree in a Active Directory Domain.

##### Component Name
diskspace plugin

##### Expected behavior
Netdata does not stat the excluded mountpoints.

**Comment by Ferroin** [comment]
Discussion at #4107 is probably relevant here as well.

**Comment by ktsaou** [comment]
Thank you @mind-code 	for the detailed report.
Yes, this is a bug.
It is fixed with PR #4494

**Comment by ktsaou** [comment]
Merged the fix.

**Comment by mind-code** [comment]
I can confirm this fixes the issue.

Thank you for your quick work!
