### ISSUE TITLE
How to configure Alarms,Charts and Email-notification

### ISSUE THREAD

**Issue by Charanjet** [netdata/netdata#4499]
##### Question summary
How to set alarm,Charts and Email-notification

##### OS / Environment
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1069-aws x86_64 );
installed netdata from git clone https://github.com/firehol/netdata.git --depth=1

##### Component Name
Thanks for providing us a good tool like Netdata and giving time for my message. I am facing some problems, please provide me the solution or let me know what I am missing:

1. When I restarts the netdata service, al the default alarms get removed. I tried giving full permissions to files etc but it did not help.
2. I followed following links to add new alarms but those are not working for me. Means those are not showing up in netdata dashboard. 
-https://github.com/netdata/netdata/wiki/email-notifications
-https://github.com/netdata/netdata/wiki/health-configuration-reference#alarm-actions
-https://github.com/netdata/netdata/wiki/alarm-notifications
3.How I can configure Netdata to send email alerts automatically.
-https://github.com/netdata/netdata/wiki/email-notifications 
4. If you can point me to some documents where it tells how to add and configure charts and alarms, will really be helpful.

##### Expected results
Setting Alarms to Nginx,PHPfpm and sql.Showing charts for these in dashboard.Sending these alarms to email.

**Comment by Charanjet** [comment]
Thanks @gmosx ,
Please help me it is urgently needed to configure netdata

**Comment by ritzzbv** [comment]
@Charanjet Can you check your netdata.conf present in /etc/netdata folder.
Check for enable = yes under [health]
Make sure it's not disabled from there.

**Comment by Charanjet** [comment]
now i only need to help how to create an alarm for nginx,mysql and phpfpm charts not required please let me know how i can do this

**Comment by ritzzbv** [comment]
@Charanjet 
1. There is not need to copy contents from github. You can find all the files related to netdata under /usr/lib/netdata/ once edit any config, then that file will be moved to /etc/netdata.

2. For nginx,mysql and any other services mostly health.d picks it up normally. Moreover if it does not then copy /usr/lib/netdata/health.d/* to /etc/netdata/health.d/

3. Edit this file /etc/netdata/health_alarm_notify.conf to configure notification systems.

Make sure you restart the netdata after `killall netdata`

**Comment by Charanjet** [comment]
Please help me how to create an alarm from scratch . I have opened /etc/netdata/health_alarm_notify.conf  what to do next to create alarm for mysql

**Comment by cakrit** [comment]
Please go through https://github.com/netdata/netdata/tree/master/health/README.md and reopen if you still can't do it after that.

**Comment by Charanjet** [comment]
Hey @ritzzbv Please help me.Can you give me code for one alarm of nginx,phpfpm or mysql.

**Comment by ritzzbv** [comment]
@Charanjet  Mostly you dont need much changes for alarms. Netdata by dafault picks up services like nginx and MySQL.
For mysql If you are running netdata as netdata user please check permission for this user.
check this issue: https://github.com/netdata/netdata/issues/3158

**Comment by Charanjet** [comment]
I just restarted the netdata service and its all default alarms get disabled.Why?
