### ISSUE TITLE
Remove that = this hacks

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#4514]
`let that = this` hacks are not needed any more.

Modern javascript supports lexical scoping (let, arrow functions).

In general, you can replace code like:

```
const that = this;

const f = function (param) {
   ...
   that.value = param
};
```

with

```
const f = (param) => {
    ...
    this.value = param;
};
```

**Comment by gmosx** [comment]
This is quite difficult to refactor in the current state of dashboard.js Spent quite some time today, but got some random issues. I will postpone this issue for the moment. The alternative is to work on this incrementally, as I did in timeout.js 

@ktsaou what do you think?

**Comment by ilyam8** [comment]
Not relevant anymore
