### ISSUE TITLE
Remove dependency on jQuery

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#4517]
Most of the functionality we use is provided in all modern browsers (e.g. document.querySelector()).

**Comment by ktsaou** [comment]
hm... you have to check the chart libraries requirements though. I think a few of them may need it...

**Comment by gmosx** [comment]
Good point. In any case, this is for the mid-term.

**Comment by gmosx** [comment]
We will not remove the dependency, it's used all over the place.
