### ISSUE TITLE
Support duplicate dimension names

### ISSUE THREAD

**Issue by agross** [netdata/netdata#4520]
##### Bug report summary

I use snmp.conf's `oidname` support to pull dimension names from the SNMP server. In my case it's disks installed in a NAS device. I have multiple disks of the same model, so dimension names are duplicated while dimension IDs (?) are not:

```sh
$ /usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp
...
CHART "Sensors.disk-temperatures" "Sensors.disk-temperatures" "Disk temperatures" "Celsius" "Disk temperatures" "" "line" 50002 10
DIMENSION "disk1" "ST10000VN0004-1ZD101    " "absolute" 1 1
DIMENSION "disk2" "ST10000VN0004-1ZD101    " "absolute" 1 1
DIMENSION "disk3" "ST12000VN0007-2GS116    " "absolute" 1 1
DIMENSION "disk4" "ST10000VN0004-1ZD101    " "absolute" 1 1
DIMENSION "disk5" "ST10000VN0004-1ZD101    " "absolute" 1 1
DIMENSION "disk6" "ST10000VN0004-1ZD101    " "absolute" 1 1
DIMENSION "disk7" "ST12000VN0007-2GS116    " "absolute" 1 1
DIMENSION "disk8" "ST12000VN0007-2GS116    " "absolute" 1 1
DIMENSION "disk9" "ST12000VN0007-2GS116    " "absolute" 1 1
DIMENSION "disk10" "ST12000VN0007-2GS116    " "absolute" 1 1
DIMENSION "disk11" "ST12000VN0007-2GS116    " "absolute" 1 1
DIMENSION "disk12" "ST10000VN0004-1ZD101    " "absolute" 1 1
...
```

Data is then reported as belonging to `disk1` to `disk12` (= dimension IDs):

```
BEGIN Sensors.disk-temperatures
SET disk1 = 34
SET disk2 = 33
SET disk3 = 35
SET disk4 = 34
```

On the netdata dashboard, only two dimensions are shown. It seems that the data is associated by dimension name, not by dimension ID. As my SNMP server has two types of disk models I only see 2 dimensions instead of 12.

<img width="288" alt="2018-10-29_22-13-20" src="https://user-images.githubusercontent.com/16245/47680730-fdede000-dbc7-11e8-9720-2a7fc8665632.png">

https://netdata.home.therightstuff.de/#menu_Sensors_submenu_System_temperature;theme=slate;help=true;update_always=true

##### OS / Environment
Fedora 28

##### Component Name
netdata dashboard and/or daemon as per https://github.com/netdata/netdata/issues/4512#issuecomment-434079049

##### Steps To Reproduce
Create snmp.conf with duplicate `oidname` for more than one dimension.

##### Expected behavior

Dimension values are displayed for all dimensions, not grouped by name.

**Comment by paulfantom** [comment]
This is the same as #2293. Closing as a duplicate
