### ISSUE TITLE
Multiple postgres connections and its metrics

### ISSUE THREAD

**Issue by marcosmamg** [netdata/netdata#4522]
To access the catalogs for each individual database in my cluster I need to specify individual connections in `postgres.conf` and I already did it.
```
Connections can be configured with the following options:
     database    : 'example_db_name'
     user        : 'example_user'
     password    : 'example_pass'
     host        : 'localhost'
     port        : 5432
```
and then I've been playing around on `/plugins.d/postgres.chart.py` but it might be that I am missing something else or doing something wrong, because my chart/metric is not showing on the dashboard. Is there any documentation to extend the postgres metrics to add metrics for specific databases? I will be querying data and sending alerts depending on results.

Thanks for your help and the great job.

**Comment by cakrit** [comment]
@ilyam8 can you help with this?

**Comment by ilyam8** [comment]
Hi @marcosmamg 

>and then I've been playing around on /plugins.d/postgres.chart.py but it might be that I am missing something else or doing something wrong, because my chart/metric is not showing on the dashboard.

What do you mean by `playing`? Did you modify `postgres` module?

I see some stats are disabled by default in configuration file

https://github.com/netdata/netdata/blob/01e2f26c2981b583fb6c749b7e1ae14d97e0e6c8/collectors/python.d.plugin/postgres/postgres.conf#L72-L75

Besides that there is no way to add metrics.

> Is there any documentation to extend the postgres metrics to add metrics for specific databases? I will be querying data and sending alerts depending on results.

This sounds like a custom query support. I may be wrong. @anayrat please help me on this too.

**Comment by anayrat** [comment]
> > Is there any documentation to extend the postgres metrics to add metrics for specific databases? I will be querying data and sending alerts depending on results.

> This sounds like a custom query support. I may be wrong. @anayrat please help me on this too.

Yes, it is like custom query. It could be an interesting feature to add. For example a directory `custom_metric.d` containing configuration files for custom metrics.

**Comment by ilyam8** [comment]
> This sounds like a custom query support. 
> Yes, it is like custom query.


@marcosmamg 

Did we understand you correctly?

**Comment by marcosmamg** [comment]
Hello @ilyam8 and @anayrat that is exactly what I need, I want to be able to create custom queries to create my own metrics/alerts based on the info I get to extract.

Thanks for your help.
