### ISSUE TITLE
Simplify makeself

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4527]
##### Feature idea summary

Reduce codebase for makeself and move makeself to `packaging` directory.

##### Expected behavior

1. `makeself` dir exists as a subdir of `packaging`
2. `makeself` consists of less scripts which are simpler
3. README.md in `makeself` is actually saying how this works

**Comment by Charanjet** [comment]
Hi paul can you please solve this issue 
https://github.com/netdata/netdata/issues/4499
Thanks in advance
