### ISSUE TITLE
memory footprint per metric

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4529]
##### Bug report summary

With issue #4487 	the fixes we applied with #4519 and the investigation with #4524 	we identified that health monitoring variables have significant memory footprint.

In more detail, it seems that each netdata metric needs about 3kb in memory for all the structures required by health monitoring variables.
When multiplied with tens of thousands of metrics, this increases the memory footprint of netdata significantly (several MB).

##### OS / Environment

All

##### Component Name

core

##### Steps To Reproduce

Add tens of thousands of metrics to netdata.

```yaml

```

##### Expected behavior

The metadata per metrics should be a lot less.

**Comment by vlvkobal** [comment]
## RRDDIM Memory Allocation Summary

### Database:
- 400 bytes (size of `RRDDIM` structure)
- storage numbers (in this particular case 3996 entries (1 hour and 6 minutes with 1 second updates) 4 bytes each (size of a storage number))

Total memory allocation is **16348** bytes (400 + 3996 * 4).

### Example of further memory allocations for an interrupt with `id` 9 characters long:

Target|Size|Value
---|---|---
`rd->id` | 10 bytes | 9 characters + '\0'
`rd->cache_filename` | 64 bytes |

---

4 config options are created with the total size of **177** bytes:

Target|Size|Value
---|---|---
config option name | 19 bytes | "dim `rd->id` name"
config option value | 10 bytes | "`rd->id`"
config option name | 24 bytes | "dim `rd->id` algorithm"
config option value | 12 bytes | "incremental"
config option name | 25 bytes | "dim `rd->id` multiplier"
config option value | 3 bytes | "`multiplier`""
config option name | 22 bytes | "dim `rd->id` divisor"
config option value | 2 bytes | "`divisor`"

---

3 `RRDDIMVAR` structures are created with the total allocated size of **2439** bytes:
1. `rd->last_stored_value` - 722 bytes
2. `rd->last_collected_value` - 774 bytes
3. `rd->last_collected_time.tv_sec` - 943 bytes

The size of the `RRDDIMVAR` structure is 200 bytes. Each structure has 23 pointers (184 bytes) and 2 enums (16 bytes). Additional memory allocations for each structure:

Target|Size|Value
---|---|---
rs->prefix | 1 byte | ""
rs->suffix | 1 - 18 bytes | "", "\_raw", "\_last_collected_t"
rs->key_id | 10 - 27 bytes | "`rs->prefix` `rd->id` `rs->suffix`"
rs->key_name | 10 - 27 bytes | "`rs->prefix` `rd->name` `rs->suffix`"
rs->key_fullidid | 28 - 45 bytes | "`st->id`.`rs->key_id`", where `st` is the chart (set)
rs->key_fullidname | 28 - 45 bytes | "`st->id`.`rs->key_name`"
rs->key_contextid | 28 - 45 bytes | "`st->context`.`rs->key_id`"
rs->key_contextname | 28 - 45 bytes | "`st->context`.`rs->key_name`"
rs->key_fullnameid | 28 - 45 bytes | "`st->name`.`rs->key_id`"
rs->key_fullnamename | 28 - 45 bytes | "`st->name`.`rs->key_name`"

For each `RRDDIMVAR` 10 `RRDVAR` variables are created. Actually, in this particular case memory is allocated only for 4 structures (64 bytes each). Additional allocations for variable names:

Target|Size|Value
---|---|---
var_local_id | 10 - 27 | "`rs->key_id`"
var_local_name | 0 bytes |
var_family_id | 10 - 27 bytes | "`rs->key_id`"
var_family_name | 0 bytes |
var_family_contextid | 28 - 45 bytes | "`rs->key_contextid`"
var_family_contextname | 0 bytes |
var_host_chartidid | 28 - 45 bytes | "`rs->key_fullidid`"
var_host_chartidname | 0 bytes |
var_host_chartnameid | 0 bytes |
var_host_chartnamename | 0 bytes |

**Comment by vlvkobal** [comment]
We have `id` included 38 times. So, without the `id` part all metadata allocates roughly about **2500** bytes (it depends on the chart, family, context names, etc.).

**Comment by ktsaou** [comment]
So, what you say is the we could link all variations of a `id` and `name` to `RRDDIM` and have all the variable link directly that variations without allocating them again. Right?

**Comment by Ferroin** [comment]
Answering that likely ends up being a question of how much of a performance impact there is, and how that impact scales proportionate to the number of dimensions.

**Comment by ktsaou** [comment]
> Answering that likely ends up being a question of how much of a performance impact there is, and how that impact scales proportionate to the number of dimensions.

The idea with these metadata is that we use them to improve performance, at the expense of memory. Netdata allocates all these and indexes them in AVL trees so that looking up these variables from health checks won't impact performance at all.

What I hadn't realized is that they need quite some memory. We could probably come up with a design that will need a lot less memory. We have to re-think all these structures.

**Comment by Ferroin** [comment]
Is there any kind of deduplication of these that could be done without needing logic to build the values on-demand?  Because if we're just going for reducing memory footprint that seems to me like a sensible starting point.  I don't know enough about the inner-workings of the code itself though to make any more concrete suggestions.

**Comment by GitBubble** [comment]
the ultimate solution maybe give two set of rules balanced between our trade off .  more performance or less memeory. it depends on our running host. in some low end arm architecture system we sure want the least consumption

**Comment by ktsaou** [comment]
Probably. The ideal solution though would be to use a lot less memory and also be as fast as possible.
