### ISSUE TITLE
Unable to easily determine the source of disk I/O

### ISSUE THREAD

**Issue by nakermann1973** [netdata/netdata#4532]
I am using netdata on a machine with around 20 docker containers.  

If I run iotop on the server, I can instantly see which process is causing high disk IO (and then find which container this process is in)

When using netdata, I can see the following:

High iowait:
![cpu-iowait](https://user-images.githubusercontent.com/35577878/47776922-d09e5080-dcf3-11e8-8174-eb77bbbd6b40.png)

IO on an individual block device:
![disk-io](https://user-images.githubusercontent.com/35577878/47776921-d09e5080-dcf3-11e8-9d15-851f9d406c69.png)

But I need to scroll through a long list of devices to potentially find the one which is busy:
![disks-all](https://user-images.githubusercontent.com/35577878/47776920-d09e5080-dcf3-11e8-8d69-e092dff32b27.png)

I can look at the Applications section to see what is causing the problem, but all the stats for the docker containers is aggregated into a single item "containers":
![apps-disk-read-write](https://user-images.githubusercontent.com/35577878/47776919-d09e5080-dcf3-11e8-8c16-8ec4d800bf30.png)

I would have to scroll through each individual container to find the culprit, which is tedious when there are many containers.

With that said, I have the following suggestions:

1) When presenting the realtime value table on the right side of a graph, have 3 columns: min/max/average, and allow the user to click a column header to sort the table.

2) Have a container overview section, which presents common metrics with all the containers on the same set of graphs (like CPU usage, memory usage, disk IO), so that individual containers can be compared.

**Comment by ktsaou** [comment]
Yes this is required.

**Comment by cakrit** [comment]
@vlvkobal this is a feature request for our internal collectors. Please add it to your backlog. It looks like it requires an extension of the UI as well, but let's discuss here to see how we can move it forward.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
