### ISSUE TITLE
incremental chart algorithm doesn't handle counter wrap properly

### ISSUE THREAD

**Issue by Ehekatl** [netdata/netdata#4533]
##### Bug report summary

I found this bug while using node.d snmp plugin, if I use a Counter32 value, the maximum length of the 32bit counter will be full in very short interval, and it reset to 0 after that, with current implementation this will produce 0 value on the graph. See:

![screen shot 2018-10-31 at 3 23 07 pm](https://user-images.githubusercontent.com/7362589/47784273-0b2dda80-dd40-11e8-939b-2bf47ca5c048.png)

##### Component Name

netdata core

##### Steps To Reproduce

any non-monolithically increased data on a chart with incremental algorithm should able to reproduce this

##### Expected behavior

I believe the correct implementation of incremental algorithm should drop the value if it's not monolithically increase (current value < previous value) and re-count on next data point.

**Comment by ktsaou** [comment]
I have applied a fix with PR #4538 
Can you test it?

**Comment by ktsaou** [comment]
Are you sure they are not right?
The chart is not based at 0.
It runs 700 - 900 Mbps

What is `update_every` for this? I will add a unittest to make sure netdata does this correct.

**Comment by ktsaou** [comment]
You can stop netdata and run the `node.d.plugin 1 debug snmp` by hand and post here 10-20 iterations. I'll use that data to add a unit test, and I'll also verify netdata does it right.

**Comment by Ehekatl** [comment]
@ktsaou ah...sorry for the confusion, I take a close look and found the data and graph on netdata slave is good, what I really want to present is this graph:

![screen shot 2018-11-01 at 7 07 38 pm](https://user-images.githubusercontent.com/7362589/47848940-eeaaa480-de0a-11e8-9a7e-a20c26f678b9.png)

It's from our grafana (by netdata slave -> netdata stream master -> prometheus), you can see the curve it's really wrong, so I take the screenshot from the netdata slave, without really check the axe value. 

I think the problem here is because I only upgrade  netdata slave but the query calculation was happen on netdata stream master...

Let me upgrade and see

**Comment by ktsaou** [comment]
merged the fix.
Thank you for reporting this!
