### ISSUE TITLE
Slack Notifications

### ISSUE THREAD

**Issue by rm4** [netdata/netdata#4540]
##### Question summary

netdata, slack , alarm , notification 
##### OS / Environment

ubuntu server 16.04 virtual machine vbox

##### Component Name

netdata , slack

**Comment by rm4** [comment]
![test alarm](https://user-images.githubusercontent.com/17122961/47834733-3f061000-ddd3-11e8-9d42-d1be1433a54b.PNG)

**Comment by ktsaou** [comment]
You can see the exact request and reply of slack, by following this procedure: https://github.com/netdata/netdata/tree/master/health/notifications#testing-notifications

Normally, slack will respond with a message.

**Comment by rm4** [comment]
Yes, im has been following the procedure.
But problem on my configuration in health_alarm_notify.conf just the wrong URL incoming webhook. And I so confused to find error. 
So Thanks for fast respond for answer my question. :)
