### ISSUE TITLE
move `/proc` and `/sys` python modules to `proc` plugin

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4541]
##### Feature idea summary

`python.d.plugin` should not be used for modules that collect info from `/sys` and `/proc`. These should be handled by `/proc` plugin.

The following modules can be moved:

- [x] https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/cpufreq
- [x] https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/cpuidle
- [x] https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mdstat
- [x] https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/linux_power_supply

it is very important to move the first 2 (cpufreq and cpuidle), since these are commonly found in most installations. These will help python do less work.

**Comment by Ferroin** [comment]
Regarding the cpufreq module, if you tag me for review on it, I'd be more than happy to help with testing on some non-x86 systems.  I've got a couple of ARM, PPC, and SPARC systems I can check it against (all of which are working correctly with the current python.d code).

Regarding the Linux PSU module, please make a point to tag me for review on that one so I don't miss it.  I'm actively using the python.d module on a number of systems, so I have a significant interest in making sure it keeps working.  I can also answer any questions there might be about the API it's using.

**Comment by l2isbad** [comment]
I am planning to implement #4010
Should i do it? Or it will be added to C version?

**Comment by ktsaou** [comment]
> I am planning to implement #4010
> Should i do it? Or it will be added to C version?

@vlvkobal 	can you do these?

**Comment by vlvkobal** [comment]
Yes, I can. I Assigned myself to #4010.

**Comment by vlvkobal** [comment]
Done
