### ISSUE TITLE
Can I use it in an instance of ec2 t2.small with a web server?

### ISSUE THREAD

**Issue by dertin** [netdata/netdata#4555]
What are the requirements?

What consumption of resources do you have?

The best option to install it is:
"bash <(curl -Ss https://my-netdata.io/kickstart.sh)"

Work with a daemon process, as it can be removed from the system.

##### OS / Environment
AWS EC2 t2.small
2GB RAM
Debian 9.5

**Comment by ktsaou** [comment]
yes, you can.
With default configuration expect 1-2% cpu usage of single core and about 25-30MB of ram.

**Comment by dertin** [comment]
Thanks, I'm going to try it.
