### ISSUE TITLE
Cannot update & cannot disable mail logging of events

### ISSUE THREAD

**Issue by alsoGAMER** [netdata/netdata#4557]
root@MCTime:~# /etc/cron.daily/netdata-updater 
sab  3 nov 2018, 21.51.00, CET : INFO:  Running on a terminal - (this script also supports running headless from crontab)

sab  3 nov 2018, 21.51.00, CET : INFO:  Updating netdata source from github...
error: Pulling is not possible because you have unmerged files.
suggerimento: Fix them up in the work tree, and then use 'git add/rm <file>'
suggerimento: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
sab  3 nov 2018, 21.51.00, CET : ERROR:  FAILED TO UPDATE NETDATA : CANNOT FETCH LATEST SOURCE (use -f for force re-install)
root@MCTime:~#

Cannot send .sh file due to telegram's bot token that are write into

**Comment by ktsaou** [comment]
Hi,

Sorry for that. We accidentally made a breaking change to the repo.
You can reset your git clone of the repo with this:

```sh
sudo sh -c 'cd /usr/src/netdata.git && git reset --hard origin/master && ./netdata-updater.sh -f'
```

After that, updates will resume as normal.

Again, we are very sorry for the frustration.

**Comment by alsoGAMER** [comment]
Ok, but i'll lost my configuration?

**Comment by ktsaou** [comment]
No, of course not.
It will just update like it did every day.

**Comment by alsoGAMER** [comment]
Ok thanks

**Comment by alsoGAMER** [comment]
root@MCTime:~# cd /usr/src/netdata.git && git reset --hard origin/master && ./netdata-updater.sh -f
HEAD ora si trova a caae263c fix CI scripts configuration and [netdata minor release] and [minor] (just to be sure)
dom  4 nov 2018, 00.00.12, CET : INFO:  Running on a terminal - (this script also supports running headless from crontab)

dom  4 nov 2018, 00.00.12, CET : INFO:  Updating netdata source from github...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 93 (delta 49), reused 84 (delta 46), pack-reused 4
Unpacking objects: 100% (93/93), done.
Da https://github.com/firehol/netdata
 + caae263c...5ae448a6 master     -> origin/master  (aggiornamento forzato)
   f3493bdf..0ed6d4af  htmldoc    -> origin/htmldoc
 * [nuova tag]         v1.11.0    -> v1.11.0
Auto-merging docker/build.sh
Auto-merging .travis/releaser.sh
CONFLICT (content): Merge conflict in .travis/releaser.sh
Auto-merging .travis.yml
CONFLICT (content): Merge conflict in .travis.yml
Merge automatico fallito; risolvi i conflitti ed eseguire il commit
del risultato.
dom  4 nov 2018, 00.00.21, CET : ERROR:  FAILED TO UPDATE NETDATA : CANNOT FETCH LATEST SOURCE (use -f for force re-install)
root@MCTime:/usr/src/netdata.git# 

:/

**Comment by ktsaou** [comment]
hm... interesting.

Could you please try this:

```sh
cd /usr/src/netdata.git && git fetch --all && git reset --hard origin/master && ./netdata-updater.sh -f
```

**Comment by alsoGAMER** [comment]
It worked, but for the second question.. how to disable logging events to mail? I've tried to disable the option in .sh file, but it doesn't work :/

**Comment by ktsaou** [comment]
If it does not fail, it does not log.
It only logs when it needs your attention.

**Comment by alsoGAMER** [comment]
I know, but i won't this feature.. i've a telegram's bot & channel for this

**Comment by ktsaou** [comment]
If you never want to get notified by the updater that it failed, you can just create a wrapper script and redirect all its output to `/dev/null`, like this:

```
#!/usr/bin/env sh

/usr/src/netdata.git/netdata-updater.sh >/dev/null 2>&1
exit 0
```

But I not sure how you will get notified if the updater fails for some reason.

**Comment by alsoGAMER** [comment]
No, no I wanted to say that, since they already do the logging on a channel telegram via the same script, if it was possible to disable the feature of logging into the mail the same things that log already in the channel..

I tried to change the parameter in the file, but nothing changes

**Comment by cakrit** [comment]
The bug is resolved and I think that the question now is on how to turn off receiving emails from cron jobs, which is not related. Perhaps [this](https://askubuntu.com/questions/175464/how-to-stop-email-report-from-cron-rootmachine-hourly) will also help. 

Closing it, please reopen if you need more help.
