### ISSUE TITLE
update  netdata error 

### ISSUE THREAD

**Issue by genrihx2** [netdata/netdata#4560]
![image](https://user-images.githubusercontent.com/3043207/47960340-081a3f00-e00b-11e8-97f5-29d7ceae9b87.png)

**Comment by ktsaou** [comment]
Sorry for that. Our fault.

Please run:

```
sudo sh -c 'cd /usr/src/netdata.git && git fetch --all && git reset --hard origin/master && ./netdata-updater.sh -f'
```

The above fixes the broken github repo sync. If does not alter anything else on your installation.

After running it, netdata will resume daily updates, like it did everyday so far.

**Comment by genrihx2** [comment]
good  ktsaou 

good run works 
Thank you
