### ISSUE TITLE
Creation of Alarm From scratch in Netdata

### ISSUE THREAD

**Issue by Charanjet** [netdata/netdata#4564]
Netdata Help Alarm creation
##### Question summary

how to create alarm from scratch
##### OS / Environment

Hi,
Please i want help to create alarms in Netdata as i am new to this.This is very cool software but i need some help to create alarms from scratch as i am not able to find any thing that can help me how to create and set configure the alarms for nginx,mysql and phpfpm.Please experienced peoples help me what i am missing and what i can follow to complete my task.

**Comment by vlvkobal** [comment]
Please read https://github.com/netdata/netdata/blob/master/health/README.md

**Comment by Charanjet** [comment]
Thanks @vlvkobal 
I read out this file but I can't understand where to write the code for alarm, how to find a chart name to attach with alarm.Can u please send me the code for alarm for mysql or phpfpm.

**Comment by l2isbad** [comment]
> mysql or phpfpm

Every `netdata` shipped with a set of predefined alarms for [mysql](https://github.com/netdata/netdata/blob/master/health/health.d/mysql.conf)

If you need some specific alarm i suggest to describe it in detail.

**Comment by Charanjet** [comment]
i need phpfpm, mysql and nginx alarms in action and to be send on email

**Comment by Charanjet** [comment]
hey @l2isbad may we fix a time to talk this is urgently needed task for me.When you will say then i will come.

**Comment by l2isbad** [comment]
Nedata shipped with alarms for [mysql](https://github.com/netdata/netdata/blob/master/health/health.d/mysql.conf) and [nginx](https://github.com/netdata/netdata/blob/master/health/health.d/nginx.conf)

What exactly alarm for `phpfm` you need? Warn you if... ? What trigger?

**Comment by Charanjet** [comment]
so how i can enable these alarms.

**Comment by l2isbad** [comment]
They are enabled by default.

> I just restarted the netdata service and its all default alarms get disabled.

How do you know?

Check `Alarms`  section of the dashboard.

**Comment by Charanjet** [comment]
in the Alarms in dashboard shows :No alarms are running in this system. and in the log status is removed to all alarms

**Comment by Charanjet** [comment]
How i can enable those all alarms.

**Comment by Charanjet** [comment]
![screenshot from 2018-11-09 16-29-29](https://user-images.githubusercontent.com/35090930/48259040-c0e1e300-e43c-11e8-8f37-28efcef96cb4.png)

![screenshot from 2018-11-09 16-31-48](https://user-images.githubusercontent.com/35090930/48259110-06061500-e43d-11e8-8172-087cbf188227.png)
Please check out these images.

**Comment by l2isbad** [comment]
@Ferroin any ideas?

**Comment by cakrit** [comment]
The last question was asked again in #4636, so closing this one and we will continue the investigation there.
