### ISSUE TITLE
mysql_local.queries_last_collected increase time every day for several seconds

### ISSUE THREAD

**Issue by petarkozic** [netdata/netdata#4565]
Hi,
I'm using your latest netdata on about 20 VPS with different services.
On several VPS I have installed Mysql server and I monitor them without problem with netdata, but on one instance **mysql_local.queries_last_collected** increase time for several seconds every day.

I can't figure why this happen, on example if I restart mysql last_collected is about 15-20 seconds what is ok, but tomorrow that will be 35-40 seconds, next day that number is more than 1 minutes and so on.

This happen only on this one instance.

Mysql version: 
Server version: 10.1.36-MariaDB

On other VPS same version of MariaDB was installed.

Thank you.

**Comment by l2isbad** [comment]
Hi @petarkozic 

What's `queries_last_collected` ? 

Are you talking about the [alarm](https://github.com/netdata/netdata/blob/master/health/health.d/mysql.conf#L4-L13)?

**Comment by ktsaou** [comment]
If the alarm `mysql_last_collected` increases, it means the chart is also left behind. You can check it by comparing the time on the `mysql_local.queries` chart to the time of the machine (run `date` via ssh).

In netdata v1.10 we were using clocks in a non-consistent way. But we fixed that in the current repo a few months ago (included in v1.11). So, when you say you are using the latest netdata, you mean you cloned the repo?

If yes, could you please check the time difference between `system.cpu` and `mysql_local.queries` using the (same host) netdata dashboard? If there is a difference above 1 sec, it may mean we haven't solved the issue entirely.

**Comment by petarkozic** [comment]
I'm using netdata version from master repository but not this latest version v1.11

If I compare chart for mysql_local.queries with time on server everything in sync and ok.

**Comment by ktsaou** [comment]
hm... it does not make sense...

The calculation of `mysql_last_collected` is this: https://github.com/netdata/netdata/blob/d160906f3e7f4ec024b643b577679bff5a40ac7e/health/health.d/mysql.conf#L6

`$now` is the system clock. `$last_collected_t` is the time the chart was last collected.
If their difference is increasing, it means the chart should also be left behind.

So, you say the chart `mysql_local.queries` gets updates, and its clock (last update time) is current, but this calculation gives increasing durations?

Could you please post a few screenshots?
Something strange is happening...

**Comment by petarkozic** [comment]
Sorry on last answer. 
After upgrade of netdata problems disappear.
