### ISSUE TITLE
Apache server status multiple request in same time

### ISSUE THREAD

**Issue by petarkozic** [netdata/netdata#4578]
Your netdata version: 1.10.0-133-g8dde644e_rolling
Your netdata commit: 8dde644 

In Apache conf I have 

```
localhost:
  update_every: 5
  name : 'local'
  url  : 'http://localhost/server-status?auto'
```

but in access log I see two request in same time.

127.0.0.1 - - [07/Nov/2018:13:24:30 +0100] "GET /server-status?auto HTTP/1.1" 200 1366 "-" "-"
127.0.0.1 - - [07/Nov/2018:13:24:30 +0100] "GET /server-status?auto HTTP/1.1" 200 1366 "-" "-"

127.0.0.1 - - [07/Nov/2018:13:24:35 +0100] "GET /server-status?auto HTTP/1.1" 200 1365 "-" "-"
127.0.0.1 - - [07/Nov/2018:13:24:35 +0100] "GET /server-status?auto HTTP/1.1" 200 1365 "-" "-"

**Comment by paulfantom** [comment]
@petarkozic please, could you use issue templates? This greatly simplifies our work. Thanks!

**Comment by cakrit** [comment]
@ilyam8 this is a question on the apache python module. If I understand what I read in the code, the first call is from the check, which also calls get_data. Perhaps it could be optimized to call get_data only once?

**Comment by ilyam8** [comment]
Apache module job does exactly one request every `update every`.

It does 2 req **only on** start, this is OK. First one in `check` (the only valid way to check).

**Comment by ilyam8** [comment]
@petarkozic if you have 2 `server-status?auto`requests every sec after netdata restart you probably have 2 jobs or maybe some other monitoring solution does it :thinking:

**Comment by petarkozic** [comment]
After updating netdata on this server I don't have more this problem.
