### ISSUE TITLE
How to enable nginx request time chart? (timings)

### ISSUE THREAD

**Issue by swinkq** [netdata/netdata#4585]
im trying this for about 2 hours and nothing, please help
I want to create chart for nginx $request_time 

found this:
https://github.com/netdata/netdata/blob/419cd0a237275e5eeef3f92dcded84e735ee6c58/conf.d/python.d/web_log.conf#L76-L89

tried to uncomment that section but nothing works...
What am i doing wrong?

**Comment by l2isbad** [comment]
yo @swinkq 

> To enable the timings chart and the requests size dimension, the  web server needs to log them

You have to configure `nginx`

1. Add to `nginx.conf` to the `http` section

```
log_format netdata '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '$request_length $request_time $upstream_response_time "$host" '
                    '"$http_referer" "$http_user_agent"';
```

2.  Find `access_log /var/log/nginx/access.log;` in the same section, replace it with `access_log /var/log/nginx/access.log netdata;`

3. Restart `nginx.service`
4. Restart `netdata.service`
.
.
Success!

**Comment by swinkq** [comment]
> yo @swinkq
> 
> > To enable the timings chart and the requests size dimension, the  web server needs to log them
> 
> You have to configure `nginx`
> 
> 1. Add to `nginx.conf` to the `http` section
> 
> ```
> log_format netdata '$remote_addr - $remote_user [$time_local] '
>                     '"$request" $status $body_bytes_sent '
>                     '$request_length $request_time $upstream_response_time "$host" '
>                     '"$http_referer" "$http_user_agent"';
> ```
> 1. Find `access_log /var/log/nginx/access.log;` in the same section, replace it with `access_log /var/log/nginx/access.log netdata;`
> 2. Restart `nginx.service`
> 3. Restart `netdata.service`
> 4. Look at the charts, see timings!

my savior!!!
Thank you so much!

**Comment by l2isbad** [comment]
You are welcome :slightly_smiling_face: 

Have you solved the problem? If so i will close the issue.

**Comment by swinkq** [comment]
yes, problem solved

**Comment by l2isbad** [comment]
nice!

**Comment by ccbarker** [comment]
@swinkq I would like to contact you about a access control intercom project I am working on
