### ISSUE TITLE
no error for url style stream destination

### ISSUE THREAD

**Issue by MoritzFago** [netdata/netdata#4591]
##### Bug report summary

If you specify the stream destination host like `tcp://examle.com` netdata tells you that the connect failed, instead of an more appropriate `syntax error`.
##### OS / Environment

freebsd 11.2p4
##### Component Name

stream.conf
##### Steps To Reproduce

Set stream.conf like below

```yaml
[stream]
    enabled = yes
    destination = tcp://monitoring.fago.me
```

##### Expected behavior

Some kind of better error message, that tells you what the problem is, instead of sending one down the wrong rabbit hole (I was sure it was a network problem until i attached gdb)

**Comment by thiagoftsm** [comment]
Hi @MoritzFago ,

Firstly we apologize for the delay to fix this error. Thank you very much for the information!

Best regards,

**Comment by ilyam8** [comment]
Closing as `wontfix`, because `destination` configuration option syntax is properly described in https://learn.netdata.cloud/docs/metrics-storage-management/reference-streaming#destination
