### ISSUE TITLE
Attempting to update NetData

### ISSUE THREAD

**Issue by Firemanjoe** [netdata/netdata#4592]
When trying to run the NetData updater on my RasPi, I'm getting the following: 
`pi@TARDIS:~/netdata $ sudo git pull

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@TARDIS.(none)')`

Unsure why I'm being asked email address and such.

**Comment by Ferroin** [comment]
This is an issue with how `git` works.  You can run those two commands with any arbitrary data passed to them and it won't complain further (provided the email address looks like an email address).

**Comment by paulfantom** [comment]
@Firemanjoe did those instructions solve your problem?

**Comment by Firemanjoe** [comment]
Yeah, I'm not sure how to make it work. I attempted to do it, but it didn't work. I'm still getting the same error.

**Comment by paulfantom** [comment]
Did you run what git told you to run? Mainly:
```
Run

git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```
?

**Comment by paulfantom** [comment]
Yes, you need to run those two commands and you can put whatever you want inside quotation marks.

For more information on how git works go here: https://git-scm.com/book/en/v1/Getting-Started

**Comment by Firemanjoe** [comment]
Thank you! I have it working, but now I'm getting this error.... ugh! LOL - not sure where to go from here. 

pi@TARDIS:~/netdata $ sudo ./netdata-updater.sh -f
Fri Nov 16 15:07:52 AST 2018 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

Fri Nov 16 15:07:52 AST 2018 : INFO:  Updating netdata source from github...
M	.codacy.yml
M	.gitignore
M	.lgtm.yml
U	.travis.yml
M	.travis/create_artifacts.sh
D	.travis/decrypt-if-have-key
D	.travis/deploy-if-have-key
D	.travis/firehol_create_artifacts.sh
U	.travis/generate_changelog.sh
A	.travis/labeler.sh
U	.travis/releaser.sh
A	.travis/tagger.sh
D	.travis/travis_rsa.enc
M	CHANGELOG.md
A	CONTRIBUTING.md
M	HISTORICAL_CHANGELOG.md
M	Makefile.am
M	README.md
M	REDISTRIBUTED.md
M	backends/Makefile.am
M	backends/README.md
A	backends/WALKTHROUGH.md
M	backends/prometheus/README.md
M	collectors/README.md
M	collectors/apps.plugin/README.md
M	collectors/cgroups.plugin/README.md
M	collectors/checks.plugin/Makefile.am
A	collectors/checks.plugin/README.md
M	collectors/freebsd.plugin/Makefile.am
A	collectors/freebsd.plugin/README.md
M	collectors/macos.plugin/Makefile.am
A	collectors/macos.plugin/README.md
M	collectors/node.d.plugin/README.md
M	collectors/plugins.d/README.md
M	collectors/proc.plugin/README.md
M	collectors/proc.plugin/proc_net_dev.c
M	collectors/proc.plugin/proc_net_stat_conntrack.c
M	collectors/proc.plugin/proc_stat.c
M	collectors/python.d.plugin/Makefile.am
M	collectors/python.d.plugin/README.md
M	collectors/python.d.plugin/beanstalk/beanstalk.conf
M	collectors/python.d.plugin/elasticsearch/README.md
M	collectors/python.d.plugin/go_expvar/README.md
A	collectors/python.d.plugin/nvidia_smi/Makefile.inc
A	collectors/python.d.plugin/nvidia_smi/README.md
A	collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py
A	collectors/python.d.plugin/nvidia_smi/nvidia_smi.conf
A	collectors/python.d.plugin/openldap/Makefile.inc
A	collectors/python.d.plugin/openldap/README.md
A	collectors/python.d.plugin/openldap/openldap.chart.py
A	collectors/python.d.plugin/openldap/openldap.conf
M	collectors/python.d.plugin/python.d.conf
M	collectors/python.d.plugin/python.d.plugin.in
M	collectors/python.d.plugin/python_modules/third_party/lm_sensors.py
M	collectors/python.d.plugin/sensors/README.md
M	collectors/python.d.plugin/sensors/sensors.chart.py
M	collectors/python.d.plugin/smartd_log/README.md
M	collectors/python.d.plugin/smartd_log/smartd_log.chart.py
M	collectors/python.d.plugin/smartd_log/smartd_log.conf
M	collectors/python.d.plugin/springboot/README.md
A	collectors/python.d.plugin/tor/Makefile.inc
A	collectors/python.d.plugin/tor/README.md
A	collectors/python.d.plugin/tor/tor.chart.py
A	collectors/python.d.plugin/tor/tor.conf
M	collectors/python.d.plugin/w1sensor/README.md
M	collectors/python.d.plugin/web_log/README.md
M	collectors/tc.plugin/README.md
M	configure.ac
M	contrib/debian/netdata.docs
M	contrib/debian/rules
M	daemon/Makefile.am
M	daemon/README.md
A	daemon/config/README.md
M	daemon/unit_test.c
M	database/README.md
M	database/rrd.h
M	database/rrdcalctemplate.h
M	database/rrddim.c
M	database/rrdset.c
M	diagrams/Makefile.am
A	diagrams/data_structures/README.md
A	diagrams/data_structures/netdata_config.svg
A	diagrams/data_structures/registry.svg
A	diagrams/data_structures/rrd.svg
A	diagrams/data_structures/src/netdata_config.xml
A	diagrams/data_structures/src/registry.xml
A	diagrams/data_structures/src/rrd.xml
A	diagrams/data_structures/src/web.xml
A	diagrams/data_structures/web.svg
A	doc/Add-more-charts-to-netdata.md
A	doc/Demo-Sites.md
A	doc/Donations-netdata-has-received.md
A	doc/Netdata-Security-and-Disclosure-Information.md
A	doc/Performance.md
A	doc/Running-behind-apache.md
A	doc/Running-behind-caddy.md
A	doc/Running-behind-lighttpd.md
A	doc/Running-behind-nginx.md
A	doc/Third-Party-Plugins.md
A	doc/Why-Netdata.md
A	doc/a-github-star-is-important.md
A	doc/high-performance-netdata.md
A	doc/netdata-for-IoT.md
A	doc/netdata-security.md
A	docker/README.md
M	docker/build.sh
M	health/README.md
M	health/health.d/net.conf
M	health/health_config.c
M	health/notifications/README.md
M	health/notifications/alarm-notify.sh.in
M	health/notifications/alerta/README.md
M	health/notifications/health_alarm_notify.conf
A	htmldoc/buildhtml.sh
A	htmldoc/buildyaml.sh
A	htmldoc/themes/material/partials/footer.html
A	installer/README.md
A	installer/UNINSTALL.md
A	installer/UPDATE.md
M	installer/functions.sh
M	libnetdata/adaptive_resortable_list/README.md
M	libnetdata/storage_number/storage_number.c
M	libnetdata/storage_number/storage_number.h
M	packaging/README.md
A	packaging/maintainers/README.md
M	registry/README.md
A	requirements.txt
A	runtime.txt
M	streaming/README.md
M	system/edit-config.in
M	system/netdata-openrc.in
M	tests/README.md
M	web/Makefile.am
M	web/README.md
M	web/api/README.md
M	web/api/badges/README.md
M	web/api/exporters/README.md
A	web/api/health/README.md
M	web/api/web_api_v1.c
M	web/gui/Makefile.am
M	web/gui/README.md
A	web/gui/browserconfig.xml
A	web/gui/confluence/README.md
A	web/gui/custom/README.md
M	web/gui/dashboard.html
M	web/gui/dashboard.js
M	web/gui/dashboard_info.js
M	web/gui/demosites.html
M	web/gui/favicon.ico
A	web/gui/images/android-icon-144x144.png
A	web/gui/images/android-icon-192x192.png
A	web/gui/images/android-icon-36x36.png
A	web/gui/images/android-icon-48x48.png
A	web/gui/images/android-icon-72x72.png
A	web/gui/images/android-icon-96x96.png
A	web/gui/images/apple-icon-114x114.png
A	web/gui/images/apple-icon-120x120.png
A	web/gui/images/apple-icon-144x144.png
A	web/gui/images/apple-icon-152x152.png
A	web/gui/images/apple-icon-180x180.png
A	web/gui/images/apple-icon-57x57.png
A	web/gui/images/apple-icon-60x60.png
A	web/gui/images/apple-icon-72x72.png
A	web/gui/images/apple-icon-76x76.png
A	web/gui/images/apple-icon-precomposed.png
A	web/gui/images/apple-icon.png
A	web/gui/images/banner-icon-144x144.png
A	web/gui/images/favicon-16x16.png
A	web/gui/images/favicon-32x32.png
A	web/gui/images/favicon-96x96.png
A	web/gui/images/favicon.ico
A	web/gui/images/ms-icon-144x144.png
A	web/gui/images/ms-icon-150x150.png
A	web/gui/images/ms-icon-310x310.png
A	web/gui/images/ms-icon-70x70.png
D	web/gui/images/seo-performance-114.png
D	web/gui/images/seo-performance-16.png
D	web/gui/images/seo-performance-24.png
D	web/gui/images/seo-performance-256.png
D	web/gui/images/seo-performance-32.png
D	web/gui/images/seo-performance-48.png
D	web/gui/images/seo-performance-512.png
D	web/gui/images/seo-performance-64.png
D	web/gui/images/seo-performance-72.png
D	web/gui/images/seo-performance-multi-size.icns
D	web/gui/images/seo-performance-multi-size.ico
M	web/gui/index.html
A	web/gui/main.css
A	web/gui/main.js
A	web/gui/manifest.json
D	web/gui/registry.html
A	web/gui/src/dashboard.js/alarms.js
A	web/gui/src/dashboard.js/boot.js
A	web/gui/src/dashboard.js/chart-registry.js
A	web/gui/src/dashboard.js/charting.js
A	web/gui/src/dashboard.js/charting/_c3.js
A	web/gui/src/dashboard.js/charting/_morris.js
A	web/gui/src/dashboard.js/charting/_raphael.js
A	web/gui/src/dashboard.js/charting/d3.js
A	web/gui/src/dashboard.js/charting/d3pie.js
A	web/gui/src/dashboard.js/charting/dygraph.js
A	web/gui/src/dashboard.js/charting/easy-pie-chart.js
A	web/gui/src/dashboard.js/charting/gauge.js
A	web/gui/src/dashboard.js/charting/google-charts.js
A	web/gui/src/dashboard.js/charting/peity.js
A	web/gui/src/dashboard.js/charting/sparkline.js
A	web/gui/src/dashboard.js/colors.js
A	web/gui/src/dashboard.js/common.js
A	web/gui/src/dashboard.js/compatibility.js
A	web/gui/src/dashboard.js/dependencies.js
A	web/gui/src/dashboard.js/epilogue.js.inc
A	web/gui/src/dashboard.js/error-handling.js
A	web/gui/src/dashboard.js/localstorage.js
A	web/gui/src/dashboard.js/main.js
A	web/gui/src/dashboard.js/options.js
A	web/gui/src/dashboard.js/prologue.js.inc
A	web/gui/src/dashboard.js/registry.js
A	web/gui/src/dashboard.js/server-detection.js
A	web/gui/src/dashboard.js/themes.js
A	web/gui/src/dashboard.js/timeout.js
A	web/gui/src/dashboard.js/units-conversion.js
A	web/gui/src/dashboard.js/utils.js
A	web/gui/src/dashboard.js/xss.js
M	web/server/README.md
Pull is not possible because you have unmerged files.
Please, fix them up in the work tree, and then use 'git add/rm <file>'
as appropriate to mark resolution, or use 'git commit -a'.
Fri Nov 16 15:07:52 AST 2018 : ERROR:  FAILED TO UPDATE NETDATA : CANNOT FETCH LATEST SOURCE (use -f for force re-install)

**Comment by Firemanjoe** [comment]
I tried to follow the instructions that you indicated and it didn't resolve anything. if I run the commands: 

cd /usr/src
cd netdata
./netdata-installer.sh

once I change into the src, I can't get into netdata as the doesn't exist. If I run the installer from the netdata directory, well, it installs it again, but doesn't resolve my existing install issue. 

Should I simply remove it and start from scratch again?

**Comment by paulfantom** [comment]
Installing from scratch seems like a good idea.

**Comment by ktsaou** [comment]
I am closing this, but you need help just post.

**Comment by Firemanjoe** [comment]
No problems on having it closed, but it didn't work. I don't know if I needed to remove all of the subfolders that go with it, but I simply ran the uninstaller and then I re-ran the installer. Should I have done more?

**Comment by ktsaou** [comment]
I suggest to use the one line installation, and post here the output of it:

```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

Don't sudo or anything else. Just run it. Then copy and whole output from your terminal and paste it here.

**Comment by ktsaou** [comment]
So, it runs.
Did you check it?

**Comment by Firemanjoe** [comment]
Ok, so an update was available and I attempted to update it via the way that I was always doing it

cd /netdata
sudo ./netdata-updater.sh

I get the same "merge files" error. I'm not the most savvy user - clearly - but I'm trying to make sense of it all.

**Comment by ktsaou** [comment]
Could you please post the error?

**Comment by ktsaou** [comment]
You can find update errors with this:

```
sudo sh -c 'cd /usr/src/netdata.git && git fetch --all && git reset --hard origin/master && ./netdata-updater.sh -f'
```
