### ISSUE TITLE
Upgrade on FreeBSD via kickstart.sh script segfaults during make all-recursive

### ISSUE THREAD

**Issue by m-d-johnson** [netdata/netdata#4593]
Hi!

I couldn't see this reported elsewhere.  Sorry if I missed something or if I'm doing it wrong.  Would appreciate advice on whether this is a bug

##### Bug report summary
When I update the git repo and re-run the kickstart.sh script, it fails as can be seen in the gist here:
[link](https://gist.github.com/m-d-johnson/a86cce0830be4a737dc4e876bc61af33)
##### OS / Environment
FreeBSD 11.2-RELEASE-p4 on bare metal.  
Intel i7 quad core, SSD. 16GB RAM, 1GbE ethernet

##### Component Name
Not sure.

##### Steps To Reproduce
```git pull
./kickstart.sh
<Enter> at prompt.
```
Wait.
Segfault during seemingly random components but always during `make all-recursive`

##### Expected behavior
The process should complete successfully with an up-to-date netdata instance running.

**Comment by ktsaou** [comment]
Hi,

just tested on this:

```sh
# freebsd-version 
11.2-RELEASE-p4
```

by running:

```
# start a bash shell
bash

# at the bash prompt
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

it worked without crash.

I also tried with this:

```
cd /usr/src/netdata.git
./kickstart.sh
```

Again, it worked without issues.

So, I guess you have bad memory. Please check your computer for memory errors.

**Comment by m-d-johnson** [comment]
Sure, will do. Thanks.

**Comment by m-d-johnson** [comment]
So, I left memtest86 running during the night and it says the memory's all good.  Any more ideas?

**Comment by ktsaou** [comment]
Could you please post the exact log? We may be able to get an idea based on the output we will see.

Since this crashes during compilation, and your RAM is good, I guess there is something wrong with the compiler tool chain. Can you compile it on another machine to verify this assumption?

**Comment by m-d-johnson** [comment]
Sure, I can try it in a KVM guest on separate hardware.  Which logs do you need to see? There's a link to a gist in the original question

**Comment by ktsaou** [comment]
ok, I missed that gist.

So, in this gist it crashed in `makeself`. In this directory and Makefile does nothing. The crash is inside the toolchain, not in netdata.

I suggest to try it somewhere else. On my tests with FreeBSD it does not crash. If you can find a way to reproduce this, it would be very helpful to find the root cause of it.

**Comment by ktsaou** [comment]
@paulfantom 	I removed the `bug` flag. There is no indication that there is something faulty in netdata here. It is probably a corrupted toolchain, or something similar.

@m-d-johnson 	of course, we will update this if you can reproduce this on another installation.

**Comment by paulfantom** [comment]
@ktsaou if this is a problem with toolchain we are shipping, then it is a bug. Repository doesn't contain only netdata code, so "bug" can mean a problem with any part that is shipped in this repo.

**Comment by ktsaou** [comment]
> @ktsaou if this is a problem with toolchain we are shipping, then it is a bug.

This is probably a bug in `make` at the specific installation. I can't reproduce on a similar system, so it must be specific to that installation.

**Comment by m-d-johnson** [comment]
I don't have time to follow up after all.  I'll close and re-open if I can work out what's going on.
