### ISSUE TITLE
Use the new logo in web/gui

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#4598]
Netdata has a new logo, we should replace all occurrences of the old logo in `web/gui`.

- [x] Favicon
- [x] Mobile icons
- [x] Header of the dashboard

**Comment by andyforceno** [comment]
Just curious, why the new logo? Also, what is it supposed to be?

**Comment by gmosx** [comment]
We wanted to refresh the branding of Netdata. It's not supposed to be anything specific, but if you insist, you could think of it as the detail around the eye of a hawk.
