### ISSUE TITLE
Sensors don`t work

### ISSUE THREAD

**Issue by hznovich** [netdata/netdata#4602]
##### Question summary

Sensors don`t work. Help please.

./plugins.d/python.d.plugin 1 debug sensors
2018-11-11 15:26:28: python.d INFO: plugin: main: Using python 2
2018-11-11 15:26:28: python.d DEBUG: plugin: main: loading '/opt/netdata/etc/netdata/python.d.conf'
2018-11-11 15:26:28: python.d DEBUG: plugin: main: module load source: 'sensors' => [OK]
2018-11-11 15:26:28: python.d DEBUG: plugin: main: loading '/opt/netdata/etc/netdata/python.d/sensors.conf'
2018-11-11 15:26:28: python.d DEBUG: plugin: main: job initialization: 'sensors sensors' => ['OK']
2018-11-11 15:26:28: python.d DEBUG: plugin: main: module status: 'sensors' => [OK] (jobs: 1)
2018-11-11 15:26:28: python.d ERROR: sensors: sensors: check() unhandled exception: Can't read
2018-11-11 15:26:28: python.d INFO: sensors: sensors: check() => [FAILED]
2018-11-11 15:26:28: python.d INFO: plugin: main: FINISHED

##### OS / Environment

Ubuntu 16.04.5 LTS

**Comment by l2isbad** [comment]
Hi @hznovich 
please run it with `trace` flag

**Comment by l2isbad** [comment]
Oh, it's an error from `lm_sensors`.

please do
1. cd to `/usr/libexec/netdata/python.d/python_modules/third_party`
2. enter `python` interpreter

run following script 
```python
import lm_sensors as sensors

for chip in sensors.ChipIterator():
    chip_name = sensors.chip_snprintf_name(chip)
    for feature in sensors.FeatureIterator(chip):
        sfi = sensors.SubFeatureIterator(chip, feature)
        for sf in sfi:
            try:
                val = sensors.get_value(chip, sf.number)
            except Exception as error:
                print(sf.name, sf.number, sf.type, repr(error))
            else:
                print(sf.name, sf.number, sf.type, val)
```

to exit from `python` run `exit()`

**Comment by hznovich** [comment]
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lm_sensors as sensors
for chip in sensors.ChipIterator():
>>>
>>> for chip in sensors.ChipIterator():
...     chip_name = sensors.chip_snprintf_name(chip)
...     for feature in sensors.FeatureIterator(chip):
...         sfi = sensors.SubFeatureIterator(chip, feature)
...         for sf in sfi:
...             try:
...                 val = sensors.get_value(chip, sf.number)
...             except Exception as error:
...                 print(sf.name, sf.number, sf.type, repr(error))
...             else:
...                 print(sf.name, sf.number, sf.type, val)
... exit()
  File "<stdin>", line 12
    exit()
       ^
SyntaxError: invalid syntax

**Comment by hznovich** [comment]
('fan1_input', 0, 256, 0.0)
('temp1_input', 0, 512, 27.8)
('temp1_crit', 1, 516, 106.0)
('temp2_input', 2, 512, 29.8)
('temp2_crit', 3, 516, 106.0)
('temp1_input', 0, 512, 43.0)
('temp1_max', 1, 513, 85.0)
('temp1_crit', 2, 516, 105.0)
('temp1_crit_alarm', 3, 643, 0.0)
('temp2_input', 4, 512, 43.0)
('temp2_max', 5, 513, 85.0)
('temp2_crit', 6, 516, 105.0)
('temp2_crit_alarm', 7, 643, 0.0)
('temp3_input', 8, 512, 31.0)
('temp3_max', 9, 513, 85.0)
('temp3_crit', 10, 516, 105.0)
('temp3_crit_alarm', 11, 643, 0.0)
('temp4_input', 12, 512, 41.0)
('temp4_max', 13, 513, 85.0)
('temp4_crit', 14, 516, 105.0)
('temp4_crit_alarm', 15, 643, 0.0)
('temp5_input', 16, 512, 38.0)
('temp5_max', 17, 513, 85.0)
('temp5_crit', 18, 516, 105.0)
('temp5_crit_alarm', 19, 643, 0.0)
('in0_input', 0, 0, 'Exception(u"Can\'t read",)')
('fan1_input', 1, 256, 0.0)
('temp1_input', 2, 512, 57.0)
('temp1_crit', 3, 516, 120.0)
('temp1_crit_hyst', 4, 517, 90.0)
('power1_average', 5, 768, 'Exception(u"Can\'t read",)')
('power1_cap', 6, 774, 'Exception(u"Can\'t read",)')

**Comment by l2isbad** [comment]
i will try to fix it asap @hznovich

**Comment by l2isbad** [comment]
fixed in https://github.com/netdata/netdata/pull/4651

**Comment by hznovich** [comment]
Thanks

**Comment by hznovich** [comment]
Sensors work now, thanks!!!
