### ISSUE TITLE
How i can copy configuration without edit?

### ISSUE THREAD

**Issue by felipe3dfx** [netdata/netdata#4613]
I just only want copy health_alarm_notify.conf is posible with edit-config script?

When runs /etc/netdata/edit-config health_alarm_notify.conf open editor, i don't want this.

**Comment by petrukngantuk** [comment]
look the in `/etc/netdata/orig/health_alarm_notify.conf`
or
`/usr/lib/netdata/conf.d/health_alarm_notify.conf`

thats the original place of default netdata config
