### ISSUE TITLE
add new chart in netdata

### ISSUE THREAD

**Issue by MarjanSadat** [netdata/netdata#4615]
hi and thanks for netdata again,
i have one text file which data is like this
```
timestamp data1 data2 data3 data4
timestamp data1 data2 data3 data4
timestamp data1 data2 data3 data4
......
```
is it possible to make a chart with python according this text file and show it in dashboard, thanks so much.

**Comment by MarjanSadat** [comment]
thanks @l2isbad,
i read that doc but didn't understand what should i do.
i added test.chart.py to /usr/libexec/netdata/python.d/test.chart.py anything else i should do?

**Comment by l2isbad** [comment]
No.

`python.d.plugin` has debug mode:

`/usr/libexec/netdata/plugins.d/python.d.plugin test debug trace`

please share the code, it will be easier to help for me :smile:

**Comment by MarjanSadat** [comment]
sorry I'm newer in netdata my code is not complete i just copied for example phpfpm.chart.py to my test, is it possible? then i restart netdata.
unfortunately i don't know how investigate my data in python in a way that show it in netdata as a chart and.
thanks so much @l2isbad

**Comment by l2isbad** [comment]
Can you do a parsing part yourself? 
What exactly help do you want from me?

**Comment by MarjanSadat** [comment]
this is an exmple of my test.chart.py

```
from random import SystemRandom

from bases.FrameworkServices.SimpleService import SimpleService

# default module values
# update_every = 4
priority = 90000
retries = 60

ORDER = ['random']
CHARTS = {
    'random': {
        'options': [None, 'A random number', 'random number', 'random', 'random', 'line'],
        'lines': [
            ['random1']
        ]
    }
}
class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.random = SystemRandom()

    @staticmethod
    def check():
        return True

    def get_data(self):
        data = dict()

        for i in range(1, 8):
            dimension_id = ''.join(['random', str(i)])

            if dimension_id not in self.charts['random']:
                self.charts['random'].add_dimension([dimension_id])

            data[dimension_id] = self.random.randint(0, 100)

        return data
```
and it shows in dashboard fortunately :)
now could you please help me how shows my data after reading text file.
my file is like this:

```
timestamp data1 data2 data3 data4
timestamp data1 data2 data3 data4
timestamp data1 data2 data3 data4
......
```
thanks

**Comment by l2isbad** [comment]
We need to read only last line? Does service append data? Or rewrites the whole file?

**Comment by MarjanSadat** [comment]
no, we need to read whole file. one of my out put is like this:
![default](https://user-images.githubusercontent.com/31684355/48393166-b9b02300-e723-11e8-86ec-788a079534c9.png)


and then the horizontal will fill with data and vertical with columns.
thanks @l2isbad

**Comment by l2isbad** [comment]
Ok, 

that's a generic chart
```python
   'random': {
        'options': [None, 'A random number', 'random number', 'random', 'random', 'line'],
        'lines': [
            ['random1']
        ]
    }
```

can you build charts for your module (dimensions, dimension names, chart title, etc)?

i still don't understand, should we sum values from columns or not? Please describe the whole logic, how it supposed to work (we read file, ok, what's next - how to process data?)

**Comment by l2isbad** [comment]
> we need to read whole file

Why? historic data isn't changed, right?

**Comment by l2isbad** [comment]
So the logic is:
* check if file was changed every 1 sec
* if it was, **read last line** (`timestamp data1 data2 data3 data4`)
* chart those values

if i understand you right you want 1 chart with N dimensions (each dimension is `dataN`, how to name it btw?)

Am i missed something?

**Comment by MarjanSadat** [comment]
yes the logic is exactly what i want, i don't know how to thank you.
about "how to name it btw?" you mean this:


![screenshot 1](https://user-images.githubusercontent.com/31684355/48398667-b1adae80-e736-11e8-8681-9a4d5e42563f.png)

if yes, it depends on file for example if it's like this `timestamp data1 data2 data3 data4 data5 ......`
we can name it like `data1 data2 data3 data4 data5 ....`

> Am i missed something?

At all.

**Comment by l2isbad** [comment]
Well, i will try to implement it on holidays, but i am not promising.

If someone willing to help please do :smile:

**Comment by MarjanSadat** [comment]
> Well, i will try to implement it on holidays, but i am not promising.

Thank you so much

**Comment by l2isbad** [comment]
Wait.

**Comment by l2isbad** [comment]
@MarjanSadat 
change `self.path = '/opt/other/test.txt` to whatever you need

```python
# -*- coding: utf-8 -*-
# Description: example netdata python.d module
# Author: Put your name here (your github login)
# SPDX-License-Identifier: GPL-3.0-or-later

import re
import os

from bases.FrameworkServices.SimpleService import SimpleService
from bases.collection import read_last_line


ORDER = [
    'some_name',
]

CHARTS = {
    'some_name': {
        'options': [None, 'Title', 'units', 'family', 'context', 'line'],
        'lines': [
        ]
    }
}

RE = re.compile(r' ([0-9.]+)')


class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS

        self.path = '/opt/other/test.txt'
        self.data = dict()
        self.size = 0

    def check(self):
        if not is_readable(self.path):
            self.error("{0} isn't readable".format(self.path))
            return False

        if is_empty(self.path):
            self.error("{0} is an empty file".format(self.path))
            return False

        data = self.get_data()

        for key in data:
            dim = [
                key,
                key.replace('_', ' '),
            ]
            self.definitions['some_name']['lines'].append(dim)

        return True

    def get_data(self):
        try:
            if not self.is_changed():
                self.debug("{0} size isn't changed, returning previous values".format(self.path))
                return self.data

            line = self.read_last_line()
        except OSError as error:
            self.error(error)
            return None

        parsed = self.parse_line(line)

        if not parsed:
            self.debug('parse failed')
            return None

        processed = self.process_data(parsed)

        self.data.update(processed)

        return self.data

    def read_last_line(self):
        line = read_last_line(self.path)
        self.size = os.path.getsize(self.path)
        return line

    def is_changed(self):
        return self.size != os.path.getsize(self.path)

    @staticmethod
    def parse_line(line):
        return RE.findall(line)

    @staticmethod
    def process_data(data):
        return dict(('data_{0}'.format(k), v) for k, v in enumerate(data))


def is_readable(path):
    return os.path.isfile(path) and os.access(path, os.R_OK)


def is_empty(path):
    return os.path.getsize(path) == 0
```

**Comment by l2isbad** [comment]
> how to do dynamic charts

netdata api doesn't support truly dynamic charts, in runtime you can:
* add new charts
* add new dimension to charts

that's pretty much all, you can't delete dimension and delete chart (you can mark it as deleted, but not 
 delete)

**Comment by MarjanSadat** [comment]
I do not know how to thank you @l2isbad ,I'm sorry for my delay.
i used your code it workde perfectly.thanks

**Comment by l2isbad** [comment]
> I do not know how to thank you

spread the word about `netdata` :+1:
