### ISSUE TITLE
Errors after uninstalling netdata

### ISSUE THREAD

**Issue by aravon72** [netdata/netdata#4616]
Hi,

I'm running CentOS 7 on VPS with CWP (CentOS Web Panel) and had netdata installed aside to it. Then I decided I don't make any real use of it, hence I uninstalled it with the commands given here on github.

The thing is that ever since, I'm getting this addition to the daily backup log I get by email from CWP. Any idea how to remove it? Or should this be asked in CWP's forum?

=====

cpulimit: no process found
/etc/cron.daily/netdata-updater:

Fri Nov  9 03:15:25 IST 2018 : INFO:  Updating netdata source from github...
U       .travis.yml
M       .travis/create_artifacts.sh
A       .travis/labeler.sh
U       .travis/releaser.sh
M       CHANGELOG.md
M       docker/build.sh
M       health/notifications/alarm-notify.sh.in
M       health/notifications/health_alarm_notify.conf
M       registry/README.md
M       system/edit-config.in
M       web/api/README.md
M       web/api/web_api_v1.c
M       web/gui/README.md
M       web/server/README.md
Pull is not possible because you have unmerged files.
Please, fix them up in the work tree, and then use 'git add/rm <file>'
as appropriate to mark resolution, or use 'git commit -a'.
Fri Nov  9 03:15:25 IST 2018 : ERROR:  FAILED TO UPDATE NETDATA : CANNOT FETCH LATEST SOURCE (use -f for force re-install)

**Comment by paulfantom** [comment]
You need to remove symlink located in `/etc/cron.daily/netdata-updater`. Seems like uninstaller didn't remove it. You can also remove netdata source code git repository from your VPS if don't need it anymore.

**Comment by aravon72** [comment]
> You need to remove symlink located in `/etc/cron.daily/netdata-updater`. Seems like uninstaller didn't remove it. You can also remove netdata source code git repository from your VPS if don't need it anymore.

I'm a bit ashamed to say I don't really know how to do either. :(

**Comment by paulfantom** [comment]
`rm /etc/cron.daily/netdata-updater`

**Comment by aravon72** [comment]
Wow, such a quick answer! Thanks!
Ran the command and seems to work. I'll keep an eye on the log tomorrow.
Thanks a bunch!
