### ISSUE TITLE
Replace http URLs with https in markdown fils

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#4626]
http URLs in markdown files need to be replaced with https, to prevent mixed content errors in netlify. 

A script was created to automatically replace http with https where https is available. The rest of the links (all of them images) will be uploaded to github using this issue, so that we get a github URL for the uploaded content. This new (https) URL will then be used to replace the existing (http) URL

**Comment by ktsaou** [comment]
This is done. Right?

**Comment by cakrit** [comment]
Done
