### ISSUE TITLE
Store nightly build artifacts somewhere

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4628]
##### Feature idea summary

Currently nightly builds are creating binaries (makeself and tar.gz archives) but not storing them anywhere. This should be fixed and binaries should be stored somewhere. Preferably in some sort of object storage so we can track how many downloads of particular files there is.

##### Expected behavior

Nightly build artifacts are preserved.

**Comment by paulfantom** [comment]
@ktsaou @gmosx do we have some object store available?

**Comment by gmosx** [comment]
@paulfantom Yes, we can use Google Cloud Storage <https://cloud.google.com/storage/>
