### ISSUE TITLE
How to definitely uninstall netdata on Ubuntu 16.04

### ISSUE THREAD

**Issue by gate0keeper** [netdata/netdata#4633]
How can I  unstall netdata and all services etc. from my Ubuntu 16.04 System? I could not find any helping notice on that.

Thanks in advance,
Daniel

**Comment by paulfantom** [comment]
You can run netdata-uninstaller.sh.

**Comment by cakrit** [comment]
Also, the documentation is [here](https://github.com/netdata/netdata/blob/master/installer/UNINSTALL.md#uninstalling-netdata). Please let us know if anything mentioned there hasn't worked for you.

**Comment by jimidak** [comment]
I am having a hard time finding the uninstaller script. 'find / -name netdata-uninstaller.sh' turns up nothing, and there is no git directory
```
cd /usr/src/netdata.git
-bash: cd: /usr/src/netdata.git: No such file or directory
```

**Comment by cakrit** [comment]
We're changing the instructions in PR #5315:
Download [netdata-uninstaller.sh](https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-uninstaller.sh) and run it as follows: `netdata-uninstaller.sh --yes --env <path_to_environment_file>`. The default `path_to_environment_file` is `/etc/netdata`, it's the location of the file `.environment` that is used by the uninstaller.

**Comment by euthonis** [comment]
```
root@syr-mail:/etc/netdata# /usr/libexec/netdata/netdata-uninstaller.sh --yes --env /etc/netdata/
/usr/libexec/netdata/netdata-uninstaller.sh: line 472: source: /etc/netdata/: is a directory

Something went wrong :(
```

Much easier approach to this instead of banging my head against a wall:

```
kill -9 `ps -efw | grep netdata | awk '{print $2}'`
rm -rf `locate netdata`
```
