### ISSUE TITLE
Enable default alarms disabled after restart service netdata

### ISSUE THREAD

**Issue by Charanjet** [netdata/netdata#4636]
##### Question summary

All default alarms get disabled after netdata service restart
##### OS / Environment

Please suggest me why all the default alarms in netdata get disabled whenever restarted the netdata service in ubuntu os.Below are the screenshots displaying by netdata #Alarms button on dashboard.How can i enable all these without reinstall because i tried this one but after every restart on fresh installation this problem occurs
##### Expected results
![screenshot from 2018-11-09 16-29-29](https://user-images.githubusercontent.com/35090930/48403786-ac5f5c80-e754-11e8-8ec5-0d2009f37583.png)
![screenshot from 2018-11-09 16-31-48](https://user-images.githubusercontent.com/35090930/48403787-ac5f5c80-e754-11e8-8133-b88402da3cf7.png)

**Comment by cakrit** [comment]
Hi @Charanjet, can you please share the configs you have under /etc/netdata/ and /etc/netdata/health.d ? 
You're probably not using the default configuration and ended up disabling all alarms.
The stock config is under /usr/lib/netdata/conf.d/health.d as explained [here](https://netdata.netlify.com/health/#health-configuration-reference)

**Comment by cakrit** [comment]
In #4499 @Charanjet mentioned that he's running Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1069-aws x86_64 ) and that he installed netdata from `git clone firehol/netdata.git --depth=1`

**Comment by cakrit** [comment]
We expect that this is fixed via PR #4898
