### ISSUE TITLE
Error running inside docker FD_SETSIZE

### ISSUE THREAD

**Issue by ivandal77** [netdata/netdata#4637]
Dear,
running netdata in docker container I obtain this error after a while:

`invalid file descriptor, ifd = 1026, ofd = 1026 (required 0 <= fd < FD_SETSIZE (1024) (errno 22, Invalid argument)
`
The system is running 

Ubuntu 18.0.4.1 kernel 4.15.0-38-generic with Docker version 18.09.0, build 4d60db4.

and collect the metric of ~100 servers.

How to fix this?

**Comment by ivandal77** [comment]
Maybe the problem is in this module:
`single-threaded.c`
sorry for asking, but you have some indication about the fixing time?
Thanks a lot

**Comment by ktsaou** [comment]
I suggest to use the `static-threaded` web server, set to 1 thread if you want just one thread for the API.

**Comment by ktsaou** [comment]
@paulfantom 	I guess you marked this as bug, to increase/control the number of file descriptors allowed in netdata docker images. ok please do this.

However, the `single-threaded` web server uses `select()` for handling connections and it does not support file descriptors above 1024. The `static-threaded` web server does not use `select()`, so it does not have this limitation and can be limited to a single thread. So, in the netdata code there is nothing to be done.

**Comment by ivandal77** [comment]
Dear all,
I confirm setting  `static-threaded` and `web server threads = 1` fix the problem in docker.
I suggest this as default configuration in docker hub image netdata/netdata.
Thanks to all,

Ivan

**Comment by ktsaou** [comment]
> I suggest this as default configuration in docker hub image netdata/netdata.

The default is not `static-threaded`?

**Comment by ktsaou** [comment]
So, the default is `static-threaded`.
I guess @ivandal77 	was asking to make `web server threads = 1` the default, but I am not sure why. The default is to use `min(cpu cores, 6)`, so it will use one thread for each cpu core, up to 6.

**Comment by ivandal77** [comment]
Dear,
`# netdata can generate its own config.
#Get it with:
#wget -O /etc/netdata/netdata.conf "http://localhost:19999/netdata.conf"
#or
#curl -s -o /etc/netdata/netdata.conf "http://localhost:19999/netdata.conf"
#4658 `
 but I curl from the wrong netdata installation. 
The correct  generated default part set:
`mode = static-threaded `
`web server threads = 6`
So should be fine, thanks for the support.

Ivan
