### ISSUE TITLE
Can't update to the latest version

### ISSUE THREAD

**Issue by Gino** [netdata/netdata#4659]
Hi there,

I tried to update my Netdata to the latest version with `sudo ./netdata-updater.sh`.

Unfortunately it gives me merge conflicts, even though I didn't change anything:
`Wed Nov 14 15:01:56 CET 2018 : INFO:  Updating netdata source from github...
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
Wed Nov 14 15:01:56 CET 2018 : ERROR:  FAILED TO UPDATE NETDATA : CANNOT FETCH LATEST SOURCE (use -f for force re-install)`

Wondering if someone can help me with this. Thanks! 👍

**Comment by Gino** [comment]
Fixed it by running:

```
git fetch --all
git reset --hard origin/master
git pull
./netdata-updater.sh -f
```

**Comment by paulfantom** [comment]
Sorry about that, we posted info about this issue in 1.11.0 release notes: https://github.com/netdata/netdata/releases/tag/v1.11.0

**Comment by pkd809** [comment]
On updating netdata through bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates
The version on netdata GUI is 16.1.0 while on the host i.e netdata -V it shows 16.1.1.
Initially when i installed netdata and tried to edit stream.conf it said .stream.conf.sw alreasy exists,which I had overwritten.
Now it neither updates the netdata even after uninstallation nor streams properly to master.Gives graphs at uneven time intervals.

Please resolve!!!!!
