### ISSUE TITLE
Monitor disk access latency (e.g. ioping)

### ISSUE THREAD

**Issue by FedericoCeratto** [netdata/netdata#4660]
##### Feature idea summary
Monitor disk access latency like ioping does, e.g. a tiny unbuffered read every second

**Comment by h0lzi** [comment]
my thoughts:
This is more or less already collected via the disk stats. We have service time etc.
Which is more or less the latency just that it's not fixed to 4k requests. So if you have bigger requests the service time is longer. But this way I have latency for my workload and not a "artificial" one with e.g. 4k which I might never have in my app.

Also these stats are collected without adding extra i/o

**Comment by ktsaou** [comment]
This is a nice request, but as @h0lzi 	suggested, we could achieve a probably more objective result by examining the metrics already collected.

For example, if disk backlog is pilling up, or service time increases and utilization is high too, then the disk struggles to do the job.

Of course `ioping` could be useful in remote filesystems, or filesystems that do not provide block device performance metrics.

So, I think it is a valid request.

**Comment by FedericoCeratto** [comment]
The disk backlog is useful but the metric it provides has a different meaning than I/O latency on an unloaded system, similarly to network latency with or without traffic. Perhaps this could go into a plugin.

**Comment by cakrit** [comment]
@mfundul can you look into this and perhaps work with @vlvkobal

**Comment by mfundul** [comment]
Will help @vlvkobal eagerly, working is going to be sporadic for a few days unfortunately.

**Comment by ktsaou** [comment]
We could follow the `fping` example:

1. Make a PR in `ioping` to output metrics in netdata format.
2. Write a simple wrapper script to call `ioping` with the right parameters.
3. The wrapper could also be used to install / compile the right version of `ioping` when it is not available.

This is what the netdata `fping` plugin does...

**Comment by vitabaks** [comment]
> Monitor disk access latency

This metric is missing :(

netdata
v1.12.0-5
