### ISSUE TITLE
Not running node.d.plugin!!! 

### ISSUE THREAD

**Issue by sohwaje** [netdata/netdata#4664]
Not showing snmp section in dashboard.
![notshowing](https://user-images.githubusercontent.com/19942049/48535452-be750280-e8ee-11e8-8431-2cee5955555c.JPG)

##### Question summary

1. I already installed node.js.
#node -v
v6.11.3
2. I configured snmp.conf file.
# vi /etc/netdata/node.d/snmp.conf
![snmp](https://user-images.githubusercontent.com/19942049/48535618-43f8b280-e8ef-11e8-98ba-51a607e29720.JPG)
3, /usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp
![plugin_test](https://user-images.githubusercontent.com/19942049/48535784-c5504500-e8ef-11e8-96b6-1189c24ce07b.JPG)
4. grep -Ei "(snmp|node\.d\.plugin)" /var/log/netdata/error.log
![error](https://user-images.githubusercontent.com/19942049/48535893-224bfb00-e8f0-11e8-8c76-600f0781731b.JPG)

##### OS / Environment

OS : CentOS release 6.10 (Final)
NETDATA Version : 1.11.0-70

**Comment by sohwaje** [comment]
also found.
![node d_2](https://user-images.githubusercontent.com/19942049/48590267-317b8900-e982-11e8-9e66-c05b0a308e60.JPG)

**Comment by sohwaje** [comment]
Is this a bug? Plz help me.

**Comment by sohwaje** [comment]
I already posted it. Do CTRL+F -> "/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp"

# sudo su -s /bin/sh netdata
# /usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp
CHART "network interface eth21" "network interface eth21" "network interface eth2 1" "megabits/s" "ports" "" "area" 50001 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth21 
SET in = 155700681
SET out = 155700681
END

CHART "network interface eth22" "network interface eth22" "network interface eth2 2" "megabits/s" "ports" "" "area" 50002 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth22 
SET in = 0
SET out = 0
END

CHART "network interface eth23" "network interface eth23" "network interface eth2 3" "megabits/s" "ports" "" "area" 50003 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth23 
SET in = 0
SET out = 0
END

CHART "network interface eth24" "network interface eth24" "network interface eth2 4" "megabits/s" "ports" "" "area" 50004 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth24 
SET in = 0
SET out = 0
END

CHART "network interface eth25" "network interface eth25" "network interface eth2 5" "megabits/s" "ports" "" "area" 50005 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth25 
SET in = 1002308
SET out = 6374567
END

CHART "network interface eth26" "network interface eth26" "network interface eth2 6" "megabits/s" "ports" "" "area" 50006 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth26 
SET in = 0
SET out = 0
END

CHART "network interface eth27" "network interface eth27" "network interface eth2 7" "megabits/s" "ports" "" "area" 50007 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth27 
SET in = 0
SET out = 0
END

CHART "network interface eth28" "network interface eth28" "network interface eth2 8" "megabits/s" "ports" "" "area" 50008 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth28 
SET in = 2038863070
SET out = 3792696237
END

CHART "network interface eth29" "network interface eth29" "network interface eth2 9" "megabits/s" "ports" "" "area" 50009 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth29 
SET in = 0
SET out = 0
END

CHART "network interface eth210" "network interface eth210" "network interface eth2 10" "megabits/s" "ports" "" "area" 50010 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth210 
SET in = 0
SET out = 0
END

CHART "network interface eth211" "network interface eth211" "network interface eth2 11" "megabits/s" "ports" "" "area" 50011 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth211 
SET in = 0
SET out = 0
END

CHART "network interface eth212" "network interface eth212" "network interface eth2 12" "megabits/s" "ports" "" "area" 50012 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth212 
SET in = 0
SET out = 0
END

CHART "network interface eth213" "network interface eth213" "network interface eth2 13" "megabits/s" "ports" "" "area" 50013 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth213 
SET in = 0
SET out = 0
END

CHART "network interface eth214" "network interface eth214" "network interface eth2 14" "megabits/s" "ports" "" "area" 50014 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth214 
SET in = 0
SET out = 0
END

CHART "network interface eth215" "network interface eth215" "network interface eth2 15" "megabits/s" "ports" "" "area" 50015 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth215 
SET in = 0
SET out = 0
END

CHART "network interface eth216" "network interface eth216" "network interface eth2 16" "megabits/s" "ports" "" "area" 50016 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth216 
SET in = 0
SET out = 0
END

CHART "network interface eth217" "network interface eth217" "network interface eth2 17" "megabits/s" "ports" "" "area" 50017 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth217 
SET in = 0
SET out = 0
END

CHART "network interface eth218" "network interface eth218" "network interface eth2 18" "megabits/s" "ports" "" "area" 50018 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth218 
SET in = 0
SET out = 0
END

CHART "network interface eth219" "network interface eth219" "network interface eth2 19" "megabits/s" "ports" "" "area" 50019 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth219 
SET in = 0
SET out = 0
END

CHART "network interface eth220" "network interface eth220" "network interface eth2 20" "megabits/s" "ports" "" "area" 50020 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth220 
SET in = 0
SET out = 0
END

CHART "network interface eth221" "network interface eth221" "network interface eth2 21" "megabits/s" "ports" "" "area" 50021 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth221 
SET in = 2952738028
SET out = 742052907
END

CHART "network interface eth222" "network interface eth222" "network interface eth2 22" "megabits/s" "ports" "" "area" 50022 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth222 
SET in = 0
SET out = 0
END

CHART "network interface eth223" "network interface eth223" "network interface eth2 23" "megabits/s" "ports" "" "area" 50023 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth223 
SET in = 0
SET out = 0
END

CHART "network interface eth224" "network interface eth224" "network interface eth2 24" "megabits/s" "ports" "" "area" 50024 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth224 
SET in = 0
SET out = 0
END

CHART "network interface eth225" "network interface eth225" "network interface eth2 25" "megabits/s" "ports" "" "area" 50025 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth225 
SET in = 0
SET out = 0
END

CHART "network interface eth226" "network interface eth226" "network interface eth2 26" "megabits/s" "ports" "" "area" 50026 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth226 
SET in = 2248451841
SET out = 353490686
END

CHART "network interface eth227" "network interface eth227" "network interface eth2 27" "megabits/s" "ports" "" "area" 50027 10
DIMENSION "in" "in" "incremental" 8 1024 
DIMENSION "out" "out" "incremental" -8 1024 
BEGIN network interface eth227 
SET in = 2850208893
SET out = 3590679667
END

BEGIN network interface eth21 895000
SET in = 155700681
SET out = 155700681
END

BEGIN network interface eth22 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth23 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth24 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth25 895000
SET in = 1002308
SET out = 6374567
END

BEGIN network interface eth26 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth27 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth28 895000
SET in = 2038863070
SET out = 3792696237
END

BEGIN network interface eth29 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth210 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth211 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth212 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth213 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth214 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth215 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth216 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth217 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth218 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth219 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth220 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth221 895000
SET in = 2952738028
SET out = 742052907
END

BEGIN network interface eth222 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth223 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth224 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth225 895000
SET in = 0
SET out = 0
END

BEGIN network interface eth226 895000
SET in = 2248451841
SET out = 353490686
END

BEGIN network interface eth227 895000
SET in = 2850208893
SET out = 3590679667
END

BEGIN network interface eth21 10017000
SET in = 155703721
SET out = 155703721
END

BEGIN network interface eth22 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth23 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth24 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth25 10017000
SET in = 1002308
SET out = 6374567
END

BEGIN network interface eth26 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth27 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth28 10017000
SET in = 2040019263
SET out = 3792825958
END

BEGIN network interface eth29 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth210 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth211 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth212 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth213 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth214 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth215 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth216 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth217 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth218 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth219 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth220 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth221 10017000
SET in = 2954075684
SET out = 749689601
END

BEGIN network interface eth222 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth223 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth224 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth225 10017000
SET in = 0
SET out = 0
END

BEGIN network interface eth226 10017000
SET in = 2333575460
SET out = 1717882304
END

BEGIN network interface eth227 10017000
SET in = 4214577181
SET out = 3676817395
END
....continue....




Which is text? "config in text format"

**Comment by sohwaje** [comment]
OK. Here it is.
![snmp_conf](https://user-images.githubusercontent.com/19942049/48963445-a6c80900-efd5-11e8-852e-35823dc95268.JPG)


![snmwalk](https://user-images.githubusercontent.com/19942049/48963446-ad568080-efd5-11e8-87da-e7cccf830cf6.JPG)

**Comment by ktsaou** [comment]
Thanks. Can you copy and paste it as text? I need to copy it too, so an image cannot do.

**Comment by sohwaje** [comment]
Yes. I do. But I don't have to publish the DEVICE IPADDRESS.
Because It is a public IP. so I used a private IP.

{
    "enable_autodetect": false,
    "update_every": 10,
    "servers": [
        {
            "hostname": "10.0.0.1",
            "community": "public",
            "update_every": 10,
            "options": { "timeout": 20000 },
            "charts": {
                "network interface eth2": {
                    "title": "network interface eth2 ",
                    "units": "megabits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "ports",
                    "multiply_range": [ 1, 27 ],
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.2.2.1.10.",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024,
                            "offset": 0
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.2.2.1.16.",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1024,
                            "offset": 0
                        }
                    }
                }
            }
        }
    ]
}

**Comment by ktsaou** [comment]
this one works for me:

```json
{
    "enable_autodetect": false,
    "update_every": 10,
    "servers": [
        {
            "hostname": "10.11.12.8",
            "community": "public",
            "update_every": 15,
            "options": { "timeout": 20000, "version": 1 },
            "charts": {
                "snmp_switch.bandwidth_port": {
                    "title": "bandwidth for port ",
                    "titleoid": ".1.3.6.1.2.1.31.1.1.1.18.",
                    "units": "kilobits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "ports",
                    "multiply_range": [ 1, 24 ],
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.2.2.1.10.",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024,
                            "offset": 0
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.2.2.1.16.",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1024,
                            "offset": 0
                        }
                    }
                }
            }
        }
    ]
}
```

I think the main problem was the chart name `network interface eth2`.

**Comment by sohwaje** [comment]
Thank you so much. I got it.
![thanks](https://user-images.githubusercontent.com/19942049/48988230-ba0ade00-f167-11e8-9bd1-ddae58465177.JPG)

**Comment by sohwaje** [comment]
Is CPU, MEMORY possible?

**Comment by ktsaou** [comment]
Yes, everything is possible. Just define the OIDs.

**Comment by sohwaje** [comment]
Can I have your example file? like a CPU or MEM...

**Comment by ktsaou** [comment]
hm... I don't have any SNMP device exposing CPU and Memory.
@cakrit @l2isbad 	can you help?

**Comment by l2isbad** [comment]
> Can I have your example file? like a CPU or MEM...

Ha, it depends on device, some big devices has **a lot of** cpus (route processor cpu, switrch processor cpu, every line card has it's own cpu, etc ,etc ).

some examples:

Thats for cisco single cpu devices
```
cpmCPUTotal5secRev (.1.3.6.1.4.1.9.9.109.1.1.1.1.6): The overall CPU busy percentage in the last five-second period. This object deprecates the object cpmCPUTotal5sec and increases the value range to (0..100).

cpmCPUTotal1minRev (.1.3.6.1.4.1.9.9.109.1.1.1.1.7): The overall CPU busy percentage in the last one-minute period. This object deprecates the object cpmCPUTotal1min and increases the value range to (0..100).

cpmCPUTotal5minRev (.1.3.6.1.4.1.9.9.109.1.1.1.1.8): The overall CPU busy percentage in the last five-minute period. This object deprecates the object cpmCPUTotal5min and increases the value range to (0..100).
```

dlink 
```
5 sec 1.3.6.1.4.1.171.12.1.1.6.1.0
1 min 1.3.6.1.4.1.171.12.1.1.6.2.0
5 min 1.3.6.1.4.1.171.12.1.1.6.3.0
```

**Comment by sohwaje** [comment]
OID? I found. Thank you everyone.
