### ISSUE TITLE
What is The Right Role for Netdata MongoDB Python Plugins?

### ISSUE THREAD

**Issue by petrukngantuk** [netdata/netdata#4666]
##### Question summary
I want to enabled mongodb plugins in netdata, but my mongodb is protected with auth, and I want to create different user n role for netdata monitoring, what is the right role for use in netdata monitoring, that can work in all chart?
Anyone can share the command for db.createUser(...) here?

##### OS / Environment
Ubuntu 16.04 Server

##### Component Name
python.d/mongodb.conf

##### Expected results
All MongoDB Chart in Netdata Dashboard Worked.

**Comment by l2isbad** [comment]
Hi @petrukngantuk 

You need a read-only user in the admin database

MongoDB 3+

```
db.createUser({
  "user":"netdata",
  "pwd": "<UNIQUEPASSWORD>",
  "roles" : [
    {role: 'read', db: 'admin' },
    {role: 'clusterMonitor', db: 'admin'},
    {role: 'read', db: 'local' }
  ]
})
```

**Comment by petrukngantuk** [comment]
what do you thing about this :
```
db.createUser({
   user: "netdata",
   pwd: "<UNIQUEPASSWORD>",
   roles:[
      {role: "clusterMonitor", db:"admin"},
      {role: "readAnyDatabase", db:"admin"}
   ]
})
```
it's same as yours but can read any database, it's secure right?

**Comment by l2isbad** [comment]
I think your example is OK, but keep in mind i am not a secure specialist, not even a mongo db user honestly

**Comment by petrukngantuk** [comment]
> I tested, it worked with only `clusterMonitor`.
> 
> mongodb version is 3.4
> 
> Can we add this info to the docs?
> https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/mongodb/mongodb.conf

so the most secure is

```
db.createUser({
   user: "netdata",
   pwd: "<UNIQUEPASSWORD>",
   roles:[
      {role: "clusterMonitor", db:"admin"},
   ]
})
```

**Comment by aadityabagga** [comment]
> 
> so the most secure is
> 
> ```
> db.createUser({
>    user: "netdata",
>    pwd: "<UNIQUEPASSWORD>",
>    roles:[
>       {role: "clusterMonitor", db:"admin"},
>    ]
> })
> ```

Yes, I believe so. Checked the logs and did not find any error relating to mongodb permissions.

If I look at the code, some more commands are run:
https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/mongodb/mongodb.chart.py#L574

With `clusterMonitor` permissions, I am able to run them as well.
https://docs.mongodb.com/manual/reference/built-in-roles/#clusterMonitor

**Comment by petrukngantuk** [comment]
> > so the most secure is
> > ```
> > db.createUser({
> >    user: "netdata",
> >    pwd: "<UNIQUEPASSWORD>",
> >    roles:[
> >       {role: "clusterMonitor", db:"admin"},
> >    ]
> > })
> > ```
> 
> Yes, I believe so. Checked the logs and did not find any error relating to mongodb permissions.
> 
> If I look at the code, some more commands are run:
> https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/mongodb/mongodb.chart.py#L574
> 
> With `clusterMonitor` permissions, I am able to run them as well.
> https://docs.mongodb.com/manual/reference/built-in-roles/#clusterMonitor

I believe it too, I just revoke user role except clusterMonitor, I restart netdata n checked the chart, everything is fine,

please add it too Readme on MongoDB Python.d Section, for better wiki
