### ISSUE TITLE
Ubuntu 18.04 apt package is still on v1.9.0, though apt is the recommended installation method

### ISSUE THREAD

**Issue by johlandabee** [netdata/netdata#4675]
Installing netdata using the distribution's package manager is the recommended installation method. Thus, the packages should be up-to-date. As for Ubuntu 18.04 `v1.9.0` will be installed using `apt install netdata`.

**Comment by paulfantom** [comment]
This is **not** a recommended way of installing netdata. We currently rely on community to package it while we are refactoring our build system to allow such packaging to happen automatically. We have a project tracking this complex problem here: https://github.com/netdata/netdata/projects/13 and also a related one here: https://github.com/netdata/netdata/projects/17

**Comment by johlandabee** [comment]
Sounds good. Though, the docs should probably be updated. [Currently it states the following](https://github.com/netdata/netdata/tree/master/installer#installation):
> For security and portability reasons, this is the preferred installation method.
