### ISSUE TITLE
Push from subsystem

### ISSUE THREAD

**Issue by iselind** [netdata/netdata#4676]
##### Question summary

I'm trying to figure out if a subsystem on my devices can somehow push data to the netdata server running on the same device.

All i find are plugins that seem to poll for to get their data when i read the documentation. Some of the data we want to collect isn't suitable to be collected in that way. Using push would be far better.

**Comment by Ferroin** [comment]
Netdata provides an implementation of the statsd protocol for situations like this.  More info can be found [here](https://github.com/netdata/netdata/tree/master/collectors/statsd.plugin).

**Comment by iselind** [comment]
Thanks a lot.
