### ISSUE TITLE
on uinstall from dietpi software uninstaller netdata delete my etc file mappe???

### ISSUE THREAD

**Issue by janbildsoehansen** [netdata/netdata#4678]
##### Question summary

sory for my bad english :/

want to delete netdata thru my dietpi software uninstaller just to install it again but after starting my uninstall of netdata sudenly it stop and made a erorr of some sort made a reboot not thinking more about it and then i cant boot up it says im missing some files

but the disk to my mac and can se that im missing my etc file folder now..??

##### OS / Environment

dietpi think is 6.17.12
##### Component Name

netdata
##### Expected results

nothing.. just want to share my trubles

**Comment by ktsaou** [comment]
Hi,

we are very sorry for that. The uninstaller does not delete anything without asking you. All `rm` commands are run with `-i` which means "ask the user", so it asks you for each and every directory and file it deletes.

Check the code here: https://github.com/netdata/netdata/blob/4e5e060e45f034dca720968d581185733b835748/netdata-installer.sh#L975-L1082

Do you have the console output of the uninstaller?

**Comment by janbildsoehansen** [comment]
ok but it dit on the uninstall via dietpi :(

all it says it error: file '/grub/i386-pc/normal.mod' not found
entering rescue mode...
grub rescue>

**Comment by ktsaou** [comment]
hm... so you installed a netdata package and you uninstalled it.
I don't know how to help you in this case. You should probably as for help at a dietpi community.

**Comment by janbildsoehansen** [comment]
haf hade it on my debian system for a wile. and it ditten wann update then i just uinstall it..
and it made a error some how and i reboot my machine and bum no etc folder no apache conf files no ssl certificats.. hade 5 live pages no only one is online for now :I

**Comment by janbildsoehansen** [comment]
it there any places to find a log to see what happen..?

**Comment by cakrit** [comment]
Apologies for not replying again @janbildsoehansen but there's really not much we can do. The uninstaller would have given you all the output on your terminal, so I'm afraid it's impossible to trace what happened. Please reopen if you believe there's anything we can help you with, though I really doubt it.
