### ISSUE TITLE
Renaming a docker container does not change its name in netdata

### ISSUE THREAD

**Issue by kachkaev** [netdata/netdata#4679]
##### Bug report summary

[Renaming a docker container](https://docs.docker.com/engine/reference/commandline/rename/) does not change its name in netdata

##### OS / Environment
* Linux my-hostname 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* netdata [9a071dea](https://github.com/netdata/netdata/tree/9a071dea2d73f663d9d478703c8c2ae85b4096a3) (being installed and updated directly on the host via an [ansible role](https://galaxy.ansible.com/jffz/netdata/))
* Docker version 18.06.1-ce, build e68fc7a

##### Component Name
docker (?)

##### Steps To Reproduce

```bash
## 1. create a new docker container
docker run --detatch --name my-container nginx:alpine

## 2. observe my-container in netdata's web UI

## 3.1. rename the container
docker rename my-container my-renamed-container

## 3.2. confirm that the container has been renamed 
docker ps | grep my-renamed-container

## 4. reload netdata UI, but still observe the old container's name in the list on the right

## 999. remove the container when it's time to finish the experiment
docker rm --force my-renamed-container
```

```ini
[global]
	 hostname = my-server
	 history = 21600
	 update every = 1
	 access log = none
```

##### Expected behavior

I've expected netdata to update the names of docker containers in the UI when they get renamed, however this does not happen even after hours of waiting. Looks like netdata caches the name of a container immediately at its creation and does not check again for it.

Here is what makes me rename the containers: I've got CI/CD pipelines, which update dockerized microservices on a VM with netdata. A typical script first creates a container named `${MICROSERVICE}--new`, then waits for the container to become healthy and if this has happened within 30 seconds, deletes the old `${MICROSERVICE}` container and renames `${MICROSERVICE}--new` to `${MICROSERVICE}`. If the healthy state is not reached, the new container gets killed and the pipeline is marked as failed.

Here's a simplified example of what a pipeline does:

```bash
docker run --detach --name ${MICROSERVICE}--new ${MICROSERVICE_IMAGE}
retry --tries=30 --min=1 --max=1 "[[ \$(docker inspect -f {{.State.Health.Status}} ${MICROSERVICE}--new) == 'healthy' ]]"

docker rename ${MICROSERVICE} ${MICROSERVICE}--old || true
docker rename ${MICROSERVICE}--new ${MICROSERVICE}
docker rm ${MICROSERVICE}--old --force || true

## error-recovery task
docker rm --force ${MICROSERVICE}--new || true
```

Despite that the new container has this `--new` suffix for only up to 30 seconds, the suffix preserves in the netdata's UI until I restart or update the tool. Watching the charts during the deploy is not necessary – it looks like netdata collects container metadata on their creation regardless of that. Caching container names is understandable, but it'd be still great if they had some TTL and eventually got updated.

Thank you so much for netdata folks! I'm excited about all these changes you've started making recently!

**Comment by paulfantom** [comment]
Name in the UI is taken from the hostname, not from container name. You cannot know about container name from inside of a container unless you mount a docker socket.

**Comment by paulfantom** [comment]
Also @kachkaev please tell me how did you install netdata using a docker container AND an ansible role which doesn't use docker containers?

**Comment by kachkaev** [comment]
👋 Hi @paulfantom and sorry if I was a bit unclear. The netdata is installed with the ansible role and so it is not sitting in a container. I do have some docker containers running on the same machine though and my issue is with their representation by netdata. Netdata has full access to the docker socket and it can successfully show me all metrics related to the containers. It just feels that it's not tracking container renaming events.

**Comment by ktsaou** [comment]
Yes, this is a feature request. Netdata reads the docker container name when it detects a container, but it does not refresh this name later.

Is there an event, or something we could use to detect this container rename, without polling for it?

**Comment by kachkaev** [comment]
https://docs.docker.com/engine/reference/commandline/events/

There seems to be a rename event in the list of container events. Is this stream what netdata is listening to already?

**Comment by ktsaou** [comment]
We are not listening for any events from docker. Netdata detects containers using CGROUPS.
But it would be interesting to listen for events from docker.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
