### ISSUE TITLE
Collector definition file to assemble collector-related info in one place

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#4685]
##### Feature idea summary
For each collector, we want a definition file (probably in yaml format) that would support the following:

- [ ] Provide info currently provided in dashboard_info.js (both help text and formatting info).
- [ ] Use it in the plugin where possible (i.e. have the definition of the charts in the yaml file).
- [ ] Generate parts of the documentation (e.g. charts, alarms)
- [ ] Documenting the alarms and possibly adding links to help people resolve them
- [ ] Test automation

##### Expected behavior

- Define the format (structure) of this file, so that other issues can be created to gradually move to using it.

**Comment by Ferroin** [comment]
>  Use it in the plugin where possible (i.e. have the definition of the charts in the yaml file).

I would very much prefer the reverse of this.  IOW, generate the charts definitions for the file from the plugin.  I would very much like to avoid depending on an extra data file for each module/plugin.

**Comment by l2isbad** [comment]
> generate the charts definitions for the file

nogo

**Comment by Ferroin** [comment]
@l2isbad The only problem I see with this is handling of things that dynamically generate charts, but providing definitions like we're talking about here is likely to be problematic for those regardless.

**Comment by cakrit** [comment]
Based on further discussion in Athens, we should just look into the following now: 

For each collector, we want a definition file (probably in yaml format) that would support the following:

- [ ] Provide info currently provided in dashboard_info.js (both help text and formatting info).
- [ ] Generate parts of the documentation (e.g. charts, alarms)
- [ ] Documenting the alarms and possibly adding links to help people resolve them

##### Expected behavior
- Define the format (structure) of this file, so that other issues can be created to gradually move to using it. 

We will generate such files initially only for the plugins that don't dynamically create charts.

**Comment by l2isbad** [comment]
We have agreed that we don't put charts definitions to that yaml file for all modules. We add new feature to plugins, they will generate charts definitions based on some mock input or something like that. I really don't like the idea to have charts definitions in a separate file. Doing that only for part of the modules looks even more ugly to me.

**Comment by ktsaou** [comment]
@cakrit 	the important part here is to have the chart definitions for the documentation.

Let @l2isbad 	decide how he likes this done. After all, if his solution does not work, he will have to somehow find a way to fix it... :)

**Comment by cakrit** [comment]
We discussed a lot with @ilyam8 and there's no solution that doesn't require work on every collector. It's a lot of work and will add complexity. I will see what quality of info we can get from a generic script that reads (and/or loads) the code, perhaps with a few methods here and there and we will need to discuss the direction again.
