### ISSUE TITLE
requirements.txt in TLD are not related to netdata

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4693]
##### Bug report summary

Documentation scripts added files confusing to contributors and not related to netdata software such as:
- requirements.txt
- runtime.txt

Especially that we are using python inside and both files relate to python.

##### OS / Environment

All

##### Component Name

Python, Documentation

##### Steps To Reproduce

```yaml

```

##### Expected behavior

No such files in top level directory.

**Comment by cakrit** [comment]
Netlify doesn't work without them.
Under https://www.netlify.com/docs/#helpful-hints, see the python section:

> You want to make sure that Netlify knows exactly which versions of various Python plugins you are using. Do this by creating a file called requirements.txt in your project’s root directory: pip freeze > requirements.txt
You can tell Netlify which version of Python to use to build your site by placing a runtime.txt file in your project’s root directory.

**Comment by cakrit** [comment]
I created a dummy site deployed from a personal branch that doesn't have the files, you can see it in https://app.netlify.com/sites/eloquent-kilby-5943bf/overview
There are no options to move those files elsewhere and I doubt we can do something from inside the build script itself.

**Comment by paulfantom** [comment]
Another reason not to have docs mixed with code :stuck_out_tongue:

**Comment by cakrit** [comment]
I will ask Netlify if they can add an option to specify the path for these files.

**Comment by cakrit** [comment]
I asked their support. Will close this for now. If Netlify does provide a setting to specify their location, it will be a very quick fix.

**Comment by paulfantom** [comment]
> I asked their support.

So why close this issue? I would understand closing it **after** getting response from them, not before. Closing it when it is essentially in progress seems very strange.

**Comment by cakrit** [comment]
Yes, you're right. I got an answer, I can move the files under htmldoc by adding a netlify.toml at the root directory that points there. It's better than having these files there, so I'll do it.
