### ISSUE TITLE
Metrics in users.mem and apps.mem over physical memory

### ISSUE THREAD

**Issue by AleAntunez** [netdata/netdata#4698]
Hi there,

We're trying to profile and application using Netdata so we can see the overall RAM usage of it. While the system memory seems to be correct (Within the physical memory bounds), it is not the case for the apps.mem and users.mem, which values seems to be over the physical memory in our machine.

![imagen](https://user-images.githubusercontent.com/1734346/48788413-134bbb00-eceb-11e8-8ca2-490c8f7a171b.png)

In our case, this machine has 256Gb of RAM, but the apps.mem and users.mem charts looks like this:

![imagen](https://user-images.githubusercontent.com/1734346/48788306-d4b60080-ecea-11e8-9ffb-384aa1d71bd2.png)

![imagen](https://user-images.githubusercontent.com/1734346/48788321-e13a5900-ecea-11e8-8971-a4375093dd4f.png)

Maybe we are misunderstanding this values but it looks like they are wrong. It could be the case?.

Thanks a lot!.

**Comment by ktsaou** [comment]
@vlvkobal to trace such issues, it would be nice to provide an `apps.plugin` command line switch, to dump some information about the grouping it does. This is not high priority (to do it now), but it would help to have it, so please add it to your roadmap.

**Comment by AleAntunez** [comment]
Hi,

thanks for your reply. We're attaching below a snapshot where the problem reported can be observed.

Thanks!

[netdata-20181122-111134-3206.zip](https://github.com/netdata/netdata/files/2607835/netdata-20181122-111134-3206.zip)

**Comment by ktsaou** [comment]
You are using an older netdata.
Could you please update to the latest version and provide the snapshot again?

**Comment by AleAntunez** [comment]
These are the results for the latest version of netdata (v1.11.1-4-g1149ce3_rolling).

![imagen](https://user-images.githubusercontent.com/1734346/48932964-b294cc00-eefe-11e8-9837-76e2efcc4906.png)

![imagen](https://user-images.githubusercontent.com/1734346/48932952-a4df4680-eefe-11e8-82c6-88f184a28a9c.png)

We're also attaching the snapshot:

[netdata-20181123-085929-300.zip](https://github.com/netdata/netdata/files/2610041/netdata-20181123-085929-300.zip)

Thanks!

**Comment by ktsaou** [comment]
ok, this is nice!

I understand this is your ssh session and it seems long standing (not just a spike), so we can trace it.

If you run `sudo ps fax` you will see the whole process list as a tree. Could you please post here the tree of your `ssh` session? Once we have the PIDs of the processes, we will need `cat /proc/PID/statm` for all of them.

**Comment by AleAntunez** [comment]
Hello,

we've re-executed to get all the data. This is, again, the memory profile:

![imagen](https://user-images.githubusercontent.com/1734346/49014731-60afa880-f181-11e8-9cd5-56854576af22.png)

![imagen](https://user-images.githubusercontent.com/1734346/49014750-70c78800-f181-11e8-8a9c-ad19ada56097.png)

And we're attaching the snapshot, ad the requested process data.

[netdata-20181126-133216-685.zip](https://github.com/netdata/netdata/files/2615580/netdata-20181126-133216-685.zip)

[process_tree.txt](https://github.com/netdata/netdata/files/2615558/process_tree.txt)

[process_statm.txt](https://github.com/netdata/netdata/files/2615559/process_statm.txt)

Thanks!

**Comment by AleAntunez** [comment]
Hi,

is there anything else you need from our side?

Thanks!

**Comment by vlvkobal** [comment]
@AleAntunez are you still experiencing the issue? If it's still relevant, could you please compile #6375 with debugging enabled `CFLAGS="-O1 -ggdb -DNETDATA_INTERNAL_CHECKS=1" ./netdata-installer.sh` and run `apps.plugin debug` for a few seconds. Please provide the debug output, netdata snapshot, process tree, and process statm.

**Comment by vlvkobal** [comment]
I'm closing the issue given that it's stale. @AleAntunez feel free to reopen it if you can provide more data.
