### ISSUE TITLE
Random number example data not matching?

### ISSUE THREAD

**Issue by jakk2809** [netdata/netdata#4702]
##### Question summary

I have enabled the 'example' Python plugin and I'm trying to understand why I can't find any matching data from the Python plugin debug tool and the plot I see in a web browser. I run the commands below to get a print out of what is being generated.

```
sudo su -s /bin/bash netdata
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace example
```

When I hover over the chart in a web browser I can't find any matching data. When I hard-code values into the example, I can see it matching on the graph (it's 1 second off, but at least the expected data is there).

I'm wondering if this is because of interpolation or maybe the random number generator?

Netdata seems to be a good plotting solution (I need to plot sensor data once per second), but I want to make sure it plots exactly what I send it.

##### OS / Environment

Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-39-generic x86_64)

##### Component Name

https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/example

##### Expected results

Data sent to Netdata with the Python plugin match the chart, even when generating random numbers.

Thank you.

**Comment by l2isbad** [comment]
Hi @jakk2809 

There is no interpolation in `example` python module (no interpolation for `absolute` values). Netdata plots exactly what it sends.

`example` uses random number generator, yes.

**Comment by jakk2809** [comment]
Hi @l2isbad 

Hmm, interesting. Here is a screenshot of what I'm seeing:

![image](https://user-images.githubusercontent.com/7157378/48864399-84818180-ed70-11e8-8527-dbe7751b4768.png)

While hovering over the data point at 9:25:28, the data from the debug tool doesn't show it. It just seemed a little strange when working with the random numbers and I'm not sure what's causing it.

**Comment by l2isbad** [comment]
@jakk2809 

These are two different instances of `python.d.plugin`.

https://github.com/netdata/netdata/blob/87cb02e50d38c558f8c9b022103e9a53ce997c00/collectors/python.d.plugin/example/example.chart.py#L46

Every value is random

**Comment by jakk2809** [comment]
@l2isbad 

Oh, I see. So that debugging tool is running another instance. Is there a way to check the 'raw data' being shown in the chart from the console?

Thank you.

**Comment by l2isbad** [comment]
> So that debugging tool is running another instance

Exactly.

Netdata shows `absolute` raw values as-is and does interpolation for `incremental` (if algorithm isn't  specified for a dimension `absolute` is being used)

**Comment by cakrit** [comment]
@l2isbad I couldn't find in our documentation the answer to this: 
>Is there a way to check the 'raw data' being shown in the chart from the console?

How would we do it e.g. for a Python module?
I think it could be a good addition to the [documentation](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/README.md)

**Comment by ilyam8** [comment]
> Is there a way to check the 'raw data' being shown in the chart from the console?

`python.d.plugin` has  debug mode, there you can see all data it pushes to `netdata`. This is 100% in the docs.

Example output:

Creating charts

```
CHART netdata.runtime_example '' 'Execution time for example' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

CHART example.random '' 'A random number' 'random number' 'random' 'random' line 90000 1 '' 'python.d.plugin' 'example'
DIMENSION 'random1' 'random1' absolute 1 1 ''
DIMENSION 'random2' 'random2' absolute 1 1 ''
DIMENSION 'random3' 'random3' absolute 1 1 ''
```

Updating charts
```
BEGIN example.random 0
SET 'random1' = 54
SET 'random2' = 88
SET 'random3' = 48
END

BEGIN netdata.runtime_example 0
SET run_time = 0
END

BEGIN example.random 1002636
SET 'random1' = 39
SET 'random2' = 49
SET 'random3' = 11
END

BEGIN netdata.runtime_example 1002636
SET run_time = 0
END
```

> shown in the chart from the console?

Depends on [dimension algorithm](https://docs.netdata.cloud/collectors/plugins.d/#dimension).

**Comment by ilyam8** [comment]
@jakk2809 if you have any question feel free to ask
