### ISSUE TITLE
Should use IEC-compliant abbreviations, e.g. KiB, MiB, etc.

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#4711]
As those are multipliers of 1024, then according to IEC standard their unit should be represented in kibibytes (KiB), mebibytes (MiB) and so on. KB, MB and alike are reserved for multipliers of 1000 so there is no confusion with SI standards of unit naming.

Standard was also implemented by IEEE in 2002 as IEEE 1541-2002.

Original issue:
https://github.com/netdata/netdata/pull/4707

**Comment by paulfantom** [comment]
IEEE 1541-2002 standard:
  - full: https://standards.ieee.org/standard/1541-2002.html
  - overview: https://en.wikipedia.org/wiki/IEEE_1541-2002

ISO/IEC:
  - overview: https://en.wikipedia.org/wiki/ISO/IEC_80000

**Comment by paulfantom** [comment]
If most of the world you mean Microsoft and other slow moving corporations - then yes. On the other hand most of the Open Source world adopted those standards and most software which does monitoring use them, for example DataDog: https://docs.datadoghq.com/developers/metrics/#units. 

One major space where those are super important is storage and example is simple. When you buy 1TB hard drive this storage space is represented in SI format (1000x multiplier), but later you use ISO/IEC format (1024x multiplication). Depending what you want to represent, those will be different.

Side note: this is one of the reasons why there is no prefixes and only standard units (for example bytes and not kilobytes) in OpenMetrics format.

**Comment by cakrit** [comment]
Fine, I saw a few more monitoring solutions that support IEC units as well, so let's do it. We'll need to keep it in mind when we try to work with Windows though :)

**Comment by ktsaou** [comment]
Yes, let's do it.
This would require quite a few changes, in data collection modules and the autoscaling of units at the dashboard.

**Comment by gmosx** [comment]
Should we keep both x1000 and x1024 multipliers in `unit-conversion.js`?

**Comment by cakrit** [comment]
We had some more discussions on this. 
Netdata today already means "KiB" when the collectors send and the UI present "KB" (i.e. 1024 is used everywhere). The exception is that of network speeds (e.g. Kilobit/s), which are and will always remain based on multiples of 1000. The action plan is the following:
- [ ] Verify that there are no exceptions that may have been missed in any collectors.
- [ ] Just add to the autoscaling unit conversions the KiB, MiB etc, with the same divisor, 1024. Do not change the current conversion for KB, MB etc.
- [ ] Switch collectors to use KiB, MiB etc. in their unit names. Doesn't have to be done at once.
- [ ] Once all the collectors have been changed and we get no more KB, MB etc, either remove the KB, MB conversions from the web gui for autoscaling, or modify them to use 1000, in case the need arises in the future.

The end state where collectors just send back SI units (e.g. octets) requires a breaking change, that can't be introduced until 2.0.

**Comment by Ferroin** [comment]
Possibly stupid question, but weren't we talking at some point about switching the collector API to only use base units (bytes for example)?  If we were, this would be an ideal time to implement that too, as we're already going to be tweaking things there as-is.  If we did go that way, we could also set up the dashboard to let users choose whether to use SI or IEC units on the dashboard itself, which would be awesome.

**Comment by cakrit** [comment]
Not a stupid question at all, it was already discussed and I refer to it in the last sentence of my previous post. This one will be a breaking change affecting also alarm triggers, as we will not just be talking about unit naming any more, but about changing the metric itself.

**Comment by ktsaou** [comment]
> This one will be a breaking change affecting also alarm triggers

and backends - so everyone using netdata backends with `average` data source will be affected too.

Switching to standard units, has to be done at the next major release.

**Comment by gmosx** [comment]
This turns out to have a bigger impact, moving to the next milestone.

**Comment by gmosx** [comment]
@cakrit After Vladimir's and Ilya's changes, is there anything else that needs to be implemented on the front-end side?. What else is missing to close this issue?

**Comment by cakrit** [comment]
node.js and apps plugins still need to be changed.

**Comment by vlvkobal** [comment]
Units in apps.plugin were changed in #4985. Did you mean some other plugin?

**Comment by pm73** [comment]
Seems like it changed metrics names (used e.g. by Prometheus/Grafana).

**Comment by cakrit** [comment]
I went through the node.d plugins, there are no related metrics in any of them. So once #5049 is merged, this can be closed.

**Comment by PhilsLab** [comment]
Why not internally handle those values as bytes?
When handling the data with the netdata-frontend or even Grafana (via Prometheus, Influx, ...),
the user gets to choose how to represent the raw data.
