### ISSUE TITLE
web server URL parsing ignores escaped characters

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4717]
There is a bug at the internal web server of netdata. It parses the URLs like this:

1. a request comes

2. it checks it received the whole of it (it searches for `\r\n\r\n` - i.e. an empty line as defined in the spec)

3. BUG 1: it decodes the whole URL. This is a bug since any `/` or `?` URL encoded will be decoded before actually parsing the URL. To work properly it should decode the URL part by part (i.e. first split it in its parts and then decode each part of it). **The way it is now, URL encoding cannot be used to encode characters that are URL control characters (`/`, `?`, `&`, `%`).** Even when URL encoded, these character will still play an important role in URL parsing (although they are escaped).

4. BUG 2: it does not separate URL `path` from URL `query string`. It treats the whole URL as a continuous string, separated by `/?&`, which of course leads to bugs like the one we face here.

So, the right flow should be like this:

1. receive the request

2. make sure it received the whole of it

3. split the path from the query string

4. URL decode the path to find the API command or the filename to be served

5. split the query string in its parts (separated with `&`)

6. for each part of the query string, split it at the `=` sign to find the `name` and `value` and decode both of them.

I think the whole HTTP parser needs to be rewritten.

Related to #4716 #4714 #3253

**Comment by cakrit** [comment]
Isn't this closed by #4716 ? What is left to do?

**Comment by ktsaou** [comment]
I applied a fix to make parsing a bit more strict, but the whole HTTP parser is faulty. It needs to be rewritten. Not high priority, but this will eventually lead to issues as netdata matures.
