### ISSUE TITLE
Example of Custom Dashboards 

### ISSUE THREAD

**Issue by matyhaty** [netdata/netdata#4726]
Thought this might be useful for those also looking
We created a dashboard like this today......

Each card is a different server.
The guage is current CPU
Then RAM %, HDD Space %, Outgoing Data (MB/s), And CPU History.
The green bar indicates which one is getting updated. Once done is loves onto the next
The right hand column will show any current alarms (which remove when resolved)

We are running this on a Raspberry Pi - using the excellent FullScreenOS project.
It runs lovely on a HD (1920x1080) TV

Hope it inspires people to make awesome things.

https://pasteboard.co/HOuCTES.png

Enjoy!

**Comment by ktsaou** [comment]
nicely done!
thank you for sharing it.
It would be nice if you could also share the source HTML file.

**Comment by lucasbaccan** [comment]
> Thought this might be useful for those also looking
> We created a dashboard like this today......
> 
> Each card is a different server.
> The guage is current CPU
> Then RAM %, HDD Space %, Outgoing Data (MB/s), And CPU History.
> The green bar indicates which one is getting updated. Once done is loves onto the next
> The right hand column will show any current alarms (which remove when resolved)
> 
> We are running this on a Raspberry Pi - using the excellent FullScreenOS project.
> It runs lovely on a HD (1920x1080) TV
> 
> Hope it inspires people to make awesome things.
> 
> https://pasteboard.co/HOuCTES.png
> 
> Enjoy!

Can you share the code used in your custom dashboard ?
