### ISSUE TITLE
openmetrics and prometheus data collection (and possibly graphite and opentsdb)

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4730]
## Motivation

[OpenMetrics](https://github.com/OpenObservability/OpenMetrics) is becoming the de-facto format for application metrics. This format assumes that applications willing to expose metrics, will be listening to an HTTP endpoint and the monitoring system should pull metrics at regular intervals by scraping that HTTP endpoint.

OpenMetrics exposition format is very close to the [Prometheus one](https://prometheus.io/docs/instrumenting/exposition_formats/).

At the same time, there are hundreds of [prometheus exporters](https://prometheus.io/docs/instrumenting/exporters/) available.

So, netdata could benefit significantly by collecting metrics from prometheus and openmetrics sources.

Also, since netdata is generally more efficient for collecting metrics with 1s granularity, all these applications will also benefit when monitored by netdata.

## How to do it

netdata needs some additional metdata about the metrics. It needs to group them together into meaningful charts. These metadata are not available in the OpenMetrics or Prometheus exposition formats.

We have 2 options to provide these metadata:

1. Write an `openmetrics.plugin` to collect the metrics and then provide a feature like the statsd "synthetic charts" one, that will pattern match the collected metrics to provide meaningful charts. If we go this way, to support new openmetrics and prometheus sources we will need to provide a config file for the "synthetic charts" configuration of each source.

2. Write python or go modules for each of the openmetrics and prometheus sources. If we go this way, to support new openmetrics and prometheus sources will need to develop a module to add the missing information.

Both are valid setups.

Ideally we should prefer the first ("synthetic charts"). It is harder and more complex, but it will also be useful for:

- statsd metrics
- graphite metrics (i.e. let netdata become a "graphite server")
- opentsdb metrics (i.e. let netdata become an "opentsdb server")

So, we could develop a generic mechanism for correlating metrics into meaningful entities.

The second option, will allow immediate results, since it can be implemented in just a matter of days (i.e. add an "OpenMetricsService" to python.d.plugin) and just a few hours for each of the sources we would like to collect metrics from.

There could also be a mixed setup: start with the second option and as things mature and generic "synthetic charts" is a reality, replace code (modules) with configs ("synthetic charts").

**Comment by cakrit** [comment]
I vote to go directly to a generic openmetrics plugin (and similar plugins for the other sources). We write it once and then it's just config files.

**Comment by cakrit** [comment]
We discussed it with Costa and it looks like the best approach for OpenMetrics is indeed a plugin orchestrator with modules for each OpenMertics exporter. The reason is that the modules give us a great deal of flexibility in how to organize the metrics. 

Graphite and OpenTSDB push metrics, just like statsd, so for them extending the current functionality in statsd (which includes synthetic charts) seems like a much better idea. Something like this was already requested in #4235.

**Comment by ktsaou** [comment]
The main issue being discussed here, is how we will add more data collection sources to netdata. Since OpenMetrics is the upcoming standard, we should support it and we should do it in the best possible way:

1. it should be easy to add more data collection sources
2. it should be easy to correlate the metrics add the missing metadata (i.e to form meaningful dashboards using the collected metrics)

So, let's focus on the alternatives to do this.

**Comment by ilyam8** [comment]
This is tagged v1.12, but the issue is more like `discussion` for me.

**Comment by ilyam8** [comment]
* python [PrometheusService ](https://github.com/netdata/netdata/pull/5177)
 * go [equivalent](https://github.com/netdata/go.d.plugin/tree/master/pkg/prometheus)

So we can parse openmetrics data, but that's all about it.

**Comment by cakrit** [comment]
After more recent discussions, we'll need a deeper design on how handle metrics with multiple dimensions (labels, tags) before we can proceed with something more meaningful.

**Comment by amoss** [comment]
@mfundul This is relevant to your industry research for the db roadmap. Please take a look at openmetrics in the context of how we organize metrics / charts.

**Comment by fzyzcjy** [comment]
Hi! I wonder what is the current state? Thanks!

**Comment by cakrit** [comment]
This is released.
