### ISSUE TITLE
Free memory shows as 'inactive' in FreeBSD

### ISSUE THREAD

**Issue by yzgyyang** [netdata/netdata#4737]
##### Bug report summary

I found that on FreeBSD, most of the free memory are in the 'inactive' memory category. This results in a constant warning of memory used by 95%+. My server is at https://netdata.ygy.io/.

##### OS / Environment

```
➜  ~ uname -a
FreeBSD FreeBSD-Main 11.2-RELEASE-p2 FreeBSD 11.2-RELEASE-p2 #0 544d31706a5(releng/11.2)-dirty: Sun Aug 26 11:04:35 CST 2018     root@bsd:/usr/obj/usr/xhx/sys/GENERIC  amd64
```

##### Component Name

ram

##### Steps To Reproduce

default configuration

default

##### Expected behavior

I expect the free memory to be displayed as-is, not in the 'inactive' memory category. This results in a constant warning of memory used by 95%+.

**Comment by Ferroin** [comment]
Netdata is almost certainly correct that you have that much inactive memory.  FreeBSD, like most UNIX systems, frees memory when space is needed, not when the last reference to that memory is dropped.  So all that inactive memory is reusable by the system, but is not technically free.

Given this, the correct fix would seem to be to update the memory usage alarm to account inactive memory on FreeBSD just like it accounts cached memory on Linux, that is, treat it as a type of free memory.

**Comment by ktsaou** [comment]
> Given this, the correct fix would seem to be to update the memory usage alarm to account inactive memory on FreeBSD just like it accounts cached memory on Linux, that is, treat it as a type of free memory.

This seems simple. Can you make a PR?

**Comment by Ferroin** [comment]
Just took a look at the current upstream version, and it looks to me like we already are accounting it.  The listed calculation line for the raised `ram_in_use` alarm on the linked dashboard is different from what the upstream alarm config shows, displaying: 

    (($active + $wired) - $used_ram_to_ignore) * 100 / (($active + $wired) - $used_ram_to_ignore + $cached + $free)

instead of:

    ($active + $wired + $laundry + $buffers - $used_ram_to_ignore) * 100 / ($active + $wired + $laundry + $buffers - $used_ram_to_ignore + $cache + $free + $inactive)

**Comment by ktsaou** [comment]
> The listed calculation line for the raised `ram_in_use` alarm on the linked dashboard is different from what the upstream alarm config show

@yzgyyang could you please update your netdata?

**Comment by yzgyyang** [comment]
Thank you everyone, I found out that I was using `quarterly` instead of `latest` which prevents me from updating to the latest netdata. I can confirm that the indication is correct on my latest netdata:

```
➜  ~ pkg info netdata
netdata-1.11.0
Name           : netdata
Version        : 1.11.0
Installed on   : Tue Dec 11 16:46:35 2018 CST
Origin         : net-mgmt/netdata
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : net-mgmt
Licenses       : GPLv3
Maintainer     : mmokhi@FreeBSD.org
WWW            : https://github.com/firehol/netdata
Comment        : Scalable distributed realtime performance and health monitoring
Options        :
	FREEIPMI       : off
Shared Libs required:
	libuuid.so.1
Annotations    :
	FreeBSD_version: 1200086
	repo_type      : binary
	repository     : FreeBSD
Flat size      : 7.19MiB
Description    :
Netdata is scalable distributed realtime performance & health monitoring system
netdata collects and visualizes metrics.
If it is a number and it can be collected somehow, netdata can visualize it.
Out of the box, it comes with plugins that collect hundreds of
system metrics and metrics of popular applications.
Netdata is very resource efficient and you can control its resource consumption.
It will use some spare CPU cycles, usually just 1-3% of a single core,
the RAM you want it have, and no disk I/O at all, apart its logging.

WWW: https://github.com/firehol/netdata
```
