### ISSUE TITLE
How Can I refresh custom chart of netdata of different server after clicking on server option?

### ISSUE THREAD

**Issue by ShankarSharma01** [netdata/netdata#4745]
##### Question summary

Currently I am refreshing chart after click on a button, I am including dashboard.js of server, but the chart data remains the same. It should be reflect on the basis of server url.

**Comment by ktsaou** [comment]
I am not sure I understand the question.

You want to create a custom dashboard with charts coming from different servers?

The dashboard you have created is not refreshing the charts?

Something else?

**Comment by ShankarSharma01** [comment]
can you please help me to out this?

**Comment by ShankarSharma01** [comment]
Yes.

I have list of servers, when I click one of them, then my chart should be reflect with data on that particular server.


________________________________

**Comment by ktsaou** [comment]
I am sorry, but I still don't get it. Can you post a few screenshots of your problem?

**Comment by ShankarSharma01** [comment]
Its ok, No problem.

I just want to know, where i have to mentioned the server ip address when refresh the chart?

**Comment by cakrit** [comment]
Are you referring to the bug in #4721? That one was fixed by #4733 
If not, maybe you can read [the registry documentation](https://docs.netdata.cloud/registry/) to understand how the 'my-netdata' menu works. 
Without a registry, you have to separately point your browser to the netdata URL of your server(s).

**Comment by bitcoiners** [comment]
I have a similar question. 
I created a custom dashboard that uses jquery tabs for groups of netdata monitored servers.
When I switch between tabs, charts are not activated automatically and only show up after some action on the screen like scrolling down the page.
It seems netdata charts need to be refreshed or activated after tabs switch. 
Any advice on how I can to that?

**Comment by bitcoiners** [comment]
Anyone? Please advise. Thanks.

**Comment by bitcoiners** [comment]
Tried NETDATA.chartRefresherReschedule();
Same result.

**Comment by bitcoiners** [comment]
I can send you my source code if you want to try it yourself.

**Comment by gmosx** [comment]
FWIW, we are working on custom / multi-server dashboards that will hopefully be 'available soon (sic)'.
