### ISSUE TITLE
Create documentation on how to opt-out of anonymous data collection

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#4746]
Related to #2760 and #4735 

The page should explain what is collected and how to turn it off and needs to be updated every time a change in the anonymous data collection process is done. 

The page should link to our privacy policy.

**Comment by cakrit** [comment]
I reviewed our instructions on Security in docs/netdata-security.md and registry/README.md. 

- [x] Security information is very prominent in our new documentation, [here](https://docs.netdata.cloud/docs/netdata-security/) and [here](https://docs.netdata.cloud/registry/#what-data-the-registry-maintains)
- [x] User IPs are no longer collected (documentation corrected in PR #4786)
- [ ] The hub will require opt-in to connect to the registry.
- [ ] We will add our privacy policy to the documentation
PR #4743 will "read the opt-out file from netdata and expose it to the dashboard"

As soon as the privacy policy is added, I will update the other tickets and close this one.

**Comment by ktsaou** [comment]
User IPs were never collected.
They were only stored at web server access.log files.

**Comment by cakrit** [comment]
#2760 was updated
