### ISSUE TITLE
Change in Incomming Webhooks Slack API breaks alerts

### ISSUE THREAD

**Issue by krinfels** [netdata/netdata#4755]
##### Bug report summary
Slack ignores "channel" and "username" parameters.
The API has been changed so that now it is required to specify the channel the messages will be posted to during the creation of a webhook 

>The majority of your legacy code for sending messages using incoming Webhooks should continue to work within a Slack app without much modification; the only thing you can no longer do is customize the destination channel and author identity at runtime.

 [source](https://api.slack.com/custom-integrations/incoming-webhooks)

I guess that it also makes #3722 obsolete.

##### OS / Environment
> uname -a
>Linux mindal 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### Component Name
slack.alert

##### Steps To Reproduce
Create new incomming webhook by following this [guide](https://api.slack.com/incoming-webhooks)
Set DEFAULT_RECIPIENT_SLACK parameter in health_alarm_notify.conf.
Try to send an alert to that channel by using ./alarm-test.sh script.

##### Expected behavior
Alert being send to chosen channel

**Comment by cakrit** [comment]
Thanks, I noticed the other day too. It's a documentation issue, the integration does work. I'll test it with random values in DEFAULT_RECIPIENT_SLACK and update the instructions accordingly.

**Comment by cakrit** [comment]
I did some tests, you can still specify a different channel or even a user and it overrides the default configuration in the webhook. 
I am removing the default addition of '#' to the "channel", so it can support both channels and users
netdata will add the '#' if it's not already there in the recipient, for backwards compatibility.
You can't just leave the default recipient empty, as this has a special meaning to netdata. So we can say that if the recipient is just a '#', this means that netdata will not be sending the channel at all. This means that you'll only need to configure the channel or the user on Slack.

**Comment by krinfels** [comment]
>I did some tests, you can still specify a different channel or even a user and it overrides the default configuration in the webhook.

That is weird. Before posting this issue I have tried setting DEFAULT_RECIPIENT_SLACK to different values and the alerts would always appear on channel that was assigned to the webhook during its creation. Perhaps you are using a webhook that was created before the API change?

**Comment by cakrit** [comment]
Nope, I just added another webhook and Slack is clear about it: 

> Channel Override
> Incoming webhooks have a default channel, but it can be overridden in your JSON payload. A public channel can be specified with "channel": "#other-channel", and a Direct Message with "channel": "@username".

**Comment by krinfels** [comment]
You're right. The problem was that I created the webhook following the official [guide](https://api.slack.com/incoming-webhooks), however using the webhook created with [this](https://my.slack.com/apps/A0F7XDUAZ-incoming-webhooks) seems to do the trick.
The main issue is that changing the channel has been disabled when using the "new" webhooks that are attached to an app, but since one can still create a legacy one this is not a problem right now.
On the side note slack considers that second method [deprecated](https://api.slack.com/custom-integrations).

**Comment by cakrit** [comment]
I will try it out and update the documentation accordingly in a different PR, with lower priority. The new webhooks will work when you put `DEFAULT_RECIPIENT_SLACK="#"` in health_alarm_notify.conf, so this issue will be closed with the merge of #4765
