### ISSUE TITLE
Python.d.plugin infinite retries, ignore penalty, and plotting 'None'

### ISSUE THREAD

**Issue by jakk2809** [netdata/netdata#4756]
##### Feature idea summary

These 3 features kind of work together so charts update, even if there is no data. I have a RabbitMQ queue that has data from another program being published to it every second. I wrote a python.d.plugin that subscribes to this data and passes it on to Netdata to plot (update_every = 1). However, if the source stops publishing data, it would be nice if the plot (optionally) continued to update, even if there is no data. Also, if some/all of the keys of the dict returned by `get_data` is None, a blank 'SET id = ' statement could be printed so that the plot continues.

I sort of had this working by changing `charts.py` and `SimpleService.py`, but my Netdata auto-updated so my changes are gone, whoops.

##### Expected behavior

Infinite retries: Would keep retrying to updating the chart.
Ignore penalty: Retries would happen `update_every` instead of getting longer with consecutive failed retries.
Plotting 'None': Print out "SET id = " for dimensions that are 'None' so the chart does not freeze.

**Comment by ilyam8** [comment]
> Infinite retries:

Retries is user configurable. Actully i don't think we need it at all (i removed it in [go.d](https://github.com/netdata/go.d.plugin)). 

I think we can remove it from `python` too @Ferroin @ktsaou 

> Ignore penalty

Penalty is nice. But we can make it user configurable.

>  Print out "SET id = " for dimensions that are 'None' so the chart does not freeze

This won't work

**Comment by Ferroin** [comment]
> Retries is user configurable. Actually i think we don't need it at all (i removed it in go.d).
> 
> I think we can remove it from python too @Ferroin @ktsaou

I don't think we need retrying on updating the chart, provided that it properly updates when new data starts coming back in.

We absolutely need to keep any retrying related to auto-detection though (although giving that some kind of exponential back-off might be a good idea).

**Comment by ilyam8** [comment]
Oh, my bad. I was talking about module [retries](https://github.com/netdata/netdata/blob/79df60266d07033ed4dc652f95a1140297506116/collectors/python.d.plugin/python.d.plugin.in#L51).

**Comment by ilyam8** [comment]
> ignore penalty

Chart penalty? You can disable it per module/job 

https://github.com/netdata/netdata/blob/79df60266d07033ed4dc652f95a1140297506116/collectors/python.d.plugin/beanstalk/beanstalk.conf#L42-L50

**Comment by ilyam8** [comment]
> We absolutely need to keep any retrying related to auto-detection though

We have `retries` option, job dies after it fails to update n `retries` in a row. I don't like it.
I think we should keep trying to recover indefinitely (with optional exponential back-off enabled by default ofc).

**Comment by Ferroin** [comment]
@ilyam8 Seconded.  Even though I start Netdata after almost everything else on my systems, I regularly have to restart it a few minutes after the system finishes booting just so it detects everything it's supposed to be monitoring.

**Comment by ilyam8** [comment]
> Of course, having infinite retries

No, if job `check()` fails, plugin drops the job (if it's not `autodetection retry` job).
`Retries` option is for jobs which passes check. That is why i suggest to remove it - if job passes check we should never kill it.

**Comment by ilyam8** [comment]
@jakk2809 

> so charts update, even if there is no data.

Updates with what? With previously collected data?

**Comment by Ferroin** [comment]
@ilyam8 Ah, I misunderstood how the auto-detection retry stuff actually works, sorry about the confusion.  That said, I still think having infinite retries and exponential back-off for them makes sense.

**Comment by jakk2809** [comment]
> This won't work

Sorry, I guess printing a blank 'SET' line isn't necessary. Omitting the dimension completely doesn't freeze the graph or causes errors, my mistake. Here is what I was doing to print None:

![image](https://user-images.githubusercontent.com/7157378/49040915-eb83a980-f167-11e8-8499-aef21d239b3f.png)


Things to seem to freeze when all the dimensions are set to None. I'm guessing that's because there are no SET statements between the BEGIN and END statements.


> Updates with what? With previously collected data?

Updating with blanks. It shows as '-' in the graph and the point is not plotted. Makes it easy to see Nones.

![image](https://user-images.githubusercontent.com/7157378/49040816-b1b2a300-f167-11e8-823f-a28242926f5d.png)

**Comment by ilyam8** [comment]
> Things to seem to freeze when all the dimensions are set to None. 

Thats by design and this is valid.

**Comment by jakk2809** [comment]
> Thats by design and this is valid.

Okay. I guess the main thing is the infinite retries and optional exponential back-off.

**Comment by ilyam8** [comment]
`SET `data2` = ` is only handy in debugging

Empty `SET` and not `SET` is same for netdata

**Comment by ilyam8** [comment]
Ok, let's start from the beginning. 

What exactly are you trying to achieve? :smile:

**Comment by ilyam8** [comment]
> Some of this data can be None so I would like Netdata to not plot the None, but plot other dimensions if there is good data.

it's default behaviour, netdata does exactly that.

>  If the RabbitMQ queue is sent data again, I would like Netdata to resume plotting the data immediately.

same, default behaviour. 
By default `python.d` plugin supresses charts which weren't updated `chart_cleanup` times in a row (charts considered updated if at least one dimension was updated). This can be overriden in module configuration file (`charts_cleanup: 0`)

**Comment by ilyam8** [comment]
So the problem is `penalty` thing.

**Comment by ilyam8** [comment]
Sum it up:
 * remove retries completely (job retries)
 * make job `penalty` (exponential back-off) optional, but enabled by default.

**Comment by jakk2809** [comment]
> Sum it up:
> 
> * remove retries completely (job retries) (or make it configurable, infinite by default)
> * make job `penalty` (exponential back-off) optional, but enabled by default.

Yes. I think so.

**Comment by ktsaou** [comment]
Another solution would be for the UI to pick up the lack of updates and visualize them.

Today we have this problem in many more cases. For example:

1. a container is not updated any more but someone views its charts. There is no indication it stopped receiving updates and there is no way to push empty chart updates for it (its charts are marked `obsolete` in netdata).

2. there is a network failure and a netdata slave cannot push metrics to a netdata master anymore (viewers of the master are not aware of this).

So, we could modify netdata, to automatically mark the charts as `stale` after loosing a few updates and expose this flag to API responses, so that `dashboard.js` will pick it up and "ghost" the chart, or something similar.

I think this is a bit more universal solution. There should be setting in `netdata.conf` to indicate the number of lost updates to mark charts as `stale`.

What do you think?

**Comment by ilyam8** [comment]
This is great. I like it!


[This](https://github.com/netdata/netdata/issues/4756#issuecomment-441808299) still should be implemented.

**Comment by ktsaou** [comment]
> [This](https://github.com/netdata/netdata/issues/4756#issuecomment-441808299) still should be implemented.

sounds reasonable (infinite retries by default, exponential back-off enabled by default - both configurable).

**Comment by ilyam8** [comment]
I am not sure about configurable retries. It makes no sense to me. Why should we stop it? I suggest to make it non configurable. We will change it only if there will be request for that feature with use case.

**Comment by ktsaou** [comment]
> I am not sure about configurable retries. It makes no sense to me. Why should we stop it? I suggest to make it non configurable. We will change it only if there will be request for that feature with use case.

You are right. It is hard to find a case for this.

However, if later we support adding new jobs at run time, a finite retries could be useful to allow netdata retire from e.g. autoscaled apps that somehow did not manage to cleanup properly.

I think both settings could have a max and it is pretty simple to implement.

The defaults could be:

- for retries, `max` would be zero (retry forever)
- for back-off, `max` would be 10 minutes (ie do not delay checks more than 10 minutes)

Still, this is your call. For the moment, finite retries are not needed.
