### ISSUE TITLE
Can I monitor a F5BIG-IP Memory using SNMP?

### ISSUE THREAD

**Issue by sohwaje** [netdata/netdata#4760]
I have make snmp.conf for Switch Interface. It's awesome.
But I cannot make other device. For instance Memory, CPU.....
Can I monitor a MEM using SNMP?
I know MIB & OID. 
sysStatMemoryTotal 1.3.6.1.4.1.3375.2.1.1.2.1.44
sysStatMemoryUsed  1.3.6.1.4.1.3375.2.1.1.2.1.45

How does it make this?

**Comment by ilyam8** [comment]
Short answer - yes, you can monitor anything if you know OID. 

Check from the cli if your device returns something for these OIDs.

```
// syntax
snmpget -v 2c -c YOUR_COMMUNITY IP_ADDRESS OID
```

**Comment by sohwaje** [comment]
Yes. I did. 
[1]Result 
memory_total = SNMPv2-SMI::enterprises.3375.2.1.7.1.1.0 = Counter64: 33767403520
memory_used = SNMPv2-SMI::enterprises.3375.2.1.7.1.2.0 = Counter64: 6526475320

How do I next?

**Comment by cakrit** [comment]
Hi @sohwaje, please follow the instructions in [the documentation](https://docs.netdata.cloud/collectors/node.d.plugin/snmp/) and let us know if are still not able to do it, so we can improve it.

**Comment by sohwaje** [comment]
Yes I do. But I don't know.
"charts", "dimensions".... Where are they?

**Comment by cakrit** [comment]
[This page] also explains charts, dimensions, contexts and families. Closing this, but feel free to ask for more help.
