### ISSUE TITLE
"Out of disk inodes" alarm when restarting LXC containers

### ISSUE THREAD

**Issue by NicolasGoeddel** [netdata/netdata#4762]
##### Bug report summary
I installed netdata on a host which runs several LXD/LXC containers on a ZFS filesystem. Every night these containers are temporarily stopped, snapshotted and restarted. During this downtime (less than 10 seconds usually) for every container I get bombarded with alarms from  `/usr/lib/netdata/conf.d/health.d/disks.conf` with this error:

> out of disk inodes time = 4h
> estimated time the disk will run out of inodes, if the system continues to allocate inodes with the rate of the last hour

Edit: I forgot to mention that also the alarm for `out of disk space time` gets triggered this way:
> out of disk space time = 1h
> estimated time the disk will run out of space, if the system continues to add data with the rate of the last hour

##### OS / Environment
Ubuntu 16.04.5 LTS
Kernel 4.4.0-131-generic
Netdata 1.11.1-27-gcc5af80_rolling (cc5af80)
LXD/LXC 2.13

##### Component Name
/usr/lib/netdata/conf.d/health.d/disks.conf

##### Steps To Reproduce
Run a fresh netdata installation on a LXC host and stop and start a container:
```
lxc stop container1
sleep 10
lxc start container1
```
But it doesn't seem to happen on every try. It seems to be better reproducible with bigger containers.

btw: Another side effect is a very high peak of CPU usage when the container was stopped of 444.134.100.000 %, but this seems not to trigger an alarm.

##### Expected behavior
Don't show any alarms if containers are restarted normally.

**Comment by cakrit** [comment]
Actually, according to [the documentation](https://docs.netdata.cloud/collectors/cgroups.plugin/#monitoring-ephemeral-containers) this isn't supposed to happen.

**Comment by paulfantom** [comment]
This is probably more related to disk monitoring than containers. Seems like either LXC or ZFS is doing some intensive disk operations when stopping a container which in turn trigger an alarm.

**Comment by NicolasGoeddel** [comment]
Could it be related to snapshotting a ZFS volume instead of stopping/starting a container? I try to check that manually.
After the snapshot I am using `zfs send` and `zfs receive` on another host to make an incremental backup from the snaphot which was made between the `lxc stop` and `lxc start` commands. This way I can make efficient backups without a long downtime.

**Comment by paulfantom** [comment]
Seems like this might be the issue.

**Comment by cakrit** [comment]
We will provide a solution for these types of issues via #3600 (definition of recurring tasks/maintenance windows), with the option to disable alarms during those periods.
