### ISSUE TITLE
edit-config question?

### ISSUE THREAD

**Issue by tbblake** [netdata/netdata#4766]
On my home systems I configure netdata to only e-mail me critical alarms via:

/etc/netdata/edit-config health_alarm_notify.conf

Can I just copy the file, use sed on it to tweak the config, and bounce netdata? Or do I have to use edit-config?

**Comment by Ferroin** [comment]
Yes, you should be fine just copying the relevant config files and then editing them with `sed` (or any other editor of your choice.  The `edit-config` script is literally just a wrapper to handle copying the file from the correct location to the correct location and starting an editor.

**Comment by tbblake** [comment]
Great, I'm a big fan of scripting/automation.  Thank you!
