### ISSUE TITLE
Fail2ban: Read "Restore Ban" for persistent bans

### ISSUE THREAD

**Issue by winstonyin** [netdata/netdata#4769]
##### Feature idea summary
Current fail2ban module only increments counter when a new IP is banned (`NOTICE [sshd] Ban xx.xx.xx.xx` in log), but fails to increment when an old IP is re-banned (`NOTICE [sshd] Restore Ban xx.xx.xx.xx` in log). The "Restore Ban" event occurs when one sets the fail2ban jail time to -1 (banned forever), and the fail2ban service is restarted.

##### Expected behavior
Fail2ban module should be able to count the number of re-banned IPs when fail2ban is restarted. This means the module needs to read the sudden appearance of hundreds of new lines in the fail2ban log.

##### My own attempt
Before the fail2ban module was refactored recently, I had a simple fix (see [these instructions](https://www.winstonyin.com/en/2018/01/03/netdata-and-fail2ban-persistent-bans/)) involving changing the REGEX_DATA. However, with the same fix on the new fail2ban module, it is only able to increment the counter by 3 or 4, when there are dozens of "Restore Ban" log entries.

**Comment by ilyam8** [comment]
Hey @winstonyin 
I think your fix should work

1.  change
https://github.com/netdata/netdata/blob/caf7b045a5d5ab87f61411f45e3eeeb3ffd161bc/collectors/python.d.plugin/fail2ban/fail2ban.chart.py#L49

to 
```python
RE_DATA = re.compile(r'\[(?P<jail>[A-Za-z-_0-9]+)\] (?P<action>Unban|Ban|Restore Ban) (?P<ip>[a-f0-9.:]+)')
```

2. change 
https://github.com/netdata/netdata/blob/caf7b045a5d5ab87f61411f45e3eeeb3ffd161bc/collectors/python.d.plugin/fail2ban/fail2ban.chart.py#L119

to
```python
if action == 'Ban' or action == 'Restore Ban':
```

Have you tried it?

**Comment by winstonyin** [comment]
Yes that is precisely the modified fix I tried. The result is that even though dozens of IPs are re-banned in a short amount of time when fail2ban is restarted, netdata only picks up 3 or 4. This gives a totally incorrect count of total number of banned IPs in jail.

**Comment by ilyam8** [comment]
Module uses `LogService` framework service, it reads all new lines every iterations.

So it should count **all** restore ban ips.

So you say if i add , for example, 1000k `Restore Ban` ips to the `fail2ban.log` module fails to parse them?

I need a step by step guide how to reproduce the bug

**Comment by winstonyin** [comment]
When the fail2ban service is restarted, 100 Restore Ban entries appear in fail2ban.log, but netdata chart corresponding to the fail2ban jail only goes up to, say, 3.

**Comment by ilyam8** [comment]
@winstonyin fixed it

**Comment by ilyam8** [comment]
@winstonyin 

thx for reporting it :+1:
