### ISSUE TITLE
Backup data automatically on some signal event

### ISSUE THREAD

**Issue by DavidS3141** [netdata/netdata#4775]
##### Current setup
Before going into the feature request short overview over my setup:

Like discribed on this [documentation (Netdata, Prometheus, Grafana stack)](https://docs.netdata.cloud/backends/walkthrough/) of yours, I am setting up this stack for a cluster covering a few machines (ca. 30). The current approach is, to install `netdata` on each worker node and have two prometheus instances, one scraping often (every 15s or so for a history of 1-3 months) and one saving trend data (scraping every 30min or so for a history of 1-2 years). (Does this actually make sense or is there maybe even some better mechanism?)

##### Feature idea summary
Netdata itself is actually providing a resolution of 1s. I have not tried it out, but it is probably not very stable to let Prometheus scrape every second 30 endpoints. Still when something unordinary happens it would be nice to have the 1-s-resolution of netdata. We do not respond to alerts in a matter of minutes, so when we actually have time to look into monitoring alerts, a few hours may have passed, meaning the netdata high resolution data is lost for that event.
The requested feature would be, that netdata could receive some kind of signal (http request) to let it back up the last hour of data for later inspection. This signal could be automatically generated through an alertmanager. Additionally, a tool for inspecting backup data in the web-interface would be nice. This way, we could look at the high resolution data and delete it after resolving the potential issues with our cluster.

**Comment by paulfantom** [comment]
> Does this actually make sense or is there maybe even some better mechanism?

Use only one prometheus with frequent scrape (ex. ~5s) and forward data to sth like InfluxDB (via prometheus remote_write) to save historical data. It is discouraged to store long-term (more than 90 days) of data in prometheus instances.

**Comment by paulfantom** [comment]
> I was not able to find anything concrete in the docs of prometheus that suggests this?

Prometheus wasn't designed to store long-term data. You can do it, but it is not a design goal. You can find prometheus instances running in production which have a retention period of 24h as short retention periods put less stress on disk and CPU when storing and retrieving data.

> Also, what do you think about the feature request?

I think that 1s resolution for distributed systems will be achieved with our netdata hub (work in progress).
Also I have never saw this type of a solution, the most popular one is to gather data with a resolution you need in all cases and just decrease resolution in database store (like graphite does it). This way you don't put stress on all nodes by retrieving large portion of data when needed and also don't store too much data which won't be relevant for trending.

**Comment by ktsaou** [comment]
netdata will solve this problem in a number of ways:

1. We develop a new database format that will decouple memory footprint from database size. Our goal is to have at least 24h of high resolution metrics, with minimal / ignorable disk activity on the host itself. On netdata masters, the new format would allow them to scale a lot better compared to what we have today. So on masters the new database format would allow even months of high resolution metrics, provided there is enough disk space (memory will be irrelevant).

2. Once the above is realized, we plan to further improve the database with re-sampling data to maintain older data for longer durations (something like 7 days with 15s, 1 month with 1min, 12 months with 15min).

3. We are also discussing the idea of saving snapshots when alarms trigger. So, every time an alarm is raised in netdata, a small snapshot (a few minutes) of the metrics will be generated, possibly uploaded to the netdata hub we are developing, to avoid additional pressure on the system.

For the moment, point No 1 above is at design phase. It is one of our key goals for the next months.

**Comment by cakrit** [comment]
@DavidS3141 I believe that #3973 will address your need exactly, without waiting for the new DB format. I am closing this one as duplicate and please provide your feedback in #3973, if there's something additional or different you'd like to see. We intend to work on it very soon.
