### ISSUE TITLE
Jumpy data when running on kubernetes

### ISSUE THREAD

**Issue by th0th** [netdata/netdata#4778]
##### Question summary
Charts are jumpy, not persistent. I really don't know how to explain this :) Please see this: [Here is a gif screencast.](https://user-images.githubusercontent.com/698079/49208335-92668080-f3c8-11e8-8467-6be097f20780.gif)

##### OS / Environment
Ubuntu 16.04 / Kubernetes v1.11.2 / Docker 17.3.2

**Comment by cakrit** [comment]
Perhaps you just need to click this button?
![image](https://user-images.githubusercontent.com/43294513/49208883-50820e00-f3b9-11e8-8069-f4458828587b.png)

**Comment by th0th** [comment]
@cakrit thanks for the reply. I tried and it didn't change anything :/

The chart feels like its getting data from multiple sources and switching between those, really strange. Do you want me to record a bit longer screencast? Would it help?

**Comment by cakrit** [comment]
Yes, please do. About 30sec to 1 min if you can.

**Comment by th0th** [comment]
Oh, [here is the link to running netdata instance](http://116.203.23.177:30000), you can see it yourself.

**Comment by cakrit** [comment]
Very strange. @ktsaou please check.

**Comment by ktsaou** [comment]
i think you have installed multiple netdata servers and the k8s is balancing requests among them. So, a few charts refreshes are coming from netdata A, and others are coming from netdata B.

**Comment by th0th** [comment]
> i think you have installed multiple netdata servers and the k8s is balancing requests among them. So, a few charts refreshes are coming from netdata A, and others are coming from netdata B.

Wow, nice catch! Thanks a lot!
