### ISSUE TITLE
richer dashboard fragments

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4780]
Netdata support "overview" sections, like these:

## Main system overview

![image](https://user-images.githubusercontent.com/2662304/49209531-65fc3580-f3c3-11e8-8029-48338ee5bcf3.png)

## web_log overview

![image](https://user-images.githubusercontent.com/2662304/49209552-77454200-f3c3-11e8-9374-702d9e015b1e.png)

## container overview

![image](https://user-images.githubusercontent.com/2662304/49209595-93e17a00-f3c3-11e8-919e-7c2aae4c8300.png)

## VM overview

![image](https://user-images.githubusercontent.com/2662304/49209645-b96e8380-f3c3-11e8-8042-780ca8555dd3.png)

---

We could support richer dashboard fragments, like these:

![image](https://user-images.githubusercontent.com/2662304/49209840-46194180-f3c4-11e8-8b32-e4a74d64578d.png)

![image](https://user-images.githubusercontent.com/2662304/49210106-df485800-f3c4-11e8-9fa8-638fea3ecaff.png)

The idea is to support new chart types and create dashboard templates to render them at the overview sections of the various monitored apps:

- [ ] define new chart types
- [ ] support templated dashboard fragments (a `yaml` of `json` definition of charts positions, types, etc)
- [ ] allow embedding dashboard fragments to 3rd party web pages, with just one `div`.

**Comment by gmosx** [comment]
This overlaps with the work I am doing on 'console'. We could reuse some of the code for the Netdata Agent WebUI.

Regarding additional chart types, it's in my roadmap 😀

**Comment by PanosJee** [comment]
Shouldn't we start looking into breaking visualizations in standalone web components and move all server communication to a separate "engine"?

**Comment by gmosx** [comment]
I am working on this separate 'engine' in a project tentatively called 'console'. We will have more to announce soon.

**Comment by cakrit** [comment]
@jacekkolasa just keep this for the "adding new charts" part, or close it. Custom dashboards are coming with netdata.cloud, we won't follow it here.
