### ISSUE TITLE
Can't enable synproxy performance plugin

### ISSUE THREAD

**Issue by SlavikCA** [netdata/netdata#4782]
##### Question summary
Can't enable synproxy performance plugin
I enabled it in the config, but can't see in the dashboard.

##### OS / Environment
Ubuntu 18.04
netdata 1.11.1 installed via bash command, not via apt

##### Component Name
synproxy performance
Also described as /proc/net/stat/synproxy

##### Expected results
I expect to see synproxy graph in the dashboard.

##### Config file:
```
slavik@ub18$ sudo cat /etc/netdata/netdata.conf
[global]
        run as user = netdata
        web files owner = root
        web files group = root
        bind socket to IP = *
        hostname = ub18-azure

[plugins]
         proc = yes

[plugin:proc]
         netdata server resources = yes
         /proc/stat = yes
         /proc/uptime = yes
         /proc/loadavg = yes
         /proc/sys/kernel/random/entropy_avail = yes
        # /proc/interrupts = yes
        # /proc/softirqs = yes
        # /proc/vmstat = yes
         /proc/meminfo = yes
         /sys/kernel/mm/ksm = yes
         /sys/devices/system/edac/mc = yes
         /sys/devices/system/node = yes
         /proc/net/dev = yes
         /proc/net/sockstat = yes
         /proc/net/sockstat6 = yes
         /proc/net/netstat = yes
        # /proc/net/snmp = yes
        # /proc/net/snmp6 = yes
        # /proc/net/sctp/snmp = yes
         /proc/net/softnet_stat = yes
         /proc/net/ip_vs/stats = yes
         /proc/net/stat/conntrack = yes
         /proc/net/stat/synproxy = yes
        # /proc/diskstats = yes
        # /proc/net/rpc/nfsd = yes
        # /proc/net/rpc/nfs = yes
        # /proc/spl/kstat/zfs/arcstats = yes
        # /sys/fs/btrfs = yes
        # ipc = yes

```

**Comment by SlavikCA** [comment]
I found this line in the log:
`
2018-11-29 10:17:12: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/net/stat/synproxy' (errno 2, No such file or directory)
`

Does that mean, that /proc/net/stat/synproxy is not supported on Ubuntu?

**Comment by ktsaou** [comment]
> Does that mean, that /proc/net/stat/synproxy is not supported on Ubuntu?

I think you have to use `-j SYNPROXY` in iptables commands for that file to be enabled. Have you configured iptables synproxy?

**Comment by SlavikCA** [comment]
When I read the docs, I was thinking, that I just need to enable it in the config like this:
```
[plugin:proc]
/proc/net/stat/synproxy = yes
```

Now, it looks like I needed to pay attention to this:

> To use SYNPROXY on your firewall, please follow our setup guides:
> 
> Working with SYNPROXY https://github.com/firehol/firehol/wiki/Working-with-SYNPROXY
> Working with SYNPROXY and traps https://github.com/firehol/firehol/wiki/Working-with-SYNPROXY-and-traps

When I tried to read these guides - it seems to be overly complicated for me. 

Do I understand it correctly, that in order to see SYNPROXY metrics I need to install FireHOL?

Or is it just `iptables` command that I need to run? I tried to Google on how to run `iptables` to enable SYNPROXY, but couldn't figure that out.

**Comment by ktsaou** [comment]
Well, netdata is a monitoring tool. It monitors what you use. So, netdata will not enable SYNPROXY for you - it will just use the SYNPROXY metrics exposed by your kernel.

FireHOL (another project I founded), is a firewall manager for iptables. This can configure SYNPROXY (using the guides you stated - though you have to learn that tool and understand how it works).

So, Netdata will monitor SYNPROXY once you configure it, independently of the method you used. Netdata will pick the metrics and visualize them, even if you just run `iptables` `SYNPROXY` commands directly on the console.
