### ISSUE TITLE
RFC Generation of agent_id

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#4783]
# Generation of agent_id

We would like to offer a mechanism for a user to prove the ownership of a Netdata Agent. For example, in the upcoming 'Hub' service, the user should be able to 'claim' the ownership of his Netdata Agents.

We propose to replace the current `machine_guid` identifier with a new cryptographically derived identifier, called `agent_id`.

In the following, we entertain two different implemetation strategies.

## Generation of `agent_id` using `UUID.v4()` and `SHA256`

The `agent_id` is computed using the following algorithm:

1. Generate a `secret_key` by computing a v4 UUID (random 128bit number).

1. Generate a `public_key` by hashing the `secret_key` using SHA256, two times.

1. Generate the `agent_id` by taking the lower 128bits of the `public_key`.

In pseudo code:

```
secret_key = UUID.v4()
public_key = SHA256(SHA256(secret_key))
agent_id = Lower128Bits(public_key)
```

The user should pass the `secret_key` to verify ownership of the agent identified by `agent_id`.

### Example usage

A user wants to claim the ownership of his Netadata Agent. He uses the following REST API call:

```
POST https://registry.com/api/v1/claim

{
    "secret_key": {{secret_key}},
    "agent_id": {{agent_id}}
}
```

The server computes the `public_key` that corresponds to the passed `secret_key` and verifies that it matches the `agent_id`.

## Generation of `agent_id` using `ECDSA`

The `agent_id` can be computed using the following algorithm:

1. Generate an [ECDSA](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm) `(secret_key, public_key)` pair ([example](https://golang.org/pkg/crypto/ecdsa/#example_))

1. Generate the `agent_id` by taking the lower 128bits of the `public_key`.

In pseudo code:

```
(secret_key, public_key) = GenerateECDSAKeyPair()
agent_id = Lower128Bits(public_key)
```

The user signs a message using the `secret_key` and the recipient verifies the integrity of the message using the `public_key` provided by the user. The recipient can derive the `agent_id` from the lower 128bits of the public key.

### Example usage

A user wants to claim the ownership of his Netadata Agent. He can use the following REST API call:

```
digest = agent_id
r, s = secret_key.Sign(digest)

POST https://registry.com/api/v1/claim

{
    "r": {{r}},
    "s": {{s}},
    "public_key": {{public_key}}
}
```

The server verifies the integrity of the (r, s) signature, using the passed `public_key`. On success, the server derives the `agent_id` from the lower 128bits of the public key.

## Discussion

The first strategy is easier to implement, with minimal dependencies. IMO it looks good-enough for simple use-cases (including the 'claim' use-case). On the negative side, it exposes the `secret_key` which is ...controversial.

The second strategy is more common and versatile. The user is not disclosing his `secret_key`.

**DISCLAIMER**: The example use cases are just _examples_ and not the proposed API/procedure for claiming agents in Hub.

**Comment by Ferroin** [comment]
Personally, I'm more in favor of the ECDSA approach.  It's both more robust, and more secure.

A slightly better workflow than what's proposed might be something like this:

1. The user asks Netdata for the public key, then adds that key to their account on the hub.
2. The user then tells Netdata what their account ID is and tells it to associate with that account.
3. Netdata calls out to the Hub API asking to associate with the given account.  The Hub responds back with a message that must be signed by a private key whose public key has been associated with the requested account.  The message itself _must_ include a timestamp, and _should_ include a nonce of some sort, as well as the account ID.
4. Netdata signs the message, and sends back the signature and message, as well as the ID of the public key that can be used to verify the message.
5. The Hub verifies that the signature is valid and that the message matches.  If they both pass, it associates that Netdata instance with the given account ID.

The requirement for the user to add the public key to their account before they can claim the instance makes it significantly more resistant to spoofing attempts.  The requirement that the message has a timestamp and a nonce makes it resistant to replay attacks.

Regardless of what's done, I would very much suggest asking the people at the [infosec](https://security.stackexchange.com/) or [crypto](https://crypto.stackexchange.com/) Stack Exchange sites to take a look at the design and see if they can find any holes.

**Comment by gmosx** [comment]
> The requirement for the user to add the public key to their account before they can claim the instance makes it significantly more resistant to spoofing attempts.

Can you elaborate on this?

Regarding the nonce/replay-attacks you are right, I will revise the proposal, thanks.

**Comment by gmosx** [comment]
Also, please note that this issue describes the generation of `agent_id` only, and _not_ the procedure of claiming the agent on the Hub. A more detailed issue for this will come later. The example use-cases are just that, an example.

**Comment by Ferroin** [comment]
>> The requirement for the user to add the public key to their account before they can claim the instance makes it significantly more resistant to spoofing attempts.
> 
> Can you elaborate on this?

Spoofing was probably not the best choice of term for what I'm worried about.  My concern here is that without requiring the user to prove they have access to the public key before they can claim a given server, users could accidentally (or intentionally) associate their Netdata instances to a different user's account.  By itself, this would be just a nuisance, but I could see it being a potential building-block for a social engineering attack.

> Also, please note that this issue describes the generation of agent_id only, and not the procedure of claiming the agent on the Hub. A more detailed issue for this will come later. The example use-cases are just that, an example.

Regarding that specifically, I think public-key cryptography is the way to go here.  The UUID proposal puts a hard upper limit on Netdata instances claimed on the hub (2^128 is a lot, but it's still a hard limit, and it's not unreasonable to expect that there will be significantly more computers than humans within the next decade or so), and has a non-negligible risk of collisions because of the use of random UUID's (instead of host-based ones for example).  The hashing proposed in that method really doesn't gain us anything either (hashing 128 bits to 256 doesn't make it any harder to guess those 128 bits, even if you then hash the result again, because there's still only 2^128 valid values, and producing a rainbow table of the valid hashes ends up being trivial).

**Comment by gmosx** [comment]
> users could accidentally (or intentionally) associate their Netdata instances to a different user's account.

As I said, this issue is not concerned with the claim process. The examples where just examples. But since you mentioned it, the users need to be signed-in to associate a Netdata Agent, so your concern is irrelevant. Please wait for the proper design issue for claiming (I am prototyping this at the moment).

**Comment by gmosx** [comment]
> Regarding that specifically, ...  valid hashes ends up being trivial).

Again I don't understand, this issue just proposes to replace one 128bit number (`machine_guid`) that we already use, with another 128bit number (`agent_id`), which allows for verification of his owner using a simple scheme. That's all.

Btw, 2^128 is not 'a lot', it's humongous: "This number is equivalent to generating 1 billion UUIDs per second for about 85 years, and a file containing this many UUIDs, at 16 bytes per UUID, would be about 45 exabytes, many times larger than the largest databases currently in existence, which are on the order of hundreds of petabytes.[16][17]"

**Comment by gmosx** [comment]
Btw, we could use more bits for the `agent_id`. For example use 160bits or even 256bits. No need to keep it to 128bits. Would that alleviate your concerns?

**Comment by Ferroin** [comment]
> Btw, we could use more bits for the agent_id. For example use 160bits or even 256bits. No need to keep it to 128bits. Would that alleviate your concerns?

The concerns about uniqueness yes.  The whole first example still scares me a bit though.  Is there some technical reason that we _can't_ use public key cryptography here, or at least some kind of existing well tested and audited authentication mechanism (because this _is_ authentication)?

**Comment by gmosx** [comment]
I also agree we should go with something similar to the 2nd strategy. I will prepare an updated RFC.

**Comment by ktsaou** [comment]
Please keep in mind there are 2 use cases:

1. User installs by hand, one or more netdata and then claims them.
2. User installs netdata via a continuous delivery platform and needs them to be pre-claimed (i.e. all information about assigning these netdata to hub accounts and possibly groups of that hub account is pre-determined).

Both use cases should be supported for both installing netdata at the host, and installing netdata via a container.
