### ISSUE TITLE
How to do custom monitoring in Netdata??

### ISSUE THREAD

**Issue by deep7710** [netdata/netdata#4784]

**Comment by cakrit** [comment]
You can try writing a [python plugin](https://docs.netdata.cloud/collectors/python.d.plugin/) or a [node.js plugin](https://docs.netdata.cloud/collectors/node.d.plugin/)

Does this answer your question?

**Comment by deep7710** [comment]
@cakrit  could you please share some examples for python plugin. I am actually relatively new to netdata.
I am using netdata as agent for prometheus. I have around 100 servers and  want to do custom monitoring on these nodes. any leads would be very helpul!!

**Comment by cakrit** [comment]
Sure, for a quick start, you can look at the [example plugin](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/example/example.chart.py). I did a PR to add the instruction to the python.d readme.

**Comment by ilyam8** [comment]
@deep7710 https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-write-a-new-module

**Comment by ilyam8** [comment]
i think we have answered OP question. 

@deep7710 if you still have questions feel free to ask.
