### ISSUE TITLE
Cookie consent for the Netdata sites

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#4798]
##### Feature idea summary
For GDPR compliance and since we use GA, we need to have a cookie consent mechanism. 
We should be able to use the same mechanism in all our sites (documentation, web site, hub etc).

**Comment by gmosx** [comment]
I added this script in the new site: https://cookieconsent.insites.com/

Works great.

**Comment by cakrit** [comment]
To be perfectly clear on this, this only has to do with the use of the GA tracking (https://www.blastam.com/blog/5-actionable-steps-gdpr-compliance-google-analytics). 
I will add the script to the docs myself.

**Comment by cakrit** [comment]
This was done a while ago, we forgot to close it.
