### ISSUE TITLE
netdata version info

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#4806]
##### Bug report summary
I installed netdata 1.11.1 from static binary.
I downloaded from git release page: <https://github.com/netdata/netdata/releases/download/v1.11.1/netdata-v1.11.1.tar.gz>
Expect version: 1.11.1
Actual version: 1.11.1_rolling

##### OS / Environment
CentOS 7

##### Component Name
API/web

##### Steps To Reproduce
install it and check the Web UI

##### Expected behavior
Expect version: 1.11.1

**Comment by paulfantom** [comment]
This should be already fixed on master branch and will propagate in next release.
PR with this fix was implemented in https://github.com/netdata/netdata/pull/4748
