### ISSUE TITLE
libstatgrab backend for netdata

### ISSUE THREAD

**Issue by bsdlme** [netdata/netdata#481]
There's a common library to collect a host's data on FreeBSD, Linux, NetBSD, OpenBSD, Solaris, DragonFly BSD, HP-UX and AIX: https://www.i-scream.org/libstatgrab/
If netdata used this as a backend then suddenly it would be super-portable.
What do you think of it?

**Comment by ktsaou** [comment]
This is nice! Thanks for the info!

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
