### ISSUE TITLE
Couchbase monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4811]
We are willing to support monitoring ***[Couchbase](https://www.couchbase.com/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by cakrit** [comment]
There's some interest here, but no sponsor. Can someone help us move it forward?

**Comment by ilyam8** [comment]
`Couchbase` monitoring documentation:

> https://blog.couchbase.com/monitoring-couchbase-cluster/

I see there are suggested 2 endpoints:

- `/pools/default`                 # Node Monitoring
- `/pools/default/buckets/stats`   # Bucket Monitoring

**Comment by Kobaruon** [comment]
Hi everyone,

I can be a sponsor for this collector. We use Couchbase and have over thousands of nodes on development, stage and production. We are mainly using Prometheus + Grafana. Right now, Netdata with its Prometheus integration collects a great amount of metrics, but they are not organized in any way and pretty much in raw status.

Native Couchbase integration would be really great for Netdata. Just like @ilyam8 said in the above post, those are the main endpoints of Couchbase. I can provide some more details about the key metrics too. I don't really know how exactly sponsoring works in reality, but feel free to ask me anything about what you need.

**Comment by ilyam8** [comment]
@Kobaruon 👋 That is very nice you are willing to help!

>  but they are not organized in any way and pretty much in raw status.

True.

---

- `lab env`: a guide how to setup couchbase test lab (single instance and HA setup if it is supported) - i guess using docker.
- do we need to add some data/simulate some load to get all the metrics?
- `metrics samples`: according their [monitoring documentation](https://blog.couchbase.com/monitoring-couchbase-cluster/) there is 2 endpoints we need to collect data from. Share your couchbase instance metrics.
- `charts`: we need to organize those metrics into charts, some metrics are not that important and can be ignored - lets think how about charts when we have metrics samples.
- `alarms`: if there are some metrics we can use to track problems we need alarms. If you can suggest something it would be really cool!

**Comment by Kobaruon** [comment]
I tried to answer your questions. I hope it's clear.

* `lab env`: 

[This documentation](https://docs.couchbase.com/server/current/install/getting-started-docker.html#section_msh_fbl_42b) should help you get started with multiple nodes on a cluster. Couchbase with its multi node setup is actually an HA solution. They have also XDCR setup which is DR scenario. We can get into that if you want. But I don't think there are docker guides for that.

* do we need to add some data/simulate some load to get all the metrics?:

After installation, you should add [sample buckets.](https://docs.couchbase.com/server/6.6/manage/manage-settings/install-sample-buckets.html#install-sample-buckets-with-the-ui) And then, you can create load test using cbc-pillowfight command which should be under /opt/couchbase/bin

Sample command: `cbc-pillowfight -U couchbase://<ip address here>/<sample bucket name> -u <username> -p <password> --num-items=100000 --set-pct=50 --min-size=2000 --max-size=2000 --timings --num-cycles=1000000`

This command should create a workload of 50% read/write.

* `metrics samples`: 

[These](https://docs.couchbase.com/server/6.6/manage/monitor/monitoring-rest.html) are critical metrics. But most of them are hidden behind bucket stats. I don't know how you can access those automatically. Because, they change from cluster to cluster and not static.

`/pools/default/buckets/<custom bucket name>/stats` you can get them here.
**ops** - operations per second
**ep_cache_miss_rate** - Couchbase should work in memory for most of the time, but it depends on your sizing, business related decisions etc. High cache miss rate might indicate problems.
**couch_docs_fragmentation** - Fragmentation of buckets. Couchbase automatically handle fragmentation but when a huge workload comes out of nowhere it can be a problem and this metric can help identify that workload or what is happening during a slowdown.
**ep_diskqueue_items** - Couchbase should write data from memory to disk and this metric shows items in queue for disk operations.
**ep_tmp_oom_errors** - When this metric increase or show any activity it indicates sizing problems.
**vb_active_resident_items_ratio** - Documents that are in memory. Higher the better.

Following DCP metrics indicate intra cluster communication between nodes.
**ep_dcp_replica_items_sent** - Documents that has been sent to other nodes.
**ep_dcp_replica_items_remaining** - Documents that are waiting to be synced.
**ep_dcp_replica_total_bytes** - Total traffic between nodes.

These are disaster recovery metrics.
**ep_dcp_xdcr_items_remaining** - Documents that are waiting to be sent to DR site.
**ep_dcp_xdcr_total_bytes** - Total traffic to the DR site.

* `charts`: 
I think metrics that I explained must be present in charts. Couchbase provides a lot of metrics, when you install your instance on docker, you will see the stats that it provides. I think most of the stats in summary should be in charts. When you hover over them, you can also see REST API points too.
<img width="878" alt="image" src="https://user-images.githubusercontent.com/4200866/93569117-ccd44f80-f999-11ea-9194-3a83b9312f66.png">
<img width="486" alt="image" src="https://user-images.githubusercontent.com/4200866/93569260-f5f4e000-f999-11ea-936e-a8b74f1f94c0.png">

Also, most of the clusters have multiple buckets in them and since most of the data comes from bucket stats. If it's possible, they should be grouped. For instance, in this graph we have two buckets and we group them into a single chart to track their ops metric.
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/4200866/93569496-48ce9780-f99a-11ea-8212-82bcf4cef90b.png">

* `alarms`: 
These metrics can be used for alarms.
**ep_cache_miss_rate** - Never over 10% but it depends on scenario.
**couch_docs_fragmentation** - Should never exceed 30%
**ep_tmp_oom_errors** - Should never occur indicated serious sizing problem.

Other metrics mostly depends on database usage, business requirements etc.

**Comment by ilyam8** [comment]
@Kobaruon 

i followed the [install-single-node-cluster docs](https://docs.couchbase.com/server/current/install/getting-started-docker.html#section_jvt_zvj_42b) and everything went smooth 🎉 

i added 3 sample buckets

<img width="1289" alt="Screenshot 2020-10-05 at 12 39 26" src="https://user-images.githubusercontent.com/22274335/95064038-d1be3080-0707-11eb-97ca-54f5a885b4f7.png">

---

## /pools/default

```json
{
    "name": "default",
    "nodes": [
        {
            "systemStats": {
                "cpu_utilization_rate": 9.491525423728813,
                "cpu_stolen_rate": 0,
                "swap_total": 0,
                "swap_used": 0,
                "mem_total": 33587417088,
                "mem_free": 30543527936,
                "mem_limit": 33587417088,
                "cpu_cores_available": 6,
                "allocstall": 0
            },
            "interestingStats": {
                "cmd_get": 0,
                "couch_docs_actual_disk_size": 83717178,
                "couch_docs_data_size": 72689819,
                "couch_spatial_data_size": 0,
                "couch_spatial_disk_size": 0,
                "couch_views_actual_disk_size": 795981,
                "couch_views_data_size": 787677,
                "curr_items": 39480,
                "curr_items_tot": 39480,
                "ep_bg_fetched": 0,
                "get_hits": 0,
                "mem_used": 118212888,
                "ops": 0,
                "vb_active_num_non_resident": 0,
                "vb_replica_curr_items": 0
            },
            "uptime": "222",
            "memoryTotal": 33587417088,
            "memoryFree": 30543527936,
            "mcdMemoryReserved": 25625,
            "mcdMemoryAllocated": 25625,
            "couchApiBase": "http://172.17.0.2:8092/",
            "couchApiBaseHTTPS": "https://172.17.0.2:18092/",
            "clusterMembership": "active",
            "recoveryType": "none",
            "status": "healthy",
            "otpNode": "ns_1@cb.local",
            "thisNode": true,
            "hostname": "172.17.0.2:8091",
            "nodeUUID": "8f5ee5385fc4d1c677c9376dac80918c",
            "clusterCompatibility": 393222,
            "version": "6.6.0-7909-enterprise",
            "os": "x86_64-unknown-linux-gnu",
            "cpuCount": 6,
            "ports": {
                "direct": 11210,
                "httpsCAPI": 18092,
                "httpsMgmt": 18091,
                "distTCP": 21100,
                "distTLS": 21150
            },
            "services": [
                "cbas",
                "eventing",
                "fts",
                "index",
                "kv",
                "n1ql"
            ],
            "nodeEncryption": false,
            "configuredHostname": "127.0.0.1:8091",
            "addressFamily": "inet",
            "externalListeners": [
                {
                    "afamily": "inet",
                    "nodeEncryption": false
                },
                {
                    "afamily": "inet6",
                    "nodeEncryption": false
                }
            ]
        }
    ],
    "buckets": {
        "uri": "/pools/default/buckets?v=105945875&uuid=aceed2ca647bd6b8c06efa008ef4ee3a",
        "terseBucketsBase": "/pools/default/b/",
        "terseStreamingBucketsBase": "/pools/default/bs/"
    },
    "remoteClusters": {
        "uri": "/pools/default/remoteClusters?uuid=aceed2ca647bd6b8c06efa008ef4ee3a",
        "validateURI": "/pools/default/remoteClusters?just_validate=1"
    },
    "alerts": [],
    "alertsSilenceURL": "/controller/resetAlerts?uuid=aceed2ca647bd6b8c06efa008ef4ee3a&token=0",
    "controllers": {
        "addNode": {
            "uri": "/controller/addNodeV2?uuid=aceed2ca647bd6b8c06efa008ef4ee3a"
        },
        "rebalance": {
            "uri": "/controller/rebalance?uuid=aceed2ca647bd6b8c06efa008ef4ee3a"
        },
        "failOver": {
            "uri": "/controller/failOver?uuid=aceed2ca647bd6b8c06efa008ef4ee3a"
        },
        "startGracefulFailover": {
            "uri": "/controller/startGracefulFailover?uuid=aceed2ca647bd6b8c06efa008ef4ee3a"
        },
        "reAddNode": {
            "uri": "/controller/reAddNode?uuid=aceed2ca647bd6b8c06efa008ef4ee3a"
        },
        "reFailOver": {
            "uri": "/controller/reFailOver?uuid=aceed2ca647bd6b8c06efa008ef4ee3a"
        },
        "ejectNode": {
            "uri": "/controller/ejectNode?uuid=aceed2ca647bd6b8c06efa008ef4ee3a"
        },
        "setRecoveryType": {
            "uri": "/controller/setRecoveryType?uuid=aceed2ca647bd6b8c06efa008ef4ee3a"
        },
        "setAutoCompaction": {
            "uri": "/controller/setAutoCompaction?uuid=aceed2ca647bd6b8c06efa008ef4ee3a",
            "validateURI": "/controller/setAutoCompaction?just_validate=1"
        },
        "clusterLogsCollection": {
            "startURI": "/controller/startLogsCollection?uuid=aceed2ca647bd6b8c06efa008ef4ee3a",
            "cancelURI": "/controller/cancelLogsCollection?uuid=aceed2ca647bd6b8c06efa008ef4ee3a"
        },
        "replication": {
            "createURI": "/controller/createReplication?uuid=aceed2ca647bd6b8c06efa008ef4ee3a",
            "validateURI": "/controller/createReplication?just_validate=1"
        }
    },
    "rebalanceStatus": "none",
    "rebalanceProgressUri": "/pools/default/rebalanceProgress",
    "stopRebalanceUri": "/controller/stopRebalance?uuid=aceed2ca647bd6b8c06efa008ef4ee3a",
    "nodeStatusesUri": "/nodeStatuses",
    "maxBucketCount": 30,
    "autoCompactionSettings": {
        "parallelDBAndViewCompaction": false,
        "databaseFragmentationThreshold": {
            "percentage": 30,
            "size": "undefined"
        },
        "viewFragmentationThreshold": {
            "percentage": 30,
            "size": "undefined"
        },
        "indexCompactionMode": "circular",
        "indexCircularCompaction": {
            "daysOfWeek": "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
            "interval": {
                "fromHour": 0,
                "toHour": 0,
                "fromMinute": 0,
                "toMinute": 0,
                "abortOutside": false
            }
        },
        "indexFragmentationThreshold": {
            "percentage": 30
        }
    },
    "tasks": {
        "uri": "/pools/default/tasks?v=55351230"
    },
    "counters": {},
    "indexStatusURI": "/indexStatus?v=116289313",
    "checkPermissionsURI": "/pools/default/checkPermissions?v=NqH8Zct0tHK%2FZ8ubuJIPKm%2BNysg%3D",
    "serverGroupsUri": "/pools/default/serverGroups?v=33997461",
    "clusterName": "ExampleCluster",
    "balanced": true,
    "memoryQuota": 18245,
    "indexMemoryQuota": 6013,
    "ftsMemoryQuota": 512,
    "cbasMemoryQuota": 3422,
    "eventingMemoryQuota": 972,
    "storageTotals": {
        "ram": {
            "total": 33587417088,
            "quotaTotal": 19131269120,
            "quotaUsed": 314572800,
            "used": 5994479616,
            "usedByData": 118212888,
            "quotaUsedPerNode": 314572800,
            "quotaTotalPerNode": 19131269120
        },
        "hdd": {
            "total": 502681239552,
            "quotaTotal": 502681239552,
            "used": 125670309888,
            "usedByData": 84513159,
            "free": 377010929664
        }
    }
}
```


## /pools/default/buckets/stats

Returns `Requested resource not found.`

Does it work for you?

## /pools/default/buckets/

I tried (same but w/o `stats`)

> /pools/default/buckets

and i get the data, a very big json (65536 characters+).

**Comment by ilyam8** [comment]
I see there is  unofficial couchbase client library: https://github.com/couchbase/go-couchbase

```go
package main

import (
	"fmt"
	"log"

	"github.com/couchbase/go-couchbase"
)

func main() {
	const (
		baseURL  = "http://192.168.88.250:8091"
		username = "Administrator"
		password = "123456"
	)
	client, err := couchbase.ConnectWithAuthCreds(baseURL, username, password)
	if err != nil {
		log.Fatal(err)
	}

	p, err := client.GetPool("default")
	if err != nil {
		log.Fatal(err)
	}

	for _, n := range p.Nodes {
		fmt.Printf("Node: %#v\n\n", n)
	}

	for _, b := range p.BucketMap {
		fmt.Printf("Bucket '%s', %#v\n\n", b.Name, b.BasicStats)
	}
}
```

I get these metrics

```cmd
Node: couchbase.Node{ClusterCompatibility:393222, ClusterMembership:"active", CouchAPIBase:"http://172.17.0.2:8092/", Hostname:"172.17.0.2:8091", AlternateNames:map[string]couchbase.NodeAlternateNames(nil), InterestingStats:map[string]float64{"cmd_get":0, "couch_docs_actual_disk_size":1.04488621e+08, "couch_docs_data_size":7.4025115e+07, "couch_spatial_data_size":0, "couch_spatial_disk_size":0, "couch_views_actual_disk_size":1.009052e+06, "couch_views_data_size":1.000748e+06, "curr_items":39480, "curr_items_tot":39480, "ep_bg_fetched":0, "get_hits":0, "mem_used":1.1820236e+08, "ops":0, "vb_active_num_non_resident":0, "vb_replica_curr_items":0}, MCDMemoryAllocated:25625, MCDMemoryReserved:25625, MemoryFree:2.7205931008e+10, MemoryTotal:3.3587417088e+10, OS:"x86_64-unknown-linux-gnu", Ports:map[string]int{"direct":11210, "distTCP":21100, "distTLS":21150, "httpsCAPI":18092, "httpsMgmt":18091}, Services:[]string{"cbas", "eventing", "fts", "index", "kv", "n1ql"}, Status:"healthy", Uptime:998, Version:"6.6.0-7909-enterprise", ThisNode:true}

Bucket 'beer-sample', map[string]interface {}{"dataUsed":1.4064171e+07, "diskFetches":0, "diskUsed":2.7764908e+07, "itemCount":7303, "memUsed":3.4284856e+07, "opsPerSec":0, "quotaPercentUsed":32.69658660888672, "vbActiveNumNonResident":0}

Bucket 'gamesim-sample', map[string]interface {}{"dataUsed":5.302172e+06, "diskFetches":0, "diskUsed":1.3752161e+07, "itemCount":586, "memUsed":2.9590088e+07, "opsPerSec":0, "quotaPercentUsed":28.21930694580078, "vbActiveNumNonResident":0}

Bucket 'travel-sample', map[string]interface {}{"dataUsed":5.565952e+07, "diskFetches":0, "diskUsed":6.3980604e+07, "itemCount":31591, "memUsed":5.4327416e+07, "opsPerSec":0, "quotaPercentUsed":51.81066131591797, "vbActiveNumNonResident":0}
```

**Comment by Kobaruon** [comment]
FYI, they also have official Go SDK https://docs.couchbase.com/go-sdk/current/hello-world/start-using-sdk.html

**Comment by Kobaruon** [comment]
By the way, I stumbled upon this document. It might help you. https://developer.couchbase.com/resources/best-practice-guides/monitoring-guide.pdf

**Comment by ilyam8** [comment]
@hamedbrd 👋 Are you willing to help with `couchbase` collector?

**Comment by hamedbrd** [comment]
@ilyam8 
where should we start?


I took a look at official pkg to see how to get the stats but I think we can not have stats in the official sdk(not too sure about this), but in the unofficial version as they mentioned we do have access to them exactly like your script, so shall we investigate more in offcial package?

Bucket struct in official pkg
https://github.com/couchbase/gocb/blob/171294ec44d0d95af8a261d4231205c567aa63a2/bucket.go#L10-L24 
 
Bucket struc in unofficial pkg
https://github.com/couchbase/go-couchbase/blob/22417a46565f9262c001704f7a4f98f06379735d/pools.go#L225-L261

**Comment by ilyam8** [comment]
@hamedbrd since we have only connect/gather metrics functionallity i think it is ok to use the unofficial pkg. I am pretty sure it works well, it is [used by telegraf couchbase input plugin](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/couchbase/couchbase.go).

**Comment by hamedbrd** [comment]
@ilyam8 I see in `telegraf` they just fetch BasicStats from `couchbase`, are these metrics enough for what we need? 
if so, then would be great to let me know which of these metrics you think we need to involve in the plugin and have a chart for each of them

this is what `telegraf` export from couchbase

```
bs := pool.BucketMap[bucketName].BasicStats
		fields["quota_percent_used"] = bs["quotaPercentUsed"]
		fields["ops_per_sec"] = bs["opsPerSec"]
		fields["disk_fetches"] = bs["diskFetches"]
		fields["item_count"] = bs["itemCount"]
		fields["disk_used"] = bs["diskUsed"]
		fields["data_used"] = bs["dataUsed"]
		fields["mem_used"] = bs["memUsed"]
```

**Comment by ilyam8** [comment]
> are these metrics enough for what we need?

@hamedbrd to be honest i can't really answer this question right now, fortunately we have @Kobaruon helping us, see

> https://github.com/netdata/netdata/issues/4811#issuecomment-694720522

---

I do think that this basic stats per bucket is ok, at least is ok to start with.

**Comment by hamedbrd** [comment]
@ilyam8 if you think basic stats per bucket would be enough to start, then means these metrics
`Bucket 'travel-sample', map[string]interface {}{"dataUsed":5.565952e+07, "diskFetches":0, "diskUsed":6.3980604e+07, "itemCount":31591, "memUsed":5.4327416e+07, "opsPerSec":0, "quotaPercentUsed":51.81066131591797, "vbActiveNumNonResident":0}`

Shall we have a chart per each of these metrics? for example for `opsPerSec` a chart which has these Dims

```
ops_per_sec_bukcet_1

ops_per_sec_bukcet_2

ops_per_sec_bukcet_3
```
Is my understanding correct?

**Comment by ilyam8** [comment]
@hamedbrd give me some time to think about grouping, will try to come up with something by Monday and we discuss it. And if you have time please think about it too 😉

**Comment by ilyam8** [comment]
This [monitoring-couchbase-best-practices](https://github.com/netdata/netdata/issues/4811#issuecomment-706088139) document is very good. I see that ideally we need to go trhough the whole document to create a good collector, however i think it is ok to start with minimal implementation - collect buckets basic stats metrics, and improve it gradually.

Some points from the doc we need to take into account:

> The REST APIs should be polled minutely via a local agent or remotely using the node(s) IP or hostname.
> Limit the number of requests per API when querying metrics, i.e. return all bucket metrics in one request
rather than issuing separate requests per metric. Heavy use of the Couchbase REST APIs can have CPU
utilization impacts on the cluster.

---

Per bucket basic stats - well, there are two options:

- a chart per metric, buckets are dimensions.

```yaml
# `buckets` family, a chart per metric, buckets are dimensions

- buckets       # family 
  - diskFetches # chart
    - bucket1   # dimension
    - bucket2
    - ...
  - diskUsed
    - ...
```

or 

- a family (subsection on the dashboard menu) per buckets, a chart per metric.

```yaml
# a chart per metrics per bucket

- bucket1       # family
  - diskFetches # chart
    - fetches   # dimensions
  - disckUsed
    - used
  - ...
- bucket2
  - ...
```

@Kobaruon which one do you think is better?

**Comment by Kobaruon** [comment]
I think "chart per metric, buckets are dimensions" is a better option.

**Comment by ilyam8** [comment]
Thx for @hamedbrd we added [couchbase collector](https://github.com/netdata/go.d.plugin/tree/master/modules/couchbase#couchbase-monitoring-with-netdata), initial version collects only buckets basic stats (`/pools/default/buckets` endpoint).

Couchbase exposes a lot of metrics, there are a lot of endpoints we can gather metrics from. If there is any interest in improving our collector, consider to open a feature request.

The most obv thing is to gather per bucket detailed stats (`/pools/default/buckets/<custom bucket name>/stats` endpoint), which is requested in https://github.com/netdata/netdata/issues/4811#issuecomment-694720522 - i think i am gonna open an issue in the go.d.plugin repo for it 🤔

**Comment by ilyam8** [comment]
Ok, it is a little bit more complex, according [couchbase-monitoring-best-practices](https://developer.couchbase.com/resources/best-practice-guides/monitoring-guide.pdf) all those cluster-wide endpoints are informational

> These endpoints are informational and should not be used for monitoring as they are an aggregate for the
entire and cluster and the best practice is to monitor each node individually


> the best practice is to monitor each node individually

I guess we need to go through that best-practices document first (checked it briefly)
