### ISSUE TITLE
Pgbouncer monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4812]
We are willing to support monitoring ***[Pgbouncer](https://pgbouncer.github.io/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by jweede** [comment]
Hi @ilyam8. We've been using a custom python plugin to monitor pgbouncer connections/pool sizes.

It's a little rough, but you might find it useful: https://gist.github.com/jweede/a70548456c74b3f6191d34aade2e5328

**Comment by ilyam8** [comment]
@jweede very niceu!

i see telegraf uses `SHOW STATS` and your plugin doesn't use the query, why?

**Comment by ilyam8** [comment]
Don't you want [to rewrite it](https://github.com/netdata/go.d.plugin) in go? it would be cool. If no i can do it myself, but i need your help.

To begin with i need to setup a lab. Please give some instuctions how to do it properly.

**Comment by jweede** [comment]
@ilyam8 the stat data wasn't relevant to our pool size monitoring use case.

I'm not against golang, but I'm not sure I'll have the time to work on it anytime soon.

**Comment by ilyam8** [comment]
Not a problem, please help with 

> To begin with i need to setup a lab. Please give some instuctions how to do it properly.

I am not banned from google, but still it will save my time :smile:

**Comment by jweede** [comment]
heheh. For testing, I used my local netdata install, local pgbouncer, and local postgres on ubuntu.

I'm not sure what more you would need beyond the docs in https://docs.netdata.cloud/collectors/

**Comment by ilyam8** [comment]
So just clean install is ok (sometimes it's not enough), ok, thanks. If i have question i'll ask you if you don't mind.

**Comment by WoLpH** [comment]
I'd be happy to assist in testing the monitoring. I've got a few postgres servers using pgbouncer under a reasonable load (roughly 1000 transactions per second) to see if it gives me anything useful :)

**Comment by cakrit** [comment]
@ilyam8 let's plan this one.

**Comment by thiagoftsm** [comment]
@ilyam8 I already worked with PGbouncer in the past, let me know case I can help you.

**Comment by nerdling** [comment]
> Hi @ilyam8. We've been using a custom python plugin to monitor pgbouncer connections/pool sizes.
> 
> It's a little rough, but you might find it useful: https://gist.github.com/jweede/a70548456c74b3f6191d34aade2e5328

@jweede thanks for keeping this gist up. It's been a lifesaver.

**Comment by dudztroyer** [comment]
Just in case someone is needing the updated collector for PgBouncer with SHOW STATS;, I've updated @jweede collector and tweaked some stuff. The configuration file should be as:

```yaml
yourjobname:
    host: "yourhost"
    user: "youradminuser" #make sure it is an admin in pgbouncer configuration
    password: "duh"
    port: "6432"
```

**Comment by ilyam8** [comment]
Ok, guys. I've added the initial version of the PgBouncer collector. Initially, I used the python version as an example, but pretty fast realized that it had some problems and ended up reading PgBouncer-related articles, PgBcouner GitHub repo issues, and source code. The [PgBouncer documentation](http://pgbouncer.org/usage.html) seems simple at first, but in fact, is not very descriptive and kind of misleading and cryptic - my overall impression.

That is what I did - the [collector readme](https://github.com/netdata/go.d.plugin/tree/master/modules/pgbouncer#pgbouncer-monitoring-with-netdata). There is definitely room for improvement and likely I made some mistakes (never used PgBouncer before). If you can suggest something - go ahead, it will be easy for me to add/change anything.

I am going to add the PgBouncer charts description (dashboard info) and release a new version of the go.d.plugin so the new collector will make it into the upcoming Netdata release.

@jweede @dudztroyer some python version problems:

 - used/free client/servers from "SHOW LISTS;" have nothing to do with connections limit, it is internal cache slots statistics (server_cache, user_cache in the source code). PgBouncer adds slots when needed (used/free client/servers from "SHOW LISTS;" can be seen in "SHOW MEM;").
 - Using pool_size and current_connections from "SHOW DATABASES;" to calculate pool utilization is not correct. PgBouncer creates a pool **per database per user** (the size of the pool - pool_size). The number of pooled connections to a Postgres database is unlimited by default (can be limited using max_db_connections).
