### ISSUE TITLE
Click House monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4813]
We are willing to support monitoring ***[Click House](https://clickhouse.yandex/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by cakrit** [comment]
We have significant interest here, but no sponsor yet. Can someone please assume the role to help us move forward?

**Comment by andrewm4894** [comment]
i actually independently opened a request on the community for this - so linking here for reference. 

https://community.netdata.cloud/t/clickhouse-collector/1318

**Comment by UnamedRus** [comment]
> Specify the metrics required and how they should be presented in charts.
> Specify the alarms that would make sense for each metric.

Good list of metrics / alerts used by our Prometheus collector.
https://kb.altinity.com/altinity-kb-setup-and-maintenance/cluster-production-configuration-guide/monitoring-considerations

**Comment by andrewm4894** [comment]
We have this PR that maybe just needs a little bit of refactoring perhaps. 

https://github.com/netdata/netdata/pull/8682

Would be really cool to try get this over this line.

**Comment by m1khal3v** [comment]
Many useful information about ClickHouse monitoring can be found in Altinity's wiki

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-monitoring/

**Comment by andrewm4894** [comment]
just to update anyone looking at this - there is a python based community contributed clickhouse collector here: https://github.com/netdata/community/tree/main/collectors/python.d.plugin/clickhouse

install instructions are actually in the example used in the readme here: https://github.com/netdata/community/tree/main/collectors#installation
