### ISSUE TITLE
Activemq monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4818]
We are willing to support monitoring ***[Activemq](http://activemq.apache.org/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by rpirsc13** [comment]
@ilyam8 That looks OK in terms of the information it is collecting. Reading the ActiveMQ documentation, the web console gathers information from the advisory topics so it should be efficient for a large number of topics/queues and messages/s

I am not using the web console from AMQ but I can deploy it on my server for testing.

**Comment by ilyam8** [comment]
@rpirsc13 

back to activemq

> I am not using the web console from AMQ but I can deploy it on my server for testing.

please do

i see `telegraf` does requests to these urls:
 * http://ip:port/webadmin/xml/queues.jsp
 * http://ip:port/webadmin/xml/topics.jsp
 * http://ip:port/webadmin/xml/subscribers.jsp

webadmin - ActiveMQ webadmin root path.

Please do these requests yourself and post here returned data.

**Comment by ilyam8** [comment]
ok, i found 

 * queues
```
<queues>
<queue name="sandra">
<stats size="0" consumerCount="0" enqueueCount="0" dequeueCount="0"/>
<feed>
<atom>queueBrowse/sandra?view=rss&amp;feedType=atom_1.0</atom>
<rss>queueBrowse/sandra?view=rss&amp;feedType=rss_2.0</rss>
</feed>
</queue>
<queue name="Test">
<stats size="0" consumerCount="0" enqueueCount="0" dequeueCount="0"/>
<feed>
<atom>queueBrowse/Test?view=rss&amp;feedType=atom_1.0</atom>
<rss>queueBrowse/Test?view=rss&amp;feedType=rss_2.0</rss>
</feed>
</queue>
</queues>
```

 * topics

```
<topics>
<topic name="ActiveMQ.Advisory.MasterBroker ">
<stats size="0" consumerCount="0" enqueueCount="1" dequeueCount="0"/>
</topic>
<topic name="AAA ">
<stats size="0" consumerCount="1" enqueueCount="0" dequeueCount="0"/>
</topic>
<topic name="ActiveMQ.Advisory.Topic ">
<stats size="0" consumerCount="0" enqueueCount="1" dequeueCount="0"/>
</topic>
<topic name="ActiveMQ.Advisory.Queue ">
<stats size="0" consumerCount="0" enqueueCount="2" dequeueCount="0"/>
</topic>
<topic name="AAAA ">
<stats size="0" consumerCount="0" enqueueCount="0" dequeueCount="0"/>
</topic>
</topics>
```

 * subscribers

```
<subscribers>
<subscriber clientId="AAA" subscriptionName="AAA" connectionId="NOTSET" destinationName="AAA" selector="AA" active="no">
<stats pendingQueueSize="0" dispatchedQueueSize="0" dispatchedCounter="0" enqueueCounter="0" dequeueCounter="0"/>
</subscriber>
</subscribers>
```


@rpirsc13 can you help me with creating charts from this data?

And an important question, it seems all those queues, topics, subscribers (i am not a activemq/message broker user, forgive me for ignorance) are dynamics things and they can appear/disappear in runtime. How often it happens? How many queues, topics, subscribers can be? 

I think we need create/delete charts in runtime.

**Comment by rpirsc13** [comment]
@ilyam8 Dynamic charts is the only way to go here. Any client can create/remove topics/queues on the go depending on the ACL ( access control ). Basically an ActiveMQ broker is an enabler for message communication between different clients/applications. IoT devices for example can use MQTT protocol over ActiveMQ to update a single topic with a value. Depending on how the application which uses AMQ is designed, the number of queues/topics can vary ( from a handful to millions )

So here are my thoughts about charts

- The advisory topic/queue charts are not needed. Basically these topics are read by the web console to gather the metrics
- Each Topic/Queue chart should contain the following dimensions. The values collected cannot be used 'as-is' since they are only counters, but we can fiddle around with them to get some interesting information

> 1. Enqueued Messages as `currentEnqueueCount - previousEnqueueCount`. The value represents the number of messages put in the queue/topic by producers.
> 2. Dequeued Messages as `currentDequeueCount - previousDequeueCount`. the value represents the number of message taken out of the queue or read from the topic by the consumers.
> 3. Unprocessed messages ( or in-flight messages ) as `enqueueCount - dequeueCount`. This metric is also very important for the health of the topic/queue so it can be used as an alarm input. The value represents the messages waiting to be consumed.
> 4. Consumer count. Self explanatory ;)

- I have not used yet data from JMX to get subscriber stats but I will research a bit on what the values mean and will let you know if it makes sense to create or not charts for them.

Here is an example of the Dequeue Messages chart. I used the JMX netdata plugin here. The example gathers dequeued messages  as `messages/s` from multiple topics which I custom labeled.
![jmx-amq-example](https://user-images.githubusercontent.com/18198565/50497958-e8b4f680-0a3c-11e9-9f02-748b947868d1.PNG)

**Comment by ilyam8** [comment]
@rpirsc13 

> The advisory topic/queue charts are not needed

Topics/queue with `Advisory` in name?

I see `Advisory` only in topics, not in queues. 

Please post your queues/topics.

> currentEnqueueCount - previousEnqueueCount
> currentDequeueCount - previousDequeueCount
> enqueueCount - dequeueCount

I think we need `incremental`, that will do

> incremental
> the value increases over time,
> the difference from the last value is presented in the chart,
> the server interpolates the value and calculates a per second figure

**Comment by ilyam8** [comment]
And i think i will do 1 chart per topic/queue with `enqueue, dequeue, waiting` dimensions`.
The thing is netdata doesn't support removing dimensions in runtime, but it supports removing charts.

> Dynamic charts is the only way to go here. Any client can create/remove topics/queues on the go depending on the ACL ( access control ). 

There is no way to clenup chart database if we have chart like in your screenshort (topic/queue name as dimension).

What do you think? Is it ok?

**Comment by ilyam8** [comment]
@rpirsc13 

started working on it

**Comment by rpirsc13** [comment]
@ilyam8 sorry for the late reply. New years preparations

> I see `Advisory` only in topics, not in queues.

That is correct. You have advisory topics for `topic` and `queue`. Topics discard messages if there are no consumers and multiply them if there are multiple consumers. So basically messages for the advisory information are just discarded if no one is interested in them ;)

> And i think i will do 1 chart per topic/queue with enqueue, dequeue, waiting dimensions.

That is perfect. We can test afterwords in my application where I have 200+ topics to see how everything scales

>There is no way to cleanup chart database if we have chart like in your screenshort (topic/queue name as dimension).

The screenshot was just an example of what I currently have using the netdata java jmx plugin using `incremental` values as you previously stated.

>started working on it

Good luck and I'll try to answer asap if you have any questions

**Comment by ilyam8** [comment]
@rpirsc13 

> We can test afterwords in my application where I have 200+ topics to see how everything scales

Well, it will be 200+ charts. Do we need some whitelist regex or something? Or maybe max topics/queues options with whitelist regex?

**Comment by ilyam8** [comment]
>  it will be 200+ charts

or even 400+, because every topic has 2 charts - messages and consumers

**Comment by ilyam8** [comment]
@rpirsc13 
to be clear

`consumerCount="0" enqueueCount="1" dequeueCount="0"`

all these are [counter type](https://prometheus.io/docs/concepts/metric_types/#counter), yes?

**Comment by ilyam8** [comment]
found myself
`consumerCoun` is gauge, other two are counter

**Comment by ilyam8** [comment]
@rpirsc13 

i added initial version of `activemq` module, it monitorcs queues and topics statistics. It doesn't monitors subscribers, but if this is needed we will add it for sure.

`go.d.plugin` is not part of netdata but it will be after some time. 

Please test it.

Intruction
https://github.com/netdata/netdata/issues/3218#issuecomment-450560747

**Comment by ilyam8** [comment]
@rpirsc13 

Oh, about this

https://github.com/netdata/netdata/issues/4818#issuecomment-450616821

I add `max_queues` and `max_topics` options, they control how many maximum number of active queues/topics. This is needed to not produce huge number of chart by default.

Please suggest default numbers.

And i think about adding [simple pattern](https://docs.netdata.cloud/libnetdata/simple_pattern/) to the module, to add only those queues/topics which are matched by simple pattern

What do you think?

**Comment by rpirsc13** [comment]
@ilyam8 I will be able to test it at work in the next couple of days. Most probably in the weekend since the days after new years are pretty busy.

>I added max_queues and max_topics options, they define maximum number of active queues/topics. This is needed to not produce huge number of chart by default.

Very nice. I think for first iteration this is perfect. 

> And i think about adding simple pattern to the module, to add only those queues/topics which are matched by simple pattern

That is a very good idea. Maybe grouping by simple patter would be a great addition as well. Like sum all incremental values matching `appname/*` into a single aggregated graph. Just an idea

**Comment by rpirsc13** [comment]
@ilyam8 As an update I have tested the plugin and all topics have been generated successfully in netdata.

> netdata on xx, collects every second 1,942 metrics, presented as 590 charts and monitored by 96 alarms, using 33 MB of memory for 1 hour, 6 mins and 36 secs of real-time history.

So everything looks OK for ~600 charts in total ( around 400 amq charts from a single broker )

![netdata-amq](https://user-images.githubusercontent.com/18198565/50739911-99ae5480-11e6-11e9-9c6b-1ed0bbd491f4.png)

The only issue that I have seen so far is that the enqueue and dequeue increase slightly ( by 1)  but the unprocessed increased by 1400+. Looks a bit weird as it can be seen in the above picture.

**Comment by ilyam8** [comment]
@rpirsc13 ye, it's a bug

```go
metrics["topics_"+rname+"_unprocessed"] = t.Stats.EnqueueCount - t.Stats.DequeueCount
```

^^ i think we need a separate chart for `unprocessed` with units `messages` (not messages/s)

am i right?

**Comment by rpirsc13** [comment]
@ilyam8 

>The question is do we need unprocessed rate or actuall value?

Good question. I think the actual value, so not incremental, is the way go. So as you say a separate chart with just `messages` as the unit.

**Comment by ilyam8** [comment]
Ok, i will add a new chart and simple pattern match tomorrow, i will ping you when it's ready to test

**Comment by ilyam8** [comment]
@rpirsc13 and if you have any other ideas feel free to suggest

**Comment by ilyam8** [comment]
@rpirsc13 

i [fixed](https://github.com/netdata/go.d.plugin/pull/107) the module

i set `max_*` to 50 by default, so change if you need. And i added simple pattern support (it is extended version of [simple pattern](https://docs.netdata.cloud/libnetdata/simple_pattern/), but you can use simple pattern syntax too).

example config

```yaml
jobs:
  - name: job1
    url: http://127.0.0.1:8161
    webadmin: admin
    max_queues: 100
    max_topics: 100
    queues_filter: '!sandr* *'
    topics_filter: '!sandr* *'
```

please test
