### ISSUE TITLE
Nsq monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4821]
We are willing to support monitoring ***[Nsq](https://nsq.io/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by nanom1t** [comment]
Hi. How it is going? I would also like to have NSQ support.

**Comment by ilyam8** [comment]
@nanom1t 

We are [wating for a sponsor](https://github.com/netdata/netdata/issues/4821#issue-386484993).

I guess you are using `nsq` in a production? If so i need your help to start working on it.

___


I see telegraf has 2 `nsq` modules:
  - [nsq](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nsq)
 - [nsq_consumer](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nsq_consumer)

Lets start from the first one (it uses `http://localhost:4151` endpoint to gahter data).

That is `nsq` output:
https://github.com/influxdata/telegraf/blob/c18934f06545ca7fe4e82dfe5aa0eb4ad65382d6/plugins/inputs/nsq/nsq_test.go#L156-L266

Please have a look, what data is important, what should we collect/chart?

**Comment by cakrit** [comment]
Closing due to no sponser.
