### ISSUE TITLE
Aws Ecs monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4837]
We are willing to support monitoring ***[Aws Ecs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/Welcome.html)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by RajezMariner** [comment]
Hey @ilyam8 , May I know if we could monitor AWS resources like ELB, ECS, and other metrics like log analysis through queries (may be smart query!). Could you please provide me the link where I can find the implementing steps.

**Comment by ilyam8** [comment]
Hi @RajezMariner. No, you cant atm. This is why the issue has `help wanted` label (this issue is about `aws ecs` monitoring). 

I have no idea how many parts does asw monitoring consist of. I checked other monitoring solutions and noticed that there is [ecs-exporter](https://github.com/slok/ecs-exporter). It exports following metrics: [link](https://github.com/slok/ecs-exporter#exported-metrics). I dont want to implement it blindly and we are waiting for a sponsor to help.

As for ELB - if you are willing to help i suggest to open a new issue.

**Comment by cakrit** [comment]
Probably related to #4871 . As mentioned in that issue, we'll need to discuss it a bit.

**Comment by ilyam8** [comment]
Few finding that could help:

Monitoring ECS article

>  https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_monitoring.html

aws go sdk lib

> https://github.com/aws/aws-sdk-go

**Comment by ilyam8** [comment]
Closing this feature request. If someone is still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
