### ISSUE TITLE
Cloudflare monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4840]
We are willing to support monitoring ***[Cloudflare](https://www.cloudflare.com/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by cakrit** [comment]
We see some interest here, but no sponsor. Since we use Cloudflare ourselves, one of our SREs should assume the sponsor role.

**Comment by cakrit** [comment]
BTW, this is dog-fooding as well!

**Comment by prologic** [comment]
@cakrit I agree. I'm sure we will collectively help here. I sadly don't have enough intimate knowledge of Cloudflare to be useful as a direct sponsor (_only barely know how to configure it_) but we will help @ilyam8 develop this for sure!

**Comment by ilyam8** [comment]
There is not `dog-fooding` part as well (not sure what is dog-fooding part btw)

Prom exporter

> https://github.com/wehkamp/docker-prometheus-cloudflare-exporter

> A very simple Prometheus exporter that exposes metrics from Cloudflare's colocations API as described in the [API documentation](https://api.cloudflare.com/#zone-analytics-analytics-by-co-locations). Sadly, this is for Cloudflare Enterprise customers only. It'll expose metrics per PoP and shows requests, bandwidth and threats.

It uses 3 endpoints:

- `%szones/%s/analytics/colos?since=-35&until=-5&continuous=false`
- `%szones/%s/firewall/events?per_page=50%s`
- `%szones/%s/dns_analytics/report?metrics=queryCount&dimensions=queryName,queryType,responseCode,coloName&since=%s&until=%s`

Collected metrics:

> https://github.com/wehkamp/docker-prometheus-cloudflare-exporter#metrics

| Name                                 | Description                                               |  Type |
|:-------------------------------------|:----------------------------------------------------------|:-----:|
| `cloudflare_pop_received_requests`   | cached and uncached requests received on an edge-location | gauge |
| `cloudflare_pop_bandwidth_bytes`     | cached and uncached bandwidth sent from an edge-location  | gauge |
| `cloudflare_pop_http_responses_sent` | breakdown of requests per HTTP code                       | gauge |
| `cloudflare_pop_threats_seen`        | number of threats identified received in at this location | gauge |
| `cloudflare_pop_threat_types`        | types of threats seen                                     | gauge |
| `cloudflare_pop_threat_countries`    | countries causing threats                                 | gauge |
| `cloudflare_dns_record_queries`      | DNS record queries per edge-location                      | gauge |
| `cloudflare_waf_uri_hits`            | WAF-rule hits at PoP location per uri                     | gauge |
| `cloudflare_waf_rules`               | WAF-rules in the system and a hit count                   | gauge |

**Comment by ilyam8** [comment]
There is API documentation:

> https://api.cloudflare.com/

I assume there is a lot of info we could collect/chart. But we need a Cloudflare (preferably with Enterpise sub) user to make it.

**Comment by ilyam8** [comment]
Closing this feature request. If someone is still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
