### ISSUE TITLE
Digital Ocean monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4841]
We are willing to support monitoring ***[Digital Ocean](https://www.digitalocean.com/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by cakrit** [comment]
Closing due to no sponsor.
