### ISSUE TITLE
Yarn Resource Manager monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4849]
We are willing to support monitoring ***[Yarn Resource Manager](https://hortonworks.com/blog/apache-hadoop-yarn-resourcemanager/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by shainnif** [comment]
happy to volunteer as a sponsor

**Comment by ilyam8** [comment]
hi @shainnif 

We need same as i requested in https://github.com/netdata/netdata/issues/4853#issuecomment-568797531

In few words: i want to see what metrics we have, which of them are meaningful/important, how could we group them into charts.

**Comment by cakrit** [comment]
@shainnif can you help us with the info @ilyam8 requested?

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
