### ISSUE TITLE
Spark monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4853]
We are willing to support monitoring ***[Spark](https://spark.apache.org/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by shainnif** [comment]
happy to volunteer as a sponsor

**Comment by ilyam8** [comment]
@shainnif hi 👋 

- how to setup a lab? a step-by-step guide would be good (if it is possible)
- how go get metrics? I guess simple http get request? Returned metrics format? It would be nice to have `http request/returned metrics` data

___
Example:

<details>
<summary>/api/v1/somePath</summary>

```json
{"a": 1}
```
</details>

<details>
<summary>/api/v1/somePath2</summary>

```json
{"a": 2}
```
</details>

**Comment by braunsonm** [comment]
Hey @ilyam8 I’ll jump in here to help how I can as well.

Spark is generally run with some form of distributed storage backend. The most popular (in my experience) being Hadoop. Getting this running locally isn’t much of a pain, and you can also run without a distributed storage backend if you’re going to play around locally.

To setup spark in standalone mode (simpliest for testing):

- Download the prebuilt package, extract it. [Here is a link for the latest stable pre-built with Hadoop support](https://www.apache.org/dyn/closer.lua/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz)
- Edit some of the configuration files to your liking, for instance:

`conf/spark-defaults.conf`:
```shell script
# Example:
# spark.master                     spark://master:7077
# spark.eventLog.enabled           true
# spark.eventLog.dir               hdfs://namenode:8021/directory
# spark.serializer                 org.apache.spark.serializer.KryoSerializer
spark.driver.memory                1g
spark.executor.memory		   4g
spark.driver.cores		   1
spark.executor.cores		   2
```

`conf/spark-env.sh`:
If you have multiple java versions installed you may want to provide a `JAVA_HOME` to the driver and executors.

```
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home
```

Lastly, you can start/stop your local cluster by using the following commands.

- Startup:
```shell script
# In Spark Install Directory
sbin/start-all.sh
# WebUI Running on http://localhost:8080
```

- Shutdown:
```shell script
# In Spark Install Directory
sbin/stop-all.sh
```

If you’d also like instructions to setup Hadoop let me know. 

You can then submit one of the example jobs with the following:

```shell
# For Scala and Java, use run-example:
./bin/run-example SparkPi

# For Python examples, use spark-submit directly:
./bin/spark-submit examples/src/main/python/pi.py

# For R examples, use spark-submit directly:
./bin/spark-submit examples/src/main/r/dataframe.R
```

All of these commands assume you’re in the extracted directory.

—

Some useful API’s and more can be found here: https://spark.apache.org/docs/latest/monitoring.html#rest-api

<details>
  <summary>/api/v1/applications</summary>
  
  A list of running applications and their status.
  
  ```
?status=[completed|running] list only applications in the chosen state. 
?minDate=[date] earliest start date/time to list. 
?maxDate=[date] latest start date/time to list. 
?minEndDate=[date] earliest end date/time to list. 
?maxEndDate=[date] latest end date/time to list. 
?limit=[limit] limits the number of applications listed. 
Examples: 
?minDate=2015-02-10 
?minDate=2015-02-03T16:42:40.000GMT 
?maxDate=2015-02-11T20:41:30.000GMT 
?minEndDate=2015-02-12 
?minEndDate=2015-02-12T09:15:10.000GMT 
?maxEndDate=2015-02-14T16:30:45.000GMT 
?limit=10
  ```
  
</details>

<details>
  <summary>/api/v1/applications/[app-id]/executors</summary>
  
  Status of executors involved in an app ID. This gives you information such as runtime, CPU usage, etc.
</details>

**Comment by ilyam8** [comment]
Hi @braunsonm thx for the detailed response. A lot of [endpoints](https://spark.apache.org/docs/latest/monitoring.html#rest-api) 😅 

That is [what datadog do](https://github.com/DataDog/integrations-core/blob/91d854728b045a74718ed4b1bb964cbd5215fc7e/spark/datadog_checks/spark/spark.py#L167-L183):

- get running apps

for every app (num of http requests == num of apps):

- get job metrics (for every app) 
- get stage metrics (for every app)
- get executor metrics (for every app)
- get rdd metrics (for every app)
- get streaming statistics metrics (for every app)

Does it look good to you? What do you think?

Current netdata dashboard is pretty limited, there is no way to represent the whole thing in a nice way unfortunately.

**Comment by braunsonm** [comment]
@ilyam8 That looks good to me!

How do you plan to display all the executor metrics? Since that will be num apps*num executors amount of data, could be a lot to show

**Comment by ilyam8** [comment]
> How do you plan to display all the executor metrics?

i have no plan, i have no idea how those metrics look like 😅 But i assume it wont be easy (probably even impossible atm), that is why i said

> Current netdata dashboard is pretty limited, there is no way to represent the whole thing in a nice way unfortunately.

@braunsonm i guess we could start from the metrics, could you share your spark metrics?

**Comment by braunsonm** [comment]
Unfortunately for privacy reasons I’m unable to share my own metrics, hopefully I can help in other ways.

**Comment by cakrit** [comment]
@ilyam8 let's see how we can pick this up again. We shouldn't need the user's metrics to build the collector, we can set up our instance and @braunsonm can continue to guide us to get it done.

**Comment by ilyam8** [comment]
in addition to https://github.com/netdata/netdata/issues/4853#issuecomment-574486437

https://github.com/big-data-europe/docker-spark

**Comment by ilyam8** [comment]
Closing this feature request. If someone is still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
