### ISSUE TITLE
CoreDNS monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4861]
We are willing to support monitoring ***[CoreDNS](https://coredns.io/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by ilyam8** [comment]
Ok, it is not easy.

___

Brief summary, details [there](https://coredns.io/manual/toc/#what-is-coredns):

Once CoreDNS has been started and has parsed the configuration, it runs Servers. Each Server is defined by the zones it serves and on what port. Each Server has its own Plugin Chain.

When a query is being processed by CoreDNS, the following steps are performed:
 - If there are multiple Servers configured that listen on the queried port, it will check which one has the most specific zone for this query (longest suffix match).
 - Once a Server has been found, it will be routed through the Plugin Chain.
 - Each plugin will inspect the query and determine if it should process it.

Processing a query means a Plugin will respond to the client with a reply.

If the plugin decides it will not process a query, it simply calls the next plugin in the chain. If the last plugin in the chain decides to not process the query, CoreDNS will return SERVFAIL back to the client.

If monitoring is enabled, **queries that do not enter the plugin chain are exported under the fake name "dropped"** (without a closing dot - this is never a valid domain name).
___

CoreDNS exported metrics:
 - `coredns_panic_count_total{}`
 No tags, no problems!
 - `coredns_dns_request_count_total{server, zone, proto, family}`
 Total count of requests _per server per zone per proto per family_.
 - `coredns_dns_request_duration_seconds{server, zone}`
 Duration to process each query in seconds _per server per zone_. Histogram.
 - `coredns_dns_request_size_bytes{server, zone, proto}`
 Size of the request in bytes _per server per zone per proto_. Histogram.
 - `coredns_dns_response_size_bytes{server, zone, proto}`
 Response size in bytes _per server per zone per proto_. Histogram.
 - `coredns_dns_request_type_count_total{server, zone, type}`
 Counter of queries _per server per zone per type_.
 - `coredns_dns_response_rcode_count_total{server, zone, rcode}`
 Counter of responses _per server per zone per rcode_.

**Comment by ilyam8** [comment]
Since i see no way to create a lot of specific charts, i think we need to focus on summary charts first.

___

Charts:
 - `coredns_panic_count_total{}`
   - Panic Rate
 - `coredns_dns_request_count_total{server, zone, proto, family}`
   - Requests Rate (total, including dropped)
   - Requests Rate Per Status (processed vs dropped, maybe 2 charts, actual values and percentages)
   - Requests Rate Per Proto (total per proto, including dropped)
   - Requests Rate Per Family (total per family, including dropped)
 - `coredns_dns_request_duration_seconds{server, zone}`
   I think summary doesn't make sense here. Am i wrong?
 - `coredns_dns_request_size_bytes{server, zone, proto}`
   I think summary doesn't make sense here. Am i wrong?
 - `coredns_dns_response_size_bytes{server, zone, proto}`
   I think summary doesn't make sense here. Am i wrong?
 - `coredns_dns_request_type_count_total{server, zone, type}`
   - Processed Requests Rate By Type (excluding dropped)
   - Dropped Requests Rate By Type
 - `coredns_dns_response_rcode_count_total{server, zone, rcode}`
   - Processed Responses Rate By RCode (excluding dropped)
   - Dropped Responses Rate By RCode

**Comment by cakrit** [comment]
We had a discussion today with @ilyam8 and we have a way forward now.
