### ISSUE TITLE
Envoy monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4866]
We are willing to support monitoring ***[Envoy](https://www.envoyproxy.io/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by cakrit** [comment]
Envoy [service mesh](https://www.envoyproxy.io/learn/service-mesh) is also quite interesting and it supports statsd.

Perhaps we can just create a few synthetic charts and document how to configure envoy itself, something similar to this: https://hackernoon.com/microservices-monitoring-with-envoy-service-mesh-prometheus-grafana-a1c26a8595fc

**Comment by ilyam8** [comment]
I see envoy has `/stats` endpoint

https://github.com/DataDog/integrations-core/tree/master/envoy#standard

A lot of metrics btw
https://docs.datadoghq.com/integrations/envoy/#metrics

It looks like envoy exposes metrics in prometheus format
https://github.com/envoyproxy/envoy/pull/2896

**Comment by cakrit** [comment]
There's some interest here, but no sponsor. Can someone help us by assuming this role?

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
