### ISSUE TITLE
Ecs Fargate monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4867]
We are willing to support monitoring ***[Ecs Fargate](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_GetStarted.html)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by memberbetty** [comment]
You can just refer to the Datadog integration with Fargate for a first implementation.

**Comment by cakrit** [comment]
This one looks very important. 
I scanned https://docs.datadoghq.com/integrations/ecs_fargate/ and https://www.datadoghq.com/blog/monitor-aws-fargate/ 
Datadog uses statsd and process monitoring, so it looks like we can do this one with some tests, configuration (synthetic charts) and a how-to/README. I'll see if we can do it together with @vlkobal.

**Comment by ilyam8** [comment]
I see that the integration collects metrics using http requests

https://github.com/DataDog/integrations-core/blob/4b998ef8e8434e7083e5a74110171668537e2749/ecs_fargate/datadog_checks/ecs_fargate/ecs_fargate.py#L26-L28

In addition datadog agent can collect custom statsd metrics from containers/application
https://github.com/DataDog/integrations-core/tree/master/ecs_fargate#dogstatsd

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.

**Comment by Syd-Ra** [comment]
I've opened a feature request on the forum as suggested; link below for reference in case it's useful.
https://community.netdata.cloud/t/aws-ecs-fargate-support/1420

**Comment by diegosasw** [comment]
Is there any up to date mechanism to monitor services/tasks running in AWS ecs fargate?
