### ISSUE TITLE
Amazon Cloudwatch monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4871]
We are willing to support monitoring ***[Amazon Cloudwatch](https://aws.amazon.com/cloudwatch/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by matrey** [comment]
FYI here are a few incidents "worthy of alerting" that I got in the past on AWS, and that can't be easily figured out from within the instance. 
They can be detected through the free CloudWatch metrics listed in the AWS console under the "Monitoring" tab.

- dead instance
  - EC2 / "Status Check Failed (Any) ( Count )"
- very high latency between the instance and disk (> 100 ms)
  - EBS / "Average Queue Length ( Operations )" 
  - and/or EBS / "Average Write Latency ( ms/op )" / "Average Read Latency ( ms/op )"
- depleted CPU credits for t2 instances without the new "t2 unlimited" option enabled, meaning that you only get baseline CPU (very slow)
  - EC2 / "CPU Credit Balance ( Count )" (potentially "CPU Credit Usage ( Count )" for forecasting)
- depleted IOPS on EBS 
  - EBS / "Burst Balance ( Percent )"

Now the economics could be an issue...
- It's possible to create CloudWatch alarms for 0.10 USD each (seems like it's per month).
- Calls to the GetMetricData API are priced at $0.01/"1,000 metrics requested"

So if I'm not mistaken:
- 1000 metrics with a CloudWatch alarm for 1 month = 100 USD
- calls to the GetMetricData API every 5 minutes (that's the resolution of free metrics anyway) for 1000 metrics for 1 month = 8640 API calls = 86.4 USD

So for my use case, focused on alerting, the cost is similar (though given that these metrics are varying slowly, I could afford an even lower frequency, e.g. once every 30 mn or 1 hour). 
But any resolution lower than 5 minutes would probably get very pricey in terms of API call cost.

**Comment by cakrit** [comment]
What @matrey wrote here regarding the economics is very important. Difficult to decide what would be "sane default settings" in this scenario.

We just started using AWS ourselves and we can discuss internally what makes sense. Perhaps netdata in this case could be used to provide extremely high resolution for user-selected metrics, for a short period of time, just to assist with troubleshooting. But not sure.

**Comment by ilyam8** [comment]
Closing this feature request. If someone is still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
