### ISSUE TITLE
Dm-Cache monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4873]
We are willing to support monitoring ***[Dm-Cache](https://en.wikipedia.org/wiki/Dm-cache)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by cakrit** [comment]
Closing due to no interest/sponsor.

**Comment by Ferroin** [comment]
Hate to revive a functionally dead issue, but I'm willing to sponsor this (though I unfortunately don't have the background in C or how our C collectors work to do the actual coding myself).

There are not (as far as I can tell) any special statistics for dm-cache itself, but the UX relating to the regular disk stats for dm-cache could be significantly improved by grouping the basic disk statistics charts for the components of each dm-cache device under the same context as the main device itself. Each dm-cache device consists of 3 functional components: an origin device (the large slow device that is being cached), a cache data device (the small fast device used for storing the cached data), and a cache metadata device (a tiny fast device used for maintaining internal state for the dm-cache code for the device). Currently these each have their own context, making it harder to keep track of what devices are associated with each other.

Actually figuring out this association is most readily done by inspecting the device-mapper table for the devices (this also tells you if it's cached or not). Sample table (from `dmsetup table` for a cached device:

```0 1610612736 cache 253:26 253:25 253:27 128 2 metadata2 writethrough smq 0```

Third value is the table type. fourth is the device major and minor for the cache metadata device, fifth is the same for the cache data device, and sixth is the same for the cache origin device.
