### ISSUE TITLE
Opensmtpd monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4883]
We are willing to support monitoring ***[Opensmtpd](https://www.opensmtpd.org/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by ScrumpyJack** [comment]
does this help?
```
>time smtpctl show stats
bounce.envelope=0
bounce.message=0
bounce.session=0
control.session=1
mda.envelope=0
mda.pending=0
mda.running=0
mda.user=0
mta.connector=0
mta.domain=0
mta.envelope=0
mta.host=0
mta.relay=0
mta.route=0
mta.session=0
mta.source=0
mta.task=0
mta.task.running=0
queue.bounce=14
queue.evpcache.load.hit=8286
queue.evpcache.size=0
queue.evpcache.update.hit=1
scheduler.delivery.ok=4132
scheduler.delivery.permfail=12
scheduler.delivery.tempfail=1
scheduler.envelope=0
scheduler.envelope.expired=2
scheduler.envelope.incoming=0
scheduler.envelope.inflight=0
scheduler.ramqueue.envelope=0
scheduler.ramqueue.message=0
scheduler.ramqueue.update=0
smtp.session=0
smtp.session.inet4=41063
smtp.session.inet6=2
smtp.session.local=103
smtp.tls=0
uptime=3889929
uptime.human=45d32m9s
smtpctl show stats  0.01s user 0.01s system 70% cpu 0.024 total

> time smtpctl show status
MDA running
MTA running
SMTP running
smtpctl show status  0.00s user 0.00s system 69% cpu 0.010 total
```

**Comment by cakrit** [comment]
@ilyam8 plz check.

**Comment by ilyam8** [comment]
@ScrumpyJack 👋 

are you still using `Opensmtpd`?

> graphs grouping should come naturally?

I would prefer your help with grouping 😄 

And i need info on types of metrics - counters/gauges.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.

**Comment by ScrumpyJack** [comment]
Yes sorry, I have not been keeping an eye on this. Happy to provide any info and help. Can we start again?

**Comment by ilyam8** [comment]
Hi @ScrumpyJack. I think lets create a topic [as i suggested](https://github.com/netdata/netdata/issues/4883#issuecomment-770713629).
