### ISSUE TITLE
Salesforce monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4885]
We are willing to support monitoring ***[Salesforce](https://www.salesforce.com/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by fullstackpiyush** [comment]
Hi,
How can I be helpful to this issue.

**Comment by ilyam8** [comment]
Hi @fullstackpiyush 	

Do you use salesforce?

I see [telegraf plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/salesforce) collects

> metrics about the limits in your Salesforce organization and the remaining 
 usage.

There is the limits

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_limits.htm

What do you think? Is this important to collect/visualize?

**Comment by stackpiyush** [comment]
Hi @ilyam8,

Apologies for very Late response.
As a developer I think it is very important to visualize the governor limits.
That will help anyone to plan further development in a multi-tenant environment.
It's also very important aspect to save organisation cost as well.

Warm Regards,
Piyush Kumar

**Comment by fullstackpiyush** [comment]
Hi @ilyam8,

Apologies for very Late response.
As a developer I think it is very important to visualize the governor limits.
That will help anyone to plan further development in a multi-tenant environment.
It's also very important aspect to save organisation cost as well.

Warm Regards,
Piyush Kumar

**Comment by cakrit** [comment]
@ilyam8 this one appears to have been forgotten.

**Comment by startryst** [comment]
this is a good initiative, even though I can't help, but look forward to seeing any progress of this collector! And in the mean time, if other popular SaaS service can be monitored, even better!

**Comment by startryst** [comment]
And btw, if any of you wish the sponsor of tinc/VPN, I'd love to help.... @ilyam8

**Comment by startryst** [comment]
> this is a good initiative, even though I can't help, but look forward to seeing any progress of this collector! And in the mean time, if other popular SaaS service can be monitored, even better!

Office365 is another perfect use case/example...

**Comment by ilyam8** [comment]
> Office365 is another perfect use case/example...

what do you mean? Monitor `Office365`, really? 😄 How does it expose metrics? What metrics does it expose?

**Comment by startryst** [comment]
> > Office365 is another perfect use case/example...
> 
> what do you mean? Monitor `Office365`, really? 😄 How does it expose metrics? What metrics does it expose?

right, so I would say the similar effort of you guys are working on salesforce should be the same....even though I don't have a tangible clue yet.

The initial thought might be, to measure the experience of fast/slow when connections to office365/salesforce looks like.

**Comment by startryst** [comment]
or, this thread is talking about, install the saleforce instance or something on the host, so that we monitor?

**Comment by ilyam8** [comment]
> @ilyam8 this one appears to have been forgotten.

Indeed!

@fullstackpiyush sorry for this.

> As a developer I think it is very important to visualize the governor limits.

Ok, collect [limits](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_limits.htm) doesnt seem hard.

I see there is `Scaceforce` [trial period](https://www.scaleforce.net/cloud-hosting-free-trial), i could use to create the module.

___

I am not clear about version. It seems current is `v48.0`.

Resource limits documentation:

> https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_limits.htm

According it they add new limits. But there is no _removed limits_.

Since it is cloud service i guess it is auto updated for all customers, am i right? Or there is an option which version to use/upgrade or stay on current?

**Comment by ilyam8** [comment]
> The initial thought might be, to measure the experience of fast/slow when connections to office365/salesforce looks like.



`Scaleforce` provides RESTAPI go fetch some metrics

> https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_what_is_rest_api.htm

Does `Office365` has something similar?

**Comment by ilyam8** [comment]
@fullstackpiyush are you still using `Scaleforce`?

**Comment by startryst** [comment]
> > The initial thought might be, to measure the experience of fast/slow when connections to office365/salesforce looks like.
> 
> `Scaleforce` provides RESTAPI to fetch some metrics
> 
> > https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_what_is_rest_api.htm
> 
> Does `Office365` has something similar?

https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/

But I still couldn't get it, this API is for from the client perspective, so are you working on this plug-in for the client? Normally the host/server we installed netdata is not the client side, correct me if i'm wrong, just try to figure out the use case.

**Comment by ilyam8** [comment]
In the collection context Netdata is a client, application is a service. Netdata uses application API to get its metrics.

**Comment by startryst** [comment]
can you give me one example of typical metrics, so that I can have a better understanding of the use case of this plug-in?

Like, how many active sales opportunities there for my salesforce account? 

If that's the case, this is beyond monitor the host itself (which is my fundamental understanding of Netdata), instead, it's monitoring something else...

**Comment by ilyam8** [comment]
Organisation limits metrics:
> https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_limits.htm

See
> https://github.com/netdata/netdata/issues/4885#issuecomment-485497649


Probably there are some other good metrics we could collect, it is hard to say for me, since i am not a `Scaleforce` user.

RESTAPI (we are going to use it to gather metrics) documentation:

> https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_what_is_rest_api.htm

**Comment by ilyam8** [comment]
@startryst are you still interested in this plugin? We could start from the following metrisc:

> https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_limits.htm

**Comment by startryst** [comment]
> @startryst are you still interested in this plugin? We could start from the following metrisc:
> 
> > https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_limits.htm

I can't get the point of the use case with netdata, but please go ahead to if you guys made the decision.

What I interested is, whether is it feasible to measure the network performance of when users access salesforce.com, you know sometimes users complained about slow experience of salesforce, but  how can we get it quantified?

**Comment by ilyam8** [comment]
> I can't get the point of the use case with netdata

Well, this is important, if the is no use case we shouldnt do it. I am not a Scaleforce user, it is hard to understand if it makes sense or not.

I was thinking it makes some sense because of

> For each limit, this resource returns the maximum allocation and the remaining allocation based on usage.

Remaining/maximum ratio.

___

> whether is it feasible to measure the network performance of when users access salesforce.com

Probably you could use [http_check module](https://github.com/netdata/go.d.plugin/tree/master/modules/httpcheck#any-http-endpoints-monitoring-with-netdata).

**Comment by startryst** [comment]
> Probably you could use http_check module.

This is cool, I'll get a try some time.

> For each limit, this resource returns the maximum allocation and the remaining allocation based on usage.

I have no idea at all about this, are you talking about install salesforce on the server? I assume salesforce.com is a SaaS service from cloud, there isn't any  server software install into the server, what I know is the client side which is the browser, so that why measure the experience from client/browser to the cloud is the thing I mentioned above.

**Comment by cakrit** [comment]
Maybe we should just close this issue, I don't think it's going to be a useful feature. @dim08 check.
