### ISSUE TITLE
Tengine monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4886]
We are willing to support monitoring ***[Tengine](http://tengine.taobao.org/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by jlyonsmith** [comment]
I'll sponsor it as long as this basically means replicating the existing Nginx monitoring support.  We're about to set up a Tengine instance for our production site so I was going to do the work anyway.  If that's OK, I'll just submit a PR and ask for help getting the appropriate tests in place.

**Comment by ilyam8** [comment]
Hi @jlyonsmith 
>  If that's OK, I'll just submit a PR and ask for help getting the appropriate tests in place.

I suggest to do it in [go](https://github.com/netdata/go.d.plugin)

**Comment by ilyam8** [comment]
it seems not hard, i see we need `ngx_http_reqstat_module` module

http://tengine.taobao.org/document/http_reqstat.html

**Comment by jlyonsmith** [comment]
Yes @ilyam8, it seems very doable.  I have a Tengine instance installed and I have configured that module and it seems to work as advertised.
