### ISSUE TITLE
Vsphere monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4888]
We are willing to support monitoring ***[Vsphere](https://www.vmware.com/products/vsphere.html)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by mrtomte** [comment]
i would love to see this implementation!

**Comment by cakrit** [comment]
It looks like there's some interest in this one. is anyone willing to assume the role of the sponsor as described in the original post?

**Comment by spiegela** [comment]
@cakrit @ilyam8 I'm interested in support for netdata in vSphere, and would be happy to sponsor, but I'm not sure how useful my feedback will be. My cluster is only a 4 node environment used for development, so it doesn't have nearly the requirements of a production environment.

**Comment by ilyam8** [comment]
@spiegela 	

To begin with we need to identify what should be monitored. I see telegraf has a nice vsphere plugin (it is huge and collects a lot of metrics).

Metrics - https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vsphere/METRICS.md

Any other metrics we could be interested in?

___ 
The problem is

> The set of performance metrics in vSphere is open ended. Metrics may be added or removed in new releases and the set of available metrics may vary depending hardware, as well as what plugins and add-on products are installed. Therefore, providing a definitive list of available metrics is difficult. The metrics listed below are the most commonly available as of vSphere 6.5.

So the set of metrics is vary a lot...

**Comment by spiegela** [comment]
IMO, I would focus first on the "host" and "datastore" metrics, since the monitoring of guests (vms) can be handled by the existing OS support.  It would be fine to add metrics that align with existing stats from the Linux dashboards, and add others based on request, if that makes the implementation easier.

I would add the guests next, since it _would_ be a pretty exciting feature to monitor each of the running machines effectively "agentless", but many users will still want to install a local presence in the guest to get details not available from vCenter.

I would focus on the cluster stats last, since those are the least looked at (in my experience).

**Comment by jimidak** [comment]
I am starting to collect some ESXi 6.5. I will post findings as I get it ironed out. If I make a little headway and it seems like it's going to be a legitimate solution, I can be a "sponsor"

**Comment by Saruspete** [comment]
Hello,

Do you need more testers for this feature ? I would very like to have it.
If you need more info on the metrics & their source, you can check Sexigraph : http://www.sexigraf.fr/quickstart/  / http://www.sexigraf.fr/web-admin/

Adrien.

**Comment by ilyam8** [comment]
> Do you need more testers for this feature ?

Yes, it will be ready soon. It will monitor vm/hosts only, because only these entities have real-time metrics. Clusters, datastores and datacenters have only historic values (updated every 300 seconds)

**Comment by BR0KK** [comment]
I'm currently looking for options to monitor my esxi hosts. At the moment i would be interested to monitore datastores (space usasge and the likes). 

I'd try this when its ready :) 

How are you connecting to esx/ vsphere via smnp, ssh or MOB/API?

**Comment by ilyam8** [comment]
Hey @BR0KK, as i said

> It will monitor vm/hosts only, because only these entities have real-time metrics. 

> Clusters, datastores and datacenters have only historic values (updated every 300 seconds) 

^^ I dont know about clusters, datastores and datacenters, maybe it will be a separate collector


> How are you connecting to esx/ vsphere via smnp, ssh or MOB/API?

via http https://github.com/vmware/govmomi

**Comment by ilyam8** [comment]
vCenter itself some health metrics too

```
HEALTH:
	The vCenter Server Appliance API offers health status indicators for several key components of the appliance:
 - green  The component is healthy.
 - yellow The component is healthy, but may have some problems.
 - orange The component is degraded, and may have serious problems.
 - red The component is unavailable, or will stop functioning soon.
 - gray No health data is available.
```

This should be monitored too, it looks like a separate collector for me too, but not sure

**Comment by ilyam8** [comment]
https://github.com/netdata/go.d.plugin/tree/master/modules/vsphere#vsphere

**Comment by ilyam8** [comment]
I added all available metrics (from my lab, they may differ) to [the metrics.txt ](https://github.com/netdata/go.d.plugin/blob/master/modules/vsphere/metrics.txt)file. Initial implementation collects only part of them, only general performance metrics. It wont be hard to add other metrics.

Lack of tags and dashboard ability to show nested objects are two huge limitations for vsphere collector.

**Comment by rgumti** [comment]
Would there be any installation instructions/notes for this plugin? I would love to try it out.

**Comment by ilyam8** [comment]
Hi @rgumti 

There is no special instruction.

Just uncomment the section in the `vsphere.conf` 

https://github.com/netdata/go.d.plugin/blob/f6a368ab9420dbfba3cf4848a8030ce66c8c2bc9/config/go.d/vsphere.conf#L142-L146

and set your vcenter user/pass

See readme

https://github.com/netdata/go.d.plugin/tree/master/modules/vsphere

**Comment by rgumti** [comment]
Hi @ilyam8 

Thank you so much!! I got this working now. Using the directions and docs you provided.

Steps I took on my Centos 8 machine:
Copy the conf:
`cp /usr/lib/netdata/conf.d/go.d/vsphere.conf /etc/netdata/go.d/`

Edit the conf:
`/etc/netdata/edit-config  /etc/netdata/go.d/vsphere.conf`

Uncommet and edit the following:
```
jobs:
  - name     : vcenter
    url      : https://<IP>
    username : administrator@vsphere.local
    password : <PASSWORD>
    tls_skip_verify: yes
```

Once done I Tested with the following:
`/usr/libexec/netdata/plugins.d/go.d.plugin -d -m vsphere`

**Comment by ilyam8** [comment]
@rgumti how many hosts/vms do you have?

**Comment by rgumti** [comment]
@ilyam8 I first used netdata at work to check performance on our filers. However I am currently using it in my homelab. I have 3 esxi hosts and roughly 12 VMs.

**Comment by Mrgove10** [comment]
Works great for homelab use, 11 vms all detected and working great !

**Comment by ilyam8** [comment]
It works great until you restart vcenter hehe 😄 Keep it in mind, will be fixed later.
