### ISSUE TITLE
Zookeeper monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4889]
We are willing to support monitoring ***[Zookeeper](https://zookeeper.apache.org/)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by killerwhile** [comment]
I can also give a hand for Zookeeper.

Zookeeper has [4 letters words](https://zookeeper.apache.org/doc/r3.4.8/zookeeperAdmin.html#sc_zkCommands) 
command which includes monitoring: `stat`, `mntr`, `cons`, `srvr`:

```
echo mntr | nc localhost 2182
```

gives you a ton of metrics back.

**Comment by ilyam8** [comment]
Nice. I checked which commands other monitoring solution use.

[telegraf](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/zookeeper):
 - `mntr`

[datadog](https://github.com/DataDog/integrations-core/blob/master/zk/datadog_checks/zk/zk.py):
 - `stat`
 - `ruok`
 - `mntr`

**Comment by killerwhile** [comment]
Thanks for checking others.
`srvr` and `stat` are all superseded by `mntr`. `cons` is giving a lots of finer grained details regarding individual connections. See examples for all 4 commands below to get an idea:

# `stat`

```
Zookeeper version: 3.4.6-5--1, built on 10/23/2017 21:20 GMT
Clients:
 /10.100.1.6:35900[1](queued=0,recved=103,sent=103)
 /10.100.1.92:60894[1](queued=0,recved=96150,sent=96150)
 /10.100.1.126:53296[1](queued=0,recved=17098,sent=17100)
 /127.0.0.1:35866[0](queued=0,recved=1,sent=0)

Latency min/avg/max: 0/0/3429
Received: 14167229
Sent: 14167229
Connections: 4
Outstanding: 0
Zxid: 0x12002d8b19
Mode: follower
Node count: 20787
```

# `srvr`

```
Zookeeper version: 3.4.6-5--1, built on 10/23/2017 21:20 GMT
Latency min/avg/max: 0/0/3429
Received: 14167308
Sent: 14167308
Connections: 4
Outstanding: 0
Zxid: 0x12002d8b1b
Mode: follower
Node count: 20787
```

# `mntr`

```
zk_version	3.4.6-5--1, built on 10/23/2017 21:20 GMT
zk_avg_latency	0
zk_max_latency	3429
zk_min_latency	0
zk_packets_received	14167409
zk_packets_sent	14167409
zk_num_alive_connections	4
zk_outstanding_requests	0
zk_server_state	follower
zk_znode_count	20787
zk_watch_count	3
zk_ephemerals_count	11
zk_approximate_data_size	36746665
zk_open_file_descriptor_count	67
zk_max_file_descriptor_count	4096
```

# `cons`

```
 /10.100.1.6:35900[1](queued=0,recved=112,sent=112,sid=0x16bd03cfbd40120,lop=PING,est=1565874594608,to=30000,lcxid=0x29,lzxid=0xffffffffffffffff,lresp=1565875305349,llat=0,minlat=0,avglat=0,maxlat=23)
 /10.100.1.92:60894[1](queued=0,recved=96154,sent=96154,sid=0x16bd03cfbd40063,lop=PING,est=1563968293917,to=60000,lcxid=0x33e,lzxid=0xffffffffffffffff,lresp=1565875290575,llat=0,minlat=0,avglat=0,maxlat=235)
 /10.100.1.126:53296[1](queued=0,recved=17283,sent=17285,sid=0x16bd03cfbd4011a,lop=GETD,est=1565867770416,to=6000,lcxid=0x3597,lzxid=0x12002d8b1f,lresp=1565875305864,llat=0,minlat=0,avglat=1,maxlat=3429)
 /127.0.0.1:36210[0](queued=0,recved=1,sent=0)
```

I'd suggest to start with `mntr`.

**Comment by ilyam8** [comment]
ok, i installed [zookeper 3.5.5(docker)](https://hub.docker.com/r/jplock/zookeeper)


# mntr
```
31 ilyam:~ $ echo mntr | nc localhost 2181
zk_version	3.5.5-390fe37ea45dee01bf87dc1c042b5e3dcce88653, built on 05/03/2019 12:07 GMT
zk_avg_latency	0
zk_max_latency	0
zk_min_latency	0
zk_packets_received	2
zk_packets_sent	1
zk_num_alive_connections	1
zk_outstanding_requests	0
zk_server_state	standalone
zk_znode_count	5
zk_watch_count	0
zk_ephemerals_count	0
zk_approximate_data_size	44
zk_open_file_descriptor_count	46
zk_max_file_descriptor_count	1048576
```

@killerwhile  I see my ouput contains all metrics (compared to yours), this is nice.

What about auth? I think there is no such thing as auth, the command is either whitelisted or not.

**Comment by ilyam8** [comment]
I added all `mntr` metrics. If we need to add something else feel free to suggest @killerwhile 	


I think `ruok` command is a good candidate, i dont know what it is but it seems it is important

datadog check:

```python
            if ruok == 'imok':
                status = AgentCheck.OK
            else:
                status = AgentCheck.WARNING
```

**Comment by ilyam8** [comment]
Hm, i am not clear how to deal with `ruok`

from [admins guide](https://zookeeper.apache.org/doc/r3.1.2/zookeeperAdmin.html#sc_monitoring)
> Tests if server is running in a non-error state. The server will respond with imok if it is running. Otherwise it will not respond at all.

So we should chart `no response`. It means that module will never fail, even if `address` is points to not existing server 🤔

**Comment by killerwhile** [comment]
@ilyam8 
No auth. We see more and more ZK clusters running with ssl/client cert sidecars to perform auth. This might come as a request sooner than later.

`ruok`: if the answer is `imok` then it's good, for anything else (different answer) or no answer, it's at least a warn.

**Comment by ilyam8** [comment]
> certificate option might come as a request sooner than later

i added connection support

https://github.com/netdata/go.d.plugin/blob/02b5f76a43e0f8cb69e936f3a33560797ae2b178/config/go.d/zookeeper.conf#L69-L92

**Comment by ilyam8** [comment]
> ruok: if the answer is imok then it's good, for anything else (different answer) or no answer, it's at least a warn.

@killerwhile 

Still not clear about `ruok`, do we need it in addition to `mntr` call?

I mean `ruok` if just a ping, if there are some problem server doesnt respond. I assume we have same with `mntr` - server doesnt respond if there are some problems.

Or there can be some cases when server responds to `mntr` but not to `ruok`?
