### ISSUE TITLE
Hadoop Hdfs monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4890]
We are willing to support monitoring ***[Hadoop Hdfs](https://hadoop.apache.org/docs/r1.2.1/hdfs_design.html)*** with netdata.

To get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by killerwhile** [comment]
Hi @ilyam8 , if you're still looking for a sponsor for HDFS, I'd be happy to help.

**Comment by ilyam8** [comment]
Hi @killerwhile, this is very nice you are willing to help :+1: 

[I see](https://www.datadoghq.com/blog/monitor-hadoop-metrics/#hdfs-metrics) there are 2 types of nodes:
 - NameNode
 - DataNode

And there are two types of metrics for the nodes:
 - jvm metrics
 - *-emitted metrics

It is clear how to collect jvm metrics - we need to enable remote JVM agent and gather metrics from it.
What about non jvm metrics? Do we need to read some files?

**Comment by killerwhile** [comment]
You're right about the components Namenode, Datanodes. Depending on the deployment model (HA for instance), you might have more. The exhaustive list of daemons running is given below:

- Namenode
- Secondarynamenode (when running non HA)
- ZKFailoverController (HA)
- Journalnode (HA)
- Datanode

All of them now expose metrics via a rest api (`/jmx`, I _think_ via Jolokia). Format is as follow:

```
{
  "beans" : [ {
    "name" : "Hadoop:service=NameNode,name=JvmMetrics",
    "modelerType" : "JvmMetrics"
    "MemNonHeapUsedM" : 65.67851,
    "MemNonHeapCommittedM" : 67.3125,
    "MemNonHeapMaxM" : -1.0,
    "MemHeapUsedM" : 154.46341,
    "MemHeapCommittedM" : 215.0,
    "MemHeapMaxM" : 843.0,
    "MemMaxM" : 843.0,
    "GcCount" : 15,
    "GcTimeMillis" : 305,
    "GcNumWarnThresholdExceeded" : 0,
    "GcNumInfoThresholdExceeded" : 0,
    "GcTotalExtraSleepTime" : 92,
    "ThreadsNew" : 0,
    "ThreadsRunnable" : 6,
    "ThreadsBlocked" : 0,
    "ThreadsWaiting" : 7,
    "ThreadsTimedWaiting" : 34,
    "ThreadsTerminated" : 0,
    "LogFatal" : 0,
    "LogError" : 0,
    "LogWarn" : 2,
    "LogInfo" : 348
  }, 
  { ... }
  ]
}
```

The `*-emitted` metrics are also present in the `/jmx` endpoint (see below). Not sure why they call them like that, but they are aggregated value which are definitely meaningful for a global overview of HDFS.

```
{
    "name" : "Hadoop:service=NameNode,name=FSNamesystem",
    "modelerType" : "FSNamesystem",
    "tag.Context" : "dfs",
    "tag.HAState" : "active",
    "tag.TotalSyncTimes" : "713 ",
    "tag.Hostname" : "dev-master-02.xxx.yyy",
    "MissingBlocks" : 0,
    "MissingReplOneBlocks" : 0,
    "ExpiredHeartbeats" : 0,
    "TransactionsSinceLastCheckpoint" : 1,
    "TransactionsSinceLastLogRoll" : 1,
    "LastWrittenTransactionId" : 84,
    "LastCheckpointTime" : 1565866098378,
    "CapacityTotal" : 161026609152,
    "CapacityTotalGB" : 150.0,
    "CapacityUsed" : 2293215232,
    "CapacityUsedGB" : 2.0,
    "CapacityRemaining" : 104107184128,
    "ProvidedCapacityTotal" : 0,
    "CapacityRemainingGB" : 97.0,
    "CapacityUsedNonDFS" : 54626209792,
    "TotalLoad" : 3,
    "SnapshottableDirectories" : 0,
    "Snapshots" : 0,
   ...
```

I think it's fair to start with the Namenode and Datanode and scrap `/jmx` http endpoint, i.e. no need of JMX.

**Comment by ilyam8** [comment]
> The *-emitted metrics are also present in the /jmx endpoint (see below).
> I think it's fair to start with the Namenode and Datanode and scrap /jmx http endpoint

Perfect!

I dont even need a lab, i can use your output ☺️ 	

Please share Namenode and Datanode `/jmx` output.

**Comment by ilyam8** [comment]
@killerwhile please^^

**Comment by killerwhile** [comment]
Sorry for the delay (some holidays :))

Here is the full listing of `/jmx` are provided in the attached [jmx.tar.gz](https://github.com/netdata/netdata/files/3540822/jmx.tar.gz)

Namenode is 

curl dev-slave-01.metis.zoo:9867/jmx | sed "s/metis.zoo/dev.local/g" > dev-slave-01.dev.local.jmx.json

**Comment by killerwhile** [comment]
Authorization can be performed using certificates and/or Kerberos.

**Comment by ilyam8** [comment]
hi @killerwhile 

Your samples were really useful, i was able to create the initial version of `hdfs` collector using them 😄 

> https://github.com/netdata/go.d.plugin/tree/master/modules/hdfs

But no doubts there is a lot of room for improvements.

Collected metris:

All metrics currently collected you can see there

> https://github.com/netdata/go.d.plugin/blob/master/modules/hdfs/metrics.go

For `datanode`:
 - [jvm](https://github.com/netdata/go.d.plugin/blob/97f9712ef307d029229e7993cec7cb2c78633af9/modules/hdfs/metrics.go#L20-L45)
 - [rpc activity](https://github.com/netdata/go.d.plugin/blob/97f9712ef307d029229e7993cec7cb2c78633af9/modules/hdfs/metrics.go#L47-L65)
 - [fs dataset state](https://github.com/netdata/go.d.plugin/blob/97f9712ef307d029229e7993cec7cb2c78633af9/modules/hdfs/metrics.go#L141-L158)
 - [data node activity](https://github.com/netdata/go.d.plugin/blob/97f9712ef307d029229e7993cec7cb2c78633af9/modules/hdfs/metrics.go#L160-L243)

For 'namenode':
 - [jvm](https://github.com/netdata/go.d.plugin/blob/97f9712ef307d029229e7993cec7cb2c78633af9/modules/hdfs/metrics.go#L20-L45)
 - [rpc activity](https://github.com/netdata/go.d.plugin/blob/97f9712ef307d029229e7993cec7cb2c78633af9/modules/hdfs/metrics.go#L47-L65)
 - [fs name system](https://github.com/netdata/go.d.plugin/blob/97f9712ef307d029229e7993cec7cb2c78633af9/modules/hdfs/metrics.go#L67-L139)

As you can see a lot of metrics are commented out there. Reason: i am not sure they are useful - not a specialist.

If you see we need to add some please suggest.

____

Alarms.

Please suggest some alarms too. My plan is to add alarms based on this article

> https://www.datadoghq.com/blog/monitor-hadoop-metrics/#hdfs-metrics

**Comment by ilyam8** [comment]
Oh, forgot about charts, here they are

> https://github.com/netdata/go.d.plugin/blob/master/modules/hdfs/charts.go

I am not 100% percent sure i did right grouping, so please to a look too @killerwhile 

Basically any suggestions are welcome

**Comment by joelhans** [comment]
Hey @killerwhile, I'd love to connect quickly to talk about your help with sponsoring this, and maybe learn more about how you'd use the HDFS/Zookeeper modules. Feel free to email me at joel@netdata.cloud if you'd like to.
