### ISSUE TITLE
pf monitoring

### ISSUE THREAD

**Issue by incognico** [netdata/netdata#4891]
I'm on FreeBSD and I don't use ipfw (which already is supported) but PF (https://www.openbsd.org/faq/pf/).

Adding support for PF would benefit OpenBSD, FreeBSD and pfSense (and many others).

For reference: https://github.com/munin-monitoring/contrib/tree/master/plugins/pf

Related: https://github.com/netdata/netdata/issues/3469#issuecomment-438843055

**Comment by cakrit** [comment]
Hi @incognico, to get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:

  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

Would you be willing/able to assume this role? 

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

@ilyam8 I didn't find this one mentioned in #4574, can you add it there?

**Comment by KGuillemot** [comment]
Hi everybody,
Is there any news concerning this PR ? It would very helpfull for us.
Thank you,
Kevin

**Comment by ilyam8** [comment]
Both munin and [telegraf](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/pf#pf-plugin) use [`pfctl`](url) to gather pf firewall statistics.

Furhtermore i see

> The pfstat command requires read access to the device file /dev/pf

___

Easy solutiuon is to write a python script that uses `pfctl`.
Hard mode is to study `pfctl` srouce code and write collector in c.
Or start with python script and replace it with c implementation later.

@vlvkobal what do you think?

**Comment by cakrit** [comment]
Let's just do a python module for this, not a c collector. @KGuillemot would you be willing to assume the 'sponsor' role for this one? See second comment.

**Comment by Zolotkey** [comment]
To help get the ball rolling...

1. Specify the metrics required and how they should be presented in charts.

Table Metrics-
* A chart for each table with the amount of ip's in the chart
* A chart for overall table-entries

Packet Metrics-
* how many  packets/bytes from each block/pass rule in a chart
* how many packets/bytes from each NAT/rdr rule in a chart

State Metrics- 
* A chart for how many pf states there are.
* A chart for how many pf fragmentations there are.

2. Specify the alarms that would make sense for each metric.

Table Metric - 
*  Each Table alarm would be customizable - Amount of table entries - not a necessity
* Overall Table-entries max is a hard limit so "needs attention" on 85%, "critical" at 95%.

Packet Metrics-
* Alarm on high packets/bytes over a certain threshold for each rule

 State Metrics- 
* Pf States and Fragments have a hard limit on them so warn when each level get to 90% of hard limit.

**Comment by ilyam8** [comment]
@Zolotkey 	thanks!

is `/sbin/pfctl -s info` enough to get all the metrics from your post?

**Comment by Zolotkey** [comment]
These were some of the flags I used in making my metrics ideas.
```
/sbin/pfctl -v -s rules
/sbin/pfctl -v -s nat
/sbin/pfctl -sm
```

```/sbin/pfctl -t <table> -T show``` then count the amount

**Comment by cakrit** [comment]
We need to plan this one.

**Comment by ilyam8** [comment]
Closing this feature request and moving it to [our community forum](https://community.netdata.cloud/) for further discussion (link will be posted soon).

**Comment by mailinglists35** [comment]
Hi, where is the link for discussion?
