### ISSUE TITLE
Docker netdata documentation

### ISSUE THREAD

**Issue by pgassmann** [netdata/netdata#4899]
- The [Readme on Dockerhub ](https://hub.docker.com/r/netdata/netdata/) does currently show general information about netdata and not much about the usage of the container image. 
- The [Wiki Page](https://github.com/netdata/netdata/wiki/Install-netdata-with-Docker
) contains a link that is no longer valid. 
- The correct link is now docs.netdata.cloud https://docs.netdata.cloud/packaging/docker/
- There is a README in the netdata/packaging/docker with good information on the usage of the docker image: https://github.com/netdata/netdata/tree/master/packaging/docker

@paulfantom Can the Information on Dockerhub be changed to show usage information for the docker image? Is this Readme added manually?

@paulfantom Can you add the information on how to specify additional parameters. 

- cli: append the desired options to the cli `docker run -d [...] netdata/netdata -i 192.168.1.1`. 
- docker-compose: `command: '-i 192.168.1.1'`

It would also be helpful to have a direct link from the docs to dockerhub. on https://docs.netdata.cloud/packaging/docker/ to https://hub.docker.com/r/netdata/netdata/

**Comment by cakrit** [comment]
> The Wiki Page contains a link that is no longer valid.
> The correct link is now docs.netdata.cloud docs.netdata.cloud/packaging/docker

Link fixed. 

Regarding additional info in the README, please go ahead and update it. We are more than happy to [get help with the documentation](
https://docs.netdata.cloud/contributing/#improve-documentation)
@paulfantom will review the changes for accuracy. 

So it's just the following that will remain:
> Can the Information on Dockerhub be changed to show usage information for the docker image? Is this Readme added manually?

**Comment by paulfantom** [comment]
Readme in docker hub is added manually and I will try to add sth to sync it via CI system with a file located at `packaging/docker/README.md`

**Comment by ktsaou** [comment]
@cakrit 	could you please take care of it? The README on docker hub, should docker related.

**Comment by paulfantom** [comment]
@pgassmann we are using `ENTRYPOINT` directive in our Dockerfile, so the way to add any parameters to netdata binary is to use `CMD`/command ( https://docs.docker.com/engine/reference/builder/#cmd ). We are not planning on duplicating documentation for how this method is implemented in various tools (docker cli/docker-compose/k8s manifests/other).

**Comment by cakrit** [comment]
I spoke with @paulfantom and I will do a PR to improve the docker documentation today. The automated update will come a bit later.

**Comment by cakrit** [comment]
#4914 updated the README, https://hub.docker.com/r/netdata/netdata/ is also updated. 
Thank you for your feedback @pgassmann
