### ISSUE TITLE
No data in charts

### ISSUE THREAD

**Issue by Noctune** [netdata/netdata#4920]
##### Bug report summary
All charts show "No data" and the log is flooded with errors of `PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)`. Restart/reboot does not seem to fix the problem and neither does clearing the cache or updating netdata to newest version (`1.11.1-85-gbd3cfad` as of writing).

##### OS / Environment
Debian 8.10

##### Component Name
netdata/proc

##### Steps To Reproduce
This has happened on a machine that hit the RAM limit and started killing processes. It might be due to an incomplete file being saved to disk. I suspected the cache, but clearing that does not seem to help. I would be grateful if anyone can suggest other files that might be corrupted and cause such an error.

##### Expected behavior
Charts with data.

**Comment by cakrit** [comment]
When you said, clearing the cache, do you mean the following?

```rm -rf /var/cache/netdata/*```

Can you try to do this in the netdata.conf [global] section?

```
    memory mode = save
```

Netdata by default is the first one to get killed when your server runs out of memory. See [OOM Score](https://docs.netdata.cloud/daemon/#oom-score)

**Comment by cakrit** [comment]
I should say that `memory mode = ram` should just be temporary, to ensure that it's data stored to disk that cause the issue. Then we can try doing the rm to clear the DB, comment the config line to get the default and try again. You obviously need to restart in each step.

**Comment by Noctune** [comment]
> When you said, clearing the cache, do you mean the following?
> 
> `rm -rf /var/cache/netdata/*`

Yes.

> 
> Can you try to do this in the netdata.conf [global] section?
> 
> ```
>     memory mode = ram
> ```
> 
> Netdata by default is the first one to get killed when your server runs out of memory. See [OOM Score](https://docs.netdata.cloud/daemon/#oom-score)

No change after restart it seems.

**Comment by cakrit** [comment]
Ok, based on the error message you sent, can you try disabling the proc plugin? 
```
[plugins]
proc = no
```
If that fixes it, then maybe check what's wrong with `/proc/schedstat`?

**Comment by Noctune** [comment]
It stops the log spam, but charts still do not work. It might be more the symptom of the problem than the problem itself.

The errors in the log seems to be mostly different plugins failing due to what they are monitoring not running (as expected), although the log is more manageable now: https://gist.github.com/Noctune/7e9610d5d4604ea6fef5823e48ef0491. I cannot spot any errors that might be related to this.

´/proc/schedstat´ does not seem to exist, but from what I can read it is only supposed to do so when scheduler statistics are enabled in the kernel.

**Comment by cakrit** [comment]
You're right, something is off. 
A couple of questions/notes from looking at the log and I'll try to get some more help:

- I see this: 
`sent email notification for: ENV-DEV-APP01 disk_space._home_flink.out_of_disk_space_time is CRITICAL to 'root'`
How bad is it with the disk space?

- I see that netdata it's still running with memory mode 'save' (5 line in the log). This means that netdata.conf doesn't have memory mode = ram. Perhaps you changed it back? 

- The last few lines with the heartbeat errors are why you're not getting any data in the charts. The question I don't know the answer to is why.

**Comment by Noctune** [comment]
>How bad is it with the disk space?

That is a new disk that has recently been added. It's not used for anything and should be empty, although I think a colleague was IO testing it at the time of the log. The main disk has plenty of space.

The addition of the disk coincides with Netdata not working anymore, so that could be the culprit somehow.

>I see that netdata it's still running with memory mode 'save' (5 line in the log). This means that netdata.conf doesn't have memory mode = ram. Perhaps you changed it back?

Yes, I changed it back. Changing it to ram and disabling proc yielded the same results.

>The last few lines with the heartbeat errors are why you're not getting any data in the charts. The question I don't know the answer to is why.

Okay. That is odd. Maybe something is broken in the OS. I will try `strace`ing to see if I can find a failing system call or something like that.

**Comment by Noctune** [comment]
The problem magically fixed itself. I unfortunately have no idea what is the cause and what fixed it, but I suspect that something hardware related changed (I am somewhat removed from the actual hardware of the machine). But thanks a lot for the help anyway!

**Comment by socomsystems** [comment]
@Noctune @cakrit are you sure it was a hardware issue?  I'm experiencing the exact same thing on on all of our Debian 8 Jesse vultr VMs.  My configs the following:

I'm setup in a headless slave scenario.  I purged all of my old netdata slave nodes and did fresh installs last night then began experiencing this.

netdata.conf
[global]
        memory mode = none
[web]
        mode = none

with
stream.conf
2018-12-20 12:55:29: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:30: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:31: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:32: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:33: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:34: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:35: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:36: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:37: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:38: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/schedstat' (errno 2, No such file or directory)
2018-12-20 12:55:39: netdata LOG FLOOD PROTECTION too many logs (201 logs in 125 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 1075 seconds.

**Comment by cakrit** [comment]
@socomsystems : Missing `proc/schedstat` and the required fix have been discussed in #4994. @vlvkobal will work on it soon.
