### ISSUE TITLE
Application log files monitoring

### ISSUE THREAD

**Issue by deep7710** [netdata/netdata#4921]
I have multiple log files being generated by my application. I want to monitor these log files for the occurrence of certain keywords. Is there a plugin to do this? I have tried few but only with limited success. I want to monitor multiple log files for various  keywords plus I want to use only one single plugin to achieve this!! need help urgently!!

**Comment by ilyam8** [comment]
Hi @deep7710 

https://github.com/netdata/netdata/pull/4900

**Comment by ilyam8** [comment]
duplicate of https://github.com/netdata/netdata/issues/3729
