### ISSUE TITLE
Use the new logo in the UI (#4913) ERROR

### ISSUE THREAD

**Issue by myopenflixr** [netdata/netdata#4925]
Hello,

After this update adding the new logo in th UI, I am getting a 404 error for the netdata-logomark.svg image. The image is not displayed.

I use a reverse proxy and everything else works great (and has for the past year).

It looks like the url to this image is www.mysite.com/images/netdata-logomark.svg whereas it should use the url of www.mysite.com/netdata/server1/images/netdata-logomark.svg.

I double checked my server and the image is present in the correct directory on my server.

Is this an issue with the index.html code or do I need to make an adjustment on my Nginx reverse proxy?

I'm running Ubuntu 16.04 and netdata is NOT installed via docker.

Thanks,
Mike

**Comment by ktsaou** [comment]
Hi,

It should be fixed with #4927 
Could you please update your netdata and confirm it is working now?
