### ISSUE TITLE
Move python collectors to go

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#4932]
Moving toward `go.d` right here :+1: 

[Corresponding project.](https://github.com/netdata/netdata/projects/27)

Important: this is not the "list to move".

Some of them should be moved, some of them not for some reason. Will see.

|  N  |   Python module  | Issue |
| --- | ---------------- | ----- |
| 1 | adaptec_raid |  | |
| 2 | apache | https://github.com/netdata/netdata/issues/5000 | |
| 3 | apache_cache |  | |
| 4 | beanstalk |  | |
| 5 | bind_rndc |  | |
| 6 | boinc |  | |
| 7 | ceph |  | |
| 8 | chrony |  | |
| 9 | couchdb |  | |
| 10 | dns_query_time | https://github.com/netdata/netdata/issues/5047 | |
| 11 | dnsdist |  | |
| 12 | dockerd |  | |
| 13 | dovecot |  | |
| 14 | elasticsearch |  | |
| 15 | exim |  | |
| 16 | fail2ban |  | |
| 17 | freeradius | https://github.com/netdata/netdata/issues/5063 | |
| 18 | go_expvar |  | |
| 19 | haproxy |  | |
| 20 | hddtemp |  | |
| 21 | httpcheck | https://github.com/netdata/netdata/issues/5004 | |
| 22 | icecast |  | |
| 23 | ipfs |  | |
| 24 | isc_dhcpd |  | |
| 25 | lighttpd | https://github.com/netdata/netdata/issues/5003 | |
| 26 | litespeed |  | |
| 27 | logind |  | |
| 28 | megacli |  | |
| 29 | memcached |  | |
| 30 | mongodb |  | |
| 31 | monit |  | |
| 32 | mysql |  | |
| 33 | nginx | https://github.com/netdata/netdata/issues/5001 | |
| 34 | nginx_plus |  | |
| 35 | nsd |  | |
| 36 | ntpd |  | |
| 37 | nvidia_smi |  | |
| 38 | openldap |  | |
| 39 | ovpn_status_log |  | |
| 40 | phpfpm |  | |
| 41 | portcheck | https://github.com/netdata/netdata/issues/5005 | |
| 42 | postfix |  | |
| 43 | postgres |  | |
| 44 | powerdns |  | |
| 45 | proxysql |  | |
| 46 | puppet |  | |
| 47 | rabbitmq | https://github.com/netdata/netdata/issues/5002 | |
| 48 | redis |  | |
| 49 | rethinkdbs |  | |
| 50 | retroshare |  | |
| 51 | samba |  | |
| 52 | sensors |  | |
| 53 | smartd_log |  | |
| 54 | spigotmc |  | |
| 55 | springboot |  | |
| 56 | squid |  | |
| 57 | squid_log |  | |
| 58 | tomcat |  | |
| 59 | tor |  | |
| 60 | traefik |  | |
| 61 | unbound |  | |
| 62 | uwsgi |  | |
| 63 | varnish |  | |
| 64 | w1sensor |  | |
| 65 | web_log | https://github.com/netdata/netdata/issues/5046 | |

**Comment by Ferroin** [comment]
Any of the modules that are doing log parsing seem to be prime candidates to be moved, though we should probably keep `LogService` around.  It's a lot easier to add a new Python module to a Netdata install than a new Go module (no compilation needed for Python, just write the module and drop it in), and `LogService` is still useful for people who want to do that.

**Comment by ilyam8** [comment]
`python.d.plugin` with all it's FrameworkServices are stay in place ofc!

**Comment by ilyam8** [comment]
main candidates:
 * modules that have external dependencies (to remove them)
 * modules that will benefit from utilizing several cpus, goroutines etc.

**Comment by ilyam8** [comment]
Closing this issue because it is stale, internally using google excel sheet to track it.
