### ISSUE TITLE
netdata server usage - stream statistics

### ISSUE THREAD

**Issue by gdelafond** [netdata/netdata#4934]
Hello,

On each netdata there is an information about its memory usage like : 
` netdata on XXXX, collects every second 1 801 metrics, presented as 260 charts and monitored by 0 alarms, using 297 MB of memory for 11 hours, 55 mins and 8 secs of real-time history.`

I do not find how to know the number of received stream and the total ram used by these streams. Is this information available somewhere ?

Regards,

**Comment by cakrit** [comment]
Well, it's not precisely what you're asking, but check [here](https://docs.netdata.cloud/database/). If by 'stream' you are referring to a hierarchical setup with a master node receiving metrics from slave nodes, you can see [here](https://docs.netdata.cloud/streaming/#options-for-the-receiving-node) a section in the configuration where you can change the history (entries stored) for each slave. 

Finally, you may want to also look at the general suggestions on [Performance](https://docs.netdata.cloud/docs/performance/), as disabling plugins you don't need also reduces the required memory.

**Comment by gdelafond** [comment]
@cakrit yes i'm referring to a hierarchical setup. I know there are information in the documentation, but here I have hundreds of server streaming to the master node. Every day this number is different, it is not very easy to know easily the node number and the RAM used by all the stream on the master node.

Maybe a graph in the "Netdata monitring/netdata" group could be added to monitor the number of stream received and the RAM used by these stream.

**Comment by cakrit** [comment]
This would be an interesting feature, for sure. The title is appropriate, "stream statistics" as we probably don't just want to show the RAM used. Adding it to the backlog.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
