### ISSUE TITLE
Info logging command in netdata-updater.sh contains command substitution.

### ISSUE THREAD

**Issue by crkochan** [netdata/netdata#4950]
##### Bug report summary
[Line 96 of the netdata-updater.sh script](https://github.com/netdata/netdata/blob/4648cf4707a3b59f674e179cc1fed1426c847399/installer/netdata-updater.sh#L96) contains a bash command substitution that is being interpreted during daily Cron runs.

https://github.com/netdata/netdata/blob/4648cf4707a3b59f674e179cc1fed1426c847399/installer/netdata-updater.sh#L96

Even though the line is calling an info level logging function, the use of the bash command substitution syntax of $() as well as being encapsulated in double quotes, causes bash to actually execute the `git stash pop` command in a sub-shell.

Since there’s (usually) no stash to pop, the command exits with a return code of 1, and Cron sends an email every day. 

##### OS / Environment
```
# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
##### Component Name
netdata-installer.sh

##### Steps To Reproduce
Run netdata-installer.sh manually, or allow the daily Cron job to execute.

##### Expected behavior
Run of netdata-installer.sh should not output `No stash found.`, and no email should be sent on an otherwise successful updater run.

**Comment by cakrit** [comment]
Thanks @crkochan the mind is trained to ignore debug statements.
@paulfantom please look into this.

**Comment by paulfantom** [comment]
Nice catch!
