### ISSUE TITLE
Docker-compose: a lot of errors; Connection refused, Can't establish connection to MySQL...

### ISSUE THREAD

**Issue by hkyq** [netdata/netdata#4956]
##### Bug report summary
My Netdata container recently stopped working. I can't access the web interface, I'm getting a lot of errors in the [docker log](https://gist.github.com/hkyq/513f08019786037770c5ab45f9c2f4b6).

##### OS / Environment
Ubuntu Server 18.04 LTS. Ran in Docker. [Here](https://gist.github.com/hkyq/158fa7143ef324359194e513f1597be1) is my docker-compose.yml. I am also using Traefik. 

##### Steps To Reproduce
Use my [docker-compose.yml](https://gist.github.com/hkyq/158fa7143ef324359194e513f1597be1) and do `docker-compose up -d` make sure to create the network `proxy` first. 

Has anyone used netdata with docker-compose & traefik? Could you share your configs?
Thanks

**Comment by ilyam8** [comment]
@hkyq was it fixed somehow?

**Comment by hkyq** [comment]
No but I can't troubleshoot this currently. Will reopen when I can.
