### ISSUE TITLE
support filtering disk naming by id

### ISSUE THREAD

**Issue by nakermann1973** [netdata/netdata#4957]
Following https://github.com/netdata/netdata/pull/3084 and https://github.com/netdata/netdata/issues/3081, I have set

```
[plugin:proc:/proc/diskstats]                                                   
  name disks by id = yes
```

This has the effect of setting my disk names to names which look like

`wwn-0x5000c5xxxxxxxxxx`

instead of (what I would prefer)

`ata-CT250MX500SSD1_xxxxxxxxxx` or `md-name-any:PV1`

Can a prefix filter be added to the `name disks by id` option to filter for the desired name format?

**Comment by nakermann1973** [comment]
My current workaround for this is to create a udev rule which populates a `/dev/disk/by-filtered-id` directory.  This contains only the names I would ike, and then set `path to /dev/disk/by-id = /dev/disk/by-filtered-id` in `netdata.conf`

**Comment by cakrit** [comment]
@mfundul can you help with this? I believe there's a feature request in this one, we just need to describe it properly.

**Comment by mfundul** [comment]
@cakrit sure. @nakermann1973 can you please post the udev rule code you used as reference? We must be careful how we do this cause depending on distribution or kernel version some kinds of devices may not be available at the `/dev/disk/by-id`. Maybe some kind of fallback priority based on available naming options?

**Comment by vlvkobal** [comment]
@nakermann1973 please test #5779
