### ISSUE TITLE
Mysql sys schema monitoring

### ISSUE THREAD

**Issue by deep7710** [netdata/netdata#4967]
I want to monitor my mysql DB with Netdata. Doing so, i want Netdata to display the time consuming queries in my database. By default, the mysql plugin does not provide this feature. is there a way by which I can get the list of time consuming queries in database on Netdata

**Comment by cakrit** [comment]
It's not currently supported. It would probably need to be a new plugin, configurable to monitor the [sys schema](https://github.com/mysql/mysql-sys) on servers that support it. @ilyam8 I think we should add it to the list in #4574 

@deep7710, to get started, we need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.

He/she will assist us with the following:
  - Specify the metrics required and how they should be presented in charts.
  - Specify the alarms that would make sense for each metric.
  - When the implementation passes QA, test the implementation in production.
  - Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

Would you be willing/able to play this role?

We would also appreciate getting votes :+1: for this issue from the community, to understand the interest in the particular collector.

**Comment by deep7710** [comment]
hi @cakrit 

I am willing to act as  sponsor for this new plugin

1) metrics required and how they should be presented in charts?

-->i want netdata to display the the top time consuming queries in my mysql. these can be presented in a tabular manner.
-->i want netdata to display the mysql query latency band.

2)alarms that would make sense for each metric.

--> we can discuss this as we start working on this plugin.

3)When the implementation passes QA, test the implementation in production.

--> yes, will test the implementation in production.

4)Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.
--> yes, will share regular feedback to improve it.

I would like to have a mysql db monitoring plugin similar to Vivdcortex which  can match upto the vivdcortex and give useful insight into our databases.

some screenshots from vivdcortex which can give some insight:

![image](https://user-images.githubusercontent.com/34769411/49803000-9903d900-fd74-11e8-8ef3-e3b134909362.png)
![image](https://user-images.githubusercontent.com/34769411/49803018a8832200-fd74-11e8-965a-a0178abeabdd.png)
![image](https://user-images.githubusercontent.com/34769411/49803035-b3d64d80-fd74-11e8-9d29-359024960a00.png)

**Comment by deep7710** [comment]
hi @cakrit 

any update on this

**Comment by ilyam8** [comment]
> i want netdata to display the the top time consuming queries in my mysql. these can be presented in a tabular manner.

This can be a problem.

**Comment by cakrit** [comment]
The need for a "table chart" was also indicated at #3086. Without something like that, the best we could do is something similar to what the apps.plugin does with the "Applications". There are [many views](https://dev.mysql.com/doc/refman/5.7/en/sys-schema-views.html) that have the data ready for us, the particular one could perhaps be retrieved from [this one](https://dev.mysql.com/doc/refman/5.7/en/sys-statements-with-runtimes-in-95th-percentile.html). 

What I don't know is if and how an entire query could be used as a dimension name, or if there's any other way to identify the query. We may have various limitations e.g. on permitted characters, max length etc. A couple of the views I saw indicate that there's not necessarily a more convenient query identifier we could use. 

What do you think @deep7710 ?

**Comment by kataras** [comment]
Hello @deep7710, the command below shows you 5 wait times of 5 queries:

![thisor](https://user-images.githubusercontent.com/22900943/51257486-6327c500-19b0-11e9-932f-587b1703e2a4.png)

As @cakrit said, we don't have a "table chart" at the moment. 

Therfore the next best thing we could do is to convert the "slow" executed queries into a meanful metric based on a configurable  field which will set what "slow" means, an "x" time; seconds/millseconds etc.

Beside that, could you please provide us the exact metrics you need from netdata to expose? Anything that could help us embrace your feature request, thank you a lot!

**Comment by cakrit** [comment]
We re-implemented the mysql plugin in go and we have the ability to pull out information from the sys schema, but we won't be able to show the slow queries themselves until we implement a `table` functionality as mentioned above. @deep7710 we would appreciate additional feedback so we can proceed with more metrics from the sys schema in new PRs.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
