### ISSUE TITLE
How to implement a custom node.js plugin?

### ISSUE THREAD

**Issue by dangeloandrea14** [netdata/netdata#4971]
I know, there's plenty of documentation and this is a stupid question, but we've been trying to implement a custom node.js plugin for two days now, and we just can't do it. NetData recognizes our plugin, but it just shows "no data" or "0".
We just need to send randomized numbers to NetData every 2-3 seconds with a node.js plugin. We've read countless plugin examples but we just can't get it to work.
What part of the plugin should we edit? What's the simplest way to send numbers to NetData?
 
Any help would be appreciated.

**Comment by cakrit** [comment]
Hi @dangeloandrea14 ,

Please try running your module [in debug mode](https://docs.netdata.cloud/collectors/node.d.plugin/#debugging-modules-written-for-nodedplugin) and put here what you get. 
Also, show what you've done this far. You can look at #4939 for a similar debugging we did recently.
