### ISSUE TITLE
Issue creating deb package from v1.11.1

### ISSUE THREAD

**Issue by leonallen22** [netdata/netdata#4979]
##### Bug report summary
Seeing the following when attempting to build a .deb from release v1.11.1:
make[1]: Entering directory `/home/ubuntu/netdata-1.11.1_rolling'
dh_installdocs
cp: cannot stat ‘CHANGELOG.md’: No such file or directory
dh_installdocs: cp -a CHANGELOG.md debian/netdata/usr/share/doc/netdata returned exit code 1

##### OS / Environment
Ubuntu 18.04/14.04

##### Steps To Reproduce
- Download https://github.com/netdata/netdata/releases/download/v1.11.1/netdata-v1.11.1.tar.gz
- Decompress
- cd into directory & follow https://github.com/netdata/netdata/tree/v1.11.1/contrib

##### Expected behavior
.deb file is created

**Comment by leonallen22** [comment]
On 18.04 it seems to successfully create the .deb anyways. On 14.04 it fails out

**Comment by leonallen22** [comment]
While poking around, this commit seemed possibly relevant, but not familiar enough with this project to know for sure: https://github.com/netdata/netdata/commit/cc786edf34427a435291a35ff8bc348a3ee294bb

**Comment by paulkatsoulakis** [comment]
I have a feeling that this commit 7be1cc5243a6fd3e4f95663b34c29f4f37123654 that introduces changelog file in the make dist tarball, should solve this issue. I faced a similar problem with missing the changelog while preparing the debian configuration for my binary release version.

I am closing this and you can keep track of the delivery of this small change through #5963 

any other inputs, comments or hints around Debian packaging are most welcome within #5963, please do not hesitate to share any knowledge that you consider will help us deliver to our customers the best possible value!

See ya and thanks for reporting the issue, you rock!
