### ISSUE TITLE
metrics data model - add tags to charts

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#4986]
##### Feature idea summary
Current metrics data model only support 2 layers.
It's hard to work with some complex metrics.
For example, nginx-vts report upstreams info like this:
```yml
upstreamZones:
  backend1:
  - server: server1.com
    requestCounter: 10
    inBytes: 20
    outBytes: 30
    responses:
      1xx: 40
      2xx: 50
      3xx: 60
      4xx: 70
      5xx: 80
  - server: server2.com
    requestCounter: 100
    inBytes: 200
    outBytes: 300
    responses:
      1xx: 400
      2xx: 500
      3xx: 600
      4xx: 700
      5xx: 800
```
the prometheus can easily report these metrics like this:
```
nginx_vts_upstream_request{upstream="backend1", server="server1.com"} 10
nginx_vts_upstream_request{upstream="backend1", server="server2.com"} 100
...
nginx_vts_upstream_response{upstream="backend1", server="server1.com", code="1xx"} 40
nginx_vts_upstream_response{upstream="backend1", server="server1.com", code="2xx"} 50
nginx_vts_upstream_response{upstream="backend1", server="server1.com", code="3xx"} 60
nginx_vts_upstream_response{upstream="backend1", server="server1.com", code="4xx"} 70
...
```

but netdata's data model can't do such deep hierarchy.
```
nginx_vts_upstream_request_average{chart="nginx_vts_local.upstream_backend1_request", family="upstream_backend1", dimension="server1.com"} 10
nginx_vts_upstream_request_average{chart="nginx_vts_local.upstream_backend1_request", family="upstream_backend1", dimension="server2.com"} 100
...
nginx_vts_upstream_response_average{chart="nginx_vts_local.upstream_backend1_server1_com_response", family="upstream_backend1_server1.com", dimension="1xx"} 40
nginx_vts_upstream_response_average{chart="nginx_vts_local.upstream_backend1_server1_com_response", family="upstream_backend1_server1.com", dimension="2xx"} 50
...
```

It's hard to create charts for netdata and custom dashboards for backend.

##### Expected behavior

I suggest change the metrics data model to multi dimension model in the next major release (netdata 2.x.x)

**Comment by cakrit** [comment]
The need to add tags to charts and have alarms read those tags has been brought up a few times already and is in our roadmap. I linked this one to #809 and slightly changed the title. We will use this issue to do the implementation, so I'm also adding here links to other issues where the same issue was brought up:
https://github.com/netdata/netdata/issues/1231#issuecomment-267164281, #3813

**Comment by ilyam8** [comment]
2 level dashboard hierarchy is a **very** annoying limitation

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
