### ISSUE TITLE
mdstat module causing netdata segv and crash

### ISSUE THREAD

**Issue by myopenflixr** [netdata/netdata#4990]
Hello,

I have been using Netdata for quite some time. I have it installed on my main server along with several VM's and have had no issues.

Everything was working just fine yesterday...but today, the netdata installation on my main server is not working at all. I've searched through the issues and cannot figure out what is wrong. All other installations of netdata on my VM's seem to be working just fine.

I went as far as running the uninstall script to install a FRESH copy of netata on my main server and am experiencing the same problem.

Here is the output of: sudo service netdata status:

● netdata.service - Real time performance monitoring
   Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Fri 2018-12-14 12:08:15 EST; 23s ago
  Process: 1587 ExecStart=/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep (code=killed, signal=SEGV)
  Process: 1583 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 1578 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 1574 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 1569 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 1587 (code=killed, signal=SEGV)

Dec 14 12:08:15 mainserver systemd[1]: netdata.service: Unit entered failed state.
Dec 14 12:08:15 mainserver systemd[1]: netdata.service: Failed with result 'signal'.

My server and all VM's run Ubuntu 16.04 server.

I am not a linux expert, so if you need any additional information from me to troubleshoot, please be specific on any commands that you need me to run.

Thanks,
Mike

**Comment by myopenflixr** [comment]
Hello,

I checked my system logs and found this....This is repeated over and over in my logs. I issued sudo service netdata stop to keep my logs from filling up until we can resolve this issue.

Dec 14 12:38:12 mainserver systemd[1]: Starting Real time performance monitoring...
Dec 14 12:38:12 mainserver systemd[1]: Started Real time performance monitoring.
Dec 14 12:38:13 mainserver kernel: [ 5542.617531] netdata[14335]: segfault at 159 ip 000000000045297e sp 00007f456aa7c590 error 4 in netdata[400000+ca000]
Dec 14 12:38:13 mainserver systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
Dec 14 12:38:13 mainserver systemd[1]: netdata.service: Unit entered failed state.
Dec 14 12:38:13 mainserver systemd[1]: netdata.service: Failed with result 'signal'.
Dec 14 12:38:31 mainserver systemd[1]: Stopped Real time performance monitoring.


Thanks,
Mike

**Comment by cakrit** [comment]
I just updated and I can't replicate it. Can you please show us `/var/log/netdata/error.log` from 12:38:11 onwards?

**Comment by Ferroin** [comment]
@myopenflixr Do you happen to know when the last time prior to this showing up that you updated and restarted Netdata was?  If we can figure out a probable time frame for when the bug itself got introduced, that would help us track ti down faster.

**Comment by myopenflixr** [comment]
Here's a copy of my error log.

[error.log](https://github.com/netdata/netdata/files/2681201/error.log)

**Comment by myopenflixr** [comment]
@Ferroin I forget what log I saw earlier when I was troubleshooting, but I "think" the issue occurred during the middle of the night randomly around 4:30am.

Prior to reporting **this** error, I completely uninstalled my previous installation of netdata using **./netdata-uninstaller.sh --force** and then installed a fresh copy using **bash <(curl -Ss https://my-netdata.io/kickstart.sh)**. I did not reboot the server between uninstall and re-install (if that matters).

**Comment by cakrit** [comment]
Please try this. In your netdata.conf, find the `[plugins]` section, and replace
`# proc = yes` with `proc = no`. Restart and let us know if it worked.

**Comment by myopenflixr** [comment]
So, this is strange....Here are the entire contents of my /etc/netdata/netdata.conf file

# netdata can generate its own config.
# Get it with:
#
# wget -O /etc/netdata/netdata.conf "http://localhost:19999/netdata.conf"
#
# or
#
# curl -s -o /etc/netdata/netdata.conf "http://localhost:19999/netdata.conf"
#

Where is the rest of the data that should be in the file?

**Comment by myopenflixr** [comment]
That worked!

So what's going on? Any idea?

**Comment by cakrit** [comment]
Yes, we've made some recent changes to these two. Let's try to break it again, so we know which one is causing the issue and then I'll ask you for some files. 
Change `/sys/class/power_supply` to `yes` and restart.

**Comment by myopenflixr** [comment]
I made the change and restarted netdata and it appears to still be working fine.

**Comment by cakrit** [comment]
Ok, then it's /proc/mdstat.

tar.gz everything you have there and send it please.

**Comment by cakrit** [comment]
@myopenflixr perhaps I wasn't clear. Can you please send us your /proc/mdstat file so we can replicate the issue and publish a fix?

**Comment by myopenflixr** [comment]
Here's the contents of my /proc/mdstat file.
[mdstat.txt](https://github.com/netdata/netdata/files/2681387/mdstat.txt)

**Comment by cakrit** [comment]
Thanks a lot. @vlvkobal will follow up from now on.

**Comment by vlvkobal** [comment]
@myopenflixr @sanjiyan, could you please update your netdata and confirm if the issue is resolved?

**Comment by myopenflixr** [comment]
Hi @vlvkobal, I have updated netdata to the latest commit and can confirm that everything works as expected. Thanks everyone for the quick resolution!

**Comment by sanjiyan** [comment]
Hi,

I have updated Netdata and it has resolved. 

My raid0 array is also shown as md0

Thanks.
