### ISSUE TITLE
Percentile/median instead of max/mean in web_log timing graphs

### ISSUE THREAD

**Issue by spinitron** [netdata/netdata#4996]
Occasional connections of long duration to the web server squash the graphs down. Even the arithmetic mean (second graph below) without the max isn't much use when there are big outliers.

It's not just a matter of outliers making for boring graphs. Percentiles (99, 95) and median make good sense as performance metrics. New Relic does a good job at this (which they should at those prices!).

![Alt text](https://monosnap.com/image/F0XJ8XYf6G09g73yNKeE1ODXY2olth.png)

**Comment by ilyam8** [comment]
Hi @spinitron (sorry fo the huge delay 😅)

> Percentile/median instead of max/mean in web_log timing graphs

I think we need them in addition, not instead.

>  New Relic does a good job at this

Could you tell us what they od?

**Comment by tom--** [comment]
What New Relic does in general is described on their web site. But I was just mentioning that they do a good job of presenting descriptive statistics in a time series. Do these images give you an idea what I mean?

https://www.google.com/search?q=new+relic+percentile&source=lnms&tbm=isch

**Comment by ilyam8** [comment]
Well, yes. btw `weblog` has something similar (but very basic)

https://github.com/netdata/go.d.plugin/blob/55267854e91e83765f34e27a833d58c578e4cd1e/config/go.d/web_log.conf#L98-L101

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
