### ISSUE TITLE
See X process on graph on a server.

### ISSUE THREAD

**Issue by imperialsun** [netdata/netdata#4997]
Hi everybody. 

To start I wanna thank you for the great work creating this wonderfull monitoring app ;) .

Now for my question : 

Server is running last debian distribution and netdata was installed using your all-in script. 

Running your app on a Selenium server ( the selenium server run on different docker container ), I see some X process on cpu chart : 

![image](https://user-images.githubusercontent.com/17067781/50046640-ac7daf80-00a6-11e9-9f58-05722f83f0f8.png)

Using htop or ps I see process like this :+1: 

![image](https://user-images.githubusercontent.com/17067781/50046653-f23a7800-00a6-11e9-9a87-57b98efbddf4.png)

So here my list off questions :

- Why the process is maked 'X' and not like the htop command.

- Why all the process is merged onto 'X' ?

Thanks for you'r time reading this.

Keep up the good work

:1st_place_medal:

**Comment by ilyam8** [comment]
Hi @imperialsun 

That chart from the `apps.plugin`

`apps.plugin` [configuration file](https://github.com/netdata/netdata/blob/master/collectors/apps.plugin/apps_groups.conf) - have a look

https://github.com/netdata/netdata/blob/493b0dd36c6e25aa4daae95df6c324c89239b0b8/collectors/apps.plugin/apps_groups.conf#L254-L261

**Comment by imperialsun** [comment]
Thanks a lot I know where to find it myself next time.
