### ISSUE TITLE
no any conf file in  /etc/netdata/python.d 

### ISSUE THREAD

**Issue by WilliamsonJack** [netdata/netdata#5013]
##### Question summary
when i  install netdata by netdata-installer.sh, they have no conf file in /etc/netdata/python.d
##### OS / Environment
debian 8.x
##### Component Name
i need nginx.conf

**Comment by paulfantom** [comment]
Yes, that is a correct behavior. All default config files are stored in `/usr/lib/netdata/conf.d`. Those files are meant to be overwritten by new installation during upgrade. To use your own config you can either copy configuration file which is interesting to you from `/usr/lib/netdata/conf.d` to `/etc/netdata` or use our tool located in `/etc/netdata/edit-config`

**Comment by cakrit** [comment]
You can read more about it [here](https://docs.netdata.cloud/docs/configuration-guide/)

**Comment by WilliamsonJack** [comment]
thanks
