### ISSUE TITLE
net_drops.WAN High?

### ISSUE THREAD

**Issue by scurtis94** [netdata/netdata#5025]
So this is what i am seeing for net_drops on my WAN interface for my router. Is this abnormally high?

![image](https://user-images.githubusercontent.com/45956466/50129172-d3261c80-0245-11e9-9541-07d184198495.png)

Thanks!

**Comment by cakrit** [comment]
This is interesting, it's almost identical to what I get on my laptop at home, only my pattern is even more regular. I know it has nothing to do with the softnet backlog and was thinking it's probably my 3-play provider broadcasting something for my set-top box to hear. I didn't go as far as tracing the interface to inspect the packets, but I know it doesn't affect anything on my system.

**Comment by scurtis94** [comment]
I can't exactly tell if it's affecting anything on my system, because I have been having some minor issues. However, if I looked at that chart and had to guess, I would expect some big problems. 

For example, I've been noticing some issues where it feels like I'm dropping packets, but none of the interfaces indicate that is occurring

**Comment by cakrit** [comment]
`WLAN` is supposed to be the name of your interface. What do you see in `netstat -i`?
