### ISSUE TITLE
Netdata Restart

### ISSUE THREAD

**Issue by alivxlive** [netdata/netdata#5035]
From time to time netdata restarted without any reason.
Restart time:  Date:        Wed, 19 Dec 2018 06:25:50

syslog:
```
Dec 19 06:25:49 localhost systemd[1]: Reloading.
Dec 19 06:25:49 localhost systemd[1]: Reloading.
Dec 19 06:25:49 localhost systemd[1]: Stopping Real time performance monitoring...
Dec 19 06:25:50 localhost monit[2044]: 'netdata-ali-1' failed protocol test [DEFAULT] at [10.0.1.112]:19999 [TCP/IP] -- Connection refused
Dec 19 06:25:50 localhost monit[2044]: 'netdata-ali-1' failed protocol test [DEFAULT] at [127.0.0.1]:8125 [TCP/IP] -- Connection refused
Dec 19 06:25:50 localhost systemd[1]: Stopped Real time performance monitoring.
Dec 19 06:25:50 localhost systemd[1]: Starting Real time performance monitoring...
Dec 19 06:25:50 localhost systemd[1]: Started Real time performance monitoring.
Dec 19 06:26:20 localhost monit[2044]: 'netdata-ali-1' cpu usage of 100.0% matches resource limit [cpu usage > 90.0%]
Dec 19 06:26:20 localhost monit[2044]: 'netdata-ali-1' cpu usage of 100.0% matches resource limit [cpu usage > 95.0%]
Dec 19 06:26:20 localhost monit[2044]: 'netdata-ali-1' connection succeeded to [10.0.1.112]:19999 [TCP/IP]
Dec 19 06:26:20 localhost monit[2044]: 'netdata-ali-1' connection succeeded to [127.0.0.1]:8125 [TCP/IP]
Dec 19 06:27:31 localhost systemd-timesyncd[533]: Network configuration changed, trying to establish connection.
Dec 19 06:27:31 localhost systemd[1]: Started ntp-systemd-netif.service.
Dec 19 06:27:31 localhost systemd-timesyncd[533]: Synchronized to time server 10.0.0.2:123 (ntp.ubuntu.com).
Dec 19 06:46:41 localhost systemd[1]: Created slice User Slice of ubuntu.
Dec 19 06:46:41 localhost systemd[1]: Starting User Manager for UID 1000...
Dec 19 06:46:41 localhost systemd[1]: Started Session 264 of user ubuntu.
Dec 19 06:46:41 localhost systemd[12199]: Listening on GnuPG network certificate management daemon.
Dec 19 06:46:41 localhost systemd[12199]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Dec 19 06:46:41 localhost systemd[12199]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Dec 19 06:46:41 localhost systemd[12199]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Dec 19 06:46:41 localhost systemd[12199]: Reached target Timers.
Dec 19 06:46:41 localhost systemd[12199]: Listening on GnuPG cryptographic agent and passphrase cache.
Dec 19 06:46:41 localhost systemd[12199]: Reached target Sockets.
Dec 19 06:46:41 localhost systemd[12199]: Reached target Paths.
Dec 19 06:46:41 localhost systemd[12199]: Reached target Basic System.
Dec 19 06:46:41 localhost systemd[1]: Started User Manager for UID 1000.
Dec 19 06:46:41 localhost systemd[12199]: Reached target Default.
Dec 19 06:46:41 localhost systemd[12199]: Startup finished in 19ms.
~
```

##### OS / Environment
OS: Ubuntu 18.04.1 LTS
Netdata version: 1.12.0-rc0-64-g8c09913c
##### Component Name
netdata master.

**Comment by paulfantom** [comment]
Looks like some external application is restarting netdata as systemd log contains a line saying that something wants to stop netdata:
> Dec 19 06:25:49 localhost systemd[1]: Stopping Real time performance monitoring...

**Comment by alivxlive** [comment]
mmm, I don't think that is the issue,
What I notice in the previous  period the following:
1. Sometimes there is a load in the server from netdata, (I don't know the  reason) 
Note for point 1:
I used the defaults setting so there is no extra setting.
Example
![selection_049](https://user-images.githubusercontent.com/9927237/50575284-cd633600-0e04-11e9-90bf-5afee375ca8d.png)

**Comment by cakrit** [comment]
In the first export you sent, I see something the following abnormality. Not sure what the 'kernel' could have been doing at that time with 54 processes and 60 threads, but it happened right before your issue: 

![screenshot from 2019-01-03 13-06-52](https://user-images.githubusercontent.com/43294513/50637183-41165780-0f59-11e9-8b55-c0db58aa7e1a.png)

In the second export, 'something' was done via ssh. What was executed is shown as 'other' so I'm not sure what it was, but again it wasn't netdata.

![screenshot from 2019-01-03 13-09-57](https://user-images.githubusercontent.com/43294513/50637191-44a9de80-0f59-11e9-9f73-adab9d7c96c8.png)

The netdata error log was clean, the "ERROR" messages you see there are normal.

**Comment by paulfantom** [comment]
@alivxlive load average is quite complex as it sums a few metrics into one (more on the topic: http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html). In your case load might be very high due to some kernel process doing a lot of disk I/O operations (copying files on slow storage etc.) Can you see if your load is still so high when netdata is off? This way we could debug if it is caused by netdata itself or if there is sth else causing it?

**Comment by alivxlive** [comment]
Thank you, I will try to turnoff netdata for testing as you said.
