### ISSUE TITLE
Monitoring RHEL 7 from Windows 7

### ISSUE THREAD

**Issue by Convicto** [netdata/netdata#5057]
Hey there, I will be quick:

I have to do a RHEL 7 (emulated in my Windows7 machine) project work for school about Netdata, one of the tasks is to "Test of service operation in Windows Connected client" im not exactly sure about what that means, I guess I should be able to view and display my RHEL 7 machine Netdata graphs on a browser from a different Windows machine (to basically remotely monitor my RHEL 7 machine from a different machine) perhaps using a local connection between my RHEL7 and my Windows 7?

Previously, we were studying basic "networking" for Linux, but sadly I have been missing some of those classes some im very lost.

so...can someone explain me how to "Test of service operation in Windows Connected client" please?

Thanks in advance!

PS: I have already installed Netdata on my RHEL 7 emulated machine, it is working perfectly.

**Comment by cakrit** [comment]
I think you'll be better off asking a few of your classmates about what is required. It sounds like you'll have various Windows machines connected as clients to a server you'll be running on your RHEL 7 and you're asked to use netdata to show something about those connections.
