### ISSUE TITLE
CSV or xlsl export

### ISSUE THREAD

**Issue by nemke43** [netdata/netdata#5058]
Hey guys,
Is there any way to export data from past X days? I need export format .csv or .xlsx

**Comment by cakrit** [comment]
It's possible to export data in CSV format, e.g. http://localhost:19999/api/v1/data?chart=system.io&format=csv

You can read more about it [here](
https://docs.netdata.cloud/web/api/queries/) and [here](https://docs.netdata.cloud/web/api/formatters/csv/). 

However, you need to call it once per chart and you will probably not have data for X days, unless if you [increase the default retention period](https://docs.netdata.cloud/docs/configuration-guide/#increase-the-metrics-retention-period). Be careful of the required memory though, read through the docs first.

**Comment by davidlmaldonado** [comment]
Is it possible to export data from a snapshot?

**Comment by cakrit** [comment]
> Is it possible to export data from a snapshot?

That's not possible right now, but it sounds like an interesting feature request, if you can explain the need. Please do it in a new issue though, this one should be left closed.
