### ISSUE TITLE
Network traffic/topology view in Netdata

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#5062]
With Netdata agents running on every host and all network information at its disposal, we should be able to build a network topology view of the entire infrastructure that's monitored by Netdata. 

Essentially agents will capture all outgoing and incoming traffic (HTTP, TCP etc) information off processes running on a given node and send to master which can manage a DAG of all interacting nodes in the cluster. It can keep track of request count, connectivity failures, error ratio etc as simple metrics. Nodes joining and leaving the topology can be auto discovered purely based on traffic activity/inactivity (configured period of time) being streamed from the agents.

Netflix [vizceral](https://github.com/Netflix/vizceral) can be used for visualization and presenting network traffic information. Clicking on a certain node in the view can take to Netdata dashboard of the specific host.

**Comment by gmosx** [comment]
> Essentially agents will capture all outgoing and incoming traffic (HTTP, TCP etc) information off processes running on a given node and send to master

Can elaborate some more on how this can be implemented?

**Comment by gamefundas** [comment]
The idea here was to do packet capture, using pcap or some unix libraries that sniff network traffic and then build relationship of all interactions between nodes where Netdata is running. The agent provides the ability to tap in to the network traffic information. Also standard port activity to external hosts outside of Netdata reach can be assumed to be "external" systems. 1521 activity is Oracle, 6379 is Redis and so on...

Skydive is another such project that does something like this but requires additional configuration and agents. Netdata agents are already out there and could do this quite easily since it has knowledge/discovery of other components running on hosts via plugins etc.

**Comment by gmosx** [comment]
Interesting idea. I think this was already suggested by @ktsaou at some point (or at least is on his mind...)

**Comment by gamefundas** [comment]
An example of what I was thinking can be viewed here
https://www.instana.com/media/Instana-Dependency-Map-Calls-Latency-Errors.gif

And also within a cloud infrastructure a lot of the services can be discovered by Netdata using the cloud provider's api and that information could be used to identify several other dependencies in the infrastructure. 

Operating inside an AWS VPC Netdata can discover all participating resources that are communicating with applications to build a service/topology map. Within AWS; VPC Flow logs, XRay tracing etc can provide information around who is talking to whom.

**Comment by cakrit** [comment]
## Network View

### Purpose

- Provide a map of the network of the organization to visualize the topology of a large system
- Visualize network issues: see flow of information, ingress/egress, see per service analysis in traffic between nodes. 
- The network view is primarily a a dependency tree. Shows what my node depends on. 
- A key point is how much  a service depends on some other service.

### Examples

Datadog has done some nice things for [Network Performance Monitoring](https://www.datadoghq.com/blog/network-performance-monitoring/). Dynatrace also has some neat graphs. 

### What data do we need

egress
- for each source ip, dest ip, dest port (eBPF), I gather how many connections, bytes sent, bytes received, retransmits, throughput (sent/received per sec)

ingress
- Try to also get this information for ingress. 
- TODO how we'll use the ingress.
- Future info: Perhaps learn from each nodes the IPs, distribute the IPs to all the other claimed knows and collect the details only for those "interesting IPs" at the same level of information. 
Allow people to configure the subnets of "interesting IPs"

### How often should it be updated

- As often as possible. What I see on that network view depends on the time range I'm looking at.

### How do we do it

- Use eBPF to collect the data. Many of open-source implementations available, including one from Datadog. 
- To build the chart, the browser will issue queries to retrieve from the agents the data within the timeframe shown on the node graph and the IPs they know they have on their various interfaces. After matching the data, it's a matter of using one of the widely available visualization tools for directed graphs.
- TODO: How do we handle load balancers to form the links?
- TODO: Think about floating IPs. 
- To identify the leaf nodes, we really need the ingress as well.

**Comment by cakrit** [comment]
We just discussed that we will need to be able to aggregate the metrics mentioned above for a given time period and be able to go to the past (e.g. see what connections we had

**Comment by gamefundas** [comment]
@cakrit stale network interactions can be managed via agent configuration as to what level of sensitivity the user wants to maintain about these connections. If its a ephemeral node that keeps changing too often they could configure it to a smaller value, few hours, but if its a host that potentially has a longer life span then someone can configure it to go stale only after few days of inactivity. Based on this the master can reap stale interactions to keep the topology quite up to date.

I know this one is on the Netdata roadmap, but any insight on this as to whether the feature is going to be Netdata cloud only? Unfortunately Netdata cloud is not an option for me due to security restrictions within the firm so a lot the recently rolled out features haven't proved to be beneficial for me :|

**Comment by cakrit** [comment]
> any insight on this as to whether the feature is going to be Netdata cloud only? 

We would like to have something on the FOSS Netdata UI to show a single agent's view if inbound/outbout connections/traffic etc., but info on the entire network from multiple nodes will only be available on the cloud.

> Unfortunately Netdata cloud is not an option for me due to security restrictions within the firm so a lot the recently rolled out features haven't proved to be beneficial for me :|

We will have an on-premise version available later in the year, but it's certain that the particular version won't be free forever for everyone. No more details on that at this point I'm afraid...

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
