### ISSUE TITLE
Where  I can get API for this Chart below 

### ISSUE THREAD

**Issue by rm4** [netdata/netdata#5066]
##### Question summary
![image](https://user-images.githubusercontent.com/17122961/50489014-f025d100-0a37-11e9-9b44-1a9b098fa96f.png)

Hi ,

I cannot found API for chart like image above. 
I has read a documentation netdata for API 
I has read a swagger editor for API documentation
But I cannot find the solution to get API spesific like  CPU in percent, used ram in percent, net inbound in percent, net outbound in percent, disk write in percent, and disk read in percent
Could you help me find the spesific API data for the chart image above  ... 

Thanks  ,

##### OS / Environment 
l
##### Component Name
API netdata chart

**Comment by cakrit** [comment]
Check out the documentation on [custom dashboards](https://docs.netdata.cloud/web/gui/custom/). You'll see many examples in it as well.
