### ISSUE TITLE
error.log: IPv6 not properly show in error messages

### ISSUE THREAD

**Issue by mkg20001** [netdata/netdata#5067]
##### Bug report summary

Quite frequently this line shows up in the error.log:
```
2018-12-27 21:21:02: netdata INFO  : WEB_SERVER[static4] : POLLFD: LISTENER: client slot 1 (fd 113) from 'fcXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:41282' is idle for more than 60 seconds - closing it. 
```

I think it should be `[fcXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX]:41282`

##### OS / Environment

Ubuntu 18.04 bionic amd64
netdata `1.12.0-rc1-9-g71ef837c`

##### Component Name

netdata core

##### Steps To Reproduce

- Visit netdata dashboard via ipv6
- Close tab
- Wait 60 seconds, line should appear

##### Expected behavior

- IP:PORT pair should be properly formatted as `[ip]:port` when address is ipv6

**Comment by vlvkobal** [comment]
While the usual IPv6 address representation in network resource identifiers is `[IPv6 address]:port`, in error messages, it is more convenient to have the form `<IPv6 address> port <port>` which was implemented in #5166.
