### ISSUE TITLE
decluttering index page

### ISSUE THREAD

**Issue by daniel-baumann** [netdata/netdata#5072]
Hi,

on the netdata default index.html page there are links to github, twitter and facebook as well as a rather large "netdata uses the following [...]" footer.

It would be nice if they could be moved to e.g. the help overlay thinggie to keep the index.html page slick.

Regards,
Daniel

**Comment by daniel-baumann** [comment]
I see that the footer has been decluttered already as of 1.11.1 (thanks!), the 'share' button things remain though.

**Comment by gmosx** [comment]
Hmm, I am not sure we should remove the social buttons. Maybe move them under the right-hand-side menu though? @ktsaou what do you think?

**Comment by daniel-baumann** [comment]
moving the social media buttons into the footer or the bottom of the menu sounds good.

the 'removal' was about the overly expressive 'third party components' which, as indicated above, has already been removed anyway in the current version.

**Comment by nodiscc** [comment]
I am also in favor of moving the "social" buttons (twitter, facebook) out of the dashboard menu at the top, to the "charts index" menu at the right (next to where netdata version information currently is)

**Comment by ilyam8** [comment]
This issue is fixed
