### ISSUE TITLE
SNMP - handle OID like  .1.3.6.1.4.1.13742.6.3.5.3.1.3.1.OUTLETID.1 with `multiply_range`

### ISSUE THREAD

**Issue by gdelafond** [netdata/netdata#5073]
##### Feature idea summary

I try to use the SNMP collector to get information from a PX3 Raritan PDU.

The current is available for outlet with the OID : .1.3.6.1.4.1.13742.6.3.5.3.1.3.1.OUTLETID.1
The voltage is available for outlet with the OID : .1.3.6.1.4.1.13742.6.3.5.3.1.3.1.OUTLETID.4

Mixing that with `multiply_range` does not work.

##### Expected behavior

Add an option to be able to add an OID part at the end of the OID when using `multiply_range`, maybe with a `subindex` option ? It could be then be used like:
```
                "pdu125.outletCurrent": {
                    "title": "Current for Outlet ",
		    "titleoid": ".1.3.6.1.4.1.13742.6.3.5.3.1.3.1.",
		    "family": "Amp",
                    "type": "line",
                    "priority": 1,
		    "units": "Amp",
		    "multiply_range": [ 1, 20 ],
                    "dimensions": {
                        "current": {
                            "oid": ".1.3.6.1.4.1.13742.6.5.4.3.1.4.1.",
                            "subindex": 1
                        }
		    }
                },
                "pdu125.outletVoltage": {
                    "title": "Voltage for Outlet ",
		    "titleoid": ".1.3.6.1.4.1.13742.6.3.5.3.1.3.1.",
		    "family": "Volt",
                    "type": "line",
                    "priority": 1,
		    "units": "Volts",
		    "multiply_range": [ 1, 20 ],
                    "dimensions": {
                        "voltage": {
                            "oid": ".1.3.6.1.4.1.13742.6.5.4.3.1.4.1.",
                            "subindex": 4
                        }
		    }
                },
```
=> will walk through : 
- .1.3.6.1.4.1.13742.6.3.5.3.1.3.1.1.1 to .1.3.6.1.4.1.13742.6.3.5.3.1.3.1.20.1
- .1.3.6.1.4.1.13742.6.3.5.3.1.3.1.1.4 to .1.3.6.1.4.1.13742.6.3.5.3.1.3.1.20.4

Patch may looks like: 
```
--- /tmp/snmp.node.js-orig	2018-10-30 18:18:38.131619799 +0100
+++ /tmp/snmp.node.js-patched	2018-10-30 18:17:39.776802321 +0100
@@ -459,7 +459,8 @@
                         var d = dim_keys[j];
 
                         chart.dimensions[d].oid += from.toString();
-
+                        if(typeof chart.dimensions[d].subindex !== 'undefined')
+			    chart.dimensions[d].oid += "." + chart.dimensions[d].subindex
                         if(typeof chart.dimensions[d].oidname !== 'undefined')
                             chart.dimensions[d].oidname += from.toString();
                     }
```

**Comment by cakrit** [comment]
Hi @gdelafond, it looks like this will work. Perhaps add a `.toString()` at the end of `chart.dimensions[d].subindex` just in case? 
Have you tested it with the PDU?
Can you add PR?

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
