### ISSUE TITLE
Old Monit metrics still remains in Netdata even after Netdata restarted

### ISSUE THREAD

**Issue by ossjet** [netdata/netdata#5074]
##### Bug report summary
Old Monit metrics still remains in Netdata even after Netdata restarted

##### OS / Environment
LXC2 container with Xenial:
```
# lsb_release -d
Description:    Ubuntu 16.04.1 LTS
```
##### Component Name
` monit.chart.py`
##### Steps To Reproduce
Problem was appeared when we updated php7.0 to php7.3. Then we updated **monit** configs to monitor new fpm version and changed its name to php73-fpm from php70-fpm:

```
root@old:~# monit summary -B | grep php
 php70-fpm                        OK                          Process

root@new:~# monit summary -B | grep php
 php73-fpm                        OK                          Process
```

After all, it seems Netdata was restarted after that but old php70-fpm metrics is still present in exported metrics (from master netdata):
```
...
netdata_monit_process_threads{chart="monit_local.processes_threads",family="applications",dimension="php70-fpm",instance="api-prod"} 1 1546031884899
netdata_monit_process_threads{chart="monit_local.processes_threads",family="applications",dimension="php73-fpm",instance="api-prod"} 1 1546031884899
netdata_monit_process_childrens{chart="monit_local.processes_childrens",family="applications",dimension="php70-fpm",instance="api-prod"} 12 1546031884899
netdata_monit_process_childrens{chart="monit_local.processes_childrens",family="applications",dimension="php73-fpm",instance="api-prod"} 61 1546031884899
netdata_monit_process_uptime{chart="monit_local.processes_uptime",family="applications",dimension="php70-fpm",instance="api-prod"} 1021 1546031884899
netdata_monit_process_uptime{chart="monit_local.processes_uptime",family="applications",dimension="php73-fpm",instance="api-prod"} 97382 1546031884899
netdata_monit_services{chart="monit_local.processes",family="applications",dimension="php70-fpm",instance="api-prod"} 0 1546031884898
netdata_monit_services{chart="monit_local.processes",family="applications",dimension="php73-fpm",instance="api-prod"} 1 1546031884898
...
```
As you can see. php70 and php73 shares the same metrics for some reason.

The same thing happens in the web interface:

![screenshot-20181229-002424](https://user-images.githubusercontent.com/31291056/50530662-e4f2a400-0b10-11e9-9bb5-12b07d240973.png)

We tried to restart it again and it takes no effect. Then we checked monit xml output and it gives correct info:

```
# curl -s localhost:2812/_status?format=xml | sed -r 's/(<\w)/\n\1/g' | grep php
<name>php73-fpm</name>
<path>/var/run/php/php7-fpm_api.sock</path>
<path>/var/run/php/php7.3-fpm.sock</path>
```

Only this helped with that:

1. Stopping Netdata
2. Cleaning out the `/var/cache/netdata`
3. Removing the file `/var/lib/netdata/registry/netdata.public.unique.id` (since it's slave netdata instance in the LXC container).
4. Starting Netdata
5. PROFIT

And it's strange, because this slave netdata works in this mode:

```
memory mode = none 
```

Also, we have some debug infomation from the plugin:

```
root@server/prod (20181229-0122-MSK):~# NETDATA_CONFIG_DIR=/etc/netdata /usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin monit debug 1 2>&1 | egrep 'php73-fpm'
2018-12-29 01:22:19: python.d DEBUG: monit: localhost: => found php73-fpm with type=3, status=0, monitoring=1
DIMENSION 'process_php73-fpm' 'php73-fpm' absolute 1 1 ''
SET 'process_php73-fpm' = 1
DIMENSION 'process_uptime_php73-fpm' 'php73-fpm' absolute 1 1 ''
SET 'process_uptime_php73-fpm' = 101226
DIMENSION 'process_children_php73-fpm' 'php73-fpm' absolute 1 1 ''
SET 'process_children_php73-fpm' = 61
^C
root@server/prod (20181229-0122-MSK):~# NETDATA_CONFIG_DIR=/etc/netdata /usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin monit debug 1 2>&1 | egrep 'php70-fpm'
^C
```
It seems the collector works just fine, but the host Netdata gives also php70-fpm metrics.

##### Expected behavior

We guess the master Netdata supposed to update the list of the metrics after restarting the slave. And since it used no database it does not have affect its cleaning.

---

Any ideas? Maybe did the trick removing `/var/lib/netdata/registry/netdata.public.unique.id`?

**Comment by cakrit** [comment]
I was a bit confused regarding where this was executed:
> Cleaning out the /var/cache/netdata

Since the client runs with memory mode none, the cache really doesn't matter there. I expect that if you check the UI of the client, you won't see php70 there, correct? 

I also expect that php70 will disappear if you clean out /var/cache/netdata on the master and restart. I assume that the mater is not running with memory mode none. 

Can you try and let us know?

We are aware of the issues with caching. The new DB format that will solve them is a top priority.

**Comment by cakrit** [comment]
The daemon has the capability to obsolete dimensions now, so @ilyam8 this is for the collectors to use.
