### ISSUE TITLE
How to upgrade from v1.9?

### ISSUE THREAD

**Issue by ras07** [netdata/netdata#5075]
What's the best way to upgrade from v1.9? I can't find any upgrade script or uninstaller. (I don't actually recall how I installed 1.9 in the first place.) Can I just run the one-line installer over the top of a 1.9 install? Should I delete anything first?

I'm running Ubuntu 18.04 in a VM.

**Comment by cakrit** [comment]
Before doing anything, I suggest you take a backup of any config files you have changed, just in case something goes wrong. If you're not sure of what you've changed, just back up everything under the following directories you'll see if you go to `http://yourhost:yourport/netdata.conf`

```
	# config directory = The user config directory, probably /etc/netdata
	# stock config directory = Probably /usr/lib/netdata/conf.d
```

Then, you should be able to tell if you installed it with apt, by running

```
sudo apt list --installed
```

If it's there, I'd say just uninstall it first with apt.  

Use the [one liner](https://docs.netdata.cloud/packaging/installer/#one-line-installation) to get the latest. 

Please let us know if you run into any issues. I did manage to mess up the installation in my Manjaro by using different installation methods and it was a bit difficult to clean up everything.

**Comment by ras07** [comment]
Thanks - I did have 1.9 installed with apt, so I uninstalled it, and installed with the one-liner. However now I get the error "xx.xx.xx.xx:19999 says ERROR 405: Cannot download charts index from server: http://xx.xx.xx.xx/api/v1.charts"

I've un-installed (with netdata-uninstall.sh) and re-installed several times. Oddly, when I re-install, it initially works fine, but when I reboot, it stops working and tosses the above error.

I've read a lot of 405-related questions in the Issues, but none seem to match my situation.

**Comment by cakrit** [comment]
I have seen this type of message when there's something wrong, but the browser has cached parts of the page. I think that if you were to do a Ctrl+R, you'd see a different message. 
I haven't figured out why yet, but after messing up my installations, I had to put the following in the '[global]' section of my configuration:
```
web files directory = /usr/share/netdata/web
```
For some reason, my netdata got the wrong web files directory, so it couldn't find the artifacts, when I started it a certain way (from inside my IDE). It did get the path correctly, when I started with a systemctl command. 

In your system the web directory may be in a different place, you can look at what http://yourhost/netdata.conf gives you for `web files directory` and add the `/web` after it. 

Please tell me if that works for you. Now I see I'm not the only one with the issue, I'll dig a bit further.

**Comment by ras07** [comment]
Something I did in my last uninstall/reinstall seems to have fixed things. After uninstalling I went through the whole filesystem looking for anything related to netdata, and deleted a number of things that were left over. Unfortunately I couldn't tell you what did it. But in any case I'm up and running. Thanks for your help!

**Comment by cakrit** [comment]
Happy you were able to resolve it.
