### ISSUE TITLE
I do not see mariadb in my desk

### ISSUE THREAD

**Issue by paweldesign** [netdata/netdata#5089]
good morning
what should I do to monitor mariadb too
thank you

**Comment by ilyam8** [comment]
Hi @paweldesign 

Mysql module [readme](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mysql) and [configuration file](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/mysql/mysql.conf) are good places to start
