### ISSUE TITLE
Support multiple config files for proper Configuration Management

### ISSUE THREAD

**Issue by daniel-baumann** [netdata/netdata#5090]
Hi,

current state of the art is for software that requires configuration files to implement a 'conf.d'-mechanism, both for sysadmin convenience and to make proper distribution packaging and configuration management via tools (ansible, puppet, etc.) possible.

For the main configuration file (/etc/netdata/netdata.conf) e.g. /etc/netdata/netdata.conf.d/*.conf (if existing) should be read as well. This concept can be expanded to any configuration file (also of the plugins etc.), but it's the most important for netdata.conf since this is basically always locally customized to contain certain settings.

Regards,
Daniel

**Comment by ilyam8** [comment]
Hi @daniel-baumann 

This is very nice request and 100% should be implemented.

It is part of https://github.com/netdata/netdata/issues/4731.  Let's discuss it in #4371

And I am closing this in favor of #4371

**Comment by cakrit** [comment]
The issue we're leaving open is #6432
