### ISSUE TITLE
Testimonials wanted

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#5094]
#### Summary

We are looking for testimonials from companies using netdata in production.

We are building a new web site for netdata and we would be honored to have your testimonials featured on it.

At the same time, we are looking for help shaping the future of netdata. I would love to have a video chat with users interested to exchange ideas.

To schedule a video chat, send me an email to `costa@netdata.cloud`, with the following:

1. name of your company
2. your name and your job title
3. a short description of your infrastructure (number of nodes, hosting providers you use, any other info you can disclose that could be useful to understand your needs)
4. what is the biggest monitoring challenge you face
5. what other monitoring solutions you use

Shortly after receiving this email, I will respond with the available slots to meet you online.

Thank you!

**Comment by Wqrld** [comment]
Would a video be required or would a textual testomonial also work?

**Comment by cakrit** [comment]
Hi @Wqrld. A video would be amazing, but text is just fine!
