### ISSUE TITLE
Slave mode "high" memory usage

### ISSUE THREAD

**Issue by dbainbridge** [netdata/netdata#5098]
##### Question summary
I followed the [instructions](https://docs.netdata.cloud/streaming/) on changing a netdata instance into slave mode but the master is still showing the slave using 19MiB of memory.  Netdata was installed via `bash <(curl -Ss https://my-netdata.io/kickstart.sh) `.  On the slave, web and memory mode was changed to `none`.
Why is the slave still using 19MiB of RAM?  

##### OS / Environment
Raspbian/RPi
##### Component Name
netdata process
##### Expected results
According to https://docs.netdata.cloud/streaming/ slave mode should only be using 5MiB of memory.  The `Real memory (RAM) used by applications` metric on master is showing the slave still using ~19MiB.  It did drop from ~25MiB when I switched the slave memory mode to none.

**Comment by cakrit** [comment]
I expect that the statement "It runs with… 5MB of RAM (yes, you read correct)" is either very old, or doesn't take into account some of the collectors which can optionally be disabled. We'll investigate and correct the statement.

**Comment by ilyam8** [comment]
Hi @dbainbridge 

I think `pythond.d.plugin` is the main memory consumer in your case.

Please do:
  * set `default_run` to `no` in `python.d.conf`
  * explicitly enable modules you need (`module_name: yes`)

Restart netdata.service on slave, check memory usage. This should help.

**Comment by ilyam8** [comment]
Ok, it seems i was wrong :cry:, it only makes sense for `python.d.plugin` process (but still it save a lot of memory!), nvm

**Comment by cakrit** [comment]
Bare netdata deamon uses 5 MiB
The plugins that I could check (i.e. have the prerequisites for) in a Fedora VM add the following on top:

| Plugin | Memory (MiB)
| ---- | ----
| proc plugin<br>_[Disabling individual proc plugins](https://docs.netdata.cloud/docs/performance/#2-disable-internal-plugins) reduces it, e.g. disabling snmp/snmp6 saves about 1.5 MiB_ | 9
| diskspace | 0.4
| cgroups | 1.2
| python <br>_Depends on what's monitored_ | 20+ 
| apps | 16

So in your case @dbainbridge, you can reduce it by selectively disabling the proc plugins you don't need. 

I will update the documentation.

**Comment by dbainbridge** [comment]
Thanks @cakrit.  I figured it was documentation issue.  Thanks for clarifying and correcting the docs!
