### ISSUE TITLE
Systemd now has IPAccounting feature

### ISSUE THREAD

**Issue by psychomelet** [netdata/netdata#5103]
##### Feature idea summary
Systemd now has IPAccounting feature, consider add support for it.

**Comment by vlvkobal** [comment]
How is it supposed to be collected and what charts should be shown in netdata?

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
