### ISSUE TITLE
Apache plugin does not seem to be working after update

### ISSUE THREAD

**Issue by raimov-uptime** [netdata/netdata#5108]
Hello. 

I had apache plugin installed and working correctly but after an update it does not work. When I debug the plugin I get:
`python.d ERROR: apache: apache: Url: http://localhost/server-status?auto. Error: 'module' object has no attribute 'Retry'`
That url is working if I try it manually. I used kickstart.sh for installation and it runs on amazon ec2.

**Comment by ilyam8** [comment]
Hi @raimov-uptime 

It seems your system has old `urllib3` package. Please check version.

Can you update it?

**Comment by ilyam8** [comment]
@raimov-uptime 
please check the fix
https://github.com/netdata/netdata/pull/5109

**Comment by raimov-uptime** [comment]
@ilyam8 Upgrading `urllib3` package worked. Thanks (also for the fix)

**Comment by ilyam8** [comment]
@raimov-uptime what version was the package?

**Comment by ilyam8** [comment]
https://pypi.org/project/urllib3/1.12/#history

Current is 1.24.1 (November 2018)

I checked 1.12 (September 2015) and it has Retry object

**Comment by raimov-uptime** [comment]
It was version 1.8.2.

**Comment by ilyam8** [comment]
Oh man, 1.8.2 is April 2014 :smile: 

Maybe it's a good idea to not merge the fix and force people to upgrade.

@Ferroin what do you think?

**Comment by Ferroin** [comment]
I'm with @cakrit on this one, it makes no sense to support such ancient versions, but the installer should check versions for everything we depend on and issue appropriate errors or warnings if the version requirement isn't met.

**Comment by paulfantom** [comment]
> installer should check versions for everything

Why couple it with installer when this is a module issue? Even better is the fact that this is an issue with an **external** module and we are trying to find a way to maybe decouple those from netdata/netdata repository (look at #5006). Also we have far too many modules which depend on other software to do it efficiently in an installer/updater. Additionally we are also distributing netdata as a docker container which cannot do such checks.
Also we are trying to remove as much logic as possible from the installer as a slow transition towards binary packaging.

**Comment by paulfantom** [comment]
We are vendoring urllib3 package so there is no need to do such checks: https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/python_modules/urllib3

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/blob/fd680665fe6ca60daf0b7741634c925cd64962e7/collectors/python.d.plugin/python.d.plugin.in#L39

append

**Comment by paulfantom** [comment]
But why?! We are vendoring libraries which we need, so why we even use system ones?

**Comment by ilyam8** [comment]
I am not sure the `urllib3` library, we shipping with netdata, will work on ancient systems.

Actually it will. Netdata's urllib3 version is 1.21

I see from[ the change log](https://pypi.org/project/urllib3/) they drop support for py2.6 only in 1.24

**Comment by Ferroin** [comment]
The problem is that we kind of need to supplement the system libraries.  There are a lot of our python.d modules that depend on specific third-party Python libraries which need to be installed on the system, and _those_ need to find the versions of modules they expect to.

So, we either need to support using the system libraries, or we need to vendor _everything_.  This goes double for `urllib3`, because it's pretty widely used by other Python modules.  We theoretically could namespace things so there is no collision issue, but that ends up resulting in us using a lot more memory in a some cases because it means we have multiple versions of the code in memory.

**Comment by Ferroin** [comment]
Also, when we move to actual packaging, we should be moving _away_ from vendoring things like this and switch to using proper package dependencies (because we'll be able to properly leverage the package manager at that point).

**Comment by ilyam8** [comment]
@paulfantom is talking about import order, we can do insert instead of append.

**Comment by ilyam8** [comment]
Rename `urllib3` to something will work too :smile:

**Comment by Ferroin** [comment]
>> we can do insert instead of append.
>
> This way we would ensure that we are using what we are shipping.

As mentioned above, it still runs the risk of breaking other libraries we depend on that we don't vendor (and shouldn't, if we vendored everything we'd be spending more time keeping things up to date and punting bugs upstream that we'd get no new development done) .  At minimum, we would need to namespace our usage of urllib3 and reset the import paths before we load the modules.

**Comment by ilyam8** [comment]
`urllib3` is the only problem package and i don't think we will vendor something else in the future

1. `urllib3` => `nurllib3`
2.
```python
try:
    import nurllib3 as urllib3
except ImportError:
    import urllib3
```

**Comment by ilyam8** [comment]
> As mentioned above, it still runs the risk of breaking other libraries we depend on that we don't vendor 

please give en example

**Comment by Ferroin** [comment]
>> As mentioned above, it still runs the risk of breaking other libraries we depend on that we don't vendor
>
> please give an example

Same exact type of thing happening here, just for a third-party library instead of us.  If any of the third-party libraries a module depends on depend on a newer version of urllib3 than what we're shipping, changing our `sys.path` manipulations from append to insert will break them (because they'll get our copy of urllib3 instead of the system copy).  The problem arises from the fact that we can't know for any arbitrary system if whatever versions of those third-party libraries that may be installed on that system will break from this or not.

**Comment by paulfantom** [comment]
@Ferroin what do you propose?

**Comment by Ferroin** [comment]
I think the rename approach is fine, but we should only be searching in our module directory for our own imports when stuff is vendored.  This issue pretty much demonstrates that we want to explicitly avoid using the system libraries, so it looks like we should be using a custom `sys.path` only for our imports, and use the default for everything else.  I'm not sure what the best way to go about that this is though.

**Comment by ilyam8** [comment]
> I think the rename approach is fine, but we should only be searching in our module directory for our own imports when stuff is vendored.

No. Look at debian/ubuntu netdata package. They don't include our `pyyaml` and `urllib3`. The thing is order - our, then system.

**Comment by ilyam8** [comment]
Rename or move vendored stuff to a separate package will do
```python
try:
    from our import urllib3
except ImportError:
  ...
or
try:
    import nurllib3 as urllib3
except ImportError:
...
```

**Comment by Ferroin** [comment]
I like the first approach a bit better, but we still need to make sure we're not polluting things for third-party libraries our modules are using.

I'd propose instead:

```python
try:
    from netdata import urllib3 as nd_urllib3
except ImportError:
   ...
```

Using `netdata` for the package name makes it a bit clearer where the module is comming from, and having the prefix means that we don't have to worry about issues like this one happening for any libraries our collector modules depend on.

**Comment by ilyam8** [comment]
> urllib3 as nd_urllib3

not needed if

> from netdata import urllib3

Actually using system package is OK. The OP problem that we don't check version.
