### ISSUE TITLE
netdata web page doesn't show float instead shell

### ISSUE THREAD

**Issue by AlexandreLicinio** [netdata/netdata#5111]
Hi, first thanks about Netdata, this is an awesome tool.

I don't manage float() in python.d module well.
I did write my own python.d chart to display some specific information gathered from a broadcast equipement. It works very well but i can't display a float number over the web page, the number only appears with 0 behind the coma.

`
l = str('margin')
idx1 += [l, 'absolute', 10, 100]
if l not in d:
d.add_dimension([l])
dic[l] = 0 if 'disconnected' in pkl_STATUS['status'][0] else float(pkl_INFO['info'][0]['sat_margin'])
`

In the shell when i do
`
cd /opt/netdata/var/log/netdata && tail -f error.log | grep ATEMEekla
`

I can see:
`2019-01-03 17:08:23: python.d ERROR: ATEMEekla_ateme_dr5000_1: ATEMEekla_ateme_dr5000_1: {'margin': 4.6, 'sat AL-rassd': 5634.048}`

So margin is `4.6` so it is correct, it's the float value.
But the webpage displays:
`margin 4,00`

I did try to change the multiplier and the divider but without any success :(

Thanks

**Comment by ilyam8** [comment]
Hi @AlexandreLicinio 

https://docs.netdata.cloud/collectors/plugins.d/#data-collection



 * value

> is the collected value, only integer values are collected. If you want to push fractional values, multiply this value by 100 or 1000 and set the DIMENSION divider to 1000.

**Comment by ilyam8** [comment]
```python
CHARTS = {
    'random': {
        'options': [None, 'A random number', 'random number', 'random', 'random', 'line'],
        'lines': [
            ['random1', 'random1', 'absolute`, 1, 1000]
        ]
    }
}

...
...
...

data['random1'] = value * 1000  #  value = 4.654
```

**Comment by AlexandreLicinio** [comment]
Thanks @ilyam8 but no success or perhaps do i have to wait until all timeline refreshed on web page ?
The shell shows the float but not the webpage.

`elif pkl_INFO['info'][0]['input_type'] == 'sat':
        CHARTS = {
                'Mux_Rate': {
                        'options': [None, 'Mux_Rate', 'kb/s', pkl_STATUS['client_name'][0], 'ateme'+pkl_STATUS['client_name'][0]+'Mux_rate', 'line'],
                        'lines': []
                        },
		'info': {
                        'options': [None, 'info', 'db', pkl_STATUS['client_name'][0], 'ateme'+pkl_STATUS['client_name'][0]+'info', 'line'],
                        'lines': []
                        }
                }`

`d = self.charts['info']
                idx1 = []
                l = str('margin')
                idx1 += [l, 'absolute', 1, 1000]
                if l not in d:
                    d.add_dimension([l])
                dic[l] = 0 if 'disconnected' in pkl_STATUS['status'][0] else pkl_INFO['info'][0]['sat_margin']`

The number in the pickle is a float not a int or a string
Sorry for the identation about python code paste.

**Comment by ilyam8** [comment]
@AlexandreLicinio 

Well, i suggest to simplify the code, it's hard to read/understand what is happening now :smile: 

Paste the whole module (using [this](https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f)), i will try to help you with the problem.

**Comment by AlexandreLicinio** [comment]
Thanks but i already did that and the margin goes to `4700` instead `4.7`

**Comment by ilyam8** [comment]
```python
	d = self.charts['info']
        idx1 = []
        l = str('margin')
        idx1 += [l, 'absolute', 1, 1000]
        if l not in d:
            d.add_dimension([l])
```

=>

```python
	d = self.charts['info']
        l = str('margin')
        if l not in d:
            d.add_dimension([l, None, 'absolute`, 1, 1000])
```

**Comment by ilyam8** [comment]
i see `idx1` is not used

**Comment by AlexandreLicinio** [comment]
Thanks @ilyam8 ! It works 🥇 

```
elif pkl_INFO['info'][0]['input_type'] == 'sat':
		d = self.charts['info']
		l = str('margin')
                if l not in d:
                    d.add_dimension([l, None, 'absolute', 1, 1000])
                dic[l] = 0 if 'disconnected' in pkl_STATUS['status'][0] else float(pkl_INFO['info'][0]['sat_margin'])*1000
```
