### ISSUE TITLE
Correct home directory for netdata set in /etc/passwd?

### ISSUE THREAD

**Issue by andyforceno** [netdata/netdata#5128]
When I run the tiger security tool, it reports the following:
`--WARN-- [pass016w] User netdata has / as home directory`

Sure enough, the user netdata has `/` set as the home dir in `/etc/passwd`. 

What is the correct home dir for the netdata user as specified in `/etc/passwd`? Is it `/usr/sbin/` where `netdata` appears to be executed from, or `/etc/netdata`? The former seems correct, but I thought I'd check. 

I'm currently running Netdata v1.12.0-rc2-14-ge51b735

**Comment by Ferroin** [comment]
I'd say `/var/lib/netdata` probably makes the most sense here.  `/var/cache` is almost never used for home directories because applications are supposed to be able to work correctly even if `/var/cache` gets nuked.

**Comment by ilyam8** [comment]
It should be fixed
