### ISSUE TITLE
Configuration translator

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#5144]
##### Feature idea summary
We need to have a configuration translator which will translate configuration from python.d.plugin configuration schema into go.d.plugin configuration schema.

Configuration schema developed for go.d.plugin will be then a standard job configuration stored in `conf.d` directory instead of separate plugin configuration directories.

This translator is essential for including go.d.plugin into default netdata installation.

##### Expected behavior
All plugins use the same configuration schema.

**Comment by cakrit** [comment]
We agreed we'll add something like this in #5311, we can go into the design now.

**Comment by paulfantom** [comment]
Closing as #5311 was also closed.
