### ISSUE TITLE
Python.d plotting zeros

### ISSUE THREAD

**Issue by jakk2809** [netdata/netdata#5146]
##### Question summary
Is the chart supposed to hide a dimension that is '0' (zero)? This seems to happen when a dimension is zero for the visible time interval of a chart.

##### OS / Environment
Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-43-generic x86_64)

##### Component Name
Python.d

##### Expected results
Plot all zeros. Do not hide a dimension even if it is constantly zero.

**Comment by ilyam8** [comment]
Hi @jakk2809 

Yes, it's by design. You can change the behaviour. 

![screenshot_20190110_100145](https://user-images.githubusercontent.com/22274335/50951608-d7e59580-14be-11e9-9e60-0097943a6779.png)

> Which dimension to show?

**Comment by jakk2809** [comment]
Thank you! Sorry I missed that. Works great now, even for dimensions that are "None".

**Comment by ilyam8** [comment]
You are welcome @jakk2809
