### ISSUE TITLE
Tuning alerts/notifications 

### ISSUE THREAD

**Issue by dwreski** [netdata/netdata#5157]
##### Question summary
I'd like advice on how best to manage the tons of alerts for the different systems being monitored.

For example, I have a backup system that constantly receives alerts for mdstat_last_collected, I'm assuming because the disks are actively writing the backup data from the remote systems during that time, and can't update the mdstat info.

```
mdstat last collected (was warning for 6 minutes and 42 seconds)
number of seconds since the last successful data collection
```
Is it okay to adjust the alert to not send notification for like seven minutes? Maybe I should disable that alert for that system entirely? I understand how to adjust the alert by editing mdstat.conf and changing the "every" value, but is that the best approach to reduce the noise without risking missing a real alert?

Maybe there's a "backup server" set of templates that can be installed with more reasonable defaults?

##### OS / Environment
```
# uname -a
Linux pixie.example.com 4.19.13-300.fc29.x86_64 #1 SMP Sat Dec 29 22:54:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
##### Component Name
mdstat_last_collected
##### Expected results
Ideally I'd like it to alert me to real problems with the mdstat system, not just the inability to update because it's doing something else.

**Comment by ilyam8** [comment]
Hi @dwreski 

> Is it okay to adjust the alert to not send notification for like seven minutes?

[Yes](https://docs.netdata.cloud/health/#alarm-line-delay). Adjust if you need.

> Maybe I should disable that alert for that system entirely? 

Sounds not good to me.

> I'm assuming because the disks are actively writing the backup data from the remote systems during that time, and can't update the mdstat info.

It shouldn't be the case.

Please check the `error.log` when alarm is up.

@vlvkobal please help

**Comment by dwreski** [comment]
There are quite a few messages in the error.log file. Most are relating to an apparent problem with the heartbeat being missed, but do these point to a potential hardware problem? Or could they be related to the type of disk activity as a result of it being a backup (rsync) server?

`2019-01-12 03:46:45: netdata ERROR : PLUGINSD[apps] : '/usr/libexec/netdata/plugins.d/apps.plugin' (pid 13724) disconnected after 792055 successful data collections (ENDs).`

`2019-01-12 04:06:06: netdata INFO  : PLUGINSD[python.d] : RRD database for chart 'cpu.cpufreq' on host 'pixie.example.com' is 0.27536 secs in the future (counter #475298, update #72509). Adjusting it to current time.`

`2019-01-12 09:50:09: apps.plugin ERROR : MAIN : Cannot process /proc/1185/cmdline (command 'load') (errno 3, No such process)`

`2019-01-12 08:59:29: apps.plugin ERROR : MAIN : heartbeat missed 564999970 microseconds`

**Comment by ilyam8** [comment]
The alarm.

https://github.com/netdata/netdata/blob/4505c9f70e842304361713379becc9331af395b0/health/health.d/mdstat.conf#L1-L9

`md.disks` - `Disks Stats` chart. It should be updated on every iteration if the `md` is there. So if the `md` is not missing from `mdstat` this is a bug.

> Or could they be related to the type of disk activity as a result of it being a backup (rsync) server?

i hoped to see some error messages from `mdstat` plugin.

**Comment by ilyam8** [comment]
Ok, let's wait @vlvkobal 

If you have time it would be nice if you check if python version has same problems. 

  * disable `c` version in `netdata.conf` (`/proc/mdstat = yes` => `no`)
  * enable python
https://github.com/netdata/netdata/blob/4505c9f70e842304361713379becc9331af395b0/collectors/python.d.plugin/python.d.plugin.in#L59

remove `mdstat` ^
  * restart `netdata.service`

**Comment by dwreski** [comment]
I don't have /proc/mdstat, or anything relating to mdstat, in /etc/netdata/netdata.conf.

I also don't have python.d.plugin.in anywhere on my system. I installed the RPM on fedora, not directly from git.

**Comment by ilyam8** [comment]
it is `python.d.plugin` (w/o `.in`)

what's your nedata version?

**Comment by dwreski** [comment]
It looks like netdata-1.10.0-1.el6.x86_64, Aug of 2018, I believe downloaded directly from the website.. I also don't have python.d.plugin.

**Comment by ilyam8** [comment]
> netdata-1.10.0

Well, it's very old.

I suggest to update to the latest.

**Comment by dwreski** [comment]
Okay, I've updated to 1.11 now, but see mdstat.conf has moved to /usr/lib64/netdata/conf.d/health.d/mdstat.conf.

If I create my own mdstat.conf in /etc/netdata/health.d, will it override the system version?

There is also a version in /usr/lib64/netdata/conf.d/python.d/mdstat.conf. I don't understand the difference.

**Comment by ilyam8** [comment]
> If I create my own mdstat.conf in /etc/netdata/health.d, will it override the system version?

yes

> There is also a version in /usr/lib64/netdata/conf.d/python.d/mdstat.conf. I don't understand the difference.

it's python module configuration, it is obsoleted (replaced by `c` version).

**Comment by ilyam8** [comment]
@dwreski 

latest is `v1.12.0-rc2`, i suggest to update to the latest

**Comment by paulfantom** [comment]
Latest stable/release is `v1.12.0`.
Latest nightly is `v1.12.0-rc2-35-nightly` or `v1.12.0-rc2-35-258a635` depending on installation method.

**Comment by cakrit** [comment]
Note that you can use the [hosts](https://docs.netdata.cloud/health/#alarm-line-hosts) line in alarms, to have them behave differently for different hosts. In reality though, what you really need is a way to temporarily disable certain alarms from the backup host, while your backups are running. This is coming with #4969

**Comment by ilyam8** [comment]
In first place there shouldn't  any problem because of
https://github.com/netdata/netdata/issues/5157#issuecomment-453774267

This is why i suggest to update to the latest (to use `c` `mdstat` collectors). And see if the problem is still exist.

**Comment by cakrit** [comment]
I based my answer on this: 

> assuming because the disks are actively writing the backup data from the remote systems during that time, and can't update the mdstat info

The state and the logs should be examined while the problem is present (presumably, when the backup system is under stress and alarms are firing). The "constantly" in the following statement does need to be qualified though:

> constantly receives alerts for mdstat_last_collected

Does the backup run e.g. every X hours and are the alarms correlated with that execution schedule?
If so, the investigation should be focused on what exactly happens during those periods only.

**Comment by dwreski** [comment]
Following up with an issue from some time ago with more info. I was asked to upgrade to the latest version, and I have done that. The problem with excessive alerts persists.

This is regarding a backup server with excessive alerts regarding disk activity. These are the alerts that are received during the periods where the rsync backup occurs regularly:

 10min disk utilization = 92% (disk_util.sdb)
 inbound packets dropped ratio = 0.14% ( net_packets.eno1 )
 10min disk backlog = 5574 ms ( disk_backlog.sdb )
 inbound packets dropped = 14 packets ( net_drops.eno1 )
 10min disk utilization (was warning for 4 hours and 7 minutes) ( disk_util.sdc )
 10min fifo errors = 24 errors ( net_fifo.eno1 )

Do I need to tune each of these to just ignore these alerts entirely?

**Comment by vlvkobal** [comment]
You can use the [Health Management API](https://docs.netdata.cloud/web/api/health/#health-management-api) to disable alarms while the backup is running.
