### ISSUE TITLE
Inbound packets dropped ratio constantly exceeds alarm limit

### ISSUE THREAD

**Issue by photis** [netdata/netdata#5158]
This issue is similar to #4536, which was closed, so I hope I'm doing the right thing filing a new issue. I'm seeing a large number of packets dropped too. 
> RX packets:11791910 errors:0 dropped:76076 overruns:0 frame:0

Netdata constantly sounds the alarm because my ratio of dropped packages for the last 10 minutes exceeds 0.1%

I found this on the Intahrnet:
```
Beginning with kernel 2.6.37, it has been changed the meaning of dropped packet count. 
Before, dropped packets was most likely due to an error. Now, the rx_dropped counter 
shows statistics for dropped frames because of:

Softnet backlog full
Bad / Unintended VLAN tags
Unknown / Unregistered protocols
IPv6 frames when the server is not configured for IPv6
[...]

If the rx_dropped counter stops incrementing while tcpdump is running; then it is more 
than likely showing drops because of the reasons listed earlier.
```
Meanwhile `ifconfig` has this to say:
```
$ sudo ifconfig eth0
eth0      Link encap:Ethernet  HWaddr f4:4d:30:6d:93:92
          inet addr:192.168.1.201  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::f64d:30ff:fe6d:9392/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11791910 errors:0 dropped:76076 overruns:0 frame:0
          TX packets:17464164 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2459415409 (2.2 GiB)  TX bytes:17603379495 (16.3 GiB)
          Interrupt:20 Memory:aa100000-aa120000
```
But `ethtool` finds no fault:
```
$ sudo ethtool -S eth0 | grep rx
     rx_packets: 11788295
     rx_bytes: 2458306572
     rx_broadcast: 139088
     rx_multicast: 129038
     rx_errors: 0
     rx_length_errors: 0
     rx_over_errors: 0
     rx_crc_errors: 0
     rx_frame_errors: 0
     rx_no_buffer_count: 0
     rx_missed_errors: 0
     rx_long_length_errors: 0
     rx_short_length_errors: 0
     rx_align_errors: 0
     rx_flow_control_xon: 0
     rx_flow_control_xoff: 0
     rx_csum_offload_good: 11637919
     rx_csum_offload_errors: 6
     rx_header_split: 0
     alloc_rx_buff_failed: 0
     rx_smbus: 0
     rx_dma_failed: 0
     rx_hwtstamp_cleared: 0
```
Would it be best to just disable this alarm, or is there indeed cause for concern and should I try to dig deeper? Thanks.

Netdata version: v1.12.0-rc2-33-g54beb88 - commit: 4505c9f 
Debian Linux 8
Linux 3.16.0-7-686-pae on i686
Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz, 4 cores

**Comment by Ferroin** [comment]
Based on what you've shown, that works out to about 0.6% of all received packets since the last time that system rebooted being dropped.  For anything above about 0.1%, you generally want to figure out why they're dropped, because even though it's usually benign, it's still wasting network bandwidth and processing time.

Unfortunately, I'm not quite sure where to start on this one.  Checking if `tcpdump` or some other packet capture program that can put the interface in promiscuous mode makes the drop counter stop increasing would be useful, but you've got a low enough percentage of drops that it would be hard to be certain that it's not just luck that caused them to stop.  Double-checking the configuration for all the systems on that network would be useful too, as stuff like this is _usually_ a result of some system not being properly configured.

**Comment by cakrit** [comment]
For me, `tcpdump` did make the packet drops disappear, as @Ferroin said. I went through https://serverfault.com/questions/780195/dropped-packets-in-all-linux-and-unix looking for an answer. 
I remember that a few weeks ago I had used `tcdump` and traced the issue I saw to broadcast packets coming from my router every 12sec, like the following:
```
11:32:36.879101 d8:b6:b7:d9:fc:74 (oui Unknown) > Broadcast, ethertype Unknown (0x88e1), length 60: 
11:32:36.879101 d8:b6:b7:d9:fc:74 (oui Unknown) > Broadcast, ethertype Unknown (0x88e1), length 60: 
        0x0000:  0000 a000 b052 0000 0000 0000 0000 0000  .....R..........
        0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............
11:32:36.879108 d8:b6:b7:d9:fc:74 (oui Unknown) > Broadcast, ethertype Unknown (0x88e1), length 60: 
        0x0000:  0000 a000 0000 16e8 0600 0000 0000 0000  ................
        0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............
```
They don't bother me, so I didn't look any further.

**Comment by meguroyama** [comment]
I had to increase the net.core.netdev_budget to 100k for the issue to go away.

**Comment by chrisspiegl** [comment]
I am experiencing this as well. The machine is relatively low traffic but shows (what looks like one dropped package) dropped packages every 30 seconds (see screenshot).

It recently got to the point of being a constant alert and I am wondering where that is coming from. I tried doing some research about it and also found the above mentioned serverfault article but don't really know how to move forward now.

Is this something that is internal to Netdata, system updates, or changes in how things are reported? Do we need to adjust in some way?

I am running everything on Ubuntu with the netdata version `v1.12.0-22-nightly`.

<img width="1549" alt="screen shot 2019-02-15 at 11 14 11" src="https://user-images.githubusercontent.com/1096384/52850196-31bb2a00-3113-11e9-9375-18ae899e80a6.png">

**Comment by cakrit** [comment]
> Is this something that is internal to Netdata, system updates, or changes in how things are reported? Do we need to adjust in some way?

Netdata is telling you the truth. I haven't seen anyone requesting that we adjust the alarm threshholds in the stock configuration. A `tcpdump` should tell you where it's coming from, it looks like you have a very similar situation to [mine](https://github.com/netdata/netdata/issues/5158#issuecomment-462283208).

**Comment by chrisspiegl** [comment]
@cakrit Thank you, I have tried looking into those things. I'm just struggling to figure out what it actually is. When I am running the `tcpdump` those 30 second package drops go away.

I also tried disabling the IPv6 on the server and that didn't change a thing. So there is that. I might just endup disabling the alert if I can't figure it out myself 🙈.

**Comment by Ferroin** [comment]
@chrisspiegl If using `tcpdump` reliably makes the drops disappear, then the packets getting dropped are probably not actually intended for your system.  Assuming it's not a router, check the destination MAC addresses and IP addresses for the packets recorded by `tcpdump` and make sure they all match up with the interface they're coming in over.  I suspect you'll see some that don't match, and those are almost certainly what's getting dropped.

**Comment by chrisspiegl** [comment]
@ferroin thank you for that explanation. It makes sense now and I understand it better. I will investigate and contact my hoster if it continues.

**Comment by TomVanBerlo** [comment]
We have the same issue and after some investigation broadcast and multicast packets with vlan tags that were not configured on our interface were the cause of the dropped packets. Tcpdump made the drops disappear. What can be done to fix this? I can silence the alarm but if there are dropped packets intended for the interface I won't be notified. 
```
root@ubuntu:~# date; cat /proc/net/dev; sleep 5; date; cat /proc/net/dev;
Fri Jul 26 09:47:56 CEST 2019
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  ens3: 3137648   20127    0 3377    0     0          0         0  5155300    3582    0    0    0     0       0          0
    lo: 2488228    5932    0    0    0     0          0         0  2488228    5932    0    0    0     0       0          0
Fri Jul 26 09:48:01 CEST 2019
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  ens3: 3141292   20161    0 3389    0     0          0         0  5159130    3590    0    0    0     0       0          0
    lo: 2495523    5947    0    0    0     0          0         0  2495523    5947    0    0    0     0       0          0
```
This is on a test machine with low network traffic but it generates a critical alarm. Percentage dropped vs accepted traffic = 17.7%. 
We concerned that we might receive these alarms when our systems are hardly used.

**Comment by ilyam8** [comment]
> broadcast and multicast packets with vlan tags that were not configured on our interface

have you considered removing these vlans from the switch trunk port toward the server?

**Comment by TomVanBerlo** [comment]
> have you considered removing these vlans from the switch trunk port toward the server?
Thanks for the quick reply. It was on a virtual machine in ovirt and we used the vlan that received all traffic(ovirtmgmt). We are changing it to a specific vlan to see if that solves the problem.

**Comment by gschintgen** [comment]
Hi, I also had mysterious dropped packets. I'll just leave a short note in case anyone else finds it useful.

In my case it turned out that my Linux software bridge dropped broadcasts of an "unknown" protocol. Those broadcasts came in fact from my home router (AVM FritzBox 6490) which is constantly checking for Powerline devices. So it's similar to what @cakrit [mentioned earlier](https://github.com/netdata/netdata/issues/5158#issuecomment-462283208).

There seems to be no way to disable this router "feature". Fortunately `ebtables` can be used to filter those packets, so that they're not polluting the interface statistics anymore.
See [here](https://blog.hambier.lu/post/tracking-dropped-packets) for details.

**Comment by utdrmac** [comment]
Netdata started chirping about this recently. What changed in my network? Oh, I got a new 16 port switch, TPLink SG116E. Using @cakrit tcpdump, I can see these:

`15:28:42.898383 b0:be:76:ac:c9:b3 (oui Unknown) > Broadcast, RRCP-0x25 reply`

Who's MAC is that? Why, it's the switch's! WTF is RRCP? https://en.wikipedia.org/wiki/Realtek_Remote_Control_Protocol

Guess the switch uses Realtek chipset and constantly yells out (broadcasts) in case I ever decide to get a windows machine and use their management GUI. (Not a chance).
Watching `ifconfig` (`watch -n1 ifconfig enp6s0`) along with `tcpdump`, I can see the dropped packet counter increases each time one of these comes across.

Any ideas how to block them? Doesn't look like `iptables` can be used because it's not an IP protocol. Some blog posts show using `ebtables` but this isn't a bridged interface.

**Comment by gschintgen** [comment]
> Any ideas how to block them? Doesn't look like `iptables` can be used because it's not an IP protocol. Some blog posts show using `ebtables` but this isn't a bridged interface.

I'm not an expert on this, but it may be possible (though a bit hackish) to set up a bridge with only a single slave interface: https://ebtables.netfilter.org/examples/basic.html#ex_nobridge

**Comment by Ferroin** [comment]
> > Any ideas how to block them? Doesn't look like `iptables` can be used because it's not an IP protocol. Some blog posts show using `ebtables` but this isn't a bridged interface.
> 
> I'm not an expert on this, but it may be possible (though a bit hackish) to set up a bridge with only a single slave interface: https://ebtables.netfilter.org/examples/basic.html#ex_nobridge

It is possible, and it works reasonably well for stuff like this, though it can be a pain to set up if you have to deal with stuff like NetworkManager or systemd-networkd.

**Comment by utdrmac** [comment]
Ubuntu 18.04 LTS uses NetPlan for managing network stuff. Feels like this would be overkill just to stop this alarm. Guess I'll modify netdata to chirp less on it. Thanks!

**Comment by thiagoftsm** [comment]
Hi @Ferroin ,

Confirming what you said, I began to have alarms like this when I started to use NetworkManager on Slackware current.

**Comment by iamareebjamal** [comment]
Same issue

**Comment by Uzzi** [comment]
Same issue on Proxmox node

**Comment by myfri09** [comment]
Also same issue on Proxmox Node.

**Comment by jw-g19** [comment]
I found the RRCP broadcasts from both TP-link TL-SG105e and Netgear GS908e were stopped by disabling "loop prevention" on the switch.
Alternatively, nftables can be used to drop the packets at ingress using something like: 

table netdev filter {
        chain eth0input {
                 type filter hook ingress device eth0 priority 0;
                   ether type 0X8899 counter drop # RRCP from switch
        }
}

**Comment by Seji64** [comment]
> 
> 
> I found the RRCP broadcasts from both TP-link TL-SG105e and Netgear GS908e were stopped by disabling "loop prevention" on the switch.
> Alternatively, nftables can be used to drop the packets at ingress using something like:
> 
> table netdev filter {
> chain eth0input {
> type filter hook ingress device eth0 priority 0;
> ether type 0X8899 counter drop # RRCP from switch
> }
> }

Thanks for this great hint! I disabled loop prevention on my TP-Link TL-SG116E. Finally i found the f**** reason for my rx_drops.

**Comment by gaia** [comment]
Also here on proxmox, but only on the tap interfaces for pfSense.

"It is especially true for some bonding configurations if an interface is a child or a bonding interface itself. If it is expected to have a certain number of drops on an interface for a certain network configuration"

from https://learn.netdata.cloud/docs/agent/collectors/proc.plugin#monitored-network-interface-metrics

I've disabled the alarm for the both pfSense tap adapters.

**Comment by OdysLam** [comment]
@Seji64 We are happy that you got it sorted and welcome to our community :) 

Thanks @jw-g19 for providing the hint!

**Comment by vjt** [comment]
For anybody stumbling into this same alarm on ESX infrastructures, [vMotions generate RARP packets](http://rickardnobel.se/vswitch-notify-switches-setting/) and these are by default dropped by the Linux kernel, and at least for me were accounting for plenty of packets dropped alarms.

If you have a recent enough kernel, the solution by @Seji64 above would work perfectly well to drop these out early:
```
table netdev filter {
  chain eth0input {
    type filter hook ingress device eth0 priority 0;
    ether type 0X8035 counter drop # RARP from VMware
  }
}
```

Cheers

**Comment by OdysLam** [comment]
Hey @vjt, 

Thanks for this. If we wanted to put this tip in our documentation, where would you expect it to find it? Existing documentation piece or a new one?

**Comment by vjt** [comment]
Hi @OdysLam! I would create a new page in the Health section [of the current documentation](https://learn.netdata.cloud/docs/agent/health) such as "notable alarms tuning / common pitfalls" or something on those lines.

That is because if googling "netdata alarms configuration" one immediately lands on that page ;-)

Cheers

**Comment by OdysLam** [comment]
Thanks @vjt for the tips, we will discuss it with @joelhans who is leading our efforts in documentation.

Joel, I feel that this would be a very good candidate for our FAQ/Knowledge base, which I feel that the need is amount by the day. Let's discuss one of these days!

**Comment by angelss197200** [comment]
I have the same issue with systemd-networkd and networkmanager, but not in dhcpcd

**Comment by OdysLam** [comment]
Hey @angelss197200,

Since we have switched our support to our forums at https://community.netdata.cloud, please go ahead and open a topic for any problem that you may have in the support category!

**Comment by tomldickson** [comment]
On my Linode servers this was triggered by LLDP:

    tcpdump -i eth0 ether proto 0x88cc

Shows it clearly happening every 30 seconds, just like netdata says:

    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
    listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
    23:21:53.723532 LLDP, length 207: h1752-rin1
    23:22:23.733646 LLDP, length 207: h1752-rin1
    23:22:53.744438 LLDP, length 207: h1752-rin1

So this in theory will stop it though I now have to figure out how to run ntfables on Ubuntu 16.04 :(

    table netdev filter {
        chain eth0input {
            type filter hook ingress device eth0 priority 0;
            ether type 0X88CC counter drop # LLDP
    }

**Comment by kyle0r** [comment]
I had flapping on this alarm too, thanks to the useful shares in this thread, it was easy to track down and implement a solution.

First I took a look at what is going on with tcpdump, assuming this exclusion filter is good:

`tcpdump -i $interface not \( udp or tcp or arp \)`

I observed LLDP packets at 60 second intervals which lined up with NetData's `net_drops` graph for the relevant `$interface`:

`05:47:19.450513 LLDP, length 119: MikroTik`

So I reused @tomldickson's suggestion to drop EtherType `0X88CC` [see here for a list of types](https://en.wikipedia.org/wiki/EtherType).

On my Debian Buster system I edited `/etc/nftables.conf` to append the drop rule.

```
table netdev filter {
    chain ens6input {
        type filter hook ingress device ens6 priority 0;
        ether type 0X88CC counter drop # LLDP
    }
}

# followed by
service=nftables.service
systemctl enable $service; systemctl start $service;

# followed by - to check the rules had applied
nft list ruleset
```

change the interface references to match your `$interface`.

Cautionary footnote on `nftables`, you should be cognitive of what your system is using for firewalling, just blindly starting to use `nftables` might end up causing more problems.

Proxmox users should [be aware of this forum thread](https://forum.proxmox.com/threads/v6-0-move-from-iptables-to-nftables.55924/), and that proxmox still uses the legacy xtables alternative.

From Mar 24, 2021:
> hello, i found that latest proxmox 6.3 still seems to be using iptables/ebtables legacy versions.

My home lab proxmox isn't using the `pve-firewall` so it was safe for me to use the `nftables` approach. I do not know if this specific ruleset is interoperable with the legacy xtables. More reading here on [Debian wiki here](https://wiki.debian.org/nftables).

**Comment by roesel** [comment]
Just in case this helps someone in the future, I had the same issue with a Proxmox host getting dropped packets triggered by a MikroTik router. Most of the solutions out there didn't work, but what worked was simply:

`sudo apt install lldpad`

(Note that it's `lldpad` and not `lldpd`.)

All dropped inbound packets disappeared immediately.

**Comment by ilyam8** [comment]
Disabling LLDP is an alternative solution (web UI: IP->Neighbors->Discovery settings).

**Comment by AlBundy33** [comment]
dropped packets with protocol 0x8912 and 0x88e1 are from avm fritz.box searching for powerline adapters.
https://pablo.tools/blog/computers/dropped-packets/

you can drop them with nftables
```
nft 'add table netdev filter'
nft 'add chain netdev filter ingress { type filter hook ingress device eno1 priority 0; policy accept; }'
nft 'add rule netdev filter ingress meta protocol {0x8912, 0x88e1} drop'
```

check the rules with
```
nft list ruleset
```

**Comment by smdx** [comment]
> lldpad

This is so awesome. The problem of using Netdata in Proxmox has been bothering me for days, and the LLDPAD installation is a perfect solution. Thank you very much.

**Comment by smdx** [comment]
> Just in case this helps someone in the future, I had the same issue with a Proxmox host getting dropped packets triggered by a MikroTik router. Most of the solutions out there didn't work, but what worked was simply:
> 
> `sudo apt install lldpad`
> 
> (Note that it's `lldpad` and not `lldpd`.)
> 
> All dropped inbound packets disappeared immediately.



> Just in case this helps someone in the future, I had the same issue with a Proxmox host getting dropped packets triggered by a MikroTik router. Most of the solutions out there didn't work, but what worked was simply:
> 
> `sudo apt install lldpad`
> 
> (Note that it's `lldpad` and not `lldpd`.)
> 
> All dropped inbound packets disappeared immediately.

This is so awesome. The problem of using Netdata in Proxmox has been bothering me for days, and the LLDPAD installation is a perfect solution. Thank you very much.

**Comment by roesel** [comment]
For other confused Proxmox admins with old MikroTik routers, I will also add that I noticed another packet causing problems with protocol `0x9abe`. After catching it with tcpdump and viewing it in Wireshark, I used `ebtables` to filter the host. I put the rule in place by running `ebtables -A INPUT -p 9abe -j DROP`.

I then checked if the filter was in place by running `ebtables -L --Lc` with the output of

```
Bridge table: filter

Bridge chain: INPUT, entries: 1, policy: ACCEPT
-p 0x9abe -j DROP , pcnt = 0 -- bcnt = 0

Bridge chain: FORWARD, entries: 0, policy: ACCEPT

Bridge chain: OUTPUT, entries: 0, policy: ACCEPT
```

I believe this is also an alternative solution to installing `lldpad`, where you could just add additional DROP rules without installing anything. This would apply to both these MikroTik packets like `0x9abe` / `0x88cc` and the ones coming from Fritz.box like `0x8912` / `0x88e1`. I hope this helps and saves someone the week of debugging I just did. I'm glad it was of some use @smdx ;).

**Comment by smdx** [comment]
> For other confused Proxmox admins with old MikroTik routers, I will also add that I noticed another packet causing problems with protocol `0x9abe`. After catching it with tcpdump and viewing it in Wireshark, I used `ebtables` to filter them on the host. I put the rule in place by running `ebtables -A INPUT -p 9abe -j DROP`.
> 
> I then checked if the filter was in place by running `ebtables -L --Lc` with the output of
> 
> ```
> Bridge table: filter
> 
> Bridge chain: INPUT, entries: 1, policy: ACCEPT
> -p 0x9abe -j DROP , pcnt = 0 -- bcnt = 0
> 
> Bridge chain: FORWARD, entries: 0, policy: ACCEPT
> 
> Bridge chain: OUTPUT, entries: 0, policy: ACCEPT
> ```
> 
> I believe this is also an alternative solution to installing `lldpad`, where you could just add additional DROP rules without installing anything. This would apply to both these MikroTik packets like `0x9abe` / `0x88cc` and the ones coming from Fritz.box like `0x8912` / `0x88e1`. I hope this helps and saves someone the week of debugging I just did. I'm glad it was of some use @smdx ;). (I have no idea if this solution is compatible with best practices on Proxmox, feel free to let me know how to do this better if you know!)

I will keep in mind that I will use this rule if necessary. Thank you.

**Comment by meguroyama** [comment]
No longer seeing this issue as of latest release.

**Comment by danilobbezerra** [comment]
I was having this error on a VM on proxmox reading the comments here I accessed my TPLINK TL-SG108E switch and disabled Loop Prevention and it worked.

Thanks.

**Comment by vlindhol** [comment]
This has been bugging me as well, finally tracked it down to STP: https://serverfault.com/questions/1053889/stp-packet-filtering

`sudo modprobe stp` made the dropped packets drop to zero <3

**Comment by blockloop** [comment]
> Just in case this helps someone in the future, I had the same issue with a Proxmox host getting dropped packets triggered by a MikroTik router. Most of the solutions out there didn't work, but what worked was simply:
> 
> `sudo apt install lldpad`
> 
> (Note that it's `lldpad` and not `lldpd`.)
> 
> All dropped inbound packets disappeared immediately.

I've spend several months tracking this down to no avail. THANK YOU!

**Comment by AndreyShpilevoy** [comment]
For me, it was a problem with TIPC protocol. My router broadcast message:
```
00:37:03.892832 TIPC v2.0 111.xxxx.1 > 111.xxxx.0, headerlength 60 bytes, MessageSize 60 bytes, Neighbor Detection Protocol internal, messageType Link request
```
I added it to ignore with:
`ebtables -A INPUT -p 88ca -j DROP`

Also had an issue with IEEE-1905.1 that was broadcasted by router.

I added it to ignore with:
`ebtables -A INPUT -p 893a -j DROP`

I have TpLink Mesh Router Deco with PowerLine.

Total rules for my Proxmox host and Proxmox Backup Server:
```
root@pbs:/# ebtables -L --Lc

Bridge table: filter

Bridge chain: INPUT, entries: 2, policy: ACCEPT
-p 0x893a -j DROP , pcnt = 522 -- bcnt = 56898
-p 0x88ca -j DROP , pcnt = 23 -- bcnt = 1380

Bridge chain: FORWARD, entries: 0, policy: ACCEPT

Bridge chain: OUTPUT, entries: 0, policy: ACCEPT
```
