### ISSUE TITLE
[RFC] Simplify build system

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#5159]
##### Feature idea summary
I am starting a slow process of preparing a move from current build system to CMake. To accomplish full transition I would like first to cleanup current code base and drastically simplify it by removing options which should be enabled by default or are not used. Later this would allow to have a cleaner, more concise build system, where we could use `#cmakedefine` instead of autoconf. 

I consider cleaning up current build system a critical step towards moving to CMake. Therefore **this issue is a blocking one** until we reach here a consensus from Code Owners.

I identified a couple options which I think could go away from current build system implementation:

What?|Default status|Expected status|Implementation details
-----|-----|------|-----
**link-time optimization**|enabled|forcibly enabled|forcibly enable it when building using shell installer and remove flag from `configure.ac`. Autoconf will still be responsible for checking if LTO can be enabled.
**zlib** support|required (can be disabled)|hard requirement|I don't see any good option why this is a weak requirement. I would say that we should require it for the sake of user experience. Also we are everywhere saying firmly that this is a required library.
**libm/math** support|required (can be disabled)|hard requirement|I don't see any good option why this is a weak requirement. I would say that we should require it for the sake of user experience.
**uuid** library|required (can be disabled)|hard requirement|Thisis responsible for setting `NETDATA_WITH_UUID` variable, but I cannot find any reference to this variable anywhere outside of a build system code. We should either remove it completely or make it a hard requirement. Also we are everywhere saying firmly that this is a required library.
**--enable-pedantic**|disabled|removed|Flag adds `-pedantic -Wall -Wextra -Wno-long-long` cflags. This is something that should be handled by IDE or directly by a developer and not polluting build system code base. This is an undocumented "feature" and from "production-ready" program, there is no benefit in keeping it.
**--disable-x86-sse**|false|removed|This option can be confusing as we have an inverted logic here. By default we enable SSE optimizations and autoconf takes care of detection if we are on x86 system. I propose to remove this option and rely only on auto-detection, it proved itself when building docker images for other architectures.
**jemalloc**/**tcmalloc**|optional, but hidden|remove support|We have only one brief note about supporting both, but even we don't use it for our only binary packaging scenario - docker images. And even that documentation note says that there is no benefit in using them. So if there is no benefit for users then it only gives us maintenance overhead.

I need opinions on this from people who are developing netdata code written in C. @ktsaou @cakrit @vlvkobal @mfundul please voice your concerns. From packaging perspective we are not using any of those and our docs are prepared for a long time when it comes to removal of those options.

##### Expected behavior
- Libraries which we are saying in docs that are required aren't optional in build system. 
- LTO is enabled for "production" packages and not enabled when building by hand.
- Unused options are removed from `configure.ac` and from shell installation script.

**Comment by Ferroin** [comment]
Regarding LTO, do we know for certain if Netdata builds correctly with current versions of Clang/LLVM?  If we don't know, we should probably check that.  Clang support is kind of important if we want to properly support certain non-Linux platforms (and is also kind of important if we want truly universal Linux support), and while Clang does provide LTO support in recent versions, it doesn't behave exactly the same as GCC/binutils LTO functionality.  Even if we do decide to force LTO usage for GCC and Clang, we should still have it depend on the compiler supporting it (even if we support no other compilers ourselves, there's no reason we should actively break them either).

---

Regarding the alternate malloc libraries, I generally agree, but I do think we should continue to avoid assuming that glibc's (arguably sometimes broken) `malloc()` semantics are the case.  Doing that should be easy, and it will help significantly with portability.

**Comment by paulfantom** [comment]
> do we know for certain if Netdata builds correctly with current versions of Clang/LLVM?

LTO is enabled by default with every installation using our shell scripts and we don't have any reports on clang usage or problems related to it. So for me it looks like either no one is using clang to compile netdata or lto is working fine with clang. Both ways are still allowing to remove conditional lto usage.

**Comment by Ferroin** [comment]
> LTO is enabled by default with every installation using our shell scripts and we don't have any reports on clang usage or problems related to it. So for me it looks like either no one is using clang to compile netdata or lto is working fine with clang. Both ways are still allowing to remove conditional lto usage.

Unless I'm misreading our configure scripts, LTO is enabled by default _if the compiler supports it_.  So there's also the possibility that autoconf generated config scripts blacklist Clang for LTO and therefore it's never been tested.

Either way, I'll look at running a test build with Clang some time in the near future and see if anything breaks.  I doubt that there will be any issues, but I think it's still worth checking.

**Comment by paulfantom** [comment]
> LTO is enabled by default if the compiler supports it.

This won't change, method `AX_CHECK_COMPILE_FLAG` to check for lto will still be there. All I want is to remove as much optional flags as possible without affecting majority of user installations. 
I wasn't clear enough and sorry for that.

**Comment by vlvkobal** [comment]
> So for me it looks like either no one is using clang to compile netdata or lto is working fine with clang.

LTO is disabled when netdata is compiled with Clang on FreeBSD.

```
configure:7941: checking whether C compiler accepts -flto
configure:7960: cc -c -O2 -I/usr/local/include -D_THREAD_SAFE -pthread  -flto  conftest.c >&5
configure:7960: $? = 0
configure:7969: result: yes
configure:7983: checking if -flto builds executables
configure:7999: cc -o conftest -O2 -I/usr/local/include -D_THREAD_SAFE -pthread -flto    -I/usr/local/include/uuid -I/usr/local/include      conftest.c   >&5
/usr/bin/ld: unrecognized option '-plugin'
/usr/bin/ld: use the --help option for usage information
cc: error: linker command failed with exit code 1 (use -v to see invocation)
configure:7999: $? = 1
configure: program exited with status 1
configure: failed program was:
...
configure:8009: result: no
```

**Comment by paulfantom** [comment]
As I said, autoconf still will be responsible for choosing if LTO is available. Issue here is about removing a flag passed to `./configure` script and/or to `netdata-installer.sh`.

In the future we can talk about clang compatibility, but let's not do this here as this issue is not about it. Of course everyone is free to create an issue for that :smile:

**Comment by williamleuschner** [comment]
So far, the only issue I've found with building netdata using clang is an additional few warnings about losing a `const` in a function call and probably misusing `strncpy`. However, I haven't yet successfully run a version of netdata I compiled with clang, because I haven't gotten the packaging stuff working yet, and that causes netdata to bail out—files it expects to exist, don't.

**Comment by amoss** [comment]
Closed as the investigation has been completed in #4310, and the work will be tracked in #7144.
