### ISSUE TITLE
Raspberry pi3 b+ Raspberry resets the configuration files

### ISSUE THREAD

**Issue by ch3p4ll3** [netdata/netdata#5160]
hi, I installed netdata on a Raspberry pi3 b+. The problem is that when I edit the python.d.conf and charts.d.conf files to get the temperature sensor reading. if I restart the Raspberry it is as if the configuration files are reset and I no longer have the sensor reading. To get it back to work I have to go back to editing the files. It's normal?

Thanks in advance

**Comment by cakrit** [comment]
First, are you using /etc/netdata/edit-config so that the stock configuration files are copied to /etc/netdata? This will ensure that your files don't get changed.
However, I'm not sure why a restart would cause a newly edited file to revert to a previous state, it sounds strange, as if it's loading a static 'image' each time.

**Comment by ch3p4ll3** [comment]
could it be the cache of my browser?

**Comment by cakrit** [comment]
You wouldn't suddenly lose something you were already seeing and the shown charts are dynamic anyway (i.e. don't depend on the browser cache). Can you tell us what exactly it is that your are editing and the location of those files? Then show what those files look like, after the restart.

**Comment by ch3p4ll3** [comment]
I used this guide: https://docs.netdata.cloud/docs/netdata-for-IoT

as written on the site I modified the file in /usr/lib/netdata/conf.d/python.d.conf adding a line at the end with 'sensors: no'. In the file in /usr/lib/netdata/conf.d/charts.d.conf I added 'sensors: force' to the end. When I restart sometimes these changes I make to the files disappear

**Comment by ch3p4ll3** [comment]
Thank you very much
