### ISSUE TITLE
Correct way to alert on undefined status?

### ISSUE THREAD

**Issue by KlausBuchegger** [netdata/netdata#5170]
##### Question summary
Hi, I'm creating a custom plugin for my setup and I'd like to know how to trigger an alert if the plugin is not providing data for x seconds (i.e. the badge is light grey). My pluging is requesting data from a custom service via a HTTP request, and I'd like to be notified if this service is not responding. 

I can detect the problem in my plugin, but I'm unsure on how to actually handle it. I tried setting the data to None in that case, but it just caused my plot to pause until new data is received. Then the plot jumps and I get an empty area for the time the service was unavailable. The plotting behaviour is somewhat okay, I just need to be able to trigger on it. But, if the plot would continue to move, this would be even better. So just shift the previous data to the left, and leaving the new data empty.

##### OS / Environment
I'm writing the plugin using python, everything else should be independant of my environment.

**Comment by Ferroin** [comment]
Take a look at https://github.com/netdata/netdata/blob/master/health/health.d/nginx.conf for an example of the preferred approach for this type of thing.

In essence, do what you're already doing in your plugin (reporting `None` for the data when you can't get data), and then configure an alarm like the one linked above to trigger if there has been no data provided in some period of time.

**Comment by KlausBuchegger** [comment]
Perfect, this is what I was looking for. And as I just checked the Expressions part of the documentation, to find info about $last_collected_t I realized that my question is solved by the very first example on that page. Now I feel kind of stupid ;)

Anyway, thank you very much for this quick response.
