### ISSUE TITLE
netdata-updater.sh doesn't have exec perms

### ISSUE THREAD

**Issue by claytondukes** [netdata/netdata#5175]
##### Bug report summary
After fresh install a few days ago, I notice that my cron job isn't working.

As per the readme, I set: 

```
0 6 * * * /usr/src/netdata.git/packaging/installer/netdata-updater.sh
```
But now I see that it doesn't have exec bit set:

```
root@pve0 [installer]: # ./netdata-updater.sh
-su: ./netdata-updater.sh: Permission denied
root@pve0 [installer]: # ll
total 88K
drwxr-xr-x 2 root root 4.0K Jan 10 13:13 ./
drwxr-xr-x 6 root root 4.0K Jan 14 06:25 ../
-rw-rw-r-- 1 root root  277 Jan 14 06:25 .environment.sh
-rw-r--r-- 1 root root  20K Jan 10 13:12 functions.sh
-rw-r--r-- 1 root root    0 Jan 10 13:12 .keep
-rwxr-xr-x 1 root root  11K Jan 10 13:12 kickstart.sh*
-rwxr-xr-x 1 root root 6.5K Jan 10 13:12 kickstart-static64.sh*
-rw-r--r-- 1 root root 3.5K Jan 10 13:12 netdata-uninstaller.sh
-rw-r--r-- 1 root root 3.1K Jan 10 13:12 netdata-updater.sh
-rw-r--r-- 1 root root  19K Jan 10 13:12 README.md
-rw-r--r-- 1 root root 1.2K Jan 10 13:12 UNINSTALL.md
-rw-r--r-- 1 root root 2.8K Jan 10 13:12 UPDATE.md
```
But I also get this:

```
root@pve0 [installer]: # bash -x ./netdata-updater.sh
+ force=0
+ '[' '' = -f ']'
+ REINSTALL_PWD=THIS_SHOULD_BE_REPLACED_BY_INSTALLER_SCRIPT
+ cd THIS_SHOULD_BE_REPLACED_BY_INSTALLER_SCRIPT
./netdata-updater.sh: line 17: cd: THIS_SHOULD_BE_REPLACED_BY_INSTALLER_SCRIPT: No such file or directory
+ exit 1
```
Seeing this makes me think there's another `netdata-updater.sh` somewhere, but `find / -name netdata-updater.sh` yields nothing.

Netdata installed with no errors - I used the kickstart method:

```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

##### OS / Environment
Ubuntu 18.04

##### Steps To Reproduce
New install using the kickstart method

**Comment by paulfantom** [comment]
You shouldn't run `./netdata-updater.sh` located in netdata repository. Updater is installed by installer when using flag `--auto-update` (https://github.com/netdata/netdata/blob/master/netdata-installer.sh#L115) and placed in your cron directory.

Running updater from netdata repository file is currently unsupported.

**Comment by claytondukes** [comment]
Sorry for my confusion, but if I installed using `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`, then how would I add that switch?

**Comment by paulfantom** [comment]
By default `kickstart.sh` executes `netdata-installer.sh` with `-u` flag (same as `--auto-update`).

**Comment by claytondukes** [comment]
So I should already have auto-update? None of the 10 or so servers I installed on have a cron entry, and all servers are telling me there's an update available.

**Comment by paulfantom** [comment]
> So I should already have auto-update?

Yes, you should. If you don't then there is some sort of a bug. Could you try reinstalling netdata from current master branch (`bash <(curl -Ss https://my-netdata.io/kickstart.sh)` should do the trick)? After that please check if you have `/etc/cron.daily/netdata-updater` or `/etc/periodic/daily/netdata-updater`.

**Comment by claytondukes** [comment]
Well, re-running it did add it to `/etc/cron.daily/netdata-updater`. Odd that on a fresh install it didn't. I can see maybe a one-off, but I put netdata on about 10 servers the other day and none of them have it.

**Comment by claytondukes** [comment]
Ugh, after 25 years of being a sysadmin, it appears I am getting senile. I have *no idea* why the hell I only looked in `/etc/cron.d` and `/etc/cron.daily`. I can't apologize enough for wasting your (and mine) time :)
<facepalm>

**Comment by paulfantom** [comment]
Happy to help! :tada:

I am closing this as it seems to be solved.
