### ISSUE TITLE
SSL support for Elasticsearch plugin

### ISSUE THREAD

**Issue by NetwarSystem** [netdata/netdata#5179]
I am running Elasticsearch 6.5.x in standalone configs and as a small cluster. We have started to use Search Guard for authentication/authorization, and it enforces SSL use on port 9200, as well as userID/password.

How would one add SSL support? I have examined the elasticsearch.conf files for Netdata and there isn't any obvious way of doing this.

**Comment by ilyam8** [comment]
Hi. What's your `netdata` version?
