### ISSUE TITLE
Netdata registry with basic auth (behind nginx proxy) results in error 409

### ISSUE THREAD

**Issue by WoLpH** [netdata/netdata#5180]
##### Bug report summary

I've been attempting to debug this issue for some time but I haven't been able to get anywhere... For some reason whenever I try to proxy the netdata registry server throug nginx it results in the dreaded: `ERROR 409: Cannot ACCESS netdata registry: http://... responded with: {"status":"redirect","registry":"http://..."}`

Strangely enough, when I look in the network tab of the browser debugger (in all of the browers I've tested) I don't see any failed responses or redirects at all. Both the Nginx log and the netdata log don't show any non-200 responses either.

Accessing the registry on port 19999 straight away works perfectly.

I've read the following issues (and have all cookies enabled) but it appears to have no effect:
 - https://github.com/netdata/netdata/issues/3618
 - https://github.com/netdata/netdata/issues/778
 - https://github.com/netdata/netdata/issues/2131
 - https://github.com/netdata/netdata/issues/3394

##### OS / Environment

Ubuntu 16.04.5 with Netdata installed (and updated today) using the [One line installation](https://docs.netdata.cloud/packaging/installer/#one-line-installation)
Nginx 1.10.3
Browsers:
 - Chrome 71.0.3578.98
 - Firefox Developer Edition 65.0b11 (64-bit)
 - I even tried Microsoft Edge on a different computer

I've tried both with and without https and with and without cloudflare proxying.

##### Component Name

Registry

##### Steps To Reproduce

1. Install Netdata
2. Set up netdata to create a registry on a custom domain
3. Proxy netdata registry through Nginx

Nginx config:
```
upstream netdata {
    server 127.0.0.1:19999;
    keepalive 1024;
}

server {
    listen 80;
    include snippets/auth.conf;
    include snippets/auth_location.conf;

    server_name netdata.domain.tld;

    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://netdata;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        gzip on;
        gzip_proxied any;
        gzip_types *;

        # Block any HTTP requests other than GET, HEAD, and OPTIONS
        limit_except GET HEAD OPTIONS {
            deny all;
        }
    }

    # WordPress Pingback Request Denial
    if ($http_user_agent ~* "WordPress") {
        return 403;
    }

}
```

Relevant netdata settings:
```
[web]
    disconnect idle clients after seconds = 3600
    respect do not track policy = no
    enable gzip compression = no

[registry]
    enabled = yes
    registry to announce = http://netdata.domain.tld
```

Just to be certain I've tried several different Nginx configs. The basic "virtual host" config from the wiki: https://docs.netdata.cloud/docs/running-behind-nginx/
And also the high performance netdata: https://docs.netdata.cloud/docs/high-performance-netdata/

##### Expected behavior

No errors like:
```
ERROR 409: Cannot ACCESS netdata registry: http://netdata.domain.tld responded with: {"status":"redirect","registry":"http://netdata.domain.tld"}
ERROR 409: Cannot ACCESS netdata registry: http://netdata.domain.tld responded with: {"status":"redirect","registry":"http://netdata.domain.tld"}
ERROR 409: Cannot ACCESS netdata registry: http://netdata.domain.tld responded with: {"status":"redirect","registry":"http://netdata.domain.tld"}
```

**Comment by ktsaou** [comment]
Hi,

Netdata registry sends `redirect` when you access the registry without a cookie. So, the registry sets the cookie and asks the web browser to `redirect` back to itself. The dashboard does this 3 times before giving up.

So, it seems that your web browser does not accept the cookie.
Could you please press F12 on your browser, switch to the `network` tab and find the requests sent to the registry? Do the have cookies at their HTTP headers?

**Comment by WoLpH** [comment]
Yes, I see both the `set-cookie` headers and the cookie responses:

![image](https://user-images.githubusercontent.com/270571/51278427-da724e80-19da-11e9-944b-5a8dd0fd2d3b.png)

The request and response headers for the first request:
Request:
```
:method: GET
:path: /api/v1/registry?action=access&machine=472499ec-e91c-11e8-bb14-0a1c68f9ddef&name=logger-00&url=https%3A%2F%2Fnetdata.domain.tld%2F&_=1547672664175
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en;q=0.9,en-US;q=0.8,nl;q=0.7,en-NL;q=0.6,nl-NL;q=0.5
authorization: Basic YWRtaW46eE5MdUJBNWVMcg==
cache-control: no-cache, no-store
cookie: netdata_registry_id=give-me-back-this-cookie-now--please; netdata_registry_id=give-me-back-this-cookie-now--please; netdata_registry_id=give-me-back-this-cookie-now--please; __cfduid=d82b80ae9007540f0a8a32b7f624d86c71547672557
dnt: 1
pragma: no-cache
referer: https://netdata.domain.tld/
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
x-requested-with: XMLHttpRequest
```

Response 1:
```
access-control-allow-credentials: true
access-control-allow-origin: *
cache-control: public
cf-ray: 49a388d16af5c849-AMS
content-encoding: br
content-type: application/json; charset=utf-8
date: Wed, 16 Jan 2019 21:04:25 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Thu, 17 Jan 2019 21:04:25 GMT
server: cloudflare
set-cookie: netdata_registry_id=give-me-back-this-cookie-now--please; Expires=Thu, 16 Jan 2020 21:04:25 GMT
status: 200
strict-transport-security: max-age=15552000; preload
x-content-type-options: nosniff
```

Response 2:
```
access-control-allow-credentials: true
access-control-allow-origin: *
cache-control: public
cf-ray: 49a388d1bc58c849-AMS
content-encoding: br
content-type: application/json; charset=utf-8
date: Wed, 16 Jan 2019 21:04:25 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Thu, 17 Jan 2019 21:04:25 GMT
server: cloudflare
set-cookie: netdata_registry_id=give-me-back-this-cookie-now--please; Expires=Thu, 16 Jan 2020 21:04:25 GMT
status: 200
strict-transport-security: max-age=15552000; preload
x-content-type-options: nosniff
```

Response 3:
```
access-control-allow-credentials: true
access-control-allow-origin: *
cache-control: public
cf-ray: 49a388d1dcf4c849-AMS
content-encoding: br
content-type: application/json; charset=utf-8
date: Wed, 16 Jan 2019 21:04:25 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Thu, 17 Jan 2019 21:04:25 GMT
server: cloudflare
set-cookie: netdata_registry_id=give-me-back-this-cookie-now--please; Expires=Thu, 16 Jan 2020 21:04:25 GMT
status: 200
strict-transport-security: max-age=15552000; preload
x-content-type-options: nosniff
```

**Comment by cakrit** [comment]
I think I see the problem. It looks like the cookie perser in https://github.com/netdata/netdata/blob/master/web/api/web_api_v1.c#L538 is a bit simplistic and doesn't handle well the following:
```
cookie: netdata_registry_id=give-me-back-this-cookie-now--please; netdata_registry_id=give-me-back-this-cookie-now--please; netdata_registry_id=give-me-back-this-cookie-now--please; __cfduid=d82b80ae9007540f0a8a32b7f624d86c71547672557
```
I will attempt to replicate this by issuing a request locally with a similar header, to see what ends up in `person_guid` in L540.

**Comment by cakrit** [comment]
Scratch the last comment, I just tested it and it's parsed perfectly. I'll look a bit more...

**Comment by cakrit** [comment]
I set up an nginx proxy exactly with your settings, configured the local netdata registry the same way and  issued a request with all your headers, using curl. I still got a valid response, which is not what you're getting. See it here:

https://pastebin.com/dpADubUp

The second part in that paste bin show what you're getting back, simulated by not sending cookies.
 I really don't get how with the same config we can get different results.I can suggest two things:
- Upgrade your netdata if you have an old one
- Add an access log that records the headers sent from nginx to netdata. 

Note that the only thing I did not do was to add basic auth, but that's really irrelevant.

**Comment by WoLpH** [comment]
> Note that the only thing I did not do was to add basic auth, but that's really irrelevant.

Just to rule it out I tested it. And that solves it... as soon as I disable basic auth I have no issues anymore.

**Comment by cakrit** [comment]
Incredible, let me see what on earth that does...

**Comment by WoLpH** [comment]
I've investigated a bit further and it seems I don't have this issue everywhere. I have 3 separate registries running on separate locations with nearly identical configurations (why invent the wheel twice, right?). Only 1 of the 3 netdata instances has this issue so I'll continue my testing to see if I can find the cause.

The non-working version:
Ubuntu 16.04.5 LTS
nginx/1.10.3 (Ubuntu)
netdata v1.12.0-rc2-51-nightly

The working versions:

Ubuntu 16.04.5 LTS
nginx/1.13.12
netdata v1.12.0-rc2-52-g61e3100

FreeBSD bsd 11.2-RELEASE
nginx/1.14.1
netdata 1.10.0

I'll try upgrading some thing to see if that changes anything

**Comment by WoLpH** [comment]
After updating the 2nd Ubuntu server to v1.12.0-rc2-51-nightly I can replicate the issue on that machine. So somewhere between v1.12.0-rc2-52-g61e3100 and v1.12.0-rc2-51-nightly this broke somehow.

**Comment by cakrit** [comment]
Very nice. Any chance you can get that access log from the problematic nightly and create an issue for the Ubuntu maintainers? I'm sure they will want to investigate it.

**Comment by WoLpH** [comment]
Well, got slightly further and for some reason the update wasn't working so I manually removed netdata completely (i.e. using the `/usr/src/packaging/installer/netdata-uninstaller.sh` script because the update removed the regular `netdata-uninstaller.sh` script).

After that I did a regular install and restored the config from the previous install. Still the same problem.

Something could still seems to be broken with the latest versions though, can I assume that the `/etc/cron.daily/netdata-updater` should be safe to execute from a shell?

At the end of a (seemingly) succesful run I see the following:
```
Uninstall script is located at: ./netdata-uninstaller.sh
 --- Installing new netdata-updater in cron ---
sed: can't read ./packaging/installer/netdata-updater.sh: No such file or directory
Update script is located at /etc/cron.daily/netdata-updater
```

It seems to be using the wrong working directory somewhere in the script since it assumes to be in `/usr/src/netdata.git`. I executed the `/etc/cron.daily/netdata-updater` script both from `/root/` and `/usr/src/netdata.git` so the current working directory is not relevant to the case.

I can replicate that behaviour on both of the Ubuntu machines.


As for the bug I'm trying to hunt down. I've got both of the Ubuntu machines at v1.12.0-rc3-3-g711dbd7 now and one is working, the other isn't. With the working machine I did wipe the config since it was pretty much vanilla so that could be the difference. The search continues, might be tomorrow before I update again ;)

**Comment by WoLpH** [comment]
> Very nice. Any chance you can get that access log from the problematic nightly and create an issue for the Ubuntu maintainers? I'm sure they will want to investigate it.

I'm not running an ubuntu specific version so I don't think it's ubuntu specific. And the FreeBSD machine runs off the standard package so it probably doesn't have the issue yet.

I'll see if I can trace it to a commit using a `git bisect` if I can figure out how to quickly rebuild without too much hassle :)

**Comment by WoLpH** [comment]
The bisect took some time (clean, recompile... etc) but I found it. This commit broke it: https://github.com/netdata/netdata/commit/08649bec373555144878b4314e87c9a8eb38c82e

It's not a small commit unfortunately, it's quite a bit to look through.

Additionally, I've isolated the part in the config that breaks it. A stock config with these flags enabled breaks it:
```
[registry]
    enabled = yes
    registry to announce = http://netdata.domain.tld
    verify browser cookies support = yes
```

**Comment by cakrit** [comment]
I will get on it ASAP, I've done that commit and will find out what causes the issue. Enabling authentication to try it out.

**Comment by cakrit** [comment]
I found the bug, fixing it.

**Comment by WoLpH** [comment]
Great! Thanks for the quick help :)

**Comment by cakrit** [comment]
I created PR 5216, please verify that it works for you too.

**Comment by WoLpH** [comment]
Yes, working great. Thanks for the quick fix :)

**Comment by cakrit** [comment]
I just did another change on that PR, so that the new management API can work behind an authenticated proxy as well, by using 'X-Auth-Token' instead of the 'Authorization' header.

I appreciate your help in tracking this down, it was tricky.

**Comment by johnramsden** [comment]
This seems to be affecting me when attempting to sign in to netdata.cloud. It says it's trying to authorize myurl.com, and it's missing the /netdata at the end of the URL. When I accept the email notification it sends me to myurl.com instead of myurl.com/netdata.

Relevant nginx configuration:

```
    location /netdata/ {
        auth_basic "Restricted";
        auth_basic_user_file auth.passwd;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:19999/;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        access_log off;
    }
```

**Comment by gmosx** [comment]
@johnramsden Thank you for the detailed report. Will try to resolve this.
