### ISSUE TITLE
Hide: timestamps, memory values left, background and use graph as a gif

### ISSUE THREAD

**Issue by Macley-Kun** [netdata/netdata#5186]
##### Question summary
Hi, i'm currently making a graph here: https://gremagol.com/westest/
And i'm trying the following i haven't found in the docs:

1. Hiding the values on the left side of a graph.
2. Hiding the values on the bottom of a graph (timestamps).
3. Hiding the squared background behind a graph.
4. If, the graph is done, i would like to use it on a different site, where it's displayed as a gif. So users can't scroll in it, and it resizes a bit easier (for me).

I know it's alot of questions, but i hope it's possible to edit the graph in such a way that i could use it for my website.
##### OS / Environment
Ubuntu 18.04
##### Component Name
Customdashboard/web/API

**Comment by Macley-Kun** [comment]
Current graph is deleted, i've moved to heroku and no longer can/need Netdata.
Never the less the suggestion can be implemented, it's ok if you want to close it ^_^

Thanks everyone for all their help 0/ gl with the project

**Comment by cakrit** [comment]
Marking it as a feature request. If you don't mink @Macley-Kun , could you [fill in our survey](https://docs.google.com/forms/d/1lXKZd8YOKJxF1clQHkv8N1tx2rF4PqPjhRwLYDceA3g/edit)? Feedback from users who have decided to use something else is invaluable.

**Comment by Macley-Kun** [comment]
Done! Thx

Met vriendelijke groet,

Wesley de Vree

________________________________
Van: Chris Akritidis <notifications@github.com>
Verzonden: vrijdag, maart 22, 2019 2:57 PM
Aan: netdata/netdata
CC: Macley; Mention
Onderwerp: Re: [netdata/netdata] Hide: timestamps, memory values left, background and use graph as a gif (#5186)


Marking it as a feature request. If you don't mink @Macley-Kun<https://github.com/Macley-Kun> , could you fill in our survey<https://docs.google.com/forms/d/1lXKZd8YOKJxF1clQHkv8N1tx2rF4PqPjhRwLYDceA3g/edit>? Feedback from users who have decided to use something else is invaluable.

―

**Comment by cakrit** [comment]
Thank you for your time!
