### ISSUE TITLE
megacli isn't included in python.d.conf

### ISSUE THREAD

**Issue by petarkozic** [netdata/netdata#5191]
I updated netdata to latest version on server where I have megacli module.

After update megacli isn't work. On debug I saw that megacli isn't enabled by default

`python.d INFO: plugin: main: module 'megacli' disabled by default`

I tried to find in python.d.conf to enable but there is no megacli in list.
I added manually and restart netdata, after that megacli works.

Please, include megacli in python.d.conf.

**Comment by petarkozic** [comment]
@ilyam8 
Also, adaptec_raid
I checked now on second server.

**Comment by ilyam8** [comment]
@petarkozic thx for reporting
