### ISSUE TITLE
python.d/nginx.conf doesn't exist

### ISSUE THREAD

**Issue by elfeffe** [netdata/netdata#5192]
I have found many tutorials about how to check php-fpm and nginx using netdata.
They always refer to a file located in /etc/netdata/python.d/nginx.conf but that file doesn't exist.
Where are the conf files located?
How to enable php-fpm and nginx cheking?
I had netdata installed from 6 months ago, uninstall script is not located anywhere, even with today git pull.
So I stopped netdata and renamed /etc/netdata to /etc/netdatabu and reinstalled it using bash <(curl -Ss https://my-netdata.io/kickstart.sh)

I see mysql, mongodb, redis. But no nginx or php-fpm

**Comment by ilyam8** [comment]
Hi @elfeffe 

Stock configuration directory is `/usr/libexec/netdata/conf.d`

You need to copy it to ` /etc/netdata/python.d/` yourself or use helper [edit-config](https://github.com/netdata/netdata/pull/4338) script (it is in `/etc/netdata`)

**Comment by elfeffe** [comment]
edit-config did the trick
