### ISSUE TITLE
Split go.d plugin into two packages

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5195]
#### Feature idea summary
Create separate library (modules vs orchestrator)
Test it with the Oracle module as stand-alone

**Comment by paulfantom** [comment]
Why it is here and not in go.d.plugin issues?

**Comment by ilyam8** [comment]
ye
i will move it

**Comment by ilyam8** [comment]
orchestrator 
https://github.com/netdata/go-plugin

**Comment by ilyam8** [comment]
Simplest plugin example
https://github.com/netdata/go-plugin/blob/master/examples/simple/main.go

> Test it with the Oracle module as stand-alone

We don't need orcaledb module as a standalone plugin, we will have `cgo.d.plugin` and it will be a part of it. At least that is the plan.

**Comment by paulfantom** [comment]
please rename it to something less confusing. We have `go.d.plugin` and now `go.plugin`, it will be very confusing to users.

**Comment by ilyam8** [comment]
Oh, yes. Any suggestions? `orchestrator` is a bit long

**Comment by ilyam8** [comment]
> go.plugin,

Keep in mind it is a library, we don't have `go.plugin`. We have plugins and modules. `go-plugin` is a plugin using this terms.

**Comment by paulfantom** [comment]
`go-orchestrator` is ok

**Comment by ilyam8** [comment]
ok ok ok

**Comment by Wing924** [comment]
why not use mono repo with 2 main package? one for no cgo, the other for cgo.
many repo make dep management very difficult.

**Comment by gmosx** [comment]
The `go-` prefix makes me think it's a general-purpose (i.e. not netdata-specific) library for Go. 
Also, I don't like the name orchestrator. However, I cannot offer a better suggestion atm, will need to think some more about it.

**Comment by ilyam8** [comment]
> Create separate library (modules vs orchestrator)

Created. Integration will be later.
