### ISSUE TITLE
GUI links to github wiki

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#5202]
##### Bug report summary
Pressing a button with GitHub logo in netdata dashboard links to unused github wiki. It should probably link to repo instead

##### OS / Environment
all

##### Component Name
web GUI

##### Steps To Reproduce
1. Go to netdata dashboard
2. Click on a button with github logo (top right corner)

##### Expected behavior
Button doesn't link to unused wiki

**Comment by cakrit** [comment]
I agree. It's a very easy change.

**Comment by gmosx** [comment]
Ok
