### ISSUE TITLE
Misleading information on memory consumption

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#5203]
##### Bug report summary
web GUI much lower memory consumption of netdata than it is in reality.
![screenshot_20190117_190615](https://user-images.githubusercontent.com/3531758/51338840-2bda1680-1a8b-11e9-9987-c55add0bbf16.png)

Chart shows constant memory consumption of a containerized netdata (only netdata running in that container) which averages at about 146MB. However info on the right says: "netdata on nas, collects [...] using 57 MB of memory for 1 hour [...]". Those two doesn't match.

##### OS / Environment
Official netdata container.

##### Component Name
Probably daemon

##### Steps To Reproduce
1. Run official netdata container
2. Go to webGUI

##### Expected behavior
One of:
1. chart and text show the same data
2. text is changed to say which component is actually using 57MB of memory

**Comment by Ferroin** [comment]
I'd argue in favor of option 2, as I'm fairly certain that data is about how much space the database is taking up in RAM (before KSM), and that actually can be very useful information.

On top of that though, option 1 will be difficult to implement, for that Netdata has to track the memory usage of itself, _and every single child it spawns_.  Even then, it probably won't exactly match the container's memory usage.
