### ISSUE TITLE
How to view history data?

### ISSUE THREAD

**Issue by Ansem93** [netdata/netdata#5206]
Hi, I wanted to try Netdata, but I want to have a 1year history.
I looked at this Issue: #397 . I think that's a good Idea.
I would love something like that.
Of course, for storage reason, data need to collected:
older 1 hour->1 minute
older 1 week ->5 minutes
older 1 month ->1 hours
older 1 year -> 1 day

This is an example, but I think that something like that should be integrated!

**Comment by cakrit** [comment]
#4687 is already being implemented. Stay tuned and please provide your feedback on the design you'll see on that issue.
Closing this one as duplicate.
