### ISSUE TITLE
netdata unable to start 

### ISSUE THREAD

**Issue by binglingziyu** [netdata/netdata#5210]
##### Netdata version
~# /usr/sbin/netdata -v
netdata 1.12.1

##### System Info
Linux VM-1-46-ubuntu 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##### Some Logs

● netdata.service - Real time performance monitoring
   Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-01-18 18:22:48 CST; 27s ago
  Process: 18720 ExecStart=/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep (code=exited, status=1/FAILURE)
  Process: 18717 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 18713 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 18710 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 18707 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 18720 (code=exited, status=1/FAILURE)

Jan 18 18:22:48 VM-1-46-ubuntu systemd[1]: netdata.service: Unit entered failed state.
Jan 18 18:22:48 VM-1-46-ubuntu systemd[1]: netdata.service: Failed with result 'exit-code'.

Jan 18 18:16:14 VM-1-46-ubuntu systemd[1]: Stopped Real time performance monitoring.
Jan 18 18:16:14 VM-1-46-ubuntu systemd[1]: Starting Real time performance monitoring...
Jan 18 18:16:15 VM-1-46-ubuntu systemd[1]: Started Real time performance monitoring.
Jan 18 18:16:15 VM-1-46-ubuntu systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 18:16:15 VM-1-46-ubuntu systemd[1]: netdata.service: Unit entered failed state.
Jan 18 18:16:15 VM-1-46-ubuntu systemd[1]: netdata.service: Failed with result 'exit-code'.
Jan 18 18:16:45 VM-1-46-ubuntu systemd[1]: netdata.service: Service hold-off time over, scheduling restart.
Jan 18 18:16:45 VM-1-46-ubuntu systemd[1]: Stopped Real time performance monitoring.
Jan 18 18:16:45 VM-1-46-ubuntu systemd[1]: Starting Real time performance monitoring...
Jan 18 18:16:45 VM-1-46-ubuntu systemd[1]: Started Real time performance monitoring.
Jan 18 18:16:45 VM-1-46-ubuntu systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 18:16:45 VM-1-46-ubuntu systemd[1]: netdata.service: Unit entered failed state.
Jan 18 18:16:45 VM-1-46-ubuntu systemd[1]: netdata.service: Failed with result 'exit-code'.

**Comment by paulfantom** [comment]
There is no netdata `1.12.1` version. Could you give us more information on how you  build/installed netdata?

**Comment by binglingziyu** [comment]
[Install Netdata on Linux manually](https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually)
```
# download it - the directory 'netdata' will be created
git clone https://github.com/netdata/netdata.git --depth=100
cd netdata

# run script with root privileges to build, install, start Netdata
./netdata-installer.sh
```

**Comment by cakrit** [comment]
It looks like you have another netdata process running (though I expected a message telling you netdata can't bind to 19999). Please do `sudo killall netdata`, restart with systemctl and send the latest entries in `/var/log/netdata/error.log` if you still have a problem.
