### ISSUE TITLE
Netdata notifies about slowqueries but mariadb doesn't log queries on every notification

### ISSUE THREAD

**Issue by dagumar** [netdata/netdata#5224]
##### Bug report summary
It seems to be that netdata is seeing some queries as slow queries but mariadb isn't and it doesn't write to the log. For this reason, I can't address which query is messing with my db.

Some other queries are notified by netdata and logged to the slow queries log, I thing this is the normal behavior.
This is netdata's log of raised alarms.
4:10:30	mysql_local.queries	mysql 10s slow queries	0 slow queries	CLEAR
4:10:20	mysql_local.queries	mysql 10s slow queries	551 slow queries	CRITICAL
1:37:40	mysql_local.queries	mysql 10s slow queries	0 slow queries	CLEAR
1:37:30	mysql_local.queries	mysql 10s slow queries	10 slow queries	WARNING
##### OS / Environment
Debian 9
##### Netdata version (ouput of `netdata -V`)
Versions: 10.1.37-MariaDB-0+deb9u1 Debian 9.6
Your netdata version: v1.12.0-rc2-51-nightly

Any help would be appreciated.

Regards.

**Comment by dagumar** [comment]
Hello,

It seems to be that netdata is seeing some queries as slow queries but mariadb isn't and it doesn't write to the log. For this reason, I can't address which query is messing with my db.

Some other queries are notified by netdata and logged to the slow queries log, I thing this is the normal behavior.


This is netdata's log of raised alarms.
4:10:30	mysql_local.queries	mysql 10s slow queries	0 slow queries	CLEAR
4:10:20	mysql_local.queries	mysql 10s slow queries	551 slow queries	CRITICAL
1:37:40	mysql_local.queries	mysql 10s slow queries	0 slow queries	CLEAR
1:37:30	mysql_local.queries	mysql 10s slow queries	10 slow queries	WARNING

Alarm raised at 04:10 has a slow query in mariadb's logs but alarm raised at 01:37 hasn't.

Versions: 10.1.37-MariaDB-0+deb9u1 Debian 9.6
Your netdata version: v1.12.0-rc2-51-nightly

Any help would be appreciated.

Regards.

**Comment by ilyam8** [comment]
Hi @dagumar 

> It seems to be that netdata is seeing some queries as slow queries

Netdata's mysql module does `SHOW GLOBAL STATUS;` query.

Response contains 
https://github.com/netdata/netdata/blob/b537efdbef909375f4a9f74c258028b02d75f40a/collectors/python.d.plugin/mysql/mysql.chart.py#L20

That is the alarm

https://github.com/netdata/netdata/blob/b537efdbef909375f4a9f74c258028b02d75f40a/health/health.d/mysql.conf#L16-L28

**Comment by dagumar** [comment]
Understood. You are saying that netdata is notifying correctly about the slow queries but mariadb is not logging every slow query. Maybe I have to do a deep research in order to address why mariadb is not logging.

Thanks for your help!

**Comment by ilyam8** [comment]
@dagumar you are welcome!

> You are saying that netdata is notifying correctly about the slow queries but mariadb is not logging every slow query.

Actually it's very interesting. Maybe netdata too paranoid about `slow_queries` :thinking: 
@Ferroin 

> Maybe I have to do a deep research in order to address why mariadb is not logging.

If you will find something please report back.

i am closing the issue. Feel free to reopen :smile:
