### ISSUE TITLE
Collection interval configuration to reduce memory

### ISSUE THREAD

**Issue by gvsrini** [netdata/netdata#5227]
I am interested in monitoring (specifically, memory consumption of) only one process. To achieve this, I need data over a reasonably good period of time, say, around a week.

I was thinking if collection time could be increased (to 10s instead of 1s) for all other data points except the process I am interested, that should be good enough. 

For my process, I would like to retain 1s granularity for at least a week. More will be better.

Is there a way I can achieve it without too much work?

**Comment by cakrit** [comment]
Unfortunately it's not possible yet, but it's top priority to address this deficiency. In #4687 we are designing a new DB format to permit very long retention of metrics. Development will begin soon.  I will close this as duplicate, but monitor that issue and you'll see progress in the next couple of months.
