### ISSUE TITLE
Updater script no longer seems to be working after a recent update

### ISSUE THREAD

**Issue by jorisvervuurt** [netdata/netdata#5228]
I just tried to manually install an update of Netdata, but I noticed the `/usr/src/netdata.git/netdata-updater.sh` script immediately exits without actually doing anything.

I’ve tried re-running `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`, which starts fine but exits immediately after it runs the `./netdata-updater.sh -f` command. It shows ‘OK’ though...

I’m running the latest Ubuntu Desktop 18.04 LTS (Bionic Beaver).

**Comment by jpeizer** [comment]
I am having the same issue.  After looking into it, it appears at some point the updater file was emptied, and now reads 0 byte size.

**Comment by paulfantom** [comment]
We changed how updater works. It should be a file located in your daily cron directory and run by cron (usually `/etc/cron.daily/netdata-updater`). Running `./netdata-updater.sh -f` is no longer a recommended option.

Change was needed to remove dependency on having source code directory on hosts and decouple packaging from development. Right now updater is supposed to fetch tarballs from GCS, put them in temporary directory and rerun installer from there.

Sorry for inconvenience but this is a necessary step to have a gating jobs so we won't break user environments like it happened a couple weeks ago and like it seems that is happening now.

**Comment by paulfantom** [comment]
If you can, please temporarily use `https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/kickstart.sh` instead of `https://my-netdata.io/kickstart.sh`.

**Comment by koebi001** [comment]
This is on Debian stretch.
On all my hosts `/etc/cron.daily/netdata-updater` is a symbolic link to `/usr/src/netdata.git/netdata-updater.sh` which now is empty. and therefore produces lots of emails from cron.
A new unattended installation using the https://my-netdata.io/kickstart.sh is not working:
```bash
$ service netdata stop && rm -rf /usr/src/netdata.git && rm -rf /etc/netdata && rm -f /etc/cron.daily/netdata-updater
$ /bin/bash -c "bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait -u"
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version: 
 --- Downloading script to detect required packages... --- 
$'[\E[2m/tmp/netdata-kickstart-q2u1Zr\E(B\E[0m]# \E[1m\E[33m' wget -O - https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh $'\E(B\E[0m\\n' --2019-01-21 13:25:18--  https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41978 (41K) [text/plain]
Saving to: ‘STDOUT’

-                                              100%[===================================================================================================>]  40.99K  --.-KB/s    in 0.03s   

2019-01-21 13:25:18 (1.24 MB/s) - written to stdout [41978/41978]

 OK  wget -O - https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh 

 --- Running downloaded script to detect required packages... --- 
$'[\E[2m/tmp/netdata-kickstart-q2u1Zr\E(B\E[0m]# \E[1m\E[33m' /bin/bash /tmp/netdata-kickstart-q2u1Zr/install-required-packages.sh --dont-wait --non-interactive netdata $'\E(B\E[0m\\n' Loading /etc/os-release ...

/etc/os-release information:
NAME            : Debian GNU/Linux
VERSION         : 9 (stretch)
ID              : debian
ID_LIKE         : 
VERSION_ID      : 9

We detected these:
Distribution    : debian
Version         : 9
Codename        : 9 (stretch)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2 

 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'zlib1g-dev' is installed...
 > Checking if package 'uuid-dev' is installed...
 > Checking if package 'libmnl-dev' is installed...
 > Checking if package 'python-yaml' is installed...
 > Checking if package 'python-pymongo' is installed...

All required packages are already installed. Now proceed to the next step.

 OK  /bin/bash /tmp/netdata-kickstart-q2u1Zr/install-required-packages.sh --dont-wait --non-interactive netdata 

 WARNING  It failed to install all the required packages, but installation might still be possible. 

 ABORTED  Stopping due to non-interactive mode. Fix the issue or retry installation in an interactive mode. 

```

**Comment by koebi001** [comment]
If I run `kickstart.sh` now I get the following:
```bash
/bin/bash -c "bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait -u"
 --- Re-installing netdata... --- 
$'[\E[2m/root\E(B\E[0m]# \E[1m\E[33m' '' /etc/cron.daily/netdata-updater -f $'\E(B\E[0m\\n' /dev/fd/63: line 88: : command not found
 FAILED   /etc/cron.daily/netdata-updater -f 

 ABORTED  Failed to forcefully update netdata 

```
After deleting the link `/etc/cron.daily/netdata-updater` `kickstart.sh` repaired the setup
```bash
$ rm -f /etc/cron.daily/netdata-updater
$ /bin/bash -c "bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait -u"
```

**Comment by paulfantom** [comment]
Should be fixed by https://github.com/netdata/netdata/pull/5276

**Comment by paulfantom** [comment]
All problems reported in this issue should be already fixed. We are now waiting for propagation of `kickstart.sh` script to be available under https://my-netdata.io/kickstart.sh (new version has following md5sum: `f16d433f3fc86264fa2e05808369c54b`).

Thank you for your patience. If something still doesn't work please reopen this issue.
