### ISSUE TITLE
netdata docker container not showing disk space utilization for lvm mounts

### ISSUE THREAD

**Issue by autogun** [netdata/netdata#5231]
netdata in a docker container is executed with the command provided on the `README.md` and result shown below -
![image](https://user-images.githubusercontent.com/11921235/51443505-55e14200-1cf2-11e9-80d4-36ba583e8fd6.png)
None of the dm-X disks are showing disk utilization.

adding `  -v /:/host:ro` actually shows disk utilizatio for all mounts except root. Removing `ro` fixes that aswell but I feel kind uncomfortable mounting it all as `rw`
![image](https://user-images.githubusercontent.com/11921235/51443632-8b872a80-1cf4-11e9-9c6f-5127536af80b.png)

Is this a known issue?
Running on ubuntu 14.04

**Comment by cakrit** [comment]
Duplicate of #5071
