### ISSUE TITLE
I hope to increase support for multiple languages

### ISSUE THREAD

**Issue by Fhaohaizi** [netdata/netdata#5236]
I got a lot of help in the documentation in #279. I hope to add more support for the child nodes, thank the author.

**Comment by cakrit** [comment]
Thanks @Fhaohaizi, you can just create Pull Requests, whenever you have something to add.

**Comment by 247361153** [comment]
Legend 🎴

**Comment by Fhaohaizi** [comment]
> 感谢@Fhaohaizi，只要有需要添加的内容，您就可以创建Pull请求。

Hello, I have submitted a pull request. This is my first submission, if you have time, you can take a look.
https://github.com/netdata/netdata/pull/5257
