### ISSUE TITLE
web_log reports unmatched lines

### ISSUE THREAD

**Issue by bgfor** [netdata/netdata#5238]
web_log plugin reports unmatched lines.

This is my log:

```txt

10.xx.xx.xx - - [21/Jan/2019:08:59:54 +0100] "POST /jmx HTTP/1.1" 200 242 223 0.024 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:54 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:54 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:55 +0100] "POST /jmx HTTP/1.1" 200 219 197 0.025 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:55 +0100] "POST /jmx HTTP/1.1" 200 242 223 0.024 0.000, 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:55 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:55 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:56 +0100] "POST /jmx HTTP/1.1" 200 242 223 0.001 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:56 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:56 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:57 +0100] "POST /jmx HTTP/1.1" 200 242 223 0.001 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:57 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:57 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:58 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:58 +0100] "POST /jmx HTTP/1.1" 200 242 223 0.057 0.006 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:58 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:59 +0100] "POST /jmx HTTP/1.1" 200 242 223 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:59 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:08:59:59 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.001, 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:00 +0100] "POST /jmx HTTP/1.1" 200 242 223 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:00 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:00 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:03 +0100] "POST /jmx HTTP/1.1" 200 242 223 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:03 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.001 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:03 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.001 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:05 +0100] "POST /jmx HTTP/1.1" 200 1388 644 0.005 0.005 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:05 +0100] "POST /jmx HTTP/1.1" 200 1626 743 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:05 +0100] "POST /jmx HTTP/1.1" 200 2391 1097 0.002 0.002 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:05 +0100] "POST /jmx HTTP/1.1" 200 2391 1097 0.001 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:06 +0100] "POST /jmx HTTP/1.1" 200 242 223 0.001 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:06 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.002 0.001 "-" "-"
10.xx.xx.xx - - [21/Jan/2019:09:00:06 +0100] "POST /jmx HTTP/1.1" 200 1912 900 0.001 0.001 "-" "-"


```

**Comment by bgfor** [comment]
I also think that these two lines are a problem. 

The Nginx documentation says that:
Times of several responses are separated by commas and colons like addresses in the $upstream_addr variable.
http://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_response_time

It seems to me that your code can not process this value correctly.

**Comment by bgfor** [comment]
https://stackoverflow.com/questions/47185144/q-nginx-upstream-response-time-returns-2-values

Someone recommends turning off next_upstream, but this is not possible in my environment. I have up to six backends.

**Comment by ilyam8** [comment]
> 0.001, 0.001
How to calc uptime in this case? what do you think?

**Comment by bgfor** [comment]
The metric is called "average" so can it just calculate the average?
You can also make a dynamic number of indicators. If the second value appears, add a new indicator. But does it make sense?

**Comment by ilyam8** [comment]
> You can also make a dynamic number of indicators. If the second value appears, add a new indicator. 

in what cases it has more then one value? Why it asks second upstream?

**Comment by bgfor** [comment]
I started checking nginx, and in addition to $upstream_response_time, I also enabled saving $upstream_addr.
The results are surprising :)

`RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:43 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.002, BodyBytesSent: 1912, RequestTime: 0.002, RequestLength: 900, Body: [XXX], ContnetType: application/json, SourcePort: 50171, WhereToGo: [::1]:1311
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:43 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.001, BodyBytesSent: 1912, RequestTime: 0.001, RequestLength: 900, Body: [XXX], ContnetType: application/json, SourcePort: 50172, WhereToGo: [::1]:1312
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:44 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.002, BodyBytesSent: 242, RequestTime: 0.002, RequestLength: 223, Body: [XXX], ContnetType: application/json, SourcePort: 50172, WhereToGo: [::1]:1312
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:44 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.002, BodyBytesSent: 1912, RequestTime: 0.002, RequestLength: 900, Body: [XXX], ContnetType: application/json, SourcePort: 50171, WhereToGo: [::1]:1311
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:44 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.002, BodyBytesSent: 1912, RequestTime: 0.002, RequestLength: 900, Body: [XXX], ContnetType: application/json, SourcePort: 50172, WhereToGo: [::1]:1312
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:45 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.001, BodyBytesSent: 242, RequestTime: 0.001, RequestLength: 223, Body: [XXX], ContnetType: application/json, SourcePort: 50172, WhereToGo: [::1]:1312
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:45 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.000, 0.002, BodyBytesSent: 1912, RequestTime: 0.002, RequestLength: 900, Body: [XXX], ContnetType: application/json, SourcePort: 50171, WhereToGo: 127.0.0.1:1311, [::1]:1311
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:45 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.002, BodyBytesSent: 1912, RequestTime: 0.002, RequestLength: 900, Body: [XXX], ContnetType: application/json, SourcePort: 50172, WhereToGo: [::1]:1312
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:46 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.001, BodyBytesSent: 242, RequestTime: 0.001, RequestLength: 223, Body: [XXX], ContnetType: application/json, SourcePort: 50172, WhereToGo: [::1]:1312
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:46 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.001, BodyBytesSent: 1912, RequestTime: 0.001, RequestLength: 900, Body: [XXX], ContnetType: application/json, SourcePort: 50171, WhereToGo: [::1]:1311
RemoteIP: 10.xx.xx.xx, RemoteUser: -, Time: 21/Jan/2019:14:58:46 +0100, Request: POST /jmx HTTP/1.1, Response: 200, SSL: -, ResponseTime: 0.001, BodyBytesSent: 1912, RequestTime: 0.001, RequestLength: 900, Body: [XXX], ContnetType: application/json, SourcePort: 50172, WhereToGo: [::1]:1312`

Sometimes localhost is translated as both 127.0.0.1 and as ::1 (line 7)

Here's the answer. If there are two backends, there are two times in the log :-)

**Comment by bgfor** [comment]
Ok, the configuration problem was on my side. No longer occurs.

However, on the occasion, netdata also has some shortcomings ;)

Thanks for the help!

**Comment by ilyam8** [comment]
@bgfor nice you found the issue :+1:
