### ISSUE TITLE
No CPU Temp on Raspberry PI Zero W?

### ISSUE THREAD

**Issue by JsBergbau** [netdata/netdata#5239]
I've uncommented in /etc/netdata/charts.d.conf
sensors=force
like on the 2 other netdata installations on Raspberry Pi 1 and Raspberry Pi 3. On those both Option "Sensors" appears and I see CPU temp, on Raspberry PI Zero W no sensor Option is displayed. 

Of course netdata was restarted after making that change. Command /opt/vc/bin/vcgencmd measure_temp works and shows temperature.

**Comment by cakrit** [comment]
Can you run `/usr/libexec/netdata/plugins.d/charts.d.plugin debug` and see what it says? I see that the sensors module tries to find some files named temp under `${NETDATA_HOST_PREFIX}/sys/devices`

```
 find "$1" -maxdepth $sensors_sys_depth -name \*_input -o -name temp 2>/dev/null
```
You can look at  `/usr/libexec/netdata/charts.d/sensors.chart.sh`, the files are being searched in the check funciton.

**Comment by JsBergbau** [comment]
Problem seems plugin uses the wrong path
 
 ```
 2019-01-21 16:19:27: charts.d: WARNING: main: Configuration file '/usr/local/lib/netdata/conf.d/charts.d.conf' not found.
 2019-01-21 16:19:27: charts.d: WARNING: main: Configuration file '/usr/local/etc/netdata/charts.d.conf' not found.
 Few lines later it says sensors is disabled, of course, config file in /etc/netdata/charts.d.conf where also netdata.conf is, seems not to be used.
 ```

**Comment by JsBergbau** [comment]
How can I fix the wrong path error?

**Comment by cakrit** [comment]
My sincerest apologies, I missed the previous comment. Please update netdata to the latest version. We put a fix for the wrong paths 2 days ago. If you still see a path error, see the workaround at #5252 (we're seeing installations sending the configs to /usr/lib64/netdata/conf.d).

**Comment by JsBergbau** [comment]
Thanks, works now. Netdata even automatically shows a connected DS18B20 sensor. I love this software.
