### ISSUE TITLE
Litespeed Vhost

### ISSUE THREAD

**Issue by HostChefs** [netdata/netdata#5248]
Hey there,

I have turned from nginx to litespeed and I am having trouble into "showing" netdata in a specific vhost and folder.
I have tried following the pattern for the apache configuration but it's not working in a specific domain and folder. For example I wanna show it on example3.com/netdata but not on example1.com and example2.com which are on the same server.

Any suggestions would be really helpful :)

**Comment by lucasRolff** [comment]
Can be done by using a simple rewrite rule in `.htaccess`:

```
RewriteEngine On
RewriteRule "^(.*)$" "http://localhost:19999/$1" [P]
```

The first part of the rule can be adapted to e.g. use /netdata

**Comment by HostChefs** [comment]
Solved! Thanks @lucasRolff
