### ISSUE TITLE
Implement a method to push important information bulletins to netdata agent users

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#5255]
We need a way to notify netdata users about important events, e.g. security updates, marquee new features etc. Depending on the importance of the message, the user could be signaled with an icon or a flash message.

The agent should poll a Twitter channel or an RSS feed.

The user should be able to disable the feature from the configuration file (opt-out).

**Comment by Ferroin** [comment]
+1, but this should have an option to opt-out of said notifications (probably as two options, one for general info like new features, and one for updates about big breaking changes and security issues).

Bonus points if the endpoint it's querying is an RSS feed anybody can poll.

**Comment by paulfantom** [comment]
Good monitoring solution is the one which works in an automated way, where you are **not** expected to look at dashboards when there is no need to look at it (no alarms or similar). Taking that into consideration I would say that RSS feed is much more important than GUI stuff. I would even go further and start a mailing list, like most open source projects.

**Comment by gmosx** [comment]
> Bonus points if the endpoint it's querying is an RSS feed anybody can poll.

It will monitor either a Twitter channel or an RSS feed (most likely the former).

**Comment by ilyam8** [comment]
Not relevant anymore
