### ISSUE TITLE
varnish plugin doesn't support custom varnishd working directory

### ISSUE THREAD

**Issue by feld** [netdata/netdata#5262]
##### Feature idea summary

varnish plugin assumes default location of varnish working directory

##### Expected behavior

A configuration option in python.d/varnishd.conf to specify varnish working directory as it might be in a custom location or not match system hostname. (e.g., `/usr/local/varnish/foo` instead of `/usr/local/varnish/hostname`).

**Comment by ilyam8** [comment]
Hi @feld 

What's `varnish working directory` ? i see module uses `varnishstat` binary and it parses its output, that is all.

**Comment by feld** [comment]
varnishsstat (on FreeBSD, for example) looks for `/usr/local/varnish/$(hostname)/_.vsm` socket file. You can specify a different varnish instance or a custom location with the `-n` flag to varnishstat.

```
       -n <dir>
              Specify the varnishd working directory (also known as instance
              name) to get logs from. If -n is not specified, the host name is
              used.
```
