### ISSUE TITLE
Netdata auth

### ISSUE THREAD

**Issue by cookins** [netdata/netdata#5266]
hello
i really like this software but not noticed any security against anyone who want to visit it on default port.
i installed it on Debian 9 remote VPS with webmin shell. can you please assist me how to make security like login and password?
thank you!

**Comment by cakrit** [comment]
We take security **very** seriously. 

Please go through [the relevant ddocumentation](https://docs.netdata.cloud/docs/netdata-security/) and you will find info on how to limit access to specific IPs, run behind an authenticated proxy and more.

We are also preparing a specialized authentication and authorization system, tailored to the distributed nature of Netdata. 

Please let us know if you require additional assistance.

**Comment by deanpcmad** [comment]
I've just setup a master netdata server (so far netdata is really cool and the notifications are working well, I just need to setup some data archiving) and I've got it behind an nginx server with HTTPS & Basic Auth. Seems to work fine, I just need to disable remote access to the netdata ports using iptables/ufw

**Comment by cookins** [comment]
Seems for me Apache proxy auth is most simple in case.

**Comment by cakrit** [comment]
[FireHOL](https://firehol.org) is excellent for firewalls too.
