### ISSUE TITLE
creating a new health alarm

### ISSUE THREAD

**Issue by bitcoiners** [netdata/netdata#5270]
I created a new health alarm /etc/netdata/health.d/nodeos.conf 
```

template: nodeos_ram_in_use
      on: nodeos.ram
      os: linux
   hosts: *
    calc: ($used * 100) / ($used + $free)
   units: %
   every: 10s
    warn: $this > (($status >= $WARNING)  ? (2) : (3))
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: down 15m multiplier 1.5 max 1h
    info: Nodeos RAM used
      to: sysadmin
```
for a plugin I developed.
https://github.com/cryptomooner/netdata/tree/master/collectors/python.d.plugin/nodeos

I am not sure how enable it or make sure it is working.
Anything else that needs to other than creating /etc/netdata/health.d/nodeos.conf?

**Comment by cakrit** [comment]
Nothing else needed, you just put it there and restart. The request  `yourserver/api/v1/alarms?all`  will show in the JSON if it's loaded correctly.

To test though, I suggest you set the limits to something very low, so that it gets triggered. Once you confirm, you change them back.

**Comment by ilyam8** [comment]
> and restart

or `killall -USR2 netdata`

**Comment by bitcoiners** [comment]
Thanks.
It does not seem to be working.. How can I debug health alarm code?
I see no alarm related messages in /var/log/netdata/error.log

**Comment by cakrit** [comment]
The [debug flags](https://docs.netdata.cloud/daemon/#debugging) will show a lot in debug.log. But do you see the alarm when you go to `http://yourserver:yourport/api/v1/alarms?all`?

**Comment by cakrit** [comment]
`warn = $this > (($status >= $WARNING) ? (2) : (3))` means that the limit is 3 when the current status is CLEAR. The limit 2 is applied only when `$status >= $WARNING`, i.e. after the alarm has been triggered (WARNING, CRITICAL). So in this example, it would need to be `(($status >= $WARNING) ? (1) : (2))` to trigger it for anything greater than 2.

**Comment by bitcoiners** [comment]
thanks.
