### ISSUE TITLE
Netdata won't update anymore

### ISSUE THREAD

**Issue by alsoGAMER** [netdata/netdata#5272]
##### Bug report summary
If i try to get updates with the button on the webui or with the .sh script, netdata does anything
##### OS / Environment
Debian 9.7
##### Netdata version (ouput of `netdata -V`)
netdata v1.12.0-rc2-51-nightly
##### Component Name
Updater
##### Steps To Reproduce
Invoke the .sh script or use the "update" button in the webui
##### Expected behavior
Netdata should check for updates

**Comment by cakrit** [comment]
We had some updates to the update process that have caused a few issues that we're still dealing with. 
The .sh can't really be executed directly any more, we'll update the documentation shortly 

First, please see if you have `/etc/cron.daily/netdata-updater` or `/etc/periodic/daily/netdata-updater`. If you do and the script is neither a symbolink link nor an empty file, please execute that. If not, follow the steps below:

1. rm the netdata-updater script
2. Run `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

You should end up with an updated installation. 

Both the update check from the UI and the documentation instructing users to execute the netdata-updater.sh should be updated, so marking this as a bug. But please let us know if you were able to complete the update.

**Comment by cakrit** [comment]
Perhaps also related to https://github.com/netdata/netdata/issues/5208#issuecomment-457104277

**Comment by alsoGAMER** [comment]
I've tried to run /etc/cron.daily/netdata-updater but nothing happens

`# file /etc/cron.daily/netdata-updater`
-> /etc/cron.daily/netdata-updater: symbolic link to /usr/src/netdata.git/netdata-updater.sh

I'll try to use `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`, when done, i'll update you

**Comment by cakrit** [comment]
`kickstart.sh` also uses `/etc/cron.daily/netdata-updater`, if it finds it there, which is why I suggested removing it first.

**Comment by alsoGAMER** [comment]
Ok so, i've reinstalled it and the sh script at `/etc/cron.daily/netdata-updater` seems to working again, i'll try if the button in the webinterface has anyway the problem

**Comment by cakrit** [comment]
The button isn't showing the correct information. We have a fix for #5201 that will be merged soon.

**Comment by paulfantom** [comment]
Should be fixed by https://github.com/netdata/netdata/pull/5276.

**Comment by cakrit** [comment]
Fixes to both issues (upgrade button and left over symlink) have been merged. Please open a new issue if you have any more problems.
