### ISSUE TITLE
Certificate error while running netdata kickstart script

### ISSUE THREAD

**Issue by pcgeek86** [netdata/netdata#5273]
##### Bug report summary

I'm trying to run the kickstart script in the install documentation, and `wget` is tossing me an error about an untrusted TLS certificate on GitHub. I've already checked to make sure I have the Ubuntu `ca-certificates` package installed and updated.

```
trevor@tbsubuntu:~$ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version:
 --- Downloading script to detect required packages... ---
$'[\E[2m/tmp/netdata-kickstart-au9Uag\E[0m\017]$ \E[1m\E[33m' wget -O - https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh $'\E[0m\017\\n' --2019-01-26 22:01:53--  https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by ‘CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.
 FAILED  wget -O - https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh

 ABORTED  Cannot download https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh
```

##### OS / Environment

* VMware ESXi 6.7
* Ubuntu 18.04 - freshly built a few days ago
* OpenSSL 1.1.0a

##### Netdata version (ouput of `netdata -V`)

netdata v1.12.0-rc3-37-gd5e1197

##### Component Name

Kickstart installer

##### Steps To Reproduce

* Installed `netdata` 1.9 from `apt install `
* Removed `netdata` 1.9 via `apt remove netdata` (left behind configuration files)
* Installed netdata using `git clone`
* Installation is broken (can't hit endpoint)
* Tried running kickstart script
* Received error message

##### Expected behavior

* Kickstart install script should run successfully

**Comment by cakrit** [comment]
Please find and install the `ca-certificates` package. If you already have it, you probably need to run an update.

**Comment by pcgeek86** [comment]
> Please find and install the `ca-certificates` package. If you already have it, you probably need to run an update.

Hey, I actually called that out in my post.

> I've already checked to make sure I have the Ubuntu ca-certificates package installed and updated.

**Comment by cakrit** [comment]
Right, sorry. 
I found the following, which suggests that some environments may not have all the root certificates stored: https://github.com/Neilpang/acme.sh/issues/1253
I'm not really keen on not checking the validity of the certificate though. If that's the problem, we'll need to discuss a better way of doing it. 

To ensure that it's not a problem with wget, can you please check if curl can get `https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh` ? I found the **very old** https://github.com/netz98/n98-magerun/issues/75 that mentioned an issue only with an old wget version.

**Comment by pcgeek86** [comment]
Just confirmed that the successful `curl` call is using the updated OpenSSL version as well. Check out the output below.

```
trevor@tbsubuntu:~$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

**Comment by pcgeek86** [comment]
It looks like `wget` is just broken, maybe because I installed openssl 1.1.1a. I'm going to close this for now, since this is affecting things beyond `netdata`. Sorry to waste your time.

```
trevor@tbsubuntu:~/kotlin-docker$ wget https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh
--2019-01-28 08:00:02--  https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
ERROR: cannot verify raw.githubusercontent.com's certificate, issued by ‘CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.
trevor@tbsubuntu:~/kotlin-docker$ wget https://google.com
--2019-01-28 08:00:59--  https://google.com/
Resolving google.com (google.com)... 2607:f8b0:400a:804::200e, 216.58.217.46
Connecting to google.com (google.com)|2607:f8b0:400a:804::200e|:443... connected.
ERROR: cannot verify google.com's certificate, issued by ‘CN=Google Internet Authority G3,O=Google Trust Services,C=US’:
  Unable to locally verify the issuer's authority.
To connect to google.com insecurely, use `--no-check-certificate'.
```
