### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by BlueNickDev** [netdata/netdata#5278]
Problem with installation with the inline command : bash <(curl -Ss https://my-netdata.io/kickstart.sh).

I've got this errors.

![image](https://user-images.githubusercontent.com/44233682/51803932-ebcd1d80-225a-11e9-9f4e-57f3cf0f6f5f.png)

**OS**
Ubuntu 18.04 LTS (Server)

**Comment by cakrit** [comment]
This is very strange. From what I've read and the tests I've done, the only way to get the error `cannot create directory '/etc/netdata': File exists` from the `mkdir -p` is if you have a **file** called `netdata` under `/etc`. This is definitely not normal. 

Can you please see what that `/etc/netdata` file is and let us know? I expect that the installation will work if you move it out of the way and rerun the same command, but I'd really like to understand what it is and how it got there.

**Comment by BlueNickDev** [comment]
I've checked inside /etc folder and there was an inactive link called "netdata" , I don't know what is it and from what was generated.
I've removed it and restart the installation, now works all good; thak you for the reply.
