### ISSUE TITLE
Where is a file netdata-updater.sh? (I use a centos7)

### ISSUE THREAD

**Issue by sohwaje** [netdata/netdata#5279]
$ cd /root/netdata
$ ls
-rwxr-x---.  1 root root 3.5K  1월 28 16:42 netdata-uninstaller.sh
-rw-rw-r--.  1 root root 7.5K  1월 28 16:42 netdata-installer.log
-rw-rw-r--.  1 root root  71K  1월 28 16:42 config.log
-rw-rw-r--.  1 root root   23  1월 28 16:42 stamp-h1
drwxr-xr-x.  5 root root  113  1월 28 16:42 web
drwxr-xr-x.  5 root root  154  1월 28 16:42 tests
drwxr-xr-x.  2 root root 4.0K  1월 28 16:42 system
drwxr-xr-x.  3 root root  177  1월 28 16:42 streaming
drwxr-xr-x.  3 root root 4.0K  1월 28 16:42 registry
drwxr-xr-x. 20 root root 4.0K  1월 28 16:42 libnetdata
drwxr-xr-x.  5 root root 4.0K  1월 28 16:42 health
drwxr-xr-x.  3 root root  241  1월 28 16:42 diagrams
drwxr-xr-x.  3 root root 4.0K  1월 28 16:42 database
drwxr-xr-x.  4 root root 4.0K  1월 28 16:42 daemon
drwxr-xr-x. 19 root root 4.0K  1월 28 16:42 collectors
drwxr-xr-x.  7 root root  266  1월 28 16:42 backends
-rw-rw-r--.  1 root root 6.8K  1월 28 16:42 netdata.spec
-rw-rw-r--.  1 root root 122K  1월 28 16:42 Makefile
-rwxrwxr-x.  1 root root  46K  1월 28 16:42 config.status
-rw-rw-r--.  1 root root 129K  1월 28 16:41 Makefile.in
-rwxr-xr-x.  1 root root  24K  1월 28 16:41 depcomp
-rwxr-xr-x.  1 root root 6.8K  1월 28 16:41 missing
-rwxr-xr-x.  1 root root  14K  1월 28 16:41 install-sh
-rwxr-xr-x.  1 root root  35K  1월 28 16:41 config.sub
-rwxr-xr-x.  1 root root  45K  1월 28 16:41 config.guess
-rwxr-xr-x.  1 root root 7.2K  1월 28 16:41 compile
-rw-rw-r--.  1 root root 9.2K  1월 28 16:41 config.h.in
drwxr-xr-x.  2 root root   86  1월 28 16:41 autom4te.cache
-rwxrwxr-x.  1 root root 282K  1월 28 16:41 configure
-rw-rw-r--.  1 root root  48K  1월 28 16:41 aclocal.m4
-rwxrwxr-x.  1 root root 1.1M  1월  3 13:54 netdata
-rwxrwxr-x.  1 root root  89K  1월  3 13:54 apps.plugin
-rwxrwxr-x.  1 root root  36K  1월  3 13:54 cgroup-network
-rw-rw-r--.  1 root root 9.7K  1월  3 13:54 config.h
-rw-rw-r--.  1 root root 9.2K  1월  3 13:54 config.h.in~
drwxr-xr-x.  6 root root   72  1월  3 13:45 packaging
-rwxr-xr-x.  1 root root  32K  1월  3 13:45 netdata-installer.sh
-rw-r--r--.  1 root root  508  1월  3 13:45 netdata.cppcheck
-rw-r--r--.  1 root root 6.8K  1월  3 13:45 netdata.spec.in
-rw-r--r--.  1 root root  446  1월  3 13:45 netlify.toml
-rw-r--r--.  1 root root  607  1월  3 13:45 package.json
drwxr-xr-x.  3 root root 4.0K  1월  3 13:45 docs
drwxr-xr-x.  5 root root   63  1월  3 13:45 contrib
-rwxr-xr-x.  1 root root 2.6K  1월  3 13:45 coverity-scan.sh
-rwxr-xr-x.  1 root root  892  1월  3 13:45 cppcheck.sh
-rw-r--r--.  1 root root  46K  1월  3 13:45 configs.signatures
-rw-r--r--.  1 root root  19K  1월  3 13:45 configure.ac
drwxr-xr-x.  3 root root   49  1월  3 13:45 build
-rw-r--r--.  1 root root  37K  1월  3 13:45 README.md
-rw-r--r--.  1 root root 6.4K  1월  3 13:45 REDISTRIBUTED.md
-rw-r--r--.  1 root root 3.5K  1월  3 13:45 CODE_OF_CONDUCT.md
-rw-r--r--.  1 root root  11K  1월  3 13:45 CONTRIBUTING.md
-rw-r--r--.  1 root root 5.0K  1월  3 13:45 CONTRIBUTORS.md
-rw-r--r--.  1 root root  20K  1월  3 13:45 HISTORICAL_CHANGELOG.md
-rw-r--r--.  1 root root  35K  1월  3 13:45 LICENSE
-rw-r--r--.  1 root root  14K  1월  3 13:45 Makefile.am
-rw-r--r--.  1 root root  73K  1월  3 13:45 CHANGELOG.md
-rw-r--r--.  1 root root  19K  1월  3 13:45 CMakeLists.txt

**Comment by cakrit** [comment]
The instructions to update are outdated, please read #5277 instead. We will finalize and merge today.
