### ISSUE TITLE
Can I check monthly or daily reports or history

### ISSUE THREAD

**Issue by CharanjeetE** [netdata/netdata#5287]
##### Question summary
I need monthly reports for netdata
##### OS / Environment
ubuntu
##### Expected results
I want to check the reports or chart for the last few days or month.Please help me where I can find those?

**Comment by cakrit** [comment]
This isn't currently possible, data are not stored for that long due to the large memory requirements. The implementation of a new DB format has started based on #4687, to enable such features.

**Comment by cakrit** [comment]
Take a look at the following, it will help you. 
https://docs.netdata.cloud/database/
Essentially, you want to increase history and tweak the collection period so you don't increase the memory requirements too much. KSM also helps, the explanation is in the same doc.

Also, if you look at some of the suggestions in the following and disable plugins/modules you don't need, you can keep metrics for much longer:
https://docs.netdata.cloud/docs/netdata-for-iot/

**Comment by cakrit** [comment]
I'm closing this one, as it's essentially what we want to achieve with #4687
