### ISSUE TITLE
Uninstaller fixes and instructions

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5290]
##### Bug report summary
The uninstall instructions in https://docs.netdata.cloud/packaging/installer/uninstall/ instruct users to use ./packaging/installer/netdata-uninstaller.sh. But that script is not present in the installation and users would need to download it.

##### OS / Environment
All

##### Netdata version (ouput of `netdata -V`)
1.12-rcXX-XX

##### Component Name
packaging

##### Steps To Reproduce
install netdata using kickstart.sh or kickstart-static64.sh
try to find netdata-uninstaller.sh

##### Expected behavior
The two kickstarts should leave the uninstaller script that uses the new .environment file in an installation directory (e.g. somewhere under /usr/libexec/netdata).

**Comment by paulfantom** [comment]
> But that script is not present in the installation and users would need to download it.

That was the intention.

**Comment by rickardrosen** [comment]
Using the kickstarter installation without params I would assume the uninstall would just work, but it does not.

It wants a weird dot file that perhaps the installer should create and keep?

**Comment by paulkatsoulakis** [comment]
I think we are good with this one. We brought back the uninstaller, updated documentation too
