### ISSUE TITLE
Can not seem to get IPMI plugin installed via 'netdata/collectors/freeipmi.plugin/' instructions, on Ubuntu 16.04.5 LTS

### ISSUE THREAD

**Issue by jimidak** [netdata/netdata#5299]
## IPMI plugin install steps:

```
> bash <(curl -Ss https://my-netdata.io/kickstart.sh)
> sudo apt-get install libipmimonitoring-dev
> ipmimonitoring
The program 'ipmimonitoring' is currently not installed. You can install it by typing:
sudo apt install freeipmi-tools
>  sudo apt install freeipmi-tools
>  bash <(curl -Ss https://my-netdata.io/kickstart.sh)
> service restart netdata

There is no no freeipmi in netdata.conf and no ipmi under  /usr/libexec/netdata/plugins.d
```
## OS
Ubuntu 16, VM

## Component Name
IPMI

**Comment by jimidak** [comment]
I should have provided more detail on my install process.  Hopefully this fill in some blanks.

----

## OUTPUT FROM RE-INSTALLING NETDATA (bash <(curl -Ss https://my-netdata.io/kickstart.sh) 
checking for IPMIMONITORING... no
checking if freeipmi.plugin should be enabled... no


## LOOKING TO SEE IF IMPIMONITOR IS AVAIL
me@host:/usr/libexec/netdata/plugins.d$ ipmi <TAB> <TAB>
ipmicmd   ipmievd   ipmilan   ipmish    ipmitool  ipmi_ui


## INSTALL PACKAGE THAT IS SUPPOSED TO PROVIDE IPMIMONITOR PER NETDATA INSTRUCTIUONS
me@host:/usr/libexec/netdata/plugins.d$ sudo apt-get install libipmimonitoring-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libipmimonitoring5a
The following NEW packages will be installed:
  libipmimonitoring-dev libipmimonitoring5a
0 upgraded, 2 newly installed, 0 to remove and 36 not upgraded.
Need to get 105 kB of archives.
After this operation, 471 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
...


## TRY IPMIMONITORING
me@host:/usr/libexec/netdata/plugins.d$ ipmimonitoring
The program 'ipmimonitoring' is currently not installed. You can install it by typing:
sudo apt install freeipmi-tools


## WHAT WAS INSTALLED?
me@host:/usr/libexec/netdata/plugins.d$ sudo -i
root@host:~#
root@host:~# dpkg -l | grep ipmi
ii  freeipmi-common                    1.4.11-1.1ubuntu4~0.16.04                  amd64        GNU implementation of the IPMI protocol - common files
ii  ipmitool                           1.8.16-3ubuntu0.2                          amd64        utility for IPMI control with kernel driver or LAN interface (daemon)
ii  libfreeipmi16                      1.4.11-1.1ubuntu4~0.16.04                  amd64        GNU IPMI - libraries
ii  libipmimonitoring-dev              1.4.11-1.1ubuntu4~0.16.04                  amd64        GNU IPMI - ipmimonitoring development package
ii  libipmimonitoring5a                1.4.11-1.1ubuntu4~0.16.04                  amd64        GNU IPMI - Sensor monitoring library
ii  libopenipmi0                       2.0.18-0ubuntu11.2                         amd64        Intelligent Platform Management Interface - runtime
ii  openipmi                           2.0.18-0ubuntu11.2                         amd64        Intelligent Platform Management Interface (for servers)
root@host:~# exit
logout


## INSTALL FREEIPMI-TOOLS AS SUGGESTED WHEN TRYING TO RUN IPMIMONITOR
me@host:/usr/libexec/netdata/plugins.d$ sudo apt-get install freeipmi-tools
...


## TRY RUNNING IPMIMONITOR AGAIN (I get the same error as you)
me@host:/usr/libexec/netdata/plugins.d$ sudo ipmimonitoring
Caching SDR repository information: /root/.freeipmi/sdr-cache/sdr-cache-dorglazierv1.localhost

ipmi_sdr_cache_create: internal IPMI error

**Comment by jimidak** [comment]
There is no freeipmi plugins section in cd /etc/netdata/netdata.conf

**Comment by jimidak** [comment]
```
root@host:/etc/freeipmi# sudo su -s /bin/sh netdata
$ /usr/libexec/netdata/plugins.d/freeipmi.plugin 5 debug
2019-02-01 21:59:19: freeipmi.plugin ERROR : MAIN : update frequency 5 seconds is too small for IPMI. Using 5.
freeipmi.plugin: calling _init_ipmi_config()
freeipmi.plugin: calling ipmi_monitoring_init()
freeipmi.plugin: detecting IPMI minimum update frequency...
freeipmi.plugin: checking data collection speed iteration 1 of 10
2019-02-01 22:00:19: freeipmi.plugin ERROR : MAIN : ipmi_monitoring_sensor_readings_by_record_id(): internal error (errno 2, No such file or directory)
2019-02-01 22:00:19: freeipmi.plugin FATAL : MAIN :freeipmi.plugin: data collection failed. # : Success

$ exit
root@host:/etc/freeipmi#
root@host:/etc/freeipmi# cat /usr/lib/netdata/conf.d/health.d/ipmi.conf
   alarm: ipmi_sensors_states
      on: ipmi.sensors_states
    calc: $warning + $critical
   units: sensors
   every: 10s
    warn: $this > 0
    crit: $critical > 0
   delay: up 5m down 15m multiplier 1.5 max 1h
    info: the number IPMI sensors in non-nominal state
      to: sysadmin

   alarm: ipmi_events
      on: ipmi.events
    calc: $events
   units: events
   every: 10s
    warn: $this > 0
   delay: up 5m down 15m multiplier 1.5 max 1h
    info: the number of events in the IPMI System Event Log (SEL)
      to: sysadmin
root@host:/etc/freeipmi#
```

**Comment by cakrit** [comment]
Ok, I tried it a bit more and discussed it with @ktsaou as well. The command `ipmimonitoring` is something that doesn't necessarily work on all systems. There is HW that has the relevant endpoints for the ipmi sensors enabled by default and HW that doesn't. It really has nothing to do with netdata. The error you see from `ipmimonitoring` is actually from the command seen below:

```
$ sudo ipmi-sensors
SDR Cache '/root/.freeipmi/sdr-cache/sdr-cache-chris-msi.localhost' invalid: Please flush the cache and regenerate it
$ sudo ipmi-sensors --flush-cache
Flushing cache: /root/.freeipmi/sdr-cache/sdr-cache-chris-msi.localhost
$ sudo ipmi-sensors
Caching SDR repository information: /root/.freeipmi/sdr-cache/sdr-cache-chris-msi.localhost
ipmi_sdr_cache_create: internal IPMI error
```

`ipmi-sensors` builds a cache, because the operation of querying the HW to find these "endpoints" or whatever they are called is expensive. If that errors, it's impossible to collect something. 
The only thing we can suggest is to try the freeipmi mailing list, in case there is something you can do for your HW.

**Comment by jimidak** [comment]
Thank you for getting back.

**Comment by stevenh** [comment]
Getting the same error here, specifically:
`2019-10-13 01:12:04: freeipmi.plugin ERROR : MAIN : ipmi_monitoring_sensor_readings_by_record_id(): internal system error (errno 2, No such file or directory)`

The strange thing is if I run it from the command line, instead of having netdata start, it works just fine.

In case it matters this is running in a container, any ideas?

**Comment by stevenh** [comment]
This was down to the plugin running as the wrong user.

I added suid to the binary and its now working. Would help if the errors from the freeipmi lib where a but nicer, so I didn't have to resort to `strace` to figure that out.
