### ISSUE TITLE
How to show Total Upload Data over the last 24 hours

### ISSUE THREAD

**Issue by antigravity83** [netdata/netdata#5300]
##### Question summary
I need to be able to monitor the total amount of data uploaded over a rolling 24 hour period. 

##### OS / Environment
Linux

##### Expected results
Data uploaded in the past 24 hours: 40.4GB

**Comment by cakrit** [comment]
@vlvkobal & @ilyam8 any ideas about this one?

**Comment by ilyam8** [comment]
Send data to backend and then do a query to it. Current netdata implementation has no such functionality (metrics long term archiving and custom queries to db)

https://docs.netdata.cloud/backends/
