### ISSUE TITLE
Prototype for netdata internal database v2.0

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#5303]
##### Feature idea summary

netdata internal database v2.0
The first step towards #4687

##### Expected behavior

New database storage engine that is based on data files that contain metrics and journal files that contain metadata. No more mmap, it will be based on asynchronous I/O and on-disk compression. It will optimize the I/O path to be viable even on rotating media. This will also allow the database memory footprint to be smaller than the database size on disk.

**Comment by cakrit** [comment]
Tasks to complete:

Perfomance testing:
- [ ] Add new DB performance statistics under the netdata monitoring section. 
- [ ] Generate dataset for realistic charts for the new DB.  Run netdata with specific command options.
- [ ] Black box testing using netdata APIs (e.g. /api/v1/data, backends etc.) (Chris)
- [ ] Internal stress testing (create a lot of data to push the DB). Run netdata with specific command options.

Unit testing:
- [ ] Data is written as expected.
- [ ] Extent written as expected
- [ ] LRU works as expected
- [ ] more...

Validate functionality of old DB
- [ ] Utilize existing unit tests.

Technical documentation

Building/packaging

Run tests on multiple infrastructures

Tests by the netdata team

Merge the code on time for v1.15 with the new DB disabled by default.
