### ISSUE TITLE
Kafka backend support

### ISSUE THREAD

**Issue by ldelossa** [netdata/netdata#5313]
##### Question summary
Does netdata officially support Kafka backend support? The infograph on the README does show that kafka is a supported backend however documentation does not reference kafka anywhere in the backend's page.

**Comment by mfundul** [comment]
By searching the netdata source code for "kafka" I found references such as [this](https://github.com/netdata/netdata/blob/de2f21c22c8f967c8698e88b5ee2a1705e5b5a0d/health/notifications/alarm-notify.sh.in#L914) piece of code. It looks like kafka is supported although I'm not sure what "official" means in this context.

**Comment by Ferroin** [comment]
We support sending notifications through Kafka, but AFAIK that's it right now.

**Comment by cakrit** [comment]
Kafka is not explicitly mentioned because it's covered by the more generic `json` backend. See the following:
https://docs.netdata.cloud/backends/#features for the docs
https://github.com/netdata/netdata/issues/1917 for a configuration a user used in an old ticket
