### ISSUE TITLE
cgroups name resolution doesn't work (on Raspbian)

### ISSUE THREAD

**Issue by caius88** [netdata/netdata#5314]
##### Bug report summary
Containerized Netdata doesn't resolve the containers name even with docker PGID env set correctly.
##### OS / Environment
Raspbian Stretch Lite on Raspberry 3 / netdata container with tag: `latest-armhf`
##### Netdata version (ouput of `netdata -V`)
netdata v1.12.0-rc3-60-g6e35d758
##### Component Name
plugin: cgroups
##### Steps To Reproduce
```version: "3.6"
services:

  netdata:
    image: netdata/netdata:latest-armhf
    container_name: netdata
    volumes:
      - ${APPDIR}/netdata/netdata.conf:/etc/netdata/netdata.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    hostname: pi3
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    environment:
      - PGID=${PGID_DOCKER}
      - PUID=${PUID}
      - TZ=${TZ}
```
where `PUID=0` and `PGID_DOCKER=$(grep docker /etc/group | cut -d ':' -f 3)` (in my case 996). 
From container logs i found some errors:
```
2019-02-01 14:26:07: cgroup-name.sh: WARNING: cannot find the name of docker container '6c2468eb8dacb89840c2477899ff6f35e4073a904b31c43c0f85a86384dc1bec'
2019-02-01 14:26:07: cgroup-name.sh: INFO: cgroup 'docker_6c2468eb8dacb89840c2477899ff6f35e4073a904b31c43c0f85a86384dc1bec' is called '6c2468eb8dac'
2019-02-01 14:26:08: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : Using host prefix directory '/host'
2019-02-01 14:26:08: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : running: exec /usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/host/sys/fs/cgroup/cpu,cpuacct/docker/6c2468eb8dacb89840c2477899ff6f35e4073a904b31c43c0f85a86384dc1bec'
2019-02-01 14:26:09: cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/host/sys/fs/cgroup/cpu,cpuacct/docker/6c2468eb8dacb89840c2477899ff6f35e4073a904b31c43c0f85a86384dc1bec'
2019-02-01 14:26:09: /usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : child pid 321 exited with code 1.
2019-02-01 14:26:09: /usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : Cannot switch to network namespace of pid 1 (errno 1, Operation not permitted)
2019-02-01 14:26:09: /usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : Cannot switch to pid namespace of pid 1 (errno 1, Operation not permitted)
2019-02-01 14:26:09: /usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : Cannot switch to mount namespace of pid 1 (errno 1, Operation not permitted)
```
Now i'm using a workaround: if i run `chmod 666 /var/run/docker.sock` and restart netdata container the names are resolved, but after an host reboot the permissions of docker.sock back to 660. I need help because i have the same configuration in an Ubuntu Server 18.04 and the names are resolved out-of-the-box without any issue :/

##### Expected behavior
I expect the docker containers are identified by name, not ID.

**Comment by paulfantom** [comment]
I cannot reproduce this.

**Comment by caius88** [comment]
> 
> 
> We accidentally saw the same thing on my laptop. The reason it was happening for me what the user I was running netdata as (myself) was not in the docker group. We added my user to `/etc/group`, I did a restart of netdata and 10s later I saw the docker name in the charts. Can you check if it's the same for you?

Hi, following the official docs i already set `PGID_DOCKER=$(grep docker /etc/group | cut -d ':' -f 3)`. Then`PUID=0` is root. With this configuration on my server (w/ Ubuntu Server 18.04) the cgroup names works as expected.
Investigating a little bit i found that _netdata_ user groups inside the container give different results:
On Ubuntu:
```
bash-4.4# id netdata
uid=201(netdata) gid=201(netdata) groups=201(netdata),999(ping),201(netdata)
```
On Raspbian:
```
bash-4.4# id netdata
uid=201(netdata) gid=201(netdata) groups=201(netdata),201(netdata)
```
On Ubuntu the `PGID=999` is the docker group. For some strange reasons the environment variable PGID on Raspbian seems to be ignored. Could be the image **netdata/netdata:latest-armhf**?

**Comment by paulfantom** [comment]
Are you sure you are running latest image? Can you start netdata again but pull image beforehand (`docker pull netdata/netdata:latest-armhf`)?

Also our docs doesn't mention anything about using `netdata/netdata:latest-armhf` directly. You are supposed to use `netdata/netdata:latest` regardless of CPU architecture.

**Comment by caius88** [comment]
> 
> 
> Are you sure you are running latest image? Can you start netdata again but pull image beforehand (`docker pull netdata/netdata:latest-armhf`)?
> 
> Also our docs doesn't mention anything about using `netdata/netdata:latest-armhf` directly. You are supposed to use `netdata/netdata:latest` regardless of CPU architecture.

Hi, recreate the container with the image `netdata/netdata:latest` but the situation remain the same. But the image is not the problem:
with **docker group 996** on host i set PGID to 996 on the compose but:
```
bash-4.4# id netdata
uid=201(netdata) gid=201(netdata) groups=201(netdata),201(netdata)
```
If i try a: 
```
bash-4.4# adduser netdata 996
addgroup: unknown group 996
```
obviously because the group 996 on the container does not exist! On Ubuntu i've been lucky because the docker group is 999, translated to the container's _ping_ group that does exist.
What is the right way to procede from here?

**Comment by paulfantom** [comment]
netdata docker container should be by default executing commands you wrote (https://github.com/netdata/netdata/blob/master/packaging/docker/run.sh#L10-L14). Please verify that container logs have following line:

> Adding user netdata to group with id 996

**Comment by caius88** [comment]
I've redeployed the compose with netdata and i found the line you mentioned:
```
pi@pi3:~ $ docker logs netdata 2>&1 | grep 996
Adding user netdata to group with id 996
```
but the 996 group is still missing:
```
bash-4.4# id netdata
uid=201(netdata) gid=201(netdata) groups=201(netdata),201(netdata)
```

**Comment by paulfantom** [comment]
I have no idea what is the cause of this on your system. I am running latest netdata on the same hardware with the same OS and with docker container monitoring and it is working.

Here is my docker-compose:
```
version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: bench
    restart: 'always'
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    environment:
      PGID: 989
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${PWD}/netdata/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf:ro"
```

Also I don't know why you are setting `PUID` and `TZ` variables as those are not taken into consideration by netdata itself.


Could you go into a container and report back output of following commands:
```sh
cat /etc/group
env
```
?

**Comment by dbrody2004** [comment]
Still having an issue with this.

On host -
grep docker /etc/group
docker:x:999:

Inside netdata docker
root@6df2b0f51830:/# id netdata
uid=999(netdata) gid=999(netdata) groups=999(netdata),4(adm),13(proxy)

root@6df2b0f51830:/# env
SMTP_TLS=on
NETDATA_PORT=19999
SMTP_SERVER=smtp.gmail.com
HOSTNAME=6df2b0f51830
CRASHMAIL_HOST=netdata
SMTP_FROM=localhost
PGID=999
PWD=/
HOME=/root
TERM=xterm
SHLVL=1
SMTP_STARTTLS=on
SMTP_PORT=587
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env

root@6df2b0f51830:/# cat /etc/group | grep netdata
adm:x:4:netdata
proxy:x:13:netdata
netdata:x:999:netdata
root@6df2b0f51830:/# 

<img width="176" alt="screen shot 2019-02-13 at 4 31 15 pm" src="https://user-images.githubusercontent.com/4682241/52753753-d1aa7380-2fac-11e9-8fe1-f7af5a8e6889.png">

**Comment by caius88** [comment]
> 
> 
> I have no idea what is the cause of this on your system. I am running latest netdata on the same hardware with the same OS and with docker container monitoring and it is working.
> 
> Here is my docker-compose:
> 
> ```
> version: '3'
> services:
>   netdata:
>     image: netdata/netdata
>     hostname: bench
>     restart: 'always'
>     ports:
>       - 19999:19999
>     cap_add:
>       - SYS_PTRACE
>     environment:
>       PGID: 989
>     volumes:
>       - /proc:/host/proc:ro
>       - /sys:/host/sys:ro
>       - /var/run/docker.sock:/var/run/docker.sock:ro
>       - "${PWD}/netdata/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf:ro"
> ```
> 
> Also I don't know why you are setting `PUID` and `TZ` variables as those are not taken into consideration by netdata itself.
> 
> Could you go into a container and report back output of following commands:
> 
> ```shell
> cat /etc/group
> env
> ```
> 
> ?

cat command:
```
bash-4.4# cat /etc/group
root:x:0:root
bin:x:1:root,bin,daemon
daemon:x:2:root,bin,daemon
sys:x:3:root,bin,adm
adm:x:4:root,adm,daemon
tty:x:5:
disk:x:6:root,adm
lp:x:7:lp
mem:x:8:
kmem:x:9:
wheel:x:10:root
floppy:x:11:root
mail:x:12:mail
news:x:13:news
uucp:x:14:uucp
man:x:15:man
cron:x:16:cron
console:x:17:
audio:x:18:
cdrom:x:19:
dialout:x:20:root
ftp:x:21:
sshd:x:22:
input:x:23:
at:x:25:at
tape:x:26:root
video:x:27:root
netdev:x:28:
readproc:x:30:
squid:x:31:squid
xfs:x:33:xfs
kvm:x:34:kvm
games:x:35:
shadow:x:42:
postgres:x:70:
cdrw:x:80:
usb:x:85:
vpopmail:x:89:
users:x:100:games
ntp:x:123:
nofiles:x:200:
smmsp:x:209:smmsp
locate:x:245:
abuild:x:300:
utmp:x:406:
ping:x:999:
nogroup:x:65533:
nobody:x:65534:
netdata:x:201:netdata
```
env command:
```
bash-4.4# env
ARCH=armhf
NETDATA_PORT=19999
ALPINE_REL=v3.8
HOSTNAME=pi3
PGID=996
PWD=/
HOME=/root
TERM=xterm
ALPINE_MIRROR=http://dl-cdn.alpinelinux.org/alpine
SHLVL=1
DOCKER_REPO=multiarch/alpine
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```

Thank you for the help :)

**Comment by dbrody2004** [comment]
Problem with that the docker socket file wasn't mounted to the docker container.  Thanks for the help, works now.

**Comment by paulkatsoulakis** [comment]
Sorry for not getting aligned with you on time @dbrody2004, we 're glad it worked after all!
We have updated our documentation also with new instructions around this, since we had another report (#5823) with problems around container name resolutions and we had to do small refactors.

Do not hesitate to get in touch with us soon
