### ISSUE TITLE
[question] Lower load with high traffic

### ISSUE THREAD

**Issue by Wqrld** [netdata/netdata#5318]
##### Question summary
What would i need to disable to lower the load on netdata while under a high traffic load. I am running netdata on some servers that are regularly under DDOS load and have found that netdata greatly lowers the lagging-treshhold where the machine can handle it much better if netdata is off.
##### OS / Environment
Ubuntu 16.04

**Comment by cakrit** [comment]
Can you see if the suggestions in the following two help you? If not, we'll need to go deeper.
https://docs.netdata.cloud/docs/performance/
https://docs.netdata.cloud/docs/high-performance-netdata/

**Comment by mfundul** [comment]
When you say lower the load on netdata, do you mean the system load that's mainly CPU or the actual network traffic load that netdata causes?

**Comment by ilyam8** [comment]
>  under DDOS load netdata greatly lowers the lagging-treshhold where the machine can handle it much better if netdata is off.

That is actually pretty interesting. We need to investigate this. What type of DDOS btw?

**Comment by Wqrld** [comment]
> > under DDOS load netdata greatly lowers the lagging-treshhold where the machine can handle it much better if netdata is off.
> 
> That is actually pretty interesting. We need to investigate this. What type/kind of DDOS btw? (i will try to check it in a lab)
This as a UDP flood, it could be that this also happens with other attacks but this was the one where turning off netdata helped.

**Comment by ilyam8** [comment]
> servers that are regularly under DDOS load

If this happens again could you save a netdata snapshot and share with us? It would be nice if there we could see graphs before DDOS and during it.

**Comment by Wqrld** [comment]
keeping this open as we're moving soon and i expect quite a lot of traffic to hit the machines

**Comment by cakrit** [comment]
We need to keep this open until we get some more info from @Wqrld

**Comment by Wqrld** [comment]
I have not had any performance issues anymore and as im getting some dedicated firewall hardware in place that shouldn't be too big of a issue anymore.

**Comment by cakrit** [comment]
Ok, so I'm closing. Let us know if you need any help.
