### ISSUE TITLE
netdata failed to install 

### ISSUE THREAD

**Issue by bmf7777** [netdata/netdata#5319]
netdata fails to install and produces the following error output...

```
[/tmp/netdata-updater-wFQSFD/netdata-v1.12.0-rc3-66-gadaaae7c]# systemctl enable netdata 
Synchronizing state of netdata.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable netdata
Failed to enable unit: Unit file /etc/systemd/system/netdata.service is masked.
 FAILED   

 FAILED  Cannot install netdata init service. 

 --- Start netdata --- 
[/tmp/netdata-updater-wFQSFD/netdata-v1.12.0-rc3-66-gadaaae7c]# /bin/systemctl stop netdata 
 OK   

Stopping netdata on pid 17753 ....
netdata on pid 17753 stopped.
[/tmp/netdata-updater-wFQSFD/netdata-v1.12.0-rc3-66-gadaaae7c]# /bin/systemctl restart netdata 
Failed to restart netdata.service: Unit netdata.service is masked.
 FAILED   

[/tmp/netdata-updater-wFQSFD/netdata-v1.12.0-rc3-66-gadaaae7c]# /bin/systemctl start netdata 
Failed to start netdata.service: Unit netdata.service is masked.
 FAILED   
```
i uninstalled twice with the same results ... i also installed via apt-get install netdata although without errors it doesn't allow web page viewing at 19999

... i have 12 other systems working fine, this is the first time an installation error has occured

any ideas how i can debug?

##### OS / Environment
ubuntu 18.04 running on Intel NUC

##### Steps To Reproduce
bash <(curl -Ss https://my-netdata.io/kickstart.sh)

**Comment by paulfantom** [comment]
You have a masked `netdata.service` please unmask it (`systemctl unmask netdata`) and reinstall.

**Comment by bmf7777** [comment]
i didn't issue a mask ... however, after the uninstall and static install ... all is working fine

**Comment by crw** [comment]
I believe the mask happens automatically when you uninstall the netdata package on Ubuntu, eg. `apt remove netdata` -- I had this same problem after uninstalling from package and installing from source.

**Comment by comperem** [comment]
i had an unintentional (and surprising) netdata mask applied somehow. I never tried uninstalling netdata. the mask  was not intentional but did get removed with `systemctl unmask netdata`

**Comment by luckman212** [comment]
If switching from `apt` install method to kickstart, how can we clean up all traces from apt installation and ensure it does not come back and interfere? I hit this problem today.
