### ISSUE TITLE
Codacy is unconfigured

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#5320]
##### Bug report summary

Codacy seems incorrectly configured.
Since Feb 1st, 2019 it shows this:

![image](https://user-images.githubusercontent.com/2662304/52185450-6e8c4480-2828-11e9-9483-eca9e5d0c224.png)

##### OS / Environment

all

##### Netdata version (ouput of `netdata -V`)

current

##### Component Name

code quality

##### Steps To Reproduce

just check codacy badge

##### Expected behavior

Codacy seems to be running with default settings, which are not appropriate for netdata.
Also certain directories (like `contrib/`) or third-party files (like `makeself.sh`) should be excluded from codacy checks.

**Comment by paulfantom** [comment]
Codacy IS configured. Its configuration file is located in netdata repo as `.codacy.yml`.

**Comment by cakrit** [comment]
![screenshot from 2019-02-07 15-12-57](https://user-images.githubusercontent.com/43294513/52417261-c73f3400-2aeb-11e9-9d20-f00114b1a19a.png)

We did a lot of fixes to get it there, but something was changed in Codacy itself for sure, both before the spike and when it went down to 0. 

Closing and we'll see if it happens again.
