### ISSUE TITLE
SMART disk monitor under containerized Netdata

### ISSUE THREAD

**Issue by caius88** [netdata/netdata#5321]
##### Question summary
Can anyone help me to configure my containerized Netdata to show SMART disks metrics of the host. I've already install smartmontools on the host. Any specific folder to be mapped (i.e. /var/log/smartd as shown in the wiki)?
##### OS / Environment
Ubuntu Server 18.04
##### Component Name
smartd_logs
##### Expected results
SMART metrics for all host disks

**Comment by cakrit** [comment]
The official documentation is no longer on the wiki, but [here](https://docs.netdata.cloud/collectors/python.d.plugin/smartd_log/). From what I understand, it's very simple to make the host's folder accessible from the container: https://stackoverflow.com/questions/46010174/access-data-from-host-in-docker-container

Once you do that, you just follow the docs to set the path and it should work fine.

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/issues/5321#issuecomment-460367342 solved the problem, @caius88 if you still have any questions feel free to ask
