### ISSUE TITLE
Monitor /proc/net for active connections per process

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5322]
##### Feature idea summary

The following comment on #2169 stirred a discussion on how we can efficiently monitor additional networking statistics: https://github.com/netdata/netdata/issues/2169#issuecomment-459952028

The idea is to extend the `proc` plugin and permit netdata to start with options that would tell it which files under `/proc/net` to parse and create charts fore. Those files will have a format like the following:

```
cat /proc/net/tcp6
  sl  local_address                         remote_address                        st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode
   0: 00000000000000000000000001000000:0277 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 2903 1 00000000effcaedd 99 0 0 10 0
   1: 00000000000000000000000001000000:1FBD 00000000000000000000000000000000:0000 0A 00000000:00000000 00:00000000 00000000  1000        0 3396178 1 00000000a2cefaf4 99 0 0 10 0
   2: 021C012000FF0022BD2A1156DBE21ACD:D6EE 5014002A070C134000000000BC000000:01BB 01 00000000:00000000 02:0000082A 00000000  1000        0 3123030 2 00000000a66343be 22 3 0 10 -1
   3: 021C012000FF0022BD2A1156DBE21ACD:9418 5014002A09080E40000000000E200000:01BB 01 00000000:00000000 02:00000780 00000000  1000        0 3457767 2 00000000ce00bd53 21 3 22 10 7
```

We looked at how we can link these metrics to processes and apparently, for tcp at least, we can use the `inode` column, as long as we have connected clients. i.e. sockets that are just listening. netdata already knows the ids shown e.g. by the command `sudo ls -l /proc/$(pidof netdata)/fd | grep socket` and some of them will match a particular row of `/proc/tcp6`. 

Efficiency is paramount here, as the proc plugin is already heavily optimized and we want to maintain the ability to run per second. So it will need a very careful design.

**Comment by cakrit** [comment]
Mentioning @lucasRolff , @ktsaou and @vlvkobal to help progress this.

**Comment by rsalmond** [comment]
I would love to have per socket numbers for rx_queue. We have some apps I would like to use this signal to autoscale on.

**Comment by thiagoftsm** [comment]
The  `ebpf.plugin` already has part of this implemented:

1 - We parse the file when the plugin is loading.
2 - We attach a function to verify when new ports stat to listen.

We need to finalize the integration with APPS to have per PID connection.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
