### ISSUE TITLE
Monitoring block io of docker containers

### ISSUE THREAD

**Issue by ldelossa** [netdata/netdata#5323]
##### Question summary
Hello there, 

I'm trying to use netdata as a container monitoring solution. Currently we scrape the unix socket that the docker daemon creates in /var/run/docker.sock. This is however slow. Parsing the cgroups is faster, however the information returned is not as rich. 

I see that I can monitor only the bytes throttled for the cgroup. Does the cgroup API allow a general "bytes read/write" monitoring on a process within that cgroup? I'm trying to understand if this is a limitation of the cgroups api in /proc of it netdata can be further extended to provide as much resolution as the docker daemon when it comes to per-container metrics. 

##### OS / Environment
Linux / CentOS Latest

##### Component Name
Cgroups and Cgroup plugin

**Comment by vlvkobal** [comment]
Netdata monitors several block io metrics for cgroups:
- I/O Bandwidth
- Serviced I/O Operations
- Throttle I/O Bandwidth
- Throttle Serviced I/O Operations
- Queued I/O Operations
- Merged I/O Operations

What you need is I/O Bandwidth. It shows the number of bytes transferred to/from the disk by the group. You can enable this chart unconditionally in `netdata.conf`
```
[plugin:cgroups]
	enable blkio bandwidth = yes
```

**Comment by vlvkobal** [comment]
If these options are set to `auto`, the charts are hidden while all dimensions are zero.

**Comment by ldelossa** [comment]
Questions are answered. Thanks
