### ISSUE TITLE
Update docs for obsolete Python modules

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5339]
Update the documentation to show the obsolete/deleted python modules:

https://github.com/netdata/netdata/blob/ad6fdf8ba3093ac6061d7f46ec628ac55f162a71/collectors/python.d.plugin/python.d.plugin.in#L59
```OBSOLETE_MODULES = ['apache_cache', 'gunicorn_log', 'nginx_log', 'cpufreq', 'cpuidle', 'mdstat', 'linux_power_supply']```
netdata/netdataAdded by GitHub

The first 3 are deleted, all others are still in the repo, but obsoleted.

**Comment by ilyam8** [comment]
> The first 3 are deleted, all others are still in the repo, but obsoleted.

all of them deleted long time ago

https://github.com/netdata/netdata/pull/5659
