### ISSUE TITLE
Uninstall script not working

### ISSUE THREAD

**Issue by jon-evm** [netdata/netdata#5341]
##### Bug report summary

Followed the uninstall from this page:
https://github.com/netdata/netdata/issues/2938

cd /usr/src/netdata.git
./netdata-uninstaller.sh --force

Then "y" gets repeated/echoed/printed over and over down the window. Waited several minutes and control+c to stop it. CPU was very high during this.

Also noticed many folders created in /tmp starting to use up the space in there. Example tmp.5n0NHvx1Sg/netdata-v1.12.0-rc3-37-gd5e1197d

Automatic updates seems to be running, I get confirmation emails. (/etc/cron.daily/netdata-updater:)

Recieved a few of these emails:
=========
ipv4.udperrors CHART
--
1m ipv4 udp receive buffer errors (was warning for 1 minute) number of UDP receive buffer errors during the last minute
=========

##### OS / Environment

CENTOS 7.6 kvm
Cpanel/WHM

##### Netdata version (ouput of `netdata -V`)

ND version - v1.12.0-rc2-52-g61e3100c

##### Steps To Reproduce

cd /usr/src/netdata.git
./netdata-uninstaller.sh --force

**Comment by paulfantom** [comment]
Please follow [official uninstallation guide](https://docs.netdata.cloud/packaging/installer/uninstall/) and not some instructions from outdated GitHub issue.

**Comment by jon-evm** [comment]
bash: netdata-uninstaller.sh: command not found

**Comment by paulfantom** [comment]
You need to download `netdata-uninstaller.sh` from git repo, located here: https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-uninstaller.sh

And invocation is: `netdata-uninstaller.sh --yes --env /etc/netdata/.environment`

**Comment by jon-evm** [comment]
I cd to etc/netdata (also tried in root directory)
wget https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-uninstaller.sh
Then netdata-uninstaller.sh --yes --env /etc/netdata/.environment
and see bash: netdata-uninstaller.sh: command not found

**Comment by cakrit** [comment]
Probably these?

```
chmod +x ./netdata-uninstaller.sh
./netdata-uninstaller.sh --yes --env /etc/netdata/.environment
```

**Comment by jon-evm** [comment]
[root@jon netdata]# ./netdata-uninstaller.sh --yes --env /etc/netdata/.environment
./netdata-uninstaller.sh: line 7: syntax error near unexpected token `newline'
./netdata-uninstaller.sh: line 7: `<!DOCTYPE html>'

**Comment by cakrit** [comment]
I'm inclined to think there is something wrong with your system. Can you please do `bash -x ./netdata-uninstaller.sh --yes --env /etc/netdata/.environment` and show us what it says? I don't see anything suspicious around line 7.

**Comment by ct2000** [comment]
hi I'm seeing the same issue ... 

`./netdata-uninstaller.sh: line 7: syntax error near unexpected token `newline'
./netdata-uninstaller.sh: line 7: `<!DOCTYPE html>'

**Comment by paulfantom** [comment]
Guys, don't blindly download things! Also verify what you are downloading. If you just blindly executed sth like `wget https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-uninstaller.sh` then you downloaded a SITE html file not a script. Link to a RAW script (without all html around it) is available at `https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-uninstaller.sh`

**Comment by paulkatsoulakis** [comment]
This looks like a resolved issue.
I will close it for now as i see that we already updated our documentation with clearer instructions to prevent such confusion in the future.

Kindly report a new issue if you find any further problems in the future @jon-evm, thanks again for getting in touch with us!

**Comment by avsion** [comment]
Hi i have the same issue can't uninstall netdata, file .enviroment is not in /etc/netdata/ directory
how can i fing this file? i'm using ubuntu 18.04 server getting the following error
./netdata-uninstaller.sh --yes --env /etc/netdata/.environment
./netdata-uninstaller.sh: line 7: syntax error near unexpected token `newline'
./netdata-uninstaller.sh: line 7: `<!DOCTYPE html>'

thank you

**Comment by cakrit** [comment]
Plz see list item 3 in https://docs.netdata.cloud/packaging/installer/uninstall/

**Comment by avsion** [comment]
Thanks i read that but can't find the file name .enviroment this is what i have in the netdata dir which one i should choose?

root@usr:/etc/netdata# ls
charts.d  custom-plugins.d  edit-config  go.d  health.d  netdata.conf  node.d  orig  python.d  ssl  statsd.d

**Comment by cakrit** [comment]
I meant list item 2. 

"If you cannot find that file and would like to uninstall Netdata, then **create new file** with following content"
