### ISSUE TITLE
How to monitor application that running within Docker container?

### ISSUE THREAD

**Issue by sohwaje** [netdata/netdata#5343]
How to monitor application that running within Docker container? 
Application such as mysql.

**Comment by Thatdarkone** [comment]
I don't think netdata can do that or perhaps i am not aware.
You could take a look at Prometheus mysql exporter https://hub.docker.com/r/prom/mysqld-exporter/

**Comment by cakrit** [comment]
You can run netdata in the container itself. You can then either access that netdata directly, or have it stream its metrics to your master. It has a low footprint that can be reduced even further, by selecting the metrics you care to monitor.

**Comment by ilyam8** [comment]
Hi @sohwaje 

> Application such as mysql.

What is the problem?

https://github.com/netdata/netdata/blob/30f7324a6cdeaefbfee2960ffcc2a3b60e58c168/collectors/python.d.plugin/mysql/mysql.conf#L150-L155



what i did:
* docker pull mysql
* docker run --name db -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123 mysql:latest
* exect to db, create `netdata` user
* add new job to netdata mysql module configuration `mysql.conf`

works
