### ISSUE TITLE
Centos 6.10, after kernel update diskstats don't work !

### ISSUE THREAD

**Issue by petarkozic** [netdata/netdata#5345]
Last night I update kernel on Centos 6.10 (WHM) server.
Kernel version: 2.6.32-954.3.5.lve1.4.59.el6.x86_64

Diskstats metrics don't show, like IO and disk operations.
I checked in netdata.conf and try to manually enable that with:

```
[plugin:proc:/proc/diskstats]
         enable new disks detected at runtime = yes
         performance metrics for physical disks = auto
         performance metrics for virtual disks = auto
         performance metrics for partitions = no
         bandwidth for all disks = auto
         operations for all disks = auto
         merged operations for all disks = auto
         i/o time for all disks = auto
         queued operations for all disks = auto
         utilization percentage for all disks = auto
        # backlog for all disks = auto
        # bcache for all disks = auto
        # remove charts of removed disks = yes
        # path to get block device = /sys/block/%s
        # path to get block device bcache = /sys/block/%s/bcache
       	# path to get virtual block device = /sys/devices/virtual/block/%s
        # path to get block device infos = /sys/dev/block/%lu:%lu/%s
```
But if I comment or uncomment this in anyway I get this error in netdata error log:

```
2019-02-07 04:18:00: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
2019-02-07 04:18:01: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
2019-02-07 04:18:02: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/diskstats' (errno 2, No such file or directory)
```
If I check for this file as root, that files is in /proc/
with root:root privileges and chmod 444

```
stat /proc/diskstats
  File: `/proc/diskstats'
  Size: 0         	Blocks: 0          IO Block: 1024   regular empty file
Device: 3h/3d	Inode: 4026532058  Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-02-07 10:08:14.477000001 +0100
Modify: 2019-02-07 10:08:14.477000001 +0100
Change: 2019-02-07 10:08:14.477000001 +0100
```

And, when I login as netdata user, files isn't exists.

```
sudo su -s /bin/bash netdata

cat /proc/diskstats
cat: /proc/diskstats: No such file or directory
```

How can I solve this, thank you ?

**Comment by Ferroin** [comment]
What are the mount options for `/proc`?  This sounds like the file isn't visible to the netdata user because of some security setting that has changed during the update.

**Comment by petarkozic** [comment]
@Ferroin 
I'm not sure what you need.
This is from /proc/self/mountinfo

`18 23 0:3 / /proc rw,relatime - proc proc rw,gid=635,hidepid=2`

**Comment by Ferroin** [comment]
@petarkozic That actually covers exactly what was needed.  Try adding the Netdata user to whatever group 635 is on your system and see if that helps.  If I'm correct about why it's not working, that should fix it.  The following command run as root should do it:

    usermod -a -G 635 netdata

**Comment by cakrit** [comment]
@paulfantom can you check if we should add this `usermod` to our installer as well?

**Comment by Ferroin** [comment]
@cakrit As a general rule, we probably should not.  At minimum, the exact group number is going to vary system-to-system, and it's only needed on some systems.  I'm not even certain that it will fix things in this case either, `hidepid` is only supposed to block access to `/proc/$PID` directories not owned by the user, so it may be something else preventing the file from being visible, I'm just suggesting it as a possible fix because if it works it's a whole lot easier than digging through SELinux rules to fix this, and significantly safer than giving out capabilities to work around it.

**Comment by petarkozic** [comment]
@Ferroin 
Yes, this resolve problem:
`usermod -a -G 635 netdata`

**Comment by paulfantom** [comment]
@cakrit we should not. We shouldn't modify user/group settings which are outside of netdata.
