### ISSUE TITLE
Update checker false positive

### ISSUE THREAD

**Issue by urbaman** [netdata/netdata#5352]
##### Bug report summary

The update checker of the web interface throws a false positive:

Your netdata version: v1.12.0-8-nightly
New version of netdata available!
Latest version: v1.12.0-8-nightly

##### OS / Environment
CloudLinux release 7.6

##### Netdata version (ouput of `netdata -V`)
netdata v1.12.0-8-nightly

**Comment by KB4284848** [comment]
Can reproduce with netdata v1.12.0-8-nightly and Raspbian 9.6 (stretch)

**Comment by cakrit** [comment]
Thanks for the report, the fix is in #5355.

**Comment by cakrit** [comment]
I should mention that the trigger was that there was a newline after the version returned by GitHub, but the code was supposed to catch these cases and it didn't.
