### ISSUE TITLE
failed to write data to database backend

### ISSUE THREAD

**Issue by Thatdarkone** [netdata/netdata#5354]
I am using prometheus as a backend which pulls metrics from my netdata instance which works great.
The only problem is netdata error logs is filled with the lines below .

`2019-02-08 10:29:37: netdata ERROR : BACKENDS : BACKEND: failed to write data to database backend '10.10.1.50:9090'. Willing to write 1498583 bytes, wrote 86880 bytes. Will re-connect.
2019-02-08 10:29:37: netdata ERROR : BACKENDS : BACKEND: reached 11 backend failures. Flushing buffers to protect this host - this results in data loss on back-end server '10.10.1.50:9090'

Why is netdata trying to write (push) to prometheus backend. Prometheus is a pull service , right ?`

my version is : netdata v1.12.0-rc3-54-g43628db

> [backend]
        # host tags =
        enabled = yes
        # data source = average
        type = opentsdb
        destination = 10.10.1.50:9090
        # prefix = netdata
        # hostname = docker01
        update every = 30
        # buffer on failures = 10
        # timeout ms = 20000
        # send names instead of ids = yes
        # send charts matching = *
        # send hosts matching = localhost *

**Comment by paulfantom** [comment]
> Why is netdata trying to write (push) to prometheus backend

Because you configured it to do it with:
> type = opentsdb
destination = 10.10.1.50:9090


Please read https://docs.netdata.cloud/backends/prometheus/

**Comment by Thatdarkone** [comment]
Thanks and yes i figured that out , the doc isn't clear though

**Comment by mehranasghari** [comment]
I get the same error, but my backend is influxdb. It was working well. I am using netdata as a docker container and netdata version is v1.28.0-196-nightly
when I restart its container the problem resolved but after hours it showed again.
How did you figure it out?

**Comment by mehranasghari** [comment]
Thanks for your attention @ilyam8. I know and I noticed my manager this topic. But we don't have this option in a running cluster.
