### ISSUE TITLE
NetData on XCP-ng dom0 CentOS

### ISSUE THREAD

**Issue by xianglo** [netdata/netdata#5357]
The @netdatalinux and @xcp-ng teams have asked me to put this here. Im hoping the community from both teams can make this happen. Perhaps get XEN Orchestra involved also. I can can peek out of rabbit holes to help in anyway I can.

**Comment by cakrit** [comment]
Hi @xianglo, we're not sure what it is that is being asked. Could you please provide a bit more background and a specific ask? Perhaps there was a reference to a thread you haven't added?

**Comment by olivierlambert** [comment]
Hey there, XCP-ng project leader. Trying to give some food for thoughts.

Currently, in Xen model, there is a privileged domain, called `dom0`, handling all the network and storage operations. When you install netdata inside it, you already got a bunch of metrics ([here is a demo host](http://95.216.43.14:19999/)), but nothing related to the particular fact that's a virtualized system, nor any Xen specific counters/data.

So when you boot, Xen is booted first, then start `dom0`, which is the privileged VM handling all the calls to start "real" VMs (`domU`'s). So the `dom0` will have indeed access to some Xen info, which could be useful to monitor.

I'm right now in the middle of gathering the kind of metrics that could be parsed and filtering on those that could be interesting for a monitoring platform :)

**Comment by cakrit** [comment]
Excellent, @ilyam8 will help move this forward.

We need a user that will act as a [sponsor](https://docs.netdata.cloud/contributing/#sponsor-a-part-of-netdata) during the implementation.
He/she will assist us with the following:

- Specify the metrics required and how they should be presented in charts. 
- Specify the alarms that would make sense for each metric.
- When the implementation passes QA, test the implementation in production.
- Use the charts and alarms in their day to day work and provide additional feedback after the collector is delivered.

So @olivierlambert you will be that sponsor? Or will you help with the first two and @xianglo with the prod testing/feedback?

**Comment by olivierlambert** [comment]
I think I can act as the sponsor. I'm in fact talking with Xen devs and other people to find exact missing metrics that could be interesting. I'll keep you posted here as soon I got new stuff!

**Comment by olivierlambert** [comment]
Okay so my first guess would be to present a new category in the right menu, eg "Xen VMs", and displaying each VM stats inside this (like it's done for containers, in fact, we could use the exact same charts)

`xentop` deliver a nice example on what could be fetched:

![capture d ecran de 2019-02-11 17-35-57](https://user-images.githubusercontent.com/1241401/52578443-82d1d200-2e24-11e9-8590-b7c8ea078499.png)

> Note: here, we don't need control domain stats itself, because it's already fetched by netdata agent

Obviously, parsing `xentop` ([sources](https://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=tools/xenstat/xentop/xentop.c;h=c46581062bf1fe7c52cba28ee09a640f0e439998;hb=HEAD)) output would be an ugly hack, ideally we should rely on `libxenstat` instead ([sources](https://xenbits.xen.org/gitweb/?p=xen.git;a=tree;f=tools/xenstat/libxenstat/src;h=a5c8107bac5b9767362beb7634dfe0054bfecd4f;hb=HEAD)), to do our own fetching.

**Comment by Ferroin** [comment]
While `dom0` stats may not be necessary, tracking the time it spends in each state in Xen's scheduler may be useful (that would be useful for all domains though), and there are some other stats that would be nice to expose that aren't necessarily tied to a particular VM (global transcendent memory stats for example).

**Comment by cakrit** [comment]
It looks like we want an internal collector for this one. @vlvkobal can you take a look at libxenstat? It looks like we can start targetting a copy of what we do with `cgroups` and add from there.

**Comment by olivierlambert** [comment]
@Ferroin you're right. It's very likely you are more a Xen expert than me (I'm more on the project/user side, than being deep into details). Feel free to catch the data you think relevant.

@cakrit Thanks, if you need anything else, let me know. I'll be able to test everything. To do that, I suppose I should be able to build a specific branch with the future modifications? I can start to work on this, where should I look for this?

**Comment by Ferroin** [comment]
@olivierlambert I'm only an 'expert' in as much as I used Xen pretty actively in the past.  It's been about 18 months since I last used it though, so I can't really give much more than just some insight on it.  I've also never used XCP, just the upstream Xen hypervisor, so there are probably some metrics for XCP platforms that are important but I don't know about.

**Comment by cakrit** [comment]
You will see a Pull Request linked to this issue (just can't tell you when right now, we'll need to look at our backlog). Every PR is on its own branch, so it's easy to get it and test it.

**Comment by olivierlambert** [comment]
@Ferroin no worries for XCP-ng metrics, we already have some via RRDs, but I'm more searching for "last 10min/1h" thing in this case. So I'm fine with the "plain" Xen way of fetching them right now! In the future, if I need more, I know where to ask :wink: 

@cakrit sure, I just wondered on the build process itself, but I'll read the doc first! :+1:

**Comment by xianglo** [comment]
Im in. enabling my issue notifications. My bad on delay

**Comment by vlvkobal** [comment]
@olivierlambert @xianglo Please test #5660. Check if chart and dimension names are correct. Should I remove or change any charts?

**The following charts should be visible:**
node metrics
- Number of CPUS
- CPU Frequency
- Memory Usage
- Freeable Transcedent Memory
- Number of Domains

domain metrics
- CPU Usage
- VCPU Usage
- Memory Reservation
- Current Number of Transcedent Memory Ephemeral Pages
- Successful Transcedent Memory Puts and Gets
- VBD<n> "Out Of" Requests
- VBD<n> Requests
- VBD<n> Read/Written Sectors
- Network<n> Received/Sent Bytes
- Network<n> Recieved/Sent Packets
- Network<n> Receive/Transmit Errors
- Network<n> Recieve/Transmit Drops

I can't get any information for networks. `xentop` always reports zero values for networks. What should I do to have these metrics reported by `libxenstat` calls?

**Comment by olivierlambert** [comment]
@vlvkobal so I cloned your branch (with `git clone --branch xenstat https://github.com/vlvkobal/netdata.git`), and then built it on a XCP-ng host directly (with `./netdata-installer.sh`).

I can't see those charts. Am I missing something?

**Comment by vlvkobal** [comment]
Please install `xen-dom0-libs-devel` and `yajl-devel` in order to compile `xenstat.plugin`.

**Comment by olivierlambert** [comment]
Now it works!

![Capture d’écran de 2019-03-24 12-28-27](https://user-images.githubusercontent.com/1241401/54878705-7e8bd200-4e30-11e9-8def-2cc279ac3105.png)
![Capture d’écran de 2019-03-24 12-28-09](https://user-images.githubusercontent.com/1241401/54878706-7e8bd200-4e30-11e9-9189-047bc78a1421.png)

Regarding the missing network values, I think it's likely related to a bug in Xen. We'll work on that.

**Comment by vlvkobal** [comment]
I've updated the plugin. Please test it again.

**Comment by olivierlambert** [comment]
Tested: it works.

![Capture d’écran de 2019-03-25 13-38-48](https://user-images.githubusercontent.com/1241401/54920402-72247980-4f03-11e9-9cf2-4af12208956a.png)


How do you select "XenServer"? (it's running on a XCP-ng node)

**Comment by vlvkobal** [comment]
It is hardcoded. I chose it because XenServer is more general, than XCP-ng. Am I wrong?

**Comment by olivierlambert** [comment]
You are :wink: XCP-ng is more community oriented and will have likely more adopters, especially with Netdata.

An alternative would be to say only "Xen", because it's more general and doesn't make any assumption on the distro where it's running (after all, this plugin parse Xen info, not the rest!)

**Comment by vlvkobal** [comment]
Thank you. I've changed the names to more general ones.

**Comment by olivierlambert** [comment]
Looks good to me and works well :+1:

**Comment by vlvkobal** [comment]
#5660 was merged. Closing this.
