### ISSUE TITLE
Netdata UPS plugin assistance

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#5358]
Hey guys,

ID10T here, curious if anyone can point me in the right direction.

I'm trying to enable the UPS plugin for netdata (Fedora), but I must be doing something stupid.

I've downloaded apcupsd.conf and apcupsd.chart.sh.

I've put apcupsd.chart.sh in /usr/libexec/netdata/charts.d/

I've put the edited version of apcupsd.conf in /etc/netdata/charts.d/

I've edited /etc/netdata/netdata.conf so that under [plugins] it states apcupsd = yes

Not appearing, I'm assuming ID10T and the documentation for this plugin is a bit bare.

Any help would be appreciated!

**Comment by Thatdarkone** [comment]
Hi,

Try running the plugin in debug mode , it should output why it's unable to run successfully

https://docs.netdata.cloud/collectors/freeipmi.plugin/#debugging

**Comment by modem7** [comment]
This is what I get when I attempt to run the chart

![captured](https://user-images.githubusercontent.com/4349962/52538889-dafacc80-2d6f-11e9-8dc2-b3bb5947a0f2.jpg)

**Comment by cakrit** [comment]
apcupsd is a BASH collector. [Debugging charts.d.plugin plugins](https://docs.netdata.cloud/collectors/charts.d.plugin/#debugging-your-collectors) is different. Please run the following instead and see what you get in the output.
```
/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 apcupsd
```
I see that the plugin requires `apcaccess`. Let's get it working and then we can have a PR to put something in the README.

**Comment by modem7** [comment]
> [alex@localhost ~]$ sudo su -s /bin/sh netdata
> sh-4.3$ /usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 apcupsd
> 2019-02-11 12:28:57: charts.d: INFO: main: started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: d                                                                                                                                                                                                                                                   ebug 1 apcupsd
> 2019-02-11 12:28:57: charts.d: INFO: main: Configuration file '/usr/lib64/netdata/conf.d/charts.d.conf' loaded.
> 2019-02-11 12:28:57: charts.d: INFO: main: Configuration file '/etc/netdata/charts.d.conf' loaded.
> 2019-02-11 12:28:57: charts.d: INFO: apache: is disabled. Add a line with apache=force in '/etc/netdata/charts.d.conf' t                                                                                                                                                                                                                                                   o enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: DEBUG: ap: is enabled for auto-detection.
> 2019-02-11 12:28:57: charts.d: DEBUG: apcupsd: is enabled for auto-detection.
> 2019-02-11 12:28:57: charts.d: INFO: cpu_apps: is disabled. Add a line with cpu_apps=force in '/etc/netdata/charts.d.con                                                                                                                                                                                                                                                   f' to enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: cpufreq: is disabled. Add a line with cpufreq=force in '/etc/netdata/charts.d.conf'                                                                                                                                                                                                                                                    to enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: example: is disabled. Add a line with example=force in '/etc/netdata/charts.d.conf'                                                                                                                                                                                                                                                    to enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: exim: is disabled. Add a line with exim=force in '/etc/netdata/charts.d.conf' to en                                                                                                                                                                                                                                                   able it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: hddtemp: is disabled. Add a line with hddtemp=force in '/etc/netdata/charts.d.conf'                                                                                                                                                                                                                                                    to enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: DEBUG: libreswan: is enabled for auto-detection.
> 2019-02-11 12:28:57: charts.d: INFO: load_average: is disabled. Add a line with load_average=force in '/etc/netdata/char                                                                                                                                                                                                                                                   ts.d.conf' to enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: mem_apps: is disabled. Add a line with mem_apps=force in '/etc/netdata/charts.d.con                                                                                                                                                                                                                                                   f' to enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: mysql: is disabled. Add a line with mysql=force in '/etc/netdata/charts.d.conf' to                                                                                                                                                                                                                                                    enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: nginx: is disabled. Add a line with nginx=force in '/etc/netdata/charts.d.conf' to                                                                                                                                                                                                                                                    enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: DEBUG: nut: is enabled for auto-detection.
> 2019-02-11 12:28:57: charts.d: DEBUG: opensips: is enabled for auto-detection.
> 2019-02-11 12:28:57: charts.d: INFO: phpfpm: is disabled. Add a line with phpfpm=force in '/etc/netdata/charts.d.conf' t                                                                                                                                                                                                                                                   o enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: postfix: is disabled. Add a line with postfix=force in '/etc/netdata/charts.d.conf'                                                                                                                                                                                                                                                    to enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: sensors: is disabled. Add a line with sensors=force in '/etc/netdata/charts.d.conf'                                                                                                                                                                                                                                                    to enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: squid: is disabled. Add a line with squid=force in '/etc/netdata/charts.d.conf' to                                                                                                                                                                                                                                                    enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: INFO: tomcat: is disabled. Add a line with tomcat=force in '/etc/netdata/charts.d.conf' t                                                                                                                                                                                                                                                   o enable it (or remove the line that disables it).
> 2019-02-11 12:28:57: charts.d: DEBUG: main: enabled charts:  ap apcupsd libreswan nut opensips
> 2019-02-11 12:28:57: charts.d: DEBUG: ap: loading module: '/usr/libexec/netdata/plugins.d/../charts.d/ap.chart.sh'
> 2019-02-11 12:28:57: charts.d: DEBUG: ap: loading module configuration: '/usr/lib64/netdata/conf.d/charts.d/ap.conf'
> 2019-02-11 12:28:57: charts.d: DEBUG: ap: not found module configuration: '/etc/netdata/charts.d/ap.conf'
> 2019-02-11 12:28:57: charts.d: WARNING: ap: command 'iw' is not found in /sbin:/bin:/usr/sbin:/usr/bin:/sbin:/usr/sbin:/                                                                                                                                                                                                                                                   usr/local/bin:/usr/local/sbin.
> 2019-02-11 12:28:57: charts.d: ERROR: ap: module's 'ap' check() function reports failure.
> 2019-02-11 12:28:57: charts.d: DEBUG: apcupsd: loading module: '/usr/libexec/netdata/plugins.d/../charts.d/apcupsd.chart                                                                                                                                                                                                                                                   .sh'
> 2019-02-11 12:28:57: charts.d: DEBUG: apcupsd: loading module configuration: '/usr/lib64/netdata/conf.d/charts.d/apcupsd                                                                                                                                                                                                                                                   .conf'
> 2019-02-11 12:28:57: charts.d: DEBUG: apcupsd: loading module configuration: '/etc/netdata/charts.d/apcupsd.conf'
> /etc/netdata/charts.d/apcupsd.conf: line 2: $'\r': command not found
> /etc/netdata/charts.d/apcupsd.conf: line 7: $'\r': command not found
> /etc/netdata/charts.d/apcupsd.conf: line 12: $'\r': command not found
> /etc/netdata/charts.d/apcupsd.conf: line 15: $'\r': command not found
> /etc/netdata/charts.d/apcupsd.conf: line 19: $'\r': command not found
> /etc/netdata/charts.d/apcupsd.conf: line 22: $'\r': command not found
> ")syntax error: invalid arithmetic operator (error token is "
> 2019-02-11 12:28:57: charts.d: DEBUG: main: activated modules:
> 2019-02-11 12:28:57: charts.d: DEBUG: main: requested to run only for: 'apcupsd'
> 2019-02-11 12:28:57: charts.d: DEBUG: main: activated charts:
> 2019-02-11 12:28:57: charts.d: DEBUG: main: run_charts=''
> 2019-02-11 12:28:57: charts.d: FATAL: main: No charts to collect data from.
> DISABLE
> charts.d: cleaning up temporary directory /tmp/.netdata-charts.d-AukDPJ8FHF ...

**Comment by modem7** [comment]
OK, I've figured it out. It was ID10T. 

Within the conf file it was as follows:

# no need for shebang - this file is loaded from charts.d.plugin

# netdata
# real-time performance and health monitoring, done right!
# (C) 2018 Costa Tsaousis <costa@tsaousis.gr>
# GPL v3+

# add all your APC UPSes in this array - uncomment it too 
declare -A apcupsd_sources=(
    ["local"]="127.0.0.1:3551"
)

# how long to wait for apcupsd to respond
apcupsd_timeout=3

# the data collection frequency
# if unset, will inherit the netdata update frequency
apcupsd_update_every=10

# the charts priority on the dashboard
apcupsd_priority=90000

# the number of retries to do in case of failure
# before disabling the module
apcupsd_retries=10

I've changed the following to:

```
# add all your APC UPSes in this array - uncomment it too declare 
-A apcupsd_sources=(
```

The "declare" function was on the wrong line and I must have skimmed over that part. 

Thanks for the debug options! Definitely helped!

**Comment by MollyBe** [comment]
Does this need editing [here](https://github.com/netdata/netdata/blob/master/collectors/charts.d.plugin/apcupsd/apcupsd.conf)
