### ISSUE TITLE
Missing build deps for automake and autoconf from the spec file

### ISSUE THREAD

**Issue by johnhomelan** [netdata/netdata#5362]
##### Bug report summary
The build process needs both autoconf and automake, however there are no BuildRequires for those packages.

##### OS / Environment
It's incorrect for all RPM based distros

##### Netdata version (ouput of `netdata -V`)

1.12,  the version of in main 

##### Component Name

netdata.spec.in 

##### Steps To Reproduce

NA 

##### Expected behavior

NA

**Comment by cakrit** [comment]
Thanks for the report. Can you do a PR for this?

**Comment by johnhomelan** [comment]
Done its PR #5363
