### ISSUE TITLE
Display/Collect processes running inside docker container

### ISSUE THREAD

**Issue by Thatdarkone** [netdata/netdata#5372]
##### Feature idea summary
additional docker metrics
##### Expected behavior

Display linux "top" like results from "docker container top "containerid" in a chart

example

> docker container top c76ef0e301d7
UID                 PID                 PPID                C                   STIME               TTY                 TIME            CMD
root            10843               10825               0                   Feb11               ?                   00:00:56        traefik

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
