### ISSUE TITLE
Change/customize order of charts in dashboard

### ISSUE THREAD

**Issue by claytonrcarter** [netdata/netdata#5374]
Thank you for netdata. It's really wonderful!

Is is possible to change the default order of the charts on the dashboard? For example, I would like to move some of the "web log" charts up to the top of the dashboard to appear right under the "system.cpu" and "system.load" charts.

Thanks!

**Comment by vlvkobal** [comment]
You can change the `priority` attribute in a chart section.

```
priority = 4220
```

**Comment by ilyam8** [comment]
@claytonrcarter 

change `priority` in `web_log` configuration file
https://github.com/netdata/netdata/blob/06a367d8762915f3cd5e06971c46e4d1535d3ae9/collectors/python.d.plugin/web_log/web_log.conf#L25-L28

**Comment by ilyam8** [comment]
You can't move it under the "system.cpu",  the best you can do is to make web_log jobs appear right after `System Overview` section.

**Comment by ilyam8** [comment]
@claytonrcarter  Change priority to 101

**Comment by claytonrcarter** [comment]
Thanks, this does the trick. Through a combination of changing the priority of various charts (both in the `etc/netdata/python.d/*` and in `etc/netdata/netdata.conf`) and disabling charts (setting `enabled = no` in `etc/netdata/netdata.conf`) I have managed to simplify the web UI quite a bit. Thank you!
