### ISSUE TITLE
litespeed_local.connections_http should reflect current connections

### ISSUE THREAD

**Issue by nullmem** [netdata/netdata#5376]
##### Expected behavior

All commercial Litespeed licenses now have unlimited connections. Therefore the expected behavior for the Litespeed plugin is to show current connections, not how many connections from 2,000 (for HTTP) or 500 (HTTPS) are remaining.

**Comment by ilyam8** [comment]
Hi @nullmem 

You mean we need to remove `conn_free` and `ssl_conn_free` dimensions from these charts, right?

https://github.com/netdata/netdata/blob/2f71662ac40e056efea2c5f2badf4b5d9df77fc7/collectors/python.d.plugin/litespeed/litespeed.chart.py#L47-L60

Could you post here `rtreport` file content, i wonder if `AVAILCONN` is still there.

**Comment by ilyam8** [comment]
Hi @lucasRolff,  could you help?

**Comment by ilyam8** [comment]
> All commercial Litespeed licenses

Since it is only `commercial` it is `help wanted`

**Comment by lucasRolff** [comment]
hmm - I kind of disagree, in terms of removing `conn_free` and `ssl_conn_free` - regardless of what the license offers (there's still people using legacy licenses that does impose a connection limit) - the limit we're checking here, is the configured limit within the server itself.

As a sysadmin, you'll still have a Max Connections set, whether it's 1000, 5000 or 100000 doesn't matter - we're counting how much of your configured limit you have used.

**Comment by ilyam8** [comment]
> As a sysadmin, you'll still have a Max Connections set, whether it's 1000, 5000 or 100000 doesn't matter - we're counting how much of your configured limit you have used.

Thanks @lucasRolff, so the limit is still in place, ok.

**Comment by ilyam8** [comment]
@nullmem 	

According input from @lucasRolff your suggested change is not needed.
