### ISSUE TITLE
charts.d plugin -- decimal values?

### ISSUE THREAD

**Issue by eric-b-hymowitz** [netdata/netdata#5382]
I've written my first charts.d collector, and it's working great, with one little SNAFU.

When I run my script in DEBUG mode, I get values to two decimal places:

```
2019-02-13 15:59:38: charts.d: DEBUG: humidity: sleeping for 1.473 seconds.
BEGIN MOC.humidity
SET humidity = 33.12
END
BEGIN MOC.temperature
SET temperature = 79.62
END
BEGIN netdata.plugin_chartsd_humidity
SET run_time = 800
END
2019-02-13 15:59:40: charts.d: DEBUG: humidity: sleeping for 4.203 seconds.
BEGIN MOC.humidity 5010000
SET humidity = 33.13
END
BEGIN MOC.temperature 5010000
SET temperature = 79.64
END
BEGIN netdata.plugin_chartsd_humidity 5010000
SET run_time = 830
END
```

But when I see my chart, it's only graphing whole numbers:

![netdata4](https://user-images.githubusercontent.com/20305120/52725831-f0dedc00-2f7f-11e9-9bce-f3ee9606c839.png)

Did I do something wrong? Or is this "just the way it is" ?

Thanks.

**Comment by ilyam8** [comment]
Hi @eric-b-hymowitz 

https://docs.netdata.cloud/collectors/plugins.d/#data-collection

> value

> is the collected value, only integer values are collected. If you want to push fractional values, multiply this value by 100 or 1000 and set the DIMENSION divider to 1000.

**Comment by eric-b-hymowitz** [comment]
D'oh.  I missed that.  Sorry.
