### ISSUE TITLE
update netdata will miss the older config 

### ISSUE THREAD

**Issue by zhangxin0112** [netdata/netdata#5386]
##### OS / Environment
centos 7
##### Netdata version (ouput of `netdata -V`)
before:
vv1.12.0-rc3
after:
netdata v1.12.0-29-g041725f
##### Steps To Reproduce

1. git clone https://github.com/netdata/netdata.git
2. git checkout v1.12.0-rc3
3. ./netdata-installer.sh --install /opt/netdata-bin
4. open ip:19999 check the version(v1.12.0-rc3)
5. vim /opt/netdata-bin/netdata/etc/netdata/orig/python.d.conf 
    --- modify the config file like open redis 
6. systemctl restart netdata
7. make sure modify has be done.
8. update netdata to the latest . 
9. git checkout master && git pull
10. ./netdata-installer.sh --install /opt/netdata-bin 

----I do the update follow the step here:
![7](https://user-images.githubusercontent.com/8244097/52772496-91fa8f00-3073-11e9-8889-c8ab5df09b91.png)

**Comment by cakrit** [comment]
Hi @zhangxin0112, this is not how you modify the configuration, you need to use `edit-config`. See the [configuration guide](https://docs.netdata.cloud/docs/configuration-guide/), it explains it very well.

**Comment by Thatdarkone** [comment]
Do you need to use edit-config ?
How about copying the conf from stock directory to /etc/netdata directory and editing using vim ?

**Comment by cakrit** [comment]
> Do you need to use edit-config ? How about copying the conf from stock directory to /etc/netdata directory and editing using vim ?

Of course, copy and edit has the same effect. You just need to know to copy the file to the right place. `edit-config` is easier for most people. 

Regarding https://github.com/netdata/netdata/issues/1646#issuecomment-463547044, the "stock version" of config file is what we ship with netdata. It is used by default, if you haven't created a "user configuration" based on that file, using `edit-config` or the copy/edit method.

**Comment by zhangxin0112** [comment]
Yep. I found it also yesterday . Thanks for your reply. Nice work.
