### ISSUE TITLE
How to get non average metrics in prometheus

### ISSUE THREAD

**Issue by flippy1345** [netdata/netdata#5393]
Hi,
is it possible to get non average values from the metrics?

I'm using netdata, prometheus and grafan, the netdata metric gets pulled by prometheus and grafan queries the metrics.

Those are a the metrics **[server_with_netdata]:19999/api/v1/allmetrics?format=prometheus&help=yes**
All values are average and this is problematic for things like ram usage where you want the exact amount, average can be 1 GB off, which can decide if something will crash or keep running.

Grafana example query:
`(netdata_system_ram_MiB_average{chart="system.ram",dimension="free",family="ram",instance="10.10.5.177:19999",job="netdata"} * 10.049)`

So my question is: is it possible in a way to get the current values?

Also it would be great to get total values like total ram.

I hop someone can help me with this

**Comment by cakrit** [comment]
Look at `source=as-collected` [here](https://docs.netdata.cloud/backends/prometheus/#netdata-support-for-prometheus)

**Comment by flippy1345** [comment]
Thank you, but now the question is where to change the data source.

**Comment by flippy1345** [comment]
Okay I got it know would be great if the wiki would contain an example:
**[netdata_server_address]/api/v1/allmetrics?format=prometheus&help=yes&_source=raw_**

**Comment by cakrit** [comment]
Can you try a PR to add this suggestion here? https://github.com/netdata/netdata/blob/master/backends/prometheus/README.md

Note that `raw` in this case is identical to `as-collected`, the documentation seems to prefer mentioning just `as-collected`.

**Comment by flippy1345** [comment]
Okay I created a push request

**Comment by cakrit** [comment]
Thanks! It's approved, we just need to get the travis glitch sorted out...
