### ISSUE TITLE
Mouse on curve should highlight the onhover curve in the legend

### ISSUE THREAD

**Issue by trebonius0** [netdata/netdata#5398]
##### Feature idea summary
When mouse hovers a graph/curve, highlight the selected curve name/value in the legend

##### Expected behavior
I have a few modules which shows response times for each route of one of my service. This service has a lot of routes (50). Therefore, I have 50 curves, which are mostly flat. Having this many curves on a graph is not a problem since I just want to see if one is really above the other or if there is latency spikes. 

When such a spike occurs, it's pretty difficult to immediatly know which route is related to this spike. 
Putting my mouse cursor over the graph should highlight it in the legend (and scroll in the legend if needed)
![image](https://user-images.githubusercontent.com/14201457/52852435-e0159e00-3118-11e9-94bc-9693c72992f0.png)
In this case, I want to identify which curve is corresponding to the 15s spike. But since I've too many graph, I have to scroll in the legend, go back go the graph, check the values, scroll back in the legend ... Pretty hard to do

Thanks !

**Comment by cakrit** [comment]
Nice idea. 

I think that you'll find the chart resize button very useful in this case. Take a look at the controls under the series and see this nice little button. 
![screenshot from 2019-02-15 14-31-31](https://user-images.githubusercontent.com/43294513/52860151-ef074b00-312e-11e9-8caa-0bd226e4fe55.png)

Click and drag until all your dimensions are shown and you won't have to do the silly scrolling thing!

**Comment by trebonius0** [comment]
I already do know this feature. But still, when you have 50 graphes, it requires the graph to be very big to see the whole legend and going through 50 lines in the legend is not fast

**Comment by Ferroin** [comment]
I would tend to agree with @trebonius0 here, having the legend automatically scroll to and in some way accentuate (bold or italics maybe?) the entry for the curve that the mouse pointer is on would be really helpful for identifying usage spikes on large graphs.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
