### ISSUE TITLE
Extend dashboard

### ISSUE THREAD

**Issue by Arnaud92BlR** [netdata/netdata#5399]
Hello all,

We would like, in addition to what netdata already does, add informations that cannot be presented in graphs. This could be typically routing table or ARP table.
How could we "extend" the dashboard to include such things ? The tables would be generated by an external daemon, either as a json or HTML file for example.

Thanks,
Arnaud

**Comment by cakrit** [comment]
@gmosx I believe this would be achieved via the 'widgets' or 'extensions' that we discussed would be possible for custom dashboards.

**Comment by gmosx** [comment]
Indeed, I plan to work on a custom data visualization library for netdata that will allow for such customizations.

**Comment by Arnaud92BlR** [comment]
That would be very helpful, indeed.
In the meantime, do you have any suggestion ? I've seen the dashboard_info_custom_example.js as a possibility to customize the dashboard: is there any other way ?

Thanks

**Comment by cakrit** [comment]
The UI is based on `index.html` and `main.js` under `/usr/share/netdata/web/`,  so you could hack it for your own goals, or even better, do a PR to extend the existing functionality. In the repo, you will find the UI html/css/js under `web/gui`.

Alternatively, you can create a [custom dashboard](https://docs.netdata.cloud/web/gui/custom/) that includes both netdata charts and whatever other content you'd need there.

**Comment by TH-HA** [comment]
Agree that the custom dashboard allow to integrate additional part , but this suffer from one main issue , it 's only static ressource. I.E it's pretty easy to generate a route.html or arp.html to display them aside of netdata graph , but this is not possible to refresh them from the UI Part. So you will need an additional webserver which is not always possible ( especially on small boxes). Using cron to refresh them is an alternative.

In addition to that , if you go with new widget to display such data, a very nice builtin feature can be to see the syslog ( or any log on the machine ) aside of netdata graph ( not a complex widget , something only allowing to remotly display ( and/or downloading ) the log files in a brut format... no search ...) .  It's , from my point of view , a key point to push even further the usage of netdata.
Regards

**Comment by cakrit** [comment]
You're absolutely correct of course, but we want to take it a bit further, at least wrt the logs. Imagine highlighting a specific section of a specific chart and getting all the **relevant** log entries around that timeframe. I'm not sure how soon we'll be able to get started on it, but it's definitely on the roadmap.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
