### ISSUE TITLE
Time Collected Alarms Issue

### ISSUE THREAD

**Issue by socomsystems** [netdata/netdata#5400]

**Comment by socomsystems** [comment]
I'm sending data from multiple nodes, about 20 to a centralized NetData server with 32Gb of RAM running Prometheus and Grafana for time series collection at soho with a residential internet connection.  Periodically or I should say at least once or twice a week the internet connection (being residential) is not so great.  When so, I'm getting inundated with "time last collected" warning and critical alarms via email.  I'm trying to figure out the best approach to take on this.

Should I increase the time last collected on each metric alarm file in health directory or is their a more global easier way to deal with this?

Thanks for direction, suggestions, experiments!

**Comment by ilyam8** [comment]
Hi @socomsystems 

To begin with... what's your netdata version?

**Comment by socomsystems** [comment]
Sorry, I should have provided that: netdata v1.12.0-rc2-51-nightly

**Comment by socomsystems** [comment]
Hi @ilyam8 the version I posted was shortly after I upgraded the primary NetData Server (one that receives all the data from nodes via streams).  It has dramatically calmed down since.  However, still getting some alarms.

E.g.

ap001 host:
net_packets.eth0.4
CHART
inbound packets dropped ratio = 2.01% 
the ratio of inbound dropped packets vs the total number of received packets of the network interface, during the last 10 minutes
ALARM
eth0.4
FAMILY
Escalated to CRITICAL
SEVERITY
Sun Feb 17 09:44:09 CST 2019 
(alarm is raised for 1 day and 20 hours)
TIME
$this >= 2
EVALUATED EXPRESSION
[ $this = 2.0134999 ]
EXPRESSION VARIABLES
The host has 5 WARNING and 3 CRITICAL alarm(s) raised.

Then it recovers in 10 minutes or so...

**Comment by ilyam8** [comment]
@socomsystems 

Was problem with a lot of `time last collected` alarms fixed after upgrade?

**Comment by socomsystems** [comment]
@ilyam8 yes to some degree, however I did find this in stream.conf which I will give an additional shot in the next coming days on all nodes.

# The buffer to use for sending metrics. 1MB is good for 10-20 seconds of data, so increase this if you expect latencies. The buffer is flushed on 
    # reconnects (this will not prevent gaps at the charts).
    buffer size bytes = 1048576

    # If the connection fails, or it disconnects, retry after that many seconds.
    reconnect delay seconds = 5

    # Sync the clock of the charts for that many iterations, when starting.
    initial clock resync iterations = 60
