### ISSUE TITLE
sensors plugin only plots sensors that have hard-coded limits

### ISSUE THREAD

**Issue by zivanfi** [netdata/netdata#5402]
`sensors.chart.py` has hard-coded limits for some sensor types. When querying sensor values, the `get_data` method checks whether there is a limit for them and discards values that are out of range. However, due to an indentation mistake, it also discards values if there are no limits for its sensor type. This is clearly not intentional, since the script has extensive code parts for other sensor types as well.

This issue can easily be fixed by correcting the indentation of the misindented line, which reveals another problem: `get_data` scales values by 1000 but the `CHARTS` constant specifies a scale factor of 1000000 for some sensors, resulting in plotting 1/1000th of the actual values for affected sensors.

**Comment by ilyam8** [comment]
@zivanfi thanks for reporting
