### ISSUE TITLE
Cannot update netdata

### ISSUE THREAD

**Issue by ZeProf2Code** [netdata/netdata#5405]
##### Bug report summary
I can't update netdata with
`bash <(curl -Ss https://my-netdata.io/kickstart.sh --no-updates)`
Error: 
`
curl: option --no-updates: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
`
Also, when at the end of the netdata's installation I got this error:
`
rm: cannot remove './netdata-updater.sh': No such file or directory
`

##### OS / Environment
Kernel : Linux 4.4.0-140-generic x86_64
OS : Ubuntu 16.04

##### Netdata version (ouput of `netdata -V`)
netdata v1.12.0-22-nightly

##### Component Name
?

##### Steps To Reproduce
Try to update netdata

##### Expected behavior
Update correctly

**Comment by paulfantom** [comment]
Parameters should be passed after parenthesis. As in docs: https://docs.netdata.cloud/packaging/installer/#one-line-installation

So this is wrong: `bash <(curl -Ss https://my-netdata.io/kickstart.sh --no-updates)`
But this is ok: `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates`

**Comment by ZeProf2Code** [comment]
Doesn't work
`
 --- Re-installing netdata... ---
$'[/root\E(B\E[0m]# \E[1m\E[33m' '' /etc/cron.daily/netdata-updater -f $'\E(B\E[0m\\n' /dev/fd/63: line 88: : command not found
 FAILED   /etc/cron.daily/netdata-updater -f

 ABORTED  Failed to forcefully update netdata
`

**Comment by ZeProf2Code** [comment]
@paulfantom

**Comment by paulfantom** [comment]
Please remove `/etc/cron.daily/netdata-updater` and try kickstart installation again.

**Comment by ZeProf2Code** [comment]
![image](https://user-images.githubusercontent.com/32982428/52919518-71486880-3303-11e9-8edd-89aea9f254cb.png)
It's not updating but no errors
![image](https://user-images.githubusercontent.com/32982428/52919529-8de4a080-3303-11e9-8793-2a16d7abca70.png)

**Comment by paulfantom** [comment]
Everything is ok. Our CD job didn't push new artifacts to GCS so updater cannot download anything newer than `v1.12.0-22-nightly`.

**Comment by ZeProf2Code** [comment]
okay :D

**Comment by paulfantom** [comment]
@cakrit we should probably change place where GUI version checker is getting its data from to prevent this kind of false-positives in the future.

I can reconfigure CI to push `packaging/version` to GCS so it would be available as https://storage.googleapis.com/netdata-nightlies/latest-version

**Comment by ZeProf2Code** [comment]
And do this error : 
`rm: cannot remove './netdata-updater.sh': No such file or directory`
That i've got at the first install important?

**Comment by cakrit** [comment]
The rm error is not important and we shouldn't be showing it.

**Comment by ZeProf2Code** [comment]
And the command in the doc is not correct : 
![image](https://user-images.githubusercontent.com/32982428/52954676-1195a000-338b-11e9-83c2-e67b154cb655.png)

**Comment by cakrit** [comment]
PR #5405 is for the documentation.
