### ISSUE TITLE
google is blocked.

### ISSUE THREAD

**Issue by jjhesk** [netdata/netdata#5410]
i was using 
bash <(curl -Ss https://my-netdata.io/kickstart.sh) to install the dashboard. It was successful the last time (v1.12.0-rc1) but it failed this time.

it is stuck at this line...

I think that is because the server is deploy in China and they have been blocked for visiting google. it stops from awaiting google response during installations..

 OK  wget -O - https://storage.googleapis.com/netdata-nightlies/sha256sums.txt 

$'[\E[2m/tmp/netdata-kickstart-txTsUv\E(B\E[0m]# \E[1m\E[33m' wget -O - https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz $'\E(B\E[0m\\n' --2019-02-18 06:18:59--  https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.220.208, 2404:6800:4005:809::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.220.208|:443... connected.
HTTP request sent, awaiting response...

**Comment by jjhesk** [comment]
I mean can you make it all standalone and not depending on googleapis please. This way more users can deploy netdata.

**Comment by cakrit** [comment]
We are looking into this with high priority. What we intend to do is have a fallback to the stable release channel, which will be getting the downloads from https://github.com/netdata/netdata/releases instead. You can see the artifacts after the description of each release, under 'assets'.  

The only other alternative you have right now is to [do the installation from source] (https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually), but that's obviously something we don't want to force users to do.

**Comment by jjhesk** [comment]
@paulfantom when is this ready? we have alot of server waiting to deploy with this lifesaving dashboard.. huge thanks!

**Comment by gmosx** [comment]
> @paulfantom when is this ready?

The milestone is scheduled for Feb 27.

**Comment by paulfantom** [comment]
@jjhesk with our [latest patch release](https://github.com/netdata/netdata/releases/tag/v1.12.2) we have introduced a stable release channel. You can now install netdata by passing `--stable-channel` parameter to `netdata-installer.sh` script. Using this will cause that all further updates will be using only packages from github.

We would appreciate any feedback if you find problems with that installation method.

**Comment by jjhesk** [comment]
got it! thank you
