### ISSUE TITLE
Hangouts Chat - Supported notifications

### ISSUE THREAD

**Issue by EnzoAkira** [netdata/netdata#5412]
Hello everyone!
In the past couple of days I have being working on a project to make alerts be send by email and other platform (in my case Hangouts Chat). 

I studied how Netdata works with other platforms (alerta.io,Rocket.Chat,Slack,etc). Then studied how Hangouts Chat API, bots, Incoming webhooks works and make something that can be integrated in Netdata.

So I managed to create a SEND_HANGOUTS through Incoming webhooks. I take from example what was made for Rocket.Chat (the principle is the same), so I created on 'alarm-notify.sh' the code to send to Hangouts. (FYI it was my first time to create something big in shell script, so if you spot an error or something wrong fill free to comment out).

```
# -----------------------------------------------------------------------------
# hangouts sender

send_hangouts() {
 local webhook="${1}" channels="${2}" httpcode sent=0 channel color payload

 [ "${SEND_HANGOUTS}" != "YES" ] && return 1

 case "${status}" in
  WARNING) color="#ffa700" ;;
  CRITICAL) color="#d62d20" ;;
  CLEAR) color="#008744" ;;
  *) color="#777777" ;;
 esac

  for channel in ${channels}; do
  payload="$(
   cat <<EOF
    {
      "cards": [
        {
          "header": {
             "title": "Netdata on ${host}",
             "imageUrl": "${images_base_url}/images/banner-icon-144x144.png",
             "imageStyle": "IMAGE"
	},
	"sections": [
           {
             "header": "<b>${host}</b>",
             "widgets": [
                {
                  "keyValue": {
                   "topLabel": "Status Message",
                   "content": "<b>${status_message}</b>",
                   "contentMultiline": "true",
                   "iconUrl": "${image}",
                   "onClick": {
                     "openLink": {
                       "url": "${goto_url}"
                      }
                     }
                  }
                 },
               {
                "keyValue": {
                  "topLabel": "${chart} | ${family}",
                    "content": "<font color=${color}>${alarm}</font>",
                    "contentMultiline": "true"
                 }
                }
              ]
            },
            {
              "widgets": [
                {
                  "textParagraph": {
                  "text": "<font color=\"#0057e7\">@ ${date}\n<b>${info}</b></font>"
                   }
                 }
               ]
             },
             {
               "widgets": [
                 {
                   "buttons": [
                     {
                       "textButton": {
                         "text": "Go to ${host}",
                         "onClick": {
                           "openLink": {
                             "url": "http://${host}:19999/"
                           }
                         }
                        }
                       }
                     ]
                    }
                 ]
       }
     ]
    }
   ]
  }
EOF
       )"

  httpcode=$(docurl -H "Content-Type: application/json" -X POST -d "${payload}" "${webhook}")

  if [ "${httpcode}" = "200" ]; then
     info "sent hangouts notification for: ${host} ${chart}.${name} is ${status} to '${channel}'"
     sent=$((sent + 1))
  else
    error "failed to send hangouts notification for: ${host} ${chart}.${name} is ${status} to '${channel}', with HTTP error code ${httpcode}."
   fi
  done

  [ ${sent} -gt 0 ] && return 0

  return 1
}
```

This code will create a card message on Hangouts like this:
![example](https://user-images.githubusercontent.com/39481527/52950361-d1c4bd80-3376-11e9-9ae8-f492608e09b9.png)

In the file **health_alarm_notify.conf** I only copied all settings from Rocket.Chat and changed to Hangouts.

For now, the only limitation I have is to resize the card message to fit more info horizontally, like is shown on the documentation of [configure Rocket.Chat alerts in Netdata](https://docs.netdata.cloud/health/notifications/rocketchat/).

**Comment by cakrit** [comment]
Awesome. We use hangouts too in some cases. Can you please do a PR, even it it's WIP? We'll give you some pointers on a few things that need to be added around the function, so that it can work exactly as all the other notification methods and we'll help with the testing.

**Comment by EnzoAkira** [comment]
Just to know, I'm still very new to GitHub PR, pull, push or merge. You can not imagine how my local repos are confusing: but it still works.

So to clarify if you do not mind giving me a procedure on how to create a PR from my repo to netdata.

Once the PR is set, I am very pleased to contribute to improving this new notification provider and to contribute some help to you!
Cheers

**Comment by cakrit** [comment]
Ok, so you to go to the netdata/netdata 'Pull Requests', press 'New Pull Request' and then click the 'Compare across forks'. It will lead to https://github.com/netdata/netdata/compare?expand=1, which allows you specify the source forked repository (your own) and the branch where you put your changes (if not master). When you create it, you'll see immediately the files changed, so you can validate that you are indeed adding what you intend to. You can then keep doing commits on your branch as you polish it, and they're reflected in the pull request. Also note the automated tests we have in there, they all need to be passing. Let me know if you need any more help, it took me a while to get my head around the various concepts in git too :)

**Comment by EnzoAkira** [comment]
Thank you for your inputs.
As you can see, I've already done a PR (# 5419), but it shows all the changes from the last merge I made and only in the end shows the files I've changed. Is there a way to clear all the merges shown in my PR?

**Comment by cakrit** [comment]
Yes, you would need to do the following on your local fork.

```
git remote add upstream https://github.com/netdata/netdata.git
git pull --rebase upstream master
```
Rebase may show a few conflicts, which you'll need to resolve manually. 
Then you can push to your 'origin master' to synchronize your remote and when you do a new PR, it will show only your changes.

**Comment by EnzoAkira** [comment]
Thank you for your help.
I managed with a work colleague to reorganize my branches and create a new PR.
Cheers

**Comment by cakrit** [comment]
The PR is very clean. I added a bunch of comments with as many explanations as I could to help you out, let us know when it's ready for us to test it.
