### ISSUE TITLE
ERROR 405: Cannot download charts index from server

### ISSUE THREAD

**Issue by ainiyt** [netdata/netdata#5418]
##### Bug report summary
ERROR 405: Cannot download charts index from server: http://192.168.199.249:19999/api/v1/charts
##### OS / Environment
 Linux Deploy &Android chroot
 Ubuntu 16.04 LTS (GNU/Linux 3.10.49-ge2cceea armv7l)
##### Netdata version (ouput of `netdata -V`)
netdata v1.12.0-22-nightly
##### 1###########
I am a Linux beginner, so the problem I am having may be simple, but I can't know what error it encountered.
I passed<(curl -Ss https://my-netdata.io/kickstart.sh)
Install netdata on a brand new system.
I have not modified any configuration.
############################

I later reinstalled netdata on the new Ubuntu 16.04 LTS. It works fine and there is no error. I want to know why it can be installed and used sometimes, sometimes it will report ERROR 405: Cannot download charts index from server: http ://192.168.199.245:19999/api/v1/charts

[error.log](https://github.com/netdata/netdata/files/2876418/error.log)

**Comment by cakrit** [comment]
Other than the apparent restart at 23:24:37, I don't see anything abnormal in that log.
I looked at older issues. Other than the issues people had with misconfigured HTTP proxies, the only other relevant thing I found was #3738. There is a chance we may have a collector generating invalid dimension names that mess up the JSON. Can you please open your browser's console (e.g. F12 on Chrome), go to network and leave it open until you get the error again? We'll hopefully be able to pinpoint where and when the problem occurs, if we have a similar situation. 

If that's difficult for you, we can start disabling metric collectors and then specific modules that may be running on your system, until we find the one causing the issue. 

I'm basing this hypothesis on the assumption that every time you start netdata exactly the same way (e.g. systemctl) and that sometimes you get the error, while others you don't, as you said in the OP.

**Comment by ainiyt** [comment]
Chrome report Failed to load resource: the server responded with a status of 401 ()
I passed bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 When reinstalling, it was found that the FAILED went.d.plugin package files checksum validation failed.
 I don't know if this has anything to do with the 405 error.
`go.d.plugin-v0.0.2.linux-arm: OK
sha256sum: go.d.plugin-v0.0.2.linux-arm64: No such file or directory
go.d.plugin-v0.0.2.linux-arm64: FAILED open or read
config.tar.gz: OK
sha256sum: WARNING: 1 listed file could not be read
 FAILED  go.d.plugin package files checksum validation failed. 

[/tmp/netdata-kickstart-2BSJ2k/netdata-v1.12.0-22-g2f71662a]# chmod a+rX /usr/libexec 
 OK   

[/tmp/netdata-kickstart-2BSJ2k/netdata-v1.12.0-22-g2f71662a]# chmod a+rX /usr/share/netdata 
 OK   

 --- Install netdata at system init --- 
I don't know what init file to install on system 'ubuntu-16.04'. Open a github issue to help us fix it.
 FAILED  Cannot install netdata init service. 

`

**Comment by ainiyt** [comment]
405 error, always exists and can't load chart.

> netdata
Real-time performance monitoring, done right!

**Comment by ainiyt** [comment]
> Other than the apparent restart at 23:24:37, I don't see anything abnormal in that log.
> I looked at older issues. Other than the issues people had with misconfigured HTTP proxies, the only other relevant thing I found was #3738. There is a chance we may have a collector generating invalid dimension names that mess up the JSON. Can you please open your browser's console (e.g. F12 on Chrome), go to network and leave it open until you get the error again? We'll hopefully be able to pinpoint where and when the problem occurs, if we have a similar situation.
> 
> If that's difficult for you, we can start disabling metric collectors and then specific modules that may be running on your system, until we find the one causing the issue.
> 
> I'm basing this hypothesis on the assumption that every time you start netdata exactly the same way (e.g. systemctl) and that sometimes you get the error, while others you don't, as you said in the OP.

I think I know the reason why netdata reported 405 error, but I can't know exactly how to solve this problem. I wonder if you are interested, use ssh connection to help me see what is causing 405 error?
   Phone model: wt88047 (I tried a lot of methods it will report 405)

**Comment by ainiyt** [comment]
When 405error appears, it will occupy port 8125, 127.0.0.1:8125 0.0.0.0:* LISTEN 9835/netdata,
Normal use does not occupy port 8125. What is the relationship between the two?

**Comment by cakrit** [comment]
The `statsd` collector uses port 8125. The new lines after the names shouldn't be there:
```
			"dimensions": {
				"cpu3_active_time": { "name": "C0 (active)" },
				"cpu3_cpuidle_state0_time": { "name": "C0
" },
				"cpu3_cpuidle_state1_time": { "name": "C1
" },
				"cpu3_cpuidle_state2_time": { "name": "C2
" }
```

Let us dig a bit and we'll either provide the fix directly, or ask you for some more info.

**Comment by cakrit** [comment]
Can you try to see if the following will fix it for you?
```
git clone --single-branch --branch cpuidle-newlineinnames https://github.com/cakrit/netdata.git nd
cd nd
./netdata-installer.sh
```
If it works, we'll merge the PR. If not, we continue looking :)

**Comment by ainiyt** [comment]
> 你能试着看看以下是否会为你解决这个问题？
> 
> ```
> git clone --single-branch --branch cpuidle-newlineinnames https://github.com/cakrit/netdata.git nd
> cd nd
> ./netdata-installer.sh
> ```
> 如果它有效，我们将合并PR。如果没有，我们继续寻找:)

Thank you very much for your help, now it works fine.
http://netdata.hm.scdu.top
