### ISSUE TITLE
How to create alarm template.

### ISSUE THREAD

**Issue by alsoeric** [netdata/netdata#5420]
##### Question summary
how do I create an alarm template for multiple cores?
##### OS / Environment
Red Hat enterprise 4.7
##### Component Name
health
##### Expected results
??

The sensors command lists the cores and temperatures shown below. The temperature graph shows each device as '''coretemp-isa-0000 temperature (sensors.coretemp_isa_0000_temperature)''' where the 0000 corresponds to the coretemp-isa-0000 device number and each graph lists all of the cores plus the physical ID. 

I want a template to trigger an alarm in any of the coretemp-isa-XXXX physical ID Y temperatures cross the warning and critical thresholds.

Reading through the other problem reports/questions, I've gotten as far as this for the template but I don't how to generalize it and also limit the temperature measured to the one associated with the physical ID.

'''
template: cpu_temp
   on: coretemp-isa-0000
units: Celsius
every: 10s
 warn: $temp > 85
 crit: $temp > 95
 info: cpu core temperature
   to: sysadmin
'''
[root@chopin health.d]# sensors
```
coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +63.0°C  (high = +93.0°C, crit = +103.0°C)
Core 0:         +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 1:         +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 2:         +56.0°C  (high = +93.0°C, crit = +103.0°C)
Core 3:         +56.0°C  (high = +93.0°C, crit = +103.0°C)
Core 4:         +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 5:         +54.0°C  (high = +93.0°C, crit = +103.0°C)
Core 8:         +56.0°C  (high = +93.0°C, crit = +103.0°C)
Core 9:         +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 10:        +56.0°C  (high = +93.0°C, crit = +103.0°C)
Core 11:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 12:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 16:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 17:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 18:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 19:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 20:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 21:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 24:        +54.0°C  (high = +93.0°C, crit = +103.0°C)
Core 25:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 26:        +55.0°C  (high = +93.0°C, crit = +103.0°C)
Core 27:        +54.0°C  (high = +93.0°C, crit = +103.0°C)
Core 28:        +55.0°C  (high = +93.0°C, crit = +103.0°C)

coretemp-isa-0001
Adapter: ISA adapter
Physical id 1:  +70.0°C  (high = +93.0°C, crit = +103.0°C)
Core 0:         +60.0°C  (high = +93.0°C, crit = +103.0°C)
Core 1:         +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 2:         +60.0°C  (high = +93.0°C, crit = +103.0°C)
Core 3:         +62.0°C  (high = +93.0°C, crit = +103.0°C)
Core 4:         +60.0°C  (high = +93.0°C, crit = +103.0°C)
Core 5:         +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 8:         +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 9:         +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 10:        +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 11:        +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 12:        +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 16:        +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 17:        +60.0°C  (high = +93.0°C, crit = +103.0°C)
Core 18:        +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 19:        +60.0°C  (high = +93.0°C, crit = +103.0°C)
Core 20:        +60.0°C  (high = +93.0°C, crit = +103.0°C)
Core 21:        +60.0°C  (high = +93.0°C, crit = +103.0°C)
Core 24:        +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 25:        +61.0°C  (high = +93.0°C, crit = +103.0°C)
Core 26:        +60.0°C  (high = +93.0°C, crit = +103.0°C)
Core 27:        +60.0°C  (high = +93.0°C, crit = +103.0°C)
Core 28:        +60.0°C  (high = +93.0°C, crit = +103.0°C)

coretemp-isa-0002
Adapter: ISA adapter
Physical id 2:  +54.0°C  (high = +93.0°C, crit = +103.0°C)
Core 0:         +47.0°C  (high = +93.0°C, crit = +103.0°C)
Core 1:         +50.0°C  (high = +93.0°C, crit = +103.0°C)
Core 2:         +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 3:         +49.0°C  (high = +93.0°C, crit = +103.0°C)
Core 4:         +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 5:         +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 8:         +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 9:         +47.0°C  (high = +93.0°C, crit = +103.0°C)
Core 10:        +49.0°C  (high = +93.0°C, crit = +103.0°C)
Core 11:        +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 12:        +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 16:        +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 17:        +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 18:        +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 19:        +46.0°C  (high = +93.0°C, crit = +103.0°C)
Core 20:        +47.0°C  (high = +93.0°C, crit = +103.0°C)
Core 21:        +47.0°C  (high = +93.0°C, crit = +103.0°C)
Core 24:        +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 25:        +49.0°C  (high = +93.0°C, crit = +103.0°C)
Core 26:        +49.0°C  (high = +93.0°C, crit = +103.0°C)
Core 27:        +48.0°C  (high = +93.0°C, crit = +103.0°C)
Core 28:        +47.0°C  (high = +93.0°C, crit = +103.0°C)

coretemp-isa-0003
Adapter: ISA adapter
Physical id 3:  +49.0°C  (high = +93.0°C, crit = +103.0°C)
Core 0:         +41.0°C  (high = +93.0°C, crit = +103.0°C)
Core 1:         +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 2:         +43.0°C  (high = +93.0°C, crit = +103.0°C)
Core 3:         +43.0°C  (high = +93.0°C, crit = +103.0°C)
Core 4:         +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 5:         +41.0°C  (high = +93.0°C, crit = +103.0°C)
Core 8:         +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 9:         +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 10:        +43.0°C  (high = +93.0°C, crit = +103.0°C)
Core 11:        +43.0°C  (high = +93.0°C, crit = +103.0°C)
Core 12:        +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 16:        +41.0°C  (high = +93.0°C, crit = +103.0°C)
Core 17:        +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 18:        +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 19:        +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 20:        +41.0°C  (high = +93.0°C, crit = +103.0°C)
Core 21:        +41.0°C  (high = +93.0°C, crit = +103.0°C)
Core 24:        +41.0°C  (high = +93.0°C, crit = +103.0°C)
Core 25:        +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 26:        +42.0°C  (high = +93.0°C, crit = +103.0°C)
Core 27:        +40.0°C  (high = +93.0°C, crit = +103.0°C)
Core 28:        +41.0°C  (high = +93.0°C, crit = +103.0°C)

```

**Comment by ilyam8** [comment]
> I want a template to trigger an alarm in any of the coretemp-isa-XXXX physical ID Y temperatures cross the warning and critical thresholds.

> Netdata also supports alarm templates, so that an alarm can be attached to all the charts of the same context (i.e. all network interfaces, or all disks, or all mysql servers, etc.).

I think you need template for dimension which is not supported currently.

See lookup section https://docs.netdata.cloud/health/#alarm-line-lookup

I suggest to use `max` method: _if at least one value > X, then alarm_

**Comment by cakrit** [comment]
Guys, this looks like we have the wrong graphs. You mean that for this example we have a single chart  that shows 3*28 dimensions? If so, then we need to take the device name and make it a 'family', with different chart names for each device. Then we can specify an alarm template for the context that includes all families. Right?

**Comment by cakrit** [comment]
The last comment may have been a bit esoteric. Essentially, if we have 3 charts instead of one, the current functionality would cover the use case.

**Comment by alsoeric** [comment]
I have 4 charts, 1 for each coretemp-isa device. each chart has 30 graphs.  core 0 to core 28 and physical 0-3.  The best solution would be triggering on any reading over limits on any graph. Showing which core/physical ID triggered the alarm would be ideal but simply getting any alarm for a over temp condition would be great.  I ok with creating 4 alarms but not 120. 

Would the max trick work if I specify the coretemp-isa-XXXX device?

Also, I'm not sure how to test the alarm. should I set the limits below the current temp readings to force a trigger?

**Comment by ilyam8** [comment]
> I ok with creating 4 alarms but not 120.

Ofc.

@alsoeric i woult try alarm template on `sensors.temperature` and `max` method

1 alarm^^

**Comment by alsoeric** [comment]
Thanks for the help. FYI, I won't be able work on this for a week. I'll update you on the success and share the template when I get back.

**Comment by alsoeric** [comment]
ok, back.

alarm file is:

> template: temperature_sensors
> on: sensors.temperature
> os: linux
> hosts: *
> lookup: max -1m
> units: Celisius
> every: 10s
> warn: $this > (($status >= $WARNING)  ? (23) : (30))
> crit: $this > (($status == $CRITICAL) ? (85) : (95))
> info: CPU core temperature
> to: sysadmin
> 

but I am getting weird temps.
bot_eb, [11.03.19 16:10]
🔴 bach.elucid.local is critical - temperature sensors
sensors.coretemp-isa-0001_temperature (temperature)
temperature sensors = 162 Celisius (https://netdata.cloud/alarms/redirect?agentID=b57e3554-b8b9-11e7-807f-782bcb47a979&host=bach.elucid.local&chart=sensors.coretemp-isa-0001_temperature&family=temperature&alarm=temperature_sensors&alarm_unique_id=1509040628&alarm_id=1508898750&alarm_event_id=103)
CPU core temperature

sensors reports: 

> coretemp-isa-0001
Adapter: ISA adapter
Core 0:       +31.0°C  (high = +79.0°C, crit = +89.0°C)
Core 1:       +23.0°C  (high = +79.0°C, crit = +89.0°C)
Core 2:       +21.0°C  (high = +79.0°C, crit = +89.0°C)
Core 8:       +23.0°C  (high = +79.0°C, crit = +89.0°C)
Core 9:       +28.0°C  (high = +79.0°C, crit = +89.0°C)
Core 10:      +29.0°C  (high = +79.0°C, crit = +89.0°C)

The alarm dump shows

>	},
		"sensors.coretemp-isa-0000_temperature.temperature_sensors": {
			"id": 1508898751,
			"name": "temperature_sensors",
			"chart": "sensors.coretemp-isa-0000_temperature",
			"family": "temperature",
			"active": true,
			"disabled": false,
			"silenced": false,
			"exec": "/usr/libexec/netdata/plugins.d/alarm-notify.sh",
			"recipient": "sysadmin",
			"source": "1@/etc/netdata/health.d/sys_temp.conf",
			"units": "Celisius",
			"info": "CPU core temperature",
			"status": "CRITICAL",
			"last_status_change": 1552335054,
			"last_updated": 1552336139,
			"next_update": 1552336149,
			"update_every": 10,
			"delay_up_duration": 0,
			"delay_down_duration": 0,
			"delay_max_duration": 0,
			"delay_multiplier": 1.000000,
			"delay": 0,
			"delay_up_to_timestamp": 1552335054,
			"value_string": "174 Celisius",
			"db_after": 1552336021,
			"db_before": 1552336080,
			"lookup_method": "max",
			"lookup_after": -60,
			"lookup_before": 0,
			"lookup_options": "",
			"warn":"$this &gt; (($status &gt;= $WARNING) ? (23) : (30))",
			"warn_parsed":"(${this} &gt; ((${status} &gt;= ${WARNING}) ? 23 : 30))",
			"crit":"$this &gt; (($status == $CRITICAL) ? (85) : (95))",
			"crit_parsed":"(${this} &gt; ((${status} == ${CRITICAL}) ? 85 : 95))",
			"green":null,
			"red":null,
			"value":174
		},

looks like I need a correction factor.

**Comment by ilyam8** [comment]
@alsoeric 	

> but I am getting weird temps.

Indeed, me too.

![Screenshot_20190312_005003](https://user-images.githubusercontent.com/22274335/54160528-d6a1fc00-4460-11e9-838a-7893cb2c9f36.png)

It seems **max** method summarizes all dimensions.

___

Ok, that is the description

> max will find the max value for the timeframe. This works on both positive and negative dimensions. It will find the most extreme value.

I see there is no mention about sum.

@cakrit @ktsaou

**Comment by alsoeric** [comment]
@ilyam8 is there any way to look at the data stream and see the raw values?

**Comment by cakrit** [comment]
Gents, this looks like a wrong divisor or multiplier. Of course I'd expect it to show up on the chart as well. Is this the python plugin? If so, instructions to debug are [here](https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module). Other plugins have similar instructions to debug.

**Comment by ilyam8** [comment]
> chart

![Screenshot_20190312_194107](https://user-images.githubusercontent.com/22274335/54218518-d0625d00-44fe-11e9-8422-e7aac91e50bf.png)

> alarm

```
alarm: temperature_sensors
 on: sensors.coretemp_isa_0000_temperature
 os: linux
 hosts: *
 lookup: max -10s
 units: Celsius
 every: 10s
 warn: $this > (($status >= $WARNING) ? (23) : (30))
 crit: $this > (($status == $CRITICAL) ? (85) : (95))
 info: CPU core temperature
 to: sysadmin
```

> alarm 
![Screenshot_20190312_194226](https://user-images.githubusercontent.com/22274335/54218625-fb4cb100-44fe-11e9-8d30-61b9f38e8e65.png)


___ 

As i said, max summarizes all dimensions.

**Comment by cakrit** [comment]
So then shouldn't we do the config like this?
`query: max -1m of package...` I don't see the rest.

**Comment by ktsaou** [comment]
`max` is used on the timeframe (find the max value for each dimension in the timeframe), not on the dimensions.

Unfortunately this is missing from the query engine. We should add it.

We should also support alarm templates for each of the dimensions matched by a simple pattern.

So this issue is about 2 enhancement requests.

**Comment by ilyam8** [comment]
> find the max value for each dimension in the timeframe

it is not clear from the docs, at least for me

**Comment by cakrit** [comment]
I will close this as duplicate, because the features are already requested in #3249 and #2107

**Comment by alsoeric** [comment]
Thanks. I am getting alarms for temps but it is the wrong value.    Temp is around 28c is this the same or a different issue? Is the number an average or a raw value that I need convert to the raw value?
  

  
bot_eb:
  
🔴 bach.elucid.local is critical - temperature sensors
  
sensors.coretemp-isa-0000_temperature (temperature)
  
temperature sensors = 221 Celisius
  
CPU core temperature
  
  

  
  
  
  
  
>

**Comment by cakrit** [comment]
> Thanks. I am getting alarms for temps but it is the wrong value. Temp is around 28c is this the same or a different issue? Is the number an average or a raw value that I need convert to the raw value? 

Right now I think your safest bet is to add alarms for each dimension separately with average instead of max. e.g. something like `lookup: average -1m unaligned of my_dimension`

**Comment by ilyam8** [comment]
Ye, @alsoeric `max` is not working for you, @cakrit's suggestion is the only way for now
