### ISSUE TITLE
/usr/bin/ld: cannot find -lcupsimage

### ISSUE THREAD

**Issue by NotSqrt** [netdata/netdata#5426]
##### Bug report summary

Hi,
When installing the current version, I have the message `/usr/bin/ld: cannot find -lcupsimage`.

It seems `libcupsimage2-dev` is a necessary dependency, but was not added in the `detect required packages` step.

##### OS / Environment

ubuntu 16.04

##### Netdata version (ouput of `netdata -V`)

`netdata v1.12.0-22-nightly`

Thanks !

**Comment by simonnagl** [comment]
Hi, I am the author of the `cups.plugin`. The plugin does not require `-lcupsimage`. #5448 should fix your issue.
