### ISSUE TITLE
Are child processes picked up by PPID, or the cmdline pattern?

### ISSUE THREAD

**Issue by ferenc0521** [netdata/netdata#5432]
##### Question summary
n00b question:
Are child processes picked up by PPID, or the cmdline pattern?
My child processes' pattern don't match the parent process's pattern, but the parent 's PID = child's PPID, so ps, top has no  problem picking up the relations.
apps.plugin doesn't seem to pick up, I have to have a pattern for the child processes too.
( I checked the issues may be related before posting)

##### OS / Environment
Ubuntu linux 64
##### Component Name
apps.plugin
##### Expected results
Snippet from apps_groups.conf  

\# File: /etc/netdata/apps_groups.conf  
\# -----------------------------------------------------------------------------
\# connect servers

covjvm: '*/data00/flazar/cov-platform/jre*'
covdb: '*/data00/flazar/cov-platform/postgres*'
covdb: '*postgres: *'

The top output: (cutting out columns) for readability

  PID     PPID  COMMAND                                                                                         
22751         1  /data00/flazar/cov-platform/postgres/bin/postgres -D /data00/flazar/cov- + 
12170 22751 postgres: coverity cim 127.0.0.1(59952) idle in transaction                            +
22157 22751 postgres: coverity cim 127.0.0.1(60287) idle                                                   +
22158 22751 postgres: coverity cim 127.0.0.1(60288) idle                                                   +
22752 22751 postgres: logger process                                                                       +
22754 22751 postgres: checkpointer process                                                                 +
22755 22751 postgres: writer process                                                                       +
22756 22751 postgres: wal writer process                                                                   +
22757 22751 postgres: autovacuum launcher process                                                          +
22758 22751 postgres: stats collector process                                                              +
22759 22751  postgres: bgworker: logical replication launcher                                               +

Problem is that the  '*postgres: *' pattern is common to all (embedded+ shared) postgresql instances, only the parent process path ( '*/data00/flazar/cov-platform/postgres*')  is unique.

The expected behavior would be that the 
covdb: '*/data00/flazar/cov-platform/postgres*'
line would be enough, it would pickup all the processes where PPID= 22751 (in this case, the PID of the parent proc) and I wouldn't need to add the 
covdb: '*postgres: *'
line.

**Comment by vlvkobal** [comment]
We are checking cmdline pattern only for grouping processes. We don't see a need to change them because it gives you flexibility.
