### ISSUE TITLE
What should be run after adding div thru javascript to populate graph in custom dashboard

### ISSUE THREAD

**Issue by TH-HA** [netdata/netdata#5433]
##### Question summary
I'm trying to create a custom dashboard which is populating  automatically a dashboard related to the network with different charts. As i want to have this dashboard generic for multiple machine and i have different interfaces , i 'm trying to use the query charts API and some javascript function to filter what should be added ( note : I'm not a web developper).

I'm able to add the different chart using the example provided by netdata , but chart remain empty.

I'm thinking about a asynchronous issue as the api request is asynchronous and the action made by the dashboard.js are already finished before the new charts are added.

Is there a method to run to populate them.

Here is a quick example ( a naive one ) which is showing what i'm doing :
The populate method run on the onload event generate nothing.
The populate method executed in the body add  the graph but they are not populated ( and they are , for some of them renamed ) 

function populate(){
        autograph();

}

function addGraph(name){
        var div = document.createElement('div');
        div.setAttribute("data-netdata",name);
        div.setAttribute("data-chart-library","dygraph");
        div.setAttribute("data-width","600");
        div.setAttribute("data-height","300");
        div.setAttribute("data-title",name);
        div.setAttribute("data-after","600");
        var parent = document.getElementById('ipdash');
        document.getElementsByTagName('body')[0].appendChild(div);
        console.log(name);

}

function autograph(){
        var request = new XMLHttpRequest();

// Open a new connection, using the GET request on the URL endpoint
request.open('GET', 'api/v1/charts', true);

request.onload = function () {
        // Begin accessing JSON data here
  var data = JSON.parse(this.response);

  if (request.status >= 200 && request.status < 400) {
        for(var chart in data.charts)
                if(chart.search("ipv4")!=-1){
                        console.log(chart);
                        addGraph(chart);
                }
  } else {
    console.log('error');
  }
  }
// Send request
request.send();

}

Regards

**Comment by gmosx** [comment]
After the placeholder divs are inserted into the DOM tree, you should call `NETDATA.updatedDom()` to notify NETDATA that the DOM is mutated and the charts need to be (re-)rendered.

It goes without saying that you need to add the `dashboard.js` script to your page, e.g.

```
<script type="text/javascript" src="https://my-netdata.io/dashboard.js?v=1"></script>
```

**Comment by TH-HA** [comment]
Thanks i'll try immediatly. I'll let you know if it works. ( if it does , it can be a good additional example of custom dashboard with automatic chart selection).

Regards

**Comment by TH-HA** [comment]
Ok , it works with an additional correction put a correct value for the data-after attribute. I was using a positive integer instead of a negative one leading to empty graph. 
What do you think about proposing this javascript function directly from dashboard.js to select easily the charts you want to display into your custom dashboard ?

**Comment by gmosx** [comment]
> What do you think about proposing this javascript function directly from dashboard.js to select easily the charts you want to display into your custom dashboard ?

Which function do you mean? `addGraph()`?

**Comment by TH-HA** [comment]
I was thinking about something more evolved allowing to automate custom dashboard creation thru javascript. 
Something like createSection(Type,ChartFilter,Parent,MaxNumberOfRows).
Create a section with the specified maxNumberOfRows , use the chart filer to automatically select the chart ( can be regexp or combination of regexp on all the attribute of a chart , context , family ....) .
The type can be an information on the kind of display you want  can be 
     RealTime : Then use the gauge and if the chart has dimension , add one gauge per dimension. 
     Historical : Then use the dygraph stacked chart 
     Combined : The put the gauge per dimension first , then an historical evolution stacked.

Also give access to special component such as log view , alarm configuration ....  

This is just an example of what i have in mind.
In addition i 'll add that : 
This can be implemented , i guess , i a way allowing to still have access to the export and if the export can include external data present in the custom dashboard it can be very powerfull.

Last , if this becoming an official api , with stability , i won't take long before someone create a web interactive dashboard builder....

Does it make sense to you ? Or i'm totally outside of the direction netdata want to take ?

**Comment by gmosx** [comment]
Actually I am working on a new Dashboard builder implemented with modern Web technologies (TypeScript, React, RxJS, etc..). The plan is to extract the client code as stand-alone npm packages. Hopefully will have something to share soon.

**Comment by TH-HA** [comment]
Thanks for the feedback. Do you search for beta tester ? :)

**Comment by gmosx** [comment]
Will ping you when we release a preview :)
