### ISSUE TITLE
Readme - News section: shows 1.11.1 as the latest release

### ISSUE THREAD

**Issue by BKPepe** [netdata/netdata#5436]
##### Bug report summary

In [readme](https://github.com/netdata/netdata#news), you can see that the latest News is from 22nd November 2018, but v1.12.0 was released 6 days ago.

**Comment by cakrit** [comment]
Thanks @BKPepe! I'm loving the 'Bug report', I've never seen the term bug used for a marketing boo boo :)

**Comment by BKPepe** [comment]
Unfortunately, the readme is again outdated. :( There isn't mention release 1.12.1, which was released 10 days ago and even now we have 1.12.2, which you guys recently released.

**Comment by cakrit** [comment]
Done, thanks again! :)
