### ISSUE TITLE
wrong netdata version in response header

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#5438]
##### Bug report summary

web UI response header show wrong version info
```
expected: Server: NetData Embedded HTTP Server v1.12.0
actual:   Server: NetData Embedded HTTP Server vv1.12.0
                                               ^^^
```                                                                  

##### OS / Environment
CentOS 7

##### Netdata version (ouput of `netdata -V`)
v1.12.0 (static build)
##### Component Name
web
##### Steps To Reproduce

curl -v http://localhost:19999/api/v1/info

##### Expected behavior

version should be `v1.12.0` not `vv1.12.0`

**Comment by cakrit** [comment]
Nice catch, thanks! PR #5440 will fix it.
