### ISSUE TITLE
Multiple Servers

### ISSUE THREAD

**Issue by LibanaAbdul** [netdata/netdata#5450]
**Hi, this system is excellent, but I would like to be able to monitor 10 servers from 1, is it possible?

If possible, please leave the link on how to do it?

Thanks**

**Comment by ilyam8** [comment]
Hi @LibanaAbdul 

Yes, this is possible.

Take a look
https://docs.netdata.cloud/streaming/

**Comment by LibanaAbdul** [comment]
Thanks!..

I have an issue :(

2019-02-21 21:35:06: netdata ERROR : STREAM_SENDER[user] : STREAM user [send to tcp:IP:19999]: failed to connect

**Comment by cakrit** [comment]
If you have already ruled out networking issues and the master is accessible on that IP and port from the slave, please post the `stream.conf` of both your master and your slave.

**Comment by LibanaAbdul** [comment]
> If you have already ruled out networking issues and the master is accessible on that IP and port from the slave, please post the `stream.conf` of both your master and your slave.

**stream.conf - Master:**

# 1. ON SLAVE NETDATA - THE ONE THAT WILL BE SENDING METRICS

[stream]
enabled = no
destination =
api key =
timeout seconds = 360
default port = 19999
send charts matching = *
buffer size bytes = 1048576
reconnect delay seconds = 5
initial clock resync iterations = 60

# 2. ON MASTER NETDATA - THE ONE THAT WILL BE RECEIVING METRICS

[API-KEY]
enabled = yes
allow from = *
default history = 3600
default memory mode = save
health enabled by default = auto
default postpone alarms on connect seconds = 60
 multiple connections = allow

[MACHINE_GUID]
enabled = no
allow from = *
history = 3600
memory mode = save
health enabled = yes
postpone alarms on connect seconds = 60
multiple connections = allow

**Comment by LibanaAbdul** [comment]
**### stream.conf - slave**

[stream]
enabled = yes
destination = tcp:ip-master:19999
api key = apikey-master
timeout seconds = 360
default port = 19999
send charts matching = *
buffer size bytes = 1048576
reconnect delay seconds = 5
initial clock resync iterations = 60

[API-KEY]
enabled = no
allow from = *
default history = 3600
default memory mode = ram
health enabled by default = auto
default postpone alarms on connect seconds = 60
multiple connections = allow

[MACHINE_GUID]
enabled = no
allow from = *
history = 3600
memory mode = save
health enabled = no
postpone alarms on connect seconds = 60
multiple connections = allow

**Comment by cakrit** [comment]
You have an issue with the API key. 
Please see [this](https://docs.netdata.cloud/streaming/#api-keys), it tells you how to get and use UUIDs.  Ensure you update the master's stream.conf with it as well (you still have `[API-KEY]`) there.

**Comment by LibanaAbdul** [comment]
> You have an issue with the API key.
> Please see [this](https://docs.netdata.cloud/streaming/#api-keys), it tells you how to get and use UUIDs. Ensure you update the master's stream.conf with it as well (you still have `[API-KEY]`) there.

![slave](https://user-images.githubusercontent.com/8950289/53252794-c088f300-368d-11e9-9b0e-a4602dd48e39.png)
![master](https://user-images.githubusercontent.com/8950289/53252796-c088f300-368d-11e9-90b0-0171a4e14268.png)

**Comment by cakrit** [comment]
Ok, so I assume you still have the problem. Another thing I noticed, was `destination = tcp:ip-master:19999`. Can you take out the `tcp:` prefix to see if that helps? I don't see such a prefix mentioned in the docs, just IP:PORT.

**Comment by LibanaAbdul** [comment]
> Ok, so I assume you still have the problem. Another thing I noticed, was `destination = tcp:ip-master:19999`. Can you take out the `tcp:` prefix to see if that helps? I don't see such a prefix mentioned in the docs, just IP:PORT.

Yes, I already did that and it didn't work. :(

**Comment by LibanaAbdul** [comment]
![image](https://user-images.githubusercontent.com/8950289/53276116-c30a3d80-36cb-11e9-94b9-09bb1cf164c7.png)

I managed to perform, however the slave looks like this :(

**Comment by cakrit** [comment]
So if I understand correctly, the error messages from the slave went away and you're now trying to see its charts from the master. That should happen by clicking a link on the top left corner menu. Can you please show what the menu on the top left corner shows you and the URL that gave you these errors? 

Also, if haven't configured netdata to use your own, local registry, can you ensure you are signed in during your tests? 

I've seen another couple of related issues, will be doing some tests today.

**Comment by cakrit** [comment]
I went through the other issues (e.g. #5479), but I don't see anything that would be related. Can you please ensure you have at netdata v1.12.1?

**Comment by LibanaAbdul** [comment]
Hi how are you? I have issue . 
![2019-02-24_18-22-36](https://user-images.githubusercontent.com/8950289/53306943-46a96300-3861-11e9-9e30-c8997263f6d4.png)
This netdata does not maintain a database for host

**Comment by cakrit** [comment]
Send me an email to chris@netdata.cloud so we can arrange a video call, I can't understand what you are doing to get this error...

**Comment by LibanaAbdul** [comment]
Hi cakrit? How are you, I have a issue the configuration that I set is erased after 12 hours or more without using the server. :s

**Comment by cakrit** [comment]
You are probably editing directly the config files provided by netdata. All your changes need to be under the `/etc/netdata` directory. So you either copy the files there and edit them, or use `/etc/netdata/edit-config`. See the answers to #5386 as well.

**Comment by LibanaAbdul** [comment]
Hi @cakrit how are you? I have a issue:

- I have a master server on 4 slave servers, and when one of them falls down or one of the slaves fails, the next notification comes from all the slaves.

": warning: apidev.mercury.cash needs attention - inbound packets dropped
net_drops.eth0 (eth0)
inbound packets dropped = 10 packets
interface inbound dropped packets in the last 10 minutes "

Question:

Should only get the alert of the one that fell, no? and not all.

Thanks!

**Comment by LibanaAbdul** [comment]
Hi @cakrit how are you? I have a issue:

I have a master server on 4 slave servers, and when one of the slaves fails, the next notification comes from all the slaves.
": warning: [hostname] needs attention - inbound packets dropped
net_drops.eth0 (eth0)
inbound packets dropped = 10 packets
interface inbound dropped packets in the last 10 minutes "

Question:

Should only get the alert of the one that fell, no? and not all.

Thanks!

**Comment by cakrit** [comment]
You aren't getting an alert **for** the slave failure, but **because of** the failure. Apparently something starts getting broadcasted to your network when that failure happens, that goes to all the slave network interfaces. They drop those packets, hence the alert. `tcpdump` on one of the slaves when this is occurring will show you what gets dropped.
