### ISSUE TITLE
[Question] make netdata show history

### ISSUE THREAD

**Issue by Seoka** [netdata/netdata#5454]
I am searching about two months now to solve this problem, but I am not getting the expected results.

##### Question summary
How to make netdata show history in the web view? I would like to be able to scroll all metrics up to for example 1 year.

##### OS / Environment
netdata conf: [link to current](http://conf.netdata.seoka.net)
shorten:
>[global]
>history = 31536028
>
>[statsd]
>private charts history = 31556952

docker container startet with:
```bash
docker run -d \
        --name netdata \
        --network web \
        --cap-add SYS_PTRACE \
        -u="netdata" \
        --group-add $(getent group docker | cut -d: -f3) \
        -e PGID=$(grep docker /etc/group | cut -d ':' -f 3) \
        -v /srv/docker/netdata/netdata.conf:/etc/netdata/netdata.conf \
        -v /srv/docker/netdata/conf.d:/usr/lib/netdata/conf.d \
        -v /srv/docker/netdata/history:/var/cache/netdata \
        -v /var/log/smartd:/var/log/smartd:ro \
        -v /proc:/host/proc:ro \
        -v /sys:/host/sys:ro \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        -v /etc/localtime:/etc/localtime:ro \
        -h netdata.seoka.net \
        --restart unless-stopped \
        --health-cmd='curl -fs -w "%{http_code}" http://localhost:19999 -o /dev/null > /dev/null 2>&1' \
        --health-interval=10s \
        --health-retries=5 \
        --health-timeout=5s \
        --health-start-period=5m \
        -l "traefik.netdata.enable=true" \
        -l "traefik.netdata.frontend.rule=Host:netdata.seoka.net" \
        -l "traefik.netdata.port=19999" \
        -l "traefik.netdata.frontend.auth.basic.usersFile=/app/data/traefik.htpasswd" \
        -l "traefik.netdataconf.enable=true" \
        -l "traefik.netdataconf.frontend.rule=Host:conf.netdata.seoka.net;Method:GET;ReplacePath:/netdata.conf" \
        -l "traefik.netdataconf.port=19999" \
        -l "traefik.netdataconf.backend.maxconn.amount=20" \
        -l "traefik.netdataconf.backend.maxconn.extractorfunc=client.ip" \
        -l "traefik.netdataconf.frontend.rateLimit.extractorFunc=client.ip" \
        -l "traefik.netdataconf.frontend.rateLimit.rateSet.new.period=60" \
        -l "traefik.netdataconf.frontend.rateLimit.rateSet.new.average=10" \
        -l "traefik.netdataconf.frontend.rateLimit.rateSet.new.burst=40" \
        netdata/netdata
```
Host System:
```bash
>uname -a
Linux seoka.net 4.19.23-1-lts #1 SMP Fri Feb 15 11:18:29 CET 2019 x86_64 GNU/Linux
>docker version
Client:
 Version:           18.09.2-ce
 API version:       1.39
 Go version:        go1.11.5
 Git commit:        62479626f2
 Built:             Mon Feb 11 23:58:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.5
  Git commit:       62479626f2
  Built:            Mon Feb 11 23:55:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

##### Component Name
all charts

##### Expected results
As I already set the [global]history = 31536028 I expected to be able to scroll back in time exactly this period of time, but netdata is showing just a little bit more than a hour.

**Comment by ilyam8** [comment]
Hi @Seoka 	

> I am searching about two months now to solve this problem

you need a backend to archive data

This should help

https://docs.netdata.cloud/docs/configuration-guide/#increase-the-metrics-retention-period

https://docs.netdata.cloud/backends/

**Comment by Seoka** [comment]
Thanks @ilyam8,
I tried this with prometheus but I disliked the need of creating all chart collections by hand.

**Comment by cakrit** [comment]
You can't have enough memory to store so much data with the current netdata. See [here](https://docs.netdata.cloud/database/ ) to understand why.
The new database which is being built (first phase in progress in #5282) will take care of that.

**Comment by Ferroin** [comment]
To clarify a bit further, with the current database, each _single_ dimension would need just over 120GB of memory to store a year's worth of history at the default one second interval.  Because Netdata's database doesn't do exponential thinning like most other TSDB's do, you can't save any space by reducing the resolution of older data without also reducing the resolution of current data.

**Comment by Seoka** [comment]
Thank you @cakrit and @Ferroin,
Well, okay - I do not have that much memory throught.
But right now I am only able to look back ~1h. Is it not possible to make at least, lets say - a week or two - visible?

On Topic of the Size of the Database - Monitoring Data is usually the same all time long - why is there no deduplication of those data? Or is this planed in the new Database Version?

**Comment by cakrit** [comment]
@Seoka please read the link I posted. It explains all the parameters and trade-offs with the current netdata.   The main parameter that matters is the collection frequency. 
You can significantly reduce memory requirements by disabling collector plugins you don't need. Fewer metrics, lower memory requirements. 

The new DB will also be compressing data. It's draft design is at https://github.com/netdata/netdata/issues/4687, a newer version will be published soon.

**Comment by Seoka** [comment]
@cakrit I already worked throw this wiki page. As I wanted to have 1sec collection frequency so I left it on default. I wanted to have 1 year of data - well I will set history down to 1,209,600 (2weeks). KSM was enabled by myself too. But I am still just able seeing about an hour on the web page. I would like to see my whole history.

**Comment by cakrit** [comment]
Ok, if you have the following:
```
[global]
history = 1209600
```

Then you should be running out of memory when you restart netdata. netdata resets it to the default only when history is > 86400 * 365

Can you please get `http://yourhost:19999/netdata.conf` so we can verify?

**Comment by Seoka** [comment]
Ha!
I spotet the reason why.
After changing the history size to 1209600 and restarting netdata, it consumes 13.7 GB of RAM, but now I am able to scroll back multiple hours. 
At least within March I will leave the link open to everyone: [conf.netdata.seoka.net](https://conf.netdata.seoka.net) it is just the configuration.
summarized:

 >   [global]
 >   history = 1209600
>
>    [statsd]
 >   private charts history = 1209600

Maybe the limit of 86400*365 is added in the wiki page?
