### ISSUE TITLE
Broken installation link on wiki

### ISSUE THREAD

**Issue by candlerb** [netdata/netdata#5462]
At https://github.com/netdata/netdata/wiki :

> More installation methods and additional options can be found at the [installation page](https://github.com/netdata/netdata/wiki/installer/#installation).

Following this link takes you to https://github.com/netdata/netdata/wiki#installation - i.e. you end up back on the same page as you were, at a non-existent anchor.

Searching the wiki pages I find https://github.com/netdata/netdata/wiki/Installation - this contains a placeholder saying to go to https://docs.netdata.cloud/packaging/installer/ - so maybe that was the right target.

**Comment by cakrit** [comment]
Thanks. Links fixed (the docker one was wrong too).
