### ISSUE TITLE
install netdata

### ISSUE THREAD

**Issue by doublejar** [netdata/netdata#5466]
##### Question summary
[/home/netdata-1.12.1]# /sbin/service netdata stop
 OK
[/home/netdata-1.12.1]# /sbin/service netdata restart
Stopping netdata...                                        [FAILED]
Starting netdata...2019-02-22 10:30:34: netdata INFO  : MAIN : /data/netdata/usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'START' '-' '-'
2019-02-22 10:30:34: netdata ERROR : MAIN : child pid 29474 exited with code 35.
                                                           [  OK  ]
 OK

OK. NetData Started!

##### OS / Environment
os  :   redhat6.7

**Comment by mfundul** [comment]
Hello @doublejar. I have a question. Did you install the static binary from the release page? How exactly did you install netdata?

**Comment by doublejar** [comment]
> Hello @doublejar. I have a question. Did you install the static binary from the release page? How exactly did you install netdata?

I was download  netdata-v1.12.1.tar.gz on this page.  https://github.com/netdata/netdata/releases
and then  
./netdata-installer.sh --install /data   or   ./netdata-installer.sh --install /data --disable-go

**Comment by mfundul** [comment]
Can you please post the netdata error log? It should be in `/data/netdata/var/log/`.

**Comment by doublejar** [comment]
> Can you please post the netdata error log? It should be in `/data/netdata/var/log/`.

> 
[error.log](https://github.com/netdata/netdata/files/2893120/error.log)

**Comment by mfundul** [comment]
This log file is very small for some reason and does not contain `2019-02-22 10:30:34` unfortunately.

**Comment by doublejar** [comment]
> This log file is very small for some reason and does not contain `2019-02-22 10:30:34` unfortunately.

yes，because I deleted the previous log，the error.log is new~~ I Reinstall 。

**Comment by cakrit** [comment]
No, there's a limit of the 200 error log entries every 1200 seconds. We just write too many `error` entries for collectors that can't be used, because the entity they monitor is not available on the system. One way around it is to disable a few of the ones you know you don't use, in the `netdata.conf` `[plugins]` section.

**Comment by doublejar** [comment]
> No, there's a limit of the 200 error log entries every 1200 seconds. We just write too many `error` entries for collectors that can't be used, because the entity they monitor is not available on the system. One way around it is to disable a few of the ones you know you don't use, in the `netdata.conf` `[plugins]` section.

ok，I will try it. Thanks

**Comment by ilyam8** [comment]
@doublejar i am not clear about the issue, if you still experiencing some problems please give more details. Feel free to reopen 😸
