### ISSUE TITLE
[FIX] RocketChat notifications not working

### ISSUE THREAD

**Issue by tctovsli** [netdata/netdata#5470]
##### Bug report summary
After configuring RocketChat notification as the documentation describes, notifications doesn't come to RocketChat.

##### Solution
The culprit of the problem, was in /usr/libexec/netdata/plugins.d/alarm-notify.sh, where rocketchat wasn't defined in the list method_names (line 146) although the script has a method for it. After adding rocketchat to this list, notifications started working.
```# -----------------------------------------------------------------------------
# List of all the notification mechanisms we support.
# Used in a couple of places to write more compact code.

method_names="
email
pushover
pushbullet
telegram
slack
alerta
flock
discord
hipchat
twilio
messagebird
pd
fleep
syslog
custom
msteam
kavenegar
prowl
awssns
"
```

On a side-note, there was also no definitions of rocketchat-recipients in health_alarm_notify.conf like all the other channels. I defined these before I found the issue with method_names.
Example of what was *not* defined in the bottom of the file: `role_recipients_rocketchat[sitemgr]="${DEFAULT_RECIPIENT_ROCKETCHAT}"`

I could make a PR, but I'm new to this project and I found this the fastest way to report the 2 issues I found.

**Comment by cakrit** [comment]
> I could make a PR, but I'm new to this project and I found this the fastest way to report the 2 issues I found.

No better way to learn! Do the PR, we welcome all contributions and you'll feel more comfortable for your second one. :)

**Comment by cakrit** [comment]
Congrats on your first PR. 
This was closed automatically when the PR was merged. You could add the role_recipients declarations as well if you like, in a different PR.
