### ISSUE TITLE
Used ram for container shows incorrectly

### ISSUE THREAD

**Issue by shinji257** [netdata/netdata#5477]
##### Bug report summary
cgroup ram reporting is showing incorrectly.  In one container (which runs a torrent client for seeding) it shows ram usage is full but when I check the netdata instance inside the container it is reporting correctly with used and cache split appropriately.  The ram allocation is 8GB + 1GB for swap (9GB total).  This container will use all free ram for disk cache (released as needed) however this ends up with NetData showing all 8GB as being used when checked from the host.

##### OS / Environment
Debian 9.7 / Proxmox 5.3-11
Kernel:  4.15.18-11-pve

##### Netdata version (ouput of `netdata -V`)
netdata v1.12.1-1-nightly

##### Component Name
I'm not sure what to use here.  It's labelled as "Used RAM without Cache within the limits for..." on the reporting.

EDIT: I believe you may be looking for cgroups.plugin collector

##### Expected behavior
The above header should exclude the disk cache.  As it stands this cache can only be flushed from the host anyways.

Added note: I don't know if this actually needs to be reported to lxc/lxd devs or proxmox instead however NetData is how I'm getting the raw data so I wanted to start here.

**Comment by shinji257** [comment]
It appears that the cgroups.plugin collector is using memory.usage_in_bytes to get memory usage in a container.  The issue is that the file reports used memory + cached memory usage.  In my case it is just disk cache and while it shouldn't be counted as used I looked and it seems that memory.stat should be used instead as it breaks it down better and is more accurate.  Indeed it does seem to do so.

memory.usage_in_bytes
`8497537024`
memory.stat
```
cache 0
rss 0
rss_huge 0
shmem 0
mapped_file 0
dirty 0
writeback 0
swap 0
pgpgin 1
pgpgout 1
pgfault 7
pgmajfault 0
inactive_anon 0
active_anon 0
inactive_file 0
active_file 0
unevictable 0
hierarchical_memory_limit 8589934592
hierarchical_memsw_limit 9663676416
total_cache 8159043584
total_rss 274038784
total_rss_huge 8388608
total_shmem 18657280
total_mapped_file 83902464
total_dirty 122880
total_writeback 0
total_swap 0
total_pgpgin 7587206
total_pgpgout 5530392
total_pgfault 7663659
total_pgmajfault 1613
total_inactive_anon 16769024
total_active_anon 275927040
total_inactive_file 3605893120
total_active_file 4534349824
total_unevictable 0
```

In the above for memory.stat I believe you would likely end up using total_cache (to represent cached memory usage) and total_rss (to represent actual used memory).  

See reference links:
https://github.com/lxc/lxcfs/issues/175#issuecomment-301594643
https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt

**Comment by vlvkobal** [comment]
By default, netdata uses the `usage_in_bytes - cache` formula. It is controlled by the `report used memory without cache = yes` option in `[plugin:cgroups]` section. You have a chart named "Used RAM without Cache..." so the option is enabled.

Could you provide screenshots of your `mem_usage_limit`, `mem_usage`, and `mem` charts for both instances of netdata (inside and outside the container)?

**Comment by shinji257** [comment]
Outside container:
![image](https://user-images.githubusercontent.com/261005/53432713-03660600-39c1-11e9-9e8b-35c8f6d078ce.png)
Inside container (sorry the specific charts were not available so I provided the closest ones):
![image](https://user-images.githubusercontent.com/261005/53432809-35776800-39c1-11e9-89e1-d915b43a0570.png)
![image](https://user-images.githubusercontent.com/261005/53432882-5e97f880-39c1-11e9-8a81-810af0c68eba.png)

Just an added note here.  I'm using the default settings for netdata.  I have not changed anything.  I did try to locate the cgroup settings but couldn't determine where to look.

**Comment by vlvkobal** [comment]
What value do you have in the `memory.use_hierarchy` for the container?

**Comment by shinji257** [comment]
It is set to 1 right now.

**Comment by vlvkobal** [comment]
The question is, why `cache` is zero in your `memory.stat`. Is it an OS bug?

As far as `usage_in_bytes = rss + cache` (according to the kernel documentation), using `total_cache` instead of `cache` is not correct. On the other hand, in this particular case, we have nothing except `total_` counters.

> total_\<counter\> - hierarchical version of \<counter\>, which in addition to the cgroup's own value includes the sum of all hierarchical children's values of    \<counter\>, i.e. total_cache

@paulfantom @Ferroin any thoughts?

@shinji257 are there any child cgroups in the cgroup of your container?

**Comment by paulfantom** [comment]
@shinji257 could you post the execution command/docker-compose for how you started netdata container?

**Comment by shinji257** [comment]
@vlvkobal There shouldn't be.  It's just a Debian 9.7 LXC container.  It doesn't run docker or anything of the sort inside it.
@paulfantom Netdata isn't running as a container.  It is running directly on a Proxmox host which uses LXC (not docker) containers.

**Comment by shinji257** [comment]
@vlvkobal Is this maybe what you were expecting?
```
shinji@zeus:/sys/fs/cgroup/memory/lxc/103/ns$ cat memory.stat
cache 8205729792
rss 201195520
rss_huge 0
shmem 69816320
mapped_file 85020672
dirty 8192
writeback 0
swap 149991424
pgpgin 1714153452
pgpgout 1712102513
pgfault 1443464672
pgmajfault 62585
inactive_anon 148713472
active_anon 122286080
inactive_file 911323136
active_file 7224549376
unevictable 0
hierarchical_memory_limit 8589934592
hierarchical_memsw_limit 9663676416
total_cache 8205729792
total_rss 201195520
total_rss_huge 0
total_shmem 69816320
total_mapped_file 85020672
total_dirty 8192
total_writeback 0
total_swap 149991424
total_pgpgin 1714153452
total_pgpgout 1712102513
total_pgfault 1443464672
total_pgmajfault 62585
total_inactive_anon 148713472
total_active_anon 122286080
total_inactive_file 911323136
total_active_file 7224549376
total_unevictable 0
```

**Comment by vlvkobal** [comment]
Exactly. If you had such stats in `memory.stat`, you would get correct charts for your container.

**Comment by shinji257** [comment]
So I'm digging into this on my end and everything you are likely expecting seems to be nested under /sys/fs/cgroup/memory/lxc/<container>/ns.  My containers are unprivileged so they lack system.slice and user.slice folders in there but the privileged ones show up right (other than also being nested under /ns).  Is there any chance that the plugin could be updated to detect when those values are all zero and check for a /ns nesting or is there a way I could set this up on my end?

As a reference point (in case no one noticed) the memory.stat that I did push was done in the host however (just in case it was missed) the top half mirrors the lower half.  cache == total_cache, rss == total_rss, and so on.  The normal memory.stat however for the host itself (not a container) it shows differing values.

The LXC version in use by Proxmox (when I checked) is 3.10-devel.

**Comment by shinji257** [comment]
Figured out how to get the current config and noticed this.

```
        # enable cgroup lxc = no
        # search for cgroups under /lxc = yes
        # enable cgroup casper.robertpendell.com = yes
        # search for cgroups under /lxc/100 = yes
        # search for cgroups under /lxc/100/ns = no
        # meminfo filename to monitor = /proc/meminfo
        # enable cgroup hermes.robertpendell.com = yes
        # search for cgroups under /lxc/103 = yes
        # search for cgroups under /lxc/103/ns = no
```

Any ways to default that to use the /ns instead?  I could add in lines manually for each container to toggle it but I'd rather it do so dynamically.

**Comment by vlvkobal** [comment]
You can change default pattern using the `search for cgroups in subpaths matching` parameter.
```
search for cgroups in subpaths matching =  !*/init.scope  !*-qemu  !*.libvirt-qemu  !/init.scope  !/system  !/systemd  !/user  !/user.slice  /lxc/*/ns  !/lxc/*/*  *
```

**Comment by vlvkobal** [comment]
I've found some information related to the `ns` folder on Proxmox forum:
https://forum.proxmox.com/threads/weird-new-structure-in-my-cgroups.31165/
https://forum.proxmox.com/threads/i-o-disk-limit.28591/page-2#post-167730

**Comment by shinji257** [comment]
I tried this and it lets it go even deeper now but doesn't pick up memory.stat from /lxc/<container>/ns instead opting to use memory.stat from /lxc/<container> instead.  Any way to override this from my end?  It is apparent that the movement of the information you need is intentional.

**Comment by shinji257** [comment]
I got pointed at their current patches.  Specifically patches 4-6 which do this separation.

https://git.proxmox.com/?p=lxc.git;a=tree;f=debian/patches/pve;hb=HEAD

**Comment by vlvkobal** [comment]
@shinji257 could you test #5592? Does it resolve the issue?

**Comment by shinji257** [comment]
I tested this and it seems to resolve the above reported issue.  I'm getting correct and expected reporting now.  However I noticed a different issue and I suspect a different commit did this (although I don't know why) or if it is some effect on my system that I had not noticed.  Either way I'll open a separate issue ticket if I can reproduce it locally in a test setup and work it out from there as I had seen it crop up on a clean (and new) install after purging everything with the uninstall script.

**Comment by shinji257** [comment]
Everything looks good to me now after the fix applied for the previous named issue. :)

**Comment by vlvkobal** [comment]
The fix was merged. Thank you @shinji257 for your cooperation!

**Comment by junsionzhang** [comment]
> The fix was merged. Thank you @shinji257 for your cooperation!

halo,I came into the same problem in docker environment ,but not netdata. I just wonder whether it is a cgroup bug and what is the solution for it now, thank you in advance

**Comment by ilyam8** [comment]
@junsionzhang hi 👋 

Could you give more details? What values do you see? Why do you think they are incorrect?
