### ISSUE TITLE
Should not show statsd events received by default

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#5481]
```
[statsd]
    add dimension for number of events received = yes
```

I believe automatically adding the above dimension to statsd charts is confusing for newcomers. 
IMO, the default value should be `no`.

**Comment by vlvkobal** [comment]
We have a quite clear explanation of the metric in our documentation: **the number of times it was updated (events)**. I don't think anybody is confused with it.

**Comment by ilyam8** [comment]
I tend to agree with @gmosx

It is clear what is `events`, yes, but it should be disabled by default.

**Comment by cakrit** [comment]
But changing a default to remove something is not the same as changing a default to add something. You don't know who may be using it already and for what. These people will just see the metric disappear and will have to go and manually enable it again.
