### ISSUE TITLE
"Other servers" menu doesn't show remote streaming servers while not logged into nedata.cloud

### ISSUE THREAD

**Issue by RX14** [netdata/netdata#5482]
Remote host is accessible as normal on `/host/alarm/`, and shows the dashboard as normal. The charts update fine. However there's no link in the server switcher menu to switch between hosts, because the whole menu is replaced by a "Please sign in to netdata.cloud" message. Upon signing in, the host appears in the menu as normal.

```
$ netdata -V
netdata v1.12.1-7-g86ed3869
```

**Comment by cakrit** [comment]
Hi @RX14, this is is by design. This way, no URLs and hostnames are sent to the global netdata registry, without explicit user action. Please see #3990 section "login to enable the registry" and the issues linked to it, like #2760.

**Comment by RX14** [comment]
This is about instances streaming data to the netdata instance. It doesn't need to send or recieve data from netdata.cloud to see the server.

**Comment by cakrit** [comment]
You're right, actually the source of information is different for the replicated hosts, it comes from `/api/v1/charts` and not the registry. So we can definitely show those without requiring information to be sent to the registry.
