### ISSUE TITLE
centos6: python.d.plugin zombie process after netdata restart

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#5491]
##### Bug report summary

Simetimes, zombie processes exist after restarting netdata.

```
$ ps faxu | grep netdata | grep -v grep
netdata   3931  0.2  4.2 139372 20112 ?        S    13:00   0:01 /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata   4244  0.0  0.0      0     0 ?        Z    13:00   0:00  \_ [postqueue] <defunct>
netdata   4295  0.3  3.1  15924 14592 ?        Sl   13:00   0:01 /opt/netdata/bin/srv/netdata -P /opt/netdata/var/run/netdata/netdata.pid
netdata   4316  0.1  3.8 137428 18124 ?        S    13:00   0:00  \_ /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata   4608  0.0  0.0      0     0 ?        Z    13:00   0:00  |   \_ [postqueue] <defunct>
netdata   4317  0.0  1.1 110840  5260 ?        Sl   13:00   0:00  \_ /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
root      4318  0.5  0.2   1456  1020 ?        S    13:00   0:02  \_ /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
```

##### OS / Environment

OS: CentOS release 6.3 (Final)
kernel: 2.6.32-696.18.7.el6.x86_64

##### Netdata version (ouput of `netdata -V`)

netdata v1.12.1 (static binary)
(compile from source don't have this issue)

##### Component Name

daemon

##### Steps To Reproduce

service netdata restart
ps aux | grep netdata

##### Expected behavior

netdata children processes should exist when parent process exists.

**Comment by ilyam8** [comment]
what i did:
 * installed centos6 (`2.6.32-754.10.1.el6.x86_64`)
 * installed netdata v1.12.1 static binary

Problem:

i see no SIGHUP for `python.d.plugin` process on `service netdata restart` (in strace output).

Python process dies only on SIGPIPE. If it doesn't write anything it will stay forever.

Solution:
 - add a _heartbeat_ func to python.d.plugin


Still it is not clear why there is no SIGHUP on netdata process restart.

**Comment by cakrit** [comment]
Isn't it just the `postfix` module that has the issue? That's the one calling `postqueue`.
From what I've seen, we don't get SIGHUP, but we do get SIGTERM. Perhaps the process for `postqueue` should  also receive a SIGTERM and it doesn't?

**Comment by ilyam8** [comment]
Ye ye, it is `SIGTERM`, but still, i did a `strace -p <python.d.plugin pid>` and i see no `SIGTERM` on restart

**Comment by ilyam8** [comment]
@cakrit this is only true for static binary.

Child process receives SIGTERM if netdata is built from source.

from source:
```
[root@localhost ~]# strace -p 26950
Process 26950 attached
select(0, NULL, NULL, NULL, {0, 318126}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=26918, si_uid=498} ---
+++ killed by SIGTERM +++

```

**Comment by mfundul** [comment]
Just a shot in the dark here, could it be again a difference between musl libc and glibc? In particular, how a process with pre-existing Pthreads behaves when forking. This is going to be tricky to track down.

**Comment by ilyam8** [comment]
i tested static binary on both manjaro and centos6, the problem is only on centos6.

**Comment by ilyam8** [comment]
@mfundul my PR fixes the bug, but, i'd, say it is workaround.

Not sending `SIGTERM` (according my tests, static binary on centos6) to child process problem on main process restart is still exist, if you think this is important please open a new issue.

**Comment by Wing924** [comment]
The zombie become less, but it still happen on v1.13.0.
```
$ uname -r
2.6.32-504.el6.x86_64

$ cat /etc/redhat-release
CentOS release 6.6 (Final)

$ /opt/netdata/usr/sbin/netdata -V
netdata v1.13.0

$ ps fax | grep netdata | grep -v grep
14644 ?        SN     2:01 /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
  775 ?        SN     1:53 /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
31034 ?        SNl    1:36 /opt/netdata/usr/sbin/netdata -P /opt/netdata/var/run/netdata/netdata.pid
31055 ?        SNl    0:22  \_ /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
31059 ?        SNl    0:05  \_ /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
17917 ?        SN     1:12  \_ /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
```

**Comment by ilyam8** [comment]
i can't reproduce it.

[netdata static binary](https://github.com/netdata/netdata/releases/download/v1.13.0/netdata-v1.13.0.gz.run)

```
[root@localhost ~]# uname -r
2.6.32-754.10.1.el6.x86_64
[root@localhost ~]# cat /etc/redhat-release 
CentOS release 6.10 (Final)
[root@localhost ~]# /opt/netdata/usr/sbin/netdata -v
netdata v1.13.0
```

**Comment by Wing924** [comment]
@ilyam8 
It not static binary, it's compile from source.
And it's a very very rare case.
Only 1 server happen while 20k+ servers don't have this issue.
