### ISSUE TITLE
Installer at  https://my-netdata.io/kickstart.sh isnt updated to master branch?

### ISSUE THREAD

**Issue by elfgoh** [netdata/netdata#5492]
##### Bug report summary
I am installing netdata over a spotty connection and have gotten my PRs merged to address the network quality
- #5476 
- #5468 

I am installing netdata using this command as documented: `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

It seems like for some reason, the installer script at https://my-netdata.io/kickstart.sh isnt updated to [master branch](https://github.com/netdata/netdata/blob/master/packaging/installer/kickstart.sh). Differences are shared below. Additional question, would it make more sense to change the installation command to `bash <(curl -Ss https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/kickstart.sh)`?

```
$ diff kickstart.sh  kickstart.latest.sh
119c119
< 		run curl -L --connect-timeout 5 --retry 3 "${url}" >"${dest}" || fatal "Cannot download ${url}"
---
> 		run curl -sSL --connect-timeout 10 --retry 3 "${url}" >"${dest}" || fatal "Cannot download ${url}"

$ shasum kickstart.sh
219b16df864bcf65af9b198acb6e66aea9472b28  kickstart.sh

$ shasum kickstart.latest.sh
e216300bd933e5f7d8df5becd303d90b0249e2e8  kickstart.latest.sh
```

##### OS / Environment
NA

##### Netdata version (ouput of `netdata -V`)
NA

##### Component Name
Installer

##### Steps To Reproduce
- Download  https://my-netdata.io/kickstart.sh
- Compare the 2 files

##### Expected behavior
- Both files should be the same

**Comment by cakrit** [comment]
Every time kickstart.sh or kickstart-static64.sh is updated, two additional manual actions are required to publish them: 
- Install them on my-netdata.io
- Update the installer README.md with the correct md5sums

This was done on purpose, for a reason similar to why the nightly builds are behind the master branch by up to 1 day, to prevent errors that we may have not caught until after the PR is merged. I do agree that it's causing some headaches and we need to always remember these extra steps, but we haven't decided to remove them. 

We'll get on it and write here when they are completed.

**Comment by cakrit** [comment]
Both scripts are updated and the md5sums on the docs too.

**Comment by paulfantom** [comment]
Closing as everything from report is already fixed.
