### ISSUE TITLE
Updater: Curl / wget output in stdout and thus mauled every day

### ISSUE THREAD

**Issue by arjanvlek** [netdata/netdata#5493]
#### Summary
The following gets outputted / mailed every day since Saturday:

/etc/cron.daily/netdata-updater:
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed

 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
28 3453k   28  984k    0     0  2853k      0  0:00:01 --:--:--  0:00:01 2844k
100 3453k  100 3453k    0     0  6278k      0 --:--:-- --:--:-- --:--:-- 6267k

This does not say anything so I think it should go to a debug log or so.

**Comment by wmtech-1** [comment]
Yes, seems like the updater is messed up again...

**Comment by paulfantom** [comment]
This should be fixed by #5485

**Comment by paulkatsoulakis** [comment]
This is indeed resolved with the mentioned PR, resolving.
Kindly open a new issue if you face any problems
