### ISSUE TITLE
Compilation warning on Fedora 28

### ISSUE THREAD

**Issue by alsoGAMER** [netdata/netdata#5494]
##### Bug report summary
Warning while compiling proc_diskstats.c
![image](https://user-images.githubusercontent.com/35269770/53323432-6c288200-38de-11e9-8cb9-d044865a1c96.png)

##### OS / Environment
NAME=Fedora
VERSION="28 (Twenty Eight)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"

GCC Version: gcc version 8.2.1 20181215 (Red Hat 8.2.1-6) (GCC)
##### Netdata version (ouput of `netdata -V`)
v1.12.1-10-nightly

##### Component Name
Install / Build (proc_diskstats.c)

##### Steps To Reproduce
Get a Fedora 28 Workstation iso, upgrade all packages and install netdata

**Comment by ilyam8** [comment]
same on ubuntu 18.04 btw

**Comment by cakrit** [comment]
This a `glibc` bug that we can't do anything about. I believe it's [this one](https://github.com/sahlberg/libnfs/issues/202).
