### ISSUE TITLE
Grafana add up metrics from same source but different dimension - Netdata

### ISSUE THREAD

**Issue by flippy1345** [netdata/netdata#5500]
Hi,
I have the problem that metrics from the same source but with different dimensions can't be added up, subtracted or ...etc.

```
netdata_system_ram{chart="system.ram",family="ram",dimension="used"}
+netdata_system_ram{chart="system.ram",family="ram",dimension="free"} 
```
Can't be processed, while something like:
```
netdata_system_ram_used{chart="system.ram",family="ram"}
+netdata_system_ram_free{chart="system.ram",family="ram"}
```
would work.

Both statements would result in a single metric with 1 value.
```
netdata_system_ram{chart="system.ram",family="ram",dimension="used"}

netdata_system_ram_used{chart="system.ram",family="ram"}
```
I have attached an image, with the top not being able to be added up and the bottom being able to be added up.
![image](https://user-images.githubusercontent.com/26430962/53330766-a3ebf580-38ef-11e9-9427-6406a4dc5a55.png)

**Comment by flippy1345** [comment]
If I want to do this:
`netdata_system_ram{chart="system.ram",family="ram",dimension="free"} + netdata_system_ram{chart="system.ram",family="ram",dimension="used"}`

I get the following JavaScript error:

**Message:**
Cannot read property 'text' of undefined

**Stack Trace:**
```
TypeError: Cannot read property 'text' of undefined
    at e.setTableColumnToSensibleDefault (http://172.30.64.177:3000/public/build/0.be20b78823b4c9d93a84.js:7:275620)
    at e.tableHandler (http://172.30.64.177:3000/public/build/0.be20b78823b4c9d93a84.js:7:275272)
    at Array.map (<anonymous>)
    at e.onDataReceived (http://172.30.64.177:3000/public/build/0.be20b78823b4c9d93a84.js:7:274736)
    at o.emit (http://172.30.64.177:3000/public/build/vendor.2305a8e1d478628b1297.js:15:520749)
    at t.emit (http://172.30.64.177:3000/public/build/app.5331f559bd9a1bed9a93.js:1:29217)
    at e.handleQueryResult (http://172.30.64.177:3000/public/build/0.be20b78823b4c9d93a84.js:7:19860)
    at u (http://172.30.64.177:3000/public/build/vendor.2305a8e1d478628b1297.js:43:68722)
    at http://172.30.64.177:3000/public/build/vendor.2305a8e1d478628b1297.js:43:69127
    at f.$digest (http://172.30.64.177:3000/public/build/vendor.2305a8e1d478628b1297.js:43:74824)
```

**Comment by flippy1345** [comment]
> If I want to do this:
> `netdata_system_ram{chart="system.ram",family="ram",dimension="free"} + netdata_system_ram{chart="system.ram",family="ram",dimension="used"}`
> 
> I get the following JavaScript error:
> 
> **Message:**
> Cannot read property 'text' of undefined
> 
> **Stack Trace:**
> 
> ```
> TypeError: Cannot read property 'text' of undefined
>     at e.setTableColumnToSensibleDefault (http://172.30.64.177:3000/public/build/0.be20b78823b4c9d93a84.js:7:275620)
>     at e.tableHandler (http://172.30.64.177:3000/public/build/0.be20b78823b4c9d93a84.js:7:275272)
>     at Array.map (<anonymous>)
>     at e.onDataReceived (http://172.30.64.177:3000/public/build/0.be20b78823b4c9d93a84.js:7:274736)
>     at o.emit (http://172.30.64.177:3000/public/build/vendor.2305a8e1d478628b1297.js:15:520749)
>     at t.emit (http://172.30.64.177:3000/public/build/app.5331f559bd9a1bed9a93.js:1:29217)
>     at e.handleQueryResult (http://172.30.64.177:3000/public/build/0.be20b78823b4c9d93a84.js:7:19860)
>     at u (http://172.30.64.177:3000/public/build/vendor.2305a8e1d478628b1297.js:43:68722)
>     at http://172.30.64.177:3000/public/build/vendor.2305a8e1d478628b1297.js:43:69127
>     at f.$digest (http://172.30.64.177:3000/public/build/vendor.2305a8e1d478628b1297.js:43:74824)
> ```

Okay I was able to get the error message away I was on Table instead on Time series

**Comment by paulfantom** [comment]
Since your grafana is getting data from prometheus then this is not a problem of netdata but of you prometheus configuration or promQL query.

**Comment by flippy1345** [comment]
I just saw that I accidentally opened the issue for netdata instead of grafana, sorry about that.
But if I resolve this on grafanas side should I comment it her just for others to see ?

**Comment by paulfantom** [comment]
Yes, please :+1:

**Comment by ilyam8** [comment]
@flippy1345 have you openned issue in the grafane repo? if so please add a link to it.

since the problem is not netdata related i am closing the issue
