### ISSUE TITLE
How to generate snapshot dynamically?

### ISSUE THREAD

**Issue by skuindian** [netdata/netdata#5501]
I have started using netdata to get the performance monitoring just a week back, previously I was using my own tool for the same.  

**Thanks for the great tool, it seems i was missing a GEM and should adopt earlier.**

Once I was exploring the netdata i came with some use case which I thought will be effective in-terms of measuring the performance.

**Use Case:**
- Start netdata.
- Run test cases.
- Generate the snapshot after the test execution.
- Send a report with the snapshot information (by using jenkins). 

##### Question summary
How to generate snapshot dynamically?
##### OS / Environment
Linux/Jenkins
##### Component Name
netdata
##### Expected results
- Way to generate dynamic snapshot.
- Configure netdata to automatically generate snapshot over some time.

**Comment by cakrit** [comment]
At the moment this is all done in Javascript (see `web/gui/main.js` `saveSnapshot`), so you'd be looking into a test framework than can have the netdata UI running before preparing the data and calling that method (unless if you simulate all the clicks on the modal of course, which would be harder). We have plans to do a lot more with snapshots in the future, but we haven't started on that work yet, so we can't give you a good estimation of when something better/easier will be available right now. 

Adding @gmosx, in case he'd like to add something.

**Comment by gmosx** [comment]
Maybe @ktsaou can come up with a temp workaround?

**Comment by skuindian** [comment]
Thanks for update, I have simulated the specified scenario using the **"Python + Selenium".**

With this solution:
- Start netdata in host (or in container)
- Start Test Execution.
- Automate to click on the "Export" and save the snapshot in specified location.
- Archive the snapshot in some place and send a automated mail with the snapshot information.

**Thanks for your attention...**
