### ISSUE TITLE
Interpolate chart

### ISSUE THREAD

**Issue by razielin** [netdata/netdata#5506]
Hello.
I would like to collecting a metric once per minute. It is possible to interpolate values between the collected samples?
Ideally, I want something like the built-in netdata's chart "load", which collects its metrics every five seconds but the graph is smooth with no gaps between metrics.
Right now my graph looks like this
![screenshot_20190225_170141](https://user-images.githubusercontent.com/19653237/53347749-6fddf800-3922-11e9-9ab8-6bf2a0d2a458.png)

**Comment by ilyam8** [comment]
> Ideally, I want something like the built-in netdata's chart "load", which collects its metrics every five seconds but the graph is smooth with no gaps between metrics.

This is how it works, i think something is wrong with your code. Please share, i'll try to find the problem.

**Comment by razielin** [comment]
> This is how it works, i think something is wrong with your code. Please share, i'll try to find the problem.

It is the whole plugin.
``` bash
reboot_required_check() {
return 0
}

reboot_required_create() {
cat <<EOF
CHART system.reboot_required '' "File Exists /var/run/reboot-required" "boolean" reboot_required reboot_required
DIMENSION is_required '' 'incremental'
EOF
return 0
}

reboot_required_update() {
local is_reboot_required=0
if [[ -f /var/run/reboot-required ]]; then
    local is_reboot_required=1
fi
cat <<VALUESEOF
BEGIN system.reboot_required
SET is_required = ${is_reboot_required}
END
VALUESEOF

return 0
}
```

**Comment by ilyam8** [comment]
```bash
reboot_required_update_every=5

reboot_required_check() {
return 0
}

reboot_required_create() {
cat <<EOF
CHART system.reboot_required '' "File Exists /var/run/reboot-required" "boolean" reboot_required reboot_required line 1000 $reboot_required_update_every
DIMENSION is_required '' 'incremental'
EOF
return 0
}

reboot_required_update() {
local is_reboot_required=0
if [[ -f /var/run/reboot-required ]]; then
    local is_reboot_required=1
fi
cat <<VALUESEOF
BEGIN system.reboot_required $1
SET is_required = ${is_reboot_required}
END
VALUESEOF

return 0
}
```

**Comment by ilyam8** [comment]
> I would like to collecting a metric once per minute.

change `reboot_required_update_every=5` to `reboot_required_update_every=60` and this is it.

I tested code from my prev post, it works.

I am closing the issue, if you still have any question feel free to ask.
