### ISSUE TITLE
Docker containers resources missing unless a netdata full restart executed

### ISSUE THREAD

**Issue by Thatdarkone** [netdata/netdata#5512]
Hello,

Not sure if i am missing something , but i find this frustrating when it comes to displaying docker container resources such as cpu,mem,disk and eth0, they won't show up in the GUI unless i restart netdata, we are talking about ephemeral containers

The most frustrating is that sometimes netdata will show the container ID and not its name until i restart netdata. 

Would you suggest running the script below in a cron, so that whenever i deploy new containers, netdata would pick up their names without requiring a full restart ?

/usr/libexec/netdata/plugins.d/cgroup-name.sh

Still not sure why the others container resources(disk,eth0...) do not show immediately for newly(ephemeral) created containers

BTW i am running netdata locally on the host.

##### OS / Environment
Centos 7.6
netdata v1.12.0-rc3-54-g43628db

##### Component Name
cgroup/container

**Comment by SuperSandro2000** [comment]
At least for me netdata picks them up after a minute or two.

**Comment by vlvkobal** [comment]
`cgroups.plugin` checks for new containers every 10 seconds by default. In `netdata.conf` you can find the option `check for new cgroups every = 10` in `[plugin:cgroups]` section and change the interval. You still have to refresh the page in your browser after netdata has started collecting data for a new container.

**Comment by cmuzyunda** [comment]
I have  " check for new cgroups every = 10" configured correctly , in fact it is the default  value, but yet it does not appear to run every 10 seconds . 
Right now i have a container which has no "disk" and net eth0" showing on nodeA, yet on nodeB this is shown but only because i did a full restart on this node.

**Comment by Thatdarkone** [comment]
I have " check for new cgroups every = 10" configured correctly , in fact it is the default value, but yet it does not appear to run every 10 seconds .
Right now i have a container which has no "disk" and net eth0" showing on nodeA, yet on nodeB this is shown but only because i did a full restart on this node.

**Comment by vlvkobal** [comment]
Did you try pressing F5 in 20 or more seconds after the container was started?

Do you have any error or info messages for cgroups in your `error.log`?

**Comment by ilyam8** [comment]
i tested it on centos7

```
→ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
```

what i did:
```
test /home/test 
→ for i in $(seq 0 9); do docker run -dp 808$i:80 nginx; done
```

I confirm the bug when netdata shows container ID instead if name, if my test it was 9 containers with names and 1 with ID.

**Comment by ilyam8** [comment]
ok, tested one more time (same `for..`), results:

 - 1 container with ID instead of name, and it has only `cpu` and `mem` charts.
 - 8 containers with name and `cpu`, `mem` and `net eth0` charts
 - 1 container with name and `cpu`, `mem`, `net eth0` and `disk` charts

**Comment by Thatdarkone** [comment]
Thanks @ilyam8 ,
I guess this only affects centos 7.6 ,any workaround you can suggest ?

**Comment by ilyam8** [comment]
~switch to debian~, we need to investigate and fix the issue

**Comment by ilyam8** [comment]
> I guess this only affects centos 7.6

i'll do more tests

**Comment by cakrit** [comment]
Compile with debug (`CFLAGS="-O1 -ggdb -DNETDATA_INTERNAL_CHECKS=1" ./netdata-installer.sh`) and set `debug flags = 0x0000000000100000` plz, we should be seeing the first of the following debug statements:

```
    if(simple_pattern_matches(enabled_cgroup_renames, cg->id)) {

        cgroup_get_chart_name(cg);

        debug(D_CGROUP, "cgroup '%s' renamed to '%s' (title: '%s')", cg->id, cg->chart_id, cg->chart_title);
    }
    else
        debug(D_CGROUP, "cgroup '%s' will not be renamed - it matches the list of disabled cgroup renames (will be shown as '%s')", cg->id, cg->chart_id);
```

**Comment by vlvkobal** [comment]
I was able to reproduce the issue (container ID instead of name) on Arch Linux.
```
2019-02-27 16:12:40: cgroup-name.sh: INFO: Running command: docker ps --filter=id="60f815c7dbcb8a67103138c231772a8139f68465c0a6046912d5857f455c126e" --format="{{.Names}}"
2019-02-27 16:12:40: cgroup-name.sh: WARNING: cannot find the name of docker container '60f815c7dbcb8a67103138c231772a8139f68465c0a6046912d5857f455c126e'
2019-02-27 16:12:40: cgroup-name.sh: INFO: cgroup 'docker_60f815c7dbcb8a67103138c231772a8139f68465c0a6046912d5857f455c126e' is called '60f815c7dbcb'
2019-02-27 16:12:40: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : found pid 8697 on file '/sys/fs/cgroup/cpu,cpuacct/docker/60f815c7dbcb8a67103138c231772a8139f68465c0a6046912d5857f455c126e/cgroup.procs'
2019-02-27 16:12:40: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : running: exec /usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/sys/fs/cgroup/cpu,cpuacct/docker/60f815c7dbcb8a67103138c231772a8139f68465c0a6046912d5857f455c126e'
2019-02-27 16:12:40: cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/sys/fs/cgroup/cpu,cpuacct/docker/60f815c7dbcb8a67103138c231772a8139f68465c0a6046912d5857f455c126e'
2019-02-27 16:12:40: netdata INFO  : PLUGIN[cgroups] : CGROUP: cgroup '/docker/60f815c7dbcb8a67103138c231772a8139f68465c0a6046912d5857f455c126e' has network interface 'vethff41cd3' as 'eth0'
2019-02-27 16:12:40: netdata INFO  : PLUGIN[cgroups] : CGROUP: registered network interface rename for 'vethff41cd3' as 'eth0' under '60f815c7dbcb'
```

**Comment by cakrit** [comment]
Any idea why `docker ps` didn't work? If you run it by hand does it return the name properly? I can only think of a timing issue, but I couldn't find anyone complaining about `docker ps` being slow in showing running containers.

**Comment by ilyam8** [comment]
> I can only think of a timing issue

^^

**Comment by cakrit** [comment]
How about storing the fact that we didn't get the container name so we can retry at the next interval? We need to collect data for about 10s before showing the charts anyway, so we can afford a few more queries for the name. It's probably that cgroups get that container id before the entire startup process is completed.

**Comment by ilyam8** [comment]
We have problem with network interfaces too, @vlvkobal 	didn't mention it
