### ISSUE TITLE
Netdata runs python plugin with random code version

### ISSUE THREAD

**Issue by alteringres** [netdata/netdata#5513]
##### Bug report summary
Hello, i have an issue  with a python plugin named "merge_charts"
The first error was legit, there was a variable I did not defined
The second error was also legit, there was a file write attempt with no permissions (i commented the code)

So, in this point, i have  a valid code which can run on local machine (i imported netdata python libs to run)with no errors.

I imported the plugin in netdata python.d plugins with two jobs to run (from merge_charts.conf).
All errors were reported by netdata, after each fix I restarted netdata agent.

The issue is that netdata seams to execute two jobs with the same module "merge_charts" but the code version is random, does not execute always the last version of the code!

##### OS / Environment
Linux 18.0
##### Component Name
internal plugin written in python
##### Steps To Reproduce
1. create a python plugin wich contains three error by intention: one with I/O without permissions, one with variable not defined
2. run plugin with netdata
3. correct first error
4. run again
5. correct last error
6 run again

Result: something it will fails as code version is from step 2, sometimes it works, sometimes will fails as the code version is from step 4

##### Expected behavior
Netdata should  execute the last code version

I put special log in _get_data method, contains different message each time i fixed the code
With last code version, i see in logs:
[Netdata-Maste]  (_get_data) =>  calling...
[uiokjhhkjh890ujkh]  (_get_data) =>  calling...
[uiokjhhkjh890ujkh]  (_get_data) =>  calling...ROXANA E CEA MAI TARE!!!!!!!!!!!!
[Netdata-Maste]  (_get_data) =>  calling...ROXANA E CEA MAI TARE!!!!!!!!!!!!
[Netdata-Maste]  (_get_data) =>  calling...ROXANA E CEA MAI TARE!!!!!!!!!!!!
[uiokjhhkjh890ujkh]  (_get_data) =>  calling...ROXANA E CEA MAI TARE!!!!!!!!!!!!
[uiokjhhkjh890ujkh]  (_get_data) =>  calling...
[Netdata-Maste]  (_get_data) =>  calling...
[uiokjhhkjh890ujkh]  (_get_data) =>  calling...ROXANA E CEA MAI TARE!!!!!!!!!!!!

ROXANA E CEA MAI TARE!!!!!!!!!!!!-> this message is from last code version, all things are ok when this message appears
calling... -> this message is from old version but it still appears 

Please forgive me if i can not explain better

**Comment by alteringres** [comment]
Netdata version is netdata v1.12.1-20-g81bf7a7

**Comment by ilyam8** [comment]
yo @alteringres 

> The issue is that netdata seams to execute two jobs with the same module "merge_charts" but the code version is random, does not execute always the last version of the code!

python.d.plugin loads `merge_charts.chart.py` on every restart, so, it is last version always.

**Comment by alteringres** [comment]
Hey @ilyam8 , thank you for your time, since you say that netdata will always load the last version of code the only valid theory is that i have  a problem with docker containers (i run into this issue in a docker container)

Can close this
