### ISSUE TITLE
RPM build to install to alternate directory

### ISSUE THREAD

**Issue by chipshadd** [netdata/netdata#5515]
##### Question summary
I would like to build netdata into an RPM that installs to an alternate installation directory.  In the spec file, I have tried adding the following parameters to configure:
```
%configure \
        --prefix="/opt/netdata/usr" \
        --sysconfdir="/opt/netdata/etc" \
        --localstatedir="/opt/netdata/var" \
        --with-zlib \
        --with-math \
        %{?with_nfacct:--enable-plugin-nfacct} \
        %{?with_freeipmi:--enable-plugin-freeipmi} \
        --with-user=netdata
```

But when I go to build it, I receive the following error:
(...)
```
 /bin/mkdir -p '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/usr/sbin'
  /bin/install -c netdata '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/usr/sbin'
 /bin/mkdir -p '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/opt/netdata/var/cache/netdata'
 /bin/install -c -m 644 packaging/installer/.keep '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/opt/netdata/var/cache/netdata'
 /bin/mkdir -p '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/opt/netdata/var/log/netdata'
 /bin/install -c -m 644 packaging/installer/.keep '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/opt/netdata/var/log/netdata'
 /bin/mkdir -p '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/opt/netdata/var/lib/netdata/registry'
 /bin/install -c -m 644 packaging/installer/.keep '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/opt/netdata/var/lib/netdata/registry'
 /bin/mkdir -p '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/opt/netdata/var/lib/netdata'
 /bin/install -c -m 644 packaging/installer/.keep '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/opt/netdata/var/lib/netdata'
 /bin/mkdir -p '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/usr/libexec/netdata/plugins.d'
  /bin/install -c apps.plugin cgroup-network '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/usr/libexec/netdata/plugins.d'
make[2]: Leaving directory `/root/rpmbuild/BUILD/netdata-v1.12.1-20-g81bf7a7'
make[1]: Leaving directory `/root/rpmbuild/BUILD/netdata-v1.12.1-20-g81bf7a7'
+ find /root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64 -name .keep -delete
+ install -m 644 -p system/netdata.conf /root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/etc/netdata
install: cannot create regular file '/root/rpmbuild/BUILDROOT/netdata-1.12.0-1.el7.x86_64/etc/netdata': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.3pkAH2 (%install)
```
##### OS / Environment
Centos 7.4 (3.10.0-957.1.3.el7.x86_64)
##### Component Name
RPM
##### Expected results
I'm probably doing something wrong, but I would like to have the RPM build successfully, and upon installing the RPM, having all the related files/folders located in a specified directory exactly how it is done when running the installation script with the --install /PATH/TO/INSTALL parameter.

**Comment by svacko** [comment]
Have you tried to use `netdata-installer.sh` with `--install /opt` as mentioned in the [doc](https://github.com/netdata/netdata/tree/master/packaging/installer#install-netdata) instead of `configure`? This has always worked for me.

**Comment by chipshadd** [comment]
`netdata-installer.sh --install /opt` works flawlessly for me but due to policy constraints, I am trying/need to replicate the same installation results from the install script via an RPM. I got the idea of adding those parameters to configure from looking in the `netdata-installer.sh` script but it seems like I am missing something, or it is not as trivial as I thought it would be.

**Comment by paulkatsoulakis** [comment]
Hi @chipshadd, 
  Thanks for reporting this. We are in the process of officially supporting packaging for our software, so i had to take some time to finish up some preparatory steps in order to get back on this with feedback. 
  First of all, regarding the way packaging works for RPM the installation path is meant to be the one that is defined by default by the system. If you *really* need to alter the installation path for the software, you will have to rebuild the RPM on a properly setup environment with the following command:

```
rpmbuild -v --define '_prefix /tmp/netdata' -ba netdata.spec
```
Note: Keep in mind that this does *not* change the following paths. If you wish to modify those paths, you will have to further modify localstatedir and sharedstatedir definitions

```/etc/netdata
/var/log/netdata
/var/cache/netdata
/var/lib/netdata
```

If you need any further information around the topic, do not hesitate to reopen the issue.
Cheers!
