### ISSUE TITLE
Per User statistics from apps.plugin disappear / stopped working

### ISSUE THREAD

**Issue by mind-code** [netdata/netdata#5517]
[#####] Bug report summary
The entire Users category does not appear anymore. I had to restart netdata, and these charts just disappeared. 

##### OS / Environment / netdata version
Debian 9
Installed via extracted tar
it worked with netdata v.1.10 until it didnt and now Ive tested v1.12.1 and the problem persists. It could be resource related, since I rebooted one of these machines yesterday and on that machine the charts are present again, but even on the machines that havnt rebooted, there is more than enough ram available.

These machines have 128cores 512-1024GB RAM

##### Component Name
apps.plugin User charts 

I found this in the error.log

```
2019-02-27 10:03:36: charts.d: INFO: cpu_apps: is disabled. Add a line with cpu_apps=force in '/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2019-02-27 10:03:36: charts.d: INFO: mem_apps: is disabled. Add a line with mem_apps=force in '/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
```

But if I do that I get a new problem:

```
2019-02-27 10:09:03: charts.d: ERROR: cpu_apps: manual configuration required: please set cpu_apps_apps='command1 command2 ...' in /cpu_apps_apps.conf
2019-02-27 10:09:03: charts.d: ERROR: cpu_apps: module's 'cpu_apps' check() function reports failure.
2019-02-27 10:09:03: charts.d: ERROR: mem_apps: manual configuration required: please set mem_apps_apps='command1 command2 ...' in /mem_apps_apps.conf
2019-02-27 10:09:03: charts.d: ERROR: mem_apps: module's 'mem_apps' check() function reports failure.
```

Maybe this is the wrong track entirely, because information regardring these functions suggest they are deprecated versions anyway.

Any help would be appreciated, since I use the users_cpu and mem chart for a custom dashboard/overview for users.

[error.log](https://github.com/netdata/netdata/files/2909477/error.log)

**Comment by cakrit** [comment]
You're indeed looking at the wrong (deprecated) plugin, the one that is collecting the data is https://docs.netdata.cloud/collectors/apps.plugin/

Run the following to see where the problem is (lots of output): 
`/usr/libexec/netdata/plugins.d/apps.plugin debug`

**Comment by mind-code** [comment]
Sadly this doesnt work:

```
apps.plugin has been compiled without debugging
2019-02-27 10:49:02: apps.plugin ERROR : MAIN : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf' (errno 2, No such file or directory)
2019-02-27 10:49:02: apps.plugin INFO  : MAIN : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
2019-02-27 10:49:02: apps.plugin INFO  : MAIN : Loaded config file '/usr/lib/netdata/conf.d/apps_groups.conf'
2019-02-27 10:49:02: apps.plugin INFO  : MAIN : started on pid 103728
```

**Comment by cakrit** [comment]
Ok, let's at least see the output without the debug. You should see a lot of `BEGIN users.` parts. If it doesn't help us understand what's happening, we may ask you to compile with the debug flags.

**Comment by mind-code** [comment]
That was the entire output. Ill gladly help and recompile. I used the netdata-installer.sh file to install. How to I recompile/install with debug?

**Comment by cakrit** [comment]
See https://docs.netdata.cloud/daemon/#compiling-netdata-with-debugging
The collector is definitely not collecting.

**Comment by mind-code** [comment]
Ok i recompiled and ran the test .. unfortunatly I dont think I can post the complete output. There's user, file and process information in there which I cannot make public. I looked over the log and tried to shorten it in a way that keeps all relevent information intact.

[apps-debug.txt](https://github.com/netdata/netdata/files/2910118/apps-debug.txt)

It just stops at the end. Could it be some sort of system imposed limit? It looks like it stops around the 75000 PID mark. These are large systems with many users that run stuff. The rebooted server with the same problem which worked after reboot was up a long time before as well. This particular Server currently has PID's running over 120000 and the apps.user and mem graphs were stuck on an earlier date. That why I restarted netdata and now the charts are gone alltogether.

Maybe its not even a netdata problem, but a systemd imposed limit?

**Comment by cakrit** [comment]
Trying to figure out what's wrong. What do you get from this?
`sudo cat /proc/sys/kernel/pid_max`

**Comment by cakrit** [comment]
Never mind, you'd be getting in `error.log` "Invalid pid %d read (expected %d to %d). Ignoring process."

**Comment by cakrit** [comment]
A shot in the dark right now, but can you try the following to see if it helps at all?
in `netdata.conf`:
```
[plugin:apps]
     update every = 5
```

**Comment by mind-code** [comment]
Unfortunatly still missing

**Comment by cakrit** [comment]
Let's try something, based on [this](https://stackoverflow.com/questions/23033547/maximum-number-of-files-directories-handled-by-dirent-struct).

In `collectors/apps.plugin/apps_plugin.c` add the following : 
 - At L1960 : `debug_log("read_pid_file_descriptors readdir errno: %s",errno);`
 - At L2438 : `debug_log("collect_data_for_all_processes readdir errno: %s",errno);`

In both cases, the debugs should be right before the call to `closedir`. 

Run it again in debug mode and let's see if we see something interesting (i.e. a non-zero errno indicating out of memory).

**Comment by cakrit** [comment]
By the way, @vlkobal we should be able to reproduce this. Just create a directory with  500k sub-directories with a similar structure as the one in proc. If it is readdir(), we should be able to see it choking the same way.

**Comment by ktsaou** [comment]
I did a simple test:

I run: `sysctl -w kernel.pid_max=1000000` and I restart netdata.

I compiled this tiny C program:

```c
#include <stdio.h>
#include <sys/types.h>
#include <unistd.h>

int main(int argc, char **argv) {

	int i;
	for(i = 0; i < 500000 ;i++) {
		int pid = fork();
		if(pid == 0) {
			// the child
			sleep(1200);
		}
	}
	sleep(1200);
}
```

The compiled binary was saved as `/tmp/test` (you may change the path if your `/tmp` does not allow executing programs - but change the service too below).

Then, I used this systemd service:

```sh
# cat /etc/systemd/system/test.service 
[Unit]
Description=Test 500000 processes

[Service]
WorkingDirectory=/tmp
User=root
Group=root
LimitAS=infinity
LimitRSS=infinity
LimitCORE=infinity
LimitNOFILE=1000000
ExecStart=/tmp/test
Restart=no
SyslogIdentifier=test
TasksMax=1000000

[Install]
```

Then run `systemctl daemon-reload`
and `systemctl start test`.

It took a lot of RAM (I wonder why):

![image](https://user-images.githubusercontent.com/2662304/53661170-675e2800-3c68-11e9-86b4-3da6a24275b1.png)

and swap:

![image](https://user-images.githubusercontent.com/2662304/53661195-78a73480-3c68-11e9-801c-5e28bc6d2232.png)

systemctl reports 217153 processes (I wonder it couldn't more):

```
● test.service - Test 500000 processes
   Loaded: loaded (/etc/systemd/system/test.service; static; vendor preset: disabled)
   Active: active (running) since Fri 2019-03-01 21:14:23 EET; 11min ago
 Main PID: 929993 (test)
    Tasks: 217153 (limit: 1000000)
   Memory: 18.4G
   CGroup: /system.slice/test.service
```

apps.plugin was working (although it needed 7 seconds to process the whole process tree):

![image](https://user-images.githubusercontent.com/2662304/53661341-ca4fbf00-3c68-11e9-9d46-a1407eeece37.png)

apps.plugin reported users too:

![image](https://user-images.githubusercontent.com/2662304/53661396-e2bfd980-3c68-11e9-82b6-02606c5e69b6.png)

and groups too:

![image](https://user-images.githubusercontent.com/2662304/53661434-f4a17c80-3c68-11e9-9f60-e99415b0335d.png)

But apps.plugin did not crash.
I think something else is the problem. It is not the number of processes.

If apps.plugin exits, then it has crashed. We need to find that crash report.

**Comment by vlvkobal** [comment]
@mind-code could you run `apps.plugin` with valgrind or gdb and provide a backtrace on exit? To run it with valgrind first copy `apps.plugin` to your home directory.

**Comment by cakrit** [comment]
We were unable to reproduce this. If anyone else has additional insights on this, please let us know. We will need a backtrace to be able to progress on this.
