### ISSUE TITLE
minimal first setup

### ISSUE THREAD

**Issue by marcelmfs** [netdata/netdata#5520]
##### Question summary
I have some servers in different geographies behind a bandwidth-limiting proxy, and the standard set of metrics collected that are being sent to the central node is hitting some limits from the network policies (not under my control). 

So I need to be able to have a minimal setup to collect only a handful of metrics. I was looking into the proc plugin, but even then, I don't need all metrics. I'd rather have aggregated information than individual drilled down metrics for now, to later increase granularity to assess the limits of the egress proxy.

##### OS / Environment
CentOS 7

##### Component Name
Stream

##### Expected results
Being able to start with just a few collectors.

**Comment by marcelmfs** [comment]
The network limitation causes gaps (streaming)

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/5718899/53491607-1d721800-3a97-11e9-9a85-2440ce85913a.png">

**Comment by Ferroin** [comment]
Check the [documentation for the proc plugin](https://docs.netdata.cloud/collectors/proc.plugin/) for info on how to do disable individual collectors in the proc plugin.

**Comment by marcelmfs** [comment]
Sorry but the link for the documentation is not enough. I'm looking for a sample configuration that only has basic metrics for the proc plugin. On the link you've sent there's only one full section of the proc plugin for diskstat.

**Comment by marcelmfs** [comment]
Ah, sorry, I manage to generate one default configuration file by removing netdata.conf and restarting again the daemon, and curl http://localhost:19999/netdata.conf. I think I've everything I need now.

**Comment by marcelmfs** [comment]
OK, I'll reopen this issue because I think the need for a minimal setup is a nice to have. 

In order for me to get to a minimal set of collected metrics and graphs, I had to first generate the auto discovered netdata.conf file and edit it by adding `enabled = no` in too many section entries in the configuration file (unless there was some other way of doing this and I totally miss the point).

Take a look at how my config (redacted for privacy), looks like after selecting what to chart:

https://gist.github.com/marcelmfs/30d9a32d276055a54d60940c3e3b2e60
