### ISSUE TITLE
Can I disable web interface ?

### ISSUE THREAD

**Issue by petarkozic** [netdata/netdata#5521]
Hi, one question ?

Becuase I use netdata as exporter for prometheus, with api

http://example.com:19999/api/v1/allmetrics

can I disable web interface somehow ?

**Comment by ilyam8** [comment]
Hi @petarkozic 	

https://docs.netdata.cloud/streaming/#configuration

> [web].mode = none disables the API (netdata will not listen to any ports).

```
[web]
    mode = none | static-threaded 
```

**Comment by petarkozic** [comment]
Damn !

I need API.

In anyway, @ilyam8 thank you on answer !
