### ISSUE TITLE
Reducing Overhead Caused by Netdata

### ISSUE THREAD

**Issue by sf720d** [netdata/netdata#5523]
#### Summary
Hello,
 
I’m trying to reduce the overhead caused by netdata, by disabling the more expensive metrics that we aren’t using.
 
I’m running into some questions (things I’m not sure about from the config and the results I’m seeing), and some things I don’t see how to disable easily and I’m hoping to get some help and clarification.

I need to disable the following charts in netdata.conf:

- system.intr
- cpu.cpu.*_interrupts
- cpu.cpu.*_softirqs
- cpu.cpu.*_cpuidle

I found the [plugin.proc] documentation but faced some issues while using it.
1. If I add this configuration:
```
[plugin:proc]
    /proc/softirqs = no
```
It will disable both `system.softirqs` and `cpu.cpu.*_softirqs`.
I don't want system.softirqs chart to be disabled. Is there a way to target only `cpu.cpu.*_softirqs` charts? We have different number of cores for each netdata host and using 
```
[cpu.cpu0_softirqs]
        enabled = no
```
for each core on each netdata host is not very feasible.

2. If I add this configuration:
```
[plugin:proc]
  /proc/interrupts = no
```
It will only disable `cpu.cpu.*_interrupts`. We need to disable both `system.intr` and `cpu.cpu.*_interrupts` charts.

3. If I add this configuration:
```
[plugin:proc:/proc/stat]
  cpu interrupts = no
```
It won’t do anything. All the interrupt charts still exist.

4. BUT if I use both 2 and 3, It will remove both `system.intr` and `cpu.cpu.*_interrupts` charts. I’m not sure how this is getting rid of `system.intr`. Can you clarify this please?

5. Is there a plugin I can use to disable `cpu.cpu.*_cpuidle` charts? 

Thank you for your help in advance.

**Comment by vlvkobal** [comment]
1. `/proc/softirqs = no` disables the whole module which provides `system.softirqs` and `cpu.cpu.*_softirqs` charts. To disable  only `cpu.cpu.*_softirqs` charts you can use this parameter:
```
[plugin:proc:/proc/softirqs]
	interrupts per core = no
```

2. `/proc/interrupts = no` disables `cpu.cpu.*_interrupts` and `system.interrupts`, not `system.intr`

3. `cpu interrupts = no` disables `system.intr`

4. Look at 2 and 3.

5. 
```
[plugin:proc:/proc/stat]
	cpu idle states = no
```

**Comment by sf720d** [comment]
Thanks for the response.
I just tried the parameters you suggested and the following questions came up:
1. Using this parameter:
`[plugin:proc:/proc/softirqs]
	interrupts per core = no`
it will disable not only `cpu.cpu.*_softirqs` but:
under System Overview:
- disk
- ram
- network
- softirqs
- softnet
- ipc_semaphores
and under CPUs:
- softirqs
- softnet

2. 
`[plugin:proc:/proc/stat]
	cpu idle states = no`
does exactly what number 1 does. and `cpu.cpu.*_cpuidle` charts still exist.


Am I doing something wrong? I'm changing /opt/netdata/netdata-configs/netdata.conf file and run
`systemctl restart netdata` after changing the configurations.

**Comment by vlvkobal** [comment]
1. `interrupts per core = no` can't disable anything except `cpu.cpu.*_softirqs`.
2. `cpu idle states = no` should disable `cpu.cpu.*_cpuidle` charts.

You can check the effective configuration at http://localhost:19999/netdata.conf. The configuration file placement depends on the package you use. As far as I know, Debian package is using `netdata-configs` directory for configuration files. You can also try `/opt/netdata/etc/netdata/netdata.conf`.

Anyway, it is very strange you get such messy behaviour. Are you sure it is repeatable and not random? Did you try **hard reloading** the page in your browser after restarting netdata?

Perhaps, your `netdata.conf` is corrupted. Please move the configuration file to a safe place, restart netdata, and download the default configuration using `curl http://localhost:19999/netdata.conf > netdata.conf`.

**Comment by sf720d** [comment]
So  I used `interrupts per core = no` in /opt/netdata/etc/netdata/netdata.conf and it worked perfectly.
But `cpu idle states = no` still doesn't do anything.  I checked http://<ip address>:19990/netdata.conf
and there is no "cpu idle states" under "plugin:proc:/proc/stat". And I can't find anything for cpu idle.
These are the configs under `plugin:proc:/proc/stat`:
```
[plugin:proc:/proc/stat]
	# cpu utilization = yes
	# per cpu core utilization = yes
	# cpu interrupts = yes
	# context switches = yes
	# processes started = yes
	# processes running = yes
	# keep per core files open = yes
	# core_throttle_count = auto
	# package_throttle_count = no
	# cpu frequency = yes
	# core_throttle_count filename to monitor = /sys/devices/system/cpu/%s/thermal_throttle/core_throttle_count
	# package_throttle_count filename to monitor = /sys/devices/system/cpu/%s/thermal_throttle/package_throttle_count
	# scaling_cur_freq filename to monitor = /sys/devices/system/cpu/%s/cpufreq/scaling_cur_freq
	# time_in_state filename to monitor = /sys/devices/system/cpu/%s/cpufreq/stats/time_in_state
	# filename to monitor = /proc/stat
```

any thoughts on cpuidle?

**Comment by vlvkobal** [comment]
Please run `netdata -V`. What is the version of your netdata?

**Comment by sf720d** [comment]
my netdata version is `netdata 1.11.1_rolling`

**Comment by vlvkobal** [comment]
Please update your netdata to the latest version. Cpuidle charts were introduced in the version 1.12.0.rc0 .

**Comment by vlvkobal** [comment]
I mean cpuidle charts written in C.

**Comment by vlvkobal** [comment]
To disable the cpuidle python module in the old netdata set `cpuidle: no` in `/opt/netdata/etc/netdata/python.d/python.d.conf`.

**Comment by sf720d** [comment]
Thank you for your help. We'll upgrade our instances to 1.12.x and use the plugins.
