### ISSUE TITLE
Ubuntu: Disable netdata service on startup

### ISSUE THREAD

**Issue by Abhinickz** [netdata/netdata#5524]
##### Question summary
I have tried to disable netdata multiple times using this below command:

```
[12:04:47 abhinickz@abhinickz -> ~$ sudo systemctl disable netdata
Removed /etc/systemd/system/multi-user.target.wants/netdata.service.
``` 
But after booting system is again showing that netdata is running.

Checking ```service --status-all``` does not show the netdata service name.

How can I disable netdata service startup on boot? 

##### OS / Environment
```
 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```
##### Component Name
Netdata Service
##### Expected results
Should stop netdata from starting up on boot.

Let me know more information is needed.

**Comment by cakrit** [comment]
You probably have `netdata-updater` in your `/etc/cron.daily`. The updater calls the installer, which enables the service again.

**Comment by paulfantom** [comment]
Also you can use `mask` to prevent any service from being enabled.

`systemctl mask netdata`

**Comment by Abhinickz** [comment]
This ```systemctl mask netdata``` worked.

```
[01:25:30 abhinickz@abhinickz -> ~$ sudo service netdata status
[sudo] password for abhinickz: 
● netdata.service
   Loaded: masked (Reason: Unit netdata.service is masked.)
   Active: inactive (dead)
```
