### ISSUE TITLE
Monitor ufw status

### ISSUE THREAD

**Issue by binaryplease** [netdata/netdata#5532]
##### Question summary

Hello, I can't figure out how to do this:
How can I monitor the status of the ufw firewall?

I can run `sudo ufw status` on the terminal and it will report `Status: active` (+open ports) or `Status: incactive`. 

I would like to:
1. See that status in the Netdata GUI 
2. send an alert if ufw changes to `disabled`

How can I do that?

##### OS / Environment
I'm running unbuntu-server and started Netdata inside a docker container.

**Comment by vlvkobal** [comment]
You can write a simple module in [Bash](https://docs.netdata.cloud/collectors/charts.d.plugin/), [Python](https://docs.netdata.cloud/collectors/python.d.plugin/), [Go](https://docs.netdata.cloud/collectors/go.d.plugin/) or [JavaScript](https://docs.netdata.cloud/collectors/node.d.plugin/) which will query the status and put 0 or 1 into a chart. Then you need to configure an [alarm](https://docs.netdata.cloud/health/) on this chart.

If you still want to run netdata inside a container, you should figure out how to get the status information from the inside of the container.
