### ISSUE TITLE
How to remove stuck Alarm?

### ISSUE THREAD

**Issue by csadam** [netdata/netdata#5533]
I'm using two headless collectors (with static install) streaming to a central netdata instance (automatic install).
One of the headless servers had a disk Alarm, and then the disk was unmounted before the netdata alarm disappeared.
The result is that I have a stuck Alarm to a disk that does not exists.

Is it possible to manually force-clean this Alarm somehow?

**Comment by cakrit** [comment]
Only thing I can think of is to stop netdata, edit `/var/lib/netdata/health/health-log.db` and remove the relevant line. It's a plain text file. 
I just tried (after keeping a backup of course) and it cleaned some older netdev alarms I had. Pretty cool actually...

**Comment by csadam** [comment]
OK, it worked, thank you.
The only difference was that my file is
`/var/lib/netdata/{uuid_of_the_slave}/health/health-log.db`
