### ISSUE TITLE
NS_ERROR_FILE_CORRUPTED: 

### ISSUE THREAD

**Issue by eXcalibre** [netdata/netdata#5535]
##### Bug report summary
I am having issues on one server only, i have netdata installed on several and can normally switch to other servers in my group under the menu to the right of the netdata logo.
NS_ERROR_FILE_CORRUPTED:  (expanding this i see
    	handleSignInMessage http://MYHOSTNAME:MYPORT/main.js?v=4:4803 
    	handleMessage http://MYHOSTNAME:MYPORT/main.js?v=4:4790 

##### OS / Environment
Ubuntu VERSION="18.04.2 LTS (Bionic Beaver)" kernel version 4.15.0-45-generic
 
My querying eenvironment
Mac OSX 10.14.3 Mojave Firefox,Safari (safari hangs on Loading please wait after the git login)

##### Output of `netdata -V`)
fresh install netdata v1.12.2-4-nightly

##### Component Name
Registery login

##### Steps To Reproduce
open web gui, select hastname menu to the right of the netdata logo.
select sign in to netdata.cloud
log in via github login (window closes and reselects the netdata tab)
no difference on the netdata menu, still states sign in.
if i use the console output in my browser i see the errors
NS_ERROR_FILE_CORRUPTED:  (expanding this i see
    	handleSignInMessage http://MYHOSTNAME:MYPORT/main.js?v=4:4803 
    	handleMessage http://MYHOSTNAME:MYPORT/main.js?v=4:4790 

##### Expected behavior
drop down list of all my servers in the registry with this new server added to the list.

**Comment by gmosx** [comment]
As a quick solution, please try the following:

1. Sign Out
2. Clear the localStorage: open the developer console (f12) write `localStorage.clear()` and press enter.
3. Sign In again

Optionally (I think it will not be needed) click the 'Synchronize with netdata.cloud' item in the menu.

**Comment by gmosx** [comment]
This seems a problem with your Firefox installation:

<https://confluence.atlassian.com/jirakb/exception-ns_error_file_corrupted-779158960.html>

**Comment by eXcalibre** [comment]
@gmosx you were spot on with the firefox issue.
removed the sqlite file and it logged in imediately after logging in to git.

Thanks very much.
