### ISSUE TITLE
Sign-in to netdata.cloud fails with "file does not exist"

### ISSUE THREAD

**Issue by dwreski** [netdata/netdata#5542]
##### Bug report summary
I have downloaded and installed the latest as of a few days ago, and after installing and running, clicking the "please sign-in to netdata.cloud to view your nodes" results in the following:
File does not exist, or is not accessible: /usr/share/netdata/web/undefined/account/sign-in-agent
##### OS / Environment
Fedora28
##### Netdata version (ouput of `netdata -V`)
netdata v1.12.2-2-nightly

##### Steps To Reproduce
- Go to http://host:19999/
- Click hostname pull-down in upper-left
- Click "please sign-in"
##### Expected behavior
How do I login?

**Comment by gmosx** [comment]
Hi, any change you added a custom `base cloud url` parameter in netdata.conf?

```
[cloud]
  cloud base url = ???
```

Can you open the dev console in the browser (press F12) and execute the following code?

```

**Comment by dwreski** [comment]
It says it's undefined. I don't currently have a [cloud] section in my netdata.conf.

My apologies if I missed how to configure that in the documentation.

**Comment by cakrit** [comment]
This is strange, what does the following return?
http://localhost:19999/api/v1/registry?action=hello

**Comment by cakrit** [comment]
Also, please show us the result of http://localhost:19999/netdata.conf under the section `[cloud]`.
It should say: 
```
[cloud]
	# cloud base url = https://netdata.cloud
```

**Comment by dwreski** [comment]
First, there was no cloud section in my /etc/netdata/netdata.conf file. If I add it and restart netdata, as you've described, a little pop-up appears with the following:

ERROR 405: Cannot download charts index from server: http://bwimail01.guardiandigital.com:19999/api/v1/charts

If I then attempt to go to the URL you've provided (substituting my hostname instead of localhost, as it's running on a remote server), it fails with This site can’t be reached

**Comment by cakrit** [comment]
> First, there was no cloud section in my /etc/netdata/netdata.conf file.

There doesn't need to be one. I didn't request that you add it, but that you look at the configuration netdata uses. That's what you get, when you request netdata to give you `netdata.conf`. Everything has a default, indicated by the `#` in front of the setting.

> If I add it and restart netdata, as you've described, a little pop-up appears with the following:
ERROR 405: Cannot download charts index from server: 

- The cloud section is completely unrelated to this error
- Adding a commented line has no effect
- You didn't need to change the configuration, netdata has the proper setting for cloud by default.

> If I then attempt to go to the URL you've provided (substituting my hostname instead of localhost, as it's running on a remote server), it fails with "This site can’t be reached" (ERR_CONNECTION_REFUSED)

You'll need to modify the "netdata.conf allow from" setting, so you can let your IP retrieve the configuration, or just do a curl/wget from the host's command line. Both the urls I asked that you hit return text (one JSON, the other a config file).

Please don't forget the `/api/v1/registry?action=hello` call to get that JSON

**Comment by gmosx** [comment]
> You'll need to modify the "netdata.conf allow from" setting,

The `allow from` setting in `/etc/netdata/netdata.conf`:

```
[registry]
    allow from = ...
```

**Comment by dwreski** [comment]
I don't know how I missed that in the documentation. Even searching for netdata "allow from" doesn't directly result in a link to documentation. Shouldn't this be included in the "Getting Started" guide or Installation section?

**Comment by cakrit** [comment]
> I don't know how I missed that in the documentation. Even searching for netdata "allow from" doesn't directly result in a link to documentation. Shouldn't this be included in the "Getting Started" guide or Installation section?

The default settings allow you to view the netdata dashboard and use the global registry without any configuration. See https://docs.netdata.cloud/web/server/#access-lists. The registry settings apply only when you configure netdata to use your own registry, in which case it's expected that one reads https://docs.netdata.cloud/registry/#run-your-own-registry

Even then, the default `allow from` is *, so the default settings were definitely not being used in your case. The only way we know that this can happen is if someone has modified the configuration, which is why I asked to see your `http://host:port/netdata.conf`.
