### ISSUE TITLE
Alert if process isn't alive

### ISSUE THREAD

**Issue by EnzoAkira** [netdata/netdata#5547]
##### Bug report summary
I'm setting up alerts for important processes that I need to know if they're alive, I've added them to the apps_groups.conf file like this:
```
Go.Main:                     *nsMain.js*
Go.Voice:                    *nsVoice.js*
Go.Chat:                     *nsChat.js*
Go.TicketsExternalService:   *nsTicketsExternalService.js*
Go.TicketsMailService:       *nsTicketsMailService.js*
Go.TicketsPostgresListen:    *nsTicketsPostgresListen.js*
Go.TicketsSockService:       *nsTicketsSockService.js*
....
```
I made my alerts based on apache example in your docs ([apache_last_collected_secs](https://docs.netdata.cloud/health/#example-1)), like:
```
# ****** Go.Main ******
template: nsMain_last_collected_secs
      on: apps.cpu
  family: cpu
    calc: $now - $apps.cpu.Go.Main_last_collected_t
   every: 5s
   units: seconds ago
    warn: $this > (($status >= $WARNING)  ? ($update_every) : ( 5 * $update_every))
    crit: $this > (($status == $CRITICAL) ? ($update_every) : (60 * $update_every))
   delay: down 10m multiplier 1.2 max 1h
    info: number of seconds since the last successful data collection
      to: sysadmin
```
I can see all the variables in the API (using Postman) and view the variable apps.cpu.Go.Main_last_collected_t, but when I stop the respective process, the variable continues with the same value (in seconds), even if I refresh many times, these variables do not change.

Is it possible that _apps.plugin_ doens't refresh all processes at same time? Or my config isn's right?
I have tried with more common process (like httpd and Postgres) and this worked as expected.

##### OS / Environment
`Centos 7 x64`
##### Netdata version (ouput of `netdata -V`)
`netdata v1.12.2-4-nightly`

**Comment by ilyam8** [comment]
@EnzoAkira 	

should be fixed after #5540 is merged
