### ISSUE TITLE
"Cannot install netdata init service" on Raspbian

### ISSUE THREAD

**Issue by shoopdawoop** [netdata/netdata#5550]
I installed netdata on an older Raspbian GNU/Linux 8.0 (jessie); Linux Kernel 3.4.90 armv7l (running on a Bananapi) and it did not recognise the system and hence failed to setup autostart via initd.

Other than that everything seems to have worked fine.

> Your netdata version: 0a2145a

`~/netdata# sudo ./netdata-installer.sh --auto-update --stable-channel`
> [...]
> 
> [/root/netdata]# chmod a+rX /usr/share/netdata
>  OK
> 
>  --- Install netdata at system init ---
> I don't know what init file to install on system 'raspbian-8'. Open a github issue to help us fix it.
>  FAILED  Cannot install netdata init service.
> 
>  --- Start netdata ---
> [/root/netdata]# /usr/sbin/service netdata stop
> netdata: unrecognized service
>  FAILED
> 
> [/root/netdata]# /usr/sbin/service netdata restart
> netdata: unrecognized service
>  FAILED
> 
> [/root/netdata]# /usr/sbin/service netdata start
> netdata: unrecognized service
>  FAILED
> 
> [/root/netdata]# stop_all_netdata
>  OK
> 
> [/root/netdata]# /usr/sbin/netdata
> 2019-03-04 17:58:50: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'START' '-' '-'
>  OK
> 
> OK. NetData Started!
> 
> [...]

**Comment by cakrit** [comment]
The relevant code start at https://github.com/netdata/netdata/blob/master/packaging/installer/functions.sh#L463

Can you do a PR to help us support it?

**Comment by paulkatsoulakis** [comment]
I am not 100% certain, but I found this https://github.com/AndrewFromMelbourne/raspifb16/tree/master/raspinfo#install that i picked up from https://www.raspberrypi.org/forums/viewtopic.php?t=126155 and it confirms systemctl as the way it should work. So we probably need to revise this part:

https://github.com/netdata/netdata/blob/cf7c64b2c37e56057a06e9a7b4a5ec549fd73e3f/packaging/installer/functions.sh#L420

**Comment by shoopdawoop** [comment]
In case this helps, I tried to set it up manually and got this:
```
~# cp /opt/netdata/system/netdata-lsb /etc/init.d/netdata
~# chmod +x /etc/init.d/netdata
~# update-rc.d netdata defaults
```
> insserv: Service named has to be enabled to start service netdata
> insserv: Service httpd has to be enabled to start service netdata
> insserv: Service squid has to be enabled to start service netdata
> insserv: Service mysql has to be enabled to start service netdata
> insserv: Service opensips has to be enabled to start service netdata
> insserv: Service hostapd has to be enabled to start service netdata
> insserv: Service postfix has to be enabled to start service netdata
> insserv: Service lm_sensors has to be enabled to start service netdata
> insserv: exiting now!
> update-rc.d: error: insserv rejected the script header
>

**Comment by paulkatsoulakis** [comment]
Spotted a similar issue #2148 pointing similar error on Debian distro.
Could you check the proposed fix @shoopdawoop just to rule out the possibility of being the same issue?

**Comment by shoopdawoop** [comment]
Sure. So I tried it again (I had already removed netdata completely) and but there is no `/etc/systemd/system/netdata.service`  (nor is there anything in `/lib/systemd/system/`).

There actually is a folder `/etc/systemd/system/` though, but all the services I use have init scripts in
`/etc/init.d/`.

And indeed a
`# service netdata stop`
gives me a `netdata: unrecognized service`.

**Comment by Ferroin** [comment]
@shoopdawoop Can you confirm if this is still an issue for you?

**Comment by prologic** [comment]
@Ferroin Any thoughts on adding Raspbian 8.0 (jessie) to our CI/CD list? Its EOL 30th June 2020 -- We're already supporting Debian 8.0 (jessie) in general anyway so I _think_ we should -- It's just we have to build for the ARMv7 / ARMv8 arch(s) -- Which we're planning to do anyway.

**Comment by Ferroin** [comment]
Raspbian has already moved on and no longer supports 8 AFAIK (as in, package management is kind of broken there at this point), so I see little value to doing CI?CD for Raspbian 8.

**Comment by cosmix** [comment]
Since this has been open for quite a while with no response and Raspbian 8 is EOL soon, I suggest we close this. @shoopdawoop please re-open if needed.
