### ISSUE TITLE
Use IFDEFs for the ipmi monitoring enums

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5556]
##### Feature idea summary
The driver-type enums we use in the freeipmi plugin are not always aligned to what ipmimonitoring itself accepts as options. We should have IFDEFs for those enums, in case they vary based on the OS and the freeipmi version.

##### Expected behavior
Support the driver-type options defined in the freeipmi header file found in the machine netdata runs on.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
