### ISSUE TITLE
Static installer fails on systemd where /lib is read-only

### ISSUE THREAD

**Issue by mildred** [netdata/netdata#5558]
##### Bug report summary

Static package fails to install on CoreOS because /lib is read-only

https://github.com/netdata/netdata/issues/68#issuecomment-469716965

##### OS / Environment

CoreOS

##### Steps To Reproduce

```
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --non-interactive
```

##### Expected behavior

It should install the systemd unit to /etc/systemd/system if it can detect that /lib is read-only, instead it errors out with:

```
 --- Install netdata at system init --- 
Installing systemd service...
[/opt/netdata]# cp system/netdata.service /lib/systemd/system/netdata.service 
cp: cannot create regular file '/lib/systemd/system/netdata.service': Read-only file system
 FAILED   

 FAILED  Cannot install netdata init service. 
```

**Comment by paulfantom** [comment]
Since CoreOS Linux is meant to be used in containerized environments and not to install applications directly onto that system I would advise to use docker container provided by netdata.

**Comment by prologic** [comment]
As much as I agree with @paulfantom I _believe_  we should support installing the NetData agent alongside the CoreOS Host system. I know I would (_but I typically run [RancherOS](https://rancher.com/rancher-os/)_) --  There are [known limitations])https://docs.netdata.cloud/packaging/docker/#limitations-running-netdata-in-docker) to running the NetData agent as a container for full monitoring of the host system.

PR incoming to fix/address this :)
