### ISSUE TITLE
streaming master is incorrectly detected (home icon of streamed hosts)

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#5560]
##### Bug report summary

![image](https://user-images.githubusercontent.com/2662304/53833681-c9cd6600-3f91-11e9-9c27-77a697e8aece.png)

The home icon should be assigned to `octopuscs.my-netdata.io`, not to `arch`.

##### OS / Environment

independent

##### Netdata version (ouput of `netdata -V`)

v1.12.2-14-g3e6a790

**Comment by cakrit** [comment]
Fixed in #5561
