### ISSUE TITLE
Is there an option to enable Web notifications?

### ISSUE THREAD

**Issue by weagertron** [netdata/netdata#5562]
I've been enjoying working with Netdata and continually get impressed with how powerful and flexible it is, you guys have done a fantastic job! However, I have stumbled across one slight issue that has been holding me back slightly...

Is there something I need to enable within the Netdata configuration to allow the HTML notifications on the Netdata dashboard to be displayed? I tried reading documentation on the Web notifications but it seems very brief: https://docs.netdata.cloud/health/notifications/web/ 

I have tried testing the alarms by using:
`/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh test "sysadmin"`
But no notifications are displayed.

I also monitored the Alarms window where I can see alarms for my custom chart being triggered frequently:
![image](https://user-images.githubusercontent.com/33099540/53893976-275fc200-4027-11e9-9d38-e260b2174d04.png)
But still, no notifications are appearing.

I checked in the developer console on my browser too to see if there were any errors being thrown but the console is practically empty with no error messages at all.

My NetData version is as follows:
![image](https://user-images.githubusercontent.com/33099540/53894202-9a693880-4027-11e9-8aee-fc6fe7cc7676.png)
There doesn't seem to be a later version available. In this instance I have installed Netdata using the 64bit static binary.

Any help on this matter will be greatly appreciated.

**Comment by ilyam8** [comment]
![screenshot_20190306_190713](https://user-images.githubusercontent.com/22274335/53895660-8fbc9c80-4043-11e9-87dc-625d3c385374.png)

**Comment by Ferroin** [comment]
Expanding on what @ilyam8 said, for this to work, two things are needed:

* Your web browser must support the Web Notification API.  Most browsers from the past 5 years meet this criteria, with the notable exceptions of Internet Explorer, Safari for iOS, and Opera Mini (more concrete info on support for this can be found at https://caniuse.com/#feat=notifications)
* You have to allow the Netdata dashboard to use the above-mentioned API.  How you do this is, unfortunately, dependent on the web browser you are using.  Most browsers will prompt you about it the first time you navigate to the dashboard, usually with message saying the address wants to use or deliver desktop notifications.  If you didn't say 'allow' or 'yes' to this prompt, then the brwoser won't prompt you again about it, and you will have to find out how to enable them for your browser.  Chrome (and it's various derivatives) use an interface as shown in the screenshot posted by @ilyam8.  I think Firefox and Opera do something similar, but I'm not sure, and I have no idea about anything else.

Also, this is handled entirely independently of the usual notification system, so `alarm-test.sh` won't ever display notifications in your web browser.  The only way to test that it's working is to manually produce conditions on the server that trigger a notification (there should _probably_ be a way to test it from the dashboard, we just don't have it right now).

**Comment by weagertron** [comment]
Thank you for your fast responses @ilyam8 and @Ferroin .

I have now enabled the notifications for my dashboard so it looks like the following:

![image](https://user-images.githubusercontent.com/33099540/53896551-20877e00-402c-11e9-86bd-eb2078db879e.png)

I am using an up to date version of Google Chrome so I believe that should support the Web Notification API. 

However, I am still not seeing any notifications at all on my dashboard. I am still seeing the alarms stacking up but not even a whiff of a notification

![image](https://user-images.githubusercontent.com/33099540/53896731-807e2480-402c-11e9-8b37-0211b32cfd5e.png)

Thank you @Ferroin for clarifying that I wouldn't see notifications on the dashboard from that command. I can turn my attention away from that now.

**Comment by ilyam8** [comment]
- `sudo kill -USR2 $(pidof netdata)`
 - go to netdata dashboard
 - wait

**Comment by weagertron** [comment]
Thanks @ilyam8, I tried what you suggested but no luck unfortunately.

I did make some progress though. My Netdata installation is currently running on a virtual machine on Centos 7 of which I am accessing the dashboard via the host machine (Windows 10). For some reason, the notifications **are** working from within the VM on Firefox, but are not working from the host running Google Chrome.

So from Firefox within the VM it works on localhost but then externally from the VM it does not work on Chrome when accessing the machine via its IP address.

Any idea why this might be the case?

**Comment by ilyam8** [comment]
That is actually pretty interesting, i see no `Notifications` options in the menu if i access dashboard not via localhost.

**Comment by weagertron** [comment]
Where would you normally see the `Notifications` option?

**Comment by ilyam8** [comment]
I meant there is no `Notifications` option in [the browser menu](https://github.com/netdata/netdata/issues/5562#issuecomment-470168831)

**Comment by weagertron** [comment]
Ah, I see what you mean. In order to make that option appear for me I had to go into the Chrome settings and add an exception for notifications to the IP address of my Netdata machine. It doesn't seem to of made a difference though.

**Comment by ilyam8** [comment]
> So from Firefox within the VM it works on localhost but then externally from the VM it does not work on Chrome when accessing the machine via its IP address.

> it does not work on Chrome

anyway @weagertron it works in Firefox

**Comment by Ferroin** [comment]
I'm fairly certain it doesn't matter that it's not going through the loopback interface, as I have exactly zero issues in Chrome seeing notifications from remote systems.

That said, on Windows 10, they show up in the 'action center' like OS-native notifications.  There have been numerous bugs in the past few versions of Windows 10 with notifications (not just Netdata, but _any_ notifications) not properly showing up there, so you may be affected by one of those.  Alternatively, if you're on a new enough version of Windows 10, you may have Focus Assist enabled for some reason, which actively prevents notifications from popping up on-screen (they should still show up in the action center though).

**Comment by Ferroin** [comment]
> I'm fairly certain it doesn't matter that it's not going through the loopback interface, as I have exactly zero issues in Chrome seeing notifications from remote systems.

Actually, scratch that, just checked once more, and it looks like they only work in Chrome if Chrome thinks the connection is 'secure' (that is, the connection is over the system's loopback interface, or uses HTTPS).  Chrome does this with _a lot_ of Web API's, and as far as I know, there's no easy way to whitelist single API's for a single site.

**Comment by ilyam8** [comment]
@weagertron i think @Ferroin is resolved the mystery, i am closing the issue, if something is not clear feel free to ask.

**Comment by sjuxax** [comment]
Just a quick note: In Firefox, notifications over plain HTTP can be allowed by flipping `dom.webnotifications.allowinsecure` to true in `about:config`, at least [for now](https://bugzilla.mozilla.org/show_bug.cgi?id=1587045).

This appears to have changed in early 2019, but it seems it doesn't apply if you access via IP address (e.g. `http://10.x.x.x:19999`). Was wondering why my notifications for my local instance disappeared -- it was because I switched to accessing by the internal hostname instead of direct IP.
