### ISSUE TITLE
FreeNAS cpu.temperature dimension

### ISSUE THREAD

**Issue by Nitro626** [netdata/netdata#5565]
Hi,

I am trying to add a new Cpu temp guage to the System overview in the FreeNAS index.html I added the HTML code to the index file no problem however the guage reported all 4 cores of my cpu's temp added together then I realised i need to add  [CODE]+ ' data-dimensions="cpu3"'[/CODE] to the code however not matter what add, I can not find the correct dimension core_3 cpu.cpu3 cpu3.temp it will not report the core3 of my cpu.

What is the dimensions use under cpu.temperature in FreeNAS?

Regards Nitro,

**Comment by ilyam8** [comment]
Hey @Nitro626 `data-dimensions` works.

chart: `sensors.coretemp_isa_0000_temperature`
dim: `Core 0`

```
        <div data-netdata="sensors.coretemp_isa_0000_temperature"
            data-title="Temperature"
            data-dimensions="Core 0"
            data-chart-library="easypiechart"
            data-dygraph-theme="sparkline"
            data-units="celsius"
            data-width="180px"
            data-height="70px"
            data-after="-3000"
            > </div>

```

**Comment by Nitro626** [comment]
Hi ilyam8,

Thanks for the reply, I've just tried it what you said, still get this sensors.coretemp_isa_0000_temperature: chart not found on url "/api/v1/chart?

Here my added code 

`if(typeof charts['cpu.temperature'] !== 'undefined')
                head += '<div class="netdata-container" style="margin-right: 10px;" data-netdata="sensors.coretemp_isa_0000_temperature"'
		+ ' data-dimensions="Core 0"'
                + ' data-chart-library="gauge"'
                + ' data-title="CPU Temp"'
                + ' data-units="Celsius"'
                + ' data-gauge-max-value="100"'
                + ' data-width="20%"'
                + ' data-after="-' + duration.toString() + '"'
                + ' data-points="' + duration.toString() + '"'
                + ' data-colors="' + NETDATA.colors[12] + '"'
                + ' role="application"></div>';
`
I don't know why its not in the correct format? I also changed the typeof charts to sensors.coretemp_isa_0000_temperature
Thats didn't work either.

This is a service with in freeNAS

Regards Nitro

**Comment by ilyam8** [comment]
ok, what i did:
 - copied [dashboard template from the wiki](https://docs.netdata.cloud/web/gui/custom/#example-empty-dashboard) and created index.html
 - [added dashboard.js](https://docs.netdata.cloud/web/gui/custom/#dashboardjs) to the file
 - got chart id and dimension name from the dashboard

![screenshot_20190307_120100](https://user-images.githubusercontent.com/22274335/53944569-b83ea800-40d0-11e9-8bc1-90a4f013272b.png)

 - added [div block from my prev comment](https://github.com/netdata/netdata/issues/5565#issuecomment-470394590) to the <body>

That is pretty much all i did, it works. Not sure about your code.

**Comment by Nitro626** [comment]
Yup,

Thats what i did first and it does not work under freenas, for some reason...

![nd](https://user-images.githubusercontent.com/48297964/53948789-31eb8b80-40fb-11e9-9842-a146111aeaf1.JPG)

![nd2](https://user-images.githubusercontent.com/48297964/53948801-39129980-40fb-11e9-97f0-cd3e519c3c6f.JPG)

Nitro
