### ISSUE TITLE
swap chart should use stack mode instead of area mode

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#5567]
##### Bug report summary
The system swap chart should use stack mode, not area mode.
The area mode looks very strange.
<img width="1063" alt="2019-03-07 14 02 33" src="https://user-images.githubusercontent.com/8895721/53933469-d82a9780-40e1-11e9-93a4-6d28e54d9357.png">

##### OS / Environment
CentOS 7

##### Netdata version (ouput of `netdata -V`)
1.12.2

##### Component Name
web UI

##### Steps To Reproduce
open web UI and check system swap chart

##### Expected behavior

**Comment by vlvkobal** [comment]
It should be stacked. Did you try reloading (or even hard reloading) the page?

**Comment by Wing924** [comment]
> It should be stacked. Did you try reloading (or even hard reloading) the page?

I confirmed it again. It's not stack but area mode.

**Comment by Wing924** [comment]
This bug will happen when the system start to use swap (added new dim).
This bug won't happen when the system have already use swap (no new dim).

**Comment by ilyam8** [comment]
i've tested it and there is not bug.

> dim was added (system started to use swap) ~ 11:08

![screenshot_20190308_110951](https://user-images.githubusercontent.com/22274335/54016073-d836a000-4192-11e9-8683-a5593bb28793.png)

> chart is stacked

![screenshot_20190308_111010](https://user-images.githubusercontent.com/22274335/54016079-da98fa00-4192-11e9-8e6b-6553bdfb345e.png)

**Comment by Wing924** [comment]
the bug is:
* single dim stack chart should show as stack not as area.

**Comment by vlvkobal** [comment]
I confirm the issue. If a chart was created with one dimension and more dimensions were added later, the chart is not stacked.
![image](https://user-images.githubusercontent.com/22008543/54019130-15029700-4193-11e9-86fa-8a792e54e53f.png)

**Comment by ilyam8** [comment]
please open a new issue or rename this one

**Comment by vlvkobal** [comment]
I'm closing this issue in favour of #5582
