### ISSUE TITLE
allow disk id's in data-netdata attributes

### ISSUE THREAD

**Issue by dscherger** [netdata/netdata#5568]
I have a custom status page for a mirrored zfs pool that has several div's like this 

```
    <div data-title="Samsung_SSD_840_PRO_Series_S1ANNSADB94287R"
         data-host="//haswell:19999"
         data-netdata="disk.sda"
         data-dygraph-valuerange="[null, null]"
         data-width="45%"
         data-height="120px"
         data-before="0"
         data-after="-480">
    </div>
```

This status page displays info for around a dozen disks but the problem I have is that disk device names like sda, sdb, etc. are not stable across reboots, particularly when other usb drives are added or removed. This leads to the status page displaying misleading information, because the disk titles no longer match the disk devices. Because this is a mirrored pool the status display shows disks in pairs, in the order they are mounted in the machine which is very nice when one disk is having issues, it is very easy to identify and replace.

So my question is, is it possible to use disk id's (from /dev/disk/by-id) in the data-netdata attribute to identify the specific device that matches the associated title?

This is on linux, both ubuntu and gentoo and seems related to #4957  #3084 and #3081. It would be great to have the default disk display use ata-* names rather than wwn-* names in my case as well.

**Comment by cakrit** [comment]
`data-netdata` is the chart name. Look at https://github.com/netdata/netdata/issues/3081#issuecomment-348301360
You can configure `netdata.conf` like this:
```
[plugin:proc:/proc/diskstats]
name disks by id = yes
```
This will change the chart name. But then you'll also need to configure your alarms accordingly, as mentioned in that comment.

**Comment by dscherger** [comment]
Thanks, I do have the configuration above in place and I see wwn disk names in the default disk charts. However in a custom dashboard if I try to use wwn names in `data-netdata="disk.sda"` I see errors like the following:
```wwn-0x50025385a0163ff4: chart not found on url "/api/v1/chart?chart=wwn-0x50025385a0163ff4" 
disk.wwn-0x50025385a0163ff4: chart not found on url "/api/v1/chart?chart=disk.wwn-0x50025385a0163ff4" 
```

**Comment by cakrit** [comment]
This can't be right. Can you see if your browser has cached the response?
I just tested it on my laptop. For the following...
```
"disk_svctm.sda": 		{
			"id": "disk_svctm.sda",
			"name": "disk_svctm.ata_samsung_mznln128hahq_00000_s3tune0jc97249",
```

... both of these URLs return data:

```
http://localhost:19999/api/v1/charts?chart=disk_svctm.ata_samsung_mznln128hahq_00000_s3tune0jc97249
http://localhost:19999/api/v1/chart?chart=disk_svctm.ata_samsung_mznln128hahq_00000_s3tune0jc97249
```

**Comment by dscherger** [comment]
Interesting... these both do return data
```
http://haswell:19999/api/v1/charts?chart=disk.ata-Samsung_SSD_840_PRO_Series_S1ANNSADB94283H
http://haswell:19999/api/v1/charts?chart=disk.wwn-0x50025385a0163ff0
```
but these both return errors
```
http://haswell:19999/api/v1/chart?chart=disk.ata-Samsung_SSD_840_PRO_Series_S1ANNSADB94283H
Chart is not found: disk.ata-Samsung_SSD_840_PRO_Series_S1ANNSADB94283H
http://haswell:19999/api/v1/chart?chart=disk.wwn-0x50025385a0163ff0
Chart is not found: disk.wwn-0x50025385a0163ff0
```
So charts (plural) is ok and char (singular) is not, and it looks like the singular char?char=... request is what data-netdata is hitting.
```
disk.ata-Samsung_SSD_840_PRO_Series_S1ANNSADB94283H: chart not found on url "/api/v1/chart?chart=disk.ata-Samsung_SSD_840_PRO_Series_S1ANNSADB94283H"
```

**Comment by cakrit** [comment]
Silly me, `/api/v1/charts` doesn't even support a `chart=` parameter, it's just ignored. So you'll get the result no matter what.

Now, it's obvious why `http://haswell:19999/api/v1/chart?chart=disk.ata-Samsung_SSD_840_PRO_Series_S1ANNSADB94283H` won't work for you, that's the id of my laptop's disk! :-)

I found the error in your call, it's the allmighty dash insteand of underscore. You'll see that the name in the `/api/v1/charts` is `disk.wwn_0x50025385a0163ff4` with an underscore, but you're requesting `disk.wwn-0x50025385a0163ff4` with a dash.

Our brains are not built to distinguish these two, the people who thought it a good idea to even have the underscore in software probably hadn't imagined the millions of work hours spent to debug such issues!

**Comment by dscherger** [comment]
So disk.ata-Samsung_SSD_840_PRO_Series_S1ANNSADB94283H is definitely not the disk in your laptop, that's definitely my disk but I don't seem to be able to refer to it using that name. Now I'm curious how/why the ata-* name works for you. Is there some special trick to get netdata to use those more meaningful names instead of the wwn names?

You are absolutely correct in that the underscore is the right answer to refer to the wwn disk though, that does work and it's definitely better than the unstable sda name. I'd still prefer to use the ata-... names here and in the general charts if there's some way to do that?

Thanks for the help though!

**Comment by dscherger** [comment]
One more bit of info, in another machine, some disks show up with the names I'd prefer like disk.ata_st3250620as_9qe1prvg and others show up with names like disk.wwn_0x50014ee2b6c032ce. Looking in /dev/disk/by-id all of the drives on this machine have ata-* names but only some have wwn-* names. If you have any ideas as to why this is I'd love to know.

Thanks again!
