### ISSUE TITLE
Memory RAM used by applications - 0.00 values are not useful

### ISSUE THREAD

**Issue by slrslr** [netdata/netdata#5574]
Hello, per [this screenshot](https://i.imgur.com/EuUIYB7.png) i can hardly discover RAM usage per app because Netdata shows "X" as top process and others are near 0.00 GB RAM. I am running Firefox and i think it should appear there and netdata allow better display apps. Current display is i think useless for me.

**Comment by vlvkobal** [comment]
`Ctrl + click` on dimensions you don't want to show. `Double click` to enable all the dimensions again.

**Comment by slrslr** [comment]
That helped, thank you.

The label "other" used RAM value greatly outmatch other labels. Any way to discover which apps are behind it? For example i do not see Firefox even i always assumed it was top RAM eater on my Windows PC (this is Linux).

label "X" is using 3GB of memory, isn|t this strange? i am using XFCE4

**Comment by Ferroin** [comment]
The `X` group includes Firefox in the default configuration.

Check https://github.com/netdata/netdata/blob/master/collectors/apps.plugin/apps_groups.conf for the current default configuration.  The collector just uses that file to map process names (matched with simple shell-style glob expressions) to application group names.
