### ISSUE TITLE
Chart is not stacked if it was created with only one dimension

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#5582]
##### Bug report summary
If a chart was created with one dimension and more dimensions were added later, the chart is not stacked.
![image](https://user-images.githubusercontent.com/22008543/54019130-15029700-4193-11e9-86fa-8a792e54e53f.png)
A simple page refresh makes it stacked.
![image](https://user-images.githubusercontent.com/22008543/54019241-5eeb7d00-4193-11e9-8915-3b5547a304ed.png)

##### Netdata version (ouput of `netdata -V`)
netdata v1.12.2-23-g3bf4edc4

##### Component Name
web gui

**Comment by ilyam8** [comment]
Issue moved to [netdata/dashboard #288](https://github.com/netdata/dashboard/issues/288) via [**ZenHub**](https://www.zenhub.com/)
