### ISSUE TITLE
Travis CI should upload docker images for PRs to docker hub

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5583]
##### Feature idea summary
k8s expect to download images from a docker registry. This adds another layer of complexity on our testing of PRs, as we'd need to do hacks like [this](https://github.com/kubernetes/minikube/blob/0c616a6b42b28a1aab8397f5a9061f8ebbd9f3d9/README.md#reusing-the-docker-daemon), or manually go through various steps that depend on where/how we test.

##### Expected behavior
Something similar to what is described in https://medium.com/mobileforgood/coding-tips-patterns-for-continuous-integration-with-docker-on-travis-ci-9cedb8348a62

Provide either a private docker registry that only contains PR images, or upload the PR images to docker hub, possibly on a different repository. Tag them clearly with the github PR id, so we can use that tag for our local tests.

Add that step to .travis and .travis.yml, so that it is executed ONLY for PRs.

**Comment by cakrit** [comment]
Looking more deeply into packaging/docker/build.sh the script does actually publish to docker hub, given the appropriate arguments. If possible, we should split publishing from building, because the script name is misleading.

**Comment by cakrit** [comment]
If we go ahead with this, we should also be deleting an image when a PR is closed:
https://github.com/docker/distribution/blob/ed0b3aebb31a38ba617bb21494de9e914b6e4bed/docs/spec/api.md#deleting-an-image

There is an alternative, for each tester to have either a private or public docker hub repository, where they upload the image they want by calling packing/docker/build.sh with appropriate arguments and environment variables. Will be trying it out as a workaround for now.

**Comment by paulkatsoulakis** [comment]
I think we have taken this feature for free, after all the pipeline clean ups that have taken place over the past month.

Basically each developer can setup travis to build his own branches within his fork.
He can define the repository to upload the docker images, along with the account details required.

What we don't have at all, is the deletion of the images as a step.
I will take a moment to think about it and propose an approach

**Comment by cakrit** [comment]
Deletion isn't required. Just put a small readme on how to configure travis on our own forks/branches and we can close this.
