### ISSUE TITLE
Failing docker builds

### ISSUE THREAD

**Issue by D34DC3N73R** [netdata/netdata#5588]
I make an automated netdata image with glibc for use with use with nvidia-docker. It has been failing with the most recent netdata builds, but still builds when using v1.12.1 as the base. This may be an upstream alpine issue, but I'm not sure. I've tried adding list of alpine mirrors to /etc/apk/repositories but that doesn't seem to make a difference. Here's the log of a failed build.

```
docker build -t netdata-glibc .
Sending build context to Docker daemon  156.7kB
Step 1/3 : FROM netdata/netdata
latest: Pulling from netdata/netdata
b3d31fe188a8: Already exists 
0defc930e58a: Already exists 
ac9f85fc2f09: Already exists 
ab66fe30fdd9: Already exists 
5308c9b93dcb: Already exists 
f84b6132626e: Already exists 
Digest: sha256:773b7b32b215f288de4f24e4fdffa6e8673a73a3fbd10838c341646554d8a99f
Status: Downloaded newer image for netdata/netdata:latest
 ---> 29784c318ad5
Step 2/3 : RUN ALPINE_GLIBC_BASE_URL="https://github.com/sgerrand/alpine-pkg-glibc/releases/download" &&     ALPINE_GLIBC_PACKAGE_VERSION="2.29-r0" &&     ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk" &&     ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk" &&     ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk" &&     apk --update upgrade && apk add --no-cache --virtual=.build-dependencies wget ca-certificates &&     wget         "https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub"         -O "/etc/apk/keys/sgerrand.rsa.pub" &&     wget         "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" &&     apk add --no-cache         "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"         "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" &&         rm "/etc/apk/keys/sgerrand.rsa.pub" &&     /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true &&     echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh &&         apk del glibc-i18n &&         rm "/root/.wget-hsts" &&     apk del .build-dependencies &&     rm         "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"         "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"
 ---> Running in 69122c75573a
fetch https://alpine:eyJ2IjoyLjEsIkRhdGEiOnsibmlkIjoiYjI3M2QyYzMiLCJvaWQiOiJkZDE5NTU1YjIwYzVlNWQyYjVlNTU3MjlhNmMyZjQ1NiIsInRpZCI6Im43RzdSNjZJIn0sInMiOiJNWVZ5QTZ6Mjd3eUhwRGtpMGRSVTl2QXZ6VUZQV2ROb3RYeGMrRWhtSGhJPSJ9@repo.polyverse.io/apk/alpine/3.9/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.polyverse.io/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch https://alpine:eyJ2IjoyLjEsIkRhdGEiOnsibmlkIjoiZDEzM2U5NmEiLCJvaWQiOiJkZDE5NTU1YjIwYzVlNWQyYjVlNTU3MjlhNmMyZjQ1NiIsInRpZCI6IlAyWnpKazhtIn0sInMiOiJCK1g4TE9hMUdDZkFaeFlYcTZuWUp3T0ZINnQzZGtqZnpha1lLQkJTNGpJPSJ9@repo.polyverse.io/apk/alpine/3.9/community/x86_64/APKINDEX.tar.gz
fetch http://mirrors.polyverse.io/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/4) Upgrading alpine-conf (3.8.1-r1 -> 3.8.1-r3)
(2/4) Upgrading alpine-base (3.9.0-r0 -> 3.9.2-r0)
(3/4) Upgrading libcurl (7.63.0-r0 -> 7.64.0-r1)
(4/4) Upgrading curl (7.63.0-r0 -> 7.64.0-r1)
Executing busybox-1.29.3-r10.trigger
1 error; 99 MiB in 60 packages
The command '/bin/sh -c ALPINE_GLIBC_BASE_URL="https://github.com/sgerrand/alpine-pkg-glibc/releases/download" &&     ALPINE_GLIBC_PACKAGE_VERSION="2.29-r0" &&     ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk" &&     ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk" &&     ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk" &&     apk --update upgrade && apk add --no-cache --virtual=.build-dependencies wget ca-certificates &&     wget         "https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub"         -O "/etc/apk/keys/sgerrand.rsa.pub" &&     wget         "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" &&     apk add --no-cache         "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"         "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" &&         rm "/etc/apk/keys/sgerrand.rsa.pub" &&     /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true &&     echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh &&         apk del glibc-i18n &&         rm "/root/.wget-hsts" &&     apk del .build-dependencies &&     rm         "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"         "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"' returned a non-zero code: 1
```

and the Dockerfile
```
FROM netdata/netdata

RUN ALPINE_GLIBC_BASE_URL="https://github.com/sgerrand/alpine-pkg-glibc/releases/download" && \
    ALPINE_GLIBC_PACKAGE_VERSION="2.29-r0" && \
    ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    apk update && apk add --no-cache --virtual=.build-dependencies wget ca-certificates && \
    wget \
        "https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub" \
        -O "/etc/apk/keys/sgerrand.rsa.pub" && \
    wget \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" && \
    apk add --no-cache \
        "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" && \
    \
    rm "/etc/apk/keys/sgerrand.rsa.pub" && \
    /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true && \
    echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh && \
    \
    apk del glibc-i18n && \
    \
    rm "/root/.wget-hsts" && \
    apk del .build-dependencies && \
    rm \
        "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"

ENV LANG=C.UTF-8
```
any help, tips, or pointers would be appreciated.

**Comment by D34DC3N73R** [comment]
The Dockerfile does build successfully using multiarch/alpine:amd64-edge as a base so it doesn't appear to be an alpine issue specifically.

**Comment by cakrit** [comment]
I ran this a few times:
```
/bin/sh -c ALPINE_GLIBC_BASE_URL="https://github.com/sgerrand/alpine-pkg-glibc/releases/download" &&     ALPINE_GLIBC_PACKAGE_VERSION="2.29-r0" &&     ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk" &&     ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk" &&     ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk" &&     wget         "https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub"         -O "sgerrand.rsa.pub" &&     wget         "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME"         "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME"
```

The first couple of times, I got this:
```
/2.29-r0/glibc-2.29-r0.apk: Scheme missing.
/2.29-r0/glibc-bin-2.29-r0.apk: Scheme missing.
/2.29-r0/glibc-i18n-2.29-r0.apk: Scheme missing.
```

After just a couple of minutes, all the downloads were successful. So there's definitely something strange going on. Perhaps the issue is with GitHub and not Alpine?

**Comment by D34DC3N73R** [comment]
I was thinking it might be some type of connection issue, but it has persisted for the last couple of weeks, it happens at home as well as docker hub, and the build completes successfully using other bases. For those reasons I'm lead to believe it is something else. As a test, I replaced the variables with the actual urls in the wget line and the build still fails at the same spot posted above.

**Comment by cakrit** [comment]
Can you try executing the command I put in the previous post yourself to see what you get? It only downloads those files, doesn't do anything else. The problem is that there are a bunch of commands getting executed besides that wget and it's really difficult to tell what produces the error like this. I don't know much about Dockerfiles, but isn't there a way to put that single line in a script that will execute the commands one by one, with an output?

**Comment by D34DC3N73R** [comment]
It fails with `apk add` regardless of what the package is.
```
FROM netdata/netdata
RUN apk add wget
``
build log
```
docker build -t netdata-glibc .
Sending build context to Docker daemon  15.98MB
Step 1/2 : FROM netdata/netdata
latest: Pulling from netdata/netdata
b3d31fe188a8: Pull complete 
0defc930e58a: Pull complete 
ac9f85fc2f09: Pull complete 
597ae51631a6: Pull complete 
0982f8729a05: Pull complete 
aaf537d3835c: Pull complete 
Digest: sha256:ec7a668e8e6712e225c0d8b00751f98d76ee814b8f529d115ee2b9a408babc41
Status: Downloaded newer image for netdata/netdata:latest
 ---> f1feee4716ca
Step 2/2 : RUN apk add wget
 ---> Running in fb48ed74c0b9
fetch https://alpine:eyJ2IjoyLjEsIkRhdGEiOnsibmlkIjoiYjI3M2QyYzMiLCJvaWQiOiJkZDE5NTU1YjIwYzVlNWQyYjVlNTU3MjlhNmMyZjQ1NiIsInRpZCI6ImppbEpKQVhWIn0sInMiOiJjWTJKZmwvMUJiYXA2RktoSlhvVUMxOFN6cGJGL0ptVlNOREFUZThVd2JRPSJ9@repo.polyverse.io/apk/alpine/3.9/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.polyverse.io/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch https://alpine:eyJ2IjoyLjEsIkRhdGEiOnsibmlkIjoiZDEzM2U5NmEiLCJvaWQiOiJkZDE5NTU1YjIwYzVlNWQyYjVlNTU3MjlhNmMyZjQ1NiIsInRpZCI6IjhVTzhsS0txIn0sInMiOiIvazF6NkNDdFQ4UzNvbkRxWUhaV1JkZUxHZHROenlPMkc2S0kxZy9uT1drPSJ9@repo.polyverse.io/apk/alpine/3.9/community/x86_64/APKINDEX.tar.gz
fetch http://mirrors.polyverse.io/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/1) Installing wget (1.20.1-r0)
Executing busybox-1.29.3-r10.trigger
1 error; 100 MiB in 61 packages
The command '/bin/sh -c apk add wget' returned a non-zero code: 1
```

**Comment by D34DC3N73R** [comment]
Another note of interest, if I clone netdata, and insert my build commands in the Dockerfile above the polyverse repo addition (directly after `FROM netdata/base:${ARCH}`) I can complete the build successfully.

**Comment by cakrit** [comment]
@archisgore can you please see if you can help with this one?

**Comment by archisgore** [comment]
Thanks @cakrit for flagging this. I'm investigating this ASAP.

**Comment by archisgore** [comment]
I can confirm that this is indeed caused when Polyverse packages are reinstalled in the base container.

```
(50/52) Replacing py2-psycopg2 (2.7.5-r0 -> 2.7.5-r0)
ERROR: py2-psycopg2-2.7.5-r0: failed to rename usr/lib/python2.7/site-packages/.apk.e6a4129270b3b99b221d1dbc3289eb2ec9dd67d2f0113746 to usr/lib/python2.7/site-packages/psycopg2-2.7.5-py2.7.egg-info.
```

It is this failed install trigger that puts it in a bad state due to a partial/failed upgrade. 

We're exploring fixes/workarounds as we speak. This is my highest priority.

**Comment by paulkatsoulakis** [comment]
Hello, @archisgore could you confirm an ETA on the solution for this?

**Comment by archisgore** [comment]
Yes indeed. I'll have a solution EOD. I'm sorry for the delay. I'll explain my thinking out loud here in case you have insights/suggestions.

1. The problem is caused by our repos being there and the reinstall. We always take full accountability for this. That being said, the problem is mainly in the install trigger of an upstream package (other Alpine containers have reported similar issues - due to how APK works.)

2. This leaves me with one option - some way to fix the bad-state APK gets into after this failed trigger.  I'm investigating a reliable option.

I'm also exploring some way to tell APK to ignore/rollback failed packages (opportunistic reinstall.)

3. The other option is to ignore the `1 error;` which according to docs is merely a report, but doesn't affect the actual operations. However ignoring that exit code risks ignoring a real error shoud one occur.

Is there something I'm missing? Else I'm pursing #2 - so that right after the reinstall, the APK will be reset into a good state.

I'll post back in more detail by EOD.

**Comment by paulkatsoulakis** [comment]
Ignoring failed packages or ignoring errors unless you have a very concrete trackable scenario that you can safely ignore, sounds like a bad idea indeed. I would also go with fixing the bad state in APK.
 Thanks for your prompt feedback, let me know if we can help somehow.

**Comment by D34DC3N73R** [comment]
Is there a problem with inserting `RUN apk fix py2-psycopg2` in the Dockerfile after the Polyverse package installation?

**Comment by archisgore** [comment]
Thanks @D34DC3N73R. I'm created a PR just now.
https://github.com/netdata/netdata/pull/5667
