### ISSUE TITLE
How to create custom gauge chart plugin

### ISSUE THREAD

**Issue by fti-dpogra** [netdata/netdata#5589]
Hi All, 

I am created a custom plugin which is showing stacked chart but i want to change it to 'easypiechart' or 'gauge chart' but everywhere is mentioned, Something like this: 'you can create chart without java script'.

but i want to create it with using plugin.

Any solution please?

Thank you so much!

**Comment by ilyam8** [comment]
Hi @fti-dpogra 	if i understand it right you need you need something like this

https://github.com/netdata/netdata/blob/3068d75ab275c356755356ab9087da8f1ef061a3/web/gui/dashboard_info.js#L1208-L1230

Please read the wiki how to customize the standard dashboard
https://docs.netdata.cloud/web/#customizing-the-standard-dashboards

**Comment by fti-dpogra** [comment]
thank you @ilyam8 
After the above case i have an issue 'Cannot load required JS library: http://********:19999/video_analysis.js' which is also mentioned and explained here 'https://github.com/netdata/netdata/issues/3104'

i have follow the suggestions but still having same problem

**Comment by ilyam8** [comment]
double check https://github.com/netdata/netdata/issues/3104#issuecomment-350093082

**Comment by fti-dpogra** [comment]
i already checked

**Comment by fti-dpogra** [comment]
i have again checked permission in .conf file...
       web files owner = netdata
	web files group = netdata
	bind to = *
	allow netdata.conf from = localhost
	enable gzip compression = yes
        custom dashboard_info.js = video_tracking.js

**Comment by ilyam8** [comment]
> http://********:19999/video_analysis.js'
> custom dashboard_info.js = video_tracking.js

**Comment by fti-dpogra** [comment]
i have two same files. is not any issue

**Comment by ilyam8** [comment]
could your show your `video_analysis.js` ?

**Comment by fti-dpogra** [comment]
Please check!

customDashboard.submenu = {
    'web_log.squid_bandwidth': {
        title: 'bandwidth',
        info: 'Bandwidth of responses (<code>sent</code>) by squid. This chart may present unusual spikes, since the bandwidth is accounted at the time the log line is saved by the server, even if the time needed to serve it spans across a longer duration. We suggest to use QoS (e.g. <a href="http://firehol.org/#fireqos" target="_blank">FireQOS</a>) for accurate accounting of the server bandwidth.'
    }
    'web_log.squid_bandwidth': {
        title: 'bandwidth A',
        info: 'Bandwidth of responses (<code>sent</code>) by squid. This chart may present unusual spikes, since the bandwidth is accounted at the time the log line is saved by the server, even if the time needed to serve it spans across a longer duration. We suggest to use QoS (e.g. <a href="http://firehol.org/#fireqos" target="_blank">FireQOS</a>) for accurate accounting of the server bandwidth.'
    }
};


// ----------------------------------------------------------------------------
// CONTEXT (the template each chart is based on)
//
// - info        html fragment for the description above the chart
// - height      a ratio to the default as a decimal number: 1.0 = 100%
// - colors      a single color or an array of colors to use for the dimensions
// - valuerange  the y-range of the chart as an array [min, max]
// - heads       an array of gauge charts to render above the submenu section
// - mainheads   an array of gauge charts to render at the menu section

var cgroupCPULimitIsSet = 0;
var cgroupMemLimitIsSet = 0;

customDashboard.context = {
    'mem.ksm_ratios': {
        heads: [
            function (os, id) {
                void(os);
                return '<div data-netdata="' + id + '"'
                    + ' data-gauge-max-value="100"'
                    + ' data-chart-library="gauge"'
                    + ' data-title="Savings"'
                    + ' data-units="percentage %"'
                    + ' data-gauge-adjust="width"'
                    + ' data-width="12%"'
                    + ' data-before="0"'
                    + ' data-after="-CHART_DURATION"'
                    + ' data-points="CHART_DURATION"'
                    + ' role="application"></div>';
            }
        ]
    },

is a just simply copy paste code

**Comment by fti-dpogra** [comment]
One more file:

// SPDX-License-Identifier: GPL-3.0-or-later
/*
 * Custom netdata information file
 * -------------------------------
 *
 * Use this file to add custom information on netdata dashboards:
 *
 * 1. Copy it to a new filename (so that it will not be overwritten with netdata updates)
 * 2. Edit it to fit your needs
 * 3. Set the following option to /etc/netdata/netdata.conf :
 *
 *    [web]
 *      custom dashboard_info.js = your_filename.js
 *
 * Using this file you can:
 *
 * 1. Overwrite or add messages to menus, submenus and charts.
 *    Use dashboard_info.js to find out what you can define.
 *
 * 2. Inject javascript code into the default netdata dashboard.
 *
 */

// ----------------------------------------------------------------------------
// MENU
//
// - title      the menu title as to be rendered at the charts menu
// - icon       html fragment of the icon to display
// - info       html fragment for the description above all the menu charts

customDashboard.menu = {
    'system': {
        title: 'System Overviewiiii',
	icon: '<i class="fas fa-bookmark"></i>',
	info: 'Overview of the key system metrics.'
    }
};


// ----------------------------------------------------------------------------
// SUBMENU
//
// - title       the submenu title as to be rendered at the charts menu
// - info        html fragment for the description above all the submenu charts

customDashboard.submenu = {
    'web_log.squid_bandwidth': {
        title: 'bandwidth',
	info: 'Bandwidth of responses (<code>sent</code>) by squid. This chart may present unusual spikes, since the bandwidth is accounted at the time the log line is saved by the server, even if the time needed to serve it spans across a longer duration. We suggest to use QoS (e.g. <a href="http://firehol.org/#fireqos" target="_blank">FireQOS</a>) for accurate accounting of the server bandwidth.'
    }
    'web_log.squid_bandwidth': {
        title: 'bandwidth A',
	info: 'Bandwidth of responses (<code>sent</code>) by squid. This chart may present unusual spikes, since the bandwidth is accounted at the time the log line is saved by the server, even if the time needed to serve it spans across a longer duration. We suggest to use QoS (e.g. <a href="http://firehol.org/#fireqos" target="_blank">FireQOS</a>) for accurate accounting of the server bandwidth.'
    }
};


// ----------------------------------------------------------------------------
// CONTEXT (the template each chart is based on)
//
// - info        html fragment for the description above the chart
// - height      a ratio to the default as a decimal number: 1.0 = 100%
// - colors      a single color or an array of colors to use for the dimensions
// - valuerange  the y-range of the chart as an array [min, max]
// - heads       an array of gauge charts to render above the submenu section
// - mainheads   an array of gauge charts to render at the menu section

customDashboard.context = {
    'mem.ksm_ratios': {
	    heads: [
	        function (os, id) {
		    void(os);
		    return '<div data-netdata="' + id + '"'
                        + ' data-gauge-max-value="100"'
			+ ' data-chart-library="gauge"'
			+ ' data-title="Savings"'
			+ ' data-units="percentage %"'
			+ ' data-gauge-adjust="width"'
			+ ' data-width="12%"'
			+ ' data-before="0"'
			+ ' data-after="-CHART_DURATION"'
			+ ' data-points="CHART_DURATION"'
			+ ' role="application"></div>';
		}
	    ]
        },
};

**Comment by cakrit** [comment]
> i have again checked permission in .conf file...

The question is whether `video_analysis.js` has identical ownership/permissions with `dashboard_info.js` and they're both in the same directory. Can you do an `ls -l` on the `web` directory of your installation to ensure the two files have the exact same ownership and permissions?

**Comment by fti-dpogra** [comment]
-rwxrwxrwx 1 root    root      3772 Mar  9 20:43 video_analysis.js

**Comment by cakrit** [comment]
> -rwxrwxrwx 1 root root 3772 Mar 9 20:43 video_analysis.js

It looks like the ownership is wrong. See what `dashboard_info.js` has please and do the `chown` to make them the same. You also don't need all those permissions there, `rw` on user and group is sufficient.

**Comment by fti-dpogra** [comment]
Hi currently i have added some code in dashboard_info_custom_example.js which is not showing any error but i am unable to aware about context. can you please help me 

// SPDX-License-Identifier: GPL-3.0-or-later
/*
 * Custom netdata information file
 * -------------------------------
 *
 * Use this file to add custom information on netdata dashboards:
 *
 * 1. Copy it to a new filename (so that it will not be overwritten with netdata updates)
 * 2. Edit it to fit your needs
 * 3. Set the following option to /etc/netdata/netdata.conf :
 *
 *    [web]
 *      custom dashboard_info.js = your_filename.js
 *
 * Using this file you can:
 *
 * 1. Overwrite or add messages to menus, submenus and charts.
 *    Use dashboard_info.js to find out what you can define.
 *
 * 2. Inject javascript code into the default netdata dashboard.
 *
 */

// ----------------------------------------------------------------------------
// MENU
//
// - title      the menu title as to be rendered at the charts menu
// - icon       html fragment of the icon to display
// - info       html fragment for the description above all the menu charts
var customDashboard = window.customDashboard || {};
customDashboard.menu = {
    'net': {
        title: 'New Video Analysi 1s',
	icon: '<i class="fas fa-th"></i>',
	info: 'Container resource utilization metrics. Netdata reads this information from <b>cgroups</b> (abbreviated from <b>control groups</b>), a Linux kernel feature that limits and accounts resource usage (CPU, memory, disk I/O, network, etc.) of a collection of processes. <b>cgroups</b> together with <b>namespaces</b> (that offer isolation between processes) provide what we usually call: <b>containers</b>.'
    }
};


// ----------------------------------------------------------------------------
// SUBMENU
//
// - title       the submenu title as to be rendered at the charts menu
// - info        html fragment for the description above all the submenu charts

customDashboard.submenu = {
};


// ----------------------------------------------------------------------------
// CONTEXT (the template each chart is based on)
//
// - info        html fragment for the description above the chart
// - height      a ratio to the default as a decimal number: 1.0 = 100%
// - colors      a single color or an array of colors to use for the dimensions
// - valuerange  the y-range of the chart as an array [min, max]
// - heads       an array of gauge charts to render above the submenu section
// - mainheads   an array of gauge charts to render at the menu section
customDashboard.context = {
'net.net': {
        heads: [
            function (os, id) {
                void(os);
                if (!id.match(/^cgroup_.*/))
                    return netdataDashboard.gaugeChart('new 1 Sent', '12%', 'sent');
                else
                    return '';
            }
        ]
}
};

please help me out

**Comment by fti-dpogra** [comment]
currently is showing three net graph but i want only one...

**Comment by cakrit** [comment]
It looks like you just need to change this line: `if (!id.match(/^cgroup_.*/))`
Put a break on that section to see the precise id of your chart and then convert it to an equality check instead, to only apply the change to the one you want.

**Comment by fti-dpogra** [comment]
Hi, 'net.net' is a built in currently which i m using but i want to create it custom. It would be great if you provide me sample code and some instruction.

**Comment by fti-dpogra** [comment]
Any update here???
