### ISSUE TITLE
Does this monitor allow for controlling lighting and fan components?

### ISSUE THREAD

**Issue by ridhwaans** [netdata/netdata#5599]
##### Question summary
Does this monitor allow for controlling pc fans and lighting?
##### OS / Environment
Windows
##### Component Name
fans, lighting, power
##### Expected results
Control panel which allows for toggling lighting (rgb, intensity), fans, power etc. The lighting source can be an led strip and doesnt necessarily have to be part of the component. Some computer builds have a fan controller board behind the mobo

**Comment by cakrit** [comment]
netdata only reads metrics, it doesn't 'control' what it monitors. It's also not currently available on Windows. So I think you'll need to look for a different software, I'm sure we have users here who can help guide you with possible options.
