### ISSUE TITLE
Proxmox containers no longer being renamed

### ISSUE THREAD

**Issue by shinji257** [netdata/netdata#5606]
##### Bug report summary
Starting recently (discovered today) Proxmox containers no longer appear to be renamed.  They are just showing up as their raw lxc container "names".  

##### OS / Environment
Debian GNU/Linux 9.8 (stretch)
Proxmox 5.3-11

##### Netdata version (ouput of `netdata -V`)
netdata v1.12.2-28-nightly (re-check with latest nightly on clean install on a test VM running same Proxmox release)
netdata v1.12.2-27-g2c55171 (discovered here while testing pull for #5477)

##### Component Name
cgroups

##### Steps To Reproduce
Install netdata using kickstart.sh

##### Expected behavior
In the past the Proxmox container cgroup would be renamed to using the hostname provided in /etc/pve for the specific container.

**Comment by shinji257** [comment]
As a data point I purged netdata from the VM and installed the current v1.12.2 stable build in the release downloads and that one renames them properly so it doesn't look like the distro did anything to break it.

**Comment by shinji257** [comment]
Checking further suggests that it may be an issue with invoking cgroup-name.sh? (Just a thought)

When running cgroup-name.sh manually it correctly gives back the hostname of related container cgroups even on the current commit here.

```
shinji@zeus:~$ sudo /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-name.sh lxc_100
2019-03-11 22:17:19: cgroup-name.sh: INFO: cgroup 'lxc_100' is called 'casper.robertpendell.com'
casper.robertpendell.com
shinji@zeus:~$ sudo /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-name.sh lxc_101
2019-03-11 22:17:23: cgroup-name.sh: ERROR: proxmox config file missing /etc/pve/lxc/101.conf or netdata does not have read access.  Please ensure netdata is a member of www-data group.
2019-03-11 22:17:23: cgroup-name.sh: INFO: cgroup 'lxc_101' is called 'lxc_101'
lxc_101
shinji@zeus:~$ sudo /opt/netdata/usr/libexec/netdata/plugins.d/cgroup-name.sh lxc_103
2019-03-11 22:17:25: cgroup-name.sh: INFO: cgroup 'lxc_103' is called 'hermes.robertpendell.com'
hermes.robertpendell.com
```

**Comment by vlvkobal** [comment]
@shinji257 please test this fix: #5612

**Comment by shinji257** [comment]
Yup.  They are getting renamed properly now.

**Comment by vlvkobal** [comment]
Thank you! Merged.
