### ISSUE TITLE
gauge chart issue

### ISSUE THREAD

**Issue by fti-dpogra** [netdata/netdata#5609]
Hi,

I added a custom gauge chart with system overview using system.cpu [context part] over 'dashboard_info_custom_example.js' file under web directory.

i want to implement this gauge chart with dynamic value which will be accessed by linux command [Example: ps | aux]

currently gauge chart is showing but is showing system.cpu data.

So my question is how can i display dynamic value with gauge chart without hover anywhere?

Below is 'dashboard_info_custom_example.js' code
Screenshot is also attached 
------------------------------------------------------------------------------------------

var customDashboard = window.customDashboard || {};
customDashboard.menu = {
    'system': {
        title: 'New Video Analysis 2',
	icon: '<i class="fas fa-th"></i>',
	info: 'Container resource utilization metrics. Netdata reads this information from <b>cgroups</b> (abbreviated from <b>control groups</b>), a Linux kernel feature that limits and accounts resource usage (CPU, memory, disk I/O, network, etc.) of a collection of processes. <b>cgroups</b> together with <b>namespaces</b> (that offer isolation between processes) provide what we usually call: <b>containers</b>.'
    }
};

// ----------------------------------------------------------------------------
// SUBMENU
//
// - title       the submenu title as to be rendered at the charts menu
// - info        html fragment for the description above all the submenu charts

customDashboard.submenu = {
};

// ----------------------------------------------------------------------------
// CONTEXT (the template each chart is based on)
//
// - info        html fragment for the description above the chart
// - height      a ratio to the default as a decimal number: 1.0 = 100%
// - colors      a single color or an array of colors to use for the dimensions
// - valuerange  the y-range of the chart as an array [min, max]
// - heads       an array of gauge charts to render above the submenu section
// - mainheads   an array of gauge charts to render at the menu section
customDashboard.context = {
'system.cpu': { 
	heads: [ 
            function (os, id) 
		{ void(os); 
		    return '<div data-netdata="' + id + '"' 
			    + ' data-gauge-max-value="100"' 
			    + ' data-gauge-generate-gradient="[0, 10, 100]"' 
			    + ' data-chart-library="gauge"' 
			    + ' data-title="Savings"' 
			    + ' data-units="percentage %"' 
			    + ' data-gauge-adjust="width"' 
			    + ' data-width="12%"' 
			    + ' data-before="0"'
			    + ' data-after="-CHART_DURATION"' 
			    + ' data-points="CHART_DURATION"' 
			    + ' data-colors="' + NETDATA.colors[4] + '"' 
			    + ' role="application"></div>'; 
		    } 
	    ] 
    }
};
![Screenshot_2019-03-12 Get control of your Linux Servers Simple Effective Awesome ](https://user-images.githubusercontent.com/47653584/54181242-ebfc4200-44c3-11e9-96a7-a85bd556b578.png)

**Comment by gmosx** [comment]
What exact metric would you like to visualize with the gauge? I don't understand this part:

```
with dynamic value which will be accessed by linux command [Example: ps | aux]
```

**Comment by fti-dpogra** [comment]
i have a script (shell) which genrates output (any positive number) randomly
