### ISSUE TITLE
Partial override of alert

### ISSUE THREAD

**Issue by mickaelperrin** [netdata/netdata#5611]
##### Question summary

I am currently searching for the best way to silent some alarms. Currently I copy and paste the entire default alarm configuration in /etc/netdata/health.d and replace to: to to: silent.

Example:

```
template: 10min_disk_backlog
      on: disk.backlog
      os: linux
   hosts: *
families: *
  lookup: average -10m unaligned
   units: ms
   every: 1m
   green: 2000
     red: 5000
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1))
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1))
   delay: down 15m multiplier 1.2 max 1h
    info: average of the kernel estimated disk backlog, for the last 10 minutes
      to: silent
```

I was wondering if there is some kind of support to only override the provided lines, for example, only:

```
template: 10min_disk_backlog
      to: silent
```
##### OS / Environment

Linux / Ubuntu 18.04

##### Component Name

alarm

**Comment by cakrit** [comment]
Unfortunately this is all you can do right now, but check #3414, we'll be adding that functionality soon.

**Comment by cakrit** [comment]
Closing this in favor of #3414

**Comment by lkraav** [comment]
As of 1.19, it's not clear from following the PR trail what's the process to overriding partial alarm parameters now?

Would love

```
template: postgres_last_collected_secs
   every: 60s
```

**Comment by cakrit** [comment]
Yes, that's what we did instead, added notification silencers. It's been a while since that was deployed definitely long before 1.19.
