### ISSUE TITLE
When zooming out of a chart, we should keep updating it

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5613]
##### Feature idea summary
Currently zooming out of a chart stops the update with new data points.

##### Expected behavior
Zooming out should show the new datapoints, correctly averaged.

**Comment by startryst** [comment]
Any update on this one?

**Comment by jacekkolasa** [comment]
I can't say now, when this feature will be available, but we'll do it. Thanks for asking

**Comment by jacekkolasa** [comment]
@dim08 We could do this, what do you think?

**Comment by r3flow** [comment]
related #2631

**Comment by ilyam8** [comment]
That is fixed.
