### ISSUE TITLE
schedule time for fping.conf

### ISSUE THREAD

**Issue by doludizgin** [netdata/netdata#5614]
##### Question summary
I want to ping digital signage computers to check if they are up. Problem is that they shutdown at night. So that will mean i get alot ping errors on netdata. They are Windows machines, so ping check just to check online status would be easiest.
##### OS / Environment
Ubuntu (netdata server) Windows 10 client
##### Component Name
fping
##### Expected results
Set a fping schedule to ping only within cetrain time

**Comment by ilyam8** [comment]
related #3187

**Comment by cakrit** [comment]
@ilyam8 is correct, the documentation is [here](https://docs.netdata.cloud/web/api/health/#health-management-api).
