### ISSUE TITLE
Notify on value change

### ISSUE THREAD

**Issue by KlausBuchegger** [netdata/netdata#5623]
##### Question summary
I'd like to know if it's possible to set a health notification rule to send an email whenever a value changes. Or even better, if a value increases. 

I just set up the freeipmi.plugin and there is an alert that sends a warning email when the system event log contains entries. Now if we don't reset the list whenever something pops up, there will be no more emails sent from netdata, as the event count will be >= 1 forever.

I guess, one way would be to set the chart to incremental, but this is within the freeipmi.plugin, I'd prefer not to meddle with that. Can I somehow refer to the previous value within an alarm rule?

##### Component Name
freeipmi.plugin
##### Expected results
Netdata should send an email whenever ipmi.events $events increases

**Comment by ilyam8** [comment]
Hi @KlausBuchegger 	

> Can I somehow refer to the previous value within an alarm rule?

You need 2 alarms (first one only to calculate a value, that will be used in seconds).

This is example:

https://github.com/netdata/netdata/blob/b7998ec82d579bd0550e23f880decdcee61264f5/health/health.d/net.conf#L137-L168


[health wiki](https://docs.netdata.cloud/health/)

**Comment by KlausBuchegger** [comment]
Perfect, thank you :) 

Now that you mention it, I vaguely remember reading about those alarm rules you cited.
I have now one rule that stores the minimum of the last 20 seconds, and another rule checking the maximum of the last 10 seconds. Those two are compared and a warning is issued if the maximum is bigger than the minimum
