### ISSUE TITLE
Creating an alarm issue - steps for creation?

### ISSUE THREAD

**Issue by lindsayjm** [netdata/netdata#5628]
Hello, 

I'm trying to create an alarm for a denial of service attack, and I've gone through issue #1202 already, but for some reason once I create an alarm file, not only is it not appearing but its also not appearing in the JSON file (localhost:19999/api/v1/alarms?all) 

Can you provide a step by step for how to create and alarm and what files need to be altered for them to be functional? 

Thanks!

**Comment by ilyam8** [comment]
Hi @lindsayjm 	

There you go
 - [health wiki page](https://docs.netdata.cloud/health/)
 - [existing alarms](https://github.com/netdata/netdata/tree/master/health/health.d) (examples)

**Comment by ilyam8** [comment]
:smile:

**Comment by lindsayjm** [comment]
Thanks!

**Comment by lindsayjm** [comment]
For some reason, when I create a .conf file, its still not functioning properly. I'm using the exact example alarm posted in #1202

**Comment by ilyam8** [comment]
What is _not functioning properly_ ?

What exactly alarm are you talking about?

**Comment by lindsayjm** [comment]
I've added the alarm listed in #1202, by ktsaou:
 alarm: eth0_packets
      on: net_packets.eth0
   units: packets
   every: 10s
    warn: $received > 5000
    crit: $received > 10000
   delay: down 10m multiplier 1.5 max 1h
    info: number of packets received on the interface
      to: sysadmin

I've made sure the file ends with .conf, and it does exist within health.d, but for some reason it is not enabled when I run the dashboard and is not appearing when running a DDOS attack. It also does not appear in the json file.

**Comment by ilyam8** [comment]
- make sure alarm is readable by `netdata` user
- do `killall -USR2 netdata` or `systemctl restart netdata.service`
- check dashboard alarm section

If there is no your alarm check `error.log` (`grep <alarm_name> error.log`)

**Comment by lindsayjm** [comment]
After performing those three steps, running again, and cannot find the file name within the error log, what would you suggest trying next?

**Comment by lindsayjm** [comment]
I will say for testing purposes, some of the alarms that are built-in with netdata (such as softnet.conf) are appearing when a DDOS is launched; I've tried changing the info in these files just as a test but the change is not reflected even after `killall -USR2 netdata`

**Comment by ilyam8** [comment]
> I've tried changing the info in these files just as a test but the change is not reflected even after killall -USR2 netdata

This should work. Are you changing files in right place? (not in source code)

ok, what i did (in installed netdata to `/opt/`:

 - `cd /opt/netdata/etc/netdata/health.d/`
 - add my alarm there
 - `killall -USR2 netdata`

it works

**Comment by lindsayjm** [comment]
So I have it installed in /opt/, but my path is /opt/netdata/health/health.d

Should I be creating the /etc/ directory?

**Comment by ilyam8** [comment]
> but my path is /opt/netdata/health/health.d

if you install netdata in `/opt`, the path will be `opt/netdata/etc/netdata/health.d/`

**Comment by lindsayjm** [comment]
Thanks!
