### ISSUE TITLE
Isn't it a security risk not having SSL mode for postgres plugin?

### ISSUE THREAD

**Issue by DenLilleMand** [netdata/netdata#5629]
##### Question summary
Isn't it a security risk not having SSL mode for postgres plugin?
In the normal configuration you can specify a SSLMode and a key.

##### OS / Environment
Any

##### Component Name
Postgres
##### Expected results
To have the normal configuration options the driver supports

**Comment by ilyam8** [comment]
https://www.postgresql.org/docs/9.1/libpq-ssl.html
