### ISSUE TITLE
[Question] Are python-pymongo and python-yaml needed for a barebones install of netdata?

### ISSUE THREAD

**Issue by elfgoh** [netdata/netdata#5632]
##### Question summary
I install netdata using ` bash <(curl -Ss https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/kickstart.sh)  --dont-wait`

The output from deriving the dependencies are as follows:
```

 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'netcat' is installed...
dpkg-query: no packages found matching netcat
 > Checking if package 'zlib1g-dev' is installed...
 > Checking if package 'uuid-dev' is installed...
 > Checking if package 'libmnl-dev' is installed...
 > Checking if package 'python' is installed...
dpkg-query: no packages found matching python
 > Checking if package 'python-yaml' is installed...
dpkg-query: no packages found matching python-yaml
 > Checking if package 'python-pymongo' is installed...
dpkg-query: no packages found matching python-pymongo

The following command will be run:

 >> IMPORTANT <<
    Please make sure your system is up to date
    by running:   apt-get update

apt-get -yq install netcat python python-pymongo python-yaml


apt-get -yq install netcat python python-pymongo python-yaml
Reading package lists...
```

Question: Are `python-pymongo` and `python-yaml` really needed, since I am not monitoring mongodb and beanstalkd?

PS. After successful installation of netdata, removal of  `python-pymongo` and `python-yaml` doesn't seem to affect ability to run netdata

Reference: https://docs.netdata.cloud/packaging/installer/#install-netdata
##### OS / Environment
Debian armhf

##### Component Name
Installer

##### Expected results
Both `python-pymongo` and `python-yaml` arent needed by netdata

**Comment by ilyam8** [comment]
`python-yaml` is not needed at all, netdata shipped with pyyaml package

**Comment by elfgoh** [comment]
> `python-yaml` is not needed at all, [netdata shipped with pyyaml package](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/python_modules)

In that case, why is the installer prompting for the install of `python-yaml`? Is this a bug?

**Comment by ilyam8** [comment]
it was needed.. long time ago
https://github.com/netdata/netdata/pull/4014/files

**Comment by elfgoh** [comment]
Looking at the source leads me to https://github.com/netdata/netdata-demo-site/blob/master/install-required-packages.sh

I haven't figured out the logic but perhaps I will get to it later, or maybe someone else will get to it before I do 🙇

**Comment by ilyam8** [comment]
I see `kickstart.sh` is a bit outdated.
Anyway it shouldn't install additional packages like `python-pymongo` w/o `-netdata-all` [option](https://github.com/netdata/netdata-demo-site/blob/db806dcf03b9cceb0130a4d3cb33ab97a8f019db/install-required-packages.sh#L88).

@paulkatsoulakis i need your help here

**Comment by elfgoh** [comment]
Out of curiosity, why isn't the [script handling netdata dependencies](https://github.com/netdata/netdata/blob/master/packaging/installer/kickstart.sh#L196) in this repo, but in a [separate repo](https://github.com/netdata/netdata-demo-site/blob/master/install-required-packages.sh) instead?

Any idea?
