### ISSUE TITLE
Want to disable python module

### ISSUE THREAD

**Issue by fti-dpogra** [netdata/netdata#5634]
NetData, is very helpful for me

I am successfully created a python module which is showing staked chart and also i created a custom dashboard which is showing gauge chart.

Gauge chart is created for this python module which is created by me. 

i want only gauge chart not this stacked chart.

is it possible?
Please suggest!

Thank you!

**Comment by ilyam8** [comment]
> i want only gauge chart not this stacked chart.

Hi @fti-dpogra 	could show a screenshot? i am not clear what are you talking about.

**Comment by fti-dpogra** [comment]
![Screenshot_2019-03-14 Get control of your Linux Servers Simple Effective Awesome ](https://user-images.githubusercontent.com/47653584/54358469-85735180-4686-11e9-9b46-ac10b38f8917.png)

**Comment by fti-dpogra** [comment]
i want to remove this stacked chart which are showing below gauge chart

**Comment by ilyam8** [comment]
Oh, i understand now. It is impossible. Those thing are too tightly coupled (database and dashboard)

**Comment by ilyam8** [comment]
@gmosx 	correct me if i am wrong

**Comment by fti-dpogra** [comment]
You are right but any solution??

**Comment by ilyam8** [comment]
There is a way to `hide` a chart from the dashboard, but there is not way to have  all charts hidden and still have gauges.

Lets wait @gmosx, i wish i wrong, but from what i know it is impossible now.

**Comment by fti-dpogra** [comment]
Thank you @ilyam8 
Waiting @gmosx

**Comment by gmosx** [comment]
I am not sure also. Will investigate and get back to you.
Nice dashboard btw :)

**Comment by ktsaou** [comment]
There is no way to hide a chart that is being collected.

But, you can create a custom dashboard and add any number of charts, of any type.

**Comment by ilyam8** [comment]
> There is no way to hide (on the default dashboard) a chart that is being collected.

`hidden` option

> and hidden to perform all operations on a chart, but do not offer it on dashboards (the chart will be send to backends)

**Comment by ktsaou** [comment]
it will remove the chart from the dashboard entirely (even the gauge)

**Comment by fti-dpogra** [comment]
> There is no way to hide (on the default dashboard) a chart that is being collected.
> 
> But, you can create a custom dashboard and add any number of charts, of any type.

All these gauge charts which are currently showing ( https://github.com/netdata/netdata/issues/5634#issuecomment-472840733 ) already coming from custom dashboard.

Is it possible gauge chart (from custom dashboard) will works without any python script?

**Comment by fti-dpogra** [comment]
> I am not sure also. Will investigate and get back to you.
> Nice dashboard btw :)

Thank you @gmosx

**Comment by fti-dpogra** [comment]
> > Also in gauge chart is not accepting decimal values..
> 
> https://docs.netdata.cloud/collectors/plugins.d/#data-collection
> 
> > is the collected value, only integer values are collected. If you want to push fractional values, multiply this value by 100 or 1000 and set the DIMENSION divider to 1000.

I tried but still not accepting fractional value. please check!
Example of my code:

'motion_tracker': {
        'options': [None, 'Video Analysis Graph', 'Motion Detection', 'Video Analysis', 'motion_tracker', 'stacked'],
        'lines': [
            ['motion_tracker','created', 'absolute', 1, 1000]
        ]
    },
  ------------------------------------------  
    def get_data(self):
        data = dict()
        data.setdefault('motion_tracker', 4.56)
        
        data.setdefault('motion_tracker', 4.56)
        return data

**Comment by ilyam8** [comment]
@fti-dpogra 

> If you want to push fractional values, multiply this value by 1000 and set the DIMENSION divider to 1000.

this will do

`data.setdefault('motion_tracker', 4.56 * 1000)`

**Comment by fti-dpogra** [comment]
> ```python
> data.setdefault('motion_tracker', 4.56 * 1000)
> ```
see my output:

DIMENSION 'motion_tracker' 'motion tracking' incremental 1 1 ''

BEGIN video_analysis.motion_tracker 0
SET 'motion_tracker' = 4560
END

**Comment by ilyam8** [comment]
The output is correct

**Comment by fti-dpogra** [comment]
> The output is correct

Thank you @ilyam8

**Comment by fti-dpogra** [comment]
> There is a way to `hide` a chart from the dashboard

There is a way to hide a chart from the dashboard?? Please Explain!

Now We have removed all gauge chart...

1. Want to run custom module only in backend not in netdata dashboard..

**Comment by ilyam8** [comment]
> There is a way to hide a chart from the dashboard

But

> it will remove the chart from the dashboard entirely (even the gauge)

`hidden` keyword after the `line`

https://github.com/netdata/netdata/blob/d27effa5d0d658dc04d45a89fa8ec86c582e2916/collectors/python.d.plugin/monit/monit.chart.py#L66-L69

**Comment by fti-dpogra** [comment]
> > There is a way to hide a chart from the dashboard
> 
> But
> 
> > it will remove the chart from the dashboard entirely (even the gauge)
> 
> `hidden` keyword after the `line`
> 
> [netdata/collectors/python.d.plugin/monit/monit.chart.py](https://github.com/netdata/netdata/blob/d27effa5d0d658dc04d45a89fa8ec86c582e2916/collectors/python.d.plugin/monit/monit.chart.py#L66-L69)
> 
> Lines 66 to 69 in [d27effa](/netdata/netdata/commit/d27effa5d0d658dc04d45a89fa8ec86c582e2916)
> 
>  'process_uptime': { 
>      'options': ['processes uptime', 'Processes uptime', 'seconds', 'applications', 
>                  'monit.process_uptime', 'line', 'hidden'], 
>      'lines': []

Thank you @ilyam8 

Disabled from netdata dashboard... 

:)

**Comment by ilyam8** [comment]
i believe yes, if module works in debug mode it will work in normal mode too.

**Comment by fti-dpogra** [comment]
> i believe yes, if module works in debug mode it will work in normal mode too.

Thank you @ilyam8 
:100:

**Comment by ilyam8** [comment]
@fti-dpogra 
so the answer to OP is https://github.com/netdata/netdata/issues/5634#issuecomment-472984683

i am closing the issue
