### ISSUE TITLE
[preparation] VMware Vsphere monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#5635]
I see #4888 is getting votes.

Plan is to setup a vmware vsphere lab and investigate APIS/metrics.

___
[golang library](https://github.com/vmware/govmomi/#govmomi)

Metrics Groups:
 - Virtual Machine
 - Host System 
 - Cluster
 - Datastore

I want to understand what metrics are most useful, how many collectors do we need, etc.

@jimidak @spiegela I hope for help/assistance :smile:

**Comment by ilyam8** [comment]
Ok, i failed to setup a lab on my PC (manjaro).

i downloaded:
 - `VMware-VMvisor-Installer-6.7.0-8169922.x86_64.iso`
 - `VMware-VCSA-all-6.7.0-11726888.iso`

i couldn't even install ESXI, for some reason installation hangs forever (I waited an hour). Dunno, maybe virtualbox problem. I need to try something else.

![Screenshot_20190318_223214](https://user-images.githubusercontent.com/22274335/54560404-59800500-49d3-11e9-8375-22854ff84cb3.png)

___

@jimidak i need your help. So you have a vmware cluster, right? From what i read we need to gather info using [vcenter api](https://www.vmware.com/support/developer/vcsa-mgmt-sdk/index.html)

Lets collect all info.

I see there are two libraries:
 - [pyvmomi](https://github.com/vmware/pyvmomi) (`python`)
 - [govmomi](https://github.com/vmware/govmomi/tree/master/govc) (`go`)


Have you tried any of them? I think we need to use go version, but if you are willing to work on it and prefer to use python that is ok too.

What do you think?

**Comment by mfundul** [comment]
From memory I recall that the only VirtualBox NIC working with ESXi is Intel PRO/1000 T Server.

**Comment by jimidak** [comment]
> Ok, i failed to setup a lab on my PC (manjaro).
> 
> i downloaded:
> 
>     * `VMware-VMvisor-Installer-6.7.0-8169922.x86_64.iso`
> 
>     * `VMware-VCSA-all-6.7.0-11726888.iso`
> 
> 
> i couldn't even install ESXI, for some reason installation hangs forever (I waited an hour). Dunno, maybe virtualbox problem. I need to try something else.
> 
> ![Screenshot_20190318_223214](https://user-images.githubusercontent.com/22274335/54560404-59800500-49d3-11e9-8375-22854ff84cb3.png)
> 
> @jimidak i need your help. So you have a vmware cluster, right? From what i read we need to gather info using [vcenter api](https://www.vmware.com/support/developer/vcsa-mgmt-sdk/index.html)
> 
> Lets collect all info.
> 
> I see there are two libraries:
> 
>     * [pyvmomi](https://github.com/vmware/pyvmomi) (`python`)
> 
>     * [govmomi](https://github.com/vmware/govmomi/tree/master/govc) (`go`)
> 
> 
> Have you tried any of them? I think we need to use go version, but if you are willing to work on it and prefer to use python that is ok too.
> 
> What do you think?

Thanks! Yes, I've been messing around with the 6.* API, and the vCenter swagger type page to understand all the API endpoints.  Working well. I have not tried the libs- just doing cURLs to the API endpoints, and getting just what I want back with POSIX utilities like grep, awk, sed, jq, etc. If I were to monitor this outside of Netdata, I would probably just make that a bash script, or python script with the os module. 

I will read up on pyvmoni.

Right now, I am doing some ESXi pre-req work on my test Netdata server, and running into a few snags. Just overall trying to understand how things work.

**Comment by ilyam8** [comment]
> From memory I recall that the only VirtualBox NIC working with ESXi is Intel PRO/1000 T Server.

I couldn't even install esxi, installation process stuck at some point :cry: 

@jimidak 	

yes, use `pyvmoni`, focus on data we can get from vcenter using the library, not on how to write module for netdata.

I think we need to see data first, agreed on charts on only after it start to implement it.

**Comment by jimidak** [comment]
> > From memory I recall that the only VirtualBox NIC working with ESXi is Intel PRO/1000 T Server.
> 
> I couldn't even install esxi, installation process stuck at some point 😢
> 
> @jimidak
> 
> yes, use `pyvmoni`, focus on data we can get from vcenter using the library, not on how to write module for netdata.
> 
> I think we need to see data first, agreed on charts on only after it start to implement it.

Can you point me to a doc on netdata.conf examples? Looking for "command options =" syntax.

**Comment by ilyam8** [comment]
> Looking for "command options =" syntax.

i see you are discussing that thing with @cakrit in https://github.com/netdata/netdata/issues/5344#issuecomment-474276203

Where do you need that ` "command options =" syntax` ?

**Comment by jimidak** [comment]
For the freeipmi section

**Comment by ilyam8** [comment]
oh, ok, i think this is the answer https://github.com/netdata/netdata/issues/5344#issuecomment-474447267

**Comment by ilyam8** [comment]
@jimidak btw if you want we can have a chat, i could help you with vsphere python stuff

**Comment by jimidak** [comment]
> @jimidak btw if you want we can have a chat, i could help you with vsphere python stuff

I would totally take you up on that!! Thanks. i think I just need a little nudge to get over a couple hurdles.

**Comment by ilyam8** [comment]
Nice, ping me when you feel ready :+1:

**Comment by jimidak** [comment]
I started to mess around with the VMWare python libs. I am getting re-orged at my company, and may lose access to the VSphere (and sadly get pulled off the Netdata project. I will dump whatever I learned, here, before that happens.

**Comment by ilyam8** [comment]
@jimidak could you ask other guys from the VSphere team if they are interested in helping us to build vmware vsphere monitoring? If so please give them the link to this issue. Would be very nice.

**Comment by Ludacon** [comment]
I run a test lab that handles some real life load for personal projects, im not sure exactly what you are looking for but i would love to help in any way i can.

**Comment by ilyam8** [comment]
i finally managed to set up a lab. Thanks to @vlvkobal. I am using his server :relaxed:  

3 esxi instances + vCenter appliance.

Real-time metrics are only available for ESXI hosts and VMs ([link](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/vsphere#realtime-vs-historical-metrics))
