### ISSUE TITLE
KVM Guest

### ISSUE THREAD

**Issue by parallelsys** [netdata/netdata#5642]
After the past two updates netdata no longer reports my vm's CPU/RAM/DISK information.

It was working without issues before.

netdata v1.12.2-46-ga2992216
OS: Fedora Server 28 x86_64
Hypervisor: KVM

The eror I get is:

cgroup_machine.slice_machine-qemu_x2d2_x2dmeteohub.scope.cpu_limit: data download failed for url: http://SERVER:19999/api/v1/data?chart=cgroup_machine.slice_machine_qemu_x2d2_x2dmeteohub.scope.cpu_limit&format=array&points=420&group=average>ime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-420&dimensions=used
cgroup_machine.slice_machine-qemu_x2d2_x2dmeteohub.scope.mem_usage_limit: data download failed for url: http://SERVER:19999/api/v1/data?chart=cgroup_machine.slice_machine_qemu_x2d2_x2dmeteohub.scope.mem_usage_limit&format=array&points=420&group=average>ime=0&options=absolute%7Cpercentage%7Cjsonwrap%7Cnonzero&after=-420&dimensions=used
cgroup_machine.slice_machine-qemu_x2d2_x2dmeteohub.scope.throttle_io: data download failed for url: http://SERVER:19999/api/v1/data?chart=cgroup_machine.slice_machine_qemu_x2d2_x2dmeteohub.scope.throttle_io&format=array&points=420&group=average>ime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-420&dimensions=read
cgroup_machine.slice_machine-qemu_x2d2_x2dmeteohub.scope.throttle_io: data download failed for url: http://SERVER:19999/api/v1/data?chart=cgroup_machine.slice_machine_qemu_x2d2_x2dmeteohub.scope.throttle_io&format=array&points=420&group=average>ime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-420&dimensions=write

**Comment by vlvkobal** [comment]
Please provide a default netdata dashboard screenshot with the right menu. What cgroups are displayed there?

**Comment by parallelsys** [comment]
Actually, I am awed... LOL
I just came back and the damn thing looks normal now and reporting just fine.

Not sure what to say...
