### ISSUE TITLE
Notifications on chrome and not on discord

### ISSUE THREAD

**Issue by secato** [netdata/netdata#5643]
Hey, I had set up my notifications conf to send to a channel in discord and received the test notifications correctly.

Right now the web interface of netdata is showing a warning for me but the notification doesn't reach the discord.

There is something that I'm doing wrong?

**Comment by ilyam8** [comment]
> Right now the web interface of netdata is showing a warning for me but the notification doesn't reach the discord.

It can be because of [delay](https://docs.netdata.cloud/health/#alarm-line-delay) param.

If there is any error in sending i believe it should be logged, so check the `error.log`

**Comment by secato** [comment]
Right. I'm getting this

`alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host`

I double checked and health_alarm_notify.conf is created at /etc/netdata/health_alarm_notify.conf, also SEND_DISCORD="YES" is set.

I restarted netdata and then checked the log again and got this in the init log, I'm not sure if it means something: 

`alarms default handler '/usr/libexec/netdata/plugins.d/alarm-notify.sh', alarms default recipient 'root'`

**Comment by ilyam8** [comment]
whats your netdata version? (ouput of `netdata -V`)

**Comment by secato** [comment]
My version is **netdata v1.12.2-46-nightly**

Update:
I changed the health_alarm_notify.conf and changed others SEND_XXXXXX to "NO". Keeping only the SEND_DISCORD="YES"

Restarted the server again and received a notification in discord.
But I tried to restart it again and received not, maybe because of the delay param.

Can I execute the script manually to simulate? with the "test" parameter is working, but I wanna test with real alarms.
`/usr/libexec/netdata/plugins.d/alarm-notify.sh`

**Comment by ilyam8** [comment]
> Restarted the server again

`killall -USR netdata`

> but I wanna test with real alarms.

it is easy to test:
 - see current value
 - tune your alarm (change warn/crit conditions to current value)
 - `killall -USR netdata`

**Comment by cakrit** [comment]
All the notifications are enabled by default, but in general nothing is executed unless you specify the other required settings. For Discord these need to be set:
```
DISCORD_WEBHOOK_URL=""
DEFAULT_RECIPIENT_DISCORD=""
```

If you've correctly set them, the best debugging is to do what's mentioned at the end of https://docs.netdata.cloud/health/notifications/#testing-notifications
When you execute the `bash -x` with the many arguments, you'll see what fails.

**Comment by secato** [comment]
I changed my set up recently to use streaming.
My nodes are headless collector, so I need only to set up the master netdata for notifications, right?

I will do some tests here and get back soon

**Comment by cakrit** [comment]
> My nodes are headless collector, so I need only to set up the master netdata for notifications, right?

Indeed. Just disable health checks in the slaves, as shown [in the documentation](https://docs.netdata.cloud/streaming/#configuring-the-slaves). 

Check stream.conf for the master too, it also has a setting, so that the master raises alarms for the slaves: https://docs.netdata.cloud/streaming/#configuring-the-master

**Comment by secato** [comment]
Ok guys, I got a notification on discord now. Thanks and sorry for the trouble.

**PS:** This project is one of the most awesome open source project that I've used recently
