### ISSUE TITLE
changelog should include go.d.plugin

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#5648]
##### Bug report summary

netdata v1.13.0 changlog don't contain go.d.plugin's changelog.

##### Component Name
release

**Comment by cakrit** [comment]
Thanks @Wing924, as always, to the point, with valuable feedback!

I think that we should do the following:
- Have a CHANGELOG.md generated under https://github.com/netdata/go.d.plugin 
- The automated entry in the netdata/netdata CHANGELOG.md for a new version of the plugin should then point to `https://github.com/netdata/go.d.plugin/CHANGELOG.md#[version]`

**Comment by Wing924** [comment]
There is a problem: go plugin have 2 repos.
It's hard to generate meaningful changelog when improve something across both repos.

**Comment by cakrit** [comment]
> There is a problem: go plugin have 2 repos.
> It's hard to generate meaningful changelog when improve something across both repos.

We should do the same thing with the changes to the library then. Have the go.d.plugin reference the version of the lib it uses and have a PR that mentions the changes to the lib whenever that version changes. @ilyam8 is that ok?

**Comment by ilyam8** [comment]
> It's hard to generate meaningful changelog when improve something across both repos

go.d.plugin is a group of modules, i think you mean we need to add go-orchestrator changelog, but it's different thing.

lets start from `go.d.plugin` changelog.

**Comment by Wing924** [comment]
The go.d.plugin changelog is for users while go-orchestrator changelog is for developers.
So netdata changelog should only include `go.d.plugin`.

**Comment by cakrit** [comment]
I was probably misunderstood. netdata will only refer to the `go.d.plugin`, not the orchestrator. The `go.d.plugin` can similarly refer to changes to the orchestrator, if there are any.

**Comment by Wing924** [comment]
@cakrit 
Do you mean only provide a link to `go.d.plugin` changelog?

**Comment by cakrit** [comment]
Let me illustrate:

If we were to improve what we do today **without** a go.d.plugin changelog.md, our PR #5638 line in the changelog would be like this:

Use [go.d.plugin v0.2.0](https://github.com/netdata/go.d.plugin/releases/tag/v0.2.0):  add x509check module, springboot2 metrics name fix [\#5638]

First link points to the release notes of 0.2.0, second one to the PR that introduced 0.2.0 into netdata.

With a changelog in go.d.plugin, the idea was to replace that first link, with a link to a header inside the changelog. Of course we could just keep the reference to the release notes and not have to change anything. Those notes are written by hand, the changelod is generated automatically.

**Comment by Wing924** [comment]
@cakrit 
I think users don't want to know the detail about go.d.plugin.
What they want to know is `XXX module become more awesome`.

Since go.d.plugin have lib and module repos, `go.d.plugin` repo's auto generated changelog contain many unused logs such as `update lib version`.
They're not meaningful for users.

**Comment by cakrit** [comment]
It's exactly the same for netdata. So we're really talking about improving our release notes, which are written by hand anyway. We'll ensure we do this better next time. I write the netdata release notes, @ilyam8 does the go.d.plugin ones right now. We'll discuss if we can update the v1.13 release notes, I don't think it's too late.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
