### ISSUE TITLE
netdata build error

### ISSUE THREAD

**Issue by defaultUser0816** [netdata/netdata#5649]
I got this returning from the netdata installer after installing all dependencies that are needed. I successfully installed netdata on another ubuntu 18.04. But on my database this error appears:

autoreconf: 'configure.ac' or 'configure.in' is required

It is a Ubuntu 18.04 Bionic like my testsystem. I can not explain this error or know how to handle that

it appears directly after start the installation 

Press ENTER to build and install netdata to your system > 

 --- Run autotools to configure the build environment --- 
[/root]# autoreconf -ivf 
autoreconf: 'configure.ac' or 'configure.in' is required
 FAILED

**Comment by cakrit** [comment]
How exactly are you installing it? `autoreconf -ivf` shoudln't be running in /root, but from within the  directory containing the source code.

**Comment by defaultUser0816** [comment]
Running it from source dir fixed it. My issue was that i automate the install by ansible. I forgot to tell ansible to change the dir before execution. Thanks a lot for fast answering :)
