### ISSUE TITLE
My Custom Module is not returning decimal number

### ISSUE THREAD

**Issue by fti-dpogra** [netdata/netdata#5655]
Hi Team Netdata,

As per your all helpful guidance i  created a python module which is displaying over My dashboard. 

But now issue is that, is only returns integer instead of any decimal number.

Please suggest me what can i do now: 

Below is example of my code:
_________________________________________________________________
CHARTS = {
    'motion_tracker': {
        'options': [None, 'Video Analysis Graph', 'Motion Detection', 'Video Analysis', 'motion_tracker', 'line'],
        'lines': [
            #['motion_tracker', 'motion tracking', 'incremental', '100']
            ['motion_tracker']
        ]
    }
}

class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.random = SystemRandom()

    @staticmethod
    def check():
        return True

    def get_data(self):
        data = dict()
       
        data.setdefault('motion_tracker', 4.56)

        #data['motion_tracker'] = 90.78

        return data

**Comment by ilyam8** [comment]
I am certain i answered to this question in another issue

But still

https://docs.netdata.cloud/collectors/plugins.d/#data-collection

>  If you want to push fractional values, multiply this value by 100 or 1000 and set the DIMENSION divider to 1000

^^

**Comment by fti-dpogra** [comment]
> I am certain i answered to this question in another issue
> 
> But still
> 
> https://docs.netdata.cloud/collectors/plugins.d/#data-collection
> 
> > If you want to push fractional values, multiply this value by 1000 and set the DIMENSION divider to 1000
> 
> ^^

Yes you answered
Thank you!
