### ISSUE TITLE
disk in raid1 array missing from netdada

### ISSUE THREAD

**Issue by camjesus2** [netdata/netdata#5658]
Hi!
I have a server with an mdadm raid1 array (with sda and sdb). On it I have an ext4 (on /), a btrfs (on /mnt/btrfs) and swap partitions.
The issue is that sda shows up on netdata (v1.12.2-46-nightly) as expected, but sdb doesn't at all.  It does show up in http://netdata.server/api/v1/charts though. All mount points show up as expected.
I've seen similar issues reported (#2830 and #448 for example), but I don't think these apply to this case.
Any clues?
And, last but not least, thanks for an amazing product.
Best regards

**Comment by cakrit** [comment]
Please paste the section of the dashboard with all the disks and then a screenshot showing the list of disks you have. If you don't want to put the screenshot here, export the dashboard and email it to info@netdata.cloud so we can take a look at it. Reading #2830, it may be that it does show up, but not the way you expected.

**Comment by camjesus2** [comment]
Thanks for taking the time to look into this, and yes, "as expected" is
probably the keyword here.
To add a little more entropy: I'm using elasticsearch (+logstash +kibana)
for long-term storage of netdata's data... And there, I can see sdb,
Actually the data from sda and sdb is similar (again, as expected since
it's a raid1)

Anyway, let's see if this is what you asked for.
1)
[image: image.png]
2) 10:37-#fdisk -l
Disk /dev/sda: 136.8 GiB, 146815733760 bytes, 286749480 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x7b17baec

Device     Boot Start       End   Sectors   Size Id Type
/dev/sda1  *     2048 286748671 286746624 136.7G fd Linux raid autodetect


Disk /dev/sdb: 136.8 GiB, 146815733760 bytes, 286749480 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xa12e5a83

Device     Boot Start       End   Sectors   Size Id Type
/dev/sdb1        2048 286748671 286746624 136.7G fd Linux raid autodetect


Disk /dev/md0: 136.6 GiB, 146680053760 bytes, 286484480 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x7ea95560

Device     Boot     Start       End   Sectors   Size Id Type
/dev/md0p1 *         2048  35352575  35350528  16.9G 83 Linux
/dev/md0p2      269699281 286471079  16771799     8G  5 Extended
/dev/md0p3       35352576 269699071 234346496 111.8G 83 Linux
/dev/md0p5      269699283 286471079  16771797     8G 82 Linux swap / Solaris


Best regards

Chris Akritidis <notifications@github.com> escreveu no dia segunda,
18/03/2019 à(s) 10:04:

**Comment by cakrit** [comment]
I said the same thing twice in my last comment. Ok, so we want:
 - Paste the section of the `/api/v1/charts` JSON with all the disks showing.
 - Show a screenshot of all the disks (we need to see the right menu and least and hopefully a few chart names) OR email us an export of your dashboard (top bar, you'll see the button to export).

**Comment by camjesus2** [comment]
Right. Here it goes. Snapshot as attachement :
1) "disk_avgsz.md0": {

			"id": "disk_avgsz.md0",
			"name": "disk_avgsz.md0",
			"type": "disk_avgsz",
			"family": "md0",
			"context": "disk.avgsz",
			"title": "Average Completed I/O Operation Bandwidth (disk_avgsz.md0)",
			"priority": 2006,
			"plugin": "proc.plugin",
			"module": "/proc/diskstats",
			"enabled": true,
			"units": "KiB/operation",
			"data_url": "/api/v1/data?chart=disk_avgsz.md0",
			"chart_type": "area",
			"duration": 30520,
			"first_entry": 1552886142,
			"last_entry": 1552916662,
			"update_every": 2,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		},
		"disk_svctm.sdb": 		{
			"id": "disk_svctm.sdb",
			"name": "disk_svctm.system",
			"type": "disk_svctm",
			"family": "system",
			"context": "disk.svctm",
			"title": "Average Service Time (disk_svctm.system)",
			"priority": 2007,
			"plugin": "proc.plugin",
			"module": "/proc/diskstats",
			"enabled": true,
			"units": "milliseconds/operation",
			"data_url": "/api/v1/data?chart=disk_svctm.system",
			"chart_type": "line",
			"duration": 30520,
			"first_entry": 1552886142,
			"last_entry": 1552916662,
			"update_every": 2,
			"dimensions": {
				"svctm": { "name": "svctm" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		},
		"disk_avgsz.sdb": 		{
			"id": "disk_avgsz.sdb",
			"name": "disk_avgsz.system",
			"type": "disk_avgsz",
			"family": "system",
			"context": "disk.avgsz",
			"title": "Average Completed I/O Operation Bandwidth (disk_avgsz.system)",
			"priority": 2006,
			"plugin": "proc.plugin",
			"module": "/proc/diskstats",
			"enabled": true,
			"units": "KiB/operation",
			"data_url": "/api/v1/data?chart=disk_avgsz.system",
			"chart_type": "area",
			"duration": 30520,
			"first_entry": 1552886142,
			"last_entry": 1552916662,
			"update_every": 2,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		},
		"disk_await.sdb": 		{
			"id": "disk_await.sdb",
			"name": "disk_await.system",
			"type": "disk_await",
			"family": "system",
			"context": "disk.await",
			"title": "Average Completed I/O Operation Time (disk_await.system)",
			"priority": 2005,
			"plugin": "proc.plugin",
			"module": "/proc/diskstats",
			"enabled": true,
			"units": "milliseconds/operation",
			"data_url": "/api/v1/data?chart=disk_await.system",
			"chart_type": "line",
			"duration": 30520,
			"first_entry": 1552886142,
			"last_entry": 1552916662,
			"update_every": 2,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		},
		"disk_qops.sdb": 		{
			"id": "disk_qops.sdb",
			"name": "disk_qops.system",
			"type": "disk_qops",
			"family": "system",
			"context": "disk.qops",
			"title": "Disk Current I/O Operations (disk_qops.system)",
			"priority": 2002,
			"plugin": "proc.plugin",
			"module": "/proc/diskstats",
			"enabled": true,
			"units": "operations",
			"data_url": "/api/v1/data?chart=disk_qops.system",
			"chart_type": "line",
			"duration": 30520,
			"first_entry": 1552886142,
			"last_entry": 1552916662,
			"update_every": 2,
			"dimensions": {
				"operations": { "name": "operations" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		},
		"disk_svctm.sda": 		{
			"id": "disk_svctm.sda",
			"name": "disk_svctm.sda",
			"type": "disk_svctm",
			"family": "sda",
			"context": "disk.svctm",
			"title": "Average Service Time (disk_svctm.sda)",
			"priority": 2007,
			"plugin": "proc.plugin",
			"module": "/proc/diskstats",
			"enabled": true,
			"units": "milliseconds/operation",
			"data_url": "/api/v1/data?chart=disk_svctm.sda",
			"chart_type": "line",
			"duration": 30520,
			"first_entry": 1552886142,
			"last_entry": 1552916662,
			"update_every": 2,
			"dimensions": {
				"svctm": { "name": "svctm" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		},
		"disk_avgsz.sda": 		{
			"id": "disk_avgsz.sda",
			"name": "disk_avgsz.sda",
			"type": "disk_avgsz",
			"family": "sda",
			"context": "disk.avgsz",
			"title": "Average Completed I/O Operation Bandwidth (disk_avgsz.sda)",
			"priority": 2006,
			"plugin": "proc.plugin",
			"module": "/proc/diskstats",
			"enabled": true,
			"units": "KiB/operation",
			"data_url": "/api/v1/data?chart=disk_avgsz.sda",
			"chart_type": "area",
			"duration": 30520,
			"first_entry": 1552886142,
			"last_entry": 1552916662,
			"update_every": 2,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		},
		"disk_await.sda": 		{
			"id": "disk_await.sda",
			"name": "disk_await.sda",
			"type": "disk_await",
			"family": "sda",
			"context": "disk.await",
			"title": "Average Completed I/O Operation Time (disk_await.sda)",
			"priority": 2005,
			"plugin": "proc.plugin",
			"module": "/proc/diskstats",
			"enabled": true,
			"units": "milliseconds/operation",
			"data_url": "/api/v1/data?chart=disk_await.sda",
			"chart_type": "line",
			"duration": 30520,
			"first_entry": 1552886142,
			"last_entry": 1552916662,
			"update_every": 2,
			"dimensions": {
				"reads": { "name": "reads" },
				"writes": { "name": "writes" }
			},
			"green": null,
			"red": null,
			"alarms": {

			}
		},


Chris Akritidis <notifications@github.com> escreveu no dia segunda,
18/03/2019 à(s) 11:04:

**Comment by cakrit** [comment]
I don't see the snapshot, but it's ok. Looking at the JSON, you probably see on the right menu something called `system`, which corresponds to your `sdb`. That is what's called a `family`.

```
			"id": "disk_qops.sdb",
			"name": "disk_qops.system",
			...
			"family": "system",
```

Your chart for `disk_qops` is probably called `disk_qops.system`, from the chart name, though I'm not 100% certain if use `name` or `id` in the UI. In almost all cases, the `id` and the `name` are identical, but not here. 

Your long-term storage obviously receives the `id`, which is why you see `sda` there. By reading #2830 again, I expect that your `mountinfo` will show something like this:
```
XX XX X:XX / system ... /dev/sdb ...
```

If all of the above are true, then this is the expected behaviour. Perhaps you'd be interested in seeing the disk identifiers instead, as in #5568?

**Comment by camjesus2** [comment]
ok....you are right about   disk_qops.system. I had noticed that in
elasticsearch, sda shows as "chart_name:disk_iotime.sda" and sdb shows as
"chart_name:disk_iotime.system "  just as you described. I was aware of
this, but wasn't sure this was "expected behaviour".
You are not right about mountinfo, because i have a Raid (#2830 didn't,
thats why I said it was a different case). with raid I get xx xx x:x / /
... /dev/md0p1. But that I can understand.

I will look into #5568. Having disks referenced by id would be great.

One last point is that on another machine I also have a Raid1 (no btrfs
though), but both disks show up as sda and sdb. That really messed me up.
Anyway, thanks for your help.

Best regards

Chris Akritidis <notifications@github.com> escreveu no dia segunda,
18/03/2019 à(s) 14:31:
