### ISSUE TITLE
format for module options in netdata.conf

### ISSUE THREAD

**Issue by jimidak** [netdata/netdata#5666]
unsure how to enable options for a plugin, in /etc/netdata/netdata.conf

-h on netdata plugins will give you syntax to adding to netdata.conf, and I see examples of uncommenting "update every ="  and  "command options =" for plugin sections in netdata.conf,
but what I can't find is how to add command options. Is it one per line, under "command options =", or all after "command options =", separated by commas? I've tried various ways, and restart netdata each time, but its not working.

**Comment by cakrit** [comment]
It's just as you would call it from the command line. 
There's an example at https://docs.netdata.cloud/collectors/freeipmi.plugin/#ignoring-specific-sensors

So `freeipmi.plugin opt1 arg1 opt2` in the command line becomes `command options = opt1 arg1 opt2` in the config file.

**Comment by maucosta80** [comment]
Good morning, I'm having trouble monitoring a specific item, the Vcenter alarms. These alarms point to disk, memory and network consumption of all Vms and all ESXis managed by Vcenter respond in a single oid. Can I insert this unique monitor for these items in netdata? If so, is there a model for what the configuration would look like? Tks

**Comment by ilyam8** [comment]
@maucosta80 what is `Vcenter respond in a single oid`. Are you using snmp or what?  :thinking:

**Comment by maucosta80** [comment]
Hi @ilyam8,  I use vcenter appliance 6.7. Snmp is configured and responding. Searching the vmware site I found the oid that reports all vcenter alarms.

**Comment by cakrit** [comment]
@maucosta80 please move the question on SNMP to a different issue. I am closing this one as we were able to help @jimidak with the command options (though in the wrong issue, the one that @ilyam8 referenced).
