### ISSUE TITLE
Get PID of running processes

### ISSUE THREAD

**Issue by EnzoAkira** [netdata/netdata#5668]
Hello everyone! I hope you have a great day.

##### Question summary
I am asking you about the processes that netdata collects.
I have a project to create several alerts and one of them will be to check if a process restarts unexpectedly, the way I thought was to check the PID of this process and compare it if it changes  as the last collection, I have already analyzed the variables available in the charts app.processes and system.active_processes and found no value relative to the PID of each process running at that time.
Is there a way to get the PID through other charts or editing the apps.plugin to provide that info?

Thanks in advance

##### OS / Environment
CentOS Linux 7.6.1810

##### Component Name
apps.plugin?!

**Comment by vlvkobal** [comment]
There isn't any information about PIDs in the charts.
You can configure an alarm for emptied groups (i.e. all processes from this group stopped/exited) or for the number of processes in the group. But to catch a restarted process, it should be stopped for more than one second.
