### ISSUE TITLE
Status of netdata/binary-packages

### ISSUE THREAD

**Issue by jweede** [netdata/netdata#5671]
It looks like https://github.com/netdata/binary-packages is no longer being published to in favor of https://github.com/netdata/netdata/releases . Probably for the better. Would it be good to add a notice to the old repo that it's deprecated?

If so I went ahead and made a PR for it:
 - https://github.com/netdata/binary-packages/pull/10

and an issue, just in case:

- https://github.com/netdata/binary-packages/issues/9

Let me know what you think. Thanks!

**Comment by paulfantom** [comment]
That repo is depracated in favor of public Google Cloud Storage bucket: https://console.cloud.google.com/storage/browser/netdata-nightlies

**Comment by jweede** [comment]
Thanks. Deprecation notice was accepted, so I'll go ahead and close this.

**Comment by Ferroin** [comment]
It might be worth explicitly [archiving the repository](https://help.github.com/en/articles/archiving-a-github-repository) in addition to the deprecation notice, as that will make it a lot more explicit that we have moved on in our packaging approach.

**Comment by cakrit** [comment]
Reopened it so we can archive it as per @ferroin 's suggestion, when we can. There's a script there as well, which @paulkatsoulakis will need to check (in case it's use in a pipeline somewhere).

**Comment by paulkatsoulakis** [comment]
I don't see that build script being used anywhere, we can follow https://help.github.com/en/articles/archiving-repositories to archive the repo.

I have added a comment already in README of the repo redirecting the users to the right resources and i have closed the 2 issues that were open with the necessary information for the users

**Comment by cakrit** [comment]
The repo was just archived.
