### ISSUE TITLE
Random Label or Text using sparkline value

### ISSUE THREAD

**Issue by fti-dpogra** [netdata/netdata#5672]
Hi All,

I created a custom dashboard with python module which is showing line charts, Gauge charts and sparkline charts too..

now sparkline chart is also showing a random integer number (like 1,2,3), Now i want to generate a text (in bootstrap button  or label format) which mentioned below.

>> If 1 is show a label/button: 'Normal'
>> If 2 is show a label/button: 'Failed'

Screenshot is also attached. 

Please suggest me where i have to make change?

Please review my case and let me know your feedback.

![Screenshot_2019-03-20 Get control of your Linux Servers Simple Effective Awesome ](https://user-images.githubusercontent.com/47653584/54660249-aa8b1880-4afb-11e9-9a85-9ce2c8ccf62e.png)

Thank You!

**Comment by cakrit** [comment]
We missed this one. @gmosx I think I saw another issue mentioning an attempt to do a "text chart" as well. Can you provide pointers on what would need to be done?

**Comment by ilyam8** [comment]
Hi @fti-dpogra 

> If 1 is show a label/button: 'Normal'
> If 2 is show a label/button: 'Failed'

You can use [badges](https://docs.netdata.cloud/web/api/badges/), badges support changing color based on value (1 - green, 2 - red).

> value_color=COLOR:null|COLOR<VALUE|COLOR>VALUE|COLOR>=VALUE|COLOR<=VALUE|...

I did something similar in the past - UPS battery usage custom dashboard (100+ UPSs, relatively big dashboard) using only badges. Changing color based on remaining % was very nice. :smile:
