### ISSUE TITLE
netdata-updater should remain after all installations

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5673]
netdata-updater.sh no longer remains in a netdata installation, unless auto-update is enabled. This is wrong, people should still be able to run the updater, even if they don't want it in cron. 
Just as with the uninstaller, the script should have never been removed. 

See where the proper place to leave the uninstaller is and put the updater there as well. (either under bin or under libexec/netdata, not sure).

The documentation should also be updated.

**Comment by cakrit** [comment]
We should also make the options consistent across all installations. kickstart.sh defaults to auto-update=true, but the installation from source defaults to auto-update=false.

**Comment by paulkatsoulakis** [comment]
> We should also make the options consistent across all installations. kickstart.sh defaults to auto-update=true, but the installation from source defaults to auto-update=false.

I could think of a reasoning behind it. People running the installer from the source may not be interested on an auto-updating installation (for example developers or testers).  Are you sure you want to align that?

**Comment by cakrit** [comment]
>  Are you sure you want to align that?

The alignment is is secondary, as long as we have documented how things work. Let's get the missing script installed, that's more important.
