### ISSUE TITLE
Use snmp to monitoring Vcenter

### ISSUE THREAD

**Issue by maucosta80** [netdata/netdata#5674]
Hi, I have a question about use snmp to monitoring Vcenter.
The vcenter has an alarm that informs both the esxi and vms connected to it. Example: esxi.host.intranet - memory usage
vm-test - disk IO
esxi2.host.intranet - cpu usage
I don't need to graph this information, I just need to know when I'm in trouble.
It's possible to use netdata to monitor at this level?.

Tks

**Comment by cakrit** [comment]
Charts will be created anyway. You'll need to
 - [Configure the SNMP plugin](https://docs.netdata.cloud/collectors/node.d.plugin/snmp/)
 - [Configure alarms](https://docs.netdata.cloud/health/)
 - [Configure notifications](https://docs.netdata.cloud/health/notifications/).

If you run into trouble, just ask questions in this issue and we'll help.

**Comment by ilyam8** [comment]
> I don't need to graph this information

That is actually a very nice thing to have, i would love to have it too. Currently collectors/db/dashboard are too highly coupled. Visualisation/dashboard should be an optional thing.

@maucosta80 	

could you please show snmp resp w/ and w/o alarms?
