### ISSUE TITLE
Errant netdata-updater logs on root "/" directory

### ISSUE THREAD

**Issue by BJWTech** [netdata/netdata#5679]
##### Bug report summary
When netdata-updater.sh is run from cron, on occasion it leaves it's log file on the root "/" directory. The files are named; netdata-updater.log.(some random 5 digit extension)

##### OS / Environment
Ubuntu 18.04.2 LTS Server AMD64
##### Netdata version (ouput of `netdata -V`)
netdata v1.13.0-8-nightly
##### Component Name
netdata-updater.sh 
##### Steps To Reproduce
Let cron run the updater
##### Expected behavior
netdata updates and cleans up it's log files

**Comment by cakrit** [comment]
That is only supposed to happen when the updater fails and the log is left on purpose, so that one can investigate what went wrong. Can you please check a couple of them and let us know what happened?

**Comment by BJWTech** [comment]
They all state that I am on the latest version. Would you like me to attach them here? I do not have access presently, but I could if it helps.

Thank you,

**Comment by BJWTech** [comment]
Here the output of the files;

-rw------- 1 root root 268 Mar 15 06:25 netdata-updater.log.4FfSaE

8a52ccc40811473cab27402a1493b8612dc4ba217cf7e3e2604a322fb1969782 *./netdata-latest.tar.gz
8a52ccc40811473cab27402a1493b8612dc4ba217cf7e3e2604a322fb1969782 *./netdata-v1.12.2-46-ga2992216.tar.gz
Fri Mar 15 06:25:39 PDT 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 268 Mar  6 06:25 netdata-updater.log.4Fki0k

e6611ef98a1458e043a966fd3e4d723b055f8a7373b4196ffb72219ef9a33b57 *./netdata-latest.tar.gz
e6611ef98a1458e043a966fd3e4d723b055f8a7373b4196ffb72219ef9a33b57 *./netdata-v1.12.2-11-g8ac48ec2.tar.gz
Wed Mar  6 06:25:14 PST 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 584 Feb 24 06:25 netdata-updater.log.5Mr6Rg

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   473  100   473    0     0    611      0 --:--:-- --:--:-- --:--:--   611
3a7c1c4adeaff3b5cbcf77aa1fc48e7acba24871175e05a1a1d352c94ad1de9b *./netdata-latest.tar.gz
3a7c1c4adeaff3b5cbcf77aa1fc48e7acba24871175e05a1a1d352c94ad1de9b *./netdata-v1.12.1-7-g86ed3869.tar.gz
Sun Feb 24 06:25:18 PST 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 268 Feb 28 06:25 netdata-updater.log.bCN5I7

69b49fbe15ed0cf709600a09f94ad8e52af8dd6ba17c0eb4bb9e3752e692c4f7 *./netdata-latest.tar.gz
69b49fbe15ed0cf709600a09f94ad8e52af8dd6ba17c0eb4bb9e3752e692c4f7 *./netdata-v1.12.1-21-g7297c45f.tar.gz
Thu Feb 28 06:25:23 PST 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 267 Mar  4 06:25 netdata-updater.log.BX8j4n

33859af0c22d229501e3226635043b5d92d1d761e1ba8d8e94fc806ff8dc551a *./netdata-latest.tar.gz
33859af0c22d229501e3226635043b5d92d1d761e1ba8d8e94fc806ff8dc551a *./netdata-v1.12.2-4-geccf0b9e.tar.gz
Mon Mar  4 06:25:24 PST 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 267 Mar  3 06:25 netdata-updater.log.C2PswX

33859af0c22d229501e3226635043b5d92d1d761e1ba8d8e94fc806ff8dc551a *./netdata-latest.tar.gz
33859af0c22d229501e3226635043b5d92d1d761e1ba8d8e94fc806ff8dc551a *./netdata-v1.12.2-4-geccf0b9e.tar.gz
Sun Mar  3 06:25:28 PST 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 267 Mar 21 06:25 netdata-updater.log.FEHTHM

a296f0a5391bbdbf125b5e1ba93f938a3db097ae5721456beba08223f3394025 *./netdata-latest.tar.gz
a296f0a5391bbdbf125b5e1ba93f938a3db097ae5721456beba08223f3394025 *./netdata-v1.13.0-8-g483cdc9d.tar.gz
Thu Mar 21 06:25:15 PDT 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 267 Mar 22 06:25 netdata-updater.log.fY9ujJ

a296f0a5391bbdbf125b5e1ba93f938a3db097ae5721456beba08223f3394025 *./netdata-latest.tar.gz
a296f0a5391bbdbf125b5e1ba93f938a3db097ae5721456beba08223f3394025 *./netdata-v1.13.0-8-g483cdc9d.tar.gz
Fri Mar 22 06:25:21 PDT 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 267 Mar 18 06:25 netdata-updater.log.gpCGnY

ead60ec5ecf2984af5e3ca9a931666e5b35582e5b29ccfd747b82136483ed915 *./netdata-latest.tar.gz
ead60ec5ecf2984af5e3ca9a931666e5b35582e5b29ccfd747b82136483ed915 *./netdata-v1.13.0-4-g53ebf33a.tar.gz
Mon Mar 18 06:25:18 PDT 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 267 Mar 20 06:25 netdata-updater.log.N7e4fD

a296f0a5391bbdbf125b5e1ba93f938a3db097ae5721456beba08223f3394025 *./netdata-latest.tar.gz
a296f0a5391bbdbf125b5e1ba93f938a3db097ae5721456beba08223f3394025 *./netdata-v1.13.0-8-g483cdc9d.tar.gz
Wed Mar 20 06:25:15 PDT 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 268 Mar  8 06:25 netdata-updater.log.NRo0Ky

9440a13278ea373f0ded044480a72b4f04fd5db6d451071149f0a932b251572c *./netdata-latest.tar.gz
9440a13278ea373f0ded044480a72b4f04fd5db6d451071149f0a932b251572c *./netdata-v1.12.2-18-gd66b45ac.tar.gz
Fri Mar  8 06:25:11 PST 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 268 Mar 16 06:25 netdata-updater.log.UFuS3h

8a52ccc40811473cab27402a1493b8612dc4ba217cf7e3e2604a322fb1969782 *./netdata-latest.tar.gz
8a52ccc40811473cab27402a1493b8612dc4ba217cf7e3e2604a322fb1969782 *./netdata-v1.12.2-46-ga2992216.tar.gz
Sat Mar 16 06:25:21 PDT 2019 : INFO:  Newest version is already installed

-rw------- 1 root root 268 Mar 13 06:25 netdata-updater.log.W2hLXw

422aeb40d98f8df223448cff6ec2300b2fb09d4249c7a894ec1ea53aae1e7ed4 *./netdata-latest.tar.gz
422aeb40d98f8df223448cff6ec2300b2fb09d4249c7a894ec1ea53aae1e7ed4 *./netdata-v1.12.2-34-gc2669a84.tar.gz
Wed Mar 13 06:25:22 PDT 2019 : INFO:  Newest version is already installed

**Comment by cakrit** [comment]
Thanks @BJWTech , the fix is in PR #5695.

**Comment by alokraj68** [comment]
This is happening to me in 1.28.0

**Comment by Danamir** [comment]
Same here.

The content of any logfile remaining :
```
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
```

**Comment by emanzx** [comment]
hi, would it possible to move the log file to somewhere better.. mine netdata updater keep failing causing the log keep growing untill all the space has been used. if it log in /var/log/netdata I would have set the quota so it wont grow more than hundred of megabytes.. i have many instances and now having problem and need  to disable all auto update..
