### ISSUE TITLE
push kickstart.sh to https://my-netdata.io/kickstart.sh

### ISSUE THREAD

**Issue by MichaelRiss** [netdata/netdata#5681]
##### Bug report summary
`packaging/installer/kickstart.sh` needs to be pushed to `https://my-netdata.io/kickstart.sh` to fix #5584 for users updating with `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait`

##### OS / Environment
Fedora 28 running plainly on a x86_64 machine

##### Netdata version (ouput of `netdata -V`)
netdata v1.12.2-46-nightly

##### Component Name
packaging/installer

##### Steps To Reproduce
`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait` still suffers from #5584
##### Expected behavior
`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait` should not suffer
 from #5584 anymore

**Comment by paulkatsoulakis** [comment]
Hello @MichaelRiss, excellent catch! 
Sorry for the inconvenience, indeed we seem to have missed it! 
It will be included asap

**Comment by cakrit** [comment]
This is something @ktsaou does, I notified him.
@paulkatsoulakis please add a check to the daily builds to verify that the kickstart.sh and kickstart-static64.sh md5sums are the same in the repo, packaging/installer/README.md and http://my-netdata.io
We have a travis test already for the first two, it runs even for PRs. The third one can't be tested for a PR though, my-netdata.io is updated manually as a second step. When we detect a discrepancy, see if travis can somehow notify @ktsaou that he needs to update the file.

**Comment by paulkatsoulakis** [comment]
This is fixed now and we also increased our monitoring capability so that we mitigate this in the future in a timely manner.
Moving forward we will definitely look into automating the whole process to avoid this ever happening in the future.

@MichaelRiss let us know with a new issue if you face any issue again.
