### ISSUE TITLE
Unable to access dashboard - new install

### ISSUE THREAD

**Issue by pigsfoot** [netdata/netdata#5688]
HI,

I have just installed Netdata onto an existing working server which is running a e-marketing platform called MailWizz.

Installation was run via the single like install command, everything seems OK and the service is running, The problem is i can not access the dashboard, all i get is a page timed out error.

The server is dedicated server at AWS with a static IP. I have opened a port for 19999 and all outgoing ports are open.

The URL i am using to access the server is http://my.IP/19999

I have attached my error and access log files if that helps.

I have tried the suggestions in the "Getting Started" documentation and everything seems OK.

Any suggestions please.

[access.log](https://github.com/netdata/netdata/files/2999183/access.log)
[error.log](https://github.com/netdata/netdata/files/2999184/error.log)

**Comment by pigsfoot** [comment]
Quick update, just installed NetData onto another server that i have which is a std Ubuntu server at AWS running a simple Apache web server and everything si working fine. 

Therefore i woudl presume the install on the previous server has something to do with a possible conflict of the application ( Mailwizz ) that server is running. Trouble is, i have no idea where to start looking.

Thanks

**Comment by ilyam8** [comment]
hi @pigsfoot 	

> 2019-03-23 09:07:49: netdata INFO  : WEB_SERVER[static2] : POLLFD: LISTENER: listening on 'tcp:0.0.0.0:19999'
2019-03-23 09:07:49: netdata INFO  : WEB_SERVER[static2] : POLLFD: LISTENER: listening on 'tcp:[::]:19999'

> all i get is a page timed out error.
> I have opened a port for 19999 and all outgoing ports are open.

i would start from checking iptables rules

**Comment by pigsfoot** [comment]
Thanks for the pointer, I'm not really sure what I'm looking for. This is the output of iptables -L

`ubuntu@ip-172-31-41-157:~$ sudo iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination
f2b-sshd   tcp  --  anywhere             anywhere             multiport dports ssh
fail2ban-VESTA  tcp  --  anywhere             anywhere             tcp dpt:8083
fail2ban-MAIL  tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission,2525,pop3,pop3s,imap2,imaps
fail2ban-FTP  tcp  --  anywhere             anywhere             tcp dpt:ftp
fail2ban-SSH  tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     all  --  ip-172-31-41-157.eu-west-2.compute.internal  anywhere
ACCEPT     all  --  localhost            anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             multiport dports http,https
ACCEPT     tcp  --  anywhere             anywhere             multiport dports ftp,12000:12100
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             multiport dports smtp,urd,submission,2525
ACCEPT     tcp  --  anywhere             anywhere             multiport dports pop3,pop3s
ACCEPT     tcp  --  anywhere             anywhere             multiport dports imap2,imaps
ACCEPT     tcp  --  anywhere             anywhere             multiport dports mysql,postgresql
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8083
ACCEPT     icmp --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain f2b-sshd (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain fail2ban-FTP (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-MAIL (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-SSH (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-VESTA (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain vesta (0 references)
target     prot opt source               destination
`

**Comment by ilyam8** [comment]
```
Chain INPUT (policy DROP)
target prot opt source destination
f2b-sshd tcp -- anywhere anywhere multiport dports ssh
fail2ban-VESTA tcp -- anywhere anywhere tcp dpt:8083
fail2ban-MAIL tcp -- anywhere anywhere multiport dports smtp,urd,submission,2525,pop3,pop3s,imap2,imaps
fail2ban-FTP tcp -- anywhere anywhere tcp dpt:ftp
fail2ban-SSH tcp -- anywhere anywhere tcp dpt:ssh
ACCEPT all -- anywhere anywhere state RELATED,ESTABLISHED
ACCEPT all -- ip-172-31-41-157.eu-west-2.compute.internal anywhere
ACCEPT all -- localhost anywhere
ACCEPT tcp -- anywhere anywhere tcp dpt:ssh
ACCEPT tcp -- anywhere anywhere multiport dports http,https
ACCEPT tcp -- anywhere anywhere multiport dports ftp,12000:12100
ACCEPT udp -- anywhere anywhere udp dpt:domain
ACCEPT tcp -- anywhere anywhere tcp dpt:domain
ACCEPT tcp -- anywhere anywhere multiport dports smtp,urd,submission,2525
ACCEPT tcp -- anywhere anywhere multiport dports pop3,pop3s
ACCEPT tcp -- anywhere anywhere multiport dports imap2,imaps
ACCEPT tcp -- anywhere anywhere multiport dports mysql,postgresql
ACCEPT tcp -- anywhere anywhere tcp dpt:8083
ACCEPT icmp -- anywhere anywhere
```

> Chain INPUT (policy DROP)

you need to add permit iptables rule (tcp dport 19999)

___

you can access netdata dashboard via ssh tunnel btw 

from your local pc

```
ssh -L 127.0.0.1:19998:127.0.0.1:19999 user@ip-address
```

check `http://127.0.0.1:19998` in your browser

**Comment by ilyam8** [comment]
@pigsfoot 

i see you have publcic IP addess in the hostname, i have to warn that it is not safe to post your iptables rules in a public resource :smile:

**Comment by pigsfoot** [comment]
Hi @ilyam8 , thanks for the pointer re the IP Address, however panic not... the address shown is an internal IP range used at AWS and is not publicly accessible.

Re the local access... i have SSH directly to the server via Putty from a windows computer in my office via secured SSH rules at AWS which also require ppk keys for authentication, therefore i'm not sure how i would run that command. 

I command using port 19998 would also need additional FW rules opening which i am reluctant to do, please see the next comment.

The problem has to be local to that server as i have successfully added Netdata to 4 other servers on the same platform ( all @ AWS ) via the single line install ( same way as this server ), each server using the same FW rule and they are all working fine.

Finally, you mention adding a permit rule to my iptable, if the script worked on all other servers fine surely that woudl be done automatically on this server ?

I have also just ran the install again and watched everything, no errors but still not working :-(

Thanks for your help so far.

**Comment by ilyam8** [comment]
> thanks for the pointer re the IP Address, however panic not...

oh, man, i didn't notice the address is from private range lol, i feel ashamed :smile:

> Finally, you mention adding a permit rule to my iptable, if the script worked on all other servers fine surely that woudl be done automatically on this server ?

netdata installer doesn't add any iptables rules, you have to do it on your own
___

that is your iptables rules (INPUT chain)

```
Chain INPUT (policy DROP)
target prot opt source destination
f2b-sshd tcp -- anywhere anywhere multiport dports ssh
fail2ban-VESTA tcp -- anywhere anywhere tcp dpt:8083
fail2ban-MAIL tcp -- anywhere anywhere multiport dports smtp,urd,submission,2525,pop3,pop3s,imap2,imaps
fail2ban-FTP tcp -- anywhere anywhere tcp dpt:ftp
fail2ban-SSH tcp -- anywhere anywhere tcp dpt:ssh
ACCEPT all -- anywhere anywhere state RELATED,ESTABLISHED
ACCEPT all -- ip-172-31-41-157.eu-west-2.compute.internal anywhere
ACCEPT all -- localhost anywhere
ACCEPT tcp -- anywhere anywhere tcp dpt:ssh
ACCEPT tcp -- anywhere anywhere multiport dports http,https
ACCEPT tcp -- anywhere anywhere multiport dports ftp,12000:12100
ACCEPT udp -- anywhere anywhere udp dpt:domain
ACCEPT tcp -- anywhere anywhere tcp dpt:domain
ACCEPT tcp -- anywhere anywhere multiport dports smtp,urd,submission,2525
ACCEPT tcp -- anywhere anywhere multiport dports pop3,pop3s
ACCEPT tcp -- anywhere anywhere multiport dports imap2,imaps
ACCEPT tcp -- anywhere anywhere multiport dports mysql,postgresql
ACCEPT tcp -- anywhere anywhere tcp dpt:8083
ACCEPT icmp -- anywhere anywhere
```

> Chain INPUT (policy DROP)

that means that default last (implicit) rule is `deny all`, so if there is no rule that allows tcp to netdata port (19999) you will have

> all i get is a page timed out error.


> The server is dedicated server at AWS with a static IP.

i assume that you can configure firewall rules via GUI or something

**Comment by pigsfoot** [comment]
Thanks for the help, much appreciated. Adding firewall / iptable rules is beyond my skills unfortunately. I have done some googling and i think i know what to add but as this is a live server can i check first please.

Is the command i need to add

`sudo iptables -A INPUT -p tcp --dport 199999 -j ACCEPT`

Thanks

**Comment by ilyam8** [comment]
`sudo iptables -A INPUT -p tcp --dport 19999 -m comment --comment netdata`

**Comment by pigsfoot** [comment]
Hi Thanks for all your help, i tried the above and it didnt work. I google a littl emor eon iptables and have eventually used thsi command to remove the drop command

`sudo iptables -P INPUT ACCEPT`

The server is protected by a dedicated firewall we have at AWS so it shouldn't be a problem. The only issue i have now is if i reboot the server the above is replaced by the original DROP command.

I have tried `sudo iptables-save` but it doesn't seem to work.

Thanks

**Comment by ilyam8** [comment]
Well, you need to find where these rules are loaded from.

> dedicated server at AWS

I guess they have some gui to manage your server, it might have `firewall` section or something. Dunno.

___

`iptables-save` just dumps all rules, it is not like you are saving changes.
