### ISSUE TITLE
feature cgroups plugin: make containers priority user configurable

### ISSUE THREAD

**Issue by Thatdarkone** [netdata/netdata#5697]
Is there a way to move containers menu entries on the dashboard to the top ? Perhaps under "system overview" menu .
Reason why i want to do this is because our motivation on using netdata is for it's containers monitoring capability.  So we want to see containers listed at the top before everything else.

**Comment by cakrit** [comment]
In the `netdata.conf` sections under `# per chart configuration`, uncomment the `priority` lines of the charts you want to see at the top and decrease the number you see there. Lower priority means that the chart appears earlier.

**Comment by cakrit** [comment]
@Thatdarkone you'll also need to restart netdata for the configuration to take effect and don't forget to refresh your browser. Please close this if you don't need any more help. I created #5698 to improve the docs.

**Comment by ilyam8** [comment]
i think this won't work, he need to redefine start priority for the cgroup plugin (not per chart), which is not supported.

**Comment by cmuzyunda** [comment]
Thanks @cakrit 
It works somehow 👍  . 
Example below in netdata.conf.

[cgroup_container1.cpu]
         priority = 1900


[cgroup_container2.cpu]
         priority = 1900

However i wish it was more flexible like @ilyam8 said , if could be defined for the cgroup plugin instead.

**Comment by Thatdarkone** [comment]
Thanks @cakrit
It works somehow 👍 .
Example below in netdata.conf.

[cgroup_container1.cpu]
priority = 1000

[cgroup_container2.cpu]
priority = 1000

However i wish it was more flexible like @ilyam8 said , if could be defined for the cgroup plugin instead.

**Comment by ilyam8** [comment]
@Thatdarkone check the fix

```
[plugin:cgroups]
        # cgroups plugin resource charts = yes
        # update every = 1
        # check for new cgroups every = 10
        containers priority = 1900

```

**Comment by Thatdarkone** [comment]
@ilyam8 

i have seen your PR with 3 commits but not sure which ones i should checkout to test this , and once checked out , i would need to run the netdata-installer.sh script i guessto update my instance.

**Comment by ilyam8** [comment]
1. `git clone http://github.com/ilyam8/netdata --branch cgroups_containers_priority --depth=100 netdata-test`
2. `cd netdata-test`
3. install

**Comment by Thatdarkone** [comment]
I can confirm your fix works @ilyam8 
Thanks for the quick turnaround.

**Comment by ilyam8** [comment]
i changed the title to more specific

**Comment by ilyam8** [comment]
don't forget back to master branch
