### ISSUE TITLE
netdata.cloud: cannot load netdata agents

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#5712]
##### Bug report summary

Just logged in by email to my account (costa@tsaousis.gr) and I got this:

![image](https://user-images.githubusercontent.com/2662304/54993951-ca26b300-4fcb-11e9-9e7a-03a22b043795.png)

What is strange is that it shows my name at the top right, but it should be showing my email address. Like it mixed my previous login (github), with the new one (email).

##### Netdata version (ouput of `netdata -V`)

```
# netdata -V
netdata v1.13.0-35-g51c75a78
```

**Comment by ktsaou** [comment]
This seems to be happening at 5% of the agents requests:

![image](https://user-images.githubusercontent.com/2662304/54994319-a7e16500-4fcc-11e9-90b6-b28c7df39d60.png)

https://frankfurt.my-netdata.io/#menu_netdata-cloud-pages_submenu_agents;

**Comment by ktsaou** [comment]
So, the question is:

> how is it possible for a dashboard to hit the agents URL and get back a 401?

It should not be possible under normal conditions, since the dashboard first checks that the users is logged in, and then it attempts to get the agents.

**Comment by gmosx** [comment]
Possibly related to an `emailauth` bug that was already resolved. Let me know if you can still reproduce this.

**Comment by vlvkobal** [comment]
@VLegakis, please close the issue if it's solved already.

**Comment by cakrit** [comment]
Solved long ago, forgotten.
