### ISSUE TITLE
Create custom gauge for disk space

### ISSUE THREAD

**Issue by mustafalani** [netdata/netdata#5715]
##### Question summary
Hi monitoring champions :)
Is it possible to do something similar to this?
![image](https://user-images.githubusercontent.com/16665383/55023503-3b328e80-4ffd-11e9-82b7-557659aa7bfa.png)

I need to show the total disk space and the used / available space.
I tried setting `data-common-max` and `data-common-min` as suggested in  [https://github.com/netdata/netdata/issues/2687]( Question #2687) but couldn't get it to work as I want.

Thanks for the great work!

**Comment by cakrit** [comment]
Almost. Look [here](https://docs.netdata.cloud/web/gui/custom/) it says the following:

You should also look at the **[custom dashboard template](https://my-netdata.io/dashboard.html)**, that contains samples of all supported charts. The code is [here](https://github.com/netdata/netdata/blob/master/web/gui/dashboard.html). 

You want the d3pie charts at the end.
