### ISSUE TITLE
E-mail notification only send for test alarms

### ISSUE THREAD

**Issue by binaryplease** [netdata/netdata#5721]
I configured netdata to send email notifications. These are send correctly when using the test script in the documentation as netdata user:
```
/usr/libexec/netdata/plugins.d/alarm-notify.sh test 
# OR
/usr/libexec/netdata/plugins.d/alarm-notify.sh test sysadmin
```
But the mails are **not** send on real alarms even though these are triggered correctly.
E.g. I stressed the cpu for 10 minutes on my host. I see the alarm notification in the browser, after a while it goes from "warning" to "critical" but I don't get any email.

I also have setup a custom notification via a script that sends SMS and have the same problem with it: Test alarm works perfectly, but no real alarm notification is send, so it seems not to be just related to mail.

I also tried for other alarms than cpu stress, same problem.

##### Question summary
How can I find the error in my config? Why does the test script not work like the real alarms? (that should be the purpouse of a test, right?)

##### OS / Environment

I'm running Ubuntu 16.04 and netdata version 3068d75 installed without container (native install)

##### Expected results
Email notification send on alarms.

**Comment by cakrit** [comment]
I have never seen this before. I can only think of permission/ownership issues (i.e. running it from the command line as root, while netdata executes it as netdata).

Please check `error.log` for lines containing `alarm-notify.sh` and put here what you see.

**Comment by binaryplease** [comment]
This is not a permissions error, I think I found the cause though. I ran the `alarm-notify.sh` command as netdata, not as root.

The error.log complained about a missing "default account". Upon further investigating, it seems when I run the `alarm-notify` script manually, the sendmail config is read from `/var/lib/netdata/.msmtprc`, the home of netdata. When the script for the alarm is triggered by a real alarm it reads from `/etc/msmtprc` instead. 

I don't know why this is or if the behaviour is expected. In case this is considered a bug it can probably be fixed easily, otherwise you might want to consider documenting it, took me quite a while to figure out this one. The purpouse of the test-script should be to be as close to the "real thing" as possible I guess, including the configurations used. Otherwise it might give wrong information that later results in missing emails.

I solved the problem for me by moving the config to `/etc/msmtprc`.

**Comment by cakrit** [comment]
But isn't your netdata running as user `netdata` as well? 
@Ferroin do you have any ideas on why this might happen?

**Comment by Ferroin** [comment]
There are two possibilities I can think of:

1. Netdata isn't running as the `netdata` user, but as `root` instead.
2. The MSMTP version of `sendmail` is using some environment variable to determine whether to load the user config file or not, and that environment variable isn't set when Netdata invokes `alarm-notify.sh`.  `$HOME` is the first possibility that comes to mind for this one.

**Comment by olegsidokhmetov** [comment]
Hello!

Someone can show me the correct *.conf file with email notification?

**Comment by k3s4** [comment]
@binaryplease I have similar problem msmtp works fine also alarm-notify.sh sending test alert normally but when I create 'real life' alert then I have following error in logfiles:

2019-11-28 16:09:32: alarm-notify.sh: ERROR: failed to send email notification for: SELKS disk_space._.out_of_disk_space_time is CLEAR to '*mymail*@gmail.com' with error code 78.

have you found solution for that? I have also try to copy .msmtprc to /etc but didn't work.

**Comment by k3s4** [comment]
> @binaryplease I have similar problem msmtp works fine also alarm-notify.sh sending test alert normally but when I create 'real life' alert then I have following error in logfiles:
> 
> 2019-11-28 16:09:32: alarm-notify.sh: ERROR: failed to send email notification for: SELKS disk_space._.out_of_disk_space_time is CLEAR to '_mymail_@gmail.com' with error code 78.
> 
> have you found solution for that? I have also try to copy .msmtprc to /etc but didn't work.

fixed.. problem was with msmtp and chmod for .msmtprc file should be 0644 instead of 0600 like it is described in documentation here - https://docs.netdata.cloud/health/notifications/email/ ...

**Comment by binaryplease** [comment]
@k3s4 Thanks, that worked!

**Comment by emperinter** [comment]
It worked on my service,I wonder why it can not be solved at original file place ?
