### ISSUE TITLE
memory growth in netdata

### ISSUE THREAD

**Issue by hamzash9500** [netdata/netdata#5723]
Hi All,
we suffer from memory growth in netdata salve on all servers, this issue happened after upgrading netdata from version 1.10 to version 1.12 .
in the following  chart display growth in Ram.
![Screenshot_٢٠١٩٠٣٢٧_١٨٠١٤٠](https://user-images.githubusercontent.com/34510063/55109121-ba978f00-50dd-11e9-8109-6923d12d44dc.png)

current netdata version : netdata v1.12.0-rc3-23-g780fd60
information of server :
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"

stream.conf on slave netdata
--------------------------------------------------------------------------------
[stream]
    # Enable this on slaves, to have them send metrics.
    enabled = yes
    destination = [ip of netdata master]:19999
    api key = *******************************
    timeout seconds = 60
    default port = 19999
    send charts matching = apps.cpu apps.cpu_system apps.cpu_user apps.files apps.lreads apps.lwrites apps.mem apps.preads
    buffer size bytes = 1048576
    reconnect delay seconds = 5
    initial clock resync iterations = 60
[API_KEY]
    enabled = no
    allow from = *
    default history = 3600
    default memory mode = ram
    health enabled by default = auto
    default postpone alarms on connect seconds = 60
    multiple connections = allow

[MACHINE_GUID]
     enabled = no
    allow from = *
    history = 3600
    memory mode = save
    health enabled = yes
    postpone alarms on connect seconds = 60
    multiple connections = allow

netdata.conf on netdata salve
------------------------------------------------------------------------------
[global]
     memory mode = none
[health]
        enabled = no

 stream.conf on netdata master :
---------------------------------------------------------------------------------
[stream]
    # Enable this on slaves, to have them send metrics.
    enabled = no
    destination =
    # The API_KEY to use (as the sender)
    api key =
    # The timeout to connect and send metrics
    timeout seconds = 60
    # If the destination line above does not specify a port, use this
    default port = 19999
    send charts matching = *
    buffer size bytes = 1048576
    reconnect delay seconds = 5
    # Sync the clock of the charts for that many iterations, when starting.
    initial clock resync iterations = 60
[*****************************************]
    # Default settings for this API key
    # You can disable the API key, by setting this to: no
    # The default (for unknown API keys) is: no
    enabled = yes
    allow from = *
    default history = 3600
    default memory mode = ram
    health enabled by default = auto
    # postpone alarms for a short period after the sender is connected
    default postpone alarms on connect seconds = 60
    multiple connections = allow
    [api key ]
    enabled = yes
    allow from = *
    # The number of entries in the database
    history = 3600
    # The memory mode of the database: save | map | ram | none
    memory mode = save
    # Health / alarms control: yes | no | auto
    health enabled = yes
    # postpone alarms when the sender connects
    postpone alarms on connect seconds = 60
     multiple connections = allow

netdata.conf on netdata master 
-----------------------------------------------------------------------------------
[global]
	# process scheduling policy = keep
	# OOM score = keep
	# glibc malloc arena max for plugins = 1
	# glibc malloc arena max for netdata = 1
	# hostname = hs-netdata-i-01c790a7be2154f2
	# history = 3996
	# update every = 1
	# config directory = /etc/netdata
	# stock config directory = /usr/lib/netdata/conf.d
	# log directory = /var/log/netdata
	# web files directory = /usr/share/netdata/web
	# cache directory = /var/cache/netdata
	# lib directory = /var/lib/netdata
	# home directory = /var/cache/netdata
	# plugins directory = "/usr/libexec/netdata/plugins.d" "/etc/netdata/custom-plugins.d"
	# memory mode = save
	# host access prefix = 
	# memory deduplication (ksm) = yes
	# TZ environment variable = :/etc/localtime
	# timezone = Etc/UTC
	# debug flags = 0x0000000000000000
	# debug log = /var/log/netdata/debug.log
	# error log = /var/log/netdata/error.log
	# access log = /var/log/netdata/access.log
	# errors flood protection period = 1200
	# errors to trigger flood protection = 200
	# run as user = netdata
	# pthread stack size = 8388608
	# cleanup obsolete charts after seconds = 3600
	# gap when lost iterations above = 1
	# cleanup orphan hosts after seconds = 3600
	# delete obsolete charts files = yes
	# delete orphan hosts files = yes

[web]
	# ses max window = 15
	# des max window = 15
	# mode = static-threaded
	# listen backlog = 4096
	# default port = 19999
	# bind to = *
	# web files owner = netdata
	# web files group = netdata
	# disconnect idle clients after seconds = 60
	# timeout for first request = 60
	# accept a streaming request every seconds = 0
	# respect do not track policy = no
	# x-frame-options response header = 
	# allow connections from = localhost *
	# allow dashboard from = localhost *
	# allow badges from = *
	# allow streaming from = *
	# allow netdata.conf from = localhost fd* 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
	# allow management from = localhost
	# enable gzip compression = yes
	# gzip compression strategy = default
	# gzip compression level = 3
	# web server threads = 2
	# web server max sockets = 512

[plugins]
	# PATH environment variable = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
	# PYTHONPATH environment variable = 
	# proc = yes
	# diskspace = yes
	# cgroups = yes
	# tc = yes
	# idlejitter = yes
	# enable running new plugins = yes
	# check for new plugins every = 60
	# node.d = yes
	# python.d = yes
	# apps = yes
	# charts.d = yes
	# fping = yes

[health]
	# enabled = yes
	# in memory max health log entries = 1000
	# script to execute on alarm = /usr/libexec/netdata/plugins.d/alarm-notify.sh
	# stock health configuration directory = /usr/lib/netdata/conf.d/health.d
	# health configuration directory = /etc/netdata/health.d
	# run at least every seconds = 10
	# postpone alarms during hibernation for seconds = 60
	# rotate log every lines = 2000

**Comment by ilyam8** [comment]
Hi @hamzash9500 

> from version 1.10 to version 1.12

Please update to the latest and check if the problem is there.
