### ISSUE TITLE
packages installer failed

### ISSUE THREAD

**Issue by sukonkan** [netdata/netdata#5727]
The experimental packages installer failed.

On Screen Show
curl -Ss 'https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all
curl: (6) Could not resolve host: raw.githubusercontent.com
![snip_25620328115229](https://user-images.githubusercontent.com/977155/55131157-0c78fd00-5150-11e9-8a7a-d4e9f9f1e4f9.png)

**Comment by maxtruxa** [comment]
This is a problem with your local installation not the installer script. Your client's DNS isn't working.

See
```
ping raw.githubusercontent.com
```

or really just anything
```
ping google.com
nslookup google.com
```
