### ISSUE TITLE
Design k8s collector endpoint autodiscovery

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5729]
We need to have a way for our collectors to discover automatically the ephemeral endpoints in a k8s cluster.

**Comment by cakrit** [comment]
I went through https://docs.datadoghq.com/agent/autodiscovery and it's very involved. 
We should probably do something like what the [Prometheus Operator](https://github.com/coreos/prometheus-operator) does.  

This will need a lot more research, I will be going through the details of what the Prometheus operator does and how it does it. We could possibly also utilize the knowledge netdata already has of the containers (cgroups plugin), perhaps extending it a bit to give us some more info on the endpoints, but I'm not sure.

**Comment by cakrit** [comment]
Will be designed along #6317 and #6295

**Comment by cakrit** [comment]
We removed the dependency from configuration management, which is a large project. Moving along with this, just for k8s

**Comment by cakrit** [comment]
Goals:
- [ ] Study datadog and prometheus
- [ ] Test polling
- [ ] Test event handling
- [ ] Define parameters that can be provided
- [ ] Define config templates for the collectors
- [ ] Discuss architecture (who is doing the discovery and how is the collector informed?)

**Comment by cakrit** [comment]
Deliverable: 

Design document.

**Comment by cakrit** [comment]
A very rough draft, for findings this far...

## Non-prometheus endpoints

Whether we’ll actually have an endpoint like httpd `server-status` available is up to the k8s deployment. Neither the `stable/nginx-ingress` nor the `stable/lamp` helm charts handle server-status requests OOB. I even messed around a bit, trying to figure out how to change that config, but I gave up. 

However, one thing is certain: these type of endpoints require information from k8s `services`. This is very simple, a `kubectl get services` command shows what we need and of course we can easily turn it into a query to get just the external-ip and the port we want.

## `/metrics` endpoints

For these, our only chance of getting some info is to query the pods. The type of info we want to be able to retrieve from k8s is:
- IP & port
- Selection criteria, so we can tell what it is we’re monitoring there (of course Prometheus doesn’t care about what is being monitored, but we and Datadog do).

`kubectl get pods --all-namespaces -o json` gives the pod info from outside the cluster (of course we can do similar queries from inside). Looking around the output from a test cluster in GCS, the container IP and name (which will probably be our OOB selection criterion) are easy to get, they exist everywhere. The port that we can access to get to the `/metrics` endpoint is a completely different story. Some promising information to get to a URL comes from any existing liveness probes, but as you'll see below, we can't trust them.

`kubectl get pods --all-namespaces -o json | jq -r '.items[] | "\(.status.podIP)\t" + (.spec.containers[]? | "\(.name)\t\(.livenessProbe.httpGet.port)\t\(.livenessProbe.httpGet.scheme)\t\(.livenessProbe.httpGet.path)")'`
Gives the following:
```
10.8.1.2    datadog-agent    null    null    null
10.8.2.2    datadog-agent    null    null    null
10.8.0.2    datadog-agent    null    null    null
10.8.1.4    nginx-ingress-controller    10254    HTTP    /healthz
10.8.1.3    nginx-ingress-default-backend    8080    HTTP    /healthz
10.8.0.7    httpd    null    null    null
10.8.0.7    php    null    null    null
10.8.0.7    mysql    null    null    null
10.8.2.8    netdata    http    HTTP    /api/v1/info
10.128.0.28    netdata    http    HTTP    /api/v1/info
10.128.0.29    netdata    http    HTTP    /api/v1/info
10.128.0.30    netdata    http    HTTP    /api/v1/info
10.8.2.7    event-exporter    null    null    null
10.8.2.7    prometheus-to-sd-exporter    null    null    null
10.8.1.5    fluentd-gcp-scaler    null    null    null
10.128.0.30    fluentd-gcp    null    null    null
10.128.0.30    prometheus-to-sd-exporter    null    null    null
10.128.0.29    fluentd-gcp    null    null    null
10.128.0.29    prometheus-to-sd-exporter    null    null    null
10.128.0.28    fluentd-gcp    null    null    null
10.128.0.28    prometheus-to-sd-exporter    null    null    null
10.8.0.4    heapster    8082    HTTP    /healthz
10.8.0.4    prom-to-sd    null    null    null
10.8.0.4    heapster-nanny    null    null    null
10.8.1.6    kubedns    10054    HTTP    /healthcheck/kubedns
10.8.1.6    dnsmasq    10054    HTTP    /healthcheck/dnsmasq
10.8.1.6    sidecar    10054    HTTP    /metrics
10.8.1.6    prometheus-to-sd    null    null    null
10.8.2.3    kubedns    10054    HTTP    /healthcheck/kubedns
10.8.2.3    dnsmasq    10054    HTTP    /healthcheck/dnsmasq
10.8.2.3    sidecar    10054    HTTP    /metrics
10.8.2.3    prometheus-to-sd    null    null    null
10.8.2.6    autoscaler    null    null    null
10.128.0.28    kube-proxy    null    null    null
10.128.0.29    kube-proxy    null    null    null
10.128.0.30    kube-proxy    null    null    null
10.8.1.9    default-http-backend    8080    HTTP    /healthz
10.8.1.7    metrics-server    null    null    null
10.8.1.7    metrics-server-nanny    null    null    null
10.128.0.29    prometheus-to-sd    null    null    null
10.128.0.28    prometheus-to-sd    null    null    null
10.128.0.30    prometheus-to-sd    null    null    null
10.128.0.30    prometheus-to-sd-new-model    null    null    null
10.8.2.4    metadata-agent    null    null    null
10.8.1.8    tiller    44135    HTTP    /liveness
```

k`ubectl exec netdata-slave-mdbsh curl http://10.8.1.4:10254/metrics` -> Gives results for nginx
But http://10.8.1.3:8080/metrics doesn’t return anything, that’s just the default backend (it's actually where we would expect to get `server-status` from).

The following URLs were also tested and work:
http://10.8.2.3:10054/metrics kubedns
http://10.8.1.6:10054/metrics sidecar(?)
http://10.8.1.8:44135/metrics tiller
http://10.8.0.4:8082/metrics heapster (scraper)

The interesting thing is they all seem to work when we query from ANY netdata pod.

**BUT** look at `kube-proxy`. No port there. I used the one we have in our go.d.plugin (10249), but connection is refused when we use the pod IP shown here. We can only get http://localhost:10249/metrics from each slave, as we already do in our go.d collector.
Tried the same for `fluentd`. 24231 is the port, found it only by doing a ps. The port DOES exist in the “command” node of the json. We can see the same for `event-exporter`, the source in the command and the ps output are the only places where we see port 80. When we do `curl http://10.8.2.7/metrics` using that port, it works. 

The big question is if there is a better way to get the ports of those /metrics endpoints, since the pods info is missing some things. It looks like the people at datadog gave up, and they’ve essentially hard-coded the ports in their default config files. See the `auto_conf.yaml` files in this page:  https://docs.datadoghq.com/agent/autodiscovery/auto_conf/

It looks like the Prometheus people gave up too. In https://sysdig.com/blog/kubernetes-monitoring-prometheus/ it’s clear that you need to change your deployment AND configure prometheus, just to get traefik working, though it already exposes its port. 

What we'll do is TBD, we will most likely have both a hard-coded config (with just the IP received from the autodiscovery service) and a config that expects a port from the service

## Watching for events

There's no documentation on how to subscribe to the k8s events API, because you don't. You just import some of their libraries in your go code and start watching (with permissions etc of course, but still). See [an example](https://github.com/bitnami-labs/kubewatch/blob/master/pkg/controller/controller.go), or the [prometheus code](https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/operator.go#L253) (watchers are [here](https://github.com/coreos/prometheus-operator/blob/master/pkg/listwatch/listwatch.go)

Prometheus is funny, you have to tell it everything, before you start monitoring. You even [change your freaking service deployment](https://sysdig.com/blog/kubernetes-monitoring-prometheus/)!!!

We won’t be doing that of course. Datadog is much smarter, it’s OOB configs are much closer to what we want. https://docs.datadoghq.com/agent/autodiscovery and the info underneath are close to what Netdata will be like.

**Comment by prologic** [comment]
> The port that we can access to get to the /metrics endpoint is a completely different story. Some promising information to get to a URL comes from any existing liveness probes, but as you'll see below, we can't trust them.

The [Default Port Allccations](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) will help here; we can codify this into whatever we build and periodically update it as we discover new entries. It at least gives us a starting point of 'standard" and "allocated" ports that various software are using to publish their `/metrics` endpoints on.

**Comment by prologic** [comment]
> What we'll do is TBD, we will most likely have both a hard-coded config (with just the IP received from the autodiscovery service) and a config that expects a port from the service

We _could_ probably periodically scan all pods and look for `/metrics` endpoints on any port that behaves like HTTP? +hard-coded ports mapping for "known things" +configs might be a good balance?

**Comment by prologic** [comment]
> Prometheus is funny, you have to tell it everything, before you start monitoring. You even change your freaking service deployment!!!

Well... You _can_ actually use their "SD" (_Service Discovery_) stuff; but I agree if you don't spend the time doing this properly its a PITA as you have to reconfigure and restart :/

There are a bunch of [x_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file) and there is even an [`kubernetes_sd_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config)

**Comment by cakrit** [comment]
> Well... You _can_ actually use their "SD" (_Service Discovery_) stuff; but I agree if you don't spend the time doing this properly its a PITA as you have to reconfigure and restart :/
> 
> There are a bunch of [x_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file) and there is even an [`kubernetes_sd_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config)

I see the following:
> The pod role discovers all pods and exposes their containers as targets. For each declared port of a container, a single target is generated. If a container has no specified ports, a port-free target per container is created for manually adding a port via relabeling.

"specified ports" - specified where? From what I saw, you need to configure your deployment to specify the port yourself. Very few deployments have it. Our target is to require **zero configuration**. Only in exceptional cases should a user have to configure anything at all, anywhere. Just install netdata on your cluster via our helm chart and see charts for all the services and pods we support.

**Comment by cakrit** [comment]
> We _could_ probably periodically scan all pods and look for `/metrics` endpoints on any port that behaves like HTTP? +hard-coded ports mapping for "known things" +configs might be a good balance?

I expect you don't suggest scanning all ports? Is there a way I can see all the reachable pod ports in my cluster? I haven't found one...

**Comment by cakrit** [comment]
> The [Default Port Allccations](https://github.com/prometheus/prometheus/wiki/Default-port-allocations) will help here; we can codify this into whatever we build and periodically update it as we discover new entries. It at least gives us a starting point of 'standard" and "allocated" ports that various software are using to publish their `/metrics` endpoints on.

This is very promising, but we cant just rely on that. If you see the examples that I tested for in our test infra, I wouldn't have detected a single one of them, if I just went by that list. Still, it's a great list to have and use. I expect we'll use it just to hard-code the possible ports where we'd expect a monitored pod to be. At least that will be my suggestion, based on the mess I've seen. At some point in the future, I believe that the `/metrics` port will become a standard option in the pod definition.

**Comment by cakrit** [comment]
Let me summarize the actionable findings here, so we can have a discussion on it next week and I can close the design document. 

## Autodiscovery collector configurations

Ideally, any collector that retrieves metrics via TCP needs to be able to accept jobs defined more or less as follows:

```
[job base name]
  *Something that says that this job requires autodiscovery, or applies to k8s*
  [k8s selection criteria section]
     [Just do what Datadog does](https://docs.datadoghq.com/agent/autodiscovery/ad_identifiers/).
     We could later allow users to specify labels instead of, or in addition to those ad_identifiers
  [dynamic endpoint section]
     Let's just stick with endpoints that only accept a host ip or name as a parameter, called %%HOST%%
     e.g. 
     - https://%HOST%%:[hard-coded-port]/metrics 
     - https://%HOST%%:[hard-coded-port]/server-status?all
     - mysql %%HOST%%  mysql port
```

So these are just templates, that need the %%HOST%% to be specified one or more times. For each autodetected host, we'll create an instance of that job. 

We will define the hard-coded ports based on the default port allocations that @prologic mentioned and our own experience (see note at the end though)

All of our go.d collectors and the internal, prometheus collector will certainly need this extension, hopefully we can do it for python.d collectors as well. 

### So are we staying with hard-coded ports?

Using these ports means that we won't require users to configure something special in their infrastructure. They can always modify our job config of course, to give it a different port. So we can go live like this and we'll be detecting a ton of endpoints, with zero configuration.

We should be wary though, that we may at some point need to extend this mechanism so that a port can be retrieved from kubernetes:
 - See the example for the `.livenessProbe.httpGet.port` [above](https://github.com/netdata/netdata/issues/5729#issuecomment-586300772), that ended up giving some valid ports.  
  - Prometheus allows users to specify the montoring port in their container/k8s configuration
  - We could have a special label for that port, like Datadog does for the k8s selection criteria
  - We could wait for standardization
  - Or investigate further, for other/better options

## Autodiscovery process

In k8s, a go.d process that always runs (go.d.plugin?) does the following:
   - Reads all the config files that have jobs like the one in the previous section.
   - Subscribes for service and pod create/update/stop events (very generic, we need to go deeper into those events, to see exactly what we need). 
   - In the beginning retrieves any active services and pods, to attempt to find matches to the selection criteria in each config's [k8s selection criteria section].  Attempting to find matches also happens as a response to events. 
   - For every matched new pod or service, it passes the %%HOST%% with a start message to the appropriate collector, so that the collector can start polling. 
   - For every matched removed pod or service, it passes the %%HOST%% with a stop message, to tell the collector to stop.

Controlling the internal prometheus collector that will be built later will require that collector to listen to a port for such messages. Communication with the go.d plugin will probably be simpler, but we should really try to make this generic, so that the python.d plugin can also be used in the same manner.

**Comment by cakrit** [comment]
@ilyam8 @amoss @cosmix @ncmans @knatsakis please check this and comment. I'll set up a call to finalize the discussion.

**Comment by amoss** [comment]
One option for port discovery might be: https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by ilyam8** [comment]
To get better understanding what is k8s, how it works, how to install/remove/update an app, etc i decided to go through deploying an app process from the beginning.

It is hard to contribute to autodiscovery topic without the good undertanding of the subject.

My practice:

K8s environments:
 - local (installed using minikube tool)
 - testing kubernetes project on GCP

My app:

It is multicontainer app https://github.com/ilyam8/multi-docker. It includes `nginx`, `postgres` and `redis` services (services we want to monitor).

On every update travis publishes images to [my dockerbub]( https://hub.docker.com/u/ilyam8).

I use those images to deploy the app on k8s. I dont use helm or any other thing, plain config files only.

**Comment by ilyam8** [comment]
> We need to have a way for our collectors to discover automatically the ephemeral endpoints in a k8s cluster.

I am pretty sure we need to use api server watch endpoints, we can get all `added/modified/deleted` events from there.


Datadog uses undocumented kubelet `/pods` endpoint which returns node pods data. The response is huge (thousands of lines) and it is quite expensive to parse it on a regular bases.

What is good that **apiserver returns all historical data on connection**. It means there is no way to miss a pod.


Example: namespace with nginx/redis/http deployments.


```sh
ilya@cloudshell:~$ ./watchpods -n netdata-auto-discovery
INFO[0000] POD EVENT                                     event=ADDED name=httpd-7d58d5569c-64rxk namespace=netdata-auto-discovery node=gke-standard-cluster-2-default-pool-86353fdd-b7
zb
INFO[0000] POD CONTAINER                                 image=httpd name=httpd ports="[{ 0 80 TCP }]"
INFO[0000] POD EVENT                                     event=ADDED name=redis-74bb8bb895-ckqrr namespace=netdata-auto-discovery node=gke-standard-cluster-2-default-pool-86353fdd-t4
5s
INFO[0000] POD CONTAINER                                 image=redis name=redis ports="[{ 0 6379 TCP }]"
INFO[0000] POD EVENT                                     event=ADDED name=nginx-54f648575c-b9887 namespace=netdata-auto-discovery node=gke-standard-cluster-2-default-pool-86353fdd-t4
5s
INFO[0000] POD CONTAINER                                 image=nginx name=nginx ports="[{ 0 80 TCP }]"
INFO[0000] POD EVENT                                     event=ADDED name=httpd-7d58d5569c-8smz8 namespace=netdata-auto-discovery node=gke-standard-cluster-2-default-pool-86353fdd-49
4b
INFO[0000] POD CONTAINER                                 image=httpd name=httpd ports="[{ 0 80 TCP }]"
INFO[0000] POD EVENT                                     event=ADDED name=redis-74bb8bb895-qbz9q namespace=netdata-auto-discovery node=gke-standard-cluster-2-default-pool-86353fdd-49
4b
INFO[0000] POD CONTAINER                                 image=redis name=redis ports="[{ 0 6379 TCP }]"
INFO[0000] POD EVENT                                     event=ADDED name=redis-74bb8bb895-6jlrq namespace=netdata-auto-discovery node=gke-standard-cluster-2-default-pool-86353fdd-b7
zb
INFO[0000] POD CONTAINER                                 image=redis name=redis ports="[{ 0 6379 TCP }]"
INFO[0000] POD EVENT                                     event=ADDED name=httpd-7d58d5569c-c6qsw namespace=netdata-auto-discovery node=gke-standard-cluster-2-default-pool-86353fdd-t4
5s
INFO[0000] POD CONTAINER                                 image=httpd name=httpd ports="[{ 0 80 TCP }]"
```

**Comment by amoss** [comment]
Summary of today's meeting:

* Where should the auto-discovery execute?
  1. A single copy for the cluster running as a separate deployment.
  2. One copy communicating with the netdata master in the cluster.
  3. A copy inside each container (or pod) running netdata.

There are few disadvantages to running multiple copies as the auto-discovery subscribes to relevant events and then performs light-weight processing in response to each event - there is no polling of end-points in the cluster. Running a single / few copies of the auto-discovery makes communication with the Netdata agents more complex and limits our options for communication (i.e. TCP would work but IPC methods would not).

* How should the auto-discovery present changes to the collector orchestrator? 
  1. Directly (using a shared volume to write a config file and then signalling)
  2. Via the netdata agent (using a new endpoint and then allowing the agent to handle comms to the orchestrator and reload).

The first option would work, but not allow any further progress. The second option puts more intelligence in the Agent but allows a development path beyond a simple file-based reload mechanism towards the Configuration Manager.

* What kind of communication mechanism should we use?
  1. Write job / config details to a file and then send a reload command to the plugin (probably via a signal). On reload the collector would compare its current configuration to the new one and work out which changes are necessary to align (e.g. launch new jobs).
  2. A shared bus.

The discussion around the shared bus briefly covered technology: we are using MQTT throughout the product and it would offer a simple solution in this case as we already have mosquitto in the Agent). Websockets and encryption would not be required for on-node communication. Authentication was not discussed but could be a requirement (i.e. prevent injection of rogue jobs.

The next part of the discussion covered potential commands that could be sent on the bus. These were initial ideas as we require some analysis of what value they would provide:
  1. Reload
  2. Sending config (i.e. avoiding the shared files)
  3. Splitting the config, e.g. AddJob, RemoveJob, QueryCurrentJobs.

**Comment by cosmix** [comment]
> Where should the auto-discovery execute?

1. Why can't we embed the auto-discovery functionality within the dæmon?
2. I would have the auto-discovery run within the master _pod_ (be it within the netdata dæmon process, or a separate process as shown above)

> How should the auto-discovery present changes to the collector orchestrator?

A shared volume is an easy way to do it, especially if the two containers are deployed in the same pod. I would probably opt for the API approach.

> What kind of communication mechanism should we use?

Although I'm wary of the 'shared bus' approach as it can get needlessly complex, I definitely think we need to find something that's more sophisticated than the 'file + signal' approach. Not sure MQTT would work in this case, but I'm interested in hearing more about the idea.

**Comment by cakrit** [comment]
> 1. Why can't we embed the auto-discovery functionality within the dæmon?

It needs to be written in `go` , to be able to register to the required API.

> 2. I would have the auto-discovery run within the master _pod_ (be it within the netdata dæmon process, or a separate process as shown above)

We didn't see anything wrong with any of the options. Perhaps running only on the master would reduce the netdata footprint a bit, that's a benefit, at the cost of some additional complexity on which slave to notify, based on the node (still a simple matter). Any other reasons for/against the options @ilyam8?

**Comment by ilyam8** [comment]
Having autodiscoverer running within the master pod or even outside of it (why should it be running within the master) is a valid option too. I have nothing against it.

However i have no preferences atm and this is the goal of the current sprint - study operators (custom resource controllers) and find different ways we can implement it.

**Comment by amoss** [comment]
Removing the old milestone as this is not what @ilyam8 was working on in the current sprint (#8481). This issue will be worked on in the upcoming sprint (for v1.22) and the outcome will be:
* Proposals for possible auto-discovery architectures: which parts of the service are situated in deployments, pods or containers etc.
* Beautiful diagrams explaining different approaches.
* Code to show extraction of images from the pod binding messages, and simple heuristics to estimate service from image name.
