### ISSUE TITLE
adding dimension to the chart dynamically (not showing from the first return data)

### ISSUE THREAD

**Issue by lwchan2k1** [netdata/netdata#5730]
Hi,

I am developing custom plugin for python.d, it works except when I add the dimension to the chart dynamically and also set the value in the same _get_data(), the new dimension get added, but value does not get set.

Is that the correct behaviour?

Thanks

**Comment by ilyam8** [comment]
Hi @lwchan2k1 	

Simple example: https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/example/example.chart.py

**Comment by lwchan2k1** [comment]
That's what I was doing similar to the example, but value did not get set for the first time when dim is added, next _get_data() called and value is set correctly (dim is already added)

**Comment by ilyam8** [comment]
show the code

**Comment by ilyam8** [comment]
> but value did not get set for the first time when dim is added

ok, i read more carefully, i think netdata need 2 data collections to show the value

**Comment by ilyam8** [comment]
> ok, i read more carefully, i think netdata needs 2 data collections to show the value

Actually nice question. I think netdata should show `absolute` value on the first data collection.

@vlvkobal

**Comment by lwchan2k1** [comment]
@ilyam8 that's what I observed, just want to confirm if this is how it works. And based on your comments, it will take the 2 data collections to show and initial value on will be ignored.

**Comment by ilyam8** [comment]
Yes, it will the 2 data collections. This is a bug, first value shouldn't be ignored for absolute dimension.

**Comment by ilyam8** [comment]
That is a minor issue, the fix is using the [`store_first` CHART option](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#chart) (see options).
