### ISSUE TITLE
netdata-updater fails only from cron

### ISSUE THREAD

**Issue by johnramsden** [netdata/netdata#5731]
##### Bug report summary

On two different machines that have been set up identically, `netdata-updater` failed for me. What's strange is when I go and try running the script in cron manually it complete successfully and says everything is up to date.

I'm unable to replicate the failing script manually.

##### OS / Environment

Ubuntu 18.04, source install.

##### Netdata version (ouput of `netdata -V`)

netdata v1.13.0-34-nightly

##### Component Name

netdata-installer.sh

##### Expected behavior

I would expect the update script to run the same through cron and manually, I couldn't figure out what the difference is other than the fact that it's in "headless" mode.

---

`/etc/netdata/.environment`:

```
# Created by installer
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
CFLAGS="-O2"
NETDATA_PREFIX=""
NETDATA_CONFIGURE_OPTIONS=""
NETDATA_ADDED_TO_GROUPS=" adm proxy"
INSTALL_UID="0"
REINSTALL_COMMAND="./netdata-installer.sh --auto-update "
RELEASE_CHANNEL="nightly"
# This value is meant to be populated by autoupdater (if enabled)
NETDATA_TARBALL_CHECKSUM="bf374ea41530e781ab61448fe17c99701fbd6693397ccf38713f0099e258dae5"
```

Error message received from cron:

```
 --- Run autotools to configure the build environment --- 
[/tmp/netdata-updater-iiHsP2/netdata-v1.13.0-41-g793e03f0]# autoreconf -ivf 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:680: error: required file 'collectors/xenstat.plugin/Makefile.in' not found
autoreconf: automake failed with exit status: 1
 FAILED   
```

**Comment by ilyam8** [comment]
fixed in https://github.com/netdata/netdata/pull/5728
