### ISSUE TITLE
Custom Dashboard with local dashboard.js

### ISSUE THREAD

**Issue by weagertron** [netdata/netdata#5735]
I am creating a custom dashboard for monitoring various devices that are using NetData. My setup consists of one main web server application running in NodeJs with React that **does not** have NetData installed which then connects to other devices that **are** running NetData.

In the past I have added the dashboard.js file into the HTML pages on my web server with the following:
`<script type="text/javascript" src="http://XXX.XXX.XXX.XXX:19999/dashboard.js"></script>`

However, I do not want to retrieve the dashboard.js file from one of the remote devices. Instead, I would rather take a copy of the dashboard.js file and reference it locally on the web server like this:
`<script type="text/javascript" src="./js/dashboard.js"></script>`

But whenever I try to do this it does not work and I receive jQuery errors like the following:
`Uncaught SyntaxError: Unexpected token <`
and
`Uncaught ReferenceError: jQuery is not defined`

 I have tried to manually add jQuery to my application too but this also did not work.

If I do reference the dashboard.js file using the IP of one of the devices running NetData then it works flawlessly but referencing a local dashboard.js file fails.

Is it possible to achieve this? Are there any extra steps or files I need to get this working? The main reason I need the dashboard.js file is so I can render the graphs on my custom dashboard.

Any help will be greatly appreciated.

**Comment by weagertron** [comment]
I did some more digging into the issue and managed to work out the solution.

After examining the files included when referencing a remote dashboard.js file in Chrome developer tools I was able to see that I was missing some files and folders. 

I required the 'lib', 'css' folders with their contents and also I had to grab the dashboard.css file to get the styling correct.

After adding these files and folders it now works fine.

**Comment by Mikez12** [comment]
> I did some more digging into the issue and managed to work out the solution.
> 
> After examining the files included when referencing a remote dashboard.js file in Chrome developer tools I was able to see that I was missing some files and folders.
> 
> I required the 'lib', 'css' folders with their contents and also I had to grab the dashboard.css file to get the styling correct.
> 
> After adding these files and folders it now works fine.

I have the same issue but by adding the folders lib and css I get another error saying 
`Access to XMLHttpRequest at 'file:///Users/micbook/Desktop/newDashboard/lib/bootstrap-3.3.7.min.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`
How do you solved this?

**Comment by cakrit** [comment]
I expect you could copy the contents of those directories to the host serving the custom dashboard, so you can server them from there, instead of the remote host. @gmosx is there anything more clever that could be done?

**Comment by weagertron** [comment]
Strange. I didn't have any issues with CORS when I added those files.

I am using React for my project which I generated using create-react-app so it created most of the file structure for me. The main difference I can see between mine and your structure is that I placed the 'lib' and 'css' directories within my 'public' directory that sits next to my index.html file.

Not sure if this will help you but its just something that I can spot at first glance.

**Comment by cakrit** [comment]
> The main difference I can see between mine and your structure is that I placed the 'lib' and 'css' directories within my 'public' directory that sits next to my index.html file

Yep, that's what I said also (but you made it clearer). @Mikez12 is obviously fetching them from the host containing the data, which is why he gets the CORS error.

**Comment by weagertron** [comment]
> > The main difference I can see between mine and your structure is that I placed the 'lib' and 'css' directories within my 'public' directory that sits next to my index.html file
> 
> Yep, that's what I said also (but you made it clearer). @Mikez12 is obviously fetching them from the host containing the data, which is why he gets the CORS error.

Great minds! I only saw your reply after I had posted mine otherwise I wouldn't of stepped in! Hopefully that will resolve your issue @Mikez12
