### ISSUE TITLE
Monitoring output file

### ISSUE THREAD

**Issue by Matthewhazi** [netdata/netdata#5752]
Hello,
I installed Netdata to get data regarding  (CPU, Memory, Temp, Disks etc ..).
I run data training model on edge devices with resnet 18/50 and at the end of the training I have to get some file that contains the data I mentioned when running.
Is there such a possibility?

OS: Ubuntu 18.04

**Comment by ilyam8** [comment]
Hi @Matthewhazi 	

I see:
 - we have some trainings
 - after the training there is a file with some content
 - we need to look for specific content in the file and visualize what?

Could you describe in detail algorithm how it supposed to work?

**Comment by Matthewhazi** [comment]
I work in an AI startup, I run our Resnet 18/50 models on edge devices (SBC, NUC etc ..).
While running the models, I want to test several parameters for benchmark such as (CPU, MEMORY, DISKS etc...).

**Comment by ilyam8** [comment]
Ok, it seems you need to write [custom module](https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-write-a-new-module).

**Comment by cakrit** [comment]
But if I understand correctly that all you need is the values of some charts while your tests were running, then you just want to export the data netdata already collects for that timeframe, is that correct? If that's all you want, you can look at the [API](https://docs.netdata.cloud/web/api/) to get data in JSON, CSV, Prometheus format etc.
