### ISSUE TITLE
can use netdata for social network analytics in backend ?

### ISSUE THREAD

**Issue by mob2005** [netdata/netdata#5754]
##### Question summary
can use netdata for social media analytics in backend ? and how it's help

**Comment by cakrit** [comment]
You can use it to monitor anything really. If there's a publicly available API on a well known platform that you use, you could provide information on what needs to be monitored and we can write the collector ourselves, to distribute it with netdata. However,  if you have custom things you want monitored (e.g. a proprietary schema in a DB you have), then you would need to write a custom metrics collector yourself. People here can definitely help you with that too. Can you provide more information?

**Comment by mob2005** [comment]
for example i use twitter api for get realtime tweets , i want trace over some kind of words in every tweet ( eg list of 2000 word ) and show count of words over time . or want to find trend between all emojis used in tweet's , can i use netdata for such purpose, is it correct use case

**Comment by cakrit** [comment]
I like this idea. The words will be configurable in the collector's .conf file. 
Of course we'll need a separate collector for each social network you'd want to monitor. @ilyam8 what do you think?

**Comment by ilyam8** [comment]
@mob2005 i think you need to parse a tweet and push raw data to some database.

> show count of words over time . or want to find trend between all emojis used in tweet's , can i use netdata for such purpose

All this is achieved by doing quries to the database, the logic shouldn't be hardcoded in the collector.

I did something similar using elasticsearh/kibana in the past (iptv analyzing)

**Comment by mob2005** [comment]
i this example , first data recived by crawlers  normalized and save to db ,  and then we send every word , hashtag or ...  to collector of netdata  for have realtime chart of number of occurrenc per secound in tweets
is it possible

**Comment by ilyam8** [comment]
ok, a collector output is charts (create, update)

example

create:
```
CHART netdata.runtime_example '' 'Execution time for example' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2019-04-02 09:38:10: python.d INFO: plugin[main] : example[example] : started in thread
2019-04-02 09:38:10: python.d DEBUG: example[example] : started, update frequency: 1
CHART example.random '' 'A random number' 'random number' 'random' 'random' line 90000 1 '' 'python.d.plugin' 'example'
DIMENSION 'random1' 'random1' absolute 1 1 ''
```

update:
```
BEGIN example.random 0
SET 'random1' = 89
END

BEGIN netdata.runtime_example 0
SET run_time = 0
END

2019-04-02 09:38:11: python.d DEBUG: example[example] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
BEGIN example.random 1001110
SET 'random1' = 67
END

BEGIN netdata.runtime_example 1001110
SET run_time = 0
END

2019-04-02 09:38:12: python.d DEBUG: example[example] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
BEGIN example.random 998838
SET 'random1' = 85
END

BEGIN netdata.runtime_example 998838
SET run_time = 0
END
```

>  realtime chart of number of occurrenc per secound in tweets

Netdata will show anything you send to it. But you need to implement all logic inside the _collector_.

**Comment by ilyam8** [comment]
> I did something similar using elasticsearh/kibana in the past (iptv analyzing)

I parsed radius accounting (igmp groups acc start/stop), and stored parsed data in elasticsearch

data fields: `userMAC`, `switchIP`, `switchPort`, `igmpGroup`, `startTime`, `durTime`.

Having such raw data i could create a lot of different graphs and analyze iptv in detail. Ex.: top (5, 10, ...) iptv channels (by watching duration, by number of people watching the channel) across all region, across city, groups of cities, same  info but in different day time (morning, noon, evening) and for different time periods and **much more**.

So if you need some comprehensive analyze netdata is not the way to go.

**Comment by cakrit** [comment]
Let's take just the example of words and emojis. I would create a chart counting occurrences of words and another of emojis, with the dimensions (words or emojis) defined in the configuration. 

I also don't see why we would want an intermediate DB. If we can get from the API the tweets since the last poll, we can look for the configured words ourselves. Of course we would never look in the past, so we start measuring a word from the moment it's added to the configuration.

**Comment by ilyam8** [comment]
i think this is make sense when you are analyzing a lot of data (thousands of users, thousands of posts), that is why he is talking about the _crawlers_.

**Comment by ilyam8** [comment]
@mob2005 am i right? to analyze `social network` you need to analyze/process (ten of) thousands of posts. It may be not achievable on a per second bases because of [rate limitting](https://developer.twitter.com/en/docs/basics/rate-limiting.html), network delays, etc.

Anyway i don't see this as a netdata module. @Ferroin 	what do you think?

**Comment by cakrit** [comment]
For twitter, we'd use [this](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/powertrack-stream). Max 60 requests/min, but with a timeout of 30 sec. So the collector would need to be a bit smart. 

Basically, I don't see the point of adding another layer, if what you want is real time monitoring. If it's really `analytics` and the OP says (i.e. historical trends and ad-hoc queries), then netdata is clearly not the way to do. But I really like the idea of configuring a collector to search for keywords and charting that in real time.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
