### ISSUE TITLE
Block-scoped declarations outside strict mode

### ISSUE THREAD

**Issue by Vftdan** [netdata/netdata#5755]
##### Bug report summary

'let' and 'const' should not be used outside strict mode to be back-compatible with some older browsers.

##### OS / Environment

- Android 6.0.1
- Samsung Internet 4.0.20-58

##### Component Name

web

##### Steps To Reproduce

View any website with netdata gui with the described environment.

##### Expected behavior

All scripts work.

##### Possible solutions

- Add "'use strict'" at the beginning of scripts
- Replace 'let' and 'const' by 'var'

**Comment by jacekkolasa** [comment]
not relevant anymore in new dashboard
