### ISSUE TITLE
"Healthy" entrypoint for HTTP-interface

### ISSUE THREAD

**Issue by n0guest** [netdata/netdata#5764]
Hello.

Is there a way to check, that netdata isn't only "up & running", but also "working ok"? For example, Prometheus has "/-/healthy" and Grafana has "/api/health" entrypoints.

After checking [current API](https://registry.my-netdata.io/swagger/#/) we tried to use "/api/v1/info" for such purpose. But it works until you have Netdata as a slave with "memory mode = none". In last case any request to "/api/v1/.+" will end only with:

> This host does not maintain a database

Is there any other URI's which can be used like a  "health check"?

PS: I guess it will be useful to have something like "/api/vX/healthy". It could be used for healthchecks from Kubernetes/Docker/Consul/etc.

**Comment by cakrit** [comment]
Perfect timing @n0guest! @varyumin is adding liveness and readiness probes on `/api/v1/info` to our Kubernetes helmchart, in [a PR](https://github.com/netdata/helmchart/pull/11). Based on what you wrote, it may not work very well. I will look into making the response better.

**Comment by n0guest** [comment]
@cakrit, isn't it a little early to close this issue? My initial question was about "healthcheck" entrypoint, but right now only "wrong answer in memory mode" is fixed.

PS: If somewhere there is another issue or PR with work on this matter, please, share a link or a number. I'd like to subscribe to follow the progress.

**Comment by cakrit** [comment]
With this PR, you no longer get

**Comment by n0guest** [comment]
> If there are any suggestions, happy to add some additional checks, so I reopened it to discuss.

I guess you should consider two areas:

initialization is complete and we are ready to process requests
required resources are available
The first one mostly about multi-threaded apps where HTTP-interfaces could be available before some important background threads were finished. The second is about the availability of critical resources, such as a database or allocated memory/structures/connections.

BTW, here is what happens in Grafana and Prometheus:

https://github.com/grafana/grafana/blob/67cbc7d4cf135c3ed2fa5a47278c6be6e7653e7f/pkg/api/http_server.go#L261
https://github.com/prometheus/prometheus/blob/81c4248081d51d628916cb214ae7e9bceb17be94/web/web.go#L334
In Grafana we at least can see some database check, when Prometheus just answers with HTTP/200. So, if we assume, that it's normal just to answer HTTP/200, then probably you could add a simple "stub" like "/api/healthy". It could help to avoid a future situation where many users have installations with "/api/info" as healthcheck and they have to update their configuration when Netdata's team would have a clear understanding "what to check to ensure we're healthy".

PS: I know, this is a stretch, but it's best that I could think of.
