### ISSUE TITLE
Add execution of updated kickstart scripts to the CI pipeline

### ISSUE THREAD

**Issue by TheRyanHowell** [netdata/netdata#5769]
##### Feature idea summary
The installer hosted at `https://my-netdata.io/kickstart-static64.sh` should be installer from the latest stable build.

##### Expected behavior
It looks like the version of the installer hosted at `https://my-netdata.io/kickstart-static64.sh` is based upon master branch, this should likely instead be the latest stable release which has been fully tested?

I also filed an issue where the installer seems broken on master, this change would have helped this not reach end-users expecting a stable installer/build. https://github.com/netdata/netdata/issues/5768

**Comment by cakrit** [comment]
> this should likely instead be the latest stable release which has been fully tested

There's actually a manual step to update kickstart scripts, we just failed to test properly.

**Comment by cakrit** [comment]
Modified the subject, we'll add the tests to the pipeline.
