### ISSUE TITLE
 disable automatically upgrade

### ISSUE THREAD

**Issue by hamzash9500** [netdata/netdata#5772]
Hi all,
How i can disable automatically upgrade for netdata .
 
I installed Netdata with a binary package
using this command:   bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)

Thanks advance.

**Comment by cakrit** [comment]
Remove `netdata-updater` from `/etc/cron.daily`. 
When you next update manually and if you use kickstart.sh to do it, add `--no-updates` when executing `kickstart.sh` script. The option is in the `advanced use dropdown of the command, in https://docs.netdata.cloud/packaging/installer/#one-line-installation

**Comment by hamzash9500** [comment]
Thanks for your help,
when execute kickstart.sh and i added --no-updates as:
sh netdata-v1.12.0-rc0-64-g8c09913c-x86_64-20181219-052839-firehol.gz.run --no-updates
I have got :[ Unrecognized flag : --no-updates]
