### ISSUE TITLE
Netdata version 

### ISSUE THREAD

**Issue by hamzash9500** [netdata/netdata#5774]
how i can know netdata version if install Netdata with a binary package.

**I'm Not installed netdata from source.**

**Comment by vlvkobal** [comment]
`netdata -V`

**Comment by hamzash9500** [comment]
netdata -V
bash: /usr/sbin/netdata: No such file or directory

**Comment by vlvkobal** [comment]
What is the output of `ps -ax | grep netdata`?

**Comment by ilyam8** [comment]
```
$(ps aux | grep -E -o "[a-z/]+netdata ") -v
netdata v1.14.0-rc0-1-gf4c2d151
```

**Comment by hamzash9500** [comment]
@vlvkobal 
this is the output
ps -ax | grep netdata
11248 ?        Ssl    0:16 /opt/netdata/bin/srv/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
11282 ?        S      0:06 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
11291 ?        Sl     0:05 /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
11297 ?        S      0:51 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1

**Comment by hamzash9500** [comment]
@ilyam8 
many thanks.

**Comment by hamzash9500** [comment]
i have another question 
How i can disable automatically upgrade .
when execute kickstart.sh and i added --no-updates as:
sh netdata-v1.12.0-rc0-64-g8c09913c-x86_64-20181219-052839-firehol.gz.run --no-updates
I have got :[ Unrecognized flag : --no-updates]

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/issues/5772#issuecomment-478928612

> Remove netdata-updater from /etc/cron.daily.

> If you don’t want to receive automatic updates, add --no-updates when executing kickstart.sh script.

bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates

**Comment by ilyam8** [comment]
check 
https://docs.netdata.cloud/packaging/installer/#one-line-installation

see `Click here for more information and advanced use of this command.` dropdown menu
