### ISSUE TITLE
Typo in netdata-updater

### ISSUE THREAD

**Issue by shinji257** [netdata/netdata#5781]
##### Bug report summary
Line 83 currently has a typo where it is calling a non-existent function/command "failed" when it should be fatal instead.

https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-updater.sh#L83

##### Netdata version (ouput of `netdata -V`)
netdata v1.14.0-rc0-20-nightly

##### Component Name
netdata-updater

##### Steps To Reproduce
Well we need a fail scenario but currently if checksum doesn't match somehow (this happened tonight for me I guess) you get the following message from the system (in my case cron sent it to me)
 /etc/cron.daily/netdata-updater: line 83: failed: command not found

##### Expected behavior
Should throw an error properly.

This is related to commit https://github.com/netdata/netdata/commit/e11ffb482980bef8f182b6160d58884d0c313ce9 where the failed function was renamed to fatal.  This line appears to have been missed and is the only one where failed is still trying to be called.  It appears that it should have been renamed to fatal when the function was renamed.

**Comment by wmtech-1** [comment]
Confirm.

All machines with netdata have reported:

`/etc/cron.daily/netdata-updater:

/etc/cron.daily/netdata-updater: line 83: failed: command not found`

**Comment by paulkatsoulakis** [comment]
Hi guys, i am getting a PR to fix the issue now, but i will let the issue open though for establishing a travis check to catch this in the future.

**Comment by cakrit** [comment]
Please update the nightly build and then close it. More and more people will get the wrong version.

**Comment by ktsaou** [comment]
happened on one netdata demo site too:

```
/etc/cron.daily/netdata-updater:
/etc/cron.daily/netdata-updater: line 83: failed: command not found
```

If I understand this correctly, this broke the update function again, requiring from all users to update their netdata by hand to get over it.

**Comment by paulkatsoulakis** [comment]
> happened on one netdata demo site too:
> 
> ```
> /etc/cron.daily/netdata-updater:
> /etc/cron.daily/netdata-updater: line 83: failed: command not found
> ```
> If I understand this correctly, this broke the update function again, requiring from all users to update their netdata by hand to get over it.

If by hand you mean rerunning the installer by hand, then yes.
Bad experience whatsoever

**Comment by paulkatsoulakis** [comment]
We have updated everything, closing this. Feel free to reopen new issue if the problem persists.
Again, apologies for all the inconvenience.
