### ISSUE TITLE
Netdata Graph value to another website's webpage

### ISSUE THREAD

**Issue by fti-dpogra** [netdata/netdata#5784]
Hi, 

Previously i created a netdata custom dashboard with gauge and line charts using python module. Now graph is hidden by me from netdata dashboard, and working fine in backend.

Now i want to collect chart values from nedata module (which running in backend) to my website's webpage.

Please suggest me...

Thank's to @ilyam8 and netdata Team

**Comment by ilyam8** [comment]
@fti-dpogra 

Do you want to embed real time graphs to your website? If yes, then use code from [custom dashboard](https://docs.netdata.cloud/web/gui/custom/) on your page.

If you need just values - to get them use netdat api

Have a look there https://registry.my-netdata.io/swagger/#/default/get_data

___

Example: i have the `example.random` chart, and i want to get **last** values for it.

Request:

`http://127.0.0.1:19999/api/v1/data?chart=example.random&&after=-1`

Response:
```json
{
    "labels": [
        "time",
        "random1",
        "random2",
        "random3"
    ],
    "data": [
        [
            1554279252,
            62,
            42,
            15
        ]
    ]
}
```

**Comment by fti-dpogra** [comment]
> @fti-dpogra
> 
> Do you want to embed real time graphs to your website? If yes, then use code from [custom dashboard](https://docs.netdata.cloud/web/gui/custom/) on your page.
> 
> If you need just values - to get them use netdat api
> 
> Have a look there https://registry.my-netdata.io/swagger/#/default/get_data
> 
> Example: i have the `example.random` chart, and i want to get **last** values for it.
> 
> Request:
> 
> `http://127.0.0.1:19999/api/v1/data?chart=example.random&&after=-1`
> 
> Response:
> 
> ```json
> {
>     "labels": [
>         "time",
>         "random1",
>         "random2",
>         "random3"
>     ],
>     "data": [
>         [
>             1554279252,
>             62,
>             42,
>             15
>         ]
>     ]
> }
> ```

i tried the link you mentioned with my ip. Output is: 
{
 "labels": ["time", "run time"],
    "data":
 [
      [ 1554289620, 112],
      [ 1554289605, 133],
      [ 1554289590, 114],
      [ 1554289575, 104]
]
}

Can you have any example of this...

**Comment by ilyam8** [comment]
change `example.random` to the chart name you are interested in and check again

**Comment by fti-dpogra** [comment]
> change `example.random` to the chart name you are interested in and check again

Now i am struggling with jquery ajax to get last value.. 

Thank you so much @ilyam8

**Comment by fti-dpogra** [comment]
> > change `example.random` to the chart name you are interested in and check again
> 
> Now i am struggling with jquery ajax to get last value..
> 
> Thank you so much @ilyam8

Hi @ilyam8 

My task is completed. You can close.

Thank you for support.

**Comment by ilyam8** [comment]
I wodner, could you provide a link to your site? Screenshot would be ok too if the site is not public.

**Comment by fti-dpogra** [comment]
Sure! I send you screenshot tomorrow. I am outside now.

**Comment by fti-dpogra** [comment]
> I wonder, could you provide a link to your site? Screenshot would be ok too if the site is not public.

![scc_final](https://user-images.githubusercontent.com/47653584/55603526-bb3cbf00-5788-11e9-8b87-c314a5a355f7.png)
