### ISSUE TITLE
Need help to understand mdstst alerts

### ISSUE THREAD

**Issue by jurgenhaas** [netdata/netdata#5787]
On a couple of hosts we're seeing constant mdstat alerts but can't understand where they are coming from.

Example 1: netdata reports 2.432 unsynchronized blocks on md2 and /proc/mdstat gives us the following output:

```
md0 : active raid1 sdb1[1] sda1[0]
      33521664 blocks super 1.2 [2/2] [UU]
      
md2 : active raid1 sda3[0] sdb3[1]
      465895744 blocks super 1.2 [2/2] [UU]
      bitmap: 4/4 pages [16KB], 65536KB chunk

md1 : active raid1 sda2[0] sdb2[1]
      523712 blocks super 1.2 [2/2] [UU]
```

We've tried to find more details with `mdadm`, with `smartctl` and with `nvme-cli` but nothing seems to be telling us what's going wrong or even how to fix that.

Example 2: on a different host the alert talks about 256 unsynchronized blocks and the /proc/mdstat output is this:

```
md1 : active raid1 nvme1n1p2[0] nvme0n1p2[1]
      523712 blocks super 1.2 [2/2] [UU]
      
md2 : active raid1 nvme1n1p3[0] nvme0n1p3[1]
      932840768 blocks super 1.2 [2/2] [UU]
      bitmap: 5/7 pages [20KB], 65536KB chunk

md0 : active raid1 nvme1n1p1[0] nvme0n1p1[1]
      4190208 blocks super 1.2 [2/2] [UU]
```

Are we missing something or is this some false positives? Any insight into what's going on is much appreciated.

**Comment by ilyam8** [comment]
Hi @jurgenhaas 

Check this
https://github.com/netdata/netdata/issues/3622

**Comment by jurgenhaas** [comment]
Thanks a lot @ilyam8, that explained it all.

**Comment by luison** [comment]
Sorry to bring this back but we have a similar issue here with a couple of nvme raid1. 
Netdata mistmatch alerts on array, that does not reflect on any issues with drives or the raid itself. 

I've read this on https://www.thomas-krenn.com/en/wiki/Mdadm_checkarray_function :

_On a truly clean RAID5 or RAID6 array, any mismatches should indicate a hardware problem at some level - software issues should never cause such a mismatch. However on RAID1 and RAID10 it is possible for software issues to cause a mismatch to be reported. This does not necessarily mean that the data on the array is corrupted. It could simply be that the system does not care what is stored on that part of the array - it is unused space. The most likely cause for an unexpected mismatch on RAID1 or RAID10 occurs if a swap partition or swap file is stored on the array._

So still uncertain if I should ignore and increase the alarm test, or how to investigate if there are any underlaying isssues, further.

**Comment by ilyam8** [comment]
hi @luison, you are right, it is unclear indeed, that alarm **just warns you** that there are some `mdstat_mismatch_cnt`'s. It doesn't mean there is a problem. 

Perhaps we need to have different alarm conditions/infos depends on the raid type. 

Related issue https://github.com/netdata/netdata/issues/10247
