### ISSUE TITLE
alarm-notify.sh should respect the cloud base url setting

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5791]
The url https://netdata.cloud is hard-coded in `health/notifications/alarm-notify.sh.in`. It should be using the netdata.conf config option `cloud base url` from the `[cloud]` section of netdata.conf.

**Comment by ladakis** [comment]
Hello,
I kinda finished the implementation of this issue but i have a difficulty on testing it. I can't utilize the code responsible for cloud in health/notifications/alarm-notify.sh.in. Correct me if i am wrong... setenv on the C code is valid for the environment of the calling process only. "env" command doesn't show the exported variables. Can i have an insight on how to utilize this part?
Thank you,
Evangelos Ladakis

**Comment by cakrit** [comment]
`mypopen` passes the environment to the executed script. Have it write something on a file for your tests. You do need to trigger it (i.e. have netdata raise an alarm). 
An easy way to do it if you don't have any alarms, is to change the threshold of one of the existing alarms. See https://docs.netdata.cloud/health/

**Comment by cakrit** [comment]
Oh, and of course you can do a WIP PR, so we can help right there.
