### ISSUE TITLE
Can you set dimension options dynamically?

### ISSUE THREAD

**Issue by lwchan2k1** [netdata/netdata#5793]
i tried to loop through the dimension from a chart and try to set options to hidden/obsolete (running netdata v1.11.1)

```
for i in range(len(self.charts['chartname'].dimensions)):
    self.charts['chartname'].dimensions[i].options = 'hidden'
```
is this a right way?

**Comment by ilyam8** [comment]
Hi @lwchan2k1 

The right way is

https://github.com/netdata/netdata/blob/beec069a3a93faf1b2679591a2055c49145fc444/collectors/python.d.plugin/python_modules/bases/charts.py#L203-L208


so something like that

```python
for dim in self.charts['chartname']:
    self.charts['chartname'].hide_dimension(dim.id)
```

**Comment by ilyam8** [comment]
What are you trying to achieve @lwchan2k1 ? 

i see no point in 

> i tried to loop through the dimension from a chart and try to set options to hidden

**Comment by lwchan2k1** [comment]
i create dimension dynamically to unique path/file, and over time it accumulates a big list shown on the charts. I just want to hide / obsolete dimension which is outdated.

in other way, can we sort dimension in the charts based on count?

**Comment by ilyam8** [comment]
> i create dimension dynamically to unique path/file, and over time it accumulates a big list shown on the charts. 

There is no way to obsolete dimension in python for now, i haven't added the feature yet. Obsolete != delete btw, obsolete is mark as obsoleted, they won't be deleted from chart immediately but after an hour by default (after deleting from database). Maybe hide+obsolete trick will do, i need to check.

> in other way, can we sort dimension in the charts based on count?

No.

**Comment by ilyam8** [comment]
i will add the fix

**Comment by ilyam8** [comment]
@lwchan2k1 please test #5795
