### ISSUE TITLE
How to monitor dotnet core or C# application using netdata

### ISSUE THREAD

**Issue by makutamatey** [netdata/netdata#5798]
I have successfully installed netdata on Amazon EC2 and it is running. My problem is how to connect the application I want to monitor to netdata. Can someone help me out?. The application is written in dotnet core

**Comment by vlvkobal** [comment]
If you want to monitor it with `apps.plugin` just add the application to a new group in `apps_groups.conf`. Look at the [documentation](https://docs.netdata.cloud/collectors/apps.plugin/#configuration) for more information.

**Comment by makutamatey** [comment]
Thank you. I am sorted out
