### ISSUE TITLE
Connecting netdata to another instance

### ISSUE THREAD

**Issue by makutamatey** [netdata/netdata#5801]
I have installed netdata on an instance on AWS, but I dont want to host my application on the same instance. I want to create another instance for my application. How can I connect netdata to that instance to collect data

**Comment by cakrit** [comment]
The short answer is that you won't be able to get most of the out of the box metrics, unless netdata runs on the same instance. You could of course monitor remotely things like a web server, a mysql DB etc, anything that relies on TCP communication. You would just configure the end points for those collectors and ensure that your netdata instance is allowed to access those endpoints. 

One other thing that is possible with containers but probably not across instances unless you use a shared storage for system files, is to have the netdata instance read specific system directories that the application instance would own.  That would entail configuring for example the proc plugin to look for the files it processes in different locations.  

I can't think of anything else you could do and it's not a use case we'd consider looking into. netdata is lightweight enough to be running on IoT devices, so I can't think of a reason to do what you're proposing.  You can also stream metrics from a netdata running on the application instance to a master netdata running on the different image (master-slave) set up, so perhaps that would cover your needs. But we'll need a bit more info on what you're trying to accomplish and the limitations you're facing.

**Comment by makutamatey** [comment]
Thank you sir. The only way out now is the master-slave approach which  I have done.
