### ISSUE TITLE
pfsense builds for armv6 and aarch64

### ISSUE THREAD

**Issue by artooro** [netdata/netdata#5804]
##### Question summary

I would like to use netdata on pfSense Netgate SG-1100 and SG-3100 appliances which are aarch64 and armv6 respectively. I was able to find an old version of netdata for aarch64 but nothing for armv6.

Is there a place to get newer builds for these architectures, or should I work on a cross build setup for my use?

##### OS / Environment

ARM 64 and 32 bit systems on Netgate SG-1100 and SG-3100 firewalls.

**Comment by cakrit** [comment]
Is there a reason you can't use the [kickstart.sh](https://docs.netdata.cloud/packaging/installer/#one-line-installation) script for the installation?

**Comment by cakrit** [comment]
Scratch the last comment, let me look into the pfsense installation instructions first...

**Comment by cakrit** [comment]
@mmokhi, the instructions we have [here](https://docs.netdata.cloud/packaging/installer/#pfsense) require a package on http://pkg.freebsd.org. Is there something you would be willing/able to publish for armv6?

**Comment by mmokhi** [comment]
I think the document is sorta outdated :thinking: 
If you are already getting the rest of packages (`bash` for example) from pkg.freebsd.org you can simply do it `pkg install netdata` as well.
You don't even need to take care of dependencies as I'm handling them already, so just `pkg install netdata` should be enough.

about armv6, I don't have the devices to test tbh.
But I don't see why it's not in official repos if FreeBSD ports are available for that platform...

On FreeBSD the packages are automatically built based on the ports, and there's no `BROKEN`/`IGNORE` flags I can see on netdata, so I expect it to be build-able in first place.

**Comment by artooro** [comment]
I was able to use poudriere on a freebsd machine to build the package for armv6. But as it turns out netdata is too inefficient in its streaming protocol and so I can't use it as many of my deployments don't have a lot of spare bandwidth.
