### ISSUE TITLE
Kickstart-static64.sh installation problems

### ISSUE THREAD

**Issue by EnzoAkira** [netdata/netdata#5807]
Hi everyone!
##### Bug report summary
Yesterday I was installing netdata with this command like always:
`sh /tmp/kickstart-static64.sh --dont-wait --dont-start-it` 
But I am not be able to access to netdata website on my machine.
I checked if the netdata service is up, and it is, but with errors like this:
![systemctl netdata](https://user-images.githubusercontent.com/39481527/55617669-8c284c80-578c-11e9-965d-0e6639b37086.png)

On journalctl has some errors too:
![journalctl netdata](https://user-images.githubusercontent.com/39481527/55618121-a7e02280-578d-11e9-9762-af4008ee9022.png)
Restarting netdata service take a bit long time and doesn't resolve anything.
##### OS / Environment
CentOS Linux 7.6.1810
Kernel 3.10.0-862.14.4.el7.x86_64
##### Netdata version (output of `netdata -V`)
netdata v1.14.0-rc0-33-gd9d41e6b
##### Component Name
netdata
##### Steps To Reproduce
- Download kickstart-static64.sh
`wget -O /tmp/kickstart-static64.sh https://my-netdata.io/kickstart-static64.sh`
- installing netdata with:
`sh /tmp/kickstart-static64.sh --dont-wait --dont-start-it` 
#####
Edit:
One thing I forgot to mention:
I dug into the code of kickstart-static64 and found that it has a "--stable-channel" argument just to install stable releases. I suggest you need to insert into docs [Installation](https://docs.netdata.cloud/packaging/installer/)
I'll try to do this and see if that solves it for now.

**Comment by paulkatsoulakis** [comment]
Hello @EnzoAkira I am suspecting you are experiencing the same problem with #5803 that is already fixed. Can you try again with the latest from https://my-netdata.io/kickstart-static64.sh and let me know?

**Comment by EnzoAkira** [comment]
It's working now! Thank you!

About the `--stable-channel` how does this work? Is it just for kickstart.sh or does it also work on kickstart-static64?

**Comment by cakrit** [comment]
https://github.com/netdata/netdata/pull/5487 introduced the stable channel everywhere. @paulkatsoulakis we need an update on the installer readme.md please.
