### ISSUE TITLE
Errorneous netdata version

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5808]
Anonymous statistics tell us that we have cases where the netdata version is not set properly. Instead of the format e.g. `v1.14.0-rc0-36-g4231e17d`, we see 7 hex chars (e.g. `8920a2c4`). It's not OS-specific, so it's definitely not a distributed package that has the issue. I haven't been able to determine if this happened in the past, or keeps happening, but one of the effects is that the UI version check will not function. 

Stats: 
Last 7 days: 17% of START events with a wrong netdata version
Last 30 days: 26% of START events with a wrong netdata version

So it could be something that is corrected now, but we need to understand what happened.

Note that the netdata version is is the generated config.h.

**Comment by paulkatsoulakis** [comment]
I am handling this bug report on #5855.
I have found that this problem also happening within travis and i spotted the bug
