### ISSUE TITLE
Customize error function

### ISSUE THREAD

**Issue by Arnaud92BlR** [netdata/netdata#5809]
Hello,

When the html page cannot retrieve data (netdata server is unreachable), an error message is displayed (something like `system.cpu: data download failed for url: http://host:19999/api/v1/data?chart=system.cpu&format=array`).

Is it possible to customize this behavior so that something else (an image, ...) is displayed ?

Thanks,
Arnaud

**Comment by gmosx** [comment]
You would like a different default? Or having the option to customize this?

**Comment by Arnaud92BlR** [comment]
I think an option to be able to customize what is displayed is the best.
Regards,
Arnaud

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
