### ISSUE TITLE
Netdata last collected alarms

### ISSUE THREAD

**Issue by secato** [netdata/netdata#5813]
Hey everyone

I'm receiving **similar** alarms almost once a day, or every two days from my instances:
![image](https://user-images.githubusercontent.com/5840942/55644991-ca823380-57ad-11e9-8656-68ad87a8faf5.png)

I'm using netdata v1.14.0-rc0-20-nightly
All instances are ubuntu 18.04
My setup is a central netdata server while the instances just stream to it

Those alarms are triggered when the instance itself cannot collect the data or if the central netdata server don't receive it?

Does anyone have any clue of what is happening?

**Comment by secato** [comment]
I checked the error.log at the exact moment when it's happened and I've got a **"too many data pending"** error when streaming the data, and then the connection was closed to flush the data.

At my central netdata there is a message on error log when the client machine connected:
**"multiple streaming connections for the same host detected"**.

**Comment by cakrit** [comment]
Apologies for the delay in the response, this one slipped through the cracks. 
Let's first get rid of the "multiple streaming connections for the same host detected" error. This can happen in two ways:
- You somehow ended running two netdata processes on the same host, at the same time.
- `/var/lib/netdata/registry/netdata.public.unique.id` contains the same GUID in more than one of your slave hosts. This could happen for example if you have your own image where netdata has ran at least once, leaving behind that file and you clone that image. 

To determine who triggers the alarm, you could directly access the GUI of one of slaves and look at Alarms -> Log from the top menu, or hit `http://slave-name:19999/api/v1/alarm_log`). Of course it depends on where the health checks are executed (i.e. the master could also run the same checks and trigger an alarm on behalf of a slave). I don't think it's that important though, the question is why the data can't be collected in the first place. 

Does the issue occur at the same time every day/couple of days? Perhaps there's a cron job causing an issue?
Is it always the same three alarms you show in your OP?
