### ISSUE TITLE
Dockerized netdata to show container names instead of IDs on QNAP

### ISSUE THREAD

**Issue by Leosirth** [netdata/netdata#5823]
Hi,

I'm running netdata as a container in a QNAP environment and would like to monitor other containers with the name as the label instead of the ID.

I went throughout other similar issues but all was referring to missing docker.sock mount or PGID

This is the docker-compose used:

```
version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: XXX
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PGID=0
```
On the host there isn't a docker group, so I set the PGID to the group ID of the user that runs dockerd (0)
The docker.sock is correctly mounted in the container:

`srw-rw----    1 root     root             0 Apr  1 08:08 docker.sock`

And this is from the host:

`srw-rw----  1 admin    administrators    0 2019-04-01 10:08 docker.sock`

with ID (from host):

`srw-rw---- 1  0     0    0 2019-04-01 10:08 docker.sock`

this is the netdata IDs:

`uid=201(netdata) gid=201(netdata) groups=30(readproc),70(postgres),80(cdrw),200(nofiles),201(netdata),300(abuild)`

Seems still a permission issue:

```
2019-04-09 12:25:52: cgroup-name.sh: INFO: Running API command: /containers/63a4bf87a8432bd47a70bd8545f33108a1da6f6adf529b7fb83c0bff465508d9/json,
nc: unix connect failed: Permission denied,
2019-04-09 12:25:53: cgroup-name.sh: WARNING: cannot find the name of docker container '63a4bf87a8432bd47a70bd8545f33108a1da6f6adf529b7fb83c0bff465508d9',
2019-04-09 12:25:53: cgroup-name.sh: INFO: cgroup 'docker_63a4bf87a8432bd47a70bd8545f33108a1da6f6adf529b7fb83c0bff465508d9' is called '63a4bf87a843',
2019-04-09 12:25:53: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : Using host prefix directory '/host',
2019-04-09 12:25:53: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : running: exec /usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/host/sys/fs/cgroup/cpuacct/docker/63a4bf87a8432bd47a70bd8545f33108a1da6f6adf529b7fb83c0bff465508d9',
2019-04-09 12:25:53: cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/host/sys/fs/cgroup/cpuacct/docker/63a4bf87a8432bd47a70bd8545f33108a1da6f6adf529b7fb83c0bff465508d9',
2019-04-09 12:25:53: /usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : child pid 1661 exited with code 1.,
2019-04-09 12:25:53: /usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : Cannot find a cgroup PID from cgroup '/host/sys/fs/cgroup/cpuacct/docker/63a4bf87a8432bd47a70bd8545f33108a1da6f6adf529b7fb83c0bff465508d9',
```
Moreover I see this error when netdata starts, dunno if correlated or expected:

```
2019-04-09 12:25:29: python.d INFO: plugin[checker] : dockerd : checking,
2019-04-09 12:25:29: python.d INFO: plugin[checker] : dockerd : source successfully loaded,
2019-04-09 12:25:29: python.d INFO: plugin[checker] : dockerd : found config file '/usr/lib/netdata/conf.d/python.d/dockerd.conf',
2019-04-09 12:25:29: python.d INFO: plugin[checker] : dockerd : created 1 job(s) from the config,
2019-04-09 12:25:29: python.d ERROR: dockerd[local] : 'docker' package is needed to use dockerd module,
2019-04-09 12:25:29: python.d INFO: plugin[checker] : dockerd[local] : check failed, skipping the job,
2019-04-09 12:25:29: python.d INFO: plugin[checker] : dockerd : all jobs failed, skipping module,
```

I'm using the official netdata:latest docker image:

`Your netdata version: v1.14.0-rc0-39-g0d4da488`

Could the groupID of 0 making trouble since in the container the same ID is used for the root group?
Can you help me to fix this?
Thanks and regards,

**Comment by cakrit** [comment]
We missed this one, apologies. Are you still facing this issue? Asking @paulkatsoulakis to take a look...

**Comment by paulkatsoulakis** [comment]
as per the documentation here: https://docs.netdata.cloud/collectors/python.d.plugin/dockerd/ you need the docker package on the instance if you want to use dockerd.

@cakrit should it be that by default package `docker` is installed on the image we ship?
I thought such a serious package is better to be explicitly installed if needed by the person setting up dockerd

**Comment by cakrit** [comment]
IMHO, our docker image needs to have everything required to run all collectors. We shouldn't be asking users to hack our Dockerfile to get something to work, it's complex enough as it is. The only other alternative is to explicitly document [here](https://docs.netdata.cloud/packaging/docker/) the options that people can provide to select what the image will contain, so that it doesn't become bloated.

**Comment by Leosirth** [comment]
Hi @cakrit  @paulkatsoulakis 

thanks for your feedback.
As per my understanding the docker package is needed for some additional docker charts and would fix the error:

`2019-04-09 12:25:29: python.d ERROR: dockerd[local] : 'docker' package is needed to use dockerd module,`

Can you also help me for having container names instead of IDs?

Thanks and regards,

**Comment by ilyam8** [comment]
@Leosirth 

The message is produced by python.d module, it is not related to the problem

**Comment by paulkatsoulakis** [comment]
> @Leosirth
> 
> The message is produced by [python.d module](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/dockerd), it is not related to the problem

actualy dockerd has a failover approach to retrieve docker name that depends on docker package

**Comment by paulkatsoulakis** [comment]
> as per the documentation here: https://docs.netdata.cloud/collectors/python.d.plugin/dockerd/ you need the docker package on the instance if you want to use dockerd.
> 
> @cakrit should it be that by default package `docker` is installed on the image we ship?
> I thought such a serious package is better to be explicitly installed if needed by the person setting up dockerd

I 'll have to take back the need for adding docker package.
the user can just pass the binary with -v option when running the image

I am continuing investigation.

**Comment by paulkatsoulakis** [comment]
@Leosirth could you confirm whether adding `-v /usr/local/bin/docker:/usr/bin/docker` in your docker run command solves your issue? I am facing some problems on my test environment so in the meantime it would help if you can check how this affects the docker name resolution

**Comment by Leosirth** [comment]
@paulkatsoulakis sure.
I'm not able to test it right now, give me a couple of hours and will let you know.

**Comment by paulkatsoulakis** [comment]
> @paulkatsoulakis sure.
> I'm not able to test it right now, give me a couple of hours and will let you know.

Hi @Leosirth, any luck ?

**Comment by Leosirth** [comment]
Hi @paulkatsoulakis 

sorry I was a little busy and also having some trouble finding the correct docker bin to use (QNAP is a little over-complicated).

In the end I still have the same issue even if I can successfully invoke docker from inside netdata container.

I'm pretty new on this so this could be nonsense but isn't that we need the python package instead of docker binary?

looking at:

https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/dockerd/dockerd.chart.py

it try to:

`import docker`

as per:

https://docker-py.readthedocs.io/en/stable/

the image doesn't have pip installed and I can't figure out if there is a requirements.txt for python package somewhere on the image building or a way to add this.

What are your thought on this?

**Comment by ilyam8** [comment]
> I'm pretty new on this so the following could be nonsense but isn't that we need the python package instead of docker binary?

yes, python package

**Comment by paulkatsoulakis** [comment]
Hello! Sorry for the late come back, the precompiled `netdata/netdata` docker image should have everything needed to run all functionality of netdata.

I 'll re-iterate and let you know

**Comment by Leosirth** [comment]
Hi @paulkatsoulakis 

I see nightly just triggered and I just updated netdata:

`v1.15.0-81-gabdd4b0e`

I mounted the docker socket with write permission, the PGID was already set, but I get the same issue and result.

docker python module is still missing and container names show IDs.

**Comment by paulkatsoulakis** [comment]
Hi @Leosirth, you also need to mount docker binary, so that netdata can use it to handle the translation of IDs to names for containers.

If you check [here](https://docs.netdata.cloud/packaging/docker/), you will notice we have added the following line also:

```
      - /path/to/actual/docker/on/the/host:/usr/bin/docker
```

I am checking now the python package issue you mention, that sounds like a different thing all together and likely not related to the translation of container IDs to names.

**Comment by Leosirth** [comment]
Hi @paulkatsoulakis 

I have already mounted the docker binary as asked previously on this issue.
I can invoke docker from inside netdata container.

I think the issue is still the permission on the docker socket.
This is the netdata ids:

`uid=201(netdata) gid=201(netdata) groups=201(netdata),201(netdata)`

While the docker socket has PID and GID 0

Regarding the python package I this it's not related to this issue, but is needed for some additional charts, I can open a new issue for this if you prefer.

Thanks and regards,

**Comment by paulkatsoulakis** [comment]
Hi @Leosirth yes for that separate issue on the python package, i think it would be better to reported on a new issue to distinct the use cases.

As a first step about this issue, please make sure you pull the latest docker image by doing a `docker pull netdata/netdata`.  Then make sure you have switched your docker compose as we said to have `rw` instead of `ro` on the docker socket mount command. As a last step, you create a group called "docker" on your host that runs the containers and then you pass to PGID the ID of that group that you have created.

Then run your container and name resolution should be fixed.

**Comment by lukasmrtvy** [comment]
@paulkatsoulakis  I dont think its working... 

```
ls -n /var/run/docker.sock 
srw-rw---- 1 0 996 0 Jun 21 21:58 /var/run/docker.sock
```
```
ls -l /var/run/docker.sock 
srw-rw---- 1 root docker 0 Jun 21 21:58 /var/run/docker.sock
```
```
grep docker /etc/group | cut -d ':' -f 3
996
```
```
docker pull netdata/netdata:latest && \
docker rm -f netdata; \
docker run -d  \
  -e PGID=$(grep docker /etc/group | cut -d ':' -f 3) \
  -v /usr/bin/docker:/usr/bin/docker \
  --name=netdata \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:rw \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  --restart unless-stopped \
  netdata/netdata:latest
```
```
docker logs netdata
Netdata entrypoint script starting
Adding group with ID 996 and name 'docker'
Adding user 'netdata' to group 'docker/996'
Group creation and assignment completed, netdata was assigned to group docker/996
Adjusting ownership of mapped docker socket '/var/run/docker.sock' to root:docker
chown: /var/run/docker.sock: Read-only file system
```

Also when I change :rw to docker.sock
```
/usr/libexec/netdata/plugins.d/cgroup-name.sh: line 51: /usr/bin/docker: No such file or directory
```
```
docker exec -it netdata  /usr/bin/docker
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "no such file or directory": unknown
```
```
docker exec -it netdata ls -l /usr/bin/docker
-rwxr-xr-x    1 root     root      68589152 May  4 02:35 /usr/bin/docker
```
```
docker exec -it netdata ls -n /usr/bin/docker
-rwxr-xr-x    1 0        0         68589152 May  4 02:35 /usr/bin/docker
```

**Comment by paulkatsoulakis** [comment]
Hi @lukasmrtvy thanks for reaching out! 
The errors about `/usr/bin/docker` are expected if you don't mount docker binary.
Our implementation does not require the docker binary for the name resolution to work though.
We utilise the API capability to retrieve the details and we only require the docker socket.
Regarding the docker binary, it may not work at all cases and this is the reason we avoid using it in the first place.

Once you have switched your socket to `rw` please check your dashboard to see if your containers are resolved by their name after some time.  Note that it might require the page to be refreshed.

Let me know once you 've checked the above, thanks!

**Comment by maisun** [comment]
I’m facing the same issue here, anybody managed to get the docker container name when running netdata I docked?

**Comment by Ferroin** [comment]
@maisun Please see https://learn.netdata.cloud/docs/agent/packaging/docker#docker-container-names-resolution.

The only requirement to get this working is to properly expose the Docker socket from the host to Netdata.

**Comment by televisi** [comment]
Sorry for reviving an old thread.
I'm having the same issue with this one on #17072 

I went to https://learn.netdata.cloud/docs/agent/packaging/docker#docker-container-names-resolution looks but unable to find a clear information on this

@Leosirth @maisun did you manage to find a resolution to this at the end?
Thanks
