### ISSUE TITLE
Is there API to get the incremental chart interpolation value in plugin/module

### ISSUE THREAD

**Issue by qingkunl** [netdata/netdata#5825]
The incremental chart interpolation in Netdata works great! However, I can't find a way/API to get the interpolated value in the plugin/module.

For example, in my Go plugin module, metrics 'a' and 'b' are incremental, and I'd like to calculate metric 'c' using the interpolated 'a' and 'b' values (e.g. c = a/b), without having to calculate the incremental interpolation for 'a' and 'b' myself in the module.

Thanks.

**Comment by ilyam8** [comment]
hi @qingkunl 

i am not clear about the question, but the only way to get those values is to use [http api](https://docs.netdata.cloud/web/api/)
