### ISSUE TITLE
Firefox displays main stats in white, even in dark mode (COSMETIC)

### ISSUE THREAD

**Issue by vc7ee** [netdata/netdata#5826]
##### Bug report summary
![image](https://user-images.githubusercontent.com/38327267/55828405-dd716c80-5afb-11e9-887f-ee756d9fec8f.png)
For a long time Firefox displays the main stats in white.
##### OS / Environment
Ubuntu 18.04
##### Netdata version (ouput of `netdata -V`)
v1.14.0-rc0-39-nightly

**Comment by ilyam8** [comment]
no problem for me - firefox `66.0.3`

@gmosx take a look

**Comment by gmosx** [comment]
Can't reproduce either.

**Comment by vc7ee** [comment]
Found it, extra canvas data. Laptop Firefox `67.0b9`.
![image](https://user-images.githubusercontent.com/38327267/56018986-0ad43b00-5cf3-11e9-843e-24a85272c8ad.png)

**Comment by henrywhitaker3** [comment]
@vc7ee how did you allow this permission? Having the same issue

**Comment by vc7ee** [comment]
@henrywhitaker3 it's like with youtube, you will get an icon there, pressing exactly on it will reveal the promt once again 
![image](https://user-images.githubusercontent.com/38327267/56161390-e6a98000-5fb8-11e9-8344-f1df703f05ab.png)

**Comment by vc7ee** [comment]
@henrywhitaker3 find this icon in the url bar while on the netdata page
![image](https://user-images.githubusercontent.com/38327267/56161458-1193d400-5fb9-11e9-8f23-de199529711c.png)
click on it
Allow it, voilá!

**Comment by vc7ee** [comment]
This should maybe be documented?
