### ISSUE TITLE
Fix dependency installation for Fedora 30

### ISSUE THREAD

**Issue by MichaelRiss** [netdata/netdata#5831]
##### Bug report summary
Currently the `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` installation does not work on the Fedora 30 pre-release. The specific problems are:
- Fedora 30 starts to cut down on python2 packages while still providing a base python2 binary. The `install-required-packages.sh` script sees the python2 binary and therefore assumes a python2 installation is fine and then fails to install the necessary python2 packages that don't exist anymore.
- `install-required-packages.sh` assumes that `libuuid-devel` is installed by default on Fedora. However on Fedora 30 this is not the case anymore, `install-required-packages.sh` misses to install this dependency and the compilation fails in the `configure` stage as a result.

I attach a modified version of `install-required-packages.sh` script (albeit renamed `install-required-packages.sh.txt` due to github file upload naming issues) that adds some exceptions to make it work on Fedora 30. It may not be the final solution for the script but it could give you some pointers to what's necessary.
Link to attached file is here ->[install-required-packages.sh.txt](https://github.com/netdata/netdata/files/3066285/install-required-packages.sh.txt)<-

A side note: I didn't find the `install-required-packages.sh` script in the netdata repository, it seems to be maintained outside. Maybe you want to consider to include this script in the repository which would facilitate improvement suggestions such as this one as they could be submitted as pull requests.

##### OS / Environment
Fedora 30 pre-release (state of 10.04.2019)
The retirement of python2 packages is a declared goal of the Fedora 30 release and therefore I do not expect the situation to change until the final release. 
https://fedoraproject.org/wiki/Changes/Mass_Python_2_Package_Removal

##### Netdata version (ouput of `netdata -V`)
netdata v1.14.0-rc0-42-nightly

##### Component Name
`https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh`

##### Steps To Reproduce
- install current Fedora 30 pre-release
- run `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

##### Expected behavior
A successful installation.

**Comment by paulkatsoulakis** [comment]
Hi @MichaelRiss, thanks for your report.
Could you share the following information from the offending machine?
1)`cat /etc/os-release` 
2)`uname -a`
3) `rpm -qa`

**Comment by paulkatsoulakis** [comment]
On a first investigation on a Fedora 29 distribution i can confirm that the installer fails on the very first attempt. The packages are there though after the failure
```
$'[\E[2m/tmp/netdata-kickstart-XXXXXXXXXXX/netdata-v1.14.0-rc0-42-gbee48fd3\E(B\E[0m]# \E[1m\E[33m' ./netdata-installer.sh --auto-update $'\E(B\E[0m\\n' + return 0
+ ./netdata-installer.sh --auto-update

  ^
  |.-.   .-.   .-.   .-.   .  netdata                                        
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


  You are about to build and install netdata to your system.

  It will be installed at these locations:

   - the daemon     at /usr/sbin/netdata
   - config files   in /etc/netdata
   - web files      in /usr/share/netdata
   - plugins        in /usr/libexec/netdata
   - cache files    in /var/cache/netdata
   - db files       in /var/lib/netdata
   - log files      in /var/log/netdata
   - pid file       at /var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata

  This installer allows you to change the installation path.
  Press Control-C and run the same command with --help for help.

 
+ local ret=1
+ '[' 1 -ne 0 ']'
+ printf ' FAILED  ./netdata-installer.sh --auto-update \n\n'
 FAILED  ./netdata-installer.sh --auto-update 

+ return 1
+ fatal 'netdata-installer.sh exited with error'
+ printf ' ABORTED  netdata-installer.sh exited with error \n\n'
 ABORTED  netdata-installer.sh exited with error 

+ exit 1
[root@bug5831 ~]# rpm -qa | grep -i uuid
libuuid-2.32.1-1.fc29.x86_64
libuuid-devel-2.32.1-1.fc29.x86_64
[root@bug5831 ~]# 

```

**Comment by paulkatsoulakis** [comment]
That is extremely weird, i only got one reproduce of this.
We may be looking at a sporadic packager failure that didn't install the package, thus resulted in the installation failure.

I will try to reproduce it, but if you have the overall execution log @MichaelRiss would be really useful.

**Comment by paulkatsoulakis** [comment]
Just for the sake of clarity, when running on fedora 29, the kickstart prompts me to get all necessary packages:

```
[root@test-bug5831 ~]# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version: 
 --- Downloading script to detect required packages... --- 
$'[\E[2m/tmp/netdata-kickstart-FkQ86M\E(B\E[0m]# \E[1m\E[33m' curl -sSL --connect-timeout 10 --retry 3 https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh $'\E(B\E[0m\\n'  OK  curl -sSL --connect-timeout 10 --retry 3 https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh 

 --- Running downloaded script to detect required packages... --- 
$'[\E[2m/tmp/netdata-kickstart-FkQ86M\E(B\E[0m]# \E[1m\E[33m' /usr/bin/bash /tmp/netdata-kickstart-FkQ86M/install-required-packages.sh netdata $'\E(B\E[0m\\n' Loading /etc/os-release ...

/etc/os-release information:
NAME            : Fedora
VERSION         : 29 (Cloud Edition)
ID              : fedora
ID_LIKE         : 
VERSION_ID      : 29

We detected these:
Distribution    : fedora
Version         : 29
Codename        : 29 (Cloud Edition)
Package Manager : install_dnf
Packages Tree   : rhel
Detection Method: /etc/os-release
Default Python v: 2 

 > Checking if package 'git' is installed...
 > Checking if package 'gcc' is installed...
 > Checking if package 'make' is installed...
 > Checking if package 'autoconf' is installed...
 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'autogen' is installed...
 > Checking if package 'automake' is installed...
 > Checking if package 'pkgconfig' is installed...
 > Checking if package 'nmap-ncat' is installed...
 > Checking if package 'zlib-devel' is installed...
 > Checking if package 'libuuid-devel' is installed...
 > Checking if package 'libmnl-devel' is installed...
 > Checking if package 'python' is installed...
 > Checking if package 'PyYAML' is installed...
 > Checking if package 'python-pymongo' is installed...

The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   dnf update  

dnf install PyYAML autoconf autoconf-archive autogen automake gcc git libmnl-devel libuuid-devel make nmap-ncat pkgconfig python python-pymongo zlib-devel 


Press ENTER to run it > 
```
So for sure we are not looking at an issue at the part of determining the required packages.

**Comment by paulkatsoulakis** [comment]
> Hi @MichaelRiss, thanks for your report.
> Could you share the following information from the offending machine?
> 1)`cat /etc/os-release`
> 2)`uname -a`
> 3) `rpm -qa`

I 'll need this information to go through a few more checks

**Comment by MichaelRiss** [comment]
Hi @paulkatsoulakis,
here is the requested information:
1. `cat /etc/os-release`:
```
NAME=Fedora
VERSION="30 (MATE-Compiz)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (MATE-Compiz)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="MATE-Compiz"
VARIANT_ID=matecompiz
```

2. `uname -a`:
```
Linux XXX 5.0.7-300.fc30.x86_64 #1 SMP Mon Apr 8 18:28:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

3. `rpm -qa`:
I add this as attachement to not spam the conversation: 
[package_list.txt](https://github.com/netdata/netdata/files/3068497/package_list.txt)

**Comment by MichaelRiss** [comment]
I would like to point out, that the problems I mentioned affect Fedora 30 and I see you trying to confirm these problems on a Fedora 29. You wont be able to confirm the problems this way as they result from the changes that happened between Fedora 29 and Fedora 30.
Also, I understand when you don't want to get into supporting pre-release distributions as things can change until the final release. That could for example be the case with the missing `libuuid-devel`, they might decide to include it in the final default installation. But that Fedora wants to phase out python2 packages is something that is a declared goal for Fedora 30 and I believe this wont change anymore.
So, you may see this as an upfront information before the distribution gets into the final state.

**Comment by paulkatsoulakis** [comment]
Hi @MichaelRiss, i know that i did not perform the test on Fedora 30.
I only used Fedora 29 because that was the machine i have at hand for the moment for fedora distribution.

So i used a brand new installation of fedora 29, that did not have libuuid-devel installed.
Running the installer ended up in a successful installation, including the install of libuuid-devel package.

Coming back to version 30, I think Fedora 30 does not differentiate our installation process.
We check the ID field from /etc/os-release to decide a few things for the packages to install and that does not change between 29 and 30 in fedora from what i see.

Could you provide me the log from the failed install?

**Comment by MichaelRiss** [comment]
Here is the log: 
[netdata-install-log.txt](https://github.com/netdata/netdata/files/3069103/netdata-install-log.txt)

**Comment by paulkatsoulakis** [comment]
This is interesting, thanks @MichaelRiss i 'm working on it

**Comment by paulkatsoulakis** [comment]
Hi @MichaelRiss, sorry for the late reply but it has been busy times that kept me a bit behind on user issues, my apologies for that.

So, i tried the installation with fedora 30, because as you correctly pointed out some packages are being deprecated and our installer seems to fail in this case.

The fixes i see on this matter are the following:
1. I will be adding the `--setopt=strict=0` flag on dnf execution, so that the whole dnf installation does not fail if one package is broken. If you look at the log file closely, it is the py-mongo package that is breaking the whole process, resulting on not installing any of the packages required. This flag fixes that.

2. On top of that, we have #5632 with a fix on the way, to make the installer not to install pymongo by default, which also reduces the noise.

I hope this helps, i am preparing the PR for 1. and will push for merging of both issues.
