### ISSUE TITLE
Disable disk backlog by UUID

### ISSUE THREAD

**Issue by 0x3333** [netdata/netdata#5841]
I have some USB Disks attached/detached to my host to do some backups, when those backups run, the disk backlog is increased, generating an alarm that is cleared after the backup has finished.

The USB Disks are primarily getting /dev/sda, but sometimes, it can be something else. I don't want to disable the alarm for /dev/sda, as the disk could get some other node name, and I'd ignore the wrong disk.

Is that possible to ignore the disks by UUID?

**Comment by vlvkobal** [comment]
You can disable disks by ID using these options:
```
[plugin:proc:/proc/diskstats] 
# name disks by id = no
# preferred disk ids = *
# exclude disks = loop* ram*
```
Look at the [documentation](https://docs.netdata.cloud/collectors/proc.plugin/#disk-names).

**Comment by 0x3333** [comment]
Yeah, I read that, but I'd like to know if is that possible to *ignore* by UUID only. I don't want all my disks to be identified by UUID, which is less intuitive. But I don't believe so.
