### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#5842]
##### Question summary
Yesterday while I was talking with Christopher he gave me a new issue to work(https://github.com/netdata/netdata/issues/2637 ), while I was reading the issue I saw that there was the possibility to move the software for Microsoft Windows too. I have experience to develop for Microsoft since 1997, but I do not touch Windows since 2015. The time far from it is not a problem, but what we wanna develop can be a problem case we do not use the correct tool. I remember that since Windows Vista, we did not have the possibility to write a windows driver using the mingw(https://mingw-w64.org/doku.php ), pay attention for an important fact, I did not need to write windows driver after 2006, but any other software could be done without any problem, at least I did not have any problem.
##### OS / Environment
Considering that we are not using drivers/module yet, do you have any objection with this compiler?
I think the mingw will help us more, because we will not change the compiler, for example, see a little piece of code from a DLL/shared library that I developed for Linux and Windows in the past:

#if !defined(_WIN32) && !defined(_WIN64)
PGresult *fs_set_timezone(PGconn *conn)
#else
PGresult __stdcall *fs_set_timezone(PGconn *conn)
#endif

As you can see I used the same logic that we use to say for the compiler what is for an OS or other. 
##### Expected results
I expect an "easily" migration of the codes to microsoft using mingw, because we will continue using gcc.

**Comment by mfundul** [comment]
No objections for mingw from me.

**Comment by thiagoftsm** [comment]
Only a small information, yesterday when I tried to compile the Netdata using mingw, it gave me the following error

configure: error: Cannot initialize pthread environment

, I think this problem will completely solved when I finish the migration for libuv to solve the issue (https://github.com/netdata/netdata/issues/2637 ), so I did not expand time to fix this problem.

**Comment by cakrit** [comment]
Let's close this and pick thing up again when we move with the implementaion.
