### ISSUE TITLE
Is there a way to disable Web Notifications

### ISSUE THREAD

**Issue by keith-mojo** [netdata/netdata#5843]
I would like to disable Web Notifications so I don't get the prompt to allow notifications on every netdata instance I have installed.

![chrome_2019-04-11_10-52-54](https://user-images.githubusercontent.com/36464384/55967637-a361b100-5c48-11e9-8b52-1554c0e5bd51.png)

How can I disable this?

**Comment by ilyam8** [comment]
I think there is no way to disable them, am i right @gmosx ?

**Comment by cakrit** [comment]
I found a solution. Follow the instructions [here](https://docs.netdata.cloud/web/#customizing-the-standard-dashboards) and add to your custom dashboard js the line `netdataShowAlarms = false;`

**Comment by cakrit** [comment]
I'm closing, let us know if you have additional questions. I tested this and it works for me. Of course you can also disable or enable notifications from your browser's settings. The solution above will prevent netdata from asking but also, never inform you of alarms via browser notifications.

**Comment by ilyam8** [comment]
> so I don't get the prompt to allow notifications on every netdata instance I have installed

Custom dashboard is not a solution.

**Comment by ilyam8** [comment]
@keith-mojo 	

![Screenshot_20190528_134834](https://user-images.githubusercontent.com/22274335/58472611-4e71ef80-814f-11e9-951e-757efd390460.png)


but keep in mind

> The solution above will prevent netdata from asking but also, never inform you of alarms via browser notifications.
