### ISSUE TITLE
swapio chart is missing on CentOS 7

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#5845]
##### Bug report summary
swapio chart is missing on CentOS 7

##### OS / Environment
```bash
$ uname -a
Linux ***** 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

##### Netdata version (ouput of `netdata -V`)
netdata v1.12.2, v1.13.0 (static binary)

##### Component Name
proc

##### Steps To Reproduce
install netdata on centos 7 and check web UI

##### Expected behavior
system swap should have swapio chart

##### Note

if the system start to use swap, swapio chart become available.

**Comment by vlvkobal** [comment]
If both of the metrics `in` and `out` are zero, then the swapio chart is not shown. You can change the configuration to always show the chart:
```
[plugin:proc:/proc/vmstat]
	swap i/o = yes
```

**Comment by Wing924** [comment]
@vlvkobal I think it's not desired.

1. We should not hide a chart only if all values are zero. There are no does suggest swapio is hidden by default if the values are zero.

2. Even if the chart is hidden, backed should report zero or we can't tell if it's zero or missing.
Currently, prometheus backend don't report swapio metrics if they are zero.

**Comment by vlvkobal** [comment]
> There are no docs suggest swapio is hidden by default if the values are zero.

There is at least one. Look at [this one](https://docs.netdata.cloud/collectors/proc.plugin/#performance-metrics).

You can have zero metrics reported by setting the correspondent option to `yes` instead of `auto` for any chart you need.

Having these metrics displayed by default is just a matter of changing the default values in the configuration file, though the usefulness of this approach is disputable.

**Comment by ilyam8** [comment]
I dont like `zero = do not show` approach either. I find it very confusing. Zero is a value.

**Comment by cakrit** [comment]
This shouldn't be closed. At the very minimum, we need to document the behavior better (i.e. not just in a single collector). If I understand correctly, the info from https://github.com/netdata/netdata/issues/5845#issuecomment-482786305 needs to go [here](https://docs.netdata.cloud/daemon/config/#per-chart-configuration). We can probably also add a paragraph [here](https://docs.netdata.cloud/docs/configuration-guide/#how-to).

As for a fix: How about a global configuration option in `netdata.conf` that modifies this behavior overall? e.g. `hide charts with zero values = yes/no`

**Comment by ilyam8** [comment]
> hide charts with zero values

In my opinion this is very confusing, zero value is a value and lack of chart looks like a bug for a user. 

So i'd say global is ok but should be `off` by default. 

Do we really need to hide charts with zero values?

**Comment by utdrmac** [comment]
Glad I searched for this. Affects `netdata v1.14.0-64-g110797a6` as well running inside docker. I couldn't figure out why swap charts were not being displayed.

**Comment by ilyam8** [comment]
This is quite a qick fix, at least for swap chart. `global` thing can be implemented later. @vlvkobal 	please
