### ISSUE TITLE
fping host removed, but alarm and entry is still shown

### ISSUE THREAD

**Issue by FieldOfRice** [netdata/netdata#5847]
##### Question summary

I have removed some names from the fping hosts variable, because i do not want them to be checked any more. After a restart of netdata they are still shown inside the Browser and alarms are also shown. How could that now unwanted alarms and entries be removed?

##### OS / Environment

Ubuntu Linux  4.4.0-93-generic 

##### Expected results

The former hostnames, which are no longer inside the hosts variable of fping.conf, should no longer be seen, neither as alarm nor inside the browser.

**Comment by ilyam8** [comment]
Hi @FieldOfRice 

> The former hostnames, which are no longer inside the hosts variable of fping.conf, should no longer be seen

That is just the way it is.

___

What i did:
 - copied fping.conf 
 > test@debian9:/opt/netdata/etc/netdata$ sudo ./edit-config fping.conf
 - added 8.8.8.8 and 8.8.4.4 to hosts
 - restarted netdata service

I see both of them on the dashboard.

 - removed 8.8.4.4 from the hosts
 - restarted netdata service

I no longer see 8.8.4.4 on the dashboard

**Comment by FieldOfRice** [comment]
Hi @ilyam8 

as i wrote after a restart of netdata the hostnames are still there.
I followed the comment inside fping.conf and added something into fping.conf hosts variable:
hosts="alpha.fritz.box" and edited /etc/hosts added 192.168.178.88 alpha.fritz.box.
That host exists and has that address. It worked as expected, but that host has too often alarms, because it goes into deep sleep and then the fping doesn't get an answer. Long story short: I do not longer want to check that host thru fping. Therefore i removed alpha.fritz.box from hosts variable.

This is what i did to get them removed:
- stop netdata at host1, which streams to host2.
- stop netdata at host2, which receives stream from host1.
- rm -rf /var/cache/netdata/fping*alpha* at host1
- rm -rf /var/cache/netdata/fping*alpha* at host2
- start netdata at host2
- start netdata at host1

Now the former used hostnames are gone, and only those inside fping.conf are seen.

**Comment by ilyam8** [comment]
oh, there are no details about streaming,etc. in the OP 😄
