### ISSUE TITLE
Missing python.d/sslcheck module

### ISSUE THREAD

**Issue by astorath** [netdata/netdata#5852]
##### Bug report summary
Tried to use new python.d/sslcheck module #5365 , but it seems to be missing from plugin configuration at all.

##### OS / Environment
- CentOS 7
- Ubuntu 18.04

##### Netdata version (ouput of `netdata -V`)
- netdata v1.13.0
- netdata v1.14.0-rc0

##### Component Name
python.d/sslcheck

##### Steps To Reproduce
- run `edit-config python.d.conf`: no sslcheck option in module list
- run `edit-config`: no sslcheck module listed
- run `edit-config python.d/sslcheck.conf`:
```
File 'python.d/sslcheck.conf' is not found in '/opt/netdata/usr/lib/netdata/conf.d'
```
- run `edit-config python.d/sslcheck/sslcheck.conf`:
```
File 'python.d/sslcheck/sslcheck.conf' is not found in '/opt/netdata/usr/lib/netdata/conf.d'
```
##### Expected behavior

Module should be present in python.d.conf and it's config available via `edit-config python.d/sslcheck.conf`

**Comment by ilyam8** [comment]
Hi @astorath 
The module was removed
Check this https://github.com/netdata/netdata/issues/5631
