### ISSUE TITLE
Connection Tracker no data/error ?

### ISSUE THREAD

**Issue by Hostile** [netdata/netdata#5854]
Hi, im new to netdata, installed and out of the box works pretty cool. Changed to 24h collection data.

It dosent shows anything in Connection Tracker and there is some error I think, how to fix it ?

http://nodesx.com:19999/#menu_netfilter_submenu_conntrack;after=1555074396000;before=1555074875000;theme=slate

Thanks

**Comment by vlvkobal** [comment]
I don't understand what is the problem. You have two connections in the chart. Could you elaborate on the issue?
