### ISSUE TITLE
how to keep netdata plugin alive without get disabled after 60 no data return?

### ISSUE THREAD

**Issue by lwchan2k1** [netdata/netdata#5857]
I have a netdata python plugin which got disabled/stopped after 60 no data collection return. How can we prevent that? or is there a way / config to keep the plugin alive?

Thanks,
Lewis

**Comment by ilyam8** [comment]
Hi @lwchan2k1 

Are you talking about python modules? If yes please update to the latest, this will do. Current version doesn't disable collectors.

**Comment by lwchan2k1** [comment]
Ok, thanks. I am running v1.11.1_rolling

**Comment by ilyam8** [comment]
Ok, then you have to options:
 - update to the latest
 - set `retries` option for job to something high (default is 60)

i highly recommend option 1

**Comment by lwchan2k1** [comment]
Thanks for the options!!

**Comment by lwchan2k1** [comment]
one more question, will autodetection_retry also bring the stopped plugin back to live?

**Comment by ilyam8** [comment]
No, it serves another purpose.

https://github.com/netdata/netdata/blob/1d304ecdc34ce4ca42428992751055663403d095/collectors/python.d.plugin/apache/apache.conf#L34-L38
