### ISSUE TITLE
Follow up adjustment of plugin permissions

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#5858]
##### Bug report summary
Following up the discussion on #5586, We realised that we need to make an adjustment so that default plugins permission gets reduced to 0750

After the change the permissions will look like this:
```
[root@d28c32151328 plugins.d]# ls -ltr *plugin
-rwxr-x--- 1 root netdata    19123 Apr 12 15:11 charts.d.plugin
-rwxr-x--- 1 root netdata     5516 Apr 12 15:11 fping.plugin
-rwxr-x--- 1 root netdata    11060 Apr 12 15:11 node.d.plugin
-rwxr-x--- 1 root netdata    21336 Apr 12 15:11 python.d.plugin
-rwsr-x--- 1 root netdata    89976 Apr 12 15:11 apps.plugin
-rwxr-x--- 1 root netdata 14818313 Apr 12 15:11 go.d.plugin
[root@d28c32151328 plugins.d]# 
```

Reasoning on this change:

We don't want broad permissions to the plugins in general.
Only people with authoritative access should have permission to run this plugin for any reason
We always run with a user that has either user or group permissions, so no need for "other" permissions. When we run as root, we establish the netdata:netdata (or root when netdata not possible) and when we run as simple user we have user/group to the user's user/group information so netdata should not be affected by this change. Also the users won't be affected. When i am root, i am authorized to execute the plugin and when i have installed as simple user i again have permissions

##### OS / Environment
latest

##### Netdata version (ouput of `netdata -V`)
latest

##### Component Name
netdata/packaging/installer

##### Steps To Reproduce
Run the installer

##### Expected behavior
We should have the same permissions for all plugins on the plugins dir

**Comment by cakrit** [comment]
Correcting above statements. We still need elevated permissions for certain plugins that need to run as root via setuid (e.g. freeipmi.plugin and apps.plugin). The plugins listed here are indeed to be modified to 750.

**Comment by Wing924** [comment]
we need to provide a way to get all plugins version by normal user or bug report may br a problem.

**Comment by paulkatsoulakis** [comment]
> we need to provide a way to get all plugins version by normal user or bug report may br a problem.

Given the elevated rights the plugins usually have, the user should either be authorised to use sudo to execute the plugins or alternatively to belong to the netdata group to be able to execute.
