### ISSUE TITLE
How do i get rid of my mounted volumes?

### ISSUE THREAD

**Issue by Toontje** [netdata/netdata#5862]
I'm using netdata on MacOS and under Disks i see all my ever mounted volumes being monitored. How do i remove those?

<img width="223" alt="Screenshot 2019-04-13 at 10 07 44" src="https://user-images.githubusercontent.com/4884243/56076706-5c082b80-5dd4-11e9-8984-ce5804dceaa6.png">

**Comment by vlvkobal** [comment]
Do you see them after restarting netdata?

**Comment by Toontje** [comment]
After restarting netdata the volumes are gone.
