### ISSUE TITLE
Clearer communiation of  telemetry

### ISSUE THREAD

**Issue by JonasDralle** [netdata/netdata#5863]
Hi. I have installed netdata on various machines now and while a `--out-out-from-anonymous-statistics ALL` cli option exists and it's in the doc it's sort of ill-communicated in my opinion.

The website and doc push people to "just install and see for yourself" and thus encourage to do just that. At no point in time the installer mentions telemetry or the option to opt out.
The installer echos `/usr/bin/install -c anonymous-statistics.sh '/usr/libexec/netdata/plugins.d` in the setup process.

I feel like the installer should interactively ask weather google et al should be spying their VMs or not.

**Comment by Ferroin** [comment]
@cakrit While I agree with the reasoning for keeping it as an opt-out mechanism, I also agree that it could be better pointed out to users.  Possible locations that should _probably_ mention it and link to the docs, but don't appear to currently include:

* The main README.md file.
* The installer documentation.
* The `kickstart.sh` and `kickstart-static64.sh` scripts (I don't theink they should stop and wait for user input or anything, but they really should mention it).

**Comment by JonasDralle** [comment]
> The kickstart.sh and kickstart-static64.sh scripts (I don't theink they should stop and wait for user input or anything, but they really should mention it).

for example by printing

```
# TELEMETRY ENABLED                                               #
# to opt out run with --out-out-from-anonymous-statistics instead #
```

Google Analytics is an especially nasty as a tracker. Were alternatives considered? e. g. Matomo, the open source self-hostable tracker.

**Comment by JonasDralle** [comment]
> but we have chosen to use an opt-out mechanism.

Maybe you want to adjust this typo. There's no "opt-out". An out-out of data transmission would be illegal since 2016. Refer to [GDPR Article 6](https://gdpr-info.eu/art-6-gdpr/) [and 7](https://gdpr-info.eu/art-7-gdpr/).

**Comment by cakrit** [comment]
GDPR does not apply. No personal data is transmitted or processed. I will take a look at Matomo, I'm not very happy with GA myself.

**Comment by JonasDralle** [comment]
That is correct. Yet GDPR might apply to someone who's using netdata (e. g. companies).

**Comment by cakrit** [comment]
I still don't see the relevance. All companies need to comply with GDPR. However, the GDPR rules apply to processes that handle personal data. For example, the netdata `apps` plugin uses actual system usernames for some metric names (look at user.cpu). The processing and storage of this particular data set is governed by GDPR, so sysadmins would need to take into account the relevant regulation. On the other hand, the data in the anonymous usage statistics (telemetry) process do not contain information that can be used to identify anyone. So GDPR is not applicable to the particular process.

**Comment by cakrit** [comment]
I tried to add Matomo, but hit a major blocker with the limitation of 10 active custom dimensions at any given time (using both visit and action custom dimensions). Combined with the fact that it only allows for a 16-char  unique visitor ID (_id), it's a no go, unfortunately. 

Getting on with the documentation changes.

**Comment by JonasDralle** [comment]
Thanks so much :raised_hands:.
I especially like the notification line of the installer

**Comment by cakrit** [comment]
I had to move it up a bit and make the message more uniform with the other messages, see #6127.
