### ISSUE TITLE
pattern for nginx error log

### ISSUE THREAD

**Issue by hamzash9500** [netdata/netdata#5867]
Hi all,
can anyone help me to find the pattern for this log:

2019/04/15 07:40:34 [error] 23947#23947: *69867 connect() failed (111: Connection refused) while connecting to upstream,client: x.x.x.x,server: <domin such as x-dev.cloud.com>,request: "GET /favicon.ico HTTP/1.1",upstream: "https://x.x.x.x:6000/favicon.ico",host: "domain such as x-dev.cloud.com",referrer: "https://domain such as x-dev.cloud.com/"

I need the pattern to monitor nginx error.log

Thanks in advance.

**Comment by ilyam8** [comment]
Hi @hamzash9500 

what do you want to monitor? In what parts of this logline are you interested in?

**Comment by hamzash9500** [comment]
Hi @ilyam8 
i need monitor error ,the part i interested about  "Connection refused"

**Comment by hamzash9500** [comment]
@ilyam8 ??

**Comment by ilyam8** [comment]
it seems you need custom plugin. I still don't understand what do you need to monitor. What do you want to see on charts?

**Comment by gevorgkhachatryan** [comment]
Hi all , 
For example , from my nginx error log , I want to monitor uris . How can I get it with web_log conf ? Now I have monitor which is getting all my uris from access log , but I can't get them from error.log.
Any ideas ?

**Comment by gevorgkhachatryan** [comment]
Here is the example from my error.log 
```2019/04/19 17:40:32 [error] 31285#0: *352763511 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: x.x.x.x , request: "x.x.x.x", upstream: "x.x.x.x ", host: "x.x.x.x"```

From logline I need `request` part .

**Comment by ilyam8** [comment]
Sorry for long delay guys

@gevorgkhachatryan 	

> From logline I need request part 

What do you mean by `need request part` ? 

> 2019/04/19 17:40:32 [error] 31285#0: *352763511 upstream timed out (110: Connection timed out) while reading response header from upstream, client: x.x.x.x, server: x.x.x.x , request: "x.x.x.x", upstream: "x.x.x.x ", host: "x.x.x.x"

1. match only log lines with `Connection timed out`
2. parse `request part`
...
?

Whats next? What do you want to see on charts?
