### ISSUE TITLE
netdata cannot run any longer because the server is out of memory. How can i clear the data?

### ISSUE THREAD

**Issue by makutamatey** [netdata/netdata#5871]

**Comment by paulkatsoulakis** [comment]
Hi @makutamatey,
   Could you provide us with more detail please?

1. Server specs: 
    a) Hardware details like like cpu, disk, ram
    b) What software is running on that server
    c) Netdata version?

2. Provide us with netdata.conf and contents of /etc/netdata/.environment (Remember to exclude any sensitive information from both files) 

3. What was the server's memory foot print at the time of the outage? The output of `ps afux` or `ps -ef` should provide us some first insights

4. Can you clarify what do you mean by `netdata cannot run any longer`? It crashes? It fails to start? It stops? What exactly happens and what do you see on netdata's error log at /var/log/netdata/error.log?

Once we get this information to gain some insights on the system's status, before we can answer you.

Thanks!

**Comment by makutamatey** [comment]
I am running it on AWS t2.micro instance(0.5GiB, 1vCPU, 6 CPU credits/hr, EBS-only storage)
I was not running any app at that moment, but I set the netdata history at 2days
the netdata version is v1.14.0-rc0-54-nightly and OS is Ubuntu 18.04.2 LTS
thank you

**Comment by makutamatey** [comment]
Yh the netdata dashboard could no longer load or display the chart and when I viewed the logs, I realized I was out of memory.

**Comment by cakrit** [comment]
So you just reduce the history, or disable some collectors. You can read [this](https://docs.netdata.cloud/database/) and [this](https://docs.netdata.cloud/docs/performance/#running-netdata-in-embedded-devices)

**Comment by makutamatey** [comment]
Thank you. but one more issue. I have changed the IP of my master  and updated the slave with the new IP and even restarted it. But the slave is still making effort to send data to the old IP which causes it to time out. Please how can I get the slave to detect the new IP?

**Comment by cakrit** [comment]
Check where you made the change. Did you modify the `destination` on the correct `stream.conf, i.e. the one in the user configuration directory `/etc/netdata`? If so, a restart will use it. If it's in the stock configuration directory, it will ignore it, because the user config takes precedence. A restart is all you need on the slave.

Suggestion: Use host names even if it means putting entries in `/etc/hosts`. It will simplify your life.

**Comment by makutamatey** [comment]
Thank you. the slave has now recognized the new IP after several hours. Thank you so so much. You have been awesome. I will try the host names and get back to you.

**Comment by makutamatey** [comment]
my master netdata has now being hosted on AWS t3.small (2GB)and it is configured to retain data for an hour. The 3 slaves also retain data for an hour, but the master keep running out of memory. Does netdata delete data from the the database and log files after the specified hours or still keep them. Can you explain to me why master keeps running out of memory and keeps crashing? Thank you.

**Comment by makutamatey** [comment]
ERROR 405: Cannot download charts index from server: http://xxxxxxxx:19999/api/v1/charts

**Comment by makutamatey** [comment]
netdata INFO  : PLUGINSD[python.d] : called DISABLE. Disabling it.
netdata ERROR : PLUGINSD[python.d] : '/usr/libexec/netdata/plugins.d/python.d.plugin' (pid 19120) disconnected after 0 successful data collections (ENDs).
 netdata ERROR : PLUGINSD[python.d] : child pid 19120 killed by signal 15.

**Comment by makutamatey** [comment]
please i want to where the master does not display nodes even though the slave does

slave 
![slave node](https://user-images.githubusercontent.com/44055180/56383152-b48e5d00-6208-11e9-9d6e-b2c49ceda123.PNG)

master 
![netdata](https://user-images.githubusercontent.com/44055180/56383158-bd7f2e80-6208-11e9-95f2-536c5dcd1572.PNG)
 
Again how can I customize the name of my database.  Thank you for helping me make a lot of progress

**Comment by makutamatey** [comment]
> So you just reduce the history, or disable some collectors. You can read [this](https://docs.netdata.cloud/database/) and [this](https://docs.netdata.cloud/docs/performance/#running-netdata-in-embedded-devices)

Please Isn't netdata supposed to delete the data from the database after the set history. For instance, If my history is set to 7200 is netdata not supposed to delete the data stored after 7200s?

**Comment by makutamatey** [comment]
I have changed the hostname under under the [global] section instead of the registry section and it appears on the master. Thank you once again.

**Comment by ilyam8** [comment]
> Please Isn't netdata supposed to delete the data from the database after the set history.

Netdata resuses same *.db file.

https://docs.netdata.cloud/database/#database
