### ISSUE TITLE
Master not streaming from slave

### ISSUE THREAD

**Issue by makutamatey** [netdata/netdata#5873]
My master is configured to stream data from the slave but it is not streaming because CONFIG: cannot load user config '/etc/netdata/stream.conf. Again how will i know if master is streaming data from slave. how are the slaves represented on master?

**Comment by cakrit** [comment]
You need to either copy the stock configuration file (unconfigured stream.conf) to /etc/netdata and edit it there, or use `/etc/netdata/edit-config stream.conf`, which does the copying for you.

It's actually the slaves that push data to the master. You can grep `/var/log/netdata/error.log` for `STREAM` and you'll see the messages that tell you if there is a problem. 

When you have it correctly set up, you'll see something like the following:

![Screenshot from 2019-04-17 09-18-34](https://user-images.githubusercontent.com/43294513/56268943-d1d10780-60f2-11e9-8ed8-60e3d6019bde.png)

In this case, the slave "fedora" streams its metrics to the master "chris-msi"

**Comment by makutamatey** [comment]
Thanks you.
