### ISSUE TITLE
Disable login on master dashboard

### ISSUE THREAD

**Issue by roedie** [netdata/netdata#5881]
##### Question summary
I've just upgraded to Netdata 1.12.1 and when I want to view other nodes on my master node I need to sign in to netdata.cloud. Is there any way to disable this?

I just want to be able to browse my nodes without signing in everytime.

##### OS / Environment
Debian 9.8 with netdata 1.12.1

**Comment by cakrit** [comment]
Unfortunately, this is how we ensure no URLs/Hostnames are sent by default to the netdata registry (now also the netdata cloud). Your alternative is to [run your own registry](https://docs.netdata.cloud/registry/#run-your-own-registry).
