### ISSUE TITLE
feature: mongodb collector add ssl connection support

### ISSUE THREAD

**Issue by mlyborg** [netdata/netdata#5884]
##### Feature idea summary
Allow SelfSigned Certs with pymongo:
import ssl
    def _create_connection(self):
        conn_vars = {'host': self.host, 'port': self.port, 'ssl':True, 'ssl_cert_reqs': ssl.CERT_NONE}
        if hasattr(MongoClient, 'server_selection_timeout'):
            conn_vars.update({'serverselectiontimeoutms': self.timeout})
##### Expected behavior
/etc/netdata/python.d/mongodb.conf
ssl : 'yes'
sslNoVerify: 'yes'

**Comment by ilyam8** [comment]
https://api.mongodb.com/python/3.3.0/examples/tls.html

> These options can also be passed as part of the MongoDB URI.

+ URI support
