### ISSUE TITLE
Netdata via nginx

### ISSUE THREAD

**Issue by manosmustang** [netdata/netdata#5886]
Hi,

it is the first time that I am using nginx.

Kibana is already running on the server with the below config 172.27.52.48.conf

server {
    listen 80;
    server_name 172.27.52.48;

    auth_basic "Restricted Access";
    auth_basic_user_file /etc/nginx/htpasswd.users;

    location / {
        proxy_pass http://localhost:5601;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

----------------------------------------------------------------------------------------
I want to run netdata under 172.27.52.48/netdata
so the below config created  netdata.conf

upstream netdata {
    server 127.0.0.1:19999;
    keepalive 64;
}

server {
   listen 80;

   location = /netdata {
        return 301 /netdata/;
   }

   location ~ /netdata/(?<ndpath>.*) {
        proxy_redirect off;
        proxy_set_header Host $host;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://netdata/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
}
--------------------------------------------------------------------------------

but when i hit the http://172.27.52.48/netdata i receive the below error

{"statusCode":404,"error":"Not Found","message":"Not Found"}

from the logs I get

2019/04/18 11:14:36 [error] 18943#0: *85 connect() failed (111: Connection refused) while connecting to upstream, client: 10.66.8.182, server: 172.27.52.48, request: "GET /netdata HTTP/1.1", upstream: "http://[::1]:5601/netdata", host: "172.27.52.48"

Any help please?

Thank you so much in advance

**Comment by modem7** [comment]
This is my working config: 

upstream backend {
    # the netdata server
    server <ip>:<port>;
    keepalive 64;
}

server {

    if ($request_method !~ ^(GET|HEAD|POST)$) {
   return 444;
}

    # nginx listens to this

    # the virtual host name of this
    server_name netdata.mydomain.com;

    error_log /var/log/nginx/netdata.myiphost.com.error.log;
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate <path>/fullchain.pem; # managed by Certbot
    ssl_certificate_key <path>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam <path>/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = netdata.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name netdata.mydomain.com;
    return 404; # managed by Certbot


}

**Comment by ilyam8** [comment]
looks related
https://github.com/netdata/netdata/issues/1346#issuecomment-266216167

**Comment by cakrit** [comment]
@ilyam8 is right. If you use a subdirectory (e.g. http://hostname/netdata) then you need the rewrite rule in that issue.

**Comment by manosmustang** [comment]
Hi,

ok. I made progress. you were right about rewriting the rule

server {
    listen 80;

    server_name 172.27.52.33;

    auth_basic "Restricted Access";
    auth_basic_user_file /etc/nginx/htpasswd.users;

    location / {
        proxy_pass http://localhost:5601;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

 location /netdata {
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_pass_request_headers on;
    proxy_set_header Connection "keep-alive";
    proxy_store off;
    rewrite ^/netdata(/.*)$ $1 break;
    proxy_pass http://127.0.0.1:19999/;

    gzip on;
    gzip_proxied any;
    gzip_types *;
 }


}


but now when I successfully open the URL I get the below 

![nginx](https://user-images.githubusercontent.com/15198539/56948704-9d6d3a80-6b39-11e9-9a83-947e6d54fbd8.JPG)


javascript is enabled in the browser

thank you again

**Comment by ilyam8** [comment]
ok, i tested it, it works for me

I think versions don't matter but still
 - debian 9.8
 - nginx version: nginx/1.10.3

i added to the default config following section:

```nginx
         location /netdata/ {
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_http_version 1.1;
                proxy_pass_request_headers on;
                proxy_set_header Connection "keep-alive";
                proxy_store off;

                gzip on;
                gzip_proxied any;
                gzip_types *;

                rewrite ^/netdata(/.*)$ $1 break;
                proxy_pass http://localhost:19999;
         }
```

![Screenshot_20190430_113941](https://user-images.githubusercontent.com/22274335/56949852-ae6b7b00-6b3c-11e9-90a8-8602ea3f9bc4.png)

**Comment by cakrit** [comment]
Please open your browser's console, put a breakpoint on L524 of `dashboard.js` and tell us the value of `s`. It should be something like `http://172.27.52.33/netdata/dashboard.js?v20190130-1`.

Also check the browser console for any other errors, that can help identify the cause.

**Comment by manosmustang** [comment]
hi cakrit,

![image](https://user-images.githubusercontent.com/15198539/56952753-b37ff880-6b43-11e9-961e-976cff8ebdd5.png)

maybe the path is wrong?

**Comment by cakrit** [comment]
I don't get how you can be seeing `index.html` but not anything else. You should have something like the following in the nedata web directory:
```
[christopher@chris-msi netdata]$ ls /usr/share/netdata/web/
console        dashboard.html                    dashboard.js         demo.html        favicon.ico                images            lib       netdata-swagger.json  robots.txt   tv.html
css            dashboard_info_custom_example.js  dashboard.slate.css  demosites2.html  fonts                      index.html        main.css  netdata-swagger.yaml  sitemap.xml  version.txt
dashboard.css  dashboard_info.js                 demo2.html           demosites.html   goto-host-from-alarm.html  infographic.html  main.js   refresh-badges.js     static
```
You can see what your web directory is by going to `http://172.27.52.33/netdata/netdata.conf`. Look for section `[global]`, parameter `web files directory`.

**Comment by manosmustang** [comment]
i think the cause of the problem might be the nginx

what i have done it to put a username & password at nginx for kibana

echo "username:`openssl passwd -password`" | sudo tee -a /etc/nginx/htpasswd.users

so something is wrong there. cause everytime i try to open it from the ip is asking for the username/password and the site has issue. instead from localhost everything is ok

**Comment by manosmustang** [comment]
nop. i removed it and its not that

**Comment by manosmustang** [comment]
fixed!

changed the proxy_pass http://127.0.0.1:19999/;

to proxy_pass http://localhost:19999/;

**Comment by manosmustang** [comment]
so the full configuration is

server {
    listen 80;

    server_name 172.27.52.33;

    #auth_basic "Restricted Access";
    #auth_basic_user_file /etc/nginx/htpasswd.users;

    location / {
    #auth_basic "Restricted Access";
    #auth_basic_user_file /etc/nginx/htpasswd.users;
        proxy_pass http://localhost:5601;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

 location /netdata/ {
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_pass_request_headers on;
    proxy_set_header Connection "keep-alive";
    proxy_store off;
    rewrite ^/netdata(/.*)$ $1 break;
    proxy_pass http://localhost:19999/;

    gzip on;
    gzip_proxied any;
    gzip_types *;
 }


}



thank you all. you can close this thread now!
