### ISSUE TITLE
DEFAULT_RECIPIENT_EMAIL only send to root...

### ISSUE THREAD

**Issue by Anasme** [netdata/netdata#5887]
Hello, thanks for prividing such tool ! it's awesome.

I'm testing the notification and installed postfix to send email, its work but when i try to overwrite configuration with another mail in my health_alarm_notify.conf like this :

> EMAIL_SENDER="'sender@domain.com"
> DEFAULT_RECIPIENT_EMAIL="myname@domain.com"

It's only sending to root... i dont know why, here are the result for alarm-notify test : 

>  netdata@myserver:/etc/netdata$ bash /usr/libexec/netdata/plugins.d/alarm-notify.sh test
> 
> ##### SENDING TEST WARNING ALARM TO ROLE: sysadmin
> 2019-04-18 12:03:02: alarm-notify.sh: INFO: sent email notification for: myserver test.chart.test_alarm is WARNING to 'root'
> ##### OK
> 
> ##### SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
> 2019-04-18 12:03:02: alarm-notify.sh: INFO: sent email notification for: myserver test.chart.test_alarm is CRITICAL to 'root'
> ##### OK
> 
> ##### SENDING TEST CLEAR ALARM TO ROLE: sysadmin
> 2019-04-18 12:03:02: alarm-notify.sh: INFO: sent email notification for: myserver test.chart.test_alarm is CLEAR to 'root'
> ##### OK
> netdata@myserver:/etc/netdata$

- mail.log:

> Apr 18 12:03:02 myserver postfix/pickup[14633]: 3715120446: uid=998 from=<sender@domain.com>
> Apr 18 12:03:02 myserver postfix/cleanup[20410]: 3715120446: message-id=<20190418100302.3715120446@myserver>
> Apr 18 12:03:02 myserver postfix/qmgr[14634]: 3715120446: from=<sender@domain.com>, size=11261, nrcpt=1 (queue active)
> Apr 18 12:03:02 myserver postfix/pickup[14633]: 4642C2044B: uid=998 from=<sender@domain.com>
> Apr 18 12:03:02 myserver postfix/cleanup[20410]: 4642C2044B: message-id=<20190418100302.4642C2044B@myserver>
> Apr 18 12:03:02 myserver postfix/qmgr[14634]: 4642C2044B: from=<sender@domain.com>, size=11359, nrcpt=1 (queue active)
> Apr 18 12:03:02 myserver postfix/pickup[14633]: 550972044E: uid=998 from=<sender@domain.com>
> Apr 18 12:03:02 myserver postfix/cleanup[20410]: 550972044E: message-id=<20190418100302.550972044E@myserver>
> Apr 18 12:03:02 myserver postfix/qmgr[14634]: 550972044E: from=<sender@domain.com>, size=11401, nrcpt=1 (queue active)
> Apr 18 12:03:02 myserver postfix/smtp[20420]: 3715120446: to=<root@domain.com>, orig_to=<root>, relay=mail.gandi.net[217.70.178.9]:587, delay=0.44, delays=0.02/0.03/0.15/0.24, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 87DF820011)
> Apr 18 12:03:02 myserver postfix/qmgr[14634]: 3715120446: removed
> Apr 18 12:03:02 myserver postfix/smtp[20450]: 4642C2044B: to=<root@domain.com>, orig_to=<root>, relay=mail.gandi.net[217.70.178.9]:587, delay=0.51, delays=0.02/0.02/0.15/0.33, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as A114E1BF211)
> Apr 18 12:03:02 myserver postfix/qmgr[14634]: 4642C2044B: removed
> Apr 18 12:03:02 myserver postfix/smtp[20474]: 550972044E: to=<root@domain.com>, orig_to=<root>, relay=mail.gandi.net[217.70.178.9]:587, delay=0.47, delays=0.02/0.02/0.12/0.31, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as AEA692000E)
> Apr 18 12:03:02 myserver postfix/qmgr[14634]: 550972044E: removed

I use gandi to send mail and its work , tell me if u need more info...

Thanks for your future help

**Comment by cakrit** [comment]
please do `grep EMAIL /etc/netdata/health_alarm_notify.conf` and paste here, so we see the entire configuration. root is the default recipient, so there's definitely something wrong with your config file.

**Comment by JamesReynolds** [comment]
Summary - add:
```
role_recipients_email[sysadmin]=
```
to the end of your config to fix this.

I've found the reason for this. If you're modifying `/etc/netdata/health_alarm_notify.conf` (or that file in `NETDATA_USER_CONFIG_DIR`) then those changes are applied _after_ the defaults. ...and the defaults do this:

```
DEFAULT_RECIPIENT_EMAIL=root
role_recipients_email[sysadmin]="${DEFAULT_RECIPIENT_EMAIL}"
```
so if you change `DEFAULT_RECIPIENT_EMAIL` it _won't_ affect the value in `role_recipients_email`.

**Comment by jamgregory** [comment]
I've just encountered this same issue when I suddenly realised I didn't receive an email notification (but was receiving Telegram ones) 🤯

I'm assuming this must have changed at some point as I'm sure it was working before. The documentation suggests setting `DEFAULT_RECIPIENT_EMAIL=` is sufficient, but that's clearly not the case...

**Comment by cakrit** [comment]
@jamgregory does `sendmail` work? It's very easy to debug the notifications, start with https://learn.netdata.cloud/docs/alerts-and-notifications/notifications/agent-alert-notifications/email#prerequisites and try https://learn.netdata.cloud/docs/alerts-and-notifications/notifications/agent-alert-notifications/email#test-the-notification-method

If indeed you see a bug, please create a new bug report, as this specific issue was resolved a long time ago.

**Comment by jamgregory** [comment]
Hey @cakrit 👋

`sendmail` is indeed working, but it seems that I either created or was using an older style ``
