### ISSUE TITLE
Docker image has plugins not executable for netdata user

### ISSUE THREAD

**Issue by Maddimax** [netdata/netdata#5890]
##### Bug report summary
(Some) Plugins in docker image are not executable by netdata user

##### OS / Environment
Docker

##### Netdata version (ouput of `netdata -V`)
netdata v1.14.0-rc0-73-g791fbf19

##### Component Name
Plugins

##### Steps To Reproduce
* Create docker container from netdata/netdata:latest ( sha256:cb431c6babc5aeb7e16ea744cb677ceae5fd71745e63fda183c66b7dbd397a46 )
* Start docker container
* Enter container shell and execute:
```
bash-4.4# ls -lach /usr/libexec/netdata/plugins.d/
total 15032
drwxr-xr-x    1 root     root         548 Apr 18 09:24 .
drwxr-xr-x    1 root     root          62 Apr 18 09:24 ..
-rwxr-xr-x    1 root     root         154 Apr 18 09:24 alarm-email.sh
-rwxr-xr-x    1 root     root       73.6K Apr 18 09:24 alarm-notify.sh
-rwxr-xr-x    1 root     root         301 Apr 18 09:24 alarm-test.sh
-rwxr-xr-x    1 root     root        6.3K Apr 18 09:24 anonymous-statistics.sh
-rwsr-x---    1 root     netdata    99.4K Apr 18 09:24 apps.plugin
-rwxr-xr-x    1 root     root        6.5K Apr 18 09:24 cgroup-name.sh
-rwsr-x---    1 root     netdata    43.3K Apr 18 09:24 cgroup-network
-r-xr-x---    1 root     root        8.0K Apr 18 09:24 cgroup-network-helper.sh
-rwxr-xr-x    1 root     root        1.2K Apr 18 09:24 charts.d.dryrun-helper.sh
-rwxr-x---    1 root     root       18.7K Apr 18 09:24 charts.d.plugin
-rwxr-x---    1 root     root        5.4K Apr 18 09:24 fping.plugin
-rwxr-x---    1 root     root       14.3M Apr 18 09:24 go.d.plugin
-rwxr-xr-x    1 root     root        8.0K Apr 18 09:24 health-cmdapi-test.sh
-rw-r--r--    1 root     root        6.5K Apr 18 09:24 loopsleepms.sh.inc
-rwxr-x---    1 root     root       10.8K Apr 18 09:24 node.d.plugin
-rwxr-x---    1 root     root       20.8K Apr 18 09:24 python.d.plugin
-rwxr-xr-x    1 root     root        7.1K Apr 18 09:24 tc-qos-helper.sh
```
##### Expected behavior
Plugins should be executable by netdata user ?

**Comment by paulkatsoulakis** [comment]
I confirm the findings, it seems that we haven't maintained netdata/netdata image.
I 'm working on it and let you know

**Comment by 8ear** [comment]
Hi @paulkatsoulakis,
I saw your code of https://github.com/paulkatsoulakis/netdata/commit/f3afa1a992843e297f60d043cf4ce30a69aa0972 perhaps I can help.

I used a lot of chmod commands and a colleague showed me a better solution with find:
`find /usr/libexec/netdata/plugins.d/ -not -user netdata -exec chown netdata.netdata {} +`

**Comment by paulkatsoulakis** [comment]
> This search in the path /usr/libexec/netdata/plugins.d/ all folders and files which are not belongs to netdata user and change them. Its a much better way then only chmod.

Good evening @8ear,
  Thanks a lot for your feedback, indeed that is a much more efficient approach. I actually removed the whole chmod set of commands in the referred commit, because it didn't really do the job it was meant to do. Not sure why those chmod got there in the first place. 
  Regarding your recommendation, if you check our [Netdata Installer](https://github.com/paulkatsoulakis/netdata/blob/master/netdata-installer.sh) you will notice we already use such technique, but i really appreciate your input and please do keep it up, because it's the users feedback that helps netdata rock harder!

Cheers
