### ISSUE TITLE
Collect MongoDB sharding metrics

### ISSUE THREAD

**Issue by donets420** [netdata/netdata#5897]
Hi all, I am comparing netdata module for MongoDB and [mongo exporter for prometheus](https://github.com/percona/mongodb_exporter/blob/master/README.md).  

Everythink is available in [netdata](https://docs.netdata.cloud/collectors/python.d.plugin/mongodb/), except MongoDB sharding metrics.

From MongoDB docs - it looks like part of  [mongostat](https://docs.mongodb.com/manual/reference/program/mongostat/), but I am not sure.

So - Could netdata collect MongoDB sharding metrics?

Thanks in advance.

**Comment by ilyam8** [comment]
Hi @donets420 
No, current implementation doesn't collect sharding metrics.

**Comment by ilyam8** [comment]
Wow, a lot of votes :smile:

**Comment by donets420** [comment]
Thanks for answer. I hope it will be implemented soon.

**Comment by cakrit** [comment]
7 votes in a week is a lot indeed. I suggest we plan it for the next sprint, it should be quick. Can anyone suggest stock alarms for the various metrics we'll collect?

**Comment by ilyam8** [comment]
> 7 votes

1 from me :smile: 

>  it should be quick

There was a reason i didn't do it writing the collector - it is not easy.
So no, it won't be quick :smile:

**Comment by donets420** [comment]
> 7 votes in a week is a lot indeed. I suggest we plan it for the next sprint, it should be quick. Can anyone suggest stock alarms for the various metrics we'll collect?

I think it will be great to have the same as [persona exporter](https://github.com/percona/mongodb_exporter):
_MongoDB Sharding metrics (shards, chunks, db/collections, balancer operations)_

**Comment by ilyam8** [comment]
Well, that exporter is great, it is written by Percona folks

> Percona is a recognized expert in MySQL® and MongoDB® open source database software

**Comment by ilyam8** [comment]
Ok, i did some research, i read [percona](https://www.percona.com/) [mongodb exporter](https://github.com/percona/mongodb_exporter) code

The source is trustable

> Percona is a leading provider of unbiased open source database solutions that allow organizations to easily, securely and affordably maintain business agility, minimize risks, and stay competitive.

#### how it works:
 - detecet node type
 - [collect metrics based on node type](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongodb_collector.go#L227-L237)

#### Node types:
 - [`mongod`](https://docs.mongodb.com/manual/reference/program/mongod/)
 - [`mongos`](https://docs.mongodb.com/manual/core/sharded-cluster-query-router/)
 - [`replSet`](https://docs.mongodb.com/manual/tutorial/deploy-replica-set/)

___ 

#### mongod specific metrics:
 - [ServerStatus](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongod/server_status.go#L53-L96) (common + specific)
 - [DatabaseStatList](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongod/database_status.go#L61-L76)
 - [CollectionStatus](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongod/collections_status.go#L75-L112)
 - [TopStatus](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongod/top_counters.go#L47-L67)
 - [IndexUsageStatList](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongod/index_usage.go#L40-L51)

#### mongos specific metrics:
 - [ServerStatus](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongos/server_status.go#L35-L41) (common + specific)
 - [DatabaseStatList](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongos/database_status.go#L67-L96)
 - [CollectionStatList](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongos/collections_status.go#L69-L99)
 - [ShardingStatus](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongos/sharding_status.go#L181-L210):
    - isClusterBalanced
    - isBalancerEnabled
    - shardingChangelogStatus
    - shardingTopologyStatus
    - mongosInfo
    - mongosBalancerLock

#### mongod and mongos common metrics:
```
[ilyam@pc collector]$ grep "commoncollector" -R mongos/* mongod/*
mongos/server_status.go:	commoncollector "github.com/percona/mongodb_exporter/collector/common"
mongos/server_status.go:	commoncollector.ServerStatus `bson:",inline"`
mongod/server_status.go:	commoncollector "github.com/percona/mongodb_exporter/collector/common"
mongod/server_status.go:	commoncollector.ServerStatus `bson:",inline"
```

 - [ServerStatus](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/common/server_status.go#L70-L105)
 - [ConnPoolStats](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/common/conn_pool_stats.go#L61-L68)

#### replSet metrics:
 - [ReplSetConf](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongod/replset_conf.go#L75-L99)
 - [ReplSetStatus](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongod/replset_status.go#L169-L279)
 - [OplogStatus](https://github.com/percona/mongodb_exporter/blob/1f6c288104a069ad57811c7552f4d4b451f9567b/collector/mongod/oplog_status.go#L114-L131)

___

From what i see `mongodb` collector should be rewritten taking into account node types and their appropriate metrics. It looks like it will be wrong to add sharding metrics to existing module.

**Comment by ilyam8** [comment]
Percona exporter "mongosMetrics" vs proposal

| Metric      | Collect    |
| ----------- | ----------- |
| Total number of sharded databases ()      | Title       |
| Paragraph   | Text        |

**Comment by georgeok** [comment]
@ilyam8 Yes this table looks correct. balancerEnabled and chunksBalanced are boolean and I don't how we can properly display it. I think we will get `Total number of chunks` because the `Shard chunks` chart is a stack chart. And we could also get `Total number of drainingshards` relatively easy.

**Comment by ilyam8** [comment]
> chunksBalanced are boolean and I don't how we can properly display it

Well, `0` or `1` will do.

All is good then, let's proceed to adding those metrics
