### ISSUE TITLE
PSI (Pressure Stall Information)

### ISSUE THREAD

**Issue by pkramme** [netdata/netdata#5901]
##### Feature idea summary
Facebook implemented PSI (Pressure Stall Information) for Linux 4.20 and higher. PSI presents high quality information about the pressure the IO, memory and CPU is under. More information here:
* https://facebookmicrosites.github.io/psi/
##### Expected behavior
I'd be nice if the Pressure Stall Information could be displayed as a line graph under their respective categories.

**Comment by RX14** [comment]
PSI is probably the most useful responsiveness metric a modern kernel has, far far more useful than load average and even CPU utilization, since it tells us how much processes are waiting, and why. Would be very nice to see this info in netdata, right near the top.

**Comment by ilyam8** [comment]
@Ferroin cofirm or deny^^ 😄 (if the metrics is very useful then prio should be changed)

**Comment by Ferroin** [comment]
Based on actually looking through the definitions for the metrics (I've never used them before myself, but mostly because I've not taken the time before to look into them), I'd say they are indeed far more useful as an indicator that a system is overloaded than anything Netdata tracks currently,

**Comment by ilyam8** [comment]
Yes, this will be a great addition. @vlvkobal @cosmix
