### ISSUE TITLE
Stream.conf cannot be found

### ISSUE THREAD

**Issue by makutamatey** [netdata/netdata#5906]
One of my slaves is not having **/etc/netdata/edit-config stream.conf**. Please how do I install it manually?

**Comment by ilyam8** [comment]
Hi @makutamatey 

> One of my slaves is not having /etc/netdata/edit-config stream.conf.

Is not having what? `edit-config` ?

**Comment by makutamatey** [comment]
Please it not having the stream.conf file where i can edit the streams and add the API KEY. when I try to open /etc/netdata/edit-config stream.conf i get the message that it cannot be found.

**Comment by ilyam8** [comment]
Could you show the error message?

**Comment by makutamatey** [comment]
please I navigated to /etc/netdata/ and I realized the edit-config file was not there. That was why I was having that error. So uninstalled netdata and reinstalled it.

**Comment by paulkatsoulakis** [comment]
@makutamatey It sounds like your installation was not successful in the first attempt.
If you have the logs and the output of that first installation, it would be useful for us to analyse what went wrong. It may be something we missed that caused the installation to fail.


At any case, we are glad to know you solved your problem and we 'll be happy to help you again if you face any issues in the future
