### ISSUE TITLE
Configure checks for xenstat plugin are short-circuited when the plugin is explicitly requested during build.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#5907]
##### Bug report summary
When building Netdata, if `--enable-plugin-xenstat` is specified on the configure script, the configure script's detection of libxenstat does not work correctly and may claim that libxenstat is present when it actually isn't, causing the build to get to the point of linking the xenstat plugin and then fail instead of bailing during the configure stage like it should.

##### OS / Environment
Linux (discovered on amd64 Gentoo, observed also on Debian Sid).

##### Netdata version (ouput of `netdata -V`)
Master branch of the git repository as of commit f0bc01ddbdfcb948bb06cf05662b0901f297e59a

##### Component Name
Build System

##### Steps To Reproduce
1. Attempt to build Netdata with `--enable-plugin-xenstat` in the configure options.

##### Expected behavior
The configure script bails with a message about libxenstat not being present on the system.

-----

Spent almost an hour tracking this down when my daily updates on some of my virtualized systems started failing to build Netdata (Gentoo finally caught up and added a USE flag to their Netdata package to enable the Xen plugin, but the same use flag is used to enable code that gives better performance on paravirtualized guests in other packages I have installed, so the update process started trying to build the Xen plugin when building Netdata, which obviously doesn't work without the Xen tools, which aren't installed on these systems because they're guests).

After having taken a look at the config.log files from the failing builds (I can provide one of these if desired), it appears that the configure checks relating to libxenstat are passing even though libxenstat is not present on the system in question (in fact, the only Xen related stuff on the systems is the headers under `/usr/include/xen` that are part of the standard set of Linux kernel headers).

**Comment by vlvkobal** [comment]
@Ferroin do you still have the `config.log` from the failing build? Could you send it to me?

**Comment by vlvkobal** [comment]
@Ferroin I can't reproduce the issue. So, I still need your help.

On freshly installed Debian Sid:

```
checking for YAJL... no
checking for xenstat_init in -lxenstat... no
checking for XENLIGHT... no
configure: error: libxenstat required but not found. try installing 'xen-dom0-libs-devel'
 FAILED
```

**Comment by arkamar** [comment]
I believe that this issue is related with #7103.

**Comment by Ferroin** [comment]
@vlvkobal Sorry about not getting back with you about this previously.  I just rechecked, and can't reproduce this myself (and Gentoo has fixed things so that trying to install Netdata with the `xen` USE flag pulls in the Xen management components that are needed), so I'm just going to close this and remove the Help Wanted tag.
