### ISSUE TITLE
fping and postgres stopped working with :latest image

### ISSUE THREAD

**Issue by DenLilleMand** [netdata/netdata#5909]
##### Question summary
Using :latest tag on https://hub.docker.com/r/netdata/netdata/ made
`fping` and `postgres` plugins stop work, are those two suppose to work in a backwards compatible manner or do i as the user have to make sure that i change something? 

When i use the v1.13.0 image as base it works just fine

##### OS / Environment
Docker run on top of Arch Linux

The container is running with `fping` version 4.1, if i run the `fping` module by it self it doesn't throw any errors.

##### Component Name
`fping` and `postgres`

##### Expected results
That my old configuration from the last time i build it(1 month ago or so) still works.

**Comment by DenLilleMand** [comment]
fping configuration, with some mocked hosts:
```
# uncomment the following line - it should already be there
fping="/usr/local/bin/fping"

# set here all the hosts you need to ping
# I suggest to use hostnames and put their IPs in /etc/hosts
hosts="<host1> <host2> <host3>"

# override the chart update frequency - the default is inherited from netdata
update_every=1

# time in milliseconds (1 sec = 1000 ms) to ping the hosts
# 200 = 5 pings per second
ping_every=200

# other fping options - these are the defaults
fping_opts="-R -b 56 -i 1 -r 0 -t 5000"
```

**Comment by ilyam8** [comment]
duplicate of: #5890

**Comment by ilyam8** [comment]
> postgres

so it is not postgres, all python modules don't work because of #5890

**Comment by DenLilleMand** [comment]
Arg alright, sorry.
