### ISSUE TITLE
[Question] Can we disable update logs?

### ISSUE THREAD

**Issue by ZeProf2Code** [netdata/netdata#5910]
##### Question summary
Hello, is this possible to completely desactivate log files from being created by the automatic netdata updater (cron) in the `/` directory?
##### OS / Environment
Ubuntu 16.04
##### Component Name
Update logging system

**Comment by cakrit** [comment]
You should have logs only if the updater fails to update netdata. These are left so you can determine what went wrong. However, I'm not sure about leaving files under `/`. I think it would be better if the log file stayed under the working directory `dir` when we have a failure.

So, we'd take the following lines out of the `update` function:
```
        dir=$(create_tmp_directory)
        cd "$dir"
```
Then we can change this:
```
logfile=$(mktemp ${logfile}/netdata-updater.log.XXXXXX)
```
to
```
logfile="${dir}/netdata-updater.log"
```
and get rid of this:
```
[ -n "${logfile}" ] && rm "${logfile}" && logfile=
```

What do you think @paulkatsoulakis ?

**Comment by cakrit** [comment]
We could of course also consider providing an option to not leave any traces on the system when the updater fails, but I'm not certain it's a good idea. Perhaps we look into a way to only keep the latest failure?

**Comment by paulkatsoulakis** [comment]
Interesting, i was looking at this part of the code when i was preparing #5918
We definitely need to know what happen when something fails for the simple reason that not all problems are reproducible easily, so logs are needed for sure.

Let me think about the idea a bit and i 'll get back on this with more comments

**Comment by paulkatsoulakis** [comment]
Hi @ZeProf2Code could you give me the result of `grep tmp /proc/mounts`?
Also, what is the log file that you see in /?

**Comment by ZeProf2Code** [comment]
I don't have it anymore because I deleted it.
`grep tmp /proc/mounts` :
```udev /dev devtmpfs rw,nosuid,relatime,size=30893124k,nr_inodes=7723281,mode=755 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=6184076k,mode=755 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0```

**Comment by ZeProf2Code** [comment]
But this wasn't probably a error because when I go to my netdata page, it always says "You already have the latest netdata!"

**Comment by Ferroin** [comment]
@cakrit I think a better approach would be to instead put the logs in `/var/log/netdata` under their own sub-directory (`/var/log/netdata/updater` maybe?).  At that point, we can just use whatever we want as a log file name (ISO 8601 date+time for example), and pruning becomes a simple `find /var/log/netdata/updater -mtime +7d -delete`.

Alternatively, use `/var/log/netdata/updater.log` and let it just be handled by our logrotate configuration.

**Comment by paulkatsoulakis** [comment]
> @cakrit I think a better approach would be to instead put the logs in `/var/log/netdata` under their own sub-directory (`/var/log/netdata/updater` maybe?). At that point, we can just use whatever we want as a log file name (ISO 8601 date+time for example), and pruning becomes a simple `find /var/log/netdata/updater -mtime +7d -delete`.
> 
> Alternatively, use `/var/log/netdata/updater.log` and let it just be handled by our logrotate configuration.

I was thinking about that too, but isn't necessary to guarantee that the cronjob is run either as root or netdata so that it can write in there? And i think that is not fully under our control, so It kind of increases the complexity a bit, what do you think ?

**Comment by cakrit** [comment]
We expect it's running as root, otherwise the installation would fail anyway. Of course I like @Ferroin 's idea better. Remember though that it's not only the log we're talking about, we have a temp directory that is left behind as well, when we get a fatal failure. 

Regarding the UI showing that you have the latest netdata, this just means that the latest update worked. Some older ones failed.

**Comment by Ferroin** [comment]
For the temp directory specifically, is there any practical benefit to keeping the temp directories from past failures?  Or, put differently, why not just use a consistent temp directory name (something under `/var/lib/netdata` or equivalent maybe?), nuke the contents on startup and when finished, and be done with it.

**Comment by paulkatsoulakis** [comment]
> We expect it's running as root, otherwise the installation would fail anyway

Well, in theory a user could install netdata with `--install` in a non privileged folder and then have it under non-rooted cronjob that should work fine. Aren't we supporting this scenario ?

**Comment by cakrit** [comment]
Yes, you're right @paulkatsoulakis. Even then though, the user the updater runs as must have access to all the netdata directories. If it doesn't, the installation will fail.

**Comment by ilyam8** [comment]
As far as i know there is no such requirement like install netdata as root user. 

Example, install as normal user. It works w/o problems.

```
[lgz :netdata]ls -l
total 12
drwxrwxr-x 3 lgz lgz 4096 апр 29 21:25 etc
drwxrwxr-x 6 lgz lgz 4096 апр 29 21:25 usr
drwxrwxr-x 6 lgz lgz 4096 апр 29 21:25 var
[lgz :netdata]
[lgz :netdata]ps faxu | grep netdata
lgz      29544  0.0  0.0   6280  2308 pts/9    S+   21:27   0:00  |       \_ grep netdata
lgz      29118  0.7  0.1 215428 37576 ?        SNl  21:25   0:00 /home/lgz/123//netdata/usr/sbin/netdata
lgz      29142  1.5  0.0   9784  5588 ?        SN   21:25   0:01  \_ /home/lgz/123//netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
lgz      29143  0.4  0.0  31560  6432 ?        SN   21:25   0:00  \_ /home/lgz/123//netdata/usr/libexec/netdata/plugins.d/cups.plugin 1
lgz      29144  0.8  0.0  59700 18016 ?        SNl  21:25   0:00  \_ /bin/python /home/lgz/123//netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
lgz      29148  0.5  0.0 114396 15636 ?        SNl  21:25   0:00  \_ /home/lgz/123//netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
lgz      29149  0.3  0.0   4280  3052 ?        SN   21:25   0:00  \_ bash /home/lgz/123//netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
```

**Comment by Ferroin** [comment]
But in that case, we can just prefix the install logs and the temporary directory like we're doing for everything else anyway, so I don't really see an issue there.

**Comment by ilyam8** [comment]
By the way, i killed netdata process and `cups` plugin didn't exit

```
[lgz :netdata]kill -9 29118
[lgz :netdata]ps faxu | grep netdata
lgz      29665  0.0  0.0   6280  2288 pts/9    S+   21:29   0:00  |       \_ grep netdata
lgz      29143  0.3  0.0  31560  6432 ?        SN   21:25   0:00 /home/lgz/123//netdata/usr/libexec/netdata/plugins.d/cups.plugin 1
```

**Comment by prologic** [comment]
@ZeProf2Code Can you help me understand. It isn't clear to my "why" you want logs disabled for the updater. I can understand a `-q/--quiet` option to silence the logs if all goes well; but a failure should still be logged. This is pretty common behaviour for many UNIX tools.

Can you elaborate more on your original ask?

**Comment by prologic** [comment]
I am closing this due to no response. If you are still having problem with this feel free to comment or raise a new issue. Thanks!.
