### ISSUE TITLE
apps.cpu chart not showing specific processes

### ISSUE THREAD

**Issue by cwcrawley** [netdata/netdata#5915]
I've recently installed netdata on a bitnami Amazon Lightsail VPS. Creating some custom dashboards and I'm noticing on my chart apps.cpu, some processes are not showing up. In particular httpd, php-fpm etc. 

The only thought I have is that php/httpd are running as separate users (user daemon), could this be why netdata is not seeing them?

I've looked through the issues/questions on here and can't see how I get netdata to access those processes as well as the others.

**Comment by vlvkobal** [comment]
apps.plugins doesn't show processes, it shows groups of processes. You can configure them by running `/etc/netdata/edit-config apps_groups.conf`. Look at the [documentation](https://docs.netdata.cloud/collectors/apps.plugin/).

**Comment by cwcrawley** [comment]
Right, So - here's what I have, but only sql, ssh and netdata show up on the chart event though php is defined in the config.

```<div data-netdata="apps.cpu"
        data-dimensions="sql|ssh|netdata|httpd|php"
        data-host="{REDACTED}"
        data-chart-library="dygraph" 
        data-title="{REDACTED}"
        data-width="48%" 
        data-height="200" 
        data-after="-300" 
        class="netdata-container-with-legend"></div>```

However running a top or htop shows httpd and php processes.

**Comment by vlvkobal** [comment]
What is your group configuration for httpd and php?

**Comment by cwcrawley** [comment]
`httpd: apache* httpd nginx* lighttpd` and `php: php*`

**Comment by vlvkobal** [comment]
Do you see them in the `apps.processes` chart?

**Comment by cwcrawley** [comment]
I've found the issue. the php group is looking for `php*` whereas the process is `.php-fpm`. It wasn't matching the process. The same for httpd (looking for `httpd` whereas the process was `httpd.bin`)
