### ISSUE TITLE
How I get the latest values via HTTP request?

### ISSUE THREAD

**Issue by andrebeltrami** [netdata/netdata#5916]
Hi guys, 

I have one simple question. Sorry if this question is already answered. 

I tried collect the latest values from a specific chart, for example "system.cpu", I am using the NetData API. Here one example of the parameters I tried use to get the latest value only. 

`"http://MY_IP:PORT/api/v1/data?chart=system.cpu&dimension=system&after=-600&before=0&points=1&group=average&gtime=5&format=json&options=seconds,jsonwrap"
`

So, how can I get only the latest value stored from a specific chart using the NetData API ? 

Thank you all !

**Comment by ilyam8** [comment]
Hi @andrebeltrami 
Example
https://github.com/netdata/netdata/issues/5784#issuecomment-479389204

**Comment by ilyam8** [comment]
@andrebeltrami 	if you have any questions feel free to reopen
