### ISSUE TITLE
Weird WD values

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#5919]
Netdata version: v1.14.0-rc0-20-nightly
OS: Fedora

I'm getting the following weird values on the new 8tb WD red: 

Actual temp:
![1](https://user-images.githubusercontent.com/4349962/56775217-06f9eb80-67be-11e9-84b1-d003466673a2.JPG)

Smartctl value is:   3 Spin_Up_Time            0x0007   151   151   024    Pre-fail  Always       -       423 (Average 447)
![2](https://user-images.githubusercontent.com/4349962/56775218-06f9eb80-67be-11e9-9728-7a39b5f4f2cd.JPG)
Temp shown seems to be normalised value, not raw (194 Temperature_Celsius     0x0002   209   209   000    Old_age   Always       -       31 (Min/Max 19/45))
![3](https://user-images.githubusercontent.com/4349962/56775219-06f9eb80-67be-11e9-8888-5d0514d0ef9c.JPG)

Unsure if this is a netdata thing or something with smartd.

**Comment by ilyam8** [comment]
Hi @modem7 

Temperature is attribute 194.

That is how it works:
https://github.com/netdata/netdata/blob/e91b9ca57dc6a7f3b087b1b5a9efc12a21f11439/collectors/python.d.plugin/smartd_log/smartd_log.chart.py#L456-L458

So if your nomalized valuie is 31 and raw is 209 it would show 31.

Could you show `tail -n 1 thatdisk.ata.csv`?

**Comment by ilyam8** [comment]
As for `Spin-Up` time netdata show raw value.

I used this input doing the collector
https://github.com/netdata/netdata/issues/4285#issuecomment-425654443

___

And please show output from `smartctl -a /dev/sdh`

**Comment by modem7** [comment]
for the tail:

`2019-04-26 14:12:34;    1;100;0;        2;132;112;      3;151;38684000679;      4;100;177;      5;100;0;        7;100;0;8;140;15;       9;99;11242;     10;100;0;       12;100;153;     22;100;100;     192;100;636;    193;100;636;    194;216;193274773534;   196;100;0;      197;100;0;      198;100;0;      199;200;0;`

Smartctl:
```
smartctl 6.5 2016-05-07 r4318 [x86_64-linux-4.18.19-100.fc27.x86_64] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Western Digital Red
Device Model:     WDC WD80EFZX-68UW8N0
Serial Number:    R6GMY2BY
LU WWN Device Id: 5 000cca 263c91033
Firmware Version: 83.H0A83
User Capacity:    8,001,563,222,016 bytes [8.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Fri Apr 26 15:18:34 2019 BST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x80) Offline data collection activity
                                        was never started.
                                        Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0) The previous self-test routine completed
                                        without error or no self-test has ever
                                        been run.
Total time to complete Offline
data collection:                (  101) seconds.
Offline data collection
capabilities:                    (0x5b) SMART execute Offline immediate.
                                        Auto Offline data collection on/off support.
                                        Suspend Offline collection upon new
                                        command.
                                        Offline surface scan supported.
                                        Self-test supported.
                                        No Conveyance Self-test supported.
                                        Selective Self-test supported.
SMART capabilities:            (0x0003) Saves SMART data before entering
                                        power-saving mode.
                                        Supports SMART auto save timer.
Error logging capability:        (0x01) Error logging supported.
                                        General Purpose Logging supported.
Short self-test routine
recommended polling time:        (   2) minutes.
Extended self-test routine
recommended polling time:        (1267) minutes.
SCT capabilities:              (0x003d) SCT Status supported.
                                        SCT Error Recovery Control supported.
                                        SCT Feature Control supported.
                                        SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000b   100   100   016    Pre-fail  Always       -       0
  2 Throughput_Performance  0x0005   132   132   054    Pre-fail  Offline      -       112
  3 Spin_Up_Time            0x0007   151   151   024    Pre-fail  Always       -       423 (Average 447)
  4 Start_Stop_Count        0x0012   100   100   000    Old_age   Always       -       177
  5 Reallocated_Sector_Ct   0x0033   100   100   005    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000b   100   100   067    Pre-fail  Always       -       0
  8 Seek_Time_Performance   0x0005   140   140   020    Pre-fail  Offline      -       15
  9 Power_On_Hours          0x0012   099   099   000    Old_age   Always       -       11242
 10 Spin_Retry_Count        0x0013   100   100   060    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       153
 22 Helium_Level            0x0023   100   100   025    Pre-fail  Always       -       100
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       636
193 Load_Cycle_Count        0x0012   100   100   000    Old_age   Always       -       636
194 Temperature_Celsius     0x0002   216   216   000    Old_age   Always       -       30 (Min/Max 19/45)
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0008   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x000a   200   200   000    Old_age   Always       -       0

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
No self-tests have been logged.  [To run self-tests, use: smartctl -t]

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
```

**Comment by ilyam8** [comment]
Speaking about attribute n 3:

> 3;151;38684000679;
> 423 (Average 447)

```python
>>> 38684000679 & 0xFFF
423

>>> (38684000679 & 0xFFF0000) >> 16
447
```

But this probably super hardware specific.

Do [same](https://github.com/netdata/netdata/issues/5919#issuecomment-487073846) for all your disks.

Lets see if we can decode raw value for all disks using same algorithm.

**Comment by ilyam8** [comment]
> Spin-Up Time S.M.A.R.T. parameter indicates an average time (in milliseconds or seconds) of spindle spinup (from zero RPM (Revolutions Per Minute) to fully operational).

> The low value means it takes too long for the hard disk to a fully operational state.

> Recommendations
> This parameter is considered informational by the most hardware vendors. Although degradation of this parameter can be an indicator of drive aging and/or potential electromechanical problems, it does not directly indicate imminent drive failure. Regular backup is recommended. Pay closer attention to other parameters and overall drive health.

So.. 423 in what units? :thinking:

**Comment by modem7** [comment]
I'll post the results of all my WD drives: 

[smart.zip](https://github.com/netdata/netdata/files/3121852/smart.zip)

This has the CSV files and smartctl results. The other WD drives are showing as we expect, just this weird 8tb one that's being weird and an ass.

**Comment by Ferroin** [comment]
@ilyam8 My guess would be that it's probably milliseconds.  Typical spin up times for most consumer drives are on the order of a few hundred milliseconds, so this value would agree with expected hardware behavior.  Might be some other fraction of a second that doesn't match up with an SI unit though.

Also, I'm not getting any apparent decoding on any of my hard disks, but all mine are Seagate, so this may be a WD specific encoding for the raw value.

@modem7 is the drive in question either newer than any of the others or possibly a different product line (for example, WD Black versus WD Red)?

**Comment by modem7** [comment]
@Ferroin 

This particular drive is certainly newer, and it's one of the 8tb helium filled drives, but still a WD Red (not pro or otherwise).

**Comment by Ferroin** [comment]
@modem7 Do you have any other 8TB helium filled WD Reds?  If so, and they aren't behaving like this, could you check if they show the same firmware version in the output of `smartctl -a`?

If the answer to both is yes, then something odd is going on, otherwise I'd say that the difference with the spin up time values is not unexpected, and the temperature decoding issue may be related as well.

**Comment by ilyam8** [comment]
@modem7 please test https://github.com/netdata/netdata/pull/5923

**Comment by modem7** [comment]
@ilyam8 - tested and confirmed as working!
