### ISSUE TITLE
fail2ban not showing up on panel

### ISSUE THREAD

**Issue by hypertjs** [netdata/netdata#5925]
##### Question summary
Hello everyone,
I want to get fail2ban to show up on my panel, however, it's not showing up.
fail2ban is currently running and when I run the debug command
```
/usr/libexec/netdata/plugins.d/python.d.plugin 1 fail2ban debug
```
It runs perfectly fine. However, it's just missing from the panel completely.

##### OS / Environment
Ubuntu 18.04
netdata v1.14.0-11-nightly

**Comment by hypertjs** [comment]
Fixed it, fail2ban.log wasn't readable.

**Comment by paulkatsoulakis** [comment]
Thanks for reporting this to us @hypertjs. Happy to hear you found the problem, we will be glad to help you in the future if you need anything else. It's great to see our users extending our codebase and making netdata even more awesome!

Cheers!
