### ISSUE TITLE
Docs website

### ISSUE THREAD

**Issue by aspyatkin** [netdata/netdata#5926]
Hello, is docs website working at all? The host `docs.netdata.cloud` seems to be always down (ERR_CONNECTION_TIMED_OUT).

**Comment by ilyam8** [comment]
Hi @aspyatkin 

Yes, it is working. 

> seems to be always down 

Enjoy your roskomnadzor :smile: 

___

Get a vpn, that is what i did (must have thing in Russia :cry: )

**Comment by ilyam8** [comment]
Nothing we can do here, Roskomnadzor is blocking IPs and doesn't remove them from the black list.
