### ISSUE TITLE
Apache server status

### ISSUE THREAD

**Issue by h181222** [netdata/netdata#5927]
Hi!

I am quite new to netdata, but i am loving it so far!

I was just wondering if there was a built-in way to check if Apache servers are online? I am trying to configure it so that if a server is down the admin receives an email notifying about the server status.

**Comment by ilyam8** [comment]
Hi @h181222 

You need to configure [apache](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/apache#apache) collector, that is it.

Netdata has apache status check alarm

https://github.com/netdata/netdata/blob/e33c45d333b0704363eb31105293c9b067158cdb/health/health.d/apache.conf#L2-L13

**Comment by h181222** [comment]
Thank you so much!

Will update issue soon with results

**Comment by h181222** [comment]
Wait, i might have misunderstood. Are you saying that as long as the "mod_status" is enabled in apache, the built in status check takes care of the rest?

**Comment by ilyam8** [comment]
- enable `mod_status`
 - restart `netdata.service`
 - check the dashboard, if you see `Apache` there all is good

**Comment by ilyam8** [comment]
https://docs.netdata.cloud/health/notifications/email/#email

**Comment by h181222** [comment]
Great thanks!

**Comment by h181222** [comment]
I got the server status working, however when i try to run the test for sending a notification (via email), the test passes, but i have not recieved an email. Is the test supposed to just see if its possible to send it, or should i actually recieve an email?

**Comment by ilyam8** [comment]
```
lgz@loled2[/opt/netdata/usr/libexec/netdata/plugins.d]sudo su -s /bin/bash netdata
netdata@loled2:/opt/netdata/usr/libexec/netdata/plugins.d$ ./alarm-notify.sh test

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2019-05-06 05:07:21: alarm-notify.sh: INFO: sent email notification for: loled2 test.chart.test_alarm is WARNING to 'root'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2019-05-06 05:07:22: alarm-notify.sh: INFO: sent email notification for: loled2 test.chart.test_alarm is CRITICAL to 'root'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2019-05-06 05:07:22: alarm-notify.sh: INFO: sent email notification for: loled2 test.chart.test_alarm is CLEAR to 'root'
# OK
```

I see test emails
```
lgz@loled2[/opt/netdata/usr/libexec/netdata/plugins.d]mail
Mail version 8.1.2 01/15/2001.  Type ? for help.
"/var/mail/lgz": 4 messages 4 new
>N  1 netdata@loled2     Mon May 06 05:05  150/11573 loled2 is critical - inbound packets dropped ratio - net_packets.ifb908.2392120
 N  2 netdata@loled2     Mon May 06 05:07  150/11098 loled2 needs attention - test alarm - test.chart
 N  3 netdata@loled2     Mon May 06 05:07  150/11196 loled2 is critical - test alarm - test.chart
 N  4 netdata@loled2     Mon May 06 05:07  150/11238 loled2 recovered - test alarm - test.chart
```

check error log @h181222

**Comment by cakrit** [comment]
Of course `sendmail` needs to be able to deliver emails, you'll first need to ensure that you can send emails from the command line first. May need a bit of set up.

**Comment by h181222** [comment]
I got it to work, it seems like the domain used wasnt accepted (sending as user instead of a dedicated email). We fixed it by simply creating a dedicated notification email. Thanks for all the help!
