### ISSUE TITLE
mongodb error exception on check : ‘locks’

### ISSUE THREAD

**Issue by donets420** [netdata/netdata#5929]
Hi all,
Does netdata mongodb plugin monitor mongos?

I have error - plugin[checker] : mongodb[mongo-27017] : unhandled exception on check : ‘locks’, skipping the job

This error relevant only for mongos

**Comment by ilyam8** [comment]
KeyErrors:

- `locks` in `serverStatus`
- `mapped` in `serverStatus['mem']`
