### ISSUE TITLE
Can the MySQL plugin be used without having the (root) password in plaintext?

### ISSUE THREAD

**Issue by petecooper** [netdata/netdata#5932]
##### Question summary

Can the MySQL plugin be used without having the (root) password in plaintext?

I see from https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mysql that most use cases require a root password to be stored in a configuration file. I understand  access to the collector configuration can be set in the filesystem, but is there a method of using the MySQL collector without saving a plaintext password?

Thank you in advance.

##### OS / Environment

Ubuntu 18.04 LTS.

##### Component Name

MySQL Python collector plugin.

##### Expected results

--

**Comment by ilyam8** [comment]
> Can the MySQL plugin be used without having the (root) password in plaintext?

Yes. 

https://github.com/netdata/netdata/blob/d01b2620eab77d8f2ab1c70456744565eff356f0/collectors/python.d.plugin/mysql/mysql.conf#L86-L106

**Comment by ilyam8** [comment]
If you don't want to have any password in the module configuration file at all you can use
`my.cnf` option (i believe you can store credential there).

Like
https://github.com/netdata/netdata/blob/d01b2620eab77d8f2ab1c70456744565eff356f0/collectors/python.d.plugin/mysql/mysql.conf#L113-L115

**Comment by petecooper** [comment]
Perfect! Thank you very much @ilyam8 !
