### ISSUE TITLE
Samba monitoring is a flat line

### ISSUE THREAD

**Issue by camjesus2** [netdata/netdata#5933]
Hi all!
I'm having some problems getting the samba performance monitoring to work.
My system is a self compiled samba on a Debian Stretch fully updated running netdata v1.14.0-rc0-20-nightly.
I've followed the documentation, and reading issue #2483 helped a lot, but (long story short) I had to modify /usr/libexec/netdata/python.d/samba.chart.py since  `find_binary('sudo'), find_binary('smbstatus')` could not locate sudo and smbstatus and therefore the modules where not loading. After setting:
```
sudo_binary = '/usr/bin/sudo'
smbstatus_binary = '/usr/local/samba/bin/smbstatus'
```
in samba.chart.py, I could finally get the charts. Unfortunatly, they are flat lines.
Now, this is where my noobiness jumps in... Most of the workstations are windows 10 and so, most (if not all) of the transactions are SMB3. Am I right to think that only SMB2 transactions are monitored? The docs seem to say that.
However, I would expect that at least Syscalls would show up.
So, my questions:
1) Any idea why I had to modify the python script? I don't know python, by the way
2) SMB3 transactions are monitored or only SMB2?
3) Any sugestions?

I guess that the real problem here are my expectations, but hey, worst case scenario, I learn something.

Best regards!

**Comment by ilyam8** [comment]
> could not locate sudo and smbstatus

We need to split the check

https://github.com/netdata/netdata/blob/cf5c6dadda618c45f67e3a3a36efc409fc34ee65/collectors/python.d.plugin/samba/samba.chart.py#L108-L112

I guess the problem with `smbstatus`

That is the script:

```python
import os

PATH = os.getenv('PATH', '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin').split(':')

def find_binary(binary):
    """
    :param binary: <str>
    :return:
    """
    for directory in PATH:
        binary_name = '/'.join([directory, binary])
        if os.path.isfile(binary_name) and os.access(binary_name, os.X_OK):
            return binary_name
    return None
```

It seems that `/usr/local/samba/bin/` not in `PATH` 

I suggest to modify `PATH` option in `netdata.conf`, please add `/usr/local/samba/bin/` there and restart netdata.

**Comment by ilyam8** [comment]
@ntlug please take a look

**Comment by ntlug** [comment]
I'm guessing a bit at this.  My guess is that a Samba "raw" compiled (make;make install) tries to place things by default at /usr/local/samba/bin.  I took my best guess based on distribution supported samba installations, and didn't look into where a "raw" source compile might place things.

Indeed, the fix is likely to add /usr/local/samba/bin to the PATH.

**Comment by ilyam8** [comment]
@ntlug 

Any ideas about `flat line` part? 

> in samba.chart.py, I could finally get the charts. Unfortunatly, they are flat lines.
Now, this is where my noobiness jumps in... Most of the workstations are windows 10 and so, most (if not all) of the transactions are SMB3. Am I right to think that only SMB2 transactions are monitored? The docs seem to say that.
However, I would expect that at least Syscalls would show up.

**Comment by camjesus2** [comment]
First of all, let me thank you for taking the time to address this.
Secondly, I can confirm that adding /usr/local/samba/bin to the path solves
the "smbstatus not found". Indeed different SAMBA distributions put
smbstatus in different places (weird but true) and self compiling generally
uses /usr/local/samba/bin unless otherwise specified at compiling time. Is
there any possibility to use something like smbd -b|grep -wi "bindir" to
get the correct directory?
Unfortunatly my graphs are still flatlines.
Best regards


Ilya Mashchenko <notifications@github.com> escreveu no dia quarta,
1/05/2019 à(s) 09:26:

**Comment by ntlug** [comment]
Does smbstatus -P return values for you from the command line?  Don't think the profile counter names are really related to protocol version level.  Our SMB3 requests show up on the smb2_ counters.

**Comment by camjesus2** [comment]
Hi Christopher.
You are right of course. smbstatus -P was always 0.
I used the  "smb.conf option" and even though testparm didn't give any
errors, it seems that  smbd profiling level1 was utterly ignored.
Modifying smbd.service to include -P 1 did the trick. All is working as
expected now.

Thanks everyone for the help.
Best regards
Carlos

Christopher Cox <notifications@github.com> escreveu no dia sábado,
4/05/2019 à(s) 00:14:

**Comment by cakrit** [comment]
Thanks @ntlug !
