### ISSUE TITLE
docker image is missing nut package

### ISSUE THREAD

**Issue by utdrmac** [netdata/netdata#5934]
##### Bug report summary
Attempting to use the BASH nut.chart.sh plugin
Plugin fails to execute because `upsc` is command not found in Docker image. The `nut-2.7.4` package from alpine-edge is not installed

##### OS / Environment
Docker, latest image 20190428

##### Netdata version (ouput of `netdata -V`)
netdata v1.14.0-11-ge91b9ca

##### Component Name
nut plugin

##### Steps To Reproduce
install netdata using Docker. Enable nut plugin. Notice failure.

##### Expected behavior
For all necessary software to be included in the docker image for all included plugins to work correctly out of box

**Comment by paulkatsoulakis** [comment]
Thanks for your report @utdrmac, that is a nice catch.
At the very minimum, we should at least mention the activity of adding the package, if we did this intentionally and did not provide the nut package.
I 'll have a look and let you know!

**Comment by utdrmac** [comment]
Not sure if this belongs in another bug, but it's all related to me attempting to get nut working. I kept getting the following in `docker logs`
` sh: exec: line 1 /usr/libexec/netdata/plugins.d/charts.d.plugin Permission denied`
It seems this script is owned/group `root/root` with `-rwxr-x---` and thus the `netdata` user cannot run the plugin.
I used `docker exec -it /bin/bash` and changed the group to `netdata` plus changed permissions to `-rwsr-x---` which matches those of apps.d.plugin and the plugin seems to be running now.

**Comment by paulkatsoulakis** [comment]
> Not sure if this belongs in another bug, but it's all related to me attempting to get nut working. I kept getting the following in `docker logs`
> ` sh: exec: line 1 /usr/libexec/netdata/plugins.d/charts.d.plugin Permission denied`
> It seems this script is owned/group `root/root` with `-rwxr-x---` and thus the `netdata` user cannot run the plugin.
> I used `docker exec -it /bin/bash` and changed the group to `netdata` plus changed permissions to `-rwsr-x---` which matches those of apps.d.plugin and the plugin seems to be running now.

That is interesting, can you confirm if this is happening with v1.14.0 official release ?
We had an issue that we fixed, so i want to rule out whether we are looking at a fixed issue or not

**Comment by utdrmac** [comment]
> That is interesting, can you confirm if this is happening with v1.14.0 official release ?
> We had an issue that we fixed, so i want to rule out whether we are looking at a fixed issue or not

I'm running Docker, netdata v1.14.0-11-ge91b9ca, "Image": "sha256:d4a7ea92f, "Created": "2019-04-28T00:32:26, if that helps identify.

> Regarding the package missing, we will need to update the base image for this, i 'll inform this
> issue once i got it ready

Sweet. Thanks!

**Comment by paulkatsoulakis** [comment]
@utdrmac regarding the permissions issue, could you try updating to latest and confirm if the problem persists? The issue has been fixed to a later version indeed, but we have to confirm that you are not facing a different problem. Thanks!
