### ISSUE TITLE
`timeout` requires flag

### ISSUE THREAD

**Issue by utdrmac** [netdata/netdata#5935]
##### Bug report summary
Running latest Docker image. Trying to use charts.plugin. 
https://github.com/netdata/netdata/blob/cf5c6dadda618c45f67e3a3a36efc409fc34ee65/collectors/charts.d.plugin/charts.d.plugin.in#L284
`timeout` requires `-t` to be passed as flag option

Seeing this error message when attempting to debug charts plugin:
```
timeout: can't execute '4': No such file or directory
```

```
# timeout
BusyBox v1.29.3 (2019-04-25 10:39:48 UTC) multi-call binary.

Usage: timeout [-t SECS] [-s SIG] PROG ARGS
```

##### OS / Environment
Docker 20190428 (latest)

##### Netdata version (ouput of `netdata -V`)
v1.14.0-11-ge91b9ca

##### Component Name
charts plugin

##### Steps To Reproduce
attempt to use nut (or any charts.d plugin)

##### Expected behavior
for the correct parameters to be passed to utilities so that things work as expected

**Comment by paulkatsoulakis** [comment]
Good morning @utdrmac, thanks for reporting the issue!
We struggle a lot to provide an out of the box capability to our users, but as you will also see the variations are so many that things slip through.

On this specific issue It seems that `timeout` syntax differs between distros. More precisely, we have the following variations:

1) FreeBSD - has a parameter duration, plus kill switches with flags
```
root@netdata-freebsd-test:~ # timeout --help
Usage: timeout [--signal sig | -s sig] [--preserve-status] [--kill-after time | -k time] [--foreground] <duration> <command> <arg ...>
```
2) Alpine - has the option `-t` for seconds
```
bash-4.4# timeout --help
BusyBox v1.29.3 (2019-04-28 10:42:51 UTC) multi-call binary.

Usage: timeout [-t SECS] [-s SIG] PROG ARGS

Runs PROG. Sends SIG to it if it is not gone in SECS seconds.
Defaults: SECS: 10, SIG: TERM.
bash-4.4# 
```
3) CentOS, Ubuntu (and i am guessing other linux distros too) have the DURATION as parameter, plus kill switch flags same like freeBSD 

```
[root@d4a7c9920642 netdata]# timeout --help
Usage: timeout [OPTION] DURATION COMMAND [ARG]...
  or:  timeout [OPTION]
Start COMMAND, and kill it if still running after DURATION.
.
.
.
DURATION is a floating point number with an optional suffix:
's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days.
.
.
```

I 'll work around a solution for this, we should have seen that for sure in the first place.

Thanks!
