### ISSUE TITLE
Markdown linter warnings and CI checks

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5941]
- [ ] Use the markdown linter remark-lint to identify and fix issues with our READMEs. 
- [ ] Look into properly configuring Codacy to warn on valid issues with markdown files.

Detailed conversation is in PR #5898

**Comment by joelhans** [comment]
Thought I'd check in to see, roughly, the progress on reducing these errors. I just got 7533, which is a lot, but significantly down from 18400+ as reported in #6664.

I'm adding some more of this cleanup to my long-term roadmap now.

**Comment by prologic** [comment]
Working on a a reviewdog based Github Action to run `remark-lint`: https://github.com/prologic/action-remark-lint

**Comment by prologic** [comment]
So I spent some time this weekend on figuring out what we can do here. Het's what I did:

Built two Github Actions:

- https://github.com/prologic/action-remark-lint
- https://github.com/prologic/action-markdownlint

Published both to the Github Action Marketplace (_who knows perhaps they can be made useful to others?_).

Tested it here: https://github.com/prologic/bitcask/pull/126

Which you can see the results of here:

- https://github.com/prologic/bitcask/pull/126/checks?check_run_id=408561808
- https://github.com/prologic/bitcask/pull/126/checks?check_run_id=408561817

----

Unfortunately both tools `remark` and `markdownlint` and subsequently the Github Actions I put together to wrap thse tools really only spit out warnings in Pull Requests. -- Unless you specifically go looking through the "Checks" for CI jobs that actually "Succeeded" to see if there were warnings I'm not finding this very useful (_I certainly wouldn't go finding warnings for "Green" jobs_).

For this to be useful I'd have to figure out how to turn the warnings into flat out errors and surface them as such.

I'm open to suggestions/ideas...

**Comment by Ferroin** [comment]
Possibly stupid idea, but why not wrap the linter in a script that looks for warnings in the output and exits with an exit code other than 0 if it finds any?

**Comment by prologic** [comment]
> Possibly stupid idea, but why not wrap the linter in a script that looks for warnings in the output and exits with an exit code other than 0 if it finds any?

Oc course we can do that -- But that's largely what ReviewDog was written to do. It works quite well. It has the added benefit of doing in-PR reviews (_which we can't do with our forking model at this time -- until Github figure out a way to support this without violating security concerns_); but also keeps the output all consistent anyway.

But of course I can just write some hacky shell script Github Action :) -- But I also felt like _trying_ to do a proper implementation of a Markdown linter with ReviewDog support. I sort of failed; but not completely. The code is up; I'll circle back on this when I have spare time; this isn't super important right now.

**Comment by cpipilas** [comment]
@Ferroin is there any action for this or we can close it?

**Comment by Ferroin** [comment]
I think we can probably close it at this point.

It would definitely be nice to have, but it’s probably more effort than it’s worth right now.
