### ISSUE TITLE
CouchDB for JSON backend?

### ISSUE THREAD

**Issue by jimmyc802** [netdata/netdata#5942]
##### Question summary
I was hoping someone could point me in the right direction to get started using the json backend option with netdata. We are trying to test the backend feature with couchdb and we are getting errors. For our testing purposes we have the destination couchdb server on the same instance that netdata is running on. Here is the error we see in the logs:

2019-04-30 12:10:19: netdata ERROR : BACKENDS : BACKEND: failed to write data to database backend '127.0.0.1:5984'. Willing to write 386800 bytes, wrote 108018 bytes. Will re-connect. (errno 11, Resource temporarily unavailable)
2019-04-30 12:10:29: netdata ERROR : BACKENDS : heartbeat missed 19999918 monotonic microseconds

Here is our configuration for the backend:
[backend]
        # host tags =
        enabled = yes
        #data source = average
        type = json
        destination = 127.0.0.1:5984
        #prefix = netdata
        hostname = netdata
        #update every = 10
        #buffer on failures = 10
        #timeout ms = 20000
        #send names instead of ids = yes
        #send charts matching = *
        #send hosts matching = localhost *

Any feedback on what we might be doing wrong here?
Is CouchDB not a good option?
 - If not, what is the best JSON document db option for the backend?

##### OS / Environment
CentOS 7.6

##### Component Name
Backend

**Comment by cakrit** [comment]
From the little I read, it looks like couchDB needs a new backend implementation, that we don't currently have. The `json` backend just opens a socket and pushes JSON documents to it. I have seen someone doing with kafka in https://github.com/netdata/netdata/issues/1917. Perhaps other people from the community can say here what they've used with the JSON backend option?

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
