### ISSUE TITLE
Storing alarms into log files other than debug/error/access logs 

### ISSUE THREAD

**Issue by lindsayjm** [netdata/netdata#5944]
Attempting to write an alarm (once triggered) into a log file (Raspberry Pi) to trigger another script. 
Any suggestions for storing this into a different log or are these the only 3 that can be used?

**Comment by cakrit** [comment]
All you need is to modify `health_alarm_notify.conf` to do whatever you like with the alarms. See [custom notification](https://docs.netdata.cloud/health/notifications/custom/#custom). 
No point in using the log files for anything like this.
