### ISSUE TITLE
MySQL8 - group replication monitoring and alerts

### ISSUE THREAD

**Issue by dancvrcek** [netdata/netdata#5945]
##### Feature idea summary

MySQL8 seems to have changed its replication status data. At least in situations, when one uses "mysqlsh" based management of an InnoDB cluster.  (but I might have missed something, in which case I apologise). 

Currently, the requirement is to give netdata@localhost the "replication client" privilege. However, "show slave status" only returns an empty set for us.

What seems to work is to use performance_schema database, and in particular "replication_group_members" table. 

It shows the most important data for monitoring (at least in our case):

*************************** 1. row ***************************
  CHANNEL_NAME: group_replication_applier
     MEMBER_ID: 45079783-9385-11e8-9706-1605ec76d48e
   MEMBER_HOST: a2
   MEMBER_PORT: 3306
  MEMBER_STATE: ONLINE
   MEMBER_ROLE: PRIMARY
MEMBER_VERSION: 8.0.16
*************************** 2. row ***************************
  CHANNEL_NAME: group_replication_applier
     MEMBER_ID: 7d1dbd7b-5c44-11e9-8027-8ef83dffb8f9
   MEMBER_HOST: a3
   MEMBER_PORT: 3306
  MEMBER_STATE: RECOVERING
   MEMBER_ROLE: SECONDARY
MEMBER_VERSION: 8.0.16
*************************** 3. row ***************************
  CHANNEL_NAME: group_replication_applier
     MEMBER_ID: c66c22ce-5c46-11e9-b7de-1a4e03cb7ac2
   MEMBER_HOST: a1
   MEMBER_PORT: 3306
  MEMBER_STATE: ONLINE
   MEMBER_ROLE: SECONDARY
MEMBER_VERSION: 8.0.16

The change would probably require:
1. extend / change privilege for netdata@localhost to include
grant select on performance_schema.* to 'netdata'@'localhost';

2. add a new metric "replication_group_members" with parameters
 - member_state with an array of values?
 - member_role ... dtto - to show which node is master

3. alerts
 - change of the master
 - change of member state - from ONLINE  to "something" and from "something" to RECOVERING and RECOVERING to ONLINE, I think the set of "something" is - OFFLINE, UNREACHABLE, ERROR, (MISSING)

##### Expected behavior

1. Provide alerts on the member state changes and role changes.
2. availability of badges for member state and role.

**Comment by ilyam8** [comment]
@dancvrcek if you could provide guide how to setup an env with mysql8 and group replication (docker i think) it would be nice.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
