### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [netdata/netdata#5946]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by gmosx** [comment]
Hi! We are always looking for new contributors. Even thought we are currently working on improving the branding of netdata, it would be great to see your suggestions/ideas for a logo.

**Comment by gpapamathND** [comment]
Hi @zuurw. Much appreciated your suggestion. 
If you don't mind, would be great to have a quick call in case you are interested for something bigger. Please, send me your email to discuss, in case you are interested.

**Comment by zuurw** [comment]
Hi @gpapamathND, here is my email: zuuritaly@gmail.com.
I will be wainting for your reply.
Cheers!!!
