### ISSUE TITLE
Application name not showing in netdata 

### ISSUE THREAD

**Issue by makutamatey** [netdata/netdata#5954]
I want to monitor my custom application separately so I can have an idea of the amount  of resources it is consuming. I found a similar [issue here](https://github.com/netdata/netdata/issues/3516 ), But It does not seem to work. In my apps_groups.conf file I set myapp:  \*myapp\*. myapp is the group name while \*myapp\* is the name of the process I am running. Yet I still don't see it in the Application section. Kindly help me resolve it.

**Comment by cakrit** [comment]
So you have a single line in `apps_groups.conf` `myapp: *myapp*.myapp`. Can you please show the exact names of some of those processes on your system? i.e. what you actually see from a `ps | grep myapp`.

**Comment by makutamatey** [comment]
So the application name is showing in systemd services by default and that meets my needs. Thank you.
