### ISSUE TITLE
role_recipients_custom not filtering correctly

### ISSUE THREAD

**Issue by foamz** [netdata/netdata#5955]
I have configured the "custom" method to only send notifications for the "Pcritical" recipient, however I seem to get all sorts of notifications that was sent to the "sysadmin" recipient on this method.

Here's a snippet of /etc/netdata/health_alarm_notify.conf:
```
# enable/disable sending custom notifications
SEND_CUSTOM="YES"

DEFAULT_RECIPIENT_CUSTOM="seemsToSendNoMatterWhatISetThisTo|critical"
custom_sender() {
    local msg="${host} ${status_message}: ${alarm} ${raised_for}"
    to="${1}"
    custom_dest=$(docurl -X POST https://url.to/sms --header 'x-api-key:xxxxxx' -X POST -H 'Content-Type: application/json' -H 'cache-control: no-cache' -d "{\"message\":\"${msg}\"}")

    if [ "${custom_dest}" = "200" ]
    then
        info "sent custom notification for ${status} of '${host}.${chart}.${name}'."
    else
        info "failed to send custom notification to ${t}, for ${status} of '${host}.${chart}.${name}', code ${code}."
    fi

}

# RECIPIENTS PER ROLE

# PCritical - Send to Teams and SMS
role_recipients_msteam[Pcritical]="${GENERAL_RECIPIENT_MSTEAM}"
role_recipients_custom[Pcritical]="${DEFAULT_RECIPIENT_CUSTOM}"

role_recipients_msteam[sysadmin]="${DEFAULT_RECIPIENT_MSTEAM}"
#role_recipients_custom[sysadmin]="${DEFAULT_RECIPIENT_CUSTOM}"
```

I only have one health check at this time in health.d, which will alarm if a host is down. Its "to" field is set to "Pcritical". 
Why are alarms for things like ram being sent to this method?

##### OS / Environment
Amazon Linux 2018.03
Netdata runs in a Docker container. netdata/netdata image

##### Netdata version (ouput of `netdata -V`)
v1.14.0-8-gf0bc01d

##### Component Name
SEND_CUSTOM

##### Expected behavior
Only use method with health checks set "to: Pcritical"

**Comment by cakrit** [comment]
> I only have one health check at this time in health.d, which will alarm if a host is down. Its "to" field is set to "Pcritical".
Why are alarms for things like ram being sent to this method?

netdata has many pre-configured alarms, which you can see under `/etc/netdata/orig/health.d`. The `/etc/netdata/health.d` optionally contains additional alarms, or overrides of the files you see in the stock configuration. Since you're building a custom sender, one thing you could do is the following:
```
DEFAULT_RECIPIENT_CUSTOM=IGNORE

custom_sender() {
if [ "${to_custom}" = "IGNORE" ] ; then return ; fi 
...
}

role_recipients_custom[Pcritical]="validrecipient|critical"
```
This way, all the default role recipients get set to "IGNORE" and you'll only get the notifications you want.
