### ISSUE TITLE
Installation script issues

### ISSUE THREAD

**Issue by vitaprimo** [netdata/netdata#5957]
### Summary

It seems that the installation script (building from source, macOS) doesn't setup the user account/group properly. macOS 10.13.6.

### Long version

For some reason I couldn't access Homebrew's installation of netdata other than from _localhost_ so I decided to uninstall it (normally with Homebrew) and try the manual install for no real reason.

I was root keeping the main user's stuff (became root using sudo -s).

This is what I got in the output:

>  --- Add user netdata to required user groups --- 
> Adding netdata user group ...
> Failed to add netdata user group !
> Adding netdata user account with home /usr/local/netdata/var/lib/netdata ...
> Failed to add netdata user account !
> Group 'docker' does not exist.
> Group 'nginx' does not exist.
> Group 'varnish' does not exist.
> Group 'haproxy' does not exist.
> Group 'adm' does not exist.
> Group 'nsd' does not exist.
> Group 'proxy' does not exist.
> Group 'squid' does not exist.
> Group 'ceph' does not exist.
> Adding netdata user to the nobody group ...
> Failed to add user netdata to group nobody !
>  --- Install logrotate configuration for netdata --- 
>  --- Read installation options from netdata.conf --- 
> id: netdata: no such user
> 
>     Permissions
>     - netdata user             : netdata
>     - netdata group            : netdata
>     - web files user           : netdata
>     - web files group          : netdata
>     - root user                : root
> 
>     Directories
>     - netdata user config dir  : /usr/local/netdata/etc/netdata
>     - netdata stock config dir : /usr/local/netdata/usr/lib/netdata/conf.d
>     - netdata log dir          : /usr/local/netdata/var/log/netdata
>     - netdata run dir          : /usr/local/netdata/var/run
>     - netdata lib dir          : /usr/local/netdata/var/lib/netdata
>     - netdata web dir          : /usr/local/netdata/usr/share/netdata/web
>     - netdata cache dir        : /usr/local/netdata/var/cache/netdata
> 
>     Other
>     - netdata port             : 19999
> 
>  --- Fix permissions of netdata directories (using user 'netdata') --- 
> [/Users/mainuser/netdata]# mkdir -p /usr/local/netdata/var/run 
>  OK   
> 
> Creating directory '/usr/local/netdata/etc/netdata/go.d'
> [/Users/mainuser/netdata]# mkdir -p /usr/local/netdata/etc/netdata/go.d 
>  OK   
> 
> [/Users/mainuser/netdata]# chown -R root:netdata /usr/local/netdata/etc/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/etc/netdata -type f -exec chmod 0640 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/etc/netdata -type d -exec chmod 0755 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# chmod 755 /usr/local/netdata/etc/netdata/edit-config 
>  OK   
> 
> [/Users/mainuser/netdata]# ln -s /usr/local/netdata/usr/lib/netdata/conf.d /usr/local/netdata/etc/netdata/orig 
>  OK   
> 
> [/Users/mainuser/netdata]# chown -R root:netdata /usr/local/netdata/usr/lib/netdata/conf.d 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/lib/netdata/conf.d -type f -exec chmod 0640 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/lib/netdata/conf.d -type d -exec chmod 0755 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# chown -R netdata:netdata /usr/local/netdata/usr/share/netdata/web 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/share/netdata/web -type f -exec chmod 0664 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/share/netdata/web -type d -exec chmod 0775 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# chown -R netdata:netdata /usr/local/netdata/var/lib/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chown -R netdata:netdata /usr/local/netdata/var/cache/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chown -R netdata:netdata /usr/local/netdata/var/log/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chmod 755 /usr/local/netdata/var/log/netdata 
>  OK   
> 
> [/Users/mainuser/netdata]# chown netdata:netdata /usr/local/netdata/var/log/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chown -R root:netdata /usr/local/netdata/usr/libexec/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/libexec/netdata -type d -exec chmod 0755 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/libexec/netdata -type f -exec chmod 0644 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/libexec/netdata -type f -a -name \*.plugin -exec chmod 0750 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/libexec/netdata -type f -a -name \*.sh -exec chmod 0755 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# chown root:netdata /usr/local/netdata/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chmod 0550 /usr/local/netdata/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh 
>  OK   
> 
>  --- Install go.d.plugin --- 
> [/Users/mainuser/netdata]# curl -sSL --connect-timeout 10 --retry 3 https://github.com/netdata/go.d.plugin/releases/download/v0.4.0/go.d.plugin-v0.4.0.darwin-amd64 
>  OK   
> 
> [/Users/mainuser/netdata]# curl -sSL --connect-timeout 10 --retry 3 https://github.com/netdata/go.d.plugin/releases/download/v0.4.0/config.tar.gz 
>  OK   
> 
> go.d.plugin-v0.4.0.darwin-amd64: OK
> config.tar.gz: OK
> [/Users/mainuser/netdata]# rm -rf /usr/local/netdata/usr/lib/netdata/conf.d/go.d 
>  OK   
> 
> [/Users/mainuser/netdata]# rm -rf /usr/local/netdata/usr/lib/netdata/conf.d/go.d.conf 
>  OK   
> 
> [/Users/mainuser/netdata]# tar -xf /tmp/netdata-go-2ut6U8/config.tar.gz -C /usr/local/netdata/usr/lib/netdata/conf.d/ 
>  OK   
> 
> [/Users/mainuser/netdata]# chown -R root:netdata /usr/local/netdata/usr/lib/netdata/conf.d 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# mv /tmp/netdata-go-2ut6U8/go.d.plugin-v0.4.0.darwin-amd64 /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 
>  OK   
> 
> [/Users/mainuser/netdata]# chown root:netdata /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chmod 0750 /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 
>  OK   
> 
>  --- Install netdata at system init --- 
> Installing MacOS X plist file...
> [/Users/mainuser/netdata]# cp system/netdata.plist /Library/LaunchDaemons/com.github.netdata.plist 
>  OK   
> 
> [/Users/mainuser/netdata]# launchctl load /Library/LaunchDaemons/com.github.netdata.plist 
>  OK   
> 
>  --- Start netdata --- 
> Stopping netdata on pid 3398 ....
> netdata on pid 3398 stopped.
> Stopping netdata on pid 37470 ....
> netdata on pid 37470 stopped.
> [/Users/mainuser/netdata]# stop_all_netdata 
> Stopping netdata on pid 37514 .....
> netdata on pid 37514 stopped.
>  OK   
> 
> [/Users/mainuser/netdata]# /usr/local/netdata/usr/sbin/netdata 
>  OK   
> 
>  OK  netdata started! 
> 
> Downloading default configuration from netdata...
> [/Users/mainuser/netdata]# curl -sSL --connect-timeout 10 --retry 3 http://localhost:19999/netdata.conf 
>  OK   
> 
> [/Users/mainuser/netdata]# mv /usr/local/netdata/etc/netdata/netdata.conf.new /usr/local/netdata/etc/netdata/netdata.conf 
>  OK   
> 
>  OK  New configuration saved for you to edit at /usr/local/netdata/etc/netdata/netdata.conf 
> 
> [/Users/mainuser/netdata]# chown netdata /usr/local/netdata/etc/netdata/netdata.conf 
> chown: netdata: illegal user name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chmod 0664 /usr/local/netdata/etc/netdata/netdata.conf 
>  OK   
> 
>  --- Check version.txt --- 
>  --- Copy uninstaller --- 
>  --- Basic netdata instructions --- 
> 
> netdata by default listens on all IPs on port 19999,
> so you can access it with:
> 
>   http://this.machine.ip:19999/
> 
> To stop netdata run:
> 
>   killall netdata
> 
> To start netdata run:
> 
>   /usr/local/netdata/usr/sbin/netdata
> 
> 
> Uninstall script copied to: /usr/local/netdata/usr/libexec/netdata-uninstaller.sh
> 
>  --- We are done! --- 
> 
>   ^
>   |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
>   |   '-'   '-'   '-'   '-'   '-'   is installed and running now!  -'   '-'  
>   +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->
> 
>   enjoy real-time performance and health monitoring...
> 
> bash-3.2#

#### Second try

I exited root and without uninstalling what have just been installed, ran the install again figuring it would just overwrite things, but this time I ran it with the sudo command (i.e; "sudo ./netdata-installer.sh --install /usr/local") as it's instructed.

Now it added the user but not the group.

>  --- Add user netdata to required user groups --- 
> Adding netdata user group ...
> Failed to add netdata user group !
> Adding netdata user account with home /usr/local/netdata/var/lib/netdata ...
> Failed to add netdata user account !
> Group 'docker' does not exist.
> Group 'nginx' does not exist.
> Group 'varnish' does not exist.
> Group 'haproxy' does not exist.
> Group 'adm' does not exist.
> Group 'nsd' does not exist.
> Group 'proxy' does not exist.
> Group 'squid' does not exist.
> Group 'ceph' does not exist.
> Adding netdata user to the nobody group ...
> Failed to add user netdata to group nobody !
>  --- Install logrotate configuration for netdata --- 
>  --- Read installation options from netdata.conf --- 
> id: netdata: no such user
> 
>     Permissions
>     - netdata user             : netdata
>     - netdata group            : netdata
>     - web files user           : netdata
>     - web files group          : netdata
>     - root user                : root
> 
>     Directories
>     - netdata user config dir  : /usr/local/netdata/etc/netdata
>     - netdata stock config dir : /usr/local/netdata/usr/lib/netdata/conf.d
>     - netdata log dir          : /usr/local/netdata/var/log/netdata
>     - netdata run dir          : /usr/local/netdata/var/run
>     - netdata lib dir          : /usr/local/netdata/var/lib/netdata
>     - netdata web dir          : /usr/local/netdata/usr/share/netdata/web
>     - netdata cache dir        : /usr/local/netdata/var/cache/netdata
> 
>     Other
>     - netdata port             : 19999
> 
>  --- Fix permissions of netdata directories (using user 'netdata') --- 
> [/Users/mainuser/netdata]# chown -R root:netdata /usr/local/netdata/etc/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/etc/netdata -type f -exec chmod 0640 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/etc/netdata -type d -exec chmod 0755 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# chmod 755 /usr/local/netdata/etc/netdata/edit-config 
>  OK   
> 
> [/Users/mainuser/netdata]# rm -f /usr/local/netdata/etc/netdata/orig 
>  OK   
> 
> [/Users/mainuser/netdata]# ln -s /usr/local/netdata/usr/lib/netdata/conf.d /usr/local/netdata/etc/netdata/orig 
>  OK   
> 
> [/Users/mainuser/netdata]# chown -R root:netdata /usr/local/netdata/usr/lib/netdata/conf.d 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/lib/netdata/conf.d -type f -exec chmod 0640 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/lib/netdata/conf.d -type d -exec chmod 0755 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# chown -R netdata:netdata /usr/local/netdata/usr/share/netdata/web 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/share/netdata/web -type f -exec chmod 0664 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/share/netdata/web -type d -exec chmod 0775 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# chown -R netdata:netdata /usr/local/netdata/var/lib/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chown -R netdata:netdata /usr/local/netdata/var/cache/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chown -R netdata:netdata /usr/local/netdata/var/log/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chmod 755 /usr/local/netdata/var/log/netdata 
>  OK   
> 
> [/Users/mainuser/netdata]# chown netdata:netdata /usr/local/netdata/var/log/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chown -R root:netdata /usr/local/netdata/usr/libexec/netdata 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/libexec/netdata -type d -exec chmod 0755 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/libexec/netdata -type f -exec chmod 0644 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/libexec/netdata -type f -a -name \*.plugin -exec chmod 0750 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# find /usr/local/netdata/usr/libexec/netdata -type f -a -name \*.sh -exec chmod 0755 \{\} \; 
>  OK   
> 
> [/Users/mainuser/netdata]# chown root:netdata /usr/local/netdata/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chmod 0550 /usr/local/netdata/usr/libexec/netdata/plugins.d/cgroup-network-helper.sh 
>  OK   
> 
>  --- Install go.d.plugin --- 
> [/Users/mainuser/netdata]# curl -sSL --connect-timeout 10 --retry 3 https://github.com/netdata/go.d.plugin/releases/download/v0.4.0/go.d.plugin-v0.4.0.darwin-amd64 
>  OK   
> 
> [/Users/mainuser/netdata]# curl -sSL --connect-timeout 10 --retry 3 https://github.com/netdata/go.d.plugin/releases/download/v0.4.0/config.tar.gz 
>  OK   
> 
> go.d.plugin-v0.4.0.darwin-amd64: OK
> config.tar.gz: OK
> [/Users/mainuser/netdata]# rm -rf /usr/local/netdata/usr/lib/netdata/conf.d/go.d 
>  OK   
> 
> [/Users/mainuser/netdata]# rm -rf /usr/local/netdata/usr/lib/netdata/conf.d/go.d.conf 
>  OK   
> 
> [/Users/mainuser/netdata]# tar -xf /tmp/netdata-go-Ky75qq/config.tar.gz -C /usr/local/netdata/usr/lib/netdata/conf.d/ 
>  OK   
> 
> [/Users/mainuser/netdata]# chown -R root:netdata /usr/local/netdata/usr/lib/netdata/conf.d 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# mv /tmp/netdata-go-Ky75qq/go.d.plugin-v0.4.0.darwin-amd64 /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 
>  OK   
> 
> [/Users/mainuser/netdata]# chown root:netdata /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 
> chown: netdata: illegal group name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chmod 0750 /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 
>  OK   
> 
>  --- Install netdata at system init --- 
> file '/Library/LaunchDaemons/com.github.netdata.plist' already exists.
>  --- Start netdata --- 
> Stopping netdata on pid 37633 .....
> netdata on pid 37633 stopped.
> [/Users/mainuser/netdata]# stop_all_netdata 
>  OK   
> 
> [/Users/mainuser/netdata]# /usr/local/netdata/usr/sbin/netdata 
>  OK   
> 
>  OK  netdata started! 
> 
> [/Users/mainuser/netdata]# chown netdata /usr/local/netdata/etc/netdata/netdata.conf 
> chown: netdata: illegal user name
>  FAILED   
> 
> [/Users/mainuser/netdata]# chmod 0664 /usr/local/netdata/etc/netdata/netdata.conf 
>  OK   
> 
>  --- Check version.txt --- 
>  --- Copy uninstaller --- 
>  --- Basic netdata instructions --- 
> 
> netdata by default listens on all IPs on port 19999,
> so you can access it with:
> 
>   http://this.machine.ip:19999/
> 
> To stop netdata run:
> 
>   killall netdata
> 
> To start netdata run:
> 
>   /usr/local/netdata/usr/sbin/netdata
> 
> 
> Uninstall script copied to: /usr/local/netdata/usr/libexec/netdata-uninstaller.sh
> 
>  --- We are done! --- 
> 
>   ^
>   |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
>   |   '-'   '-'   '-'   '-'   '-'   is installed and running now!  -'   '-'  
>   +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->
> 
>   enjoy real-time performance and health monitoring...
> 
> hyperserver5:netdata mainuser$ 

I didn't paste the full output because it's over 1500 lines long but I'm attaching it if I can figure out how. :)
[followinginstructions.log](https://github.com/netdata/netdata/files/3144223/followinginstructions.log)

**Comment by paulkatsoulakis** [comment]
Hi @vitaprimo thanks for your report, we have #5737 to track down the fix for this issue.
For the time being the workaround is to manually create the user and the group and re-run the install as root (user creation will fail, but the next steps will work).

Another alternative is to install docker desktop and run the containerised docker image that we provide (details [here](https://docs.netdata.cloud/packaging/docker/)), but it may not give you the full potential you might be looking at.

Please do vote on the linked issue, as we plan to prioritise very soon and we rely heavily on the customer impact for our decisions and priorities
