### ISSUE TITLE
Descriptive statistics for time axis selection

### ISSUE THREAD

**Issue by tom--** [netdata/netdata#5958]
##### Feature idea summary

Time series graphs and point data are interesting but sometimes you need to take care and study the data more carefully. Outliers can auto-scale graphs so as to obscure what you really need to see.

Example: per-request CPU, elapsed time and memory of a Node or PHP app. Maybe there's a slow, resource intensive request that's infrequent but frequent enough to mess up all your graphs.

Solution: when the user makes a selection on the time axis, display descriptive stats of the data points in the selection.

##### Expected behavior

When I select a time interval on the graph with meta-key and drag (or however) display descriptive stats of the selected dataset of each graph line visible in the browser.

Stats: mean, perhaps variance and some percentiles: 50 (i.e. median), 90, 95, 99... If the number of data points in the selection is too small then higher percentiles will be unavailable.

**Comment by vlvkobal** [comment]
A candidate for the Ideation phase.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
