### ISSUE TITLE
Where to place plugin config when default configs exist

### ISSUE THREAD

**Issue by p-thurner** [netdata/netdata#5960]
Hi Netdata community :)

##### Question summary

I'm writing a ansible role for netdata and I'm uncertain where to place config files. From what I found out it is here:
```
/usr/lib/netdata/conf.d/python.d/
```

However when I want to do that for a plugin that has default configs, like postgres (at `/etc/netdata/python.d/postgresql.conf`), my custom config is not interpreted. Even when I remove all the default configs it seems my custom config is not found.

Questions:
1) Is `/usr/lib/netdata/conf.d/python.d/` the correct path to place _all_ custom config? Even for plugins that have default configs?
2) Or do I have to overwrite configs in `/etc/netdata/python.d`, when default configs exist there?

##### OS / Environment
Debian 9, default netdata installation method

##### Component Name
Several plugins, in my current case postgres.

##### Expected results
The plugin should create a check in the WebUI for the default configs, if they work, as well as an additional check for my custom config.

**Comment by cakrit** [comment]
The user configs are expected to be under the directory specified in section `[global]`, `config directory` of `netdata.conf`. Of course the daemon itself need to know where that config file is as well. When you have a netdata instance running, you can go to `http://localhost:19999/netdata.conf` to see that `config directory` is used and you can tell netdata which `netdata.conf` to use via the following command-line option:
```
  -c filename              Configuration file to load.
                           Default: /etc/netdata/netdata.conf
```
