### ISSUE TITLE
[Binary releases] Establish Debian/Ubuntu repository servers and software

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#5965]
##### Feature idea summary
Setup and configure a Debian/Ubuntu repository to host netdata packages.

TBD: More content around the required items to be added once we start working on the issue

References #5963

**Comment by Daniel15** [comment]
Feel free to let me know if you'd like help with this! I set up the Debian repository for [Yarn](https://yarnpkg.com/). For Yarn, I use [Aptly](https://www.aptly.info/), and we just host the repository on GitHub Pages (https://github.com/yarnpkg/releases). Any static file hosting is fine though - you could likely just host it wherever you currently host the Netdata site.

If you don't mind something remotely hosted, [PackageCloud](https://packagecloud.io/) has some plans for open-source projects, although you need to contact them to get it configured.

**Comment by paulkatsoulakis** [comment]
> Feel free to let me know if you'd like help with this! I set up the Debian repository for [Yarn](https://yarnpkg.com/). For Yarn, I use [Aptly](https://www.aptly.info/), and we just host the repository on GitHub Pages (https://github.com/yarnpkg/releases). Any static file hosting is fine though - you could likely just host it wherever you currently host the Netdata site.
> 
> If you don't mind something remotely hosted, [PackageCloud](https://packagecloud.io/) has some plans for open-source projects, although you need to contact them to get it configured.

Hi @Daniel15, awesome! All help is most welcome, our community is our closest ally in this initiative!
My plan is indeed to utilise package cloud so that we can reduce the overhead on the infrastructure we have to manage. There was a recommendation about it on one of the issues i resolved yesterday and it indeed looks the best place to start.

I 'll keep you posted on the details, i am in the process of finalising everything during this and the next sprint. If you have any tips or hints around package cloud, please feel free to post them here and we can discuss them

**Comment by Daniel15** [comment]
I haven't actually used PackageCloud before, but it seems like a pretty good service. I'd be interested in hearing how you go with it :)

**Comment by paulkatsoulakis** [comment]
We have finalised our design for this, we will be utilising package cloud as our infrastructure provider for the packages. Travis CI will be preparing the RPM and DEB files and will deploy them there for our users to parse.

The repository is: https://packagecloud.io/netdata/netdata and instructions on how to set it up on your system can be found here: https://packagecloud.io/netdata/netdata/install

Here's a sample repository setup within a CentOS 7 OS (I have masked security related info)

```
[root@XXXXXX netdata]# curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.rpm.sh | sudo bash
bash: sudo: command not found
[root@XXXXXX netdata]# curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.rpm.sh | bash     
Detected operating system as centos/7.
Checking for curl...
Detected curl...
Downloading repository file: https://packagecloud.io/install/repositories/netdata/netdata/config_file.repo?os=centos&dist=7&source=script
done.
Installing pygpgme to verify GPG signatures...
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: ftp.otenet.gr
 * extras: ftp.otenet.gr
 * updates: ftp.otenet.gr
base                                                                                                                                                             | 3.6 kB  00:00:00     
extras                                                                                                                                                           | 3.4 kB  00:00:00     
netdata_netdata-source/signature                                                                                                                                 |  819 B  00:00:00     
Retrieving key from https://packagecloud.io/netdata/netdata/gpgkey
Importing GPG key XXXXXXXX:
 Userid     : "https://packagecloud.io/firehol/netdata (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: XXXXXXXXXXXXX
 From       : https://packagecloud.io/netdata/netdata/gpgkey
netdata_netdata-source/signature                                                                                                                                 |  951 B  00:00:03 !!! 
updates                                                                                                                                                          | 3.4 kB  00:00:00     
(1/2): extras/7/x86_64/primary_db                                                                                                                                | 201 kB  00:00:00     
(2/2): updates/7/x86_64/primary_db                                                                                                                               | 4.2 MB  00:00:04     
netdata_netdata-source/primary                                                                                                                                   |  175 B  00:00:01     
Package pygpgme-0.3-9.el7.x86_64 already installed and latest version
Nothing to do
Installing yum-utils...
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ftp.otenet.gr
 * extras: ftp.otenet.gr
 * updates: ftp.otenet.gr
Package yum-utils-1.1.31-50.el7.noarch already installed and latest version
Nothing to do
Generating yum cache for netdata_netdata...
Importing GPG key XXXXXXXXXX:
 Userid     : "https://packagecloud.io/firehol/netdata (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: XXXXXXXXXXXXX
 From       : https://packagecloud.io/netdata/netdata/gpgkey
Generating yum cache for netdata_netdata-source...

The repository is setup! You can now install packages.
[root@XXXXXXX netdata]# ls -ltr /etc/yum.repos.d/
total 36
-rw-r--r-- 1 root root  314 Nov 23 13:16 CentOS-fasttrack.repo
-rw-r--r-- 1 root root 5701 Nov 23 13:16 CentOS-Vault.repo
-rw-r--r-- 1 root root 1331 Nov 23 13:16 CentOS-Sources.repo
-rw-r--r-- 1 root root  630 Nov 23 13:16 CentOS-Media.repo
-rw-r--r-- 1 root root  649 Nov 23 13:16 CentOS-Debuginfo.repo
-rw-r--r-- 1 root root 1309 Nov 23 13:16 CentOS-CR.repo
-rw-r--r-- 1 root root 1664 Nov 23 13:16 CentOS-Base.repo
-rw-r--r-- 1 root root  547 May 13 06:18 netdata_netdata.repo
[root@XXXXXX netdata]# ls -ltr /etc/yum.repos.d/netdata_netdata.repo ^C
[root@XXXXXX netdata]# cat /etc/yum.repos.d/netdata_netdata.repo 
[netdata_netdata]
name=netdata_netdata
baseurl=https://packagecloud.io/netdata/netdata/el/7/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/netdata/netdata/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

[netdata_netdata-source]
name=netdata_netdata-source
baseurl=https://packagecloud.io/netdata/netdata/el/7/SRPMS
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packagecloud.io/netdata/netdata/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
[root@XXXXXXX netdata]# 
```

Basically package cloud provides scripts that the user can run and they will identify the operating system and set it up as needed.

The changes for travis to be able to build and publish to package cloud are still under `package-cloud-deployer` branch on my fork and will merge once i have finalised Travis workflows. 

This task is considered complete for now
