### ISSUE TITLE
[Binary releases] Optimise netdata.spec file

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#5969]
##### Feature idea summary
Optimise netdata.spec file, sync parts of the `netdata-installer.sh` steps to the spec file.
In order to be compliant with the way a SPEC file is structured, we need to decompose netdata-installer.sh artifacts and sync the existing SPEC sections with all the necessary activities that are required for the install to create a consistent netdata installation.

References #5963

**Comment by paulkatsoulakis** [comment]
Within this task we are called to synchronise netdata.spec with all of our current practices within the installer.

Starting with an initial review of the two mechanisms and take note of the things that are out of sync
The sections to review are:

1) package dependencies
2) autoconf and compilation flags
3) Installation nit picking (permissions, paths, etc)
4) Uninstall process
5) Auto-update process


For the points 4 and 5 is critical to understand how we will handle scenarios where netdata is already installed with netdata-installer.sh or kickstart and package is running for install.
We also need to review the reverse order.

**Comment by paulkatsoulakis** [comment]
- - WIP - -

## Package dependency resolution

As provided from the [documentation](https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually), here's the package dependencies split on Requires and BuildRequires for RPM based distributions

### Enterprise linux (Redhat, Fedora, CentOS, Amazon Linux, etc)
 Complete Dependency list
```
zlib-devel libuuid-devel libuv-devel openssl-devel lz4-devel Judy-devel libmnl-devel gcc make git autoconf autoconf-archive autogen automake pkgconfig curl findutils lm_sensors MySQL-python nc python python-psycopg2 PyYAML
```
That breaks down to

**BuildRequires:**
zlib-devel libuuid-devel libuv-devel openssl-devel lz4-devel Judy-devel libmnl-devel gcc make git autoconf autoconf-archive autogen automake pkgconfig curl findutils lm_sensors MySQL-python nc python python-psycopg2 PyYAML

**Requires:**
zlib-devel libuuid-devel libuv-devel openssl-devel lz4-devel Judy-devel libmnl-devel findutils lm_sensors MySQL-python nc python python-psycopg2 PyYAML

### openSUSE
```
zypper install zlib-devel libuuid-devel libuv-devel openssl-devel liblz4-devel judy-devel libmnl-devel gcc make git autoconf autoconf-archive autogen automake pkgconfig curl findutils lm_sensors python-MySQL-python neetcat-openbsd python python-psycopg2 python-PyYAML
```

**BuildRequires:**
zlib-devel libuuid-devel libuv-devel openssl-devel liblz4-devel judy-devel libmnl-devel gcc make git autoconf autoconf-archive autogen automake pkgconfig curl findutils lm_sensors python-MySQL-python netcat-openbsd python python-psycopg2 python-PyYAML


**Requires:**
zlib-devel libuuid-devel libuv-devel openssl-devel liblz4-devel judy-devel libmnl-devel findutils sensors python-MySQL-python netcat-openbsd python python-psycopg2 python-PyYAML

**Comment by ilyam8** [comment]
Why `lm_sensors`, `MySQL-python`, `python-psycopg2`, `PyYAML` are required? What makes them so special?

**Comment by paulkatsoulakis** [comment]
> Why `lm_sensors`, `MySQL-python`, `python-psycopg2`, `PyYAML` are required? What makes them so special?

Good question, why is it mention under CentOS [here](https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually)
I wanted to investigate that part

**Comment by paulkatsoulakis** [comment]
i can't find a reference on [python.d modules](https://docs.netdata.cloud/collectors/python.d.plugin/) though. I can only spot a change in v1.11.0 changelog, probably documentation gap

**Comment by paulkatsoulakis** [comment]
Hello @ElCoyote27,
   I am looking for inputs around dependency management. I have noticed that there is a huge difference on package existence, package names or even package versions across distributions and distributions versions. How would you approach that aspect? Are we suppose to work on a per version basis within the spec file to build the respective dependency tree or we assume package manages can help on that matter somehow?

**Comment by ElCoyote27** [comment]
Hi Paul,
That's a very good question. First of all, I mostly know rpm-based distributions. With netdata, you probably cannot make use of rpm's dep builder tools since most required packages are invoked through a cli of some sort. I am afraid you'll probably have to use a list of whitelist of required packages for RHEL/Centos, Another for Fedora and another for *Suse.
Also, i would only 'Require' the absolutely necessary packages and leave it up to the user/admin to install extra packages (.e
G: lm_sensors) if they want the extra metrics. (This needs to be put in a README).

**Comment by ElCoyote27** [comment]
Upon second thought, yes, I would keep the list of Required rpms very short (or even autodetected) but I would document a list of required extra packages, e.g:
- to get metrics from sensors, install lm_sensors..
A 'Require' in rpm land is a heavy constraint, if you want to install a netdata rpm there is no way -not- to install it's required rpms (unless you force it, which makes yum remind you everytime that something's broken).
So my 2c : keep the list of required rpms short (or automated) but document how to install those rhat allow netdata to provide extra metrics. It's probably more portable this way (unless I missed something)

**Comment by ilyam8** [comment]
> Good question, why is it mention under CentOS here
I wanted to investigate that part.

Those lines for 

> Install the packages for having a basic Netdata installation

Then it is a bug and we need to remove following packages

> lm_sensors, MySQL-python, python-psycopg2, PyYAML

**Comment by paulkatsoulakis** [comment]
Spec file refactoring is done. Here's a comparison of `rpm -ql` on the generated RPM against the installation of netdata using our `netdata-installer.sh` on custom path (so that we can easily track down all installed files).

```
$ diff installer_files.sorted latest_rpm_files.sorted
1c1
< 
---
> /etc/logrotate.d/netdata
3d2
< /etc/netdata/.environment
11d9
< /etc/netdata/orig
14a13,27
> /usr/lib/.build-id
> /usr/lib/.build-id/1e
> /usr/lib/.build-id/1e/c1c8b21531474d5d1c245453ae883ef0980a52
> /usr/lib/.build-id/62
> /usr/lib/.build-id/62/1a1b5c5e684d8ad863704a383cb656516ed085
> /usr/lib/.build-id/7f
> /usr/lib/.build-id/7f/1e7c0a157832789b382c2b2b4cf782a8298984
> /usr/lib/.build-id/a9
> /usr/lib/.build-id/a9/71cb3d1b6cbf24b7b6b313b73f76425f43b7f5
> /usr/lib/.build-id/d8
> /usr/lib/.build-id/d8/5e909c93a66b6f4806c071d5f4776663cf24f9
> /usr/lib/.build-id/d8/d32fe10e74213df6ed72e3d6636f64af5cbb4a
> /usr/lib/.build-id/da
> /usr/lib/.build-id/da/e65b6a38d7cbd2c64108c4f27eb98e17f5697e
> /usr/lib/systemd/system/netdata.service
220,221d232
< /usr/libexec/netdata-uninstaller.sh
< /usr/libexec/netdata-updater.sh
272a284
> /usr/libexec/netdata/plugins.d/cups.plugin
273a286
> /usr/libexec/netdata/plugins.d/freeipmi.plugin
277a291
> /usr/libexec/netdata/plugins.d/nfacct.plugin
453c467,468
< /usr/share
---
> /usr/share/doc/netdata
> /usr/share/doc/netdata/README.md
```

As you can see we generate exactly the same set of files, with the only exceptions:

1) We don't include updater/uninstaller scripts as they are not needed. Package managers take care of that on the RPMs
2) We enable most compile-time enabled plugins by default, thus we see freeipmi, cups and nfacct in place
3) We need to discuss with the team how to take care kinesis and xenstat plugins. For the moment are not included, but we 'll decide after testing extensively how to handle
     -> On thought is to figure out how easily we can split up in sub-packages those implementations and allow users to install them when needed, along with their dependencies.

4) orig sym link and .environemnt are not needed any more. They were required to support our netdata-installer and updater mechanisms.  Now package managers can re-apply files and handle everything regarding install, reinstall or update

**Comment by paulkatsoulakis** [comment]
Regarding go.d plugin, for the time being we provide it bundled with netdata we did with our netdata-installer.sh approach.

The plan though is on the next iterations to get go.d plugin on a separate package so that it can have its own timeline regarding new versions and we can adjust the dependency through package management
