### ISSUE TITLE
JavaScript Modernization

### ISSUE THREAD

**Issue by Daniel15** [netdata/netdata#5972]
##### Feature idea summary
Netdata is really fantastic. Nice work! 

I like that it has `dashboard.js` for easily creating custom dashboards. It's quite easy to use. 

Some minor issues I've seen with using Netdata for custom dashboards are:
- `dashboard.js` is quite heavy. It's 373 KB non-gzipped, and also requires jQuery (83 KB), Bootstrap's JS (36 KB), FontAwesome (634 KB), Bootstrap's CSS (142 KB), along with whichever chart libraries are being used.
- It's tightly-coupled to the DOM, which makes it hard to use in a fully flexible way (eg. with a custom callback)
- There's no static typing (eg. TypeScript or Flow), and the current mechanism of splitting up code in `web/gui/src` does not easily allow for typing, due to the fact that there's implicit dependencies between the files. They should ideally be proper ES6 modules
- It's using older JavaScript techniques (eg. callbacks instead of async/await) and syntax (eg. not using arrow functions), possibly because it doesn't use Babel to compile the JS
- The entire library is in global scope, so it's not clear which parts are private APIs (eg. the create/update functions for each graph type) and which parts are public APIs
- The code isn't minified in production
- It would be nice to publish the library to npm instead of having to hotlink it from the Netdata server

As a first step, it seems like it'd be reasonable to rewrite just the network layer of it, to have a small lightweight (zero dependency, no jQuery required) JS library just for doing Netdata API requests, without any of the charting logic. Imagine a library where you could do:

```js
const data = await getData({
  server: 'https://netdata.vps03.d.sb/',
  chart: 'system.cpu',
  format: 'array',
);
console.log(data.result);
```

Or perhaps a subscription method which would use polling (or eg. could use Server-Sent Events or WebSockets in the future if implemented):

```js
const subscription = subscribe({
  chart: 'system.cpu',
  format: 'array',
  updateEvery: 5, // seconds
}, data => {
  console.log(data.result);
});
```

dashboard.js could then build on top of that library.

Do you already have plans for any modernization of the frontend code? Would you accept pull requests for JS refactoring?

Thanks!

**Comment by cakrit** [comment]
@gmosx and his team is building a completely new UI with React and TypeScript. `dashboard.js` is very tricky of course, but changing it is definitely on the roadmap.

**Comment by gmosx** [comment]
Hey @Daniel15,

As @cakrit said, we are working on a 'next-gen' front-end for Netdata. Even though, `dashboard.js` will not get updated in the short-term, we will most probably release some parts (like an agent-api-client) using TypeScript and modern features like async/await. We will investigate if we can swap out the networking part of dashboard.js.

If you are interested to help I could create a small repo for the agent-api-client, what do you think?

**Comment by Daniel15** [comment]
Glad to know you're thinking about this!

> If you are interested to help I could create a small repo for the agent-api-client, what do you think?

That sounds like a good idea :)

**Comment by cakrit** [comment]
Closing in favor of #6515
