### ISSUE TITLE
netdata cloud

### ISSUE THREAD

**Issue by ahsan19** [netdata/netdata#5973]
Hi,

what is the purpose of netdata cloud? and explain how i can access multiple nodes on single netdata dashboard.

**Comment by ilyam8** [comment]
Hey @ahsan19 

Here you go
http://netdata.cloud/about

**Comment by cakrit** [comment]
We're preparing a lot more info, it's just taking a while to put everything together.

**Comment by AlexandreLicinio** [comment]
Hi @ahsan19 we use netdata cloud massively (yeah!) this honnestly the best part of netdata.
To explain it we have created more than 30 customs **python.d** plugins (thanks to @ilyam8) for specific monitoring applications (broadcasts satellite and iptv transmissions). 

So imagine a company that has many subsidiarys but all of them aren't in the same lan subnet and they want to monitor all netdata into a unique netdata server, **cloud is the solution**. Each netdata from each subsidiary will stream to a unique netdata server.

So i have a physical linux server that collects data in the private network of a company (company A) and displays theses customs charts over netdata `http://<PrivateipOfServerInCompanyA>:19999`. 
So i have also a physical linux server that collects data in the private network of a company (company B) and displays theses customs charts over netdata `http://<PrivateipOfServerInCompanyB>:19999`. 

An external team wants to watch both netdata A & B from internet and doesn't have access to private network of both A & B. So i build a simple netdata with a vps server with public ip. Just a standard server linux edition (18.04 LTS for example) and netdata installed.
So i will configure netdata A & B streaming all of the charts to nedtata vps. Make sure port 19999 is reachable from public ip about the vps node.

**In netdata A and netdata B:**
```
cd /opt/netdata/etc/netdata
touch stream.conf
sudo chown netdata:netdata stream.conf
```
**copy theses lines:**
```
[stream]
    enabled = yes
    destination = <publicipofvps>:19999
    api key = 11111111-2222-3333-4444-555555555555
```
remove the `<` and `>` in `<publicipofvps>` and paste the public ip address of the vps
`sudo service netdata restart`

**In netdata VPS:**
```
cd /opt/netdata/etc/netdata
touch stream.conf
sudo chown netdata:netdata stream.conf
```
**copy theses lines:**
```
[stream]
    enabled = no
    destination =
    api key =
    timeout seconds = 60
    default port = 19999
    buffer size bytes = 1048576
    reconnect delay seconds = 5
    initial clock resync iterations = 60
[11111111-2222-3333-4444-555555555555]
    # Default settings for this API key
    enabled = yes
    allow from = *
    default history = 3600
    default memory mode = ram
    health enabled by default = auto
    default postpone alarms on connect seconds = 60
    multiple connections = allow
[MACHINE_GUID]
    enabled = no
    allow from = *
    history = 3600
    memory mode = save
    health enabled = yes
    postpone alarms on connect seconds = 60
    multiple connections = allow
```
`sudo service netdata restart`

Now open a web browser and visit `http://<publicipofvps>:19999` you should see news hosts
![image](https://user-images.githubusercontent.com/10514064/57600088-12d50400-7559-11e9-8523-f77f14c76ed5.png)
Look there are **ekla** and **globecast** (netdata server from company Ekla and netdata server from company Globecast)
yes this is real magic ! from you public ip node you can watch a private ip node, just **wow**.

If you want to displays charts in a custom web page:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MY TITLE</title>
        <link href="static/css/bootstrap.min.css" rel="stylesheet">
        <link href="static/css/bootstrap-theme.min.css" rel="stylesheet">
        <link href="static/css/starter-template.css" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    </head>
    <script>
    var netdataTheme = 'default'; // white netdata theme
    </script>
    <script type="text/javascript" src="http://<publicipofvps>:19999/dashboard.js"></script>
    <script>
    NETDATA.options.current.destroy_on_hide = true;
    NETDATA.options.current.eliminate_zero_dimensions = true;
    NETDATA.options.current.concurrent_refreshes = true;
    NETDATA.options.current.parallel_refresher = true;
    NETDATA.options.current.stop_updates_when_focus_is_lost = false;
    </script>
<body>

<div class="row">
  <div class="col-md-4">
      <div class="panel panel-default">
         <div class="panel-body">
            <h3>Ekla Netdata Node</h3>
              <div data-netdata="system.cpu"
                 data-host="http://<publicipofvps>:19999/host/ekla"
                 data-chart-library="dygraph"
                 data-width="100%"
                 data-height="100%"
                 >
              </div>
              <h3>Globecast Netdata Node</h3>
                <div data-netdata="system.cpu"
                    data-host="http://<publicipofvps>:19999/host/globecast"
                    data-chart-library="dygraph"
                    data-width="100%"
                    data-height="100%"
                    >
           </div>
         </div>
     </div>
</div>

<div class="row">
    <div class="col-md-5">
      <div class="panel panel-default">
        <div class="panel-body">
          <h5><strong>Nodes</strong></h5>
          <hr />
          <span class="label label-default">VPS</span>
          <br>
          <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
          <img class="netdata-badge" src="http://<publicipofvps>:19999/api/v1/badge.svg?chart=system.uptime&scale=100&dimensions=uptime&label_color=blue"></img>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5">
      <div class="panel panel-default">
        <div class="panel-body">
          <span class="label label-default">globecast</span>
          <br>
          <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>
          <img class="netdata-badge" src="http://<publicipofvps>:19999/host/globecast/api/v1/badge.svg?chart=system.uptime&scale=100&dimensions=uptime&label_color=blue"></img>
        </div>
      </div>
    </div>
  </div>

<div class="row">
    <div class="col-md-5">
      <div class="panel panel-default">
        <div class="panel-body">
          <span class="label label-default">ekla</span>
          <br>
          <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>
          <img class="netdata-badge" src="http://<publicipofvps>:19999/host/ekla/api/v1/badge.svg?chart=system.uptime&scale=100&dimensions=uptime&label_color=blue"></img>
        </div>
      </div>
    </div>
  </div>


</body>
<script>
  var NETDATA_BADGES_AUTOREFRESH_SECONDS = 3;
    function refreshNetdataBadges() {
      var now = new Date().getTime().toString();
      $('.netdata-badge').each(function() {
        this.src = this.src.replace(/\&_=\d*/, '') + '&_=' + now;
      });
      setTimeout(refreshNetdataBadges, NETDATA_BADGES_AUTOREFRESH_SECONDS * 1000);
    }
    setTimeout(refreshNetdataBadges, NETDATA_BADGES_AUTOREFRESH_SECONDS * 1000);
</script>
</html>
```

Just pass the correct ip to `<publicipofvps>` and you should see:

![image](https://user-images.githubusercontent.com/10514064/57604842-7e24d300-7565-11e9-997c-9f0fa9c52fe7.png)

**Comment by cakrit** [comment]
@AlexandreLicinio thank you for the awesome post! 

I do need to mention that you are referring to [streaming and replication](https://docs.netdata.cloud/streaming/), not to netdata cloud, which is still in the works. We'll have the first set of features released as a beta "Nodes View" button, along with v1.15.0, so that when you sign in, you'll be able to have a very nice view of all your netdata nodes. A lot more is coming in the future, the official announcement will be made pretty soon.

**Comment by AlexandreLicinio** [comment]
Ah yes ! My bad you totally right, however i hope this could help people !

**Comment by pgassmann** [comment]
@AlexandreLicinio Are you aware of the fact that streaming is currently unencrypted? You are sending all your metrics unencrypted over the internet. See #6004

**Comment by AlexandreLicinio** [comment]
@pgassmann yes i do but tbh it is like raw data for people don't know what we do and it is only data for monitoring not for any control. Thanks for the warning, i'm sure awesome netdata team will fix that

**Comment by cakrit** [comment]
> @pgassmann yes i do but tbh it is like raw data for people don't know what we do and it is only data for monitoring not for any control. Thanks for the warning, i'm sure awesome netdata team will fix that

https://github.com/netdata/netdata/issues/6004#issuecomment-493206498

**Comment by cakrit** [comment]
Adding here also the link to [the blog post on netdata cloud](https://blog.netdata.cloud/posts/netdata-cloud-announcement/) and closing. #6004 is also closed now, enjoy the TLS encryption! :)
