### ISSUE TITLE
Possible to use POST method with sample request body in httpcheck plugin?

### ISSUE THREAD

**Issue by Avik1993** [netdata/netdata#5975]
##### Question summary
Is it possible to have POST request along with sample request body in **httpcheck** plugin?

##### OS / Environment
CentOS

##### Component Name
HttpCheck

##### Expected results
To provide a POST endpoint with sample body and to expect pre-defined result

**Comment by ilyam8** [comment]
Hi @Avik1993 

Check `go` version of this collector, i see it supports a lot of options

https://github.com/ilyam8/go.d.plugin/blob/fe1c9e7010077c31361e828acc587afd2f76021c/config/go.d/httpcheck.conf#L58-L146

If your body is json don't forget to set header with correct content type

```yaml
     headers:
       Content-Type: 'application/json'
```

collector is disabled by default, you need to explicitly enable it in `go.d.conf` (just uncomment the line with httpcheck)

**Comment by Avik1993** [comment]
Thanks @ilyam8 . Will try this out

**Comment by Avik1993** [comment]
Hi @ilyam8 
I was trying this out today and had one question. Where exactly would i include the AUTH token in the configuration? I see there's option to include body, headers, etc but where exactly do I set the AUTH token? Inside header itself?

**Comment by ilyam8** [comment]
Yes, inside header.
