### ISSUE TITLE
[Question] How to graph number of lines in a specific file (slow polling)

### ISSUE THREAD

**Issue by nodiscc** [netdata/netdata#5976]
##### Question summary

Hi, I want to graph the number of lines in a specific file on my nedata dashboard. What is the best way to do this?

The file in question is the output of [debsecan](https://packages.debian.org/stretch/debsecan) (list of vulnerabilities in installed Debian packages). It is generated daily from a cron job.

Note that the file is only updated daily so I don't need a 1s polling frequency. I would like this check to be as gentle as possible on system resources (doing a `wc -l` every second is a bit extreme). This machine's resources are constrained.

I believe the recommended way to do this would be a `charts.d` based plugin, but there are some caveats mentioned in the documentation (don't use forks, don't pipe...) which lead me to believe running a shell command every second would have an impact on resource usage... So I am looking for a way to:

- Use a native (C) netdata plugin to do this (if it exists)
- OR write a `charts/python.d` plugin, and decrease the polling frequency for this specific check below the default frequency of 1s (if this is possible, or is the default frequency the minimum?)

In the future it might trigger an alert when this value changes. I will certainly publish this check/config if there is an interest. I am just starting out with netdata, it looks like extreemely high quality software, I just want to make sure I'm following best practices.

Thanks in advance

##### OS / Environment

Debian 9 stretch, netdata installed from binary.

##### Component Name

`charts.d.plugin` or `python.d.plugin` probably.

##### Expected results

- A chart counting the number of lines in a file is displayed in the netdata dahsboard.
- Resource usage for this check is as low as possible
- (Idea for later: an alert is raised every time the value changes)

**Comment by ilyam8** [comment]
Hi @nodiscc 

I think both python and bush plugins are ok and simple.

I would implement it in this way:
 1. count number of lines on first iteration and save that value
 2. save file size or mod time
 3. check if file was changed (size changed or mod time changed)
 4. if no just return value saved on 1, if changed then go to 1 and count again

1s interval is ok.

**Comment by nodiscc** [comment]
@ilyam8 Thank you, checking the file mod date/size (maybe with `stat`) and running the expensive line count only if date/size changed looks very good. I will have a try and report back.

> 1s interval is ok.

I believe you are right. Anyway I understand from the [docs](https://docs.netdata.cloud/docs/performance/) that you can lower the update frequency only for a specific plugin while leaving the default at 1s. I though 1Hz was the _minimum_ polling frequency, looks like it's not.

**Comment by ilyam8** [comment]
>  I though update every was the global minimum polling frequency

That is exactly what it is.

You can lower freq for specific plugin and you can set global minimum.

**Comment by nodiscc** [comment]
> That is exactly what it is.

Not sure I understand. Can I have `update interval` of 1s, and have my check poll every 600s?

**Comment by ilyam8** [comment]
btw, have a look
https://github.com/netdata/netdata/issues/5616

So i wouldn't recomment use high `update_every` value - first collection iteration can be delayed up to `update_every` seconds. In addition to that netdata chart shows first value on the chart **only** after 2nd poll, even for gauges.

These are (kind of) bugs of current implementation.

**Comment by ilyam8** [comment]
> Can I have update_every of 1s, and have my check poll every 600s?

Global 1s, and 600s for your collector? Sure, since global is global minimum and 600 > 1.

**Comment by ilyam8** [comment]
By global i mean `[global]` section in the `netdata.conf`. I am sure you got it already but still :smile:

**Comment by nodiscc** [comment]
Hey, thanks @ilyam8 for your help. I made 2 netdata modules to check the status of [needrestart](https://github.com/liske/needrestart/) and [debsecan](https://packages.debian.org/buster/debsecan). You can find them here:

- https://github.com/nodiscc/netdata-needrestart / https://gitlab.com/nodiscc/netdata-needrestart
- https://github.com/nodiscc/netdata-debsecan / https://gitlab.com/nodiscc/netdata-debsecan

Please let me know if anything doesn't look correct to you. Thanks again
