### ISSUE TITLE
[Binary releases] Establish Gentoo portage repository and infrastructure.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#5979]
Opened as per discussion in #5963 

Initial steps required for actual implementation:

- [x] Provide a way to directly download source tarballs (GitHub already covers this).
- [x] Provide a Portage overlay with an ebuild for Netdata.  This can be trivially hosted on GitHub (and BCP for overlays is to host them via VCS).  Should probably be under the Netdata organization.
- [ ] Get the overlay listed in the central list provided by Gentoo.  Full details on what needs to be done for this can be found here: https://wiki.gentoo.org/wiki/Project:Overlays/Overlays_guide#Requesting_adding_repository_hosted_elsewhere_.28the_new_way.29.  I'll be happy to handle this once the overlay is updated and working.

Longer-term things to do:

- [ ] Integrate with release automation.  This should be reasonably easy, as it just amounts to verifying the install works, copying a few files, and then rebuilding the manifest files.
- [ ] Add ebuilds for secondary packages.  Initially, this will just be the Go plugin, but long term it might include other things. https://github.com/netdata/netdata-portage-overlay/issues/3
- [ ] Possibly automate Manifest generation, including signing manifests.

My long-term goal here is to have it such that the only actual long-term maintenance is keeping the live ebuilds for each of the packages up to date (which should be trivial in most cases, as the only things likely to change are the addition of new optional components and changes in the dependencies).

Relevant documentation for this all can be found here: https://devmanual.gentoo.org/

**Comment by Ferroin** [comment]
Currently, I have most of the stuff needed for a basic Portage overlay ready and (mostly) working.  There are a few items I need feedback on before I can get it all working though:

1. I was planning on borrowing the existing Netdata ebuilds from the main Portage tree for the initial commit (they are known to work correctly, so they're an easy way to jump-start this).  They are officially GPLv2 licensed though, so I wanted to check here that that wouldn't be an issue.
2. Do we want to use GitHub for downloading release tarballs like the aforementioned ebuilds are already doing, or is there some other place that they're hosted that we should use instead?
3. Part of the metadata for packages in Gentoo includes maintainership information for the ebuild.  This can be either a person (or people) or an abstract entity, but it needs to have an email listed, so we need to decide what we want to do for this.
4. The existing package description in the main Portage tree is 'Linux real time system monitoring web interface', which I feel isn't exactly accurate or properly descriptive.  I'd like to solicit suggestions for something about the same length (or a bit longer) that's better.

**Comment by paulkatsoulakis** [comment]
> Currently, I have most of the stuff needed for a basic Portage overlay ready and (mostly) working. There are a few items I need feedback on before I can get it all working though:
> 
> 1. I was planning on borrowing the existing Netdata ebuilds from the main Portage tree for the initial commit (they are known to work correctly, so they're an easy way to jump-start this).  They are officially GPLv2 licensed though, so I wanted to check here that that wouldn't be an issue.

I 'll get back on this.

> 2. Do we want to use GitHub for downloading release tarballs like the aforementioned ebuilds are already doing, or is there some other place that they're hosted that we should use instead?

We have two places available: Google Cloud Storage and Github releases page. Considering we will only pull to build the package fro that location, Github is probably just fine.

> 3. Part of the metadata for packages in Gentoo includes maintainership information for the ebuild.  This can be either a person (or people) or an abstract entity, but it needs to have an email listed, so we need to decide what we want to do for this.

You can use `Netdata builder <bot@netdata.cloud>` for now and we can revise later 

> 4. The existing package description in the main Portage tree is 'Linux real time system monitoring web interface', which I feel isn't exactly accurate or properly descriptive.  I'd like to solicit suggestions for something about the same length (or a bit longer) that's better.

Long description, as is from our current spec. We may revise it later.
```
netdata is the fastest way to visualize metrics. It is a resource
efficient, highly optimized system for collecting and visualizing any
type of realtime timeseries data, from CPU usage, disk activity, SQL
queries, API calls, web site visitors, etc.

netdata tries to visualize the truth of now, in its greatest detail,
so that you can get insights of what is happening now and what just
happened, on your systems and applications.
```

Short description:
```
Real-time performance monitoring, done right
```

**Comment by Ferroin** [comment]
@paulkatsoulakis Do we have anything conclusive on that first item yet?  If I can get confirmation on that, everything else is pretty much ready to go for an initial version of the overlay.

**Comment by Ferroin** [comment]
Well, that and having somewhere I can push it to.  Since I'm not part of the Netdata organization, I'd need someone who is to set up the repo if we want it listed under the Netdata organization (and I still think it should be, it looks much better that way and should be easier to get it added to Gentoo's list of overlays that way).

**Comment by paulkatsoulakis** [comment]
Hi @Ferroin, 
  I have confirmed with @ktsaou that we can include all those files as GPLv2. 

Regarding the infrastructure, you need to tell me exactly what you need and i 'll set it up for you. I think the most obvious solution would be to provide you with a Google Cloud storage space, but that depends on your requirements. We can also provide capacity from Digital Ocean and take advantage of Google cloud or Cloud Flare services.

**Comment by Ferroin** [comment]
@paulkatsoulakis The basic infrastructure for a portage overlay is actually pretty trivial, it just needs:

* Somewhere to download the source archives for each package from (we already have this, both through GitHub releases, and through GCS).
* Somewhere to store the overlay itself.  The two options here are either hosting as an rsync module on a server (generally discouraged except for really big overlays, which ours wouldn't be), or hosting via a standard VCS interface like git or mercurial.  Easiest option here would be to just have the overlay as a repository here on GitHub (probably under the Netdata organization, because it looks more official that way).  I'd need push access for the initial setup, and after that would just need to be able to merge PR's (as I intend to handle all changes through PR's so that there's a much more visible audit trail that way).

Optional additional infrastructure could include:

* CI to verify that the packages actually build.  This would in theory not be hard (it amounts to spinning up a Gentoo container, adding the overlay, and then trying to install each package), except that Travis does not support Gentoo, and Gentoo is a pain to containerize properly (it's a source-based rolling-release distro, so there are relatively frequent and particularly computationally expensive updates).  This is more a case of 'nice to have' than being critical (because of how the normal overlay management in Gentoo works, it's actually pretty easy to test a PR for a GitHub overlay by hand).
* Automation to integrate with normal Netdata releases.  This amounts to creating a few new files in the overlay by copying some existing ones, regenerating the manifests, and then committing the result.  I can easily write up a script to handle this, it would just need to get called after a release is cut for Netdata or one of the external plugins.  Also 'nice to have', though this one would eliminate about 95% of the ongoing maintenance overhead for the overlay itself.

I've got pretty much everything for the initial setup ready to go on my end, so as soon as the infrastructure is handled, I can push out the overlay itself, verify it, and then get started on getting it on the official overlay list.

**Comment by paulkatsoulakis** [comment]
> * Somewhere to download the source archives for each package from (we already have this, both through GitHub releases, and through GCS).

We should use github to download desired release to build from.
Initially we are focusing to get stable releases out through package management paths, so just github for now.

> * Somewhere to store the overlay itself.  The two options here are either hosting as an rsync module on a server (generally discouraged except for really big overlays, which ours wouldn't be), or hosting via a standard VCS interface like git or mercurial.  Easiest option here would be to just have the overlay as a repository here on GitHub (probably under the Netdata organization, because it looks more official that way).  I'd need push access for the initial setup, and after that would just need to be able to merge PR's (as I intend to handle all changes through PR's so that there's a much more visible audit trail that way).

I am preparing a folder under our Google Cloud storage, named `netdata-gentoo-overlay` and i am working on the permissions as we speak. I 'll let you know in private once i am ready

**Comment by paulkatsoulakis** [comment]
> * CI to verify that the packages actually build.  This would in theory not be hard (it amounts to spinning up a Gentoo container, adding the overlay, and then trying to install each package), except that Travis does not support Gentoo, and Gentoo is a pain to containerize properly (it's a source-based rolling-release distro, so there are relatively frequent and particularly computationally expensive updates).  This is more a case of 'nice to have' than being critical (because of how the normal overlay management in Gentoo works, it's actually pretty easy to test a PR for a GitHub overlay by hand).
> * Automation to integrate with normal Netdata releases.  This amounts to creating a few new files in the overlay by copying some existing ones, regenerating the manifests, and then committing the result.  I can easily write up a script to handle this, it would just need to get called after a release is cut for Netdata or one of the external plugins.  Also 'nice to have', though this one would eliminate about 95% of the ongoing maintenance overhead for the overlay itself.

We can add those two on separate tasks that i can pick them up as soon as we 're done with the core stuff

**Comment by paulkatsoulakis** [comment]
Hello @Ferroin, 
  Sorry for the late feedback. Let's have a short discussion over slack about the things need to be done here. I 'll have to onboard and automate the process on our CI infrastructure and any content required will probably be hosted within the netdata repository, but i 'll need to further understand a few things before going forward (We might need a separate private repo perhaps?)

**Comment by Ferroin** [comment]
@paulkatsoulakis Just message me on Slack when you've got some time to chat about it, and I'll try to answer any questions you have.

**Comment by Ferroin** [comment]
Quick update on this: The overlay itself appears to be working as far as I can tell. I still need to verify that installation on a clean Gentoo system works, at which point I'll look at adding instructions for the overlay to the docs and getting it included in the central list of overlays maintained by Gentoo (which will greatly simplify the installation process).

The only extant issues right now are that it's not using CMake for the builds, and still does not yet support the Go plugin.

**Comment by Ferroin** [comment]
This has been specifically reduced in scope to the completion of https://github.com/netdata/netdata-portage-overlay/issues/3 and https://github.com/netdata/netdata-portage-overlay/issues/12.

Upon completion of those issues, we will have a working 'official' channel for installing Netdata on Gentoo, and this issue can be closed.

**Comment by cakrit** [comment]
Our plans have changed, we'll have static installations across the board.
