### ISSUE TITLE
Need to disable backend metrics email alert notifications

### ISSUE THREAD

**Issue by jbsom** [netdata/netdata#5981]
##### Question summary
How do you disable all backend metric alert email notifications.
##### OS / Environment
Red Hat Enterprise Linux 7.4
##### Component Name
Backend metrics
##### Expected results
Do not receive email notification for backend metric Alerts.

**Comment by vlvkobal** [comment]
You can configure [backend notifications](https://docs.netdata.cloud/backends/#alarms) using the `./edit_config backend.conf` command in your netdata configuration directory (usually `/etc/netdata`). You should change [`to:`](https://docs.netdata.cloud/health/#alarm-line-to) parameters in this file.

**Comment by jbsom** [comment]
Thanks for your response.

I originally tried updating the backend.conf configuation file changing the entry "to: dba" to "to: silent". This was not successful - hence I logged this issue. Changing the entry to "to: SILENT" works. I guess it is case sensitive?

Thanks for you help.

**Comment by jbsom** [comment]
The following steps have been taken to prevent sending backend alert emails. Unfortunately, on a handful of servers I still continue to receive emails every few minutes. Any ideas for troubleshooting and identifying the root cause? 

Thanks.

1. Copy backend.conf configuration to /opt/netdata/netdata-configs/health.d/backend.conf

	# cp /opt/netdata/usr/lib/netdata/conf.d/health.d/backend.conf /opt/netdata/netdata-configs/health.d

2. Edit the backend.conf file changing the following the “to: dba” entry to “to: SILENT” for each alarm.

	# vi /opt/netdata/netdata-configs/health.d/backend.conf

	  # to: dba
	  to: SILENT

3. Reload netdata configuration files.

	# killall -USR2 netdata

Note: the same edited file containing “to: SILENT” was copied to all nodes.

**Comment by jbsom** [comment]
I apologize for the formatting...

**Comment by vlvkobal** [comment]
You can use a custom script which does nothing. Look at the [`exec:`](https://docs.netdata.cloud/health/#alarm-line-exec) parameter.

**Comment by cakrit** [comment]
It should be `silent` lower-case. The fact that you're receiving notifications after setting it means there's something wrong with the configuration. You mentioned the directory `/opt/netdata/netdata-configs`. I'm not sure if that's the user config directory in RHEL. Can you please check in `http://localhost:19999/netdata.conf` what's the path in the following variables?
```
[global]
...
	# config directory = ...
	# stock config directory = ...
```
The `config directory` is where you want the modified files, under folder `health.d`. The command `[config directory]/edit-config health.d/backend.conf` will take care of the copy/paste for you. 
If you modify files directoy on the `stock config directory`, you will lose your changes when netdata is updated and of course you could have by mistake a different config in the user `config directory`. The user config takes precedence over the stock config.

There's nothing special about the `backend` alarms or any alarm for that matter. By the way, what's your netdata version?
