### ISSUE TITLE
[Binary releases] Redesign versioning scheme on netdata

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#5983]
##### Feature idea summary
During our implementation of packaging infrastructure with netdata, we bumped into a problem with versioning in our repository. Debian packaging tools do not accept the letter "v" as part of the version, it rather expects a very specific structure on the folder and tarball filenames.

We handle this at the packaging process for now, but as part of this story we want to eliminate v letter, so that our codebase is more compliant with our packaging infrastructure

##### Expected behavior
Versioning no longer includes 'v' anywhere, without breaking any existing implementation or process

**Comment by paulkatsoulakis** [comment]
Things to check:
* What happens to the update process from dashboard (we have a check to notify the user for new versions)
* What happens between packaging version and kickstart install

**Comment by Saruspete** [comment]
Hello,

i'm having a bad time trying to update from 1.13 to v1.15 : I've created the RPM from the provided tools (contrib/rhel/build-netdata-rpm.sh) and the generated RPM indeed have a "v" prefix. This messes up the upgrade, and yum finds the 1.13 is more recent than v1.15

May I help you to push this issue forward ?

Thanks,

**Comment by cakrit** [comment]
For any change, ensure that we respect the fact that older installations will still have the "v" in front of them. The following are the ones I could find/think of:

The UI version check is done here:
https://github.com/netdata/netdata/blob/master/web/gui/main.js#L2870
https://github.com/netdata/netdata/blob/master/web/gui/main.js#L2871
These need a check if the string starts with "v", to get rid of it. Now they assume it does.

The daemon gets the version from either `git describe` or `packaging/version`, not quite sure:
https://github.com/netdata/netdata/blob/master/configure.ac#L8
https://github.com/netdata/netdata/blob/master/configure.ac#L9
Regardless, the CI process that produces the tag can just remove the "v" and it should work.

https://github.com/netdata/helmchart/blob/master/Chart.yaml#L5
Easy fix, we just change it when we get a new tag for 1.16.0, without the "v"

The updater doesn't care about the format, it does a sha256sum check.

https://github.com/netdata/netdata/blob/master/daemon/anonymous-statistics.sh.in#L26
Needs to change if the X.Y.Z-XXX format changes to X.Y.Z.XXX. The leading v is removed anyway with the `tr`

May want to reverse #5440, but not necessary.

**Comment by paulkatsoulakis** [comment]
> Hello,
> 
> i'm having a bad time trying to update from 1.13 to v1.15 : I've created the RPM from the provided tools (contrib/rhel/build-netdata-rpm.sh) and the generated RPM indeed have a "v" prefix. This messes up the upgrade, and yum finds the 1.13 is more recent than v1.15
> 
> May I help you to push this issue forward ?
> 
> Thanks,

Hi @Saruspete thanks for reaching out!
I am pretty sure you had problems with that, this issue is on the backlog right after the beta release of our own packaging repositories, so not far from now.

As a temporary solution you could create a small patch to remove the 'v' keyword from the spec file and also kill the dashes if you need latest nightly version.

Let me know what you think and i would be glad to help you out with anything else you might need!

**Comment by Saruspete** [comment]
Hi @paulkatsoulakis 
Yeah, I've patched all occurences of PACKAGE_VERSION, like in configure and packaging/version. That worked as espected.
I've also added the passing of options from build-netdata-rpm.sh invocation to ./configure (like --enable-plugin-freeipmi).

Now, i'm trying to find out more details on the --enable-maintainer-mode added by the packaging script, that seems to be only added in rpm generation (not sles nor debian).

From the rpm specfile perscpective, there is a "hidden" field "Epoch" or "Serial", not often discussed, but used when [renumbering the version](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html-single/RPM_Guide/#id819192)

>  Epoch: 3
> If you renumber your versions, use an Epoch setting to clarify the version history. For example, Sun Microsystems went from SunOS 4.1 to Solaris 2. The Epoch: helps RPM properly handle strange version number changes. Define the Epoch: as a whole number such as 1, 2, or 3.
> Warning
> Avoid using the Epoch: directive if at all possible. It is far better to use a sane version-numbering scheme than to try to resolve the mess with epoch values. The main problems with using an epoch value are that epochs are hidden from users in most cases, and using epochs can lead to very strange-looking tasks such as a newer package with a version number that looks older than the older package.
> 
> The older Serial: directive also works similarly to the Epoch: directive. For example:
> Serial: 6
> Like the Epoch:, the Serial: directive should be a number that counts upward. Modern packages should use the Epoch: directive instead of Serial:, since Serial: has been deprecated for many, many rpm versions.

**Comment by paulkatsoulakis** [comment]
> I've also added the passing of options from build-netdata-rpm.sh invocation to ./configure (like --enable-plugin-freeipmi).

Keep in mind that netdata has auto-detection for most of the plugins.
Adding the required packages will get you the functionality ready.
for freeipmi plugin you just need `freeipmi-devel` and (`libipmimonitoring-dev` or alibipmimonitoring-devel`)

**Comment by Saruspete** [comment]
Yes, it does autodetect, but sometimes that's not what we want :)

I use RPM for distributing the packages on all my servers. So my build servers will have many libraries (and their -devel part), which I might or might not want on my production ones. 

For example, I don't want the plugin tc (that is almost always available), but need the freeipmi plugin.
Shall my script be moved to a new build server, I expect the build to fail if I miss the library, nt to have a package without the ipmi plugin.
Same thing when i'll move my static build env to chroots, because I explicitly added in ./configure that i really want it. Hence the need to provide user-options it to the standard build script

**Comment by Ferroin** [comment]
@Saruspete It sounds then like you should be explicitly asking for each plugin you care about and disabling ones you don't.  I'm not 100% certain, but that should result in the build failing if it can't find required libraries/headers for the plugins you want.

**Comment by Saruspete** [comment]
Yes it does fail in the ./configure step.

**Comment by paulkatsoulakis** [comment]
@Saruspete that is very thoughtful of you, thanks!

Feel free to move the discussion to #5969 that is more relative if you want to discuss it more.
I am pretty sure @Ferroin or me can provide some further insights on the matter.

Not to mention also that we are very driven by our community. The way you take advantage of netdata, is what interest us, so your feedback might give us some more perspective on the matter.

**Comment by prologic** [comment]
@Ferroin I _think_ this needs to go into #7826 as well but maybe a duplicate or related to #7820 and #7821

**Comment by Ferroin** [comment]
Based on discussion with @prologic, we're not going to worry about this for now since we're working around it just fine for DEB packages.

If it becomes a further issue in the future, we'll reevaluate it then.

**Comment by prologic** [comment]
> CI/CD & Packaging backlog automation moved this from To do to Done yesterday

😲
