### ISSUE TITLE
Please help me configure a custom SMS gateway for netdata

### ISSUE THREAD

**Issue by makutamatey** [netdata/netdata#5984]
Please are all the variables for the custom_sender function required? Again, you please give me an example using the variables below? I was reading the docs but it is a bit overwhelming. I actually do not understand how to configure my custom sender now. 
This is what is required by my sms gateway  **https://domain.website.com/?From=From&To=To&Content=Content&username=username&password=password**
Thank you.

${to_custom} the list of recipients for the alarm
${host} the host generated this event
${url_host} same as ${host} but URL encoded
${unique_id} the unique id of this event
${alarm_id} the unique id of the alarm that generated this event
${event_id} the incremental id of the event, for this alarm id
${when} the timestamp this event occurred
${name} the name of the alarm, as given in netdata health.d entries
${url_name} same as ${name} but URL encoded
${chart} the name of the chart (type.id)
${url_chart} same as ${chart} but URL encoded
${family} the family of the chart

**Comment by cakrit** [comment]
Try this in the `custom_sender` function:

```
    # example human readable SMS
    local msg="${host} ${status_message}: ${alarm} ${raised_for}"

    # limit it to 160 characters and encode it for use in a URL
    urlencode "${msg:0:160}" >/dev/null; msg="${REPLY}"

    # a space separated list of the recipients to send alarms to
    to="${1}"

    for phone in ${to}; do
                        httpcode=$(docurl \
                                --form-string "From=XXX" \
                                --form-string "To=${phone}" \
                                --form-string "Content=${msg}" \
                                --form-string "username=YYY" \
                                --form-string "password=ZZZ" \
                                https://domain.website.com/)

                        if [ "${httpcode}" = "200" ]; then
                                info "sent custom notification ${msg} to '${phone}'"
                                sent=$((sent + 1))
                        else
                                error "failed to send custom notification ${msg} to '${phone}' with HTTP error code ${httpcode}."
                        fi
    done
```
Of course, don't forget to also set `DEFAULT_RECIPIENT_CUSTOM="phone1 phone2"` as well.

I will put the full example on the file and the README. 

One thing: I used GET because of how you structured the URL, but I strongly suggest using POST and an encrypted connection, since I see a username and password as URL params. Strange implementation, if you ask me...

You could of course also use SMS Server Tools 3 to connect with your SMS gateway and then use [the smstools3 notifications](https://docs.netdata.cloud/health/notifications/smstools3/).

**Comment by makutamatey** [comment]
Thank you sir. I appreciate it. Please is there a way I can test it like how we can test the email?.

**Comment by cakrit** [comment]
Sure, the info on how to test it is [here](https://docs.netdata.cloud/health/notifications/#testing-notifications). So just modify your configuration file and follow the instructions there.

**Comment by makutamatey** [comment]
to="${+233 24xxxxx31}"
please the line above give  **bad substitution** error. When am I doing wrong?

**Comment by cakrit** [comment]
`${ΧΧ}` gives you the value of variable XX. You want "+233 24xxxxx31", but be careful with the space, it would need to be url-encoded to "+233%2024xxxxx31". You're better off just getting rid of the space

**Comment by makutamatey** [comment]
please the xx is a placeholder I put here. the value in the curly bracket is my actual phone number. I added the + and removed the space when I was troubleshooting, but I still the bad substitution

**Comment by cakrit** [comment]
`${MYVARIABLE}` gives you the value of MYVARIABLE. You want either:
```
to="+23324xxxxx31"
```
or
```
MYVARIABLE="+23324xxxxx31"
to="${MYVARIABLE}"
```
