### ISSUE TITLE
HTTP requests are classified as AF_UNIX

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#5987]
##### Bug report summary
While we were developing the SSL for the web server we saw that the following line inside static-threaded.c is saying for us that  pi->socktype is defined as AF_UNIX instead AF_INET or AF_INET6.

 if(unlikely(pi->socktype == AF_UNIX)) {
        web_client_set_unix(w);
    }
    else {
        web_client_set_tcp(w);
    }
##### OS / Environment
Slackware Linux current 4.19.41 #2 SMP Wed May 8 19:41:24 CDT 2019 x86_64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz GenuineIntel GNU/Linux

##### Netdata version (ouput of `netdata -V`)
netdata v1.14.0-50-g5e3cc484

##### Component Name
Web Server

##### Steps To Reproduce
Access Netdata using any browser.

##### Expected behavior
When we do calls with browsers, it is expected that the pi->socktype value to be AF_INET or AF_INET6.

**Comment by cakrit** [comment]
@mfundul or @vlvkobal can you verify that this is an issue? I don't know enough about it...

**Comment by thiagoftsm** [comment]
While I was working in the HTTPS today, I used the rebuild project time to understand better the problem. Firstly I saw inside the web/server/static/static-threaded.c we are comparing pi->socktype and AF_UNIX, this will always be false. You can confirm this reading the file libnetdata/socket/socket.c inside this file socktype is always receiving either SOCK_STREAM or SOCK_DGRAM in the functions that works only with the socket, the variable that carries the socket type is ai_protocol, but we are not carring the protocol inside the POLLINFO structure. I will give another information before to go deep in the code, when we read the definition of AF_UNIX and SOCK_STREAM we can see that both have the same value 1, on the other hand, AF_INET and SOCK_DGRAM also have equal definition that is 2. 

Now l will analyse the calls of poll_add_fd that is the function responsible to create the POLLINFO, I am copying it next

inline POLLINFO *poll_add_fd(POLLJOB *p
                             , int fd
                             , int socktype
                             , WEB_CLIENT_ACL port_acl
                             , uint32_t flags
                             , const char *client_ip
                             , const char *client_port
                             , void *(*add_callback)(POLLINFO * /*pi*/, short int * /*events*/, void * /*data*/)
                             , void  (*del_callback)(POLLINFO * /*pi*/)
                             , int   (*rcv_callback)(POLLINFO * /*pi*/, short int * /*events*/)
                             , int   (*snd_callback)(POLLINFO * /*pi*/, short int * /*events*/)
                             , void *data
) 

as you can see the second argument is the socktype, but unfortunately when the web_server calls it from statitc-threaded.c it pass for socktype the value of the socket instead the socket type as you can see in the next code:

  POLLINFO *fpi = poll_add_fd(
                        pi->p
                        , w->ifd
                        , pi->port_acl
                        , 0
                        , POLLINFO_FLAG_CLIENT_SOCKET
                        , "FILENAME"
                        , ""
                        , web_server_file_add_callback
                        , web_werver_file_del_callback
                        , web_server_file_read_callback
                        , web_server_file_write_callback
                        , (void *) w
                );

and inside the socket.c, it is always called with SOCK_STREAM:

   poll_add_fd(p
                                        , nfd
                                        , SOCK_STREAM
                                        , pi->port_acl
                                        , POLLINFO_FLAG_CLIENT_SOCKET
                                        , client_ip
                                        , client_port
                                        , p->add_callback
                                        , p->del_callback
                                        , p->rcv_callback
                                        , p->snd_callback
                                        , NULL
                            );

A possible solution for this is we begin to carry the protocol with POLLINFO, I will  wait for more reviews and suggestion before we move to fix this, of course we need to rewrite the server poll_add_fd call independent of any solution.

**Comment by thiagoftsm** [comment]
Case we do not need to test the protocol in other parts of the code, we can set the flag for unix and tcp inside poll_add_fd.

**Comment by thiagoftsm** [comment]
I gave a partial solution for the static-threaded.c, I am saying partial, because I am not liking the way I am choosing the protocol when there is a possible error for the getpeername, this was the simplest way to fix the identification of the socket in the server side, for more details, please, see ( https://github.com/netdata/netdata/pull/5956 ).

**Comment by thiagoftsm** [comment]
This bug is completely killed when the HTTPS is merged, the final solution is to use client_port from POLLINFO.

**Comment by thiagoftsm** [comment]
The solution for this issue was given together with the SSL implementation, so I am closing it.
