### ISSUE TITLE
How to identify the source of growing blocked processes

### ISSUE THREAD

**Issue by paulocoghi** [netdata/netdata#5988]
##### Question summary
When the number of blocked processes grow indefinitely, how to identify exactly what are these processes.

Since I'm inside a system container (LXC/OpenVZ), I can't modify the hosts' kernel modules to use tools like [perf-tools](https://github.com/brendangregg/perf-tools) or [bcc-tools/bpfcc-tools](https://github.com/iovisor/bcc)

![growing-blocked-process](https://user-images.githubusercontent.com/378397/57525339-bbe9e780-732a-11e9-9429-e92c099e95d2.png)
_(in our real case, we aready have more than 600k blocked processes in 2-3 days after a reboot)_

##### OS / Environment
Ubuntu 16.04 virtualized through OpenVZ

##### Component Name
Internal plugins -> [proc.plugin](https://docs.netdata.cloud/collectors/proc.plugin/)

**Comment by Ferroin** [comment]
'Blocked' in this case translates to processes that are shown in the 'D' state in tools like `ps` and `top`.  The first step to tracking this down would be figuring out what processes are ending up in that state.

FWIW, most of the time when something like this happens it's either:

* A fork bomb (intentional or otherwise).
* A hardware failure of some kind (often disk or network, but anything that can trash internal state in the kernel can cause this type of thing).

**Comment by mfundul** [comment]
This 'D' state can also be processes that are waiting in kernel space for I/O to complete when there are extreme I/O loads in the server.

**Comment by Ferroin** [comment]
@mfundal Yes, but it's unusual to see such high (and moreover constantly increasing) numbers of processes in that state.  Roughly 99% of the time when you see constant increases and high numbers, it means something is misbehaving, and the most common cases of that are a fork-bomb or a hardware issue.

**Comment by paulocoghi** [comment]
Always in 0% of iowait. Using distributed NVMe storage. Most probably fork-bomb. I'm still diagnosing it.

**Comment by paulocoghi** [comment]
It's good to see that `CONFIG_PROC_EVENTS` is enable on many kernels, including in RHEL, Debian and Ubuntu.

With [the adaptation of a process event monitor](https://unix.stackexchange.com/a/438083/14789) from @cirosantilli (that's both Italian and Brazilian, like me :smile: ), I could properly identify the origin of the "fork-bomb".

This is a customer's server, that uses PM2 to run many node programs, and one of them is ending because of errors and being constantly created again by PM2.

**Comment by paulocoghi** [comment]
I will re-post here what I have informed on my question on ServerFault

---

**1. Check `CONFIG_PROC_EVENTS`**

First check if `CONFIG_PROC_EVENTS` is enable. Depending on your distro, you can run:

    grep CONFIG_PROC_EVENTS= /boot/config-`uname -r`

If it's enabled, you will get the following result:

    CONFIG_PROC_EVENTS=y

---

**2. If it's enabled, create the monitor**

Create a file `proc_events.c` with the content:

```c
static volatile bool need_exit = false;

static int nl_connect()
{
    int rc;
    int nl_sock;
    struct sockaddr_nl sa_nl;

    nl_sock = socket(PF_NETLINK, SOCK_DGRAM, NETLINK_CONNECTOR);
    if (nl_sock == -1) {
        perror("socket");
        return -1;
    }
    sa_nl.nl_family = AF_NETLINK;
    sa_nl.nl_groups = CN_IDX_PROC;
    sa_nl.nl_pid = getpid();
    rc = bind(nl_sock, (struct sockaddr *)&sa_nl, sizeof(sa_nl));
    if (rc == -1) {
        perror("bind");
        close(nl_sock);
        return -1;
    }
    return nl_sock;
}

static int set_proc_ev_listen(int nl_sock, bool enable)
{
    int rc;
    struct __attribute__ ((aligned(NLMSG_ALIGNTO))) {
        struct nlmsghdr nl_hdr;
        struct __attribute__ ((__packed__)) {
            struct cn_msg cn_msg;
            enum proc_cn_mcast_op cn_mcast;
        };
    } nlcn_msg;

    memset(&nlcn_msg, 0, sizeof(nlcn_msg));
    nlcn_msg.nl_hdr.nlmsg_len = sizeof(nlcn_msg);
    nlcn_msg.nl_hdr.nlmsg_pid = getpid();
    nlcn_msg.nl_hdr.nlmsg_type = NLMSG_DONE;

    nlcn_msg.cn_msg.id.idx = CN_IDX_PROC;
    nlcn_msg.cn_msg.id.val = CN_VAL_PROC;
    nlcn_msg.cn_msg.len = sizeof(enum proc_cn_mcast_op);

    nlcn_msg.cn_mcast = enable ? PROC_CN_MCAST_LISTEN : PROC_CN_MCAST_IGNORE;

    rc = send(nl_sock, &nlcn_msg, sizeof(nlcn_msg), 0);
    if (rc == -1) {
        perror("netlink send");
        return -1;
    }

    return 0;
}

static int handle_proc_ev(int nl_sock)
{
    int rc;
    struct __attribute__ ((aligned(NLMSG_ALIGNTO))) {
        struct nlmsghdr nl_hdr;
        struct __attribute__ ((__packed__)) {
            struct cn_msg cn_msg;
            struct proc_event proc_ev;
        };
    } nlcn_msg;
    while (!need_exit) {
        rc = recv(nl_sock, &nlcn_msg, sizeof(nlcn_msg), 0);
        if (rc == 0) {
            /* shutdown? */
            return 0;
        } else if (rc == -1) {
            if (errno == EINTR) continue;
            perror("netlink recv");
            return -1;
        }
        switch (nlcn_msg.proc_ev.what) {
            case PROC_EVENT_NONE:
                printf("set mcast listen ok\n");
                break;
            case PROC_EVENT_FORK:
                printf("fork: parent tid=%d pid=%d -> child tid=%d pid=%d\n",
                        nlcn_msg.proc_ev.event_data.fork.parent_pid,
                        nlcn_msg.proc_ev.event_data.fork.parent_tgid,
                        nlcn_msg.proc_ev.event_data.fork.child_pid,
                        nlcn_msg.proc_ev.event_data.fork.child_tgid);
                break;
            case PROC_EVENT_EXEC:
                printf("exec: tid=%d pid=%d\n",
                        nlcn_msg.proc_ev.event_data.exec.process_pid,
                        nlcn_msg.proc_ev.event_data.exec.process_tgid);
                break;
            case PROC_EVENT_UID:
                printf("uid change: tid=%d pid=%d from %d to %d\n",
                        nlcn_msg.proc_ev.event_data.id.process_pid,
                        nlcn_msg.proc_ev.event_data.id.process_tgid,
                        nlcn_msg.proc_ev.event_data.id.r.ruid,
                        nlcn_msg.proc_ev.event_data.id.e.euid);
                break;
            case PROC_EVENT_GID:
                printf("gid change: tid=%d pid=%d from %d to %d\n",
                        nlcn_msg.proc_ev.event_data.id.process_pid,
                        nlcn_msg.proc_ev.event_data.id.process_tgid,
                        nlcn_msg.proc_ev.event_data.id.r.rgid,
                        nlcn_msg.proc_ev.event_data.id.e.egid);
                break;
            case PROC_EVENT_EXIT:
                printf("exit: tid=%d pid=%d exit_code=%d\n",
                        nlcn_msg.proc_ev.event_data.exit.process_pid,
                        nlcn_msg.proc_ev.event_data.exit.process_tgid,
                        nlcn_msg.proc_ev.event_data.exit.exit_code);
                break;
            default:
                printf("unhandled proc event\n");
                break;
        }
    }

    return 0;
}

static void on_sigint(__attribute__ ((unused)) int unused)
{
    need_exit = true;
}

int main()
{
    int nl_sock;
    int rc = EXIT_SUCCESS;

    signal(SIGINT, &on_sigint);
    siginterrupt(SIGINT, true);
    nl_sock = nl_connect();
    if (nl_sock == -1)
        exit(EXIT_FAILURE);
    rc = set_proc_ev_listen(nl_sock, true);
    if (rc == -1) {
        rc = EXIT_FAILURE;
        goto out;
    }
    rc = handle_proc_ev(nl_sock);
    if (rc == -1) {
        rc = EXIT_FAILURE;
        goto out;
    }
    set_proc_ev_listen(nl_sock, false);
out:
    close(nl_sock);
    exit(rc);
}
```

Ensure that you can compile C programs. On Debian or Debian-based distros, like Ubuntu, run:

    sudo apt-get install build-essential


And compile it with:

    gcc proc_events.c -o proc_events

---

**3. Run it for a few seconds**

Running it this way will output directly on terminal:

    ./proc_events

But you can also redirect it and run for a few seconds, in order to save its output on a file:

    ./proc_events > results_file

---

**4. Analise the results**

The output will be in the following format:

```
fork: parent tid=48 pid=48 -> child tid=56 pid=56
fork: parent tid=48 pid=48 -> child tid=57 pid=57
exec: tid=57 pid=57
exec: tid=56 pid=56
exit: tid=57 pid=57 exit_code=0
exit: tid=56 pid=56 exit_code=0
```

**Comment by cirosantilli** [comment]
Paulo! I'm glad you've found that answer useful. Good luck on your hardcore debugging ;-)

**Comment by paulocoghi** [comment]
Thanks, @cirosantilli!

**Comment by cakrit** [comment]
Gents, why not convert this code to a collector? I'm thinking about the following:
- Possibly one chart for each `proc_ev.what` or at least one for each of PROC_EVENT_FORK, PROC_EVENT_EXEC PROC_EVENT_EXIT. 
- The dimensions are process names retrieved from the pid perhaps as described [here](https://stackoverflow.com/questions/29451920/how-to-get-process-name-from-pid-using-c).
- To reduce memory requirements and too many ephemeral dimensions, we could avoid sending a metric until we have received MIN_REQUIRED_EVENTS within PERIOD sec, for the same process name. The MIN_REQUIRED_EVENTS and the PERIOD would be in the collector's config. 

If we tweak these two properly, the charts would be normally empty and we'd see info only when we start having a reasonable amount of e.g. forks within the specified period for a particular process. We could of course also add alarms at much higher threshholds than the threshhold to actually send a metric to the daemon. cc: @vlkobal

**Comment by paulocoghi** [comment]
> The dimensions are process names retrieved from the pid perhaps as described here.

I believe it's easier to get the process info from `/proc`.

And, although Ciro said this approach wouldn't be reliable because there is a risk that the process finishes and another one took its PID, it is always reliable to take the information from the parent process, which, by the way, is **the** source of the forks.

**Comment by cakrit** [comment]
Closing this since @vlvkobal created a feature request. We can progress in #6031.
