### ISSUE TITLE
network interface speed, duplex, operstate

### ISSUE THREAD

**Issue by koebi001** [netdata/netdata#5989]
##### Feature idea summary

raise an alarm in case the network interface speed changes to a lower speed or is not equally to the fastest possible speed

##### Expected behavior

raise an alarm in case the network interface speed changes to a lower speed
raise an alarm in case the network interface speed is not equally to the fastest possible speed

**Comment by ilyam8** [comment]
> raise an alarm in case the network interface speed is not equally to the fastest possible speed

This is true for almost every home pc (1GB nic and 100mbit connection to the router/switch). 

It would be nice to have a warning about the duplex btw

**Comment by ilyam8** [comment]
As far as i know currently netdata aware only of the actual working interface speed. @vlvkobal

**Comment by Ferroin** [comment]
Checking for changes in speed should be easy, same for duplex (just poll `/sys/class/net/*/{duplex,speed}` and watch for changes).  Actual handling in Netdata could be as simple as converting the chart variable for interface speed to a hidden dimension and watching for changes.  Duplex could be handled similarly (also, JFYI, duplex shows as 'unknown' for an unconnected Ethernet port, and speed as -1).  We should be watching for any change though, not just downgrades, as a bump up means that something had happened that caused things to not be working, and is now resolved.  This seems to me to be a case where being able to send one-shot notifications (as in 'this unique event happened') would make sense.

Figuring out the actual maximal possible speed and duplex for an interface is, however, not easy.  Unless there's some API for it over netlink (I doubt there is), you have to look up actual hardware info and compare that to known values for specific hardware yourself.

An alternate approach would be to track the highest values ever seen for speed and duplex, and report if the current value is lower.  This would avoid the need for knowing what the actual best possible configuration is (thus mitigating cases like running GbE capable systems on a 100M switch), and would also avoid a degraded initial state from hiding other issues.  If this is done, there should still be one-off notifications for upgrades in speed or duplex that raise the expected value.

**Comment by ilyam8** [comment]
> to a hidden dimension

chart variable!

**Comment by ilyam8** [comment]
> /sys/class/net/*/{duplex,speed}

https://github.com/netdata/netdata/blob/c82f4a1df3dd4f7997073d1c4dd7f92b9c39ce50/collectors/proc.plugin/proc_net_dev.c#L455-L456

> As far as i know netdata is only aware of the actual working interface speed.

https://github.com/netdata/netdata/blob/c82f4a1df3dd4f7997073d1c4dd7f92b9c39ce50/collectors/proc.plugin/proc_net_dev.c#L643-L670

We need to add duplex @vlvkobal

**Comment by ilyam8** [comment]
> Figuring out the actual maximal possible speed and duplex for an interface is, however, not easy. 

just and idea, we need to investigagte how [`ethtool`](https://github.com/torvalds/linux/blob/master/net/core/ethtool.c) does it

**Comment by Ferroin** [comment]
@ilyam8 To actually track changes though, we need to actually update this, and last I knew, chart variables only get populated on initialization and then never get touched again.

Also, on a side note, duplex is a string value, not a number (probably won't be an issue, but still needs to be handled).  Only possible values I know of for certain are 'unknown', 'half', and 'full', but there might be others I don't know about for exotic states.

Also, good point about ethtool, I had forgotten about that.  I think it's doing something over netlink, but I'm not 100% certain (I just know it works for non-root users to list things like link modes on my boxes).

**Comment by ilyam8** [comment]
> chart variables only get populated on initialization and then never get touched again.

No, they can be updated/and even added on every iteration.

**Comment by ilyam8** [comment]
In addition to `speed` and `duplex` it would be nice to collect `operstate`

> https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net

**Comment by stelfrag** [comment]
- The network speed is collected already (/sys/class/net/XXXX/speed) as *nic_speed_max*
- Added support to read the **duplex** and **operstate** files

Those will be added as custom chart variables under _bandwidth_ with an appropriate mapping. See below.

### Duplex status map (variable *duplex_state*)
- 0 = unknown
- 1 = half duplex
- 2 = full duplex

### Operstate status map (variable *operstate*)
This is in the order listed in [kernel info/ sysfs-class-net](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net))
- 0 = unknown
- 1 = notpresent
- 2 = down
- 3 = lowerlayerdown
- 4 = testing
- 5 = dormant
- 6 = up


Comments please

**Comment by ilyam8** [comment]
> The network speed is collected already (/sys/class/net/XXXX/speed) as nic_speed_max


Hm, why is it `_max` when it is current 🤔

**Comment by stelfrag** [comment]
> > The network speed is collected already (/sys/class/net/XXXX/speed) as nic_speed_max
> 
> Hm, why is it `_max` when it is current 
> 
> Naming is wrong, we need to change it. Max != current.

Yes, but we need to see the impact because that has been there since 2018 so users may have 
alarms on that variable already (#4594)

**Comment by ilyam8** [comment]
Well, it is a bug to me. We fix bugs. If they have some alarms, then alarms are wrong - they expecte max speeed, but the speed is not max if i understand all right.

**Comment by Ferroin** [comment]
> Well, it is a bug to me. We fix bugs ☝️ If they have some alarms, then alarms are wrong - they expecet max speeed, but the speed is not max [according docs](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net).

It's still not nice to just break the alarms. Possibly add a new name (`nic_speed` probably) that's correct, officially deprecate the old one but keep it, let that simmer for a release, and then remove the old one (with noticeable comments about this in the release notes).

**Comment by ilyam8** [comment]
I would agree if it wasnt a bug. Var name should be `nic_current_speed` because it is nic current spid.

**Comment by Ferroin** [comment]
> I would agree if it wasnt a bug. ~Var name should be `nic_current_speed` because it is nic current speed.~

The only reason I'm worried about it is that it has a potential to break user configurations if we just flat-out fix it, and we could go about fixing it in a way that would give users some time to adjust.

> Is there a way to get max supported speed btw?
> 
> I recall `ethtool` thing reports all supported modes/speeds.

Not through `/sys` that I know of. `ethtool` either uses something through the Netlink API) or makes `ioctl()` calls, though I don't remember which. We could, in theory, do the same, but I suspect it would slow things down, and it would also make us a bit more dependent on the kernel version than `/sys` is likely to.
