### ISSUE TITLE
api/v1/chart and api/v1/data calls don't return chart variables names, values

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#5990]
##### Bug report summary
 - `api/v1/chart` response body

```json
{
  "id": "net.eth0",
  "name": "net.eth0",
  "type": "net",
  "family": "eth0",
  "context": "net.net",
  "title": "Bandwidth (net.eth0)",
  "priority": 7000,
  "plugin": "proc.plugin",
  "module": "/proc/net/dev",
  "enabled": true,
  "units": "kilobits/s",
  "data_url": "/api/v1/data?chart=net.eth0",
  "chart_type": "area",
  "duration": 259996,
  "first_entry": 1557243996,
  "last_entry": 1557503992,
  "update_every": 1,
  "dimensions": {
    "received": {
      "name": "received"
    },
    "sent": {
      "name": "sent"
    }
  },
  "green": null,
  "red": null,
  "alarms": {
    "1m_sent_traffic_overflow": {
      "id": 1516144061,
      "status": "CLEAR",
      "units": "%",
      "update_every": 10
    },
    "1m_received_traffic_overflow": {
      "id": 1516144060,
      "status": "CLEAR",
      "units": "%",
      "update_every": 10
    },
    "interface_speed": {
      "id": 1516144081,
      "status": "UNDEFINED",
      "units": "Mbit",
      "update_every": 10
    }
  }
}
```

<br>

 - `api/v1/data?chart=chart_name` returns only list of dimension names

i don't see `variables`

##### OS / Environment

any

##### Netdata version (ouput of `netdata -V`)
current 

> netdata v1.14.0-33-g83be8271

##### Component Name

API

##### Steps To Reproduce
 - find a chart with chart variables
 - make `api/v1/chart` and `api/v2/data` calls to that chart

##### Expected behavior

 - `apiv/v1/chart` returns list of chart variables
 - `apiv/v1/data` returns chart variables values

**Comment by cakrit** [comment]
The variables with their values are provided by `api/v1/alarm_variables?chart=XXX`
We definitely need to add the call to swagger, because it only appears in https://docs.netdata.cloud/health/#variables as far as I remember...

**Comment by cakrit** [comment]
Oh, but I would of course consider adding what @ilyam8 suggested to the other calls, as a feature request.

**Comment by ilyam8** [comment]
> suggested to the other calls

Yes, i think since they are `chart variables` they should be added to both `/chart` and `/data` calls.
