### ISSUE TITLE
Getting all raised alarms of all replicated databases from one API call (or in one place)

### ISSUE THREAD

**Issue by JessedeJonge** [netdata/netdata#5993]
Similar to #3148. I have one master node. 20 slaves are sending their database to the master. Now I want one place to see all raised alarms, right now I need to go to each dashboard to see which alarm is raised. I am writing a custom dashboard to go with this so I thought they might be available at /api/v1/alarms but unfortunately this only returns the alarms of the master. Any way to get all the raised alarms from all the nodes via an API call?

**Comment by ilyam8** [comment]
Hi @JessedeJonge 

> or in one place

Will be in the netdata cloud http://netdata.cloud/about
https://github.com/netdata/netdata/pull/5902

**Comment by JessedeJonge** [comment]
@ilyam8 this should definitely be an option via the API at least. I don't want to use the cloud.

**Comment by ilyam8** [comment]
I am agree with you, was answering to the `in one place` part of the question.

@cakrit

**Comment by cakrit** [comment]
It should be possible to show all alarms. I just need to investigate a bit. 
And trust me @JessedeJonge, after the cloud matures a bit, you'll find it a great tool.

**Comment by manos-saratsis** [comment]
@JessedeJonge I am not sure if there is a single API call which can give you all alarms but you can use the /host/$hostname/api/v1/alarms and fire multiple API calls to get your slaves alarms.

It's in our immediate roadmap to support replication and have Custom Dashboards on Cloud. 

Even today you can claim all your slave nodes into a Space, add them to a War Room and have access to all their active alarms from one place. I suggest you give it a try.

**Comment by thiagoftsm** [comment]
Hi @manos-saratsis ,

You are right, we need to go trough all hosts right now.

best regards!

**Comment by cakrit** [comment]
Closing, as this is covered by the cloud.
