### ISSUE TITLE
netdata - what is policy for release tags? 

### ISSUE THREAD

**Issue by donets420** [netdata/netdata#5994]
Hello netdata team.
v1.14.0 was released 2019-04-18.
After that it were many bug fixes implemented and added features.
What is policy for tags?
I am waiting new tag because [issue 5929](https://github.com/netdata/netdata/issues/5929) was resolved after last release date.

Thanks in advance.

**Comment by cakrit** [comment]
We have nightly releases as well, so you can also get those. It's actually the default, when you enable automatic updates. See [this](https://docs.netdata.cloud/packaging/installer/update/#updating-netdata-after-its-installation).

Having said that, v1.15.0 is planned for this week.

**Comment by donets420** [comment]
Great! Thanks a lot!
