### ISSUE TITLE
How to set different resolution on different chart in netdata?

### ISSUE THREAD

**Issue by ramonli** [netdata/netdata#5998]
I have setup a netdata server to monitor application metrics, and would like to use statsd to collect metrics data. After research some days, I still have no idea of how to set different resolution on different chart. For example, I would like to show total sales every hour, however the request count every minute. It seem netdata will only refresh the chart every one second(the global setting of 'update every'). So how to make netdata refresh total sales chart per hour(a lower resolution), and the total request count per minute? or I just misunderstood netdata/statsd? Thanks in advance.

**Comment by vlvkobal** [comment]
`update every (flushInterval)` is a general parameter for the whole statsd plugin. You can use [sampling rates](https://docs.netdata.cloud/collectors/statsd.plugin/#sampling-rates) for individual metrics to alter their values.

You can set up another netdata instance though, specifically for the hourly charts.

**Comment by ramonli** [comment]
@vlvkobal seems the answer is [custom dashboards](https://docs.netdata.cloud/web/gui/custom/#changing-rates)

**Comment by vlvkobal** [comment]
Yes, you can use them. As with *sampling rates*, you can't change collecting rates using *custom dashboards* but can change data to be displayed in different units.

**Comment by ramonli** [comment]
Thanks a lot.

**Comment by vlvkobal** [comment]
@ramonli did you reopened the issue by mistake? Do you have any additional questions on the subject?
