### ISSUE TITLE
Slack does not send to channel

### ISSUE THREAD

**Issue by JessedeJonge** [netdata/netdata#6003]
Hi, 

Set up the following values:

```
# enable/disable sending slack notifications
SEND_SLACK="YES"
# Login to slack.com and create an incoming webhook. You need only one for all
# your netdata servers (or you can have one for each of your netdata).
# Without it, netdata cannot send slack notifications.
# Get yours from: https://api.slack.com/incoming-webhooks
SLACK_WEBHOOK_URL="WEBHOOK URL HERE"

# if a role's recipients are not configured, a notification will be send to:
# - A slack channel (syntax: '#channel' or 'channel')  
# - A slack user (syntax: '@user')
# - The channel or user defined in slack for the webhook (syntax: '#')
# empty = do not send a notification for unconfigured roles 
DEFAULT_RECIPIENT_SLACK="# random"
```

The webhook is activated on channel 'all-alarms'. When firing off a test alarm this is the output:

`# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2019-05-13 16:40:05: alarm-notify.sh: INFO: sent slack notification for: testcontainer test.chart.test_alarm is WARNING to '#random'
2019-05-13 16:40:06: alarm-notify.sh: INFO: sent slack notification for: testcontainer test.chart.test_alarm is WARNING without specifying a channel
2019-05-13 16:40:06: alarm-notify.sh: INFO: sent email notification for: testcontainer test.chart.test_alarm is WARNING to 'root'
 OK
`
So this seems to be alright. However, the alarms only get send to the default 'all-alarms' channel and not to #random. Am I missing something? ( I dont really care about roles, I just want all alarms in the configured channel)

**Comment by cakrit** [comment]
It's the space after the `#`. It shouldn't be there:
```
DEFAULT_RECIPIENT_SLACK="# random"
```

**Comment by JessedeJonge** [comment]
@cakrit 
Based on the configuration text above. The # sends it to the defined slack webhook channel so 'all-alarms':
`# - The channel or user defined in slack for the webhook (syntax: '#')`

Then, 'random' should send it to channel named random:
`# - A slack channel (syntax: '#channel' **or 'channel'**)  `

The following is also in the documentation:

> You can define multiple recipients like this: # #alarms systems @myuser. 
> This example will send the alarm to:
> - The recipient defined in slack for the webhook (not known to netdata)
> - The channel ‘alarms’
> - The channel ‘systems’
> - The user @myuser

Anyway, when changing to #random (without space). The test notification will output:
```
# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2019-05-14 11:40:05: alarm-notify.sh: INFO: sent slack notification for: testcontainer test.chart.test_alarm is WARNING to '#random'
2019-05-14 11:40:05: alarm-notify.sh: INFO: sent email notification for: testcontainer test.chart.test_alarm is WARNING to 'root'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2019-05-14 11:40:05: alarm-notify.sh: INFO: sent slack notification for: testcontainer test.chart.test_alarm is CRITICAL to '#random'
2019-05-14 11:40:05: alarm-notify.sh: INFO: sent email notification for: testcontainer test.chart.test_alarm is CRITICAL to 'root'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2019-05-14 11:40:06: alarm-notify.sh: INFO: sent slack notification for: testcontainer test.chart.test_alarm is CLEAR to '#random'
2019-05-14 11:40:06: alarm-notify.sh: INFO: sent email notification for: testcontainer test.chart.test_alarm is CLEAR to 'root'
# OK
```

But the notification will still end up in 'all-alarms, not in 'random'. Any idea?

**Comment by cakrit** [comment]
I guess the documentation wasn't fresh in my mind! :) Sorry about that @JessedeJonge, my comment was clearly wrong. I'm investigating and will respond in a few minutes.

**Comment by cakrit** [comment]
I am definitely not getting the same behavior. My webhook in on channel "netdata-alarms" and I put in the config a channel "christest". I received the alarms as expected. I really don't get what could be happening, since we're getting a success for the call. There are two things that might help:

- Follow the two-steps process in https://docs.netdata.cloud/health/notifications/#testing-notifications to run with `bash -x`, so you can get the `curl` call to the API. Run it manually and see if you're getting something strange. 
- Create a brand new channel, and try that, instead of random (though I can't imagine what settings Slack could possibly have that would prevent a channel from getting updates via another channel's webhook).

**Comment by JessedeJonge** [comment]
@cakrit This API call is executed: 

`curl -X post /usr/bin/curl -X POST --data-urlencode $'payload=        {\n            "channel": "#alarms2",\n            "username": "netdata on testcontainer",\n            "icon_url": "https://registry.my-netdata.io/images/banner-icon-144x144.png",\n            "text": "testcontainer recovered, `test.chart` (_test.family_), *test alarm (alarm was raised for 3 seconds)*",\n            "attachments": [\n                {\n                    "fallback": "test alarm (alarm was raised for 3 seconds) - test.chart (test.family) - this is a test alarm to verify notifications work",\n                    "color": "good",\n                    "title": "test alarm (alarm was raised for 3 seconds)",\n                    "title_link": "https://netdata.cloud/alarms/redirect?agentID=467955c0-5b66-11e9-b23e-5a923416454f&host=testcontainer&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=3",\n                    "text": "this is a test alarm to verify notifications work",\n                    "fields": [\n                        {\n                            "title": "test.chart",\n                            "short": true\n                        },\n                        {\n                            "title": "test.family",\n                            "short": true\n                        }\n                    ],\n                    "thumb_url": "https://registry.my-netdata.io/images/check-mark-2-128-green.png",\n                    "footer": "by testcontainer",\n                    "ts": 1557832000\n                }\n            ]\n        }' 
HOOK HERE
`

Note the channel: #alarms2 (a new one I created.). When manually calling this call the message still ends up in #all-alarms.

**Comment by cakrit** [comment]
I really don't get this. We have essentially the same payloads, yet the behavior is different. 
Can you try creating a new webhook (again with the all-alarms channel) and see if you get anything different? I haven't found any suspicious settings in Slack, but if even the new webhook doesn't work, try contacting them so they can check what's happening with your set up. Just the call should be enough for them to give us a hint of what's going on.

**Comment by JessedeJonge** [comment]
@cakrit I recreated the webhook and the issue still remains. I contacted the Slack support team and am waiting for a response. Will report back when I received an answer.

**Comment by JessedeJonge** [comment]
@cakrit I just got the following response:
 
> Thanks for getting in touch about this. Unfortunately, I'm afraid that the issue is due to the fact that app incoming webhooks cannot be overridden to send to specific channels.
> 
> For this use case where you need to be able to send messages to different channels, it would be better not to use an app incoming webhook because those are restricted to a single channel so you cannot override the channel when using this component type.
> 
> Instead, you should use our chat.postMessage API method (https://api.slack.com/methods/chat.postMessage) with a bot token (https://api.slack.com/docs/oauth#using_tokens).
> 
> To start, you need to create a Slack API app (from here: https://api.slack.com/apps), add a bot user, and then install the app which will generate two types of tokens:
> 
> User access token (starts with xoxp-)
> Bot access token (starts with xoxb-)
> It's the second of the above two tokens that you'll need to use. The only issue is that the app bot user needs to be invited to the channels where they will be posting messages.
> 
> In case you're wondering, app incoming webhooks get added at the time that the app is installed and therefore, the channel assignment for that webhook is manually specified by the installing user.
> 

Just wondering what to do now and how you are able to get this to work?

**Comment by JessedeJonge** [comment]
Actualy, specifying a channel in the JSON payload might actually be disabled: https://api.slack.com/custom-integrations/incoming-webhooks#migrating_from_legacy_incoming_webhooks

@cakrit

**Comment by JessedeJonge** [comment]
The issue turned out to be that Slack new Incoming Webhooks do not support specifying the channel in the JSON payload.
However, you can still download the legacy webhook as a [Slack app](https://dataprovider-servers.slack.com/apps/A0F7XDUAZ-incoming-webhooks?next_id=0).

It might be a good idea to change the default configuration text to represent this? Also, the code needs to be rewritten to the new (non-legacy) system as well. @cakrit

**Comment by cakrit** [comment]
Thanks a lot, now it makes sense. I'll check it out tomorrow and put something together.
