### ISSUE TITLE
Secure streaming via SSL

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6004]
Based on the discussion in #5943, we need to progress with SSL between netdata slaves and masters.

**Comment by pgassmann** [comment]
Currently streaming is not secure and not recommended over public internet? is this correct? is there a workaround for public cloud servers?

@cakrit Could streaming over websockets be an option to implement safe streaming over http(s)? That way it could also work through a reverse proxy

**Comment by Ferroin** [comment]
> Currently streaming is not secure and not recommended over public internet? is this correct?

Yes, that is correct.  There are a few potential issues here:

* A lot of the data collected by Netdata is extremely useful to an attacker because it gives them a lot of information about the system configuration.  At minimum, it tells them what software you are using, and at worst it gives them live feedback on attacks.
* Because the connection is unsecured, it's very easy to manipulate the stream to hide information, making it easy for an MITM attack to conceal other attacks against the system.

> Is there a workaround for public cloud servers?

IPSEC, WireGuard, or whatever your preferred encrypted VPN solution is.

**Comment by cakrit** [comment]
Just a little more patience guys, @thiagoftsm is already on it and we should have the communication encrypted next week (and https for the web server in general).

**Comment by thiagoftsm** [comment]
Hi guys, as @cakrit  said  in development environment we already have the HTTPS working to access data and the communication between master and slave is at least 80% encrypted. I would say that we are two step away to reach the goal, where the last step is to test in different environments.

**Comment by cakrit** [comment]
This is actually merged now!

**Comment by pgassmann** [comment]
Thank you for the great update. The corresponding merge is #5956

The related documentation: 
- https://docs.netdata.cloud/streaming/#securing-the-communication
- https://docs.netdata.cloud/web/server/#enabling-tls-support

Now I need to find a way to integrate it into my setup with docker and a reverse-proxy with letsencrypt.
https://docs.netdata.cloud/packaging/docker/

As far as I understand, the streaming is SSL but not HTTPS and will not work through a reverse proxy. So either I find a way to reuse the letsencrypt cert/key by the reverse proxy or configure netdata to use a self-signed cert for streaming with no certificate-check.

**Comment by thiagoftsm** [comment]
Hi @pgassmann , you are correct, the stream will send messages that looks like an HTTP, but it is not officially a HTTP. Netdata accepts the use of self-signed certificate, but in the slave you will need to enable "ssl invalid certificate = yes".

Best Regards!

**Comment by ilyam8** [comment]
Yes, @thiagoftsm did a marvelous job :+1: 	

> ssl invalid certificate = yes

was changed to  `ssl skip certificate verification`
