### ISSUE TITLE
Notifications Slave

### ISSUE THREAD

**Issue by LibanaAbdul** [netdata/netdata#6005]
Team,

How can I test the notifications of a slave to the master?

Thanks!

**Comment by LibanaAbdul** [comment]
![image](https://user-images.githubusercontent.com/8950289/57716687-278bc780-763f-11e9-8bbb-fd2547a0a04d.png)

Change the values to receive notifications. They are shown in the dashboard, but I can not even reach the telegram, mail and MSteams, it is worth mentioning that this is a slave.

**Comment by cakrit** [comment]
First of all, you need to specify which server you want to be running the health checks so it's the only one generating the alarms. In https://docs.netdata.cloud/streaming/ you will see several references to `health`, which explain how the configuration works in a master-slave set up.

Let's assume that you decide you want only the master to be doing the health checks and sending notifications. 
- From the master's UI, you would actually need to select your slave from the left menu (under databases streamed to this host) to see those alarms. 
- You will need to [configure notifications](https://docs.netdata.cloud/health/notifications/) on the master to receive them on your system of choice. You will see under this link a list of all the supported notification methods, with some additional info, but the config file `health_alarm_notify.conf` is pretty self-explanatory.

**Comment by OdysLam** [comment]
Hey, 

I just came by this issue as I was researching the alarms. Would it be beneficial to underline in the documentation that the view from the Master's UI is the data & alarms as they exist in the Master?

Thus the alarms depicted there would be different (as a unit) from those that exist in the slave's UI.

I am not sure if it is trivial or a subtle difference that confuses most newcomers.

Cheers :)

**Comment by thiagoftsm** [comment]
Thank you @OdysLam , we are working in our documentation nowadays  and we will consider your comments.

**Comment by OdysLam** [comment]
Hey @thiagoftsm ,

As I was reading through the docs, I have pinpointed some parts which I was thinking to PR sometime in the coming weeks with suggestions. 

If you actively work on it, maybe it would be better to indicate them earlier? Some are language-related and some regarding the content.

Big fan btw.

Cheers :)

**Comment by thiagoftsm** [comment]
Hi @OdysLam ,

I do not wanna change your plans, be free to give the suggestion that you want when you can. :)

We are glad to have fans like you!

Cheers.
