### ISSUE TITLE
solaris/*bsd support 

### ISSUE THREAD

**Issue by jmatis** [netdata/netdata#601]
Is there any chance you could start looking into supporting other flavour of unixes please ? (what you have done is so amazing i simply want to have it everywhere :)

**Comment by ktsaou** [comment]
Thanks! There are a few folks that work on BSD #112  #187 . For basic system data collection on non-linux system we could use libstatgrab #481 .

Currently the only blocking library used by netdata is `libuuid`, but we can easily replace this with something else (netdata uses just 2 calls to parse and generate random UUIDs).

The problem, is that my roadmap is full with new features (health monitoring and alerts, longer data history, new plugins, etc), so I need help to do this...

**Comment by kirillDanshin** [comment]
hi! is there any news about solaris support?

**Comment by h0lzi** [comment]
Getting support for Solaris would be nice. At least some simple support via libstatgrab would be awesome. I can provide test infrastructure etc. I lack the skill to code it though.

**Comment by ktsaou** [comment]
libstatgrab seems nice, although a bit stale...

**Comment by h0lzi** [comment]
well it's mostly for OS that do not change their API for those kinds of stuff very often.
It's used e.g. in collectd for Solaris and works quite ok with it. I would love to get rid of collectd on Solaris though and have only one tool :)

**Comment by williamleuschner** [comment]
I'm interested in porting netdata to OpenBSD. Currently, I'm trying to get it to compile—it makes it to `log.c` before failing.

Once I've gotten it to compile, I'll see what I can do about the smattering of `#if defined(__FreeBSD) || defined(__APPLE__) || …` and associated constructs that might make porting to other BSDs easier.

**Comment by ktsaou** [comment]
> I'm interested in porting netdata to OpenBSD.

Wow! Thank you! This would be great!
I have provides a patch to fix log.c

**Comment by williamleuschner** [comment]
I've opened a PR (#4192) to track my progress on patching netdata to work on OpenBSD. It's not ready yet, but you all will have more visibility into what I'm doing while I do it.

**Comment by prologic** [comment]
We're actively working on FreeBSD support and we already support macOS (_not really BSD but once upon a time maybe_).

- #8120 
- #8130 
- #8131

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
