### ISSUE TITLE
netdata/packaging: Run basic testing for master/slave scenarios in CI

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6012]
##### Feature idea summary
It came to my mind as an open item when we bumped into a bug that was raised due to the fact the slave was running an old version.

Basically with this issue, we will implement some use case scenarios on Travis CI to make sure that for any code change, we will validate the master-slave connectivity touches baseline quality (Services remain started, for starters)

CC: @cakrit 
##### Expected behavior
Travis validates master-slave functionality use cases
I will let it as part of the issue to identify what are the feasible cases we can test

**Comment by prologic** [comment]
I _think_ this should be a part of a larger body of work (_EPIC_). I'd love to combine a bunch more related issues/tasks together. This is a good project for an SET btw @cosmix :D

**Comment by cosmix** [comment]
indeed it is @prologic.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
