### ISSUE TITLE
Q: tagging support for graphite? 

### ISSUE THREAD

**Issue by wcallgair** [netdata/netdata#6023]
##### Question summary
Ive been unable to get tagging to work with my graphite stack. According to the docs tagging is currently only sent to opentsdb and prometheus (https://docs.netdata.cloud/backends/), however I do see that a commit was made last year that should have added tagging: https://github.com/netdata/netdata/pull/3992

Potentially two questions. Is this actually supported by netdata? And, if so, am I using host tagging properly? 

Thanks

```
[backend]
enabled = yes
type = graphite
data source = average
prefix = netdata
update every = 60
buffer on failures = 60
timeout ms = 20000
destination = graphite.example.domain.com:2003
hostname = server01
host tags = tag=test-tag
```
##### Component Name
netdata v1.12.0
graphite backend

**Comment by vlvkobal** [comment]
I don't see any problems with graphite tagging. I applied your configuration to my netdata instance and looked at the output:
```
$ nc -l 2003
netdata.server01.system.entropy.entropy;tag=test-tag 1183.0000000 1557992245
netdata.server01.system.active_processes.active;tag=test-tag 183.0000000 1557992245
netdata.server01.system.load.load1;tag=test-tag 0.0600000 1557992230
netdata.server01.system.load.load5;tag=test-tag 0.1000000 1557992230
netdata.server01.system.load.load15;tag=test-tag 0.1100000 1557992230
netdata.server01.system.uptime.uptime;tag=test-tag 141837.0000000 1557992245
netdata.server01.cpu.cpu3_cpuidle.C0__active_;tag=test-tag 100.0000000 1557992245
netdata.server01.cpu.cpu2_cpuidle.C0__active_;tag=test-tag 100.0000000 1557992245
netdata.server01.cpu.cpu1_cpuidle.C0__active_;tag=test-tag 100.0000000 1557992245
netdata.server01.cpu.cpu0_cpuidle.C0__active_;tag=test-tag 100.0000000 1557992245
netdata.server01.system.processes.running;tag=test-tag 5.0000000 1557992245
netdata.server01.system.processes.blocked;tag=test-tag 0.0000000 1557992245
netdata.server01.system.forks.started;tag=test-tag 0.0000000 1557992245
netdata.server01.system.ctxt.switches;tag=test-tag 551.0213000 1557992245
netdata.server01.system.intr.interrupts;tag=test-tag 674.1572000 1557992245
...

```

**Comment by vlvkobal** [comment]
BTW, don't you want to update your netdata? It does nothing with graphite backend, but there were a lot of other changes. The latest release is v1.14.0 and v1.15.0 is coming soon.

**Comment by wcallgair** [comment]
Thanks, I didnt think to try NC. Its indeed sending tags so it must be an issue with our graphite cluster. 

Regarding the versions, for various reasons we need to rebuild the package with our configs and custom plugins. I do plan on updating soon though. 

Thanks for the quick reply, I really appreciate the help!
