### ISSUE TITLE
Collect information about fork and exec events

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#6031]
Gents, why not convert this code to a collector? I'm thinking about the following:
- Possibly one chart for each `proc_ev.what` or at least one for each of PROC_EVENT_FORK, PROC_EVENT_EXEC PROC_EVENT_EXIT. 
- The dimensions are process names retrieved from the pid perhaps as described [here](https://stackoverflow.com/questions/29451920/how-to-get-process-name-from-pid-using-c).
- To reduce memory requirements and too many ephemeral dimensions, we could avoid sending a metric until we have received MIN_REQUIRED_EVENTS within PERIOD sec, for the same process name. The MIN_REQUIRED_EVENTS and the PERIOD would be in the collector's config. 

If we tweak these two properly, the charts would be normally empty and we'd see info only when we start having a reasonable amount of e.g. forks within the specified period for a particular process. We could of course also add alarms at much higher threshholds than the threshhold to actually send a metric to the daemon. cc: @vlvkobal

_Originally posted by @cakrit in https://github.com/netdata/netdata/issues/5988#issuecomment-491752846_

**Comment by cakrit** [comment]
> > The dimensions are process names retrieved from the pid perhaps as described here.
> 
> I believe it's easier to get the process info from `/proc`.
> 
> And, although Ciro said this approach wouldn't be reliable because there is a risk that the process finishes and another one took its PID, it is always reliable to take the information from the parent process, which, by the way, is **the** source of the forks.

**Comment by ilyam8** [comment]
@vlvkobal @thiagoftsm is this covered with ebpf.plugin?

**Comment by thiagoftsm** [comment]
Yes, the majority of the bullets were already merged, the exception is the following:

-  To reduce memory requirements and too many ephemeral dimensions, we could avoid sending a metric until we have received MIN_REQUIRED_EVENTS within PERIOD sec, for the same process name. The MIN_REQUIRED_EVENTS and the PERIOD would be in the collector's config.

This is because eBPF.plugin, like apps.plugin reads `/proc` every second, because we need to keep compatibility between plugins charts.

**Comment by ilyam8** [comment]
I don't think we have any ephemeral dimensions, so that bullet is irrelevant. I assume we have suggested metrics per system + per apps groups. Am I missing something?

**Comment by thiagoftsm** [comment]
> I don't think we have any ephemeral dimensions, so that bullet is irrelevant. I assume we have suggested metrics per system + per apps groups. Am I missing something?

You are not missing, they are linked with apps groups.

**Comment by ilyam8** [comment]
Thanks for the clarification! What we have is not exactly OP (request is per-process events but we have per-process groups), but let's consider it as implemented by now.
