### ISSUE TITLE
One server, multiple PHP-FPM endpoints

### ISSUE THREAD

**Issue by petecooper** [netdata/netdata#6034]
##### Question summary

Is it possible to have multiple, local PHP-FPM endpoints monitored from a single collector, each with they own identifier (e.g. "PHP 7.1", "PHP 7.2" etc)? If so, what is the sanest/preferred syntax for the collector, please?

I have three PHP-FPM endpoints, each with monitoring enabled, at:

```
http://127.0.0.1:71/phpfpm71status?full&json
http://127.0.0.1:72/phpfpm72status?full&json
http://127.0.0.1:73/phpfpm73status?full&json
```

When one endpoint is used in Netdata, like this (from `conf.d/python.d/phpfpm.conf`)…

```
update_every: 1
priority: 90100
local:      
url: 'http://127.0.0.1:72/phpfpm72status?full&json'
```

…it works perfectly. But I cannot figure out how to collect multiple instances on the same server and have Netdata show them discretely.

Thank you in advance.

##### OS / Environment

Ubuntu 18.04 LTS

##### Component Name

`python.d` `phpfpm` collector

**Comment by ilyam8** [comment]
Hi @petecooper 

Sure

https://github.com/netdata/netdata/issues/5964#issuecomment-489460279

**Comment by petecooper** [comment]
Thank you @ilyam8 - I have tried multiple instances of `local` in one file, like this:

```
update_every: 1
priority: 90100

local:
url: 'http://127.0.0.1:71/phpfpm71status?full&json'

local:
url: 'http://127.0.0.1:72/phpfpm72status?full&json'

local:
url: 'http://127.0.0.1:73/phpfpm73status?full&json'
```

![Screen Shot 2019-05-16 at 20 26 36](https://user-images.githubusercontent.com/226578/57881546-78efae80-7819-11e9-974e-f10beb14b5ad.png)

I reload Netdata using `sudo systemctl restart netdata`, and the dashboard shows one instance:

![Screen Shot 2019-05-16 at 20 27 25](https://user-images.githubusercontent.com/226578/57881581-945ab980-7819-11e9-97d9-34e50f625d78.png)

…or is this single instance actually three endpoints combined?

**Comment by ilyam8** [comment]
`local` is a key, it should be unique

```yaml
local71:
  url: 'http://127.0.0.1:71/phpfpm71status?full&json'

local72:
  url: 'http://127.0.0.1:72/phpfpm72status?full&json'

local73:
  url: 'http://127.0.0.1:73/phpfpm73status?full&json'
```

**Comment by petecooper** [comment]
Perfect - thank you very much!
