### ISSUE TITLE
[Binary releases] Generate roadmap document on packaging

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6036]
##### Feature idea summary
We would like to generate a document within netdata repository to keep track of all the information that is crucial for our packaging support and also to help us keep track of our progress regarding distributions that we support, Quality assurance over those distributions and consistency

In short we would like to list down the distributions netdata will commit to officially support and for each distribution, information regarding:
1) CI status (Do we track the netdata's health for that distro?)
2) kickstart status (Is it functional on this distribution? Can we use it and is the latest version ok)
3) kickstart-static64 status (Is it functional on this distribution? Can we use it and is the latest version ok)
4) Binary packaging status (Do we provide a binary package for this? If so, for which architectures?)

##### Expected behavior
Documentation

**Comment by cakrit** [comment]
> to list down the distributions netdata will commit to officially support

Correction: List down all the supported distributions by the people who actually maintain them. e.g. look at which releases Ubuntu supports officially and list those. So all, non-obsolete linux distros will be there (even the niche ones) and we'll ensure that netdata can be installed on all of them.

**Comment by cakrit** [comment]
Perhaps we put this in packing/installer/DISTRIBUTIONS.md? Any better names are welcome.

**Comment by paulkatsoulakis** [comment]
> Perhaps we put this in packing/installer/DISTRIBUTIONS.md? Any better names are welcome.

yep, sounds good

**Comment by paulkatsoulakis** [comment]
> Correction: List down all the supported distributions by the people who actually maintain them. e.g. look at which releases Ubuntu supports officially and list those. So all, non-obsolete linux distros will be there (even the niche ones) and we'll ensure that netdata can be installed on all of them.

yep, that is how i ended up on the list of distros in #5963

**Comment by paulkatsoulakis** [comment]
Distributions to support as per the maintainers

* Ubuntu (https://wiki.ubuntu.com/Releases)
   * Ubuntu 14.04.6 LTS (Trusty Tahr)
   * Ubuntu 16.04.6 LTS (Xenial Xerus)
   * Ubuntu 18.04.2 LTS (Bionic Beaver)
   * Ubuntu 19.04 (Disco Dingo) **latest

* Debian (https://www.debian.org/releases/ and https://wiki.debian.org/LTS/)
    * Debian 7 (Wheezy)
    * Debian 8 (Jessie)
    * Debian 9 (Stretch)
    * Debian 10 (buster) **Not released yet

* Redhat Enterprise (https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux and https://access.redhat.com/support/policy/updates/errata)
   * Versions 6.* 
   * Versions 7.*
   * Versions 8.*

* Fedora (https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle). As per the release lifecycle and support unless i misunderstood it, they support latest three releases. That gives us:
   * Fedora 28
   * Fedora 29
   * Fedora 30
   * Fedora 31 **Not released yet

* CentOS (https://en.wikipedia.org/wiki/CentOS#CentOS_releases and https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d)
   * Centos 6.*
   * Centos 7.*

* OpenSuSE (https://en.opensuse.org/Lifetime)
   * Open SuSE Leap 42.3
   * Open SuSE 15.0
   * Open SuSE 15.1

* All other linux through static binary distributions
   To guarantee the good state of our static binaries, we 'll be adding tests on various distributions to guarantee that

**Comment by cakrit** [comment]
> All other linux

This needs to be greatly expanded and `kickstart-static64.sh` needs to be tested on all of them.
See https://repology.org/project/netdata/versions for a huge list, we need to filter the 50-70 that will be included here.

**Comment by paulkatsoulakis** [comment]
> > All other linux
> 
> This needs to be greatly expanded and `kickstart-static64.sh` needs to be tested on all of them.
> See https://repology.org/project/netdata/versions for a huge list, we need to filter the 50-70 that will be included here.

yep, i was thinking about this part, how to further expand in detail.
I 'll check repology now

**Comment by paulkatsoulakis** [comment]
At the healthy code column i 'll be embedding a Travis badge to indicate code health status per distro
https://docs.travis-ci.com/user/status-images/
