### ISSUE TITLE
Lot of ERROR messages.

### ISSUE THREAD

**Issue by HolgerHees** [netdata/netdata#6038]
Hi,

first thanks for this awesome software. But I have some trouble and I don't know how to proceed. First I try to find out what else I could provide for this report to be a good bug report.

First, I use the latest version (v1.14.0) from openSUSE build Service. I know, I should compile it by my self to avoid any other causes for this behavior. But for now I still use this package from there.

but now I try to describe my behavior. The good news is that netdata seems to run without any noticeable problems. But I get a lot of ERROR logs and I can't ignore them because otherwise I overlook other ERROR logs. So my policy in my system is to have 0 ERROR logs. Netdata is the last piece of software which prevents me from that.

from time to time I get ERROR messages like "child pid 13701 exited with code 1." without knowing which child process it was. So I don't know which plugin etc was generating this error.

another error I get from time to time is "read failed" followed by a "'/usr/lib/netdata/plugins.d/apps.plugin' (pid 11781) disconnected after 792055 successful data collections (ENDs)." or "'/usr/lib/netdata/plugins.d/nfacct.plugin' (pid 11780) disconnected after 72005 successful data collections (ENDs).". As this binaries are used to collect many different data I also not know what exactly was the problem.

If I check my process list I see that the command line for the parent process was "netdata CLEAR on at Wed May 15 13:00:26 CEST 2019: test.chart new value".

If I say from time to time, I mean ~10 times per day. Sometimes more. Sometimes less. I already tried to change the process scheduler to "other" with a nice value of 0. Because I'm running it on a 4 core atom based server with 16GB memory and a typical load between 0.5 and 1.5.

Is there anything else I can provide without compiling it with enabled debug flags?

best

**Comment by cakrit** [comment]
We haven't taken the time to review all the messages that go to error.log and you're absolutely correct, netdata is very chatty there. We certainly need to review those messages and do fixes, but it's not a trivial task. I think we can keep this as a feature request and ask the community as well as the team to look into improvements that we can do in this area, with multiple PRs.

**Comment by ilyam8** [comment]
related: #5480

I don't know how to fix it, because it very depends on context - python.d.plugin produces a lot of `error` level messages during auto-detection, and this is ok,  because all those messages come from _jobs_ and in context of jobs they are errors for sure, but in context of plugin/netdata they are just warnings or even infos.

The easiest solution is to split log files and have a separate file for external plugins.

**Comment by ilyam8** [comment]
Related issue https://github.com/netdata/netdata/issues/7182

**Comment by cakrit** [comment]
Let's just add a file for external plugins and be done with this. It needs a resolution.

**Comment by thiagoftsm** [comment]
> Let's just add a file for external plugins and be done with this. It needs a resolution.

The PR that splits logs is already ready for review.
