### ISSUE TITLE
graphite doesn't always get all the metrics sent by netdata

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6042]
We verified that the issue with graphite not accepting all the metrics we send is not related to the new netdata version. After several tests, we saw that even with that older commit, netdata can still be sending metrics to graphite and graphite doesn't add them. So there may be something going on with the latest version of graphite we used in the tests and we may need to change something in our backend code. In any case, I will open a new issue for this investigation.

_Originally posted by @cakrit in https://github.com/netdata/netdata/issues/6039#issuecomment-493418063_

**Comment by vlvkobal** [comment]
Graphite is configured by default to not allow a lot of metrics to be created at once. Creation drops can be seen in `carbon.agents.<agent ID>.droppedCreates`. To change this behaviour two parameters should be tuned in `/opt/graphite/conf/carbon.conf`: `MAX_UPDATES_PER_SECOND` and `MAX_CREATES_PER_MINUTE`.
