### ISSUE TITLE
Nvidia SMI disabling after each update

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#6046]
Your netdata version: v1.14.0-55-nightly
OS: Fedora

With each update, the nvidia chart changes it's disabled_by_default = True values from "True" to "False".

Unsure if this is a bug, or if I'm enabling it incorrectly.

**Comment by cakrit** [comment]
In http://localhost:19999/netdata.conf, you will see the following two parameters:
```
	# config directory = /etc/netdata
	# stock config directory = /usr/lib/netdata/conf.d
```

To persist your configurations, don't edit the files under the `stock config directory` directly. Use the `[config directory]/edit-config` command, or copy the stock config file to its proper place under the [config directory] and edit it there.

**Comment by ilyam8** [comment]
> With each update, the nvidia chart changes it's disabled_by_default = True values from "True" to "False".

https://github.com/netdata/netdata/blob/132e8377489ef88e8ef2089d21fc5943ae196587/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L13

To enable the module you need to explicitly enable in [`python.d.conf`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python.d.conf)

To do it use intructions from prev post

**Comment by modem7** [comment]
Perfect!

Thank you very much guys, all sorted!
