### ISSUE TITLE
Nodes are inconsistently unreachables

### ISSUE THREAD

**Issue by SR-G** [netdata/netdata#6051]
##### Bug report summary

Some nodes are inconsistently reported as "unreachable" under the "nodes" feature ... whereas they are full available.

##### OS / Environment

Official docker container. Latest version.
Latest docker version.
Host irrelevant (but actually is archlinux up to date).

##### Netdata version (ouput of `netdata -V`)

`
bash-4.4# netdata -V
netdata v1.14.0-72-gdf1c4059
`

##### Component Name

Netdata cloud / "nodes" feature.

##### Steps To Reproduce

Declare three docker containers A, B, C on three different servers. In my situation :
- A is on a local server (192.168.8.X)
- B is on another local LAN server (192.168.8.Y) (but on the same network)
- C is a remote server on a VPS in a datacenter (A.B.C.D)

Netdata is started in the exact same way everywhere (same docker command, excepted the hostname (--hostname A or B or C)).

Then when accessing the "nodes" feature, some nodes are nearly all the time unreachable.
Even when using the netdata URL of the "A" node then switching to the nodes feature, the node where this netdata installation is running is considered as unreachable (see screenshot) ... which seems quite weird.

![example](https://i.imgur.com/0GvS2eR.png)

Behavior is inconsistent, sometime some nodes start to appear, then they are not reachable again ...
For example, when using the netdata installation on "C", i always see nodes B and C (but not A, whereas A is the same network than B). And so on.

Of course there is no firewall issues, and so on : pings are perfectly working from one node to another one, and the used client is able to reach every single netdata installation (A, B or C).
(client used is on the same LAN network than nodes A and B (192.168.Z) and has indeed access to everything)

##### Expected behavior

Have all the nodes accessible under the "nodes" feature.

**Comment by Deviousretard** [comment]
Node reach ability for me seems dependent on which domain I access the overview from. They only work when viewed in the node-viewer from their own domain.

At the dropdown menu for switching between nodes, there is this notifcation message.
" Checks may fail if you are viewing an HTTPS page and the server to be checked is HTTP only. " 
Now that might cause problems for me, but i can't find a place to switch between http or https..

**Comment by SR-G** [comment]
Ok but : 
- i'm not using HTTPS anywhere at this time (only HTTP all over the place)
- as shown in the screenshot, i'm indeed having the issue when browsing nodes from a given node itself (i.e., i enter "192.168.8.4:19999" (netdata host/port) in a browser, netdatas shows up, i switch to the "nodes" feature and then i have this exact node (192.168.8.4) marked as "unreachable" (whereas it is the node actually delivering the page ...)

**Comment by gmosx** [comment]
Hmm.. I suspect that the machine-guid on the node at 192.168.8.4 has changed. We will need to report this in a different way.

**Comment by gmosx** [comment]
@SR-G Any chance you can attach the output of the development console here? (e.g. in Chrome press F12).

Also can you attach the output of: `192.168.8.4:19999/api/v1/info`

Thanks.

**Comment by Deviousretard** [comment]
Ah, I'm getting a " (Reason: CORS header ‘Access-Control-Allow-Origin’ missing) " In the console. That probably explains it.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

**Comment by gmosx** [comment]
> Ah, I'm getting a " (Reason: CORS header ‘Access-Control-Allow-Origin’ missing) " In the console. That probably explains it.

Any chance you are running the agent behind some kind of proxy (e.g. nginx)? AFAIK, the agent's http daemon includes the ACAO header in all responses.

**Comment by Deviousretard** [comment]
Yep, nginx. I'll see if i can edit it later today.

**Comment by gmosx** [comment]
> I'll see if i can edit it later today.

Great, let me know if you resolve this.

**Comment by VLegakis** [comment]
> > I'll see if i can edit it later today.
> 
> Great, let me know if you resolve this.

Done

**Comment by gmosx** [comment]
@SR-G pushed a new version that shows the reason for the urls classified as invalid:

![image](https://user-images.githubusercontent.com/37342/58006003-a9706a80-7aef-11e9-9be6-d7c4b665649b.png)

Can you tell me what's the reason in your case?

**Comment by SR-G** [comment]
@gmosx Sure - is there a docker tag embedding your modification, or does i have to install the github trunk by hand ?

**Comment by cakrit** [comment]
> @gmosx Sure - is there a docker tag embedding your modification, or does i have to install the github trunk by hand ?

You should be able to see that message without updating netdata. The change was done server-side (cloud).

**Comment by SR-G** [comment]
@gmosx Has anything be corrected on server side, in addition to the new log being added on the web screen about reason why a node is unreachable ?

Because, indeed, for now i'm not able anymore to reproduce the issue (and of course nothing has been changed in the meanwhile on my side, neither on netdata setup nor on network environment), after a few tries, all the nodes seem to be reachable each time for now (whatever the source node / url is). They are now grayed / unreachable on page load during less than 1s, and are then switched to reachable.

Not sure my additional details are relevant when everything is working - seems to be coherent here :

`
{
	"version": "v1.14.0-72-gdf1c4059",
	"uid": "558af64c-79cd-11e9-88b4-0242ac11000e",
	"mirrored_hosts": [
		"netdata-jupiter"
	],
	"alarms": {
		"normal": 241,
		"warning": 2,
		"critical": 0
	},
	"os_name": "Alpine Linux",
	"os_id": "alpine",
	"os_id_like": "unknown",
	"os_version": "unknown",
	"os_version_id": "3.9.4",
	"os_detection": "/etc/os-release",
	"kernel_name": "Linux",
	"kernel_version": "4.19.27-1-lts",
	"architecture": "x86_64",
	"virtualization": "unknown",
	"virt_detection": "none",
	"container": "docker",
	"container_detection": "dockerenv",
	"collectors": [
		{
			"plugin": "proc.plugin",
			"module": "/proc/mdstat"
		},
		{
			"plugin": "apps.plugin",
			"module": ""
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/diskstats"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/softirqs"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/uptime"
		},
		{
			"plugin": "cgroups.plugin",
			"module": "systemd"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/meminfo"
		},
		{
			"plugin": "idlejitter.plugin",
			"module": ""
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/dev"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/stat/nf_conntrack"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/loadavg"
		},
		{
			"plugin": "proc.plugin",
			"module": "ipc"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/sockstat"
		},
		{
			"plugin": "statsd.plugin",
			"module": "stats"
		},
		{
			"plugin": "cgroups.plugin",
			"module": "stats"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/interrupts"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/snmp"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/stat"
		},
		{
			"plugin": "netdata",
			"module": "stats"
		},
		{
			"plugin": "diskspace.plugin",
			"module": ""
		},
		{
			"plugin": "web",
			"module": "stats"
		},
		{
			"plugin": "python.d.plugin",
			"module": "sensors"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/netstat"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/sys/kernel/random/entropy_avail"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/vmstat"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/snmp6"
		},
		{
			"plugin": "python.d.plugin",
			"module": ""
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/softnet_stat"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/sockstat6"
		},
		{
			"plugin": "cgroups.plugin",
			"module": "/sys/fs/cgroup"
		}
	]
}
`

**Comment by gmosx** [comment]
Nice to hear that this issue was resolved.
Can you please create a separate issue for the situation described in `edit2` and close this one?

**Comment by SR-G** [comment]
Sure, done in #6063
