### ISSUE TITLE
Varnish 6.2 empty statistics

### ISSUE THREAD

**Issue by setupgr** [netdata/netdata#6056]
Hello,

I can't see any statistics in varnish section.

Everything is null (0)

**Comment by ilyam8** [comment]
Hi @setupgr 

> Everything is null (0)

I am not clear. You see the `varnish` section, but all charts shows zeros?

___

Please show output from:
 - `varnishstat -1`
 - `./python.d.plugin debug varnish` (how to debug - [link](https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module))

**Comment by setupgr** [comment]
It seems ok now, or I think so.

Varnish.service config file was wrong.

Από: Ilya Mashchenko <notifications@github.com>
Αποστολή: Monday, May 20, 2019 3:43 PM
Προς: netdata/netdata <netdata@noreply.github.com>
Κοιν.: setupgr <setupgr@hotmail.com>; Mention <mention@noreply.github.com>
Θέμα: Re: [netdata/netdata] Varnish 6.2 empty statistics (#6056)


Hi @setupgr<https://github.com/setupgr>

Everything is null (0)

I am not clear. You see the varnish section, but all charts shows zeros?

________________________________

Please show output from:

  *   varnishstat -1
  *   ./python.d.plugin debug varnish (how to debug - link<https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module>)
