### ISSUE TITLE
Error flooding netdata error log

### ISSUE THREAD

**Issue by setupgr** [netdata/netdata#6058]
I have this error flooding netdata error log from top to button:

2019-05-20 18:43:25: netdata ERROR : BACKENDS : Failed to connect to '::1', port '2003' (errno 111, Connection refused)
2019-05-20 18:43:25: netdata ERROR : BACKENDS : Failed to connect to '127.0.0.1', port '2003' (errno 111, Connection refused)
2019-05-20 18:43:25: netdata ERROR : BACKENDS : BACKEND: failed to update database backend 'localhost'

How can I resolve this?

**Comment by vlvkobal** [comment]
It depends on what your goal is. If you want to archive your data to a graphite database, you should make the database management system listening on port 2003, and your firewall should allow a connection to the port. If you configured backend by mistake, just set `enabled = no` in `[backend]` section of `netdata.conf`.

**Comment by setupgr** [comment]
How can I open a port for that in CSF?

**Comment by setupgr** [comment]
I just open port 2003 tcp in/out in CSF.
How can I make the database management system listening on port 2003?

Latest error message: 
netdata.backend_metrics
number of metrics lost due to repeating failures to contact the backend server

**Comment by setupgr** [comment]
[backend]
	enabled = yes
	# host tags = 
	# data source = average
	# type = graphite
	 destination = 127.0.0.1:2003
	# prefix = netdata
	# hostname = ****myhostname
	# update every = 10
	# buffer on failures = 10
	# timeout ms = 20000
	# send names instead of ids = yes
	# send charts matching = *
	# send hosts matching = localhost *

**Comment by setupgr** [comment]
Never mind, I just disable backend.

Thank you
