### ISSUE TITLE
I just need to add a second raw of gauges, just under the first row

### ISSUE THREAD

**Issue by setupgr** [netdata/netdata#6059]
I just need to add a second raw of gauges, just under the first row.

Let's say I need to see 3 more gauges in the size of "used ram" gauge, with the same functionality for:
centos-home, sda1, sdb

I need them to be permanent - not to be removed in the next netdata update.

Any suggestions?

** I also comment this in Sep 28, 2018

**Comment by ilyam8** [comment]
Hi @setupgr 

It seems you need [custom dashboard](https://docs.netdata.cloud/web/gui/custom/)
