### ISSUE TITLE
netdata/dashboard: Rethink the zoom in/out functionality on the charts

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6061]
##### Feature idea summary
  I was wondering whether it would worth making the step of the zoom in/out buttons on the charts adjustable, so that the user can get faster to the desired timespan.  Short stepping probably made sense back in the day when netdata was focusing on recent history only.

  Alternatively, we could have buttons to change the view style in "day view", "hour view", "minute view". Not sure how we would want these buttons to alter the view, perhaps we could get some ideas on what would be the ideal functionality to make navigation in time faster.

<img width="1110" alt="Screenshot 2019-05-20 at 21 11 20" src="https://user-images.githubusercontent.com/34388743/58043181-3265c100-7b45-11e9-8c15-0c2f7e7c4b1e.png">

##### Expected behaviour
Make chart navigation faster and more efficient

**Comment by ilyam8** [comment]
>  buttons to change the view style in "day view", "hour view", "minute view"

i'd say we need this not only per chart but global per server

**Comment by cakrit** [comment]
These buttons will move out of the charts and go towards the bottom of the screen. Indeed they will be global for server and yes we need a better way to show longer timespans.

**Comment by cakrit** [comment]
Also, from #6135 

> ##### Feature idea summary
> Display the whole timeframe of stored Data with DBengine.
> 
> The the Moment in the webconsole only Memory Timeframe is display:
> netdata on centos01, collects every second 1.699 metrics, presented as 293 charts and monitored by 147 alarms, using **2 MB of memory for 1 hour, 6 mins and 36 secs of real-time history.**
> 
> ##### Expected behavior
> Display the whole timeframe stored in DB Engine

It's a good idea, even if it's not the default view.

**Comment by cakrit** [comment]
@ivorjvr and @oyabun as discussed, the time selector you're designing for the cloud should also be available on the agent UI. 
For the agent especially, the idea in https://github.com/netdata/netdata/issues/6061#issuecomment-496220481 above is interesting, i.e. something like a "Max" or "All data" option when selecting a timeframe.

**Comment by mailinglists35** [comment]
Hi,

Is there currently some workaround/manual editing available to zoom out much more than the gui allows?

I definitely understand netdata is designed with short term data retention, but I was wondering if it is possible to condense even more than the currently maximum possible that the minus sign allows (for example I'd like to fit in the display the entire past hour or the entire past 24 hours)

Thanks!

**Comment by ilyam8** [comment]
hi @mailinglists35 

i think no. Actually you can zoom out manualy for whatever period you want and do it faster then pushing over 9k times on `-` button

> http://127.0.0.1:19999/#menu_system_submenu_cpu;after=1579897306250;before=1579898169000;theme=slate;help=true

See `after`/`before` options, they are unixtimestamps, you can calc it yourself... 😄 

But it is just a snapshot, dashboard wont be updating 😢 

Probably i am missing something lets ask @jacekkolasa

**Comment by jacekkolasa** [comment]
No, unfortunately there is no other, hidden way... Well, fastest zooming out is probably when ALT+mouse-scroll. But i think we're getting quite close to releasing features to FE, date-range picker should come soon!

**Comment by ipeacocks** [comment]
> date-range picker should come soon!
Hope so. I am trying to use it for Raspberry Pi and it's good basic monitoring but w/o time range pick it's not so usable even for this scenario.
Anyway, thank you.

**Comment by kovacshuni** [comment]
i'd like to have this as well.
same discussion in https://github.com/netdata/netdata/issues/250

**Comment by ilyam8** [comment]
Fixed by adding date-time picker.
