### ISSUE TITLE
Can't unregister a new node with same IP

### ISSUE THREAD

**Issue by SR-G** [netdata/netdata#6063]
##### Bug report summary

While using the Nodes (beta) feature : i have several nodes declared and available.
I delete one node (by deleting the docker container and restarting it), this is generating a new GUID with the same previous IP. After that i have two nodes on the dashboard : 
- the new one (reachable)
- the old one (unreachable)

Problem is that i'm not able to delete the old unreachable one (deletion works but then the nodes is still available after refresh).

##### OS / Environment

Official docker container. Latest version.
Latest docker version.
Host irrelevant (but actually is archlinux up to date).

##### Netdata version (ouput of `netdata -V`)

bash-4.4# netdata -V netdata v1.14.0-72-gdf1c4059

##### Component Name

Netdata cloud / "nodes" feature.

##### Steps To Reproduce

1. Create several nodes through docker containers
2. Delete one node (docker stop + docker rm)
3. Recreate a new docker container (which will have same IP than before but of course a new GUID)
4. Enter the dashboard : we have two times the node (which is fine at this point)
5. Delete the unreachable node (same IP / old GUID) > this is working fine and unreachable node has now vanished
6. Refresh the dashboard
7. At this time i have to auth again through OAuth (which is a bit surprising) (sometimes i have this step 2 times)
8. I come back on the netdata panel, then switch again to the dashboard
9. Then when entering the dashboard again, i have again the new and old (unreachable) node

Step 4-5 : 

![step 4](https://i.imgur.com/VsbPjTj.png)

Post-step 5 :  

![post step 4](https://i.imgur.com/J1ezhIH.png)

Step 7 :  

![step 7](https://i.imgur.com/qKSXxBc.png)

Step 9 : 

![step 9](https://i.imgur.com/nWd54t2.png)

##### Expected behavior

Node removed should be really forgotten and should not reappear.

**Comment by gmosx** [comment]
Thank you for the report

> i have several nodes declared and available.
> I delete one node (by deleting the docker container and restarting it), this is generating a new GUID with the same previous IP.

@paulkatsoulakis, @cakrit: According to @ktsaou, this should not be the case. Can you investigate?

Of course we will check what happens on the cloud-side also.

**Comment by SR-G** [comment]
About the "new GUID", it's just an hypothesis on my side as i have for the shutdown (and now unreachable) node the "wrong machine guid" in the (new) additional detail about why the node is unreachable.

**Comment by cakrit** [comment]
> @paulkatsoulakis, @cakrit: According to @ktsaou, this should not be the case. Can you investigate?

Nope, this can definitely be the case. In Kubernetes we added a preStart to keep the same machine GUID and one could do the same in docker. However, IP or hostname could definitely be linked with different machine GUIDs at different times (as described here), or even at the same time (when you have a load balancer).

**Comment by cakrit** [comment]
We are feverishly working on a completely revamped version of the cloud, coming in ~1 month and we're not going to be making changes to the code that's now in production.

However, this case is special enough to warrant specific tests that we must execute, to verify that "visited nodes" are properly managed. @manos-saratsis @rduffield @cosmix please read through this so we ensure we have it fixed for launch, or shortly after.
