### ISSUE TITLE
New dbengine stil creates directories for individual charts in the cache directory.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#6067]
##### Bug report summary
When using the new dbengine memory mode, Netdata still creates all the same directories that it would for the save and map memory modes even though it puts nothing in them.

##### OS / Environment
x86_64 Gentoo (working on confirming on other distros)

##### Netdata version (ouput of `netdata -V`)
1.15.0

##### Component Name
database/engine

##### Steps To Reproduce
1. Configure Netdata to use the new dbengine memory mode and start it.
2. Check the contents of your configured cache directory.

##### Expected behavior
The `dbengine` memory mode should only create the directories it actually uses.

----

This isn't exactly critical or anything, it's just a bit of an annoyance.  I can entirely understand wanting to preserve these directories if they already exist, but creating them if they don't is a waste of resources when using the `dbengine` memory mode.

**Comment by mfundul** [comment]
@cakrit also noticed this bug, and I was also aware of it. It looked a little troublesome and we ignored it but I will look into it again and it will be fixed pretty soon.
