### ISSUE TITLE
Raspberry Pi 3B wrong CPU frequency display

### ISSUE THREAD

**Issue by JsBergbau** [netdata/netdata#6069]
##### Bug report summary
Netdata shows wrong CPU frequency, takes throttling not into account
##### OS / Environment
Raspbian 
uname -r
4.19.42-v7+

##### Netdata version (ouput of `netdata -V`)
netdata v1.14.0-rc0-20-nightly
##### Component Name
CPUs
##### Steps To Reproduce
Execute sysbench --num-threads=4 --test=cpu --cpu-max-prime=200000 run to heat CPU up. When it reaches 80 °C CPU frequency gets throttled (on Pi 3B+ beginning with 60 °C frequency gets reduced from 1400 MHz to 1200 MHz). netdata shows in Grap always 1400 MHz COU frequency. Probably CPU freq is read via /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq That always displays unthrottled frequency. On Raspberry the currenct frequency can be measured via /opt/vc/bin/vcgencmd measure_clock arm
##### Expected behavior
Show real frequency with respecting throttling via /opt/vc/bin/vcgencmd measure_clock arm

**Comment by vlvkobal** [comment]
CPU frequency can be reduced when the CPU is in an idle state or for battery life preserving, not only when it gets hot. So, we can't take this information into account.

**Comment by cakrit** [comment]
All the threads I found on https://raspberrypi.stackexchange.com/search?q=scaling_cur_freq say that it's supposed to contain the current frequency. One of the posts suggested that a user update their firmware if the file didn't exist. Do you have a reference that says that this metric is inaccurate in certain conditions?

**Comment by vlvkobal** [comment]
I'm sorry. I misunderstood the statement.

**Comment by Ferroin** [comment]
@cakrit is correct here.  If that file is not accurately reflecting the reduced frequency from thermal throttling, that should be reported upstream at https://github.com/raspberrypi/linux as it's a bug in _their_ cpufreq handling, not in Netdata (and it doesn't just affect Netdata, it affects _anything_ that uses that file for measuring the CPU frequency, which is pretty much everything on Linux as that's _the_ way to get the CPU frequency).

**Comment by JsBergbau** [comment]
Thanks for the hint. New bug report is open at https://github.com/raspberrypi/linux/issues/2986

**Comment by giuliomoro** [comment]
> it's a bug in _their_ cpufreq handling, not in Netdata (and it doesn't just affect Netdata, it affects _anything_ that uses that file for measuring the CPU frequency, which is pretty much everything on Linux as that's _the_ way to get the CPU frequency).

FWIW, the [docs](https://www.kernel.org/doc/html/v6.1/admin-guide/pm/cpufreq.html), say:

> scaling_cur_freq
> Current frequency of all of the CPUs belonging to this policy (in kHz).
> In the majority of cases, this is the frequency of the last P-state requested by the scaling driver from the hardware using the scaling interface provided by it, which may or may not reflect the frequency the CPU is actually running at (due to hardware design and other limitations).

So that cannot be relied upon in absolute terms. OTOH, there is `cpuinfo_cur_freq` which should (though it [doesn't](https://github.com/raspberrypi/linux/issues/5874) on the Pi) return the _actual_ hw frequency. It requires root privileges to be read, as it's potentially more expensive.

> cpuinfo_cur_freq
> Current frequency of the CPUs belonging to this policy as obtained from the hardware (in KHz).
> This is expected to be the frequency the hardware actually runs at. If that frequency cannot be determined, this attribute should not be present.

I don't know what netdata is or why it needs an accurate reading of the CPU. I just came across the issue on the Pi side and thought I'd add some context here.
