### ISSUE TITLE
Mass add Netdata nodes to Netdata Cloud/Nodes

### ISSUE THREAD

**Issue by JessedeJonge** [netdata/netdata#6076]
Hi, 

I just updated all my Netdata instances (154) and saw the new Netdata Nodes option in the menu bar. I actually like the overview it gives me, but I am wondering how to get all my nodes assigned to my account. Is there any way to mass add Netdata Instances to my account or do I need to visit all the 154 instances and log in?

**Comment by cakrit** [comment]
Right now, this is unfortunately the only way. We've planned the following major enhancements for these cases:
- Add all visited nodes automatically and provide button 'trust all'. 
- Add all master-slave nodes as trusted, if any one of them is trusted.
- (Later) Claim nodes without visiting them, by passing an identifier to their configuration.

**Comment by JessedeJonge** [comment]
Especially interested in the last enhancement. Thanks for the hard work.
