### ISSUE TITLE
Possible wrong paths in console (nodes) view

### ISSUE THREAD

**Issue by alejandrofm** [netdata/netdata#6085]
Hi, I'm using nginx as a proxy/auth for 3 servers with netdata installed.
Version: 1.15

The path for my nginx:
server:port/netdata/server2/console/index.html
where server# is the path to that server

When I load console (nodes) it looks for files in wrong paths, some examples:
/dashboard.js?v20190515 net::ERR_ABORTED 404 (Not Found)
it should be:
/netdata/server2/dashboard.js?v20190515

Same hapends with:
/static/img/netdata-logomark.svg
/api/v1/registry?action=hello&cb=http://xxx:###

This makes the SYSTEM tab empty, no logo, etc.

**Comment by cakrit** [comment]
Fixed in #6093, please get the latest commit and try again.
