### ISSUE TITLE
invalid help links on platform (web log nginx/apache)

### ISSUE THREAD

**Issue by alejandrofm** [netdata/netdata#6086]
location: /#menu_web_log_apache_submenu_clients
text: (check /etc/netdata/python.d/web_log.conf)
Links to: https://github.com/netdata/netdata/blob/master/conf.d/python.d/web_log.conf
Result: 404

location: /#menu_web_log_nginx
text: (check /etc/netdata/python.d/web_log.conf)
Links to: https://github.com/netdata/netdata/blob/master/conf.d/python.d/web_log.conf
Result: 404

**Comment by cakrit** [comment]
Thanks for the report @alejandrofm , pr #6087 fixes it.
