### ISSUE TITLE
don't spread a chart across extents

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#6106]
##### Feature idea summary
Try to not spread a chart across extents when using `memory mode = dbengine`. This will reduce the number of I/O requests needed to serve queries.

**Comment by Ferroin** [comment]
Just to clarify, is the issue here filesystem-level extents, or something internal to the dbengine files themselves?

**Comment by mfundul** [comment]
> 
> 
> Just to clarify, is the issue here filesystem-level extents, or something internal to the dbengine files themselves?

It's dbengine data-files internal extents.

**Comment by Ferroin** [comment]
@mfundal Thought so, but wanted to be sure (I've dealt with the other case before in other software, and it's a royal pain in the arse to even get remotely right).

**Comment by stelfrag** [comment]
This already works
