### ISSUE TITLE
Stopping collectors on master

### ISSUE THREAD

**Issue by michaal94** [netdata/netdata#6107]
Hi,

Is there a possibility to stop all collectors for Netdata (in netdata.conf I set all [plugins] to no - is that enough?)? Also, can I remove that whole instance from the dashboard menu? What I want to do is to use master only to show data from servers without collecting or displaying from the master.

**Comment by ilyam8** [comment]
Hi @michaal94 

> is that enough?

have you checked the dashboard?

All plugins `no` + statsd `no`

![Screenshot_20190523_204850](https://user-images.githubusercontent.com/22274335/58274750-33446000-7d9c-11e9-810c-b4993a115a36.png)

**Comment by michaal94** [comment]
On the dashboard I am left with blank page for my master. Can I get rid of it?

**Comment by ilyam8** [comment]
To be honest i am not clear how it is supposed to work - remove master dashboard and at the same to be able to switch between slaves and browse their data.

Do you mean to have only this and nothing else? :thinking: 

![Screenshot_20190523_211032](https://user-images.githubusercontent.com/22274335/58276089-3bea6580-7d9f-11e9-9093-8548b9f13eb6.png)

**Comment by michaal94** [comment]
It is like this:
![aaa](https://user-images.githubusercontent.com/25354680/58276471-70eebc00-7d8f-11e9-8be8-134ec62df019.png)

**Comment by ilyam8** [comment]
Yes. The question is what do you want? Have only header?

**Comment by michaal94** [comment]
I wanted to disable the tab in the menu

**Comment by cakrit** [comment]
There's nothing like what you're looking for. It looks like you need a very custom dashboard (i.e. your own index.html and main.js). We could leave this issue open for a bit, to see if other users are interested in such a feature.
