### ISSUE TITLE
"mdstat.mdX_disks" chart's total is misleading

### ISSUE THREAD

**Issue by UltimateByte** [netdata/netdata#6108]
##### Bug report summary
Minor issue here, also likely simple to fix.

Basically, I find the chart "mdstat.mdX_disks" to be misleading: 

To illustrate the way I noticed the issue, in this example, I have a 3 disks RAID 5 array:
![netdata raid inuse](https://user-images.githubusercontent.com/8805941/58288313-8249bf80-7db3-11e9-9891-53cd3f3f4818.PNG)

"Total" shows 3, in use shows 2 (since one disk is reconstructing).
Problem is on the graph, by looking it fast, it seems like I have 5 disks while I have 3.
I might be too one sided here but it doesn't make sens to me to present it that way. What do you think?

The max value of the chart equals to "total + in use", whereas what would be expected is: The max value is the total.
A better representation could be: the max value is active disks, and negative value would be out of RAID or "not in use" disks. this could be achieved by just subtracting "inuse" value from "total".

##### OS / Environment
OpenMediaVault (Debian 9 x64)

##### Netdata version (ouput of `netdata -V`)
v1.14.0-80-g132e8377

##### Component Name
mdstat.mdx_disks chart

##### Steps To Reproduce
Have any mdstat array with one disk or more, check the chart.
Notice that the chart's height is equal to "in use" disks + "total" disks.

##### Expected behavior
The "total" information is not that useful in the chart.
What I would do is a graph comparable to the network interface chart:
On top in green, you have active drives. On bottom in red, you have out of order drives.
This can be achieved with a simple subtraction.

PS:
BTW I was impressed/surprised/glad to see mdstat info in Netdata in the first place! Thanks again for the good work, keep up!

**Comment by vlvkobal** [comment]
@UltimateByte please check #6164. The issue should be fixed.

**Comment by UltimateByte** [comment]
Awesome, thank you @vlvkobal !

**Comment by vlvkobal** [comment]
Thank you @UltimateByte for reporting the issue!
