### ISSUE TITLE
Alarms on system boot

### ISSUE THREAD

**Issue by alejandrofm** [netdata/netdata#6114]
Hi, i'm using V1.15.

My system currently has 4gb of free disk space, I know it's low (same happened with 7gb, low too), I don't receive an alarm on normal usage, but on reboot I get this alarms saying **if the system continues to add data with the rate of the last hour**, the system is been ON for 1 minute, and on boot it could reserve some disk.
Using 1 minute for 60 minutes prediction seems off, after boot the line is horizontal, so it will not run out of space, nothing points to that.

I think it should wait at least for some seconds to start the calculations of a trend on netdata restart or system boot

This is what I receive

disk_space._dev 
estimated time the disk will run out of space, if the system continues to add data with the rate of the last hour

disk_inodes._dev
estimated time the disk will run out of inodes, if the system continues to allocate inodes with the rate of the last hour

disk_space._dev_shm
estimated time the disk will run out of space, if the system continues to add data with the rate of the last hour

disk_inodes._dev_shm
estimated time the disk will run out of inodes, if the system continues to allocate inodes with the rate of the last hour

disk_space._run
estimated time the disk will run out of space, if the system continues to add data with the rate of the last hour

disk_inodes._run
estimated time the disk will run out of inodes, if the system continues to allocate inodes with the rate of the last hour

disk_inodes._run_lock
estimated time the disk will run out of inodes, if the system continues to allocate inodes with the rate of the last hour
 
Thank you!

**Comment by cakrit** [comment]
I'd like to see the chart with a little over 1 hours' worth of data, for one of your disk space charts, right after the startup, where you get the alarm. Looking at how the calculations are done, you shouldn't be getting these alarms unless we mistakenly assume that the whole disk was available ~1 hour prior to the reboot. 

netdata checks the 10m period from now - 60 min until now - 50 min and it gets the minimum value of `avail` during that period. If the system was in use and in a normal state, `avail` at that point would be lower than at startup, so it should be impossible to get this alarm. If netdata doesn't have any data for that period, then it probably interpolates, based on the data it does have (I'll need to verify). If we do interpolate and the result is that we're showing a fully unitilized disk, then we definitely have a bug. Moreover, if this is the case, then a delay of a few seconds will probably not matter. 

I'll need to do some more checks to validate this hypothesis, but I need to see one of your charts first, so I can replicate the behavior.

**Comment by alejandrofm** [comment]
Hi, I need to restart the server again to test, I don't think it will happen this week, but if I restart it I'll post screenshots. Thank you

**Comment by cakrit** [comment]
Kind reminder. I'm removing the bug label so that the stale bot will catch it if we don't get a new comment in 30 days.

**Comment by alejandrofm** [comment]
Couldn't reproduce, maybe was a error in the build I was using then.

**Comment by cakrit** [comment]
Ok, thanks @alejandrofm . Let us know if you see it again.
