### ISSUE TITLE
Netdata 1.15 crashes on Ubuntu 16.04

### ISSUE THREAD

**Issue by bohannin** [netdata/netdata#6117]
Netdata was recently updated to 1.15 (manually as the updater script was stuck on 1.14).  Netdata starts then when the UI is hit, immediately crashes.  If I curl the url from the command line, I get the html response, but from a browser an ajax call once the page is loaded is crashing Netdata.  Ajax call is: https://netdata.url/api/v1/charts?_=1558732027083

I am reverse proxied through Nginx for https, but same behavior happens directly to netdata port.

Consistent syslog data for each crash:
May 24 17:11:11 hostname kernel: [80956.938297] traps: netdata[21704] general protection ip:40eed3 sp:7f42a0445110 error:0 in netdata[400000+de000]
May 24 17:11:11 hostname systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
May 24 17:11:11 hostname systemd[1]: netdata.service: Unit entered failed state.
May 24 17:11:11 hostname systemd[1]: netdata.service: Failed with result 'signal'.
May 24 17:11:41 hostname systemd[1]: netdata.service: Service hold-off time over, scheduling restart.
May 24 17:11:41 hostname systemd[1]: Stopped Real time performance monitoring.
May 24 17:11:41 hostname systemd[1]: Starting Real time performance monitoring...
May 24 17:11:41 hostname systemd[1]: Started Real time performance monitoring.

##### OS / Environment
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
Linux hostname 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0-11-nightly

**Comment by ilyam8** [comment]
@bohannin could you update to the latest and check if the problem is there?
```
./netdata -v
netdata v1.15.0-25-g9f532f49
```

**Comment by bohannin** [comment]
Thanks - I ran the updater which grabbed netdata v1.15.0-15-nightly, which has been stable so far.
