### ISSUE TITLE
New dashboard navigation menu

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#612]
Netdata dashboards have 2 menus:
1. The chart index at the right
2. The dashboard navigation menu at the top

We need to move much of the documentation inside the netdata dashboard ( #378 ), so a new navigation menu is needed.

This new menu will have the following items:
1. **search box**
   
   for charts, dimensions, other netdata servers
2. **charts**
   
   the right menu will appear as submenus here when the dashboard is viewed on mobile devices
3. **my-netdata**
   
   menu for linking to other netdata servers (servers will appear as submenus
4. **my-dashboards**
   
   like my-netdata, but for bookmarking custom dashboards
5. **settings**
6. **update check**
7. **add data collectors**
   
   documentation on configuring netdata for monitoring more applications. Ideally this documentation should download content from the a demo site too (i.e. `local` and `latest` versions).
   - System Resources
   - Firewall (iptables, synproxy)
   - Memory (ram, slab, ksm)
   - Disks
   - Network interfaces
   - Containers (docker, lxc, cgroups)
   - NFS File Servers
   - Network QoS
   - Applications Resource Utilization
   - Users Resource Utilization
   - User Groups Resource Utilization
   - Hardware Sensors
   - apache
   - nginx
   - mysql
   - bind (named)
   - squid
   - nut (UPS)
   - tomcat
   - php-fm
   - postfix
   - exim
   - SNMP devices
   
   of course any other collector will be added here
8. **help**
   - **issue tracker**
     
     link to github issues
   - **Configuration Guide**
     - netdata Configuration
     - charts.d.plugin Configuration
     - node.d Configuration
     - python.d Configuration
   - **Plugins API Guide**
   - **Web API Guide**
   - **Custom Dashboards Guide**
   - **Troubleshooting Guide**
     - Performance
     - Memory Usage
     - Embedding (IoT) Guide
9. links to
   - home @github
   - home @facebook
   - home @twitter

@simonnagl @paulfantom how does this look like?

**Comment by paulfantom** [comment]
At a quick glance, maybe it would be better to move **documentation**, **data collectors** and **issue tracker** under **help** submenu?

**Comment by ktsaou** [comment]
Especially for **data collectors** I have the impression that most users are not aware they can monitor more apps with netdata. This is the main reason I believe **add applications** or **add more charts** or **add data collectors** should be given a separate menu item. It is a very important menu entry.

I have also added accounts to various commercial solutions. They all share this menu item.

**Comment by ktsaou** [comment]
I moved **issue tracker** under **documentation** and renamed **documentation** to **help**.
