### ISSUE TITLE
netdata crash reports

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#6123]
To ensure the quality of netdata we should somehow collect crash reports.

So, every time a netdata agent crashes, we should be notified somehow.

The report should ideally include the following:

1. netdata version
2. netdata installation method
3. operating system identification information
4. backtrace of the point netdata crashed (optional)

I understand there are possibly 2 distinct cases these crashes should be handled:

- netdata running systemd - systemd most probably has a mechanism to track crashes
- init - we should provide our own mechanism to track crashes

Also, since we provide stable and nightly channels, I suggest that:

- netdata in stable channels should run with compiler optimizations enabled (backtrace will not be possible)
- netdata in unstable channels should run without compiler optimization enabled (backtrace will be possible)

Note that the kernel provides hooks for getting core dumps. However, we should be very careful not to enable those system-wide, as this may lead to unexpected behavior on production systems.

**Comment by Ferroin** [comment]
> netdata running systemd - systemd most probably has a mechanism to track crashes

AFAIK, there's no special extra handling with systemd beyond making it easier to set up an rlimit for core file size than most other init systems.  The 'special' stuff is pretty much universally distro (or meta-distro) specific (for example, ABRT on Fedora and friends), and is almost always handled through a global `/proc/sys/kernel/core_pattern` hook.

> netdata in unstable channels should run without compiler optimization enabled (backtrace will be possible)

I would very much encourage looking into this more concretely.  Most distros build things with `-O2` and still provide perfectly reasonable backtraces as long as debugging info is present (either embedded in the app, or as a separate package).  The only potential issue you could have at `-O2` is automatic inlining by GCC, but you can turn that off by itself.  Given this, I'd suggest we actually try getting a backtrace with `-O2` (keep in mind that you need to not strip the binary either) and see if there are any actual issues before deciding to ship a completely unoptimized version.  If we can't get a sane backtrace with `-O2`, we should then try `-Og` (newer GCC, enables all optimizations that would be enabled by `-O2` which don't interfere with the ability to debug the code, plus a few other things that make it easier to debug), though I seriously doubt that there will be actual issues with `-O2` provided the binary isn't stripped.

> Note that the kernel provides hooks for getting core dumps. However, we should be very careful not to enable those system-wide, as this may lead to unexpected behavior on production systems.

Not easily possible unless we have a separate process managing Netdata or enforce running in a container (and even the container approach will only work on very recent Linux kernels, as the core dump stuff has not been namespace aware for very long).

**Comment by ilyam8** [comment]
I think we can close this issue. We have Sentry now.
