### ISSUE TITLE
web_log reports unmatched lines

### ISSUE THREAD

**Issue by Komic** [netdata/netdata#6125]
This seems to be the problematic line (should parse as a 502):

```txt

2a01:abc:abc:abcd:abcd:abcd:abc:abc - - [26/May/2019:03:50:04 +0200] "GET /:/websockets/notifications?X-Plex-Token=redacted HTTP/1.1" 502 166 261 0.002 0.000, 0.004 "-" "okhttp/2.6.0"

```

**Comment by ilyam8** [comment]
Hi @Komic 	

> 0.000,

i think the problem is the comma. Do you really need it? What is you log format?

**Comment by Komic** [comment]
My log_format directive is the one provided by web_log.conf, `log_format netdata '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $request_length $request_time $upstream_response_time "$http_referer" "$http_user_agent"';`.

**Comment by Wing924** [comment]
upstream_response_time may contain "," if first upstream server return error and nginx request to second server.

**Comment by ilyam8** [comment]
ok, i think removing traling spaces from

https://github.com/netdata/netdata/blob/9f532f4981bdc4455a3115e580fe4014ff928efb/collectors/python.d.plugin/web_log/web_log.chart.py#L663

and

https://github.com/netdata/netdata/blob/9f532f4981bdc4455a3115e580fe4014ff928efb/collectors/python.d.plugin/web_log/web_log.chart.py#L671

will fix the problem, @Komic could you test it?

**Comment by Komic** [comment]
yup, that worked, thanks!

**Comment by Wing924** [comment]
btw, since upstream_response_time may contain space, you need to wrap it with double quotation.

**Comment by Wing924** [comment]
btw, since upstream_response_time may contain space, you need to wrap it with double quotation.
