### ISSUE TITLE
Reduce number of codacy issues

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6131]
We have an increase in the issues reported by Codacy and need to work on them. 
- 19 Python
- 1036 Markdown #5941. Actually depending on the Linter options, you can see thousands of warnings.
- 136 C

**Comment by ilyam8** [comment]
![Screenshot_20190527_143247](https://user-images.githubusercontent.com/22274335/58417058-5026af00-808c-11e9-965c-c22c4ed14e2c.png)

**Comment by cakrit** [comment]
![Screenshot from 2019-05-27 13-39-20](https://user-images.githubusercontent.com/43294513/58417443-14d4b200-8085-11e9-9274-29f6d2210e02.png)

You gotta love Codacy... :)

**Comment by vlvkobal** [comment]
@cakrit check if you are looking not at **netdata/netdata**
![image](https://user-images.githubusercontent.com/22008543/58418518-9e3db180-8090-11e9-9e76-0951d8056d24.png)

**Comment by vlvkobal** [comment]
Besides, we still have issues when new commits are checked not by netdata/netdata Codacy instance, but paulkatsoulakis/netdata.

**Comment by cakrit** [comment]
The pull requests are integrated with `paulkatsoulakis/netdata` instead of `netdata/netdata`. @paulkatsoulakis please fix it.

**Comment by paulkatsoulakis** [comment]
Guys, can you elaborate a bit more? Where do you see that the project is linked to the paulkatsoulakis/netdata repository? And why is this raising codacy errors in the first place even if that was true.

My account is used for the integration, is not using my repositories.

**Comment by paulkatsoulakis** [comment]
oh, github side, hm

**Comment by paulkatsoulakis** [comment]
Should be fixed now, let me know
