### ISSUE TITLE
Display the whole timeframe of real-time history when DB Engine is used

### ISSUE THREAD

**Issue by h0lzi** [netdata/netdata#6135]
##### Feature idea summary
Display the whole timeframe of stored Data with DBengine.

The the Moment in the webconsole only Memory Timeframe is display:
netdata on centos01, collects every second 1.699 metrics, presented as 293 charts and monitored by 147 alarms, using **2 MB of memory for 1 hour, 6 mins and 36 secs of real-time history.**

##### Expected behavior
Display the whole timeframe stored in DB Engine

**Comment by cakrit** [comment]
Thanks @h0lzi. It's a good idea. I added it to #6061 and I'll close this one as duplicate.
