### ISSUE TITLE
Netdata cloud - What information is stored?

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#6140]
I was starting to explore the new "Nodes" feature as part of 1.5 release and the integration with Netdata cloud but don't see any documentation on what sort of information will be stored offsite when I choose one of the authentication methods. 

My organization is apprehensive to store any information off the organization network so looking to see if this is only service metadata or network information such as IP's, domain names, url's will also be stored in the cloud?

**Comment by cakrit** [comment]
You're right @gamefundas, we need to update the [registry](https://docs.netdata.cloud/registry/) page with references to Netdata cloud. The information stored is what's mentioned in that page, except for the person guid, which is replaced with the info for the sign in functionality. So, when you sign in, we store URLs and host names.

The old registry did that as well, by default. To prevent it, you just don't sign in. To be able to still see a list of hosts, without storing info on the cloud, you can [use your own registry](https://docs.netdata.cloud/registry/#run-your-own-registry). Of course that means you won't have the node view, which is the point of this question.

We will be working on an on-premise version in Q3-Q4, as soon as we get most of t[he basic features](https://blog.netdata.cloud/posts/netdata-cloud-announcement/) implemented. We're keeping a list of people who have expressed interest in the on-premise version, so please send us an email to info@netdata.cloud, so we can notify you of any developments.

**Comment by cakrit** [comment]
I updated the docs in #6144.
