### ISSUE TITLE
Certifcate validation

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6141]
##### Feature idea summary
The current implementation of SSL only has two possibilities for the slave, either does not connect with master with invalid certificate or connect ignoring the error, we can improve this.

##### Expected behavior
To give more options for the users.

**Comment by cakrit** [comment]
Check section "Certificate Verification" in https://curl.haxx.se/docs/sslcerts.html, it covers all the cases. 
We will have the exact same thing whenever netdata acts as a client (i.e. in streaming and backends now, when a netdata agent tries to connect to https://netdata.cloud later). But the options should not be the same for all connections, each destination may require a different policy. So the correct place for these configurations is `stream.conf`, `[backend]` in `netdata.conf` etc.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
