### ISSUE TITLE
opensuse - installation by hand issues due to hardcoded libexec in netdata-installer.sh

### ISSUE THREAD

**Issue by RobDean69** [netdata/netdata#6153]
I get errors when trying to install Netdata on an OpenSUSE 15 system as below. Same errors when running an update. I have attached a full log as a text file.

`[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# chown -R root:netdata /usr/libexec/netdata
chown: cannot access '/usr/libexec/netdata': No such file or directory
FAILED

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# find /usr/libexec/netdata -type d -exec chmod 0755 {} ;
find: '/usr/libexec/netdata': No such file or directory
FAILED

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# find /usr/libexec/netdata -type f -exec chmod 0644 {} ;
find: '/usr/libexec/netdata': No such file or directory
FAILED

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# find /usr/libexec/netdata -type f -a -name *.plugin -exec chmod 0750 {} ;
find: '/usr/libexec/netdata': No such file or directory
FAILED

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# find /usr/libexec/netdata -type f -a -name *.sh -exec chmod 0755 {} ;
find: '/usr/libexec/netdata': No such file or directory

and also:

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# mv /tmp/netdata-go-r04XEL/go.d.plugin-v0.5.0.linux-amd64 /usr/libexec/netdata/plugins.d/go.d.plugin
mv: cannot move '/tmp/netdata-go-r04XEL/go.d.plugin-v0.5.0.linux-amd64' to '/usr/libexec/netdata/plugins.d/go.d.plugin': No such file or directory
FAILED

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# chown root:netdata /usr/libexec/netdata/plugins.d/go.d.plugin
chown: cannot access '/usr/libexec/netdata/plugins.d/go.d.plugin': No such file or directory
FAILED

[/tmp/netdata-kickstart-SJQXq1/netdata-v1.15.0]# chmod 0750 /usr/libexec/netdata/plugins.d/go.d.plugin
chmod: cannot access '/usr/libexec/netdata/plugins.d/go.d.plugin': No such file or directory
FAILED

[Error1.txt](https://github.com/netdata/netdata/files/3230272/Error1.txt)
`

**Comment by paulkatsoulakis** [comment]
linking with previous report #6092 

Hi @RobDean69, thanks for coming back with this report.  Allow me to mention that you should have re-opened issue #6092 when you commented, so that we don't miss it. My apologies at any case for now getting back with comments earlier.

I 'll check the issue and let you know.

**Comment by paulkatsoulakis** [comment]
@RobDean69 could you provide me with the output of `/etc/os-release` too?
Thanks !

**Comment by paulkatsoulakis** [comment]
```
XXXXXXXXX:~ # cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
XXXXXXXXXX:~ # uname -a
Linux XXXXXXXXXX 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
XXXXXXXXX:~ #       
```
I could not get a reproduce on a containerised environment with the above version.
I might have to try a bare metal install, so i need your os-release to make sure i use the right image

**Comment by RobDean69** [comment]
@paulkatsoulakis 

Running `cat /etc/os-release` gives 

`
NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
'

`uname -a` gives 
`Linux linux-087A 4.12.14-lp150.12.61-default #1 SMP Tue May 14 18:07:55 UTC 2019 (83c1242) x86_64 x86_64 x86_64 GNU/Linux`

I couldn't work out how to re-open the previous issue so I opened this one (I'm not a big user of github).
`

**Comment by paulkatsoulakis** [comment]
I have identified the root cause of this behaviour, now i am working on understanding the right solution to this. I 'll update once i have a solution at hand
