### ISSUE TITLE
Can't load known netdata agents from netdata.cloud

### ISSUE THREAD

**Issue by henrywhitaker3** [netdata/netdata#6154]
##### Bug report summary
Nodes won't load in the dropdown list, instead the message "Can't load known netdata agents from netdata.cloud!" is shown. Clicking on the 'Nodes' link in the navbar takes you to `/console.html` which is just a blank page, the console output is this: `Loading failed for the <script> with source “https://netdata.cloud/static/console/main.js?v=4”` although navigating to that link shows the javascript just fine.
##### OS / Environment
Ubuntu 18.04 LXC on Proxmox host, behind an NGINX reverse proxy (although the issue remains when navigating to `ip:19999`)
##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0-31-nightly
##### Steps To Reproduce
Login to nodes (?) with Github profile, try to get list of all nodes from netdata cloud
##### Expected behavior
Nodes to appear in the dropdown list

**Comment by gmosx** [comment]
Hey Henry, I cannot reproduce this issue. I am not really sure I understand how exactly you did it. Could you add some more info, e.g. a screenshot of the Developer Console?

**Comment by henrywhitaker3** [comment]
Here you go 
![Screenshot from 2019-05-30 16-40-58](https://user-images.githubusercontent.com/36062479/58644823-99c40380-82f1-11e9-9f99-e73db75d0c25.png)
The loading failed for googletagmanager only happens intermittently.

I've just tried deleting the local storage entry for `options.destroy_on_hide` but it doesn't change anything, just comes back as undefined on refresh. Weirdly, this issue only happens on certain PCs and not on others, although all tested both working and not working were running Ubuntu and using Firefox for the browser

**Comment by cakrit** [comment]
2 different .js files from two different locations is definitely a client issue. Can you check the "Network" view and see what you get? I would expect a network issue, perhaps a timeout?

**Comment by cakrit** [comment]
Closing due to no response, please comment if you still face an issue.
