### ISSUE TITLE
Add support for ThingM Blink(1) notification LED's

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6156]
If someone else wants to pick this up, I'd be more than happy to help with testing (I've got half-a-dozen of the USB LED modules this is supposed to work with (specifically, the mk2 revision), so I can test complex configurations), and would be happy to provide some advice on working with the CLI tool this is using, but I'm not sure that I'm the best person to push this forwards right now.

Unless you have some objection, I think the best way forwards right now would be to close this and start fresh on a new implementation, as much has changed in alarm-notify.sh since I last touched this, and what's here didn't ever consistently work to begin with.

If someone does do a new implementation, it might be worth looking instead at integrating with the Linux Kernel LED API, which includes support for the particular hardware this was designed to work with, as well as a lot of other hardware options, and thus might be more practically useful to a wider audience.

_Originally posted by @Ferroin in https://github.com/netdata/netdata/pull/3956#issuecomment-496625948_

**Comment by cakrit** [comment]
#3956 has a lot more details on this. If someone is interested in this, it's best to start from there.

**Comment by cakrit** [comment]
@Ferroin see if you can/want to pick this up again, otherwise please close it.

**Comment by Ferroin** [comment]
Similar case to #6158, I do want to take care of this, but it's just too low of a priority for the moment because of all the other stuff I'm working on.

**Comment by prologic** [comment]
I am closing this due to no response. This is a nice cool idea et all but I don't see us doing this anytime soon and it seems more like a pet project. As it stands right now the way alarm notifications works is fairly flexible that you could script up anything you wanted, including sending signals out via GPIO or IC2 and make a bunch of LEDs blink :D
