### ISSUE TITLE
Test Automation: Fuzz targets for OSS-fuzz (dynamic analysis tool)

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6162]
##### Feature idea summary
Spawned by #4256 
Netdata was accepted in https://github.com/google/oss-fuzz 3 years ago, but we haven't created any fuzz targets.

##### Expected behavior

t is SUGGESTED that at least one dynamic analysis tool be applied to any proposed major production release of the software before its release. dynamic_analysis A dynamic analysis tool examines the software by executing it with specific inputs. For example, the project MAY use a fuzzing tool (e.g., American Fuzzy Lop) or a web application scanner (e.g., OWASP ZAP or w3af). In some cases the OSS-Fuzz project may be willing to apply fuzz testing to your project. For purposes of this criterion the dynamic analysis tool *needs to vary the inputs in some way to look for various kinds of problems or be an automated test suite with at least 80% branch coverage*. The Wikipedia page on dynamic analysis and the OWASP page on fuzzing identify some dynamic analysis tools. The analysis tool(s) MAY be focused on looking for security vulnerabilities, but this is not required.

Whoever will pick this up can start from https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
