### ISSUE TITLE
Why is auto-update not working? V1.14.0

### ISSUE THREAD

**Issue by Joshua-Stringfellow** [netdata/netdata#6170]
##### Question summary

Why is netdata not automatically updating? We are using version v1.14.0, which appears to have been released since auto update was enabled by default, but it does not seem to be updating. We installed netdata using ``` bash <(curl -Ss https://my-netdata.io/kickstart.sh) ```. The cron job was created during the install, however, we are still on version v1.14.0.

##### OS / Environment

Ubuntu 14.04.6 LTS

##### Component Name
N/a

##### Expected results
The netdata instance I am using should be updated to version v1.15.0.

**Comment by cakrit** [comment]
Can you run the auto-updater manually and tell us what is says? Also, put here the contents of your `/etc/netdata/.environment` file, so we can check that too.

**Comment by Joshua-Stringfellow** [comment]
Contents of /et/netdata/.environment:
``` 
# Created by installer
PATH="/usr/lib/ccache:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
CFLAGS="-O2"
NETDATA_PREFIX=""
NETDATA_CONFIGURE_OPTIONS=""
NETDATA_ADDED_TO_GROUPS=" docker adm proxy"
INSTALL_UID="0"
REINSTALL_COMMAND="./netdata-installer.sh --auto-update "
RELEASE_CHANNEL="nightly"
# This value is meant to be populated by autoupdater (if enabled)
NETDATA_TARBALL_CHECKSUM=""
```
Result from running updater manually:
```
Thu May 30 10:02:54 CDT 2019 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
40863aa10e86f24d3df0836386cf243f86b22edb534eef2d19d942c93390680c *./latest-version.txt
4b5354bb34e9a78189edf3e55819f2de30152d72f1b1f292edb39d19bac3fcd5 *./netdata-latest.gz.run
7345d455cd704ee3c53c27ffaf30890460db69b2de35120502705bb22f0ce851 *./netdata-latest.tar.gz
4b5354bb34e9a78189edf3e55819f2de30152d72f1b1f292edb39d19bac3fcd5 *./netdata-v1.15.0-33-gf86173d6.gz.run
7345d455cd704ee3c53c27ffaf30890460db69b2de35120502705bb22f0ce851 *./netdata-v1.15.0-33-gf86173d6.tar.gz
Thu May 30 10:02:55 CDT 2019 : INFO:  Newest version is already installed
```

Result of ``` netdata -version ``` : ```netdata v1.14.0-rc0-29-nightly ```

**Comment by cakrit** [comment]
Thanks @Joshua-Stringfellow . Please update `/etc/netdata/.environment` and put anything non-empty in `NETDATA_TARBALL_CHECKSUM`. e.g. `=xyz`

@paulkatsoulakis please fix `https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-updater.sh#L98` to handle an empty `NETDATA_TARBALL_CHECKSUM` as well. (i.e. ensure we update when it's empty).
