### ISSUE TITLE
A failure to restore API access after Netdata restart due to memory leak

### ISSUE THREAD

**Issue by jakubgs** [netdata/netdata#6175]
### Summary

My `netdata` process stopped responding to API requests after being restarted due to a spike in memory usage.
Despite being unavailable it appeared to `systemd` as running.

### Versions

* `v1.12.2` - Netdata version
* `Ubuntu 18.04.2 LTS` - OS

### Steps To Reproduce

1. Run `netdata`
2. Try using up all the memory
3. See the API stop responding

I tried reproducing this using [`stress`](https://linux.die.net/man/1/stress) but the failures I could get resulted in process dying and being restarted by `systemd` without issues, restoring API access. So I couldn't get this exact failure mode.

Not sure if related byt the drop in memory available coincided with I/O spike, particularly `reads`.

### Expected Behaviour

I'd expect `netdata` to be able to handle a restart due to a spike in memory usage caused by another process.
Instead `netdata` silently failed and stopped responding to API requests after being restarted.

### Observed Behaviour

1. Noticed that my `/api/v1/alarms` healtcheck on the `netdata` process started failing with a timeout
  ```bash
   $ curl -sv http://localhost:8001/api/v1/alarms
  *   Trying 127.0.0.1...
  * TCP_NODELAY set
  ```
2. Checked the status of the process with `systemctl status` and got:
  ```
  ● netdata.service - Real time performance monitoring
    Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
    Active: active (running) since Thu 2019-05-30 10:31:26 UTC; 7h ago
   Process: 2029 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS
   Process: 2028 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
   Process: 2026 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCE
   Process: 2020 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
  Main PID: 2030 (netdata)
     Tasks: 1 (limit: 2362)
    CGroup: /system.slice/netdata.service
            └─2030 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling po
  ```
  This state had a distinct lack of other 2 processes that run along a healthy `netdata` process:
  ```
            ├─7098 /usr/libexec/netdata/plugins.d/apps.plugin 10
            └─7099 /usr/libexec/netdata/plugins.d/go.d.plugin 5
  ```
  Which indicates something clearly went wrong.
3. Checked the logs with `journalctl` which showed that the process died with `SIGKILL` and was restarted within a minute by `systemd`.
  ```journalctl
  May 30 10:30:55 node-01.do-ams3.swarm.test systemd[1]: netdata.service: Main process exited, code=killed, status=9/KILL
  May 30 10:30:55 node-01.do-ams3.swarm.test systemd[1]: netdata.service: Failed with result 'signal'.
  May 30 10:31:25 node-01.do-ams3.swarm.test systemd[1]: netdata.service: Service hold-off time over, scheduling restart.
  May 30 10:31:25 node-01.do-ams3.swarm.test systemd[1]: netdata.service: Scheduled restart job, restart counter is at 14.
  ```
4. Checked `strace` of the process and it was stuck on the [`pause()`](http://man7.org/linux/man-pages/man2/pause.2.html) call.
5. Successfully sent it `SIGUSR1`, `SIGUSR2`, and `SIGHUP` and it responded accordingly.
6. Terminated the process with `SIGTERM` without issues.
7. After process restart with `systemctl start` the API was back online.

### Possible Debugging Options?

What should I investigate next time I see this behavior before I kill the process?

One mistake I made was not using `-f` with `strace` when I encountered this issue, so I'll be sure to do that next time this manifests.

### Question

My understanding is that the `/usr/sbin/netdata` process is the one responsible for handling API requests. Is that correct?

**Comment by cakrit** [comment]
systemd did well to kill netdata. See [OOM Score](https://docs.netdata.cloud/daemon/#oom-score) if you want it to remain running when running out of memory, you'll need to decrease it. 
I'm not sure what happens with a high OOM Score when netdata starts again and the system is still under memory pressure. Perhaps systemd sends netdata the `pause` signal?  Someone else may be able to explain it better.

By the way, we strongly recommend you upgrade, even though it will not have an effect on this particular issue. We're in version 1.15.0 already! :)

**Comment by jakubgs** [comment]
Thanks for the suggestion about the OOM Score, I've adjusted that. We'll see what happens.

And thanks for reminding me about a new version!

**Comment by cakrit** [comment]
Sure, just please come back and close the issue if it works for you.

**Comment by jakubgs** [comment]
Since I've added the OOM score of `-1000` I haven't seen this issue, so I guess that helps.
