### ISSUE TITLE
Chart's "name" not streamed

### ISSUE THREAD

**Issue by csch42** [netdata/netdata#6177]
##### Bug report summary

A chart's "name" (if set in netdata.conf) is not passed up to the stream collector if streaming is enabled.

##### OS / Environment

Linux / various (Ubuntu 18.04 on x86_64 as well as Debian Stretch on mips)

##### Netdata version (ouput of `netdata -V`)

netdata v1.15.0-31-gecc5fd4

##### Component Name

Streaming

##### Steps To Reproduce

Configure "streaming" to a netdata collector, then set
(for example)

```
[net.eth0]
        name = foobar
```
in netdata.conf and restart netdata.

Verify that the chart is (locally) accessible by "net.eth0" as well as by "foobar".
(This works flawlessly in the current version)

Lookup the same chart on the streaming collector side. Only "net.net0" is found there. "foobar" is declared "Unknown".

(I verified, by wiresharking the stream, that the "name" (foobar) is not transmitted by the streaming client)

NB: The name can still be set on the collector side, by specifying something, like

```
[b3de7ca4-822f-11e9-b143-24a43cb3710f/net.eth0]
        name = foobar
```
by specifying the UUID of the streaming client → this also works as expected.

##### Expected behavior

Assuming the streaming protocol works along the lines of the plugin-streaming protocol (and it certainly looks like that in wireshark) the `CHART` statement's 2nd parameter is reserved to carry a name, but it appears to always the empty ("") inside the stream. It _should_ carry a name - if so configured on the streaming client.

**Comment by csch42** [comment]
Meanwhile I found this code-snippet in `streaming/rrdpush.c`

```
    // properly set the name for the remote end to parse it
    char *name = "";
    if(likely(st->name)) {
        if(unlikely(strcmp(st->id, st->name))) {
            // they differ
            name = strchr(st->name, '.');
            if(name)
                name++;
            else
                name = "";
        }
    }
```
 this means a name _must_ contain a period ('.') character or it isn't streamed. And if it does, only the part _after_ the period is streamed.

I wonder what the logic behind this might be? 🤔 It apparently makes the chart behave ("appear") differently on the streaming client than on the server/collector.

**Comment by csch42** [comment]
According to the logic _discovered_ on my previous comment I was able to convince the client to stream the name, by specifying

```
[net.eth0]
        name = lala.foobar
```

in `netdata.conf`. Verified by sniffing the stream with _Wireshark_ again, yielding

```
CHART "net.eth0" "foobar" "Bandwidth" "kilobits/s" "eth0" "net.net" "area" 7000 1 "   " "proc.plugin" "/proc/net/dev"
DIMENSION "received" "received" "incremental" 8 1000 "  "
DIMENSION "sent" "sent" "incremental" -8 1000 "  "
BEGIN "net.eth0" 0
SET "received" = 4018081196
SET "sent" = 2631515084
END

```
inside the stream. 

Yet, still "foobar" is nowhere to be found when querying the collector, so there is something wrong at the receiving end as well ... 🤷🏼‍♂️

Continuing to research ...

**Comment by cakrit** [comment]
Ok, I got it. Since the chart id doesn't change, the master doesn't bother to update the name. This is definitely a bug, but the workaround is easy, you just restart the master.
As for the reason for sending only the second part, it came from https://github.com/netdata/netdata/pull/4508. We have a problem with our chart names, because of the special characters that jQuery doesn't like. So all the `type` parts of the chart name replace special chars with underscores. This causes problems with duplicate chart names, e.g. if you have 'type-1.xxx' and 'type_1.xxx'. #4508 was just a band-aid, we do need to do something about this in the long run.

**Comment by cakrit** [comment]
As for the "bug" part, I think that if anything in the chart info changes (i.e. the collector starts sending something different), plugins.d should be updating the `st` structure. Can you take a look at this part @vlkobal?

**Comment by csch42** [comment]
So I now set the name to `net.foobar` on the client side (although I could've set it to `anything.foorbar` as well ...) and restarted streaming client & server. And now I have "net.foobar" as an alternative chart name I can use on either. I can live with that for now :-)

It should be documented, though, that `xxx.yyy` must be specified on the client ('.' inside) and it shows up as `type.yyy` on the stream collector (disregarding the xxx part).

BTW: The reason I want this is, that I run _netdata_ on a larger number of routers (UBNT EdgeRouters), will many different configurations and I want to _tag_ interfaces with _upstream_, _wlan_, _O&M_, etc., so I can have _unified_ dashboards for all of them, regardless of which physical interface plays a particular role on a given router.

Speaking of which: It'd be nice, if interface-alias strings would be carried too, but I'm not sure which chart-attribute would/could carry such an information. Maybe this would need a _generic_ "info", "remark", "label", "whatchamacallit" attribute for all charts?! 🤔

Anyhow: Thanks for your support!

**Comment by csch42** [comment]
PS: unfamiliar with this, hence asking: Should I close the "issue" with some sort of a "workaround found" state or how do I handle this?

**Comment by ilyam8** [comment]
That is the `name` param description: https://docs.netdata.cloud/collectors/plugins.d/#chart

To be honest i don't understand the reason behind this

https://github.com/netdata/netdata/blob/cc2b9d2b4c1b3fbac91ac64b2f0e81c7850e344c/streaming/rrdpush.c#L176-L180

it looks like a bug to me, but it is very likely i am missing something because comment is

https://github.com/netdata/netdata/blob/cc2b9d2b4c1b3fbac91ac64b2f0e81c7850e344c/streaming/rrdpush.c#L171

So it is `properly set the name` :thinking: 	


___ 

> Should I close the "issue"

i think no, at least documentation should be updated (if there is no bug)

**Comment by cakrit** [comment]
> it looks like a bug to me, but it is very likely i am missing something because comment is

It's what I wrote in https://github.com/netdata/netdata/issues/6177#issuecomment-497716657. "As for the reason..."

> at least documentation should be updated (if there is no bug)

Agreed. @vlvkobal , it looks like we need a completely new paragraph under https://docs.netdata.cloud/streaming/, mentioning the strangeness with naming charts and the need to restart the master.
