### ISSUE TITLE
Monitoring CPU usage of multiple Redis instances

### ISSUE THREAD

**Issue by trebonius0** [netdata/netdata#6183]
Hey guys

I'm setting up multiple Redis instances on my server, to take advantage of the multiple cores, as I'm using 80% of one core atm.
I followed the response given in this question: https://github.com/netdata/netdata/issues/1946 and I was able to successfully see multiple redis graphs :
![image](https://user-images.githubusercontent.com/14201457/58716608-b469ab80-83c9-11e9-845c-500d5cf18615.png)

The thing I would like to do now is to have different lines in the *Applications > CPU* graphs for each redis instance, to make sure none is close to 100% of one core. 
By default, redis is under a "nosql" key. I went to the apps_groups.conf file, removed redis from the nosql key and I added at the end: 
```
redis_6379: *redis*6379*
redis_6380: *redis*6380*
```

Indeed, when I do a `ps eaux | grep redis` I get

```
/usr/local/bin/redis-server *:6379 
/usr/local/bin/redis-server *:6380
```

But sadly, this does not work. 

So, how can I separate the different redis instances from the Applications > CPU graphs ?

Thanks

**Comment by vlvkobal** [comment]
You can't use an asterisk in the middle of the pattern. From the apps.plugin [documentation](https://docs.netdata.cloud/collectors/apps.plugin/#configuration):
> You can add an asterisk * at the beginning and/or the end of a process:
```
*name suffix mode: will search for processes ending with name (at /proc/PID/stat)
name* prefix mode: will search for processes beginning with name (at /proc/PID/stat)
*name* substring mode: will search for name in the whole command line (at /proc/PID/cmdline)
```
So, look at `/proc/PID/cmdline` for a Redis instance and figure out how to write a pattern in the form `*name*`.

**Comment by trebonius0** [comment]
Thanks :)
What if the command line itselfs contains a * ?

In my case the command line is

> /usr/local/bin/redis-server *:6379

**Comment by vlvkobal** [comment]
What is the content of `/proc/PID/cmdline` for this instance?

**Comment by trebonius0** [comment]
`/usr/local/bin/redis-server *:6379`

**Comment by vlvkobal** [comment]
Try using `"*/usr/local/bin/redis-server *:6379*"`.

**Comment by trebonius0** [comment]
It does not work as expected: in my apps_groups file I have 
redis_6379: */usr/local/bin/redis-server *:6379*                                                                                                                                                                                             redis_6380: */usr/local/bin/redis-server *:6380*    

and in netdata both are aggregated into the redis_6379 key.

**Comment by trebonius0** [comment]
Ok I found a way to do this. 
In the .service file; I set

> ExecStart=/bin/bash -c "exec -a redis_6379 /usr/local/bin/redis-server-6379 /etc/redis/redis-6379.conf"

And then I configure netdata apps group with *redis_6379*
