### ISSUE TITLE
Centos7 netdata only showing ssh bans and not other 13 filters.

### ISSUE THREAD

**Issue by eXcalibre** [netdata/netdata#6184]
##### Bug report summary
when using netdata to monitor the blocks and bans on my system, it only shows sshd bans. i have 14 jails active and l/ogging in the log file. so only 1 of the 14 jails actually displays on the netdata fail2ban section. i understand that netdata only displays bans since it was started and i have attempted to restart the netdata daemons as well as restarting the fail2ban server, both have no change to the single ssh logging only instead of all jails.

##### OS / Environment
Centos 7.6

##### Netdata version (ouput of `netdata -V`)
v1.15.0-42-nightly

##### Component Name
fail2ban

##### Steps to Reproduce
normal operation - stop/start or reload netdata or and fail2ban 

##### Expected behavior
netdata used to monitor and report acurately on all jails, i think around version 1.13 it started to show this issue, its hard to say exactly as the cron updater also failed to update, so i ran a manual remove and reinstall to get up to 1.15.x

ADDITIONAL info.
jails active
Status
|- Number of jail:	14
`- Jail list:	anohome, apache-badbots, apache-noscript, apache-overflows, dovecot, php-url-fopen, portscan, postfix, proftpd, relay, sasl, ssh, steve-sasl, webmin

ssh jail (logging and working on netdata)
fail2ban-client status ssh
Status for the jail: ssh
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  `- File list:	/var/log/secure
`- Actions
   |- Currently banned:	26
   |- Total banned:	26
   `- Banned IP list:	1.180.17.225 1.9.46.177 100.6.87.221 101.201.238.56 101.251.197.238 101.255.52.171 101.99.65.72 103.10.30.224 103.108.158.131 103.127.50.100 103.198.131.249 103.213.251.190 103.24.106.222 103.243.143.142 103.85.66.114 104.131.178.223 104.131.224.81 104.131.37.34 104.215.103.200 104.236.119.79 104.236.250.88 104.236.52.94 104.248.124.163 104.248.148.98 104.248.240.220 104.248.254.222

Dovecot  (not displayed on netdata)
fail2ban-client status ssh
Status for the jail: ssh
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  `- File list:	/var/log/secure
`- Actions
   |- Currently banned:	26
   |- Total banned:	26
   `- Banned IP list:	1.180.17.225 1.9.46.177 100.6.87.221 101.201.238.56 101.251.197.238 101.255.52.171 101.99.65.72 103.10.30.224 103.108.158.131 103.127.50.100 103.198.131.249 103.213.251.190 103.24.106.222 103.243.143.142 103.85.66.114 104.131.178.223 104.131.224.81 104.131.37.34 104.215.103.200 104.236.119.79 104.236.250.88 104.236.52.94 104.248.124.163 104.248.148.98 104.248.240.220 104.248.254.222

sasl (also not showing on netdata)
fail2ban-client status sasl
Status for the jail: sasl
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	1
|  `- Journal matches:	_SYSTEMD_UNIT=postfix.service
`- Actions
   |- Currently banned:	9
   |- Total banned:	9
   `- Banned IP list:	151.80.238.201 151.80.162.216 185.137.111.125 185.137.111.129 185.137.111.136 185.137.111.77 185.137.111.96 185.222.209.99 51.254.58.226

another sasl filter (also not showing on netdata.)
fail2ban-client status steve-sasl
Status for the jail: steve-sasl
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	10
|  `- File list:	/var/log/maillog
`- Actions
   |- Currently banned:	39
   |- Total banned:	39
   `- Banned IP list:	1.192.155.154 114.232.13.83 114.96.47.233 115.150.22.23 120.42.132.184 141.98.80.47 145.249.106.141 145.249.106.194 151.80.162.216 151.80.238.201 175.11.212.199 180.117.225.112 180.122.147.22 183.163.234.84 185.137.111.125 185.137.111.129 185.137.111.136 185.137.111.14 185.137.111.145 185.137.111.44 185.137.111.77 185.137.111.96 185.172.68.178 185.222.209.97 185.222.209.99 190.171.134.164 190.223.51.130 193.135.214.98 193.56.28.188 194.67.205.92 201.245.197.138 203.2.117.74 220.128.142.139 45.13.36.22 46.3.96.2 49.72.12.212 49.84.206.208 51.254.58.226 58.217.15.132

I have even removed both netdata and fail2ban and reinstalled them, but to no avail as the pro

**Comment by ilyam8** [comment]
Hi @eXcalibre 	
Could you run `faileban` module in [debug mode](https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module)?

**Comment by ilyam8** [comment]
> only showing ssh bans and not other 13 filters

https://github.com/netdata/netdata/blob/6d2ea32bd7349603a049f81554ac2b41441e4b21/collectors/python.d.plugin/fail2ban/fail2ban.chart.py#L206


^^ so if the jail auto detection failes to find any jails in the files module fall backs to only on jail - ssh.

It might be the case.

**Comment by eXcalibre** [comment]
I am a noob to this, so will try and see if i can do what you have asked. :) thanks for the advice ilyam.

**Comment by eXcalibre** [comment]
Thanks ilyam. you seem to have hit the problem there, it is using the DEFAULT_JAILS section, i made a change to the DEFAULT_JAILS and added in another jail and now the two jails show on the netdata dashboard.
Any idea how i can find out why its not finding/using my jail.local or jail.conf? (they are duplicated to make sure one is found).
in the meantime, i will look into the debug option you posted earlier and see if i can find more info.
thanks again.

**Comment by eXcalibre** [comment]
Ok so in debug mode, it all seems to be getting seen ok and all jails are visible.

On the dashboard only DEFAULT jails are displayed.?
Does this help in any way??

OUTPUT OF DEBUG

/usr/libexec/netdata/plugins.d/python.d.plugin fail2ban debug trace
2019-06-01 13:39:02: python.d INFO: plugin[main] : using python v2
2019-06-01 13:39:02: python.d INFO: plugin[main] : starting setup
2019-06-01 13:39:02: python.d INFO: plugin[main] : checking for config in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-06-01 13:39:02: python.d INFO: plugin[main] : config found, loading config '/usr/lib/netdata/conf.d/python.d.conf'
2019-06-01 13:39:02: python.d INFO: plugin[main] : config successfully loaded
2019-06-01 13:39:02: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
2019-06-01 13:39:02: python.d INFO: plugin[checker] : starting...
2019-06-01 13:39:02: python.d INFO: plugin[checker] : fail2ban : checking
2019-06-01 13:39:02: python.d INFO: plugin[checker] : fail2ban : source successfully loaded
2019-06-01 13:39:02: python.d INFO: plugin[checker] : fail2ban : found config file '/usr/lib/netdata/conf.d/python.d/fail2ban.conf'
2019-06-01 13:39:02: python.d INFO: plugin[checker] : fail2ban : created 1 job(s) from the config
2019-06-01 13:39:02: python.d DEBUG: fail2ban[fail2ban] : config files to parse: ['/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.d/jail.conf', '/etc/fail2ban/jail.d/00-firewalld.conf', '/etc/fail2ban/jail.local']
2019-06-01 13:39:02: python.d DEBUG: fail2ban[fail2ban] : /etc/fail2ban/jail.d/00-firewalld.conf parse failed
2019-06-01 13:39:02: python.d ERROR: fail2ban[fail2ban] : /etc/fail2ban/jail.local is not readable or not exist
2019-06-01 13:39:02: python.d INFO: fail2ban[fail2ban] : monitoring jails: ['DEFAULT', 'apache-overflows', 'ssh', 'webmin', 'proftpd', 'sasl', 'apache-noscript', 'apache-badbots', 'php-url-fopen', 'dovecot', 'anohome', 'relay', 'portscan', 'postfix', 'steve-sasl']
2019-06-01 13:39:02: python.d INFO: plugin[checker] : fail2ban[fail2ban] : check successful
2019-06-01 13:39:02: python.d INFO: plugin[checker] : terminating...
2019-06-01 13:39:02: python.d INFO: plugin[main] : stopping checker process
2019-06-01 13:39:02: python.d INFO: plugin[main] : setup complete, 1 active module(s) : '['fail2ban']'
2019-06-01 13:39:02: python.d INFO: plugin[main] : fail2ban : created 1 job(s)
2019-06-01 13:39:02: python.d INFO: plugin[main] : fail2ban[fail2ban] : init successful
2019-06-01 13:39:02: python.d DEBUG: fail2ban[fail2ban] : config files to parse: ['/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.d/jail.conf', '/etc/fail2ban/jail.d/00-firewalld.conf', '/etc/fail2ban/jail.local']
2019-06-01 13:39:02: python.d DEBUG: fail2ban[fail2ban] : /etc/fail2ban/jail.d/00-firewalld.conf parse failed
2019-06-01 13:39:02: python.d ERROR: fail2ban[fail2ban] : /etc/fail2ban/jail.local is not readable or not exist
2019-06-01 13:39:02: python.d INFO: fail2ban[fail2ban] : monitoring jails: ['DEFAULT', 'apache-overflows', 'ssh', 'webmin', 'proftpd', 'sasl', 'apache-noscript', 'apache-badbots', 'php-url-fopen', 'dovecot', 'anohome', 'relay', 'portscan', 'postfix', 'steve-sasl']
2019-06-01 13:39:02: python.d INFO: plugin[main] : fail2ban[fail2ban] : check successful
CHART netdata.runtime_fail2ban '' 'Execution time for fail2ban' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2019-06-01 13:39:02: python.d INFO: plugin[main] : fail2ban[fail2ban] : started in thread
2019-06-01 13:39:02: python.d DEBUG: fail2ban[fail2ban] : started, update frequency: 1
CHART fail2ban.jails_in_jail '' 'Banned IPs (since the last restart of netdata)' 'IPs' 'in jail' 'jail.in_jail' line 60001 1 '' 'python.d.plugin' 'fail2ban'
DIMENSION 'DEFAULT_in_jail' 'DEFAULT' absolute 1 1 ' '
DIMENSION 'apache-overflows_in_jail' 'apache-overflows' absolute 1 1 ' '
DIMENSION 'ssh_in_jail' 'ssh' absolute 1 1 ' '
DIMENSION 'webmin_in_jail' 'webmin' absolute 1 1 ' '
DIMENSION 'proftpd_in_jail' 'proftpd' absolute 1 1 ' '
DIMENSION 'sasl_in_jail' 'sasl' absolute 1 1 ' '
DIMENSION 'apache-noscript_in_jail' 'apache-noscript' absolute 1 1 ' '
DIMENSION 'apache-badbots_in_jail' 'apache-badbots' absolute 1 1 ' '
DIMENSION 'php-url-fopen_in_jail' 'php-url-fopen' absolute 1 1 ' '
DIMENSION 'dovecot_in_jail' 'dovecot' absolute 1 1 ' '
DIMENSION 'anohome_in_jail' 'anohome' absolute 1 1 ' '
DIMENSION 'relay_in_jail' 'relay' absolute 1 1 ' '
DIMENSION 'portscan_in_jail' 'portscan' absolute 1 1 ' '
DIMENSION 'postfix_in_jail' 'postfix' absolute 1 1 ' '
DIMENSION 'steve-sasl_in_jail' 'steve-sasl' absolute 1 1 ' '

BEGIN fail2ban.jails_in_jail 0
SET 'DEFAULT_in_jail' = 0
SET 'apache-overflows_in_jail' = 0
SET 'ssh_in_jail' = 1
SET 'webmin_in_jail' = 0
SET 'proftpd_in_jail' = 0
SET 'sasl_in_jail' = 0
SET 'apache-noscript_in_jail' = 0
SET 'apache-badbots_in_jail' = 0
SET 'php-url-fopen_in_jail' = 0
SET 'dovecot_in_jail' = 0
SET 'anohome_in_jail' = 0
SET 'relay_in_jail' = 0
SET 'portscan_in_jail' = 0
SET 'postfix_in_jail' = 0
SET 'steve-sasl_in_jail' = 0
END

CHART fail2ban.jails_bans '' 'Jails Ban Rate' 'bans/s' 'bans' 'jail.bans' line 60000 1 '' 'python.d.plugin' 'fail2ban'
DIMENSION 'DEFAULT' 'DEFAULT' incremental 1 1 ' '
DIMENSION 'apache-overflows' 'apache-overflows' incremental 1 1 ' '
DIMENSION 'ssh' 'ssh' incremental 1 1 ' '
DIMENSION 'webmin' 'webmin' incremental 1 1 ' '
DIMENSION 'proftpd' 'proftpd' incremental 1 1 ' '
DIMENSION 'sasl' 'sasl' incremental 1 1 ' '
DIMENSION 'apache-noscript' 'apache-noscript' incremental 1 1 ' '
DIMENSION 'apache-badbots' 'apache-badbots' incremental 1 1 ' '
DIMENSION 'php-url-fopen' 'php-url-fopen' incremental 1 1 ' '
DIMENSION 'dovecot' 'dovecot' incremental 1 1 ' '
DIMENSION 'anohome' 'anohome' incremental 1 1 ' '
DIMENSION 'relay' 'relay' incremental 1 1 ' '
DIMENSION 'portscan' 'portscan' incremental 1 1 ' '
DIMENSION 'postfix' 'postfix' incremental 1 1 ' '
DIMENSION 'steve-sasl' 'steve-sasl' incremental 1 1 ' '

BEGIN fail2ban.jails_bans 0
SET 'DEFAULT' = 0
SET 'apache-overflows' = 0
SET 'ssh' = 1
SET 'webmin' = 0
SET 'proftpd' = 0
SET 'sasl' = 0
SET 'apache-noscript' = 0
SET 'apache-badbots' = 0
SET 'php-url-fopen' = 0
SET 'dovecot' = 0
SET 'anohome' = 0
SET 'relay' = 0
SET 'portscan' = 0
SET 'postfix' = 0
SET 'steve-sasl' = 0
END

BEGIN netdata.runtime_fail2ban 0
SET run_time = 1
END

2019-06-01 13:39:02: python.d DEBUG: fail2ban[fail2ban] : update => [OK] (elapsed time: 1, failed retries in a row: 0)
BEGIN fail2ban.jails_in_jail 1002023
SET 'DEFAULT_in_jail' = 0
SET 'apache-overflows_in_jail' = 0
SET 'ssh_in_jail' = 1
SET 'webmin_in_jail' = 0
SET 'proftpd_in_jail' = 0
SET 'sasl_in_jail' = 0
SET 'apache-noscript_in_jail' = 0
SET 'apache-badbots_in_jail' = 0
SET 'php-url-fopen_in_jail' = 0
SET 'dovecot_in_jail' = 1
SET 'anohome_in_jail' = 0
SET 'relay_in_jail' = 0
SET 'portscan_in_jail' = 0
SET 'postfix_in_jail' = 0
SET 'steve-sasl_in_jail' = 0
END

BEGIN fail2ban.jails_bans 1002023
SET 'DEFAULT' = 0
SET 'apache-overflows' = 0
SET 'ssh' = 1
SET 'webmin' = 0
SET 'proftpd' = 0
SET 'sasl' = 0
SET 'apache-noscript' = 0
SET 'apache-badbots' = 0
SET 'php-url-fopen' = 0
SET 'dovecot' = 1
SET 'anohome' = 0
SET 'relay' = 0
SET 'portscan' = 0
SET 'postfix' = 0
SET 'steve-sasl' = 0
END

BEGIN netdata.runtime_fail2ban 1002023
SET run_time = 2
END

2019-06-01 13:39:03: python.d DEBUG: fail2ban[fail2ban] : update => [OK] (elapsed time: 2, failed retries in a row: 0)
BEGIN fail2ban.jails_in_jail 996744
SET 'DEFAULT_in_jail' = 0
SET 'apache-overflows_in_jail' = 0
SET 'ssh_in_jail' = 2
SET 'webmin_in_jail' = 0
SET 'proftpd_in_jail' = 0
SET 'sasl_in_jail' = 0
SET 'apache-noscript_in_jail' = 0
SET 'apache-badbots_in_jail' = 0
SET 'php-url-fopen_in_jail' = 0
SET 'dovecot_in_jail' = 2
SET 'anohome_in_jail' = 0
SET 'relay_in_jail' = 0
SET 'portscan_in_jail' = 0
SET 'postfix_in_jail' = 0
SET 'steve-sasl_in_jail' = 0
END

BEGIN fail2ban.jails_bans 996744
SET 'DEFAULT' = 0
SET 'apache-overflows' = 0
SET 'ssh' = 2
SET 'webmin' = 0
SET 'proftpd' = 0
SET 'sasl' = 0
SET 'apache-noscript' = 0
SET 'apache-badbots' = 0
SET 'php-url-fopen' = 0
SET 'dovecot' = 2
SET 'anohome' = 0
SET 'relay' = 0
SET 'portscan' = 0
SET 'postfix' = 0
SET 'steve-sasl' = 0
END

BEGIN netdata.runtime_fail2ban 996744
SET run_time = 0
END

2019-06-01 13:39:04: python.d DEBUG: fail2ban[fail2ban] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
BEGIN fail2ban.jails_in_jail 999937
SET 'DEFAULT_in_jail' = 0
SET 'apache-overflows_in_jail' = 0
SET 'ssh_in_jail' = 4
SET 'webmin_in_jail' = 0
SET 'proftpd_in_jail' = 0
SET 'sasl_in_jail' = 0
SET 'apache-noscript_in_jail' = 0
SET 'apache-badbots_in_jail' = 0
SET 'php-url-fopen_in_jail' = 0
SET 'dovecot_in_jail' = 3
SET 'anohome_in_jail' = 0
SET 'relay_in_jail' = 0
SET 'portscan_in_jail' = 0
SET 'postfix_in_jail' = 0
SET 'steve-sasl_in_jail' = 0
END

BEGIN fail2ban.jails_bans 999937
SET 'DEFAULT' = 0
SET 'apache-overflows' = 0
SET 'ssh' = 4
SET 'webmin' = 0
SET 'proftpd' = 0
SET 'sasl' = 0
SET 'apache-noscript' = 0
SET 'apache-badbots' = 0
SET 'php-url-fopen' = 0
SET 'dovecot' = 3
SET 'anohome' = 0
SET 'relay' = 0
SET 'portscan' = 0
SET 'postfix' = 0
SET 'steve-sasl' = 0
END

BEGIN netdata.runtime_fail2ban 999937
SET run_time = 0
END

2019-06-01 13:39:05: python.d DEBUG: fail2ban[fail2ban] : update => [OK] (elapsed time: 0, failed retries in a row: 0)

**Comment by ilyam8** [comment]
Hey @eXcalibre 	

Did you execute plugin as `netdata` user? if you did it as `root` the problem is very likely is permissions - netdata is not able to read those dirs/files.

**Comment by ilyam8** [comment]
> 2019-06-01 13:39:02: python.d INFO: fail2ban[fail2ban] : monitoring jails: ['DEFAULT', 'apache-overflows', 'ssh', 'webmin', 'proftpd', 'sasl', 'apache-noscript', 'apache-badbots', 'php-url-fopen', 'dovecot', 'anohome', 'relay', 'portscan', 'postfix', 'steve-sasl']



btw what is `DEFAULT` ? :smile:

**Comment by ilyam8** [comment]
> Any idea how i can find out why its not finding/using my jail.local or jail.conf? (they are duplicated to make sure one is found).

> If needed, customizations should be provided in *.local files.

The order is

https://github.com/netdata/netdata/blob/6d2ea32bd7349603a049f81554ac2b41441e4b21/collectors/python.d.plugin/fail2ban/fail2ban.chart.py#L176-L181


See  `man jail.conf` for details

**Comment by eXcalibre** [comment]
> Hey @eXcalibre
> 
> Did you execute plugin as `netdata` user? if you did it as `root` the problem is very likely is permissions - netdata is not able to read those dirs/files.

Hi ilyam.
I did, but i have just run it again as netdata user and the output is the same. I have also set the permissions to 755 to make sure its readable.
I have just reloaded netdata and fail2ban and both are now displaying as expected, so it was a permission issue. 
sorry for reporting it, thanks for sorting it, ;)
