### ISSUE TITLE
netdata/packaging: Sporadic job failures in Travis CI

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6185]
##### Bug report summary
We seem to be facing some sporadic failures in Travis CI during package installation.
Suspecting the issue related to polyverse, but not 100% certain.
I am opening this for investigation with the support from the polyverse team

```
 ---> Running in d8567e2e2d1b
fetch http://mirrors.polyverse.io/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.polyverse.io/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/33) Installing fakeroot (1.23-r0)
(2/33) Installing sudo (1.8.25_p1-r2)
[91mERROR: fakeroot-1.23-r0: BAD signature
[0m[91mERROR: sudo-1.8.25_p1-r2: BAD signature
[0m(3/33) Installing libcap (2.26-r0)
[91mERROR: libcap-2.26-r0: BAD signature
[0m(4/33) Installing pax-utils (1.2.3-r0)
[91mERROR: pax-utils-1.2.3-r0: BAD signature
[0m(5/33) Installing libattr (2.4.47-r7)
(6/33) Installing attr (2.4.47-r7)
[91mERROR: libattr-2.4.47-r7: BAD signature
[0m[91mERROR: attr-2.4.47-r7: BAD signature
[0m(7/33) Installing tar (1.32-r0)
[91mERROR: [0m[91mtar-1.32-r0: BAD signature[0m[91m
[0m(8/33) Installing pkgconf (1.6.0-r0)
[91mERROR: pkgconf-1.6.0-r0: BAD signature[0m[91m
[0m(9/33) Installing patch (2.7.6-r4)
(10/33) Installing lzip (1.20-r0)
[91mERROR: patch-2.7.6-r4: BAD signature
[0m[91mERROR: lzip-1.20-r0: BAD signature
[0m(11/33) Installing abuild (3.3.1-r0)
[91mERROR: abuild-3.3.1-r0: BAD signature
[0m(12/33) Installing binutils (2.31.1-r2)
(13/33) Installing libmagic (5.36-r0)
[91mERROR: binutils-2.31.1-r2: BAD signature
[0m(14/33) Installing file (5.36-r0)
[91mERROR: libmagic-5.36-r0: BAD signature
[0m(15/33) Installing isl (0.18-r0)
[91mERROR: file-5.36-r0: BAD signature
[0m(16/33) Installing libgomp (8.3.0-r0)
[91mERROR: isl-0.18-r0: BAD signature
[0m(17/33) Installing libatomic (8.3.0-r0)
(18/33) Installing mpfr3 (3.1.5-r1)
[91mERROR: mpfr3-3.1.5-r1: BAD signature
[0m(19/33) Installing mpc1 (1.0.3-r1)
(20/33) Installing gcc (8.3.0-r0)
[91mERROR: mpc1-1.0.3-r1: BAD signature
[0m(21/33) Installing musl-dev (1.1.20-r4)
[91mERROR: musl-dev-1.1.20-r4: BAD signature
[0m(22/33) Installing libc-dev (0.7.1-r0)
[91mERROR: libc-dev-0.7.1-r0: BAD signature
[0m(23/33) Installing g++ (8.3.0-r0)
(24/33) Installing make (4.2.1-r2)
[91mERROR: make-4.2.1-r2: BAD signature
[0m(25/33) Installing fortify-headers (1.0-r0)
[91mERROR: fortify-headers-1.0-r0: BAD signature
[0m(26/33) Installing build-base (0.5-r1)
[91mERROR: build-base-0.5-r1: BAD signature
[0m(27/33) Installing pcre2 (10.32-r1)
[91mERROR: pcre2-10.32-r1: BAD signature
[0m(28/33) Installing git (2.20.1-r0)
[91mERROR: git-2.20.1-r0: BAD signature
[0m(29/33) Installing alpine-sdk (1.0-r0)
[91mERROR: alpine-sdk-1.0-r0: BAD signature
[0m(30/33) Installing py-egenix-mx-base (3.2.9-r0)
[91mERROR: py-egenix-mx-base-3.2.9-r0: BAD signature
[0m(31/33) Installing libldap (2.4.47-r2)
[91mERROR: libldap-2.4.47-r2: BAD signature
[0m(32/33) Installing libpq (11.3-r0)
(33/33) Installing py2-psycopg2 (2.7.5-r0)
[91mERROR: libpq-11.3-r0: BAD signature
[0mExecuting busybox-1.29.3-r10.trigger
28 errors; 264 MiB in 116 packages
The command '/bin/sh -c apk add make alpine-sdk &&     cd /judy-${JUDY_VER} && make install && cd / &&     rm -rf /judy-${JUDY_VER} && apk del make alpine-sdk &&     mv /usr/sbin/fping /usr/local/bin/fping &&     chmod 4755 /usr/local/bin/fping &&     mkdir -p /var/log/netdata &&     addgroup -g ${NETDATA_GID} -S netdata &&     adduser -S -H -s /usr/sbin/nologin -u ${NETDATA_GID} -h /etc/netdata -G netdata netdata &&     chown -R root:netdata /etc/netdata &&     chown -R netdata:netdata /var/cache/netdata /var/lib/netdata /usr/share/netdata &&     chown -R root:netdata /usr/lib/netdata &&     chown -R root:netdata /usr/libexec/netdata/ &&     chmod 4750 /usr/libexec/netdata/plugins.d/cgroup-network /usr/libexec/netdata/plugins.d/apps.plugin &&     chmod 0750 /var/lib/netdata /var/cache/netdata &&     ln -sf /dev/stdout /var/log/netdata/access.log &&     ln -sf /dev/stdout /var/log/netdata/debug.log &&     ln -sf /dev/stderr /var/log/netdata/error.log' returned a non-zero code: 28
travis_time:end:0b9a8d00:start=1559368083191449737,finish=1559368211513478995,duration=128322029258
[0K[31;1mThe command "packaging/docker/build.sh" exited with 28.[0m
```
##### OS / Environment
Any, CI related

##### Netdata version (ouput of `netdata -V`)
Not relevant to netdata version

##### Component Name
netdata/packaging/ci

##### Expected behavior
Package installation should not fail

**Comment by paulkatsoulakis** [comment]
Hello @archisgore, I 'll need your support on this. I am not sure i can find any further details about this issue from our side.

**Comment by archisgore** [comment]
Looking into this now. Please feel free to tag us anytime there's issues even if you don't suspect it is us, and we'll engage support and help. I'll post back soon....

**Comment by paulkatsoulakis** [comment]
Hello @archisgore, any news on the matter? Looks like a really sporadic issue, so not sure if we can manage to spot anything.

**Comment by archisgore** [comment]
We did some investigation. There was no repro obviously. What it looks like is a signature mismatch. We have a few theories and are looking into them. It may be caused during mirror-sync (when Alpine mirrors are sync'ing.) I'm looking through the APK source code to look for the signature mismatch and find what conditions may cause it.

**Comment by paulkatsoulakis** [comment]
> We did some investigation. There was no repro obviously. What it looks like is a signature mismatch. We have a few theories and are looking into them. It may be caused during mirror-sync (when Alpine mirrors are sync'ing.) I'm looking through the APK source code to look for the signature mismatch and find what conditions may cause it.

You could check the timestamps between the sync and the job above that is failing to verify the theory.

There is a timestamp that might help:
```
travis_time:end:0b9a8d00:start=1559368083191449737,finish=1559368211513478995,duration=128322029258
```

**Comment by archisgore** [comment]
@paulkatsoulakis Can you post a travis build link to a failed job? Ideally two? We are still investigating.

**Comment by paulkatsoulakis** [comment]
Here's a log that errored with that message: https://travis-ci.com/paulkatsoulakis/netdata/jobs/204862486

**Comment by archisgore** [comment]
Thank you!

**Comment by archisgore** [comment]
I'm testing for repros with and without this. I think I know what may be happening, but I'm going to confirm.

https://github.com/netdata/netdata/pull/6205

**Comment by archisgore** [comment]
Some more details:
1. The failure happens after the polyverse step, in the block that installs `apk add make alpine-sdk`

2. Notice in a successful build this is what is logged:
```
Step 15/18 : RUN     apk add make alpine-sdk &&     cd /judy-${JUDY_VER} && make install && cd / &&     rm -rf /judy-${JUDY_VER} && apk del make alpine-sdk &&     mv /usr/sbin/fping /usr/local/bin/fping &&     chmod 4755 /usr/local/bin/fping &&     mkdir -p /var/log/netdata &&     addgroup -g ${NETDATA_GID} -S netdata &&     adduser -S -H -s /usr/sbin/nologin -u ${NETDATA_GID} -h /etc/netdata -G netdata netdata &&     chown -R root:netdata /etc/netdata &&     chown -R netdata:netdata /var/cache/netdata /var/lib/netdata /usr/share/netdata &&     chown -R root:netdata /usr/lib/netdata &&     chown -R root:netdata /usr/libexec/netdata/ &&     chmod 4750 /usr/libexec/netdata/plugins.d/cgroup-network /usr/libexec/netdata/plugins.d/apps.plugin &&     chmod 0750 /var/lib/netdata /var/cache/netdata &&     ln -sf /dev/stdout /var/log/netdata/access.log &&     ln -sf /dev/stdout /var/log/netdata/debug.log &&     ln -sf /dev/stderr /var/log/netdata/error.log
 ---> Running in 067077b9e341
fetch https://alpine:eyJ2IjoyLjEsIkRhdGEiOnsibmlkIjoiYjI3M2QyYzMiLCJvaWQiOiJkZDE5NTU1YjIwYzVlNWQyYjVlNTU3MjlhNmMyZjQ1NiIsInRpZCI6Ik5DdVYzajI2In0sInMiOiJwcUVKZnZoKzlrdTVxUzFpbDhKSk15cHE3STN2WEdoVno1TjU4WnBiZmcwPSJ9@repo.polyverse.io/apk/alpine/3.9/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.polyverse.io/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch https://alpine:eyJ2IjoyLjEsIkRhdGEiOnsibmlkIjoiZDEzM2U5NmEiLCJvaWQiOiJkZDE5NTU1YjIwYzVlNWQyYjVlNTU3MjlhNmMyZjQ1NiIsInRpZCI6IjdmR2tBZFg3In0sInMiOiJWODBiRTN2djdrNllsU2xQb1AzbHVlTjFHMXc2NWtQbSt3NFVkWXQwOGxBPSJ9@repo.polyverse.io/apk/alpine/3.9/community/x86_64/APKINDEX.tar.gz
fetch http://mirrors.polyverse.io/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
fetch https://uk.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch https://uk.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
```

2. In the failed build you linked to:

```
Step 15/18 : RUN     apk add make alpine-sdk &&     cd /judy-${JUDY_VER} && make install && cd / &&     rm -rf /judy-${JUDY_VER} && apk del make alpine-sdk &&     mv /usr/sbin/fping /usr/local/bin/fping &&     chmod 4755 /usr/local/bin/fping &&     mkdir -p /var/log/netdata &&     addgroup -g ${NETDATA_GID} -S netdata &&     adduser -S -H -s /usr/sbin/nologin -u ${NETDATA_GID} -h /etc/netdata -G netdata netdata &&     chown -R root:netdata /etc/netdata &&     chown -R netdata:netdata /var/cache/netdata /var/lib/netdata /usr/share/netdata &&     chown -R root:netdata /usr/lib/netdata &&     chown -R root:netdata /usr/libexec/netdata/ &&     chmod 4750 /usr/libexec/netdata/plugins.d/cgroup-network /usr/libexec/netdata/plugins.d/apps.plugin &&     chmod 0750 /var/lib/netdata /var/cache/netdata &&     ln -sf /dev/stdout /var/log/netdata/access.log &&     ln -sf /dev/stdout /var/log/netdata/debug.log &&     ln -sf /dev/stderr /var/log/netdata/error.log
 ---> Running in 9149917eeb62
fetch http://mirrors.polyverse.io/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.polyverse.io/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/33) Installing fakeroot (1.23-r0)
(2/33) Installing sudo (1.8.25_p1-r2)
```

It only fetches two repositories. We are digging deeper into why this may happen intermittently. This is a big clue.

**Comment by archisgore** [comment]
Another instance (this is for self-reference) - I may edit this comment to add more instances:
https://travis-ci.com/paulkatsoulakis/netdata/jobs/204422848
https://travis-ci.com/paulkatsoulakis/netdata/jobs/203195752
https://travis-ci.com/paulkatsoulakis/netdata/jobs/204862486

**Comment by archisgore** [comment]
Seems the issue occurs exactly every four days (13 days ago, 9 days ago, 5 days ago, and one day ago.)

**Comment by paulkatsoulakis** [comment]
> Seems the issue occurs exactly every four days (13 days ago, 9 days ago, 5 days ago, and one day ago.)

So we are looking at some job that correlates with operations taking place on your side?
I do not recall we do anything at such intervals

**Comment by archisgore** [comment]
Still looking for commonalities and why this is happening. There's no process on our side that happens every four days either. 

I've found some commonalities and am now reproducing them on my host. This issue seems to be reported frequently on the Alpine User mailing list as a mirror problem. I'm trying to confirm.

**Comment by archisgore** [comment]
For instance, mirrors frequently rsync from each other. It's possible that there is some transient error. Just so we're on the same page, I don't see this issue going farther back than two weeks. Is that the same observation you have? So whatever is causing it, changed in the last two weeks.

**Comment by archisgore** [comment]
Our fork had the same failure 18 hours ago.
https://travis-ci.com/polyverse/netdata/jobs/205190086

**Comment by archisgore** [comment]
Just FYI, I want to wait till noon tomorrow (which'll be 24 hours from the last failure) and rerun my test. I have the container building every hour: https://travis-ci.com/polyverse/netdata/builds

If I don't find a consistent repro, we're ready to yank the polyverse mirrors. But I'd like to be sure that is the root cause, and nothing else.

**Comment by archisgore** [comment]
I got a repro locally between 10-11 PM PST last evening. This means it's not environmental (aka having to do with Travis). However, the fact that it happened on my laptop at the same time I saw it on Travis, tells me it is being triggered by remote behavior. Just what that behavior is and why it's occurring is something I'm still investigating.

**Comment by archisgore** [comment]
We found nothing yet on our side. I've not got a machine running this build in a loop 24/7. About 3-4 builds per hour. When it reoccurs, I've got probe scripts to download a lot of files and cache them. Just in case.

**Comment by archisgore** [comment]
To check in... I've got a script running 15 builds per hour. I saw one repro, but my probe didn't capture useful data. I've modified the probe and it's running. When it repeats, we have a script that'll curl all the various Alpine mirrors (including ours), along with the scrambling repo, and look for symptoms or discrepancies. All logs/metrics on our service seemed nominal during all incidents and I want to rule out a bad upstream mirror.

**Comment by archisgore** [comment]
We've finally narrowed down the problem on our side (or at least one problem, that the probes caught.) We're fixing it now.

**Comment by paulkatsoulakis** [comment]
Great news @archisgore thanks for attending this on a timely manner!
Let me know once this is resolved

**Comment by archisgore** [comment]
So here's what happened, and it's a weird one. This is the bug details from our internal issue which may be private for the outside:

Netdata faced this issue: https://github.com/netdata/netdata/issues/6185

After a LOT of debugging it was apparent that:
1. ELB metrics don't display the timeout.
2. There was no latency regression.
3. No server load or request load.

What is most likely happening is this. Under SSL connections, it is desirable to reuse the same TCP connection for multiple application-layer connections (HTTP), to avoid re-negotiating on every request.

The connection looks like this:

Client -> ELB -> Host

If possible the ELB creates a TCP connection to the host, in the absence of any client:

ELB ---- (TCP SSL connnection) ---> Host

And when the client hits the ELB, it can quickly hit that Host without the latency and overhead of negotiatinng.

Here's the problem:
1. ELB will assume the connection is valid for at least 60s from establishment (as configured in the ELB Description page).
2. Host may have closed the connection so far as it is concerned.

Now this happens:

Client -> ELB ---XXXX---> Host

ELB sees the connection is closed, and returns a 504 Gateway timeout immediately (within milliseconds).

The remedy as recommended by the internet, is to ensure the Host's IdleTimeout is larger than the ELB timeout. I'm making it double to be extra-safe, but greater by 5 seconds is considered sufficient.

**Comment by archisgore** [comment]
We're now merging and deploying this fix.

**Comment by paulkatsoulakis** [comment]
>ELB metrics don't display the timeout.

I think its time you start using netdata and let us know of the collectors required :)

**Comment by archisgore** [comment]
Yes indeed. :-)

**Comment by archisgore** [comment]
The fix is deployed on our side. We're still in holding pattern with our probes - if there's no repro in 7 days, we'll call it resolved.

**Comment by paulkatsoulakis** [comment]
Great news @archisgore, i think i 'll call it resolve now.
Please do keep the monitor as long as you believe is required to confirm the fix though.
I 'll open a new issue if i notice the problem again.

Thank you once again for your prompt response and resolution !
