### ISSUE TITLE
tv.html errors on https

### ISSUE THREAD

**Issue by 161134050** [netdata/netdata#6188]
##### Bug report summary
/tv.html fails to load the three left charts when accessed via https
![image](https://user-images.githubusercontent.com/39843740/58757522-40054880-8540-11e9-84bc-ce48f6beb878.png)

##### OS / Environment
Ubuntu 18.04 
##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0-42-nightly
##### Component Name
tv
##### Steps To Reproduce
Enable https on nginx, I just have it on Cloudflare with flexible SSL, (only Cloudflare edge to user), open ip:19999/tv.html 
##### Expected behavior
Netdata loads and updates graphs

![image](https://user-images.githubusercontent.com/39843740/58757570-c883e900-8540-11e9-98ad-8f1fb0137e86.png)

It seems like the page is requesting http:// for the chart and then my browser is refusing to load because of mixed-content

**Comment by thiagoftsm** [comment]
We have seen this while we were developing, in normal situation this happens due cache that the browsers keep, please, try to use the key combination "CTRL+SHIFT+R" to reolad the page completely.

**Comment by 161134050** [comment]
Nope, doesn't work :S I've removed cache, still happens

I also tried on firefox, same thing

**Comment by 161134050** [comment]
Yeah, it's still using http endpoints after clicking "load unsafe scripts'

example url 
http://registry.my-netdata.io/api/v1/chart?chart=system.cpu&_=1559485426115

**Comment by thiagoftsm** [comment]
I remembered a specific problem that we had with Nginx, I do not know if this can be your problem, so I will describe here to try to help you. In our case, we tried to use nginx to only redirect for our HTTPS Netdata with the initial configuration that we had, and the Nginx got failures, after some tests we discovered that the simple redirect was not enough, so we appended the following lines on our nginx server:

server {
proxy_set_header X-Forwarded-Proto https;
proxy_pass https://localhost:19999;
}

ssl on;
ssl_certificate /etc/nginx/cert.pem;
ssl_certificate_key /etc/nginx/key.pem;

Please, pay attention for the fact that the last three options that we set are global, while the other two were Virtual-Host( I apologize by the Apache terms that I am using here.).

Another information, the pem files here are not the same of the Netdata, therefore this is not a problem, we test the scenario where they use the same and everything worked too.

**Comment by 161134050** [comment]
I've added that config to my nginx and everything seems to be working fine now, thanks

**Comment by thiagoftsm** [comment]
You are welcome!

**Comment by 161134050** [comment]
Just kidding, I was accidentally viewing over http. 

Its still happening after applying that config

**Comment by thiagoftsm** [comment]
All right, let us continue working on this. As you could see there are two possible possibilities to error, so please, can you send us the access.log log for both (Netdata and Nginx)?

**Comment by cakrit** [comment]
It's just the http links in that file. The fix is in @6198.
