### ISSUE TITLE
Update frequency for x509check alarm

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#6193]
##### Bug report summary
Should the update frequency for the new template: x509check_last_collected_secs
in health/health.d/x509check.conf
be changed from 10 to 60s ?
It is getting set to 60 when go.d starts:
> netdata ERROR : PLUGINSD[go.d] : Health alarm 'x509check_example.site.time_until_expiration.x509check_last_collected_secs' has update every 10, less than chart update every 60. Setting alarm update frequency to 60.

Relevant line is number 8 in
health/health.d/x509check.conf

##### Component Name
health/health.d/x509check.conf

**Comment by ilyam8** [comment]
Hi @Steve8291, yes, you are right, thanks!
