### ISSUE TITLE
WSGI/FCGI/Application server metrics

### ISSUE THREAD

**Issue by HittingSmoke** [netdata/netdata#62]
I was hoping to contribute to these myself until I saw that it's written in C (I don't know C) so I'll just throw them out here in case anyone else is up to the task.

On the list of web-related server metrics supported so far it's just MySQL, Apache, and Nginx. I would be great to get some support for application backends.

PHP-FPM, like Nginx, has a statistics option to enable which will expose some numbers on the server: https://easyengine.io/tutorials/php/fpm-status-page/

uWSGI (usually for Python, but supports much more) supports basic server operational data as well as an endless metrics subsystem that can be customized to output any data available via a variety of methods inducing statsd, files, and sockets: http://uwsgi-docs.readthedocs.org/en/latest/Metrics.html

Circus (Python) has a top-like process viewer as well as CLI-based management commands: http://circus.readthedocs.org/en/latest/for-ops/cli/#cli

The three of those are quite widely used and all expose information that would make great metrics to show/record.

**Comment by ktsaou** [comment]
In which languages can you write?
If you can help it would be great, since I don't have all these installed.

Netdata external plugins is very simple (https://github.com/firehol/netdata/wiki/External-Plugins). You can write plugins in any language you like. Just 7 different lines are parsed by netdata. I can help you with this if you can handle the data collection itself.

**Comment by HittingSmoke** [comment]
I'm a devops guy so I'm not actually a programmer by trade. However I do Python via Django for some of my own web apps and know my way around HTML and CSS.

I'll fork the repo and look at how netdata parses information from Nginx stub-status. That should give me an idea of whether or not I can make something work easily for at least PHP-FPM and Circus. uWSGI will require a bit more work in exposing the metrics I think.

**Comment by ktsaou** [comment]
Nice!

It is a shell script: https://github.com/firehol/netdata/blob/master/charts.d/nginx.chart.sh

If the source data are JSON, you can use node. This is the `named` plugin: https://github.com/firehol/netdata/blob/master/node.d/named.node.js

and this is the simplest node.js JSON data collector is this: https://github.com/firehol/netdata/blob/master/node.d/sma_webbox.node.js

**Comment by ghprod** [comment]
:+1:

**Comment by FedericoCeratto** [comment]
Unfortunately there isn't a widely used protocol for application metrics, but StatsD seems to be gaining ground and has libraries for different languages. Some specs:
https://github.com/b/statsd_spec/blob/master/README.md
https://github.com/etsy/statsd/blob/master/docs/metric_types.md
https://github.com/etsy/statsd/blob/master/docs/namespacing.md

**Comment by paulfantom** [comment]
If you are using uWSGI, you can enable its embedded SNMP server and connect it to netdata SNMP plugin.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
