### ISSUE TITLE
Update fails because of new system dependencies

### ISSUE THREAD

**Issue by churnd** [netdata/netdata#6200]
I have netdata installed on several KVM hosts that run Debian 8/9.  I ran the install via `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` about a few months ago.  Over the weekend, they have all been failing to update due to missing system dependencies.  I decided to uninstall & reinstall on one of the hosts to see if it would install more packages that weren't already there.  Turns out, it did bring in several new packages:

```Loading /etc/os-release ...

/etc/os-release information:
NAME            : Debian GNU/Linux
VERSION         : 9 (stretch)
ID              : debian
ID_LIKE         :
VERSION_ID      : 9

We detected these:
Distribution    : debian
Version         : 9
Codename        : 9 (stretch)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2

 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'zlib1g-dev' is installed...
 > Checking if package 'uuid-dev' is installed...
 > Checking if package 'libmnl-dev' is installed...
 > Checking if package 'libuv1-dev' is installed...
dpkg-query: no packages found matching libuv1-dev
 > Checking if package 'liblz4-dev' is installed...
dpkg-query: no packages found matching liblz4-dev
 > Checking if package 'libssl-dev' is installed...
dpkg-query: no packages found matching libssl-dev
 > Checking if package 'libjudy-dev' is installed...
dpkg-query: no packages found matching libjudy-dev

The following command will be run:

 >> IMPORTANT <<
    Please make sure your system is up to date
    by running:   apt-get update

apt-get install libjudy-dev
apt-get install liblz4-dev
apt-get install libssl-dev
apt-get install libuv1-dev


Press ENTER to run it >
```

What is the proper procedure for handling new system requirements when netdata needs them?  I'm assuming the auto-update feature doesn't do this automatically (which is good IMO).  The updates were all failing due to the missing libssl-dev:

https://gist.github.com/churnd/496e0556d5fc442f001416b2320a5070

**Comment by cakrit** [comment]
The info on how to install the required packages is [here](https://docs.netdata.cloud/packaging/installer/#prepare-your-system). 

`kickstart.sh` also has the following installer options:
```
#  --dont-wait       do not prompt for user input
#  --non-interactive do not prompt for user input
```

With these options, the packages should be installed automatically (of course they're not enabled by default, which as you said, is a good thing).

**Comment by churnd** [comment]
Yes, that part is fine & applies to the initial setup.  My question is more of how do we handle it when we are using the netdata automatic updater via cron daily & it starts failing because netdata starts requiring some new packages that weren't required before?  What's the proper way to detect which packages are missing?  This seems like an oversight to what should be a more automated process.

**Comment by cakrit** [comment]
You're right, the [netdata-updater](https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-updater.sh) should be doing something about this. I'll discuss with @paulkatsoulakis, because we had said that we shouldn't be breaking the update process, even if the new packages were missing.

**Comment by paulkatsoulakis** [comment]
> You're right, the [netdata-updater](https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-updater.sh) should be doing something about this. I'll discuss with @paulkatsoulakis, because we had said that we shouldn't be breaking the update process, even if the new packages were missing.

Hello, indeed there shouldn't be any broken path because of missing dependencies regarding DB or SSL. I 'll have a look and let you know

**Comment by paulkatsoulakis** [comment]
At a first glance, i ran a brand new debian 8 docker image and executed kickstart that brought the same version with you (1.15.0-42).

Process did not fail, even though i did notice a package for db not being installed, thus db-engine not being available as an option.

I went ahead and checked why libuv1-dev is not installed and it seems that this is available only on Debian 9 and not on Debian 8.  I 'll research the alternatives to this, as dbengine is mission critical for us and we want it on all distributions.

Continuing investigation, no conclusions yet

**Comment by paulkatsoulakis** [comment]
One note: the file you provided on gist, does not seem to be the full log.
Could you check if you can find the full logs from the update process that failed ?

**Comment by churnd** [comment]
> One note: @churnd, the file you provided on gist, does not seem to be the full log.
> Could you check if you can find the full logs from the update process that failed ?

Where does the update process log to?  The gist was from the output of the cron job that was emailed to me.  I think it's pretty clear that the issue is missing dependencies added after a system was bootstrapped earlier this year, as @cakrit said above:  https://github.com/netdata/netdata/issues/6200#issuecomment-498301715.  The issue is not with NEW installs, it's with OLD installs & new system dependencies being introduced.

**Comment by paulkatsoulakis** [comment]
Ok i got the reproduce scenario @churnd. 
My apologies for facing this, we are working on a solution ASAP.
The installer should not fail in the absence of libraries for optional modules like DB engine or SSL support. 

I 'll update you as soon as the solution is pushed on tonight's nightly release.
Thanks for reporting the issue !

**Comment by Ferroin** [comment]
@paulkatsoulakis I don't know that there is any sane option for handling libuv1 on older versions of Debian (or other distros that don't have it) other than bundling the code ourselves to build it locally if we can't install it.  The simple fact is that Debian tends to lag a bit behind other distros on a lot of packages (see for example NodeJS, which is still on 4.8 (compared to 10.16 for upstream LTS) in Debian 9).

**Comment by paulkatsoulakis** [comment]
Our nightly process is in progress, next nightly will be with the fix for the above problem.
@churnd Please do let me know if the problem is now fixed

**Comment by ilyam8** [comment]
shouldnt we unpin the issue?

**Comment by cakrit** [comment]
Done
