### ISSUE TITLE
Pihole stats modules 

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#6204]
##### Feature idea summary
Pi-Hole monitoring

##### Expected behavior
As netdata works excellently on a pi, may I suggest some form of pihole stats monitoring? 

Eg. 
DNS
DHCP
Queries blocked 
Total queries 
Percent blocked
And maybe (unsure if there's any point in this one as the value rarely changes significantly) number of domains blocked. 

Pi-Hole now is available with an api, so it we should be able to get the information from it much like we can with a remote nginx instance.

**Comment by ilyam8** [comment]
Hi @modem7 	

> Pi-Hole now is available with an api, so it we should be able to get the information from it much like we can with a remote nginx instance.

Could you provide a link to the api readme with all endpoints etc.? i see it has API v2 and v3.

i found this app
https://github.com/Qrome/Pi-hole-Monitor

it uses `/admin/api.php?summary`.

**Comment by modem7** [comment]
This is what I can find:

https://discourse.pi-hole.net/t/pi-hole-api/1863
https://github.com/pi-hole/api
https://pi-hole.net/2018/10/15/announcing-our-restful-api-contributions-welcome/

api.php?summary shows the following:
![Capture1](https://user-images.githubusercontent.com/4349962/58895538-0f621200-86ec-11e9-81fb-377d4d6d12c7.JPG)
![Capture2](https://user-images.githubusercontent.com/4349962/58895539-0f621200-86ec-11e9-9537-811e9c894664.JPG)

Hope that helps some?

**Comment by ilyam8** [comment]
@modem7 

> api.php?summary

do you mean `/admin/api.php?summary` ?

i am not clear, with `api key` you have completely different response for same requests? or you get some info in addition?

What is `API key`? http basic auth?

**Comment by modem7** [comment]
Within PiHole there is an API key they call "WebPassword", which is similar in format to 7547b7cf6fb7947a7cf5bc3850b3614cf943c9867cb324543fe93739494857cd.

On here: https://discourse.pi-hole.net/t/pi-hole-api/1863 - you can see what values you are able to retrieve with and without the API key.

So https://pihole.myiphost.com/admin/api.php?**topClients**&auth=webpassword would allow you to view the top clients as you have authorisation, so it seems that we'd be able to get two types of values:

1. Unauthorized, so we'd be able to get it working out of the box
2. Authorized, needs additional config to enter the web password/api key.

Unsure if that made **any** sense!

**Comment by ilyam8** [comment]
Which of them are useful and deserves to be collected?

**Comment by modem7** [comment]
**values from /api.php?summaryRaw (no API key needed for these stats) (use /api.php?summary if formatted numbers are better):**

- Domains being blocked (unsure about this, some may like it, some may not): "domains_being_blocked"
- DNS Queries today "dns_queries_today"
- Ads Blocked today "ads_blocked_today"
- Ads percentage today "ads_percentage_today"
- Unique domains "unique_domains"
- queries forwarded "queries_forwarded"
- queries cached "queries_cached"
- unique clients "unique_clients" (this probably needs an alert if it increases)
- Clients Ever Seen "clients_ever_seen"
- Pihole status "status"

percent values from /api.php?getQueryTypes&auth=webpassword (needs API key)
A (IPv4)	
AAAA (IPv6)	
ANY	
SRV	
SOA	
PTR	
TXT	

- Percent values from /api.php?getForwardDestinations (these are dynamic)

e.g. jermaine-pc.home|192.168.0.223	45644

What are your thoughts?

**Comment by ilyam8** [comment]
Could you add metric types for those metrics? i mean [gauge/counter](https://prometheus.io/docs/concepts/metric_types/)

**Comment by Ferroin** [comment]
Other than the last two items and the `clients_ever_seen` value, all of those are pretty unquestionably useful values.  The `clients_ever_seen` value may or may not be useful depending on what exactly it tracks (if it's the total unique clients ever seen, then it's a better alarm trigger than `unique_clients`).  The relative query type percentages are mostly of interest to people who are super into monitoring _everything_, but likely aren't useful for alarms (they're too dependent on external factors to predict consistent values), and I'm not sure what the last item actually is.

Most of the values appear to be counters, except the percentages and status value which are obviously gauges.

**Comment by ilyam8** [comment]
i am not clear about the `_today` suffix. Are these counters reset every 24hr or what? :smile:

**Comment by modem7** [comment]
@Ferroin - I have to agree with you on that, I wasn't 100% sure on it myself, but yes, it's a "total ever seen" counter. The last item is top request frequencies per client.

@ilyam8 the "today" is value over the last 24 hours, which might be better as a more accurate measure of what's occurring, otherwise we'll either end up with a humongous number, or a dinky "did one, one another, did yet another". 

From what I understand (which is very little), all of these are gauges, unsure what you mean by type in this case, if you let me know, I'll see what fantastic notepad wizardry I can do!

What I'll also do, is get some screenshots of the dashboard so you can see what is visually represented (but not "monitored" per se) on the dashboard and I'll edit this post.

**Comment by ilyam8** [comment]
`gauge` - a value that can arbitrarily go up and down.
`counter` - a value can only increase or be reset to zero on restart.

i guess `_today` metrics are gauges. 

@modem7 you deleted some stuff, if it is sensitive just describe it in text.

**Comment by modem7** [comment]
I thought it was sensitive, but I was being a muppet. All of this is internal hostnames, in my case doesn't really matter if it's made public or not (hell, if they can scan the hostnames, I'm already screwed as they're in :P)

**Comment by ilyam8** [comment]
i think these deleted stuff is worth to chart. Btw netdatas gui is not able to sort dimensions in whatever order, so i don't know what to do with top charts

**Comment by modem7** [comment]
Oops - I derailed slightly. 

The top charts we'll ignore, was trying to equate it more to the gauges/counters part. 

The deleted items which were redacted got replaced with non-redacted parts, and for images 1 and 2, I replaced the with what information is shown on mouseover (which will most likely be part of the chart in question)

**Comment by modem7** [comment]
I've also posted here where the developer of pihole may have additional insights that I may not have regarding the API. I don't have any context on Netdata or how they h...

https://www.reddit.com/r/pihole/comments/bwtx9q/netdata_and_pihole_discussion/

**Comment by ilyam8** [comment]
ok, i installed `pi-hole`

that is what i get right after install

> api.php?summary

```json
{
    "domains_being_blocked": "113,438",
    "dns_queries_today": "187",
    "ads_blocked_today": "2",
    "ads_percentage_today": "1.1",
    "unique_domains": "21",
    "queries_forwarded": "48",
    "queries_cached": "33",
    "clients_ever_seen": "1",
    "unique_clients": "1",
    "dns_queries_all_types": "187",
    "reply_NODATA": "6",
    "reply_NXDOMAIN": "0",
    "reply_CNAME": "12",
    "reply_IP": "9",
    "privacy_level": "0",
    "status": "enabled",
    "gravity_last_updated": {
        "file_exists": true,
        "absolute": 1560443834,
        "relative": {
            "days": "0",
            "hours": "00",
            "minutes": "00"
        }
    }
}
```

**Comment by ilyam8** [comment]
ok, the collector is ready, i will be included in the next go.d.plugin version

alarms will be added later today
