### ISSUE TITLE
monitor dnsmasq dhcp server leases

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#6206]
@jlgoolsbee  did you ever get around to submitting a PR? On my machine, when pointing the `isc_dhcd` plugin at `/var/lib/misc/dnsmasq.leases`, the plugin crashes. Most likely due to the leases file having an unparsable format by the current plugin.

Log sample:

```
2019-06-04 05:54:50: python.d INFO: plugin[main] : isc_dhcpd[job_name] : started in thread
2019-06-04 05:54:50: netdata INFO  : PLUGINSD[python.d] : File /var/cache/netdata/netdata.runtime_isc_dhcpd_myname/run_time.db is too old (last 
collected 1559627690 seconds ago, but the database is 3996 seconds). Clearing it.
2019-06-04 05:54:52: alarm-notify.sh: INFO: not sending notification for CLEAR of 'router.net_packets.br0.inbound_packets_dropped_ratio' (last s
tatus was UNINITIALIZED)
2019-06-04 05:54:52: netdata ERROR : HEALTH : child pid 21334 exited with code 1.
```

_Originally posted by @naclander in https://github.com/netdata/netdata/issues/3179#issuecomment-498532234_

`dnsmasq` leases file example

(from google)
```
$ cat /var/lib/misc/dnsmasq.leases

1417132679 78:c5:e5:b4:4d:07 172.16.2.153 android-fbe390b0bb404da *
1417134678 20:54:76:e4:d8:a5 172.16.2.125 android-ab6e5d0a524c9c7d *
```

**Comment by naclander** [comment]
Would it make sense for this to be a whole new monitor? Or just extend the `isc_dhcpcd` monitor to also support he dnsmasq lease file format?

**Comment by ilyam8** [comment]
i think it would.

**Comment by ilyam8** [comment]
@naclander i added `dnsmasq_dhcp` collector.

It autodetects all dhcp-ranges reading `dnsmasq` configuration files.

[Readme](https://github.com/netdata/go.d.plugin/tree/master/modules/dnsmasq_dhcp).

![Screenshot_20190613_144410](https://user-images.githubusercontent.com/22274335/59430367-bdf00c00-8dea-11e9-873a-ed4b98258e3a.png)



What do you think?

Could you test it? You need `go` on your system to be able to compile the plugin from source.

**Comment by ilyam8** [comment]
hey @modem7 

Could you test it too? you are the pi-hole thing user, i think it uses `dnsmasq` as dhcp server

**Comment by ilyam8** [comment]
ok, the problem with that representation that i can't apply alarms for  all dhcp-ranges using template.

I think will i will add two charts (`active leases` and `utilization`) for every dhcp-range, dhcp-range will be the family.

**Comment by ilyam8** [comment]
Changed to

![Screenshot_20190613_184929](https://user-images.githubusercontent.com/22274335/59447540-11268680-8e0c-11e9-8471-9379853966fb.png)

**Comment by modem7** [comment]
Heya guys, 

If you could give me a bit of a crash course on compiling the go plugin for netdata, I'll happily test!

**Comment by ilyam8** [comment]
@modem7 	

Here you go:
 - `git clone https://github.com/netdata/go.d.plugin`
 - `cd go.d.plugin`
 - `make`
 - run module in debug mode
 > bin/godplugin -m dnsmasq_dhcp -d

you will see something like this

```
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 6
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] jobcreate.go:68 loading 'dnsmasq_dhcp' configuration
[ INFO  ] dnsmasq_dhcp[dnsmasq_dhcp] dhcp.go:72 start config : leases_path: [/opt/other/dnsmasq/leases], conf_path: [/opt/other/dnsmasq/dnsmasq.conf], conf_dir: [/opt/other/dnsmasq/dnsmasq.d]
[ INFO  ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:22 configuration files to read : [/opt/other/dnsmasq/dnsmasq.conf /opt/other/dnsmasq/dnsmasq.d/1.conf /opt/other/dnsmasq/dnsmasq.d/2.conf]
[ INFO  ] main[main] orchestrator.go:118 start main loop
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:28 reading /opt/other/dnsmasq/dnsmasq.conf
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found 'dhcp-range=192.168.0.0,192.168.0.9,12h'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:40 adding '192.168.0.0-192.168.0.9'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found 'dhcp-range=tag:green,192.168.1.0,192.168.1.9,12h'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:40 adding '192.168.1.0-192.168.1.9'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found 'dhcp-range = 1230::0, 1230::9'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:40 adding '1230::-1230::9'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found 'dhcp-range = 1235::2, 1235::500, ra-stateless'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found 'dhcp-range=1234::, ra-stateless, ra-names'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found 'dhcp-range=1234::, ra-stateless'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found 'dhcp-range=1234::, ra-only, 48h'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:28 reading /opt/other/dnsmasq/dnsmasq.d/1.conf
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found 'dhcp-range=192.168.2.0,192.168.2.9,12h'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:40 adding '192.168.2.0-192.168.2.9'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:28 reading /opt/other/dnsmasq/dnsmasq.d/2.conf
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:35 found 'dhcp-range = 1231::0, 1231::9'
[ DEBUG ] dnsmasq_dhcp[dnsmasq_dhcp] autodetection.go:40 adding '1231::-1231::9'
[ INFO  ] dnsmasq_dhcp[dnsmasq_dhcp] dhcp.go:100 using dhcp-ranges : [192.168.0.0-192.168.0.9 192.168.1.0-192.168.1.9 192.168.2.0-192.168.2.9 1230::-1230::9 1231::-1231::9]
```


To see the charts:
 - stop netdata.service
 - move/copy compiled plugin to the `plugins.d`
> cp bin/godplugin /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin
 - start netdata.service
 - see the dashboard

**Comment by modem7** [comment]
$ make
go mod download
make: go: Command not found
Makefile:10: recipe for target 'download' failed
make: *** [download] Error 127

**Comment by ilyam8** [comment]
https://drive.google.com/open?id=1Ew3kBemSSHl0cGYFZTsss5e6dgTSs2CF

**Comment by modem7** [comment]
user@Pi:~/go.d.plugin $ sudo su -s /bin/bash netdata
netdata@Pi:/home/pi/go.d.plugin$ /bin/godplugin -m dnsmasq_dhcp -d
bash: /bin/godplugin: cannot execute binary file: Exec format error

**Comment by ilyam8** [comment]
@modem7 do you use telegram? if yes ping me there (`ilyam8`)
