### ISSUE TITLE
easypiecharts: change label text size

### ISSUE THREAD

**Issue by Owned67** [netdata/netdata#621]
How to change pls, it's to small:
http://i.imgur.com/xCEGCxY.png

**Comment by ktsaou** [comment]
Yes I have tried to make the label bigger, but it does not look good (it overlaps with the circle; if we make the circle bigger to fit the labels, the charts become huge).

These charts are nice, but the label needs to be placed somewhere else...

**Comment by tx7** [comment]
How about put the label wrap around outside the charts?
And make the font size bigger.

**Comment by paulfantom** [comment]
Image is not accessible rendering this issue incomplete. Please attach new image if this issue is still valid and reopen it.
