### ISSUE TITLE
Script to test travis CI stages locally

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6211]
> Something that is very important to me is to somehow be able to run most tests locally and not depend on infrastructure and waiting indefinitely. This is very important for rapid testing cycles from the developer's perspective.

This makes a lot of sense.
We discussed with @paulkatsoulakis and he'll write a script for us to be able to run any travis stage we want locally.

_Originally posted by @cakrit in https://github.com/netdata/netdata/issues/6167#issuecomment-498609213_

**Comment by prologic** [comment]
As discussed internally this i no longer relevant as we have made the decision t migrate away from Travis CI to Github Actions and we do plan to be able to support running CI/CD workflows locally #8300
