### ISSUE TITLE
apps.plugin: add network interface bandwidth usage

### ISSUE THREAD

**Issue by idef1x** [netdata/netdata#6215]
##### Feature idea summary
the apps.plugin collector currently collects no network usage per application. Only opened network sockets.
I think it would be great to see/monitor which application/group is using the servers interface bandwidth

##### Expected behavior
Collection of interface bandwidth usage per application/group

**Comment by vlvkobal** [comment]
Do you have an idea of how it could be done? Does Linux have such information in `proc` filesystem?

**Comment by idef1x** [comment]
Not sure where exactly, but I was hoping you could do the same trick as doing for containers and use the metrics shown per cgroups? I am not a programmer, but will try to look for relevant info in the /proc filesystem...

**Comment by ilyam8** [comment]
found this
https://github.com/raboof/nethogs

> NetHogs is a small 'net top' tool. Instead of breaking the traffic down per protocol or per subnet, like most tools do, it groups bandwidth by process.

> NetHogs does not rely on a special kernel module to be loaded. If there's suddenly a lot of network traffic, you can fire up NetHogs and immediately see which PID is causing this. This makes it easy to identify programs that have gone wild and are suddenly taking up your bandwidth.

> Since NetHogs heavily relies on /proc, most features are only available on Linux. NetHogs can be built on Mac OS X and FreeBSD, but it will only show connections, not processes.

**Comment by idef1x** [comment]
Indeed and since nethogs makes use of /proc, it must be somewhere I would say. There's a /proc/[pid]/net/dev, but apparently that shows the same as /proc/net/dev :(

**Comment by vlvkobal** [comment]
NetHogs maintains a process list and a connection list, listens for TCP packets using libpcap, and finds what process the packet belongs to using the address and inode information from `/proc/net/tcp`. This method is neither precise nor simple.

**Comment by cakrit** [comment]
I get the 'not simple' part, but why 'not precise'?

**Comment by vlvkobal** [comment]
What about non-TCP traffic?

**Comment by cakrit** [comment]
Looks like pcap [can do UDP too](https://www.winpcap.org/docs/docs_412/html/group__wpcap__tut6.html)

**Comment by vlvkobal** [comment]
Yes, but how to find which process is responsible for a UDP packet transferred? Still, there is non-TCP && non-UDP traffic too.

**Comment by idef1x** [comment]
monitorix seems to do it  by reading /proc/[pid]/io (https://github.com/mikaku/Monitorix/blob/master/lib/process.pm) The outcome is substracting the read/write bytes from the read/write chars (see line 254). Doesn't look right to me though, since the man proc page defines it as storage io...The graphs monitorix produces looks quite alright, but have to look after some more tests if it's usable..

**Comment by idef1x** [comment]
I think it's more complex than I was hoping for..My latest (crazy?) idea would be to check which ports are being used by the process (lsof -ni |grep <process>) and create an iptables rule for that to count the packets/bytes. 

Problems with this is : 
- ports recycle, but on the other hand how big is the chance that both source and destination pairs show up for different processes?
-  not sure of the performance impact on the server though..

**Comment by idef1x** [comment]
Did some (probably ugly) scripting, which I am pretty sure it's not the best, but it's the best so far I could come up with ;)
Anyway it's based on looking for open IP sockets used by the process (only ipv4 supported for now) and creating iptables rules for it to measure the traffic usage. The script is based on outputting to graphite, so nothing to do with netdata, but to get an idea how it could be done? Anyway the script is on : https://github.com/idef1x/test/blob/master/process_network_usage.sh

**Comment by vlvkobal** [comment]
It was already implemented in the eBPF plugin. Look at `apps.bandwidth_sent` and `apps.bandwidth_recv`.
