### ISSUE TITLE
Difficulties understanding python.d chart plugin; multiple graphs

### ISSUE THREAD

**Issue by utdrmac** [netdata/netdata#6221]
##### Question summary
I'm trying to convert the charts.d NUT plugin to python.d. For the most part, I have this done. It works just fine with my environment.

There are two things I'm struggling with.

## 1.

The first is understanding how to tell the difference between "no config file provided" and "N number of jobs found in config."

If no config file present, the plugin should report on all connected UPS systems. This means that on the right menu of netdata, there would be N number of "UPS XXX" sections, where XXX is the detected name of the UPS.

If there is a config file, and a job, then those sections should appear. Multiple jobs is handled automatically.

What is the correct python logic to detect these two situations?

## 2.

Closely related to 1 above, if more than 1 job is configured, or more than 1 UPS is found in a no-config situation, how do I modify self.definitions to include more than 1 "set" of graphs so that each job appears as a group'd menu on the right-hand side?

##### Component Name
python.d plugin

**Comment by ilyam8** [comment]
Hi @utdrmac 

Number of configs == number of jobs. No config == 1 config.

> If no config file present, the plugin should report on all connected UPS systems. This means that on the right menu of netdata, there would be N number of "UPS XXX" sections

No, there will be once section but with N subsections (families), every subsection is a separate UPS.

> how do I modify self.definitions to include more than 1 "set" of graphs

you have set of charts for every UPS, in case of multiply UPS you need to add multiply set of these charts. All this should be done in `check()` method.

**Comment by utdrmac** [comment]
@ilyam8 
> Number of configs == number of jobs. No config == 1 config.

How do I count the number of configs?

> No, there will be once section but with N subsections (families), every subsection is a separate UPS.

Hmm. This is different from the docker plugin where it shows 1 'main menu' for each docker with same sub-sections for each container. But I can see under 'Disks', there is 1 submenu for each disk.

1 family == 1 UPS?

**Comment by ilyam8** [comment]
> How do I count the number of configs?

You don;t need to count them.

```yaml
job1:
  param1: value1
  param2: value2

job2:
  param1: value1
  param2: value2
```

^^ There you can see 2 jobs, so two instances of module (collector) will be initialized with these configs.

You can read about it in [any config file](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/adaptec_raid/adaptec_raid.conf).

> This is different from the docker plugin where it shows 1 'main menu' for each docker with same sub-sections for each container.

Yes, this is different.

**Comment by utdrmac** [comment]
@ilyam8 
If there is no config file provided, how do I detect that? If no config is provided, then my plugin should auto-detect all connected UPS. But how can my code detect the difference between no config and 1 config with multiple jobs?

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/blob/cae6ec1ad6d89dfc14665cc8d0af73086602bbd7/collectors/python.d.plugin/apache/apache.chart.py#L94-L99

config is `configuration`

i suggest to reflect flow from `nut.sh`

```
# a space separated list of UPS names
# if empty, the list returned by 'upsc -l' will be used
nut_ups=
```

if `nut_ups` is an empty list then consider it as do all.

```python
 class Service(UrlService): 
     def __init__(self, configuration=None, name=None): 
         UrlService.__init__(self, configuration=configuration, name=name) 
         self.order = ORDER 
         self.definitions = CHARTS 
         self.nut_ups = self.configuration.get('nut_ups') 
```

```yaml
job2:
  param1: value1
  param2: value2
```

^^ all job params in `configuration`.

**Comment by utdrmac** [comment]
@ilyam8 Yes, I know all that already and have all that code already. As I stated above, yes, I am trying to reflect the same flow from nut.sh. But I do not understand how to determine/detect if a config is provided or no config provided.

If no config provided, how do I detect this so that I can get a list of all UPSes? (I know how to get the list, I just do not understand how to determine _if_ I need to do so based on no-config/config present).

**Comment by utdrmac** [comment]
```
# Individual job specified?
upsname = self.configuration.get("upsname", None)
if upsname is not None:

		# add to array of upses
		self.upses.append(upsname)

		# get host/port for job, or use defaults
		self.host = self.configuration.get("host", "127.0.0.1")
		self.port = self.configuration.get("port", 3493)

		self.debug("Attempting to get info for %s@%s:%d" % (self.upsname, self.host, self.port))

else:
		# Get a list of configured UPSes
		self.upses = self.get_list()

# get data for 1 or all connected UPSes
data = self._get_data()
if data is None:
		self.debug("Unable to get data for any UPS")
		return False
```

**Comment by ilyam8** [comment]
> But I do not understand how to determine/detect if a config is provided or no config provided.

As i said earlier there is no `config not provided`, there is always at least one config (one job).

If there is something mandatory should be provided by the user and this mandatory is missing, then `check` should return false, that is it.

___

Could you describe the python version work flow? Is it using `ups` binary to get data?

**Comment by utdrmac** [comment]
I'm working inside netdata docker container. `upsd` is running on the host. My plugin uses the SocketService framework to connect to upsd on port 3943 (default) to run commands like 'LIST VARS $UPSNAME'

**Comment by ilyam8** [comment]
Nice. Is there a command to list all UPSs? I mean i see no reason to not chart some UPSs. Do you?

I suggest to remove filtering UPSs functionality, we can add it later if there will be request. What do you think?

**Comment by utdrmac** [comment]
Yes, `LIST UPS` :)
The goal was to support monitoring of UPSes on other hosts as well, but if you think that's overkill/unnecessary at this time, then I can simply rework it so that it only grabs UPSes connected to the `upsd` running on $host:$port.

**Comment by ilyam8** [comment]
>  so that it only grabs UPSes connected to the upsd running on $host:$port.

Well, there is always a possibility to add another job

```
local:
  host: 127.0.0.1
  port: 3943

remote:
  host: 10.0.0.1
  port: 3943
```

**Comment by utdrmac** [comment]
If I define `CHARTS` at the top of my python script, how do I duplicate this for each UPS and also modify the family?

```
ORDER = [
        'battery_voltage',
        'temp'
]

CHARTS = {
        'battery_voltage': {
                'options': [None, 'UPS Battery Voltage', 'Volts', 'ups', 'nut.battery.voltage', 'line'],
                'lines': [
                        ['battery_voltage', 'voltage', 'absolute', 1, 100],
                        ['battery_voltage_high', 'high', 'absolute', 1, 100],
                        ['battery_voltage_low', 'low', 'absolute', 1, 100],
                        ['battery_voltage_nominal', 'nominal', 'absolute', 1, 100]
                ]
        },
        'temp': {
                'options': [None, 'UPS Temperature', 'temperature', 'ups', 'nut.temperature', 'line'],
                'lines': [
                        ['temp', 'temp', 'absolute', 1, 100]
                ]
        }
}
```

**Comment by utdrmac** [comment]
Must I create each chart programmatically?

**Comment by utdrmac** [comment]
I'm so lost. I have no idea how to create additional charts with different family names. All my code seems incredibly "non-standard" way of doing it within the plugin.

**Comment by Ferroin** [comment]
A large part of the issue here is that documentation is somewhat lacking.  I would encourage you to take a look at the [unbound module](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/unbound/unbound.chart.py) for an example of how to do this if you just need to generate charts at module startup (which is what this case sounds like).  The module itself generates one chart per thread reported by unbound in it's stats. The relevant function is `_generate_perthread_charts`.

**Comment by ilyam8** [comment]
> I'm so lost. I have no idea how to create additional charts with different family names.

Well, write a function `def ups_chart_template(name)` that returns a set of charts.

example

https://github.com/netdata/netdata/blob/3b72bed2a5d42ad1f22f18b573a937a8f2e40e42/collectors/python.d.plugin/beanstalk/beanstalk.chart.py#L117-L168

___

flow is

1. write ups chart template func.
2. get all available ups in `check` method.
3. create charts for every ups name and update `self.order` and `self.definitions` in `check` method.
