### ISSUE TITLE
 kickstart.sh: Getting Nightly SHA256 sums from storage.googleapis.com times out

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#6227]
Related to #6191 

I'm getting the following on both Fedora and Debian:

> [/tmp/netdata-kickstart-uYwCmz]$ curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/sha256sums.txt
> curl: (7) Failed to connect to storage.googleapis.com port 443: Connection refused
>  FAILED
> 
>  ABORTED  Cannot download https://storage.googleapis.com/netdata-nightlies/sha256sums.txt

Not seeing any disruptions or outages on https://www.google.com/appsstatus#hl=en-GB&v=status

**Comment by cakrit** [comment]
Just did exactly the same thing and I have no problem. Of course it has nothing to do with the OS you're running on. Do you still have the issue?

**Comment by ilyam8** [comment]
[WORKSFORME](https://bugzilla.mozilla.org/show_bug.cgi?id=399463) finally!

**Comment by modem7** [comment]
@cakrit I certainly did, but I had a thought and it seems it was an ID10T error. 

I've recently set up a pi-hole, and it was blocking storage.googleapis.com.

FML. 

:D - Thanks for testing though! The label is perfect!
