### ISSUE TITLE
The number of cpu cores obtained in the docker container is inconsistent with the actual number of allocations.

### ISSUE THREAD

**Issue by chkch** [netdata/netdata#6229]
My service is k8s+Docker deployment mode. I install netdata in a single docker. The number of cpu cores and detailed data is the host, not the number of CPUs allocated to docker. (The host CPU is 40 cores, single. Taiwan docker is 2 cores)

The version is the latest v1.15, the operating system of the docker container is centos7, and the jdk version is 1.8u_211.

**Comment by vlvkobal** [comment]
Netdata is executed with the `-s /host` option in a docker container and reads information from `/host/proc` and `/proc/sys`. You can run netdata without the `-s` option and it will read `/proc` and `/sys`. But I don't see any sense in monitoring the container itself.

**Comment by cakrit** [comment]
@chckh we strongly suggest you use and help improve our [helm chart](https://github.com/netdata/helmchart) for k8s.

**Comment by chkch** [comment]
Thank you, I think I have got the answer I want.
