### ISSUE TITLE
Error during installation in devuan

### ISSUE THREAD

**Issue by ieguiguren** [netdata/netdata#6230]
#### Summary

During the installation in a Devuan GNU/Linux system, the installation script complaints about a not-known package:
```
 --- Install netdata at system init --- 
I don't know what init file to install on system 'devuan-1'. Open a github issue to help us fix it.
 FAILED  Cannot install netdata init service. 
```

Devuan is a GNU/Linux system which avoided the adoption of systemd. So it seems to lack the installation parameters for the classic init.d system.

#### System:
root@server:/opt# lsb_release -a         
No LSB modules are available.
Distributor ID:	Devuan
Description:	Devuan GNU/Linux 1.0 (jessie)
Release:	1.0
Codename:	jessie

#### Apt config
```
cat /etc/apt/sources.list
# 


deb http://de.mirror.devuan.org/merged/ jessie main
deb-src http://de.mirror.devuan.org/merged/ jessie main

# jessie-security, previously known as 'volatile'
deb http://de.mirror.devuan.org/merged/ jessie-security main non-free
deb-src http://de.mirror.devuan.org/merged/ jessie-security main non-free

# jessie-updates, previously known as 'volatile'
deb http://de.mirror.devuan.org/merged/ jessie-updates main non-free
deb-src http://de.mirror.devuan.org/merged/ jessie-updates main non-free

```

**Comment by paulkatsoulakis** [comment]
Hello @ieguiguren, thanks for reaching out to us!
In order to efficiently support you, we need to see the complete log of the installation so that we can tell what decisions netdata installer took end to end.

The fact that systemd installation failed, does not mean netdata failed to install.
In the end the installer should have instructed you how you can stop/start the service once done.

I also need to know exactly which commands you executed to install netdata on the system.

thanks!

**Comment by ieguiguren** [comment]
Hi, Paul. 

I hope this helps you. The command I ran was:
`
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates
`

Attached you may find the terminal output of the installation (so far I didn't found a log created by the installer).
[netdata_install.log](https://github.com/netdata/netdata/files/3275588/netdata_install.log)

> In the end the installer should have instructed you how you can stop/start the service once done.
Yes, that's correct, though it is not installed as a service AFAIK.

>The fact that systemd installation failed, does not mean netdata failed to install.
You're correct. The installation (upgrade in my case) completed successfully.

Thanks in advance for your help.

**Comment by paulkatsoulakis** [comment]
Hi @ieguiguren, thanks for your inputs! 
I think the terminal output is not complete.
Seems like you are missing parts of it.

Could you try executing the following and send me the resulting files? (`/tmp/netdata_installer_output`, `/tmp/netdata_installer_error`)

within a bash shell, execute the following command:

```
bash <(curl -sS https://my-netdata.io/kickstart.sh)  > /tmp/netdata_installer_output 2>/tmp/netdata_installer_error
```
