### ISSUE TITLE
SOLVED - SMTP configuration transport

### ISSUE THREAD

**Issue by panpansh** [netdata/netdata#6249]
like this tool I use from a nodejs app : https://nodemailer.com/smtp/
I can define directly the transport like that : 
```Json
host: '127.0.0.1',
port: 1025, 
secure: false, 
auth: {
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASSWORD
}
```
It can be nice to have the same possibility 👍 
Best Regards.

**Comment by cakrit** [comment]
Are you suggesting a new/addition email notification method for alarms that instead of using `sendmail` ([see here](https://docs.netdata.cloud/health/notifications/email/)] connects directly to an SMTP server?

**Comment by panpansh** [comment]
yeah but I have the solution 👍 
Maybe some users can like it then do this : 

remove sendmail
install msmtp
make a symbolic link of /usr/bin/msmtp to /usr/sbin/sendmail (default debian location of senddmail)
login as netdata
create and make configuration of ~/.msmtprc (look at the doc it's simple)
it works

**Comment by cakrit** [comment]
Awesome! Care to make a PR with this addition to the README [here](https://github.com/netdata/netdata/blob/master/health/notifications/email/README.md)? It may be of use to others :)

**Comment by panpansh** [comment]
https://github.com/netdata/netdata/commit/e515ecdd89cdfc559e79c5ff5695308cc8f6fbcc

**Comment by cakrit** [comment]
Excellent @panpansh, thanks! I requested a few changes in the PR, to make it even more awesome. :)
