### ISSUE TITLE
Support Veritas file system(VXFS) 

### ISSUE THREAD

**Issue by Pratik32** [netdata/netdata#6250]
##### Question summary
Can it monitor performance of Veritas filesystem (VXFS)?
I went through the project's summary page, I can see it supports VxVM but not VXFS.
I would like to ask if you have any plans of supporting it with VXFS.
I work on VXFS as developer, would like to contribute towards the project by enabling the support. 
Kindly respond.

**Comment by ilyam8** [comment]
Hi @Pratik32.

> Can it monitor performance of Veritas filesystem (VXFS)?
I went through the project's summary page, I can see it supports VxVM but not VXFS.

Yes, you are right, there is not support for VXFS atm.

> I work on VXFS as developer, would like to contribute towards the project by enabling the support.

This is great :+1: 	@vlvkobal

**Comment by ElCoyote27** [comment]
Hi @Pratik32 I'm using Netdata on vxfs RHEL7.x machines. There aren't many metrics but it works out of the box. If netdata could make use of vxstat, then I'm sure the stats would be better.

**Comment by Pratik32** [comment]
Hi @ElCoyote27 , VXFS has different types of metrics that we can use for its performance  analysis. e.g vxfsstat - this is a counters based utility that we can use for performance measurements. We also have other utilities to determine fragmentation `index.`
So, apart from vxstat(which measures disk/vol performance btw) we can do allot of other things with above mentioned utilities(there are many more).

**Comment by h0lzi** [comment]
Hi,
for i/o stats for VxVM the stuff that is reported to /proc/diskstats already works.
Having more stats is always good. We use netdata on SLES and Redhat for around 30 Vertias/Oracle clusters with vxfs and odm.
with https://github.com/netdata/netdata/issues/4116 netdata made the Naming a little nicer for VxVM nodes. 
What would be cool is having "online" paths. But that's VxVM not vxfs :)

**Comment by vlvkobal** [comment]
What additional metrics can be collected for the VxFS and in what way? Are there any files we can read, libraries we can use, or queries we can make? While it is possible to use the `vxstat` or other tools and parse their output, this method is the least desirable.

**Comment by ilyam8** [comment]
found this

https://www.veritas.com/support/en_US/article.100021327

the title looks related

**Comment by Pratik32** [comment]
@ilyam8  , Yes that will be useful. in-fact there is an extensive tuning guide for every VXFS release. 
@vlvkobal , VXFS does not store any perf data in any files. We generate it on the fly and dump it. like I mentioned earlier - 'vxfsstat' is one of those utility (not to be confused with 'vxstat' which is a VxVM thing.) 
Here is the manual page for vxfsstat - [man page](https://sort.veritas.com/public/documents/sf/5.1/aix/manpages/file_system/man/html/man1m/vxfsstat.1m.html). 
We can read those counters and make sense out of them and predict the performance of filesystem from different aspects.

**Comment by ElCoyote27** [comment]
It would also be nice if the vxfs tunables could be reported. In some environments, I've used things such as this:
```
# cat /etc/vx/tunefstab 
#
# 7.3+
system_default dalloc_enable=1
system_default buf_breakup_size=1048576
system_default discovered_direct_iosz=1048576
system_default max_direct_iosz=1048576
system_default max_diskq=1048576
system_default lazy_copyonwrite=1
system_default read_nstream=2
system_default write_nstream=1
system_default write_pref_io=65536
system_default write_unit_io=65536
system_default read_pref_io=65536
system_default read_unit_io=65536
system_default read_ahead=0
#
/dev/vx/dsk/local00dg/kvm0_lv read_nstream=2,write_nstream=1,write_pref_io=65536,read_pref_io=65536
/dev/vx/dsk/ssd01dg/kvm0_lv read_nstream=2,write_nstream=1,write_pref_io=65536,read_pref_io=65536
/dev/vx/dsk/ssd02dg/kvm0_lv read_nstream=2,write_nstream=1,write_pref_io=65536,read_pref_io=65536
/dev/vx/dsk/local03dg/kvm0_lv read_nstream=2,write_nstream=1,write_pref_io=65536,read_pref_io=65536

```

**Comment by Pratik32** [comment]
@ElCoyote27  Exactly, data produced by vxfsstat can leveraged to suggest smart tuning . whether it is related to I/O , I/O scheduling policies etc.

**Comment by vlvkobal** [comment]
What would be the CPU usage for running the `vxfsstat` utility every second and parsing its output? Isn't there any lower-level method for collecting the counters?

**Comment by vlvkobal** [comment]
As far as I can't see other methods of getting VXFS data except `vxfsstat`, I'm putting the request into the external collector area.

**Comment by ilyam8** [comment]
Could anyone share `vxfsstat` output?

**Comment by ElCoyote27** [comment]
here's an example (infoscale 7.4.1 on RHEL7):
`# vxfsstat  /shared/data0

09:14:34.110 Thu 11 Jul 2019 09:14:34 AM EDT -- absolute sample

Lookup, DNLC & Directory Cache Statistics
        0 maximum entries in dnlc
  4783125 total lookups             0.00% fast lookup
434920169 total dnlc lookup        98.90% dnlc hit rate
        0 total enter           430137056.00  hit per enter
        0 total dircache setup      0.00  calls per setup
  4789934 total directory scan      0.04% fast directory scan

inode cache statistics
  1241008 inodes current   1703434 peak              2886166 maximum
  6762658 lookups            35.93% hit rate
  2299658 inodes alloced    1058650 freed
    16477 sec recycle age [not limited by maximum]
      600 sec free age

09:14:34.115 Thu 11 Jul 2019 09:14:34 AM EDT -- absolute sample

Per file system Lookup, DNLC & Directory Cache Statistics
398525249 total dnlc lookup        98.90% dnlc hit rate
  4403958 total directory scan      0.04% fast directory scan

Per filesystem inode cache statistics
  6286813 lookups                  37.60% hit rate
  3061143 inodes current
`

**Comment by ElCoyote27** [comment]
And also:
```
# vxfsstat -v /shared/data0

09:16:26.661 Thu 11 Jul 2019 09:16:26 AM EDT -- absolute sample

vxi_alloc_emap                 4852    vxi_alloc_smap                  316
vxi_alloc_expand_retry          123    vxi_alloc_find_retry              0
vxi_alloc_findfail               17    vxi_alloc_sumsum               2782
vxi_alloc_findfix               120    vxi_alloc_mapflush                0
vxi_alloc_prev                   32    vxi_alloc_search               3546
vxi_alloc_sumclean                0    vxi_alloc_try                  3578
vxi_execpgin                      0    vxi_execpgout                     0
vxi_bawrite                    3802    vxi_bwrite                    89421
vxi_btwrite                      22    vxi_lwrite                   116337
vxi_bdwrite                   26924    vxi_bdwrite_loglow                8
vxi_bcache_curkbyte         1692288    vxi_bcache_maxkbyte         7553024
vxi_bc_chunksteal                 0    vxi_bc_hits                16457979
vxi_bc_lookups             17085879    vxi_bc_reuse                 626782
vxi_bc_subflush                 138    vxi_bc_waits                   8852
vxi_fspgin                        0    vxi_fspgout                       0
vxi_bmap                   17821586    vxi_bmap_cache             33790781
vxi_bmap_indirect                 2    vxi_bread                    529158
vxi_brelse                       36    vxi_brelse_loglow                 0
vxi_clonemap                    617    vxi_cutwrite                      0
vxi_eau_cleaned                   0    vxi_eau_expand                    3
vxi_eau_unexpand                  0    vxi_eau_write                     0
vxi_icache_allocedino       2299658    vxi_icache_freedino         1061450
vxi_icache_curino           1238208    vxi_iaccess                437144188
vxi_dirblk                  5419384    vxi_dirlook                 4783125
vxi_dirlook_dot                   0    vxi_dirlook_dotdot                0
vxi_dirlook_notfound           4244    vxi_fast_lookup                   0
vxi_dnlc_hit               430158866    vxi_dnlc_enter                    0
vxi_dnlc_miss               4783123    vxi_dnlc_neg_hit               6131
vxi_dnlc_neg_enter                0    vxi_dnlc_size                     0
vxi_flush_throttle               35    vxi_iflush_cut                    0
vxi_map_write                     0    vxi_getblk                        0
vxi_dirscan                 4788045    vxi_dirc_hit                      0
vxi_dirc_miss                     0    vxi_dirc_spchit                   0
vxi_dirc_spcmiss                  0    vxi_fast_dirscan               1889
vxi_icache_inuseino          116633    vxi_icache_maxino           2886166
vxi_icache_peakino          1703434    vxi_bcache_recycleage         21628
vxi_icache_recycleage         16590    vxi_ifree_timelag               600
vxi_iget                    6762658    vxi_iget_found              2429826
vxi_iget_loop               7914895    vxi_inofail                       0
vxi_iinactive               5195589    vxi_iinactive_front            1479
vxi_iinactive_slow                1    vxi_inopage                 4247694
vxi_ipage                         0    vxi_iupdat                    87137
vxi_iupdat_cluster          1238934    vxi_async_iupdat               1425
vxi_log                     1324920    vxi_log_blks                 927045
vxi_log_delayed             1324895    vxi_log_flush                  2359
vxi_log_idle                     12    vxi_log_write                  4065
vxi_lread                  16984506    vxi_maj_fault                971995
vxi_pgin                    5305144    vxi_pgpgin                 19842747
vxi_rapgpgin               18870743    vxi_rasectin               150965796
vxi_sectin                 158741608    vxi_physmem_mbyte            257350
vxi_virtmem_mbyte          105922578    vxi_qtrunc                      728
vxi_trunc                      1473    vxi_ra                            0
vxi_read_dio                 169227    vxi_read_rand               5928529
vxi_read_seq                      0    vxi_setattr_nochange           1382
vxi_sumupd                       22    vxi_randwrite_throttle            0
vxi_ntran                      4714    vxi_bufspace_delay                0
vxi_bufspace_tranflush            0    vxi_tranleft_asyncflush           0
vxi_tranleft_delay                0    vxi_tranleft_syncflush            0
vxi_tflush_cut                    0    vxi_tflush_inode              83382
vxi_tflush_map_async              0    vxi_tflush_map_clone              0
vxi_tflush_map_sync               1    vxi_tran_commit             1324920
vxi_tran_low                    512    vxi_tran_retry                    0
vxi_tran_space              1369648    vxi_tran_subfuncs           1364529
vxi_async_realloc                 0    vxi_async_shorten                 0
vxi_tranidflush                2185    vxi_tranidflush_flush          2197
vxi_tranidflush_none        1474659    vxi_tranlogflush            1334097
vxi_tranlogflush_flush           58    vxi_clone_create                  0
vxi_clone_remove                  0    vxi_clone_rename                  0
vxi_clone_convnodata              0    vxi_clone_cntl                    0
vxi_clone_stat                  816    vxi_clone_mkpfset                 0
vxi_clustblk_ino                946    vxi_clone_dispose                 0
vxi_superwrite                   38    vxi_write_asynccnt                0
vxi_write_synccnt                 0    vxi_write_dio                157561
vxi_write_donetran                0    vxi_write_logged                  0
vxi_write_logonly                 0    vxi_write_rand              7388687
vxi_write_seq               3510164    vxi_anonpgin                      0
vxi_anonpgout                     0    vxi_sectout                538429568
vxi_pagecluster                   0    vxi_pagestrategy                  0
vxi_pgout                  11527103    vxi_pgpgout                67303696
vxi_sync_delxwri                  0    vxi_sync_inode                    0
vxi_sync_page                     0    vxi_write_only                    0
vxi_write_throttle                0    vxi_read_to_map                   0
vxi_dirc_setup                    0    vxi_dirc_purge                    0
vxi_bmap_lookup            33787205    vxi_bmap_indir_lookup             0
vxi_bmap_alloc                 3576    vxi_bmap_enter                    0
vxi_bmap_cache_hit         28422319    vxi_searchau_expandnext         123
vxi_searchau_expandfree           0    vxi_fsflush_fsq                 281
vxi_iupdat_tran_log               0    vxi_iupdat_tran_async             0
vxi_lct_clone                     0    vxi_fsq_flush                  1001
vxi_fsq_flush_mlink           99611    vxi_fsq_flush_flush           86016
vxi_tflush_buffer              1926    vxi_tflush_map                58982
vxi_tflush_map_tryfail            0    vxi_tflush_map_logclone         616
vxi_tran_doneid            191493930    vxi_tran_logid                    0
vxi_dirtytran_flush               0    vxi_unlockmap_clone               1
vxi_write_cio                     0    vxi_write_cio_retry               0
vxi_slab_alloc_fail               0    vxi_getpages1_fail                0
vxi_getpages2_fail                0    vxi_getpages4_fail                0
vxi_getpages8_fail                0    vxi_getpages_pages          5059271
vxi_vmalloc                     820    vxi_vmalloc_fail                  0
vxi_vmalloc_pages            231216    vxi_shrink_request                0
vxi_bufalloc_fails                0    vxi_inoalloc_fails                0
vxi_tran_doneres                  0    vxi_tran_doneres_extra            0
vxi_tran_doneres_unused           0    vxi_tran_doneres_consumed         0
vxi_read_aio                      0    vxi_write_aio                     0
vxi_sync_aio                      0    vxi_statvfs_bfree                 0
vxi_cached_fdd                    0    vxi_codm_adv_nocache              0
vxi_codm_mrside                   0    vxi_cfdd_sync_big                 0
vxi_cfdd_async_big                0    vxi_fdd_preload                   0
vxi_cache_read_async              0    vxi_cache_read_sync               0
vxi_fdd_cache_read_succ           0    vxi_fdd_cache_read_fail           0
vxi_delicache                    17    vxi_delicache_reuse              17
vxi_delicache_inact               0    vxi_delicache_hardlmt             0
vxi_inofail_retrycnt              0    vxi_delicache_process             0
vxi_dentry_unused             21843    vxi_dentry_unhashed               0
vxi_isteal_delay                  0    vxi_fail_chunkclean               0
vxi_pdio_read                     0    vxi_pdio_write                    0
vxi_rcq_full                      0    vxi_unshare                       0
vxi_unshare_data_copy             0    vxi_unshare_lazy_cow              0
vxi_unshare_lazy_skip             0    vxi_unshare_lazy_abrt             0
vxi_rct_scan                     12    vxi_rct_blocks_free               0
vxi_comp_ioctl                    0    vxi_decomp_ioctl                  0
vxi_decomp_ioctlblk               0    vxi_decomp_readblk                0
vxi_decomp_modifyblk              0    vxi_comp_compblk                  0
vxi_comp_nocompblk                0    vxi_do_iestats                    0
vxi_set_iestats                   0    vxi_mapped_to_vmalloc             0
vxi_pg_shared                     0    vxi_pgin_shared                   0
vxi_rapgin_shared                 0    vxi_splice_read                   0
vxi_emap2_hit                304708    vxi_emap2_alloc               64239
vxi_emap2_free                    0    vxi_ssd_dio_sync_write            0
vxi_ssd_dio_async_write           0    vxi_ssd_dio_sync_read             0
vxi_ssd_dio_async_read            0    vxi_congested                     0
vxi_tranpre_bmapsplit             0    vxi_tranpre_fclalloc              0
vxi_tranpre_ldiradd               0    vxi_tranpre_expandau              0
vxi_tranpre_unshr_indir           0    vxi_tranpre_rcqfull               0
vxi_tranpre_bmapadjust            0    vxi_tranpre_deliprocess           0
vxi_pinned_total           5632671541    vxi_pinned_icache          2687854368
vxi_pinned_bcache          197008928    vxi_pinned_cbuf                   0
vxi_pinned_glmlock_entry          0    vxi_pinned_glmlock                0
vxi_pinned_rwsleeplock         2304    vxi_pinned_rwsleeplock_rec  198119120
vxi_pinned_map             13919688    vxi_pinned_sumsum           1929312
vxi_pinned_eausum          10438688    vxi_smap_audirtytran            313
vxi_smap_syncflush                0    vxi_fel_write_count               0
vxi_fel_flush_count               0


```

**Comment by ilyam8** [comment]
could you do

> time vxfsstat -v /shared/data0

**Comment by vlvkobal** [comment]
Is it possible to get VXFS on Linux free of charge? Does a "test" version exist?

**Comment by ElCoyote27** [comment]
You can download 'infoscale' trialware free of charge (I think there's a time limit but I am not sure). Only Supports RHEL, SuSe and Centos, though (kernel modules need to load)

**Comment by ElCoyote27** [comment]
time vxfsstat -v on that mnt point (/shared/data0) gave me this result:


real    0m0.044s
user    0m0.009s
sys     0m0.035s
[root@t440 ~]#
  07/11/2019 17:29:36 .: 0.41 1.05 1.23

**Comment by ilyam8** [comment]
ok, according [man page](https://sort.veritas.com/public/documents/sf/5.1/aix/manpages/file_system/man/html/man1m/vxfsstat.1m.html) `vxfsstat` thing cah show a lot of different statistics depends on provided option.


@ElCoyote27 you used `vxfsstat -v /shared/data0`. Was this just an example or `-v` provides most useful metrics?

**Comment by ElCoyote27** [comment]
@ilyam8 What I shared was just an example. I think @Pratik32 would be able to let you know what metrics should be combed by netdata (I'm just a user, not a VXFS developper)

**Comment by ilyam8** [comment]
@Pratik32 please ^^

**Comment by ilyam8** [comment]
@Pratik32 @ElCoyote27 

It seems it is not easy to setup a VXFS lab. Please provide me a guide.

What i did:
 - regisered on [their site](https://www.veritas.com/trial/en/us/veritas-infoscale-solutions) and downloaded `Veritas_InfoScale_7.4.1_CentOS.iso`
 - found [this install guide](https://www.veritas.com/bin/support/docRepoServlet?bookId=129695450-129695454-1&requestType=pdf)

I tried to follow insctruction and 
 - mounted iso file
 - ran the insaller

But it seems it is possible to install it only remotely from another machine and you need to setup a dns server. 

So it would to have a guide how to setup a lab, how many nodes i need, which product should i use (foundation, storage, etnerprise or availability), etc.

**Comment by ElCoyote27** [comment]
@ilyam8 
It doesn't have to be 'remote' it can be a local install.
e.g:
1) mount the ISO
2) run the installer with your local hostname as argument. e.g:
# ./installer $(uname -n)
3) follow the prompts. If you're installing a on single machine, you probably don't want 'Enterprise' or 'Availability', so select 'Foundation' or 'Storage'.

**Comment by ilyam8** [comment]
Ok, I did exactly that.

```
Logs are being written to /var/tmp/installer-201909241055rjQ while installer is
in progress

    Verifying systems: 100%

    Estimated time remaining: (mm:ss) 0:00                            8 of 8

    Checking system communication ..................................... Done
    Checking release compatibility .................................... Done
    Checking installed product ........................................ Done
    Checking platform version ......................................... Done
    Checking prerequisite patches and rpms ............................ Done
    Checking file system free space ................................... Done
    Checking configured component ..................................... Done
    Performing product prechecks ...................................... Done

The following patch for InfoScale product will be downloaded and installed:
	infoscale-rhel7.7_x86_64-Patch-7.4.1.1300

infoscale-rhel7.7_x86_64-Patch-7.4.1.1300 has already been downloaded.

System verification checks completed successfully

CPI ERROR V-9-0-0

0 No pkg object defined for pkg VRTSvxvm74 and padv RHEL7x8664

```

The error is

> CPI ERROR V-9-0-0
> 0 No pkg object defined for pkg VRTSvxvm74 and padv RHEL7x8664

Any ideas?

**Comment by ElCoyote27** [comment]
I'd say: try with 7.6. If you get the same error, try with RHEL7.6 or 7.7 (that could be a problem with the Centos bits used by the Infoscale stack)

**Comment by ilyam8** [comment]
Ok, i managed to install it. The version was the problem. I installed Centos 7.4 and all went smoothly.

```
The following rpms were installed on mylocalhost.localdomain:

	VRTSperl
	VRTSpython
	VRTSvlic
	VRTSspt
	VRTSveki
	VRTSvxvm
	VRTSaslapm
	VRTSvxfs
	VRTSsfmh
	VRTSsfcpi


Storage Foundation Startup completed successfully

The following processes were started on mylocalhost.localdomain:

	CollectorService
	veki
	vxdmp
	vxio
	vxspec
	vxconfigd
	vxvm-recover
	vxencryptd
	vxcloud
	xprtld
	vxfs
	vxportal
	fdd
	vxcafs
```

For some reason i dont have `vxfsstat`

```
[root@mylocalhost rhel7_x86_64]# vx
vxassist           vxcloudd-shadow    vxdisk             vxencryptd         vxiod              vxloader           vxprint            vxsd               vxtrace
vxautoanalysis     vxcmdlog           vxdiskadd          vxencryptd-shadow  vxkeyless          vxloggerd          vxreclaimlog       vxslaveutil        vxtranslog
vxautoconvert      vxconfigd          vxdiskadm          vxesd              vxkmipclient       vxmake             vxrecover          vxsnap             vxtune
vxautorollback     vxdco              vxdiskpr           vxgetdev           vxlicinst          vxmemstat          vxrelayout         vxsnptadm          vxvmconvert
vxcache            vxdctl             vxdmpadm           vxhotplug          vxlicinstupgrade   vxmend             vxrlink            vxstart_vvr        vxvol
vxcachepold        vxddladm           vxdmptune          vxibc              vxlicrep           vxnetd             vxrsync            vxstat             vxvoltune
vxcloud            vxdefault          vxedit             vxinfo             vxlictest          vxnotify           vxrvg              vxtask             vxvset
vxcloudd           vxdg               vxencrypt          vxinstall          vxlink             vxplex             vxscriptlog        vxtestpr           vxvvrstatd 
```

**Comment by ElCoyote27** [comment]
@ilyam8 
that's because you don't have /opt/VRTS/bin in your PATH:
`
# which vxfsstat
/opt/VRTS/bin/vxfsstat
`

The following file is what I usually create on a RHEL box to have easy access to those paths:
`
# cat /etc/profile.d/VRTSvcs.sh 
export PATH="${PATH}:/opt/VRTSvcs/bin:/opt/VRTS/bin"
`

**Comment by ElCoyote27** [comment]
Assuming you'll want to dedicate a spare disk to Infoscale, here's what you'd do:
1) initialize the disk (we assume /dev/sdc in the following examples)
```# vxdisksetup -ivf sdc```
2) create a disk group on that disk:
```# vxdg init tes01dg sdc```
3) verify that the DG shows up by doing this:
```# vxdisk list
# vxdg list
# vxprint -Ath
```
4) create a logical volume within your diskgroup:
```# vxassist -g test01dg make test01_lv 1G```
5) create a vxfs filesystem on top of that Logical Volume:
```# mkfs -t vxfs /dev/vx/dsk/test01dg/test01_lv```
6) mount the filesystem somewhere (or add it to /etc/fstab):
```# mount -t vxfs /dev/vx/dsk/test01dg/test01_lv /mnt```
7) type ```# df``` and verify you have a new 1G vxfs filesystem


Please ask

**Comment by cakrit** [comment]
Looks like we've left this one unplanned for a while.

**Comment by ilyam8** [comment]
Closing this feature request and moving it to [our community forum](https://community.netdata.cloud/) for further discussion (link will be posted soon).

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
