### ISSUE TITLE
expose system start time instead uptime

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#6252]
##### Feature idea summary

Currently, netdata expose system uptime via `System Uptime` and `netdata_system_uptime_seconds_average` metric.
There are 2 problems:
* This chart is not useful because it just show a straight line. A single text can represent it.
* For prometheus backend, it's better to expose system start time instead of uptime.
  *  `system start time` is constant unless restart system 
     * better compression -> lower storage requirement
     * stale value can present correct uptime by `now() - system_start_time_seconds` while `uptime` can't.
  * many other exproter such like `node exporter`, `java exproter`, etc. use start time instead of uptime.

##### Expected behavior

Show uptime by single text in UI.
Report system start time instead of system uptime.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
