### ISSUE TITLE
addgroup: gid '999' in use

### ISSUE THREAD

**Issue by D34DC3N73R** [netdata/netdata#6253]
I get the following error when trying to start a netdata container now.
```
Netdata entrypoint script starting
Adding group with ID 999 and name 'docker'
addgroup: gid '999' in use
```
I've changed /var/run/docker.sock:/var/run/docker.sock:ro to /var/run/docker.sock:/var/run/docker.sock:rw as outlined [here](https://github.com/netdata/netdata/tree/master/packaging/docker).

##### OS / Environment
Ubuntu 18.04
##### Netdata version (ouput of `netdata -V`)
netdata/netdata:latest
##### Steps To Reproduce
start netdata with docker group id

**Comment by paulkatsoulakis** [comment]
Hello @D34DC3N73R, thanks for reporting this!
Let me touch base with netdata image state and i 'll let you know

**Comment by paulkatsoulakis** [comment]
If that is okay i will reference #6251 and close this so that we have a single issue to conclude with the troubleshooting.  Thanks again for reporting this and we 'll catch up the resolution of the issue on #6251
