### ISSUE TITLE
Netdata variable granularity support in netdata daemon - with basic unit testing

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#6255]
##### Feature idea summary
Netdata variable granularity support in netdata daemon.
##### Expected behavior
Allow users to change data collection frequency of metrics without:
- deleting older chart data
- invalidating existing alarm data
- affecting streaming
- invalidating web server data queries of older data
- affecting backends

**Comment by cakrit** [comment]
We won't be ready to merge when we complete this, we'll need another issue with extensive functional tests.

**Comment by mfundul** [comment]
Moving on to extensive functional testing.
