### ISSUE TITLE
RFE: Minor change to the spec.in file in order to help with building rpms on RHEL

### ISSUE THREAD

**Issue by ElCoyote27** [netdata/netdata#6256]
Hi,

In order to easily build rpms of netdata on RHEL7.x, I have to use that patch (you cannot use dashes in an rpm version):

```
diff --git a/netdata.spec.in b/netdata.spec.in
index e201f4a..7f65295 100644
--- a/netdata.spec.in
+++ b/netdata.spec.in
@@ -79,13 +79,17 @@ Recommends: python2-psycopg2 \
 %global netdata_recommends %{nil}
 %endif
 
+%define realversion @PACKAGE_VERSION@
+%define bldversion %( echo "$(echo @PACKAGE_VERSION@|sed -e 's/^v1/1/' -e 's/-[a-z0-9]*//2' -e 's/-/\./')")
+%define curdate %( echo "$(date '+%Y%m%d')")
+
 Summary:       Real-time performance monitoring, done right
 Name:          netdata
-Version:       @PACKAGE_VERSION@
-Release:       1%{?dist}
+Version:       %{bldversion}
+Release:       %{curdate}.1%{?dist}
 License:       GPLv3+
 Group:         Applications/System
-Source0:       https://github.com/netdata/%{name}/releases/download/%{version}/%{name}-%{version}.tar.gz
+Source0:       https://github.com/netdata/%{name}/releases/download/%{realversion}/%{name}-%{realversion}.tar.gz
 URL:           http://my-netdata.io
 BuildRequires: pkgconfig
 BuildRequires: xz
@@ -128,7 +132,7 @@ so that you can get insights of what is happening now and what just
 happened, on your systems and applications.
 
 %prep
-%setup -q -n %{name}-%{version}
+%setup -q -n %{name}-%{realversion}
 
 %build
 autoreconf -i
```
Please consider change the `Version:       @PACKAGE_VERSION@` line.
Thank you,
Vincent

**Comment by ElCoyote27** [comment]
BTW, this gives me a nice easy way to build rpms that auto-update fine when the update is pushed to my local repos:

`$ ls -l */netdata*-1.15*
-rw-r--r--. 1 root root 3684234 May 25 00:33 SRPMS/netdata-1.15.0.15-20190525.1.el7.src.rpm
-rw-r--r--. 1 root root 3740184 Jun 10 15:14 SRPMS/netdata-1.15.0.84-20190610.1.el7.src.rpm
-rw-r--r--. 1 root root 2018056 May 25 00:33 x86_64/netdata-1.15.0.15-20190525.1.el7.x86_64.rpm
-rw-r--r--. 1 root root 2022840 Jun 10 15:14 x86_64/netdata-1.15.0.84-20190610.1.el7.x86_64.rpm
-rw-r--r--. 1 root root 1250780 May 25 00:33 x86_64/netdata-debuginfo-1.15.0.15-20190525.1.el7.x86_64.rpm
-rw-r--r--. 1 root root 1281364 Jun 10 15:14 x86_64/netdata-debuginfo-1.15.0.84-20190610.1.el7.x86_64.rpm
`

**Comment by ElCoyote27** [comment]
e.g:
```
$ rpm -qi netdata
Name        : netdata
Version     : 1.15.0.15
Release     : 20190525.1.el7
Architecture: x86_64
Install Date: Sat 25 May 2019 12:34:04 AM EDT
Group       : Applications/System
Size        : 7556994
License     : GPLv3+
Signature   : DSA/SHA1, Sat 25 May 2019 12:33:45 AM EDT, Key ID 2a04f563c825b4bb
Source RPM  : netdata-1.15.0.15-20190525.1.el7.src.rpm
Build Date  : Sat 25 May 2019 12:33:34 AM EDT
```

**Comment by ElCoyote27** [comment]
And:
```
# rpm -Fvh netdata*
Preparing...                          ################################# [100%]
Updating / installing...
   1:netdata-1.15.0.84-20190610.1.el7 ################################# [ 50%]
Cleaning up / removing...
   2:netdata-1.15.0.15-20190525.1.el7 ################################# [100%]

```

**Comment by paulkatsoulakis** [comment]
Hello @ElCoyote27 ! That is some pretty valuable info, love it, thanks!

I am actually working during this sprint on fine tuning our spec file and get it up to date with the latest stuff that going around with netdata. We are in the process of generating our own binary packages repositories.

I will resolve this issue and link it to #5969 as a resource. By all means do not hesitate to provide further info or guidance there. I will follow up with you once i get to the task, so that you know what we will be doing with the stuff you recommended us.

Thanks again for the support and we 'll be in touch again soon on the matter!

**Comment by ElCoyote27** [comment]
Hi Paul,
Glad to hear it's being worked on. Please don't hesitate to reach out if I can be of assistance.
Regards,
Vincent

**Comment by paulkatsoulakis** [comment]
will certainly do, cheers!
