### ISSUE TITLE
Creating a custom dashboard for netdata

### ISSUE THREAD

**Issue by makutamatey** [netdata/netdata#6257]
I have a master/slave netdata architecture which currently works well. But I want to create a custom dashboard to display all the servers on one screen/dashboard. I have disabled the databases of the slaves before connecting them to the master. My question is do I have to enable all the databases of the slaves before I can create a custom dashboard to display the dashboards of all the slaves on one screen? @cakrit . Thank you

**Comment by AlexandreLicinio** [comment]
If i understand well you @makutamatey, please have a look at [https://github.com/netdata/netdata/issues/5973#issuecomment-491716200](url) you know how to stream, i explain how to watch from a single html page multiple netdata instances (streaming/replication behaviour).

**Comment by ilyam8** [comment]
> My question is do I have to enable all the databases of the slaves before I can create a custom dashboard to display the dashboards of all the slaves on one screen?

No, you do not. You can request the slave data from the master.

See @AlexandreLicinio 	[comment](https://github.com/netdata/netdata/issues/5973#issuecomment-491716200)
