### ISSUE TITLE
How to hide Demo Netdata nodes?

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#6262]
Is there a way to hide the Demo netdata nodes in Netdata master as the users are confused looking at demo servers worldwide. Couldn't see a property for this perhaps I missed out somewhere in the registry settings.

**Comment by cakrit** [comment]
@jacekkolasa it should be easy to provide an option just for this, but consider that with the labels we'll add, we can provide an easy way to filter those servers out (i.e. we can label them with something like netdata-demo-server=true)

**Comment by gamefundas** [comment]
I believe a configuration option to disable demo servers would make a lot of sense. When are the labels feature being introduced. Also I am thinking that's for Netdata cloud, which I cant use due to limitations with external auth.

**Comment by wally007** [comment]
Is there any update to this ? 
I can not believe users are okay with spam in their monitoring dashboards ?!?! 
I can understand one-off showcase - or some sort of checkbox - but not persistent foreign servers. What benefit does it give this to anyone ?

I tried enabling/disabling registry (I'm not using registry), I'm using 1x Master netdata + 10 slaves streaming metrics to the master. All of the sudden some users (the ones that arent in restricted network) are reporting that they see demo sites. What gives ?

**Comment by wally007** [comment]
After disabling registry - rebooting - enabling/disabling again - I can see Demo nodes disappeared for all users (restricted as well as unrestricted networks)

Reason why i didnt see demo nodes in my dashboards was because I was in restricted network. Users however have proxy set up - hence access to internet - and they did see them.

Nevertheless, i think it should be up to server owner to configure what is shown in dashboards. I really fail to see use case for these demo sites other than grievance.

**Comment by gamefundas** [comment]
Of course the demo sites provide the ability to showcase the product dashboard features and is also a means to confirm netdata is setup successfully in my environment, but beyond that it is confusing once the users start using the dashboard. 

One of my user jumped in and asked "why are we bringing in and storing data for unknown global servers in our VPC?" Then there is a lot of explaining to do for this.

I strongly believe demo servers should be enabled/disabled by means of a configuration.

**Comment by ilyam8** [comment]
@dim08 @manos-saratsis take a look^^

**Comment by dim08** [comment]
Will follow and and come back with an answer.

**Comment by jacekkolasa** [comment]
I think this issue is not valid anymore with the new-navbars dashboard. Please, anyone, correct me if i'm wrong
