### ISSUE TITLE
How to remove/unregister a streaming node to prevent the health alarms from triggering

### ISSUE THREAD

**Issue by madhermit** [netdata/netdata#6266]
##### Question summary
Following this guide: https://docs.netdata.cloud/streaming/#monitoring-ephemeral-nodes
What should I do to a ephemeral (slave) node prior to terminating it to prevent the health alarms from triggering?

Thanks!

**Comment by cakrit** [comment]
What alarms do you get? I assume you have the master running the health checks and raising the alarms, correct?

**Comment by madhermit** [comment]
@cakrit Yes, I have `[health] enabled = no` for the slaves and `[health] enabled = yes` on master. 

The alarms that are triggered when terminating a slave server are as follows:
- `memcached_local.cache` last collected
- `web_log_nginx.response_codes` last collected
- `ipv4.tcphandshake` last collected
- `netfilter.conntrack_sockets` last collected
- `ipv4.udperrors` last collected

**Comment by cakrit** [comment]
"Last collected" alarms shouldn't be triggered when a slave is no longer streaming. 
Having seen the code for health, I can think of two ways to approach this:
- Hacky way is to ensure that all such alarms and templates have a specific string in the name (e.g. "last_collected" or use in the query "last_collected_secs"). Treat them differently and ensure that the slave is streaming, before raising an alarm.
- Better way is to explicitly add a flag to all such alarms, so that they are raised only if the slave is still streamin.g

**Comment by cakrit** [comment]
@ilyam8 @vlvkobal  @Ferroin and @thiagoftsm I'd like to have your input here as well.

**Comment by thiagoftsm** [comment]
I am already working with some Alarms issue at this moment, so I will simulate in my side what happened with @madhermit and I will fix the problem. I agree with you when you say "Better way is to explicitly add a flag to all such alarms, so that they are raised only if the slave is still streamin.g".

**Comment by ilyam8** [comment]
> "Last collected" alarms shouldn't be triggered when a slave is no longer streaming.

I think the slave should have flag `up/down`, and if the slave is in down state then netdata master should skip its database checking alarms.

**Comment by cakrit** [comment]
> I think the slave should have flag `up/down`, and if the slave is in down state then netdata master should skip its database checking alarms.

This makes me feel like an idiot. Of course this is all we need, we don't need to bother with specific health checks at all. Haven't looked at what we can use to make this determination, we'll need to check the rrdhost struct carefully, in case that logic already exists.

**Comment by thiagoftsm** [comment]
All right, when I finish the json I will work on this!

**Comment by cakrit** [comment]
It's actually already implemented, but not documented in the README, only in `stream.conf`. 
 
```
    # Shall we enable health monitoring for the hosts using this API key?
    # 3 possible values:
    #    yes     enable alarms
    #    no      do not enable alarms
    #    auto    enable alarms, only when the sending netdata is connected
    # You can also set it per host, below.
    # The default is taken from [health].enabled of netdata.conf
    health enabled by default = auto
```

The default for the master is supposed to be `auto`. @madhermit can you verify that if it's set to auto you don't have an issue? As @ktsaou told me, for this to work, the slave needs to exit gracefully (i.e. netdata needs to stop). If it's a hard failure, the master will keep the connection open until it times out. Maybe that's what is causing the alarms you see and not the configuration?

**Comment by madhermit** [comment]
@cakrit Confirmed that in my `stream.conf` on the master I have `health enabled by default = auto`.
I just tested this again by terminating the slave and received notices for the above mentioned 5 alarms.
They immediately went to `needs attention` (ignoring the delay my `every` setting in the `last_collected` alarm config should have produced). Then 120 seconds later (the value for the `every` setting) moved to `critical` state, which then stayed triggered indefinitely until the node falls off/expires.
Hope that helps!

**Comment by madhermit** [comment]
@cakrit so rereading your post, it sounds like the (obvious) solution to my initial inquiry would be to shutdown the slave before terminating it. That makes sense!

**Comment by cakrit** [comment]
I updated the documentation in #6281 so we don't have such issues in the future. Even we didn't know how exactly it works! :)
