### ISSUE TITLE
netdata/web: layout getting messed up on certain dimensions when resizing the window

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6269]
##### Bug report summary
<img width="1440" alt="Screenshot 2019-06-12 at 11 06 28" src="https://user-images.githubusercontent.com/34388743/59334034-4b0b6600-8d02-11e9-8f1a-67d35990f3de.png">
<img width="1299" alt="Screenshot 2019-06-12 at 11 07 16" src="https://user-images.githubusercontent.com/34388743/59334036-4b0b6600-8d02-11e9-86cb-c40dba076b0e.png">

##### OS / Environment
Any

##### Netdata version (ouput of `netdata -V`)
Latest

##### Component Name
netdata/web

##### Steps To Reproduce
Just try to resize browser window slowly from maximum screen size (13") to smaller window

##### Expected behavior
Smooth resizing

**Comment by mfundul** [comment]
![image](https://user-images.githubusercontent.com/44345837/59373601-aa916200-8d52-11e9-998c-2190dcd391c0.png)
same thing with 1271 pixels width in firefox.

**Comment by ivorjvr** [comment]
Possible fix for it to truncate the name. if you wrap the name in a `<div></div>`

`.someclass{
   overflow: hidden;
   text-overflow: ellipsis;
   white-space: nowrap;
   max-width: 290px;
}`

**Comment by cakrit** [comment]
Fixed in #6455
