### ISSUE TITLE
Two Netdata instances on one nginx

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#6273]
Hi guys, 

I currently have two Netdata instances (one on my raspbian pi, one on my fedora server), and I would like to have Nginx serve a single page where I can access both via the nodes feature.

Currently my condensed version (which doesn't work at all, got it from the Netdata guides) is:
https://pastebin.com/nEWmJwYn

My working single instance is:
https://pastebin.com/1eWWSEG0

I'm honestly not quite sure where I'm going wrong! Unsure if anyone can point me in the right direction?

**Comment by cakrit** [comment]
What URL do you use in the multiple server version? From should be `https://netdata.mydomain.com/netdata/backend-server1/` to access your pi. Even the trailing slash matters, based on the regex `/netdata/(?<behost>.*)/(?<ndpath>.*)`

**Comment by cakrit** [comment]
Oh, and the nodes view isn't related to this at all, we're just talking about the nginx config. You can access the nodes any way you like when signed in and you'll still see both on the nodes view.

**Comment by modem7** [comment]
Heya,

Right, so currently (for single instances) I use netdatapi.mydomain.com and netdatahda.mydomain.com

No trailing slashes which is where as you say I'm probably going wrong!

How does one set a baseurl (/netdata) in the config?

**Comment by cakrit** [comment]
You already set that up in https://pastebin.com/nEWmJwYn 
Essentially you have a location called /netdata instead of a location called /. The `netdata` part gets stripped off due to the way the path is parsed here...
```
location ~ /netdata/(?<behost>.*)/(?<ndpath>.*) 
```
and the request that reaches netdata here:
```
 proxy_pass http://backend-$behost/$ndpath$is_args$args;
```

**Comment by modem7** [comment]
Heya, 

Sorry for the delay in response! 

When I try to run this, I just get the "welcome to nginx" page - not quite sure what's going on. 

But thanks for clarifying the /netdata part! I wasn't aware!

**Comment by cakrit** [comment]
Can you paste your full config again here, so we can test it as well (of course replacing the IPs again)? There may be another detail we're not seeing.

**Comment by modem7** [comment]
The configs in the top post are still the live ones I'm using - but can certainly repost them if that helps!

Let me know!

**Comment by cakrit** [comment]
Nope, I tried them. They work perfectly with the following URLs (I removed SSL because I was lazy):
http://netdata.mydomain.com/netdata/server1/
http://netdata.mydomain.com/netdata/server2/

Any other URL will fail. 

I had to add some things to nginx.conf around that fragment though, otherwise the nginx service wouldn't start:
```
events {
    worker_connections  1024;
}

http {
 I put your config here
}
```

If that was it, then we can update the docs to show the full config.

**Comment by modem7** [comment]
@cakrit - thank you for explaining it to me fully, I'm obviously an absolute idiot!

OK, with your information in the previous post, I've managed to make a nice modification that doesn't require the /netdata/ part.

```
upstream backend-pi {
    server 192.168.0.250:19999;
    keepalive 64;
}
upstream backend-hda {
    server 192.168.0.254:19999;
    keepalive 64;
}

server {
    # the virtual host name of this subfolder should be exposed
    server_name netdata.mydomain.com;

    error_log /var/log/nginx/netdata.mydomain.com.error.log;
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location ~ /(?<behost>.*)/(?<ndpath>.*) {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://backend-$behost/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;
    }

    # make sure there is a trailing slash at the browser
    # or the URLs will be wrong
     location ~ /(?<behost>.*) {
         return 301 /$behost/;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/netdata.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/netdata.mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = netdata.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


listen 80;
    server_name netdata.mydomain.com;
    return 404; # managed by Certbot
	}
```

This allows me to just put in netdata.mydomain.com/pi and netdata.mydomain.com/hda and still retain the ability to view both servers without entering the basic http auth details twice, and it's seen seamlessly. 

Thank you so much once again, and apologies for being an absolute muppet who didn't catch the obvious!
