### ISSUE TITLE
No warning about losing private registry when signing into Netdata Cloud

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#6279]
##### Bug report summary

When someone's Netdata is connected to a private registry, they will want to know that by signing in to Netdata Cloud, they will use the `netdata.cloud` registry instead of their private registry. If they click the `Sign In` button on the top-right corner, they see this popup:

![image](https://user-images.githubusercontent.com/1153921/59467062-a5c8be80-8de3-11e9-887c-7cced8024c9a.png)

However, if they click on either of the Nodes<sup>Beta</sup> buttons, on either the top navigation or the dropdown on the left-hand side, they will not get this popup and will go directly to the Netdata Cloud sign-in.

We should minimize incidents where people don't know they are no longer using their private registry. Consistency in the popup behavior will also make documentation simpler.

Also—my first issue, so I welcome feedback on how to make these better.

##### OS / Environment

Any

##### Netdata version (ouput of `netdata -V`)

netdata v1.15.0-85-nightly

##### Component Name

web

##### Steps To Reproduce

- Visit the dashboard for an agent connected to a private registry
- Click the `Sign In` button to see expected behavior
- Then click any of the Nodes<sup>Beta</sup> buttons to get redirected to Netdata Cloud without the popup

##### Expected behavior

All links to Nodes view/Netdata Cloud should show the popup warning users of private registries that signing in to Netdata Cloud will "overwrite" their private registry.

**Comment by jacekkolasa** [comment]
fixed with new navbars
