### ISSUE TITLE
collector/freeipmi - option to remove the ID added to the label

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#6284]
##### Feature idea summary
Add an option to not append the sensor_number to the label if it is already unique.

##### Expected behavior

In file [freeipmi_plugin.c](https://github.com/netdata/netdata/blob/a61a01bb2444d697393c81c8eb92633210e2a226/collectors/freeipmi.plugin/freeipmi_plugin.c#L407-L422) the sensor number is always appended to the dimension.
While this ensure uniqueness, when sent to a backend (like influxdb) it shows as different fields.

I have multiple generations and brands of servers, and the sensor number often changes between them, while they report the same kind of element (thus, same label). 

ipmi-sensors reports the name as expected (eg, Inlet Temp)
Server1: `ID: in4  Label: Inlet Temp`
Server2: `ID: in5  Label: Inlet Temp`

But while used by process freeipmi.plugin, it's displayed as : 
Server1: `DIMENSION 'i4_n7_r2' 'Inlet Temp i4' absolute 1 1000`
Server2: `DIMENSION 'i5_n3_r2' 'Inlet Temp i5' absolute 1 1000`

So when I push them into the backend, for the temperature I got 2 fields:

- netdata.ipmi.temperature_c.Inlet_Temp_i4
- netdata.ipmi.temperature_c.Inlet_Temp_i5

What option / method should we add to disable this added ID if the label is already unique on the system ?

Same goes with fan speed, outlet temperature, etc...

**Comment by cakrit** [comment]
There's no option to do that right now, but it's a trivial change to add a new command line option and modify the printf in lines 407-422, so that the sensor number is not included in the string between the single quotes, if that CL option is provided. 
Question: Does the 'i4_n7_r2' in the example you provided matter, or is it only the second part that causes the issue?

**Comment by Saruspete** [comment]
Hello,
No the ID does not matter: it's an aggregate of the ID & types reported by freeipmi. It's purely hardware dependant and is not pushed in the backend. It's only used as an ID to generate the netdata charts.

The only thing that matters in my (most) case is the label, as it's the human readable field reported by the sensors (or changed by configuration).

However, it may be interesting to keep it when we have multiple fields that are reported with the same label. You don't want to have 2 identical "Temp" labels, without a differential.
That's why I propose the "uniqueness" clause : only append the ID if the label was already used. Charge to the administrator to fix freeipmi.conf to do the hardware research and put a more clear and unique label to this particular sensor ID (if he cares, else he can live with "Temp" and "Temp i3"
