### ISSUE TITLE
Netdata lateral menu hidden

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6287]
##### Bug report summary
When we are seeing Netdata software output with the browser, case we go to the end of the page pressing the key "end" we have two problems:

1 -  There is blank lines after the text "Released under GPL v3 or later. Netdata uses third party tools. ", that  is not the main problem, but it is something that could have reltion with the next problem that is the critical.
2 - The lateral menu disappear.

##### OS / Environment
Slackware Linux Current : Google Chrome  (75.0.3770.90 (Official Build) (64-bit) ) and firefox (60.7.0esr)

##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0-106-g53d5e366

##### Component Name
Web interface 

##### Steps To Reproduce
Press the key "end" to go to the bottom.

##### Expected behavior
Do not hide the lateral menu.

**Comment by ivorjvr** [comment]
@thiagoftsm Adding a height:100vh to the class .sidebar-body should solve the problem

**Comment by Ferroin** [comment]
I can only intermittently reproduce this here.  It only seems to happen on my end if I hit the End key while the page is scrolling back up to the top form hitting the Home key.  @ivorjvr's suggestion (adding `height: 100vh;` seems to fix it here too (tested by adding it manually using the Chrome dev tools).

**Comment by thiagoftsm** [comment]
Thank you very much for everybody, in special for @ivorjvr , I sent the fix for the PR #6294.

**Comment by ilyam8** [comment]
Not fixed until #6294 is merged

**Comment by thiagoftsm** [comment]
It was merged by Christopher, so I am closing it!

**Comment by cakrit** [comment]
I didn't merge it, I approved it.
