### ISSUE TITLE
Redirect cannot overwrite netdata.

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6288]
##### Bug report summary
When we access the following option inside Netdata:

Alarms > All

At the end we have the text "Check this configuration file for more information.", when the user clicks  in the link, the Netdata is completely over written by the action, I think the better solution would be to open a new tab.

##### OS / Environment
Slackware Linux Current : Google Chrome (75.0.3770.90 (Official Build) (64-bit) ) and firefox (60.7.0esr)

##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0-106-g53d5e366

##### Component Name
Netdata Web

##### Steps To Reproduce
Access "Alarms > All" go to the end of the tab and click on link "this configuration file"

##### Expected behavior
Open the link in another tab and keep Netdata open.

**Comment by ivorjvr** [comment]
Yes completely agree, it needs to open in a new tab

**Comment by thiagoftsm** [comment]
Hi @ivorjvr ,for both cases we have the html/js/css files in our project, please, can you change both files and do a PR  for us?

**Comment by cakrit** [comment]
This isn't for @ivorjvr to fix. Assigning to @VLegakis and @gmosx

**Comment by thiagoftsm** [comment]
Thank you very much for everybody, in special for @ivorjvr , I sent the fix for the PR #6294.

**Comment by ilyam8** [comment]
Not fixed since #6294 is not merged

**Comment by thiagoftsm** [comment]
The PR was merged by @cakrit , so I am closing it now! Thanks!

**Comment by ilyam8** [comment]
no, it is not :smile:
