### ISSUE TITLE
/dev/fd/63: line 113:  : command not found when trying to update 

### ISSUE THREAD

**Issue by gouthamravee** [netdata/netdata#6289]
##### Bug report summary
When trying to update netdata using bash <(curl -Ss https://my-netdata.io/kickstart.sh) I get the error in the title. 

##### OS / Environment
Debian 9 Linux 4.15.18-14 
Proxmox hypervisor

##### Netdata version (ouput of `netdata -V`)
v.1.14.0-rc0-20-nightly

##### Component Name
Netdata updater?

##### Steps To Reproduce
install netdata 
forget how you installed netdata (really important bit here)
update netdata using bash <(curl -Ss https://my-netdata.io/kickstart.sh)

##### Expected behavior
netdata should update

**Comment by paulkatsoulakis** [comment]
Hello @gouthamravee,
  Thanks for reaching out! I am sorry to hear you bumped into problems. I am afraid the input you provide is not enough. Would it be possible to graph the full output of the shell from the execution of kickstart so that we can tell exactly which part raised that error?

**Comment by andrezaycev** [comment]
Have the same issue

```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 --- Re-installing netdata... ---
[/var/log/netdata]# '' /etc/cron.daily/netdata-updater -f
/dev/fd/63: line 113: : command not found
 FAILED

 ABORTED  Failed to forcefully update netdata
```
for cron.daily command have next

```
/etc/cron.daily/netdata-updater
Tue Jun 18 14:24:48 MSK 2019 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
ee6f8969ff66f6d9c878bac2debadec55352e823eae3f12c0cf58da6e10410fe *./latest-version.txt
e3e67fbcdd19e42e57edf8fd9cee810ec2adb433872ada4772291b662fa0f6d8 *./netdata-latest.gz.run
c5f318223d5edc9b64a837e6146969af61d0664a0b9f032c59dc6863e36c381c *./netdata-latest.tar.gz
e3e67fbcdd19e42e57edf8fd9cee810ec2adb433872ada4772291b662fa0f6d8 *./netdata-v1.15.0-101-g3213a4a6.gz.run
c5f318223d5edc9b64a837e6146969af61d0664a0b9f032c59dc6863e36c381c *./netdata-v1.15.0-101-g3213a4a6.tar.gz
Tue Jun 18 14:24:49 MSK 2019 : INFO:  Newest version is already installed
```
but GUI and netdata -V still show me old version (netdata v1.14.0-rc0-20-nightly)

**Comment by andrezaycev** [comment]
Found solution:

My `/etc/netdata/.environment` file:

```
# Created by installer
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
CFLAGS="-O2"
NETDATA_PREFIX=""
NETDATA_CONFIGURE_OPTIONS=""
NETDATA_ADDED_TO_GROUPS=" docker adm proxy"
INSTALL_UID="0"
REINSTALL_COMMAND="./netdata-installer.sh --auto-update "
RELEASE_CHANNEL="nightly"
# This value is meant to be populated by autoupdater (if enabled)
NETDATA_TARBALL_CHECKSUM=""
```

I replaced `NETDATA_TARBALL_CHECKSUM` to 
```
NETDATA_TARBALL_CHECKSUM="new_installation"
```
and run `/etc/cron.daily/netdata-updater`

Result after:
```
:~# netdata -V
netdata v1.15.0-98-nightly
```

command `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` also working after `.environment` changes

**Comment by gouthamravee** [comment]
@paulkatsoulakis  Hey thanks for looking at this, haven't had time to pull a full log. I will today after work and try the solution from @andrezaycev if their solution works I'll close this. 

Thank you.

**Comment by molcese** [comment]
> Found solution:
> 
> My `/etc/netdata/.environment` file:
> 
> ```
> # Created by installer
> PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
> CFLAGS="-O2"
> NETDATA_PREFIX=""
> NETDATA_CONFIGURE_OPTIONS=""
> NETDATA_ADDED_TO_GROUPS=" docker adm proxy"
> INSTALL_UID="0"
> REINSTALL_COMMAND="./netdata-installer.sh --auto-update "
> RELEASE_CHANNEL="nightly"
> # This value is meant to be populated by autoupdater (if enabled)
> NETDATA_TARBALL_CHECKSUM=""
> ```
> 
> I replaced `NETDATA_TARBALL_CHECKSUM` to
> 
> ```
> NETDATA_TARBALL_CHECKSUM="new_installation"
> ```
> 
> and run `/etc/cron.daily/netdata-updater`
> 
> Result after:
> 
> ```
> :~# netdata -V
> netdata v1.15.0-98-nightly
> ```
> 
> command `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` also working after `.environment` changes

Perfect!!!
Thanks!!

**Comment by cakrit** [comment]
So we introduced a bug at some point that ended up with NETDATA_TARBALL_CHECKSUM having the possibility to be empty. We need to do something about this ASAP, so that at least in 1.16.0 we can treat an empty checksum the same as "new_installation".

**Comment by paulkatsoulakis** [comment]
Hello, it seems that this issue has been fixed already with:

```
commit 06ceaa2309bbc4261e295b800cf7331badebf6ca
Author: Paul Emm. Katsoulakis <34388743+paulkatsoulakis@users.noreply.github.com>
Date:   Fri May 31 18:08:42 2019 +0300

    netdata/packaging: always update on empty checksum (#6182)
```

And introduced to this version onwards: v1.15.0-42-nightly.

It seems that indeed at the moment for people with older versions the solution is to do the above workaround

**Comment by paulkatsoulakis** [comment]
I 'll see if i can understand how we ended up in this bogus situation with an empty checksum there.
If i can't find anything i will just resolve the issue as the provided workaround will cover us sufficiently

**Comment by paulkatsoulakis** [comment]
i am afraid i can't get a repro somehow.
I tried various paths using either versions around 1.14.0-rc0-20 or latest one.

I will resolve this for now, but by all means do let me know if i missed anything or if the problem persists in any way

**Comment by gouthamravee** [comment]
Hello, sorry about the late reply. I was able to update to the latest version. I realized I never used the one line install method, I had pulled the repo and built it that way. Anyways went through the same process and I've updated both instances of netdata I have on my network from 1.14 to 1.16
