### ISSUE TITLE
Plugin fail2ban failed with ascii error

### ISSUE THREAD

**Issue by v1ru535** [netdata/netdata#6290]
Hi all,
##### Question summary
I configured the fail2ban plugin, forced it into the "charts.d.conf" and when I restart netdata the plugin fail2ban failed with these error in the error.log on various servers:
```
python.d ERROR: fail2ban: local: check() unhandled exception: 'ascii' codec can't decode byte 0xe2 in position 2145: ordinal not in range(128)
python.d INFO: fail2ban: local: check() => [FAILED]
```
A few days before that worked

##### OS / Environment
Debian 9 , install fron dist

##### Component Name
netdata v1.12.1

##### Expected results
On many other servers, it works like a charm.

Thanks

**Comment by ilyam8** [comment]
Hi @v1ru535 	

> Debian 9 , install fron dist

That is the problem, `netdata v1.12.1` is ancient. The fix is to remove it and [install latest version](https://docs.netdata.cloud/packaging/installer/).

**Comment by v1ru535** [comment]
Hi @ilyam8 
Thanks a lot, with "netdata v1.15.0-95-nightly" it's now ok!
