### ISSUE TITLE
XMPP/Jabber notification support

### ISSUE THREAD

**Issue by DocMAX** [netdata/netdata#6292]
Please add XMPP/Jabber notification support, thank you.

**Comment by cakrit** [comment]
Can you please add a link to the XMPP/Jabber API?

**Comment by DocMAX** [comment]
Do you mean this? https://xmpp.org/software/libraries.html

**Comment by thiagoftsm** [comment]
Hi @DocMAX , I worked with Jabber fewer years after the project to be released, and it will be a pleasure to bring it for Netdata. The link that you gave us does not have C library, so I will put the suggestion of the C library (http://strophe.im/libstrophe/ here ) for when I work with it. In this exact moment I am working in other features of Netdata, but I will return for your request ASAP.

Best Regards!

**Comment by cakrit** [comment]
Wait, what we need for alarm notifications is either an HTTP endpoint, or an executable we can call for alarm-notify.sh. There's no point in implementing yet another XMPP client. So the question is if there's a widely available client that either offers an HTTP API we can call (i.e. a service people will be able to set up easily) or a way to post a message via a shell command. Anything more advanced goes well beyond what has been done for the scores of other notification integrations.

**Comment by thiagoftsm** [comment]
@DocMAX  considering what @cakrit said us, I saw that we have the possibility to use HTTP over XMPP ( https://xmpp.org/extensions/xep-0332.html ), but do you know the inverse?

@cakrit only to complement your previous information, XMPP is not much different of XML, and we do not have nothing developed with XML internally yet.

**Comment by DocMAX** [comment]
The notification system is catastropic! Hard to understand even with the doc. My command is "sendxmpp" to send messages. I replaced alarm-notify.sh with my own script. But how do i get the parameters/variables?

#!/usr/bin/env bash
echo "???parameters???" | /usr/bin/sendxmpp

**Comment by cakrit** [comment]
Sorry you didn't easily find what you were looking for. All you need to do is follow the instructions at https://docs.netdata.cloud/health/notifications/custom/

Of course we can also help you debug your `send_custom` function.

We'd like to understand what misled you into thinking you'd have to replace the script itself, so we can improve the docs

**Comment by DocMAX** [comment]
ok, i did it. if anyone interested:

```
SEND_CUSTOM="YES"
DEFAULT_RECIPIENT_CUSTOM="root"

custom_sender() {
    local msg="${host} ${status_message}: ${alarm} ${raised_for}"
    echo $msg | /usr/bin/sendxmpp ...parameters...
}

```

**Comment by virtadpt** [comment]
@cakrit "So the question is if there's a widely available client that either offers an HTTP API we can call..."
I wrote one a while ago for this purpose.  I'm working on using it to send alerts from my OpenWRT boxen (though my older one has a version of Netdata that doesn't seem to support custom alerting).

https://github.com/virtadpt/exocortex-halo/tree/master/exocortex_xmpp_bridge
