### ISSUE TITLE
netdata/installer/docker: Question regarding docker container name resolution config

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6293]
##### Question summary
Hello @ArjenR 
Following up our discussion [here](https://github.com/netdata/netdata/commit/7ee5dc37ae6bca9945db518b2b0cc7d69ce36ae0#r33952591), i am creating this issue to continue the discussion.
I 'll post my next comment below.

##### OS / Environment
Any

##### Component Name
netdata/installer/docker

**Comment by paulkatsoulakis** [comment]
Coming back to the last comment, here's a few more clarifications in case they help:

1. If you don't care about docker container name resolution on netdata dashboard, you can simply avoid adding PGID variable to docker container and you will not have this problem.  That way you don't modify what we provide as stock run script and we can easily support you in the future.

2. If you require docker containers name resolution to work, you need to follow the instructions [here](https://docs.netdata.cloud/packaging/docker/), section "Docker container names resolution" as i mentioned before.

3. If you know another alternative to docker container name resolution (or perhaps more industry standard) that do not require read/write access to docker socket, by all means do let us know on this issue so that we can attend and fix your issues asap.

I hope this helps, let me know your comments and we 'll be glad to help in the best possible way

**Comment by D34DC3N73R** [comment]
I guess I'm wondering why v1.15 didn't need rw access for container name resolution. Also, why that needed to be changed in v1.16. I'm also wondering if using something like docker dns name resolution would be a more secure way to resolve container names (although it would only be able to resolve container names on the same docker network).

**Comment by D34DC3N73R** [comment]
I'm also not sure how portainer does container name resolution, but their image doesn't need the docker group PGID, and doesn't need rw access to /var/run/docker.sock.

**Comment by paulkatsoulakis** [comment]
> I guess I'm wondering why v1.15 didn't need rw access for container name resolution. Also, why that needed to be changed in v1.16. I'm also wondering if using something like docker dns name resolution would be a more secure way to resolve container names (although it would only be able to resolve container names on the same docker network).

Hi @D34DC3N73R, It worked on v1.15.0? Interesting, in that case i may have been misguided because it didn't work for me. Could you provide me the exact steps you follow for running `netdata/netdata:v1.15.0` that gives you successful name resolution on container names?

**Comment by ArjenR** [comment]
Ok so to be clear. As far as I can tell rw access to the docker.sock is only required for the chmod of the docker.sock to the group id given using PGID. 
But this is not necessary. The docker.sock already has that ID for the group since this is why we need to create the group in the container and add the netdata user to it in the first place.... 

So I just comment out the lines 
```
if [ -n "${GRP}" ]; then
	echo "Adjusting ownership of mapped docker socket '${DOCKER_SOCKET}' to root:${GRP}"
	chown "root:${GRP}" "${DOCKER_SOCKET}"
```
And I have name resolution for the docker containers with the GID used by my host OS. This is all for OpenSUSE MicroOS. 

> and doesn't need rw access to /var/run/docker.sock.

Portainer does have rw access. And I guess it should, since it actually manages the containers etc.

But why not get the GID for docker.sock if it exists?
``` PGID=$(stat -c '%g' ${DOCKER_SOCKET) ```

**Comment by paulkatsoulakis** [comment]
The thing is that i see a completely different behaviour when the image is executed on mac and i am testing now on Ubuntu 1804 with latest docker that also behaves differently. It's weird.

> But why not get the GID for docker.sock if it exists?
> `PGID=$(stat -c '%g' ${DOCKER_SOCKET)`

Initially because we want to comply with what docker instructs [here](https://docs.docker.com/install/linux/linux-postinstall/) and also because of the complexity to run this command successfully across all OS distributions ...

I been doing my experiments on docker for Mac, which seems to give me totally different experience than an ubuntu1804 install with docker.  I am working on it and let you know.

**Comment by paulkatsoulakis** [comment]
@ArjenR and @D34DC3N73R could you share the output of `umask` from the hosts running the containers? 

Thanks!

**Comment by ArjenR** [comment]
> could you share the output of `umask` from the hosts running the containers?

@paulkatsoulakis sure it is 0022 for the user root which runs the dockerd.

**Comment by ArjenR** [comment]
> could you share the output of `umask` from the hosts running the containers?

@paulkatsoulakis sure it is 0022 for the user root which runs the dockerd.

**Comment by ArjenR** [comment]
> could you share the output of `umask` from the hosts running the containers?

@paulkatsoulakis sure it is 0022 for the user root which runs the dockerd.

**Comment by D34DC3N73R** [comment]
@paulkatsoulakis umask is 0002 for my user and 0022 for root on my host.

I typically run my own version of the netdata image that adds a GNU C library to run binaries linked against glibc. (this allows nvidia-docker2 to be compatible with the netdata image which allows GPU monitoring in container) d34dc3n73r/netdata-glibc if you want to check it out. When running netdata/netdata:v1.15.0 I wasn't able to resolve container names. However, when running  d34dc3n73r/netdata-glibc:v1.15.0 container names resolve fine. The only difference between images is this library.

**Comment by D34DC3N73R** [comment]
@ArjenR 
portainer still runs with ro access and allows container identification, restarting, recreating, logs, image deletion etc.
`- /var/run/docker.sock:/var/run/docker.sock:ro`

**Comment by ViViDboarder** [comment]
In other services, I've found `ro` access sufficient for reading and writing to the daemon. Despite
having `ro` access to the socket, one can still create new Docker containers and gain full access to the entire server. This is flagged in #5680.

Also, `cadvisor` manages to get Docker service names using `- /var/lib/docker:/varlib/docker:ro`. I haven't dug into how they do it, but that could be a safer mechanism.

**Comment by D34DC3N73R** [comment]
@paulkatsoulakis I figured out how to get container names from `netdata/netdata:v1.15.0`. If `- /usr/bin/docker:/usr/bin/docker:ro` is not mounted, netdata will resolve container names. If mounted, container names will not resolve. My full docker-compose is 
```
    netdata:
        container_name: netdata
        image: netdata/netdata:v1.15.0
        network_mode: bridge
        ports:
            - 19999:19999
        restart: unless-stopped
        environment:
            - PGID=999
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
```

cat /etc/os-release
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

uname -a
`Linux hostname 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

umask
`0002`

ls -la /var/run/docker.sock
`srw-rw---- 1 root docker 0 Jun 20 11:51 /var/run/docker.sock`

grep docker /etc/group | cut -d ':' -f 3
`999`

**Comment by paulkatsoulakis** [comment]
Hello @D34DC3N73R, yes!

I have already updated the documentation from days ago if you check [here](https://docs.netdata.cloud/packaging/docker/).
I am afraid i did not communicate it correctly (at least not on all issues) and it slipped through.

Using the docker binary is not cross-distribution compatible and is only left as an option for extreme cases that the service is not functioning for some reason.

**Comment by D34DC3N73R** [comment]
@paulkatsoulakis `- /path/to/actual/docker/on/the/host:/usr/bin/docker` is still present on the docker-compose example. I don't see any reference to the docker binary stating that it's only an option for extreme cases. It appears the last edit was 16 days ago, 7 days before this topic was created. In any case, I would appreciate any relevant updates regarding this topic. Will netdata continue to require rw access to docker.sock? Will container names be resolved using a different method (like docker socket proxy), or will the method return to  the way it was in 1.15.0?

**Comment by paulkatsoulakis** [comment]
> @paulkatsoulakis `- /path/to/actual/docker/on/the/host:/usr/bin/docker` is still present on the docker-compose example. I don't see any reference to the docker binary stating that it's only an option for extreme cases. It appears the last edit was 16 days ago, 7 days before this topic was created. In any case, I would appreciate any relevant updates regarding this topic. Will netdata continue to require rw access to docker.sock? Will container names be resolved using a different method (like docker socket proxy), or will the method return to the way it was in 1.15.0?

yikes! Sorry about that! That totally slipped through my eyes.
Docker binary is not needed and pushing a PR right now to remove that stall reference.

I 'll get back on the docker socket requirements.
I have some findings, but i have paused the research until i have a definite understanding across all distributions what is the situation.
I will be posting a patch though to avoid breaking docker run time, until we finalise the design on this.

**Comment by maisun** [comment]
> 1. docker container and you will not have this problem.  That way you don't modify what we provide as stock run script and we can easily support you in the future.

Hi I tried to follow the link and there is no "Docker" group in /etc/group on my QNAP device. I also tried to set user to root and admin  (QNAP default) without luck. Anything I'm missing? Really look forward to get name resolution to work

**Comment by ViViDboarder** [comment]
@maisun you should probably use a proxy to protect your Docker socket. 

Here's an example (slightly modified) config that I use on my QNAP devices.

```
---
version: '2'
services:

  netdata:
    image: netdata/netdata:latest
    ports:
      - 19999:19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - "DOCKER_HOST=docker_proxy:2375"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfirmed
    restart: always

  docker_proxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
    restart: always
```

**Comment by maisun** [comment]
> @maisun you should probably use a proxy to protect your Docker socket.
> 
> Here's an example (slightly modified) config that I use on my QNAP devices.
> 
> ```
> ---
> version: '2'
> services:
> 
>   netdata:
>     image: netdata/netdata:latest
>     ports:
>       - 19999:19999
>     volumes:
>       - /proc:/host/proc:ro
>       - /sys:/host/sys:ro
>     environment:
>       - "DOCKER_HOST=docker_proxy:2375"
>     cap_add:
>       - SYS_PTRACE
>     security_opt:
>       - apparmor:unconfirmed
>     restart: always
> 
>   docker_proxy:
>     image: tecnativa/docker-socket-proxy
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock:ro
>     environment:
>       CONTAINERS: 1
>     restart: always
> ```

Thanks, in the end I found out it's because I forgot to mount the docker.sock in my container, shame on me! Will try the proxy solution :-)

**Comment by D34DC3N73R** [comment]
using the proxy is definitely more secure, especially if your netdata install is accessible online.
