### ISSUE TITLE
netdata/packaging: Fine tune documentation regarding package dependencies per distribution

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#6300]
Link to wiki page: 
> https://docs.netdata.cloud/packaging/installer/#prepare-your-system

Wiki says

> install the packages for having a basic Netdata installation (system monitoring and many applications, without mysql / mariadb, postgres, named, hardware sensors and SNMP)

But at the same time

> CentOS / Red Hat Enterprise Linux
> yum install autoconf automake curl gcc git libmnl-devel libuuid-devel openssl-devel libuv-devel lz4-devel Judy-devel lm_sensors make MySQL-python nc pkgconfig python python-psycopg2 PyYAML zlib-devel

Following packages should be removed from the list:
 - `lm_sensors`
 - `MySQL-python`
 - `python`
 - `python-psycopg2`
 - `PyYAML`

**Comment by paulkatsoulakis** [comment]
Hi @ilyam8, so those packages are not needed by any module?

**Comment by ilyam8** [comment]
The point here that they are not needed for 

> basic install

As you may see they are not included in other lists.

**Comment by ilyam8** [comment]
I admit that `basic install` looks a little bit vague

> (system monitoring and many applications, without mysql / mariadb, postgres, named, hardware sensors and SNMP)

i think it should be only `system monitoring`.


maybe we should rename it to `minimal install`

**Comment by paulkatsoulakis** [comment]
The thing is that @cakrit has requested that we install all required module packages and i think that is why those packages are there

**Comment by ilyam8** [comment]
Anyway there is a bug, if we want to install

> all required module packages

then we need to add a lot packages to the lists.

___

That is how it is now

 - wiki ways `basic install`
 - `Debian`, `Fedora` and `openSUSE` lists include only basic install
 - `CentOS / Red Hat Enterprise Linux` list includes basic install + some other random packages (most of them are python packages)

My suggestion is to remove all unneeded for basic install packages from those lists.

If wee need `all required module packages` manual install instruction then we need to add it.

**Comment by cakrit** [comment]
We need to update it, but don't it in a rush. We need a table of all dependencies and what they enable. We'll then mark which ones should be in the basic installation and which in the full. It's not just the manual installation though that we need to consider. For the same dependencies, we should say which ones are in the docker image, which are in the static 64, which in the binary packages, which are installed by default with kickstart.sh and also the option to enable or disable the installation of the dependency, when that option is available. I'm sure that with a table like this, we'll see things that make no sense and that need to be fixed.

**Comment by cakrit** [comment]
To make myself a bit clearer, let's start the table with what we do now and then we say what we should be doing. We should also keep in mind the people who are already using a process and expect certain things to happen.

**Comment by ilyam8** [comment]
> We'll then mark which ones should be in the basic installation and which in the full.

I think we need:
 - minimal
 - basic
 - full

At least i see point in `minimal` and `full`. Not sure about `basic` tho.

**Comment by paulkatsoulakis** [comment]
We also have to clarify what "basic install" means, i don't think we have the same understanding about this. We have plenty of modules enabled by default, others are auto-detection and we said in the past we want all packages installed so that all capabilities are auto-enabled.

I 'll set up a table with the current status and we take it from there.

**Comment by ilyam8** [comment]
i think `install` word mainly refers to the amount of optional packages being installed. At least i understand it in that way.

**Comment by paulkatsoulakis** [comment]
Draft table here:
https://docs.google.com/spreadsheets/d/1_-rtbXD9meAbPBCFf6LRS33BKJ_kgzoWHYM7OcNJTPk/edit#gid=0

**Comment by vlvkobal** [comment]
The prometheus remote write backend has only two dependencies: protobuf and snappy. Are there any problems with these libraries? Why don't you want to include the prometheus remote write backend to the RPM and DEB packaging?

**Comment by ilyam8** [comment]
> We also have to clarify what "basic install" means, i don't think we have the same understanding about this. 

This^^ Until we havent done it it is hard to say if we need to include X or not.

**Comment by paulkatsoulakis** [comment]
Document updated on https://docs.google.com/spreadsheets/d/1_-rtbXD9meAbPBCFf6LRS33BKJ_kgzoWHYM7OcNJTPk/edit#gid=0

Please do let your comments on the document directly and we can wrap it up through slack if there are any comments.
I will be doing the final adjustments on the documentation where might be needed, as part of the wrap up work for the road map document on #6036

**Comment by cakrit** [comment]
- The xls doesn't mention packages (e.g. for the dbengine).
- An xls is fine for internal review, but we need to publish something on our docs.  A lot of columns there, so difficult to fit in a page using markdown, but we'll think of something.

**Comment by paulkatsoulakis** [comment]
I already have the packages in there, what do you mean?

**Comment by cakrit** [comment]
You're right, the rows are too long and I didn't see them out on the right.
Let's just see how we can format it to be able to publish it.

**Comment by paulkatsoulakis** [comment]
So we keep this story for next sprint to do so?
I would prefer to wrap all the documentation work on the other story, its relevant anyway

**Comment by paulkatsoulakis** [comment]
I have already finished populating this information on our documentation, it is combined with the changes for #6036 

The change can be reviewed here: https://github.com/paulkatsoulakis/netdata/blob/distribution-support-matrix-doc/packaging/DISTRIBUTIONS.md

I will resolve this for now and we will review all the content  when i issue the PR for #6036
