### ISSUE TITLE
Test of close and reopen from author.

### ISSUE THREAD

**Issue by cakrit75** [netdata/netdata#6302]
This is just a test, trying to duplicate a user's inability to reopen an issue s/he authored.

**Comment by cakrit75** [comment]
Indeed can't reopen, checking GitHub settings.

**Comment by cakrit** [comment]
It's a stupid "feature" of GitHub.

See https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github
and upvote https://github.com/isaacs/github/issues/583
