### ISSUE TITLE
Never able to sign in

### ISSUE THREAD

**Issue by VLegakis** [netdata/netdata#6306]
From an email to support@netdata.cloud

> I run a few netdata nodes and am unable to login - I am redirected to the authorisation screen, enter an e-mail address and receive an e-mail but I am never logged in.  I’ve tried with two different e-mail address and google auth but the same results.  All the nodes are running detain with a git install of netdata - fully updated.

**Comment by VLegakis** [comment]
Hello Bill,
could you please paste here any data found in your browser's console? Alternatively a screenshot would do also. Would you like to mention a bit more about your setup? Are you or your nodes behind any firewalls or anything similar?

**Comment by thiagoftsm** [comment]
Hi @VLegakis let me explain the whole situation by steps. I detected this problem while I was working with Netdata using the Mozilla Firefox 60.7.2esr on Slackware Linux current. In this browser every time that I try to login using it, I receive the following message:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]"

When we see the console output I am receiving 302,303 and 304 from google saying to the browser redirects,  but it looks like that the JSON is not working with this specific browser.

**Comment by nicolasparada** [comment]
I'm unable to replicate it with Firefox 60.7.2esr (64-bit) on Windows.

**Comment by nicolasparada** [comment]
`JSON.parse` is a JavaScript API so the error happens in the browser.
But I don't see JSON parsing involved in sign in endpoints...

**Comment by nicolasparada** [comment]
Oh, in firefox devtools `Response#json()` is logged as `JSON.parse` ('-' )

**Comment by thiagoftsm** [comment]
I will give an additional information that I saw now, I am able to login using my google account now, and this is happening after I login with it in the Google Chrome, but my github account still fails

**Comment by nicolasparada** [comment]
So, the error is on the automatic sign up, no the sign in.

**Comment by nicolasparada** [comment]
I was able to reproduce it by deleting my own account from the database so it goes to the auto sign up next time.
This didn't happen on Chrome.

**Comment by thiagoftsm** [comment]
I am having the same problem yet with github account and mozilla-firefox-60.7.2esr on Slackware current!

**Comment by nicolasparada** [comment]
Droping an update here.
I was able to replicate the `JSON.parse` error on sign-up. The problem was because it was not sending cookies and now it's solved ✅

But the issue persists still. Now, accordingly to @thiagoftsm, first time to sign in just redirects back asking to sign-in again. A second time redirects back to the agent, but you cannot see your username on the dropdown menu. I'm not able to replicate this issue.

**Comment by cakrit** [comment]
Perhaps @thiagoftsm needs to clear his cache?

**Comment by thiagoftsm** [comment]
I began to test with the firefox "private window" to avoid cache, but  after to read your question, I decided to clean all the firefox cache and try to access again, and the problem persists, so it does not look like cache.

**Comment by cakrit** [comment]
Ok, so get together in a call, share your screen and @nicolasparada is checking the logs server-side, you show the client-side logs etc.

**Comment by thiagoftsm** [comment]
Of course, when he is available we will do the call.

**Comment by thiagoftsm** [comment]
It is working now, with the exception that the name is missed, because the github did not few it in the sign up, I gave a suggestion for we avoid this behavior on our cloud channel!

**Comment by VLegakis** [comment]
Great! Thanks for all the hard work on this @nicolasparada and @thiagoftsm ! Closing this.

**Comment by thiagoftsm** [comment]
You are welcome @VLegakis , when you and the cloud team need something, please, let me know!
