### ISSUE TITLE
collectors/perf.plugin/perf_plugin.c:171: error: 'PERF_COUNT_HW_REF_CPU_CYCLES' undeclared here (not in a function)

### ISSUE THREAD

**Issue by 143230** [netdata/netdata#6321]
#### Summary
collectors/perf.plugin/perf_plugin.c:171: error: 'PERF_COUNT_HW_REF_CPU_CYCLES' undeclared here (not in a function)
daemon/global_statistics.c:59:6: warning: #warning NOT using atomic operations - using locks for global statistics
daemon/global_statistics.c:89:2: warning: #warning NOT using atomic operations - using locks for global statistics
make64[2]: *** [collectors/perf.plugin/perf_plugin.o] Error 1

met this error when install netdata

**Comment by vlvkobal** [comment]
What operating system do you use?

**Comment by 143230** [comment]
Linux version 3.10.0_3-0-0-10 (root@xxxxxxx) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) )

**Comment by vlvkobal** [comment]
Do you have the `/usr/include/linux/perf_event.h` file on your system? Does it miss the `PERF_COUNT_HW_REF_CPU_CYCLES` declaration?
