### ISSUE TITLE
Not able to Install NetData Manually

### ISSUE THREAD

**Issue by mukesh4567** [netdata/netdata#6322]
I have clone the netdata master Branch and trying to run the installer using sh file. 
After some scripts execution , I am getting below error.
Please help , I don't have internet connectivity on that machine, So is there another way to install netdata.

make[2]: Entering directory `/root/netdata/netdata-master'
  CC     collectors/apps.plugin/apps_plugin.o
In file included from collectors/apps.plugin/apps_plugin.c:9:
collectors/apps.plugin/../../libnetdata/libnetdata.h:83:23: error: uuid/uuid.h: No such file or directory
make[2]: *** [collectors/apps.plugin/apps_plugin.o] Error 1
make[2]: Leaving directory `/root/netdata/netdata-master'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/netdata/netdata-master'
make: *** [all] Error 2
 FAILED

**Comment by stelfrag** [comment]
This should help [Install Netdata on offline systems](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/offline)

**Comment by Ferroin** [comment]
@stelfrag Actually, that doesn’t really help much. Our offline installation support is currently _very_ broken. Fixing that is one of the goals of the ongoing work to overhaul the installer and updater code.

Currently, the only way to install Netdata offline is to follow [the manual build instructions found here](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/source).
