### ISSUE TITLE
Change memory pie chart?

### ISSUE THREAD

**Issue by ELECTROHAXZ** [netdata/netdata#6323]
Is it possible to make the memory pie chart at the top of the page not show the cached and buffers memory but only show the used memory? I know the RAM graph in the summary tab shows the breakdown but I would like to make the pie chart only show the used memory.

**Comment by ilyam8** [comment]
Hi @ELECTROHAXZ 	

The memory chart (not pie chart btw) at the top of System Overview section does not account cached memory. It is sum of `used` and `buffers`.

I agree that this is a little bit confusing, as a user i would expect `used` to be `used` and not `used` + `buffer`.

@vlvkobal 	@mfundul

**Comment by ELECTROHAXZ** [comment]
@ilyam8 Ah yes, I know it's not actually a pie chart, but in the HTML code it is referred to as a pie chart. Good to know that it doesn't show cached, but I'm still trying to make it only show used memory and not buffers. Do you know how to make it only show used?

**Comment by ilyam8** [comment]
> Do you know how to make it only show used?

It is an easy fix, but i am not aware of reason why it is done in that way. Lets wait  for @netdata/core 	

@Ferroin could make it clear too i am sure!

**Comment by ELECTROHAXZ** [comment]
No replies since then, anyone have any ideas?

**Comment by cakrit** [comment]
I found the following in `main.js` and modified it to say `data-dimensions="used"`, but I know that it's not the proper place to do it. Does it at least show what you want to get? I'll try to find where this `charts['system.ram']` should be defined instead...

```
    if (typeof charts['system.ram'] !== 'undefined') {
        head += '<div class="netdata-container" style="margin-right: 10px;" data-netdata="system.ram"'
            + ' data-dimensions="used|buffers|active|wired"' // active and wired are FreeBSD stats
            + ' data-append-options="percentage"'
            + ' data-chart-library="easypiechart"'
            + ' data-title="Used RAM"'
            + ' data-units="%"'
            + ' data-easypiechart-max-value="100"'
            + ' data-width="9%"'
            + ' data-after="-' + duration.toString() + '"'
            + ' data-points="' + duration.toString() + '"'
            + ' data-colors="' + NETDATA.colors[7] + '"'
            + ' role="application"></div>';
    }
```

**Comment by cakrit** [comment]
Found it. See https://docs.netdata.cloud/web/#customizing-the-standard-dashboards
So first try to see if you can get what you want with this parameter and then create a custom dashboard_info js so you can persist your change across netdata updates.
