### ISSUE TITLE
Centrally control which modules should be run

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#6327]
The netdata daemon already tracks the plugin and module of each chart.
So, what we miss now is configuration:

1. set a different history of the charts of a specific plugin or module
2. centrally control which modules should be run

_Originally posted by @ktsaou in https://github.com/netdata/netdata/issues/2692#issuecomment-441260206_

**Comment by cakrit** [comment]
It doesn't track jobs though. One module can have multiple jobs and we should track and configure those as well. In fact, they could be all we track, with the plugin and module being additional info for each job.
