### ISSUE TITLE
Cannot reinstall netdata

### ISSUE THREAD

**Issue by alsoGAMER** [netdata/netdata#6329]
##### Bug report summary
Cannot reinstall netdata

##### OS / Environment
Debian 9.9

##### Netdata version (ouput of `netdata -V`)
netdata v1.14.0-rc0-20-nightly

##### Component Name
Installer

##### Steps To Reproduce
Run bash <(curl -Ss https://my-netdata.io/kickstart.sh)

##### Output
 --- Re-installing netdata... --- 
[/root]# '' /etc/cron.daily/netdata-updater -f 
/dev/fd/63: line 113: : command not found
 FAILED   

 ABORTED  Failed to forcefully update netdata

**Comment by paulkatsoulakis** [comment]
Hello @alsoGAMER,
 Thanks for your report! I am sorry to hear that. It seems your issue is a duplicate of #6289. Kindly follow up this issue for the resolution of your problem, Thanks!
