### ISSUE TITLE
netdata bad -c option

### ISSUE THREAD

**Issue by manjotsc** [netdata/netdata#6332]
It runs fine, but I cannot stop it. I am running on freebsd

**Comment by manjotsc** [comment]
![Annotation 2019-06-22 193501](https://user-images.githubusercontent.com/51430971/59969808-db2c8500-9524-11e9-8e25-ffbb72c0b419.png)

**Comment by ilyam8** [comment]
Hi @manjotsc 	

Please see

https://github.com/netdata/netdata/issues/6228
https://github.com/netdata/netdata/issues/3469
https://github.com/netdata/netdata/pull/5982

**Comment by manjotsc** [comment]
Thanks @ilyam8 
https://github.com/netdata/netdata/issues/6228
 continue topic link above.
