### ISSUE TITLE
Persist Netdata-Cloud View Settings in Localstorage

### ISSUE THREAD

**Issue by mstaack** [netdata/netdata#6341]
##### Feature idea summary
Changing View Layout/Grouping settings in the new Nodes View.
Possible by using Localstorage.

##### Expected behavior
View Settings stay the same after page reload.

**Comment by cakrit** [comment]
cc @gpapamathND

**Comment by Ferroin** [comment]
Might I suggest looking into an abstraction library that can also use IndexdDB if it's present?  Local storage tends to be very limited in how much data it can store, and also has some issues related to serialization (more specifically, it can only store strings, while IndexdDB can store most simple JS types natively).  I've personally found [localForage](https://localforage.github.io/localForage/) to be good for stuff like this, it automatically picks the best backend to use and handles any serialization automatically as well.

**Comment by cakrit** [comment]
We will eventually be saving the view settings in the back-end of the new netdata.cloud. Local storage was investigated and shot down because it can't be shared with other users.
