### ISSUE TITLE
Tomcat collector break on invalid XML caused by single quotes in Memory Pool names (code solution inside)

### ISSUE THREAD

**Issue by Danamir** [netdata/netdata#6343]
##### Bug report summary
The Tomcat plugin breaks when collecting data from a Tomcat 8 server running with OpenJDK : The XML returned by the `/manager/status?XML=true` page contains single quotes attributes in the `<jvm>` tags, and the Memory Pool names contains single quotes (ie. `CodeHeap 'non-nmethods'`). Thus producing invalid XML, and provoking the error `(...) is not a vaild XML page. Please add "?XML=true" to tomcat status page` (and there's a minor typo on "vaild", just sayin').

Example: 
```xml
    <jvm>
        (...)
        <memorypool name='CodeHeap 'non-nmethods'' type='Non-heap memory' usageInit='2555904' usageCommitted='3670016' usageMax='7593984' usageUsed='1349376'/>
        <memorypool name='CodeHeap 'non-profiled nmethods'' type='Non-heap memory' usageInit='2555904' usageCommitted='24379392' usageMax='122032128' usageUsed='24303360'/>
        <memorypool name='CodeHeap 'profiled nmethods'' type='Non-heap memory' usageInit='2555904' usageCommitted='35848192' usageMax='122032128' usageUsed='33184384'/>
        <memorypool name='Compressed Class Space' type='Non-heap memory' usageInit='0' usageCommitted='7127040' usageMax='1073741824' usageUsed='6459400'/>
        (...)
    </jvm>
```

##### OS / Environment
Debian GNU/Linux 9 (stretch)
Apache Tomcat/8.5.14
OpenJDK 11.0.3+7-Debian-1bpo92

##### Netdata version (ouput of `netdata -V`)
v1.15.0-114-nightly

##### Component Name
python.d.plugin/tomcat.chart.py

##### Steps To Reproduce
Configure tomcat plugin with a Tomcat 8 server running with OpenJDK 11.

##### Expected behavior
The tomcat plugin should chart the data returned by the status page.

#### Tested solution
I added the following regular expression replace to the XML `raw_data` returned in `tomcat.chart.py` . It removes all redundant single quotes in the attributes values.

```python
        raw_data = self._get_raw_data()
        if raw_data:
            raw_data = re.sub(r"='([^']+)'([^']+)''", r"='\g<1>\g<2>'", raw_data)
```
Another possible solution would be to replace all the single quote attributes by double quote ones.

**Comment by ilyam8** [comment]
@Danamir are you willing to make a PR?

cc @Wing924

**Comment by Danamir** [comment]
Sure, why not.

It will be my first, so I'll try not to break anything.  😅

**Comment by Wing924** [comment]
Sorry for late response. It’s a bug for tomcat with java 9+ and has been fixed by newer tomcat version. 
https://bz.apache.org/bugzilla/show_bug.cgi?id=61603
I think rather than adding the dirty workaround, update tomcat is better.

**Comment by ilyam8** [comment]
what do you think @Danamir ?

Or we can have xml parser and xml single quote fix parser

```python
class XMLParser:
    @staticmethod
    def parse(data):
        try:
            return ET.fromstring(data)
        except ET.ParseError:
            return None
    
    
class XMLSingleQuoteFixParser(XMLParser):
    @staticmethod
    def parse(data):
        data = single_quote_regex.sub(r"='\g<1>\g<2>'", data)
        return XMLParser.parse(data)
```

and choose second if needed and log a warning, suggest user to upgrade or something

**Comment by Danamir** [comment]
Updating Tomcat would be the better solution, but sadly the latest stable version of tomcat8 packaged with Debian stretch is 8.5.14, and using the repos version is the recommended way to install it. So the bug could still affect a lot of people. 

Correcting the problem on the fly and outputting a warning seems to be a reasonable solution. But I'll let you be the judge.

**Comment by Wing924** [comment]
Options:
* add workaround to tomcat plugin
* update tomcat
* use java 8, not java 11

**Comment by Wing924** [comment]
> Correcting the problem on the fly and outputting a warning seems to be a reasonable solution.

It looks OK for me because some users can’t update tomcat nor downgrade java. It’s the last resort.

**Comment by ilyam8** [comment]
> but sadly the latest stable version of tomcat8 packaged with Debian stretch is 8.5.14

i see that [the problem](https://bz.apache.org/bugzilla/show_bug.cgi?id=61603) is 

> Fixed in 9.0.2, 8.5.24, 8.0.48, 7.0.83.


however i see no bug in 8.5.14 (deb9), i think it is somehow connected with tomcat+java version

> Correcting the problem on the fly and outputting a warning seems to be a reasonable solution. 

Looks ok to me, why not. Please do, if you have any question feel free to ask

**Comment by ilyam8** [comment]
> It will be my first, so I'll try not to break anything.  sweat_smile

not an easy one , huh ? :smile:

**Comment by Danamir** [comment]
> not an easy one , huh ? 😄

Clearly ! But it's instructive. 😛

I committed the fix with a warning when needed.
