### ISSUE TITLE
Uninstaller uses "-f" flag for groupdel, which is not always available

### ISSUE THREAD

**Issue by DanielFEvans** [netdata/netdata#6348]
### Bug report summary

On Linux, the Netdata uninstaller script calls `groupdel -f "${groupname}"`. However, the `-f` flag is not universally available:
```
$ groupdel -f netdata
groupdel: invalid option -- 'f'
Usage: groupdel [options] GROUP

Options:
  -h, --help                    display this help message and exit
  -R, --root CHROOT_DIR         directory to chroot into
```

As this step comes quite late in the uninstaller (and there's some prudent error checking/handling), the uninstallation still completes mostly successfully.

##### OS / Environment

Scientific Linux release 7.6 (Nitrogen)

##### Netdata version (output of `netdata -V`)

netdata v1.15.0-114-nightly

##### Component Name

Uninstaller

##### Steps To Reproduce

Follow uninstall instructions at:
https://github.com/netdata/netdata/blob/master/packaging/installer/UNINSTALL.md

##### Expected behavior

Uninstaller runs without errors.

**Comment by Ferroin** [comment]
This is indeed an issue, but I'd argue that we should instead not be removing groups and users we created in the first place.  It's got the potential to leave files behind without a defined mapping for the UID or GID, which is a security issue waiting to happen.
