### ISSUE TITLE
Custom API

### ISSUE THREAD

**Issue by fti-dpogra** [netdata/netdata#6349]
Hi, It is possible to create an API from netdata which has the following data,
['system1','system2','system3','system3']

Whenever i hit this API using 'http://my-ip:19999/system_json', i would like to get these data

Please suggest

**Comment by cakrit** [comment]
Not sure what you mean. Please review the available API calls first: https://docs.netdata.cloud/web/api/
You're probably intersted in the `/api/v1/data` call.

**Comment by fti-dpogra** [comment]
Thanks for your reply.

Using netdata API I already created charts over my webpage .

But now I want to create a API where only has this data ['abc', 'xyz','asd']. Using this I will create a dropdown

**Comment by ilyam8** [comment]
Hey @fti-dpogra. It is still not clear what are you asking about.

> ['system1','system2','system3','system3']
> ['abc', 'xyz','asd']

You want some API call that returns a list of some data. What kind of data do you need? Please give an example
