### ISSUE TITLE
Question for netdata's Monitoring alarm

### ISSUE THREAD

**Issue by zhangsimingshannonai** [netdata/netdata#6350]
Hi, I'm using Netdata and I have a "Disk usage" monitoring scenario.
I have  serveral server and each server have a configured netdata run on them.

What I want is to use one server or one management platform to do a centralized management.
Such as I want to set all my alarm disk usage from %50 to %60, or from one place I can change all my netata server's config.
In a word, I want to use one platform to manage all my netdata server. Like a zabbix server to manage all the zabbix client.  Does netdata support this feature? please give me some suggestion, thanks.

**Comment by Ferroin** [comment]
Netdata does not currently have any such functionality.  There may be plans for it for the Netdata Cloud, but I'm not sure (@cakrit would probably know).

As far as a solution now, I'd suggest looking into a regular orchestration tool like [Ansible](https://www.ansible.com/), [Chef](https://www.chef.io/), or [Puppet](https://puppet.com/).

**Comment by cakrit** [comment]
Indeed, this is something that cloud will be doing, but via the generic configuration management API that the agent will have anyway. @ilyam8 and @vlvkobal have already started the design on that, starting with the data collection jobs. 

The orchestration tools @Ferroin mentioned are the recommended solution ATM.

**Comment by zhangsimingshannonai** [comment]
> Netdata does not currently have any such functionality. There may be plans for it for the Netdata Cloud, but I'm not sure (@cakrit would probably know).
> 
> As far as a solution now, I'd suggest looking into a regular orchestration tool like [Ansible](https://www.ansible.com/), [Chef](https://www.chef.io/), or [Puppet](https://puppet.com/).

Thanks, I see.

**Comment by zhangsimingshannonai** [comment]
> Netdata does not currently have any such functionality. There may be plans for it for the Netdata Cloud, but I'm not sure (@cakrit would probably know).
> 
> As far as a solution now, I'd suggest looking into a regular orchestration tool like [Ansible](https://www.ansible.com/), [Chef](https://www.chef.io/), or [Puppet](https://puppet.com/).

Thanks, I see.

**Comment by zhangsimingshannonai** [comment]
> Indeed, this is something that cloud will be doing, but via the generic configuration management API that the agent will have anyway. @ilyam8 and @vlvkobal have already started the design on that, starting with the data collection jobs.
> 
> The orchestration tools @Ferroin mentioned are the recommended solution ATM.

Thanks, I hope this designment to go faster~

**Comment by cakrit** [comment]
The research/design is in progress in #6317. Closing this one, so people can follow progress there.

**Comment by ilyam8** [comment]
i would note that `centralized management platform` is not the same as `configuration manager`. 

> Like a zabbix server to manage all the zabbix client.

I think we need to look into it, what is `zabbix client` and what is `manage zabbix client`.

**Comment by cakrit** [comment]
netdata cloud will be able to push configs to the agents, but it can't do it without until the config manager is implemented.
