### ISSUE TITLE
Simple way to save and log alerts

### ISSUE THREAD

**Issue by katsil** [netdata/netdata#6352]
Hello. I have simple question: is there any way to save alerts and log them? I mean e.g. alerta.io have simple and useful interface to log&save alerts, see history and etc., but is there any **other** services working with Netdata which can do the same like alerta?

This is gonna be very cool if they`ll be **self-hosted**

##### Question summary
Self hosted service for log alerts?

##### Component Name
netdata alerts https://docs.netdata.cloud/health/notifications/

Thanks!

**Comment by cakrit** [comment]
I believe that if you go through the list of integrations we have and just look at their web sites, you'll find the most common ones. After all, the reason netdata is integrated with them is that people asked for it, which means they use it! netdata of course also logs alerts and you can see the log from the UI, but it's not as advanced as others. 

For some reason, I haven't seen anyone asking for notifications sent to Nagios, using it's ability for [passive checks](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/passivechecks.html). It should be really easy to add from the netdata side, if you find it useful.

**Comment by katsil** [comment]
> I believe that if you go through the list of integrations we have and just look at their web sites, you'll find the most common ones. After all, the reason netdata is integrated with them is that people asked for it, which means they use it! netdata of course also logs alerts and you can see the log from the UI, but it's not as advanced as others.
> 
> For some reason, I haven't seen anyone asking for notifications sent to Nagios, using it's ability for [passive checks](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/passivechecks.html). It should be really easy to add from the netdata side, if you find it useful.

im not using nagios in my cluster, but im using netdata+graphite+grafana. but in this case i dont i can log alerts. 
okay thanks anyway i`ll try and find best solution in intergration list. thanks
