### ISSUE TITLE
mysql slave status for channels

### ISSUE THREAD

**Issue by vpapas** [netdata/netdata#6353]
Hello,

Is it possible to check slave status per channel in case there are multiple replication channels in MySQL? 
Maybe to add an option in mysql.conf which will indicate that MySQL runs with multiple replication channels and also the ability to add the name of each channel that netdata will check.
The python script will have to execute the following command:

`show slave status for channel 'channel_name'`

With this option netdata can monitor slave status in  Mysql instances with multisource replications.

**Comment by ilyam8** [comment]
Hi @vpapas 	

> show slave status for channel 'channel_name'

could you show the ouput? is it differ from  `show slave status`?

**Comment by vpapas** [comment]
Hi @ilyam8 

The output is the same (regarding the fields) but in case you don't specify the channel the output contains multiple rows (depending on the number of channels):

> mysql> show slave status\G
*************************** 1. row ***************************
               Slave_IO_State:
                  Master_Host: xxxxxxxxxxx
                  Master_User: user
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File:
          Read_Master_Log_Pos: 4
               Relay_Log_File: xxxxx@002dindb@002d01.000001
                Relay_Log_Pos: 4
        Relay_Master_Log_File:
             Slave_IO_Running: No
            Slave_SQL_Running: No
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 0
              Relay_Log_Space: 154
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 0
                  Master_UUID:
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State:
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set: 64485c6f-334c-11e8-b1d8-0050569d2e3c:1-19159184
                Auto_Position: 1
         Replicate_Rewrite_DB:
                 Channel_Name: channel01
           Master_TLS_Version:
*************************** 2. row ***************************
               Slave_IO_State:
                  Master_Host: xxxxxxxxxxx
                  Master_User: user
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File:
          Read_Master_Log_Pos: 4
               Relay_Log_File: xxxx@002dindb@002d11.000001
                Relay_Log_Pos: 4
        Relay_Master_Log_File:
             Slave_IO_Running: No
            Slave_SQL_Running: No
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 0
              Relay_Log_Space: 154
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 0
                  Master_UUID:
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State:
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set: 64485c6f-334c-11e8-b1d8-0050569d2e3c:1-19159184
                Auto_Position: 1
         Replicate_Rewrite_DB:
                 Channel_Name: channel02
           Master_TLS_Version:
2 rows in set (0.00 sec)

But if you specify the channel the output contains only one row.

So the metrics for the slave (Slave Behind Seconds & Slave Status) are for the first channel (i guess) and not for all channels. 

It would be more helpful if the module could check the slave status of each channel.

Thanks.
