### ISSUE TITLE
Health monitoring in centralized netdata infrastructure

### ISSUE THREAD

**Issue by secato** [netdata/netdata#6354]
I'm running a centralized netdata infrastructure (a master with several slaves) and it seems that the slaves health monitoring only follows the config of the master.

For instance, I'm trying to set up a different health.d/swap.conf in one of my slaves, but it keeps following the master's config.

**Comment by cakrit** [comment]
Which configs are taken into account when health checks are running depend on where you are actually running the health checks. So if you have health disabled on your slaves and enabled on your master, then it's your master's configs that are used. If you want to keep these checks running only on the master, you can work on its config and use the `hosts` directive to have e.g. different limits for different hosts.

**Comment by secato** [comment]
I didn't touch any health config on both master / slave, they are running on default values so I think the health check is enabled on both? The only thing that I've done so far was set up a health.d/swap.conf in the slave.

These are my slave configs:
**netdata.conf**
![image](https://user-images.githubusercontent.com/5840942/60444707-19e0d000-9bf4-11e9-9d76-cb2c06332b72.png)

**stream.conf**
![image](https://user-images.githubusercontent.com/5840942/60444748-2cf3a000-9bf4-11e9-8e07-ac416c6f006e.png)
![image](https://user-images.githubusercontent.com/5840942/60444763-341aae00-9bf4-11e9-9825-13e65ac07766.png)

**Comment by cakrit** [comment]
The netdata.conf on your slaves indicates you're running health checks on each slave. So the configs you do on each slave will trigger alarms there. Not sure if you've configured each slave to send notifications, but you will definitely see them in the log trying to call alarm-notify.sh every time an alarm is triggered, based on the custom config you put in each slave's `/etc/netdata/health.d` directory.

The stream.conf sections you sent have no effect on the slave. They do affect how the master works, but only if you modify stream.conf on the master netdata. The default setting is indeed auto, which means that the master will also be doing health checks on behalf of the slaves. So with this setup, you'd be getting duplicate alarms, one from a slave and another from the master. 

I suggest you set the slave netdata's `[health] -> enabled` to `no` in each slave's `netdata.conf`, so you don't worry about those health setting any more. Modify your `health.d` settings only on the master, so you also have a single source of alarm notifications (i.e. you don't need to modify `health_alarm_notify.conf` on each slave). IF you want different threshholds for each slave, then you can use the `host` line on your custom alarms.

**Comment by secato** [comment]
Thank you @cakrit for the clarification. I followed your recommendations and it's working fine now.
