### ISSUE TITLE
Configuring/tweaking update rate of graphs

### ISSUE THREAD

**Issue by arialth** [netdata/netdata#6355]
##### Question summary
I have noticed that, when selecting long timespans (specifically, I am trying to get 24 hours of data on a graph), the rate at which the graph updates drops dramatically. Additionally, I don't see any documented history length for system.processes and system.load, but I've observed that neither of them show the same length or the full length when setting data-after:-84600 and data-after:0. 
The longer the timeframe, the longer it seems to take to update. I go from 5 seconds per refresh at 600 seconds of history to 30-45 at 24 hours. The load on the system does not spike during this time and the actual graph refreshes seem to occur in the sub-10ms range. It's just the timespan BETWEEN refreshes that goes up.
##### OS / Environment
Official docker image for netdata (alpine linux) running on a VPS. 
VPS CPU: 3.8ghz
VPS RAM: 2GB
VPS OS: Centos7
Browser accessing netdata: Firefox
Manual settings on custom dashboard:
```
        NETDATA.setOption("stop_updates_when_focus_is_lost", false);
        NETDATA.setOption("destroy_on_hide", true);
        NETDATA.setOption("show_help", false);
        NETDATA.setOption("idle_between_loops", 1);
        NETDATA.setOption("idle_lost_focus", 1);
```

##### Component Name
Dygraphs on custom dashboard
##### Expected results
Ideally, there would be a configuration item to specify the timespan between which a graph will refresh. I've looked through the documentation, but I haven't been able to find anything of the sort. If I can't get the graphs to refresh every second with such a wide frame of time, that's fine, I'd just like to know if this is intended or not. Feedback on why graphs set to the same frame of time do not match would be nice as well.

**Comment by cakrit** [comment]
Well, think about what kind of refresh you could possibly be getting for such a long time range. Essentially, each point corresponds to X minutes worth of data, averaging all the updates you have received within that time. So if the chart was to update, all you'd see would be the last point to the right changing it's value, as it gets more data, until the required time to finalize its value (X minutes) passes. I don't think it's an unreasonable implementation, but we're always open to suggestions for improvements of course.

**Comment by arialth** [comment]
@cakrit 

That... actually makes a lot of sense when you explain it that way. I think it's a lot more clear in my head what's going on now. Thank you!
