### ISSUE TITLE
[QUESTION] Show Docker Container without ID

### ISSUE THREAD

**Issue by matze19999** [netdata/netdata#6358]
Is there a way to monitor Docker Container with the name and without the ID? Because on every restart of the container they get a new ID and I have to set up an new alarm everytime.... 

![image](https://user-images.githubusercontent.com/13684520/60339808-1954f900-99aa-11e9-9b57-9403427adbf7.png)

**Comment by ilyam8** [comment]
Hi @matze19999 	
Is this some specififc to that container alarm? If no `template` will do.

https://docs.netdata.cloud/health/#entities-in-the-health-files

> templates, which define rules that should be applied to all charts having a specific context. You can use this feature to apply alarms to all disks, all network interfaces, all mysql databases, all nginx web servers, etc.

**Comment by matze19999** [comment]
Thanks, I didn't see this!
