### ISSUE TITLE
Alerts for "swap full" are not necessarily a problem

### ISSUE THREAD

**Issue by candlerb** [netdata/netdata#6362]
(I wasn't sure whether to put this as bug report or feature request, so I'm putting it here for discussion)

##### Question summary

Netdata is generating alerts at swap 90% full (warning) and 98% full (critical), but these don't necessarily indicate any sort of problem, and it may be that no action needs to be taken - so I think these are spurious.

##### OS / Environment

Ubuntu 18.04, netdata 1.9.0-711-g8f957be5_rolling

(I know, hasn't been updated for a while, but the relevant component doesn't appear to have changed)

##### Component Name

`used_swap` in [health.d/swap.conf](https://github.com/netdata/netdata/blob/master/health/health.d/swap.conf#L32)

##### Expected results

The machines in question have 8GB RAM and 1GB swap (*).  They have a number of lxd containers, some of which are pretty idle.

The problem is that after a while I am receiving swap full alerts like this, firstly warnings:

```

nuc2 needs attention
--
system.swap
Chart

used swap = 90%
the percentage of swap memory used
Alarm

swap
Family

WARNING
Severity

Wed Jun 26 11:36:56 BST 2019
Time
```

Then critical:

```
nuc2 is critical
--
system.swap
Chart

used swap = 98%
the percentage of swap memory used
Alarm

swap
Family

Escalated to CRITICAL
Severity

Fri Jun 28 23:59:03 BST 2019 
(was warning for 2 days and 12 hours)
Time
```

On the one hand, what these alerts are saying is true: the swap space is almost entirely used.

```
root@nuc2:~# free
              total        used        free      shared  buff/cache   available
Mem:        8055376     5259136      811256      415152     1984984     2044592
Swap:        976892      976560         332
```

But on the other hand: this does not represent any sort of problem, and there's nothing I should be doing about it.  The system still has 2GB of *available* RAM.  Another system has even more available RAM:

```
root@nuc1:~# free
              total        used        free      shared  buff/cache   available
Mem:        8055376     3654908     1820644      716796     2579824     3393224
Swap:        976892      962144       14748
```

I believe what has happened is that 1GB of inactive pages have been migrated into swap by the kernel in the background, to free up real RAM for more active data (even useful as disk buffer cache)

It's possible to clear these alerts by turning off swap and then turning it back on again, but this pointlessly migrates idle pages back into RAM.  And eventually they migrate back into swap.

I think that if an alert is to be generated in this situation, it should be when the *available* RAM falls below a certain percentage of (total RAM plus swap).  However there is already a RAM alert on used / (used + cache + free) which is quite similar, although it doesn't take into account swap.

For now I think I will disable the swap alerts, but in their current form, I'm not sure they have much value.

-----

(*) BTW: I intentionally make swap partitions small.  If a system ends up actively using a large amount of swap, it ends up performing like treacle, usually so badly that it needs rebooting anyway.  Better to let it run out of RAM while it's still able to be administered

**Comment by cakrit** [comment]
So the very description of the chart is wrong then: "Swap space is used when the amount of physical memory (RAM) is full."? 
We'd need to implement #4154 in order to take into account free RAM before raising an alarm for swap. However, if this is something common for the kernel to do, then what's the point of having swap in a different chart? @Ferroin as always, your insights would be invaluable here...

**Comment by mfundul** [comment]
Not only do different kernel configurations affect swap behaviour, but different Operating Systems will have completely different kernels and subsequently different swap behaviour. In the future, we will also need to support Windows which famously aggressively fills-up the pagefile immediately after boot.

**Comment by Ferroin** [comment]
Linux doesn't do any kind of preemptive swapping, either in or out.  I'm fairly certain that the same is true of BSD.

Given that LXC is in-use, memory cgroups are probably being used, which can easily lead to situations like this (if a memory cgroup gets near it's physical RAM usage limit, it will start swapping, even if there is plenty of free RAM left in the system as a whole.  So, in this case, the situation does make sense (and that system probably does need more swap).

-----

There's a second argument, at least on Linux, in favor of #4154 and making the swap alarm depend on RAM: Linux keeps copies of swapped-out pages in swap even after they get swapped back in, at least until the last reference to them in RAM is dropped.  The reason for this is a simple performance optimization (if the page needs swapped out again and has not changed, it doesn't need to be written out to swap if there's still a copy in swap already), but it means that swap space usage doesn't tend to shrink on most Linux systems.

**Comment by mfundul** [comment]
Even in linux there is some tuning that can be done and lead to unpredictable results such as `watermark_scale_factor` or `watermark_boost_factor` (more information [here](https://www.kernel.org/doc/Documentation/sysctl/vm.txt).

**Comment by candlerb** [comment]
@Ferroin:

> Linux doesn't do any kind of preemptive swapping, either in or out.

Then there's something subtle I don't understand then, and/or what I've [read elsewhere](https://unix.stackexchange.com/questions/2658/why-use-swap-when-there-is-more-than-enough-free-space-in-ram) may be wrong.

The SwapFaq says this about the [swappiness](https://help.ubuntu.com/community/SwapFaq#What_is_swappiness_and_how_do_I_change_it.3F) parameter:

> "The swappiness parameter controls the tendency of the kernel to move processes out of physical memory and onto the swap disk.
> ...
> swappiness=100 tells the kernel to aggressively swap processes out of physical memory and move them to swap cache"

If the kernel is moving pages into swap *before* memory pressure forces it to do so, then isn't that pre-emptive swapping?

> memory cgroups are probably being used

I've checked with `lxc config show <id> --expanded` on all containers, and none has a memory limit.

A direct search in the cgroup filesystem also seems to show all memory limits unconstrained:

```
root@nuc1:~# find /sys/fs/cgroup -name 'memory.kmem.limit_in_bytes' | xargs cat 2>/dev/null | uniq -c
    734 9223372036854771712
root@nuc1:~#
```

**Comment by Ferroin** [comment]
> If the kernel is moving pages into swap before memory pressure forces it to do so, then isn't that pre-emptive swapping?

'Predictive' is probably a better way to say what I was trying to say.  In short, Linux doesn't try to predict when the system will enter a state of high memory pressure and preemptively swap pages out before that happens (and, similarly, does not swap in pages until they are actually needed by a running process).  Swapping only gets triggered when memory allocation happens, and only if that allocation would put the system above some specific amount of memory pressure (note that swapping in pages functionally triggers memory allocation).  The `swappines` parameter controls that threshold proportionate to the total memory in the system through a complicated and generally poorly understood formula (and, in general, it's a bad idea to play with it as it really doesn't behave as most people expect it to).

> I've checked with lxc config show <id> --expanded on all containers, and none has a memory limit.
>
> A direct search in the cgroup filesystem also seems to show all memory limits unconstrained:

Odd, you shouldn't be hitting swap at all then unless you're using non-default kernel parameters for memory management (or you actually were overcomitted at some point).

**Comment by stelfrag** [comment]
As I am reviewing this, we have an issue of swap (threshold and full alert), which is in fact valid. 

Unless we have something in place as described in #4154 this isolated metric isn't getting a view
on the complete system picture (i.e. there is RAM left and will be used, system won't fail) 

Unless we have another option / suggestion on this issue (which would be in fact more tweaks on the system for this specific setup) I will close this

**Comment by stelfrag** [comment]
Closing this one
