### ISSUE TITLE
Akumuli backend for netdata

### ISSUE THREAD

**Issue by Lazin** [netdata/netdata#6363]
Hi everyone,
I'm thinking about adding new backend that will allow sending metrics to the Akumuli TSDB (https://github.com/akumuli/Akumuli). It's possible to do this using OpenTSDB protocol but native Akumuli protocol is way more compact and efficient.
If this is not against the project's goals I'll start working on PR.

**Comment by cakrit** [comment]
Definitely not against the project's goals! Thanks @Lazin, @vlvkobal will help you out, if you have questions.

**Comment by Lazin** [comment]
Thanks, good to know that!
