### ISSUE TITLE
Netdata Docker container registry configuration

### ISSUE THREAD

**Issue by timorkal** [netdata/netdata#6365]
Hello,
I have 100 machines to run netdata docker container.
I know that to configure my own registry I need to change the /etc/netdata/netdata.conf file.
But I can't find anywhere in the docs how can I configure my own registry during a docker container run.
Is there some command line/environment variable that I can run my container with, to get this configured?

**Comment by cakrit** [comment]
I believe that mounting a file with the configuration you need, will do the trick. See https://github.com/netdata/netdata/issues/5782#issuecomment-479572521 for the suggestion. We didn't close that issue/discussion, but that option seems to be the only available one right now.

**Comment by timorkal** [comment]
Thank you, this helped.

**Comment by cakrit** [comment]
Good to know! :)
