### ISSUE TITLE
Custom dashboard on focus updates

### ISSUE THREAD

**Issue by tinyhammers** [netdata/netdata#6368]
Hello humans...

I've put together a really simple custom dashboard, which is working fine, but I wondered if there is a way of setting refresh to always, just like you can on the default ND dashboard?

I've got it on another screen, so every time I click somewhere else, it pauses.
 Any ideas?

Thanks, beauts.

**Comment by cakrit** [comment]
The default dashboard also pauses when it's not in focus. On the UI configuration "Performance" tab, there is an Onf Focus/Always setting that controls that behavior. I looked in the code for what that does, I think that you all you need to do is set `NETDATA.options.current.stop_updates_when_focus_is_lost = false`. 
See https://github.com/netdata/netdata/blob/master/web/gui/demosites2.html#L75
Not sure if we have these options properly documented, so can you do a PR if you also couldn't find them?

**Comment by tinyhammers** [comment]
Oh @cakrit, that's exactly it!
It's working perfectly now. 
Thanks, man.
I vote for you to be King Of The Universe.
