### ISSUE TITLE
fping host limit?

### ISSUE THREAD

**Issue by tinyhammers** [netdata/netdata#6376]
Greeting and well met, my dudes....

Is there a limit to the amount of hosts I can add to the `fping.conf` file?
I'm grinding through adding all my hosts to `/etc/hosts` and `fping.conf` as per the instructions (150 of them so far 😢), but only some of them are showing on my dashboard.

I've ping'd and fping'd a host that is in both of the above files, but not showing on the dashboard, and it works fine.

I've not had a lot of sleep, so potentially being a total fool here, but I'm very confused.
Am I missing something?

Plz to halp?
(Sorry I keep asking so many questions)

**Comment by ilyam8** [comment]
I see no limits, fping plugins is a simple bash script

https://github.com/netdata/netdata/blob/c56e086ba341041611c084e7a38d68ef678d6d6f/collectors/fping.plugin/fping.plugin.in#L193-L197

So you can run it by hand and see if it works, maybe 150+ is to much for fping,

> fping -N -l -Q 1 <list of hosts>

i did some tests:
 - fping can handle 150 hosts
 - fping cant handle 300 hosts

**Comment by tinyhammers** [comment]
Thanks for taking the time to test it @ilyam8 🤗. Good to know it does have a limit.
Some of my hosts are having `Temporary failure in name resolution`, so I'm wondering if thats it.
I mean, they have a hostname and an IP in the hosts file, so it can't be that hard to resolve. Maybe it's something to do with `resolv.conf`?

Computers are stupid. If I've learnt anything from working with them, it's that I want to live a log cabin in the woods.

**Comment by ilyam8** [comment]
> Good to know it does have a limit.

you can spawn several fping plugins btw
