### ISSUE TITLE
Issues reported by cppcheck

### ISSUE THREAD

**Issue by ac000** [netdata/netdata#6378]
##### Bug report summary

Running the cppcheck.sh script under the current commit c56e086ba341 ("Easily disable alarms, by persisting the silencers configuration (#6360)) produces the following *issues*

[/home/andrew/programming/netdata/collectors/cgroups.plugin/cgroup-network.c:233]: (warning) Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?

[/home/andrew/programming/netdata/tests/profile/benchmark-line-parsing.c:648]: (warning) Unnecessary comparison of static strings.

[/home/andrew/programming/netdata/web/server/web_client.c:214]: (portability) Non reentrant function 'getpwuid' called. For threadsafe applications it is recommended to use the reentrant replacement function 'getpwuid_r'.
[/home/andrew/programming/netdata/web/server/web_client.c:222]: (portability) Non reentrant function 'getpwnam' called. For threadsafe applications it is recommended to use the reentrant replacement function 'getpwnam_r'.
[/home/andrew/programming/netdata/web/server/web_client.c:245]: (portability) Non reentrant function 'getgrgid' called. For threadsafe applications it is recommended to use the reentrant replacement function 'getgrgid_r'.
[/home/andrew/programming/netdata/web/server/web_client.c:253]: (portability) Non reentrant function 'getgrnam' called. For threadsafe applications it is recommended to use the reentrant replacement function 'getgrnam_r'.
160/160 files checked 100% done

[/home/andrew/programming/netdata/tests/profile/benchmark-line-parsing.c:536] -> [/home/andrew/programming/netdata/tests/profile/benchmark-line-parsing.c:506]: (warning) Null pointer dereference: base
[*]: (information) Unmatched suppression: nullPointerRedundantCheck

##### OS / Environment

Fedora 30 (x86-64)

##### Netdata version (ouput of `netdata -V`)

v1.15.0-136-gc56e086b

##### Component Name

General

##### Steps To Reproduce

./cppcheck.sh

##### Expected behavior

Generally no problems reported

**Comment by ac000** [comment]
So the last warning (Null pointer dereference) seems to be a false positive [0] with this telling trac ticket[1].

[0]: https://sourceforge.net/p/cppcheck/discussion/general/thread/8561473a/?limit=25
[1]: https://trac.cppcheck.net/ticket/7146

**Comment by thiagoftsm** [comment]
Hi @ac000, firstly thanks by your feedback!

I will answer you about the web_server(web/server/web_client.c), because I am one of the responsible people by this code. As cppcheck.sh reported, and it is also written in the manual of each function, they are not thread safe and we have comments in each function that express this, but case you analyse the file, you will see that the functions that are not thread safe will not be called when the Netdata is working in multi thread, because the static variable inside the functions will already be initialized, the unique time that they are called without initialization is inside the file daemon/main.c when the Netdata has only the main threaded started, so for this specific scenario that we have, it is not a problem to call these functions.
Case there is any doubt about what I write, please, let me know!

Best Regards!

**Comment by ac000** [comment]
@thiagoftsm What you write makes total sense. I didn't get around to actually looking into those ones yet so you saved me some time! Thanks!

Cheers,
Andrew

**Comment by thiagoftsm** [comment]
Hi @ac000,

You are welcome! Well, now you already know the person you can ask any doubt about the web server code, so be free to ask me, it will be a pleasure to help you!

Cheers,
Thiago

**Comment by ac000** [comment]
@thiagoftsm Brilliant!

**Comment by ac000** [comment]
So [tests/profile/benchmark-line-parsing.c:648]: (warning) Unnecessary comparison of static strings, comes from

    (void)strcmp("1", "2");

in main()

That is amongst a group of three function calls preceded by the comment

    // cache functions

Now the best I can surmise is that the intention here is to try and populate the level 1/2 caches with the code for these functions.

But then test1() which uses strcmp() is called twice anyway with the timing result of just the second one used, so the *dummy* strcmp() call would seem superfluous.

I would say the same is true for the call to strtoull()

    (void)strtoull("123", NULL, 0);

as that is also used in test1().

I actually ran this benchmark with and without the calls to all three functions, i.e

    // cache functions
    (void)simple_hash2("hello world");
    (void)strcmp("1", "2");
    (void)strtoull("123", NULL, 0);

With the above functions being called

test1() average = 7801604
test2() average = 1333162

Without those three function calls

test1() average = 7779905
test2() average = 1321438

Those are the averages of three runs. test1() uses strcmp() & strtoull() and test2() uses simple_hash2(), so in that run, *not* calling the three functions initially was actually quicker.

Subsequent runs of each show similar numbers with each edging the other out, however the difference is in the noise.

So I'd say to just remove those three function calls from main() altogether.

I also have a patch for the first cppcheck warning.

Cheers,
Andrew

**Comment by ac000** [comment]
I've opened a pull request for this issue and the first one (Assignment of function parameter has no effect outside the function).

As I mentioned in the pull request (https://github.com/netdata/netdata/pull/6386) this second issue may be controversial. We'll see...

Cheers,
Andrew

**Comment by amoss** [comment]
This was merged months ago - closing to clean up. Please reopen and post comments if there is any more to do.
