### ISSUE TITLE
statsd: order metrics by name and not by type

### ISSUE THREAD

**Issue by FedericoCeratto** [netdata/netdata#6385]
Statsd metrics shown on the dashboard can be ordered by name in a meaningful way as they are sorted alphabetically.
Examples:
- "foo.bar.response_time.udp" appears next "foo.bar.response_time.tcp"
- All the metrics related to "project X" appear together as they start with "myorg.projectx."

Currently Netdata divides the metrics in 3 groups by type: counters, gauges, timers which is less practical.

**Comment by cakrit** [comment]
Hi @FedericoCeratto, can you please specify the API call response you're referring to?

**Comment by FedericoCeratto** [comment]
@cakrit I'm talking about how the StatsD metrics are listed on the UI

**Comment by vlvkobal** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
