### ISSUE TITLE
Running behind nginx: File does not exist, or is not accessible

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6393]
I am having similar issue.
I get error message `File does not exist, or is not accessible: /usr/share/netdata/web/netdata/`

_Originally posted by @Avik1993 in https://github.com/netdata/netdata/issues/778#issuecomment-508372149_

**Comment by cakrit** [comment]
Please check the permissions on `/usr/share/netdata/web/netdata/` and let us know what you see. Those files should be readable. I expect that you can't access the UI directly either.  
How and when did you install netdata?

**Comment by Avik1993** [comment]
I had installed it a week before, and its at version `v1.15.0-135-nightly`.
I have files under `/usr/share/netdata/web/`. 
I dont any `netdata` directory under `web`

**Comment by ilyam8** [comment]
> I am having similar issue

Since the issue is the same i guess the solution is the same too.

> proxy_pass http://netdata;

> proxy_pass http://netdata/$ndpath$is_args$args;

**Comment by Avik1993** [comment]
Hi @ilyam8 
Yes I have implemented the same configurations in Nginx.
The only difference is, I dont have any `netdata` folder under `/usr/share/netdata/web/`.
It directly have all web files under the `web` folder.
Should all files be moved to a new `netdata` folder under `/usr/share/netdata/web/`?

**Comment by ilyam8** [comment]
> Should all files be moved to a new netdata folder under /usr/share/netdata/web/?

I think no.

> Yes I have implemented the same configurations in Nginx.


Your [config](https://github.com/netdata/netdata/issues/6393#issuecomment-508431370) is not the same, have you changed it?

**Comment by cakrit** [comment]
> But why does it goes onto to refer to /usr/share/netdata/web/netdata instead of just /usr/share/netdata/web

The nginx config is the issue and specifically the proxy_pass. Use [this example](https://docs.netdata.cloud/docs/running-behind-nginx/#as-a-subfolder-to-an-existing-virtual-host)

**Comment by Avik1993** [comment]
Thank you @cakrit @ilyam8 
I was able to resolve it using config pointed out by you.
Although, on loading it up, a pop is displayed `Cannot load required JS library: https://[DOMAIN]/netdata/lib/perfect-scrollbar-0.6.15.min.js`
Also, I cannot see my streaming nodes anymore when accessing through nginx.

But when i access directly using port, it doesnt create any pop and i can see my streaming nodes too.

Do i need to make any change to streaming config if I have to use netdata through proxy?

**Comment by cakrit** [comment]
Nope, it's still a wrong URL. The path should NOT have `/netdata` in it when it reaches the agent.
Please put your new config here.

**Comment by Avik1993** [comment]
sure.

```
upstream netdata {
    # the Netdata server
    server 127.0.0.1:19999;
    keepalive 64;
}

       location = /netdata {
                return 301 /netdata/;
        }

        location ~ /netdata/(?<ndpath>.*) {
                proxy_redirect off;
                proxy_set_header Host $host;

                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #proxy_pass http://netdata;
                proxy_pass_request_headers on;
                proxy_http_version 1.1;
                #proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "keep-alive";
                proxy_store off;
                proxy_pass http://netdata/$ndpath$is_args$args;

                gzip on;
                gzip_proxied any;
                gzip_types *;
        }
`

**Comment by cakrit** [comment]
Nope, this fragment works perfectly on my nginx. Perhaps there is a problem with other things you have in this `server` section.

I just did this:
```
server {
    listen 80;
    # the virtual host name of this subfolder should be exposed
    server_name netdata.domain.tld;

       location = /netdata {
                return 301 /netdata/;
        }

        location ~ /netdata/(?<ndpath>.*) {
                proxy_redirect off;
                proxy_set_header Host $host;

                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #proxy_pass http://netdata;
                proxy_pass_request_headers on;
                proxy_http_version 1.1;
                #proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "keep-alive";
                proxy_store off;
                proxy_pass http://netdata/$ndpath$is_args$args;

                gzip on;
                gzip_proxied any;
                gzip_types *;
        }
}

```

**Comment by Avik1993** [comment]
The only difference between your config and mine is that I am serving it over HTTPS and not HTTP.

**Comment by cakrit** [comment]
get http://127.0.0.1:19999/netdata.conf find `web files directory = YOURPATH` in global, and see what's in that path. You should see a lib/perfect-scrollbar-0.6.15.min.js right under that directory. Also check the permissions there. The directory and all subdirectories/files should be readable by the user netdata runs as (default user is netdata).

I was wrong about the URL by the way, you sent what you see on the browser, which is fine, it will always show that `/netdata` there. So there's something else going on...

**Comment by Avik1993** [comment]
I do `lib/perfect-scrollbar-0.6.15.min.js` file under directory returned by `web files directory`.
Let me figure out what's wrong, but this is regarding just the pop up.

Regarding streaming nodes, do i need to update my registry URL in order to see streaming nodes when accessing netdata through nginx reverse proxy? As I am able to see all nodes when accessing directory.

**Comment by cakrit** [comment]
The nodes streamed to your master will magically appear on the top-left menu, regardless of any other settings. You just need to properly configure streaming, based on the info in the docs. If you don't see them, check first the slave error.log and then the master's.
