### ISSUE TITLE
Improve plugin exit/restart logic

### ISSUE THREAD

**Issue by emmrk** [netdata/netdata#6402]
##### Bug report summary
Plugin exit/restart logic could be improved.

For instance, there is an unnecessary `sleep` when (not) restarting a disabled worker thread. Enabled/disabled checks are not unified and are strewn all over the code, which may cause bugs in the future.

There are no related issues so far, so this is obviously low priority. The problem was first noted in https://github.com/netdata/netdata/pull/6387 and is recorded here for posterity.

##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0-144

##### Component Name
Collectors, pluginsd

**Comment by ilyam8** [comment]
@vlvkobal this could be fixed by changing `bug` label to `feature request` 😉

**Comment by vlvkobal** [comment]
We had a discussion with @ilyam8. I'm closing this since it is a very low priority issue and it will most likely be fixed during the next refactoring of `pluginsd`.
