### ISSUE TITLE
Binding Netdata to Socket

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#6403]
##### Question summary
I'm trying to get netdata to bind to a linux socket so that I can run it behind apache webserver. I've been using the documentation here: https://docs.netdata.cloud/docs/running-behind-apache/

I have things running fine behind apache with my netdata.conf set to
`[web]`
`bind to = localhost`

VirtualHost Settings:
```
<VirtualHost *:80>
    ServerName www.netdata.mysite.com
    RewriteEngine On
    ProxyRequests Off
    ProxyPreserveHost On

    <Proxy *>
        Require all granted
    </Proxy>

    ProxyPass "/" "http://localhost:19999/" connectiontimeout=5 timeout=30 keepalive=on
    ProxyPassReverse "/" "http://localhost:19999/"
</VirtualHost>
```
However, as soon as I change that to `bind to = unix:/tmp/netdata.sock`
And set the following in my Apache VirtualHost I am no longer able to connect.
```
<VirtualHost *:80>
    ServerName www.netdata.mysite.com
    RewriteEngine On
    ProxyRequests Off
    ProxyPreserveHost On

    <Proxy *>
        Require all granted
    </Proxy>

    ProxyPass "/" "unix:/tmp/netdata.sock|http://localhost:19999/" connectiontimeout=5 timeout=30 keepalive=on
    ProxyPassReverse "/" "http://localhost:19999/"
</VirtualHost>
```
The following shows up in my netdata-access log:
>Get / HTTP/1.1" 503 583 "-" Mozilla/5.0
The following shows up in my netdata-error log:
>[proxy:error] No such file or directory: HTTP: attempt to connect to Unix domain socket /tmp/netdata.sock (localhost) failed
>[proxy_http:error] HTTP: failed to make connection to backend: httpd-UDS

I would greatly appreciate any help.
Thanks.

##### OS / Environment
Ubuntu server 18.04, Apache 2.4.29

**Comment by cakrit** [comment]
I don't know much about Unix sockets myself, but what I've done in a similar situation is to manually touch the file myself and ensure the netdata user has read/write access to it. You httpd user would also need to be able to read from/write to it as well. Try it by hand and see if it helps. If there's a better way, I'd love to hear from the community. We do need to update the documentation for that, regardless of whether the solution is to do it manually, or there's some other way to configure it...

**Comment by Steve8291** [comment]
Finally got it.
Since Apache 2.4.24, Apache cannot read from sockets in /tmp
Creating a new directory inside /run or /var/run and chown netdata:netdata allows connection.
For some reason you can't use the netdata directory that is created there by systemd netdata.service
I think this can probably be fixed by adjusting the netdata.service file.
Still have more testing to do but I will report back here and then try to add some notes to the documentation.

**Comment by Steve8291** [comment]
So it is definitely a problem with systemd and newer Apache versions. I played around with making a netdata.socket systemd file but it isn't required to make this work. I suppose it could be good to have the socket created by systemd in the future. Netdata is also using the /var/run/netdata/ directory to put the socket into. I must have had a typo before. So to sum up:
In the netdata.conf file set `bind to = /var/run/netdata/netdata.sock` or `bind to = /run/netdata/netdata.sock`
At least on Ubuntu /var/run is symlinked to /run

**Comment by cakrit** [comment]
Cool mate, will you be able to do a PR for the docs? 
You've been all over the place by the way, your contributions are HIGHLY appreciated! :)

**Comment by Steve8291** [comment]
Thanks @cakrit 
I think I've got a pull request for it: https://github.com/netdata/netdata/pull/6406
Please look it over to make sure it all sounds good.

**Comment by JialuZhang** [comment]
@Steve8291 

In your configuration,
```
<VirtualHost *:80>
    ServerName www.netdata.mysite.com
    RewriteEngine On
    ProxyRequests Off
    ProxyPreserveHost On

    <Proxy *>
        Require all granted
    </Proxy>

    ProxyPass "/" "http://localhost:19999/" connectiontimeout=5 timeout=30 keepalive=on
    ProxyPassReverse "/" "http://localhost:19999/"
</VirtualHost>
```

the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

**Comment by Steve8291** [comment]
Thanks @JialuZhang 
That does make sense. I had wondered if it was necessary since there were no rewrite conditions. If I remember right I think I was basing that off of several examples I found elsewhere for proxypass. Let me just test it on my instance to make sure it doesn't cause any problems turning it off and then one of us can put in a pull request to change the documentation.
