### ISSUE TITLE
Netdata on GCP not loading

### ISSUE THREAD

**Issue by B3nd3r15** [netdata/netdata#6407]
##### Question summary
I am running ubuntu 16.04.6 LTS on GCP and I have two firewall rules to allow port 19999 inbound and outbound but I cannot get the web page to load at serverip:19999. Is there any additional ports that I need to allow for it to load properly? When I look on the server netdata is running fine with no errors that I know of. 

If I install it locally on a vm it all runs fine. When I look at netstat port 19999 it is listening on the GCP Server..

##### OS / Environment
ubuntu 16.04.6 LTS on GCP

##### Component Name
Web UI  <serverip>:19999

##### Expected results
to see the netdata info for my server.

**Comment by cakrit** [comment]
Do you get a timeout or a connection refused? netdata doesn't need any other ports and the default setting is to allow connections from anywhere for the plain dashboard access. So it definitely looks like it has something to do with the firewall setup.

**Comment by B3nd3r15** [comment]
I'm getting a timeout. I have the priority set to 1000 which is the first to be processed.

**Comment by ilyam8** [comment]
>  When I look at netstat port 19999 
> I have the priority set to 1000 which 

Could you show it?

**Comment by B3nd3r15** [comment]
From the server:
netstat -tulpn
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0                      0 0.0.0.0:19999           0.0.0.0:*               LISTEN                 1530/netdata

From the GCP firewall rules page:
![image](https://user-images.githubusercontent.com/12829971/60827767-8f114f80-a176-11e9-9920-51f500f3d288.png)

**Comment by ilyam8** [comment]
Looks ok, i assume `Targets Apply to all` is source/destination, am i right?

I guess there is a rule with deny action and a higher priority. Try to temporary disable them one by one and see if it fixes the problem.

**Comment by B3nd3r15** [comment]
I don't have anything denying any connections. Apply to all is for this project. So any servers running for this project will allow port 19999 instead of me just putting in one server ip. Ip Ranges 0.0.0.0 means any ip. I've set up firewall rules for other gcp projects and they are almost instant. I've had these set up for a while now and still timing out.

**Comment by cakrit** [comment]
Put a /0 after the IP. That's what I see from our GCP firewall rules for other, irrelevant services. Looks like the default netmask is /255

**Comment by B3nd3r15** [comment]
that was it. Glad it was my stupid typo. Thanks everyone.

**Comment by ilyam8** [comment]
> I don't have anything denying any connections. 

sounds not good btw :smile: why do you need allow rules if there is not deny rules :thinking:

**Comment by B3nd3r15** [comment]
From what I understand GCP blocks everything by default only allowing what you have listed. Maybe i'm wrong but if they do change it in the future I'll be set anyways. I just tried to set it up on another server and it didn't work until i put the firewall rule in. Maybe something with my project setup. Not sure.
