### ISSUE TITLE
custom_log_format

### ISSUE THREAD

**Issue by hamzash9500** [netdata/netdata#6410]
Hi all,
can anyone help me to find the pattern for this log:
x.x.x.x [09/Jul/2019:09:34:00 +0000] "GET /xxxxx/xxx?rules=[{%22or%22:[%22xxx%22,%22xxx%22,%22tagEvent%22,%22xxxx%22,%22xxxx%22,%22xxxx%22,%22xxxx%40,%22xxxxx%22,%22xxxx%22]}]&limit=12&offset=0&location={%22xxx%22:0} HTTP/1.1" 304 0 1122 0.112 0.112 "https://xxx-xxx.xxx.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36"

nginx config:
log_format netdata '$remote_addr [$time_local] "$request" $status $body_bytes_sent $request_length $request_time $upstream_response_time "$http_referer" "$http_user_agent"';

Thanks in advance,,,

**Comment by ilyam8** [comment]
The difference only is `- $remote_user ` part

https://github.com/netdata/netdata/blob/ef94259aeda57294cef39eba74d758ed36d1a2eb/collectors/python.d.plugin/web_log/web_log.conf#L98-L101

so this one should work

https://github.com/netdata/netdata/blob/ef94259aeda57294cef39eba74d758ed36d1a2eb/collectors/python.d.plugin/web_log/web_log.chart.py#L649-L654

just remove `-`

**Comment by hamzash9500** [comment]
thank you @ilyam8 
But I still get illogical and incorrect values, Please look at the attached  graph

 
![nginxlog](https://user-images.githubusercontent.com/34510063/60964408-ea307700-a31b-11e9-9803-1885fe3cfd25.png)

**Comment by ilyam8** [comment]
Well, check the values on the netdata dashboard. They should be good there.
