### ISSUE TITLE
[Question] Time schedule an alarm

### ISSUE THREAD

**Issue by jghaanstra** [netdata/netdata#6418]
##### Question summary
I'm new to Netdata but like it a lot. I searched the docs and Github but was unable to find an answer to my question. I have a VPS which runs user backups over night. This causes the default 10min_disk_backlog warning to trigger since it takes some time to generate the backups. So I would like to change the default template for 10min_disk_backlog and disable the warning between 05:00 AM till 06:00 AM. Is it possible to create a time schedule for warning and if so, how do I do this. The default template looks like this:

```
template: 10min_disk_backlog
      on: disk.backlog
      os: linux
   hosts: *
families: *
  lookup: average -10m unaligned
   units: ms
   every: 1m
   green: 2000
     red: 5000
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1))
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1))
   delay: down 15m multiplier 1.2 max 1h
    info: average of the kernel estimated disk backlog, for the last 10 minutes
      to: sysadmin
```

##### OS / Environment
CentOS 7 installed with kickstart-static64.sh

##### Component Name
/netdata/conf.d/health.d/disk.backlog /10min_disk_backlog

##### Expected results
A time scheduled alarm.

**Comment by ilyam8** [comment]
Set maintenance time is a nice feature indeed.

Related issues: #3187, #5614 

I see both issues are closed, link to related wiki page: https://docs.netdata.cloud/web/api/health/#health-management-api

From the wiki i see that there is a option to disable/silent alarms via api. And you need to write a script or something to have `maintenance time` feature.

Am i missing something? @thiagoftsm @cakrit

**Comment by cakrit** [comment]
Nope, that's the whole point of that feature. 
There's a very short note at the end of the health documentation: https://docs.netdata.cloud/health/#disabling-health-checks-or-silencing-notifications-at-runtime

@jghaanstra we'd appreciate a PR to improve https://docs.netdata.cloud/health/, so that people like you can find what you're looking for much more easily!

**Comment by jghaanstra** [comment]
Ok, thanx for the information. I'll have some free time after this weekend and will look into a PR which adds some additional information in the documentation. It should mainly included more information that it is (currently) not possible to schedule alerting using the config and that scheduling is done on runtime using the API.

I'm closing this.

**Comment by jghaanstra** [comment]
Perhaps someone is still reading along, I dont want to create a new issue.

It tried using the Health API but I get a 403 error on both curl and Postman get commands even though I'm using the X-Auth-Token header with the token from /opt/netdata/var/lib/netdata/netdata.api.key

```
 curl "http://vps.solidewebservices.com:19999/api/v1/manage/health?cmd=RESET" -H "X-Auth-Token: 6xxxxxxx-9xxx-1xxx-9xxx-0xxxxxxxx9"
You are not allowed to access this resource.
```

What could be wrong?

**Comment by thiagoftsm** [comment]
Hi @jghaanstra ,

About this 403, we have a test for the health api inside the directory tests/health_mgmtapi/ , as you can see there curl command is more or less exact what you are running, except by the fact tha we use curl in the silence mode(-s). Can you confirm to us that the NETDATA_VARLIB_DIR is pointed to the directory that you specified?

Best regards!

**Comment by cakrit** [comment]
Check `allow management from` in https://docs.netdata.cloud/web/server/#access-lists

**Comment by jghaanstra** [comment]
> Check `allow management from` in https://docs.netdata.cloud/web/server/#access-lists

Thank you, that does the trick. I'll see if I can say something about that as well in the docs as the default setting did not allow me to use the  Health Management API.

**Comment by cakrit** [comment]
That's the spirit! :)
