### ISSUE TITLE
Mysql query and average

### ISSUE THREAD

**Issue by petarkozic** [netdata/netdata#6420]
Hi,
I need one information. If we take a look into Mysql queries dashboard in Netdata we can see the number of queries per seconds.

Because I using prometheus and format prometheus there is average metrics.

If we take a look into:

netdata_mysql_queries_queries_persec_average
in which time span is this average which I get in prometheus?

Thank you.

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/tree/master/backends/prometheus#accuracy-of-average-and-sum-data-sources

**Comment by petarkozic** [comment]
@ilyam8 
Does that mean time span in average was defined by scrape interval from prometheus if I understand this?

**Comment by ilyam8** [comment]
Yes, excatly.

**Comment by petarkozic** [comment]
Thank you very much !
