### ISSUE TITLE
Run command with sudo in python.d module (ExecutableService)

### ISSUE THREAD

**Issue by rirze** [netdata/netdata#6423]
##### Question summary
How do I run a custom python module with a command that can only be run with sudo?

##### OS / Environment
RHEL 7.2
##### Component Name
/usr/libexec/netdata/python.d/raid_status.chart.py
This file extends the python framework netdata module class, `bases.FrameworkServices.ExecutableService`, with the command being set to `sudo /usr/sbin/hpssacli ctrl all show config`. 
##### Problem Output
```
bash-4.2$ /usr/libexec/netdata/plugins.d/python.d.plugin raid_status debug trace
2019-07-10 09:32:24: python.d INFO: plugin: main: Using python 3
2019-07-10 09:32:24: python.d DEBUG: plugin: main: module load source: 'raid_status' => [OK]
2019-07-10 09:32:24: python.d ERROR: plugin: main: module load config: 'raid_status' => [FAILED]
2019-07-10 09:32:24: python.d DEBUG: plugin: main: job initialization: 'raid_status raid_status' => ['OK']
2019-07-10 09:32:24: python.d DEBUG: plugin: main: module status: 'raid_status' => [OK] (jobs: 1)
[sudo] password for netdata:
```

Here it pauses, expecting user input. I'm expecting an output where the module runs on its own without asking for a password every time. If there is a way to get expected behavior by changing permissions, then please let me know.

**Comment by ilyam8** [comment]
Hi @rirze 	

https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/adaptec_raid#prerequisite

**Comment by rirze** [comment]
Thank you, that solved my issue.

**Comment by mikefaille** [comment]
@rirze I see your plugin seem to use the following command for hp raid : `hpssacli`
If it's possible, I will be interest to reuse your source code. Thanks.

**Comment by rirze** [comment]
@mikefaille Hi, the solution was to change user permissions in the sudoers file as Ilyam had linked.

**Comment by ilyam8** [comment]
@rirze i think @mikefaille wants to use your collector

**Comment by rirze** [comment]
@mikefaille Unfortunately, I cannot share my source code for the collector-- my company works with contractors with strict security policies. I also confess that my collector was simple and only collected one metric from the entire `hpssacli` metric. It is by no means, a complete collector as some of the plugins Netdata ships with. 

If you need help writing the collector, I gladly offer my help. You may contact me at cheedella.sourabh@gmail.com

**Comment by ilyam8** [comment]
@mikefaille i sugges to open a feature request

If you share your `hpssacli ctrl all show config` output it wont be hard to write a collector.

 - `hpssacli ctrl all show config` output
 - what do we need to collect from there

**Comment by BICB4** [comment]
I followed windows netdata monitoring using wmi, but it doesnt work, are there any more detailed instructions or video?

https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi

**Comment by ilyam8** [comment]
@BICB4 it has nothing to do with that issue, but

> but it doesnt work

doesnt say much, see

> https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi#troubleshooting
