### ISSUE TITLE
Using python module class LogService to access another user's file

### ISSUE THREAD

**Issue by rirze** [netdata/netdata#6427]
##### Question summary
How do I get the python class `LogService` to access a log file that resides another user's directory? The netdata user doesn't have permissions (by default) to access that directory and I was wondering how I can configure the user netdata to make this possible.
##### OS / Environment
RHEL 7.2
##### Component Name
`bases.FrameworkServices.LogService`
##### Expected results
```
bash-4.2$ /usr/libexec/netdata/plugins.d/python.d.plugin hvac_temp debug trace 
2019-07-10 15:36:22: python.d INFO: plugin: main: Using python 3 
2019-07-10 15:36:22: python.d DEBUG: plugin: main: module load source: 'hvac_temp' => [OK] 
2019-07-10 15:36:22: python.d DEBUG: plugin: main: job initialization: 'hvac_temp hvac_temp' => ['OK']
2019-07-10 15:36:22: python.d DEBUG: plugin: main: module status: 'hvac_temp' => [OK] (jobs: 1)
2019-07-10 15:36:22: python.d ERROR: hvac_temp: hvac_temp: Cannot access /home/notnetdata/log/unit_box_sensors.log
2019-07-10 15:36:22: python.d INFO: hvac_temp: hvac_temp: check() => [FAILED]
2019-07-10 15:36:22: python.d INFO: plugin: main: FINISHED
```

**Comment by ilyam8** [comment]
Hey @rirze 	

> to access a log file that resides another user's directory?


How about not to log to `home` directory? Or this is mandatory?

**Comment by rirze** [comment]
Hi @ilyam8,

Well the metric I need to monitor is in that directory... is there a way to give the class sudo permission?

**Comment by ilyam8** [comment]
No, python plugin has same permissions as netdata.

**Comment by paulkatsoulakis** [comment]
Hello there, thanks for reaching out!
If i may say, i think there is some bad practice regarding the application you are running from /home directory.

I would recommend to change the log directory for this application to be in an appropriate path, for example /var/log. In there you have the directory named MY_APP_LOG_WHATEVER_NAME for the application logs. This folder will have `myloguser:myloggroup` ownership and permissions set to 750 (owner full access, group read/execute, other none). The folder must reside on a path that is accessible for read by everybody (/var/log is like that)

In that scenario, all you have to do is add `netdata` user to `myloggroup` and it will be able to read the contents of that directory successfully.

Note: Do not add netdata on any super user groups or use sudo, as this may incorporate security risks.


Thanks again for reaching out!

**Comment by rirze** [comment]
Thanks for the advice. We actually use a single separate user directory for security reasons, so it's not as bad as I first described it to be. 

Your step to add netdata to the user group is exactly what I needed to solve this, it now works.

Thanks again
