### ISSUE TITLE
Hosts happen to have the same hostname (prefix) - dropdown shows 3 hosts but 2 are identical

### ISSUE THREAD

**Issue by girlandhercode** [netdata/netdata#6437]
##### Question summary
I have 3 servers. 1 will be "master" and remaining two will be "slaves".  The server's actual assigned hostnames are in this format:

`overwatch.league.university.edu`

`apex.elite.university.edu`

`apex.legends.university.edu`  <-- This is the "master" node.

The "Databases streamed to this agent" dropdown on the Netdata dashboard shows 3 entries:

`apex`
`overwatch`
`apex`

And the two `apex` servers are bringing up the same dashboard. The URL switches to  `.../host/overwatch/#menu_system;theme=slate;help=true` when choosing the `overwatch` dashboard, but this url is simply `.../#menu_system;theme=slate;help=true` on either of the other `apex` dashboards.

I hava assigned each of the streaming nodes different API_KEYs generated via the `uuidgen` command and these each have an entry on the "master" `stream.conf`

"master" `stream.conf`
```
[apex.elite api key]
    enabled = yes
    default history = 3600
    default memory = ram

[overwatch.league api key]
    enabled = yes
    default history = 3600
    default memory = ram
```
"slave" `stream.conf`
```
[stream]
    enabled = yes
    destination = XXX.XXX.X.XX:19999
    api key = <depending on server this gets one of the created keys>
    timeout seconds = 60
```

**Summary**: I load 2 different dashboards for `apex.legends.university.edu` and `overwatch.league.university.edu` but the 3rd `apex.elite` dashboard is a duplicate of `apex.legends`.

##### OS / Environment
Ubuntu 18.04.2 LTS
Netdata version is `1.16` latest release

##### Component Name
web/dashboard
##### Expected results
See 3 different dashboards one from the "master" one for each of the "slaves".

Is there a way to alias these names or assign them? I know in the `[global]` there is a `hostname` option, however it states in the docs this is auto-detected (this is my problem, i believe, since it only takes the first part of the host name up to the FIRST dot). 

Thank you in advance!!!

**Comment by cakrit** [comment]
Check what you have in `/etc/hostname` in those two machines. If you don't want to change it, there's no problem modifying the `hostname` option in netdata, it's autodetected, but your setting will be used instead.

**Comment by girlandhercode** [comment]
Thank you! Changing the `hostname` option under the `[global]` `netdata.conf` settings worked!! Now all three servers show up with their designated names.
