### ISSUE TITLE
Securing Netdata via Netdata.conf

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#6438]
##### Question summary

I've been unsuccessful in trying to lock down the rather excellent Netdata running on a cloud VPS from a US based host via the Netdata.conf allow options. I'd greatly appreciate some assistance or perhaps improved documentation.

I want it to remain accessible on my VPS localhost if necessary but need to lock down web access to myself. The Google sign in doesn't seem to provide this since Netdata is immediately visible via the ipaddress:19999 url.

If I add my IP address to the allow connections from line in Netdata.conf, it lets me view Netdata, but my home IP is a dynamic one provided by my UK fibre broadband provider and changes occasionally or I reboot or update my router.

My router auto updates a Netgear Dynamic DNS hostname with my current IP address, so I tried using this domain in the allow connections field, but it doesn't work even though the hostname resolves to my IP address correctly. 

This works okay:

`allow connections from = localhost 86.xxx.xxx.999`

This doesn't work at all, access denied!

`allow connections from = localhost example.mynetgear.com`

Thank you.

##### OS / Environment

`root@vpsxxxxx [/etc/netdata]# pt-summary
Percona Toolkit System Summary Report
    Date | 2019-07-11 20:18:26 UTC (local TZ: BST +0100)
    Hostname | vpsxxxx.inmotionhosting.com
      Uptime | 17:49,  1 user,  load average: 0.10, 0.13, 0.18
    Platform | Linux
     Release | CentOS Linux release 7.6.1810 (Core) 
      Kernel | 3.10.0-042stab138.1
Architecture | CPU = 64-bit, OS = 64-bit
   Threading | NPTL 2.17
     SELinux | Disabled
 Virtualized | OpenVZ/Virtuozzo
Processor
  Processors | physical = 2, cores = 24, virtual = 48, hyperthreading = yes
      Speeds | 48x2299.744
      Models | 48xIntel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
      Caches | 48x30720 KB
Memory 
       Total | 3.0G
        Free | 683.1M
        Used | physical = 1.9G, swap allocated = 3.0G, swap used = 232.0k, virtual = 1.9G
      Shared | 137.4M
     Buffers | 473.3M
      Caches | 874.8M
       Dirty | 280 kB
     UsedRSS | 1.6G
  Swappiness | 1
 DirtyPolicy | 20, 10
 DirtyStatus | 0, 0
`

##### Component Name

netdata.conf

##### Expected results

Netdata should hopefully allow connections from a correctly resolving domain as it does with an IP address.

**Comment by cakrit** [comment]
Well, netdata isn't meant to replace the need for firewalls. Without asking to verify, I expect that the reason hostnames are not allowed in the access list is to prevent query performance issues from DNS lookups. The check against the access list is executed every time a socket is opened, so the performance hit could become very significant. Implementation-wise it wouldn't be that difficult to do it, but I'm not certain it's a good idea. I may be wrong of course, let me check internally.

**Comment by cakrit** [comment]
I discussed with @ktsaou . He's ok doing it, but it's more complex than I thought, since it's extremely easy for someone to spoof a hostname. He'd need to do the following:
- Reverse lookup on the originating IP to get a list of hostame(s) declared for that IP
- Forward DNS lookup on hostnames, to ensure the IP appears there. 
- Match one of the validated host names with the names in the access list.

We will move forward if there is sufficient interest on this from the community, so like the issue if you want it to move forward, or take a crack on implementing it!

**Comment by TheOldMan2000** [comment]
Thank you for the informative response, much appreciated. I understand, yes probably there are much more efficient ways to reduce access. I tried the method posted this week about putting it behind Apache but it didn't work for me, I use CentOS7 not Ubuntu, so you get half way and run into errors about no such file or directory etc. 

We're encouraged as server admins not to reveal any unnecessary details about potential services and other information even in general, from the perspective of best practice and target hardening. criminals and door rattlers will look for any potential opening, so I'd like to reduce opportunity if possible. He says after posting his server and OS config!

**Comment by cakrit** [comment]
> He says after posting his server and OS config!

ROFL!

**Comment by ilyam8** [comment]
> I tried the method posted this week about putting it behind Apache but it didn't work for me, I use CentOS7 not Ubuntu, so you get half way and run into errors about no such file or directory etc.

This will sovle you problem, apache [mod_authz_host](https://httpd.apache.org/docs/2.4/mod/mod_authz_host.html) is what you need.

**Comment by Saruspete** [comment]
Hello,

That is indeed a nice feature too, especially on hosts where you want to reduce all installed software (and a web server is not a small one, attack surface speaking). So to have netdata definitely standalone, that's a real gain (like on hypervisors or IoT)

Let me add my infrastructure & security experience: 
- Contrarily of forward dns where multiple hosts can point to the same IP, a reverse dns only points to 1 name. So you should only have 0 or 1 hostname for the originating IP 
- Most servers have a DNS cache (let it be sssd, nscd, local dnsmasq...) 
- many hosts don't have a reverse at all.
- we often use (or would like to) wildcard inside the name (eg:  host-*-admin.mycorp.com) or plain domain (.mycorp.com) to avoir constant configuration update.
- DNS server may protect themselves from query flood.

> since it's extremely easy for someone to spoof a hostname.

Well, it's not *that* easy to spoof dns, especially on custom / corp DNS. But I'd appreciate a recent scenario where this has been done to prove me wrong. 

That feature with the https + auth would be a lovely addition to get netdata fully standalone !
