### ISSUE TITLE
Httpcheck multiline regex

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#6444]
Hi

I would like to configure multiline regex in httpcheck.conf.
I seems not possible when reading the source code 
``` 
pattern = self.configuration.get('regex')
self.regex = re.compile(pattern) if pattern else None
``` 

re.MULTILINE option is not given to re.compile function.

**Comment by ilyam8** [comment]
@fmercier-almerys hi

It always was possible to use any flag, every flag has inline version

> https://docs.python.org/3/library/re.html#re.M

`re.MULTILINE` => `(?m)`
`re.DOTALL` => `(?s)`

See

```python
In [10]: re.search('(?s)start.*finish', "start run run\n run finish")
Out[10]: <re.Match object; span=(0, 25), match='start run run\n run finish'>
```
