### ISSUE TITLE
Running behind HAproxy removes styling

### ISSUE THREAD

**Issue by johnramsden** [netdata/netdata#6446]
##### Question summary

I'm running netdata behind HAproxy. I'm able to get forwarded to the correct netdata port from https://example.com/netdata but all of the styling and images seem to be missing.

I've successfully run behind nginx with:

```
    location /netdata/ {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:19999/;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        access_log off;
    }
```

But I'm not sure how to get the equivalent config working on HAproxy.

##### OS / Environment

* netdata v1.16.0-43-nightly
* Ubuntu 18.04
* HAproxy 2.0.0

##### HAproxy Relevant configuration

```
frontend https_frontend
    ## HTTP ##
    bind :::80 v4v6
    # Redirect all HTTP traffic to HTTPS with 301 redirect
    redirect scheme https code 301 if !{ ssl_fc }

    ## HTTPS ##
    # Bind to all v4/v6 addresses, use a list of certs in file
    bind :::443 v4v6 ssl crt-list /etc/letsencrypt/certslist.txt

    acl is_netdata url_beg  /netdata

    ## Backends ##
    use_backend     netdata_backend       if is_netdata

backend netdata_backend
    option forwardfor
    server      netdata_local     127.0.0.1:19999

    http-request set-header Host %[src]
    http-request set-header X-Forwarded-For %[src]
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request set-header Connection "keep-alive"

```

**Comment by cakrit** [comment]
I haven't seen any issues related to haproxy configuration, but even your nginx configuration isn't correct. https://docs.netdata.cloud/docs/running-behind-nginx/#as-a-subfolder-to-an-existing-virtual-host shows that you need a URL-rewrite that strips /nedata from the path, if you want to access it as XXX/netdata. I expect that you need to do something similar for haproxy as well. 
We would really appreciate a new README page with the config, when you get it to work. If you can't write it, let's at least have the configuration that worked for you and we'll add the page ourselves.

**Comment by johnramsden** [comment]
@cakrit Another page for the docs would be very useful. I'll make a pull request with what I have. I did actually try without the `/netdata`, by proxying the base URL, and ran into the same issue.

For nginx I've never had an issue with my configuration, but I will change it.

**Comment by cakrit** [comment]
It's strange that you didn't have an issue. I don't like strange. When you access the console directly, you just see http://localhost:19999/#... ?
We may get help from someone else who has already done it via HAProxy here, it's interesting...

**Comment by johnramsden** [comment]
I haven't had the issue with nginx proxying, if that's what you're referring to. I get https://mydomain.com/netdata/# , and everything's working. I'm using same configuration on multiple sites. Maybe there is a certain situation that causes problems?

Also, an update - I tried again in the configuration _does_ actually work using only the base URL. It's just when a subpath is used that the problem occurs.

**Comment by cakrit** [comment]
Ok, I tried again with your nginx configuration. So, apparently most of the UI works without the rewrite, but I saw at least one thing that didn't work properly, when I call `api/v1/info`, I see an error retrieving the favicon.

I'm not really clear on why it works without the rewrite in nginx, i.e. without a configuration like the following:
```
upstream netdata {
    # the Netdata server
    server 127.0.0.1:19999;
    keepalive 64;
}

server {
    listen 81;
    # the virtual host name of this subfolder should be exposed
    server_name netdata.domain.tld;

       location = /netdata {
                return 301 /netdata/;
        }

        location ~ /netdata/(?<ndpath>.*) {
                proxy_redirect off;
                proxy_set_header Host $host;

                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #proxy_pass http://netdata;
                proxy_pass_request_headers on;
                proxy_http_version 1.1;
                #proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "keep-alive";
                proxy_store off;
                proxy_pass http://netdata/$ndpath$is_args$args;
        }
}
```
I'll see if I can figure that out, but the most important thing is that we still haven't understood why your HAProxy config doesn't work. 

Can you do a tail -f on your `/var/log/netdata/access.log` so we can see how the requests come in? They shouldn't have a `netdata` preceding the path.

**Comment by cakrit** [comment]
I installed HAproxy and started trying. The first warnings I see are the following:
```
[christopher@chris-msi netdata]$ /usr/bin/haproxy -f /etc/haproxy/haproxy.cfg 
[WARNING] 198/155259 (11033) : parsing [/etc/haproxy/haproxy.cfg:57] : HTTP log/header format not usable with backend 'netdata_backend' (needs 'mode http').
[WARNING] 198/155259 (11033) : config : missing timeouts for backend 'netdata_backend'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 198/155259 (11033) : config : 'http-request' rules ignored for backend 'netdata_backend' as they require HTTP mode.
[WARNING] 198/155259 (11033) : config : 'option forwardfor' ignored for backend 'netdata_backend' as it requires HTTP mode.
[WARNING] 198/155259 (11033) : config : missing timeouts for frontend 'http_frontend'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
```

**Comment by cakrit** [comment]
I just can't get the acl to match. Ever. I tried everything I could find online, nothing works. 

In the following example, it just goes to www_backend, which is meant to give me a 5xx error. Sometimes I accidentally saw something that looked like netdata, but with the browser caching, I just couldn't tell.

```
frontend http_frontend
    ## HTTP ipv4 and ipv6 on all ips ##
    bind :::8082 v4v6
    acl nd path_beg -i /netdata/
    use_backend netdata_backend if nd
    default_backend www_backend

backend netdata_backend
    mode        http
    option forwardfor
    server localhost 127.0.0.1:19999
    http-request set-header Host %[src]
    http-request set-header X-Forwarded-For %[src]
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request set-header Connection "keep-alive"
    http-request set-path %[path,regsub(^/netdata,/)]


backend www_backend
    mode        http
    option forwardfor
    server      netdata_local     127.0.0.1:19998
    http-request set-header Host %[src]
    http-request set-header X-Forwarded-For %[src]
    http-request set-header X-Forwarded-Port %[dst_port]
    http-request set-header Connection "keep-alive"
    http-request set-path %[path,regsub(^/netdata/,/)]
```
HOWEVER, when I made netdata_backend the default backend, everything works perfectly with the regsub. No requests to invalid paths, it just works.

I spent an hour on this, I suggest you try it yourself as well and continue on that thread with haproxy. Something fishy is happening with those ACLs.

**Comment by johnramsden** [comment]
Interesting, does it work with:

```
acl nd path_beg -i /netdata
```

**Comment by johnramsden** [comment]
And maybe the rest of my configuration is necessary:

```
global
    maxconn     20000

    log         /dev/log local0     # Log to systemd socket
    log         /dev/log local1 notice
    user        haproxy
    group       haproxy
    pidfile     /run/haproxy.pid

    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    daemon

    tune.ssl.default-dh-param 4096  # Max size of DHE key

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL). This list is from:
    #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    # An alternative list with additional directives can be obtained from
    #  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http
```

**Comment by cakrit** [comment]
These settings didn't make a difference, but it was Chrome that was giving me misleading responses. Firefox was much nicer. 
The key to make it work (other than the rewrite) was this magic line that you put in the README

```
http-request redirect scheme https drop-query append-slash if is_netdata ! { path_beg /netdata/ }
```
So I'm all good, will be approving the PR as soon as @joelhans 's comments are addressed.
