### ISSUE TITLE
Implement object name map

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#6448]
##### Feature idea summary
Implement a lookup structure that maps names (of objects, as described [here](https://github.com/netdata/netdata/issues/8183)) to GUIDs. The purpose of the object name map is to map unique name identifiers (e.g. concatenated ids of host|chart|dimension) of objects to UUIDs (128 bit). This only resides in memory.

**Comment by stelfrag** [comment]
Will be handled in #8900
