### ISSUE TITLE
Implement tiering of metrics

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#6450]
##### Feature idea summary
Implement tiering of metrics as described in #4687 (https://github.com/netdata/netdata/issues/4687#issuecomment-458504481).

**Comment by manos-saratsis** [comment]
Some ideas we could pick from:
- Graphite Wisper DB https://graphite.readthedocs.io/en/latest/whisper.html
- RRDtool https://oss.oetiker.ch/rrdtool/doc/rrdtool.en.html

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
