### ISSUE TITLE
Disable HTML email for alarms

### ISSUE THREAD

**Issue by leo-lb** [netdata/netdata#6458]
##### Feature idea summary
Currently netdata sends mixed HTML/text emails for alarms, I'd like that it sends text-only emails. Some command line clients just don't parse HTML and text-only is just fine.

**Comment by cakrit** [comment]
How about we just add an option for plain text vs HTML in `health_alarm_notify.conf` so we can do both? I like the idea.

**Comment by cakrit** [comment]
Actually, are you able to do a PR for it @leo-lb ? We can help you with it, it should be quite simple really, just some shell scripting...

**Comment by leo-lb** [comment]
@cakrit When I can get to it, sure.

**Comment by leo-lb** [comment]
@cakrit https://github.com/netdata/netdata/pull/6485
