### ISSUE TITLE
Issues with signing up to the cloud

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6459]
From Clayton C. :
Hi, sorry to bother you on a Sunday, but I just learned about ND Cloud and was trying to get it setup for my instances, but I'm having trouble doing so. 

Steps #1:
1. in ND, click "nodes" or "sign-in"
2. enter email address and click "Authorize"
3. receive email, click the "Sign In" button
4. I'm redirected back to the original ND instance, w/ not noticeable difference. Clicking "nodes" or "sign-in" again just repeats the loop.

Steps #2:
1. go to http://netdata.cloud/account/sign-in (no https?), enter email address and click "sign-in"
2. receive email, click the "Sign In" button
3. I'm redirected back to https://www.netdata.cloud, again w/ no difference. Going back to http://netdata.cloud/account/sign-in just repeats the process.

I'm using the email address clayton@fedcoseeds.com, I'm not using the Google or Github logins.

Also, in the "Introducing Netdata Cloud" blog post, there is a link to a "companion piece" about getting setup w/ ND Cloud. It links to this URL https://blog.netdata.cloud/posts/how-to-netdata-cloud/ which results is a 404.

Thanks!

**Comment by cakrit** [comment]
- Can you please check if the link opens a new browser, different to the one you are using to see the agent console? 
- If you copy the URL of the link to sign-in and paste it manually on a different tab of the browser you used to start the process, do you get signed in properly?

I assume you are correctly clicking the link of the latest email you have received. These links expire after a bit and generating a new one invalidates the last one. We are not generating  proper error message when this happens and it is something we definitely need to fix.

The http link is clearly a bug as of course the broken link to the blog post as well.

**Comment by claytonrcarter** [comment]
Hi, thanks for the quick reply!

- If I click the "Sign-in" or "Nodes" link from the ND dashboard, it opens in a new tab.
- After I enter my email address there and receive the confirmation email, the "sign in" link from that email also opens in a new tab.
- Pasting the sign-in URL (http://netdata.cloud/account/sign-in) does not log me in; it just sends me back to the "sign-in" page which then takes me back into the "authorize" loop (ie sending me an email to confirm, etc)

I have disabled all ad-blockers (uBlock & pihole) and I'm using up-to-date FF on a Mac.

**Comment by cakrit** [comment]
I meant to paste what you get from right clicking on the 'Sign In' button in the email you received and selection 'copy this url'. gmail replaces the link with a ct.sendgrid.net url that then goes on to a URL like this:
http://manifest-quasar-227909.appspot.com/account/emailauth/callback?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNocmlzQG5ldGRhdGEuY2xvdWQiLCJleHBpcmVzIjoiMTU1NzgxNzIxOCJ9.S-uzcVXcGH6-zM5lGHIcGA9ptl2lpz0Mqq19RY8dSjw&state=%2Faccount%2Fsign-in-agent%3Fid%3D410d49ae-5ed4-11e9-a4e5-525400061463%26name%3Dfedora%26origin%3Dhttp%253A%252F%252F192.168.122.52%253A20001%252F%26redirected%3Dtrue

The particular one I sent has an expired token.

**Comment by cakrit** [comment]
Let me summarize the issues we certainly have and we'll see if @claytonrcarter has a different one:
- [ ] Error handling needs fixing: Users get almost no error messages when something goes wrong with the sign in process, they get redirected to the sign-in page agan.
- [ ] We do have a couple error messages, for when a token has expired, or when the signature is invalid. The page showing that error is awful and must be replaced.
- [ ] The sign-in link is http
- [ ] The blog post link must be fixed
- [ ] The URL in the email points users to netdata.cloud, which has been redirected to the web site. That link doesn't seem to make sense at all.

**Comment by claytonrcarter** [comment]
Yes, I also tried that, too. 😄  If I paste that link into a new tab, I am not logged in or signed in, same as before. I just double checked and this also doesn't work for me in Chrome.

When I load my ND dashboard in question, I am noticing a 401 response for a URL like: https://netdata.cloud/account/sso-agent?id=... This happens twice everytime I load the dashboard. Is that related?

BTW, this is a fresh install of ND 1.16.0. Thank you for the help!

**Comment by cakrit** [comment]
That 401 is what you get when the cloud doesn't recognize you as a user. Thanks @claytonrcarter , we'll continue investigating and let you know if we require more info.

**Comment by cakrit** [comment]
Additional issues:
- [ ] When I run behind a reverse proxy that puts netdata behind a sub-path (e.g. http://somedomain/netdata/) the sign-in via email doesn't work. The other sign-in methods work fine.
- [ ] Reported but not verified, that the sign-in via email doesn't work on Safari.

**Comment by ivorjvr** [comment]
![error page](https://user-images.githubusercontent.com/1156027/61299456-0dee3400-a7d8-11e9-89e3-1e585f155278.png)

**Comment by syedomair** [comment]
@cakrit 
"Error handling needs fixing: Users get almost no error messages when something goes wrong with the sign in process, they get redirected to the sign-in page again."
The reason it keeps on redirecting to the sign-in page is that on the successful login through the email link, the code deletes the session variable. Then the next time the user tries to comes in with the same link since the session variable is deleted (it is an error) and we got redirect to the sign-in page. 
If the user clicks on the email link third time, it will work fine because on the second time session was set correctly but it got redirected. 
If the user clicks on the email link the fourth time, it will not work because, at the third time, the session was deleted on success. 
On the fifth time, it will work again and so on. 
I just commented out this line sess.Delete("FreshSignIn"), it is working for all the times (no redirects).

**Comment by cakrit** [comment]
What is that session variable? Perhaps we can ask the user who reported the issue to tell us what he sees in his process, perhaps there are cases where it's not properly set, or where the browser doesn't see the call we do when we press the button in the email  as the same session at all (it's an email link after all, I don't get how the link is matched to that session). 

Can you test that all other scenarios work as well when we don't delete it? If so, then what is this delete supposed to accomplish?

**Comment by VLegakis** [comment]
Verified this as running correctly in Safari (actually with exactly the same above issue as with other browsers. So, verified Safari in not any special case)

**Comment by cosmix** [comment]
@VLegakis Safari doesn't work with Github login.

**Comment by pgassmann** [comment]
I had similar issues caused by uMatrix Browser Plugin that blocks external resources. netdata.cloud relies heavily on Google services.

**Comment by VLegakis** [comment]
> @VLegakis Safari doesn't work with Github login.

Hello @cosmix this has been verified as working in Safari. Please contact if your problem persists.

**Comment by cosmix** [comment]
@VLegakis I don't understand what 'has been verified as working in Safari' means. It fails on two of my machines. Please note that there are no enabled extensions in my Safari installs, and I can provide more detail if you need it — this is as vanilla an install as possible; as of writing this comment it's not verified as working, but the exact opposite, as far as I'm concerned. You will need to triage this yourself, evaluate the extent of this issue, find the causes and report back. 'Works for me' is no verification I'm afraid.

**Comment by VLegakis** [comment]
@cosmix Thank you for your feedback. Let's try more to reproduce this. Since this issue is not related to the one here I moved it to: https://github.com/netdata/netdata/issues/6500
and we can follow up there.

**Comment by nicolasparada** [comment]
OK, we did some updates and put a fix for the email authentication.
Still we need to improve how errors are presented to the users.
And also handle the case when netdata is running in something like a reverse-proxy which puts it in a subpath.

**Comment by claytonrcarter** [comment]
Thank you for all of your help on this! I was able to get this to work in Safari, but not so in Chrome and FF. I disabled uBlock Origin and piHole for all browsers.

**Safari:** process worked as advertised: click "sign in", enter email, paste link from email into Safari, that tab closes and my NC dashboard starts showing my email address where "sign in" had been. Clicking on "Nodes" now takes me to the nodes view.

**Chrome:** process almost works: "sign in" seems to work and my email address shows on the ND dashboard as if I'm signed in, but clicking on "Nodes" takes me back to the "Authorize" loop, where I need to send an authorization email, etc.

**Firefox:** no change at all, sign in and authorization appear to not work at all as originally reported.

Thanks!

**Comment by cakrit** [comment]
@claytonrcarter we can't replicate the behavior you're seeing in Chrome and Firefox. 
Can you please show the exact steps you're following? I'm especially interested in whether you are clicking the link from your email client or copying pasting it to the browser you started the process on. 
I'm also interested in any other addons you may have, that could be affecting the process.

**Comment by syedomair** [comment]
About the issue "When I run behind a reverse proxy that puts netdata behind a sub-path (e.g. http://somedomain/netdata/) the sign-in via email doesn't work. The other sign-in methods work fine." 
@cakrit could please explain how to reproduce this problem. Initially, we thought it as a new feature rather than a bug.

**Comment by nicolasparada** [comment]
It puts a prefix to the URL. So instead of `/account/emailauth/callback` it's `/something/account/emailauth/callback`. But this prefix is stripped to the Go server, so we cannot know from there. I think the only option here is to thrust the client and accept a `prefix` parameter or something like that.

**Comment by nicolasparada** [comment]
Sure there are lots of reverse proxies over there to put a netdata agent there and test, but @syedomair here is a simple Go snippet for a reverse proxy:
```go
package main

import (
	"flag"
	"log"
	"net/http"
	"net/http/httputil"
	"net/url"
	"strings"
)

func main() {
	remote := "http://localhost:19999"
	prefix := "/netdata/"
	listen := "0.0.0.0:3000"
	flag.StringVar(&remote, "r", remote, "Remote address")
	flag.StringVar(&prefix, "p", prefix, "Remote Prefix")
	flag.StringVar(&listen, "l", listen, "Listen address")
	flag.Parse()
	u, err := url.Parse(remote)
	if err != nil {
		log.Fatalf("could not parse remote address url: %v\n", err)
	}
	if !u.IsAbs() {
		log.Fatalln("remote address must be an absolute url")
	}

	rp := httputil.NewSingleHostReverseProxy(u)
	prefix = "/" + strings.Trim(prefix, "/") + "/"
	if prefix == "//" {
		prefix = "/"
	}
	http.Handle(prefix, http.StripPrefix(prefix, rp))
	err = http.ListenAndServe(listen, nil)
	log.Fatalf("could not start server: %v\n", err)
}
```
So you run netdata at `localhost:19999` but you can access it through `localhost:3000/netdata/`

**Comment by syedomair** [comment]
I can now recreate this problem on my local, looking at the code.

**Comment by claytonrcarter** [comment]
@cakrit 

1. Connect to wifi w/ no network-wide adblockers (I use a pihole at home)
2. Start Firefox (v 68.0.1, currently up-to-date) in safe mode, w/ all add-ons disabled.
3. Open preferences, go to "Privacy & Security", select "Manage Data", remove all cookies for domains related to netdata. (includes domains netdata.cloud and my-netdata.io)
4. Set "Content Blocking" to "Standard".
5. Open a new tab, connect to my ND dashboard (running v1.16.0 on port 18888)
6. Click the "Sign In" link in the upper right corner.
7. A new tab opens and I am directed to the "Authorize" page on netdata.cloud, at url https://netdata.cloud/account/sign-in?state=%2Faccount%2Fsign-in-agent%3Fid%3D6988d24a-a623-11e9-a483-9a6d7656700f%26name%3Dops%26origin%3Dhttp%253A%252F%252F___________.com%253A18888%252F%26redirected%3Dtrue (note that I removed my domain name in this URL)
8. I enter my email address and click the "Authorize" button.
9. Switch to email tab, open newly received email titled "Sign-In to Netdata Cloud". Right click on the "Sign In" button, select "Copy Link Location".
10. Switch back to netdata.cloud tab (still on "Authorization" page) and paste link from email: https://u8647778.ct.sendgrid.net/wf/click?upn=nwyYRIHK433co6SC7yTF5woyH-2FVA3x9Yu9mnesv4seegFdJXQALszM-2FUyUYVHoysijWhy7cPZI4q94EBVNH4F-... (truncated
11. The request goes out and the tab appears to be redirected, then it closes itself.
12. Switch back to ND dashboard tab and refresh. There is no change and the page still displays the "Sign-In" button in the upper right.

Note that step 11 is a little erratic. Sometimes it simply closes that tab, sometimes it appears to redirect my back to my dashboard w/i the tab. Regardless, it never actually signs me in.

Thank you for help on this and for being so responsive!

**Comment by nicolasparada** [comment]
Thank you @claytonrcarter or the detailed steps. That's very helpful.

**Comment by cakrit** [comment]
@syedomair and @nicolasparada I repeated the tests following the steps @claytonrcarter sent and didn't have a problem, until I tested with a brand new email address (testuser@netdata.cloud). It's not the sign-in, but the sign-up that has a problem. It failed the first time with a new email account, when I repeated the process with the same account (i.e. after sign-up was completed) it worked.

**Comment by cakrit** [comment]
@syedomair if you choose to not go via the go.d route for the reverse proxy, you can install nginx and put on `/etc/nginx/nginx.conf` what you see in https://docs.netdata.cloud/docs/running-behind-nginx/#as-a-subfolder-to-an-existing-virtual-host. You just restart nginx then (e.g. sudo systemctl nginx restart) and access netdata via http://localhost/netdata/

**Comment by nicolasparada** [comment]
Unable to replicate so far. On Windows Firefox 68.0.1. Using a new email address from [temp-mail.org](https://temp-mail.org), it sends the mail and login without problem.

**Comment by cakrit** [comment]
@claytonrcarter can you try once again? I got a failure in sign-up twice using new email accounts and your process, but then couldn't get it to happen again. We suspect that we have fixed it and that was I was seeing was due to .js file caching.

**Comment by nicolasparada** [comment]
If we confirm that this is an issue with caching. We could then set some headers for that, like `stale-while-revalidate`.

**Comment by claytonrcarter** [comment]
No luck. I opened dev tools and explicitly disabled cache for all of these attempts and everything worked as before: no success in signing in.

Perhaps this is another clue: I just tried the Github OAuth authentication in Firefox and the results are the same: I go through the authentication process just fine, but I'm not signed in. I also tried in Chrome and it behaves as I originally reported: the ND dashboard shows my username as if I'm signed in, but clicking on the Nodes link takes me back to the "Authorize" page on netdata.cloud.

I'm sorry that I didn't try this earlier, but it's certainly suggesting that whatever I'm experiencing isn't related to the email authentication process. I have been trying to use the email authentication b/c my work email and github account are separate.

Thank you again for all of you help with this!

**Comment by claytonrcarter** [comment]
BTW, as reported before, this is still working in Safari for me even w/ adblockers enabled.

**Comment by cakrit** [comment]
No, thank you for being so patient. These problems are so difficult to solve when we can't replicate them! Can you please open the browser console, click on preserve logs, repeat the process and send us everything you see there? Also a screenshot of the application storage for netdata.cloud. 

The only other thing we can do at this point is set up a video call with you... :)

**Comment by claytonrcarter** [comment]
Hi, I attempted to get as complete as I could. I posted relevant files/data here: https://gist.github.com/claytonrcarter/0142ff10a329f4095730b365de80a5ad Note that this was FF running in safe mode w/ privacy settings set to "standard" (as far as I can tell) and I attempted to mask my host name in these logs.

One problem with gathering information is that the authorization tab closes before I'm able to review the console or network logs; even with "Preserve Logs" enabled. I tried to record a video of the process, but the tab closes with no errors displayed and no statuses of the requests.

In Chrome, as I mentioned, the oauth appears to work and my GH username appears in the ND dashboard. When I go through the authorization process, the tab also closes w/ no chance for me to copy data, but again w/ no errors that I can note. *However*, the tab showing my ND dashboard displays the following message in the JS console. It seems like this is shown every time I go through the auth process. Also worth noting: even though Chrome shows that I'm logged in, if I reload the ND dashboard, I am no longer logged in.
```
main.js?v=7:5000 Uncaught (in promise) TypeError: Cannot read property 'concat' of null
    at syncAgents (main.js?v=7:5000)
    at main.js?v=7:5082
syncAgents @ main.js?v=7:5000
(anonymous) @ main.js?v=7:5082
Promise.then (async)
netdataRegistryCallback @ main.js?v=7:5076
handleSignInMessage @ main.js?v=7:4899
handleMessage @ main.js?v=7:4879
```

Safari continues to work as advertised. :)

**Comment by nicolasparada** [comment]
Thank you so much @claytonrcarter. The `postMessage` error is something new. We will look into it and provide a fix asap.

**Comment by cakrit** [comment]
Kind reminder, it seems that we have a PR pending to provide a fix for this.

**Comment by cakrit** [comment]
@claytonrcarter I looked at the linked PR again, the issue should be fixed. I'm closing, but please comment if you still have an issue.

**Comment by tetrode** [comment]
I have this issue with the brave browser, latest version. FF and Chrome work OK

**Comment by cakrit** [comment]
> I have this issue with the brave browser, latest version. FF and Chrome work OK

We have #6298 open for this.
