### ISSUE TITLE
Mongodb Client SSL keyfile support

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#6464]
Hi

Mongodb recommends using SSL key client file in production. However netdata python.d plugin does not support it. 
Can you make some involvement to add this new configuration ?

```
>>> client = pymongo.MongoClient('example.com',
...                              ssl=True,
...                              ssl_certfile='/path/to/client.pem',
...                              ssl_keyfile='/path/to/key.pem',
...                              ssl_pem_passphrase=<passphrase>)
```

**Comment by ilyam8** [comment]
duplicate of https://github.com/netdata/netdata/issues/5884, closing the issue

**Comment by ilyam8** [comment]
@fmercier-almerys i will try to implement #5884, np!

**Comment by fmercier-almerys** [comment]
Hi You closed the issue as a duplicated with #5884 but it seems #5884 addresses only server ssl certificate no ?

**Comment by fmercier-almerys** [comment]
Ok you prefer #5884 to addresses the two needs, client and server ssl certificates, up to you +1

**Comment by ilyam8** [comment]
yes, i plan to add all [client ssl related stuff](https://api.mongodb.com/python/3.3.0/examples/tls.html)
