### ISSUE TITLE
Python Example for text only chart renderer 

### ISSUE THREAD

**Issue by set-element** [netdata/netdata#6469]
##### Question summary
Could someone please provide a toy example for a python plugin that uses the text-only chart type? Something like example.chart.py but for text chart output.  I have experimented a bit but have not managed to get anything to work.

Many thanks for an amazing project!
scott

##### OS / Environment
Linux/CentOS 6.5
##### Component Name
python.d

**Comment by ilyam8** [comment]
Hi, this can be achieved using custom dashboards. It is not python/plugin related.

see
https://github.com/netdata/netdata/pull/5971
https://docs.netdata.cloud/web/gui/custom/

**Comment by set-element** [comment]
Will use that.  Thank you for your quick response!
scott
