### ISSUE TITLE
Variables exposed as prometheus metrics grow stale over time

### ISSUE THREAD

**Issue by jabbrwcky** [netdata/netdata#6470]
##### Bug report summary

When scraping metrics with prometheus including variables, the variables are exported with a stale timestamp causing the metrics to be dropped by prometheus, if the Netdata process has been running for some while, e.g.:

```
# COMMENT netdata "[host]" to prometheus "[IP]", source "as collected", last seen 403962 seconds ago

netdata_info{instance="[host]",application="netdata",version="1.10.1_rolling"} 1 1563257864635

# COMMENT global host and chart variables
netdata_active_processors 4.0000000 1562759185000
```

The variables report the timestamp netdata was last restarted (first scrape possibly?), others report the current time.

Once the static data has aged enough, the variable values will start failing in the scrape.

##### OS / Environment

 ubuntu 14.04

##### Netdata version (ouput of `netdata -V`)

netdata 1.10.1_rolling

##### Component Name

prometheus export

##### Steps To Reproduce

On a host where netdata has been running for some time scrape metrics using an prometheus server also scraping the constant variables:

`http:/host:19999/api/v1/allmetrics\?format=prometheus\&source=raw\&variables=yes`

##### Expected behavior

The exporter should return static metrics values with the current timestamp, not the time the metrics were recorded.

**Comment by ilyam8** [comment]
> https://docs.netdata.cloud/collectors/plugins.d/#variable

> These variables can be set and updated at any point.


> > The variables report the timestamp netdata was last restarted (first scrape possibly?), others report the current time.

According wiki it is valid to set `var` only on start and dont update the value during runtime (doesnt make sense if the value is not changed).

**Comment by cakrit** [comment]
@jabbrwcky please upgrade to the latest version first. A lot of time has passed since 1.10. 
I'm not sure if there are any changes to this behavior since then, but it's always a good idea to have your netdata updated.

**Comment by ilyam8** [comment]
wow, i didnt notice the version :see_no_evil:

**Comment by jabbrwcky** [comment]
I'll have to ask our operations guys if they can upgrade it in general - I will try installing a more recent version manually on one of the hosts and see if the issue is still there

**Comment by jabbrwcky** [comment]
I just tried `netdata v1.16.0-43-nightly` on one of the hosts and the timestamps of variables and changing metrics differ (not by much as I just started netdata), so I expect the error to occur also with the latest version when the process has been running long enough.
