### ISSUE TITLE
can network metrics under apps plugin reporting data send/receive per connected port?

### ISSUE THREAD

**Issue by ardenxu** [netdata/netdata#6473]
##### Question summary
we are using netdata's app plugin to monitor application running in container on K8S, the netdata's dashboard gives application's network data with open socket number.

We would have more data:
network: each port sending/receiving data sum, port connected number, and its related queue length.

https://github.com/netdata/netdata/issues/2174  raised similar request for network data related metrics,  but looks like did not implemented yet.  not sure if there is plugin/script available for such kind of metrics.

Thanks!

##### OS / Environment
centos7.2

##### Component Name
apps.plugin

**Comment by vlvkobal** [comment]
Related: #6215

**Comment by vlvkobal** [comment]
A simple answer to the question - you can't monitor these metrics at the moment.

If it comes to the implementation of this request, it's even more complicated than the one made in #6215 in terms of visualisation. How do you see the appearance of the charts in apps.plugin if there was a reasonable way to get the information?
