### ISSUE TITLE
Should this be raising an alarm?

### ISSUE THREAD

**Issue by tinyhammers** [netdata/netdata#6477]
Hey lovely humans...

I've got a question regarding disk space. 

According to this screenshot, it's at 87.7% and the badge is green, but it also says warning threshold is 80%-90%, so surely it should be orange and there should be an alarm?

<img width="862" alt="Screenshot 2019-07-17 at 09 45 54" src="https://user-images.githubusercontent.com/878379/61361616-a936e600-a878-11e9-9e2f-ce1eb3f44070.png">

Surely that's not right?

Thanks as always :)

**Comment by cakrit** [comment]
Please read https://docs.netdata.cloud/health/#special-use-of-the-conditional-operator
You'll get it! :)

**Comment by ilyam8** [comment]
Just a note, those conditionals are very hard to read for average (netdata) user. The representation is very low level.
