### ISSUE TITLE
Newby Questions  beware....

### ISSUE THREAD

**Issue by BR0KK** [netdata/netdata#6484]
Installed this on my ucs with docker and owncloud. 
I can access netdata via ip:19999 and it runs fine

The wiki states that i should give netdata access to my docker container. 
Since i'm a newb i im unable to do so becuse im stuck at this part: 

"Docker container names resolution"

Running this: grep docker /etc/group | cut -d ':' -f 3
Gives me the number 144 

Then the wiki tells me to ad this to my docker something

"2) Change docker socket access level to read/write like so: from

/var/run/docker.sock:/var/run/docker.sock:ro
change to

/var/run/docker.sock:/var/run/docker.sock:rw
"

Where do i add this number to now? 
Is this a file that im supposed to edit? 
Where is this located? 

Thx from a windows newb 

:)

**Comment by cakrit** [comment]
You can put that in your docker run command, using the `-v` option. i.e. `-v /var/run/docker.sock:/var/run/docker.sock:rw`

BUT, this is being changed right now in PR #6441, so that people don't have to give write access.
