### ISSUE TITLE
does netdata send data to any cloud environment?

### ISSUE THREAD

**Issue by techie879** [netdata/netdata#6486]
Hi, 

Just wanted to make sure if netdata reports systems data to any central repository in the cloud?  we are trying to make sure it does not report anything or send any information outside the organization?  if it's the case, how to turn it off? 

thanks.

**Comment by vlvkobal** [comment]
By default, only anonymous usage information is sent to the cloud. For more information on the issue, look at the following pages in the Netdata documentation:
[Anonymous Statistics](https://docs.netdata.cloud/docs/anonymous-statistics/)
[Registry](https://docs.netdata.cloud/registry/)
[Security design](https://docs.netdata.cloud/docs/netdata-security/)
