### ISSUE TITLE
Validate auto-detection jobs in "Gold OSs" in CI

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6488]
#### Feature idea summary
From #6295 
We need to validate our auto-detection for all monitored applications supported by us in what we'll call "Gold OSs" , i.e. LTS from Ubuntu, Debian, RHE, SuSE, CentOS. There will be some applications that we mark as community-supported, such as `freeipmi`.  

Note that we will need to extend in the future with Kubernetes auto-detection. 

##### Expected behavior
An automatically generated table with:
 - All applications in first column
 - Responsible collector in second column (e.g. go.d/xxx) 
 - Community-supported flag (Y/N) -> N means that we're responsible to test it and ensure auto-detection works
 - Two columns for each Gold OS: 
    - Autodected when netdata starts after the application (YES/NO), 
    - Autodetected when the application started after netdata (YES/NO).

##### How
- Automated testing mechanism to set up the environment and run the tests for each OS.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
