### ISSUE TITLE
Auto-detect previously running jobs after a system restart

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6489]
#### Bug report summary

As mentioned in #6295, netdata may not auto-detect all running applications after a system restart. For a quick win, we should be keeping track of which jobs were active before the last netdata restart. For those jobs only, we should retry for ~5 minutes, every 30 sec. 

- [X] python.d

- [X] go.d

- [ ] charts.d

- [ ] ????

##### Steps To Reproduce
system restart

##### Expected behavior
Collect metrics from applications started after netdata,  when we previously successfully collected data from them.

**Comment by ilyam8** [comment]
Do we need this for charts.d and ???? ? I am not sur about it

**Comment by ilyam8** [comment]
If no we can close since it is implemented for py and go

**Comment by cakrit** [comment]
I say we do it for bash, but not node.js. 
How about the C external collectors @vlvkobal ?

**Comment by vlvkobal** [comment]
Bash is soon-to-be deprecated, isn't it?

It doesn't make sense to do recheck for internal plugins. If it is somewhere, rechecking is done already.

External plugins:
- fping and ioping - they are configured or not, that's it
- apps plugin works anyway
- nfacct, ipmi, xenstat и slabinfo are enabled if relevant libraries are available
- ipmi - if it wasn't detected, it won't appear magically

If I missed anything, please correct me.

**Comment by cakrit** [comment]
cups?

**Comment by ilyam8** [comment]
I dont think we need it for bash and for `cups`. I would say it is not worth to spend time on it now. @stelfrag what is your plan?

**Comment by stelfrag** [comment]
My plan was to spend a bit of time to check that part of the code  understand it, and if possible do something about it. Of course plans can change and if you think it's not worth it,  I will will swap it out for something more useful.

**Comment by ilyam8** [comment]
The problem we wanted to solve is the problem with monitoring services (netdata service starts before some other service). Services are monitored by python/go modules. 

See https://github.com/netdata/netdata/issues/6489#issuecomment-535615140

Indeed, we could add this feature to `cups`, but common, this is very low priority imo.

**Comment by ilyam8** [comment]
This is not a `bug` btw, it was `feature request`.

**Comment by stelfrag** [comment]
Thank you @ilyam8 , I will close it today and replace it with something more useful!!

**Comment by stelfrag** [comment]
After discussion, I think we should not spend time on this, so I am closing it
