### ISSUE TITLE
MegaCLI plugin making me question my existence

### ISSUE THREAD

**Issue by tinyhammers** [netdata/netdata#6495]
Hello again, people...

I'm trying to get the MegaCLI plugin to work on Xen Server 7 (essentially CentOS)
I've added a job to the megacli.config here:
```
raidcheck:
  name : 'raid'
  update_every  : 1
  priority: 60000
  autodetection_retry: 0
```

I've run the debug with:
`/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace megacli` as user `netdata`

This is the output
```
2019-07-18 15:36:23: python.d INFO: plugin[main] : using python v2
2019-07-18 15:36:23: python.d INFO: plugin[main] : starting setup
2019-07-18 15:36:23: python.d INFO: plugin[main] : checking for config in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-07-18 15:36:23: python.d INFO: plugin[main] : config found, loading config '/usr/lib/netdata/conf.d/python.d.conf'
2019-07-18 15:36:23: python.d INFO: plugin[main] : config successfully loaded
2019-07-18 15:36:23: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
2019-07-18 15:36:23: python.d INFO: plugin[checker] : starting...
2019-07-18 15:36:23: python.d INFO: plugin[checker] : megacli : checking
2019-07-18 15:36:23: python.d INFO: plugin[checker] : megacli : source successfully loaded
2019-07-18 15:36:23: python.d INFO: plugin[checker] : megacli : disabled by default
2019-07-18 15:36:23: python.d INFO: plugin[checker] : terminating...
2019-07-18 15:36:23: python.d INFO: plugin[main] : stopping checker process
2019-07-18 15:36:23: python.d INFO: plugin[main] : no modules to run
DISABLE
```
As far as I can see this is OK, there's no errors, but it's not reporting on the dashboard.
Does this mean it's disabled?
` megacli : disabled by default`

I've checked in python.d.conf and uncommented megacli, even though it seems to be on by default.

Anyone know what I'm doing wrong?

Thanks

**Comment by ilyam8** [comment]
Hey @tinyhammers 	

> I've checked in python.d.conf and uncommented megacli, even though it seems to be on by default.

There?
> /usr/lib/netdata/conf.d/python.d.conf

**Comment by ilyam8** [comment]
> Does this mean it's disabled?
> megacli : disabled by default

Yes, you need to explicitly enable the collector.

`# megacli: yes`
=>
`megacli: yes`

**Comment by tinyhammers** [comment]
Hey guys, 

Jacking my own closed thread here, but now I have another fun and exciting error.
CAVEAT: This might not actually be a Netdata issue, it may be a lack of understanding of Linux, but I'd just like to check if that's OK.

Job is setup
` RAID check:

     name: RAID check        # the JOB's name as it will appear at the
                             # dashboard (by default is the job_name)
                             # JOBs sharing a name are mutually exclusive
     update_every: 1         # the JOB's data collection frequency
     priority: 60000         # the JOB's order on the dashboard
     penalty: yes            # the JOB's penalty
     autodetection_retry: 0  # the JOB's re-check interval in seconds
     do_battery: yes`

I have added the netdata user to the sudoers file
`netdata ALL=NOPASSWD:/opt/MegaRAID/MegaCli/megacli`

If I switch to the netdata user (`su -s /bin/bash netdata`) and run `sudo -n megacli -LDPDInfo -aAll` I get the output that I was expecting

`Adapter #0

Number of Virtual Disks: 1
Virtual Drive: 0 (Target Id: 0)
Name                :
RAID Level          : Primary-1, Secondary-0, RAID Level Qualifier-0
Size                : 1.818 TB
State               : Degraded
Stripe Size         : 256 KB
Number Of Drives per span:2
Span Depth          : 2
Default Cache Policy: WriteThrough, ReadAhead, Direct, No Write Cache if Bad BBU
Current Cache Policy: WriteThrough, ReadAhead, Direct, No Write Cache if Bad BBU
Access Policy       : Read/Write
Disk Cache Policy   : Enabled
Encryption Type     : None
Bad Blocks Exist: No
Number of Spans: 2
Span: 0 - Number of PDs: 2`

It doesn't prompt me for a password, so it seems the stuff in `/etc/sudoers` is correct.

However.... when I try to test the plugin by running
`/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace megacli`
I get `python.d ERROR: megacli[RAID_check] : sudo: a password is required`

I'm really not sure what I'm missing here. As far as I understand I can run those commands using `sudo` without a password, yet Netdata seems to feel differently.

Any ideas what I've done wrong?

A lorry load of thanks, as always 😃

**Comment by ilyam8** [comment]
> I get python.d ERROR: megacli[RAID_check] : sudo: a password is required

> sudo: a password is required

i see module executes following commands:
 - `sudo -n -v` (only once during check)
 - `sudo -n megacli -LDPDInfo -aAll -NoLog`
 - `sudo -n megacli -AdpBbuCmd -a0 -NoLog` (battery metrics)

> -v, --validate
                 Update the user's cached credentials, authenticating the user if
                 necessary.  For the sudoers plugin, this extends the sudo timeout
                 for another 15 minutes by default, but does not run a command. 
                 Not all security policies support cached credentials.

**Comment by ilyam8** [comment]
some of those commands fails with `sudo: a password is required`

**Comment by tinyhammers** [comment]
Hey @ilyam8 

Those commands run fine. 
The netdata user doesn't have a password set, so I ran `passwd netdata` to set a password for it, and this seems to have solved the the problem I reported, now there's another one. 😃

Now I get `python.d ERROR: megacli[RAID_check] : failed to parse "/bin/sudo -n /opt/MegaRAID/MegaCli//megacli -AdpBbuCmd -a0 -NoLog" output`.

This looks to be a similar error to the one reported on #4278. I've checked the solution for that in `/usr/libexec/netdata/python.d/megacli.chart.py` and it is already set to `r'Adapter #([0-9]+) State(?:\s+)?: ([a-zA-Z]+)'` so clueless as to where to go next.

**Comment by ilyam8** [comment]
@tinyhammers please make sure your netdata version is latest

If it is and problem exist i suggest to open an issue

**Comment by tinyhammers** [comment]
OK, will do. Thanks.
