### ISSUE TITLE
Custom dashboard - legend labels missing

### ISSUE THREAD

**Issue by iandk** [netdata/netdata#6506]
##### Bug report summary
When creating a custom dashboard, I noticed, that the labels of the legend is missing.
E.g. "user, nice, iowait"

Normal dashboard WITH titles:
<img width="1810" alt="Bildschirmfoto 2019-07-19 um 23 33 26" src="https://user-images.githubusercontent.com/13487247/61566924-08197c80-aa7e-11e9-9018-befe27900648.png">

Custom dashboard WITHOUT titles:
<img width="1336" alt="Bildschirmfoto 2019-07-19 um 23 34 24" src="https://user-images.githubusercontent.com/13487247/61566938-16679880-aa7e-11e9-8abd-4ac4a83f0641.png">

##### OS / Environment
Debian 9

##### Netdata version (ouput of `netdata -V`)
netdata v1.16.0-61-nightly

##### Component Name
All components

##### Steps To Reproduce
`<div data-host="http://mydomain.io:19999/" data-title="CPU usage" data-netdata="system.cpu"
            data-height="200px"></div>`

##### Expected behavior
Display labels

**Comment by cakrit** [comment]
I can't replicate this behavior. All I put in a custom html file is shown below and it works fine:
```
<html lang="en">
<script>
var netdataTheme = 'slate'; // this is dark
</script>
<script type="text/javascript" src="dashboard.js?v20170724-7"></script>
<body>
<div data-host="http://localhost:19999/" data-title="CPU usage" data-netdata="system.cpu" data-height="200px"></div>
</body>
</html>
```

Can you please provide info on your browser, the complete custom html you created and any browser console errors you may have?

**Comment by ilyam8** [comment]
I am closing the issue since @iandk didnt answer
