### ISSUE TITLE
Add support for other TLS/SSL libraries than OpenSSL

### ISSUE THREAD

**Issue by BKPepe** [netdata/netdata#6509]
##### Feature idea summary

OpenWrt aims for minimalistic devices even for their upcoming release (OpenWrt 19.07) they still count with support for routers with 4 MB / 32 MB. They are using mbedTLS which is designed to fit on small embedded devices. For these small devices, I can not provide a new version as since netdata version 1.15, there is a new database engine, which requires [OpenSSL](https://github.com/netdata/netdata/blob/master/configure.ac#L345). I don't own any such of those small devices, but some people might do like @diizzyy, who helps me with keeping netdata up-to-date in OpenWrt. Current idea is to have two packages of Netdata in OpenWrt.  (netdata-legacy = 1.14 for those small devices, which will be supported approx for a year and then netdata, the latest one)

##### Expected behavior

- Add support at least for mbed TLS in Netdata.

What is a disadvantage of mbed TLS that there is not support for TLS 1.3, yet. While wolfSSL supports it.

**Comment by cakrit** [comment]
Small devices should be running without the dbengine. The netdata instances on those devices should be streaming metrics to other netdata for long-term storage. @paulkatsoulakis on that sheet we have in #6300 we should also mention how one could remove a particular dependency, when they don't want the installation to include it. We already have several such flags, we may need to add more. 

The other TLS libraries do make sense for the SSL support though, so we should do the work anyway.

**Comment by Ferroin** [comment]
Unless I'm mistaken, the dbengine is completely independent of OpenSSL.  If it isn't, it should be, as it isn't doing any encryption.

As far as alternate TLS implementations, mbed should indeed be on the list, and I'd argue that verifying against LibreSSL should be there too (I'm 99% certain from a quick look at what we're using that LibreSSL will work (provided of course that the headers match up properly), but having some level of official support would be good).  GnuTLS and NSS would be nice to have in terms of flexibility, but not critical.  Also, if we're looking at Windows support, we should probably eventually support SChannel (the TLS implementation provided as part of Windows).

**Comment by mfundul** [comment]
> 
> 
> Unless I'm mistaken, the dbengine is completely independent of OpenSSL. If it isn't, it should be, as it isn't doing any encryption.

It's just using the cryptographic SHA functions.

**Comment by Ferroin** [comment]
@mfundul OK, potentially stupid question: Why are we using a crypto hash for a non-cryptographic purpose?  I mean, I would assume we're using it as part of some sort of hash table structure, or for integrity checking the files on disk when we load them, both of which don't _need_ crypto-grade hashes.

**Comment by mfundul** [comment]
> 
> 
> @mfundul OK, potentially stupid question: Why are we using a crypto hash for a non-cryptographic purpose? I mean, I would assume we're using it as part of some sort of hash table structure, or for integrity checking the files on disk when we load them, both of which don't _need_ crypto-grade hashes.

For the same reason it's used in deduplication solutions, to guarantee practically no collisions for deterministic UUID generation.

**Comment by Ferroin** [comment]
Ah, OK, I didn't realize we were using UUID's internally in the dbengine backend.

Might be worth considering the option of just using libuuid on Linux systems for that, as that would allow people to build Netdata on Linux without it depending on any SSL/TLS library.

**Comment by mfundul** [comment]
> 
> 
> Ah, OK, I didn't realize we were using UUID's internally in the dbengine backend.
> 
> Might be worth considering the option of just using libuuid on Linux systems for that, as that would allow people to build Netdata on Linux without it depending on any SSL/TLS library.

That is the plan for the current [design](https://github.com/netdata/netdata/issues/4687#issuecomment-458504481), but until we put some data structures in place (e.g. metrics map) to handle random UUIDs we are stuck with uniquely mapping netdata chart/dimension identifiers to UUIDs.

**Comment by mfundul** [comment]
In any case, dbengine is not a hard requirement to compile the actual code itself. `./configure` should proceed without problems without dbengine dependencies and it should produce a binary with no dbengine support.

It can even be explicitly ran like this `./configure --disable-dbengine`.

**Comment by BKPepe** [comment]
I think there was no change since I reported this issue, right? OpenWrt is now using WolfSSL by default instead of MbedTLS and would be good if there is support for it as well instead of relying only on OpenSSL.

**Comment by dim08** [comment]
@thiagoftsm please do so

**Comment by thiagoftsm** [comment]
Hello everybody, 

I made the PR that will bring support for `WolfSSL`, but I observed that when `libwebsockets` is compiled against `WolfSSL`, it does not recognize some functions that `WolfSSL` has, this means that the `cloud` is a function that is not available when it is used. :disappointed: 

I will take a look later to verify if a patch to `libwebsockets` can fix this problem.

Best regards!

**Comment by underhood** [comment]
@thiagoftsm we are planning the ACLK-NG that will not need libwebsockets.

**Comment by thiagoftsm** [comment]
> @thiagoftsm we are planning the ACLK-NG that will not need libwebsockets.

Thanks for the update @underhood ! I won't expend time trying to fix the wolfssl compilation against `libwebsockets` considering that we won't need it.

**Comment by ktsaou** [comment]
With PR #15113 we re-wrote and abstracted the entire SSL support in netdata. Using the new code, it is much easier to have different ssl implementations in Netdata.
