### ISSUE TITLE
netdata package maintainers

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#651]
# This issue has been converted to a wiki page

For the latest info check it here: https://github.com/firehol/netdata/wiki/netdata-package-maintainers

---

I think it would be useful to prepare a wiki page with information about the maintainers of netdata for the Linux distributions, automation systems, containers, etc.

Let's see who is who:

---
## Official Linux Distributions

| Linux Distribution | Netdata Version | Maintainer | Related URL |
| :-: | :-: | :-: | :-- |
| Arch Linux | Release | @svenstaro | [netdata @ Arch Linux](https://www.archlinux.org/packages/community/x86_64/netdata/) |
| Arch Linux AUR | Git | @sanskritfritz | [netdata @ AUR](https://aur.archlinux.org/packages/netdata-git/) |
| Gentoo Linux | Release + Git | @candrews | [netdata @ gentoo](https://github.com/gentoo/gentoo/tree/master/net-analyzer/netdata) |
| Debian | Release | @lhw @FedericoCeratto | [netdata @ debian](https://anonscm.debian.org/git/collab-maint/netdata.git) |
| Slackware | Release | @willysr | [netdata @ slackbuilds](https://slackbuilds.org/repository/14.2/system/netdata/)
| Ubuntu |  |  |  |
| Red Hat / Fedora / Centos |  |  |  |
| SuSe / openSuSe |  |  |  |

---
## FreeBSD

System|Initial PR|Core Developer|Package Maintainer
|:-:|:-:|:-:|:-:|
FreeBSD|#1321|@vlvkobal|@mmokhi

---
## MacOS

System|URL|Core Developer|Package Maintainer
|:-:|:-:|:-:|:-:|
MacOS Homebrew Formula|[link](https://github.com/Homebrew/homebrew-core/blob/master/Formula/netdata.rb)|@vlvkobal|@rickard-von-essen

---
## Unofficial Linux Packages

| Linux Distribution | Netdata Version | Maintainer | Related URL |
| :-: | :-: | :-: | :-- |
| Ubuntu | Release | @gslin | [netdata @ gslin ppa](https://launchpad.net/~gslin/+archive/ubuntu/netdata) https://github.com/firehol/netdata/issues/69#issuecomment-217458543 |

---
## Embedded Linux

| Embedded Linux | Netdata Version | Maintainer | Related URL |
| :-: | :-: | :-: | :-- |
| ASUSTOR NAS | ? | William Lin | https://www.asustor.com/apps/app_detail?id=532 |
| OpenWRT | Release | @nitroshift | [openwrt package](https://github.com/openwrt/packages/tree/master/admin/netdata) |
| ReadyNAS | Release | @NAStools | https://github.com/nastools/netdata |
| QNAP | Release | QNAP_Stephane | https://forum.qnap.com/viewtopic.php?t=121518 |
| DietPi | Release | @Fourdee | https://github.com/Fourdee/DietPi |

---
## Linux Containers

| Containers | Netdata Version | Maintainer | Related URL |
| :-: | :-: | :-: | :-- |
| Docker | Git | @titpetric | https://github.com/titpetric/netdata |

---
## Automation Systems

| Automation Systems | Netdata Version | Maintainer | Related URL |
| :-: | :-: | :-: | :-- |
| Ansible | git | @jffz | https://galaxy.ansible.com/jffz/netdata/ |
| Chef | ? | @sergiopena | https://github.com/sergiopena/netdata-cookbook |

---

If you know other maintainers of distributions that should be mentioned, please help me complete the list...

cc: @mcnewton @philwhineray @alonbl @simonnagl @paulfantom

**Comment by candrews** [comment]
You can set the "Related URL" for Gentoo to https://github.com/gentoo/gentoo/tree/master/net-analyzer/netdata

**Comment by ktsaou** [comment]
> You can set the "Related URL" for Gentoo to https://github.com/gentoo/gentoo/tree/master/net-analyzer/netdata

Thanks! Done.

**Comment by jasonwbarnett** [comment]
@ktsaou It should probably be:

Redhat == CentOS (just rebranded and a few other nuances)
Fedora is where things are tested before being released to Redhat/CentOS

RHEL/CentOS
Fedora

**Comment by ktsaou** [comment]
> RHEL == CentOS (just rebranded and a few other nuances)

ok, fixed that. Although there are differences. I decided to treat separately when I found this: https://github.com/firehol/netdata-demo-site/blob/28c7962d28a942c5321e8475f51d5b17dd48a884/install-required-packages.sh#L653

**Comment by ktsaou** [comment]
I meant this: https://github.com/firehol/netdata-demo-site/blob/28c7962d28a942c5321e8475f51d5b17dd48a884/install-required-packages.sh#L613-L616

**Comment by NAStools** [comment]
I'm maintaining a version of netdata for NETGEAR ReadyNAS @ https://github.com/nastools/netdata

**Comment by ktsaou** [comment]
> I'm maintaining netdata for NETGEAR ReadyNAS

nice. Thank you!

Please make sure the directory `/var/lib/netdata/registry` is empty on your distribution package. There is an embedded devices package that distributes netdata with the unique id file pre-installed. This makes all these netdata installations appear as the same one to the global registry..

**Comment by jasonwbarnett** [comment]
> ok, fixed that. Although there are differences. I decided to treat separately when I found this: https://github.com/firehol/netdata-demo-site/blob/28c7962d28a942c5321e8475f51d5b17dd48a884/install-required-packages.sh#L653

I just submitted a PR to correct that repo. Not sure who put those packages in the repo, but they're wrong.

**Comment by NAStools** [comment]
> Please make sure the directory /var/lib/netdata/registry is empty on your distribution package.
I'm building with [dh-autoreconf](https://github.com/NAStools/netdata/blob/master/debian/rules) and don't end up with a registry directory.  Do I need to be including this?
```
root@readynas:/apps/nastools-netdata# find . -name registry
root@readynas:/apps/nastools-netdata#
```

**Comment by ktsaou** [comment]
> I'm building with dh-autoreconf and don't end up with a registry directory. Do I need to be including this?

The installation should only create `/var/lib/netdata`. The rest are created by netdata itself. It is ok.

**Comment by FedericoCeratto** [comment]
Can you please add https://anonscm.debian.org/git/collab-maint/netdata.git for Debian (and maybe put in my name as well?) Thanks

**Comment by ktsaou** [comment]
> Can you please add https://anonscm.debian.org/git/collab-maint/netdata.git for Debian (and maybe put in my name as well?) Thanks

done. thanks!

I would love  to provide a binary package and probably a PPA for users to install it easily on debian based distributions, until the distros include it.  I am completely ignorant of the procedure - I have tried to do it a few times, but it is totally counter-intuitive for me. Can you help me?

**Comment by ktsaou** [comment]
oh! I replaced @lhw with @FedericoCeratto . Do you want me to add @lhw back, to list both of you?

**Comment by FedericoCeratto** [comment]
@ktsaou we are both maintaining the package and lhw did a lot of work :)

**Comment by ktsaou** [comment]
Added @lhw back, together with you.

**Comment by jffz** [comment]
Just updated the ansible role and uploaded it into ansible galaxy.

You can retrieve the whole playbook here : https://galaxy.ansible.com/jffz/netdata/

Direct usage with ansible-galaxy: `ansible-galaxy install jffz.netdata`

**Comment by ktsaou** [comment]
updated the link above to point to https://galaxy.ansible.com/jffz/netdata/

**Comment by jffz** [comment]
Maybe you can delete "
https://github.com/jffz/ansible-netdata/blob/master/tasks/main.yml" to
avoid any mistake.


________________

BACHELOT *Geoffrey*
*Tel:* *+33 6 19 44 00 42 <%2B33%206%2019%2044%2000%2042>*
*Mail:* *bachelotg@gmail.com <bachelotg@gmail.com>*

2016-10-17 12:43 GMT+02:00 Costa Tsaousis <notifications@github.com>:

**Comment by ktsaou** [comment]
You mean https://github.com/firehol/netdata/blob/master/ansible/netdata.yml ?

**Comment by jffz** [comment]
yeah sorry, i pasted a wrong link

**Comment by ktsaou** [comment]
done is #1123

**Comment by thinrope** [comment]
I have been (trying to) following the (amazing amount of) development in this project... Quite a few new features were merged (fping, DBs, external backend come to mind), is there any timeframe for a new release?
It will help iron out a few more things, without having "old" users complain like when they had to switch between gnome2/3 or WinXP/7 :-)

**Comment by ktsaou** [comment]
I think in 1-2 weeks v1.5 will be out.
We need some time to test all new features.

**Comment by ktsaou** [comment]
Dear all, netdata v1.5.0 has been released!

**Comment by candrews** [comment]
Should be in Gentoo shortly: https://github.com/gentoo/gentoo/pull/3607

**Comment by ktsaou** [comment]
hm... I see it searches for the URL at firehol.org but @philwhineray has moved everything to github.

@philwhineray also, since travis failed to create the tar files, can I create them by hand and upload them to github? If that is too hard, I'll release 1.5.1 shortly to have the packages generated...

**Comment by philwhineray** [comment]
Hopefully the redirects from the website take care of it for most people.

Creating the packages by hand should not be hard. Just checkout the tag, run the `fakeroot ./packaging/git-build` step from .travis.yml and upload the tar-files that are created manually.

**Comment by philwhineray** [comment]
I am going to be out for the next hour or two but after that, if you are struggling, let me know and I will create them and do the upload. I think you will find it easy though, you just need to have the dependent library headers and fakeroot command.

**Comment by FedericoCeratto** [comment]
@ktsaou thanks for the reminder! Looks like something is different in the tarball signing: the signature file is not published anymore at https://github.com/firehol/netdata/releases/ - is that on purpose?

**Comment by ktsaou** [comment]
ok, I have the packages. I am uploading them now.
Is there another procedure to sign them?

**Comment by FedericoCeratto** [comment]
Perhaps something changed on GH? If you curl | grep you'll see asc files for previous releases:
curl https://github.com/firehol/netdata/releases/ | grep '\.tar\.gz\.asc'

**Comment by ktsaou** [comment]
Uploaded. 

@FedericoCeratto: Phil changed the release procedure to have travis create the files of the release. There was an issue and this broke in the middle. I have uploaded the files now, but there might be something more missing to upload the signature files and possibly update the firehol.org site for the release.

I think @philwhineray will help us complete the release in a while...

**Comment by philwhineray** [comment]
OK, so the travis would also normally do checksums and upload them i.e.:

~~~~
for i in *.tar.*; do md5sum -b $i > $i.md5; sha512sum -b $i > $i.sha
~~~~

The signing is always a separate step to ensure what went in the package is what was in git. On yout machine, In the `firehol/infrastructure` repo do this:

~~~~
./bin/sign-github-release netdata 1.5.0
~~~~

It should download the packages, check they are OK then ask for your gpg key password to sign, then upload the .asc files using the token you previously set up in `~/.firehol-github-oauth`.

**Comment by philwhineray** [comment]
Also, I put a helper script in there:

`./bin/upload-github-asset` which might be quicker than uploading all the checkums by hand:

~~~~
./bin/upload-github-asset netdata 1.5.0 *.md5 *.sha
~~~~

**Comment by philwhineray** [comment]
For future reference, the [infrastructure repo readme](https://github.com/firehol/infrastructure#readme) documents this and most of the other things I have set up, just in case the proverbial bus hits me.

**Comment by ktsaou** [comment]
@philwhineray :

```
firehol-infrastructure.git $ ./bin/sign-github-release netdata 1.5.0
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

?

**Comment by philwhineray** [comment]
Sorry, it needs to be:

~~~~
./bin/sign-github-release netdata v1.5.0
~~~~

i.e. the full tag name

**Comment by ktsaou** [comment]
ok. done!
Thanks @philwhineray !
(have a look, everything should be ok now)

**Comment by philwhineray** [comment]
Looks OK to me!

**Comment by ktsaou** [comment]
netdata at freeports: http://www.freshports.org/net-mgmt/netdata/
@vlvkobal Wow!

**Comment by ktsaou** [comment]
@mmokhi I believe you submitted netdata to freeports. If yes, first of all, **thank you**, next I would like to add you to this issue as the maintainer for freebsd. Do you agree?

**Comment by mmokhi** [comment]
@ktsaou Hey, my pleasure to help.
Sure I'll agree. :smile: I think it'll help me to connect with related people sooner and discover bugs/updates easier :wink:

**Comment by ktsaou** [comment]
ok. nice. I added you.

**Comment by mmokhi** [comment]
Thanks :smile: :+1:

**Comment by FedericoCeratto** [comment]
@ktsaou the .asc signature file for 1.6.0 is still missing from https://github.com/firehol/netdata/releases
The URL should be https://github.com/firehol/netdata/releases/download/v1.6.0/netdata-1.6.0.tar.xz.asc

**Comment by ktsaou** [comment]
hm... @philwhineray any ideas?

**Comment by philwhineray** [comment]
Well package uploads are automatic but you still have to run the signature
script by hand. Did that get done?

**Comment by ktsaou** [comment]
> Well package uploads are automatic but you still have to run the signature
> script by hand. Did that get done?

Forgive me... I missed that detail.
How do I do that?

**Comment by philwhineray** [comment]
I think the infrastructure repo readme has the details.

Apologies: I am on phone email only so I can't check the details.

**Comment by ktsaou** [comment]
ok, let me check... thanks!

**Comment by ktsaou** [comment]
done!

@philwhineray thank you for your help (yeap, the docs are clear)!

@FedericoCeratto thank you for bringing this to my attention. I completely missed this detail.

**Comment by ktsaou** [comment]
I have released netdata v1.7.0
Please update your repos/distros.

**Comment by mmokhi** [comment]
Already done :wink: :smile: 

https://svnweb.freebsd.org/ports?view=revision&revision=446144

**Comment by nitroshift** [comment]
As you're probably aware, OpenWRT is in the process of merging with LEDE project. Until the repositories are merged there will be no changes in the code, unless security related. Thanks for your understanding.

nitroshift

**Comment by ktsaou** [comment]
Hi all,

I have just released netdata v1.8.0
Please update your packages.
Thanks!

**Comment by candrews** [comment]
1.8.0 is in Gentoo: https://github.com/gentoo/gentoo/commit/55c3ec1b2cb2ad736f9da9a6d53861e31346d761

**Comment by lhw** [comment]
1.8.0 is up in debian shortly: https://tracker.debian.org/news/873552

**Comment by mmokhi** [comment]
Sorry for delay :wink: took a little long to review :smile: but finally landed :wink:

**Comment by ktsaou** [comment]
@mmokhi thanks!

A [folk on reddit says](https://www.reddit.com/r/freebsd/comments/70uj2d/netdata_the_opensource_realtime_performance_and/dnhjqff/?context=3) the [freebsd port for netdata v1.8.0 is broken](http://portsmon.freebsd.org/portoverview.py?category=net-mgmt&portname=netdata&wildcard=).

**Comment by mmokhi** [comment]
Yeh,
Fix was committed moment ago  :smile:  https://svnweb.freebsd.org/changeset/ports/450630

**Comment by magao** [comment]
You might want to reach out to `QNAP_Stephane` who posts builds at https://forum.qnap.com/viewtopic.php?t=121518 (and to QNAP Club) and see if they want to be listed as a maintainer.

Speaking of which, time to update my QNAPs.

**Comment by ktsaou** [comment]
Hi all,

I have just released netdata v1.9.0
Please update your packages.
Thanks!

**Comment by willysr** [comment]
Hi,

I maintain netdata SlackBuild script for Slackware. We rely on released tarball
https://slackbuilds.org/repository/14.2/system/netdata/

**Comment by ktsaou** [comment]
@willysr thank you! I added you to the list at the top.

**Comment by ktsaou** [comment]
Hi all,

netdata v1.10.0 has just been released!
Please update your packages.

cc: @svenstaro @SanskritFritz @candrews @lhw @FedericoCeratto @willysr @vlvkobal @mmokhi @gslin @nitroshift @NAStools @titpetric @jffz @sergiopena @mcnewton @philwhineray @alonbl @simonnagl @paulfantom @l2isbad

**Comment by FedericoCeratto** [comment]
The Debian package for v1.10.0 is almost ready.

**Comment by svenstaro** [comment]
Done.

**Comment by FedericoCeratto** [comment]
@ktsaou the python.d/python_modules/urllib3/packages/six.py is not part of the urllib3 and it's not listed in LICENSE-REDISTRIBUTED.md

**Comment by ktsaou** [comment]
> @ktsaou the python.d/python_modules/urllib3/packages/six.py is not part of the urllib3 and it's not listed in LICENSE-REDISTRIBUTED.md

oops! I didn't know that. @l2isbad do we need this file? If yes, we should add it to the license. If not, we should remove it.

**Comment by l2isbad** [comment]
> do we need this file?

<details><summary>i think yes</summary>

```python
[/opt/netdata/usr/libexec/netdata/python.d/python_modules/urllib3]grep -R "from .*six *"
filepost.py:from .packages import six
filepost.py:from .packages.six import b
connection.py:from .packages import six
connection.py:from .packages.six.moves.http_client import HTTPConnection as _HTTPConnection
connection.py:from .packages.six.moves.http_client import HTTPException  # noqa: F401
fields.py:from .packages import six
connectionpool.py:from .packages import six
connectionpool.py:from .packages.six.moves import queue
util/response.py:from ..packages.six.moves import http_client as httplib
util/retry.py:from ..packages import six
util/request.py:from ..packages.six import b, integer_types
_collections.py:from .packages.six import iterkeys, itervalues, PY3
packages/six.py:    """Remove item from six.moves."""
response.py:from .packages.six import string_types as basestring, binary_type, PY3
response.py:from .packages.six.moves import http_client as httplib
contrib/pyopenssl.py:    from ..packages import six
contrib/appengine.py:from ..packages.six.moves.urllib.parse import urljoin
contrib/appengine.py:from ..packages.six import BytesIO
contrib/ntlmpool.py:from ..packages.six.moves.http_client import HTTPSConnection
poolmanager.py:from .packages.six.moves.urllib.parse import urljoin
exceptions.py:from .packages.six.moves.http_client import (
request.py:from .packages.six.moves.urllib.parse import urlencode
```

</details>

**Comment by willysr** [comment]
Slackware SlackBuild script has been updated and it will be part for this weekend's public update.

Thanks :)

**Comment by ktsaou** [comment]
> @ktsaou the python.d/python_modules/urllib3/packages/six.py is not part of the urllib3 and it's not listed in LICENSE-REDISTRIBUTED.md

added it with PR #3586 
thank you for letting me know...

**Comment by titpetric** [comment]
Done, hub version is published. Next/docker image will replace ssmtp most likely (a PR is in the works), so there will be some changes regarding readme and such.

**Comment by FedericoCeratto** [comment]
This might be useful: https://repology.org/metapackage/netdata/badges  :)

**Comment by rickard-von-essen** [comment]
Add macOS [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/netdata.rb).

**Comment by ktsaou** [comment]
> Add me as macOS Homebrew formula.

added you. Thank you for supporting netdata!

**Comment by ktsaou** [comment]
If you know who is the netdata package maintainer for alpine, please invite him here. It seems the latest package on alpine is broken #3897

**Comment by rickard-von-essen** [comment]
Alpine Linux netdata package source: https://git.alpinelinux.org/cgit/aports/log/?qt=grep&q=Netdata

**Comment by rickard-von-essen** [comment]
[netdata/APKBUILD](https://git.alpinelinux.org/cgit/aports/tree/testing/netdata/APKBUILD?id=2c4bd574a759f519863f3276086ac04d1fa15ec9) 

```shell
# Contributor: Carlo Landmeter <clandmeter@gmail.com> 
# Maintainer:
```

**Comment by ktsaou** [comment]
nice finding!

@clandmeter are the netdata package maintainer for alpine?

**Comment by paulfantom** [comment]
@ktsaou is list of maintainers from https://github.com/firehol/netdata/issues/651#issue-163803641 is up to date? I am currently in process of writing new ansible role for netdata as I've tried @jffz one some time ago, but he is unresponsive and my PRs are waiting and waiting. I want to include option to install netdata not only from source (I don't want to install build tools on multiple servers), but also from pre-built repository packages. While writing I need to checked some of  those repos, and alternative ones as I want to support systems I usually support with my roles:
 - Ubuntu 16.04 & 18.04
 - Debian 8 & 9
 - CentOS 7
 - Fedora 27

What I found:
 - "Related URL" for debian official distro doesn't work
 - debian 8 doesn't have netdata included, so the table is a bit misleading
 - Fedora and CentOS have natdata packages (1.10) in copr (https://copr.fedorainfracloud.org/coprs/baoboa/netdata/ and https://copr.fedorainfracloud.org/coprs/tartare/netdata/), maybe consider adding them?
 - there is actually an official package for netdata (1.9.0) in ubuntu 18.04 maintained by @lhw, at least that's what `apt show netdata` says

There are possibly more things lacking, but I found that in current state it si impossible to support all those repo combinations in one ansible role, so I decided to use official releases and install it all by myself with ansible. Hopefully it will be ready soon and we all be able to install netdata faster on multiple devices at once (compile on one device - install on many). :smile:

**Comment by lhw** [comment]
@paulfantom If you want to check debian package status it's actually easier to just go to the package tracker: https://tracker.debian.org/pkg/netdata 
So for now its up-to-date but you are right it's not in debian 8 at least not officially and even in debian 9 it's only in the backports. And Ubuntu packages are simply pulled from debian testing which was 1.9.0 at the time.

@ktsaou The URL for debian has changed as debian switched to gitlab its now http://salsa.debian.org/debian/netdata

**Comment by ktsaou** [comment]
ok guys I converted this to a wiki page: https://github.com/firehol/netdata/wiki/netdata-package-maintainers

So, feel free to edit it to reflect the current status.

**Comment by ktsaou** [comment]
updated also the original post to divert to the wiki.

**Comment by paulfantom** [comment]
Wiki page is now at https://github.com/netdata/netdata/wiki/netdata-package-maintainers.

Closing as this information is tracked in wiki.

**Comment by paulfantom** [comment]
@lhw @FedericoCeratto do you need GPG signature for tar packages of netdata? If yes, why?

**Comment by FedericoCeratto** [comment]
@paulfantom the signature is optional and it's meant to ensure the authenticity and integrity of the tarball

**Comment by paulfantom** [comment]
Great! :+1: So it is not crucial if you are downloading from github via HTTPS. In such scenario source authenticity is achieved by downloading using github and transport security is achieved by using HTTPS. And if someone would gain access to our code on github, then GPG signature won't prevent anything since archive signing is in travis.

**Comment by FedericoCeratto** [comment]
HTTPS provides limited security (there has been many issues) and only for data in transit (not at rest). GPG signatures from Travis or other 3rd party services are not accepted - the tarball has to be signed directly by the author.

**Comment by philwhineray** [comment]
The GPG signatures are only on source files and are currently provided directly by an author.

I don't have a strong view about what happens going forwards but for reference, the current process is:

1. a GPG-signed tag is created
2. this is checked by the travis build. it does not add anything directly but just makes sure later steps should work
3. a script, `sign-github-release` from the firehol/infrastructure repo is run on the developer's machine where signing will take place. This takes a clean copy of the repo and checks the source signature. If then downloads the release source tar from github and if the contents match, prompts the dev to sign. It then uploads the signature back to the github release.

If you are thinking to replace the tagging with a system which does so automatically, e.g. based on the content of a PR, I think the signatures can still be produced without opening much of a hole.

The script in (3) would need to be updated not look for a signature, and any manual checks that the tag is good move from before tagging (otherwise the git gpg signature did nothing anyway) to after.

I should note as well at this point that the checks in said script are not perfect. They don't check files added by Travis since we have no way to independently verify them, much as with binary output. The key suspects I would suggest are those produced by autoconf/automake, so if you distrust Travis, or the possibility that the tar could be interfered with between upload by travis and download for checking before signing, whilst the sources should be sound, running `autoreconf` in your own trusted environment would be a good idea.

**Comment by philwhineray** [comment]
Source tar signatures could still be produced without changing much that is. I'm not suggesting signed tags from Travis, to be clear.

**Comment by candrews** [comment]
Well, it's already in Gentoo: https://github.com/gentoo/gentoo/tree/master/net-analyzer/netdata
