### ISSUE TITLE
Disk utilization percentage over 100%

### ISSUE THREAD

**Issue by johnramsden** [netdata/netdata#6510]
##### Question summary

From what I understand about disk utilization, and it being a percentage of time, it shouldn't go over 100%. Either I am misunderstanding what this metric means, or there is a bug.

I've been getting alerts extremely high percentages of disk utilization. For example today:

> 10min disk utilization = 715828% 
> the percentage of time the disk was busy, during the last 10 minutes

I have been getting this alert along with a disk backlog alert.

> 10min disk backlog = 715829 ms 
> average of the kernel estimated disk backlog, for the last 10 minutes

##### OS / Environment

Ubuntu 18.04, netdata v1.16.0-70-nightly

##### Component Name

health

##### Expected results

Percentage of time <= 100%.

**Comment by vlvkobal** [comment]
How often do you get the alerts? Was it just once in a prolonged period of time? How does it look like on the charts?

**Comment by mfundul** [comment]
What `memory mode` are you using?

**Comment by cakrit** [comment]
Let's continue on #6511 please, it looks like under certain, conditions there's an issue with `proc` stats in Ubuntu 18.04

**Comment by mfundul** [comment]
Did you install netdata in a container, or is it installed natively in the host? Is this host a VM or a bare metal machine?

**Comment by vlvkobal** [comment]
@johnramsden Please make a Netdata snapshot for a timeframe, which includes the spikes, and then send it to vlad@netdata.cloud.
