### ISSUE TITLE
Netdata throwing super high CPU usage and load alarms.

### ISSUE THREAD

**Issue by fulcrum29** [netdata/netdata#6511]
I have 8 netdata instances in LXC containers, host ubuntu 18.04  - 1 master/ 7 slaves (memory mode map). One of the slaves was throwing super high CPU alarms, I disabled it and now it occured on the other slave also with load alarm.
From my discord:
`pr-main is critical, system.cpu (cpu), 10min cpu usage = 7626516%`
`pr-main is critical, system.load (load), load average 1 = 737761900000 load`
Netdata version - v1.16.0-70-nightly ( and previous versions as well )

**Comment by mfundul** [comment]
What `memory mode` are you using?

**Comment by fulcrum29** [comment]
> edit: Is this what you mean `map`?
Yes, I use `map` memory option.

**Comment by mfundul** [comment]
Do you see the same problem when observing the chart itself in the dashboard, or is it only an issue with the alarm?

**Comment by cakrit** [comment]
Do you also see insane numbers in disk utilization? See #6510. 
Same question as @vlvkobal 's  #6510:

> How often do you get the alerts? Was it just once in a prolonged period of time? How does it look like on the charts?

**Comment by cakrit** [comment]
Also, one more thing. When you say previous versions, which versions have you tried? Did you for example have the same issue with 1.15?

**Comment by fulcrum29** [comment]
> Do you see the same problem when observing the chart itself in the dashboard, or is it only an issue with the alarm?

Yes, super high numbers in charts as well.


> Also, one more thing. When you say previous versions, which versions have you tried? Did you for example have the same issue with 1.15?

I remember, I had the same issue in 1.13 and next versions.

**Comment by cakrit** [comment]
> IRC, I had the same issue in 1.13 and next versions.

You had the problem in the stable 1.13.0 version, or in some nightly after 1.13? We're trying to figure out what to look for...

**Comment by mfundul** [comment]
@fulcrum29 is netdata installed on a Hard Disk Drive by any chance? `memory mode = map` is very heavy in disk I/O overhead and it interferes with the rest of the system significantly. In our new versions we suggest using `memory mode = dbengine` for scenarios such as yours. See [here](https://docs.netdata.cloud/database/#dbengine).

**Comment by vlvkobal** [comment]
Might be connected: #6077

**Comment by mfundul** [comment]
@fulcrum29 did you see spikes in the charts for both `system.load` and `system.cpu`?

**Comment by vlvkobal** [comment]
@fulcrum29 Please make a Netdata snapshot for a timeframe which includes the spikes, and send it to vlad@netdata.cloud.

**Comment by fulcrum29** [comment]
> @fulcrum29 is netdata installed on a Hard Disk Drive by any chance? `memory mode = map` is very heavy in disk I/O overhead and it interferes with the rest of the system significantly. In our new versions we suggest using `memory mode = dbengine` for scenarios such as yours. See [here](https://docs.netdata.cloud/database/#dbengine).

NVMe SSD in RAID

**Comment by johnramsden** [comment]
From #6510:

> @johnramsden Please make a Netdata snapshot for a timeframe, which includes the spikes, and then send it to [vlad@netdata.cloud](mailto:vlad@netdata.cloud).

@vlvkobal I assume I can't do this retroactively, I'll get one next time it occurs. My metrics are in prometheus, would a query from there help?

`memory mode = save` on host, not in container.

I'm running ZFS with multiple datasets, could that be a factor?

**Comment by vlvkobal** [comment]
@johnramsden Do you have in your dashboard something like this?

![image](https://user-images.githubusercontent.com/22008543/61646160-3d59e080-acb1-11e9-8718-f86862e0da1f.png)

How often do you get the alerts? Do you have spikes or gaps on the charts when you get the alerts? Is it one spike or a series of them?

> I can't do this retroactively, I'll get one next time it occurs

Great, I'll wait for it.

**Comment by vlvkobal** [comment]
@fulcrum29 Could you make a snapshot with `memory mode = save`?

**Comment by mfundul** [comment]
> 
> 
> @fulcrum29 Could you make a snapshot with `memory mode = save`?

This might cause an out of memory condition if the database is bigger than the available RAM.

**Comment by cakrit** [comment]
I spoke with @ktsaou. 
Let's first see if what we're seeing is an issue with the slave itself, or if it's a problem with streaming. To do that, please access the slave UI console *directly* (i.e. you shouldn't be seeing http://masterurl/host/slave, but http://slave-url). If the dashboard looks clean on the slave but as horrible as what we saw on the master, then we know it has to do with streaming.

If indeed streaming is an issue, let us know if there's anything between the slaves and the master. i.e. does the slave send metrics to the master via a load balancer or proxy? We would also need to see some logs from both the problematic slave and the master. You can send those logs as before, to vlad@netdata.cloud and @vlvkobal will share them with the rest of the team.

**Comment by johnramsden** [comment]
@vladmovchan Emailed vlad@netdata.cloud two snapshots of disk utilization.

**Comment by cakrit** [comment]
@fulcrum29 and @vladmovchan we need the data requested in my last comment: https://github.com/netdata/netdata/issues/6511#issuecomment-513850949

**Comment by vladmovchan** [comment]
It seems I was mentioned by mistake in the last two comments. I guess both should be addressed to @vlvkobal

**Comment by vlvkobal** [comment]
@johnramsden I see spikes on your snapshots but they aren't abnormal. What alarm message did you receive on the spike?

**Comment by johnramsden** [comment]
@vlvkobal 


> disk_backlog.sdc
> CHART
> 
> --
> 
> 10min disk backlog = 715829 ms
> average of the kernel estimated disk backlog, for the last 10 minutes
> ALARM
> 
> sdc
> FAMILY
> 
> CRITICAL
> SEVERITY

---


> disk_util.sdc
> CHART
> 
> --
> 
> 10min disk utilization = 715828%
> the percentage of time the disk was busy, during the last 10 minutes
> ALARM
> 
> sdc
> FAMILY
> 
> CRITICAL
> SEVERITY

---

I actually just received the same alert on a different host too.

> 10min disk utilization = 715828% 

>

**Comment by vlvkobal** [comment]
@johnramsden Please provide the data for the `disk_backlog.sdc.10min_disk_backlog` and `disk_util.sdc.10min_disk_utilization` alarms from the `http://localhost:19999/api/v1/alarms?all` API call.

**Comment by johnramsden** [comment]
@vlvkobal alarms:

```
                "disk_backlog.sdc.10min_disk_backlog": {
                        "id": 1562022162,
                        "name": "10min_disk_backlog",
                        "chart": "disk_backlog.sdc",
                        "family": "sdc",
                        "active": true,
                        "disabled": false,
                        "silenced": false,
                        "exec": "/usr/libexec/netdata/plugins.d/alarm-notify.sh",
                        "recipient": "sysadmin",
                        "source": "152@/etc/netdata/health.d/disks.conf",
                        "units": "ms",
                        "info": "average of the kernel estimated disk backlog, for the last 10 minutes",
                        "status": "CLEAR",
                        "last_status_change": 1564140363,
                        "last_updated": 1564208643,
                        "next_update": 1564208703,
                        "update_every": 60,
                        "delay_up_duration": 0,
                        "delay_down_duration": 900,
                        "delay_max_duration": 3600,
                        "delay_multiplier": 1.200000,
                        "delay": 0,
                        "delay_up_to_timestamp": 1564140363,
                        "warn_repeat_every": "0",
                        "crit_repeat_every": "0",
                        "value_string": "1.47 ms",
                        "db_after": 1564208044,
                        "db_before": 1564208643,
                        "lookup_method": "average",
                        "lookup_after": -600,
                        "lookup_before": 0,
                        "lookup_options": "unaligned",
                        "warn":"$this &gt; $green * (($status &gt;= $WARNING) ? (0.7) : (1))",
                        "warn_parsed":"(${this} &gt; (${green} * ((${status} &gt;= ${WARNING}) ? 0.7 : 1)))",
                        "crit":"$this &gt; $red * (($status == $CRITICAL) ? (0.7) : (1))",
                        "crit_parsed":"(${this} &gt; (${red} * ((${status} == ${CRITICAL}) ? 0.7 : 1)))",
                        "green":2000,
                        "red":5000,
                        "value":1.470519
                },
```

```
                "disk_util.sdc.10min_disk_utilization": {
                        "id": 1562022163,
                        "name": "10min_disk_utilization",
                        "chart": "disk_util.sdc",
                        "family": "sdc",
                        "active": true,
                        "disabled": false,
                        "silenced": false,
                        "exec": "/usr/libexec/netdata/plugins.d/alarm-notify.sh",
                        "recipient": "sysadmin",
                        "source": "130@/etc/netdata/health.d/disks.conf",
                        "units": "%",
                        "info": "the percentage of time the disk was busy, during the last 10 minutes",
                        "status": "CLEAR",
                        "last_status_change": 1564140363,
                        "last_updated": 1564208643,
                        "next_update": 1564208703,
                        "update_every": 60,
                        "delay_up_duration": 0,
                        "delay_down_duration": 900,
                        "delay_max_duration": 3600,
                        "delay_multiplier": 1.200000,
                        "delay": 0,
                        "delay_up_to_timestamp": 1564140363,
                        "warn_repeat_every": "0",
                        "crit_repeat_every": "0",
                        "value_string": "0.69%",
                        "db_after": 1564208044,
                        "db_before": 1564208643,
                        "lookup_method": "average",
                        "lookup_after": -600,
                        "lookup_before": 0,
                        "lookup_options": "unaligned",
                        "warn":"$this &gt; $green * (($status &gt;= $WARNING) ? (0.7) : (1))",
                        "warn_parsed":"(${this} &gt; (${green} * ((${status} &gt;= ${WARNING}) ? 0.7 : 1)))",
                        "crit":"$this &gt; $red * (($status == $CRITICAL) ? (0.7) : (1))",
                        "crit_parsed":"(${this} &gt; (${red} * ((${status} == ${CRITICAL}) ? 0.7 : 1)))",
                        "green":90,
                        "red":98,
                        "value":0.6898524
                }
```

**Comment by cakrit** [comment]
Do we need to do something here, or has it gone away from a fix for some other issue?

**Comment by tmikaeld** [comment]
I'm still seeing 10min_disk_utilization warning, it's been constant, happens on all default proxmox installations.

**Comment by ilyam8** [comment]
@tmikaeld hi, if you think the alarm value is wrong, please make a snapshot when the alarm is up and send it to vlad@netdata.cloud. Or consider to open a new issue about `10min_disk_utilization`.

We recheked snaphotes, the one, we got from @fulcrum29, contains many problems - huge spikes on all charts with `incremental` dimensions.


@fulcrum29 consider updating to the latest stable version (v1.29.0), if there are any problems, please let us know.
