### ISSUE TITLE
I have install netdata and follow Running Netdata behind Nginx but ...

### ISSUE THREAD

**Issue by maccas777** [netdata/netdata#6513]
question -

I have install netdata on my local environment where I am testing it to be load on my nginx server 

But i fail to get the web page to prompted me username and password 

I would like to know if there anyone who can guide me or a link can be helpful 

OS / Environment
CentOS Linux release 7.6.1810 (Core) 

I have also used 
https://www.digitalocean.com/community/tutorials/how-to-set-up-real-time-performance-monitoring-with-netdata-on-ubuntu-16-04
 and 
https://www.vultr.com/docs/installing-netdata-on-centos-7

this and yet still dont get it to work 

any help will be much appreciated

**Comment by cakrit** [comment]
Did you read this? https://docs.netdata.cloud/docs/running-behind-nginx/#enable-authentication

**Comment by prhomhyse** [comment]
@maccas777 

After creating an authentication or password file, please restart Nginx as advised [here](https://docs.netdata.cloud/docs/running-behind-nginx/#nginx-configuration-file).
