### ISSUE TITLE
Add netdata charts for streaming

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6514]
##### Feature idea summary
Be able to validate the health of slave-master communication (streaming/replication) via netdata charts.

##### Expected behavior
In the netdata section of each netdata, we should start showing charts for the communication between a master and its slaves. Communication errors, transferred data, memory used for each slave should appear on the master. Similarly, the slave should also be collecting data on streaming from its perspective and show those charts. We should also add stock alarms for the errors.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
