### ISSUE TITLE
Many email alerts queue cookies/drops

### ISSUE THREAD

**Issue by samuelmf** [netdata/netdata#6517]
Hi guys i have installed netdata on my centos servers, by only in one of them i recieve several alerts with messages like this:

ip.tcp_syn_queueCHART--
1m tcp syn queue cookies = 24 cookies
ip.tcp_accept_queueCHART
1m tcp accept queue drops = 237.1 drops

I recieve messages like, critical, needs attention and recovered.

How can i do solve that? (i'm newbie)

##### OS / Environment
Centos 7.4 with Cpanel/WHM

**Comment by cakrit** [comment]
See #3234 and #4281, I believe they will help you.
