### ISSUE TITLE
Missing file when install the netdata

### ISSUE THREAD

**Issue by zhonglinwei** [netdata/netdata#6519]
##### Question summary
git clone https://github.com/netdata/netdata.git --depth=100
cd netdata && ./netdata-installer.sh --stable-channel --install /data
And then give me some errors:
chmod 755 /data/netdata/etc/netdata/edit-config 
chmod: cannot access `/data/netdata/etc/netdata/edit-config': No such file or directory
 FAILED

**Comment by paulkatsoulakis** [comment]
thanks for your report @zhonglinwei, i am sorry to hear that!
I 'll have a look asap and let you know

**Comment by paulkatsoulakis** [comment]
As a first comment, the error is not a hard error meaning the installation is successful.
The bug seems to be on the installer though, i 'll work on it and let you know

**Comment by paulkatsoulakis** [comment]
I have reverted the solution given for #6507 and will rework it as part of this story.
I am regenerating nightlies as we speak to avoid further issues with users.

Thanks again for your report @zhonglinwei !

**Comment by paulkatsoulakis** [comment]
re-published fixed nightly, closing this!
will follow up the fix for the macOS path issues from #6165 

Thanks!
