### ISSUE TITLE
host needs attention / is critical - 1m ipv4 udp receive buffer errors - ipv4.udperrors

### ISSUE THREAD

**Issue by hoppel118** [netdata/netdata#6527]
Hi guys,

I get emails like this:

![host needs attention](https://user-images.githubusercontent.com/991344/61771959-671a2100-adf1-11e9-8bdd-e0c7dbed3c9a.PNG)

![host is critical](https://user-images.githubusercontent.com/991344/61771986-7600d380-adf1-11e9-876d-9dc0274592f4.PNG)

I am using netdata in a docker container on an openmediavault 4 machine with debian stretch os. Everything is up-to-date.

```
root@omv4:~# uname -a
Linux omv4 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-4~bpo9+1 (2019-06-19) x86_64 GNU/Linux
```

I found some issue reports here on github from other guys reporting the same issue, but there are no answers to fix the issue:

https://github.com/netdata/netdata/issues/4086
https://github.com/netdata/netdata/issues/1754
https://github.com/netdata/netdata/issues/2102

At the netdata WebInterface I see the following:

![udp errors](https://user-images.githubusercontent.com/991344/61772371-60d87480-adf2-11e9-9df5-b7081c723631.PNG)

![udp some errors](https://user-images.githubusercontent.com/991344/61772378-646bfb80-adf2-11e9-9af1-e7a580398431.PNG)

I tried to configure my receive and write buffers, but nothing helped. I started with the following configuration:

https://github.com/netdata/netdata/issues/1076#issuecomment-509214247

But for my udp errors this didn't work and I tried to combine the informations of the following internet sites:

https://www.ibm.com/support/knowledgecenter/en/SSQPD3_2.6.0/com.ibm.wllm.doc/UDPSocketBuffers.html
http://www.nateware.com/linux-network-tuning-for-2013.html#.XTgD2lwzZhF
https://opensourceforu.com/2016/10/network-performance-monitoring/
https://wiki.archlinux.org/index.php/Sysctl

My current "/etc/sysctl.d/99-network-tuning.conf" looks as follows:

```
### KERNEL TUNING ###

# Increase size of file handles and inode cache
fs.file-max = 2097152

# Do less swapping / Virtual memory
vm.swappiness = 10
vm.dirty_ratio = 60
vm.dirty_background_ratio = 2

# Sets the time before the kernel considers migrating a proccess to another core
kernel.sched_migration_cost_ns = 5000000

# Group tasks by TTY
#kernel.sched_autogroup_enabled = 0

### GENERAL NETWORK SECURITY OPTIONS ###

# Number of times SYNACKs for passive TCP connection.
net.ipv4.tcp_synack_retries = 2

# Allowed local port range
net.ipv4.ip_local_port_range = 2000 65535

# Protect against tcp time-wait assassination hazards, drop RST packets for sockets in the time-wait state
net.ipv4.tcp_rfc1337 = 1

# Helps protect against SYN flood attacks. Only kicks in when net.ipv4.tcp_max_syn_backlog is reached
net.ipv4.tcp_syncookies = 1

# Specify how many seconds to wait for a final FIN packet before the socket is forcibly closed
net.ipv4.tcp_fin_timeout = 10

# With the following settings, your application will detect dead TCP connections after 120 seconds (60s + 10s + 10s + 10s + 10s + 10s + 10s)
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6

### TUNING NETWORK PERFORMANCE ###

# https://www.ibm.com/support/knowledgecenter/en/SSQPD3_2.6.0/com.ibm.wllm.doc/UDPSocketBuffers.html
# On the Linux platform Tx ring buffer overruns can occur when transmission rates approach 1Gbps and the default send socket buffer is greater than 65536.
# It is recommended to set the net.core.wmem_default kernel parameter to no larger than 65536 bytes.
# Transmitting applications can configure the send socket buffer size for InfiniBand, UDP, or TCP protocols independently in a transmit instance.

# Default and Maximum Socket Receive Buffer
net.core.rmem_default = 8388608
net.core.rmem_max = 16777216

# Default and Maximum Socket Send Buffer
net.core.wmem_default = 65536
net.core.wmem_max = 16777216

# Increase the maximum amount of option memory buffers
net.core.optmem_max = 65536

# Increase number of incoming connections
#net.core.somaxconn = 65535

# Increase number of incoming connections backlog
net.core.netdev_max_backlog = 100000

# Maximum number of microseconds in one NAPI polling cycle.
# Polling will exit when either netdev_budget_usecs have elapsed during the poll cycle or the number of packets processed reaches netdev_budget.
net.core.netdev_budget = 60000
net.core.netdev_budget_usecs = 6000

# Increase the tcp read and write-buffer-space allocatable
net.ipv4.tcp_rmem = 4096 1048576 2097152
net.ipv4.tcp_wmem = 4096 65536 16777216

# Increase the tcp read and write-buffer-space allocatable (default = 4096)
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192

# Increase the maximum total buffer-space allocatable
# This is measured in units of pages (4096 bytes)
#net.ipv4.tcp_mem = 786432 1048576 26777216
#net.ipv4.udp_mem = 65536 131072 262144

# Make room for more TIME_WAIT sockets due to more clients,
# and allow them to be reused if we run out of sockets
net.ipv4.tcp_max_syn_backlog = 30000
net.ipv4.tcp_max_tw_buckets = 2000000
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_slow_start_after_idle = 0
```

What else information do you need to help me to solve my issue?

How is it possible to analyze my network regarding udp traffic to find the cause?

Best regards Hoppel

**Comment by ilyam8** [comment]
So you are saying changing `net.core.rmem_max` param doesnt help? Does it affect number of RcvbufErrors?

**Comment by hoppel118** [comment]
Yes, this tunable doesn't help and it doesn't affect the number of RcvbufErrors.

Tried a lot of combinations. But after I found the following information from ibm, I thought that this configuration might be the only one for a 1Gbit ethernet interface:

https://www.ibm.com/support/knowledgecenter/en/SSQPD3_2.6.0/com.ibm.wllm.doc/UDPSocketBuffers.html

By the way... it's a 10Gbit interface, but the switch is only capable of 1Gbit.

**Comment by ilyam8** [comment]
> Which value should be set for this tunable in your opinion?

i have no idea, i would do it that way:
 - set param; see the result; if ok done else go to set param :smile:

**Comment by hoppel118** [comment]
> i would do it that way:
> 
> set param; see the result; if ok done else go to set param 😄

This is what I did. But I do not find the parameters. 

Any other ideas or concrete configuration suggestions to work out the issue?

Thanks and regards Hoppel

**Comment by hoppel118** [comment]
Hey guys,

this is how I analyzed my issue.

```
:~# sysctl net.core | grep mem
net.core.optmem_max = 65536
net.core.rmem_default = 8388608
net.core.rmem_max = 16777216
net.core.wmem_default = 65536
net.core.wmem_max = 16777216
```
So, my "net.core.rmem_default" is "8388608". With the following command I recognized that there is one program "perl" with a high Recv-Q at port 1900 (UPnP). The value "8390400" of it is nearly my "net.core.rmem_default = 8388608", but it's slightly higher. 
```
:~# netstat -unlp
Aktive Internetverbindungen (Nur Server)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 0.0.0.0:31909           0.0.0.0:*                           17804/perl
udp        0      0 0.0.0.0:68              0.0.0.0:*                           2580/dhclient
udp        0      0 0.0.0.0:111             0.0.0.0:*                           2250/rpcbind
udp        0      0 172.17.0.1:123          0.0.0.0:*                           2884/ntpd
udp        0      0 10.11.11.11:123         0.0.0.0:*                           2884/ntpd
udp        0      0 127.0.0.1:123           0.0.0.0:*                           2884/ntpd
udp        0      0 0.0.0.0:123             0.0.0.0:*                           2884/ntpd
udp        0      0 172.17.255.255:137      0.0.0.0:*                           2728/nmbd
udp        0      0 172.17.0.1:137          0.0.0.0:*                           2728/nmbd
udp        0      0 10.11.11.255:137        0.0.0.0:*                           2728/nmbd
udp        0      0 10.11.11.11:137         0.0.0.0:*                           2728/nmbd
udp        0      0 0.0.0.0:137             0.0.0.0:*                           2728/nmbd
udp        0      0 172.17.255.255:138      0.0.0.0:*                           2728/nmbd
udp        0      0 172.17.0.1:138          0.0.0.0:*                           2728/nmbd
udp        0      0 10.11.11.255:138        0.0.0.0:*                           2728/nmbd
udp        0      0 10.11.11.11:138         0.0.0.0:*                           2728/nmbd
udp        0      0 0.0.0.0:138             0.0.0.0:*                           2728/nmbd
udp        0      0 0.0.0.0:730             0.0.0.0:*                           2250/rpcbind
udp   8390400      0 0.0.0.0:1900            0.0.0.0:*                           17804/perl
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           17804/perl
udp        0      0 239.255.255.250:1900    0.0.0.0:*                           10418/tvheadend
udp        0      0 0.0.0.0:3425            0.0.0.0:*                           15259/EmbyServer
udp        0      0 0.0.0.0:3935            0.0.0.0:*                           15259/EmbyServer
udp        0      0 10.11.11.11:5353        0.0.0.0:*                           2721/homebridge
udp        0      0 10.11.11.11:5353        0.0.0.0:*                           2722/homebridge
udp        0      0 10.11.11.11:5353        0.0.0.0:*                           2739/homebridge
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           2263/avahi-daemon:
udp        0      0 0.0.0.0:7359            0.0.0.0:*                           15259/EmbyServer
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           14584/netdata
udp        0      0 0.0.0.0:48213           0.0.0.0:*                           2263/avahi-daemon:
udp        0      0 0.0.0.0:56620           0.0.0.0:*                           10418/tvheadend
udp6       0      0 172.17.0.1:59104        :::*                                15416/java
udp6       0      0 :::111                  :::*                                2250/rpcbind
udp6       0      0 ::1:123                 :::*                                2884/ntpd
udp6       0      0 :::123                  :::*                                2884/ntpd
udp6       0      0 :::730                  :::*                                2250/rpcbind
udp6       0      0 :::3478                 :::*                                15416/java
udp6       0      0 :::10001                :::*                                15416/java
udp6       0      0 10.11.11.11:22480       :::*                                15416/java
```
With the following command I can see alle my programs using port 1900:

```
~# netstat -unlp | grep ":1900"
udp        0      0 239.255.255.250:1900    0.0.0.0:*                           15379/tvheadend
udp   8389376      0 0.0.0.0:1900            0.0.0.0:*                           4704/perl
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           4704/perl
```

So I had a look at "netstat" with the following command:

```
~# netstat -anus
IcmpMsg:
    InType3: 2629
    OutType3: 2620
Udp:
    1877318 packets received
    55 packets to unknown port received
    212919 packet receive errors
    1016291 packets sent
    212919 receive buffer errors
    0 send buffer errors
    IgnoredMulti: 136947
```

After that I tried to double my read buffer, configured it and rebooted my system:

~# sysctl net.core | grep mem
net.core.optmem_max = 65536
net.core.rmem_default = 16777216
net.core.rmem_max = 16777216
net.core.wmem_default = 65536
net.core.wmem_max = 16777216

Waited some time until netdata reported udp errors:

```
~# netstat -unlp | grep ":1900"
udp   16779008      0 0.0.0.0:1900            0.0.0.0:*                           4817/perl
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           4817/perl
udp        0      0 239.255.255.250:1900    0.0.0.0:*                           4569/tvheadend
```
```
~# netstat -anus
IcmpMsg:
    InType3: 622
    OutType3: 617
Udp:
    718046 packets received
    98 packets to unknown port received
    138744 packet receive errors
    279929 packets sent
    138744 receive buffer errors
    0 send buffer errors
    IgnoredMulti: 30593
```
Nothing changed, the Recv-Q is slightly higher than the read buffer.

One last check:

```
:~# sysctl net.core | grep mem
net.core.optmem_max = 65536
net.core.rmem_default = 33554432
net.core.rmem_max = 33554432
net.core.wmem_default = 65536
net.core.wmem_max = 16777216
```
```
:~# netstat -unlp | grep ":1900"
udp   33556224      0 0.0.0.0:1900            0.0.0.0:*                           3958/perl
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           3958/perl
udp        0      0 239.255.255.250:1900    0.0.0.0:*                           3779/tvheadend
```
```
:~# netstat -anus
IcmpMsg:
    InType3: 96
    OutType3: 96
Udp:
    74361 packets received
    96 packets to unknown port received
    10486 packet receive errors
    6742 packets sent
    10486 receive buffer errors
    0 send buffer errors
    IgnoredMulti: 1743
```
Again the same behavior. It's not possible to solve the issue by increasing the "net.core.rmem_default".

But I recognized that port 1900 (UPnP) generates the issue.

I use TVHeadend, Emby and FHEM (Sonos module), which all use port 1900. I know that I have the issue since I use the FHEM module for Sonos. I use Emby and TVHeadend for some years now and never had udp problems.

I googled a bit around and found other guys with similar TVHeadend problems. So I tried to not automatically start TVHeadend, rebooted my server, waited some time and manually started TVHeadend. This was 7 days ago and I don't see any issue. Now when I have a look at the above commands I get the following results:

```
 :~# sysctl net.core | grep mem
net.core.optmem_max = 65536
net.core.rmem_default = 8388608
net.core.rmem_max = 16777216
net.core.wmem_default = 65536
net.core.wmem_max = 16777216
```
```
:~# netstat -unlp | grep ":1900"
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           10172/EmbyServer
```
```
:~# netstat -anus
IcmpMsg:
    InType3: 7782
    OutType3: 7696
Udp:
    3975237 packets received
    52 packets to unknown port received
    0 packet receive errors
    2980744 packets sent
    0 receive buffer errors
    0 send buffer errors
    IgnoredMulti: 248902
```

This looks really fine. So I need to configure my service in a way that docker service start behind  the FHEM Service. FHEM is installed on the host machine directly while TVHeadend and Emby are docker container.

But I found another issue for TVHeadend:

https://github.com/linuxserver/docker-tvheadend/issues/100

This Issue was solved two days ago by the following comment:

> If you use IPTV, SAT>IP or HDHomeRun, you need to create the container with --net=host and remove the -p flags. This is because to work with these services Tvheadend requires a multicast address of `239.255.255.250` and a UDP port of `1900` which at this time is not possible with docker bridge mode.
> If you have other host services which also use multicast such as SSDP/DLNA/Emby you may experience stabilty problems. These can be solved by giving tvheadend its own IP using macavlan.

Now I have two choice to solve my issue. I will try to configure my TVHeadend container with a macvlan IP.

I am going to report it back here. For the moment I only want to show you the result of my analyzes.

This is definitely nothing that could be solved by netdata. ;)

Thanks and regards Hoppel

**Comment by cakrit** [comment]
Cool, thanks @hoppel118. Closing it and hopefully what you wrote will help others too.

**Comment by hoppel118** [comment]
OK, so I configured my systemd services to start first FHEM and then Docker. But this didn't help.

I added the following in the systemd docker configuration file:

```
[Unit]
Wants=fhem.service
After=network.target
```
After this you have to tell your systemd that there were configuration changes:

```
~# systemctl --system daemon-reload
```

To check if everything works as expected, I restarted my docker service:

```
:~# systemctl stop docker
:~# systemctl start docker
```
After evrything was back to normal operation, I rebooted my server and had a look at the following command:

```
~# netstat -unlp | grep ":1900"
udp        0      0 239.255.255.250:1900    0.0.0.0:*                           15379/tvheadend
udp   8389376      0 0.0.0.0:1900            0.0.0.0:*                           4704/perl
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           4704/perl
```

Shortly thereafter, the emails of netdata came again. So I stopped FHEM and TVHeadend and got a Mail from netdata, that everything is fine again. 

Conclusion: For me it only works if my UPnP services start in the following order:

1. Emby
2. FHEM
3. TVHeadend

After this test, I tried my second choice and configured a macvlan in docker, gave Emby and TVHeadend its own IP addresses and rebooted my server.

Now the result of the "netstat unlp" is as follows:

```
:~# netstat -unlp | grep ":1900"
udp   8388864      0 0.0.0.0:1900            0.0.0.0:*                           3922/perl
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           3922/perl
```
I am fine with this result, since emby and tvheadend now have their own IP.

So ,I had a look at "netstat -anus":

```
:~# netstat -anus
IcmpMsg:
    InType3: 78
    OutType3: 72
Udp:
    10553 packets received
    72 packets to unknown port received
    3343 packet receive errors
    1686 packets sent
    3343 receive buffer errors
    0 send buffer errors
    IgnoredMulti: 31
```

What happened? I don't understand this. Why are there packet receive errors again? 

Maybe I have to read more about macvlan. This oesn't work as expected.

But I made my last check and started my UPnP Services in the following order:

1. Emby
2. FHEM
3. TVHeadend

After that everything was fine again. I'll report back here, when I found a solution.

Regards Hoppel

**Comment by hoppel118** [comment]
> Cool, thanks @hoppel118. Closing it and hopefully what you wrote will help others too.

It would be nice if you could open my issue again, even though it's certainly not a netdata mistake. I stay tuned to the topic.

Thanks and regards Hoppel

**Comment by hoppel118** [comment]
So, I found a workaround for my situation.

There is also an issue within tvheadend. It's not possible to disable UPnP even though the option is checked.

![image](https://user-images.githubusercontent.com/991344/63263527-2b0b9c00-c289-11e9-8bd3-298ab5e0496e.png)

So, I analyzed which services need port 1900 and in which order they must be started. 

I configured my TVHeadend and my Emby docker container to not use the macvlan. Emby is in network mode "Host" again and TVHeadend is now in network mode "Bridge". For TVHeadend I exposed the ports 9981 and 9982 only. So port 1900 can't communicate outside the container. Port 1900 of TVHeadend is used for "SAT>IP Server", which I don't use. 

There are other TVHeadend users who recognized the same behavior. I wrote my findings in this post in the TVHeadend forum:

https://tvheadend.org/boards/5/topics/37322?r=38510#message-38510

OK, now I only have to ensure that my FHEM starts behind docker (Emby).

This I solved by systemd parameters. I configured my systemd fhem.service as follows:

```
[Unit]
After=docker.service
```

After that i told my systemd that there were configuration changes with the following command:

```
:~# systemctl --system daemon-reload
```

So, I rebooted my server and everything looks as expected:

Emby was startet first and holds port 1900:

```
:~# netstat -unlp | grep ":1900"
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           3038/EmbyServer
```

For the moment I don't see any packet receive errors or receive buffer errors:

```
4:~# netstat -anus
IcmpMsg:
    InType3: 48
    InType8: 30
    OutType0: 30
    OutType3: 48
Udp:
    768 packets received
    48 packets to unknown port received
    0 packet receive errors
    302 packets sent
    0 receive buffer errors
    0 send buffer errors
    IgnoredMulti: 26
```

This is not the perfect way. But it works for me. 

@cakrit I think, you can close this issue again. I am goint to report back here, when I found another solution.

Thanks and regards Hoppel

**Comment by hoppel118** [comment]
So, I reduced the "/etc/sysctl.d/99-network-tuning.conf" because I really don't know what all these tunables are used for:

```
### TUNING NETWORK PERFORMANCE ###

# https://www.ibm.com/support/knowledgecenter/en/SSQPD3_2.6.0/com.ibm.wllm.doc/UDPSocketBuffers.html
# On the Linux platform Tx ring buffer overruns can occur when transmission rates approach 1Gbps and the default send socket buffer is greater than 65536.
# It is recommended to set the net.core.wmem_default kernel parameter to no larger than 65536 bytes.
# Transmitting applications can configure the send socket buffer size for InfiniBand, UDP, or TCP protocols independently in a transmit instance.

# Default and Maximum Socket Receive Buffer
net.core.rmem_default = 8388608
net.core.rmem_max = 16777216

# Default and Maximum Socket Send Buffer
net.core.wmem_default = 65536
net.core.wmem_max = 16777216

# Increase the maximum amount of option memory buffers
net.core.optmem_max = 65536

# Increase number of incoming connections backlog
net.core.netdev_max_backlog = 100000

# Increase the tcp read and write-buffer-space allocatable
net.ipv4.tcp_rmem = 4096 1048576 2097152
net.ipv4.tcp_wmem = 4096 65536 16777216

# Increase the ucp read and write-buffer-space allocatable
net.ipv4.udp_rmem_min = 4096
net.ipv4.udp_wmem_min = 4096

# Maximum number of microseconds in one NAPI polling cycle.
# Polling will exit when either netdev_budget_usecs have elapsed during
# the poll cycle or the number of packets processed reaches netdev_budget.
net.core.netdev_budget = 60000
net.core.netdev_budget_usecs = 6000

# Disable TCP slow start on idle connections
net.ipv4.tcp_slow_start_after_idle = 0
```

Maybe it's possible to reduce out more, but with this configuration it seems to work without any udp or system.softnet_stat issue reported by netdata.

For system.softnet_stat issue have a look at the following issue: https://github.com/netdata/netdata/issues/1076

Regards Hoppel

**Comment by eresonance** [comment]
For people searching for resolutions to these UDP Rx errors, I found a very similar issue with home assistant related to [zeroconf](https://github.com/home-assistant/core/issues/35031). Still no resolution there unfortunately :(

**Comment by isakrubin** [comment]
Same issue however not using docker.

sudo sysctl net.core | grep mem
net.core.optmem_max = 20480
net.core.rmem_default = 26214400
net.core.rmem_max = 26214400
net.core.wmem_default = 26214400
net.core.wmem_max = 26214400

cat /etc/netdata/health.d/udp_errors.conf|grep to
# you can disable an alarm notification by setting the 'to' line to: silent
      to: silent
      to: silent
      to: silent

Inbox full of notifications 24/7....

Just looking for a way to disable the notifications, settings "to:" to silent does not seem to work at all.

**Comment by heapxor** [comment]
Is there any fix? i have same issue running armbian on banan m1+ soc.
