### ISSUE TITLE
how to define alarm rules with netdata monitoring container cpu usage?

### ISSUE THREAD

**Issue by ardenxu** [netdata/netdata#6528]
##### Question summary

we are using netdata to monitor application container usage on k8s,  and report the data to prometheus. Prometheus can get metrics like netdata_apps_cpu_percentage_average, and would like to add alert rule for netdata cpu metrics.

For cpu usage, the problem is different application may have different cpu core #, so define one unique cpu threshold for cpu usage is not reasonable.  so is it possible for netdata report the cpu core num for container monitoring? or have other option to achieve similar purpose.

thanks!

##### OS / Environment
cent os 7.2    netdata1.15.0  prometheus 2.10.0

**Comment by cakrit** [comment]
I suggest you use `XXX.cpu_limit`, so you don't worry about cores at all and get something more meaningful. `cpu_limit` takes into account the limits specified for each container. It's the first chart shown below. The name of the chart in this example is too long and doesn't show up on the screen, but it does end with .cpu_limit.

![Screenshot from 2019-07-24 11-05-14](https://user-images.githubusercontent.com/43294513/61780770-64c0c280-ae03-11e9-8c31-fb14079ed775.png)

**Comment by ardenxu** [comment]
@cakrit  thanks for input.  i get that after enabled cgroup plugin, but we want to monitor each app after enable netdata in application image.  if we enable cgroup in each app, all the cpu related info are almost duplication. do you have any suggestion regarding this?  for both  cpu and memory we have similar puzzle.

![image](https://user-images.githubusercontent.com/20676860/61843083-04965300-aecd-11e9-92fd-500146ef3a7c.png)

**Comment by ardenxu** [comment]
@cakrit  we can get cpu core # now with shell script plugin, its works.  but how can I find the new metrics introduced by the plugin on prometheus side? 

![image](https://user-images.githubusercontent.com/20676860/61861885-6ec7eb80-aeff-11e9-80b4-ea9c7faa997e.png)

post the script for later reference.
===========================================================
# shellcheck shell=bash disable=SC2154,SC1072,SC1073,SC2009,SC2162,SC2006,SC2002,SC2086,SC1117
# no need for shebang - this file is loaded from charts.d.plugin
# SPDX-License-Identifier: GPL-3.0-or-later

# netdata
# real-time performance and health monitoring, done right!
# (C) 2016 Costa Tsaousis <costa@tsaousis.gr>
#

cpu_limit_update_every=10
load_priority=100

# this is an example charts.d collector
# it is disabled by default.
# there is no point to enable it, since netdata already
# collects this information using its internal plugins.
cpu_limit_enabled=1
#cpu_limit_cpunum=0
#cpu_limit_memmax=0

cpu_limit_check() {
	# this should return:
	#  - 0 to enable the chart
	#  - 1 to disable the chart

	#if [ ${load_average_update_every} -lt 5 ]; then
		# there is no meaning for shorter than 5 seconds
		# the kernel changes this value every 5 seconds
        #         load_average_update_every=5
	#fi

	[ ${cpu_limit_enabled} -eq 0 ] && return 1
	return 0
}

cpu_limit_create() {
	# create a chart with 2 dimensions
	cat <<EOF
CHART cpu.limit '' "CPU limit" "memory max" load cpu.limit line $((load_priority + 1)) $load_average_update_every
DIMENSION cpu  'cpu core limit' absolute 1 1
DIMENSION memory 'memory max Gbytes' absolute 1 1
EOF

	return 0
}

cpu_limit_update() {
	# do all the work to collect / calculate the values
	# for each dimension
	# remember: KEEP IT SIMPLE AND SHORT

	# here we parse the system average load
	# it is decimal (with 2 decimal digits), so we remove the dot and
	# at the definition we have divisor = 100, to have the graph show the right value
        cpu="$(expr $(cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us) / $(cat /sys/fs/cgroup/cpu/cpu.cfs_period_us) )"
        memory="$(expr $(cat /sys/fs/cgroup/memory/memory.limit_in_bytes) / 1024 / 1024 / 1024)"

	# write the result of the work.
	cat <<VALUESEOF
BEGIN cpu.limit
SET cpu=$cpu
SET memory=$memory
END
VALUESEOF

	return 0
}

**Comment by ardenxu** [comment]
sorry for disturb, found out the answer from official doc. thanks!

metrics are under : http://your.netdata.ip:19999/api/v1/allmetrics?format=prometheus&help=yes

![image](https://user-images.githubusercontent.com/20676860/61870497-d33f7680-af10-11e9-9c56-07165f64d073.png)

**Comment by cakrit** [comment]
So are you covered now? I wasn't sure I understood the previous few comments. If you're ok, please close the issue.
