### ISSUE TITLE
Plugin httpcheck heavily changes the WebUI

### ISSUE THREAD

**Issue by It4lik** [netdata/netdata#6530]
OS : Debian 9.9
Netdata : v1.16.0-70-nightly

**Issue :** enabling and using python.d httpcheck module causes dashboard layout and behaviour to be unexpectedly modified. 

I enabled 5 HTTP Checks with the following configuration : 
```
website:
  name: 'Pretty name'
  url: `https://www.website.com`
  timeout: 3
  update_every: 15
```

And then refresh netdata configuration. 

The new dashboard :
* has a **buggy** `python.d` section at the start
* does not group HTTP Checks in a group like "HTTP Checks" on chart index (right menu)
* make all groups of Chart Index buggy : they won't drop down anymore (see on screen 2 how "Memory" is highlighted but no drop-down below it)

Buggy top chart  (screen 1) :   
![netdata1](https://user-images.githubusercontent.com/6367335/61784093-59709580-ae09-11e9-8d31-3829b85d8292.png)

Buggy/not intuitive chart index (screen 2) :  
![netdata2](https://user-images.githubusercontent.com/6367335/61784095-5b3a5900-ae09-11e9-8a34-db958e9a1bb6.png)

it4.

**Comment by cakrit** [comment]
Please get rid of all special characters in the configuration and see if that solves the issue. Looks like the JS is broken due to probably the single quote I saw in the OP. We definitely need to do something about this, but let's see if that's your issue first.

**Comment by It4lik** [comment]
@cakrit thanks for your quick answer
Indeed. I tried to escape the single quote or quote the whole string with double quotes but that's still broken. Yup if I get rid of it, everything is back to normal. 
Works for me, I'll keep it as it is. 
And yup, that's pretty unexpected with a "simple" single quote, whether it's escaped or double-quoted.

And about grouping : is it possible to group HTTP Checks under their own category (same for docker containers) ?

**Comment by cakrit** [comment]
We'd need an additional level to put all cgroups (e.g. docker containers) in a single category. They already contain groups of charts. For httpcheck it's not the same, so we should be able to do it. @ilyam8 ?

Will create a separate issue for the special character handling.

**Comment by It4lik** [comment]
Allright I see. In my opinion it would be great if they can both have their own group, and I'll be manually navigating through the few charts they expose (cpu, ram, net, etc.). But that's totally subjective :)

For httpcheck, you'll face the same problem I think : they are already a category in themselves : they contain the subkeys "response" and "status". 

I think grouping these could bring a lot of clarity to a chart index which uses them. 
It might also be something that we could configure in the associated config file.

**Comment by ilyam8** [comment]
>  is it possible to group HTTP Checks under their own category

Well, that is how it is. Every go.d/python.d module (not job) has its own category

**Comment by It4lik** [comment]
Okay, sounds to me like a limitation to the Netdata dashboard customization. But again, this is purely subjective. 
Thanks for all your answers, I'm closing this thread.
