### ISSUE TITLE
Nginx requests including netdata dashboard requests

### ISSUE THREAD

**Issue by fausto1124** [netdata/netdata#6537]
#### Question summary
I'm actually using netdata to monitor requests made to a nodejs api behind an nginx server.
The graphs are actually working but its requests gets huge when the netdata graphs are open because of the requests made to get the graphs info. How can i exclude the requests made by netdata to only monitor the api requests? Thanks

##### OS / Environment
Ubuntu 18.04
Nginx
Node js

**Comment by ilyam8** [comment]
Hey @fausto1124 	

> I'm actually using netdata to monitor requests made to a nodejs api behind an nginx server.

I think [`web_log`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/web_log) will do.

 - log requests to the node js api to a separate file
 - use `web_log` to parse that file

**Comment by fausto1124** [comment]
I used the web_log configuration with a regex to match the urls that i want to track only.

Thanks!

**Comment by ilyam8** [comment]
> I used the web_log configuration with a regex

> log requests to the node js api to a separate file
> use web_log to parse that file

^^ This is much faster, just saying :smile: Check `Netdata Monitoring` -> `python.d` section, there is `web_log` execution time stats.
