### ISSUE TITLE
Wrong Disk-Space Metric

### ISSUE THREAD

**Issue by flippy1345** [netdata/netdata#6545]
Hi,
I want to display the amount of used disk space in grafana with metrics from netdata.
First I wanted to see the used amount with:
`netdata_disk_space{chart="disk_space._", job="raw-bc-manage1-prod16", family="/", dimension="used"}`

This is the result of the metric:
![image](https://user-images.githubusercontent.com/26430962/61878849-1a6a3f00-aef2-11e9-88ad-c79551931507.png)

4.12 GB is not way too low.

This is the right amount:
![image](https://user-images.githubusercontent.com/26430962/61878997-62896180-aef2-11e9-8740-f23af012df89.png)
 16GB is used 14GB is free.

The question now is how to get the correct data.
The standard netdata dasboard with ":19999" shows under Disks the right amount.

**Comment by flippy1345** [comment]
Can no one help me with this?

**Comment by ilyam8** [comment]
WWhat backend are you using?

**Comment by flippy1345** [comment]
I use Prometheus for Metric strorage, Grafana to display it, netdata to collect it and Ubuntu is the Server OS.
http://XXX:19999/api/v1/allmetrics?format=prometheus&source=as-collected

**Comment by ilyam8** [comment]
```
COMMENT homogeneous chart "disk_space._", context "disk.space", family "/", units "GiB"
# COMMENT netdata_disk_space: chart "disk_space._", context "disk.space", family "/", dimension "avail", value * 4096 / 1073741824 gives GiB (gauge)
netdata_disk_space{chart="disk_space._",family="/",dimension="avail"} 2172207 1565016851220
# COMMENT netdata_disk_space: chart "disk_space._", context "disk.space", family "/", dimension "used", value * 4096 / 1073741824 gives GiB (gauge)
netdata_disk_space{chart="disk_space._",family="/",dimension="used"} 501213 1565016851220
# COMMENT netdata_disk_space: chart "disk_space._", context "disk.space", family "/", dimension "reserved for root", value * 4096 / 1073741824 gives GiB (gauge)
netdata_disk_space{chart="disk_space._",family="/",dimension="reserved for root"} 148262 1565016851220
```

Pay attention to

> value * 4096 / 1073741824 gives GiB (gauge)
