### ISSUE TITLE
Privileged side-car container

### ISSUE THREAD

**Issue by dcflachs** [netdata/netdata#6553]
So the issue I am trying to solve involves running Netdata in a docker container. Since netdata has a web interface i would prefer to keep the container as unprivileged  as possible. However to access certain metrics, in this case matching veth networks to other containers, netdata need greater privilege. Thinking out loud it would be nice to be able to run a second more highly privileged netdata container, to collect certain metrics and stream them to the primary container. This is already somewhat possible using the master slave streaming configuration, however the metrics will be "hidden" in a slave database rather than integrated into the master database. Would it be possible to add a master/slave configuration where the slave metrics are synced and written into the masters database?

Alternatively would it be possible to create sone sort of simple RPC based interface that would allow netdata to remotely execute a collector (preferably only particularly specified one) in a more privileged container via a unix or tcp socket?

**Comment by cakrit** [comment]
> the metrics will be "hidden" in a slave database rather than integrated into the master database

Well, the metrics are no more 'hidden' than the master metrics are. It's just a different URL on the master, that shows you all the info streamed from the slave. You could perhaps put a reverse proxy in front of the master, that only shows the http://master/host/slave GUI via a different URL, if you don't want to use the node menu to show the slave's info. 

We don't have any plans currently to do what you suggested, but I can tell you that we have some very strong proponents of the idea you mentioned (wink to @ilyam8). As we move more seriously into kubernetes, we may eventually reevaluate the current architecture, that uses pipes to send metrics to a netdata daemon and that requires the whole application to be installed everywhere. But a headless collector that doesn't store anything locally and pushes all metrics to a master netdata is already very close to the suggested alternative. Once we properly provide custom dashboards via netdata.cloud, I think that the concern regarding the 'hidden' charts will also be aleviated.

**Comment by vlvkobal** [comment]
> We don't have any plans currently to do what you suggested
