### ISSUE TITLE
embed one specific graph

### ISSUE THREAD

**Issue by Wqrld** [netdata/netdata#6562]
Hi, i have a netdata instance running and i want to embed one of the graphs of my netdata instance onto the client's panel. How would i go about doing this? (Preferably with authentication so the user can't view the other client's graphs but this is not a requirement)

**Comment by Wqrld** [comment]
I have seen https://docs.netdata.cloud/web/gui/custom/#custom-dashboards but that still lets other people view your other graphs

**Comment by ilyam8** [comment]
Hey @Wqrld 	

Check this
https://docs.netdata.cloud/web/gui/confluence/

**Comment by Wqrld** [comment]
That still lets people find the original netdata instance and view other people's graphs though

**Comment by cakrit** [comment]
You'll need to set up another netdata instance, configure it as master and stream to it only the charts this person should be able to see. 

```
    # filter the charts to be streamed
    # netdata SIMPLE PATTERN:
    # - space separated list of patterns (use \ to include spaces in patterns)
    # - use * as wildcard, any number of times within each pattern
    # - prefix a pattern with ! for a negative match (ie not stream the charts it matches)
    # - the order of patterns is important (left to right)
    # To send all except a few, use: !this !that *   (ie append a wildcard pattern)
    send charts matching = *
```

**Comment by Wqrld** [comment]
Okay, its a bit of a workaround but i can work with that
