### ISSUE TITLE
Netdata showing docker container IDs despite having a networked container that exposes socket

### ISSUE THREAD

**Issue by Windyo** [netdata/netdata#6564]
##### Question summary
I'm posting this as a question because it may be a case of "didn't understand the manual".

I have Netdata in a container.
That container has a network, `nginx-proxy` which is part of a reverse proxy implementation for web access.
That network, `nginx-proxy`, is made of an nginx container, a docker-gen container, and a letsencrypt container. The nginx container has access to the Docker socket..

As per the netdata configuration that say that having a container which exposes the socket is enough, I would expect netdata to be able to resolve the docker names, instead ofjust the IDs. This does not happen.
So now I added the docker socket as readonly to the netdata container but still doesn't change.

##### OS / Environment
UbuntuServer:latest

##### Component Name
Docker Containers

##### Expected results
Shows Names

##### docker-compose file

version: '3'
services:
  netdata:
    hostname:
      netdata.domain.eu
    image: netdata/netdata
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=netdata.domain.eu
      - LETSENCRYPT_HOST=netdata.domain.eu
      - LETSENCRYPT_EMAIL=w@domain.com    
      - NETWORK_ACCESS=internal
      - NETDATA_PORT=80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

**Comment by Windyo** [comment]
ping :)

**Comment by vlvkobal** [comment]
Do you have correct permissions to the socket, as explained in the [documentation](https://docs.netdata.cloud/packaging/docker/#docker-container-names-resolution)?

**Comment by Windyo** [comment]
I understood the documentation as giving three option, not having all of them fulfilled - hence why I setup a proxy container that has access to the docker socket in its definition. Is that wrong ?

Anon

________________________________

**Comment by vlvkobal** [comment]
You are right. You should choose only one option. As for the proxy, @paulkatsoulakis or @ViViDboarder might help you.

**Comment by ViViDboarder** [comment]
Hey @Windyo. The documentation on using the proxy is a bit unclear because it doesn't provide an example of _how_ you proxy a connection to your Docker socket. It's a bit more involved than just mounting the Docker socket in a volume in an HAProxy container.

Here is an example repository (and image) that provides a proxy to the socket: https://github.com/Tecnativa/docker-socket-proxy

This is a handy way of limiting access to the socket for more than just Netdata, so I actually run the Docker Socket proxy in it's own Docker Compose file and leave it on a private network that I can add to other services that require access.

If that sounds like gibberish to you, you can just add it as a second service to your a Docker Compose file with Netdata. For example:

```yaml
version: '3'
services:
  netdata:
    image: netdata/netdata
    # ... rest of your config ...
    ports:
      - 19999:19999
    environment:
      - DOCKER_HOST=proxy:2375
  proxy:
    image: tecnativa/docker-socket-proxy
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
```

This isn't included in the official documentation because the Netdata team hasn't had a chance to fully review the image that it's using. Once that is complete, the documentation might be made more clear.

**Comment by Windyo** [comment]
Hey there !

Well in my case I actually use netdata behind a reverse proxy https://github.com/jwilder/<https://github.com/jwilder/nginx-proxy>nginx-proxy<https://github.com/jwilder/nginx-proxy>

I have it set up as individual containers - so nginx exposed to the internet, a private network bridging that and all networks I want to proxy, and a docker-gen container that has docker socket exposed.

By definition I have to have the netdata contziner join that network in order for it to be accessible anyway, hence  why I think I cover my bases. However I see that there are a few environment variables that you set - are those necessary ?

Cheers

**Comment by paulkatsoulakis** [comment]
Hello @Windyo, have you tried setting up `DOCKER_HOST=proxy:2375` variable to point to the right host:port combination your proxy that exposes the socket listens on?

**Comment by ViViDboarder** [comment]
It's good that you have netdata behind a proxy, but that same proxy won't necessarily proxy requests _to_ your Docker socket.

You might be able to make your nginx proxy do that as well, but you can take a look at how the image I shared does it here: https://github.com/Tecnativa/docker-socket-proxy/blob/master/haproxy.cfg

Essentially they setup a backend that points to the unix socket `/var/run/docker.sock` and then route HTTP requests from port `2375` to that socket.

The proxy you linked just routes HTTP requests to other Docker containers via HTTP. It uses the socket only to build the nginx configs and identify the ports. This is something different.

**Comment by Windyo** [comment]
Hmmm I've spent more time on this but I just can't get it to work. Like at all.
either I see th docker Ids, or I don't see anything.

I am sure this is just me being stupid, so if someone could help i'de be super grateful.

`version: '3'
services:
  netdata:
    hostname:
      netdata.domain.com
    image: netdata/netdata
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=netdata.domain.com
      - LETSENCRYPT_HOST=netdata.domain.com
      - LETSENCRYPT_EMAIL=stuff@domain.com   
      - NETWORK_ACCESS=internal
      - NETDATA_PORT=80
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nginx-proxy
      - netdata-docker
  proxy:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERS=1
    networks:
      - netdata-docker

networks:
  nginx-proxy:
    external: true
  netdata-docker
`

**Comment by Windyo** [comment]
So...
er.
Well I had made a typo in a variable in the .env file.
yupppppppp.

For anyone looking at this you can use @ViViDboarder's OoB solution, it works perfectly.
If you already have a docker proxy like I do, pass the Netdata container the `DOCKER_HOST=`variable pointing to your proxy.

**Comment by cakrit** [comment]
Reopening, because I'd like the documentation to reflect the interesting points raised here. @paulkatsoulakis and @prhomhyse can you take a look please?

**Comment by ViViDboarder** [comment]
@Windyo yea. Sorry I couldn't get on sooner to point you back in the right direction. Glad you got it sorted out and were able to remove the socket from the Netdata container!

I believe it would be more clear with the example if someone can review the referenced image.

**Comment by Windyo** [comment]
@cakrit pull seems to have been merged, ok to close ?

**Comment by paulkatsoulakis** [comment]
Closing for now, @cakrit feel free to reopen if you need more information to be exposed on the documentation
