### ISSUE TITLE
Network monitoring not working on Ubuntu 18.04 LTS upgraded from 14.04 LTS

### ISSUE THREAD

**Issue by voidburn** [netdata/netdata#6565]
##### Bug report summary
Installing Netdata in an Ubuntu 18.04 LTS system that has been upgraded from a 14.04 LTS and did not switch over to the Netplan network configuration system (retains the original "ifupdown" under /etc/network/interfaces) seems to be affecting Netdata's ability to detect and show networking monitors.

##### OS / Environment
Ubuntu 18.04 LTS

##### Netdata version (ouput of `netdata -V`)
netdata v1.16.0 (static binary build)

##### Component Name
Networking 

##### Steps To Reproduce
Upgrade Ubuntu to Ubuntu 18.04 LTS from 14.04 LTS (going through 16.04 LTS) using the `do-release-ugprade` commands. 

Check which network configuration system is retained (should be ifupdown, and the ethernet interface names should remain eth0, eth1, ethN). 

Install and open netdata, no network monitoring should be present. The net in/out gauges don't appear at the top and the IPV4/IPV6 sections in the right hand menu are missing.

##### Expected behavior
The network interfaces are detected and network monitoring appears correctly

**Comment by ilyam8** [comment]
> Netplan network configuration system (retains the original "ifupdown" under /etc/network/interfaces) seems to be affecting Netdata's ability to detect and show networking monitors.

This shouldnt be the case, netdata reads `/proc` to get network stats. Have you checked `error.log`? i suggest to do a service restart and check the `error.log`

**Comment by voidburn** [comment]
I checked and I do see several errors like this:
`2019-07-31 00:31:21: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/net/sockstat' (errno 13, Permission denied)`

So I went to check the actual file permissions, but unless it's trying to open it for writing I don't see why it should fail:
`-r--r--r--  1 root root 0 Jul 31 00:34 sockstat`

**Comment by vlvkobal** [comment]
What are the permissions for `/proc/net`?

**Comment by ilyam8** [comment]
> So I went to check the actual file permissions

you can try to read them as `netdata` user

> sudo su -s /bin/bash netdata; cat /proc/net/sockstat`

**Comment by voidburn** [comment]
If I try and cat the sockstat with the netdata user I do indeed get a permission denied. I checked all symlinks on the way to /proc/self/net (as the netdata user):

lrwxrwxrwx  1 root root 0 Jul 19 13:56 self -> 142291
dr-xr-x---   7 netdata root 0 Jul 31 13:44 142291
dr-xr-xr-x  13 netdata root 0 Jul 31 13:32 net
-r--r--r--  1 root root 0 Jul 31 13:37 sockstat

yet I still get the permission denied error when trying to cat it. The fresh install looks identical but I can cat without issues. I've never seen this before.

**Comment by voidburn** [comment]
Small update: it appears that all pid folders under /proc are missing the executable flag, this is definitely not a netdata bug. I will try and drill down on the problem and figure out how it breaks during the upgrades and how to fix it.

**Comment by voidburn** [comment]
Replacing the installed kernel (OVH custom 3.14) with the ubuntu generic kernel did the trick. That was the culprit of this behavior.
