### ISSUE TITLE
Set alarm for CPU temperature in FreeNAS

### ISSUE THREAD

**Issue by Zamana** [netdata/netdata#6566]
#### Set alarm for CPU temperature in FreeNAS

Hi!

I would like to implement an alarm to raise when my CPU gets hot. I check the /usr/local/etc/netdata/health.d/cpu.conf but was unable to understand, by reading the documentation, how do I actually set the temperature check on CPU.

Can anybody help?
Thanks.
Regards.

**Comment by ilyam8** [comment]
Hi @Zamana 	

Check https://github.com/netdata/netdata/issues/2107#issue-222995778

**Comment by Zamana** [comment]
Hi ilyam8!

Thank you very much!!!

This is working for me now:

`alarm   : temperature_out
on      : cpu.temperature
os      : freebsd
hosts   : *
calc    : ($cpu0.temp + $cpu1.temp + $cpu2.temp + $cpu3.temp + $cpu4.temp + $cpu5.temp + $cpu6.temp + $cpu7.temp) / 8
units   : C
every   : 5s
warn    : $this > 30
crit    : $this > 50
#delay  : 1m
info    : CPU temperature is out of spec
to      : sysadmin`

/usr/local/etc/netdata/health.d/cpu_temp.conf

Thanks a lot!
