### ISSUE TITLE
Soft failures in Travis CI

### ISSUE THREAD

**Issue by knatsakis** [netdata/netdata#6568]
##### Question summary
.travis.yml currently contains some configuration for _soft failures_, i.e.: 
```
matrix:
  allow_failures:
    - env: ALLOW_SOFT_FAILURE_HERE=true
```
and 
```
ALLOW_SOFT_FAILURE_HERE=true
```
variables in some jobs.
However, this mechanism does not seem to work and it does not seem straightforward to fix it.

What is the intention behind this mechanism?
Should it be fixed (or replaced by something else)? Or removed altogether?

##### Component Name
CI/CD [.travis.yml]

**Comment by knatsakis** [comment]
@paulkatsoulakis maybe you could shed some light?

**Comment by paulkatsoulakis** [comment]
Hi @knatsakis, yes this comes from the early stages of development on Travis CI.
To be honest i do not recall if this worked for me after all or not, but i left it aside to re-evaluate once the heavy stuff come by.

Have you confirmed that this is indeed not working as intended ?

**Comment by knatsakis** [comment]
Hi @paulkatsoulakis,

I have confirmed it. For example you can see in [this](https://travis-ci.org/knatsakis/netdata/builds/566215771) build, that a job with ALLOW_SOFT_FAILURE_HERE has failed but the build was not marked successful and the rest of the stages were not executed.

Besides, this is in accordance with the documentation. As stated [here](https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail):

> When matching jobs against the definitions given in allow_failures, all conditions in allow_failures must be met exactly, and **all the keys in allow_failures element must exist in the top level of the build matrix (i.e., not in matrix.include).**

and later:

> **Without the top-level env, no job will be allowed to fail.**

By the way, if the packages are built in parallel, (as with #6579), one failed package does not affect the others. For example see [this](https://travis-ci.org/knatsakis/netdata/builds/566203318) build.

Should I create a PR to remove ALLOW_SOFT_FAILURE HERE?

**Comment by knatsakis** [comment]
After recent changes to `.travis.yml`, it seems that `ALLOW_SOFT_FAILURE_HERE` works again as intended.

Closing this issue.
