### ISSUE TITLE
Unable to trigger alarm for mysql.connections_active

### ISSUE THREAD

**Issue by johnramsden** [netdata/netdata#6569]
##### Question summary

I'm unable to trigger alarms for mysql.connections_active. I receive alerts when running the test alarm and receive other alerts, but it appears that mysql.connections_active is always staying in a non warning state.

I even tried setting:

```
template: mysql_connections
      on: mysql.connections_active
    calc: $active * 100 / $limit
   units: %
   every: 10s
    warn: $this > (($status >= $WARNING)  ? (0) : (100))
    crit: $this > (($status == $CRITICAL) ? (0) : (100))
   delay: down 1m multiplier 1.5 max 1h
    info: the ratio of current active connections vs the maximum possible number of connections
      to: dba
```

And when I look at the badge for the alert it shows up as green. I basically want to be warned whenever my connections active goes over 20%. But I can't get it to alert at all.

##### OS / Environment

Ubuntu 14.04

##### Component Name

health

##### Expected results

Alerted on MySQL connections active over threshold

**Comment by ilyam8** [comment]
hi @johnramsden 	

> I basically want to be warned whenever my connections active goes over 20%.

> warn: $this > (($status >= $WARNING)  ? (0) : (100))
> crit: $this > (($status == $CRITICAL) ? (0) : (100))

See your warn/crit conditions.

`warn` if `$calc` > 100 (if status < WARNING)
`warn` if `$calc` > 0 (if status >= WARNING)

**Comment by johnramsden** [comment]
Does that mean the defaults are wrong?

https://github.com/netdata/netdata/blob/63114bceddd8ee6916f0c8e5c642a579c2dfc1ac/health/health.d/mysql.conf#L65-L74

**Comment by ilyam8** [comment]
>  warn: $this > (($status >= $WARNING)  ? (60) : (70)) 
>  crit: $this > (($status == $CRITICAL) ? (80) : (90)) 

These are good, warn alarm will trigger when `$active * 100 / $limit` > 70

**Comment by johnramsden** [comment]
Oh, [I see](https://docs.netdata.cloud/health/#special-use-of-the-conditional-operator). I misinterpreted that as warn between 60 and 70, critical between 80 and 90.

Thanks @ilyam8 .
