### ISSUE TITLE
More information on Netdata Nodes Console

### ISSUE THREAD

**Issue by pogzie** [netdata/netdata#6571]
I just started using Netdata due to its ease of use. I am planning to promote it to production in the coming months but one feature I'd hope to get applied is to have more data in the Nodes console. This would save me the time doing a custom template and manually add each everytime theres a new server. At the very least, the Nodes console could give me my complete asset overview.

##### Feature idea summary
- Have additional data or information on the boxes on the Netdata Nodes console https://i.imgur.com/4Ifwv7G.png 

##### Expected behavior
- Something like this (CPU, memory, disk) https://i.imgur.com/YrzffJE.png 
- And a dark theme fore Nodes overview :)

**Comment by ilyam8** [comment]
> And a dark theme fore Nodes overview :)

:handshake:

**Comment by gpapamathND** [comment]
Hmmm interesting request @pogzie :) 

@ivorjvr I think you have proposed a similar design.

**Comment by ivorjvr** [comment]
@gpapamathND think the % availability must indicate uptime. I have created something similar in the past and plan to flesh it out. But will consider using bar chart like the one above. 

Dark theme will come soon :)

@pogzie thanks for the idea

**Comment by cakrit** [comment]
The next version will have a lot more info and some basic customization. I'm closing this one because it's definitely one of the things we're building, but we won't provide the update here. Look out for the next release, in the next couple of months! :)
