### ISSUE TITLE
What unit of measurement is "read/s" on the chart ZFS reads.

### ISSUE THREAD

**Issue by kyleaupton** [netdata/netdata#6576]
##### Question summary
I want to monitor reads on my ZFS file system and was wondering what unit of measurement "reads/s" on the chart zfs.reads is.
##### OS / Environment
Ubuntu 16.04.1 LTS with zfs version "0.6.5.6-0ubuntu10"
##### Component Name
zfs.reads
##### Expected results
Units like MB/s or something similar.

Any help would be appreciated as I am new to netdata. Thanks!

**Comment by vlvkobal** [comment]
`reads/s` means the number of reads (read operations) per second.

**Comment by kyleaupton** [comment]
Ah, gotcha. Thanks!
