### ISSUE TITLE
Implement graphql

### ISSUE THREAD

**Issue by websitevirtuoso** [netdata/netdata#6577]
I found article about categories http

https://medium.com/hackernoon/the-spectacles-of-a-web-server-log-file-90c995e9e986#.ab7wdadz0
```
nginx_netdata:                        # name the charts
  path: '/var/log/nginx/access.log'   # web server log file
  categories:
    badges      : '^/api/v1/badge\.svg'
    charts      : '^/api/v1/(data|chart|charts)'
    registry    : '^/api/v1/registry'
    alarms      : '^/api/v1/alarm'
    allmetrics  : '^/api/v1/allmetrics'
    api_other   : '^/api/'
    netdata_conf: '^/netdata.conf'
    api_old     : '^/(data|datasource|graph|list|all\.json)'
```

More and more system and my as well using graphql protocol.

**Comment by cakrit** [comment]
Perhaps `/api/v2`? What do you think @cosmix ?

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
