### ISSUE TITLE
no clear notifications with repeat feature

### ISSUE THREAD

**Issue by pschiffe** [netdata/netdata#6581]
Hi all,

##### Bug report summary
I'm not receiving `CLEAR` (green) notifications any more after the upgrade to netdata 1.16 and enabling the repeat notification feature. Also, I don't see the alarms in web ui Alarms Log.

Config change to enable the repeat feature:
```
[health]
        stock health configuration directory = /etc/netdata/conf.d/health.d
        default repeat warning = 2h
        default repeat critical = 1h
```

##### OS / Environment
```
# /usr/libexec/netdata/plugins.d/system-info.sh 
NETDATA_SYSTEM_OS_NAME="CentOS Linux"
NETDATA_SYSTEM_OS_ID=centos
NETDATA_SYSTEM_OS_ID_LIKE=rhel fedora
NETDATA_SYSTEM_OS_VERSION=7 (Core)
NETDATA_SYSTEM_OS_VERSION_ID=7
NETDATA_SYSTEM_OS_DETECTION=/etc/os-release
NETDATA_SYSTEM_KERNEL_NAME=Linux
NETDATA_SYSTEM_KERNEL_VERSION=3.10.0-957.21.3.el7.x86_64
NETDATA_SYSTEM_ARCHITECTURE=x86_64
NETDATA_SYSTEM_VIRTUALIZATION=kvm
NETDATA_SYSTEM_VIRT_DETECTION=systemd-detect-virt
NETDATA_SYSTEM_CONTAINER=none
NETDATA_SYSTEM_CONTAINER_DETECTION=systemd-detect-virt
```

##### Netdata version (ouput of `netdata -V`)
```
# netdata -V
netdata v1.16.0
```

##### Component Name
health

##### Steps To Reproduce
Upgrade to netdata 1.16, globally enable repeat notification feature as described above, wait for alarm. You should receive notification with raised alarm, and once the the alarm is gone, clear notification. I didn't receive repeated notification nor clear notification.

##### Expected behavior
Receive clear notification if alarm is gone. Also it should be visible in Alarm Log in web ui, currently it's not.

**Comment by pschiffe** [comment]
Update - I'm receiving repeated notifications, and when the alarm is active, I can see it in Active Alarms in web ui, but not in Log.

**Comment by thiagoftsm** [comment]
Hi @pschiffe ,

I will verify this. Thanks to give use the initial report and the update for it.

**Comment by cakrit** [comment]
This is high priority.

**Comment by thiagoftsm** [comment]
I am working on this right now.
