### ISSUE TITLE
display netdata service uptime in dashboard

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#6584]
##### Feature idea summary
It would be nice if we knew how long the netdata service has been up for by just looking at the netdata dashboard.

We could change this:
```
netdata on newyork.netdata.rocks, collects every second 1,406 metrics
```
to something like this:
```
netdata on newyork.netdata.rocks (service running for 23 hours), collects every second 1,406 metrics
```

**Comment by ilyam8** [comment]
Fixed in https://github.com/netdata/netdata/pull/10997
