### ISSUE TITLE
Accessing plugin data using a textonly chart type without drawing an additional linechart

### ISSUE THREAD

**Issue by set-element** [netdata/netdata#6585]
Greetings,

I have a question about taking data from a python plugin and getting it to display in a textonly format in the dashboard without needing to display an additional line chart of that data.  If I draw a line chart with the data as well as using the textonly display everything works great.

I have tried using hidden charts as well as hidden dimensions as a way to get the data to the dashboard namespace, but both fail with a:

> chart not found on url "/api/v1/chart?chart=TestSystem.uptime"

error.  Manually going to the referenced url provides all the normal and expected information.

The textonly box is being generated via:

```
<div
  data-netdata="TestSystem.uptime"
  data-chart-library="textonly"
  data-textonly-suffix="%"
  data-update-every="2"
  style="display: inline">
</div>
```

My apologies if I am missing something blindingly obvious here - any assistance would be greatly appreciated!

thank you,
scott

##### Question summary
Is it possible to 
##### OS / Environment
CentOS release 6.5
netdata version: netdata v1.15.0-70-g8e72397

**Comment by ilyam8** [comment]
from what i know it is impossible

https://github.com/netdata/netdata/issues/5634#issuecomment-472984683

**Comment by set-element** [comment]
Thank you for the quick reply!  If I come up with a decent workaround I will post the results here.  
cheers,
scott
