### ISSUE TITLE
netdata docker-compose not send alert slack channel

### ISSUE THREAD

**Issue by wsj31013** [netdata/netdata#6586]
##### Question summary
I recently installed netdata using a docker-compose.
I inserted "SLACK_WEBHOOK_URL, SLACK_CHANNEL" in the docker-compose.yml file to send the message to slack, but it is not sent.
I've looked at a lot of netdata official documents.
There seems to be no related setting. Could you tell me why the message is not being sent to Slack?

I wrote a variable using the environment directive, but the message is not sent, so entering the docker container and modifying the file below directly sends a message.
Rather than go directly into the container and modify the file
Is there a way to set it up with only the docker-compose file?
Could you share your configs?

Thanks.

##### OS / Environment
1. Platform : AWS EC2
2. OS : Ubuntu 16.04.5 LTS (Xenial Xerus) 64bit
3. Kernel : 4.4.0-138-generic
4. Docker : 18.09.8
5. Docker-compose : 1.24.1, build 4667896b

docker-compose.yml : 
```sh
version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: ip-172.31.XXX.XXX.ap-northeast-2.compute.internal
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ubuntu/netdata_custom_cpu.conf:/etc/netdata/health.d/cpu.conf:ro
      - /home/ubuntu/netdata_custom_ram.conf:/etc/netdata/health.d/ram.conf:ro
    environment:
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/XXXX
      - SLACK_CHANNEL=my channel name
      #- DEFAULT_RECIPIENT_SLACK=my channel name

```

##### Docker inspect
```sh
$ docker inspect ubuntu_netdata_1 | grep -i slack

"SLACK_WEBHOOK_URL=https://hooks.slack.com/services/XXXX
"SLACK_CHANNEL=my slack channel name"

```

#### Edit health_alarm_notify.conf and Alert messages test
```sh
$ docker exec -it ubuntu_netdata_1 bash
bash-4.4# vi /usr/lib/netdata/conf.d/health_alarm_notify.conf

SLACK_WEBHOOK_URL="https://hooks.slack.com/services/XXXX"
DEFAULT_RECIPIENT_SLACK="my slack channel name"

bash-4.4# killall -USR2 netdata
bash-4.4# bash -x /usr/libexec/netdata/plugins.d/alarm-notify.sh test

Logs
2019-08-02 09:32:08: alarm-notify.sh: INFO: sent slack notification for: ip-172.31.XXX.XXX.ap-northeast-2.compute.internal test.chart.test_alarm is CLEAR to '#my slack channel name'

```

**Comment by cakrit** [comment]
I assume that the test you have at the end of the post is outside the container, right?

 Passing the environment variables as you do in docker-compose.yml won't affect alarm-notify.sh, it will still read the settings from the stock alarm config. Why don't you mount one more volume with `/usr/lib/netdata/conf.d/health_alarm_notify.conf`?

**Comment by wsj31013** [comment]
Hi cakrit.
Thanks for reply. You are right.
first of all, end of the post is inside the container.
I thought the docker environment variable would automatically send an alarm to the slack channel in the container, which was not true.
I wondered if there was a way to send an alarm to the Slack channel with only a docker environment variable called environment.

As you say, mount /usr/lib/netdata/conf.d/health_alarm_notify.conf with the "volumes" parameter and it should work. :)

**Comment by cakrit** [comment]
Happy to help.
