### ISSUE TITLE
Users have the impression db is limited to 1h

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#6587]
##### Feature idea summary

Articles are being written about netdata all over the place.

However, most of the users have the impression that the database size of netdata is limited to just 1h. They are aware that:

1. They can configure the database size, for any duration
2. There is a new database in netdata that decouples the memory footprint of netdata and the database size. This actually means users can provide enough disk space even for very large databases and still netdata will use just a fraction of that in memory.

##### Expected behavior

We need to somehow let the users know of the above.

For example, we could make the memory size at the dashboards a link to a page that explains how users can configure the database size:

![image](https://user-images.githubusercontent.com/2662304/62365659-49556600-b52d-11e9-81e0-a0ac6d1b8b21.png)

We could also provide a message at the charts when a chart is panned beyond its available past:

![image](https://user-images.githubusercontent.com/2662304/62365811-ae10c080-b52d-11e9-8006-c81db51ce292.png)

We should also emphasize it at the installation guide: https://docs.netdata.cloud/packaging/installer/ as one of the first things the users should do.

There is already a relative section in the Getting Started Guide: https://docs.netdata.cloud/docs/gettingstarted/ but it may have to be moved first. Also its current title "Sizing Netdata" may not be straight forward for most users on what it means.

The new database engine is big news for netdata. It should have quite an announcement at the README file of the repo.

Of course, more ideas are welcome.

This is also very important for netdata.cloud. At the nodes view and everywhere the node appears, it is crucial to show its database size. Of course this gets a bit more complicated with replication (the same data may exist in multiple nodes with different retention policies each), still this information is very important and should be presented.

**Comment by joelhans** [comment]
I don't know if the installation page(s) are the right place for information about configuring the database/history size, but I'll do a review to see where it could make sense.

The getting started guide is definitely in need of some attention. I'll move it up on my priority list and put more emphasis on increasing history size and/or using DB engine. I'll report back here when I've made progress on either of these fronts.

**Comment by cakrit** [comment]
@joelhans let's get some suggestions on the content (phrasing & link) that we could add to the two places of the agent UI Costas suggested. The work of putting it there needs to be done by our front-end people.

**Comment by joelhans** [comment]
I'm starting to wonder if I could write up a very short tutorial about increasing history size, both via the `history` config and the DB engine. Then we could link only to that. But, for the time being...

**For this space:**

![image](https://user-images.githubusercontent.com/2662304/62365659-49556600-b52d-11e9-81e0-a0ac6d1b8b21.png)

Here's a template for phrasing that sentence, including some small grammatical fixes. Obviously, changing all the code blocks with the info from the agent.

> Every second, Netdata collects `#` metrics, presents them in `#` charts and monitors them with `#` alarms. Netdata is using `#` MB of memory on `HOSTNAME` for `#` hour, `#` minutes, and `#` seconds of real-time history. 
> 
> Get more history by [configuring Netdata's `history`](https://docs.netdata.cloud/daemon/config/#global-section-options) or using the [DB engine](https://docs.netdata.cloud/database/engine/).

**For the available space when panning:**

![image](https://user-images.githubusercontent.com/2662304/62365811-ae10c080-b52d-11e9-8006-c81db51ce292.png)

> Want to extend your history of real-time metrics? [Configure Netdata's `history`](https://docs.netdata.cloud/daemon/config/#global-section-options) or use the [DB engine](https://docs.netdata.cloud/database/engine/).

**Comment by cakrit** [comment]
@jacekkolasa you can do this as a short break from your refactoring.

**Comment by jacekkolasa** [comment]
@cakrit sure :+1:

**Comment by jacekkolasa** [comment]
PR is ready. I didn't restrict the history tip, so @cakrit @ktsaou please let me know if you want me to give an option for the user to turn it off (via global variable), or maybe disable it by default in custom dashboards. The feature doesn't cause any significant performance impact

**Comment by jacekkolasa** [comment]
Oh and the sticky-note is only for Dygraph - is it ok?

**Comment by cakrit** [comment]
> PR is ready. I didn't restrict the history tip, so @cakrit @ktsaou please let me know if you want me to give an option for the user to turn it off (via global variable), or maybe disable it by default in custom dashboards. The feature doesn't cause any significant performance impact

Not sure about the benefit of this then. 

> Oh and the sticky-note is only for Dygraph - is it ok?

It's on what we use most on the agent UI, which is fine.
