### ISSUE TITLE
Can we use unmodified Netdata release as a monitoring service for commercial PaaS project?

### ISSUE THREAD

**Issue by heqingy** [netdata/netdata#6591]
Hi, 

We are looking for a system real-time monitoring tools. We noticed that Netdata is under GPL.

My question is:

If we create an AWS AMI with unmodified Netdata service installed, and expose the Netdata port for web access, do we need to worry about GPL and make our product released as GPL?

**Comment by cakrit** [comment]
Hi @heqingy,

We don't see an issue, but we suggest you consult your lawyers for such matters.
