### ISSUE TITLE
Charts not showing on WSL

### ISSUE THREAD

**Issue by MayhemBill** [netdata/netdata#6593]
##### Question summary
The short question: I recently found this service, and I've installed it on several of my servers, Specifically Ubuntu 18.04 and Ubuntu WSL 18.04 (Ubuntu on Windows Server) and for some reason there are missing charts on the WSL version. the only things that show on WSL is CPU RAM and SWAP, is this intentional?

**Comment by mfundul** [comment]
WSL is an emulation layer for linux user space applications in Windows operating systems. Since its nature is to only intercept POSIX system calls there is no linux kernel running. Therefore, if you install netdata in WSL, you don't have access to any of the host hardware or native applications.

Even if there was a linux kernel in place, which should be the case for WSL version 2 with the help of Hyper-V, netdata will still be inside a virtualized environment with no direct access to host resources.

**Comment by ilyam8** [comment]
Hey @MayhemBill 	

There is an option to collect windows metrics from linux server using netdata, take a look

> https://github.com/netdata/go.d.plugin/tree/master/modules/wmi

**Comment by mfundul** [comment]
> 
> 
> Hey @MayhemBill
> 
> There is an option to collect windows metrics from linux server using netdata, take a look
> 
> > https://github.com/netdata/go.d.plugin/tree/master/modules/wmi

Ideally you could send the WMI metrics directly to your WSL netdata installation.

**Comment by MayhemBill** [comment]
Thanks for the info, I'll give an install and report back here.

**Comment by MayhemBill** [comment]
@ilyam8 So I've installed wmi_exporter but I'm having some issues configuring the plugin, from my understanding I've enabled the go.g.plugin, but I don't understand where I'm supposed to put the wmi.conf file so that it will actually be read by the plugin.

**Comment by ilyam8** [comment]
My netdata installed in `/opt`

```
[ilyam@pc netdata]$ pwd
/opt/netdata/etc/netdata
[ilyam@pc netdata]$ sudo ./edit-config go.d/wmi.conf
[sudo] password for ilyam: 
Copying '/opt/netdata/usr/lib/netdata/conf.d/go.d/wmi.conf' to '/opt/netdata/etc/netdata/go.d/wmi.conf' ... 
Editing '/opt/netdata/etc/netdata/go.d/wmi.conf' ...
```

You need to uncomment and modify `jobs` section

```yaml
jobs:
  - name: win_server1
    url: http://10.0.0.1:9182/metrics
    update_every: 5
    timeout: 5

  - name: win_server2
    url: http://10.0.0.2:9182/metrics
    update_every: 5
    timeout: 5
```

in case of any problems run `go.d.plugin` in debug mode
 - cd to `plugins.d`
 - become netdata user (`sudo su -s /bin/bash netdata`)
 - run `./go.d.plugin -d -m wmi`

**Comment by ilyam8** [comment]
plugins.d dir

```
test@deb92:~$ ps aux | grep -m 1 -E -o "[a-z/.]+plugins.d"
/opt/netdata/usr/libexec/netdata/plugins.d
```

`update_every` and `timeout` are optional, you need to set them if you see gaps on charts, but it is very likely you will need to increase them

**Comment by MayhemBill** [comment]
Okay, it was a config issue, I must have missed the first test, is there a way to show the metrics on the overview? specifically the net up/down?

**Comment by ilyam8** [comment]
Unfortunately no, all go.d.plugin modules follow same logic - they have `<module name> <job name>` section on the dashboard and all metrics under it.

You can write custom dashboard but it will be a lot of work, so it is still an option, but the option is far from good.

stock wmi alarms btw

> https://github.com/netdata/netdata/blob/master/health/health.d/wmi.conf
