### ISSUE TITLE
Netdata not creating index with rrdcalc_create_from_template

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6594]
##### Bug report summary
During the development of a new feature for Netdata, I notice that every time that I tried to create a new alarm from template, I had the following group of errors:

2019-08-04 23:53:08: netdata ERROR : PLUGIN[proc] : Cannot insert the alarm index ID 10min_cpu_usage
2019-08-04 23:53:08: netdata ERROR : PLUGIN[proc] : Cannot insert the alarm index ID 10min_cpu_iowait
2019-08-04 23:53:08: netdata ERROR : PLUGIN[proc] : Cannot insert the alarm index ID 20min_steal_cpu
2019-08-04 23:53:09: netdata ERROR : PLUGIN[proc] : Cannot insert the alarm index ID interface_speed

##### OS / Environment
Slackware Linux Current
##### Netdata version (ouput of `netdata -V`)
I am using `netdata v1.16.1-1-g5a2026cb`, but this is present since the first time that the the index alarms_idx_health_log was introduced to Netdata.
##### Component Name
Health
##### Steps To Reproduce
It only necessary to run netdata with a template alarm.
##### Expected behavior
We need to insert the alarm inside the index.

**Comment by cakrit** [comment]
I don't understand the description of this issue. `alarms_idx_health_log` is already in the master branch and all existing alarm templates are being loaded without errors (so the steps to reproduce don't seem to be as described).  So what exactly is it that causes this in production?

**Comment by ilyam8** [comment]
> During the development of a new feature for Netdata

https://github.com/netdata/netdata/pull/6560

**Comment by cakrit** [comment]
So this isn't a bug report then, it's a PR issue that needs to be resolved. If that's the case, please close this.

**Comment by thiagoftsm** [comment]
I already gave the solution in the PR that I created for template, I saw a relationship between what I was doing with this, and I changed the code in the PR.
