### ISSUE TITLE
Netdata keeps connections as established

### ISSUE THREAD

**Issue by dbeledrin** [netdata/netdata#6598]
Hi all,

I have the following case in my infrastructure:

**On my client-server side, I have stopped the netdata service and also there is no active connection towards port 4242:**
```

> systemctl status netdata

● netdata.service - Real time performance monitoring
   Loaded: loaded (/usr/lib/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: **inactive** (dead) since Fri 2019-08-02 12:53:49 EEST; 3 days ago
  Process: 23390 ExecStart=/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep (code=exited, status=0/SUCCESS)
  Process: 23387 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 23385 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 23383 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 23380 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 23390 (code=exited, status=0/SUCCESS)

```

**But... on my netdata server, I see multiple established connections from the above client...**

```
> netstat -tunp | grep 4242 | grep X.X.X.X (--> client server's IP)


tcp6       0      0 netdata-server-IP:4242      X.X.X.X:34856       ESTABLISHED 18428/influxd
tcp6       0      0 netdata-server-IP:4242      X.X.X.X:33344       ESTABLISHED 18428/influxd
tcp6       0      0 netdata-server-IP:4242      X.X.X.X:34918       ESTABLISHED 18428/influxd
tcp6       0      0 netdata-server-IP:4242      X.X.X.X:35330       ESTABLISHED 18428/influxd
tcp6       0      0 netdata-server-IP:4242      X.X.X.X:34826       ESTABLISHED 18428/influxd_
```

**What is even weirder, is that I have set a limit on my netdata server to not accept more than 3 connections from the same IP:**

> iptables -nL

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  127.0.0.1            0.0.0.0/0
REJECT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:4242 flags:0x17/0x02 #conn src/32 > 3 reject-with icmp-port-unreachable
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination_
```

Also, the specific problem occurs only from VMs that are on Azure.

My OS on both client and netdata server: CentOS Linux release 7.6.1810 (Core)
Netdata version:  netdata v1.14.0-30-g63de71a

Do you happen to have any idea of what might be causing this? Do you need any more info that I have failed to mention?

Thank you in advance for any feedback.

**Comment by ilyam8** [comment]
@dbeledrin 	
correct me if i am wrong

- you have master slave setup
- you stopped netdata service on the slave 3 days ago
- you see ESTABLISHED connectionf from the client on master

?

**Comment by dbeledrin** [comment]
Hi @ilyam8 ,

Thank you for your reply.

Your points are correct. I have a netdata server and clients that connect to port 4242 to provide the data.

I did stop the service on one of the clients but my master server kept showing the connection from the specific client as "ESTABLISHED".

One point I forgot to mention is that the problem only clears when I restart the netdata service on my master server. So this is why I'm thinking that it might be a netdata issue. Maybe some fine tuning in the configuration that I have missed?

**Comment by cakrit** [comment]
I did a test with the slave running on Ubuntu 18.04 and the client (slave) properly closes the connection, even if I stop the slave netdata with a `kill -9`. Can someone test on CentOS to see if there's a difference? Basically do `netstat -tunp | grep 19999` on the master to see the connected slave, kill the connected slave and see if the connection disappears, as it should. The ideal scenario to try and replicate would be a CentOS slave with a CentOS master, both 7.6.1810 (Core)

**Comment by dbeledrin** [comment]
Hi @cakrit !!

Long time, no see :)

Thanks for the tests.

To be honest, I think it might be a mix of netdata/Azure issue, since:

1. I don't have the same problem with master/clients that are not on Azure.
2. The problem is resolved (for the Azure VMs), only when I restart the netdata service.

Of course, I might be wrong but I think I have tested everything else.

**Comment by cakrit** [comment]
Thanks @dbeledrin I was on leave :)
Are you using the Azure load balancer by any chance? I saw [this](https://docs.microsoft.com/en-gb/azure/load-balancer/load-balancer-tcp-reset) which may be useful. But they do say [here](https://serverfault.com/questions/661704/azure-closing-idle-network-connections/661984) that if you do use it, there's a default timeout of 4mins. 

I then saw [this rant](https://joonas.fi/2017/01/23/microsoft-azures-networking-is-fundamentally-broken/) that said amongst other complaints that 

> When a session is disconnected, all incoming packets are blackholed instead of issuing an RST packet which would correctly let the sender know of connection issue, instead of just waiting and waiting.

So my guess is that the latter is what you're facing and that using the load balancer with a reasonable timeout would resolve it.

**Comment by dbeledrin** [comment]
@cakrit , thank you for the articles.

We are not using the Azure load balancer.

If this helps in any way, we have also tried shutting down the Azure VM and the connection keeps appearing as "ESTABLISHED".

Also, I have narrowed the keepalive on the master side
[]# sysctl -p
net.ipv4.tcp_keepalive_time = 30
net.ipv4.tcp_keepalive_intvl = 5
net.ipv4.tcp_keepalive_probes = 3

I will also set the same values on the client to see if it will make any difference.

Is there any netdata configuration that might be causing this? (although there is no problem with non-Azure VMs).

**Comment by cakrit** [comment]
> Is there any netdata configuration that might be causing this? (although there is no problem with non-Azure VMs).

There's nothing on the netdata side that I know of. From the last link I sent, it does look like an Azure issue, as far as I understand. Maybe someone else has had similar experience and can chip in.

**Comment by dbeledrin** [comment]
Ok, thanks again for all the input. :)
