### ISSUE TITLE
Make MongoDB backend multithreaded

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#6599]
##### Feature idea summary
The `mongoc` library blocks execution of the metric archiving process until all buffered data has been sent and a response has been received from the database. Blocking operations should be run in separate threads to allow Netdata buffering more than one batch of metrics at a time.

##### Expected behavior
Netdata sends metrics to a MongoDB database in a nonblocking way.

**Comment by cakrit** [comment]
We won't proceed with this approach, but with a refactoring of backends.
