### ISSUE TITLE
netdata re-enables itself after being disabled

### ISSUE THREAD

**Issue by chesty** [netdata/netdata#6601]
##### Bug report summary

netdata re-enables itself and starts on next reboot after being disabled and stopped

##### OS / Environment

ubuntu 18.04 lts

##### Netdata version (ouput of `netdata -V`)

netdata v1.16.1

##### Steps To Reproduce

1. install netdata with `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
2. stop and disable netdata `systemctl disable netdata` and `systemctl stop netdata`
3. confirm netdata is dead and disabled `systemctl status netdata`
4. change the checksum in /var/lib/netdata/netdata.tarball.checksum to force an update
5. run /usr/libexec/netdata/netdata-updater.sh
6. check netdata is still dead and disabled `systemctl status netdata`

If netdata-updater finds a new version, it runs `./netdata-installer.sh --auto-update  --dont-wait --dont-start-it` 

The new version is installed and it's not started, however `systemctl status netdata` show's it's now enabled, and netdata will start on the next reboot.

##### Expected behavior

If I stop and disable netdata, it stays stopped and disabled.

ps. I find netdata very useful and thank you to the creator(s) and the community for their work.\

**Comment by paulkatsoulakis** [comment]
Hello @chesty, thank you very much for your report!

That is a very good point, our installer as we speak always assumes you execute it with intend to get netdata up & running.

This is why we always do:
```
383                                 echo >&2 "Installing systemd service..."
384                                 run cp system/netdata.service "${SYSTEMD_DIRECTORY}/netdata.service" &&
385                                         run systemctl daemon-reload &&
386                                         run systemctl enable netdata &&
387                                         return 0
```

I don't know if we can tell when the service was manually disabled, to avoid re-enabling it.
I 'll investigate it and let you know. In the meantime any ideas on the matter are most welcome

**Comment by paulkatsoulakis** [comment]
Ok fine, so we can tell that netdata is enabled by running `systemctl is-enabled netdata` and then handle the mentioned step accordingly.

I 'll push a PR right now, thanks again @chesty for bringing this up!
