### ISSUE TITLE
broken /api/v1/info on macOS

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata#6608]
##### Bug report summary
`/api/v1/info` call on macOS returns improper JSON:
```
...
	"os_name": "	Mac OS X ",
	"os_id": "mac",
	"os_id_like": "mac",
	"os_version": "	10.14.6 ",
...
```
The leading white spaces in value fields are not valid and result in parsing error. When combined with 200 response this can be quite confusing.

##### OS / Environment
macOS Mojave 10.14.6 (obviously)

##### Netdata version (ouput of `netdata -V`)
v1.16.1-32-gf68e6160

##### Expected behavior
having access to jQuery, this should log the data:
`$.get('http://localhost:19999/api/v1/info', (data) => { console.log('success', data) })`

Alternatively, it's quite easy to check in Firefox because it automatically parses the JSON and shows error if it's present, just open new tab and go to http://localhost:19999/api/v1/info

**Comment by thiagoftsm** [comment]
We already have a PR that solves this issue, the PR #6612 , but we are needing somebody to test it for we merge.

**Comment by ilyam8** [comment]
@jacekkolasa is the best person to test it :smile:

**Comment by thiagoftsm** [comment]
I have to agree with you :smile: , @jacekkolasa case you have a time, please, can you test the PR for us? I already tested it in different flavors of Linux and the result was expected, but I cannot test on Mac.

**Comment by jacekkolasa** [comment]
@thiagoftsm @ilyam8 confirming, works good now and JSON.parse is successful on mac

**Comment by thiagoftsm** [comment]
Thanks @jacekkolasa !
