### ISSUE TITLE
Netdata update error

### ISSUE THREAD

**Issue by pkd809** [netdata/netdata#6614]
On updating netdata through bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates
The version on netdata GUI is 16.1.0 while on the host i.e netdata -V it shows 16.1.1.
Initially when i installed netdata and tried to edit stream.conf it said .stream.conf.sw alreasy exists,which I had overwritten.
Now it neither updates the netdata even after uninstallation nor streams properly to master.Gives graphs at uneven time intervals.

Please resolve!!!!!

**Comment by ilyam8** [comment]
@pkd809 you forget to add text

**Comment by pkd809** [comment]
On updating netdata through bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates
The version on netdata GUI is 16.1.0 while on the host i.e netdata -V it shows 16.1.1.
Initially when i installed netdata and tried to edit stream.conf it said .stream.conf.sw alreasy exists,which I had overwritten.
Now it neither updates the netdata even after uninstallation nor streams properly to master.Gives graphs at uneven time intervals.

Please resolve!!!!!

**Comment by pkd809** [comment]
> On updating netdata through bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates
> The version on netdata GUI is 16.1.0 while on the host i.e netdata -V it shows 16.1.1.
> Initially when i installed netdata and tried to edit stream.conf it said .stream.conf.sw alreasy exists,which I had overwritten.
> Now it neither updates the netdata even after uninstallation nor streams properly to master.Gives graphs at uneven time intervals.
> 
> Please resolve!!!!!

.stream.conf.sw file existed somewhere on the root.

**Comment by ilyam8** [comment]
> Gives graphs at uneven time intervals.

Could you give more details about it? Some screenshots?

**Comment by pkd809** [comment]
> > Gives graphs at uneven time intervals.
> 
> Could you give more details about it? Some screenshots?

Sorry being a new user to netdata I did't expect such errors earlier.It streams well for other servers but it is problematic on this one. Its an ubuntu 16.04 Xenial server.
 

Also plz suggest on how to add charts if sevices run on different containers on the same server.I have already installed netdata container on it.

**Comment by ilyam8** [comment]
Np :wink: 

> It streams well for other servers but it is problematic on this one. Its an ubuntu 16.04 Xenial server.

What is your problem? Elaborate what is "problematic"? 

> Also plz suggest on how to add charts if sevices run on different containers on the same server.I have already installed netdata container on it.

What services?

**Comment by pkd809** [comment]
On updating netdata through   bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates   
The version on netdata GUI  is 16.1.0 while on the host i.e netdata -V it shows 16.1.1.
Initially when i installed netdata  and tried to edit stream.conf it said .stream.conf.sw alreasy exists,which I had overwritten.
Now it neither updates the netdata even after uninstallation nor streams properly to master.Gives graphs at uneven time intervals.

Please resolve!!!!!

> Np 
> 
> > It streams well for other servers but it is problematic on this one. Its an ubuntu 16.04 Xenial server.
> 
> What is your problem? Elaborate what is "problematic"?
> 
> > Also plz suggest on how to add charts if sevices run on different containers on the same server.I have already installed netdata container on it.
> 
> What services?
Services such as Nginx,php-fpm, MariaDB(Mysql),Redis,failtoban etc.

Real problem being netdata update and streaming.
Due to overwriting the pre existent file that somehow matched with stream.conf now is creating the problem. Is there any way to debug the same or trace the error and hence rectify the same.

**Comment by ilyam8** [comment]
> Services such as Nginx,php-fpm, MariaDB(Mysql),Redis,failtoban etc.

It is possible to monitor Nginx,php-fpm, MariaDB(Mysql) and Redis remotely. 

See [nginx.conf](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/nginx/nginx.conf) for example

https://github.com/netdata/netdata/blob/b8836f0b632250551e84a5ac6e96f9537678846c/collectors/python.d.plugin/nginx/nginx.conf#L96-L106

As you can see there can be any number of jobs. You only need `url` to nginx server `stub_status`. So if netdata container is able to communicate with other container via network it wont be hard to monitor services you mentioned.

`fail2ban` module reads log files. I think it is possible to since you can mount same location as volume to many docker containers.

**Comment by ilyam8** [comment]
> Real problem being netdata update and streaming.
> Due to overwriting the pre existent file

I stil dont get what is the problem with streaming.

In the first post i see

> Gives graphs at uneven time intervals.

And now

>  overwriting the pre existent file that somehow matched with stream.conf

**Comment by pkd809** [comment]
> > Real problem being netdata update and streaming.
> > Due to overwriting the pre existent file
> 
> I stil dont get what is the problem with streaming.
> 
> In the first post i see
> 
> > Gives graphs at uneven time intervals.
> 
> And now
> 
> > overwriting the pre existent file that somehow matched with stream.conf


STREAM [receive from [139.59.11.202]:52426]: API key 'a9f2bc0b-114f-46c6-a784-7cfa71484033' is not allowed. Forbidding access. (errno 11, Resource temporarily unavailable)
on running -
tail -f /var/log/netdata/*.log

Hence unable to stream to other netdata.Plz suggest some solutions.

**Comment by pkd809** [comment]
> > > Real problem being netdata update and streaming.
> > > Due to overwriting the pre existent file
> > 
> > 
> > I stil dont get what is the problem with streaming.
> > In the first post i see
> > > Gives graphs at uneven time intervals.
> > 
> > 
> > And now
> > > overwriting the pre existent file that somehow matched with stream.conf
> 
> STREAM [receive from [139.59.11.202]:52426]: API key 'a9f2bc0b-114f-46c6-a784-7cfa71484033' is not allowed. Forbidding access. (errno 11, Resource temporarily unavailable)
> on running -
> tail -f /var/log/netdata/*.log
> 
> Hence unable to stream to other netdata.Plz suggest some solutions.

Hi ilyam.........................plz suggest some solution to this issues.
netdata  version is   v1.16.1-11-g66d6498

**Comment by ilyam8** [comment]
As you see the error is 

> API key 'a9f2bc0b-114f-46c6-a784-7cfa71484033' is not allowed. Forbidding access

Check `API KEY` section in master/slave configuration

There a lot of info about it in [stream.conf](https://github.com/netdata/netdata/blob/master/streaming/stream.conf)

**Comment by pkd809** [comment]
> As you see the error is
> 
> > API key 'a9f2bc0b-114f-46c6-a784-7cfa71484033' is not allowed. Forbidding access
> 
> Check `API KEY` section in master/slave configuration
> 
> There a lot of info about it in [stream.conf](https://github.com/netdata/netdata/blob/master/streaming/stream.conf)

Hi ilyam plz tell the command to set an alarm I want to edit the thresholds CRITICAL and WARNING.

I  am trying 
vi /etc/netdata/orig/health.d/diskd.conf 

It mentions the templates.Have exited the same and restarted netdata but there is no change yet on the netdata dashboard as i see the respective alarm.

**Comment by pkd809** [comment]
> vi /etc/netdata/orig/health.d/diskd.conf

vi /etc/netdata/orig/health.d/disks.conf

**Comment by cakrit** [comment]
1. Don't edit the stock config files directly. You will lose your changes when you update netdata. Read https://docs.netdata.cloud/docs/configuration-guide/#persist-my-configuration on how to make changes that will be persisted across updates.

2. https://docs.netdata.cloud/health/ has all the info on how to customize the alarms.

**Comment by pkd809** [comment]
> 1. Don't edit the stock config files directly. You will lose your changes when you update netdata. Read https://docs.netdata.cloud/docs/configuration-guide/#persist-my-configuration on how to make changes that will be persisted across updates.
> 2. https://docs.netdata.cloud/health/ has all the info on how to customize the alarms.

Hi Cakrit..
Actually i found a direct command to customize the alarms,it consisted of edit-config.
Please if you can suggest some direct one line command to do the same.I am actually not able to customize the alarms through above method,netdata documetation being little complex.

**Comment by pkd809** [comment]
I had lost the command somewhere i did,t save it nor can find the same in history.

**Comment by pkd809** [comment]
Done.
The comand asked above is....
Modify alarms and notifications
Add a new alarm
/etc/netdata/edit-config health.d/disks.conf

**Comment by pkd809** [comment]
> Done.
> The comand asked above is....
> Modify alarms and notifications
> Add a new alarm
> /etc/netdata/edit-config health.d/disks.conf

got it.

**Comment by pkd809** [comment]
2019-08-13 09:40:04: python.d DEBUG: phpfpm[localipv4] : urllib3 version: 1.21.1
2019-08-13 09:40:04: python.d DEBUG: phpfpm[localipv4] : Url: http://127.0.0.1/status?full&json. Http response status code: 502
2019-08-13 09:40:04: python.d ERROR: phpfpm[localipv4] : _get_data() returned no data or type is not <dict>
2019-08-13 09:40:04: python.d INFO: plugin[checker] : phpfpm[localipv4] : check failed, skipping the job
2019-08-13 09:40:04: python.d INFO: plugin[checker] : phpfpm : all jobs failed, skipping module
2019-08-13 09:40:04: python.d INFO: plugin[checker] : terminating...
2019-08-13 09:40:04: python.d INFO: plugin[main] : stopping checker process
2019-08-13 09:40:04: python.d INFO: plugin[main] : no modules to run
DISABLE
 
php-fpm chart not getting added and shows the above error.

**Comment by ilyam8** [comment]
>  Url: http://127.0.0.1/status?full&json. Http response status code: 502

As you see module received [502](https://www.lifewire.com/502-bad-gateway-error-explained-2622939) error.

Check your web server logs.

**Comment by pkd809** [comment]
> > Url: http://127.0.0.1/status?full&json. Http response status code: 502
> 
> As you see module received [502](https://www.lifewire.com/502-bad-gateway-error-explained-2622939) error.
> 
> Check your web server logs. Try to load the url in your browser (dont forget to change ip address).

Thanks a lot ilyam.Got it.Added the chart successfully.
It was a different port defined on www.conf  and i was using a different one on nginx for php-fpm.

2019-08-13 06:45:29: python.d INFO: plugin[main] : using python v2
2019-08-13 06:45:29: python.d INFO: plugin[main] : starting setup
2019-08-13 06:45:29: python.d INFO: plugin[main] : checking for config in ['/opt/netdata/etc/netdata', '/opt/netdata/usr/lib/netdata/conf.d']
2019-08-13 06:45:29: python.d INFO: plugin[main] : config found, loading config '/opt/netdata/usr/lib/netdata/conf.d/python.d.conf'
2019-08-13 06:45:29: python.d INFO: plugin[main] : config successfully loaded
2019-08-13 06:45:29: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
2019-08-13 06:45:29: python.d INFO: plugin[checker] : starting...
2019-08-13 06:45:29: python.d INFO: plugin[checker] : mysql : checking
2019-08-13 06:45:29: python.d INFO: plugin[checker] : mysql : source successfully loaded
2019-08-13 06:45:29: python.d INFO: plugin[checker] : mysql : found config file '/opt/netdata/usr/lib/netdata/conf.d/python.d/mysql.conf'
2019-08-13 06:45:29: python.d INFO: plugin[checker] : mysql : created 28 job(s) from the config
2019-08-13 06:45:29: python.d ERROR: mysql[mycnf1] : MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2019-08-13 06:45:29: python.d INFO: plugin[checker] : mysql[mycnf1] : check failed, skipping the job
2019-08-13 06:45:29: python.d ERROR: mysql[mycnf2] : MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2019-08-13 06:45:29: python.d INFO: plugin[checker] : mysql[mycnf2] : check failed, skipping the job
2019-08-13 06:45:29: python.d ERROR: mysql[debiancnf] : MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin
2019-08-13 06:45:29: python.d INFO: plugin[checker] : mysql[debiancnf] : check failed, skipping the job


On some other server mysql chart is not getting added giving the error mentioned upwards.Plz suggest coz its successflly added on other servers with same configurations. 

Thanks in advance.

**Comment by pkd809** [comment]
> MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin

It didn't as for any such mysqldb or pythonmysqldb on other servers.

**Comment by ilyam8** [comment]
By default all python modules are enabled. You can change the behaviour in the [`python.d.conf`](https://github.com/netdata/netdata/blob/dc38b1d15df2d07f65c0f3c8f8f944fbcc89a574/collectors/python.d.plugin/python.d.conf#L13-L17)

**Comment by pkd809** [comment]
> By default all python modules are enabled. You can change the behaviour in the [`python.d.conf`](https://github.com/netdata/netdata/blob/dc38b1d15df2d07f65c0f3c8f8f944fbcc89a574/collectors/python.d.plugin/python.d.conf#L13-L17).

should i un-comment it an enable it for mysql?????

**Comment by ilyam8** [comment]
It seems i misunderstood you. If you want to get mysql collector working readme is a good place to start

https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mysql#mysql

See `Requirements`.

That is why you have in logs

> MySQLdb or PyMySQL module is needed to use mysql.chart.py plugin

**Comment by pkd809** [comment]
> > By default all python modules are enabled. You can change the behaviour in the [`python.d.conf`](https://github.com/netdata/netdata/blob/dc38b1d15df2d07f65c0f3c8f8f944fbcc89a574/collectors/python.d.plugin/python.d.conf#L13-L17).
> 
> should i un-comment it and enable it for mysql?????
> Done but didn't get the chart..

**Comment by pkd809** [comment]
Hi,
There seem to be too many files inside /var/cache/netdata .
If i have to limit netdata cache formed due to map mode of operation, which file shall I edit?????

**Comment by mfundul** [comment]
You cannot reduce the number of files in `/var/cache/netdata` with `memory mode = map`. You might want to consider deleting your database and start using `memory mode = dbengine` to reduce the number of files and to gain other [advantages](https://docs.netdata.cloud/database/engine/).
