### ISSUE TITLE
netdata failed to install due to judy failure

### ISSUE THREAD

**Issue by arielman** [netdata/netdata#6620]
Hi
When trying to install netdata rpm on our server, it asks for Judy, and when we're trying to install this package, 
[root@XXXXX ~]# rpm -ivh /tmp/netdata-1.16.0-1.el7.x86_64.rpm
error: Failed dependencies:
        Judy is needed by netdata-1.16.0-1.el7.x86_64
        freeipmi is needed by netdata-1.16.0-1.el7.x86_64
        libJudy.so.1()(64bit) is needed by netdata-1.16.0-1.el7.x86_64
        libipmimonitoring.so.6()(64bit) is needed by netdata-1.16.0-1.el7.x86_64
        liblz4.so.1()(64bit) is needed by netdata-1.16.0-1.el7.x86_64
        libuv >= 1 is needed by netdata-1.16.0-1.el7.x86_64
        libuv.so.1()(64bit) is needed by netdata-1.16.0-1.el7.x86_64
        lz4 is needed by netdata-1.16.0-1.el7.x86_64 

based on the guideline (https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually), the command for redhat is:
yum install autoconf automake curl gcc git libmnl-devel libuuid-devel openssl-devel libuv-devel lz4-devel Judy-devel make nc pkgconfig python zlib-devel

However, Judy is not a Redhat package (its a 3rd party), so it cannot be installed by YUM. It has to be downloaded/installed in a similar way to netdata. I couldn't find installable or link to download Judy.

**Comment by mfundul** [comment]
In the guideline, in the [prepare](https://docs.netdata.cloud/packaging/installer/#prepare-your-system) section it is stated that you need EPEL and OKay repositories. The OKay repository is specifically needed for libuv version 1.

**Comment by paulkatsoulakis** [comment]
Hello @arielman, our RPM handles all dependencies required to be pulled for the service to run.
As @mfundul mentioned, you need to add the EPEL repository by doing `yum install -y epel-release` and in some versions you may also need the OKay repository.

Specifically we mention:
```
Please note that for RHEL/CentOS you need EPEL. In addition, RHEL/CentOS version 6 also need OKay for package libuv version 1.
```

Please try this and let us know if it works.
I will be closing the issue but please do re-open if the above instructions did not help you solve the problem.

Once again, thanks for reaching out and apologies for not being zero effort for you.
Our documentation is a constant work in progress and we invest on it, exactly to avoid such situations. Your feedback will help us refine it better.

**Comment by arielman** [comment]
I confirm it worked. TNX!

**Comment by namlegief** [comment]
Hi , have the same issue with docker 
netdata # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.1
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
Please advise.

**Comment by OdysLam** [comment]
Hey @namlegief,

We are so sorry that you are encountering this issue. We have switched our support process to our forums at https://community.netdata.cloud/c/support/agent-support/14 for the Netdata Agent. Please do sign up and create a new topic. It is very important to state if you used our own image for the docker container or another image, in which case the dockerfile will help us enormously. 

Best,
Odysseas
