### ISSUE TITLE
Netdata on VMs sent to customers

### ISSUE THREAD

**Issue by D4V3M0NK** [netdata/netdata#6622]
##### Question summary
Use of netdata on ephemeral images

##### OS / Environment
Ubuntu 16.x, 18.x / RHEL 7.x

I am supplying a VM to my customers and once on premise and their networking is all set up, I remote in and deploy my software on that VM.  At the moment I'm using netdata to monitor these systems by configuring my server as a master, and then setting up the on premise VM as a master (so the customer can view) but also as a slave to my master server (forgive me, I'm new to netdata and not sure of the correct terminology - basically both my customers and I need to see what's going on - if they miss something, I will follow up with them).

At the moment I'm installing netdata when the on-premise VM is networked etc, but I wonder if I can speed this up by installing netdata on the image I make available to all my customers, thereby negating having to install whilst on site.  From what I can see, all I'd need to do when the VM is up and running when on premise, is to configure the unique identifer (which I get from my master anyway) and configure the upstream server.

Is this the best way of doing this?

**Comment by Ferroin** [comment]
Unless things have changed since I last checked, Netdata will automatically generate a unique ID when it starts up if it doesn't find one already saved where it expects it to be.  So you should be able to install Netdata normally and remove the unique ID file (which I unfortunately don't remember the name of) and the resultant system should 'just work'.

**Comment by cakrit** [comment]
@Ferroin is correct, the file he mentioned is `/var/lib/netdata/registry/netdata.public.unique.id`. So this file should not be on your image. For security reasons, also remove the auto-generated file `/var/lib/netdata/netdata.api.key`, which holds an auth key that can be used to issue Health API management commands.

**Comment by cakrit** [comment]
Oh, and of course our installer has the `--dont-start-it` flag, which would prevent the files from getting generated at all, since netdata would not start after the installation.

**Comment by D4V3M0NK** [comment]
Thank you both for your comments. @cakrit you mention the `--dont-start-it flag`: at the moment I'm using the kickstart script to install NetData, but I see that there's Linux static builds that I could also use. However, I'm guessing that in order to use that flag, I'd have to compile manually? 

Alternatively, of course, I just remove those two files after kickstart? It appears that that kickstart file also gets the latest version etc etc so is _probably_ the safest and easiest route to take?

**Comment by cakrit** [comment]
You can use kickstart just fine. Check under https://docs.netdata.cloud/packaging/installer/#one-line-installation, there's a section you can expand 'Click here for more information and advanced use of the one-line installation script.' 
The option is mentioned there and an example is provided with many options.
