### ISSUE TITLE
MacOS + netdata, Is it possible to Configure Netdata to monitor performance stats per application ?

### ISSUE THREAD

**Issue by aSk134** [netdata/netdata#6625]
Hello folks, 
I Cannot figure out how to monitor performance Stats (atleast CPU usage) per an application on Mac OS with netdata,  What am I doing wrong? 
Any help/ advice is much appreciated.

##### OS / Environment  
Mac OS Catalina

##### Component Name 
Netdata + macOS (plus any application)

##### Expected results 
Collect CPU usage per an application with netdata.

Thank you in advance.

P.S. If something is unclear i will be happy to elaborate.

**Comment by ilyam8** [comment]
i think you need [apps plugin](https://docs.netdata.cloud/collectors/apps.plugin/), but it doesnt work in Mac OS
https://github.com/netdata/netdata/issues/1892

**Comment by aSk134** [comment]
ahhhh, man, that really sucks; I really like this tool i just need it to work on mac. 
Can anyone suggest a similar tool that can do everything netdata does but can also monitor performance per application?
Thank you in advance.

**Comment by ilyam8** [comment]
I guess you need free solution, i am not aware if there is any, i bet no :smile: 	

Non free:
 - [monity](https://apps.apple.com/us/app/monity/id915542151?mt=12)
 - [istat menus](https://bjango.com/mac/istatmenus/)

Both do application monitoring.

**Comment by aSk134** [comment]
@ilyam8, thank you for the suggestion. I have used istatMenus, they have a free trial period but this app is not free. I have not used monity but it looks like this app is not free. 
I am looking at similar apps to netdata:
Grafana
Monit
Nagios.

Has anyone had experience with these?
Alos, curios to see if support for apps.plugin might be available on macOS in the future?

**Comment by ilyam8** [comment]
> Alos, curios to see if support for apps.plugin might be available on macOS in the future?

Ofc! ~It will cost only 4.99$, pre-order is only 2.99$~

**Comment by paulkatsoulakis** [comment]
I will be resolving this issue for now and we can catch up any further comments or concerns through #1892 

Thank you for reaching out @aSk134 and we 'll be here if there is anything else we can do to help you with maximising netdatas capabilities for you.

From our side we will try to see if we can progress with #1892 or at least provide some alternative solution to this. Thanks again!

**Comment by aSk134** [comment]
@paulkatsoulakis, great to hear that, im really looking forward to this feature on MacOS, if there is any help needed testing this feature I would gladly volunteer to be an early adopter of the new build/release. 
Everyone (@ilyam8, @paulkatsoulakis ) thank you for your help and responsiveness. 

P.S. please keep me posted on any new updates.
