### ISSUE TITLE
Valgrind warnings in nightly

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6628]
I get tons of Valgrind warnings from the latest build, more than ever before:

![Screenshot from 2019-08-09 11-38-03](https://user-images.githubusercontent.com/43294513/62770117-a192e780-ba9a-11e9-8ae7-a3b26d68b7a1.png)

[valgrind.xml.txt](https://github.com/netdata/netdata/files/3485717/valgrind.xml.txt)

@Volkodavchik had looked into the `UninitCondition` for `security.c` a bit and had sent what you'll see below. Not sure how much they help, but putting them here so you can comment. Note that @thiagoftsm had said about this particular issue that `it is a false positive, case you use an "alt+f7" inside clion, you will see that the function security_start_ssl is always called with a valid value.`

I still don't want these, valgrind should be clean, plus we get a lot more now. 

What follows is from @Volkodavchik : 

Valgrind and false-positives
- To be sure, it is not a false-positive but a true issue - it should be reproduced.
To maximize the probability of issue reproduction it is necessary to have the same conditions/env for the tests done, etc.:
- Being Valgrind and other test round checks a part of release procedure (automated via Jenkins or any other tool)
- Execute all tests on some "sandbox" environment (Virtual Machine, Docker one or similar)
- Be able to clone the test environment to repeat the test and see what is going on (snapshots or pre-setup images)
- Have a full/major list of supported platforms and "sandboxes" for them. Like (Ubuntu 16.06 LTS vxxxyyy, Fedora 22 vxxxyyy, etc)

- Regarding this Valgrind issue - now we only guess that it is a false positive because it was not reproduced.
 That might be possible due to a way how memory allocated/released by library functions and OS itself.
 E.g. using memory pool, which is not freed immediately by OS (https://www.linuxquestions.org/questions/programming-9/valgrind-reports-memory-leak-at-opendir-495092/), and therefore Valgrind reports memleak. Or "race condition", when garbage collector started memcleanup, but Valgrind checked pointer to memory first and reported it.
To minimize such things it is worth to have a set of sandboxes for basic tests (see above).
User "thiagoftsm" patch https://github.com/netdata/netdata/pull/6468/files#r305014121
 While personally I am not an expert on SSL and therefore changes from functional perspective might be hard to
analyze, I see some things which I think should be avoided on "production":
1. collectors/plugins.d/plugins_d.c
 - No checks of given pointers to the function as input arguments, like * output, *ssl, etc. Any or all of them might be NULL - result in segfault
 - No preset of initial values for local variables (like *endbuffer, length, etc) - might lead to incorrect results.
 - All library functions might end up unsuccessfully, no checks are present to memcpy,memset and other library functions.
 - "magic" numbers, like 256 are not good in production code - should be created a const or enum with proper expl.
2. libnetdata/socket/security.c
- Comments like "@return it returns 0 case it performs the handshake, 8 case it is a clean connection
and another integer power of 2 otherwise." might be updated if all values returned as named variables to @NETDATA_SSL_HANDSHAKE_COMPLETE and link to this variable
More or less the same issues are present in all files of the patch. While they are not critical at first glance, it is always good to have a clear production code.

**Comment by cakrit** [comment]
Screenshots from CLion, since the XML is hard to read...

[Screenshot from 2019-08-09 1.zip](https://github.com/netdata/netdata/files/3485810/Screenshot.from.2019-08-09.1.zip)

**Comment by mfundul** [comment]
I scanned the whole xml file, the dbengine warnings have been there since v.1.15 and we have considered them to be false positive. However, I should take a second look at them.

**Comment by mfundul** [comment]
I've run valgrind in Ubuntu 18.04 and I cannot get those errors. I ran both the native valgrind version 3.13 and the up-to-date version 3.15 via snap. I used the same arguments as the attached xml file in the issue.

**Comment by cakrit** [comment]
```
christopher@chris-msi netdata]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 9.1.0 (GCC) 
```

**Comment by mfundul** [comment]
@cakrit what version of manjaro are you running?

**Comment by cakrit** [comment]
```
NETDATA_SYSTEM_OS_NAME="Manjaro Linux"
NETDATA_SYSTEM_OS_ID=manjaro
NETDATA_SYSTEM_OS_ID_LIKE=arch
NETDATA_SYSTEM_OS_VERSION=18.0.4
NETDATA_SYSTEM_OS_VERSION_ID=unknown
NETDATA_SYSTEM_OS_DETECTION=Mixed
NETDATA_SYSTEM_KERNEL_NAME=Linux
NETDATA_SYSTEM_KERNEL_VERSION=4.19.59-1-MANJARO
NETDATA_SYSTEM_ARCHITECTURE=x86_64
```

**Comment by mfundul** [comment]
I tested the exact same OS, gcc and valgrind versions, ran valgrind with the same arguments and cannot get any of the `dbengine` warning in the original post's XML file other than the very few known false positives.

**Comment by cakrit** [comment]
I no longer get the warnings in CLion. I have no idea how the issue went away, but closing.
