### ISSUE TITLE
Sign in issue

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6629]
Adding below a bug report from a user:

---------- Forwarded message ---------
Date: Fri, Aug 9, 2019 at 12:07 PM
Subject: Sign In Issues
To: <support@netdata.cloud>

Hi,

I've tried to sign into multiple installs (noc@world-text.com) and this worked to start with, but now I can't seem to sign into any of them?

Kind regards,

NV

**Comment by neilvince** [comment]
Netdata Version: v1.16.1-10-nightly
Browser info: Safari Version 12.1.2 (14607.3.9)
OS info: macOS 10.14.6 (18G87)
When did you first notice the issue? Fri 9 Aug 10:00:00 UTC 2019

**Comment by nicolasparada** [comment]
Hi @neilvince, thanks for the report.
Could you tell us what is happening here?
You click sign-in and you are redirected to Netdata Cloud, then which auth method do you use?
Are you caught in a loop after that? The window closes itself without logging you in? You are just redirected to Cloud homepage?
Do you see any errors logged in the agent devtools?

A more detailed explanation would be very helpful. Thanks.

**Comment by neilvince** [comment]
Hi,

I was trying to log in (and had done so before) with the email address, but iafter clicking the email sent to us (Sign-In to Netdata Cloud) it would load up the dashboard and still not be signed in.   This was the same when authenticating via Google, but in this case the you get stuck in an endless loop asking you to sign in with Google.   I cannot unfortunately give any debug info now as it has started to work again (sign in with Google).

Kind regards,

Neil

**Comment by nicolasparada** [comment]
Sorry about that. At least you were able to sign-in using Google.

So, the issue with the email auth persists, right?
Maybe you can help us, here is what I need you to do. Sign-in with your email, and once redirected back to the dashboard if you don't see yourself logged-in, open the devtools and check if there is any errors there.

Thanks you.

**Comment by neilvince** [comment]
The email route is still failing and as requested:

`[Error] Failed to load resource: the server responded with a status of 401 () (sso-agent, line 0) https://netdata.cloud/account/sso-agent?id=de1e0126-ba8b-11e9-b356-0672035d4bf8`

**Comment by nicolasparada** [comment]
OK, I see. That's helpful. Thank you.

**Comment by cakrit** [comment]
```
Date: Tue, Aug 13, 2019 at 5:49 PM
Subject: Unable to login
To: support@netdata.cloud <support@netdata.cloud>

Hi,

I am unable to login to the cloud. I am using Chrome 75 and whenever I go to http://XX.XX.XX.XX:19999/console.html#/, it sends me to login to the Netdata cloud. When I use GitHub, it redirects and then closes the tab. With email, I open the link but it gets stuck at pages like https://netdata.cloud/account/sign-in-agent?id=6672ade8-1509-11e9-9720-44ed57001cf4&origin=&redirected=true
```

**Comment by cakrit** [comment]
```
Date: Aug 01 11:32AM +0200

I get the verification-mail, then i click on the "sign in" button in the 
mail. In my browser i get redirected to the frontpage. I also tried to 
copy the link and open it in a private browser, so no extension should 
braek somtething.
```

**Comment by cakrit** [comment]
We have since fixed issues with Sign-In that we had, due to duplicate emails. @neilvince can you please verify that your issue is fixed?

**Comment by cakrit** [comment]
Actually, this another Safari issue. Closing in favor of #6500
