### ISSUE TITLE
Prometheus documentation version update

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6630]
##### Feature idea summary
Our documentation now is saying for we do download of the Prometheus 2.3.2, but today when I got the Prometheus to test, I verified that the current release is 2.11.1, so instead to do download of a specific version, I think it would be better to download of the stable version.

The link identified with problem was https://docs.netdata.cloud/backends/prometheus/ , this is not the unique link talking about Prometheus, we also have https://docs.netdata.cloud/backends/walkthrough/#prometheus talking about,  in this last we do download of 1.7.1, but we have a better text that does not allow miss understanding "Prometheus provides a tarball of their latest stable versions here: https://prometheus.io/download/. "

##### Expected behavior
Do not create a wrong vision for users that Netdata works with a specific version of Prometheus.

**Comment by prhomhyse** [comment]
A solution was a way to download and use the latest version of Prometheus. 
The current one is v 2.11.1.
@joelhans suggested a one-liner method and it works pretty well.

With this PR #6652 
The documentation does not depend on a particular version now.

**Comment by thiagoftsm** [comment]
Hi @prhomhyse ,

Thank you very much by the update, I saw the changes in the PR and I liked the result.
