### ISSUE TITLE
noob question about netdata under a vpn and nginx

### ISSUE THREAD

**Issue by cocodrino** [netdata/netdata#6636]
Hi guys, I'm a bit newbie with netdata and I've a small problem, right now I set nginx for my master node, so I can access to my dashboard under the port 8888 with http authentication, this works great, now, my amazon instances are under a vpn, the SG indicates that they can access to any port under this vpn and the port 8888 is accesible to any ip (so I can access to my dashboard without enter in the vpn)...

I'm a bit lost here (I don't have so much experience with vpn's) amazon provides me a private ip which I can use for my instances communication, I set that ip in my slave instance, but seems that I can't connect, the logs show some problems, my config is this

``` /etc/netdata/stream.conf
[stream]
  enabled = yes
  destination = <Amazon Private IP>
  api key = 11ab48e7-2e8b-43ff-8fd7-2cb1cxxxx
```

logs 
```
2019-08-11 01:35:38: netdata ERROR : STREAM_SENDER[ip-17x-31-27-xx] : STREAM ip-17x-31-27-xx [send to 17x.31.27.xx]: failed to connect

```

is there any general configuration where just set my private ip all nodes inside my vpn can communicate to my master instance?...thank you so much guys

**Comment by vlvkobal** [comment]
How did you configure your master? Do you have any streaming errors on the master?

**Comment by cakrit** [comment]
Let's cover the simplest possible issue first. In your slave configuration I don't see port 8888 (destination is just an IP). Did you modify `default port` further down the config from 19999 to 8888?

After ensuring you've done that and assuming you still have issues, try the connectivity from the slave to the master yourself. e.g. see https://www.tecmint.com/check-remote-port-in-linux/

**Comment by cocodrino** [comment]
thank you so much @cakrit , after check using the command nc I'll able to notice that ufw was blocking some required ports, I turn off these rules and everything works as expected, thank you...
