### ISSUE TITLE
Update and replication issues

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6641]
On updating netdata through bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates
The version on netdata GUI is 16.1.0 while on the host i.e netdata -V it shows 16.1.1.
Initially when i installed netdata and tried to edit stream.conf it said .stream.conf.sw alreasy exists,which I had overwritten.
Now it neither updates the netdata even after uninstallation nor streams properly to master.Gives graphs at uneven time intervals.

Please resolve!!!!!

_Originally posted by @pkd809 in https://github.com/netdata/netdata/issues/4659#issuecomment-518982888_

**Comment by cakrit** [comment]
You are reporting multiple different issues here. 
### Netdata does not update
Since you ran kickstart.sh with the flag to not update, you will need to run it again to get a newer version. You can check `/etc/netdata/.environment` after your run kickstart.sh again, to ensure you see something like the following:
```
PATH="[your path here]"
CFLAGS="-O2"
NETDATA_PREFIX=""
NETDATA_CONFIGURE_OPTIONS=""
NETDATA_ADDED_TO_GROUPS=" docker haproxy adm ceph nobody"
INSTALL_UID="0"
NETDATA_GROUP="netdata"
REINSTALL_COMMAND="./netdata-installer.sh "
RELEASE_CHANNEL="nightly"
IS_NETDATA_STATIC_BINARY="no"
NETDATA_LIB_DIR="/var/lib/netdata"
```
### Different version in GUI vs netdata -V
To my knowledge, the only way this can happen is if you're looking at a different netdata's UI than the `netdata` binary you executed with the `-V` option. What you see on the GUI IS what `netdata -V` shows. 
Ensure you're looking at the UI of the host you ran the command on. If you select a slave node and see its charts, then you will see its netdata version as well. That version could be different that the version on the master.
If that's not the case, check the `netdata` path to ensure that you don't have a second netdata binary.

### .stream.conf.sw 
Just find that file and remove it. Use `edit-config` again and it will store the configuration in the proper place.You can double-check by looking at the contents of `/etc/netdata/stream.conf`.
I haven't seen that error myself, but it's not related to the other issues.

### Graphs at uneven time intervals
We need to see that. Can you provide a screenshot? There are many things that could go wrong with streaming. We'll need to see `error.log` from the master and the slave as well.

**Comment by scream314** [comment]
That sounds similar to what I had once: I installed 2 Netdatas by mistake, the "normal" and the "static binary" one. I was tweaking one's config, but the other was running.
You can find out if that is the case by checking the contents of `/etc/netdata` and `/opt/netdata/etc/netdata/`. AFAIK the first should exist if the normal one is installed, the second if you have the static binary, both if both.
Maybe that could explain why you are seeing 2 different version numbers.
