### ISSUE TITLE
Using REST API

### ISSUE THREAD

**Issue by rodrigovaras** [netdata/netdata#6647]
I'm new to the ndata project but so far it looks very promising.
Here in MSFT we are considering to use it check the health of a linux VM being allocated in Azure to be used by developers to host their projects.
Since the VM will not have any public API and also we did not want to open the ndata port anyway, we were looking on having a worker agent to use the REST API into the local port using http and then upload the result data into a dedicated service that would broadcast the alarms and the health status to other consumers. 
I check the REST API and thinking on using the '/allmetrics' path but when looking into the results it looks overwhelming data hard to aggregate. For example checking the CPU section it looks that it report the percent for every process. We would love something more simple like an API that report the total percent CPU (like the one in the first part of the dashboard).
Is this expected that when using the REST API the summarized data has to be manually calculated?
I also check the '/charts' but still getting some difficulty in extracting the summarized data.

Any other suggestion on what we want to achieve?

**Comment by ilyam8** [comment]
> is this expected that when using the REST API the summarized data has to be manually calculated?

Yes

> looks overwhelming data hard to aggregate

Actully it is not that hard. Netdata is able to export data in prometheus format (`/api/v1/allmetrics?format=prometheus`). I think you can find prometheus metrics parser written in any language ([python parser](https://github.com/prometheus/client_python#parser) for example). Since it is easy to parse it is easy to make any calculation you need.

**Comment by ilyam8** [comment]
> For example checking the CPU section it looks that it report the percent for every process.

per core

```
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="guest_nice"} 0.0000000 1565641364000
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="guest"} 0.0000000 1565641364000
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="steal"} 0.0000000 1565641364000
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="softirq"} 0.0840854 1565641364000
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="irq"} 0.1977992 1565641364000
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="user"} 6.0022194 1565641364000
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="system"} 1.5112027 1565641364000
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="nice"} 0.0000000 1565641364000
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="iowait"} 0.0472707 1565641364000
netdata_cpu_cpu_percentage_average{chart="cpu.cpu5",family="utilization",dimension="idle"} 92.1574224 1565641364000
```

**Comment by cakrit** [comment]
Hi @rodrigovaras, we'd very much like to help in any way we can and would be very interested in a public announcement, after we get this up and running. 

Let's start with the statement below:

> Since the VM will not have any public API and also we did not want to open the ndata port anyway, we were looking on having a worker agent to use the REST API into the local port using http and then upload the result data into a dedicated service that would broadcast the alarms and the health status to other consumers.

@ilyam8 already mentioned the Prometheus exporter, but that's not the only thing netdata can do. If you look at https://docs.netdata.cloud/backends/, you'll realize that there's no need for you write a worker agent. Just select your aggregator of choice and we can build a backend for that. Alarm notifications are different and actually much simpler. You can look at https://docs.netdata.cloud/health/notifications/. 

We could set up a call to discuss your precise use cases and the various options if you like, just contact me at chris@netdata.cloud and we can arrange it.

**Comment by rodrigovaras** [comment]
Thanks very much on the responses, @cakrit i will contact you to see if we can have a chat over the phone and give you more details.
