### ISSUE TITLE
netdata not getting installed :  Public key for libuv-devel-0.10.34-1.el6.x86_64.rpm is not installed

### ISSUE THREAD

**Issue by darshanoag** [netdata/netdata#6649]
I am getting below error when trying to install netdata 

Transaction Summary
=====================================================================================================================================================
Install       9 Package(s)

Total size: 487 k
Installed size: 1.3 M
Is this ok [y/N]: y
Downloading Packages:
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY

Public key for libuv-devel-0.10.34-1.el6.x86_64.rpm is not installed

We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues

OS Version is :  
Linux sjc-asr-197 2.6.32-754.3.5.el6.x86_64 #1 SMP Thu Aug 9 11:56:22 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

Can somebody please help ?

**Comment by paulkatsoulakis** [comment]
Hello @darshanoag, thank you for reaching out to us.

I need two things to help you out:
1) what is the command you used exactly to run the installation of netdata

2) the full output of the command, so that we can get all the details of what our installer did.

In general looks like a repository problem, not really related to netdata.
The above information i am asking will help me get better visibility of what went wrong

Thanks !

**Comment by darshanoag** [comment]
Command used to install: 
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
Below is the complete log: 

[05:20 dhavnoor@sjc-asr-197 dhavnoor] > bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version: 
 --- Downloading script to detect required packages... --- 
[/tmp/netdata-kickstart-Wdb7oI]$ curl -sSL --connect-timeout 10 --retry 3 https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh 
 OK   

 --- Running downloaded script to detect required packages... --- 
[/tmp/netdata-kickstart-Wdb7oI]$ sudo /usr/bin/bash /tmp/netdata-kickstart-Wdb7oI/install-required-packages.sh netdata 
Enter RADIUS password (http://otp for help): 
Cannot find /etc/os-release
Loading /etc/lsb-release ...
Cannot find distribution with /etc/lsb-release
Running command: lsb_release ...

We detected these:
Distribution    : RedHatEnterpriseServer
Version         : 6.10
Codename        : Santiago
Package Manager : install_yum
Packages Tree   : rhel
Detection Method: lsb_release
Default Python v: 2 

WARNING
package autoconf-archive is not available in this system.
You may try to install without it.

WARNING
package autogen is not available in this system.
You may try to install without it.

 > Checking if package 'zlib-devel' is installed...
 > Checking if package 'libuuid-devel' is installed...
 > Checking if package 'libmnl-devel' is installed...
 > Checking if package 'libuv-devel' is installed...
 > Checking if package 'lz4-devel' is installed...
 > Checking if package 'openssl-devel' is installed...
 > Checking if package 'Judy-devel' is installed...

The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   yum update  

yum install Judy-devel libmnl-devel libuuid-devel libuv-devel lz4-devel 


Press ENTER to run it > 
yum install Judy-devel libmnl-devel libuuid-devel libuv-devel lz4-devel 
Loaded plugins: fastestmirror, merge-conf, priorities
Setting up Install Process
Loading mirror speeds from cached hostfile
7388 packages excluded due to repository priority protections
Resolving Dependencies
There are unfinished transactions remaining. You might consider running yum-complete-transaction first to finish them.
--> Running transaction check
---> Package Judy-devel.x86_64 0:1.0.5-1.el6 will be installed
--> Processing Dependency: Judy = 1.0.5-1.el6 for package: Judy-devel-1.0.5-1.el6.x86_64
--> Processing Dependency: libJudy.so.1()(64bit) for package: Judy-devel-1.0.5-1.el6.x86_64
---> Package libmnl-devel.x86_64 0:1.0.2-3.el6 will be installed
--> Processing Dependency: libmnl(x86-64) = 1.0.2-3.el6 for package: libmnl-devel-1.0.2-3.el6.x86_64
--> Processing Dependency: libmnl.so.0()(64bit) for package: libmnl-devel-1.0.2-3.el6.x86_64
---> Package libuuid-devel.x86_64 0:2.17.2-12.28.el6_9.2 will be installed
---> Package libuv-devel.x86_64 1:0.10.34-1.el6 will be installed
--> Processing Dependency: libuv(x86-64) = 1:0.10.34-1.el6 for package: 1:libuv-devel-0.10.34-1.el6.x86_64
--> Processing Dependency: libuv.so.0.10()(64bit) for package: 1:libuv-devel-0.10.34-1.el6.x86_64
---> Package lz4-devel.x86_64 0:r131-1.el6 will be installed
--> Processing Dependency: lz4(x86-64) = r131-1.el6 for package: lz4-devel-r131-1.el6.x86_64
--> Processing Dependency: liblz4.so.1()(64bit) for package: lz4-devel-r131-1.el6.x86_64
--> Running transaction check
---> Package Judy.x86_64 0:1.0.5-1.el6 will be installed
---> Package libmnl.x86_64 0:1.0.2-3.el6 will be installed
---> Package libuv.x86_64 1:0.10.34-1.el6 will be installed
---> Package lz4.x86_64 0:r131-1.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=================================================================================================================================
 Package                   Arch               Version                             Repository                                Size
=================================================================================================================================
Installing:
 Judy-devel                x86_64             1.0.5-1.el6                         Cisco-EPEL-Repo                           69 k
 libmnl-devel              x86_64             1.0.2-3.el6                         PatchBundle-nonreboot-Q3FY16              16 k
 libuuid-devel             x86_64             2.17.2-12.28.el6_9.2                Snapshot-nonreboot-Q1FY19                 88 k
 libuv-devel               x86_64             1:0.10.34-1.el6                     Cisco-EPEL-Repo                           41 k
 lz4-devel                 x86_64             r131-1.el6                          Cisco-EPEL-Repo                           18 k
Installing for dependencies:
 Judy                      x86_64             1.0.5-1.el6                         Cisco-EPEL-Repo                          114 k
 libmnl                    x86_64             1.0.2-3.el6                         PatchBundle-nonreboot-Q3FY16              21 k
 libuv                     x86_64             1:0.10.34-1.el6                     Cisco-EPEL-Repo                           57 k
 lz4                       x86_64             r131-1.el6                          Cisco-EPEL-Repo                           63 k

Transaction Summary
=================================================================================================================================
Install       9 Package(s)

Total download size: 487 k
Installed size: 1.3 M
Is this ok [y/N]: y
Downloading Packages:
(1/9): Judy-1.0.5-1.el6.x86_64.rpm                                                                        | 114 kB     00:00     
(2/9): Judy-devel-1.0.5-1.el6.x86_64.rpm                                                                  |  69 kB     00:00     
(3/9): libmnl-1.0.2-3.el6.x86_64.rpm                                                                      |  21 kB     00:00     
(4/9): libmnl-devel-1.0.2-3.el6.x86_64.rpm                                                                |  16 kB     00:00     
(5/9): libuuid-devel-2.17.2-12.28.el6_9.2.x86_64.rpm                                                      |  88 kB     00:00     
(6/9): libuv-0.10.34-1.el6.x86_64.rpm                                                                     |  57 kB     00:00     
(7/9): libuv-devel-0.10.34-1.el6.x86_64.rpm                                                               |  41 kB     00:00     
(8/9): lz4-r131-1.el6.x86_64.rpm                                                                          |  63 kB     00:00     
(9/9): lz4-devel-r131-1.el6.x86_64.rpm                                                                    |  18 kB     00:00     
---------------------------------------------------------------------------------------------------------------------------------
Total                                                                                            1.5 MB/s | 487 kB     00:00     
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY


Public key for libuv-devel-0.10.34-1.el6.x86_64.rpm is not installed



We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues


 FAILED   

 WARNING  It failed to install all the required packages, but installation might still be possible. 

Press ENTER to attempt netdata installation >

**Comment by darshanoag** [comment]
--- OK, let's give it a try... --- 
[/tmp/netdata-kickstart-Wdb7oI]$ curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/sha256sums.txt 
 OK   

[/tmp/netdata-kickstart-Wdb7oI]$ curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz 
 OK   

[/tmp/netdata-kickstart-Wdb7oI]$ tar -xf netdata-latest.tar.gz 
 OK   

 --- Installing netdata... --- 
[/tmp/netdata-kickstart-Wdb7oI/netdata-v1.16.1-32-g0f2531e0]$ sudo ./netdata-installer.sh --auto-update 

  ^
  |.-.   .-.   .-.   .-.   .  netdata                                        
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


  You are about to build and install netdata to your system.

  It will be installed at these locations:

   - the daemon     at /usr/sbin/netdata
   - config files   in /etc/netdata
   - web files      in /usr/share/netdata
   - plugins        in /usr/libexec/netdata
   - cache files    in /var/cache/netdata
   - db files       in /var/lib/netdata
   - log files      in /var/log/netdata
   - pid file       at /var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata

  This installer allows you to change the installation path.
  Press Control-C and run the same command with --help for help.

Press ENTER to build and install netdata to your system > 

 --- Run autotools to configure the build environment --- 
[/tmp/netdata-kickstart-Wdb7oI/netdata-v1.16.1-32-g0f2531e0]# autoreconf -ivf 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
 OK   

[/tmp/netdata-kickstart-Wdb7oI/netdata-v1.16.1-32-g0f2531e0]# ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/libexec --with-zlib --with-math --with-user=netdata CFLAGS=-O2 
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin//install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a pax tar archive... gnutar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for a BSD-compatible install... /usr/bin//install -c
checking for pkg-config... /usr/bin//pkg-config
checking pkg-config is at least version 0.9.0... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /router/bin/grep
checking for egrep... /router/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for __attribute__((returns_nonnull))... no
checking for __attribute__((malloc))... yes
checking for __attribute__((noreturn))... yes
checking for __attribute__((noinline))... yes
checking for __attribute__((format))... yes
checking for __attribute__((warn_unused_result))... yes
checking for struct timespec... yes
checking for clockid_t... yes
checking for library containing clock_gettime... -lrt
checking for clock_gettime... yes
checking for sched_setscheduler... yes
checking for sched_getscheduler... yes
checking for sched_getparam... yes
checking for sched_get_priority_min... yes
checking for sched_get_priority_max... yes
checking for getpriority... yes
checking for setpriority... yes
checking for nice... yes
checking for recvmmsg... yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for inline... inline
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... yes
checking for _Generic... no
checking for __atomic... no
checking size of void *... 8
checking host system type... (cached) x86_64-unknown-linux-gnu
checking whether sys/types.h defines makedev... yes
checking for sys/types.h... (cached) yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking sys/prctl.h usability... yes
checking sys/prctl.h presence... yes
checking for sys/prctl.h... yes
checking sys/vfs.h usability... yes
checking sys/vfs.h presence... yes
checking for sys/vfs.h... yes
checking sys/statfs.h usability... yes
checking sys/statfs.h presence... yes
checking for sys/statfs.h... yes
checking sys/statvfs.h usability... yes
checking sys/statvfs.h presence... yes
checking for sys/statvfs.h... yes
checking sys/mount.h usability... yes
checking sys/mount.h presence... yes
checking for sys/mount.h... yes
checking for accept4... yes
checking operating system... linux with id 1
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for sin in -lm... yes
checking if libm should be used... yes
checking for uv_fs_scandir_next in -luv... no
checking for LZ4_compress_default in -llz4... no
checking for JudyLIns in -lJudy... no
checking for ZLIB... yes
checking if zlib should be used... yes
checking for UUID... no
configure: error: libuuid required but not found. Try installing 'uuid-dev' or 'libuuid-devel'.
 FAILED   


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues


 FAILED   

 ABORTED  netdata-installer.sh exited with error

**Comment by paulkatsoulakis** [comment]
Thank you @darshanoag, it seems that you have an issue with your repository.
The error 
```Total 1.5 MB/s | 487 kB 00:00
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA256 Signature, key ID 0608b895: NOKEY
Public key for libuv-devel-0.10.34-1.el6.x86_64.rpm is not installed
```

is the one that is breaking the whole yum execution, thus resulting into failing to install the required packages. You need to figure this out with your vendor (Redhat).

From a quick search on the error: `https://access.redhat.com/solutions/31543` you may find other threads also that explain this problem.

I will be closing the issue for now since we are not looking at a Netdata issue, but please do reopen the issue once you fix the yum repository issue and you still facing problems with netdata install.


Thanks again for your report, do not hesitate to reopen and ask for further information here if the above did not cover you. See you!
