### ISSUE TITLE
configure pulls in libs even if functions are disabled

### ISSUE THREAD

**Issue by diizzyy** [netdata/netdata#6656]
The configure script seems to incorrectly add libraries for linking even if functionality is disabled.

Example:
If you pass ```--disable-https --disable-dbengine``` netdata binary will still link OpenSSL if avaible.
Some libraries such as liblz4 and libuv are unconditionally linked when/if found.

OS: 
Alpine Linux 3.10.1 (x86-64) and OpenWrt (master branch)

Tested version:
Netdata v1.16.1 (https://github.com/netdata/netdata/releases/tag/v1.16.1)

**Comment by mfundul** [comment]
Can you test [this](https://github.com/netdata/netdata/pull/6658) Pull Request and see if your problem is fixed?

**Comment by diizzyy** [comment]
Hi,
PR works as intended
Thanks!
