### ISSUE TITLE
installation issue on Fedora 30

### ISSUE THREAD

**Issue by sukhyun** [netdata/netdata#6657]
#### Summary
When double clicking netdata rpm file for installation on Fedora 30 (32bit), the below appears:

![netdata-install](https://user-images.githubusercontent.com/1342465/63001628-f5dd0380-beae-11e9-9a45-c48af657d5ae.png)

**Comment by cakrit** [comment]
This distribution channel isn't supported by this project. Please see https://docs.netdata.cloud/packaging/installer/#binary-packages for the binary packages we distribute.
