### ISSUE TITLE
ubuntu: make cups package optional

### ISSUE THREAD

**Issue by berendt** [netdata/netdata#6662]
At the moment the Ubuntu netdata package has cups as dependency. Normally cups is not required on server systems. Please mark cups as suggested package.

**Comment by paulkatsoulakis** [comment]
Hi @berendt, thank you for reporting this!
We are actually planning to start separating the various sub-components of netdata that are not really mandatory for the majority of our users.  Things like CUPS, FREEIPMI or PERF is some of the plugins to be separated to different sub-packages.

**Comment by berendt** [comment]
Sub packages definitely make sense.

Avahi Daemon was also installed. Think this came as a dependency on Cups.
