### ISSUE TITLE
qemu: wrong mapping of network interfaces

### ISSUE THREAD

**Issue by berendt** [netdata/netdata#6665]
##### Bug report summary

There are 5 QEMU instances running on one system (started by OpenStack). The network interfaces are all assigned to the last instance.

<img width="173" alt="Screenshot 2019-08-15 at 12 10 21" src="https://user-images.githubusercontent.com/419091/63088660-dea52100-bf55-11e9-95f1-28b6ef760c70.png">

##### OS / Environment

Ubuntu 18.04

##### Netdata version (ouput of `netdata -V`)

v1.16.0-70-nightly

##### Component Name

qemu

##### Steps To Reproduce

Start more than 2 QEMU instances with OpenStack.

##### Expected behavior

Each QEMU instance should have 2 network interfaces.

**Comment by stelfrag** [comment]
hi @berendt 

Apologies for the delay on following up on this.

If the problem persists, could you provide some information from the logfile?

in particular check for lines that execute 

`cgroup-network-helper.sh --cgroup ....` 

For example you say see something that resembles to the following:

`MAIN : running: exec /usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/sys/fs/cgroup/cpu,cpuacct/machine/qemu-13-debian10.libvirt-qemu'`

Then we would also like you to provide the output of that command 
(run it on the command line with sudo) 
example:

`sudo /usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/sys/fs/cgroup/cpu,cpuacct/machine/qemu-13-debian10.libvirt-qemu'`

thank you!!

**Comment by stelfrag** [comment]
Please reopen with log information if this is still a problem.
