### ISSUE TITLE
ubuntu: wrong default paths in /etc/netdata/edit-config

### ISSUE THREAD

**Issue by berendt** [netdata/netdata#6666]
##### Bug report summary

On Ubuntu the /etc/netdata/edit-config script is not usable because of wrong defaults.

```
  Stock config files at: '/usr/local/lib/netdata/conf.d'
  User  config files at: '/usr/local/etc/netdata'
```

Default should be /usr/lib/x86_64-linux-gnu/netdata/conf.d and /etc/netdata.

At the moment it is necessary to set NETDATA_USER_CONFIG_DIR and NETDATA_STOCK_CONFIG_DIR to be able to use edit-config.

##### OS / Environment

Ubuntu 18.04

##### Netdata version (ouput of `netdata -V`)

v1.16.0-70-nightly

##### Component Name

Ubuntu packaging

##### Steps To Reproduce

```
# /etc/netdata/edit-config netdata.conf
File 'netdata.conf' is not found in '/usr/local/lib/netdata/conf.d'
```

##### Expected behavior

Editor with netdata.conf should be opened.

**Comment by ilyam8** [comment]
How did you install netdata @berendt?

**Comment by paulkatsoulakis** [comment]
Hello @berendt, thanks a lot for your report! Sorry to hear you bumped into problems.
Could provide us with more details please?

1. Output of `cat /etc/os-release`
2. Installation method
     a) What command exactly did you run?
     b) what was the full output of the execution?

We have multiple distribution channels and we may be looking at a very specific issue

**Comment by berendt** [comment]
I used https://packagecloud.io/netdata/netdata-edge/. Installation as usual with `apt-get install netdata netdata-data`.

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

```$ apt-cache policy netdata
netdata:
  Installed: 1.16.70
  Candidate: 1.16.70
  Version table:
 *** 1.16.70 500
        500 https://packagecloud.io/netdata/netdata-edge/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.16.43 500
        500 https://packagecloud.io/netdata/netdata-edge/ubuntu bionic/main amd64 Packages
     1.16.10 500
        500 https://packagecloud.io/netdata/netdata-edge/ubuntu bionic/main amd64 Packages
     1.9.0+dfsg-1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

**Comment by paulkatsoulakis** [comment]
Issue seems to have been fixed since last nightly.
@berendt Kindly let me know if that looks okay for you.

Keep in mind that we had to stick with FHS standard paths regarding our configuration, because we need to maintain compatibility across many distributions and we need to be able to efficiently troubleshoot.

but please any thoughts or concerns, do not hesitate to share.
Thanks again for reporting this, it was an excellent catch on an issue that we were kinda see it coming!
