### ISSUE TITLE
Configure is unable to find OpenSSL libraries on Gentoo.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#6669]
##### Bug report summary

The generated `configure` script fails to find OpenSSL on Gentoo systems.

##### OS / Environment

Gentoo Linux (probably also Gentoo derivatives).

##### Netdata version (ouput of `netdata -V`)

Current master branch.

##### Component Name

build

##### Steps To Reproduce

On a Gentoo system with all the required dependencies for Netdata installed, try to build Netdata by hand.

##### Expected behavior

The configure script correctly detects that OpenSSL is installed.

----

Originally came up as part of working on #5979, which is functionally dependent on this being fixed.

I'm fairly certain something is going wrong internally in the configure script, as OpenSSL is part of the base install on Gentoo and is fully installed on all of the systems I've checked this on.  Gentoo does not have separate development versions of packages, it just installs all the headers alongside any given library.

Sample [config.log](https://github.com/netdata/netdata/files/3505343/config.log) from a failed build (configure was invoked with `--enable-dbengine`, so not finding OpenSSL was fatal).

<details>
<summary>Sample configure output from a failed build.</summary>
<pre>
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for __attribute__((returns_nonnull))... yes
checking for __attribute__((malloc))... yes
checking for __attribute__((noreturn))... yes
checking for __attribute__((noinline))... yes
checking for __attribute__((format))... yes
checking for __attribute__((warn_unused_result))... yes
checking for struct timespec... yes
checking for clockid_t... yes
checking for library containing clock_gettime... none required
checking for clock_gettime... yes
checking for sched_setscheduler... yes
checking for sched_getscheduler... yes
checking for sched_getparam... yes
checking for sched_get_priority_min... yes
checking for sched_get_priority_max... yes
checking for getpriority... yes
checking for setpriority... yes
checking for nice... yes
checking for recvmmsg... yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for inline... inline
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... yes
checking for _Generic... yes
checking for __atomic... yes
checking size of void *... 8
checking whether sys/types.h defines makedev... no
checking sys/mkdev.h usability... no
checking sys/mkdev.h presence... no
checking for sys/mkdev.h... no
checking sys/sysmacros.h usability... yes
checking sys/sysmacros.h presence... yes
checking for sys/sysmacros.h... yes
checking for sys/types.h... (cached) yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking for sys/prctl.h... yes
checking for sys/vfs.h... yes
checking for sys/statfs.h... yes
checking for sys/statvfs.h... yes
checking for sys/mount.h... yes
checking for accept4... yes
checking operating system... linux with id 1
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for sin in -lm... yes
checking if libm should be used... yes
checking for uv_fs_scandir_next in -luv... yes
checking for LZ4_compress_default in -llz4... yes
checking for JudyLIns in -lJudy... yes
checking for zlib... yes
checking if zlib should be used... yes
checking for uuid... yes
checking for SHA256_Init in -lcrypto... yes
checking for json-c... yes
checking for json_object_get_type in -ljson-c... yes
configure: error: OpenSSL required but not found. Try installing 'libssl-dev' or 'openssl-devel'.
</pre>
</details>

**Comment by paulkatsoulakis** [comment]
This is actually a great finding!
It seems that when checking for both HTTPS and DB Engine dependencies, doesn't compute well.

I don't get why we didn't bump into this earlier. Probably the problem was hidden by auto-detection. Posting a PR to fix this

**Comment by Ferroin** [comment]
> Probably the problem was hidden by auto-detection. 

Yeah, it appears to have been just silently failing the check when using autodetection.

The involvement of HTTPS checks also explains why I didn't run into this back when the dbengine stuff got added, HTTPS wasn't present then, so it just worked.
