### ISSUE TITLE
illegal characters (;) in URLS (fragment)

### ISSUE THREAD

**Issue by karlhungus** [netdata/netdata#6674]
##### Bug report summary

netdata uses a `;` as a [separator for it fragments](https://github.com/netdata/netdata/blob/7648928e7db8b12a52e03ee0f4f05602c986701b/web/gui/main.js#L84). This trips up some security software. [RFC 3986](https://tools.ietf.org/html/rfc3986#page-49) describes valid characters after fragments.

##### OS / Environment
N/A

##### Netdata version (ouput of `netdata -V`)
1.10.0 (but also head)

##### Component Name
web

##### Steps To Reproduce
Visit a dashboard on the provided docker image url contains `;` i.e. http://localhost:19999/#;theme=slate

##### Expected behavior
Ideally replace semicolons with something valid like `.`

Related Issue https://github.com/netdata/netdata/issues/3819

**Comment by thiagoftsm** [comment]
Hi @karlhungus ,

The Netdata webserver follows the RFC using '&' as separator, this specific feature is used in our dashboard that wil be changed in a near future, I will discuss with our team about this problem that you are reporting, but when I tried to access the Netdata( the latest version) I did not have any problem to see the charts and work with the software.

Best regards!

**Comment by ilyam8** [comment]
> The Netdata webserver follows the RFC using '&' as separator

That separator is for querires, the issue aboutkn fragments separator

rel: https://stackoverflow.com/questions/566276/what-two-separator-characters-would-work-in-a-url-anchor
