### ISSUE TITLE
Network traffic seen from master to slave from port 19999

### ISSUE THREAD

**Issue by tctovsli** [netdata/netdata#6676]
##### Question summary
I'm having an issue with reconnects between the master and one of the slaves, when I stumbled upon som discarded packets in the firewall.
I've only opened the traffic from slave to master on **destination port** 19999, but there seems to be traffic from the master on **source port** 19999 towards random high ports on the slaves.
Is this correct?
Is the slave initiating the connection, and then the master is connecting back on other ports?

Could you perhaps write a little document on what exact ports are used in each direction, as this was not very clear?

##### Component Name
streaming
documentation

**Comment by cakrit** [comment]
I expect you're seeing the client port of the TCP connection, i.e. something like this (from the master point of view):
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State 
tcp        0      0 192.168.122.1:19999     192.168.122.162:42258   ESTABLISHED
```
It's still a single TCP connection.

**Comment by tctovsli** [comment]
Actually, this was what I expected. However, in our firewall appliance, I see discarded packets with source netdata-master and source port 19999. It looks like it's trying to connect from the master to the slave.

Allowing that traffic was possible, but it didn't solve my disconnect issues, though.

**Comment by cakrit** [comment]
Well the master does need to respond to the slave, so it definitely needs to send packets. But it doesn't establish any connections (it can't anyway, the slave wouldn't permit it). Any more details on your disconnect issues with the firewall enabling the packets both ways? We'll need the slave and master `error.log`.

**Comment by tctovsli** [comment]
Yeah, I started a new issue in #6679 . I think we can continue this thread there.
