### ISSUE TITLE
How to enable the freeipmi.plugin in docker

### ISSUE THREAD

**Issue by haoxingxing** [netdata/netdata#6681]
##### Question summary
I want to enable the plugin in the docker,but in the doc,I dont find any infomation about it
[freeipmi.plugin](https://docs.netdata.cloud/collectors/freeipmi.plugin/)
##### OS / Environment
ubuntu aarch64(arm64) with docker
##### Component Name
plugins in docker

**Comment by Saruspete** [comment]
Hello,

Your ARM board must provide IPMI entry through `/dev/ipmi/` or `/dev/ipmi0` on your docker host.
Then, you must allow this device (usually c / 240 / 0) on your docker, and mknod it.
Also, if your container is running as non-root, you'll need to ensure its user has access to this device.

Alternatively, you can connect remotely through network to your IPMI interface, providing the host/user/pass on the commandline. 
Eg, for user=hello / pass=world

```
[plugin:freeipmi
  update every = 10
  command options = driver-type LAN_2_0 hostname your-ipmi-board username hello password world 
```

**Comment by Saruspete** [comment]
Hello,

Did you manage to test it on your board with required changes ?

Cheers

**Comment by haoxingxing** [comment]
thanks,
but I finally found my board doesnt have a ipmi device
