### ISSUE TITLE
Support for a fully offline installation using pre-compiled binary

### ISSUE THREAD

**Issue by sahilarora535** [netdata/netdata#6684]
##### Feature idea summary
In the current set of installation methods available for netdata as per the documentation, the pre-compiled binary installation method script downloads the binaries straight from Github, and then installs it on the machine. In some enterprises, we do not have the luxury to do that since we might not have internet access. There should also be some script which we can use and also supply the binary ourselves, which will make the installation fully offline.

##### Expected behavior
Something like this should make sense:

```
/path/to/kickstart-static64.sh /path/to/pre-built-binary
```
This should skip downloading the binary from the internet and just install the binary from the location provided. There should be no connection to the internet to install netdata.

**Comment by ilyam8** [comment]
I see we have `*.run` files on the [`Releases`](https://github.com/netdata/netdata/releases) page (see `Assets`), they can be installed offline:
 - make it executable
 - execute

**Comment by cakrit** [comment]
Sure, but Sahil is correct in that we don't describe in our docs an offline installation method. @paulkatsoulakis could you add these instructions, perhaps as an additional section, or a paragraph in the static installation method?

**Comment by sahilarora535** [comment]
@cakrit Thank you very much. Having a documentation section which describes how to install using this `.run` file would be super.

**Comment by paulkatsoulakis** [comment]
The PR #6693 already mention this, but it seems that indeed we don't pay enough attention for the static64 case.Please check section https://docs.netdata.cloud/packaging/installer/#offline-installations

I will propose some more documentation changes with a separate PR., thanks for pointing out the issue @sahilarora535 !
