### ISSUE TITLE
netdata header UI is broken

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#6687]
##### Bug report summary

netdata web UI header is broken if the hostname is a little long.

##### OS / Environment

Mac OS / Mac Book Pro / Chrome

##### Netdata version (ouput of `netdata -V`)

v1.16.0

##### Component Name

We UI

##### Steps To Reproduce

Open the web UI with a long hostname server.

##### Expected behavior

Header should not break

![netdata-header](https://user-images.githubusercontent.com/8895721/63240889-a15dcd80-c28c-11e9-8210-90012b41fd2a.jpg)

**Comment by ilyam8** [comment]
looks related: #6455

**Comment by cakrit** [comment]
Indeed, try the latest nightly @Wing924, you should see it go away. v1.17 is coming in a week or two, if you'd rather wait for the stable. Please close if the latest is ok for you.

**Comment by Wing924** [comment]
@cakrit Thank you! I'll close this issue and wait for v1.17

**Comment by ilyam8** [comment]
dup of #5812
