### ISSUE TITLE
Auth token Error

### ISSUE THREAD

**Issue by hamza-younas94** [netdata/netdata#6690]
Netdata was working fine today morning i tried to open the Net Data its start giving me error:

```
{
  "status": 1106,
  "description": "Auth token corrupted",
  "data": {}
}
```

**Comment by cakrit** [comment]
@hamza-younas94 I expect you had signed in and then you started seeing this, correct?
Adding @nicolasparada and perhaps @cosmix can also have a look. I expect that clearing your browser's application storage for netdata.cloud and any cookies will force you to sign in again and make the issue go away.

**Comment by hamza-younas94** [comment]
@cakrit  there isnt any authentication, i am using caprover

**Comment by cakrit** [comment]
Then I'm not sure where that error is coming from, as netdata uses authentication tokens only for the Sign In functionality. Can you please provide more details and screenshots?

**Comment by hamza-younas94** [comment]
![Screenshot from 2019-08-19 16-40-14](https://user-images.githubusercontent.com/2129240/63262710-1a1a5500-c2a0-11e9-9d12-6618b71e043d.png)
![Screenshot from 2019-08-19 16-40-34](https://user-images.githubusercontent.com/2129240/63262711-1b4b8200-c2a0-11e9-820f-fb5428779be6.png)

**Comment by nicolasparada** [comment]
This error comes from crapover https://github.com/caprover/caprover/blob/c9897258bc2968527178c37d0019f72d7430b49a/src/user/Authenticator.ts#L140 While reading cookie `captainCookieAuth` which is unrelated to Netdata.
The same issue is reported here https://github.com/caprover/caprover/issues/213.

**Comment by cakrit** [comment]
Closing as not related to netdata.

**Comment by loopmatix-dev** [comment]
Seems some issue with caprover's browser cookies.

`Work-around: ` 
1. Login to caprover from **Incognito mode** / Private window.
2. Access NetData Engine.

Works fine for me!
