### ISSUE TITLE
Static distribution overwrites edited config files, ignores /etc/netdata

### ISSUE THREAD

**Issue by deanishe** [netdata/netdata#6692]
##### Bug report summary

When running the static version installer (`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`), which is the recommended way to update, the installer overwrites my edited `netdata.conf` file with its empty one.

I've tried moving the config files I've edited to `/etc/netdata`, but the binary version appears to ignore this folder.

##### OS / Environment

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
```

##### Netdata version (ouput of `netdata -V`)

netdata v1.16.1-62-gd261783c

##### Component Name

Binary installer

##### Steps To Reproduce

```bash
# Install netdata
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)

# Get complete netdata.conf file and make changes
cd /opt/netdata/etc/netdata
curl http://localhost:19999/netdata.conf > netdata.conf
vi netdata.conf  # change something...

# Run installer again (i.e. update netdata)
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)

# Config file has been overwritten:
cat netdata.conf
# netdata can generate its own config which is available at 'http://<netdata_ip>/netdata.conf'
# You can download it with command like: 'wget -O /opt/netdata/etc/netdata/netdata.conf http://localhost:19999/netdata.conf'
```

##### Expected behavior

The installer should not simply overwrite configuration files the user has edited.

It should offer to either back up the existing config file, place the new one beside it (`netdata.conf.dist` or the like), or also read config from /etc/netdata and leave those files entirely alone.

**Comment by cakrit** [comment]
> The installer should not simply overwrite configuration files the user has edited.

I replicated the issue and it's definitely a bug. Our [suggested update method](https://docs.netdata.cloud/packaging/installer/update/#you-downloaded-a-binary-package) says to run the static64 installer again, so we definitely broke something at some point. The installer shouldn't do anything on `/opt/netdata/etc/netdata`, if it already exists.

> I've tried moving the config files I've edited to /etc/netdata, but the binary version appears to ignore this folder.

Since the installation was done under directory `/opt/netdata`, the user config directory IS `/opt/netdata/etc/netdata`. You can see in the [command line options](https://docs.netdata.cloud/daemon/#command-line-options) that you can start netdata with `-c <config file>` for the main `netdata.conf`, which has options for several directories you can change, including `config directory` in the `[global]` section.

**Comment by deanishe** [comment]
> you can start netdata with `-c <config file>` for the main netdata.conf

Thanks. Unfortunately, the installer also overwrites the systemd `netdata.service` file, too, removing the changes. But that's certainly far less hassle than its overwriting the config file!

**Comment by cakrit** [comment]
I know you can override anything put in netdata.service by putting your changes somewhere else in systemd, but unfortunately I can't remember where.

**Comment by paulkatsoulakis** [comment]
> I know you can override anything put in netdata.service by putting your changes somewhere else in systemd, but unfortunately I can't remember where.

@deanishe, hello! Thanks for reaching out for help and i am sorry you bumped into issues.
netdata.service is the stock options for systemd configuration. To override this you execute a `sudo systemctl edit netdata.service` or `systemctl edit netdata.service` if you are already root.

Indicative article around this: https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services

FWIW our netdata-update.sh script now supports auto-updating static installations, should you wish to enable it running daily.

I 'll get on the bug reported now and come back with more comments about

**Comment by deanishe** [comment]
Oh yeah, good call. `sudo systemctl edit netdata.service` is your huckleberry.

I added the following and it's working perfectly:

```
[Service]
ExecStart=
ExecStart=/opt/netdata/bin/srv/netdata -c /etc/netdata/netdata.conf ...
```

Thanks very much! That's a good enough workaround for now.

**Comment by paulkatsoulakis** [comment]
> Oh yeah, good call. `sudo systemctl edit netdata.service` is your huckleberry.
> 
> I added the following and it's working perfectly:
> 
> ```
> [Service]
> ExecStart=
> ExecStart=/opt/netdata/bin/srv/netdata -c /etc/netdata/netdata.conf ...
> ```
> 
> Thanks very much! That's a good enough workaround for now.

Just for the sake of clarity, using systemctl edit is the way to override systemd settings, it is not a workaround.

I 'll let you know once i have more info on the bug reported, thanks !

**Comment by deanishe** [comment]
> it is not a workaround.

It is for this issue.

**Comment by DougParker1992** [comment]
@paulkatsoulakis, I don't know if there was a regression, but the static64 installer is overwriting my configuration files.

I can confirm that the following files are overwritten:

- `/opt/netdata/usr/lib/netdata/conf.d/stream.conf`
- `/opt/netdata/usr/lib/netdata/conf.d/fping.conf`
- `/opt/netdata/usr/lib/netdata/conf.d/health_alarm_notify.conf`

**Comment by ilyam8** [comment]
@DougParker1992 user configuration is stored in `/opt/netdata/etc/netdata/` in your case, you should modify `stream.conf`, etc there

**Comment by DougParker1992** [comment]
@ilyam8 Awesome, thank you so much for this information! This resolved all of my problems. :)

**Comment by dmfreemon** [comment]
I'm seeing the same issue as the OP, with netdata version 1.20.0.

Bug report summary (which is the same as the OP):

When running the static version installer (bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)), which is the recommended way to update, the installer overwrites my edited netdata.conf file with its empty one.

My repo steps are exactly the same as the OP.

My version string is:
$ /opt/netdata/usr/bin/netdata -V 
netdata v1.20.0-258-g182ea93b

I have confirmed this happens for (at least) these distros:
* CentOS Linux release 7.7.1908 (Core)
* Fedora 31

**Comment by prologic** [comment]
I'm going to focus on #8531 that got filed instead of this older issue.  Thank you @dmfreemon
