### ISSUE TITLE
netdata/ci: Introduce smoke testing for the netdata registry

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6696]
#### Bug report summary
After yesterday's incident, that we come to realise approved and merged code was corrupting the registry APIs, we prioritised the introduction of validations for the registry API on our CI, to block faulty PRs from going into our master branch

CC: @cosmix @cakrit 
##### OS / Environment
Any

##### Netdata version (ouput of `netdata -V`)
Latest

##### Component Name
netdata/ci

##### Steps To Reproduce
N/A

##### Expected behavior
Run CI tests to protect registry workflows

**Comment by prologic** [comment]
@cakrit I didn't look very carefully at the issues when I search searching and putting into a new EPIC to cover off what we need to get done for "Binary Packaging" #7826 -- Do we need _this_ specific issue anymore? I was actually looking for a "smoke testing the packages, netdata agent and API" -- Something we've already talked about and agreed upon.
