### ISSUE TITLE
Is there any administrator permissions for this tool?

### ISSUE THREAD

**Issue by arielman** [netdata/netdata#6697]
Hi
I wanted to know if there are some administrator permissions for this monitoring tool? for example, some screen which only a particular user/group can see? if Y, how can I define it?

**Comment by ilyam8** [comment]
There are no administrator permissions.

> for example, some screen which only a particular user/group can see?

Netdata's dashboard is one screen, what do you mean?

**Comment by cakrit** [comment]
Please see https://docs.netdata.cloud/web/server/#access-lists and https://docs.netdata.cloud/web/server/#binding-netdata-to-multiple-ports for IP/port - based access permissions.

**Comment by ilyam8** [comment]
For my defense - i didnt mention ip/port ACLs/binding options because it doesnt sounds like 

> administrator permissions for this monitoring tool
