### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by aljailane** [netdata/netdata#6699]
##### Bug report summary

warning when | $this > (($status >= $WARNING) ? (0) : (10))
-- | --
db lookup | sum of the sum of dimensions squeezed , of chart system.softnet_stat, starting 10 mins ago and up to now, with options absolute, unaligned.
check every | 1 min
execute | /usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on recovery 1 hour, multiplied by 1.5, up to 2 hours
source | 18@/usr/lib/netdata/conf.d/health.d/softnet.conf

warning when | $this > 0
-- | --
critical when | $this > (($status == $CRITICAL) ? (0) : (60))
db lookup | sum of the sum of dimensions TCPReqQFullDoCookies , of chart ip.tcp_syn_queue, starting 1 min ago and up to now, with options absolute, unaligned.
check every | 10 secs
execute | /usr/libexec/netdata/plugins.d/alarm-notify.shhysteresis on recovery 5 mins, multiplied by 1.5, up to 1 hour
source | 70@/usr/lib/netdata/conf.d/health.d/tcp_listen.conf

##### OS / Environment
Centos 7
##### Netdata version (ouput of `netdata -V`)
v1.16.1-73-nightly

**Comment by ilyam8** [comment]
Hey @aljailane 👋 

What is the problem? It is not clear to be honest. Let me guess - warn/crit conditions? (they are in bold)
