### ISSUE TITLE
Spike: Kubernetes collector endpoint autodiscovery

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#6702]
Spike task to identify what is required in order to discover automatically the ephemeral endpoints in a kubernetes cluster.

**Comment by gpapamathND** [comment]
Requires the feature of Configuration Manager: #6432 

Can be designed together with: #6295

**Comment by cakrit** [comment]
We will need to do this one without the Configuration Manager, perhaps with an addition to the plugins.

**Comment by cakrit** [comment]
Duplicate, I reopened another issue. See epic #7903
