### ISSUE TITLE
give more attention to after/before query params in Empty State

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata#6706]
##### Feature idea summary
When entering Dashboard with too old `after=` / `before=` query params, user should be instructed why there's no data, or/and have the easy possibility of clearing `after=`/`before=`

##### Expected behavior
I know this "Empty" info is important but sometimes it's hard to notice that `after=` and `before=` params have changed, for example in the following scenario:

- on default (bigger) netdata.conf `history` settings, pan left and then click "+" sign, after clicking the `after=` and `before=` query params are set in url.
- decrement history setting so the selected time period (in after/before params) will not be available

Then after refreshing the dashboard shows "Empty" labels. To fix this, user can either 1) clear the query params, or 2) click "+/-" buttons.

It's hard to guess what went wrong - perhaps we should advice the user to reset the current state, or display a reset button?

to recreate the empty state, go to http://frankfurt.my-netdata.io/#menu_system_submenu_cpu;after=1566407760000;before=1566407842000;theme=slate;help=true in icognito mode (or clear localStorage before going there)

**Comment by cakrit** [comment]
The "reset" button is the "play" button we have. This kind of works for the normal charts, but gauges definitely can't benefit from this. It may make sense to add something similar when we see the empty info, but we need to take into account that we really want to take all those play/rewind buttons out of the charts themselves and show one big floating ribbon towards the bottom of the screen, for the entier UI. That will allow us to more easily select longer timeframes with additional buttons (there's a relevant issue open on this), display the time range we're querying for and more. This future ribbon may address this issue as well. cc @ivorjvr for info.

**Comment by jacekkolasa** [comment]
Yes, of course "reset" button works exactly in that case, we can perhaps discuss if we want to display a hint in Empty State to press the "play-reset" button (perhaps only as a tooltip on hover?). Big floating ribbon sounds good, especially since we `sync` by default.

**Comment by ilyam8** [comment]
Closing this because it may not be applicable anymore. @jacekkolasa please, reopen if needed.
