### ISSUE TITLE
apps.plugin: disable Users and  User Groups

### ISSUE THREAD

**Issue by nunojpg** [netdata/netdata#6708]
> apps.plugin provides charts for 3 sections:
> 
> Per application charts as Applications at Netdata dashboards
> Per user charts as Users at Netdata dashboards
> Per user group charts as User Groups at Netdata dashboards

Can per user and per user group be disabled so that I only store application charts?

**Comment by ilyam8** [comment]
Hi @nunojpg 	

I think yes

check `[plugin:apps]` section in the netdata.conf

there you can set command line options

https://github.com/netdata/netdata/blob/1a4e81c218d8e56f367b61b17d5f8e71a2cbb40b/collectors/apps.plugin/apps_plugin.c#L3819-L3827

**Comment by ilyam8** [comment]
from what i see you need

```
  command options = no-users no-groups
```

**Comment by ilyam8** [comment]
It looks like we need to update app plugins documentation

**Comment by ilyam8** [comment]
i dont see those options in the module `helpz either

https://github.com/netdata/netdata/blob/1a4e81c218d8e56f367b61b17d5f8e71a2cbb40b/collectors/apps.plugin/apps_plugin.c#L3829-L3869

**Comment by pmjcreations** [comment]
Hello,

Sorry for re-opening this thread.

I have updated /etc/netdata/netdata.conf file with the following line.

```
[plugin:apps]
	# update every = 1
	command options = without-users without-groups
```

But, I still see all users are listed.

Please see this screenshot https://i.imgur.com/933ScBt.png

Am I missing something? Do I need to restart netdata to see the changes?

**Comment by vlvkobal** [comment]
Have you restarted Netdata and reloaded the dashboard?

**Comment by vlvkobal** [comment]
You can also check if the configuration was applied by accessing http://localhost:19999/netdata.conf

**Comment by pmjcreations** [comment]
Hi @vlvkobal,

I have restarted Netdata, and still, it is listing all the users.

This is not on localhost.

However, accessing http://xx.xxx.xx.xx:19999/netdata.conf says You are not allowed to access this resource.

**Comment by vlvkobal** [comment]
The default configuration
```
allow netdata.conf from = localhost fd* 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
```

You should add the host you are accessing Netdata from to this list. You should restart Netdata to apply any changes in the configuration.

**Comment by pmjcreations** [comment]
Hi @vlvkobal,

I can see that the changes are applied to http://xx.xxx.xx.xx:19999/netdata.conf

[plugin:apps]
	command options = without-users without-groups
	# update every = 1

**Comment by vlvkobal** [comment]
If you still see _Users_ and _User Groups_ in the dashboard, then do a hard reload in your browser.

**Comment by pmjcreations** [comment]
Well, I reopened the incognito window and the _Users_ and _User Groups_ are no more in the dashboard.

However, Here is the mistake I did that I have to acknowledge.

Please see this screenshot once again https://i.imgur.com/933ScBt.png

You can see many lvexxxx. They are indeed users but contained users.

Here is the explanation from the dashboard itself.

> Container resource utilization metrics. Netdata reads this information from cgroups (abbreviated from control groups), a Linux kernel feature that limits and accounts resource usage (CPU, memory, disk I/O, network, etc.) of a collection of processes. cgroups together with namespaces (that offer isolation between processes) provide what we usually call: containers.

Please tell me how do I remove the cgroups from the dashboard.

Would adding `command options = without-cgroups` under the same `[plugin:apps]` works the way without-groups worked?

**Comment by ilyam8** [comment]
Check `[plugins]` section, there is `cgroups = yes`

**Comment by pmjcreations** [comment]
Sooo Goood @vlvkobal and @ilyam8.

That works.
