### ISSUE TITLE
make error when compiling on rhel 6.8

### ISSUE THREAD

**Issue by slaurencelle** [netdata/netdata#6713]
Hello i try to compile netdata on my rhel 6.8 server after installing the package need, i lunch the script :
./netdata-installer.sh --libs-are-really-here 

i receive this error

In file included from collectors/apps.plugin/apps_plugin.c:9:
collectors/apps.plugin/../../libnetdata/libnetdata.h:83:23: error: uuid/uuid.h: No such file or directory
make[2]: *** [collectors/apps.plugin/apps_plugin.o] Error 1
make[2]: Leaving directory `/mnt/netdata'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/mnt/netdata'
make: *** [all] Error 2
 FAILED

Hope you can help

**Comment by paulkatsoulakis** [comment]
hello,  could you list the packages you have installed?
It seems that something is not the way you think it is

**Comment by paulkatsoulakis** [comment]
If the server you are trying to install netdata has access to the internet, i would recommend to follow our [one line install guide](https://docs.netdata.cloud/packaging/installer/#one-line-installation) and in case this fails also, it will help us send the complete output of the above command in a file so that we examine it. Just don't forget to anonymise any sensitive info like IPs or usernames

**Comment by slaurencelle** [comment]
Hellom Paul,

here is the package i install

yum install -y zlib-devel gcc make git autoconf autogen automake pkgconfig

and i did try to use the one liner but nothing happen after i do enter it's just doing a carriage return and new line.

That is why i use the other procedure.

but i got this when running it this way : 
git clone https://github.com/firehol/netdata.git --depth=1
cd netdata/
./netdata-installer.sh
Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues

so i run it with the option suggest since the package was there
./netdata-installer.sh --libs-are-really-here
 
it after that that i got the error i send to open the bug

Stephane

**Comment by paulkatsoulakis** [comment]
Hello @slaurencelle, I am afraid you are not using the right instructions. These are not all the required packages for a manual install and the commands you run seem to be from an old documentation. Could you provide more details where did you find the above instructions?

In the mean time, please choose the desired instructions from this link: https://docs.netdata.cloud/packaging/installer/

The above link describes the exact set of packages you need for a manual installation

**Comment by slaurencelle** [comment]
Hello Paul,

Thanks i use the link for the latest documentation and now it's working !!!

But i like to know how i can add more chart ? like for exemple apache, tomcat and fpm-php monitoring ?

tks in advance for the info !

Stéphane
________________________________
De : Paul Emm. Katsoulakis <notifications@github.com>
Envoyé : 24 août 2019 02:20
À : netdata/netdata <netdata@noreply.github.com>
Cc : slaurencelle <slaurencelle@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [netdata/netdata] make error when compiling on rhel 6.8 (#6713)


Hello @slaurencelle<https://github.com/slaurencelle>, I am afraid you are not using the right instructions. These are not all the required packages for a manual install and the commands you run seem to be from an old documentation. Could you provide more details where did you find the above instructions?

In the mean time, please choose the desired instructions from this link: https://docs.netdata.cloud/packaging/installer/

The above link describes the exact set of packages you need for a manual installation

**Comment by paulkatsoulakis** [comment]
Hello @slaurencelle, i am glad we solved your problem!
Here's the link with details on adding charts: https://docs.netdata.cloud/web/gui/custom/#adding-charts You will find plenty of information around there.

I will be solving this issue for now. In case you have more problems with the charts, please do open a new issue with the right title and all the details so that we can help you solve it
