### ISSUE TITLE
Study augeas to validate/modify design and see if/how we can incorporate it in the solution

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#6718]
Study augeas to validate/modify design and see if/how we can incorporate it in the solution (i.e. whether it can become the heart of the config manager).

**Comment by alexandernst** [comment]
How is this going? Any progress doing an augeas lens for netdata?

**Comment by ilyam8** [comment]
Hi @alexandernst no progress so far but this is still on our roadmap
