### ISSUE TITLE
AM2320 digital i2c temp sensor support

### ISSUE THREAD

**Issue by tommybuck** [netdata/netdata#6721]
##### Feature idea summary
Add support for the i2c AM2320 digital temp sensor on a raspberry pi.
https://www.adafruit.com/product/3721
##### Expected behavior
Show the current tempersture and humidity readings as two graphs under the sensors section of netdata.

**Comment by ilyam8** [comment]
Hm, cant check the link

> Error 1020 Ray ID: 50afac21dd07e00f • 2019-08-23 20:00:23 UTC
Access denied
What happened?
This website is using a security service to protect itself from online attacks.

___

> i2c AM2320 digital temp sensor on a raspberry pi.

Do you know how to get metrics?

**Comment by tommybuck** [comment]
See attached datasheet.

**Comment by ilyam8** [comment]
nothing is attached

**Comment by tommybuck** [comment]
[adafruit-am2320-temperature-humidity-i2c-sensor.pdf](https://github.com/netdata/netdata/files/3555741/adafruit-am2320-temperature-humidity-i2c-sensor.pdf)

**Comment by ilyam8** [comment]
It is not clear from the pdf how to collect data 🤔

**Comment by tommybuck** [comment]
If you read the full code example it prints out the current values from the
sensor.

import time
import board
import busio
import adafruit_am2320
# create the I2C shared bus
i2c = busio.I2C(board.SCL, board.SDA)
am = adafruit_am2320.AM2320(i2c)
while True:
print("Temperature: ", am.temperature)
print("Humidity: ", am.relative_humidity)
time.sleep(2)

**Comment by ilyam8** [comment]
oh, nice, it looks it is easy to add a simple python module

@tommybuck 	try this:
 - copy code to `am2320.chart.py`
 - mode `am2320.chart.py` to python.d dir
 - restart netdata service
 - check the dashboard

```python
try:
    import board
    import busio
    import adafruit_am2320
    HAS_STUFF = True
except ImportError:
    HAS_STUFF = False


from bases.FrameworkServices.SimpleService import SimpleService


ORDER = [
    'temperature',
    'humidity',
]

CHARTS = {
    'temperature': {
        'options': [None, 'Temperature', 'celsius', 'temperature', 'am2320.temperature', 'line'],
        'lines': [
            ['temperature']
        ]
    },
    'humidity': {
        'options': [None, 'Relative Humidity', 'percentage', 'humidity', 'am2320.humidity', 'line'],
        'lines': [
            ['humidity']
        ]
    }
}


class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.am = None

    def check(self):
        if not HAS_STUFF:
            self.error("following libraries are needed to get module working: board, busio, adafruit_am2320")
            return False

        try:
            i2c = busio.I2C(board.SCL, board.SDA)
            self.am = adafruit_am2320.AM2320(i2c)
        except Exception as error:
            self.error("error on creating I2C shared bus : {0}".format(error))
            return False

        return True

    def get_data(self):
        return {
            'temperature': self.am.temperature,
            'humidity': self.am.relative_humidity,
        }

```

**Comment by tommybuck** [comment]
I have done the above but it doesn't show up in the dashboard. Does it need a config file or a file editing to configure it?

**Comment by ilyam8** [comment]
@tommybuck 	

You need to place it to `python.d`. If netdata and pytho.d.plugin is running you can find the dir by using this command

```
test@debian10:~$ ps aux |  grep -E -o "[^ ]+/[p]ython.d.plugin" | sed 's/plugins\.d\/python\.d\.plugin/python.d\//'
/opt/netdata/usr/libexec/netdata/python.d/
```

In my case abs path to `python.d` is 

> /opt/netdata/usr/libexec/netdata/python.d/

it is a dir with `*.chart.py` files

```
test@debian10:~$ ls /opt/netdata/usr/libexec/netdata/python.d/
adaptec_raid.chart.py   chrony.chart.pyc          energid.chart.py      go_expvar.chart.pyc  litespeed.chart.py   mysql.chart.pyc       oracledb.chart.py          powerdns.chart.pyc    retroshare.chart.py   springboot.chart.pyc  varnish.chart.py
...
...
```

**Comment by tommybuck** [comment]
I have moved the am2320.py file to /usr/libexec/netdata/python.d/

`/usr/libexec/netdata/python.d $ ls -lh a*`
-rw-r--r-- 1 root netdata 6.5K Sep 17 20:46 adaptec_raid.chart.py
-rw-r--r-- 1 root netdata 8.6K Sep  9 21:33 adaptec_raid.chart.pyc
-rw-r--r-- 1 root netdata 1.6K Sep  9 20:46 **am2320.chart.py**
-rw-r--r-- 1 root netdata 4.3K Sep 17 20:46 apache.chart.py
-rw-r--r-- 1 root netdata 4.1K Sep  9 21:33 apache.chart.pyc
....

Also added `am2320: yes` to /usr/lib/netdata/conf.d/python.d.conf

now getting this in the error.log:
2019-09-17 21:14:45: python.d WARNING: plugin[main] : [am2320] 'am2320.conf' was not found
2019-09-17 21:14:45: python.d INFO: plugin[main] : [am2320] built 1 job(s) configs
2019-09-17 21:14:48: python.d ERROR: am2320[am2320] : following libraries are needed to get module working: board, busio, adafruit_am2320
2019-09-17 21:14:48: python.d INFO: plugin[main] : am2320[am2320] : check failed

But if I run the test code above [(comment)](https://github.com/netdata/netdata/issues/6721#issuecomment-528423942) it works and I see values printed to the screen.

What shall I try next?

**Comment by ilyam8** [comment]
This is the problem

> following libraries are needed to get module working: board, busio, adafruit_am2320


```python
try:
    import board
    import busio
    import adafruit_am2320
    HAS_STUFF = True
except ImportError:
    HAS_STUFF = False
```

^^ that import failed



> But if I run the test code above (comment) it works and I see values printed to the screen.

What python version do you use?

**Comment by ilyam8** [comment]
1. update to the latest
2. cd /usr/libexec/netdata/plugins.d/
3. sudo su -s /bin/bash netdata
4. TRY ./python.d.plugin am2320 -ppython2 AND ./python.d.plugin am2320 -ppython3

**Comment by tommybuck** [comment]
> 
> 
> This is the problem
> 
> > following libraries are needed to get module working: board, busio, adafruit_am2320
> 
> ```python
> try:
>     import board
>     import busio
>     import adafruit_am2320
>     HAS_STUFF = True
> except ImportError:
>     HAS_STUFF = False
> ```
> 
> ^^ that import failed
> 
> > But if I run the test code above (comment) it works and I see values printed to the screen.
> 
> What python version do you use?

the system has both 2.7 and 3.7. However the Adafruit modules are python 3 only.

**Comment by tommybuck** [comment]
>     4\. ./python.d.plugin am2320 -ppython2

`/usr/libexec/netdata/plugins.d$ ./python.d.plugin am2320 -ppython2`
2019-09-17 22:19:42: python.d INFO: plugin[main] : using python v2
2019-09-17 22:19:42: python.d ERROR: plugin[main] : unknown modules : ['-ppython2']
2019-09-17 22:19:42: python.d INFO: plugin[main] : probably you meant :
['am2320']

`/usr/libexec/netdata/plugins.d$ ./python.d.plugin am2320 -ppython3`
2019-09-17 22:20:42: python.d INFO: plugin[main] : using python v2
2019-09-17 22:20:42: python.d ERROR: plugin[main] : unknown modules : ['-ppython3']
2019-09-17 22:20:42: python.d INFO: plugin[main] : probably you meant :
['am2320']

**Comment by ilyam8** [comment]
@tommybuck 	

i think you missed 1.

> update to the latest

**Comment by tommybuck** [comment]
`netdata -V`
netdata v1.17.1

**Comment by ilyam8** [comment]
This feature was added in https://github.com/netdata/netdata/pull/6781 (was merged several hrs ago)

[This script](https://github.com/netdata/netdata/issues/6721#issuecomment-528423942) works with py2 or py3?

**Comment by tommybuck** [comment]
I have now upgraded to latest version.

Now if I run the command above I get this:
/usr/libexec/netdata/plugins.d$ ./python.d.plugin am2320 -ppython3

2019-10-04 09:39:28: python.d INFO: plugin[main] : using python v3
2019-10-04 09:39:28: python.d WARNING: plugin[main] : [am2320] 'am2320.conf' was not found
2019-10-04 09:39:28: python.d INFO: plugin[main] : [am2320] built 1 job(s) configs
2019-10-04 09:39:28: python.d ERROR: am2320[am2320] : error on creating I2C shared bus : [Errno 13] Permission denied: '/dev/i2c-1'
2019-10-04 09:39:28: python.d INFO: plugin[main] : am2320[am2320] : check failed
2019-10-04 09:39:28: python.d INFO: plugin[main] : no jobs to serve
2019-10-04 09:39:28: python.d INFO: plugin[main] : exiting from main...

However if I don't run it as the netdata user and use sudo it works!

sudo ./python.d.plugin am2320 -ppython3

2019-10-04 09:40:49: python.d INFO: plugin[main] : using python v3
2019-10-04 09:40:50: python.d WARNING: plugin[main] : [am2320] 'am2320.conf' was not found
2019-10-04 09:40:50: python.d INFO: plugin[main] : [am2320] built 1 job(s) configs
2019-10-04 09:40:50: python.d INFO: plugin[main] : am2320[am2320] : check success
CHART netdata.runtime_am2320 '' 'Execution time for am2320' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

CHART am2320.temperature '' 'Temperature' 'celsius' 'temperature' 'am2320.temperature' line 60000 1 '' 'python.d.plugin' 'am2320'
DIMENSION 'temperature' 'temperature' absolute 1 1 ' '

BEGIN am2320.temperature 0
SET 'temperature' = 20
END

CHART am2320.humidity '' 'Relative Humidity' 'percentage' 'humidity' 'am2320.humidity' line 60001 1 '' 'python.d.plugin' 'am2320'
DIMENSION 'humidity' 'humidity' absolute 1 1 ' '

BEGIN am2320.humidity 0
SET 'humidity' = 54
END

BEGIN netdata.runtime_am2320 0
SET run_time = 32
END

**Comment by tommybuck** [comment]
so now we just need to tell the plug-in to run as python3 and it should show up on the dashboard?

**Comment by ilyam8** [comment]
@tommybuck 

> so now we just need to tell the plug-in to run as python3 and it should show up on the dashboard?

It looks like yes. Either it or install needed libraries for py2.

To get python.d.plugin running using py3 you need to add `-ppython3` in `netdata.conf`

find `[plugin:python.d]` section there and modify `command options`

```
[plugin:python.d]
  command options = -ppython3
```

**Comment by tommybuck** [comment]
yep made that change and now it shows up on the dashboard.

Shall I do a pull request to get it added to the repository? Or are you going to do it?

**Comment by ilyam8** [comment]
@tommybuck if you have time please do

Check

> https://docs.netdata.cloud/collectors/python.d.plugin/#pull-request-checklist-for-python-plugins

**Comment by tommybuck** [comment]
Im trying to push a pull request but I'm getting access denied?

**Comment by ilyam8** [comment]
- fork netdata repo to your account (github gui)
 - git clone https://github.com/tommybuck/netdata
 - cd netdata
 - checkout FEATURE_NAME
 - <make changes>
 - git push origin FEATURE_NAME
 - go to https://github.com/tommybuck/netdata, there you will see `make a PR` or something
