### ISSUE TITLE
Netdata reloading itself when a docker container starts / stops

### ISSUE THREAD

**Issue by InfRandomness** [netdata/netdata#6725]
##### Feature idea summary
Hello, today I was working with docker and netdata, I realized that to see the containers I just started, I needed to give a refresh to netdata manually, so I came with this idea : Netdata reloading itself when something happens in the Docker sock by listening it.

##### Expected behavior
Just normal reloading based on the Docker sock.

**Comment by ilyam8** [comment]
>  realized that to see the containers I just started, I needed to give a refresh to netdata manually

Hi @InfRandomness, you dont need to restart netdata, there is a delay, but netdata will autodetect new containers after some time (10 secs by default, there is `check for cgroups every` option under `[plugin:cgroups]` directory in the `netdata.conf`)

**Comment by InfRandomness** [comment]
Oh, alright, I did not see it then (because I refreshed almost directly). Thanks !
