### ISSUE TITLE
See previous data

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#6727]
##### Question summary
I came to my workstation this morning, and I found a ton of "ram.available" critical alerts during the weekend (when computer should idle).

Even though I figured out the culprit (due to my predictable morning routine + realtime graphs), I was wondering, if I could go back in time and explicitly figure out the offending process.

I keep seeing issues around about "saving historical data", but I cannot make enough sense as to what it's status. I also don't have / don't want to get a netdata account.

**Comment by ilyam8** [comment]
>  I also don't have / don't want to get a netdata account.

There are some options:
 - increase history size, see [link](https://docs.netdata.cloud/database/#database)
 - archiving metrics to backends, see [link](https://docs.netdata.cloud/backends/)

**Comment by stdedos** [comment]
Thank you! I'll play around with backends then :smile:
