### ISSUE TITLE
Cannot disable opening netdata.conf from Web

### ISSUE THREAD

**Issue by neneone** [netdata/netdata#6728]
I'd like to disable web access to `netdata.conf` file for security reasons.
I tryied to set `allow netdata.conf from` as the following.
```
allow netdata.conf from = no
```
I didn't work.
I am using Debian 9 with Nginx and all my connections are proxyed through Cloudflare.

**Comment by ilyam8** [comment]
Yo @neneone, this will work

`allow netdata.conf from = locahost !*`

**Comment by ilyam8** [comment]
Syntax: [simple pattern](https://docs.netdata.cloud/libnetdata/simple_pattern/)
