### ISSUE TITLE
plugin python.d/nginx_plus  doesn't support new api

### ISSUE THREAD

**Issue by xbulat** [netdata/netdata#6730]
The current version of plugins nginx_plus is supporting ngx_http_status_module what was deprecated  after version 1.13.3. There is a new status page of nginx-plus is a part of [ngx_http_api_module](http://nginx.org/en/docs/http/ngx_http_api_module.html) and provides a bit another REST API

**Comment by ilyam8** [comment]
To be honest we really need label/tages for nginx_plus module, see https://github.com/netdata/netdata/issues/4986#issue-390919378

**Comment by cakrit** [comment]
@ilyam8 perhaps we can pick this one up as soon as we get labels  support in this quarter.

**Comment by ilyam8** [comment]
Fixing python.d/nginx_plus doesn't really make much sense, will be fixed in go version when we have proper labels support.

**Comment by ilyam8** [comment]
Fixed in https://github.com/netdata/go.d.plugin/pull/992
