### ISSUE TITLE
Netdata queries can be arbitrarily long and can take a long time to complete

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#6733]
##### Bug report summary
Netdata queries can be arbitrarily long and can take a long time to complete, effectively keeping the web server busy. This could lead to a denial of service.
##### Netdata version (ouput of `netdata -V`)
all versions
##### Component Name
web
##### Expected behavior
Either disallow big queries or asynchronously multiplex them to avoid denial of service scenarios.

**Comment by mfundul** [comment]
We should both limit the queries and introduce thread pools to allow the web server to dynamically handle any increase in load in a performant way.

**Comment by thiagoftsm** [comment]
> We should both limit the queries and introduce thread pools to allow the web server to dynamically handle any increase in load in a performant way.

I agree with both suggestions, but only to remember, when we say limit, are we saying that we will limit the data returned or the time to execute?

**Comment by amoss** [comment]
It would make more sense to limit by the amount of data. If we do this then we need some way for the client to continue with the rest of the query, e.g. a stateless token that encodes the remaining part of the query.

**Comment by thiagoftsm** [comment]
> It would make more sense to limit by the amount of data. If we do this then we need some way for the client to continue with the rest of the query, e.g. a stateless token that encodes the remaining part of the query.

I used to do this when I was working with PHP using `$_SESSION` variables, it is also possible to do this using cookies. These are features that we can bring to the web server.
