### ISSUE TITLE
sidebar-info update - DB engine

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata#6734]
##### Feature idea summary
We should remove `Netdata is using ** of memory on **for ** minutes and ** seconds of real-time history.` from the info block on the right-side sidebar. That info is no more valid.

Also, we shouldn't show the tip to use DB engine, if user is already using it.

related to https://github.com/netdata/netdata/issues/6587

**Comment by jacekkolasa** [comment]
@joelhans cc: @cakrit 
We needed to remove `Netdata is using ** of memory on **for ** minutes and ** seconds of real-time history.` sentence because that is not true (the memory and time is wrong), but perhaps we shouldn't remove the `host` information, what do you think? If you agree, could you please provide the changed copy of:

> Every second, Netdata collects # metrics, presents them in # charts and monitors them with # alarms. Netdata is using # MB of memory on HOSTNAME for # hour, # minutes, and # seconds of real-time history.
without the last sentence but with hostname info?

**Comment by joelhans** [comment]
Perhaps it's as simple as this?

> Every second, Netdata collects 2,087 metrics on **HOSTNAME**, presents them in 296 charts, and monitors them with 80 alarms.

While you're mucking with this section, could you add a comma between **charts** and **and**? So, it would read: `...presents them in # charts, and monitors them...`

I'm a big fan of the Oxford comma...

**Comment by jacekkolasa** [comment]
I love the additional coma, I would never come up with that, I'm glad I've asked you to look at it :) done

**Comment by joelhans** [comment]
Well, it was my error to begin with, so this was a good opportunity to fix it!
