### ISSUE TITLE
netdata/packaging: Introduce smoke testing for .deb and .rpm packages

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6739]
##### Feature idea summary
We have introduced binary packages to our users, but we have not introduced sufficient smoke testing and validations 

This task is about creating the necessary CI flows to validate .deb and .rpm packages across all supported distributions

##### Expected behavior
.deb and .rpm packages are validated through the nightly process for:
1) properly installing netdata
2) installed netdata starts up and produces some basic capabilities correctly (service up, registry gives numbers, etc)

**Comment by Ferroin** [comment]
Preliminary work covered by #7735, as we're planning on using the work there for the actual package build process in CI.

**Comment by Ferroin** [comment]
This will likely be closed when #7346.

The actual work for this is functionally done, but it uses Docker, so it won't be in use until we switch away from LXC properly.
