### ISSUE TITLE
netdata/packaging: Add kickstart-static64 testing on CI

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6740]
##### Feature idea summary
We need to gain visibility on the good health of static installer across all distributions
This task will introduce static64 kickstart installer tests in Travis

##### Expected behavior
kickstart-static64 will now be validated through the nightly process for problems

**Comment by prologic** [comment]
@Ferroin I _think_ we can treat "static" packages as anther type of "Binary Package" if you will. We'll just call the OS/Distro something like `linux:static`. I _believe_ it can be done the same way with the patterns/recipes we're establishing in #7826  -- Therefore I'm adding it to #7826

**Comment by Ferroin** [comment]
@prologic Sounds good to me.

**Comment by Ferroin** [comment]
I'm going to look into implementing this in GitHub Actions as part of the Build & Install test workflow.

**Comment by Ferroin** [comment]
PR will be forthcomming after #8383 is merged (as I'm basing the work on that).

**Comment by prologic** [comment]
This will be clsoed by #8864 -- I'm taking over this issue as I'm already actively working on this.

**Comment by Ferroin** [comment]
Long-since done.
