### ISSUE TITLE
[/proc/stat cpuidle] Avoid isolated CPUs

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#6741]
##### Bug report summary
When configured on a typical "real-time" setup, the CPU Idle module (now integrated in proc.plugins (PR #4635) ) freeze the netdata daemon.

On Linux, there is a [boot-param](https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt) "isolcpus" which removes given CPUs to the default scheduling affinity. With nohz_full opt, it also disables all scheduling tick on selected CPUs.
So, no process will be able to run on the listed cpus, unless explicitely granted with `/usr/bin/taskset` or syscall `sched_setaffinity()` (which is called by `pthread_setaffinity_np()` ).

Usually, we isolate these CPUs to dedicate them to a specific latency critical process, which is running in a spinning loop (infinite non-blocking poll) + realtime scheduling policy.

Since PR #4635  cpuidle plugin has been merged inside proc.plugins, which is also part of core netdata daemon. When cpuidle [schedules one of its thread](https://github.com/netdata/netdata/blame/v1.16.0/collectors/proc.plugin/proc_stat.c#L993-L1003) to an isolated cpu, the thread hangs (never scheduled) and netdata can't be stopped / killed (until the blocked thread gets a higher priority than the spinning process).

This hang is normal and expected as the Kernel Scheduler has the explicit order (through realtime policy) to never de-schedule the realtime process (which is spinning in an infinite polling loop). 
That's why we isolate the CPU from the standard scheduling policy through `isolcpus` bootparam.

It's not a bug in netdata per-se, but rather a lack of environment awareness. 

##### OS / Environment
Linux / Redhat 6/7 , Fedora 30, (or any version).

You might need the following sysctl to be effective:
```
kernel.sched_rt_runtime_us = 1000000
```

This sysctl is usually to 950000, which deschedule any realtime process, to let other non-prioritized process to run nonetheless.

##### Netdata version (ouput of `netdata -V`)

> netdata v1.16.0

##### Component Name
proc.plugins

##### Steps To Reproduce

To reproduce on a standard desktop (to ack bug):
1. spawn an infinite loop on CPU3 (or any other):  `taskset -c 3 chrt -r 1 bash -c 'while :; do :; done'`
2. Now every process that will go on CPU3 will hang, stuck in "running" state. Try: `taskset -c 3 bash`

here's a typical Realtime setup, on a linux machine (isolating only cpu3) :
1. Add a bootopt `isolcpus=3 nohz_full=3` to grub
2. run as root: `sysctl kernel.sched_rt_runtime_us=1000000` (optional but added for completness)
3. spawn an infinite loop on CPU3:  `taskset -c 3 chrt -r 1 bash -c 'while :; do :; done'`
4. Now every process that will go on CPU3 will hang, stuck in "running" state.

As cpuidle is a thread of core, and is stuck, waiting to be scheduled, netdata won't be able to stop properly.

As a side effect, Load average increase quickly and dramatically.

##### Expected behavior

By default, cpuidle should not try to run on isolated cores (maybe also check for cgroup "cpuset").
You can use `sched_getaffinity()`  on the own pid of proc.plugins to get the default affinity list on which to run the threads. Listing should be able to be modified through config.

Many Thanks.

**Comment by paulkatsoulakis** [comment]
This is indeed an important BUG.
We should not be touching isolated CPUs.
I am setting priority to medium, but i would probably raise it to High too. @cakrit ?

**Comment by ilyam8** [comment]
> Since PR #4635 cpuidle plugin has been merged inside proc.plugins, which is also part of core netdata daemon. When cpuidle schedules one of its thread to an isolated cpu, the thread hangs (never scheduled) and netdata can't be stopped / killed (until the blocked thread gets a higher priority than the spinning process).


This is an big issue, i think we should refactor internal plugins inmplementation @vlvkobal I suggest to open an issue.

**Comment by vlvkobal** [comment]
We can read the list of isolated CPUs from the `/sys/devices/system/cpu/isolated` file and do not touch them with waking threads. It will have a drawback though. If nothing has been done by a cpu core between data collection points, then collected data for cpuidle is wrong. It's also worth mentioning that `isolcpus` is a deprecated kernel parameter and it's strongly advised to use cpusets instead. I don't see any win-win scenario at the moment.

**Comment by mfundul** [comment]
> 
> 
> We can read the list of isolated CPUs from the `/sys/devices/system/cpu/isolated` file and do not touch them with waking threads. It will have a drawback though. If nothing has been done by a cpu core between data collection points, then the collected data for cpuidle is wrong. It's also worth mentioning that `isolcpus` is a deprecated kernel parameter and it's strongly advised to use cpusets instead. I don't see any win-win scenario at the moment.

In this case where real-time threads will consume 100% of a core with a tickless scheduler I believe there will not be any meaningful scheduler statistics anyway, since the application thread will never yield to the kernel. I think it is acceptable to have wrong metrics for those CPU cores, cause in this scenario the kernel `/proc/schedstat` is probably wrong no matter what.

**Comment by Saruspete** [comment]
The isolcpus was [marked as deprecated](https://github.com/torvalds/linux/commit/b0d40d2b22fe48cfcbbfb137fd198be0a1cd8a85) only 2 years ago, in 4.15rc1.
From a distribution PoV (especially a "stable" one like Redhat/CentOS), it's a very new change and not likely to be followed before a long time.

While cpusets are indeed the recommended way for the future, there's little use for them at the moment.

To me, the issue is only related to the pinning of threads to non-standard CPUs. As a sysadmin, if I set a specific list of CPUs to netdata (either by setting it's own sched_setaffinity, either by putting it in a cgroup) I don't expect it to run on CPUs I didn't granted it, even for monitoring.

**Comment by stelfrag** [comment]
A first quick approach would be to introduce a new setting that will limit the cores the server runs on so that at this point allow netdata to stop properly.

**Comment by stelfrag** [comment]
After checking on this, doing some tests and discussing it internally it seems it will be much better and simpler to just read the file with the isolated cpus e.g `/sys/devices/system/cpu/isolated` and avoid pinning those.

**Comment by Saruspete** [comment]
From the kernel source:
sysfs print at `driver/base/cpu.c :: print_cpus_isolated`. Reads `cpu_isolated_map`, which is defined in `kernel/sched/core.c` by `isolated_cpu_setup(char *str)`. It simply sets the value of boot param  `isolcpus=` and parse it into a bitmask.

Thus, `/sys/devices/system/cpu/isolated` is a shortcut over `isolcpus=` bootparam. It doesn't take into account cgroups, custom isolation etc...

So I advocate for the use of `sched_getaffinity` which:
- is be default the value of `/sys/devices/system/cpu/isolated`
- provides the affinity netdata is currently configured with, thus the affinity the system administrator wants netdata to run on.
- takes into account the `cpuset` cgroups, which further restricts (dynamically) the affinity of the process.

**Comment by mfundul** [comment]
In any case, this only needs to happen for the cpu_idle threads in netdata. There is no other pinning taking place in netdata at the moment so we should not waste too much effort making a generic solution right now.

**Comment by stelfrag** [comment]
Thank you @Saruspete , I verified by testing this,  just before you posted the comments above. No parsing is needed and will proceed as @mfundul also suggests
