### ISSUE TITLE
netdata/ci: Wrap up coverity script refinement, make it usable, extend CI pipeline compile checks

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6749]
##### Bug report summary
Currently coverity scans were run exclusively from Travis, resulting on the absence of proper developer toolkit for coverity scanning

As part of this issue we need to:
- [x] wrap up #6747 with a new PR to attend comments and inputs found in #6747

~Update CI pipeline to execute multiple versions of the installer with different configure flags~

- [ ] Make coverity scan run with most (if not all) of the configure flags available for maximum coverage as needed

##### OS / Environment
Any

##### Netdata version (ouput of `netdata -V`)
N/A

##### Component Name
netdata/ci

##### Expected behavior
Coverity should be usable by developers, the CI pipeline that runs coverity should cover all functional cases and once this is resolved C developers should have coverity on their daily agenda

**Comment by paulkatsoulakis** [comment]
Branch `fix-coverity-toolkit` on my fork has the work for this, i 'll be working on it today.
I had to deal with Athens municipality this morning and that got me delayed

**Comment by paulkatsoulakis** [comment]
xenstat plugin proved to be more complex that i thought.
We don't seem to have worked with this on distros other than NCP-ng where the initial development took place.

From the tests i did on Ubuntu 18.04 and Cent OS 7 distributions (containerised), i could not get netdata to compile successfully with any of the available packages.

The error i couldn't get through with is:
```
make[2]: Leaving directory `/netdata/web'
make[2]: Entering directory `/netdata'
  CCLD     xenstat.plugin
/tmp/ccm39i63.ltrans0.ltrans.o: In function `vbd_metrics_collect.isra.2':
/netdata/collectors/xenstat.plugin/xenstat_plugin.c:336: undefined reference to `xenstat_vbd_error'
collect2: error: ld returned 1 exit status
make[2]: *** [xenstat.plugin] Error 1
make[2]: Leaving directory `/netdata'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/netdata'
make: *** [all] Error 2
[root@80ea85095f33 netdata]# history
```

After discussing with @vlvkobal, it seems that we need to work with the following repository to get things running for netdata, rather than using an existing binary package. At least i wasn't able to spot which binary package would cover us.

https://github.com/xen-project/xen

**Comment by paulkatsoulakis** [comment]
Note: I was working on the above because these are necessary considerations for our packaging also, to decide what to do with .deb and .rpm

**Comment by paulkatsoulakis** [comment]
Latest input from @vlvkobal after checking the code, it seems that the missing definition during compile time is due to the fact that binary packages are not on the right version.

Seems that we need Xen 4.12 and above, while the available on the repos (at least the containirised ones) is 4.9

**Comment by arkamar** [comment]
The function `xenstat_vbd_error` will be part of the `4.13` which is currently in `rc1` stage.  https://github.com/xen-project/xen/commit/91c3e3dc91d614d3385d69d03e2dbefbe8abced4

**Comment by prologic** [comment]
Asked the team if we still use this as we have two other static code analysers  we use actively LGTM and Codeacy. @cakrit Are we playing for this at all? We're leaning towards removing this entirely and closing this out if we can the consensus we need.

**Comment by thiagoftsm** [comment]
I agree with @mfundul the emails that Coverity is sent to us are very useful when we merge a code with possible problems.

**Comment by prologic** [comment]
Yeah its okay we got to the above points in the Slack thread :)

The PR that is up now that will fix/close this issue is to migrate off of Travis :D
