### ISSUE TITLE
diskspace plugin on rhel 7.4 not providing netdata_disk_space_GB_average metric

### ISSUE THREAD

**Issue by chrisfw** [netdata/netdata#6750]
##### Question summary
Why does the diskspace plugin not provide any diskspace metrics on my 7.4 RHEL instance, but it works fine on RHEL 6.6.  I am looking for netdata_disk_space_GB_average to be provided  (Note I am using the old units intentionally)  There are no errors in the log related to the diskspace plugin and it appears to be initialized without a problem:
2019-08-31 16:52:28: netdata INFO  : PLUGIN[diskspace] : thread created with task id 177819

##### OS / Environment
RHEL 7.4 and RHEL 6.6
##### Component Name
diskspace plugin
##### Expected results
netdata_disk_space_GB_average provided on both netdata installs (both are version 1.15.0)

**Comment by chrisfw** [comment]
FYI, I have the same problem with the diskspace plugin on another RHEL 6.9 server (netdata v 1.15.0)

**Comment by ilyam8** [comment]
Hi @chrisfw 	

I see there is a condition to do disk space

https://github.com/netdata/netdata/blob/2f5e36ef232a436d98717eb81b0791dbef8cffb1/collectors/diskspace.plugin/plugin_diskspace.c#L252-L254

by default `do_space` is auto

```
[plugin:proc:diskspace]
        # space usage for all disks = auto
        # inodes usage for all disks = auto
```

try to uncomment these options and set value to `yes`

**Comment by vlvkobal** [comment]
Please check the permissions for mount points.

> The plugin requires Netdata to have execute/search permissions on the mount point itself, as well as each component of the absolute path to the mount point.

**Comment by chrisfw** [comment]
@vlvkobal   Following the instructions for this issue [Disk space not available #3716](https://github.com/netdata/netdata/issues/3716) the results are below.  Do I need to do a chmod to add execute or is there another command I need to run?  I followed the other instructions to do the ` cat /proc/self/mountinfo` and `cat /proc/1/mountinfo` and both returned results without error.

```
ls -l /proc/self/mountinfo /proc/1/mountinfo
-r--r--r--. 1 root    root    0 May 30 17:14 /proc/1/mountinfo
-r--r--r--. 1 netdata netdata 0 Sep  2 07:29 /proc/self/mountinfo
```

**Comment by chrisfw** [comment]
> Hi @chrisfw
> 
> I see there is a condition to do disk space
> 
> https://github.com/netdata/netdata/blob/2f5e36ef232a436d98717eb81b0791dbef8cffb1/collectors/diskspace.plugin/plugin_diskspace.c#L252-L254
> 
> by default `do_space` is auto
> 
> ```
> [plugin:proc:diskspace]
>         # space usage for all disks = auto
>         # inodes usage for all disks = auto
> ```
> 
> try to uncomment these options and set value to `yes`
> 
> ^^ this is the case only if `bavail, breserved_root, bused` metrics have zero values
> 
> @vlvkobal please take a look

@ilyam8 I tried uncommenting as you suggested on my RHEL 7.4 server, restarted netdata and unfortunately it did not work.

**Comment by vlvkobal** [comment]
Of course, Netdata has to have access to `mountinfo`. But mount points I mentioned are directories which are listed in `mountinfo`. You should check permissions for these directories.

**Comment by chrisfw** [comment]
If I understood you correctly,  spot checking mountinfo files indicates that the netdata user does appear to have the required permissions.  Note that I removed some output lines for brevity and security:
```
/opt/netdata/netdata-configs]# sudo su - netdata
Last login: Mon Sep  2 08:53:15 CDT 2019 on pts/1
-sh-4.2$ find /proc/*/mountinfo
/proc/100/mountinfo
/proc/102478/mountinfo
/proc/102854/mountinfo
/proc/102855/mountinfo
/proc/102/mountinfo
/proc/103992/mountinfo
/proc/103/mountinfo
/proc/10425/mountinfo
/proc/104/mountinfo
/proc/105/mountinfo
/proc/106070/mountinfo
/proc/106390/mountinfo
/proc/106803/mountinfo
/proc/107/mountinfo
/proc/108444/mountinfo
/proc/108/mountinfo
/proc/109/mountinfo
/proc/10/mountinfo
/proc/110/mountinfo
/proc/111291/mountinfo
/proc/111292/mountinfo
/proc/112167/mountinfo
/proc/112532/mountinfo
/proc/112801/mountinfo
/proc/112802/mountinfo
/proc/112/mountinfo
/proc/113/mountinfo
...
/proc/self/mountinfo
-sh-4.2$ cat /proc/98938/mountinfo
18 62 0:17 / /sys rw,nosuid,nodev,noexec,relatime shared:6 - sysfs sysfs rw,seclabel
19 62 0:3 / /proc rw,nosuid,nodev,noexec,relatime shared:5 - proc proc rw
20 62 0:5 / /dev rw,nosuid shared:2 - devtmpfs devtmpfs rw,seclabel,size=65796272k,nr_inodes=16449068,mode=755
21 18 0:16 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:7 - securityfs securityfs rw
22 20 0:18 / /dev/shm rw,nosuid,nodev shared:3 - tmpfs tmpfs rw,seclabel
23 20 0:11 / /dev/pts rw,nosuid,noexec,relatime shared:4 - devpts devpts rw,seclabel,gid=5,mode=620,ptmxmode=000
24 62 0:19 / /run rw,nosuid,nodev shared:23 - tmpfs tmpfs rw,seclabel,mode=755
25 18 0:20 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:8 - tmpfs tmpfs ro,seclabel,mode=755
26 25 0:21 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:9 - cgroup cgroup rw,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
27 18 0:22 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:20 - pstore pstore rw
28 25 0:23 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,hugetlb
29 25 0:24 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,freezer
30 25 0:25 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:12 - cgroup cgroup rw,perf_event
31 25 0:26 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,memory
32 25 0:27 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,net_prio,net_cls
33 25 0:28 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,blkio
34 25 0:29 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,pids
35 25 0:30 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,cpuset
36 25 0:31 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,cpuacct,cpu
37 25 0:32 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,devices
59 18 0:33 / /sys/kernel/config rw,relatime shared:21 - configfs configfs rw
62 1 253:0 / / rw,relatime shared:1 - ext3 /dev/mapper/rootvg-root rw,seclabel,data=ordered
38 18 0:15 / /sys/fs/selinux rw,relatime shared:22 - selinuxfs selinuxfs rw
39 19 0:35 / /proc/sys/fs/binfmt_misc rw,relatime shared:24 - autofs systemd-1 rw,fd=36,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12547
40 18 0:6 / /sys/kernel/debug rw,relatime shared:25 - debugfs debugfs rw
41 20 0:14 / /dev/mqueue rw,relatime shared:26 - mqueue mqueue rw,seclabel
42 20 0:36 / /dev/hugepages rw,relatime shared:27 - hugetlbfs hugetlbfs rw,seclabel
43 39 0:37 / /proc/sys/fs/binfmt_misc rw,relatime shared:28 - binfmt_misc binfmt_misc rw
77 62 8:1 / /boot rw,relatime shared:29 - ext3 /dev/sda1 rw,seclabel,data=ordered
93 62 253:12 / /home rw,relatime shared:37 - ext3 /dev/mapper/rootvg-home rw,seclabel,data=ordered
95 24 0:38 / /run/user/0 rw,nosuid,nodev,relatime shared:119 - tmpfs tmpfs rw,seclabel,size=13161476k,mode=700
100 24 0:39 / /run/user/205 rw,nosuid,nodev,relatime shared:123 - tmpfs tmpfs rw,seclabel,size=13161476k,mode=700,uid=205,gid=203
105 24 0:40 / /run/user/1009 rw,nosuid,nodev,relatime shared:127 - tmpfs tmpfs rw,seclabel,size=13161476k,mode=700,uid=1009,gid=206```

**Comment by vlvkobal** [comment]
```
$ ls -ld /
drwxr-xr-x 17 root root 4096 Jun  2 15:37 /
```
Here you can see the 'x' flag set on the root directory for other users (not an owner or group member), which means Netdata can get filesystem statistics using the `statvfs()` function.

**Comment by chrisfw** [comment]
Checking with the same command on my server yields the same result as your illustration.
```
-sh-4.2$ ls -ld /
dr-xr-xr-x. 34 root root 4096 May 30 17:16 /
```

**Comment by vlvkobal** [comment]
What configuration do you have in `[plugin:proc:diskspace]` section in `netdata.conf`?

**Comment by chrisfw** [comment]
```
[plugin:proc:diskspace]
        # remove charts of unmounted disks = yes
        # update every = 1
        # check for new mount points every = 15
        # exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/* /snap/* /var/lib/docker/*
        # exclude space metrics on filesystems = *gvfs *gluster* *s3fs *ipfs *davfs2 *httpfs *sshfs *gdfs *moosefs fusectl
         space usage for all disks = yes
         inodes usage for all disks = yes

```

**Comment by ilyam8** [comment]
I think whole error.log would be useful

@chrisfw please do

1. cd to log dir
2. cp /dev/null error.log
3. restart netdata service
4. wait a bit
5. share error.log

**Comment by chrisfw** [comment]
Here it is.  Note I replaced the server name.  There is an error reported for the diskspace plugin regarding a missed heartbeat, but I am not sure if it is significant or not.

[error.log](https://github.com/netdata/netdata/files/3566465/error.log)

**Comment by vlvkobal** [comment]
What responses do you get for `http://localhost:19999/api/v1/chart?chart=disk_space._` and `http://localhost:19999/api/v1/chart?chart=vdisk_space._data02`?

**Comment by chrisfw** [comment]
For the first request, please see the attached file.  For the second, it was a 404.

[diskspace_chart.txt](https://github.com/netdata/netdata/files/3566645/diskspace_chart.txt)

```
--2019-09-02 10:59:55--  http://localhost:16163/api/v1/chart?chart=vdisk_space._data02
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:16163... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-09-02 10:59:55 ERROR 404: Not Found.
```

**Comment by vlvkobal** [comment]
Ok, can you just open your Netdata dashboard in a browser and look at Disks if you have any charts for Disk space utilization? You should have at least one for `/data02` because there is an alarm raised for this mount point in the log you sent.

**Comment by chrisfw** [comment]
There is a chart for /data02, /data01, etc.  So for some reason those chart metrics aren't being included by the api?

![netdata_disks](https://user-images.githubusercontent.com/6135741/64132230-405deb80-cd9c-11e9-8198-e3e94ffd3d65.png)

**Comment by chrisfw** [comment]
@vlvkobal Any thoughts on what I can do next to troubleshoot this issue?

**Comment by vlvkobal** [comment]
Please provide the content of `http://your.netdata.ip:19999/netdata.conf` and `http://your.netdata.ip:19999/api/v1/allmetrics?format=prometheus&help=yes`. You can send it to vlad@netdata.cloud.

**Comment by vlvkobal** [comment]
You set
```
[backend]
	send charts matching = system.* cpu.* mem.* disk.* ipv4.* ip.* ipv6.* net.* services.*
```
in your `netdata.conf`. You have to add `disk_space.*` and `disk_inodes.*` to the list to get Netdata send these charts to prometheus.

**Comment by chrisfw** [comment]
Strange, I don't recall ever modifying that list and for some installs it is populating and others it is not.  I will do as you suggest and let you know.  Thank you @vlvkobal !
