### ISSUE TITLE
Colorblind mode or customizable color scheme

### ISSUE THREAD

**Issue by cxdn** [netdata/netdata#6751]
##### Feature idea summary
I use netdata on my unraid server and it is great, but the heavy use of red and green in the charts makes it difficult on my eyes as I am very colorblind. Its not a huge issue but it would be a nice usability feature for me personally.

**Comment by jacekkolasa** [comment]
@cxdn thanks for the idea. At this moment we are refractoring the dashboard (with backwards compatibility) to react.js stack. There's no sense to add features before we finish with it. After the work will be done, we can discuss that issue.

In the meantime perhaps custom dashboards with custom colours could work for you? https://docs.netdata.cloud/web/gui/custom/#chart-colors

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
