### ISSUE TITLE
Error 405: Cannot download charts index from server - 2019

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6752]
just install netdata... get the same Error 405... have to restar (# netdata restart) manually every reboot not even a cron job do nothing...

_Originally posted by @juanjocastillo in https://github.com/netdata/netdata/issues/475#issuecomment-526959399_

**Comment by cakrit** [comment]
Hi @juanjocastillo,

What is your installation method and on which OS?

**Comment by thiagoftsm** [comment]
Hi @cakrit ,

Did you install Netdata using binary package? Or did you use the netdata-installer.sh?

**Comment by juanjocastillo** [comment]
Tks for the fast response!!
I use the "une line" intall (netdata-installer.sh)
Its a really good soft!! Too bad i have to manually start it every reboot...

**Comment by cakrit** [comment]
@juanjocastillo the `netdata-installer.sh` isn't the one-liner, the `kickstart.sh` is the one liner. The first one requires installing all the dependencies first, as described in https://docs.netdata.cloud/packaging/installer/#install-netdata-on-linux-manually

`kickstart.sh` however (https://docs.netdata.cloud/packaging/installer/#one-line-installation) doesn't need anything. 

By default netdata will go into your systemd, so that you don't have to start it manually. 
So did you just clone the repo and ran `netdata-installer.sh`? In this case, I'd suggest you [uninstall](https://docs.netdata.cloud/packaging/installer/uninstall/) and either do the new [binary installation](https://docs.netdata.cloud/packaging/installer/#binary-packages), or just go with the `kickstart.sh`

**Comment by juanjocastillo** [comment]
@cakrit 
Done... same thing... but now i know whats wrong... 
I'm using port 80, (/etc/netdata/netdata.conf)
right after  i change port 19999 to 80... 
There is something to do to get netdata working on the 80?

**Comment by ilyam8** [comment]
> There is something to do to get netdata working on the 80?

Ports below 1024 are privileged
https://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-on-linux

**Comment by thiagoftsm** [comment]
Hi @juanjocastillo ,

For you use ports below 1024, it is necessary to run Netdata or any software as `root` user, something that is not recommended unless this is strictly necessary.

**Comment by cakrit** [comment]
The gents are correct. Look into running netdata behind a reverse proxy, e.g. [run it behind nginx](https://docs.netdata.cloud/docs/running-behind-nginx/)
