### ISSUE TITLE
install netdata on esxi 6.7

### ISSUE THREAD

**Issue by avsion** [netdata/netdata#6754]
Hi, is netdata available for ESXi? if so how do i install it?

Thank you

**Comment by ilyam8** [comment]
hi @avsion, i dont think it is possible to install netdata directly to esxi (hypervisor).
Netdata has a [vsphere collector](https://github.com/netdata/go.d.plugin/tree/master/modules/vsphere), it monitors esxi hosts/vms via `vCenter`.

**Comment by mfundul** [comment]
Netdata natively runs only on linux, FreeBSD and Mac OS kernels. vmkernel is not supported and is not in the roadmap for the foreseeable future. You should try to follow @ilyam8 's approach.

**Comment by ilyam8** [comment]
> vmkernel is not supported and is not in the roadmap for the foreseeable future. 

i think it is even not possible, so nothing we can do about it

**Comment by avsion** [comment]
I have enabled the built in netdata on freenas 11.2 U5 very cool however ATM only v1.10 is available which missing freeipmi for temp monitoring. totally understand , it would be great if i could monitor my server, will check out vsphere collector option.  BTW love your work and contribution your a rockstars!!!

**Comment by ilyam8** [comment]
v1.10 is ancient 👴

**Comment by avsion** [comment]
i know FreeNAS Policy check every version before any release, which is the right way to do it, netdata update is disabled and even FreeNAS pkg to prevent breaking it.  i assume we can use iocage or ports which we are using to install apps such as unifi controller..etc however not sure what charts and version are available. cheers
