### ISSUE TITLE
Some servers are grouped?

### ISSUE THREAD

**Issue by ExchequerNL** [netdata/netdata#6760]
I have a few servers where I have netdata enabled. I have authorized them all via email. However they seem to be grouped per datacenter. So in the case of these 5 servers the division is 1, 2 and 2. 

Annoyingly when I visit the node page there is a nice overview. However on that page I only see the info of one of the two servers. The only thing that shows there are multiple servers is the top right mentioning of the node url's which hold the two correct server names.

Can I prevent this behavior?

**Comment by VLegakis** [comment]
Hello @ExchequerNL ,
Thank you for reaching out. Could you please provide us with the account under which you register your nodes (email of other means)? Also any additional details of your setup would be very helpful so we take a closer look at your issue. e.g all nodes in each datacenter are reachable by separate public URIs?
Many thanks again,
Vassilis

**Comment by gpapamathND** [comment]
Hi @ExchequerNL 

Could you please send your email address, so we can check what is wrong with your setup? 
We have a scenario that needs to be verified, hence we need your email :)

**Comment by ExchequerNL** [comment]
> 
> 
> Hi @ExchequerNL
> 
> Could you please send your email address, so we can check what is wrong with your setup?
> We have a scenario that needs to be verified, hence we need your email :)

I would but I see no way to send a DM/PM.

**Comment by ilyam8** [comment]
@ExchequerNL just send an email with a link to this issue and requested data to `gp@netdata.cloud`

**Comment by gpapamathND** [comment]
@ExchequerNL would you mind to send an email here: `gp@netdata.cloud` to help proceed ? 
Also, previous week our team did some updates in the netdata cloud. Could you please try again and report if the problem persists ?

**Comment by ExchequerNL** [comment]
Hi sorry for my slow response, I have sent the mail as requested.

**Comment by gpapamathND** [comment]
Thank you @ExchequerNL we are checking and revert.

**Comment by cakrit** [comment]
> So in the case of these 5 servers the division is 1, 2 and 2.

The screenshot you sent us shows clearly that we have only two servers, one with 3 urls (deko2) and one with 2 urls (pro1). We also saw that more recently, a third server was added, with 1 url (deko1). 

The "grouping" you see is probably an artifact of using the same exact image that contains the GUID for the initial server you set up, to create that image. If the same machine GUID (`/var/lib/netdata/registry/netdata.public.unique.id`) is the same in more than one host, things are unpredictable. This file is auto-generated the first time a netdata runs on a machine and is supposed to be unique for each netdata instance. I expect that all your problems start from there.

You can just delete that file and restart. When you visit those servers again, while signed in, you should see new entries in the list. Please also ensure they do not share the same hostname, or that you configure in `netdata.conf` section `[global]` `hostname

**Comment by ExchequerNL** [comment]
Hi cakrit,

I can confirm deleting the GUID and changing the conf fixed the issue. Maybe you guys can add a hostname check when the update is run manually? I tend to clone a lot :)

regards

**Comment by cakrit** [comment]
We have added clearer error messages in the streaming log and will also warn users about this if they start using the cloud and claim their servers (after the next cloud release).
