### ISSUE TITLE
Cross compilation libjudy backends

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6763]
##### Feature idea summary
To cross compile Netdata, it will be necessary to have the Dbengine and  the communication with backends.
##### Expected behavior
When we deliver the Netdata windows version we will use Dbengine and communicate with all backends that were already developed.

**Comment by vlvkobal** [comment]
I don't understand what is the issue about. Please update the description and assign an area label.

**Comment by thiagoftsm** [comment]
When we begin to port to Microsoft, libjudy is the unique that is creating problems, all the other libraries we are using we can do cross compilation with it without major problems, this is the motive this issue was created.
