### ISSUE TITLE
Why do the disk io bandwidth and completion charts only display writes, but not reads?

### ISSUE THREAD

**Issue by chrisfw** [netdata/netdata#6773]
##### Question summary
On multiple machines, why does netdata only show writes not reads for IO bandwidth and completion?
##### OS / Environment
RHEL 6.9
##### Component Name
UI Disk Charts and Prometheus Export
##### Expected results
Reads should be shown
![netdata_disks_io](https://user-images.githubusercontent.com/6135741/64216322-66f85100-ce86-11e9-9e89-c843ef15fc36.png)

**Comment by ilyam8** [comment]
Hi @chrisfw

Check dashboard `settings->performance->which dimnsion to show`

**Comment by chrisfw** [comment]
Thank you @ilyam8 .  The reads show now - they are reporting as zero values (as the setting indicates), but I realized those disks are not being hit.  The disks that are active do report reads as expected.  Good to know about that setting and apologies for the confusion.

**Comment by ilyam8** [comment]
Np, to be honest i agree with you, hide all zero values behavior by default is a little bit confusing.
