### ISSUE TITLE
netdata-installer.sh is not copying properly

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6779]
##### Bug report summary
During the tests with the PR #6567 I notice that the `netdata-installer.sh` has an behavior unexpected at least for me. I already had Netdata installed in the default directories, and to test the PR cited, I cloned the repository and I ran the `netdata-installer.sh` again for it compile the binary and move the newest files for the correct directories. When the installer finished the whole process of  compilation, I had the newest binary as expected, but the conf file and the alarms were not moved for the correct directories. I believe that instead to check whether the input files were not present in the destination directory, the installer probably checked the existence of the directory and did not copy any file inside `/usr/lib/netdata/`.

##### OS / Environment
Debian 9.9
##### Netdata version (ouput of `netdata -V`)
netdata v1.17.0-69-gce817e88
##### Component Name
Collector
##### Steps To Reproduce
1 - Installa Netdata using `netdata-installer.sh`.
2 - Get a PR with new collector and run the `netdata-installer.sh`
##### Expected behavior
Copy the files (*.conf and *.py) from the PR to the correct directories.

**Comment by paulkatsoulakis** [comment]
on a first quick thought, If we are talking about problem with new configuration files, we may have an issue related to `configs.signatures` not being updated.

I will run installer with master and then re-run with the branch to see if this is the case.
I may be wrong

**Comment by paulkatsoulakis** [comment]
I am working on debian 9 and can't get the mentioned reproduce.


`root@f8582dc7c477:/usr/lib/netdata/conf.d/health.d# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@f8582dc7c477:/usr/lib/netdata/conf.d/health.d# 
`

The steps i followed:
1) run the kickstart from master branch and installed netdata
2) checked out gearman branch and run `./netdata-installer.sh --dont-wait`

then when the install finished i can see the following files, part of the PR:
```
root@f8582dc7c477:/usr/lib/netdata/conf.d/health.d# ls -l /usr/lib/netdata/conf.d/health.d/gearman.conf 
-rw-r----- 1 root netdata 755 Sep  4 18:28 /usr/lib/netdata/conf.d/health.d/gearman.conf
root@f8582dc7c477:/usr/lib/netdata/conf.d/health.d# 
```
```
root@f8582dc7c477:/usr/lib/netdata/conf.d/python.d# ls -l /usr/lib/netdata/conf.d/python.d/gearman.conf 
-rw-r----- 1 root netdata 2671 Sep  4 18:28 /usr/lib/netdata/conf.d/python.d/gearman.conf
root@f8582dc7c477:/usr/lib/netdata/conf.d/python.d# 
```

I am not sure i can follow what is the problem.
I think i need more help trying to reproduce the issue

**Comment by paulkatsoulakis** [comment]
I don't have rights to close the issue, @thiagoftsm if you confirm that we don't really have issue after all please resolve

**Comment by thiagoftsm** [comment]
I test again and this time everything worked, probably there was some initial garbage with the files, because after I run `netdata-uninstaler.sh` and retest I could see that the process worked fine.
