### ISSUE TITLE
Can't enable plugins because "File *.conf is physically at... which is not in /etc/netdata". Aborting.

### ISSUE THREAD

**Issue by Synchro** [netdata/netdata#6782]
#### Question summary

I have installed netdata from git in /usr/local/src, as recommended by the docs, and the installer installs to `/opt/netdata`, and adds symlinks from `/etc/netdata` and `/usr/lib/netdata` When I try to run the install script, it complains about this arrangement and refuses to install the config files:

```sh
sudo /etc/netdata/edit-config health.d/phpfpm.conf
Copying '/usr/lib/netdata/conf.d/health.d/phpfpm.conf' to '/etc/netdata/health.d/phpfpm.conf' ...
Editing '/etc/netdata/health.d/phpfpm.conf' ...
File '/etc/netdata/health.d/phpfpm.conf' is physically at '/opt/netdata/etc/netdata/health.d/phpfpm.conf', which is not in '/etc/netdata'. Aborting.
```
Similarly for config:

```sh
/etc/netdata/edit-config health_alarm_notify.conf
Editing '/etc/netdata/health_alarm_notify.conf' ...
File '/etc/netdata/health_alarm_notify.conf' is physically at '/opt/netdata/etc/netdata/health_alarm_notify.conf', which is not in '/etc/netdata'. Aborting.
```
Given that this is a standard install, why doesn't this work?
##### OS / Environment
Ubuntu 16.04
##### Expected results

**Comment by paulkatsoulakis** [comment]
Hi @Synchro, thank you so much for your report and i am sorry you faced problems.
I need a few more data to better understand your issue and try to replicate it.

1) I need the output of `cat /etc/os-release`
2) I need the exact command you run for netdata installation
3) I need to know from which path did you execute the mentioned edit config commands

And a clarification: when you mention `When I try to run the install script, it complains about this arrangement and refuses to install the config files`, you actually mean the edit-config script, not the install script, right?

Thanks in advance for your response, i 'll start looking at the possible use case here but your reply would speed up the process a lot

**Comment by Synchro** [comment]
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

A correction about the git repo - it is in `/usr/src/netdata.git`, not `/usr/local/src`. I can't find the original installation command in my shell history, however it was originally installed over a year ago, and it is using `https://github.com/firehol/netdata.git` as its git remote. That said, it appears to be fully up to date - from git log:

```
commit 89e71c474c865da29415b68b03795221721c72de
Author: Joel Hans <joel@netdata.cloud>
Date:   Wed Sep 4 17:04:07 2019 -0700
```

That said, the actual running version is much older - in the UI it says I'm running 1.8.1, as if the updater script isn't working, even though it looks like everything is succeeding.

```
which netdata
/usr/sbin/netdata
ubuntu@system:/usr/src/netdata.git$ netdata -v
netdata v1.17.0-19-g89e71c4
```

I then wondered if I had ended up with two versions installed, and it looks like I do - `/opt/netdata` contains the 1.8.1 version, and I checked the systemd config file and it points at `/opt/netdata/usr/sbin/netdata` instead of `/usr/sbin/netdata`. So I've repointed the git remote, forced a reinstall, changed the exec target in the systemd service file (the forced reinstall didn't replace it), copied the `/opt/netdata/etc/netdata` folder to `/etc/netdata`, replacing the old symlink, and finally remove the `/opt/netdata` folder completely.

It now appears to be happy, and I can run the editor commands.

**Comment by paulkatsoulakis** [comment]
I was afraid you were running an older version that may have caused some kind of confusion.
I am glad the issue is sorted out for you @Synchro, thanks for taking the time to clarify the situation to us.  This feedback will be important to consider for the future, cheers! 

Enjoy the fresh version of netdata and stick around as we 're having plenty of exciting stuff coming soon!
