### ISSUE TITLE
Freeze quick overview on agent UI

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6793]
##### Feature idea summary
Provide a way to freeze the quick overview on the agent UI, similar to the "freeze top row" in workbooks. Allow users to scroll through the other charts, without losing the key metrics.

##### Expected behavior
Something similar to this:

![image](https://user-images.githubusercontent.com/43294513/64362665-355ec180-d00f-11e9-9716-61aac71c78af.png)

**Comment by jacekkolasa** [comment]
@dim08 FYI

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
