### ISSUE TITLE
validate passed attributes in custom dashboards

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata#6798]
##### Feature idea summary
Perhaps it would be a good idea to validate passed attributes do `[data-netdata]` nodes and display warnings in the console. For example `data-desired-units` can be only `auto` or `default`. It's not that hard to make mistake.

We can later discuss different options to modify TS typings fo that they serve both statically and during runtime (for example with https://github.com/gcanti/io-ts) - cc @cosmix @builat @Azein @VLegakis

**Comment by cosmix** [comment]
I agree @jacekkolasa, it would make sense to do that, at least to some extent that would result in a more robust implementation.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
