### ISSUE TITLE
Unicode in log file path

### ISSUE THREAD

**Issue by Avamander** [netdata/netdata#6799]
##### Bug report summary
When trying to monitor an nginx web log I can't enter the log file path properly because I get the error `web_log[nginx_log_3] : unhandled exception on check : 'ascii' codec can't encode character u'\xfc' in position 16: ordinal not in range(128), skipping the job`

##### OS / Environment
Ubuntu 19.04

##### Netdata version (ouput of `netdata -V`)
v1.17.0-26-nightly

##### Component Name
web_log

##### Steps To Reproduce
```
nginx_log_3:
   name: "example"
   path: "/var/log/nginx/ü.log"
```

##### Expected behavior
It reads the log file path nicely

**Comment by ilyam8** [comment]
@Avamander py3 doesnt have such problem. If you have py3 installed you can force python.d.plugin use it.

find `[plugin:python.d]` section in `netdata.conf`

```
[plugin:python.d]
  command options = -ppython3
```

**Comment by ilyam8** [comment]
In addition to my prev post go version has no such problems
> https://github.com/netdata/go.d.plugin/tree/master/modules/weblog
