### ISSUE TITLE
Monitor /proc/pagetypeinfo for memory fragmentation

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#6802]
##### Feature idea summary
The Linux Kernel splits its memory space in Zones (eg, for x86_64):
- DMA : @ 0 to 16MB, for legacy reasons
- DMA32 : @ 16MB to 4GB, for 32bits hardware
- Normal: @4GB to ..., the standard addressing.

Each of these zones is split in pages of 2^10 (1MB for 4KB pagesize) by the **buddyallocator**.
To limit internal fragmentation, it will try to take the smallest page that satisfy the request.

eg: an application requests 100K. The allocator will search for a page of order 7 (128K). If it can't find one, it will try to search for a higher order (8) and split it in 2 half (buddies). If it still can't, it'll do the same twice with an order 9 page, ... up to the max order.

When a page is released, the allocator will try to merge it with its buddy to form a higher page.

If all pages are low-level pages, it often denotes memory fragmentation. Most of the time, this is due to the kernel cache that uses unmovable pages. You can clean the most consumed (inode & dentries) by issuing a "echo 3 >/proc/sys/vm/drop_caches".

The 

A "clean" (ie non-fragmented) machine will have high order pages (8, 9, 10) : 
```
odin [00:13:12][0][~] cat /proc/pagetypeinfo 
Page block order: 9
Pages per block:  512

Free pages count per migrate type at order       0      1      2      3      4      5      6      7      8      9     10 
Node    0, zone      DMA, type    Unmovable      0      0      0      0      2      1      1      0      1      0      0 
Node    0, zone      DMA, type      Movable      0      0      0      0      0      0      0      0      0      1      3 
Node    0, zone      DMA, type  Reclaimable      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone      DMA, type   HighAtomic      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone      DMA, type          CMA      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone      DMA, type      Isolate      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type    Unmovable      1      0      0      0      0      0      1      1      1      1      0 
Node    0, zone    DMA32, type      Movable      2      1      2      0      1      3      2      1      2      1    593 
Node    0, zone    DMA32, type  Reclaimable      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type   HighAtomic      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type          CMA      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type      Isolate      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone   Normal, type    Unmovable    870    530    391    157    103     41      9      2      1      0      0 
Node    0, zone   Normal, type      Movable   5886   9235   5728   4072   1561    324    115     41     12      4  13018 
Node    0, zone   Normal, type  Reclaimable      3      4      8     11      2      3      1      1      1      0      0 
Node    0, zone   Normal, type   HighAtomic      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone   Normal, type          CMA      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone   Normal, type      Isolate      0      0      0      0      0      0      0      0      0      0      0 
```

while a more fragmented server will have mostly low-order pages:
```
Page block order: 9
Pages per block:  512

Free pages count per migrate type at order       0      1      2      3      4      5      6      7      8      9     10 
Node    0, zone      DMA, type    Unmovable      0      1      1      0      2      1      1      0      1      0      0 
Node    0, zone      DMA, type  Reclaimable      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone      DMA, type      Movable      0      0      0      0      0      0      0      0      0      1      3 
Node    0, zone      DMA, type      Reserve      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone      DMA, type          CMA      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone      DMA, type      Isolate      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type    Unmovable    159      6      2      0      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type  Reclaimable      9   8271   6716      0      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type      Movable    589   8078   3128      9      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type      Reserve      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type          CMA      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone    DMA32, type      Isolate      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone   Normal, type    Unmovable   1373   1465   1173      2      0      0      0      0      0      0      0 
Node    0, zone   Normal, type  Reclaimable     14      5     13      0      0      0      0      0      0      0      0 
Node    0, zone   Normal, type      Movable  16256  80265 156907    529     67      0      0      0      0      0      0 
Node    0, zone   Normal, type      Reserve      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone   Normal, type          CMA      0      0      0      0      0      0      0      0      0      0      0 
Node    0, zone   Normal, type      Isolate      0      0      0      0      0      0      0      0      0      0      0 
```

If you want more details, you can see my [memory management presentation](https://www.slideshare.net/Saruspete/memory-management-112860641)

##### Expected behavior

What I'm foreseeing is :
- 1 graph per Zone (DMA, DMA32, Normal) & Usual type (Movable / Unmovable). While DMA is almost useless, it could still be useful for 32bits (if supported). Other types (Reclaimable, HighAtomic, CMA, Isolate) are rarely used and would add dimensions for nothing.
- each graph will have the 10 orders as dimension, named and multiplied by their size (eg, dim0 = 4KB, dim10=1024KB).
- Another stack graph as the distribution of the total memory of the system, between **used** (without detail on the page size, that would need parsing of /proc/*/smaps), and the different pages types.

Would a new file like `collectors/proc.plugin/proc_pagetypeinfo.c` be fine ?

**Comment by mfundul** [comment]
The linux buddy allocator fragmentation issue is of very high importance. Long running servers will definitely suffer from it. Some drivers will attempt to `kmalloc()` large regions which may also break the kernel under those circumstances.

I support this feature request in principle, but I have no strong feeling on the specifics of how the graphs must be presented.

**Comment by Saruspete** [comment]
I'm currently working on it.
For the graphs I needed by experience, I'm currently doing :

- Global available size per-order: 1 Set (the whole system), 10 dim (the 10 orders). This provides overview of the system global fragmentation
- Detail: Per-Numanode & Zone & Type: Type non zero (usually 3: unmovable,movable, reclaimable) * ( Number of NUMA nodes (usually 1 or 2) + 2 (DMA/DMA32 for Node0 only) = 6-8 Sets. 10 Dim each (the 10 orders).  Shows detail on the Type (unmovable, movable, reclaimable) to understand what kind of allocation type is fragmenting the system. Will only create

**Comment by Ferroin** [comment]
> Other types (Reclaimable, HighAtomic, CMA, Isolate) are rarely used and would add dimensions for nothing.

We should at least have the option to have them included, even if they're disabled by default.  CMA is actually used pretty actively on some systems (certain setups on the Raspberry Pi make use of it for example), and fragmentation affecting the Reclaimable pages can be rather important at times.

**Comment by Saruspete** [comment]
Yes, that's planned :  With "auto" I will only add types with non-empty pages (to limit useless metrics), and all can be forcefully listed to be added even if empty.

**Comment by Saruspete** [comment]
For now (wip) I managed to get this :
![netdata_pagetypeinfo](https://user-images.githubusercontent.com/9157986/64573261-01ff9800-d36b-11e9-8e29-28c694d0c837.png)

This is a `find / -ls >/dev/null`, followed by a `echo 3 > /proc/sys/vm/drop_caches`

I'll test on more beefy servers tomorrow.

**Comment by Saruspete** [comment]
I let it run on a server that I rebooted. The gap between the 5GB of fragmented memory and the low 400MB of new, high order contigous after reboot may be tricky to understand.

I would like to add the values of /proc/meminfo to integrate the "consumed" value to the graph.
Is there any way to use the values retrieved by `proc_meminfo.c` so I don't double-read the same file ?

**Comment by Saruspete** [comment]
@vlvkobal / @mfundul  would you have an idea on this (reading data on another module) ? 
Or should I just duplicate the code from meminfo ?

**Comment by mfundul** [comment]
I foresee issues if the data collection frequency (`update_every`) of this collector and meminfo is different...

**Comment by Saruspete** [comment]
Ok, that solves the issue. Too risky, I'll just copy the part i'm interested in.
