### ISSUE TITLE
Strange reporting of app CPU usage (wrong app reported)

### ISSUE THREAD

**Issue by aldem** [netdata/netdata#6805]
##### Bug report summary

In section "Applications/cpu" I have noticed that ssh group is reported as consuming almost 100% CPU constantly, and after manual checking it seems that this is wrong.

I have one process consuming 100% CPU but it is definitely not ssh. After starting another process for testing purpose from different session, usage was doubled. Process tree looks like this:

![image](https://user-images.githubusercontent.com/754722/64477590-b2b83c80-d19d-11e9-8f02-0418f312c86f.png)

isaac64 was the first one reported in ssh group, openssl was the second (started for testing), checking /proc entries didn't reveal anything in exe, path, cmdline or comm that could match "ssh*".

My app_groups config has the line (unchanged from default):

```ssh: ssh* scp dropbear```

If I remove "ssh*", usage is reported as usual ("other"), adding "sshd" causes netdata to account CPU usage for all apps started from ssh sessions for ssh itself, i.e. it looks like it is propagated somehow to sshd, and this makes me wonder why - there are more processes below (and above) sshd...

##### OS / Environment
Debian 10 + Proxmox Kernel (5.0), Debian 9 Proxmox kernel (4.15), Debian 10 Raspberry PI 4 (kernel 4.19.66-v7l+)

##### Netdata version (ouput of `netdata -V`)
netdata v1.16.0, netdata v1.17.0

##### Steps To Reproduce
Login over ssh to system running netdata and run something that consumes 100% CPU for a while (```openssl speed rsa``` is good candidate), observe app CPU usage.

##### Expected behavior
Well... whatever is consuming CPU should be reported where it belongs according to apps_groups definitions :)

**Comment by vlvkobal** [comment]
This is because `sshd` is a parent process. All child stats are accumulated on it. You can create separate groups for `openssl` and `isaac64`.

Please read the [documentation](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin#configuration)

> For each process given, its whole process tree will be grouped, not just the process matched. The plugin will include both parents and children. If including the parents into the group is undesirable, the line other: * should be appended to the apps_groups.conf.

> The order of the entries in this list is important: the first that matches a process is used, so put important ones at the top. Processes not matched by any row, will inherit it from their parents or children.

**Comment by aldem** [comment]
@vlvkobal Thank you for clarification.

Though it would be more logical if ```other: *``` would be included by default in stock configuration, as current behavior is a bit counter-intuitive.
