### ISSUE TITLE
Collectors to provide stats in the past

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#6806]
##### Feature idea summary
some collectors are based on log files, that may not be populated (sync'd) at constant stream, or any other issue that prevents the source of the collector to be fully "realtime".

As the values are stored in line without time reference for each, it could be either a way to disable the timeout check in the core, or an argument to add / update older values than the start of netdata.

##### Expected behavior

Handle a special char / format / keyword in the protocol to put data in the past :
```
BEGIN id.chart
TIME 1567896665
SET varA = 123
SET varB = 567
END

BEGIN id.chart
TIME 1567896666
SET varA = 456
SET varB = 890
END
```

Or a way for the collector to declare itself async, and values pushed in order, but in bulk.

**Comment by cakrit** [comment]
Hm, I don't think we can send past data to netdata though. We'll need to discuss if it's even possible.

**Comment by mfundul** [comment]
> 
> 
> Hm, I don't think we can send past data to netdata though. We'll need to discuss if it's even possible.

It is possible, at least with `memory mode = dbengine`, to fake the timestamps in the same manner the dbengine dataset generator does.

**Comment by Saruspete** [comment]
Wonderful, I needed to test dbengine on my prod to reduce the io induced by `memory mode = map`. 

Do you have a link to test such a "feature" ? :)

**Comment by mfundul** [comment]
> 
> 
> Wonderful, I needed to test dbengine on my prod to reduce the io induced by `memory mode = map`.
> 
> Do you have a link to test such a "feature" ? :)

Well, it is an undocumented feature for internal testing purposes. If you call the netdata binary with the `--help` argument you get:
```
  -W createdataset=N       Create a DB engine dataset of N seconds and exit.
```
which will create the dataset under the hostname folder `dbengine-dataset`. This will be of the chart `example` of python plugin with128 dimensions. I'm not sure if it will be useful to you, but you can inspect the code [here](https://github.com/netdata/netdata/blob/master/daemon/unit_test.c).

**Comment by Saruspete** [comment]
Hello,

The soft I needed this for is updated to provide realtime statistics, so I don't need it anymore
As nobody else has manifested interest in this feature, closing the request.

Thank you all ! :)
