### ISSUE TITLE
Netdata Not Sending Email Notifications (sendmail tested and good)

### ISSUE THREAD

**Issue by compumatter** [netdata/netdata#6807]
##### Question summary
What config am I missing that causes sendmail not to work with Netdata
##### OS / Environment
LINUX 18.04 debian
##### Component Name
Netdata Apache.conf testing
##### Expected results
Expect to receive critical warning of apache stoppage but do not.

This is a youtube video I have created which accurately displays a failing Apache server however does not send the notification email.
https://www.youtube.com/watch?v=a2WjxAqaylU

This sendmail test works from the command line so I know it's not a sendmail issue:

    sudo  /usr/libexec/netdata/plugins.d/alarm-notify.sh test
    Works fine - 3 netdata alarms get echo'd to the screen - see below

```
# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2019-09-08 18:56:45: alarm-notify.sh: INFO: sent email notification for: servermatter test.chart.test_alarm is WARNING to 'admin@compumatter.com'
# OK
# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2019-09-08 18:56:45: alarm-notify.sh: INFO: sent email notification for: servermatter test.chart.test_alarm is CRITICAL to 'admin@compumatter.com'
# OK
# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2019-09-08 18:56:45: alarm-notify.sh: INFO: sent email notification for: servermatter test.chart.test_alarm is CLEAR to 'admin@compumatter.com'
# OK
```
**Furthermore, I actually get these emails in my email client.** 
This my successful /var/log/mail.log based on those sends
```
Sep  8 18:58:38 servermatter postfix/pickup[8238]: C57B18003C: uid=998 from=<netdata>
Sep  8 18:58:38 servermatter postfix/cleanup[21318]: C57B18003C: message-id=<20190909015838.C57B18003C@servermatter.domainmatter.lan>
Sep  8 18:58:38 servermatter postfix/qmgr[8239]: C57B18003C: from=<netdata@servermatter.domainmatter.lan>, size=11268, nrcpt=1 (queue active)
Sep  8 18:58:38 servermatter postfix/pickup[8238]: DD60E8003B: uid=998 from=<netdata>
Sep  8 18:58:38 servermatter postfix/cleanup[21318]: DD60E8003B: message-id=<20190909015838.DD60E8003B@servermatter.domainmatter.lan>
Sep  8 18:58:38 servermatter postfix/qmgr[8239]: DD60E8003B: from=<netdata@servermatter.domainmatter.lan>, size=11408, nrcpt=1 (queue active)
Sep  8 18:58:38 servermatter postfix/pickup[8238]: F172080074: uid=998 from=<netdata>
Sep  8 18:58:38 servermatter postfix/cleanup[21318]: F172080074: message-id=<20190909015838.F172080074@servermatter.domainmatter.lan>
Sep  8 18:58:38 servermatter postfix/qmgr[8239]: F172080074: from=<netdata@servermatter.domainmatter.lan>, size=11366, nrcpt=1 (queue active)
Sep  8 18:58:39 servermatter postfix/smtp[21365]: DD60E8003B: to=<admin@compumatter.com>, relay=ASPMX.L.GOOGLE.com[74.125.20.27]:25, delay=0.49, delays=0.11/0/0.08/0.29, dsn=2.0.0, status=sent (250 2.0.0 OK  1567994319 b9si10868161pgb.478 - gsmtp)
Sep  8 18:58:39 servermatter postfix/qmgr[8239]: DD60E8003B: removed
Sep  8 18:58:39 servermatter postfix/smtp[21364]: C57B18003C: to=<admin@compumatter.com>, relay=ASPMX.L.GOOGLE.com[74.125.20.27]:25, delay=0.67, delays=0.11/0.08/0.08/0.4, dsn=2.0.0, status=sent (250 2.0.0 OK  1567994319 x7si12658995pff.140 - gsmtp)
Sep  8 18:58:39 servermatter postfix/qmgr[8239]: C57B18003C: removed
Sep  8 18:58:39 servermatter postfix/smtp[21366]: F172080074: to=<admin@compumatter.com>, relay=ASPMX.L.GOOGLE.com[74.125.20.27]:25, delay=0.66, delays=0.15/0/0.1/0.4, dsn=2.0.0, status=sent (250 2.0.0 OK  1567994319 k20si11097163pll.184 - gsmtp)
Sep  8 18:58:39 servermatter postfix/qmgr[8239]: F172080074: removed
```
I have set the following configuration values elsewhere within Netdata

/etc/netdata/health_alarm_notify.conf
* sendmail="/usr/sbin/sendmail"
* SEND_EMAIL="YES"
* DEFAULT_RECIPIENT_EMAIL="validemail@mydomain.ext" (changed so kept private)

To test, I stop the Apache server with sudo service apache2 stop

This causes Netdata to show the alarm in it's UI.  Working normally and correctly

However, the email never gets sent and nothing new appears in the /var/log/mail.log 

What sayeth the group ?

Jay
CompuMatter

**Comment by cakrit** [comment]
What do you see in `/var/log/netdata/error.log` when it tries to send the alarm notifications?

**Comment by compumatter** [comment]
Thanks for your quick reply.

An evidently telling statement in the log file :-)

2019-09-09 01:49:48: alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host 'servermatter', chart 'apache_local.requests' to 'webmaster' for 'apache_last_collected_secs' = '12' for status 'WARNING'.
2019-09-09 01:50:38: alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host 'servermatter', chart 'apache_local.requests' to 'webmaster' for 'apache_last_collected_secs' = '62' for status 'CRITICAL'.

It appears to be globally disabled. Where should I be looking to resolve this?

Thanks.

**Comment by compumatter** [comment]
Perhaps relevant settings in /usr/lib/netdata/conf.d/health_alarm_notify.conf

```
# EMAIL_SENDER="user@domain"
# EMAIL_SENDER="User Name <user@domain>"
# EMAIL_SENDER="'User Name' <user@domain>"
# EMAIL_SENDER="\"User Name\" <user@domain>"
EMAIL_SENDER=""

# enable/disable sending emails
SEND_EMAIL="YES"

# if a role recipient is not configured, an email will be send to:
DEFAULT_RECIPIENT_EMAIL="amazon@compumatter.com"
```

**Comment by cakrit** [comment]
Please don't directly edit `/usr/lib/netdata/conf.d/health_alarm_notify.conf`
You want the changes in `/etc/netdata/health_alarm_notify.conf`, which you mentioned in the OP. 

There's no global disabling of notifications that I know of, it just appears that there are no enabled notifications there. However, when the `/usr/libexec/netdata/plugins.d/alarm-notify.sh test` works, netdata should send notifications. One thing I noticed is that you didn't sudo to the `netdata` user, but to root for that test. Please repeat the test by following the instructions [here](https://docs.netdata.cloud/health/notifications/#testing-notifications)
