### ISSUE TITLE
How do I add custom alarms?

### ISSUE THREAD

**Issue by xperator** [netdata/netdata#6810]
##### Question summary
How can I have custom alarms?
I want to have 2 very simple alarms. I want to be notified when

- system reboots
- someone successfully ssh'es to server

I wonder if it's possible to achieve these with netdata's builtin functions, or do I need to write plugins and codes in python, etc..?

##### OS / Environment
Ubuntu

**Comment by ilyam8** [comment]
Hi @xperator 

I think it is possible to be notified when `system reboots` using data from `system.uptime` chart. As for `someone successfully ssh'es to server` you need to write a custom collector.

system reboots example (if system uptime less then 600 - warn)

```
alarm: system_reboot
      on: system.uptime
   units: seconds
   calc: $uptime
   every: 10s
    warn: $this < 600
   delay: down 5m
    info: system was rebooted
      to: sysadmin
```
