### ISSUE TITLE
Install the question request answer on the router

### ISSUE THREAD

**Issue by BH1NBN** [netdata/netdata#6818]
Can I install it on the hnd / axhnd router? I saw the installation instructions and can be installed on more linxu systems such as arch, centos, Alpine, Debian. Currently, I have an ASUS GT AC5300 router. Belongs to hnd, I don't know if it can be successfully installed!

I also tried the automatic installation command but the report was wrong!

**Comment by paulkatsoulakis** [comment]
Thanks for reaching out @BH1NBN, can you try running this installation: https://docs.netdata.cloud/packaging/installer/#linux-64bit-pre-built-static-binary

This is the precompiled version that has bundled in all dependencies and is what we recommend on non common linux x64 operating systems

**Comment by paulkatsoulakis** [comment]
I don't see much details on the official page.
Could you provide more details from the shell you have available? Information like `cat /proc/version` and `busybox` or `busybox --list` (whichever provides busybox details)

**Comment by BH1NBN** [comment]
I hope I didn't understand the error you mean!

**Comment by BH1NBN** [comment]
I hope to understand your meaning correctly!

admin@GT-AC5300:/tmp/home/root# cat /proc/version
Linux version 4.1.27 (sadog@ubuntu) (gcc version 5.3.0 (Buildroot 2016.02) ) #2 SMP PREEMPT Thu Jun 27 16:58:57 CST 2019
admin@GT-AC5300:/tmp/home/root# busybox --list
[
[[
add-shell
arp
arping
ash
awk
base64
basename
bash
blkid
blockdev
cat
chmod
chown
chpasswd
chrt
clear
cmp
cp
crond
cut
date
dd
depmod
df
diff
dirname
dmesg
dnsdomainname
dos2unix
du
echo
egrep
env
ether-wake
expr
false
fatattr
fdisk
fgrep
find
flock
free
fsck
fsck.minix
fstrim
fsync
ftpget
ftpput
getopt
grep
gunzip
gzip
halt
head
hostname
ifconfig
insmod
ionice
kill
killall
klogd
less
ln
logger
login
logread
ls
lsmod
lsusb
makemime
md5sum
mdev
mkdir
mknod
mkswap
modprobe
more
mount
mv
nc
netstat
nice
nohup
nslookup
ntpd
pidof
ping
ping6
poweroff
printf
ps
pwd
pwdx
readlink
reboot
remove-shell
renice
rm
rmdir
rmmod
route
sed
sendmail
setconsole
sh
shuf
sleep
smemcap
sort
split
strings
stty
swapoff
swapon
sync
syslogd
tail
tar
taskset
tee
telnetd
test
tftp
tftpd
time
top
touch
tr
traceroute
traceroute6
true
tty
udhcpc
umount
uname
uniq
unix2dos
unzip
uptime
usleep
vconfig
vi
watch
wc
which
xargs
zcat
zcip

**Comment by paulkatsoulakis** [comment]
Great, thanks for the feedback it sounds good.
Try the instructions i provided and let us know of the results.
We will need all of the command output if the process fails, so that we can understand what happened

**Comment by BH1NBN** [comment]
> Great, thanks for the feedback it sounds good.
> Try the instructions i provided and let us know of the results.
> We will need all of the command output if the process fails, so that we can understand what happened

I know very little about the Linux environment, so I only have some very basic and simple operations! I will try my best to assist you in your operation! I really hope to get your help! Because this netdata is very cool, it can help me observe my router status more intuitively.

**Comment by BH1NBN** [comment]
> Great, thanks for the feedback it sounds good.
> Try the instructions i provided and let us know of the results.
> We will need all of the command output if the process fails, so that we can understand what happened

Because my technical ability is limited, I am not sure if my operation is correct!

===================================================

admin@GT-AC5300:/jffs/tmp# bash < curl -Ss https://my-netdata.io/kickstart.sh 
-sh: can't open （: no such file
admin@GT-AC5300:/jffs/tmp$ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
-sh: syntax error: unexpected "("
admin@GT-AC5300:/jffs/tmp# $ bash < curl -Ss https://my-netdata.io/kickstart.sh
-sh: can't open curl: no such file
-sh: $: not found
admin@GT-AC5300:/jffs/tmp# curl -Ss https://my-netdata.io/kickstart.sh
#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Run me with:
#
# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
#
# or (to install all netdata dependencies):
#
# bash <(curl -Ss https://my-netdata.io/kickstart.sh) all
#
# Other options:
#  --dont-wait       do not prompt for user input
#  --non-interactive do not prompt for user input
#  --no-updates      do not install script for daily updates
#
# This script will:
#
# 1. install all netdata compilation dependencies
#    using the package manager of the system
#
# 2. download netdata nightly package to temporary directory
#
# 3. install netdata

# shellcheck disable=SC2039,SC2059,SC2086

# External files
PACKAGES_SCRIPT="https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh"

# ---------------------------------------------------------------------------------------------------------------------
# library functions copied from packaging/installer/functions.sh

setup_terminal() {
	TPUT_RESET=""
	TPUT_YELLOW=""
	TPUT_WHITE=""
	TPUT_BGRED=""
	TPUT_BGGREEN=""
	TPUT_BOLD=""
	TPUT_DIM=""

	# Is stderr on the terminal? If not, then fail
	test -t 2 || return 1

	if command -v tput >/dev/null 2>&1; then
		if [ $(($(tput colors 2>/dev/null))) -ge 8 ]; then
			# Enable colors
			TPUT_RESET="$(tput sgr 0)"
			TPUT_YELLOW="$(tput setaf 3)"
			TPUT_WHITE="$(tput setaf 7)"
			TPUT_BGRED="$(tput setab 1)"
			TPUT_BGGREEN="$(tput setab 2)"
			TPUT_BOLD="$(tput bold)"
			TPUT_DIM="$(tput dim)"
		fi
	fi

	return 0
}
setup_terminal || echo >/dev/null

# -----------------------------------------------------------------------------
fatal() {
	printf >&2 "${TPUT_BGRED}${TPUT_WHITE}${TPUT_BOLD} ABORTED ${TPUT_RESET} ${*} \n\n"
	exit 1
}

run_ok() {
	printf >&2 "${TPUT_BGGREEN}${TPUT_WHITE}${TPUT_BOLD} OK ${TPUT_RESET} ${*} \n\n"
}

run_failed() {
	printf >&2 "${TPUT_BGRED}${TPUT_WHITE}${TPUT_BOLD} FAILED ${TPUT_RESET} ${*} \n\n"
}

ESCAPED_PRINT_METHOD=
printf "%q " test >/dev/null 2>&1
[ $? -eq 0 ] && ESCAPED_PRINT_METHOD="printfq"
escaped_print() {
	if [ "${ESCAPED_PRINT_METHOD}" = "printfq" ]; then
		printf "%q " "${@}"
	else
		printf "%s" "${*}"
	fi
	return 0
}

progress() {
	echo >&2 " --- ${TPUT_DIM}${TPUT_BOLD}${*}${TPUT_RESET} --- "
}

run_logfile="/dev/null"
run() {
	local user="${USER--}" dir="${PWD}" info info_console

	if [ "${UID}" = "0" ]; then
		info="[root ${dir}]# "
		info_console="[${TPUT_DIM}${dir}${TPUT_RESET}]# "
	else
		info="[${user} ${dir}]$ "
		info_console="[${TPUT_DIM}${dir}${TPUT_RESET}]$ "
	fi

	printf >>"${run_logfile}" "${info}"
	escaped_print >>"${run_logfile}" "${@}"
	printf >>"${run_logfile}" " ... "

	printf >&2 "${info_console}${TPUT_BOLD}${TPUT_YELLOW}"
	escaped_print >&2 "${@}"
	printf >&2 "${TPUT_RESET}\n"

	"${@}"

	local ret=$?
	if [ ${ret} -ne 0 ]; then
		run_failed
		printf >>"${run_logfile}" "FAILED with exit code ${ret}\n"
	else
		run_ok
		printf >>"${run_logfile}" "OK\n"
	fi

	return ${ret}
}

fatal() {
	printf >&2 "${TPUT_BGRED}${TPUT_WHITE}${TPUT_BOLD} ABORTED ${TPUT_RESET} ${*} \n\n"
	exit 1
}

warning() {
	printf >&2 "${TPUT_BGRED}${TPUT_WHITE}${TPUT_BOLD} WARNING ${TPUT_RESET} ${*} \n\n"
	if [ "${INTERACTIVE}" = "0" ]; then
		fatal "Stopping due to non-interactive mode. Fix the issue or retry installation in an interactive mode."
	else
		read -r -p "Press ENTER to attempt netdata installation > "
		progress "OK, let's give it a try..."
	fi
}

create_tmp_directory() {
	# Check if tmp is mounted as noexec
	if grep -Eq '^[^ ]+ /tmp [^ ]+ ([^ ]*,)?noexec[, ]' /proc/mounts > /dev/null 2>&1; then
		pattern="$(pwd)/netdata-kickstart-XXXXXX"
	else
		pattern="/tmp/netdata-kickstart-XXXXXX"
	fi

	mktemp -d $pattern
}

download() {
	url="${1}"
	dest="${2}"
	if command -v curl >/dev/null 2>&1; then
		run curl -sSL --connect-timeout 10 --retry 3 "${url}" >"${dest}" || fatal "Cannot download ${url}"
	elif command -v wget >/dev/null 2>&1; then
		run wget -T 15 -O - "${url}" >"${dest}" || fatal "Cannot download ${url}"
	else
		fatal "I need curl or wget to proceed, but neither is available on this system."
	fi
}

set_tarball_urls() {
	if [ "$1" = "stable" ]; then
		local latest
		# Simple version
		# latest="$(curl -sSL https://api.github.com/repos/netdata/netdata/releases/latest | grep tag_name | cut -d'"' -f4)"
		latest="$(download "https://api.github.com/repos/netdata/netdata/releases/latest" /dev/stdout | grep tag_name | cut -d'"' -f4)"
		export NETDATA_TARBALL_URL="https://github.com/netdata/netdata/releases/download/$latest/netdata-$latest.tar.gz"
		export NETDATA_TARBALL_CHECKSUM_URL="https://github.com/netdata/netdata/releases/download/$latest/sha256sums.txt"
	else
		export NETDATA_TARBALL_URL="https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz"
		export NETDATA_TARBALL_CHECKSUM_URL="https://storage.googleapis.com/netdata-nightlies/sha256sums.txt"
	fi
}

detect_bash4() {
	bash="${1}"
	if [ -z "${BASH_VERSION}" ]; then
		# we don't run under bash
		if [ -n "${bash}" ] && [ -x "${bash}" ]; then
			# shellcheck disable=SC2016
			BASH_MAJOR_VERSION=$(${bash} -c 'echo "${BASH_VERSINFO[0]}"')
		fi
	else
		# we run under bash
		BASH_MAJOR_VERSION="${BASH_VERSINFO[0]}"
	fi

	if [ -z "${BASH_MAJOR_VERSION}" ]; then
		echo >&2 "No BASH is available on this system"
		return 1
	elif [ $((BASH_MAJOR_VERSION)) -lt 4 ]; then
		echo >&2 "No BASH v4+ is available on this system (installed bash is v${BASH_MAJOR_VERSION}"
		return 1
	fi
	return 0
}

dependencies() {
	SYSTEM="$(uname -s 2> /dev/null || uname -v)"
	OS="$(uname -o 2> /dev/null || uname -rs)"
	MACHINE="$(uname -m 2> /dev/null)"

	echo "System            : ${SYSTEM}"
	echo "Operating System  : ${OS}"
	echo "Machine           : ${MACHINE}"
	echo "BASH major version: ${BASH_MAJOR_VERSION}"

	if [ "${OS}" != "GNU/Linux" ] && [ "${SYSTEM}" != "Linux" ]; then
		warning "Cannot detect the packages to be installed on a ${SYSTEM} - ${OS} system."
	else
		bash="$(command -v bash 2>/dev/null)"
		if ! detect_bash4 "${bash}"; then
			warning "Cannot detect packages to be installed in this system, without BASH v4+."
		else
			progress "Downloading script to detect required packages..."
			download "${PACKAGES_SCRIPT}" "${TMPDIR}/install-required-packages.sh"
			if [ ! -s "${TMPDIR}/install-required-packages.sh" ]; then
				warning "Downloaded dependency installation script is empty."
			else
				progress "Running downloaded script to detect required packages..."
				run ${sudo} "${bash}" "${TMPDIR}/install-required-packages.sh" ${PACKAGES_INSTALLER_OPTIONS}
				# shellcheck disable=SC2181
				if [ $? -ne 0 ] ; then
					warning "It failed to install all the required packages, but installation might still be possible."
				fi
			fi

		fi
	fi
}

safe_sha256sum() {
	# Within the contexct of the installer, we only use -c option that is common between the two commands
	# We will have to reconsider if we start non-common options
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum $@
	elif command -v shasum >/dev/null 2>&1; then
		shasum -a 256 $@
	else
		fatal "I could not find a suitable checksum binary to use"
	fi
}

# ---------------------------------------------------------------------------------------------------------------------
umask 022

sudo=""
[ -z "${UID}" ] && UID="$(id -u)"
[ "${UID}" -ne "0" ] && sudo="sudo"
export PATH="${PATH}:/usr/local/bin:/usr/local/sbin"

# ---------------------------------------------------------------------------------------------------------------------
# try to update using autoupdater in the first place

updater=""
[ -x /etc/periodic/daily/netdata-updater ] && updater=/etc/periodic/daily/netdata-updater
[ -x /etc/cron.daily/netdata-updater ] && updater=/etc/cron.daily/netdata-updater
if [ -L "${updater}" ]; then
	# remove old updater (symlink)
	run "${sudo}" rm -f "${updater}"
	updater=""
fi
if [ -n "${updater}" ]; then
	# attempt to run the updater, to respect any compilation settings already in place
	progress "Re-installing netdata..."
	run "${sudo}" "${updater}" -f || fatal "Failed to forcefully update netdata"
	exit 0
fi

# ---------------------------------------------------------------------------------------------------------------------
# install required system packages

INTERACTIVE=1
PACKAGES_INSTALLER_OPTIONS="netdata"
NETDATA_INSTALLER_OPTIONS=""
NETDATA_UPDATES="--auto-update"
RELEASE_CHANNEL="nightly"
while [ -n "${1}" ]; do
	if [ "${1}" = "all" ]; then
		PACKAGES_INSTALLER_OPTIONS="netdata-all"
		shift 1
	elif [ "${1}" = "--dont-wait" ] || [ "${1}" = "--non-interactive" ]; then
		INTERACTIVE=0
		shift 1
	elif [ "${1}" = "--no-updates" ]; then
		# echo >&2 "netdata will not auto-update"
		NETDATA_UPDATES=
		shift 1
	elif [ "${1}" = "--stable-channel" ]; then
		RELEASE_CHANNEL="stable"
		shift 1
	else
		break
	fi
done

if [ "${INTERACTIVE}" = "0" ]; then
	PACKAGES_INSTALLER_OPTIONS="--dont-wait --non-interactive ${PACKAGES_INSTALLER_OPTIONS}"
	NETDATA_INSTALLER_OPTIONS="--dont-wait"
fi

TMPDIR=$(create_tmp_directory)
cd "${TMPDIR}"

dependencies

# ---------------------------------------------------------------------------------------------------------------------
# download netdata package

set_tarball_urls "${RELEASE_CHANNEL}"

download "${NETDATA_TARBALL_CHECKSUM_URL}" "${TMPDIR}/sha256sum.txt"
download "${NETDATA_TARBALL_URL}" "${TMPDIR}/netdata-latest.tar.gz"
if ! grep netdata-latest.tar.gz "${TMPDIR}/sha256sum.txt" | safe_sha256sum -c - >/dev/null 2>&1; then
	fatal "Tarball checksum validation failed. Stopping netdata installation and leaving tarball in ${TMPDIR}"
fi
run tar -xf netdata-latest.tar.gz
rm -rf netdata-latest.tar.gz >/dev/null 2>&1
cd netdata-* || fatal "Cannot cd to netdata source tree"

# ---------------------------------------------------------------------------------------------------------------------
# install netdata from source

if [ -x netdata-installer.sh ]; then
	progress "Installing netdata..."
	run ${sudo} ./netdata-installer.sh ${NETDATA_UPDATES} ${NETDATA_INSTALLER_OPTIONS} "${@}" || fatal "netdata-installer.sh exited with error"
	if [ -d "${TMPDIR}" ] && [ ! "${TMPDIR}" = "/" ]; then
		run ${sudo} rm -rf "${TMPDIR}" >/dev/null 2>&1
	fi
else
	fatal "Cannot install netdata from source (the source directory does not include netdata-installer.sh). Leaving all files in ${TMPDIR}"
fi
admin@GT-AC5300:/jffs/tmp#

**Comment by BH1NBN** [comment]
> Ok, i understand you are not very familiar with the shell, no worries.
> Let's try to run the following commands in sequence one by one, copy and paste them on your shell
> 
> 1. `curl -Ss https://my-netdata.io/kickstart-static64.sh > /tmp/kickstart-static64.sh` or if this fails, try `wget -O /tmp/kickstart-static64.sh https://my-netdata.io/kickstart-static64.sh`
> 
> If both of the above command fail, paste the errors here and i 'll see for another alternative based on your busybox environment
> 
> 1. `chmod +x /tmp/kickstart-static64.sh`
> 2. `/tmp/kickstart-static64.sh --dont-wait`
> 
> Paste the results here once you 're done.

I feel that the situation is not good.

admin@GT-AC5300:/jffs/tmp# curl -Ss https://my-netdata.io/kickstart-static64.sh > /tmp/kickstart-static64.sh
Terminated

admin@GT-AC5300:/jffs/tmp# wget -O /tmp/kickstart-static64.sh https://my-netdata.io/kickstart-static64.sh
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2019-09-11 22:32:57--  https://my-netdata.io/kickstart-static64.sh
Resolving my-netdata.io... 104.28.3.248, 104.28.2.248, 2606:4700:30::681c:3f8, ...
Connecting to my-netdata.io|104.28.3.248|:443... connected.
ERROR: cannot verify my-netdata.io's certificate, issued by 'CN=CloudFlare Inc ECC CA-2,O=CloudFlare\\, Inc.,L=San Francisco,ST=CA,C=US':
  Unable to locally verify the issuer's authority.
To connect to my-netdata.io insecurely, use `--no-check-certificate'.
admin@GT-AC5300:/jffs/tmp#

**Comment by paulkatsoulakis** [comment]
No worries, try again step 1 with the following command this time:

`wget --no-check-certificate -O /tmp/kickstart-static64.sh https://my-netdata.io/kickstart-static64.sh`

if that works and `ls -l /tmp/kickstart-static64.sh` shows you the file, then execute steps 2 and 3

**Comment by BH1NBN** [comment]
An exception occurs when 1, 2, and 3 have passed the 4 command.

admin@GT-AC5300:/tmp/home/root# wget --no-check-certificate -O /tmp/kickstart-static64.sh https://my-netdata.io/kickstart-static64.sh
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2019-09-11 22:41:28--  https://my-netdata.io/kickstart-static64.sh
Resolving my-netdata.io... 104.28.2.248, 104.28.3.248, 2606:4700:30::681c:3f8, ...
Connecting to my-netdata.io|104.28.2.248|:443... connected.
WARNING: cannot verify my-netdata.io's certificate, issued by 'CN=CloudFlare Inc ECC CA-2,O=CloudFlare\\, Inc.,L=San Francisco,ST=CA,C=US':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: '/tmp/kickstart-static64.sh'

/tmp/kickstart-static64.sh                                       [ <=>                                                                                                                                        ]   6.41K  --.-KB/s    in 0s      

2019-09-11 22:41:29 (20.2 MB/s) - '/tmp/kickstart-static64.sh' saved [6564]


admin@GT-AC5300:/tmp# ls -l /tmp/kickstart-static64.sh
-rw-rw-rw-    1 admin    root          6564 Sep 11 22:41 /tmp/kickstart-static64.sh
admin@GT-AC5300:/tmp# 

admin@GT-AC5300:/tmp# chmod +x /tmp/kickstart-static64.sh

admin@GT-AC5300:/tmp# /tmp/kickstart-static64.sh --dont-wait
/tmp/kickstart-static64.sh: line 159: id: not found
[: bad number
 ABORTED  Static binary versions of netdata are available only for 64bit Intel/AMD CPUs (x86_64), but yours is: aarch64. 

admin@GT-AC5300:/tmp#

**Comment by paulkatsoulakis** [comment]
oh, that's an aarch64, i see. 
Let me think about it and i 'll get back with more feedback

**Comment by BH1NBN** [comment]
> oh, that's an aarch64, i see.
> Let me think about it and i 'll get back with more feedback

Thank you for your answers and powerful help! Due to country problems, I am already late at night. 23:00 There is still a lot of work tomorrow, I have to fall asleep! If I can communicate with you tomorrow night! You can also leave a message directly, I have time to reply with you in time!
