### ISSUE TITLE
RRDSET: chart name 'XXX' on host 'XXX' already exists.

### ISSUE THREAD

**Issue by HolgerHees** [netdata/netdata#6819]
Hello,

since version 1.16.0 I'm getting ~800 messages like 

RRDSET: chart name 'apps.sockets' on host 'XXX' already exists.

per day. My hope was that this will be solved with version 1.17.0 but it is still there.

What exactly does this mean and how can I fix this error message.

I'm running netdata on opensuse leap 15.0 since a while and I have the feeling that with every version I get more error messages. I have an automatic alerting system which informs me about any error or warning on all log files of my server. But currently I have to exclude netdata from this, which is not a good solution.

BTW: If you are interested to know how this works. Here you can find the whole setup.

[https://github.com/HolgerHees/smartserver](https://github.com/HolgerHees/smartserver)

best

**Comment by mfundul** [comment]
After some research this looks like it's related to PR #6304 and specifically [this](https://github.com/netdata/netdata/blob/f0ea1c0b390a3b10a4ed5b143bf618b4e619b0fa/database/rrdset.c#L515) line. This was also merged after v1.15 and before v1.16.0 was released. What do you think @vlvkobal ?

**Comment by mfundul** [comment]
@HolgerHees what `memory mode` are you using in your `netdata.conf`?

**Comment by HolgerHees** [comment]
@mfundul i'm not specifying any `memory mode` in my `netdata.conf`

so I guess it will be the default mode `save`

**Comment by ilyam8** [comment]
@HolgerHees 

could you provide logs?

**Comment by HolgerHees** [comment]
Hi,

today I got

```
Sep 16 11:23:55 marvin netdata[23709]: read failed: end of file
Sep 16 11:23:55 marvin netdata[23709]: '/usr/lib/netdata/plugins.d/apps.plugin' (pid 8427) disconnected after 964867 successful data collections (ENDs).
Sep 16 11:23:56 marvin netdata[23709]: connected to '/usr/lib/netdata/plugins.d/apps.plugin' running on pid 5680
Sep 16 11:23:57 marvin netdata[23709]: RRDSET: chart name 'netdata.apps_cpu' on host 'marvin' already exists.
Sep 16 11:23:57 marvin netdata[23709]: RRDSET: chart name 'netdata.apps_sizes' on host 'marvin' already exists.
Sep 16 11:23:57 marvin netdata[23709]: RRDSET: chart name 'netdata.apps_fix' on host 'marvin' already exists.
Sep 16 11:23:57 marvin netdata[23709]: RRDSET: chart name 'netdata.apps_children_fix' on host 'marvin' already exists.
Sep 16 11:23:57 marvin netdata[23709]: RRDSET: chart name 'apps.cpu' on host 'marvin' already exists.
Sep 16 11:23:57 marvin netdata[23709]: RRDSET: chart name 'apps.mem' on host 'marvin' already exists.
Sep 16 11:23:57 marvin netdata[23709]: RRDSET: chart name 'apps.vmem' on host 'marvin' already exists.
Sep 16 11:23:57 marvin netdata[23709]: RRDSET: chart name 'apps.threads' on host 'marvin' already exists.
```

followed by 100 more messages like RRDSET:...

but I think the first 3 lines are not the reason, because later I got similar messages without the mentioned 3 lines.

`Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.cpu' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.mem' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.vmem' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.threads' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.processes' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.uptime' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.uptime_min' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.uptime_avg' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.uptime_max' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.cpu_user' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.cpu_system' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.swap' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.major_faults' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.minor_faults' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.preads' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.pwrites' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.lreads' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.lwrites' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.files' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.sockets' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'users.pipes' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.cpu' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.mem' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.vmem' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.threads' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.processes' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.uptime' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.uptime_min' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.uptime_avg' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.uptime_max' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.cpu_user' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.cpu_system' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.swap' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.major_faults' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.minor_faults' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.preads' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.pwrites' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.lreads' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.lwrites' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.files' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.sockets' on host 'marvin' already exists.
Sep 16 12:58:47 marvin netdata[23709]: RRDSET: chart name 'groups.pipes' on host 'marvin' already exists.
`

if you want I can also provide a full log file from the whole day.

**Comment by vlvkobal** [comment]
What do you have in your logs before `Sep 16 11:23:55 marvin netdata[23709]: read failed: end of file`?

How often do you have `read failed` in the logs?

**Comment by vlvkobal** [comment]
Yes, It's a good idea to provide the full log file.

**Comment by HolgerHees** [comment]
before this line I have nothing similar. It was working for hours with hundred of log messages like

```
Sep 16 11:23:01 marvin netdata[23709]: 9885: 23731 '[localhost]:58190' 'DISCONNECTED'
Sep 16 11:23:01 marvin netdata[23709]: 9885: 23731 '[localhost]:58190' 'DATA' (sent/all = 124/124 bytes -0%, prep/sent/total = 0.03/0.13/0.16 ms) 200 '/api/v1/alarms'
```

I'm getting errors like that since the beginning I'm using netdata with version 1.14.0. I created also a bug report for that.

https://github.com/netdata/netdata/issues/6038

btw. how can I attach a log file. I don't want to post the full file here.

**Comment by ilyam8** [comment]
You can attach it but you need to `zip` it first. Or just use [pastebin](https://pastebin.com)

**Comment by HolgerHees** [comment]
[netdata.zip](https://github.com/netdata/netdata/files/3616064/netdata.zip)

**Comment by vlvkobal** [comment]
You shouldn't have
```
'CONNECTED'
'DISCONNECTED'
'DATA' (sent/all = 124/124 bytes -0%, prep/sent/total = 0.03/0.58/0.61 ms) 200 '/api/v1/alarms'
```
messages in the error log. They should be written to the access log. Check the `access log = /var/log/netdata/access.log` option in the `netdata.conf`.

**Comment by vlvkobal** [comment]
As for the `RRDSET: chart name 'netdata.apps_cpu' on host 'marvin' already exists` messages, they are informative, not errors. But the reason they appear in the error log is that `apps.plugin` has quitted and restarted by the Netdata daemon. The question is, what is happening to `apps.plugin`, why it terminates. Unfortunately, I can't figure it out from the logs.

**Comment by vlvkobal** [comment]
Please run the `sudo /usr/libexec/netdata/plugins.d/apps.plugin debug` command in a separate terminal and provide it's output when it crashes

**Comment by HolgerHees** [comment]
sorry, this was a misunderstanding. I provided a merged logfile of info and error messages.

now I attached the error logfile and the logfile of  `sudo /usr/libexec/netdata/plugins.d/apps.plugin debug `

[netdata.zip](https://github.com/netdata/netdata/files/3616676/netdata.zip)

**Comment by vlvkobal** [comment]
You terminated the plugin with Ctrl + C, but you should leave it running until it has died. I need the last messages of its output when it crashes. And it looks like you forgot to add the `debug` option.

**Comment by HolgerHees** [comment]
ok. I will run it today evening and will inform you when it crashed again.

**Comment by HolgerHees** [comment]
so, i took a while, because I was using a rpm package from opensuse and I had to install and compile it by my self to enable the debug flag. But now I got it running with debug enabled and I have now a 3GB log file.

Here I attached only a snipped with the last 10000 lines. If you need more let me know.

[apps.plugins.last10000.zip](https://github.com/netdata/netdata/files/3619459/apps.plugins.last10000.zip)

**Comment by vlvkobal** [comment]
I've looked at the log. There are no problems. The plugin didn't crash, it was a planned restart.

BTW, @ktsaou, why did you make the apps plugin restarting every 4 hours?

**Comment by vlvkobal** [comment]
I think the messaged are valid. We can't suppress them for apps.plugin only. So, the question is, do we need the ERROR log level for them? It is the scope of #6038.

**Comment by ilyam8** [comment]
it doesnt looks like an error level to me

**Comment by cakrit** [comment]
It's not a matter of log level IMHO, but of messages that shouldn't be written at all in the case of a plugin restart.
Based on the OP, those messages didn't appear before v1.16. So what changed now? 
Also, perhaps we can have a check to ensure we don't show them when a plugin has restarted (e.g. with a check on whether we had gaps in collection)?

**Comment by vlvkobal** [comment]
> those messages didn't appear before v1.16. So what changed now?

We had a bug with chart names in streaming and it was fixed. Now we get these messages on any chart redefinition.

> perhaps we can have a check to ensure we don't show them when a plugin has restarted

To make it unambiguous we need to change the external plugins API.

> e.g. with a check on whether we had gaps in collection

Personally, I strongly against such ambiguous "magic".

**Comment by cakrit** [comment]
Sure, suggest something specific it and plan for the fix. As it is, this is a bug.

**Comment by ilyam8** [comment]
> perhaps we can have a check to ensure we don't show them when a plugin has restarted

It wont work in general. This should be an error and even a warning.

Define new and update chart (add new dimension in runtime) use same instruction - [`CHART`](https://docs.netdata.cloud/collectors/plugins.d/#chart)

So it is a valid operation according external plugin api.

**Comment by HolgerHees** [comment]
thanks a lot :-) will try it out soon.
