### ISSUE TITLE
[health] Log standard message when executing health_script

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#6822]
##### Feature idea summary

When health triggers the `health script`, there is no log. From [the health.c](https://github.com/netdata/netdata/blob/master/health/health.c#L293-L303) source, there is only a debug message. 

I'd like either a more standard (not debug) notification message, or a whole separate debug file health.log. This request is motived by : 
- it creates new process, which is a little bit unusual for netdata core part
- it would have helped diagnose issues with `delay` option (like #2952), `repeating` alerts not being cleared (#6581), and a requests from users asking if I'm sure netdata did trigger the alerting script.
- I've not tested extensively, but it seems the alerting process is created by a new process, but the `health` thread is still waiting for its output before continuing. A stall alerting script may (will ?) block the health alerting thread.

Maybe adding thread pool or "max execution time" for the scripts would be ok, but that would increase complexity in the current codebase. Maybe libuv would help if the move is done...

##### Expected behavior

A more friendly message when executing the script health check (`health.c :: health_alarm_execute`), like: 
> Execution of %script took %ms (from %startts to %endts) and returned %rc. Output sent to file %outputlogfile

And / or in a dedicated log file, like health.log

**Comment by thiagoftsm** [comment]
Hi @Saruspete ,

In normal situation when this script is executed, netdata sends for the channels  specified by the users the message, only to confirm whether I understood your request, are you talking for us to bring messages only in fail cases? Or are you talking about to store everything?

**Comment by Saruspete** [comment]
Hi @thiagoftsm  funny you replied, I started checking on this today :)

for the logs, I was planning to log (i'll check on my prod for how chatty this list is, and remove them if needed)
- Notification of script execution (time taken and return code) 
- Notification of script inhibition, with the `delay` element (shouldn't be too chatty, thanks to the hysteresis values
- repeated events (`default repeat (critical|warning)`)

So, I've started working on it, and found the names are quite unclean: The filename (`/var/lib/netdata/health/`) is stored as `host->health_log_filename` while it should have been something like  `health_db_filename` (and same for `health_log_fp` et al.)

So I plan to :

1. add fields `health_alarm_log_{fp,filename}`  and move current usage from `health_log_*` to these `health_alarm_log_*` or `health_db_filename`
2. reuse these `health_log_*` to implement real health log in `/var/log/netdata/health.log` for event logging, specified herebefore

What do you think about this renaming ?

**Comment by thiagoftsm** [comment]
Hi @Saruspete,

Let me try to help you for we move this in front. :)

I believe the name `health_log_filename` was selected to avoid confusion with our database files, I agree that it looks like more a database table than other thing, be free to change and when you create the PR we can check the opinion from others.

About the plan:
1 - It makes sense to put the new fields in the files and structure.
2 - You are 100% correct about this too.

I will only ask something for you in this beginning, please, keep in your mind that due the fact users receive the alarms on other channel, it is possible that they do not want to have a specific log for it, so let us create an option for the users to disable this kind of log. Your idea is good, but people can have an opinion different, so it is good to give an option for them to disable.

**Comment by Saruspete** [comment]
Hi @thiagoftsm 

Sorry for the delay, just worked on it today.

I'll be testing this patch on my prod. While I have a fair amount of servers, they all have the same architecture, so it would be nice to cover more states like streaming, more filtering, etc...

Thanks for your insights.

**Comment by thiagoftsm** [comment]
All right @Saruspete !

I saw that you already created a PR for it, I will review it late today.

thank you very much!

**Comment by MrZammler** [comment]
Closing this since the linked PR was closed.
