### ISSUE TITLE
New nut.chart.py - replaces charts.d.plugin/nut.chart.sh

### ISSUE THREAD

**Issue by utdrmac** [netdata/netdata#6827]
[nut.chart.py.zip](https://github.com/netdata/netdata/files/3603180/nut.chart.py.zip)

(github would not let me upload the .py file so I had to compress it.)

Forking this entire project just to submit 1 file seemed extremely wasteful and unnecessary, so I'm submitting the new script/plugin/collector via this method.

This collector is a (hopefully) improved rewrite of the aged charts.d.plugin/nut/nut.chart.sh which has various issues regarding timeout and zombie processes. In a way, this resolves #6033 

This collector uses the native python classes for connecting to a service over TCP/IP and issuing commands to upsd to get stats on connected UPSes. Unfortunately, I do not have multiple UPSes to test multi-use functionality. Hopefully someone who does can try this script out and validate it works for multiple UPSes.

Here's a screenshot from my system, using the plugin. It detected the name of my UPS, tripplite, and displays all of the same information that the older script did.

![Screen Shot 2019-09-11 at 7 14 32 PM](https://user-images.githubusercontent.com/4413670/64744208-80be1780-d4c8-11e9-91b8-26ef9e1890d7.png)

**Comment by ilyam8** [comment]
> Forking this entire project just to submit 1 file seemed extremely wasteful and unnecessary, so I'm submitting the new script/plugin/collector via this method.

@utdrmac to have your plugin merged someone need to make a PR anyway ^^

I would like you to do it since it is your work. If for some reason you dont want to do it i could do it.

**Comment by utdrmac** [comment]
Forking entire projects just to change 1 line, or just add one file is my #1 complaint about github. It's such a waste. I'll do it. bleh.

**Comment by ilyam8** [comment]
Actually it is not 1 file. See 

> https://docs.netdata.cloud/collectors/python.d.plugin/#pull-request-checklist-for-python-plugins

**Comment by Ferroin** [comment]
@ilyam8 Actually, that checklist is out of date.  Opening a PR as we speak to update it to reflect the current structure of the repository.
