### ISSUE TITLE
SPIKE Libraries to change sockets and webserver

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6831]
##### Feature idea summary
Considering the necessity that we have to migrate to Microsoft and to create conditions to have unit tests in the web server, it is necessary to migrate the connection pool from epool for something more generic like libuv or something more complete like libwebsockets or libh2o, these last two libraries have the libuv as their basis.

This SPIKE will map all the functions and necessaries steps to do the migration.

@mfundul considering the issue that you created, you gave me the idea to write this spike as a documentation that you help not only you, but all future contributors to give new features for our webserver.
##### Expected behavior
To have the road map to migrate the web server and our libsockets to any operating system.

**Comment by thiagoftsm** [comment]
| Web server Action | Netdata File | Netdata Function | Lib H2O | Lib Websocket |
| --------------------------- | ----------------- | ------------------------- | ------------ | --------------------- |
| Create Socket | web/server/web_server.c | api_listen_sockets_setup | - | - |
| Create Socket | libnetdata/socket/socket.c | listen_sockets_setup | - | - |
| Create Socket | libnetdata/socket/socket.c |   bind_to_this | uv_ipX_addr, uv_tcp_bind, uv_listen | lws_create_context, lws_create_vhost |
| Add socket to pool | web/server/static/static-threaded.c | socket_listen_main_static_threaded_worker | - | - |

**Comment by thiagoftsm** [comment]
To finish this SPIKE I decided to run a simple benchmark with both servers written in the previous post to compare the results, I wrote a shell script that executes a simple request for the index page in a TLS tunnel, but it does this in a loop, initially I set only 40 requests to test and I got the following results:

### LibH2O
```
real    0m2.047s
user    0m0.376s
sys     0m0.104s
```

### Libwebsockets
```
real    0m0.581s
user    0m0.394s
sys     0m0.128s

```

**Comment by thiagoftsm** [comment]
After to get the results from the previous tests, I decided to do more a benchmark, this time I decided to do download of my `netdata.conf` using both Netdata and the simple web server linked with libwebsockets, this time I decided to go directly in the loop with 10000 requests:

### LIbwebsockets
```
real    2m1.982s
user    1m25.947s
sys     0m27.800s
```

### Netdata
```
real    2m40.550s
user    1m37.156s
sys     0m34.365s
```

The fact that Netdata is slower than libwebsockets in this specific example it is hoped, because Netdata is a big code, while the test code has only 421 lines of code, what really matter here is the fact that Netdata was more or less 38 seconds slower only.

**Comment by ilyam8** [comment]
> a simple benchmark with both servers written in the previous post to compare the results, I wrote a shell script that executes a simple request for the index page in a TLS tunnel, but it does this in a loop, initially I set only 40 requests

> LibH2O
> real    0m2.047s
user    0m0.376s
sys     0m0.104s


It looks strange to me, could you share your benchmark code? 
cc @underhood 

libh2o should be very fast

https://h2o.examp1e.net/assets/staticfile612-nginx1910-h2o170.png

**Comment by thiagoftsm** [comment]
I agree Ilya, I will talk with him.
This is not a real web server, it is only a simple test, libh20 does not have a shared library by default and its binary was 9 times bigger than libwebsockets binary, this is something to consider for sure.

**Comment by thiagoftsm** [comment]
I did another benchmark, this time I used the h2o web server compiled and I adjust it to use SSL v1.2. 
I again requested 10000 times the file `netdata.conf` that I use in a specific computer, and I got the following results:

### H2O webserver
```
real    2m21.183s
user    1m35.662s
sys     0m29.541s
```

As we can see H2O is faster than Netdata.
So the initial benchmark had problem related to original code linked with H2O that brings a problem related with their examples, because they were the basis for I build the software here.

**Comment by gpapamathND** [comment]
Final decision what library to use is pending. @thiagoftsm please define the final result of the investigation

**Comment by underhood** [comment]
What is the time-frame for decision here? I would say this is not decision to be taken lightly as it will possibly go with us long time.

@thiagoftsm can you share your benches as @ilyam8 mentioned?

Maybe make a git repo with them. Don't worry much about code quality here. Point is that other people can take a look as well potentially spotting something.

**Comment by thiagoftsm** [comment]
Hi @underhood ,

We are finishing the SPIKE today, but we can continue working on this during the next 15 days, because I am not plaining to bring this for Netdata before this interval, I have other things to do in the next two weeks.

Initially I ran in sequence, but I will publish more benchmarks in the sequence that was done in concurrency. Until this POST everything was done with one TCP connection per request, I did not use keep-alive any time.

**Comment by thiagoftsm** [comment]
I am bringing another benchmark done with libwebsockets, Netdata and H2O. In this benchmark, I added an '&' at the end of the `curl ` command line to put some process to run in parallel, I let the script to put 240 process to run before to sleep 1 second and run more 240
 process. Doing these requests I got the following results for each webserver:

### Libwebsockets
``` 
real    1m15.987s
user    2m17.859s
sys     0m36.822s
``` 

### Netdata
```
real    1m6.418s
user    1m51.946s
sys     0m36.715s
```

### H2O
```
real    1m29.879s
user    2m21.055s
sys     0m35.375s

**Comment by thiagoftsm** [comment]
After to run some tests with curl and bash script, I decided to use specific tools to do benchmarks, the first test was done with Apache HTTP server benchmarking tool(`ab`) and I got the following results:

### Libwebsockets
```
bash-5.0$ ab -t 100 -n 10000 -c 397 https://localhost:7891/netdata.conf
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            7891
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256
Server Temp Key:        X25519 253 bits
TLS Server Name:        localhost

Document Path:          /netdata.conf
Document Length:        251809 bytes

Concurrency Level:      397
Time taken for tests:   15.871 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      2522490000 bytes
HTML transferred:       2518090000 bytes
Requests per second:    630.09 [#/sec] (mean)
Time per request:       630.067 [ms] (mean)
Time per request:       1.587 [ms] (mean, across all concurrent requests)
Transfer rate:          155214.97 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1  331 309.0    251    3242
Processing:    16  290  93.3    325     429
Waiting:        0  154  61.0    179     274
Total:         28  622 320.7    581    3550

Percentage of the requests served within a certain time (ms)
  50%    581
  66%    595
  75%    604
  80%    610
  90%    647
  95%   1482
  98%   1605
  99%   1644
 100%   3550 (longest request)
```

### Netdata
```
bash-5.0$ ab -t 100 -n 10000 -c 397 http://localhost:20000/netdata.conf
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 9840 requests completed
```

### H20
```
bash-5.0$ ab -t 100 -n 10000 -c 397 https://localhost:8081/netdata.conf
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        h2o/2.3.0-DEV
Server Hostname:        localhost
Server Port:            8081
SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256
Server Temp Key:        X25519 253 bits
TLS Server Name:        localhost

Document Path:          /netdata.conf
Document Length:        251809 bytes

Concurrency Level:      397
Time taken for tests:   11.072 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      2520630000 bytes
HTML transferred:       2518090000 bytes
Requests per second:    903.17 [#/sec] (mean)
Time per request:       439.561 [ms] (mean)
Time per request:       1.107 [ms] (mean, across all concurrent requests)
Transfer rate:          222321.24 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        3   29  44.9     20     322
Processing:    45  409  45.6    412     509
Waiting:        0    7   9.7      4      97
Total:         48  438  60.6    431     815

Percentage of the requests served within a certain time (ms)
  50%    431
  66%    436
  75%    442
  80%    448
  90%    477
  95%    492
  98%    651
  99%    732
 100%    815 (longest request)
```

I will call attention here that the fact I am using the number `397` in the concurrency option, because with a big number it is necessary to change the source code of libwebsockets to  increase the option `backlog` of the function `listen()`.
Another thing to call attention here it is the fact that Netdata failed in this benchmark.

**Comment by underhood** [comment]
Just a quick comment during my lunch break:

when i was benchmarking my mempool PR I also noticed 2 things:
1. sometimes Netdata becomes too slow and unresponsive (this might be same what you see with ApacheBench although I thested with httperf) -> therefore there seems to be something that makes netdata webserver upset when too many parallel requests are running.
2. keep-alive seems not to be working really well currently (although i have to test again to be sure fault is not actually at httperf side)

First I thought it is my PR breaking things but then i compiled Master and saw the same thing.
I am glad I saw someone else notice this problem as well.
I didn't want to report becuase I was not yet sure it's not my VM breaking things etc. Anyhow the eye of Sauron has noticed already.

Additionally i noticed netdata seems to not close all threads properly at least some times - not confirmed yet

**Comment by thiagoftsm** [comment]
Finally I am bringing a last benchmark from `wrk`, this was a tool presented to me by Ilya(Thank you very much @ilyam8 !).

### Libwebsockets
```
bash-5.0$ wrk -t4 -c397 -d5m https://localhost:7891/netdata.conf
Running 5m test @ https://localhost:7891/netdata.conf
  4 threads and 397 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   291.82ms   20.10ms 561.49ms   80.26%
    Req/Sec   340.76    102.35   590.00     66.62%
  406455 requests in 5.00m, 95.49GB read
Requests/sec:   1354.61
Transfer/sec:    325.87MB
```

### Netdata
```
bash-5.0$ wrk -t4 -c397 -d5m https://localhost:19999/netdata.conf
Running 5m test @ https://localhost:19999/netdata.conf
  4 threads and 397 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.38s   412.16ms   2.00s    62.82%
    Req/Sec    33.73     41.18   353.00     86.24%
  16541 requests in 5.00m, 3.76GB read
  Socket errors: connect 38, read 68, write 0, timeout 9292
Requests/sec:     55.13
Transfer/sec:     12.85MB
```

### H20
```
bash-5.0$ wrk -t4 -c397 -d5m https://localhost:8081/netdata.conf
Running 5m test @ https://localhost:8081/netdata.conf
  4 threads and 397 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    65.38ms   41.18ms   1.06s    72.54%
    Req/Sec     1.54k   466.08     3.51k    67.06%
  1829727 requests in 5.00m, 429.58GB read
Requests/sec:   6097.37
Transfer/sec:      1.43GB
```

**Comment by thiagoftsm** [comment]
In this post I am bringing the simple version of the files used to test the libraries.

[files.zip](https://github.com/netdata/netdata/files/3657263/files.zip)

**Comment by thiagoftsm** [comment]
The benchmarks with H2O server proof that H2O  has an awesome basis, but the fact that it is not simple to port it to Microsoft, and no less important the fact that it only has static library by default will increase Netdata binary size around 60%. Another problem  is the fact that H2O examples gave me an initial wrong impression from the library,  so it is necessary to go deep in the web server code to understand better how to use the library. I am not saying it is a problem to study H2O code, but the fact  that we had a small example in  the source code that is almost 25 times slower than the WebServer is something preety bad.
Libwebsockets  does not have the same performance that H2O had, on the other hand it was prepared to run in different Operate Systems, it also has a better documentation and it examples work fine.
Considering the results and the fact that we wanna improve Netdata quality, I think to move with any library will move us in the correct direction, but the fact that H2O static library when linked raises the binary size a lot and it is necessay to do explicit calling  for libuv while libwebsockets simplified everything to us, I think libwebsockets will improve Netdata and it will simplify the transaction to other Operate Systems.

**Comment by cakrit** [comment]
Apologies for noticing just now, but the benchmark was incorrect. `netdata.conf` is a static file for the other two, but not for netdata, which generates the output. Please repeat them with something truly static, like  `dashboard.js`. The difference is enormous, as you can see below:
```
[christopher@chris-msi netdata]$ wrk -t4 -c397 -d5s http://localhost:19999/netdata.conf
Running 5s test @ http://localhost:19999/netdata.conf
  4 threads and 397 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   962.74ms  423.82ms   1.94s    60.81%
    Req/Sec   110.12    111.51   570.00     85.37%
  1879 requests in 5.03s, 1.02GB read
  Socket errors: connect 0, read 0, write 0, timeout 6
Requests/sec:    373.59
Transfer/sec:    207.80MB

[christopher@chris-msi netdata]$ wrk -t4 -c397 -d5s http://localhost:19999/dashboard.js
Running 5s test @ http://localhost:19999/dashboard.js
  4 threads and 397 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.88ms   10.45ms  63.96ms   64.11%
    Req/Sec     3.07k   294.27     4.32k    76.56%
  60991 requests in 5.05s, 22.01GB read
Requests/sec:  12073.95
Transfer/sec:      4.36GB
```

I'd also like to see cpu and memory netdata charts during the execution of the benchmark. 

Performance and efficiency are crucial for us, we won't use a library that will degrade them.

**Comment by thiagoftsm** [comment]
No problem, I am glad you found the problem and I am able now to generate the correct results, I already could see in the first round of tests that we had an improvement with Netdata results as expected.
I decided do not create other comments with the newest results, I am updating the previous results of request benchmark where  I am using ```dashboard.js``` for the current day, but I saved the old results with ``` netdata.conf```, when I finish the update with the access benchmark, I will generate a report with the cpu and memory benchmark.

**Comment by thiagoftsm** [comment]
I used Netdata with dbengine set as memory mode to measure CPU usage, for sure this would not be good for Netdata, because I am using itself to measure its performance, but I decided to move in front anyway, because I trust the results.

### Netdata

![netdata_cpu](https://user-images.githubusercontent.com/49162938/65838911-a6845280-e2f7-11e9-8ba4-e4d8154508cb.png)

### Libwebsockets

![websockets_cpu](https://user-images.githubusercontent.com/49162938/65838922-b56b0500-e2f7-11e9-8991-7abc86fd0c09.png)

### H2O

![h2o_cpu](https://user-images.githubusercontent.com/49162938/65838930-cddb1f80-e2f7-11e9-821a-6cba9c7d7a9c.png)

**Comment by thiagoftsm** [comment]
The final benchmark was done again with `wrk` doing requests for all three webservers, here we are measuring the memory usage of each webserver.

### Netdata

![netdata_mem](https://user-images.githubusercontent.com/49162938/65839065-59a17b80-e2f9-11e9-800a-ac5be5bbe44e.png)

### Websockets

![websockets_mem](https://user-images.githubusercontent.com/49162938/65839075-632ae380-e2f9-11e9-984b-23a31e654336.png)

### H2O

![h2o_mem](https://user-images.githubusercontent.com/49162938/65839083-750c8680-e2f9-11e9-9b6b-02154eb655b3.png)

The memory management of both libwebsockets and H2O in this case was done by libuv.

**Comment by thiagoftsm** [comment]
Considering the latest results, I think we cannot discard the possibility to bring the general idea from both libraries to improve Netdata core instead to bring libraries, but for sure I keep my vision that libwebsockets is the best option, mainly considering the fact that h2o failed to compile with `mingw`.

**Comment by cakrit** [comment]
> Considering the latest results, I think we cannot discard the possibility to bring the general idea from both libraries to improve Netdata core instead to bring libraries, but for sure I keep my vision that libwebsockets is the best option, mainly considering the fact that h2o failed to compile with `mingw`.

We can't use those libraries at all. Taking 4 CPU cores just to serve the web requests is a big no. The memory benchmark shows horrible performance too. We need to remember that netdata is doing a lot of other things as well, not just serving that static content. You'd need to set it to memory mode RAM and disable all collectors to have really comparable results. 

So I say we forget about what those libraries do and incrementally improve netdata.

**Comment by cakrit** [comment]
Actually, I believe we could easily take this one step further. We canadd a blog post and a link to that post  from `docs/Performance.md`, to showcase how performant netdata really is. 

With only the `apps` plugin enabled and memory mode RAM with the shortest possible history, we can run the benchmarks again and put the results in a blog post. @joelhans can help with this, let's just have another, fair run for netdata with the exact same test. The tests for the other libraries don't need to be repeated.

**Comment by thiagoftsm** [comment]
We can use their ideas instead the library, mainly because H2O has URL parser more concentrated and it does not destroy the original request .
@underhood is also working in something that can improve our web server, our buffer management is something that did not allow Netdata be better in this benchmark.
@joelhans any doubt you have let me know.

**Comment by cakrit** [comment]
Joel will just wait for the updated performance metrics and charts after you repeat the test on netdata,
> With only the apps plugin enabled and memory mode RAM with the shortest possible history
Update the ticket after the test and he can prepare the blog post.

**Comment by underhood** [comment]
@cakrit I do not agree that in this tests High CPU usage is a bad thing. If we do a max load test if server is able to finish quickly by better using availible resources it is better. Of course we can then limit the usage in netdata so it doesn't allow all cores to be used. But quicker it is able to process the request the better. Remember these tests do not simulate normal usage as netdata is used but represent maximum load we are able to generate.

**Comment by underhood** [comment]
@cakrit I also have to investigate the netdata thing where webserver stops responding when under high parallel load. Something i noticed and @thiagoftsm seen something similar in the tests. I will try to find as much as possible but y'all know my situation until 1st Jan

**Comment by underhood** [comment]
@cakrit Regarding 

> So I say we forget about what those libraries do and incrementally improve netdata.

That might be a way to go but only as long as we want to support just HTTP 1.1, but there is HTTP/2 already, websockets and HTTP/3 on the way. Therefore using libs is much more future proof (as features in daemon grow) implementing all that will be way too much work IMHO to be done by Netdata (following all the standards, testing with all possible browsers/configs, security matters) and is best left to people who want to develop web servers - not what netdata wants.

**Comment by Ferroin** [comment]
> So if server is able to finish X requests quicker and generates higher CPU load -> GOOD, if it generates higher CPU load but takes same time for those X requests ->BAD

I'd argue that this assessment only holds true if the ratio of time to CPU load is the same or lower for the faster completion.  If we can finish some set number of requests 20% faster, but cause 50% more CPU load while doing so, we've not improved, we've actually gotten worse.

**Comment by underhood** [comment]
@Ferroin
Yep naturally, point was to say that lib being able to use 100% of each core to max is not necessarily bad thing.
I can add bazilionth digit of Pi calculation then add some sleeps and mutexes i between everywhere so then CPU load will be low while actually taking much more CPU cycles per request and more time.

**Comment by cakrit** [comment]
I looked at the response times and requests/sec after @underhood 's  comments and we're comparing apples with oranges again. 

The reason the CPU usage is so low and the response time and throughput so high compared to the other two is that the following settings were left with the default values:

```
[web]
    web server threads = 4
    web server max sockets = 512
```
So we should repeat the tests with different values in these two, to get comparable throughput/latency and then we can look again at the CPU %. 

Of course the reason we started investigating the other libraries was to not have to do everything ourselves. Let's do a proper benchmark and, if it's the performance hit is acceptable (if it even exists), by all means we go with one of the options. 

There is a huge difference between netdata and any normal web server. netdata should not use all available resources, except perhaps when running containerized, with user-set container resource limits. This is a crucial feature and you can see at the [performance doc](https://docs.netdata.cloud/docs/performance/) and the [netdata for IoT doc](https://docs.netdata.cloud/docs/netdata-for-iot/) how important it is to netdata.

**Comment by thiagoftsm** [comment]
I will work on the benchmarks again today, I did not release newest versions of the  benchmark yet, because I began to receive a great number of gaps in some charts when I was using H2O and Apache and I raised the number of requests of the benchmark. After a research and a brief talk with @underhood and Ilya , we arrived in the conclusion that was not a bug, but we had the gaps, due the fact the webservers were not allowing other software to get a slice of time to process.

**Comment by underhood** [comment]
> I looked at the response times and requests/sec after @underhood 's comments and we're comparing apples with oranges again.
> 
> The reason the CPU usage is so low and the response time and throughput so high compared to the other two is that the following settings were left with the default values:
> 
> ```
> [web]
>     web server threads = 4
>     web server max sockets = 512
> ```
> 
> So we should repeat the tests with different values in these two, to get comparable throughput/latency and then we can look again at the CPU %.
> 
> Of course the reason we started investigating the other libraries was to not have to do everything ourselves. Let's do a proper benchmark and, if it's the performance hit is acceptable (if it even exists), by all means we go with one of the options.
> 
> There is a huge difference between netdata and any normal web server. netdata should not use all available resources, except perhaps when running containerized, with user-set container resource limits. This is a crucial feature and you can see at the [performance doc](https://docs.netdata.cloud/docs/performance/) and the [netdata for IoT doc](https://docs.netdata.cloud/docs/netdata-for-iot/) how important it is to netdata.

@cakrit agreed that is why i suggested making a repo with benchmarks so it is more clear what and how it is tested.

@cakrit It is clear that netdata should not use all available resources and that was not my point.

**Comment by thiagoftsm** [comment]
The next group of Benchmarks I am beginning to bring here were done in a different computer, to confirm that the results are not related to hardware, I used the following environment now:

- An Intel I5  with 8GB ram and 4 real processors. This computer has hyper-threading technology.
- This computer has among the servers running: Xorg server 1.20-5, PostgreSQL 11.5, Apache 2.4.41
- I also started a VM with Virtual Box using 2 cores and 512MB of ram
- Both computer and VM runs Slackware Current with kernel 4.19.76 and the latest Netdata and libraries available for the current day.
- With the exception of Apache and Netdata that was running during all time, the other web servers were started when the benchmark began and killed when the benchmark was finished.
- This benchmark was done with the software wrk with 4 threads and 397 concurrency.
- Netdata was running with ```memory mode = ram``` , ```web server threads = 4``` and ```web server max sockets = 512``` 

Firstly I am bringing the CPU results:

### Netdata 
![netdata_cpu_default](https://user-images.githubusercontent.com/49162938/66099982-a5258500-e598-11e9-8bb5-a234fb3b3a99.png)

### Websockets
![websockets_cpu_default](https://user-images.githubusercontent.com/49162938/66099993-b078b080-e598-11e9-8f6c-b85b510bf6ca.png)

### H2O 
![h2o_cpu_default](https://user-images.githubusercontent.com/49162938/66099998-b7072800-e598-11e9-8a83-ec7c2a96bb98.png)

### Apache
![apache_cpu_default](https://user-images.githubusercontent.com/49162938/66100005-c1292680-e598-11e9-9dde-efff1a02a85f.png)

The gaps presented in the charts were due the fact Netdata could not get time from processor every seconds due the high sample of data and number of process/threads opened  by the servers.

**Comment by thiagoftsm** [comment]
I am splitting the results for CPU and Memory to avoid a long comment, now I am bringing the memory results for memory of the benchmark

### Netdata
![netdata_mem_default](https://user-images.githubusercontent.com/49162938/66100225-9a1f2480-e599-11e9-913c-dda80d6f3b11.png)

### WebSockets
![websockets_mem_default](https://user-images.githubusercontent.com/49162938/66100242-ac995e00-e599-11e9-8342-097aee5fe902.png)

### H2O
![h2o_mem_default](https://user-images.githubusercontent.com/49162938/66100245-b1f6a880-e599-11e9-9c20-ffc13d4dc360.png)

### Apache
![apache_mem_default](https://user-images.githubusercontent.com/49162938/66100259-bd49d400-e599-11e9-9eb9-46eb2bec9246.png)

**Comment by thiagoftsm** [comment]
The next Benchmark had the following change in Netdata configuration:

-  ```web server threads = 8```

With the double of threads available we got the following results for CPU:

### Netdata
![netdata_cpu_8_256](https://user-images.githubusercontent.com/49162938/66100786-cfc50d00-e59b-11e9-9d05-d3e86e22b744.png)

### Websockets
![websockets_cpu_8_256](https://user-images.githubusercontent.com/49162938/66100789-d489c100-e59b-11e9-931e-8aeaa76ca2d4.png)

### H2O
![h2o_cpu_8_256](https://user-images.githubusercontent.com/49162938/66100799-de132900-e59b-11e9-8ce5-f8c1ee7f53f9.png)

### Apache
![apache_cpu_8_256](https://user-images.githubusercontent.com/49162938/66100808-e2d7dd00-e59b-11e9-93eb-0bf698235944.png)

**Comment by thiagoftsm** [comment]
To finish the group of 8 threads, I am bringing the memory results:

### Netdata
![netdata_mem_8_256](https://user-images.githubusercontent.com/49162938/66101030-d4d68c00-e59c-11e9-8b6b-3336f697f3a4.png)

### Websockets
![websockets_mem_8_256](https://user-images.githubusercontent.com/49162938/66101039-dc963080-e59c-11e9-8368-34cc6f71fecd.png)

### H2O
![h2o_mem_8_256](https://user-images.githubusercontent.com/49162938/66101058-e324a800-e59c-11e9-8487-7b25aee36a40.png)

### Apache
![apache_mem_8_256](https://user-images.githubusercontent.com/49162938/66101063-e7e95c00-e59c-11e9-9451-65777ad2af21.png)

**Comment by thiagoftsm** [comment]
The final Benchmark of the group had the following change in Netdata configuration:

- ```server max sockets = 1024```

With the double of threads available we got the following results for CPU:

### Netdata
![netdata_cpu_8_1024](https://user-images.githubusercontent.com/49162938/66102536-3e0cce00-e5a2-11e9-99ce-98669c2ef37b.png)

### Websockets
![websockets_cpu_8_1024](https://user-images.githubusercontent.com/49162938/66102545-4238eb80-e5a2-11e9-9e56-dc49a9870941.png)

### H2O
![h2o_cpu_8_1024](https://user-images.githubusercontent.com/49162938/66102553-47963600-e5a2-11e9-9883-ea11d8356724.png)

### Apache
![apache_cpu_8_1024](https://user-images.githubusercontent.com/49162938/66102562-4cf38080-e5a2-11e9-9ba6-9e3b642d5dca.png)

**Comment by thiagoftsm** [comment]
Finally, I am bringing the memory for 1024 sockets:

### Netdata
![netdata_mem_8_1024](https://user-images.githubusercontent.com/49162938/66102599-64326e00-e5a2-11e9-8baa-0fb5639a652e.png)

### Websockets
![websockets_mem_8_1024](https://user-images.githubusercontent.com/49162938/66102607-698fb880-e5a2-11e9-9286-222327f80e71.png)

### H2O
![h2o_mem_8_1024](https://user-images.githubusercontent.com/49162938/66102620-701e3000-e5a2-11e9-84f1-ff032b458b83.png)

### Apache
![apache_mem_8_1024](https://user-images.githubusercontent.com/49162938/66102624-74e2e400-e5a2-11e9-9925-959294a555b4.png)

**Comment by underhood** [comment]
Hi,
@thiagoftsm I do think to be able to interpret the CPU results we absolutely need the time it took to complete the same amount of requests from each webserver. I would imagine something like this:

All web servers were given 1 000 000 requests to handle. Each server was running on 4 threads:

| Server | ***!! Time*** | avg. CPU load |
| ---        | ---       |  --- |
| Netdata | ... | 30% |
| websocket | ... | 200% |

The point I am trying to convey is if for example websockets use 400% CPU but is able to finish 10x quicker it is more effective (uses less resources per request handled). But if we just see CPU time but not time it took to handle all requests we cannot really know.

**Comment by thiagoftsm** [comment]
Hi @underhood ,

I used Netdata chart to show how the processor and memory are working during the time, the average give us a central information that won't express this exactly, for example see the latest chart for websockets, the average will give us a value higher than 72 due the extremes, but for a long time it did not need more than 72Mb.
For I have the exact number of 1M requests, I will  need to use ```ab``` instead ```wrk```.
We used only one file, I will update the description, thanks to remember!

**Comment by cakrit** [comment]
That's not @underhood's point, it's that we need to see the results of the `wrk` to compare latency and throughput. 

Repeating what I said, with emphasis to clarify:
> So we should repeat the tests with different values in these two, **to get comparable throughput/latency** and **then** we can look again at the CPU %.

**Comment by thiagoftsm** [comment]
After to get the results with other benchmark, I decided to freeze the thread values at 2048 and I increased the web server Threads, the following results were got for Netdata.

### 32 Threads
#### CPU
![netdata_cpu_32_2048](https://user-images.githubusercontent.com/49162938/66163731-84087700-e620-11e9-85bd-a958d4b7f61c.png)

```
thiago@ceres:~$ wrk -t4 -c397 -d8m https://localhost:19999/dashboard.js
Running 8m test @ https://localhost:19999/dashboard.js
  4 threads and 397 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   267.74ms  180.09ms   1.53s    69.21%
    Req/Sec   372.22    237.46     1.17k    61.07%
  710387 requests in 8.00m, 256.33GB read
  Socket errors: connect 0, read 12, write 0, timeout 0
Requests/sec:   1479.67
Transfer/sec:    546.72MB
```
#### Memory
![netdata_mem_32_2048](https://user-images.githubusercontent.com/49162938/66163771-97b3dd80-e620-11e9-8b17-abc5e450fb66.png)

### 64 Threads
#### CPU
![netdata_cpu_64_2048](https://user-images.githubusercontent.com/49162938/66163791-a601f980-e620-11e9-82b6-e8fcbf64b74b.png)

```
thiago@ceres:~$ wrk -t4 -c397 -d8m https://localhost:19999/dashboard.js
Running 8m test @ https://localhost:19999/dashboard.js
  4 threads and 397 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   292.11ms  215.76ms   1.87s    68.19%
    Req/Sec   341.46    203.70     1.21k    62.78%
  652749 requests in 8.00m, 235.53GB read
  Socket errors: connect 0, read 20, write 0, timeout 0
Requests/sec:   1359.62
Transfer/sec:    502.36MB
```
#### Memory
![netdata_mem_64_2048](https://user-images.githubusercontent.com/49162938/66163852-c631b880-e620-11e9-840b-f04a7de72d00.png)

**Comment by thiagoftsm** [comment]
Hello everyone,

After a talk with @cakrit now, we decided that next sprint we will begin to test libh2o, I will try to reduce their static library to get what we really need from them.

I am also bringing a table with all the previous results:

![discussion](https://user-images.githubusercontent.com/49162938/66226770-27ae6180-e6cb-11e9-83a7-aba8c777a2da.png)

**Comment by thiagoftsm** [comment]
Considering that we defined the road to go and I will do already in the next sprint, I am closing it.

**Comment by cakrit** [comment]
Based on the tests above, the suggestion is indeed to move with libh2o and try to reduce the static library's footprint. If there are any other opinions, please comment so we can close.

**Comment by cosmix** [comment]
As already discussed with @thiagoftsm, I'm absolutely fine with H2O if we can find a way to minimize the amount of code we'll use from H2O, as the lib is massive.

**Comment by amoss** [comment]
For benchmarking there is a good tool available: https://github.com/httperf/httperf
This produces quite fine-grained statistics and ramps up to a high load-level.

The picoparser looks like a good choice for performance, but the code is quite subtle and intricate - so I wonder how do we handle the dependency? 

1. Pulling the relevant parts of the code into the netdata repo
2. Extracting it from h20 as a build-time dependency

**Comment by thiagoftsm** [comment]
Netdata already brought codes from other libraries to our code keeping the reference for the original developers, you can see this on the top of the file `libnetdata/avl/avl.c`, so we would not have problems with this.

**Comment by amoss** [comment]
Do we have a list of which parts of h2o need to be pulled into netdata and which parts we do not need?

**Comment by thiagoftsm** [comment]
Right now Netdata only works with HTTP/1.1 and our stream that is a kind of HTTP method, so our goal now is to bring the HTTP stuff and probably we will need to have websockets too.

I think it would be good to use the picopaser from libh2o, because this will help us to bring the rest, case they are different.

**Comment by amoss** [comment]
I took another look at h2o - they pull in the picohttpparser directly into their [deps/ directory](https://github.com/h2o/h2o/tree/master/deps/picohttpparser) and then keep a copy in their source tree. I think we can do the same.

**Comment by thiagoftsm** [comment]
> I took another look at h2o - they pull in the picohttpparser directly into their [deps/ directory](https://github.com/h2o/h2o/tree/master/deps/picohttpparser) and then keep a copy in their source tree. I think we can do the same.

I agree 100% with you.

**Comment by amoss** [comment]
Is this ready to close?

**Comment by thiagoftsm** [comment]
I think so, we will move with libh2o.

**Comment by cosmix** [comment]
Agreed.
