### ISSUE TITLE
python.d using a full core 100% of the time

### ISSUE THREAD

**Issue by Wqrld** [netdata/netdata#6845]
AMD Ryzen 5 3600X 6-Core Processor
ubumtu 16.04
High packet-throughput environment (the only thing that really makes this different from my other setups is that this one has a lot more throughput due to a minecraft gameserver). I vaguely remember reporting this before but that seemed to have fixed itself(that was another machine)

**Comment by Wqrld** [comment]
https://i.wqrld.net/static/Windows_Yv

**Comment by Wqrld** [comment]
checking the debug trace logs gives no repeating output. just the modules starting and shutting down

**Comment by cakrit** [comment]
Can you tell from the charts you see which specific module/job is having a hard time? If you see a chart with very high stats (perhaps a web_log or something similar), you can mouse over the date and see the plugin and module that generate it:
![Screenshot from 2019-09-15 13-48-47](https://user-images.githubusercontent.com/43294513/64921203-8e251b80-d7c0-11e9-87db-a5b4eead7b6e.png)

In the image above, it's the go.d plugin's `httpcheck` module. 

If you can't identify a suspicious chart this way, you could start disabling python.d modules one by one. We have created go.d modules for the most cpu-intensive python.d modules to prevent this from happening, so it could be a matter of disabling the python module and using the go.d one instead. 

Please let us know what you find.

**Comment by ilyam8** [comment]
@Wqrld 

> Can you tell from the charts you see which specific module/job is having a hard time? 

check `Netdata Monitoring` -> `python.d` section on the dashboard

**Comment by ilyam8** [comment]
@Wqrld 
what is your netdata version btw?

> test@debian10:/opt/netdata/usr/sbin$ ./netdata -v
netdata v1.17.1-28-g744a1261

**Comment by Wqrld** [comment]
Running netdata v1.17.1

**Comment by Wqrld** [comment]
> check Netdata Monitoring -> python.d section on the dashboard
This section does not exist for me

**Comment by ilyam8** [comment]
Check the whole `Netdata Monitoring -> python.d` section. There is a chart with execution time for every python job.

**Comment by cakrit** [comment]
![Screenshot from 2019-09-16 17-10-05](https://user-images.githubusercontent.com/43294513/64970129-7bd0dd80-d8a5-11e9-9181-777887bb493b.png)

**Comment by Wqrld** [comment]
https://i.wqrld.net/static/Cake_ge

i was able to kill the python.d process that was using a lot of cpu and it seems to be working fine now. Ill keep this open if it comes back

**Comment by ilyam8** [comment]
> it seems to be working fine now. Ill keep this open if it comes back

@Wqrld please reopen if there is problem again
