### ISSUE TITLE
netdata/packaging: provide ipkg package of netdata

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6848]
##### Feature idea summary
Enlightened by the feedback from https://github.com/netdata/netdata/issues/6846, we should be providing IPK package for netdata for our users to consume on variety of embedded devices that support this.

##### Expected behaviour
Provide a .ipk together with the rest of the release artifacts on nightly and stable releases

**Comment by Ferroin** [comment]
If we're planning on doing this, it would be good to provide solid instructions on how to build an IPK manually given a cross-build environment for the target system.  There are just too many different acrhitectures to cover, and way too many custom systems that opkg is used on (pretty much every platform that uses it is built from a ridiculously customizable meta-distribution like Yocto or Buildroot, so there's some significant variance in what the platform will have included).

**Comment by BH1NBN** [comment]
@paulkatsoulakis  See your conversation, are you sure? I no longer see the available ipk? I just get the ipkg command for the program used by my device, but I am a little sad to see that I did not prepare the IPK file

**Comment by Ferroin** [comment]
@ilyam8 This can be punted to product for further evaluation.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
