### ISSUE TITLE
netdata/packaging: Build from source for Judy-devel and libuv for Centos7 x86

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6849]
##### Bug report summary
Based on Travis build: https://travis-ci.com/netdata/netdata/jobs/235311638
We don't seem to have an official repository i know of that provides Judy-devel and libuv.

We have to build from source for those two particular packages, for x86 Centos-7

##### OS / Environment
CentOS 7, 32 bit (x86)

##### Netdata version (ouput of `netdata -V`)
Latest

##### Component Name
netdata/packaging

##### Steps To Reproduce
Just trigger the 32 bit RPM package build, it will fail on CentOS 7
Sample: https://travis-ci.com/netdata/netdata/jobs/235311638

##### Expected behavior
No failures

**Comment by paulkatsoulakis** [comment]
We already have a way to build judy from source four our docker images, i will be using this method for the OSes we do not have a binary package available.

**Comment by paulkatsoulakis** [comment]
Got a script for libuv to compile under 32 bit centos 7 and got a test failing 

you try to build latest release from their repository for libuv and fails a test ```FAIL: test/run-tests
======================================================
1 of 1 test failed
Please report to https://github.com/libuv/libuv/issues
======================================================
make[1]: *** [Makefile:5209: check-TESTS] Error 1
make[1]: Leaving directory '/opt/libuv-1.32.0'
make: *** [Makefile:5469: check-am] Error 2
``` ```not ok 48 - fs_copyfile
# exit code 6
# Output from process `fs_copyfile`:
# Assertion failed in test/test-fs-copyfile.c on line 202: req.result == UV_EACCES
```

**Comment by paulkatsoulakis** [comment]
```[root@4a8d3561eb92 test]# cat /etc/os-release 
NAME=Fedora
VERSION="29 (Container Image)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Container Image)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
[root@4a8d3561eb92 test]# 
```

**Comment by paulkatsoulakis** [comment]
I am merging the introduction of those two scripts, without adding them onto the pipeline anywhere. PR: https://github.com/netdata/netdata/pull/6850

I have two things to think about:

1) What are we going to instruct our users to do, for the OS that the binary packages are not available? Prompt them to run our scripts to install libuv and judy? Would that make enough sense?

2) The failing test, i need to understand whether this is indeed some bug the test really caught OR if this is somehow related to the peculiarities the docker image itself may have and may cause problems with libuv. Perhaps @mfundul can provide faster feedback on this, given his experience working deeply on libuv.  The OS details and the errors are mentioned on previous comment

**Comment by mfundul** [comment]
CentOS 7 32-bit is not an officially supported arch. It's not supported by Redhat nor EPEL, so it's making things difficult for everybody. However, this assertion might be something unrelated, maybe something like [this](https://github.com/libuv/libuv/issues/2257)?

**Comment by paulkatsoulakis** [comment]
> CentOS 7 32-bit is not an officially supported [arch](https://wiki.centos.org/SpecialInterestGroup/AltArch/i386). It's not supported by Redhat nor EPEL, so it's making things difficult for everybody. However, this assertion might be something unrelated, maybe something like [this](https://github.com/libuv/libuv/issues/2257)?

I am not sure what you mean its not officially supported.
Check here: https://wiki.centos.org/Download, section "AltArch" releases

**Comment by mfundul** [comment]
From the link in my comment:
```
The i386 effort is being done as a community SIG project. Everyone is welcome to participate, though the actual builds are an artefact of the 64 bit process in that all 32 bit packages are built, but only some used as multi-lib in the 64 bit architecture. But we still need community help to maintain documentation and also fix issues that may arise in this architecture.

We encourage vendors to come and join this effort, especially for the newer 32-bit IOT boards like Intel Edison, etc.

The wider CentOS Ecosystem is also welcome to engage with us, both at the project and code level. If you are working with a project that interfaces, manages or develops on top of CentOS, especially in the virtualization, cloud, container and infrastructure management areas - we would love to have you guys get involved. 
```

for Redhat see [here](https://access.redhat.com/solutions/509373) and for EPEL see [here](https://linuxhint.com/epel_centos7/).

**Comment by cakrit** [comment]
It doesn't matter if an OS is officially supported or not. We must guarantee that all OS versions in LTS work perfectly, but that doesn't mean that we ignore the other OSs. If we are able to provide a binary pkg distribution for this OS we do it, otherwise we ensure at least one of our methods (install from source, kickstart, kickstart-static64) works there.

**Comment by mfundul** [comment]
Agreed, I'm just justifying the difficulties and saying it's to be expected that there will be problems with this distro spin. Putting it in prespective as in it's not a widely used LTS that is a showstopper bug.

**Comment by Ferroin** [comment]
libuv is in EPEL, as is Judy, so this is currently invalid.

Long term, it would, however, be nice to vendor Judy because it's not present on an increasing number of systems we want to support, but there's a separate issue for that (#8153).
