### ISSUE TITLE
 I can't send alarm e-mails.

### ISSUE THREAD

**Issue by brhnsfrn** [netdata/netdata#6853]
Hello,
I can't send alarms with Postfix. 3 test e-mail waiting in the queue. When I turn the device's power off and back on, it sends emails.

**postqueue -p**

-Queue ID-  --Size-- ----Arrival Time---- -Sender/Recipient-------
B572980AB3    11199 Sun Sep 15 17:49:15  BurhanPi@burhanpifqdn.example.com
(Host or domain name not found. Name service error for name=smtp.gmail.com type=                                                                                        AAAA: Host not found, try again)
                                         brhnsfrn@gmail.com

839BC80ABD    11339 Sun Sep 15 17:49:16  BurhanPi@burhanpifqdn.example.com
(Host or domain name not found. Name service error for name=smtp.gmail.com type=                                                                                        AAAA: Host not found, try again)
                                         brhnsfrn@gmail.com

F3FDB80AB8    11297 Sun Sep 15 17:49:15  BurhanPi@burhanpifqdn.example.com
(Host or domain name not found. Name service error for name=smtp.gmail.com type=                                                                                        AAAA: Host not found, try again)
                                         brhnsfrn@gmail.com

-- 33 Kbytes in 3 Requests.

**Comment by cakrit** [comment]
Hi @brhnsfrn,

Apologies, but this isn't the correct forum to discuss issues with postfix, or name resolution. Having said that, I suggest you  `dig`  while the name resolution is failing, to check for the nameserver used and go from there.
