### ISSUE TITLE
Elasticsearch plugin SSL and Basic Authent

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#6858]
Hi

I notice the current python elasticsearch plugin does not support SSL and basic authent.
Should be convenient to add SSL and basic auth feature to this plugin

Basic authent should be easily added with user:pwd injected in the url :  
```
self.url = '{scheme}://{host}:{port}'.format(
            scheme=self.configuration.get('scheme', 'http'),
            host=self.host,
            port=self.port,
        )
```
Or using basic authent header

**Comment by ilyam8** [comment]
Hi @fmercier-almerys 	

Basic auth is supported
https://github.com/netdata/netdata/blob/2238b41ff146b440226aab40a878ac344391d2ca/collectors/python.d.plugin/elasticsearch/elasticsearch.conf#L71-L74

SSL too

```yaml
local:
 host: '127.0.0.1'
 port: '9200'
 scheme: `https`
```

ssl related options

https://github.com/netdata/netdata/blob/2238b41ff146b440226aab40a878ac344391d2ca/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py#L53-L56

**Comment by fmercier-almerys** [comment]
Ok sorry, it works nice
