### ISSUE TITLE
Alarm-notify.sh works but netdata agent does not send notifications

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#6860]
Hi

I configured slack notification target and ran : 

```
su -s /bin/bash netdata
bash-4.2$ /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh test

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2019-09-16 16:40:42: alarm-notify.sh: INFO: sent slack notification for: apim-es1-dev test.chart.test_alarm is WARNING to '#monitoring-alerts'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2019-09-16 16:40:43: alarm-notify.sh: INFO: sent slack notification for: apim-es1-dev test.chart.test_alarm is CRITICAL to '#monitoring-alerts'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2019-09-16 16:40:43: alarm-notify.sh: INFO: sent slack notification for: apim-es1-dev test.chart.test_alarm is CLEAR to '#monitoring-alerts'
# OK
```

I have a master slave architecture with slave configured in headless mode (memory and web none but health is enabled)

I configured slack chanel on the master too and the ran the notifier script also on it
The slack url have HTTPS scheme so I added the certificate on certifi bundle to avoid cert validation pb.

If notifier.sh test works, when a Alarm is triggered on a slave or on the master it does not push the content to slack.

```
alarm-notify.sh: ERROR: failed to send slack notification for: apim-es1-dev elasticsearch_local.cluster_health_status.elasticsearch_last_collected is WARNING to '#monitoring-alerts', w
ith HTTP error code 000.
```
What is the code 000 ?

I am on netdata v1.17.1-14-ga8e56a94

**Comment by cakrit** [comment]
I was just writing a different response, when you updated the OP. Please do a deeper trace using the info at https://docs.netdata.cloud/health/notifications/#testing-notifications, so that you can get the exact `curl` call done to the Slack API. Then you can repeat the call with curl in verbose mode, if needed. It's conceivable that it's the https endpoint, but I haven't seen that error code before.

**Comment by fmercier-almerys** [comment]
I am reading https://github.com/netdata/netdata/issues/6860 I try --insecure option because the issue says curl is embedded in netdata so il will change to the system curl path

**Comment by fmercier-almerys** [comment]
Yes change the embedded curl for the system curl make it works. It is a certificate TLS pb

**Comment by fmercier-almerys** [comment]
you can close this issue
