### ISSUE TITLE
Edit health alarm message?

### ISSUE THREAD

**Issue by secato** [netdata/netdata#6862]
It's possible to edit the health alarm notification message? I'm using discord.

**Comment by cakrit** [comment]
Easy way, with the drawback that any updates to `alarm-notify.sh` will be irrelevant to you, once you do it: Copy `/usr/libexec/netdata/plugins.d/alarm-notify.sh` to a location accessible by the user `netdata`, edit the `send_discord()` function in the copied file and update `netdata.conf` `[health]` `script to execute on alarm`.

Harder way: Take the contents of the `send_discord()` function in `/usr/libexec/netdata/plugins.d/alarm-notify.sh` and use them to replace the contents of the `custom_sender()` function in `/etc/netdata/health_alarm_notify.conf` and edit there. You will need to set `SEND_DISCORD="NO"` and `SEND_CUSTOM="YES"`, but it should work without any other changes. Do test it first of course.
