### ISSUE TITLE
Centering charts from alarm log should not need a redirect

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6866]
##### Feature idea summary
#6391 fixed the issue of properly centering alarms. However, the alarm entries in the "Log" tab of the UI apparently require a redirect via goto-host-from-alarm.html, or the cloud redirect page. We shouldn't need that redirect.

##### Expected behavior
When I click on an entry in the alarm "Log" tab, the screen should just scroll to the appropriate chart, center on the time and freeze, exactly as we do for active alarms.

**Comment by ilyam8** [comment]
That is fixed (apart from the "freeze" part).

> exactly as we do for active alarms.

I observe the same behavior for both active alarms and entries from "Log" tab.
