### ISSUE TITLE
Web server and symbolic links

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6873]
##### Feature idea summary
The majority of the web servers has the capability to follow symbolic links, see apache for example https://httpd.apache.org/docs/2.4/mod/core.html, but this also can create security  issues in the server side, as it was explained in #1394, the initial issue related to this subject.

We need to have conditions to follow symbolic links and check whether they are safe to deliver for the user.
##### Expected behavior
Web server loads files from symbolic links.

**Comment by thiagoftsm** [comment]
It is necessary to find a new paper, but this ( https://research.cs.wisc.edu/mist/safefile/safeopen_ares2008.pdf ) is a good start point.

**Comment by amoss** [comment]
What is the use-case for this - why do we want to follow symbolic links and which files that are served will be affected?

**Comment by thiagoftsm** [comment]
This is an old request done from our users, the goal is our web server to have a feature like the "Options FollowSymLinks" present in Apache webserver.

**Comment by amoss** [comment]
Ok, I've had a quick read-through the older issues and the original PR. I'll take a much deeper look and have a think about the security implications that are discussed.

**Comment by prologic** [comment]
Actually I'm with @amoss on this one. I don't understand why we would want to support turning the Netdata Agent into a more feature-rich web server. But I confess I did not read the older issue; just finding it really hard to come up with a use-case for this.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
