### ISSUE TITLE
Kubernetes container matching and PGID resolution

### ISSUE THREAD

**Issue by majodev** [netdata/netdata#6878]
#### Bug report summary
All containers in a kubernetes pod are currently not resolved as there is a hard-limit on the first item in `containerStatuses[]`. See [here](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh.in#L89).

##### OS / Environment
CoreOS and Ubuntu

##### Netdata version (output of `netdata -V`)
Netdata 1.17.1

##### Component Name
cgroup-name.sh

##### Steps To Reproduce
Exchange [here](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh.in#L89) from
```bash
jq -r '.items[] | "k8s_\(.metadata.namespace)_\(.metadata.name)_\(.metadata.uid)_\(.status.containerStatuses[0].name) \(.status.containerStatuses[0].containerID)"' |
```
to
```bash
jq -r '.items[] | "k8s_\(.metadata.namespace)_\(.metadata.name)_\(.metadata.uid)_" + (.status.containerStatuses[] | "\(.name) \(.containerID)")'
```
to make it happen again (encountered this bug during an upgrade).

##### Expected behavior

ID is matched all containers in all pods.

**Comment by ilyam8** [comment]
@majodev hi. I see you are suggesting a solution. Could you make a PR?

**Comment by majodev** [comment]
Hi, I'm still testing if this is the only line required to fully resolve the situation, especially for both normal Ubuntu and Container-Optimized OS with containerd nodes (whom still suffer from a non fully resolution). 

e.g. for Ubuntu-k8s-nodes

```

```
k8s_lernsieg-service-dev_app-base-7864b5d7b9-zbpmp_f8e75af2-d9fc-11e9-8b78-42010a9c0077_assistant containerd://3a52c5f9abcde5a7ca0e143155ac9266f38bd88e6d35ef172fd1db1be774aaf5
k8s_lernsieg-service-dev_app-base-7864b5d7b9-zbpmp_f8e75af2-d9fc-11e9-8b78-42010a9c0077_nfs-server containerd://1282f97b4172a0f834f0b10805f4df47b51bf9f562e5008b496f99aa538e562a
k8s_lernsieg-service-dev_app-base-7864b5d7b9-zbpmp_f8e75af2-d9fc-11e9-8b78-42010a9c0077_postgres containerd://89a0ebe3442411bd14030785e238bddeeee491bd7370a3eb58e8d6501d68bb2b
k8s_lernsieg-service-dev_app-base-7864b5d7b9-zbpmp_f8e75af2-d9fc-11e9-8b78-42010a9c0077_redis containerd://0a3e53939ac4c049c2fea1811999eaaa0670eeaa230fb26a7b9f68f57ed7c613
```

**Comment by majodev** [comment]
For example, if I execute the following in the netdata container:

```bash
curl -sSk -H "Authorization: Bearer $KUBE_TOKEN"  "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/pods" | jq -r '.items[] | "k8s_\(.metadata.namespace)_\(.metadata.name)_\(.metadata.uid)_" + (.status.containerStatuses[] | "\(.name) \(.containerID)")'
```

Ubuntu k8s nodes:
```
k8s_project-namespace_deployment-name-66b69b889d-4kr42_d8782797-aed1-11e9-8b78-42010a9c0077_assistant docker://af4d14ccac6778ec1f85be1af4d4510e4c849678592275fb20b4305c29cb3aa6
k8s_project-namespace_deployment-name-66b69b889d-4kr42_d8782797-aed1-11e9-8b78-42010a9c0077_nfs-server docker://d44150a9eb7e895a80a3f1b806edd418ad3227358195d1ece8f3e0a8370e0492
k8s_project-namespace_deployment-name-66b69b889d-4kr42_d8782797-aed1-11e9-8b78-42010a9c0077_postgres docker://f741bdde8675f3f7dd2063f6377d594a9660f0ade051cc2eb360fc8910a7b728
k8s_project-namespace_deployment-name-66b69b889d-4kr42_d8782797-aed1-11e9-8b78-42010a9c0077_redis docker://449daaa242f9ac9b5756edde46ba74f534ec7219384f15d9103d4510bf3bc802
```

Container-Optimized OS with containerd nodes:
```
k8s_project-namespace_deployment-name-7864b5d7b9-zbpmp_f8e75af2-d9fc-11e9-8b78-42010a9c0077_assistant containerd://3a52c5f9abcde5a7ca0e143155ac9266f38bd88e6d35ef172fd1db1be774aaf5
k8s_project-namespace_deployment-name-7864b5d7b9-zbpmp_f8e75af2-d9fc-11e9-8b78-42010a9c0077_nfs-server containerd://1282f97b4172a0f834f0b10805f4df47b51bf9f562e5008b496f99aa538e562a
k8s_project-namespace_deployment-name-7864b5d7b9-zbpmp_f8e75af2-d9fc-11e9-8b78-42010a9c0077_postgres containerd://89a0ebe3442411bd14030785e238bddeeee491bd7370a3eb58e8d6501d68bb2b
k8s_project-namespace_deployment-name-7864b5d7b9-zbpmp_f8e75af2-d9fc-11e9-8b78-42010a9c0077_redis containerd://0a3e53939ac4c049c2fea1811999eaaa0670eeaa230fb26a7b9f68f57ed7c613
```

It seems that all containers are reported correctly but unfortunately, only all containers on the *Ubuntu* node (without containerd) are correctly matched and found. On the COS Node, only the `assistant` container is found by netdata, and I currently suspect this has to do with the `containerd://` protocol, or the identifiers itself.

**Comment by cakrit** [comment]
When I do what you propose on our GCS cluster I get the following:
```
bash-4.4# curl -sSk -H "Authorization: Bearer $KUBE_TOKEN"  "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/pods" | jq -r '.items[] | "k8s_\(.metadata.namespace)_\(.metadata.name)_\(.metadata.uid)_" + (.status.containerStatuses[] | "\(.name) \(.containerID)")'
k8s_default_hopping-hamster-nginx-ingress-controller-55b8d5f5c8-hp8j8_510e719b-adff-11e9-8a8e-42010a800061_nginx-ingress-controller docker://8920180ea204079eb7095aff848bb14e1dde87bc16543c72c01d29e53327f409
k8s_default_hopping-hamster-nginx-ingress-default-backend-5c9d64dd4c-vnz68_51189e27-adff-11e9-8a8e-42010a800061_nginx-ingress-default-backend docker://5e123df49325ab8fccab977a1f79a0fdec3412cc1d2159ec26ee5dec7fffab5f
jq: error (at <stdin>:6328): Cannot iterate over null (null)
```
I see a case in our setup where we have a second entry in `containerStatuses`, so I'll try to find a way to make it work.

**Comment by majodev** [comment]
@cakrit Interesting, not yet seen this error our GKE though (v1.13.7-gke.8, ~400pods, ~500containers).

This looks like there may be `/api/v1/pods` response payloads where `items[].status` is `null` or `items[].status.containerStatuses` is `null`. I'm not sure how to query this kind of optionals in jq yet, but there is definitely a way...

**Comment by cakrit** [comment]
I found how it work, just a `?` after the Statuses array:
```
jq -r '.items[] | "k8s_\(.metadata.namespace)_\(.metadata.name)_\(.metadata.uid)_" + (.status.containerStatuses[]? | "\(.name) \(.containerID)")'
```

Doing the PR now, thanks @majodev!!!

**Comment by majodev** [comment]
Very nice. I can also confirm that this fix works regardless of the Host/Node OS (Ubuntu, Container-Optimized OS with containerd). We had an issue with a wrong `PGID` env setting on some hosts:
* We resolved that now by mounting the host `/etc/group` to `/host/etc/group` readonly into the container and auto-resolve the PGID through `PGID=$(grep docker /host/etc/group | cut -d ':' -f 3)` on netdata container startup).
* Especially finding new cgroups (new pods and all its containers) now works flawlessly.

Thanks for the quick PR.

**Comment by cakrit** [comment]
> * We resolved that now by mounting the host `/etc/group` to `/host/etc/group` readonly into the container and auto-resolve the PGID through `PGID=$(grep docker /host/etc/group | cut -d ':' -f 3)` on netdata container startup).

Based on what you learned from your case here, is there something we should/cloud be doing in the netdata helmchart to make things simpler for everyone? e.g. add a volumemount for `/etc/group` to https://github.com/netdata/helmchart/blob/master/templates/daemonset.yaml and add the PGID in the prestart commands?

**Comment by majodev** [comment]
We are not currently using this helm chart and have no plans to do.

You may defiantly add this volume mount there by default, however, I'm not totally sure how you are going to inject this resolved `PGID` without touching the Dockerfile (`PGID=$(grep docker /host/etc/group | cut -d ':' -f 3)` must run in the container *before* the default entrypoint).

We currently do this by building our own image and directly overwrite the [run.sh](https://github.com/netdata/netdata/blob/master/packaging/docker/run.sh) file for this usecase which may not be a adequate solution for the helm project...

**Comment by cakrit** [comment]
Leaving it as a feature request for the PGID.

**Comment by prologic** [comment]
@majodev Would you be willing to put up a PR for adding PGID support to the entry-point for our docker images?

**Comment by cakrit** [comment]
Since this is just for k8s and @ilyam8 did find a way to persist the identifier we need, I'm closing this one. We should have a different issue for docker PGID, if not we'll create one.
