### ISSUE TITLE
remove not updated charts after some time

### ISSUE THREAD

**Issue by RobbScarlet** [netdata/netdata#688]
Hi,
If I do not need a chart, how can I delete it.
I want to delete the chart which do not collect data after 10 minutes, and let it not display on the dashboard.

**Comment by ktsaou** [comment]
I had such code in netdata, but I see I have disabled it for some reason and I can't remember why.

I can re-enable it, but I would like to make a few tests first. So, I'll leave this open.

**Comment by cakrit** [comment]
The collectors now have the ability (and responsibility) to mark both charts and dimensions as obsolete. So if we have specific examples of charts that should be removed, we need to create an issue for those collectors.

**Comment by vlvkobal** [comment]
Charts can be obsoleted using the `obsolete` option in an external plugin. The documentation is [here](https://docs.netdata.cloud/collectors/plugins.d/#chart). For an internal plugin the `rrdset_is_obsolete()` function should be used.

**Comment by cakrit** [comment]
I believe we can close this one, let us know if you need more help.
