### ISSUE TITLE
wrong metrics on Network interface

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#6883]
##### Bug report summary
network interface show wrong metrics

##### OS / Environment
CentOS 7.6
system have 2 NIC: eth0 and eth1 but only eth1 has IP and connects to network

```
$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 00:50:56:ac:8e:72  txqueuelen 1000  (Ethernet)
        RX packets 88762582  bytes 30197495659 (28.1 GiB)
        RX errors 0  dropped 300277  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet xx.xx.xx.xx  netmask 255.255.255.0  broadcast xx.xx.xx.255
        ether 00:50:56:ac:1a:c3  txqueuelen 1000  (Ethernet)
        RX packets 41422832  bytes 9075738818 (8.4 GiB)
        RX errors 0  dropped 25565  overruns 0  frame 0
        TX packets 35535794  bytes 46097509691 (42.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 26903539  bytes 8339877004 (7.7 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26903539  bytes 8339877004 (7.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

##### Netdata version (ouput of `netdata -V`)
v1.17.1

##### Component Name
network

##### Steps To Reproduce
install netdata and check Web UI on network interface

##### Expected behavior
eth0 should have no access -> Bandwidth should be nearly 0

![eth0](https://user-images.githubusercontent.com/8895721/65130523-896a9c80-da38-11e9-8668-8309448efe11.jpg)

**Comment by ilyam8** [comment]
hi @Wing924 

Lack of ip doesnt mean no bandwidth

>eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 00:50:56:ac:8e:72  txqueuelen 1000  (Ethernet)
        RX packets 88762582  bytes 30197495659 (28.1 GiB)

**Comment by ilyam8** [comment]
But connetion to network does 😄 

So you are saying eth0 `eth0` doesnt rx any packets (tcpdump?) but netdata show it?

**Comment by Saruspete** [comment]
eth0 is in `RUNNING` state, which means it's physically connected to the network (have duplex).
There's always some packets like arp, multicast, broadcast etc.. which are sent on the network.
While your machine isn't part of these broadcast and multicast (224.0.0.1) sollicitations, your interface receive them nonetheless.

If you don't want it, down your interface:
`ifconfig eth0 down`
or 
`ip link set eth0 down`  

As a side note, by default (sysctl `net.ipv4.conf.all.rp_filter=0`) Linux responds to incoming packets from the fastest interface available, not only the one the packet came through. So you **might** get network interruption doing so. But in your current case, doesn't seem likely.

**Comment by Wing924** [comment]
@ilyam8 @Saruspete 
I confirm it again and found it's not bug.
Many servers with same network config also show high bandwidth on eth0.
Tested on v1.13.0, v1.16.0 and v1.17.1 and the results are same.
Thank you for your help.
