### ISSUE TITLE
Multiple Alarm configuration on Master based on Slave

### ISSUE THREAD

**Issue by DeWaRs1206** [netdata/netdata#6886]
First of all, congrats on this tools. It's awesome! 
I have still a question
##### Question summary
I'm using the stream feature to monitor different landscape I'm in charge of. 
Everything is working great, my slaves send data to my master, I can switch between etc.
My current problem is, I would like the Master to send the alarm and I have different alarm configuration depending of the landscape. 
For example, I send alert to specific Slack Channel depending of the landscape. (I have a specific slack channel for PROD servers, and another for other landscape)

I can't find a way to configure the alarm on the master side to redirect the Slack alarm to a specific channel. Maybe this is not possible or I'm thinking the wrong way. 

Could you please help me on that? 

##### OS / Environment
Ubuntu 18.04 for all servers (Master / Slave) 
##### Component Name
Alarm notification 
##### Expected results

Thanks a lot and congrats on your great tool again !

**Comment by cakrit** [comment]
I don't really see a way to do this with a single master, unless you want to create your own custom sender: i.e. start with `send_slack()` in `/usr/libexec/netdata/plugins.d/alarm-notify.sh` and use it to replace the contents of `custom_sender()` `/etc/netdata/health_alarm_notify.conf`. Having a second master just for the dev infrastructure may be simpler, for what you want to do.

**Comment by DeWaRs1206** [comment]
@cakrit thanks for the answer. After some investigation, I found a way based on your suggestion, an then maybe an even simpler way. Do we agree that `health_alarm_notify.conf` is ready every time an alarm is trigger? Then something like:
```
if [[ $host =~ "PROD" ]];then
        DEFAULT_RECIPIENT_SLACK="devops-monitor-prod"
else
        DEFAULT_RECIPIENT_SLACK="devops-monitor"
fi
```
should works right?

**Comment by cakrit** [comment]
Yes, very clever solution! :)
