### ISSUE TITLE
Kickstart script md5 hash mismatch. Verification fails. Docs are ahead of the scripts deployment.

### ISSUE THREAD

**Issue by AnianZ** [netdata/netdata#6888]
##### Bug report summary

The md5sums declared in the docs for the kickstart.sh and kickstart-static64.sh seem to be out of sync again. The docs already contain the new hashes for both files while `curl -Ss https://my-netdata.io/kickstart-static64.sh | md5sum | cut -d ' ' -f 1` still returns the old checksum and therefore fails my deployment. I'm aware that in #6049 a similar issue was reported and then resolved but it seems the error has cropped up again and the last change to the kickstart scripts was yesterday (2019-09-17) at the time of reporting this issue. So maybe there is another problem in the deployment pipeline. Or maybe I'm just not patient enough.

Just as an additional question: How often are these deployments kickstart scripts expected to change? I wanted to download, verify and run them via Anisble and if the checksum changes regularly I would probably need to skip the validation.

##### OS / Environment
Ubuntu 18.04.1 Server

##### Netdata version (ouput of `netdata -V`)
_Netdata not installed yet_

##### Component Name
packaging

##### Steps To Reproduce
`[ "5c432e78d5f40403e8b7c00b1a19a7ca" = "$(curl -Ss https://my-netdata.io/kickstart-static64.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"`

##### Expected behavior
Output of `OK, VALID`

**Comment by cakrit** [comment]
Thanks for the report, we're on it.

**Comment by cakrit** [comment]
Try again please.

**Comment by cakrit** [comment]
Works for me now, closing and will monitor for comments to see if you still face issues.

**Comment by AnianZ** [comment]
Thanks. I can confirm that it works from my side as well. :+1: Thanks for the quick support. Will this hash change often in the future?

**Comment by cakrit** [comment]
The hash and the README mentioning the new hash changes whenever we make a change in `kickstart-static64.sh`. We just did one a few minutes ago, because there was a bug parsing the options. In general they don't change very often, but I wouldn't hardcode them in any automated scripts, unless you're willing to retrieve and parse https://github.com/netdata/netdata/blob/master/packaging/installer/README.md

**Comment by AnianZ** [comment]
Ok. Then I will probably remove the hash checking from my script when it start's failing again.
