### ISSUE TITLE
Broken non-interactive install of static binaries

### ISSUE THREAD

**Issue by roens** [netdata/netdata#6891]
##### Bug report summary

Yesterday's [commit](https://github.com/netdata/netdata/commit/4dc34c07) (adding "support for offline installs using kickstart") seems to have broken the non-interactive (or, `--dont-wait`) install. Rather than installing without question, the script appears to get stuck in a loop.

I've validated this by adding `-x` between `bash` and the script `kickstart-static64.sh`. This results in a rapid and repeated filling of shell scroll-back of `opts=' --accept --accept --accept --accept…`.

Using the [previous iteration of the script](https://github.com/netdata/netdata/raw/dc38b1d15df2d07f65c0f3c8f8f944fbcc89a574/packaging/installer/kickstart-static64.sh) works as expected.

##### OS / Environment

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

##### Netdata version (ouput of `netdata -V`)

N/a: issue is regarding installation on a new host.

##### Component Name

One-line install of Linux 64bit pre-built static binary

##### Steps To Reproduce

Attempt the 1-line install of static binaries with the "don't ask" flag:

```
bash kickstart-static64.sh --non-interactive
```

##### Expected behavior

Should have installed Netdata.

**Comment by roens** [comment]
FWIW, this'll also break manual upgrades of existing installs using the `kickstart-static64.sh` script… since running it with either `--non-interactive` or `--dont-wait` flag will end up in the same endless loop.

**Comment by paulkatsoulakis** [comment]
Hi guys, my apologies you had to go through this.
This was a bug that was identified and fixed on kickstart.sh, but slipped through somehow on `kickstart-static64.sh`

Fix is on the way, will update asap
