### ISSUE TITLE
Request header field x-auth-token is not allowed by Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by EnzoAkira** [netdata/netdata#6893]
### Bug report summary
x-auth-token is not allowed by Access-Control-Allow-Headers

I am making a Maintenance page to manage the alarms of a few servers and at same time check if server are alive.
I am using a page on a Confluence server and I created this code: 

<details><summary>
  sample of code
  </summary>
  
   ```javascript
...
var serverNetdataTemplate = {
  url: '',
  type: null,
  contentType: 'application/json; charset=UTF-8',
  crossDomain : true,
  withCredentials: true,
  data: null,
  processData: true,
  headers: {
    'X-Auth-Token': ''
  }
};
....
function refreshMaintenanceState() {
  //Only update if in focus
  if(document.hasFocus()) {
    //Refresh clusters Maintenance state
    $('div.panel').each(function() {
    ...
    //Netdata API
      var serverNetdataGet = JSON.parse(JSON.stringify(serverNetdataTemplate));
      serverNetdataGet.url = `https://${serverName}-vpn.xyz.com:19999/api/v1/manage/health`;
      serverNetdataGet.headers['X-Auth-Token'] = 'as76d57a-8as7-ljk3-54oo-l23kj4234knn';
      serverNetdataGet.type = 'GET';
      serverNetdataGet.data = 'cmd=LIST';
          
     $.ajax(serverNetdataGet)
     ...
    }
   }
  } 
   ```
  </details>

After the ajax do there job I get the following error:
`Access to XMLHttpRequest at 'https://HostName-vpn.xyz.com:19999/api/v1/manage/health?cmd=LIST' from origin 'https://confluence.xyz.com' has been blocked by CORS policy: Request header field x-auth-token is not allowed by Access-Control-Allow-Headers in preflight response.`

I dig on netdata code and found this piece:
https://github.com/netdata/netdata/blob/9094de0f63759554696a6c02d54d01f877ab1cdb/web/server/web_client.c#L1215

It's missing X-Auth-Token.
I assume that it's the cause, but I'm not sure if that apply to my case.

### OS / Environment
CentOS 7

### Netdata version (ouput of `netdata -V`)
v1.17.1-6-g09e05ed

### Component Name
API

### Steps To Reproduce
Create a ajax request to netdata API with X-Auth-Token

### Expected behavior
List, RESET and DISABLE ALARMS

**Comment by cakrit** [comment]
Hadn't tried this to be honest, thanks for the catch! 
It's an innocuous addition, will wait for the PR checks to be completed and merge it.

**Comment by EnzoAkira** [comment]
Thank you very much for your very quick response!

I have great new! I made a few tests and that worked very well!!!

Once more thank you and keep doing a excellent work!!!!!!! 👍

**Comment by thiagoftsm** [comment]
Thank you by the report @EnzoAkira, we are glad that everything works fine.

**Comment by EnzoAkira** [comment]
Hi guys!
Just to ask, when this fix will be on the stable-channel Linux 64bit pre-built static?

Thanks

**Comment by thiagoftsm** [comment]
Hi @EnzoAkira , the stable channel will be updates in few days with the release of version 1.18.

**Comment by EnzoAkira** [comment]
Thank you @thiagoftsm for the quick feedback!!!
