### ISSUE TITLE
install netdata in ubuntu 18.04 with anaconda and nvidia-smi

### ISSUE THREAD

**Issue by andresfp14** [netdata/netdata#6901]
##### Question summary
How can I install netdata so that it uses a previously installed version of python (anaconda), and enable the nvidia-smi plugin?

##### OS / Environment
Ubuntu 18.04
conda 4.6.14
NVIDIA-SMI 410.48

##### Component Name
collectors/python.d.plugin/nvidia_smi

##### Expected results
1. nvidia-smi charts shown in the netdata dashboard
2. netdata using anaconda environment to run the python.d plugins

##### What I tried:
A) Installing netdata via apt get:
- `sudo apt-get install zlib1g-dev uuid-dev libuv1-dev liblz4-dev libjudy-dev libssl-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl`
- `sudo apt-get install netdata -y` 
The nvidia-smi plugin doesn't even appear in the installed directories.

B) Cloning the repo, using the installer and modifying the files mentioned in the plugin.
- `sudo apt-get install zlib1g-dev uuid-dev libuv1-dev liblz4-dev libjudy-dev libssl-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl`
- `git clone https://github.com/netdata/netdata.git`
- `cd netdata`
- `sudo ./netdata-installer.sh`
 - editing the configurations using `sudo sh edit-config python.d.conf` and `sudo sh edit-config python.d/nvidia_smi.conf`
- lastly restarting the netdata service

but it doesn't seem to work so far... I would appreciate some help

**Comment by ilyam8** [comment]
Hey @andresfp14 

Try to run `python.d.plugin` in debug mode

See

> https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module

**Comment by andresfp14** [comment]
Thanks @ilyam8 ,

Apparently the problem was simpler.... I had forgotten to modify netdata.conf .
although when I tried to debug the python module, I ended with a  
```
Traceback (most recent call last):
  File "python.d.plugin", line 55, in <module>
    from bases.collection import safe_print
ModuleNotFoundError: No module named 'bases' 
```
I'll close the question, as the specific problem was solved. Thanks again!
