### ISSUE TITLE
As a fan of Netdata I would request a new feature: stickers for my laptop

### ISSUE THREAD

**Issue by tioumen** [netdata/netdata#6906]
#### Feature idea summary
Netdata is a huge project for a while and as a big fan of the project I would have a stickers for my laptop. A way to spread the project ... :)

##### Expected behavior
Netdata will create them and sell them (or for free for nay guys who already contributed / will contribute to the project.

**Comment by cakrit** [comment]
We won't sell them of course!!! :) 
Let me discuss with a couple of people how we'll set this up, so that it's not a one-time thing.

**Comment by cakrit** [comment]
We actually did set this up and I forgot to mention it. 
Each month, all of us at Netdata will nominate one or more users, who we believe made a positive impact. These users will receive a small token of our appreciation. 

The first list was announced in #7133 

@jlbriston will put together something to publicize it better. I'll nominate @tioumen of course for this month's reward, but also @andrewm4894 and @agrimal just for the lovely eyes, hearts, smiley faces etc. in this ticket.
