### ISSUE TITLE
Netdata Debian package depends on freeipmi

### ISSUE THREAD

**Issue by agrimal** [netdata/netdata#6907]
Installing netdata version 1.17.191 from [https://packagecloud.io/netdata/netdata-edge](https://packagecloud.io/netdata/netdata-edge) installs the following packages on Debian 10 Buster : 

```
freeipmi
freeipmi-bmc-watchdog
freeipmi-common
freeipmi-ipmidetect
freeipmi-tools
libfreeipmi17
libipmiconsole2
libipmidetect0
libipmimonitoring6
libjudydebian1
libnetfilter-acct1
libprotobuf17
libprotoc17
libsnappy1v5
libuv1
netdata
```

I want to install netdata in several virtual machines, so i don't need the freeipmi package which pulls 9 packages.
Removing freeipmi from depencies would make netdata installing only 7 packages on Debian : 
```
libjudydebian1
libnetfilter-acct1
libprotobuf17
libprotoc17
libsnappy1v5
libuv1
netdata
```

I know you already removed cups but I can't find any thread where you talk about removing freeipmi.

**Comment by paulkatsoulakis** [comment]
Hello, i will be working on it today.
We are working on creating separate sub-packages for all non-mandatory collectors or backends

**Comment by prologic** [comment]
@agrimal Our apologies for the delay i shipping this. We have work-in-progress PR(s) to address this and we are working on getting those cleaned up, tested and merged! Please bear with us!
