### ISSUE TITLE
DBengine hanging without logging

### ISSUE THREAD

**Issue by KrisShannon** [netdata/netdata#6910]
##### Bug report summary

We have a server collecting about 16,000 dimensions (mainly due to per user cgroups)

The `page cache size` had been left at the default of 32Mb.

Netdata was repeatedly hanging and a junior admin who was looking into it ended up spending a couple of days chasing down lots of red herrings.

After we finally took some stack backtraces we could see nearly all the threads were stuck in [`sleep_usec` in `pg_cache_reserve_pages`](https://github.com/netdata/netdata/blob/v1.17.1/database/engine/pagecache.c#L252)

This was able to pinpoint the issue as not enough page cache.

Increasing `page cache size` fixed the hanging.

There was no clue in the error.log that the `page cache size` was too small.

##### OS / Environment

CloudLinux 7.6 running cPanel/WHM 11.78
208 user accounts

##### Netdata version (ouput of `netdata -V`)

netdata v1.17.1

( installed from [PackageCloud EL7 Repo](https://packagecloud.io/netdata/netdata/el/7/x86_64) )

##### Component Name

DBEngine Logging

##### Steps To Reproduce

Configure netdata to collect too many dimensions for the configured `page_cache_size`

##### Expected behavior

Some kind of warning that there are contention issues with the `page cache`.

Maybe once the failures has reached the failure ceiling then a warning would be appropriate.

**Comment by mfundul** [comment]
Thank you for reporting this issue. We will fix this as soon as possible.

**Comment by mfundul** [comment]
You can test #6911 if you like. For guidelines on dbengine configuration see [here](https://docs.netdata.cloud/database/engine/#memory-requirements).
