### ISSUE TITLE
Local node view

### ISSUE THREAD

**Issue by eglyn** [netdata/netdata#6912]
Hi everyone,

Is there a way to have a node view like netdata cloud, but on local network ?

For security reason, we don't want to upload any information from our network, but the node view seems very convenient :)

i activated the local registry, but there is only a list in the top menu where we can choose the machine, but no overview.

Thx in advance.

**Comment by ilyam8** [comment]
Hi @eglyn. No there is no way to have node view w/o netdata cloud.

If you use streaming see

> https://github.com/netdata/netdata/pull/6603

**Comment by eglyn** [comment]
thx for your answer, i m going to check that :)

**Comment by cakrit** [comment]
Hi @eglyn, 

Please send an email to info@netdata.cloud, requesting information on the "On-premise" version of netdata.cloud. We'll send you a response and keep your email on file, so we can notify you when the On-premise version of netdata.cloud is available.
