### ISSUE TITLE
Netdata capabilities

### ISSUE THREAD

**Issue by H-Sura** [netdata/netdata#6919]
##### Question summary
Hello. Is it possible to monitor only status of some services or devices? For eg. if interface is up, or if service is running. Only yes or no. Thank you.
##### OS / Environment
Gentoo Linux
##### Component Name
Alerting, status monitoring
##### Expected results
Status monitoring (eg. is interface or service up)

**Comment by ilyam8** [comment]
Hi @H-Sura 

You can disable all plugin you dont need. See `netdata.conf` `[plugins]` section.

As for 

> For eg. if interface is up

I think no, i dont think we collect `operstate`

> /sys/class/net/<iface>/operstate

> https://github.com/netdata/netdata/search?q=operstate&unscoped_q=operstate

Related issue: https://github.com/netdata/netdata/issues/531 (show static information on the dashboard)

We could add `operstate` as a var for now. Not sure is this a good idea or not.

**Comment by ilyam8** [comment]
> https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net

> Possible values are:
		"unknown", "notpresent", "down", "lowerlayerdown", "testing",
		"dormant", "up".

**Comment by ilyam8** [comment]
@vlvkobal check it, i think we could add

https://github.com/netdata/netdata/issues/6919#issuecomment-534083493

if you agree lets open a feature req

**Comment by ilyam8** [comment]
@stelfrag it looks similar to #5989

what do you think
https://github.com/netdata/netdata/issues/6919#issuecomment-534049359
?

**Comment by stelfrag** [comment]
> @stelfrag it looks similar to #5989
> 
> what do you think
> [#6919 (comment)](https://github.com/netdata/netdata/issues/6919#issuecomment-534049359)
> ?

Yes looks similar, check a condition, set variable and act on it. Good idea to consider both
