### ISSUE TITLE
How see detailed network statistic?

### ISSUE THREAD

**Issue by nicdnepr** [netdata/netdata#6923]
##### Question summary
net data show big network usage
![2019-09-23-172723_1920x1080_scrot](https://user-images.githubusercontent.com/2581487/65434446-7df7e680-de27-11e9-89f7-ea744ef5f509.png)
How can I see detailed network statistic? Like what process name is generate such big traffic

##### OS / Environment
centos 7
##### Component Name
Net Inbound

**Comment by ilyam8** [comment]
Hi @nicdnepr 

> How can I see detailed network statistic?

Check following sections on the dashboard:
 - Networking Stack
 - IPv4 Networking
 - IPv6 Networking
 - Network Interfaces


> Like what process name is generate such big traffic

It is not possible to get this info using netdata atm.

Check this

> https://github.com/raboof/nethogs
