### ISSUE TITLE
Debian package is broken

### ISSUE THREAD

**Issue by agrimal** [netdata/netdata#6925]
#### Bug report summary

Debian nightly package is broken :

-  When going to `http://server:19999` i got the following message :
  `ERROR 101: Cannot load jQuery: http://server:19999/lib/jquery-2.2.4.min.js` Dashboard is not working anymore.
- Version of package is `1.17.191` but `netdata -V` gives `netdata v1.17.1-91-nightly`

##### OS / Environment

Debian 10 Buster

```bash
root@server [~] # netdata -V
netdata v1.17.1-91-nightly
root@server [~] # dpkg -l | grep netdata
ii  netdata                        1.17.191                    amd64        real-time charts for system monitoring
root@server [~] # cat /etc/apt/sources.list.d/netdata.list 
deb https://packagecloud.io/netdata/netdata-edge/debian/ buster main
```

##### Steps To Reproduce
`apt install netdata`

##### Workaround

This solves the first problem : 
```
cp -a /usr/share/netdata/www/* /usr/share/netdata/
```

**Comment by paulkatsoulakis** [comment]
Hi @agrimal, thanks for your report.

Regarding the versioning, is something that we had to do to simplify version format for the binary packages. We intend to eventually rework our versioning scheme, but that is going to be on another iteration, as there are many dependencies to be attended.

I will check the web issue that you mention now and let you know

**Comment by paulkatsoulakis** [comment]
wow! That was a really sneaky one.
I didn't see it coming during manual testing, because of required js being cached on the browser so the broken state could not be seen.

I am sorry you experienced this @agrimal, i will be posting a fix right away.
Basically what happens is the sym-linking of the directories is not right.

**Comment by agrimal** [comment]
No problem nightlies are done for testing.
I switched to nightlies because stable install too many package, as soon as you remove freeipmi from dependencies on stable, i switch back to it.

Thanks for your quick fix

**Comment by cakrit** [comment]
Nightly build running again, will be ok in a couple of hours.

**Comment by Habetdin** [comment]
I'm using stable branch of netdata at packagecloud and upgraded netdata from 1.17 to 1.18 today. Host OS is Ubuntu 18.04 LTS.

After the upgrade, I've got the same error as the OP when trying to open netdata in my browser:
`ERROR 101: Cannot load jQuery: https://main.lyxoto.download/netdata/lib/jquery-2.2.4.min.js`

Got www directory path from full config:
```[global]
	# I'm not overriding the default value, so can't tell if did it change since the 1.17?
	# web files directory = /var/lib/netdata/www```

And fixed issue by copying missing file(s) from the path that is mentioned in the first post: `cp -a /usr/share/netdata/www/* /var/lib/netdata/www/`.

**Comment by Habetdin** [comment]
@cakrit I'm using stable branch of netdata at packagecloud and upgraded netdata from 1.17 to 1.18 today. Host OS is Ubuntu 18.04 LTS.

After the upgrade, I've got the same error as the OP when trying to open netdata in my browser:
`ERROR 101: Cannot load jQuery: https://main.lyxoto.download/netdata/lib/jquery-2.2.4.min.js`

Got www directory path from full config:
```
[global]
	# I'm not overriding the default value, so can't tell if did it change since the 1.17?
	# web files directory = /var/lib/netdata/www
```
It had some stuff in the root directory (`/var/lib/netdata/www`) but not in its subdirectories like `images` or `lib`.

At first I was about to just copy the files like in first post by doing `cp -a /usr/share/netdata/www/* /var/lib/netdata/www/`, but after checking the #6930 I've decided to remove empty directories:
```
rm -rf /var/lib/netdata/www/.well-known
rm -rf /var/lib/netdata/www/css
rm -rf /var/lib/netdata/www/fonts
rm -rf /var/lib/netdata/www/images
rm -rf /var/lib/netdata/www/lib
rm -rf /var/lib/netdata/www/static
```
And created proper symlinks:
```
ln -s /usr/share/netdata/www/.well-known /var/lib/netdata/www/.well-known
ln -s /usr/share/netdata/www/css         /var/lib/netdata/www/css
ln -s /usr/share/netdata/www/fonts       /var/lib/netdata/www/fonts
ln -s /usr/share/netdata/www/images      /var/lib/netdata/www/images
ln -s /usr/share/netdata/www/lib         /var/lib/netdata/www/lib
ln -s /usr/share/netdata/www/static      /var/lib/netdata/www/static
```

**Comment by Habetdin** [comment]
@paulkatsoulakis @cakrit Sorry for bothering, but...

After upgrading my netdata from 1.17 to 1.18 today, I've got the same error as the OP when trying to open netdata in my browser:
`ERROR 101: Cannot load jQuery: https://netdata.hostname/lib/jquery-2.2.4.min.js`

I'm using the stable branch of netdata at packagecloud and the host OS is Ubuntu 18.04 LTS.

Got www directory path from full config:
```
[global]
	# I'm not overriding the default value, so can't tell if did it change since the 1.17?
	# web files directory = /var/lib/netdata/www
```
It had some stuff in the root directory (`/var/lib/netdata/www`) but not in its subdirectories like `images` or `lib`.

At first I was about to just copy the files like in first post by doing `cp -a /usr/share/netdata/www/* /var/lib/netdata/www/`, but after checking the #6930 I've decided to remove empty directories:
```
rm -rf /var/lib/netdata/www/.well-known
rm -rf /var/lib/netdata/www/css
rm -rf /var/lib/netdata/www/fonts
rm -rf /var/lib/netdata/www/images
rm -rf /var/lib/netdata/www/lib
rm -rf /var/lib/netdata/www/static
```
To replace them with the next proper symlinks:
```
ln -s /usr/share/netdata/www/.well-known /var/lib/netdata/www/.well-known
ln -s /usr/share/netdata/www/css         /var/lib/netdata/www/css
ln -s /usr/share/netdata/www/fonts       /var/lib/netdata/www/fonts
ln -s /usr/share/netdata/www/images      /var/lib/netdata/www/images
ln -s /usr/share/netdata/www/lib         /var/lib/netdata/www/lib
ln -s /usr/share/netdata/www/static      /var/lib/netdata/www/static
```

That resolved the issue for me.

**Comment by borisdigital** [comment]
> @paulkatsoulakis @cakrit Sorry for bothering, but...
> 
> After upgrading my netdata from 1.17 to 1.18 today, I've got the same error as the OP when trying to open netdata in my browser:
>...
> That resolved the issue for me.

I'm having the very same problem here on a debian buster with stable (v1.18) packages from packagecloud. The proposed workaround seems to work fine here.
Just one question: Will this break any netdata updates?

**Comment by knatsakis** [comment]
Hi @borisdigital @Habetdin, lets follow the progress in #7067. Thanks
