### ISSUE TITLE
Netdata Debian/Ubuntu packages depend on too many packages

### ISSUE THREAD

**Issue by rda0** [netdata/netdata#6932]
Installing netdata from the new BETA repositories https://packagecloud.io/netdata/netdata/debian and https://packagecloud.io/netdata/netdata/ubuntu installs too many packages (see also  #6907).

For example on Ubuntu 18.04 bionic, apt shows:

```
+rda:~# apt show netdata
Package: netdata
Version: 1.17.1
Priority: optional
Section: net
Maintainer: Netdata Builder <bot@netdata.cloud>
Installed-Size: 32.4 MB
Depends: adduser, libcap2-bin (>= 1:2.0), lsb-base (>= 3.1-23.2), zlib1g (>= 1:1.1.4), libuuid1 (>= 2.16), libuv1 (>= 1.4.2), liblz4-1 (>= 0.0~r130), libjudydebian1, openssl, libmnl0 (>= 1.0.3-4~), libjson-c3 (>= 0.10), cups, freeipmi, libnetfilter-acct1, libprotobuf-c1, libsnappy1v5, libprotoc10, libc6 (>= 2.17), libcups2 (>= 1.7.0), libgcc1 (>= 1:3.3.1), libipmimonitoring5a (>= 1.1.5), libprotobuf10, libssl1.1 (>= 1.1.0), libstdc++6 (>= 5.2)
Homepage: https://netdata.cloud
Download-Size: 6,764 kB
APT-Manual-Installed: yes
APT-Sources: https://packagecloud.io/netdata/netdata/ubuntu bionic/main amd64 Packages
Description: real-time charts for system monitoring
 Netdata is a daemon that collects data in realtime (per second)
 and presents a web site to view and analyze them. The presentation
 is also real-time and full of interactive charts that precisely
 render all collected values.
```

where I would rather like something like:

```
Depends: libc6 (and any other essential packages)
Recommends: all other packages to enable all possible plugins
```

One can then decide to install without recommends for a minimalistic setup:

```
apt install --no-install-recommends netdata
```

Although I would not even want `cups` in Recommends. I would expect that in Suggests.

**Comment by Ferroin** [comment]
The CUPS plugin is in the process of being split out to a separate package.

The NFACCT (`libnetiflter-acct1` dependency) and IPMI (`freeimpi` and `libipmimonitoring5a` dependencies) plugins should probably get the same treatment, especially considering that both need to be SUID root to work.

As far as I know, everything else is either dependencies for the core itself, or would require complex and creative use of `dlopen()` to support operating without it.

**Comment by Ferroin** [comment]
Relevant: #6907.

Didn't notice it before commenting above about the IPMI stuff.

**Comment by rda0** [comment]
@Ferroin Thanks for the feedback.

Are you also involved in bringing it into the official Debian repos? Because I saw it in sid: https://packages.debian.org/sid/netdata. I like the construct with the metapackage, consisting of:

- dep: netdata-core
- dep: netdata-plugins-bash
- dep: netdata-web
- rec: netdata-plugins-nodejs
- rec: netdata-plugins-python

According to the [netdata-core package in sid](https://packages.debian.org/sid/netdata-core), the following dependencies are required:

```
root@phd-sid:~# apt show netdata-core
Package: netdata-core
Version: 1.17.1-1
Priority: optional
Section: net
Source: netdata
Maintainer: Lennart Weller <lhw@ring0.de>
Installed-Size: 1,648 kB
Pre-Depends: init-system-helpers (>= 1.54~)
Depends: libcap2-bin, lsb-base, libc6 (>= 2.17), libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4)
Recommends: curl
...
```

**Comment by cakrit** [comment]
cc @knatsakis

**Comment by FedericoCeratto** [comment]
@rda0 : the Debian packages are developed independently.

Optional dependencies are always preferred to mandatory ones. Netdata should made modular where possible.

**Comment by Ferroin** [comment]
The current stance on this is that while we have room to improve, we don’t currently have the manpower to work on this concretely.

Personally, I’d love to see us have separate packages for each plugin and the dashboard as well as the core and just tag all the extra stuff as recommends, but actually putting that together is not exactly trivial.

**Comment by Ferroin** [comment]
Re-labeling this as a feature request per my above comment. I plan to tackle this by deagregating the Netdata packages to a greater degree as part of the followup work to the upcoming installation/updater overhaul.
