### ISSUE TITLE
Uninstalling Netdata should not remove `netdata` user and group.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#6933]
##### Bug report summary
The uninstall process removes the netdata user and group if they exist on the system.

##### OS / Environment
All

##### Netdata version (ouput of `netdata -V`)
Current master branch, behavior has existed for quite some time.

##### Component Name
`kickstart.sh`, Debian packages, possibly other packages (haven't checked any of the RPM's)

##### Steps To Reproduce
Uninstall an existing install of Netdata.

##### Expected behavior
The `netdata` user and group are not removed by the uninstall process.

---

Fedora's packaging guide has some good info on why this is bad practice [here](https://fedoraproject.org/wiki/Packaging:UsersAndGroups#Allocation_Strategies).  Quoting the relevant part:

> **Do not remove users or groups**
We never remove users or groups created by packages. There's no sane way to check if files owned by those users/groups are left behind (and even if there would, what would we do with them?) and leaving those behind with ownerships pointing to now nonexistent users/groups may result in security issues when a semantically unrelated user/group is created later and reuses the UID/GID. Also, in some setups deleting the user/group might not be possible or/nor desirable (eg. when using a shared, remote user/group database). Cleanup of unused users/groups is left to the system administrators to take care of if they so desire.

Adding to this, you have no way to know that the user or group you're removing is the same one which you added, and orphaned files are likely to cause confusion for users in addition to the potential security issues.

We try to deal with the orphaned files issue, but we can't be sure we got everything, so it's still a potential risk, and we quite simply can't deal with any of the other issues properly.

**Comment by paulkatsoulakis** [comment]
That is interesting finding indeed @Ferroin, spot on as usual!
The recommendation does make sense indeed, i wonder why nobody bothered with it so far.

@cakrit any thoughts around this? Otherwise i can just go ahead and remove user deletion from all entry points

**Comment by Ferroin** [comment]
> I wonder why nobody bothered with it so far.

I suspect that it just hasn't been an actual issue for anybody so far.  Most users are likely to use the defaults for most of the configuration for Netdata, so it's not hugely likely that they'll have files that would be affected by this.

I actually would have brought it up sooner, but I kept forgetting to open an issue for it (I've been rather distracted lately between chaos at work and working on various personal projects).

**Comment by Thatdarkone** [comment]
I don't get it so let me ask , why would you want to keep netdata user and group if you are uninstalling netdata either for good or so you can start again.

**Comment by Ferroin** [comment]
@Thatdarkone There are a couple of issues with removing the user/group:

* We can't be sure that the `netdata` user and/or group we're trying to remove is the same one we previously added.  For all we know, Netdata could be configured to run under a different user, and the `netdata` user could be used on this system for something completely unrelated (it's not super likely, but it's not unrealistic).  Removing a user that's unrelated to us is a very bad thing, so we should try and avoid it if at all possible.
* We quite simply can't remove the user or group in some cases (not because we don't want to, but because there's literally no way for us to do it).  Network-based user databases (NIS, AD, etc) are the best example of this, as they almost always require special handling that `userdel` and `groupdel` don't do to remove users and groups, typically to help keep the system properly secured.
* Removing a user or group doesn't remove any of their files, it just removes the mapping between that user or group name and the numeric ID that everything uses to actually represent it internally.  This leads to a couple of other issues:
    * It allows for the possibility of unwanted information disclosure, which may be a serious security issue.  Because the files still exist on-disk with the old UID/GID, any new user who is added and gets assigned that UID or GID will be able to access those files.  This is particularly significant for Netdata, because a lot of the information we store is actually rather useful for at least planning further attacks against the system.
    * Any tools like `ls -l` that try to display the user name or group name associated with a given file won't be able to.  This is potentially confusing to many people, and also is a potential security issue (on any reasonably secure system, you usually want to know where any random file came from, and without a user or group name, that's much more difficult to verify).
* In the very specific case of a reinstall, you (usually) want the same UID/GID for Netdata that you had previously, as that simplifies a number of other things (for example, audit logs will be more consistent).

We kind of try to deal with the second issue, but we only remove certain predefined paths, and we can't be sure we got everything.  The other issues, however, we simply can't avoid.

**Comment by cakrit** [comment]
> @cakrit any thoughts around this? Otherwise i can just go ahead and remove user deletion from all entry points

I have no opinion on the matter and I trust @Ferroin implicitly. Let's remove the deletions.

**Comment by paulkatsoulakis** [comment]
Cool, @knatsakis could you take over this task?
I 'll be available for any help to get through, just make sure you ping me for questions and for sure for reviews

**Comment by Ferroin** [comment]
I have not checked the RPM's deeply yet, but they don't appear to be affected by this. The DEB packages appear to only do it when a purge is requested instead of a regular removal (that is, wipe out _everything_ the package added to the system), which appears to be standard practice for Debian and thus should probably be kept.

That just leaves the `netdata-uninstaller.sh` script, which I should have a PR for shortly to make the removal optional (with a default to not doing it).

**Comment by thiagoftsm** [comment]
Considering that we have `database engine` as default memory mode now, should we keep the user/group pair and the database files instead to remove all? I think this is the default pattern for databases.

**Comment by Ferroin** [comment]
> Considering that we have `database engine` as default memory mode now, should we keep the user/group pair and the database files instead to remove all? I think this is the default pattern for databases.

I was planning on making the removal of the files optional as well, with a simple question to ask about removing either all or nothing and a pair of switches to override the question.
