### ISSUE TITLE
Galera cluster status monitoring

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#6934]
##### Feature idea summary
It would be good to see WSREP cluster status and size, not just replication flow that is already present in Netdata.
For example, following parameters are missing:
`

SHOW STATUS LIKE 'wsrep_cluster_weight'
Variable_name: wsrep_cluster_weight
        Value: 1
SHOW STATUS LIKE 'wsrep_cluster_size'
Variable_name: wsrep_cluster_size
        Value: 1
SHOW STATUS LIKE 'wsrep_cluster_status'
Variable_name: wsrep_cluster_status
        Value: Primary
SHOW STATUS LIKE wsrep_local_state
Variable_name: wsrep_local_state
        Value: 4
SHOW STATUS LIKE 'wsrep_local_state_comment'
Variable_name: wsrep_local_state_comment
        Value: Synced
SHOW STATUS LIKE 'wsrep_open_transactions'
Variable_name: wsrep_open_transactions
        Value: 18
SHOW STATUS LIKE 'wsrep_connected'
Variable_name: wsrep_connected
        Value: ON
SHOW STATUS LIKE 'wsrep_local_index'
Variable_name: wsrep_local_index
        Value: 0
SHOW STATUS LIKE 'wsrep_ready'
Variable_name: wsrep_ready
        Value: ON
SHOW STATUS LIKE 'wsrep_thread_count'
Variable_name: wsrep_thread_count
        Value: 98
`
Most of these parameters are strings, so they should be displayed like status table in Netdata interface.

These parameters can be used for status monitoring, for example, when **wsrep_cluster_status** is changed, an alert should be sent to 'dba' or 'admin' contact.
Also, when node leaves the cluster or joines it (thus, **wsrep_cluster_size** is changed) an alert should be sent, too, for example, if node left the cluster, this event is critical (while joining can be just notification).

As from what we can see now, Netdata already extracts information from same variable group, so adding these parameters should also be possible, shouldn't it?

**Comment by ilyam8** [comment]
Hi @ekexcello 

Can we get all the info in one request?

**Comment by ilyam8** [comment]
Oh, i think all those values are in `SHOW GLOBAL STATUS;` response, right?

**Comment by ekexcello** [comment]
Hello Ilya,
Yes, all these variables are present in `SHOW GLOBAL STATUS;` or even in `SHOW STATUS LIKE 'wsrep_%';` output.

**Comment by ilyam8** [comment]
Nice, module executes `SHOW GLOBAL STATUS;` query, so we only need to convert (netdata understands only `int` values) and add values for these `wsrep_*` keys.

> SHOW STATUS LIKE 'wsrep_cluster_weight'
Variable_name: wsrep_cluster_weight
Value: 1

This one looks straightforward. Just a separate chart.


> SHOW STATUS LIKE 'wsrep_cluster_size'
Variable_name: wsrep_cluster_size
Value: 1

Units?

> SHOW STATUS LIKE 'wsrep_cluster_status'
Variable_name: wsrep_cluster_status
Value: Primary

What other values can be there? Secondary?

> SHOW STATUS LIKE wsrep_local_state
Variable_name: wsrep_local_state
Value: 4

Other states? 

> SHOW STATUS LIKE 'wsrep_local_state_comment'
Variable_name: wsrep_local_state_comment
Value: Synced

Other possible values?

> SHOW STATUS LIKE 'wsrep_open_transactions'
Variable_name: wsrep_open_transactions
Value: 18

This one is easy.

> SHOW STATUS LIKE 'wsrep_connected'
Variable_name: wsrep_connected
Value: ON

ON/OFF?

> SHOW STATUS LIKE 'wsrep_local_index'
Variable_name: wsrep_local_index
Value: 0

Do we need this?

> SHOW STATUS LIKE 'wsrep_ready'
Variable_name: wsrep_ready
Value: ON

ON/OFF?

> SHOW STATUS LIKE 'wsrep_thread_count'
Variable_name: wsrep_thread_count
Value: 98 

No question with it.
