### ISSUE TITLE
Slave down alert in master/slave architecture

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#6937]
Hi

I have a Master/slave architecture with slave headless mode (web and DB are hosted by master). Master trigger alerts.

I tested several strategy to know if a slave is down :
* fping : Ok it works nice but it checks if server is down not netdata agent service
* portcheck : in headless mode there is no listen port exposed by slave
* Http check : Nothing really usable in headless mode
* Stream.conf health param : Too much tcp and udp alarm are raised but not really user friendly

But I in allmetrics endpoint by exemple I could have a metric last collected time for a slave and It could be possible to know if there is a pb with data collection.

**Comment by ilyam8** [comment]
Hi @fmercier-almerys 

dup of #3931

**Comment by fmercier-almerys** [comment]
Hi I found a very nice endpoint : 
http://netdata-server:19999/host/my-slave/api/v1/alarms

The response contains the slave status : (True if available or False)
`
{
	"hostname": "my-slave",
	"latest_alarm_log_unique_id": 1568299759,
	"status": false,
	"now": 1569578522,
	"alarms": {

	}
}

`

**Comment by cakrit** [comment]
> Hi I found a very nice endpoint :
> http://netdata-server:19999/host/my-slave/api/v1/alarms
> 
> The response contains the slave status : (True if available or False)
> 
> ```
> {
> 	"hostname": "my-slave",
> 	"latest_alarm_log_unique_id": 1568299759,
> 	"status": false,
> 	"now": 1569578522,
> 	"alarms": {
> 
> 	}
> }
> ```

That's not accurate actually, that status just tells you if health is enabled or not. Just set in `[health]` `enabled=no` and you'll see it change.

**Comment by fmercier-almerys** [comment]
Health in master is Auto and on slaves it is no
So when the slave push data It seems in auto mode the status = True and is not equals False 
not relevant ?

**Comment by cakrit** [comment]
Yes, this is a hack that will work in the configuration you describe, but only there.
