### ISSUE TITLE
vsphere: x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by zaptel** [netdata/netdata#6940]
Any chance we can avoid SSL validation for vsphere module?

netdata_1  | 2019-09-24 19:29:02: go.d ERROR: vsphere[vc] error on creating vsphere client : Post https://xx.xx.xx.xx/sdk: x509: cannot validate certificate for xx.xx.xx.xx because it doesn't contain any IP SANs
netdata_1  | 2019-09-24 19:29:02: go.d ERROR: vsphere[vc] Init failed
netdata_1  | 2019-09-24 19:29:02: go.d WARNING: main[main] vsphere[vc]: autodetection failed

**Comment by ilyam8** [comment]
> Any chance we can avoid SSL validation for vsphere module?

Hi, have you tried `tls_skip_verify` option?

https://github.com/netdata/go.d.plugin/blob/d0c1d470d02638dd2e132a7f864e0d9ce72f08b8/config/go.d/vsphere.conf#L100-L103

**Comment by zaptel** [comment]
Thank you and sorry for being lazy to read config file :( 
Seem working properly.

<img width="1288" alt="Untitled 3" src="https://user-images.githubusercontent.com/36852830/65546646-356c2600-df18-11e9-8547-684d19bbf085.png">
