### ISSUE TITLE
[DEBIAN] undefined reference to `OPENSSL_init_ssl'

### ISSUE THREAD

**Issue by mickae1** [netdata/netdata#6943]
i Tried the last version of netdata-1.17.1 .

When I tried to compile netdata with ./netdata-installer.sh .

I got the error:

/tmp/cc9hLv8t.ltrans3.ltrans.o: In function `security_init':
cc9hLv8t.ltrans3.o:(.text+0x27fa): undefined reference to `OPENSSL_init_ssl'
/tmp/cc9hLv8t.ltrans2.ltrans.o: In function `security_process_accept':
cc9hLv8t.ltrans2.o:(.text+0x5364): undefined reference to `SSL_is_init_finished'
/tmp/cc9hLv8t.ltrans2.ltrans.o: In function `security_initialize_openssl_client.lto_priv.210':
cc9hLv8t.ltrans2.o:(.text+0x548a): undefined reference to `TLS_client_method'
/tmp/cc9hLv8t.ltrans13.ltrans.o: In function `socket_listen_main_static_threaded':
cc9hLv8t.ltrans13.o:(.text+0x10ae): undefined reference to `TLS_server_method'
collect2: error: ld returned 1 exit status

I have already installed the required package :

 apt-get install zlib1g-dev uuid-dev libuv1-dev liblz4-dev libjudy-dev libssl-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl python

The following NEW packages will be installed:
  autoconf-archive autogen autogen-doc guile-2.0-libs libgc1c2 libjudy-dev libjudydebian1 liblz4-1 liblz4-dev libmnl-dev libopts25 libopts25-dev libuv1 libuv1-dev

**Comment by cakrit** [comment]
Please provide OS name/version and also libssl-dev version.

**Comment by mickae1** [comment]
Distributor ID: Debian
Description:    Debian GNU/Linux 8.8 (jessie)
Release:        8.8
Codename:       jessie

libssl:
Get:1 http://security.debian.org/ jessie/updates/main libssl-dev armhf
1.0.1t-1+deb8u11


Thanks,

**Comment by paulkatsoulakis** [comment]
Hello @mickae1, sorry you bumped into troubles.
I think you probably haven't pulled in the right dependencies or you have done something with your repos.

When i tried your command, as you pasted it on a clean debian 8 and 8.8, it failed:
```
root@7be8dc20ac5e:/netdata# apt-get install zlib1g-dev uuid-dev libuv1-dev liblz4-dev libjudy-dev libssl-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl python
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libuv1-dev
```

That is because Debian jessie doesn't have libuv1 that we need for DB engine, but is not required for a successful netdata installation. 
So probably you didn't run that command or you run an extra command you did not paste here or you have done something with your repos because i see libuv1 is found on your machine.

Our kickstart.sh installation though, has a clever way to decide on dependencies transparently.
I would recommend to run `bash <(curl -sS https://my-netdata.io/kickstart.sh)` as per the instructions [here](https://docs.netdata.cloud/packaging/installer/#one-line-installation).

Should you wish to pull the latest **stable** version using kickstart instead of latest nightly, run `bash <(curl -sS https://my-netdata.io/kickstart.sh) --stable-channel`

**Note**: Before you run the above script, make sure you run an `apt-get update all` to make sure repositories are synced.

**Comment by mickae1** [comment]
Ok, I tried : 

bash <(curl -sS https://my-netdata.io/kickstart.sh) --stable-channel


And I got those errors:

```
  GEN      netdata
/tmp/ccdL2w0g.ltrans3.ltrans.o: In function `security_init':
ccdL2w0g.ltrans3.o:(.text+0x27fa): undefined reference to `OPENSSL_init_ssl'
/tmp/ccdL2w0g.ltrans2.ltrans.o: In function `security_process_accept':
ccdL2w0g.ltrans2.o:(.text+0x5364): undefined reference to `SSL_is_init_finished'
/tmp/ccdL2w0g.ltrans2.ltrans.o: In function `security_initialize_openssl_client.lto_priv.210':
ccdL2w0g.ltrans2.o:(.text+0x548a): undefined reference to `TLS_client_method'
/tmp/ccdL2w0g.ltrans13.ltrans.o: In function `socket_listen_main_static_threaded':
ccdL2w0g.ltrans13.o:(.text+0x10ae): undefined reference to `TLS_server_method'
collect2: error: ld returned 1 exit status
Makefile:2605: recipe for target 'netdata' failed
make[2]: *** [netdata] Error 1
make[2]: Leaving directory '/tmp/netdata-kickstart-3DeHIt/netdata-v1.17.1'
Makefile:3005: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/netdata-kickstart-3DeHIt/netdata-v1.17.1'
Makefile:1630: recipe for target 'all' failed
make: *** [all] Error 2
 FAILED

 FAILED

 ABORTED  netdata-installer.sh exited with error
```

**Comment by mickae1** [comment]
Obviously, It's a problem of OpenSSL, I've compiled manually openssl 1.1.1 .... maybe it's the problem ?

`ldconfig -p|grep ssl
        libssl3.so (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libssl3.so
        libssl.so.1.1 (libc6,hard-float) => /usr/local/lib/libssl.so.1.1
        libssl.so.1.1 (libc6,hard-float) => /usr/lib/libssl.so.1.1
        libssl.so.1.0.0 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0
        libssl.so (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libssl.so
        libssl.so (libc6,hard-float) => /usr/local/lib/libssl.so
        libgnutls-openssl.so.27 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libgnutls-openssl.so.27`

**Comment by mickae1** [comment]
ldconfig -p|grep crypto
        libopencryptoki.so.0 (libc6,hard-float) => /usr/lib/libopencryptoki.so.0
        libk5crypto.so.3 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libk5crypto.so.3
        libcrypto.so.1.1 (libc6,hard-float) => /usr/local/lib/libcrypto.so.1.1
        libcrypto.so.1.1 (libc6,hard-float) => /usr/lib/libcrypto.so.1.1
        libcrypto.so.1.0.0 (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
        libcrypto.so (libc6,hard-float) => /usr/lib/arm-linux-gnueabihf/libcrypto.so
        libcrypto.so (libc6,hard-float) => /usr/local/lib/libcrypto.so

**Comment by mickae1** [comment]
too bad that I can't  do ldd /tmp/ccRhySBj.ltrans3.ltrans.o to see which lib it try to reach

**Comment by mickae1** [comment]
this the makefile config for openssl :
LIBCRYPTO_CFLAGS = -I/usr/local/include
LIBCRYPTO_LIBS = -L/usr/local/lib -lcrypto

**Comment by mickae1** [comment]
Ok, it's my fault, libcrypto.so is the openssl 1.1.1 version. I'm going to fix that.

**Comment by ilyam8** [comment]
@cakrit i think we should close this one in favor of https://github.com/netdata/netdata/issues/7016 

or vice versa

am i missing something @cakrit? why reopen?

**Comment by cakrit** [comment]
It was because he commented here. Ok, let's proceed in #7017

**Comment by jai247** [comment]
I am facing the same error in Amazon Linux while installing and OpenSSL version is 1.1.1. Is any update on this issue?

/tmp/cckwT1Yo.ltrans4.ltrans.o: In function `security_process_accept':
<artificial>:(.text+0xcce2): undefined reference to `SSL_is_init_finished'
/tmp/cckwT1Yo.ltrans4.ltrans.o: In function `security_initialize_openssl_client.lto_priv.237':
<artificial>:(.text+0xce45): undefined reference to `TLS_client_method'
/tmp/cckwT1Yo.ltrans8.ltrans.o: In function `security_init':
<artificial>:(.text+0x5161): undefined reference to `OPENSSL_init_ssl'
/tmp/cckwT1Yo.ltrans7.ltrans.o: In function `socket_listen_main_static_threaded':
<artificial>:(.text+0x3873): undefined reference to `TLS_server_method'
/tmp/cckwT1Yo.ltrans11.ltrans.o: In function `rrdeng_store_metric_init':
<artificial>:(.text+0x3270): undefined reference to `EVP_MD_CTX_new'
<artificial>:(.text+0x32da): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status

**Comment by thiagoftsm** [comment]
Hi @jai247,

What is your Netdata version?

Best regards!

**Comment by jai247** [comment]
Hi @thiagoftsm,
Thanks for the reply.
Netdata version:  netdata-v1.19.0

**Comment by thiagoftsm** [comment]
@jai247 I remember we had different issues like this, in normal situation the problems happen because:

1 - The shared libraries are different version;
2 - OpenSSL and LibreSSL have more or less the same function name, but the code are not the same.

In normal situation, case you compile Netdata this could be solved, the problems happen more frequently when we get the binary from the internet. Did you use `kickstart` to install Netdata?
@Ferroin and @prologic , please, can you take a look in this case? I am months without to touch AWS.

**Comment by jai247** [comment]
@thiagoftsm Yes, I have tried with using **kickstart** same error.
@Ferroin @prologic 
/tmp/cckwT1Yo.ltrans4.ltrans.o: In function security_process_accept': <artificial>:(.text+0xcce2): undefined reference to SSL_is_init_finished'
/tmp/cckwT1Yo.ltrans4.ltrans.o: In function security_initialize_openssl_client.lto_priv.237': <artificial>:(.text+0xce45): undefined reference to TLS_client_method'
/tmp/cckwT1Yo.ltrans8.ltrans.o: In function security_init': <artificial>:(.text+0x5161): undefined reference to OPENSSL_init_ssl'
/tmp/cckwT1Yo.ltrans7.ltrans.o: In function socket_listen_main_static_threaded': <artificial>:(.text+0x3873): undefined reference to TLS_server_method'
/tmp/cckwT1Yo.ltrans11.ltrans.o: In function rrdeng_store_metric_init': <artificial>:(.text+0x3270): undefined reference to EVP_MD_CTX_new'
:(.text+0x32da): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status

**Comment by Ferroin** [comment]
> @thiagoftsm Yes, I have tried with using **kickstart** same error.
> @Ferroin @prologic
> /tmp/cckwT1Yo.ltrans4.ltrans.o: In function security_process_accept': :(.text+0xcce2): undefined reference to SSL_is_init_finished'
> /tmp/cckwT1Yo.ltrans4.ltrans.o: In function security_initialize_openssl_client.lto_priv.237': :(.text+0xce45): undefined reference to TLS_client_method'
> /tmp/cckwT1Yo.ltrans8.ltrans.o: In function security_init': :(.text+0x5161): undefined reference to OPENSSL_init_ssl'
> /tmp/cckwT1Yo.ltrans7.ltrans.o: In function socket_listen_main_static_threaded': :(.text+0x3873): undefined reference to TLS_server_method'
> /tmp/cckwT1Yo.ltrans11.ltrans.o: In function rrdeng_store_metric_init': :(.text+0x3270): undefined reference to EVP_MD_CTX_new'
> :(.text+0x32da): undefined reference to `EVP_MD_CTX_free'
> collect2: error: ld returned 1 exit status

This is an ABI mismatch.

Do you have multiple versions of OpenSSL installed, possibly a local build of 1.1.x? We currently have issues handling that in the build. See #7016 for details.

**Comment by prologic** [comment]
In the meantime it _might_ be possible to build the version of openSSL we depend on and install it in a custom path and use `LD_LIBRARY_PATH`?

**Comment by Ferroin** [comment]
> In the meantime it _might_ be possible to build the version of openSSL we depend on and install it in a custom path and use `LD_LIBRARY_PATH`?

Possibly, but I'd like to avoid hacks like this if possible.

Especially since we're pushing to have all new installs using binary packages whenever possible (so this won't be an issue on Debian anymore unless users explicitly build locally).

**Comment by prologic** [comment]
I mostly meant only as a temporary work-around for @mickae1 :)

**Comment by mickae1** [comment]
@prologic I've still the same problem, any idea ? 

#10076

**Comment by thiagoftsm** [comment]
> @prologic I've still the same problem, any idea ?
> 
> #10076

@Ferroin , please, take a look on this.
