### ISSUE TITLE
Custom Alarms not detected

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#6949]
Hi

I added some plugins as Mongodb, fping etc and they provide default alarm preconfigured and it works.
I have a Master / slave architecture with slave running in headless mode.
If want to override a default alarm on a slave or add a new one copying a .conf file in health.d folder (or with edit-config script) the alarm is not detected. I can not see it on the slave dashboard and any override of the config of a default alarm is not taking into account.
No problem on master
No problem for default alarm on each slave

Is it a bug or I forget some netdata configuration .?

**Comment by ilyam8** [comment]
Hi @fmercier-almerys 

> If want to override a default alarm on a slave or add a new one copying a .conf file in health.d folder (or with edit-config script) the alarm is not detected.

Did you check `error.log`?

Keep in mind you need reload health configuration after changes, see

> https://docs.netdata.cloud/health/#health-configuration-reference

Simple netdata service restart will do too

**Comment by fmercier-almerys** [comment]
Ok So I have no error but I can notice If I override the master alarm config it is visible on slaves.
On a slave I have elasticsearch so to configure alarm I must set param on the master
slaves with elasticsearch plugin use master ES alarm conf.
But in the case where I want to add a CPU alarm only on One slave how can do it ?
Seems in headless mode alarm config must be set on the master ?
