### ISSUE TITLE
How to create New Alarm with New role

### ISSUE THREAD

**Issue by yoongacme** [netdata/netdata#6959]
##### Question summary
How I create a new alarm with a new role? for example i had created an alarm is related one folder disk storage usage by default the role is under sysadmin, i want to change the role so i can send the notification with different email when the alarm is trigger 
##### OS / Environment
Freenas

**Comment by ilyam8** [comment]
Hi @yoongacme 

Did you check alarms wiki page?

> https://docs.netdata.cloud/health/notifications/#netdata-alarm-notifications

**Comment by yoongacme** [comment]
yes, i had explore the disks.conf to trigger a new alarm, but the "to" line i would like to create a new role which mean a new group to confirm the email notification sending to right person

**Comment by ilyam8** [comment]
@yoongacme according [wiki page](https://docs.netdata.cloud/health/notifications/#netdata-alarm-notifications) you need:
 - edit it on your system run `/etc/netdata/edit-config` `health_alarm_notify.conf`
 - create your [recipient email](https://github.com/netdata/netdata/blob/master/health/notifications/health_alarm_notify.conf#L205)
 - confiure your [role](https://github.com/netdata/netdata/blob/6acaac795bb665d2711b3625a473799712d38ca6/health/notifications/health_alarm_notify.conf#L803-L809)
 - use new role in `to`


See how to test notifications

> https://docs.netdata.cloud/health/notifications/#testing-notifications

**Comment by cakrit** [comment]
I'm adding a short clarification command in #6961. I think it will help you @yoongacme 
Let us know if you still can't figure it out.

**Comment by yoongacme** [comment]
@cakrit  Thanks for you help, but the mail still send to the root user mail, and i found the alarm is stick with the sysadmin
![image](https://user-images.githubusercontent.com/55829982/65755480-c4aa5100-e145-11e9-953a-c7e9b4273978.png)

and below is the code that i had add on disks.conf
template: disk_space.mnt_FTP_yoong
      on: disk.space
    calc: $used * 100 / ($avail + $used)
   every: 1m
    warn: $this > 80
    crit: $this > 95
  repeat: warning 120s critical 10s
      to: yoong

and here is the command that i set send the email to others

role_recipients_email[yoong]="${jslee@acme.my}"
role_recipients_pushover[yoong]="${DEFAULT_RECIPIENT_PUSHOVER}"
role_recipients_pushbullet[yoong]="${DEFAULT_RECIPIENT_PUSHBULLET}"
role_recipients_telegram[yoong]="${DEFAULT_RECIPIENT_TELEGRAM}"
role_recipients_slack[yoong]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_alerta[yoong]="${DEFAULT_RECIPIENT_ALERTA}"
role_recipients_flock[yoong]="${DEFAULT_RECIPIENT_FLOCK}"
role_recipients_discord[yoong]="${DEFAULT_RECIPIENT_DISCORD}"
role_recipients_hipchat[yoong]="${DEFAULT_RECIPIENT_HIPCHAT}"
role_recipients_twilio[yoong]="${DEFAULT_RECIPIENT_TWILIO}"
role_recipients_messagebird[yoong]="${DEFAULT_RECIPIENT_MESSAGEBIRD}"
role_recipients_kavenegar[yoong]="${DEFAULT_RECIPIENT_KAVENEGAR}"
role_recipients_pd[yoong]="${DEFAULT_RECIPIENT_PD}"
role_recipients_custom[yoong]="${DEFAULT_RECIPIENT_CUSTOM}"

**Comment by cakrit** [comment]
`${jslee@acme.my}` is trying to get the value of the variable `jslee@acme.my`, which obviously wasn't your intention. What is happening is that resolves to an empty string, so you get the default recipient, i.e. root. You just put that back to `DEFAULT_RECIPIENT_EMAIL`, set `DEFAULT_RECIPIENT_EMAIL=jslee@acme.my` and you're done.
