### ISSUE TITLE
Notification redirect URL error

### ISSUE THREAD

**Issue by Thatdarkone** [netdata/netdata#6963]
##### Question summary

Clicking on email notification link "View Netdata" redirects to an error page displaying "File does not exist, or is not accessible: /usr/share/netdata/web/alarms/redirect" 

the alarms/redirect sub-dir does not in fact exists , does it need to be created manually ?
all files under /usr/share/netdata/web are owned by netdata user

Centos 7

Netdata version 1.16
##### Expected results

See the dashboard and charts that trigger the alarm

**Comment by cakrit** [comment]
Hi @Thatdarkone,

It looks like you've modified the `cloud base url` in `netdata.conf` to your host. This isn't a valid configuration and you will never get Netdata to work properly like this. If you don't want to use the netdata registry (which is gradually being replaced with netdata.cloud), what you want to do is [run your own registry](https://docs.netdata.cloud/registry/#run-your-own-registry). We will also eventually provide a way to run netdata.cloud on premise. If you're interested in receiving news on the on-premise version, you can send an email to info@netdata.cloud and we'll add you to the list we maintain.

**Comment by Thatdarkone** [comment]
So i configured my own registry and it seems to work but you the redirection produces a jquery ERROR with the following message : "**ERROR 101: Cannot load jQuery: http://myserver:19999/lib/jquery-2.2.4.min.js"**

I then have to reload the page for the redirection to work
How do i get past that first annoying error

**Comment by ilyam8** [comment]
Closing due to no answer from @Thatdarkone
