### ISSUE TITLE
Kickstart.sh doesn't work for CentOS 8 & RHEL 8

### ISSUE THREAD

**Issue by rirze** [netdata/netdata#6967]
##### Bug report summary
Running the `kickstart.sh` on CentOS 8 fails on 'Installation of required packages'.

```
/etc/os-release information:
NAME            : CentOS Linux
VERSION         : 8 (Core)
ID              : centos
ID_LIKE         : rhel fedora
VERSION_ID      : 8

We detected these:
Distribution    : centos
Version         : 8
Codename        : 8 (Core)
Package Manager : install_yum
Packages Tree   : centos
Detection Method: /etc/os-release
Default Python v: 2

This system is receiving updates from Red Hat Satellite or Spacewalk server.
Last metadata expiration check: 2:42:06 ago on Fri Sep 27 14:58:16 2019.
No match for argument: Judy-devel
No match for argument: MySQL-python
No match for argument: autoconf-archive
No match for argument: autogen
No match for argument: libmnl-devel
No match for argument: libuv-devel
No match for argument: python
There are following alternatives for "python": python2, python36
No match for argument: python-psycopg2



We are very sorry!

Installation of required packages failed.

What to do now:

1. Make sure your system is updated.
Most of the times, updating your system will resolve the issue.


2. If the error message is about a specific package, try removing
that package from the command and run it again.
Depending on the broken package, you may be able to continue.


3. Let us know. We may be able to help.
Open a github issue with the above log, at:


https://github.com/firehol/netdata/issues                                                                                             
```
##### OS / Environment
CentOS 8
##### Netdata version (ouput of `netdata -V`)
1.10.0 (I am limited to this version due to company policies. Version should be irrelevant to this issue) 
##### Component Name
Installation scripts
##### Steps To Reproduce
`bash kickstart.sh all --non-interactive`
##### Expected behavior
Installation should succeed.

**Comment by paulkatsoulakis** [comment]
Hello @rirze, thank you for your report! I am sorry to hear you faced problems.
I 'll have a look on the matter and let you know, it just got released officially [last week](https://wiki.centos.org/About/Building_8) and we should have done our exercises to make sure it works.

**Comment by paulkatsoulakis** [comment]
@rirze i think you may be looking at an issue related to a really outdated version.

I would recommend that if you can't use the latest release of netdata, to use either our [binary distributions](https://docs.netdata.cloud/packaging/installer/#binary-packages) or the [static binary](https://docs.netdata.cloud/packaging/installer/#linux-64bit-pre-built-static-binary), which ever complies better to your policy.   

If it is absolutely necessary to work with 1.10.0, you can try the [static binary](https://github.com/netdata/netdata/releases/tag/v1.10.0) from that release

**Comment by rirze** [comment]
Thanks, I will try that and get back to you.

**Comment by perryk** [comment]
Same troubles for me using Centos 8 and kickstart.sh from the latest master branch.

I have EPEL-8 enabled, however these in particular look to not be found:

```
No match for argument: Judy-devel
No match for argument: MySQL-python
No match for argument: libuv-devel
No match for argument: python-psycopg2
```

Packages exist for python2 and python3, however not for one named "python" .  The alternatives command however can be used to set either 2 or 3.

Clearly Centos 8 is pretty new, just adding in a +1 to say I'm not able to use Kickstart.sh either.

**Comment by rirze** [comment]
The static installer works, although with a lot of changes to our current workflow. While this is okay for the short term, it would be relieving if there were corresponding packages for the maintenance of the service.

I'll be keeping this issue open so that may be resolved.

**Comment by paulkatsoulakis** [comment]
Regarding the kickstart installer, the issue raised on Cent OS 8 is the fact that python 2 package is no longer named "python", obviously due to the upcoming deprecation of version 2 they want to force users to be aware of this change.

We will have to change our dependency management script to facilitate that adjustment of the package name.  The rest of the packages, libuv-devel and Judy-devel are not blocking for the netdata install, but it is an issue because we lose the DB engine capability.

@mfundul can you provide some insights how we could fetch the source package for those two on CentOS 8? It seems that only runtimes are available through binary packages for this version, unless they have moved the -devels to some repo that i can't find.  Thanks!

**Comment by paulkatsoulakis** [comment]
Not to forget to mention the rest of the packages that are also missing btw autoconf-archive, autogen, libmnl-devel and MySQL-python, i still haven't found what is the state for those.

**Comment by mfundul** [comment]
I've looked for libuv-devel in epel, elrepo and rpmfusion with no luck.

**Comment by mfundul** [comment]
https://lwn.net/Articles/796202/

```
## Known RHEL-8 packages missing -devel
* libblueray-devel
* liba52-devel
* libXvMC-devel
* libdvdnav-devel
* gfbgraph-devel
* libuv-devel
* rest-devel
* qgpgme-devel
```

**Comment by paulkatsoulakis** [comment]
interesting stuff, so they have split up packages differently on rhel 8, which i assume is inherited on Cent OS 8 too.
Details: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/package_manifest/codereadybuilder-repository

**Comment by wccropper** [comment]
The code ready packages (autogen/autoconf-archive) are in the CentOS-PowerTools.repo, just enable it. But there are still missing packages :(

**Comment by guaguasi** [comment]
Any updates on this?

**Comment by tzikis** [comment]
For what it's worth, I get the same error when trying the auto-installer for the latest version on CENTOS 6:
```
configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.
 FAILED


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues
```

Installing with the precompiled x64 binaries worked fine

**Comment by guaguasi** [comment]
@tzikis That's expected. If you read the documentation in the prepare your system section, you'll see that CentOS 6 requires another repository for `libuv`

https://docs.netdata.cloud/packaging/installer/#prepare-your-system

**Comment by tzikis** [comment]
@guaguasi yes and no. it makes sense and i see that now, but at the same time i was using the automated installer so in theory, that should have taken care of it automagically ;)

**Comment by Ferroin** [comment]
Quick notes on this:

* CentOS 8 changed naming for the Python packages. The relevant scripts that handle installing deps and were choking on this have already been updated on our end.
* CentOS 8 is currently missing libuv-devel ([upstream bug report](https://bugs.centos.org/view.php?id=16826)), which is a hard dependency for building Netdata. You can work around this by installing the [OKay repository](https://okay.network/blog-news/rpm-repositories-for-centos-6-and-7.html) which includes a working libuv-devel package.
* CentOS 8 is currently missing libmnl-devel ([upstream bug report](https://bugs.centos.org/view.php?id=16832)), which is a required dependency for the NFACCT plugin. You can work around this by disabling the NFACCT plugin at configure time (should happen automatically).

**Comment by Ferroin** [comment]
After further digging, I've determined that this is fallout from RedHat making a rather questionable choice to not ship most of the `-devel` packages because they don't want to deal with tickets asking for support for them when they officially don't support them.

Further info: https://lists.centos.org/pipermail/centos-devel/2019-November/018082.html

I'm not sure there's any way we can get this working reliably without switching to pulling SRPMs for all of our deps and building them ourselves. On the packaging side that may be acceptable, but I'm not sure I would want to see that in te install script given both how long it would take and how much it would change (and potentially break) the system it's being run on.

**Comment by guaguasi** [comment]
@Ferroin After enabling the PowerTools repo, I think the only two packages I was missing was Judy-devel and libuv-devel which I rebuilt myself.

That said, you guys made a change to the kickstart.sh script that forces python2 to be installed. Why? Is that necessary for something? No option I could find would prevent that from happening. I ended up symlinking the python3 binary, which I believe is the system default now, to python which got around it. Everything seems to be working fine. When the CentOS 8 python2 workaround wasn't in place, I just used the netdata python plugin config flag to specify the location of the python3 binary (without symlinking) and everything seemed to work fine as well.

Forcing python2 seems to just add unnecessary packages.

Am I missing something?

**Comment by Ferroin** [comment]
> That said, you guys made a change to the kickstart.sh script that forces python2 to be installed. Why? Is that necessary for something? No option I could find would prevent that from happening. I ended up symlinking the python3 binary, which I believe is the system default now, to python which got around it. Everything seems to be working fine. When the CentOS 8 python2 workaround wasn't in place, I just used the netdata python plugin config flag to specify the location of the python3 binary (without symlinking) and everything seemed to work fine as well.
>
> Forcing python2 seems to just add unnecessary packages.
>
> Am I missing something?

CentOS 8 doesn't have any way (at least that I saw) to just depend on 'python' without specifying a version, so the script had to be updated to pull in _something_ if Python for some reason wasn't installed. That, plus them not installing things a 'python' _or_ 'python3' symlink (like they should be) resulted in deciding on Python 2 as the dep because it was minimal work to get it working. I do plan to revisit this soon however and hopefully figure out a way to get it working with Python 3.6 on CentOS.

**Comment by guaguasi** [comment]
I don't think CentOS works without python as it is used for yum/dnf.

That being said, I believe you can check dependency with the `platform-python` package (https://i.imgur.com/BizWR2L.png). yum/dnf also use it as the "environment" python: `#!/usr/libexec/platform-python`. I don't know why it's not in the PATH as it and the `/usr/bin/python3` package both eventually end up linked to `/usr/libexec/platform-python3.6` (https://i.imgur.com/IoLhKbd.png)

Not sure how it would affect the pv variable.

**Comment by lkacso** [comment]
Hi,
I ve run the following commands but still no luck:

yum -y install python2
rpm -ivh http://repo.okay.com.mx/centos/8/x86_64/release/okay-release-1-3.el8.noarch.rpm
sudo yum config-manager --set-enabled PowerTools
sudo yum install 'dnf-command(config-manager)'
sudo yum config-manager --set-enabled PowerTools
sudo yum update

I get an error for Judy-devel

yum install Judy-devel autoconf-archive autogen libmnl-devel libuv-devel lz4-devel openssl-devel 
Last metadata expiration check: 0:18:40 ago on Wed Jan  8 12:18:58 2020.
No match for argument: Judy-devel
Error: Unable to find a match

Any hint what can I do about it?
Still the same error

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues
 

Running CentOS Linux release 8.0.1905 (Core)

**Comment by Ferroin** [comment]
@lkacso There's nothing we can do right now, it's an upstream issue with CentOS 8 resulting from them blindly following RHEL 8's poor design choices. They're in theory aware of the issues this is causing (it's not just Netdata, but a bunch of other stuff just can't be built on CentOS 8 right now). You can track progress on [the upstream bug report](https://bugs.centos.org/view.php?id=16492) covering this (the name is misleading, it's functionally a meta-issue for all the missing `-devel` packages).

**Comment by Ferroin** [comment]
Further clarification regarding this:

With the OKay repository included, the following packages are still missing on CentOS 8:

* Judy-devel
* autoconf-archive
* libmnl-devel

And the following are provided by the OKay repository, but aren't in base CentOS 8 even with EPEL:

* autogen
* libuv-devel

**Comment by prologic** [comment]
I _have_ to wonder how folks are expected to do any kind of Development on RHEL 8 / CentOS 8 ? I mean we're going to have to figure this out ourselves and we intend to solve many "build" issues by providing Binary Packages in general (See: #7826)

I _think_ a better upstream bug report to link to is this one:

- https://bugs.centos.org/view.php?id=16626

**Comment by Millificent** [comment]
Sorry I logged this as a separate issue. Is it still broke?

**Comment by prologic** [comment]
Sorry I should wait until all the PR(s) listed here are merged before I let Github Close it by Merging :)

**Comment by prologic** [comment]
> Sorry I logged this as a separate issue. Is it still broke?

We're pretty close :) PR(s) merging soon!

**Comment by Millificent** [comment]
Is there a manual way to do it rn or best waiting for auto installer? (sorry)

**Comment by prologic** [comment]
> Is there a manual way to do it rn or best waiting for auto installer? (sorry)

Yes!

See this initial `Dockerfile.centos8`:

```sh
FROM centos:8

#
# Install Build Dependencies
#

# Enable config-manager (NEW)
RUN yum install -y 'dnf-command(config-manager)'

# Enable PowerTools (NEW)
RUN yum config-manager --set-enabled PowerTools

# Enable EPEL (copied from docs)
RUN yum install -y epel-release

# Install Repo for libuv-devl (NEW)
RUN yum install -y https://extras.getpagespeed.com/release-el8-latest.rpm

# Update yum (copied from docs)
RUN yum update -y

# Install Devel Packages (copied from docs)
RUN yum install -y autoconf automake curl gcc git libmnl-devel libuuid-devel \
	               openssl-devel make nc pkgconfig zlib-devel

# Install Judy-Devel directly (NEW)
# XXX: dnf --enablerepo=PowerTools install Judy-devel (FAILS)
# See: https://centos.pkgs.org/8/centos-powertools-x86_64/Judy-devel-1.0.5-18.module_el8.1.0+217+4d875839.x86_64.rpm.html
RUN yum install -y http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/Judy-devel-1.0.5-18.module_el8.1.0+217+4d875839.x86_64.rpm

# Install libuv-devel (NEW)
RUN yum install -y libuv-devel

# Install python3 (NEW)
RUN yum install -y python3

# Copy Sources (TESTING)
WORKDIR /netdata
COPY . .

# Build it (TESTING)
CMD ["./netdata-installer.sh"]
```

This is also documented in #7890 

Take special note of the `(NEW)` comments above.

**Comment by hyperxpro** [comment]
`http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/Judy-devel-1.0.5-18.module_el8.1.0+217+4d875839.x86_64.rpm` is now returning HTTP Status: 404.
