### ISSUE TITLE
Improve API documentation for `api/v1/alarms`

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6968]
##### Feature idea summary
The response model for the `alarms` call isn't documented in our Swagger documentation. We need to add descriptions for each returned value. See the `data` response for an example.

##### Expected behavior
Explain every variable returned in the JSON. The fuzzer will report tests pass for negative and positive tests against the endpoint.

**Comment by thiagoftsm** [comment]
While I was reviewing the PR 7012 I notice that it will be necessary to do updates in the file `web/api/netdata-swagger.yaml` that are related to the alarm, so I am bringing the comments that I wrote there to here for it be fixed when the new PR that has relationship with alarm is created.

- Variable `latest_alarm_log_unique_id:` : The alarm log is not "only" int32 it is unsigned int 32, please see database/rrdcalc.cfunctionrrdcalc_get_unique_id`.
- Variable `now`: Now it is not an int32, now is the current timestamp that is time_t, I think it is more safe to say it is unsigned int 64 bits, for more details, please see health/health_json.c function health_alarms2json and libnetdata/clocks/clocks.c function now_realtime_sec()
- Variable `id` : The id is unsigned long, so it will be int32 if and only if you are working on 32 bits computer.
- Variable `last_status_change:` : please, this variable has the same pattern described for the other time_t variables, can you change it?
- Variable `last_updated` : please, this variable has the same pattern described for the other time_t variables, can you change it?
- Variable `next_update` : please, this variable has the same pattern described for the other time_t variables, can you change it?
- Variable `delay_multiplier` : Delay multiplier is a float value not an int32, please, change it.
- Variable `delay_up_to_timestamp` : please, this variable has the same pattern described for the other time_t variables, can you change it?
- Variable `db_after` : This is unsigned long, please, can you change it?
- Variable `db_before` : This is unsigned long, please, can you change it? All the corrections asked here can be confirmed in the file health/health_json.c in the function health_rrdcalc2json_nolock

For alarm_log_entry the following changes are necessary:
- Variable `unique_id`: This is unsigned int32, please, can you change it?
- Variable `alarm_id `: This is unsigned int32, please, can you change it?
- Variable `alarm_event_id` : This is unsigned int32, please, can you change it?
- Variable `exec_run` : This is unsigned int32, please, can you change it?
- Variable `when`: This is time, so it follows the rules for time_t and it is defined as unsigned long, please, can you change it?
- Variable `duration`: This is time, so it follows the rules for time_t and it is defined as unsigned long, please, can you change it?
- Variable `non_clear_duration`: This is time, so it follows the rules for time_t and it is defined as unsigned long, please, can you change it?
-  Variable `non_clear_duration`: This is time, so it follows the rules for time_t and it is defined as unsigned long, please, can you change it?
- Variable `delay_up_to_timestamp` : This is time, so it follows the rules for time_t and it is defined as unsigned long, please, can you change it?
- Variable `updated_by_id` : this is unsigned int32, please, can you change it?
- Variable `updates_id` : this is unsigned int32, please, can you change it?
- There is a missed variable before silenced there is another variable called last_repeat, please, add it. You can check this inside file health/health_json.c in the function health_alarm_entry2json_nolock.
-

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
