### ISSUE TITLE
Deadlock defect introduced in database

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#6969]
##### Bug report summary

A new defect was detected by Coverity Scan:
```
** CID 349552:  Program hangs  (ORDER_REVERSAL)
/database/rrddim.c: 404 in rrddim_add_custom()


________________________________________________________________________________________________________
*** CID 349552:  Program hangs  (ORDER_REVERSAL)
/database/rrddim.c: 404 in rrddim_add_custom()
398         }
399     
400         if(unlikely(rrddim_index_add(st, rd) != rd))
401             error("RRDDIM: INTERNAL ERROR: attempt to index duplicate dimension '%s' on chart '%s'", rd->id, st->id);
402     
403         if(host->alarms_with_foreach || host->alarms_template_with_foreach) {
>>>     CID 349552:  Program hangs  (ORDER_REVERSAL)
>>>     Calling "__netdata_rwlock_wrlock" acquires lock "rrdhost.rrdhost_rwlock" while holding lock "rrdset.rrdset_rwlock" (count: 1 / 14).
404             rrdhost_wrlock(host);
405             rrdcalc_link_to_rrddim(rd, st, host);
406     
407             rrdhost_unlock(host);
408         }
409         rrdset_unlock(st);
```
The offending commit is:
```
commit e3471fa5727bcf286dd3b52ec0cdecd8fdf7067e
Author: thiagoftsm <thiagoftsm@gmail.com>
Date:   Fri Sep 27 12:24:54 2019 +0000

    Create a template for all dimensions (#6560)
```
introduced by #6560 
##### Component Name
database

**Comment by mfundul** [comment]
@thiagoftsm do you think that simply moving:
```
409         rrdset_unlock(st);
```
above line:
```
403         if(host->alarms_with_foreach || host->alarms_template_with_foreach) {
```
is fine or do you see any non obvious side effects?

**Comment by mfundul** [comment]
Moreover, don't we need to retake the lock `rrdset_rdlock` somehow?

**Comment by mfundul** [comment]
Another way is to add at the very beginning of `rrddim_add_custom()`:
```
    if(host->alarms_with_foreach || host->alarms_template_with_foreach) {
        rrdhost_wrlock(host);
    }
```
and at the very end:
```
    if(host->alarms_with_foreach || host->alarms_template_with_foreach) {
        rrdcalc_link_to_rrddim(rd, st, host);
        rrdhost_unlock(host);
    }
```
and be careful with error handling. Also, again, consider side effects.

**Comment by thiagoftsm** [comment]
Thank you, I will test them now.

**Comment by thiagoftsm** [comment]
> Another way is to add at the very beginning of `rrddim_add_custom()`:
> 
> ```
>     if(host->alarms_with_foreach || host->alarms_template_with_foreach) {
>         rrdhost_wrlock(host);
>     }
> ```
> 
> and at the very end:
> 
> ```
>     if(host->alarms_with_foreach || host->alarms_template_with_foreach) {
>         rrdcalc_link_to_rrddim(rd, st, host);
>         rrdhost_unlock(host);
>     }
> ```
> 
> and be careful with error handling. Also, again, consider side effects.

Considering that `CID 349552` is talking about a double lock, I think this won't avoid, because we will call the write lock for chart yet.

**Comment by mfundul** [comment]
> 
> 
> > Another way is to add at the very beginning of `rrddim_add_custom()`:
> > ```
> >     if(host->alarms_with_foreach || host->alarms_template_with_foreach) {
> >         rrdhost_wrlock(host);
> >     }
> > ```
> > 
> > 
> > and at the very end:
> > ```
> >     if(host->alarms_with_foreach || host->alarms_template_with_foreach) {
> >         rrdcalc_link_to_rrddim(rd, st, host);
> >         rrdhost_unlock(host);
> >     }
> > ```
> > 
> > 
> > and be careful with error handling. Also, again, consider side effects.
> 
> Considering that `CID 349552` is talking about a double lock, I think this won't avoid, because we will call the write lock for chart yet.

The problem is not nested locking, but rather it's priority inversion. The rest of the daemon code is calling:
1. `LOCK HOST`
2. `LOCK CHART`
whereas this code calls:
1. `LOCK CHART`
2. `LOCK HOST`

So the deadlock will happen if threads A and B do the following:
1. `A: LOCK HOST`
2. `B: LOCK CHART`
3. `B: LOCK HOST: (blocked)`
4. `A: LOCK CHART: (blocked)`

**Comment by thiagoftsm** [comment]
Now I am understanding better what we were having, I am using completely your suggestion now, thanks!
