### ISSUE TITLE
Samsung SSD 860 QVO 1TB: sem sensor

### ISSUE THREAD

**Issue by wsalmeida** [netdata/netdata#6973]
When running hddtem on debian I noticed that the output generated the following result
##
AVISO: O disco /dev/sdb não parece ter um sensor de temperatura.
AVISO: Isto não significa que não tem nenhum.
AVISO: Se tem a certeza que tem um, por favor contacte-me (hddtemp@guzu.net).
AVISO: Veja as opções --help, --debug e --drivebase.
/dev/sdb: Samsung SSD 860 QVO 1TB: sem sensor
##
wouldn't be a bug as other apps usually display the temperature?

**Comment by ilyam8** [comment]
Hi @wsalmeida. The issue is not netdata related. Netdata uses `hddtemp` output to monitor temperature.

**Comment by cakrit** [comment]
Indeed, please see http://savannah.nongnu.org/mail/?group=hddtemp
