### ISSUE TITLE
Statsd metric with single value does not get sent to backend : is it the expected beahavior ?

### ISSUE THREAD

**Issue by jbfuzier** [netdata/netdata#6974]
Hi, 

I noticed that when there is a single value sent to the statsd input, it nevers get sent to the backend (neither does it get to the all_metrics page.

If I send 2 datapoints, it gets to the backend as expected.

Is this an expected beahavior ?
If it is unexpected, I will dig deeper to idenfify where it is comming from, but first I just want to be sure that it is not the expected beahavior.

##### OS / Environment
Debian 9.5
##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0
##### Component Name
statsd
##### Steps To Reproduce
```
from statsd import StatsdClient
import time
statsd_client = StatsdClient(prefix='test')
statsd_client.gauge("_single", 100)
statsd_client.gauge("_multiple", 100)
time.sleep(5)
statsd_client.gauge("_multiple", 100)
time.sleep(5)
```
##### Expected behavior

test_single and test_multiple, BOTH visible with data in :
/api/v1/allmetrics?format=prometheus_all_hosts&source=as-collected&types=yes&help=yes

**Comment by ilyam8** [comment]
Hi @jbfuzier 

> I noticed that when there is a single value sent to the statsd input, it nevers get sent to the backend (neither does it get to the all_metrics page.

It is expected behavior, but if i remember it right there is a workaround for `statsd` - [`store_first` chart option](https://docs.netdata.cloud/collectors/plugins.d/#chart), so they should be exported


> store_first to make Netdata store the first collected value, assuming there was an invisible previous value set to zero (this is used by statsd charts - if the first data collected value of incremental dimensions is not zero based, unrealistic spikes will appear with this option set)

> this is used by statsd charts

@vlvkobal please take a look

**Comment by jbfuzier** [comment]
Thanks, 

Regarding the chart config, is there a way to make store_first the default for all charts ? Or to configure charts with a pattern (statsd_* for ex) ?

On a related topic, by default, when netdata does not receive value from a statsd client, it report a 0 value to the backend; is there a way to bypass this so that it does not report any value to the backend ?

**Comment by ilyam8** [comment]
> is there a way to make store_first the default for all charts ? 

It should be default, we will check it.

> when netdata does not receive value from a statsd client, it report a 0 value to the backend; is there a way to bypass this so that it does not report any value to the backend

This sounds like a bug. Thx for reporting.

**Comment by jbfuzier** [comment]
For the second point, I think this is by design, however is it expected to also repeat the last value to the backend ?

> When a gauge is not collected and the setting is not to show gaps on the charts (the default), the last value will be shown, until a data collection event changes it.

From : https://docs.netdata.cloud/collectors/statsd.plugin/

**Comment by ilyam8** [comment]
Oh, you are right, it is by design. But you can change the behavior.

See

> https://docs.netdata.cloud/collectors/statsd.plugin/#statsd-charts

`gaps on *` options

**Comment by jbfuzier** [comment]
Thanks `gaps on *` does indeed disable the reporting of the value when there is no value (tested with a graphite backend).

**Comment by jbfuzier** [comment]
Apologies, I missed the fact that the slave doing the collection was in v1.10, I updated everything to the last version and this seems to be working even for a single value.

For reference, I found a commit that is related to this : 

https://github.com/netdata/netdata/pull/2411/commits/b642399514bc599d4746c452e17db5de9e5a8438

**Comment by ilyam8** [comment]
@jbfuzier this is perfect!
