### ISSUE TITLE
health: nonexistent variable in expression always evaluates to zero

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#6980]
##### Bug report summary

SSIA

[from the wiki](https://docs.netdata.cloud/health/#expressions)

> Expressions can have variables. Variables start with $. Check below for more information.

> There are two special values you can use:
>   - nan, for example $this != nan will check if the variable this is available. A variable can be nan if the database lookup failed. All calculations (i.e. addition, multiplication, etc) with a nan result in a nan.

##### OS / Environment

debian10

##### Netdata version (ouput of `netdata -V`)

netdata v1.17.1-127-g2cb7c2fd

##### Component Name

health

##### Steps To Reproduce

 - use nonexistent variable in health expression

##### Expected behavior

nonexistent variable in expression always evaluates to `nan`

**Comment by thiagoftsm** [comment]
when the variable is not present, Netdata cannot evaluate it, I think we can update the documentation to explain this better another possibility is to write a message in the error.log and do not create the alarm. Do you have another suggestion?

**Comment by ilyam8** [comment]
My suggestion is in Expected behavior

> nonexistent variable in expression always evaluates to nan

Currently it is zero
