### ISSUE TITLE
Global alert dashboard

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#6981]
Hi

Do you have any plan about a feature that provides a global alerting dashboard ? 
In a master slave infrastructure or with lot of isolated netdata agent it may provide a central dashboard for all raised alarm

**Comment by cakrit** [comment]
Sure @fmercier-almerys , we call it "Centralized health monitoring" and it will be part of netdata cloud. 
I will close this in favor of #1527 which of course will need more refinement. You can also see it mentioned in the high-level roadmap at https://www.netdata.cloud/roadmap.
