### ISSUE TITLE
dashboard top panel server name wrapping

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#6986]
### Bug report summary

My server name is `debian10`, the name is pretty short. See screenshot. Top one is `chrome`, bottom one is `safari`. Both browsers in zoom mode:

<img width="1440" alt="Screenshot 2019-10-02 at 18 24 57" src="https://user-images.githubusercontent.com/22274335/66057838-0bcb8400-e542-11e9-8293-06ff08191d77.png">

However, the name is not shortened in this case

<img width="1440" alt="Screenshot 2019-10-02 at 18 25 20" src="https://user-images.githubusercontent.com/22274335/66057849-0ff7a180-e542-11e9-9885-c63d38c595ca.png">

##### OS / Environment
mac os mojave

##### Netdata version (ouput of `netdata -V`)

netdata v1.17.1-161-ga909cabc

##### Component Name

`web/gui`

##### Steps To Reproduce
 - open netdata dashboard in full screen mode
 - see server name

##### Expected behavior
Dont shorten short names in full screen/zoom mode

**Comment by jacekkolasa** [comment]
fixed with new navbars
