### ISSUE TITLE
10min dbengine global page cache errors mass alarms

### ISSUE THREAD

**Issue by andrezaycev** [netdata/netdata#6996]
##### Bug report summary
Mass alarm sending from all my hosts
##### OS / Environment
Ubuntu 16.04 Server
##### Netdata version (ouput of `netdata -V`)
v1.17.1-175-nightly
##### Expected behavior

Today all my hosts with installed netdata started sending alarms (about 15-20 hosts)
```
%HOSTMAME % is critical - 10min dbengine global page cache errors
netdata.dbengine_global_errors (dbengine)

```

Telegram group received about 2500 messages per hour.
Look likes that it started after the cron.daily task for netdata-updater by start time

**Comment by andrezaycev** [comment]
![image](https://user-images.githubusercontent.com/9984761/66250566-74ec0b00-e77f-11e9-813d-1b6e435dcdc9.png)
Graph after cron-daily update. Check 12:30 im my time

**Comment by mfundul** [comment]
Since #6977 `memory mode = dbengine` has become the default. It appears that you have more metrics than the default `page cache size = 32` can handle and metrics are being dropped to resolve deadlocks.

Please increase your page cache size according to [this](https://github.com/netdata/netdata/tree/master/database/engine#memory-requirements).

**Comment by mfundul** [comment]
Should you like to revert to the old default for any reason (e.g. access your old history) you can explicitly set `memory mode = save` in your global configuration file.

**Comment by andrezaycev** [comment]
> Should you like to revert to the old default for any reason (e.g. access your old history) you can explicitly set `memory mode = save` in your global configuration file.

Thanks. Temporarily added this option. Flood has stopped. Hope you will fix default params for using netdata without additional tuning

**Comment by mfundul** [comment]
> 
> 
> > Should you like to revert to the old default for any reason (e.g. access your old history) you can explicitly set `memory mode = save` in your global configuration file.
> 
> Thanks. Temporarily added this option. Flood has stopped. Hope you will fix default params for using netdata without additional tuning

The default will handle 8192 metrics before hitting the limit. Since #6800 the number of metrics has skyrocketed which has been a problem. I could increase the default value to 128MiB, which could be problematic for some small devices, but I guess it's better this way. What value did you personally use to resolve your problem?

**Comment by andrezaycev** [comment]
i added ```memory mode = save ``` as quickly solution now

**Comment by mfundul** [comment]
> 
> 
> i added `memory mode = save ` as quickly solution now

Ok, I will change this and let you know.

**Comment by mfundul** [comment]
@andrezaycev can you test  #6997 please? The changes are:
-    Reduce mass flood effect of dbengine page cache alarm
-    Increase database engine default page cache size to support up to 32K metrics out of the box

**Comment by andrezaycev** [comment]
If you tell me true way how correctly test in current host with preinstalled netdata nightly

**Comment by mfundul** [comment]
> 
> 
> If you tell me true way how correctly test in current host with preinstalled netdata nightly

I've been testing this already, it's going to be a net change for the better. I guess the easiest way will be to update your nightly build as soon as I merge. I will let you know.

**Comment by cakrit** [comment]
#6997 helps by increasing the time between the notifications to 1hr and increasing the default page cache size, but it's not a proper solution. We'll think about it, leaving this open.

**Comment by mfundul** [comment]
@andrezaycev you may update to the latest nightly and restore `memory mode = dbengine`.
