### ISSUE TITLE
[Api] How to get units ?

### ISSUE THREAD

**Issue by clintnetwork** [netdata/netdata#7000]
Hi,

I use NetData API to get statistics, and I use google charts, to direct consume JSON but I would like to know how to have units and display units in this charts ?

Best regards

**Comment by ilyam8** [comment]
> [Api] How to get units

Hi. What endpoint do you use?

**Comment by clintnetwork** [comment]
Hey,

By example: `/api/v1/data?chart=net.eth0&after=-60&format=datasource&options=nonzero`

**Comment by ilyam8** [comment]
It doesnt look like there is a way to get units using `/api/v1/data` endpoint. 

It seems it makes sense to have units there. @cakrit

**Comment by cakrit** [comment]
The units are in the `/api/v1/chart` call. You only need to get those once, so they shouldn't be included in the `/api/v1/data` response, for performance reasons (you'll be doing a LOT of `data` calls). 

We have a problem in the swagger file, the response for the `data` call is wrong (points to the `chart` response), but I'll create a new issue for that. 

@clintnetwork you can perhaps look at what `dashboard.js` does, for more details.

**Comment by clintnetwork** [comment]
Hmm yeah but the /chart endpoint can generate google charts output ?

**Comment by ilyam8** [comment]
It returs json response

```json
{
  "id": "system.cpu",
  "name": "system.cpu",
  "type": "system",
  "family": "cpu",
  "context": "system.cpu",
  "title": "Total CPU utilization (system.cpu)",
  "priority": 100,
  "plugin": "proc.plugin",
  "module": "/proc/stat",
  "enabled": true,
  "units": "percentage",
  "data_url": "/api/v1/data?chart=system.cpu",
  "chart_type": "stacked",
  "duration": 259997,
  "first_entry": 1570121442,
  "last_entry": 1570381438,
  "update_every": 1,
  "dimensions": {
    "guest_nice": {
      "name": "guest_nice"
    },
    "guest": {
      "name": "guest"
    },
    "steal": {
      "name": "steal"
    },
    "softirq": {
      "name": "softirq"
    },
    "irq": {
      "name": "irq"
    },
    "user": {
      "name": "user"
    },
    "system": {
      "name": "system"
    },
    "nice": {
      "name": "nice"
    },
    "iowait": {
      "name": "iowait"
    }
  },
  "green": null,
  "red": null,
  "alarms": {
    "20min_steal_cpu": {
      "id": 1516143851,
      "status": "CLEAR",
      "units": "%",
      "update_every": 300
    },
    "10min_cpu_iowait": {
      "id": 1516143850,
      "status": "CLEAR",
      "units": "%",
      "update_every": 60
    },
    "10min_cpu_usage": {
      "id": 1516143849,
      "status": "CLEAR",
      "units": "%",
      "update_every": 60
    }
  }
}
```

it didnt mention `/chart` call because of

> google charts output

**Comment by clintnetwork** [comment]
Oh, and how to get direct google chart valid output ?

**Comment by cakrit** [comment]
There's an example of a custom dashboard with google charts at https://my-netdata.io/dashboard.html (your netdata installation also has that `dashboard.html`). Check the source code and go through the [custom dashboards documentation(https://docs.netdata.cloud/web/gui/custom/). There's even a link to the method in `dashboard.js` that handles Google charts.

If you don't want to use `dashboard.js` but write your own code, I'm afraid you'll need to study the Javascript code. There's also  PR #6516  that's refactoring that code to React, it may be simpler to read. But it's in progress.

**Comment by clintnetwork** [comment]
Really good charts! thanks

Anyway, I think it can be interesting to have units from `/data` endpoint.

**Comment by 0x11DFE** [comment]
> Really good charts! thanks
> 
> Anyway, I think it can be interesting to have units from `/data` endpoint.

Been looking into this has it been updated since then?
