### ISSUE TITLE
Netdata not updating after a few minutes

### ISSUE THREAD

**Issue by navinsaven** [netdata/netdata#7001]
##### Bug report summary
Netdata works briefly and then the graphs stop updating after a few minutes. The process is still running on the server but it is unresponsive. I can navigate to the dashboard but none of the graphs are loading.
##### OS / Environment
Red Hat Enterprise Linux Server release 7.7 (Maipo)
##### Netdata version (ouput of `netdata -V`)
netdata v1.17.1-175-nightly

**Comment by mfundul** [comment]
Do you have any critical alarms related to the page cache? This looks like #6996. Does updating to the latest nightly fix your problem?

**Comment by navinsaven** [comment]
I didn't notice any critical alarms related to the page cache but updating to the latest nightly build fixed the issue. So far the dashboard has been updating for the past 30 minutes. Will continue to observe. Thanks!

**Comment by cakrit** [comment]
Ok we'll close it for now, but please comment if you see anything strange popping up again.
