### ISSUE TITLE
Dbengine retention & slaves

### ISSUE THREAD

**Issue by jbfuzier** [netdata/netdata#7009]
Hi,

I am using netdata slaves (web mode=none, memory mode=none) which streams metrics to a master netdata instance.

I  switched to db engine, I noticed that for the netdata of the master host itself, retention is long (sevral days), however, for slaves retention is only to one hour.

Is it expected for slaves whose data is on the master node to have a different retention than the master own data ?

Master's own metrics: 
![image](https://user-images.githubusercontent.com/4688432/66311986-0d18fa00-e910-11e9-9016-622e478d89d3.png)
![image](https://user-images.githubusercontent.com/4688432/66312191-7b5dbc80-e910-11e9-848e-c5588a442631.png)

![image](https://user-images.githubusercontent.com/4688432/66311745-8106d280-e90f-11e9-8844-b3053400b211.png)

One slave (viewed on the master web ui) : 
![image](https://user-images.githubusercontent.com/4688432/66312103-43567980-e910-11e9-9190-01c2d05f271b.png)
![image](https://user-images.githubusercontent.com/4688432/66312143-5bc69400-e910-11e9-93f6-257bd19d5229.png)

![image](https://user-images.githubusercontent.com/4688432/66312078-38034e00-e910-11e9-8228-ed6e88507e5c.png)

**Comment by ilyam8** [comment]
hi @jbfuzier 

I see it is configurable in `stream.conf`

https://github.com/netdata/netdata/blob/551617bd322e2b855ccf19375650348fda77938a/streaming/stream.conf#L123-L138

**Comment by mfundul** [comment]
@jbfuzier you should read [this](https://docs.netdata.cloud/streaming/) guide.

**Comment by jbfuzier** [comment]
Thanks,

I misunderstood the documentation, I thought that the global memory mode setting would take over everything.

If memory mode is set to dbengine in streaming, will it inherit the global page cache size & dbengine disk space ?

Will the page cache size & dbengine disk space be the total for all slaves + master, or will each be assigned their own cache & disk space (which would means number of slaves * cache size) ?

**Comment by mfundul** [comment]
> 
> 
> Thanks,
> 
> I misunderstood the documentation, I thought that the global memory mode setting would take over everything.
> 
> If memory mode is set to dbengine in streaming, will it inherit the global page cache size & dbengine disk space ?

That is correct.
> 
> Will the page cache size & dbengine disk space be the total for all slaves + master, or will each be assigned their own cache & disk space (which would means number of slaves * cache size) ?

Each slave is its own dbengine instance, which multiplies cache and disk sizes.

**Comment by jbfuzier** [comment]
Thanks, 
For the 2nd point, that would be good to mention that in the documentation, as it has a great impact in sizing the cache according to the memory available on the master node.

Is there a plan to implement some kind of auto setting for the cache ?

**Comment by mfundul** [comment]
> 
> 
> Thanks,
> For the 2nd point, that would be good to mention that in the documentation, as it has a great impact in sizing the cache according to the memory available on the master node.

We describe it [here](https://docs.netdata.cloud/database/engine/#configuration).
> 
> Is there a plan to implement some kind of auto setting for the cache ?

We discussed the auto setting very recently but it's not clear yet how we'll move forward.

**Comment by jbfuzier** [comment]
Thanks very much for all those explainations.
