### ISSUE TITLE
Improve handling of out of order timestamps in database engine

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#7011]
##### Bug report summary
Currently, if for any reason the data collection timestamps of the metric data points get reversed this will result in either pages with invalid starting/ending times or overlapping pages which is not allowed and as a result one of the pages will be dropped. We need to also examine whether this is related to monotonic time support in certain systems.

##### Netdata version (ouput of `netdata -V`)
v1.17.1
##### Component Name
database/engine

##### Expected behavior
Figure out a way to salvage the most important data points after a time shift has taken place. We should decide on criteria.

**Comment by cakrit** [comment]
duplicate of #9713, though that one says we're getting segfaults. Closing this one.
