### ISSUE TITLE
info endpoint returns invalid JSON in BSD

### ISSUE THREAD

**Issue by VLegakis** [netdata/netdata#7022]
When calling the `info` endpoint of an agent (version `v1.14.0-rc0-361-g62ba60b0`) installed on a Mac OSX the JSON returned doesn't seem to be valid.

For example you can call this:
`http://arachovis.com:19999/api/v1/info`
Which returns this:
```
{
	"version": "v1.14.0-rc0-361-g62ba60b0",
	"uid": "e50bf3fc-9be2-11e9-bea0-a860b6262c5c",
	"mirrored_hosts": [
		"localhost"
	],
	"alarms": {
		"normal": 23,
		"warning": 0,
		"critical": 0
	},
	"os_name": "	Mac OS X ",
	"os_id": "mac",
	"os_id_like": "mac",
	"os_version": "	10.14.6 ",
	"os_version_id": "unknown",
	"os_detection": "sw_vers",
	"kernel_name": "Darwin",
	"kernel_version": "18.7.0",
	"architecture": "x86_64",
	"virtualization": "unknown",
	"virt_detection": "none",
	"container": "unknown",
	"container_detection": "none",
	"collectors": [
		{
			"plugin": "macos",
			"module": "iokit"
		},
		{
			"plugin": "cups.plugin",
			"module": ""
		},
		{
			"plugin": "idlejitter.plugin",
			"module": ""
		},
		{
			"plugin": "macos",
			"module": "sysctl"
		},
		{
			"plugin": "statsd.plugin",
			"module": "stats"
		},
		{
			"plugin": "python.d.plugin",
			"module": "web_log"
		},
		{
			"plugin": "netdata",
			"module": "stats"
		},
		{
			"plugin": "macos",
			"module": "mach_smi"
		},
		{
			"plugin": "web",
			"module": "stats"
		},
		{
			"plugin": "python.d.plugin",
			"module": ""
		}
	]
}
```

This is not valid JSON since it includes `\t` characters in:
`"os_name": "	Mac OS X ",`
and
`"os_version": "	10.14.6 ",`

This results in failed info calls affecting the node's reachability (namely in the cloud).
Not sure whether this has been already fixed on later version of the agent or whether it exists in other OSs

**Comment by ilyam8** [comment]
looks like
https://github.com/netdata/netdata/issues/6608

which is fixed in https://github.com/netdata/netdata/pull/6612

**Comment by thiagoftsm** [comment]
As Ilya said this was already fixed, you can confirm this running in a newest Netdata, but case you can identify the problem with the upgrade to newest Mac, please, let us know.

**Comment by VLegakis** [comment]
Ok. I verified it fixed in the latest version.
