### ISSUE TITLE
Redirect `/workspaces/` request to console.html

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7023]
##### Feature idea summary
The cloud team is bringing a new feature that needs redirects from Netdata agent. Everytime that the agent receives a request for ```https//localhost:19999/workspaces/YYY``` where ```YYY``` is a "random" value, the agent needs to redirect to ```https//localhost:19999/console.html```
##### Expected behavior
Redirects must happen with ```workspaces``` request

**Comment by cakrit** [comment]
Please ensure this remains on a separate branch, it will NOT be merged to master, until we deploy the next version of netdata.cloud to production. The two will need to be synchronized.

**Comment by cakrit** [comment]
Please discuss whether this should be merged to master or remain on a separate branch.

**Comment by cosmix** [comment]
I don’t think this should be merged. I would like to understand the reasoning behind the request please.

**Comment by thiagoftsm** [comment]
We will talk tomorrow about this @cosmix , @Azein will explain the cloud necessity for we move in front with this.
I created a PR for this to create conditions of the cloud team to move in front.
