### ISSUE TITLE
./netdata-installer.sh --disable-https

### ISSUE THREAD

**Issue by mickae1** [netdata/netdata#7025]
I would like to disable https, but I can't use netdata-installer.sh with option --disable-https

**Comment by mickae1** [comment]
./configure --disable-https
make

works

but how to proper install netdata ? make install ?

**Comment by paulkatsoulakis** [comment]
Hello @mickae1, thanks for reaching out.
My apologies for facing this issue, i can indeed see the issue being replicated.
We 'll be getting right on it and post a fix about it.

Just to answer your question though, if you want netdata installed on the standard paths under /usr, issuing a simple `make install` after make should do the trick but there are other stuff that we execute with `netdata-installer.sh` to get the system up and running so i would recommend to be a little patient for our fix on netdata installer

**Comment by knatsakis** [comment]
Hi @mickae1, thank you very much for your report.

#7027 adds the missing --disable-https, so could you please try again using tomorrow's nightly build?

Thanks!
