### ISSUE TITLE
Netdata updater

### ISSUE THREAD

**Issue by tinyhammers** [netdata/netdata#7026]
Hey mah dudes....

Quick question...

If I run the `netdata-updater.sh` in `/usr/libexec/netdata/` will it overwrite any custom changes I have made, such as stuff in `etc/netdata/python.d` or `/etc/netdata/health.d`?

I ran it on one box, and I _think_ that it did kill my changes, so I wanted to check before I run it across the entire infrastructure, delete the Internet, and send our planet spiralling into that "local" blackhole they found the other week.
I'm only thinking of mankind's survival here.  

Thank you, you gorgeous, mammalian bipeds ❤️

**Comment by paulkatsoulakis** [comment]
Helo @tinyhammers, thanks for reaching out! You made my day with the description, i surely hope you didn't face the problem you are afraid of, we suppose to have you covered by taking care situations of custom configurations. The updater output should inform you in detail with decisions around that aspect. Do you by any chance have the update output available on a log?  If not, i can ran a couple of tests again just to make sure that there is nothing we missed in that process.

**Comment by cakrit** [comment]
Awesome post indeed! The updater has never touched any of my configs in /etc/netdata and I haven't seen anyone else mentioning such a case before.

**Comment by tinyhammers** [comment]
Hey @paulkatsoulakis...

I don't have the output, sadly. The best idea is for me to try again on another machine and see what happens, so I'll do that and let you know 😃

**Comment by knatsakis** [comment]
Hi @tinyhammers, thank you very much for your inspired report :)

I have verified that the updater does not overwrite custom changes in /etc/netdata/*.d directories.

I am going to close this issue now, but feel free to reopen it if you have more information on what happened.

Cheers!
