### ISSUE TITLE
Document the data-model of the allmetrics endpoint.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7029]
### Feature idea summary
In issue #7005 we fixed the swagger documentation for the `api/v1/data` endpoint to show the structure of the responses for each of the possible formats. Currently the `api/v1/allmetrics` endpoint has no documentation for the responses.

##### Expected behavior
Update the swagger documentation to show the data model for the different responses to the `api/v1/allmetrics` endpoint. This involves the json formatted response, the shell reponse and the promethesis_write reponse.

The fuzzer will report that positive / negative tests against the endpoint pass.

**Comment by amoss** [comment]
The format of the responses is not defined in the swagger. It needs to be written so that the fuzzer can match the server responses against it for testing.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
