### ISSUE TITLE
Exclude sda, sdb, sdc... devices

### ISSUE THREAD

**Issue by rdf6** [netdata/netdata#7032]
Can someone provide a working example of how to exclude from monitoring the sda, sdb, sdc, and so on devices?  I can successfully exclude other disk devices, but can't seem to get the syntax correct for excluding these.

![devices](https://user-images.githubusercontent.com/15618037/66439767-bccc9580-e9fe-11e9-9ed5-6f3ff860d9a3.jpg)

**Comment by ilyam8** [comment]
Hi @rdf6 

> https://docs.netdata.cloud/collectors/proc.plugin/#netdata-configuration

see `exclude disks` option

syntax is 

> https://docs.netdata.cloud/libnetdata/simple_pattern/

____

uncomment the option and append `sd*`

**Comment by rdf6** [comment]
Thanks @ilyam8, works perfectly now.  I had been looking in the wrong section.
