### ISSUE TITLE
Kickstart-static64.sh doesn't install netdata-updater cron

### ISSUE THREAD

**Issue by rdf6** [netdata/netdata#7039]
##### Bug report summary
When installing the static binary, it does not install the netdata-updater into /etc/cron.daily.

##### OS / Environment
cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

##### Netdata version (ouput of `netdata -V`)
netdata -V
netdata v1.17.1

##### Component Name
packaging/installer

##### Steps To Reproduce
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --stable-channel
...
ls -al /etc/cron.daily/netdata-updater
ls: cannot access /etc/cron.daily/netdata-updater: No such file or directory

##### Expected behavior
Should install the netdata-updater into /etc/cron.daily, just like it does when using kickstart.sh.  I do see that the following file does exist, but isn't being copied to cron.daily:

/opt/netdata/usr/libexec/netdata/netdata-updater.sh

**Comment by cakrit** [comment]
As per [the documentation](https://docs.netdata.cloud/packaging/installer/update/#you-downloaded-a-binary-package), this isn't actually a bug, but a very good feature request.

**Comment by knatsakis** [comment]
The documentation could use some improvement. [Here](https://docs.netdata.cloud/packaging/installer/#one-line-installation), it mentions:

> To install Netdata from a binary package on any Linux distro and any kernel version on Intel/AMD 64bit systems, and keep it up to date with our nightly releases automatically, run the following:
>
> `bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`

**Comment by rdf6** [comment]
Thanks.  I did determine that I can use kickstart.sh instead of kickstart-static64.sh so that properly installed the updater in cron.  @knatsakis you're correct that that is the part of the documentation which confused me.

**Comment by knatsakis** [comment]
@rdf6, thank you very much for your report.

I am closing this as kickstart-static64.sh now installs /etc/cron.daily/netdata-updater

I will continue working on #7197 which is a closely related issue.
