### ISSUE TITLE
--stable-channel option not working

### ISSUE THREAD

**Issue by rdf6** [netdata/netdata#7040]
##### Bug report summary
When using the --stable-channel option to only update upon major releases, the installation does not seem to honor that option.  The generated .environment file contains:
RELEASE_CHANNEL="nightly"

##### OS / Environment
cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

##### Netdata version (ouput of `netdata -V`)
netdata -V
netdata v1.17.1

##### Component Name
packaging/installer

##### Steps To Reproduce
Using either of the installation commands does not honor --stable-channel:
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait --stable-channel
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --stable-channel

##### Expected behavior
Expecting the generated .environment file to contain:
RELEASE_CHANNEL="stable"

so that when the cron.daily job runs, it will only update upon major release.

**Comment by oxplot** [comment]
Confirmed and proposed fix in #7051

**Comment by knatsakis** [comment]
Hi @rdf6,

I believe this issue is now resolved in the latest nightly release.

Thank you very much for your detailed report!
