### ISSUE TITLE
Change background-color for theme: Dark

### ISSUE THREAD

**Issue by vitabaks** [netdata/netdata#7044]
##### Feature idea summary
Please consider changing the background color for the dark theme topic.
By default is:
`background-color: #272b30;`

I suggest using `#15191C;`.
or something close to that...

##### Expected behavior
![background_15191C](https://user-images.githubusercontent.com/37010174/66559758-99206100-eb5e-11e9-9b2b-61c600b7e435.png)

**Comment by Ferroin** [comment]
If you push the contrast too high, it actually makes things less readable for people with dyslexia or astigmatism, and the current dark theme is fine for such users right now (at least, it's fine from my perspective as someone with a particularly bad case of astigmatism).

Given that, I'd rather see this as a new theme, ideally just going all the way to black for the background (for the power savings on OLED screens).

**Comment by vitabaks** [comment]
Maybe you can add as an additional option the ability to change the background color in Settings -> Visual -> "background-color: RGB"? That it was not necessary to edit the css file.

You may not agree with me, but after installation I always change the default background to `#15191C;` :)

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
