### ISSUE TITLE
[Spike] agent claiming

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#7052]

**Comment by cosmix** [comment]
What is the definition of done here? @mfundul 

Suggestions from the planning:

1. A design document for the claiming on the agent side.
2. An estimation of the work needed to complete claiming on the agent side.

**Comment by mfundul** [comment]
There are some problems in implementing https://github.com/netdata/netdata/issues/7086 .

There is the problem of authenticating the netdata agent identification. MACHINE_GUID is not enough because:
- MACHINE_GUID is not a secret, it can be visible in the network or known to other users. Thus it is not secure. Malicious netdata agents can copy the MACHINE_GUID and connect to netdata cloud hosts without authorization. Moreover, the original netdata agent will be locked out of netdata cloud which is a Denial-Of-Service attack.
- MACHINE_GUID can be easily cloned when creating VMs or containers by mistake, thus it is not unique.
- basing MACHINE_GUID on hardware IDs does not fix the uniqueness issue because the IDs themselves are often virtualized by the hypervisor as part of the virtual machine firmware. It is entirely dependent on the hypervisor type and configuration whether those will be unique or not.

Netdata cloud being a Certificate Authority can work around the issue of agent identification in the following way:
- Agents without a Certificate will create one before claiming but after installation.
- Netdata cloud remembers the public key for a given MACHINE_GUID. Any subsequent claiming requests **or** connection attempts for this MACHINE_GUID will be denied. The agent shall be advised to change its MACHINE_GUID.

However, there is still the possibility of cloning an agent after claiming, and as a result also cloning its Certificate. In this case, when netdata cloud detects a second connection attempt the agent is advised to create a new Certificate.

The agent also needs to get the invitation token in a secure and practical way. One way to do that is by using a new netdata configuration file with suitable permissions. This file will not be globally visible.

However, we also need a command line tool to interact with the agent at runtime, with some form of Inter-Process-Communication. I have rejected the following possibilities:

- POSIX pipes: they are unidirectional and as a result not practical to return a status. Moreover, they are multi-process unsafe and not portable to Windows.
- network sockets: there is no easy and obvious security model with networking even though its low performance is not likely to be an issue since we don't intend to use commands in rapid succession.
- message queues: we do not want asynchronous messages like a mailbox, we need real-time communication with the agent when it's online.
- shared memory: it's way too complicated to implement some sort of IPC queue, that is both multi-process safe and secure, from scratch.

The best solution seems to be libuv IPC pipes:
- They have a well defined file-based security model.
- They are cross platform (based on UNIX sockets and Windows named pipes).
- They are bidirectional so that commands can return status or other information.
- They are multi-process safe.

This command line tool will conveniently solve another problem of the netdata agent, which is that the signals are inadequate for communication with the agent, and that is especially true for Windows. There is some reference code in #7255 that adds IPC command support to the netdata agent. One can pass commands running:

```socat - UNIX-CONNECT:/tmp/netdata-cli```

The work to support agent claiming from the netdata agent side can be broken down to the following tasks:

- Introduce a new configuration file for claiming-related information storage and retrieval. Integrate it with the agent configuration modules and any relevant scripts such as installers. Create claiming-related state in the netdata agent memory that will be used by the command server and the agent-cloud communication modules. This state also includes tokens, client and server(CA) Certificates. Harden said state to be thread-safe and support asynchronous events. (5 days)
- Implement a command server in the netdata agent to receive commands from a command line tool in addition to the configuration file over libuv IPC pipes (based on #7255). (3 days)
- Implement a command line script (2 days)
- Implement the agent-cloud communication protocol (to be determined). (5 days?)

**Comment by amoss** [comment]
Do we need certificates if we assume that the claiming token is a shared secret? The user is expected to cut and paste it from an encrypted page into a ssh terminal to run the claiming command. The agent can then use the combination of `MACHINE_GUID` + `invite token` to open the agent-cloud link.

**Comment by amoss** [comment]
Another comment for the grooming session: we have a similar issue when a user tries to open the dashboard on an agent in their browser. How do we know that the https certificate is valid, there is no man-in-the-middle attempt to redirect the user to another machine?
