### ISSUE TITLE
Dimension templates not loading for sensors or hddtemp

### ISSUE THREAD

**Issue by kmlucy** [netdata/netdata#7058]
##### Bug report summary
I upgraded to 1.18 and am trying to get dimension templates working for my cpu and hdd temperatures. Here are the alarm templates I created:
```
template: core_temp
      on: sensors.temperature
  lookup: max -10s unaligned foreach *
   units: degrees celcius
   every: 10s
    warn: $this > (($status >= $WARNING) ? (72) : (63))
    crit: $this > (($status == $CRITICAL) ? (81) : (72))
    info: current CPU temperature
      to: sysadmin

template: disk_temp
      on: hddtemp.temperatures
  lookup: max -10s unaligned foreach *
   units: degrees celcius
   every: 10s
    warn: $this > (($status >= $WARNING) ? (47) : (42))
    crit: $this > (($status == $CRITICAL) ? (49) : (44))
    info: current disk temperature
      to: sysadmin
```

The alarms are not loaded, however. I can't find any reference to them in `/netdata/api/v1/alarms?all`, and they are not loaded on the dashboard.

##### OS / Environment
Docker (netdata/netdata)

##### Netdata version (ouput of `netdata -V`)
netdata v1.18.0-4-gd01816f0

##### Component Name
Health

##### Steps To Reproduce

1. Setup HDDTemp or Sensors
2. Create alarms as per above

##### Expected behavior
Alarms load in Netdata

**Comment by kmlucy** [comment]
I have narrowed this down to being a problem with the combination of `template` and `foreach`.

The exact same alarm template works if I change the `foreach *` in the `lookup` line to `of Core 0`:
```
template: core0_temp
      on: sensors.temperature
  lookup: max -10s unaligned of Core 0
   units: degrees celcius
   every: 10s
    warn: $this > (($status >= $WARNING) ? (72) : (63))
    crit: $this > (($status == $CRITICAL) ? (81) : (72))
    info: current CPU temperature
      to: sysadmin
```

I also works if I change the template to an alarm:
```
   alarm: core_temp
      on: sensors.coretemp_isa_0001_temperature
  lookup: max -10s unaligned foreach *
   units: degrees celcius
   every: 10s
    warn: $this > (($status >= $WARNING) ? (72) : (63))
    crit: $this > (($status == $CRITICAL) ? (81) : (72))
    info: current CPU temperature
      to: sysadmin
```

**Comment by thiagoftsm** [comment]
Hi @kmlucy ,

Thank you for your feedback, we are already working to fix the problem.

**Comment by thiagoftsm** [comment]
Hi @kmlucy ,

I was testing here to try to find the problem, but I could not create the same error here, at least with the charts that I have available the template worked fine, so I will ask you some additional information that will help us to debug this error.
Please, run the following request for you Netdata Agent and give us the output:

```bash
curl -k https://localhost:19999/api/v1/chart?chart=sensors.temperature
```

The motive we are not having the alarms created from the templates means that Netdata cannot compare the template variables with the alarm variables, this is the motive I am asking you these information.

Best regards!

**Comment by kmlucy** [comment]
I don't get any results with `sensors.temperature`, but if I put the chart rather than the context, I do get results:
```
# curl -k http://localhost:19999/api/v1/chart?chart=sensors.temperature
Chart is not found: sensors.temperature

# curl -k http://localhost:19999/api/v1/chart?chart=sensors.coretemp_isa_0000_temperature
                {
                        "id": "sensors.coretemp-isa-0000_temperature",
                        "name": "sensors.coretemp_isa_0000_temperature",
                        "type": "sensors",
                        "family": "temperature",
                        "context": "sensors.temperature",
                        "title": "coretemp-isa-0000 temperature (sensors.coretemp_isa_0000_temperature)",
                        "priority": 60002,
                        "plugin": "python.d.plugin",
                        "module": "sensors",
                        "enabled": true,
                        "units": "Celsius",
                        "data_url": "/api/v1/data?chart=sensors.coretemp_isa_0000_temperature",
                        "chart_type": "line",
                        "duration": 34878,
                        "first_entry": 1570722483,
                        "last_entry": 1570757360,
                        "update_every": 1,
                        "dimensions": {
                                "coretemp-isa-0000_temp1": { "name": "Package id 0" },
                                "coretemp-isa-0000_temp2": { "name": "Core 0" },
                                "coretemp-isa-0000_temp3": { "name": "Core 1" },
                                "coretemp-isa-0000_temp4": { "name": "Core 2" },
                                "coretemp-isa-0000_temp5": { "name": "Core 3" },
                                "coretemp-isa-0000_temp6": { "name": "Core 4" },
                                "coretemp-isa-0000_temp7": { "name": "Core 5" }
                        },
                        "chart_variables": {
                        },
                        "green": null,
                        "red": null,
                        "alarms": {

                        }
                }
```

**Comment by thiagoftsm** [comment]
I think I could understand the problem, in your first alarms, you said for Netdata creates alarms `on` the chart `sensors.temperature` and probably it could not, because the chart is not present, please, change your alarms to use on `sensors.coretemp_isa_0000_temperature` and try to use again template instead alarm.

Best Regards!

**Comment by kmlucy** [comment]
Changing `sensors.temperature` to `sensors.coretemp_isa_0000_temperature` does not work; I still don't get any `sensors` alarms created. Besides, that wouldn't solve the issue. I have two physical CPUs and three charts for this server: `sensors.coretemp_isa_0001_temperature`, `sensors.coretemp_isa_0001_temperature`, and `sensors.i350bb_pci_0200_temperature`. I want alarms for each dimension of each chart. 

All three charts have the same context: `sensors.temperature`. Based on the docs, I should be able to the this with a `template` for that context, and a `foreach` to get each dimensions.

See my comment above: https://github.com/netdata/netdata/issues/7058#issuecomment-540707832. I can get it working with a `template` on the context `sensors.temperature`, just not with the `foreach`. I can also get it working with a `foreach` if I choose one of the three specific charts and get rid of the `template`.

**Comment by thiagoftsm** [comment]
You are correct, it was my fault, I am sorry.
It is too late now, so tomorrow I will return on this to fix it.

**Comment by thiagoftsm** [comment]
I could discover the real problem, thank you to force me return to the code.
I verified that our template alarms for these specific charts are created using `-` in their names while the charts have `_` in their name, so the system is not able to compare the rule to create alarms with the chart and it does not create, I will release a fixe in few hours for this.

**Comment by kmlucy** [comment]
Perfect, thanks. Glad to help.

**Comment by thiagoftsm** [comment]
I am working on this now, only to give more details about the whole situation, this specific chart somehow is created with the name `sensors.coretemp_isa_0000_temperature` and id `sensors.coretemp-isa-0000_temperature`, this difference of pattern created all the problems, because alarms are set using the `id` pattern, but when we are trying to create the alarm, we were comparing with name. They id and name should be equal to avoid this error.
