### ISSUE TITLE
Workaround flags for freeipmi-plugin

### ISSUE THREAD

**Issue by Tualua** [netdata/netdata#7066]
Hello! Please add workaround command line options to freeipmi-plugin connect for example to OCP servers

    ipmi-dcmi -D LAN -h 192.168.1.1 -u admin -p password --get-system-power-statistic --workaround-flags=noauthcodecheck

Without this flag I get following error

    freeipmi.plugin ERROR : MAIN : ipmi_monitoring_sensor_readings_by_record_id(): password verification timeout

**Comment by vlvkobal** [comment]
@Tualua please test #10701.
