### ISSUE TITLE
Having trouble with implementing authentication on nginx server block

### ISSUE THREAD

**Issue by devNigel** [netdata/netdata#7074]
I am trying to figure out where to implement the authentication as shown in this guide:
https://docs.netdata.cloud/docs/running-behind-nginx/#enable-authentication
 
Does netdata create any default nginx conf anywhere which is used for serving under SERVER_IP_ADDRESS:19999?

I am using a custom nginx server and it's nginx configurations are a bit different than shown in the guide and they are located in the path "/etc/nginx-rc/conf.d"

There are no nginx server blocks related to netdata, but I am able to access the netdata dashboard from SERVER_IP_ADDRESS:19999

I tried creating a new nginx conf file for the server IP address in a new file to implement authentication like this:

/etc/nginx-rc/conf.d/netdata.conf:

```
server {
listen 19999;
server_name SERVER_IP_ADDRESS;
auth_basic "Protected";
auth_basic_user_file /etc/passwords;
}
```

But this is crashing the nginx. 

I inspected the nginx error log and I found this:
* duplicate upstream "backend" in /etc/nginx-rc/conf.d/default_server.conf:1
* bind() to 0.0.0.0:19999 failed (98: Address already in use)

Is it possible to setup authentication without upstream?

Any ideas?

**Comment by ilyam8** [comment]
> listen 19999;

netdata listens on 19999

**Comment by amoss** [comment]
Try changing the block from a `server` to an `upstream` like this:
```
upstream backend {
    # the Netdata server
    server 127.0.0.1:19999;
    keepalive 64;
}
```
This tells nginx that netdata is running on port 19999 instead of trying to open the http there. To pass requests to it you need a redirect inside an address block, e.g.:
```
server {
    # ... this is your existing server block for nginx, using e.g. ...
    # listen 80;
    # server_name netdata.example.com;

   # This redirects requests that land on URLS under netdata/ to the upstream above.
    location /netdata/ {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
    }
}
```

Inside this address block you can then set authentication, e.g. as shown [here](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/).
