### ISSUE TITLE
go.d.plugin - how to enable "disabled by default" plugin 

### ISSUE THREAD

**Issue by mapl** [netdata/netdata#7077]
### Question summary

The doc at https://github.com/netdata/go.d.plugin states
___
Why disabled? How to enable?
We are in process of migrating collectors from python to go.

**Configurations are incompatible. All rewritten in go modules are disabled by default. This is a temporary solution, we are working on it.

To enable module please do the following:

1. explicitly disable python module in python.d.conf
2. explicitly enable go module in go.d.conf
3. move python module jobs to go module configuration file (change syntax, see go module configuration file for details).
4. restart netdata.service**

___

I my case I wanted to enable the "example" plugin to see some charts produced by this plugin.

I did some testing with "sudo /usr/libexec/netdata/plugins.d/go.d.plugin -m example" and saw plausible output:

CHART 'netdata.execution_time_of_example' '' 'Execution Time for example' 'ms' 'go.d' 'netdata.go_plugin_execution_time' '' '145000' '1' '' 'go.d' 'example'
DIMENSION 'time' '' '' '' '' ''

CHART 'example.random' '' 'A Random Number' 'random' 'random' '' '' '70000' '1' '' 'go.d' 'example'
DIMENSION 'random0' 'random 0' '' '' '' ''
DIMENSION 'random1' 'random 1' '' '' '' ''

BEGIN example.random
SET random0 = 10
SET random1 = 51
END

___
However the "example" plugin is disabled by default 

sudo /usr/libexec/netdata/plugins.d/go.d.plugin
[ INFO  ] main[main] setup.go:72 module 'phpfpm' disabled by default
[ INFO  ] main[main] setup.go:72 module 'rabbitmq' disabled by default
[ INFO  ] main[main] setup.go:72 module 'freeradius' disabled by default
[ INFO  ] main[main] setup.go:72 module 'lighttpd' disabled by default
[ INFO  ] main[main] setup.go:72 module 'mysql' disabled by default
[ INFO  ] main[main] setup.go:72 module 'nginx' disabled by default
[ INFO  ] main[main] setup.go:72 module 'apache' disabled by default
[ INFO  ] main[main] setup.go:72 module 'web_log' disabled by default
**[ INFO  ] main[main] setup.go:72 module 'example' disabled by default**
[ INFO  ] main[main] setup.go:72 module 'openvpn' disabled by default
[ INFO  ] main[main] setup.go:72 module 'bind' disabled by default
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 2
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] create.go:71 loading 'consul' configuration
[ INFO  ] main[main] create.go:71 loading 'logstash' configuration

The only way I've found so far was to set the disabled flag to false for this plugin in the go.d.plugin sourcecode and recompile it.

Is there another way to enable "disabled by default" plugins?

##### OS / Environment
current nightly
##### Component Name
go.d.plugin
##### Expected results
enabled

**Comment by ilyam8** [comment]
@mapl You need to explicitely enable them in plugin configuration file ([`go.d.conf`](https://github.com/netdata/go.d.plugin/blob/master/config/go.d.conf))

So just uncomment needed module and set value to `yes`

**Comment by mapl** [comment]
well, I did that explicitely but still the plugin did not honor it.

`example: yes`

**Comment by ilyam8** [comment]
Well, have you restarted netdata?

What file did you change?

What file do you use, stock or user one? (stock is in /usr/lib/netdata/conf.d, user is in /etc/netdata)

**Comment by mapl** [comment]
yes, I restarted netdata several times

`sudo systemctl restart netdata.service`

#### current working directory:

**/etc/netdata**

`sudo ./edit-config go.d.conf`

```
# netdata go.d.plugin configuration
#
# This file is in YaML format.

# Enable/disable the whole go.d.plugin.
enabled: yes

# Enable/disable default value for all modules.
default_run: yes

# Maximum number of used CPUs. Zero means no limit.
max_procs: 0

# Enable/disable specific g.d.plugin module
modules:
#  activemq: yes
#  apache: yes
#  bind: yes
#  consul: yes
#  coredns: yes
#  dns_query: yes
#  docker_engine: yes
#  dockerhub: yes
example: yes
#  freeradius: yes
#  httpcheck: yes
#  k8s_kubelet: yes
#  k8s_kubeproxy: yes
#  lighttpd: yes
#  lighttpd2: yes
#  logstash: yes
#  mysql: yes
#  nginx: yes
#  openvpn: yes
#  portcheck: yes
#  rabbitmq: yes
#  scaleio: yes
#  solr: yes
#  springboot2: yes
#  tengine: yes
#  vsphere: yes
```
___

`sudo ./edit-config go.d/example.conf`

```
# netdata go.d.plugin configuration for example
#
# This file is in YaML format. Generally the format is:
#
# name: value
#
# There are 2 sections:
#  - GLOBAL
#  - JOBS
#
#
# [ GLOBAL ]
# These variables set the defaults for all JOBs, however each JOB may define its own, overriding the defaults.
#
# The GLOBAL section format:
# param1: value1
# param2: value2
#
# Currently supported global parameters:
#  - update_every
#    Data collection frequency in seconds. Default: 1.
#
#  - autodetection_retry
#    Re-check interval in seconds. Attempts to start the job are made once every interval.
#    Zero means not to schedule re-check. Default: 0.
#
#  - priority
#    Priority is the relative priority of the charts as rendered on the web page,
#    lower numbers make the charts appear before the ones with higher numbers. Default: 70000.
#
#
# [ JOBS ]
# JOBS allow you to collect values from multiple sources.
# Each source will have its own set of charts.
#
# IMPORTANT:
#  - Parameter 'name' is mandatory.
#  - Jobs with the same name are mutually exclusive. Only one of them will be allowed running at any time.
#
# This allows autodetection to try several alternatives and pick the one that works.
# Any number of jobs is supported.
#
# The JOBS section format:
#
# jobs:
#   - name: job1
#     param1: value1
#     param2: value2
#
#   - name: job2
#     param1: value1
#     param2: value2
#
#   - name: job2
#     param1: value1
#
#
# [ List of JOB specific parameters ]:
#  No parameters
#
#
# [ JOB defaults ]:
#  No parameters
#
#
# [ JOB mandatory parameters ]:
#  No parameters
#
# ------------------------------------------------MODULE-CONFIGURATION--------------------------------------------------
# [ GLOBAL ]
# update_every: 1
# autodetection_retry: 0
# priority: 70000
#
#
# [ JOBS ]
jobs:
  - name: example
```

**Comment by ilyam8** [comment]
i think it is yaml syntax error, you forgot a space

```yaml
modules:
#  activemq: yes
#  apache: yes
#  bind: yes
#  consul: yes
#  coredns: yes
#  dns_query: yes
#  docker_engine: yes
#  dockerhub: yes
  example: yes
``

**Comment by mapl** [comment]
@ilyam8 yes! the space did the trick. Thank you

Furthermore, I've checked some online yaml validators and both versions are completely valid according to their results. May we have a parsing issue here? 


### valid
![image](https://user-images.githubusercontent.com/9784732/66756442-5205d900-ee9a-11e9-8f82-d59331359be7.png) 
![image](https://user-images.githubusercontent.com/9784732/66756463-5f22c800-ee9a-11e9-9ebf-9878ba9a29b7.png)

### invalid on purpose

![image](https://user-images.githubusercontent.com/9784732/66756542-8aa5b280-ee9a-11e9-9024-ae81b1e68de9.png)

**Comment by ilyam8** [comment]
@mapl i was not clear, the syntax is valid, yes, but the result is different

```yaml
modules:
  example: yes
```

is 
```go
map[modules:map[example:true]]
```


```yaml
modules:
example: yes
```

is

```go
map[example:true modules:<nil>]
```

**Comment by mapl** [comment]
Fully agree, 

Perhaps an additional note inside the conf would help others to avoid such mistakes.
...One missing space made my day...


https://mengzhuo.github.io/yaml-to-go/ also shows the difference in the struct

```
modules:
example: yes
```
Golang to struct conversion: 

```
type AutoGenerated struct {
	Modules interface{} `yaml:"modules"`
	Example string      `yaml:"example"`
}
```
___

```
modules:
 example: yes
```

Golang to struct conversion: 
```
type AutoGenerated struct {
	Modules struct {
		Example string `yaml:"example"`
	} `yaml:"modules"`
}
```
