### ISSUE TITLE
python.d error reporting

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#7079]
##### Bug report summary
I have a lot of errors in my log from this collector that I think would be better to classify as `INFO` messages. They are all " suppressed due to non updating charts." This is always going to be the case for charts that I don't have something that can be monitored. For instance, I don't use galera cluster so that will always be an `ERROR`. Having so many error messages makes it more difficult to debug other collectors that are not functioning properly. 
It doesn't look like `collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py` is set up to handle any `INFO` messages at all.

Example: 

> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 
> 'smartd_log.seek_time_performance' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.sata_interface_downshift' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.write_error_rate' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.verify_total_err_corrected' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.write_total_err_corrected' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.soft_read_error_rate' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.write_total_unc_errors' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.throughput_performance' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.unexpected_power_loss' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.read_total_err_corrected' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.percent_lifetime_used' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.unused_reserved_nand_blocks' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.verify_total_unc_errors' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.airflow_temperature_celsius' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.read_total_unc_errors' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.program_fail_count' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.reserved_block_count' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.erase_fail_count' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: smartd_log[smartd_log] : chart 'smartd_log.wear_leveller_worst_case_erase_count' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.galera_flow_control' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.galera_cluster_weight' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.galera_queue' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.galera_open_transactions' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.galera_bytes' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.slave_behind' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.galera_cluster_state' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.slave_status' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.userstats_cpu' was suppressed due to non updating
> 2019-10-13 08:07:56: python.d ERROR: mysql[socket1_netdata] : chart 'mysql_local.galera_writesets' was suppressed due to non updating

##### OS / Environment
Ubuntu Server

##### Netdata version (ouput of `netdata -V`)
`netdata v1.18.0-10-nightly`

##### Component Name
`collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py`

**Comment by ilyam8** [comment]
This is not an error, we need to change it to warning/info. I agree.
