### ISSUE TITLE
Servers dashboard webpage

### ISSUE THREAD

**Issue by samuelmf** [netdata/netdata#7080]
Hi guys is possible make a webpage where i show the status of all my servers?

**Comment by thiagoftsm** [comment]
Hi @samuelmf ,

Netdata has a HTTP API that you can ask information from it, you can see more details in our documentation https://docs.netdata.cloud/web/api/ , the API delivers information in different formats, depending of your request, you can verify almost 100% of the metrics using it.
Case you can give us more detail about what you want from the servers, we can help you to mount the query.

**Comment by cosmix** [comment]
@samuelmf the easiest way to use Netdata to monitor all of your servers, is to use netdata.cloud. If, for some reason, that's not acceptable, you can create a dashboard and add the necessary `<div>` tags that will result in charts from various different Netdata agents to be shown together. You can find more information about this here: https://docs.netdata.cloud/web/gui/custom/
