### ISSUE TITLE
Agent Claiming - Core

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#7086]
As an Admin of Netdata Nodes, I would like to have the option to claim nodes in workspaces (and warRooms), as a proof of ownership and trust of the Netdata Nodes (by the Admins), as well as applying extra security.

**The main idea**
**`Claiming of Nodes`**: is a Node onboarding process in a workspace (and warRooms), that will be achieved by using a common invitation mechanism per workspace. The invitation mechanism, includes creation of a public claiming-token by the Admins of the Workspace. A Node, can subscribe to the invite (i.e. is allowed to be included in the Workspace & added automatically in WarRooms) with two ways:

1.  `Manually` - this is what most people with a few systems will do:
- Via the config of the Node, by setting manually the invitation token
- Via the installer of Node, by defining manually the invitation token, during the installation

2. `Automatically` - this is what most people with hundreds or even thousands of systems will do:
- Via a command line tool on the Node.

Implementation

This issue will serve as a description of the implementation work that is required to deliver claiming in the agent. In order to implement the design as agreed we have a skeleton `claim.sh` written in bash (this generates the keys and accesses the cloud API).

* Put `claim.sh.in` into the tree and add autotools to install it into the target file-system.
* Provide a `#define` with the path that can be used to call `exec()` from the agent.
* Patch up any paths in the `claim.sh` at install time, target file layout is: 
```
etc/netdata/claim.d/private.pem
etc/netdata/claim.d/public.pem
etc/netdata/claim.d/cloud_fullchain.pem
etc/netdata/claim.d/token
etc/netdata/claim.d/rooms
etc/netdata/claim.d/is_claimed
```
* Sort out file permissions.
* Provide support for three use-cases:
1. Script is called directly in the shell, then cli-tool is used to reload agent state.
2. Agent is run with command-line arguments (including token), `exec()` on the script.
3. Put the token in the file, run the agent with `-claim` and `exec()` the script.
* Resolve the hole in the design: do we delete the token after (3) if the claim is unsuccessful (may requrie some knowledege of target use under Ansible).
* Put return codes into the script (0 for success, non-0 for error).
* Uninstaller steps to clean up.

**Comment by cakrit** [comment]
To understand what information needs to be sent from the agent side to the cloud during the claiming process, look at https://github.com/netdata/cloud-backend/issues/71

**Comment by cakrit** [comment]
The todos are:
- Modify netdata to read a config file to issue the request to the cloud backend and store the state (claimed, failed etc). Let's not use netdata.conf for this.
- Create the script that can be executed from the command line to trigger the process above

Once a netdata agent knows that it has been claimed (success of the process) it should be starting the agent-cloud link every time it starts (once the agent-cloud link is implemented).

The state can be reversed if during the establishment of the agent-cloud link, the cloud backend tells the agent that it's now unclaimed. Then the agent needs to clear the claiming configuration.

**Comment by amoss** [comment]
This issue will serve as a description of the implementation work that is required to deliver claiming in the agent. In order to implement the design as agreed we have a skeleton `claim.sh` written in bash.

* Put `claim.sh.in` into the tree and add autotools to install it into the target file-system.
* Provide a `#define` with the path that can be used to call `exec()` from the agent.
* Patch up any paths in the `claim.sh` at install time, target file layout is: 
```
etc/netdata/claim.d/private.pem
etc/netdata/claim.d/public.pem
etc/netdata/claim.d/cloud_fullchain.pem
etc/netdata/claim.d/token
etc/netdata/claim.d/rooms
etc/netdata/claim.d/is_claimed
```
* Sort out file permissions.
* Provide support for three use-cases:
1. Script is called directly in the shell, then cli-tool is used to reload agent state.
2. Agent is run with command-line arguments (including token), `exec()` on the script.
3. Put the token in the file, run the agent with `-claim` and `exec()` the script.
* Resolve the hole in the design: do we delete the token after (3) if the claim is unsuccessful (may requrie some knowledege of target use under Ansible).
* Put return codes into the script (0 for success, non-0 for error).
* Uninstaller steps to clean up.

**Comment by thiagoftsm** [comment]
Hi @amoss ,

When we brought TLS to Netdata, we defined `/etc/netdata/ssl` as default destination to certificates, of course this can be changed inside `netdata.conf`, but  I would suggest that we continue storing TLS certificates inside the directory cited.

Best regards!

**Comment by mfundul** [comment]
> 
> 
> Hi @amoss ,
> 
> When we brought TLS to Netdata, we defined `/etc/netdata/ssl` as default destination to certificates, of course this can be changed inside `netdata.conf`, but I would suggest that we continue storing TLS certificates inside the directory cited.
> 
> Best regards!

@cakrit explicitly said that it should be different to not confuse any users. It's a different use case I guess.

**Comment by thiagoftsm** [comment]
I understand this point of view, but like OpenSSL uses the same directory to store all certificates from different websites and services, I was thinking to keep the certificates also in the same directory.

I do not have a strong opinion about to put everything related to claim in the new directory, this was only a suggestion to keep the file with more or less the same contents inside specific directories.

**Comment by amoss** [comment]
The `private.pem` and `public.pem` are not certificates - they are an RSA key-pair and I can remember that @cakrit pointed out it would be confusing to users if they were in the `etc/netdata/ssl` directory.

For the `cloud_fullchain.pem` - it is only there in the case that the cloud certificate cannot be walked back to the trust roots (so only for on-premise installations with a local certificate). I have no strong feelings either way so the person who picks up the issue for implementation can decide.
