### ISSUE TITLE
Support configuration of static labels for each collector job

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#7094]

**Comment by amoss** [comment]
Is this still relevant to the current plan for labels or should we let this issues close in favour of user-stories for labels on one of the product issues?

**Comment by thiagoftsm** [comment]
This has a direct relationship with labels for charts, I would move in front with this without user requests, because we already have labels for hosts.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
