### ISSUE TITLE
Enabler: All API calls support labels, where applicable 

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#7096]

**Comment by cakrit** [comment]
Host labels/tags:
- [ ] The following should also become default labels (TBD by team):
    - os_name
    - os_id
    - os_id_like
    - os_version
    - os_version_id
    - kernel_name
    - kernel_version
    - architecture
    - virtualization
    - container
- [ ] On a master host, we should have a default label/tag specifying if a host is a master or a slave.
- [ ] `api/v1/info` response should show list all host labels under a "labels" JSON array
- [ ] `api/v1/charts` response should list all host labels under a "labels" JSON array
- [ ] `api/v1/chart` response should list all host labels under a "labels" JSON array
- [ ] `api/v1/data` response should include all host labels where other labels already appear
- [ ] `api/v1/alarm_variables` should show all labels that can be used in alarm configurations

**Comment by cakrit** [comment]
@thiagoftsm this is the issue where your suggestion to put the labels in alarm_log should be. I added it at the end of the previous comment.

**Comment by thiagoftsm** [comment]
Thank you @cakrit !

I was in doubt about the correct place that specific comment.

**Comment by vlvkobal** [comment]
> `api/v1/data` response should include all host labels where other labels already appear

It doesn't make sense because the existing labels are actually dimension names. What does make sense, on the other hand, is to include host labels to `jsonwrap` format, which has been done in #7493.

**Comment by amoss** [comment]
The "where other labels already appear" does not seem to fit. You are correct that those are a different kind of labels (names of dimensions).  I don't see any existing labels of the same kind in the data responses. Does it make sense to put them in the top-level dictionary? so that (for example) you would get a result like this:
```
{
  "api": 1,
  "id": "system.cpu",
  "name": "system.cpu",
  "view_update_every": 30,
  "update_every": 1,
  "first_entry": 1575741276,
  "last_entry": 1576001272,
  "before": 1576001250,
  "after": 1576000651,
  "labels": {
	"app": "netdata",
	"controller-revision-hash": "64966d4b74",
	"release": "netdata",
	"role": "slave"
  },
  "dimension_names": [
    "guest_nice",
    "guest",
    "steal",
    "softirq",
    "irq",
    "user",
    "system",
    "nice",
    "iowait"
  ],
  "dimension_ids": [
    "guest_nice",
    "guest",
    "steal",
    "softirq",
    "irq",
    "user",
    "system",
    "nice",
    "iowait"
  ],
  "latest_values": [
    ...
  ],
  "view_latest_values": [
    ...
  ],
  "dimensions": 9,
  "points": 20,
  "format": "json",
  "result": {
    "labels": [
      "time",
      "guest_nice",
      "guest",
      "steal",
      "softirq",
      "irq",
      "user",
      "system",
      "nice",
      "iowait"
    ],
    "data": [
       ...
    ]
  },
  "min": 0,
  "max": 4.3554856
}
```

**Comment by vlvkobal** [comment]
They are already there:
```
{
   "api": 1,
   "id": "system.cpu",
   "name": "system.cpu",
   "labels": {
      "app": "netdata",
      "controller-revision-hash": "64966d4b74",
      "release": "netdata",
      "role": "slave"
   },
   "view_update_every": 1,
   "update_every": 1,
   "first_entry": 1575731668,
   "last_entry": 1576006662,
   "before": 1576006662,
   "after": 1576006653,
   "dimension_names": ["guest_nice", "guest", "steal", "softirq", "irq", "user", "system", "nice", "iowait"],
   "dimension_ids": ["guest_nice", "guest", "steal", "softirq", "irq", "user", "system", "nice", "iowait"],
   "latest_values": [0, 0, 0, 0, 0, 0.1253133, 0, 0, 0],
   "view_latest_values": [0, 0, 0, 0, 0, 0.1253133, 0, 0, 0],
   "dimensions": 9,
   "points": 10,
   "format": "json",
   "result": {
 "labels": ["time", "guest_nice", "guest", "steal", "softirq", "irq", "user", "system", "nice", "iowait"],
    "data":
 [
      ...
  ]
},
 "min": 0,
 "max": 0.1253133
}
```

**Comment by amoss** [comment]
Recording from the slack discussion so we don't lose it:

In order to add the labels to the alarm_log there are several parts that were not discussed. The labels need to be added to ALARM_ENTRY. The `health-log.db` format needs to be expanded. Write/parse labels to/from the file.

**Comment by amoss** [comment]
Merged and completed.
