### ISSUE TITLE
As a user, I want to attach custom labels to all metrics in a host, so that I can better search/filter/group through the metrics I aggregate in my TSDB of choice

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#7099]

**Comment by cakrit** [comment]
- [ ] Include all labels/tags in archiving, alongside existing labels/tags
- [ ] Allow users option to exclude our own labels, i.e. to only send their own custom labels? (to be discussed).

**Comment by cakrit** [comment]
TBD where our own default labels will be added to prometheus (allmetrics).

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
