### ISSUE TITLE
Slow display of Netdata URL via LAN...

### ISSUE THREAD

**Issue by bmf7777** [netdata/netdata#7106]
##### Question summary
i've notice a very long delay when visting the nd url (local) via firefox ... not sure when this started happening but the netdata black background is display, then the graphs and symbology can take 10-20 seconds to be display ... once running its fine ... this happens on various Intel NUCs and RPI3s ... it's a little faster with Chrome but clearly there is a delay from what i was used to - any ideas on how to debug this are much appreciated
 thanks
##### OS / Environment
Ubuntu 18.x on Intel NUC with v1.18.0-17-nightly

**Comment by ilyam8** [comment]
Hi @bmf7777 

is it localhost or remote pc?

**Comment by bmf7777** [comment]
remote pc/mac and iphone ...

**Comment by ilyam8** [comment]
- netdata installed on your pc/mac
 - you access netdata from you iphone

right?

What if you access netdata directly from your pc (http://127.0.0.1:19999)? Do you experience delay problems?

**Comment by bmf7777** [comment]
i believe i discovered the issue...it's being caused by a combination of privacy protection of firefox along with ghostery ad blocking ... once trusted and disabled ... speeds are back to normal
