### ISSUE TITLE
Multiple netdata instances behind HAProxy with same backend and multiple paths

### ISSUE THREAD

**Issue by knippers** [netdata/netdata#7117]
#### Question summary
I am trying to setup multiple netdata instances to be accessible via one haproxy frontend/backend where each netdata is identified by a different path (e.g. /ttxv01 and /ttxv02). 

The issue I am having is that one of the two dashboards seems to be selected and the node menu adds the address of both paths to the same node:
![image](https://user-images.githubusercontent.com/69477/66989756-42b6a380-f0c5-11e9-9ec1-c6a117c50e45.png)

So it seems it is identifying the netdata instance based on host:port and not the uri path. Is this assumption correct? Or is my config incorrect?

Below is the full HAProxy config (it is in fact configured in OPNSense but I copied the config from the system). 

#### HAProxy config
```
frontend netdata
    bind 192.168.0.76:8888
    mode http
    option http-keep-alive
    default_backend nonexisting
    option forwardfor
    acl acl_5da6db471d4e42.10025157 path_reg -i ^/ttxv[0-9]+
    use_backend netdata_backend if acl_5da6db471d4e42.10025157
 
backend netdata_backend
    option httpchk OPTIONS / HTTP/1.0
    mode http
    balance source
    stick-table type ip size 50k expire 30m
    stick on src
    acl acl_5da6cc27648939.81903445 path_beg -i /ttxv01
    acl acl_5da6d557605aa1.91449701 path_beg -i /ttxv02
 
    http-request replace-uri /ttxv[0-9]+/(.*) /\1
    http-request set-header Host %[src]
    http-request set-header X-Forwarded-For %[src]
    http-request set-header Connection "keep-alive"
    http-request set-header X-Forwarded-Port %[dst_port]

    use-server netdata_ttxv01 if acl_5da6cc27648939.81903445
    use-server netdata_ttxv02 if acl_5da6d557605aa1.91449701
    http-reuse safe
    server netdata_ttxv01 192.168.200.2:19999 check inter 2s
    server netdata_ttxv02 192.168.200.1:19999 check inter 2s

backend nonexisting
     mode http
    balance source
    errorfile 503 /tmp/haproxy/errorfiles/5da6d7afae8831.89938882.txt
    http-reuse safe
```

**Comment by agrimal** [comment]
FYI I achieved what you want to do with nginx as reverse proxy, that allow me to access netdata instances via url/instance1, url/instance2 in HTTPS.
But the load balancing is done with physical load balancer F5 BIG-IP in front of nginx.
I suppose you can put keepalived/haproxy in front of nginx, but maybe this is too much for this simple case.
I can however share the nginx config if you want to try it out.

**Comment by knippers** [comment]
@agrimal Thanks for the reply. It would be asome if you could share the config. It is good to know that netdata should not have to be the issue.

**Comment by agrimal** [comment]
### Requirements / Assumptions :
- All your servers are in the DNS zone `example.com` 
- Your nginx virtual host resolves to `netdata.example.com` and `netdata-registry.example.com`
- You can access Netdata via `http://server1.example.com:19999`, `http://server2.example.com:19999`, and so on.
- You have configured Netdata registry on each server to point to `netdata-registry.example.com` :
```
# /etc/netdata/netdata.conf
[registry]
    enabled = no
    registry to announce = https://netdata-registry.example.com
```
- The host server1.example.com has  `enabled = yes` in `[registry]` section
```
# /etc/netdata/netdata.conf
[registry]
    enabled = yes
    registry to announce = https://netdata-registry.example.com
```

### Result
- You will be able to access Netdata via `https://netdata.example.com/server1`, `https://netdata.example.com/server2`, and so on, using `server1` as registry via nginx.

### Configuration

**Here is the first virtual host for `netdata.example.com` :** 
```
server {
    listen 80;
    server_name netdata.example.com;
    access_log /var/log/nginx/port80-netdata.example.com-access.log;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name netdata.example.com;
    access_log /var/log/nginx/port443-netdata.example.com-access.log;

    ssl_certificate /etc/ssl/certs/rvprx.pem;
    ssl_certificate_key /etc/ssl/private/rvprx.key;

    resolver <YOUR_DNS_IP_HERE>;

    location ~ ^/([A-Za-z0-9-]+)$ {
        return 301 https://$host$request_uri/;
    }

    location ~ ^/([A-Za-z0-9-]+)/(.*)$ {

        set $target  $1.example.com;
        set $port    19999;
        set $new_uri $2;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_pass http://$target:$port/$new_uri$is_args$args;
    }
}
```

**Here is the second virtual host for `netdata-registry.example.com` :**
```
server {
    listen 80;
    server_name netdata-registry.example.com;
    access_log /var/log/nginx/port80-netdata-registry.example.com-access.log;
    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl http2;
    server_name netdata-registry.example.com;
    access_log /var/log/nginx/port443-netdata-registry.example.com-access.log;

    ssl_certificate /etc/ssl/certs/rvprx.pem;
    ssl_certificate_key /etc/ssl/private/rvprx.key;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_pass http://server1.example.com:19999;
    }
}
```

**Comment by knippers** [comment]
Thank you very much. I will be reviewing the config. Separating out the registry is a good idea to make it all more readable. Currently my thinking is I have something wrong in the config for the netdata_backend to select the right server. I will consider switching to nginx as well as it allows for dynamic back-end selection (HAProxy is static config that needs updating with each netdata node being added).

**Comment by ilyam8** [comment]
@agrimal that seems a useful info, we could update our wiki. What do you think?

**Comment by agrimal** [comment]
@ilyam8 You can use this in wiki for sure if you want to, but the configuration can be probably optimized because nginx parameters are numerous. But that's a good starting point and it can be improved later.

**Comment by knippers** [comment]
I will close this issue as the question is answered. I do still have to figure out if I can get it working on HAProxy (on OPNSense) but in general I would advise others to go the nginx route as that allows for a dynamic backend/proxy-to part.
