### ISSUE TITLE
Error in installation - Centos 7

### ISSUE THREAD

**Issue by cedricVu** [netdata/netdata#7119]
Hi, Im installing net-data on my Centos 7 server.
I got this error while running this command:
bash <(curl -Ss https://my-netdata.io/kickstart.sh)

##### Bug report summary
make[2]: Entering directory `/tmp/netdata-kickstart-xTxeNt/netdata-v1.18.0-38-gbaff9e85'
  CC       libnetdata/os.o
  CC       web/api/formatters/json_wrapper.o
  CC       web/api/formatters/charts2json.o
  CC       web/api/formatters/rrdset2json.o
  CC       collectors/cgroups.plugin/sys_fs_cgroup.o
  CC       collectors/apps.plugin/apps_plugin.o
  CC       libnetdata/adaptive_resortable_list/adaptive_resortable_list.o
  CC       libnetdata/config/appconfig.o
  CC       libnetdata/avl/avl.o
  CC       libnetdata/buffer/buffer.o
  CC       libnetdata/clocks/clocks.o
  CC       libnetdata/dictionary/dictionary.o
  CC       libnetdata/eval/eval.o
  CC       libnetdata/libnetdata.o
  CC       libnetdata/locks/locks.o
  CC       libnetdata/log/log.o
libnetdata/log/log.c: In function 'log_facility_id':
libnetdata/log/log.c:161:10: error: 'LOG_AUTH' undeclared (first use in this function)
   return LOG_AUTH;
          ^
libnetdata/log/log.c:161:10: note: each undeclared identifier is reported only once for each function it appears in
libnetdata/log/log.c:165:10: error: 'LOG_AUTHPRIV' undeclared (first use in this function)
   return LOG_AUTHPRIV;
          ^
libnetdata/log/log.c:175:10: error: 'LOG_CRON' undeclared (first use in this function)
   return LOG_CRON;
          ^
libnetdata/log/log.c:179:10: error: 'LOG_DAEMON' undeclared (first use in this function)
   return LOG_DAEMON;
          ^
##### OS / Environment
Centos 7
##### Netdata version (ouput of `netdata -V`)
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
##### Steps To Reproduce
Run bash <(curl -Ss https://my-netdata.io/kickstart.sh) by root user

**Comment by thiagoftsm** [comment]
Hi @cedricVu,

The compiler is showing this message, because it is not able to find these definitions that are inside the file `/usr/include/sys/syslog.h`, you can install the package glibc-headers:

![VirtualBox_Centos_18_10_2019_02_22_45](https://user-images.githubusercontent.com/49162938/67060917-375b8a80-f14e-11e9-87ff-3686d8b15e1f.png)

This snapshot was extract from a VM with Centos 7 installed.

Best regards!

**Comment by cedricVu** [comment]
Thanks, It worked now.
