### ISSUE TITLE
Changing the units on a chart does not properly handle old data.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#7122]
#### Bug report summary
When the units for a chart are changed (for example, by PR #7121), the old data for the chart is kept as-is without accounting for the change in units (and thus it ends up being invalid).

##### OS / Environment
All

##### Netdata version (ouput of `netdata -V`)
Commit 7ff016ea74261246def5500308f17cb575059856, though this has probably been around for a long time.

##### Component Name
areas/database (verified to be the case on dbengine, not sure yet if it's the case on the older memory modes).

##### Steps To Reproduce
1. Update a collector to change the units on a chart (python.d and charts.d are probably the easiest).
2. Restart Netdata.
3. Notice that the chart still displays the old data prior to the switch (as well as the new data), but doesn't account for the change in units.

##### Expected behavior
The old data should either be dropped (easiest, but destructive) because it's not valid with the new units, or it should be properly scaled to the new units (not sure if this is feasible).

##### Extra Info
This is a low priority bug that's not likely to actually impact anybody.  Actually fixing it properly is not likely to be quick or easy either, so I can entirely understand if it just sits here.  The main point of opening this issue was to make sure it's publicly documented behavior so that other developers don't get caught by surprise when they run into it.

**Comment by ilyam8** [comment]
> the old data for the chart is kept as-is without accounting for the change in units

@Ferroin could you add a screenshot?

**Comment by ilyam8** [comment]
Ok, nvm. It is obvious w/o any screenshot 😅

**Comment by mfundul** [comment]
This is a problem for all memory modes. There is not intelligence in netdata that understands what `seconds` or `milliseconds` is.

One solution is to drop invalid data from a chart.

For `dbengine` memory mode, the effect can be achieved by including units in the GUID generation.

For other memory modes, units need to be added to the chart signature so that the data are explicitly cleared when there is a mismatch in the same way this already happens for `update_every`.

**Comment by Ferroin** [comment]
> This is a problem for all memory modes. There is not intelligence in netdata that understands what seconds or milliseconds is.

I kind of suspected that was the case.

I really don't think it's worth worrying about actually fixing it though since it will make the code more complicated no matter how it gets fixed, and it's not something that's likely to be an issue for users (even ignoring the fact that the trigger condition should be extremely infrequent).

It definitely caught me by surprise though when testing #7121, as I would have expected the old data to be cleared but it wasn't, so I think it's worth documenting, at least for people who are doing testing.

**Comment by cakrit** [comment]
@mfundul @stelfrag  will this be handled with the work we do on sqlite?

**Comment by mfundul** [comment]
> 
> 
> @mfundul @stelfrag will this be handled with the work we do on sqlite?

This looks like it's orthogonal to the metadata log or sqlite. Any work that is done will not change the data model of netdata so no unit transformation will take place for sure. Moreover, invalidating past data if a unit change is detected is something that could probably be done for both the metadata log and sqlite implementations.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
