### ISSUE TITLE
unbound queries data-desired-units

### ISSUE THREAD

**Issue by mkoubar** [netdata/netdata#7124]
@ilyam8 can we add data-desired-units feature to unbound section so that number of queries will not that huge because after running for 1-day numbers will be as below
![queries](https://user-images.githubusercontent.com/16787802/67045976-03756a80-f138-11e9-8b07-0092b1c1d3eb.png)

**Comment by ilyam8** [comment]
@Ferroin 

I think we need to make dimensions of this chart `incremental` and change units to `queries/s`. I think total number of queries is not that useful. What do you think?

**Comment by ilyam8** [comment]
ok, Process Queries chart is wrong, we need so split it at least in to 3 charts

```
# Total Queries
total.num.queries=1249

# Cache
total.num.cachehits=235
total.num.cachemiss=1014

# Queries By Type
total.num.queries_ip_ratelimited=0
total.num.prefetch=3
total.num.zero_ttl=0
total.num.recursivereplies=1014
```

The question is - sum of queries by type is less them total number of queries? What are we missing?

**Comment by ilyam8** [comment]
Ok, it seems we need to do some research about unbound metrics. Current implementation has some problems. We should collect more metrics and group them differently.

Metrics w/ description:
 - https://docs.datadoghq.com/integrations/unbound/#metrics


@Ferroin dont hurry with PR, lets discuss first.

**Comment by mkoubar** [comment]
FYI : @ilyam8 @Ferroin when statistics-cumulative: yes extended-statistics: yes are activated in unbound.conf 
the result of unbound-control  stats_noreset will give all these results below:
thread0.num.queries=169493
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=152164
thread0.num.cachemiss=17329
thread0.num.prefetch=2633
thread0.num.zero_ttl=0
thread0.num.recursivereplies=17322
thread0.requestlist.avg=1.87261
thread0.requestlist.max=19
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=4
thread0.requestlist.current.user=4
thread0.recursion.time.avg=0.098119
thread0.recursion.time.median=0.0489934
thread0.tcpusage=0
thread1.num.queries=172811
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=155926
thread1.num.cachemiss=16885
thread1.num.prefetch=2540
thread1.num.zero_ttl=0
thread1.num.recursivereplies=16883
thread1.requestlist.avg=1.80396
thread1.requestlist.max=18
thread1.requestlist.overwritten=0
thread1.requestlist.exceeded=0
thread1.requestlist.current.all=2
thread1.requestlist.current.user=2
thread1.recursion.time.avg=0.096275
thread1.recursion.time.median=0.0486465
thread1.tcpusage=0
thread2.num.queries=172785
thread2.num.queries_ip_ratelimited=0
thread2.num.cachehits=155978
thread2.num.cachemiss=16807
thread2.num.prefetch=2675
thread2.num.zero_ttl=0
thread2.num.recursivereplies=16806
thread2.requestlist.avg=1.67396
thread2.requestlist.max=18
thread2.requestlist.overwritten=0
thread2.requestlist.exceeded=0
thread2.requestlist.current.all=1
thread2.requestlist.current.user=1
thread2.recursion.time.avg=0.085126
thread2.recursion.time.median=0.0485568
thread2.tcpusage=0
thread3.num.queries=167620
thread3.num.queries_ip_ratelimited=0
thread3.num.cachehits=150858
thread3.num.cachemiss=16762
thread3.num.prefetch=2619
thread3.num.zero_ttl=0
thread3.num.recursivereplies=16761
thread3.requestlist.avg=1.62081
thread3.requestlist.max=16
thread3.requestlist.overwritten=0
thread3.requestlist.exceeded=0
thread3.requestlist.current.all=1
thread3.requestlist.current.user=1
thread3.recursion.time.avg=0.086544
thread3.recursion.time.median=0.0484766
thread3.tcpusage=0
total.num.queries=682709
total.num.queries_ip_ratelimited=0
total.num.cachehits=614926
total.num.cachemiss=67783
total.num.prefetch=10467
total.num.zero_ttl=0
total.num.recursivereplies=67772
total.requestlist.avg=1.74374
total.requestlist.max=19
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=8
total.requestlist.current.user=8
total.recursion.time.avg=0.091575
total.recursion.time.median=0.0486683
total.tcpusage=0
time.now=1571347895.662019
time.up=977.731578
time.elapsed=0.549458
mem.cache.rrset=7510760
mem.cache.message=7938584
mem.mod.iterator=16588
mem.mod.validator=0
mem.mod.respip=0
mem.streamwait=0
histogram.000000.000000.to.000000.000001=7508
histogram.000000.000001.to.000000.000002=0
histogram.000000.000002.to.000000.000004=0
histogram.000000.000004.to.000000.000008=0
histogram.000000.000008.to.000000.000016=2
histogram.000000.000016.to.000000.000032=0
histogram.000000.000032.to.000000.000064=3
histogram.000000.000064.to.000000.000128=5
histogram.000000.000128.to.000000.000256=12
histogram.000000.000256.to.000000.000512=5687
histogram.000000.000512.to.000000.001024=3870
histogram.000000.001024.to.000000.002048=327
histogram.000000.002048.to.000000.004096=67
histogram.000000.004096.to.000000.008192=157
histogram.000000.008192.to.000000.016384=261
histogram.000000.016384.to.000000.032768=773
histogram.000000.032768.to.000000.065536=31351
histogram.000000.065536.to.000000.131072=8207
histogram.000000.131072.to.000000.262144=6174
histogram.000000.262144.to.000000.524288=1844
histogram.000000.524288.to.000001.000000=773
histogram.000001.000000.to.000002.000000=401
histogram.000002.000000.to.000004.000000=344
histogram.000004.000000.to.000008.000000=6
histogram.000008.000000.to.000016.000000=0
histogram.000016.000000.to.000032.000000=0
histogram.000032.000000.to.000064.000000=0
histogram.000064.000000.to.000128.000000=0
histogram.000128.000000.to.000256.000000=0
histogram.000256.000000.to.000512.000000=0
histogram.000512.000000.to.001024.000000=0
histogram.001024.000000.to.002048.000000=0
histogram.002048.000000.to.004096.000000=0
histogram.004096.000000.to.008192.000000=0
histogram.008192.000000.to.016384.000000=0
histogram.016384.000000.to.032768.000000=0
histogram.032768.000000.to.065536.000000=0
histogram.065536.000000.to.131072.000000=0
histogram.131072.000000.to.262144.000000=0
histogram.262144.000000.to.524288.000000=0
num.query.type.A=670630
num.query.type.NS=3
num.query.type.SOA=54
num.query.type.PTR=1202
num.query.type.TXT=301
num.query.type.AAAA=10099
num.query.type.SRV=418
num.query.type.NAPTR=2
num.query.class.IN=682709
num.query.opcode.QUERY=682709
num.query.tcp=107
num.query.tcpout=0
num.query.tls=0
num.query.tls.resume=0
num.query.ipv6=0
num.query.flags.QR=0
num.query.flags.AA=0
num.query.flags.TC=0
num.query.flags.RD=682689
num.query.flags.RA=0
num.query.flags.Z=0
num.query.flags.AD=0
num.query.flags.CD=4904
num.query.edns.present=19676
num.query.edns.DO=19674
num.answer.rcode.NOERROR=668655
num.answer.rcode.FORMERR=0
num.answer.rcode.SERVFAIL=1115
num.answer.rcode.NXDOMAIN=12908
num.answer.rcode.NOTIMPL=0
num.answer.rcode.REFUSED=20
num.answer.rcode.nodata=4505
num.query.ratelimited=0
num.answer.secure=0
num.answer.bogus=0
num.rrset.bogus=0
num.query.aggressive.NOERROR=0
num.query.aggressive.NXDOMAIN=0
unwanted.queries=89
unwanted.replies=2
msg.cache.count=26186
rrset.cache.count=23611
infra.cache.count=2
key.cache.count=0
num.query.authzone.up=0
num.query.authzone.down=0

**Comment by Ferroin** [comment]
@ilyam8 The 'queries by type' thing isn't really queries by type, it's data on specific types of queries.

`total.num.queries_ip_ratelimited` is queries that were dropped due to rate limiting on a per-ip basis.  I'm fairly certain that this isn't counted among the cache stats.  On most installations, this should never be anything but zero, but it's important to be able to monitor it as it's a good indicator of an ongoing DoS attack against Unbound. This maps to the `ratelimit` metric.

`total.num.queries_prefetch` is queries that were generated internally by Unbound itself to pre-fetch records (either for cache-revalidation, or retrieving extra data like DNSSEC keys). I'm pretty sure they're not counted in the total queries or the cache stats (they're kind of implicitly cache misses, because they wouldn't be issued if the data was in cache). This maps to the `prefetch` metric.

`total.num.zero_ttl` is queries that were expired in the cache, but got served from it anyway.  I'm not certain what circumstances this might actually happen though, but it should be a subset of cache hits. This maps to the `expired` metric.

`total.num.recursivereplies` is the number of queries that resulted in Unbound performing recursion itself.  In the common cases, this should either always be zero (if you're configured to forward everything to an upstream recursive DNS server), or always match the cache miss count (if you're configured to not forward anything to an upstream DNS server).  However, for certain setups, it may not match either (for example, where I work we have Unbound on our firewalls configured to forward requests for our domain to our internal DNS server, but everything else gets handled without forwarding by Unbound), and it's generally useful when looking at overall DNS traffic to have this data so that you know what percentage was recursive and what percentage was non-recursive. This maps to the `recursive` metric.

In theory, there's a handful of DNSCrypt related metrics like this too, we just don't track those because almost nobody uses DNSCrypt.

I think it does make sense to split out to three charts though.  I don't remember why I didn't originally.

----

Ultimately, the issue here posted by the OP comes down to the module having been designed to run against an instance of Unbound with `statistics-cumulative` set to `no`, and that was not properly documented.  I have no issue adding support for the alternative case (`statistics-cumulative: yes`), but I would like to continue to support the current behavior as well.

**Comment by ilyam8** [comment]
> The 'queries by type' thing isn't really queries by type, it's data on specific types of queries

Yes, that is why i wrote in my post - `this chart is wrong`

Queries by type is 

> num.query.type.A=670630
num.query.type.NS=3
num.query.type.SOA=54
num.query.type.PTR=1202
num.query.type.TXT=301
num.query.type.AAAA=10099
num.query.type.SRV=418
num.query.type.NAPTR=2

Current `Process Queries` chart is wrong:
 - mixing dims with different meaning in one chart
 - wrong dims algorithm

**Comment by ilyam8** [comment]
@mkoubar 

please share the output with

> statistics-cumulative: no extended-statistics: no

> statistics-cumulative: yes extended-statistics: no

> statistics-cumulative: no extended-statistics: yes

**Comment by Ferroin** [comment]
@ilyam8 Agreed on the fact that it's mixing dimensions with different meanings in one chart, but not entirely that it's the wrong algorithm.

The issue is `statistics-cumulative`.  When it's on, the counters don't get reset at all and the dimensions in Netdata need to be incremental.  When it's off, the counters get reset every time they get read, and the dimensions in Netdata need to be absolute.  The module currently blindly assumes it's off without documenting this anywhere other than the code itself (which is non-obvious in this case), so you get bogus results if it's on.

**Comment by ilyam8** [comment]
> The issue is statistics-cumulative. When it's on, the counters don't get reset at all and the dimensions in Netdata need to be incremental. 

Oh, thanks for the explanation! This is true for all counters?

**Comment by Ferroin** [comment]
> > The issue is statistics-cumulative. When it's on, the counters don't get reset at all and the dimensions in Netdata need to be incremental.
> 
> Oh, thanks for the explanation! This is true for all counters?

As far as I understand it, it's true for all the reported metrics that count events.  So the timing and memory usage info needs to stay as absolute regardless, but we need to key off of the value of `statistics-cumulative` in the settings to determine whether the other dimensions should be incremental or absolute.

**Comment by ilyam8** [comment]
ok, then we have several options:
 - try to get `statistics-cumulative` during auto_config
 - make `statistics-cumulative` option configurable
 - both

**Comment by ilyam8** [comment]
And we need to think about the charts

> total.num.zero_ttl is queries that were expired in the cache, but got served from it anyway. I'm not certain what circumstances this might actually happen though, but it should be a subset of cache hits.

If it is cache related then we need to move it to the `cache` family along with cache_hits/cache_misses stuff

**Comment by Ferroin** [comment]
> ok, then we have several options:

Both is the way to go, at least for parity with what we have for all other configuration.

> If it is cache related then we need to move it to the cache family along with cache_hits/cache_misses stuff

All of the `total.num.zero_ttl` queries are also cache hits. More specifically, they're a particular type of cache hit that's tracked independently of the tracking of cache hits because it being non-zero usually means something is wrong with your caching.

**Comment by mkoubar** [comment]
@ilyam8  sorry for the delay the output of both no is:
root@ns1:~# unbound-control stats_noreset
thread0.num.queries=1
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=0
thread0.num.cachemiss=1
thread0.num.prefetch=0
thread0.num.zero_ttl=0
thread0.num.recursivereplies=0
thread0.requestlist.avg=1
thread0.requestlist.max=1
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=1
thread0.requestlist.current.user=1
thread0.recursion.time.avg=0.000000
thread0.recursion.time.median=0
thread0.tcpusage=0
thread1.num.queries=2
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=2
thread1.num.cachemiss=0
thread1.num.prefetch=0
thread1.num.zero_ttl=0
thread1.num.recursivereplies=0
thread1.requestlist.avg=0
thread1.requestlist.max=0
thread1.requestlist.overwritten=0
thread1.requestlist.exceeded=0
thread1.requestlist.current.all=0
thread1.requestlist.current.user=0
thread1.recursion.time.avg=0.000000
thread1.recursion.time.median=0
thread1.tcpusage=0
thread2.num.queries=1
thread2.num.queries_ip_ratelimited=0
thread2.num.cachehits=0
thread2.num.cachemiss=1
thread2.num.prefetch=0
thread2.num.zero_ttl=0
thread2.num.recursivereplies=1
thread2.requestlist.avg=0
thread2.requestlist.max=0
thread2.requestlist.overwritten=0
thread2.requestlist.exceeded=0
thread2.requestlist.current.all=0
thread2.requestlist.current.user=0
thread2.recursion.time.avg=0.236823
thread2.recursion.time.median=0
thread2.tcpusage=0
thread3.num.queries=0
thread3.num.queries_ip_ratelimited=0
thread3.num.cachehits=0
thread3.num.cachemiss=0
thread3.num.prefetch=0
thread3.num.zero_ttl=0
thread3.num.recursivereplies=0
thread3.requestlist.avg=0
thread3.requestlist.max=0
thread3.requestlist.overwritten=0
thread3.requestlist.exceeded=0
thread3.requestlist.current.all=0
thread3.requestlist.current.user=0
thread3.recursion.time.avg=0.000000
thread3.recursion.time.median=0
thread3.tcpusage=0
total.num.queries=4
total.num.queries_ip_ratelimited=0
total.num.cachehits=2
total.num.cachemiss=2
total.num.prefetch=0
total.num.zero_ttl=0
total.num.recursivereplies=1
total.requestlist.avg=0.5
total.requestlist.max=1
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=1
total.requestlist.current.user=1
total.recursion.time.avg=0.236823
total.recursion.time.median=0
total.tcpusage=0
time.now=1571405114.158591
time.up=31.232563
time.elapsed=0.904431
root@ns1:~#

**Comment by mkoubar** [comment]
@ilyam8 
statistics-cumulative: no extended-statistics: yes:
thread0.num.queries=1
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=0
thread0.num.cachemiss=1
thread0.num.prefetch=0
thread0.num.zero_ttl=0
thread0.num.recursivereplies=1
thread0.requestlist.avg=0
thread0.requestlist.max=0
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=0
thread0.requestlist.current.user=0
thread0.recursion.time.avg=0.003121
thread0.recursion.time.median=0
thread0.tcpusage=0
thread1.num.queries=0
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=0
thread1.num.cachemiss=0
thread1.num.prefetch=0
thread1.num.zero_ttl=0
thread1.num.recursivereplies=0
thread1.requestlist.avg=0
thread1.requestlist.max=0
thread1.requestlist.overwritten=0
thread1.requestlist.exceeded=0
thread1.requestlist.current.all=0
thread1.requestlist.current.user=0
thread1.recursion.time.avg=0.000000
thread1.recursion.time.median=0
thread1.tcpusage=0
thread2.num.queries=0
thread2.num.queries_ip_ratelimited=0
thread2.num.cachehits=0
thread2.num.cachemiss=0
thread2.num.prefetch=0
thread2.num.zero_ttl=0
thread2.num.recursivereplies=0
thread2.requestlist.avg=0
thread2.requestlist.max=0
thread2.requestlist.overwritten=0
thread2.requestlist.exceeded=0
thread2.requestlist.current.all=0
thread2.requestlist.current.user=0
thread2.recursion.time.avg=0.000000
thread2.recursion.time.median=0
thread2.tcpusage=0
thread3.num.queries=0
thread3.num.queries_ip_ratelimited=0
thread3.num.cachehits=0
thread3.num.cachemiss=0
thread3.num.prefetch=0
thread3.num.zero_ttl=0
thread3.num.recursivereplies=0
thread3.requestlist.avg=0
thread3.requestlist.max=0
thread3.requestlist.overwritten=0
thread3.requestlist.exceeded=0
thread3.requestlist.current.all=0
thread3.requestlist.current.user=0
thread3.recursion.time.avg=0.000000
thread3.recursion.time.median=0
thread3.tcpusage=0
total.num.queries=1
total.num.queries_ip_ratelimited=0
total.num.cachehits=0
total.num.cachemiss=1
total.num.prefetch=0
total.num.zero_ttl=0
total.num.recursivereplies=1
total.requestlist.avg=0
total.requestlist.max=0
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=0
total.requestlist.current.user=0
total.recursion.time.avg=0.003121
total.recursion.time.median=0
total.tcpusage=0
time.now=1571406665.059510
time.up=11.768185
time.elapsed=0.801449
mem.cache.rrset=75653
mem.cache.message=72418
mem.mod.iterator=16588
mem.mod.validator=0
mem.mod.respip=0
mem.mod.subnet=0
histogram.000000.000000.to.000000.000001=0
histogram.000000.000001.to.000000.000002=0
histogram.000000.000002.to.000000.000004=0
histogram.000000.000004.to.000000.000008=0
histogram.000000.000008.to.000000.000016=0
histogram.000000.000016.to.000000.000032=0
histogram.000000.000032.to.000000.000064=0
histogram.000000.000064.to.000000.000128=0
histogram.000000.000128.to.000000.000256=0
histogram.000000.000256.to.000000.000512=0
histogram.000000.000512.to.000000.001024=0
histogram.000000.001024.to.000000.002048=0
histogram.000000.002048.to.000000.004096=1
histogram.000000.004096.to.000000.008192=0
histogram.000000.008192.to.000000.016384=0
histogram.000000.016384.to.000000.032768=0
histogram.000000.032768.to.000000.065536=0
histogram.000000.065536.to.000000.131072=0
histogram.000000.131072.to.000000.262144=0
histogram.000000.262144.to.000000.524288=0
histogram.000000.524288.to.000001.000000=0
histogram.000001.000000.to.000002.000000=0
histogram.000002.000000.to.000004.000000=0
histogram.000004.000000.to.000008.000000=0
histogram.000008.000000.to.000016.000000=0
histogram.000016.000000.to.000032.000000=0
histogram.000032.000000.to.000064.000000=0
histogram.000064.000000.to.000128.000000=0
histogram.000128.000000.to.000256.000000=0
histogram.000256.000000.to.000512.000000=0
histogram.000512.000000.to.001024.000000=0
histogram.001024.000000.to.002048.000000=0
histogram.002048.000000.to.004096.000000=0
histogram.004096.000000.to.008192.000000=0
histogram.008192.000000.to.016384.000000=0
histogram.016384.000000.to.032768.000000=0
histogram.032768.000000.to.065536.000000=0
histogram.065536.000000.to.131072.000000=0
histogram.131072.000000.to.262144.000000=0
histogram.262144.000000.to.524288.000000=0
num.query.type.A=1
num.query.class.IN=1
num.query.opcode.QUERY=1
num.query.tcp=0
num.query.tcpout=0
num.query.ipv6=0
num.query.flags.QR=0
num.query.flags.AA=0
num.query.flags.TC=0
num.query.flags.RD=1
num.query.flags.RA=0
num.query.flags.Z=0
num.query.flags.AD=0
num.query.flags.CD=0
num.query.edns.present=0
num.query.edns.DO=0
num.answer.rcode.NOERROR=1
num.answer.rcode.FORMERR=0
num.answer.rcode.SERVFAIL=0
num.answer.rcode.NXDOMAIN=0
num.answer.rcode.NOTIMPL=0
num.answer.rcode.REFUSED=0
num.query.ratelimited=0
num.answer.secure=0
num.answer.bogus=0
num.rrset.bogus=0
unwanted.queries=0
unwanted.replies=0
msg.cache.count=23
rrset.cache.count=32
infra.cache.count=4
key.cache.count=0

**Comment by ilyam8** [comment]
@mkoubar

Where is `statistics-cumulative` option located in the config?

**Comment by mkoubar** [comment]
@ilyam8  
server:
 verbosity: 1
 statistics-interval: 0
 statistics-cumulative: no
 extended-statistics: yes
 num-threads: 4

**Comment by mkoubar** [comment]
statistics-interval: <seconds>
              The number of seconds between printing statistics to the log for
              every  thread.  Disable with value 0 or "". Default is disabled.
              The histogram statistics are only printed if replies  were  sent
              during  the  statistics  interval,  requestlist  statistics  are
              printed for every interval (but can be 0).  This is because  the
              median calculation requires data to be present.

       statistics-cumulative: <yes or no>
              If  enabled,  statistics  are cumulative since starting unbound,
              without clearing the statistics counters after logging the  sta-
              tistics. Default is no.

       extended-statistics: <yes or no>
              If  enabled,  extended  statistics are printed from unbound-con-
              trol(8).  Default is off, because keeping track of more  statis-
              tics takes time.  The counters are listed in unbound-control(8).

**Comment by ilyam8** [comment]
@mkoubar 

Could you give me a step-by-step guide how to setup a unbound? I mean build and get it running

**Comment by mkoubar** [comment]
sure @ilyam8 you can check:
https://nlnetlabs.nl/documentation/unbound/howto-setup/
or just let me know what os you are using to help:)

**Comment by ilyam8** [comment]
new unbound

> https://github.com/netdata/go.d.plugin/tree/master/modules/unbound

Will be in the new version of `go.d.plugin`. Tomorrow or the day after.

We plan to [obsolete](https://github.com/netdata/netdata/blob/abf1626db13c9bdfc71219a616f6fa2be97e6628/collectors/python.d.plugin/python.d.plugin.in#L128-L138) python version of unbound module.
