### ISSUE TITLE
OpenTSDB only receiving the netdata.apps.* metrics

### ISSUE THREAD

**Issue by lucasjhall** [netdata/netdata#7134]
##### Question summary

OpenTSDB seems to be only receiving the `netdata.apps.*` metrics. This is verified by running `{opentsdb}/api/suggest?type=metrics` as well as added the OpenTSDB to Grafana and exploring available metrics on the db.  I have a feeling it's a configuration issue, `{netdata}/api/v1/allmetrics` shows all metrics, as well as the graphical UI, but for some reason the `[backend]` does not receive....

##### OS / Environment

Ubuntu `18.04` 
OpenTSDB `2.4.0`

##### Netdata version (ouput of `netdata -V`)

netdata `v1.18.0-55-g2d2e3a1e`
netdata `v1.18.0-44-nightly`

##### Component Name

OpenTSDB Backend 

##### Steps To Reproduce

Installed via sh command :
`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

Changed backend settings
```
[backend]
        enabled = yes
        type = opentsdb:http
        destination ={opentsdb}:4242
```

Restarted the service. 

Only metrics in the `netdata.apps.*` were visible via`{opentsdb}/api/suggest?type=metrics`

##### Expected behavior

All metrics as from `/api/v1/allmetrics` be present in OpenTSDB.

**Comment by vlvkobal** [comment]
What is the output of `nc -l -p 4242` command? Do you all metrics in the output?

**Comment by ilyam8** [comment]
I confirm info from OP.

What i did:
 - install opentsdb (https://hub.docker.com/r/petergrace/opentsdb-docker)
 - configured netdata (latest ver) to send metrics to ip:4242

> http://127.0.0.1:4242/api/suggest?type=metrics


```json
[
    "netdata.apps.cpu.X",
    "netdata.apps.cpu.apps.plugin",
    "netdata.apps.cpu.containers",
    "netdata.apps.cpu.cron",
    "netdata.apps.cpu.dhcp",
    "netdata.apps.cpu.go.d.plugin",
    "netdata.apps.cpu.httpd",
    "netdata.apps.cpu.kernel",
    "netdata.apps.cpu.ksmd",
    "netdata.apps.cpu.logs",
    "netdata.apps.cpu.netdata",
    "netdata.apps.cpu.other",
    "netdata.apps.cpu.python.d.plugin",
    "netdata.apps.cpu.sql",
    "netdata.apps.cpu.ssh",
    "netdata.apps.cpu.system",
    "netdata.apps.cpu.tc_qos_helper",
    "netdata.apps.cpu.time",
    "netdata.apps.cpu.wifi",
    "netdata.apps.cpu_system.X",
    "netdata.apps.cpu_system.apps.plugin",
    "netdata.apps.cpu_system.containers",
    "netdata.apps.cpu_system.cron",
    "netdata.apps.cpu_system.dhcp",
    "netdata.apps.cpu_system.go.d.plugin"
]
```

**Comment by ilyam8** [comment]
Tested with `nc -l 4242`. Netdata sends all metrics

> ilyam:~ $ cat metrics4242  | grep -E -o "\"metric\": \"[^\"]+\"" | sort | uniq | wc -l
    1671

**Comment by ilyam8** [comment]
ok, found, there is the `max` query

> http://127.0.0.1:4242/api/suggest?type=metrics&max=2000

returns all

See 
> http://opentsdb.net/docs/build/html/api_http/suggest.html
