### ISSUE TITLE
developing new plugin

### ISSUE THREAD

**Issue by bitcoiners** [netdata/netdata#7137]
Hello,
I am developing a python plugin for netdata. Source is here
https://github.com/eosdetroit/netdata/tree/master/collectors/python.d.plugin/nodeos
Having trouble building the code, getting error:

```
Making all in python.d.plugin
make[3]: Entering directory '/home/ubuntu/dev/netdata/collectors/python.d.plugin'
if sed \
	-e 's#[@]localstatedir_POST@#/var#g' \
	-e 's#[@]sbindir_POST@#/usr/sbin#g' \
	-e 's#[@]pluginsdir_POST@#/usr/libexec/netdata/plugins.d#g' \
	-e 's#[@]configdir_POST@#/etc/netdata#g' \
	-e 's#[@]libconfigdir_POST@#/usr/lib/netdata/conf.d#g' \
	-e 's#[@]cachedir_POST@#/var/cache/netdata#g' \
	-e 's#[@]registrydir_POST@#/var/lib/netdata/registry#g' \
	-e 's#[@]varlibdir_POST@#/var/lib/netdata#g' \
	python.d.plugin.in > python.d.plugin.tmp; then \
	mv "python.d.plugin.tmp" "python.d.plugin"; \
else \
	rm -f "python.d.plugin.tmp"; \
	false; \
fi
make[3]: *** No rule to make target 'nodeos/nodeos.conf', needed by 'all-am'.  Stop.
```

I am not familiar with make, can somebody please take a look at my source code and tell how I can fix this issue and build the code. 
Thank you.

**Comment by ilyam8** [comment]
Hi. If you want to get it working just drop the `*.chart.py` file in the `python.d/`. That is pretty much it.


If you want to add it to makefiles see

https://docs.netdata.cloud/collectors/python.d.plugin/#pull-request-checklist-for-python-plugins

**Comment by bitcoiners** [comment]
I want to make sure it compiles and followed instructions from 
https://docs.netdata.cloud/collectors/python.d.plugin/#pull-request-checklist-for-python-plugins
still it is not compiling. Mind taking a look?

**Comment by ilyam8** [comment]
@bitcoiners take a look at this PR

> https://github.com/netdata/netdata/pull/7024/files

That module is added to all files, the PR compiles. Use it as a reference.
