### ISSUE TITLE
Crontask to update netdata

### ISSUE THREAD

**Issue by InfRandomness** [netdata/netdata#7138]
##### Question summary
Crontab may not update netdata

##### OS / Environment
Debian 10 x86_64 / 4.19.0-6-amd64

##### Component Name
Netdata update

##### Expected results
Hello. I have installed netdata on my server a while ago and it looks like the crontask does not work.
I have just updated it manually and made sure it was added to the crontab (and it is).

`--- Check if we must enable/disable the netdata updater tool --- 
Adding to cron
Auto-updating has been enabled. Updater script linked to: /etc/cron.daily/netdata-update`

So I have checked the list of crontabs for the user netdata and root, and it is said there is no tasks in it.
How can I make it work ? Is it a netdata bug ?

**Comment by ilyam8** [comment]
@InfRandomness 

Hi. How did you install netdata?

**Comment by InfRandomness** [comment]
I followed the tutorial there : https://github.com/netdata/netdata#quick-start

`# make sure you run `bash` for your shell
bash

# install Netdata directly from GitHub source
bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

**Comment by ilyam8** [comment]
@InfRandomness Why did you decide it is not updated?

i installed netdata via

> bash <(curl -Ss https://my-netdata.io/kickstart.sh)

I see `netdata-updater` script in `/etc/cron.daily`

Sript is ok

> test@debian10:~$ run-parts --test /etc/cron.daily  | grep netdata
/etc/cron.daily/netdata-updater

And it will be executed every

> test@debian10:~$ cat /etc/crontab | grep daily
25 6	* * *	root	test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )

What doesnt work for you?

**Comment by InfRandomness** [comment]
I know it does not update itself with the cron because of the simple fact that almost every time I connect on the page, I have an update, and it looks like it's never updating with the crontask.

**Comment by InfRandomness** [comment]
Oh, yeah, thanks ! (And sorry for inactivity, did not see the answers)
