### ISSUE TITLE
How to check if mount exists

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#7140]
Hi

How can i declare a mount alert that check mount is available.
I tried this example below but if mount is not available, disk.space context does not exists so alert is not activated. 

```
template: disk_data_volume_present
      on: disk.space
      os: linux freebsd
   hosts: *-mongo* *-es*
families: /data*
    calc: $now - $last_collected_t
   every: 1m
    crit: $this > $update_every
    info: Data volume disk mount
      to: sysadmin
```

**Comment by ilyam8** [comment]
@fmercier-almerys i dont this this is prossible.

@thiagoftsm @vlvkobal correct me if i m wrong

**Comment by Ferroin** [comment]
AFAIK, @ilyam8 is correct and there's no way currently to do this.  Netdata is really good at checking conditions based on the values of continuous metrics, but not so much when it comes to simple binary states like this.

Short term, you might consider looking into [monit](https://mmonit.com/monit/), which is very good at tracking things like this, and can also be monitored by Netdata to leverage all the benefits of Netdata's alarm delivery and historical data functionality.

Long term, I would love to see Netdata get the ability to be configured to run arbitrary commands and track their exit status in charts, which would make things like this dead simple to throw together by hand (the command in this case would be `mountpoint -q /wherever`).

**Comment by thiagoftsm** [comment]
You are not wrong @ilyam8 and @Ferroin said something important and I think we can bring this in the future and I already assigned our project team this issue for we plan this.
