### ISSUE TITLE
Build the CMake prototype

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7144]
##### Feature idea summary
Implement a prototype of the build-system that can work independently of autotools.

##### Expected behavior
The following instruction should be sufficient to build netdata:
```
git clean -dxf ; mkdir build; cd build; cmake ..; cmake --build .
```
Specifically, no `config.h` will be generated by `autoreconf -ivf`, this requires the following tasks to be completed (as documented in the spike #4310 ) 

- [ ] Compiler / system detection (including detection of header-files and feature-set).
- [ ] Porting any other `.m4` macros into test-programs for `check_c_source_compiles()` / `try_compile`.
- [ ] Implementing netdata configuration features as command-line options for CMake.
- [ ] Write the `config.h.in` for input to `configure_file()`.
- [ ] Solve the `stderror_r` / `_Generic()` issue.
- [ ] Decide on an appropriate aminimum version of CMake / policy set.

The purpose of this issue to perform the change in the build-system in a "depth-first" way, rather than
"breadth-first". What this means is that a single environment and a small set of known configurations
will be tested against the prototype as it is developed. There will be a further issue to track proper testing
across a larger number of known-configurations and target environments.

This issue does not include the install target, this will be the focus of another issue.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
