### ISSUE TITLE
Replace the installer script with a CMake install target.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7146]
# Feature idea summary
This is the final step in preparing the CMake build-system for a public release. Implement the steps of the `nedata-installer.sh` script as an install target for CMake.

##### Expected behavior
Netdata can be installed from a clean checkout by:
```
mkdir build; cd build; cmake ..; cmake --build . --target install
```

**Comment by Ferroin** [comment]
No current plans to implement this.
