### ISSUE TITLE
Converting the build-system to CMake

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7150]
## Summary
Wrapper for the separate issues in converting the build-system.

**Comment by vlvkobal** [comment]
@stelfrag @vkalintiris we still support both - Autotools and CMake build systems, which is not wise. Can we plan further steps on the Epic? I believe that getting rid of Autotools will be of great benefit for us.

**Comment by vlvkobal** [comment]
BTW, we broke our CMake build configuration with the last commits. At least, ACLK is misconfigured.

**Comment by ilyam8** [comment]
@amoss ❤️
