### ISSUE TITLE
How to keep data for the Netdata GUI ?

### ISSUE THREAD

**Issue by xysth** [netdata/netdata#7151]
Hi,

I do lots of benchmark and I wanted to keep/backup data somewhere I can browse it again through Netdata GUI and not through a Grafana dashboard.

The idea is to do a benchmark, stream all the data to a central Netdata server. When the benchmark is finished I can copy the db somewhere. Few months later I restore/copy back the db to a brand new Netdata server and browse the old data even it was month/year later.

Thanks

**Comment by vlvkobal** [comment]
You can use snapshots 
![image](https://user-images.githubusercontent.com/22008543/67289138-c833bc80-f4e6-11e9-8bfe-78f6dc5ea000.png)

**Comment by xysth** [comment]
Ok I need to give another try then, because I failed to use it.
Thanks for the answer
