### ISSUE TITLE
Log health variables

### ISSUE THREAD

**Issue by mahamafzar** [netdata/netdata#7153]

**Comment by ilyam8** [comment]
Hi @mahamafzar what do you mean by debug? Could u describe your use case?

**Comment by mahamafzar** [comment]
Yes my mean is debug

**Comment by vlvkobal** [comment]
You can use the `http://arch-esxi:19999/api/v1/alarm_variables?chart=example.chart` API call.
You can also enable [debugging](https://docs.netdata.cloud/daemon/#debugging) for `D_HEALTH 0x0000000000800000` but you will end up with tons of debug messages.
