### ISSUE TITLE
Support for LinuxFromScratch

### ISSUE THREAD

**Issue by scomoletti** [netdata/netdata#7155]
##### Question summary
Has anyone installed Netdata on a Linux From Scratch based system yet? Linux From Scratch is a custom linux distribution which is popular for black-box solutions from a number of vendors where their applications are provided as a custom ISO install. It uses SV instead of init.d or systemd. There is no package manager of any kind. Everything is compiled locally in the ISO. Limited python2 support, no pip. Not all system libraries are in the expected places. Dev libs and header files removed before packaging the ISO for distribution. Lots of fun to support...
The netdata installer I used was configured to use /opt/netdata but it still created an /etc/netdata directory and I cant find any install logs anywhere. Menu bar at the top is broken and only shows settings, community, help, and the actual hostname. All other items are missing (alarms...). I'm still evaluating what plugins do/dont work correctly.

##### OS / Environment
http://www.linuxfromscratch.org/
I have no specific version numbers I can provide, it's a black box iso from a vendor but I do have root creds to the shell. 

##### Component Name
Netdata installer, graphite web presentation, more?

##### Expected results
Updated installer to support LinuxFromScratch? or SV support generically. Updates for web presentation.

**Comment by prologic** [comment]
@scomoletti Sorry for the very very delayed response (_I only recently joined the company this year_); I _have_ nearly managed to get NetData on an LFS-ish system. I'll be sure to update this issue if/when I succeed. In theory its possible. you just have to manage/handle the dependencies yourself -- I would probably advise you try the static installer as a first bet.

Trying to compile NetData on an LFS system will be much more work :)

**Comment by prologic** [comment]
@scomoletti Would you be happy enough for me to close this issue out if I built a [CRUX](https://crux.nu) port for Netdata (`PkgFile`) which ias a close to an LFS system as you can get without going all the hard work of building all the tooling yourself (_mostly following the documentaiton_).

If so I will close this out with a PR that address #7917

**Comment by prologic** [comment]
Just as a final note on this; but I will not reopen this.

Its not that we don't want to support building the Netdata agent on an LFS system. We probably should and at the very least document it. We just don't have the bandwidth for this righ tnow.

The static binary (`kickstart-static64.sh`) will actually work just fine and I run this on some very custom (_built from scratch_) Linux systems I run.

Bottomline is this. If you manage to build and install all the build tools on an LFS system + what libraries we need it should be possible to run:

```#!sh
autoreconf -ivf
./configure
make
```

Or run:

```#!sh
./netdata-installer.sh ...
```
