### ISSUE TITLE
unbound graph not showing

### ISSUE THREAD

**Issue by nurlennart** [netdata/netdata#7156]
##### Question
So I've configured the unbound module and the module's debug output seems to collect data successful but nothing is showing up on the netdata dashboard. 
I'm using the unbound socket as remote-control. 
How can this be fixed?
##### OS / Environment
DietPi 
##### Netdata version (ouput of `netdata -V`)
netdata v1.18.1-11-nightly
##### Component Name
python.d/unbound.

**Comment by ilyam8** [comment]
Hi @nurlennart 

Did you debug it as `netdata` user?

**Comment by nurlennart** [comment]
Hey @ilyam8 

thanks for your fast reply.
debugged it as root and that turned out to be the error, netdata had no permissions to read unbound's key files. 
sometimes it's the most obvious, haha. 

everything is working now, thanks a lot! :)

**Comment by ilyam8** [comment]
@nurlennart 

unbound module has some problems, see

> https://github.com/netdata/netdata/issues/7124

it will be fixed soon (i hope)
