### ISSUE TITLE
Network viewer eBPF collector

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7159]
##### Feature idea summary
After to spike the Network viewer as eBPF on Linux last sprint, I will work creating the necessary structure to have the Network Viewer based on K[ret]probe.

##### Expected behavior
Collect all information from Network related to egress and ingress.

**Comment by ilyam8** [comment]
why is this closed?

**Comment by ilyam8** [comment]
expected behavior:

> Collect all information from Network related to egress and ingress.

**Comment by thiagoftsm** [comment]
The necessary structure is already known, now I will create issues that will be the next steps for network viewer.

**Comment by ilyam8** [comment]
Whay is necessary structure?

**Comment by thiagoftsm** [comment]
The necessary structure to do compilation and generate the shared library, the structure is the following:

libbpf/
helper_library/
ebpf_program/
kernel_source/

With this directory structure and files that are inside them, we can compile the shared library that will be used to create the network viewer collector.
An important detail, the kernel source that is listed as part of the structure will be installed in the normal directories of the Linux distributions, but it is an important part of the final structure.

**Comment by ilyam8** [comment]
Ok, i think OP `expected behavior`, title and labels are misleading. According them it looks like that collector is implemented.

**Comment by thiagoftsm** [comment]
You are completely correct, I forgot to change the title. 
During the sprint we had a meeting that changed what I would do during the sprint and I did not change the title.
I apologize due the problem created, I will be more clear in the new issues I am creating now.
