### ISSUE TITLE
Fully test the new URL parsing code.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7165]
#### Summary

- [ ] Build performance tests (wrk) to check behaviour under load.
- [ ] See if we can put the set of fuzzing urls into wrk as a payload generator.

#### Expected result

The test results should show that the new URL parsing code is properly integrated, and that we can demonstrate good coverage of the API automatically.

**Comment by amoss** [comment]
The swagger definitions got upgraded to OpenAPI3.0 to fix a bug. We were planning to improve the handling of the response formats when this was done - it will be necessary for the fuzzer to decode the responses in this piece of work anyway. The missing points are moving into this issue:

In OpenAPI3.0 there is a new "oneOf" operator that can be used to indicate the sub-types. Converting the API requires:

* Changing the fields in the header for the new syntax.
* Working out how to use `oneOf` in the definitions.
* Checking for differences between Swagger2.0 and OpenAPI3.0

**Comment by ilyam8** [comment]
Enhance the testability of the Netdata internal web-server
