### ISSUE TITLE
Implement AWS Kinesis exporting connector

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#7169]
##### Feature idea summary

* Code already exists in the backend that can export AWS Kinesis.
* Code currently has poor structure - intertwined with the existing backends.
* Sits on top of AWS SDK in C++, unknown if this wrapper will change.
* Similar in complexity to the Prometheus remote write exporter.
* Unit-tests will need to call the wrapped C++ code - unclear if this is difficult.

##### Expected behavior

* Reviewer will require a working AWS Kinesis service to test against.
* @cakrit will need to provide access to AWS for testing properly.
* Note for the reviewer - the threading/locking should be standard for the exporting engine, may need to read the config reading code.

**Comment by cakrit** [comment]
> @cakrit will need to provide access to AWS for testing properly.

Credentials sent in slack.
