### ISSUE TITLE
edit-config fails due to /opt being a symlink

### ISSUE THREAD

**Issue by sock3t** [netdata/netdata#7179]
##### Bug report summary
I want to edit a config file but edit-config throws this error:
`[root@192.168.150.23 ~]# /opt/netdata/etc/netdata/edit-config apps_groups.conf`

`File '/opt/netdata/usr/lib/netdata/conf.d/apps_groups.conf' is physically at '/var/opt/netdata/usr/lib/netdata/conf.d/apps_groups.conf', which is not in '/opt/netdata/usr/lib/netdata/conf.d'. Aborting.`

##### OS / Environment
[root@192.168.150.23 /]# cat /etc/os-release
NAME=Fedora
VERSION="29 (Twenty Nine)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Twenty Nine)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

##### Netdata version (ouput of `netdata -V`)
I installed the latest versions of the binary flavor of netdata just a couple minutes ago:
`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`

`[root@192.168.150.23 /]# /opt/netdata/bin/netdata -V`
`netdata v1.18.1-18-g74f9ccd5`

##### Component Name
`edit-config`

##### Steps To Reproduce

- Make /opt a symlink like this example:
`[root@192.168.150.23 /]# ls -lah /opt`
`lrwxrwxrwx 1 root root 7 Jun 26 19:26 /opt -> var/opt`
- Install binary flavor of netadata (which by default installs into /opt/netadata) which in this case goes into the "_physical_" location `/var/opt/netdata`
- now try to run edit-config

##### Expected behavior
Do not fail to run edit-config if netdata is installed into a folder which is a symlink.

Similar issue is https://github.com/netdata/netdata/issues/6782.
The solution there was to move netdata to a different directory, but in my situation this is not desired and it is the default directory that netdata uses. I don't even understand why netdata (edit-config) needs to check about the config files stored under a symlinked path - why would that be an issue?

**Comment by ilyam8** [comment]
@knatsakis please take a look

**Comment by alexandernst** [comment]
Can confirm this happening on v1.19.0 on a Debian 10. Tried to symlink the stream.conf file and got the same error: `File '/etc/netdata/stream.conf' is physically at '/var/www/webapp/conf/netdata/stream.conf', which is not in '/etc/netdata'. Aborting.`

**Comment by thiagoftsm** [comment]
Hi @alexandernst ,

Only to confirm, when you installed Netdata did  you append `/` at the end of the path?

Best regards!

**Comment by alexandernst** [comment]
I installed from the package cloud repo.

**Comment by prologic** [comment]
I've had a quick look into this; I _think_ its something we can probably fix (_maybe_); But can someone (_preferably someone with background/context_) help me understand why we did this:

https://github.com/netdata/netdata/blob/5ecdecce05a1a0dd2317efa0b426331290f49635/system/edit-config.in#L41-L58

**Comment by prologic** [comment]
I'll create a repro case and post here later today.

Is this a common setup having `/opt` symlinked to `/var/opt`?

**Comment by prologic** [comment]
Reproducer:

```sh
$ cat > test.sh << EOF
#!/bin/sh

apk --no-cache -U add alpine-sdk bash curl libuv-dev zlib-dev util-linux-dev libmnl-dev gcc make git autoconf automake pkgconfig python logrotate

(
  rm -rf /opt
  mkdir -p /var/opt
  cd / || exit 1
  ln -s /var/opt .
)

./netdata-installer.sh --dont-wait --dont-start-it --install /opt

/opt/netdata/etc/netdata/edit-config apps_groups.conf
EOF

$ docker run -i -t --rm -v $PWD:/netdata -w /netdata alpine ./test.sh
```

Produces:

```sh
.
.
.
  enjoy real-time performance and health monitoring...

File '/opt/netdata/usr/lib/netdata/conf.d/apps_groups.conf' is physically at '/var/opt/netdata/usr/lib/netdata/conf.d/apps_groups.conf', which is not in '/opt/netdata/usr/lib/netdata/conf.d'. Aborting.
```

**Comment by prologic** [comment]
Just commenting out the `file_is_in_path` calls fixes this;

```sh
$ git diff
diff --git a/system/edit-config.in b/system/edit-config.in
index abfd5a45..be69201b 100755
--- a/system/edit-config.in
+++ b/system/edit-config.in
@@ -61,7 +61,7 @@ edit() {
        echo >&2 "Editing '${1}' ..."

        # check we can edit
-       file_is_in_path "${1}" "${NETDATA_USER_CONFIG_DIR}" || exit 1
+       # file_is_in_path "${1}" "${NETDATA_USER_CONFIG_DIR}" || exit 1

        "${EDITOR}" "${1}"
        exit $?
@@ -69,7 +69,7 @@ edit() {

 copy_and_edit() {
        # check we can copy
-       file_is_in_path "${NETDATA_STOCK_CONFIG_DIR}/${1}" "${NETDATA_STOCK_CONFIG_DIR}" || exit 1
+       # file_is_in_path "${NETDATA_STOCK_CONFIG_DIR}/${1}" "${NETDATA_STOCK_CONFIG_DIR}" || exit 1

        if [ ! -f "${NETDATA_USER_CONFIG_DIR}/${1}" ]
        then
```

No more problems.

```sh
.
.
.
  enjoy real-time performance and health monitoring...

Copying '/opt/netdata/usr/lib/netdata/conf.d/apps_groups.conf' to '/opt/netdata/etc/netdata/apps_groups.conf' ...
Editing '/opt/netdata/etc/netdata/apps_groups.conf' ...
```

So the question is why were/are we doing this in the first place? Can we just test for write-ability with `test -w /path/to/file`? and `test -w /path/todir`? I _assume_ `test` is smart enough to handle symbolic links?
