### ISSUE TITLE
Ability to set log level in netdata.conf

### ISSUE THREAD

**Issue by Helios-23** [netdata/netdata#7182]
Currently, log levels are extremely verbose  and can only be on or off. log events come in the following levels [WARN, INFO, ERROR, FATAL]
On
debug log = /var/log/netdata/debug.log
error log = /var/log/netdata/error.log
access log = /var/log/netdata/access.log
off
debug log = none
error log = none
access log = none

To reduce logging size in production environments and generally make the logs more meaningful to read it would be  a great feature to be able to control the verbosity of the log level by specifying the level you'd like to have appear or above like so:

debug log = /var/log/netdata/debug.log WARN
error log = /var/log/netdata/error.log ERROR
access log = /var/log/netdata/access.log INFO

or

debug log = /var/log/netdata/debug.log 
debug log_level = WARN
error log = /var/log/netdata/error.log
error log_level = ERROR 
access log = /var/log/netdata/access.log 
access log_level = INFO

For EXAMPLE by adding this configuration feature to netdata.conf
setting the log level to WARN would  show: WARN, INFO, ERROR, FATAL
setting the log level to INFO  would  show: INFO, ERROR, FATAL
setting the log level to ERROR  would  show: ERROR, FATAL
etc.

**Comment by thiagoftsm** [comment]
Hi @Helios-23 ,

It is already possible to set the facility log for syslog using the following option:

```
[global]
    # facility log = daemon
```

but, this will set a common facility for each log level.
I liked your suggestion and I will talk with our team for we bring this feature.

**Comment by Ferroin** [comment]
Quick suggestion on level naming, the hierarchy should probably be (in descending order of verbosity):

* DEBUG
* INFO
* WARN
* ERROR
* FATAL

That matches up with what most other tools do for this type of thing, so it's the least likely to cause confusion.

**Comment by JayKus** [comment]
Might be redundant, but making it explicit: it would be very much appreciated that this could be set through docker environmental settings `-e` once implemented. 

Much appreciated!

**Comment by thiagoftsm** [comment]
Hi @JayKus ,

I moved the status from `new  issue` to `Read for Dev`, this way we will create plan to bring this additional feature in a near future.

Best regards!

**Comment by fzyzcjy** [comment]
Hi is there any updates (after half a year)?

**Comment by thiagoftsm** [comment]
@dim08 this is an old request that we have, please, can you bring us an update?

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.

**Comment by UltraBlackLinux** [comment]
I would also appreciate this, if it's not already implemented. Netdata prints disproportionally much into my docker compose console and I can barely find other logs. Removing the logging driver doesn't change anything and neither does piping everything to /dev/null

**Comment by thiagoftsm** [comment]
Hello @UltraBlackLinux,

I am rebasing the PR https://github.com/netdata/netdata/pull/14727 and fixing some CI warnings, I will set PR ready for review today to bring this feature.

Best regards!

**Comment by lordraiden** [comment]
will this be available via docker environment variable? most of the apps have this feature as a variable.

**Comment by thiagoftsm** [comment]
Hello @lordraiden,

When collectors are running, they read variable `NETDATA_LOG_SEVERITY_LEVEL` from environment to set their severity level.

I am not sure how docker variables work, but if it is not possible to use this environment variable, I understand it will be necessary to do small changes in our current code. Please, open a feature request whether it is not possible to use the environment variable already created, and we will bring it.

Best regards!

**Comment by lordraiden** [comment]
> Hello @lordraiden,
> 
> When collectors are running, they read variable `NETDATA_LOG_SEVERITY_LEVEL` from environment to set their severity level.
> 
> I am not sure how docker variables work, but if it is not possible to use this environment variable, I understand it will be necessary to do small changes in our current code. Please, open a feature request whether it is not possible to use the environment variable already created, and we will bring it.
> 
> Best regards!

Adding this as an environment variable in netdata compose file doesn't work
      - NETDATA_LOG_SEVERITY_LEVEL=warning
I still get all kind of logs

**Comment by thiagoftsm** [comment]
Thank you to update @lordraiden !

We will work to address this issue.

**Comment by ktsaou** [comment]
This feature has been implemented. Check the documentation here: https://learn.netdata.cloud/docs/miscellaneous/libnetdata/log#configuring-log-sources

**Comment by ilyam8** [comment]
`health`, `aclk` and `access` sources would ignore both global and individual log levels, they could only be turned on or off. Because of ignoring log level the access.log file contained debug-level messages, a lot of them.

Fixed in #16922.

We didn't respect the NETDATA_LOG_LEVEL env variable if set. There were no way to change the log level using env variables (docker/k8s case).

Fixed in #16943.
