### ISSUE TITLE
how can i  enable nvidia_smi  plugin ?

### ISSUE THREAD

**Issue by apri30th** [netdata/netdata#7183]
##### Question summary
Can't enable nvidia_smi plugin.  i  have already  read  the 6901 question 

and i  switch  to user  netdata  via  su -s /bin/bash netdata
  use the command      /usr/libexec/netdata/plugins.d/python.d.plugin nvidia_smi debug trace 
the dubug logs show  like normal  as below 
BEGIN nvidia_smi.gpu1_clocks 1000000
SET 'gpu1_graphics_clock' = 135
SET 'gpu1_video_clock' = 555
SET 'gpu1_sm_clock' = 135
SET 'gpu1_mem_clock' = 850
END

BEGIN nvidia_smi.gpu0_clocks 1000000
SET 'gpu0_graphics_clock' = 135
SET 'gpu0_video_clock' = 555
SET 'gpu0_sm_clock' = 135
SET 'gpu0_mem_clock' = 850
END

BEGIN nvidia_smi.gpu1_mem_utilization 1000000
SET 'gpu1_memory_util' = 0
END

BEGIN nvidia_smi.gpu2_clocks 1000000
SET 'gpu2_graphics_clock' = 135
SET 'gpu2_video_clock' = 555
SET 'gpu2_sm_clock' = 135
SET 'gpu2_mem_clock' = 850
END

BEGIN nvidia_smi.gpu2_temperature 1000000
SET 'gpu2_gpu_temp' = 56
END

BEGIN netdata.runtime_nvidia_smi 1000000
SET run_time = 60
END

2019-10-24 15:14:42: python.d DEBUG: nvidia_smi[nvidia_smi] : update => [OK] (elapsed time: 60, failed retries in a row: 0)

but i haven't seen the nvidia_smi chart in my localhost:19999 

##### OS / Environment

 cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
$uname -r
4.14.11-1.el7.elrepo.x86_64

##### netdata version
 netdata -v
netdata v1.17.1-204-nightly
##### Component Name
nvidia_smi 
##### Expected results
nvidia_smi chart shows

**Comment by ilyam8** [comment]
Hi @apri30th 

You need to explicitly enable it in `python.d.conf`. That is it.

If it doesnt work do see `error.log` (grep nvidia_smi error.log)
