### ISSUE TITLE
Ubuntu 19.04 dependency

### ISSUE THREAD

**Issue by Fjodor42** [netdata/netdata#7184]
##### Bug report summary

*.deb packages from https://packagecloud.io/netdata/netdata-edge/install have old dependency on libprotoc10

##### OS / Environment

Ubuntu 19.04

##### Netdata version (ouput of `netdata -V`)

1.18.latest

##### Component Name

DEB packaging

##### Steps To Reproduce

1. `curl -s https://packagecloud.io/install/repositories/netdata/netdata-edge/script.deb.sh | sudo bash`
2. `sudo apt install netdata`

##### Expected behavior

Netdata installed via APT

##### Actual behavior

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 netdata : Depends: libprotoc10 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by prologic** [comment]
As discussed internally we don't build packages for this version of Ubuntu anymore so closing.
