### ISSUE TITLE
Can't get streaming/replication to work with docker

### ISSUE THREAD

**Issue by truh** [netdata/netdata#7186]
Not sure if this is a bug or I'm just doing something wrong so I created this issue as a question.

##### Question summary
I'm currently trying learn how to use netdata in a streaming/replication setup for that purpose I created a setup with multiple dockerized netdata instances. Unfortunately the replication doesn't work as I would expect. I would very thankful if someone could tell me what I'm doing wrong. 
  
##### OS / Environment
All nodes in the setup are based on the `netdata/netdata` docker image from docker hub.

You can find the minimal setup I'm trying to get to work here https://github.com/truh/netdata-docker-demo. Just clone it and run `docker-compose up` inside the repo folder. 

To open the dashboard of the netdata-master in browser enter http://localhost:17777/.

##### Component Name
streaming

##### Expected results
To have the graph from the netdata-node replicated onto netdata-master.

I would expect to see the a second node in the *your other netdata servers* drop down as well as a second entry in http://localhost:17777/api/v1/info `.mirrored_hosts`.

**Comment by mfundul** [comment]
Can you share your `error.llog` files from your 2 netdata agents?

**Comment by truh** [comment]
Of courese, here are the error logs.

* [netdata-master](https://gist.github.com/truh/4d6c37697e2be6af2043ff2426e837a8#file-netdata-master-error-log)

* [netdata-node](https://gist.github.com/truh/4d6c37697e2be6af2043ff2426e837a8#file-netdata-node-error-log)

**Comment by truh** [comment]
Had to remove the // from `tcp://netdata-master:19999` -> `tcp:netdata-master:19999`

Thanks for making me read the logs.
