### ISSUE TITLE
No NTP metrics when ntpd not synchronised.

### ISSUE THREAD

**Issue by ScrumpyJack** [netdata/netdata#7190]
When I deliberately disconnect peers from an NTP "client" and restart ntpd on said client, netdata stops showing metrics for NTP. Is this the expected behaviour? 

Also, the stratum reported is always 4, even though the client is at either 16 or 3.

(Netdata 1.12)

**Comment by ilyam8** [comment]
@ScrumpyJack 

Could you run python.d.plugin in [debug mode](https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module) and during it plese do

> deliberately disconnect peers from an NTP "client" and restart ntpd on said client

lets see where it fails

**Comment by ilyam8** [comment]
> (Netdata 1.12)

hold on hold on

Please update to the latest

**Comment by ScrumpyJack** [comment]
I was afraid you might say that

**Comment by Ferroin** [comment]
The missing metrics have nothing to do with Netdata itself and is expected behavior.  Without remote peers, ntpd can't compute any of those metrics because it has no references to compute them against.

The bogus stratum though is probably a bug in Netdata itself.

**Comment by thiagoftsm** [comment]
Hi @ScrumpyJack , we released Netdata 1.18.1, it is possible that the problem was already fixed, let us know case the update does not help.

**Comment by ScrumpyJack** [comment]
@Ferroin 

The peers are configured, just not reachable. NTP will try to contact them and do it's thing, and will stay in the INIT state, but netdata doesn't show any data for it, as if ntpd isn't running

**Comment by ilyam8** [comment]
> I was afraid you might say that, but I don't see any mention of ntp in the changelog since 1.12.



Yes, but i did some fixes to python.d.plugin and probably i changes some error/info log messages.

**Comment by Ferroin** [comment]
@ScrumpyJack But until you talk to the peers, you can't determine any of the relevant information that you need to compute those metrics.  Peer stratum and RTT are the trivial examples here (neither can be determined unless the peer responds), but most of the other metrics require knowing what the peers think the time is (and fetching some other info from them).

Ultimately, the ntpd module for Netdata is not getting any data back from ntpd, so it's reporting this to Netdata, which is in turn not displaying any charts (because we don't display empty charts).

**Comment by ScrumpyJack** [comment]
I'll update on a host this afternoon and let you know.

Here is further info until then:

```
ntpq -pn
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 10.193.140.90   .INIT.          16 u    -   64    0    0.000    0.000   0.000
 10.193.140.91   .INIT.          16 u    -   64    0    0.000    0.000   0.000
```

```
curl -s http://localhost:19999/api/v1/allmetrics | fgrep -i ntpd
# chart: ntpd_local.sys_precision (name: ntpd_local.sys_precision)
NETDATA_NTPD_LOCAL_SYS_PRECISION_PRECISION="-23"      # log2 s
NETDATA_NTPD_LOCAL_SYS_PRECISION_VISIBLETOTAL="-23"      # log2 s
# chart: ntpd_local.sys_offset (name: ntpd_local.sys_offset)
NETDATA_NTPD_LOCAL_SYS_OFFSET_OFFSET="-0"      # milliseconds
NETDATA_NTPD_LOCAL_SYS_OFFSET_VISIBLETOTAL="0"      # milliseconds
# chart: ntpd_local.sys_jitter (name: ntpd_local.sys_jitter)
NETDATA_NTPD_LOCAL_SYS_JITTER_SYSTEM="0"      # milliseconds
NETDATA_NTPD_LOCAL_SYS_JITTER_CLOCK="0"      # milliseconds
NETDATA_NTPD_LOCAL_SYS_JITTER_VISIBLETOTAL="0"      # milliseconds
# chart: ntpd_local.sys_tc (name: ntpd_local.sys_tc)
NETDATA_NTPD_LOCAL_SYS_TC_CURRENT="7"      # log2 s
NETDATA_NTPD_LOCAL_SYS_TC_MINIMUM="3"      # log2 s
NETDATA_NTPD_LOCAL_SYS_TC_VISIBLETOTAL="10"      # log2 s
# chart: ntpd_local.sys_rootdisp (name: ntpd_local.sys_rootdisp)
NETDATA_NTPD_LOCAL_SYS_ROOTDISP_DISPERSION="20"      # milliseconds
NETDATA_NTPD_LOCAL_SYS_ROOTDISP_VISIBLETOTAL="20"      # milliseconds
# chart: ntpd_local.sys_frequency (name: ntpd_local.sys_frequency)
NETDATA_NTPD_LOCAL_SYS_FREQUENCY_FREQUENCY="94"      # ppm
NETDATA_NTPD_LOCAL_SYS_FREQUENCY_VISIBLETOTAL="94"      # ppm
# chart: ntpd_local.sys_wander (name: ntpd_local.sys_wander)
NETDATA_NTPD_LOCAL_SYS_WANDER_CLOCK="0"      # ppm
NETDATA_NTPD_LOCAL_SYS_WANDER_VISIBLETOTAL="0"      # ppm
# chart: ntpd_local.sys_rootdelay (name: ntpd_local.sys_rootdelay)
NETDATA_NTPD_LOCAL_SYS_ROOTDELAY_DELAY="30"      # milliseconds
NETDATA_NTPD_LOCAL_SYS_ROOTDELAY_VISIBLETOTAL="30"      # milliseconds
# chart: ntpd_local.sys_stratum (name: ntpd_local.sys_stratum)
NETDATA_NTPD_LOCAL_SYS_STRATUM_STRATUM="4"      # stratum
NETDATA_NTPD_LOCAL_SYS_STRATUM_VISIBLETOTAL="4"      # stratum
# chart: netdata.runtime_ntpd_local (name: netdata.runtime_ntpd_local)
NETDATA_NETDATA_RUNTIME_NTPD_LOCAL_RUN_TIME="1"      # ms
NETDATA_NETDATA_RUNTIME_NTPD_LOCAL_VISIBLETOTAL="1"      # ms
```

but the charts are empty

**Comment by ScrumpyJack** [comment]
@Ferroin Let's imagine someone edits ntp.conf and makes a typo in the IPs of peers, and restarts NTP. All my alerts that pick up on high offset, or massive jitter etc won't help because the metrics aren't relevant yet, and I can't alert on stratum as it's always 4. And on top of that ??format=prometheus shows no metrics at all.

What do you suggest?

**Comment by Ferroin** [comment]
> @Ferroin Let's imagine someone edits ntp.conf and makes a typo in the IPs of peers, and restarts NTP. All my alerts that pick up on high offset, or massive jitter etc won't help because the metrics aren't relevant yet, and I can't alert on stratum as it's always 4. And on top of that ??format=prometheus shows no metrics at all, so i can't alert on a combination of poll/reach or something else.
> 
> What do you suggest?

Ideally in this case, we need an alarm for when we can't collect data from ntpd.

Barring that:

Short term, use some other tool to monitor whether ntpd has successfully synced with peers or not.

Long term, same thing I suggested in https://github.com/netdata/netdata/issues/7140#issuecomment-544633085, Netdata should get the ability to run arbitrary commands and track their exit status without needing to manually write a script to do it.

----

All that aside, I think there's a bug here that's not specific to the ntpd module.  Based on https://github.com/netdata/netdata/issues/7190#issuecomment-546335387, it looks like we're returning the last valid data continuously when we can't collect data for a given chart, which seems wrong to me.

**Comment by ilyam8** [comment]
>  it looks like we're returning the last valid data continuously when we can't collect data for a given chart

https://github.com/netdata/netdata/blob/265df2494708aa85293cc5c6dbf018d4d79ed9e4/collectors/python.d.plugin/ntpd/ntpd.chart.py#L274-L297


I see we start from empty `dict` and populate it on every iteration. We dont return stale data.

**Comment by ilyam8** [comment]
> https://github.com/netdata/netdata/issues/7190#issuecomment-546331998

Probably this will help. @ScrumpyJack you could add some additional `info`logs to better understand what is going on.

**Comment by Ferroin** [comment]
@ilyam8 Not the module, but Netdata itself.  I've seen cases before where a module was running but not returning any data successfully, charts were not displayed, and the API returned the last collected value for the metrics (from before the last restart of Netdata). It looks to me like that's what's happening here.

@ScrumpyJack Any chance you could try to reproduce this with `memory mode` set to something that doesn't save the data to disk and a restart of Netdata after the restart of ntpd?  I suspect you'll still not see charts, but also won't see any data for ntpd in the results of the allmetrics API call either.

**Comment by ilyam8** [comment]
> I've seen cases before where a module was running but not returning any data successfully, charts were not displayed, and the API returned the last collected value for the metrics (from before the last restart of Netdata).

Looks like a serious bug @mfundul @vlvkobal We need to check it

**Comment by Ferroin** [comment]
> > I've seen cases before where a module was running but not returning any data successfully, charts were not displayed, and the API returned the last collected value for the metrics (from before the last restart of Netdata).
> 
> Looks like a serious bug @mfundul @vlvkobal We need to check it

Agreed.  Prior to this, I'd just chalked it up to transient errors somewhere in hardware, as I'd never been able to reproduce it. This issue, however, is showing essentially the same symptoms I'd seen before, so I'm going to see if I can get it to reliably happen with a build of the current master branch.

**Comment by ScrumpyJack** [comment]
I'm struggling to build 1.18 for my environment (too many dependancies that I don't have), so I can't check if anything is fixed in latest - Will keep you posted

**Comment by ScrumpyJack** [comment]
Exactly the same behaviour when on netdata v1.18.1-30-nightly

**Comment by ScrumpyJack** [comment]
So, to sum it up, it would be cool to get netdata collecting stratum correctly, even when no other metrics are showing anything that can be charted. That way, we'd see a stratum 16 on INIT (which means that clock are unsynchronised)

**Comment by ilyam8** [comment]
About stratum. From the OP

> Also, the stratum reported is always 4, even though the client is at either 16 or 3.

I see we have `sys_stratum` and `peer_statum` charts. The wrong one is sys_statum ?

**Comment by ScrumpyJack** [comment]
> About stratum. From the OP
> 
> > Also, the stratum reported is always 4, even though the client is at either 16 or 3.
> 
> I see we have `sys_stratum` and `peer_statum` charts. The wrong one is sys_statum ?

Yes, sorry, that's fine

**Comment by ScrumpyJack** [comment]
We've run the plugin with debug, and when there is no ntp sync, we get this error

`
2019-11-01 16:45:24: receiving data
2019-11-01 16:45:24: python.d WARNING: plugin[main] : ntpd[ntpd] : unhandled exception on check : UnicodeEncodeError('ascii', u'\u0582\x00\x01\x12\x00\x00\x00\x00\x01\x7fversion="ntpd 4.2.6p5@1.2349-o Wed Apr 12 16:24:24 UTC 2017 (1)",\r\nprocessor="x86_64", system="Linux/4.1.12-112.14.10.el7uek.x86_64",\r\nleap=3, stratum=16, precision=-24, rootdelay=0.000, rootdisp=0.360,\r\nrefid=INIT, reftime=0x00000000.00000000, clock=0xe166dfa4.66ef22b5,\r\npeer=0, tc=3, mintc=3, offset=0.000, frequency=91.168, sys_jitter=0.000,\r\nclk_jitter=0.000, clk_wander=0.000\r\n\x00', 0, 1, 'ordinal not in range(128)'), skipping the job`

**Comment by Ferroin** [comment]
Well, that explains why we're getting an error, for some reason there's a stray Unicode character outside of the ASCII range at the start of the data stream, which we're trying to encode into ASCII.

U+0582 is ւ, which is an Armenian character (a lowercase Ywin I believe). I'm betting we're just getting garbage at the start of the stream or that what is there is getting misinterpreted as UTF-8 when it isn't.

**Comment by ScrumpyJack** [comment]
Can anyone else reproduce this issue?

**Comment by vzDevelopment** [comment]
I was able to replicate this on a CentOS 7 box running Python 2.7.5. Note: It works fine with Python 3 because Python 3 defaults to UTF-8.

The issue is with this line: 
https://github.com/netdata/netdata/blob/c3b201b2b5e745e2bf736f77ed771933d3eb0024/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py#L250
If you comment it out, then it no longer crashes.

You can fix format throwing an error by using:

```
u'final response: {0}'.format(data)
```

However, the debug call will then throw the error because of the `str` map:
https://github.com/netdata/netdata/blob/c3b201b2b5e745e2bf736f77ed771933d3eb0024/collectors/python.d.plugin/python_modules/bases/loggers.py#L124
Changing the `str` to `unicode` would fix this, but it would break it in Python 3.

Another option would be to do something like this which would work in both Python 2 and 3, but it isn't fixing the underlying problem and other plugins might run into the same issue:
```
             if self._check_raw_data(data):
                 break

-        self.debug('final response: {0}'.format(data))
+        try:
+            self.debug('final response: {0}'.format(data))
+        except UnicodeEncodeError:
+            ascii_data = data.encode('ascii', 'backslashreplace')
+            self.debug('final response with non-ascii characters escaped: {0}'.format(ascii_data))
+
         return data

     def _get_raw_data(self, raw=False, request=None):
```

N.b. I've put the escaping bit in the catch so for those using Python 3 it will show the actual UTF-8 characters.

**Comment by Ferroin** [comment]
We might want to consider just putting that type of UnicodeEncodeError catch behavior inside the logging interface itself. That would prevent this particular situation from being an issue for any Python plugins again, at least for logging.

**Comment by ilyam8** [comment]
Thanks @vzDevelopment!

@ScrumpyJack you need to update netdata to get the fix.

However 

> Also, the stratum reported is always 4, even though the client is at either 16 or 3.

Problem is not fixed, i suggest to open a new issue, because this issue is

> No NTP metrics when ntpd not synchronised
