### ISSUE TITLE
Sometimes graphite metrics for load average are missing

### ISSUE THREAD

**Issue by kam1sh** [netdata/netdata#7191]
Hi! Firstly, thank you for Netdata, it really helps us to collect metrics from the infrastructure, though sometimes it has issues like that.
##### Bug report summary
Similar to #2602, Netdata sometimes does not send load average metrics to the carbon/graphite. By sometimes I mean 1-3 points out of 12 (in a minute). Also, in the Netdata web UI everything seems fine.
Here's Grafana screenshot:
![image](https://user-images.githubusercontent.com/14600211/67488508-9eaa9a80-f678-11e9-8f2f-330bc527c380.png)

##### OS / Environment
Ubuntu 18.04.2
Backend configuration:
```
[backend]
        enabled = yes
        destination = tcp:<...>
        update every = 5
        prefix = <...>
        type = graphite
        data source = average
        hostname = <...>
```
##### Netdata version (ouput of `netdata -V`)
v1.18.1-20-g0084bbdd
##### Component Name
Graphite backend
##### Steps To Reproduce
I tried to reproduce that issue in a completely local VM, but no luck =( But I decided to file issue to find out who else got that behavior. After the weekend I'll recompile Netdata with debug and post logs.
##### Expected behavior
Netdata sends load average metrics every five seconds

**Comment by thiagoftsm** [comment]
Hi @kam1sh ,

What is the memory mode you are using with your netdata?

**Comment by kam1sh** [comment]
@thiagoftsm Sorry, forgot to show global section:
```
[global]
        history = 3600
        memory mode = mem
```

**Comment by thiagoftsm** [comment]
Thank you @kam1sh !

Now that you gave us more information, I am thinking that we can have problem in two places and I already assigned our team for they help us. For we be sure about the problem that is happening, I will do more two questions for you:

1 - Can you see the same gaps on Netdata for the same time?
2 - Do you have in your error.log messages like these:
- BACKEND: failed to write data to database backend ' '. Willing to write X bytes, wrote Y bytes. Will re-connect.
- BACKEND: failed to update database backend 
?
Case you do not have exactly these messages, can you share with us error messages with the keyword BACKEND?

Best regards!

**Comment by kam1sh** [comment]
1. Everything looks fine:
![image](https://user-images.githubusercontent.com/14600211/67591356-ec510100-f765-11e9-995e-676249916cde.png)
2. No. Of the errors there's only messages about failed plugins, like `ERROR: web_log[squid_log2] : /var/log/squid/access.log not readable or not exist`.

I can collect debug logs, just tell what flags I have to enable. Only D_BACKEND?

**Comment by kam1sh** [comment]
I find interesting next messages:

> ...
> 2019-10-25 20:37:26: netdata DEBUG : BACKENDS : (0785@backends/b:backends_main  ): BACKEND: not sending dimension 'load1' of chart 'system.load' from host '<...>', its last data collection (1572025040
> ) is not within our timeframe (1572025041 to 1572025046)
> 2019-10-25 20:37:26: netdata DEBUG : BACKENDS : (0785@backends/b:backends_main  ): BACKEND: not sending dimension 'load5' of chart 'system.load' from host '<...>', its last data collection (1572025040
> ) is not within our timeframe (1572025041 to 1572025046)
> 2019-10-25 20:37:26: netdata DEBUG : BACKENDS : (0785@backends/b:backends_main  ): BACKEND: not sending dimension 'load15' of chart 'system.load' from host '<...>', its last data collection (157202504
> 0) is not within our timeframe (1572025041 to 1572025046)
> ...
> 2019-10-25 20:37:26: netdata DEBUG : BACKENDS : (0795@backends/b:backends_main  ): BACKEND: sending host '<...>', metrics of 248 dimensions, of 79 charts. Skipped 3 dimensions.
> 2019-10-25 20:37:26: netdata DEBUG : BACKENDS : (0805@backends/b:backends_main  ):  
> BACKEND: buffer has 20813 bytes, added metrics for 248 dimensions, of 79 charts, from 1 hosts
> ...
> 2019-10-25 20:37:31: netdata DEBUG : BACKENDS : (0795@backends/b:backends_main  ): BACKEND: sending host '<...>', metrics of 251 dimensions, of 79 charts. Skipped 0 dimensions.
> 2019-10-25 20:37:31: netdata DEBUG : BACKENDS : (0805@backends/b:backends_main  ): BACKEND: buffer has 21025 bytes, added metrics for 251 dimensions, of 79 charts, from 1 hosts
> ...

It looks like sometimes Netdata finds load average metrics as stale, which results in sending 248 metrics instead of 251.

If you need complete log, just say how to send it to you.

**Comment by thiagoftsm** [comment]
About the debug messages, the D_BACKEND already gave us important information, as you can see we had 5 second difference in the error message and this can be the description of the output that you have seen in your Graphite.
Do you have gaps on your graphite related to these time interval ?

**Comment by kam1sh** [comment]
In Friday - yes, I had. But today I checked it again and now there is no correlation. Looks like the cause in somewhere else...

**Comment by thiagoftsm** [comment]
Hi @kam1sh ,

We were talking here now about the problem you reported and we would like to ask you to do a change in your configuration, please, can you set `update every = 6`.The load average module is updating stats once in 5 seconds. That's why there are moments when data for load average is not present on every backend update. I advise setting update every = 6 or more.

**Comment by mfundul** [comment]
> 
> 
> @thiagoftsm Sorry, forgot to show global section:
> 
> ```
> [global]
>         history = 3600
>         memory mode = mem
> ```

`memory mode = mem` is not valid. Please configure your netdata as described [here](https://github.com/netdata/netdata/tree/master/database#memory-modes).

**Comment by kam1sh** [comment]
@thiagoftsm changed interval and now graphs looks fine! Does that mean that Netdata works well only with `update every`>=6? Or it's a temporary workaround?
Also I think it's better to change issue title to _Gaps in graphite storage for load average metrics_, if you don't mind.
@mfundul oh, I never saw any warnings about that in netdata logs... changed to `ram`, thank you!

**Comment by vlvkobal** [comment]
> Does that mean that Netdata works well only with update every>=6?

Netdata works well even with `update every = 1`. The problem is not with Netdata but with the way Grafana displays data in a chart when a data record is missing.

It's a valid way of displaying data - if there is no value, you see a gap in the chart. I don't know, but Graphana might allow configuring this behavior.

As for the Netdata side, the way load average values are sent is also valid. Netdata doesn't repeat old records, it sends only new information.

**Comment by kam1sh** [comment]
@vlvkobal Sorry, I don't mean Netdata, but the load average module in particular.

**Comment by vlvkobal** [comment]
There is no problem with `load average` module too. It reads data once in 5 seconds because an operating system doesn't provide any new data inside this interval anyway.

**Comment by vlvkobal** [comment]
In general, any module can have its own data collecting interval. You can set `Null value` in `Graph panel` to `connected` in Grafana for charts with gaps if you want to see a smooth line.

**Comment by kam1sh** [comment]
OK, we will use null value for now. But it would be nice to see at least previous value of load average, if latest info is not available. And/or some documentation about that behavior, for another users.

Anyway, thank you all. I'm closing the issue.
