### ISSUE TITLE
netdata-updater.sh always updates during first run after installation

### ISSUE THREAD

**Issue by knatsakis** [netdata/netdata#7195]
##### Bug report summary
The netdata-updater.sh always performs a reinstallation during the first run on a clean installation

##### OS / Environment
All

##### Netdata version (ouput of `netdata -V`)
v1.18.1

##### Component Name
netdata-updater.sh, kickstart.sh kickstart-static64.sh

##### Steps To Reproduce
Perform a clean netdata installation using kickstart.sh. Run the netdata-updater.sh script (/etc/cron.daily/netdata-updater.sh). A reinstallation/update will be performed regardless of whether there is a newer version available or not.

##### Expected behavior
An update should only occur if there is a newer version available.

**Comment by amoss** [comment]
Does this still need triage - the reproduction steps look clear and it is an internal report?

Please estimate the length of the fix (pulling any of us that you need into an estimation meeting), put the estimate on the issue and remove the triage label.

**Comment by knatsakis** [comment]
Hi @amoss,

Yes it is an internal report. The reproduction steps are clear but **the cause** is still unclear too me, so I think we should keep the `needs triage` label.

**Comment by prologic** [comment]
This is now the end result:

```sh
 enjoy real-time performance and health monitoring...

Fri Jan 31 03:35:15 UTC 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Fri Jan 31 03:35:15 UTC 2020 : INFO:  Current Version: 001019000399
Fri Jan 31 03:35:15 UTC 2020 : INFO:  Latest Version: 001019000336
Fri Jan 31 03:35:15 UTC 2020 : INFO:  Newest version 001019000399 <= 001019000336 is already installed
ERROR: Test failed
/netdata # /etc/periodic/daily/netdata-updater
Fri Jan 31 03:35:56 UTC 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Fri Jan 31 03:35:56 UTC 2020 : INFO:  Current Version: 001019000399
Fri Jan 31 03:35:56 UTC 2020 : INFO:  Latest Version: 001019000336
Fri Jan 31 03:35:56 UTC 2020 : INFO:  Newest version 001019000399 <= 001019000336 is already installed
/netdata # echo $?
1
/netdata #
```
