### ISSUE TITLE
Remove support for local tarballs from netdata-updater.sh

### ISSUE THREAD

**Issue by knatsakis** [netdata/netdata#7196]
##### Feature idea summary
Remove support for local tarballs from netdata-updater.sh

The netdata-updater.sh does not need to support local tarballs. If the user needs to upgrade their netdata installation on a system without internet access, they can reinstall using kickstart.sh or kickstart-static64.sh.

The netdata-updater.sh should only be used for non-interactive, automatic updates on systems with internet access.

Removing said support will make this script simpler and more robust.

**Comment by thiagoftsm** [comment]
Hi @knatsakis ,

I remember this feature was brought recently and I see one positive thing on it, when we need to upgrade various servers inside a network and this Network has NFS shares, you do not need to do download again. Is this feature really impacting the installer performance for we remove it?

**Comment by knatsakis** [comment]
Hi @thiagoftsm,

It is impacting it's complexity to be precise.

Considering the case that you mention, isn't it a manual/interactive action by the user?
If so, then why not use kickstart.sh/kickstart-static64.sh with the `--local-files` option?

Is there really a difference between updating and installing the latest version on top of the previous one?

**Comment by thiagoftsm** [comment]
> Hi @thiagoftsm,
> 
> It is impacting it's complexity to be precise.

I understood now the motive you are working on this.

> Considering the case that you mention, isn't it a manual/interactive action by the user?

It would be manual.

> If so, then why not use kickstart.sh/kickstart-static64.sh with the `--local-files` option?

I agree 100%.

> Is there really a difference between updating and installing the latest version on top of the previous one?

Zero difference. You convinced me with all questions, because you forced me to reflect. Thank you!
