### ISSUE TITLE
kickstart-static64.sh does not write a proper REINSTALL_COMMAND to .environment

### ISSUE THREAD

**Issue by knatsakis** [netdata/netdata#7198]
##### Bug report summary
kickstart-static64.sh does not write a proper REINSTALL_COMMAND to /opt/netdata/etc/netdata/.environment

##### OS / Environment
kickstart-static64.sh installations

##### Netdata version (ouput of `netdata -V`)
v1.18.1

##### Component Name
kickstart-static64.sh

##### Steps To Reproduce
Install using kickstart-static64.sh. The REINSTALL_COMMAND in /opt/netdata/etc/netdata/.environment is always `./netdata-installer.sh --install /opt`

##### Expected behavior
The REINSTALL_COMMAND should contain all the options that where passed to the initial installer (esp. --auto-updates)

**Comment by Kramerican** [comment]
As a user who is quite confused as to what is happening with auto-updates, I just have a question: Does this explain why, seemingly, netdata removes the /etc/cron.daily/netdata-updater cron job on its own accord?

I ask as I thought this had been solved, re-installed netdata and doublechecked that the updater script was in the cron folder.

Now when I check I see I am several versions behind, and the cronjob has disappeared.

**Comment by knatsakis** [comment]
@Kramerican, I am sorry that this has caused confusion.

I think this issue, along with #7197 explains the behavior that you are describing. Auto-update does not work with kickstart-static64.sh currently. (Only with kickstart.sh)

We are working to resolve this issue and you can monitor progress here and in #7197.

Thanks a lot for your feedback!
