### ISSUE TITLE
Node-list not loading on macOS Safari 13.0.2

### ISSUE THREAD

**Issue by AndLindemann** [netdata/netdata#7201]
##### Bug report summary
On MacOS Safari 13.0.2 the node menu in the top left corner does not load the list of nodes from the registry. It is stuck on "Loading, please wait..."
The javascript console displays an error that might be related:
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'registryAgents.concat')

<img width="1436" alt="Bildschirmfoto 2019-10-27 um 13 45 26" src="https://user-images.githubusercontent.com/4157845/67634817-cbe98980-f8c0-11e9-8265-7be04524a8c2.png">

##### OS / Environment
macOS 10.15 Catalina
Safari 13.0.2 (15608.2.30.1.1)
 
##### Netdata version (ouput of `netdata -V`)
netdata v1.18.1-26-nightly

##### Steps To Reproduce
1. Access netdata dashboard on Safari 13.0.2
2. Try to open list of nodes in the top left corner

##### Expected behavior
List of nodes should be display. Instead it is stuck on "Loading, please wait..."

**Comment by thiagoftsm** [comment]
Hi @AndLindemann ,

I will do a question for you to confirm that I could repeat the error you are reporting here, is your safari doing a request for a netdata without TLS (https)?

Best regards!

**Comment by AndLindemann** [comment]
Yes, no TLS here. Direct access to the Netdata webserver via HTTP on default port 19999.

**Comment by jacekkolasa** [comment]
@AndLindemann I am investigating this issue but it's hard to guess what happened. Can you please check if in different browser you have the same results? If yes, perhaps doing `localStorage.clear()` in Safari will help?

Also can you tell me if you have any errors from `/api/v1/registry?action=access...` calls? For me it looks like the `registry?action=access` call error has happened and at the same time there is invalid/old `localStorage["cloud.sync"]` property

**Comment by AndLindemann** [comment]
I also checked on my mobile (iOS Safari) - works fine.
iPad (iPadOS Safari) - same issue, also not loading the list.

Registry calls seem to work fine.
<img width="772" alt="Bildschirmfoto 2019-10-28 um 17 33 19" src="https://user-images.githubusercontent.com/4157845/67697668-3544c780-f9a9-11e9-938d-e03cebd22d07.png">

However the 3 calls out to registry.my-netdata.io all only return the following same json code:
{
    "status": "redirect",
    "registry": "https://registry.my-netdata.io"
}

There is no other data being returned from registry.my-netdata.io and these are the only requests going out to that domain.

**Comment by jacekkolasa** [comment]
Hi @AndLindemann, the information you provided helper me to recreate this bug, but it's happening for me only when i am logged in to the cloud, is it the case in your situation?

I see there's a problem with non-cloud registry on Safari (and perhaps similar issue on newest Firefox, version 70 - [issue](https://github.com/netdata/netdata/issues/7227) ), and we need to do more research in that area.

I think i can make a fix for that current scenario, which will not fix non-cloud registry on Safari, but at least allow us to see the nodes from Cloud. Could you please check, if running following line in Safari console fixes the problem? 

```
localStorage.setItem("cloud.sync", JSON.stringify({[cloudAccountID]: new Date().getTime()}))
```
You need to run it and refresh the page

**Comment by AndLindemann** [comment]
Yes, this is the case for me, I'm using the cloud registry.
That line works. After executing it, I can see the nodes listed in the menu.

**Comment by jacekkolasa** [comment]
Great, thanks!
