### ISSUE TITLE
Incorrect streaming master url

### ISSUE THREAD

**Issue by nyacat** [netdata/netdata#7204]
##### Bug report summary
when switch to stream node, the whole nav url broken,
e.g:
master url: `http://1.2.3.4:19999/`
slave url: `http://1.2.3.4:19999/host/"salve hostname"`

once click the slave url, the whole nav url become something I don't understand
slave url become:  `http://1.2.3.4:19999/host/"salve hostname"/host/"salve hostname"`
and can't go back to master
![img1](https://user-images.githubusercontent.com/2476717/67664135-ff501500-f9a1-11e9-8a7d-05431ab1ca5d.jpg)
![img2](https://user-images.githubusercontent.com/2476717/67664136-ff501500-f9a1-11e9-939d-e5292a757bb4.jpg)

##### OS / Environment
Master: Debian 10.1
Slave: Debian 9.11
##### Netdata version (ouput of `netdata -V`)
Both: netdata v1.18.1-26-nightly

**Comment by thiagoftsm** [comment]
According what we are seeing in your screen, it looks like that your host name has a space, that is a character not expected in HTTP protocol requests, please, can you confirm this?

**Comment by nyacat** [comment]
yup, I confirm I've set hostname with space.

**Comment by thiagoftsm** [comment]
All right, please, case you can change the hostname and confirm that Netdata is working fine or have a problem with FQDN names, let us know.

**Comment by nyacat** [comment]
I've change hostname without space, seem working fine

**Comment by thiagoftsm** [comment]
Nice I am glad with this, I will close this issue now, but be free to reopen case you detect the same problem.
Case you have any problem, please, let us know for we help you again.

Best regards!
