### ISSUE TITLE
Fix default memory mode in getting started guid

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7208]
https://docs.netdata.cloud/docs/getting-started/#change-how-long-netdata-stores-metrics

It still says that the default memory mode is RAM. We need to correct it.

**Comment by mfundul** [comment]
I don't see it.

**Comment by cakrit** [comment]
`By default, Netdata uses a database engine uses RAM to store recent metrics.`

**Comment by mfundul** [comment]
That should be fixed as:
`uses a database engine that uses RAM to store recent metrics`

**Comment by joelhans** [comment]
I agree with @mfundul: there's a missing `that` in the first sentence. I'll fix that.

I don't know if I agree with your initial concern, @cakrit, because I think the rest of the paragraph explains what the database engine does, and makes it clear it's not RAM-only, like `save` is. That said, I'm happy to try to clear up any concern by rewriting the whole paragraph to something like this:

> By default, Netdata uses a database engine that uses both RAM and disk to store metrics. Recent metrics are stored in the system's RAM, while historical metrics are "spilled" to disk by the database engine to keep RAM usage low.

How does that look?

**Comment by Ferroin** [comment]
'database engine' sounds a bit odd to me in both uses in that snippet, even if that's what we call the actual implementation. The usage in both cases here is technically jargon, but it's being presented like a fixed phrase that we're expecting people to know (looking at it from a linguistics perspective, it feels like a questionable translation of an idiom from some other language, the two words used kind of make sense together, but are not really used together in this way by most people (at least, not in AmE, and probably not in most other dialects of English)).

Perhaps something like this:

> By default, Netdata uses a custom database which uses both RAM and the disk to store metrics. Recent metrics are stored in the system's RAM to keep access fast, while historical metrics are 'spilled' to disk to keep RAM usage low.

That way we don't worry about confusing people with the terminology, and are a bit more clear about why we keep recent data in RAM.

**Comment by joelhans** [comment]
@Ferroin You make a great point. I'd be happy with implementing that verbiage instead.
