### ISSUE TITLE
Newbie Q : Instrumenting C++ Cloud Application - Options

### ISSUE THREAD

**Issue by AidanMcP** [netdata/netdata#7212]
Apologies, this is a very high level question, and perhaps has been asked in other formats and forums, but hopefully it'll be a quick one for some kind soul to point me in the right direction.

Background: I have been looking at netdata for system monitoring, and it's (obviously!) superb. Now, I wan to look at monitoring my own application. It's a C++ data store, running in a distributed cloud environment.  I have KPIs like pass/fail counts, latency values, and slightly more complex latency percentile stats which I want to monitor,  I had initially thought I'd be exposing the data in a Prometheus metrics format / webpage to be pulled/scraped from a central node, but from looking at the netdata documentation I have push/pull options such as statsd and others.

So basically I am wondering what my high level options are. My basic requirements would be
- Is a C++ application I'd be instrumenting. Will be cloud architecture - i.e. 100s of instances.
- Instrumentation can't significantly impact performance.
- Need ~1 sec frequency of stats on the application, but would then want rolled up summary available historically (with less granularity obviously)
- Cheaper implementation cost the better. I'd guess that publishing stats from my app would be cheaper to implement that pushing stats to another endpoint.

Any guidance much appreciated. I appreciate some replies might be RTFM - I am still in the process of reading all documentation and options, but just posting this question as some direction/links from experienced people in the community are very valuable.

Thanks in advance,
Aidan

**Comment by vlvkobal** [comment]
You can easily turn your application into an external Netdata plugin. Look at the [fping](https://github.com/netdata/netdata/tree/master/collectors/fping.plugin) or [ioping](https://github.com/netdata/netdata/tree/master/collectors/ioping.plugin) plugins. [Here](https://github.com/koct9i/ioping/pull/41) you can find changes to the ioping itself. All you need is just send statistics to Netdata using [external plugins API](https://docs.netdata.cloud/collectors/plugins.d/#external-plugins-api).

**Comment by ilyam8** [comment]
>  exposing the data in a Prometheus metrics format
> statsd

Both looks good to me. I would avoid doing something netdata specific.

**Comment by Ferroin** [comment]
I'm with @ilyam8 on this, I think it makes more sense to not be Netdata-specific for it.  I'd personally favor having the app push data out in statsd format,a s that's a bit more portable than the Prometheus format.

The [statsd wiki](https://github.com/statsd/statsd/wiki) lists two C++ client implementations: [cpp-statsd-client](https://github.com/vthiery/cpp-statsd-client) and [statsd-client-cpp](https://github.com/talebook/statsd-client-cpp).  I'd probably choose the first one myself, but mostly because it doesn't require any extra handling when linking.

**Comment by AidanMcP** [comment]
Thankyou @vlvkobal @ilyam8 and @Ferroin for the advice here - very much appreciated.

**Comment by AidanMcP** [comment]
Happy to close this. I went with the statsd option. Thanks again for the help.
