### ISSUE TITLE
What is the best way to send alarm notifications as gRPC calls?

### ISSUE THREAD

**Issue by er1cthe0ne** [netdata/netdata#7231]
##### Question summary

Netdata looks great and I like how it focus on data :)

I am evaluating Netdata and want to see what is the best model to send alarm notifications as gRPC calls? Any idea or suggestions? Would I be looking at doing a custom "alarm-notify.sh" script?

Thanks in advance!

**Comment by thiagoftsm** [comment]
Hi @er1cthe0ne ,

Nowadays netdata supports different ways to send the alarms as you can see theIRC example https://docs.netdata.cloud/health/notifications/irc/ ,  you do not need to do a specific `alarm-notify.sh` , my suggestion is you create a PR like #7013 that extends `alarm-notify.sh` . 

I executed a search on google and I verified that gRPC has REST API( https://grpc.io/blog/coreos/ ), this is probably the simplest way to extend `alarm-notify.sh`.

Case you decide to follow this road, you will help not only you, but everybody that works with gRPC. 

Any doubt, please, let us know.

**Comment by er1cthe0ne** [comment]
Hi thiagoftsm, 

Thanks for the pointing me to the right direction. I got the idea now.
