### ISSUE TITLE
Monitoring website availability and metrics

### ISSUE THREAD

**Issue by supersexy** [netdata/netdata#7235]
I am not sure if this is still inside the scope of netdata, however I would like to put some website metrics on the dashboard, similar to the things that sitespeed.io provides, but also:

* website online / offline
* tls certificate ok / not ok
* dns data etc.

Did somebody ntegrate this into netdata and I was not able to find it? 
Or is this too feature-creepy?

Thanks for your attention!

**Comment by Ferroin** [comment]
I would suggest looking into the [httpcheck collector](https://docs.netdata.cloud/collectors/go.d.plugin/modules/httpcheck/).

If you use an actual hostname in the URL and make sure to specify it as HTTPS, it can trivially check all three of the things you mentioned, though it can only give a pass/fail for all together right now.

Realistically, we could probably extend httpcheck to give more granular error statuses (at minimum handling the cases of TLS validation failing and DNS lookup failing), though I'm probably not the best person to try to do that (I have exactly zero experience with coding in Go).

It might also be worth looking into adding a collector to pull metrics from sitespeed.io itself, as it appears to collect some data that is beyond the scope of Netdata (for example, I seriously don't see us ever getting the ability to run Lighthouse audits against sites).

**Comment by ilyam8** [comment]
hi @supersexy 

> website online / offline
https://github.com/netdata/go.d.plugin/tree/master/modules/httpcheck

> tls certificate ok / not ok
https://github.com/netdata/go.d.plugin/tree/master/modules/x509check

> dns data etc.

what dns data? what dns?

**Comment by ilyam8** [comment]
> Realistically, we could probably extend httpcheck to give more granular error statuses

i even did it but commented out to not break compativility with python ver

https://github.com/netdata/go.d.plugin/blob/52a2cc00fff1f9c8661bef16b84bdb112941a5cb/modules/httpcheck/collect.go#L61-L76

**Comment by supersexy** [comment]
thank you, this looks verx interesting, will take a look. 
Granularity would be very much appreciated. 
Re DNS: check if the domain still is served by the expected DNS server(s) to the expected ip(s) is what I do.

**Comment by thiagoftsm** [comment]
Hi @supersexy ,

I am closing this issue, but case you have the same problem again, please, be free to reopen it.

Best regards!
