### ISSUE TITLE
Netdata upgrade from 1.10.0 to 1.18.1 odd error logs now

### ISSUE THREAD

**Issue by jeremyjpj0916** [netdata/netdata#7237]
### Question summary

Been awhile since I been in the netdata repo, gotta say yall have made some great improvements on documentation and ways to install netdata and build it into lots of environments, so kudos there!

Onto my issue/concern/question:

I run netdata w a master/slave model.

1-3 slaves stream to a master node. I generally use Netdata for Statsd and some host level monitoring. I run Netdata on OpenShift Origin containers. After moving from v1.10.0 to v1.18.1

I see some odd error logs, maybe these have been seen before or someone may have an explanation to what there error logs are? I have noticed some master nodes give this error and some don't too which is really odd(I have multiple environments on the Origin cluster hence multiple master nodes too, all following the same docker deployment). Any ideas what could cause this error and how I could fix it? This error seems to be unimpactful as my statsD metrics are still making it through just fine:
```
2019-11-01 05:36:20: netdata ERROR : WEB_SERVER[static5] : Incoming connection on '10.129.2.1' does not match a numeric pattern, and host could not be resolved (err=Name does not resolve) (errno 22, Invalid argument)
 | 2019-11-01 05:36:21: netdata ERROR : WEB_SERVER[static4] : Incoming connection on '10.128.4.1' does not match a numeric pattern, and host could not be resolved (err=Name does not resolve) (errno 22, Invalid argument)
 | 2019-11-01 05:36:23: netdata ERROR : WEB_SERVER[static5] : Incoming connection on '10.129.2.1' does not match a numeric pattern, and host could not be resolved (err=Name does not resolve) (errno 22, Invalid argument)
  | 2019-11-01 05:36:24: netdata ERROR : WEB_SERVER[static4] : Incoming connection on '10.130.4.1' does not match a numeric pattern, and host could not be resolved (err=Invalid flags) (errno 107, Socket not connected)
```

This is how I am currently deploying via a Dockerfile now:
```
FROM docker.repo.company.com/repo/alpine:3.10

USER root

ENV NETDATA_VERSION=1.18.1

# install required packages
RUN apk add alpine-sdk bash curl zlib-dev util-linux-dev libmnl-dev gcc make git autoconf automake pkgconfig python logrotate

ADD . /gitsources
#Fix /opt/netdata path and logrotate
RUN chmod -R 777 /gitsources \
    && touch /etc/logrotate.d/netdata \
    && chmod 777 /etc/logrotate.d/netdata \
    && mkdir /opt/netdata \
    && chmod -R 777 /opt/netdata \
    && chmod 777 /gitsources/kickstart-static64.sh \
    && chmod 777 /gitsources/netdata-v$NETDATA_VERSION.gz.run

RUN bash /gitsources/kickstart-static64.sh --dont-wait --dont-start-it --no-updates --local-files /gitsources/netdata-v$NETDATA_VERSION.gz.run /gitsources/sha256sums.txt

COPY ./system/netdata.conf /opt/netdata/etc/netdata/netdata.conf
COPY ./conf.d/stream.conf /opt/netdata/usr/lib/netdata/conf.d/stream.conf

RUN chmod -R 777 /opt/netdata

WORKDIR /
ENV NETDATA_PORT 19999
EXPOSE 19999 19999/udp 8125 8125/udp

CMD /opt/netdata/bin/netdata -D -p 19999
```

**Comment by amoss** [comment]
Hello, it is great to hear that the improvements to the docs are useful. There has been a lot of effort on improving them lately and we are very happy that it show. There is a big PR on the streaming docs working its way through the system at the moment, should be merged soon.

The error that you are seeing are from a new feature that was added in v1.18. The access control lists for web connections used to work entirely on IP addresses. We now allow DNS hostnames in the patterns as well. Resolving the hostnames (and doing a DNS query to check they are valid) is much slower than comparing the IP addresses internally against the pattern. If netdata performs the check but was unable to resolve a hostname then we log the error in resolving the DNS to indicate that it has occurred.

If you would like to disable this behaviour it is configurable - if you have upgraded from an older version then all of your ACL patterns will be numeric IP addresses. To disable the DNS check you can add this to your netdata.conf in the `[web]` section:
```
    allow connections by dns = no
    allow dashboard by dns = no
    allow badges by dns = no
    allow registry by dns = no
    allow streaming by dns = no
    allow netdata.conf by dns = no                                                                                                                                                           
    allow management by dns = no
```

**Comment by jeremyjpj0916** [comment]
I tried the suggested conf changes:

![image](https://user-images.githubusercontent.com/31913027/68033115-77198a80-fc95-11e9-8b35-15d2659c3730.png)

But seemingly the ERROR messages are still persisting:

![image](https://user-images.githubusercontent.com/31913027/68033226-a5976580-fc95-11e9-85cb-5935684dba39.png)

**Comment by amoss** [comment]
It is difficult to diagnose the problem as normally the next step would be to ask you to enable debug so that I can see what happens in `libnetdata/socket/socket.c:1012`. If the allow dns options are disabled they logged in debug mode and prevent execution of the piece of code that generates the error. Unfortunately the `kickstart-static64.sh` installer uses a pre-compiled binary that does not include debugging.

Can we check the version number? The stable v1.18 release did not contain this fix, it went into v1.18.1. If you `curl 10.128.100.1:19999/api/v1/info | grep version` (replacing the IP address with the container logging the errors instead of the one sending the stream), what output do you see?

**Comment by jeremyjpj0916** [comment]
Master node endpoint response:
```
{
	"version": "v1.18.1",
	"uid": "3b7284de-fcb6-11e9-9e6a-0a580a82174f",
	"mirrored_hosts": [
		"netdata-118-72xld",
		"kong-1034-fvd92",
		"kong-1033-phj4k"
	],
	"alarms": {
		"normal": 0,
		"warning": 0,
		"critical": 0
	},
	"os_name": "Alpine Linux",
	"os_id": "alpine",
	"os_id_like": "unknown",
	"os_version": "unknown",
	"os_version_id": "3.10.2",
	"os_detection": "/etc/os-release",
	"kernel_name": "Linux",
	"kernel_version": "3.10.0-957.12.1.el7.x86_64",
	"architecture": "x86_64",
	"virtualization": "hypervisor",
	"virt_detection": "/proc/cpuinfo",
	"container": "docker",
	"container_detection": "dockerenv",
	"collectors": [
		{
			"plugin": "proc.plugin",
			"module": "/proc/uptime"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/meminfo"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/dev"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/stat/nf_conntrack"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/loadavg"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/sockstat"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/stat"
		},
		{
			"plugin": "netdata",
			"module": "stats"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/netstat"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/vmstat"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/net/softnet_stat"
		}
	]
}
```
Slave Stream nodes are on 1.10.1 still, I have not upgraded them yet.

**Comment by amoss** [comment]
I need to rebuild the static binary so that it has debugging information enabled. I will come back to you shortly with a replacement.

**Comment by jeremyjpj0916** [comment]
If you see a way to drop into my docker file above a preferred approach to build from source I can temporarily comment out my existing build line using the made binary run file. If that would give you good insight, just include w/e --arg needed to  enable debug mode too. That will be fine too @amoss the hosts I am testing on can connect to public net.

**Comment by amoss** [comment]
I've just gone back to check and the fix missed the merge window on the v1.18.1 release. It is in the nightly build, but it will not appear in the stable channel until v1.19 (which is about three weeks from now).
 
In the mean-time a quick fix would be to run the kickstart script twice so that it does an update to the nightly build (cutting from https://github.com/netdata/netdata/blob/master/packaging/installer/UPDATE.md) :
```
RUN bash /gitsources/kickstart-static64.sh --dont-wait --dont-start-it --no-updates --local-files /gitsources/netdata-v$NETDATA_VERSION.gz.run /gitsources/sha256sums.txt
RUN bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --no-updates
```

The new version will pick up the config options and disable the checks. Does this work?

**Comment by jeremyjpj0916** [comment]
@amoss I will give that a test and confirm if it fixes the error logs! I am fine with it printing error logs for now anyways to my stdout, its not too obnoxious. Glad we got to the bottom of it. Appreciate it. Will confirm back here after a test and then close the issue.

**Comment by jeremyjpj0916** [comment]
Ehh, I remember hitting this before:

```
Step 8/17 : RUN bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh ) --no-updates
--
  | ---> Running in 7362af828d99
  |  
  | /bin/sh: syntax error: unexpected "("
  | Removing intermediate container 7362af828d99
  | error: build error: The command '/bin/sh -c bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh ) --no-updates' returned a non-zero code: 2
```

Lets just wait till v1.19.x and I can confirm on the fixes. Thx.

**Comment by amoss** [comment]
I've asked you to do something that is very over-complicated as I've pulled something from a slack channel in a hurry where we are trying to fix your issue. I've had a think about it and realise now that there is a simpler way to fix it. The default behaviour of the `kickstart-static64.sh` is to pull the nightly from storage.

Please try changing your existing `RUN` line to this:
```
RUN bash /gitsources/kickstart-static64.sh -dont-wait --dont-start-it --no-updates
```

Instead of using the local copy of the release it will just pull the nightly directly over your internet connection.

**Comment by jeremyjpj0916** [comment]
Is there a --debug arg I need to be adding to the netdata CMD call at the bottom right?

**Comment by jeremyjpj0916** [comment]
Confirmed, your conf arguments work with the nightly. Thanks! Will await the netdata 1.19 release on those error messages!
