### ISSUE TITLE
Typo on https://www.netdata.cloud/

### ISSUE THREAD

**Issue by tzikis** [netdata/netdata#7241]
#### Summary

Hi guys, minor issue here but I didn't know where else to notify you about it. There's a small typo on the https://www.netdata.cloud/ website, in the integrations/plugins section. Instead of **Raspbian** you have **Raspian**

I would make a PR, but i'm not even sure that the website is publicly available (looks like it isn't, and that would make sense). If it is, I'm happy to fix this myself.

Cheers!

**Comment by ktsaou** [comment]
@cakrit please take care of this.

**Comment by ktsaou** [comment]
@tzikis thank you for reporting it.

**Comment by cakrit** [comment]
Fixed. Thanks @tzikis!
