### ISSUE TITLE
How to change the number of grafics?

### ISSUE THREAD

**Issue by egorov-av** [netdata/netdata#7247]
Good afternoon!
Thanks so much for a wonderful product!

I had a question during the operation, the web page seems to me too overloaded with graphics, I do not need many. Is it possible to disable a number of grafics? For example, the idlejitter block or softirqs, I do not use since there is no need.

**Comment by vlvkobal** [comment]
Just set `no` in `netdata.conf` for every plugin/chart you want to disable. For example, if you want to disable diskspace plugin, set `diskspace = no` in the `[plugins]` section. 
```
[system.cpu]
	enabled = no
```
disables the `system.cpu` chart.
