### ISSUE TITLE
Netdata StatsD Multiple Percentiles/Disable Dimensions

### ISSUE THREAD

**Issue by jeremyjpj0916** [netdata/netdata#7249]
Question:

For Netdata, I am curious about this field:

From the docs: https://docs.netdata.cloud/collectors/statsd.plugin/

```
 # histograms and timers percentile (percentThreshold) = 95.00000
```

I wanted to do something like:
```
histograms and timers percentile (percentThreshold) = 99.00 95.00 !stddev !sum
```

Seems this isn't possible? Is it comma separated? I am trying it on 1.18.1.

**Comment by jeremyjpj0916** [comment]
Uh oh, looks like I pick one?

"show the 95th percentile (or any other percentile, as configured at statsd global config)" ?

Hmm would make sense to enable the ability to remove dimensions, add %'s(as a list).

**Comment by ilyam8** [comment]
it looks like it is a single value, yes
https://github.com/netdata/netdata/blob/01aaa909393a48d9db83c22dc95fffdd1cc074c9/collectors/statsd.plugin/statsd.c#L2169-L2173

**Comment by jeremyjpj0916** [comment]
💔 noooooooooo

**Comment by jeremyjpj0916** [comment]
Maybe some kinda for loop here could be implemented based on a newer config?:

https://github.com/netdata/netdata/blob/01aaa909393a48d9db83c22dc95fffdd1cc074c9/collectors/statsd.plugin/statsd.c#L1630

Make a few extra:
```
  RRDDIM *rd_percentile;
//Extras for potential multi custom percentiles
  RRDDIM *rd_percentile2;
  RRDDIM *rd_percentile3;
  RRDDIM *rd_percentile4;
```

https://github.com/netdata/netdata/blob/01aaa909393a48d9db83c22dc95fffdd1cc074c9/collectors/statsd.plugin/statsd.c#L1630
```
if( config.listpercentiles != '\0')
{
..foreach in list...
           m->histogram.ext->rd_percentile{1,2,3} = rrddim_add(m->st, statsd.config.listpercentiles.stringvalue, NULL, 1, statsd.decimal_detail, RRD_ALGORITHM_ABSOLUTE);
...
}
```

There is likely a much more elegant way to allocate and do this on the fly in C.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
