### ISSUE TITLE
Strange time glitch using dbengine on FreeBSD.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7253]
##### Bug report summary
Working installation of netdata. Changed the netdata.conf to include the following settings:
```
[global]
    history = 30000
    memory mode = dbengine
```

The node is a streaming master, the two slave nodes were not altered.
After restarting netdata to pick up the configuration changes all the charts were empty in the dashboard, and the log contained error messages such as:
```
2019-11-05 10:29:11: netdata ERROR : WEB_SERVER[static1] : RRDR is empty for system.cpu (RRDR has 5 dimensions, options is 0x00000205) (errno 35, Resource temporarily unavailable)
```

Switching the memory mode / history size back did not fix the problem. It persisted through many restarts and several complete uninstall / reinstall cycles. At some point the URL in the browser was corrupted to include time parameters that filtered out all data:
```
https://mechani.se/netdata/host/loki/#menu_system_submenu_cpu;after=1572944275250;before=1572945396000;theme=slate;help=true
```

Reinstalling netdata and manually restoring the URL fixed the problem.

##### OS / Environment
FreeBSD mechani.se 12.0-RELEASE-p4 FreeBSD 12.0-RELEASE-p4 GENERIC  amd64

##### Netdata version (ouput of `netdata -V`)
netdata v1.18.1-65-gcdf698d7

##### Component Name
Unknown

##### Steps To Reproduce
Unknown

##### Expected behavior
Not this.

**Comment by amoss** [comment]
Further information, enabling `dbengine`  by itself causes this to happen:
```
2019-11-05 11:38:21: netdata FATAL : MAIN :RRD_MEMORY_MODE_DBENGINE is not supported in this platform. # : No such file or directory

2019-11-05 11:38:21: netdata INFO  : MAIN : /usr/local/netdata/usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'FATAL' 'netdata:MAIN' '0258@database/r:rrdhost_create /2'
2019-11-05 11:38:21: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2019-11-05 11:38:21: netdata INFO  : MAIN : /usr/local/netdata/usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'EXIT' 'ERROR' '-'
2019-11-05 11:38:21: netdata INFO  : MAIN : EXIT: cleaning up the database...
2019-11-05 11:38:21: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
```
The daemon then hangs while shutting down.

**Comment by mfundul** [comment]
> 
> 
> Further information, enabling `dbengine` by itself causes this to happen:
> 
> ```
> 2019-11-05 11:38:21: netdata FATAL : MAIN :RRD_MEMORY_MODE_DBENGINE is not supported in this platform. # : No such file or directory
> 
> 2019-11-05 11:38:21: netdata INFO  : MAIN : /usr/local/netdata/usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'FATAL' 'netdata:MAIN' '0258@database/r:rrdhost_create /2'
> 2019-11-05 11:38:21: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
> 2019-11-05 11:38:21: netdata INFO  : MAIN : /usr/local/netdata/usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'EXIT' 'ERROR' '-'
> 2019-11-05 11:38:21: netdata INFO  : MAIN : EXIT: cleaning up the database...
> 2019-11-05 11:38:21: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
> ```
> 
> The daemon then hangs while shutting down.

This means you don't have the dependencies to enable `dbengine`. For more information look [here](https://github.com/netdata/netdata/blob/master/packaging/installer/README.md#prepare-your-system).

**Comment by amoss** [comment]
This is a way to replicate the problem seen in #5896.

**Comment by thiagoftsm** [comment]
Please, run the following command:

```sh
# ldd /usr/local/netdata/usr/sbin/netdata:
ldd /usr/local/netdata/usr/sbin/netdata:
        libm.so.5 => /lib/libm.so.5 (0x800308000)
        libz.so.6 => /lib/libz.so.6 (0x80033a000)
        libcrypto.so.111 => /lib/libcrypto.so.111 (0x800354000)
        libssl.so.111 => /usr/lib/libssl.so.111 (0x800641000)
        libuuid.so.1 => /usr/local/lib/libuuid.so.1 (0x8006d6000)
        libuv.so.1 => /usr/local/lib/libuv.so.1 (0x8008da000)
        liblz4.so.1 => /usr/local/lib/liblz4.so.1 (0x800906000)
        libJudy.so.1 => /usr/local/lib/libJudy.so.1 (0x80093b000)
        libthr.so.3 => /lib/libthr.so.3 (0x80099a000)
        libc.so.7 => /lib/libc.so.7 (0x8009c5000)
        librt.so.1 => /usr/lib/librt.so.1 (0x800db8000)
        libdl.so.1 => /usr/lib/libdl.so.1 (0x800dc0000)
```
With all the libraries installed, it is not expected to have problems on FreeBSD 12-p11

**Comment by amoss** [comment]
But we know that a library is missing - this is how we can replicate the hang in the clean-up code.

**Comment by thiagoftsm** [comment]
I had the problem before, but everything worked fine when I installed Judy.

**Comment by amoss** [comment]
> I had the problem before, but everything worked fine when I installed Judy.

That matches what I saw. I think there are two separate things that need to be done here:

1. Use the bug to work out why the clean-up code can hang in this situation. Hopefully it gives us some broader ideas about situations that are harder to replicate.
2. Fix the installer so that it cannot put netdata into a bad state - if Judy is a hard-dependency then abort the install if it is not available.

**Comment by thiagoftsm** [comment]
> > I had the problem before, but everything worked fine when I installed Judy.
> 
> That matches what I saw. I think there are two separate things that need to be done here:
> 
>     1. Use the bug to work out why the clean-up code can hang in this situation. Hopefully it gives us some broader ideas about situations that are harder to replicate.

I agree 100% with this.

>     2. Fix the installer so that it cannot put netdata into a bad state - if Judy is a hard-dependency then abort the install if it is not available.

We merged few days ago a PR that had options to disable dbengine during compilation time, and netdata also run on devices that do not have enough memory/disk to use the default dbengine configuration, so I cannot agree with the second for while.

**Comment by amoss** [comment]
> We merged few days ago a PR that had options to disable dbengine during compilation time, and netdata also run on devices that do not have enough memory/disk to use the default dbengine configuration, so I cannot agree with the second for while.

This seems reasonable. In these cases netdata should install / start / shutdown cleanly without Judy installed on the system.

**Comment by mfundul** [comment]
Closing this in favour of #5896.
