### ISSUE TITLE
Netdata 1.18.1 (from Debian sid) Material Icons in console.html commented out

### ISSUE THREAD

**Issue by cryptoluks** [netdata/netdata#7254]
On several machines I installed the netdata metapackage from Debian sid repo which currently holds version 1.18.1-1

The Material Icons did not work right out of the box.
![image](https://user-images.githubusercontent.com/9020527/68203585-62573280-ffc6-11e9-8b73-9e6f1326fcae.png)

I inspected the source of console.html and spotted that the header line commented out.

```html
<!-- <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" /> -->
```

This only affects my Debian machines. The same version of Netdata from the Arch Linux repo works as expected.

Is this the right place for this bug or is it related to the Debian package maintainer?

Thanks for all your effort.

**Comment by jacekkolasa** [comment]
@knatsakis that's strange, but i downloaded `netdata-web` package from https://packages.debian.org/sid/netdata-web, unpacked `data.tar.xz` contains different `/usr/share/netdata/web/console.html` file, with the same line commented:
```
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" /> -->
```

That line was never changed in git history, maybe someone uploaded locally changed version by mistake?

**Comment by jacekkolasa** [comment]
ok, turns out that we don't support the Debian package from that repo, if you need to use it, could you please create the issue at their appropriate forum, or install Netdata distro from packagecloud?

I'll close the issue then, but please comment if you have any questions
