### ISSUE TITLE
Installation with packages in Ubuntu trusty

### ISSUE THREAD

**Issue by ki0** [netdata/netdata#7258]
##### Bug report summary
Im trying to install netdata with Ubuntu repository in Trusty version and the package has a incomplete dependencie.
##### OS / Environment
Ubuntu trusty
##### Netdata version (ouput of `netdata -V`)
Latest
##### Component Name
netdata
##### Steps To Reproduce
root@e0df0ae0ac79:/# apt-get install netdata
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 netdata : PreDepends: dpkg (>= 1.17.14) but 1.17.5ubuntu5.8 is to be installed
E: Unable to correct problems, you have held broken packages.
root@e0df0ae0ac79:/# apt-cache policy dpkg
dpkg:
  Installed: 1.17.5ubuntu5.8
  Candidate: 1.17.5ubuntu5.8
  Version table:
 *** 1.17.5ubuntu5.8 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.17.5ubuntu5.6 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     1.17.5ubuntu5 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

**Comment by amoss** [comment]
Bug report has been replicated in the following way:
```
vagrant init ubuntu/trusty64
vagrant up
vagrant ssh
curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.deb.sh | bash -
```

**Comment by Ferroin** [comment]
We no longer build packages for Ubuntu Trusty (as of #7481), and this is not likely to change (both because of dpkg, and our hard dependency on libuv1). For the time being, the recommendation is to use the `kickstart-static64.sh` installation method.

**Comment by prologic** [comment]
But in end the end we actually are sill supporting Ubuntu 14.04 (_trusty_) in the sense that we have made sure Netdata still correctly builds there with #8916 which once merged will close this issue out.

**Comment by Ferroin** [comment]
Closing this as it’s old and already answered. A decision was made to simply drop support for anything but static installs on Ubuntu 14.04 due to issues with dependencies.
