### ISSUE TITLE
NetData alarms not working?

### ISSUE THREAD

**Issue by NStadija** [netdata/netdata#7260]
I've just set up slack notification for netdata and they seemed to work fine when using command "/usr/libexec/netdata/plugins.d/alarm-notify.sh test".

Then i decided to run a stress test on the server and see if the netdata alarms pick it up and see the actual slack message how it would look for real event you know but i didn't get nothing.

So i wen to check on WEB UI if alarms are set up and they were, next i went to see Log's on WEB UI all of them are status: CLEAR and i am unable to open them. So as far as i know i dont get no alarm notifications, is this a big? am i doing something wrong? any help would be highly appreciated.

![Screenshot 2019-11-06 at 10 57 28](https://user-images.githubusercontent.com/42933173/68292663-3e5a2680-0084-11ea-8f21-6fc6f3a69583.png)

![Screenshot 2019-11-06 at 10 58 34](https://user-images.githubusercontent.com/42933173/68292744-66e22080-0084-11ea-89f8-c6fae2581272.png)

Stress test i used: 
```
yum install stress-ng
stress-ng --cpu 4 --io 2 --vm 1 --vm-bytes 1G --timeout 60s --metrics-brief
```

OS / Environment:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

Netdata Version:
netdata v1.18.1-66-nightly

**Comment by thiagoftsm** [comment]
Hi @NStadija ,

In normal situation netdata will store inside error.log messages like this:

```
2019-11-06 13:46:58: alarm-notify.sh: INFO: sent slack notification for: hades system.cpu.dev_dim_template_user is CRITICAL to '#myalarms'
```

Or it will write an error when it cannot send messages to the destination specified inside the file `health_alarm_notify.conf`, please, could you check inside your error.log the messages that you have? And case it is possible, you can share with us for we help you.

Best regards!

**Comment by NStadija** [comment]
It seems that everything is working now sorry to waste your time

**Comment by thiagoftsm** [comment]
Do not worry @NStadija , we are here to help you, any possible problem that you find, please, let us know.

**Comment by NStadija** [comment]
@thiagoftsm There is another question i could raise  but its not a bug, Should i ask here? or create a question issue?

**Comment by thiagoftsm** [comment]
Please, create a new question and we will answer you.
