### ISSUE TITLE
RFC: Long-term metrics persistence for ephemeral containers 

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7265]
##### Feature idea summary
Every time an ephemeral container like a k8s pod starts, it gets a different host name and a different MACHINE_GUID (`/var/lib/netdata/registry/netdata.public.unique.id`). This causes the following issues:
 - The dbengine of a netdata master considers any ephemeral slaves completely new hosts and creates a new database for them, losing all history
 - The registry also considers the ephemeral container a completely new host. Today that doesn't cause serious problems, but with netdata.cloud we will keep seeing new nodes getting added. 

Labels/tags will help organize the information, but I think we may be able to do better. If netdata could somehow be configured to consistently generate at least the same MACHINE_GUID every time a docker container for a specific purpose is started, we'd be able to simplify our user's life tremendously. 

Let's take a very difficult problem we have with our default k8s deployment, using the helmchart in https://github.com/netdata/helmchart. A single master netdata runs on one of the nodes of the cluster, with dbengine enabled for long-term metrics storage. The master doesn't itself monitor anything except for netdata itself, it only exists to receive and persist metrics from the slaves. One slave netdata pod runs on each node of the cluster, collecting data. 

Now, as long as you don't restart any of the slave pods, everything is fine. The master itself has a persistent storage volume for the DB and even the master's MACHINE_GUID is persisted, because it's inside a second persistent storage, for the alarms. But with the daemonset deployment we currently use, the slaves will get a new host name and a new guid every time netdata is upgraded, or the pod is restarted for any other reason. I created https://github.com/netdata/helmchart/issues/61 to see if we can change our k8s deployment for the specific case, but I think you understand that it's a specific case of a more general issue: when nothing is persisted across restarts, we can't see a continuous chart that spans across those restarts. 

Even adding labels via a configuration doesn't help much. You see, all the slave pods will inevitably receive identical configurations, from some management tool. So it seems at first glance that all is lost in such cases. 

I think that there are three types of possible paths:

1. Use access to the docker socket to read some information from the host (I've lost track of the issues related to docker socket permissions). Possible caveat: can only work for one ephemeral container per host => can't have more than one ephemeral netdata running there. Not sure if that's really a problem. 
2. Use storage on the host (e.g.  k8s daemonsets can mount a persistent volume from a path on the host's filesystem). 
3. Use some other persistent storage (e.g. k8s statefulset PVC, though I'm not sure how exactly this works).

I haven't done research on what other monitoring systems do with ephemeral containers, perhaps they just accept that everything changes and can't show history, even if the same thing is monitored. Perhaps they just aggregate metrics using labels, to show a history without ever worrying about a specific k8s cluster node, or host monitored by a container. But to tell you the truth, I don't think there's a point to investigate what they do, if we can find a good solution to maintain that history.

**Comment by amoss** [comment]
One part of a solution could be to split the `MACHINE_GUID` into two parts - one that is intentionally static and one that is different for each ephemeral node. A possible way to do this would be:
* `MACHINE_GUID =  hi_bits | lo_bits`
* `hi_bits = hash(API_KEY)`
* `lo_bits = generate_UUID()`

By hashing the `API_KEY` we get a value that is constant across the cluster, but does not leak information about the secret. This gives us something to name the entire collection.

By generating a UUID when the container starts (as we already do) we get something unique to each ephemeral node. The combination of the two gives us a more detailed `MACHINE_GUID` so that we can strip out the static / transient parts depending on how we need to process it.

**Comment by stelfrag** [comment]
> One part of a solution could be to split the `MACHINE_GUID` into two parts - one that is intentionally static and one that is different for each ephemeral node. A possible way to do this would be:
> 
> * `MACHINE_GUID =  hi_bits | lo_bits`
> * `hi_bits = hash(API_KEY)`
> * `lo_bits = generate_UUID()`
> 
> By hashing the `API_KEY` we get a value that is constant across the cluster, but does not leak information about the secret. This gives us something to name the entire collection.
> 
> By generating a UUID when the container starts (as we already do) we get something unique to each ephemeral node. The combination of the two gives us a more detailed `MACHINE_GUID` so that we can strip out the static / transient parts depending on how we need to process it.

As I understand it that would require configuration change on the freshly started pod / container before a netdata server launch wouldn't it?

**Comment by amoss** [comment]
I'm not sure which part of the configuration would change before the launch, as I understand it:

* The `API_KEY` is a static parameter that is configured before the pod / container is launched, i.e. in the configuration file for the slave that is read into the `dockerfile`.
* The `generate_UUID()` is called when the server launches to pick a random value.

**Comment by stelfrag** [comment]
If I understand it correctly a `magic_uuid_remap` function should exist on master, which would 
magically when a slave connects, based on information from the slave (and more), decide that the UUID B just received is actually UUID A that we got 2 hours ago. 

This `magic_uuid_remap` would need to migrate all metrics collected so far from UUID A to UUID B
and processing continues

**Comment by amoss** [comment]
I read the existing comments the other way around - that it is difficult to make a `magic_uuid_remap` function so we should move to another approach. 

Taking a concrete example https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/ the `php_apache` node would be the ephemeral case. At any point in time there may be:

1. No running instances
2. A single instance
3. Multiple instances

Tying together metrics and remapping UUIDs makes sense in case 2 as it is the "same" service being restarted in different pods. But in a more general setting (I think case 3 the more common) it is no longer a 1:1 relationship. The same service can be 0/1/n nodes depending on the point in time and the question of what we should do with the metrics from those 0/1/n nodes becomes harder.

**Comment by stelfrag** [comment]
Exactly the case, that's why it needs to do *magic*, and needs some extra help to maybe achieve it. 

I believe that's why Chris said maybe the containers can access the master and store some info there that would be used upon restart 

certainly not easy -- you gave a great example of how that would complicate / break things!!

**Comment by cakrit** [comment]
Let's consider when/why I would want multiple instances on the same node. Only one of those instances would monitor node-level information (containers on the node, coreDNS, kube-proxy etc.). This is why what we have on k8s today is a daemonset, we want one and only one netdata collecting that type of info per node. All the other instances would need to be sidecar containers in a pod running e.g. an nginx or a mysql, right? These instances would need to run only the nginx or the mysql collector, nothing else. Well, the pod created for nginx is ephemeral too, so what history are we talking about in this case? The nginx instance I used to monitor no longer exists after the pod is restarted, so the only thing that makes sense in this case is to provide a service view, showing the "aggregated" metric history I mentioned before. So those additional netdata instances in sidecar containers should indeed have ephemeral UUIDs. 

If we agree on this point, then we still have the matter of the UUID for a single container per node to address, then the 2nd question is when/how we can prepare that container with an appropriate UUID. Note that if `/var/lib/netdata/registry/netdata.public.unique.id` contains a UUID before netdata starts, there is no need to "remap" anything, netdata won't even try to generate a new one.  

Are there ways to run code to put a file there before netdata starts? Sure!   https://github.com/netdata/helmchart/issues/61 contains some k8s-specific suggestions and we also have an `ENTRYPOINT` in our docker image, that executes [packaging/docker/run.sh](https://github.com/netdata/netdata/blob/master/packaging/docker/run.sh). So we can do 'something' to prepare the system before netdata starts.

Now, what's that something? In both methods, whatever algorithm we put runs as root and we do have access to the host's filesystem. We can read and write as we please, it's fully controllable and anyone can modify the behavior with environment flags or specific settings. This is important, because that's how we can allow persistence for the node-monitoring instance and prevent it for the sidecar instances. They're started with different environments. A user should even be able to prevent the persistence we'll try hard to provide even for the first instance, by providing the appropriate parameter (see [1] for something even smarter). But if the init container or run.sh script is allowed to do 'something' then we can do one of the following:
1. Save UUID on host (node)
 - Check the host's filesystem for an existing UUID file. If one does not exist, generate it on the host.
 - Put the UUID from that file into `/var/lib/netdata/registry/netdata.public.unique.id`
Caveat: We're *writing* to the node. I don't see security concerns, because the attack surface is very small. The init container or ENTRYPOINT script are executed and then done, netdata will still run as user netdata, possibly without ANY further access via the docker socket (see [this](https://github.com/netdata/netdata/tree/master/packaging/docker#docker-container-names-resolution) for more info).
2. Forget about UUID, just get a UID (essentially the `API_KEY` idea @amoss mentioned). 
 - Instead of a *Universally* unique identifier, just generate a UUID-like hash, based on the node's hostname, MAC address or whatever else would make sense, to make collisions highly improbable. But ensure that that hash will be the same, every time that function gets the same input. We've already mentioned in claiming that we shouldn't trust UUIDs for secure identification of a host, so that UID is used for "soft" identification.

 Why is option 2 essentially the same as the API_KEY idea? Because the truly unique UUID becomes almost useless for the problems we're trying to solve. It won't be used in the DB, it won't be used to identify the agent to the cloud (cloud would still like to understand that it's essentially the same agent as before, registry wouldn't want to count it as a new machine). We could use it in streaming, but that's about it. 

[1] - We haven't talked at all yet about sidecar containers. It's very likely that those netdata instances will be created based on different docker images, or same images with completely different defaults (all collection disabled except for application-specific logs and metrics). One of those different defaults could be a "UUID persistence"/"Single instance per host" flag that will ensure sidecar containers don't try to get get persistent UUIDs.

**Comment by amoss** [comment]
The discussion seems to have stalled. I think this is because @cakrit is the only one in the discussion with enough experience in the case that we are discussing - I propose that we create a spike instead:

* Setup a k8s configuration for testing.
* Try each of the three cases listed in the original text.
* Experiment with any other ways of either making the MACHINE_GUIDs unique, or fixing collisions.
* Report back on the results.

**Comment by cakrit** [comment]
Following a discussion with @mfundul today, I think that we will be forced to request access to a host directory for persistence. Even if we were to work around the persistence issue for MACHINE_GUID, agent claiming for cloud will also require a persistent SSL cert. I can't imagine generating automatically the same SSL cert after a pod restart.

**Comment by thiagoftsm** [comment]
> I can't imagine generating automatically the same SSL cert after a pod restart.

I agree, this would be  impossible, because the TLS certificates are generated using big random prime numbers values, case you could generate the same, this would mean that we have an algorithm easy to break or case you prefer a fake TLS algorthm.

**Comment by amoss** [comment]
This is an interesting point - if we are dealing with nodes that have been cloned somehow - have their entropy pools diverged? If not, would we see the same sequence of random numbers after querying /dev/random ? There is some discussion of this issue at https://news.ycombinator.com/item?id=11561340, although the summary is that the issue was fixed on virtual machines with virt drivers a few years ago. For containers I assume that they are really sharing the host's entropy pool.

**Comment by mfundul** [comment]
It is theoretically possible to seed a public/private key pair from the MACHINE_GUID but we should not do it (check https://crypto.stackexchange.com/questions/6086/initialize-a-prng-with-a-password). If we're basing the generation of RSA public/private prime numbers on non random or non secret input then the security is non-existent. And the MACHINE_GUID is not a secret, nor are any serial numbers on which it was based upon.

**Comment by cakrit** [comment]
@prologic I believe you had some ideas on this matter. Can you please record them here? We need to make a decision and get started on this, for many reasons.

**Comment by prologic** [comment]
@cakrit I _believe_ you're referring to our conversation where I described how you could create a named persistent volume in Docker and attach that to the container, effectively making `/var/lib/netdata` persist through restarts.

The flow would look something like this in `docker` CLI speak:

```sh
$ docker volume create -d local netdata
$ docker run -v netdata:/var/lib/netdata ... netdata/netdata
```

Or a Docker Stack might look like:

```yaml
version: "3.8"

services:
  netdata:
    image: netdata/netdata
    ports:
      - "1999:1999/tcp"
    volumes:
      - netdata:/var/lib/netdata
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  netdata:
    driver: local
```

**Comment by cakrit** [comment]
I see. It will actually be simpler to tell users to just pass the UUID as an environment variable, same as what we do for the host labels. It would be awesome of course if we could have a stable UUID even without this happening. For kubernetes, the [solution has been found](https://github.com/netdata/helmchart/issues/61#issuecomment-576778181) by @josecv, we just need to implement it now. 

I'll do a bit more digging, to see if I can find something under the directories we already mount, that could help us. `/etc/fstab` actually does have a UUID, we haven't needed to mount that before, but perhaps we could start doing it.

**Comment by cakrit** [comment]
Ok, so it looks like we could mount `/dev/disk` to `/host/dev/disk` and then just do an `ls` on `/host/dev/disk/by-uuid`, with some sorting (or a more advanced algorithm, that somehow finds the disk that has the `/` partition) that will allow us to consistently get the same UUID, every time a container is started. We also allow users to override this behavior by passing a UUID as a docker environment variable. 

We add these two methods plus the one for kubernetes above to the daemon, so that it doesn't just rely on the existence of the file for the machine guid. 

@Ferroin and @prologic what do you think?

**Comment by cakrit** [comment]
One more note on this. When we start adding sidecar containers to monitor apps running in pods, we don't want the host's info at all and we don't want persistent UUIDs. So the logic we're talking about here is for containers that monitor the system they're running on. We'll discuss how we'll differentiate, once we decide how we'll structure the netdata operator for k8s.

**Comment by mfundul** [comment]
In my experience, the existence of `disk/by-uuid` depends on the system configuration and the disk controller driver (for physical or virtual block devices). I remember it's not guaranteed to be there for all devices.

**Comment by cakrit** [comment]
> In my experience, the existence of `disk/by-uuid` depends on the system configuration and the disk controller driver (for physical or virtual block devices). I remember it's not guaranteed to be there for all devices.

That's ok, it doesn't need to exist everywhere, we're just trying to improve a bad situation. 

I've been thinking about this a bit more though and we DO have a risk to break something if we do it:
If for some reason I run two ND containers on the same machine AND mount `/dev` on both of them, AND I stream their metrics to the same master, this logic will break things (duplicate host) and force me to provide a different UUID to one of them. So we'll probably just need to go with additional volumes for docker.

**Comment by prologic** [comment]
I'm still of the opinion that we persist the volume in either native Docker or Kubernetes. Both have the notion of "local persistent volumes". I can't see a reliable way to "bind mount" some host-specific thing to help keep a stable UUID -- not to mention in some environments the use of SELinux might prohibit us doing this in the first place.

**Comment by cakrit** [comment]
We have a [decision for kubernetes](https://github.com/netdata/helmchart/issues/61) and a [decision for docker](#7680). Closing this.
