### ISSUE TITLE
Shared library for Network Viewer

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7272]
##### Feature idea summary
As we decided previously, we will have shared libraries for Network Viewer and these shared libraries will be built for kernels that are either "long term support" or "stable" , right now this list includes:

3.10.0-1062 ( RHEL 7)
4.9.199 ( Probably will be discarded) 
4.14.152
4.19.82
5.3.9
##### Expected behavior

To build the shared library necessary to run the network viewer for at least these kernel versions.

**Comment by ilyam8** [comment]
[About `stable`](https://www.kernel.org/category/releases.html)

> After each mainline kernel is released, it is considered "stable." 

> New mainline kernels are released every 2-3 months.

> every 2-3 months

**Comment by stelfrag** [comment]
But how many of those stable kernels make it to an LTS distribution?

**Comment by thiagoftsm** [comment]
In my opinion, we could keep the kernel version package until kernel.org decides that is not more kept.

**Comment by thiagoftsm** [comment]
The libraries were build after to adjust Makefiles according the necessity of each distribution, the next step will be to make our CI/CD to build the libraries to run on distributions.
