### ISSUE TITLE
Network Viewer DB/Collector

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7275]
##### Feature idea summary
Netdata needs to collect every tcp/udp packet, but it cannot send this information direct to the cloud, we will need to organize the data before to send to cloud.

Take external code that currently works and integrate with the agent

##### Expected result

* Add an experimental branch with the version of the agent that correctly compiles linked with Thiago's new library.
* Demonstrate that it works on one target configuration against a known kernel version.
* Demonstrate that the data is accessible inside the agent.
* A single demo chart with the live number of active sockets.
* Periodic output to the logs with the full set of current statistics.

**Comment by amoss** [comment]
I don't think that we can solve the problem by organizing the data. Perhaps it would work better to calculate some statistics about the data and send them to the cloud instead?

**Comment by thiagoftsm** [comment]
I was not clear, I am sorry, when I said organize the data, I was thinking to do all the necessary math and send the statistical moment to the cloud.

**Comment by amoss** [comment]
That makes more sense. Of course it raises an immediate question: what statistics should we calculate and send to the cloud. I saw the list of actives counts for egress on the issue during the planning meeting but it is vague and the ingress was left as an open question. The first goal of the technical refinement should be an exact list of what values the agent sends to the cloud.

**Comment by thiagoftsm** [comment]
We will work with the sum of bytes sent and received, we also need the number of bytes processed in an interval of time at least.
The ingress was left opened, because our main idea was to monitor connection between hosts that are in the same network, when we talk about ingress, we can receive requests from clients that can be everywhere, so we decided to work more with the egress, because it is more simple to identify.
