### ISSUE TITLE
Improve the dependency detection in CMake.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7276]
##### Feature idea summary

Cleanly detect the packages and libraries that we rely on from the CMakeFiles.txt

- [ ] Extraction of standard include/library paths from the system compiler.
- [ ] Package detection for each of our external dependencies, taking into account `pkg-config` entries, OS heuristics for packages, soft/hard dependencies.

There is full description in `./BUILD.md`, which essentially reduces to:

* Write a CMake function that handles the hard- and soft- cases.
* Put in fall-backs for non `pkg-config` cases.
* Use the detected paths from `--print-search-dirs`.
* Add specific heuristics for platforms (e.g. insert `/usr/local` for FreeBSD).

##### Expected behavior

The set of detected libraries and flags should match the behaviour of the existing autotools version.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
