### ISSUE TITLE
Dashboard, all servers in one graph/chart?

### ISSUE THREAD

**Issue by NStadija** [netdata/netdata#7284]
Is it possible to create a dashboard where is all my nodes/servers? the only stuff i want to view per server is the system.cpu, system.ram and disk_space._

At the moment im editing and using tv.html example and seeing what i can get done and i kinda want that everything fits in 1 page that there is no need to scroll down or up. i do know that it depends on server.

or maybe its possible to create a graph for like system.cpu and i can see all my servers into it? rather then having system.cpu for each server separately?

This is what i have so far made:
![Screenshot 2019-11-07 at 15 03 14](https://user-images.githubusercontent.com/42933173/68400319-bea98600-016f-11ea-835e-02d18d8e4258.png) 

OS / Environment:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

Netdata Version:
netdata v1.18.1-66-nightly

**Comment by jacekkolasa** [comment]
Hi @NStadija, unfortunately it is currently impossible to fit multiple metrics on the same chart. The way you are doing it is now the most optimal way. However, we will be adding this option in the future. Here's similar ticket: https://github.com/netdata/netdata/issues/3761

**Comment by jacekkolasa** [comment]
I hope this answers your question. I'll close this issue, but if you need anything more, please ask here
