### ISSUE TITLE
inconsistency in manifest tags

### ISSUE THREAD

**Issue by masterkain** [netdata/netdata#7290]
getting spammed by flux about this tag:

```
│ ts=2019-11-08T19:55:58.51261421Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/netdata/netdata auth={map[]} warn="manifest for tag v1.12.0-rc2 missing in repository netdata/netdata" impact="flux will fail to auto-rel
│ ease workloads with matching images, ask the repository administrator to fix the inconsistency"
```

**Comment by prologic** [comment]
Hi @masterkain -- Apologies for the delay in responding to this issue. Are you still experiencing issues with this? I had a look and we don't seem to have published (_or we removed it_) a `v1.12.0-rc2` tag for our Docker images in [Docker Hub repo](https://hub.docker.com/r/netdata/netdata/tags?page=1&name=v1.12.0)

Considering the latest version is also `v1.19.x` I'd also recommend upgrading if you haven't already.
