### ISSUE TITLE
Streaming plugins/apps metrics to master node

### ISSUE THREAD

**Issue by zoto724** [netdata/netdata#7291]
##### Question summary
**Should all metrics be streamed to the master node from slave nodes or are only base metrics included?** 

I've successfully installed and configured netdata on 2 nodes.  One is setup as a master with the following configuration:
Master -- stream.conf
```
[xxx]
    enabled = yes
    allow from = *
    default history = 3600
    default memory mode = dbengine
    last_collected alarms
    health enabled by default = auto
    default postpone alarms on connect seconds = 60
    multiple connections = allow
```

A slave is set to stream metrics to the master node, and metrics from the slave node show up from the master, however some stats are missing such as applications, users, and fping metrics.  
Slave node viewed from the master drop down - 
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/7454082/68507910-ffba9c80-023a-11ea-9de7-080b7f5f9afc.png">

slave node viewed directly on the slave node - Note additional menu items such as "fping" and "postfix"
<img width="195" alt="image" src="https://user-images.githubusercontent.com/7454082/68508152-aacb5600-023b-11ea-8b08-094638412aaf.png">
Slave config -
```
[stream]
    destination = 10.130.192.36:19999:SSL
    ssl skip certificate verification = yes
    api key = xxx
    timeout seconds = 60
    default port = 19999
    send charts matching = *
    buffer size bytes = 1048576
    reconnect delay seconds = 5
    initial clock resync iterations = 60
```

##### OS / Environment
CENTOS 7 / install via curl to bash method - v1.18.1-84-nightly
##### Component Name
Steaming/fping
##### Expected results
Streams from the slave nodes include all stats generated by the slave.

**Comment by thiagoftsm** [comment]
Hi @zoto724 ,

What are the values for `page cache size` and `dbengine disk space` on master? Another doubt, case you run the command `grep STREAM error.log` are you seeing error messages?

Best regards!

**Comment by zoto724** [comment]
hey @thiagoftsm , 
```
[global]
page cache size = 32
dbengine disk space = 512
memory mode = dbengine
```
I see plenty of "INFO" level messages in the log related to streaming.  There are a few errors such as this related to starting/stopping clients/server:
`2019-11-08 17:13:08: netdata ERROR : STREAM_RECEIVER[ip-10-130-192-55.ec2.internal,[10.130.192.55]:55336] : STREAM ip-10-130-192-55.ec2.internal [receive from [10.130.192.55]:55336]: disconnected (completed 123416 updates).` but that's it.

**Comment by thiagoftsm** [comment]
Thank you for the information @zoto724!

Some users reported in the past problems with stream and dbengine, in normal situation they had a dbengine configuration(https://docs.netdata.cloud/database/engine/#database-engine ) that was not good enough for their environment as you can see here https://github.com/netdata/netdata/issues/6852#issuecomment-535615442  , and @mfundul help them.

I will do an investigation for the case that you are reporting here to check whether we are having specific problems with postfix and fping, please, while I am investigating could you see our documentation and do few adjusts in your master side?

**Comment by zoto724** [comment]
Thanks @thiagoftsm, I think I've narrowed down the issue, this is maybe a bug but I cant be sure.  From my testing, it appears that self signed certs(maybe all certs) and SSL enabled on a slave node set to send stats to a master node disables streaming of some stats for some reason.  

Steps to reproduce- 
Master node setup is very vanilla - streaming/fping enabled
Slave node set to send stats to the master node via IP.addr:19999:SSL

This setup produces all the stats I'd expect, including fping and postfix.  
To make stats not send i can do the following from the slave node:
```
[root@ip-10-130-192-53 centos]# cd /etc/netdata/ssl/
[root@ip-10-130-192-53 ssl]# openssl req -new -newkey rsa:2048 -nodes -sha512 -x509 -days 1000 -keyout key.pem -out cert.pem -subj "/C=US/ST=USA/L=here/CN=doesntmatter"
Generating a 2048 bit RSA private key
.............................+++
.+++
writing new private key to 'key.pem'
-----
[root@ip-10-130-192-53 ssl]# chown netdata:netdata *
[root@ip-10-130-192-53 ssl]# service netdata restart
Redirecting to /bin/systemctl restart netdata.service
```
From the master node, fping/postfix/some others stop sending to master node from this slave node
to re-enable-
```
[root@ip-10-130-192-53 ssl]# ls
cert.pem  key.pem
[root@ip-10-130-192-53 ssl]# rm *
rm: remove regular file ‘cert.pem’? y
rm: remove regular file ‘key.pem’? y
[root@ip-10-130-192-53 ssl]# service netdata restart
Redirecting to /bin/systemctl restart netdata.service
```
stats start sending again from the slave node for all metrics.

**Comment by zoto724** [comment]
I should add I realize this sets up SSL on the slave node, and that slave node SSL isn't necessary to stream to the master node with SSL, but I want to be able to view the slave node stats directly if needed, hence why i'd like SSL enabled on the slave node also.

**Comment by thiagoftsm** [comment]
> I should add I realize this sets up SSL on the slave node, and that slave node SSL isn't necessary to stream to the master node with SSL, but I want to be able to view the slave node stats directly if needed, hence why i'd like SSL enabled on the slave node also.

The slave does not need a SSL certificate to connect with the server as you could see. In theory we could have the SSL working on slave, because the context for the client and server are different, but it looks like that you found a bug. I will work on this during the week to fix the error reported.

Thank you very much!

**Comment by thiagoftsm** [comment]
Hi @zoto724 ,

I created now the PR #7306 that fixes this bug, case you have a condition to test it, please, let us know whether it really fixed the problem.
During my tests, I verified that postfix  was not sending correctly the stream as you reported, but after the fixes everything worked fine

**Comment by zoto724** [comment]
Hey @thiagoftsm, 
Thanks for this, I successfully built your branch on a slave node and enabled SSL on it, fping and other stats still send to the master node.  
Thanks again for your help!

**Comment by thiagoftsm** [comment]
We are glad that we could fix the bug and give all the necessary conditions for you run netdata.
I also need to say thank you for your report and for the tests that you executed in your side.
Any problem that you have or any doubt, please, let us know

Best regards!
