### ISSUE TITLE
apache web_log pattern search FAILED

### ISSUE THREAD

**Issue by Mic-Pod** [netdata/netdata#7293]
##### Question summary
Hi,
I'm trying to use web_log plugin with apache2, but I always get:
`ERROR: web_log[apache_log1] : Custom log: pattern search FAILED`

- Entry in apache vhost file:
```
LogFormat "%v %p %h %t \"%r\" %>s %O %I %D \"%{Referer}i\" \"%{User-Agent}i\"" vhost_netdata
LogFormat "%h %l %u %t \"%r\" %>s %O %I %D \"%{Referer}i\" \"%{User-Agent}i\"" netdata
CustomLog ${APACHE_LOG_DIR}/nextcloud-access.log netdata
```
- Entry in web_log.conf:
```
#  custom_log_format:
#     pattern: '(?P<vhost>[a-zA-Z\d.-_]+) (?P<port>\d+) (?P<address>[\da-f.:]+) \[.*\] "(?P<method>[A-Z]+)[^"]*" (?P<code>[1-9]\d{2}) (?P<bytes_sent>\d+) (?P<resp_length>\d+) (?P<resp_time>\d+)'
```

##### OS / Environment
Ubuntu Server 18.04
Apache 2.4.41
Netdata v1.18.1-95-g079f1687
##### Component Name
netdata/collectors/python.d.plugin/web_log/web_log.conf

##### Expected results
visible apache2 log graphs

**Comment by ilyam8** [comment]
@Mic-Pod hi, show your log line

**Comment by Mic-Pod** [comment]
I have discovered what caused the error... I'm using HostnameLookups in apache2.conf.
So when pattern was looking for address there was an error because instead of address I had FQDN in access log...

**Comment by Mic-Pod** [comment]
I'm wondering if it's possible to modify pattern to be compatible with hostnames.

**Comment by ilyam8** [comment]
Yes, you need to modify pattern or use `%a` instead of `%h` (which is not acceptable i think).


Change `(?P<address>[\da-f.:]+)` to `(?P<address>[a-zA-Z0-9-:.]+)`, it should work but keep in mind that all hostnames will be treated as ipv4 addresses.

**Comment by Mic-Pod** [comment]
OK, thank You. I will just disable HostnameLookups for now.
