### ISSUE TITLE
devuan with OpenRC

### ISSUE THREAD

**Issue by hbfs** [netdata/netdata#7294]
##### Bug report summary
netdata does not start after reboot on devuan beowulf/ceres with OpenRC init system

##### OS / Environment

devuan beowulf/ceres

##### Netdata version (ouput of `netdata -V`)
\netdata v1.18.1-91-nightly

##### Steps To Reproduce

install from one liner
reboot

##### Expected behavior
should start automatically like on other systems

similar modification of https://github.com/netdata/netdata/pull/6275 likely relevant

**Comment by hbfs** [comment]
latestest installer 

```
 --- Install netdata at system init ---
./packaging/installer/functions.sh: line 306: [: =~: binary operator expected
I don't know what init file to install on system 'debian-3'. Open a github issue to help us fix it.
 FAILED  Cannot install netdata init service.
```

**Comment by Ferroin** [comment]
@hbfs Can you confirm if this is still an issue?

**Comment by Ferroin** [comment]
Closing this as there's been no response from the OP, and Devuan appears to have become abandonware AFAICT. If it's still an issue, please comment here (ideally with links pointing to proof that Devuan is not functionally dead) and we'll reopen it.

**Comment by hbfs** [comment]
@Ferroin ended up using `local` for start up and its been working fine 
devuan beowulf 3.0.0 was released on 2020-06-09 https://dev1galaxy.org/viewtopic.php?id=3557
Curious to know why you think devuan is abandonware?

**Comment by Ferroin** [comment]
> @Ferroin ended up using `local` for start up and its been working fine
> devuan beowulf 3.0.0 was released on 2020-06-03 https://dev1galaxy.org/viewtopic.php?id=3557
> Curious to know why you think devuan is abandonware?

As of March 5 when I made that comment, the Devuan website appeared to have not been updated for quite some time, there was no clearly visible evidence of ongoing development, and there was no visible evidence on the site that 2.0 had ever made it past beta status (IOW, it looked like development had died off before the release happened, and the only 'stable' release was based on an EOL release of Debian).

In fact, the current state of the website doesn't seem to be entirely updated either (still has multiple references to 2.0 as 'stable' despite the release of 3.0).

**Comment by hbfs** [comment]
Thats understandable. The devuan site needs some love. The activity is elsewhere on the forums, mailing list, irc. Their philosophy is release when its stable and ready vs a periodic cadence. devuan 2.x is based on debian 9 which had a point release in Feb so it shouldn't be EOL.

I'll update this issue after trying netdata on a fresh install.
