### ISSUE TITLE
False-positive update check warning in stable releases

### ISSUE THREAD

**Issue by kachkaev** [netdata/netdata#7295]
##### Bug report summary

👋 I’m here because of this exclamation sign:

<img width="118" alt="update button warning" src="https://user-images.githubusercontent.com/608862/68535507-61623000-033b-11ea-9938-fa7b64c0fa29.png">

##### OS / Environment / Version

`netdata/netdata:v1.18.1` (official docker container)

##### Steps To Reproduce

I used to update netdata via an ansible script that pulled the new code from a git repo, but lately switched to a lightweight docker container option. By using a tagged version such as `1.18.1` I was expecting to conceptually move from a nightly channel to a stable one, meaning that I am no longer asked to update every time the is a commit to netdata master. However, I still see an exclamation mark next to the update button, which looks like a false-positive to me:

<img width="590" alt="update check netdata modal" src="https://user-images.githubusercontent.com/608862/68535583-46dc8680-033c-11ea-85e6-d026af4666da.png">

##### Expected behavior

By using a tagged netdata version, I am expecting to receive update warnings only when a new stable release is out. Otherwise, the exclamation mark becomes rather useless. It becomes tempting to ignore it completely, knowing that it is there pretty much all the time. How difficult would it be to fix this _Update Check_ behaviour?

**Comment by thiagoftsm** [comment]
Hi @kachkaev ,

We are working here to solve the problem reported, please, can you give us the output of the command `cat /etc/netdata/.environment  | grep RELEASE_CHANNEL`?

Best regards.

**Comment by kachkaev** [comment]
👋 sorry for a delayed response!

Here's what I get:

```docker ps
```

```
CONTAINER ID        IMAGE                     COMMAND              CREATED             STATUS                 PORTS                      NAMES
0d7bed4f10fc        netdata/netdata:v1.18.1   "/usr/sbin/run.sh"   29 seconds ago      Up 20 seconds          0.0.0.0:19999->19999/tcp   netdata
...
```

```
docker exec -it netdata sh
/ # cat /etc/netdata/.environment | grep RELEASE_CHANNEL
```
```
RELEASE_CHANNEL="nightly"
```

**Comment by kachkaev** [comment]
ping @thiagoftsm 🙂

**Comment by thiagoftsm** [comment]
Hi @kachkaev ,

I apologize the delay to answer you.
We had an internal conversation about this problem where I gave information for our devops team to verify what is happening. 
@knatsakis and @ncmans did you have time to investigate this problem?

**Comment by ncmans** [comment]
@thiagoftsm yes, opened https://github.com/netdata/netdata/pull/7373

**Comment by thiagoftsm** [comment]
> @thiagoftsm yes, opened #7373

Thank you @ncmans !

**Comment by kachkaev** [comment]
After upgrading to `v1.20.0` by using a [corresponding docker image](https://hub.docker.com/layers/netdata/netdata/v1.20.0/images/sha256-7248d7bb697e5bc13f1c628e8da91671a5e095934f8f278d987ab1596291695a?context=explore), I still see a prompt to upgrade 🤔

<img width="588" alt="Screenshot 2020-02-23 at 09 06 40" src="https://user-images.githubusercontent.com/608862/75109531-2ea72380-561c-11ea-85bb-b1bafdad885b.png">

**Comment by kachkaev** [comment]
Using [`v1.21.1`](https://hub.docker.com/layers/netdata/netdata/v1.21.1/images/sha256-29f91d4d2c6f3e6e2b978cbeb8f1574dfd1aabed1104107162cc18462e4542d6?context=explore)


<img width="595" alt="Screenshot 2020-04-25 at 12 30 45" src="https://user-images.githubusercontent.com/608862/80278746-acf17600-86f0-11ea-887a-49f9e73e9c34.png">

@ncmans could you please have a look and reopen if applicable?

**Comment by kachkaev** [comment]
The issue is still there: 

<img width="809" alt="Screenshot 2020-06-14 at 20 58 21" src="https://user-images.githubusercontent.com/608862/84602821-eb4e1a80-ae81-11ea-8f39-fe1c602a973e.png">

Please reopen 🙏

**Comment by ilyam8** [comment]
@kachkaev https://github.com/netdata/netdata/issues/9296
