### ISSUE TITLE
What about Redfish plugin ?

### ISSUE THREAD

**Issue by frsauvage** [netdata/netdata#7296]
##### Feature idea summary
Redfish is now a standard replacing ipmi quickly.
##### Expected behavior
Monitoring Redfish hardware

**Comment by ilyam8** [comment]
i googled a bit
 - [Redfish 1.0 is defined as a standard and a RESTful API for the management of scale-out commodity servers](https://www.infoq.com/news/2015/08/redfish/)
 - [supermicro redfish nagios plugins](https://www.supermicro.com/en/solutions/management-software/redfish)

According article we can monitor via redfish api:
 - System health
 - Memory
 - Fan sensors
 - Temperature sensors
 - Voltage sensors
 - Power supply
 - Storage


plugins code
> https://github.com/nsfcac/Nagios-Redfish-API-Integration/tree/master/redfishplugins


@frsauvage am i missing something? Could you provide example output for different api calls? (see nagios plugins)

**Comment by frsauvage** [comment]
Thank a lot @ilyam8 

By mentionning Nagios plugins, you mean that Nagios plugins works in netdata ? Or should I just be inspire myself  from that Nagios scripts to write netdata scripts ?
I am pretty good in Redfish, so develop Redfish scripts is not a problem, 
URL are OK, I agree, even if Nagios scripts are more "check" scripts than "value" scripts.

Well, question is more a best practice advise I need: Is it the best way to develop python netdata modules using 'requests' python library to get Redfish data, like Nagio scripts are using curl shell command ? 
I just would like to know the best way because I begin in netdata development.
I saw the netdata page "How to develop a module", in that case, it is OK for me, as I am a python developer.

Best regards,
Francine

**Comment by ilyam8** [comment]
> By mentionning Nagios plugins, you mean that Nagios plugins works in netdata ? Or should I just be inspire myself from that Nagios scripts to write netdata scripts ?

No, to write a module we need an example output. If i understand it correctly we need to fetch data from several endpoints. So i would prefer to have this [module written in `go`](https://github.com/netdata/go.d.plugin).

So you either do it yourself or just provide all needed info - list of `enpoint - example data` and i will write it. It seems not difficult since it is just do http req, parse json response logic.

**Comment by frsauvage** [comment]
Thank you for your answer @ilyam8 ,
And thank you for the help you propose. 
I would prefer to do it by myself as I need to evaluate extension capacity of netdata as well, I notice your grateful attention.

I read your example and I plan to follow these steps, please correct me if I am wrong:
1. copy/paste an example containing Makefile.inc, x.charts.py and x.conf files
2. add a docker volume to xxx/python.d.plugin/redfish directory
3? well, here, I am confused.... 
You mention redfish devices are external devices. That is right, so what is the way netdata deals with external devices ? 
3. add a list of endpoints (some-)where in netdata ? => can I use "node" concept ?
4. adapt my "redfish module" - inheriting UrlService- to receive the concerned endpoint/user/password (better have a vault to secure access?)  as parameters and return _getdata() values

Am I right ?

Best regards,
Francine

**Comment by ilyam8** [comment]
@frsauvage 

see

> https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-write-a-new-module
> https://docs.netdata.cloud/collectors/python.d.plugin/#pull-request-checklist-for-python-plugins

See other modules which use `UrlService` as a base class. Example:
> https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/rabbitmq/rabbitmq.chart.py

**Comment by frsauvage** [comment]
@ilyam8, 
I just understood that I should add netdata on each node (server) to monitor it.
It is not possible for my IoT redfish devices, I should monitor it remotely without installing anything on it, You can close this issue.

Best regards,
Francine

**Comment by ilyam8** [comment]
> I just understood that I should add netdata on each node (server) to monitor it.

It depends on what you want to monitor. Netdata consumes data from collector, collector can fetch metrics from everywhere.  For example, if metrics are available via http endpoints, we can fetch them using python module which uses `UrlService` as a base class.

See apache module config, there you can set `url`

https://github.com/netdata/netdata/blob/1094175c3bd08ecf5c83c91605e9fd1d02052108/collectors/python.d.plugin/apache/apache.conf#L75-L85

You can add any number of jobs for every module.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
