### ISSUE TITLE
File does not exist, or is not accessible: /opt/netdata/usr/share/netdata/web/mngmnt-dash.html

### ISSUE THREAD

**Issue by NStadija** [netdata/netdata#7309]
File does not exist, or is not accessible: /opt/netdata/usr/share/netdata/web/mngmnt-dash.html

For some reason today i am not able to access web custom dashboard anymore - was working perfectly fine on weekend. 

However, i can access and view in web the "tv.html" dashboard and "dashboard.html".

![Screenshot 2019-11-12 at 11 00 37](https://user-images.githubusercontent.com/42933173/68666348-ad7bc300-053b-11ea-9238-79cc4f14156c.png)

OS / Environment:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

Netdata Version:
netdata v1.18.1-66-nightly

**Comment by ilyam8** [comment]
Do you access netdata via nginx?

**Comment by NStadija** [comment]
> Do you access netdata via nginx?

Yes

**Comment by ilyam8** [comment]
Then i suggest to check nginx error.log and configuration.

Have you tried to get `mngmnt-dash.html` directly from hetdata web server?

**Comment by NStadija** [comment]
> Then i suggest to check nginx error.log and configuration.
> 
> Have you tried to get `mngmnt-dash.html` directly from hetdata web server?

ive checked nginx error.log  no errors regarding that 

(what do you mean? by directly from hetdata web server)

i get the "File does not exist, or is not accessible: /opt/netdata/usr/share/netdata/web/mngmnt-dash.html" by going on http://ip_address:19999/mngmnt-dash.html

**Comment by ilyam8** [comment]
> what do you mean? by directly from hetdata web server

I mean bypass nginx proxy and fetch data directly from netdata built-in web server.

Probably i misunderstood you, does

> http://ip_address:19999/mngmnt-dash.html

request go through nginx proxy?

**Comment by NStadija** [comment]
> > what do you mean? by directly from hetdata web server
> 
> I mean bypass nginx proxy and fetch data directly from netdata built-in web server.
> 
> Probably i misunderstood you, does
> 
> > http://ip_address:19999/mngmnt-dash.html
> 
> request go through nginx proxy?

no it doesnt go through nginx proxy

**Comment by mfundul** [comment]
It looks like the error message path is `/opt/netdata/usr/share/netdata/web/mngmnt-dash.html` but your `pwd` path is `/usr/share/netdata/web/mngmnt-dash.html`.

Maybe somehow you've got 2 different installations of netdata, like one in `/opt/netdata/` and one in `/`?
