### ISSUE TITLE
how to configure fping plugin to run inside network namespace

### ISSUE THREAD

**Issue by er1cthe0ne** [netdata/netdata#7311]
First of all, netdata is looking promising, I am doing more experiment with it.

I am trying to do the equivalent of the following within netdata fping plug in, is it possible?

ip netns exec [network namespace name] fping [ip] [fping options]

Any suggestions?

Thanks,
Eric

**Comment by vlvkobal** [comment]
I'm not sure if it works, but try using something like `fping="/usr/bin/ip"` and `fping_opts="netns exec [network namespace name] fping [ip] [fping options]"`. Or change the `/usr/libexec/netdata/plugins.d/fping.plugin` shell script.

**Comment by er1cthe0ne** [comment]
Thanks for the suggestion. I was thinking in the line of your first suggestion. I didn't think about changing /usr/libexec/netdata/plugins.d/fping.plugin.

**Comment by vlvkobal** [comment]
@cakrit suggested that if you are modifying the script, keep in mind that it will be rewritten on the next Netdata update.

**Comment by er1cthe0ne** [comment]
Got it, I will keep that in mind. Thanks!
