### ISSUE TITLE
Hundreds of Emails Notifications daily! Please help.

### ISSUE THREAD

**Issue by martinperreault** [netdata/netdata#7314]
Hi,
We recently installed Netdata on CentOS6 via WHM. 
Since then, I am receiving hundreds of email notifications per day about "1m tcp accept queue overflows - ip.tcp_accept_queue".  After researching this, it seems people are saying we can ignore these as Netdata is too sensitive.

My questions are:

1) Is Netdata really too sensitive about this trigger, or should I be alarmed? And if so, what should I do about it to fix the issue?

2) How in the world do I disable email notifications? I looked online, but all solutions I found didn't work...

3) Why isn't there a simply toggle in the settings interface of Netdata to control email notifications, instead of having to open .conf files and restart services?

Thank you for your help!  My inbox is flooded with these emails!

Martin

**Comment by ilyam8** [comment]
@Ferroin 

I think we need to tune these alarms

https://github.com/netdata/netdata/blob/928c52f73f7f21e6d434bff82b01effedb6010bd/health/health.d/tcp_listen.conf#L21-L46

same way you did in https://github.com/netdata/netdata/pull/7250

**Comment by ilyam8** [comment]
btw @martinperreault 

have you tried to increse this parameter

> $ sysctl net.core.somaxconn
net.core.somaxconn = 16384


See `Accept Queue`

> https://blog.cloudflare.com/syn-packet-handling-in-the-wild/

**Comment by martinperreault** [comment]
Thank you @ilyam8  for the suggestion. Where should I change this value? In Apache general settings? And what would be a more appropriate value?

**Comment by ilyam8** [comment]
No, it is sytem value. From [the article](https://blog.cloudflare.com/syn-packet-handling-in-the-wild/)

> The Accept Queue contains fully established connections: ready to be picked up by the application. When a process calls accept(), the sockets are de-queued and passed to the application.

> Queue size limits
The maximum allowed length of both the Accept and SYN Queues is taken from the backlog parameter passed to the listen(2) syscall by the application. For example, this sets the Accept and SYN Queue sizes to 1,024:

> listen(sfd, 1024)
> Note: In kernels before 4.3 the SYN Queue length was counted differently.

> This SYN Queue cap used to be configured by the net.ipv4.tcp_max_syn_backlog toggle, but this isn't the case anymore. Nowadays net.core.somaxconn caps both queue sizes. On our servers we set it to 16k:

> $ sysctl net.core.somaxconn
net.core.somaxconn = 16384


I m not a specialist, i dont know if it will help in your case, but i think it is ok to experiment. 

Check current value

> test@debian10:~$ sudo sysctl net.core.somaxconn
net.core.somaxconn = 128

Change the value

> test@debian10:~$ sudo sysctl net.core.somaxconn=16384
net.core.somaxconn = 16384

It is temporary change, to make it permanent you need to add that row to the `/etc/sysctl.conf`

Do some tests. Probably you have problems with some app and it is the reason accept queue is overflows. Probably not. I tend to agree that we need to tune the alarms and make them less strict.

**Comment by Ferroin** [comment]
@ilyam8 Agreed. I'll make a pass over all the other alarms we ship at the same time to try and catch any other cases like this so that we don't have to keep doing one-off PR's for these.  I should have a PR some time either later today or tomorrow.

**Comment by martinperreault** [comment]
> Change the value
> test@debian10:~$ sudo sysctl net.core.somaxconn=16384
> net.core.somaxconn = 16384

ok thanks, I did that now. I assume it's effective right away and I don't need to reboot the machine since it is not permanent?

> It is temporary change, to make it permanent you need to add that row to the /etc/sysctl.conf
... and then I assume a reboot is in order?

Sorry for the questions, I have limited knowledge with this.

**Comment by ilyam8** [comment]
> ok thanks, I did that now. I assume it's effective right away and I don't need to reboot the machine since it is not permanent?

Yes. You dont need to reboot system to make changes permanent. 

 - modify `/etc/sysctl.conf`
 - `sudo sysctl -p`

>  -p[FILE], --load[=FILE]
              Load  in sysctl settings from the file specified or /etc/sysctl.conf if
              none given.  Specifying - as filename means reading data from  standard
              input.   Using  this  option  will  mean arguments to sysctl are files,
              which are read in the order they are specified.  The file argument  may
              be specified as regular expression

**Comment by martinperreault** [comment]
I can confirm that the net.core.somaxconn = 16384 did not have any positive effect, and I have received over 50 email notifications since I made the change.

How do I simply tell Netdata to stop emailing me with those notifications?

**Comment by amoss** [comment]
> @ilyam8 Agreed. I'll make a pass over all the other alarms we ship at the same time to try and catch any other cases like this so that we don't have to keep doing one-off PR's for these. I should have a PR some time either later today or tomorrow.

The "1m ipv4 udp receive buffers errors" might be a bit too aggressive as well. Because it is set to zero it tends to flip in and out of the alarm state causing a lot of emails. I have a server for video and this fires multiple times a day.

**Comment by ilyam8** [comment]
@How do I simply tell Netdata to stop emailing me with those notifications?
 
- cd to `/etc/netdata` (actual path depends on your install)
 - run `./edit-config health.d/tcp_listen.conf`
 - change `to: sysadmin` to `to: silent`
 - save changes
 - restart netdata service

**Comment by martinperreault** [comment]
> cd to /etc/netdata (actual path depends on your install)
This appears to be our path as well.

> run ./edit-config health.d/tcp_listen.conf
This line confuses me...
I cannot find a tcp_listen.conf file anywhere...
If I try to cd to "/edit-config health.d/", it says no such directory.
If I enter:
 run ./edit-config health.d/tcp_listen.conf
run command is not found
if I try :
 nano ./edit-config health.d/tcp_listen.conf
It opens the file ./edit-config
and I cannot find a "to" line in the code.

The following are the only folders and files I can see in directory /etc/netdata/
charts.d
custom-plugins.d
edit-config* (written like this, with the *)
.environment
go.d
health.d
.installer-cleanup-of-stock-configs-done
netdata.conf
node.d
orig@
python.d
ssl
statsd.d

What am I missing ?

Sorry to be a bother... I really want to stop the flooding of all those email warnings. (I still wish there was a simlpy ON/OFF toggle in the UI of Netdata, would make things so much simpler...)

**Comment by amoss** [comment]
Don't type run at the beginning, type (exactly):
```
./edit-config health.d/tcp_listen.conf
```

**Comment by ilyam8** [comment]
@martinperreault we made some changes to those alarms, please update to the latest   and check if the problem is resloved

**Comment by martinperreault** [comment]
Thasnk you @ilyam8 
I looked in Netdata UI under the UDPATE menu, and it says I have the latest version (Your netdata version: v1.18.1-114-nightly)

meanwhile I ran the code listed above by @amoss and restarted the service netdata and so far no email notifications have come in.
