### ISSUE TITLE
problem running bash commands under charts.d

### ISSUE THREAD

**Issue by er1cthe0ne** [netdata/netdata#7315]
##### Question summary
I have the below script to count the number of peer* interfaces inside all the containers. It runs fine when executed directly or run it under bash shell. It also works fine with:
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 example

However, when the same code was added in /usr/libexec/netdata/charts.d/example.chart.sh, charts.d process will not load (or it crashed) which prevented the corresponding chart to load.

Any suggestion on what is the problem and how to fix this?

Below is the full script:
------------------
```bash
#!/bin/bash

total="0"
for container in $(docker ps -q); do
    (***problematic line below***)
    peercount=$(docker exec -it $container bash -c "ls -A /sys/class/net | grep peer* | wc -l")
    (***problematic line above***)
    peer_count_string=${peercount//[^[:alnum:]]/}
    echo $container:$peer_count_string
    total=$(($total + $peer_count_string))
done
```
------------------

##### OS / Environment
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by stelfrag** [comment]
Hi @er1cthe0ne 

Can you check and see if there is anything in the logfile (error.log) ?

**Comment by er1cthe0ne** [comment]
Hi @stelfrag, great suggestion. 

The error.log did indicate the problematic line failed (or returned nothing) when running under charts.d process likely because it is running as netdata user. Should I give netuser account more power or look into running equivalent command which doesn't require higher privilege access?

**Comment by stelfrag** [comment]
Hi @er1cthe0ne 

You should avoid giving netdata extra privileges, and adjust the running command accordingly. 

Also check https://docs.netdata.cloud/docs/netdata-security/#your-systems-are-safe-with-netdata

**Comment by stelfrag** [comment]
I suspect the offending command is `docker`, so in your case adding extra privileges 
to the netdata user would be to be allowed to execute docker commands as non-root (usually this can be done by adding the netdata user to the `docker` group).

You need to determine if that would be a security risk for you or it would be ok.

**Comment by stelfrag** [comment]
Closing this. If you have any other questions / problems please create another issue or reopen if it is related to this.
