### ISSUE TITLE
I/O wait of CPU increased on netdata.

### ISSUE THREAD

**Issue by pkd809** [netdata/netdata#7316]
![cpuiowait](https://user-images.githubusercontent.com/43242987/68847003-e9f21f00-06f3-11ea-92bc-704906dd7376.png)

My CPU i/o wait increases to 100% on 7 out of 12 cores on ubuntu 18.04 Bionic and gradually covers all the cores. Server becomes inaccessible during this period and we have to reboot it again though netdata keeps giving the metrics.

Screen shot for the mentioned issue is attached above.
Please help me to rectify the issue ......How can I find what is causing the problem.Does natdata have any such option to download reports for the above attached issue.

**Comment by ilyam8** [comment]
@pkd809 check `Applications` -> `cpu` on the dashboard

**Comment by mfundul** [comment]
You can export snapshots via netdata dashboard (https://twitter.com/linuxnetdata/status/930028316161175554?lang=en). Also you can check the Applications section on the right (e.g. http://127.0.0.1:19999/#menu_apps). There are CPU and disk statistics per process there.
