### ISSUE TITLE
Monitoring 2 varnish services with Netdata

### ISSUE THREAD

**Issue by kaaaq** [netdata/netdata#7317]
I have 2 varnish on one Ubuntu server (I have created 2 process with different ports in systemd),

One of them is for caching data in ram and the second one caching data on file, the scenario is like this:

client request...> Varnish(ram)....>Varnish(file)....>Backend 

Requests come from clients if Varnish(ram) doesn't have the response, forward it to Varnish(file) and If it doesn't have the response it forward the req to backend and then both of them cache the response.

Now the question comes here that how can monitor both of them with Netdata?

on this link (https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/varnish) you didn't explain clearly how I should monitor it.

how can I monitor this 2 varnish services with netdata, please help me and write a sample config file for me for understanding that.
***this is really important that you give me a sample Netdata config file  and explain it how should i do.****
there are 4 files on this link:
https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/varnish
should i write a python.d moudle?
what is varnish.chart.py?

##### OS / Environment:
Ubuntu16.04

##### Expected results:
monitoring the amount ram of varnish one and amount of disk space of varnish two Seprately...

**Comment by ilyam8** [comment]
Hi @kaaaq 

I see `varnish` module uses `varnishstat` binary to get metrics

https://github.com/netdata/netdata/blob/4207f1797ebaf295aa954858d27bfbbeacaf5081/collectors/python.d.plugin/varnish/varnish.chart.py#L215-L218

There is `-n` option

> -n
> Specifies the name of the varnishd instance to get logs from. If -n is not specified, the host name is used.


Probably you could use it. Not a varnish specialist 😄 If `instance_name` works, then you need to set 2 jobs in the `varnish` module config file

```yaml
job_name1:
  instance_name: "instance_name"

job_name2:
  instance_name: "instance_name"
```

**Comment by kaaaq** [comment]
Thanks for your answer but i've 2 varnish services that one of them work with ram backend for caching and one of them with disk,
So i wanna monitor the amount of ram and disk for each service and netdata display it seprately.
What things should i write in "instance_name"?
can i write the name of that service file?

**Comment by ilyam8** [comment]
@kaaaq 

Probably i misunderstood you

See apps plugin, it can show cpu/mem/disk usage per process/group.

https://github.com/netdata/netdata/tree/master/collectors/apps.plugin

**Comment by ilyam8** [comment]
I was saying about python varnish module, which collects varnish specific metrics, see

> https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/varnish

**Comment by kaaaq** [comment]
my problem solved by your first answer:
I add -n option to my varnish service and i write the name in "instance_name"
So now i've two seprated part for monitoring each service.
Thanks so much for your help.

**Comment by kaaaq** [comment]
Hi,
Today i do my previous steps for monitoring varnish with netdata (exactly the same steps)
but in my new server i cant monitor it with netdata
why netdata doesnt show the varnish chart?

**Comment by kaaaq** [comment]
I'm  trying to monitor just one varnish

**Comment by ilyam8** [comment]
closing in favor of #7328
