### ISSUE TITLE
Disk stats (usage, etc.) not reported if /proc/diskstats doesn't exist 

### ISSUE THREAD

**Issue by AnoopAlias** [netdata/netdata#7321]
NetData version - latest

The issue is similar to https://github.com/netdata/netdata/issues/1369

Instead of simfs we have ploop filesystem and the disk stats are not being shown

# iostat -x
Linux 3.10.0 (rep2.hosting1976.fr)      11/15/2019      _x86_64_        (12 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.55    0.34    1.04    0.00    0.00   97.07

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
ploop53188        0.00     0.00  147.92   74.68   806.51  4298.98    45.87     0.00    0.00    0.00    0.00   0.00   0.00

**Comment by stelfrag** [comment]
Hi @AnoopAlias 

Thank you for reporting this! We we will investigate it

**Comment by stelfrag** [comment]
Hi @AnoopAlias

Could you please check and see if the the ploop appears under */sys/block* on your system
or at a path under /sys at all?

There is code in place that takes into account the case when the /proc/diskstats is missing and
goes through several other alternatives under /sys at you mentioned -- similar with the simfs case

thank you for your feedback

**Comment by AnoopAlias** [comment]
Yes the device exist under /sys/block

`# ls /sys/block/ploop53188/
alignment_offset   discard_alignment  inflight           power/             ptune/             removable          slaves/            trace/             
capability         ext_range          pdelta/            pstat/             queue/             ro                 stat               uevent             
dev                holders/           ploop53188p1/      pstate/            range              size               subsystem/    `

**Comment by cakrit** [comment]
@vlvkobal #1369 resulted in what was supposed to be a fix. Can you check?

**Comment by AnoopAlias** [comment]
This was fixed.
