### ISSUE TITLE
Netdata doesn't work alongside Cloudron

### ISSUE THREAD

**Issue by Dinkum** [netdata/netdata#7323]
#### Bug report summary
Cloudron is a popular self hosting software. When I try to install Netdata alongside it, it installs without any obvious errors. However, upon visiting machine.ip:19999 Netdata doesn't load. 

##### OS / Environment
Cloudron on Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-65-generic x86_64)

##### Netdata version (ouput of `netdata -V`)
netdata v1.18.1-114-nightly

##### Component Name
NA

##### Steps To Reproduce
I ran the one-liner from netdata.cloud

##### Expected behavior
That Netdata would be available on machine.ip:19999

**Comment by stelfrag** [comment]
Hi @Dinkum 

Thank you for reporting this. In order to be able to determine what might be wrong, please check the
`error.log` of the server, found typically in `/var/log/netdata/error.log`  

Please run the following command

`grep "LISTENER" /var/log/netdata/error.log`

We want to look for a line similar to this

```
POLLFD: LISTENER: listening on 'tcp:0.0.0.0:19999'
```

**Comment by Dinkum** [comment]
The following logs are on my server. 

> 2019-11-15 16:55:27: netdata INFO  : WEB_SERVER[static1] : POLLFD: LISTENER: listening on 'tcp:0.0.0.0:19999'
2019-11-15 16:55:27: netdata INFO  : WEB_SERVER[static1] : POLLFD: LISTENER: listening on 'tcp:[::]:19999'
2019-11-15 16:55:27: netdata INFO  : STATSD_COLLECTOR[1] : POLLFD: LISTENER: listening on 'udp:127.0.0.1:8125'
2019-11-15 16:55:27: netdata INFO  : STATSD_COLLECTOR[1] : POLLFD: LISTENER: listening on 'tcp:127.0.0.1:8125'
2019-11-15 16:55:27: netdata INFO  : WEB_SERVER[static3] : POLLFD: LISTENER: listening on 'tcp:0.0.0.0:19999'
2019-11-15 16:55:27: netdata INFO  : WEB_SERVER[static3] : POLLFD: LISTENER: listening on 'tcp:[::]:19999'
2019-11-15 16:55:27: netdata INFO  : WEB_SERVER[static2] : POLLFD: LISTENER: listening on 'tcp:0.0.0.0:19999'
2019-11-15 16:55:27: netdata INFO  : WEB_SERVER[static2] : POLLFD: LISTENER: listening on 'tcp:[::]:19999'
2019-11-15 16:55:27: netdata INFO  : WEB_SERVER[static4] : POLLFD: LISTENER: listening on 'tcp:0.0.0.0:19999'
2019-11-15 16:55:27: netdata INFO  : WEB_SERVER[static4] : POLLFD: LISTENER: listening on 'tcp:[::]:19999'

I can also verify Netdata is working by running 
> ssh -L 19999:0.0.0.0:19999 user@machine.ip

and then going to "http://localhost:19999" in my browser.

**Comment by ilyam8** [comment]
> However, upon visiting machine.ip:19999 Netdata doesn't load.

> I can also verify Netdata is working by running
>ssh -L 19999:0.0.0.0:19999 user@machine.ip
> and then going to "http://localhost:19999" in my browser.

So it works, right? It doesnt work when you are trying to access netdata from remote host? Firewall?

**Comment by stelfrag** [comment]
Please try 

`ssh -R 19999:0.0.0.0:19999 user@machine.ip`

on the machine that runs netdata and try again

**Comment by ilyam8** [comment]
> ssh -R 19999:0.0.0.0:19999 user@machine.ip

How is this supposed to work? It is remote forwarding. It creates forwarding  remote 127.0.0.1:19999 -> 127.0.0.1:19999 local.

**Comment by stelfrag** [comment]
> How is this supposed to work? It is remote forwarding. It creates forwarding remote 127.0.0.1:19999 -> 127.0.0.1:19999 local.

Yes, so machine.ip will open a listening port on 127.0.0.1:19999 which is tunneled back to the local
host (where netdata runs)

**Comment by ilyam8** [comment]
What for? I re-read OP. What i see there is

 - netdata is successfully installed on the server (ip - machine.ip)
 - netdata is not accesible from remote via machine.ip:19999
 - netdata is running and accesible from localhost (verified via ssh tunnel - ssh -L 19999:0.0.0.0:19999 user@machine.ip)

**Comment by stelfrag** [comment]
@ilyam8  you are right !!! I incorrectly assumed machine.ip is a different machine

@Dinkum  I apologize for the confusion!

**Comment by ilyam8** [comment]
@Dinkum 

It is very likely built-in firewall, see

> https://cloudron.io/documentation/security/#configuring-cloud-firewall

**Comment by ilyam8** [comment]
From the info you posted https://github.com/netdata/netdata/issues/7323#issuecomment-554468834 i see netdata is up and running. See output from `ps  faxu | grep [n]etdata`.

**Comment by Dinkum** [comment]
You are correct @ilyam8 about the details about the issue I am facing. 

I just found, and was about to paste the Cloudron documentation link, but you beat me to it. 

Netdata is up and running, and this is indeed a Cloudron issue not a Netdata issue. 
> ps faxu | grep [n]etdata

further confirms this. Thanks for the help!

**Comment by gramakri** [comment]
Thanks for debugging this, we will fixup Cloudron firewall configuration to support netdata

**Comment by ezbot21** [comment]
@gramakri may i know has cloudron team fix the firewall issue already? Or what is the workaround for the time being? manually edit the firewall using sudo ufw allow 19999... Please advice. Thank you. :)

**Comment by alexander-potemkin** [comment]
Raising this up, in case it got missed, @gramakri ?

**Comment by gramakri** [comment]
I guess https://docs.cloudron.io/networking/#whitelist-ports is what you are looking for. You can open specific ports on the Cloudron firewall.
