### ISSUE TITLE
Bug in creating Makefile

### ISSUE THREAD

**Issue by rsyncOSX** [netdata/netdata#7324]
Utilizing ./netdata-installer.sh on FreeBSD 12.1 fails. Creating Makefile by ./configure --disable-dependency-tracking works and netdata compiles, does not seems there are missing libraries..

config.status: error: in `/root/netdata':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
 FAILED

**Comment by thiagoftsm** [comment]
Hi @rsyncOSX ,

I was testing now the netdata-installer.sh on FreeBSD 12-p12 and I saw that `config.log` is reporting the following message:

```
config.status:1374: executing depfiles commands
config.status:1449: cd .       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
make: "(stdin)" line 4566: Missing dependency operator
make: Fatal errors encountered -- cannot continue
```

Please, can you confirm that you have the same messages in your `config.log`?

Best regards!

**Comment by rsyncOSX** [comment]
Thx, dont have access to my FreeBSD server until later this evening (verify config.log). Issue is solved and closed so I suppose this is not necessary now ...

**Comment by thiagoftsm** [comment]
It looks like that the problem was already fixed with the PR #7326 , please, can you test it for we confirm? At least on my FreeBSD when I compile it worked fine.

Best regards!

**Comment by amoss** [comment]
@rsyncOSX The issue closed automatically because the PR is connected to the issue. If you still see a problem when you try it please feel free to re-open the issue and give us more information.

**Comment by rsyncOSX** [comment]
> @rsyncOSX The issue closed automatically because the PR is connected to the issue. If you still see a problem when you try it please feel free to re-open the issue and give us more information.

@amoss @thiagoftsm I can confirm netdata compiles after pulling the update on netdata on my FreeBSD 12.1.
