### ISSUE TITLE
Stable release tarballs should default to RELEASE_CHANNEL=stable

### ISSUE THREAD

**Issue by knatsakis** [netdata/netdata#7331]
##### Bug report summary
When installing from a stable tarball as those found in GitHub releases page, the RELEASE_CHANNEL should default to `stable`

##### OS / Environment
All

##### Netdata version (ouput of `netdata -V`)
Current stable releases

##### Component Name
Packaging

##### Steps To Reproduce
Download the latest stable release tarball from GitHub release page and install netdata. The RELEASE_CHANNEL written in /etc/netdata/.environment will be `nightly`

##### Expected behavior
The RELEASE_CHANNEL in /etc/netdata/.environment should be `stable`

**Comment by ncmans** [comment]
Related to https://github.com/netdata/netdata/issues/7295
