### ISSUE TITLE
Sort of issue with netdata charts stop updating

### ISSUE THREAD

**Issue by weeblr** [netdata/netdata#7336]
##### Bug report summary
On my custom dashboard, charts stop updating after a few minutes. Needs a hard reload to start updating again.
##### OS / Environment
Browsers: windows Chrome,Brave,Firefox, all current versions.
##### Netdata version (ouput of `netdata -V`)
1.18.1
##### Steps To Reproduce
I have made a custom dashboard to show basic data from 7 different servers, including the one that's running as master. 
The dashboard works fine. It is set to continuously update even after loosing focus with:

````
// always update the charts, even if focus is lost
NETDATA.options.current.stop_updates_when_focus_is_lost = false;
````

That works, dashboard updates after loosing focus but charts stop updating after a few minutes. Same with Chrome/Brave/Firefox. Also if started in 2 tabs of the same browser, the default Netdata dashboard keeps updating while the custom one stops after a while.

No javascript error or warning in the console. The console shows that when this happens, no further requests to the server are made, they just stop. The javascript is not "dead" as the reload code is executed and the page reloads as expected. 
However the automatic reload does not restart updating the charts. Only a hard reload with Ctrl+R or ctrl+reload button resets everything and charts updates again, until next stop.

After doing quite some tests, **I realized the charts stopped updating just after that automatic reload**!  I commented out the automatic reload code and the dashboard has now been updating for 30mn.

The reload code is the standard one:

````
    var RELOAD_EVERY = 5;
    setTimeout(function () {
        location.reload();
    }, RELOAD_EVERY * 60 * 1000);
````

I have now tested with forcing a hard reload from javascript:

````
    var RELOAD_EVERY = 5;
    setTimeout(function () {
        location.reload(true);
    }, RELOAD_EVERY * 60 * 1000);
````

But charts stop updating after a while, exactly as before. I'm not sure brave support this location.reload syntax though, MDN is unclear that.

Any clue as to what can cause this and how to fix it?

###### Dashboard code (simplified, some charts remove)

````
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Example Dashboard</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

</head>
<body class="p-8 ">

<!-------------------- xxxxxx requests ---------------------------->
<div class="flex justify-center md:justify-start flex-wrap">
    <div class="md:absolute w-full md:w-auto self-start md:pl-6">
        <h4 class="font-semibold">xxxxxx.com</h4>
    </div>
    <div class="md:w-1/6 self-end mt-6">
        <div class="netdata-container-gauge" data-host="https://yyyyxxxxxx.com:19999/host/xxxxxx.com"
             data-netdata="phpfpm_local.requests" data-dimensions=""
             data-after="-600"
             data-points="240"
             data-gauge-max-value="20"
             data-chart-library="gauge" data-title="PHP requests" data-colors="#66AA00"
             data-gauge-stroke-color="#888888"
             data-width="12em" data-height="">
        </div>
    </div>
    <div class="md:w-1/6 self-end mt-6">
        <div class="netdata-container-gauge" data-host="https://yyyyxxxxxx.com:19999/host/xxxxxx.com"
             data-netdata="mysql_local.queries" data-dimensions="queries"
             data-after="-600"
             data-points="240"
             data-chart-library="gauge" data-title="MYSQL requests" data-colors="#66AA00"
             data-gauge-stroke-color="#888888"
             data-width="12em" data-height="">
        </div>
    </div>
    <div class="md:w-1/6 self-end mt-6">
        <div class="netdata-container-gauge" data-host="https://yyyyxxxxxx.com:19999/host/xxxxxx.com"
             data-netdata="nginx_local.requests" data-dimensions=""
             data-after="-600"
             data-points="240"
             data-gauge-max-value="100"
             data-chart-library="gauge" data-title="Nginx requests" data-colors="#66AA00"
             data-gauge-stroke-color="#888888"
             data-width="12em" data-height="">
        </div>
    </div>
    <div class="w-1/2 hidden md:block self-end">
        <div class="netdata-container-with-legend" data-host="https://yyyyxxxxxx.com:19999/host/xxxxxx.com"
             data-netdata="nginx_local.requests"
             data-dygraph-valuerange="[0,100]"
             data-width="100%" data-height="100%" data-before="0"
             data-after="-420" data-id="xxxxxx_com_nginx_local_requests" data-colors="#66AA00"
             data-decimal-digits="-1">
        </div>
    </div>
</div>

</body>
<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous">
</script>

<script>var netdataNoBootstrap = true;</script>

<script type="text/javascript" src="https://yyyyxxxxxx.com:19999/dashboard.js"></script>
<script>
    // Set options for TV operation
    // This has to be done, after dashboard.js is loaded

    // destroy charts not shown (lowers memory on the browser)
    NETDATA.options.current.destroy_on_hide = true;

    // set this to false, to always show all dimensions
    NETDATA.options.current.eliminate_zero_dimensions = false;

    // lower the pressure on this browser
    NETDATA.options.current.concurrent_refreshes = false;

    // if the tv browser is too slow (a pi?)
    // set this to false
    NETDATA.options.current.parallel_refresher = true;

    // always update the charts, even if focus is lost
    NETDATA.options.current.stop_updates_when_focus_is_lost = false;

    // Since you may render charts from many servers and any of them may
    // become offline for some time, the charts will break.
    // This will reload the page every RELOAD_EVERY minutes
    var RELOAD_EVERY = 5;
    setTimeout(function () {
        location.reload();
    }, RELOAD_EVERY * 60 * 1000);

    // custom function to change color based on threshold in pie charts
    function wbPieChartBarColorLowerIsBetter(percent) {
        switch (true) {
            case percent > 90:
                return '#cb3935';
                break;
            case percent > 50:
                return '#f0ad4e';
                break;
            default:
                return '#5cb85c';
                break;
        }
    }

    function wbPieChartBarColorLoadAverage(value) {
        switch (true) {
            case value > 25:
                return '#cb3935';
                break;
            case value > 10:
                return '#f0ad4e';
                break;
            default:
                return '#5cb85c';
                break;
        }
    }

</script>
</html>

````

**Comment by jacekkolasa** [comment]
hi @weeblr! I am unable to recreate the bug, i've done similar setup, just made the refresh happen every `60 * 1000` ms, opened few tabs with custom dashboard, 1 with Default Dashboard and it all works, without focus and the refresh doesn't break it.

Could you check opening your setup from Chrome Incognito Window, and also leave opened dev tools with network tab, to see if requests to your servers are properly send?

**Comment by weeblr** [comment]
Hi @jacekkolasa 

Yep, that just does not make any sense :)

> just made the refresh happen every 60 * 1000 ms

I am refreshing every 5 minutes, not every minute. It may make a difference but I have not tested with one minute yet.

> Could you check opening your setup from Chrome Incognito Window,

Will do and report

>  and also leave opened dev tools with network tab, to see if requests to your servers are properly send?

Like I said, that's the 1st thing I looked at and the requests are totally NOT sent. The app just stops asking for data. And again, there's no javascript error in the console that would justify stopping requests. The auto-refresh keeps happening again and again as expected.

I normally use Brave but I'll do all subsequent testing with Chrome.
FYI, I have now removed the auto-reload and the dashboard has been updating fine for more than an hour with me doing plenty of other things. 

Best regards

**Comment by jacekkolasa** [comment]
@weeblr hi again, after more experiments i was finally able to recreate your issue, and the problem most probably was the additional jquery loading. When i removed your `src="https://code.jquery.com/jquery-3.4.1.min.js"` script, it started to work. I think it's probably a bug in dashboard.js related to this. Please let us know if that will fix your problem.

**Comment by weeblr** [comment]
@jacekkolasa Thanks for looking into this. In the mean time I had tested that Incognito or reloading every minute was having the same effect. 

I though jquery was required but I'll take it out now.

BTW: I did notice one thing in the console:

````
localStorage: LOADED UNDEFINED "options.destroy_on_hide" as value undefined of type undefined
````

Is this related? 

Best regards

**Comment by weeblr** [comment]
Yes, works! removing jquery allows normal operation. I do not see any issue with removing it either.

**Comment by jacekkolasa** [comment]
Happy to hear it's working :) I'll close the issue then, but if they will be problems, feel free to reopen/ask here. 
Btw. we are working on refractoring dashboard.js, so when we'll release, that issue will not be present

**Comment by weeblr** [comment]
Hi

can you comment on:

> localStorage: LOADED UNDEFINED "options.destroy_on_hide" as value undefined of type undefined

or should I open another issue for that?

**Comment by jacekkolasa** [comment]
Thanks for mentioning it, i think we'll fix that during refractor, so there's no need for separate issue 👍 

And thanks for all the input, it's good to know this problem exists.
