### ISSUE TITLE
Eliminate LXC from package generation pipeline

### ISSUE THREAD

**Issue by cosmix** [netdata/netdata#7346]
### Rationale

Currently LXC is used to build the agent packages for linux distributions. This has already proved problematic, necessitating several workarounds to make things work. More people are familiar with Docker (vs LXC), there is much more community support and documentation, let alone tooling to automate this, and it would make sense to move our package building to Docker.

**Comment by prologic** [comment]
@Ferroin Can we turn this into an EPIC? I can't tell how far along we are with this and/or if you need any help? :) I'm pretty full up at the moment with eBPF but I'd love to help you here if you need it!

**Comment by Ferroin** [comment]
> @Ferroin Can we turn this into an EPIC? I can't tell how far along we are with this and/or if you need any help? :) I'm pretty full up at the moment with eBPF but I'd love to help you here if you need it!

I don't know that an EPIC really fits in this case, as there are only two intermediary steps, both are done, and neither have a direct user-visible impact.

As far as progress, right now I'm just trying to find the time to actually test the GHA workflows I've put together for this. I'd be happy to push the branch to my fork if you want to look at it and try testing it though.

**Comment by prologic** [comment]
> As far as progress, right now I'm just trying to find the time to actually test the GHA workflows I've put together for this. I'd be happy to push the branch to my fork if you want to look at it and try testing it though.

Please by all means :D early feedback is always better! I can help you test it :)

**Comment by Ferroin** [comment]
> > As far as progress, right now I'm just trying to find the time to actually test the GHA workflows I've put together for this. I'd be happy to push the branch to my fork if you want to look at it and try testing it though.
> 
> Please by all means :D early feedback is always better! I can help you test it :)

OK, the branch is up. It's called `gha-packaging`. Right now it's just doing amd64 packages, but it covers all 5 distros we use with all versions we support (and takes significant advantage of YAML's anchor map merging to avoid duplication). It's also using a custom local action to do the commit filtering, because there not only isn't any support for this in GHA, but there isn't any published action I could find that does it the way we need to either.

**Comment by prologic** [comment]
> OK, the branch is up. It's called `gha-packaging`. Right now it's just doing amd64 packages, but it covers all 5 distros we use with all versions we support (and takes significant advantage of YAML's anchor map merging to avoid duplication).

Thanks I'll check it out! Can you put the PR itself up too in Draft form?

> It's also using a custom local action to do the commit filtering, because there not only isn't any support for this in GHA, but there isn't any published action I could find that does it the way we need to either.

yeah this is okay; thats why actions are so flexible, GHA doesn't need to support this natively per se.

**Comment by Ferroin** [comment]
> Thanks I'll check it out! Can you put the PR itself up too in Draft form?

Done, #8065.

**Comment by Ferroin** [comment]
Not inactive, just slow.

**Comment by cakrit** [comment]
This will be done as part of the move to GHA
