### ISSUE TITLE
Cannot install or update netdata from 1.14 and prior

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#7350]
##### Bug report summary

Netdata was installed on a system:

```
# netdata -V
netdata v1.14.0-rc0-20-nightly
```

Run netdata updater to update it:

```
# /etc/cron.daily/netdata-updater
Thu Nov 21 14:33:05 EET 2019 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
ef8af858cfa1218e252b6594c3f6620901fab5840e28d2e5890a982b74359a6a *./latest-version.txt
6a5124c1ecc5a4b50b1cec4aa755b6886f0b1785d338a1c957ec4a0a3ccb73c2 *./netdata-latest.gz.run
054987bffe530b25b1a3c9c345498cffa8a5e432fa976782e49f5ad6de6102cb *./netdata-latest.tar.gz
6a5124c1ecc5a4b50b1cec4aa755b6886f0b1785d338a1c957ec4a0a3ccb73c2 *./netdata-v1.18.1-144-g2c26cb21.gz.run
054987bffe530b25b1a3c9c345498cffa8a5e432fa976782e49f5ad6de6102cb *./netdata-v1.18.1-144-g2c26cb21.tar.gz
Thu Nov 21 14:33:06 EET 2019 : INFO:  Newest version is already installed
```

It thinks the latest version is already installed. It is not.

Let's run the installer again to install the latest version:

```
# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 --- Re-installing netdata... ---
[/root]# '' /etc/cron.daily/netdata-updater -f
/dev/fd/63: line 114: : command not found
 FAILED

 ABORTED  Failed to forcefully update netdata
```

It fails too.

##### OS / Environment

```
# cat /etc/os-release
PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="November 2019"
VERSION_ID="2019.11-1"
ID=osmc
ID_LIKE=debian

ANSI_COLOR="1;31"
HOME_URL="https://www.osmc.tv"
SUPPORT_URL="https://www.osmc.tv"
BUG_REPORT_URL="https://www.osmc.tv"
```

##### Netdata version (ouput of `netdata -V`)

```
# netdata -V
netdata v1.14.0-rc0-20-nightly
```

##### Component Name

N/A

##### Steps To Reproduce

I am not sure. I just found this system like that.

##### Expected behavior

Update or re-install netdata.

**Comment by ktsaou** [comment]
The solution to re-install netdata was to `rm /etc/cron.daily/netdata-updater` and then run the kickstart again.

But still, the default installation scripts have a dead-end when upgrading from older versions of netdata.

**Comment by thiagoftsm** [comment]
I remember we had a PR that updated `netdata-installer.sh`, because an user reported that netdata was not updating according expected. @knatsakis is it possible that PR has relationship with this error?

**Comment by cosmix** [comment]
@ktsaou installing 1.14 (release) and then following the above steps resulted in a normal update to 1.14 for me. @knatsakis @ncmans can you reproduce?

**Comment by ncmans** [comment]
Fresh installed on Ubuntu Bionic:

```
$ git checkout v1.14.0
$ sudo ./netdata-installer.sh -u
$ netdata -V
netdata v1.14.0
$ /etc/cron.daily/netdata-updater
# Successful
```

So either this is OSMC specific (need a Rpi to test), or there are other changes on that installations before the update.

**Comment by stelfrag** [comment]
I will try to check this over the weekend. I have Rpi with OSMC

**Comment by stelfrag** [comment]
Could not reproduce

```
osmc@Kodi:~/netdata$ netdata -v
netdata v1.14.0
osmc@Kodi:~/netdata$ sudo /etc/cron.daily/netdata-updater
:
: 
Setting netdata.tarball.checksum to 'new_installation'

 --- We are done! --- 

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed and running now!  -'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  enjoy real-time performance and health monitoring...

osmc@Kodi:~/netdata$ netdata -v
netdata v1.18.1-154-nightly
osmc@Kodi:~/netdata$
```
The only thing different is the actual starting version/build
which is `netdata v1.14.0-rc0-20-nightly` and I started from
the `v1.14.0` tag

I will see if I can recheck with a commit close to `netdata v1.14.0-rc0-20-nightly`

**Comment by espensgr** [comment]
I can reproduce this, all my digital ocean servers have this problem. 
The fix with `rm /etc/cron.daily/netdata-updater` and then running the `kickstart.sh` works.
The only thing is i had to run the rm with sudo.

**Comment by ilyam8** [comment]
seems related https://github.com/netdata/netdata/issues/5272

i recall we had such problem

**Comment by amoss** [comment]
@ktsaou We can't reproduce this locally, but the comment from @espensgr may be useful if you see the problem again. Please feel free to reopen if this re-occurs.
