### ISSUE TITLE
Re-introduce Netdata to FreeNAS

### ISSUE THREAD

**Issue by ncmans** [netdata/netdata#7356]
## Background

Netdata has been [removed from FreeNAS since 11.3](https://github.com/freenas/freenas/pull/3633/files) due to reportedly "long standing memory leaks" as explained in [a relevant forum post](https://www.ixsystems.com/community/threads/is-there-anything-like-a-netdata-equivalent-for-freenas.79945/#post-553692).

We really like what FreeNAS folks do and would like to see this issue figured out and netdata reintroduced as we think it offers significant value to their users.

https://github.com/netdata/netdata/issues/1707 may be related to the mentioned memory leaks.

**Comment by TRUNKSNEO** [comment]
Please accept my comment as a point of view and an interest of seeing this application/plugin NETDATA either fixed or available for users to decide for them self and not having to hack the system just to be able to install it.  

Adding also the following comment as mention on #1707 by @jordanhubbard himself 
"I will say that the newest version, out of the git repo, exhibits FAR less system overhead and seems to essentially fix the problems I've observed before by means of what I will simply refer to as magical unicorns :) It definitely seems to be much better."

In my view this either points to a fix or has also mention by @jordanhubbard "we can all hope for the best" 😉, so far for me it works great and I have been using with very little if any tweaks for the last 2 year, just updating on every major release. 

Adding some of my FreeNAS info to assist the comment, please let me know if there is any more information I can share to further sustain this request for NETDATA in the upcoming FreeNAS 11.3 thank you. 

![HTOP](https://user-images.githubusercontent.com/639710/71182429-fd058b00-226d-11ea-8a4e-f92032417710.jpeg)

![Dashboard](https://user-images.githubusercontent.com/639710/71182432-fd9e2180-226d-11ea-9d3c-5756183e3834.jpeg)

![NetData](https://user-images.githubusercontent.com/639710/71182433-fd9e2180-226d-11ea-8c6c-31ce4c314da6.jpeg)

**Comment by LeoWinterDE** [comment]
Would like to see a [Netdata plugin](https://www.freenas.org/plugins/) for FreeNas.
I'll take a closer look at it when I have some time to build it - https://www.ixsystems.com/documentation/freenas/11.3-RELEASE/plugins.html#create-a-plugin

**Comment by olivluca** [comment]
> ## Background
> 
> Netdata has been [removed from FreeNAS since 11.3](https://github.com/freenas/freenas/pull/3633/files) due to reportedly "long standing memory leaks" as explained in [a relevant forum post](https://www.ixsystems.com/community/threads/is-there-anything-like-a-netdata-equivalent-for-freenas.79945/#post-553692).


I cannot find that post but I found [this one](https://www.ixsystems.com/community/threads/replacement-for-netdata.80054/) where they say there's a community maintained plugin.
Funny that they removed it because I'm starting to put netdata everywhere only because I saw it in freenas.

**Comment by aserrallerios** [comment]
There's a community plugin, but some of the metrics are jails' instead of host's, and I don't think there's any way to overcome that limitation.

**Comment by wade-p** [comment]
One way to install on the host is to [enable the pkg manager](https://www.justinsilver.com/random/fix-pkg-on-freenas-11-2/) then pkg install netdata

I needed to tweak the config in /usr/local/etc/netdata/netdata.conf to bind to something other than localhost (127.0.0.1) since I wanted to scrape netdata with prometheus.
