### ISSUE TITLE
Netdata v1.18.1-165-gbd5f9122 Segfaulting

### ISSUE THREAD

**Issue by dkowis** [netdata/netdata#7361]
##### Bug report summary
All the netdatas on my (xen-based) virtual machines on ubuntu 18.04 are segfaulting.

Been happening for a while now, I think, prometheus shows the last data collection on 22 Nov at 6am. So I guess yesterday morning. Probably after an automated update.

```
Nov 23 17:32:12 monitor netdata[3004]: 2019-11-23 17:32:12: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Nov 23 17:32:12 monitor kernel: [  774.936176] PLUGIN[diskspac[3024]: segfault at 7c ip 00007f5e142efefd sp 00007f5e14715830 error 4 in netdata[7f5e14217000+317000]
Nov 23 17:32:12 monitor kernel: [  774.936202] Code: 8d 3d 4b 27 1a 00 89 44 24 1c e8 ae ed 00 00 89 05 d4 e6 46 00 48 8b 05 a1 2c 48 00 48 8d 35 86 13 18 00 48 8d 3d 27 27 1a 00 <48> 63 50 7c e8 1a d5 00 00 48 8b 15 83 2c 48 00 41 89 c6 48 8d 35
Nov 23 17:32:13 monitor systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
Nov 23 17:32:13 monitor systemd[1]: netdata.service: Failed with result 'signal'.
```
##### OS / Environment

uname: `Linux monitor.dark.kow.is 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

##### Netdata version (ouput of `netdata -V`)
netdata v1.18.1-165-gbd5f9122

##### Component Name
cgroups, diskspac, idlejitt, proc, tc are all showing up with segfaults in my `dmesg`

##### Steps To Reproduce
Try to start the application.

##### Expected behavior
The application should start, and collect metrics.

**Comment by dkowis** [comment]
An update to: `netdata v1.18.1-165-gbd5f9122` is still segfaulting.

**Comment by mfundul** [comment]
Can you follow [these](https://docs.netdata.cloud/daemon/#debugging) instructions to compile a netdata binary with debugging enabled?

Then you should be able to run netdata with `gdb` and gather a backtrace by typing `bt` in the `gdb` command line after it crashes.

**Comment by cakrit** [comment]
No response here in a while, closing.
