### ISSUE TITLE
Install netdata with Python3

### ISSUE THREAD

**Issue by AbdelmalekIhdene** [netdata/netdata#7364]
##### Question summary
I run the installation command `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` and it prompts me to install python2.7 and successfully installs. However, I was wondering if it was possible to install netdata with python3 instead of python2.7.

##### OS / Environment
Ubuntu 18.04 LTS

**Comment by ncmans** [comment]
Thanks @AbdelmalekIhdene for the report.

netdata can be installed with python 3 as well. However, the default python package on Ubuntu 18.04 LTS is python 2 and I've confirmed that it does indeed try to install `python` package even if `python3` is already installed.

I do think that netdata should pick any compatible python already installed and use that.

**Comment by Ferroin** [comment]
We can check whether `python` or `python3` are installed using the following one-liner on any dpkg based system (including Ubuntu, Debian, and Devuan):

    dpkg --list-selections | grep -E -q 'python3?\s*install'

That will return an exit status of 0 if one of the packages with the exact names `python` or `python3` is installed, or 1 if neither is installed (and it doesn't need root privileges, but that's not really relevant here).

I'm of the opinion that we should probably prefer Python 3.x over Python 2.x on install if neither is installed, as it's a bit more efficient, though it's unlikely that we'll come across a system that doesn't have one of the two installed (every dpkg-based distro I know of has one or the other as part of the default install).

**Comment by AbdelmalekIhdene** [comment]
Does netdata check for the existence of python2 or just for the existence of python? A quick fix for now, I believe, would be `alias python=python3`.

**Comment by ncmans** [comment]
> Does netdata check for the existence of python2 or just for the existence of python? A quick fix for now, I believe, would be `alias python=python3`.

Installer checks if a certain package is installed by querying the package manager, and so aliasing python will have no effect in this case.

**Comment by IceCodeNew** [comment]
```
update-alternatives --install /usr/bin/python python /usr/bin/python2 1
update-alternatives --install /usr/bin/python python /usr/bin/python3 2
```

I used to have the same problem and I find out these commands could solve this problem for good.
