### ISSUE TITLE
python.d.conf is restored to original value

### ISSUE THREAD

**Issue by firstlevelIT** [netdata/netdata#7367]
all changes to python.d.conf are lost. why it's rewritten? by who?

**Comment by ilyam8** [comment]
Hi @firstlevelIT 

Rewritten by the installer. You modifies stock config. To make changes permanent you need to copy `python.d.conf` to the `/etc/netdata` dir and make changes in there.

See configuration guide

> https://docs.netdata.cloud/docs/configuration-guide/

**Comment by ilyam8** [comment]
@firstlevelIT i m closing this but if you still have question feel free to ask
