### ISSUE TITLE
As a user, I want to be able to use custom host labels in alarm configurations, so that I can group a collection of resources that are logically related

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7369]
- [x] Add new parameter to alarms and alarm templates that allows a user to apply the alarm only to charts of hosts with the specific labels. The parameter should accept [netdata simple patterns](https://docs.netdata.cloud/libnetdata/simple_pattern/) 
- [ ] See labels as available variables in `/api/v1/alarm_variables`

**Comment by thiagoftsm** [comment]
Here we can have two different approaches in my vision, we can create another line on alarms and template or we can use `on`  to define this, right now I am inclined to use the last option, unless the rest of structure force me to change this.

**Comment by thiagoftsm** [comment]
Considering the initial talk on #7370, I am thinking that probably we can have labels also displayed as result for `/api/v1/alarm_log/.

**Comment by thiagoftsm** [comment]
Hi @cakrit ,

In the `label` line that we are bringing for Netdata,  you said " alarm only to charts of hosts with the specific labels.",  I understood that we are considering these possible values:

- `label` : The user only specifies the label without its value, so we will check the presence of the label only and we will apply the alarm independent of the value.
- `labelX = valueA`: The host must have the label `labelX` with the value `valueA`

Am I missing something? Or Am I extending what was thought before?

Thanks!

**Comment by ilyam8** [comment]
> Add new parameter to alarms and alarm templates that allows a user to apply the alarm only to charts of hosts with the specific labels. 

> we can create another line on alarms and template 

Not easy as it looks. I dont understand how it works, how to define AND/OR logic.

**Comment by amoss** [comment]
Merged and completed.
