### ISSUE TITLE
Export snapshots to PDF

### ISSUE THREAD

**Issue by ChrisEt** [netdata/netdata#7374]
##### Feature idea summary
It would be great if snapshots could be printed to PDF. At the moment, only the live dashboard has a "Print" icon. Loaded snapshots don't.

##### Expected behavior
The use case is that I perform an experiment on my device and want to record all metrics for later analysis. So right after the experiment, I save it as a snapshot. I can load this snapshot at a later time and analyze every chart in detail. But for less netdata-versed techies I'd also like to archive the whole experiment in PDF form. This is not possible at the moment because there is no "Print" icon when working on a loaded snapshot.

I don't know if this suggestion is easy to implement or near impossible. Or maybe this use case could be solved in a different way, such as adding a "include PDF" option when saving a snapshot?

Anyway, thanks a lot for developing and maintaining such a great tool!

**Comment by prologic** [comment]
@jacekkolasa Is this something we can work on or plan to work on in the near future? I haven't played with this aspect of the NetData UI yet myself.

**Comment by jacekkolasa** [comment]
it's a nice idea, thanks for asking, i'll keep it in the backlog!

**Comment by magedfawzy** [comment]
was there a fix.. i desperatly need to save as pdf for 1 hour at least. Thanks

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
