### ISSUE TITLE
sh启动13行报错什么鬼

### ISSUE THREAD

**Issue by joweywen** [netdata/netdata#7378]
sh启动13行报错什么鬼，求助哪
netdata-installer.sh: line 13: syntax error near unexpected token `<'
netdata-installer.sh: line 13: `        done < <(echo "${PATH}" | tr ":" "\\n")'

**Comment by ilyam8** [comment]
@knatsakis please take a look

**Comment by xshi0001** [comment]
hi!
here is the same problem
```
[root@Carroad114 netdata-v1.19.0]# sh netdata-installer.sh
netdata-installer.sh: line 13: syntax error near unexpected token `<'
netdata-installer.sh: line 13: `        done < <(echo "${PATH}" | tr ":" "\\n")'
```
```
[root@Carroad114 netdata-v1.19.0]# uname -a
Linux Carroad114 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by ilyam8** [comment]
@Ferroin please check

**Comment by Ferroin** [comment]
@xshi0001 The install script currently requires Bash 4 (or newer). It will not work with POSIX sh. We have plans to change this long term, but it's not a high priority right now.
