### ISSUE TITLE
Looks like netdata restart constantly

### ISSUE THREAD

**Issue by kozicpetar** [netdata/netdata#7379]
Hi at all,
I have one issue on the two same servers. Actually, I have installed three new CpanelDNS servers with same configuration.
On all servers, I installed netdata with kickstart from manual.

On two of that three server I have same logs and looks like a netdata was in some restart loop.
My netdata bind on non default port, I set port 19000

##### Bug report summary
In syslog I have this:
```
netdata: 2019-11-28 11:11:30: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
netdata: LISTENER: IPv4 bind() on ip '0.0.0.0' port 19000, socktype 1 failed.
netdata: 2019-11-28 11:11:30: netdata ERROR : MAIN : LISTENER: IPv4 bind() on ip '0.0.0.0' port 19000, socktype 1 failed. (errno 98, Address already in use)
netdata: 2019-11-28 11:11:30: netdata ERROR : MAIN : LISTENER: Cannot bind to ip '0.0.0.0', port 19000
netdata: 2019-11-28 11:11:30: netdata ERROR : MAIN : LISTENER: IPv6 bind() on ip '::' port 19000, socktype 1 failed. (errno 98, Address already in use)
netdata: 2019-11-28 11:11:30: netdata ERROR : MAIN : LISTENER: Cannot bind to ip '::', port 19000
netdata: 2019-11-28 11:11:30: netdata FATAL : MAIN :LISTENER: Cannot listen on any API socket. Exiting... # : Success
netdata: 2019-11-28 11:11:30: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
netdata: 2019-11-28 11:11:30: netdata INFO  : MAIN : EXIT: cleaning up the database...
netdata: 2019-11-28 11:11:30: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
netdata: 2019-11-28 11:11:30: netdata INFO  : MAIN : EXIT: removing netdata PID file '/var/run/netdata/netdata.pid'...
netdata: 2019-11-28 11:11:30: netdata ERROR : MAIN : EXIT: cannot unlink pidfile '/var/run/netdata/netdata.pid'. (errno 2, No such file or directory)
netdata: 2019-11-28 11:11:30: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
netdata: LISTENER: Cannot bind to ip '0.0.0.0', port 19000
systemd: netdata.service: main process exited, code=exited, status=1/FAILURE
netdata: LISTENER: IPv6 bind() on ip '::' port 19000, socktype 1 failed.
systemd: Unit netdata.service entered failed state.
netdata: LISTENER: Cannot bind to ip '::', port 19000
systemd: netdata.service failed.
netdata: LISTENER: Cannot listen on any API socket. Exiting...
netdata: EXIT: netdata prepares to exit with code 1...
netdata: EXIT: cleaning up the database...
netdata: Cleaning up database [0 hosts(s)]...
netdata: EXIT: removing netdata PID file '/var/run/netdata/netdata.pid'...
netdata: EXIT: cannot unlink pidfile '/var/run/netdata/netdata.pid'.
netdata: EXIT: all done - netdata is now exiting - bye bye...
```

##### OS / Environment
On both problematic server:
```
CentOS Linux release 7.7.1908 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.7.1908 (Core)
CentOS Linux release 7.7.1908 (Core)
```

##### Netdata version (ouput of `netdata -V`)
`netdata v1.19.0`

**Comment by thiagoftsm** [comment]
Hi @kozicpetar ,

According this log, you already have some process using the port 19000, considering that you are using the newest version, I have few doubts:

1 - Was your installation an update from previous versions?
2 - What is the output of the command `ss -lptn 'sport = :19999'`? 
3 - The previous command will display the PID, can you also run the command `ps aux| grep PID`?

Best regards!

**Comment by kozicpetar** [comment]
No, I don't have another process which using same port.
1. Fresh installed netdata
2. 
`ss -lptn 'sport = :19999'`
```
State      Recv-Q Send-Q                                                                         Local Address:Port                                                                                        Peer Address:Port
```

because my netdata was on another port

`ss -lptn 'sport = :19000`
```
State      Recv-Q Send-Q                 Local Address:Port        Peer Address:Port
LISTEN     0      128                            *:19000                         *:*                      users:(("netdata",pid=24101,fd=4))
LISTEN     0      128                           [::]:19000                       [::]:*                   users:(("netdata",pid=24101,fd=5))
```

3.
```netdata  24101  0.3 11.4 334260 116248 ?       SNl  03:39   2:44 /usr/sbin/netdata```

**Comment by thiagoftsm** [comment]
Firstly I apologize the confusion, I ran the command before on my computer to remember the correct options after this I copied the command and I forgot to change.
There are basically two possibilities for the Linux does not allow Netdata uses the socket.

1 - There is another process running on it as a client, we can detect this case you stop Netdata and run the same command I asked you before.
2 - The second possible problem is another service process tried to use the socket before and it did not close it correctly. The Linux can freeze the socket for few minutes before allow Netdata to use it.

Please, could you do the possibility 1 for we have more information? After this, with Netdata stopped yet, could you run the command `netstat -antp | grep 19000` ?

**Comment by ilyam8** [comment]
> netstat -antp | grep 19000

you need to run it as a `roor` user to see processes (`p` option)

or use

> sudo ss -ntlp 'sport = :19000'

**Comment by ilyam8** [comment]
ok, it is already in https://github.com/netdata/netdata/issues/7379#issuecomment-559536245

```
State      Recv-Q Send-Q                 Local Address:Port        Peer Address:Port
LISTEN     0      128                            *:19000                         *:*                      users:(("netdata",pid=24101,fd=4))
LISTEN     0      128                           [::]:19000                       [::]:*                   users:(("netdata",pid=24101,fd=5)
```

Netdata is up and running. Somehow you are trying to start up another instance of netdata.

**Comment by kozicpetar** [comment]
How's that is possible when netdata was installed from kickstart on all three servers ?

**Comment by kozicpetar** [comment]
When I stoped netdata service

`systemctl stop netdata`

and did `ps aux | grep netdata` I saw several netdata process still working.

`killall -9 netdata`
was helped me to stop all process

and again running `systemctl start netdata` solved my problem.
Thanks.

**Comment by maravento** [comment]
Please reopen this ticket. The solutions offered do not work and the processes are still open:
```
netdata   997533  0.0  0.0  70716 25980 ?        Sl   11:47   0:03 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
root      997541  0.0  0.0 388436  4048 ?        Sl   11:47   0:05 /usr/libexec/netdata/plugins.d/ebpf.plugin 1
```

**Comment by 1265578519** [comment]
BUG：netdata INFO  : MAIN : SIGNAL: Not enabling reaper
chown -R netdata:netdata /var/cache/netdata
chown -R netdata:netdata /var/lib/netdata
chown -R netdata:netdata /var/log/netdata
运行命令修复权限
