### ISSUE TITLE
Usefull slave data links on dashboard

### ISSUE THREAD

**Issue by RealKelsar** [netdata/netdata#7380]
### Feature idea summary

Links in the Master Dashboard are like:

```http://master.example.com:19999/host/slave-01/```

while access via reverse proxy would work fine like that:

```https://master.example.com/host/slave-01/```

##### Expected behavior

I would like to be able to set a 'prefix' to generate those links, so that the Netdata Port does not need be accessible directly by external Networks, while still being able to control Access to the Dashboard with a reverse proxy. That way the Netdata port can be shielded by its own network or firewall rules.

**Comment by prologic** [comment]
Hi @RealKelsar ; Apologies for the late reply to your issue.

Can you help me understand what you mean by:

> I would like to be able to set a 'prefix' to generate those links

I understand mostly the gist of the rest of what you're saying but not this "prefix" bit and link generation?

**Comment by RealKelsar** [comment]
Hi @prologic,
I think I meant to make the whole Host + URL Part configurable, like beeing able to define the dashboard would be reachable via this Host and Path, while Netdata itself does not need that.

Basically i called it Prefix because it would prefix the Netdata internal URLs, like if the Netdata Master itself would be

````
http://master.example.com:19999/host/slave-01/
````

With a 'prefix'([]) it could be:

````
[https://webserver.example.com/netdata]/host/slave-01/
```

I hope I made it more clear.

**Comment by prologic** [comment]
Thanks @thiagoftsm and @underhood for taking this on! My intention was to go through old outstanding issues we haven't responded to yet and get on top of them :)

Thanks @RealKelsar for the updated explanation :)

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
