### ISSUE TITLE
smartd_log.chart.py - wrong setting in reallocated sectors count

### ISSUE THREAD

**Issue by Stoatwblr** [netdata/netdata#7383]
Lines 263-268:

    'reallocated_sectors_count': {
        'options': [None, 'Reallocated Sectors Count', 'sectors', 'wear', 'smartd_log.reallocated_sectors_count',
                    'line'],
        'lines': [],
        'attrs': [ATTR5],
        'algo': INCREMENTAL,
    },

The algo here should be ABSOLUTE, not INCREMENTAL.

As it stands, the chart simply blips as a block is reallocated instead of stepping

**Comment by ilyam8** [comment]
@Stoatwblr hi, i agree, are you willing to make a PR?

**Comment by ilyam8** [comment]
Ok, i made the PR

**Comment by Stoatwblr** [comment]
Sorry, I was otherwise engaged. There are a few other entries which need fixing too.

Most of the "INCREMENTAL" entries should be looked at closely, however the important ones are:

read_total_err_corrected
read_total_unc_errors
write_total_err_corrected
write_total_unc_errors
verify_total_err_corrected
verify_total_unc_errors

spin_up_retries
calibration_retries
reallocated_sectors_count
program_fail_count
erase_fail_count
reallocation_event_count

When monitoring drives, it's easy to miss blips and what really matters is the _total_ health numbers over time (It's worth reading the smart attribute tables for explanations of each item)

If these traces sit at zero it's far too easy to get a false sense of security

**Comment by ilyam8** [comment]
Smartd numbers is a big source of confusion to me, sometimes we need raw value, sometimes we need normilized. Sometimes we need to decode value, sometimes we dont. And on top of that the stuff is vendor specific 😓 

@Stoatwblr so all those attributes from your post should be `absolute`? What about we add both?

cc @Ferroin

**Comment by Stoatwblr** [comment]
Normalised is almost always a health issue, and vendor-specific is a nightmare all by itself - I spent weeks decoding a few sata-dom maker formats and submitting them a while back.

I've got no objection to "both", but that raises the question of how to represent them. Some of my systems have 200+ drives on them and the ZFS test rig I'm using has 32.

At the moment I believe all the entries listed should be absolute. Keeping them as incrementals is only going to give you transition events and that's really less useful on an "old age" or "prefail" counter than tracking the absolutes.

https://en.wikipedia.org/wiki/S.M.A.R.T. has a pretty good summary of everything

**Comment by Stoatwblr** [comment]
I'd say that multizon error rate should be include too - this is a direct indicator of the machanical condition of the drive (high raw number  == bad)

In all cases for things like sectors reallocated and suchlike,  whilst the raw numbers are useful when doing diagnostics the health numbers (the normalised ones) are what counts: one drive might have 10,000 reallocated sectors/block and have 500,000 spare whilst another might run out of spares at 500 reallocated. 

It's very much a case of using the value (countdown) towards threshold to determine imminent failure - but of course a rapid increase in the raw numbers (or decrease in the normalised value) is also a warning sign of trouble - I won't keep a drive online that started developing a few tens of pending bad sectors every week even if it's notionally "OK", because it's clearly on a failure path and more importantly because it's going to hang for long periods trying to read marginal sectors (pending sectors are marginals. They can't be reallocated/spared/declared OK(*) until overwritten and every time the drive attempts to read the same sector it's going to have the same issue.)

(*) A marginal sector might have been due to vibration or a high fly write - or because someone shouted at the drive: https://www.youtube.com/watch?v=tDacjrSCeq4

**Comment by Stoatwblr** [comment]
There's also the question of how you extract things like temperature - for example "smartctl -l scttemp" (vs scttempsts or scttsmphist)  can tell you not only the temperature of the drive, but also its recommended and warranty-busting limits, along with historical max/min

**Comment by ilyam8** [comment]
@Stoatwblr have you checked the code

https://github.com/netdata/netdata/blob/34a7b8ad0a992f1f764ea38eacdb6edd44ce2885/collectors/python.d.plugin/smartd_log/smartd_log.chart.py#L496-L515

Do we use correct logic for collected attributes? What do you think? I see you have spend some time on understanding smart values 😄 

I know that current implementation is not good but i have not expertise/knowledge to make it better. It would be nice if you could help.

**Comment by ilyam8** [comment]
> There's also the question of how you extract things like temperature 

We read smartd logs, if something is encoded in a raw value we can extract it. If it is not, we cant.

**Comment by ilyam8** [comment]
About the issue

> smartd_log.chart.py - wrong setting in reallocated sectors count

It will be fixed after #7384 is merged. I will open a new one from your post
https://github.com/netdata/netdata/issues/7383#issuecomment-559598122
