### ISSUE TITLE
Missing users on the users tab

### ISSUE THREAD

**Issue by larsomen** [netdata/netdata#7386]
#### Question summary
Missing users on the users tab.

We are in the middle of migrating from directadmin to plesk hosting servers. Our directadmin servers show the CPU usage etc from every customer of ours, which if very helpfull to diagnose which customer of ours is causing high load on the server. On our new servers they just don't show up sadly. The only users that do show on the graphs are "netdata" and "root". When i check the running processes with htop the php-fpm processes of the websites of our clients do show up with the correct user that belongs to that website, so i don't get why netdata won't show these users/processes.

##### OS / Environment
Centos 7
CloudLinux 7.7
Plesk ObsidianVersion 18.0.21 Update #3

**Comment by vlvkobal** [comment]
Do you run Netdata in a container?

**Comment by larsomen** [comment]
As far as i know i don't. I just installed it on the server as the root user with the command "bash <(curl -Ss https://my-netdata.io/kickstart.sh)". Is there a way i could check to be sure?

It does see a couple of LVE containers from cloudlinux by default though. I believe this is detected via the cgroups plugin? I disabled it on one of the plesk servers via the netdata config because we would get a lot of alerts of websites inside these containers that where hitting ram limits etc.

**Comment by vlvkobal** [comment]
`kickstart.sh` installs Netdata as a service. You can check if Netdata is running as a process using the `ps ax | grep netdata` command. You should see something like this
```
 216658 ?        Ssl    0:24 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
 216702 ?        S      0:31 /usr/libexec/netdata/plugins.d/apps.plugin 1
 216704 ?        Sl     0:01 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 216705 ?        Sl     0:01 /usr/libexec/netdata/plugins.d/go.d.plugin 1
```

Yes, containers are detected by cgroups plugin.

Do you have all the statistics in place for the "Application" and "User Groups" sections?

Please also check if you have set "All" for the "Which dimensions to show?" option in the "Settings" menu.

**Comment by larsomen** [comment]
> `kickstart.sh` installs Netdata as a service. You can check if Netdata is running as a process using the `ps ax | grep netdata` command. You should see something like this
> 
> ```
>  216658 ?        Ssl    0:24 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
>  216702 ?        S      0:31 /usr/libexec/netdata/plugins.d/apps.plugin 1
>  216704 ?        Sl     0:01 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
>  216705 ?        Sl     0:01 /usr/libexec/netdata/plugins.d/go.d.plugin 1
> ```
> 
> Yes, containers are detected by cgroups plugin.
> 
> Do you have all the statistics in place for the "Application" and "User Groups" sections?
> 
> Please also check if you have set "All" for the "Which dimensions to show?" option in the "Settings" menu.

I get the following output so seems to be alright.

>  254984 ?        Ssl   21:23 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
 255100 ?        Sl     0:31 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 255106 ?        Sl     1:34 /usr/libexec/netdata/plugins.d/go.d.plugin 1
 796478 ?        S      0:22 /usr/libexec/netdata/plugins.d/apps.plugin 1
 850767 ?        S      0:03 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
 864139 pts/0    S+     0:00 grep --color=auto netdata

And what do you mean by "Do you have all the statistics in place for the "Application" and "User Groups" sections?"?

The "which dimensions to show" option is on All but it still only displays netdata and root as users.

**Comment by vlvkobal** [comment]
> And what do you mean by "Do you have all the statistics in place for the "Application" and "User Groups" sections?"?

Could you show what dimensions you have in the `apps.processes` chart?
![image](https://user-images.githubusercontent.com/22008543/69875629-48a7c300-12c6-11ea-88eb-b7ee6a547455.png)

**Comment by larsomen** [comment]
![image](https://user-images.githubusercontent.com/6460114/69878193-81df3380-12c4-11ea-94bb-92bcbfe17f07.png)

**Comment by vlvkobal** [comment]
I asked for the "Application" section, not for the "Users".
