### ISSUE TITLE
Pausing displaying charts

### ISSUE THREAD

**Issue by JohnnyBee2** [netdata/netdata#7389]
Hi,
I love netdata.

Recently (I don't know exactly when) netdata stops displaying charts as in the screenshot.

![netdata2](https://user-images.githubusercontent.com/22611765/69869362-eb534800-12ac-11ea-931f-3ca4684229c4.jpg)

Charts appear after about 1.5 minutes. They work for some time and are stopped again .....
In browser debugging mode I get a lot of status (pending).

![debug2](https://user-images.githubusercontent.com/22611765/69869432-23f32180-12ad-11ea-955f-ce80a236459e.jpg)

Best regards and please help.

Browsers: Firefox, Chrome, Opera, Vivaldi (latest versions).
NETDATA:
New installation on the new CentOS (8 cores 8GB)
- One-line installation
- Linux 64bit pre-built static binary,
- Install Netdata on Linux manually
v1.19.0-8-g34a7b8a (previous also)
- netdata dasboard options : refresh - always

**Comment by mfundul** [comment]
Can you check your error log? It's probably in `/var/log/netdata/error.log`.
