### ISSUE TITLE
cgroups.plugin should parse for podman containers

### ISSUE THREAD

**Issue by Komic** [netdata/netdata#7391]
Before [Podman](https://podman.io/) inevitably replaces Docker as the standard for containers, netdata's cgroups plugin should be able to parse container names. The `podman ps` command [behaves pretty much just like Docker's](https://www.mankier.com/1/podman-ps).
There might be other stuff in netdata about this compatibility I'm forgetting about.

Related to https://github.com/netdata/netdata/issues/4868

**Comment by K900** [comment]
I've experimented with this a bit, and there seems to be an inherent permissions issue with Podman and Netdata - only the user who started the container can access it via `podman ps`, and only root can access the API socket. This basically means that Netdata has to run as root to get meaningful container names, which is unfortunate.

I've got a script working here: https://github.com/K900/netdata/commit/94ffb4817856a91ce12fb0e2dea52506e43e0346

But again, this will not function unless Netdata runs as root.

**Comment by ilyam8** [comment]
just thinking out loud - it sounds like we need _name resolution_ as an external plugin/service? 🤔

**Comment by K900** [comment]
Technically, container name resolution already _is_ an external service, it's just running on a restricted Unix socket. I actually managed to get around it on my machine by doing the docker-socket-proxy dance recommended in the docs for running Netdata itself in Docker, except binding the proxy to a local port and then pointing `PODMAN_HOST` to that (with my changes applied).

@ilyam8 would you be interested in pulling my changes for the time being? They don't hurt anything, and at least Netdata will work for anyone who wants to do the socket dance. I'd be willing to write up a documentation page for that too.

**Comment by ilyam8** [comment]
i meant some thing that we can setcap (linux) or something to avoid running nd from root user or something like that. nd would be just query that name resolution thing.


> would you be interested in pulling my changes for the time being?

Feel free to make a PR, will see.

> I'd be willing to write up a documentation page for that too.

👍

**Comment by K900** [comment]
That would have to be `setuid` then and not `setcap` - Podman's rootful socket is `root:root 0600`.

**Comment by Komic** [comment]
Hi, I was finally able to try this out, I'm afraid this still isn't working as intended. Netdata is now displaying the 12-chars container ID, not their names. I can confirm it's able to read podman's socket. Podman v2.0.0 also shipped with a REST API, which may be relevant.

**Comment by Komic** [comment]
@prologic should this be reopened, or would you rather track this in a separate issue?

**Comment by ilyam8** [comment]
@Komic i think a separate issue is better
