### ISSUE TITLE
What data, if any, is sent/collected when using the nodes view?

### ISSUE THREAD

**Issue by ZacharySalim** [netdata/netdata#7396]
I am curious if any information about the machines I want to monitor with netdata is collected or sent when I sign in to use the nodes view? I would like to use netdata to monitor multiple machines at my company, but security comes first. We need to have all data regarding these machines remain local in the network.

I guess a secondary question is why is an account necessary to view multiple machines in the nodes view?

**Comment by cakrit** [comment]
Custom dashboards showing charts from multiple hosts have always been possible. That's not what we're doing with cloud though. What you see right now in the nodes view is a very small glimpse into [our plans](https://blog.netdata.cloud/posts/netdata-cloud-announcement/).

Netdata cloud will be receiving a lot of data from each agent, when used. It's a cloud-based monitoring offering. An on-premise version will also be available, to paying customers (early adopters will of course have some benefits. You can express interest in the on-premise version, by emailing info@netdata.cloud). 

Of course, no one needs to use the nodes view if they don't want to/their security policies prevent them from doing it. I hope I have answered your questions.

**Comment by ZacharySalim** [comment]
That does answer my question. I have a follow up question. I have combed through the setup documentation and I am a bit confused on how to achieve my desired configuration. I ma looking to have multiple (around 20) machines send all of the data to a database residing on one machine. I want that machine to display all of this info on a custom dashboard. Also, to make this easily deploy able I am installing Netdata from the .run files provided in releases. Is there a more specific guide I can follow to achieve this? My efforts so far have only ended up in errors from the machines trying to connect.

**Comment by ilyam8** [comment]
Hi @ZacharySalim 

Wiki is a good place to start

> https://docs.netdata.cloud/streaming/

Custom dashboard

> https://docs.netdata.cloud/web/gui/custom/#configure-dash
