### ISSUE TITLE
Monitor nginx docker container

### ISSUE THREAD

**Issue by MSaadatt** [netdata/netdata#7397]
Hi,
How can I monitor nginx in docker container with netdata?

**Comment by ilyam8** [comment]
Hi @MSaadatt 
Yes, it is possible. See

https://github.com/netdata/netdata/blob/556aa2769a1a2f63b7a235e946460715a24001fb/collectors/python.d.plugin/nginx/nginx.conf#L100-L102


You can any number of jobs there.
