### ISSUE TITLE
Enabler: Internal netdata labels

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7400]
- [ ] The following will be default internal labels (not exported to third party systems, unless explicitly requested by users):

|Description|api/v1/info|Label Name|
|---|---|---|
|OS name|os_name|_os_name|
|OS version| os_version|_os_version|
|Kernel version|kernel_version|_kernel_version|
|Architecture|architecture|_architecture|
|Virtualization|virtualization|_virtualization|
|Container Tech|container|_container|

- [ ] For streaming, we should also have default labels specifying if a host is a master  (has metrics streamed to it) and/or a slave (streams metrics to another host).
    - _is_master=[true/false]
    - _is_slave=[true/false] AND/OR _streams_to=[master host, as defined in stream.conf]

**Comment by thiagoftsm** [comment]
Hi @cakrit,

I think we do not need the `_is_slave=[true/false]` the `_stream_to` already carries this information implicit and it also carries an additional information.

**Comment by cakrit** [comment]
> Hi @cakrit,
> 
> I think we do not need the `_is_slave=[true/false]` the `_stream_to` already carries this information implicit and it also carries an additional information.

You may be right, we'll close this in tech. refinement in a few hours (I was going to say tomorrow, but it's tomorrow only for me :)

**Comment by thiagoftsm** [comment]
All right!

Case we consider "only" timezone I agree 100%! :D

**Comment by vlvkobal** [comment]
Closed in #7485
