### ISSUE TITLE
Inform users about telemetry and how to opt-out

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7401]
Indicate in all installers before the Enter/yes-no: "Anonymous statistics will be [enabled/disabled]", according to the provided option. Provide information on the option relevant to the specific installer, to opt-out:

- [x] netdata-installer.sh
- [x] kickstart.sh 
- [x] kickstart-static64.sh
- [ ] binary packages (not sure about this one)

For docker images:

- [x] Add a `DO_NOT_TRACK` env var which when set will disable the anonymous stat pings.
- [x] Document the env var

Related: https://github.com/netdata/netdata/issues/7404#event-2848554127

**Comment by ncmans** [comment]
@cakrit I see you wrote:

> We will plan the implementation of the suggested measures (other than opting-in) as soon as possible.

 in https://github.com/netdata/netdata/issues/7366#issuecomment-560551829

Does that make this high priority? cc @cosmix

**Comment by sneak** [comment]
The statistics collected are not and can not be anonymous, so by claiming this, you would be making a false statement to your users. I suggest making the copy clear about the fact that the software will *not* use an anonymous method to submit the data.

**Comment by amoss** [comment]
@sneak the information provided by Google describing their anonymous IP collection is here: https://support.google.com/analytics/answer/2763052?hl=en.

**Comment by sneak** [comment]
What google does or does not do with the data is irrelevant. The data that is transmitted is not anonymous nor is it transmitted anonymously. 

It is also received by more parties than just Google.

**Comment by cakrit** [comment]
> @cakrit I see you wrote:
> 
> > We will plan the implementation of the suggested measures (other than opting-in) as soon as possible.
> 
> in [#7366 (comment)](https://github.com/netdata/netdata/issues/7366#issuecomment-560551829)
> 
> Does that make this high priority? cc @cosmix

Yes, this is high priority. We did fill the next sprint with critical priority items, but if there's any capacity from anyone, we want to progress the other items as well.

**Comment by ncmans** [comment]
@cakrit kickstart scripts already prompt dozen times for installing various OS packages if `--dont-wait` or `--non-interactive` options aren't set. Should stat collection be another question we ask interactively when running kickstarts?
