### ISSUE TITLE
Show key installer options in www.netdata.cloud "installation"

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7402]
Add options  auto-updates:on/off, stable/nightly, anonymous statistics (on/off) and accordingly generate the correct kickstart.sh command in https://www.netdata/cloud section installation.
The exact texts are negotiable, whatever makes sense.

**Comment by cakrit** [comment]
@joelhans let's add this request to the RFC for updates to our website.

**Comment by joelhans** [comment]
This functionality is now live on the site: https://www.netdata.cloud/#installation

Closing this issue.
