### ISSUE TITLE
Improve documentation of opting out of telemetry

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7403]
In docs, we'll make the installation options more prominent: 
- packaging/installer/README.md - Show more prominently the options for telemetry, auto-updates, stable/nightly. 
- Show additional opt-out possibilities in https://github.com/netdata/netdata/blob/master/docs/netdata-security.md#opt-out-of-anonymous-statistics and https://github.com/netdata/netdata/blob/master/docs/anonymous-statistics.md#opt-out

**Comment by joelhans** [comment]
I'll start working on this today.
