### ISSUE TITLE
Script to pull kubernetes labels from pod API

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7411]
* Extract the part of `cgroup-names.sh` that accesses the pod API.
* Extract the checks that guard execution only if inside a pod.
* Extend to extract the user-defined labels from the data returned from the API.
* Make this work in the initial environment of the agent (i.e. `exec()` the script before threads are spawned in the daemon).
* Check performance of this approach and that it does not slow down agent startup.
* Ensure this also works if called from a thread in the agent (to support reloading changes).
* Create a linked list using the struct from #7408 but do not attempt to link it into RRDHOST.

Some information about Kubernetes labels is available at https://www.replex.io/blog/9-best-practices-and-examples-for-working-with-kubernetes-labels.
There is some similar recent work in: https://github.com/netdata/netdata/pull/7416

**Comment by stelfrag** [comment]
Super !!

I put comments in #7410 that cover things for this issue as well

**Comment by cakrit** [comment]
This almost 100% with #7453, will need to incorporate Thiago's validation and need a little help to see how I can process the script exit code, to handle failures differently.

**Comment by amoss** [comment]
It looks like issues are not getting auto-closed by ZenHub when the PRs are merged - I'm leaving it open incase you want to want to tweak it otherwise please close.

Let's talk about the complexity estimate vs the result in the Sprint Review, it's a good task to use as an example. Something to cover is how much of the complexity estimate came from lack of knowledge on kubernetes / estimating difficulty in finding the information. Obviously you chewed through in a few hours so one part to discuss is did the team over-estimate the complexity or did you have enough background knowledge to collapse it to something simpler. This discussion can help with identifying base-line task sizes for story points.

**Comment by cakrit** [comment]
> It looks like issues are not getting auto-closed by ZenHub when the PRs are merged - I'm leaving it open incase you want to want to tweak it otherwise please close.

Yes, I'd like to improve what I mentioned in https://github.com/netdata/netdata/issues/7411#issuecomment-562494038 
If I wanted the issue to be auto-closed, I would have written `fixes #7411` in the PR.

**Comment by amoss** [comment]
Completed and merged.
