### ISSUE TITLE
Merge config-file labels and kubernetes into the RRDHOST.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7412]
* Merge the two linked lists, so that user-defined labels take precedence over the kubernetes labels.
* Acquire the lock in RRDHOST.
* Replace the old list.
* Release the lock and clean up the old list.

**Comment by mfundul** [comment]
It should probably be a new lock, cause this lock is being called at a potentially higher level for readers, for a different purpose. It can lead to deadlocks or priority inversion. It's not straightforward to use the host lock.

**Comment by cakrit** [comment]
> It should probably be a new lock, cause this lock is being called at a potentially higher level for readers, for a different purpose. It can lead to deadlocks or priority inversion. It's not straightforward to use the host lock.

We are changing the host structure, so we lock the host. I don't get the comments at all.

**Comment by cakrit** [comment]
> > It should probably be a new lock, cause this lock is being called at a potentially higher level for readers, for a different purpose. It can lead to deadlocks or priority inversion. It's not straightforward to use the host lock.
> 
> We are changing the host structure, so we lock the host. I don't get the comment at all.

Never mind, I see it was changed to a label only lock, which makes sense.

**Comment by amoss** [comment]
Not sure why the PR didn't autoclose...
