### ISSUE TITLE
Initiate the Agent-Cloud-Link

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7413]
When the agent is in a claimed state:

* Periodic timer to check the status of the ACL.
* If the agent is claimed and the link is not operational set up the wss + MQTT transport layer.

This will require:
* Including the libmosquito library as a dependency, sync with the SRE team.
* Add a heartbeat.
* Add error-checking.
* Tuning the connection parameters (timeouts) to be added to config.

Demo against a standard broker (VerneMq?)

**Comment by stelfrag** [comment]
#### Update

- A new thread is created to check for the mqtt_state (agent_cloud link)
  - Check to see if agent is in claimed state
  - Try to establish connection to the cloud 
     - Reads parameters (hostname, port)  from a new [mqtt] section in netdata.conf
     - Setup PING every 60 seconds (default)
- Uses MQTT Protocol version 5.0
- Setup sample subscription to a topic
  - Setup of a message callback to take action on received messages
- Assumes generic function to establish base_topic communication to the cloud (TBD)
- Periodic check for connection reinit if needed
- Check for graceful shutdown of connection (Needs more work)
- Test standard connection on localhost (mosquitto broker)
- Test standard connection on VerneMQ (docker setup)

**Comment by amoss** [comment]
[WIP] pull requests are appreciated :)

**Comment by stelfrag** [comment]
##### Update
- The libmosquitto library could not be used to upgrade the connection to wss
- Attempted to switch and use the libpaho library
  - Was able to use mqtt over websockets
  - Was able to use mqtt over SSL
  - Was not to use mqtt over secure websockets (seems like an issue with the libpaho C library)

##### Next steps
- Close this issue, will open a new one to focus solely on investigating the wss upgrade
- Post a comment on the libpaho project page asking about an issue that's being worked on and may resolve the failure to upgrade to secure websockets
- Focus again on the libmosquitto -- post a Q on the project for assistance (if there is a way to upgrade to wss)
