### ISSUE TITLE
How to install a plugin? (smartd_log)

### ISSUE THREAD

**Issue by David-Lor** [netdata/netdata#7415]
Reading the [documentation](https://github.com/netdata/netdata/blob/master/docs/Add-more-charts-to-netdata.md) regarding adding more charts to netdata, it does not specifically mention how  plugins can be installed and activated on Netdata.

Specifically I am interested on the [smartd_log](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/smartd_log) plugin, but neither the [plugin readme](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/smartd_log), nor the [section](https://github.com/netdata/netdata/blob/master/docs/Add-more-charts-to-netdata.md#sensors) where the plugin is displayed, have information regarding how to install & activate it.

**Comment by ilyam8** [comment]
Hi @David-Lor 

It is enabled by deafault, it reads `smartd` log files. See

https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/smartd_log#prerequisite

**Comment by ilyam8** [comment]
I see it expects to find logs in 

https://github.com/netdata/netdata/blob/a2b0c9c702264de9d7039c2edc809bf37111096e/collectors/python.d.plugin/smartd_log/smartd_log.chart.py#L25

If it is not correct dir in your case (which is likely) you need to manually set it in the module configuration file

https://github.com/netdata/netdata/blob/a2b0c9c702264de9d7039c2edc809bf37111096e/collectors/python.d.plugin/smartd_log/smartd_log.conf#L64

**Comment by David-Lor** [comment]
@ilyam8 all right, everything is fine! Tried changing the `/etc/default/smartmontools` with the line described on the README section on the plugin, and it's showing the stats now!

I assumed they required manual installation since in the documentation these plugins are described as "available external plugins".

Regards and thanks! closing the issue.

**Comment by ilyam8** [comment]
@joelhans ^^ take a look, probably we need to make it clear

**Comment by joelhans** [comment]
@ilyam8 Definitely. It's a huge project, but I do want to overhaul the entire collectors docs to make a lot of this clearer. Adding it to the backlog.
