### ISSUE TITLE
Route does not exist upon logging in by email

### ISSUE THREAD

**Issue by VLegakis** [netdata/netdata#7424]
This issue has been verified by @cakrit as happening also to Chrome (apart from the initial reporter's IE browser)

https://netdata.cloud/account/#error=token+expired&method=passwordless redirects to www.netdata.cloud/account...

![Screenshot 2019-11-28 at 16 10 04-fs8 copy](https://user-images.githubusercontent.com/861415/70159617-e08c1f00-16c1-11ea-95af-0d5bf447b6b2.png)

**Comment by ilyam8** [comment]
What is this browser? 🤔

**Comment by nicolasparada** [comment]
Uhmm... Needs triage, but as input, know that:
https://netdata.cloud/account/sign-in-agent
And
https://www.netdata.cloud/account/sign-in-agent
Are different and the second one doesn't work (notice the `www.`).

Tho, this might not really be the issue here, but the fact that the `sign-in-agent` part is being removed from the URL path.
Only `/account/` instead of `/account/sign-in-agent`.

So far, cannot replicate.

**Comment by cakrit** [comment]
> Uhmm... Needs triage, but as input, know that:
> https://netdata.cloud/account/sign-in-agent
> And
> https://www.netdata.cloud/account/sign-in-agent
> Are different and the second one doesn't work (notice the `www.`).
> 
> Tho, this might not really be the issue here, but the fact that the `sign-in-agent` part is being removed from the URL path.
> Only `/account/` instead of `/account/sign-in-agent`.
> 
> So far, cannot replicate. For starters, IE doesn't run our javascript. And Chrome works just fine.

@nicolasparada have you tried with an expired token? The OP states that it's https://netdata.cloud/account/#error=token+expired&method=passwordless that has the issue

**Comment by nicolasparada** [comment]
On Chrome it works fine. It goes to the sign-in page and a snackbar shows the error there "token expired".
On IE the page is blank because our JavaScript doesn't run on IE.

**Comment by cakrit** [comment]
This is chrome:

![image](https://user-images.githubusercontent.com/43294513/70320786-72874b00-17da-11ea-9d68-061d266300ee.png)

**Comment by nicolasparada** [comment]
Yeah, that page does not exists (so it redirects to the netlify `www.` site).
We need to determine how is that you get into `/account/` instead of `/account/sign-in-agent`.

**Comment by nicolasparada** [comment]
Whoever can replicate, you could tell me the full URL you are visiting when you are presented with the form to login with email (`https://netdata.cloud/account/sign-in-agent`).
And inspect the devtools network panel and tell me the request body made to `POST https://netdata.cloud/api/v1/auth/send-magic-link`. I'm interested in the `redirectURI` field there.

**Comment by nicolasparada** [comment]
Reopening since the fix is not yet deployed.

**Comment by nicolasparada** [comment]
All right. Fix already deployed 🎉
