### ISSUE TITLE
Streaming : Can I display total KPI from N x Slaves on Master Dashboard

### ISSUE THREAD

**Issue by AidanMcP** [netdata/netdata#7426]
#### Question summary

Hi folks, Apologies in advance for another newbie question, but I've searched online and can't find a definitive answer.  I've setup Netdata on a number of hosts, and am sending KPIs to Netdata via Statsd (after some much appreciated guidance here - #7212 )

All good, but my next step is to look towards Streaming my metrics to a central location. I've not done this yet, but wiki steps look useful.  I understand I'll see a drop-down for *each* slave host, but it there a way I can display metrics summed from all hosts?

Simple example would be if each host sends me a TPS figure, is there a simple way I could see a head-line TPS for my entire deployment.

I appreciate I could achieve this with Prometheus, but I'd be surprised if I couldn't get this from Netdata? 

Thanks in advance,
Aidan

**Comment by thiagoftsm** [comment]
Hi @AidanMcP ,

> l. I understand I'll see a drop-down for each slave host, but it there a way I can display metrics summed from all hosts?

Netdata allows users to have custom dashboards https://docs.netdata.cloud/web/gui/custom/ , I think this is what you wanna do,  you will see inside this link an example of how to display the same chart from different hosts.

Best regards!

**Comment by AidanMcP** [comment]
Thanks @thiagoftsm - much appreciated.
I'd been looking in the Streaming section - that helps a lot. Looks good.
