### ISSUE TITLE
ERROR: PLUGINSD: /usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin : read fail ed.

### ISSUE THREAD

**Issue by ujmoser** [netdata/netdata#7429]
#### netdata reports plugin load errors at startup

I installed netdata on my Ubuntu Server 18.08.3. When I start netdata it complains about not being able to read from pyyaml2 (see log snippet)

```
 Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin", line 31, in <module>
    from bases.loaders import ModuleAndConfigLoader
  File "/usr/lib/x86_64-linux-gnu/netdata/python.d/python_modules/bases/loaders.py", line 15, in <module>
    from pyyaml2 import SafeLoader as YamlSafeLoader
ImportError: No module named pyyaml2
2019-12-04 20:46:50: netdata ERROR: PLUGINSD: /usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin : read fail
ed.
2019-12-04 20:46:50: netdata ERROR: PLUGINSD: plugin '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin' di
sconnected.
2019-12-04 20:46:50: netdata INFO : PLUGINSD: '/usr/lib/x86_64-linux-gnu/netdata/plugins.d/python.d.plugin' on pid 74
38 stopped after 0 successful data collections (ENDs).
```
As a result it does not load additional servers from my mysql.conf.

**Comment by ilyam8** [comment]
@ujmoser hey

i suggest to uninstall using `apt-get` and install it from source, see netdata docs

**Comment by ilyam8** [comment]
@ujmoser feel free to comment if the issue is not solved

**Comment by ujmoser** [comment]
I tried the install from source as can be found in in the netdata docs but could not get the mysql sensors configured. I assumed that I need the mysql.conf in /etc/netdata/python.d/ directory and mysql=force enabled in python.d.conf. I configured my remote servers that I want to monitor in mysql.conf and successfully tested the connection for user netdata using the mysql cli.

So I tried again with a fresh install of Ubuntu 18.04.3 upgraded all packages and installed netdata from the Ubuntu repos. In this case I got the same error but complaning about pyyaml3. So I installed pyyaml3 and then netdata complained again about pyyaml2. So I searched for pyyaml2 on the net and on PyPI but I only find PyYAML 5.2 (https://pypi.org/search/?q=pyyaml2&o=). Seems like some components already use Python3 and others still use Python2. IMHO it would make sense to have all modules on the same Python version.

BTW since mysql monitoring in charts.d is deprecated it should be removed because it clutters the error.log with lots of useless messages.

**Comment by ilyam8** [comment]
You dont need to install `pyyaml` because we vendor it

> https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/python_modules

If for some reason there is no vendored yaml pkgs we python.d.plugin tries to load `yaml`

https://github.com/netdata/netdata/blob/8260af09934d9b0dc0b5944b18fe0dd0ac60d831/collectors/python.d.plugin/python_modules/bases/loaders.py#L11-L17

___

See

https://packages.ubuntu.com/search?keywords=netdata&searchon=names&suite=bionic&section=all

netdata `1.9.0`, it is ancient, currecnt version is `1.19.0`

That is why i suggested to uninstall it.

Install guide:

> https://docs.netdata.cloud/packaging/installer/

___

> BTW since mysql monitoring in charts.d is deprecated it should be removed because it clutters the error.log with lots of useless messages.

It is one line

> 2019-12-08 13:13:00: charts.d: INFO: mysql: is disabled. Add a line with mysql=force in '/opt/netdata/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).

**Comment by ilyam8** [comment]
> IMHO it would make sense to have all modules on the same Python version.

That is how it is. 

Lets start from unistalling netdata from ubuntu repos and installing current version. 

Then we debug your problem with `mysql`.

**Comment by ujmoser** [comment]
Finally managed to set it up after installation from source and to get data from my cluster nodes.
