### ISSUE TITLE
Clarify meaning of asterisk and question marks on Netdata distribution support matrix

### ISSUE THREAD

**Issue by ncmans** [netdata/netdata#7432]
The two tables in question:
* https://docs.netdata.cloud/packaging/distributions/#amd64-architecture
* https://docs.netdata.cloud/packaging/distributions/#x86-architecture

1. What is the meaning of question mark against a distro? Either define it or replace them with ✗ and N/A which are clearly understood.

2. What is the meaning of the asterisk against CentOS and RHEL distros? A footnote at the bottom of the table linked to the asterisk is useful.

**Comment by thiagoftsm** [comment]
> What is the meaning of question mark against a distro? Either define it or replace them with ✗ and N/A which are clearly understood.

RHEL has subversion,  so the meaning is we are supporting all 7.X versions, the same thing happens with CentOS, that has the latest 7.X is `CentOS Linux release 7.7.1908`

**Comment by ncmans** [comment]
Oh! I'm so used to seeing `X` that the asterisk completely threw me off.

**Comment by ncmans** [comment]
> > What is the meaning of question mark against a distro? Either define it or replace them with ✗ and N/A which are clearly understood.
> 
> RHEL has subversion, so the meaning is we are supporting all 7.X versions, the same thing happens with CentOS, that has the latest 7.X is `CentOS Linux release 7.7.1908`

I assume you're talking about the asterisk (e.g. `6.*`) and not the question mark.

**Comment by thiagoftsm** [comment]
Yes, the question mark is something that I cannot understand either, it looks like that this was not set yet, but it could be.
