### ISSUE TITLE
Netdata service keeps stopping on Ubuntu 14.04

### ISSUE THREAD

**Issue by sebszocinski** [netdata/netdata#7433]
This might be a basic question but i've checked the issues and docs and can't seem to find any solution. 

I have Netdata installed and running fine on two Ubuntu 16 and 18 servers but on my other two 14.04 servers the service seems to keep stopping or crashing? I have to SSH in and run `service netdata start` to bring it back up again. I can't seem to see anything in the logs either.

Any help would be great!

**Comment by cakrit** [comment]
Hi @sebszocinski, we really need to see what you have in your `error.log` right before the crashes. It's usually located at `/var/log/netdata/error.log`. We have other similar reports and haven't been able to replicate it yet. Also please tell us which version you're using.

**Comment by sebszocinski** [comment]
Hi @cakrit no worries, happy to share this but don't want to make it public as it lists some client data, can I share it another way? ie via email?

**Comment by cakrit** [comment]
email it to support@netdata.cloud please. 
Also, can you see if your issue is similar at all to the one mentioned in #7440? The `lsof` command results indicate that perhaps there's an issue with the dbengine.

**Comment by mfundul** [comment]
@sebszocinski can you disable log flood protection cause I'm missing a lot of logs, by setting `errors flood protection period` to `0` in the [configuration](https://github.com/netdata/netdata/tree/master/daemon/config#global-section-options)?

**Comment by sebszocinski** [comment]
hey @mfundul - okay done. I will report back with a new log file after it crashes next.
