### ISSUE TITLE
Netdata DB collectors 

### ISSUE THREAD

**Issue by GPGithelp** [netdata/netdata#7443]
Can we have a quick setup guide, step by step to setup DB collectors.
Unfortunately we are all not python literate. 

I'm trying to setup a collector for Oracle and MySQL. did upgrade the python version, installed cx_oracle and added the oracledb.conf file with connection details.
Somewhere I'm missing config as I cannot see the Databases not the charts.
In the documentation some links show "error" or "page not found"

There must be an easier way for the novice to install and use this tool.

Thanks.
Regards,
GP.

**Comment by ilyam8** [comment]
Hi @GPGithelp 

Please do as `netdata` user

> ./python.d.plugin debug mysql

> ./python.d.plugin debug oracle

**Comment by ilyam8** [comment]
> In the documentation some links show "error" or "page not found"

could you point to these doc pages with broken links?

**Comment by OdysLam** [comment]
Hey @GPGithelp,

While helping a colleague, I put together a short guide for setting up netdata with a web-server (nginx, mariadb, php-fpm).

Feel free to take a look, it might prove useful:
https://www.notion.so/odyslamtzidis/Netdata-guide-for-Production-Web-Server-Nginx-PHP-fpm-MariaDB-f17397f9c8524765bb06adec59aa2087

Cheers :)
