### ISSUE TITLE
netdata fails to build without libuv

### ISSUE THREAD

**Issue by csch42** [netdata/netdata#7445]
##### Bug report summary

As of _today_ netdata fails building on numerous platforms without _libuv_ installed.

##### OS / Environment

Linux, Debian Stretch / Wheezy for MIPS / MIPSEL architecture

##### Netdata version (ouput of `netdata -V`)

Latest pull as of ~ 5. Dec. 2019, 15:00 UTC

##### Component Name

libuv (possibly libjudy as well?)

##### Steps To Reproduce

invoke _netdata-installer.sh_ → "configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'."

##### Comments

It looks like libuv and/or judy were previously built locally if not present - with the added benefit, that both were included _statically_ into the binary (big feature for deploying netdata on "embedded Linux" devices). This appears to no longer be the case.

I did a _git pull_ just yesterday and the build worked just fine, so the change must have been recent?

I tried "make clean", etc.

**Comment by mfundul** [comment]
Yes, libuv has been added as hard dependency during compilation. This has been in the documentation as a requirement for some months now, the way forward for the netdata codebase is using a lot of libuv code.

The judy library is not a hard requirement for netdata. If it's missing, you lose `memory mode = dbengine`. Both those libraries were never statically included with the `netdata-installer.sh` method, because this method causes a compilation that depends on those libraries.

libuv should be included in the static binaries available for download though.

**Comment by csch42** [comment]
Hmmm ... 🤔

I may need to build them seperately then, I guess, as there appears to be no `libuv` development package in the Debian archives for _wheezy_ and I do not want the external dependencies for libuv and judy on _squeeze_, either. It's one of the important "features" of _netdata_ for me → just one binary, without external dependancies, which I can just slap on my routers (MIPS / MIPSEL based Ubiquiti EdgeRouters)

Which, btw., is also the reason the pre-built binaries do not help me, as my platforms are not supported with these.

**Comment by csch42** [comment]
So I took the "hints" from .`travis/package_management/build_judy.sh` and `.travis/package_management/build_libuv.sh`, locally built and installed static-only versions of both and now I'm back to "normal" → single binary (Oh, wait ... there is `netdatacli` now 🤔😉) without external dependencies - and even _dbengine_ is now available on all platforms too.

**Comment by venken** [comment]
configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.
 FAILED   
tell me ，how to fix it？

**Comment by amoss** [comment]
@venken You need to install the package for your system. Take a look at https://docs.netdata.cloud/packaging/installer/ (there are examples in the "This is how to do it by hand" section).

**Comment by molcese** [comment]
I have the same problems. Debian 8 Jessie

**Comment by nitrogear** [comment]
Fix for Ubuntu: apt install libuv1-dev

**Comment by mfundul** [comment]
That looks problematic: https://www.lucas-nussbaum.net/blog/?p=947

**Comment by molcese** [comment]
> That looks problematic: https://www.lucas-nussbaum.net/blog/?p=947

Thanks!!!
Work fine!!!

**Comment by Behner** [comment]
> Fix for Ubuntu: apt install libuv1-dev

@nitrogear what repository do you see libuv1-dev in? What version of Ubuntu are you on?

**Comment by csch42** [comment]
So I took the "hints" from .travis/package_management/build_judy.sh and .travis/package_management/build_libuv.sh, locally built and installed static-only versions of both and now I'm back to "normal" → single binary (Oh, wait ... there is netdatacli now 🤔😉) without external dependencies - and even dbengine is now available on all platforms too.

Sorry for bugging you. I was just surprised by the whole "Woah! It built fine just yesterday!!!"-part 🤷🏼‍♂️

Thanks - case closed.

**Comment by dsylla** [comment]
Fix Ubuntu 14.04 (Trusty)

sudo add-apt-repository ppa:acooks/libwebsockets6
sudo apt-get update
sudo apt-get install libuv1.dev

Source : https://stackoverflow.com/a/49628607

**Comment by rachlenko** [comment]
Hows about redhat8 ? 
I've installed : 
libuv.x86_64 : Platform layer for node.js

It is doesn't helps

**Comment by RisedSky** [comment]
> Fix Ubuntu 14.04 (Trusty)
> 
> sudo add-apt-repository ppa:acooks/libwebsockets6
> sudo apt-get update
> sudo apt-get install libuv1.dev
> 
> Source : https://stackoverflow.com/a/49628607

People who can't find the ppa package : 
sudo apt update
sudo apt -y install software-properties-common dirmngr apt-transport-https lsb-release ca-certificates
