### ISSUE TITLE
Disabling a Slave from sending alarms or alerts

### ISSUE THREAD

**Issue by MichealBenzel** [netdata/netdata#7450]
Looking for a way to disable some of my slaves from sending any alerts or alarms and removing them from the Master's dashboard.  Everything right now is a Master / Slave setup Linux working perfectly I might add ... just need to disable the alarms an alerts while leaving everything in place in case I ever want to restart them.

**Comment by ilyam8** [comment]
Hi @MichealBenzel 

See

https://github.com/netdata/netdata/blob/0f72fd029099080c9080eedfa6493aa1a5ac7ab9/streaming/stream.conf#L140-L148

**Comment by MichealBenzel** [comment]
Thank you! Setting to auto on the Master and stopping and starting the service then shutting off the Nodes service did as needed.
