### ISSUE TITLE
HTTP basic authentication for streaming?

### ISSUE THREAD

**Issue by netchild** [netdata/netdata#7457]
##### Feature idea summary

I found a lot of closed tickets which talk about converting the streaming to http/websockets, there is also talk about authentication (which shall be feasible after converting to http/websockets), but I can't really find any docs about it.

So let's give a scenario:
 - 2 sites with netdata
 - each site has a reverse proxy (e.g. nginx) which does the TLS work and has http basic authentication configured for access to netdata
 - access between the reverse proxy and netdata is http

This means direct access no netdata inside each site without encryption and authentication, but cross-site access (over the internet) via TLS and authentication.

Now the goal is to to stream the netdata-data from one site to the other site. The streaming feature already allows to specify SSL to encrypt, but what about basic authentication?

So far I can not find any trace in the docs that this is possible. As such the feature request to specify user/pw for basic authentication.

**Comment by thiagoftsm** [comment]
Hi @netchild .

It is possible to configure a simple HTTP Auth on webservers to access netdata with authentication ( https://docs.netdata.cloud/docs/running-behind-apache/#enable-basic-auth ) , but Netdata itself is not authenticating yet, it only does for while direct connection.

**Comment by netchild** [comment]
I'm doing already HTTP auth (in nginx instead of apache). The feature request is to implement e.g. "<user>:<pw>@<hostname>:<port>:SSL" syntax for the streaming config, or even better its own user/pw settings and to provide the http auth headers to the master.

I noticed that Netdata itself is not really up to this right now. I already experimented with the registry and HTTP auth, doesn't work (for a non-registry netdata system). The OPTIONS request to the registry is somehow throwing away the user:pw@ part (not sure if this is a browser issue or an netdata-js issue) and nginx responds back that it wants HTTP auth. The XMLHttpRequest afterwards fails due to CORS policy which seems to be an issue on my side (I've set the Access-Control-Allow-Origin in nginx on the registry-server, but the browser still complains about it not being set... and while looking at it: seems netdata sets this to "*", so I have it set twice... but even before I had it, it complained about this... maybe another CORS header I've set, I need to investigate).

**Comment by thiagoftsm** [comment]
I think I understood better now, only to confirm, before we have condition to move in front. Righit now, Netdata is missing this part of the RFC https://tools.ietf.org/html/rfc7235#section-4.2 , so we need to give the conditions for our users to give arguments like ":@::SSL" that will be converted to the header `Authorization: Basic PASS`. Am I missing something?

**Comment by netchild** [comment]
With PASS being base64 of "user:pass" according to https://en.wikipedia.org/wiki/Basic_access_authentication).

It may be better to add an authorisation type setting (which may initially only support "basic"), so that later one can add other authorisation types like digest authentication without breaking the behavior during an update of netdata.

**Comment by thiagoftsm** [comment]
> It may be better to add an authorisation type setting (which may initially only support "basic"), so that later one can add other authorisation types like digest authentication without breaking the behavior during an update of netdata.

It makes sense, thank you for the explanation! I will talk with our team for we bring this feature for the whole community. Thank you for the explanation!

**Comment by marienfressinaud** [comment]
I would love to see this feature implemented, but note you can disable HTTP basic authentication for specific IPs. E.g. for Nginx:

```nginx
server {
  location / {
    # […]

    satisfy any;
    allow ip.of.slave.netdata;
    deny all;

    auth_basic "Restricted Content";
    auth_basic_user_file /path/to/.htpasswd;
  }
}
```

I hope it can help while the feature is not implemented.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
