### ISSUE TITLE
Installation or Build Fauilure

### ISSUE THREAD

**Issue by Cadjoe** [netdata/netdata#7461]
`![netdata-installation-failure](https://user-images.githubusercontent.com/29492191/70356435-6931c900-1842-11ea-9212-e31e19f86f64.png)`

#### Summary
I have all the required packages but still the build process/attempt fails every time. I've verified that like indicated below and ran the installation again, a couple of times but I still get the same error

> yum install libuuid-devel zlib-devel gcc make automake pkg-config
Updating Subscription Management repositories.
Last metadata expiration check: 0:23:34 ago on Fri 06 Dec 2019 15:48:21 EST.
Package libuuid-devel-2.32.1-17.el8.x86_64 is already installed.
Package zlib-devel-1.2.11-10.el8.x86_64 is already installed.
Package gcc-8.3.1-4.5.el8.x86_64 is already installed.
Package make-1:4.2.1-9.el8.x86_64 is already installed.
Package automake-1.16.1-6.el8.noarch is already installed.
Package pkgconf-pkg-config-1.4.2-1.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by mfundul** [comment]
You need libuv version 1. See the documentation [here](https://github.com/netdata/netdata/tree/master/packaging/installer#prepare-your-system) on how to prepare your system.

The yum command is
```
yum install autoconf automake curl gcc git libmnl-devel libuuid-devel openssl-devel libuv-devel lz4-devel Judy-devel make nc pkgconfig python zlib-devel
```

Please include the full text output of your installation so that we can see all errors as they occured.

**Comment by Cadjoe** [comment]
>

>   ./netdata-installer.sh 
> 
>   ^
>   |.-.   .-.   .-.   .-.   .  netdata                                        
>   |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!  
>   +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->
> 
> 
>   You are about to build and install netdata to your system.
> 
>   It will be installed at these locations:
> 
>    - the daemon     at /usr/sbin/netdata
>    - config files   in /etc/netdata
>    - web files      in /usr/share/netdata
>    - plugins        in /usr/libexec/netdata
>    - cache files    in /var/cache/netdata
>    - db files       in /var/lib/netdata
>    - log files      in /var/log/netdata
>    - pid file       at /var/run/netdata.pid
>    - logrotate file at /etc/logrotate.d/netdata
> 
>   This installer allows you to change the installation path.
>   Press Control-C and run the same command with --help for help.
> 
> Press ENTER to build and install netdata to your system > 
> 
>  --- Run autotools to configure the build environment --- 
> [/root/netdata]# autoreconf -ivf 
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force -I build/m4
> autoreconf: configure.ac: tracing
> autoreconf: configure.ac: not using Libtool
> autoreconf: running: /usr/bin/autoconf --force
> autoreconf: running: /usr/bin/autoheader --force
> autoreconf: running: automake --add-missing --copy --force-missing
> autoreconf: Leaving directory `.'
>  OK   
> 
> [/root/netdata]# ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/libexec --libdir=/usr/lib --with-zlib --with-math --with-user=netdata CFLAGS=-O2 
> configure: loading site script /usr/share/config.site
> checking whether to enable maintainer-specific portions of Makefiles... no
> checking for a BSD-compatible install... /bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking how to create a pax tar archive... gnutar
> checking whether make supports nested variables... (cached) yes
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking whether make supports the include directive... yes (GNU style)
> checking dependency style of gcc... gcc3
> checking for g++... no
> checking for c++... no
> checking for gpp... no
> checking for aCC... no
> checking for CC... no
> checking for cxx... no
> checking for cc++... no
> checking for cl.exe... no
> checking for FCC... no
> checking for KCC... no
> checking for RCC... no
> checking for xlC_r... no
> checking for xlC... no
> checking whether we are using the GNU C++ compiler... no
> checking whether g++ accepts -g... no
> checking dependency style of g++... none
> checking for pkg-config... /bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking minix/config.h usability... no
> checking minix/config.h presence... no
> checking for minix/config.h... no
> checking whether it is safe to define __EXTENSIONS__... yes
> checking for __attribute__((returns_nonnull))... yes
> checking for __attribute__((malloc))... yes
> checking for __attribute__((noreturn))... yes
> checking for __attribute__((noinline))... yes
> checking for __attribute__((format))... yes
> checking for __attribute__((warn_unused_result))... yes
> checking for struct timespec... yes
> checking for clockid_t... yes
> checking for library containing clock_gettime... none required
> checking for clock_gettime... yes
> checking for sched_setscheduler... yes
> checking for sched_getscheduler... yes
> checking for sched_getparam... yes
> checking for sched_get_priority_min... yes
> checking for sched_get_priority_max... yes
> checking for getpriority... yes
> checking for setpriority... yes
> checking for nice... yes
> checking for recvmmsg... yes
> checking for int8_t... yes
> checking for int16_t... yes
> checking for int32_t... yes
> checking for int64_t... yes
> checking for uint8_t... yes
> checking for uint16_t... yes
> checking for uint32_t... yes
> checking for uint64_t... yes
> checking for inline... inline
> checking whether strerror_r is declared... yes
> checking for strerror_r... yes
> checking whether strerror_r returns char *... yes
> checking for _Generic... yes
> checking for __atomic... yes
> checking size of void *... 8
> checking whether sys/types.h defines makedev... no
> checking sys/mkdev.h usability... no
> checking sys/mkdev.h presence... no
> checking for sys/mkdev.h... no
> checking sys/sysmacros.h usability... yes
> checking sys/sysmacros.h presence... yes
> checking for sys/sysmacros.h... yes
> checking for sys/types.h... (cached) yes
> checking for netinet/in.h... yes
> checking for arpa/nameser.h... yes
> checking for netdb.h... yes
> checking for resolv.h... yes
> checking for sys/prctl.h... yes
> checking for sys/vfs.h... yes
> checking for sys/statfs.h... yes
> checking for sys/statvfs.h... yes
> checking for sys/mount.h... yes
> checking for accept4... yes
> checking operating system... linux with id 1
> checking if compiler needs -Werror to reject unknown flags... no
> checking for the pthreads library -lpthreads... no
> checking whether pthreads work without any flags... no
> checking whether pthreads work with -Kthread... no
> checking whether pthreads work with -kthread... no
> checking for the pthreads library -llthread... no
> checking whether pthreads work with -pthread... yes
> checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
> checking if more special flags are required for pthreads... no
> checking for PTHREAD_PRIO_INHERIT... yes
> checking for sin in -lm... yes
> checking if libm should be used... yes
> checking for uv_fs_scandir_next in -luv... no
> configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.
>  FAILED   
> 
> 
>   ^
>   |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
>   |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'  
>   +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->
> 
> 
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> Sorry! netdata failed to build...
> 
> You may need to check these:
> 
> 1. The package uuid-dev (or libuuid-devel) has to be installed.
> 
>    If your system cannot find libuuid, although it is installed
>    run me with the option:  --libs-are-really-here
> 
> 2. The package zlib1g-dev (or zlib-devel) has to be installed.
> 
>    If your system cannot find zlib, although it is installed
>    run me with the option:  --libs-are-really-here
> 
> 3. You need basic build tools installed, like:
> 
>    gcc make autoconf automake pkg-config
> 
>    Autoconf version 2.60 or higher is required.
> 
> If you still cannot get it to build, ask for help at github:
> 
>    https://github.com/netdata/netdata/issues

The above is the issue I was facing which is related to libuv1 or libuv-devel. My system couldn't find them when I ran `yum install libuv -y` or `libuv-devel`. I had to download and install it manually from [here](url). 

Thanks for your help @mfundul .
