### ISSUE TITLE
netdata stop continuing monitor mongodb after the service stop and restart

### ISSUE THREAD

**Issue by debu99** [netdata/netdata#7463]
we use netdata to monitoring mongodb and we found if the mongodb service was stopped and we manually fixed the issue, the netdata didn't successfully receive the metrics data, even we browse the localhost webpage, we found there is no mongodb item, but after we restart the netdata service, it successfully showed the mongodb on webpage and also received from remote db

**Comment by ilyam8** [comment]
There is a `penalty` option, if module keeps failing to get data `python.d.plugin` temporarily increases its `update_every` value. It wil change it back right after first successful collection.

https://github.com/netdata/netdata/blob/7e6e405c146b17cb60711883770aa67d0fbae185/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SimpleService.py#L52-L55


You can disable this by setting `penalty` to `no` in the module configuration file.
