### ISSUE TITLE
Registry feature needs "Do Not Track" disabled in the browser

### ISSUE THREAD

**Issue by netchild** [netdata/netdata#7465]
##### Bug report summary

You mention in the registry docs that the browser needs to be configured to allow cross-site cookies. You may say that implicitely this means also to "disable the Do Not Track setttings". Please mention explicitely in the docs to disable DNT and to allow cross-site cookies.

At least Chrome shows in the developer console that the request is not send due to DNT.

**Comment by jacekkolasa** [comment]
I think that Netdata must also be configured to "respect do not track policy", listed here: https://docs.netdata.cloud/web/server/#other-netdataconf-web-section-options

Browser settings that need to be configured can vary - for example in Safari you need to uncheck "Prevent cross-site tracking", or you need to visit netdata running registry explicitly. In Brave Browser - you need to disable Brave Shields, to fix that.
 
@joelhans what do you think?

**Comment by joelhans** [comment]
@jacekkolasa Made a tweak to this. Thanks for the feedback!
