### ISSUE TITLE
ksm no longer merging on ubuntu

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#7467]
##### Bug report summary
I've noticed that my "Kernel Same Page Merging" charts have gone away. Checking on the server I still have:
```
cat /sys/kernel/mm/ksm/run
1
cat /sys/kernel/mm/ksm/sleep_millisecs
1000
```
When I check for merging I get:
```
grep . /sys/kernel/mm/ksm/pages_*
/sys/kernel/mm/ksm/pages_shared:0
/sys/kernel/mm/ksm/pages_sharing:0
/sys/kernel/mm/ksm/pages_to_scan:100
/sys/kernel/mm/ksm/pages_unshared:0
/sys/kernel/mm/ksm/pages_volatile:0
```
So it seems that ksmd is set up but that netdata is not merging any pages.

##### OS / Environment
OS:         Ubuntu 18.04.3 LTS (bionic)
Kernel:     4.15.0-72-generic
##### Netdata version (ouput of `netdata -V`)
netdata v1.19.0-62-nightly

##### Expected behavior
Should see some page merging .

**Comment by mfundul** [comment]
KSM does not apply for `memory mode = dbengine`.

You can refresh your configuration file with:
```
wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
```
and check your values.

**Comment by Steve8291** [comment]
Thanks @mfundul 
I just checked and I have the default value ` memory mode = dbengine` in my netdata.conf
I also found out that I can no longer do a simple refresh of my config file with the wget command.
Seems that it can no longer connect now that I run netdata behind apache and have it set up as an https site with password authentication. 
I temporarily disabled password authentication for the site and was able to connect and download the new config file with `wget -O /etc/netdata/netdata.conf https://www.mynetdata.site/netdata.conf`
However, I still do not show any same page merging.
Is there any chance that this is all due to running behind Apache?

**Comment by mfundul** [comment]
netdata itself is not merging any pages because you're using `memory mode = dbengine`. Now about the charts, it's possible they are not showed because all data are zero. @vlvkobal is that correct?

**Comment by Steve8291** [comment]
I went back and reread the newer documentation on the database: [https://docs.netdata.cloud/database/#monitoring-kernel-memory-de-duplication-performance](url)
I think that when dbengine became the default I lost the charts. Makes complete sense now. 
Thanks for explaining that @mfundul 
I would assume that charts will not be shown if the data is zero. That's how other charts behave for me.
