### ISSUE TITLE
kickstart-static64.sh: Unknown option '--disable-telemetry' or invalid number of arguments.

### ISSUE THREAD

**Issue by VivaldiKF** [netdata/netdata#7470]
##### Bug report summary

The [pre-built static binary installation](https://github.com/netdata/netdata/tree/master/packaging/installer#linux-64bit-pre-built-static-binary) method fails when adding the option `--disable-telemetry`:

This works:

```bash
$ bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --no-updates --stable-channel
```

This does not work:

```bash
$ bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --no-updates --stable-channel --disable-telemetry
```

The error message:

```plain
Unknown option '--disable-telemetry' or invalid number of arguments. Please check the README for the available arguments of /dev/fd/63 and try again
```

##### OS / Environment

The environment is a fresh install of Debian 10.2 in a VM:

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version (ouput of `netdata -V`)

N/A; `netdata` will not install.

##### Steps To Reproduce

Append `--disable-telemetry` to the pre-built static binary installation method:

```bash
$ bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --no-updates --stable-channel --disable-telemetry
```

##### Expected behavior

No error message; successful installation.

**Comment by Ferroin** [comment]
#7437 is adding this. Not sure how the docs got updated before that was merged though, but until it's merged, this option won't work.
