### ISSUE TITLE
Please improve documentation for CentOS 7 with Apache

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#7471]
##### Question summary

Please can you improve the documentation with some more relevant step by step walkthrough guides in particular relating to CentOS 7 with Apache and VHosts?

There seems to be an emphasis in places on nginx, Ubuntu, PHP-FPM which is fine but we don't all use them. FPM is a resource hog! I've been trying for over a year to do the following:

1) Configure Netdata to work behind CentOS7 Apache (MPM Event), using proxy via either netdata.hostname.com or as a folder following my vhosts e.g. examplesite1.com/netdata examplesite2.com/netdata etc. 
None of the documentation examples seem to actually work on the latest Apache and CentOS7.

"Rest of vhost config follows?" 
You don't actually get to see the vhosts in Apache if you follow the Apache guidance on safe editing.

In Apache there are instead 3 areas (designated safe from update overwrites, don't edit httpd.conf or includes, use the provided config area) via WHM > Server Configuration > Apache Configuration > Include Editor.  I presume you have to use either pre vhost or post vhost. 
The examples don't mention them when configuring a vhost. They just tell you to code to vhosts. 
What about SSL for those hosts, do they just inherit from httpd.conf whilst the hostserver Netdata still uses the /ssl folder?

2) I finally got the https version of Netdata on my host server working after copying the certs via WHM into Netdata, copying the .crt and .key via SSH from source into /etc/netdata/ssl and renaming to .pem wouldn't work, connection refused. Creating empty files in there and pasting the cert and key from WHM into them finally worked!

##### OS / Environment

Netdata 1 line install, nightly releases.

48 core CentOS 7.6 cloud VPS which has access to 6GB RAM (3GB and another 3GB of burstable ram), PHP 7.3.12 with CentOS 7.7 and latest v84.0.16 of WHM CPanel, Redis, Zend Opcache.

`# Percona Toolkit System Summary Report ######################
    Hostname | vpsXXXXXX.xxxxxx.com
      Uptime | 12:46,  1 user,  load average: 0.07, 0.13, 0.26
    Platform | Linux
     Release | CentOS Linux release 7.7.1908 (Core)
      Kernel | 3.10.0-042stab138.1
Architecture | CPU = 64-bit, OS = 64-bit
   Threading | NPTL 2.17
     SELinux | Disabled
 Virtualized | OpenVZ/Virtuozzo
# Processor ##################################################
  Processors | physical = 2, cores = 24, virtual = 48, hyperthreading = yes
      Speeds | 48x2299.744
      Models | 48xIntel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
      Caches | 48x30720 KB
# Memory #####################################################
       Total | 3.0G
        Free | 447.4M
        Used | physical = 2.1G, swap allocated = 3.0G, swap used = 204.0k, virtual = 2.1G
      Shared | 8.6M
     Buffers | 519.8M
      Caches | 783.7M
       Dirty | 344 kB
     UsedRSS | 1.3G
  Swappiness | 1
 DirtyPolicy | 20, 10
 DirtyStatus | 0, 0 `

`

extension_dir | /opt/cpanel/ea-php73/root/usr/lib64/php/modules | /opt/cpanel/ea-php73/root/usr/lib64/php/modules

Configuration File (php.ini) Path | /opt/cpanel/ea-php73/root/etc

`

##### Component Name

Python.d/phpfpm.conf

##### Expected results

Improved or updated documentation for users of Apache with CentOS covering PHP stats, proxying Netdata behind Apache, keeping Netdata on hostserver for global server but also for vhosts so data is relevant to the specific host/website e.g. examplevhost.com/netdata or netdata.examplevhost.com formats.

PHP stats working with minimal or no config out of the box, support for Apache, FastCGI and LSAPI if it's possible to do.

Many thanks.

**Comment by ilyam8** [comment]
I see there is pretty detailed how to run `netdata` behind nginx/apache in the docs

> https://docs.netdata.cloud/docs/running-behind-nginx/#running-netdata-behind-nginx

**Comment by TheOldMan2000** [comment]
Yes, thanks, but it didn't work for me.
