### ISSUE TITLE
how to reenable plugin after it had been killed (manually)

### ISSUE THREAD

**Issue by mapl** [netdata/netdata#7472]
I've killed the go.d.plugin process and assumed after starting it again, netdata would resume collection data. Then I saw this message in the error.log. 
Is there a way to "reenable" the go plugin once it had been killed?

```
netdata INFO  : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 22662) was killed 
with SIGTERM. Disabling it.
```

**Comment by ilyam8** [comment]
If i understand it right there is no way netdata will start the plugin killed by sigterm

https://github.com/netdata/netdata/blob/8260af09934d9b0dc0b5944b18fe0dd0ac60d831/collectors/plugins.d/plugins_d.c#L687-L692

**Comment by mapl** [comment]
Thank you for confirming. 
As it seems there is currently no way to restart the plugin, other than restarting the netdata service itself, I would like to raise a feature request proposal to make it possible

**Comment by ilyam8** [comment]
Why do you need to kill it manually?

**Comment by mapl** [comment]
well, i'm playing around compiling my own go.d.plugin and want to use this instead of the shipped go.d.plugin. So I thought, I just kill go.d.plugin process and start my own one, living in another directory. 

But it is unfortunately not that simple. 

Right now, I need to overwrite /usr/libexec/netdata/plugins.d/go.d.plugin with my own compiled version and restart the netdata service.

Perhaps there is another more convenient way?

**Comment by ilyam8** [comment]
What do you want to overwrite?

If you want to disable some modules, all you need is:
 - git clone go.d.plugin
 - [disable modules](https://github.com/netdata/go.d.plugin/blob/2240677c2a61a8260a7b84cceda0f949a703cba8/cmd/godplugin/main.go#L14-L51) you dont need
 - compile it
 - name it differently (suffix must be `.plugin`)
 - disable go.d.plugin in netdata.conf

**Comment by mapl** [comment]
I added the my own compiled binary "go2.d.plugin" to the plugin section in the netdata.conf and populated the other required configs for this plugin. 

I also needed to copy my own binary to the /usr/libexec/netdata/plugins.d/ folder in order to get it loaded (no error occured in the error.log when the bin is actually missing...) 

In the end it works, so I do not need to touch the original go.d.plugin bin. 

Thank you for bringing this to my attention!

**Comment by ilyam8** [comment]
> no error occured in the error.log when the bin is actually missing..

It is ok, netdata just loads all plugins (`*.plugin`) from the plugins.d dir.

Is your problem solved? Can we close the issue?

**Comment by mapl** [comment]
My initial inquery was whether its possible to restart the plugin after its SIGTERM
For now its not really a problem, but it would be good to have some kind of setting to control the behavior.

**Comment by ilyam8** [comment]
I see no use case for it. 

> Right now, I need to overwrite /usr/libexec/netdata/plugins.d/go.d.plugin with my own compiled version and restart the netdata service.

How you were trying to do it is not the correct way imo.

**Comment by mapl** [comment]
> There is no need to overwrite existing binary, it is better to disable exisiting and add your own.

I did that now, thanks to your advise. It was just a quick and dirty way

**Comment by ilyam8** [comment]
btw if you use `SIGHUP`, `SIGINT` netdata doesnt disable it.

**Comment by ilyam8** [comment]
See

https://github.com/netdata/go-orchestrator/blob/c793edba0e8f5c81c151a2b89bae559aa9126613/orchestrator.go#L150-L164

it exits with 0

**Comment by mapl** [comment]
oh man :) i'm sorry SIGINT seems to work well!

go.d INFO: main[main] SIGINT received. Terminating...
netdata ERROR : PLUGINSD[go2.d] : read failed: end of file
netdata ERROR : PLUGINSD[go2.d] : '/usr/libexec/netdata/plugins.d/go2.d.plugin' (pid 24618) disconnected after 478 successful data collections (ENDs).
netdata INFO  : PLUGINSD[go2.d] : connected to '/usr/libexec/netdata/plugins.d/go2.d.plugin' running on pid 24641

**Comment by ilyam8** [comment]
Yes, if it exits with 0 then this netdata uses this func to handle it

https://github.com/netdata/netdata/blob/8260af09934d9b0dc0b5944b18fe0dd0ac60d831/collectors/plugins.d/plugins_d.c#L659-L685
