### ISSUE TITLE
Request to compile aarch64 one-click installation using asus router GT AC 5300

### ISSUE THREAD

**Issue by BH1NBN** [netdata/netdata#7474]
Request to compile aarch64 one-click installation using asus router GT AC 5300
I do n’t have the relevant knowledge of liunx, so I would like to ask for help, my friend

**Comment by prologic** [comment]
Hi @BH1NBN Apologies for the late response. Have you already tried our [Installing NetData with kickstart.sh](https://docs.netdata.cloud/packaging/installer/methods/kickstart/) method?

We do already support building NetData on non-x86 architectures and our Docker Images already support this as well. I don't have access to the exact hardware platform you mention; but we are also actively working on multi-arch support in general. See: #7826 and #7824

**Comment by prologic** [comment]
We are closing this in favour of #6847 as we cannot realistically test or reproduce this in any of our lab environments and we feel it would be better to support static builds of the agent for other platforms with `kickstart-static*.sh`
