### ISSUE TITLE
health.silencers.json file missing

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#7477]
##### Bug report summary
Ever since the new Health API was created I've seen the following in my error log:

> netdata ERROR : MAIN : Cannot open the file /var/lib/netdata/health.silencers.json (errno 2, No such file or directory)

Would it be possible to have either the netdata installer or the `main.c` function `set_silencers_filename()` create the file or ignore it if it doesn't exist. I'm guessing it doesn't exist because I've never used the API. 
Note: It isn't enough to just create the file. It needs to at least have `json` appended to it or you get the error:

> netdata ERROR : MAIN : Health silencers file /var/lib/netdata/health.silencers.json has the size 0 that is out of range[ 1 , 10000 ]. Aborting read.

I can silence the error with:
`echo 'json' > /var/lib/netdata/health.silencers.json`

##### OS / Environment
OS:         Ubuntu 18.04.3 LTS (bionic)
Kernel:     4.15.0-72-generic

##### Netdata version (ouput of `netdata -V`)
v1.19.0-69-nightly

##### Component Name
web/api/health

The three files that are involved are:

> netdata/daemon/main.c
> netdata/libnetdata/health/health.c
> netdata/libnetdata/health/health.h

##### Steps To Reproduce
Install and check the logs.

**Comment by thiagoftsm** [comment]
Hi @Steve8291 ,

Thank you to call us attention for this fact, I created the PR #7479 to clarify the message converting it from an error to info.
