### ISSUE TITLE
Add libmosquitto dependency to the agent

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#7482]
##### Library dependency

We need to add the ```libmosquitto``` dependency to the agent as it is needed for the agent - cloud link MQTT protocol setup

**Comment by amoss** [comment]
* This needs to be added to the dependency checking / detection in autotools.
* Does the installer require any changes?
* Needs to be included in pre-built images.
* What is the impact on kickstart?
* Documentation must be updated to include the packages in the install steps.
