### ISSUE TITLE
Should VHosts all be Master or Slaves to the main Netdata?

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#7484]
Please could I get clarification so that I understand correctly, in this scenario:

You have a VPS. You install Netdata on the main VPs server hostname myvps.myhostingcompany.net

That gives you a Netdata Dashboard at myvps.myhostingcompany.net:19999 which shows serverwide data and stats.

On the VPS you have several websites as VHosts, each with their own unique domain:
siteA.com
siteB.com etc

A) Is there a scenario where you would install Netdata on each VHost, presumably the information each shows would be solely relevant to that particular website, Memory, Mysql, Apache weblog etc via 
siteA.com:19999
siteB.com:19999 etc?

B) Or is each VHost Dashboard on siteA.com, site B.com going to all display the same data, all mirroring the main Netdata at myvps.myhostingcompany.net, in which case it would be rather pointless?

C) Or should the Netdata installs on each VHost SiteA.com, SiteB.com each be set to Slave mode and stream without a DB to the Master Netdata on the server hostname myvps.myhostingcompany.net?

Do you accomplish this set up proxying the main Netdata via Apache to each VHost or would you need to install a Netdata separately on each VHost, because you log into your VPS via SSH and run the one line install command, it installs Netdata on the main server hostname, myvps.myhostingcompany.net:19999

Many thanks!

**Comment by ilyam8** [comment]
Hi

Do you have some virtualization on your VPS?

**Comment by TheOldMan2000** [comment]
Hi
Yes, cloud VPS Virtuoso, CentOS 7.

**Comment by ilyam8** [comment]
Ok, Vhosts just websites (not vms) and it is not feasible to install netdata there.

Still you can use `weblog` to monitor a lot of things for every vhost

> https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#charts

**Comment by TheOldMan2000** [comment]
Thanks for the clarification!
