### ISSUE TITLE
RFC: "Host" labels in docker containers

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7488]
In #7400, we are taking some of the environment parameters auto-detected by netdata and converting into "host" labels. However, in a docker container, looking at the container we're running in for these parameters may well be the wrong thing to do.

Users run netdata in a docker container on their system, in order to monitor **the host system**, not the container itself. Our whole internal definition of `host` is misleading here. Yes, the container itself can be considered a `host` by its own right, but what's the point? If we were to switch our focus and acknowledge that the container's only purpose is to monitor the host machine that runs docker, the netdata docker instance itself should be no more than just another cgroup on that host. This "point of view shift" is already there for everything that we get from the host's `var` and `sys`. So when I look at the dashboard of a netdata running on docker, I may be seeing on the URL whatever was specified for that container, but the key charts themselves correctly show me what's happening on the host machine. We can't directly access packaged applications on that host machine, so auto-discovery for a mysql server would not work, but we at least provide the info users need the most.

Getting back to the environment parameters mentioned earlier, netdata currently populates that information by executing [system-info.sh](https://github.com/netdata/netdata/blob/master/daemon/system-info.sh). So it's just looking at the info of the container itself. While useful for statistical and possibly later for self-diagnosing purposes, this information shouldn't be used to label a netdata's charts, when running as a docker container. Instead, we should try to find a way to get the host's "system info", if at all possible. 

Further down the line, we should attempt to retrieve [additional labels from the docker metadata](https://docs.docker.com/config/labels-custom-metadata/), if a user has provided netdata access to the docker socket. Alternative ways may be possible in specific use cases, such as with [Amazon ECS container metadata](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-metadata.html). We'll need some assistance identifying such alternatives. However, we need to be clear that those labels should only be attached to the monitored cgroups (including the netdata container) and not to the host itself. 

We will have an internal discussion on these matters and would like to also request assistance from the community.

**Comment by cakrit** [comment]
The following 3 are actually correct and can be used:
Kernel version
Architecture
Container Tech

To be able to get 
OS name, OS version and Virtualization we need to modify our docker file to mount /etc/os-release under /host/etc/os-release and read that file for the specific labels.

**Comment by cakrit** [comment]
- [ ] Add to the README under https://github.com/netdata/netdata/tree/master/packaging/docker the following to the docker command:
`  -v /etc/os-release:/host/etc/os-release:ro \`
- [ ] Modify system-info.sh to also look under the host prefix. The `netdata.conf` env. variable NETDATA_HOST_PREFIX will tell us where to find the os-release file.  system-info.sh will check that variable and if it's not empty, it will run additional code, to try produce 5 more variables (NAME|ID|ID_LIKE|VERSION|VERSION_ID) for the host, by looking for ${NETDATA_HOST_PREFIX}/fos-release . We add those variables to the netdata environment. 
```
	if [ -f "/host/etc/os-release" ]; then
		OS_DETECTION="/host/etc/os-release"
		eval "$(grep -E "^(NAME|ID|ID_LIKE|VERSION|VERSION_ID)=" </host/etc/os-release)"
	fi
```

**Comment by amoss** [comment]
Update: I've written the code to handle the split between container and host. 
* The systemd-detect-virt still needs to be put in.
* Check the interface to the GA.
* Check the loading code in main.c.
* Test on some docker configuration (i.e. our standard container and the new incremental build Dockerfile).
* Push to the beginning of the next sprint - will be complete before the new info task starts.

**Comment by amoss** [comment]
Some of the new bare-metal output:
```
NETDATA_HOST_OS_NAME=FreeBSD
NETDATA_HOST_OS_ID=FreeBSD
NETDATA_HOST_OS_ID_LIKE=FreeBSD
NETDATA_HOST_OS_VERSION=12.0-RELEASE-p6
NETDATA_HOST_OS_VERSION_ID=
NETDATA_HOST_OS_DETECTION=uname
NETDATA_SYSTEM_KERNEL_NAME=FreeBSD
NETDATA_SYSTEM_KERNEL_VERSION=1200086
NETDATA_SYSTEM_ARCHITECTURE=amd64
NETDATA_SYSTEM_VIRTUALIZATION=unknown
NETDATA_SYSTEM_VIRT_DETECTION=none
NETDATA_SYSTEM_CONTAINER=unknown
NETDATA_SYSTEM_CONTAINER_DETECTION=none
```

```
NETDATA_HOST_OS_NAME=Debian
NETDATA_HOST_OS_ID=buster
NETDATA_HOST_OS_ID_LIKE=
NETDATA_HOST_OS_VERSION=10
NETDATA_HOST_OS_VERSION_ID=10
NETDATA_HOST_OS_DETECTION=lsb_release
NETDATA_SYSTEM_KERNEL_NAME=Linux
NETDATA_SYSTEM_KERNEL_VERSION=4.19.0-6-amd64
NETDATA_SYSTEM_ARCHITECTURE=x86_64
NETDATA_SYSTEM_VIRTUALIZATION=none
NETDATA_SYSTEM_VIRT_DETECTION=systemd-detect-virt
NETDATA_SYSTEM_CONTAINER=unknown
NETDATA_SYSTEM_CONTAINER_DETECTION=none
```

**Comment by amoss** [comment]
Improved the virtualization detection, if `systemd-detect-virt` is available we don't need any further information, but in a Vagrant box this is not available so added some further heuristics.

As root:
```
NETDATA_HOST_OS_NAME=Ubuntu
NETDATA_HOST_OS_ID=trusty
NETDATA_HOST_OS_ID_LIKE=debian
NETDATA_HOST_OS_VERSION=14.04
NETDATA_HOST_OS_VERSION_ID=14.04
NETDATA_HOST_OS_DETECTION=lsb_release
NETDATA_SYSTEM_KERNEL_NAME=Linux
NETDATA_SYSTEM_KERNEL_VERSION=3.13.0-170-generic
NETDATA_SYSTEM_ARCHITECTURE=x86_64
NETDATA_SYSTEM_VIRTUALIZATION=VirtualBox
NETDATA_SYSTEM_VIRT_DETECTION=dmidecode
NETDATA_SYSTEM_CONTAINER=unknown
NETDATA_SYSTEM_CONTAINER_DETECTION=none
```

As non-privileged user:
```
NETDATA_HOST_OS_NAME=Ubuntu
NETDATA_HOST_OS_ID=trusty
NETDATA_HOST_OS_ID_LIKE=debian
NETDATA_HOST_OS_VERSION=14.04
NETDATA_HOST_OS_VERSION_ID=14.04
NETDATA_HOST_OS_DETECTION=lsb_release
NETDATA_SYSTEM_KERNEL_NAME=Linux
NETDATA_SYSTEM_KERNEL_VERSION=3.13.0-170-generic
NETDATA_SYSTEM_ARCHITECTURE=x86_64
NETDATA_SYSTEM_VIRTUALIZATION=unknown
NETDATA_SYSTEM_VIRT_DETECTION=none
NETDATA_SYSTEM_CONTAINER=unknown
NETDATA_SYSTEM_CONTAINER_DETECTION=none
```

i.e. If Netdata cannot detect the virtualization then it treats the detection as the host system.

**Comment by amoss** [comment]
Initial testing results from running in a custom container:
```
	"os_name": "Debian GNU/Linux",
	"os_id": "debian",
	"os_id_like": "",
	"os_version": "10 (buster)",
	"os_version_id": "10",
	"os_detection": "/host/etc/os-release",
	"container_os_name": "Ubuntu",
	"container_os_id_like": "debian",
	"container_os_version": "20.04 LTS (Focal Fossa)",
	"container_os_version_id": "20.04",
	"container_os_detection": "/etc/os-release",
	"kernel_name": "Linux",
	"kernel_version": "4.19.0-6-amd64",
	"architecture": "x86_64",
	"virtualization": "unknown",
	"virt_detection": "none",
	"container": "docker",
	"container_detection": "dockerenv",
	"host_labels": {
		"_is_master": "false",
		"_container": "none",
		"_virtualization": "unknown",
		"_architecture": "x86_64",
		"_kernel_version": "4.19.0-6-amd64",
		"_os_version": "10 (buster)",
		"_os_name": "Debian GNU/Linux"
	},
```
This indicates that the script is working, the environmental variable interface is correct, the storage and export over the web API works and the host labels code needs to be updated.

**Comment by amoss** [comment]
Fixed the bugs in the auto host labels, this is the final state of the `/api/v1/info` query. This is highly redundant - we should have discussion about deprecating everything outside of the host_labels dictionary and put everything inside there in a consistent way.
```
	"os_name": "Debian GNU/Linux",
	"os_id": "debian",
	"os_id_like": "",
	"os_version": "10 (buster)",
	"os_version_id": "10",
	"os_detection": "/host/etc/os-release",
	"container_os_name": "Ubuntu",
	"container_os_id_like": "debian",
	"container_os_version": "20.04 LTS (Focal Fossa)",
	"container_os_version_id": "20.04",
	"container_os_detection": "/etc/os-release",
	"kernel_name": "Linux",
	"kernel_version": "4.19.0-6-amd64",
	"architecture": "x86_64",
	"virtualization": "unknown",
	"virt_detection": "none",
	"container": "docker",
	"container_detection": "dockerenv",
	"host_labels": {
		"_is_master": "false",
		"_virt_detection": "none",
		"_container_detection": "dockerenv",
		"_container": "docker",
		"_virtualization": "unknown",
		"_architecture": "x86_64",
		"_kernel_version": "4.19.0-6-amd64",
		"_os_version": "10 (buster)",
		"_os_name": "Debian GNU/Linux"
	},
```
For comparison here is the same section from a bare-metal host:
```
	"os_name": "Debian GNU/Linux",
	"os_id": "debian",
	"os_id_like": "unknown",
	"os_version": "10 (buster)",
	"os_version_id": "10",
	"os_detection": "/etc/os-release",
	"kernel_name": "Linux",
	"kernel_version": "4.19.0-6-amd64",
	"architecture": "x86_64",
	"virtualization": "none",
	"virt_detection": "systemd-detect-virt",
	"container": "unknown",
	"container_detection": "none",
	"host_labels": {
		"_is_master": "false",
		"_virt_detection": "systemd-detect-virt",
		"_container_detection": "none",
		"_container": "unknown",
		"_virtualization": "none",
		"_architecture": "x86_64",
		"_kernel_version": "4.19.0-6-amd64",
		"_os_version": "10 (buster)",
		"_os_name": "Debian GNU/Linux"
	},
```

**Comment by amoss** [comment]
Unexpected work that came up during this issue has increased the complexity estimate from 1 -> 3. This is recording what changed to help future planning:

* Proper testing required range of both VMs and docker images.
* Bugs that were in this area of the code but not within the scope of the task: FreeBSD detection, Virtualization detection, os_name quoting breaking the JSON, bug in the host labels that doesn't show up outside of containers.
* There is a patched Coverity false-positive in one of the procedures that is interesting enough to investigate further.
