### ISSUE TITLE
After good installation Dashboard are not available.

### ISSUE THREAD

**Issue by Gorgo126** [netdata/netdata#7491]
Hi,

Server : 
VPS with Ubuntu 16.04
Plesk are installed on this server.

------------------------------------------------------------------

I install NetData with the Online Installation Command : 
bash <(curl -Ss https://my-netdata.io/kickstart.sh)

All this installation seem to be done without errors.

I go to my browser at "MY-IP:19999" and I have an error connection time out.

Any idea about this problem ?

Thanks a lot !

**Comment by ilyam8** [comment]
Hi, it seems netdata is not running.

Have you checkes it?

> ps faxu | grep netdata

> I go to my browser at "MY-IP:19999" and I have an error connection time out.

If netdata is running the problem is likely firewall. I see you are trying to access it from remote pc.

**Comment by Gorgo126** [comment]
Result of # ps faxu | grep netdata : 

root      4145  0.0  0.0  12940  1072 pts/0    S+   14:14   0:00          \_ grep --color=auto netdata
netdata   2754  0.9  1.6 241492 32788 ?        Ssl  14:07   0:03 /usr/sbin/netdata -P /var/run/netdata/netdata.p                          id -D -W set global process scheduling policy keep -W set global OOM score keep
netdata   2938  0.0  0.1   9768  2736 ?        S    14:07   0:00  \_ bash /usr/libexec/netdata/plugins.d/tc-qos-                          helper.sh 1
netdata   2940  1.1  0.2  17576  4164 ?        S    14:07   0:04  \_ /usr/libexec/netdata/plugins.d/apps.plugin                           1
netdata   2950  0.0  0.8 124824 16476 ?        Sl   14:07   0:00  \_ /usr/libexec/netdata/plugins.d/go.d.plugin                           1
netdata   2972  0.2  2.6 117116 53284 ?        Sl   14:07   0:00  \_ /usr/bin/python /usr/libexec/netdata/plugin                          s.d/python.d.plugin 1

- Yes I rent a VPS and I access it from my personal computer.

I check the firewall...

**Comment by Gorgo126** [comment]
Yep it's my Firewall, all work perfectly now :-)

Thanks a lot !
