### ISSUE TITLE
Netdata update overwrites my `python.d` collector modifications

### ISSUE THREAD

**Issue by petecooper** [netdata/netdata#7496]
##### Question summary

How can I stop Netdata overwriting my `python.d` collector updates on update?

##### OS / Environment

Ubuntu 18.04 LTS

##### Component Name

`python.d` collectors, I use Nginx and PHP.

##### Expected results

When I install Netdata, I update the Nginx collector to the following:

```
update_every: 1
priority: 90100
local:
url: 'http://127.0.0.1:81/stub_status'
```

I set an update check in cron:

```
41 21 * * * bash /usr/libexec/netdata/netdata-updater.sh
```

When Netdata updates, it appears to overwrite the Nginx collector modifications, and restores the default version.

I would be grateful if you could advise on where I am going wrong.

Thank you in advance.

**Comment by stelfrag** [comment]
Hi @petecooper 

This is probably related to #7367 -- please check that you don't modify the stock configuration file

Check here [Configuration guide](https://docs.netdata.cloud/docs/configuration-guide/)

**Comment by petecooper** [comment]
Thanks @stelfrag - perfect.
