### ISSUE TITLE
Virtual network interface speed is UNDEFINED from netdata alarm

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7497]
#### Summary

Like the VPN virtual NIC interface, what I see from the alarm of netdata, is UNDEFINED as below:
![image](https://user-images.githubusercontent.com/22472752/70606286-19367600-1c37-11ea-8731-55c537d5c8e1.jpeg)

we know the virtual interface by default is defined as 10Mbps(can verify by ethtool), but is there anyway we can fine-tune this to reflect the reality?

**Comment by ilyam8** [comment]
Hi @startryst 

You can check that there is `nic_speed_max` variable with **current** nic speed (yes, it is current, not max) in the `/api/v1/chart?chart=net.IFACE_NAME` response

> http://127.0.0.1:19999/api/v1/chart?chart=net.enp0s3

See `chart_variables` section

```json
{
    "nic_speed_max": 1000
}
```

And you can see it `Alarms->All` section

<img width="867" alt="Screenshot 2019-12-11 at 17 30 21" src="https://user-images.githubusercontent.com/22274335/70630032-f064af80-1c3b-11ea-848a-4cf0f50fa169.png">


___

But you are right, there is hyphen instead of value in the `Alarms->Log`.

<img width="868" alt="Screenshot 2019-12-11 at 17 32 23" src="https://user-images.githubusercontent.com/22274335/70630181-33bf1e00-1c3c-11ea-8599-a65125182288.png">


___

@thiagoftsm please check if it is a bug or feature

**Comment by ilyam8** [comment]
@startryst just wondering, why it is important for you? Do you use alarm log somehow?

**Comment by startryst** [comment]
> @startryst just wondering, why it is important for you? Do you use alarm log somehow?

@ilyam8 I read your above suggestions, and actually my use case is a bit simple, for the virtual network interface(or physical) I would like to raise an alarm if the actually speed over certain threshold, like below(when over 2Mbps), I can observe that from the datashboard, but I wish to know how can I define the threshold in netdata to raise the alarm:

![image](https://user-images.githubusercontent.com/22472752/70677095-1be1ab80-1cc9-11ea-95d3-084b64a29f46.jpeg)

BTW, from the api path you mentioned above, I saw green and red with null, is that one I should look into?

"nic_speed_max": 1000.00000
			},
			"**green": null**,
			"**red": null**,
			"alarms": {
				"1m_sent_traffic_overflow": {
					"id": 1574859480,
					"status": "CLEAR",
					"units": "%",
					"update_every": 10
				},
				"1m_received_traffic_overflow": {
					"id": 1574859479,
					"status": "CLEAR",
					"units": "%",
					"update_every": 10
				},
				"interface_speed": {
					"id": 1574859478,
					"status": "UNDEFINED",
					"units": "Mbit",
					"update_every": 10
				}
			}
		}

**Comment by startryst** [comment]
I think I figure it out:
`# -----------------------------------------------------------------------------`
`# check for speed over threshold`
`template: over_1m_2m`
`      on: net.net`
`families: virtual_int1 virtual_int2`
`  lookup: average -1m absolute foreach received,sent`
`   units: Kbps`
`   every: 1m`
`    warn: $this > 2000`
`    crit: $this > 3000`
`      to: sysadmin`

The unit of received/sent, is Kbps? instead of Mbps, right? This can't be adjusted?

**Comment by ilyam8** [comment]
yes, `kilobits/s`

> This can't be adjusted?

What do you need to adjust?

**Comment by startryst** [comment]
> yes, `kilobits/s`
> 
> > This can't be adjusted?
> 
> What do you need to adjust?

OK, I get it, I need to / by 1000 if I prefer use Mbps.

Another separate thing check with you, if I try to consolidate all the three NIC's bandwidth utilization all together for the last minutes, to see if it over certain threshold, I tried below warn, but looks not effective, any suggestions?
`warn: ($this + $net.vnic2.received + $net.vnic3.received) > 20000`
@ilyam8

**Comment by ilyam8** [comment]
I dont really know, there is no clear way how to do it, probably some hack 🤔 

@vlvkobal @thiagoftsm ?

**Comment by thiagoftsm** [comment]
I do not think it is possible to do this right now, but we are already planing to bring in the future a integration of alarms and this means integration among variables of other charts.

**Comment by ilyam8** [comment]
To make [this](https://github.com/netdata/netdata/issues/7497#issuecomment-564881730) possible we need some dummy alarms.

Example.

I have:
 - alarm1 counts bw of eth0 
 - alarm2 counts bw of eth1
 - alarm3 counts bw of eth2

And i need a sum alarm - it is not connected to any chart, it justs calculates $alarm1 + $alarm2 + $alarm3 and checks the value in warn/crit.

**Comment by startryst** [comment]
I tried multiple times, but found the below one works:
`   alarm: Receiving_Bandwidth_Over_Subscribed`
`      on: net.vnic1`
`  lookup: average -1m absolute of received`
`    calc: $this/1000 + $net.vnic2.received/1000 + $net.vnic3.received/1000`
`   units: Mbps`
`   every: 1m`
`    warn: $this > 7`
`    crit: $this > 10`
`      to: sysadmin`
Which sum the receiving bandwidth of 1 minutes from vnic1, vnic2 and vnic3, if the combined bandwidth over 7Mbps, then raise the warn, 10Mbps raise the critical.

From what I tested/observed, it's working, anything wrong?

@thiagoftsm @ilyam8

**Comment by ilyam8** [comment]
Cool if it works, consider to use `delay` option

> https://docs.netdata.cloud/health/reference/#alarm-line-delay

**Comment by startryst** [comment]
> Cool if it works, consider to use `delay` option
> 
> > https://docs.netdata.cloud/health/reference/#alarm-line-delay

For the delay, it just to 'delay' the alarm notification sent by alarm-notify.sh, or i can reduce the alarm notification?

As you see below, the alarm are flapping between WARNING and CRITICAL, after a few times, it back to CLEAR, so how I can stop the all of those flapping WARNING and CRITICAL flapping, what I need is the first time when it get warned/criticaled, and the when it back to CLEAR, the middle ones are not necessary. I believe delay is not parameter to achieve this?

![image](https://user-images.githubusercontent.com/22472752/70798205-4b83d700-1de1-11ea-9da6-4bc569e33ff7.jpeg)

**Comment by ilyam8** [comment]
> For the delay, it just to 'delay' the alarm notification sent by alarm-notify.sh

Yes, it still will be flapping in logs. 

You can use something like this to reduce flapping

https://github.com/netdata/netdata/blob/dd8b13dd570f002bf31f901cf24516119ec8280c/health/health.d/wmi.conf#L11-L12

**Comment by ilyam8** [comment]
```
warn: (($status >= $WARNING)  ?  7 : 3)
crit: (($status == $CRITICAL) ? 10 : 5)
```

**Comment by startryst** [comment]
> warn: (($status >= $WARNING)  ?  7 : 3)
> crit: (($status == $CRITICAL) ? 10 : 5)

My previous setting is warn when greater than 5, critical when greater than 7, so based on your suggestion , should I use:

warn: (($status >= $WARNING)  ?  3 : 5)
crit: (($status == $CRITICAL) ? 5 : 7)

**Comment by ilyam8** [comment]
yes, you are right 😓
