### ISSUE TITLE
tomcat requests not showing in dashboard graph but other graph like jvm memory is showing clearly. 

### ISSUE THREAD

**Issue by somir** [netdata/netdata#7499]

**Comment by ilyam8** [comment]
Hi @somir 

could you run tomcat in debug mode and share the output

See

> https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-debug-a-python-module

**Comment by somir** [comment]
Please find the output below:

[root@ip-192-168-10-232 tmp]# /usr/libexec/netdata/plugins.d/python.d.plugin tomcat debug trace
2019-12-11 10:37:57: python.d INFO: plugin[main] : using python v2
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : [tomcat] looking for 'tomcat.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : [tomcat] loading '/etc/netdata/python.d/tomcat.conf'
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : [tomcat] '/etc/netdata/python.d/tomcat.conf' is loaded
2019-12-11 10:37:57: python.d INFO: plugin[main] : [tomcat] built 3 job(s) configs
2019-12-11 10:37:57: python.d DEBUG: plugin[main] : tomcat[localhost] was previously active, applying recovering settings
2019-12-11 10:37:57: python.d DEBUG: tomcat[localhost] : urllib3 version: 1.10.2
2019-12-11 10:37:57: python.d INFO: plugin[main] : tomcat[localhost] : check success
CHART netdata.runtime_tomcat_local '' 'Execution time for tomcat_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2019-12-11 10:37:57: python.d DEBUG: tomcat[localhost] : started, update frequency: 1
2019-12-11 10:37:57: python.d INFO: plugin[main] : tomcat[localipv4] : already served by another job, skipping it
2019-12-11 10:37:57: python.d INFO: plugin[main] : tomcat[localipv6] : already served by another job, skipping it
CHART tomcat_local.jvm_survivor '' 'Survivor Memory Usage' 'MiB' 'memory' 'tomcat.jvm_survivor' area 60006 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'survivor_used' 'used' absolute 1 1048576 ' '
DIMENSION 'survivor_committed' 'committed' absolute 1 1048576 ' '
DIMENSION 'survivor_max' 'max' absolute 1 1048576 ' '

BEGIN tomcat_local.jvm_survivor 0
SET 'survivor_used' = 0
SET 'survivor_committed' = 22020096
SET 'survivor_max' = 22020096
END

CHART tomcat_local.processing_time '' 'processing time' 'seconds' 'statistics' 'tomcat.processing_time' area 60002 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'processingTime' 'processing time' incremental 1 1000 ' '

BEGIN tomcat_local.processing_time 0
SET 'processingTime' = 0
END

CHART tomcat_local.jvm_eden '' 'Eden Memory Usage' 'MiB' 'memory' 'tomcat.jvm_eden' area 60005 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'eden_used' 'used' absolute 1 1048576 ' '
DIMENSION 'eden_committed' 'committed' absolute 1 1048576 ' '
DIMENSION 'eden_max' 'max' absolute 1 1048576 ' '

BEGIN tomcat_local.jvm_eden 0
SET 'eden_used' = 121281248
SET 'eden_committed' = 134742016
SET 'eden_max' = 313524224
END

CHART tomcat_local.accesses '' 'Requests' 'requests/s' 'statistics' 'tomcat.accesses' area 60000 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'requestCount' 'accesses' incremental 1 1 ' '
DIMENSION 'errorCount' 'errors' incremental 1 1 ' '

BEGIN tomcat_local.accesses 0
SET 'requestCount' = 0
SET 'errorCount' = 0
END

CHART tomcat_local.bandwidth '' 'Bandwidth' 'KiB/s' 'statistics' 'tomcat.bandwidth' area 60001 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'bytesSent' 'sent' incremental 1 1024 ' '
DIMENSION 'bytesReceived' 'received' incremental 1 1024 ' '

BEGIN tomcat_local.bandwidth 0
SET 'bytesSent' = 0
SET 'bytesReceived' = 0
END

CHART tomcat_local.threads '' 'Threads' 'current threads' 'statistics' 'tomcat.threads' area 60003 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'currentThreadCount' 'current' absolute 1 1 ' '
DIMENSION 'currentThreadsBusy' 'busy' absolute 1 1 ' '

BEGIN tomcat_local.threads 0
SET 'currentThreadCount' = 10
SET 'currentThreadsBusy' = 0
END

CHART tomcat_local.jvm '' 'JVM Memory Pool Usage' 'MiB' 'memory' 'tomcat.jvm' stacked 60004 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'free' 'free' absolute 1 1048576 ' '
DIMENSION 'eden_used' 'eden' absolute 1 1048576 ' '
DIMENSION 'survivor_used' 'survivor' absolute 1 1048576 ' '
DIMENSION 'tenured_used' 'tenured' absolute 1 1048576 ' '
DIMENSION 'code_cache_used' 'code cache' absolute 1 1048576 ' '
DIMENSION 'compressed_used' 'compressed' absolute 1 1048576 ' '
DIMENSION 'metaspace_used' 'metaspace' absolute 1 1048576 ' '

**Comment by ilyam8** [comment]
All available charts

https://github.com/netdata/netdata/blob/ae42f91c8b54b048bdf563b0a148a7d428feaff7/collectors/python.d.plugin/tomcat/tomcat.chart.py#L19-L28

You have 7/8 in your output (i see no only `jvm_tenured`)

Requests chart

https://github.com/netdata/netdata/blob/ae42f91c8b54b048bdf563b0a148a7d428feaff7/collectors/python.d.plugin/tomcat/tomcat.chart.py#L31-L37

should be on the dashboard

**Comment by somir** [comment]
My tomcat.chart.py file same as your shared but result is same, requests not showing till now. Please find the screenshot for your convenience. 

![Selection_014](https://user-images.githubusercontent.com/26133382/70681778-c99f8b00-1cc6-11ea-98b1-3984c53ef0ce.png)


**tomcat.chart.py file details.**
===========================================================
[root@ip-192-168-10-232 centos]# cat /usr/libexec/netdata/python.d/tomcat.chart.py
# -*- coding: utf-8 -*-
# Description: tomcat netdata python.d module
# Author: Pawel Krupa (paulfantom)
# Author: Wei He (Wing924)
# SPDX-License-Identifier: GPL-3.0-or-later

import xml.etree.ElementTree as ET
import re

from bases.FrameworkServices.UrlService import UrlService

MiB = 1 << 20

# Regex fix for Tomcat single quote XML attributes
# affecting Tomcat < 8.5.24 & 9.0.2 running with Java > 9
# cf. https://bz.apache.org/bugzilla/show_bug.cgi?id=61603
single_quote_regex = re.compile(r"='([^']+)'([^']+)''")

ORDER = [
    'accesses',
    'bandwidth',
    'processing_time',
    'threads',
    'jvm',
    'jvm_eden',
    'jvm_survivor',
    'jvm_tenured',
]

CHARTS = {
    'accesses': {
        'options': [None, 'Requests', 'requests/s', 'statistics', 'tomcat.accesses', 'area'],
        'lines': [
            ['requestCount', 'accesses', 'incremental'],
            ['errorCount', 'errors', 'incremental'],
        ]
    },
    'bandwidth': {
        'options': [None, 'Bandwidth', 'KiB/s', 'statistics', 'tomcat.bandwidth', 'area'],
        'lines': [
            ['bytesSent', 'sent', 'incremental', 1, 1024],
            ['bytesReceived', 'received', 'incremental', 1, 1024],
        ]
    },
    'processing_time': {
        'options': [None, 'processing time', 'seconds', 'statistics', 'tomcat.processing_time', 'area'],
        'lines': [
            ['processingTime', 'processing time', 'incremental', 1, 1000]
        ]
    },
    'threads': {
        'options': [None, 'Threads', 'current threads', 'statistics', 'tomcat.threads', 'area'],
        'lines': [
            ['currentThreadCount', 'current', 'absolute'],
            ['currentThreadsBusy', 'busy', 'absolute']
        ]
    },
    'jvm': {
        'options': [None, 'JVM Memory Pool Usage', 'MiB', 'memory', 'tomcat.jvm', 'stacked'],
        'lines': [
            ['free', 'free', 'absolute', 1, MiB],
            ['eden_used', 'eden', 'absolute', 1, MiB],
            ['survivor_used', 'survivor', 'absolute', 1, MiB],
            ['tenured_used', 'tenured', 'absolute', 1, MiB],
            ['code_cache_used', 'code cache', 'absolute', 1, MiB],
            ['compressed_used', 'compressed', 'absolute', 1, MiB],
            ['metaspace_used', 'metaspace', 'absolute', 1, MiB],
        ]
    },
    'jvm_eden': {
        'options': [None, 'Eden Memory Usage', 'MiB', 'memory', 'tomcat.jvm_eden', 'area'],
        'lines': [
            ['eden_used', 'used', 'absolute', 1, MiB],
            ['eden_committed', 'committed', 'absolute', 1, MiB],
            ['eden_max', 'max', 'absolute', 1, MiB]
        ]
    },
    'jvm_survivor': {
        'options': [None, 'Survivor Memory Usage', 'MiB', 'memory', 'tomcat.jvm_survivor', 'area'],
        'lines': [
            ['survivor_used', 'used', 'absolute', 1, MiB],
            ['survivor_committed', 'committed', 'absolute', 1, MiB],
            ['survivor_max', 'max', 'absolute', 1, MiB],
        ]
    },
    'jvm_tenured': {
        'options': [None, 'Tenured Memory Usage', 'MiB', 'memory', 'tomcat.jvm_tenured', 'area'],
        'lines': [
            ['tenured_used', 'used', 'absolute', 1, MiB],
            ['tenured_committed', 'committed', 'absolute', 1, MiB],
            ['tenured_max', 'max', 'absolute', 1, MiB]
        ]
    }
}


class Service(UrlService):
    def __init__(self, configuration=None, name=None):
        UrlService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.url = self.configuration.get('url', 'http://127.0.0.1:8080/manager/status?XML=true')
        self.connector_name = self.configuration.get('connector_name', None)
        self.parse = self.xml_parse

    def xml_parse(self, data):
        try:
            return ET.fromstring(data)
        except ET.ParseError:
            self.debug('%s is not a valid XML page. Please add "?XML=true" to tomcat status page.' % self.url)
            return None

    def xml_single_quote_fix_parse(self, data):
        data = single_quote_regex.sub(r"='\g<1>\g<2>'", data)
        return self.xml_parse(data)

    def check(self):
        self._manager = self._build_manager()

        raw_data = self._get_raw_data()
        if not raw_data:
            return False

        if single_quote_regex.search(raw_data):
            self.warning('Tomcat status page is returning invalid single quote XML, please consider upgrading '
                         'your Tomcat installation. See https://bz.apache.org/bugzilla/show_bug.cgi?id=61603')
            self.parse = self.xml_single_quote_fix_parse

        return self.parse(raw_data) is not None

    def _get_data(self):
        """
        Format data received from http request
        :return: dict
        """
        data = None
        raw_data = self._get_raw_data()
        if raw_data:
            xml = self.parse(raw_data)
            if xml is None:
                return None

            data = {}

            jvm = xml.find('jvm')

            connector = None
            if self.connector_name:
                for conn in xml.findall('connector'):
                    if self.connector_name in conn.get('name'):
                        connector = conn
                        break
            else:
                connector = xml.find('connector')

            memory = jvm.find('memory')
            data['free'] = memory.get('free')
            data['total'] = memory.get('total')

            for pool in jvm.findall('memorypool'):
                name = pool.get('name')
                if 'Eden Space' in name:
                    data['eden_used'] = pool.get('usageUsed')
                    data['eden_committed'] = pool.get('usageCommitted')
                    data['eden_max'] = pool.get('usageMax')
                elif 'Survivor Space' in name:
                    data['survivor_used'] = pool.get('usageUsed')
                    data['survivor_committed'] = pool.get('usageCommitted')
                    data['survivor_max'] = pool.get('usageMax')
                elif 'Tenured Gen' in name or 'Old Gen' in name:
                    data['tenured_used'] = pool.get('usageUsed')
                    data['tenured_committed'] = pool.get('usageCommitted')
                    data['tenured_max'] = pool.get('usageMax')
                elif name == 'Code Cache':
                    data['code_cache_used'] = pool.get('usageUsed')
                    data['code_cache_committed'] = pool.get('usageCommitted')
                    data['code_cache_max'] = pool.get('usageMax')
                elif name == 'Compressed':
                    data['compressed_used'] = pool.get('usageUsed')
                    data['compressed_committed'] = pool.get('usageCommitted')
                    data['compressed_max'] = pool.get('usageMax')
                elif name == 'Metaspace':
                    data['metaspace_used'] = pool.get('usageUsed')
                    data['metaspace_committed'] = pool.get('usageCommitted')
                    data['metaspace_max'] = pool.get('usageMax')

            if connector is not None:
                thread_info = connector.find('threadInfo')
                data['currentThreadsBusy'] = thread_info.get('currentThreadsBusy')
                data['currentThreadCount'] = thread_info.get('currentThreadCount')

                request_info = connector.find('requestInfo')
                data['processingTime'] = request_info.get('processingTime')
                data['requestCount'] = request_info.get('requestCount')
                data['errorCount'] = request_info.get('errorCount')
                data['bytesReceived'] = request_info.get('bytesReceived')
                data['bytesSent'] = request_info.get('bytesSent')

        return data or None
[root@ip-192-168-10-232 centos]# 

===========================================================

**Comment by somir** [comment]
Hi @ilyam8 

Please find the latest tomcat output (debug mode)....!!!

[root@ip-192-168-10-232 centos]# /usr/libexec/netdata/plugins.d/python.d.plugin tomcat debug trace
2019-12-12 04:30:37: python.d INFO: plugin[main] : using python v2
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : [tomcat] looking for 'tomcat.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : [tomcat] loading '/etc/netdata/python.d/tomcat.conf'
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : [tomcat] '/etc/netdata/python.d/tomcat.conf' is loaded
2019-12-12 04:30:37: python.d INFO: plugin[main] : [tomcat] built 3 job(s) configs
2019-12-12 04:30:37: python.d DEBUG: plugin[main] : tomcat[localhost] was previously active, applying recovering settings
2019-12-12 04:30:37: python.d DEBUG: tomcat[localhost] : urllib3 version: 1.10.2
2019-12-12 04:30:37: python.d INFO: plugin[main] : tomcat[localhost] : check success
CHART netdata.runtime_tomcat_local '' 'Execution time for tomcat_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2019-12-12 04:30:37: python.d DEBUG: tomcat[localhost] : started, update frequency: 1
2019-12-12 04:30:37: python.d INFO: plugin[main] : tomcat[localipv4] : already served by another job, skipping it
2019-12-12 04:30:37: python.d INFO: plugin[main] : tomcat[localipv6] : already served by another job, skipping it
CHART tomcat_local.jvm_survivor '' 'Survivor Memory Usage' 'MiB' 'memory' 'tomcat.jvm_survivor' area 60006 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'survivor_used' 'used' absolute 1 1048576 ' '
DIMENSION 'survivor_committed' 'committed' absolute 1 1048576 ' '
DIMENSION 'survivor_max' 'max' absolute 1 1048576 ' '

BEGIN tomcat_local.jvm_survivor 0
SET 'survivor_used' = 7437600
SET 'survivor_committed' = 22020096
SET 'survivor_max' = 22020096
END

CHART tomcat_local.processing_time '' 'processing time' 'seconds' 'statistics' 'tomcat.processing_time' area 60002 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'processingTime' 'processing time' incremental 1 1000 ' '

BEGIN tomcat_local.processing_time 0
SET 'processingTime' = 0
END

CHART tomcat_local.jvm_eden '' 'Eden Memory Usage' 'MiB' 'memory' 'tomcat.jvm_eden' area 60005 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'eden_used' 'used' absolute 1 1048576 ' '
DIMENSION 'eden_committed' 'committed' absolute 1 1048576 ' '
DIMENSION 'eden_max' 'max' absolute 1 1048576 ' '

BEGIN tomcat_local.jvm_eden 0
SET 'eden_used' = 109975688
SET 'eden_committed' = 134742016
SET 'eden_max' = 313524224
END

CHART tomcat_local.accesses '' 'Requests' 'requests/s' 'statistics' 'tomcat.accesses' area 60000 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'requestCount' 'accesses' incremental 1 1 ' '
DIMENSION 'errorCount' 'errors' incremental 1 1 ' '

BEGIN tomcat_local.accesses 0
SET 'requestCount' = 0
SET 'errorCount' = 0
END

CHART tomcat_local.bandwidth '' 'Bandwidth' 'KiB/s' 'statistics' 'tomcat.bandwidth' area 60001 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'bytesSent' 'sent' incremental 1 1024 ' '
DIMENSION 'bytesReceived' 'received' incremental 1 1024 ' '

BEGIN tomcat_local.bandwidth 0
SET 'bytesSent' = 0
SET 'bytesReceived' = 0
END

CHART tomcat_local.threads '' 'Threads' 'current threads' 'statistics' 'tomcat.threads' area 60003 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'currentThreadCount' 'current' absolute 1 1 ' '
DIMENSION 'currentThreadsBusy' 'busy' absolute 1 1 ' '

BEGIN tomcat_local.threads 0
SET 'currentThreadCount' = 10
SET 'currentThreadsBusy' = 0
END

CHART tomcat_local.jvm '' 'JVM Memory Pool Usage' 'MiB' 'memory' 'tomcat.jvm' stacked 60004 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'free' 'free' absolute 1 1048576 ' '
DIMENSION 'eden_used' 'eden' absolute 1 1048576 ' '
DIMENSION 'survivor_used' 'survivor' absolute 1 1048576 ' '
DIMENSION 'tenured_used' 'tenured' absolute 1 1048576 ' '
DIMENSION 'code_cache_used' 'code cache' absolute 1 1048576 ' '
DIMENSION 'compressed_used' 'compressed' absolute 1 1048576 ' '
DIMENSION 'metaspace_used' 'metaspace' absolute 1 1048576 ' '

BEGIN tomcat_local.jvm 0
SET 'free' = 397437528
SET 'eden_used' = 109975688
SET 'survivor_used' = 7437600
SET 'tenured_used' = 0
SET 'code_cache_used' = 11313664
SET 'metaspace_used' = 19144640
END

CHART tomcat_local.jvm_tenured '' 'Tenured Memory Usage' 'MiB' 'memory' 'tomcat.jvm_tenured' area 60007 1 '' 'python.d.plugin' 'tomcat'
DIMENSION 'tenured_used' 'used' absolute 1 1048576 ' '
DIMENSION 'tenured_committed' 'committed' absolute 1 1048576 ' '
DIMENSION 'tenured_max' 'max' absolute 1 1048576 ' '

BEGIN tomcat_local.jvm_tenured 0
SET 'tenured_used' = 0
SET 'tenured_committed' = 358088704
SET 'tenured_max' = 716177408
END

BEGIN netdata.runtime_tomcat_local 0
SET run_time = 4
END

**Comment by ilyam8** [comment]
> requests not showing

I see they are showing on your screenshot. Do you mean the problem is zero values?

**Comment by somir** [comment]
Hi @ilyam8,
Do you mean the problem is zero values?----- Yes but not sure why it showing 0 value. 
No error message in my NetData, testing Apache on same machine & it's working fine and showing all data. 

FYI, my tomcat application concurrent users is above 10+/sec. , can you please tell me why it showing zero values? 

BR//
Somir

**Comment by ilyam8** [comment]
Can you share

> http://127.0.0.1:8080/manager/status?XML=true

output?

**Comment by somir** [comment]
Hi @ilyam8,

Please find the bellow link for your convenience. 

![Selection_015](https://user-images.githubusercontent.com/26133382/70690323-ab468900-1ce0-11ea-8ab3-046ef4214849.png)

**Comment by ilyam8** [comment]
Well, you need to authenticate to get access to the data.

**Comment by somir** [comment]
HI @ilyam8,
Thanks...
According to your suggestions I passed the credentials in netdata tomcat.conf file but maybe it's didn't take credentials automatically. Can please help me regarding this issue.
![Selection_016](https://user-images.githubusercontent.com/26133382/70701788-27e46200-1cf7-11ea-90f5-10b53f07b943.png)

tomcat.conf file details:
================================

localhost:
  name : 'local'
  url  : 'http://localhost:8080/manager/status?XML=true'
  user : 'admin'
  pass : 'admin'


localipv4:
  name : 'local'
  url  : 'http://127.0.0.1:8080/manager/status?XML=true'
  user : 'admin'
  pass : 'admin'


localipv6:
  name : 'local'
  url  : 'http://[::1]:8080/manager/status?XML=true'
  user : 'admin'
  pass : 'admin'

**Comment by ilyam8** [comment]
it seems it works since you see `tomcat` on the dashboard.

I want to see 'http://127.0.0.1:8080/manager/status?XML=true' output, otherwise it is not clear why some metrics have zero value.

**Comment by somir** [comment]
Please find the bellow screen shot. FYI, till now I am same state.
Note: use w3m cli web browser.

![Selection_017](https://user-images.githubusercontent.com/26133382/70702946-4f3c2e80-1cf9-11ea-9e21-67aae69d24e2.png)
![Selection_018](https://user-images.githubusercontent.com/26133382/70702952-519e8880-1cf9-11ea-80d6-92a47614285e.png)

**Comment by ilyam8** [comment]
Could you copy the response and post it? I need the text

**Comment by somir** [comment]
Output like in cli mode:
--------------------------------------------
<status><jvm><memory free='433389288' total='514850816' max='954728448'/><memorypool name='PS Eden Space' type='Heap memory' usageInit='134742016' usageCommitted='134742016' usageMax='313524224' usageUsed='74094744'/><memorypool name='PS Old Gen' type='Heap memory' usageInit='358088704' usageCommitted='358088704' usageMax='716177408' usageUsed='0'/><memorypool name='PS Survivor Space' type='Heap memory' usageInit='22020096' usageCommitted='22020096' usageMax='22020096' usageUsed='7366784'/><memorypool name='Code Cache'

Output thought web using real ip:
------------------------------------------------
![Selection_019](https://user-images.githubusercontent.com/26133382/70705709-b6a8ad00-1cfe-11ea-9105-d508c09bb42e.png)

**Comment by ilyam8** [comment]
I dont need screenshot, i need actual data. 

Please do (dont forget to change ip if needed)

> view-source:http://127.0.0.1:8080/manager/status?XML=true

**Comment by somir** [comment]
Please find the output for your convenience.
==============================================
"Tomcat Status
JVM:	free:396244736	total:514850816	max:954728448
Memory Pools
Name:PS Eden Space	Type:Heap memory	Initial:134742016	Committed:134742016	Maximum:313524224	Used:118606080
Name:PS Old Gen	Type:Heap memory	Initial:358088704	Committed:358088704	Maximum:716177408	Used:0
Name:PS Survivor Space	Type:Heap memory	Initial:22020096	Committed:22020096	Maximum:22020096	Used:0
Name:Code Cache	Type:Non-heap memory	Initial:2555904	Committed:6488064	Maximum:251658240	Used:6471680
Name:Compressed Class Space	Type:Non-heap memory	Initial:0	Committed:2097152	Maximum:1073741824	Used:1911400
Name:Metaspace	Type:Non-heap memory	Initial:0	Committed:18874368	Maximum:-1	Used:18336120
Connector -- "ajp-nio-8009"
threadInfo	maxThreads:200	currentThreadCount:10	currentThreadsBusy:0
requestInfo 	maxTime:0	processingTime:0	requestCount:0	errorCount:0	bytesReceived:0	bytesSent:0
Stage	Time	B Sent	B Recv	Client	VHost	Request
Connector -- "http-nio-8080"
threadInfo	maxThreads:200	currentThreadCount:10	currentThreadsBusy:1
requestInfo 	maxTime:149	processingTime:364	requestCount:56	errorCount:1	bytesReceived:0	bytesSent:119650"

**Comment by ilyam8** [comment]
ok, you need this option

https://github.com/netdata/netdata/blob/53ab093d84919c743450199a31bca9a13412e451/collectors/python.d.plugin/tomcat/tomcat.conf#L71-L73

```yaml
localhost:
  name: 'local'
  url: 'http://localhost:8080/manager/status?XML=true'
  connector_name: http-nio-8080
```

**Comment by ilyam8** [comment]
Not a tomcat user, probably we need to chart all connectors 🤷‍♂ 

@Wing924 what do you think? does it make sense?

**Comment by ilyam8** [comment]
@somir 

https://github.com/netdata/netdata/issues/7499#issuecomment-566088182 is the fix, so i am closing the issue

**Comment by somir** [comment]
Hi @ilyam8 
I added the bellow option in tomcat.conf file but result is same. FYI, my URL is password protected. Can you please review again my problem?

@Wing924, Can you please looking my problem?

Current config file details:
-----------------------------------------
localhost:
  name : 'local'
  url  : 'http://localhost:8080/manager/status?XML=true'
  user : 'admin'
  pass : 'admin'

localipv4:
  name : 'local'
  url  : 'http://127.0.0.1:8080/manager/status?XML=true'
  user : 'admin'
  pass : 'admin'

localipv6:
  name : 'local'
  url  : 'http://[::1]:8080/manager/status?XML=true'
  user : 'admin'
  pass : 'admin'

localhost:
  name: 'local'
  url: 'http://localhost:8080/manager/status?XML=true'
  connector_name: http-nio-8080

**Comment by ilyam8** [comment]
> my URL is password protected

then add user/pass


```yaml
localhost:
  name: 'local'
  url: 'http://localhost:8080/manager/status?XML=true'
  connector_name: http-nio-8080
  user: 'admin'
  pass: 'admin'
```

and remove other jobs

**Comment by ilyam8** [comment]
@somir you managed to get it working, right?
