### ISSUE TITLE
How to check if there are any actual running modules of a plugin, thus we would know if we really need that plugin enabled?

### ISSUE THREAD

**Issue by nicknaychov** [netdata/netdata#7505]
This is important especially during the current migration from python to go plugin modules. I would like possibly to disable python plugin, but not sure how to check if there are any modules using that plugin, so I can safely disable it.
Could not find anywhere in the docs info about that. 
Thanks

**Comment by ilyam8** [comment]
Hi @nicknaychov 

> but not sure how to check if there are any modules using that plugin

These modules are standalone modules, you can see the list of running modules on your server in the two places:

 - `/api/v1/info` response (see `collectors` section), it contains all running collectors, not only python
 - netdata dashboard: `Netdata monitoring -> python.d`

**Comment by nicknaychov** [comment]
this is go.d.conf
`# netdata go.d.plugin configuration
#
# This file is in YaML format.

# Enable/disable the whole go.d.plugin.
enabled: yes

# Enable/disable default value for all modules.
default_run: yes

# Maximum number of used CPUs. Zero means no limit.
max_procs: 0

# Enable/disable specific g.d.plugin module
modules:
#  activemq: yes
apache: yes
#  bind: yes
#  consul: yes
#  coredns: yes
#  dns_query: yes
#  docker_engine: yes
#  dockerhub: yes
#  example: no
#  freeradius: yes
#  httpcheck: yes
#  k8s_kubelet: yes
#  k8s_kubeproxy: yes
#  lighttpd: yes
#  lighttpd2: yes
#  logstash: yes
mysql: yes
#  nginx: yes
#  openvpn: yes
#  portcheck: yes
#  rabbitmq: yes
#  scaleio: yes
#  solr: yes
#  springboot2: yes
#  tengine: yes
#  vsphere: yes
web_log: yes
#  wmi: yes
#  x509check: yes`

but i still get
`
2019-12-16 17:05:47: go.d INFO: main[main] module 'mysql' disabled by default`

**Comment by ilyam8** [comment]
ok, should be

```yaml
modules:
#  activemq: yes
  apache: yes # <- space before apache
```

**Comment by ilyam8** [comment]
i need to add that info to the go.d.conf, it is 3rd time i see this problem 😄
