### ISSUE TITLE
Introduce bytes transferred counter

### ISSUE THREAD

**Issue by lucasRolff** [netdata/netdata#7508]
##### Feature idea summary

With the introduction of the dbengine, it also means we're able to store data for a longer period of time, such as days, weeks, months or even years.

I'd like to request the feature of getting the bytes transferred (over individual interfaces) exposed as a counter, so we'll be able to see how much X interface did transfer in the last minute, hour, day, week, month etc.

The reason I'm specifically requesting a counter is that tons of already existing software such as other TSDB backends support generating the charts and metrics based on the network counter.

Looking at the `proc_net_dev.c` I see that the bytes are already used to calculate the bandwidth ( https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_net_dev.c#L626-L627 ) - so I think implementing it would be relatively simple.

We're moving from other monitoring solutions, solely to use netdata (With prometheus as a backend for long term storage), one thing we need to measure is the traffic over a given interface over a period of time.

Now, I can get this from the node_exporter provided by Prometheus, but I'd like to avoid using another piece of software to monitor a single thing.

##### Expected behavior

- Expose bytes transferred per interface as a counter

**Comment by Ferroin** [comment]
While it's not directly exposed as a gauge, you can get the equivalent data with a REST query to `api/v1/data`. See [the docs](https://docs.netdata.cloud/web/api/queries/) for details on query parameters.

If, for example, your first interface is named `eth0`, the path and query string:

    api/v1/data?chart=net.eth0&after=-3600&points=60&group=sum

Will get you a JSON response similar to:

```json
{
 "labels": ["time", "received", "sent"],
    "data":
 [
      [ 1576162140, 215.1493375, -687.0525538],
      [ 1576162080, 948.6841644, -3040.3962336],
      [ 1576162020, 1717.9824865, -5144.2331416],
      [ 1576161960, 1194.4960435, -9231.5226206],
      [ 1576161900, 123.5332215, -197.2640064],
      [ 1576161840, 146.626781, -234.5519982],
      [ 1576161780, 153.0479997, -250.6159995],
      [ 1576161720, 129.6080014, -197.2400042],
      [ 1576161660, 172.3242131, -256.6799922],
      [ 1576161600, 143.8997897, -195.2640048],
      [ 1576161540, 145.064001, -230.4240005],
      [ 1576161480, 160.9218217, -210.3119995],
      [ 1576161420, 146.8882244, -386.7040035],
      [ 1576161360, 192.6319063, -253.8158827],
      [ 1576161300, 81.2274891, -171.2955097],
      [ 1576161240, 157.4425605, -243.3925984],
      [ 1576161180, 185.8720008, -248.2399971],
      [ 1576161120, 121.0639994, -203.0332753],
      [ 1576161060, 273.9519992, -243.2861354],
      [ 1576161000, 143.4560015, -177.1069592],
      [ 1576160940, 294.5811473, -836.3736407],
      [ 1576160880, 246.5930249, -325.9030757],
      [ 1576160820, 253.327479, -3034.3848814],
      [ 1576160760, 188.1937267, -256.3840014],
      [ 1576160700, 188.0775406, -226.599051],
      [ 1576160640, 272.3710765, -294.0890558],
      [ 1576160580, 160.1679938, -204.3998868],
      [ 1576160520, 127.0880018, -195.0239989],
      [ 1576160460, 117.8959957, -233.552002],
      [ 1576160400, 253.8000048, -3280.5477589],
      [ 1576160340, 175.8188907, -247.6928076],
      [ 1576160280, 164.7891074, -206.9924329],
      [ 1576160220, 112.9680008, -175.8778754],
      [ 1576160160, 327.6800066, -371.2744731],
      [ 1576160100, 589.16019, -490.4652902],
      [ 1576160040, 239.2878269, -312.3104305],
      [ 1576159980, 239.2483224, -323.8017309],
      [ 1576159920, 645.1585483, -670.9900576],
      [ 1576159860, 123.906841, -254.0167044],
      [ 1576159800, 287.4542857, -339.1453817],
      [ 1576159740, 159.9585178, -254.8266135],
      [ 1576159680, 172.329469, -206.6701008],
      [ 1576159620, 187.1840061, -287.1790407],
      [ 1576159560, 362.9600109, -472.3452521],
      [ 1576159500, 88.2720006, -192.5599998],
      [ 1576159440, 236.8000077, -243.6468642],
      [ 1576159380, 154.1760018, -200.5611345],
      [ 1576159320, 179.3279955, -209.423048],
      [ 1576159260, 201.9999975, -255.2169576],
      [ 1576159200, 152.544, -192.8800019],
      [ 1576159140, 62403.9050732, -2575.7175647],
      [ 1576159080, 175.4160005, -202.3909515],
      [ 1576159020, 179.2720016, -219.8696728],
      [ 1576158960, 165.3360053, -252.3153135],
      [ 1576158900, 344.3840009, -181.8505307],
      [ 1576158840, 220.7120039, -295.9120017],
      [ 1576158780, 239.0996421, -208.8546458],
      [ 1576158720, 333.5563551, -215.8584597],
      [ 1576158660, 340.5223535, -267.2759381],
      [ 1576158600, 256.3176497, -188.4072256]
  ]
}
```

In that response, each entry in the `"data"` array represents a single minute in the past hour, with the first item being a timestamp, the second being aggregate bytes received over that minute, and the third being the aggregate bytes sent.

**Comment by ilyam8** [comment]
Btw these negative numbers are not good. We make the value negative so that it looks better on the dashboard and it is common practice. But it looks weird outside of netdata (exporting, rest api responses)

**Comment by lucasRolff** [comment]
Hi @Ferroin 

I modified my title to be a counter instead of a gauge (I've taken another cup of coffee in the meantime).

So what I'm **actually** looking for is a counter, so we don't have the issue that @ilyam8 describes as well - then as long as the graphing software can work with counters (which is also rather common these days), we will be able to produce the stats we need.

While I like the rest API result above, it also means I'll have to fetch data over a period of time - working with counters can often be easier.

**Comment by ilyam8** [comment]
> exposed as a counter

To make counter metrics meaningful on the netdata dashboard we use `incremental` algorithm for dimensions. Netdata does interpolation and store interpolated delta, not actual value in that case. 

I agree with you that it would be nice.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
