### ISSUE TITLE
Netdata agent component diagram

### ISSUE THREAD

**Issue by OdysLam** [netdata/netdata#7512]
Hey everyone,

In an effort to understand better how Netdata works, I created the following diagram from reverse-engineering the docs and the source code. 

![netdata agent diagram](https://www.lucidchart.com/publicSegments/view/bb5c6b86-7e17-4604-a441-212409c9383b/image.png)

It is probably highly inaccurate, thus I am asking for positive feedback in order to correct it.

You can find the diagram on [lucidchart](https://www.lucidchart.com/invitations/accept/0463cd8d-946a-4d18-9ef0-15d145fa1183) or you can comment here.

**Comment by ilyam8** [comment]
Hi @OdysLam 

I think following will be useful

https://github.com/netdata/netdata#infographic

**Comment by OdysLam** [comment]
Yes it was, but it was a bit too high-level and too crowded, I was more interested for actual discreet software components.

**Comment by Ferroin** [comment]
@OdysLam If you're looking at discrete components, then I think you probably have things pretty well covered already (or, put differently, what you've got already matches up with my understanding of how everything goes together).

**Comment by amoss** [comment]
PlantUML would make it easier for you. It works on a simple description file that is automatically rendered instead of manually laying out diagrams. There are details on how to write this kind of diagram at https://plantuml.com/component-diagram

There is an online editor / renderer, or the offline version is a java `.jar `that processes the description locallly and outputs a `.png`

**Comment by OdysLam** [comment]
Hey @Ferroin , thanks for that. Now that I think of it, I think that web-gui should be a higher stack of threads to illustrate the arbitrary number of threads that can be set by the user.

@amoss, to be honest, I thought about UML but I opted for a simpler diagram that would serve to give an overview, rather than formally defining the components for a specification-level document. Thank you for pointing out that tool, will definitely check it out 🙏.

On that topic, I prefer manual designing the diagram because it gives me the chance to understand what I am building, as I am building it. _Paragon_ is a very good tool for professional UML diagrams.

**Comment by ilyam8** [comment]
This `lucidchart` thing is not free, cosider to use [draw.io](https://www.draw.io/). A little bit lame for UMLs, but free and you can share 😄

**Comment by OdysLam** [comment]
@ilyam8 - It is free, if you have a student account 😜. (I used to use `draw.io`, until I found out about that student account thing).

Here is the `draw.io` link, editable: https://drive.google.com/file/d/1g2yUsXf9iTrkAYpvjmDuM4xKyUhYo_0i/view?usp=sharing
