### ISSUE TITLE
Integration testing of the labels branch.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7514]
This covers the integration testing of merging the labels branch back into master.

Please document the tests used in comments in this issue.

Timeboxed task: 0.5 days each.

**Comment by thiagoftsm** [comment]
For alarms, it is necessary to do the following tests:

1 - Get an alarm, for example, I used this:
```
 alarm: dev_dim_template_user
    on: system.cpu
    os: linux
lookup: sum -3s at 0 every 3 percentage of user
 units: %
 every: 1s
  warn: $this > 1
  crit: $this > 4
 label: label1 = 123 
```

and I changed netdata.conf to

```
[host labels]
        label1 = 123
        label2 =456
        label3= 789
```

2 - I run netdata to confirm I had alarms.
3 - change label1 = 123 to invalid value label1 = 123456, I cannot have alarms
4 - Use only the label name inside label:, for example, label1 I will have alarms again.
5 - Use simple patterns with label:, for example label* instead label1
6 - Change the previous lookup line for one with foreach:
lookup: sum -3s at 0 every 3 percentage foreach system,user,nice
I must have alarms again
7 - Change alarm: to template: I also need to have alarms.

**Comment by thiagoftsm** [comment]
Now to test values from config file, we need to create labels that respect the restrictions created on #7410 , I used labels like this:

```
# This must be accepted
label_test = 123 
# The next must be rejected
_internal = Only netdata can use _ as first character
ãçü = Cannot have values that are not ascii
Математик = neither this are allowed.
```
