### ISSUE TITLE
netdata : user NOT in sudoers ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=/usr/sbin/ipsec whack --trafficstatus

### ISSUE THREAD

**Issue by AGI-admin** [netdata/netdata#7520]
##### Bug report summary
We are getting daily security notices about the above command trying to be executed with sudo.  Also getting a second notice for the command `/usr/sbin/ipsec whack --status`

##### OS / Environment
CentOS 6.10 bare metal server

##### Netdata version (ouput of `netdata -V`)
netdata v1.19.0-96-nightly

##### Component Name
 collectors/charts.d.plugin/libreswan?

##### Steps To Reproduce
Install netdata using the one-line command

##### Expected behavior
netdata doesn't run commands requiring sudo...

Thanks

**Comment by ilyam8** [comment]
@AGI-admin sometimes it is the only way to get data.

There are several modules that executed some command with sudo:
 - [adaptec_raid](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/adaptec_raid)
 - [hpssa](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/hpssa)
 - [megacli](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/megacli)
 - [samba](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/samba)

All of them are disabled by default tho. And we mention in the module readme `Requirements` section that it needs `sudo` to work.

Probably `libreswan` should follow same logic (be disabled by default). Or do the check before try to execute the binary with `sudo`

> sudo -n -l ipsec

Does that check trigger security warning? @AGI-admin

**Comment by Ferroin** [comment]
> Probably libreswan should follow same logic (be disabled by default). Or do the check before try to execute the binary with sudo

I'd suggest doing both actually. Checks should always work from least invasive to most and bail early if they can (IOW, check running the command with `sudo` as late as possible), but I'm strongly of the opinion that anything that _needs_ privilege escalation should be disabled by default.

**Comment by ilyam8** [comment]
> should be disabled by default

I agree, but if we disable it right now it will stop working for users.

**Comment by Ferroin** [comment]
Indeed. I'll look at getting a fix for the check function before the end of the day today though (gotta have _something_ to do while waiting for test builds on Travis to finish :smile:)

**Comment by Ferroin** [comment]
NVM, looks like we're already ordering things in the check correctly. The issue is that we ahve to run the `ipsec` command to actually check if it's from libreswan or not.

**Comment by AGI-admin** [comment]
Sorry for the late reply, been very busy.  The messages have stopped so i guess you fixed something.  Thanks!

> > sudo -n -l ipsec

> Does that check trigger security warning? @AGI-admin

@ilyam8 When i try to run that from the netdata account, it says `sudo: a password is required`

**Comment by AGI-admin** [comment]
We have been getting the security notices again for some days now.

**Comment by ilyam8** [comment]
> netdata : user NOT in sudoers ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=/usr/sbin/ipsec whack --trafficstatus

Such messages? we havent fixed it. You can disables `libreswan` in `charts.d.conf`

```
libreswan=no
```

**Comment by ilyam8** [comment]
@Ferroin i think we could do same check before executing `sudo ipsec ...` as in `samba` module

https://github.com/netdata/netdata/blob/1d9d0982a17f2feaf1b8765b059d2de7a93bf8f9/collectors/python.d.plugin/samba/samba.chart.py#L120-L125

**Comment by ilyam8** [comment]
Or even make it more simple

> If a command is specified but not allowed by the policy, sudo will exit with a status value of 1.

- sudo -n -l ipsec whack --trafficstatus
- check exit code

**Comment by cakrit** [comment]
@Ferroin plz see @ilyam8 's suggestion above. It sounds like an easy fix.

**Comment by ilyam8** [comment]
Well, i could fix it myself.

**Comment by AGI-admin** [comment]
Where does the `libreswan=no` go?  I tried to put it in new file /etc/netdata/charts.d/charts.d.conf but it doesn't do anything and the "SECURITY information" email is still received everyday or when netdata is restarted.

**Comment by ilyam8** [comment]
> /etc/netdata/charts.d/charts.d.conf

There. Make sure it is not commented out.

```
[ilyam-pc netdata]# grep libre charts.d.conf
libreswan=no
```

**Comment by AGI-admin** [comment]
That's all I have:
```
# cat /etc/netdata/charts.d/charts.d.conf 
libreswan=no
#
```

**Comment by ilyam8** [comment]
@AGI-admin 

could you test the fix #8569?

**Comment by AGI-admin** [comment]
Hi, it seems if I put the `charts.d.conf` in `/etc/netdata` instead of `/etc/netdata/charts.d/` then it works!

**Comment by ilyam8** [comment]
> # cat /etc/netdata/charts.d/charts.d.conf 


oh, i didnt notice 🙈 

Plugin config file (`charts.d.conf`) should be in `/etc/netdata`, indeed. 

`/etc/netdata/charts.d/` contains modules configuration files (libreswan, etc.)

**Comment by DirectRoot** [comment]
I have not yet tried the fix above, but thought it worth pointing out that I have just started receiving alerts from RHEL7 servers about this too. At least one of the servers in question is running `v1.21.1-11-nightly`.

Should I just be doing as above, or does this indicate some wider problem?

Thanks!
Chris.

**Comment by ilyam8** [comment]
Hi. OS?

@DirectRoot do as `netdata` user and share result

```sh
sudo -n -l ipsec whack --status && echo $?
sudo -n -l ipsec whack --trafficstatus && echo $?
```

**Comment by DirectRoot** [comment]
@ilyam8 , sorry my reference to RHEL == Red Hat Enterprise Linux.

Here is the output, but this is what I'd expect, given I've not configured this feature and so not granted `netdata` the `sudo` that `libreswan.conf` refers to (`charts.d/libreswan.conf` is entirely commented out).

![Screenshot from 2020-04-15 11-26-01](https://user-images.githubusercontent.com/34790650/79356417-ee25a100-7f0c-11ea-96fc-90dc4580522f.png)

**Comment by ilyam8** [comment]
I asked because we have exactly same check

https://github.com/netdata/netdata/blob/81b6d6e600333e6731fb4b92e86a8292c79d5a48/collectors/charts.d.plugin/libreswan/libreswan.chart.sh#L105-L108

https://github.com/netdata/netdata/blob/81b6d6e600333e6731fb4b92e86a8292c79d5a48/collectors/charts.d.plugin/libreswan/libreswan.chart.sh#L40-L48

I think these `sudo -n -l ...` commands shouldnt trigger security alert. Do they?

**Comment by ilyam8** [comment]
>  sorry my reference to RHEL == Red Hat Enterprise Linux.

Man, i didnt notice, i you mentioned RHEL 🙈

**Comment by DirectRoot** [comment]
> Man, i didnt notice you mentioned RHEL see_no_evil

Haha! Don't worry ;)

I think only the `--status` command is causing the alert, I received this from three servers this morning.

`Apr 16 03:06:57 : netdata : a password is required ; TTY=unknown ; PWD=/etc/netdata ; USER=root ; COMMAND=list /usr/sbin/ipsec whack --status`

**Comment by ilyam8** [comment]
> USER=root ; COMMAND=list

Well, i dont know how to check w/o causing the alert then.  I guess `LIST` is `-l` option.

Can you check it in cmd? Does `sudo -n -l ipsec whack --status` causes notification? What about `sudo -n -l`?

**Comment by DirectRoot** [comment]
Yes, executing either of these commands as `netdata` causes an alert.

**Comment by ilyam8** [comment]
@DirectRoot https://github.com/netdata/netdata/issues/7520#issuecomment-607199533 😅

**Comment by DirectRoot** [comment]
Ah, yes that should fix it. Thanks!
