### ISSUE TITLE
Bug in creating Makefile

### ISSUE THREAD

**Issue by rsyncOSX** [netdata/netdata#7521]
##### Bug report summary
Seems like a previous bug is back in creating the Makefile

Bug in creating Makefile #7324

##### OS / Environment
FreeBSD 12.1 p1
##### Netdata version (ouput of `netdata -V`)
Last update
##### Component Name
Creating Makefile

**Comment by thiagoftsm** [comment]
Hi @rsyncOSX ,

I recompile now Netdata on my FreeBSD and everything was OK, I also used the latest version.
Netdata needs libuv as hard dependency now, do you have it installed?
Can you share with us the `config.log?

best regards!

**Comment by rsyncOSX** [comment]
[config.log](https://github.com/netdata/netdata/files/3961771/config.log)

**Comment by rsyncOSX** [comment]
> libuv

I installed libuv and making of netdata works :-) thx, closing the issue..
