### ISSUE TITLE
Whether to add Chinese support？能否加入中文支持

### ISSUE THREAD

**Issue by xnxy2012** [netdata/netdata#7523]
Whether to add Chinese support？
thank you very much！

**Comment by markwone** [comment]
> Whether to add Chinese support？
> thank you very much！

you mean the web page display by chinese？ 
you can see https://github.com/Fhaohaizi/netdata, only replace some js file by chinese such as dashboard_info.js、main.js

**Comment by joelhans** [comment]
We do have some documentation translated into Chinese: https://docs.netdata.cloud/zh/

We'd love to have more contributions to that effort, which is housed on this repository: https://github.com/netdata/localization

**Comment by markwone** [comment]
> We do have some documentation translated into Chinese: https://docs.netdata.cloud/zh/
> 
> We'd love to have more contributions to that effort, which is housed on this repository: https://github.com/netdata/localization

thank you very much! I like it

**Comment by xnxy2012** [comment]
thank you！

**Comment by xnxy2012** [comment]
> We do have some documentation translated into Chinese: https://docs.netdata.cloud/zh/
> 
> We'd love to have more contributions to that effort, which is housed on this repository: https://github.com/netdata/localization

thank you！

**Comment by markwone** [comment]
> We do have some documentation translated into Chinese: https://docs.netdata.cloud/zh/
> 
> We'd love to have more contributions to that effort, which is housed on this repository: https://github.com/netdata/localization

Can make netdata web pages display Chinese？

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
