### ISSUE TITLE
multiple [backend] in netdata.conf not working any more

### ISSUE THREAD

**Issue by vpnable** [netdata/netdata#7527]
##### Bug report summary
With the recent auto update (it occured about 12 hours ago) the host tags need to be in the first occuring [backend] category in netdata.conf, which was not like this before.
So you can not just append configuration options to netdata.conf any more.

##### OS / Environment
OS: Ubuntu 18.04, bare metal
[stream] is enabled, streaming data to a central netdata which then exports data to prometheus. The configuration below is on the slave.

##### Netdata version (ouput of `netdata -V`)
netdata v1.19.0-103-nightly

##### Component Name
netdata.conf / backend host tags / stream

##### Steps To Reproduce
Part of netdata.conf which is NOT working (host tags is ignored):
```
[backend]
        # host tags = 
        # enabled = no
        # data source = average

...

[backend]
        host tags = asn="9009",city="VIE",continent="EU",country="AT",isp="m247",serverid="339",type="vpn"
```

What IS working:
```
[backend]
        host tags = asn="9009",city="VIE",continent="EU",country="AT",isp="m247",serverid="339",type="vpn"
        # enabled = no
        # data source = average

...

#[backend]
#        host tags = asn="9009",city="VIE",continent="EU",country="AT",isp="m247",serverid="339",type="vpn"
```

What IS ALSO working:
```
#[backend]
        # host tags = asn="9009",city="VIE",continent="EU",country="AT",isp="m247",serverid="339",type="vpn"
        # enabled = no
        # data source = average

...

[backend]
        host tags = asn="9009",city="VIE",continent="EU",country="AT",isp="m247",serverid="339",type="vpn"
```

My current configuration has this data appended to the default netdata.conf:
```
[global]
        # disable the local database
        memory mode = none
        hostname = 339-vie04
        # do not update every second by default
        update every = 3

[health]
        # disable health checks
        enabled = no

[web]
        mode = none
        bind to = 127.0.0.1:19999

[backend]
        host tags = asn="9009",city="VIE",continent="EU",country="AT",isp="m247",serverid="339",type="vpn"
```

##### Expected behavior
It should be possible to use multiple [backend] configuration categories in netdata.conf, to just append a custom configuration.

**Comment by thiagoftsm** [comment]
Hi @vpnable ,

Netdata is bringing `exporters` now as experimental, case you wanna have multiple `backend` it will be necessary to create a file `exporting.conf` and write the configuration for them there, for example, when I was testing this new feature I used this:

```
[exporting:global]
    enabled = yes

[json:my_instance1]
    enabled = yes
    destination = localhost:5448

[json:my_instance2]
    enabled = yes
    destination = localhost:5449

[json:my_instance3]
    enabled = yes
    destination = localhost:5449

[opentsdb:my_instance4]
    enabled = yes
    destination = localhost:4242
```

best regards!

**Comment by thiagoftsm** [comment]
The file `exporting.conf` needs to be inside `/etc/netdata`.

**Comment by vpnable** [comment]
Thanks, @thiagoftsm . However, not sure if that is what we need, we have that configuration (including the host tags) on the slaves, streaming all data to the master. But exporting should be configured on the master, shouldn't it?
So even with the following exporting.conf on the slave, host tags are not sent to the master, but I assume this is not how the exporting.conf is meant to work, right?
```
[exporting:global]
    enabled = yes
    host tags = asn="9009",city="VIE",continent="EU",country="AT",isp="m247",serverid="339",type="vpn"
```

**Comment by thiagoftsm** [comment]
Hi @vpnable ,

Now I understood better the situation. The new features brought could not affect what you had, we will do an investigation to fix this ASAP.

Best regards!
