### ISSUE TITLE
Can I install it on the armv8 platform?

### ISSUE THREAD

**Issue by BH1NBN** [netdata/netdata#7528]
I am not a developer, but I very much hope that natdata will run on my device. Therefore, I asked developers to help me. I have prepared some related links for your reference.

[Device parameters](https://koolshare.cn/forum.php?mod=attachment&aid=MjYxMzE3fDczMjlmMzhhfDE1NzYzMzU3ODV8MjAyMjkyfDE0OTg4OQ%3D%3D&nothumb=yes)

Compilation tools
[brcm-arm-hnd / Broadcom HND ARM platform](https://github.com/RMerl/am-toolchains)

**Comment by Ferroin** [comment]
Netdata itself is known to build and run fine on both 32 and 64 bit ARM systems, so the deciding factor is whether you can get all the required dependencies built and working, which in turn usually just depends on what distribution you're using.

**Comment by markwone** [comment]
Do you want to run in an embedded linux environment? the one need to cross compile？

**Comment by BH1NBN** [comment]
> Do you want to run in an embedded linux environment? the one need to cross compile？
Yes, I want to install it in an embedded device, but I don't know how to cross compile these things. Is it almost impossible for someone who hasn't worked in this industry?

I would appreciate it if you could compile a runnable version!

**Comment by BH1NBN** [comment]
> Do you want to run in an embedded linux environment? the one need to cross compile？

Yes, I want to install it in an embedded device, but I don't know how to cross compile these things. Is it almost impossible for someone who hasn't worked in this industry?
I would appreciate it if you could compile a runnable version!

**Comment by markwone** [comment]
> > Do you want to run in an embedded linux environment? the one need to cross compile？
> 
> Yes, I want to install it in an embedded device, but I don't know how to cross compile these things. Is it almost impossible for someone who hasn't worked in this industry?
> I would appreciate it if you could compile a runnable version!

Can you read Chinese？I wrote a Chinese document about netdata cross compilation on armv7。I can share to you

**Comment by BH1NBN** [comment]
> > > 您想在嵌入式Linux环境中运行吗？需要交叉编译吗？
> > 
> > 
> > 是的，我想将其安装在嵌入式设备中，但是我不知道如何交叉编译这些内容。对于没有在这个行业工作的人来说，这几乎是不可能的吗？
> > 如果您可以编译可运行的版本，我将不胜感激！
> 
> 你会读中文吗？我在armv7上写了一个有关netdata交叉编译的中文文档。我可以分享给你



> > > Do you want to run in an embedded linux environment? the one need to cross compile？
> > 
> > 
> > Yes, I want to install it in an embedded device, but I don't know how to cross compile these things. Is it almost impossible for someone who hasn't worked in this industry?
> > I would appreciate it if you could compile a runnable version!
> 
> Can you read Chinese？I wrote a Chinese document about netdata cross compilation on armv7。I can share to you

这太好了，我们来自同一国度，伟大的P.R.C，我会根据您的文章仔细阅读参考！但我的是armv8我不知道是否能通过您群提供的很顺利的，搞出来！我本人不是一个linux的开发者甚至对linux了解甚少，但我可以去尝试着操作！我非常希望他能应用到我的路由器上！希望您能够帮助我！同时也感谢您的！回复！谢谢！

**Comment by markwone** [comment]
> > > > 您想在嵌入式Linux环境中运行吗？需要交叉编译吗？
> > > 
> > > 
> > > 是的，我想将其安装在嵌入式设备中，但是我不知道如何交叉编译这些内容。对于没有在这个行业工作的人来说，这几乎是不可能的吗？
> > > 如果您可以编译可运行的版本，我将不胜感激！
> > 
> > 
> > 你会读中文吗？我在armv7上写了一个有关netdata交叉编译的中文文档。我可以分享给你
> 
> > > > Do you want to run in an embedded linux environment? the one need to cross compile？
> > > 
> > > 
> > > Yes, I want to install it in an embedded device, but I don't know how to cross compile these things. Is it almost impossible for someone who hasn't worked in this industry?
> > > I would appreciate it if you could compile a runnable version!
> > 
> > 
> > Can you read Chinese？I wrote a Chinese document about netdata cross compilation on armv7。I can share to you
> 
> 这太好了，我们来自同一国度，伟大的P.R.C，我会根据您的文章仔细阅读参考！但我的是armv8我不知道是否能通过您群提供的很顺利的，搞出来！我本人不是一个linux的开发者甚至对linux了解甚少，但我可以去尝试着操作！我非常希望他能应用到我的路由器上！希望您能够帮助我！同时也感谢您的！回复！谢谢！

其实区别主要在于是不是交叉编译，官方提供的交叉编译的资料比较少，我目前也仅限于基础功能没有问题，一些小问题还在逐渐发现解决中。你可以看我邮件发给你的资料。如果有问题，可以联系我，邮件，微信都可以

**Comment by prologic** [comment]
@BH1NBN Sorry for the delay with this. I'm going to close this issue in favour of #6847 -- Please follow that issue. Binary Packages and Support for non-x86 architectures is part of a larger body of work that we're actively working on and ARM is one of the first on our list.

Can you also help us understand more about your device(s) in general? What are they; what specs? What OS is running on them? This will help us prioritise and decide on what other archtectures to support in our build systems.

**Comment by BH1NBN** [comment]
> > > > > 您想在嵌入式Linux环境中运行吗？需要交叉编译吗？
> > > > 
> > > > 
> > > > 是的，我想将其安装在嵌入式设备中，但是我不知道如何交叉编译这些内容。对于没有在这个行业工作的人来说，这几乎是不可能的吗？
> > > > 如果您可以编译可运行的版本，我将不胜感激！
> > > 
> > > 
> > > 你会读中文吗？我在armv7上写了一个有关netdata交叉编译的中文文档。我可以分享给你
> > 
> > 
> > > > > Do you want to run in an embedded linux environment? the one need to cross compile？
> > > > 
> > > > 
> > > > Yes, I want to install it in an embedded device, but I don't know how to cross compile these things. Is it almost impossible for someone who hasn't worked in this industry?
> > > > I would appreciate it if you could compile a runnable version!
> > > 
> > > 
> > > Can you read Chinese？I wrote a Chinese document about netdata cross compilation on armv7。I can share to you
> > 
> > 
> > 这太好了，我们来自同一国度，伟大的P.R.C，我会根据您的文章仔细阅读参考！但我的是armv8我不知道是否能通过您群提供的很顺利的，搞出来！我本人不是一个linux的开发者甚至对linux了解甚少，但我可以去尝试着操作！我非常希望他能应用到我的路由器上！希望您能够帮助我！同时也感谢您的！回复！谢谢！
> 
> 其实区别主要在于是不是交叉编译，官方提供的交叉编译的资料比较少，我目前也仅限于基础功能没有问题，一些小问题还在逐渐发现解决中。你可以看我邮件发给你的资料。如果有问题，可以联系我，邮件，微信都可以

抱歉最近一直在忙忽略了你的信息！我先尝试的试试看 如果搞不定我希望您能给予一些帮助！

**Comment by BH1NBN** [comment]
> @BH1NBN Sorry for the delay with this. I'm going to close this issue in favour of #6847 -- Please follow that issue. Binary Packages and Support for non-x86 architectures is part of a larger body of work that we're actively working on and ARM is one of the first on our list.
> 
> Can you also help us understand more about your device(s) in general? What are they; what specs? What OS is running on them? This will help us prioritise and decide on what other archtectures to support in our build systems.
=============================================================
Hello! Because I know very little about Linux and do not know how to compile, but I can provide you with what you need. What information do you need or should I do?

Attached are some of my running commands for your reference! If I need to use remote ssh I will specially authorize my network for you
=============================================================
I have also provided you with some related links! Links needed for cross compilation
https://github.com/koolshare/rogsoft   （Chinese）
https://github.com/RMerl/am-toolchains/tree/master/brcm-arm-hnd
=============================================================
[busybox --list.txt](https://github.com/netdata/netdata/files/4071244/busybox.--list.txt)
[uname -a.txt](https://github.com/netdata/netdata/files/4071245/uname.-a.txt)
[version.txt](https://github.com/netdata/netdata/files/4071246/version.txt)

**Comment by BH1NBN** [comment]
> @BH1NBN Sorry for the delay with this. I'm going to close this issue in favour of #6847 -- Please follow that issue. Binary Packages and Support for non-x86 architectures is part of a larger body of work that we're actively working on and ARM is one of the first on our list.
> 
> Can you also help us understand more about your device(s) in general? What are they; what specs? What OS is running on them? This will help us prioritise and decide on what other archtectures to support in our build systems.

> @BH1NBN Sorry for the delay with this. I'm going to close this issue in favour of #6847 -- Please follow that issue. Binary Packages and Support for non-x86 architectures is part of a larger body of work that we're actively working on and ARM is one of the first on our list.
> 
> Can you also help us understand more about your device(s) in general? What are they; what specs? What OS is running on them? This will help us prioritise and decide on what other archtectures to support in our build systems.
=============================================================
Hello! Because I know very little about Linux and do not know how to compile, but I can provide you with what you need. What information do you need or should I do?

Attached are some of my running commands for your reference! If I need to use remote ssh I will specially authorize my network for you
=============================================================
I have also provided you with some related links! Links needed for cross compilation
https://github.com/koolshare/rogsoft   （Chinese）
https://github.com/RMerl/am-toolchains/tree/master/brcm-arm-hnd
=============================================================
[busybox --list.txt](https://github.com/netdata/netdata/files/4071244/busybox.--list.txt)
[uname -a.txt](https://github.com/netdata/netdata/files/4071245/uname.-a.txt)
[version.txt](https://github.com/netdata/netdata/files/4071246/version.txt)

**Comment by prologic** [comment]
To summarive (_and avoid downloading attached files_):

- ARM64 on ARMv8
- Linux 4.x with busybox userland
- Built with buildrot

@BH1NBN The only question I have for you is:

What type of system is this? What hardware?

**Comment by prologic** [comment]
> What type of system is this? What hardware?

Don't worry. You answered this [here](https://github.com/netdata/netdata/issues/6847#issuecomment-575139712) thanks!
