### ISSUE TITLE
Please add charts for LSAPI PHP Handler on Apache

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#7529]
##### Feature idea summary

Please, if technically possible, can you add a collector for displaying of PHP stats when using the LSAPI PHP Handler available in WHM and Apache.  

Netdata states "Most modules come with auto-detection, configured to work out-of-the-box on popular operating systems with the default settings." but there are no PHP charts available in Netdata unless the server is using PHP-FPM and NginX.

This is confusing compared to other monitoring apps such as New Relic.
PHP-FPM handler is considered my many to be unusable on average servers due to excessive resource (memory) usage.

Whilst it would be useful to have PHP stats available for FCGI and Zend when using Apache, LSAPI has been shown to provide more performance than PHP-FPM or FastCGI and uses less system resources, it is available for free via WHM/CPanel (and is built-in if using the Litespeed web server) and is likely to become the next go to handler for many users seeking improved performance.

https://www.litespeedtech.com/open-source/litespeed-sapi/php

Documentation:
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php

##### Expected behavior

Preferably available with no configuration after install, Netdata to show various stats and charts relating to PHP/Opcache for servers using Lightspeed's LSAPI PHP Handler on Apache.

Thank you.

**Comment by ilyam8** [comment]
hi @TheOldMan2000 

I dont really understand the request. Could you explain how to get these metrics? Parse some file? Some http endpoint?

I see `Lightspeed` thing, i rememeber it is not free tool. But we have a collector for it

> https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/litespeed

**Comment by TheOldMan2000** [comment]
Hi,
Sorry for the late reply. No, not the Litespeed operating system, or the
open source version. I'm actually referring  to their PHP Handler LSAPI
which is available free in WHM which is an alternative to the resource hog
PHP-FPM and the much slower FastCGI PHP Handler.
I'm not sure where the stats would be, sorry.

**Comment by cakrit** [comment]
I don't see any mention of anyone monitoring performance metrics for LSAPI. Perhaps there isn't anything exposed. Unless someone can provide a specific endpoint to monitor, we can't progress with this. Closing and we can reopen if we get new info.
