### ISSUE TITLE
configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.

### ISSUE THREAD

**Issue by 8isles** [netdata/netdata#7534]
This error came out when I tried to install netdata.

When I tried to yum search the package and the package is not found. 

Does anyone have a solution for this?

**Comment by markwone** [comment]
you can compile the libuv by source ,  and install it. then install netdata

**Comment by 8isles** [comment]
> you can compile the libuv by source, and install it. then install netdata

Do you mean that I can write the source code by hand? Is there any way for me to get the source code, please?

**Comment by markwone** [comment]
> > you can compile the libuv by source, and install it. then install netdata
> 
> Do you mean that I can write the source code by hand? Is there any way for me to get the source code, please?

you can down the source code from here
https://codeload.github.com/libuv/libuv/zip/v1.x

**Comment by Saruspete** [comment]
Greetings,

Not to sound rude, but this question is already answered by the documentation, section [preparing your system](https://docs.netdata.cloud/packaging/installer/#prepare-your-system).

if you're using Redhat/CentOS 6, this section is of interest for you:
> Please note that for RHEL/CentOS you need [EPEL](http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/). In addition, RHEL/CentOS version 6 also need [OKay](https://okay.com.mx/blog-news/rpm-repositories-for-centos-6-and-7.html) for package libuv version 1.

Please provide more details on your setup: OS Name & Version, CPU Architecture, etc...

**Comment by ElliotNB** [comment]
@Saruspete We have EPEL installed on all of our servers running CentOS 6.10 latest and this error still persists. So far it seems that compiling `libuv` by source is the only viable solution.

**Comment by Saruspete** [comment]
EPEL 6 is not sufficient: it only provides `libuv-0.10`, while netdata needs at least `libuv-1`. That's why you need to install a more recent package provided by OKay.
You can follow the instruction in the documentation to install it on CentOS 6

**Comment by ElliotNB** [comment]
If anyone wants to compile the latest `libuv` from source on CentOS 6, here are step by step instructions:

```
yum -y install libtool
wget https://github.com/libuv/libuv/archive/v1.34.0.tar.gz
tar -zxvf v1.34.0.tar.gz
cd libuv-1.34.0
sh autogen.sh
./configure
make
make check
make install
ldconfig -v
```

If you already have `libuv` or `libuv-devel` installed via the EPEL 6 repo, you'll need to uninstall them first:

`yum -y remove libuv libuv-devel`

If you don't do that, then the netdata installer might grab the older 0.10 libuv files and error out -- as it did for me.

**Comment by Cosmo121** [comment]
> If anyone wants to compile the latest `libuv` from source on CentOS 6, here are step by step instructions:
> 
> ```
> yum -y install libtool
> wget https://github.com/libuv/libuv/archive/v1.34.0.tar.gz
> tar -zxvf v1.34.0.tar.gz
> cd libuv-1.34.0
> sh autogen.sh
> ./configure
> make
> make check
> make install
> ldconfig -v
> ```
> 
> If you already have `libuv` or `libuv-devel` installed via the EPEL 6 repo, you'll need to uninstall them first:
> 
> `yum -y remove libuv libuv-devel`
> 
> If you don't do that, then the netdata installer might grab the older 0.10 libuv files and error out -- as it did for me.

This fixed my issue with installing on Rocky Linux. Thanks friend!

**Comment by Richo85** [comment]
I could not find libuv-1.34.0 when I unzip the v1.34.0.tar.gz.
