### ISSUE TITLE
How to prevent access on port 19999  using httpd CentOS 6

### ISSUE THREAD

**Issue by kkoomen** [netdata/netdata#7535]
I want to put an htpasswd in the /usr/share/netdata/web/ folder on port 19999 where the server is running. I am using the `httpd` package on CentOS 6.10. I have seen https://docs.netdata.cloud/docs/running-behind-apache/ and also other issues where people try to get it behind apache, but then people create a vhost as a proxy to port 19999 where as port 19999 is still available to the outside world (right?)

So how can I prevent the outside world accessing port 19999 by adding an htpasswd using httpd?

**Comment by ilyam8** [comment]
Hi @kkoomen 

 - bind netdata to 127.0.0.1
 - proxy requests to 127.0.0.1:19999 via httpd

**Comment by kkoomen** [comment]
@ilyam8 I already managed to get it to work like that, yes. Thanks.
