### ISSUE TITLE
/usr/bin/env: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by markwone** [netdata/netdata#7536]
##### Question summary

I run the netdata-installer.sh script on my embedded Linux and reported "/usr/bin/env: bad interpreter: No such file or directory"this error. I checked the path of env is "/bin/env". Is there any compatible way for two path?
##### OS / Environment
embedded linux for zynq 7020
##### Expected results
fixed this problem?

**Comment by Saruspete** [comment]
Greetings,

It's the first time I see `env` not being in its standard `/usr/bin` path. It's even the primary use of `env`: to search for an interpreter in a non-standard location, but located in `$PATH`.|
In all official [documentation](https://www.gnu.org/software/coreutils/manual/html_node/env-invocation.html) and [manpage](https://manpages.debian.org/testing/coreutils/env.1.en.html), you'll see `/usr/bin/env`. 

This is clearly a bug in your distribution, as almost all scripts are expecting `env` to be in `/usr/bin`, not anywhere else. 

A quick fix would be something like: 
```
if ! [[ -d "/usr/bin" ]]; then
  if ! mkdir -p "/usr/bin"; then
    echo >&2 "ERROR: cannot create '/usr/bin'"
  fi
fi
if ! ln -s /bin/env /usr/bin/env; then
  echo >&2 "ERROR: Unable to symlink env. Return code: $?"
fi
```

But a bugreport needs to be opened to your dji support.

**Comment by markwone** [comment]
Hi
    my env is a command of busybox , someone install the busybox in the root directory /，so the path of env is  /bin/env。I know how to fixed it . just  I want to  weather need to compatible /bin/env。if like you say，env at /bin is very few，we can ignore it. thank you very much!

**Comment by james123-max** [comment]
ames@james-VirtualBox:~/application$ truffle version
bash: /usr/local/bin/truffle: /usr/bin/env: bad interpreter: No such file or directory   

when even i want to check for my truffle version i get this message can someone help
