### ISSUE TITLE
system.cpu: data download failed for url: http://192.168.8.2:19999/api/v1/data?chart=system.cpu&format=json&points=509&group=average>ime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-540

### ISSUE THREAD

**Issue by markwone** [netdata/netdata#7537]
##### Bug report summary
the dash board ok, but line chart of cpu 、load and so on can not display! print :
system.cpu: data download failed for url: http://192.168.8.2:19999/api/v1/data?chart=system.cpu&format=json&points=509&group=average>ime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-540
##### OS / Environment
linux zynq 7020 
##### Netdata version (ouput of `netdata -V`)
v1.19.0
##### Steps To Reproduce
when we reboot the embedded device and restart netdata service
##### Expected behavior
who can help me , tell me How to solve? thank you!

**Comment by thiagoftsm** [comment]
Hi @markwone ,

I tested the URL that you copied with few changes for my host, and I did not have any problem to get the data, I ran the following command:

```
curl -k "https://192.168.0.12:19999/api/v1/data?chart=system.cpu&format=json&points=509&group=average>ime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-540"
{
   "api": 1,
   "id": "system.cpu",
   "name": "system.cpu",
   "view_update_every": 1,
   "update_every": 1,
   "first_entry": 1571052435,
   "last_entry": 1576503774,
   "before": 1576503774,
   "after": 1576503235,
   "dimension_names": ["softirq", "user", "system", "nice", "iowait"],
   "dimension_ids": ["softirq", "user", "system", "nice", "iowait"],
   "latest_values": [0.5050505, 2.2727273, 1.5151515, 0, 0],
   "view_latest_values": [0.5050505, 2.272727, 1.5151515, 0, 0],
   "dimensions": 5,
   "points": 540,
   "format": "json",
   "result": {
 "labels": ["time", "softirq", "user", "system", "nice", "iowait"],
    "data":
 [
      [ 1576503235000, null, null, null, null, null],
      [ 1576503236000, null, null, null, null, null],
      [ 1576503237000, null, null, null, null, null],
```

I had to use `-k` because I have self-signed certificate and I put between quotes to avoid problems with bash interpretation.

What was the exact command that you used to get the data?

Best regards!

**Comment by markwone** [comment]
> Hi @markwone ,
> 
> I tested the URL that you copied with few changes for my host, and I did not have any problem to get the data, I ran the following command:
> 
> ```
> curl -k "https://192.168.0.12:19999/api/v1/data?chart=system.cpu&format=json&points=509&group=average>ime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-540"
> {
>    "api": 1,
>    "id": "system.cpu",
>    "name": "system.cpu",
>    "view_update_every": 1,
>    "update_every": 1,
>    "first_entry": 1571052435,
>    "last_entry": 1576503774,
>    "before": 1576503774,
>    "after": 1576503235,
>    "dimension_names": ["softirq", "user", "system", "nice", "iowait"],
>    "dimension_ids": ["softirq", "user", "system", "nice", "iowait"],
>    "latest_values": [0.5050505, 2.2727273, 1.5151515, 0, 0],
>    "view_latest_values": [0.5050505, 2.272727, 1.5151515, 0, 0],
>    "dimensions": 5,
>    "points": 540,
>    "format": "json",
>    "result": {
>  "labels": ["time", "softirq", "user", "system", "nice", "iowait"],
>     "data":
>  [
>       [ 1576503235000, null, null, null, null, null],
>       [ 1576503236000, null, null, null, null, null],
>       [ 1576503237000, null, null, null, null, null],
> ```
> 
> I had to use `-k` because I have self-signed certificate and I put between quotes to avoid problems with bash interpretation.
> 
> What was the exact command that you used to get the data?
> 
> Best regards!
Hi
    it is not enter command by hand , it was displayed by web page when I visit it

**Comment by amoss** [comment]
Please could you attach a screenshot of your browser showing the dashboard with the error?

**Comment by markwone** [comment]
> Please could you attach a screenshot of your browser showing the dashboard with the error?

![datadownloadfail](https://user-images.githubusercontent.com/58732509/70991784-29e95f00-2103-11ea-8506-1d09610fb47e.png)

**Comment by amoss** [comment]
That's the client area in the browser - I was hoping to see what is in the URL bar at the top. Part of the URL in the error message looks corrupted (the `group=average>ime=0` part).

The meter above the broken charts shows an instantaneous reading for the cpu load although the chart has failed to load.

What happens if you try to access the chart data via curl:
```
curl "http://192.168.8.2:19999/api/v1/data?chart=system.cpu&format=json&points=509&group=average>ime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-10"
```
