### ISSUE TITLE
Invalid css/js resources when URL for slave node has no final `/` on streaming master

### ISSUE THREAD

**Issue by pgassmann** [netdata/netdata#7539]
##### Bug report summary

Invalid css/js resources when URL for slave node has no final `/` on streaming master.

not OK: `http://master-host:master-port/host/slave-host`
404: `http://master-host:master-port/host/main.css?v=5`
Also 404:
```
/host/main.js?v20190905-0
/host/images/netdata-logomark.svg
/host/dashboard.js?v20190902-0
```

OK: `http://master-host:master-port/host/slave-host/`
CSS 200 OK: `http://master-host:master-port/host/slave-host/main.css?v=5`

OK `http://master-host:master-port`
CSS Path: `http://master-host:master-port/main.css?v=5`

Short:
resources are available on `/` and on `/host/slave/` but not on `/host`

Why are the resource paths relative and not absolute? (always `/main.css`)

##### OS / Environment

Latest netdata docker image: `netdata/netdata:latest`

##### Netdata version (ouput of `netdata -V`)

`v1.19.0-102-g878e1327`

##### Component Name

Web UI

##### Steps To Reproduce

Go to netdata instance that receives streams. select slave host in menu. remove last bits in the URL `/#menu_system;theme=slate;help=true`

##### Expected behavior

css and js resources are always the same, independent of main or slave host. always `/main.css` etc.

**Comment by thiagoftsm** [comment]
Hi @pgassmann ,

I was studying the bug report now, and I arrived in the conclusion that this is a problem with browser request and not Netdata answer. When you write a request like `https://localhost:19999/host/darkstar`, you are saying for Netdata to search inside the directory `host` the file `darkstar`, because Netdata does not have a file called `darkstar` it delivers a 404 to you, on the other hand, when we write `https://localhost:19999/host/darkstar` you are saying for Netdata to deliver the index(`/`)  of `host/darkstar`. I arrived in the conclusion after to study Netdata request and verify that at least in my case the browser used cache to do the request. Of course I can be wrong, and I assigned other developers to discuss this kind of request.

Best regards!

**Comment by pgassmann** [comment]
The issue happened, when I sent the link to another person and he got no css. Of course one could say that I copied the link wrong. But most links on the Internet don't need a / at the end. 
From my point of view the webserver should handle this case. Delivering a broken page is never OK. If the link is wrong the webserver should respond with 404 and not deliver some html without css/js. It could be solved with a simple redirect.

Currently for each slave, the browser has a different path to the css resources. Is this necessary? do the css/js etc differ from slave to slave and from host? If they are the same, it would be better if the css/js files have to be downloaded only once.

**Comment by amoss** [comment]
Following the steps in the bug report leads to a broken page. @pgassmann is correct above that the web server should not deliver a broken page. The fix can be either:

1. Deliver a 404 if the URL contains a `/host/name`
2. Deliver a 302 if the URL contains a `/host/name` -> `/host/name/`

I think the second case is preferable as it feels more usable, and it matches the behavior of nginx / apache.

**Comment by thiagoftsm** [comment]
>     1. Deliver a 404 if the URL contains a `/host/name`
> 
>     2. Deliver a 302 if the URL contains a `/host/name` -> `/host/name/`
> 
> 

Right now Netdata is returning a group of 404, we should change it to 302 with the new URL.

**Comment by thiagoftsm** [comment]
> The issue happened, when I sent the link to another person and he got no css. Of course one could say that I copied the link wrong. But most links on the Internet don't need a / at the end.
> From my point of view the webserver should handle this case. Delivering a broken page is never OK. If the link is wrong the webserver should respond with 404 and not deliver some html without css/js. It could be solved with a simple redirect.
> 
> Currently for each slave, the browser has a different path to the css resources. Is this necessary? do the css/js etc differ from slave to slave and from host? If they are the same, it would be better if the css/js files have to be downloaded only once.

Thank you for this additional information that help us to understand better what happened .
