### ISSUE TITLE
Ubiquiti ER-X SNMP configuration

### ISSUE THREAD

**Issue by samip5** [netdata/netdata#7542]
##### Question summary
I don't know how to get traffic stats from my ER-X via SNMP.

##### OS / Environment
Ubuntu Server 18.04

##### Component Name
SNMP

##### Expected results
Some example config for Ubiquiti EdgeRouters would be nice addition.

```
.1.3.6.1.2.1.1.1.0 = STRING: "EdgeOS v2.0.6.5208541.190708.0508"
.1.3.6.1.2.1.1.2.0 = OID: .1.3.6.1.4.1.41112.1.5
.1.3.6.1.2.1.1.3.0 = Timeticks: (38802) 0:06:28.02
.1.3.6.1.2.1.1.4.0 = STRING: "root"
.1.3.6.1.2.1.1.5.0 = STRING: "ER-X"
.1.3.6.1.2.1.1.6.0 = STRING: "Turku, Finland"
.1.3.6.1.2.1.1.7.0 = INTEGER: 14
.1.3.6.1.2.1.1.8.0 = Timeticks: (32) 0:00:00.32
.1.3.6.1.2.1.1.9.1.2.1 = OID: .1.3.6.1.6.3.11.3.1.1
.1.3.6.1.2.1.1.9.1.2.2 = OID: .1.3.6.1.6.3.15.2.1.1
.1.3.6.1.2.1.1.9.1.2.3 = OID: .1.3.6.1.6.3.10.3.1.1
.1.3.6.1.2.1.1.9.1.2.4 = OID: .1.3.6.1.6.3.1
.1.3.6.1.2.1.1.9.1.2.5 = OID: .1.3.6.1.6.3.16.2.2.1
.1.3.6.1.2.1.1.9.1.2.6 = OID: .1.3.6.1.2.1.49
.1.3.6.1.2.1.1.9.1.2.7 = OID: .1.3.6.1.2.1.4
.1.3.6.1.2.1.1.9.1.2.8 = OID: .1.3.6.1.2.1.50
.1.3.6.1.2.1.1.9.1.2.9 = OID: .1.3.6.1.6.3.13.3.1.3
.1.3.6.1.2.1.1.9.1.2.10 = OID: .1.3.6.1.2.1.92
.1.3.6.1.2.1.1.9.1.3.1 = STRING: "The MIB for Message Processing and Dispatching."
.1.3.6.1.2.1.1.9.1.3.2 = STRING: "The management information definitions for the SNMP User-based Security Model."
.1.3.6.1.2.1.1.9.1.3.3 = STRING: "The SNMP Management Architecture MIB."
.1.3.6.1.2.1.1.9.1.3.4 = STRING: "The MIB module for SNMPv2 entities"
.1.3.6.1.2.1.1.9.1.3.5 = STRING: "View-based Access Control Model for SNMP."
.1.3.6.1.2.1.1.9.1.3.6 = STRING: "The MIB module for managing TCP implementations"
.1.3.6.1.2.1.1.9.1.3.7 = STRING: "The MIB module for managing IP and ICMP implementations"
.1.3.6.1.2.1.1.9.1.3.8 = STRING: "The MIB module for managing UDP implementations"
.1.3.6.1.2.1.1.9.1.3.9 = STRING: "The MIB modules for managing SNMP Notification, plus filtering."
.1.3.6.1.2.1.1.9.1.3.10 = STRING: "The MIB module for logging SNMP Notifications."
```

**Comment by ilyam8** [comment]
hi @samip5 

To get net device stats via snmp i would suggest to use:

- https://www.observium.org/
- https://www.librenms.org/

**Comment by samip5** [comment]
I'm want to use netdata, so I can use same dashboard for SNMP AND systems.

**Comment by ilyam8** [comment]
Well, it wont be easy 😄

**Comment by samip5** [comment]
> Well, it wont be easy 😄

That's not very helpful sounding. :(

**Comment by ilyam8** [comment]
Netdata snmp support is very very basic, you need to get all OIDs yourself.

Have you found OIDs? What help do you need?

In general:
 - find iface indexes
 - use these oid to monitor what you need

> http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?oid=1.3.6.1.2.1.31.1.1.1

I think you need:

- 1.3.6.1.2.1.31.1.1.1.6 (ifHCInOctets)
- 1.3.6.1.2.1.31.1.1.1.10 (ifHCOutOctets)

snmp module config is json, so i suggest to check it every time you make som changes in https://jsonformatter.curiousconcept.com/

**Comment by ilyam8** [comment]
oh, if you are on linux install `snmp` (debian/ubuntu), you will need `snmpwalk` tool.

**Comment by samip5** [comment]
> oh, if you are on linux install `snmp` (debian/ubuntu), you will need `snmpwalk` tool.

I'm looking at the OID's, but they don't make really any sense to me.

P.S Those your listed OID's does not exist.

**Comment by ilyam8** [comment]
yes, last number is interface index.

Check `1.3.6.1.2.1.31.1.1.1.1` OID to get names.

So if you are want to monitor 6 interface you need:
> 1.3.6.1.2.1.31.1.1.1.6.6 # input
> 1.3.6.1.2.1.31.1.1.1.10.6 # output


Then just follow https://docs.netdata.cloud/collectors/node.d.plugin/snmp/

**Comment by samip5** [comment]
This errors:
```
$ sudo /usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp
2019-12-16 15:29:50: node.d.plugin: ERROR: Cannot read user-configuration file /etc/netdata/node.d.conf: ENOENT: no such file or directory, open '/etc/netdata/node.d.conf'.
2019-12-16 15:29:50: node.d.plugin: ERROR: snmp: 192.168.2.1: Received error = { RequestFailedError: NoSuchName: 1.3.6.1.2.1.31.1.1.1.6.6
    at Object.Session.onSimpleGetResponse [as onResponse] (/usr/libexec/netdata/node.d/node_modules/net-snmp.js:954:16)
    at Session.onMsg (/usr/libexec/netdata/node.d/node_modules/net-snmp.js:928:9)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
  name: 'RequestFailedError',
  message: 'NoSuchName: 1.3.6.1.2.1.31.1.1.1.6.6',
  status: 2 } varbinds = undefined
DISABLE
```

But if I do ` snmpwalk -v 2c -c public 192.168.2.1 1.3.6.1.2.1.31.1.1.1.6.6` I do get a reply from snpwalk?

**Comment by ilyam8** [comment]
> 2019-12-16 15:29:50: node.d.plugin: ERROR: Cannot read user-configuration file /etc/netdata/node.d.conf: ENOENT: no such file or directory, open '/etc/netdata/node.d.conf'.

Where did you put your config?

**Comment by samip5** [comment]
> > 2019-12-16 15:29:50: node.d.plugin: ERROR: Cannot read user-configuration file /etc/netdata/node.d.conf: ENOENT: no such file or directory, open '/etc/netdata/node.d.conf'.
> 
> Where did you put your config?

/etc/netdata/node.d/snmp.conf

**Comment by ilyam8** [comment]
> But if I do snmpwalk -v 2c -c public 192.168.2.1 1.3.6.1.2.1.31.1.1.1.6.6 I do get a reply from snpwalk?

show

**Comment by samip5** [comment]
> > But if I do snmpwalk -v 2c -c public 192.168.2.1 1.3.6.1.2.1.31.1.1.1.6.6 I do get a reply from snpwalk?
> 
> show

```
$ snmpwalk -v 2c -c public 192.168.2.1 1.3.6.1.2.1.31.1.1.1.6.6
iso.3.6.1.2.1.31.1.1.1.6.6 = Counter64: 16413739028
```

**Comment by ilyam8** [comment]
ok, share your conig (dont forget to remove community)

**Comment by samip5** [comment]
I used the example as a base.


The config:
```
{
    "enable_autodetect": false,
    "update_every": 5,
    "max_request_size": 100,
    "servers": [
        {
            "hostname": "192.168.2.1",
            "community": "",
            "update_every": 10,
            "max_request_size": 50,
            "options": { "timeout": 10000 },
            "charts": {
                "snmp_switch.bandwidth_eth2": {
                    "title": "Internet traffic",
                    "units": "kilobits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "ports",
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.31.1.1.1.6.6",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024,
                            "offset": 0
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.31.1.1.1.10.6",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1024,
                            "offset": 0
                        }
                    }
                },
                "snmp_switch.bandwidth_tun0": {
                    "title": "Tunnel to Hetzhner",
                    "units": "kilobits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "ports",
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.31.1.1.1.6.17",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024,
                            "offset": 0
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.31.1.1.1.10.17",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1024,
                            "offset": 0
                        }
                    }
                }
            }
        }
    ]
}
```

**Comment by ilyam8** [comment]
add `version` to the options

> version, the SNMP version to use. 0 is Version 1, 1 is Version 2c. The default is Version 1 (0).

> But if I do snmpwalk -v 2c -c COMMUNITY 192.168.2.1 1.3.6.1.2.1.31.1.1.1.6.6 I do get a reply from snpwalk?

> -v 2c

**Comment by samip5** [comment]
Oh, now it works. Now I just need to get it output Mbits and not kilobits/s. :)

**Comment by ilyam8** [comment]
There is units auto scale feature.

See Dashboard-Settings-Locale-Scale Units.

So dashboard will convert units automatically.

> "divisor": 1024,

should be 1000 btw, 1024 is wrong.

**Comment by ilyam8** [comment]
If you want to hardcode megabits:

```
"units": "megabits/s",
```

```
                            "multiplier": 8,
                            "divisor": 1000000,
```

**Comment by samip5** [comment]
I got it now, thank you. 👍

**Comment by cbmgit** [comment]
> I used the example as a base.
> 
> The config:
> 
> ```
> {
>     "enable_autodetect": false,
>     "update_every": 5,
>     "max_request_size": 100,
>     "servers": [
>         {
>             "hostname": "192.168.2.1",
>             "community": "",
>             "update_every": 10,
>             "max_request_size": 50,
>             "options": { "timeout": 10000 },
>             "charts": {
>                 "snmp_switch.bandwidth_eth2": {
>                     "title": "Internet traffic",
>                     "units": "kilobits/s",
>                     "type": "area",
>                     "priority": 1,
>                     "family": "ports",
>                     "dimensions": {
>                         "in": {
>                             "oid": "1.3.6.1.2.1.31.1.1.1.6.6",
>                             "algorithm": "incremental",
>                             "multiplier": 8,
>                             "divisor": 1024,
>                             "offset": 0
>                         },
>                         "out": {
>                             "oid": "1.3.6.1.2.1.31.1.1.1.10.6",
>                             "algorithm": "incremental",
>                             "multiplier": -8,
>                             "divisor": 1024,
>                             "offset": 0
>                         }
>                     }
>                 },
>                 "snmp_switch.bandwidth_tun0": {
>                     "title": "Tunnel to Hetzhner",
>                     "units": "kilobits/s",
>                     "type": "area",
>                     "priority": 1,
>                     "family": "ports",
>                     "dimensions": {
>                         "in": {
>                             "oid": "1.3.6.1.2.1.31.1.1.1.6.17",
>                             "algorithm": "incremental",
>                             "multiplier": 8,
>                             "divisor": 1024,
>                             "offset": 0
>                         },
>                         "out": {
>                             "oid": "1.3.6.1.2.1.31.1.1.1.10.17",
>                             "algorithm": "incremental",
>                             "multiplier": -8,
>                             "divisor": 1024,
>                             "offset": 0
>                         }
>                     }
>                 }
>             }
>         }
>     ]
> }
> ```

Make sure this JSON is valid, it can be validated using https://codebeautify.org/jsonvalidator or  https://jsonformatter.org/

**Comment by ilyam8** [comment]
@cbmgit it is valid, if i copy the content intto jsonformatter.org field and press `validate` i get `VALID JSON` (top right corner)
