### ISSUE TITLE
chown: /usr/libexec/netdata/plugins.d/app.plugin: Operation not permitted

### ISSUE THREAD

**Issue by markwone** [netdata/netdata#7552]
##### Bug report summary
 when I run netdata-installer.sh on my embedded linux device by root user, it print like as the title.
##### OS / Environment
linux zynq
##### Netdata version (ouput of `netdata -V`)
v1.19
##### Steps To Reproduce
Must appear
##### Expected behavior
help me， thank you！

**Comment by markwone** [comment]
who can help me?

**Comment by amoss** [comment]
What do you see if you try:
```
ls -l /usr/libexec/netdata/plugins.d/
```

**Comment by markwone** [comment]
![pluginsls](https://user-images.githubusercontent.com/58732509/70991142-dfb3ae00-2101-11ea-912d-5de4a437c12f.png)


> What do you see if you try:
> 
> ```
> ls -l /usr/libexec/netdata/plugins.d/
> ```

**Comment by Saruspete** [comment]
Taking a guess: is the / or /usr a special mountpoint or has specific options ? Or maybe a kernel security module like selinux or apparmor refuses this setuid...

can you provide the output of:
```
cat /proc/mounts
df -hP
getenforce
lsmod
```

usually an [sosreport](https://github.com/sosreport/sos) is useful to gather all required information, but as your linux distribution seems a bit unusual, I don't know if it will be available to you.

**Comment by markwone** [comment]
> Taking a guess: is the / or /usr a special mountpoint or has specific options ? Or maybe a kernel security module like selinux or apparmor refuses this setuid...
> 
> can you provide the output of:
> 
> ```
> cat /proc/mounts
> df -hP
> getenforce
> lsmod
> ```
> 
> usually an [sosreport](https://github.com/sosreport/sos) is useful to gather all required information, but as your linux distribution seems a bit unusual, I don't know if it will be available to you.

I get it，because my file on a vfat filesystem, so that I cannot chown the file, thank you very much!
