### ISSUE TITLE
Reference issues number: https://github.com/netdata/netdata/issues/7499

### ISSUE THREAD

**Issue by somir** [netdata/netdata#7553]
My issue number-7499 till now not solved. Please request to you don't close issues without user confirmation.

Hi @ilyam8,
I added the above config in tomcat.conf file but result is same. FYI, my URL is password protected. Can you please review again my problem?

@Wing924, Can you please looking my problem?
Current config file details:

localhost:
name : 'local'
url : 'http://localhost:8080/manager/status?XML=true'
user : 'admin'
pass : 'admin'

localipv4:
name : 'local'
url : 'http://127.0.0.1:8080/manager/status?XML=true'
user : 'admin'
pass : 'admin'

localipv6:
name : 'local'
url : 'http://[::1]:8080/manager/status?XML=true'
user : 'admin'
pass : 'admin'

localhost:
name: 'local'
url: 'http://localhost:8080/manager/status?XML=true'
connector_name: http-nio-8080

**Comment by ilyam8** [comment]
closed in favor of #7499

**Comment by ilyam8** [comment]
you didnt add user/pass to the job with `connector_name`

**Comment by somir** [comment]
Hi @ilyam8 
Thanks it's working fine. I gave you pain last couple of days. thanks again for your support. 

I have a question, Is it possible to collect remote server data without setup netdata in remote machine?

BR//
Somir

**Comment by ilyam8** [comment]
> I have a question, Is it possible to collect remote server data without setup netdata in remote machine?

Yes, just add another job, change `127.0.0.1` to remote server ip address

```
remote:
  url: 'http://127.0.0.1:8080/manager/status?XML=true'
  user: 'admin'
  pass: 'admin'
```

**Comment by somir** [comment]
thanks
