### ISSUE TITLE
api calls 403 error httpd CentOS 6.10

### ISSUE THREAD

**Issue by kkoomen** [netdata/netdata#7568]
##### Bug report summary

I use httpd on CentOS 6.10 and the calls to get all the data do work for several minutes, but eventually it stops working (the data is not updating anymore) and I'm getting 403 errors for the api calls. See screenshot:

![Screenshot 2019-12-18 at 10 20 35](https://user-images.githubusercontent.com/10693490/71051339-fe0dbe00-2182-11ea-8e7d-84bd415b1921.png)

The above errors occur because the response returns a server 403.

![Screenshot 2019-12-18 at 11 42 36](https://user-images.githubusercontent.com/10693490/71054061-85f7c600-218b-11ea-8fc7-1bcd300b87b1.png)

##### OS / Environment

CentOS release 6.10 (Final)

##### Netdata version (ouput of `netdata -V`)

netdata v1.19.0-129-nightly

##### Steps To Reproduce

1) Setup netdata

2) Add the following configuration in `/etc/netdata/netdata.conf`

```
[global]
    access log = none
[web]
    bind to = localhost
    enable gzip compression = no
```

3) Add the following apache directives to `/etc/httpd/conf/httpd.conf` (or in my case: a virtualhost-specific config file located at `/etc/httpd/conf/sites-available/my-website.conf.vhost`):

```
RewriteEngine On
ProxyRequests Off
ProxyPreserveHost On

ProxyPass "/" "http://localhost:19999/" connectiontimeout=5 timeout=30 keepalive=on
ProxyPassReverse "/" "http://localhost:19999/"
```

##### Expected behavior

It should be able to do api calls without getting a 403.

**Comment by kkoomen** [comment]
I am seeing errors in my httpd log that say this (replaced my production url with `my-website.com`):

```
[Wed Dec 18 12:09:32 2019] [info] Initial (No.1) HTTPS request received for child 10 (server my-website.com:443)
[Wed Dec 18 12:09:32 2019] [error] [client 67.212.238.232] client denied by server configuration: proxy:http://localhost:19999/api/v1/alarms, referer: https://my-website.com/
[Wed Dec 18 12:09:32 2019] [debug] mod_proxy_http.c(56): proxy: HTTP: canonicalising URL //localhost:19999/error/403.html
[Wed Dec 18 12:09:32 2019] [debug] proxy_util.c(1525): [client 67.212.238.232] proxy: http: found worker http://localhost:19999/ for http://localhost:19999/error/403.html, referer: https://my-website.com/
[Wed Dec 18 12:09:32 2019] [debug] mod_proxy.c(1026): Running scheme http handler (attempt 0)
[Wed Dec 18 12:09:32 2019] [debug] mod_proxy_http.c(2018): proxy: HTTP: serving URL http://localhost:19999/error/403.html
[Wed Dec 18 12:09:32 2019] [debug] proxy_util.c(2102): proxy: HTTP: has acquired connection for (localhost)
[Wed Dec 18 12:09:32 2019] [debug] proxy_util.c(2158): proxy: connecting http://localhost:19999/error/403.html to localhost:19999
[Wed Dec 18 12:09:32 2019] [debug] proxy_util.c(2289): proxy: connected /error/403.html to localhost:19999
[Wed Dec 18 12:09:32 2019] [debug] mod_proxy_http.c(1775): proxy: start body send
[Wed Dec 18 12:09:32 2019] [debug] mod_proxy_http.c(1885): proxy: end body send
```

**Comment by Saruspete** [comment]
Greetings, 

The error message (error/403.html) seems to come from apache. It's usually an alias that takes over real pages. Also from the line 
> [Wed Dec 18 12:09:32 2019] [error] [client 67.212.238.232] client denied by server configuration
its looks like an apache issue rather than a netdata one.

If you say it's working as expected then stops, are you using a load balancer (so the IP changes and is not allowed) or an anti-flood / throttling feature in apache ?

**Comment by kkoomen** [comment]
The 403 comes from the production server, yes. We have no load balancers at all and I have no idea about anti-flood / throttling things in apache. I can recreate a clean VPS to see if this happens out of the box. If not, then it's something specifically configured at the production server.

**Comment by kkoomen** [comment]
> [...] or an anti-flood / throttling feature in apache ?

I just saw that `/etc/httpd/conf.d/mod_evasive.conf` exists on the server, which could be the problem.

**Comment by ilyam8** [comment]
Indeed
https://github.com/netdata/netdata/issues/2011

**Comment by ilyam8** [comment]
@joelhans we need to mention it in the docs

**Comment by kkoomen** [comment]
@ilyam8 I've set DOSPageCount to 50 for the virtualhost itself and this does seem to fix it. I also suggest it should be documented clearly. Took me a whole day to figure out this problem. Thanks for your time and help.

**Comment by JialuZhang** [comment]
In your posted configuration,
```
RewriteEngine On
```
the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
