### ISSUE TITLE
Initial page load too slow

### ISSUE THREAD

**Issue by kkoomen** [netdata/netdata#7569]
##### Feature idea summary

The initial time for me to see statistics takes about 20 seconds after a "hard refresh" aka non-cached refresh. I don't know if it is me or that everyone has it, but it takes a lot of time for all the requests to be loaded.

Can this be improved? I don't know exactly how everything works under the hood, but it shouldn't take that long to me.

##### Expected behavior

The page should load fast, not 20 seconds.

**Comment by Saruspete** [comment]
Greetings,

I'm not seeing this behavior on my side, especially something as long as 20s.
Can you do a profiling with your browser, and attach the resulting report ?

Also check your network path: packet drop, fragmentation due to incoherent MTU, bad ethernet cable causing half duplex, tcp packet reordering causing retransmit...

**Comment by thiagoftsm** [comment]
Hi @kkoomen ,

Are you using SSL with your netdata? I remember that I had problem in the past with browser cache after I enable SSL on Netdata, but after I use "CTRL+SHIFT+R" my browser did not have more problems.

best regards!

**Comment by ilyam8** [comment]
I think @kkoomen is accessing netdata via apache.

**Comment by ilyam8** [comment]
@kkoomen if i am right, it would be nice you do "hard-refresh" but bypass apache.

**Comment by kkoomen** [comment]
> I think @kkoomen is accessing netdata via apache.

You are 100% right.

**Comment by ilyam8** [comment]
You've fixed your [problem with `mod_evasive`](https://github.com/netdata/netdata/issues/7568). Did it solve `Initial page load too slow`?

**Comment by kkoomen** [comment]
Nope, it did not solve it, otherwise I would've closed both issues.

**Comment by Saruspete** [comment]
@kkoomen can you upload a profiling report with your browser and attach it here ?

**Comment by kkoomen** [comment]
@Saruspete Sorry, totally forgot about that. However, #7568 could potentionally have fixed it. My load time is 8-9 seconds now. Is that as expected?
