### ISSUE TITLE
Cannot restrict access to web dashboard with access list

### ISSUE THREAD

**Issue by thomas-jakemeyn** [netdata/netdata#7586]
##### Question summary

I am using `netdata v1.19.0-138-nightly` and trying to restrict the access to the dashboard and badges to 2 IPv4 addresses (no wildcard) by leveraging the [access list](https://docs.netdata.cloud/web/server/#access-lists) feature. I uncommented the 2 `allow` parameters below. I left all the other `allow` parameters commented out since their default values do make sense.

```yaml
allow dashboard from = localhost IP1 IP2
allow badges from = localhost IP1 IP2
```

This does not work as expected as I can still access the dashboard from any IP address. Am I missing something?

##### OS / Environment

CentOS (not containerized)

##### Component Name

web

##### Expected results

I should only be able to access the dashboard from the 2 configured IP addresses.

**Comment by Saruspete** [comment]
Greeting,

Silly question, but asking nonetheless to rule it out: did you restart netdata after doing the config modification, and clear the cache of your browser ?

Also, can you post the relevant logfiles (in `/var/log/netdata/access.log`) related to your http queries ?

**Comment by thomas-jakemeyn** [comment]
Yes I did restart netdata and cleared my browser cache. I even tried from an incognito window to be sure.

**Comment by ilyam8** [comment]
I testes it on latest, it works as expected.

my `[web]` section

```console
	allow dashboard from = localhost 192.168.56.2 192.168.56.3
	allow badges from = localhost 192.168.56.2 192.168.56.3
```

My IP is 192.168.56.1, i cant access netdata dashboard

> You are not allowed to access this resource.

**Comment by thomas-jakemeyn** [comment]
Do I need to uncomment the bind parameter and change its value maybe?

**Comment by ilyam8** [comment]
You don't. All i did is i set `allow dashboard from/allow badges from`.

i am on `netdata v1.19.0-150-g23973d7f` btw.

Try `allow dashboard from = !*`, it is deny all access.

**Comment by thiagoftsm** [comment]
Hi @thomas-jakemeyn ,

I tested now with the following options:

```
allow dashboard from = localhost
allow badges from = localhost
```

And I received in my browser the message `You are not allowed to access this resource.` as expected. When I read my `access.log` I also have the following message for the request:

```
2019-12-19 21:41:15: 10: 8733 '[192.168.0.12]:34106' 'DATA' (sent/all = 64/44 bytes -41924418349339893760%, prep/sent/total = 0.01/0.03/0.04 ms) 403 '/'
```

What are you seeing in your netdata `access.log` when there is a request from an ip different of the ips listed?

**Comment by thomas-jakemeyn** [comment]
Thank you all for your support!

I re-tested today against the same `netdata` instance (that was still running) **without changing anything** and it worked!
- From home, I got the message `You are not allowed to access this resource`.
- Through my office VPN, I could access the `netdata` web dashboard.

Then, I decided to re-run my (idempotent) Ansible playbook to re-provision `netdata` and I got the same behavior as before: I could access `netdata` from home while I should not be allowed to.

Before the provisioning, the access log contains `403`s when accessing from home and `200`s when accessing over VPN. After the provisioning, it contains only `200`s for both IP addresses. I did not change anything in the Ansible playbook...

**Comment by thomas-jakemeyn** [comment]
Well, if I just restart the Azure VM, then the access list works as expected. So it could be linked to the fact that my configuration changes are not properly applied. This is how I do it with Ansible.

```yaml
    ##################################################
    # Apply configuration settings

    - name: "Restart Netdata to apply configuration changes"
      systemd:
        name: "netdata"
        daemon_reload: "yes"
        enabled: "yes"
        state: "started"
```

**Comment by thomas-jakemeyn** [comment]
I made a mistake: `"started"` should have been `"restarted"`. With that change, everything works as expected. My bad.

Once again, thank you for your prompt reaction!
