### ISSUE TITLE
netdata occasional cpu usage rate 67%

### ISSUE THREAD

**Issue by markwone** [netdata/netdata#7591]
![@@1576846367294](https://user-images.githubusercontent.com/58732509/71256127-ded18500-236a-11ea-9163-6f374777f6b3.png)

##### OS / Environment
arm linux zynq 7020
##### Netdata version (ouput of `netdata -V`)
V1.19

**Comment by mfundul** [comment]
Is this with an ARM cortex A9 processor? For such embedded platforms maybe switching from `memory mode = dbengine` to `memory mode = ram` or `memory mode = save` may reduce CPU utilization.

**Comment by markwone** [comment]
> Is this with an ARM cortex A9 processor? For such embedded platforms maybe switching from `memory mode = dbengine` to `memory mode = ram` or `memory mode = save` may reduce CPU utilization.

yes, thank you，let me  try！

**Comment by markwone** [comment]
> memory mode

if the default mode is not save？

**Comment by mfundul** [comment]
> 
> 
> > memory mode
> 
> if the default mode is not save？

This has changed to `dbengine`. Moreover, a lot of new collectors have been added so you should disable charts that you don't need that have a lot of dimensions. Lastly, you can increase the `update_every` period from 1 to 2 for further reduction.

**Comment by markwone** [comment]
> > > memory mode
> > 
> > 
> > if the default mode is not save？
> 
> This has changed to `dbengine`. Moreover, a lot of new collectors have been added so you should disable charts that you don't need that have a lot of dimensions. Lastly, you can increase the `update_every` period from 1 to 2 for further reduction.

I changed update every (flushInterval) to 10, but it still feels like updating once every 1s。
and how to disable charts than I dont want？

**Comment by mfundul** [comment]
> 
> 
> > > > memory mode
> > > 
> > > 
> > > if the default mode is not save？
> > 
> > 
> > This has changed to `dbengine`. Moreover, a lot of new collectors have been added so you should disable charts that you don't need that have a lot of dimensions. Lastly, you can increase the `update_every` period from 1 to 2 for further reduction.
> 
> I changed update every (flushInterval) to 10, but it still feels like updating once every 1s。
> and how to disable charts that I dont want？

You should read [this](https://docs.netdata.cloud/docs/performance/) guide.

**Comment by ilyam8** [comment]
@markwone coulnd you sent a snapshot to `ilya@netdata.cloud` ?

**Comment by markwone** [comment]
> ilya@netdata.cloud

ok， I already sent it to you by email

**Comment by ilyam8** [comment]
@markwone it is a screenshot (`.png`), see `export/save a netdata snapshot` button  on the dashboard top bar

**Comment by markwone** [comment]
> @markwone it is a screenshot (`.png`), see `export/save a netdata snapshot` button on the dashboard top bar

sorry，it run on the company intranet and I cannot be exported to you，only can screenshot

**Comment by markwone** [comment]
> @markwone it is a screenshot (`.png`), see `export/save a netdata snapshot` button on the dashboard top bar
OK，I make it run on  extranet。 I already sent it‘s snapshot to you by email

**Comment by markwone** [comment]
> @markwone it is a screenshot (`.png`), see `export/save a netdata snapshot` button on the dashboard top bar

Have you received my email about snapshot？
not only Occasionally 67%， but also usually around 8% on my embedded device

**Comment by ilyam8** [comment]
hi @markwone yes i received it but i see not data (all charts are empty) when i import it. Have you tried to import it yourself?

___

We need to understand what uses a lot of cpu. You can do it yourself using ...netdata 😄 Check `Application` and `Netdata Monitoring` sections on the dashboard.

**Comment by markwone** [comment]
> hi @markwone yes i received it but i see not data (all charts are empty) when i import it. Have you tried to import it yourself?
> 
> We need to understand what uses a lot of cpu. You can do it yourself using ...netdata  Check `Application` and `Netdata Monitoring` sections on the dashboard.

yes，I try  to import it, all charts are empty too

**Comment by cakrit** [comment]
@markwone I am closing this because there hasn't been a response in a while. If you still have the issue with the latest netdata, please comment with some more info on how we can replicate the issue and we'll reopen it.
