### ISSUE TITLE
NetData suddenly not working (on 3 different servers) and port 19999 not listening?

### ISSUE THREAD

**Issue by newalphamedia** [netdata/netdata#7598]
**UPDATE: Not sure why, but netdata simply needed restarting. I ran this command: systemctl restart netdata**

Hi - running NetData on 3 different servers with NGINX on Ubuntu OS (all same setup). I noticed today when attempting to access netdata that I receive 502 Bad Gateway errors. I noted in the error logs:

_2019/12/20 22:43:42 [error] 7810#7810: *2340156 connect() failed (111: Connection refused) while connecting to upstream, client: 175.37.111.42, server: *********, request: "GET /netdata/ HTTP/1.1", upstream: "http://127.0.0.1:19999/", host: "*********"_

The strange thing is this has occurred for all 3 servers at the same time, with no changes being made on my part. NetData has been running perfectly fine for many months. I checked if port 19999 is accessible with netstat commands but port 19999 is not listed/empty response (command: netstat -nat | grep 19999).

**Comment by ilyam8** [comment]
Hi.

I guess following command returns nothing?

> ps faxu | grep [n]etdata


Try to update to the latest and restart netdata

**Comment by newalphamedia** [comment]
Hi - I attempted a restart and that worked. Somehow netdata service on all 3 servers must have stopped running. If it helps anyone else, I suggest restarting netdata to see if that resolves it: **systemctl restart netdata**

**Comment by ilyam8** [comment]
Yes, there was a bug 🙈  It is fixed on latest.
