### ISSUE TITLE
How to use vim instead of vi for the 'edit-config'

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7602]
##### Question summary
I can change the `vi` in script of `edit-config` to `vim` as below:
`EDITOR="${EDITOR-vim}"`

but each time after its upgraded, it change back to vi again, can you advice how to keep the vim as the editor for the 'edit-config' tool?

**Comment by ilyam8** [comment]
Hi, are you on debian/ubuntu? If yes use

> sudo update-alternatives --config editor

and choose `vim.basic` from the list

**Comment by startryst** [comment]
No, on CentOS

Sent from iPhone

**Comment by ilyam8** [comment]
Ok, see

> https://wiki.centos.org/EdHeron/EditorDefaultNano

**Comment by startryst** [comment]
> Ok, see
> 
> > https://wiki.centos.org/EdHeron/EditorDefaultNano

Thanks, that's exactly what i'm looking for.
:-)
