### ISSUE TITLE
lm-sensors doesn't come with predefined alarms?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7603]
##### Question summary
I've configured the sensor according to this [link](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/sensors/sensors.conf), but looks there isn't any predefined alarms, right? So I need to build my own into the health.d folder?

**Comment by ilyam8** [comment]
Yes, you are right. See

> https://docs.netdata.cloud/health/quickstart/#write-a-new-health-entity

**Comment by startryst** [comment]
Thanks.
