### ISSUE TITLE
Persist custom dashboards in docker container

### ISSUE THREAD

**Issue by Wibbbs** [netdata/netdata#7604]
I am running Netdata in a docker container and have created a custom dashboard html. I would like to serve this custom dashboard from the netdata server. From what I understand I need to place the html in the /usr/share/netdata/web directory, which works great. My issue is that on a container update or recreation, my custom dash is lost as the web directory is rebuilt.

I have tried mapping a volume to the web directory as below:

```
volumes:
  ./web:/usr/share/netdata/web
```

When I do this the web directory ends up being empty and the custom dash does not load at all. Is there anyway to persist a custom dashboard with the docker image?

**Comment by stelfrag** [comment]
Hi @Wibbbs 

I am assuming you are using a docker compose as described in [Install Netdata with Docker](https://docs.netdata.cloud/packaging/docker/) and you try to save (expect to) the data under `./web` at the host.

I will try to recreate this to get an idea of what's going on .

Its quite possible the error.log of the Netdata agent in the container give us a clue as to what it is happening (If you can get that would be helpful)

**Comment by amoss** [comment]
If you want to take a copy of the dashboard configuration and place it into the image then you could do this at build time with a COPY command in the `Dockerfile`. For example to overwrite that directory on our standard image you could use:
```
FROM netdata/netdata:latest
COPY web/ /usr/share/netdata/web/
```
Any container that you launch from this image will then contain your custom configuration. This works in a single direction - from host to container. Is this what you are trying to achieve or do you need to store changes from `/usr/share/netdata/web`on the host?

**Comment by prologic** [comment]
@Ferroin @cakrit Hmm this is likely still an issue and I _think_ we should still fix/address this. It feels very similar to persisting the Agent GUID problem. Worth adding this to an EPIC to overhaul our official Docker image(s) and their documentation.

**Comment by cakrit** [comment]
> @Ferroin @cakrit Hmm this is likely still an issue and I _think_ we should still fix/address this. It feels very similar to persisting the Agent GUID problem. Worth adding this to an EPIC to overhaul our official Docker image(s) and their documentation.

You are correct, we've already discussed the need to add a LOT more features and documentation to our docker image. Please create that issue (I wouldn't call it an epic). Custom dashboards is one thing I missed from the k8s helmchart as well. I think that a better solution than the one suggested here is to instruct users to put their custom dashboards in a subdirectory under `/usr/share/netdata/web` and mount a volume for that as well.

**Comment by prologic** [comment]
> You are correct, we've already discussed the need to add a LOT more features and documentation to our docker image. Please create that issue (I wouldn't call it an epic). Custom dashboards is one thing I missed from the k8s helmchart as well. I think that a better solution than the one suggested here is to instruct users to put their custom dashboards in a subdirectory under `/usr/share/netdata/web` and mount a volume for that as well.

Agreed. I'll file an issue. #8055

**Comment by loulich** [comment]
Hi @Wibbbs 
I've you got find any solution ??

Thanks
