### ISSUE TITLE
bootstrap4 with custom netdata dashboard

### ISSUE THREAD

**Issue by AlexandreLicinio** [netdata/netdata#7606]
Hello, 
I have a webpage running the latest bootstrap4 framework.
When i want to add a custom dashboard into it, all the web page displays bootstrap3 css.
It there any way to fix it ?

The problem appears only with dashboards, not with badges.

Thanks

**Comment by Tommuh** [comment]
It adds bootstrap by default, you can disable this.
Add following in the header before the dashboard.js.

```
    <script type="text/javascript">      
        var netdataNoBootstrap = true;     
    </script>  
```

**Comment by AlexandreLicinio** [comment]
Thanks @Tommuh i also notice that there is a js conflict.

`

      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <script src="//cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.4.0/clipboard.min.js"></script>

      <script type="text/javascript">var netdataNoBootstrap = true;</script>
      <script type="text/javascript" src="${netdata}/dashboard.js"></script>
      <script type="text/javascript"> var netdataTheme = 'default'; // white netdata theme </script>
      <script type="text/javascript">
        NETDATA.options.current.destroy_on_hide = true;
        NETDATA.options.current.eliminate_zero_dimensions = true;
        NETDATA.options.current.concurrent_refreshes = true;
        NETDATA.options.current.parallel_refresher = true;
        NETDATA.options.current.stop_updates_when_focus_is_lost = false;
      </script>
    </head>
    <body>

      <div data-netdata="system.cpu"
          data-host="${netdata}"
          data-chart-library="dygraph"
          data-width="100%"
          data-height="100%"
          ></div>
`

if the line: `<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>` is present in the **HEAD** section then the chart will not display.
But if i delete it i lost all the js functions related to bootstrap but i get the chart !

Do you know how to fix it please ?

**Comment by AlexandreLicinio** [comment]
Hmm no, my

**Comment by Tommuh** [comment]
I was typing a reponse, glad it got fixed.
