### ISSUE TITLE
How to remove a collector?

### ISSUE THREAD

**Issue by phantomlsh** [netdata/netdata#7610]
##### Question summary

First I want to connect to a redis database, so I created ```/etc/netdata/python.d/redis.conf``` and configed it. Then I found that I have made a stupid mistake on the name, so I went to redis.conf and change the name. Bad thing is that, in the dashboard, the old name of redis (Redis [oldname]) still exists and there is a alarm considering it losing connection!

##### OS / Environment

CentOS 7 64bit

##### Component Name

python.d.plugin

##### Expected results

Remove the Redis [oldname] collector, so that it will not appear on the right hand side of the dashboard, or in the alarm.

**Comment by ilyam8** [comment]
Hi @phantomlsh 

> Remove the Redis [oldname] collector, so that it will not appear on the right hand side of the dashboard, or in the alarm.

Rename/remove the job in the `/etc/netdata/python.d/redis.conf` and restart `netdata.service`

**Comment by phantomlsh** [comment]
Thank you very much. I found out that if using stream, I must restart the netdata of the main server instead of only the node. THX!
