### ISSUE TITLE
How to make the plugin to work for alarm, but not to show the chart in the dashboard?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7611]
##### Question summary
As the subject, not necessary to show the chart, but wish to define certain alarms for the chart, how can I hide the chart or not showing in the dashboard?

**Comment by ilyam8** [comment]
Hi @startryst 

It is impossible.

**Comment by startryst** [comment]
> Hi @startryst
> 
> It is impossible.

Thanks.
