### ISSUE TITLE
How can I customized this field in the dashboard to other text?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7612]
##### Question summary
![Screen Shot 2019-12-24 at 3 56 42 PM](https://user-images.githubusercontent.com/22472752/71401889-3707d000-2666-11ea-973a-f4f6151bcc62.jpg)
The `FPing Latency for host 10.0.4.1` is the title, I can change that by add a per-chart configuration, but the top one(highlighted above of the yellow box) which is the target host to pint, but it shows without the dot, so is there any place I can configure to give it a name of that field?

**Comment by ilyam8** [comment]
Well, i dont know why but this is hardcoded in the `fping` tool

```console
test@DEB10-1:/opt/netdata/usr/libexec/netdata/plugins.d$ fping -N 8.8.8.8 -l -Q 1
CHART fping.8_8_8_8_packets '' 'FPing Packets for host 8.8.8.8' packets '8_8_8_8' fping.packets line 110020 1
```

For some reason it replaces `.` with `_` in family. You see it as space on the dashboard.

I think you can change it using per-chart configuration.

**Comment by ilyam8** [comment]
ok, that is it

https://github.com/schweikert/fping/blob/39a567d1629ed62caf1fe255124e55e36083e4cd/src/fping.c#L2393-L2400

We do it because we use `name` as a chart id.

@vlvkobal see

https://github.com/schweikert/fping/blob/develop/src/fping.c#L194

>  char* name; /* name as given by user */

and we mangle it if `netdata_flag`.

**Comment by startryst** [comment]
> Well, i dont know why but this is hardcoded in the `fping` tool
> 
> ```
> test@DEB10-1:/opt/netdata/usr/libexec/netdata/plugins.d$ fping -N 8.8.8.8 -l -Q 1
> CHART fping.8_8_8_8_packets '' 'FPing Packets for host 8.8.8.8' packets '8_8_8_8' fping.packets line 110020 1
> ```
> 
> > '8_8_8_8'
> 
> For some reason it replaces `.` with `_` in the family. You see it as spaces on the dashboard.
> 
> I think you can change it using per-chart configuration.

The per-chart configuration only change the title, which is `FPing Latency for host 10.0.4.1`, but couldn't fine the parameter to adjust the larger text of the IP from per chart configuration.

**Comment by ilyam8** [comment]
You need to find your `fping.*` charts (3 charts per host) and change `family` there.

See my example

```bash
[fping.8_8_4_4_packets]
	history = 5
	# enabled = yes
	# cache directory = /opt/netdata/var/cache/netdata/fping.8_8_4_4_packets
	# chart type = line
	# type = fping
	family = 8.8.4.4
[fping.8_8_4_4_quality]
	history = 5
	# enabled = yes
	# cache directory = /opt/netdata/var/cache/netdata/fping.8_8_4_4_quality
	# chart type = area
	# type = fping
	family = 8.8.4.4
[fping.8_8_4_4_latency]
	history = 5
	# enabled = yes
	# cache directory = /opt/netdata/var/cache/netdata/fping.8_8_4_4_latency
	# chart type = area
	# type = fping
	family = 8.8.4.4
```

<img width="1326" alt="Screenshot 2019-12-25 at 08 43 30" src="https://user-images.githubusercontent.com/22274335/71437694-06ba4300-26f3-11ea-9ed1-13615e2a9baa.png">

**Comment by startryst** [comment]
> You need to find your `fping.*` charts (3 charts per host) and change `family` there.
> 
> See my example
> 
> ```shell
> [fping.8_8_4_4_packets]
> 	history = 5
> 	# enabled = yes
> 	# cache directory = /opt/netdata/var/cache/netdata/fping.8_8_4_4_packets
> 	# chart type = line
> 	# type = fping
> 	family = 8.8.4.4
> [fping.8_8_4_4_quality]
> 	history = 5
> 	# enabled = yes
> 	# cache directory = /opt/netdata/var/cache/netdata/fping.8_8_4_4_quality
> 	# chart type = area
> 	# type = fping
> 	family = 8.8.4.4
> [fping.8_8_4_4_latency]
> 	history = 5
> 	# enabled = yes
> 	# cache directory = /opt/netdata/var/cache/netdata/fping.8_8_4_4_latency
> 	# chart type = area
> 	# type = fping
> 	family = 8.8.4.4
> ```
> 
> <img alt="Screenshot 2019-12-25 at 08 43 30" width="1326" src="https://user-images.githubusercontent.com/22274335/71437694-06ba4300-26f3-11ea-9ed1-13615e2a9baa.png">

Got you, wasn't aware `family` is the one for that
