### ISSUE TITLE
Redis plugin not working any more after the last nightly update.

### ISSUE THREAD

**Issue by Tommuh** [netdata/netdata#7613]
Hello,

Since the last nightly update **v1.19.0-180-nightly** the Redis plugin is not working any more.
Redis is working fine, I can connect to it and I can set and retrieve keys.

This is the error from the error log:

> 
> 2019-12-24 09:09:02: python.d INFO: plugin[main] : [redis] built 1 job(s) configs
> 2019-12-24 09:09:02: python.d WARNING: plugin[main] : redis[localhost] : unhandled exception on check : TypeError('decoding Unicode is not supported',), skipping the job

The debug log is enabled, but is empty.

Is there a way to fix this? 
I had a minor heart attack last night, because I thought Redis was down. :')

Cheers, Tom

**Comment by ilyam8** [comment]
@Tommuh fixed, thx for reporting 😅

**Comment by Tommuh** [comment]
This is working again! Thank you for the quick fix.
