### ISSUE TITLE
Make errors when installing

### ISSUE THREAD

**Issue by LetianXiang** [netdata/netdata#7619]
I could not install netdata after I cloned it, entered the directory and tried
>sudo ./netdata-installer.sh

Following are the result shown
> --- Backup existing netdata configuration before installing it --- 
 --- Install netdata --- 
[/Users/letianxiang/Documents/Developer/netdata]# make install 
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-recursive
Making install in diagrams
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in system
/usr/bin/install -c -d /etc/netdata
 .././install-sh -c -d '/etc/netdata'
 /usr/bin/install -c edit-config '/etc/netdata'
Making install in tests
make[3]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/usr/libexec/netdata/plugins.d'
mkdir: /usr/libexec/netdata: Read-only file system
mkdir: /usr/libexec/netdata: No such file or directory
make[3]: *** [install-dist_pluginsSCRIPTS] Error 1
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive

My OS is macOS 10.15.3 Beta (19D49f).

can anybody help?

**Comment by Ferroin** [comment]
Check out the docs for [installation on macOS](https://docs.netdata.cloud/packaging/installer/#macos).. There are some extra steps that are needed because we can't install directly to `/usr` on macOS.
