### ISSUE TITLE
Show the warn/critical as a line/threshold in the dashboard (with distinct line color/type)

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7621]
##### Feature idea summary
So, in the dashboard, would like to see a contact line which defined by the almarm WARN/CRITICAL, so that when checking the dashboard, will know how far the operating is away from the alarm WARN/CRITICAL, or even cross the WARN/CRITICAL

**Comment by Ferroin** [comment]
Note that this is probably not as trivial as it might sound, since alarm definitions can have conditionals in them to set different trip points based on any of a number of things, and you can nest those conditionals to a theoretically arbitrary depth.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
