### ISSUE TITLE
Centralized configuration for all nodes managed?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7622]
##### Feature idea summary
Not sure whether we dan do today, but now, I need to configure each /etc/netdata/*.conf for each node, even for the same change, need to do it over again and again....

**Comment by thiagoftsm** [comment]
Hi @startryst ,

We are already thinking about a feature like this, please, take a look on #6432  to confirm that we are going in a direction that will help not only you but the whole community.

**Comment by ilyam8** [comment]
it is dup of #6432
