### ISSUE TITLE
Monitoring in spingboot，What's the version of spring-boot-starter-actuator？

### ISSUE THREAD

**Issue by GoogleQian** [netdata/netdata#7624]
I can't find the publicmetrics interface in which package I changed many versions of the actuator, but I can't find it
![image](https://user-images.githubusercontent.com/38888609/71456576-04c8b080-27d5-11ea-9238-66961e2cb6a8.png)

**Comment by ilyam8** [comment]
@Wing924 please halp

**Comment by Wing924** [comment]
@GoogleQian 
Could you tell me which springboot version do you use? 1.x or 2.x?

If you use 1.x, any versions of spring-boot-starter-actuator should work. (I tested with 1.5.4)

if you use 2.x, you don't need this settings.

**Comment by GoogleQian** [comment]
I didn't specify a version of 2. X at first, and I couldn't find it. I was so depressed

**Comment by Wing924** [comment]
@GoogleQian 
You should check which springboot version you use, because there're 2 modules: 
* springboot module in python.d is for 1.x
* springboot2 module in go.d is for 2.x

If you don't set version, it may be 2.x.
