### ISSUE TITLE
ERROR 405: Cannot download charts index from server

### ISSUE THREAD

**Issue by jameswagoner** [netdata/netdata#7625]
##### Bug report summary

Alert window loads with ERROR 405: Cannot download charts index from server: http://192.168.4.22:19999/api/v1/charts

##### OS / Environment

Ubuntu 18.04

##### Netdata version (ouput of `netdata -V`)

netdata v1.14.0-rc0-20-nightly

##### Component Name

Web UI

##### Steps To Reproduce

Hit up url in Chrome Browser

##### Expected behavior

Should see the dashboard with charts look all super fly

##### Additional notes

I can clear my application cache for the site and can see the dashboard run for a bit and then fairly quickly, all the charts clear and error messages complaining about not loading the urls.

**Comment by ilyam8** [comment]
Hi @jameswagoner. Please update to the latest, `v1.14.0-rc0-20-nightly` is pretty old.
