### ISSUE TITLE
Investigate correct capabilities for plugins that require elevated privileges.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#7631]
There are a number of our process-external plugins that require special permissions which are currently using SUID to obtain the required privileges. These should be updated wherever possible to use appropriate capabilities instead of being SUID root.

**Comment by Ferroin** [comment]
Relevant to #6619.

**Comment by cosmix** [comment]
Related to https://github.com/netdata/netdata/issues/7487

**Comment by Ferroin** [comment]
This still needs some work, but is overall mostly just research that needs to be done so that we flag individual plugins with the correct capabilities.
