### ISSUE TITLE
Docker container show container id instead of name

### ISSUE THREAD

**Issue by David-Lor** [netdata/netdata#7633]
##### Bug report summary

Like in the issues https://github.com/netdata/netdata/issues/5112 and https://github.com/netdata/netdata/issues/2995, my Netdata instance is not showing the container names, but their IDs/auto-generated-hostnames. But in my case, the Netdata instance is installed directly on the host, not through Docker.

This happens for containers created through docker-run and docker-compose alike.

##### OS / Environment

Debian 10 Buster

##### Netdata version (output of `netdata -V`)

netdata v1.19.0-61-g55bdae1

##### Component Name

cgroups?

##### Expected behavior

Show the container names instead of their IDs.

**Comment by vlvkobal** [comment]
Please grep for `cgroup-name.sh` in `error.log`. What messages do you have there?

**Comment by stelfrag** [comment]
Hi @David-Lor 

So instead of the container ids you want the names as in the following example (name autp generated by docker in this case)

```
CONTAINER ID        IMAGE                    COMMAND              CREATED             STATUS              PORTS               NAMES
53e9ff09fe71        alpine                   "/bin/ash"           2 hours ago         Up 2 hours                              youthful_matsumoto
8a6122686796        netdata/netdata:latest   "/usr/sbin/run.sh"   2 hours ago         Up 2 hours          19999/tcp           naughty_ganguly
```

So 

53e9ff09fe71  maps to ***youthful_matsumoto***
8a6122686796 maps to ***naughty_ganguly***

**Comment by stelfrag** [comment]
Hi @David-Lor

I verified that the code will attempt to map the name if there is permission to run the docker command. In order for netdata to be able to run the docker command you need to give permission the the netdata user. This is done by adding the netdata user  to the `docker` group (create and configure if it doesn't exist)

However you may want to **weigh the security concerns** before you do that. 
Check the section [Giving group access to the Docker socket](https://docs.netdata.cloud/packaging/docker/)

So if you do give it  permission, it will correctly map the name. e.g. : 

```
2020-01-02 13:42:14: cgroup-name.sh: INFO: Running command: docker ps --filter=id="0bb22454598b9f61f7b1d26487d31d37f7acece50c6885c00be483014de1acf9" --format="{{.Names}}"
2020-01-02 13:42:14: cgroup-name.sh: INFO: docker container '0bb22454598b9f61f7b1d26487d31d37f7acece50c6885c00be483014de1acf9' is named 'sleepy_golick'
2020-01-02 13:42:14: cgroup-name.sh: INFO: cgroup 'docker_0bb22454598b9f61f7b1d26487d31d37f7acece50c6885c00be483014de1acf9' is called 'sleepy_golick'
```


*Note: The above will not work if the docker command is installed via snap however (it will complain about netdata home directory is not under /home) and it will require addition tweaking*

**Comment by David-Lor** [comment]
@stelfrag Adding the netdata user to the docker group fixed the problem

**Comment by art1415926535** [comment]
> @n3roGit
> 
> > Whats to do when running Netdata in a container?
> 
> > Adding the netdata user to the docker group fixed the problem
> 
> have you tried it?

---

```bash
sudo usermod -aG docker netdata
```

```
usermod: user 'netdata' does not exist
```

**Comment by ilyam8** [comment]
https://learn.netdata.cloud/docs/agent/packaging/docker#giving-group-access-to-the-docker-socket-less-safe

**Comment by art1415926535** [comment]
> https://learn.netdata.cloud/docs/agent/packaging/docker#giving-group-access-to-the-docker-socket-less-safe


Thanks!

**Comment by rahulonmars** [comment]
> https://learn.netdata.cloud/docs/agent/packaging/docker#giving-group-access-to-the-docker-socket-less-safe

This is still not working for me.
I tried setting the environment variable inside the container. It's still not picking the container name.

I also have created a user - netdata on my host machine and added that to the docker group.

P.S: netdata is running inside the container.
