### ISSUE TITLE
Operate safely and without third party servers

### ISSUE THREAD

**Issue by l-jonas** [netdata/netdata#7634]
##### Feature idea summary

It should be easy to configure netdata to operate without any connections to third party servers

##### Current behavior

I did

- set a custom registry (https://0.0.0.0)
- did the telemetry opt out
- configured a CSP-Header at a nginx which is before netdata: ``default-src 'self' 'unsafe-eval' 'unsafe-inline'; base-uri 'none'; block-all-mixed-content; form-action 'none'; frame-ancestors 'none'`` (based on my knowledge, there is no word about such a thing in the documentation)

##### Expected behavior

- it should work without unsafe-eval and unsafe-inline (security best practices), but it does not
- a recommendation for setting a CSP in the documentation - a CSP in the default configs
- this strict CSP should not catch any requests to third party servers because they should not occur, but it does
  - ``https://0.0.0.0/api/v1/registry?action=access&machine=...`` (well, this one is actually allowed, but a flag to disable the registry feature would be better)
  - ``https://netdata.cloud/account/sso-agent?id=...``
  - ``https://api.github.com/repos/netdata/netdata/releases/latest?=...``

**Comment by cakrit** [comment]
Registry:
https://learn.netdata.cloud/docs/agent/registry shows how to run your own registry

sso-agent:
That has been disabled in more recent versions.

New version checks:
I don't recall seeing any complaints about this before and it's been part of netdata for several years. We are evolving netdata very fast and would like to keep people informed of what we're doing, with updated agents. I haven't seen many comments on this so I'll close it for now, but if see strong objections, we will reconsider.

**Comment by l-jonas** [comment]
What I want is a way to disable the registry feature completely - I don't need it.

I don't need any update checks within netdata. My package manager does the updates together with all the other updates. And they leak to third parties when I look at my monitoring. This is not optimal.

i did not test if NetData still uses the JavaScript eval function - using eval and not setting a CSP by default are bad practices.
