### ISSUE TITLE
Redis collector, 0 keys instead of unregistering chart.

### ISSUE THREAD

**Issue by Tommuh** [netdata/netdata#7635]
Hello,

I have a request to change one graph for the Redis collector. It is about the **keys_redis**, I think it is working wrong at this moment. When there are no keys it will unregister the chart, the chart will not come back when keys are eventually added. To make it appear again you need to restart Netdata. I think the chart must return 0 keys by default.

Obviously this doesn't happen often, but last Christmas it was very quite. When Netdata updated and restarted it self it didn't find any keys for Redis so it unregistered the chart.

Cheers, Tom

**Comment by ilyam8** [comment]
@Tommuh fixes in #7639, it would be nice if you test it

**Comment by Tommuh** [comment]
@ilyam8 how can I test it? Do you release it in a nightly or do I need to do something else? 
Once again, thank you for coming with a quick solution!

**Comment by ilyam8** [comment]
Download [new redis.chart.py](https://raw.githubusercontent.com/ilyam8/netdata/redis_fix_keys_redis_chart/collectors/python.d.plugin/redis/redis.chart.py), move it to the `python.d/` (dir with bunch of *.chart.py files) and restart `netdata.service`.

**Comment by Tommuh** [comment]
Great, I will do that later today, will report back asap.

**Comment by Tommuh** [comment]
I have tested the change.

When there are 0 keys and I restart Netdata the chart isn't visible = NOK
> chart 'redis_local.keys_redis' was suppressed due to non updating
I think the chart must be present, outputting 0 keys.

When I add a key thru redis-cli it becomes visible. = OK
When I remove the key so it becomes 0 again the chart stays visible (till restart happens). = OK

**Comment by ilyam8** [comment]
> chart 'redis_local.keys_redis' was suppressed due to non updating

It will add the chart when first key is added.

> I think the chart must be present, outputting 0 keys.

There is nothing to show before it happened.

**Comment by ilyam8** [comment]
> When there are 0 keys and I restart Netdata the chart isn't visible = NOK

Yes, cant do nothing about it.

**Comment by Tommuh** [comment]
Thank you for your reply, I understand it.
That the chart becomes visible when a keys is added is already a good thing and I'm very happy with that. I think Redis shouldn't be empty as well, but that is more my problem.
