### ISSUE TITLE
Error while accessing netdata dashboard.

### ISSUE THREAD

**Issue by ritzzbv** [netdata/netdata#7641]
##### Question summary
Getting following error with Netdata version: v1.19.0-214-nightly while accessing the dashboard

Cannot load required JS library: http://xxx.domain.com/host/501/lib/perfect-scrollbar-0.6.15.min.js

Any help would be appreciated.

Regards,
Ritesh

**Comment by jacekkolasa** [comment]
hello @ritzzbv , can you see if you can open that http://xxx.domain.com/host/501/lib/perfect-scrollbar-0.6.15.min.js link? I think the problem is somewhere else, can you give us more info, what do you see, was it working before update?

**Comment by ritzzbv** [comment]
Hi @jacekkolasa ,
1. Yes, I can access the URL given above directly in the browser.
2. Yes, Everything was working fine before the update. Actually I was running a very old version of Netdata around 1.10 version.

Any other info I can provide?

Regards,
Ritesh

**Comment by jacekkolasa** [comment]
Yes, can you please explain what do you see when you open Netdata Dashboard? Is there a white page, or the Dashboard works normally? Does it break only when you open /host page, or does it work when you open the `master` Dashboard as well?

Also, can you please try `localStorage.clear()` in the console, and see if that fixes the problem, or try another browser?

**Comment by ritzzbv** [comment]
Hi @jacekkolasa ,
1. I am seeing an alert box with a message I have mentioned above. Once I click on OK, the dashboard is loading fine. 
2. I am seeing this randomly sometimes on master and on slave hosts as well.
3. I did localStorage.clear(). But the issue still persists.

I am using dbengine as my memory mode.

Regards,
Ritesh

**Comment by ritzzbv** [comment]
Hi @jacekkolasa,

Any help on this would be appreciated.  

Regards,
Ritesh

**Comment by jacekkolasa** [comment]
Hi @ritzzbv , i was trying to recreate your problem, but with no luck. Can you please tell
1. are you using default dashboard (like `...:19999/`) or custom one? (like `...:19999/tv.html`)
2. do you see any other errors in the browser console when the alert with `perfect-scrollbar-0.6.15.min.js` shows up?
3. is it always `perfect-scrollbar`, or is it sometimes some other lib, like `bootstrap-3.3.7.min.js`?

**Comment by ritzzbv** [comment]
Hi @jacekkolasa ,

1. Yes I am using default dashboard behind nginx like this netdata.abc.com
2. I can only see this in console "localStorage: LOADED UNDEFINED "options.destroy_on_hide" as value undefined of type undefined"
3. Yes, it's always perfect-scrollbar

Regards,
Ritesh

**Comment by jacekkolasa** [comment]
Thanks for info. That "LOADED UNDEFINED" is something we don't have to worry about now.
I have hard time finding the potential source of the issue. Can you please
- confirm that `NETDATA.requiredJs.length` is `5`, after you load the dashboard
- confirm that you didn't do any custom changes in html/js files?

Currently there's an old bug in `dashboard.js` that - if you have missing `lib/perfect-scrollbar-0.6.15.min.js` file, then it shows some other file in the error, for example `lib/bootstrap-toggle-2.2.2.min.js`. So I even cannot recreate that error, if you're using the standard dashboard.

Please also let me know which browser are you using and if changing browser, or using Incognito Mode will fix your problem

**Comment by ritzzbv** [comment]
Hi @jacekkolasa ,
I can see another error "http://netdata/abc.com/lib/fontawesome-all-5.0.1.min.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)"

1.Yes, NETDATA.requiredJs.length is 5
2. No, changes in html/js files

I am on Google Chrome browser with Ubuntu 18.04 OS, changing to incognito does not help either.

Regards,
Ritesh

**Comment by jacekkolasa** [comment]
`ERR_INCOMPLETE_CHUNKED_ENCODING` could be a hint. @thiagoftsm sorry for bouncing this issue back to you, but you have been working with our server, any ideas?

Perhaps some solutions from https://stackoverflow.com/questions/29894154/chrome-neterr-incomplete-chunked-encoding-error could help?

**Comment by ritzzbv** [comment]
Hi @jacekkolasa @thiagoftsm ,

Any help on this issue would be great.

Regards,
Ritesh

**Comment by jacekkolasa** [comment]
@ritzzbv sorry for the lack of answers, i was just unable to reproduce the problem. Fortunately, in ~few weeks we are releasing rewritten Dashboard (on Frontend side), so that problem will likely be gone. In the meantime, the only things that came to my mind are - if you could try with different browser or different machine where you open the dashboard. Also, perhaps new installation or update could fix the problem.
