### ISSUE TITLE
cannot set libuv thread name to XXXX. Err: 13 (error 13, Permission denied)

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7644]
##### Bug report summary
```
2019-12-31 03:22:54: netdata INFO  : MAIN : All threads finished.
2019-12-31 03:22:54: netdata INFO  : MAIN : EXIT: freeing database memory...
2019-12-31 03:22:54: netdata INFO  : MAIN : Freeing all memory for host 'alysz2'...
2019-12-31 03:22:54: netdata INFO  : MAIN : Shutting down RRD engine event loop.
2019-12-31 03:22:54: netdata INFO  : MAIN : Shutting down RRD engine event loop complete.
2019-12-31 03:22:54: netdata INFO  : MAIN : Freed 81511648 bytes of memory from page cache.
2019-12-31 03:22:54: netdata INFO  : MAIN : SYSTEM_INFO: free 0x1d18660
2019-12-31 03:22:54: netdata INFO  : MAIN : EXIT: removing netdata PID file '/var/run/netdata/netdata.pid'...
2019-12-31 03:22:54: netdata ERROR : MAIN : EXIT: cannot unlink pidfile '/var/run/netdata/netdata.pid'. (errno 13, Permission denied)
2019-12-31 03:22:54: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
```

```
2019-12-31 03:22:56: netdata INFO  : MAIN : Loading journal file "/var/cache/netdata/dbengine/journalfile-1-0000000002.njf".
2019-12-31 03:22:56: netdata INFO  : MAIN : Journal file "/var/cache/netdata/dbengine/journalfile-1-0000000002.njf" loaded (size:2502656).
2019-12-31 03:22:56: netdata ERROR : MAIN : cannot set libuv thread name to DBENGINE. Err: 13 (errno 13, Permission denied)
```

```
2019-12-31 03:22:56: netdata ERROR : MAIN : cannot set libuv thread name to DAEMON_COMMAND. Err: 13 (errno 13, Permission denied)
2019-12-31 03:22:56: netdata INFO  : MAIN : netdata initialization completed. Enjoy real-time performance monitoring!
2019-12-31 03:22:56: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'START' '-' '-'
```

##### OS / Environment
CentOS release 6.9 (Final)

##### Netdata version (ouput of `netdata -V`)
netdata v1.19.0-214-nightly

**Comment by Saruspete** [comment]
Greetings,

Thanks for reporting. This error should not be fatal. can you confirm it ?
So I see you're using CentOS 6, so is your libuv library provided by repository `OKay` ?

Also, I see this error:
```
EXIT: cannot unlink pidfile '/var/run/netdata/netdata.pid'. (errno 13, Permission denied)
```
Are you running netdata with a custom user ?

The permission denied error from the thread renaming means the application does not have access to it own `/proc/self/task/$pid/comm` file. So it either has to do with a kernel security like SELinux, or a custom libuv library modification.

Can you also post the output of
```
ps -Leo pid,tid,ppid,comm,args
```

Thanks.

**Comment by startryst** [comment]
> Greetings,
> 
> Thanks for reporting. This error should not be fatal. can you confirm it ?
> So I see you're using CentOS 6, so is your libuv library provided by repository `OKay` ?
> 
> Also, I see this error:
> 
> ```
> EXIT: cannot unlink pidfile '/var/run/netdata/netdata.pid'. (errno 13, Permission denied)
> ```
> 
> Are you running netdata with a custom user ?
> 
> The permission denied error from the thread renaming means the application does not have access to it own `/proc/self/task/$pid/comm` file. So it either has to do with a kernel security like SELinux, or a custom libuv library modification.
> 
> Can you also post the output of
> 
> ```
> ps -Leo pid,tid,ppid,comm,args
> ```
> 
> Thanks.

Not fatal.
Yes, library is installed by `Okay`

My netdata running by user netdata:
```
ps -ef|grep netdata
netdata  11299     1  0 03:22 ?        00:00:57 /usr/sbin/netdata -P /var/run/netdata/netdata.pid
root     11814 11789  0 09:47 pts/0    00:00:00 grep netdata
```

SELinux is not enabled:
```
getenforce
Disabled

```





```
11299 11299     1 netdata         /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11375     1 netdata         /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11377     1 PLUGIN[proc]    /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11378     1 PLUGIN[diskspac /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11379     1 PLUGIN[idlejitt /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11380     1 STATSD          /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11383     1 WEB_SERVER[stat /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11384     1 PLUGINSD        /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11385     1 HEALTH          /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11386     1 netdata         /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11389     1 PLUGINSD[fping] /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11396     1 STATSD_COLLECTO /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11423     1 netdata         /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11424     1 netdata         /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11425     1 netdata         /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11299 11426     1 netdata         /usr/sbin/netdata -P /var/run/netdata/netdata.pid
11398 11398 11299 fping           /usr/local/bin/fping -N -l -Q 1 -p 200 -R -b 56 -i 1 -r 0 -t 5000 alyhk1.lia
11751 11751  1403 pickup          pickup -l -t fifo -u
11787 11787  1301 sshd            sshd: root@pts/0 
11789 11789 11787 bash            -bash
11817 11817 11789 ps              ps -Leo pid,tid,ppid,comm,args
```

**Comment by thiagoftsm** [comment]
Hi @startryst ,

after to see your ps output,  I have the impression that you have more one Netdata running, please, compare with my output:

```
 6230  6230     1 netdata         netdata
 6230  6240     1 DBENGINE        netdata
 6230  6242     1 PLUGIN[proc]    netdata
 6230  6243     1 PLUGIN[diskspac netdata
 6230  6244     1 PLUGIN[cgroups] netdata
 6230  6245     1 PLUGIN[tc]      netdata
 6230  6246     1 PLUGIN[idlejitt netdata
 6230  6247     1 STATSD          netdata
 6230  6250     1 WEB_SERVER[stat netdata
 6230  6251     1 PLUGINSD        netdata
 6230  6252     1 HEALTH          netdata
 6230  6253     1 DAEMON_COMMAND  netdata
 6230  6256     1 PLUGINSD[go.d]  netdata
 6230  6257     1 PLUGINSD[charts netdata
 6230  6259     1 PLUGINSD[apps]  netdata
 6230  6260     1 PLUGINSD[python netdata
 6230  6263     1 PLUGINSD[nfacct netdata
 6230  6272     1 STATSD_COLLECTO netdata
 6230  6284     1 WEB_SERVER[stat netdata
 6230  6285     1 WEB_SERVER[stat netdata
 6230  6286     1 WEB_SERVER[stat netdata
 6262  6262  6230 bash            bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
 6269  6269  6230 apps.plugin     /usr/libexec/netdata/plugins.d/apps.plugin 1
 6270  6270  6230 nfacct.plugin   /usr/libexec/netdata/plugins.d/nfacct.plugin 1
 6275  6275  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 6275  6535  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 6275  6538  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 6275  6540  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 6275  6541  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 6275  6544  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 6280  6280  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6293  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6294  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6295  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6302  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6303  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6312  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6313  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6314  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6321  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6341  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
 6280  6545  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
```

As you can see, I have only one Netdata process, but I have different plugins, Please, could you shutdown all netdata process and restart again to confirm that the problem persists?

**Comment by startryst** [comment]
> Hi @startryst ,
> 
> after to see your ps output, I have the impression that you have more one Netdata running, please, compare with my output:
> 
> ```
>  6230  6230     1 netdata         netdata
>  6230  6240     1 DBENGINE        netdata
>  6230  6242     1 PLUGIN[proc]    netdata
>  6230  6243     1 PLUGIN[diskspac netdata
>  6230  6244     1 PLUGIN[cgroups] netdata
>  6230  6245     1 PLUGIN[tc]      netdata
>  6230  6246     1 PLUGIN[idlejitt netdata
>  6230  6247     1 STATSD          netdata
>  6230  6250     1 WEB_SERVER[stat netdata
>  6230  6251     1 PLUGINSD        netdata
>  6230  6252     1 HEALTH          netdata
>  6230  6253     1 DAEMON_COMMAND  netdata
>  6230  6256     1 PLUGINSD[go.d]  netdata
>  6230  6257     1 PLUGINSD[charts netdata
>  6230  6259     1 PLUGINSD[apps]  netdata
>  6230  6260     1 PLUGINSD[python netdata
>  6230  6263     1 PLUGINSD[nfacct netdata
>  6230  6272     1 STATSD_COLLECTO netdata
>  6230  6284     1 WEB_SERVER[stat netdata
>  6230  6285     1 WEB_SERVER[stat netdata
>  6230  6286     1 WEB_SERVER[stat netdata
>  6262  6262  6230 bash            bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
>  6269  6269  6230 apps.plugin     /usr/libexec/netdata/plugins.d/apps.plugin 1
>  6270  6270  6230 nfacct.plugin   /usr/libexec/netdata/plugins.d/nfacct.plugin 1
>  6275  6275  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
>  6275  6535  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
>  6275  6538  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
>  6275  6540  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
>  6275  6541  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
>  6275  6544  6230 python          /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
>  6280  6280  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6293  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6294  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6295  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6302  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6303  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6312  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6313  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6314  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6321  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6341  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
>  6280  6545  6230 go.d.plugin     /usr/libexec/netdata/plugins.d/go.d.plugin 1
> ```
> 
> As you can see, I have only one Netdata process, but I have different plugins, Please, could you shutdown all netdata process and restart again to confirm that the problem persists?

Yes, tried shutdown all netata process and restarted again, and those three errors  still exist:

```
ps -ef|grep netdata
netdata  24455     1  0 03:31 ?        00:00:28 /usr/sbin/netdata -P /var/run/netdata/netdata.pid
netdata  24554 24455  0 03:31 ?        00:00:15 /usr/local/bin/fping -N -l -Q 1 -p 200 -R -b 56 -i 1 -r 0 -t 5000 alyhk1.liang.network 10.0.0.9 10.0.0.11 10.0.0.101
root     24748 24729  0 06:39 pts/0    00:00:00 grep netdata

service netdata stop
Stopping netdata...                                        [  OK  ]

ps -ef|grep netdata
root     24788 24729  0 06:39 pts/0    00:00:00 grep netdata


service netdata start
Starting netdata...2020-01-01 06:40:03: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
                                                           [  OK  ]
```

**Comment by thiagoftsm** [comment]
Hi @startryst ,

Firstly happy new year!
Now returning for the specific problem that you are reporting, I could not find a way to have it on my computers, but I am using the latest version of libuv on all them. What is your libuv version?

Best regards!

**Comment by ilyam8** [comment]
> 2019-12-31 03:22:56: netdata ERROR : MAIN : cannot set libuv thread name to DBENGINE. Err: 13 (errno 13, Permission denied)

It doesnt look like an `error` level to me.

**Comment by thiagoftsm** [comment]
I agree @ilyam8, this could be converted to `INFO` case the problem has a relationship with libuv version.
