### ISSUE TITLE
netdata alarm url is not redirecting to netdata master server

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7646]
##### Question summary
I have implemented netdata streaming and have enabled alarms to be sent to a rocketchat channel. The problem is alerts sent to the rocket chat has an address but it is not the address of my master node which is checking the thresholds. I have already put my master address in `cloud base url` of `netdata.conf` but when I click on the link in rocket chat I get this error:
`File does not exist, or is not accessible: /opt/netdata/usr/share/netdata/web/alarms/redirect`
How can I fix this? 

##### OS / Environment
Ubuntu 16.04 with netdata 1.19
##### Component Name
health monitoring
##### Expected results
An url which redirects to the problematic node

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

I tried to repeat the problem that you are having, but I did not have success, so I will do few question for you to try to help you.

1 - In my case I have a local registry enabled and I am using `slack` to receive the notification, do your URLs have the following format: `https://localhost:19999/goto-host-from-alarm.html?host=darkstar&chart=system.cpu&family=cpu&alarm=dev_dim_template_system&alarm_unique_id=1577834471&alarm_id=1577834470&alarm_event_id=1&alarm_when=1577834532` ?
2 - Are you signed to Netdata cloud?

Best regards,

**Comment by yasharne** [comment]
Hi @thiagoftsm yes, I have enabled the registry:
```
[registry]
        enabled = yes
        registry to announce = http://172.16.76.7:19999
```
but when I click on the message sent to the rocket chat I get this error:
```
Sorry... your account is not linked to a netdata server named: one-23.x.y.z
```
here is the URL:
`
http://172.16.76.7:19999/goto-host-from-alarm.html?host=one-23.x.y.z&chart=system.swap&family=swap&alarm=used_swap&alarm_unique_id=1577818839&alarm_id=1578067152&alarm_event_id=2&alarm_when=1578067178
`
I haven't signed to the Netdata cloud and I want to use my own registry.

**Comment by thiagoftsm** [comment]
@yasharne this error is happening, because the local registry is not able to find the host in the local registry. Your configuration is correct for the master, but it is also necessary to set the variable `registry to announce` on slaves, but on slaves, it is also necessary to set `enabled = no`, you can see more details in this link https://docs.netdata.cloud/registry/#run-your-own-registry . Did you also adjust the slaves like I described?

**Comment by yasharne** [comment]
Thanks, disabling registry and adding `registry to announce` on the slaves solved the problem
