### ISSUE TITLE
Samba monitoring stopped working

### ISSUE THREAD

**Issue by camjesus2** [netdata/netdata#7651]
Hi all,
First of all, I wish you a happy and prosperous 2020!
I'm having some problems with my samba performance monitoring that stopped working supposedly after upgrade to v1.19 (from v1.14).
My system is a self compiled samba on a Debian Buster server and I've followed the troubleshooting I've found in issue #2483.
My current situation is:
1) `su -m 'netdata' -c 'sudo -n smbstatus -F'`  returns expected results so it seems sudo is correctly configured

2) `/var/log/netdata/error.log` shows 
```
"2020-01-01 21:19:20: python.d ERROR: samba[samba] :
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified

2020-01-01 21:19:20: python.d INFO: plugin[main] : samba[samba] : check failed"
```

3) Running the plugin `/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 samba` as "netdata" gives 
```
...
2020-01-01 22:18:51: python.d DEBUG: plugin[main] : [samba] 
/usr/lib/netdata/conf.d/python.d/samba.conf is loaded
2020-01-01 22:18:51: python.d INFO: plugin[main] : [samba] built 1 job(s) configs
[sudo] password for netdata:

```
4) Running the plugin as root, of course, works as expected

5) samba option in `/usr/lib/netdata/conf.d/python.d.conf` is explicitly enabled

After a lot of messing with sudo, I'm kind of at a loss here (certain, however, that I'm missing something very basic) and so, any suggestion would be appreciated.

Best regards,
Carlos

**Comment by ilyam8** [comment]
Hi @camjesus2 

I see samba module runs 2 command in the `check`:
 - `sudo -v`

https://github.com/netdata/netdata/blob/ef0be0c5064b1614a13fa26e8f5f5a8bfd253698/collectors/python.d.plugin/samba/samba.chart.py#L114-L115

 - `sudo -n smbstatus -P`

https://github.com/netdata/netdata/blob/ef0be0c5064b1614a13fa26e8f5f5a8bfd253698/collectors/python.d.plugin/samba/samba.chart.py#L120-L122

Both of them shouldnt resulted in

```bash
2020-01-01 22:18:51: python.d INFO: plugin[main] : [samba] built 1 job(s) configs
[sudo] password for netdata:
```


try to execute them as `netdata` user

```bash
sudo su -s /bin/bash netdata
sudo -v
sudo -n smbstatus -P
```

**Comment by ilyam8** [comment]
I think `sudo -v` is the problem 😅

**Comment by ilyam8** [comment]
@camjesus2 please share the output of

> sudo grep netdata /etc/sudoers

**Comment by camjesus2** [comment]
@ilyam8 sudo -v is indeed a problem.
`09:58-EHFS:/home/dominator# sudo grep netdata /etc/sudoers.d/netdata`
returns
`netdata ALL = (root) NOPASSWD: /usr/local/samba/bin/smbstatus`
