### ISSUE TITLE
Script to generate Netdata support file for bugreport

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#7657]
# Support script
Netdata is available on many platforms and versions. Bugtracking on such a consequent combination possibilities is hard and bug tickets always request to generate more commands.

We should provide a script that gathers automatically required info to be attached to error reports.

Idea from #7550 comments (@prologic @ilyam8 @stelfrag)

## Features:
- **Must not** reveal secrets or disclose private information (filter out configuration, log files and command output)
- **Must** work on all officially supported platforms (OS and Containers)
- **May** take into account specific package versions, like EPEL, or issue a warning asking to test with official netdata release before submitting bug

## Information sources to query
- Host:
  - `uname -a`
  - `sw_vers` (Apple)
  - `/etc/*release` (Linux)
  - `/etc/netdata/netdata.conf`
  - `ps -Leo "pid,tid,ppid,user,comm,wchan:20,args"`
  - `(rpm -qa || dpkg -la || equery list '*') | grep -e netdata -e libuv -e Judy`
- `/var/log/netdata/`
  - raw logs for the last 2 netdata startup, or last 7 days, whichever comes first.
  - extract the time range for the last error / failure / startup.
- `/var/log/messages` / journalctl / dmesg
  - Logs within the previously found time-range
  - Any line with `netdata` in it

## Private information to be sanitized
- IP Addresses
- hostname
- non-standard users
- containers name

## Workflow
- Provide the script in the `lib` folder of netdata, along with others ones like alerting
- In the github reporting templates, ask for output of this script
- The script will gather multiple information sources to ease netdata debugging. 
- The script should check if tools like openssl is available, in order to encrypt files / archives with a *netdata support* private key, only held by a bot, or a vault to keep it longterm.
- if machine is connected to internet, propose to upload it to the ticket, or to an alternative storage.
- Also provide an `--offline` to skip any test related to internet connectivity.

**Comment by prologic** [comment]
Hi @Saruspete ; Apologies for the late reply!

@Ferroin @ilyam8 (_and others_) I know we've done a bunch of work amending our Github Issue templates. Is this enough? Should we go to the effort of building such a script/tool or park this?

Long-term I feel that we _may_ need this anyway -- especially once we consider Windows support -- And writing a tool (_say in Go for portability reasons and just because its a damn good language!_) would be beneficial here.˚

**Comment by ilyam8** [comment]
> Should we go to the effort of building such a script/tool or park this?

At some point yes 😄

**Comment by Ferroin** [comment]
> Long-term I feel that we may need this anyway -- especially once we consider Windows support

Agreed, it's not unusual for people to have no idea how to get the info we're likely to want on Windows.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
