### ISSUE TITLE
Master's console.html showing greyed out `outdated` nodes

### ISSUE THREAD

**Issue by marcelmfs** [netdata/netdata#7658]
#### Bug report summary
After updating master from 1.16 to 1.19-lastest (nightly), some nodes in console.html are being displayed completely greyed out with `outdated` label on them.

My nodes are at a variety of versions, I'm in the process of upgrading them, but even ones within the same minor version are behaving like described.

When I open the nodes' dashboard in the master I see the default view without any issues, e.g. https://master.example.com/host/SLAVE-netdata-host/#menu_system;theme=slavte;help=true displays the expected graphs.

![netdata_console_outdated_nodes](https://user-images.githubusercontent.com/5718899/71664359-f93b3380-2d58-11ea-82f9-5a187644b5c0.png)

After deleting the nodes' URL I still see a greyed out node but instead of `outdated` the label now changed to `unreachable`. 

![netdata_console_unreachable_node](https://user-images.githubusercontent.com/5718899/71664361-fd675100-2d58-11ea-88a4-95c1a88d9a6e.png)

Edit: after an hour or so the `unreachable` updated node now is showing as expected.

![netdata_console_more_unreachables](https://user-images.githubusercontent.com/5718899/71673625-93ab6f00-2d79-11ea-9afc-1ffa1e8f25fd.png)

Edit2: It became unreachable again, and others that were also updated too became unreachable after removing them from the master console.

~~I guess my question now is if, version 1.19.0-225-nightly master console is not compatible with previous versions of slaves?~~

##### OS / Environment
#Master:
Linux <hostname_redacted> 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.7.1908 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.7.1908 (Core)
/etc/system-release:CentOS Linux release 7.7.1908 (Core)

#Slave:
Linux <hostname_redacted> 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.5 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.5"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
/etc/os-release:HOME_URL="https://www.redhat.com/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.5 (Maipo)
/etc/system-release:Red Hat Enterprise Linux Server release 7.5 (Maipo)

##### Netdata version (ouput of `netdata -V`)
netdata v1.19.0-225-nightly

##### Component Name
console.html

##### Steps To Reproduce
I didn't try to reproduce this issue, issue showed up after upgrading master's to 1.19.0-225-nightly

##### Expected behavior
Netdata master's console showing nodes as reachable/alive/not greyed out.

**Comment by cakrit** [comment]
@marcelmfs we dropped the ball on this one, you should have received an answer much sooner. 
I'm not sure what's happening here, but we're feverishly working on a completely revamped version of the cloud. This issue will definitely go away with the new version, which is coming in ~1 month. We're doing any more fixes on the old code, so stay tuned and I think you'll like what you'll see! :)
