### ISSUE TITLE
Missing dependencies ubuntu xenial packagecloud

### ISSUE THREAD

**Issue by michlaustn** [netdata/netdata#7659]
When trying to install netdata from the packagecloud repositories on Ubuntu Xenial there are a number of missing dependencies:

* libjson-c3
* libprotoc10
* libprotobuf10

Attempting to install version netdata/bionic 1.19.0 amd64

**Comment by Ferroin** [comment]
> Attempting to install version netdata/bionic 1.19.0 amd64

You're trying to install a package for Bionic (18.04) on Xenial (19.04). Missing dependencies like this are expected when you mismatch repository versions.
