### ISSUE TITLE
Gaps in fping graph, with longer ping interval?

### ISSUE THREAD

**Issue by DirectRoot** [netdata/netdata#7661]
##### Question summary
How do I stop the `fping` graph from showing gaps in the data (and hence causing alarms) when pinging at a longer interval?

![image](https://user-images.githubusercontent.com/34790650/71674438-2d0e5d00-2d49-11ea-87a6-735aecd46308.png)

##### OS / Environment
Pi 4 running Raspbian 10 (Buster)
I've set `update_every=20` and `ping_every=4000`, which I expect to be equivalent to "ping the host every 4s, with each point on the graph showing 5 pings".

##### Component Name
fping

##### Expected results
Graph joins data points when pinging at a longer than default interval.

Thanks in advance for any help,
Chris.

**Comment by ilyam8** [comment]
Hi @DirectRoot 

> I've set update_every=20 and ping_every=4000, which I expect to be equivalent to "ping the host every 4s, with each point on the graph showing 5 pings

Yes, this is how it is.

Are those gaps only in the fping charts?

**Comment by DirectRoot** [comment]
> Are those gaps only in the fping charts?

Yes, everything else has no gaps. `fping` itself produces charts with no gaps on a shorter ping+update cycle; it works on the default settings and pinging every second with update every 2s.

**Comment by ilyam8** [comment]
@DirectRoot 

I cant reproduce it. Thas is my config

```bash
test@DEB10-1:/opt/netdata/etc/netdata$ sudo grep ^[a-z] fping.conf
hosts="192.168.56.12"
update_every=20
ping_every=4000
```

host `192.168.56.12` is not responding to icmp echo

<img width="1219" alt="Screenshot 2020-01-03 at 21 23 53" src="https://user-images.githubusercontent.com/22274335/71741273-896b9c80-2e6f-11ea-87bc-6da359d2135c.png">

Latency chart is empty, because there is no response, but other two charts have data since `DEB10-1` is pinging.

**Comment by DirectRoot** [comment]
@ilyam8 after restarting the netdata collector, I also needed to restart the netdata central where the graphs were being viewed and alarms generated. After a restart the graphs are rendered correctly.

Thanks for your help!
C.
