### ISSUE TITLE
Can't sign in to Netdata Cloud from PFSense Netdata instance

### ISSUE THREAD

**Issue by RAMilewski** [netdata/netdata#7667]
##### Bug report summary
Installed Netdata on PFSense machine following instructions in [the documentation](https://docs.netdata.cloud/packaging/installer/#pfsense).  I encountered a couple of kernel version warnings in the process.

I'm pretty green when it comes to FreeBSD. Should I have used packages from [release 2](http://pkg.freebsd.org/FreeBSD:11:amd64/release_2/All/) rather than [latest](http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/)?

On cursory inspection Netdata appears to be running normally.  However, clicking the **Sign In** button throws the error: _File does not exist, or is not accessible: /usr/local/share/netdata/web/null/account/sign-in-agent_. 

The directory /usr/local/share/netdata/web/null does not, of course exist.   
find / -name sign-in-agent comes up empty.

##### OS / Environment 
FreeBSD pfsense.rampage.net 11.2-RELEASE-p10 FreeBSD 11.2-RELEASE-p10 #9 4a2bfdce133(RELENG_2_4_4): Wed May 15 18:54:42 EDT 2019     root@buildbot1-nyi.netgate.com:/build/ce-crossbuild-244/obj/amd64/ZfGpH5cd/build/ce-crossbuild-244/pfSense/tmp/FreeBSD-src/sys/pfSense  amd64
grep: No match.

##### Netdata version 
netdata v1.19.0

##### Component Name
Sign-In-Agent (?)

##### Steps To Reproduce
See bug report summary.

##### Expected behavior
A connection to my Netdata Cloud account.

Thank you for an utterly spectacular product!!

**Comment by thiagoftsm** [comment]
Hi @RAMilewski ,

We generated the PR #7665  few hours ago for pfSense, please, can you test it to confirm that it also can solve your problem?
In this PR we did not set the `release_2`.

Best Regards!

**Comment by RAMilewski** [comment]
Thanks for the very quick response!  Alas... No Joy!

I tried the URLs mentioned in PR [#7665](https://github.com/netdata/netdata/pull/7665) but encountered the same missing sign-in agent error described above.   

I also tried loading the most recent packages I could find for Judy and and python37 that did not throw the kernal version errors described above and in [#7473](https://github.com/netdata/netdata/issues/7473).  These came from FreeBSD [release 3](uhttp://pkg.freebsd.org/FreeBSD:11:amd64/release_3/All/rl), which also contains a package for netdata 1.17.1.  When installed that package _**does**_ throw the kernel version error on installation.  _It also exhibits the same missing sign-in agent error as 1.19.0._   I uninstalled 1.17.1 and installed 1.19.0 from the FreeBSD [latest](http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/) repository.

I suspect the failure to start problem described in [#7473](https://github.com/netdata/netdata/issues/7473) was due to trying to run Netdata 1.19.0 on python 36.

I think the real problem with the Netdata install instructions for PFSense is that they don't take into account the fact that it's the PFSense updater that manages FreeBSD updates on PFSense boxes. This means that the appropriate packages really depend on the PFSense version.   The most concise summary I have found of the correlation between PFSense versions a FreeBSD versions 
comes from [NetGate](https://docs.netgate.com/pfsense/en/latest/releases/versions-of-pfsense-and-freebsd.html).

I believe that most shops running PFSense on production boxes would be loathe to start updating FreeBSD independently of PFSense.

This means that most PFSense users are stuck using Netdata 1.10.0 from the FreeBSD [release 2](http://pkg.freebsd.org/FreeBSD:11:amd64/release_2/All/) repository.   

This is also true for FreeNAS, although the current version runs a later version of FreeBSD than PFSense.  I'm hoping that issue will go away with the resolution of **[#7356](https://github.com/netdata/netdata/issues/7356)** (hopefully before FreeBSD 13 hits general release).   In the case of FreeBSD it looks like the integration is more complex than just a package install and the same reservation about attempting it on production boxes would apply.

#### Conclusion
I don't think the missing sign-in agent issue is related to versions of FreeBSD libraries, but due to some other difference between Linux and FreeBSD.  Do you have any stats on how many FreeBSD boxes are using the Netdata Cloud?

**Comment by nicolasparada** [comment]
Hey, can you tell us if by visiting `http://localhost:19999/api/v1/registry?action=hello` (or the host you are in) you see a proper URL under `cloud_base_url`?
I suspect that you are getting `/usr/local/share/netdata/web/null` from there. This URL is read from the `netdata.conf` file and by default it should be `https://netdata.cloud`.

**Comment by thiagoftsm** [comment]
Today I installed pfSense on a VM to try to repeat your problems. 
I had some problems with permissions that were solved after I set inside my netdata.conf the line `run as user = netdata`, before this my netdata was running as `nobody`. 
I could not repeat the error that you are having after to set the correct `run as user`, but I also could not run netdata before to set it, please, what is the user running netdata?

Best regards!

**Comment by RAMilewski** [comment]
**thiagoftsm:**  Per top, netdata is running as user netdata even though that line is commented out of  netdata.conf.  

**Nicholasparada**  That's not where the url is coming from.  http://pfsense:19999/api/v1/registry?action=hello reports:
	"action": "hello",
	"status": "ok",
	"hostname": "pfsense.rampage.net",
	"machine_guid": "658755e8-2cee-11ea-90a9-00e0b6159b9c",
	"registry": "https://registry.my-netdata.io",
	"cloud_base_url": "https://netdata.cloud",
	"anonymous_statistics": true

_**But the problem appears to be browser configuration !!!**_

I've been using Firefox Developer Edition.   I can log pfsense into netdata.cloud using google chrome and if I relaunch Firefox DevEd with a clean profile, it will also log in to netdata cloud.

Querying the registry with ?action=hello from my normal DevEd profile reports:

**Comment by prologic** [comment]
@RAMilewski I _believe_ the issue you are facing _might_ be related to [Disabling of3rd-party cookies](https://www.cookiesandyou.com/disable-cookies/windows/chrome/) -- Can you confirm this is the case for you? if so and is your normal browser configuration; I would recommend allowing cookies from `netdata.cloud`

**Comment by RAMilewski** [comment]
@prologic I agree it has something to do with cookies, but I don't understand why the behavior is different when browsing to a netdata instance on a linux machine and one on PFSense (FreeBSD).
Nothing in the browser profile configuration is changing.  I can have both open in separate tabs and netdata on the linux instance interacts normally with netdata.cloud and the instance on FreeBSD doesn't.

....next step is to do a diff on the user.js files in the Firefox profiles of the browser instances that work uniformly and the one that doesn't.   I'll report back.

**Comment by RAMilewski** [comment]
OK, I think I've isolated the issues. Just to recap, this testing was done with Firefox Developer edition (70.0b1) running on MacOS 10.13.6.  My PFSense machine is running PFSense 2.4.4-RELEASE-p3 (amd64) on FreeBSD 11.2-RELEASE-p10

The following are necessary to be able to log the PFSense machine running FreeBSD into netdata.cloud, **_but are not required to log my Linux or OS X machines into netdata.cloud._** 

1.  The Avira Browser Safety extension to Firefox, if present, must be disabled.
2.  Firefox > Preferences > Privacy and Security > Browser Privacy > Enhanced Tracking Protection must be set to:
          - **Standard** or
          - **Custom** with the **Cookies** drop-down set to **_"Cross-site and social media trackers"_**       Setting the drop-down to **_"Cookies from unvisited websites"_** will _**not**_ work.
3.  **Send websites a “Do Not Track” signal** must be set to **_Only when Firefox Developer Edition is set to block known trackers_**

Can anyone explain why the FreeBSD netdata instance behaves this much differently than the OS X and Linux Netdata instances?

**Comment by thiagoftsm** [comment]
Hi @RAMilewski ,

FreeBSD sets default values different of Linux, it is completely possible that some Linux distributions can compile firefox and also enable options that would limit access to netdata.cloud.
Unfortunately I cannot say anything about MacOS, but I believe they also follow the pattern that you had with FreeBSD.

Best regards!

**Comment by RAMilewski** [comment]
Differences in how FreeBSD, MacOS and Linux compile Firefox have nothing to do with this issue.

As I said above, Firefox is running on MacOS for all of my testing.  Netdata is running on my Macs, 4 headless Linux boxes and two headless FreeBSD machines.  

But I've got everything working as well as it's going to despite the fact that I really don't understand what's happening to make the FreeBSD instances behave so differently.   No point spending more effort chasing ghosts, so I'll close this issue.
