### ISSUE TITLE
Add more charts to Netdata (docker image)

### ISSUE THREAD

**Issue by tx7** [netdata/netdata#7669]
#### Summary
Hi,

I'm currently using Netdata in a Docker container.
I would like to add more charts to it for Plex Media Server, Emby, etc...
The media servers aren't running via Docker.
Where do I go to add it ?
Is it apps_groups.conf file or something ?

Thanks

**Comment by ilyam8** [comment]
Hi @tx7 

> Is it apps_groups.conf file or something ?

Yes, to monitor cpu/mem/disk usage of process/group of processes you can use [`apps.plugin`](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin) (`netdata` should be installed on the same host as the app).

> I would like to add more charts to it for Plex Media Server, Emby, etc...

If it is not enough and you need to monitor app specific metrics you need to write the specific plugin.

The easiest way to do it is to write custom module to [python.d.plugin](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin#pythondplugin).

**Comment by tx7** [comment]
Hi,

Where is the apps.plugin located ?
How do I add Plex to it ?

Thanks

**Comment by ilyam8** [comment]
As you mentioned you need to add it to the plugin configuration file, see

https://github.com/netdata/netdata/tree/master/collectors/apps.plugin#configuration

It would be nice you made a PR, example

https://github.com/netdata/netdata/pull/7287

**Comment by tx7** [comment]
So, I sudo docker exec -it netdata /bin/bash.
Next, I went into /etc/netdata/edit-config , but I don't see the apps_groups.conf file.

**Comment by ilyam8** [comment]
See 
https://docs.netdata.cloud/docs/configuration-guide/

you need to `./edit-config apps_groups.conf`

**Comment by tx7** [comment]
I ran it, but I don't know which key to use to edit the file.
Can't use nano or vim at all.

**Comment by ilyam8** [comment]
@tx7 

Create the file in the host system and mount it to the container.

Example:

```
docker run -d --name=netdata   -p 19999:19999  --mount type=bind,src=$(pwd)/apps_groups.conf,dst=/etc/netdata/apps_groups.conf   -v /etc/passwd:/host/etc/passwd:ro   -v /etc/group:/host/etc/group:ro   -v /proc:/host/proc:ro   -v /sys:/host/sys:ro   --cap-add SYS_PTRACE   --security-opt apparmor=unconfined   netdata/netdata
```

> --mount type=bind,src=$(pwd)/apps_groups.conf,dst=/etc/netdata/apps_groups.conf

^^, check this

> https://docs.docker.com/storage/bind-mounts/

**Comment by tx7** [comment]
I think it's working.

Thanks for the help.
