### ISSUE TITLE
apps plugin not in-sync between alarm and chart dashboard

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7670]
##### Bug report summary
Before last night upgrade, everything was fine, but after that, as you see below, the alarm dashboard show nothing returns in terms of how many processes:
![image](https://user-images.githubusercontent.com/22472752/71756809-c7e37480-2ecc-11ea-8786-d1884b411dfd.jpeg)

but in the dashboard, it shows the number of process running in real time:
![image](https://user-images.githubusercontent.com/22472752/71756850-e6497000-2ecc-11ea-92d2-71946cd2b62c.jpeg)

the alarm configuration is pretty simple:
```
   alarm: dnsmasq
      on: apps.processes
    calc: $dnsmasq
   every: 10s
    crit: $this != 1
   units: processes
   delay: up 1m down 5m multiplier 1.5 max 1h
      to: sysadmin
```

for apps_groups.conf, just add a few lines at the top of the file:

```
sshd: sshd
dnsmasq: dnsmasq
autossh: autossh

```
##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)
CentOS Linux release 7.3.1611 (Core) 

##### Netdata version (ouput of `netdata -V`)
netdata v1.19.0-239-nightly

**Comment by ilyam8** [comment]
hi @startryst 

You are right, it seems it doesnt work when alarm name is equal to dimension name.

```
   alarm: dnsmasq
    calc: $dnsmasq
```

^^

To get them working rename them to something like `apps_NAME_processes`

```
   alarm: apps_dnsmasq_processes
      on: apps.processes
    calc: $dnsmasq
   every: 10s
    crit: $this != 1
   units: processes
   delay: up 1m down 5m multiplier 1.5 max 1h
      to: sysadmin
```

___

It looks like a bug to me.

**Comment by startryst** [comment]
> hi @startryst
> 
> You are right, it seems it doesnt work when alarm name is equal to dimension name.
> 
> ```
>    alarm: dnsmasq
>     calc: $dnsmasq
> ```
> 
> ^^
> 
> To get them working rename them to something like `apps_NAME_processes`
> 
> ```
>    alarm: apps_dnsmasq_processes
>       on: apps.processes
>     calc: $dnsmasq
>    every: 10s
>     crit: $this != 1
>    units: processes
>    delay: up 1m down 5m multiplier 1.5 max 1h
>       to: sysadmin
> ```
> 
> It looks like a bug to me.

right, after changed to `apps_xxxxx_processes`, works.

**Comment by amoss** [comment]
After discussion in the planning session this will require three reviews to check some of the subtle aspects. @mfundul and @stelfrag will take a look - please wait for three approvals before merging.

**Comment by thiagoftsm** [comment]
This bug was bigger than it was reported here, I created the issue #7834 that gives a global vision about the problem.
The alarm is already in review process, thank you @startryst to report this for us.
