### ISSUE TITLE
Community custom-made dashboard html´s

### ISSUE THREAD

**Issue by rdnsx** [netdata/netdata#7671]
Hi, 

maybe i´m just missing something, i thought would be obvious... but is there a place/pool were users can provide and/or get custom-made dashboard html´s made by the communitiy?

Cheers
rdnsx

**Comment by ilyam8** [comment]
Hi, no, there is no such place unfortunately 😢

**Comment by joelhans** [comment]
As Ilya said, there's currently no place for this, but I really like the idea.

One option is to create a new page in the documentation, almost like a gallery, with screenshots and links to the custom dashboard's code. I could link to that page from a few places throughout the documentation.

Or, I could use a Notion board, like this: https://www.notion.so/joelnetdata/Custom-dashboards-gallery-ccb2d839331b4dea925048a380bccdd6

Another option would be some tool/service that lets users submit their custom dashboards automatically. I'm not sure if such a tool exists, but I'd be happy to experiment if someone has an idea.

**Comment by rdnsx** [comment]
Thanks for your joining. I like the notion board idea and links in the documentation. 
For me it's like:

1. I wanne see a preview, name and short description of each dashboard

2. Users must be able to upload the preview picture and html file themselfes

3. External links to download the file from are not allowed, to ensure downloadlinks are working at any time.

4. Maybe a rating possibility to make sure uploaded Dashboards are working.

**Comment by joelhans** [comment]
2 is going to be the toughest to implement, but I'll continue looking into how we could implement this.

**Comment by rdnsx** [comment]
Perfect. You know... For me there would be no bigger pain than finding the perfect template and the external link doesnt work, because the provider of the file cahnged whatever...

**Comment by amoss** [comment]
This seems like a really good idea. There is something similar for Graphviz at https://graphviz.gitlab.io/gallery/ and it helps their community see what is possible and get ideas on how to implement things. This would definitely be great for Netdata.

**Comment by tnyeanderson** [comment]
Check out `web/gui/dash-example.html`. See the README in `web/gui/custom` for instructions.

That's at least a start :) some discussion on this in #7757

**Comment by cakrit** [comment]
I suggest we extend what we have as follows:
- The existing directory `web/gui/custom` gets subdirectories, one for each user-contributed custom dashboard. 
-  `web/gui/custom/README.md` lists those directories, with a short explanation of what each one contains, perhaps an image with a screenshot as mentioned above and a link to the README of the particular directory.
-  e.g We move `dash-example.html` to `web/gui/custom/dash`, create a README.md there with content moved from what was already added to the main README.md for custom dashboards and just leave it it's place a summary. 

The question is then if we want the installation scripts to put those htmls under `/usr/share/netdata/web/custom` as well, or if we'll just leave them in the repo for reference.

**Comment by tnyeanderson** [comment]
> The question is then if we want the installation scripts to put those htmls under /usr/share/netdata/web/custom as well, or if we'll just leave them in the repo for reference.

I personally think they should be for reference in the repo, not installed in `/usr/share`.

**Comment by cakrit** [comment]
It looks like we have an agreement then. I'll see if I can steal some time to make the changes myself.

**Comment by cakrit** [comment]
It's been over a year on this and it was forgotten on me. I'm reassigning it and we see when we pick it up.

**Comment by ilyam8** [comment]
We moved dash to [the netdata/community repo](https://github.com/netdata/community/tree/main/netdata-agent-dashboard). If there are any community dashboards related contributions they should go in there.

@OdysLam
