### ISSUE TITLE
use common files (css/js) for host and slaves

### ISSUE THREAD

**Issue by pgassmann** [netdata/netdata#7672]
##### Feature idea summary

use common files (css/js) for host and slaves

Follow up of #7539 and #7643 

Currently for each slave, the browser has a different path to the css resources (`/host/<slave>/`.  Is this necessary? do the css/js etc differ from slave to slave and from host? If they are the same, it would be better if the css/js files have to be downloaded only once.

cc @underhood 

##### Expected behavior

css and js resources are always the same, independent of main or slave host. always `/main.css` etc.
This wouold also allow browser caching for these files when switching between slaves.

**Comment by jacekkolasa** [comment]
Hi @pgassmann , thanks for the idea! The css/js files are actually the same. Slave hosts don't even serve vendor files, all is fetched from master. We're doing Dashboard refactor at this moment, so it will make sense do apply your requested change after the refactor is done.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
