### ISSUE TITLE
--disable-backend-prometheus-remote-write does not work

### ISSUE THREAD

**Issue by candrews** [netdata/netdata#7673]
##### Bug report summary
`./configure  --disable-backend-prometheus-remote-write` still builds prometheus support.

This configure flag is documented at https://github.com/netdata/netdata/blob/v1.19.0/packaging/DISTRIBUTIONS.md

Here's a log demonstrating the problem:
[build.log](https://github.com/netdata/netdata/files/4024017/build.log)
`--disable-backend-prometheus-remote-write` is passed, yet this line is still output:
```
checking if prometheus remote write backend should be enabled... yes
```

##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)
Gentoo/Linux

##### Netdata version (ouput of `netdata -V`)
1.19.0

##### Component Name
prometheus

##### Steps To Reproduce
Configure with `--disable-backend-prometheus-remote-write`

##### Expected behavior
When `--disable-backend-prometheus-remote-write` is passed, prometheus should not be enabled and support for it should not be built.

**Comment by vlvkobal** [comment]
The fix was merged. Thank you @candrews.
