### ISSUE TITLE
backend http request need proper Host header

### ISSUE THREAD

**Issue by Ehekatl** [netdata/netdata#7676]
##### Bug report summary

When using prom remote write, it use hostname as backend Host header

```
                    buffer_sprintf(http_request_header,
                                    "POST %s HTTP/1.1\r\n"
                                    "Host: %s\r\n"
                                    "Accept: */*\r\n"
                                    "Content-Length: %zu\r\n"
                                    "Content-Type: application/x-www-form-urlencoded\r\n\r\n",
                                    remote_write_path,
                                    hostname,
                                    data_size
                    );
```

it should use destination's hostname for proper routing the requests

##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)
Ubuntu 18.04

##### Netdata version (ouput of `netdata -V`)
v1.19.0

##### Component Name
netdata backend

##### Steps To Reproduce

use prom remote write with domain as destination

```
[backend]
  enabled = yes
  type = prometheus_remote_write
  data source = as collected
  destination = DOMAIN
```

##### Expected behavior

Backend follow HTTP standard use destination's domain in Host header

**Comment by amoss** [comment]
The Host header should be the system that we are sending the metrics to - the code pulls this value out of the `localhost` structure.

**Comment by Ehekatl** [comment]
@amoss ya it should be, but now it use hostname from localhost rather than the domain from destination
