### ISSUE TITLE
unreachable status for node with authentication?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7677]
##### Question summary
One of my node configured with http authentication, so in the nodes panel, it always shows as unreachable, even though the password has been remembered by the browser, and if I click that node, it can be opened without any user intervention, is that the expected result?

**Comment by ilyam8** [comment]
not sure you are the correct person @VLegakis, but please take a look

**Comment by tibra** [comment]
I'd like to follow up on this just for clarification: 

- The moment I enable a basic authentication on my Netdata-Nodes and open the "Nodes View beta", only the node I'm currently on shows information about itself, the rest is just "unreachable".
- When I click on a node and follow the link, I'm redirected without basic auth directly into the node's dashboard.
- Tested in Firefox with disabled Anti-Activity-Tracking and a default Chromium without any plugins.

As I understand, the Nodes View is probably not possible with Basic Authentication, isn't it?

**Comment by ilyam8** [comment]
@jacekkolasa if you have time ^^
