### ISSUE TITLE
Support host variables in prometheus remote write

### ISSUE THREAD

**Issue by Ehekatl** [netdata/netdata#7678]
##### Feature idea summary

Currently remote write will not send host variables

##### Expected behavior

It behave the same as in `/api/v1/allmetrics`

**Comment by ilyam8** [comment]
Hi @Ehekatl 
> host variables

variables or labels or both? 😄

**Comment by Ehekatl** [comment]
@ilyam8 I made a little pr, you can check there

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
