### ISSUE TITLE
Configure apps_groups.conf

### ISSUE THREAD

**Issue by snub-fighter** [netdata/netdata#7681]
##### Question summary
Ive attempted to alter the apps_groud.conf file to add a custom application `casinocoind`
My setup is as follows using the template inside the existing config file.
```
# -----------------------------------------------------------------------------
# casinocoind
  
casinocoind: casinocoind*
```
As there are two processes which are running I added the asterisk.
```

ps -e  | grep casino
28181 ?        00:00:00 casinocoind: #1
28183 ?        00:34:16 casinocoind
```

I then restarted the netdata service `service netdata restart`  I must be missing a step bc this seemed straight forward.

```
 /usr/libexec/netdata/plugins.d/apps.plugin  debug 1 2>&1  | grep casino
DIMENSION casinocoind '' absolute 1 10000 
DIMENSION casinocoind '' absolute 1 1024
DIMENSION casinocoind '' absolute 1 1024
DIMENSION casinocoind '' absolute 1 1
DIMENSION casinocoind '' absolute 1 1
DIMENSION casinocoind '' absolute 1 1
DIMENSION casinocoind '' absolute 1 1
DIMENSION casinocoind '' absolute 1 1
DIMENSION casinocoind '' absolute 1 1
DIMENSION casinocoind '' absolute 1 10000
DIMENSION casinocoind '' absolute 1 10000
.....
....
SET casinocoind = 0
SET casinocoind = 0
SET casinocoind = 0
SET casinocoind = 22
SET casinocoind = 2
SET casinocoind = 266484
SET casinocoind = 266484
SET casinocoind = 266484
SET casinocoind = 266484
SET casinocoind = 1928356
SET casinocoind = 3134980
SET casinocoind = 0
```

##### OS / Environment
Ubuntu 18.04
netdata v1.19.0-239-nightly
##### Component Name
  apps_group.conf -> casinocoind
##### Expected results
I expected to see the application show up but it does not.  Refer to image attached.
![image](https://user-images.githubusercontent.com/5192578/71839524-34e33f80-3070-11ea-9a5d-6570c65b645a.png)

**Comment by snub-fighter** [comment]
Additional findings.  

I shortened the process name from `casinocoind* to casinoc* ` this seems to have "patched" the issue.
The question that remains is why is a shorter name working?

```
# -----------------------------------------------------------------------------
# casinocoind
  
casinocoind: casinoc*
```

**Comment by vlvkobal** [comment]
The output of `apps.plugin` you provided shows that the plugin is working correctly. You probably didn't see your process in cpu charts because it wasn't using the cpu at that time. Try setting `enable zero metrics = yes` in `netdata.conf`.

**Comment by ilyam8** [comment]
And `Dashboard->Settings->Performance->Which dimensions to show?: all`

**Comment by snub-fighter** [comment]
Ill close as my issue is resolved.
