### ISSUE TITLE
Feature request: GPU monitoring support

### ISSUE THREAD

**Issue by Brainiarc7** [netdata/netdata#770]
Hello guys,

Here's a feature request:

Can we have GPU monitoring support on this software, in a similar fashion  that Ganglia uses?

That way, it can be adapted to work across multiple vendors (AMD and NVIDIA) as we call up the respective tools from a python script, as illustrated here:
1. http://blog.erdemagaoglu.com/post/3074180322/monitoring-nvidia-gpu-metrics-with-ganglia
2. https://sourceforge.net/projects/nvchart/

Regards,

Brainiarc7.

**Comment by paulfantom** [comment]
> That way, it can be adapted to work across multiple vendors (AMD and NVIDIA)

@Brainiarc7 do you have any example how to monitor AMD GPU?

**Comment by Splo0sh** [comment]
[http://www.rkblog.rk.edu.pl/w/p/monitoring-amd-intel-and-nvidia-graphics-card-usage-under-linux/](http://www.rkblog.rk.edu.pl/w/p/monitoring-amd-intel-and-nvidia-graphics-card-usage-under-linux/)

Sadly I cannot test the AMD approach since I don't have an AMD GPU.

**Comment by Brainiarc7** [comment]
Sorry I'm a bit late on this.

On Linux, raeontop is the way to go when it comes to monitoring GPU utilization.

It works with both amdgpu (on newer GCN-class hardware), radeonsi and radeon drivers.

**Comment by paulfantom** [comment]
It should be quite easy to write module for Nvidia GPU monitoring using [pyNVML](https://pypi.python.org/pypi/nvidia-ml-py/7.346.0) library. However I couldn't find any such library for AMD cards. I think it might be easier to write two modules, one for nvidia, and one for AMD.

Also currently I don't have nvidia or AMD card at home, so it will be quite hard for me to write this without ability to test what I am doing.
If anyone has access to appropriate hardware and is willing to write this module it would be perfect. There is a [wiki page](https://github.com/firehol/netdata/wiki/How-to-write-new-module) explaining how to do it and in case of problems I can always help.

**Comment by Brainiarc7** [comment]
Hey,

I can run the tests for you,  got the gear at hand.

Regards,

Brainiarc7

Going through the wiki now.

On Aug 20, 2016 4:48 PM, "Paweł Krupa" <notifications@github.com> wrote:

It should be quite easy to write module for Nvidia GPU monitoring using
pyNVML <https://pypi.python.org/pypi/nvidia-ml-py/7.346.0> library. However
I couldn't find any such library for AMD cards. I think it might be easier
to write two modules, one for nvidia, and one for AMD.

Also currently I don't have nvidia or AMD card at home, so it will be quite
hard for me to write this without ability to test what I am doing.
If anyone has access to appropriate hardware and is willing to write this
module it would be perfect. There is a wiki page
<https://github.com/firehol/netdata/wiki/How-to-write-new-module>
explaining how to do it and in case of problems I can always help.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/firehol/netdata/issues/770#issuecomment-241201118>, or mute
the thread

**Comment by Splo0sh** [comment]
I can try to write something when I'm back home again next week. Would be nice if you could test it then @Brainiarc7

**Comment by Brainiarc7** [comment]
Sure thing.

**Comment by Splo0sh** [comment]
Small update: 
I have a rough basis for nvidia cards which I will build into a netdata chart now. It took a bit because I want it to work with older cards in a kind of "legacy" mode as well. And there's also my day job... ;)

I hope that I will have something to test this weekend, latest early next week.

Cheers

**Comment by Splo0sh** [comment]
Okay, here is my first go: [https://github.com/Splo0sh/netdata_nv_plugin](https://github.com/Splo0sh/netdata_nv_plugin)

I have some problems with the legacy mode. It's working fine when debuging it via `/usr/libexec/netdata/plugins.d/python.d.plugin debug nv` but when running in netdata the `nvidia-settings` app that I call for that is not able to access any info. I have some ideas why this is happening but it's really secondary at the moment and I will take look soon.

@Brainiarc7, I tested it under Ubuntu 16.04, with the nvidia drivers installed. On one system I have a GTX 980 which works fine and on my old MacBook Pro it's a 9600m gt/9400m which also works but only showing temperature and memory usage. Legacy mode would add GPU and memory load, as well as clock frequencies.

I was also able to test the functions on a OpenSuse system at work with 4 Nvidia Quadro cards (K80, so with ECC) and these should also work. But I'm not allowed to let netdata run there, sooooo yeah. Hope it works ^^

And last but not least, I have no chance of testing Nvidia S-class units e.g. the Tesla S2070. But they should theoretically give additional temperatures (intake, exhaust and board) and fan RPM.

Give it a try and tell me if I screwed up somewhere ;)

And check out the `README`. Important thing is to have the nvidia drivers installed and either the `nvidia-ml-py` python package installed via pip, or downlaod the source package and copy the containing two scripts to netdata's `python-modules` folder.

Cheers

PS: I will look into AMD next, but I don't have a card to test and non of my family, friends or coworker seems to have one available for testing either. So this will be fun ^^

**Comment by Splo0sh** [comment]
@paulfantom is there a way to do a cleanup in case of a restart or stop of the netdata service? I'ld love to close the NVML lib in that case.

**Comment by paulfantom** [comment]
I don't think there is currently a way to do cleanup on exit by using python only. Is NVML a standalone application which needs to be closed after use?

About code:
1. Please change line 54 from `print()` to `self.info()`. Netdata uses stdout (print) only for sending data, and stderr (self.info, self.error, self.debug) for logging. Sending logging info on stdout will stop whole python plugin.
2. You could execute `pynvml.nvmlShutdown()` before returning False in `check()` method (lines 137, 147)
3. `if self.deviceCount > 0:` and `if self.unitCount > 0:` in `_get_data()` are not needed. If those are 0, for loops won't start.
4.  You don't need to check if some module (in this case `subprocess` and `re`) is imported. Just import it, python will handle it, and code will be cleaner.
5. `'Error in fetching data from nvidia-settings'+output` should be:
`'Error in fetching data from nvidia-settings '+output`. Just a space missing.

Overall looks good. Thanks for writing it! :+1:

**Comment by Splo0sh** [comment]
Thank you for the feedback @paulfantom!! I updated it according to your suggestions. Also I peeked into the `base.py` and adjusted the subprocess import to only import the necessary stuff.

I will now look into the legacy mode. And if I am able to get my hands on an AMD card and/or a system with a Intel onboard graphics, I can give those a shot as well.

Cheers and thanks :)

**Comment by Splo0sh** [comment]
> I don't think there is currently a way to do cleanup on exit by using python only. Is NVML a standalone application which needs to be closed after use?

I thought maybe you are using something like [atexit](https://docs.python.org/2/library/atexit.html) or so.

Regarding the `NVMLShutdown`, form the Nvidia NVML documentation:

> Shut down NVML by releasing all GPU resources previously allocated with nvmlInit().
> For all products.
> This method should be called after NVML work is done, once for each call to nvmlInit() A reference count of the number of initializations is maintained. Shutdown only occurs when the reference count reaches zero.
> For backwards compatibility, no error is reported if nvmlShutdown() is called more times than nvmlInit().

I could load and release the resources on every check but I wanted to catch all the possible volatile ECC errors and my understanding is, the driver won't shutdown as long as I keep NVML loaded:

> ECC counter types.
> Note: Volatile counts are reset each time the driver loads. On Windows this is once per
> boot. On Linux this can be more frequent. On Linux the driver unloads when no active
> clients exist. If persistence mode is enabled or there is always a driver client active (e.g.
> X11), then Linux also sees per-boot behavior. If not, volatile counts are reset each time a
> compute app is run. 

The loading and unloading is kinda quick. Here's a run of 100 cycles on my old machine:
```
total time:  0.0277769565582 s
time per cycle:  0.000277769565582 s
```

What do you think? Load and unload each time for a query or leave it as is?

**Comment by ktsaou** [comment]
From the documentation I understand that `NVMLShutdown()` should match `nvmlInit()`. Are you calling `nvmlInit()` on each iteration?

**Comment by Splo0sh** [comment]
No, at the moment only in the plugin's  `check()` initialization, to initialize it once for the lifetime of the plugin. But I could call the init and shutdown at every `_get_update()`.

**Comment by paulfantom** [comment]
> And if I am able to get my hands on an AMD card and/or a system with a Intel onboard graphics, I can give those a shot as well.

But don't mix them with this one. I think we should have it in separate modules.

> I thought maybe you are using something like atexit or so.

It was not needed previously, but you can use it for this module. For example somewhere in a constructor.

> But I could call the init and shutdown at every _get_update()

Why? I think it is faster to initialize something once, and use it throughout whole runtime than to initialize it every second.

**Comment by paulfantom** [comment]
One more thing. Have you tested it on python >= 2.7 and python >= 3.2 ?

**Comment by Splo0sh** [comment]
@paulfantom, my thoughts exactly!

I will not mix them. It will be an amd.chart.py and a intelgpu.chart.py or something like that : )

**Comment by paulfantom** [comment]
> no, but I can do that.

Please do. All netdata python modules should be compatible with python versions specified above.

**Comment by Splo0sh** [comment]
Okay @paulfantom, I testet it with 2.6.8, 2.7.12, 3.2.6 and 3.5.2. But we might have small issue with the nvidia-ml-py package since there is one single print function in it that is not in parentheses (pynvml.py:1671). I added the fixed one to my repo, just something to keep in mind.

**Comment by paulfantom** [comment]
I don't think this will be a problem (print statement) because "nvmlSystemGetTopologyGpuSet" is not executed anywhere (or is it?).

Whoa, that's a lot of interpreter versions! Just for the future, python 2.6.8 is not supported by netdata and python 2.7.x is some kind of LTS version.

**Comment by Splo0sh** [comment]
It was good practice for me and environments in this case ;)

> I don't think this will be a problem (print statement) because "nvmlSystemGetTopologyGpuSet" is not executed anywhere (or is it?).

Well it still throws an error when importing `pynvml`. Do you know a way to ignore it and import it never the less?

For the moment being, everybody who wants to use it just has to copy the nv.chart.py, nv.conf and the fixed pynvml.py file from my repo to their respective places (all in the readme). I think this is fine.

**Comment by paulfantom** [comment]
Wow, nice readme!

Does something like this print anything on stdout:
```py
import pynvml
pynvml.nvmlInit()
pynvml.nvmlShutdown()
```
and can you post output if it is?

**Comment by paulfantom** [comment]
Also there is this funny thing in python which may work (test on python3 first):
```py
def new_print(*args, **kwargs):
  pass

old_print = print
print = new_print
import pynvml
pynvml.nvmlInit()
pynvml.nvmlShutdown()
print = old_print
```

**Comment by paulfantom** [comment]
But for python2 this won't work since `print` is a statement, not a function. However by adding `from __future__ import print_function` to the begging of `python.d.plugin` (must be before other imports), this may work or it will crash... I don't know, but it is worth testing.

**Comment by Splo0sh** [comment]
> Wow, nice readme!

Thanks!

> Does something like this print anything on stdout:

```python
Python 3.5.2
>>> import pynvml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jan\Anaconda3\envs\py35\lib\site-packages\pynvml.py", line 1671
    print c_count.value
                ^
SyntaxError: Missing parentheses in call to 'print'
```
Like I said, it fails at the syntax check during import.

> Also there is this funny thing in python which may work (test on python3 first):

```python
>>> def new_print(*args, **kwargs):
...   pass
...
>>> old_print = print
>>> print = new_print
>>> import pynvml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jan\Anaconda3\envs\py35\lib\site-packages\pynvml.py", line 1671
    print c_count.value
                ^
SyntaxError: Missing parentheses in call to 'print'
>>> new_print('something')
>>> print('something')
>>>
```

Btw,  I also tried to import single functions, same import error, of course. I think there is no way around this.

**Comment by Splo0sh** [comment]
At the moment I'm just thinking about the best way to contact them...

**Comment by paulfantom** [comment]
> print c_count.value

That is very strange, python 3 doesn't have print as statement, I wonder how they did this. 
Have you tried my idea for python2? Basically this:
```py
from __future__ import print_function
def new_print(*args, **kwargs):
  pass

old_print = print
print = new_print
import pynvml
pynvml.nvmlInit()
pynvml.nvmlShutdown()
print = old_print
```

**Comment by paulfantom** [comment]
However I don't think it will change anything.

Also good luck contacting them. It may be hard to accomplish.

**Comment by Splo0sh** [comment]
Yes I did. The print function switching works and I can also import pynvml... Crazy world. Porbably the `from __future__ import print_function` doesn't propagate to imports (scopes and all).

My guess is, since all the other print functions are correctly ported, they at some point added this and didn't check if it works under Python 3.

**Comment by Splo0sh** [comment]
Oh, another thing. I will probably kick out the legacy mode. I already killed so much time on it but it boils down to it needing an x-server and this nvidia tool apparently also checks for a real monitor to be plugged into the card. I will try a few workarounds but I think it will just produce headaches on my side and an unstable plugin for netdata. And that is definitely something I wouldn't want.

So if I don't find an elegant way of doing this, old nvidia cards (e.g. geforce 9600) will have to live with only temperature and 'used' memory information readouts.

**Comment by Splo0sh** [comment]
Okay, I found the problem. To put it in a nutshell, you need an active X session for the legacy mode. Which is fine, it only needs a little user input to share the session with root.

If the legacy mode is set to True and fails, it gets deactivated and the plugin falls back to normal mode, so no harm.

I updated my repo and hopefully added all required help/instructions to the readme.

**Comment by Splo0sh** [comment]
Small update: I'm maybe able to get my hands on an AMD card in a few weeks so I can start working on AMD graphics card charts.

@paulfantom, do you want me to do a pull request for the nvidia charts in the meantime, or would you like to keep it separate for people to install it on their own? I would include the fixed `pynvml` Python module which works with both Python 2 and 3.

**Comment by paulfantom** [comment]
@Splo0sh if you could wait for a little bit with pull request that would be great. Your work is great, it's just that I don't have much time right now to review this.

**Comment by Splo0sh** [comment]
Absolutely fine with me :) just hit me up!

**Comment by bartwo** [comment]
Hi is there any update on this?

**Comment by rinseout** [comment]
For anyone looking for the nvidia plugin, it's been done by @coraxx and resides here:
https://github.com/coraxx/netdata_nv_plugin

**Comment by ktsaou** [comment]
Thanks! I added the wiki page https://github.com/firehol/netdata/wiki/Third-Party-Plugins that lists third party distributed netdata plugins. I already listed the nvidia one.

**Comment by rinseout** [comment]
Thanks for everything guys. We will be implementing this at work to display availability/load on our shared deep learning boxes.

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/issues/2249

**Comment by icyblade** [comment]
Is there any chance of implementing this plugin into netdata?

**Comment by ktsaou** [comment]
These work:

- https://github.com/firehol/netdata/pull/2759
- https://github.com/coraxx/netdata_nv_plugin

**Comment by harutyundermenjyan** [comment]
it's not working for me as well.
I've installed nv plugin on 8 machines and it worked good a ~year or a months ago. But after last updates it is stopped to work.

**Comment by l2isbad** [comment]
@harutyundermenjyan i checked and it works for me
The only fixes i did are
https://github.com/firehol/netdata/issues/2249#issuecomment-304556855

**Comment by ktsaou** [comment]
netdata can monitor NVIDIA cards: https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nvidia_smi

I am not sure how to do it for AMD cards.
I am closing this. If you need can help with AMD, please open a new issue.

**Comment by edhemphill** [comment]
it should be possible to monitor the amdgpu drivers via [ROCm-SMI](https://github.com/RadeonOpenCompute/ROC-smi)  which itself just looks at parts of `/sys`

**Comment by shellshock1953** [comment]
Hi, Netdata!
Any possible updates on this one?
Proton is a thing now, SteamDeck is upcoming, and seems Linux gaming is getting more and more mature every day!.
It will be great to be able to monitor AMD GPU using Netdata!

**Comment by ktsaou** [comment]
@ilyam8 please have a look. Monitoring GPUs seems to be a very common request.
