### ISSUE TITLE
Parse host tags

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#7700]
#### Feature idea summary
In the new exporters, we will no longer support "host tags". Users will have to define them as custom host labels in netdata.conf. We need to update the documentation to this effect. But we will need to parse existing "host tags" from the netdata.conf [backend] section and consider them custom host labels (need to check the format that each backend uses for tags/labels, so we know how to process them).

##### Expected behavior
Host tags are parsed in accordance with the configured backend format and stored as labels.

**Comment by amoss** [comment]
Some questions:
* Why is this blocked by the JSON parser/generator issue? These are being read from the `netdata.conf` and output in the exporter format.
* What are the cases that we need to consider (i.e. what is the explicit list of backend formats) ?
* The key point in the earlier discussion was that the syntax is currently dependent on the backend type, and after the move it will be the same configuration entries for different types of syntax depending on the exporter type - how do we resolve the issue of knowing which format to accept from the configuration file?
