### ISSUE TITLE
JSON parser/generator as hard dependency (probably json-c)

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#7701]
#### Feature idea summary
JSON being one of the most used I/O formats for the Netdata agent we should not reinvent the wheel and use `json-c` *(or other similar library)* to both parse/generate JSON to/from same data structures.

`json-c` *(https://github.com/json-c/json-c)* was chosen as it is already used in health as soft dependency but it is up to the discussion and better library might be chosen *(if it fits all the requirements, at least tries to adhere to JSON standards and has better performance)*.

Last necessity to parse JSON arrised in #7700 and it was discussed it makes no sense to handcraft YAJPG&trade; (Yet Another Json Parser and Generator).

Start using this parser for all new code that needs to handle JSON.

In case we will decide bringing in `json-c` as hard dependency is an issue we might look into something like cJSON *(https://github.com/DaveGamble/cJSON)* that we can bring into the codebase directly.

##### Expected behaviour
*Do not write own JSON parsing code in multiple places
*Do not hand generate JSON by `buffer_sprintf` in multiple places
*we should be able to parse JSON into same data structures  that are used to generate JSON string

**Comment by amoss** [comment]
Some initial points:

* cJSON is not thread safe.
* The data-model for cJSON is one structure per JSON which implies heavy use of memory allocation / deallocation every time we parse/serialize JSON data.

The `buffer_sprintf` code that outputs JSON is heavily used and we need to consider the performance of anything that we replace it with. One advantage of the current code is that it does not touch the memory allocator during output of JSON

**Comment by amoss** [comment]
This has been done via a different issue.
