### ISSUE TITLE
Graphs for nfacct.plugin and /proc/net/stat/nf_conntrack

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#7707]
##### Question summary
I'm trying to set up the netfilter graphs in netdata. I get a "Connection Tracker Connections" graph under the "Firewall (netfilter)" heading but that is the only one.
I'm seeing the following in my error.log

> netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/net/stat/nf_conntrack' (errno 2, No such file or directory)

However, Ubuntu doesn't create that directory for conntrack. I have only the following:
> /proc/sys/net/netfilter/nf_conntrack_acct
> /proc/sys/net/netfilter/nf_conntrack_buckets
> /proc/sys/net/netfilter/nf_conntrack_checksum
> /proc/sys/net/netfilter/nf_conntrack_count
> /proc/sys/net/netfilter/nf_conntrack_dccp_loose
> /proc/sys/net/netfilter/nf_conntrack_dccp_timeout_closereq
> /proc/sys/net/netfilter/nf_conntrack_dccp_timeout_closing
> /proc/sys/net/netfilter/nf_conntrack_dccp_timeout_open
> /proc/sys/net/netfilter/nf_conntrack_dccp_timeout_partopen
> /proc/sys/net/netfilter/nf_conntrack_dccp_timeout_request
> /proc/sys/net/netfilter/nf_conntrack_dccp_timeout_respond
> /proc/sys/net/netfilter/nf_conntrack_dccp_timeout_timewait
> /proc/sys/net/netfilter/nf_conntrack_events
> /proc/sys/net/netfilter/nf_conntrack_expect_max
> /proc/sys/net/netfilter/nf_conntrack_frag6_high_thresh
> /proc/sys/net/netfilter/nf_conntrack_frag6_low_thresh
> /proc/sys/net/netfilter/nf_conntrack_frag6_timeout
> /proc/sys/net/netfilter/nf_conntrack_generic_timeout
> /proc/sys/net/netfilter/nf_conntrack_helper
> /proc/sys/net/netfilter/nf_conntrack_icmp_timeout
> /proc/sys/net/netfilter/nf_conntrack_icmpv6_timeout
> /proc/sys/net/netfilter/nf_conntrack_log_invalid
> /proc/sys/net/netfilter/nf_conntrack_max
> /proc/sys/net/netfilter/nf_conntrack_sctp_timeout_closed
> /proc/sys/net/netfilter/nf_conntrack_sctp_timeout_cookie_echoed
> /proc/sys/net/netfilter/nf_conntrack_sctp_timeout_cookie_wait
> /proc/sys/net/netfilter/nf_conntrack_sctp_timeout_established
> /proc/sys/net/netfilter/nf_conntrack_sctp_timeout_heartbeat_acked
> /proc/sys/net/netfilter/nf_conntrack_sctp_timeout_heartbeat_sent
> /proc/sys/net/netfilter/nf_conntrack_sctp_timeout_shutdown_ack_sent
> /proc/sys/net/netfilter/nf_conntrack_sctp_timeout_shutdown_recd
> /proc/sys/net/netfilter/nf_conntrack_sctp_timeout_shutdown_sent
> /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal
> /proc/sys/net/netfilter/nf_conntrack_tcp_loose
> /proc/sys/net/netfilter/nf_conntrack_tcp_max_retrans
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_close
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_close_wait
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_established
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_fin_wait
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_last_ack
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_max_retrans
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_syn_recv
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_syn_sent
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_time_wait
> /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_unacknowledged
> /proc/sys/net/netfilter/nf_conntrack_timestamp
> /proc/sys/net/netfilter/nf_conntrack_udp_timeout
> /proc/sys/net/netfilter/nf_conntrack_udp_timeout_stream
> /proc/sys/net/nf_conntrack_max

I don't know if the `nfacct.plugin` is important for any of this but it seems to be set up and working correctly even though it doesn't make any new graphs.
Runnning `sudo /usr/libexec/netdata/plugins.d/nfacct.plugin 1 debug`
I get:
> nfacct.plugin: calling nfacct_init()
> nfacct.plugin: starting data collection
> nfacct.plugin: calling nfacct_collect()
> nfacct.plugin: calling nfacct_send_metrics()
> nfacct.plugin: iteration 1, dt 999997 usec
> ...

Could someone tell me if I don't have conntracker set up properly in the netdata.conf ?
Also, what graphs should I be seeing from `nfacct.plugin` vs. `proc.plugin: proc_net_stat_conntrack`?

##### OS / Environment
OS:         Ubuntu 18.04.3 LTS (bionic)

##### Component Name
proc.plugin: proc_net_stat_conntrack
nfacct.plugin

##### Expected results
I think I should be seeing more charts from these plugins.
Might be related to: https://github.com/netdata/netdata/issues/161

**Comment by vlvkobal** [comment]
There is a bug in Autotools checks for `nfacct.plugin`. Please test a fix from #7727.

**Comment by vlvkobal** [comment]
As for the Connection Tracker charts in `proc.plugin: proc_net_stat_conntrack`, they are the same as in `nfacct.plugin`. The difference is that `proc.plugin` uses a deprecated `procfs` interface.
