### ISSUE TITLE
How to sum bandwidth of two nic?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7708]
##### Question summary
Pretty simple request, now I can have the bandwidth utilization for enp1s0 and enp2s0, but I wish to have chart to show the sum of enp1s0 and enp2s0 in terms of sent and receive

**Comment by snub-fighter** [comment]
I have a similar question that relates to aggregating data.  [#7706 ](https://github.com/netdata/netdata/issues/7706)

**Comment by ilyam8** [comment]
Hi @startryst. There is no way to do it atm (implying you want to use netdata only), but it is in our plans.

**Comment by snub-fighter** [comment]
@ilyam8 Is there a timeline for that?  Im attempting to build out a python plugin that does this for a donut pie chart.

**Comment by ilyam8** [comment]
@snub-fighter there is no defined timeline, i may be wrong but a lot of things should be changed to make this happen - we need to be able to create custom charts from metrics. 

I think it will be possible after all in https://github.com/netdata/netdata/issues/7730 will be implemented.

**Comment by amoss** [comment]
To give some expectation on time-scales - #7730 is the entire roadmap for the DB for the rest of 2020. It's not clear yet what the priority order will be, but please keep an eye on the issue - we'll be updating it over the next two weeks.
