### ISSUE TITLE
I used the all in one installer. Can someone post step by step how to uninstall it

### ISSUE THREAD

**Issue by lacedup** [netdata/netdata#7709]
I used the all in one installer. Can someone post step by step how to uninstall it? Thank you

**Comment by Saruspete** [comment]
Hello,

The installed should have printed the path to the uninstall script :
```
/usr/libexec/netdata/netdata-uninstaller.sh
```
execute it as root, and you're done.

**Comment by Rodri9o** [comment]
echo -e "y y y y y y \n \n \n \n \n \n \n \n" | /usr/libexec/netdata/netdata-uninstaller.sh --yes
