### ISSUE TITLE
Unable to disable prometheus remote write backend

### ISSUE THREAD

**Issue by jelmd** [netdata/netdata#7710]
##### Bug report summary

Neither `./configure --enable-backend-prometheus-remote-write=no ..` nor `./configure --disable-backend-prometheus-remote-write` prevents netdata from linking in prometheus remote write backend.

##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)
Linux bionic 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### Netdata version (ouput of `netdata -V`)
netdata v1.19.0 (https://github.com/netdata/netdata/releases/download/v1.19.0/netdata-v1.19.0.tar.gz)

##### Component Name
build

##### Steps To Reproduce
on a ubuntu 18.04 (bionic machine) do:
```
apt-get install zlib1g-dev uuid-dev libuv1-dev liblz4-dev libjudy-dev libssl-dev libmnl-dev gcc make git autoconf autoconf-archive autogen automake pkg-config curl python libjson-c-dev libcups2-dev libipmimonitoring-dev libnetfilter-acct-dev libxen-dev libyajl-dev libprotobuf-dev libsnappy-dev protobuf-compiler libmongoc-dev xen-utils-4.9
wget https://github.com/netdata/netdata/releases/download/v1.19.0/netdata-v1.19.0.tar.gz
tar xzf netdata-v1.19.0.tar.gz
cd netdata-v1.19.0
./configure --disable-silent-rules --enable-accept4 --enable-x86-sse --enable-lto --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/lib --libdir=/usr/share --with-webdir=/usr/share/netdata/www --with-libcap --with-zlib --with-math --with-user=netdata --enable-https --enable-dbengine --enable-jsonc --without-jemalloc --without-tcmalloc --enable-plugin-nfacct --enable-plugin-freeipmi --enable-plugin-xenstat --enable-plugin-cups --enable-backend-mongodb --enable-backend-kinesis=no --enable-backend-prometheus-remote-write=no

##### Expected behavior
Prometheus backend support should be disabled. No netdata dependency to snappy, protobuf, stdc++ libs.

**Comment by ilyam8** [comment]
Hi @jelmd 

i think the bug is fixed in https://github.com/netdata/netdata/pull/7674

**Comment by ilyam8** [comment]
dup of https://github.com/netdata/netdata/issues/7673
