### ISSUE TITLE
Netdata high ram usage 

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7711]
##### Bug report summary
Our master netdata server with 35 hosts streaming metrics has CPU usage of 80 percent (25.5 GB of 32 GB)
![image](https://user-images.githubusercontent.com/7656049/72240998-e4815a00-35fa-11ea-834e-9b488711215d.png)
 DBengine is using about 20Gb of ram:
![image](https://user-images.githubusercontent.com/7656049/72241087-20b4ba80-35fb-11ea-9364-73dda6d4a7c2.png)
The `page_cache_size` is 128 and `dbengine_disk_space` is  4096 in the master node. 
Here is the output of htop on the master server:
![image](https://user-images.githubusercontent.com/7656049/72241537-55754180-35fc-11ea-8ce4-46f44b4755b3.png)

##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)
Linux ubuntu 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.1 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.1 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
##### Netdata version (ouput of `netdata -V`)
v1.19.0
##### Component Name
DBengine
##### Expected behavior

**Comment by mfundul** [comment]
I think you're talking about RAM usage and not CPU usage, probably a typo?

The memory numbers appear to be correct. You have 35 hosts, which means 35 database instances. For a page cache size of 128MiB times 35 you get over 4GiB of RAM usage for the aggregate page cache size over all database instances.

Moreover, for 4GiB storage space per host you get 140GiB of compressed metrics. With typical compression savings of 70% that would mean that the effective amount of stored metrics is up to 467GiB. The amount of needed metadata are 3% of 467GiB which amounts to 14GiB of metadata.

See [here](https://github.com/netdata/netdata/tree/master/database/engine) for reference.

The expected memory footprint of the dbengine instances for those assumptions is up to 18GiB RAM.

If each host had about 2000 metrics, with an average savings ratio of 70% and a data collection interval of 1 second that would give you a retention period of up to one week. You can validate that by selecting any chart in the dashboard, zooming out and scrolling left until the beginning of history. The actual retention period depends on the number of metrics, the average compression ratio and the data collection frequency.

**Comment by yasharne** [comment]
Thanks for your explanation, now things make sense.
