### ISSUE TITLE
Is there any way to enable ipmi monitoring without recompiling netdata

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7712]
##### Question summary
We are using netdata precompiled binaries (the one that installs under /opt by default) and now we want to enable ipmi monitoring on our bare-metal servers but installing `libipmimonitoring-dev` and adding this plugin to netdata.conf file was not enough:
```
[plugin:freeipmi]
    update every = 5
    command options = 
```
`ipmimonitoring` command works fine
##### OS / Environment
Ubuntu 16.04
Netdata 1.19
##### Expected results
monitor ipmi parameters without recompiling netdata from source.

**Comment by ilyam8** [comment]
Hi @yasharne 

it is not possible

> https://github.com/netdata/netdata/tree/master/collectors/freeipmi.plugin#compile-freeipmiplugin

> re-install Netdata from source. The installer will detect that the required libraries are now available and will also build freeipmi.plugin
