### ISSUE TITLE
Login to netdata cloud/registry not working for Safari, but OK for Firefox

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#7715]
##### Bug report summary
Many days ago, it was fine for Safari, but don't know what happened, recent a few weeks, the login feature of netdata doesn't work, the symptom is as below:
![Screen Shot 2020-01-13 at 10 48 58 PM](https://user-images.githubusercontent.com/22472752/72265243-2809b180-3657-11ea-9129-8fe49eb31b85.jpg)
sign in by google is success

![Screen Shot 2020-01-13 at 10 50 26 PM](https://user-images.githubusercontent.com/22472752/72265283-3657cd80-3657-11ea-9435-3415ff5400d2.jpg)
but couldn't get the nodes from the list. showing loading....

and also when click the nodes button, it will revert back to the login window, and if I login again and click the nodes button, same, back to the login window again...

But the firefox on the same Mac is OK, and I tried clear all my safari history, still not working.

##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)
Mac OS 10.14.6, Safari 13.0.4

**Comment by thiagoftsm** [comment]
Hi @startryst ,

You did not give us Netdata version, please, could you give us the version that you are running?

Another doubt, are you using `TLS` with your netdata agent?

Best regards!

**Comment by startryst** [comment]
@thiagoftsm 

netdata -V
netdata v1.19.0-296-nightly

Not using TLS

**Comment by cakrit** [comment]
Hi @startryst, apologies for not responding earlier.

I'm not sure what's happening here, but we're feverishly working on a completely revamped version of the cloud. This issue will definitely go away with the new version, which is coming in ~1 month. We're not doing any more fixes on the old code, so stay tuned and I think you'll like what you'll see! :)
