### ISSUE TITLE
Verify and clean up shell health related shell scripts.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#7719]
This covers all the shell scripts under `health', as well as `contrib/sles11/alarm-notify-basic.bash3.sh, for which all the following need to be done:

* Ensure consistent formatting.
* Fix any extant issues reported by shellcheck.
* Try to eliminate as may shellcheck directives  as possible, and fix the issues those are hiding.
* Trying to shift as much as possible to using POSIX compliant Bourne shell code instead of relying on Bash.

**Comment by ilyam8** [comment]
@cosmix is it fixed? was it a bug? i am asking because it will be added as a fixed bug to the changelog automatically

**Comment by cosmix** [comment]
I think so @ilyam8 cc @Ferroin please reopen and/or relabel, if I'm mistaken.

**Comment by Ferroin** [comment]
It probably should have had the nochangelog tag, as it didn't get "fixed" so much as "we decided what to do about it and didn't need the issue for that approach".
