### ISSUE TITLE
strip ELF in order to reduce release size

### ISSUE THREAD

**Issue by setop** [netdata/netdata#7728]
##### Feature idea summary

strip ELF in order to reduce release size

##### Expected behavior

Before:

```
du -sh netdata/
73M     netdata/
```

Striping:

`find netdata -type f -executable -print0 | xargs -0 strip`

After:

```
du -sh netdata/
51M     netdata/
```

Saves 22MB, 30%, multiplied by the number of nodes in the monitored infrastructure.

**Comment by prologic** [comment]
@setop May I confirm what your installation method was on your machines?

**Comment by cosmix** [comment]
@setop hey. We need additional information about your environment, Netdata version and installation method before continuing. If you intend to provide this info please reopen.

**Comment by setop** [comment]
I used `netdata-v1.19.0.gz.run` on a Linux x86_64 machine.
