### ISSUE TITLE
Port in use after uninstall from Ubuntu

### ISSUE THREAD

**Issue by braunsonm** [netdata/netdata#7734]
##### Bug report summary
After installing Netdata from the Ubuntu repository and then uninstalling it and installing it using the bash script, the netdata service always fails to start with the following error in the logs:
```
2020-01-14 21:32:03: netdata ERROR : MAIN : uv_pipe_bind(): address already in use (errno 98, Address already in use)
netdata: daemon/commands.c:543: command_thread: Assertion `0 == uv_loop_close(loop)' failed.
```

Even though the output of `sudo lsof -i -P -n | grep 19999` is blank, and so is `ps fax | grep 19999`. The output of `netstat -nat | grep LISTEN | grep 19999` is also blank.

I have uninstalled the Ubuntu package using the —purge flag to no effect and I’ve uninstalled and reinstalled using your bash script twice with the same error. The install does not have any failures except when starting the service (due to the above issue).

I also have adjusted the `netdata.conf` to contain the following:
```
[web]
  default port = 30002
```
As just a random port I know is open, and even then the process still fails to start with systemctl.

Note that netdata did work properly with the Ubuntu package, it’s only when trying to switch over did this issue arise.

##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)
Linux discus-spark1 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.3 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.3 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic

##### Netdata version (ouput of `netdata -V`)
netdata v1.19.0-314-nightly

**Comment by prologic** [comment]
What does your `ss -tapn` look like? or `ss -tapn | grep 19999`?

**Comment by braunsonm** [comment]
Oddly, blank as well. I might have to restart the server, but trying to avoid that if possible.

**Comment by prologic** [comment]
Are you able to provide an `strace` of the startup to me? A [gist](https://gist.github.com) should work. Don't restart the server if you can help it; let's see if we can't figure this out :) -- To be clear do you have stock standard config for NetData -- i.e: you haven't customized what port it uses/etc?

**Comment by braunsonm** [comment]
I did attempt to, but it didn’t help so I returned to the blank default file.

I can provide the stack trace, you just mean the error.log file? If so, I’ve uploaded a gist [here](https://gist.github.com/braunsonm/7a51de9dc91632bde7146b4fc5ece593), you can see the startup loop from systemd restarting it over and over in there. (twice in the snippet I uploaded).

**Comment by prologic** [comment]
I actually meant; could you do the following:

```bash
systemctl stop netdata
strace netdata -D &> netdata.log
```

And upload `netdata.log` to a Github gist. The error log you provided is _also_ useful; Thank you :)

**Comment by braunsonm** [comment]
Ah, [here](https://gist.github.com/braunsonm/62155e585cd9c95271f676e83a967956) you are.

**Comment by mfundul** [comment]
@braunsonm it looks as if there are 2 netdata instances from the error messages, not that this is the case though. Can you delete the file `/tmp/netdata-ipc` and run netdata again to see what changes?

**Comment by braunsonm** [comment]
That did it! All seems to be working well now. You can close this or leave it open if it is indeed a bug, thanks for helping me :)

**Comment by prologic** [comment]
@mfundul I _think_ we can do something to improve this situation? Some ideas:

- Detect if the libuv IPC socket exists on startup and delete it if no other instances of `netdata` are found to be running
- Warn the user with an `ERROR` level message on the existence of a possible erroneous libuv IPC socket

What do you think?

I'm a bit sad I wasn't able to see this in the strace output but never-mind :)

**Comment by mfundul** [comment]
> 
> 
> @mfundul I _think_ we can do something to improve this situation? Some ideas:
> 
>     * Detect if the libuv IPC socket exists on startup and delete it if no other instances of `netdata` are found to be running
> 
>     * Warn the user with an `ERROR` level message on the existence of a possible erroneous libuv IPC socket
> 
> 
> What do you think?
> 
> I'm a bit sad I wasn't able to see this in the strace output but never-mind :)

It is deleted in theory, but I guess it was installed as a different user from Ubuntu than the default netdata user of the github codebase. As a result it was not deleted, and there seems to be a bug during cleanup, before the actual print that warns the user that the command server failed to initialize. That is the bug that actually needs to be fixed.

**Comment by prologic** [comment]
> seems to be a bug during cleanup

I _assume_ you mean the uninstall script? Is it [this one](https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-uninstaller.sh)?

**Comment by mfundul** [comment]
> 
> 
> > seems to be a bug during cleanup
> 
> I _assume_ you mean the uninstall script? Is it [this one](https://github.com/netdata/netdata/blob/master/packaging/installer/netdata-uninstaller.sh)?

I was talking about the netdata agent crashing instead of disabling the command server, but it would be a good idea to add it to the uninstaller as well.

**Comment by prologic** [comment]
> I was talking about the netdata agent crashing instead of disabling the command server, but it would be a good idea to add it to the uninstaller as well.

👍I'll look into doing this today.
