### ISSUE TITLE
Change only part of config without copying whole config file to /etc/netdata

### ISSUE THREAD

**Issue by amishmm** [netdata/netdata#7736]
##### Question summary
I find (suspect) that netdata squid plugin is creating some issue with my squid setup. (Due to its repeated queries)

So as a workaround I disable squid plugin by adding `squid: no` to `/etc/netdata/python.d.conf`

Now current solution is to copy whole `/usr/lib/netdata/conf.d/python.d.conf` to `/etc/netdata/python.d.conf` and then add line `squid: no`

So tomorrow if an important change is made to default `/usr/lib/netdata/conf.d/python.d.conf`, (say a buggy plugin is disabled or a new plugin is replaced by old one and old one is disabled by default) then I would not know until I check the difference every time I upgrade netdata and then apply the same change to `/etc/netdata/python.d.conf`. (otherwise buggy plugin will get activated OR new plugin and old plugin both will get activated and conflict with each other)

Is there a way where I can override only some parts of default python.d.conf and leaving everything as is?

i.e. say a file called `/etc/netdata/python.d.override.conf`
```
squid: no
```

**Or an alternate way** is to use include file?

The `/etc/netdata/python.d.conf` will look like this:

```
include: /usr/lib/netdata/conf.d/python.d.conf
squid: no
```

In above two example, netdata will apply everything that is in `/usr/lib/netdata/conf.d/python.d.conf` file and then disable squid plugin.

This makes everything so easy to maintain. Whatever changes are made in default configuration file, will automatically apply in future without manual intervention.

Please do let me know if this is already possible in any way.

Please consider this as a feature request if its not possible currently.

##### OS / Environment
Any OS / Any Environment

**Comment by prologic** [comment]
Have you read the [Configuration](https://docs.netdata.cloud/docs/configuration-guide/#configuration-guide) section of our docs? I need to figure out myself if what you're asking is possible; bare with me :)

**Comment by prologic** [comment]
I'm not sure its possible according to [How configuration works](https://docs.netdata.cloud/docs/configuration-guide/#how-netdata-configuration-works) to do what you're described -- which I see as an import system really. I'll check with the team that looks after this part.

**Comment by amishmm** [comment]
> Have you read the [Configuration](https://docs.netdata.cloud/docs/configuration-guide/#configuration-guide) section of our docs? I need to figure out myself if what you're asking is possible; bare with me :)

Yes I read it but no where I could find what I was looking for.

Many popular softwares allow you to just override the defaults instead of copying and modifying whole config files. (e.g systemd)

Or they allow you to include one config inside other so you do not need to duplicate every configuration (squid, httpd, dovecot etc etc.)

**Comment by ilyam8** [comment]
Hi @amishmm 

> Now current solution is to copy whole /usr/lib/netdata/conf.d/python.d.conf to /etc/netdata/python.d.conf and then add line squid: no

Correct, that is how it works with all user/stock configs.

> say a buggy plugin is disabled or a new plugin is replaced by old one and old one is disabled by default

If there is buggy module we need to fix the bug. If we want something to be disabled by default we dont use `python.d.conf`, we disabled it in module source code, example

https://github.com/netdata/netdata/blob/006e1ea38f538fedfd22f38059b02111cd3f3f02/collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py#L15

(to enable it module should be explicitly enabled in the `python.d.conf`)

**Comment by ilyam8** [comment]
> Many popular softwares allow you to just override the defaults instead of copying and modifying whole config files. (e.g systemd)

> Or they allow you to include one config inside other so you do not need to duplicate every configuration (squid, httpd, dovecot etc etc.)

There is an epic - configuration manager, it will handle all these, but it is not high priority atm, there is no clear view how it will be implemented. But it is in the roadmap i think.

https://github.com/netdata/netdata/issues/6432

**Comment by amishmm** [comment]
Hi @ilyam8 

Thank you for your clarification.

> If there is buggy module we need to fix the bug. If we want something to be disabled by default we dont use python.d.conf, we disabled it in module source code, example

This does not seem to be true. Because if I see default python.d.conf, there are lines like:
```
apache_cache: no
chrony: no
logind: no
```

Also Configuration manager (#6432) does not seem to be related to my question. It looks like a frontend to config but it will not solve my problem unless backend is changed to read an override file.

My feature request is very minor. Its probably going to be just few line code.

Step 1) Read `/etc/netdata/python.d.conf` if exists, else read `/usr/lib/netdata/conf.d/python.d.conf`
Step 2) Read `/etc/netdata/conf.local/python.d.conf` if exists (which will override settings of step 1)

Code for step 1 already exists. Step 2 can re-call the same function that is used in step 1) but with just a different path.

I dont know python but if my idea is accepted and if you can give me some pointers where to begin (where to look for that function) then I can try to create a pull request.

Thank you.

**Comment by ilyam8** [comment]
> This does not seem to be true. Because if I see default python.d.conf, there are lines like:


It is true.

https://github.com/netdata/netdata/blob/99f442ce629f9ee6fd3145db62e2fe4c48e36106/collectors/python.d.plugin/python.d.plugin.in#L349-L350

https://github.com/netdata/netdata/blob/99f442ce629f9ee6fd3145db62e2fe4c48e36106/collectors/python.d.plugin/python.d.plugin.in#L530-L532

to get disabled by default module running it should be explicitly enabled

```
module_name: yes
```

___

> Also Configuration manager (#6432) does not seem to be related to my question. It looks like a frontend to config but it will not solve my problem unless backend is changed to read an override file.

Actually it is. Currently every external module is repsonsible for reading/processing configurations. If we want to add some feature to it we need to change reading config code for every plugin. The idea is to move this to CM - a plugin will become a consumer.

___

> Step 1) Read /etc/netdata/python.d.conf if exists, else read /usr/lib/netdata/conf.d/python.d.conf
Step 2) Read /etc/netdata/conf.local/python.d.conf if exists (which will override settings of step 1)

This is one use case and it is kind of make sense for `python.d.conf`, but current behavior is better for `module_name.conf` - you do want to rewrite stock jobs, not  add your own.

Current behaviour is not specific to `python.d.plugin`, as i said all parts do same - other plugins, health, etc.

**Comment by ilyam8** [comment]
I agree that we need something more complex - including configs, overriding configs. The idea is to handle all this in one place - CM, not in every plugin.

**Comment by ilyam8** [comment]
Back to your concern

> say a buggy plugin is disabled or a new plugin is replaced by old one and old one is disabled by default

- If there is a bug - we fix it.
- If we want to replace module we disable it in python.d.plugin, see `obsolete`

https://github.com/netdata/netdata/blob/99f442ce629f9ee6fd3145db62e2fe4c48e36106/collectors/python.d.plugin/python.d.plugin.in#L128-L144
- if we decide to disable it by default, we disable it in the source code (this feature was added to solve exactly the problem you are saying)

**Comment by amishmm** [comment]
@ilyam8 
Thank you so much for detailed answer.

However I still don't get it. How do I solve my problem.

How do I disable squid module? Without copying whole python.d.conf to /etc/netdata?

Because I do not want keep diff-merging stock and user config files everytime I update netdata. i.e. everytime stock python.d.conf is changed, I do not want to keep checking if /etc/netdata/python.d.conf is exactly same except `squid: no`

> This is one use case and it is kind of make sense for python.d.conf, but current behavior is better for module_name.conf - you do want to rewrite stock jobs, not add your own.

I did not get what you mean. But do you mean to say that if I place squid.conf file somewhere (I guess /etc/netdata/python.d/squid.conf) and set `disable: true` inside it, then it will do what I want?

**Comment by ilyam8** [comment]
> Because I do not want keep diff-merging stock and user config files everytime I update netdata. 

You dont need it, just disable `squid` in user config.

> https://docs.netdata.cloud/docs/configuration-guide/

- cd to `/etc/netdata` (dir depends on your install, if you install it in `/opt` it is `/opt/netdata/etc/netdata`)
- `./edit-config python.d.conf` (as `root` user)
- modify it, restart netdata

**Comment by ilyam8** [comment]
> I find (suspect) that netdata squid plugin is creating some issue with my squid setup.

what problems btw?

i dont see any restrictions in the docs

> https://wiki.squid-cache.org/Features/CacheManager


probably your squid version has some bugs

**Comment by ilyam8** [comment]
ok, 

> So tomorrow if an important change is made to default /usr/lib/netdata/conf.d/python.d.conf, (say a buggy plugin is disabled or a new plugin is replaced by old one and old one is disabled by default) 

we keep that in mind, no worries, you dont need to chek diff between user and stock after every upgrade

https://github.com/netdata/netdata/issues/7736#issuecomment-574573880

**Comment by amishmm** [comment]
> ./edit-config python.d.conf (as root user)

Ok that is what I have done currently. Thank you.

Although it does not resolve my issue.

Because for example tomorrow if developers (i.e. you guys) decide that current default `gc_interval: 300` is not optimal and change it to say `gc_interval: 600`.

So you will change the value in file /usr/lib/netdata/conf.d/python.d.conf

But my user file in /etc/netdata will still have `gc_interval: 300` and it will not use optimal value until I realize this and change in my python.d.conf file too.

Similarly tomorrow if netdata has thousands of modules and developers decide that ok we disable all modules by default and only enable top 100 most used modules. So you change `/usr/lib/netdata/conf.d/python.d.conf` to
```
enabled: no
module1: yes
module2: yes
...
module100: yes
```

But my local `/etc/netdata/python.d.conf` file will still have `enabled: yes` and it will enable all thousands of modules.

So point is I will have to keep checking and diff-merging to make sure that `/etc/netdata/python.d.conf` identical to `/usr/lib/netdata/conf.d/python.d.conf` (except my customization)

**None-the-less, thank you again for your patience and detailed answers.** I do hope one day override feature will be implemented :)

**Comment by ilyam8** [comment]
> Similarly tomorrow if netdata has thousands of modules and developers decide that ok we disable all modules by default and only enable top 100 most used modules.

As i said if we disable it by default we do it other way

https://github.com/netdata/netdata/blob/006e1ea38f538fedfd22f38059b02111cd3f3f02/collectors/python.d.plugin/adaptec_raid/adaptec_raid.chart.py#L15

> But my local /etc/netdata/python.d.conf file will still have enabled: yes

stock config has commented out lines

```
# module_name: yes
```

I understand what you are talking about, but all these `thousands of modules` and `ifs` are edge cases and we dont not have such problems atm.

Official way to chane stock is to copy stock to user dir and make changes. It works. It is very simple approach. It has pros and cons. We aware of it. It is very likely will be changed in the future, but it not that easy as it may looks.

**Comment by amishmm** [comment]
> > I find (suspect) that netdata squid plugin is creating some issue with my squid setup.
> 
> what problems btw?
> 
> i dont see any restrictions in the docs
> 
> > https://wiki.squid-cache.org/Features/CacheManager
> 
> probably your squid version has some bugs

I am using Arch Linux (and hence latest squid 4.9-1). And my squid.conf is also unchanged from 2-3 years and working fine. It acts as NAT proxy.

I started using netdata from about a week (on same machine as squid). From same day people started complaining that they are not able to browse some sites. (I have same setup in 3-4 offices and every office had same complaint). Restarting squid would solve the problem. (Happened atleast once everyday)

So for testing I disabled squid module of netdata. And complaints vanished. Have not received the complaint from 3 days now.

So it appears that netdata collecting squid statistics every second is creating some issue. May be squid is running out of resources? Not sure. Since they are production systems, I have not gone in detailed research.

But overall after disabling squid module of netdata, things are normal.

**Comment by amishmm** [comment]
> Official way to chane stock is to copy stock to user dir and make changes. It works. It is very simple approach. It has pros and cons. We aware of it. It is very likely will be changed in the future, but it not that easy as it may looks.

No problem. I understand. You may close the issue if you do not wish to keep track of it.

Thank you.

**Comment by ilyam8** [comment]
> From same day people started complaining that they are not able to browse some sites

Doesnt sound good. It would be nice to understand why it is a problem to get counters metrics every second.

> The cache manager is a component of Squid which provides management controls and reports displaying statistics about the squid process as it runs.

> reports displaying statistics

We use it for it 😄 

btw keep in mind we have `sqiudlog` module (rewritten in go)

https://github.com/netdata/go.d.plugin/tree/master/modules/squidlog

to use it you need to [disalbe python version and enable go version](https://github.com/netdata/go.d.plugin#why-disabled-how-to-enable)

**Comment by ilyam8** [comment]
Closing in favor of #6432
