### ISSUE TITLE
ACLK - Complete the access to the authentication endpoint

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#7738]
#### Feature summary

- Retrieve the private key that was stored to the disk during claiming.
- The cloud endpoints have a real certificate that be validated from the system-level trust roots.
- First request is to the new cloud endpoint for the challenge, receiving the challenge in a JSON structure.
- Extract the challenge string and decrypt it using the RSA private key.
- Second request delivers the  challenge to the second endpoint and receives user/password in a JSON structure.
- The username and password are set in the aclk thread.
- Need to establish how to test that the correct username/password are passed to the broker.

#### Expected output

- We need the endpoints from the cloud team.
- Test against either VerneMQ or Mosquitto to establish the correct credentials are passed.

**Comment by amoss** [comment]
The overall backend API is being finalized at the moment, but the details of the authentication endpoints are in  api/spec/openapi.yaml in the cloud-backed repo. I've reviewed it and it looks correct and usable for us.

**Comment by amoss** [comment]
The grooming session to finalize the details of how we do this (the lifetime of the session key and its relationship to the challenge-response) is on Friday so this task cannot be performed in this sprint. Removing milestone so that we can put it in the next sprint.

**Comment by amoss** [comment]
This has changed again (it was redefined at the weekend) but the definition should now be stable so that we can implement this. Removing the estimate as it was not agreed by the team.

**Comment by amoss** [comment]
I'm confused about why this is in the v1.20-Sprint4 milestone at all as I didn't think we were doing it in the last sprint and the grooming mentioned in the comment two weeks ago effectively finished over the weekend? Also we've just estimate it for the next sprint?
