### ISSUE TITLE
[SPIKE] Integrate libmosquitto / libwebsockets event loops to support wss

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#7739]
Investigation on integrating the libwebsockets into libmosquitto and coordinate the two event
loops. 

- Agent calls a mosquitto function
  - The mosquitto's library event loop builds the necessary mqtt packets
     - The libwebsockets event loop is called to encapsulate the mqtt packet into a websockets packet
     - Response is received by libwebsockets,  unpacked and passed to the libmosquitto mqtt decoding functions. 

This will add libwebsockets as an additional dependancy  to the agent

**Comment by underhood** [comment]
Update about status as of now.

### Quick overview of how it works:
Way it works: small patch (~7 lines changed) to libmosquitto allowing us (netdata) to be called in place of system socket read and write calls. Websocket loop is used with libmosquitto loop mostly avoided.

### What works:
-> MQTT over WSS (yes with TLS) to Mosquitto server
-> MQTT over WSS (secure) to VerneMQ

### Stability:
Currently tested with maximum of 200 000 messages between broker and netdata (with SSL over websocket (wss)) and works stable but not as effective as it can be yet.

### Problems (what I will continue working on):
- Performance (usable but not ideal) - but this just needs work. I already know what needs to be done to make it more effective and quicker.
- Code improvements -> clear out some quick and dirty parts and do it properly

**Comment by stelfrag** [comment]
Excellent work @underhood!! 😀

**Comment by underhood** [comment]
The result of SPIKE is code in underhood/netdata mqtt_lws branch and patch for libmosquitto in underhood/mosquitto hook branch
