### ISSUE TITLE
ACLK - Packaging / installation of the agent with libmosquitto statically linked

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#7740]
In order to deploy the results of #7739 into our production code, all available methods of building / installing Netdata must be updated to:

* Pull in the latest version of the forked library (netdata/mosquitto).
* The fork needs to be updated to fix the cahnges that allow the static build of the library and any changes made during the spike.
* The autotools build needs to be updated.

# Expected result

* Instructions for pulling the fork / building the library.
* Necessary changes to autotools / CMake.

Anything else that is required to support the SRE team in #7906.

**Comment by underhood** [comment]
work on this is in `underhood/netdata` branch `aclk_agent_7740` but #7739 has to be merged first for PR to be created

**Comment by underhood** [comment]
To document the plan in GitHub. This issue should:
- if environment var `ACLK=yes` when `autoreconf -ivf` is run *(ACLK env var is the master ACLK disable flag until it is ready to be released)*
- then configure should have 3 options:
    1. default `detect` - no param given: configure will check if both `libmosquitto.a (custom static lib)` and `-lwebsockets (shared lib)` are present and in case yes will build ACLK. Otherwise just show warning and build without ACLK
    1. `--enable-aclk` - this will signify that we want ACLK and therefore configure will fail if `libmosquitto.a (custom static lib)` or `-lwebsockets (shared lib)` ( is not found )
    1. `--disable-aclk` - no ACLK build

The SRE team will then update the installer script to download `libmosquitto` fork and build it (make in `mosquitto/lib`) and call the `./configure` in way it was discussed.

**Comment by amoss** [comment]
Why do we need to pass an environmental variable into `autoreconf` ? I think that configure should have both options described (and the default auto-detect behaviour) in all configurations. Is there a specific problem created by doing this?

**Comment by underhood** [comment]
Hi this comes from ACLK 1 from @stelfrag and the idea is that we do not even try to compile or do anything if ACLK!=yes to be able to merge code step by step while it is not yet exactly production ready.

**Comment by amoss** [comment]
> Hi this comes from ACLK 1 from @stelfrag and the idea is that we do not even try to compile or do anything if ACLK!=yes to be able to merge code step by step while it is not yet exactly production ready.

There is a reason for gating the code that will be executed behind a feature flag, but the same reasoning does not apply to linking in the library if it is available. I don't think we need this here.

**Comment by stelfrag** [comment]
> > Hi this comes from ACLK 1 from @stelfrag and the idea is that we do not even try to compile or do anything if ACLK!=yes to be able to merge code step by step while it is not yet exactly production ready.
> 
> There is a reason for gating the code that will be executed behind a feature flag, but the same reasoning does not apply to linking in the library if it is available. I don't think we need this here.

Everybody is right :smile: 

The feature flag (in the code that got merged) disabled everything because a few days go we didn't have the library available during installation.

Actually  it would compile the code (with the MQTT related functions as stubs). Based on some review comments I changed it to skip the aclk/ directory entirely.

As we are now getting to the point of having the library available we can fine tune the feature flag to have the library embedded in the code (and of course avoid the environment variable and add a proper installer option)
