### ISSUE TITLE
ACKL - Docker file replacement to build and test and new functionality

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#7741]
New docker file to build and test the ACLK to cloud functionality

- Refresh the agent code from the repository
  - Includes the forked source code of the mosquitto library
- Build the libmosquitto static library (under netdata/mosquitto)
- Build the agent so as it statically links the libmosquitto.a library
- Configure the agent to be in a claimed state
- Configure the [agent_cloud_link] section in netdata.conf

**Comment by amoss** [comment]
Closed in favor of #7899.
