### ISSUE TITLE
ACLK - Create the alarm_log handler response

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#7745]
- This will create the response for the alarms that will be forwarded to the alarms
topic. 
- The information needed is returned by /api/v1/alarms_log

**Comment by thiagoftsm** [comment]
> This will create the response for the alarms request that will be forwarded to the alarms
topic.

When you said "response for the alarms", I understood that cloud will do a request for the agents, but it is possible that a thread will do the request. Which source will do the request?

**Comment by stelfrag** [comment]
> > This will create the response for the alarms request that will be forwarded to the alarms
> > topic.
> 
> When you said "response for the alarms", I understood that cloud will do a request for the agents, but it is possible that a thread will do the request. Which source will do the request?

Good catch! 

This will be a push operation as the alarms will be triggered on the agent and submitted to the cloud. So there is no "request" -- you are correct. I removed the **request** word from the initial description

**Comment by thiagoftsm** [comment]
Thank you very much for the answer! :)
