### ISSUE TITLE
Add the new meta-data from system-info.sh to the web API and ACLK.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7751]
# Feature idea summary

The `system-info.sh` script will be updated in #7731 to add the following new information

*    Number of cores
*    Nominal frequency (not the current frequency)
*    Amount of RAM
*    Sum of available capacity on disks

The format of these new environment variables will be defined. The data needs to be read into `main.c` where the script is called, stored in an appropriate place and then included in the `/api/v1/info` response as new fields, and in the `info` metadata message on the ACLK. For this task only the web API handler needs to be updated - the ACLK functionality calls that handler.

##### Expected behavior

We should be able to see the new information in `/api/v1/info` queries on a range of systems that includes different processor architectures (ARM, AMD, Intel) and different types of netdata installation (bare-metal, VM, container).

**Comment by thiagoftsm** [comment]
>     * Number of cores
>     * Nominal frequency (not the current frequency)
>     * Amount of RAM
>     * Sum of available capacity on disks

Hi @Ferroin ,

Please, could you change the `daemon/system-info.sh` to bring the `Sum of available capacity on disks`?

Thank you!
