### ISSUE TITLE
health_alarm_notify.conf sends non critical errors the channel defined for critical errors

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7756]
##### Question summary
in our `health_alarm_notify.conf` we have defined both slack and rocket chat to receive the critical alarms, but sometimes we get warning alarms on these channels:
Rocket chat:
![Screenshot from 2020-01-16 03-06-24](https://user-images.githubusercontent.com/7656049/72480779-b7f15c00-380d-11ea-979b-04d9875283e4.png)
Slack:
![Screenshot from 2020-01-16 03-11-00](https://user-images.githubusercontent.com/7656049/72480876-0e5e9a80-380e-11ea-806e-571200e1d2f9.png)
But in the configuration file, we have defined to send only `critical` alerts:
```
###############################################################################
# Rocket.chat
SEND_ROCKETCHAT="YES"
ROCKETCHAT_WEBHOOK_URL="https://chat.x.y/hooks/TOKEN"
DEFAULT_RECIPIENT_ROCKETCHAT="sre-alerts|critical"

###############################################################################
# Slack
SEND_SLACK="YES"
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/TOKEN"
DEFAULT_RECIPIENT_SLACK="grafana_alerts|critical"
role_recipients_rocketchat[sysadmin]="${DEFAULT_RECIPIENT_ROCKETCHAT}"
role_recipients_rocketchat[domainadmin]="${DEFAULT_RECIPIENT_ROCKETCHAT}"
role_recipients_rocketchat[dba]="${DEFAULT_RECIPIENT_ROCKETCHAT}"
role_recipients_rocketchat[webmaster]="${DEFAULT_RECIPIENT_ROCKETCHAT}"
role_recipients_rocketchat[proxyadmin]="${DEFAULT_RECIPIENT_ROCKETCHAT}"
role_recipients_rocketchat[sitemgr]="${DEFAULT_RECIPIENT_ROCKETCHAT}"
##################################################################
role_recipients_slack[sysadmin]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[domainadmin]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[dba]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[webmaster]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[proxyadmin]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[sitemgr]="${DEFAULT_RECIPIENT_SLACK}"
```

##### OS / Environment
Ubuntu 18.04
netdata  1.19
##### Component Name
alert
##### Expected results
receive only critical alerts

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

What is the current `bash` version that you are using?

Best regards!

**Comment by yasharne** [comment]
Hi @thiagoftsm here it is:
`GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)`

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

Thank you for all information, I worked today on this doubt that you had and I could recreate the problem. Firstly thank you very much to detect this bug for us, during my triage I detected that Netdata has this error for role `root`, but it is possible it was creating in other cases, so I created the PR #7769 that brings a FIX for this.

Best regards!
