### ISSUE TITLE
netdata badges units

### ISSUE THREAD

**Issue by arabiran** [netdata/netdata#7758]
I Want to use badges to monitor my server but I don't know how to change to show small number I mean for example convert to GB my memory and show in badges ? And also how to fix height and width my badges I also using embed mod.

**Comment by thiagoftsm** [comment]
Hi @arabiran ,

Case you do a normal request like `https://localhost:19999/api/v1/badge.svg?chart=system.ram&dimension=free`, netdata will return the exact value of the chart, but it is possible to change the value using two additional variables that are `multiply` and `divide`, for example, we can change the previous request to `https://localhost:19999/api/v1/badge.svg?chart=system.ram&dimension=free&divide=1024` the final result will be divided to 1024 before to be displayed, for you reach your goal it will also be necessary to change the `units` variable like this `https://localhost:19999/api/v1/badge.svg?chart=system.ram&dimension=free&divide=1000&units=G`, for more details about badge you can read our documentation https://registry.my-netdata.io/swagger/#/default/get_badge_svg.

Best regards!

**Comment by arabiran** [comment]
Thank you @thiagoftsm 
The best answer to question One
But any advice for question two (how to fix height and width my badges)

**Comment by thiagoftsm** [comment]
> Thank you @thiagoftsm
> The best answer to question One
> But any advice for question two (how to fix height and width my badges)

You are welcome @arabiran !
I imagined that our documentation was saying something about the options, but I notice now that it does not have, so we will need to fix this, but to avoid create a delay for you, I would like to say that it is possible to change width using the variables `fixed_width_lbl` and `fixed_width_val`, for example, the latest request that I gave to you can be changed for `https://localhost:19999/api/v1/badge.svg?chart=system.ram&dimension=free&divide=1000&units=G&fixed_width_lbl=100&fixed_width_val=100`. About the `height`, we do not have yet any possibility to do changes on it, case the `width` variables are not enough, please, create another issue for `feature request`, so we can plan to bring it in a near future.

Best regards!

**Comment by arabiran** [comment]
You are right 
i did mistake about height .
I chaged to <embed src="http://localhost:19999/api/v1/badge.svg?chart=mysql_local.table_locks&options=abs&dimensions=Table_locks_waited&decimal-digits=-1&after=-120&refresh=auto&units=null&group=max&fixed_width_lbl=450&fixed_width_val=450&label=Lock 5Min&value_color=grey:null|green<25|yellow<45|orange<65|red&label_color=blue "/>

but not working

**Comment by thiagoftsm** [comment]
Thank you to give us the information about your Netdata version, the width is a new feature that was inserted few versions ago, and the version 1.14 is more or less one year old, please, can you update your Netdata for the latest (1.19) and try again?

**Comment by arabiran** [comment]
I can not update online. Is it possible to offline update?

**Comment by thiagoftsm** [comment]
> I can not update online. Is it possible to offline update?

Yes, it is possible, this was also brought recently, you can see the step-by-step necessary to do offline installation in this link https://docs.netdata.cloud/packaging/installer/#offline-installations .

**Comment by arabiran** [comment]
thank you @thiagoftsm
