### ISSUE TITLE
slow performance observed on calling /api/v1/alarms

### ISSUE THREAD

**Issue by HolgerHees** [netdata/netdata#7759]
Hello,

I observed a strange behavior when I'm calling /api/v1/alarms.

If I call /api/v1/alarms every 5 seconds (or more) the answer tooks ~700 to 800ms but if I call it every 4.5 seconds (or less) the answer tooks 45 ms.

I'm using version v1.18.1

I'm already checked the config documentation for any interval setting around 5 seconds but I have not find anything related to that.

**Comment by stelfrag** [comment]
Hi @HolgerHees 

- How do you measure the answer delay so we can try to reproduce (browser? command line?)
- Is there any other browser accessing the Netdata dashboard at the time?
- Is the server a master?

**Comment by ilyam8** [comment]
@HolgerHees 

Just to make it clear.

- every 5 seconds - 700-800ms
- every 4.5 seconds - 45ms

is this correct?

**Comment by HolgerHees** [comment]
I call it from my webpage in this way.

```
function loadAlerts()
{
  var id = Math.round( Date.now() / 1000 );
  var xhr = new XMLHttpRequest();
  xhr.open("GET", "/api/v1/alarms?active&_=" + id);
  xhr.withCredentials = true;
  xhr.onreadystatechange = function() {
    if (this.readyState != 4) return;
    window.setTimeout(loadAlerts,4500);
  }
  xhr.send();
}
loadAlerts();
```

If I call it with 4500ms I get response times like

![image](https://user-images.githubusercontent.com/5681988/72802934-263e8000-3c4d-11ea-8a96-57492510a737.png)

But if I change it to 5000ms I get

![image](https://user-images.githubusercontent.com/5681988/72803028-5ede5980-3c4d-11ea-88fb-43ef1c7b3c15.png)

netdata is running as a master and no other client is requesting it.

**Comment by HolgerHees** [comment]
I created a small example with an almost empty HTML page to avoid any sideeffect from my original html page

```
<html>
<head>
<script>
function loadAlerts()
{
  var id = Math.round( Date.now() / 1000 );
  var xhr = new XMLHttpRequest();
  xhr.open("GET", "//netdata.smartmarvin.de/api/v1/alarms?active&_=" + id);
  xhr.withCredentials = true;
  xhr.onreadystatechange = function() {
    if (this.readyState != 4) return;
    window.setTimeout(loadAlerts,4500);
  }
  xhr.send();
}
loadAlerts(); 
</script>
</head>
<body>
loaded
</body>
</html>

```

changing `window.setTimeout(loadAlerts,4500);` to `window.setTimeout(loadAlerts,5000);`  is slowing it down from ~40ms to ~700ms

I tested it also in firefox and chrome to confirm this is not a browser related issues.

**Comment by jacekkolasa** [comment]
Interesting issue, i haven't been able to reproduce it, testing with timeouts from 4000 to 6000 shows no difference.

@HolgerHees can you confirm that this long waiting time happens during `Waiting (TTFB)`? Like in below screenshot from Chrome:

<img src="https://user-images.githubusercontent.com/5786722/72803955-a36af480-3c4f-11ea-9e92-135b2ac33224.png" width="300">

**Comment by ilyam8** [comment]
Do you access netdata direcly or via some proxy? Could you try to access netdata directly and (if it is possible) from the server on which master instance is installed

**Comment by HolgerHees** [comment]
checking the timings was the right hint.

looks like the browser is still using a already established https connection.

![image](https://user-images.githubusercontent.com/5681988/72806256-188cf880-3c55-11ea-843e-cabe283863d5.png)

![image](https://user-images.githubusercontent.com/5681988/72806296-2f334f80-3c55-11ea-9d28-9c716849eeb4.png)

both are using a https connection. But the first one (4500ms) seams to reuse it and the second one (5000ms) is creating every time again a new connection.

thanks a lot for spending/wasting your time to my problem.

**Comment by HolgerHees** [comment]
![image](https://user-images.githubusercontent.com/5681988/72806555-b7b1f000-3c55-11ea-96fe-ab810a2cb802.png)

this is the default response header from my apache

**Comment by jacekkolasa** [comment]
It's actually very interesting discovery and something it's good to remember, thx @HolgerHees!

**Comment by stelfrag** [comment]
I think this can be closed. Please reopen if needed
