### ISSUE TITLE
mysql user count connection per user

### ISSUE THREAD

**Issue by arabiran** [netdata/netdata#7762]
##### Feature idea summary
Hi
I'm using netdata for MySQL monitoring but I need to know how many connections per MySQL user and did not found in netdata chart

**Comment by ilyam8** [comment]
Hi @arabiran 

Are you still interested in this feature? If yes - how do i get that info?

**Comment by chongwang87** [comment]
https://github.com/netdata/netdata/issues/3620#issue-312822612

**Comment by ilyam8** [comment]
Thanks, @chongwang87. 

@gdelafond @arabiran are you still interested in this request?

**Comment by gdelafond** [comment]
Hello, yes it would be nice to have that to detect abusers or bugs in applications. @ilyam8

**Comment by ilyam8** [comment]
Ok, then closing this issue in favor of #3620
