### ISSUE TITLE
Shared libraries for eBPF collectors

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7771]
##### Feature idea summary
Netdata is bringing eBPF collectors to monitor parts of the Linux Kernel, but we do not want to bring big dependencies for our users. To solve this problem we decided to create a shared library that will be dynamic loaded from the collectors. This shared library will be downloaded during the installation process.

###### Environment

To build our shared library we must have  the following environment:
- A kernel compiled with the following options:
```
CONFIG_KPROBES=y
CONFIG_KPROBES_ON_FTRACE=y
CONFIG_HAVE_KPROBES=y
CONFIG_HAVE_KPROBES_ON_FTRACE=y
CONFIG_KPROBE_EVENTS=y
```
- Libelf headers
- llvm/clang , because GCC cannot compile eBPF codes.
- Kernel headers
- Libbpf ( https://github.com/libbpf/libbpf )

About the last option for the environment, it is necessary to give important information. We are using the latest version of eBPF when the kernel is newest than 4.14.X, but for version before 1.15, we changed the libbpf to also give support for these kernels, so we will have 2 libbpf versions been compiled depending of the kernel.

In theory we do not need to compile the codes for all kernel versions, I have worked only with `long term` kernels, and when a distribution decides to work with a different version, I always used the immediate `long term` before the version running on the distribution, unless there is a big change for that specific version, that will set another kernel to compile.

###### Distribution

About the Linux distribution, I am developing using Slackware current, but I also could create without big effort the environment on Fedora and Ubuntu. 

###### Test
The whole structure to build the shared library also has codes used to test the eBPF programs. To run these tests, it is necessary to mount the following file systems:

```
mount -t debugfs nodev /sys/kernel/debug
mount -t tracefs nodev /sys/kernel/tracing
```

##### Expected behavior
We expect to have conditions to change `netdata-installer.sh` and other scripts to do download of the shared libraries and eBPF programs that will be used with Netdata.

**Comment by prologic** [comment]
Removing the "Needs Triage" label as I'm fairly confident I understand what needs to be done here. @Ferroin I'd like to get on to this next after we've mostly happy (_doesn't have to be perfect_) with the binary packaging / multiarch stuff we're currently doing.

**Comment by Ferroin** [comment]
> Removing the "Needs Triage" label as I'm fairly confident I understand what needs to be done here. @Ferroin I'd like to get on to this next after we've mostly happy (_doesn't have to be perfect_) with the binary packaging / multiarch stuff we're currently doing.

Fine by me. When this gets to actual binary packaging though, we need to be building the library as part of the packaging process (there is _ZERO_ reason for us not to, we'll just add the requisite dependencies to the package builders and the build process itself).

**Comment by thiagoftsm** [comment]
An additional information, for kernels 5.4.x, some eBPF codes are compiled  only when we comment the following line

```
#define CONFIG_CC_HAS_ASM_INLINE 1
```

inside the file:

`/lib/modules/5.4.x/build/include/generated/autoconf.h`

**Comment by Ferroin** [comment]
@prologic Per discussion with @cakrit in the core team sync today, this is being bumped to high priority to be ready for the next release for at least the `kickstart-static64.sh` builds. You seem to have a better idea what needs to be done here than I do, so I'd appreciate if you could take this over (I should be fine handling the packaging stuff solo for the time being).

**Comment by prologic** [comment]
> @prologic Per discussion with @cakrit in the core team sync today, this is being bumped to high priority to be ready for the next release for at least the `kickstart-static64.sh` builds. You seem to have a better idea what needs to be done here than I do, so I'd appreciate if you could take this over (I should be fine handling the packaging stuff solo for the time being).

I thought as much from my Slack discussion with Timo last night :)

**Comment by prologic** [comment]
- netdata/kernel-collector#4
- netdata/kernel-collector#5

**Comment by thiagoftsm** [comment]
@prologic I think we can close this one, do you agree?

**Comment by prologic** [comment]
i agree :) I think it is done right? :)
