### ISSUE TITLE
How to Monitor a Sonicwall NSA

### ISSUE THREAD

**Issue by simplesupreme** [netdata/netdata#7774]
How would I monitor performance of a sonicwall nsa 2650 device using netdata?

**Comment by ilyam8** [comment]
Hi @simplesupreme 

Since it is a netwrok device you can use `snmp` collector

https://docs.netdata.cloud/collectors/node.d.plugin/snmp/#snmp-data-collector

Keep in mind it is very basic and eay to configure, i would suggest to try [`librenms`](https://www.librenms.org/).

**Comment by ilyam8** [comment]
Probably this will be helpful

https://github.com/netdata/netdata/issues/7542

**Comment by simplesupreme** [comment]
Thanks ilyam8! I've been on a bit of a hiatus. What do you think of cloudviewnms?

**Comment by ilyam8** [comment]
I have no expirience with `cloudviewnms`, but it reminds me of [`snmpc`](https://www.castlerock.com/).

But if you want to monitor network device(s) - router, switch or firewall - i would recomment `observium` or `librenms`, both are great tools.
