### ISSUE TITLE
Support SRE deployment of eBPF libraries.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7781]
##### Feature idea summary
Placeholder: @thiagoftsm please fill out as discussed.

##### Expected behavior
Deployment of new library via the netdata installer.

**Comment by amoss** [comment]
Duplicate - closing.

**Comment by thiagoftsm** [comment]
After the stand up I am reopening the issue, this issue has a relationship with #7771 , the core team developed all the necessary code and conditions to compile in different versions, now we need to give the code and conditions for SRE-team move in front with the rest.

**Comment by ilyam8** [comment]
One note: it would be nice to not download these libraries on every update, see https://github.com/netdata/netdata/issues/7799
