### ISSUE TITLE
Custom Dashboard Pages - Ability to 'Refresh Always'

### ISSUE THREAD

**Issue by TSKimball** [netdata/netdata#7785]
I was unable to find this in the documentation, after several lookthroughs of it.

##### Feature idea summary
A 'custom dashboard' html file should have the ability to refresh charts with the same options as the default chart file.  In our case, similar to the settings' entries "refresh charts=always" and "refresh policy=sequential."  This is required in order to create a single-pane URL that can live alongside other monitoring tools (web, java etc) that are next to the netdata's base screens.

##### Expected behavior
A custom chart/dash URL should have the same update ability as a default dashboard when no longer in focus.  Perhaps by an argument in the <script /> clause.

**Comment by ilyam8** [comment]
> A custom chart/dash URL should have the same update ability as a default dashboard when no longer in focus.

there is an option to enable `update when not in focus` feature

```java
<script>
NETDATA.options.current.stop_updates_when_focus_is_lost = true;
</script>
```

**Comment by jacekkolasa** [comment]
exactly, please remember to add it after including dashboard.js, here's an example: https://github.com/netdata/netdata/blob/master/web/gui/tv.html#L74
