### ISSUE TITLE
Cannot access the web interface from another/remote machine

### ISSUE THREAD

**Issue by pree-t1** [netdata/netdata#7786]
Environment:
GCP instance with Ubuntu 18.04

Ran the below command to install Netdata:
`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

It seemed to install successfully, however, when I try to remotely access it on another machine using the below URL:
`http://<public ip of the machine running netdata>:19999/`

It shows below error:

`The site can't be reached.
ERR_CONNECTION_TIMED_OUT`

I checked firewall and it is disabled:
`$ sudo ufw status`
`Status: inactive`

I also added the below statement in both `[web]` and `[global]` sections in `/etc/netdata/netdata.conf` followed by service restart:
`bind to = 0.0.0.0`
`sudo systemctl restart netdata`

What do I need to change in order to access the Netdata web interface remotely?

**Comment by thiagoftsm** [comment]
Hi @pree-t1 ,

To be sure that everything is correct with the socket, please, could you check the output of the `netstat`  command and compare with my output?

```
bash-5.0# netstat -avntp| grep 19999
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN      6669/netdata        
tcp6       0      0 :::19999                :::*                    LISTEN      6669/netdata
```

It is expected you have something like this.
Another doubt, when you run locally the following command:

```
curl --o info.csv http://localhost:19999/api/v1/info
```

Does Netdata delivers a file to you?

Finally, it is expected that the `curl` reques will store information inside your `access.log`, is this happening?

Best regards!

**Comment by pree-t1** [comment]
Here are the outputs:

`$ netstat -avntp| grep 19999`
<img width="590" alt="Screen Shot 2020-01-18 at 7 52 16 AM" src="https://user-images.githubusercontent.com/58445482/72666472-7b696000-39c7-11ea-8ed6-0d000a8ec9f5.png">


`$ sudo netstat -avntp| grep 19999`
<img width="663" alt="Screen Shot 2020-01-18 at 7 53 02 AM" src="https://user-images.githubusercontent.com/58445482/72666491-98059800-39c7-11ea-8938-a53fc883305a.png">

`$ curl -o info.csv http://localhost:19999/api/v1/info`
<img width="569" alt="Screen Shot 2020-01-18 at 7 51 08 AM" src="https://user-images.githubusercontent.com/58445482/72666462-61c81880-39c7-11ea-9a73-0896cd3a7aa9.png">


Is there anything obvious from these results which might be causing this issue?

**Comment by thiagoftsm** [comment]
No, the results are showing that everything is correct with Netdata, so we will need to return to the firewall. 
Firstly I apologize, I never worked with `ufw` and I do not work with 'systemd`, so I will give more commands for we check the firewall rules, please, run the following commands:
```
nft list ruleset
iptables -L
iptables -L -t nat
```

Case we do not have any firewall rule set in your firewall, we will have empty outputs or policies defined as `ACCEPT`.

Best regards!

**Comment by pree-t1** [comment]
Here are the results:

`$ nft list ruleset`
No output.

`$ sudo iptables -L`
<img width="640" alt="Screen Shot 2020-01-18 at 2 19 24 PM" src="https://user-images.githubusercontent.com/58445482/72671342-9060e600-39fd-11ea-8af7-63b2987e278c.png">

`$ sudo iptables -L -t nat`
<img width="651" alt="Screen Shot 2020-01-18 at 2 20 24 PM" src="https://user-images.githubusercontent.com/58445482/72671362-ce5e0a00-39fd-11ea-9151-7cf6e3179228.png">

Looks alright to me. What do you think?

**Comment by thiagoftsm** [comment]
These rules are showing that you have a firewall enabled in your computer, as I supposed. It is possible to observe that the `FORWARD` chain has a `DROP` policy that would affect only packages moving between interfaces, but the rules that we see inside this chain say us that the traffic is not blocked.
Finally I can see that there is an INPUT rule for Netdata, also I can see that there is not rules with conntrack module. I will do more few questions for you:

1 - Can you access the Netdata from the internal network?
2 - Are you using other software like `fail2ban` to restrict access to the computer?
3 - Is this machine direct connected  to the internet? Or is there a firewall in front it?
4 - Case the computer is accessing the internet directly, can you shutdown completely the  firewall and try to access Netdata again? Please, do not forget to set the FORWARD policy to ACCEPT.
5 - Whether after to shutdown the firewall rules you could access normally Netdata, this means that it will be necessary to do more changes inside your firewall.

**Comment by prologic** [comment]
Some questions I'm also curious about:

- Are you able to share with us the public ip at all?
- Are you able to ping the public ip from the same client machine you are trying to access the NetData Web interface from?

**Comment by pree-t1** [comment]
This is a GCP instance as I mentioned in my original post. There is a public IP associated with it and I can ping on it from another machine (where I am trying to access Netdata web interface as well). It looks like I might need to create a firewall to allow Netdata traffic, since I am not sure if there is a clean way to turn off the firewall completely. Also, I am not using any software like `fail2ban` to restrict any access.

**Comment by prologic** [comment]
I just had a thought... Normally (_I have no direct experience with GCP at this point yet_) most cloud providers have this notion of a "virtual private cloud" and "security group" -- This is AWS speak. I imagine GCP has similar. In fact [this doc](https://cloud.google.com/vpc/docs/firewalls) has an overview of GCP Firewall configuration that you should probably be applying to your GCP instances or group of instances if you put them in the same VPC. It is very likely there is a default security group too which explains why you can ping the instance, maybe ssh into it but nothing else (_everything else is silently dropped to the floor by the GCP VPC gateways_)

**Comment by prologic** [comment]
@pree-t1 Are you able to modify your VPC / Firewall configuration to allow inbound access to the NetData Web port on `19999`? Once we have this figured out we should probably add a section to our [docs](https://docs.netdata.cloud) :)

**Comment by pree-t1** [comment]
Added a firewall rule:
`Name: <name>`
`Type: Ingress`
`Targets: <name-tag>`
`Filters: 0.0.0.0/0`
`Protocols/ports: 19999`
`Action: allow`
`Priority: 1000`

Also, add the above target tag to the instance's network tags. I was able to get it working with these changes.

**Comment by prologic** [comment]
> Also, add the above target tag to the instance's network tags. I was able to get it working with these changes.

Awesome! We'll see if we can add a section to our docs as appropriate for future NetData users on GCP. Thanks for sharing! And we're glad you got this working :)

**Comment by prologic** [comment]
cc @joelhans Let's figure out how best to add a section to our docs related to running NetData on cloud providers and especially accessing the NetData instances where Network / Firewall modifications are generally required.

**Comment by pree-t1** [comment]
@prologic I noticed you changed tags. Please feel free to close it once documentation is updated. Thanks!

**Comment by prologic** [comment]
Closing in favour of #7854 where we will document this more widely for NetData running in Cloud Providers for at least AWS, Azure, GCP and maybe a few others...
