### ISSUE TITLE
FreeBSD 12-RELEASE: "sed: -I or -i may not be used with stdin" during auto-updater install

### ISSUE THREAD

**Issue by tuklusan** [netdata/netdata#7788]
Installer for FreeBSD 12-RELEASE does not install the updater tool. There seems to be a problematic invocation of sed.

`uname -a`:

```sh
FreeBSD dell-poweredge-2950.sanyalnet.lan 12.0-RELEASE-p10 FreeBSD 12.0-RELEASE-p10 GENERIC  amd64
```

`./netdata-installer.sh --install /opt`:

```sh
...
...
--- Installing (but not enabling) the netdata updater tool --- 
sed: -I or -i may not be used with stdin
 FAILED  Cannot install netdata updater tool. 

 --- Check if we must enable/disable the netdata updater tool --- 
You chose *NOT* to enable auto-update, removing any links to the updater from cron (it may have happened if you are reinstalling)
...
...
```

Otherwise all good.

**Comment by prologic** [comment]
@tuklusan May I please have a copy of your `netdata-installer.log` file if still available?

**Comment by tuklusan** [comment]
> @tuklusan May I please have a copy of your `netdata-installer.log` file if still available?

Looking for it, will of course attach it, in the meanwhile, here's the session logs:

[netdata-install-log1.txt](https://github.com/netdata/netdata/files/4079950/netdata-install-log1.txt)
[netdata-install-log0.txt](https://github.com/netdata/netdata/files/4079951/netdata-install-log0.txt)

**Comment by tuklusan** [comment]
@prologic found it under /root/netdata ...
[netdata-installer.log](https://github.com/netdata/netdata/files/4079957/netdata-installer.log)

**Comment by prologic** [comment]
@tuklusan Unfortunately I was hoping to see something else in the logs that would help me pin point this down :/ -- I'm only 90% sure where this is happening but I'll have to spin up a FreeBSD VM environment to be sure.

**Comment by tuklusan** [comment]
OK, thanks for looking into it. Let me know if I can be of any help. Would you like to ssh to my box into a sudo account? May be easier than having to install a fresh FreeBSD 12 VM. You can reach me directly at supratim at riseup dot net. I took a full disk backup today so there is zero risk.

**Comment by prologic** [comment]
@tuklusan How did you even get NetData to build on your FreeBSD system? I have to admit I'm not too experienced in *BSD (_unless you count macOS!_); I'm running into early failures like:

```sh
Press ENTER to build and install netdata to '/opt/netdata' >
 --- Run autotools to configure the build environment ---
[/root/netdata]# autoreconf -ivf
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal -I build/m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/share/autoconf-2.69/Autom4te/FileUtils.pm line 326.
autoreconf-2.69: failed to run aclocal: No such file or directory
 FAILED
```

This is on FreeBSD 12.1 on amd64 -- Appreciate your help here; if our build tools are broken on FreeBSD (_now_) we'll have to fix that :)

**Comment by prologic** [comment]
Okay I should have realised :) We're using GNU's Automake

```sh
$ pkg install automake
```

**Comment by prologic** [comment]
It really helps to follow our own [docs](https://docs.netdata.cloud/packaging/installer/#freebsd) sometimes 🤣I was copying/pasting your session to try to repro your installation failure and your `pkg instal` line was missing some of our required dependencies :)

**Comment by prologic** [comment]
@tuklusan I have a fix if you'd be so kind as to test/confirm it on your system too?

Here's how:

```sh
root@freebsd:~ # git clone https://github.com/prologic/netdata
Cloning into 'netdata'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 49252 (delta 6), reused 14 (delta 5), pack-reused 49231
Receiving objects: 100% (49252/49252), 34.31 MiB | 6.12 MiB/s, done.
Resolving deltas: 100% (34292/34292), done.
root@freebsd:~ # cd netdata
root@freebsd:~/netdata # git checkout fix_freebsd_installer
Branch 'fix_freebsd_installer' set up to track remote branch 'fix_freebsd_installer' from 'origin'.
Switched to a new branch 'fix_freebsd_installer'
root@freebsd:~/netdata # ./netdata-installer.sh --install /opt

...
```

This works for me on my FreeBSD 12.1 VM:

```sh
 --- Installing (but not enabling) the netdata updater tool ---
Update script is located at /opt/netdata/usr/libexec/netdata/netdata-updater.sh

 --- Check if we must enable/disable the netdata updater tool ---
You chose *NOT* to enable auto-update, removing any links to the updater from cron (it may have happened if you are reinstalling)

Did not find any cron entries to remove

 --- Wrap up environment set up ---
Preparing .environment file
[/root/netdata]# chmod 0644 /opt/netdata/etc/netdata/.environment
 OK

Setting netdata.tarball.checksum to 'new_installation'

 --- We are done! ---

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed and running now!  -'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  enjoy real-time performance and health monitoring...

root@freebsd:~/netdata #
```

And the changes being proposed I've confirmed behave the same on FreeBSD's `sed` and GNU Sed.

**Comment by tuklusan** [comment]
Confirmed; it works for me too! Thank you. Attaching the installer log and the session just in case for reference.
[netdata-installer.log](https://github.com/netdata/netdata/files/4087567/netdata-installer.log)
[session.log](https://github.com/netdata/netdata/files/4087568/session.log)
