### ISSUE TITLE
badge font color

### ISSUE THREAD

**Issue by arabiran** [netdata/netdata#7791]
Hi 
How to change badge font color?

**Comment by thiagoftsm** [comment]
> Hi
> How to change badge font color?

Hello @arabiran ,

I will use the latest example that I gave to you to simplify the understanding,  we can change the colors using two variables `label_color` and `value_color`, this is done given as argument for these variables the color name as you can see in the next example

```
https://localhost:19999/api/v1/badge.svg?chart=system.ram&dimension=free&divide=1000&units=G&fixed_width_lbl=100&fixed_width_val=100&label_color=green&value_color=white
```

For value colors there are more options, that you can consult in our documentation ( https://registry.my-netdata.io/swagger/#/default/get_badge_svg ).

Best regards!

**Comment by arabiran** [comment]
Hello @thiagoftsm 
**label_color   a color to be used for the _background_ of the label** 
Is it true ( Just **Background** ) but I ask about **badge Font Color** like gauge Lable and Other

**Comment by thiagoftsm** [comment]
I was verifying now our source code, and I saw that in this exact moment, we do not have conditions to set the font color as you can see in the link below

https://github.com/netdata/netdata/blob/ff2697e73a52a311a644737ace5c18a57bf15853/web/api/badges/web_buffer_svg.c#L743

but, we define a class `bdge-ttl-width` that can be changed using HTML/CSS. I am converting your doubt to feature request, for we bring this in a near future.

best regards!

**Comment by arabiran** [comment]
Hi @thiagoftsm 
Thanks and I hope will be soon saw
Best regards.

**Comment by thiagoftsm** [comment]
Hi @arabiran ,

@underhood brought the feature to Netdata. Thank you for you suggestion and Thank you @underhood for the amazing work!
