### ISSUE TITLE
CloudLinux cagefs limits

### ISSUE THREAD

**Issue by splaquet** [netdata/netdata#7792]
##### Question summary
I operate several CloudLinux CentOS servers. The problem that I have is that my accounts often hit their memory limits, although there’s really no true threat to the server memory. Almost hundreds of times a day, I receive notices from netdata, warning about memory limits. I was unable to find any other questions from folks having the same type of issue. 

The question I have is if there are any simple methods to disable those memory email warnings, for only those within cageFS system. I’d hate to miss an actual email for a server memory issue. 

The only solution I can think of for now is to disable warning emails.  

##### OS / Environment
CloudLinux CentOS
 
##### Component Name
mem_usage

##### Expected results
Warnings at the server level, not account level

**Comment by ilyam8** [comment]
Hi @splaquet 

> lmost hundreds of times a day, I receive notices from netdata, warning about memory limits.

What notices do you receive from netdata? What alarm is triggered?
