### ISSUE TITLE
Shellcheck changed shell scripts in PR(s)

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#7793]
Instead of running `shellcheck` against the entire codebase; let's just run `shellcheck` against changed shell scripts in PR(s). This way we can incrementally improve the quality of our shell scripts and catch problems early on like in #7770 and #7787 

Supersedes #7789

**Comment by thiagoftsm** [comment]
I agree 100%! We can assume that other scripts inside the project already passed through `shellcheck` and we need to verify only the new changes and files that we are bringing.

**Comment by prologic** [comment]
In the long-run it would be nice to do this across the board. But I'll consider this a small spike to validate the idea (_should work okay_) and see how it goes. In general this is better; but keep the scope small for now until we figure out a good pattern in general. Plan to do this via a separate CI job (_probably via a Github Action_) in parallel to our existing CI jobs.
