### ISSUE TITLE
Netdata doesn't disable metric collection despite the configuration

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7797]
##### Bug report summary
I want to disable IPv6 monitoring on my servers, so here is my `netdata.conf` file:
```
[global]
    memory mode = none
	error log = False 
	debug log = False
	access log = False

[web]
	mode = none

[registry]
    enabled = False
    registry to announce = http://a.b.c.d:19999

[plugin:proc:/proc/net/sockstat6]
	ipv6 TCP sockets = False
	ipv6 UDP sockets = False
	ipv6 UDPLITE sockets = False
	ipv6 RAW sockets = False
	ipv6 FRAG sockets = False

[system.ipv6]
	enabled = False

[ipv6.packets]
	enabled = False

[ipv6.mcast]
	enabled = False

[ipv6.mcastpkts]
	enabled = False

[ipv6.icmp]
	enabled = False

[ipv6.icmprouter]
	enabled = False

[ipv6.icmpneighbor]
	enabled = False

[ipv6.icmpmldv2]
	enabled = False

[ipv6.icmptypes]
	enabled = False

[ipv6.udppackets]
	enabled = False

[ipv6.ect]
	enabled = False

[ipv6.sockstat6_tcp_sockets]
	enabled = False

[ipv6.sockstat6_udp_sockets]
	enabled = False

[ipv6.sockstat6_raw_sockets]
	enabled = False

[ipv6.errors]
	enabled = False

[ipv6.udperrors]
	enabled = False

[ipv6.udperrors]
	enabled = False
```
By the way, I'm streaming the metrics to a master server.
But when I open the dashboard, I still see the IPv6 metrics being collected:
![image](https://user-images.githubusercontent.com/7656049/72707066-cf657780-3b74-11ea-907f-8e28375ebabc.png)

##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)
Linux one-02.compute.x.y.z 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.5 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.5 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
##### Netdata version (ouput of `netdata -V`)
v1.19.0
##### Expected behavior
Not showing IPv6 charts

**Comment by ilyam8** [comment]
hi @yasharne 

it seems you have some problems with user configurations 🤔 (https://github.com/netdata/netdata/issues/7755)

i tested it and it works, i disabled `IPv6 Networking` charts, related configuration part:

```bash
[plugin:proc:/proc/net/sockstat6]
	# ipv6 TCP sockets = auto
	# ipv6 UDP sockets = auto
	# ipv6 UDPLITE sockets = auto
	# ipv6 RAW sockets = auto
	# ipv6 FRAG sockets = auto
	# filename to monitor = /proc/net/sockstat6
	ipv6 TCP sockets = no
	ipv6 UDP sockets = no
	ipv6 UDPLITE sockets = no
	ipv6 RAW sockets = no
	ipv6 FRAG sockets = no

[plugin:proc:/proc/net/snmp6]
	# ipv6 packets = auto
	# ipv6 fragments sent = auto
	# ipv6 fragments assembly = auto
	# ipv6 errors = auto
	# ipv6 UDP packets = auto
	# ipv6 UDP errors = auto
	# ipv6 UDPlite packets = auto
	# ipv6 UDPlite errors = auto
	# bandwidth = auto
	# multicast bandwidth = auto
	# broadcast bandwidth = auto
	# multicast packets = auto
	# icmp = auto
	# icmp redirects = auto
	# icmp errors = auto
	# icmp echos = auto
	# icmp group membership = auto
	# icmp router = auto
	# icmp neighbor = auto
	# icmp mldv2 = auto
	# icmp types = auto
	# ect = auto
	# filename to monitor = /proc/net/snmp6
	ipv6 packets = no
	ipv6 fragments sent = no
	ipv6 fragments assembly = no
	ipv6 errors = no
	ipv6 UDP packets = no
	ipv6 UDP errors = no
	ipv6 UDPlite packets = no
	ipv6 UDPlite errors = no
	bandwidth = no
	multicast bandwidth = no
	broadcast bandwidth = no
	multicast packets = no
	icmp = no
	icmp redirects = no
	icmp errors = no
	icmp echos = no
	icmp group membership = no
	icmp router = no
	icmp neighbor = no
	icmp mldv2 = no
	icmp types = no
	ect = no
```

___

There is no option to disable the whole module of `proc` plugin, workaround it to change `filename to monitor` to something that is not exists

```bash
[plugin:proc:/proc/net/sockstat6]
	# ipv6 TCP sockets = auto
	# ipv6 UDP sockets = auto
	# ipv6 UDPLITE sockets = auto
	# ipv6 RAW sockets = auto
	# ipv6 FRAG sockets = auto
	filename to monitor = /proc/net/sockstat61

[plugin:proc:/proc/net/snmp6]
	# ipv6 packets = auto
	# ipv6 fragments sent = auto
	# ipv6 fragments assembly = auto
	# ipv6 errors = auto
	# ipv6 UDP packets = auto
	# ipv6 UDP errors = auto
	# ipv6 UDPlite packets = auto
	# ipv6 UDPlite errors = auto
	# bandwidth = auto
	# multicast bandwidth = auto
	# broadcast bandwidth = auto
	# multicast packets = auto
	# icmp = auto
	# icmp redirects = auto
	# icmp errors = auto
	# icmp echos = auto
	# icmp group membership = auto
	# icmp router = auto
	# icmp neighbor = auto
	# icmp mldv2 = auto
	# icmp types = auto
	# ect = auto
	filename to monitor = /proc/net/snmp61
```

Result is same - no `IPv6 Networking` section on the dashboard.

**Comment by yasharne** [comment]
I wonder if the configuration is cached somewhere and causes netdata to read the old configuration.

**Comment by ilyam8** [comment]
No, it is not cached.

**Comment by yasharne** [comment]
the weird thing is I'm using ansible to put this setting on the servers and from 14 servers (one gitlab server, 12 MariaDB servers, and the master netdata) gitlab and master netdata has disabled the IPv6 metric collection but other 12 MariaDBs haven't.

**Comment by ilyam8** [comment]
> Netdata doesn't disable metric collection despite the configuration

Well, there is no bug in netdata

if config is in place and it is disabled in the config

https://github.com/netdata/netdata/blob/6ba71e1704ef9fcd9335e1e4e1ad844b00a082fd/collectors/proc.plugin/proc_net_sockstat6.c#L39-L43

the charts wont be created

https://github.com/netdata/netdata/blob/6ba71e1704ef9fcd9335e1e4e1ad844b00a082fd/collectors/proc.plugin/proc_net_sockstat6.c#L114-L144

___

so check your ansible stuff

**Comment by yasharne** [comment]
after few hours, changes have been applied. I can't find the reason I guess it has something to do with the streaming feature

**Comment by ilyam8** [comment]
> But when I open the dashboard, I still see the IPv6 metrics being collected:


if it is master dashboard then yes, it is expected. You need to restart master to get changes reflected on the master dashboard.

**Comment by ilyam8** [comment]
So if you remove something it is not enough to restart slave(s), master should be restarted too.

**Comment by ilyam8** [comment]
Data collection on slave is disabled tho 😄 @yasharne i am closing the issue, feel free to comment/ask if you need something.
