### ISSUE TITLE
Suggested feature: Disk usage treemap

### ISSUE THREAD

**Issue by astewart-twist** [netdata/netdata#78]
This may be well outside the intended scope of this awesome app, but I've always thought it would be immensely useful to have a web-based version of disk treeview applications like DiskX (http://www.derlien.com/) or DaisyDisk (https://daisydiskapp.com/) for running on servers.

![image](https://cloud.githubusercontent.com/assets/14282772/14154072/8a4ecc30-f66f-11e5-92bc-05ab7e3cccff.png)

Something like Mike Bostock's zoomable treemaps in D3 would be awesome: https://bost.ocks.org/mike/treemap/

**Comment by ktsaou** [comment]
Well, I do believe this is outside of scope.
But let it be here. You never know!

**Comment by ktsaou** [comment]
We will add many more visualization in netdata. The visualization you suggest is nice, but it only shows the current snapshot of the data. netdata would need a visualization that would allow also a view over time.

Anyway, I am closing this.
We will discuss such visualizations later.
