### ISSUE TITLE
API query for applications chart

### ISSUE THREAD

**Issue by snub-fighter** [netdata/netdata#7800]
Im trying to query the netdata API for the cpu applications chart.  Main issue I find is I dont see a list of charts to query against.  Am I supposed to go through html code from default chart page and figure out what it is or is there some list somewhere?
Example : `https://registry.my-netdata.io/api/v1/data?chart=system.cpu `  This doesnt show the applications though but its a start.

![image](https://user-images.githubusercontent.com/5192578/72741044-b69c9800-3b5b-11ea-9e58-8e43b24e4598.png)

**Comment by thiagoftsm** [comment]
Hi @snub-fighter ,

For you get the whole list of charts available and their dimensions, your need to do a call  for `/api/v1/charts`, for example, the previous URL would become `https://registry.my-netdata.io/api/v1/charts`.

Best regards!

**Comment by snub-fighter** [comment]
I think I figured it out.  @thiagoftsm  Thank you! 
 `http://127.0.0.1:19998/api/v1/data?chart=apps.cpu`
