### ISSUE TITLE
Validate custom plugin logic for apps.cpu summarization

### ISSUE THREAD

**Issue by snub-fighter** [netdata/netdata#7801]
Two Questions here!
 1. Would this be fairly accurate to create an external python plugin pulling the following data?
 2. Once the plugin is created how do I query it in a chart assuming the plugin is named 'multigroup_cpu.charts.py'  ?
```
<div data-netdata="multigroup_cpu"
...
...
```
**My method**  

1. Pull Applications CPU data
2. Extract %'s and summarize the application usage into larger groups
3. Pull system.cpu data and use its total value as a percentage of 100% (e.g. 2.5 = 2.5%)
4. Create a d3pie chart using the following data : 

Chart represents 100% CPU Utilization with 3 Groups.
This would provide a similar experience as the temperature easypiechart except it depicts multiple groups.

1. Custom Group A is for specific applications under `apps.cpu`
2. Custom Group B is for all other applications under `apps.cpu`
3. Custom Group C is for 100 - (A+B) to ensure unused CPU utilization is represented in chart.

![image](https://user-images.githubusercontent.com/5192578/72742723-2fe9ba00-3b5f-11ea-84e7-32b290dfe5e8.png)

**Comment by thiagoftsm** [comment]
I think that part of your requests can be achieved doing the configuration of `apps.plugin`, please, take a look in our documentation to confirm my initial impression https://docs.netdata.cloud/collectors/apps.plugin/#appsplugin .

About a python plugin, this will be an external plugin and we also wrote a step by step of how to create one in this link https://docs.netdata.cloud/collectors/python.d.plugin/, but I suggest you firstly to read the overview https://docs.netdata.cloud/collectors/plugins.d/ .

Case this is not enough, please, let me know that I can help you with more details.

Best regards!

**Comment by ilyam8** [comment]
@snub-fighter 

I dont get the question to be honest 😅


`apps_groups.conf` contains groups of processes, you want to calculate cpu usage for specific set of groups from the `apps_groups.conf`?

like

```
sql: mysqld* mariad* postgres* postmaster* oracle_* ora_*
nosql: mongod redis* memcached *couchdb*
```

=> sql+nosql?

**Comment by snub-fighter** [comment]
I want to make a custom group for MY processes and then bundle the
remaining to have a simplistic aggregated view of whats important to me on
a custom dashboard inside a piechart.

In short I can then view the total cpu usage vs my_personal_apps cpu usage
inside a pie chart.

**Comment by ilyam8** [comment]
Yes, you have 2 options
- write your collector and do all processing there. You need create new charts, etc.
- export data to some tsdb and do processing using queries (should be relatively simple). In that way you cant use netdata dasboard.

**Comment by snub-fighter** [comment]
Do u think my method of using the api would be proficient?  Im simply
letting native plugins do most of the work and then i aggregate the data
the way I want and reurn it to netdata.

**Comment by ilyam8** [comment]
i think it is the only way to achieve your goals using netdata only - write a collector that will do whatever processing you need.
