### ISSUE TITLE
Change the streaming protocol to allow forward-compatability.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7804]
##### Description
During the testing of the PR for issue #7488 we discovered that the new division of `system_info` into `HOST_` and `CONTAINER_` labels is incompatible with the design of the streaming protocol. The handshake for a stream connection names the structure fields as parameters in the initial request.

To change this we need to introduce a new version of the streaming protocol that transfers the two sets of labels. Unfortunately we have discovered that the changes in issue #7549 that were meant to allow forward-compatibility in the streaming protocol are not forward-compatible with further changes.

The basic problem is that the protocol message must be one of two exact strings to avoid the connection being aborted and there is no way to put a version number in the strings.

To move forward we need to redesign the streaming protocol handshake so that it is forward-compatible (and also backwards compatible with the recent changes).

#### Summary

Originally the startup message "Hit me baby, one more time..." from master to slave was used as a protocol discriminator. After #7549 it is acting as a version discriminator and hosts will disconnect when they do not recognize the message.

The protocol will be updated to perform agreement of highest compatible version during handshake. For simplicity we will switch to integer protocol versions, using the following scheme:

```
0 - original
1 - host labels
2 - host labels + docker labels
3 - host labels + docker labels + chart labels
```

The advantage of integer numbering over a bitmask scheme is that we can depend on grouping of features after negotiation, which leads to simpler code. We need to handle the three schemes in a backwards compatible way:

```
1. old slave                      -> no "NETDATA_PROTOCOL_VERSION"
2. slave with the patch #7549     -> NETDATA_PROTOCOL_VERSION=1.1
3. new slave                      -> ver=2&...
```

```
A. old master                -> "Hit me baby, one more time..."
B. master with the patch     -> "... with host labels"
C. new master               -> negotiate according to psuedo-code

master_version = 2;
if ('ver=n' was in the url  ) {
  "Hit me with your rhythm stick: %d" % min(n,master_version)
  use_version = n;
} else {
  "Hit me baby, one more time..."
   version = 0;
}
```

Falling back to the lowest version fixes a current incompatibility with systems from before patch #7549. On the client side we can map the response string back to the negotiated version.

**Comment by amoss** [comment]
I've put some temporary code in rrdpush so that we can get issue #7488 finished and unblock other tasks. A better approach (which should be implemented in this task) is to check the `NETDATA_SYSTEM_CONTAINER_DETECTION` value on a stream from an old version, if it is set to "none" or "unknown" then rename the six `NETDATA_SYSTEM_*` variables as `NETDATA_HOST_*` - *otherwise' rename them as `NETDATA_CONTAINER_*`. This will produce the most accurate metadata data when old versions stream to a newer host.

**Comment by thiagoftsm** [comment]
> I've put some temporary code in rrdpush so that we can get issue #7488 finished and unblock other tasks. A better approach (which should be implemented in this task) is to check the `NETDATA_SYSTEM_CONTAINER_DETECTION` value on a stream from an old version, if it is set to "none" or "unknown" then rename the six `NETDATA_SYSTEM_*` variables as `NETDATA_HOST_*` - *otherwise' rename them as `NETDATA_CONTAINER_*`. This will produce the most accurate metadata data when old versions stream to a newer host.

I reviewed the code already, depending of your answer for the missing variables I will approve and we can move in front with this.

**Comment by amoss** [comment]
Yes please approve the other PR. If you are happy with what we need to achieve in this issue then please start.
