### ISSUE TITLE
Error when i trying to install / update netdata ?

### ISSUE THREAD

**Issue by ludochan** [netdata/netdata#7806]
Hello i have this error when i trying to install / update netdata ?

> checking for uv_fs_scandir_next in -luv... no
> configure: error: libuv required but not found. Try installing 'libuv1-dev' or '                                                                                                                                                             libuv-devel'.
>  FAILED
> 
> 
>   ^
>   |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
>   |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
>   +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->
> 
> 
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 

i don't know  what's the cause because i installed

>  libuv

with this method.

> apt install libtool
> wget https://github.com/libuv/libuv/archive/v1.34.0.tar.gz
> tar -zxvf v1.34.0.tar.gz
> cd libuv-1.34.0
> sh autogen.sh
> ./configure
> make
> make check
> make install
> ldconfig -v

i'm on Debian GNU/Linux 8.11 (jessie)
Thanks for your help :)

**Comment by ilyam8** [comment]
@ludochan 

check this discussion
https://github.com/netdata/netdata/issues/7445#issuecomment-562614618

**Comment by ilyam8** [comment]
`libuv` is a hard dependency now

**Comment by ilyam8** [comment]
To fix it:

- add new `jessie-backports` repos to the `/etc/apt/sources.list`

```
deb http://archive.debian.org/debian/ jessie-backports main contrib non-free
deb-src http://archive.debian.org/debian/ jessie-backports main contrib non-free
```

- as a `root` user execute

```
echo 'Acquire::Check-Valid-Until no;' > /etc/apt/apt.conf.d/99no-check-valid-until
apt-get update
apt-get install libuv1-dev
```

- install/update netdata

**Comment by ludochan** [comment]
> To fix it:
> 
> * add following repos to the `/etc/apt/sources.list`
> 
> ```
> deb http://archive.debian.org/debian/ jessie-backports main contrib non-free
> deb-src http://archive.debian.org/debian/ jessie-backports main contrib non-free
> ```
> 
> * as a `root` user execute
> 
> ```
> echo 'Acquire::Check-Valid-Until no;' > /etc/apt/apt.conf.d/99no-check-valid-until
> apt-get update
> apt-get install libuv1-dev
> ```
> 
> * install/update `netdata` 🎉

Thanks work like a charm o/ have a great day
