### ISSUE TITLE
Propose the ACLK protocol description.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7807]
##### Expected behavior

The full list is on PR # 60 in the docs repo - removing it from here so that is does not get out of sync.

##### Expected outcome

A complete definition of the payload specification on the ACLK ready for grooming in the next sprint.

**Comment by amoss** [comment]
@cosmix / @stelfrag We need to discuss the recent insertion of a GUID into the msg-id field in the JSON wrapper.

UUID generation accesses /dev/random. This is not a major problem when the requests to generate the UUIDs are infrequent. But when this happen too often it will drain the system entropy pool causing the read to block. This will be a bottleneck on the link.

Do we need a UUID or can we switch to a 64-bit counter that will cause a performance problem?

**Comment by cosmix** [comment]
That’s an interesting point @amoss — are you sure it uses `/dev/random`? I thought it was `/dev/urandom`. Either way, I don’t think it’d be a problem, at least, given a protocol that tries to minimize the number of messages sent (e.g. by bundling messages together when possible etc.)

Let’s find out if it’s `urandom` or `random` first. If it’s `urandom` I think we’ll be alright as the probability of collision will still be very low. 

An advantage of the UUID, is that other agents could refer to the message UUID of another agent in the future — which would be easier, than say referring to another agent by its machine-guid AND a 64bit uint.

A 64bit uint, will certainly postpone any issue of integer overflow, sure, :)

But I’m thinking that for 32bit systems (IoT boards) it’ll be slow — on the other hand, we already accept this penalty on those systems anyway elsewhere in the project.

I’m probably good with either.

**Comment by stelfrag** [comment]
I tried uuid_generate. It will use /dev/urandom if available. From the man page:

> The uuid_generate function creates a new universally unique
>        identifier (UUID).  The uuid will be generated based on high-quality
>        randomness from /dev/urandom, if available.  If it is not available,
>        then uuid_generate will use an alternative algorithm which uses the
>        current time, the local ethernet MAC address (if available), and
>        random data generated using a pseudo-random generator.

**Comment by amoss** [comment]
Interestingly the code does not match the man-page:
https://sourceforge.net/p/libuuid/code/ci/master/tree/randutils.c

If you look inside the `random_get_fd()` then you can see that it tries `/dev/urandom` first, then falls back to `/dev/random` if that fails. On Linux and FreeBSD both will be available so `/dev/urandom` will be used. I'm not aware of any systems where only `/dev/random` would be available - are there any?

The probability of collisions is the same for `urandom` / `random` (they have switched to using the same PRNG for both inside the kernel). The fall-back will work fine on bare-metal, but how will it work in containers, especially ephemeral ones? If we cannot guarantee a unique MAC then the probability of collision is much higher.

**Comment by cosmix** [comment]
Thanks @amoss! I admit, I didn't look at the code. I don't see how `urandom` can fail, unless, as you write, it's not available. I don't know of any systems without `urandom`, and don't remember ever encountering one either. In theory there may be (legacy) systems without both (in the FreeBSD world, `urandom` is an alias to `random`)

Re: containers: I believe that (at least) docker starts with a fixed MAC and then creates a unique MAC per container, typically incremented serially for each new container. This means that there is, indeed, a very slightly higher probability for collisions, but I still think that given the way `urandom` works (search for `add_device_randomness`), it's still a very small probability. If we go down that route, I suggest we use `getrandom()` anyway, which will provide good guarantees, in all situations and default to `urandom` when possible (i.e. all the time, except for early in the boot sequence when `urandom` is still uninitialized)

**Comment by stelfrag** [comment]
Yes I saw the code .. weird :-)
Ok so are we worried about code blocking and/or non unique UUIDs (per agent?)

**Comment by amoss** [comment]
I was initially worried about the potential for blocking slowing down message transmission, but it would not seem to be a problem. For collisions I'm happy that libuuid (or directly calling `getrandom()` would be fine as the probability is negligible.

**Comment by amoss** [comment]
Removing the estimate as the definition of this task has changed completely during the sprint.

**Comment by amoss** [comment]
Document is finished and in the docs repo under `architecture/agent`.

**Comment by amoss** [comment]
Putting an estimate on afterwards so I can see the burndown chart. I'm not actually sure if this is closer to a 5 or an 8 given the number of people that were involved.
