### ISSUE TITLE
Add support for alarm values only to `/api/v1/alarms` endpoint.

### ISSUE THREAD

**Issue by cosmix** [netdata/netdata#7810]
##### Feature idea summary

The `/api/v1/alarms` endpoint returns a lengthy and detailed response for all currently active alarms. A more succinct response is required when frequently polling the agent for current alarm values. To this end we need to implement a new endpoint, e.g. `/api/v1/alarms_values` that will return just the active alarm ids and their values.

**Comment by cosmix** [comment]
@amoss please organize the development of this as you see fit. You can reuse the existing endpoint if you wish (e.g. `/api/v1/alarms?values_only`) or add a new endpoint. Obviously the functionality for handling the API call is already there as part of the existing `alarms` endpoint.

**Comment by stelfrag** [comment]
An example of an active alarm via `127.0.0.1:19999/api/v1/alarms` is:

```
{
	"hostname": "futura",
	"latest_alarm_log_unique_id": 1572374922,
	"status": true,
	"now": 1579673829,
	"alarms": {
		"net.virbr0.network_down": {
			"id": 1576579829,
			"name": "network_down",
			"chart": "net.virbr0",
			"family": "virbr0",
			"active": true,
			"disabled": false,
			"silenced": false,
			"exec": "/usr/libexec/netdata/plugins.d/alarm-notify.sh",
			"recipient": "root",
			"source": "24@/etc/netdata/health.d/my_alarm.conf",
			"units": "Mbit",
			"info": "The current operstate of the interface",
			"status": "CRITICAL",
			"last_status_change": 1579623500,
			"last_updated": 1579673822,
			"next_update": 1579673832,
			"update_every": 10,
			"delay_up_duration": 0,
			"delay_down_duration": 0,
			"delay_max_duration": 0,
			"delay_multiplier": 1.000000,
			"delay": 0,
			"delay_up_to_timestamp": 1579623500,
			"warn_repeat_every": "0",
			"crit_repeat_every": "0",
			"value_string": "0 Mbit",
			"last_repeat": "0",
			"calc":"$network_state",
			"calc_parsed":"${network_state}",
			"crit":"$this = 0",
			"crit_parsed":"(${this} == 0)",
			"green":null,
			"red":null,
			"value":0
		}
}
```

The output can be trimmed down to:

```
{
	"hostname": "futura",
	"alarms": {
		"net.virbr0.network_down": {
			"id": 1576579829,
			"value":0
		}
}
```
Is that sufficient?

This will only return alarms for the master (any slaves need to be accessed via /host/slave/ ...)

**Comment by cosmix** [comment]
Yes, that's sufficient as far as scope is concerned, but I think re: slaves we need to discuss this. I don't know if it was discussed by the product team (cc @rduffield), but I certainly think we need to be clear on this.

**Comment by thiagoftsm** [comment]
Hi guys,

I believe we do not need to create a new endpoint to return this kind of data, I would prefer to add a new variable like it was suggested, and we do an internal filter using it.

best regards!

**Comment by cosmix** [comment]
@thiagoftsm in proper REST API design, the response payload format has to be the same irrespectively of any URL query parameter switches. So, using the same endpoint would be wrong. The best way to handle it would then be to do the abstraction internally and expose another endpoint that treated `alarm_values` as a resource.

Since the agent API is far from a strict RESTful API, I'm ok with (ab)using the same endpoint and pass a query parameter.

**Comment by thiagoftsm** [comment]
> @thiagoftsm in proper REST API design, the response payload format has to be the same irrespectively of any URL query parameter switches. So, using the same endpoint would be wrong. The best way to handle it would then be to do the abstraction internally and expose another endpoint that treated `alarm_values` as a resource.

I agree 100% with each word written here.

> Since the agent API is far from a strict RESTful API, I'm ok with (ab)using the same endpoint and pass a query parameter.

This was the motive I suggest to keep the same endpoint, on the other hand, this can be a good opportunity for we begin to delivery a complete RESTful API, but we need to create backward compatibility, so I will give another suggestion, we only change the current endpoint, and we start to work in parallel to have an `/api/v2/` that will follow RFCs.

**Comment by stelfrag** [comment]
> Yes, that's sufficient as far as scope is concerned, but I think re: slaves we need to discuss this. I don't know if it was discussed by the product team (cc @rduffield), but I certainly think we need to be clear on this.

Indeed the slaves part affects all the calls

**Comment by cosmix** [comment]
Another note: the browser will also have to hit the original endpoint, to get the state of the alarm. So we might want to include this in the shortened response payload too.

E.g.:

```json

{
	"hostname": "futura",
	"alarms": {
		"net.virbr0.network_down": {
			"id": 1576579829,
			"value":0,
                         "status": "CRITICAL"
		}
}

```

What do you think?

**Comment by stelfrag** [comment]
> Another note: the browser will also have to hit the original endpoint, to get the state of the alarm. So we might want to include this in the shortened response payload too.
> 
> E.g.:
> 
> ```json
> {
> 	"hostname": "futura",
> 	"alarms": {
> 		"net.virbr0.network_down": {
> 			"id": 1576579829,
> 			"value":0,
>                          "status": "CRITICAL"
> 		}
> }
> ```
> 
> What do you think?

That's fine of course as long as the shortened response is useful (or can be used for something useful) on it's own. 

For example, with the above response you will get the state of the alarm but there is no information as to when the alarm was triggered.

That information will come from the alarm_log of course and those two results would have to be combined to get the timestamp.  Depending on the use case we may want to add that as well.

**Comment by ilyam8** [comment]
Just an idea, to make it flexible - user needs to set in request which fields he wants (endpoint returns min set `id` + `value` + requested). I saw something like that in vsphere `rest` api.

**Comment by stelfrag** [comment]
> Just an idea, to make it flexible - user needs to set in request which fields he wants (endpoint returns min set `id` + `value` + requested). I saw something like that in vsphere `rest` api.

This is a trimmed down version to quickly get current value of an alarm (the full alarm has been already pushed to the cloud at this moment).

**Comment by thiagoftsm** [comment]
Hi guys,

I created the PR that brings what we need, please, let me know whether it is necessary to change anything for we merge it.

best regards!
