### ISSUE TITLE
mysql queries Today

### ISSUE THREAD

**Issue by arabiran** [netdata/netdata#7811]
Hi 
I Want to show MySQL queries from 00:00:00 until now!
I do this command in 00:00:00 mysqladmin flush-status.
and use this badge for monitor MySQL queries  

```html
<embed src="http://mynetdata-server/api/v1/badge.svg?chart=mysql_local.queries&options=unaligned&scale=150&dimensions=queries|questions&after=-86400&precision=0&divide=1000000&group=sum&label=Today%20Server query&value_color=blue&units=Million"
```

but the value show in badge increase and decrease. increase is ok but why decrease after some time?

netdata v1.14.0-43-nightly

**Comment by ilyam8** [comment]
Hi @arabiran 

> increase is ok but why decrease after some time?

Why woudnt it decrease if it is rolling window?

> dimensions=queries|questions&after=-86400

sum of queries and questions for the last 86400 seconds

**Comment by arabiran** [comment]
Hi @ilyam8 
Thank's. 
But you mean netdata can not show the sum of queries for just One Day  I mean from 00:00:00 Until now?

**Comment by ilyam8** [comment]
> https://docs.netdata.cloud/web/api/badges/#netdata-badges

before/after

> These can be absolute unix timestamps, or relative to now, number of seconds. 

You need to calc absolute unix timestams/offset from now and use it in your request.
