### ISSUE TITLE
Splitting UDP packets for backend

### ISSUE THREAD

**Issue by nghtrifork** [netdata/netdata#7812]
Hello.

I would like to use the UDP backend for graphite on netdata. Everything was easily configurable. However, I am having issues with sending the UDP data because my max MTU is 1500 and netdata is sending packets with length of 11600+.

I tried enhancing the "update every" to 1 and 10 but the packet size is the same.

Is it possible to split the UDP packets in chunks?

**Comment by vlvkobal** [comment]
No, it's not possible ATM.

**Comment by ilyam8** [comment]
I dont really understand, 1500 mtu is default mtu. IP packet should be fragmented by os (if there is no `do not fragment me flag`).

**Comment by nghtrifork** [comment]
Hi @ilyam8. I was trying to read upon what you have said, but I am not sure I understand it properly.

We are running netdata in docker (which runs on top of alpine as far as I can see). We are collecting metrics through netdata and we want to send them as UDP packets to our graphite backend. And that works to the extend that we do collect them and we do send them. However, I do not see any way of configuring such fragmentation on the OS level.  

Another option for us would be to send the metrics as soon as they are gathered (1 metric per udp packet) even if that means spamming graphite. Is that possible anyhow at the moment? I am asking this as vlvkobal said that is not possible to split udp packets at the moment and given that it's priority low I don't expect the  team will have in focus soon.
