### ISSUE TITLE
Permission errors using deb packages

### ISSUE THREAD

**Issue by waldner** [netdata/netdata#7813]
##### Bug report summary

Running from deb packages produces many errors

##### OS / Environment

```
Linux scooter 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version (ouput of `netdata -V`)

`netdata v1.19.0`

##### Component Name

netdata

##### Steps To Reproduce

- Install deb packages following the instrucions here https://packagecloud.io/netdata/netdata/install#bash-deb
- Look at logs

It's quite difficult do tell apart real errors from failed connections triggered by autodiscovery of services in the log, but it seems to me that the main issue is that netdata runs as user netdata so it cannot access locations (mainly /proc and /sys) that require root or special group access (eg queries to local docker engine API).

**Comment by ilyam8** [comment]
Hi @waldner 👋 

So what is the problem? Yes, error log contains a lot of messages. I agree that is is a mess.

See https://github.com/netdata/netdata/issues/6038

my opinion on the topic comment

> https://github.com/netdata/netdata/issues/6038#issuecomment-493415568

**Comment by waldner** [comment]
The problem is, for me as a user, not being able to know whether I need to take some action (like running netdata as root or adding user netdata to some group) or not.

**Comment by ilyam8** [comment]
Ok, so it is duplicate of #6038

You are right, this is a problem.

**Comment by waldner** [comment]
Thanks.
