### ISSUE TITLE
Properly notify users if they do not have required repos enabled when installing via our installer scripts.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#7818]
The relevant requirements are:

* On CentOS 6: EPEL and [OKay](https://okay.network/blog-news/rpm-repositories-for-centos-6-and-7.html).
* On CentOS 7: EPEL
* On CentOS 8: EPEL, and probably [OKay](https://okay.network/blog-news/rpm-repositories-for-centos-6-and-7.html)

We should be bailing as early as possible during the install if these repos aren't present, instead of randomly failing late in the build process.

**Comment by prologic** [comment]
Which dependencies btw our of EPEL do we require for the build to succeed?

**Comment by Ferroin** [comment]
I don't remember the full list, but they get pulled in automatically by the install scripts _if_ EPEL is enabled.

OKay on RHEL 6 is required for libuv1, and on RHEL 8 provides the devel packages for libuv1.

**Comment by Ferroin** [comment]
OK, further update on this, we don't get the right versions of libuv-devel and Judy-devel without EPEL.

On top of that, we do actually warn users that they need EPEL, but it's an unconditional warning that doesn't cause a failure during install, and on top of that we appear to be just ignoring errors pulling them in for some reason. Running `install-required-packages.sh` on CentOS 7 without EPEL throws no errors, exits with a 0 exit status, and makes no indication that anything might be missing.

**Comment by prologic** [comment]
@Ferroin #7918 _might_ make this obsolete where I'm taking a bit of a different approach here as we discussed in person.

**Comment by prologic** [comment]
@Ferroin This is done. I did this and automatically installed them optionally now. Closing :)
