### ISSUE TITLE
Native Binary Packages

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#7826]
##### Feature idea summary

This is part of a larger body of work to support and actively maintain native binary packages for all supported OS / Distributions we support today starting with Debian, Ubuntu, Fedora, CentOS, RHEL and openSUSE on the amd64 / x86_64 architecture and move the default installation method to "install from Native Binary Packages".

We have limited support for native binary packages for _some_ Distributions but not all. Our `kickstart.sh` script also continues to build form source. Part of the bigger problem is the way this work was originally done using LXC which turned out to be more work/effort and troublesome that it was worth.

The new plan is to mirror what we have today using Docker-based build and test flows and continue to publish to [packagecloud](https://packagecloud.io/netdata/netdata)

Existing work already done include:
- Docker-based builder images for the above distributions in [netdata/helper-images](https://github.com/netdata/helper-images)
- `Dockerfile` for a full build/install/test cycle #7735

##### Expected behavior

The default installation method for most systems is "Native Binary Packages" with a fallback to "Build from Source".

**Comment by mickae1** [comment]
hi,I would like to know if there is a script to generate a deb file ?

**Comment by prologic** [comment]
There is, but have you checked out [repo](https://packagecloud.io/netdata/netdata)?

**Comment by mickae1** [comment]
> There is, but have you checked out [repo](https://packagecloud.io/netdata/netdata)?

I tried, but after adding the repo to my source list, 

Apt-get update 
Apt-get install netdata
Answer : no package exist with this name ..

Where is the script to create .deb package?

**Comment by prologic** [comment]
The regular Debian control files are on `contrib/debian` you can build the DEB packages there using the normal tooling. Looks like you're trying to get Netdata on an ARM system with Debian packages? (_which AFAIK we don't support at this time_).

**Comment by mickae1** [comment]
> The regular Debian control files are on `contrib/debian` you can build the DEB packages there using the normal tooling. Looks like you're trying to get Netdata on an ARM system with Debian packages? (_which AFAIK we don't support at this time_).

can you explain me how to proceed ?

**Comment by prologic** [comment]
@mickae1 Are you able to file a separate bug report for your inability to use our prebuilt Debian packages we provide? Those _should_ work.

**Comment by mickae1** [comment]
@prologic  it's done #10076

**Comment by Ferroin** [comment]
All parts finished.
