### ISSUE TITLE
Updating multiple text charts at once and delay the refresh time.

### ISSUE THREAD

**Issue by Tommuh** [netdata/netdata#7830]
**1.**
Is it possible to update multiple text charts at once. I have some text charts that belong to each other, sometimes the give incorrect values because some get updated earlier then the other.

I know I can refresh the page every x seconds but that is not what I want.

Below is a total of 5 text charts. I want the PHP requests (2 text charts) to update simultaneously.
The same applies for the PHP childs which are 3 text charts.

![image](https://user-images.githubusercontent.com/2089879/72967271-3ecfa700-3dc1-11ea-94f0-97bfc16c6d75.png)

**2.**
I also have some text charts that doesn't need to update every second. It is good to know what it's output is but it is not important enough to refresh it that quick. It would be great if an extra parameter could be attached which represent refresh time in seconds. I just want to slow down some refreshing to 30 to 60 seconds. This will give my server some relief from those unnecessary refreshes.

**3.**
Why does the text chart have a width 100% and height 100%? 
I think this is not necessary it only makes it annoying to overwrite those values.

**Final.**
We are very happy with Netdata, it saved our lifes a couple times already !! 
We have already upgraded our dashboard a couple of times, it looks like this right now.

![image](https://user-images.githubusercontent.com/2089879/72967953-c9fd6c80-3dc2-11ea-9ba8-3ac3289de8a0.png)

**Comment by ilyam8** [comment]
@jacekkolasa please take a look

**Comment by jacekkolasa** [comment]
Hi @Tommuh, thanks for asking!

Re: 2.
There is a tricky way to force less updates - by providing small `data-points` attributes to `data-netdata` nodes. If default `data-after` is -300 (s), and you'll set `data-points=5`, then the charts will update every minute. The same thing applies to `charts` which display one single, last value (it's done this way so you can hover on dygraph chart and single-value charts will immediately update).
You probably know that, but you can check update interval in the response from `v1/data?chart=`, in `view_update_every`.
If you don't provide `data-points`, then the `points` are calculated based on the chart width, which doesn't of course make sense in single-value charts...

We could in the future allow additional attribute to force `view_update_every`, which would override `points` in some scenarios.

1. Will changing `points` to smaller number fix your problem? That way you'll have updates less often and they will appear to be more synced. Unfortunately there is no way currently to "sync" charts.

3. This is unfortunate, i think we should keep it like this for backwards compatibility, but of course it doesn't make sense, except width is used to calculate the nr of `points` that need to be fetched. We'll need to rethink how to setup single-value charts, the widths should have nothing to do with it.

Let me know if there's anything else.
And thx for sharing your dashboard screenshot :)

**Comment by Tommuh** [comment]
@jacekkolasa thank you for your reply. 

**2.**
I will try the data-points trick.

**1.**
Alright, maybe this is a good feature? 

For example, set a value identifying as a group and combine those requests as one request and fetch all the data needed for those charts...

**3.**
OK :)

**Comment by jacekkolasa** [comment]
hey @Tommuh, i actually missed one attribute which we have especially for this case, called obviously `data-update-every`, which will override all other settings.

Re: 1, could you check what is your setting under `NETDATA.options.current.concurrent_refreshes;`? Setting it to `true` should actually keep sending synced requests, maybe that will fix your problem?

**Comment by Tommuh** [comment]
@jacekkolasa  sorry for late reply.

The requests are sync now with the **concurrent_refreshes** on true.
I tried the "data-update-every", it work like a charm! 

Thank you very very much!

**Comment by jacekkolasa** [comment]
glad it helped!
