### ISSUE TITLE
In-UI configuration editor?

### ISSUE THREAD

**Issue by CSawyerLDN** [netdata/netdata#7831]
I manage several systems with 40+ processors, 30+ network interfaces and a few dozen disks.  The autogenerated netdata configuration file is in the region of 80000 lines with ~3500 [items] and is almost unbearable (and unreliable) to edit in addition to presenting a lot of data i don't want to see/can't digest.  It would be great to be able to disable unneeded config [items] and plugins _from_ the UI

**Comment by prologic** [comment]
Possibly related #6432

**Comment by cosmix** [comment]
Hello @CSawyerLDN, 

We do not currently have plans for a configuration UI on the agent, but we are going to offer a number of UI-based features on our Netdata.Cloud platform later this year. While you cannot do this from the UI, you could easily both disable the collectors and/or create a custom dashboard (https://docs.netdata.cloud/web/gui/custom/) where you'd only choose the charts you're interested in. cc @rduffield @cakrit

**Comment by cakrit** [comment]
@CSawyerLDN I think you're missing something. You don't need to put any of that output into your `netdata.conf`. You can just add overrides for whatever you want to change from that enormous list. So your `netdata.conf` can just have a few lines in it, just with your changes. 

I seldom download the entire `netdata.conf`, I just add the `[sections]` I want to modify and the few parameters that I want to give a new value to. 

Does this info help you with your problem?

**Comment by CSawyerLDN** [comment]
It would, but i have 859 active [sections] :/,  Are [sections] that aren't defined in netdata.conf by default "enabled = no"?

**Comment by cakrit** [comment]
No, the defaults are exactly what you see at `localhost:19999/netdata.conf`. 

Take a look at http://london3.my-netdata.io/netdata.conf. This enormous list of sections and params can be generated without a `netdata.conf` file existing at all. If I wanted to make any changes to that machine's netdata.conf , I would certainly not download that file and go looking. Instead, I would just add changes to whatever sections I want to modify.  

Look at `plugin:proc:diskspace` and notice how many of them there are. Check the `inode usage` setting in them. Some have it by default set to `auto`, others to `no`. 
If I just wanted to enable `inodes usage` charts for `/sys/fs/cgroup`, I would just add to my netdata.conf file the following:
```
[plugin:proc:diskspace:/sys/fs/cgroup]
	inode usage = auto
```

But let's try something a bit tricky, i.e. to set it to `auto` for all partitions. I'm too lazy to copy/paste and then modify each section, so I'd do this:
```bash
curl https://london3.my-netdata.io/netdata.conf > t
grep -A 2 "plugin:proc:diskspace:" t | grep -v "space usage" | tr -d '#-' | sed "s/= no/= auto/" > netdata.conf
```

**Comment by cakrit** [comment]
Did this help @CSawyerLDN? Can we close the issue?

**Comment by CSawyerLDN** [comment]
Thanks for everyone's input.  @cakrit, my systems are vastly more complex than the example you cited.  Your methodology is sound but i'd have to apply dozens of highly selective greps to achieve the same results - it's actually easier to just bash through the config file.  That the generated config file between any two systems isn't the same further complicates matters - i've never had success copying and edited config from one system with another virtually identical one.  C'est la vie, huh?

cheers, all

**Comment by cosmix** [comment]
Thanks for the input @CSawyerLDN and sorry we couldn’t be of much help this time. We’ll certainly take this into account when considering new functionality for the agent. Cc @rduffield @manos-saratsis @cakrit

**Comment by cakrit** [comment]
@CSawyerLDN please drop us an email to info@netdata.cloud, I'd like us to set up a call and discuss your needs a bit more, with our product team.
