### ISSUE TITLE
Validate destination

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7833]
##### Feature idea summary
The issue #4591 brought an important point, Netdata was not testing the destinations before to connect with it, it would be good to give better messages every time we try to connect with an external server.
##### Expected behavior
Raise messages when destinations are not valid

**Comment by ilyam8** [comment]
> https://github.com/netdata/netdata/pull/7297#issuecomment-577308532

> Netdata will raise the error message different times until it reaches the maximum specified in the configuration, the default is 10.

Will it try to connect (or init) N times even if the destination is wrong? Does it make sense?

**Comment by thiagoftsm** [comment]
> Will it try to connect (or init) N times even if the destination is invalid? Does it make sense?

Netdata always did this, independent of to be an invalid address or there was a problem to connect, it tries to reconnect. This is a pattern kept in the new exporter too, so I think we everybody need to agree with this move.
@vlvkobal do you have any objection to change this for the exporters too?

For everybody know, the unique necessary change is to deliver different errors (-1, -2, -3) depending of the error.
I do not have any problem to do this changes, but we need to have an agreement  around the new pattern.

**Comment by ilyam8** [comment]
My point that if the destination is invalid there is no sense to try even once. It looks natural to me.

**Comment by ilyam8** [comment]
> but we need to have an agreement around the new pattern.

Old pattern doesnt have destination validation stage. You are adding it and it seems logical to adjust the pattern too.

**Comment by thiagoftsm** [comment]
I understood your point @ilyam8 and I was studying the case now, and I verified that there is an additional complexity. The function that was changed to give better information is called from `connect_to_one_of`

https://github.com/netdata/netdata/blob/cb38b91c287dd62c22e7faa16628acda47f2c745/libnetdata/socket/socket.c#L853

This function does not try to connect to only one destination, it parses a list of possible destinations and try to connect to the first that it has success, so to change the logic behind this is a bigger change while our initial goal was to give different messages for invalid destinations.

**Comment by ilyam8** [comment]
I think that we need to split validation and connecting and add something like validating step. If there is at least one invalid dst in the destinations list we shouldnt try to connect to any and exit with error - because it would be unexpected behavior for a user. At least i see it this way.

**Comment by ilyam8** [comment]
Example:

```
destinations = dst1 dst2 dst3
```

I expect Netdata connects in this order. I dont want netdata to connect to `dst3` if `dst1` and `dst2` syntax is invalid. 

Because if `dst1` and `dst2` syntax is invalid and Netdata export works it means that this list was implicitly changed to 


```
destinations = dst3
```

**Comment by thiagoftsm** [comment]
> I think that we need to split validation and connection and add something like validating step. If there is at least one invalid dst in the destinations list we shouldnt try to connect to any and exit with error - because it would be unexpected behavior for a user. At least i see it this way.

I respect your opinion, but I think that Netdata gives for the user the option to list various destinations to be sure that it will be possible to connect to at least one. 

Let us extend the discussion with others. @cosmix , @amoss, @mfundul , @stelfrag  and @vlvkobal I would like to hear your opinion about this subject that we are discussing here before we take the decision about what to do with the PR. Thank you!

**Comment by ilyam8** [comment]
> I respect your opinion, but I think that Netdata gives for the user the option to list various destinations to be sure that it will be possible to connect to at least one.

Yes. 

> will be possible to connect to at least one.

If one of them doesnt respond/alive and not if one of them has invalid destination syntax.
