### ISSUE TITLE
Split indexes to enable different names on alarms

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7834]
##### Bug report summary
In the issue #7670 the user described a bug that was present on Netdata, but after an investigation it was identified that there was an ancient bug affecting other areas on Netdata that needs to be fixed.

##### OS / Environment

/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="14.2"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=14.2
/etc/os-release:PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
/etc/os-release:HOME_URL="http://slackware.com/"
/etc/os-release:SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:VERSION_CODENAME=current

##### Netdata version
netdata v1.19.0-379-g129c57e2
 

##### Component Name
Health
##### Steps To Reproduce
Set dimension and alarm with the same name.
##### Expected behavior
Enable users to give any name for alarms.

**Comment by ilyam8** [comment]
@thiagoftsm i suggest to add a note to the alarms documentation - the alarm name shouldn't be equal to the dimension name. #7670 case is very rare, but fixing it seems to be not as easy as it looks. It is very unlikely you will have time to fix it. A note in the documenation will do 😉

**Comment by thiagoftsm** [comment]
> @thiagoftsm i suggest to add a note to the alarms documentation - the alarm name shouldn't be equal to the dimension name. #7670 case is very rare, but fixing it seems to be not as easy as it looks. It is very unlikely you will have time to fix it. A note in the documenation will do wink

Our documentation already have this [description](https://learn.netdata.cloud/docs/agent/health/quickstart#write-a-new-health-entity). Should we set the Pipeline to icebox?

**Comment by ilyam8** [comment]
if it is documented then we are good 👍
