### ISSUE TITLE
Netdata cloud not properly forwarding to nodes

### ISSUE THREAD

**Issue by Pingger** [netdata/netdata#7838]
Hi
##### Question summary
First things First: I have very likely misconfigured something.
I'm currently having an issue with Netdata notifications (over Telegram), that link to my netdata server. The cloud link provided does not properly forward:
http://netdata.cloud/alarms/redirect?agentID=77a15fdc-2a8f-11ea-8c13-1af8315ad190&host=iskariot.info&chart=fping.45_11_18_138_latency&family=45_11_18_138&alarm=host_latency&alarm_unique_id=1577691448&alarm_id=1577661018&alarm_event_id=289&alarm_when=1579804463
Yes, the local port 19999 is blocked, because I want SSL encryption ... always, but the last link in the given list works fine, when manually copied, but not when clicked. On click there is a link prefix, that seems to break the connection.
```
    http://iskariot.info:19999/#top;nowelcome=1;host=iskariot.info;chart=fping.45_11_18_138_latency;family=45_11_18_138;alarm=host_latency;alarm_unique_id=1577691448;alarm_id=1577661018;alarm_event_id=289;alarm_when=1579804463
    http://netdata.iskariot.info:19999/#top;nowelcome=1;host=iskariot.info;chart=fping.45_11_18_138_latency;family=45_11_18_138;alarm=host_latency;alarm_unique_id=1577691448;alarm_id=1577661018;alarm_event_id=289;alarm_when=1579804463
    https://netdata.iskariot.info/#top;nowelcome=1;host=iskariot.info;chart=fping.45_11_18_138_latency;family=45_11_18_138;alarm=host_latency;alarm_unique_id=1577691448;alarm_id=1577661018;alarm_event_id=289;alarm_when=1579804463

```
Additionally I can't seem to get the Nodes view from working. I click "Sign In" authenticate using GitHub, after that in the top right my github name is shown, but clicking the Host name in the top left only shows "Loading, please wait ...". And entering the nodes view using the "Nodes" Button doesn't show any hosts. (For this part see: https://github.com/netdata/netdata/issues/7838#issuecomment-604732495)

##### OS / Environment
Debian 10 (x64). with apache2 reverse proxy
##### Component Name
Netdata cloud? Not sure what to put here...
##### Expected results
The notification links to be working and the nodes view, too.

**Comment by thiagoftsm** [comment]
Hi @Pingger ,

I think it is also possible to have relationship with cloud, I assigned to our guys for them see this, but there is something that called my attention. You said `the local port 19999 is blocked, because I want SSL encryption` , but Netdata can use TLS it is only necessary to do the configuration described at https://docs.netdata.cloud/web/server/#enabling-tls-support .

Best regards!

**Comment by Pingger** [comment]
Additionally apache keeps good logs about which IP tries to access what resources and allows for http authentication

**Comment by Pingger** [comment]
not stale, still waiting for reply

**Comment by val123456** [comment]
I have the same issue on Nodes.

**Comment by Pingger** [comment]
A few days ago I was forced to reinstall my server. Issue still occurs with all stock settings. No forwarding, no apache, plain netdata

**Comment by Pingger** [comment]
Looks like I found part of the issue. Having the Tracking Protection in firefox enabled breaks quite a lot, as it seems to be a bit aggressive from time to time.
Specifically whitelisting  
"registry.my-netdata.io"  
"netdata.cloud"  

At least the Nodes view suddenly starts working.

Suggestion: Add a message, that explains the issue to the user? e.g. "can't load session cookie, are cookie allowed?"

**To clarify:** The issue with the redirect still occurs

**Comment by ilyam8** [comment]
@jacekkolasa take a look

**Comment by cakrit** [comment]
Alarm redirection is no longer working with the new cloud, we will provide more info on it in #9487
