### ISSUE TITLE
ACLK complete support for proxies (HTTP/SOCKS5) (Claiming/Auth/Link)

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#7840]
##### Feature idea summary
Outbound connections from agents to the cloud may need to go through a transparent proxy. As a user, I want to be able to provide the proxy information to netdata, so that my agent can work correctly with the cloud, through a transparent proxy. 

##### Expected behavior

- The `https_proxy` definition consists of a proxy ip/hostname, port, and optionally username and password (see for example the `curl` `-x` option). 
- The `https_proxy` definition must be provided by the user during claiming (either via one or more parameters to the claiming command, or via additional configuration settings). 
- The `https_proxy` definition must be persisted, to be read by netdata for the ACLK establishment.

### Notes
1. Check also the WSS forward proxy case
2. To provide a way for users to check if the ACLK works when setting up their proxy
3. In case the proxy is not accessible after its configuration, we need to provide hints to guide the users (eg check static routing, iptables or firewall policies)

**Comment by underhood** [comment]
We should support read also environment variables `http_proxy` and `https_proxy` not just our config
`http_proxy=http://USERNAME:PASSWORD@SERVER:PORT/`

**Comment by cakrit** [comment]
> We should support read also environment variables `http_proxy` and `https_proxy` not just our config
> `http_proxy=http://USERNAME:PASSWORD@SERVER:PORT/`

Nice! Though we ONLY use https of course, but sure, let's follow any conventions that exist already.

**Comment by underhood** [comment]
I would say it should be in following order:
```
1. commandline flags (to be able to override environment variable)
2. env variable
3. netdata config
```
not 100% sure about 2/3 order though

**Comment by stelfrag** [comment]
> I would say it should be in following order:
> 
> ```
> 1. commandline flags (to be able to override environment variable, i might want to use different proxy than rest of the system for different purposes)
> 2. env variable
> 3. netdata config
> ```
> 
> not 100% sure about 2/3 order though

I agree with the order. 

ENV affects the whole system, so it should be 2 and netdata.config overrides it

**Comment by ilyam8** [comment]
if 

> netdata.config overrides it

which sounds correct, then netdata.config should be 2, right?

**Comment by stelfrag** [comment]
Yes @ilyam8 you are correct. :slightly_smiling_face:

**Comment by underhood** [comment]
Currently the proxy support depends completely on the libwebsockets library and its support for proxies.

Quick Googling shows
https://libwebsockets.org/lws-api-doc-master/html/md_README_8test-apps.html
Search for `proxy support` on that page says:
>The http_proxy environment variable is respected by the client connection code for both ws:// and wss://.
>**It doesn't support authentication.**
>You use it like this
>```
>$ export http_proxy=myproxy.com:3128
>$ libwebsockets-test-client someserver.com
>```

Therefore it seems we have good and bad news
- Good:
    - libwebsockets does already take enviroment variable http_proxy into account
    - this can be overriden with `lws_set_proxy` during startup phase
- Bad:
    - Unsure now what about https_proxy ! Will continue investigation
    - Seems like there is no authentication support (this is critical)

**Comment by cakrit** [comment]
>   * Seems like there is only basic proxy auth support

I guess we'll need to extend it? See https://libwebsockets.org/pipermail/libwebsockets/2015-June/001837.html

>   * NTLM proxy seems not supported (this is case for many linux apps), this is used by many Microsoft heavy companies _(you are lucky if you don't know it :) )_. (http://cntlm.sourceforge.net/)

So we need yet another case to be described in our claiming process and docs, that requires cntlm to be installed. (@manos-saratsis @rduffield)

**Comment by underhood** [comment]
In regards to claiming script now it is using `wget` and `curl` which already will take ENV variables into account. Task here will be to pass override values from `netdata.conf`/commadnline flag to the script when we want to ignore the env variables.

**Comment by underhood** [comment]
Work on this is can be tracked in `underhood/netdata` branch `aclk_agent_proxy`

**Comment by underhood** [comment]
HTTP proxy support - in LWS
Socks proxy support - in LWS
HTTPS proxy support - unknown/unsure yet !!

**Comment by rduffield** [comment]
Scope: start with this working with the proxy in our test environment.

**Comment by amoss** [comment]
Each of the proxy issues has been merged.
