### ISSUE TITLE
netdata out of disk space time says problem fixed when disk is full

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7842]
##### Bug report summary
As you can see in this screenshot netdata says the problem of out of disk space is solved by 2:44:
![image](https://user-images.githubusercontent.com/7656049/73034077-290dc080-3e59-11ea-8c1b-ea2e31e5f543.png)
whereas the disk free space is zero on that time:
![image](https://user-images.githubusercontent.com/7656049/73034112-46428f00-3e59-11ea-82a6-6e842d68d06c.png)

##### OS / Environment

```
Linux gitlab-01.tool.x.y.z 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.5 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.5 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

 
netdata v1.19.0
##### Component Name

health.d

**Comment by ilyam8** [comment]
Hi @yasharne 

> As you can see in this screenshot netdata says the problem of out of disk space

It is not really `out of disk space` alarm, it is 

https://github.com/netdata/netdata/blob/f1d133190bda44504a7f55834ec626ab4e3d32ee/health/health.d/disks.conf#L64-L66

There is an alarm that calculates disk fill rate

https://github.com/netdata/netdata/blob/f1d133190bda44504a7f55834ec626ab4e3d32ee/health/health.d/disks.conf#L48-L61

and `out_of_disk_space_time` uses it

**Comment by amoss** [comment]
Closing based on the response above.
