### ISSUE TITLE
Monitoring Alerta

### ISSUE THREAD

**Issue by jurgenhaas** [netdata/netdata#7850]
##### Feature idea summary

Alerta (https://alerta.io) is already being supported as a channel for notifications. In addition to that it would be great to be able to monitor the health of Alerta as an application. And there are certain components that yould be watched:

- is alerta up and running: that's probably as simple as a http check and doesn't require extra development
- is the alerta api responding, call `alerta status` to see if the expected output is received
- is alerta receiving data from external sources, e.g. call `alerta --json history` and see when the last alert came in
- are the alerta API keys still valid or due to expire by calling `alerta --json keys`

The executable `alerta` is a Python3 script and cpould be utilised by NetData, I guess.

##### Expected behavior

A python plugin should find out if the alerta client is installed and if so, query its API on a regular basis with the 3 suggestions above. If anything serious arises a notification should be sent to a channel which is not Alerta by default. Simply because it may not be functioning anymore.

**Comment by ilyam8** [comment]
Hi @jurgenhaas 

What python script are you talking about? Where could i see it?

This is alerta http api documentation

https://docs.alerta.io/en/latest/api/reference.html

please check it and tell what calls we need to use and in what order

**Comment by jurgenhaas** [comment]
Hi @ilyam8 the python script I meant is the CLI wrapper at `/usr/local/bin/alerta` which utilises the Alerta API:

```
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from alertaclient.cli import cli
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
```

To write our own client to retrieve information from Alerta there is some documentation available at https://docs.alerta.io/en/latest/development.html#examples and their Python SDK is documented at https://github.com/alerta/python-alerta-client

So, to retrieve data for the 3 options above,something like this should do:

```
from alertaclient.api import Client

client = Client(endpoint='https://alerta-api.herokuapp.com/', key='demo-key')
client.mgmt_status()
client.get_history()
client.get_keys()
```

**Comment by jurgenhaas** [comment]
Just did some tests and using `get_history()` is not the correct function to retrieve currently open alerts. The correct function call should look like `client..get_alerts([('status', 'open')])`

**Comment by jurgenhaas** [comment]
Is this still of any interest?

**Comment by ilyam8** [comment]
Hi @jurgenhaas Looks like you are the only person interested in this collector. 

It has [HTTP API](https://docs.alerta.io/en/latest/api/reference.html), it means it is relativly easy to write a collector.

As usual, we need to understand what metrics we need to collector and how represent them (charts).

I see you are suggesting to get alerts with status=open.

Corresponding endpoint is [`/alerts`](https://docs.alerta.io/en/latest/api/reference.html#search-alerts). Using it we can get a number of (status=open) alerts.

What else do you think to gather from Alerta?

**Comment by jurgenhaas** [comment]
From this script 

```


from alertaclient.api import Client

client = Client(endpoint='https://alerta-api.herokuapp.com/', key='demo-key')
client.mgmt_status()
client.get_history()
client.get_keys()
```

I'd be particularly interested in the fact if Alerta is even responding. In addition the status request delivers some basic numbers that could be extracted: [status.json.txt](https://github.com/netdata/netdata/files/5958626/status.json.txt)

Operationally critical though are the expiry dates of the API keys managed by Alerta. You can see the response here: [keys.json.txt](https://github.com/netdata/netdata/files/5958624/keys.json.txt)

The charts should therefore show if Alerta is running and responding and if key expiry dates get close, this should raise an alarm.

The alerts themselves are visible in the Alerta dashboard, so I'm not sure if we should handle them in NetData as well.

Does that make sense?

**Comment by ilyam8** [comment]
> I'd be particularly interested in the fact if Alerta is even responding.

You can use `httpcheck` collector.

---

[`client.mgmt_status()`](https://github.com/alerta/python-alerta-client/blob/2b793e6c3b83686d11c6bd76e1a09fed0a3662db/alertaclient/api.py#L475-L477) uses `/management/status` endpoint. For some reason i couldn't find (CTRL-F) it in [the docs](https://docs.alerta.io/en/latest/api/reference.html).


[`client.get_keys()`](https://github.com/alerta/python-alerta-client/blob/2b793e6c3b83686d11c6bd76e1a09fed0a3662db/alertaclient/api.py#L280-L282) uses `/keys` endpoint. [It is in the docs](https://docs.alerta.io/en/latest/api/reference.html#list-all-api-keys).

**Comment by jurgenhaas** [comment]
Ah, thinking about it we could even use `httpcheck` for the status and api key check as well as we can look into the JSON response that way too. Can we do some logical checks there?

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
