### ISSUE TITLE
Command to reload netdata configuration

### ISSUE THREAD

**Issue by manos-saratsis** [netdata/netdata#7852]
##### Feature idea summary
[Via the "service" command](https://github.com/netdata/netdata/blob/master/docs/getting-started.md#start-stop-and-restart-netdata) we can start, stop and restart a Netdata agent. The option to [reload](https://docs.netdata.cloud/health/quickstart/#reload-health-configuration) might be a useful addition to the wrapper script.

##### Expected behavior
To reload configuration (eg health configuration) without having to restart Netdata via
> service netdata reload

**Comment by thiagoftsm** [comment]
Hi @manos-saratsis ,

We have `netdatacli` that allows to reload `labels` and `alarms`, probably it is only necessary to call it to solve part of the problem, on the other hand, for Netdata to reload the whole configuration and reconnect to backends it will be necessary bigger changes.

Best regards!

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.

**Comment by mailinglists35** [comment]
@ilyam8 what is the status or conclusion, is it feasible?

would it be way easier to reload config only if there are no structural changes, but only values of existing parameters? such as `update_every` globally or in a plugin

**Comment by ilyam8** [comment]
I think #15080 is related. It is adding/updating/removing (for starters) data collection jobs/setting via UI/HTTP API.

**Comment by kingfisher77** [comment]
It seems unclear what the status is on Reloading Configuration like Http Check or Certificate Check without restarting the whole service. Isn't that a fundamental requirement?

**Comment by ilyam8** [comment]
Hey, @kingfisher77. We are working on configuring Netdata's components via UI (w/o restarting the whole thing) but it is wip. See this [workaround](https://github.com/netdata/netdata/discussions/16063#discussioncomment-7123152) for go.d collectors for now.
