### ISSUE TITLE
Update documentation with post-install instructions for GCP users

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#7854]
Given #7786 and other feedback from users on GCP, we need to document how users can quickly fix some common configuration issues, particularly around firewalls that prevent users from accessing the Netdata dashboard.

This could also be extended with details about other platforms, but for the sake of this issue we'll document GCP and I'll research if we have documented solutions for other cloud providers in the issues already.

I'm thinking right now that this work is blocked by #7841, which will add a folder at `packaging/installer/methods/`. Once merged, I could put a `cloud-providers.md` file into that folder with these instructions, and link to this page from the main installation page as well.

I also need some insight into the GCP interface to help direct users to where they need to go to add a firewall rule. @pree-t1, do you think you could help with that? A few screenshots would be enough, or just written instructions: Click on **Settings**, then **Firewall rules**, etc... If not, someone around here should have a GCP account...

Working firewall rule for GCP:

```
Name: <name>
Type: Ingress
Targets: <name-tag>
Filters: 0.0.0.0/0
Protocols/ports: 19999
Action: allow
Priority: 1000

Also, add the above target tag to the instance's network tags. I was able to get it working with these changes.
```

@prologic FYI!

**Comment by pree-t1** [comment]
Sorry for the delayed response.
In front of each google cloud instance, there are three vertical dots, right click on that and select `Network interface details`. Then select `Firewall rules`. You can create a new firewall rule then.
Here is the link for reference: https://cloud.google.com/vpc/docs/using-firewalls
