### ISSUE TITLE
Update documentation in health/quickstart.md to clarify /usr/lib/netdata vs. /etc/netdata

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#7855]
@manos-saratsis pointed out to me that in the health quickstart page (`health/quickstart.md`), there's a little confusion around the differences, if any, between health config files in `/usr/lib/netdata/` and `/etc/netdata`. 

Given that we don't want users directly editing the files in `/usr/lib/netdata/`, this section of the quickstart guide should be clarified to say they can _find_ they files there as reference, but should always use `edit-config` to edit the files, because the script copies them to `/etc/netdata/` first.

**Comment by thiagoftsm** [comment]
This is correct @joelhans , we always expect the alarms from our users inside `/etc/netdata/health.d` .

**Comment by manos-saratsis** [comment]
@joelhans I would add instructions on how to setup your preferred editor with `edit-config`.
