### ISSUE TITLE
Add Alarm Line: message

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#7858]
##### Feature idea summary
Don't know if this has ever been suggested but I would find it very useful to be able to add messages to my alarm configs. 
My reasoning for this is that I often forget what I need to adjust to fix the alarm I have set. For instance, if an alarm is triggered I would like to get the usual critical or warning message but with some text I've added like: 
> To fix this issue you need to raise the max_active_processes in /etc/php/pool.d/www.conf

I realize that I could write scripts for every alarm to send a specific message but that is way too much work. It would also be nice to have the message right there in the alarm template. 

##### Expected behavior
This would only work for specific notification methods, namely email.
I assume it would need to be disabled for things like syslog, text alert, etc.
I was picturing something like this in the template files:
```
template: phpfpm_max_children_reached
      on: phpfpm.performance
    calc: $max_children_reached
   units: times
   every: 10s
    crit: $this > 0
    info: number of times phpfmp has reached max children
      to: webmaster
mess: php-fpm has reached it's process limit.
mess: You may need to increase the pm.start_servers, or pm.min/max_spare_servers
```

**Comment by thiagoftsm** [comment]
Hi @Steve8291 ,

The `info` line can be changed to give the message that you want, you only need to create a file inside `/etc/netdata/health.d`, case the alarms already exists, you only need to run the command `./etc/netdata/edit-config ALARM_NAME`  and change it.
Case you believe our messages are not good enough, please, give us a PR with the newest messages and we will check and merge them to improve Netdata for you and the community.

Best Regards!

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.

**Comment by ilyam8** [comment]
@Steve8291 a very nice idea 👍

**Comment by axroth** [comment]
@Steve8291 very nice idea, indeed!
