### ISSUE TITLE
How to disable recovered alerts 

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7859]
##### Question summary
When some warning or critical alert is sent to the channel (rocketchat and slack in my case), netdata sends a recovered message once the problem is solved. I wonder if it is possible to disable these recovered alerts.

##### OS / Environment
Ubuntu 16.04
netdata v1.19.0
##### Component Name
health.d
##### Expected results
option to disable recovered alerts

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

It is not possible to disable this specific case, because we consider this as good for our users to know that the problem was fixed.

Best regards!

**Comment by thiagoftsm** [comment]
@yasharne I am closing this question, but be free to reopen case the doubt was not solved.

Best regards!
