### ISSUE TITLE
netdata install via docker lost guid after upgrade

### ISSUE THREAD

**Issue by admun** [netdata/netdata#7860]
##### Bug report summary
I am running netdata using netdata/netdata:latest docker image, when upgrade netdata image to new version, it reports "wrong machine GUID".

Is there a way to retain GUID after container image update?

##### OS / Environment
CentOS 7

##### Netdata version

 bash-4.4# $(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V
netdata v1.19.0-335-g4c6714be

##### Component Name
n/a
##### Steps To Reproduce
I am using ansible to run docker on the remote hosts

---
  - name: install docker
    yum: 
      pkg: ['docker', 'python-pip', 'python-docker-py', 'python-urllib3']
      state: present

  - name: enable docker
    service: name=docker enabled=yes

  - name: start docker
    service: name=docker state=started

  - name: create netdata container
    docker_container:
      hostname: "{{ ansible_ssh_host }}"
      name: netdata
      image: netdata/netdata:latest
      restart_policy: unless-stopped
      state: started
      recreate: yes
      pull: yes
      force_kill: yes
      capabilities:
        - SYS_PTRACE
      ports:
        - "19999:19999"
      volumes:
        - "/sys:/host/sys:ro"
        - "/proc:/host/proc:ro"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "/etc/passwd:/host/etc/passwd:ro"
        - "/etc/group:/host/etc/group:ro"

##### Expected behavior
No "wrong machine GUID" after netdata update to newer version

**Comment by prologic** [comment]
Yes there _is_ a way to retain the GUID AFAIK _now_. That is to use a local volume or bind mount `/var/lib/netdata` -- Both _should_ work.

e.g:

```sh
$ docker volume create -d local netdata
$ docker run -v netdata:/var/lib/netdata ...
```

or:

```sh
$ docker run ... -v /some/path/on/host:/var/lib/netdata ...
```

cc @cakrit 

And there are some related issues that are either similar or duplicates here too where this has come up before (_except I can't find them easily through the Github issue type-ahead; if I find them I'll link them alter here..._)

Would you be able to try one of my above suggestions and let me know how it goes? I'm confident it _should_ work :)

**Comment by prologic** [comment]
#7265 is similar here -- specifically [my comment](https://github.com/netdata/netdata/issues/7265#issuecomment-576459927)

**Comment by admun** [comment]
> #7265 is similar here -- specifically [my comment](https://github.com/netdata/netdata/issues/7265#issuecomment-576459927)

Oh I see. In my case, the containers are not ephemeral but the effects the same.

Let me try to add the /var/lib/netdata mount to the container and retry.

will report back. Thanks for the quick response.

**Comment by prologic** [comment]
> Let me try to add the /var/lib/netdata mount to the container and retry.

Don't necessarily bind-m0unt your Host's `/var/lib/` -- But either a) use a named volume with `docker volume create -d local ..` and mount that or b) bind-mount `/some/host/path/netdata` to `/var/lib/netdata` into the container.
 
> will report back. Thanks for the quick response.

Keen to hear how this goes for you :) -- I do this all the time for various reasons or another with Docker / Docker Swarm in general so the same concepts _should_ work.

**Comment by admun** [comment]
@prologic I confirm giving the container a /var/lib/netdata allow the GUID survives docker pull netdata/netdata:latest

I guess this is not really a bug in my case, but I think maybe documentation can use a update for this bit of info.

**Comment by prologic** [comment]
> I guess this is not really a bug in my case, but I think maybe documentation can use a update for this bit of info.

I agree -- IHMO its just lacking documentation. I would live to improve this situation; and I'll make sure we do -- We just have to decide how we want to solve this for the general case -- i.e: technically by some different mechanisms of computing a "GUID" or by way of improving our packaging / documentation.

I'll keep this open for now until I've worked out which way we're going with this -- In the meantime I'm glad this worked for you!

**Comment by cakrit** [comment]
Let's add the instructions to mount additional volumes for the following:
- `/var/cache/netdata` - Database Engine, persist metrics
- `/var/lib/netdata` - GUID, alarm log, private registry, notification silencers config
- `/etc/netdata`  - User config (see also https://github.com/titpetric/netdata#adding-custom-alarms-charts-and-configuration-overrides)

Perhaps even do a PR on `titpetric/netdata` to document the importance of the first two.

**Comment by prologic** [comment]
> Let's add the instructions to mount additional volumes for the following:
> 
> * `/var/cache/netdata` - Database Engine, persist metrics
> * `/var/lib/netdata` - GUID, alarm log, private registry, notification silencers config
> * `/etc/netdata`  - User config (see also https://github.com/titpetric/netdata#adding-custom-alarms-charts-and-configuration-overrides)

Yes! 👍

> Perhaps even do a PR on `titpetric/netdata` to document the importance of the first two.

We have #7819 to import those improvements which will also include improvements for this specif issue too.

**Comment by ElleshaHackett** [comment]
I will post my question here as it seems most related to this issue. I found out about Netdata yesterday, got so excited I deployed it on all servers today. I used docker for that.

I firstly started my docker containers according to the documentation like this: 

```bash
docker run -d --name=netdata \
  -p 19999:19999 \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  netdata/netdata
```

But then of course the Docker ID would be used as hostname and after searching I noticed that I could not change the hostname unless I specified it on container creation. So I removed the docker container `docker rm netdata` and image using `docker image rm netdata/netdata` and then I opened a new container with hostname like this:

```bash
docker run -d --name=netdata \
  -p 19999:19999 \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  --hostname MyUniqueHostname \
  netdata/netdata
```

Then when I opened in the browser the `IP:19999` I noticed that The hostname (left top of GUI) was changed. But when I went to the Console page I saw the old and the new. For both I clicked under Node URLs on `delete` and then on the red `forget` button. So the old and new instances were both cone from the console. Then I reopened the `IP:19999` and the only the new appeared back in my console. But the machines I restarted like this are now all showing `unreachable` and under Node URLs is now written `wrong machine guid`. How do I fix this? Or better, How do I delete all old/cached machine guid's from the console and readd the right ones?

**Comment by cakrit** [comment]
@ElleshaHackett welcome to the wonderful world of Netdata! 
Really impressive, how much you figured out so soon. The first thing I would do, would be to persist the machine guid, by mounting `/var/lib/netdata`, as discussed in this issue. I would also give it a new hostname, so that we can cleanly delete all the old nodes and machine guids. 

With a brand new hostname and a persistent GUID, you'll only have one reachable node. Then you can delete all the old URLs and hosts, with the process you described. The thing is, I'm not sure if we've done enough testing for same "hostname" appearing with multiple GUIDs. So, if you see that you just can't get rid of those old hosts, let us know and we'll delete them manually (you can send us the email used to sign up privately, to info@netdata.cloud). 

This "console" UI will become obsolete within the next 2-3 months, when we release a new and much improved version of netdata cloud. We're working very hard on that, so we probably won't be doing any more patches for the existing version.

**Comment by ElleshaHackett** [comment]
@cakrit thanks for the feedback. Somehow the problem has solved itself. Before I tried your solution. I'm not sure how to mount which mounting point from the host to the container as the documentation seems to differ from the image. I used this:

https://hub.docker.com/r/netdata/netdata

In the docs there it seems they are mounting stuff with `/host/*`. Also it was confusing to find out that in that docker container no netdata service is running but instead an initiation script is started. Meaning there is no way to restart the service, instead the whole container needs to be restarted.

Any ideas on what mounting line to include in my docker command? Also how do I add that afterwards without recreating my containers again and again creating issues with GUIDs in the netdata console.


--- 
A bit off topic:

_Lastly I find it quite difficult (even with documentation) to find a way to enable and configure plugins for specific software. I started quite enthusiastic and as planning to write my own plugins, maybe I will still later (likely in Node.js and Python) but for now I firstly need to learn more about the plugin architecture and how it works. As I hoped for something simple regarding enabling/disabling and installing/uninstalling plugins. I'd also like to find out exactly what the difference is between running in within a docker and locally when all the required folders from the host are shared (read-only), I mean theoretically that should be enough to access the same as on the host. But I like the benefits of having everything running a little more isolated from the host without having the files all over the host machine_

**Comment by cakrit** [comment]
@ElleshaHackett for the second (off topic thing), I suggest you split it in a separate issue. We're not very happy with how easy it is to add a new collector either and we'll be working on that.  The [relevant page](https://docs.netdata.cloud/collectors/plugins.d/#external-plugins-overview) needs a lot of love (wink at @joelhans and @ilyam8 ). But you don't need to understand everything about it, copy/pasting is an essential part of SW development, we have tons of examples. Also @ilyam8 will be there to help you out with your PR.

Running netdata containerized is what over one third of the community does. The vast majority of collectors relies on TCP to retrieve metrics, so there aren't that many things that you're missing if you don't have the disk available (with the exception of `/proc` `/sys` etc of course). 

I will leave the other part (the relevant to this thread question) to be answered with a PR that will take care of the discrepancies you noticed and cover the documentation gaps that made this hard for you. Assigning to  @prologic

**Comment by ilyam8** [comment]
> likely in Node.js and Python

If you are going to make a PR please no `node.js`. As for python - there is no such thing as install plugin. You name your script `*.chart.py` and drop it into the `/python.d/`, that is pretty much it.

**Comment by prologic** [comment]
I _think_ the PR is to the docs  for how to properly configure and run NetData via Docker?

**Comment by cakrit** [comment]
> I _think_ the PR is to the docs for how to properly configure and run NetData via Docker?

Precisely.

**Comment by cakrit** [comment]
The only remaining issue here is to improve the documentation on the volumes that need to be mounted.

**Comment by ilyam8** [comment]
>  I confirmed giving the container a /var/lib/netdata allow the GUID to survives docker pull netdata/netdata:latest

I guess this is not really a bug in my case, but I think maybe documentation can use a update for this bit of inf


it is already in the docs

> https://learn.netdata.cloud/docs/agent/packaging/docker#run-the-agent-with-the-docker-command

**Comment by ilyam8** [comment]
Fixed in https://github.com/netdata/netdata/pull/8813

**Comment by prologic** [comment]
Thanks @ilyam8 !
