### ISSUE TITLE
Netdata behind nginx+cloudflare "Cannot load required JS Library"

### ISSUE THREAD

**Issue by lopoki** [netdata/netdata#7861]
netdata v1.19.0-336-nightly Ubuntu 18.04.3 LTS

So I'm trying to setup netdata behind nginx reverse prozy with DNS from cloudflare.
accessing https://mydomain/nd/#;theme=white;help=false gets error "Cannot load required JS Library"
So the page itself loads but empty because no JS loaded.

user_browser --> cloudflare --> server

How can I fix this?

My netdata, nginx conf:
https://docs.netdata.cloud/docs/running-behind-nginx/

```
upstream nd {
    server internal_IP:55554;
    keepalive 64;
}

....

server {
    server_name mydomain;
    listen 443 ssl http2; 
....
 location = /nd {
        return 301 /nd/;
           }

location ~ /nd/(?<ndpath>.*) {
        proxy_pass http://nd/$ndpath$is_args$args;
        proxy_redirect off;
        proxy_set_header Host $host;

#        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Real-IP $remote_addr;
        #proxy_pass http://nd/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;
    }
```

My cloudflare setting:
SSL/TLS encryption mode is Full
Cloudflare Universal SSL certificate ON
Always Use HTTPS ON
Automatic HTTPS Rewrites ON
Caching Standard

In addition to this. Accessing above server using different domain via https+Let's encrypt SSL without Cloudflare, using similar Nginx reverse proxy setting also shows the same error "Cannot load required JS Library"

**Comment by cosmix** [comment]
Possibly related to #7641 cc @jacekkolasa @thiagoftsm @amoss

**Comment by thiagoftsm** [comment]
Hi @lopoki ,

When I worked with nginx as reverse proxy, I used a configuration more or less like yours, but I had the following differences:

```
server {
listen       8080;
proxy_set_header X-Forwarded-Host $host;

ssl on;
ssl_certificate /etc/nginx/cert.pem;
ssl_certificate_key /etc/nginx/key.pem;
proxy_pass https://localhost:19999;
}
```

In my case, I had Netdata with SSL certificate, so it could not be 100% like yours.

Best regards!

**Comment by jacekkolasa** [comment]
Hi, @lopoki , do you still have this problem? If yes, could you please check the network tab in browser dev tools, and see what error codes you get when fetching .js files?

**Comment by amoss** [comment]
Closing due to lack of information - @lopoki if you are still having problems then please re-open and talk to @jacekkolasa about what is happening.
