### ISSUE TITLE
API info has two patterns in the code.

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7863]
##### Bug report summary
After we merge the PRs that brought containers to `web/api`, it would be good to have only one pattern for the code.

##### OS / Environment
```
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="14.2"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=14.2
/etc/os-release:PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
/etc/os-release:HOME_URL="http://slackware.com/"
/etc/os-release:SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:VERSION_CODENAME=current
```

##### Component Name
Web
##### Steps To Reproduce

1. Read the code

##### Expected behavior
To have the same number of elements in the response, independent of what is running on the host.

**Comment by ilyam8** [comment]
it is not clear for the OP what is the problem.

Steps to reproduce 👍 😃 

Os/Env is not relevant to the problem. Is it a bug btw?

**Comment by thiagoftsm** [comment]
It is not a bug, it was only to adjust the response.
We were having a response with X values when there was container and we had with (X-5) without containers.
This rule was applied only to containers, for all the other variables in the response we were setting `null` values when there was not any value, so I am bringing the same concept for the whole response,

**Comment by thiagoftsm** [comment]
About the OS, I only set it, because it is one of the fields expected.

**Comment by ilyam8** [comment]
> We were having a response with X values when there was container and we had with (X-5) without containers.

probably this should be in the OP with examples instead of 

> After we merge the PRs that brought containers to web/api, it would be good to have only one pattern for the code.

My point that it is not clear what and why you are doing, is this a bug or not,etc.

**Comment by thiagoftsm** [comment]
Considering the explanation given at https://github.com/netdata/netdata/pull/7864#issuecomment-578783031 , I am closing this issue.
