### ISSUE TITLE
Implement TTL/Data Expire on Mongo Backend config

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#7865]
It would be nice to have the option to set a [mongo ttl](https://docs.mongodb.com/manual/tutorial/expire-data/) on the mongo data as part of the config for the mongodb backend. 

I believe i was able to add such an index to the existing `timestamp` field by using a mongo cli command like below:

```
> db.collection.createIndex( { timestamp: 1 }, { expireAfterSeconds: (60*60*24*3) } )
{
        "createdCollectionAutomatically" : true,
        "numIndexesBefore" : 1,
        "numIndexesAfter" : 2,
        "ok" : 1
}
```

It might be nice to be able to set such a `expireAfterSeconds` optional index in the `mongodb.conf`. 

This could be useful for users who just want to store the most recent data in mongo without having to worry about managing mongo size seperatly.

**Comment by andrewm4894** [comment]
@thiagoftsm not sure if i'm missing any labels on this or not. Happy to provide more info if needed.

**Comment by thiagoftsm** [comment]
> @thiagoftsm not sure if i'm missing any labels on this or not. Happy to provide more info if needed.

For now I think we do not need more nothing, everything is right! :)

**Comment by andrewm4894** [comment]
The index on the `timestamp` field would also be useful for when querying the mongo database based on timestamp. Seems like there is no index on `timestamp` by default so this would be another use case for this index.

**Comment by andrewm4894** [comment]
Just an update on this - looks like the TTL needs to be applied on a [`Date()`](https://docs.mongodb.com/manual/reference/bson-types/#document-bson-type-date) type. So `timestamp` is a number or integer and so the ttl is not being applied in my case above. 

We would need to have a Date() type field that the ttl could be applied to.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
