### ISSUE TITLE
How do I customize the data?

### ISSUE THREAD

**Issue by BH1NBN** [netdata/netdata#7867]
I have some data obtained in my own way
{"Cpu0": {"total": "17367161", "usage": "1148016"}, "cpu1": {"total": "17960729", "usage": "126202"}, "cpu2": { "Total": "17951659", "usage": "133376"}, "cpu3": {"total": "17953410", "usage": "127798"}}} \ n; \ nmemInfo = {"total" : "1048576", "Free": "469552", "Used": "579024"}
Can I transfer this data to a netdata chart in real time?
If yes, what should I do?

**Comment by ilyam8** [comment]
Hi @BH1NBN 

You can write a python.d module to get/process this data and convert it into charts

Check this
https://docs.netdata.cloud/collectors/python.d.plugin/#how-to-write-a-new-module

**Comment by BH1NBN** [comment]
@ilyam8
 I know a little about python but I'm not very proficient! Is there an easy-to-understand example? I want to refer to it! I tried to understand the connection you provided, but I don't know how to start writing.

**Comment by ilyam8** [comment]
the link i gave you is a good place to start

take a look at this module as an example

> https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/dnsdist/dnsdist.chart.py

**Comment by BH1NBN** [comment]
@ilyam8 
Thank you for your guidance. I also saw your example, I will try to write an example to run! thank you for your reply!
https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/example/example.chart.py

**Comment by ilyam8** [comment]
> I have some data obtained in my own way

Actually it depends on the way of gathering data. If you use http req then `dnsdist` is a corrcet example.

**Comment by BH1NBN** [comment]
@ilyam8 
1. My idea is that python can access http requests
2. Get the result and present it in a netdata chart

**Comment by ilyam8** [comment]
> My idea is that python can access http requests

Then example from [my prev post](https://github.com/netdata/netdata/issues/7867#issuecomment-579097780) is nice. You only need to replace charts and add a little bit of processing.
