### ISSUE TITLE
documentation on phpfpm plugin confusing

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#7868]
##### Question summary

Trying to interpret PHP-FPM Request Memory graph. Searches on this word combination points to netdata code only, attempt to find explanation on https://docs.netdata.cloud/collectors/python.d.plugin/phpfpm/ failed as documentation on that page seems to be outdated as it describes only first 3 graphs the module creates. Unclear things are
- What's shown in fact on the graph? Does this graph shows memory consumption per request? Average? Total?
- why units displayed are megabytes while on same server php-fpm consumes gigabytes and this is correctly shown on application memory graph?
- can documentation on above mentioned link be fixed by someone who knows exactly what module displays?

##### OS / Environment
Linux 4.19.92-gentoo

##### Component Name
python.d/phpfpm

##### Expected results
Documentation on above mentioned page describing what graph shows (in order to be able to interpret it correctly)

**Comment by ilyam8** [comment]
Hi @ekexcello 

Yes, documenation is outdated 😅 

About memory, see

> https://brandonwamboldt.ca/understanding-the-php-fpm-status-page-1603/

> last request memory – the max amount of memory the last request consumed (it’s always 0 if the process is not in Idle state because memory calculation is done when the request processing has terminated)

min - min value among all processes
max - max value among all processes
avg - average = sum / count

**Comment by ekexcello** [comment]
Thank you for explanation, @ilyam8 
BTW, won't it be good to rename graph from "Request memory" to "Last request memory" in that case?

**Comment by ilyam8** [comment]
Hm, fixing chart titles i realized that we are taking into account only processes in `idle` state, which makes sense for:

- last request cpu
- last request memory

because for both metrics

>  it’s always 0 if the process is not in Idle state because calculation is done when the request processing has terminated.

Which is not the case for `request duration`

in the #7876 i changes chart title accordnig to current logic

> PHP-FPM Requests Duration Among All Idle Processes

But

>  the duration in µs of the requests

i think we dont need to skip idle state processes calculating request duration average. What do you think @ekexcello ?

@Ferroin ?
