### ISSUE TITLE
Fails to build with `-fno-common` / GCC 10

### ISSUE THREAD

**Issue by candrews** [netdata/netdata#7869]
##### Bug report summary
gcc-10 and above flipped a default from -fcommon to -fno-common: https://gcc.gnu.org/PR85678

netdata currently fails to compile when given the CFLAG `-fno-common`:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/libnetdata.o (symbol from plugin): in function `strdupz':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/locks/locks.o (symbol from plugin): in function `netdata_thread_disable_cancelability':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/log/log.o (symbol from plugin): in function `facility_log':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/popen/popen.o (symbol from plugin): in function `myp_init':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/procfile/procfile.o (symbol from plugin): in function `procfile_adaptive_initial_allocation':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/os.o (symbol from plugin): in function `get_system_cpus':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/simple_pattern/simple_pattern.o (symbol from plugin): in function `simple_pattern_create':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/socket/socket.o (symbol from plugin): in function `poll_default_add_callback':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/socket/security.o (symbol from plugin): in function `security_openssl_library':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/statistical/statistical.o (symbol from plugin): in function `log_series_to_stderr':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/storage_number/storage_number.o (symbol from plugin): in function `pack_storage_number':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/threads/threads.o (symbol from plugin): in function `netdata_thread_tag':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/url/url.o (symbol from plugin): in function `from_hex':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/json/json.o (symbol from plugin): in function `json_callback_print':
(.text+0x0): multiple definition of `silencers_filename'; libnetdata/log/log.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/json/json.o (symbol from plugin): in function `json_callback_print':
(.text+0x0): multiple definition of `netdata_ready'; libnetdata/log/log.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/json/json.o (symbol from plugin): in function `json_callback_print':
(.text+0x0): multiple definition of `api_secret'; libnetdata/log/log.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/json/json.o (symbol from plugin): in function `json_callback_print':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libnetdata/health/health.o (symbol from plugin): in function `create_silencer':
(.text+0x0): multiple definition of `silencers'; collectors/apps.plugin/apps_plugin.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```

Here's the the build log showing the failure:
[net-analyzer:netdata-9999:20200127-204109.log](https://github.com/netdata/netdata/files/4119330/net-analyzer.netdata-9999.20200127-204109.log)

Here's some more info about how to fix the issue: https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common
##### OS / Environment

n/a, use GCC 10 or specify the `fno-common` CFLAG.

##### Netdata version

 Current master, https://github.com/netdata/netdata/commit/a4223457b49497f57bd199dfaf5cf35c4fb86997

##### Component Name

core

##### Steps To Reproduce

1. Compile with CFLAGS="-fno-common"

##### Expected behavior

Should compile.

**Comment by thiagoftsm** [comment]
Hi @candrews ,

I was studying the compilation logs now and I have few questions for you:

1 - I verified that you are linking with `json-c`, what is the `json-c` version that you have installed?
2 - I also could see that Gentoo has the same gcc version that I am using on Slackware, please, can you give us the output of `gcc -v`?  I also suspect that the final binary can be missing some option.

Best regards!

**Comment by candrews** [comment]
1. json-c version is 0.13.1
2. ``` # gcc --version
gcc (Gentoo 9.2.0-r3 p4) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. ```

You can see this problem in Travis CI at #7870 (it's not a Gentoo specific problem, it happens whenever `-fno-common` is set which it will be by default in GCC 10)

**Comment by thiagoftsm** [comment]
I understood the problem, I saw your PR, but I found interesting the fact that I do not have the problem using the same libraries and the same compiler, this was the motive I made the questions.

I will request a final test for you, please, instead to use:

```
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/netdata-9999 --htmldir=/usr/share/doc/netdata-9999/html --libdir=/usr/lib64 --localstatedir=/var --with-user=netdata --enable-jsonc --enable-plugin-cups --enable-dbengine --disable-plugin-nfacct --disable-plugin-freeipmi --disable-backend-kinesis --disable-backend-mongodb --disable-backend-prometheus-remote-write --disable-plugin-xenstat --enable-x86-sse --with-zlib
```

could you compile with the following options:

```
CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-go --disable-lto --dont-wait --dont-start-it --install=/opt/test_netdata
 ```

Best regards!

**Comment by candrews** [comment]
That works, which is expected, as `-fno-common` isn't explicitly set and I'm not using >=GCC 10.

**Comment by thiagoftsm** [comment]
Thank you, this is what I wanted to confirm!
I also compiled Netdata with -fno-common, so let us wait the `sre-team` moves in front with your PR.

**Comment by prologic** [comment]
@thiagoftsm Adding this options fails in our CI/CD build environments too -- so I don't its specific to @candrews 's environment per se.

**Comment by prologic** [comment]
> I also compiled Netdata with -fno-common, so let us wait the `sre-team` moves in front with your PR.

I don't think we can merge the PR as-is. it currently breaks our builds. See my reply on the PR.

**Comment by candrews** [comment]
Yes, this PR should not be merged right now.

My intent is for this PR is twofold:
1. Demonstrate in a clear, reproducible fashion on netdata's own systems (so it's clear that the issue is not distro related, for example) that netdata currently fails to build with the `-fno-common` CFLAG which will be set by default in GCC 10 (so in GCC 10, no explicit CFLAG setting is necessary - netdata fails by default with GCC 10 today).
2. Have this PR ready as it should be merged when the source changes have been made that cause the build failures.

**Comment by Ferroin** [comment]
To clarify so nobody has to follow the links about the fix, the issue here is that with `-fno-common`, GCC will emit assembly that uses the `.data` section for uninitialized globals instead of the `.bss` section, which results in the duplicate definition errors seen in the first comment when there are multiple definitions of the same global variable.

The correct fix is, as documented in link to the Gentoo Wiki page on handling this, is to explicitly mark declarations  with `extern` so that they get treated as declarations and not definitions.

**Comment by amoss** [comment]
Ok, so after the new issues is fixed and merged we will retest this PR so that it can be merged. @candrews Thank you for pointing this out, it will save us a lot of trouble in the future.

**Comment by thiagoftsm** [comment]
Thank you @candrews , we merged your PR after we fix the error.
I will close this issue, but feel free to reopen!
