### ISSUE TITLE
"System RAM used" metric uses confusing denominator in formula

### ISSUE THREAD

**Issue by mateon1** [netdata/netdata#7871]
##### Bug report summary
Note: this is NOT #3381 (but involves the same metric) - this issue refers to the metric being confusing even outside of a container.

---

The formula for calculating the memory use is either wrong, or at the very least confusing.
`system.ram.ram_in_use` uses the following expression:
```bash
($used - $used_ram_to_ignore) * 100 / ($used - $used_ram_to_ignore + $cached + $free)
```
with `$used_ram_to_ignore` being the ZFS arc size, and documented as "memory that is reported as used, but [can be resized on demand]".

On my system the ZFS arc takes just under half of my RAM, which makes the ram_in_use alarm trigger eagerly.

I believe that `used_ram_to_ignore` should not be subtracted in the denominator, so `ram_in_use` represents the percentage of system memory that cannot be given to other programs.

(Also, I'm pretty sure that `used_ram_to_ignore` should be the difference between the current arc size and the min size of the arc, instead of the whole arc size.)

##### OS / Environment
Linux ceres 4.19.75 #1-NixOS SMP Sat Sep 21 05:17:15 UTC 2019 x86_64 GNU/Linux
NixOS 20.03pre194079.82fe35cd29b (Markhor)

##### Netdata version
netdata v1.17.1
 
##### Component Name
health

##### Steps To Reproduce
I discovered this bug when digging into why I was getting more alarms after updating netdata, and noticing that the calculated percentage on the "ram in use" widget was off.
Steps to reproduce:
1. Run netdata on a system with a large ZFS ARC in relation to normal memory.
2. Open netdata and find the "system - ram" "ram in use" alarm in the "All alarms" section.
3. Notice wonky reported values.

##### Expected behavior
I expected the calculated value to be closer to the amount of used RAM that cannot be automatically freed.

**Comment by vlvkobal** [comment]
@Ferroin please have a look at it.

**Comment by amoss** [comment]
@thiagoftsm please could you check this?

**Comment by thiagoftsm** [comment]
> @thiagoftsm please could you check this?

I will work on this tomorrow!

**Comment by araemo** [comment]
I am having a similar issue, but my suspicion was that $zfs.arc_size.arcsz is not being read right.

On my system, as well, half the ram is used by the arc, until memory pressure starts reducing it.  So, this alarm fires often, as a false alarm.  Is there a way to see if the $zfs.arc_size.arcsz is being imported right?

the actual zfs.arc_size graph is displaying the correct details, but the mem.available graph does not reflect the RAM available from the arc.  I do agree with @mateon1 that the correct $used_ram_to_ignore should be arcsz - min ($zfs.arc_size.arcsz - $zfs.arc_size.min)

I changed that line from:
```
calc: ($zfs.arc_size.arcsz = nan)?(0):($zfs.arc_size.arcsz)
```
to:
```
calc: ($zfs.arc_size.arcsz = nan)?(0):($zfs.arc_size.arcsz - $zfs.arc_size.min)
```
And the ram in use % looks much better now.:
```
$ free -m && grep "^size" /proc/spl/kstat/zfs/arcstats && grep "^c_min" /proc/spl/kstat/zfs/arcstats
              total        used        free      shared  buff/cache   available
Mem:          64315       42994       20737          15         583       20615
Swap:             0           0           0
size                            4    13983473472
c_min                           4    2107474176

```
At this point, I see ram used to ignore is 11382 MiB, and ram in use is 49.2%, which is much more accurate than what I was seeing before.  (oddly, restarting netdata caused the arc to evict most of its contents.. is netdata calling anything interesting ZFS related at startup?)
![Restart_Netdata_ARC_dropped](https://user-images.githubusercontent.com/1126773/80993176-a063d080-8e08-11ea-8e76-74df3152f168.png)

**Comment by thiagoftsm** [comment]
Hi @araemo ,

> On my system, as well, half the ram is used by the arc, until memory pressure starts reducing it. So, this alarm fires often, as a false alarm. Is there a way to see if the $zfs.arc_size.arcsz is being imported right?

You can always do a request to Netdata using the web API to verify the used values, please, do the following requests to confirm that the data is correct:

1 - Get values for specific chart: `http://localhost:19999/api/v1/alarm_variables?chart=zfs.arc_size`
2 - Get data for the chart: `http://localhost:19999/api/v1/alarm_variables?data=zfs.arc_size&after=-60`

> the actual zfs.arc_size graph is displaying the correct details, but the mem.available graph does not reflect the RAM available from the arc. I do agree with @mateon1 that the correct $used_ram_to_ignore should be arcsz - min ($zfs.arc_size.arcsz - $zfs.arc_size.min)
> 
> I changed that line from:
> 
> ```
> calc: ($zfs.arc_size.arcsz = nan)?(0):($zfs.arc_size.arcsz)
> ```
> 
> to:
> 
> ```
> calc: ($zfs.arc_size.arcsz = nan)?(0):($zfs.arc_size.arcsz - $zfs.arc_size.min)
> ```
> 
> And I also changed the ram in use calc to be:
> 
> ```
> calc: ($used - $used_ram_to_ignore) * 100 / ($used + $cached + $free)
> ```
> 
> And the ram in use % looks much better now.:
> 
> ```
> $ free -m && grep "^size" /proc/spl/kstat/zfs/arcstats && grep "^c_min" /proc/spl/kstat/zfs/arcstats
>               total        used        free      shared  buff/cache   available
> Mem:          64315       42994       20737          15         583       20615
> Swap:             0           0           0
> size                            4    13983473472
> c_min                           4    2107474176
> ```

Thank you for the suggestions!

> At this point, I see ram used to ignore is 11382 MiB, and ram in use is 49.2%, which is much more accurate than what I was seeing before. (oddly, restarting netdata caused the arc to evict most of its contents.. is netdata calling anything interesting ZFS related at startup?)
> ![Restart_Netdata_ARC_dropped](https://user-images.githubusercontent.com/1126773/80993176-a063d080-8e08-11ea-8e76-74df3152f168.png)

Please, would you like to create a PR to fix this problem considering that you wrote all details here?
