### ISSUE TITLE
eBPF process and Apps.plugin integration

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7873]
##### Feature idea summary
We already have a global vision of what is happening with process, but it would be interesting to have the same vision per process group, so we need to do integration with eBPF plugin.

For while we are working with these possibilities to move in front with the integration:

1 - Shared Memory: Here we will create a common memory region between `apps.plugin` and `ebpf.plugin`. It will be necessary to use locks to update the values that will come from `ebpf.plugin`, here I am assuming that `apps.plugin` will be responsible to make all the charts, for more details read [this](https://github.com/netdata/netdata/issues/7873#issuecomment-618132093).

2 - Other IPCs: We can select another IPC that will allow `ebpf.plugin` to send data to `apps.plugin` that will generate the charts. [IPCs](https://github.com/netdata/netdata/issues/7873#issuecomment-619633734)

3 - Shared library: We could move outside `apps.plugin` the common code for both collectors to a specific shared library that will be used from both collectors.  For more details about the functions will need to be moved to the Shared library go to [this link](https://github.com/netdata/netdata/issues/7873#issuecomment-600957047)

##### Expected behavior
To define the road to generate new charts for the apps groups.

**Comment by amoss** [comment]
@thiagoftsm Please explain the different options in this issue so that we can have an asynchronous discussion leading up to the grooming meeting.

**Comment by thiagoftsm** [comment]
With the conclusion of #8112 and the results that we got on #7987 we need to define how we will do the integration between the collectors.
The eBPF program won't be able to have the same charts that we have at apps.plugins, but `apps.plugin` has a logic that we need for the `ebpf_program.plugin`, so we need to define the road to do this "integration".

**Comment by thiagoftsm** [comment]
I will present few scenarios, firstly let us suppose that we want to have an eBPF plugins completely independent of apps.plugin, in this scenario we will have a hash table inside the collector where we will store the relationship between TGIDs and PIDs. We will also have two other hash tables inside the collector, one to store the PID statistic and other to store TGID statistic. We will have the following algorithm to update the tables:

1 - When the function is called we read the necessary values.
2 - After this we split the values for TGID and PID that are stored together, we can separate them using bitwise.
3 - We search inside the hash table that stores PID the previous statistic values for we update, case it is not present we create it. It is interesting when we create the PID information, we also create the other two rows inside the other hash tables.
4 - Finally we get the statistic values for TGID and we update/create it like the previous steps.

It is important to consider that probably the relationship between TGID and PID is not necessary to be stored in a new hash table, because we can store together the statistic values the TGID associated. We can also associate to the statistic structure the internal string `Name` that can be visualized inside `/proc/PID/status`. This is a 16 bytes long text that can be used like we use the texts in apps.plugin.

In the user ring, we can move trough all values present inside the `PID` structure and generate the charts using the information stored there.

**Comment by thiagoftsm** [comment]
Case we decide to use with `eBPF` collector what was already created for `apps.plugin`, we need to port the following structures:

- `struct target`: target is the structure that processes are aggregated to be reported to netdata.
- `struct pid_on_target`: structure associated with the previous structure.

We will also need to move functions that manipulate these structures to a shared library, for example, we will need to move:

- `get_users_target` and `get_groups_target`: Aggregate all processes in groups, to have a limited number of dimensions
- `get_apps_groups_target`:  find or create a new target
- `zero_all_targets`: Reset all targets with value zero.

It is important to say that case we decide to follow this road, we cannot only cut and paste code to other file, it will be necessary to change function arguments and body, because we have `avl` trees associated to these functions. Another important information, we do not need to move all functions that work with `struct target`, because the PIDs are manipulated in a different way with `eBPF`.

**Comment by thiagoftsm** [comment]
After the last discussion I scheduled a meeting next week to talk with product team about the integration between both plugins. In this meeting we intend to talk about the overlap between both plugins and I will also explain a necessity to create a more generic structure that could allow us to do integration of different plugins .

**Comment by thiagoftsm** [comment]
On the meeting with product team we agreed that it is necessary to define the charts that will be integrated with `apps.plugins` in another meeting. 

It was also defined that we won't have duplicated information between `eBPF` configuration files and `apps.plugin` files. The `ebpf` configuration file will control the following features:

- Run level: What is the eBPF  run level `return` or `entry mode`?
- Developer mode: is the `developer mode` enabled?
- ebpf programs loaded: Instead to have different eBPF collectors, we will have only one eBPF plugin and we will control inside the configuration file the `program` that will be loaded.

About the `apps_groups.conf` we decided that it will be the unique file organizing both collector groups and we will create new entries on it to define the eBPF charts to be displayed.

**Comment by thiagoftsm** [comment]
We had a meeting yesterday to discuss the charts that we will create inside `apps.plugin` using the data collected with `ebpf.plugin`, during this meeting we defined that:

- `eBPF` plugin will be renamed to `ebpf.plugin`
-  `ebpf.plugin` will become a modular process like `proc.plugin` and the network information will be integrated to it after this.
- Each dimension on the global eBPF charts will become a chart inside `apps.plugin` and the dimensions of the new charts will be the process groups.

We also discussed a propose to do the integration between both collectors, in the new propose apps.plugin will create a pipe or unix socket that will establish a direct connection between apps.plugin and ebpf.plugin. In this case, apps.plugin will have another thread exclusively for this communication.

**Comment by cosmix** [comment]
> We also discussed a propose to do the integration between both collectors, in the new propose apps.plugin will create a pipe or unix socket that will establish a direct connection between apps.plugin and ebpf.plugin. In this case, apps.plugin will have another thread exclusively for this communication.

I would like to see a more complete description of this @thiagoftsm before the implementation is groomed and planned. I have serious doubts as to whether such an approach would be optimal, but I need to understand what you have in mind before commenting further.

**Comment by thiagoftsm** [comment]
I will do @cosmix .
I was thinking to create another issue exclusively for this.

**Comment by thiagoftsm** [comment]
Continuing with the requested description, case we decide do not follow https://github.com/netdata/netdata/issues/7873#issuecomment-600957047 and follow the suggestion https://github.com/netdata/netdata/issues/7873#issuecomment-611822278 the following changes will be necessary inside `apps.plugin`:

-   `apps.plugin` has right now only one thread, it will be necessary to create another thread that will be used to do communication with the `ebpf.plugin`.
    - The whole process communication between the two collectors will be done in this thread and it should be initialized inside it.
    -  We have basically two suggestion for this kind of communication, it will be either pipe or unix socket.
    - It is necessary to have a synchronization between apps.plugin and `ebpf.plugin` heartbeat, because the default value changes depending the hardware apps.plugin is running.
-    We will move from the function `main()` the main loop of the collector to another thread, after this apps.plugin will have two threads at least.
- The main loop needs to be changed, because it will also need to read information received from the `eBPF` collector before to send data to Netdata.
- Initially the data that will come from `eBPF` won't update the current charts, they will go to another chart for we verify that we are not missing information with `eBPF`.

**Comment by amoss** [comment]
The purpose of the meeting was to define a list of charts with eBPF data that will be added to Netdata. For each chart we should read:
* What will be in it
* How will it look
* What is the use-case for the chart

I don’t see that information, please add it to the issue.

**Comment by thiagoftsm** [comment]
@amoss I added it initially direct to the epic, but no problem I also bring it here.

**Comment by thiagoftsm** [comment]
> What will be in it

We won't remove any chart that was already inserted. We will convert the dimensions of the current global charts in new charts inside the apps.plugin. 
  
> How will it look

We will create two submenu inside Apps.plugins with the following charts: 

- `ebpf.syscall`: Here we will create charts that will demonstrate Files open, Files close, Files deleted, Calls to write, calls to read, bytes written, bytes read, Process created, thread created.
- `ebpf.net`: For while we will have only the bandwith per application.  
  
These chart will have the same dimensions of the other `Apps.plugin` charts.

>   What is the use-case for the chart

Our goal with these new charts it is to demonstrate for our users how the software running on the machine are consuming resources like IO, band with. We will also demonstrate for the users the errors that are happening in each operation to help identify the hardware health or software bug.

**Comment by amoss** [comment]
@thiagoftsm - I did not look there for it, but you are right it makes more sense in the epic. I'll answer there.

**Comment by ilyam8** [comment]
> inside Apps.plugins
> per application

Inside Applications, Groups and Users?

**Comment by thiagoftsm** [comment]
No @ilyam8 , I apologize, because I did not express correct. We are not going to touch Groups and Users, we will create additional charts that will bring additional information for Applications.

**Comment by thiagoftsm** [comment]
Case we decide to move forward with a `shared memory` between both collectors, the collectors will work as a producer ( `ebpf.plugin`) and consumer ( `apps.plugin`) problem. The shared memory won't have any data that will be parsed, we will work only with binary values. The values inside this shared memory will be stored inside `avl` trees to simplify `apps.plugin` search for the wanted values.

##### Apps.plugin

We will add to `apps.plugin` a new function that will create the shared memory before to enter in the main loop ( currently this loop starts at line `4162`). 

We will also add a new function to read data from shared memory, that will be called between the functions

```
calculate_netdata_statistics();
normalize_utilization(apps_groups_root_target);
```
present in the main loop.

Finally on apps.plugin we will add the functions to create the new charts proposed on https://github.com/netdata/netdata/issues/8727 .

##### eBPF.plugin

The `ebpf.plugin`  will continue sending the global charts direct to Netdata.

The plugin will have a new thread responsible to work with the shared  data. This thread will:
-  Open the shared memory after the `apps.plugin` initialized it.
-  Read the data from the hash table that stores the PID information inside kernel ring.
-  Insert values in the `avl` tree inside the shared memory.

The values inside the shared memory won't be only values read from kernel, we will also store the last time that `apps.plugin` read information from the shared memory.

[Top](https://github.com/netdata/netdata/issues/7873#issue-556161688)

**Comment by thiagoftsm** [comment]
Considering that eBPF runs only on Linux another possibility to do the integration is to use either `pipe` or `Unix socket` to do the communication. For both cases the following steps will be necessary:

##### Apps.plugin

1 - A new function outside the main loop to create either the `pipe` or the `unix` socket.
2 - We need another thread that will be responsible to receive the information from the PIPE.
3 - About the messages, case we use a pipe that will receive messages from ebpf.plugin, we will redirect `stdout` and `stderr`, including the global charts, to apps.plugin, the application messages will be parsed by `apps.plugin` while the global charts will be forward to Netdata. On the other hand, case we use unix socket, the global charts will continue sending direct to Netdata and I propose here we bing a binary protocol between the two plugins. 

##### eBPF.plugin

1 - Case we decide to go with Unix socket, it will be necessary to bring functions to create connection and send data  trough this channel.
2 - We need to create a function that reads information from kernel ring to user ring.
3 - Finally we need to call the functions to send the data.

[Top](https://github.com/netdata/netdata/issues/7873#issue-556161688)

**Comment by amoss** [comment]
Could you identify the benefits of implementing via:
1. Shared memory
2. IPC

I don't see any. The code in apps plugin still needs to be updated to integrate the new information so there is no benefit in preserving the original behaviour, or re-using what is already there.

I can see drawbacks in comparison to sharing the code (the solution is more work and it will be more fragile at run-time).

Unless there is a real trade-off here, we should just pick the simplest implementation and go with it.

**Comment by thiagoftsm** [comment]
> Could you identify the benefits of implementing via:
> 
>     1. Shared memory
>     2. IPC

The major benefits for both cases are two: 

1 - We do not need to parse the `apps_groups.conf` with eBPF plugin.
2 - In the kernel ring we have right now conditions to read a 16 bytes variable with the task name, this variable sometimes does not give the whole name of the application. To group the apps it would be necessary to read `/proc/PID/cmdline`.

I agree that these two benefits can be grouped in only one, but I decided to split to give more details.

> 
> I don't see any. The code in apps plugin still needs to be updated to integrate the new information so there is no benefit in preserving the original behaviour, or re-using what is already there.

We cannot avoid changes on `apps.plugin`, the two roads will result in some changes in this collector.

> I can see drawbacks in comparison to sharing the code (the solution is more work and it will be more fragile at run-time).
> 
> Unless there is a real trade-off here, we should just pick the simplest implementation and go with it.

I cannot find a big benefit to give you. Let us agree tomorrow the final road with the team.

**Comment by thiagoftsm** [comment]
After the last meeting with all options available, the Core team unanimous agree to move forward with the `shared library`.
