### ISSUE TITLE
Remove global declarations from header files.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7875]
##### Bug report summary

Netdata will not build with `-fno-common` set. This is because of the following global variable declarations in header files:

```
./libnetdata/health/health.h:47:SILENCERS *silencers;
./web/api/web_api_v1.h:32:char *api_secret;
./daemon/common.h:87:int netdata_ready;
./health/health.h:55:char *silencers_filename;
```

Please work out which translation these should be declared in.
* Move the declaration into the C file.
* Insert `extern` defs into any other C file that access it.

##### OS / Environment
All.

##### Netdata version
All.
 

##### Steps To Reproduce
Add the flag to the installer CFLAGS and rebuild. Observe the errors.

##### Expected behavior
No errors should result from the use of this flag.

**Comment by thiagoftsm** [comment]
It is ready waiting for review!
