### ISSUE TITLE
SQL queries statistics

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#7879]
##### Feature idea summary
In order to analyze behavior of mysql engine, it would be helpful to have a chart displaying how quick response mysql provides, including
* number of queries in processlist (**_Cp_**, can be also split into client queries and engine processes)
* time to fetch processlist (**_Tp_**), uS
* longest running query time withing running queries (**_Ts_**), S

This can help to identify moments when some mysql query slows down engine (causing response time on monitoring query and number of queued queries to grow)

For example, following query could be used for monitoring:
`select ID,TIME,COMMAND,State,MAX_MEMORY_USED,info from INFORMATION_SCHEMA.PROCESSLIST WHERE Info IS NOT NULL AND Info NOT LIKE "%PROCESSLIST%" ORDER BY TIME ASC;`

**_Tp_** should be measured directly, for example:
```
#assume mysql connection _connection_ is established
    t1=datetime.now()
#execute SQL query
    cursor=connection.cursor()
    cursor.execute(query)  #query is above mentioned one
#measure elapsed time
    t2=datetime.now()
    tp=t2-t1
```
Longest running query lifetime **_Ts_** can be read directly from last line of response and number of running queries **_Cp_** is equal to number of rows.

##### Expected behavior
Requested graph can be displayed in 'MySQL Queries' section. All three mentioned parameters could be displayed on same graph.

**Comment by ilyam8** [comment]
hi @ekexcello 

Could you share output from suggested request?

**Comment by ekexcello** [comment]
Hello @ilyam8 

Not sure that I understood you right.
Now I have only text files generated based on this query, in the form of table they would look like:

```
#Date-time		time to fetch, uS	number of rows	longest running query time, S
2020-01-28-12-29-57	3501			46		30
2020-01-28-12-30-12	36530			37		2
2020-01-28-12-30-27	10706			218		17
```
It would be heplful to have these table as a graph.

These columns are created every 15 seconds based on mentioned query output in the very way I described them. Query output lines looked like (column Info dropped here):

```
ID      TIME    COMMAND State           MAX_MEMORY_USED
7275799 2       Query   Updating        182520  
7275778 2       Query   Update          82136   
7275740 2       Query   Update          213168  
7275747 2       Query   None            213168  
7275635 2       Query   Creating table  8491216 
7275469 2       Query   Update          180472  
7275432 2       Query   Update          130272  
7273057 30      Query   Updating        125248 
```

In this example **_Ts_** will be 30, **_Cp_** will be 8.

Please tell me whether this information is what you asked for (I'm not sure that I answered your question with this).

**Comment by ilyam8** [comment]
@ekexcello

I'm trying to figure out which algorithm we need here.

- execute `select ID,TIME,COMMAND,State,MAX_MEMORY_USED,info from INFORMATION_SCHEMA.PROCESSLIST WHERE Info IS NOT NULL AND Info NOT LIKE "%PROCESSLIST%" ORDER BY TIME ASC;` query
- measure time to fetch the answer (`Tp`)
- go trhough list and find process with largest Time (`Ts`)
- cound number of processes in the list (`Cp`)

`Cp` can be split into several categories:
- client queries
- engine processes

Corrent? Am i missing something?

**Comment by ekexcello** [comment]
Hello @ilyam8 
Everything is correct.

Two small notes.
a) you can remove 'info' field from query, this is running query details, this information will be discarded anyway. You can make it more simple removing everything except ID and TIME.
b) no need to go through the list for finding largest time as list is ordered by time. You can even make things easier is you use `ORDER BY TIME DESC` instead of `ORDER BY TIME ASC` and read longest time from first line of output, not last one.

So query you can use is `select ID,TIME from INFORMATION_SCHEMA.PROCESSLIST WHERE Info IS NOT NULL AND Info NOT LIKE "%PROCESSLIST%" ORDER BY TIME DESC`, then you measure query fetch time (`Tp`), read longest process time `Ts` from first line of query result and count number of lines in the result (`Cp`).
Again, everything is correct in you algorithm description.

**Comment by ilyam8** [comment]
What permissions do we need for that query?

**Comment by ekexcello** [comment]
Required should be SELECT and PROCESS.
I tested running the query as 'netdata' sql user, it worked.

For now `Netdata` user requires following privileges for working with mysql (python) plugin:
`*.*:SELECT,SHOW DATABASES,PROCESS,USAGE,REPLICATION CLIENT`
This means that it has PROCESS and SELECT required for the mentioned query as far as I can guess, thus no additional privileges required.

**Comment by ilyam8** [comment]
> Cp can be split into several categories:

How to do it?

**Comment by ekexcello** [comment]
> > Cp can be split into several categories:

> How to do it?

Sorry, I slightly mislead you, not 'engine processes' but 'system processes'.

This requires additional column to be selected, especially, `User`. In that case you will have to count result lines containing `system user`, those will be system processes... However, this makes query process more complex as you have to read every line.

**Comment by ilyam8** [comment]
> However, this makes result parsing process more complex as you have to read every line.

doesnt sound like a problem at all

**Comment by ilyam8** [comment]
> The PROCESSLIST table provides information about which threads are running.

Link: [click](https://dev.mysql.com/doc/refman/8.0/en/processlist-table.html)

**Comment by ekexcello** [comment]
Hello @ilyam8 
Sorry for the delay. 
Yes, PROCESSLIST provides information that is in fact in this request, but it's much more convenient to find moments when processlist becomes long or some query runs abnormally long time using Netdata interface than scrolling through the log file, this was the reason for this request.

**Comment by ilyam8** [comment]
Hi, @ekexcello. I have a question

> time to fetch processlist (Tp), uS

Why do we need that? Why is that query so special we need its fetch time? Сan it take a long time?

**Comment by ekexcello** [comment]
Hello @ilyam8 
The reason for measuring time for fetching processlist is that from one side this is done by query and from another side, this doesn't require opening any (table) files. In same time, this query provides enough details to analyze status of other queries. Thus, in case time to fetch processlist is tiny but time of longest running query is several seconds or more, this would mean that there are either suboptimal user queries or mysqld requires some tuning (table cache, opening files etc). But in case time to fetch processlist itself is long (seconds), the performance problem already became a trouble with either too many queries running or some deadlocking occuring or mysqld main thread being blocked or something similar. Thus, time to fetch processlist itself is helpful also.

**Comment by ilyam8** [comment]
Ok, I see, thanks for the detailed response. We have [slow_queries](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Slow_queries), which indicates the system is overloaded (measured in real-time, not CPU time) or MySQL itself requires some tuning.

I am thinking that it probably makes sense to add fetch time for [all the queries we execute](https://github.com/netdata/go.d.plugin/tree/master/modules/mysql#requirements) 🤔
