### ISSUE TITLE
Improve updating docs (UPDATE.md) with per-method instructions

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#7881]
During the big overhaul of installation docs (#7841), @Ferroin pointed out some issues with the document about updating Netdata. The product team has recently informed me that we'll need a very concise and up-to-date document about updating Netdata agents to help users access Netdata Cloud once the current entrypoint (Nodes View) is disabled.

This document should contain specific update methods for the following methods:

- kickstart.sh
- kickstart-static64.sh
- Manual installation
- Packages
- Docker (?)

Austin had a few specific comments, which I've added below.

```
Netdata versions older than `v1.12.0-rc2-52` had a `netdata-updater.sh` script in the root directory of the source code,
which has now been deprecated. The manual process that works for all versions to get the latest commit in git is to use
the `netdata-installer.sh`. The installer preserves your custom configuration and updates the information of the
installation in the `.environment` file under the user configuration directory.
```

> Unless I'm mistaken, kickstart.sh works too, and is probably a safer update method as it will ensure that any new dependencies get pulled in. It also preserves user configuration just like netdata-installer.sh (it actually calls out to netdata-installer.sh to do the actual install).

```
If a newer version of Netdata is not available from the source you got it, we suggest to uninstall the version you have
and follow the [installation](README.md) instructions for installing a fresh version of Netdata.
```

> They should never need to go through this, they should be going through the regular package manager based workflow for their system to update the package.

**Comment by joelhans** [comment]
I'm going to remove myself as the assignee here and let @Ferroin take the lead on figuring out how to best address the concerns he brought up with these documents as he has time. I don't have the bandwidth nor expertise to test all the various possibilities here.

**Comment by joelhans** [comment]
Hey @Ferroin, after a call with product people today, I need to put a higher priority on this. Having a concise updating doc is crucial for the Cloud launch. I can take the lead editing the doc but I'll need your support to verify the instructions are correct and we're correctly documenting all the potential gotchas. I'll probably dive in next week.

**Comment by Ferroin** [comment]
> Hey @Ferroin, after a call with product people today, I need to put a higher priority on this. Having a concise updating doc is crucial for the Cloud launch. I can take the lead editing the doc but I'll need your support to verify the instructions are correct and we're correctly documenting all the potential gotchas. I'll probably dive in next week.

Just let me know when you've got questions or need a review. @prologic may also be a good resource for this as he's been helping a lot with the packaging and installer as well.
