### ISSUE TITLE
Software life cycle

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7884]
##### Feature idea summary
We are working to bring an eBPF collector that monitor the life cycle of processes running on the computer. This collector will monitor all IO operations, thread creations and software end.

- [x] A new configuration file for this collector
- [x] Convert the unique eBPF collector to 2 eBPF collectors: Kprobe and Kretprobe
- [x] Split the current chart that monitors `_do_fork` in charts with more explicit syscalls.
- [x] Create charts described at ```Expected behavior```
- [x] Logs when using developer mode
- [ ] Create alarms for each chart.

##### Expected behavior
To have a global vision of the software running on a specific computer, to reach this goal we will have the following charts:
- Open and close files
- I/O Operation ( Read and write)
- Delete files
- Process and thread creation
- Error during I/O operation (For while only count)
- Error to create process/thread
- Number of process running
- Process status
- % of process that can be created.

**Comment by thiagoftsm** [comment]
An example of configuration file for this specific collector:

``` 
Example:
[input def]
   app to monitor = netdata apps.plugin firefox*
[some specific error]
   app = netdata
   errno = 13
   fd = *
   arguments = *,*,4,*
   output chart = some name
   output dimension = some name
```

**Comment by amoss** [comment]
Merged.
