### ISSUE TITLE
Bluetooth interfering with netdata

### ISSUE THREAD

**Issue by fatt0ny** [netdata/netdata#7887]
##### OS / Environment
Archlinux
netdata: v1.19.0

##### Question summary
As soon as a device (Logitech harmony hub) connects via bluetooth to the host system i am experiencing the following  errors...

netfilter last collected secs = 00:00:11 ago 
ipv4 udperrors last collected secs = 00:00:11 ago
ipv4 tcphandshake last collected secs = 00:00:11 ago

These errors continue until the bluetooth device disconnects 

looking at the charts, all the graph have sporadic data collection during the errors. Netdata seems to only be receiving data every 10s or so

<img width="1393" alt="Screenshot 2020-01-25 at 19 10 41" src="https://user-images.githubusercontent.com/4146903/73318979-ee2dd300-4232-11ea-9f8f-7242e8ec2165.png">

As you can see on the left fo the chart the bluetooth device is connected & on the right i disconnect it.

I would be very grateful if you could offer me any advice in tracking down the root cause of this!
I am unsure if these are actual system errors or interference with netdata receiving the data it needs.
apart from the netdata errors i don't seem to be having any issues on the system during the error conditions.

Kind regards

**Comment by ilyam8** [comment]
Hi @fatt0ny 

Have you checked netdata error.log during the problem?

**Comment by Ferroin** [comment]
Note that this is probably not Netdata specific. The normal cause for gaps like this is that the system can't keep up with the incoming data that needs to be processed, which means that other software might be affected too.

Most likely root cause is a combination of lots of Bluetooth traffic from the connected device combined with efficiency issues in whatever drivers or software are handling this on the host system.

**Comment by fatt0ny** [comment]
Hi thanks for your input!

@Ferroin 
This makes sense, although there is only one bluetooth device connected & it is a hub for a remote control/keyboard, i would not have expected this to have high data needs. 


@ilyam8 
Here is an excerpt from the netdata log. I have also attached the full log. 

I connected the bluetooth device @ 20:17:16
[error.log](https://github.com/netdata/netdata/files/4130549/error.log)



`2020-01-29 20:17:16: alarm-notify.sh: WARNING: Cannot find file '/etc/netdata/health_alarm_notify.conf'.
2020-01-29 20:17:16: alarm-notify.sh: INFO: sent email notification for: Xserve ipv4.tcphandshake.ipv4_tcphandshake_last_collected_secs i>
2020-01-29 20:17:16: alarm-notify.sh: WARNING: Cannot find file '/etc/netdata/health_alarm_notify.conf'.
2020-01-29 20:17:16: alarm-notify.sh: INFO: sent email notification for: Xserve ipv4.udperrors.ipv4_udperrors_last_collected_secs is WARN>
2020-01-29 20:17:16: alarm-notify.sh: WARNING: Cannot find file '/etc/netdata/health_alarm_notify.conf'.
2020-01-29 20:17:16: alarm-notify.sh: INFO: sent email notification for: Xserve netfilter.conntrack_sockets.netfilter_last_collected_secs>
2020-01-29 20:17:45: netdata ERROR : PLUGIN[proc] : Cannot read file '/sys/class/power_supply/hid-00:04:20:fd:85:ed-battery/capacity' (er>
2020-01-29 20:17:46: netdata ERROR : PLUGIN[proc] : heartbeat missed 35000371 monotonic microseconds
2020-01-29 20:18:15: netdata ERROR : WEB_SERVER[static2] : PROCFILE: Cannot open file '/etc/netdata/.environment' (errno 2, No such file >
2020-01-29 20:18:26: netdata ERROR : PLUGIN[proc] : Cannot read file '/sys/class/power_supply/hid-00:04:20:fd:85:ed-battery/capacity' (er>
2020-01-29 20:18:27: netdata ERROR : PLUGIN[proc] : heartbeat missed 40002539 monotonic microseconds`

Thanks

**Comment by fatt0ny** [comment]
Should also point out that:

2020-01-29 20:17:45: netdata ERROR : PLUGIN[proc] : Cannot read file '/sys/class/power_supply/hid-00:04:20:fd:85:ed-battery/capacity'

specifically "00:04:20:fd:85:ed" is the mac address of the bluetooth device in question.

**Comment by Ferroin** [comment]
OK, can you try disabling the power supply collector by adding the following to your Netdata config:

```
[plugin:proc]
    /sys/class/power_supply = no
```

**Comment by fatt0ny** [comment]
@Ferroin 
This has stopped the errors!! & the graphs are receiving a continual flow of data

Any chance you could explain what that has done?

looks like the bluetooth device is reporting there is a battery where there should be none
Any reason to be concerned this error is causing other errors on the system?

Thanks, really appreciate your help, this has driven me mad for 2 weeks!!

**Comment by ilyam8** [comment]
I dont know what is going on there, but i think in general the problem with our internal `/proc` plugin, it is a part of the netdata daemon and if it hangs all netdata hangs.

other rel issue

https://github.com/netdata/netdata/issues/6741#issuecomment-527143969

**Comment by Ferroin** [comment]
@fatt0ny Netdata has a collector that queries state for power supply devices exposed by the Linux kernel which is enabled by default. Most battery-powered Bluetooth devices expose battery information through the same interface, so they'll get queried by the plugin as well. However, there are some Bluetooth devices which expose the interface to query a battery but don't actually implement it correctly, which can cause delays like this in code that tries to query this information.

Beyond that, it's the exactly as @ilyam8 said, the relevant collector is part of the proc plugin, which means it hangs the core when it hangs.

**Comment by fatt0ny** [comment]
Thank you both for your help.
Regards
