### ISSUE TITLE
Propose a log format for the new netdata agent database

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#7892]
##### Feature idea summary
 Propose a log format for the design for persistent metadata in the netdata agent database in #7891

**Comment by amoss** [comment]
The current details of the protocol in the `examples.md` file need to be extracted and merged with the details in `metata-log.md` to make a concrete proposal for the syntax of the new protocol. This document should explain the impact on `plugins.d`, in particular the need to convert to an incremental parser and the need to resolve the locking issues and leakage of host pointers.

The new proposed locking scheme does not need to be described in this document, we can groom it separately.

The review of this document should attempt to decide if these are the right changes to make - this is a proposal, the reviews need to check that it is understandable and doesn't contain typos and then the proposal needs to be groomed in a new task.
