### ISSUE TITLE
Discuss pros and cons of the new database log format

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#7893]
##### Feature idea summary
Discuss the pros and cons of the new database log format versus checkpointing and compaction. Examine the performance trade-offs and decide what will be the way forward.

**Comment by amoss** [comment]
This issue has become more complex that was understood at the beginning of the sprint. A new problem has emerged during the definition of these two approaches. We need to discuss the current locking scheme for the data-structures that will be manipulated in either of these two approaches. We have a proposal for a new locking scheme, however:
* It has not been validated - we do not know if it works.
* We do not understand the performance implications of implementing it.
* We don't know how much work it will be to fix the current behavior.

**Comment by amoss** [comment]
The work in the TODO list (in `examples.md`) will "complete" this task in the following sense:
* The description of compaction will be complete.
* The description of checkpoint is complete modulo the new locking proposal.

Although this is "complete" it is not done - and it is not clear how to reach a definition of done here as we need to understand the locking proposal.

**Comment by mfundul** [comment]
Reopening since it's only partially done.
