### ISSUE TITLE
ACLK Integration with cloud and WSS

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#7896]
This issue will deliver the actual ACLK connection based on the revised design.

- Handle the initial agent connection and reconnection on failures
  - Certificates for user / pass decryption
  - Challenge response with the cloud
- Handle the WSS upgrade code
  - Integrate with the libmosquitto library
    - Handle the mosquitto local fork build and own changes to the code
  - Integrate libmosquitto event loop to the agent
  - Add libwebsockets dependancy for MQTT packet encapsulation
- Stress testing (msg flood control) of:
  - Incoming requests from the cloud
  - Outgoing (pushed) events to the cloud
- Additional configuration options and sane defaults
- UTF-8 encoding support
- Investigation of agent side hashing to reduce agent - cloud link load

**Comment by stelfrag** [comment]
#### Update
- Handle the initial connection and metadata submission to the cloud when the agent enters a stable state.
  - Popcorning is used to monitor chart updates and the agent enters a stable state when no chart updates are received after X seconds
  - When the agent enters a stable state the on connect metadata is sent to the cloud

- Initial integration with the libmosquitto  / libwebsockets (wss) code is successful

#### Ongoing
- To further test disconnection and exponential backoff  retry delay
- UTF-8 encoding

**Comment by amoss** [comment]
Some parts of this cannot be completed without further synchronisation with the cloud team. I suggest that some of the good-to-have features should be delayed until after the release, specifically:
* The agent-side hashing of collector state changes
* Additional configuration options for parameter tuning.

**Comment by stelfrag** [comment]
#### Update (things actually implemented via PR #8139)

- Support for popcorn-ing at connect
- Add delay function for reconnect (not integrated yet / awaiting for wss merge and callback)
  - Uses exponential delay + 0-999 ms jitter (with a maximum of 1024 seconds delay)
- MQTT build in exponential backoff delay to 1024 seconds
- Integrate chart detection (add and delete)
- Integrate alarm reload detection (disables chart / alarm updates while reloading)
- Integrate alarm trigger (health_log)
- Detect collector addition / deletion. Triggers on_connect metadata
- JSON payload parse / tuning
- Encoding added
- Add debugging messages

#### Todo (handle with a new PR or more) 
- Handle the initial agent connection using
  - Cloud Challenge 
  - Fetch user/pass
  - Open MQTT/WSS link
- Handle reconnections using
  - Exponential backoff delay and as above reinstate the connection by doing:
    - Cloud Challenge 
    - Fetch user/pass
    - Open MQTT/WSS link

**Comment by amoss** [comment]
Code is reviewed, tested and merged onto the feature branch. Will handle merging the feature branch shortly.
