### ISSUE TITLE
Check the final state / integration of the host labels tasks.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7898]
#### Summary

The work for the host labels was split into many pieces, and each one was tested individually. We need to run through a final series of tests to check that they all integrate successfully and demo the finished result.

#### Expected Outcome

Each of the individual cases for host labels needs to work:
* Config file specified labels
* Auto-detected labels
* Labels supplied through docker
* Visibility of the labels through the web API.
* Labels passed over the streaming protocol.

**Comment by amoss** [comment]
Assigning this to Vlad as he has checked the cases and will take the demo in the review next week.

**Comment by vlvkobal** [comment]
Everything is working as expected.
