### ISSUE TITLE
Docker files for dev / testing.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7899]
#### Summary

One of the problems that we face in reviewing PRs is that there are many complex configurations for Netdata that are difficult to setup and use for testing. The current approach is to use a set of VMs that contain various OS configurations, Netdata installs and all of the other tools that we need for a full monitoring stack. The problem with this is that it is not robust, easy to maintain and does not allow repeatable testing during development.

We can overcome these issues with a custom version of the Dockerfiles that are used for packaging Netdata for different target environments. The main differences between our use-cases and packaging are:

* Must support incremental builds for dev - not always a clean install.
* Must support debugging / valgrind and other tools.
* Must support injection of partial configuration files for a predictable setup.
* Must be usable in docker-compose to create multi-node configurations.

### Expected outcome

Support the following configurations for dev/testing:

* Simple single Netdata installation (i.e. the basic one-node case).
* Master/slave configurations with multiple Netdata nodes.
* ACLK testing configuration with custom fork, VerneMQ etc.
* Monitoring stack with Prometheus / Grafana and other configs that we need to test exporting on.

**Comment by amoss** [comment]
Uses a re-written version of the Dockerfiles from #7754 - will close that and clean up.

**Comment by Ferroin** [comment]
This is on the list of things to do in the near future for the SRE team once we have the binary packaging stuff working correctly.

**Comment by amoss** [comment]
That sounds good. I have a half-written version and I need it for a task in this sprint so my plan is to make it work and then hand it over for you guys to polish / maintain.

**Comment by prologic** [comment]
We _should_ be able to do this fairly easily. I've typically been doing this a fair bit already:

```sh
cat > test.sh <<EOF
#!/bin/sh

# Install Dependencies
apk add --no-cache -U alpine-sdk bash curl libuv-dev zlib-dev util-linux-dev libmnl-dev gcc make git autoconf automake pkgconfig python logrotate

# Build
./netdata-installer.sh
```

And:

```sh
$ docker run -i -t -v $PWD:/netdata -w /netdata alpine /bin/sh ./test.sh
```

So unless you need something drastically more complicated; I _think_ we can do this now.

I'm also a little sad that the `Dockerfile` for our upstream `netdata/netdata` Docker Image lives in `./packaging/docker/` with a bunch of complicated scripts and docs for when all you want to do is (_sometimes_) is `docker build -t prologic/netdata .` and `docker run ... prologic/netdata` quickly.

**Comment by amoss** [comment]
Please don’t close this issue until I have finished working on it. The linked PR reruns the netdata installer instead of renaming the build incrementally and it does not allow injection of partial configuration.

**Comment by prologic** [comment]
> Please don’t close this issue until I have finished working on it. The linked PR reruns the netdata installer instead of renaming the build incrementally and it does not allow injection of partial configuration.

Sorry about this :) -- I was going to reach out to you actually to see what more we can/should do here. When we both have some time let's discuss in Slack?

**Comment by amoss** [comment]
I've connected the PR from the cross_hosts branch that you've already seen. I think that the PR that you merged was a little bit too simplified:

* We need multiple user-lands inside the docker containers (not just Alpine)
* Caching the netdata-installer step is not sufficient.

Take a look at the pair of Debian Dockerfiles to see what I'm trying to do - the `make install` step is the one that should be redone for an incremental build (with everything up to there sitting in the Docker cache). The two advantages are:

* This only takes about 15s (which is about the minimum for our current Makefile).
* Only the build targets are copies over, so the installed target (e.g. config) is not touched.

**Comment by amoss** [comment]
The next step that I will look at is getting the CentOS version into the same state as Debian. I could not do this on the mac as there is a problem with the base CentOS image on Docker For Mac (it seems to hang for no reason). Now that I'm back in front of a linux machine I can fix this up.

**Comment by prologic** [comment]
> We need multiple user-lands inside the docker containers (not just Alpine

Why do you need this specifically? If we can do CI test runs against all the things we care about then is it enough that your build on one works sufficiently?

**Comment by prologic** [comment]
> The next step that I will look at is getting the CentOS version into the same state as Debian. I could not do this on the mac as there is a problem with the base CentOS image on Docker For Mac (it seems to hang for no reason). Now that I'm back in front of a linux machine I can fix this up.

Hmmmm 🤔 I'm still of the opinion that there's quite a bit of overlap here. We have pre-built images with all "build dependencies" we use in CI today in netdata/helper-iamges

See my comment above however about "Why?"; Maybe I'm missing something important here?

**Comment by prologic** [comment]
> the make install step is the one that should be redone for an incremental build (with everything up to there sitting in the Docker cache)

Can you elaborate on this a bit?

**Comment by amoss** [comment]
> > We need multiple user-lands inside the docker containers (not just Alpine
> 
> Why do you need this specifically? If we can do CI test runs against all the things we care about then is it enough that your build on one works sufficiently?

* If we are fixing a bug that only shows up on a particular distro then we need to do the dev builds in that that distro.
* If we are doing dev that requires a certain user-land (e.g. the host-labels work recently, or collectors that only exist on a certain distro) then we need to build against that user-land.

**Comment by prologic** [comment]
> * If we are fixing a bug that only shows up on a particular distro then we need to do the dev builds in that that distro.
> * If we are doing dev that requires a certain user-land (e.g. the host-labels work recently, or collectors that only exist on a certain distro) then we need to build against that user-land.

I _suspected_ as much and I _think_ you can re-use our `netdata/package-builder` images for this purpose. Let me think about though..

**Comment by amoss** [comment]
> Can you elaborate on this a bit?

Try:
```
cd build_external
docker build -f clean_install_debian_buster.Dockerfile .. -t debian_buster_clean_install:latest
docker build -f make_install_debian_buster.Dockerfile .. -t debian_buster_clean_install:latest
echo >> ../daemon/main.c     # Simulate edit step
docker build -f make_install_debian_buster.Dockerfile .. -t debian_buster_clean_install:latest
echo >> ../daemon/main.c     # Simulate edit step
docker build -f make_install_debian_buster.Dockerfile .. -t debian_buster_clean_install:latest
echo >> ../daemon/main.c     # Simulate edit step
```
The unusual thing is the way that the image is built from itself applying only the latest changes to the source tree. Note what gets rebuilt inside the container and what doesn't.

**Comment by amoss** [comment]
The estimate for this one is after the fact and very different to what we would have estimated in advance.
* Scope has been reduced - monitoring stack and valgrind/debugging will need to wait for a further iteration.
* It took about two days to implement the functionality in docker.
* It took took at least another three days to get the ACLK working in the test environment [this was not anticipated/planned].
* Reviews should be easy :)
