### ISSUE TITLE
Updates via `netdata-updater.sh` or the kickstart scripts don't remove files left over from the previous installation.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#7901]
When using our install scripts or the automatic updater script, we blindly install on top of what is already there, and then don't remove old files that were part of the previous installation but aren't included in the new installation.

Aside from potentially causing problems for users, this means that we need to be careful when we remove files from the installation process, especially collectors, to ensure that we don't use the old files at all, often requiring extra code and thus increasing the complexity of some components.

The correct fix here is probably to save off a list of everything we install together with timestamps and checksusms, and then on update we remove any files not in the list from the previous install that aren't listed in the new install where the checksums and timestamps match what's on disk.

**Comment by prologic** [comment]
> The correct fix here is probably to save off a list of everything we install together with timestamps and checksusms, and then on update we remove any files not in the list from the previous install that aren't listed in the new install where the checksums and timestamps match what's on disk.

This is precisely how the [CRUX](https://crux.nu) package manager works :) So +1

**Comment by Ferroin** [comment]
> > The correct fix here is probably to save off a list of everything we install together with timestamps and checksusms, and then on update we remove any files not in the list from the previous install that aren't listed in the new install where the checksums and timestamps match what's on disk.
> 
> This is precisely how the [CRUX](https://crux.nu) package manager works :) So +1

Not just CRUX, but almost all work this way, with varying degrees of verification that the user didn't modify the files that are to be removed before removing them.

**Comment by Ferroin** [comment]
Closing this, as it is (mostly) a non-issue now for newer installs and it’s not really possible for us to retrofit old installs to avoid the issue.
