### ISSUE TITLE
Properly handle DM multipath on Linux in `system-info.sh` when collecting disk sizes.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#7904]
Currently, we completely ignore device-mapper devices on Linux when calculating disk sizes using the contents of `/sys/block`. This is usually a good thing, but it means that we overreport disk sizes on systems that use multipathing.

For at least the case of DM multipath (the common case), we can work around this by parsing the DM table for each DM target to see if it's a multipath target, and if so use the target device and ignore the component devices.

**Comment by Ferroin** [comment]
To further clarify, this is an issue with the system-info.sh script, so it specifically affects data as reported on the cloud.

**Comment by ilyam8** [comment]
Closing because we can't really fix this issue because we have no access to systems with DM multipath (setup a lab is also somewhat complicated). We will reopen and fix the issue if there will be a user that has a system with DM multipath and want us to help.

**Comment by Ferroin** [comment]
Switched closure reason, this is not completed, it’s not planned for the time being.
