### ISSUE TITLE
ACLK - Packaging and deploying the custom fork of libmosquitto

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#7906]
##### Feature idea summary
In order to deploy the ACLK feature into production we are using a custom version of libmosquitto that has been upgraded to support our use-case (wss+MQTT). This currently exists as a repo that we have forked. The long-term plan is to push the changes upstream and improve the external library.

In the short-term we must deploy our custom version to be able to establish the ACLK. This needs to be a custom build step that:

* Pulls in the latest version of the forked library (netdata/mosquitto).
* Compiles a static library.
* Compiles netdata to include the static library.

Issue #7740 will result in:

* Instructions for pulling the fork / building the library.
* Necessary changes to autotools / CMake.

##### Expected behavior

All Netdata installation options (the installer, kickstart, binary packages) need to be updated to include these new changes and check that we can deploy them to supported platforms. 

These changes are required to allow deployment of the ACLK for the February release.

**Comment by underhood** [comment]
Overview:
- Fork of mosquitto located at (netdata/mosquitto) that needs to be pulled into `mosquitto` folder.
``` text
git clone ssh://git@github.com/netdata/mosquitto mosquitto/
```
- it has to be built as static library. Currently achieved manually by:
``` text
cd mosquitto/lib && make
```
Which will build mosquitto/lib/libmosquitto.a for the build process to use (this will be the core team responsibility to update the cmake and autotools build system to use that library).

**Comment by amoss** [comment]
This approach has a problem - it assumes that the installer is being run by a github user who has their key accessible to sshd. This is not (necessarily) true for all install methods. Take a look at `install_go` in `netdata-installer.sh` to see how to download it without needing a github key.

**Comment by Ferroin** [comment]
Adding @prologic and myself to this, as special consideration will potentially be needed for the package builds and docker images, as well as handling of prepping the compiled static library for download.. @underhood Once you've gotten a complete build process pinned down, please ping @prologic and me either here on GitHub or on Slack so we can start on the CI parts for this.

**Comment by Ferroin** [comment]
Based on limited discussion, this is going to quickly get complicated since we have to support FreeBSD, and a vast majority of CI platforms seem to think that BSD just doesn't exist. I'll be discussing this later today with the SRE team and once we've figured out how we want to handle this I'll comment here again with info on how we're moving forwards.

**Comment by prologic** [comment]
> Based on limited discussion, this is going to quickly get complicated since we have to support FreeBSD, and a vast majority of CI platforms seem to think that BSD just doesn't exist. I'll be discussing this later today with the SRE team and once we've figured out how we want to handle this I'll comment here again with info on how we're moving forwards.

As discussed in our sync today; I _think_ we can do this easily with just regular SSH/Shell to a BSD VM / Machine. No need to have a CI that supports BDS natively. Also this means Github Actions works just fine if we do it this way.

Also let's be sure to document and properly decide one way or another which CI system we're going to end up using and do a decision matrix.

**Comment by Ferroin** [comment]
https://github.com/netdata/mosquitto/pull/2 Handles part of the requirements on the libmosquitto side. It only takes care of Linux (but it does handle ARM correctly). I'll be doing separate PR's there for the FreeBSD and macOS parts.

The current approach on that side requires creating a release for our fork of libmosquitto, which will then trigger the GHA workflow added by the aforementioned PR, which builds and then attaches to the release the required artifacts.
