### ISSUE TITLE
Audit for errors during system calls

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7908]
### Target
* Audit of errors during system calls

### Why?
* Logs provide context to performance metrics 

### What?
* Utilise eBPF collector to collect error logs which are generated by syscalls (i.e. functions inside the kernel). 

* Capture Errors 
 -permission denied 
 -no such file or directory

* Associate errors with additional information 
    -PID = process id 
    -errno = retuned error (convert number to text error description based on libc mapping)
    -file descriptor
    -Syscall Arguments

* Specify what kind of errors users want to see (configuration file)
    -Specify which apps and the type of errors we need to report.

* External benchmarking
   -Compare Netdata vs Dtrace on error reporting.

**Comment by thiagoftsm** [comment]
An example of configuration file for this specific collector:

``` 
Example:
[input def]
   app to monitor = netdata apps.plugin firefox*
[some specific error]
   app = netdata
   errno = 13
   fd = *
   arguments = *,*,4,*
   output chart = some name
   output dimension = some name
```

**Comment by ilyam8** [comment]
@thiagoftsm if that Epic is relevant, please move it under netdata/product.

**Comment by thiagoftsm** [comment]
I will talk with @manos-saratsis about this, right now we have different priorities.
