### ISSUE TITLE
The package uuid-dev (or libuuid-devel) has to be installed.

### ISSUE THREAD

**Issue by Androz2091** [netdata/netdata#7919]
##### Question summary
I'm getting the following error when I run the installer:
```js
Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues
```
I tried to run the installer like this:
`./netdata/netdata-installer.sh --libs-are-really-here`
But it doesn't work.

When I run `apt-get install uuid-dev zlib1g-dev`, it shows the following:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
uuid-dev is already the newest version (2.29.2-1+deb9u1).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-5).
The following packages were automatically installed and are no longer required:
  net-tools python3-prettytable
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
How can I fix this problem? I setup a lot of VPS with Netdata on Debian 9 and this never happened to me...
And of course, I read the other issues that seemed to be about the same, but I couldn't find anything that could help me...

##### OS / Environment
Debian 9.11

##### Expected results
Netdata should be installed.

**Comment by prologic** [comment]
Hi @Androz2091 !

Can you try to run `packaging/installer/install-required-packages.sh | tee install-deps.log` and if that fails for any reason attach the `install-deps.log` file here in your next comment? :)

**Comment by Androz2091** [comment]
It shows the following help page:

<img width="731" alt="Capture d’écran 2020-01-30 à 17 13 42" src="https://user-images.githubusercontent.com/42497995/73467657-e7fb3c00-4383-11ea-8230-fb3b2a23480f.png">

**Comment by prologic** [comment]
Sorry I told you the wrong thing 🤦‍♂️

Try this:

```sh
./packaging/installer/install-required-packages.sh --dont-wait
```

**Comment by prologic** [comment]
I'm not even sure to be honest why our usage of the script shows everything as optional; but we only print a help/usage message when no arguments are passed. @Ferroin ?

**Comment by Ferroin** [comment]
> I'm not even sure to be honest why our usage of the script shows everything as optional; but we only print a help/usage message when no arguments are passed. @Ferroin ?

I think the intent was that this could be used after initial setup of Netdata to pull in the packages for some specific collector that may now be needed on the system. I agree that the base (`netdata`) part should probably be non-optional and just be enabled by default as well.

**Comment by Androz2091** [comment]
Here is the result for `./packaging/installer/install-required-packages.sh --dont-wait`:
```
Loading /etc/os-release ...

/etc/os-release information:
NAME            : Debian GNU/Linux
VERSION         : 9 (stretch)
ID              : debian
ID_LIKE         :
VERSION_ID      : 9

We detected these:
Distribution    : debian
Version         : 9
Codename        : 9 (stretch)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2

 > Checking if package 'autoconf-archive' is installed...

All required packages are already installed. Now proceed to the next step.
```

**Comment by prologic** [comment]
@Androz2091 Okay... Is there anything special about your Debian 9 system I should know about? I'll try to repro this locally.

**Comment by Androz2091** [comment]
Here are some other informations about the VPS:
```
CPU : 8 vCore @ 2,40GHZ+
RAM : 8Go DDR3
HDD : 50Go RAID 10
Connection : 200 Mbps
Datacenter : Paris Nanterre (PND)
Technology : KVM
```

**Comment by prologic** [comment]
I mostly meant if you had tweaked or customized the Debian 9 system in any interesting ways. But if you haven't; that's okay I'll just repro with a clean Debian 9 VM and see what's going on here. Thanks!

**Comment by J3K** [comment]
`apt install libuv1-dev`

**Comment by Androz2091** [comment]
It's a debian server...

**Comment by prologic** [comment]
> Sorry I told you the wrong thing 🤦‍♂️
> 
> Try this:
> 
> ```shell
> ./packaging/installer/install-required-packages.sh --dont-wait
> ```

@Androz2091 Sorry I _think_ I told you the wrong thing; there's actually more arguments to be passed to get the right dependencies installed.

Can you try this:

```sh
./packaging/installer/install-required-packages.sh --dont-wait --non-interactive netdata
```

Which _should_minimally install the dependencies required to build the agent. Let me know how that goes!

**Comment by Androz2091** [comment]
I ran the `install-required-packages.sh` script with the updated args and it worked! Then, I ran the `netdata-installer.sh` script and it worked too. Thank you very much!

**Comment by prologic** [comment]
> I ran the `install-required-packages.sh` script with the updated args and it worked! Then, I ran the `netdata-installer.sh` script and it worked too. Thank you very much!

You're very welcome! I'm glad it worked for you in the end! 😀
