### ISSUE TITLE
How to debug slave/master config that is not working or logging anything at all?

### ISSUE THREAD

**Issue by alexandernst** [netdata/netdata#7928]
##### Question summary

I have a simple slave/master setup. The config is as follows:

**master netdata.conf**

```
[global]
    run as user = netdata
    web files owner = root
    web files group = netdata

[web]
    default port = 19999
    allow connections from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow dashboard from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow badges from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow streaming from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow netdata.conf from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow management from = localhost

[registry]
    enabled = yes
    registry to announce = http://172.16.19.27:19999
```

**master stream.conf**

```
[e63945ee-a1aa-44b5-9f50-05536454031e]
    enabled = yes
    default history = 3600
    default memory mode = save
    health enabled by default = auto
    allow from = *
```

**slave netdata.conf** 

```
[global]
    run as user = netdata
    web files owner = root
    web files group = netdata

    memory mode = none

[web]
    mode = none

    default port = 19999
    allow connections from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow dashboard from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow badges from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow streaming from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow netdata.conf from = localhost fd* 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 169.254.* 192.168.*
    allow management from = localhost

[registry]
    enabled = no
    registry to announce = http://172.16.19.27:19999
```

**slave stream.conf**

```
[stream]
    enabled = yes
    destination = 172.16.19.27:19999
    api key = e63945ee-a1aa-44b5-9f50-05536454031e
```

The problem that I'm having is that the master doesn't seem to be receiving the data from the slave (or maybe the slave isn't trying to send anything?). I have no clear way to say what's actually going on. After restarting `netdata` service (`systemctl restart netdata`) on both the master and the slave, and monitoring the log files `/var/log/netdata/(access | debug | error).log` I was expecting to see anything related to streaming (`| grep -i stream`), but I found nothing at all. It's like neither the slave nor the master weren't even trying to stream / receive a stream.

How can I further debug in order to see what is actually going on?

##### OS / Environment

I'm running on a Debian 10. Netdata is v.1.19.0 installed from the package cloud repository.

##### Component Name

N/A

##### Expected results

N/A

**Comment by stelfrag** [comment]
Hi @alexandernst 

Could you check the permissions on the `stream.conf` on the slave and make sure it is in the correct
directory?

Assuming a default installation path, it should be   `/etc/netdata/stream.conf`

Your configuration should at least give STREAM error messages on the slave (even if the master is down). For example
```
STREAM_SENDER[debian10] : STREAM debian10 [send to 172.16.19.27:19999]: connecting...
```

**Comment by alexandernst** [comment]
Oh, strange. I just checked my log again and now I see some more details. Mainly:

```
2020-01-30 19:29:50: netdata INFO  : MAIN : CONFIG: cannot load user config '/etc/netdata/stream.conf'. Will try stock config.
2020-01-30 19:29:50: netdata INFO  : MAIN : Host 'slave' (at registry as 'slave') with guid 'be072d8e-434f-11ea-95fd-0a1f9e8300fd' initialized, os 'linux', timezone 'Etc/UTC', tags '', program_name 'netdata', program_version 'v1.19.0', update every 1, memory mode none, history entries 3996, streaming disabled (to '' with api key ''), health disabled, cache_dir '/var/cache/netdata', varlib_dir '/var/lib/netdata', health_log '/var/lib/netdata/health/health-log.db', alarms default handler '/usr/libexec/netdata/plugins.d/alarm-notify.sh', alarms default recipient 'root'
```

Current permissions (`/etc/netdata/stream.conf`)

```
-rw-r-x---  1 root root  346 Jan 30 19:23 stream.conf
```

**Comment by stelfrag** [comment]
Ok the netdata user cannot read the `stream.conf`

Please try

`sudo chown root:netdata /etc/netdata/stream.conf`
`sudo chmod u=rw,g=r /etc/netdata/stream.conf`

and restart the slave

**Comment by alexandernst** [comment]
Great! We're making progress. I applied the same permissions to the master and now I see that the slave is sending data to the master. Now it seems that both machine have the same GUID and thus the master is refusing to receive the data (¿?)

```
netdata ERROR : STREAM_RECEIVER[slave,[172.16.19.233]:13334] : STREAM slave [receive from 172.16.19.233:13334]: denied to receive metrics, machine GUID [be072d8e-434f-11ea-95fd-0a1f9e8300fd] is my own. Did you copy the master/proxy machine guid to a slave?
```

Is that something common? (both machines are AWS instances launched from the same template and at the same time)

**Comment by alexandernst** [comment]
Oh... I just saw the part of the docs that talks about the `/var/lib/netdata/registry/netdata.public.unique.id`

**Comment by stelfrag** [comment]
The error is due to the API key that is on the stream.conf (on master and slave) and as the error suggests it is the one of the master. 

At the command line, you can generate a new one by typing

`uuid`

and use that at the appropriate place in the `stream.conf` in the slave and master

Restart both and you should be fine

**Comment by alexandernst** [comment]
Great! One last question. Now I see my slave twice:

![slave_netdata_dashboard_y_install_netdata_sh_—_expressjs-ami](https://user-images.githubusercontent.com/89727/73484677-07a15d00-43a2-11ea-9920-9af7cfc0784b.png)

Why is that happening?

**Comment by alexandernst** [comment]
Oh, nevermind, it was just a cache problem. I think I'm good now :)  Thank you for the excelent support!
