### ISSUE TITLE
./packaging/installer/install-required-packages.sh with no arguments prints usage/help

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#7930]
##### Bug report summary

Discovered in #7919 I _believe_ this to be either a bug or a bug in the usage/help string of the script `./packaging/installer/install-required-packages.sh`.

```sh
prologic@Jamess-iMac
Fri Jan 31 07:14:42
~/NetData/netdata
 (master) 0
$ dki -t --rm -v $PWD:/netdata -w /netdata centos:7 /bin/sh -c './packaging/installer/install-required-packages.sh'
OPTIONS:
.
.
.
If you don't supply the --dont-wait option, the program
will ask you before touching your system.
```

##### OS / Environment

Any

##### Netdata version

Any

##### Component Name

area/packging

##### Steps To Reproduce

1. Run `./packaging/installer/install-required-packages.sh` without any arguments

##### Expected behavior

The script should continue without argument as described in the help/usage output and prompt the user to continue. Currently it just exits with `1`. I'm not sure why.

**Comment by amoss** [comment]
@prologic We don't need to triage this :)

**Comment by prologic** [comment]
You are right 🤣 We sorta know what we're doing right 😛

**Comment by Ferroin** [comment]
We may want to consider this eventually, but the given use-case is not really something we support anyway, so closing it as wontfix  for the time being.
