### ISSUE TITLE
Smoke Tests for Agent Plugins

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#7931]
##### Feature idea summary

To prevent regressions like what occurred in #7632 and fixed in #7923 we should do some basic validation and smoke testing of the NetData Agent Plugins as we do for the NetData Agent itself.

Ensure they run at a basic level and appear to operate normally. This might require hitting an API endpoint or querying for a metric to ensure this or simply introspecting the agent's logs.

We want to be sure that in normal NetData Agent operations that plugins work correctly.

There _might_ be other cases where we _might_ break plugin functionality and doing some basic smoke testing should hopefully catch/prevent a lot of those.

##### Expected behaviour

We don't break plugins :)

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
