### ISSUE TITLE
Cent OS Dependency problem

### ISSUE THREAD

**Issue by alfredvalderrama98** [netdata/netdata#7936]
##### Question summary

Press ENTER to run it > 
yum install Judy-devel autoconf-archive autogen libmnl-devel libuuid-devel libuv-devel lz4-devel 
Last metadata expiration check: 0:02:23 ago on Fri Jan 31 10:25:00 2020.
No match for argument: Judy-devel
No match for argument: autoconf-archive
No match for argument: autogen
No match for argument: libmnl-devel
No match for argument: libuv-devel
Error: Unable to find a match: Judy-devel autoconf-archive autogen libmnl-devel libuv-devel

##### OS / Environment
CentOS 8
##### Component Name
Judy-devel autoconf-archive autogen libmnl-devel libuuid-devel libuv-devel lz4-devel
##### Expected results
Im expecting that it will automatically install. But those packages listed cannot found in any centos repositories. Please fix this error.

**Comment by prologic** [comment]
Duplicate of #6967 and fixed by #7890 and #7918 

Please help me test the fixes :) These PRs will be merged soon!
