### ISSUE TITLE
add feature flag for new dashboard release

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata#7940]
##### Feature idea summary
We want to release new Dashboard but still have an option to fallback to old version, in case of bugs or bad experience.

##### Expected behavior
- we should add a new flag (feature flag) to Netdata, called `use new dashboard`
- flag should be OFF by default, at least right now, until we test it internally
- when that flag is ON, requests to `index` (`/`) in web server should point to `index-new.html` instead of `index.html`

When we remove 2 versions, we'll then switch to more friendly names

**Comment by thiagoftsm** [comment]
Before I start to create the PR that will bring this new feature, I will give a suggestion, can we use a more generic variable name instead `use new dashboard`? Because case we update the dashboard again next year, we won't have condition to select the dashboards only based in the word `new`, unless we are sure we will have only two dashboards running in parallel forever.

**Comment by jacekkolasa** [comment]
I was thinking that this flag will last for very short time, when we'll confirm that it's experience is better, we'll remove the old version. Especially considering changes with SSO.
But, that doesn't stop us from having different name, of course :) Do you have any suggestions? `use react dashboard`?

**Comment by thiagoftsm** [comment]
I loved this last suggestion(`use react dashboard` ), I will move in front with it. :)

**Comment by jacekkolasa** [comment]
@cakrit @cosmix me and @amoss think that the feature flag should first be turned off by default, so we can test the new Dashboard internally first, and if it will work ok, release it as default on. Do you agree?

**Comment by thiagoftsm** [comment]
> @cakrit @cosmix me and @amoss think that the feature flag should first be turned off by default, so we can test the new Dashboard internally first, and if it will work ok, release it as default on. Do you agree?

Yes I agree, we are doing the same thing with eBPF collector, this is the safest approach.
Let us move in front with this! :)

**Comment by cosmix** [comment]
I agree @jacekkolasa and @amoss

**Comment by amoss** [comment]
@jacekkolasa: Please update the expected behavior in the issue description.

**Comment by amoss** [comment]
After reviewing the results we have decided to take a different approach on the feature flag.
