### ISSUE TITLE
Pfsense\freebsd sysctl(vfs.bufspace...) failed: Cannot allocate memory (errno 12, Cannot allocate memory) 

### ISSUE THREAD

**Issue by kdy1968** [netdata/netdata#7947]
##### Bug report summary

```bash
system.ram chart not available
2020-02-02 07:46:13: netdata ERROR : PLUGIN[freebsd] : FREEBSD: sysctl(vfs.bufspace...) failed: Cannot allocate memory (errno 12, Cannot allocate memory)
2020-02-02 07:46:13: netdata ERROR : PLUGIN[freebsd] : DISABLED: system.ram chart
2020-02-02 07:46:13: netdata ERROR : PLUGIN[freebsd] : DISABLED: system.ram module
```

##### OS / Environment
```
FreeBSD venus.mecury.local 11.3-STABLE FreeBSD 11.3-STABLE #80 54b0ad59490(RELENG_2_4_5): Sat Feb  1 17:22:58 EST 2020     root@buildbot2-nyi.netgate.com:/build/ce-crossbuild-245/obj/amd64/IuZS8Bew/build/ce-crossbuild-245/sources/FreeBSD-src/sys/pfSense  amd64
1103507
```

##### Netdata version

netdata v1.19.0

 

##### Steps To Reproduce

1. ...removed and re-added netdata, upgraded from freebsd 11.2 to 11.3
2. ...

##### Expected behavior
system.ram chart to be displayed in console

**Comment by ilyam8** [comment]
i see the problem in the freebsd.plugin @vlvkobal

**Comment by amoss** [comment]
@ilyam8 When you say that you can see the problem could you please provide a little more information - can you see a bug in the code or do you mean that you can replicate the problem on a similar system?

**Comment by ilyam8** [comment]
@amoss, no i cant replicate the problem (didnt try). @thiagoftsm assigned sre team guys.

I see in the OP

> 2020-02-02 07:46:13: netdata ERROR : PLUGIN[freebsd] : FREEBSD: sysctl(vfs.bufspace...) failed: Cannot allocate memory (errno 12, Cannot allocate memory)


and assume that correct person is @vlvkobal

**Comment by amoss** [comment]
I think the question is who can try to replicate the problem most effectively - @vlvkobal is more familiar with that part of the code but may not have a pfsense configuration for testing. We need to replicate the problem to check that it is a bug and not part of the configuration on the original system. Who can try a pfsense configuration most effectively (because they already have one available) ?

**Comment by kdy1968** [comment]
@vlvkobal , @amoss I loaded up a VM with freebsd 11....netdata worked as expected
loaded up vm with pfsense 2.4.4, it shows the same issue, so it appears pfsense is blocking access  to these stats, where/how does the system.ram dashboard pull the ram stats?

**Comment by Ferroin** [comment]
I'm not 100% certain about this, but I'm pretty sure that pfSense runs with significantly more stringent security settings than the default ones used by FreeBSD (11 or 12). I suspect that's part of why this issue only seesm to crop up on pfSense. I'm going to try and find some time to play around with the security settings in my own FreeBSD VM's to try and reproduce this outside of pfSense.

**Comment by vlvkobal** [comment]
Needs reproduction at first.

**Comment by vlvkobal** [comment]
@kdy1968 could you check for _"Cannot allocate memory"_ messages in your `error.log`. Do you have a lot of them? Please try increasing `memorylocked` resource limit (look at https://github.com/netdata/netdata/issues/8707#issuecomment-675364099).

**Comment by vlvkobal** [comment]
What version of `json-c` is installed on your machine? Please upgrade it to 0.14. My FreeBSD 11.3 VM with working Netdata v1.24.0-123-ga11d33bb reports
```
# pkg info json-c
json-c-0.14
Name           : json-c
Version        : 0.14
```

**Comment by kdy1968** [comment]
yes i have verified that info:
pkg info json-c
json-c-0.14
Name           : json-c
Version        : 0.14

i also tried to remove and reinstall that package..

i found this thread https://github.com/netdata/netdata/issues/7030
the error is slightly different
results of ldd /usr/local/sbin/netdata

        libm.so.5 => /lib/libm.so.5 (0x8008ee000)
        libz.so.6 => /lib/libz.so.6 (0x800b1e000)
        libcrypto.so.8 => /lib/libcrypto.so.8 (0x800e00000)
        libssl.so.8 => /usr/lib/libssl.so.8 (0x801279000)
        libuuid.so.1 => /usr/local/lib/libuuid.so.1 (0x8014ee000)
        libuv.so.1 => /usr/local/lib/libuv.so.1 (0x8016f2000)
        liblz4.so.1 => /usr/local/lib/liblz4.so.1 (0x80191d000)
        libJudy.so.1 => /usr/local/lib/libJudy.so.1 (0x801b50000)
        libjson-c.so.5 => /usr/local/lib/libjson-c.so.5 (0x801dad000)
        libthr.so.3 => /lib/libthr.so.3 (0x801fbd000)
        libc.so.7 => /lib/libc.so.7 (0x8021e6000)
        librt.so.1 => /usr/lib/librt.so.1 (0x802588000)
        libdl.so.1 => /usr/lib/libdl.so.1 (0x80278e000)

**Comment by vlvkobal** [comment]
I can reproduce the error on both FreeBSD and PfSense. `http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/netdata-1.24.0.txz` is broken:
```
root@freebsd-11:/etc/pkg # pkg add -q http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/netdata-1.24.0.txz
...
root@freebsd-11:/etc/pkg # /usr/local/sbin/netdata
/usr/local/lib/libjson-c.so.5: version JSONC_0.14 required by /usr/local/sbin/netdata not defined
```
@Ferroin @prologic can we do anything about the broken package?

@kdy1968 Please remove the netdata package and install the following one:
```
pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/quarterly/All/netdata-1.23.1.txz
```

**Comment by thiagoftsm** [comment]
Hi guys,

This is a well known problem, every time that FreeBSD updates json-c we have it. I remember I made a [quick fix](https://github.com/netdata/netdata/pull/7041) in the past. 

A simple quick fix would be to create the necessary symbolic link, but this is not the final fix for the problem.

Best regards!

**Comment by kdy1968** [comment]
@vlvkobal thanks i went back to 1.23.1,,as i wasnt sure what to link..netdata is running again, to the original question, i did have some cannot allocate memory errors in the log previously, i ran the limits command, which showed memorylocked         infinity kB...

**Comment by amoss** [comment]
Our packaging has changed a bit since that fix by @thiagoftsm and the latest versions of netdata build a local copy of json-c and then statically link it into the binary to avoid problems. If we do not maintain the external port then we cannot fix it - can you build directly from source instead?

**Comment by kdy1968** [comment]
installing via netdata-installer.sh and via bash <(curl -Ss https://my-netdata.io/kickstart.sh) all
results in:
Unable to find a usable temprorary directory. Please set $TMPDIR to a path that is both writable and allows execution of files and try again.

appears this is a know issue...
https://github.com/netdata/netdata/pull/9842

**Comment by kdy1968** [comment]
@vlvkobal nolonger getting the temp folder error, however im unable to build:

`[2.4.5-RELEASE][admin@venus.mecury.local]/root/netdata-master: ./netdata-installer.sh

  ^
  |.-.   .-.   .-.   .-.   .  netdata
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


  You are about to build and install netdata to your system.

  The build process will use /tmp for
  any temporary files. You can override this by setting $TMPDIR to a
  writable directory where you can execute files.

  It will be installed at these locations:

   - the daemon     at /usr/sbin/netdata
   - config files   in /etc/netdata
   - web files      in /usr/share/netdata
   - plugins        in /usr/libexec/netdata
   - cache files    in /var/cache/netdata
   - db files       in /var/lib/netdata
   - log files      in /var/log/netdata
   - pid file       at /var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata

  This installer allows you to change the installation path.
  Press Control-C and run the same command with --help for help.


  NOTE:
  Anonymous usage stats will be collected and sent to Google Analytics.
  To opt-out, pass --disable-telemetry option to the installer or export
  the environment variable DO_NOT_TRACK to a non-zero or non-empty value
  (e.g: export DO_NOT_TRACK=1).

Press ENTER to build and install netdata to your system >  --- Prepare custom libmosquitto version ---
[/root/netdata-master]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-mosquitto-XXXXXX.CARAD0xw/v.1.6.8_Netdata-4.tar.gz https://github.com/netdata/mosquitto/archive/v.1.6.8_Netdata-4.tar.gz
 OK

v.1.6.8_Netdata-4.tar.gz: OK
[/root/netdata-master]# tar -xf /tmp/netdata-mosquitto-XXXXXX.CARAD0xw/v.1.6.8_Netdata-4.tar.gz -C /tmp/netdata-mosquitto-XXXXXX.CARAD0xw
 OK

[/tmp/netdata-mosquitto-XXXXXX.CARAD0xw/mosquitto-v.1.6.8_Netdata-4]# env CFLAGS= CXXFLAGS= LDFLAGS= cmake -D WITH_STATIC_LIBRARIES:boolean=YES .
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  CMakeLists.txt:32 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/netdata-mosquitto-XXXXXX.CARAD0xw/mosquitto-v.1.6.8_Netdata-4/CMakeFiles/CMakeOutput.log".
 FAILED

[/tmp/netdata-mosquitto-XXXXXX.CARAD0xw/mosquitto-v.1.6.8_Netdata-4]# env CFLAGS= CXXFLAGS= LDFLAGS= make -C lib
make: Entering directory '/tmp/netdata-mosquitto-XXXXXX.CARAD0xw/mosquitto-v.1.6.8_Netdata-4/lib'
cc  -I. -I.. -I../lib -I../src/deps -DWITH_THREADING -DWITH_SOCKS  -fPIC -c mosquitto.c -o mosquitto.o
make: cc: Command not found
make: *** [Makefile:101: mosquitto.o] Error 127
make: Leaving directory '/tmp/netdata-mosquitto-XXXXXX.CARAD0xw/mosquitto-v.1.6.8_Netdata-4/lib'
 FAILED

[/tmp/netdata-mosquitto-XXXXXX.CARAD0xw/mosquitto-v.1.6.8_Netdata-4]# mv lib/libmosquitto_static.a lib/libmosquitto.a
mv: rename lib/libmosquitto_static.a to lib/libmosquitto.a: No such file or directory
 FAILED

~/netdata-master
[/root/netdata-master]# mkdir -p /root/netdata-master/externaldeps/mosquitto
 OK

[/root/netdata-master]# cp /tmp/netdata-mosquitto-XXXXXX.CARAD0xw/mosquitto-v.1.6.8_Netdata-4/lib/libmosquitto.a /root/netdata-master/externaldeps/mosquitto
cp: /tmp/netdata-mosquitto-XXXXXX.CARAD0xw/mosquitto-v.1.6.8_Netdata-4/lib/libmosquitto.a: No such file or directory
 FAILED

[/root/netdata-master]# cp /tmp/netdata-mosquitto-XXXXXX.CARAD0xw/mosquitto-v.1.6.8_Netdata-4/lib/mosquitto.h /root/netdata-master/externaldeps/mosquitto
 OK

 OK  libmosquitto built and prepared.

 --- Prepare libwebsockets ---
[/root/netdata-master]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-libwebsockets-XXXXXX.dG3H9Wwh/v3.2.2.tar.gz https://github.com/warmcat/libwebsockets/archive/v3.2.2.tar.gz
 OK

v3.2.2.tar.gz: OK
[/root/netdata-master]# tar -xf /tmp/netdata-libwebsockets-XXXXXX.dG3H9Wwh/v3.2.2.tar.gz -C /tmp/netdata-libwebsockets-XXXXXX.dG3H9Wwh
 OK

[/tmp/netdata-libwebsockets-XXXXXX.dG3H9Wwh/libwebsockets-3.2.2]# env CFLAGS= CXXFLAGS= LDFLAGS= cmake -D LWS_WITH_SOCKS5:bool=ON .
-- Compiled with LWS_WITH_DIR and LWS_WITH_DIR
-- The C compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_TOOLCHAIN_FILE=''
-- Found Git: /usr/local/bin/git
fatal: not a git repository (or any of the parent directories): .git
Git commit hash:
-- Performing Test LWS_HAVE_inline
-- Performing Test LWS_HAVE_inline - Failed
-- Performing Test LWS_HAVE___inline__
-- Performing Test LWS_HAVE___inline__ - Failed
-- Performing Test LWS_HAVE___inline
-- Performing Test LWS_HAVE___inline - Failed
-- Performing Test LWS_HAVE_MALLOC_TRIM
-- Performing Test LWS_HAVE_MALLOC_TRIM - Failed
-- Performing Test LWS_HAVE_MALLOC_USABLE_SIZE
-- Performing Test LWS_HAVE_MALLOC_USABLE_SIZE - Failed
-- Looking for fork
-- Looking for fork - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for malloc
-- Looking for malloc - found
-- Looking for memset
-- Looking for memset - found
-- Looking for realloc
-- Looking for realloc - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for vfork
-- Looking for vfork - found
-- Looking for execvpe
-- Looking for execvpe - not found
-- Looking for getifaddrs
-- Looking for getifaddrs - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for _snprintf
-- Looking for _snprintf - not found
-- Looking for _vsnprintf
-- Looking for _vsnprintf - not found
-- Looking for getloadavg
-- Looking for getloadavg - found
-- Looking for atoll
-- Looking for atoll - found
-- Looking for _atoi64
-- Looking for _atoi64 - not found
-- Looking for _stat32i64
-- Looking for _stat32i64 - not found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - not found
-- Looking for fcntl.h
-- Looking for fcntl.h - not found
-- Looking for in6addr.h
-- Looking for in6addr.h - not found
-- Looking for memory.h
-- Looking for memory.h - not found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - not found
-- Looking for stdlib.h
-- Looking for stdlib.h - not found
-- Looking for strings.h
-- Looking for strings.h - not found
-- Looking for string.h
-- Looking for string.h - not found
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - not found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - not found
-- Looking for sys/sockio.h
-- Looking for sys/sockio.h - not found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for vfork.h
-- Looking for vfork.h - not found
-- Looking for sys/capability.h
-- Looking for sys/capability.h - not found
-- Looking for malloc.h
-- Looking for malloc.h - not found
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Looking for inttypes.h
-- Looking for inttypes.h - not found
-- Looking for cap_set_flag in cap
-- Looking for cap_set_flag in cap - not found
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - not found
-- Performing Test LWS_HAS_INTPTR_T
-- Performing Test LWS_HAS_INTPTR_T - Failed
-- Performing Test LWS_HAS_GETOPT_LONG
-- Performing Test LWS_HAS_GETOPT_LONG - Failed
-- Performing Test LWS_HAVE_VISIBILITY
-- Performing Test LWS_HAVE_VISIBILITY - Success
-- Performing Test LWS_GCC_HAS_IGNORED_QUALIFIERS
-- Performing Test LWS_GCC_HAS_IGNORED_QUALIFIERS - Success
-- Performing Test LWS_GCC_HAS_TYPE_LIMITS
-- Performing Test LWS_GCC_HAS_TYPE_LIMITS - Success
Compiling with SSL support
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  CMakeLists.txt:1723 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/netdata-libwebsockets-XXXXXX.dG3H9Wwh/libwebsockets-3.2.2/CMakeFiles/CMakeOutput.log".
See also "/tmp/netdata-libwebsockets-XXXXXX.dG3H9Wwh/libwebsockets-3.2.2/CMakeFiles/CMakeError.log".
 FAILED

[/tmp/netdata-libwebsockets-XXXXXX.dG3H9Wwh/libwebsockets-3.2.2]# env CFLAGS= CXXFLAGS= LDFLAGS= make
make: *** No targets specified and no makefile found.  Stop.
 FAILED

[/root/netdata-master]# mkdir -p /root/netdata-master/externaldeps/libwebsockets
 OK

[/root/netdata-master]# cp /tmp/netdata-libwebsockets-XXXXXX.dG3H9Wwh/libwebsockets-3.2.2/lib/libwebsockets.a /root/netdata-master/externaldeps/libwebsockets/libwebsockets.a
cp: /tmp/netdata-libwebsockets-XXXXXX.dG3H9Wwh/libwebsockets-3.2.2/lib/libwebsockets.a: No such file or directory
 FAILED

 FAILED  Failed to build libwebsockets.

 --- /usr/include/Judy.h does not exist, but we need libJudy, building our own copy ---
 --- Prepare libJudy ---
[/root/netdata-master]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-judy-XXXXXX.ULl6eWSb/v1.0.5-netdata1.tar.gz https://github.com/netdata/libjudy/archive/v1.0.5-netdata1.tar.gz
 OK

v1.0.5-netdata1.tar.gz: OK
[/root/netdata-master]# tar -xf /tmp/netdata-judy-XXXXXX.ULl6eWSb/v1.0.5-netdata1.tar.gz -C /tmp/netdata-judy-XXXXXX.ULl6eWSb
 OK

[/tmp/netdata-judy-XXXXXX.ULl6eWSb/libjudy-1.0.5-netdata1]# env CFLAGS= CXXFLAGS= LDFLAGS= libtoolize --force --copy
env: libtoolize: No such file or directory
 FAILED

 FAILED  Failed to build libJudy.


 --- Run autotools to configure the build environment ---
[/root/netdata-master]# autoreconf -ivf
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I build/m4
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: not using Libtool
autoreconf-2.69: running: /usr/local/bin/autoconf-2.69 --force
configure.ac:16: error: possibly undefined macro: AC_MSG_NOTICE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:269: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:274: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:593: error: possibly undefined macro: AC_CHECK_HEADER
autoreconf-2.69: /usr/local/bin/autoconf-2.69 failed with exit status: 1
 FAILED


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues`

**Comment by vlvkobal** [comment]
An easy part - update `pkgconf` to the newest version
```
pkg delete pkgconf
pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/pkgconf-1.7.3,1.txz
```
Then you can install a gcc compiler
```
pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/mpfr-4.1.0.txz
pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/mpc-1.1.0_2.txz
pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/gcc9-9.3.0_1.txz
ln -s /usr/local/bin/gcc9 /usr/local/bin/gcc
```
But it's still not enough to build Netdata
```
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/home/vlad/netdata':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
 FAILED
```
We can continue and eliminate problems step by step, but I think it's much more simple to build Netdata package on FreeBSD and install it on pfSense.

**Comment by kdy1968** [comment]
@vlvkobal , i have limited knowledge on this, how do i go about building the package, on freebsd so that i can move it over to the pfsense box

**Comment by vlvkobal** [comment]
I'd wait while the FreeBSD team makes a new package with Netdada 1.25.
