### ISSUE TITLE
ram_available / mem.available calculation on linux os (kernel 3.14+)

### ISSUE THREAD

**Issue by mailinglists35** [netdata/netdata#7948]
#### Summary
Looking at `health.d/ram.conf`, I observe the following calculation of value of available memory:

`calc: ($avail + $system.ram.used_ram_to_ignore) * 100 / ($system.ram.used + $system.ram.cached + $system.ram.free + $system.ram.buffers)`

But at the same time, modern linux kernel (since v3.14 - https://github.com/threez/ruby-vmstat/issues/16) provides the total estimated amount of available memory via `/proc/meminfo`

https://access.redhat.com/solutions/406773 "MemAvailable: An estimate of how much memory is available for starting new applications, without swapping."

`$ grep Available /proc/meminfo 
MemAvailable:    3128880 kB`

Is there a way to replace the calc in ram.conf with simply the value taken directly from `/proc/meminfo`, if the kernel is at least 3.14?

Thank you!

**Comment by vlvkobal** [comment]
The value of the `MemAvailable` is accessible through the `$mem.available.avail` variable.
