### ISSUE TITLE
Issues when selecting another servers

### ISSUE THREAD

**Issue by dimitriskr** [netdata/netdata#7958]
#### Summary
1) Shows message "Nesting of hosts is not allowed" after I change the host on my master Netdata.
2) Cannot go back

#### Details
I have 2 slave Netdatas streaming their databases to one master and it is working fine, I can see the statistics just fine. 
**Steps**
When I go to the dashboard first time, it shows me the master's stats. 

I click on the menu to select one of the slaves, all good.

When I click the 2nd slave, it shows me the "nesting" error, as above, in a white plain screen
The URL structure on the error screen is https://domain/host/[slave 1 name]/host/[slave 2 name/[some usual variables]

When I am on the 1st slave, I cannot go back to the master server

I am using netdata behind nginx reverse proxy, set up as shown on the app's documentation, version `v1.19.0-336-nightly`

**Comment by ilyam8** [comment]
Hi @dimitriskr 

i searched `nesting`, check thi topic

https://github.com/netdata/netdata/issues/5903#issuecomment-486793963

**Comment by dimitriskr** [comment]
Thanks @ilyam8 !

The title of this issue wasn't much descriptive for this so I didn't take a look at it.
For anyone looking: Don't use spaces in your hostnames!
