### ISSUE TITLE
Restructure security-related documentation

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#7965]
Per an internal discussion, our documentation could do a better job of introducing users to the concept of putting Netdata behind a web server proxy to improve security. In addition, we have existing documentation that answers many common questions about Netdata's security model, but users don't seem to be able to find it easily.

Here are the immediate steps to take:

- [ ] Move `docs/security-design.md` from beneath the **About Netdata** top-level nav item and into its own section.
- [ ] Reference that file in more locations.
  - [ ] `DOCUMENTATION.md`
  - [ ] `docs/getting-started.md`
  - [ ] `docs/step-by-step/step-10.md`

I may also restructure `security-design.md` a bit more to differentiate between Netdata's security philosophies and concrete actions users can take.

**Comment by ilyam8** [comment]
@joelhans please update/remove the milestone

**Comment by joelhans** [comment]
Not stale. I'll have a PR for this up by the end of the week.
