### ISSUE TITLE
[SPIKE]: Setup and Explore Scaleway ARM for GHA Self-Hosted Runner

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#7968]
#### Summary

- [ ] Get Scaleway account and access to ARM Instances
- [ ] Setup a Instance with Self-Hosted Github Runner + Docker
- [ ] Test some of our CI with it for ARM builds (e.g: helper-images)

**Comment by Ferroin** [comment]
Closing, Scaleway is not an option due to their lack of IAM support.
