### ISSUE TITLE
Cannot install netdata on the debian stretch server

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7974]
##### Bug report summary
I'm trying to install prebuilt netdata on a debian server, but after the installation I get a message unit systemd is not started, here is the output of `systemctl status netdata`:
```
● netdata.service - Real time performance monitoring
   Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-02-04 19:04:31 +0330; 3s ago
  Process: 18558 ExecStartPre=/bin/mkdir -p /opt/netdata/var/cache/netdata (code=exited, status=127)
 Main PID: 11398 (code=exited, status=0/SUCCESS)

Feb 04 19:04:31 nginx-04.lb.x.y.z systemd[1]: netdata.service: Unit entered failed state.
Feb 04 19:04:31 nginx-04.lb.x.y.z systemd[1]: netdata.service: Failed with result 'exit-code'.
```
The output of `journalctl -xe`:
```
-- Unit netdata.service has failed.
-- 
-- The result is failed.
Feb 04 19:05:31 nginx-04.lb.x.y.z systemd[1]: netdata.service: Unit entered failed state.
Feb 04 19:05:31 nginx-04.lb.x.y.z systemd[1]: netdata.service: Failed with result 'exit-code'.
```
I'm streaming this server to a master server.
When I remove the user and the group `netdata` in the systemD unit, the service starts successfully but it doesn't send metrics to the master server

##### OS / Environment
```
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="9"
/etc/os-release:VERSION="9 (stretch)"
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/
```

##### Netdata version
v1.19.0
 

##### Steps To Reproduce

1. install netdata with the following parameter: `kickstart-static64.sh --non-interactive --stable-channel --no-updates`

##### Expected behavior
Netdata to start streaming metrics normally like every other server with the netdata.

**Comment by yasharne** [comment]
UPDATE: setting user and group to `root` and chwon -R root:netdata /opt/netdata fixed the problem

**Comment by prologic** [comment]
cc @Ferroin I know we did some tweaks to permissions/ownerships recently. Do you mind taking a look at this one?

**Comment by ilyam8** [comment]
i installed netdata using `kickstart-static64.sh` on debian10, no problems for me

> sudo ./kickstart-static64.sh --non-interactive --stable-channel --no-updates

```bash
test@DEB10-1:~$ sudo systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-02-04 16:49:54 EST; 5s ago
```

**Comment by amoss** [comment]
Couldn't reproduce when tested, it looks like a system-specific issue and the user has a work-around.
