### ISSUE TITLE
Monotonic.py bugs and solutions

### ISSUE THREAD

**Issue by BH1NBN** [netdata/netdata#7976]
When installing netdata under synology system, an exception occurs when running 

```bash
/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin <module> debug trace
2020-02-04 23:07:29: python.d WARNING: plugin [main]: [test_example] error on loading source: RuntimeError ("no suitable implementation for this system: RuntimeError ('can not find library rt',) ",), skipping it
2020-02-04 23:07:29: python.d INFO: plugin [main]: no jobs to run
```

Cause of error: ld.so.conf does not exist in / etc under synology

Monotonic.py will throw exceptions

The current solution is to replace the following code

```python
clock_gettime = ctypes.CDLL (ctypes.util.find_library('c'), use_errno = True).clock_gettime
```

After replacement

```python
clock_gettime = ctypes.CDLL ('/usr/lib/libc.so.6', use_errno = True).clock_gettime
```
Hope you guys can improve it in the next version

The discovery and solution of the above problem was assisted by a senior Linux friend. I am not proficient in Linux, but after the observation of my friend, I have this problem!

**Comment by ilyam8** [comment]
@BH1NBN there is no problem for python3, py2 is deprecated.

I guess we could add some `elif` to this part

https://github.com/netdata/netdata/blob/b5dcce7238a325a30223a573eabb73fcd2d927e0/collectors/python.d.plugin/python_modules/third_party/monotonic.py#L134-L140

@BH1NBN is there a way to get a PR with proper fix from your linux friend?

**Comment by BH1NBN** [comment]
@ilyam8 
There is currently no way!  Because he's busy!  For this he has contributed 5 hours to solve this piece of code I posted!  But he also gave me a solution!  The rest is to find the position of that rt!  That is the short code I replaced below!  But when I have time, I will try to solve this problem according to his ideas!  I have made some notes!  One librt.so was not found so I try to fix it as much as possible!  I will give you a reply at that time!  But the time is uncertain!

**Comment by ilyam8** [comment]
Found

https://github.com/atdt/monotonic/issues/23#issuecomment-565844421

**Comment by ilyam8** [comment]
it seems we need following to get py2 working on synology

```python
        try:
            clock_gettime = ctypes.CDLL('/lib/libc.so.6',
                                        use_errno=True).clock_gettime
        except AttributeError:
            clock_gettime = ctypes.CDLL('/lib/librt.so.1',
                                        use_errno=True).clock_gettime 
```

**Comment by BH1NBN** [comment]
for Synology 6.+
Following are the paths of the two files：
/usr/lib/librt.so.1
/usr/lib/libc.so.6
Hope to fix this soon
