### ISSUE TITLE
About memory issues

### ISSUE THREAD

**Issue by BH1NBN** [netdata/netdata#7983]
How do I get the real memory usage? I now have 16g of memory but only 14g. Not only that, the actual used capacity is assumed to be 32% of the total memory used, but this 32% does not include those used by dcoker and vm. What about memory?
netdata runs on synology platform

data-netdata="system.ram"

**Comment by ilyam8** [comment]
Hi @BH1NBN 

Your question is not clear.

> but this 32% does not include those used by dcoker and vm.

Why do you think so? `system.ram` chart show system memory usage.

**Comment by BH1NBN** [comment]
@ilyam8 
1.I actually installed memory 16G but netdat shows 14g
2. Suppose I did not enable 10% of the virtual machine's memory usage, and it still remains at 10%.

**Comment by ilyam8** [comment]
@BH1NBN 

see `free -h` output

> but netdat shows 14g

Where? sum of all dimensions of `system.ram` is 16? could you show?

**Comment by BH1NBN** [comment]
@ilyam8 
```
              total        used        free      shared  buff/cache   available
Mem:            15G        6.0G        521M         11M        9.1G        9.2G
Swap:           11G        2.0G        9.4G

```
That's it. I understand what you mean now!
But why the memory occupied by the virtual machine does not change?
I started the vm virtual machine in synology. I can obviously see the increase in memory usage but no change in netdata.

**Comment by ilyam8** [comment]
Netdata collects memory info from `/proc/meminfo`.

> I started the vm virtual machine in synology. I can obviously see the increase in memory usage but no change in netdata.

I think there are changes. If there are changes in the `/proc/meminfo` they are reflected in the charts.

**Comment by BH1NBN** [comment]
@ilyam8 ok
