### ISSUE TITLE
About host list of netdata/fping.conf

### ISSUE THREAD

**Issue by ponizovje** [netdata/netdata#7986]
Dear, All
I have more than 300 servers.
The hosts in fping.conf are too long.
Is there a solution? or could you tell me how to use it correctly?

I have a master-slave(Stream) environment.
I want to fping from master to all slaves.

netdata/fping.conf
```
fping="/usr/local/bin/fping"
hosts="host1 host2 host3 ....."
ping_every="200"
```

**Comment by ilyam8** [comment]
Hi @ponizovje 

See https://github.com/netdata/netdata/issues/6376

**Comment by ponizovje** [comment]
Hi @ilyam8 

Thank you very much!
I couldn't find the question.

Will it be modified to handle more than 300 hosts in the future?
Or should I consider another way?

**Comment by ilyam8** [comment]
> Will it be modified to handle more than 300 hosts in the future?

it is fping limitation, you need several fping instances running

**Comment by ilyam8** [comment]
> When monitoring a port, an alert will be issued if the host goes down.


What port?

**Comment by ponizovje** [comment]
> it is fping limitation, you need several fping instances running
Oh, I see.

For example, a port 80 down alert is issued.
I log in to the host and try to fix the problem.
However, I cannot log in to the host.
In that case, I will recognize that the host is down.
(But it's not very good.)

**Comment by ponizovje** [comment]
> it is fping limitation, you need several fping instances running

Oh, I see.

I felt I could fping over 300 hosts in this way.
https://github.com/netdata/netdata/tree/master/collectors/fping.plugin

**Comment by ponizovje** [comment]
For example, port 80 goes down.
I access the host, but I can't.
I will determine that the host is down or sshd is down.
(But this is the worst.)
