### ISSUE TITLE
ACLK - MQTT/LWS refinement

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#8000]
#### Feature idea summary

#7880 added the basic MQTT/LWS support.

- [ ] Improve logging considerably (connection drops etc.) for users to be able to troubleshoot
- [x] Reconnection handling as per ACLK docu - Add callback for Stelios on connection drop on LWS layer
- [ ] Write buffer optimisation - Avoid mallocs and frees
- [x] clarify if we ever want to use websocket without TLS and handle `int aclk_lws_wss_use_ssl = 1;` accordingly

**Comment by amoss** [comment]
Most of this has been completed in another task, we've agreed that the left-over parts (optimisation of memory allocation) is nice to have but essential to the March 25th release.

**Comment by amoss** [comment]
This has been handled in other issues
