### ISSUE TITLE
/var/cache/netdata/dbengine growing out of control

### ISSUE THREAD

**Issue by stormi** [netdata/netdata#8001]
### Question summary
I'm the main packager for the open source virtualisation platform XCP-ng. 
A few months ago, we chose to offer netdata in our repositories for users to install on their controller domain. That domain is a minimal CentOS-like OS that controls all devices and VMs. 

netdata seemed to be lightweight enough to run on that control domain without impeding the performance of the VMs. CPU-wise and RAM-wise, this seems to be the case, although I've seen situations where the CPU usage was really high, but I could not reproduce consistently. That's the first doubt for me regarding the software.

Today, I noticed that our lab, made of 3 hosts, had unusual disk usage. Over the 18 Gb reserved for dom0 (that minimal controller OS I mentioned earlier), 11 Gb were used by netdata in `/var/cache/netdata/dbengine` on lab3. lab2 has 9.5Gb used by dbengine files. lab1 "only" 4 Gb. 

On lab2 and lab3, lots of files going up to December 2nd. Also one 2Gb file on lab3, one 1Gb file on lab2. 

Screenshot from lab2:
![Screenshot_20200207_121755](https://user-images.githubusercontent.com/451043/74027984-95d0a100-49a9-11ea-9110-578b8230ddbf.png)

I may have misunderstood the documentation, but I thought the default (which I kept) for dbengine max size was 256 Mb. I'm surprised that the total reached 11 Gb. I'm also surprised that a single file reached 2 Gb.

Restarting the netdata service on lab2 triggered a cleanup.
Restarting the netdata service on lab3 didn't. It still uses 11Gb.

I'm highly worried about that because we encouraged our users to install netdata to monitor their hosts. By design, the hosts do not have a separate /var partition. We inherited this from Citrix XenServer and may consider changing that in the future, but until know that was not supposed to matter because everything is tailored not to grow disk space usage out of control. A host with a filled hard disk means downtime for their production VMs.

Must we go backwards and force the uninstallation of netdata in our next security update? Have I simply made a configuration mistake? Can we find a better solution? Can I totally disable disk cache if there's no better solution and what would that mean in terms of history? A few minutes? A few hours?

##### OS / Environment
XCP-ng 8.0 (CentOS 7.5 based)
netdata 1.19.0

##### Component Name
dbengine

##### Expected results
/var/cache/netdata/dbengine consistently under 256 Mb.

**Comment by Ferroin** [comment]
Are you streaming data from other nodes? That's one of the places where this gets a bit confusing, as each noed that data is being streamed from has it's own dbengine instance with it's own space usage settings.

**Comment by mfundul** [comment]
This is a bug, not a normal condition, a single file being this big that is. Please see if it's fixed by #7777 
You can manually clean up the buggy set of files by  deleting the matching `.ndf` and `.njf` files when the service is not running.

The 256MiB limit is per database instance, so for example if you're streaming, each slave will also allocate this amount, see [here](https://github.com/netdata/netdata/blob/master/database/engine/README.md#configuration).

If your issue persists you should change this from a question to a bug.

**Comment by stormi** [comment]
So, after restarting the netdata service once more on lab3, it finally decided to clean the old entries as lab2 did. I did not restart the service on lab1, on purpose.

After the whole week-end, the new status is:
* lab2: 341M, no file with an unexpected length
* lab3: 523M, no file with an unexpected length

In both cases, none of the db files created since the service was restarted on friday was deleted afterwards.

I haven't applied #7777 yet. Can it be cherry-picked and applied on top of netdata 1.19.0 safely?

Both lab2 and lab3 are slaves that are streaming towards another host
On another host of mine, netdata does seem to respect the 256 Mb limit.

There's no netdata.conf on those hosts, so they use defaults parameters. There is a `stream.conf` on each host:
```
[11:21 xcp-ng-lab-3 ~]# cat /etc/netdata/stream.conf

# do not edit, managed by XCP-ng

[stream]
    # Enable this on slaves, to have them send metrics.
    enabled = yes
    destination = tcp:192.168.5.253:19999
    api key = (redacted)
    timeout seconds = 60
    default port = 19999
    send charts matching = *
    buffer size bytes = 1048576
    reconnect delay seconds = 5
    initial clock resync iterations = 60
```

Note: the 192.168.5.253 host is actually offline. I don't know if that can explain in any way the above issues.

**Comment by mfundul** [comment]
About the `stream.conf` and the offline server, I don't think it explains the issue.

About #7777, since it has been merge to master branch, you could compile from source as the instruction say. Alternatively, you could install nightly binary packages from [here](https://packagecloud.io/netdata/netdata-edge).

**Comment by stormi** [comment]
I've updated to latest master. Now we need to wait enough to see if the issue comes back (not easy to test since it's happens kind of randomly).

**Comment by mfundul** [comment]
Closing this for now. If you notice the same issue feel free to reopen it or create a new bug report.
