### ISSUE TITLE
Properly retry failed jobs on Travis.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8003]
##### Feature idea summary

Travis CI, unfortunately, appears to have rather spotty network connections at times. This causes failed jobs in builds on a semi-regular basis for us, requiring us to manually restart the jobs to have the builds finish. Ideally, we should be automatically retrying on errored builds and some failures as well so that we don't need to manually intervene all the time.

##### Expected behavior

We only rarely have to manually restart jobs in Travis.

**Comment by Ferroin** [comment]
Partially fixed by: #8203

**Comment by prologic** [comment]
We retry most of the things that fail often and have thus reduce Travis noise considerably. This will get further fixed by #8329 and netdata/infra#233 -- Closing this as "done".
