### ISSUE TITLE
Docs: Get mkdocs to use h1 heading as page title for collectors pages

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#8007]
With #7997, we can use different strings for the main heading on a collector page and its associate entry in the left-hand navigation:

![image](https://user-images.githubusercontent.com/1153921/74049815-2a2f0980-4992-11ea-9590-853a31009b29.png)

But, the page title—the string that shows on the browser tab/window—is still the same as the navigation:

![image](https://user-images.githubusercontent.com/1153921/74049794-1daab100-4992-11ea-92c8-f10691802d0e.png)

A better solution would be to have the left-hand navigation read: `beanstalk`
And the page title and first heading read: `Monitor Beanstalk with Netdata` (or `Beanstalk monitoring with Netdata`)

We have to somehow get mkdocs to use different strings for the left-hand navigation and the page title, which, it seems, is currently hard-coded into their implementation.

**Comment by ilyam8** [comment]
> https://www.mkdocs.org/user-guide/writing-your-docs/

```yaml
nav:
- Home: 'index.md'
- About: 'about.md'
```

> Note that if a title is defined for a page in the navigation, that title will be used throughout the site for that page and will override any title defined within the page itself.

Unfortunately 😢

**Comment by ilyam8** [comment]
ok, found the solution 🎉 We need to use `metdata`.

https://squidfunk.github.io/mkdocs-material/extensions/metadata/#usage

```markdown
Title: Our Title
___

# X Monitoring with Netdata
```

<img width="740" alt="Screenshot 2020-02-08 at 00 00 52" src="https://user-images.githubusercontent.com/22274335/74065497-19b87680-4a06-11ea-9e05-971cd4b81b12.png">

**Comment by ilyam8** [comment]
@joelhans 

if the goal is exactly

> Get mkdocs to use h1 heading as page title for collectors pages

Then the quick way to do it is to use my dirty hack from [this pr](https://github.com/netdata/netdata/pull/7992/files)


```bash
find ${SRC_DIR}/collectors/ -regextype posix-egrep -regex ".*/collectors/.*" -type f -name 'README.md' -exec sed -i -e '1 s|^# \(.*\)|title: \1\n---\n\n# \1\n|' {} \;
```

What it does is

```
# some header
...
```

=>

```
title: some header
___

# some header
...

```

it expects **first line** starts with `#`, second symbol is space, rest is header.

**Comment by ilyam8** [comment]
```dif
@@ -35,6 +35,10 @@ sed -i -e '0,/# Netdata /s//# Netdata Documentation\n\n/' ${SRC_DIR}/README.md
 # Remove all GA tracking code
 find ${SRC_DIR} -name "*.md" -print0 | xargs -0 sed -i -e 's/\[!\[analytics.*UA-64295674-3)\]()//g'

+if [ -d ${SRC_DIR}/collectors/ ]; then
+  find ${SRC_DIR}/collectors/ -regextype posix-egrep -regex ".*/collectors/.*" -type f -name 'README.md' -exec sed -i -e '1 s|^# \(.*\)|title: \1\n---\n\n# \1\n|' {} \;
+fi
+
```
