### ISSUE TITLE
Allow CIDR ranges in webserver access lists

### ISSUE THREAD

**Issue by skanadian** [netdata/netdata#8008]
In the [web] allow ACLs, is it possible to implement CIDR ranges instead of wildcards?

ie.
192.168.0.0/27 is more secure than 192.168.0.* and easier than writing 32 different IPs.

Thank you.

**Comment by E46-S54** [comment]
This would be a really useful feature!

**Comment by thiagoftsm** [comment]
Considering that more than one person is requesting this feature, I moved it from the status of `New Issue` to `Sprint backlog`, this way we can plan it and bring in a near future to Netdata.

Best regards!

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).

**Comment by pingulee** [comment]
Can I use my current web access as a CIDR?
ex) 192.168.0.0/27

**Comment by ilyam8** [comment]
No, CIDR is not supported.
