### ISSUE TITLE
Missing information on stream

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8010]
##### Bug report summary
We are missing all container variables when the stream is started from slave to master, it is necessary to bring this new information to the protocol.

##### OS / Environment
```
All environments
```

##### Netdata version
netdata v1.19.0-463-g9cf6f461
 

##### Component Name
Stream

##### Steps To Reproduce
1. Set master Netdata and start it
2. Configure stream.conf and starts the stream
3. Access `/api/v1/info` on slave
4. Access `/host/hostname/api/v1/info` on master

The information on 3 and 4 will be different.

##### Expected behavior
To transfer container information from slave to master

**Comment by stelfrag** [comment]
I compiled a new master / slave with the PR applied and here are the differences:

On the left side is how the host appears to the master (via /host/slave/api/v1/info) and on the
right it is the info from the slave directly.

The `host_labels` are the same, just in reverse order in the object.


![image](https://user-images.githubusercontent.com/52996999/74102517-bb49e000-4b4c-11ea-858b-81a3ff22e92c.png)

**Comment by stelfrag** [comment]
The same test on a RPI slave shows an additional difference in the kernel_version 

On the left side is how the host appears to the master (via /host/slave/api/v1/info) and on the
right it is the info from the slave directly.

The host_labels are the same, just in reverse order in the object.

![image](https://user-images.githubusercontent.com/52996999/74102744-344a3700-4b4f-11ea-91a2-48d8cf36e6c9.png)

**Comment by thiagoftsm** [comment]
The problems with the 4 missing variables, it was fixed.
Now about the kernel version, the plus sign at the end, case it was sent different of an encoded value, this is a problem for master, and I believe this happened, please, can you confirm that it was not encoded to '%2B'? 

Best regards!

**Comment by thiagoftsm** [comment]
I was thinking here @stelfrag , case you do not see any '%2B' in the stream, something that I am almost sure will happen, this means that the stream has a bug to be fixed, and this bug does not have direct relationship with this problem that we are working here, so when you confirm this, please create another issue and assign it to me for I work next sprint on it.

**Comment by stelfrag** [comment]
There is a **+** (plus sign) in the stream data. The part in question inthe stream data, has

```
NETDATA_SYSTEM_KERNEL_VERSION=4.19.66-v7+&NETDATA_SYSTEM_ARCHITECTURE=armv7l

```

**Comment by thiagoftsm** [comment]
Our web server when receive this information process it and changes, so we need to change the stream on the client to encode the values before to send.
