### ISSUE TITLE
How to access alarms and templates per hosts via

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8014]
##### Question summary
I'm trying to make a sort of auto document generator for our netdata monitoring system. Right now, we have about 150 servers stream their metrics to a central netdata server, I can get the hostnames monitored by the netdata in this URL: `/api/v1/info`
Is there any way to access the templates or alarms per host via the API?
For example some in some templates on some hosts we have defined disk usage critical of 95 percent and some of them have disk usage critical of 90 percent. 
##### OS / Environment
Ubuntu 18
netdata v1.19
##### Expected results
some URL like `http://netdata/host1/api/v1/health` to get all the templates and alarms for the `host1`

**Comment by stelfrag** [comment]
Hi @yasharne thank you for using Netdata!!

Please check if `http://netdata/host1/api/v1/alarms` works for you

**Comment by yasharne** [comment]
Hi @stelfrag, Thanks for your response. Yes, I have already read the API documentation and tried the link you provided but it only gives me the rised alarms at the moment for the given host, not all the templates or alarms defined for the host.

**Comment by stelfrag** [comment]
> Hi @stelfrag, Thanks for your response. Yes, I have already read the API documentation and tried the link you provided but it only gives me the rised alarms at the moment for the given host, not all the templates or alarms defined for the host.

Try with the ?all parameter -- e.g. `http://netdata/host1/api/v1/alarms?all`

**Comment by yasharne** [comment]
Great! that's what I've been looking for
Thanks
