### ISSUE TITLE
How to control the continuity of the chart?

### ISSUE THREAD

**Issue by BH1NBN** [netdata/netdata#8016]
I think the netdata chart runs almost every second to collect the data and a perfect streamline curve can be observed from the chart
The plugin I wrote will break the curve!
In other words, the plugin uses api to remotely access xxx.xxx.xxx.xxx/api to obtain data. This time is not fixed, sometimes 3 seconds, sometimes 1 second, it may take 5 seconds to collect data. netdata will be missing for 3 seconds. Is there any way to make a chart curve with a single icon continuously?

My status is this:
```
   /            /\      
--      \    -      \_/
```

**Comment by ilyam8** [comment]
> This time is not fixed, sometimes 3 seconds, sometimes 1 second, it may take 5 seconds

I would change module `update_every` to 5 seconds.

**Comment by BH1NBN** [comment]
> update_every

``` python
# -*- coding: utf-8 -*-
# Description: example netdata python.d module
# Author: BH1NBN
# SPDX-License-Identifier: GPL-3.0-or-later


from bases.FrameworkServices.SimpleService import SimpleService

update_every = 5

ORDER = [
    'cpu',
    'mem',
    'jffs',
    'temperature',
    'net'
]
```
???

**Comment by ilyam8** [comment]
Yes (it will collect data every 5 seconds).

**Comment by BH1NBN** [comment]
> Yes (it will collect data every 5 seconds).
ok
