### ISSUE TITLE
Export chart

### ISSUE THREAD

**Issue by BH1NBN** [netdata/netdata#8020]
Can I add export chart options to a custom page?

**Comment by ilyam8** [comment]
Hi @BH1NBN 👋 Could you reword? I dont get it 🤷‍♂

**Comment by ilyam8** [comment]
What exactly do you want? Please give some examples.

**Comment by BH1NBN** [comment]
> What exactly do you want? Please give some examples.
https: // local: 199999 when visiting, there is pdf or jpg download in the previous menu
I want to implement this function in my custom page

**Comment by BH1NBN** [comment]
@ilyam8  print this dashboard to PDF

**Comment by ilyam8** [comment]
You mean only one chart? It is impossible, you can export the whole dashboard only

**Comment by BH1NBN** [comment]
ok i understand
@ilyam8

**Comment by ilyam8** [comment]
> a custom page?

or pdf export of custom dashboard?

**Comment by BH1NBN** [comment]
> > a custom page?
> 
> or pdf export of custom dashboard?

yes

**Comment by ilyam8** [comment]
i dont think it is something we plan to implement

cc @jacekkolasa

**Comment by jacekkolasa** [comment]
hey @BH1NBN , unfortunately we don't have that feature in plans for custom dashboards, but we plan to do Custom Dashboard in the Cloud, and they will have print feature (in several weeks though).
