### ISSUE TITLE
Improve netdata agent locking scheme, discuss proposal

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#8021]
##### Feature idea summary

* Analyse what the current locking behavior is in the Agent.
* Work out which parts of the code use the current convention that we think people work to.
* Identify what can go wrong in the places that do not.
* Identify the performance impact of the proposal.
* Groom with the team the new locking proposal for correctness -> is this a valid design?

##### Expected output

* n m-hour meetings structured as follows:

1. Markos prepares an analysis of what the current cases are.
2. Team analyses the cases against pre-picked examples in the code.
3. Identify what the results are of the locking semantics are.
4. Iterate.

Identified future use-cases to be discussed are check-pointing the metadata for storages, and reloading the config file during run-time (after initialization).

* An API for accessing locks.
* Documentation that explains the semantics of the API.
* Analysis of the edge-cases that will occur against the behavior of the API.

##### Existing concurrency proposal.

To implement a robust checkpointing (#7893) we must assume that the locking behavior is updated globally to match assumptions.

Moreover, the current host/chart/dimension locking scheme is problematic in at least one way, the locks are not being used as was the original intention in the code.

The original intention of the global lock was to protect the list of hosts:
```
netdata_rwlock_t rrd_rwlock;
```

The original intention of the host lock is in the comment:
```
struct rrdhost {
...
    // lock for this RRDHOST (protects rrdset_root linked list)
    netdata_rwlock_t rrdhost_rwlock;
}
```

The original intention of the chart lock is in the comment:
```
struct rrdset {
...
    // protects dimensions linked list
    netdata_rwlock_t rrdset_rwlock;
}
```

Moreover, there is no dimension lock whatsoever, which is something that needs to be examined as well.

Some parts of the agent use these assumptions about the use of these locks, but some do not.

Locking scheme 1:
* rrd_rwlock     -> protects *only* the structure of the hosts list, not the hosts themselves 
* rrdhost_rwlock -> protects the host structure including the list of charts ( *and anything below it in the tree ?* )
* rrdset_rwlock  -> protects the chart structure including the list of dimensions ( *and anything below it in the tree ?* )
* rrddim_rwlock  -> protects the dimension structure

Caveat 1:
* There is no reference counting on any pointers in the system, and we current leak pointers from critical regions to
  the following code. This affects the use of `rrd_rwlock` and the individual host pointers. This scheme implies that the following needs to be done *every* time a host structure is accessed:
  ```
  Acquire read on rrd_rwlock
  Acquire read/write on rrdhost_rwlock
  Release read on rrd_rwlock
  ```
Caveat 2:
* The locks below the-top level list lock cover the entire tree downwards, only the top-level has the special behavior in Caveat 1. For example, to update a chart we need to hold the write locks on both the host and the chart:
  ```
  Acquire read on rrd_rwlock
  Acquire read on rrdhost_rwlock
  Release read on rrd_rwlock
  Acquire write on rrdset_rwlock
  ... modify the chart
  Release write on rrdset_rwlock
  Release read on rrdhost_rwlock
  ```

In this example releasing the host lock could happen immediately after getting the chart lock, if the host structure is never referenced again. In practice however, the netdata agent code almost always will reference the parent structures so you either need a reference counter or you should hold the lock longer as shown above.

Discussion point:
* Which operations are writes and which are reads, e.g. is adding a dimension to a chart a write operation on the host? - Following the above assumptions the answer is "no".

If we follow the above scheme there is a potential deadlock condition. Imagine that you want to attach a new alarm to the chart. If we're holding the host read-lock, the alarm creation will block until we release it. For this kind of scenarios, it might be wiser to use reference counting and releasing the locks more eagerly.

With reference counting we would reduce the scope of the locks. Every lock would be responsible for the protection of a certain number of fields and there would not be any inheritance of the protection. 

Holding a reference to a structure would protect this structure from de-allocation only. The big difference with this approach is that the structure whose reference one is holding may completely change by the next time you access it.

One idea is to use reader-writer locking for reference counting as well. This gives a free mechanism for blocking to any deallocation thread.

Locking scheme 2 (with reference counting):
* rrd_rwlock     -> protects *only* the structure of the hosts list, not the hosts themselves 
* rrdhost_rwlock -> protects the host structure including the list of charts
* rrdset_rwlock  -> protects the chart structure including the list of dimensions
* rrddim_rwlock  -> protects the dimension structure
* reference_rwlock -> protects its parent structure from deallocation only

The update-chart example now becomes:
  ```
  Acquire read on rrd_rwlock
  Acquire read on rrdhost_rwlock
  Release read on rrd_rwlock
  Acquire write on rrdset_rwlock
  Acquire read on rrdhost->reference_rwlock
  Release read on rrdhost_rwlock
  ... modify the chart
  Release write on rrdset_rwlock
  Release read on rrdhost->reference_rwlock
  ```

This allows for the netdata code to have host/chart/dimension pointers outside of locks as before, and reusing them. The only thing one needs to do is to acquire a read lock to increase the reference count.

The host deallocation code would need to be like this:
```
  Acquire write on rrdhost_rwlock
  Acquire write on rrdhost->reference_rwlock
  ... free the structures attached to this host
  ... unlink host, make it unreachable
  Release write on rrdhost->reference_rwlock
  Release write on rrdhost_rwlock
  ... free host
```

- The big advantage of this approach is that the netdata code needs fewer changes and the granularity is finer than extending the nesting of the first approach.
- The disadvantage is that this allows for the structure to significantly change while a context is holding a reference, since it only protects form deallocation.

Scenario: a chart is updated as we are check-pointing another host.

**Comment by amoss** [comment]
The estimate for this task is not a effort-based estimate, it is a time-boxed estimate that this task will take a full sprint.

**Comment by amoss** [comment]
Rebalancing story points among issues.

**Comment by mfundul** [comment]
Created issues #8207, #8208, #8209, #8210 , closing.
