### ISSUE TITLE
Placeholder for K8s dogfooding task

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8024]
#### Summary

This is a blank placeholder for the work @ilyam8 will do in the next sprint. Please sync with @cakrit and @ncmans about the work and cut this into an appropriate number of well-described issues.

**Comment by ilyam8** [comment]
- [ ] Autodiscovery
 
___

Applications:

- [ ] VerneMQ
- [X] CockroachDB
- [ ] MongoDB
- [ ] Redis
- [ ] Traefik
- [ ] Apache Pulsar

**Comment by cakrit** [comment]
Removed autodiscovery from here, it will be covered in #5729 and the follow-up implementation task. Linked this to the epic.
