### ISSUE TITLE
Update and improve design of infographic on main README

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#8026]
The infographic in our [main README](https://github.com/netdata/netdata#infographic) is out-of-date and doesn't really look that great. @ilyam8 and I discussed for a bit that it's in need of an update and refresh.

@ilyam8 can edit this list or comment below with other specific things to fix.

- Update `metrics database` section to clarify we're using the database engine with **long-term metrics storage**
- Include Netdata Cloud to some degree
- The title ("high level feature set and architecture of netdata...") isn't written well
- Styling conflicts with our design system

**Comment by ilyam8** [comment]
For me the whole thing doesnt looks like `high level feature set and architecture of netdata`, it looks like the opposite - very detailed view (i see there are all our collectors!).

I think if we want it to be `high level feature set` we need to remove all detailes from there. Currently it is hard to read - a lot of detailes - it is always out-of-date.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
