### ISSUE TITLE
manually executed updater compares current to current version, instead of current to latest

### ISSUE THREAD

**Issue by gmeszaros** [netdata/netdata#8027]
##### Bug report summary
When disabling auto-updater and calling it manually, the updater script compares wrong environment variables. It should compare current to latest, but it compares current to current, which always evaluates to true, hence skipping update.

##### OS / Environment
This is a bug in the updater script, applies to bash based installations (at least Ubuntu)

```
Linux ESPRIMO-C720 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
```
netdata v1.19.0-473-nightly
``` 

##### Component Name
this is a bug in the `./packaging/installer/netdata-updater.sh` file.

##### Steps To Reproduce
1. when a new nightly gets released
2. and auto-updater is disabled (no cronjob for it)
3. call manually `/usr/libexec/netdata/netdata-updater.sh` script

##### Expected behavior
The script should invoke the update procedure and carry out an upgrade.

##### Actual behavior 2020. febr. 10., hétfő, 15:38:03 CET : INFO:  Running on a terminal - (this script also supports running headless from crontab)                                                                                    
2020. febr. 10., hétfő, 15:38:04 CET : INFO:  Current Version: 001019000441                                                                                                                                        
2020. febr. 10., hétfő, 15:38:04 CET : INFO:  Latest Version: 001019000473                                                                                                                                         
2020. febr. 10., hétfő, 15:38:04 CET : INFO:  Newest version 001019000441 <= 001019000473 is already installed

**Comment by prologic** [comment]
**FYI:**

Our sincerest applogies for breaking the Automatic Updater (_usually run by Cron_). The fix has been merged and tested. If you are running on NetData `v1.19.0-432`, in order to get past this broken updater and to the newest nightly, Please re-run the NetData installer as per normal. The process of re-installation also gets you the newest version.

Thank you!
