### ISSUE TITLE
installer: netdata-updater.sh errors when run manually

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8029]
btw

first of all

https://github.com/netdata/netdata/blob/d3fa405141a8d2e6689c2dedb4bedb7cf9120044/packaging/installer/netdata-updater.sh#L141

doesnt work because `Netdata` is not in `PATH` pretty often.

It means that following code

https://github.com/netdata/netdata/blob/d3fa405141a8d2e6689c2dedb4bedb7cf9120044/packaging/installer/netdata-updater.sh#L147-L148

doesnt work at all and only produces errors 

> ./netdata-updater.sh: line 147: [: : integer expression expected

cc @Ferroin

_Originally posted by @ilyam8 in https://github.com/netdata/netdata/pull/8028#issuecomment-584172977_

**Comment by prologic** [comment]
I'll pick this up today and resolve this.

**Comment by ilyam8** [comment]
@prologic probably can be fixed in https://github.com/netdata/netdata/pull/8028

**Comment by ilyam8** [comment]
But if you want to improve current_version detection, then yes. But

https://github.com/netdata/netdata/pull/8028#issuecomment-584185808

it seems we dont really need it

https://github.com/netdata/netdata/pull/8028#issuecomment-584345612

**Comment by prologic** [comment]
I _think_ this issue is also a duplicate somehow too right? (_sorry just catching up!_)

**Comment by prologic** [comment]
Closing this as a duplicate of #8027 where #8028 _should_ fix this.

**Comment by ilyam8** [comment]
Well, almost.

#8027 doesnt mention

> ./netdata-updater.sh: line 147: [: : integer expression expected

**Comment by prologic** [comment]
I'll make sure that gets fixed too!
