### ISSUE TITLE
Can I access it using https?

### ISSUE THREAD

**Issue by BH1NBN** [netdata/netdata#8033]
Appears when accessing using https

This site cannot provide a secure connection 192.168.2.102 The response sent is invalid.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

**Comment by ilyam8** [comment]
Hi

> Can I access it using https?

Yes, see https://docs.netdata.cloud/web/server/#enabling-tls-support

> Appears when accessing using https

Acess what? Provide more details.
