### ISSUE TITLE
ACLK improvements

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#8034]
#### Summary

- Additional configuration options for parameter tuning
  - Retrieve parameters early enough so that defaults are set and show up in the runtime configuration
  - Eg. Max reconnection timeout, ACLK disable option via a config option
- Ensure that the ACLK configuration (default values) appear in the netdata.conf
  - The values are now fetched only when an agent is claimed and there is an attempt to establish the ACLK
- Integration of the re-connection delay on ACLK failure
  - When the wss connection drops the aclk layer needs to:
    - Wait `aclk_reconnect_delay()` seconds
    - Try to re-establish the link

##### Additional suggestions, improvements, fixes based on the PR #8139 comments
- Remove defines that are used only once
- Rewrite the parts of the code that use pthread functions directly
  - Should use libuv
- Move macros to header files
- Remove the code that checks if we need mqtt over wss
  - The protocol will support MQTT over secure websockets
- Check instances of structures that are publicly exposed when there is no need and make static
  - Example: The lws_engine_instance
- Check instances of functions that are publicly exposed when there is no need and make static
  - Example: aclk_query_find
- Clean up code not in use and the associated supporting structure fields
  - Example: defer deletion of queries
- Remove the on_connect / on_disconnect call backs.
  - The code should be accessing the necessary connect and disconnect functions directly
- Remove all code related to MQTT that implies not use of wss
  - Currently there is code in place that uses libmosquitto to offer MQTT either plaintext or over SSL, Since we introduced libwebsockets, there that code path is not used at runtime. 
  - Note: in the future we may decide to use that code path if libmosquitto  supports libwebsockets.
- Specs compliance regarding the filtering on duplicate messages arriving at the same time
  - Currently the code will filter out those messages arriving at the same second with identical fields
     - Topic, payload, msg-id
- Handle cases where the agent receives invalid JSON requests
  - This should be rare possibly an oversight/part of a breaking change that we may have introduced in the protocol. Still we must have a way to identify and fix in coordination with the cloud team

**Comment by amoss** [comment]
Found new problems during the clean-up:

Bug:                                                                                                                    
The stabilization delay is problematic - it injects up to 60s of sleep into many code-paths. But it can only be called once the link has been established so it makes the re-connection behavior problematic. There is no synchronisation over the connected flag and it could change during query processing. The return codes from query processing are not checked and so messages are dropped if the link changed state.                                 
                                                                                                                        
Bug:                                                                                                                    
All queries are ignored during pop-corning, but commands from the cloud are in the same queue for processing so the agent would ignore requests during this period.                                                                     
                                                                                                                        
Bug:                                                                                                                    
Any query resets the pop-corning timer (including encapsulated queries) so pop-corning can go on indefinitely.            
                                                                                                                        
Bug:                                                                                                                    
The implementation of the time-out / check is wrong and it will always sleep 10s longer than necessary.

**Comment by amoss** [comment]
Merged onto feature branch after review.
