### ISSUE TITLE
ACLK Send alarms to the cloud

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#8035]
#### Summary
- Add a hook for when new alarms are written to the alarm_log.
- Decide if the payload for the new message is the same as the JSON transport for the alarm_log (on the ACLK).
- Pack the alarm data into the JSON structure.
- Integrate with the health_log and send alarms as they are triggered  (hook already there)
  - This will happen after the agent enters a stable state and the on_connect metadata has been sent

#### Expected outcome

- Should be able to trigger alarms on the Agent when the ACLK is connected and observe the messages.

**Comment by amoss** [comment]
This can be tested during the current smoke-test - if it works then the code is already merged into the feature branch and the issue can be closed.

**Comment by stelfrag** [comment]
The alarm hook is already in place. 

The alarm update is sent when an entry in the health log is added (The same json structure is generated)

The type of the message should be "status-change"

**Comment by thiagoftsm** [comment]
@stelfrag  are we going to send the alarm log? Or we are going to send only alarms when they are created?
