### ISSUE TITLE
ACLK Integration testing with the cloud

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#8036]
#### Summary
In order to do the testing a cloud endpoint must be available to test the functionality of the
ACLK code in a real environment. Tests currently are done from the agent side against
a broker that simple dumps the messages on the console to ensure delivery.

The following must be done in coordination with the cloud team - these tests will be performed manually against a single snapshot of the cloud backend.

- Bring online a docker image that will better simulate the cloud side.
  - It will contain actual code that will run on the cloud when it goes live
- Agent claiming
  - Steps
     1. Start with an unclaimed agent
     2. Issue the claim command
     3. Ensure that the ACLK thread establishes the link
         - On a running agent is may take up to 60 seconds to establish the ACLK
     4. Stop and restart agent
- Challenge request and response (on agent start)
  - Verify the challenge request
     - Delay on fail until maximum backoff
   - Verify the password request
      - Delay on fail until maximum backoff (restarts the challenge step)
- Challenge request and response (after a link disconnection / network failure)
  - Force link failure to test the challenge / password
    - Verify agent state, reconnection delay
  - Force remote broker disconnection
     - Verify agent state, reconnection delay
- Load stress test
  - Send messages to the agent and check the response time / latency
  - Simulate network latency

#### Expected outcome

* A definite structured list of test-cases.
* A list of what passes and what fails.

**Comment by amoss** [comment]
We could not converge on an estimate for this task - it is either a 5 or an 8.
