### ISSUE TITLE
netdata mariadb plugin shows behind the master critical error of 120 days 

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8042]
##### Bug report summary
netdata says the MariaDB slave is 120 days behind the master for 10 seconds but it comes back to normal:
![image](https://user-images.githubusercontent.com/7656049/74245576-76fb4300-4cf8-11ea-921f-e16b028f36ec.png)

##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.3 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.3 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version
 
netdata v1.19.0

##### Component Name

python.d

**Comment by ilyam8** [comment]
Hi @yasharne 

I see module does no processing, it reads ``SHOW SLAVE STATUS;` query response and returns `Seconds_Behind_Master` value from there.

**Comment by yasharne** [comment]
Thanks @ilyam8 
I found [this](https://www.percona.com/blog/2017/01/27/wrong-seconds_behind_master-with-slave_parallel_workers-0/) article on `Seconds_Behind_Master`  telling the wrong seconds. I think I need to follow up on the issue with our DBA team.
