### ISSUE TITLE
Is there any way to go to host from alarm without already opening the particular host?

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8043]
##### Question summary
Right now we have around 200 servers streaming metrics to our central netdata server, every time I see an alert in our rocket chat channel when I click on it, it takes me to the particular chart of the particular host on the given time if I have already opened that host, else, I get this error:
![image](https://user-images.githubusercontent.com/7656049/74246275-7e6f1c00-4cf9-11ea-8e90-fb62ac6bf71e.png)
This is kind of annoying because first I have to open the host on the central machine in order to add it to my registry then I can click on the link and go to the given host and the same happens for my colleague who clicks on the alerts as well.
Is there any way to solve this?
Here is my master netdata server registry:
```
[registry]
    enabled = True
    registry to announce = http://master:19999
```
streaming servers registry:
```
[registry]
    enabled = False
    registry to announce = http://master:19999
```
##### OS / Environment
netdata v1.19.0
##### Component Name
registry
##### Expected results
go to host from the alert without already opening that host

**Comment by jacekkolasa** [comment]
Hi @yasharne, i'm afraid this is not possible currently, but we'll keep that in mind and we'll fix that when we'll have more resources!
