### ISSUE TITLE
RFC: Redesign Agent right navbar for Kubernetes

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8045]
#### Feature idea summary

We currently just show a meaningless list of pods/containers on the right menu for k8s containers. We **probably** need to organize the information in a more meaningful hierarchy, perhaps taking into account labels, services and/or other information provided for each pod. 

However, the stand alone FOSS agent will never display information from multiple hosts in a single view and we've already settled on our k8s monitoring architecture. If reorganizing the current charts and containers at the level of a node is meaningless, then we should just not do it and stick with the view that will be built on the cloud, which will include information from the entire cluster.

**Comment by ilyam8** [comment]
I would say it is not only for k8s, but in general. Another good example is `vsphere` collectors, its hierarchy:

- datacenter
  - cluster
    - host
      - vm

As for k8s

> https://github.com/netdata/netdata/issues/5387#issuecomment-466919849

So it is arbitrary nested depth.

**Comment by cakrit** [comment]
> So it is arbitrary nested depth.

Yes, I like this.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
