### ISSUE TITLE
Add a "what's new" button to the agent UI

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8046]
##### Feature idea summary

Add a way to the UI, to notify users of significant changes/improvements. Requirements to be specified, in should not be obtrusive.

**Comment by oyabun** [comment]
Something Like this? https://www.figma.com/file/LXeXGZaVU8acGEjfeiZ8S8/what-s-new-8046?node-id=0%3A1

**Comment by cakrit** [comment]
It looks beautiful, but we need ideation & refinement.

**Comment by ilyam8** [comment]
Added
