### ISSUE TITLE
Agent navigation bars when ACLK is not available

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8048]
### Summary

Ensure that requirements on product#277 are met.

- [ ] If user disabled aclk on purpose do not show anything
- [ ] Show info message on dashboard if user didn't purposefully disable ACLK informing him he is missing out
- [ ] If agent is claimed already but there is no ACLK make it a well visible error. (User claimed already so he wants cloud and maybe update made it not build on his machine)

**Comment by amoss** [comment]
* If the installer / build succeeded in providing the components required for the ACLK then this needs to be communicated.
* The `--disable-cloud` flag on the installer needs to be passed into the code.

**Comment by amoss** [comment]
This issue cannot be implemented until the communication between the dashboard and the agent is clarified on product#277.

**Comment by amoss** [comment]
How should this information be communicated between the agent and the dashboard?

The best suggestion that we have so far is to add it to the `/api/v1/Registry?action=hello` endpoint. Currently this produces:
```
{
	"action": "hello",
	"status": "ok",
	"hostname": "london3.my-netdata.io",
	"machine_guid": "792bb46a-fb11-11e7-b935-e6a17492adc8",
	"registry": "https://registry.my-netdata.io",
	"cloud_base_url": "https://netdata.cloud",
	"anonymous_statistics": true
}
```
So we would add the following fields:
```
     "cloud-enabled": "true",
     "cloud-available": "true",
     "agent-claimed": "true"
```
* Should we do expose this information public-ally - as we have no private communication channel between the dashboard and the agent?
* I don't know the purpose of this end-point - does this fit?

**Comment by underhood** [comment]
with the `agent-claimed` i think this has to be updated during run as claiming AFAIK (correct me if I am wrong) should be possible during agent run without restart.
