### ISSUE TITLE
Report cases where the Agent Cloud link is blocked by firewall

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8051]
#### Discussion for the planning meeting on Wednesday

* This needs to be groomed before we can estimate the complexity.
* If this is needed by March 25 then this causes a problem in how it can be placed in the upcoming sprint.

#### Summary

Ensure that the requirements of product#243 are met.

- [x] Define endpoint for ACLK connection failures with SRE team if not done by #8050 already. Endpoint will be GAnalytics
- [x] Implement reporting to the endpoint of cases like:
    - SSL update failed
    - WebSockets update failed
- [x] do not send anything if `DO_NOT_TRACK` env var is set

**Comment by amoss** [comment]
Please groom in the upcoming sprint how we will do this.

**Comment by underhood** [comment]
Where: Google Analytics
How: Call the script
Event types/details of fields: @manos-saratsis where do we get this info?
If we are completely blocked it makes no sense to retry/try storing informations anywhere IMHO Therefore we try sending and ignore the result.
