### ISSUE TITLE
Automatic updates don't work

### ISSUE THREAD

**Issue by jeremyfritzen** [netdata/netdata#8053]
##### Bug report summary
**Automatic updates don't work.**

I installed netdata on 3 debian VMs with the automatic one-line installation script, as described in the [official documentation](https://docs.netdata.cloud/packaging/installer/#automatic-one-line-installation-script).

I can see that the script is indeed present in the directory /etc/cron.daily/ but the software doesn't update automatically each night.
As you can see in the above image, it is not up to date:

![image](https://user-images.githubusercontent.com/26802442/74275438-28f43880-4d14-11ea-9dc5-ec06a5895641.png)

##### OS / Environment
```
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="9"
/etc/os-release:VERSION="9 (stretch)"
/etc/os-release:VERSION_CODENAME=stretch
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version
netdata v1.19.0-469-nightly

##### Steps To Reproduce

1. Install netdata through this command (as described [here](https://docs.netdata.cloud/packaging/installer/#automatic-one-line-installation-script)) on a debian machine
2. Wait 24h
3. Check on url:19999: a notification about a new version appears. But the software didn't update automatically.

##### Expected behavior
The software should update automatically each night, as explained [here ](https://docs.netdata.cloud/packaging/installer/#automatic-one-line-installation-script)in the official documentation:

> To install Netdata from source and get automatic nightly updates, run the following as your normal user: `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

**Comment by Ferroin** [comment]
This is a known issue and is being worked on with high priority. There should be a fix some time within the next 24 hours, though a manual reinstall will be required to get things working again (you would just need to re-run the same install command you used originally on each system).

Progress can be tracked at #8027 and #8028.

**Comment by jeremyfritzen** [comment]
Thanks!
Sorry for not having noticed the previous posts.
