### ISSUE TITLE
Update docs on persisting Dashboards in Docker run NetData

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8055]
See #7604 for background;

- Add improved instructions on our [docs](https://docs.netdata.cloud/) to help users persist their custom Dashboards

Something like:

```sh
$ mkdir /path/to/host/dashbaords
$ docker run -v /path/to/host/dashbaords:/path/inside/container ....
```

We should also test/verify the accuracy of this information before putting up the PR to amend the docs.

**Comment by D34DC3N73R** [comment]
Rather than mounting a subdirectory, would it be possible to change this to the way that /etc/netdata works? Still possible to load netdata when the directory is empty, but allows for files to override the defaults?

**Comment by CoreyVidal** [comment]
Has this been addressed or updated in any way? I'm experiencing the same issues from this thread and #7604.

**Comment by prologic** [comment]
> Has this been addressed or updated in any way? I'm experiencing the same issues from this thread and #7604.

I'm _fairly_ certain this has been [well documented](https://learn.netdata.cloud). Please have a look and if this is not the case please open an issue or file a PR addressing this. Thank you!
