### ISSUE TITLE
Apache Pulsar

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8062]
##### Feature idea summary

We are using `Apache Pulsar`, it would be nice to have the collector.

`Apache Pulsar` [exposes data in prometheus format](https://pulsar.apache.org/docs/en/deploy-monitoring/).

##### Expected behavior

apache pulsar collector

**Comment by amoss** [comment]
Removing milestone so that we can replan when @ilyam8 is available.

**Comment by ilyam8** [comment]
Hi @aahmed-se

I noticed you are the author of https://github.com/apache/pulsar/pull/3047 😄 

How do i change `statsUpdateFrequencyInSecs` when i run `Pulsar` in a standalone mode in a docker container?

I changed `statsUpdateFrequencyInSecs` in the `conf/broker.conf`, restarted container but it doesnt seem to take any affect (value in the config is changed, but `statsUpdateFrequencyInSecs` in fact is not).

**Comment by aahmed-se** [comment]
for standalone you need to change standalone.conf
