### ISSUE TITLE
Docs: Group collectors by type

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#8069]
During the work involved in #7878 / #7996, we decided that grouping collectors by type, rather than their plugin/orchestrator, was too much of a task for the current sprint. So, this issue will serve as the place where we can discuss how to organize collectors by type and manage the work of editing `collectors/COLLECTORS.md` into a list that's organized by type.

@ilyam8 can comment below about his specific concerns with the grouping by type that currently exists on the main README, the homepage, and in `docs/Add-more-charts-to-netdata.md`. Generally speaking, some of the types were not accurate, and there were instances of certain collectors being associated with the wrong type.

TODOs:

- [ ] Decide on what types we should feature
- [ ] Restructure the collectors list `.md` based on types

**Comment by ilyam8** [comment]
Initial break down of **external modules** by monitoring area. It is far from good/complete, should be adjusted. 

We need to add internal collectors and build a good and not complex structure.

Top levels should be something like:

- System
- Application
- Remote devices
- ???

Any help appreciated.

cc @joelhans @manos-saratsis 

___

### Databases and KV Stores

- [cockroachdb](go.d.plugin/modules/cockroachdb/README.md)
- [mysql](go.d.plugin/modules/mysql/README.md)
- [couchdb](python.d.plugin/couchdb/README.md)
- [mysql](python.d.plugin/mysql/README.md)
- [oracledb](python.d.plugin/oracledb/README.md)
- [postgres](python.d.plugin/postgres/README.md)
- [proxysql](python.d.plugin/proxysql/README.md)
- [redis](python.d.plugin/redis/README.md)
- [rethinkdbs](python.d.plugin/rethinkdbs/README.md)
- [riakkv](python.d.plugin/riakkv/README.md)
- [mongodb](python.d.plugin/mongodb/README.md)
- [zookeeper](go.d.plugin/modules/zookeeper/README.md)
- [consul](go.d.plugin/modules/consul/README.md)

### Search Engines

- [elasticsearch](python.d.plugin/elasticsearch/README.md)
- [solr](go.d.plugin/modules/solr/README.md)

### Web and Caching Proxy Servers and HTTP Load Balancers

- [apache](python.d.plugin/apache/README.md)
- [apache](go.d.plugin/modules/apache/README.md)
- [lighttpd](go.d.plugin/modules/lighttpd/README.md)
- [lighttpd2](go.d.plugin/modules/lighttpd2/README.md)
- [tengine](go.d.plugin/modules/tengine/README.md)
- [phpfpm](go.d.plugin/modules/phpfpm/README.md)
- [nginx](python.d.plugin/nginx/README.md)
- [nginx](go.d.plugin/modules/nginx/README.md)
- [web_log](go.d.plugin/modules/weblog/README.md)
- [web_log](python.d.plugin/web_log/README.md)
- [tomcat](python.d.plugin/tomcat/README.md)
- [litespeed](python.d.plugin/litespeed/README.md)
- [nginx_plus](python.d.plugin/nginx_plus/README.md)
- [phpfpm](python.d.plugin/phpfpm/README.md)
- [squid](python.d.plugin/squid/README.md)
- [squidlog](go.d.plugin/modules/squidlog/README.md)
- [varnish](python.d.plugin/varnish/README.md)
- [haproxy](python.d.plugin/haproxy/README.md)
- [traefik](python.d.plugin/traefik/README.md)

### Any HTTP and TCP Endpoints
- [httpcheck](go.d.plugin/modules/httpcheck/README.md)
- [httpcheck](python.d.plugin/httpcheck/README.md)
- [portcheck](python.d.plugin/portcheck/README.md)
- [portcheck](go.d.plugin/modules/portcheck/README.md)

### Virtualization and Containers

- [vcsa](go.d.plugin/modules/vcsa/README.md)
- [vsphere](go.d.plugin/modules/vsphere/README.md)
- [dockerd](python.d.plugin/dockerd/README.md)
- [docker_engine](go.d.plugin/modules/docker_engine/README.md)

### Storage Systems

- [ipfs](python.d.plugin/ipfs/README.md)
- [hdfs](go.d.plugin/modules/hdfs/README.md)
- [ceph](python.d.plugin/ceph/README.md)
- [scaleio](go.d.plugin/modules/scaleio/README.md)
- [samba](python.d.plugin/samba/README.md)

### Messaging Systems

- [activemq](go.d.plugin/modules/activemq/README.md)
- [rabbitmq](python.d.plugin/rabbitmq/README.md)
- [rabbitmq](go.d.plugin/modules/rabbitmq/README.md)
- [vernemq](go.d.plugin/modules/vernemq/README.md)
- [beanstalk](python.d.plugin/beanstalk/README.md)

### Email Servers

- [postfix](python.d.plugin/postfix/README.md)
- [dovecot](python.d.plugin/dovecot/README.md)
- [exim](python.d.plugin/exim/README.md)

### DNS Servers

- [bind](go.d.plugin/modules/bind/README.md)
- [coredns](go.d.plugin/modules/coredns/README.md)
- [dns_query](go.d.plugin/modules/dnsquery/README.md)
- [unbound](go.d.plugin/modules/unbound/README.md)
- [named](node.d.plugin/named/README.md)
- [bind_rndc](python.d.plugin/bind_rndc/README.md)
- [powerdns](python.d.plugin/powerdns/README.md)
- [nsd](python.d.plugin/nsd/README.md)
- [dnsdist](python.d.plugin/dnsdist/README.md)
- [dns_query_time](python.d.plugin/dns_query_time/README.md)

### DHCP

- [dnsmasq_dhcp](go.d.plugin/modules/dnsmasq_dhcp/README.md)
- [isc_dhcpd](python.d.plugin/isc_dhcpd/README.md)

### VPN

- [openvpn](go.d.plugin/modules/openvpn/README.md)
- [ovpn_status_log](python.d.plugin/ovpn_status_log/README.md)
- [tor](python.d.plugin/tor/README.md)
- [libreswan](charts.d.plugin/libreswan/README.md)

## AAA Servers

- [freeradius](go.d.plugin/modules/freeradius/README.md)
- [freeradius](python.d.plugin/freeradius/README.md)
- [openldap](python.d.plugin/openldap/README.md)

### APM (Application Performance Monitoring)

- [springboot](python.d.plugin/springboot/README.md)
- [springboot2](go.d.plugin/modules/springboot2/README.md)
- [phpdaemon](go.d.plugin/modules/phpdaemon/README.md)
- [go_expvar](python.d.plugin/go_expvar/README.md)
- [uwsgi](python.d.plugin/uwsgi/README.md)

### K8S Control Plane

- [k8s_kubelet](go.d.plugin/modules/k8s_kubelet/README.md)
- [k8s_kubeproxy](go.d.plugin/modules/k8s_kubeproxy/README.md)

### Distributed computing

- [boinc](python.d.plugin/boinc/README.md)
- [gearman](python.d.plugin/gearman/README.md)

### Log Analysis Applications

- [logstash](go.d.plugin/modules/logstash/README.md)
- [fluentd](go.d.plugin/modules/fluentd/README.md)

### Time Servers

- [chrony](python.d.plugin/chrony/README.md)
- [ntpd](python.d.plugin/ntpd/README.md)

## Digital Certificates

- [x509check](go.d.plugin/modules/x509check/README.md)

### Media Streaming Servers

- [icecast](python.d.plugin/icecast/README.md)

### Provisioning Systems

- [puppet](python.d.plugin/puppet/README.md)

### Telephony Servers

- [opensips](charts.d.plugin/opensips/README.md)

### Game Servers

- [spigotmc](python.d.plugin/spigotmc/README.md)

### System Monitoring Applications
- [monit](python.d.plugin/monit/README.md)

### Social Sharing Servers

- [retroshare](python.d.plugin/retroshare/README.md)

### System Security

- [fail2ban](python.d.plugin/fail2ban/README.md)

### Advertisement and tracker blocker applications

- [pihole](go.d.plugin/modules/pihole/README.md)

### APIs

- [dockerhub](go.d.plugin/modules/dockerhub/README.md)

### Windows Machines

- [wmi](go.d.plugin/modules/wmi/README.md)

___

### System Hardware and Sensors

- [hpssa](python.d.plugin/hpssa/README.md)
- [adaptec_raid](python.d.plugin/adaptec_raid/README.md)
- [megacli](python.d.plugin/megacli/README.md)
- [nvidia_smi](python.d.plugin/nvidia_smi/README.md)
- [sensors](charts.d.plugin/sensors/README.md)
- [sensors](python.d.plugin/sensors/README.md)
- [hddtemp](python.d.plugin/hddtemp/README.md)
- [smartd_log](python.d.plugin/smartd_log/README.md)

### System Users

- [logind](python.d.plugin/logind/README.md)

___

### Remote Devices and Sensors

- [snmp](node.d.plugin/snmp/README.md)
- [fronius](node.d.plugin/fronius/README.md)
- [sma_webbox](node.d.plugin/sma_webbox/README.md)
- [stiebeleltron](node.d.plugin/stiebeleltron/README.md)
- [w1sensor](python.d.plugin/w1sensor/README.md)
- [energid](python.d.plugin/energid/README.md)
- [ap](charts.d.plugin/ap/README.md)
- [apcupsd](charts.d.plugin/apcupsd/README.md)
- [nut](charts.d.plugin/nut/README.md)
- [am2320](python.d.plugin/am2320/README.md)

**Comment by joelhans** [comment]
@ilyam8 I edited your list with a few changes:

- Ordered them alphabetically.
- Added (Go) or (Python) when applicable.
- Changed some of the headings to use spelled-out terms instead of acronyms.

I don't have any immediate objections to how you've organized the types, but I also don't know nearly as much about this as you do. It _looks_ fine to me.

I'm struggling to think about how we add all the things our internal plugins monitor without this list being ridiculously large. proc.plugin alone monitors like 20 different things.

**Comment by ilyam8** [comment]
> add all the things our internal plugins monitor without this list being ridiculously large

Yes, i think about it too. If the goal is to have a long list to provide wow effect we need to put all of them.

There is datadog integrations page:

> https://docs.datadoghq.com/integrations/

It is a flat "list", all system metrics (most of our internal plugins collect system metrics) are under `system` intergration, it is just a one item.

**Comment by joelhans** [comment]
Now that I think about it, there's no way we can list all of the different things collected by something like proc.plugin. If we did that, we might as well list _all_ the charts from _all_ the collectors, and that would get ridiculous really fast.

Maybe we can borrow from the old README though. I can get started on this tomorrow, maybe.

## System metrics

[](proc.plugin/README.md)
[Block devices](proc.plugin/README.md)
[](proc.plugin/README.md)
 - per disk: I/O, operations, backlog, utilization, space, etc.
    BCACHE - detailed performance of SSD caching devices.
    DiskSpace - monitors disk space usage.
    mdstat - software RAID.
    hddtemp - disk temperatures.
    smartd - disk S.M.A.R.T. values.
    device mapper - naming disks.
    Veritas Volume Manager - naming disks.
    megacli - adapter, physical drives and battery stats.
    adaptec_raid - logical and physical devices health metrics.
    ioping - to measure disk read/write latency.


### Filesystems

[BTRFS](proc.plugin/README.md)
[NFS file servers and clients](proc.plugin/README.md)
[ZFS](proc.plugin/README.md)

### Networking

[Network stack](proc.plugin/README.md)
[Netfilter](proc.plugin/README.md)
[SYNPROXY](proc.plugin/README.md)
[nfacct](nfacct.plugin/README.md)
[Network QoS](tc.plugin/README.md)
[fping](fping.plugin/README.md)
[Access points](ap.plugin/README.md)

### Processes

[System processes](proc.plugin/README.md)
[Applications](apps.plugin/README.md)
[systemd](cgroups.plugin/README.md)

### System hardware and sensors

- [adaptec_raid](python.d.plugin/adaptec_raid/README.md)
- [hddtemp](python.d.plugin/hddtemp/README.md)
- [hpssa](python.d.plugin/hpssa/README.md)
- [megacli](python.d.plugin/megacli/README.md)
- [nvidia_smi](python.d.plugin/nvidia_smi/README.md)
- [sensors](charts.d.plugin/sensors/README.md)
- [sensors](python.d.plugin/sensors/README.md)
- [smartd_log](python.d.plugin/smartd_log/README.md)

### System users

- [User and user group resource usage](apps.plugin/README.md)
- [logind](python.d.plugin/logind/README.md)

**Comment by joelhans** [comment]
Just realized that we fixed this a while back with #9513. Closing.
