### ISSUE TITLE
naming convensions for charts

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#807]
I think we should have a universal way of naming charts.

Currently, there are:
1. A chart `type.id` that uniquely identifies a chart
2. A chart `type.name` that also uniquely identifies a chart
3. A chart `family` (i.e. `eth0`, or `sda`, etc)
4. A chart `context` (i.e. the template that defines the data the chart is presenting)

I think the right way to do it is to have a single chart id that is like this:

```
host.instance.family.type.subtype
```

where:
- `host` new entity: the netdata hostname
- `instance` (or `category`?) is today's main menu on the dashboard
- `family` is today's submenu on the dashboard (as-is today)
- `type.subtype` is today's `context` (i.e. the template of the chart)

This needs some more work, to map all the charts to new names. Unfortunately, it will break all custom dashboards developed so far.

**Comment by paulfantom** [comment]
I like it! Should we implement it in v2.0?

**Comment by ktsaou** [comment]
I think it has to wait a bit more. I'll not have enough time for the next weeks and I have to render notifications/alarms on the dashboard.

I like it too though, although it will break all APIs (plugins, web, custom dashboards, etc). So, it we will also need a migration document for all those that have developed plugins and dashboards so far.

**Comment by paulfantom** [comment]
Since v1.2 is mostly compatible with current git repository state. I propose to test health monitoring, release it as v1.3 and then implement this change as v2.0. This way it will be clear that major version (v2) is incompatible with previous one (v1). What do you think about this?

**Comment by ktsaou** [comment]
yes, I agree.

**Comment by paulfantom** [comment]
Since this will make v2.0 incompatible with v1.3, maybe we should create new branch from master repository after release? This way we could work on v2.0 in master branch and fix bugs for people who will use v1.3 in "support" branch. @ktsaou what do you think?

**Comment by ktsaou** [comment]
Yes, this is a nice idea.

While trying to get alarms visualized, I realized we are going to need another level:

```
host.family.category.type.subtype
```

- `host` new entity: the netdata hostname
- `family` is today's main menu on the dashboard
- `category` is today's sub-menu on the dashboard
- `type.subtype` is today's context (i.e. the template of the chart data)

**Comment by paulfantom** [comment]
> we will have touch all the plugins

No problem, I can do all bash and python ones.

**Comment by ktsaou** [comment]
@cakrit 	this is one of the most important tasks at the netdata core.

We should take into account OpenMetrics for this.

It will be a breaking change. It may change the external plugins API, the streaming API, etc. So, we could also rename other incorrectly parts of netdata with the same release (like `charts.d`).

**Comment by Saruspete** [comment]
Greetings,

This is indeed a very needed feature. I'm still struggling to work with the different names, like "type", "name", "family", "context",  what's required, what's generated automatically, how to get info in the dashboard.

So far, I didn't find a way for plugins to add their hint on top of the charts. Only the `web/gui/README.md` file explaining how to create a whole new .js file with modifications, and the related change in netdata configuration to use it.

If I have different plugins, I have to sync this single .js file with multiple modules changes, while it would be way better to get that info frm the plugin itself, during the dashboard definition.

Cheers

**Comment by ilyam8** [comment]
Indeed, naming is confusing. Especially `type.it` (it is not type). `type.id` must be globally unique, all other chart definition parameters doesnt matter. (in fact they are different time series!).

> So far, I didn't find a way for plugins to add their hint on top of the charts.

Check `dashboard_info.js`

**Comment by Saruspete** [comment]
> Check `dashboard_info.js`

That was the 2nd part of the paragraph :smile:  details for updating dashboard_info.js are in `web/gui/README.md`

I meant: currently, there's no way for a plugin to provide details for the charts it defines, without  changing any file in the /web interface.

**Comment by ilyam8** [comment]
> without changing any file in the /web interface.

Yes, and it is makes sense actually, that is dashboard feature.

But what you are saying makes sense too. Perhaps better solution would be to maintain module specific `*.js` file in the module dir or something like that.
