### ISSUE TITLE
go.d.plugin tries to load the plugins from the wrong directory

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8072]
##### Bug report summary
I'm trying to use `x509check` plugin in my netdata and my `go.d.conf` file is in `/opt/netdata/etc/netdata/go.d.conf` and  `x509check.conf` file is in `/opt/netdata/etc/netdata/go.d/x509check.conf` (copied by the `edit-config` file). but when I run the  `go.d.plugin` in debug mode it looks for `go.d.conf` and `x509check.conf` in the wrong directory.
here is the output of `go.d.plugin -d -m x509check` command:
```
[ WARN  ] main[main] setup.go:52 find config file error : can't find 'go.d.conf' in [/opt/etc/netdata /opt/usr/lib/netdata/conf.d], will use default configuration
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 2
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] create.go:71 loading 'x509check' configuration
[ WARN  ] main[main] create.go:92 'x509check': can't find 'go.d/x509check.conf' in [/opt/etc/netdata /opt/usr/lib/netdata/conf.d], will use default 1 job configuration
[ ERROR ] x509check[x509check] x509check.go:101 'source' parameter is mandatory, but it's not set
[ ERROR ] x509check[x509check] job.go:116 Init failed
[ WARN  ] main[main] start.go:41 x509check[x509check]: autodetection failed
[ INFO  ] main[main] orchestrator.go:126 start main loop
[ DEBUG ] main[main] orchestrator.go:141 tick 0
[ DEBUG ] main[main] orchestrator.go:141 tick 1
[ DEBUG ] main[main] orchestrator.go:141 tick 2
```
But when I run `go.d.plugin -d -m x509check -c /opt/netdata/etc/netdata/` command I see the debug output correctly.
I'm using the prebuilt netdata which is installed under /opt/netdata directory.

##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.3 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.3 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

 netdata v1.19.0

##### Component Name
external plugins

##### Steps To Reproduce

1. ...
2. ...

##### Expected behavior
load the configuration from `/opt/netdata/etc/netdata` instead of `/opt/etc/netdata `

**Comment by ilyam8** [comment]
Hi @yasharne 

> go.d.plugin -d -m x509check -c /opt/netdata/etc/netdata/ -c /opt/netdata/etc/netdata/go.d

(you can add any number of `-c`)

**Comment by ilyam8** [comment]
For python some variables are set during install

See `@...` vars

https://github.com/netdata/netdata/blob/393f28b470a7b3f718a1d168e8d186cd549c5d9d/collectors/python.d.plugin/python.d.plugin.in#L80-L90

This is not true for `go.d.plugin`.

**Comment by ilyam8** [comment]
`go.d.plugin` try to load `NETDATA_USER_CONFIG_DIR` and `NETDATA_STOCK_CONFIG_DIR` env variables and if they are not there it uses hardcoded paths - it should work if Netdata installed in `/opt/`

https://github.com/netdata/go.d.plugin/blob/d41e79cac0d6b1b9c89cf34df112c8c1359d943f/cmd/godplugin/main.go#L56-L64


```console
^C[ INFO  ] main[main] orchestrator.go:156 SIGINT received. Terminating...
root@DEB10-1:/opt/netdata/usr/libexec/netdata/plugins.d# ./go.d.plugin -d -m x509check
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 1
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] create.go:71 loading 'x509check' configuration
[ DEBUG ] main[main] create.go:204 config file is empty
[ ERROR ] main[main] create.go:103 skipping 'x509check': config 'jobs' section is empty or not exist
[ INFO  ] main[main] orchestrator.go:126 start main loop
[ DEBUG ] main[main] orchestrator.go:141 tick 0
```

**Comment by yasharne** [comment]
Thanks @ilyam8 
Setting `NETDATA_USER_CONFIG_DIR` to `/opt/netdata/etc/netdata/` solved the problem in the debug mode.
But my question is those files are copied by the `edit-config` command and I couldn't see the charts on the dashboard (probably because of the wrong directory). I can run the python plugins without any problem so I expected to go plugins to works as well without any changes.

**Comment by yasharne** [comment]
Ok I've found another problem, the output of `/opt/netdata/etc/netdata/edit-config go.d.conf` is: 
```
enabled: yes
default_run: no
x509check: yes
```
But in `tail -f /opt/netdata/var/log/netdata/error.log | grep "x509"` i get:
```
2020-02-12 20:47:16: go.d INFO: main[main] module 'x509check' disabled in configuration file
```

**Comment by ilyam8** [comment]
https://github.com/netdata/go.d.plugin/blob/d41e79cac0d6b1b9c89cf34df112c8c1359d943f/config/go.d.conf#L14-L19

**Comment by ilyam8** [comment]
```yaml
# Enable/disable specific g.d.plugin module
# If you want to change any value, you need to uncomment out it first.
# IMPORTANT: Do not remove all spaces, just remove # symbol. There should be a space before module name.
modules:
#  activemq: yes
#  apache: yes
```

**Comment by yasharne** [comment]
Thank you so much @ilyam8 for your help, it was my problem not paying much attention to the configuration file syntax :)
