### ISSUE TITLE
"dbengine disk space" param not respected?

### ISSUE THREAD

**Issue by stormi** [netdata/netdata#8079]
##### Bug report summary
I have updated netdata to latest master to test if #8001 still occurs.
To speed up the testing, instead of waiting for the db to reach 256M, I've set its size to 32M, with this setting in `/etc/netdata/netdata.conf`, under the `[global]` section: `dbengine disk space = 32`.

One 3 hosts, I've left the old db and on one host I've removed all files in `/var/cache/netdata/dbengine` (after stopping the service). 

18h later:
* the 3 first hosts still have dbs around 248M
* the fourth host's db already reached 79M.

Is it a bug, or a misunderstanding of the docs from me?

##### OS / Environment
XCP-ng 8.0 and 8.1beta

##### Netdata version
netdata v1.19.0-491-nightly, built as a RPM

##### Component Name
dbengine

##### Steps To Reproduce
Set `dbengine disk space = 32` and restart netdata service.

##### Expected behavior
Not more than 32M of disk space used by dbengine.

**Comment by mfundul** [comment]
In the [documentation](https://docs.netdata.cloud/database/engine/#configuration) it is stated that:
```
    page cache size = 32
    dbengine disk space = 256

The above values are the default and minimum values for Page Cache size
and DB engine disk space quota.
```
so it would be a problem if it goes well above 256MiB.

**Comment by stormi** [comment]
Oh, ok, I missed that it's a minimum. Thanks.
