### ISSUE TITLE
Add CentOS 6-specific instructions to installation docs

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#8081]
Users on CentOS 6 (#8080) are having issues finding install instructions specific to their distro. This also can apply to CentOS 8, which requires a [different process](https://docs.netdata.cloud/packaging/installer/methods/manual/#centos-rhel-8x).

Now, we could simply place the CentOS 6 instructions alongside those CentOS 8 instructions and call it a day, but I think we need to make users more aware of these specific needs. Maybe we create a separate `os/centos.md` page with these, and link to it from the installation guide and in the left-hand nav?

The actual instructions for CentOS 6, from @Ferroin:

> For CentOS 6 you'll need to enable EPEL (yum install epel-release) and the OKay repositories for the installation to work.

**Comment by prologic** [comment]
@joelhans Those instructions on EPEL are sort of / kind of invalid now in the senes that I updated the `install-required-packages.sh` script to go install the appropriate repos for the user anyway. They are prompted in non-interactive mode, otherwise it'll just go grab what it needs to.
