### ISSUE TITLE
custom "update every" for internal plugins

### ISSUE THREAD

**Issue by martinbbg** [netdata/netdata#8084]
From what I understood from the docs, only external plugins can be configured with a custom "update every" (for the entire plugin).

It would be nice to be able to do this for internal ones too, or even better for every metric.

For example, all the ntp metrics really don't need to be checked as often as other metrics.

**Comment by vlvkobal** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
