### ISSUE TITLE
Exim plugin documentation

### ISSUE THREAD

**Issue by kozicpetar** [netdata/netdata#8087]
I need to put this as feature.

In your documentation for exim plugin, here:
https://docs.netdata.cloud/collectors/python.d.plugin/exim/

you wrote `Configuration is not needed.`

But, on WHM you need to do configuration because exim was called from netdata user. By default exim have set `queue_list_requires_admin` to True.

We need to reconfigure this on next way:
1. Login to WHM
2. Service Configuration --> Exim Configuration Manager --> tab Advanced Editor
3. Scroll down to button Add additional configuration settings like on Screenshot
![Screen Shot 2020-02-14 at 10 20 48 AM](https://user-images.githubusercontent.com/53332414/74518595-6aebcd00-4f14-11ea-8995-e03c168eef0e.png)
4. Click on button and in left drop-down choose `queue_list_requires_admin` and set value to false
as on screenshot below.
![Screen Shot 2020-02-14 at 10 21 53 AM](https://user-images.githubusercontent.com/53332414/74518764-ac7c7800-4f14-11ea-8ff1-5bd1b76bbd4f.png)

5. Scroll to the end and click on Save

**Comment by ilyam8** [comment]
Hi @kozicpetar 

Are you willing to make a PR?

Just add a `Requirements` section to the readme, like

> https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/adaptec_raid#requirements

W/o screenshots, just `queue_list_requires_admin` should be set to False and text  descripton (Service Configuration --> Exim Configuration Manager --> tab Advanced Editor ...)

**Comment by kozicpetar** [comment]
Ok, I will do that.
