### ISSUE TITLE
Registry person GUID cookie will eventually stop working in Chrome

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8094]
Chrome displays the following, for cookies set by the current netdata.cloud and by the registry (my-netdata.io).:

A cookie associated with a cross-site resource at http://registry.my-netdata.io/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

We'll need to get it fixed.

**Comment by sk33lz** [comment]
These cookies are now being completely blocked in Chrome 80.0.3987.132.

```A cookie associated with a cross-site resource at http://registry.my-netdata.io/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.```

```A cookie associated with a cross-site resource at http://my-netdata.io/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.```

**Comment by cosmix** [comment]
@jacekkolasa @Azein let's confirm that this is not going to be a problem going forward.
