### ISSUE TITLE
Repeat alarms for a particular alert

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8099]
##### Question summary
I'm using `X509check` module to monitor my webpages SSL certificates. I want to write an alert to send me the alert from a month before expiry and repeat this every day until we reach the certificate end of life or fix the expiration.
I know there is an option to repeat an alarm in an interval [here](https://github.com/netdata/netdata/issues/2956) but I don't want this behavior on all of the alarms, I just want it for the `x509check` alarm. 
Is there any way to achieve this?
Thanks 
##### OS / Environment
netdata v.1.19.0
##### Component Name
health.d

**Comment by ilyam8** [comment]
Hi @yasharne 

you can copy and modify existing alarm adding `repeat` to it

> https://docs.netdata.cloud/health/reference/#alarm-line-repeat

**Comment by ilyam8** [comment]
> you can copy and modify existing 

same way you do it for configuration files - using `edit-config` script

**Comment by yasharne** [comment]
Thanks
