### ISSUE TITLE
alarms shipped with netdata

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#810]
I need a few ideas for alarms that could be shipped with netdata.

Of course the standard alarms should be pretty generic, meaning they should check for conditions that are generally good to check (no niche things).

I am thinking of:
## all web servers and database servers
- [ ] For web servers and database servers, detect requests flood. For example, if the average requests rate of a web server suddenly increases by a factor of 10, we could say the server is under a flood.
- [ ] For web servers and database servers, detect suddenly idle periods. For example, if the average requests rate for the last 10 minutes is above 10/s and suddenly goes to zero/s for 30 seconds, we could raise an alarm.
- [x] mysql availability check
## cpu
- [x] Trigger a warning if `user,system,nice,softirq,irq,guest,guest_nice` (i.e. all except `waitio` and `steal`) cpu utilization is above 90% for 5 minutes
- [x] Trigger a warning if `waitio` cpu utilization is above 10% for 5 minutes
- [x] Trigger a warning if `steal` cpu utilization above 10% for 20 minutes (http://blog.scoutapp.com/articles/2013/07/25/understanding-cpu-steal-time-when-should-you-be-worried)
## memory
- [x] trigger alarm if the server is running out of RAM
- [x] trigger alarm if there is swap activity
## memcached
- [x] add memcached alarm in case it fails.
- [x] trigger a warning if memcached cache size utilization is above 80% and critical if it is above 90%.

Other ideas?

**Comment by LucaDev** [comment]
I would appreciate an alarm if my memcached usage goes over 80%

**Comment by ktsaou** [comment]
> I would appreciate an alarm if my memcached usage goes over 80%

Can you help me figure out how this is to be calculated? Which charts have the values we need?

**Comment by LucaDev** [comment]
@paulfantom is it possible to add the cache size as a chart?

**Comment by paulfantom** [comment]
This should work:
https://github.com/paulfantom/netdata/blob/master/python.d/memcached.chart.py

I don't know why I didn't include this metric.

**Comment by ktsaou** [comment]
we need 2 values: the whole cache size and the used cache size.

**Comment by ktsaou** [comment]
or we can have python plugin calculate the percentage (`used / all`).

**Comment by ktsaou** [comment]
or, to be compatible with the rest of the charts, we could have `used` and `avail`, like `system.mem` does.

**Comment by paulfantom** [comment]
Lines from 556 of [memcached protocol description](https://github.com/memcached/memcached/blob/master/doc/protocol.txt) show what is available.

Maybe we can use `bytes` as `used` and `limit_maxbytes` as `all`?

**Comment by ktsaou** [comment]
@LucaDev I see in this document memcached reports evictions. Is this a better metric?

**Comment by LucaDev** [comment]
If memcached has to remove files from cache its already too late for an warning I guess

**Comment by ktsaou** [comment]
> If memcached has to remove files from cache its already too late for an warning I guess

so this can be the critical one. To build this alarm we need to know the used memory and the total memory or the available memory. Can you help us figure out the numbers we need?

**Comment by LucaDev** [comment]
Yeah, @paulfantom is right. He already made the needed changes in his repo

**Comment by paulfantom** [comment]
I have modified "Cache" chart in [memcached.chart.py](https://github.com/paulfantom/netdata/blob/master/python.d/memcached.chart.py). Now it has two dimensions:
1. `bytes` with name `used`
2. `limit_maxbytes` with name `total`
@LucaDev is my naming right?
@ktsaou will this help you to create requested alarm?

**Comment by LucaDev** [comment]
In my test installation Memcached had a maximum of 64 MB RAM and got filled to around 10 MB
![Memcached Stats](https://cloud.githubusercontent.com/assets/5812715/17888016/553d5d5e-6929-11e6-97e3-4a1c642b3443.png)

**Comment by ktsaou** [comment]
@paulfantom add `wasted` too and I'll do the alarm.

@LucaDev we want:

1. warning when: `$used * 100 / ($used + $wasted + $avail) > 80`
2. critical when the same calculation is ` > 90`

right?

**Comment by paulfantom** [comment]
> add `wasted` too and I'll do the alarm.

Someone knows where can I get this data? I read memcached basic statistics protocol couple times, but I still don't know where this (`wasted`) is coming from.

**Comment by LucaDev** [comment]
I dont think wasted memory is needed in this calculation, because memcached can reuse it if needed, it's just pre allocated.
@paulfantom https://github.com/codeb2cc/phpMemcachedAdmin/blob/4cbea8c5e557f5a60650ad8c0100387d4f000cd9/Library/Data/Analysis.php#L248 This could help

**Comment by paulfantom** [comment]
@LucaDev so to get `wasted` I need another query, since current one doesn't give slab information. Is it really needed?

**Comment by LucaDev** [comment]
No, it isn't. It's just a nice to have but not needed in any way I could imagine

**Comment by ktsaou** [comment]
@LucaDev I have added memcached in PR #845 https://github.com/ktsaou/netdata/blob/master/conf.d/health.d/memcached.conf

I also included a prediction of the hours remaining until memcached runs out of cache.
Can you test it before merging it?

**Comment by LucaDev** [comment]
"cache full percent" is working fine and "last collected secs" is working too but "cache full after hours" wasnt. 
![Screenshot](https://cloud.githubusercontent.com/assets/5812715/18027133/8867d210-6c5b-11e6-8d36-039b5114085b.png)
Do I have to fill it slower?

**Comment by ktsaou** [comment]
It is calculated based on the available size 30 mins ago. Does this chart have 30 mins of data?

---
Sent from my iphone.

27 Αυγ 2016, 14:39, ο/η Luca <notifications@github.com> έγραψε:

**Comment by LucaDev** [comment]
Oh I thought it would use the available data if the last 30mins are not fully available. I'll test it again

**Comment by LucaDev** [comment]
okay, it finally works. Nice!

**Comment by Splo0sh** [comment]
> I need a few ideas for alarms that could be shipped with netdata.

* Alarm when ping response time surpasses certain threshold
* when 'too' many mails are in queue (can be indication for e.g. mailserver being abused)
* network transfer spikes
* openvz quotas like diskspace, inodes etc

since for most of these there are no "normal" values, the alarm could work with a delta, i.e. if the amount of mails in queue, network transfer volume or ping response changes more then X% over a period of time -> alarm?!

Just spit balling here :)

**Comment by ktsaou** [comment]
@cakrit 	working on alarms is a crucial part of netdata.
We have many things to do, like:

- add more alarms for common issues, especially for the monitored applications
- fix the threshold and calculations, so that the alarms will be more useful and less chatty
- provide better notifications
etc

We need to discuss this, by prioritizing the importance of data collection plugins and finding users willing the help us test new alarms in production.

So, I am closing this issue, but please add this to our roadmap.
