### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [netdata/netdata#8103]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/netdata/netdata)](https://www.tickgit.com/browse?repo=github.com/netdata/netdata)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/netdata/netdata)](https://www.tickgit.com/browse?repo=github.com/netdata/netdata)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by prologic** [comment]
Hi @patrickdevivo Please feel free to put up said PR! We welcome all contributions! :)

**Comment by prologic** [comment]
cc @joelhans

**Comment by patrickdevivo** [comment]
https://github.com/netdata/netdata/pull/8115

**Comment by cosmix** [comment]
@cakrit could you please comment on this? I feel you should have the chance to state your opinion on this before it gets approved/rejected.

**Comment by cakrit** [comment]
I'm sorry, but I just don't see the value of putting this in our main README. Let's just create  one or more issues and get rid of the TODOs altogether.

**Comment by prologic** [comment]
```sh
$ sift '(TODO|FIXME|XXX)' | wc -l
179
```

We'll need to figure out how to divide up the work to fix this.

=> #8330

**Comment by patrickdevivo** [comment]
Thanks for considering!

> ```shell
> $ sift '(TODO|FIXME|XXX)' | wc -l
> 179
> ```
> 
> We'll need to figure out how to divide up the work to fix this.
> 
> => #8330

FWIW - adding support for more and custom phrases like `FIXME`, `XXX`, `HACK` etc is on the top of my `// TODO` list!
