### ISSUE TITLE
ACLK Integration testing with the cloud (part 2)

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#8104]
#### Summary
In order to do the testing a cloud endpoint must be available to test the functionality of the
ACLK code in a real environment. Having the infrastructure working we need to verify
the correctness of the data in all cases.

The following tests assume a stable working ACLK connection

- Ensure message delivery and filtering 
  - Parse of messages (verify that the message sent is parse and stored correctly)
  - Handle double messages (verify the cloud side processing)
- Pushed updates for
  - New collectors (on_connect metadata resubmission)
    - Verify the cloud state (that it correctly updates the collector list)
  - New charts
     - Verify the cloud state (that it correctly updates the charts list)
  - New alarms (this is triggered on health reload)
     - Verify the cloud state (that it correctly updates the alarm list)

Note:
- When the agent is in `stable state`, a new chart added by a new collector will trigger a metadata update (due to the collector) and chart update

#### Expected outcome

* A definite structured list of test-cases.
* A list of what passes and what fails.

**Comment by underhood** [comment]
Parse of messages (verify that the message sent is parse and stored correctly) - Core has to fix the topics
Handle double messages (verify the cloud side processing) - verify later

**Comment by amoss** [comment]
The expected outcome on this task is described in the OP above. When the ACLK is connected we need a documented method to test:
* Incoming message are parsed correctly.
* Duplicate message are dropped.
* Outgoing messages are correctly generated for new collectors.
* Outgoing messages are correctly generated for new charts.
* Outgoing messages are correctly generated for new alarms.

If the cloud-side is ready then this becomes documenting how we observe changes in the cloud state. If the cloud-side is not ready then it becomes a paho script to inject / display messages at the broker.

**Comment by amoss** [comment]
I had a chat with @fracasula and I will write something to provoke the test cases that we need for the pushed updates.
