### ISSUE TITLE
custom template is not loading in the master netdata server

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8106]
##### Question summary
We have a few streaming servers streaming their metrics to a central netdata server, on one of this machines, we have enabled `dns_query` plugin which has four jobs, first one is querying one of our addresses from the DNS inside our datacenter (afranet), the second one is querying the same address from a DNS inside another DC we have, The third one is querying the address from a DNS server inside our country and the last one is querying the address from OpenDNS DNS servers.
I want to write a health template which puts a threshold on each of these charts, for example, the RTT of querying the name from `afranet` should be bellow 10ms. So I write this template and put it inside `/opt/netdata/etc/netdata/health.d/dns_query.conf`:
```
template: dns_query_rtt
families: *
      on: dns_query_afranet_servers_from_afranet_dns.query_time
  lookup: average -25s unaligned of time
   every: 30s
   units: ms
    crit: $this > 10
    info: the average rtt over the last 25s for querying an afranet server from the afranet DNS
      to: sysadmin
```
But after `killall -USR2 netdata` I don't see the template inside `Alarms -> All` of the server if have enabled `dns_query`
Here is the chart:
![image](https://user-images.githubusercontent.com/7656049/74634053-5c9deb00-5178-11ea-97b2-b25a21960a9b.png)

##### OS / Environment
netdatav1.19.0
##### Component Name
health

**Comment by ilyam8** [comment]
> template: dns_query_rtt
families: *
      on: dns_query_afranet_servers_from_afranet_dns.query_time

should be `alarm`

templates `on` on context, alarms on `char id`

**Comment by ilyam8** [comment]
Keep in mind that `alarm` applies only on the specific chart, if you have several  dns_query jobs, you need to use `template`.
