### ISSUE TITLE
ACLK agent side hashing to reduce data transfer to the cloud

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#8107]
#### Summary
Discuss common hashing with the cloud on objects like collectors, charts, alarms etc so that the
agent can avoid sending data to the cloud that has not changed.

To make this meaningful it should also affect the way we send on_connect messages. Right now we are sending the entire set of e.g. of charts, alarms.

When the ACLK is established there must be a way for the agent and the cloud to exchange hash information (agent requests the hash list from the cloud).
 
A simple example 1 (to avoid charts resubmission)
1. Agent creates a hash for a `chart object`
2. Sends a chart update
3. ACLK drops
4. ACLK established again. 
5. Chart will not be resent (hash value has not changed)

A simple example 2 (chart hash list synchronized)
1. Agent starts
2. ACLK established
3. Agent requests chart hash list from the cloud
4. Individual chart updates are scheduled
    - Chart hash value computed
    - Chart update is skipped because the computed hash matches the cloud side

#### Expected outcome
- Significant reduction in the ACLK traffic
- Reduced processing load on the cloud side

**Comment by amoss** [comment]
This work has not been agreed or scoped. We will reopen it if we decide to do it.
