### ISSUE TITLE
[eBPF]: Handle dynamic Kernel changes automatically

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8118]
##### Feature idea summary

As discussed [in this thread](https://github.com/netdata/netdata/pull/8075#discussion_r380184416) we want to be able to support dynamic Kernel changes on a system (_upgrades or downgrades_) and automatically handle this without user intervention. The installer currently works fine and does mostly the right thing regarding picking the right published eBPF package from the [kernel-collector](https://github.com/netdata/kernel-collector) repo on NetData Agent installation.

##### Expected behaviour

The implementation of this feature should:

- Re-use the existing installer logic for installing the "right" eBPF Package. ✅
- Wrap this same logic in a shell script for re-use by the Agent.
- Automatically detect Kernel changes (_up or down_) by the Agent; and invoke the above script.

Future enhancements of script (_to be named_) _may_ also do on-demand building of the eBPF package(s) for a user's system on their behalf (_to be discussed_). The scope of this feature however is to only support kernel changes and download the "right" eBPF packages(s) re-install/re-configure without user intervention.

**Comment by prologic** [comment]
@thiagoftsm Please correct me if I'm wrong, but since we now detect the running Kernel version at run-time and load the appropriate "shared library" or "stub + kernel specific implementation program" (_for upcoming static support_) this can be closed. This is effectively done IHMO. I will therefore close it.

**Comment by thiagoftsm** [comment]
I agree this could be closed.
