### ISSUE TITLE
Setup CI for macOS

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8120]
As per title. We desperately need to stop getting bitten by *BSD nuances and take BSD more seriously. Let's first off setup CI so PR(s) actually fail if they do not work correctly on *BSD systems.

**Comment by amoss** [comment]
If a team member raises the issue I assume it does not require triage :)

**Comment by prologic** [comment]
Probably not 🤣

**Comment by Ferroin** [comment]
For macOS, the build itself should be done via `brew sh`.

**Comment by prologic** [comment]
> For macOS, the build itself should be done via `brew sh`.

As mentioned in another PR by @cosmix and myself in person; I didn't even know about `brew sh` at all :) And I _think_ we should make things work without. It is/wasn't that hard to do and I don't think many users will drop into a `brew sh` just to run the installer.

**Comment by Ferroin** [comment]
> > For macOS, the build itself should be done via `brew sh`.
> 
> As mentioned in another PR by @cosmix and myself in person; I didn't even know about `brew sh` at all :) And I _think_ we should make things work without. It is/wasn't that hard to do and I don't think many users will drop into a `brew sh` just to run the installer.

For the installer itself, yeah, people won't run it from `brew sh` most of the time.

_However_, I'd be willing to be a a large sum of money that most of our users on macOS are using Homebrew, not the install script, and the build environment that Homebrew uses is equivalent to `brew sh`.

**Comment by prologic** [comment]
> _However_, I'd be willing to be a a large sum of money that most of our users on macOS are using Homebrew, not the install script, and the build environment that Homebrew uses is equivalent to `brew sh`.

This is true :)

**Comment by prologic** [comment]
This is not a bug but a feature-request for our CI

**Comment by cakrit** [comment]
Modified to set up CI for MacOS, as we have a different issue for FreeBSD
