### ISSUE TITLE
is "bind to" in default configuration used?

### ISSUE THREAD

**Issue by stormi** [netdata/netdata#8123]
##### Question summary
The default `netdata.conf` file has this option under the `[global]` section:
```
bind to = localhost
```

However when I download netdata.conf from localhost:19999 I see this added comment: "option 'bind to' is not used."
```
[...]
[global]
        run as user = netdata
        history = 3996

        # option 'bind to' is not used.
        bind to = localhost
[...]
```

I know about the 'bind to' option in the web section, but is the 'bind to' option from the global section useful at all? If yes, in what context?

**Comment by stelfrag** [comment]
Hi @stormi 

There is an internal config move  for `bind to` from the `[global]` section to the `[web]` section. So it is a backwards compatible option

**Comment by stormi** [comment]
Then is there a reason not to move it to the web section in the default `netdata.conf` ?
