### ISSUE TITLE
Unecessary link when installing eBPF

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8127]
##### Bug report summary
While I was installing eBPF using `--enable-ebpf`, I detected that in my directory I have a symbolic link `libbpf_kernel.so.0` to the shared library, but we only need this link in the LD_LIBRARY_PATH directories.

##### OS / Environment
```
Linux hades 5.4.20 #1 SMP Sat Feb 15 14:02:24 UTC 2020 x86_64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="14.2"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=14.2
/etc/os-release:PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
/etc/os-release:HOME_URL="http://slackware.com/"
/etc/os-release:SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"                                                                                                                                                                                         
/etc/os-release:VERSION_CODENAME=current   
```

##### Netdata version
netdata v1.19.0-645-gdd3d85ac 

##### Component Name
Netdata installer

##### Steps To Reproduce
1. Run `./netdata-installer.sh ---enable-ebpf`

##### Expected behavior
To have symbolic only on shared library directories

**Comment by prologic** [comment]
This only happens here:

https://github.com/netdata/netdata/blob/3e970168ad2ede15079b70dbab97031f5b362261/netdata-installer.sh#L1200

And there's only one instance of running `ln` here

So I'm a little confused as to how this is possible?

**Comment by thiagoftsm** [comment]
I retest now, compiling from scratch and I could confirm that Netdata is creating an unnecessary symbolic link:

![VirtualBox_Slackware_Kprobes_18_02_2020_21_39_54](https://user-images.githubusercontent.com/49162938/74780589-d11b7b80-5297-11ea-999e-c67dd7f08a66.png)

**Comment by prologic** [comment]
You mean the one in `/home/...`?

**Comment by thiagoftsm** [comment]
> You mean the one in `/home/...`?

yes, this was the place I compiled, I was expecting to have only the other shared link.
