### ISSUE TITLE
No support for install-required-packages.sh for FreeBSD

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8130]
##### Bug report summary

As per title. See:

```sh
root@freebsd:~/netdata # ./packaging/installer/install-required-packages.sh --dont-wait --non-interactive netdata-all
Cannot find an os-release file ...
Cannot find valid distribution with lsb-release

I NEED YOUR HELP
It seems I cannot detect your system automatically.
Running in non-interactive mode
 > Bailing out...

```

##### OS / Environment

```sh
root@freebsd:~/netdata # uname -a
FreeBSD freebsd 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64
```

##### Netdata version

```sh
root@freebsd:~/netdata # git rev-parse --short HEAD
3e970168a
``` 

##### Component Name

- area/packaging

##### Steps To Reproduce

1. Setup a FreeBSD VM
2. Clone the netdata repo
3. Run: `./packaging/installer/install-required-packages.sh`
4. Observe the output

##### Expected behavior

We support installing all the right tools automatically on FreeBSD without the user having to go find what needs to be installed in our docs or through trial 'n error.

**Comment by Ferroin** [comment]
Part of the problem here is that users may not want to use binary packages on FreeBSD. There's also the [FreeBSD Ports Tree](https://www.freebsd.org/ports/), and some users even just choose to DIY everything. We can't automatically know which people prefer.

**Comment by prologic** [comment]
Don't users have a choice here already?

If you want to do things manually; go right ahead.

If you want to take advantage of our 1-line installer / kickstart we need this.

We can take the approach of just `pkg install xyz` like we tell users to in the docs and of course use all the same logic with prompts, etc.

I _feel_ like we should do this :)

**Comment by Ferroin** [comment]
> Don't users have a choice here already?

No, not really. This script gets run unconditionally whenever you run the kickstart installer.

**Comment by prologic** [comment]
Oh yes I'm aware of that; that's not at issue here. And until we have full proper binary packages everywhere we must still support this method of installation.

The thing is; in the recent weeks I've been playing around with various *BSD(s) and some users they don't seem at all too grumpy about using `pkg` anyway; so I don't really see a big issue here per se; we pick the best option we can and go with it.

If users want to do things manually on their own; that's fine but don't expect our tools to help too much (_because you've chosen to do things by hand :/_)

**Comment by prologic** [comment]
So... When I get back to this (_probably on Sat now_) I will add support for FreeBSD using `pkg`. This is the plan of record :)

**Comment by Ferroin** [comment]
At least double check that stuff installed through the ports tree will register as existing on the system so we don't overwrite it if it's there. I think it _should_ be picked up correctly, but I'm not certain.

**Comment by prologic** [comment]
Fixed by https://github.com/netdata/netdata/pull/9413
