### ISSUE TITLE
One line install no loger works on AWS Amazon Linux

### ISSUE THREAD

**Issue by raul-reclique** [netdata/netdata#8132]
##### Question summary

One line install used to work on AWS Amazon Linux. Version 2.9.2 no longer works. It had been installing automatically for close to a year. Now, system is updated but fails:

```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
...
yum install Judy-devel autoconf-archive libuv-devel 
Loaded plugins: priorities, update-motd, upgrade-helper
No package Judy-devel available.
No package autoconf-archive available.
No package libuv-devel available.
```

##### OS / Environment

 AWS Amazon Linux. Version 2.9.2
Amazon Linux AMI release 2018.03

##### Things I tried

I read that `Judy-devel` needed epel-release but it's already installed and up-to-date

```
sudo yum install -y epel-release
# Output:
Package epel-release-6-8.9.amzn1.noarch already installed and latest version
Nothing to do
```

**Comment by prologic** [comment]
Hhi @raul-reclique 

Are you able to rule out a few things with me (_itll be quicker than me spinning up an AWS EC2 right this minute_):

Can you clone our repo and run the following?

```sh
$ git clone https://github.com/netdata
$ ./packaging/installer/install-required-packages.sh --dont-wait --non-interactive netdata-all
```

Remove the `--non-interactive` if you'd prefer to be prompted and be sure what its doing.

If you can provide me the output or relevant bits of the output that would be great!

**Comment by raul-reclique** [comment]
```
Unknown distribution ID: amzn
./packaging/installer/install-required-packages.sh: line 977: validate_tree_rhel: command not found

/etc/os-release information:
NAME            : Amazon Linux AMI
VERSION         : 2018.03
ID              : amzn
ID_LIKE         : rhel fedora
VERSION_ID      : 2018.03

We detected these:
Distribution    : rhel
Version         : 2018.03
Codename        : 2018.03
Package Manager : install_yum
Packages Tree   : rhel
Detection Method: /etc/os-release
Default Python v: 2 

... # Does some checkings 

Running in non-interactive mode
sudo yum -y install Judy-devel MySQL-python autoconf-archive libuv-devel lm_sensors nodejs python-psycopg2 python-pymongo 
Loaded plugins:net priorities, update-motd, upgrade-helper
amzn-main                                                                                                                                                                | 2.1 kB  00:00:00     
amzn-updates                                                                                                                                                             | 2.5 kB  00:00:00     
No package Judy-devel available.
Package MySQL-python26-1.2.3-11.14.amzn1.x86_64 already installed and latest version
No package autoconf-archive available.
No package libuv-devel available.
No package lm_sensors available.
No package nodejs available.
Package python26-psycopg2-2.5.1-3.8.amzn1.x86_64 already installed and latest version
No package python-pymongo available.
Nothing to do

All Done! - Now proceed to the next step.
```

**Comment by prologic** [comment]
Thanks! This is what I suspected! I'm not entirely sure we ever broke this per se; so I will do some poking/digging around on an Amazon Linux system (_assuming I can get my hands on one without AWS/EC@; otherwise I'll spin one up_). bare with me... I'll respond by the end of today.

**Comment by raul-reclique** [comment]
I don't think a netdata change broke it. most likely an AWS update to their repos caused it. But I couldn't even figure out a workaround and we liked using netdata! Thanks for your help!

**Comment by raul-reclique** [comment]
@prologic did you find a workaround for this?

**Comment by prologic** [comment]
> @prologic did you find a workaround for this?

My apologies! I got side-tracked with the [v1.20.0](https://github.com/netdata/netdata/releases/tag/v1.20.0) release and supporting new eBPF collector features.

I will get this fixed today. The only work-around is to install the missing packages yourself which I'll be doing so myself and updating our installer. The other thing you can try is our static installer which is documented [here](https://docs.netdata.cloud/packaging/installer/methods/kickstart-64/) if you'd like to try that.

**Comment by prologic** [comment]
I sadly _thought_ I could repro and fix this locally with a local instance following [these docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html#amazon-linux-2-virtual-machine-download) and using [this image](https://cdn.amazonlinux.com/os-images/2.0.20200207.1/virtualbox/) but sadly this doesn't get me the version of Amazon Linux you report nor a reproducer:

```sh
[ec2-user@amzn2 netdata]$ uname -a
Linux amzn2 4.14.165-131.185.amzn2.x86_64 #1 SMP Wed Jan 15 14:19:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[ec2-user@amzn2 netdata]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
[ec2-user@amzn2 netdata]$
```

**Comment by prologic** [comment]
@raul-reclique I _note_ that you are using an Amazon Linux AMI _much_ older than I seem to be able to get my hands on. Is there any chance you _could_ upgrade from `2018.03` to `2.0.2`? (_they seem to have changed their versioning scheme?_)

**Comment by prologic** [comment]
@raul-reclique As I don't currently have an Amazon EC2 account; would you terribly mind exporting that AMI using [these instructions](https://aws.amazon.com/ec2/vm-import/) as a VMDG or similar so I can better help and hopefully fix? (_if possible_)

**Comment by raul-reclique** [comment]
@prologic the version listed on the interface is 2.9.2 . I am not sure why the os-release says something different than the interface. Even if a launch a new environment it lists as 2.9.2 on the yml configuration, but then the os-release says 2018.03. it does not seem like I can upgrade any further but I might be locked into LTS releases.

my uname -a does seem to be ahead of yours 4.14.158 (mine) > 4.14.165 (yours):

```bash
[ec2-user@ip-... ~]$ uname -a
Linux ip-... 4.14.158-101.185.amzn1.x86_64 #1 SMP Tue Dec 24 03:25:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I will try to get AWS to shed light on the versioning issue.

**Comment by prologic** [comment]
@raul-reclique Yeah the version of Amazon Linux I was able to get a hold off for premises testing seems to be `2.0.20200217` as indicated by the image `-amzn2-virtualbox-2.0.20200207.1-x86_64.xfs.gpt.vdi` and the above `/etc/os-release` output. I am not able to repro as it is right now either a) Getting an exported VM image of your instance (_see above_) or b) Getting an EC2 myself (_working on this_) to spin up the same AMI.

**Comment by prologic** [comment]
Meanwhile I recommend you use the static installer until I get this sorted out (_see above_)

**Comment by raul-reclique** [comment]
the static installer does work and I will adjust to it and use it instead. thanks for your help!

**Comment by prologic** [comment]
Your welcome!

**Comment by Agronis** [comment]
@prologic if I may help resolve this issue, do please let me know.

I too have a whole swath of servers on 2018.03 and the primary one-liner fails as mentioned.

Particularly on libuv-devel even though
`Package 1:libuv-devel-0.10.34-1.el6.x86_64 already installed and latest version`

epel-release is also installed, and up to date

However, as also mentioned, static install works just fine.

**Comment by prologic** [comment]
@Agronis If you can get my a rootfs or disk image of the system in question I can help get this fixed. Let me know if you can make that happen :)

**Comment by issacchern** [comment]
Hi there, I am also having issue using the standard script:
bash <(curl -Ss https://my-netdata.io/kickstart.sh)

Like others said or suggested, the command line below works:
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)

Not sure if this helps, but here's the os info:

[ec2-user@data-rs netdata]$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Comment by prologic** [comment]
As stated above in my comments, I haven't been able to get a hold of older Amazon Linux images for me to be able to repro and potentially fix the issue. PR(s) at this point are welcome! Unfortunately I also haven't had any offers of anyone exporting a fresh Amazon LInux AMI of the problematic version to a VMDK or QCOW image. If someone is able to provide me with one I can absolutely see what's going on!

Thanks!

**Comment by vbakayev** [comment]
Hey @prologic ,

I'm running few EMR clusters, which operate based on Amazon Linux 2018.03, and I'm running into this on a regular basis :) Till now my repeatable solution was to do repository checkout, and then return back to commit before libuv2 dependency got introduced: 198c7fa

Few ideas:

1) Amazon Linux packages are listed on https://aws.amazon.com/amazon-linux-ami/2018-03-packages/, no indication of "libuv" or alike. It might be available in externally generated repos, but base image or default repository does not contain needed.

2) I'm pretty convinced that exporting AMI image into VMDK still can be done even with free tier, more here: https://docs.aws.amazon.com/vm-import/latest/userguide/vmexport_image.html. If this does not work for you, I'll do that myself and PM you with link to downloaded image.

**Comment by prologic** [comment]
Just a thought; but are you able to use our static binary instead? `kickstart-static64.sh`?

**Comment by vbakayev** [comment]
Yes, static binary install works flawlessly.

**Comment by prologic** [comment]
> Yes, static binary install works flawlessly.

Are you happy with that for the time being? I would love to build native support for compiling on AWS instances and packaging for it but I don't have the bandwidth now.

**Comment by vbakayev** [comment]
As I said, as a temporary measure, static binary works for us.
