### ISSUE TITLE
install-required-packages.sh fails on Clear Linux

### ISSUE THREAD

**Issue by jptuomi** [netdata/netdata#8137]
The experimental packages installer failed.

This is what it says:

```txt

Loading /etc/os-release ...
Unknown distribution ID: clear-linux-os
Unknown distribution ID: clear-linux-os
Cannot find valid distribution in: clear-linux-os clear-linux-os
Cannot find valid distribution with lsb-release

I NEED YOUR HELP
It seems I cannot detect your system automatically.
And it seems I cannot find a known package manager in this system.
Please open a github issue to help us support your system too.

```

Clear Linux itself provides a so called bundle for netdata, however it is outdated and doesn't include Judy for dbengine support.

The latest version is installable through compiling with kickstart.sh, however judy doesn't get compiled there either since that is part of the centOS-setup IIRC.

Further Clear Linux is based on a [stateless design](https://docs.01.org/clearlinux/latest/guides/clear/stateless.html) where libraries and applications added outside of their package-management system swupd should be stored in /usr/local, /etc, /opt, /home etc. This would be fine, however pkg-config doesn't look in /usr/local/lib/pkgconfig for the .pc-file from my own compiled libJudy.

Best regards
Johan Tuomi

**Comment by prologic** [comment]
@Ferroin As discussed today I _think_ you're all over this. I have no bandwidth myself as I'm doing similar things for *BSD! Yell out of course if you need a hand!

**Comment by Ferroin** [comment]
> @Ferroin As discussed today I _think_ you're all over this. I have no bandwidth myself as I'm doing similar things for *BSD! Yell out of course if you need a hand!

Yeah, I can cover it. It's just dependent at the moment on me getting a Clear Linux VM set up to test in. If not today, I should have a chance to get to it either tomorrow or early next week.

**Comment by jptuomi** [comment]
That is just great, the changes look solid.
I will run this asap when family life ain't getting in the way.
devpkg-Judy is on its way as well according to: [clearlinux / distribution #1761](https://github.com/clearlinux/distribution/issues/1761#issuecomment-588527023)
