### ISSUE TITLE
Daily Out-Of-Memory error and restart

### ISSUE THREAD

**Issue by willhseitz** [netdata/netdata#8140]
##### Bug report summary

I have noticed that my netdata master node is reporting >90% memory daily. After checking logs, I see that the netdata process is slowly filling up to max 8gb (and 4gb swap) daily, then killing itself and starting again. I looked at graphs under the Netdata Monitoring section, but I dont see any type of growing queue, etc.

I found open Issues https://github.com/netdata/netdata/issues/7566 and https://github.com/netdata/netdata/pull/7565 that looks related, but I don't think it's memory related. Closed Issues https://github.com/netdata/netdata/issues/5835 and https://github.com/netdata/netdata/issues/1168 seem like they could be related.

Here is the last ~2 days of App memory:
![netdata OOM](https://user-images.githubusercontent.com/17074342/74858281-e32e0600-52f9-11ea-92d3-0db93d7f4e81.png)

In syslog, I see the kernel filling up swap to max, then killing netdata:
```
Feb 18 18:36:33 netdata-01 kernel: [985056.500441] Swap cache stats: add 5692136, delete 5692044, find 918156/1017798
Feb 18 18:36:33 netdata-01 kernel: [985056.500441] Free swap  = 0kB
Feb 18 18:36:33 netdata-01 kernel: [985056.500442] Total swap = 4038652kB
...
Feb 18 18:36:33 netdata-01 kernel: [985056.500491] Out of memory: Kill process 5016 (netdata) score 1966 or sacrifice child
Feb 18 18:36:33 netdata-01 kernel: [985056.501620] Killed process 5016 (netdata) total-vm:13534880kB, anon-rss:7815584kB, file-rss:0kB, shmem-rss:0kB
```
I'm seeing OOM logs like above for each netdata plugin, each a couple minutes apart:
```
$ grep /var/log/syslog.1 -e "Killed"
Feb 18 17:18:34 netdata-01 kernel: [980376.642223] Killed process 5335 (python) total-vm:150004kB, anon-rss:21812kB, file-rss:0kB, shmem-rss:0kB
Feb 18 17:18:46 netdata-01 kernel: [980389.449747] Killed process 5317 (nodejs) total-vm:704120kB, anon-rss:6012kB, file-rss:0kB, shmem-rss:0kB
Feb 18 18:16:38 netdata-01 kernel: [983795.207442] Killed process 5338 (go.d.plugin) total-vm:125724kB, anon-rss:2876kB, file-rss:0kB, shmem-rss:0kB
Feb 18 18:23:28 netdata-01 kernel: [984160.442996] Killed process 22157 (apps.plugin) total-vm:21648kB, anon-rss:1896kB, file-rss:0kB, shmem-rss:0kB
Feb 18 18:24:45 netdata-01 kernel: [984273.333784] Killed process 25701 (bash) total-vm:19244kB, anon-rss:1156kB, file-rss:0kB, shmem-rss:0kB
Feb 18 18:36:33 netdata-01 kernel: [985011.659413] Killed process 22233 (bash) total-vm:18640kB, anon-rss:496kB, file-rss:0kB, shmem-rss:0kB
Feb 18 18:36:33 netdata-01 kernel: [985056.501620] Killed process 5016 (netdata) total-vm:13534880kB, anon-rss:7815584kB, file-rss:0kB, shmem-rss:0kB
```

Using `dbengine` with 2gb memory and 10gb disk storage:
```
    page cache size = 2048
    dbengine disk space = 10240 
```

##### OS / Environment

1 master node and 6 streaming nodes. The OOM issue is only happening on the master node. All are set to update on nightly branch and currently on `v1.19.0-533-nightly`
```
$ uname -a; grep -Hv "^#" /etc/*release
Linux netdata-01.unwiredbb.net 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic

```

##### Netdata version

 netdata v1.19.0-533-nightly

##### Component Name

Netdata master daemon?

##### Steps To Reproduce

1. ...
2. ...

**Comment by mfundul** [comment]
As described in the [documentation](https://github.com/netdata/netdata/blob/master/database/engine/README.md#configuration) this configuration applies per database instance. There is one instance for localhost and one per streaming node.

The aggregate page cache size is over 14GiB and the storage space over 70GiB. The memory requirements are even larger than that, look [here](https://github.com/netdata/netdata/blob/master/database/engine/README.md#memory-requirements) for reference.

**Comment by willhseitz** [comment]
Ah, that makes much more sense. I missed that those settings are **per** streaming node :)
Thank you for the quick response!
