### ISSUE TITLE
Error installing required packages on CentOS 8.1

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8149]
As mentioned in #7966 runing `./packaging/installer/install-required-packages.sh` fails on CentOS 8.1

This was tested throughly and known to work s; I'm not sure what happened here or what go tmissed.

To repro:

```sh
prologic@Jamess-iMac
Fri Feb 21 10:33:09
~/NetData/netdata
 (master) 0
$ git rev-parse --short HEAD
5f9250b9

prologic@Jamess-iMac
Fri Feb 21 10:35:02
~/NetData/netdata
 (master) 0
$ docker run -i -t --rm -v "$PWD":/netdata -w /netdata centos:8 /bin/sh -c './packaging/installer/install-required-packages.sh --dont-wait --non-interactive netdata-all' | tee log
```

=> [log](https://gist.github.com/prologic/2e648090f98f7410b329a7a01508c48e)

**Comment by Xplouder** [comment]
@prologic Thank you for the quick replies!

**Comment by prologic** [comment]
> @prologic Thank you for the quick replies!

You're welcome :) If you happen to know how to fix this in our `./packaging/installer/install-required-packages.sh` script I'd be more than happy to review and accept a PR from you! Otherwise I'll get to it after today.

**Comment by prologic** [comment]
This got fixed likely by the following commits:

- * ff4eb9c8 2020-03-10 | Fix cosmetic error checking for CentOS 8 version in install-required-packages (#8339) [James Mills]
- * 72d35831 2020-03-05 | Fix RHEL / CentOS 8.x dependencies for Judy-devel and others (#8202) [James Mills]

This no longer repros:

```sh
$ git rev-parse --short HEAD
2bbcb930

$ docker run -i -t --rm -v "$PWD":/netdata -w /netdata centos:8 /bin/sh -c './packaging/installer/install-required-packages.sh --dont-wait --non-interactive netdata-all' | tee log
```

=> [log](https://gist.github.com/prologic/0c07980b3f7a3fd3f27cf553e6898cf9)
