### ISSUE TITLE
ACLK update build to use libwebsocket static lib

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#8152]
##### Feature idea summary
On systems with Libwebsockets <3 we should use Libwebsockets 3 build by installer.

##### Expected behavior
autotools build system should (in following order):
- Check shared library libwebsockets 3+ is present in system. If it is use it for ACLK
- Check static library build of libwebsockets exists (by installer). If it is use it for ACLK
- If both previous steps failed do not build ACLK

**Comment by amoss** [comment]
I'm flipping the milestone so that this is visible on the board during stand-up.
