### ISSUE TITLE
Handle the case of systems which do not have libJudy available as a package.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8153]
##### Feature idea summary

Either:

1. Use a similar approach to what we're currently doing with our custom fork of libmosquitto and plan to do for libwebsockets3. Namely, look to see if Judy is available, and build it locally if it is not.
2. Just bundle the Judy souces as part of our source tree and unconditionally use those instead of any system version of Judy.

Personally I'd lean more towards the second case (as we functionally remove a dependency that most users would not otherwise have on their systems that way), but I'm probably not the best person to do the development for that.

@netdata/core, @cosmix Opinions on this would be appreciated.

##### Expected behavior

We no longer require the system to have libJudy installed at build time to be able to use components that depend on it.

**Comment by mfundul** [comment]
Number 2. seems good to me, we only need to be aware that there are extra patches which are out of tree, depending on the distribution, or on whether Windows are being used (for when we port to Windows).

**Comment by Ferroin** [comment]
Are the distro patches just to get Judy to build, or are they for some other functionality?

**Comment by Ferroin** [comment]
Are the distro patches just to get Judy to build, or are they for some other functionality?

**Comment by mfundul** [comment]
The official repository is this one: https://sourceforge.net/projects/judy/files/judy/Judy-1.0.5/

I think the patches are for both building and bugfixes, some examples:
https://github.com/plq/libjudy/commit/c2c23fe3062b9b8e4cc3ca4a6168f0bb95aa21c0
http://launchpadlibrarian.net/205863092/judy_1.0.5-4_1.0.5-5.diff.gz

Maybe we can look at what Ubuntu is building and compare.

**Comment by prologic** [comment]
I'm tired of dealing with all these Judy problems we have. I'ma actually stuck on one in particular for CentOS/RHEL 8.x so this needs to be done with a matter of priority.

@mfundul I've imported from SVN (_because I don't trust anyone out there_) and started importing patches I can found that seem legit.

https://github.com/prologic/judy

I am however unable to currently import the Ubuntu patches as yet -- They look like they were made on the `1.0.5` tag. We _might_ have to rewrite that patch on `master` and then we can cut a point release and use this as our bundled Judy like we have done with other problematic dependencies.

Appreciate if you could help out here especially with reviews of the patches I'm pulling in at https://github.com/prologic/judy/pulls
