### ISSUE TITLE
Loop add all GPU charts to custom dashboard

### ISSUE THREAD

**Issue by rmrao** [netdata/netdata#8156]
Hi, I'm trying to build a custom dashboard for monitoring a number of GPU servers, each of which have a different number of GPUs. I've been able to enable the `nvidia_smi` plugin. Now, I'd like to build something like the example in `dash-example.html`, but for each host, add a graph for `nvidia_smi.gpu{x}_mem_usage` for each value of x, if that x exists in the returned data for the host.

Is there an example of how to do this, or something similar? I know that in the default netdata dashboard, this information is looped over and added, but I'm not exactly an expert web developer, so if you could at least point me towards where that happens, that would be great.

Thanks!

**Comment by ilyam8** [comment]
@jacekkolasa please take a look

**Comment by jacekkolasa** [comment]
Hi @rmrao ,
Default Netdata Dashboard builds charts based on 2 sources:
1. dashboard_info.js - https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info.js, with an option to customize it - https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info_custom_example.js
2. [/api/v1/charts](https://london.my-netdata.io/api/v1/charts) endpoint

The logic behind it is here, but it's a little complicated - https://github.com/netdata/netdata/blob/master/web/gui/main.js#L1690-L1929

Perhaps building dashboard_info_custom.js would fit your needs?

If you want to build totally custom dashboard, you could fetch /api/v1/charts endpoint with js and build charts (divs) based on this, using `div.innerHTML = "yourDynamicChartsList"`, and then calling `NETDATA.start()`.

**Comment by rmrao** [comment]
Thanks for pointing this - I actually think I mostly figured it out and forgot to close the issue. I basically did as you suggested and fetched the charts endpoint.
