### ISSUE TITLE
Add mesos-spawned container UUIDs to container naming

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8160]
So while waiting on "real" mesos/marathon support (and by all means, keeping working on Kube first; I'm sure that has a bigger audience), I quickly threw together this extension to cgroup-name.sh (https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh.in) I thought I'd post it up here in case anyone was interested.  I figured that the plan to do true support will likely completely supersede these efforts, so I didn't bother to kick it in as a PR.  But since I've found it useful enough in the interim, for our use case at least, that I thought it might others might want to try it out.  In this case, it renames the presented counter values for mesos managed docker containers to something that is more useful to identify them, in coordination with the orchestration model.

In this case, it identifies containers of this type using the current "mesos-" naming convention of the container that is instanced.  When found (and using the docker classic model), it retrieves the image name and tag, crunches that down to eliminate repo/library information, replaces the characters that would make the result not play well with the UI and other backends (we use graphite/grafana, with which netdata's integration is really great!), and adds on the last portion of the UUID to keep it unique and easy to find in the mesos UI.  

I figured it's not useful to everyone, nor is particularly hardened.  And it's not as good as getting a list of the current marathon app ids, chasing those down to the mesos spawned containers UUIDs (which I suspect will be the ideal use case when this ticket gets formally considered). But since it has no reliance on anything except what is visible to the local cotainerizer, it was a nice easy hack for the time being. I certainly find it useful so thought I would post it here in case it was interesting to anyone else while this ticket for more complete support is pending consideration.

Keep up the great work guys!
[cgroup-name.sh.txt](https://github.com/netdata/netdata/files/2979941/cgroup-name.sh.txt)

_Originally posted by @rob-duewer in https://github.com/netdata/netdata/issues/4881#issuecomment-474069938_

**Comment by cakrit** [comment]
@amoss please assign and plan

**Comment by lordraiden** [comment]
Withis this the Docker version of netdata will identify docker names?
Will change something in docker config or is just an internal change?

> root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Netdata' --net='br0' --ip='192.168.1.209' --cpuset-cpus='3,7' -e TZ="Europe/Paris" -e HOST_OS="Unraid" -v '/mnt/user/Docker/Netdata/':'/etc/netdata/override':'rw' -v '/proc':'/host/proc':'ro' -v '/sys':'/host/sys':'ro' -v '/var/run/docker.sock':'/var/run/docker.sock':'ro' --dns=10.10.50.2 --cap-add SYS_PTRACE --security-opt apparmor=unconfined --log-opt max-size=200m --log-opt max-file=1 'netdata/netdata'

a57393a79e26a731be0c5132405a9e73d968dacfa98986e26c9a2a19dfdc7fae

![imagen](https://user-images.githubusercontent.com/17175395/75826188-38145680-5da7-11ea-99ff-1edcd4e55f08.png)

**Comment by rob-duewer** [comment]
Just in case it's useful to you, I don't think so.
All my suggestion does is internally manipulate the name string, when what's coming into the cgroup-name plugin helper script matches the pattern.  So if the internally incoming determined cgroup identifier doesn't have the docker- and then later, the mesos- naming structure; it won't affect what you see at all.  And the way I wrote it thus far, that second level of parsing after determining mesos ownership, relies on the "classic" model to get the image information. And that requires execution of the docker CLI.  Which I'm not certain is available when running netdata as a container itself within the particular host.  (I'm no expert on that part though, we use it bare on our nodes so the CLI is always available.)

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
