### ISSUE TITLE
Hardcoded values in web ui prevent running from a subdirectory

### ISSUE THREAD

**Issue by Whisprin** [netdata/netdata#8166]
##### Bug report summary
Netdata and apache is configured as described in the [docs](https://docs.netdata.cloud/docs/running-behind-apache/).
I can access netdata via https://my.host/netdata.
However, there's just black text on white background. No html or js is available.

[netdata/web/gui/index.html](https://github.com/netdata/netdata/blob/master/web/gui/index.html#L16) contains hardcoded values to `main.css`, `main.js` and `dashboard.js`. When I manually prepend `netdata/` to those I can see and access the webinterface.

##### OS / Environment

```
Arch Linux 5.4.19-1-lts
```

##### Netdata version

 1.19.0

##### Component Name

web

##### Steps To Reproduce

Install netdata, setup apache with mod_proxy and access netdata web trough a server subfolder.

##### Expected behavior

I can see the web ui served from a subfolder.

**Comment by cakrit** [comment]
Hi @Whisprin, the instructions work fine. Is the `rewrite` module enabled as well? Please provide your relevant apache configuration, without any hostnames/IPs.

**Comment by cakrit** [comment]
Oh, I should say that I added #8169, because `apache2-bin` didn't install `a2enmod` on Ubuntu, but the rest is fine.

**Comment by Whisprin** [comment]
Thanks @cakrit, yes, mod_rewrite is installed, enabled and working as well. 
The index.html returned by the server request resources from the root (https://my.host/main.css) and not the /netdata subfolder (https://my.host/netdata/main.css). Locally I can access http://localhost:19999, but not http://localhost:19999/netdata.

This is the relevant part of the config:
```
<Location "/netdata" >
    RewriteEngine On
    ProxyPreserveHost On

    AuthType Basic
    AuthName "Netdata"
    AuthUserFile /etc/netdata/.htpasswd
    AuthGroupFile /dev/null
    Require valid-user
    # Local netdata server accessed with '/netdata/', at localhost:19999
    ProxyPass http://localhost:19999/ connectiontimeout=5 timeout=30 keepalive=on
    ProxyPassReverse http://localhost:19999/

    # if the user did not give the trailing /, add it
    # for HTTP (if the virtualhost is HTTP, use this)
    #RewriteRule ^/netdata$ http://%{HTTP_HOST}/netdata/ [L,R=301]
    # for HTTPS (if the virtualhost is HTTPS, use this)
    RewriteRule ^/netdata$ https://%{HTTP_HOST}/netdata/ [L,R=301]
</Location>
```

**Comment by Whisprin** [comment]
Got it. The problem is that the `RewriteRule` inside `<Location>` doesn't work. 

When I access https://my.host/netdata/ (with trailing slash) it works.

**Comment by cakrit** [comment]
When I saw that trailing slash I thought it looked suspicious, but the Firefox on my Ubuntu VM didn't seem to have any problems showing the data, because I didn't put basic auth on it. 
Wanna do PR to correct the doc @Whisprin ?

**Comment by Whisprin** [comment]
@cakrit It's not just the extra slash in the Basic Auth docs. Apparently `RewriteRule` inside `<Location>` [should be avoided](https://stackoverflow.com/questions/6672455/mod-rewrite-in-location-in-apache-conf-causing-rewrite-in-htaccess-file-not). 
That's probably the reason for the extra slash and missing RewriteRule in the docs.

However, when I place the RewriteRule outside of Location it doesn't have an effect.
I'm yet to find the correct RewriteRule inside Location that doesn't lead to infinite redirects.

**Comment by Whisprin** [comment]
Got it. `RewriteRule ^/$ ...` works inside Location. 

Preparing a PR now. Thanks for the support @cakrit
