### ISSUE TITLE
A way to turn off the mosquitto installation

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#8168]
##### Feature idea summary
I've noticed that netdata is now installing a directory:
`/tmp/netdata-mosquitto-oIBING/mosquitto-v.1.6.8_Netdata-3/`
It would be nice to be able to turn this off in a config since I don't use mosquitto and chkrootkit complains about new directories showing up in /tmp that contain code.

**Comment by ilyam8** [comment]
Hi @Steve8291 

There is `--disable-cloud` installer flag

https://github.com/netdata/netdata/blob/a666833d4d3a3b49948a171fd9973a46123d37b7/netdata-installer.sh#L260-L263

**Comment by Steve8291** [comment]
Thanks. Is there any way to set that permanently since it will be overwritten every time netdata does a nightly install?

**Comment by Steve8291** [comment]
I think I have it figured out. Can I just set the installer flags in the `/etc/netdata/.environment` file?
If so, do I set the flags in:
`REINSTALL_OPTIONS="--autoupdate --disable-cloud"` 
or 
`NETDATA_CONFIGURE_OPTIONS="--disable-cloud"`

**Comment by ilyam8** [comment]
@Steve8291 

you need to install netdata with that flag, update will use it later on every update

you dont need to manually set stuff in `/etc/netdata/.environment`

**Comment by Steve8291** [comment]
Thanks @ilyam8 
That's exactly what I was looking for.
