### ISSUE TITLE
Grooming the Developer mode (log format)

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8176]
##### Feature idea summary
Netdata ebpf collector already has two modes (`entry` or `return`), but we have conditions to extend this for at least more one running mode, the `developer` mode. In this mode Netdata will not only gives information for our users about the number of function calls that failed, but it will also says the motive it failed and the road for the failure happens.

##### Expected behavior
To have the format that will allows to create a new log that will help developers to fix their bugs.

**Comment by amoss** [comment]
This will be handled as a technical groom with the team. We have decide that two calls will be necessary: one to propose and show us some demos of the various logging facilities and what they mean against real code, a second one to analyse the proposal and check for consensus.

**Comment by ilyam8** [comment]
>  but it will also says the motive it failed and the road for the failure happens.

Could you provide some examples? How does that additional info look like?

**Comment by thiagoftsm** [comment]
> > but it will also says the motive it failed and the road for the failure happens.
> 
> Could you provide some examples? How does that additional info look like?

Of course @ilyam8, I will schedule a meeting for next Tuesday and I will bring an example for the current log until Sunday.

**Comment by thiagoftsm** [comment]
When I started to work on developer mode, my original idea was to have a file with the format like `/var/log/messages`:

```
TIMESTAMP PROCESS (ERRNO) : MESSAGE
```

where:
-  TIMESTAMP : Could be the OS time like `messages` or some time related to process run time.
- PROCESS: Inside the kernel ring we have a task name with 16 bytes that is the same name written inside `/proc/PID/status`.
- ERRNO : The error raised 
- MESSAGE: This can be a description of the `errno` .

But, after the last sprint, we now have condition to detect memory leaks on the software like `valgrind` does, and this is an important feature to give for our users, so to use the previous format does not make sense, unless we accept to have different line formats inside the file.

**Comment by thiagoftsm** [comment]
I have intention to use different programs to demonstrate the errors and we improve the logs, for while I am starting with this shell script:

```
#!/bin/bash

echo "I am running with PID " $$

date
mkdir testing
mkdir testing

sleep 1
date

touch testing/write_here
touch testing/not_write_here

chmod 400 testing/not_write_here


echo "No error" > testing/write_here
echo "Error" > testing/not_write_here

sleep 1
date

rm testing
rm -rf testing
```

That displays the following output:

```
I am running with PID  17834
Wed Mar  4 00:49:39 UTC 2020
mkdir: cannot create directory ‘testing’: File exists
Wed Mar  4 00:49:40 UTC 2020
io.sh: line 19: testing/not_write_here: Permission denied
Wed Mar  4 00:49:41 UTC 2020
rm: cannot remove 'testing': Is a directory
```

And it generates the following logs:

```
2020-03-04 00:49:39 sh[17834]: No such file or directory
2020-03-04 00:49:40 sh[17834]: Permission denied
```

It is important to call attention for the fact that we are not monitoring all the functions inside the kernel, so we won't generate all errors.

**Comment by thiagoftsm** [comment]
Now from Netdata during a normal running:

```
2020-03-04 01:00:18 netdata[18058]: Bad file descriptor
2020-03-04 01:00:58 netdata[18058]: Bad file descriptor
2020-03-04 01:00:18 PLUGINSD[charts[18058]: Bad file descriptor
2020-03-04 01:00:19 PLUGIN[proc][18058]: No such file or directory
2020-03-04 01:00:19 PLUGIN[proc][18058]: No such file or directory
2020-03-04 01:00:19 PLUGINSD[node.d[18058]: Bad file descriptor
2020-03-04 01:00:29 PLUGIN[cgroups][18058]: Bad file descriptor
2020-03-04 01:00:29 PLUGIN[proc][18058]: Invalid argument
```

**Comment by thiagoftsm** [comment]
The most common error that I am detecting during all the tests:

```
2020-03-04 01:00:18 pulseaudio[1829]: Resource temporarily unavailable
2020-03-04 01:00:18 AudioIP~ent RPC[2121]: Resource temporarily unavailable
2020-03-04 01:00:18 AudioIPC Callba[1937]: Resource temporarily unavailable
2020-03-04 01:00:18 threaded-ml[1937]: Resource temporarily unavailable
2020-03-04 01:00:18 pulseaudio[1829]: Resource temporarily unavailable
```

**Comment by thiagoftsm** [comment]
I also started `apache` and I tried to access a file that does not exist on my webserver directory and I got the following errors:

```
2020-03-04 01:24:33 httpd[19829]: No such file or directory
2020-03-04 01:24:51 httpd[19853]: Resource temporarily unavailable
```

**Comment by amoss** [comment]
Alternative suggestion
```
{"date":"03/05/2020:23:30:27 UTC", "process":"example","PID":"8000","call":"malloc","size":"512"}
```

**Comment by thiagoftsm** [comment]
- We will support both formats, ltsv and json, and the ltsv will be the default format
- We will use date format as ISO 8601
- instead to have a `dev` option for the `load` option, we will have a new variable to enable or disable the developer mode.
- A flag variable to define what will be shown in the developer mode

- It is also necessary too verify the `uprobes` attached to memory. It is necessary to check the results when attached for PIDs and for the whole system, are we missing something when using them?

**Comment by thiagoftsm** [comment]
With the creation of #8344 and #8345 I am closing this issue.
