### ISSUE TITLE
Netdata web_log not showing accurate response time

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8182]
##### Bug report summary
We have an old netdata built under `/etc` with the local web interface and a prebuilt netdata installed under `/opt`. both have the same `web_log.conf` file. In the Prometheus server, one target is the local netdata and another one is our master server which netdata installed under `/opt` sends the metrics to. So we have two metrics from each hosts from two different jobs on the prometheus.
The problem is for the `netdata_web_log_response_time_milliseconds_average` metric we get two different number:
![aaa](https://user-images.githubusercontent.com/7656049/75151246-73fe4a80-571b-11ea-9e49-8eb0a9b907df.png)
The data gathered by the netdata  under `/etc` seems more reasonable because if I run the command `sudo tail -f /var/log/nginx/api.x.y-access.log | awk '{print $12}'` I get this output:
0.038
0.061
0.025
0.023
0.049
0.082
0.025
0.083
0.019
0.049
0.050
0.025
0.105
0.028
0.019
0.024
0.040
0.036
0.017
0.021
0.034
0.036
0.031
0.024
0.029
0.020
0.039

##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.5 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.5 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version
v1.19.0
 

##### Component Name
python.d

**Comment by ilyam8** [comment]
Hi @yasharne `avg` is sum/count. Probably jobs have read different number of lines 🤔 

consider to use go version btw

> https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#apachenginx-logs-monitoring-with-netdata

**Comment by yasharne** [comment]
@ilyam8 Thanks for your hint, the `/etc` version collects metrics every 2 seconds and the `/opt` version collect metrics every 5 seconds, making `/opt` collect metrics every two seconds made the same output for the given metrics.
