### ISSUE TITLE
Regression: netdata working in wrong directories after update

### ISSUE THREAD

**Issue by Pingger** [netdata/netdata#8186]
##### Bug report summary

After updating to netdata 1.20 suddenly all configs are loaded and stored in /opt/netdata. here the /etc /opt /usr /var directories are now created and used instead of the normal ones that already exist.  
So the folder structure looks like this:

![image](https://user-images.githubusercontent.com/4761298/75183723-63fa6100-5743-11ea-8a76-03151e050305.png)

The installer even updated some files in the correct "/etc/netdata" folder, like the "edit-config" script
##### OS / Environment

```
Linux ************* #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"

```

##### Component Name

area/packaging

##### Steps To Reproduce

1. run installer `bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)  --stable-channel --disable-telemetry`
2. have issues

##### Expected behavior

1. run installer,
2. configs are read from correct locations and not from some obscure undocumented locations!
2b. or be properly told, that there is a change in folder structure and what to be aware of when using configs of previous versions!

**Comment by ilyam8** [comment]
```cmd
test@DEB10-1:/opt/netdata$ ls -l --group-directories-first
total 32
drwxrwxr-x 3 netdata netdata 4096 Feb 20 20:56 bin
drwxrwxr-x 4 netdata netdata 4096 Feb 24 15:06 etc
drwxr-xr-x 3 netdata netdata 4096 Feb 20 20:55 include
drwxr-xr-x 3 netdata netdata 4096 Feb 20 20:55 lib
drwxrwxr-x 6 netdata netdata 4096 Feb 20 20:55 share
drwxrwxr-x 2 netdata netdata 4096 Feb 20 20:56 system
drwxrwxr-x 5 netdata netdata 4096 Feb 24 15:06 usr
drwxrwxr-x 6 netdata netdata 4096 Feb 20 20:56 var
lrwxrwxrwx 1 netdata netdata   11 Feb 24 15:06 netdata-configs -> etc/netdata
lrwxrwxrwx 1 netdata netdata   15 Feb 24 15:06 netdata-dbs -> var/lib/netdata
lrwxrwxrwx 1 netdata netdata   15 Feb 24 15:06 netdata-logs -> var/log/netdata
lrwxrwxrwx 1 netdata netdata   17 Feb 24 15:06 netdata-metrics -> var/cache/netdata
lrwxrwxrwx 1 netdata netdata   19 Feb 24 15:06 netdata-plugins -> usr/libexec/netdata
lrwxrwxrwx 1 netdata netdata   21 Feb 24 15:06 netdata-web-files -> usr/share/netdata/web
lrwxrwxrwx 1 netdata netdata    3 Feb 24 15:06 sbin -> bin

test@DEB10-1:/opt/netdata$ ls -l --group-directories-first etc/
total 8
drwx------ 11 netdata netdata 4096 Feb 24 15:06 netdata
drwxr-xr-x 11 netdata netdata 4096 Feb 20 20:56 netdata.new
```

**Comment by ilyam8** [comment]
@Ferroin 

if i install it twice it creates `netdata.new` and changes perms of `netdata`, see

```cmd
test@DEB10-1:/opt/netdata$ ls -l --group-directories-first etc/
total 8
drwx------ 11 netdata netdata 4096 Feb 24 15:06 netdata
drwxr-xr-x 11 netdata netdata 4096 Feb 20 20:56 netdata.new
```

**Comment by cakrit** [comment]
@Pingger this was definitely unintended. We're on it.

**Comment by ilyam8** [comment]
@Pingger 

> after updating to netdata 1.20 suddenly all configs are loaded and stored in /opt/netdata.

Where were they stored before?

**Comment by Ferroin** [comment]
Based on code inspection, it looks like this has been around since 1.19 and has two specific impacts:

* Installing to anywhere other than `/opt` with the static installer won't work.
* Updating a static install will move it to `/opt` if it started elsewhere.

It looks however like the update issue only impacts users updating from versions prior to 1.19 to 1.19 or 1.20.

Probable cause is: 4b9cc50ad

**Comment by Pingger** [comment]
> 
> 
> @Pingger
> 
> > after updating to netdata 1.20 suddenly all configs are loaded and stored in /opt/netdata.
> 
> Where were they stored before?
> 
> What version did you upgrade from?
from 1.19 
they where stored in /etc/netdata /usr/share/netdata and /var/cache/netdata
now they are in /opt/netdata/etc/netdata, /opt/netdata/usr/share/netdata and /opt/netdata/var/cache/netdata
I probably missed several folders, but all folders follow this sheme

**Comment by Ferroin** [comment]
@Pingger Did you possibly originally install with `kickstart.sh` and then try to reinstall/update using `kickstart-static64.sh`?

I'm asking since now that I'm looking properly at the code again instead of running around like a chicken with my head cut off trying to get this fixed, it looks like it never should have been possible to have the static installer put things anywhere other than under `/opt/netdata` (this is unfortunately a limitation of the fact that it's pre-built).

Regardless switching install methods without first uninstalling has never worked, though this really should be documented better and the installers should probably bail if they see someone trying to do it.

**Comment by Pingger** [comment]
I intitially installed with kickstart.sh, then I updated with kickstart.sh, and after that already broken, I discovered there is now an option for x64 which I then also tried, but that didn't change anything.

**Comment by Pingger** [comment]
Ok I now again run the installer using 
`bash <(curl -Ss https://my-netdata.io/kickstart.sh)  --stable-channel --disable-telemetry --enable-ebpf
` just to make sure. And suddenly it once again reads and writes to the correct directories ...

I don't know, what went wrong the first time, but now it works again.
should I close this issue?

**Comment by Ferroin** [comment]
Let's leave it open for now, at least until we're certain on our end that there's not a bug in the regular `kickstart.sh` installer script that caused this to happen in the first place.

**Comment by ilyam8** [comment]
> then I updated with kickstart.sh

this is kind of broken, if i use `kickstart.sh` twice i get

https://github.com/netdata/netdata/issues/8186#issuecomment-590525915

**Comment by Ferroin** [comment]
OK, then we probably need a separate issue for that. I suspect it's a leftover from when we still put the default configs in `/etc/netdata`.

**Comment by cosmix** [comment]
Ok guys, we'll update documentation to advise people not to run kickstart.sh twice, until we resolve these issues in issues #8294, #8198. And we'll update kickstart to not clobber existing installs if run multiple times.
