### ISSUE TITLE
install new Dashboard into Netdata

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata#8194]
##### Feature idea summary
Dashboard will be released in similar way as `go.d.plugin`. Netdata installer should fetch it from https://github.com/netdata/dashboard/releases, and unpack it to `usr/share/netdata/web` (ie. to the same place where normally /web folder goes during installation)

There is a problem that current dashboard outputs assets with hashes in their filenames. Currently server's Makefile explicitly states which files should be served, but we should support all files inside `static/*` folder (and that folder will be fetched from netdata/dashboard release)

To support feature flag introduced by https://github.com/netdata/netdata/issues/7940, `index.html` should be renamed to `index-new.html`, until we'll remove the old dashboard completely

**Comment by thiagoftsm** [comment]
I believe this issue has direct relationship with that issue with two `index.html`, please, can you confirm this?

**Comment by jacekkolasa** [comment]
yes, to prevent confusion i've renamed https://github.com/netdata/netdata/issues/7940 to explicitly state that is only about feature flag

**Comment by Ferroin** [comment]
@jacekkolasa Could we possibly get a gzipped tarball instead of a ZIP archive for this? We currently do not depend on unzip and not all Linux distros have it installed by default.

**Comment by jacekkolasa** [comment]
@Ferroin sure, we can do that. 

BTW. the current build was uploaded manually by me, but we'll need to make a pipeline (using Github Actions, if that is our choice), to compile the dashboard code on every Git Tag (`npm run build` command) and add a checksum to both release and Netdata (again, same process as go.d.plugin). Should i create a ticket for that?

**Comment by Ferroin** [comment]
> @Ferroin sure, we can do that.
> 
> BTW. the current build was uploaded manually by me, but we'll need to make a pipeline (using Github Actions, if that is our choice), to compile the dashboard code on every Git Tag (`npm run build` command) and add a checksum to both release and Netdata (again, same process as go.d.plugin). Should i create a ticket for that?

Ideally yes, but on the dashboard repo, not here. Assign me and @prologic in the issue, as one of the two of us will probably be the one to do it (and if not, we'll probably be helping whoever does).

**Comment by thiagoftsm** [comment]
@Ferroin I assigned us for we move this in front.

**Comment by prologic** [comment]
I'm almost certain this was done elsewhere.
