### ISSUE TITLE
Benchmark apps.plugin and ebpf.plugin round 2

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#8195]
##### Feature idea summary

This is the continuation of  #7987

We need to have a better idea about what is necessary to move from apps.plugin to ebpf.plugin

The plan is to figure out some more representative mixes of Computation versus I/O, by looking into stress-ng, Transaction Processing Performance Council, fio or vdbench. The aim is also to stress the kprobes that ebpf has implemented.

After having created a couple of scenarios based on the above research, benchmark a system at about 25%, 50%, 75% and 100% load. The system is going to have a 4C/4T CPU so for the 25% load the load is going to be of 2 kinds:
  - 25% of multithreaded load
  - 25% of single threaded fully busy load (no duty cycle)

No need for the netdata agent to be running. The benchmark is going to affect apps.plugin and ebpf.plugin on their own, to reduce noise.

**Comment by mfundul** [comment]
## Evaluation

We evaluate the performance impact of `apps.plugin` and `ebpf.plugin` on a Fedora 31 installation,
linux kernel version 5.5.5-200.fc31.x86_64. The machine runs on a quad core(8 threads) `Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz` CPU, with 32GB of RAM.

We effectively disable intel speedstep and turbo, so that we can set a steady clock of 3.6GHz to produce more stable results with the following commands:
```
echo 100 > /sys/devices/system/cpu/intel_pstate/min_perf_pct
echo 100 > /sys/devices/system/cpu/intel_pstate/max_perf_pct 
echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo 
```
In both idle and fully loaded cases the CPU clock always was:
```
cpu MHz		: 3599.239
```

We remove all disk I/O bottlenecks from the equation by using a ramdisk drive for all filesystem and disk
operations. To create the ramdisk we ran:
```
modprobe brd rd_size=29360128
```
To remove any page allocation overheads from our results we pre-allocate the ramdisk drive:
```
dd if=/dev/zero of=/dev/ram0 bs=1M oflag=direct
```

The benchmarks ran without the netdata agent itself running. The 3 configurations used are baseline, ebpf, and apps:
- baseline means that not much else other than the benchmark is running in the system
- ebpf means that the netdata plugin `ebpf.plugin` is running with a 1 second interval.
- apps means that the netdata plugin `apps.plugin` is running with a 1 second interval.

The `ebpf.plugin` process was configured with the default settings and uses the following `p:kprobes`:
```
vfs_write
vfs_writev
vfs_read
vfs_readv
do_sys_open
vfs_unlink
do_exit
release_task
_do_fork
__x64_sys_clone
__close_fd
```
This means that for the system to be affected by the `ebpf.plugin` process an application needs to be doing a lot of:
- read/write syscalls
- opening/deleting unix files
- spawning a lot of linux threads

Due to a current bug, the kprobe state is cleaned up up between runs with the command:
```
echo "" >  /sys/kernel/debug/tracing/kprobe_events
```

### fio

We use `fio` as our read/write syscall synthetic stress tester since it is the most potent 
microbenchmark at generating immense loads of I/O operations. Our configuration file is:
```
[global]
name=fio-rand
filename=/dev/ram0
rw=randrw
bs=4K
direct=1
time_based=1
runtime=60
iodepth=1
ioengine=psync
numjobs=1
group_reporting
disable_lat=1
disable_slat=1
disable_clat=1
disable_bw_measurement=1

[file1]
size=256M
```
Where `numjobs` goes from 1 to 8, spawning the corresponding number of processes doing synchronous I/O on the ramdisk drive.

This chart shows performance as combined read and write I/O thousand-operations per second:

![fio-IOPS](https://user-images.githubusercontent.com/44345837/75633025-4d07b300-5c0a-11ea-919d-cdf68f5125cb.png)

This chart shows the correponding CPU utilization of the previous runs:
![fio-CPU](https://user-images.githubusercontent.com/44345837/75633027-4e38e000-5c0a-11ea-9ecb-4d4d04897fa1.png)

This chart shows the slowdown percentage relative to the baseline run:
![fio-slowdown](https://user-images.githubusercontent.com/44345837/75633026-4da04980-5c0a-11ea-8e3c-74efc744d146.png)

It is clear that synchronous I/O is affected by ebpf regardless of how loaded the server is, as long as a single thread can be saturated. At full load, the overhead for `ebpf.plugin` becomes a little more pronounced. However, these scenarios are much closer to worst case than any typical case.

### stress-ng

Benchmarking the linux thread tracing impact proved to be an exercise in futility. We used stress-ng to test this by both focusing on pthread-only scenarios and various mixes of CPU and cache stress scenarios combined with the pthread stresser.
The results were never easily reproducible and there is no measurable impact of the netdata plugins. It appears that the huge overheads of linux thread spawning are not affected by our very light code injection in the thread tracing probes.
For 100% CPU load stressing thread spawning with stress-ng produces at most 90K kprobe calls per second whereas I/O stressing with fio produces about 3M kprobe calls per second.

### pgbench

For our real world benchmarking we use postgresql and pgbench. First we mount all postgresql database instances on our ramdisk drive:
```
mount /dev/ram0 /var/lib/pgsql/
```
Then we reinitialize the database to a clean state.

We initialize the benchmark tables by running:
```
pgbench -i --unlogged-tables --quiet --scale=1000
```
which generates about 15GiB of data. We make sure to keep our system available RAM very low, so that the I/O hits the ramdisk as often as possible to have reproducible results and remove variability:
```
              total        used        free      shared  buff/cache   available
Mem:          31976       30949         611         208         415         456
Swap:             0           0           0
```
Before every run we drop all file-system caches for the same reason:
```
echo 3 > /proc/sys/vm/drop_caches
```

Finally, every pgbench run vacuums the state before running:
```
pgbench --vacuum-all --protocol=prepared --skip-some-updates -j 64 -c 64 -T 600
```
Where `-c` represents clients. It goes from 1 to 64, spawning the corresponding number of threads performing queries and transactions.

This chart shows the transactions per second for 1 to 64 clients:
![PGbench-tps](https://user-images.githubusercontent.com/44345837/75633029-5abd3880-5c0a-11ea-84e4-0be4a3e63d86.png)

This chart shows the corresponding CPU utilization of the previous runs:
![PGbench-CPU](https://user-images.githubusercontent.com/44345837/75633030-5b55cf00-5c0a-11ea-8cd1-4d6be16029c8.png)

This chart shows the average latency of the previous runs:
![PGbench-latency](https://user-images.githubusercontent.com/44345837/75633032-5b55cf00-5c0a-11ea-9d40-566d9854c5f2.png)

Those real-world runs show that our use of ebpf is neither heavy, nor deep enough yet to seriously affect heavy applications at any load.

**Comment by thiagoftsm** [comment]
> Those real-world runs show that our use of ebpf is neither heavy, nor deep enough yet to seriously affect heavy applications at any load.

I loved this sentence, but I am not considering only it. I think your results showed what we were expecting.
Thank you @mfundul ! I will bring the fix for when then SIGINT is not effective as I was expecting until the end of the current sprint.
