### ISSUE TITLE
I need your help to build my dashboard like this.

### ISSUE THREAD

**Issue by hilmi-afifi** [netdata/netdata#8204]
![image](https://user-images.githubusercontent.com/38133643/75314411-412a9280-5892-11ea-801f-7eed929bfbe5.png)

**Comment by hilmi-afifi** [comment]
i'm try to copy paste your site script , but can't load anything hahaha, helpme please to custom my dashboard like that.. :)thanks, regards hilmi

**Comment by cosmix** [comment]
Thanks for contacting us @hilmi-afifi — you can find more information on creating custom dashboards at https://docs.netdata.cloud/web/gui/custom/
