### ISSUE TITLE
Update static builds to use Alpine 3.12 and eliminate manually built dependencies in favor of Alpine packages.

### ISSUE THREAD

**Issue by brawer** [netdata/netdata#8205]
In [install-alpine-packages.sh](https://github.com/netdata/netdata/blob/17c0f9a70e122f17a3a6ad963603a10ab768a34b/packaging/makeself/install-alpine-packages.sh#L42), netdata is compiling the Snappy library locally because “snappy doesnt have static version in alpine”. FYI, Alpine has just added [package snappy-static](https://pkgs.alpinelinux.org/packages?name=snappy-static&branch=edge). So, in case you want, you could do the following instead of doing a local install:

```
apk add snappy-static --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main
```

**Comment by prologic** [comment]
@brawer Thanks for the report and sorry for the delay! We've added this to our backlog. In the meantime if you are willing to put up a PR we will happily review and accept your contribution! Thanks!

**Comment by Ferroin** [comment]
For reference regarding this, there is a `snappy-static` package in Alpine 3.12, which we plan to switch to using when we update our static builds to use Alpine 3.12.

**Comment by Ferroin** [comment]
Finished in https://github.com/netdata/netdata/pull/10241
