### ISSUE TITLE
Implement a Google Cloud Pub/Sub C/C++ publisher

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#8206]
#### Feature idea summary
We will implement a C/C++ publisher using a [Pub/Sub service definition](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto), `protoc`, and gRPC C++ library.

- [x] Add gRPC C++ library as a dependency
- [x] Generate a Pub/Sub C++ client library using `protoc`
- [ ] Solve a problem with integrating both libraries
- [x] Wrap C++ code into C functions
- [x] Implement the publisher
- [x] Test the publisher on a live Pub/Sub service

##### Expected behavior
- A simple Pub/Sub publisher is implemented
- We can use the client API to implement a Pub/Sub exporting connector.

**Comment by andrewm4894** [comment]
I am happy to sponsor or help push for this one if needed. It is a key part of a GCP BigQuery based backend that should be useful for the wider community too.

**Comment by vlvkobal** [comment]
A simple Pub/Sub publisher is implemented.
