### ISSUE TITLE
Split the RRDHOST->rrdhost_rwlock into rrdhost_rwlock and health_rrwlock

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#8207]
##### Feature idea summary

Split the `RRDHOST->rrdhost_rwlock` into `rrdhost_rwlock` and `health_rrwlock` as described in the agent locking scheme [proposal](
https://github.com/netdata/docs/blob/master/architecture/agent/locking/Proposal2.md) so that health code is decoupled from main host lock.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
