### ISSUE TITLE
Integrate the new reference counting in host and chart destructors/constructors

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#8209]
##### Feature idea summary

Integrate the reference counting in the object (hosts, charts) destructors and constructors as described in the agent locking scheme [proposal](
https://github.com/netdata/docs/blob/master/architecture/agent/locking/Proposal2.md). Also introduce the new finer-grain locks in the proposal.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
