### ISSUE TITLE
Add reference counting get()/put() calls wherever is needed

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#8210]
##### Feature idea summary

Add reference counting `get()`/`put()`calls in the netdata code wherever is needed, as described in the agent locking scheme [proposal](
https://github.com/netdata/docs/blob/master/architecture/agent/locking/Proposal2.md).

This code change does not provide functionality on its own. The target is to integrate this code to the agent in a multi-step process towards the new agent locking scheme. Testing that nothing breaks in the netdata agent should suffice.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.

**Comment by ilyam8** [comment]
@mfundul ❤️
