### ISSUE TITLE
Installation error system bit centos7

### ISSUE THREAD

**Issue by dylanyht** [netdata/netdata#8215]
--- Downloading static netdata binary: https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run ---
[/tmp/netdata-kickstart-DPDYze]# curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/sha256sums.txt
 OK

[/tmp/netdata-kickstart-DPDYze]# curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run
 OK

 ABORTED  Static binary checksum validation failed. Stopping netdata installation and leaving binary in /tmp/netdata-kickstart-DPDYze

**Comment by prologic** [comment]
@frei-style Do you mind performing the following and pasting the output here in a comment?

```sh
$ cd /tmp/netdata-kickstart-DPDYze
$ sha256sum netdata-latest.gz.run
$ cat sha256sum.txt
```

Thanks!

**Comment by dylanyht** [comment]
The content of sha256sum.txt is empty

**Comment by EnzoAkira** [comment]
Hello guys!
I'm having the similar issue.
I use ansible to deploy netdata but today the playbook stuck and on host the script kickstart stopped at
`[/tmp/netdata-kickstart-ATlC2K]# curl -sSL --connect-timeout 10 --retry 3 https://github.com/netdata/netdata/releases/download/v1.20.0/netdata-v1.20.0.gz.run` 

I use the script: `kickstart-static64.sh --dont-wait --stable-channel --no-updates`

**Comment by prologic** [comment]
@EnzoAkira Are you also seeing the downloaded `sha256sum.txt` file empty too?
