### ISSUE TITLE
How do you deploy netdata agents?

### ISSUE THREAD

**Issue by simplesupreme** [netdata/netdata#8217]
How do you deploy netdata agents? Might be a simple enough question with a simple answer but I cannot make out from the documentation if there's any other option than using netcloud.

I've installed netdata on an Ubuntu 18.04 machine and designated it the master, now I want to install the agent and monitor several other Ubuntu 18.04 machines from a central platform without having to use netcloud. How do I do that?

Thanks

**Comment by thiagoftsm** [comment]
Hi @simplesupreme ,

Netdata has a documentation to configure slaves in this link https://docs.netdata.cloud/streaming/#streaming-configuration , but this configuration won't remove access to the cloud feature, it will give you condition to access your hosts using both methods.

Best regards!
