### ISSUE TITLE
Add ability to reload netdata configuration without restarting the whole service

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8222]
##### Feature idea summary
Every time I want to make a change in netdata configuration files such as `netdata.conf`, `stream.conf` and `python.d.conf` files, I have to restart the netdata service, This can cause problem in cases like we have a huge master server with lots of slaves streaming metrics, So in my case, it takes about 2 minutes to restart the master server to read the new configuration and it takes about 5 minutes to see all the metrics of all the slaves and in the meanwhile people from CallCenter, DevOps and SRE keep messaging if there is something catastrophic happened to the business.
This is the best scenario which I get what I want from the configuration and I don't need to add anything else to the configuration file.
##### Expected behavior
something like `systemctl reload netdata` or the same mechanism used for alerting system `killall -USR2 netdata` to reload the configuration without restarting the services.

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

Netdata has a plan to create a configuration management that among the expected new behaviors, it will have a way to reload all the configuration without to restart the service. You can see more details in the issue #6432 .

**Comment by ilyam8** [comment]
This can be added for python/go plugins, it is much easier then CM (which is huge)

**Comment by thiagoftsm** [comment]
But, for internal plugins we would need the CM, or we need to bring a possibility to reload all plugins present in Netdata.

**Comment by amoss** [comment]
Hi @yasharne and thank you for the feedback. We like the idea - it is something that we want to do already. There are some challenges in how it is implemented as we need to work through the whole code-base to remove some assumptions about the configuration being constant, implement the new loading routines and also check the locking behaviour of several structures. I'm closing this issue as we already have an issue to discuss this but please feel free to add comments to #6432 in the discussion on configuration management.
