### ISSUE TITLE
health:  simple pattern doesnt work well for `of` and `foreach`

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8239]
##### Bug report summary

Alarm line `lookup` [documentation](https://docs.netdata.cloud/health/reference/#alarm-line-lookup)

> of DIMENSIONS is optional and has to be the last parameter. Dimensions have to be separated by , or |. The space characters found in dimensions will be kept as-is (a few dimensions have spaces in their names). This accepts Netdata simple patterns and the match-ids and match-names options affect the searches for dimensions.

Simple patterns [documentation](https://docs.netdata.cloud/libnetdata/simple_pattern/#netdata-simple-patterns)

> Simple patterns are a space separated list of words

___

Following two things are mutually exclusive:

- The space characters found in dimensions will be kept as-is (a few dimensions have spaces in their names).

- This accepts Netdata simple patterns

It is a common situation when **i want to lookup for not all dimensions but some of them** and i dont want to give a full list (why do we have simple pattern then?) or i dont know dim names, because they are dynamic.

For exampling i want to find sum of all dims except from `this` and `that`

```cmd
  lookup: sum -1m unaligned absolute match-names of !this !that *
```

^^ it is a simple pattern, but it doesnt work because of `The space characters found in dimensions will be kept as-is`.

##### OS / Environment

```
any
```

##### Netdata version

 
`netdata v1.20.0-57-g1ea0d8d0`

##### Component Name

`health`

##### Steps To Reproduce

1. use simple pattern with spaces in `of`
2. see it doesnt work

##### Expected behavior

Simple pattern works according its documentation for `of` and `foreach`.

**Comment by thiagoftsm** [comment]
We are missing simple pattern creation when we are reading the health files and as consequence we cannot use them to create the alarms.
I already moved this bug to  `Ready for dev` for we plan the fix for it.

**Comment by underhood** [comment]
Hi,

the string behind `of` eventually goes to `rrdr_disable_not_selected_dimensions` which creates simple pattern out of it however with different separators:
```C
simple_pattern_create(dims, ",|\t\r\n\f\v", SIMPLE_PATTERN_EXACT);
```

I have created fake collector that creates chart with following dimensions:
```Ruby
$dim_names = [ 'test_1', 'test_2', 'test_3', 'test_4', 'test_5', 'something_else', 'whateva' ]
```
and alarm for it with following lookup:
```
  lookup: average -11s unaligned of !test_2,test*,softirq,irq,guest
```

and this works as expected matching test* except `test_2`.

**Comment by ilyam8** [comment]
Yes, lgtm. Health doc update will do.

**Comment by thiagoftsm** [comment]
I agree with both, the documentation is enough for we fix this problem.
Thank you @underhood .
