### ISSUE TITLE
web: do not uncollapse first alarm in alarms->all section

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8240]
##### Bug report summary

It seems like a minor problem but in fact is very annoying. If i open `Alarms->All` section the first alarm there is uncollapsed.

I never really need to have it uncollapsed and every time i want to check some other alarm i have to collapse it.

See:

<img width="1025" alt="Screenshot 2020-02-28 at 12 52 51" src="https://user-images.githubusercontent.com/22274335/75538167-3eae7100-5a29-11ea-844d-d9841a2a1241.png">

##### OS / Environment

```
macOS, Chrome
```

##### Netdata version

 
`netdata v1.20.0-57-g1ea0d8d0`

##### Component Name

`web`

##### Steps To Reproduce

1. open dashboard `Alarms->All` section

##### Expected behavior

Have collapsed list of alarms by default.

**Comment by jacekkolasa** [comment]
done in https://github.com/netdata/netdata/pull/10122
