### ISSUE TITLE
Persist alarm log to db

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#8243]
##### Feature idea summary

I would like alarm log data to flow into the db so that i have it persisted somewhere that will flow automatically into my backend along with the metrics themselves.

My specific use case here is that i am streaming multiple nodes to a master and i can't pull the alarm log data from the `/api/v1/alarm_log` endpoint of each sending node.

So ideally i'd like for the alarm log to just stream in along with the metrics data. 

##### Expected behavior

Ideally the alarm log data could be handled just like another chart or source in the backend db. 

Alternatively perhaps the alarm log data could be exposed to stats d and make its way to the backend via that route.

**Comment by thiagoftsm** [comment]
Hi @andrewm4894 ,

We have a file where we store the last 1000 alarm log by default, it is the file /var/lib/netdata/health/health-log.db, does this file have all the necessary fields that you need?

Best regards!
