### ISSUE TITLE
Cache over 4gb

### ISSUE THREAD

**Issue by anatoleplanteur** [netdata/netdata#8246]
Hi,
I run netdata since a whileon centos7, everything was ok until couple of day. Suddently the folder /opt/netdata/var/cache/netdata/dbengine growing and growing.
I actually have a 4gb folder on my little root folder. I find a thread about that on github telling us to 
Change
# memory mode = dbengine
to
# memory mode = ram

After restarting i still get the 4gb file.

What the way to delete that logs file ? do you think issue is fixed ?

Thanks

**Comment by mfundul** [comment]
The default database is `dbengine` and is stored at `var/cache/netdata/dbengine` for the localhost, more information [here](https://docs.netdata.cloud/database/engine/). The default quota per database instance is 256MiB and unless you've changed that or you have many netdata agents streaming to this particular host then this would be a bug.

What version of netdata are you running? If you're not running the latest release please upgrade.

About using `memory mode = ram`, this doesn't delete any `dbengine` files by default. However, as long as the netdata agent is stopped or if it's running with `memory mode = ram` feel free to delete the folder `/opt/netdata/var/cache/netdata/dbengine` by hand.
