### ISSUE TITLE
ip.tcp_syn_queue cookie alerts

### ISSUE THREAD

**Issue by AaronRobinson** [netdata/netdata#8249]
ip.tcp_syn_queue (tcp), 1m tcp syn queue cookies = 2 cookies

I’ve been getting this netdata alert regularly for the past few days on one server. 

I think I understand the error. I’m receiving a lot of TCP requests (SYN), sending SYN-ACK but getting no ACK. The SYN queue is filling and cookies are being created for the overspill. 

I’ve captured traffic using tcpdump spanning one of these instances and I can see a bunch of requests with SYN, SYN-ACK and no ACK. It looks like a SYN flood attack. However the volumes don’t look huge. Nowhere near the queue size of 2048. 

Despite this I’ve increased the size of the net.core.somaxconn up to 16k but still get regular alerts.

Any ideas or help appreciated. 

I’m on Ubuntu 16.04 LTS and have netdata auto updated to the latest version.

**Comment by ilyam8** [comment]
Rel: #3234, #6998

There is the PR that makes syn cookie alarm less aggressive: #7250

> I’ve captured traffic using tcpdump spanning one of these instances and I can see a bunch of requests with SYN, SYN-ACK and no ACK.

It sounds like a problem, the alarm you are getting is `warning`.

**Comment by AaronRobinson** [comment]
Thanks. Yes, it's a warning but I'd like to understand what's causing the alert and capture the investigation work here to help others in the future. Although the warning may be too aggressive, I don't think I shouldn't be getting any cookie overflows given I have the queues set much higher than the number of SYN attacks.

From the TCP dump taken, I can see many attempts to access the server but it looks like hundreds, certainly nowhere near the queue size specified in both net.core.somaxconn and net.ipv4.tcp_max_syn_backlog

```
$ sysctl net.ipv4.tcp_max_syn_backlog
net.ipv4.tcp_max_syn_backlog = 16384
$ sysctl net.core.somaxconn
net.core.somaxconn = 16384
$ 
```

**Comment by ilyam8** [comment]
>  I don't think I shouldn't be getting any cookie overflows given I have the queues set much higher than the number of SYN attacks.

Yes, warning is mainly needed to capture

> a bunch of requests with SYN, SYN-ACK and no ACK.

**Comment by ilyam8** [comment]
I think the only way to understand why a counter is incremented is to check the kernel source code (or find a good article 😄).

Check this article:
> https://blog.cloudflare.com/syn-packet-handling-in-the-wild/
