### ISSUE TITLE
Fix known issues with claiming

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8263]
#### Summary

As we work through testing we are collecting issues with claiming together so that we can track them before the release.

#### Known issues

* Timeout handling. Before I set the proxy I run the claiming command (the command line stalled for many seconds, probably reached the 3*5min timeout limit) but the script reported “Node was successfully claimed.” which was not the case.
* `hostname` is not available on some systems but `$HOSTNAME` is set.
* Needs a debug flag to see the contents of `tmpin` and `tmpout`.
* The integer expression problem if the return code is blank

**Comment by mfundul** [comment]
https://github.com/netdata/netdata/blob/fd343ac0c262cd6a1535b67e7894d06760e10259/claim/netdata-claim.sh.in#L219

This line of code should make sure that `HTTP_STATUS_CODE` has valid contents before testing against `204`.
