### ISSUE TITLE
CMake build is broken

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#8271]
##### Bug report summary
When Netdata is built using CMake the process terminates with the following error
```
[ 74%] Building C object CMakeFiles/netdata.dir/aclk/mqtt.c.o
In file included from /home/vlad/netdata/aclk/mqtt.c:6:
/home/vlad/netdata/aclk/aclk_lws_wss_client.h:4:10: fatal error: libwebsockets.h: No such file or directory
    4 | #include <libwebsockets.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/netdata.dir/build.make:1189: CMakeFiles/netdata.dir/aclk/mqtt.c.o] Error 1
make[2]: Leaving directory '/home/vlad/netdata/cmake-build-debug'
make[1]: *** [CMakeFiles/Makefile2:942: CMakeFiles/netdata.dir/all] Error 2
make[1]: Leaving directory '/home/vlad/netdata/cmake-build-debug'
make: *** [Makefile:95: all] Error 2

```

##### OS / Environment
Arch Linux

##### Netdata version
commit e72044548fb241f41104f834edaa73192c1fef34

##### Component Name
packaging, ACLK

##### Steps To Reproduce
Build Netdata using CMake

##### Expected behavior
CMake should build Netdata

**Comment by amoss** [comment]
@vlvkobal The problem specific to the ACLK flag is fixed in the latest version but the CMake build does not work correct on master. The target prefix is hardcoded to `/` and there does not seem to be a way to set it?
