### ISSUE TITLE
Add an option to expose host variables via Prometheus remote write

### ISSUE THREAD

**Issue by agrimal** [netdata/netdata#8272]
Hello,

In this [PR](https://github.com/netdata/netdata/pull/4200) you added the option to send host metrics by adding `variables=yes` to the netdata URL.

Can you please also add this option to the Prometheus remote write protocol ?  
I need netdata_netfilter_conntrack_max to monitor the conntrack table, because its value is not the same on every host and can be adjusted at runtime.

Or maybe just add this metric to the default metrics.  
In the same way, you export max memory, why not max conntrack ?

**Comment by ilyam8** [comment]
Closing in favor of #8272
