### ISSUE TITLE
godplugin doesnt handle job names with spaces

### ISSUE THREAD

**Issue by mjtice** [netdata/netdata#8273]
##### Bug report summary
The x509check (go.d) chart shows `no data` 

##### OS / Environment
`CentOS Linux release 7.2.1511`

Netdata was installed via RPM
```
# rpm -qa | grep -i netdata
netdata-conf-1.18.1-1.el7.noarch
netdata-1.18.1-1.el7.x86_64
netdata-data-1.18.1-1.el7.noarch
```
Because it doesn't appear that the go.d plugin is packaged with the RPMs, I installed the plugin manually via:
```
wget https://github.com/netdata/go.d.plugin/releases/download/v0.15.0/go.d.plugin-v0.15.0.linux-amd64.tar.gz
tar xzvf go.d.plugin-v0.15.0.linux-amd64.tar.gz -C /usr/libexec/netdata/plugins.d/go.d.plugin
chown root /usr/libexec/netdata/plugins.d/go.d.plugin

wget https://github.com/netdata/go.d.plugin/releases/download/v0.15.0/config.tar.gz
tar xzvf config.tar.gz -C /etc/netdata/conf.d
chown -R root /etc/netdata/conf.d/go.d*
```

##### Netdata version
```
# netdata -V
netdata v1.18.1
```
 

##### Component Name
`go.d.plugin`

##### Steps To Reproduce
I'm trying to evaluate the expiration time of my Kafka certificates.  Because I've enabled `ssl.client.auth=required` I'm choosing to extract the certificate from the keystore and running the plugin against the file.

```
openssl pkcs12 -in kafka-keystore.p12  -nokeys -out cert.pem
openssl x509 -inform PEM -outform PEM -in cert.pem -out /etc/kafka/certificate.crt
chown netdata /etc/kafka/certificate.crt
```

Reading the certificate, the `Validity` time is printed:
```
openssl x509 -noout -text -in /etc/kafka/certificate.crt

[...]
Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=[redacted], ST=[redacted], L=[redacted], O=[redacted], O=[redacted], OU=[redacted], CN=prod.ostk.com Pipeline Intermediate Authority
        Validity
            Not Before: Sep  5 00:15:46 2019 GMT
            Not After : Sep  4 00:16:15 2020 GMT
[...]
```

The x509check.conf has this yaml:
```
jobs:
  - name: Kafka TLS Expiry
    source: file:///etc/kafka/certificate.crt
    days_until_expiration_warning: 1400
    days_until_expiration_critical: 700
    timeout: 2
```

Debug output prints the expiration - but the `time` is `0`.

```
# ./go.d.plugin -d -m x509check
[ DEBUG ] main[main] orchestrator.go:141 tick 1156
BEGIN x509check_Kafka TLS Expiry.time_until_expiration 1000009
SET expiry = 15934370
VARIABLE CHART days_until_expiration_warning = 1400
VARIABLE CHART days_until_expiration_critical = 700
END

BEGIN netdata.execution_time_of_x509check_Kafka TLS Expiry 1000009
SET time = 0
END
```

##### Expected behavior
I believe the chart should show data.

**Comment by ilyam8** [comment]
@mjtice 👋 

It is job execution time - how much time it takes to collect data. You can see this chart under `Netdata Monitoring->go.d` section.


Collected data is

```cmd
BEGIN x509check_Kafka TLS Expiry.time_until_expiration 1000009
SET expiry = 15934370
VARIABLE CHART days_until_expiration_warning = 1400
VARIABLE CHART days_until_expiration_critical = 700
END
```

**Comment by ilyam8** [comment]
> The x509check (go.d) chart shows no data

Default update every for the module is 60 seconds

https://github.com/netdata/go.d.plugin/blob/5146e9b1c498fd876c1dfc19f866c57d3e3dceb6/modules/x509check/x509check.go#L20

Data on chart appear after 2nd collect iteration.

So you need to wait or change `update_every` in the module configuration file.

**Comment by ilyam8** [comment]
> tar xzvf go.d.plugin-v0.15.0.linux-amd64.tar.gz

latest is `v0.16.0` btw

**Comment by ilyam8** [comment]
> tar xzvf go.d.plugin-v0.15.0.linux-amd64.tar.gz

latest is `v0.16.0` btw

**Comment by ilyam8** [comment]
> BEGIN x509check_Kafka TLS Expiry.time_until_expiration 1000009


hm, there is a bug, please remove spaces from the job name

```yaml
jobs:
  - name: Kafka_TLS_Expiry
```

**Comment by mjtice** [comment]
Ah, good to know, thanks @ilyam8.  I removed the spaces from the name and restarted the process.  Data is now showing up in the chart!
