### ISSUE TITLE
How to check if X509 certificate is revoked or not

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8277]
##### Feature idea summary
Is there any way to check if a certificate is revoked or not? I saw a configuration in the `X509check.conf` which is `tls_skip_verify` but I haven't seen it being used in the code and there is no chart for it in the netdata. 
I tried to monitor a webpage with revoked certificate (https://revoked.grc.com/) with this configuration:
```
 - name: revoked
   source: https://revoked.grc.com:443
   days_until_expiration_critical: 7
   tls_skip_verify: no
```
But It tells me the expiry and doesn't mention the revokation:
![image](https://user-images.githubusercontent.com/7656049/75857051-cd950200-5e0a-11ea-9dbb-e7c46feaad7c.png)

##### Expected behavior
A chart on the netdata claiming whether a Certificate is valid or not

**Comment by ilyam8** [comment]
Hi @yasharne. Currently there is no such functionality.

**Comment by ilyam8** [comment]
> tls_skip_verify

is used to create `tls.Config`

https://github.com/netdata/go.d.plugin/blob/master/pkg/web/tls.go

> 	// InsecureSkipVerify controls whether a client verifies the
	// server's certificate chain and host name.
	// If InsecureSkipVerify is true, TLS accepts any certificate
	// presented by the server and any host name in that certificate.
	// In this mode, TLS is susceptible to man-in-the-middle attacks.
	// This should be used only for testing.

**Comment by ilyam8** [comment]
It is not `x509check` specific option, every module that does http requests has it.
