### ISSUE TITLE
How can I contribute to go modules?

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8278]
##### Question summary
I've tried to contribute a go plugin but didn't find an instruction on how to achieve this. There is a link [here](https://github.com/netdata/go.d.plugin/) but it is broken and the contribution link is not working

##### Component Name
go.d

**Comment by ilyam8** [comment]
Hi @yasharne 

You need to open a PR in the https://github.com/netdata/go.d.plugin

What kind of contribution are you talking about? New module? Improve of existing module?

**Comment by yasharne** [comment]
Hi @ilyam8 
I want to improve an existing module but I have no idea on where to put the modified go file to test the functionality

**Comment by ilyam8** [comment]
Well, every module has its own dir with its source code (testdata, tests, etc). 

You clone repo, create a branch, add changes, commit them and make the PR.

If you give me more details what are you going to do probably i could give a more detailed instruction.

**Comment by yasharne** [comment]
@ilyam8 Thanks for your clarification, But where can I test my changes? For example, When I'm developing a python module for netdata, I put the python file in the format of `my-plugin.chart.py` in `usr/libexec/netdata/python.d/` and the configuration file in `/etc/netdata/python.d/my-plugin.conf`.
My question is after I made the changes inside the go module, where should I place it in my local netdata to test the output?

**Comment by ilyam8** [comment]
Oh, you mean real test, i was thinking about tests like

> https://github.com/netdata/go.d.plugin/blob/master/modules/weblog/weblog_test.go


You need to compile the plugin and replace existing one or just run it in the debug mode.

See

https://github.com/netdata/go.d.plugin/pull/352#issuecomment-592986100

**Comment by ilyam8** [comment]
I usually compile it with the default params i need to run it in debug mode

> bin/godplugin -d -m MODULENAME

**Comment by cakrit** [comment]
Let's get this in the documentation.
