### ISSUE TITLE
RPM versioning is broken.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8283]
In short, as of #7794, RPM package builds don't work outside of our own CI workflows.

This comes down to the fact that we end up with a version in the RPM spec file after templating that does not match up with the tag in `git`.

Fixing this requires:

1. Removing the code stripping the `v` from the version number in the tag in our CI workflow for building RPM packages.
2. Reverting #7794.

**Comment by prologic** [comment]
Fixed by #8305
