### ISSUE TITLE
Add more robust checking of `make dist`.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8284]
As of right now, our validation of `make dist` only reliably catches issues resulting from mandatory components in the install failing.

However, we now have a number of important optional components that we need to verify work correctly.

As a result, we need to update our checking to more robustly verify that installing from a tree prepared with `make dist` pulls everything in correctly.

**Comment by prologic** [comment]
@Ferroin The "Checks / Dist" workflow is now migrated to GHA. Can you elaborate on what's needed here?

**Comment by Ferroin** [comment]
It needs #8382 merged and that flag needs to be used for the `make dist` builds. However, #8382 is effectively blocked pending completion of #8378, which will resolve the build failures being seen in it.

**Comment by prologic** [comment]
All yours then :)
