### ISSUE TITLE
Netdata shouldn't fail if /run/netdata or /var/run/netdata don't exist.

### ISSUE THREAD

**Issue by cosmix** [netdata/netdata#8293]
These directories are not reliable going to be there, because `/run` and `/var/run` get wiped on most systems on reboot. Netdata should be creating this directory on startup, but isn't reliably for some reason.

**Comment by prologic** [comment]
> These directories are not reliable going to be there, because /run and /var/run get wiped on most systems on reboot. Netdata should be creating this directory on startup, but isn't reliably for some reason.

On which system? Source-based install or native package?

**Comment by Ferroin** [comment]
We shouldn't be relying on this anyway whenever possible. If, for example, we're started as root, we should create these directories (and possibly `/var/lib/netdata`) with the correct ownership/permissions if they don't already exist, _before_ we change to our actual runtime UID. A vast majority of other tools behave this way, creating their own cache/log directories if they don't exist at runtime.

**Comment by prologic** [comment]
I was just wondering if this is still an issue. I haven't run into this myself so I'm curious what system/version this happened on. We _might_ be able to close this as "can't reproduce"?
