### ISSUE TITLE
Add cron-based CI checks to verify nightlies ran succesfully

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8296]
Since we've been bitten by this twice now and both times it was me :( We should fix this.

Proposed fix is simply to add a Github Actions cron-based Workflow to verify and validate that we actually successfully created a nightly build.

**Comment by Ferroin** [comment]
These need to _not_ be in whatever our primary CI system is.

There's no point in checking from Travis if our Travis builds finished, since failures that we wouldn't otherwise notice will cause the check that they ran to not run.

**Comment by prologic** [comment]
> These need to _not_ be in whatever our primary CI system is.
> 
> There's no point in checking from Travis if our Travis builds finished, since failures that we wouldn't otherwise notice will cause the check that they ran to not run.

As discussed in person I have a different approach than the original wording of this issue. I'll put up a PR soon and we can discuss against real code :) But basically the idea is to simply have a Cron workflow that does:

- Check Docker Hub
- Checks PackageCLoud
- Checks Nightlies Storage

For "Last Updated" times of key files.

If > 48h ago, fail the job (_we'll get an email_).

Otherwise all good :)
