### ISSUE TITLE
Re-enable 'truthy' yamllint check when upstream bug is fixed.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8303]
Relevant bug is https://github.com/adrienverge/yamllint/issues/158

**Comment by ilyam8** [comment]
i see there is [a workaround](https://github.com/adrienverge/yamllint/issues/158#issuecomment-536735525), we can add `on` to the list of allowed-values.

```yaml
truthy:
  allowed-values: ['true', 'false', 'on', 'yes', 'no']
```

**Comment by ilyam8** [comment]
Fix https://github.com/adrienverge/yamllint/pull/247

**Comment by ilyam8** [comment]
https://github.com/adrienverge/yamllint/releases/tag/v1.22.0

We can re-enable `truthy` rule.
