### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8304]

**Comment by prologic** [comment]
No we will still be doing this. Other higher priority things have taken precedence.

**Comment by zack-shoylev** [comment]
I'm interested in this issue in light of potentially making installs like https://github.com/netdata/netdata/blob/master/packaging/installer/methods/pfsense.md easier (i.e. as a native package).

**Comment by prologic** [comment]
https://github.com/netdata/netdata/pull/9413 Added first class support for FreeBSD. What's left now is CI.

**Comment by prologic** [comment]
on our backlog, low priority
