### ISSUE TITLE
Properly document that we have issues with multiple installed versions of OpenSSL.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8306]
Wehn users have both a distro installed version of OpenSSL and a manually installed local version, the build fails in strange and non-obvious ways.  We should document that we don't support building in such circumstances.

Long term I see low value in actually fixing the build for this, as it is going to become a much less common situation as OpenSSL 1.1 becomes more and more common.

**Comment by joelhans** [comment]
I still need to get around to this.
