### ISSUE TITLE
Dockerd module in python plugin not showing graphs

### ISSUE THREAD

**Issue by WinstonBlue** [netdata/netdata#8309]
##### Question summary
Netdata slave pod doesn't visualize dockerd module graphs (healthy/unealthy) and alarms. 
##### OS / Environment
Netdata installed with helmchart on a kubernetes cluster in Centos7 VMs
##### Component Name
External Python plugin/dockerd module
##### Expected results
Netdata showing healthy/unhealthy container graphs and alarms

Hi,

I've installed netdata in a Kubernetes cluster (using the official helmchart) and would like to monitor healthy/unhealthy containers and set an alarm when a container is down.

I have installed python-docker module on a slave (with pip and Python 2.7 not 3.x) and enabled python plugin, dockerd module and docker health metrics with 'edit-config', as described in the official documentation.
Module debug (with '/etc/libexec/netdata/plugins.d/python.d.plugin dockerd debug trace') shows me the metrics but when I refresh the slave page on the browser i cannot see the corresponding graphs and alarms.

Ps: I have enabled other plugins and modules (such as cgroups and k8s_kubelet) to view pod metrics and I have no problems to visualize the corresponding graphs on the browser.

**Comment by ilyam8** [comment]
Hi @WinstonBlue 

Have you checked `error.log`?

See `grep python error.log`

**Comment by WinstonBlue** [comment]
Hi @ilyam8 ,
thank you for your prompt response.
I checked error.log in /var/log/netdata but i can see no logs.
Python debug shows me the following logs:

2020-03-05 10:44:53: python.d DEBUG: dockerd[local] : update => [OK] (elapsed time: 31, failed retries in a row: 0)
BEGIN dockerd_local.unhealthy_containers 993273
SET 'unhealthy_containers' = 0
END

BEGIN dockerd_local.healthy_containers 993273
SET 'healthy_containers' = 0
END

BEGIN dockerd_local.running_containers 993273
SET 'running_containers' = 57
END

BEGIN netdata.runtime_dockerd_local 993273
SET run_time = 22
END

**Comment by ilyam8** [comment]
> Python debug shows me the following logs:

@WinstonBlue do you run it as `netdata` user?

**Comment by WinstonBlue** [comment]
@ilyam8 yes.

**Comment by ilyam8** [comment]
> I have installed python-docker module on a slave (with pip and Python 2.7 not 3.x) and enabled python plugin, dockerd module and docker health metrics with 'edit-config', as described in the official documentation.


It seems it doesnt work because you install it after netdata, `python.d.plugin` should be restarted. I am not a specialist but i think you get the idea.

**Comment by hrs-io** [comment]
@ilyam8,
thank you so much!
You solved my problem.

**Comment by ilyam8** [comment]
@hrs-io what problem? 😄 Did you have same problem as @WinstonBlue ? 😄

**Comment by WinstonBlue** [comment]
@ilyam8,
ok. I've restarted the python plugin and now I can see the docker module graphs and alarms.
Thank you very much.
I close the issue.
