### ISSUE TITLE
netdata show root disc statistics for sdcard disc

### ISSUE THREAD

**Issue by ofirule** [netdata/netdata#8311]
##### OS / Environment
<pre><code>$ uname -a
Linux tegra-ubuntu 4.4.38-docker #1 SMP PREEMPT Sat Aug 4 14:06:35 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
</pre></code>

##### Netdata version

version: v1.20.0 
running on docker for aarch64

##### Explanation

These are my file system disk space usage:
<pre><code>$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        28G  8.7G   18G  34% /
devtmpfs        7.7G     0  7.7G   0% /dev
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           7.7G   68M  7.7G   1% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/mmcblk1p1   59G   20G   36G  36% /media/sdcard
tmpfs           785M     0  785M   0% /run/user/1001
</pre></code>

My docker is configured to save all images on the sdcard:
<pre><code>cat /etc/docker/daemon.json 
{"graph": "/media/sdcard/docker-base"}
</pre></code>

and it looks like netdata is reporting stats for the sdcard discs usage as if it's the disc maped to root:
![Screenshot from 2020-03-05 16-57-10](https://user-images.githubusercontent.com/3669143/75994242-55f6ce00-5f03-11ea-9d02-f83d9a708f6e.png)

##### Expected behavior

I would like netdata to show discspace statistics for my discs as shown in `df -h`

**Comment by prologic** [comment]
@ ofirule Very sorry about the late resply.

Can you share with me how you started NetData? More specifically the `docker run` options you used or the `docker-composey.yml` you used? THanks!

**Comment by ofirule** [comment]
My docker run options: 

    docker run -d --name=netdata --restart=always -v /proc:/host/proc:ro -v /sys:/host/sys:ro -v /var/run/docker.sock:/var/run/docker.sock:ro --cap-add SYS_PTRACE --cap-add NET_ADMIN -e PGID=999 --security-opt apparmor=unconfined -v /etc/notraffic/netdata/netdata.conf:/etc/netdata/netdata.conf -v /etc/notraffic/netdata/stream.conf:/etc/netdata/stream.conf -v /etc/firehol/fireqos.conf:/etc/firehol/fireqos.conf --network host netdata_with_fireqos:1.20.6


I use my own docker image which is built on top of `netdata/netdata:v1.20.0-aarch64` and adds fireqos

**Comment by ofirule** [comment]
Same problem running 
`docker rm -f netdata && docker run -d --name=netdata \
  --net=host \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  --cap-add SYS_PTRACE \
  --cap-add NET_ADMIN \
  -e PGID=999 \
  --security-opt apparmor=unconfined \
  --restart=always \
  netdata/netdata
`

Your netdata version: v1.21.1-159-gca3019e4

**Comment by prologic** [comment]
@ofirule Sorry about the late response. Please have a read of the following comments in other related issues (_I think_):

- https://github.com/netdata/netdata/issues/5071#issuecomment-460442980
-https://github.com/netdata/netdata/issues/5071#issuecomment-511764911

If I understand the issue at hand correctly if you bind-mount `/` and `/media/sdcard` from the host into the container somewhere Netdata running inside the container should be able to see that file system and produce disk utilization statistics for it.

Let me know if this helps?

**Comment by cakrit** [comment]
Closing due to no response, please comment if the instructions above don't solve your problem.
