### ISSUE TITLE
Login missed when I refresh

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8312]
##### Bug report summary
When I have my register at a remote computer inside my network, and I tried to `Sign in` to verify a more information about the alarms I had the impression that everything was fine, but when I click on the alarm it redirects me to a page with the message:

```
Sorry ... your account is not linked to netdata server named ceres.
```

And when I do the refresh my name disappear on top menu. 

On the other hand, case I go to the machine with the register and open a browser and try to do the previous steps, everything works fine.

##### OS / Environment
```
Linux hades 5.4.23 #1 SMP Sun Mar 1 11:56:15 UTC 2020 x86_64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="14.2"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=14.2
/etc/os-release:PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
/etc/os-release:HOME_URL="http://slackware.com/"
/etc/os-release:SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:VERSION_CODENAME=current
```

##### Netdata version
netdata v1.20.0-63-g489854b9 

##### Component Name
Web front end

##### Steps To Reproduce
1. Set inside your `netdata.conf` the registry to be a local machine and starts netdata
2. Go to another host to access the first machine.
3. Do the login and reload the page.

##### Expected behavior
Access remote hosts and do not lose the login after a page refresh.

**Comment by cakrit** [comment]
The alarms on the netdata UI should take you directly to the chart shown on the same UI. There's another issue open, to fix that, can't find it right now.
Alarm redirection when signed in (clicking in a URL in an email notification doesn't work, that's tracked in #9487
