### ISSUE TITLE
Address and fix TODO(s) in codebase

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8330]
#### Summary

As per [this comment](https://github.com/netdata/netdata/issues/8103#issuecomment-595490380) we want to address and fix (_remove all_) `TODO|XXX|FIXME`(s) from our codebase. This issue is to track that work.

Currently at the time of wriring:

```sh
$ sift '(TODO|FIXME|XXX)' | wc -l
179
```

**Comment by prologic** [comment]
@amoss As per discussions in relevant linked issues and closed (_but not merged_) please take this issue and prioritize as you see fit. Thanks :)

**Comment by amoss** [comment]
I've handed it over to our product owner for prioritizing as suggested.

**Comment by prologic** [comment]
I do not see this happening and this is very low priority. if this still needs to happen please open _specific_ issues to address appropriate TODO(s) in subsections of codebases. An all-encompassing issue will not work here at this time.
