### ISSUE TITLE
Algolia search challenges in docs

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8336]
I couldn't find this configuration setting from the search bar. Can we do something to make it work?

<img width="621" alt="health" src="https://user-images.githubusercontent.com/43294513/76091427-62fed600-5f72-11ea-9c84-d7b82934e46e.png">

**Comment by joelhans** [comment]
The Docsearch folks have updated their configuration for how they crawl the site, so hopefully this will be enabled soon.

**Comment by joelhans** [comment]
Closing, since this is now fixed:

![Screenshot_20200427_123203.png](https://images.zenhubusercontent.com/5d6fe9c8778eb601c98036eb/7d8f01fe-bb2e-42c5-beac-32874e3aeaea)
