### ISSUE TITLE
How monitor multiple tomcat instances with python.d?

### ISSUE THREAD

**Issue by gwingnhbc** [netdata/netdata#8338]
Sorry, newbie to netdata here.

I am trying to monitor three seperate tomcat instances, on different ports, that we have on our server and then display their charts on the main netdata console but struggling with this.  I can modify the existing tomcat plugin config so as to connect to the tomcat manager app at any one of the instances and display charts for that - but only one instance at a time.

I have fiddled around and tried a few ideas but without success - could anyone guide me as to the best approach for getting these multiple instances monitored please?

Netdata version:  v1.2.0-50
O/S:   RHEL 7.7
Hardware:  Non container, OVM/Xen 64 bit VM

**Comment by ilyam8** [comment]
Hi @gwingnhbc 

Check this issue

> https://github.com/netdata/netdata/issues/5964

**Comment by gwingnhbc** [comment]
Thanks for the super fast reply.

So easy!  I just defined the multiple jobs and it worked straight away. I *thought* I had already tried that as my first attempt at getting it working but I must have done something different/wrong the first time around :-)
