### ISSUE TITLE
Cant access Netdata dashboard via HTTPS

### ISSUE THREAD

**Issue by ddddoooo1243** [netdata/netdata#8341]
After I install netdata im trying to access my dashboard from https://server-ip:19999 and it just says This site can’t provide a secure connection

Im using centos 7

**Comment by thiagoftsm** [comment]
Hi @ddddoooo1243 ,

By default Netdata does not enable TLS connections, because it is necessary to have an TLS certificate for this works, please, take a look on https://docs.netdata.cloud/web/server/#enabling-tls-support and let us know case you have any doubt.

Best regards!

**Comment by prologic** [comment]
Hi @ddddoooo1243 as per @thiagoftsm 's comments please follow the documentation on how to enable TLS. Otherwise http://<server_ip>:19999 should work out of the box.

**Comment by niltonvasques** [comment]
Same here... I followed the instructions [here](https://docs.netdata.cloud/web/server/#enabling-tls-support) but without any success:

```config
[web]
        ssl key = /etc/netdata/ssl/key.pem
        ssl certificate = /etc/netdata/ssl/cert.pem
        # tls version = 1.3
        # tls ciphers = none
        # ses max window = 15
        # des max window = 15
        # mode = static-threaded
        # listen backlog = 4096
        # default port = 19999
        # bind to = *
        # web files owner = netdata
        # web files group = netdata
        # disconnect idle clients after seconds = 60
        # timeout for first request = 60
        # accept a streaming request every seconds = 0
        # respect do not track policy = no
        # x-frame-options response header = 
        allow connections from = localhost 192.168.0.*
        # allow connections by dns = heuristic
        # allow dashboard from = localhost *
        # allow dashboard by dns = heuristic
        # allow badges from = *
        # allow badges by dns = heuristic
        # allow streaming from = *
        # allow streaming by dns = heuristic
        # allow netdata.conf from = localhost fd* 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
        # allow netdata.conf by dns = no
        # allow management from = localhost
        # allow management by dns = heuristic
        # enable gzip compression = yes
        # gzip compression strategy = default
        # gzip compression level = 3
        # web server threads = 1
        # web server max sockets = 256
```

**Comment by thiagoftsm** [comment]
Hi @niltonvasques ,

It looks like that you are using a Netdata version that does not accept TLS 1.3 yet, we already commit a solution for our master branch and we will release 1.21 this week that will fix the problem you are having. 
You do not need to wait for the new release, you can already clone the Netdata repository and compile it from scratch to have this working for you.

Best regards!

**Comment by thiagoftsm** [comment]
@niltonvasques and @ddddoooo1243  I am considering that after we merge the support for the latest TLS your problem was fixed, be free to reopen case it is necessary.
