### ISSUE TITLE
Netdata on synology: Access to file is not permitted: /opt/netdata/usr/share/netdata/web//index.html

### ISSUE THREAD

**Issue by micah** [netdata/netdata#8343]
##### Bug report summary
I installed Netdata on Synology, as described on https://docs.netdata.cloud/packaging/installer/methods/synology/. First I created a user/group called 'netdata', then I installed using: https://docs.netdata.cloud/packaging/installer/methods/kickstart-64/

I then ran the chown commands detailed on the synology installation page, and then I attempted to go to http://192.168.1.241:19999 where I received this message:

```
Access to file is not permitted: /opt/netdata/usr/share/netdata/web//index.html
```

No configuration was done, if I pull the config, I see that `run as user = netdata` and `web files owner = netdata` are commented out, so the defaults are used. But this does make me wonder about the Synology installation chown steps:

```
chown -R root:netdata /opt/netdata/usr/share/netdata
chown -R netdata:netdata /opt/netdata/var/lib/netdata /opt/netdata/var/cache/netdata
chown -R netdata:root /opt/netdata/var/log/netdata
```

Doesn't that mean the config should be changed to be `web files owner = root` ? I tried to change this in the config and reload, but that didn't seem to change anything.

The `/opt/netdata/var/log/netdata/error.log` didn't have any information about this.

##### OS / Environment
This is a Synology DS918+ which is an intel-based linux 4.4.59 kernel

##### Netdata version
netdata v1.20.0-90-g3599ad65

```
netdata  15816  1.3  1.5 115016 58856 ?        SNl  09:50   0:17 /opt/netdata/bin/srv/netdata
netdata  16068  0.1  0.0   1644  1308 ?        SN   09:50   0:02 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata  16078  0.1  0.0   2072  1732 ?        SN   09:50   0:01 bash /opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin 1
root     16089  3.1  0.1   7432  5636 ?        SN   09:50   0:41 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
netdata  16093  0.3  0.6 135584 24756 ?        SNl  09:50   0:04 /bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata  16095  0.0  0.4 125516 16536 ?        SNl  09:50   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
root     28537  0.0  0.0  23148  2208 pts/22   S+   10:12   0:00 grep netdata
```

##### Component Name
Web

**Comment by micah** [comment]
I changed `netdata.conf` to have `web files owner = root` and `web files group = netdata` and restarted netdata, and now it works. The default config file had `users` as the group. 

It seems that the Synology instructions should be updated to show people how to get the netdata.conf and edit it for these settings.

Is it not possible to have the web files owned as `netdata`?

**Comment by prologic** [comment]
@micah Thanks for reporting! Are you okay with the current work-around you've found? I haven't been able to repro this issue yet as getting a hold of a Sinology environment has been tricky (_trying to get [this working](https://xpenology.club/install-dsm-6-1-on-virtualbox/)..._)

**Comment by micah** [comment]
It does seem like it works.

The only thing I'm concerned about is discussion elsewhere about having
the files owned as `root`, but that seems like an orthogonal issue.

**Comment by jptuomi** [comment]
I can confirm that this solves the issue, the guide should be updated with these two settings.
https://docs.netdata.cloud/packaging/installer/methods/synology/

**Comment by ilyam8** [comment]
@jptuomi are you willing to make a PR?

**Comment by prologic** [comment]
As per @ilyam8's comment and mine; I'm unassigning NetData as owners of this issue and re-leballeing appropriately. We need community help to deliver this as none of us have access to a Synology device and it is rather difficult (AFAIK) to get a local Synology VM (_I've tried_).

If someone is willing to put up a PR for this; we will happily review and accept it. Thanks!

**Comment by kachunkachunk** [comment]
@prologic - It really is a bit of a bear getting a Synology VM going, but you can start here: https://xpenology.com/forum/topic/13061-tutorial-install-dsm-62-on-esxi-67/, and if it's too much of a pain in the rear, I can make one for you (eventually). Mostly just need to know what your host CPU would be, and what hypervisor.

As for this issue and impending PR, only thing I can add is that Synology DSM seems to force you into leaving the new netdata user in the Users group (GID=100), and I'm not sure how to pull it from that group. But I assume this is what influences the start sequence into making it conflict with the web files ownership policy.

**Comment by prologic** [comment]
@kachunkachunk Thanks for the update! Appreciate it. Unfortunately I actually tried to get a Synology VM going here and I wasn't able to (_easily_). Short of buying a Synology NAS myself its going ot be a bit hard for me to make the necessary changes here and throughly test them. We still need communiry fuppsort for this.

If you are able to provide a VMDK or QCOW disk image of a running Sinology DSM OS it might makes things a bit easier to do dev/testing on. It would be VirtualBox Hypervisor or QEMU/KVM on Intel chips.

**Comment by vanguardcloud** [comment]
@prologic @ilyam8 hey guys! This is my first post here at GitHub just because **I'm just following love with NETDATA**, specially for Synology! Based on this I feel that I have to contribute somehow. If you want to connect remotely in my system we can work on this and I can definitely get you access.

I will also try to configure for you a XPnology VM so you can do any test you want in the future, I used to test Synology in a VM by myself, just need to seat and make it once again.

Thank you all!

**Comment by kachunkachunk** [comment]
I've personally been too busy and this slipped off my radar. I'm more of a VMware hypervisor kind of guy, as well. Hopefully you can put something convenient together for prologic or anyone else developing on VirtualBox or QEMU/KVM.

**Comment by prologic** [comment]
if someone can get my a Synology VM ready to go I can make this happen.

**Comment by vanguardcloud** [comment]
@prologic I just finished the Synology VM. Here is the URL for download: [https://www.transfernow.net/6tKeh5072020](url)

`user = admin | pass = Password100!`

Let me know if you need any assistance from here.

**Comment by prologic** [comment]
Thank you! Downloaded. I'll have a play with this when I get other things off my plate!

**Comment by vanguardcloud** [comment]
No problem @prologic ! Really enjoying the great work you guys are doing with netdata, so please feel free to reach me out if you need any assistance with Synology. Unfortunately I can't afford a real device, but if for any reason it is necessary, we can definitely use mine for tests :+1:

**Comment by prologic** [comment]
Thanks!  I'm still leaving this issue as "Help Wanted"; as that's actually true and I'm not sure when I'll be able to get to this. But I'll try :)

**Comment by UAnton** [comment]
Same BUG in last update!

**Comment by prologic** [comment]
> Same BUG in the last update!

This issue is quite old, dare you able to share some details?
