### ISSUE TITLE
CPU statistics using eBPF

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8346]
##### Feature idea summary
During the spike #7885 , it was identified that we can bring CPU monitoring using `perf` events like the command `perf` does. And considering what we have as output from this command,  it is possible to say that we can bring a general CPU statistic using `perf` events.

##### Expected behavior
To have new charts that will demonstrate the following information per PID:

``` Performance counter stats for 'gzip file1':

       1920.159821 task-clock                #    0.991 CPUs utilized          
                13 context-switches          #    0.007 K/sec                  
                 0 CPU-migrations            #    0.000 K/sec                  
               258 page-faults               #    0.134 K/sec                  
     5,649,595,479 cycles                    #    2.942 GHz                     [83.43%]
     1,808,339,931 stalled-cycles-frontend   #   32.01% frontend cycles idle    [83.54%]
     1,171,884,577 stalled-cycles-backend    #   20.74% backend  cycles idle    [66.77%]
     8,625,207,199 instructions              #    1.53  insns per cycle        
                                             #    0.21  stalled cycles per insn [83.51%]
     1,488,797,176 branches                  #  775.351 M/sec                   [82.58%]
        53,395,139 branch-misses             #    3.59% of all branches         [83.78%]
```

Ths example was extracted from http://brendangregg.com/perf.html#CPUstatistics

**Comment by ilyam8** [comment]
Issue moved to [netdata/kernel-collector #247](https://github.com/netdata/kernel-collector/issues/247) via [**ZenHub**](https://www.zenhub.com/)
