### ISSUE TITLE
Difference between bandwidth of server interface and sum of web_log bandwidth

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8348]
##### Bug report summary
We have an Nginx load balancer which we monitor all the v hosts using the web_log module. The log format is like bellow:
```
log_format netdata '$remote_addr - $remote_user [$time_local] ' '"$request" $status $body_bytes_sent ' '$request_length $request_time ' '"$http_referer" "$http_user_agent" "$upstream_addr" "$http_locale" $upstream_response_time';
```
The only service which is running on this server is the `nginx`, but when I compare `netdata_web_log_bandwidth_kilobits_persec_average` metric with `netdata_system_ip_kilobits_persec_average` there is huge difference among them:
![Untitled](https://user-images.githubusercontent.com/7656049/76206100-aaa28d80-6210-11ea-85e9-f2b411abac67.png)

##### OS / Environment

```
Linux nginx-01.lb.x.y.z 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="9"
/etc/os-release:VERSION="9 (stretch)"
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

 
netdata v1.19.0
##### Component Name

external plugins

##### Expected behavior
get almost the same output

**Comment by yasharne** [comment]
I think I found the answer, `web_log` calculates the bandwidth used for the requests which arrive to the Nginx (like `GET HTTP`) and  the response made by Nginx (like `200 HTTP`) from the log files, so it is not aware of things like `TCP handshake` or `SSL handshake` or `TCP retransmission` etc. thats why we get more traffic in interface chart rather than in the web_log charts.

**Comment by ilyam8** [comment]
Yes, it depends on used parameter.

> https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#known-fields

For example:

- `$bytes_sent` (`%O`) - Bytes sent to a client, including request and headers.

- `$body_bytes_sent` (%B/%b) - Bytes sent to a client, not counting the response header.


> Since httpd 2.0, unlike 1.3, the %b and %B format strings do not represent the number of bytes sent to the client, but simply the size in bytes of the HTTP response. It will will differ, for instance, if the connection is aborted, or if SSL is used. The %O format provided by mod_logio will log the actual number of bytes sent over the network.
