### ISSUE TITLE
Fix the JSON parsing issues on the ACLK.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8349]
#### Summary

We need to fix problems that were observed during the smoke-test. 
* The uninitialised variables inside the JSON parser that valgrind is complaining about.
* The behavior depends on which json parser is in use. If the JSONC external dependency is available then it works, it seems to break on the internal version.

Currently there are somehwere up to three different json parsers in use in the project in different places. This is a problem that we need to resolve but we cannot do in this sprint because of time. 

This will be fixed now, and then after March 25 we will clean this up properly in #7701.

**Comment by stelfrag** [comment]
Update: 

- In certain occasions the user supplied callback function was not called to fill the user supplied structure with the parsed results
