### ISSUE TITLE
Fix the pop-corning implementation in the ACLK.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8350]
#### Summary

* Before the beginning of the sprint clarify with product what should happen to queries / commands on the ACLK before the popcorning process has finished.
* All queries are ignored (dropped) during pop-corning, but commands from the cloud are in the same queue for processing so the agent would ignore requests during this period.
* Any query resets the pop-corning timer (including encapsulated queries) so pop-corning can go on indefinitely.
* The implementation of the time-out / check is wrong and it will always sleep 10s longer than necessary.

**Comment by stelfrag** [comment]
In sync with the product team it was decided that queries during pop-corning will be ignored. We will re-examine this in the future if there are new commands sent to the agent that need to be handled in a different way.

**Comment by stelfrag** [comment]
> All queries are ignored (dropped) during pop-corning, but commands from the cloud are in the same queue for processing so the agent would ignore requests during this period.

- Added check so that incoming requests from the cloud will be ignored if the agent is still initializing. There is no attempt to queue the commands.

> Any query resets the pop-corning timer (including encapsulated queries) so pop-corning can go on indefinitely.

The timer is not affected by the cloud commands anymore

**Comment by stelfrag** [comment]
> The implementation of the time-out / check is wrong and it will always sleep 10s longer than necessary.

The interval will be reduced / tuned. As it is now, it will always sleep X seconds (defined as 10 now) so if the last activity is detected on _agent_start_ + 9 seconds, it will sleep another 10 seconds so the agent will be marked stable on _agent_start_ + 19 seconds
