### ISSUE TITLE
Specific Metrics using prometheus_all_hosts

### ISSUE THREAD

**Issue by E46-S54** [netdata/netdata#8361]
#### Question summary
I am running netdata 1.20 and am experimenting with the prometheus_all_hosts exporter.

I'd like to extract a single metric for all my hosts from a netdata master, say for example IO WAIT or whatever it may be.

Is there a way I can use the API to pull just all IO WAIT metrics for all hosts, rather than every metric for every host using `api/v1/allmetrics?format=prometheus_all_hosts`

Thanks

**Comment by vlvkobal** [comment]
No, it's not possible at the moment.

**Comment by E46-S54** [comment]
Thanks @vlvkobal
