### ISSUE TITLE
ACLK Last Will Testament implementation

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#8369]
#### Summary
The ACLK should define a Last Will Testament (LWT) that will be triggered when there is an abnormal link failure (described in the ACLK specifications document)

The LWT message will be (example):

```
{
    "type" : "disconnect",
    "version" : 1,
    "msg-id" : "fbc8509b-c3f7-492e-a1f8-303662853054",
    "timestamp" : 1583858212,
    "payload" : "unexpected"
}
```

The payload value **unexpected** denotes that the disconnection was not initiated by the agent. 

If the agent initiates the disconnection, e.g. when the agent is shutdown, then the message that will be sent will be: 

```
{
    "type" : "disconnect",
    "version" : 1,
    "msg-id" : "fbc8509b-c3f7-492e-a1f8-303662853054",
    "timestamp" : 1583858212,
    "payload" : "graceful"
}
```
The payload value **graceful** denotes that the disconnection was initiated by the agent. 

This will be done in the following way:

1. Agent shutdown is detected while the ACLK is established
2. The **disconnect** message with the **graceful** payload is prepared and send to the cloud
3. Agent explicitly sends a disconnect command to the cloud to gracefully shutdown the connection
    - This is how the broker on the cloud side _understands_ that the LWT will not be sent.
4. Agent shutdown completes

Notes:
1. If the shutdown is detected before agent enters a stable state.
    - Agent should disconnect as soon as possible
2. The timestamp on the LWT message will be in the past, i.e. when the agent initiated the ACLK.

**Comment by underhood** [comment]
> The payload value unexpected denotes that the disconnection was not initiated by the agent.
Is there any case where cloud disconnects gracefully (e.g. update on cloud side) when it is expected?

**Comment by stelfrag** [comment]
Update:

- The LWT is set before the connection is established. 
- When the agent shutdowns gracefully: 
  - A new message that indicates a `graceful` shutdown is constructed and sent to the ACLKs `outbound/meta` topic.
  - An MQTT disconnect packet is created.
  - The lws layer needs to remain active to deliver the final message to the broker
  - The event loop is called explicitly to handle the packet delivery.
