### ISSUE TITLE
Mysql Chart Not Showing Up

### ISSUE THREAD

**Issue by WerdPress** [netdata/netdata#8370]
For some reason I cannot get Mysql monitor to showup on the front end. I have tested from commandline to see if there were any issues with:

`./go.d.plugin -d -m mysql`

Connects fine and looks to work ok.

Logs don't show any issues but nothing on front, see screen. Not really sure where to look next.

![netdata011](https://user-images.githubusercontent.com/62028949/76339285-40512200-62d0-11ea-8570-6562acaf1941.png)

Ubuntu 18.04
Netdata installed with one liner
Current Version: v1.20.0-119-nightly
**Mysql:** Using Percona drop in for Mysql 8

**Comment by ilyam8** [comment]
Hi @WerdPress 

Go version of mysql is disabled by default atm, so you either use [python version ](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mysql) (collects more metrics but you need to install MySQLdb lib) or [enable go version](https://github.com/netdata/go.d.plugin#why-disabled-how-to-enable).

**Comment by WerdPress** [comment]
@ilyam8 

Thanks for that. I have made sure python version is disabled and enabled go version and restarted netdata. But it still refuses to showup on the front-end. Can you think of anything else I might check to help me figure out why it is still missing?

**Comment by ilyam8** [comment]
> ./go.d.plugin -d -m mysql

Did you run it as `netdata` user?

And check `error.log`

> grep mysql error.log

**Comment by WerdPress** [comment]
@ilyam8 

Thanks, I got it sorted out, few things that I had missed or messed up.

1.) In "go.d.conf" I had uncommented mysql line but accidentally removed space from start.
2.) My go.d/mysql.conf was broken
