### ISSUE TITLE
[docs] 404 errors on `go.d` collector links, 'name' column

### ISSUE THREAD

**Issue by petecooper** [netdata/netdata#8377]
##### Bug report summary

404 errors on `go.d` collector links, specifically the 'name' column:

https://github.com/netdata/netdata/blob/master/collectors/COLLECTORS.md#go-god

Leaving this here as a note to myself, I will investigate and raise a PR if/when I find correct links.

**Comment by petecooper** [comment]
Actually, I'm going to have to defer to someone else - the target directory https://github.com/netdata/netdata/blob/master/collectors/go.d.plugin/modules/ and its parent (https://github.com/netdata/netdata/blob/master/collectors/go.d.plugin/) appear to be missing and my search foo isn't able to locate it.

**Comment by ilyam8** [comment]
thx for reporting @petecooper!
