### ISSUE TITLE
SNMPv3 - AES?

### ISSUE THREAD

**Issue by PewPewFingerGuns** [netdata/netdata#8395]
I as reading the documentation regarding the SNMPv3 implementation and noticed only two options are available:

"none", 
"DES".

Am I correct in assuming AES is not yet supported?

**Comment by ilyam8** [comment]
Netdata uses [node-net-snmp](https://github.com/markabrahams/node-net-snmp) lib. I see AES support was added 24 Jan

> https://github.com/markabrahams/node-net-snmp/commit/666cbd45034f4a202ff8fded64e2f0674d6186a2#diff-168726dbe96b3ce427e7fedce31bb0bc


We need to update the lib

**Comment by ilyam8** [comment]
We have `node-net-snmp` lib vendored, i see they added mib parsing feature (10k+ lines)

> https://github.com/markabrahams/node-net-snmp/commit/62eef8e7f2ef142f814899c88b74ee2ddb6acfb5#diff-168726dbe96b3ce427e7fedce31bb0bc

Vendor the latest version means add all those lines to the netdata repo. What do you think guys @cakrit @jacekkolasa ?

**Comment by ilyam8** [comment]
Probably it will work w/o adding mibs

> https://github.com/markabrahams/node-net-snmp/tree/master/lib/mibs

**Comment by ilyam8** [comment]
@markabrahams could you help? We would like to update to the latest but it would be nice to not include mibs and at the same time it would be nice to not change source code.

**Comment by markabrahams** [comment]
Hi @ilyam8 - at the moment the structure of the module is monolithic, and the MIBs are required for the agent implementation and MIB parsing sections of the module.  Removing these would leave a half-broken module, even though it's a half you might not use in your case.  So your options are to live with the 300KB of extra MIB files, or fork the repo and delete the MIBs - and maybe to be consistent delete the agent and MIB parser code.

**Comment by ilyam8** [comment]
> or fork the repo and delete the MIBs - and maybe to be consistent delete the agent and MIB parser code.

i dont like it because it will be hard to keep in sync with the upstream.

@amoss what do you think?

**Comment by amoss** [comment]
> > or fork the repo and delete the MIBs - and maybe to be consistent delete the agent and MIB parser code.
> 
> i dont like it because it will be hard to keep in sync with the upstream.
> 
> @amoss what do you think?

* Which collector will use it and what language is that collector implemented in?
* Is this the main repo or go.d?

**Comment by ilyam8** [comment]
> Which collector will use it and what language is that collector implemented in?

snmp collector - node.js

> https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/snmp

`node-net-snmp` lib is vendored

> https://github.com/netdata/netdata/blob/master/collectors/node.d.plugin/node_modules/net-snmp.js

It would be nice to update it because lack of AES sounds bad, but to have it updated we need to add +300KB (costs of having something vendored).

**Comment by ilyam8** [comment]
Closing this issue due to [the low interest in this feautre](https://github.com/netdata/netdata/pull/8408).

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
