### ISSUE TITLE
`install-required-packages.sh` doesn't pull in packages for some optional features.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8396]
Currently, to build all the optional features in netdata, you need to install almost a dozen extra packages beyond what `install-required-packages.sh netdata-all` pulls in.

**Comment by prologic** [comment]
Lets also as part of this work figure out how to prevent this divergence from happening again in addition to fixing the missing dependencies in our tooling.

**Comment by prologic** [comment]
I _think_ this can go in our Backlog too as lo-pri at this time. Its not blocking anyone or anything I can think of right now.

**Comment by Ferroin** [comment]
The way to prevent this from happening in the future is to add a configure option to turn on all the optional dependencies, and then use that option for CI builds.

The simple fact that this stuff was optional is why it got missed.

**Comment by prologic** [comment]
Let's make it two separate CI jobs? One that builds normally ignoring options features and the other that forces optional features.

**Comment by Ferroin** [comment]
I'm fine with either approach, but this needs fixed regardless.

@netdata/core Could we get an up-to-date list of all the optional dependencies for various Netdata features (and ideally info on how to force those features to be built) so we can properly update our testing and prevent issues like this from coming up in the future?

**Comment by mfundul** [comment]
I don't think it's as simple as `all` vs `optional`. For instance, `dbengine` support is optional but it should be an enforced dependency for most users because it is important for user experience.

I propose something like `mandatory`, `default`, `optional`. Where some features from `optional` would also be part of the `default` installation.

**Comment by Ferroin** [comment]
I rather like that idea, possibly add a `netdata-basic` target for `install-required-packages.sh` that only pulls in the stuff that's absolutely required for Netdata to build.

That doesn't change the need though for us to have a proper dependency list somewhere. I can theoretically put that together myself, but it is likely to be far simpler to get info from the people who developed the optional features  as to what they require and how to enable them.

**Comment by mfundul** [comment]
`dbengine` relies on libuuid, libuv1, lz4, Judy, and openssl. I think libuuid and libuv1 are mandatory so that would leave us only lz4, Judy and openssl.

**Comment by mfundul** [comment]
There is some information [here](https://github.com/netdata/netdata/blob/master/packaging/installer/methods/manual.md)

**Comment by Ferroin** [comment]
Yeah, the install documents are also incomplete. The primary offender I know of right now is the stuff in the exporting engine, but for all I know there could be other things I don't know of.

**Comment by amoss** [comment]
Why is this a problem? If the features are optional then they should not be in the required packages list.

**Comment by mfundul** [comment]
`dbengine` is optional.

**Comment by amoss** [comment]
`dbengine` is the default. We should probably treat that differently to something that is optional. Recommended?

**Comment by prologic** [comment]
It is a problem because we have no continuous way of testing and ensuring the feature builds. Along with appropriate unit tests and forced optional features we can also ensure that the optional feature should in theory also work.

**Comment by Ferroin** [comment]
More specifically than what @prologic said (which is correct), `install-required-packages.sh netdata-all` should pull in _all_ packages that are needed for a full featured build (that is, every optional feature turned on). Regular installs are done with `install-required-packages.sh netdata`, which only pulls in the requirements for a default install right now. The expectation here is just as much that _users_ have a way to easily pull in all the deps to ensure they can build with a specific set of features without having to look up per-feature what those deps are (especially since we don't have most of the optional ones for build-time features like the exporting engine listed in the docs).

**Comment by amoss** [comment]
That makes sense (thanks @Ferroin for the explanation). So you need to know a full list of required and optional packages to make both configurations works.

**Comment by amoss** [comment]
Can we set up a list that will be maintained that lists the available features - for each one specifying:
* Required / recommended (or "default") / optional.
* List of package dependencies for each package manager that we have listed in the manual install instructions.

I'm open to suggestions about syntax / formatting, but the file should be kept in the main repo so that devs can update it as they add or modify features.

It would be nice we generated the manual installation instructions from it, as well as using it to drive the CI/CD.

**Comment by Ferroin** [comment]
I think having a dedicate list is a good idea, but I don't know how viable it will be to verify things in CI unless we also get a way to force trying to enable all the optional features at build time and fail if any deps can't be found.

**Comment by amoss** [comment]
What if we add the appropriate installer flag to enable the feature to the file - would that allow testing?

**Comment by Ferroin** [comment]
That would help significantly, provide that the file is easily parseable from shell script (CSV or TSV would be great, JSON a bit less so (it's a pain to loop over JSON arrays in shell script).

**Comment by amoss** [comment]
The rumors of my attachment to JSON have been greatly exaggerated :), if you propose a simple text syntax then we can get feedback from @netdata/core about how it would work.

**Comment by Ferroin** [comment]
I'd say just plain TSV should be fine. We need a field for the feature name, a list of dependencies, and the switch to enable the feature. Possibly do separate fields for each package manager we support instead of just one for deps (having just the dependncy names is actually arguably more useful for getting support for new platforms, but of course less useful for users doing installs).

**Comment by prologic** [comment]
> It would be nice we generated the manual installation instructions from it, as well as using it to drive the CI/CD.

This. If we use `YAML` we can drive the CI/CD system with that. I'm pretty sure we can also generate docs based on this too. cc @joelhans

**Comment by prologic** [comment]
Please let's use YAML. We already have the tooling. We can _easily_ use `jq` in our CI/CD systems (_which is already installed anyway_) to handle any kind of query we want (_eg.: looping over arrays_)

**Comment by prologic** [comment]
@Ferroin Do you mind if we remove the bug label here? This isn't really bug but a feature/enhancement to pre-existing flows. We _should_ do this but it was never designed to do so in the first place; so not a bug :)

**Comment by Ferroin** [comment]
@prologic It's technically both a feature request and a bug. The `netdata-all` target for `install-required-packages.sh` is supposed to pull in _everthing_ you need for all features of netdata, and it does not right now, so that's a bug.

**Comment by prologic** [comment]
Fair :)

**Comment by cakrit** [comment]
The only thing needed from the agent team is a clean markdown document with a simple table with two columns: Feature (more than one words acceptable) and Library (one word only)

This will allow @Ferroin to fix install-required-packages once, link that document to the maintainer guide and enable future automations.

**Comment by amoss** [comment]
I've added this to the epic for changing the deps for the static build. I'll make the list as part of that work.

**Comment by Ferroin** [comment]
Closing this as it’s obviously not going to happen, and we are pivoting instead to preferentially pulling in minimal dependencies and not building locally at all.
