### ISSUE TITLE
Obviously bogus values reported for idlejitter.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8409]
##### Bug report summary
The idle jitter collector is reporting obviously bogus values on my home server system. Hardware is a Ryzen 9 3950X with 64GB of DDR4-2666 RAM.

The `min` dimension is stuck reporting 0, `max` is stuck reporting -1, and `average` is seemingly randomly jumping between 0 and 361701000000000000.

![screenshot-7503b3bf](https://user-images.githubusercontent.com/905151/76775416-b4ca0c00-677b-11ea-8f21-d6cff5f5f2a2.png)

I've looked on a couple of other systems, and do not see the same behavior, but I've ruled out most of the likely hardware issues that could cause something like this (RAM and CPU appear to be perfectly fine, PSU is working correctly (and has plenty of excess capacity)).

##### OS / Environment
```
Linux home-one 5.5.1-ahferroin7+ #146 SMP Sun Mar 15 11:35:16 EDT 2020 x86_64 AMD Ryzen 9 3950X 16-Core Processor AuthenticAMD GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.7
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo/Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:HOME_URL="https://www.gentoo.org/"
/etc/os-release:SUPPORT_URL="https://www.gentoo.org/support/"
/etc/os-release:BUG_REPORT_URL="https://bugs.gentoo.org/"
```

##### Netdata version
netdata v1.20.0-171-g161ba159, but I've also verified this on the 1.20 release on the same system.

##### Component Name
area/collectors

##### Steps To Reproduce
None so far.

##### Expected behavior
Properly sensible values for idle jitter.

**Comment by mfundul** [comment]
Have you tried different `memory mode`s? Have you enabled HPET?

**Comment by Ferroin** [comment]
There's no option to disable the HPET on this hardware. I've not tested yet with a different memory mode though. I'll check that first thing after lunch.

**Comment by mfundul** [comment]
What are the values of `dmesg | grep HPET` and `cat /sys/devices/system/clocksource/clocksource0/current_clocksource`?

**Comment by mfundul** [comment]
It's possible that the idlejitter data collection thread is hopping from CPU complex to CPU complex and changes clock domains. But that would only make sense if there was no reliable system clock.

**Comment by Ferroin** [comment]
It can't be an issue with jumping between domains. First thing I tried right after opening the issue was pinning the idle jitter thread to a single CPU, and that's doing nothing.

Possibly relevant, but it reports 'normal' metrics for a short period of time after the system reboots, typically a few minutes from when Netdata itself starts up, but just restarting Netdata does nothing.

There are three lines regarding the HPET in `dmesg` output:

``
[  +0.000000] ACPI: HPET 0x00000000D8BB6140 000038 (v01 ALASKA A M I    01072009 AMI  00000005)
```
```
[  +0.000000] ACPI: HPET id: 0x10228201 base: 0xfed00000
```
```
[  +0.070000] tsc: PIT calibration matches HPET. 2 loops
```

How exactly is the idlejitter collector poking at the HPET though? is this a case of us using kernel interfaces that in turn rely on it, or are we actually trying to talk to it?

**Comment by Ferroin** [comment]
Same behavior with `memory mode = ram` and `memory mode = save` as well, so it looks like it's not the dbengine at least.

**Comment by Ferroin** [comment]
Also, current clock source appears to be TSC, not HPET. I'll reboot with `clocksource=hpet` to see if that helps at all.

**Comment by Ferroin** [comment]
Same behavior with the clocksource forced to be the HPET.

**Comment by Ferroin** [comment]
Correction, looks like that _may_ have fixed it. I'm not 100% certain yet though.

**Comment by Ferroin** [comment]
Nope, didn't fix it.

**Comment by mfundul** [comment]
> 
> 
> It can't be an issue with jumping between domains. First thing I tried right after opening the issue was pinning the idle jitter thread to a single CPU, and that's doing nothing.
> 
> Possibly relevant, but it reports 'normal' metrics for a short period of time after the system reboots, typically a few minutes from when Netdata itself starts up, but just restarting Netdata does nothing.
> 
> There are three lines regarding the HPET in `dmesg` output:
> 
> ```
> [  +0.000000] ACPI: HPET 0x00000000D8BB6140 000038 (v01 ALASKA A M I    01072009 AMI  00000005)
> ```
> 
> ```
> [  +0.000000] ACPI: HPET id: 0x10228201 base: 0xfed00000
> ```
> 
> ```
> [  +0.070000] tsc: PIT calibration matches HPET. 2 loops
> ```
> 
> How exactly is the idlejitter collector poking at the HPET though? Is this a case of us using kernel interfaces that in turn rely on it, or are we actually trying to talk to it?

No, we're not actually talking to it, it is the former. It is actually pretty straightforward code, this is why I was thinking this being a hardware configuration issue.

**Comment by mfundul** [comment]
I did change some clock code in the daemon but if the release version 1.20 has the same problem then this is not the cause.

**Comment by Ferroin** [comment]
I can check 1.20 again just to be sure.

I think it probably is something with the hardware configuration though, I'm not seeing the same issues with a functionally identical build of Netdata on any of my other systems, and I was not seeing this behavior prior to upgrading the hardware in question over the weekend. I'm stumped as to what exactly it might be though. The NTP daemon on the same system is still reporting less than 2ms of clock jitter just like it was before, so I don't _think_ timekeeping is completely inconsistent here.

Also, not sure if it's relevant, but I've looked a bitt further at the actual data, and it looks like instead of reading back as 0 outside of the huge spikes, the `average` dimension is reporting values that actually make sense for this hardware given the load and observed behavior system performance. It also seems, somewhat interestingly, to spike less when all the CPU cores are at near full utilization.

**Comment by mfundul** [comment]
I think Ryzen CPUs turn off their clocks during CPU sleep states whereas intel CPUs do not. However, I would expect HPET to solve this kind of problem.

**Comment by mfundul** [comment]
Might be related to this? https://www.tomshardware.com/reviews/amd-ryzen-clock-bug-benchmark-scores,6312.html

**Comment by Ferroin** [comment]
Possibly, but the discrepancy here seems a bit large for it to be that. 361701000000000000 microseconds translates to roughly 11461 years if I'm doing the math right...It doesn't look much like an overflow error either though. It works out to 5050524A3E75000 in hexadecimal, so it's not at a easy to understand halfway point.

**Comment by Ferroin** [comment]
However, I can try rebuilding the kernel with a different timer frequency and see if that changes anything. IIRC, this one is the only system I have running at 100Hz.

**Comment by Ferroin** [comment]
Using a kernel with a different timer frequency appears to produce no visible changes in the behavior either.

**Comment by MrAmos123** [comment]
Hmm, I just raised the same issue. (Sorry about that, I missed this thread)

https://github.com/netdata/netdata/issues/8436

**Comment by mfundul** [comment]
@MrAmos123 can you verify if this problem exists in the official release version v.1.20?

**Comment by MrAmos123** [comment]
> @MrAmos123 can you verify if this problem exists in the official release version v1.20?

I haven't forgotten will edit this comment when I get home and I'm able to do this.

**Comment by mfundul** [comment]
@Ferroin we have some conflicting information from:
https://github.com/netdata/netdata/issues/8436#issue-584447821

more specifically:
`This used to work fine, not sure what happened. It's stopped working within the last few days.`

Can you retest the release version v1.20? At this point it looks like it could be the commit https://github.com/netdata/netdata/commit/161ba1592f5412bd378ace104979ddb66cd33973

**Comment by mfundul** [comment]
@MrAmos123 can you test https://github.com/netdata/netdata/pull/8441?

**Comment by MrAmos123** [comment]
@mfundul Okay -- So I'm not sure how to downgrade Netdata to an earlier version, however, I installed Ubuntu Server 18.04.4 LTS on a VM locally (fresh from Ubuntu) and installed Netdata on it using the script `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`.

So clean ISO and clean Netdata install and `idlejitter` broken out of the box.

I hope this is somewhat helpful.  

If I can get some instructions to help downgrade I can test it for you then.

The Virtual Environment is VMware's ESXi.

**Comment by ilyam8** [comment]
@MrAmos123 

```
git clone https://github.com/mfundul/netdata --branch=fix-idle-jitter netdata_fix_idlejitter
cd netdata_fix_idlejitter
sudo ./netdata-installer.sh --install /opt
```

remove `/opt` if your current install not in `/opt`

**Comment by MrAmos123** [comment]
This is really odd, I wanted to test it on a HyperV VM and I can't replicate it using the nightly builds. I'll need to close some VM's when I get a chance on my ESXi box to test there, right now I can't test it.
