### ISSUE TITLE
Coverity (CID 355076)

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8415]
##### Bug report summary
```
/streaming/rrdpush.c: 175 in configured_as_master()
169         int is_master = 0;
170     
171         appconfig_wrlock(&stream_config);
172         for (section = stream_config.first_section; section; section = section->next) {
173             uuid_t uuid;
174     
>>>     CID 355076:  Program hangs  (LOCK)
>>>     "appconfig_get_boolean" locks "stream_config.mutex" while it is locked.
175             if (uuid_parse(section->name, uuid) != -1 &&
176                 appconfig_get_boolean(&stream_config, section->name, "enabled", 0)) {
177                 is_master = 1;
178                 break;
179             }
180         }
```

We have the following call sequence : `appconfig_get_boolean` -> `appconfig_get` , when the function on line 289 inside the file `libnetdata/config/appconfig.c`  is called it tries to find the section that we want and case it is not found, it calls appconfig_section_create and this function also calls `appconfig_wrlock`.

We need to avoid this situation that always happen when Netdata starts.

##### OS / Environment

```
Linux hades 5.4.25 #1 SMP Sat Mar 14 12:33:07 UTC 2020 x86_64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="14.2"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=14.2
/etc/os-release:PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
/etc/os-release:HOME_URL="http://slackware.com/"
/etc/os-release:SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:VERSION_CODENAME=current

```

##### Netdata version
netdata v1.20.0-293-g158e9f21 

##### Component Name
Stream

##### Expected behavior
Eliminate the error reported.

**Comment by thiagoftsm** [comment]
I reviewed the whole code around this bug described here, and I arrived in the conclusion that Coverity gave us this bug report, because it could not detect that we are locking `sections` and we are doing a loop trough values that cannot be recreated. The maximum that could happen in this situation is we create another option.

The final conclusion is that we have here a false positive. I will copy this description to Coverity when their site returns.

**Comment by mfundul** [comment]
The problem here is that while we already know the `struct section *` value we have to go back and do a lookup by name because the API does not allow us to work on a `struct section *` pointer.

I think the best solution would be to refactor the API a little bit and have 2 functions instead of 1. The outer function remains the same as it is, looks up by name. This function calls the inner function that works on the pointer. Finally, we externalize the inner function API and we sanitize the code easily.

E.g. from
```
char *appconfig_get(struct config *root,
                    const char *section,
                    const char *name,
                    const char *default_value)
{
...
}
```
to
```
char *appconfig_get_by_section(struct section *section,
                               const char *name,
                               const char *default value)
{
...
}

char *appconfig_get(struct config *root,
                    const char *section,
                    const char *name,
                    const char *default_value)
{
    // lookup/lock/get struct section pointer
    return appconfig_get_by_section(co, name, default_value);
}
```

**Comment by amoss** [comment]
Reworking the API looks like the good option here - haven't procedures that may / may-not acquire locks depending on the context of the call is dangerous and prone to future error.

**Comment by thiagoftsm** [comment]
I agree with both, let us try to plan this for next sprints.
