### ISSUE TITLE
DNS query plugin doesn't detect the dns failure 

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8419]
##### Bug report summary

We are using the DNS query plugin to monitor one of our services from `1.1.1.1`. The problem is, we got in a situation where we couldn't resolve the query using dig command:
```
dig @1.1.1.1 services.y.z

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> @1.1.1.1 services.asanpardakht.net
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
We even closed the `1.1.1.1` destination on the firewall,
but in the charts we saw a still query time:
![image](https://user-images.githubusercontent.com/7656049/76895407-2e114e00-68a5-11ea-9a88-42dbb2d4d607.png)
Seems like every time it can resolve the query, it updates the value but when it can't, it keeps the old value

##### OS / Environment

```
Linux netdata-plugins.tool.x.y.z 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.3 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.3 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

 
netdata v1.19.0
##### Component Name

go.d

**Comment by ilyam8** [comment]
Hi 👋 

i dont see it caches the response, is there is 2 checks: 
 - response code
 - error

So if there is error or response code != success it doesnt add value to the result map

https://github.com/netdata/go.d.plugin/blob/6542eefdc8697a4c8fc1060e620d4ff13575c44d/modules/dnsquery/dnsquery.go#L177-L191

**Comment by ilyam8** [comment]
i tested it

```yaml
jobs:
 - name: example
   domains:
     - google.com
     - github.com
     - reddit.com
   servers:
     - 8.8.4.4
```

I created a rule to drop all packets to the dst 8.8.4.4 and enabled it during the debug


 - Disabled

```sh
[ilyam-pc plugins.d]# ./go.d.plugin -d -m dns_query
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 6
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] create.go:71 loading 'dns_query' configuration
[ INFO  ] main[main] orchestrator.go:126 start main loop
[ INFO  ] main[main] start.go:46 dns_query[example]: autodetection success
[ DEBUG ] main[main] orchestrator.go:141 tick 0
[ DEBUG ] dns_query[example] dnsquery.go:167 current domain : github.com
CHART 'netdata.execution_time_of_dns_query_example' '' 'Execution Time for dns_query_example' 'ms' 'go.d' 'netdata.go_plugin_execution_time' '' '145000' '5' '' 'go.d' 'dns_query'
DIMENSION 'time' '' '' '' '' ''

CHART 'dns_query_example.query_time' '' 'DNS Query Time' 'ms' 'query time' 'dns_query_time.query_time' '' '70000' '5' '' 'go.d' 'dns_query'
DIMENSION '8_8_4_4' '8.8.4.4' '' '' '1000000' ''

BEGIN dns_query_example.query_time
SET 8_8_4_4 = 26360846
END

BEGIN netdata.execution_time_of_dns_query_example
SET time = 26
END
```

 - Enbled

```sh
[ DEBUG ] main[main] orchestrator.go:141 tick 1
[ DEBUG ] main[main] orchestrator.go:141 tick 2
[ DEBUG ] main[main] orchestrator.go:141 tick 3
[ DEBUG ] main[main] orchestrator.go:141 tick 4
[ DEBUG ] main[main] orchestrator.go:141 tick 5
[ DEBUG ] dns_query[example] dnsquery.go:167 current domain : github.com
[ DEBUG ] main[main] orchestrator.go:141 tick 6
[ DEBUG ] dns_query[example] job.go:183 Skip the tick due to previous run hasn't been finished
[ DEBUG ] main[main] orchestrator.go:141 tick 7
[ DEBUG ] dns_query[example] job.go:183 Skip the tick due to previous run hasn't been finished
[ ERROR ] dns_query[example] dnsquery.go:186 error on querying 8.8.4.4 after A query for github.com : read udp 192.168.88.250:39129->8.8.4.4:53: i/o timeout
[ DEBUG ] main[main] orchestrator.go:141 tick 8
[ DEBUG ] main[main] orchestrator.go:141 tick 9
[ DEBUG ] main[main] orchestrator.go:141 tick 10
[ DEBUG ] dns_query[example] dnsquery.go:167 current domain : google.com
[ DEBUG ] main[main] orchestrator.go:141 tick 11
[ DEBUG ] dns_query[example] job.go:183 Skip the tick due to previous run hasn't been finished
[ DEBUG ] main[main] orchestrator.go:141 tick 12
[ DEBUG ] dns_query[example] job.go:183 Skip the tick due to previous run hasn't been finished
[ ERROR ] dns_query[example] dnsquery.go:186 error on querying 8.8.4.4 after A query for google.com : read udp 192.168.88.250:57864->8.8.4.4:53: i/o timeout
[ DEBUG ] main[main] orchestrator.go:141 tick 13
[ DEBUG ] main[main] orchestrator.go:141 tick 14
[ DEBUG ] main[main] orchestrator.go:141 tick 15
```

 - Disabled again

```sh
[ DEBUG ] dns_query[example] dnsquery.go:167 current domain : reddit.com
BEGIN dns_query_example.query_time 5000042
SET 8_8_4_4 = 8557538
END

BEGIN netdata.execution_time_of_dns_query_example 5000042
SET time = 8
END
```

**Comment by ilyam8** [comment]
The chart should froze, dns_query module doesnt return any value in case of error.

**Comment by ilyam8** [comment]
We need to add availability alarm.

**Comment by yasharne** [comment]
I have this job:
```
- name: services
  domains:
    - services.y.z
  servers:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
```
and if I get answers from `8.8.8.8` and `9.9.9.9`, the chart won't freeze

**Comment by ilyam8** [comment]
Yes, but there is no new data for `1.1.1.1`

**Comment by yasharne** [comment]
Therefore it keeps the old one:
![image](https://user-images.githubusercontent.com/7656049/76899491-ea224700-68ac-11ea-94b5-4070aed7bc26.png)

**Comment by ilyam8** [comment]
<img width="1222" alt="Screenshot 2020-03-17 at 23 41 13" src="https://user-images.githubusercontent.com/22274335/76899539-cd841000-68a8-11ea-9c22-310d6aee7dc0.png">

**Comment by ilyam8** [comment]
It seems your blocking rule doesnt work for the module for some reason, check the debug mode

**Comment by yasharne** [comment]
I closed the `1.1.1.1` destination on the firewall again, and here is the output of `/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin -m dns_query | grep -i "1_1_1_1"` command:
```
[ ERROR ] dns_query[asanpardakht] dnsquery.go:186 error on querying 1.1.1.1 after A query for services.y.z : write udp 172.16.76.147:51594->1.1.1.1:53: write: operation not permitted
SET 1_1_1_1 = 
[ ERROR ] dns_query[asanpardakht] dnsquery.go:186 error on querying 1.1.1.1 after A query for services.y.z : write udp 172.16.76.147:40599->1.1.1.1:53: write: operation not permitted
SET 1_1_1_1 =
```
But I don't know why I still see it on the chart:
![image](https://user-images.githubusercontent.com/7656049/76901077-cc0a1600-68af-11ea-9460-7f23fcae96e8.png)

**Comment by ilyam8** [comment]
There is no value as you see. There is no magic, we are missing something.

What is your fw rule? `iptables -A OUTPUT --dst 1.1.1.1 -j DROP`?

**Comment by yasharne** [comment]
yes

**Comment by ilyam8** [comment]
🤷‍♂ if the request is originated by the server it should go through `OUTPUT` chain.

Is `error on querying` errors in the netdata error.log?

**Comment by ilyam8** [comment]
Probably conntrack? do you `ACCEPT` some RELATED, ESTABLISHED?

**Comment by yasharne** [comment]
I see errors on dns_query cannot resolve from `1.1.1.1` and I believe the plugin is working fine because I don't get any output when I run the plugin in the debug mode, but there may be some problem on the APIs repeating the previous number which causes still number (both on the netdata dashboard and Prometheus)

**Comment by ilyam8** [comment]
> both on the netdata dashboard and Prometheus

netdata dashboard shows the data returned by the module. So if it shows values then module returns the values. However i cant reproduce it atm.
