### ISSUE TITLE
kickstart.sh not displaying line breaks (\n) correctly.

### ISSUE THREAD

**Issue by NinoM4ster** [netdata/netdata#8422]
##### Bug report summary

Hello! While reinstalling Netdata on two Ubuntu systems with the Kickstart script, I noticed that in some parts, the script fails to display a line break properly, instead showing a literal `\n`:

![image](https://user-images.githubusercontent.com/8485761/76914706-e33e0900-6899-11ea-8c78-17b21541226d.png)

##### OS / Environment

```
Linux apollo 4.4.0-174-generic #204-Ubuntu SMP Wed Jan 29 06:41:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.6 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.6 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

 netdata v1.20.0

##### Component Name

`kickstart.sh` instalation script (https://my-netdata.io/kickstart.sh)
##### Steps To Reproduce

1. Execute the kickstart.sh file as instructed [here](https://github.com/netdata/netdata/tree/master/packaging/installer#automatic-one-line-installation-script) (in my case I supplied `--stable-channel --disable-telemetry` as arguments)
2. Follow the installation instructions and watch.

##### Expected behavior

You should see the line breaks working correctly.

**Comment by prologic** [comment]
Hi @NinoM4ster this was already fixed by was already fixed by #8326 #8325 and #8324 So if you remove the `--stable-channel` option you won't see this. That being said I've put up #8447 to improve this a bit more as well as #8446 that applies similar fixes for the uninstaller.

Thanks for reporting!
