### ISSUE TITLE
Add support for MaxScale 

### ISSUE THREAD

**Issue by abdulnewswav** [netdata/netdata#8423]
Hi,

I would like to suggest to add custom plugin to support Maxscale server
you can read more about MaxScale from here:
https://mariadb.com/kb/en/maxscale/
It's a smart database proxy and load balancer, which can redirect queries to different SQL DBs based on predefined rules, I look into internet and i just got few Prometheus exporters, so I think is possible to add a plugin and integrate metrics into Netdata ecosystem

**Comment by ilyam8** [comment]
Hi @abdulnewswav 

Does it expose some metrics? How to retrieve them?

I see that module does some monitoring itself

> https://mariadb.com/kb/en/maxscale-22-monitors/

**Comment by abdulnewswav** [comment]
@ilyam8 
Yes it does!
It has a rest api:
https://mariadb.com/kb/en/mariadb-maxscale-24-maxctrl/
It can show threads, services, servers ...
this one: https://mariadb.com/kb/en/mariadb-maxscale-24-maxctrl/#show-service can show how many connections connected to the service
So I think Maxscale server can export a good bunch of data

**Comment by ilyam8** [comment]
> It has a rest api

This is good.

> can show how many connections connected to the service

It would be nice to get some help from on this part. It is not easy to undertand what metrics we need, how to group them, how to represent them in a meaningful way on the Netdata dasbhoard.

This is the list of resources:

> https://mariadb.com/kb/en/9045/#resources

Could you go trhrough it and see what resources are important, what we need to monitor?

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
