### ISSUE TITLE
(Solved) Two similar systems, same version, different layout...?

### ISSUE THREAD

**Issue by NinoM4ster** [netdata/netdata#8424]
##### Bug report summary

Hello! I recently reinstalled Netdata on two similar Ubuntu systems, but they still look very different, including the browser icon (which was one of the reasons of the reinstall).

System 1:
![image](https://user-images.githubusercontent.com/8485761/76915656-d1119a00-689c-11ea-8e6d-2bb171d30b66.png)

System 2:
![image](https://user-images.githubusercontent.com/8485761/76915680-e4bd0080-689c-11ea-823b-15d92f9045ee.png)

##### OS / Environment

System 1:
```
Linux apollo 4.4.0-174-generic #204-Ubuntu SMP Wed Jan 29 06:41:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.6 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.6 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

System 2:
```
Linux Poseidon 4.4.0-176-generic #206-Ubuntu SMP Fri Feb 28 05:02:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.6 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.6 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```
##### Netdata version

Both systems were updated at the same time, so naturally they are both running the same version:

System 1:
![image](https://user-images.githubusercontent.com/8485761/76915782-40878980-689d-11ea-9d5e-710875a1f56b.png)

System 2:
![image](https://user-images.githubusercontent.com/8485761/76915811-52692c80-689d-11ea-878b-ef6d681d0a27.png)

##### Component Name

Web dashboard

##### Steps To Reproduce

I have no idea how this happened...

##### Expected behavior

System 1's Netdata should look like System 2's, specially after a complete reinstall (`netdata-uninstaller.sh`, then `kickstart.sh`).

**Comment by NinoM4ster** [comment]
Well, this is awkward...

After restarting the Netdata service (`sudo service netdata restart`) and refreshing the browser with Ctrl + F5 it's now looking like it should.

Maybe browser caching is to blame?

Either way, sorry for the useless bug report and thanks for this awesome tool.

-Nino

**Comment by thiagoftsm** [comment]
Hello @NinoM4ster ,

Considering your last comment,  I would say that cache was probably the problem, but case it persists, please, let us know.

Best regards!
