### ISSUE TITLE
Installer stop_all_netdata uv_pipe_connect() err

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8428]
#### Question summary

In Ubuntu 18.04 I get the following installer error:

```stop_all_netdata uv_pipe_connect() : no such file or directory```

I have my netdata running as user `chris`, but I don't know if it's related.
Do we know where it comes from?

**Comment by ilyam8** [comment]
code is

https://github.com/netdata/netdata/blob/16f835489c1a93b5dbd84747c52c883f43b716f0/cli/cli.c#L134-L160

**Comment by mfundul** [comment]
This is because the installer calls `netdatacli` which cannot find the netdata daemon, exactly because it hasn't been installed yet.

**Comment by cakrit** [comment]
> This is because the installer calls `netdatacli` which cannot find the netdata daemon, exactly because it hasn't been installed yet.

Actually I get the error even when it is already installed and netdata is running.

**Comment by mfundul** [comment]
I verified that the only way to get this message is if the agent is down, so it's possible the installer calls `netdatacli` multiple times.

**Comment by mfundul** [comment]
By looking at here:
https://github.com/netdata/netdata/blob/fd343ac0c262cd6a1535b67e7894d06760e10259/packaging/installer/functions.sh#L571

It is possible that systemd has stopped netdata already before `netdatacli` is called.

**Comment by Ferroin** [comment]
Relabeling this as a bug, there's a logic error there that appears to be causing this.

**Comment by prologic** [comment]
I'll fix this
