### ISSUE TITLE
 Health Management documentation URL

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8431]
##### Bug report summary
The documentation for `Health Management API` is not using Netdata default port  and it is breaking the pattern that was present in the previous sections of the document.

##### Netdata version
netdata v1.20.0-182-g02b38297 

##### Component Name
Documentation

##### Steps To Reproduct

1. Access the link https://docs.netdata.cloud/web/api/health/#further-reading 

##### Expected behavior
I will give two suggestion for this:

1 - Health Management API will keep the pattern present in the previous sections ( http://your.netdata.ip:19999/api/v1/ )
2 - Before to use `myserver` in the URLs, we will define that `myserver` is `your.netdata.ip:19999`.

Best regards!

**Comment by joelhans** [comment]
Fixed by #8837!
