### ISSUE TITLE
Disabled Alarms Turning Back On?

### ISSUE THREAD

**Issue by DirectRoot** [netdata/netdata#8435]
##### Question summary

When commenting out alarms in config files, or changing the `to:` field to `silent`, the alarm is reinstated with nightly updates.

Point 2. here states `If the file is there but is not the original shipped by netdata, the installer will not overwrite it.` https://github.com/netdata/netdata/issues/3153#issuecomment-352727888

And the docs mention changing the recipient to `silent` https://docs.netdata.cloud/docs/configuration-guide/#modify-alarms-and-notifications

What am I missing to be able to permanently disable an alarm?

##### OS / Environment

RHEL nodes streaming to an Ubuntu central, where I'm modifying the alarm config.

##### Expected results

The alarm should stay disabled, currently it is only silenced until the nightly update.

**Comment by ilyam8** [comment]
Hi, those are stock configs and they are being rewritten on every update.

You need to modify user configuration files

> https://docs.netdata.cloud/docs/configuration-guide/#configuration-guide

**Comment by ilyam8** [comment]
There is `edit-config` script in the `/opt/netdata/etc/netdata/` directory (if netdata is installed in `/opt/`). Use it to modify alarms.

**Comment by DirectRoot** [comment]
Ah right! I was jumping the gun and not using `edit-config` . Doing so has copied the modified config into `health.d` where I assume it will take priority of the stock config.

If you don't here from me tomorrow, this is solved. Thanks @ilyam8!

**Comment by ilyam8** [comment]
I am sure it is solved, but if it is just say 😄
