### ISSUE TITLE
charts.d.plugin not exiting while netdata service restart

### ISSUE THREAD

**Issue by patademahesh** [netdata/netdata#8448]
##### Bug report summary
We are trying to write a custom plugin for application log monitoring using charts.d collector but while netdata service restart "/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin" this process is not able to exit properly and starts throwing below error in logs. 

$ tail -f /opt/netdata/var/log/netdata/error.log| grep 'charts.d'
```
2020-03-20 09:56:23: netdata INFO  : PLUGINSD : stopping plugin thread: plugin:charts.d
2020-03-20 09:56:30: netdata ERROR : PLUGINSD[charts.d] : cat: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 647: echo: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 648: echo: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 649: echo: write error: Broken pipe
```

Here is my plugin:
$ /opt/netdata/netdata-plugins/charts.d/log_watch.chart.sh

```sh
# shellcheck shell=bash disable=SC2154,SC1072,SC1073,SC2009,SC2162,SC2006,SC2002,SC2086,SC1117
# no need for shebang - this file is loaded from charts.d.plugin
# SPDX-License-Identifier: GPL-3.0-or-later

# netdata
# real-time performance and health monitoring, done right!
# (C) 2016 Costa Tsaousis <costa@tsaousis.gr>
#

log_watch_update_every=10
log_watch_priority=6000

# this is an example charts.d collector
# it is disabled by default.
# there is no point to enable it, since netdata already
# collects this information using its internal plugins.
log_watch_enabled=0

log_watch_check() {
        # this should return:
        #  - 0 to enable the chart
        #  - 1 to disable the chart

        [ "x${log_watch_files}" == "x" ] && return 1
        return 0
}

log_watch_create() {
        # create a chart with 3 dimensions
        while read file; do
                log_watch_file_name=$(echo $file | cut -d':' -f1)
                log_watch_file=$(basename $log_watch_file_name | cut -d'.' -f1)
                cat <<EOF
CHART log_watch.$log_watch_file '' "Monitor application Log file" "#errors" $log_watch_file  log_watch line $(expr ${log_watch_priority} + 1) $log_watch_update_every
DIMENSION errors 'errors count' absolute 1 1
EOF

        done < <(echo $log_watch_files | tr ';' '\n')
        return 0
}

log_watch_update() {
        # do all the work to collect / calculate the values
        # for each dimension
        # remember: KEEP IT SIMPLE AND SHORT
        log_watch_netdata_cache="/opt/netdata/var/cache/netdata/log_watch/"
        mkdir -p "${log_watch_netdata_cache}"
        while read file; do
                log_watch_file_name=$(echo $file | cut -d':' -f1)
                log_watch_ignore=$(echo $file | cut -d':' -f2)
                log_watch_critical=$(echo $file | cut -d':' -f3)
                log_watch_file=$(basename $log_watch_file_name | cut -d'.' -f1)
                log_watch_state_file="${log_watch_netdata_cache}$log_watch_file.state"

                [ ! -e $log_watch_state_file ] && \
                echo "$log_watch_file_name|$(/bin/ls -i $log_watch_file_name | awk '{print $1}')|$(/usr/bin/wc -l $log_watch_file_name | awk '{print $1}')" > $log_watch_state_file

                log_watch_file_pos=$(expr `cat $log_watch_state_file | cut -d'|' -f3` + 1)
                log_watch_file_inode=$(cat $log_watch_state_file | cut -d'|' -f2)
                if [ $(cat $log_watch_state_file | cut -d'|' -f3) -le $(/usr/bin/wc -l $log_watch_file_name | awk '{print $1}') ] && \
                        [ $log_watch_file_inode -eq $(/bin/ls -i $log_watch_file_name | awk '{print $1}') ]; then
                        errors=$(/bin/sed -n ${log_watch_file_pos},\$p $log_watch_file_name | \
                                 grep -Ei "(${log_watch_critical})" | \
                                 grep -Ev "(${log_watch_ignore})" | /usr/bin/wc -l)
                else
                        errors=$(grep -Ei "(${log_watch_critical})" $log_watch_file_name | \
                                 grep -Ev "(${log_watch_ignore})" | /usr/bin/wc -l)
                fi
                        echo "$log_watch_file_name|$(/bin/ls -i $log_watch_file_name | awk '{print $1}')|$(/usr/bin/wc -l $log_watch_file_name | awk '{print $1}')" > $log_watch_state_file


        # write the result of the work.
        cat <<VALUESEOF
BEGIN log_watch.$log_watch_file
SET errors = ${errors:-0}
END
VALUESEOF
        done < <(echo $log_watch_files | tr ';' '\n')

        return 0
}
```

$ cat /opt/netdata/etc/netdata/charts.d/log_watch.conf
```
# no need for shebang - this file is loaded from charts.d.plugin

# netdata
# real-time performance and health monitoring, done right!
# (C) 2018 Costa Tsaousis <costa@tsaousis.gr>
# GPL v3+
# Format:- logfile:pipe-sep-ignore-patterns:pipe-sep-crit-patterns;logfile2:pipe-sep-ignore-patterns:pipe-sep-crit-patterns;..
log_watch_files='/var/log/sample1.log:my|by|not found error:error;/var/log/sample2.log::fatal'
```

##### OS / Environment
```
Linux www.example.com 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS release 6.5 (Final)
/etc/redhat-release:CentOS release 6.5 (Final)
/etc/system-release:CentOS release 6.5 (Final)
```

##### Netdata version
 ```
netdata v1.19.0
```

##### Component Name
```/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin```

##### Steps To Reproduce
1. Install plugin provided above
2. Create log files /var/log/sample1.log and /var/log/sample2.log
3. start netdata service
4. wait for sometime and restart netdata service
4. tail for log with filter 'charts.d'. its starts giving below error in error log
$ tail -f /opt/netdata/var/log/netdata/error.log| grep 'charts.d'
```
2020-03-20 09:56:23: netdata INFO  : PLUGINSD : stopping plugin thread: plugin:charts.d
2020-03-20 09:56:30: netdata ERROR : PLUGINSD[charts.d] : cat: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 647: echo: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 648: echo: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 649: echo: write error: Broken pipe
```

##### Expected behavior
successful charts.d.plugin exit and service restart.

**Comment by ilyam8** [comment]
Hi @patademahesh 

Have you considered to write it in python?

**Comment by patademahesh** [comment]
Yeah we can but it'll take time. Bash was easy for us. 

It's a simple script. We don't understand what is the problem. It works very well until we restart the daemon.

**Comment by ilyam8** [comment]
I seems Netdata doesnt send `SIGTERM` to `chart.d.plugin` and `charts.d.plugin` itself doesnt exit on `SIGPIPE`. 

There is no such problem for `python.d.plugin` and there is no such problem on not old distributions at all.

Could you show `$log_watch_file_name` content? I suspect it is very easy to write it in python.

**Comment by patademahesh** [comment]
`$log_watch_file_name` content is filepath from below var passed in .conf file.

log_watch_files='**/var/log/sample1.log**:my|by|not found error:error;**/var/log/sample2.log**::fatal'

**Comment by ilyam8** [comment]
> Create log files /var/log/sample1.log and /var/log/sample2.log

ok, i mean content of these files, what we need to parse

**Comment by patademahesh** [comment]
You can insert anything with string error. If it detects **error** word in the file the counter will be increased. Thats it.

Eg. echo "this is test error line" >> /var/log/sample1.log

**Comment by ilyam8** [comment]
Do we need to read from one log file? (one log file per job)

**Comment by ilyam8** [comment]
If one per job you could use

https://github.com/netdata/netdata/issues/3729#issuecomment-389719427

(modify it for your needs: chart desc, etc)

**Comment by patademahesh** [comment]
No we want it for multiple file and single job. 

Thank you so much for the link but will it keep track of lines read and read only changed lines ?

**Comment by ilyam8** [comment]
> Thank you so much for the link but will it keep track of lines read and read only changed lines ?

Yes, but it doesnt allow to read from several files. And i think you need adding new log files during runtime.

**Comment by ilyam8** [comment]
related discussion: #7420

**Comment by patademahesh** [comment]
The actual requirement is we want a plugin like [this](https://checkmk.com/cms_legacy_logfiles.html). In this we can add ignore and match patterns. 

The script plugin you shared will only match a line and increase the counter. we cant add ignore patterns in that.

**Comment by ilyam8** [comment]
Yes, that `check_mg` log thing is good. I dont know if it possible to make a generic log plugin that will work in all cases, there is still no decision in #7420 - we need more use cases to understand it.

That simple python script can be easily extended to provide `ignore and match patterns`. The only requirement is 1 log file per job, which seems doesnt work for you.

**Comment by ilyam8** [comment]
Probably the easiest way here is to fix `charts.d.plugin` 🤔

**Comment by patademahesh** [comment]
> Probably the easiest way here is to fix `charts.d.plugin`

yep. but what is the problem with it ? i still don't understand.

**Comment by patademahesh** [comment]
> Yes, that `check_mg` log thing is good. I dont know if it possible to make a generic log plugin that would work in all cases, there is still no decision in #7420 - we need more use cases to understand it.
> 
> That simple python script can be easily extended to provide `ignore and match patterns`. The only requirement is 1 log file per job, which seems doesnt work for you.

I think this should be the one use case. Please add it to your list.

**Comment by ilyam8** [comment]
> yep. but what is the problem with it ? i still don't understand.

I dont know, i think i need to test in in Centos6. I am downloading 6.10, but it is unlikely i will be able to test it soon.

@prologic @Ferroin any ideas?

**Comment by patademahesh** [comment]
Okey. Thank you for your help.

**Comment by patademahesh** [comment]
hi @ilyam8 did you get any chance to check this ?

**Comment by ilyam8** [comment]
No 😅  i marked the issue as unread and wll try to find some time to check in upcoming days.

**Comment by prologic** [comment]
@patademahesh My guess is that one of your sub-processes you spawn in your script is hanging on s pipe and you don't have any cleanup / signal signal handler in this script at all.

You should add one first of all to improve the situation: e.g:

```#1hs

cleanup() {
   # do clean up
}

trap cleanup EXIT
```

You should also write a `SIGINT` and `SIGTERM` handler as well:

```#!sh

handler() {
   # do stuff here
}

TRAP handler SIGINT SIGTERM
```

See [this blog post](https://www.linuxjournal.com/content/bash-trap-command) for good documentation and examples on how to do this.

I _believe_ this will really help a lot :)

**Comment by ilyam8** [comment]
@patademahesh can you test the fix #8529 ?

**Comment by patademahesh** [comment]
@ilyam8 sorry for the delayed response. Yes your fix worked like charm. 

It gave error once and exited after printf command.

```
2020-03-30 10:01:20: netdata ERROR : PLUGINSD[charts.d] : cat: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 654: echo: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 655: echo: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 656: echo: write error: Broken pipe
/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin: line 582: printf: write error: Broken pipe
```

I tried with trap in my script but it didn't work.

**Comment by patademahesh** [comment]
@ilyam8  Thanks a lot for your quick support and fix.

**Comment by ilyam8** [comment]
It wasnt quick at all, it is 10 days 😄

**Comment by prologic** [comment]
> It wasnt quick at all, it is 10 days 😄

You should see how long it takes to fix a simple bug in a Government IT/Tech org, University or deeply bureaucratic Corporation :)
