### ISSUE TITLE
Host tags not present in Prometheus export

### ISSUE THREAD

**Issue by marcomusso** [netdata/netdata#8449]
##### Question summary

(Related to #3364)

Hi, I'm using netdata v1.20.0-1 and I added in my conf file:

```
[host labels]
    application = epenv
    role = middleware
    service_level = development
    zone = ams3z1

[exporting:global]
    enabled = yes
    send configured labels = yes
    send automatic labels = no

[backend]
    host tags = application="epenv",role="middleware",service_level="development",zone="ams3z1"
```

But those tags are only present in the netdata_host_tags metric.
From the discussion in #3364 I was expecting those labels to appear on every metric exported from that host even if the last sentence is misleading: does that means that there was a decision to NOT add those labels to every metric?

##### OS / Environment

CentOS 7.4.1708
netdata-1.20.0-1 (installed rpm)

##### Component Name

backend / Host tags

##### Expected results

All metrics including the key/value pairs specified and not only these:

```
# curl -s "localhost:19999/api/v1/allmetrics?format=prometheus" | grep epenv
netdata_info{instance="XXXXXXXXXXX",application="netdata",version="v1.20.0"} 1 1584718104058
netdata_host_tags_info{application="epenv",role="middleware",service_level="development",zone="ams3z1"} 1 1584718104058
netdata_host_tags{application="epenv",role="middleware",service_level="development",zone="ams3z1"} 1 1584718104058
```

**Comment by vlvkobal** [comment]
Yes, host tags are added only once at host level.

There is a plan to implement labels on the metric level, but it's an epic project which involves a database redesign. Some discussions and links are in #6503, #7891.

**Comment by marcomusso** [comment]
Thanks for the quick answer, I'll subscribe to those issues.
