### ISSUE TITLE
syno ds216play install faills even when all reqs are there

### ISSUE THREAD

**Issue by gabsor** [netdata/netdata#8453]
Before I posted this, I've been testing all possibilities and read almost any doc on getting netdata alive..... But I'm stuck. Hope someone can help, highly appreciated. 

##### Question summary
Been trying to install netdata on synology ds216play.
It used to be present/part in the optware but running entware now and I cannot find a package / setup that is working. 

##### OS / Environment
3.10.105 #24922 SMP Tue Jul 9 18:27:16 CST 2019 armv7l GNU/Linux synology_monaco_ds216play.

##### Component Name
See below...

##### Expected results
I would expect install to be succesfull since all  pre-reqs are there, also updated PATH to all libs and reqs... But no s6. 
- zlib is installed
- autoconf installed
- automake installed
- libuuid installed
- libuv installed
- gcc installed
-------------------------------------------------------------------------------------

Script output: 
bash-4.3# cd /opt
bash-4.3# git clone https://github.com/firehol/netdata.git netdata --depth=1
bash-4.3# cd netdata
bash-4.3# ./netdata-installer.sh

  ^
  |.-.   .-.   .-.   .-.   .  netdata
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  You are about to build and install netdata to your system.

  It will be installed at these locations:

   - the daemon     at /usr/sbin/netdata
   - config files   in /etc/netdata
   - web files      in /usr/share/netdata
   - plugins        in /usr/libexec/netdata
   - cache files    in /var/cache/netdata
   - db files       in /var/lib/netdata
   - log files      in /var/log/netdata
   - pid file       at /var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata

  This installer allows you to change the installation path.
  Press Control-C and run the same command with --help for help.

  NOTE:
  Anonymous usage stats will be collected and sent to Google Analytics.
  To opt-out, pass --disable-telemetry option to the installer or export
  the enviornment variable DO_NOT_TRACK to a non-zero or non-empty value
  (e.g: export DO_NOT_TRACK=1).

**No autotools found**

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                    .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   autotools v2.60 required  '   '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

-------------------------------------------------------------------------------
autotools 2.60 or later is required

Sorry, you do not seem to have autotools 2.60 or later, which is
required to build from the git sources of netdata.

**bash-4.3# autoconf -V
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.**

Written by David J. MacKenzie and Akim Demaille.

----------------------
_Install via netdata site:_

 --- Run autotools to configure the build environment ---
[/tmp/netdata-kickstart-gqUiEW/netdata-v1.20.0-200-gc6c5686c]# ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/libexec --libdir=/usr/lib --with-zlib --with-math --with-user=netdata CFLAGS=-O2 LDFLAGS= checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) no
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/tmp/netdata-kickstart-gqUiEW/netdata-v1.20.0-200-gc6c5686c':
**configure: error: no acceptable C compiler found in $PATH**
See `config.log' for more details
 FAILED

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues

 FAILED

 ABORTED  netdata-installer.sh exited with error

**gcc is in path !!!
bash-4.3# gcc
gcc: fatal error: no input files
compilation terminated.**

**Also ran with --libs-are-really-here but no difference.

**Finally, ran the  configure in /tmp/netdata*****

bash-4.3# ./config./configure ZLIB_CFLAGS=" " ZLIB_LIBS="-lz" --with-libuuid="/opt/lib"^C
bash-4.3# ./configure ZLIB_CFLAGS=" " ZLIB_LIBS="-lz" --with-libuuid="/opt/lib"
configure: WARNING: unrecognized options: --with-libuuid
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for pkg-config... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking if cloud functionality should be enabled... no
checking for __attribute__((returns_nonnull))... yes
checking for __attribute__((malloc))... yes
checking for __attribute__((noreturn))... yes
checking for __attribute__((noinline))... yes
checking for __attribute__((format))... yes
checking for __attribute__((warn_unused_result))... yes
checking for struct timespec... yes
checking for clockid_t... yes
checking for library containing clock_gettime... none required
checking for clock_gettime... yes
checking for sched_setscheduler... yes
checking for sched_getscheduler... yes
checking for sched_getparam... yes
checking for sched_get_priority_min... yes
checking for sched_get_priority_max... yes
checking for getpriority... yes
checking for setpriority... yes
checking for nice... yes
checking for recvmmsg... yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for inline... inline
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... yes
checking for _Generic... yes
checking for __atomic... yes
checking size of void *... 4
checking whether sys/types.h defines makedev... yes
checking for sys/types.h... (cached) yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking for sys/prctl.h... yes
checking for sys/vfs.h... yes
checking for sys/statfs.h... yes
checking for sys/statvfs.h... yes
checking for sys/mount.h... yes
checking for accept4... yes
checking operating system... linux with id 1
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for sin in -lm... yes
checking if libm should be used... yes
checking for uv_fs_scandir_next in -luv... yes
checking for LZ4_compress_default in -llz4... no
checking for JudyLIns in -lJudy... no
checking for ZLIB... yes
checking if zlib should be used... yes
checking for UUID... no
**configure: error: libuuid required but not found. Try installing 'uuid-dev' or 'libuuid-devel'.**

I'm stuck......

**Comment by mfundul** [comment]
It looks to me you may be missing `pkg-config` or `pkgconfig` or `pkgconf` or whatever its name may be in your platform.

**Comment by mfundul** [comment]
You could always try installing a static binary instead of compiling as well, maybe something like [this](https://docs.netdata.cloud/packaging/installer/methods/kickstart-64/)?.

**Comment by mfundul** [comment]
There is also synology documentation [here](https://docs.netdata.cloud/packaging/installer/methods/synology/).

**Comment by gabsor** [comment]
Tx for your reply. The[ synology documentation](https://docs.netdata.cloud/packaging/installer/methods/synology/) is only covering the amd64 architecture.

**Comment by gabsor** [comment]
> pkg-config

pkg-config is there, alive and kicking

**Comment by gabsor** [comment]
> You could always try installing a static binary instead of compiling as well, maybe something like [this](https://docs.netdata.cloud/packaging/installer/methods/kickstart-64/)?.

Also for Intel/AMD 64bit Linux systems only

**Comment by Ferroin** [comment]
@gabsor Can you post the output of `pkg-config --modversion uuid`? That will at least tell us if `pkg-config` can find libuuid properly or not.

**Comment by mfundul** [comment]
> 
> 
> @gabsor Can you post the output of `pkg-config --modversion uuid`? That will at least tell us if `pkg-config` can find libuuid properly or not.

More importantly  this! `checking for gcc... no`

**Comment by Ferroin** [comment]
The OP had said in the description that they managed to work around that though. Inability to find `gcc` wouldn't suggest to me that `pkg-config` is broken though, that's a broken filesystem layout.

**Comment by bolemo** [comment]
Still valid on Synology DiskStation ds414j

Can only install older version from Entware. Can not build it (same issues as described here)

```
root@Mnemosyne:~# uname -a
Linux Mnemosyne 3.2.40 #25426 SMP Wed Jul 8 03:10:10 CST 2020 armv7l GNU/Linux synology_comcerto2k_ds414j
```
