### ISSUE TITLE
memory mode save, not keeping appropriate history 86400

### ISSUE THREAD

**Issue by kdy1968** [netdata/netdata#8457]
##### Bug report summary
i'm attempting to netdata in memory, the global section of netdata.conf looks like this:
[global]
	# process scheduling policy = keep
	# OOM score = keep
	# glibc malloc arena max for plugins = 1
	# glibc malloc arena max for netdata = 1
	# hostname = pluto
	  history = 86400
	# update every = 1
	# config directory = /etc/netdata
	# stock config directory = /usr/lib/netdata/conf.d
	# log directory = /var/log/netdata
	# web files directory = /usr/share/netdata/web
	# cache directory = /var/cache/netdata
	# lib directory = /var/lib/netdata
	# home directory = /var/cache/netdata
	# plugins directory = "/usr/libexec/netdata/plugins.d" "/etc/netdata/custom-plugins.d"
	  memory mode = save
	# page cache size = 32
	# dbengine disk space = 256
	# host access prefix = 
	# memory deduplication (ksm) = yes
	# TZ environment variable = :/etc/localtime
	# timezone = America/New_York
	# debug flags = 0x0000000000000000
	# debug log = /var/log/netdata/debug.log
	# error log = /var/log/netdata/error.log
	# access log = /var/log/netdata/access.log
	# facility log = daemon
	# errors flood protection period = 1200
	# errors to trigger flood protection = 200
	# run as user = netdata
	# pthread stack size = 8388608
	# cleanup obsolete charts after seconds = 3600
	# gap when lost iterations above = 1
	# cleanup orphan hosts after seconds = 3600
	# delete obsolete charts files = yes
	# delete orphan hosts files = yes
	# enable zero metrics = no

i have this set across 3 machines none of them collect 24 hours(86400) worth of data

##### OS / Environment
fx6300 processor, 16 gigabyte ram
```
Linux pluto 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic

```

##### Netdata version

netdata v1.20.0-205-nightly

 

##### Component Name

unknown

##### Steps To Reproduce

by setting memory mode to save, and select history to history = 86400
see above global config.

##### Expected behavior
 expected expected it to maintain 24hours worth of chart data

**Comment by mfundul** [comment]
This global configuration may be overridden per chart, per plugin or for streaming by separate configuration options (e.g. [streaming](https://docs.netdata.cloud/streaming/#configuration)). What is your use case?

**Comment by kdy1968** [comment]
I'm using the stock config,  not stream, only changes made were in the global config...

**Comment by mfundul** [comment]
How many hours of chart data do you see in your case?

**Comment by mfundul** [comment]
It's possible that your configuration file is not formatted correctly, is it missing tab characters? Can you share your `var/log/netdata/error.log` file?

**Comment by kdy1968** [comment]
I believe it was related to the config files, i recreated the netdata config files and it is work as expected now, closing
