### ISSUE TITLE
Trying to understand the netdata-installer.sh

### ISSUE THREAD

**Issue by Danissss** [netdata/netdata#8466]
Hi, I am trying to understand how netdata compiled/built; so I took look at `netdata-installer.sh` and the standard output of the script, which have a lot of information.

I saw netdata would build each of its components (e.g. `collector`, `web/*`, etc.). Does the `daemon` start all the process such as `web/server` (based on what I saw from `deamon/config/common.h)`? 

Thank you!

**Comment by mfundul** [comment]
Indeed it does!

**Comment by Danissss** [comment]
That's really cool ;)

**Comment by Danissss** [comment]
Sorry, more questions about `deamon`.

`deamon` handles the process of data collecting (i.e. using `collectors`) and data transmitting (i.e. send the data to `web/server`).

I was reading `deamon` [config](https://github.com/netdata/netdata/tree/master/daemon/config), and how to customize dashboard [here](https://docs.netdata.cloud/web/gui/custom/).

```html
<div data-netdata="stiebeleltron_system.hotwater.hotwatertemp"
 data-title="Hot Water Temperature"
 data-decimal-digits="1"
 data-chart-library="easypiechart"
 data-colors="#FE3912"
 data-width="55%"
 data-height="50%"
 data-points="1200"
 data-after="-1200"
 data-dimensions="actual"
 data-units="°C"
 data-easypiechart-max-value="50"
 data-easypiechart-min-value="40"
 data-common-max="netdata-hotwater-max"
 data-common-min="netdata-hotwater-min"
></div>
```

May I ask how `data-netdata=""` grab the data? I assume the collector process will send data to server within certain frequency? through ajax? 

Thanks!

**Comment by jacekkolasa** [comment]
@Danissss Yes :) dashboard.js looks for DOM elements with `data-netdata=` and builds charts on top of this, it then polls the server with frequency based on e.g. attributes, metadata, through ajax
