### ISSUE TITLE
RabbitMQ: report status per queue

### ISSUE THREAD

**Issue by marcomusso** [netdata/netdata#8473]
##### Feature idea summary

The good implementation of rabbitmq monitoring in #1813 and #6686 is working fine but I don't see the number of queued messages per queue (either as a new metric or as a dimension/family). According to my exported metrics for Prometheus and the comments on those issues I don't think this is supported.

##### Expected behavior

Begin able to have metrics (also exported) of deliver/publish and number of messages per queue.

**Comment by ilyam8** [comment]
Hi

What endpoint provides messages per queue metrics

**Comment by marcomusso** [comment]
No idea right now, I have to check. What I know for sure is that the collectd plugin provides that in our graphite backend. I'll report here as soon as I have time to do some tests.

**Comment by marcomusso** [comment]
`curl -s localhost:15672/api/queues | jq '.[].name'` returns all names and it seems that in the payload there are all the needed information (tons of it, per queue). This was already exposed here: https://github.com/netdata/netdata/issues/1813#issuecomment-280790056

I think the most interesting is `messages_unacknowledged` but if an effort is made it's probably worth returning everything. Since the payload is json it was strange not to see those values already in the Prometheus export that includes already a lot of stuff but I couldn't find the queues details (to put some alerts on).

**Comment by ilyam8** [comment]
I guess it is expensive call. @Wing924 do you know?

**Comment by Wing924** [comment]
If we query it every seconds, it's expensive call if your cluster have many queues.

**Comment by marcomusso** [comment]
But the interval can be set right? The management UI defaults to 5s, with a sensible default I think it can be implemented, I'm planning for example to poll every 30s or 1m...

**Comment by ilyam8** [comment]
Yes, you can change `update_every` but if i remember it right there is no way to have different `update_every` for the different jobs charts. It is global per job.

**Comment by ilyam8** [comment]
@marcomusso 

please share 

> curl -s localhost:15672/api/queues

output

**Comment by marcomusso** [comment]
Thanks for specifing the update_every limitation, it's ok for me to check all rabbitmq aspects at the same frequency.

Attached responses for two different systems: the bigger one is from an Elasticsearch implementation that is effortlessly indexing at 40k docs/s and the call is quite fast (time reports: 0.01s user 0.01s system 41% cpu 0.045 total). 

[api_queues.zip](https://github.com/netdata/netdata/files/4386291/api_queues.zip)

**Comment by marcomusso** [comment]
Of course I'm available if you need to test some code...

**Comment by ilyam8** [comment]
@marcomusso 

these is queue stats

```json
  {
    "message_stats": {
      "disk_reads": 19234,
      "disk_reads_details": {
        "rate": 0
      },
      "disk_writes": 7670981555,
      "disk_writes_details": {
        "rate": 821.2
      },
      "deliver": 7670982145,
      "deliver_details": {
        "rate": 652.6
      },
      "deliver_no_ack": 0,
      "deliver_no_ack_details": {
        "rate": 0
      },
      "get": 0,
      "get_details": {
        "rate": 0
      },
      "get_no_ack": 0,
      "get_no_ack_details": {
        "rate": 0
      },
      "publish": 7670981122,
      "publish_details": {
        "rate": 165.8
      },
      "publish_in": 0,
      "publish_in_details": {
        "rate": 0
      },
      "publish_out": 0,
      "publish_out_details": {
        "rate": 0
      },
      "ack": 7670981522,
      "ack_details": {
        "rate": 656.2
      },
      "deliver_get": 7670982145,
      "deliver_get_details": {
        "rate": 652.6
      },
      "confirm": 0,
      "confirm_details": {
        "rate": 0
      },
      "return_unroutable": 0,
      "return_unroutable_details": {
        "rate": 0
      },
      "redeliver": 623,
      "redeliver_details": {
        "rate": 0
      }
    },
    "reductions": 4166578369487,
    "reductions_details": {
      "rate": 457539.6
    },
    "messages": 5,
    "messages_details": {
      "rate": -6.8
    },
    "messages_ready": 0,
    "messages_ready_details": {
      "rate": 0
    },
    "messages_unacknowledged": 5,
    "messages_unacknowledged_details": {
      "rate": -6.8
    },
    "policy": null,
    "exclusive_consumer_tag": null,
    "consumers": 6,
    "consumer_utilisation": 1,
    "memory": 1117520,
    "recoverable_slaves": null,
    "state": "running",
    "garbage_collection": {
      "min_bin_vheap_size": 46422,
      "min_heap_size": 233,
      "fullsweep_after": 65535,
      "minor_gcs": 28
    },
    "messages_ram": 5,
    "messages_ready_ram": 0,
    "messages_unacknowledged_ram": 5,
    "messages_persistent": 5,
    "message_bytes": 4297,
    "message_bytes_ready": 0,
    "message_bytes_unacknowledged": 4297,
    "message_bytes_ram": 4297,
    "message_bytes_persistent": 4297,
    "head_message_timestamp": null,
    "disk_reads": 19234,
    "disk_writes": 7670981555,
    "backing_queue_status": {
      "mode": "lazy",
      "q1": 0,
      "q2": 0,
      "delta": [
        "delta",
        "undefined",
        0,
        "undefined"
      ],
      "q3": 0,
      "q4": 0,
      "len": 0,
      "target_ram_count": "infinity",
      "next_seq_id": 7670981555,
      "avg_ingress_rate": 403.7374400916994,
      "avg_egress_rate": 403.7374400916994,
      "avg_ack_ingress_rate": 403.7374400916994,
      "avg_ack_egress_rate": 408.9422802696501
    },
    "node": "rabbit@rabbitmq-ams2z3-bluelagoon.lhi.tt3.com",
    "arguments": {
      "x-queue-mode": "lazy"
    },
    "exclusive": false,
    "auto_delete": false,
    "durable": true,
    "vhost": "/",
    "name": "umi"
  }
```


What metrics do we need to collect?

And how to represent it? A separate section per queue? Or set of charts and every queue is a dimension?

**Comment by marcomusso** [comment]
Good question, I can give you an idea... but it's not  at all a complete breakdown.
I have to base by "needs" as the data I get out of collectd/graphite which is not ideal of course.

I have two sets of data: one generic overview (which is similar to what we have now in netdata) and a detailed view per virtualhost: in this case for every queue I get all this metrics:

```
ack
confirm
deliver
deliver_get
deliver_noack
get
get_noack
messages
messages_ready
messages_unacknowledged
publish
publish_in
publish_out
redeliver
return
```

which could be the dimension of a queue. The pluging I provides also avg, avg_rate,rate, sample sub-details for each but those are functions of the data that can be computed so no problem here. When rate is specified (ex. `publish_in_details.rate`) I would of course keep it asdding `_rate` to the (new) metric name.

I don't know the constriant that you have in terms of naming conventions for netdata exposed metrics ( and then it;s export to Prometheus) but I can guess a name that includes the virtual host name (default `/` and rendered as `slash`) followed by `queues` then `<name of the queue>` with the dimension, for example, `messages_ready_ram` (and of course every othrer dimension like `messages_persistent `, `messages_unacknowledged_ram `...).

**Comment by ilyam8** [comment]
Currently we have following section:
 - overview
 - vhost <VHOST_NAME>

There is 2 options:

- `queues` section and a separate chart for every metrics (ack, confirm, ...) with queue name as dim name
- `queue <VHOST_NAME_QUEUE_NAME>` section for every queue

**Comment by marcomusso** [comment]
I do like the queue name as a dimension, it's easy to filter/exclude them. Can't think of any drawbacks for that unless it breaks some naming convention I don't know of.

**Comment by ilyam8** [comment]
Fixed in https://github.com/netdata/netdata/pull/10064
