### ISSUE TITLE
History config option removed or just broken?

### ISSUE THREAD

**Issue by Kramerican** [netdata/netdata#8479]
I have always had in my config:

```
cat > /opt/netdata/etc/netdata/netdata.conf << EOF
[global]
 history = 86400
 enable zero metrics = yes
EOF

```
But history is not being maintained for 24hours as I want it across my servers. It is quite random how much history I can view across servers. I could not find anything but passing references in the docs to this directive - has this config changed?

**Comment by mfundul** [comment]
Default `memory mode` changed from `save` to `dbengine`. You can refresh you `netdata.conf` by running something like `wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf`.

**Comment by Ferroin** [comment]
Expanding a bit on what @mfundul said:

The new dbengine memory mode doesn't retain metrics based on time, but instead uses disk-usage limits to decide when to drop data. The default limit is 256MB, which actually isn't much for most systems (though it should give more than the default retention period of one hour provided by the old storage backends). More details can be found at https://docs.netdata.cloud/database/engine/

Based on some reasonably simple math, every 4kB page of space allocated translates to 1024 samples, for one metric, or approximately 17.067 minutes with the default 1 second sampling rate. This translates to 85 pages, or roughly 3.03413MB of space, per metric if you want a retention period of 24 hours.

**Comment by mfundul** [comment]
This disk space limit also depends on compression rates of the metric data. It's typical to have at least 70% space savings due to compression with dbengine.

**Comment by Ferroin** [comment]
Ah, yes, I forgot about the compression. The numbers above give a decent worst-case estimate though.

**Comment by Kramerican** [comment]
Alright thanks a lot for the answers - I'll test it out :)
