### ISSUE TITLE
Claiming improvements

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8486]
-[ ] The [command-line parameters](https://github.com/netdata/netdata/tree/master/claim#netdata-agent-command-line) should be the suggested way to do claiming in docker. Add the info to claim/README.md.

@rduffield and @manos-saratsis we need a decision on the following. Both will work, the second is just a bit more awkward.
- [ ]  Option 1: At the end of the claiming script, and based on a command line param, we try to run the command  `netdatacli reload-claiming-state`. By default it is executed, if netdata calls it with a certain param, it is not executed.
  - If it fails, we just say that "the netdata agent will be connected to the cloud when it is started again", or something to that effect.
  - If it succeeds, we say "the netdata agent is connecting to the cloud". It would be awesome if in the future the reload-claiming-state actually waited for the establishment of the ACLK and returned any errors, so that the script could inform the user, but that can wait.
- [ ] Option 2: We modify the command we show on the cloud UI and add `;netdatacli reload-claiming-state` to the end of it (making an even longer command).

**Comment by manos-saratsis** [comment]
@cakrit option1 is great
