### ISSUE TITLE
$PATH not set correctly for Linux installs

### ISSUE THREAD

**Issue by skanadian** [netdata/netdata#8488]
I've created my own netdata installer by using build-x86_64-static.sh

When using the installer outside of a normal shell (ie. called from cron via config management) the $PATH is not defined correctly.

This causes problems with "packaging/installer/functions.sh" where anything calling "if command" won't work. (ie. adding users/groups, systemd scripts, etc).  As a result, netdata runs as root and the systemd scripts aren't installed at all.

For example this codeblock;

`# Linux`
`if command -v groupadd 1> /dev/null 2>&1; then`
`  run groupadd -r "${groupname}" && return 0`
`fi`

It seems to work correctly on CentOS6, but CentOS7 does not work.

As a temporary fix I added this to the top of "packaging/makeself/install-or-update.sh" which resolves the issue.

PATH="${PATH}:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

It's probably not a proper fix in some environments but works fine in CentOS7.

To reproduce:
Run centos7.
Build installer.
Cron installer.  (/bin/sh /root/netdata-VERSION.gz.run --accept)
Check if netdata user/group/systemd scripts exist.

**Comment by prologic** [comment]
@skanadian Our apologies for the delay on responding, somehow this issue slipped my radar :/

Before I dig into this, could you help me understand why you are trying to install Netdata from whtini a Cron job? Also we _could_ / _probably_ should set our own `$PATH` I guess, at least from a security standpoint we reduce the risk of running a different binary we weren't expecting by `PATH` injection.

**Comment by skanadian** [comment]
@prologic 

My CMS (config management system) runs from cron.

The CMS has instructions for the server to "/bin/sh /path/to/netdata.gz.run --accept"

I could push the $PATH definition upstream to cron or the CMS, but considered other cases where a user may want to install netdata outside of a normal shell environment. (a CMS of their own, linux kickstart, etc).

I'm not sure how portable "command -v" is across other distributions without a $PATH defined, or what else inside the netdata installer might break as a result of no $PATH.

**Comment by prologic** [comment]
Even on my iMac `./daemon/system-info.sh` reports:

```
NETDATA_SYSTEM_VIRTUALIZATION=unknown
NETDATA_SYSTEM_VIRT_DETECTION=none
```

have we never really ever differentiated between virtual/container and bare-metal before? 🤔

**Comment by prologic** [comment]
@skanadian Sorry for the delay once again. I've added this to our immediate. backlog (_we try to fix bugs first_) and we'll add the extra paths. The scripts currently assume they are running as "root" which typically has these paths setup already in the `$PATH` environment, so you are right. Bare with us :) Meanwhile if you'd like to put up a PR I'd be more than happy to review it!

**Comment by Ferroin** [comment]
Actually, I _think_ this breaks things on Gentoo as well if run as a non-root user (Gentoo does not include any `*/sbin` paths in the default non-root `$PATH`).

There's more here than just adding paths though. The sample code block given in the original post will actually break for non-root installs if we add these paths, or possibly do very wrong things if it doesn't just stop working.

**Comment by prologic** [comment]
How does adding a few extra search paths, specifically paths for binaries typically found in `/sbin/` and `/usr/sbin` break things exactly? The only possibility is a binary name collision between `bin` and `sbin` paths which the shell would use the search paths as defined right? So I'm a bit lost here :) Not sure how this would hurt non-root user from installing Netdata.

**Comment by Ferroin** [comment]
> How does adding a few extra search paths, specifically paths for binaries typically found in `/sbin/` and `/usr/sbin` break things exactly? The only possibility is a binary name collision between `bin` and `sbin` paths which the shell would use the search paths as defined right? So I'm a bit lost here :) Not sure how this would hurt non-root user from installing Netdata.

We're calling out to tools in a number of places that must be run as root without properly checking for `EUID=0`. I don't know that it will make things stop working, but it will make the script throw a lot of errors when run as a non-root user.

**Comment by prologic** [comment]
Unless we have __very__ good strong reasons to support running our installer(s) as non-root I would just make this consistent and not have to worry about this so much.

**Comment by Ferroin** [comment]
> Unless we have **very** good strong reasons to support running our installer(s) as non-root I would just make this consistent and not have to worry about this so much.

They currently work correctly when run as a non-root user provided you specify an install prefix that you can write to (it sets things up to run as the current user, so you lose out on stuff that needs `EUID=0`, but otherwise works fine). I'm hesitant to break this, especially since it should be possible to handle this properly without breaking anything.

**Comment by prologic** [comment]
> so you lose out on stuff that needs EUID=0, but otherwise works fine). I'm hesitant to break this, especially since it should be possible to handle this properly without breaking anything.

I _actually_ wonder how much of the Netdata agent's functionality is useable at this point. Do you have an enumerated list of what no longer becomes functional?

Just trying to understand the problem fully :)

**Comment by Ferroin** [comment]
> I _actually_ wonder how much of the Netdata agent's functionality is useable at this point. Do you have an enumerated list of what no longer becomes functional?
> 
> Just trying to understand the problem fully :)

Anything that's SUID root in `/usr/libexec/netdata/plugins.d` stops working, because you can't make it SUID root if you're not root yourself (for obvious security reasons). As of right now on Linux, this consists of:

* slabinfo.plugin
* perf.plugin
* eBPF.process.plugin
* ioping.plugin
* apps.plugin (may still work on some system swiht lax security settings)
* Mapping of networking cgroup names.

These can all be made to work by ensuring somehow that Netdata has appropriate capabilities though.

**Comment by Ferroin** [comment]
This should hopefully be handled as part of the work on overhauling the installer/updater code.
