### ISSUE TITLE
Incorrect lstrip() truncates module names

### ISSUE THREAD

**Issue by tycho** [netdata/netdata#8490]
Commit 198b735f30d1bdbbb8ca87dc1f0b25f9091bfe3b is incorrectly implemented. It uses `self.module_name = self.__module__.lstrip('pythond_')` which assumes that `lstrip` takes an exact string argument, whereas it's really taking a set of characters to strip from the beginning:

https://docs.python.org/3/library/stdtypes.html#str.lstrip

So with that commit, a module named internally as something like `pythond_nvidia_smi` becomes `vidia_smi` after the string `pythond_n` is stripped from the front.

**Comment by ilyam8** [comment]
> pythond_nvidia_smi becomes vidia_smi

linus-vs-nvidia.jpg 😄 

___


Thx for reporting @tycho
