### ISSUE TITLE
Tun virtual network interfaces not recognized after last upgrade

### ISSUE THREAD

**Issue by djrm05** [netdata/netdata#8495]
Hi,

I upgraded Netdata yesterday and after that the Tun network interfaces (openvpn) are not appearing in the dashboard. I've just upgraded to v1.20.0-243-ga75dce49 and it still the same. So everything else seems to be there except the tun interfaces (in my case 2)

This netdata is running in an Ubuntu 18.04 desktop machine.

**Comment by vlvkobal** [comment]
Please show all `[plugin:proc:/proc/net/dev...]` sections from your configuration `http://localhost:19999/netdata.conf`.

**Comment by djrm05** [comment]
Please see below. Im able to see only bond0, eno1 and enp2s0 and tun0/tun1 are not...

`[plugin:proc:/proc/net/dev]
	# filename to monitor = /proc/net/dev
	# path to get virtual interfaces = /sys/devices/virtual/net/%s
	# path to get net device speed = /sys/class/net/%s/speed
	# path to get net device duplex = /sys/class/net/%s/duplex
	# path to get net device operstate = /sys/class/net/%s/operstate
	# enable new interfaces detected at runtime = auto
	# bandwidth for all interfaces = auto
	# packets for all interfaces = auto
	# errors for all interfaces = auto
	# drops for all interfaces = auto
	# fifo for all interfaces = auto
	# compressed packets for all interfaces = auto
	# frames, collisions, carrier counters for all interfaces = auto
	# disable by default interfaces matching = lo fireqos* *-ifb
	# refresh interface speed every seconds = 10
	# refresh interface duplex every seconds = 10
	# refresh interface operstate every seconds = 10

[plugin:proc:/proc/net/dev:enp2s0]
	# enabled = yes
	# virtual = no
	# bandwidth = auto
	# packets = auto
	# errors = auto
	# drops = auto
	# fifo = auto
	# compressed = auto
	# events = auto

[plugin:proc:/proc/net/dev:tun0]
	# enabled = yes
	# virtual = yes
	# bandwidth = auto
	# packets = auto
	# errors = auto
	# drops = auto
	# fifo = auto
	# compressed = auto
	# events = auto

[plugin:proc:/proc/net/dev:lo]
	# enabled = no
	# virtual = yes`

**Comment by vlvkobal** [comment]
Try setting `enable zero metrics = yes` in the `[global]` section and restart Netdata.

**Comment by djrm05** [comment]
This fixed it! May I know why this was not an issue in previous versions?

Thanks by the way!! :)

**Comment by ilyam8** [comment]
This `enable zero metrics = no` (default is `no`) option always causes confusions

**Comment by djrm05** [comment]
well, this option was not included in my conf file.. I was looking in the commented lines in the global section and was not there, so I had to added it. This is why I ask why this was not an issue for previous versions where the TUN adapters were working .

**Comment by vlvkobal** [comment]
I think it's a coincidence. Charts with zero metrics were disabled by default quite a long time ago (a few years ago). The `enable zero metrics` zero option to enable them was introduced only a few months ago.

**Comment by djrm05** [comment]
thanks @vlvkobal  for your help here :) 👍
