### ISSUE TITLE
Collectors not installed using Homebrew on macOS

### ISSUE THREAD

**Issue by snorkrat** [netdata/netdata#8510]
##### OS / Environment: 
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

```

```

##### Component Name
Collectors

First off, sorry for my complete lack of knowledge around this.  I just found out about netdata a few days ago and have been playing around with it.

I installed via Homebrew on macOS and I don't think all the collectors were installed by default?

Looking at the netdata.conf I can see that the config and stock config dir are as follows:
config directory = /usr/local/etc/netdata
stock config directory = /usr/local/Cellar/netdata/1.20.0/lib/netdata/conf.d

In the config directory I see 
<img width="276" alt="Screenshot 2020-03-27 at 11 35 41" src="https://user-images.githubusercontent.com/29180003/77752250-1e210900-701f-11ea-85bd-888ff7051f93.png">

In the stock config dir I see the following:
<img width="198" alt="Screenshot 2020-03-27 at 11 36 28" src="https://user-images.githubusercontent.com/29180003/77752302-36912380-701f-11ea-8f72-fc2bb388bcc9.png">

All of the folders here are empty... So would I be correct in saying that for example the go.d collector/plugins are all missing? I was trying to add some more metrics like nginx stats, free disk space etc which use the go.d collector I believe.  This is when I noticed that the folder was empty.

Apologies again for my lack of understanding! Still learning this.

**Comment by ilyam8** [comment]
I confirm that `go.d.plugin` is not installed, i installed netdata using `brew`, 

```cmd
46 ilyam:~ $ ls -l /usr/local/Cellar/netdata/1.20.0/lib/netdata/conf.d/
total 104
drwxr-xr-x  9 ilyam staff   288 Feb 21 04:52 charts.d
drwxr-xr-x 79 ilyam staff  2528 Feb 21 04:52 health.d
drwxr-xr-x 70 ilyam staff  2240 Feb 21 04:52 python.d
drwxr-xr-x  3 ilyam staff    96 Feb 21 04:52 statsd.d
-r--r--r--  1 ilyam staff 10273 Feb 21 04:52 apps_groups.conf
-r--r--r--  1 ilyam staff   190 Feb 21 04:52 aws_kinesis.conf
-r--r--r--  1 ilyam staff  1533 Feb 21 04:52 charts.d.conf
-r--r--r--  1 ilyam staff    26 Feb 21 04:52 ebpf_process.conf
-r--r--r--  1 ilyam staff  1233 Mar 30 10:29 fping.conf
-r--r--r--  1 ilyam staff 42442 Feb 21 04:52 health_alarm_notify.conf
-r--r--r--  1 ilyam staff    57 Feb 21 04:52 health_email_recipients.conf
-r--r--r--  1 ilyam staff  1010 Feb 21 04:52 ioping.conf
-r--r--r--  1 ilyam staff   148 Feb 21 04:52 mongodb.conf
-r--r--r--  1 ilyam staff  1310 Feb 21 04:52 node.d.conf
-r--r--r--  1 ilyam staff  1994 Feb 21 04:52 python.d.conf
-r--r--r--  1 ilyam staff  8873 Feb 21 04:52 stream.conf
```

```cmd
47 ilyam:~ $ ls -l /usr/local/Cellar/netdata/1.20.0/libexec/netdata/plugins.d/
total 308
-rwxr-xr-x 1 ilyam staff  4873 Feb 21 04:52 acl.sh
-rwxr-xr-x 1 ilyam staff   154 Feb 21 04:52 alarm-email.sh
-rwxr-xr-x 1 ilyam staff 79372 Mar 30 10:29 alarm-notify.sh
-rwxr-xr-x 1 ilyam staff   301 Feb 21 04:52 alarm-test.sh
-rwxr-xr-x 1 ilyam staff  2152 Mar 30 10:29 alarm.sh
-rwxr-xr-x 1 ilyam staff  3923 Mar 30 10:29 anonymous-statistics.sh
-rwxr-xr-x 1 ilyam staff  6957 Mar 30 10:29 cgroup-name.sh
-rwxr-xr-x 1 ilyam staff  8240 Feb 21 04:52 cgroup-network-helper.sh
-rwxr-xr-x 1 ilyam staff  1259 Feb 21 04:52 charts.d.dryrun-helper.sh
-rwxr-xr-x 1 ilyam staff 20138 Mar 30 10:29 charts.d.plugin
-rwxr-xr-x 1 ilyam staff 41200 Mar 30 10:29 cups.plugin
-rwxr-xr-x 1 ilyam staff  5554 Mar 30 10:29 fping.plugin
-rwxr-xr-x 1 ilyam staff   737 Feb 21 04:52 get-kubernetes-labels.sh
-rwxr-xr-x 1 ilyam staff  7328 Mar 30 10:29 health-cmdapi-test.sh
-rwxr-xr-x 1 ilyam staff  5424 Mar 30 10:29 ioping.plugin
-rwxr-xr-x 1 ilyam staff  6631 Mar 30 10:29 loopsleepms.sh.inc
-rwxr-xr-x 1 ilyam staff 11098 Mar 30 10:29 node.d.plugin
-rwxr-xr-x 1 ilyam staff 22930 Mar 30 10:29 python.d.plugin
-rwxr-xr-x 1 ilyam staff 11020 Feb 21 04:52 request.sh
-rwxr-xr-x 1 ilyam staff 17067 Feb 21 04:52 system-info.sh
-rwxr-xr-x 1 ilyam staff  7372 Mar 30 10:29 tc-qos-helper.sh
-rwxr-xr-x 1 ilyam staff  2912 Mar 30 10:29 template_dim.sh
```

**Comment by Ferroin** [comment]
Long term we're going to have to take over ownership of the Netdata Homebrew recipie.

Short term, for the go plugin specifically, we really should provide a way for users to download and 'install' just that, as there are a number of package managers that are outside of our control which do not include it.

**Comment by ilyam8** [comment]
i think main goal of having Netdata on macOS is to monitor local system, you dont need `go.d.plugin` (monitoring external apps) to be honest.

**Comment by Ferroin** [comment]
I can see some value in some of the collectors. There are some people out there who insist on using Mac systems as servers for some reason despite there being many far better supported alternatives.

**Comment by ilyam8** [comment]
Well, a person can always install netdata in  docker container which has everything inside.

Downloading and installing goplugin is basically wget+tar+mv.

Anyway nothing we can do since we are not mantaining homebrew recipie.

**Comment by prologic** [comment]
Let's use this issue as an excuse then to take over control/ownership of the Homebrew Formulae for NetData and pull them into our org. I would also invite said collaborates to continue to maintain them if they wish but they become `netdata/homebrew-netdata` (_I believe this is how it works if we choose to maintain them as taps_) otherwise we can maintain them as part of the official Formulae tree. Who wants to own this?

**Comment by Ferroin** [comment]
I think we should probably keep it in the official formula tree, as people are already using it from there. I can help with testing for this, but I am probably not the best person to maintain it due to my comparative lack of knowledge WRT macOS.

**Comment by prologic** [comment]
> I think we should probably keep it in the official formula tree, as people are already using it from there. I can help with testing for this, but I am probably not the best person to maintain it due to my comparative lack of knowledge WRT macOS.

Yeah it's okay I'll take this on.

**Comment by prologic** [comment]
On closer inspection and after cloning the Homebrew/homebrew-core repo loks like they do a pretty good job of keeping this up-to-date for us. I think we should leave things as is. And I agree with @ilyam8 's statements about collectors and macOS.

**Comment by prologic** [comment]
I am closing this as per @ilyam8 's comment. We feel that shiping the vast majority of collectors on macOS systems are out-of-scope at this point. If there are specific collector(s) you want available or you run macOS server(s) please feel free. to file a new more specific issue with the request. Thanks!

**Comment by pcm32** [comment]
This seems to be the case for linux as well, for reasons that go beyond the scope of this issue, we need to have netdata installed by an unprivileged user through homebrew in linux, and we want to make use of the solr and zookeeper Go based collectors. Would it be possible to at least have some documentation on how to install the go orchestrator plugin manually please? Thanks!
