### ISSUE TITLE
Alarm log redirect should not involve the cloud

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8514]
When clicking on a node's alarm log entry, I should be redirected directly to that chart and time, without redirecting to the cloud first, just as we do with active and configured (all) alarms. 

@thiagoftsm maybe there was some confusion as to how this is supposed to work, but redirects via the cloud are only required when I see a link to go to that alarm, in an alarm notification (email, slack etc).

**Comment by thiagoftsm** [comment]
I got @cakrit !
@jacekkolasa in this case we only need to change the default link used in the alarm log on dashboard to fix.

**Comment by jacekkolasa** [comment]
fixed in https://github.com/netdata/netdata/pull/9786
