### ISSUE TITLE
How to send mails using an SMTP server credentials?

### ISSUE THREAD

**Issue by shrinidhi111** [netdata/netdata#8515]
##### Question summary
I would like to know if there is a way to send alert emails using SMTP credentials from netdata?

##### What do I mean by that?
In python I use this simple code to send emails without setting up any SMTP server or installing  

```python
import os
from email import encoders
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
SMTP_SERVER = 'email-smtp.us-west-2.amazonaws.com'
SMTP_PORT = 587
SMTP_USERNAME = 'XXXXXXXX'
SMTP_PASSWORD = 'XXXXXXXXXXXXXXXXXXXXXXX'
SMTP_FROM = 'notification@domain.org'
SMTP_TO = 'user@example.com'
```
[ See https://realpython.com/python-send-email/ for more information ]

But I could not find any place where I can type in the SMTP credentials when I ran 
`sudo /etc/netdata/edit-config health_alarm_notify.conf`

**Comment by prologic** [comment]
hi @shrinidhi111 !

As it states here: https://github.com/netdata/netdata/blob/d5d1865469b63385d70645f710728482aed0f23d/health/notifications/health_alarm_notify.conf#L6-L7

NetData uses your system's `sendmail` (_standard UNIX tool used to send outgoing emails_).

You _should_ configure your system's `sendmail` or equivilent as appropriate depending on what you use.

This is well documented [here](https://github.com/netdata/netdata/blob/master/health/notifications/email/README.md)

Hope this helps! Let us know if you have any trouble. Personally I use msmtp myself a lot on servers where I don't care to have a full Postfix install.

**Comment by shrinidhi111** [comment]
Thanks for the clarification.. I do not prefer installing SMTP servers which is why I use the aforementioned python libraries to directly send emails on runtime..

This is actually very easy and I really hope that you would consider it as a feature in the future.

**Comment by prologic** [comment]
I recommend you look at writing a custom alarm_notify script then. Please see the docs on this [here](https://docs.netdata.cloud/health/notifications/custom/) -- NetData is quite flexible :)
