### ISSUE TITLE
doesnt recognise vmware photon os distro

### ISSUE THREAD

**Issue by osde8info** [netdata/netdata#8524]
##### Bug report summary

doesnt recognise vmware photon os  distro

##### OS / Environment

```
vmware photon os distro
```

##### Netdata version

latest 

##### Component Name

installer

##### Steps To Reproduce

1. ...
install
2. ...
get CANNOT detect yum 

##### Expected behavior

autodetect yum

**Comment by prologic** [comment]
Related #8526 

@osde8info Thank you for bringing this to our attention! As I mentioned in the other issue, are you willing to put up a PR to fix this? Also if our tooling isn't recognizing your distro at all we can close #8526  and just fix it here in this thiss.

**Comment by prologic** [comment]
Duplicate of https://github.com/netdata/netdata/issues/8526 Closing in favor of https://github.com/netdata/netdata/issues/8526
