### ISSUE TITLE
vmware photon os has missing dependancy yum  install libuv libuv-devel 

### ISSUE THREAD

**Issue by osde8info** [netdata/netdata#8526]
##### Bug report summary

vmware photon os has missing dependancy yum  install libuv libuv-devel 
##### OS / Environment

```
vmware photon 
```

##### Netdata version

 latest

##### Component Name

installer 

##### Steps To Reproduce

1. ...
install
2. ...
get libuv libuv-devel missing 

##### Expected behavior

should detect missing libuv libuv-devel

**Comment by prologic** [comment]
TIL: There is a RPM-based Distro called "VMWare Photon". 😱

@osde8info Are you willing to put up a PR to fix this for VMWare Photon?

**Comment by cosmix** [comment]
Not a priority right now.

**Comment by prologic** [comment]
@osde8info As stated we would love to support Netdata on as many systems as we can, but we need help to do so! If you are willing to put up a PR that modifies `install-required-packages.sh` to supprot your system of choice I would more than happy to help review and get it in for you! Thanks :)
