### ISSUE TITLE
How to configure netdata daemon to sends logs to remote syslog

### ISSUE THREAD

**Issue by nikobearrr** [netdata/netdata#8528]
##### Question summary
I would like to send netdata's logs to syslog.
I have seen this page where it says it can be done https://docs.netdata.cloud/daemon/config/ and this issue where a guy says "it works fine" https://github.com/netdata/netdata/issues/5717. 

I have a syslog server running on a non-standard port where I would like to send to logs. I would also like to specify which protocol I would like to use, but I cannot figure by the given information how to do so. I'd also like to use a specific facility if that is possible?

##### OS / Environment
Netdata v1.20

**Comment by prologic** [comment]
When you say "non-standard port". What do you mean exactly here? Are you running a remote syslog daemon? I'm curious why you don't use rsyslogd here and configure that to forward the logs to your custom syslogd server rather than reconfiguring netdata logging facilities?

**Comment by nikobearrr** [comment]
Hi @prologic. 
By non-standard port I mean that we run an external daemon at port 4500. So in the end of the day I would like to send my logs to udp:sysloghost:4500. 
Only specific applications will send logs to our sysloghost

**Comment by prologic** [comment]
As I started in my earlier comment, this is something I _think_ you could do with rsyslog without having to touch netdata's logging configuration. Beyond this I'm afraid I'm not too familiar with how deeply NetData can be configured (yet).

**Comment by ilyam8** [comment]
Yes, `netdata->rsyslog->any destination` will do. Rsyslog is very flexible and good.

> I'd also like to use a specific facility if that is possible?

It is possible. There is `facility log` parameter in the `[global]` section.

**Comment by nikobearrr** [comment]
Hi @ilyam8 

I cannot find `facility log` in the `[global]` section 
I am looking here: https://docs.netdata.cloud/daemon/config/#global-section-options

Yes, I can do it through local rsyslog, but if I can mitigate it and directly send it to my custom syslog-ng daemon I would prefer that. My question arose, because I cannot understand if I can specify the hostname and/or port based on the available docs.

**Comment by ilyam8** [comment]
> I cannot find facility log in the [global] section

Check `netdata.conf`, it seems it is missing in the docs.

> because I cannot understand if I can specify the hostname and/or port based on the available docs.

I think it is not possible, you can only send to local syslog.

**Comment by ilyam8** [comment]
netdata -> local rsyslog -> any destination. I think it is the only way atm. And it looks ok to me.

**Comment by nikobearrr** [comment]
Hi @ilyam8 , I am bringin this topic again as I am evaluating the netdata -> local syslog -> any destination. 
We are running our netdata in docker. How can I configure netdata to send to the local host? I checked the running container and there is no rsyslogd service running. I suspect you were not talking for netdata running in Docker and I am left with the impression that I cannot use syslog when running it dockerized?

**Comment by ilyam8** [comment]
> We are running our netdata in docker. How can I configure netdata to send to the local host?

Well, if you need access `localhost:port` from the container, then (linux only)

> https://docs.docker.com/network/host/

**Comment by ilyam8** [comment]
Perhaps changing logging driver to syslog could help (not sure, didnt have any exp with it)

> https://docs.docker.com/config/containers/logging/syslog/

**Comment by nikobearrr** [comment]
Sadly the option with the docker logging driver does not work for us. We use community docker and in case we change the logging drive to syslog then we cannot do `docker logs <container>` anymore: https://docs.docker.com/config/containers/logging/configure/#limitations-of-logging-drivers

That is the reason why we want to make netdata send to our syslog server directly (not through docker's logging driver)

I will look into the networking configuration, however it does not seem right I need to change that in order to get logs.

Thank you for the suggestions

**Comment by ilyam8** [comment]
> I will look into the networking configuration, however it does not seem right I need to change that in order to get logs.

i agree

**Comment by nikobearrr** [comment]
I'd like to bring this question again, because I have been trying to figure out a [good] way to do this and so far I haven't. In that case I would like to open a feature request for this functionality - so we can set host, port and protocol for syslog logging. Should I create a new issue for the feature request or should this issue be converted into such? 
I understand this is not of the highest priority for the netdata team, so I don't expect it to be done [anytime soon], but perhaps someone else who needs it can help out (since I am not much of a C developer myself to help).

**Comment by prologic** [comment]
Why can't you use rsyslog and configure _that_ to send local syslog logs to a remote syslog server?

**Comment by ilyam8** [comment]
@prologic https://github.com/netdata/netdata/issues/8528#issuecomment-648916991

**Comment by prologic** [comment]
The agent sending its logs directly to a syslog server then is probably something the @netdata/agent team should look into prioritising. I can't say for sure. cc @amoss

**Comment by amoss** [comment]
> Sadly the option with the docker logging driver does not work for us. We use community docker and in case we change the logging drive to syslog then we cannot do `docker logs <container>` anymore: https://docs.docker.com/config/containers/logging/configure/#limitations-of-logging-drivers
> 
> That is the reason why we want to make netdata send to our syslog server directly (not through docker's logging driver)
> 
> I will look into the networking configuration, however it does not seem right I need to change that in order to get logs.
> 
> Thank you for the suggestions

This is expected behaviour. Netdata tries to send its logs to one location. The normal default running in a container is to write everything to `stdout` (by linking the default file paths to redirect the output). Docker picks up everything on `stdout` and `stderr` from the main process in a container and stores it in the docker log.

If you set the logging output to `syslog` then Netdata will happily log to syslog instead, but it won't duplicate the logs onto `stdout` as well. It sounds as if want you need is the ability to output logs to `syslog` and `stdout` at the same time. If you raise this as a feature request then we can try to prioritize it among the other work that we are doing more easily than adding separate support to log to a remote rsyslogd.
