### ISSUE TITLE
Static distribution overwrites edited config files, with netdata v1.20.0

### ISSUE THREAD

**Issue by dmfreemon** [netdata/netdata#8531]
[I could not figure out how to re-open a issue/bug report, so...]

I'm seeing the same issue as:

https://github.com/netdata/netdata/issues/6692

except with netdata version 1.20.0.

Bug report summary (which is the same as #6692):

When running the static version installer (bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)), which is the recommended way to update, the installer overwrites my edited netdata.conf file with its empty one.

My repo steps are exactly the same as #6692.

My version string is:
$ /opt/netdata/usr/bin/netdata -V
netdata v1.20.0-258-g182ea93b

I have confirmed this happens for (at least) these distros:

* CentOS Linux release 7.7.1908 (Core)
* Fedora 31

**Comment by dmfreemon** [comment]
The automatic update script that runs via cron.daily also overwrites the netdata.conf file in the same way.

**Comment by prologic** [comment]
I will get to this in the next day or two. Thanks for reporting its in my immediate backlog.

**Comment by prologic** [comment]
Sorry for the delay (_other things got in the way_). I can confirm this is a bug and I can reproduce it. Here's what I know so far:

- The `kickstart_static64.sh` -- Specifically the `install_or_update.sh` script that is embedded inside the [Makeself](https://makeself.io/) archive _tries_ to copy old configs and creates a symlink called `orig`.
  - The problem with this is a) users don't seem to know about it b) it doesn't preserve the existing `netdata.conf` at all that I can find and c) its surprising behavior

I'm working on.a way to interactively preserve configuration changes on updates where you get the opportunity to do things like:

- take upstream version
- take your version
- merge and edit the result

I'm looking at what options exists that I can reuse (_depending on license_) and I know of:

- CRUX's `rejmerge` -- GPLv2
- Gentoo's `dispatch-conf` -- GPLv2
- _there are heaps of others embedded inside Linux distributions..._

Many of these tools however use the familiar `diff` and `patch` tools usually available on most systems including busybox-type systems like [uLinux](https://github.com/prologic/ulinux) where I'm testing this on...

I plan to have something testable today...

**Comment by Ferroin** [comment]
Sorry for the (further) delay on this one. I should have a quick fix to avoid nuking the `netdata.conf` file some time later today, and if all goes well it should land in the nightlies within the next few days.

**Comment by Ferroin** [comment]
This appears to still be an issue, though I'm honestly not sure _why_ it's an issue. Reopening this for further investigation and tracking.

**Comment by TheOldMan2000** [comment]
Thanks for working on this. Netdata wiped my netdata.conf again upgrading to v1.22.1-179-g2fe9e1b6

**Comment by prologic** [comment]
@Ferroin In case you are still investifgating... We have some functions that seem to do things related to `netdata.conf` in our Static Netdata distribution:

```#!sh
$ sift 'netdata\.conf' packaging/makeself/
packaging/makeself/install-or-update.sh:257:  create_netdata_conf "${NETDATA_PREFIX}/etc/netdata/netdata.conf"
packaging/makeself/install-or-update.sh:263:    create_netdata_conf "${NETDATA_PREFIX}/etc/netdata/netdata.conf"
packaging/makeself/install-or-update.sh:266:    create_netdata_conf "${NETDATA_PREFIX}/etc/netdata/netdata.conf" "http://localhost:19999/netdata.conf"
packaging/makeself/install-or-update.sh:270:run chmod 0644 "${NETDATA_PREFIX}/etc/netdata/netdata.conf"
packaging/makeself/jobs/70-netdata-git.install.sh:27:# Remove the netdata.conf file from the tree. It has hard-coded sensible defaults builtin.
packaging/makeself/jobs/70-netdata-git.install.sh:28:rm -f "${NETDATA_INSTALL_PARENT}/etc/netdata/netdata.conf"
```

**Comment by prologic** [comment]
Specifically this `create_netdata_conf()` function -- I'm not sure what it does (_haven't looked yet_).

**Comment by prologic** [comment]
I notice at the end of every installation of our Makeself archive (`*.gz.run`) it ends with:

```
[/opt/netdata]# chmod 0644 /opt/netdata/etc/netdata/netdata.conf
 OK
```

So it got me thinking 🤔

**Comment by TheOldMan2000** [comment]
If it helps, I get that too, here's a copy of the installer output from my CentOS7 Virtuozzo install (64 bit). It also mentions not knowing what the auto-update option is. 

`
/etc/cron.daily/netdata-updater:

Entering /tmp/netdata-updater-dNQI9P

  ^
  |.-.   .-.   .-.   .-.   .  netdata
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  (C) Copyright 2017, Costa Tsaousis
  All rights reserved
  Released under GPL v3+

  You are about to install netdata to this system.
  netdata will be installed at:

                    /opt/netdata

  The following changes will be made to your system:

  # USERS / GROUPS
  User 'netdata' and group 'netdata' will be added, if not present.

  # LOGROTATE
  This file will be installed if logrotate is present.

   - /etc/logrotate.d/netdata

  # SYSTEM INIT
  This file will be installed if this system runs with systemd:

   - /lib/systemd/system/netdata.service

   or, for older Centos, Debian/Ubuntu or OpenRC Gentoo:

   - /etc/init.d/netdata         will be created


  This package can also update a netdata installation that has been
  created with another version of it.

  Your netdata configuration will be retained.
  After installation, netdata will be (re-)started.

  netdata re-distributes a lot of open source software components.
  Check its full license at:
  https://github.com/netdata/netdata/blob/master/LICENSE.md
Creating directory /opt/netdata
Verifying archive integrity...     0%           12%           24%           36%           49%           61%           73%           85%           98%         100%   All good.
Uncompressing netdata, the real-time performance and health monitoring system     0%           12%           24%           36%           49%           61%           73%           85%           98%         100%  
Unknown option ' --auto-update'. Ignoring it.
 --- Attempt to create user/group netdata/netadata --- 
Group 'netdata' already exists.
User 'netdata' already exists.
 --- Add user netdata to required user groups --- 
Group 'docker' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'nginx' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'varnish' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'haproxy' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

User 'netdata' is already in group 'adm'.
User 'netdata' is already in group 'nsd'.
Group 'proxy' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'squid' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

Group 'ceph' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

User 'netdata' is already in group 'nobody'.
Group 'I2C' does not exist.
 FAILED  Failed to add netdata user to secondary groups 

 --- Check SSL certificates paths --- 
 --- Install logrotate configuration for netdata --- 
[/opt/netdata]# chmod 644 /etc/logrotate.d/netdata 
 OK   

 --- Telemetry configuration --- 
You can opt out from anonymous statistics via the --disable-telemetry option, or by creating an empty file /opt/netdata/etc/netdata/.opt-out-from-anonymous-statistics 

 --- Install netdata at system init --- 
Installing systemd service...
[/opt/netdata]# cp system/netdata.service /lib/systemd/system/netdata.service 
 OK   

[/opt/netdata]# systemctl daemon-reload 
 OK   

[/opt/netdata]# systemctl enable netdata 
 OK   

 --- Install (but not enable) netdata updater tool --- 
Update script is located at /opt/netdata/usr/libexec/netdata/netdata-updater.sh

 --- Check if we must enable/disable the netdata updater tool --- 
You chose *NOT* to enable auto-update, removing any links to the updater from cron (it may have happened if you are reinstalling)

Removing cron reference: /etc/cron.daily/netdata-updater

 --- creating quick links --- 
[/opt/netdata]# rm sbin 
 OK   

[/opt/netdata]# ln -s bin sbin 
 OK   

[/opt/netdata/usr]# rm bin 
 OK   

[/opt/netdata/usr]# ln -s ../bin bin 
 OK   

[/opt/netdata/usr]# rm sbin 
 OK   

[/opt/netdata/usr]# ln -s ../bin sbin 
 OK   

[/opt/netdata/usr]# rm local 
 OK   

[/opt/netdata/usr]# ln -s . local 
 OK   

[/opt/netdata]# rm netdata-configs 
 OK   

[/opt/netdata]# ln -s etc/netdata netdata-configs 
 OK   

[/opt/netdata]# rm netdata-web-files 
 OK   

[/opt/netdata]# ln -s usr/share/netdata/web netdata-web-files 
 OK   

[/opt/netdata]# rm netdata-plugins 
 OK   

[/opt/netdata]# ln -s usr/libexec/netdata netdata-plugins 
 OK   

[/opt/netdata]# rm netdata-dbs 
 OK   

[/opt/netdata]# ln -s var/lib/netdata netdata-dbs 
 OK   

[/opt/netdata]# rm netdata-metrics 
 OK   

[/opt/netdata]# ln -s var/cache/netdata netdata-metrics 
 OK   

[/opt/netdata]# rm netdata-logs 
 OK   

[/opt/netdata]# ln -s var/log/netdata netdata-logs 
 OK   

[/opt/netdata/etc/netdata]# rm orig 
 OK   

[/opt/netdata/etc/netdata]# ln -s ../../usr/lib/netdata/conf.d orig 
 OK   

 --- fix permissions --- 
[/opt/netdata]# chmod g+rx\,o+rx /opt 
 OK   

[/opt/netdata]# chown -R netdata:netdata /opt/netdata 
 OK   

 --- fix plugin permissions --- 
[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/apps.plugin 
 OK   

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/apps.plugin 
 OK   

[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/ioping 
 OK   

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/ioping 
 OK   

[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/cgroup-network 
 OK   

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/cgroup-network 
 OK   

[/opt/netdata]# chown root:netdata bin/fping 
 OK   

[/opt/netdata]# chmod 4750 bin/fping 
 OK   

Save install options
 --- starting netdata --- 
 --- Restarting netdata instance --- 

Stopping all netdata threads
[/opt/netdata]# stop_all_netdata 
 OK   

Starting netdata using command 'systemctl start netdata'
[/opt/netdata]# systemctl start netdata 
 OK   


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata              .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed now!  -'   '-'   '-'   '-'  
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

[/opt/netdata]# chmod 0644 /opt/netdata/etc/netdata/netdata.conf 
 OK   

Switching back to /
`

**Comment by Ferroin** [comment]
OK, this should _really_ be fixed now starting with tonight's nightly builds.

**Comment by prologic** [comment]
With #9174 merged. Please please please let us know if there are any further issues here. The PR was throughly tested (_again_) and I hope we don't have this issue reoccur.
