### ISSUE TITLE
Exclude disks/paths/mountpoints in FreeBSD

### ISSUE THREAD

**Issue by herrbischoff** [netdata/netdata#8536]
##### Question summary

I'm running Netdata on a FreeBSD build server that uses Poudriere to create packages. Poudriere uses ZFS to quickly create and tear down jails. Netdata throws tons of alerts about running out of disk space in those mounts, which is not the case and irrelevant. Since those jails are temporary and change frequently, I'd like to exclude the full path under which they are created (/usr/local/poudriere).

I tried [following the docs](https://docs.netdata.cloud/collectors/diskspace.plugin/) but this setting does not work for me, neither path gets excluded (`/ram` is a small ram disk):

```
[plugin:proc:diskspace]
        exclude space metrics on paths = /ram/* /usr/local/poudriere/*
```

What irritates me is that `proc` is referenced, as this is a mechanism exclusive to Linux. I suspect that the setting simply doesn't apply for my setup. Seeing that `freebsd.plugin` is the only one referenced in `netdata.conf`, it all but verifies this suspicion. However, [freebsd.plugin](https://docs.netdata.cloud/collectors/freebsd.plugin/) comes with almost no documentation.

How do I exclude some disks/paths/mountpoints in FreeBSD from monitoring altogether?

##### OS / Environment

FreeBSD 12.1, installed via `pkg`.

##### Component Name

freebsd.plugin / diskspace.plugin

##### Expected results

Excluded disks/paths/mountpoints do not show up as graphs and generate no alerts.

**Comment by herrbischoff** [comment]
With regard to the Stalebot notification I ask again if anyone can shed any light on this.

**Comment by vlvkobal** [comment]
Please use the `exclude space metrics on paths` option in the `plugin:freebsd:getmntinfo` section. You can view your actual configuration at the `http://yourhost:19999/netdata.conf` enpoint.

**Comment by herrbischoff** [comment]
Thanks for the pointer, especially the mention of `http://yourhost:19999/netdata.conf`, which is very helpful. It should be featured way more prominently in the documentation that all implemented settings can be found there.

**Comment by vlvkobal** [comment]
> especially the mention of http://yourhost:19999/netdata.conf, which is very helpful. It should be featured way more prominently in the documentation that all implemented settings can be found there
@joelhans :point_up:
