### ISSUE TITLE
FreeBSD 11.3 + Unbound + Netdata = setfacl unbound.conf: Operation not supported

### ISSUE THREAD

**Issue by TDJ211** [netdata/netdata#8549]
##### Question summary
Cannot make unbound.conf readable by Netdata in FreeBSD
##### OS / Environment
FreeBSD 11.3 stable
##### Component Name
permissions
##### Expected results
Netdata to read unbound.conf data and display

Installed Netdata and its reading the out of the box stuff just fine. But when trying to make unbound.conf data readable by Netdata I get the below

```
$ sudo setfacl -m user:netdata:r unbound.conf
setfacl: unbound.conf: acl_get_file() failed: Operation not supported
```

**Comment by ilyam8** [comment]
Hi @TDJ211 👋 Reading `unbound.conf` is optional, you can set all parameters in the module configuration file. `unbound.conf` is used for auto-detection to get following parameters:

> https://github.com/netdata/go.d.plugin/blob/62e45e4415a3752dd2a096581754e77b82f54f48/modules/unbound/config/config.go#L9-L17

cc @Ferroin

**Comment by Ferroin** [comment]
The instrctions kind of assume the host system is Linux. I'm not sure of how you would go about setting ACL's on FreeBSD beyond the basic POSIX file permissions. The important thing if you want autodetection of settings from `unbound.conf` is just that the user Netdata runs as can read the file,exactly how that's done is technically irrelevant.

**Comment by ilyam8** [comment]
And keep in mind if you have several config files (include) all of them should be readable by netdata user.

**Comment by TDJ211** [comment]
Thanks for the swift reply guys! 

I got everything running on Ubuntu, but it seems that Unbound runs much better on FreeBSD than Linux/Ubuntu. 

I love Netdata as it gives me so much info than I even realized I needed. (i.e it alerted me to Entropy issues when running Unbound on Rasp Pi).

Anyways, on to my question: 

Sorry but Im still a bit of a Unix n00b. I cant even navigate to where I would apply that code. I even tried finding it on my Ubuntu installation and I just have no idea. On the Ubuntu installation I do see the go.d plugin and I am able to get to the "edit-config go.d.conf" but I have no idea how to get to the specific module config.

On my FreeBSD installation, I installed using the method from documentation
https://docs.netdata.cloud/packaging/installer/methods/freebsd/

But inside Netdata directory I do not see the go.d plugin. This is what I have inside netdata directory

```
root@unbound-12:/usr/local/etc/netdata # ls
.clang-format           LICENSE                 daemon
.codacy.yml             Makefile                database
.codeclimate.yml        Makefile.am             depcomp
.csslintrc              Makefile.in             diagrams
.dockerignore           README.md               docs
.eslintignore           REDISTRIBUTED.md        exporting
.eslintrc               SECURITY.md             health
.git                    aclk                    install-sh
.gitattributes          aclocal.m4              libnetdata
.github                 apps.plugin             missing
.gitignore              autom4te.cache          netdata
.lgtm.yml               backends                netdata-installer.log
.remarkignore           build                   netdata-installer.sh
.remarkrc.js            build_external          netdata.cppcheck
.squash.yml             claim                   netdata.spec
.travis                 cli                     netdata.spec.in
.travis.yml             collectors              netdatacli
.yamllint.yml           compile                 netlify.toml
BREAKING_CHANGES.md     config.guess            package-lock.json
BUILD.md                config.h                package.json
CHANGELOG.md            config.h.in             packaging
CMakeLists.txt          config.log              registry
CODE_OF_CONDUCT.md      config.status           stamp-h1
CONTRIBUTING.md         config.sub              streaming
CONTRIBUTORS.md         configs.signatures      system
DOCUMENTATION.md        configure               test-driver
Dockerfile              configure.ac            tests
Dockerfile.docs         contrib                 web
Dockerfile.test         coverity-scan.sh
HISTORICAL_CHANGELOG.md cppcheck.sh
```

**Comment by ilyam8** [comment]
> root@unbound-12:/usr/local/etc/netdata # ls

^^ That is netdata source code.
___

According [docs](https://docs.netdata.cloud/packaging/installer/methods/freebsd/) it should be in `/opt/netdata/etc/netdata`

**Comment by TDJ211** [comment]
Ahhh, ok thanks. 

Now do I copy and paste the config from `https://github.com/netdata/go.d.plugin/blob/62e45e4415a3752dd2a096581754e77b82f54f48/modules/unbound/config/config.go#L9-L17`

in the "edit-config go.d.conf" and uncomment the Unbound module?

**Comment by ilyam8** [comment]
No, you `./edit-config go.d/unbound.conf` and that is it.

In case of problem use debug mode

> https://github.com/netdata/go.d.plugin/tree/master/modules/unbound#troubleshooting

**Comment by ilyam8** [comment]
@TDJ211 i am closing the issue, but feel free to ask if you still cant get it working

**Comment by TDJ211** [comment]
Ok, I `./edit-config go.d/unbound.conf` and updated the file paths


```
jobs:
  - name: local
    address: 127.0.0.1:8953
    timeout: 1
    conf_path: usr/local/etc/unbound/unbound.conf
    cumulative: yes
    use_tls: yes
    tls_skip_verify: yes
    tls_cert: usr/local/etc/unbound/unbound_control.pem
    tls_key: usr/local/etc/unbound/unbound_control.key
```
I think I got that part right. 

I have yet to make unbound.conf readable by 'netdata' user.

Here's the output of getfacl unbound.conf
```
root@unbound-12:/opt/netdata/etc/netdata # getfacl /usr/local/etc/unbound/unbound.conf
# file: /usr/local/etc/unbound/unbound.conf
# owner: root
# group: wheel
user::rw-
group::r--
other::r--
```

Ive given up on trying to get setfacl to work though. Somehow I need to enable it, but cant figure out how.


Ferroin mentioned using some basic POSIX file permissions to do this. Should I add netdata to 'wheel' group?

I was able to successfully get stats running `unbound-control stats_noreset` 

It wont let me su - netdata to run `./go.d.plugin -d -m unbound`

`root@unbound-12:/opt/netdata/etc/netdata # su - netdata
This account is currently not available.
`

**Comment by ilyam8** [comment]
> Im still not sure what im supposed to do with this

Nothing, it is source code, i gave the link to show you parameters we auto-detect from the config file.


> This account is currently not available.

su -s /bin/bash netdata

Try `./go.d.plugin -d -m unbound` as `netdata` user and as `root`

**Comment by TDJ211** [comment]
`root@unbound-12:/opt/netdata/etc/netdata # su -s /bin/bash netdata
su: unknown login: /bin/bash
root@unbound-12:/opt/netdata/etc/netdata # ./go.d.plugin -d -m unbound
./go.d.plugin: Command not found.
root@unbound-12:/opt/netdata/etc/netdata # service netdata restart
Stopping netdata.
Waiting for PIDS: 13470.
Starting netdata.
2020-04-02 02:22:16: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
`

**Comment by ilyam8** [comment]
> root@unbound-12:/opt/netdata/etc/netdata # ./go.d.plugin -d -m unbound

there is no `go.d.plugin` in the `/opt/netdata/etc/netdata` it is in the `/opt/netdata/usr/libexec/netdata/plugins.d/`.

**Comment by TDJ211** [comment]
```
root@unbound-12:/opt/netdata/usr/libexec/netdata/plugins.d # ./go.d.plugin -d -m unbound
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 2
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] create.go:72 loading 'unbound' configuration
[ INFO  ] main[main] orchestrator.go:158 start main loop
[ INFO  ] unbound[local] init.go:19 reading '/usr/local/etc/unbound/unbound.conf'
[ INFO  ] unbound[local] init.go:41 applying configuration: ["statistics-cumulative": 'yes', "control-enable": 'yes', "control-interface": '', "control-port": '', "control-user-cert": '', "control-key-file": '', "control-cert-file": '']
[ DEBUG ] unbound[local] init.go:43 changing 'cumulative_stats': false => true
[ DEBUG ] unbound[local] unbound.go:82 using address: 127.0.0.1:8953, cumulative: true, use_tls: false, timeout: 1s
[ ERROR ] unbound[local] unbound.go:100 command 'UBCT1 stats_noreset': empty resopnse
[ ERROR ] unbound[local] job.go:121 Check failed
[ WARN  ] main[main] start.go:41 unbound[local]: autodetection failed
[ DEBUG ] main[main] orchestrator.go:173 tick 0
[ DEBUG ] main[main] orchestrator.go:173 tick 1
[ DEBUG ] main[main] orchestrator.go:173 tick 2
```

**Comment by ilyam8** [comment]
> [ ERROR ] unbound[local] unbound.go:100 command 'UBCT1 stats_noreset': empty resopnse
 https://github.com/netdata/go.d.plugin/blob/62e45e4415a3752dd2a096581754e77b82f54f48/modules/unbound/collect.go#L30-L36


> [ DEBUG ] unbound[local] unbound.go:82 using address: 127.0.0.1:8953, cumulative: true, use_tls: false, timeout: 1s


I guess it doesnt work because we dont use tls

**Comment by TDJ211** [comment]
Aha, for some odd reason I turned TLS off in `./go.d.plugin -d -m unbound`

I just turned it back on and viola!! It worked!!

You da man Ilyam! Thank you so much!

**Comment by TDJ211** [comment]
One more question: 

So far im 2 for 3. Ive gotten it working on my test lab and on a 2nd server. 

I initially had some issues after the success message and getting it to display on the Netdata dashboard. Im not exactly sure of what I did but I tried a series of restarts and reboots and im pretty sure it came up after about 10 mins of messing around. 

Now im on my 3rd server install with the success message but its been a day and its still will not displaying on my Netdata dashboard. Any ideas? See out below

```
root@unbound-bsd:/opt/netdata/etc/netdata # **./edit-config go.d/unbound.conf**

jobs:
  - name: local
    address: 127.0.0.1:8953
    timeout: 1
    conf_path: /usr/local/etc/unbound/unbound.conf
    cumulative: yes
    use_tls: yes
    tls_skip_verify: yes
    tls_cert: /usr/local/etc/unbound/unbound_control.pem
    tls_key: /usr/local/etc/unbound/unbound_control.key
```


```
root@unbound-bsd:/opt/netdata/usr/libexec/netdata/plugins.d # **./go.d.plugin -d - m unbound**
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 2
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] create.go:72 loading 'unbound' configuration
[ INFO  ] main[main] orchestrator.go:158 start main loop
[ INFO  ] unbound[local] init.go:19 reading '/usr/local/etc/unbound/unbound.conf                                     '
[ INFO  ] unbound[local] init.go:41 applying configuration: ["statistics-cumulative": 'yes', "control-enable": 'yes', "control-interface": '', "control-port": '', "control-user-cert": '', "control-key-file": '', "control-cert-file": '']
[ DEBUG ] unbound[local] init.go:43 changing 'cumulative_stats': false => true
[ DEBUG ] unbound[local] unbound.go:82 using address: 127.0.0.1:8953, cumulative: true, use_tls: true, timeout: 1s
[ DEBUG ] unbound[local] unbound.go:84 using tls_skip_verify: true, tls_key: /us                                     r/local/etc/unbound/unbound_control.key, tls_cert: /usr/local/etc/unbound/unbound_control.pem
[ INFO  ] main[main] start.go:46 unbound[local]: autodetection success
[ DEBUG ] main[main] orchestrator.go:173 tick 0
CHART 'netdata.execution_time_of_unbound_local' '' 'Execution Time for unbound_local' 'ms' 'go.d' 'netdata.go_plugin_execution_time' '' '145000' '1' '' 'go.d' 'unbound'
DIMENSION 'time' '' '' '' '' '' 
```

**Comment by ilyam8** [comment]
> root@unbound-bsd:/opt/netdata/usr/libexec/netdata/plugins.d # ./go.d.plugin -d - m unbound


it works when you are `root` user, try as `netdata`.

**Comment by TDJ211** [comment]
```
su -s /bin/bash netdata
su: unknown login: /bin/bash
```

**Comment by ilyam8** [comment]
Did you do `su -s /bin/bash netdata` as root?

it works for me

**Comment by TDJ211** [comment]
Yea I did

`root@unbound-dns-bsd:~ # su -s /bin/bash netdata
su: unknown login: /bin/bash
`

Sorry if I havent mentioned it, but Im on FreeBSD 12.1 now btw

**Comment by TDJ211** [comment]
Ok, just tried in 11.3, same thing

**Comment by ilyam8** [comment]
I dont know why it doesnt work in freebsd, ive never used freebsd.

> su - netdata

**Comment by TDJ211** [comment]
Yea, that was the first thing I tried. This is what im getting

```
root@unbound-12:~ # su - netdata
This account is currently not available.
```

What do you think that means? Permissions? I need to find a way to allow netdata to allow login

**Comment by TDJ211** [comment]
OK, im finding a few different ways to login. Does the netdata user have a password?

https://unix.stackexchange.com/questions/10994/how-can-i-switch-one-user-to-another-in-freebsd

**Comment by ilyam8** [comment]
no, you need to create it (`passwd`)

**Comment by ilyam8** [comment]
> [ ERROR ] unbound[local] unbound.go:76 creating client: could not load keypair /usr/local/etc/unbound/unbound_control.pem:/usr/local/etc/unbound/unbound_control.key: open /usr/local/etc/unbound/unbound_control.pem: permission denied

> open /usr/local/etc/unbound/unbound_control.pem: permission denied

**Comment by TDJ211** [comment]
I really appreciate your patience. I finally figured out how to enable ACL's in FreeBSD. The syntax is also a little different. 
 
For future reference of others, here it is:

Enable ACLs in FreeBSD

Add option acls inside /etc/fstab under your primary file system and then reboot

```
# Device        Mountpoint      FStype  Options Dump    Pass#
/dev/da0s1a     /                     ufs        rw,acls   1            1
/dev/da0s1b     none              swap      sw        0            0

```

FreeBSD syntax for setfacl

```
sudo setfacl -m u:netdata:r unbound.conf
sudo setfacl -m u:netdata:r unbound_control.key
sudo setfacl -m u:netdata:r unbound_control.pem
```

**Comment by TDJ211** [comment]
Hello, its me again. 

Im trying to do the same FreeBSD install on a Rasp Pi3B. 

After installing Unbound and then Netdata, I do not even see the unbound module present. 

```
root@generic:/opt/netdata/etc/netdata # sudo ./edit-config go.d/unbound.conf
File 'go.d/unbound.conf' is not found in '/opt/netdata/usr/lib/netdata/conf.d' 
```

And when I look install netdata/conf.d directory, I do not see any of the go.d collectors at all. 

```
root@generic:/opt/netdata/usr/lib/netdata/conf.d # ls
apps_groups.conf                health_email_recipients.conf
aws_kinesis.conf                ioping.conf
charts.d                        node.d.conf
charts.d.conf                   python.d
ebpf_process.conf               python.d.conf
fping.conf                      statsd.d
health.d                        stream.conf
health_alarm_notify.conf
```
Any ideas??

**Comment by ilyam8** [comment]
> Im trying to do the same FreeBSD install on a Rasp Pi 3B.

How did you install it? I guess you install it _from ports_ (not sure, not a freebsd user) and we dont mantain that thing.

However you can download it manually and put in the `plugins.d` dir.

See

> https://github.com/netdata/go.d.plugin/releases/tag/v0.18.0

> root@generic:/opt/netdata/etc/netdata # sudo ./edit-config go.d/unbound.conf
File 'go.d/unbound.conf' is not found in '/opt/netdata/usr/lib/netdata/conf.d'
Same. Create the dir manually and put `unbound.conf` in there.

You can download it using this link:

> https://raw.githubusercontent.com/netdata/go.d.plugin/v0.18.0/config/go.d/unbound.conf

**Comment by TDJ211** [comment]
Yea, I installed from here:  https://docs.netdata.cloud/packaging/installer/methods/freebsd/

By "put in the plugins.d dir." do you mean place file inside `/opt/netdata/etc/netdata/custom-plugins.d` dir?
