### ISSUE TITLE
Location for custom python modules

### ISSUE THREAD

**Issue by FedericoCeratto** [netdata/netdata#8555]
The available documentation at https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin#how-to-debug-a-python-module does not indicate a path to install custom python modules. (With "custom" I mean that they are not shipped as part of an OS package for Netdata, but deployed by the end user.)

The /usr directory is meant to be written only by package managers / installers. See `man hier` for clarification.

Is there a supported location for python modules under /etc/netdata ?

Related: #8471

Thanks!

**Comment by ilyam8** [comment]
Hi @FedericoCeratto. No, there is no custom location.

https://github.com/netdata/netdata/blob/ef2bd3956b2797de31008ddffab671b9675f070d/collectors/python.d.plugin/python.d.plugin.in#L89-L95

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).

**Comment by ilyam8** [comment]
@FedericoCeratto we use `/etc/netdata/python.d/` for configuration files. Which directory do you think will do for custom python modules? `/etc/netdata/python.d/modules/`?

**Comment by ilyam8** [comment]
@Ferroin which directory could we use for custom python modules?

**Comment by FedericoCeratto** [comment]
`/etc/` is not meant for scripts. The directories for custom plugins could be configurable and perhaps default to `/opt/netdata/python.d/` and `/usr/lib/netdata/python.d/` or similar.

**Comment by Ferroin** [comment]
@ilyam8 It should be something under `/usr/lib/netdata` if it’s for Netdata specifically. The bigger issue is our broken handling of Python site directories, we currently do not have the same module search path when running the `python.d` plugin from the agent and when running an interactive shell as the Netdata user, which means that you can’t just start a shell as the Netdata user and `pip install` whatever modules you want directly.

**Comment by ilyam8** [comment]
I see we use [`CONFIG_DIR/custom-plugins.d`](https://github.com/netdata/netdata/blob/1bcf1572b93f1f4cae837b6152c286b8da83c973/collectors/plugins.d/plugins_d.c#L129) for custom plugins by default. I understand that

> /etc/ is not meant for scripts

but since we are using it for plugins, I can make python.d checking `CONFIG_DIR/custom-plugins.d/python.d` for modules.

What do you think, guys?
