### ISSUE TITLE
How can I install netdata on CentOS without any keyboard input?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#8566]
easy one, when I install netdata on CentOS by bash command `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`, I need to press `enter` or `y` a few times, is there a way to make it all automatically?

**Comment by prologic** [comment]
Try adding `--dont-wait --non-interactive` to the end.

**Comment by ilyam8** [comment]
> [ilyam@ilyam-pc netdata]$ bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-cloud --dont-wait --non-interactive

```
...
The following command will be run:

 >> IMPORTANT <<
    Please make sure your system is up to date
    by running:   pacman -Syu

pacman --needed -S autoconf-archive autogen judy python-pymongo


Press ENTER to run it >
```

**Comment by startryst** [comment]
> ```batchfile
> pacman -Syu
> ```

I'm talking  about CentOS, which is using yum....

**Comment by ilyam8** [comment]
I see i see, i mean anyway `--dont-wait --non-interactive` doesnt work and installer waits for the user input.

have you tried `--dont-wait --non-interactive` ?

**Comment by ilyam8** [comment]
Probably it works like that because i am running it from terminal

**Comment by startryst** [comment]
> Try adding `--dont-wait --non-interactive` to the end.

Tried, works perfectly for CentOS 7

Thank you, both @prologic @ilyam8

**Comment by ilyam8** [comment]
it looks like `--dont-wait` is enough btw

https://github.com/netdata/netdata/blob/d31707e6a400f2dfa4dca93b16e562e2c3f4a3db/packaging/installer/kickstart.sh#L301-L303

**Comment by prologic** [comment]
> it looks like `--dont-wait` is enough btw

Yeah you are right. I'm so used to the other tools we have :)
