### ISSUE TITLE
CUPS information

### ISSUE THREAD

**Issue by m-wynn** [netdata/netdata#857]
CUPS provides a lot of interesting statistics (jobs in queue, printer statuses, printing frequency), and can benefit from alerts (for example, if print jobs start piling up or one gets stuck).

It would be very nice to see a CUPS plugin for netdata.

**Comment by luserx0** [comment]
I'm interested in taking this plugin on me in terms of GSoC 2017.

**Comment by luserx0** [comment]
Well, I was not accepted in netdata for GSoC, but I got into GNU-Kawa. So, for the time being I won't be able to create the plugin. 
Looking forward to contribute in the near future.

This issue remains unassigned :)

**Comment by l2isbad** [comment]
Hm, i see we have almost finished (@simonnagl  confirm or deny ) [CUPS plugin in C](https://github.com/netdata/netdata/pull/1678)

@vlvkobal please have a look, maybe you can take over it

**Comment by simonnagl** [comment]
The basis work was done. I would not say I almost finished it.
