### ISSUE TITLE
Is it possible to access a job variable defined in conf file inside the alarm template?

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8574]
##### Question summary
I have configured `http_check` plugin to monitor 5 webpages, is it possible to pass the `url` variable from `http_check.conf` to the alert so I can know the URL which causes the problem?
##### Expected results
An alert description like this:
```
average of failed requests either due to timeouts or no connection during the last 5 minutes on http://test.x.y.z
```

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

You can see all available variables to create an alarm doing a request for Netdata using the following format `http://localhost:19999/api/v1/alarm_variables?chart=CHART_NAME`, for example, to see variables for `system.cpu`, please, do the following request :

```
http://localhost:19999/api/v1/alarm_variables?chart=system.cpu
```

**Comment by yasharne** [comment]
Thanks @thiagoftsm, How can I use the variables inside the `info` section of the alert template?

**Comment by thiagoftsm** [comment]
You are welcome @yasharne !

The `info` fields right now as described in our [documentation]( https://learn.netdata.cloud/docs/agent/health/quickstart#write-a-new-health-entity ) the field `info` only accepts a description that is appended to the `dashboard` and message sent to different channels. Netdata does not support an external variable for alarms.

I changed this `issue` from `question` to user request, for we bring this feature in a near future.

best regards!

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
