### ISSUE TITLE
Auto generate the ChangeLog

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8575]
##### Feature idea summary

The existing tools we use to generate the [ChangeLog](/CHANGELOG.md) are
a bit buggy and unreliable. We need a way to auto-generate this
changelog per release cycle without too much human effort.

##### Requirements

- [ ] Preserve the existing format
- [ ] Skip merge commits, nightlies, package builds, etc.
- [ ] Skip commits whoose PRs were marked `no changelog`.
- [ ] Not suck :)

##### Expected behavior

We have a tool that can automatically update the [ChangeLog](/CHANGELOG.md)
which we will eventually incorporate into the new automated release
workflows.

cc @cakrit

**Comment by joelhans** [comment]
I don't want to add complexity to this task of yours, but out of curiosity: Is there a way to auto generate a YAML file with this information?

I only ask because I saw another project using the same framework as the new docs site I'm building, and they have a really cool [release page](https://vector.dev/releases/0.8.2) where you can filter issues by type, see a number of changelogs in one place, etc. If there was a YAML file with the text from the PR and some type of grouping, I could try my hand and building a page like this for us.

**Comment by prologic** [comment]
> I don't want to add complexity to this task of yours, but out of curiosity: Is there a way to auto generate a YAML file with this information?

Short answer, yes. Tell me what you want and how you want it structured and we can do it.

Are you also able to help me structure/format the ChangeLog and configure `git-chglog` appropriately? :) Chris seems somewhat busy and I'd love to get this done :)

**Comment by joelhans** [comment]
Actually, JSON is probably better for something like the output I'm looking for. This is just me writing fake JSON off the top of my head, but I don't think we need much more than this.

```json
[
  {
    "release": "v1.21.0",
    "date": "2020-04-27",
    "commits": [
      {
        "number": "8472",
        "title": "This is the title of a PR",
        "type": "feature",
        "url": "https://github.com/netdata/netata/pulls/..."
      },
      {
        "number": "8472",
        "title": "This is the title of a PR",
        "type": "bugfix",
        "url": "https://github.com/netdata/netata/pulls/..."
      },
      {
        "number": "8472",
        "title": "This is the title of a PR",
        "type": "update",
        "url": "https://github.com/netdata/netata/pulls/..."
      },
      {
        "number": "8472",
        "title": "This is the title of a PR",
        "type": "docs",
        "url": "https://github.com/netdata/netata/pulls/..."
      }
    ]
  },
  {
    "release": "v1.20.0",
    "date": "2020-02-15",
    "commits": [
      {
        "number": "8144",
        "title": "This is the title of a PR",
        "type": "feature",
        "url": "https://github.com/netdata/netata/pulls/..."
      },
      {
        "number": "8143",
        "title": "This is the title of a PR",
        "type": "bugfix",
        "url": "https://github.com/netdata/netata/pulls/..."
      },
      {
        "number": "8142",
        "title": "This is the title of a PR",
        "type": "update",
        "url": "https://github.com/netdata/netata/pulls/..."
      },
      {
        "number": "8141",
        "title": "This is the title of a PR",
        "type": "docs",
        "url": "https://github.com/netdata/netata/pulls/..."
      }
    ]
  }
]
```

**Comment by joelhans** [comment]
As far as the rest goes, I'm still trying to wrap my head around how git-chglog works! But I'm happy to help you as best I can to figure this out.

The biggest challenge here is how we get git-chglog to categorize PRs. There's no consistency in the way we title PRs, so it seems difficult to use titles for this categorization. For example, sometimes I use "fix" in the PR title for a documentation change, but then that will end up in the bugfix category instead of the documentation update.

Is there any other way to pull information that would help us categorize PRs? Maybe the labels assigned to them on creation? Or do we just have to create some kind of `feat(web) ...` standard style for PR titles and enforce it?

**Comment by joelhans** [comment]
Hey @prologic — I chatted with @zack-shoylev about this some today, and he had an interesting idea for how we could roll this out. To roughly paraphrase his idea:

1. We decide a commit spec/standard we think provides the best balance of being easy to use and automation-friendly. Maybe something like [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
2. Build changelog automation around that standard.
3. Begin to ask engineers and contributors to use that standard, but not enforce it.
4. Once adoption is high enough, enforce the standard using CI checks during PR creation.

What do you think? Have you used some kind of commit spec in previous jobs, and did you find them useful for the team?

**Comment by prologic** [comment]
No I don't like that idea; its a bit too prescriptive and a bit cryptic to read. I could not find the original PR I put up for improving the PR Title guidelines but I've put it up again here: https://github.com/netdata/netdata/pull/8809/files

This came out of collaboration with @cosmix where the PR/Commit Titles should be in the "Imperative Mood"; which many have been already largely following.

If we follow this standard well enough then the proposed tool I'm proposing can and will work very well (_with some configuration tweaks_).

**Comment by prologic** [comment]
@joelhans As to your previous point; yes I agree, we should also "categorize" commits based on the labels we assign PRs. I'll look into how we can do that too.

**Comment by zack-shoylev** [comment]
`Must reference an existing issue.` can be very helpful and go a long way. Would you enforce that through a check? What about categories? Not saying you should, just curious.

One very nice feature here that would help with content generation and outreach would be extracting images or technical discussions/specs from linked issues (maybe as a post-processing or even manual step). The point here is that a change log is a reference but a change log with some high-level discussion on changes (even a few sentences) is engaging and good content. Though for now we should probably focus on getting the first part done in a more automated way.

**Comment by prologic** [comment]
> Though for now we should probably focus on getting the first part done in a more automated way.

👍

**Comment by prologic** [comment]
Duplicate of #8117 (_which I'm choosing in preference to put at the top of my Backlog_).
