### ISSUE TITLE
Incorrect signal handling

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#8576]
##### OS / Environment
```
Linux 4.19.109-gentoo #1 SMP x86_64 AMD EPYC 7451
Gentoo Base System release 2.6
```
##### Netdata version
netdata v1.20.0
##### Component Name
collectors
##### Description
After a day of running netdata 1.20, it was found that various charts are frozen on different servers. 
For example, one server has had issue with netfilter charts were frozen on one server (another has had Apllications plugin issue and so on).
No errors found in logs, logged information appeared to be very brief:
```
/var/log/netdata/error.log:2020-04-01 15:50:57: netdata INFO  : PLUGINSD[nfacct] : set name of thread 62510 to PLUGINSD[nfacct
/var/log/netdata/error.log:2020-04-01 15:50:57: netdata INFO  : PLUGINSD[nfacct] : connected to '/usr/libexec/netdata/plugins.d/nfacct.plugin' running on pid 62514
/var/log/netdata/error.log:2020-04-01 17:43:53: nfacct.plugin INFO  : MAIN : NFACCT process exiting
/var/log/netdata/error.log:2020-04-01 19:50:57: nfacct.plugin INFO  : MAIN : NFACCT process exiting
```
Note that two lines refer to _nfacct_ plugin referring to pid 62514 and thread (probably, _pid_, too?) 62510.

On netdata reload attempt it was found that netdata ignores all signals except 9 (SIGKILL) and 19 (SIGSTOP) and it became impossible to either reload configuration with SIGHUP2 or restart netdata process using SIGTERM.

It was also found that some processes in netdata tree have <defunct> state:
```
netdata  62229  1.7  0.7 2308740 2055572 ?     Sl   Apr01  23:52  |   \_ /usr/sbin/netdata -D
netdata  62495  0.0  0.0      0     0 ?        Z    Apr01   0:00  |       \_ [sh] <defunct>
netdata  62500  2.3  0.0 188320 26116 ?        Sl   Apr01  31:03  |       \_ /usr/lib/python-exec/python3.6/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata  62507  0.0  0.0   2384  1592 ?        S    Apr01   0:23  |       \_ /usr/libexec/netdata/plugins.d/qmail.plugin 1
netdata  62511  0.0  0.0   2372  1544 ?        S    Apr01   0:13  |       \_ /usr/libexec/netdata/plugins.d/svstat.plugin 1
netdata  62514  0.0  0.0      0     0 ?        Z    Apr01   0:01  |       \_ [nfacct.plugin] <defunct>
netdata  62515  0.0  0.0   2376   804 ?        S    Apr01   0:01  |       \_ /usr/libexec/netdata/plugins.d/parser.plugin 1
netdata  67228 22.8  0.0 100024 84984 ?        S    11:51  32:37  |       \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
netdata  85497  0.0  0.0   4352  3272 ?        S    13:51   0:01  |       \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
```
attempts to send signals 1,12,15 have had no effect, no line was loggid into log files, no output printed to console, nothing happened to process state. Finally, netdata process was killed with SIGKILL and restarted.

Newly restarted process also has one plugin in defunct-state, but another plugin got defunct, now this is scanner plugin:
```
netdata  61923  1.8  0.1 702768 443156 ?       Sl   15:10   0:59  |   \_ /usr/sbin/netdata -D
netdata  62159  0.0  0.0   4352  3332 ?        S    15:10   0:03  |       \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata  62181  2.2  0.0 188712 31948 ?        Sl   15:10   1:15  |       \_ /usr/lib/python-exec/python3.6/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata  62183 25.5  0.0  97632 82272 ?        S    15:10  14:04  |       \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
netdata  62186  0.0  0.0   2384   776 ?        S    15:10   0:00  |       \_ /usr/libexec/netdata/plugins.d/qmail.plugin 1
netdata  62188  0.0  0.0      0     0 ?        Z    15:10   0:00  |       \_ [scanner.plugin] <defunct>
netdata  62190  0.0  0.0   2372   816 ?        S    15:10   0:00  |       \_ /usr/libexec/netdata/plugins.d/svstat.plugin 1
netdata  62192  0.0  0.0   2624   840 ?        S    15:10   0:00  |       \_ /usr/libexec/netdata/plugins.d/nfacct.plugin 1
netdata  62193  0.0  0.0   2376   756 ?        S    15:10   0:00  |       \_ /usr/libexec/netdata/plugins.d/parser.plugin 1
```
and logged lines:
```
/var/log/netdata/error.log:No scannerd log directory detected
/var/log/netdata/error.log:2020-04-02 15:10:15: netdata INFO  : PLUGINSD[scanner] : thread created with task id 62185
/var/log/netdata/error.log:2020-04-02 15:10:15: netdata INFO  : PLUGINSD[scanner] : set name of thread 62185 to PLUGINSD[scanne
/var/log/netdata/error.log:2020-04-02 15:10:15: netdata INFO  : PLUGINSD[scanner] : connected to '/usr/libexec/netdata/plugins.d/scanner.plugin' running on pid 62188
```

In addition, it was found that after receiving SIGTERM and exit, netdata left plugins running in background. Upon `next kill -15 netdata`, both plugins of new and previous restart appear to stay in process list:
```
# ps xa | grep 'sbin/netdata'
21011 ?        Sl     0:07 /usr/sbin/netdata -D

# ps xa | grep plugin
21275 ?        S      0:00 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
21298 ?        Sl     0:01 /usr/lib/python-exec/python3.6/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
21301 ?        R      0:01 /usr/libexec/netdata/plugins.d/apps.plugin 1
21304 ?        S      0:00 /usr/libexec/netdata/plugins.d/qmail.plugin 1
21308 ?        S      0:00 /usr/libexec/netdata/plugins.d/svstat.plugin 1
21310 ?        S      0:00 /usr/libexec/netdata/plugins.d/parser.plugin 1
21311 ?        S      0:00 /usr/libexec/netdata/plugins.d/nfacct.plugin 1
27859 ?        S      0:01 /usr/libexec/netdata/plugins.d/qmail.plugin 1
27865 ?        S      0:00 /usr/libexec/netdata/plugins.d/svstat.plugin 1
27866 ?        S     24:28 /usr/libexec/netdata/plugins.d/apps.plugin 1
27868 ?        S      0:00 /usr/libexec/netdata/plugins.d/parser.plugin 1
27869 ?        S      0:00 /usr/libexec/netdata/plugins.d/nfacct.plugin 1
44577 ?        S     20:02 /usr/libexec/netdata/plugins.d/apps.plugin 1
44578 ?        S      0:01 /usr/libexec/netdata/plugins.d/qmail.plugin 1
44581 ?        S      0:00 /usr/libexec/netdata/plugins.d/nfacct.plugin 1
44583 ?        S      0:00 /usr/libexec/netdata/plugins.d/svstat.plugin 1
44584 ?        S      0:00 /usr/libexec/netdata/plugins.d/parser.plugin 1
62183 ?        S     15:45 /usr/libexec/netdata/plugins.d/apps.plugin 1
62186 ?        S      0:00 /usr/libexec/netdata/plugins.d/qmail.plugin 1
62190 ?        S      0:00 /usr/libexec/netdata/plugins.d/svstat.plugin 1
62192 ?        S      0:00 /usr/libexec/netdata/plugins.d/nfacct.plugin 1
62193 ?        S      0:00 /usr/libexec/netdata/plugins.d/parser.plugin 1
62507 ?        S      0:25 /usr/libexec/netdata/plugins.d/qmail.plugin 1
62511 ?        S      0:15 /usr/libexec/netdata/plugins.d/svstat.plugin 1
62515 ?        S      0:01 /usr/libexec/netdata/plugins.d/parser.plugin 1
```
Note plugin processes with same PIDs (for example, 62193) mentioned with netdata having PID 61923 that received SIGTERM and exited!

Downgrade to 1.19 seems to solve the issue, plugins exit with netdata restart, no defunct process found.

##### Steps To Reproduce
Upgrade to version 1.20 and restart it.

##### Expected behavior
Expected to have
- no child processes in Z (<defunct>) state
- process signals (SIGUSR2 -12 and SIGTERM -15, as mentioned in documentation)
- close and clean chile plugin processes on exit

**Comment by Ferroin** [comment]
@ekexcello Can you please check and see if this is still an issue on the most recent nightly build. I _think_ most of this is fixed in the current nightlies, but I'm not certain, and it would be good to know before 1.21 is released on Monday even if we aren't able to fix it before then.

**Comment by Ferroin** [comment]
Just realized I didn't notice you're running on Gentoo. Can you give a bit more info about how you installed Netdata (from the official Portage tree, from our overlay, using one of the other install methods, something else).

**Comment by ekexcello** [comment]
Hello @Ferroin 
Netdata was installed from official Portage tree, last used was net-analyzer/netdata/netdata-1.20.0-r1.ebuild

**Comment by Ferroin** [comment]
@ekexcello Can you try with the live ebuild then (net-analyzer/netdata-9999)? I suspect this might be an issue with the ebuild and not our code, but I'm not 100% sure, and verifying if the live ebuild still exhibits this behavior or not will help confirm. Note that you'll have to manually unmask it in your Portage config before you can install it.

**Comment by ekexcello** [comment]
Tried to install testing version (9999), Netdata reported version `v1.20.0-302-g71290d9c`.
First two restarts were clear, no plugin remained after netdata exit. However, in several minutes attempt to restart netdata failed again as SIGTERM was ignored. In `ps` output there was failed plugin state `Z    18:35   0:00 [scanner.plugin] <defunct>`. After killing it, further restart attempts began to leave plugins after exit just in the way it was described. So, in current testing version this issue is present in very same way.

**Comment by ilyam8** [comment]
> scanner.plugin

it is custom plugin btw, we dont have `scanner.plugin`

> further restart attempts began to leave plugins after exit just in the way it was described

what plugins? Please give us the whole list of running plugins and list of `<defunct>` after restart

**Comment by ekexcello** [comment]
Hello @ilyam8 
I have seen problems with `scanner.plugin` and `nfacct.plugin`
However, plugins that remain after restart are not in 'defunct' state. They are simply detached from parent netdata process (that exits) and left 'as is'. It would be correct to say that simply all plugins including python and except of those that fall in `<defunct>` state immediately after start are left when main netdata process exits.

**Comment by ekexcello** [comment]
Plugins are:
```
/usr/libexec/netdata/plugins.d/tc-qos-helper.sh
/usr/libexec/netdata/plugins.d/svstat.plugin
/usr/libexec/netdata/plugins.d/qmail.plugin
/usr/libexec/netdata/plugins.d/python.d.plugin
/usr/libexec/netdata/plugins.d/nfacct.plugin
/usr/libexec/netdata/plugins.d/apps.plugin
/usr/libexec/netdata/plugins.d/parser.plugin
```
Some of them are custom but we have had no issue with them until last update.

**Comment by mfundul** [comment]
@ekexcello do you have the same problems if you install netdata from the official source as shown [here](https://docs.netdata.cloud/packaging/installer/#automatic-one-line-installation-script)?

**Comment by cakrit** [comment]
Closing due to no response, feel free to comment here if the issue persist.s

**Comment by ekexcello** [comment]
Sorry for delayed reply. We filed to reproduce this on any system other then Gentoo with installation from portage. Both Netdata installed with official script on Gentoo, on Debian 10, on Centos 7 and old Netdata 1.12 installed with apt on Debian 10 worked correctly with signals. However, the installation this issue was initially reported for still has problems with installed Netdata 1.22.1 and disabled custom plugin, so reason isn't clear yet.

**Comment by prologic** [comment]
If you are able to diagnose this, feel free to open a new issues with specific details we can look at. Thanks! :)
