### ISSUE TITLE
Special Characters in URLs in Registry Node Menu are Escaped

### ISSUE THREAD

**Issue by verdog** [netdata/netdata#8581]
##### Bug report summary

I am trying to set up a self-run registry. There are two machines: `antsy0`, which is the registry itself, and `antsy1`, which is part of the registry. The registry remembers dashboards I visit, but the urls it remembers are incorrect. It replaces some parts of the `http://` portion of their urls with escaped url versions.

![image](https://user-images.githubusercontent.com/25630273/78277987-60e15600-74e3-11ea-952e-72cb461d560d.png)

The actual urls are `http://antsy0.cs.wmich.edu:19999` and `http://antsy1.cs.wmich.edu:19999`. So it is replacing the `/` and `:` characters.

Clicking on a server name shows this:

![image](https://user-images.githubusercontent.com/25630273/78279379-6fc90800-74e5-11ea-9297-77267cc129a3.png)

And in the web console, I see this:

```
invalid URL detected: main.js:111:12
http%3A%2F%2Fantsy0.cs.wmich.edu%3A19999%2F#;theme=slate main.js:112:12
registry search call failed http://antsy0.cs.wmich.edu:19999 dashboard-react.js:628:13
```

The incorrect urls are also stored in the registry database on `antsy0`.

##### OS / Environment

Both machines are freshly created blank ubuntu vms with nothing except netdata installed on them.

```
$ uname -a; grep -Hv "^#" /etc/*release
Linux antsy0-dev 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

```

I have only changed the following configuration settings:
`antsy0` (the registry)
```
[registry]
        enabled = yes
        ...
        registry to announce = http://antsy0.cs.wmich.edu:19999

```

`antsy1`
```
[registry]
        enabled = no
        ...
        registry to announce = http://antsy0.cs.wmich.edu:19999
```

##### Netdata version

 
`netdata v1.20.0-291-nightly` on both machines.

##### Component Name

Registry/Web

##### Steps To Reproduce

1. Install netdata with `sudo ./netdata-installer.sh --stable-channel --disable-telemetry --dont-wait` on both machines.
2. Configure machines as above.

##### Expected behavior

The urls shown in the registry dropdown menu would not be escaped and would be clickable.

**Comment by wangyp0701** [comment]
The urls shown in the registry dropdown menu would not be escaped and would be clickable.
I have this problem, too

**Comment by leepeuker** [comment]
I have the same problem, running the same OS / Environment as described by @verdog 
Only difference is the netdata version (`v1.20.0-326-nightly`).

**Comment by jacekkolasa** [comment]
@verdog @wangyp0701 @leepeuker this problem should be fixed in current nightly version. Unfortunately the problematic urls will have to be removed from registry manually, i hope that's not a big problem

**Comment by prologic** [comment]
@jacekkolasa is this also related and possibly a duplicate https://github.com/netdata/netdata/issues/8736 ?

**Comment by jacekkolasa** [comment]
@prologic yes, thanks for pointing that out

**Comment by prologic** [comment]
@jacekkolasa Do you mind closing it approprialtely then? :)
