### ISSUE TITLE
Display any log file of the host in netdata

### ISSUE THREAD

**Issue by csvke** [netdata/netdata#8583]
Question summary
Display a log file in Netdata interface.
I’d like to, perhaps create a simple plugin, that display the log file of a serving running in the host machine with netdata installed. Because I am working on CorrElec that runs a very limited closed Linux district, I can only run netdata as a docker container.
Specifically, I’d like to display the log file of Kodi in that CoreELEC machine so I can read the log file remotely from another machine via a browser

OS / Environment
CoreElec / Debian

Component Name
N/A

Expected results
Read a log file, for example, /var/log/syslog and display it in the netdata dashboard

**Comment by ilyam8** [comment]
Hi @csvke, there is no support for reading/displaying generic logs in netdata.

**Comment by csvke** [comment]
thanks
