### ISSUE TITLE
Running Netdata within a Docker container. I am having trouble configuring the Netcloud service to have an opportunity to monitor each 'node' as it is running within a Docker container.

### ISSUE THREAD

**Issue by zacharygittery** [netdata/netdata#8587]
I have two docker containers running on two devices with netdata processes. I have one acting as the slave and one as the master. I am unable to use the 'sign in' button from the splash screen at host:port. I presume because I am running this service from within a docker container. I need some assistance figuring out how to get the Netcloud service running while maintaining Netdata running from within a Docker container.

Master is a RPi 4 running Raspbian (kernel 4.19).
Slave is Ubuntu 18.04 LTS (kernel 5.3.0-45-generic).

**Comment by zacharygittery** [comment]
UPDATE: I am currently unable to ping https://app.netdata.cloud/ from multiple machines.

Is there an issue with the net cloud service?

**Comment by cakrit** [comment]
Yes, the URL app.netdata.cloud shouldn't have made it to the master branch yet. @mfundul is preparing a PR and we'll have a new nightly to fix the issue today.

**Comment by cakrit** [comment]
Also, the fact that it's running in Docker is irrelevant. You can verify by installing instead the latest stable release, v1.20.
