### ISSUE TITLE
RFC: Upgrade Agent Telemetry

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8597]
##### Feature idea summary

Our current agent telemetry does not provide enough information about the user experience on the agent. We need raw data to understand which parts of the product are most important to users, which parts are heavily used and where we should focus our development effort.

As a company our success is measured by how well we build an agent that serves our user's needs. To do this effectively we need to understand how they use the agent so that we can continue to improve it in a way that reflect's our community's desires as well as our own as developers - we may have some assumptions about which parts of the agent deliver value but they are meaningless with real data to back them up.

Our telemetry is designed to build an aggregate anonymised view of the usage patterns of agents. All data is associated with a GUID that is randomly generated when the agent is installed. This allows us to estimate the population size of agents, and distinguish reports between different installations - this is vital to estimate the relative use / importance of features. The GUID is anonymous and tied to an installation rather than a user - we have no need for personal data and no desire to collect it.

The purpose of this issue is to have a discussion about how we develop our telemetry, what it collects, and why we need it. This helps us gain some feedback on how it is received and we reach a consensus about how to implement it. 

[@dim08, @vlvkobal, @thiagoftsm, @andrewm4894 and @aabatangle: I've tried to incorporate the points that you've already made - please jump in corrections, further suggestions and discussions]

##### Initial proposal

* Installation configuration
  1. OS / Platform
  1. Method of installation (source, binary, kickstart, docker pull etc)
  1. Install time (i.e. age of installation)
  1. Run-time (i.e. how old is the current netdata process)
  1. Update method
  1. Installer options, CFLAGs, compiler etc
  1. Satisfied build dependencies (i.e. which optional packages are available)
* Agent usage pattern
  1. Collectors in use, frequency, auto-detected options
  1. Exporting connectors used
  1. Enabled feature flags
  1. Code-paths in use
* Dashboard usage pattern
  1. Histogram of chart usage (i.e. what is most useful to users)
  1. Web server error log (e.g. 4xx and 5xx responses)
  1. Length of interaction
  1. Object label (i.e. where the user has clicked)
* Error logs
* Crash events
* Alarm events
  1. Frequency of alarm use / notification use
  1. Configured alarms (can we infer usefulness from this)

##### Some open questions

* How fine-grained can we make consent - can users opt out of particular categories / events or just globally from all telemetry?
* Do we need to capture events from all (consenting) agents or can we use a random sample?
* Which error logs should be collected and how do we sanitise / anonymise them?
* What kind of consent do we need before extracting logs and how should we approach it?
* Should we act as a conduit for OpenTelemetry to allow users to instrument their own applications (major increase in scope/effort - how much value does it add for users) ?
* What transport options should we pick for the telemetry (http endpoints, ACLK etc) ?
* How frequently should we upload telemetry ?
* Do we need to make any changes to our privacy policy ?
* Can we remove Google Analytics?

**Comment by thiagoftsm** [comment]
> Configured alarms (can we infer usefulness from this)
We are missing the interrogation for the question or verb and pronoun are inverted here. 

> Do we need to capture events from all (consenting) agents or can we use a random sample?

Both are valid, we can try to get the maximum available and after this to reduce them using Bayes' formulas, but we can also use other statistical methods to define the usage based in random sample.

> Which error logs should be collected and how do we sanitise / anonymise them?

@ilyam8 is our log parsing able to parse our `error.log`?

> How frequently should we upload telemetry ?
This has direct relationship with the sample collected, but we need to keep in mind that Netdata needs to run during a time for we know. Probably a good start would be when the database starts to rotate data.

> Do we need to make any changes to our privacy policy ?
We need to be very clear with our users, probably yes.

> Can we remove Google Analytics?
I think so.

**Comment by oyabun** [comment]
I’m very curious about usage pattern analytics. How do you plan to track the chart usage?  Interactions with charts? The number of charts? Average time on screen?. Since charts are something that are fundamentally consumed visually

**Comment by amoss** [comment]
> I’m very curious about usage pattern analytics. How do you plan to track the chart usage? Interactions with charts? The number of charts? Average time on screen?. Since charts are something that are fundamentally consumed visually

These are good questions. I would like to know what kind of usage model we should infer from the charts. It would be good to define the telemetry w.r.t. to the most valuable model of user interaction.

**Comment by PanosJee** [comment]
Will it both running in the front & back-end?

**Comment by ilyam8** [comment]
> @ilyam8 is our log parsing able to parse our error.log?

I wish our log format had structure (key=value key=value ...). `error.log` file is unparsable atm.

**Comment by PanosJee** [comment]
Try this https://cribl.io

**Comment by amoss** [comment]
> Will it both running in the front & back-end?

We have not designed it yet so this is open for discussion, but based on what we want to collect I think it must. In order to communicate the browser analytics via the same channel as the telemetry in the binary we should have a way for the front-end to deliver telemetry to the back-end (probably an endpoint in the Agent that the dashboard connects to) and then send all of the telemetry from the Agent to a central server.

**Comment by amoss** [comment]
This https://opentelemetry.io/ might be an interesting way to go.

**Comment by PanosJee** [comment]
> we should have a way for the front-end to deliver telemetry to the back-e (probably an endpoint in the Agent that the dashboard connects to) and then send all of the telemetry from the Agent to a central server.

Funny thing that for those without having enabled the cloud it is more likely to be able to communicate from the front-end rather than the back-end. Of course you can send more and in a more sophisticated way (batching etc) from the backend. 

A few ideas:
- Capturing user actions could be better served with something like [Segment's analytics.js](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/) but it will require a lot of instrumentation. We can direct the data to BigQuery for analysis later.
- Unfortunately the above won't capture front-end performance, luckily enough is quite easy to access **window.performance** and perhaps we should explore adding EUM (End User Monitoring as a feature to Netdata cloud
- Front end bugs: I think Bugsnag or Sentry are king here especially for getting meaningful stack traces from minimized React.
- We can use front-end to report a few things like the number of metrics collected since they already appear in the dashboard
- The problem with front-end based reporting is that we only get reports when users access the dashboard. I am really in favour to develop our own vs using Google Analytics 

Backend:
- We need to get stack traces but given that we have a C program we will get memory dumps and we will need a service to symbolicate. That ain't easy to develop. I think Sentry has [support](https://blog.sentry.io/2019/05/23/native-crash-reporting-symbol-servers-pdbs-sdk-c-c-plus-plus)

**Comment by amoss** [comment]
@PanosJee - Some really nice ideas.

* Front-end performance is not something that we had considered initially for telemetry but that would give us a lot of information about how to improve the user-interface. As this is the part that has the most influence on user perception of the Agent collecting performance data may be the most effective approach to improving the product.

* Stack traces are ideally what we need as it make bug replication much simpler for us so that we can push out fixes faster. I'll add a spike task to get somebody to evaluate Sentry along with other linux approaches (ABRT, BugBuddy etc).

* Likewise, we will schedule a spike to evaluate front-end analytics options as well (e.g. anlalytics.js) for use both in the Agent UI and the Cloud.

**Comment by cosmix** [comment]
Hold on guys. We're discussing session tracking for the cloud -- no point re-discussing the same thing here. Please sync with @oyabun @rduffield, they're already evaluating a few solutions.

**Comment by andrewm4894** [comment]
Can you add me to the conversations here too please as i'd like to be clear on what is and is not possible in terms of driving new data driven features that might relate to wider telemetry discussions.

**Comment by cosmix** [comment]
@PanosJee 

> We need to get stack traces but given that we have a C program we will get memory dumps and we will need a service to symbolicate. That ain't easy to develop. I think Sentry has support


This is not possible if users build their own version of the agent, only if we provide the binary.

**Comment by amoss** [comment]
It depends on how they build it:
* Completely manually from source -> we can't identify symbols.
* Via our installer -> we can wrap the build, i.e. build a debug version, capture symbols and then strip. The map that we capture can be used to decode stack traces from the "release" build.

**Comment by cosmix** [comment]
Correct @amoss

**Comment by ilyam8** [comment]
I think we need to add exporing to the telemetry to understand how many people use netdata as a metric collector and export data to some tsdb.

My asumption that it is always the case if it is not localhost or small home setups.

If they are most of our users then take a look at

> https://github.com/netdata/netdata/issues/8801

In that area using netdata is quite problematic.

**Comment by andrewm4894** [comment]
Wanted to add some Google Analytics alternatives to this thread for reference:

- https://github.com/PostHog/posthog
- https://piwik.pro/ (not sure this is really free or open source anymore)
- https://matomo.org/home/
- http://www.openwebanalytics.com/

Wider list here: https://en.wikipedia.org/wiki/List_of_web_analytics_software

**Comment by oyabun** [comment]
AFAIK Piwik === Matomo :)

From my side, I will love to use Segment plus Amplitude for example. 
Google Analytics works great for eCommerce and media, for products I prefer to use at least Segment. 
A good combination would be a CDP like a Segment and an ETL like Stich, and then integrate all the instrumentation through Segment API while we control the destination of data using other tools.  
In the worst scenario, at least Segment will do the work of sending the info to different destinations. 

Also, the Replay feature from Segment allows us to migrate to new tools without headaches.
https://segment.com/docs/guides/what-is-replay/

**Comment by andrewm4894** [comment]
+1 for Segment as a potential option too. 

Segment is becoming more and more popular in this space for sure and does have an export to data warehouse functionality which is very important for being able to do flexible custom product analytics. 

Less sure of how segment looks from a cost point of view.

**Comment by andrewm4894** [comment]
I have looked a bit more at this today and starting to form an opinion that something like a self hosted PostHog could be a good option. 

**Pros:**
- active open source project.
- seems like a developer friendly project as opposed to a more commercial/marketing focused type one.
- we can host it ourselves.
- has a Go integration/SDK https://posthog.com/docs/integrations/go-integration. For example we could replace registry with custom events sent to post hog. https://posthog.com/docs/tutorials/actions#using-custom-events-to-track-advanced-behaviors
- avoids re-inventing the wheel when comes to typical product analytics stuff like user sessions, custom events, custom dimensions etc. 

**Cons:** 
- need to maintain our own implementation and supporting infra.
- will it always have an open source option?

So we could have our own self hosted PostHog with a Postgres database we can look after and manage. 

- Front end events: https://posthog.com/docs/integrations/js-integration
- Backend custom events: https://posthog.com/docs/tutorials/actions#using-custom-events-to-track-advanced-behaviors + Go library.

**Comment by jamesefhawkins** [comment]
> will it always have an open source option?

Hey all, I'm one of the founders of PostHog. Just wanted to answer to give a little reassurance on this one (and it's fun working with other repos in GitHub directly...!)

We make [our strategy public](https://posthog.com/handbook/strategy/strategy) - being open source is our primary competitive differentiation - product analytics is a busy space, so we will forever have this :) [This post talks about how we think about sales](https://posthog.com/blog/product-led-growth ) too.

We put together a little guide on the [ethics of open source analytics](https://posthog.com/blog/open-source-telemetry-ethical) if you fancy a read, which covers different levels of anonymity.

If you're thinking of using Sentry, we have a [simple integration](https://posthog.com/docs/integrations/sentry-integration) for that too :)

**Comment by OdysLam** [comment]
Hey, @jamesefhawkins thanks for that writeup and welcome to our community :) 

I know for a certainty that we are going to look into these resources.

Since you are here, if you have any questions about Netdata, please do reach out! 

Cheers and welcome again to [Netdata Community](https://community.netdata.cloud).

**Comment by cakrit** [comment]
We have already switched over to using Posthog and are receiving eye opening data that will help us improve the agent in many ways.
