### ISSUE TITLE
Netdata Chrome Cookies Blocked due to missing Samesite attribute

### ISSUE THREAD

**Issue by XxLilBoPeepsxX** [netdata/netdata#8601]
##### Bug report summary

When running netdata v1.20.0-296-gdd0c4269 on Linux kali 4.9.80-Re4son-v7+ armv7l GNU/Linux, and port forwarding through a cisco E3000 router to allow public access to the dashboard, you are not able to sign up or sign in through any of the means provided on the dashboard to configure or register nodes, or claim the server, due to chrome blocking the cross-site cookies. 

Google Chrome developers inspection console states that:
 "A cookie associated with a cross-site resource at http://registry.my-netdata.io/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032." 

This makes it impossible to register or sign up as a new user from Windows 10 Google Chrome Version 80.0.3987.163 (Official Build) (64-bit), and it is the same issue on Microsoft Edge and Firefox. 

##### OS / Environment

```
Linux kali 4.9.80-Re4son-v7+(kali rolling) armv7l GNU/Linux
```

##### Netdata version

 
netdata v1.20.0-296-gdd0c4269
##### Component Name
 Web Component - Indicated as issue in Line 1 of index.html by the google chrome developers console. 

##### Steps To Reproduce

I discovered this bug from attempting to create and sign into an account through my dashboard and discovering that the page opened in a new window/tab that was supposed to be the login page would "load" for around 5 minutes, and then say "this site cannot be reached, connection timed out" and never allow me to actually sign in or create an account or anything like that. 
1. Install netdata on Kali Linux 
2. run `systemctl enable netdata && systemctl start netdata` (note: I am default signed in as the root user so sudo is not applicable)
3. `netdata run`
4. open preferred internet browser and access web dashboard
##### Expected behavior

Upon opening the web dashboard, the metrics and data load and all appear to be fully operational, until you attempt to sign in through the prompt at the bottom of the screen, the sign-in button in the top right corner, or by clicking the "nodes" button and opening sign-in through the nodes menu. Upon clicking any of the various sign-in methods, it opens a new tab/window with a link in it to app.netdata.cloud/(agent ID and my IP address and all that stuff that's personally-identifying after the initial URL) and then loads, spending between 10 seconds to 5 minutes with a blank screen, before getting to the page that says "this site cannot be reached, app.netdata.cloud took too long to respond." (See screenshot 2). 
Upon realizing there was something that wasn't operating correctly, I first went back to my server and made sure to fully update all packages and system functions, and verify the correct installation of the dependencies and the netdata program. The system is fully up-to-date and the installation is complete and without errors. I then restarted the netdata service and reloaded the web dashboard and tried again to sign-in. It didn't work, so my next step was to open developers' console in google chrome and see if there was a background site or service that was being blocked/hindered from being run by the site policy settings, and I discovered the cookies issue. (See screenshot 1) I went to the site settings and allowed all permissions, including insecure site content, and tried again, (and many more times) with no avail. After searching the internet and the other issues to no avail, I am now submitting this issue, seeking help. 

INCLUDED IMAGES:

1- Screenshot of Google Chrome Developers Console Error messages (due to my public IP address being exposed I did not include the whole screen, but if the developers wish to obtain the IP address to access my monitoring page it will be given privately.)

![image](https://user-images.githubusercontent.com/24320242/78454873-c7dc4780-7668-11ea-908f-33ffae1df64c.png)

2- Screenshot of the sign-in page that the netdata dashboard opens, in the state that I am repeatedly getting. 
![image](https://user-images.githubusercontent.com/24320242/78455117-7339cc00-766a-11ea-8c32-6db28b3bda75.png)

**Comment by ilyam8** [comment]
Hi @XxLilBoPeepsxX 

I see link is `app.netdata.cloud` which is not correct. It is fixed in https://github.com/netdata/netdata/pull/8598.

You need to update to the latest.

**Comment by XxLilBoPeepsxX** [comment]
I'm updating right now, I'll comment again with the results upon completion of the update. Thank you!

**Comment by XxLilBoPeepsxX** [comment]
Problem Solved, thank you!

**Comment by ilyam8** [comment]
dup of #8587
