### ISSUE TITLE
red hat enterpise 7 and oracle linux 7 have missing deps (Judy-devel,libuv-devel,python3-pymongo)

### ISSUE THREAD

**Issue by osde8info** [netdata/netdata#8602]
##### Bug report summary

yum install Judy-devel libuv-devel python3-pymongo 
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
No package Judy-devel available.
No package libuv-devel available.
No package python3-pymongo available.
Error: Nothing to do

##### OS / Environment

```
red hat 7.8
```

##### Component Name

installer

##### Steps To Reproduce

1. ...
install
2. ...
get
yum install Judy-devel libuv-devel python3-pymongo 
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
No package Judy-devel available.
No package libuv-devel available.
No package python3-pymongo available.
Error: Nothing to do

##### Expected behavior

should resolve deps

similar to photon os problem

**Comment by prologic** [comment]
Hi @osde8info It is not clear from your description how you installed NetData on your system. Please copy/paste the exact steps you took as we have CI that regularly tests installs on CentOS 7 and 8 (_we can't test RHEL easily_) so this should be working.

**Comment by osde8info** [comment]
red hat do do a FREE developer accounts just goto developer.redhat.com

i will double check on centos and oracle linux and send steps that failed

**Comment by etchesou** [comment]
Same error message on Oracle Linux 7 with all updates installed. Here the steps taken:

> [root@oracle12 ~]# bash <(curl -Ss https://my-netdata.io/kickstart.sh)  --stable-channel --disable-telemetry
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version:
 --- Fetching script to detect required packages... ---
[/tmp/netdata-kickstart-R4lxh2]# curl -sSL --connect-timeout 10 --retry 3 https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh  OK

 > --- Running downloaded script to detect required packages... ---
[/tmp/netdata-kickstart-R4lxh2]# /usr/bin/bash /tmp/netdata-kickstart-R4lxh2/install-required-packages.sh netdata Loading /etc/os-release ...
Unknown distribution ID: ol

> /etc/os-release information:
NAME            : Oracle Linux Server
VERSION         : 7.7
ID              : ol
ID_LIKE         : fedora
VERSION_ID      : 7.7

> We detected these:
Distribution    : fedora
Version         : 7.7
Codename        : 7.7
Package Manager : install_yum
Packages Tree   : rhel
Detection Method: /etc/os-release
Default Python v: 2 (will install python3 too)

>Searching for distro_sdk ...
Searching for autoconf_archive ...
WARNING
package autoconf-archive is not available in this system.
You may try to install without it.

>Searching for libz_dev ...
 > Checking if package 'zlib-devel' is installed...
Searching for libuuid_dev ...
 > Checking if package 'libuuid-devel' is installed...
Searching for libmnl_dev ...
 > Checking if package 'libmnl-devel' is installed...
Searching for libuv ...
 > Checking if package 'libuv-devel' is installed...
Searching for lz4 ...
 > Checking if package 'lz4-devel' is installed...
Searching for openssl ...
 > Checking if package 'openssl-devel' is installed...
Searching for judy ...
 > Checking if package 'Judy-devel' is installed...
Searching for python3_pymongo ...
 > Checking if package 'python3-pymongo' is installed...

>The following command will be run:

> >> IMPORTANT <<
    Please make sure your system is up to date
    by running:   yum update

>yum install Judy-devel libuv-devel python3-pymongo


>Press ENTER to run it >
yum install Judy-devel libuv-devel python3-pymongo
Loaded plugins: ulninfo
ol7_latest                                                                                                                               | 2.7 kB  00:00:00
ol7_optional_latest                                                                                                                      | 2.5 kB  00:00:00
No package Judy-devel available.
No package libuv-devel available.
No package python3-pymongo available.
Error: Nothing to do



>We are very sorry!

> Installation of required packages failed.

>What to do now:

 > 1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

>  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

>  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

 >          https://github.com/firehol/netdata/issues


> FAILED

> WARNING  It failed to install all the required packages, but installation might still be possible.

>Press ENTER to attempt netdata installation >

**Comment by k0ste** [comment]
This packages is present in EPEL.

```
Installed Packages
Name        : Judy
Arch        : x86_64
Version     : 1.0.5
Release     : 8.el7
Size        : 368 k
Repo        : installed
From repo   : epel
Summary     : General purpose dynamic array
URL         : http://sourceforge.net/projects/judy/
License     : LGPLv2+
Description : Judy is a C library that provides a state-of-the-art core technology
            : that implements a sparse dynamic array. Judy arrays are declared
            : simply with a null pointer. A Judy array consumes memory only when it
            : is populated, yet can grow to take advantage of all available memory
            : if desired. Judy's key benefits are scalability, high performance, and
            : memory efficiency. A Judy array is extensible and can scale up to a
            : very large number of elements, bounded only by machine memory. Since
            : Judy is designed as an unbounded array, the size of a Judy array is
            : not pre-allocated but grows and shrinks dynamically with the array
            : population.
```

**Comment by etchesou** [comment]
Enabling ol7_developer_EPEL repo resolves Judy and libuv-devel. But python3-pymongo is still no package available.

**Comment by ilyam8** [comment]
i dont really know why `python-pymongo` is required

**Comment by Ferroin** [comment]
pymongo is only needed if you need to monitor MongoDB instances using the python collector.

**Comment by ilyam8** [comment]
Yeah, there are a lot of packages you need monitor different services with python.d.plugin, but we dont install  them.

**Comment by prologic** [comment]
> red hat do do a FREE developer accounts just goto developer.redhat.com

Thank you I'll look into this and get our team to ensure we have subscriptions assuming we can get access to what we need locally.

**Comment by osde8info** [comment]
FYI
ibm red hat have FREE containers available at http://registry.access.redhat.com/ubi8/ubi:latest
oraclelinux have a FREE container at hub.docker.com

**Comment by ilyam8** [comment]
They are free to download, indeed. Have you tried it? Can you add repo/update from it, install stuff w/o active subscription?

**Comment by ilyam8** [comment]
Ok, i tested it, it works. What i did is:

- install https://hub.docker.com/_/oraclelinux/
- exec into container
- yum update/upgrade, install some packages

**Comment by ilyam8** [comment]
Yeah, it seems it works:

ol7.7:
 - image: https://hub.docker.com/_/oraclelinux/

 - add epel repo: 

> yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

```cmd
[root@aa738d765943 /]# yum search Judy-devel libuv-devel python-pymongo
Loaded plugins: ovl, ulninfo
========================================================================================= N/S matched: Judy-devel ==========================================================================================
Judy-devel.x86_64 : Development libraries and headers for Judy
php-pecl-judy-devel.x86_64 : php-pecl-judy developer files (header)

========================================================================================= N/S matched: libuv-devel =========================================================================================
libuv-devel.x86_64 : Development libraries for libuv

======================================================================================= N/S matched: python-pymongo ========================================================================================
python-pymongo.x86_64 : Python driver for MongoDB
python-pymongo-gridfs.x86_64 : Python GridFS driver for MongoDB

  Name and summary matches mostly, use "search all" for everything.
[root@aa738d765943 /]#
```

**Comment by ilyam8** [comment]
oh, and it is `python36-*` for ol7.7

```cmd
[root@aa738d765943 /]# yum search python36-pymongo
Loaded plugins: ovl, ulninfo
====================================================================================== N/S matched: python36-pymongo =======================================================================================
python36-pymongo.x86_64 : Python driver for MongoDB
python36-pymongo-gridfs.x86_64 : Python GridFS driver for MongoDB

  Name and summary matches only, use "search all" for everything.
```


```cmd
[root@aa738d765943 /]# yum search python36
Loaded plugins: ovl, ulninfo
========================================================================================== N/S matched: python36 ===========================================================================================
python36-cairo-devel.x86_64 : Libraries and headers for python36-cairo
python36-greenlet-devel.x86_64 : C development headers for python36-greenlet
boost-python36.x86_64 : Shared object symbolic links for Boost.Python 3
boost-python36-devel.x86_64 : Shared object symbolic links for Boost.Python 3
boost-python36-static.x86_64 : The Python3 Boost C++ static development libraries
libpeas-loader-python36.x86_64 : Python 36 loader for libpeas
python36-Cython.x86_64 : A language for writing Python 3.6 extension modules
python36-GitPython.noarch : Python3 Git Library
python36-HepMC3.x86_64 : HepMC3 Python 3 bindings
python36-HepMC3-rootIO.x86_64 : HepMC3 ROOT I/O module Python 3 bindings
python36-HepMC3-search.x86_64 : HepMC3 search module Python 3 bindings
python36-PyMySQL.noarch : Pure-Python MySQL client library
python36-PyYAML.x86_64 : YAML parser and emitter for Python 3.6
python36-SecretStorage.noarch : Python 3.x module for secure storing of passwords and secrets
python36-abimap.noarch : A helper for library maintainers to use symbol versioning
python36-aiosmtpd.noarch : Asyncio-based SMTP server
python36-argcomplete.noarch : Bash tab completion for argparse
python36-argh.noarch : Unobtrusive argparse wrapper with natural syntax
python36-arrow.noarch : Better dates and times for Python
...
...
```

**Comment by prologic** [comment]
@ilyam8 Thanks for testing! This is great news 🎉Do you want to take ownership of getting support for RHEL and Oracle Linux into our `install-required-packages.sh` and into our CI? :)

**Comment by ilyam8** [comment]
No 😅

**Comment by prologic** [comment]
Oookay then 😳

**Comment by osde8info** [comment]
workaround

kickstart_static64.sh does work for oracle linux 7 (but netdata still not listed as service in firewall-config)

kickstart_static64.sh does work for oracle linux 8 (but netdata still not listed as service in firewall-config)

**Comment by prologic** [comment]
This is still on our backlog, at this point I don't think I'll be able to get to this this week, but I welcome any PR that adds support for these two distros. You only need to modify `./packaging/install-required-packages.sh`. I would also test this on a Docker container/image and also add this to the `.github/workflows/build-and-install.yml` workflow. If @osde8info you put up some PRs for this I will happily review and accept them :)

**Comment by prologic** [comment]
@Ferroin I'm assigning this to you as I _believe_ the work you are doing to bundle libjudy will also solve this issue. 🙇‍♂️

**Comment by Ferroin** [comment]
Yes, it should be fixed by #9776 (and I've already got a 'Fixes' tag there for this issue).

**Comment by Ferroin** [comment]
#9839 will fix the pymongo error mentioned here.

**Comment by prologic** [comment]
As #9839 is merged I _think_ we can close this.
