### ISSUE TITLE
Raspberry Pi 4b Temp?

### ISSUE THREAD

**Issue by michaelnstl** [netdata/netdata#8603]
Question summary
Is it possible to have the temp of my raspberry pis show up on the dashboard?  I see others have asked this question, years ago - but couldn't see a definitive answer.

OS / Environment
Raspian - Latest and the latest version of NetData

**Comment by osde8info** [comment]
what do you see when you goto

http://localhost:19999/#menu_sensors_submenu_temperature;theme=slate;help=true

**Comment by michaelnstl** [comment]
It just refreshes the current (default) main page.  Shows nothing different.

**Comment by ilyam8** [comment]
hi @michaelnstl 👋 

If i remember it right `lm_sensors` doesnt work on raspberry pi, you need to use this bash module

> https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin/sensors

To get it working add `sensors=force` in the `charts.d.conf`

**Comment by michaelnstl** [comment]
So the link above told me to use this instead:
https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/sensors

But there is no instructions as to what I am support to change.  

Edit the python.d/sensors.conf configuration file using edit-config from the your agent's config directory, which is typically at /etc/netdata.

cd /etc/netdata   # Replace this path with your Netdata config directory, if different
sudo ./edit-config python.d/sensors.conf

What am i suppose to add to the file?
![Screen Shot 2020-04-05 at 5 29 13 PM](https://user-images.githubusercontent.com/62186018/78511566-4a493200-7763-11ea-8585-af3459198b69.png)

**Comment by ilyam8** [comment]
The link also says

> Unlike the python one, this module can collect temperature on RPi.

**Comment by ilyam8** [comment]
> sudo ./edit-config charts.d.conf

sensors=force

**Comment by michaelnstl** [comment]
Thank you - it works beautifully now.
