### ISSUE TITLE
on centos 8 / oraclelinux 8 / red hat 8 doesnt show up as a service in firewall-config

### ISSUE THREAD

**Issue by osde8info** [netdata/netdata#8604]
##### Feature idea summary
on centos 8 / oraclelinux 8 / red hat 8 show up as a service in firewall-config so you can set port by service and not have to manually enter 19999

##### Expected behavior
on centos 8 / oraclelinux 8 / red hat 8 show up as a service in firewall-config so you can set port by service and not have to manually enter 19999

**Comment by prologic** [comment]
> maybe this is a separate bug BUT netdata seems to need a lot of devel repos which wouldnt normally be on a prod server

We are working on this. This is part of ongoing work to get NetData available as native binary packages on more systems. We currently only support a small handful (somd Debian, Ubuntu, CentOS and Fedora).

For prod machines you could also consider installing the static binary by using the `kickstart_static64.sh` install option.

**Comment by Ferroin** [comment]
> > maybe this is a separate bug BUT netdata seems to need a lot of devel repos which wouldnt normally be on a prod server
> 
> We are working on this. This is part of ongoing work to get NetData available as native binary packages on more systems. We currently only support a small handful (somd Debian, Ubuntu, CentOS and Fedora).

And on this note, the CentOS packages should work on equivalent versions of RHEL without any issues. We don't yet have packages for CentOS 8 though, but we are actively working on it.

**Comment by osde8info** [comment]
FYI
ibm red hat have FREE containers available at http://registry.access.redhat.com/ubi8/ubi:latest
oraclelinux have a FREE container at hub.docker.com

**Comment by osde8info** [comment]
netdata also not listed as service in firewall-config on oracle linux 7

**Comment by prologic** [comment]
@osde8info Could you please help me understand what is meant by:

> netdata also not listed as service in firewall-config on oracle linux 7

I'm not familiar enough with RHEL/Oracle servers and the various management tools they provide. What does this mean? What is a "service in firewall-config"? What firewall-config? iptables? A web gui? How do we make this happen?

**Comment by osde8info** [comment]
firewall-config is a gui app used by CENTOS, ORACLELINUX & REDHAT that lists all systemd services and lets you enable disable ports by service name (and port num)

netdata does not appear in the list 

if i knew systemd better i could tell you why netdata is the ONLY systemd service not to appear in that list

**Comment by Ferroin** [comment]
I'm pretty sure this isn't a systemd issue. Unless I'm mistaken, `firewald` (the actual relevant component here) has it's own list of files defining services that it reads, and I'm certain we aren't installing such a file.

**Comment by osde8info** [comment]
sorry you are going way beyond my area of expertise here im afraid i cant help you any further

**Comment by ilyam8** [comment]
@Ferroin i guess it is `wontfix`?

**Comment by prologic** [comment]
> I think it is very unlikely we will be working in that direction

Why's that?

**Comment by Ferroin** [comment]
@ilyam8 In most cases, it's the application packages themselves that provide the files that `firewalld` reads to figure out what ports a service needs.

**Comment by prologic** [comment]
@Ferroin So we should be able to provide such a file too right?

**Comment by Ferroin** [comment]
> @Ferroin So we should be able to provide such a file too right?

Yes, though I have no real knowledge of how `firewalld` actually works beyond what's been stated above. Actually supporting this would be a good thing though, as it's rather popular among a number of distributions (the other big one is UFW, which would be good to support too).

**Comment by prologic** [comment]
Sorry for the dealy on this; but I I believe you want to do something like this on your system9s):

```#!sh
$ cat > /etc/firewalld/services/netdata.xml <<EOF
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>netdata</short>
  <description>Netdata real-time monitoring service</description>
  <port port="19999" protocol="tcp"/>
</service>
EOF
$ systemctl restart firewalld
```

I ran into this myself while doing some testing on CentOS 8 where pretty much everything inbound is blocked (_by default_) except for ICMP and SSH.

Please let me know if this helps! It is not clear to me (_yet_) whether we should be adding this to the Netdata installer or any of our packaging at this time. This is delving into the realms of "touching system configuration" a little too much IHMO.

**Comment by prologic** [comment]
Once you do this you also want to:

```#!sh
$ sudo firewall-cmd --zone=public --permanent --add-service=netdata
$ sudo sudo firewall-cmd --reload
```

**Comment by Ferroin** [comment]
Marking this as help wanted as it should (theoretically) be easy for someone who actually has a proper understanding of how `firewalld` works, but we currently are not likely to get to it any time soon ourselves.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
