### ISSUE TITLE
If I'm using a netdata run systemctl stop netdata.service，it will make a mistake.

### ISSUE THREAD

**Issue by xgxdmx** [netdata/netdata#8605]
If I'm using a netdata run systemctl restart netdata.service，it will make a mistake.

```cmd
● netdata.service - Real time performance monitoring
     Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Sun 2020-04-05 19:54:40 CST; 1s ago
    Process: 22454 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 22455 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 22456 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
    Process: 22457 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
    Process: 22458 ExecStart=/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D (code=dumped, signal=SEGV)
   Main PID: 22458 (code=dumped, signal=SEGV)

Apr 05 19:54:31 Star systemd[1]: Starting Real time performance monitoring...
Apr 05 19:54:31 Star systemd[1]: Started Real time performance monitoring.
Apr 05 19:54:31 Star netdata[22458]: SIGNAL: Not enabling reaper
Apr 05 19:54:31 Star netdata[22458]: 2020-04-05 19:54:31: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Apr 05 19:54:40 Star systemd[1]: Stopping Real time performance monitoring...
Apr 05 19:54:40 Star systemd[1]: netdata.service: Main process exited, code=dumped, status=11/SEGV
Apr 05 19:54:40 Star systemd[1]: netdata.service: Failed with result 'core-dump'.
Apr 05 19:54:40 Star systemd[1]: Stopped Real time performance monitoring.
```

I use Ubuntu Focal Fossa (development branch)

**Comment by xgxdmx** [comment]
netdata is the latest nightly version

**Comment by ilyam8** [comment]
hi @xgxdmx 

How did you install netdata?

**Comment by xgxdmx** [comment]
> hi @xgxdmx
> 
> How did you install netdata?

I use a script to install
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --enable-ebpf --nightly-channel --disable-telemetry --auto-update

**Comment by ilyam8** [comment]
Could you try to reinstall it? Dont forget to remove old install first.

My os is manjaro and i installed it using following command

> bash <(curl -Ss my-netdata.io/kickstart.sh) --nightly-channel --disable-telemetry --disable-cloud --install /opt

No problems for me.

And please share install log.

**Comment by xgxdmx** [comment]
> Could you try to reinstall it? Dont forget to remove old install first.
> 
> My os is manjaro and i installed it using following command
> 
> > bash <(curl -Ss my-netdata.io/kickstart.sh) --nightly-channel --disable-telemetry --disable-cloud --install /opt
> 
> No problems for me.
> 
> And please share install log.

Thank you very much, I added --disable-cloud successfully solved the problem.
But can you tell me what this parameter means, I don't seem to find it in the document.
--disable-cloud
Thank you very much.

**Comment by ilyam8** [comment]
it disabled netdata.cloud, i added it to make installing process faster.

I installed using your command

> bash <(curl -Ss my-netdata.io/kickstart.sh) --enable-ebpf --nightly-channel --disable-telemetry --auto-update

No problems too. 

I guess just clean install fixed the problem.
