### ISSUE TITLE
Netdata Cloud and Serverpilot Installation guide

### ISSUE THREAD

**Issue by MediaMaquina** [netdata/netdata#8608]
##### Question summary
I wonder how can i get netdata to work with serverpilot? I installed netdata but it times out with :19999.
Must i add netdata to nginx config or can it serve itself? I read the docs but i'm afraid to mess up a live server. Maybe someone that used Serverpilot can explain?
https://docs.netdata.cloud/docs/running-behind-nginx/
Won't `location /` mess up my live site?

Also, **Serverpilot configures Nginx as a reverse proxy of Apache** which means this won't be enough. i would also need to configure APACHE, i believe it won't work with just nginx.
##### OS / Environment
Ubuntu 16.04
##### Expected results
Load ip:19999 on the browser.

**Comment by kasparsj** [comment]
Same as running apps in other language than php:
https://serverpilot.io/docs/how-to-run-apps-in-any-language/

**Comment by MediaMaquina** [comment]
Nice thanks! I'll try that.
