### ISSUE TITLE
Update my-netdata.io

### ISSUE THREAD

**Issue by hazcod** [netdata/netdata#8609]
Hi, it seems my-netdata.io which functions as the online demo for newcomers still runs on v1.16.1, while the latest version is v1.21.0. Can this get updated? Thank you.

**Comment by prologic** [comment]
> Hi, it seems my-netdata.io which functions as the online demo for newcomers still runs on v1.16.1, while the latest version is v1.21.0. Can this get updated? Thank you.

Working on it. This is #7848 I ran into some issues early on but will get back to this tonight after having just released NetData  [v1.21.0](https://github.com/netdata/netdata/releases/tag/v1.21.0) today 🎉

Please follow #7848 for progress on this. I will close this as a dupe.
