### ISSUE TITLE
[SPIKE] Review the eBPF code

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#8612]
##### Investigate
- How the eBPF code interfaces with the kernel to collect statistics
  - How the eBPF VM works, and the syntax of the language for probes.
  - All of the eBPF code that has been written in kernel-collectors.
  - Differences between kprobes vs tracepoints and how they affect the code.
- For each kprobe/kretprobe review the function in the kernel being probed and the code around (callers and impact of execution).
- Storage structures used to store collected metrics
   - e.g. BPF_MAP_TYPE_HASH, BPF_MAP_TYPE_ARRAY etc
- How a collector reads the stored information and creates charts
- How the library is compiled to add support for different kernels
   - The per-kernel specific parts of the library for loading eBPF.
 
#### Expected Outcome
- Understand how to implement a new eBPF collector
  - Low level code + interface with a collector
- Understand eBPF impact (kprobes / tracepoints)  on resources
  - Memory, CPU,  I/O
- Better understand how eBPF could co-exist / replace / enhance the apps plugin
- Review / debug the low level eBPF code already in alpha-preview
   - Produce as comprehensive a review as possible within one sprint
   - Create PRs in which the review comments are added into the code as comments.
   - Parts that can not be reviewed within a sprint should be cut into small follow-on issues. 

#### Open Questions For The Planning Meeting

- How many people should work on this? - it will soak up a significant part of the team capacity.
- Should this be interleaved with other work or a full-time activity? - switching costs will be significant given that the code is completely different to Netdata.
- How much exploratory testing should the review include?

**Comment by thiagoftsm** [comment]
@stelfrag , I will suggest you start studying https://github.com/netdata/docs/pull/157 and after this you can go in this blog https://blogs.oracle.com/linux/notes-on-bpf-1 .
Any doubt, please, let me know.

**Comment by thiagoftsm** [comment]
I almost forgot the main source of examples that you have, please, also take a look on https://github.com/torvalds/linux/tree/master/samples/bpf . Unfortunately on kernel `5.4.30` it is not compiling all examples, but it is a very good place for you see working examples.

**Comment by thiagoftsm** [comment]
@underhood I have a doubt, can we close this issue?
