### ISSUE TITLE
[SPIKE] Review the eBPF code [WIP]

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#8616]
Get to know how the netdata ebpf collector is implemented. Also, review the ebpf library and examine all its existing linux kernel version support.

**Comment by thiagoftsm** [comment]
Please, read the comments https://github.com/netdata/netdata/issues/8612#issuecomment-609768299 and https://github.com/netdata/netdata/issues/8612#issuecomment-609776350 .

**Comment by amoss** [comment]
Closed in favour of #8612
