### ISSUE TITLE
How to configure node 'Service' type for Netcloud usage?

### ISSUE THREAD

**Issue by zacharygittery** [netdata/netdata#8624]
Quick question.

I am wondering how I can create a custom service type to assign to each node. This way I can group by Service in the Netcloud console.

Is there a readme somewhere in the github repo to do this that I am simply unaware of?

**Comment by ilyam8** [comment]
Hi @zacharygittery 

I think `host labels` will do

> https://docs.netdata.cloud/docs/configuration-guide/#netdata-labels

> This way I can group by Service in the Netcloud console.

Not sure this is supported atm but this is planned for sure.
