### ISSUE TITLE
[Mac OS 10.14] After Brew Install - Web Service Not Running

### ISSUE THREAD

**Issue by IvanShires** [netdata/netdata#8625]
##### Bug report summary
When trying to install NetData on Mac OS X 10.14, after running the install script (brew install NetData), the service appears to be running, but the web interface does not appear to be running.
##### OS / Environment
Late 2016 Macbook Pro, Mac OS X 10.14
```
Darwin Ivans-MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
```

##### Netdata version
 ```
Ivans-MacBook-Pro:~ 1vannn$ netdata -V
-bash: netdata: command not found
```
##### Component Name
Web Component / Installation Component

##### Steps To Reproduce
1. Ran the Brew Install script provided by https://docs.netdata.cloud/packaging/installer/methods/macos/ (brew install netdata)

##### Expected behavior
The Web Component to run with default settings
##### Output from Brew Services (https://github.com/Homebrew/homebrew-services)
```
Ivans-MacBook-Pro:~ 1vannn$ brew services list
Name       Status  User   Plist
netdata    started root   /Library/LaunchDaemons/homebrew.mxcl.netdata.plist
```
I also tried to start NetData without being the Root user

**Comment by prologic** [comment]
I am not able to reproduce this on my iMac running macOS 10.15 with Brew.

I stopped my existing netdata, uninstalled it and ran:

```sh
$ brew update
$ brew install netdata
$ brew services start netdata
```

And it worked just fine I could see the process running, the port listening and navigate to http://localhost:19999/

Can you help us understand more about what's going on on your system?

**Comment by ilyam8** [comment]
@prologic this happens after upgrade

**Comment by IvanShires** [comment]
@prologic Here is the output, but I'm really not sure what happened the first time. I just removed it and reinstalled following the directions. No clue what must've happened. Must've been my fault somewhere along the lines. Sorry about that! Issue resolved.

```
Ivans-MacBook-Pro:~ 1vannn$ brew update
Updated 3 taps (homebrew/core, homebrew/cask and jzelinskie/duckdns).
==> Updated Formulae
autopep8        dvc             groonga         ncview          pkg-config
aws-cdk         eccodes         libaacs         netcdf          prettier
awscli          ejabberd        libdvdnav       newman          starship
baidupcs-go     frugal          mapnik          oauth2_proxy    terragrunt
bazel           gdal            minetest        omniorb         vala
botan           gdcm            monolith        openimageio     visp
contentful-cli  gmt             nano            par             vtk
crystal         gmt@5           nco             pcl
==> Updated Casks
alt-tab                    manictime                  torguard
autovolume                 marvin                     tuple
blitz                      mdimagesizemdimporter      vagrant-vmware-utility
caprine                    sonic-pi                   vidrio
coconutbattery             sqlpro-for-mssql           webstorm
epubmdimporter             sqlpro-for-sqlite          zalo
fastonosql                 sqlpro-studio              zettelkasten
firefox                    teamwire
malwarebytes               timelane
==> Deleted Casks
strongvpn-client
```
```
Ivans-MacBook-Pro:~ 1vannn$ brew uninstall netdata
Uninstalling /usr/local/Cellar/netdata/1.20.0... (472 files, 7.2MB)
Error: Could not remove netdata keg! Do so manually:
  sudo rm -rf /usr/local/Cellar/netdata/1.20.0
Ivans-MacBook-Pro:~ 1vannn$ sudo rm -rf /usr/local/Cellar/netdata/
Password:
Ivans-MacBook-Pro:~ 1vannn$ ls /usr/local/Cellar/
aircrack-ng	gdbm		lame		mysql-client	python@2
beanstalkd	geoip		leptonica	ntopng		readline
cairo		gettext		libffi		numpy		redis
cmake		glib		libpng		openalpr	rrdtool
dnsmasq		graphite2	libtiff		opencv@2	sqlite
duckdns		harfbuzz	libtool		openexr		telnet
eigen		heroku		libuv		openssl		tesseract
ffmpeg		heroku-node	log4cplus	openssl@1.1	unixodbc
fontconfig	icu4c		lz4		pango		wget
fping		ilmbase		msodbcsql	pcre		x264
freetype	jpeg		msodbcsql17	pixman		xvid
fribidi		json-c		mssql-tools	python		xz
Ivans-MacBook-Pro:~ 1vannn$ 
```
```
Ivans-MacBook-Pro:~ 1vannn$ brew install netdata
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/netdata-1.21.0.mojave.bottl
Already downloaded: /Users/1vannn/Library/Caches/Homebrew/downloads/36050ff777630e314fc8268d492d4e744ae13de20aad209dae868191882e71c0--netdata-1.21.0.mojave.bottle.tar.gz
==> Pouring netdata-1.21.0.mojave.bottle.tar.gz
==> Caveats
To have launchd start netdata now and restart at login:
  brew services start netdata
Or, if you don't want/need a background service you can just run:
  /usr/local/sbin/netdata -D
==> Summary
🍺  /usr/local/Cellar/netdata/1.21.0: 475 files, 7.3MB
Ivans-MacBook-Pro:~ 1vannn$ brew services start netdata
==> Successfully started `netdata` (label: homebrew.mxcl.netdata)
```

**Comment by prologic** [comment]
> @prologic this happens after upgrade

Oh I somehow missed that part :/

**Comment by snorkrat** [comment]
Sorry to resurrect this old issue, but I seem to be having a similar issue.  I used `brew upgrade` and noticed that netdata wasn't working after that.  By not working I mean that the webUI would look like it was constantly trying to load but not displaying anything.  I then performed the following, in order: `brew stop netdata` `brew uninstall netdata` `brew update` `brew install netdata` `brew start netdata` but no success.  I can't seem to figure out what is wrong.  In my netdata.conf file I have made sure the web user and group are correct, and the directory /usr/local/share/netdata/web also has these same user and group permissions.

Is there anything that I'm missing?

**Comment by snorkrat** [comment]
Figured it out.  Looking through the logs I could see that it was trying to load cached files in `/usr/local/var/cache/netdata/` I assumed these were left over from my previous netdata install.

I then uninstalled netdata, deleted the `/usr/local/var/cache/netdata/` folder completely, installed netdata again via homebrew and all is working.
