### ISSUE TITLE
Fix timestamp problems in LWT for unexpected disconnects.

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8629]
##### Problem summary

When the agent registers its LWT the timestamp in the top-level dictionary cannot be set to a real value as we do not know in advance when the message will be sent. This creates a message ordering problem in the Cloud.

#### Proposed fix

* The agent will pick and store a connection time when it initiates the connection.
* The timestamp in the LWT will be set to the connection time + 1µs.
* A new pair of keys will be added to the top-level dictionary for all outgoing message.
  1. `connect-secs` -> the second component of the connection time.
  1. `connect-us` -> the microsecond component of the connection time.

The connection time stored in the new keys will act as a monotonically increasing session-id for identifying which session the message originated in and allow a total ordering of connect  / disconnect events in the event that they are delivered out of order.

**Comment by fracasula** [comment]
LGTM. Only thing is that I'd probably name the new pair of keys it as follows for consistency:

```
connect
connect-offset-usec
```

**Comment by fracasula** [comment]
One thing that might be worth mentioning in the docs - once we get to update them - is that on netsplits VerneMQ does not guarantee the delivery of LWT messages and that having the `connect` as a "session-id" would help us mitigate issues related to that on the cloud.
