### ISSUE TITLE
RFC: Categorization of GitHub issues

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8630]
To be able to monitor our backlog and prioritize work while executing our roadmap, we are suggesting the following top-level grouping of GitHub feature requests in this repo, and any other repos related to netdata:

- Status=Closed, Label=wontfix -> Issues we've decided shouldn't become part of netdata.
- Status=Open:
  - Label=help wanted, Assignee=NULL -> Issues we agree would improve netdata, that the maintainers will not work on. It's up to the community to contribute the relevant fix/improvement.
  - Label=blocked, Assignee=Maintainer -> Issues that require user or product input. Can't be planned until the blocker is removed
  - Assignee=Maintainer -> Issues that aren't in the immediate roadmap, but that we want to work on eventually (could be low priority bugs). Where possible, these issues MAY be linked to Epics in the internal netdata/product and categorized under a general initiative.
  - Label=roadmap, Assignee=Maintainer -> Issues that are being planned for delivery in the short to medium term (within the next 9-12 months). These issues MUST  be linked to Epics in the internal netdata/product and categorized under a general initiative. Those Epics MUST appear on the company roadmap, along a time axis. 
  - Label=needs triage -> Issues that must be triaged and categorized as shown above.

We didn't go into details regarding bugs. My suggestion is for Low and Medium priority bugs to follow the categorizations above, high priority bugs are picked up and worked on ASAP, without a need to link to Epics etc. 

cc @cosmix, @dim08 , @amoss and obviously open to comments/suggestions.

**Comment by cakrit** [comment]
As for discussions like this one, they are eventually closed automatically, by the netdatabot.

**Comment by amoss** [comment]
Overall it looks good and should help organize the issues in the repo. One minor point, having a Maintainer assigned to every issue doesn't seem to fit well with areas of responsibility and implies that each piece of work is owned by one person. If we are moving towards larger scale features that define work for the team is this still appropriate? What I have in mind is that we should be defining the work at the far end of our roadmap, even if we don't know who will be assigned to it.

**Comment by cosmix** [comment]
I agree with @amoss

**Comment by cakrit** [comment]
So how about the following?

- Status=Closed, Label=wontfix -> Issues we've decided shouldn't become part of netdata.
- Status=Open:
  - Label=help wanted -> Issues we agree would improve netdata, that the maintainers will not work on. It's up to the community to contribute the relevant fix/improvement.
  - Label=blocked -> Issues that require user or product input. Can't be planned until the blocker is removed
  - Label=backlog -> Issues that aren't in the immediate roadmap, but that we want to work on eventually (could be low priority bugs). Where possible, these issues MAY be linked to Epics in the internal netdata/product and categorized under a general initiative.
  - Label=roadmap -> Issues that are being planned for delivery in the short to medium term (within the next 9-12 months). These issues MUST  be linked to Epics in the internal netdata/product and categorized under a general initiative. Those Epics MUST appear on the company roadmap, along a time axis. 
  - Label=needs triage -> Issues that must be triaged and categorized as shown above.

**Comment by amoss** [comment]
Looks good.

**Comment by vlvkobal** [comment]
Please specify what does mean _"product input"_. I suspect I get it wrong.

**Comment by cakrit** [comment]
> Please specify what does mean _"product input"_. I suspect I get it wrong.

I updated that line to make it clearer @vlvkobal, thanks.

So since we agreed on this, I'm closing it. @dim08  you can proceed with the creation of the new labels and the not enviable task of reclassifying all issues.
