### ISSUE TITLE
Allow to close browser print dialog on Print view

### ISSUE THREAD

**Issue by David-Lor** [netdata/netdata#8631]
##### Feature idea summary

When using the Print view, on the new popup window -where a snapshot is rendered-, a browser Print dialog is opened, to allow exporting the Netdata snapshot to PDF. But -at least on Firefox- when the browser Print dialog is closed, the whole window closes.

This does not allow other actions, like using the Save page as... function of the browser (printing as PDF is not always the best way to go).

##### Expected behavior

When closing the browser Print dialog, the Netdata popup window shall remain opened.

**Comment by ilyam8** [comment]
That is fixed
