### ISSUE TITLE
alarm template 'on' line match exact chart

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#8634]
##### Question summary
We have to monitor and create an alarm on number of mysql (mariadb/galera) running threads.
We run two SQL instances on same hardware, should monitor them all.
However, if we define notification _template_, not _alarm_, two alarms are created for each instance (4 alarms for 2 instances!) instead of expected one per instance:
```
template: threads_running
      on: mysql.threads
lookup: average -10s of running
```
leads to creation of alarms on _two charts_:
 - mysql_local-MariaDB-Galera.threads
 - mysql_local-MariaDB-Galera.threads_creation_rate

instead of creation of _mysql_local-MariaDB-Galera.threads_ only. Moreover, as threads_creation_rate has no component named 'running', second alarm has empty value.

Indeed, both charts _Threads (mysql_local_MariaDB_Galera.threads)_ and _Threads Creation Rate (mysql_local_MariaDB_Galera.threads_creation_rate)_ have very same context named mysql.threads.
So, we have to define _alarms_ using chart names instead of _templates_. Is there a way to create template that would only match one chart for each monitored mysql instance? Again, we have two on same hardware, but only this chart is defined in the way causing such issue, other alarm templates are shared between instances...

##### OS / Environment
Linux 4.19.107-gentoo x86_64 AMD Opteron 6376
netdata-1.20.0
##### Component Name
Health
##### Expected results
It would be convenient to have syntax that explicitly mentiones whether template uses wildcard or not.

**Comment by ilyam8** [comment]
@ekexcello 👋 

template applied on chart context


https://github.com/netdata/netdata/blob/3c4cb607d6b77b9fd9076dd6662d3bc13975c871/collectors/python.d.plugin/mysql/mysql.chart.py#L341-L354


both these charts have same context

`threads_creation_rate` chart should have different context. It is a bug. Are you willing to make a PR?

**Comment by thiagoftsm** [comment]
Hi @ekexcello ,

The `on` used with alarm `template` is used with contexts as you can see on this link https://docs.netdata.cloud/health/reference/#alarm-line-alarm-or-template . 
Thank you to find this bug!

**Comment by ekexcello** [comment]
Strange, but 1.21.1 doesn't have this fixed (chart context is still same) and pull request #8636 is now [reverted.](https://github.com/prologic/netdata/commit/33e40afccb5ffbd36e1a6f0b9fe7250d13a7eda5) Will it be accepted back on next release?

**Comment by thiagoftsm** [comment]
@Ferroin did you revert some features before we release `1.21.1`?

**Comment by Ferroin** [comment]
Yes, v1.21.1 contains onlythe stuff that was in v1.21 plus the fix for the bug that prompted it. All the changes that were reverted are back in master again now though.

**Comment by thiagoftsm** [comment]
Thank you! @ekexcello we will release this with 1.22 in the next days.

**Comment by ekexcello** [comment]
Thank you, @thiagoftsm !
