### ISSUE TITLE
Multi Server monitor Dashboard.

### ISSUE THREAD

**Issue by AencoCTO** [netdata/netdata#8640]
On the main netdata web site, you have multi dashboard view, ie london. after looking at the source, their is a lot of chunking going on, and its like a minefield of code to try and pull together a working dashboard multi site monitor, in addition, using cloud service is not workable, since our servers are deep inside firewalls. with that in mind, would it be possible to either post, make or link to a guide that would make it possible to build a html dashboard for multi-server monitoring? or is there a project that has already done this that we can pull and interrogate?
Regards

**Comment by stevenans9859** [comment]
Ok
