### ISSUE TITLE
Easy way to disable Stock Alarms

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#8641]
##### Feature idea summary
Allow disabling stock health config alarms. Currently trick of setting `stock health configuration directory` to non-existent dir can do that. However, that is a little bit 'hacky'.

##### Expected behavior
Simple non-hacky way to disable all stock alarms for users who want to use only custom alarms. Useful also for developers.
Introduce flag `disable stock health configuration`

**Comment by thiagoftsm** [comment]
To insert this flag inside `netdata.conf` is one step for this, but it will be good case we also can bring this feature to our web management API.

**Comment by ilyam8** [comment]
Adding `disable stock health configuration` configuration option looks good to me.
