### ISSUE TITLE
Netdata installer needs to install specific version of `kernel-collector` repository

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8650]
##### Feature idea summary
Right now `netdata-installer.sh` is always getting the latest version of `kernel-collector` repository, this can become a problem with new features and old installations.

The netdata-installer needs to do with eBPF the same we are doing with go.d.

##### Expected behavior
We will have parity between Netdata versions and kernel collector versions

* (@core-sre) Netdata-installer will download a package containing:
  - libebpf [2 versions; <4.15, 4.15+]
  - libnetdataebpf (our shared library) [single version]
  - ebpf programs [single version of processes, sockets]

* (@thiagoftsm) The collector (plugin) will make a decision at run-time to map the current kernel version onto the appropriate files.

Expected: Thursday nightly to release ebpf

**Comment by Ferroin** [comment]
Handling for this should ideally be consistent with how we handle LWS/mosquitto, the new dashboard, and the go.d plugin.

**Comment by ilyam8** [comment]
ideally as `go.d plugin` - do not download if actual version == current

**Comment by prologic** [comment]
I agree with both @Ferroin and @illes -- When @thiagoftsm and I originally did this work we missed a few things (_because we were iterating quickly_): We need to:

- [ ] Add support for integrity checks for what we download like libwebsockets/libmosquitto does.
- [ ] Only download/install if there is a newer version

**Comment by cosmix** [comment]
Since this is slated for 1.23, this is low priority for now.
