### ISSUE TITLE
eBPF Black Box Testing

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#8651]
##### Feature idea summary

Testing on at least following distributions should be performed:
- Debian 10
- CentOS 7
- Ubuntu 18.04
- alpine 3.9.4

**Comment by underhood** [comment]
####Noticed issues:

- On Fedora 31 it tries to install shared libs into `/usr/lib64/iscsi`
- `--install` prefix of installer doesn't work well with eBPF

####Good News:
- Debian seems to be working _(Linux debian 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux)_

**Comment by thiagoftsm** [comment]
Probably we need to improve the detection about the directories the OS uses to install the shared libraries, it looks like that some distributions are adding different directories inside their `/etc/ld.so.conf` .
We copy the main shared library for the listed shared library directory to be sure that the loader will find them.
Right now we are supporting `4.19.105`, `4.19.104`, `4.19.6` and `4.19.98`. We expect Debian to fail, if and only if, they decide to use another different kernel patch, considering that they will continue using `4.19`.

**Comment by mfundul** [comment]
In `CentOS Linux release 7.7.1908` and kernel `3.10.0-1062.1.1.el7.x86_64` I get:

```
 --- eBPF Kernel Collector (opt-in) --- 
 Using eBPF Kernel Package built against Linux 4.14.171
 Downloading check-kernel-config.sh ...
[/root/netdata]# chmod +x /tmp/netdata-ebpf-xy4SOL/check-kernel-config.sh 
 OK   

[/root/netdata]# /tmp/netdata-ebpf-xy4SOL/check-kernel-config.sh 
 OK   

 --- Installing eBPF plugin --- 
 Using eBPF Kernel Package built against Linux 4.14.171
 Detected GLIBC
netdata_ebpf-4_14_171-glibc.tar.xz: OK
 Extracting netdata_ebpf-4_14_171-glibc.tar.xz ...
 Finding suitable lib directory ...
[/root/netdata]# cp -a -v /tmp/netdata-ebpf-zxkWRb/usr/lib64/libbpf_kernel.so /usr/lib64/mysql 
'/tmp/netdata-ebpf-zxkWRb/usr/lib64/libbpf_kernel.so' -> '/usr/lib64/mysql/libbpf_kernel.so'
 OK   

[/root/netdata]# cp -a -v /tmp/netdata-ebpf-zxkWRb/libnetdata_ebpf.so /usr/libexec/netdata/plugins.d 
'/tmp/netdata-ebpf-zxkWRb/libnetdata_ebpf.so' -> '/usr/libexec/netdata/plugins.d/libnetdata_ebpf.so'
 OK   

[/root/netdata]# cp -a -v /tmp/netdata-ebpf-zxkWRb/pnetdata_ebpf_process.o /usr/libexec/netdata/plugins.d 
'/tmp/netdata-ebpf-zxkWRb/pnetdata_ebpf_process.o' -> '/usr/libexec/netdata/plugins.d/pnetdata_ebpf_process.o'
 OK   

[/root/netdata]# cp -a -v /tmp/netdata-ebpf-zxkWRb/rnetdata_ebpf_process.o /usr/libexec/netdata/plugins.d 
'/tmp/netdata-ebpf-zxkWRb/rnetdata_ebpf_process.o' -> '/usr/libexec/netdata/plugins.d/rnetdata_ebpf_process.o'
 OK   

[/root/netdata]# ln -v -f -s /usr/lib64/mysql/libbpf_kernel.so /usr/lib64/mysql/libbpf_kernel.so.0 
'/usr/lib64/mysql/libbpf_kernel.so.0' -> '/usr/lib64/mysql/libbpf_kernel.so'
 OK   
```
It uses `/usr/lib64/mysql/` for some reason.

The ebpf plugin does not work:
```
2020-04-10 05:55:40: netdata ERROR : PLUGINSD[ebpf_process] : read failed: end of file
2020-04-10 05:55:40: netdata ERROR : PLUGINSD[ebpf_process] : '/usr/libexec/netdata/plugins.d/ebpf_process.plugin' (pid 18180) disconnected after 0 successful data collections (ENDs).
2020-04-10 05:55:40: netdata ERROR : PLUGINSD[ebpf_process] : child pid 18180 exited with code 1.
2020-04-10 05:55:40: netdata ERROR : PLUGINSD[ebpf_process] : '/usr/libexec/netdata/plugins.d/ebpf_process.plugin' (pid 18180) exited with error code 1 and haven't collected any data. Disabling it.
2020-04-10 05:55:40: netdata INFO  : PLUGINSD[ebpf_process] : thread with task id 18156 finished
```

**Comment by thiagoftsm** [comment]
@mfundul as we talked on Slack, @Ferroin will bring the missing changes on `netdata-installer.sh`.

It is using `/usr/lib64/mysql/` , because we need to update the logic used to detect directories where the system loads the shared libraries.

**Comment by Ferroin** [comment]
> It is using /usr/lib64/mysql/ , because we need to update the logic used to detect directories where the system loads the shared libraries.

No, we need to completely redo the handling for this from scratch. We can't just use system search paths because:

* It violates required behavior for prefixed installs (including the static installer).
* Our library name isn't sufficiently unique that we can guarantee that it won't overwrite something else the user miht want.

This is a case where we unfortunately have to use RPATH and modify it at install time.

**Comment by Ferroin** [comment]
As I mentioned during the standup today, I think I've found a way to handle the RPATh stuff here. I need to do a bit more research into the tooling and verify that I actually understand how RPATH works  (specifically whether it supplements or replaces the normal linker search path configuration), but should hopefully have this ready for testing by the end of the day on Monday.
