### ISSUE TITLE
not receiving alert notifications for CLEARED alarms

### ISSUE THREAD

**Issue by luckman212** [netdata/netdata#8653]
- Netdata **v1.20.0-326-nightly**
- Ubuntu **19.10**

I set up [Health check Alarm notifications today](https://docs.netdata.cloud/health/notifications/), and it went by the book. Alerts going to Twilio SMS and MS-Teams. Everything works. The only thing is, I am not getting alert notifications when the alarms are **CLEARED**. (These are `fping` monitored hosts).

Is this normal/expected? Some config I have to tweak? I saw some mention of `options: no-clear-notification` so I scoured my disk for this setting in all *.conf files but only found a single instance of it in `/usr/lib/netdata/conf.d/health.d/net.conf` under `template: 10s_received_packets_storm` which doesn't seem related.

Thanks for any tips!

**Comment by luckman212** [comment]
**update:** the CLEARED alert eventually came through at 1:00pm on the dot, which was 20 min after the fact (the actual alarm cleared at 12:40pm). Seems like an hourly cronjob may be rolling these up?

Any way to get them immediately?

**Comment by ilyam8** [comment]
@luckman212 👋 

Probably `delay`? 

> https://docs.netdata.cloud/health/reference/#alarm-line-delay

**Comment by luckman212** [comment]
@ilyam8 That looks promising, will have to set some time aside to read through it, thanks

**Comment by ilyam8** [comment]
I assume you have delay down option.

**Comment by mfundul** [comment]
I have problems with `alarm-notify.sh` which may be related to this. I'm getting:
```
2020-04-08 21:38:39: alarm-notify.sh: INFO: sent email notification for: CentOS-7-mfundul ipv4.tcphandshake.ipv4_tcphandshake_last_collected_secs is WARNING to 'root'
curl: (3) <url> malformed
2020-04-08 21:38:39: alarm-notify.sh: ERROR: failed to sent CUSTOM_INFO notification for: CentOS-7-mfundul ipv4.tcphandshake.ipv4_tcphandshake_last_collected_secs is WARNING to   with error code 3.
```
which I've traced back to https://github.com/netdata/netdata/commit/3c4cb607d6b77b9fd9076dd6662d3bc13975c871

**Comment by mfundul** [comment]
It doesn't work due to thess lines:
```
# -----------------------------------------------------------------------------
# send the EVENT to Dynatrace
send_dynatrace "${host}" "${chart}" "${name}"  "${status}"
SENT_DYNATRACE=$?
```
If I comment this one out like this:
```
#send_dynatrace "${host}" "${chart}" "${name}"  "${status}"
```
It's fixed.

Is this supposed to be unconditional?

**Comment by ilyam8** [comment]
I see logic is

check if method is set

https://github.com/netdata/netdata/blob/6b63ba8fe52b490f83c1983645c16f1f49591149/health/notifications/alarm-notify.sh.in#L518-L523

call the func

https://github.com/netdata/netdata/blob/6b63ba8fe52b490f83c1983645c16f1f49591149/health/notifications/alarm-notify.sh.in#L2464-L2466

Return immediately in func if method is disabled (missing part, no return - added in https://github.com/netdata/netdata/pull/8654)

https://github.com/netdata/netdata/blob/6b63ba8fe52b490f83c1983645c16f1f49591149/health/notifications/alarm-notify.sh.in#L1915-L1921

**Comment by olivluca** [comment]
It appears that the delay down only affects the notification but not the alarm log in the dashboard. Shouldn't the delay also affect what's shown on the dashboard?

**Comment by thiagoftsm** [comment]
Hi @olivluca ,

What is the Netdata version running on your computer?

best regards!

**Comment by olivluca** [comment]
v1.21.1

**Comment by thiagoftsm** [comment]
Hi @olivluca ,

I was testing now in my environment, and I observed that I can receive the clean alarms:

![err56](https://user-images.githubusercontent.com/49162938/81125775-abae1d80-8f28-11ea-8e40-1a009ae3fc6c.png)

Please, could you give me the alarm that is not sending `clear` notification for you?

best regards!

**Comment by olivluca** [comment]
I receive them too but there's a discrepancy between the dashboard (where the alarm shows as cleared immediately) and the clear notification (which is sent only after the `delay down` time has passed)

**Comment by olivluca** [comment]
E.g: this alarm (fping.ftpserver_quality) shows as cleared at 9:01 on the dashboard, but the notification was sent at 9:31

![image](https://user-images.githubusercontent.com/8250980/81150756-995fce00-8f80-11ea-80fa-390b837425a7.png)

![image](https://user-images.githubusercontent.com/8250980/81150778-9fee4580-8f80-11ea-81ac-e7cb31c222fb.png)

**Comment by thiagoftsm** [comment]
Hi @olivluca ,

Firstly I apologize the delay to answer you, but we are having busy days.
Inside your `error.log` we have log for both events, the packet loss and the time that we send data to alert, please can you confirm that the times that we see in these screenshots are the same inside your `error.log`?
Another doubt, is this netdata receiving streams from other slaves?

Best regards!

**Comment by olivluca** [comment]
> Inside your `error.log` we have log for both events, the packet loss and the time that we send data to alert, please can you confirm that the times that we see in these screenshots are the same inside your `error.log`?

Yes

```
2020-05-06 09:31:08: alarm-notify.sh: INFO: sent alerta notification for: helpdesk fping.ftpserver_quality.packet_loss is CLEAR to 'Production'
2020-05-06 09:31:08: alarm-notify.sh: INFO: sent email notification for: helpdesk fping.ftpserver_quality.packet_loss is CLEAR to 'root'

```
> Another doubt, is this netdata receiving streams from other slaves?

No.

**Comment by olivluca** [comment]
Note that the difference (30 minutes) is exactly the `delay down` in the rule for that alarm.

**Comment by thiagoftsm** [comment]
Considering what we are reading in the logs and screenshots, I think the dashboard is probably doing a wrong math to convert the timestamp that it receives from Unix epoch to user value. @jacekkolasa , please, can you take a look on this?

A last doubt, is your computer configured in a timezone that is not an integer value? For example, GMT 4:30?

**Comment by olivluca** [comment]
I think it's not that: I noticed this problem because when I click on the alerta message it leads me to the netdata dashboard and there is no alarm there.
At first I though that netdata wasn't sending the notification but the I realized it sent it after the delay.

Besides the start time of the alarm (not shown in the screenshot) is correct.

And, no, my timezone is gmt +2:00

**Comment by thiagoftsm** [comment]
> I think it's not that: I noticed this problem because when I click on the alerta message it leads me to the netdata dashboard and there is no alarm there.
> At first I though that netdata wasn't sending the notification but then I realized it sent it after the delay.
> Besides the start time of the alarm (not shown in the screenshot) is correct.

It is possible your database was locked during a long time and this affected the notification.  Are you using `memory mode = dbengine`? If you are, can you see any error related to it inside your logs?

We executed a long study to try improving the lock scheme that Netdata currently has. We will bring updates to it soon.

> And, no, my timezone is gmt +2:00

Thank you for the additional information.

**Comment by olivluca** [comment]
Yes, it's dbengine, and no, I cannot see any locking error (I see some LOG FLOOD PROTECTION messages but logging has resumed by the time the alarm shows as cleared on the dashboard).

The screenshot was just an example, other notifications are sent 1 hour later and that's the down time programmed for those alarms.

I may be wrong but I really think that's something to do with the delay down parameter.

**Comment by ilyam8** [comment]
> Note that the difference (30 minutes) is exactly the delay down in the rule for that alarm.

Well, it is expected then, we **send** notifications only after delay up/down time. It doesnt apply to the alarm log.

**Comment by olivluca** [comment]
It may be expected but it is confusing: I see an alarm active in alerta (in may case), click it, go to netdata dashboard and there's no alarm there.

**Comment by thiagoftsm** [comment]
Hi @olivluca ,

Did you update your Netdata for a version bigger than 1.22? Case this happened, we are not redirecting yet the alarms with the new cloud and dashboard, but we will bring this feature soon. @VLegakis  and I are already working on this.

Best regards!

**Comment by olivluca** [comment]
Yes, now I'm using 1.22.1

**Comment by n0099** [comment]
I'm encountering this issue too, for me it's delayed for 15mins and netdata version is `v1.36.0-314-nightly`

**Comment by MrZammler** [comment]
Hi @n0099 

Can you describe your problem exactly? You are getting CLEARED alarms notifications after a 15 min delay ?

On the alert you have this problem, does it's configuration have a [delay](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) ?

**Comment by n0099** [comment]
> You are getting CLEARED alarms notifications after a 15 min delay ?

Yes, but I'm not sure that will it always be waiting for 15mins since this server have only alarmed two times till now.

> does it's configuration have a [delay](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) ?

They are built-in alarms so how can I figure out its default config?

**Comment by MrZammler** [comment]
Most likely the configuration files for the alerts should be in `/usr/lib/netdata/conf.d/health.d/`

What is the alert that is firing?

**Comment by n0099** [comment]
I've just done some pressure tests on the server, all these alarms had notified me via the browser push notification:
![image](https://user-images.githubusercontent.com/13030387/200120337-005f1015-ea5d-44ab-a11e-5ae05fafbe75.png)
![image](https://user-images.githubusercontent.com/13030387/200120330-ac6b6dda-f809-4792-9d8d-90e6597a2d2e.png)

But only the `system.ram` and `memory.available` alarms had pushed the notify message to zulip (a slack alternate) and telegram via my modified `custom_sender()` in `/etc/netdata/health_alarm_notify.conf`:
![image](https://user-images.githubusercontent.com/13030387/200120326-a09dd617-eed2-43b2-9ffc-29eeede9589b.png)
![image](https://user-images.githubusercontent.com/13030387/200120343-2a0dfe24-bfce-4865-9705-84d16ad6cf69.png)
and u can see that the `system.ram` and `memory.available` alarms had recovered to CLEAR state at `20:15`, but their zulip and telegram notify is pushed at `20:30`, that's the 15 mins delay.

**Comment by n0099** [comment]
> configuration files for the alerts should be in `/usr/lib/netdata/conf.d/health.d/`

The `/usr/lib/netdata/conf.d/health.d/ram.conf` file have these lines:
![image](https://user-images.githubusercontent.com/13030387/200121111-2545df9f-8814-450f-9791-a87e842ce57d.png)

**Comment by MrZammler** [comment]
Hi @n0099 

You can remove, or decrease the down delay, by creating a custom copy of this alert for your system.

In `/etc/netdata/`, try running `sudo ./edit-config health.d/ram.conf`. This will open an editor, edit the `down 15m` to e.g. `down 1m` and restart Netdata.

Cleared `ram_available` alerts should then send a notification after 1m.

**Comment by n0099** [comment]
Thanks, but how can I let other alarms to notify through `custom_sender()`? Currently only system.ram and memory.available will.

**Comment by MrZammler** [comment]
Hi @n0099 

You can do the same check for the other alerts (not all of them have this option), and adjust as needed.

**Comment by n0099** [comment]
What checks? for example in the `ram.available` alarm above:
![image](https://user-images.githubusercontent.com/13030387/200121111-2545df9f-8814-450f-9791-a87e842ce57d.png)
which prop defined the behavior of sending notification to `custom_sender()`?
