### ISSUE TITLE
Netdata daemon binary references outdated web assets and copyright

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#8657]
##### Bug report summary

@aabatangle noticed that when users put the `-help` flag on the `netdata` CLI tool, they'll see outdated information about some of our website assets, which could make it harder for them to find information or documentation.

The sites referenced for **Home Page** and **Wiki / Docs** are not current. The copyright is also not current and references Costa instead of Netdata, Inc.

Output from `netdata -help` below:

```
➜ netdata -help                                                                 15:30:29 

 ^
 |.-.   .-.   .-.   .-.   .  netdata                                         
 |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!   
 +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

 Copyright (C) 2016-2017, Costa Tsaousis <costa@tsaousis.gr>
 Released under GNU General Public License v3 or later.
 All rights reserved.

 Home Page  : https://my-netdata.io
 Source Code: https://github.com/netdata/netdata
 Wiki / Docs: https://github.com/netdata/netdata/wiki
 Support    : https://github.com/netdata/netdata/issues
 License    : https://github.com/netdata/netdata/blob/master/LICENSE.md

 Twitter    : https://twitter.com/linuxnetdata
 Facebook   : https://www.facebook.com/linuxnetdata/
```

##### OS / Environment

```

```

##### Netdata version

 
netdata v1.21.0-10-g3c4cb607

##### Component Name

daemon

##### Steps To Reproduce

1. Run `netdata -help`
2. See the output linking to out-of-date asset.s

##### Expected behavior

The `netdata -cli` output should point to current website assets:

- **Home Page** should link to [https://netdata.cloud](https://netdata.cloud)
- **Wiki / Docs** should link to [https://docs.netdata.cloud](https://docs.netdata.cloud)

We also need to Update the following line:

- Before: Copyright (C) 2016-2017, Costa Tsaousis <costa@tsaousis.gr>
- After: Copyright (C) 2016-2020, Netdata, Inc. <info@netdata.cloud>

**Comment by mfundul** [comment]
Small correction, this is the `netdata` daemon binary, not the cli binary which is `netdatacli`.

**Comment by joelhans** [comment]
> Small correction, this is the `netdata` daemon binary, not the cli binary which is `netdatacli`.

Good point. I changed the title.

**Comment by joelhans** [comment]
@aabatangle I just updated this ticket to say that the copyright is also old, and suggested the following as an alternative. Let's confirm, as this kind of thing is well outside my wheelhouse.

- Before: Copyright (C) 2016-2017, Costa Tsaousis <costa@tsaousis.gr>
- After: Copyright (C) 2016-2020, Netdata, Inc. <info@netdata.cloud>

**Comment by aabatangle** [comment]
Yep - that's correct.
