### ISSUE TITLE
The future support/development of the ioping plugin

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#8660]
##### Feature idea summary
Taking into account, that the developers of ioping are [not willing to add Netdata support](https://github.com/koct9i/ioping/pull/41#issuecomment-601644070) to the ioping tool itself, we should consider our options:
- Just leave everything as it is at the moment and use our own repo for our version of the tool.
- Try persuading the guys to include Netdata support to the main ioping repo.
- Plan writing a new plugin in Go and parse the JSON output of the tool.
- Integrate the ioping source code into Netdata.

I suppose our users don't use the plugin extensively.

**Comment by ilyam8** [comment]
> Just leave everything as it is at the moment and use our own repo for our version of the tool.

What is wrong with it? I am not saying there is nothing, but why did you bring up the discussion?

**Comment by vlvkobal** [comment]
> why did you bring up the discussion?

Because of the discussion in https://github.com/koct9i/ioping/pull/41

**Comment by ilyam8** [comment]
It is not gonna make it into the master, i get it. But keep using our own fork seems to be working. I mean what is wrong with our current approach?

**Comment by vlvkobal** [comment]
I think - nothing at the moment. The only inconvenience I see -  we will have to update our repo with new versions of ioping on requests from our users.

**Comment by ilyam8** [comment]
I see no active development, there are several commits in a year. Taking all this into account i think it is safe to keep follow current approach.

**Comment by vlvkobal** [comment]
I agree. I'm closing the issue.
