### ISSUE TITLE
Scaling milliseconds to graph

### ISSUE THREAD

**Issue by nikobearrr** [netdata/netdata#8661]
##### Question summary

I am collecting some metrics from SNMP devices using the netdata node.d and it works great. I can fetch the status and present it. My issue is that I get the uptime in milliseconds. At the moment I have configured my chart as such:
```

"snmp_server.uptime": {
    "title": "uptime",
    "units": "seconds",
    "type": "area",
    "priority": 1,
    "family": "uptime",
    "dimensions": {
        "uptime": {
            "oid": "... some iod",
            "algorithm": "absolute",
            "multiplier": 1,
            "divisor": 100,
            "offset": 0
        }
    }
}
``` 

that shows as a chart and showing me 

```
time
41d:22:39:11

```

which is what I expect to see. 
My issue/question is that I expect that I should not need to divide it by 100 and just provide milliseconds units, so something like this:
```

"snmp_server.uptime": {
    "title": "uptime",
    "units": "milliseconds", # <-- changed this
    "type": "area",
    "priority": 1,
    "family": "uptime",
    "dimensions": {
        "uptime": {
            "oid": "... some iod",
            "algorithm": "absolute",
            "multiplier": 1,
            "divisor": 1, # <-- removed divisor
            "offset": 0
        }
    }
}

```

But when I do this, instead of seing the same 

```
time
41d:22:39:11

```

I see

```
M:SS.ms
4636:46.40

```

which shows me the uptime in minutes. I would have expected to see it in the same time format as when I chose "seconds" for units. 
I checked the dashboard.js https://github.com/netdata/netdata/blob/281fd893d0b5d48bf9f0df688b85c95ba236e450/web/gui/dashboard.js#L957 and it seems this made for milliseconds only - not for seconds or nanoseconds.

As it is now I will go with seconds and division, but I would preferably just specify milliseconds and get the time amount. I am not sure if this is bug or on purpose so I didn't open this as a bug report.

In general it would be nice if there is a place on the docs where I can see what kind of units I can put. I tried to google, but nothing really came out, so I searched the repository.

##### OS / Environment
netdata v1.21 running on docker

##### Component Name
node.d plugin running snmp

**Comment by ilyam8** [comment]
Hi @nikobearrr 

You need to send seconds to netdata daemon, so if a device returns in other units use multiplier/divisor. I dont think `uptime` in ms makes much sense.

**Comment by ilyam8** [comment]
>     "units": "milliseconds", # <-- changed this

try ms or disable Settings-Locale-ScaleUnits

**Comment by nikobearrr** [comment]
Hi @ilyam8 

It's not up to me what the hardware is sending. It's not actually milliseconds, but hundreds of seconds, so even if I use milliseconds I will need to multiply by 10.

`"units": "milliseconds", # <-- changed this` worked fine, based on what I can see in the https://github.com/netdata/netdata/blob/281fd893d0b5d48bf9f0df688b85c95ba236e450/web/gui/dashboard.js#L957 file. 

I take that this is by design. 
My suggestion would be to have a page on the docs which contains explanation regarding units, preferably around here: https://docs.netdata.cloud/web/gui/custom/#chart-units showing what units are avaiable to set and what the output will be. 

I will use `seconds` and divide the input parameter.
