### ISSUE TITLE
Update React dashboard handling to not require a switching script.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8662]
Based on recent discussions, we're ditching the `netdata-switch-dashboard.sh` script in favor of just installing the old dashboard prefixed under the new one.

This will require changes to the installer code to set up the prefixing correctly, and will probably need changes to the old dashboard code as well.

**Comment by hexchain** [comment]
How should downstream distro packages handle this change? Should the new dashboard be built independently and then installed into `$(webdir)`?

**Comment by Ferroin** [comment]
> How should downstream distro packages handle this change? Should the new dashboard be built independently and then installed into `$(webdir)`?

I'm not entirely sure honestly. I don't know that we've decided on our end whether we want to handled as it's own package or not (I'd personally like to).

**Comment by Ferroin** [comment]
OK, slight update here. This _shouldn't_ break third-party packages, but they will still need to prepare the react dashboard to provide Netdata Cloud support.

**Comment by hexchain** [comment]
From the PR I see that the dashboard in this repository is being installed into `$(webolddir)`, but since the Arch package is built using only `configure` and `make`, I would expect that the daemon cannot find the dashboard.

Does that mean distros should build https://github.com/netdata/dashboard (either separately or in the build process of netdata daemon) and install it to `$(webdir)`, in order to have a functional dashboard?

**Comment by Ferroin** [comment]
@hexchain The PR will be changing shortly so that there shouldn't be any loss of Dashboard functionality for distro packages that aren't handling the new dashboard.

Long-term though, what you describe is what will be needed. The existing dashboard is (eventually) going away and the one at https://github.com/netdata/dashboard will be the official one. The new dashboard is also required for the upcoming Netdata Cloud functionality that will be part of release 1.22 (planned for release on 2020-04-27).

**Comment by hexchain** [comment]
Thanks for the explanation. When the old dashboard is eventually phased out, will the build process of the new dashboard be integrated into the build process of the daemon?

**Comment by Ferroin** [comment]
@hexchain I suspect it probably won't be. I do know that the new dshboard will be kept as a separate repo though.
