### ISSUE TITLE
dbengine not created

### ISSUE THREAD

**Issue by zupo** [netdata/netdata#8676]
##### Bug report summary

I have a very basic netdata installation. I've configured it to use dbengine with 2GB of space because I need some history. But I still only got ~11 hours of history. Then I noticed that `/var/cache/netdata/dbengine` does not exist / was not created. What am I doing wrong?

##### OS / Environment

```
 uname -a; grep -Hv "^#" /etc/*release 
Linux corona 4.19.80 #1-NixOS SMP Thu Oct 17 20:45:44 UTC 2019 x86_64 GNU/Linux
/etc/os-release:NAME=NixOS
/etc/os-release:ID=nixos
/etc/os-release:VERSION="19.03.173691.34c7eb7545d (Koi)"
/etc/os-release:VERSION_CODENAME=koi
/etc/os-release:VERSION_ID="19.03.173691.34c7eb7545d"
/etc/os-release:PRETTY_NAME="NixOS 19.03.173691.34c7eb7545d (Koi)"
/etc/os-release:LOGO="nix-snowflake"
/etc/os-release:HOME_URL="https://nixos.org/"
/etc/os-release:SUPPORT_URL="https://nixos.org/nixos/support.html"
/etc/os-release:BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

##### Netdata version

 
```
# /nix/store/fcma69zx8r31yrhv83nds5imlhjxnbwx-netdata-1.11.1/bin/netdata -V
netdata 1.11.0_rolling
```

##### Component Name

DBEngine

##### Steps To Reproduce

This is my config:

```
[backend]
data source=average
destination=xxx:2003
enabled=yes
prefix=xxx.netdata
send charts matching=nvidia_smi.gpu0_gpu_utilization nvidia_smi.gpu0_mem_utilization nvidia_smi.gpu0_temperature system.cpu system.io system.load system.net system.ram users.cpu users.mem
type=graphite
update every=60

[global]
dbengine disk space=2048
memory mode=dbengine
page cache size=128
plugins directory=/nix/store/fcma69zx8r31yrhv83nds5imlhjxnbwx-netdata-1.11.1/libexec/netdata/plugins.d /nix/store/fmcnyijas1dk23b92fkirvdz06hk8cb2-wrapped-plugins/libexec/netdata/plugins.d
update every=10

[web]
web files group=root
web files owner=root
```

##### Expected behavior

1. Since I am giving dbengine 2048 of disk space I am expecting more than ~11 hours of history
2. According to https://docs.netdata.cloud/database/engine/ I am expecting to find `/var/cache/netdata/dbengine` but it's not there.

**Comment by mfundul** [comment]
You need to use spaces instead of `...mode=db...` -> `...mode = db...`. The same applies to all settings.

**Comment by mfundul** [comment]
Moreover, this netdata version is ancient, it does not support `dbengine`. You should follow the instructions in the documenation and reinstall netdata.

**Comment by zupo** [comment]
Thanks for the quick reply!
