### ISSUE TITLE
Aggregating cpu usage of all qemu instances in single chart.

### ISSUE THREAD

**Issue by alishir** [netdata/netdata#8678]
Hi,
Currently netdata show cpu usage of each qemu instance based on its cgroups.But I want to create a single chart that shows cpu usage of multiple qemu instance in single chart.
I want to know which instance is using more CPU on given time.
I searched the issues, and net but unfortunately I didn't find how should I create this type of charts?

I'm using latest version of netdata on CentOS host.

**Comment by zdzichu** [comment]
You probably want https://github.com/netdata/netdata/issues/2359 implemented
