### ISSUE TITLE
netdata update script deleted the netdata.conf file

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8679]
##### Question summary
I planned to update our master netdata servers to the latest stable version (1.21.0) using the script located in `/opt/netdata/usr/libexec/netdata/netdata-updater.sh`, after the upgrading process, I noticed all files inside `/opt/netdata/etc/netdata` directory including plugins and `stream.conf` are unchanged except `netdata.conf` file which says I can download the template using 127.0.0.1:19999/netdata.conf
Is it something expected in the process of updating?
##### OS / Environment
netdata v1.20.0
##### Expected results
keep `netdata.conf` like every other config file

**Comment by prologic** [comment]
> Is it something expected in the process of updating?

I'm afarid this is a bit of a know problem at the moment (See: https://github.com/netdata/netdata/issues/8531) I don't yet have a fix for this; but my plan was to make it possible for a user (_you_) to be prompted of any changes and give you an opportunity to do things like:

- take upstream
- leave mine alone
- merge differences

A bit like what the `git` and `dpkg` do.
