### ISSUE TITLE
backend - prometheus remote write - how to specify basic http auth credentials?

### ISSUE THREAD

**Issue by chrisfw** [netdata/netdata#8681]
##### Question summary
A typical Prometheus remote write config (in this case for the Grafana Cloud) in prometheus.yml where the endpoint requires http auth looks like this:

```remote_write:
   - url: https://prometheus-us-central1.grafana.net/api/prom/push
     basic_auth:
       username: xxxx
       password: yyyyyy 
```
The netdata documentation for the Prometheus remote write config has this
```
[backend]
    destination = example.domain:example_port
    remote write URL path = /storage/read
```
I see there is some documentation on adding http auth to the netdata backend, but it is not clear to me if the same type of config applies to the prometheus backend?

##### OS / Environment
RHEL 7.8
##### Component Name
Prometheus Remote Write Backend
##### Expected results
A full sample netdata.conf with http authentication enabled and example credentials detailed in the netdata Prometheus Remote Write documentation.

**Comment by vlvkobal** [comment]
The Prometheus Remote Write backend doesn't support HTTPS at the moment. You can use HTTPS with OpenTSDB and MongoDB backends.

**Comment by ilyam8** [comment]
@chrisfw asked about http basic auth.

**Comment by vlvkobal** [comment]
Only the MongoDB backend supports HTTP basic auth.

**Comment by ilyam8** [comment]
basic auth shouldnt be hard to implement, all we need is to base64 encode value and add it to the header

example in go
```go
v := []byte("admin" + ":" + "password")
basicAuth := base64.StdEncoding.EncodeToString(v)
httpReq.Header.Set("Authorization", "Basic "+basicAuth)
```

**Comment by stathis** [comment]
This would indeed be very useful.

**Comment by dgsus** [comment]
+1 , or at least the possibility of tls

**Comment by vlvkobal** [comment]
TLS support was added in #9911.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
