### ISSUE TITLE
charts.d/apcupsd: treat "TRIM ONLINE" status as ok status

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8687]
Hi,
I think that status "TRIM ONLINE" should also be added. Currently I have the situation when UPS is reporting status TRIM ONLINE but everything works great. Sadly this status is causing metrics not being collected.

```cmd
apcaccess status | grep -i status
STATUS   : TRIM ONLINE

/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 apcupsd
charts.d: DEBUG: apcupsd: loading module: '/usr/libexec/netdata/plugins.d/../charts.d/apcupsd.chart.sh'
charts.d: DEBUG: apcupsd: loading module configuration: '/usr/lib/netdata/conf.d/charts.d/apcupsd.conf'
charts.d: DEBUG: apcupsd: loading module configuration: '/etc/netdata/charts.d/apcupsd.conf'
charts.d: ERROR: apcupsd: APC UPS local on 127.0.0.1:3551 is not online.
charts.d: ERROR: apcupsd: No APC UPSes found available.
charts.d: ERROR: apcupsd: module's 'apcupsd' check() function reports failure.
```

_Originally posted by @Mic-Pod in https://github.com/netdata/netdata/issues/5428#issuecomment-612635833_

**Comment by ilyam8** [comment]
@Mic-Pod could you test the fix? #8688

**Comment by Mic-Pod** [comment]
My status went back to simple "ONLINE" so I can not verify for sure. But I have edited the file, restarted netdata and it looks good. As I understand it will be easier now to add another statuses that should not stop the collector from gathering metrics. For example status OVERLOAD will currently trigger the collector to mark the UPS as OFFLINE and as a result, no metrics will be collected while they should be. It is normal, temporary state when UPS status is somehow degraded but it is still working and metrics should be collected.

**Comment by ilyam8** [comment]
> For example status OVERLOAD will currently trigger the collector to mark the UPS as OFFLINE and as a result, no metrics will be collected while they should be

Yes, all we need is to modify `is_ups_status_ok` func logic. However i have no apc upses, cant do it properly.

**Comment by ilyam8** [comment]
> For example status OVERLOAD

I can add other status in the PR. Any other suggestions?

**Comment by ilyam8** [comment]
> But I have edited the file

you can download the file

> https://raw.githubusercontent.com/ilyam8/netdata/apcupsd_fix_status_check/collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh

**Comment by Mic-Pod** [comment]
> you can download the file

Thanks, didn't think about downloading. Just quickly edited those few lines ;)

> I can add other status in the PR. Any other suggestions?

I'm not sure about all statuses but I think for those: `CAL TRIM BOOST ONLINE ONBATT OVERLOAD LOWBATT` metrics should be still collected.

I was also wondering if it wouldn't be better to somehow reverse the logic - from:
`if ! is_ups_status_ok then "is not online"` _many statuses to include_
to:
`if is_ups_status_not_ok then "is not online"` _only 2 statuses:_ `COMMLOST or SHUTTING DOWN` _(according to docs)_
What do You think?

**Comment by ilyam8** [comment]
sounds reasanoble

**Comment by ilyam8** [comment]
@Mic-Pod test [new version](https://raw.githubusercontent.com/ilyam8/netdata/apcupsd_fix_status_check/collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh)
