### ISSUE TITLE
charts.d/apcupsd: memory leak and high cpu usage when netdata is started before apcupsd

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8689]
##### Bug report summary

Reported by @cryptoluks  in #8686

> If netdata is started before apcupsd (happens when starting apcupsd automatically through checkbox in GUI and netdata through shellcmd mechanism) a cat process will eat up CPU and RAM. The cat process seems to be triggered by the default activated apcupsd netdata charts plugin (writes to /tmp/.netdata-charts.d-foo/run.foo). When disabling the netdata apcupsd plugin, the cat process is not spawned at boot.

##### OS / Environment

```
pfsense
```

##### Netdata version

 
`netdata v1.21.0-20-g231d1935`

##### Component Name

`collectors/charts.d/apcupsd`

##### Steps To Reproduce

1. start `Netdata` before `apcupsd`

**Comment by ilyam8** [comment]
I guess best fix is to drop bash version and rewrite this module in go. Should be pretty easy.

https://github.com/flyte/apcaccess/blob/develop/apcaccess/status.py

**Comment by cakrit** [comment]
Let's do this rewrite then! :)

**Comment by ilyam8** [comment]
Closing this issue. The warning was added in #8686. We will rewrite the collector in go.
