### ISSUE TITLE
Is it still possible to install netdata without root/sudo?

### ISSUE THREAD

**Issue by 161134050** [netdata/netdata#8690]
### Question summary
This was asked in #3948 however, @ktsaou said to do the following 

"You will need to pass the parameter --install ~/ to netdata-installer.sh to install netdata in your home. Other than that, everything is the same."

This was in 2018, and right now when I go to the netdata installation page all I can find is a kickstarter script which keeps begging me for sudo.

Is the netdata-installer.sh still relevant? Where can I find it? Is it still possible to run without root?

##### OS / Environment
Debian 9

**Comment by ilyam8** [comment]
> Is the netdata-installer.sh still relevant? Where can I find it? Is it still possible to run without root?

It should be possible if you `git clone https://github/netdata/netdata; cd netdata; ./netdata-installer.sh --install <DIR>`

Not sure about kickstart script

**Comment by 161134050** [comment]
Thanks for that,

However, I was unable to install because of missing dependencies like uuid-dev

Is there a pre-compiled static binary that I could just run?

**Comment by thiagoftsm** [comment]
Hi @161134050 ,

We have the static binary installation as you can see in this link https://docs.netdata.cloud/packaging/installer/methods/kickstart-64/#install-netdata-with-kickstart-static64sh

**Comment by 161134050** [comment]
> Hi @161134050 ,
> 
> We have the static binary installation as you can see in this link https://docs.netdata.cloud/packaging/installer/methods/kickstart-64/#install-netdata-with-kickstart-static64sh

Thanks, but i'm unable to run that, it's asking for sudo to run `sudo sh /tmp/netdata-kickstart-3sy86T/netdata-latest.gz.run -- --auto-update`

**Comment by thiagoftsm** [comment]
I could recreate this error and I also got another, based in your first comment:

```
bash-5.0$ mkdir netdata
bash-5.0$ curl -o kickstart-static64.sh https://my-netdata.io/kickstart-static64.sh
bash-5.0$ sh kickstart-static64.sh --install ./netdata/
Unknown option '--install' or invalid number of arguments. Please check the README for the available arguments of kickstart-static64.sh and try again
```

On the other hand,  when I cloned Netdata, and installed it from scratch I could install without any problem:

```
bash-5.0$ mkdir /tmp/tests
bash-5.0$ git clone https://github.com/netdata/netdata.git
bash-5.0$ cd netdata
bash-5.0$ ./netdata-installer.sh --dont-wait --install /tmp/tests --dont-start-it 2> err >out
```

About the `kickstart-static64.sh` script, I will address the SRE team to give us condition to do in the future. @prologic and @Ferroin , please, can you investigate the installation of Netdata using `kickstart-static64.sh --install`? Thank you!

**Comment by Ferroin** [comment]
We can't currently support a prefixed install with the static installer because we have to hard-code certain default locations into the compiled Netdata binary and cannot update those at install time (in particular, it needs an absolute path to it's configuration director).

I would honestly love to support it, but doing that would require some somewhat complicated changes to some of the cor ecode to handle default paths as being relative to the netdata binary (and it would have to be optional).

**Comment by prologic** [comment]
I am closing this as "wont' fix" for now. The amount of effort required to make allow custom installation prefixes for the static installer is considerable. The source-based installer with custom prefix works provided your host system has the requried build dependenices, _and_ the amount of work currently required for us to to make what the `install-required-packages.sh` does but for a local non-root user is out of scope at this time.

Long-term we would probably like to do this; but I would suggest getting the required dependneices installed on your host to build netdata from soruce in a custom prefix without root or use the provided Docker iamges (_which can be run as a normal user_).
