### ISSUE TITLE
Python 2 EOL

### ISSUE THREAD

**Issue by mjtice** [netdata/netdata#8696]
Hi guys,

Given that python 2 was end-of-life in January, are there plans to de-support python2 in Netdata?  I bring this up because I'm trying to write a plugin and the module (https://github.com/dgildeh/JMXQuery) only supports python3.

The plugin documentation states:
>all code needs to be compatible with Python 2 (≥ 2.7) and 3 (≥ 3.1)

**Comment by ilyam8** [comment]
> all code needs to be compatible with Python 2 (≥ 2.7) and 3 (≥ 3.1)

Hi @mjtice :wave: I don't think this requirement remains valid.

**Comment by ilyam8** [comment]
Related, from [yamllint project](https://github.com/adrienverge/yamllint#yamllint)

> Python 2 upstream support stopped on January 1, 2020. yamllint will keep best-effort support for Python 2.7 until January 1, 2021. Passed that date, yamllint will drop all Python 2-related code.

I think something like that is true for us too.

**Comment by ilyam8** [comment]
But complete drop all py2-related code will be discussed.
