### ISSUE TITLE
Register Slayer to Registry with local IP

### ISSUE THREAD

**Issue by kkech** [netdata/netdata#8697]
##### Question summary
I have deployed two netdata servers. The one is the master and the second is the slayer. Slayer still has local database and health checks. The master node has static IP and the slayer has non-static. I added in the registry the master node and now I am trying to add the slayer. When the slayer is registered to the registry, it uses its non-static IP. This causes problems with alerts in the slack(as the IP is not accessible) and also the registry cannot get data from the slayer. Is there any way that I can fix this?
##### OS / Environment
Ubuntu 18.04, Rasbian
##### Expected results
I want the slayer to be accessible from the registry. Furthermore, the URL from the slack message needs to redirect to the master node http://master-host:master-port/host/slave-host/, in order to be able to access it.

Thank you in advance and congratulations for all the work!!!

**Comment by thiagoftsm** [comment]
Hi @kkech ,

I am assuming you are writing about the Netdata `slaves` to answer you. We already had another issue created to fix a problem like this https://github.com/netdata/netdata/issues/6975, but I will give additional information to help you.

You can try to centralize the registry changing the slave `netdata.conf` :

```
[registry]
   registry to announce = https://MASTER-HOSTER:19999
``` 

When a slave registries itself on master, it sends the its UUID that is used to create the entries, the IP in this case is an additional information.

Is your master also sending messages to you? 
What is the error message that you receive when you try to access the slave using master address?

Thank you for your considerations!
