### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by ibmendoza** [netdata/netdata#87]
Would appreciate if under Releases, there is a ready to download binary (just a friendly reminder from a usability perspective!)

Thanks.

**Comment by ktsaou** [comment]
You are right. I need help achieving this though (a lot of distros).

**Comment by tsumaru720** [comment]
This kind of relates to #94 - In addition to OS specific install packages, a standalone binary could be useful :)

**Comment by mcnewton** [comment]
Maybe http://openbuildservice.org/ could be useful here? It can be used to build packages for lots of different distributions and archs.

Cheers,
Matthew

**Comment by philwhineray** [comment]
@tsumaru720 the idea of a standalone binary is probably too much to hope for - you still need to define processor architecture, dependent library versions etc. which basically winds up equating to distro versions.

@mcnewton  OBS looks like it might be great solution to project-provided binaries, especially if the hosted version at https://build.opensuse.org/ can be used. Here is a list of its targets: https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets

If anyone wants to pick this up and run with it, I can help with providing hooks from github and the other firehol servers for automation.

**Comment by mcnewton** [comment]
I'm pretty sure OBS can be fully automated on their systems. I've not done it myself, but know others who use it. Will try to remember to ask...

**Comment by ArtriciaDM** [comment]
Thanks

Artricia Harris

On Apr 2, 2016 10:29 AM, Matthew Newton <notifications@github.com> wrote:
I'm pretty sure OBS can be fully automated on their systems. I've not done it myself, but know others who use it. Will try to remember to ask...

---

**Comment by terryburton** [comment]
@mcnewton @ArtriciaDM @philwhineray I use OBS to build binaries for most major distros and to provide Continuous Integration package building.

This comment describes how: https://github.com/firehol/netdata/pull/132#discussion_r58855443

**Comment by ktsaou** [comment]
OBS?

**Comment by mcnewton** [comment]
@ktsaou openSuSE Build Service - https://build.opensuse.org/

**Comment by glensc** [comment]
most people just want linux-x86-64 binary, and netdata being without much dependencies (just libc and libz) it would "just work":

```
➔ rpm -q netdata --requires|grep 64bit
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.15)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libz.so.1()(64bit)
```

**Comment by chilicuil** [comment]
Please make it an static binary, so it just work with any Linux distribution.

**Comment by glensc** [comment]
no need to make fully static, every linux system has those [tree libraries](https://github.com/firehol/netdata/issues/87#issuecomment-206941840)

**Comment by chilicuil** [comment]
[not](http://alpinelinux.org/) [every](http://www.voidlinux.eu/) [linux](http://landley.net/aboriginal/) [system](https://github.com/jelaas/bifrost-build)

**Comment by ktsaou** [comment]
Netdata builds and runs on alpine perfectly. Check #66 
If the others are using also musl libc, there is not something to be done.

If not, guys, I would really appreciate some help. There are a few changes to be made at the source to allow it build statically. Then the process of creating a static binary could be simple:

```sh
CFLAGS="-O3 -static" ./netdata-installer.sh --install /opt --dont-start-it
```

This now gives a few linking errors, but let's say these are solved.

Then, there are wiki pages to be written, users to be supported using this package, possibly provide different packages for different architectures, etc.

So, if anyone is willing to maintain the statically linked distribution of netdata, please volunteer and let's do it.

**Comment by glensc** [comment]
i think some CI (travis f.e) should build them, but they (such CI projects) lack place to upload results, so you need another place like https://packagecloud.io, but then again OpenSuSE OBS was suggested, but i have never used OBS.

**Comment by terryburton** [comment]
There's also [travis-github-release](https://github.com/terryburton/travis-github-release) which is a simple Travis CI after_success script that will upload build objects (tarballs, binaries, etc.) for tagged commit to a GitHub release.

Example use: https://github.com/bwipp/postscriptbarcode/blob/master/.travis.yml
Which generates the release tarballs here: https://github.com/bwipp/postscriptbarcode/releases

**Comment by nixfu** [comment]
This project needs to move from installing via the build scripts like it was an old school BSD program to learning how to use package management like a real app.   The build scripts need to just build the binaries and do the packaging, and the packages should be doing the installs.  

The current process of making an RPM fails because it is not disabling nfacct properly and because it is trying to do some install of a file like a directory.  It is obvious the RPM spec file process is in need to attention. This should be a focus not to keep installing via git clone/make.

**Comment by X3MBoy** [comment]
I will try to package netdata for fedora. But i'm new with netdata and with packaging, so this could take time. If somone has some work on this, help will be appreaceated

**Comment by ktsaou** [comment]
> The current process of making an RPM fails because it is not disabling nfacct properly and because it is trying to do some install of a file like a directory. It is obvious the RPM spec file process is in need to attention. This should be a focus not to keep installing via git clone/make.

Can you make a PR to fix these issues?

**Comment by glensc** [comment]
i can suggest using [fpm](https://github.com/jordansissel/fpm) making distro packages.

basically it works like this:
- you build your stuff, run make install DESTDIR=/tmp/netdata-root
- tell fpm to takes files from /tmp/netdata-root and make package

however this still lack mechanism of publishing the packages. but it could work for maintainers

**Comment by paulkatsoulakis** [comment]
Closing this, as we will be attempting to nail this through #5963
