### ISSUE TITLE
IPFW monitoring stops at random

### ISSUE THREAD

**Issue by Duffyx** [netdata/netdata#8707]
##### Bug report summary
When monitoring my FreeBSD server, at some point in time the IPFW graphs will stop following and get stuck in the past. (not updated anymore).

##### OS / Environment
uname -a: FreeBSD vados.lan 13.0-CURRENT FreeBSD 13.0-CURRENT #0 r359690: Tue Apr  7 18:33:29 CEST 2020     root@vados.lan:/usr/obj/usr/src/amd64.amd64/sys/VADOS  amd64
uname -K: 1300088

##### Netdata version
netdata-1.20.0

##### Component Name
FreeBSD plugin - IPFW

##### Steps To Reproduce
Start netdata, wait 1-2 days, IPFW graphs will stop working.
As seen below: only IPFW graphs hang because of memory allocation error bellow?
![image](https://user-images.githubusercontent.com/32487486/79200805-48ecc900-7e37-11ea-9f46-11f616a3bcdc.png)

##### Expected behavior
Graphs continue to work once netdata is started.

#### In error log:
2020-04-13 15:14:09: netdata ERROR : PLUGIN[freebsd] : FREEBSD: ipfw socket reading error (errno 12, Cannot allocate memory)
2020-04-13 15:14:09: netdata ERROR : PLUGIN[freebsd] : DISABLED: ipfw.packets chart
2020-04-13 15:14:09: netdata ERROR : PLUGIN[freebsd] : DISABLED: ipfw.bytes chart
2020-04-13 15:14:09: netdata ERROR : PLUGIN[freebsd] : DISABLED: ipfw.dyn_active chart
2020-04-13 15:14:09: netdata ERROR : PLUGIN[freebsd] : DISABLED: ime -a;pfw.dyn_expired chart
2020-04-13 15:14:09: netdata ERROR : PLUGIN[freebsd] : DISABLED: ipfw.mem chart

**Comment by thiagoftsm** [comment]
Hi @Duffyx ,

Is this happening only with IPFW?
What is your web browser?

Best regards!

**Comment by Duffyx** [comment]
Yes, it is only the IPFW graphs that stops working after the error from my error.log. The othergraphs continue to update and work. I'm using chrome to access netdata.

**Comment by ilyam8** [comment]
@vlvkobal take a look since you are the author of [this plugin](https://github.com/netdata/netdata/blob/master/collectors/freebsd.plugin/freebsd_ipfw.c)

**Comment by thiagoftsm** [comment]
@Duffyx ,

Please, can you share with us your `error.log`? 

Best regards!

**Comment by Duffyx** [comment]
[error.log](https://github.com/netdata/netdata/files/4475204/error.log)
This is a pretty bulky logfile, although I think its easily distilled which causes the problem as snipped above.

**Comment by Duffyx** [comment]
Hi, has anyone been able to take a look at this? I'm still having a problem with this.

**Comment by ilyam8** [comment]
@vlvkobal ping

**Comment by vlvkobal** [comment]
There is a similar issue - #7947. I couldn't find any problems with the plugin code. The question is - why there are memory allocation errors? It looks like a problem on the OS side.

**Comment by Duffyx** [comment]
I don't know, its consistent in spitting out this error when my history has run out. eg: history = 86400 in netdata.conf, after this time has passed the plugin stops working while the others continue to run losing previous data and replacing it with new data like I expect.

**Comment by ilyam8** [comment]
> history = 86400 in netdata.conf, after this time has passed the plugin stops working

A good finding! I suggest to decrease the history and see it is always the case.

**Comment by Duffyx** [comment]
> > history = 86400 in netdata.conf, after this time has passed the plugin stops working
> 
> A good finding 👍 I suggest to decrease the history and see it is always the case. If it is easily reproducible it is nice!

I just tested this but unfortunately this did not reproduce :-/

**Comment by vlvkobal** [comment]
I've found a huge amount of _"Cannot allocate memory"_ messages in your `error.log`. You should have had problems with apps plugin and `net.*` charts as well. Do you still have these messages in `error.log`?

**Comment by vlvkobal** [comment]
Probably, [changing `memorylocked` resource limit](https://forums.FreeBSD.org/threads/kvm_open-kvm_getprocs-cannot-allocate-memory.37602/post-208357) could solve the issue. You can find more information about resource limits in the [FreeBSD documentation](https://www.freebsd.org/doc/handbook/security-resourcelimits.html).
