### ISSUE TITLE
Custom environment variable within config files (i.e. netdata.conf)?

### ISSUE THREAD

**Issue by zacharygittery** [netdata/netdata#8714]
Is there a method/syntax to use env variables in netdata.conf?

for example,

hostname = ${MY_CUSTOM_ENV_VAR}

**Comment by ilyam8** [comment]
Hi, no, there is no.

**Comment by fullbl** [comment]
would it be possible to reopen it as a feature request? Storing mysql password in .conf file is not exactly the best practice here!
