### ISSUE TITLE
Rename `ebpf_process.plugin` to `ebpf.plugin`

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8717]
##### Feature idea summary
We are converting the current `ebpf_process.plugin` in a modular collector. This module will load different eBPF programs according with the user selections. 

We will also use this plugin to load the necessary information for the future Network Viewer that we are planing.

Considering the fact that an unique collector will take care of all eBPF programs we will create, it makes sense rename it for `ebpf.plugin`. To reach this goals, the following steps are needed:

- Rename the files inside `collector/`directory.
- Rename the collector inside `Makefile`s , `.gitignore`, `configure.ac`, `netdata.spec` and `netdata-installer.sh`.
- We need to insert a function inside `netdata_installer.sh` that will remove completely the old collector ( `ebpf_process.plugin`) before we install the new `ebpf_plugin`..

##### Expected behavior
We can never have two ebpf collectors running on the computer and the unique remaining will be `ebpf.plugin`.

**Comment by ilyam8** [comment]
>  in the new propose apps.plugin will create a pipe or unix socket that will establish a direct connection between apps.plugin and ebpf.plugin. In this case, apps.plugin will have another thread exclusively for this communication.

> Considering the fact that an unique collector will take care of all eBPF programs we will create

Does it work?

**Comment by thiagoftsm** [comment]
> Does it work?

This is one of the possibilities that we can explore, but the majority of the team prefers to work with shared library.
