### ISSUE TITLE
Netdata reports total memory and all CPUs of host on libvirt instances

### ISSUE THREAD

**Issue by dolohow** [netdata/netdata#8719]
##### Bug report summary
Charts of libvirt virtual machines running qemu shows total memory of host and all cpus, while only a fraction of memory and few cpus are assigned to those instances.

![image](https://user-images.githubusercontent.com/1408564/79325878-3a271480-7f12-11ea-9356-6aa66874a5fe.png)

When I ssh to machine it shows
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.9G        629M        210M         35M        3.0G        2.9G
Swap:          4.0G         12M        4.0G
```

##### OS / Environment
```
Linux ssl-woox-pl 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
```
netdata v1.20.0-326-nightly
```

##### Component Name
libvirt / qemu

##### Steps To Reproduce
1. Create libvirt virtual machine with kvm
2. Install latest netdata with `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
3. Observe charts of libvirt instance

##### Expected behavior
Expected behaviour would be to get information of how much ram and cpu is assigned to virtual machine instead of reporting total memory installed in host os.

Best

**Comment by Ferroin** [comment]
@dolohow Sorry about the long delay in responding to this.

This appears to be a misunderstanding about how libvirt works and how Netdata works with it.

What the libvirt plugin is actually tracking is the data reported by libvirt about the host's resource utilization resulting from each VM (for example, how much memory on the host each VM is taking up).

What you appear to want is data from the guest systems. There is no way to do this with netdata only installed on the host, you will have to install Netdata in each guest and stream the metrics to the host system to get this info.

**Comment by dolohow** [comment]
Currently, netdata tracks some cgroups data related to libvirtd.

I would like to track information provided by `libvirt`.  This plugin https://github.com/fromanirh/netdata-virt actually does what I want, but I think it is outdated and does not work (it is reporting data, but netdata does not pick them).
