### ISSUE TITLE
email authentication for connection to the cloud no longer works

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#8722]
With the latest from master, email authentication to the cloud is broken.  We go to sign-in page, get the magic link, press it, get redirected to the agent UI and we're still not signed in. 

Tested with Chrome against https://frankfurt.my-netdata.io/ (v1.21.1-11-nightly) and with Firefox against a local host with the latest from master.

**Comment by thiagoftsm** [comment]
@cakrit this is a well known issue already reported to the team, it ha relationship with SSO.

**Comment by cakrit** [comment]
We close this as soon as we have a fix on the nightlies.
