### ISSUE TITLE
Modular eBPF plugin

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8731]
##### Feature idea summary
The current eBPF plugin is monolithic and we need to change it for we load more eBPF programs. To reach this goal we will follow the same pattern already adopted with `proc.plugin`, in this work the following steps will be done:

- Everything related to the current eBPF program inside `ebpf.c` will be moved to another source file (ebpf_process.c). This implies to move the chart creation function, functions used to read data from kernel ring to user ring and process the data, functions that send messages to Netdata. 
- We will have the following changes in the configuration files: 
- `ebpf.conf` will be the global configurator, but we will create configurations for specific eBPF programs, these files will be created inside `ebpf.d`. 
   -   Create a new section inside that will be used to define the ebpf programs that will be loaded ( `[ebpf programs]` ).
    -  The configurations defined inside the global section of `ebpf.conf` can be overwritten for the specific configurations inside `ebpf.d`.
   - Example:
```
[global]
   load = entry
[ebpf programs]
   process = yes
   network viewer = yes
```

-  Like `proc.plugin` we will also have a global structure that will have the functions to be called in each new file added.
- The ebpf programs can be loaded either using `ebpf.conf` or trough command line arguments.
- Right now we have 3 threads inside the `eBPF plugin` ( "Publisher", "Collector", Log ). We will have only one thread per eBPF program and we group the "Publisher" and "Collector" will be merged inside an unique thread.

##### Expected behavior
Organize the collector to bring new eBPF programs.

**Comment by underhood** [comment]
One thing I would like is to also organize/structure data a bit better in the plugin itself instead of one big array with all the values.

**Comment by thiagoftsm** [comment]
> One thing I would like is to also organize/structure data a bit better in the plugin itself instead of one big array with all the values.

I agree, I began to work on this in the PR #8879 where I am creating the basis for this PR. You can see there an array of structures that will be passed as arguments for the threads, be free to give any suggestion.
