### ISSUE TITLE
Improve Offline Installs

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8733]
Capturing a thread from Slack:

> Offline installs are a mess. As of right now, you have to know about and download a total of 6 different things, place them all on the target system, set a different environment variable for each one, and then run the installer. That's not counting eBPF (which adds a whole new set of complications itself, which is part of why I'm trying to push there for runtime kernel detection instead of install time kernel detection). Yes, you could use the static installer, but not everyone wants that, and offline installs there are also not exactly trivial.

**Comment by ilyam8** [comment]
> As of right now, you have to know about and download a total of 6 different things, place them all on the target system, set a different environment variable for each one, and then run the installer.

Really? 🤔 What are these 6 things and different env vars?

**Comment by Ferroin** [comment]
@Ilyam8 We have the following external items we download during the installation process:

* The Netdata sources themselves (as produced by `make dist`).
* LWS
* Mosquitto
* The go.d.plugin binary
* The go.d.plugin config files
* The new dashboard.

This will become at least 7 things when we finally have eBPF enabled, and possibly 8 if we end up using the same approach for handling of libJudy as we did for LWS/Mosquitto.

Each one of those also has it's own environment variable that needs to be set correctly to make the install process use local copies that were already downloaded.

**Comment by ilyam8** [comment]
I think we need something like template. Something like `helm` does. It would be nice to have some `whateverl.yaml` file, set all options there and then just parse it and get all values from there during install.

Probably i am missing something but that was the first thing that came into my mind.

**Comment by prologic** [comment]
> I think we need something like template. Something like `helm` does. It would be nice to have some `offline_install_values.conf`, set all options there and then just parse it and get all values from there during install.
> 
> Probably i am missing something but that was the first thing that came into my mind.

This is more or less what @Ferroin and I discussed. Basically wrap everything up in a nice way so doing offline installs isn't an arduous task.
