### ISSUE TITLE
List of nodes is showing as URL-encoded

### ISSUE THREAD

**Issue by Juggler00** [netdata/netdata#8736]
##### Bug report summary

I am running a private registry. When I view "My nodes" on the dashboard, the different nodes show as URL-encoded. This does not let me navigate to them by clicking on them.

##### OS / Environment

```
Linux docker 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 ```
netdata v1.21.1-20-nightly
```
##### Component Name

web component

##### Steps To Reproduce

1. Edit netdata.conf as follows:
```
[registry]
        enabled = yes
        registry to announce = http://192.168.2.9:19999
        registry hostname = Docker
```

On other hosts, do the same except with `enabled = no

2. From the dashboard, click on the menu in the top-left to see the list of other Netdata servers. 

##### Expected behavior

I would expect the list to show something similar to:
```
Docker
  http://192.168.2.9:19999
```
Instead, I see:
<img width="435" alt="Screen Shot 2020-04-16 at 10 07 21" src="https://user-images.githubusercontent.com/2402668/79466127-2808ad00-7fca-11ea-8420-fad764c133cb.png">

**Comment by prologic** [comment]
Are you running the same version of NetData for the private regsitry too?

**Comment by Juggler00** [comment]
Yes. All instances of NetData are currently showing as up-to-date.

**Comment by jacekkolasa** [comment]
hey @Juggler00 , the issue is known and the fix was added to nightly yesterday. Perhaps you even have the fix but unfortunately broken registry links (url-encoded) have reached your private registry. Can you try removing them manually?

**Comment by Juggler00** [comment]
I've updated all instances to the latest nightly; that has fixed the problem. Thank you!
