### ISSUE TITLE
Need help debugging remote write failures to InfluxDB

### ISSUE THREAD

**Issue by 0ortmann** [netdata/netdata#8737]
##### Question summary

I configured netdata to report to InfluxDB via the `opentsdb:http` backend. But netdata is not able to send data to InfluxDB. I need help debugging, as I do not know where to look anymore.

After restarting netdata, I sometimes can see a successful initial communication between the two nodes in the `/var/log/netdata/error.log`. Here is the relevant snip:

  ```
  [LOTS of plugin logs]
  ...
  2020-04-16 13:59:41: netdata INFO  : BACKENDS : BACKEND: received 192 bytes from opentsdb backend. Ignoring them. Sample: 'HTTP/1.1 204 No Content  Date: Thu, 16   Apr 2020 13:59:36 GMT    HTTP/1.1 204 No Content  Date: Thu, 16 Apr 2020 13:59:36 GMT    HTTP/1.1 204 No Content  Date: Thu, 16 Apr 2020 13:59:36 GMT    '
  2020-04-16 13:59:44: netdata INFO  : PLUGINSD[charts.d] : thread with task id 21275 finished
  2020-04-16 13:59:46: cgroup-name.sh: INFO: cgroup 'init.scope' is called 'init.scope'
  2020-04-16 14:00:26: netdata ERROR : BACKENDS : BACKEND: failed to write data to database backend '10.13.1.0:4242'. Willing to write 323036 bytes, wrote 300098  bytes. Will re-connect. (errno 11, Resource temporarily unavailable)
  2020-04-16 14:00:31: netdata ERROR : BACKENDS : heartbeat missed 10003944 monotonic microseconds
  ```

And the last two messages repeat then.

The first line reads as if everything went OK (status 204), but then the write fails. However, at all times I can verify that the InfluxDB host is reachable and responsive.

##### OS / Environment

- Debian Buster
  ```sh
  uname -a
  Linux <HOST> 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 
  GNU/Linux
  ```
- Netdata installed via kickstart script, stable channel.
  ```sh
  sudo netdata -v
  netdata v1.21.1
  ```
- InfluxDB is reachable, OpenTSDB is enabled in the config. On the host running netata, I can ping / curl the InfluxDB host
  ```ssh
  $ curl -i 10.13.1.0:4242/api

  HTTP/1.1 404 Not Found
  Content-Type: text/plain; charset=utf-8
  X-Content-Type-Options: nosniff
  Date: Thu, 16 Apr 2020 14:25:19 GMT
  Content-Length: 19

  404 page not found                 # --> the port is correctly bound and accepting requests
  ```

- The netdata config. I increased the limit for the log flood protection to be sure to get to see the all relevant error logs.
  ```cfg
  netdata.conf
  ----------------
  [global]
    run as user = netdata
    web files owner = root
    web files group = root
    # Netdata is not designed to be exposed to potentially hostile
    # networks. See https://github.com/netdata/netdata/issues/164
    bind socket to IP = 127.0.0.1
    errors to trigger flood protection = 10000

  [backend]
    enabled = yes
    type = opentsdb:http
    destination = 10.13.1.0:4242
    update every = 5
    timeout = 10000
    send names instead of ids = yes

  [web]
    bind to = *
  ```
- The InfluxDB config
  ```cfg
  [meta]
    dir = "/var/lib/influxdb/meta"

  [data]
    dir = "/var/lib/influxdb/data"
    engine = "tsm1"
    wal-dir = "/var/lib/influxdb/wal"

  [[opentsdb]]
    enabled = true
    bind-address = ":4242"
    database = "opentsdb"
    tls-enabled = false
  ```
   
Both nodes are members in a private VPN, hence the IP namespace `10.13/16`.

##### Component Name

Backends OpenTSDB

##### Expected results

Any debugging help or fingerpoints where to look at is greatly appreciated. I have searched older issues, but could not find a similar scenario without obvious config errors.

**Comment by vlvkobal** [comment]
Please run `nc -l -p 4242` on the database server. Do you see incoming metrics from Netdata?

**Comment by 0ortmann** [comment]
I see a connection from the node IP where netata is running. But I do not see any data being sent:

```sh
nc -vvl -p 4242

listening on [any] 4242 ...
10.13.20.0: inverse host lookup failed: Unknown host
connect to [10.13.1.0] from (UNKNOWN) [10.13.20.0] 42628
```

Meanwhile, the netdata logs give me the same error:

```sh
2020-04-16 15:43:21: netdata ERROR : BACKENDS : Failed to connect to '10.13.1.0', port '4242' (errno 111, Connection refused)
2020-04-16 15:43:21: netdata ERROR : BACKENDS : BACKEND: failed to update database backend '10.13.1.0:4242'
2020-04-16 15:44:06: netdata ERROR : BACKENDS : BACKEND: failed to write data to database backend '10.13.1.0:4242'. Willing to write 323778 bytes, wrote 286284 bytes. Will re-connect. (errno 11, Resource temporarily unavailable)
```

Note: the first two lines about general disconnection are from me taking down the opentsdb endpoint and replacing it with `netcat`.

**Comment by vlvkobal** [comment]
I applied your configuration to Netdata and it works. Please check using `netcat` on the machine, where Netdata is installed, if Netdata sends metrics to destinations `127.0.0.1:4242` and `10.13.20.0:4242`. Also, check your real Netdata configuration using `http://10.13.20.0:19999/netdata.conf`

**Comment by fti-cneve** [comment]
Any updates? I am facing the same issue. 
```
OS: Debian 10 (Buster)
Netdata Version: v1.31.0
Influxdb Version: 1.8.1

```
![image](https://github.com/netdata/netdata/assets/47653578/e6adc5de-6bb7-414c-9df9-bf54f0e51ec2)
