### ISSUE TITLE
Implementation - Calculation of metrics correlation (Agent side)

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8738]
##### Feature idea summary
Netdata will give conditions for our users to correlate all metrics on a computer in a specified period of time. To bring this feature we will need to do the following changes on agents:

- To add the file `correlation.c` inside `libnetdata/statistical/` that will have numerical methods used to compute not only correlation, but artificial intelligence methods. In this first input we will bring Pearson's correlation coefficient.
- Create a new structure that will be used for the `AI` methods that we will bring. This structure will have:
    - Variables to store rows and columns size;
    - It will have pointers for the allocated vectors.
    - Variables to store the first and last timestamp used to do computation.
    - Please, pay attention for the fact that independent of the matrix order, we will always work with allocated vector, like the library LAPACK/Blas does.  Case you do not know the library structure, please, see this [matrix operation example](http://www.netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gaeda3cbd99c8fb834a60a6412878226e1.html#gaeda3cbd99c8fb834a60a6412878226e1 )
- The host structure will be changed, we will add the previous defined structure to process the correlation values for that specific host.
- We will add a new `endpoint` ( `/api/v1/ai_correlation?start=1587065305&end=1587065365&chart=system.cpu`[&method=pearson&charts_scope=['system.cpu','system.load','system.io']]) to our web server that will receive the necessary fields from front end (Start time, End Time, Chart id) and we will process the whole information following this algorithm:
    - Allocate the vectors case it was not allocated.
    - Fill the vector values for the specified period.
    - Process the Pearson's correlation
    - Sort the results.
    - Send back to front end a JSON message with correlated values greater than `0.6` (I personally disagree of the defined value. @cakrit , @vlvkobal, @amoss , @andrewm4894  we need a meeting to discuss this. I would understand `0.68` as a good initial value, but the selected value does not make sense to me right now.).

##### Expected behavior
Bring to Netdata the algorithm to process Pearson's correlation and create a new `endpoint` that gives condition for the front end team to see results like this:

```
{ 
   { "start", "1587065305" },
   { "end", "1587065365" },
   { "chart", "system.cpu" } ,
   { "method", "pearson" },
    { "charts_scope", ['system.cpu','system.load','system.io'] }
},
{
        {"system.cpu.system", "system.cpu.user", 0.906928},
        {"system.cpu.system", "system.cpu.softirq", 0.89011},
        {"system.cpu.user", "system.cpu.softirq", 0.850437},
}
```

##### Pseudo Code / Calculation steps
1. Create data table with all system.overview metrics, one column per metric one row per second spanning the selected timeframe. aggregate data in a similar manner to the chart. 
2. Compute [pearsons correlation](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#Mathematical_properties) between all pairs of columns in data table. Avoid computing reversed pairs of columns (so not computing same correlation twice). 
3. Filter for correlation pairs with abs(correlation) > threshold (default to 0.5). 
4. Plot results in bar chart, ordered by abs(correlation) and color based on if positive or negative correlation.

**Comment by amoss** [comment]
I don't think that we need a meeting to discuss the choice of the threshold value.

* Please give an example of the endpoint url to show how it is defined.
* Show an example of the json produced so that we can verify its structure.
* Name the file after what it actually does (e.g. correlation.c) rather than something general.

**Comment by thiagoftsm** [comment]
@andrewm4894 we have charts with more than one dimension, will our final result to be associated to only one dimension? Or when the user selects a specific region on chart, will we show one correlation for each dimension?

**Comment by thiagoftsm** [comment]
About the `threshold value`, I think we need to select a value based in a statistical measure instead to decide arbitrarily a value. My argument to use `0.68` is based in the fact that Pearson's coefficient assumes that the values are [normally distributed](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3576830/), based in this fact, we can use one of the values defined in [the 68-95-99.7% rule](http://statweb.stanford.edu/~naras/jsm/NormalDensity/NormalDensity.html).

A second argument about to use values bigger than `0.68` is also described in the paper from the previous paragraph, to define as `0.6` means that we will also give "moderate correlations" as output. 

Finally we can create a new section inside `netdata.conf` for our users define the threshould they want.

**Comment by thiagoftsm** [comment]
>     * Please give an example of the endpoint url to show how it is defined.

I updated the initial comment with an example.

>     * Show an example of the json produced so that we can verify its structure.

I am waiting for an answer in a comment above to do not give a partial example.

>     * Name the file after what it actually does (e.g. correlation.c) rather than something general.

I also updated the first comment.

**Comment by andrewm4894** [comment]
> @andrewm4894 we have charts with more than one dimension, will our final result to be associated to only one dimension? Or when the user selects a specific region on chart, will we show one correlation for each dimension?

The final goal is a bar chart where each bar is a dimension pair. So for example if user selects system.cpu. Then the final bar chart will be pairs of dimensions (dim A, dim B) where all pairs have a dim A that is one of the dims from the system.cpu chart. e.g. 
('system.cpu.user', dim B),
('system.cpu.user', dim B),
('system.cpu.idle', dim B)
('system.cpu.system', dim B)
...

Where dim B is all other dimensions from the charts in scope, which we will default to all system.... charts. 

Below is a concrete example of what i mean:

![Annotation 2020-04-01 133913](https://user-images.githubusercontent.com/2178292/79570628-b441cf80-80b1-11ea-8a50-c845773c625c.jpg)

So ultimatley this would be a new chart type (bar chart) where each dimension on the chart is a pair of existing dimensions really.  

So i think:

> Or when the user selects a specific region on chart, will we show one correlation for each dimension?

for each dimension of selected chart (what i am calling the "context chart") we will show multiple correlations (all pairs with the various "dim B" from other charts and even its own chart).

**Comment by andrewm4894** [comment]
one question is if we have a parameter in the api endpoint or something in `netdata.conf` to limit the scope of charts to be looked at. 

e.g. /api/v1/ai_correlation?start=1587065305&end=1587065365&chart=system.cpu&charts_scope=['system.cpu','system.load','system.io']

^ something like this means that the api call will only look at pairs of correlations within the subset of `charts_scope` so as to avoid having to calculate all (context_chart.dimension_id, other_chart.dimension_id). Not sure if this should live as a default param in the api endpoint, probably should to give most flexibility.

**Comment by thiagoftsm** [comment]
> Below is a concrete example of what i mean:

Now it was more clear for me, but this chart created another doubt. Considering that Pearson's gives correlation in the closed interval [ -1.0, 1.0]  and I am seeing two colors in this charts, I understood that the red is showing the negative correlation while the green is showing the positive correlation. Is this conclusion correct?

**Comment by thiagoftsm** [comment]
> one question is if we have a parameter in the api endpoint or something in `netdata.conf` to limit the scope of charts to be looked at.
> 
> e.g. /api/v1/ai_correlation?start=1587065305&end=1587065365&chart=system.cpu&charts_scope=['system.cpu','system.load','system.io']
> 
> ^ something like this means that the api call will only look at pairs of correlations within the subset of `charts_scope` so as to avoid having to calculate all (context_chart.dimension_id, other_chart.dimension_id). Not sure if this should live as a default param in the api endpoint, probably should to give most flexibility.

I liked your idea and I think this is something that we can bring. @amoss , @dim08, @cakrit do you have objections to @andrewm4894 suggestion?

**Comment by amoss** [comment]
The output given is not valid, try something like this:

```
{ "input" : { 
    "start": "1587065305" ,
    "end": "1587065365" ,
    "chart": "system.cpu" ,
    "method", "pearson",
    "charts_scope", ['system.cpu','system.load','system.io'] 
    },
   "output" : [
        { "dims" : [ "system.cpu.system", "system.cpu.user"],
           "cor" :  0.906928
        },
        ....
}
```

**Comment by thiagoftsm** [comment]
After to do the initial tests using only with one chart, we extend the tests to cover all the charts available on an environment, the environment selected had the following characteristics:

```
NETDATA_SYSTEM_CPU_MODEL=Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
NETDATA_SYSTEM_CPU_FREQ=2700000 
NETDATA_SYSTEM_TOTAL_RAM=8257753088
X server running
eBPF plugin enabled
`dbengine` as memory mode
1604 metrics
306 charts
```

To have a bigger stress on the code, we did not use `charts_scope` parameter to force the system to use the whole correlation matrix. On these situation we need in average `1.2' second to process the matrix with `2,572,817` values. On this environment we deliver for the users as response around `7.8 %` of the values  calculated on the matrix.
