### ISSUE TITLE
"options: no-clear-notification" for connection_timeouts and connection_fails alarms

### ISSUE THREAD

**Issue by apurkrt** [netdata/netdata#8741]
##### Bug report summary
In my opinion, there should not be "options: no-clear-notification" for "connection_timeouts" and "connection_fails" alarm. This option is explained as a special precaution for some kind of alarms https://docs.netdata.cloud/health/reference/#alarm-line-option

But timeouts and connection fails does not fall in that category - there simply is or is not a given percentage of timeouts/connection fails in a given timeframe. No issue with "newer data 'polluting' the old" is applicable.

##### OS / Environment
gentoo linux

##### Netdata version
netdata v1.21.1

##### Component Name
netdata/health/health.d/portcheck.conf

##### Steps To Reproduce
1. cd /etc/netdata
2. ./edit-config health.d/portcheck.conf
3. when the alarm triggers, you won't receive a notification on eventual recovery

##### Expected behavior
there should be a notification on recovery from those alarms

**Comment by ilyam8** [comment]
@ccremer 👋 if i remember it right (there is [no history](https://github.com/netdata/netdata/commits/master/health/health.d/httpcheck.conf)) you added them. Why did you add these options?

**Comment by ccremer** [comment]
Uff, I do not remember anymore :)
The suggestion to remove that option sounds to good to me.
