### ISSUE TITLE
Netdata running in docker and IPMI tool reporting

### ISSUE THREAD

**Issue by johncaz** [netdata/netdata#8745]
netdata v1.21.1-19-g3ce7fdc7

AME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

Hello 
Testing using netdata/container. We have multiple instances installed bare metal, but want to explore using the container instance. 
Looking for ideas or suggestions on how have netdata pull ipmi information. 
I have installed freeipmi.plugin and have run ipmimonitoring and then started a container instance. 
 
Thx ..

**Comment by prologic** [comment]
> I have installed freeipmi.plugin and have run ipmimonitoring and then started a container instance.

Can you elaborate on this a bit more?

AFAIK we don't ship/support the IPMI collector inside our Docker image(s) at this time (yet)... I'll have to check.

**Comment by johncaz** [comment]
Hello 

thank you for responding. 
Was hoping for some suggestions on how to have ipmi stats pulled by netdata that is running in a container? Since IPMI has to be installed on the actual hardware need a way to pull the stats to the netdata instance. 

IDK .. maybe my logic is wrong..

**Comment by ValentinChirikov** [comment]
Hi everyone, i've found no info on adding IPMI to docker netdata. So i figured a way to make it work & i'd like to leave the solution here if someone will also looking for it:

add the parameters below to conatainer
```
  --device=/dev/ipmi0 \
  -e NETDATA_EXTRA_APK_PACKAGES:freeipmi \
```
