### ISSUE TITLE
fping, change ping count -c 

### ISSUE THREAD

**Issue by FabioEight** [netdata/netdata#8746]
Currently it's not possible to change the number of pings sent per round using "-c" option if there are more than 1 hosts.
Editing fping.conf adding the option "-c 1" results in:

2020-04-17 09:07:10: fping.plugin: INFO: starting fping: /usr/local/bin/fping -N -l -Q 15 -p 5000 -c 1 -R -b 56 -i 1 -r 0 -t 5000 192.168.1.1 192.168.1.2
/usr/local/bin/fping: specify only one of c, l

There's any way to change the number of ping sent per round?

**Comment by vlvkobal** [comment]
Check `fping` options in the command line first. The issue you are concerned with is about `fping` usage, not Netdata.
