### ISSUE TITLE
How to customize chart to display traffic separately in ethernet card

### ISSUE THREAD

**Issue by olg33** [netdata/netdata#8753]
Hi,
I installed netdata in a Ubuntu VM  and created a very basic chart to graph traffic at ethernet interface (ens160). Code looks like this:

>   div data-netdata="net.ens160"
                data-title="ens160 (Native)"
                data-chart-library="dygraph"
                data-width="90%"
                data-height="100%"
                data-after="-300"
                ></div>

 
 
The chart displays incoming and outgoing (Rx/Tx) traffic on interface ens160 (ethernet0). However I'd like to create two separate graphics where only RX or Tx traffic is displayed, 

So I'd like to know if there is a unique.id for network interfaces that displays Tx or Rx traffic but not both, or, if there is any additional parameter for id "net.ens160" to obtain the desired results. 

Thank you.

**Comment by ilyam8** [comment]
Hi @olg33 

data-dimensions=""

**Comment by olg33** [comment]
Hi ilyam8,

For incoming traffic I tried:

div data-netdata="net.ens160"
      data-dimensions="in"

But it didn't work. Also tried values like "in_value" but the graph displayed an  empty message stating that no data was coming in.

Am I missing something else?

Thanks.

**Comment by ilyam8** [comment]
I think it is `received` and `sent`

**Comment by olg33** [comment]
Those values did the trick.

Thank you so much!
