### ISSUE TITLE
Netdata restarting mySQL every minute ??

### ISSUE THREAD

**Issue by rbuelund** [netdata/netdata#8761]
On Ubuntu 14 with netdata installed - every minute the mySQL server is restarted. In the auth.log it looks as though this happens because of netdata ??

```cmd
Apr 18 19:32:07 web1 sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 18 19:32:07 web1 sudo: pam_unix(sudo:session): session closed for user root
Apr 18 19:32:10 web1 sudo:   nobody : TTY=unknown ; PWD=/tmp/.netdata-charts.d-EnOWNl9YAO ; USER=root ; COMMAND=/usr/sbin/service mysql status
**Apr 18 19:32:10 web1 sudo:   nobody : TTY=unknown ; PWD=/tmp/.netdata-charts.d-EnOWNl9YAO ; USER=root ; COMMAND=/usr/sbin/service mysql restart**
Apr 18 19:32:10 web1 sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 18 19:32:10 web1 sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 18 19:32:10 web1 sudo: pam_unix(sudo:session): session closed for user root
Apr 18 19:32:10 web1 sudo:   nobody : TTY=unknown ; PWD=/tmp/.netdata-charts.d-EnOWNl9YAO ; USER=root ; COMMAND=/usr/sbin/service proftpd status
Apr 18 19:32:10 web1 sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 18 19:32:10 web1 sudo:   nobody : TTY=unknown ; PWD=/opt/netdata/etc/netdata ; USER=root ; COMMAND=/usr/sbin/service postfix status
Apr 18 19:32:10 web1 sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 18 19:32:10 web1 sudo: pam_unix(sudo:session): session closed for user root
Apr 18 19:32:10 web1 sudo:   nobody : TTY=unknown ; PWD=/tmp/.netdata-charts.d-EnOWNl9YAO ; USER=root ; COMMAND=/usr/sbin/service dovecot status
```

Theese lines (and more) are repating themselves every minte in the log - and every time at exact xx:xx:10 the mysql server does a restart !?

**Comment by ilyam8** [comment]
Hi. How did you install netdata? What is your netdata version? Have you applied some chages after install?

**Comment by rbuelund** [comment]
That is a really god question. I have just been given this problem with a mysql server restarting every minute - nobody knows anything about what has been done on the server!!! But to help my further investigation I need to know if this really is the netdata daemon that is restarting the mysql server? Any clues on why this is happening would also be appreciated.

**Comment by ilyam8** [comment]
No, it is not Netdata. There is no such code and netdata has no permissions to restart services on a system.

**Comment by rbuelund** [comment]
Ok - but can it be because of netdata trying to read the status of mySQL?? May it crashes and then automatically restarts ? Just to eventually rule that possibility out also.

**Comment by ilyam8** [comment]
Source code: https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/mysql/mysql.chart.py

You need to create a user to get netdata collecting mysql metrics, otherwise it cant connect

https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mysql#requirements

Quesries:
https://github.com/netdata/netdata/blob/430c91bfc8656d57d697234468676a88ed2ca36b/collectors/python.d.plugin/mysql/mysql.chart.py#L10-L13

**Comment by rbuelund** [comment]
I believe it is connecting through root ?

But have you any ide what the PWD part of this log line is telling? - that looks like something from netdata: 

Apr 19 09:21:10 web1 sudo:   nobody : TTY=unknown ; PWD=/tmp/.netdata-charts.d-ZeEtGiuZHI ; USER=root ; COMMAND=/usr/sbin/service mysql restart
