### ISSUE TITLE
SNMP collector should allow description

### ISSUE THREAD

**Issue by nikobearrr** [netdata/netdata#8763]
##### Expected behavior

We are using SNMP collector to fetch a lot of SNMP data. We would like to show above status charts what does each value mean, e.g. 1 = OK, 2 = Error. SNMP collector should provide a field "description" to write a description of the chart

**Comment by ilyam8** [comment]
Hi @nikobearrr 

> SNMP collector should provide a field "description" to write a description of the chart

What description are you talking about? There is chart title and you can set it in the snmp module config. The problem with chart title is font size, it is really small which makes title hard to read.

It is better to add that info to the dashboard_info.js, like

https://github.com/netdata/netdata/blob/b395ad961bb88cbdce6e8be6a98ecc046de75f3e/web/gui/dashboard_info.js#L2689-L2719

To keep chanes across upgraded you need to add the changes to the 

> https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info_custom_example.js

**Comment by nikobearrr** [comment]
Hi @ilyam8

Yes, by description I meant this information (like the one in the VCSA). I would like to be able to add those to my graphs which are created by SNMP.

By looking at the SNMP config [here](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/snmp) and the snmp.node.js plugin file [here](https://github.com/netdata/netdata/blob/master/collectors/node.d.plugin/snmp/snmp.node.js) I do not see this supported.

I was not aware I can have custom icons/text for my dashboards as the example in dashboard_info_custom_example. I would prefer to be able to do this directly through the SNMP json config as then all the information stays in 1 place.
