### ISSUE TITLE
Registry hostname not working

### ISSUE THREAD

**Issue by tenent007963** [netdata/netdata#8765]
##### Configuration

Registry node (hostname: not.working.xyz):
         ` [registry]`
                  `enabled = yes`
                  `registry to announce = http://not.working.xyz:19999`
                  `registry hostname = node3 `
Other non-registry nodes(hostname: slave.working.xyz):
         ` [registry]`
                  `enabled = no`
                  `registry to announce = http://not.working.xyz:19999`
                  `registry hostname = node1` / `2`

##### Bug report summary

Netdata registry hostname not resolving properly on all nodes.

_Console output:_
On non-registry nodes:
`invalid URL detected:
main.js:112 http%3A%2F%2Fslave.working.xyz%3A19999%2F#;theme=slate`
`registry search call failed http://not.working.xyz:19999`

On registry nodes:  
> No error output

_Dashboard:_ 
>My nodes: 
 Node1: http://slave.working.xyz:19999/http%3A%2F%2Fslave.working.xyz%3A19999%2F
 Node2: http://slave.working.xyz:19999/http%3A%2F%2Fslave1.working.xyz%3A19999%2F
 Node3: http://slave.working.xyz:19999/http%3A%2F%2Fnot.working.xyz%3A19999%2F

##### OS / Environment

```
Linux proxy 5.0.0-1034-gcp #35-Ubuntu SMP Tue Mar 17 03:56:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 ```netdata v1.21.1```

##### Component Name

[registry]

##### Steps To Reproduce

1. Setup netdata registry following the steps from [the official guide](https://docs.netdata.cloud/registry/#run-your-own-registry)
2. restart netdata using `service netdata restart` and wait for 3 mins

##### Expected behavior

Expected registry itself able to resolve hostname properly and able to point to other nodes without problems.

**Comment by dmpe** [comment]
Yes, I think I am facing the same problem. 
a small example: 
![image](https://user-images.githubusercontent.com/1799661/80356668-0df88580-887a-11ea-95c4-d374cde01367.png)

The url contains spaces and I pretty sure it was not happening in the previous versions

**Comment by jacekkolasa** [comment]
Related to https://github.com/netdata/netdata/issues/8581, fixed now. Unfortunately users need to manually remove broken urls, sorry for that! I hope it's not a big problem, but if it is, we can work on adding a code snippet to remove all broken urls
