### ISSUE TITLE
Possible to attach custom text to alert?

### ISSUE THREAD

**Issue by carsten-AEI** [netdata/netdata#8770]
##### Question summary
(sorry for this potentially stupid question)

I plan to investigate using netdata to monitor a large room full of servers, i.e. each node would run its small netdata instance with/without local database and stream its data to a central host who would try to work through its local alarm criteria.

Currently, we have a lot of local scripts checking various things, but they not only record **if** there is a problem but **what** is the problem. With the various external plugins it should be easy to set-up metrics which would return non-zero in case of problem, but I currently fail to see how I could propagate upstream what is wrong - unless I start encoding various error conditions into values :wink: 

E.g. when looking at [health/health.d/ipmi.conf](https://github.com/netdata/netdata/blob/master/health/health.d/ipmi.conf) I can get an alert if SEL contains something but not what.

If this check is a strictly local one, this may not matter much, but for example, we test NFS mounts between machines and an error could mean, its a local or remote problem and thus would like to cluster/aggregate the results both ways to identify a server not being reachable (assuming local checks do not show a problem).

##### OS / Environment

Any

##### Component Name

collection/alerting

##### Expected results

tagged/custom metadata along with alerts (generated on nodes not necessarily on central collection host)

**Comment by ilyam8** [comment]
hi @carsten-AEI 

Could you elaborate a bit? Probably give some example with (what it would be)

> tagged/custom metadata along with alerts

**Comment by carsten-AEI** [comment]
Sorry for the delayed reply.

Right now, every alert needs to be linked to a chart - unless I did not understand the docs correctly - and a typical alert by email looks like:

```
net_packets.eno2                                             Chart
--
inbound packets dropped ratio = 0.1% the  ratio of inbound dropped packets vs the total number of received  packets of the network interface, during the last 10 minutes                                             Alarm
eno2                                             Family
WARNING                                             Severity
Wed May 13 01:24:12 UTC 2020                                              Time
$this >= 0.1                                             Evaluated Expression
[ $this = 0.1008915 ]                                              Expression Variables
The host has 3 WARNING and 0 CRITICAL alarm(s) raised.
```

For example, we monitor/test various autofs NFS mounts between our servers as a client check. In order not to overwhelm the network and servers, we randomly choose a few from a list and in case a problem appears send this information upstream (good ol' nagios right now). The information we upload here is who is the client and who is the server and what did not work (we do similar repeated tests for other services, e.g. IPMI connectivity, ...).

Again, if I understand netdata enough, if we wanted to convey the same information with netdata, we would need to create one chart for every possible combination of client/servers we would want to monitor and created a templated alert on these, right?

But wouldn't this simple explode as it would roughly scale terribly with the number of servers and clients? In our case, we would look at ~3,000 servers/clients, i.e. for a simple, rarely performed check we would add ~9,000,000 charts per netdata instance per test?

Or did I simply take a wrong turn and I looked at the problem from a wrong angle?

**Comment by ilyam8** [comment]
You understand it right, in order to check/monitor something, you need the metric == a chart with a dimension or dimensions.


> But wouldn't this simple explode as it would roughly scale terribly with the number of servers and clients? 

Well, yes, huge amount of charts is not good and so as a chart with huge amount of dimensions. I think one of the fundamental problems of `nd` - you dont put a metric into database, you put a chart => chart is always on the dashboard, if it is not you cant perfrom `health` checks, etc.
