### ISSUE TITLE
allow separate configuration of network alarms for cgroups

### ISSUE THREAD

**Issue by ScottAtConvesio** [netdata/netdata#8773]
# Feature idea summary
duplicate net.conf for cgroups to allow separate alarm thresholds for cgroups from the entire node.

##### Details:
The network alarms (packet drop, netdata_budget, etc) configuration is shared between the node and cgroups. In our setup, we get alarms from containers that have very little traffic -- as an example, 400 packets in 10 minutes. So 8 packets dropped in 10 minutes becomes an alarm condition. But the node is pulling hundreds of kb to over 1gb of data, so considerably more packets. That makes it difficult to set meaningful alarm thresholds.

Essentially I'm looking to duplicate net.conf to tweak alarm values for cgroups.

**Comment by ilyam8** [comment]
Hey, @ScottAtConvesio. It is possible to create a different set of alarms for cgroups using [families](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-families) filter.

[We've excluded](https://github.com/netdata/netdata/pull/10806) cgroups net ifaces from packets dropped alarms.
