### ISSUE TITLE
Chart results not available if format=prometheus after a few minutes

### ISSUE THREAD

**Issue by marcomusso** [netdata/netdata#8778]
I'm trying to use https://github.com/mo0nsniper/netdata/blob/master/charts.d/services.chart.sh to monitor systemd service (because app_groups doesn't return anything if the process is not running) but I get always the correct value as "raw":

```
$ curl -s 'localhost:19999/api/v1/allmetrics' | grep NETDATA_SERVICES_SYSTEM_SERVICES_NAEMON
NETDATA_SERVICES_SYSTEM_SERVICES_NAEMON="1"      # Status
```

But nothing for prometheus:

```
$ curl -s 'localhost:19999/api/v1/allmetrics?format=prometheus&source=as-collected' | grep 'family="naemon"'
$
```

Before heading to the solution of @mo0nsniper I checked app_groups.conf which returns 1 if the process is running but no metric if the process is not running, the chart is even empty inthe webui.

What can cause this behaviour?

##### OS / Environment

CentOS 7, netdata 1.21-1

##### Expected results

I was expecting the constant output of the metric in Prometheus format

![chart stops exporting metrics to Prometheus](https://user-images.githubusercontent.com/4507548/79763465-6a145480-8324-11ea-83b7-0c10ca0ab25f.png)

the only entry in error.log is:

```
2020-04-20 13:54:06: netdata ERROR : PLUGINSD[charts.d] : requested a SET to dimension with id 'systemd-timedated' on stats 'Services.System_services' (Services.status) on host 'dev-mastercluster-ams3z1-gator.umi.tt3.com', which does not exist. Disabling it.
```

That means the chart gets disabled?

**Comment by ilyam8** [comment]
> 2020-04-20 13:54:06: netdata ERROR : PLUGINSD[charts.d] : requested a SET to dimension with id 'systemd-timedated' on stats 'Services.System_services' (Services.status) on host 'dev-mastercluster-ams3z1-gator.umi.tt3.com', which does not exist. Disabling it.


We need to add a dimenstion before update it.

create:
```sh
CHART 'example.random' '' 'A Random Number' 'random' 'random' '' '' '70000' '1' '' 'go.d' 'example'
DIMENSION 'random0' 'random 0' '' '' '' ''
DIMENSION 'random1' 'random 1' '' '' '' ''
```

```sh
BEGIN example.random
SET random0 = 10
SET random1 = 51
END
```

If there is new dimension we cant SET it

```sh
BEGIN example.random
SET random0 = 10
SET random1 = 51
SET random2 = 51
END
```

We have to add it

resend chart with all dims (+ the new one)
```sh
CHART 'example.random' '' 'A Random Number' 'random' 'random' '' '' '70000' '1' '' 'go.d' 'example'
DIMENSION 'random0' 'random 0' '' '' '' ''
DIMENSION 'random1' 'random 1' '' '' '' ''
DIMENSION 'random2' 'random 2' '' '' '' ''
```

or with the new only

```sh
CHART 'example.random' '' 'A Random Number' 'random' 'random' '' '' '70000' '1' '' 'go.d' 'example'
DIMENSION 'random2' 'random 2' '' '' '' ''
```

**Comment by ilyam8** [comment]
It seems the plugin you are using has bugs

**Comment by marcomusso** [comment]
Ah good to know! Thanks! I'll try to fix it!

**Comment by marcomusso** [comment]
If I understood correctly the problem (at least in this case) is that a systemd unit **disappears** between runs and all dimensions should be there once defined.
When debugging (I should have done before to give more context) I can see that service going away after a few runs.

But then: why the raw data is always reporting the status for one dimension and the Prometheus export isn't ?

**Comment by ilyam8** [comment]
I dont know what is going on there, you are using third-party module.

**Comment by marcomusso** [comment]
Ok, right let's stick to what is needed for a chart to work properly and forget about this 3rd party script.

So there is a DIMENSION that appears after the CREATE part. If there is no state between runs how can I detect that a new DIMENSION needs to be added (and trigger an new-dimension-only DIMENSION)?

**Comment by ilyam8** [comment]
We send set of charts on starts:

```sh
CHART 'example.random' '' 'A Random Number' 'random' 'random' '' '' '70000' '1' '' 'go.d' 'example'
DIMENSION 'random0' 'random 0' '' '' '' ''
DIMENSION 'random1' 'random 1' '' '' '' ''
```

During runtime we send updates every update_every:

```sh
BEGIN example.random
SET random0 = 10
SET random1 = 51
END
```

If there are new dimensions and we need to update chart definitions during runtime we need to resend the chart:


```sh
CHART 'example.random' '' 'A Random Number' 'random' 'random' '' '' '70000' '1' '' 'go.d' 'example'
DIMENSION 'random0' 'random 0' '' '' '' ''
DIMENSION 'random1' 'random 1' '' '' '' ''
DIMENSION 'random2' 'random 1' '' '' '' ''
```


If we need to remove dimenstion we need to resend the chart and set `obsolete` flag fot the dimension. It takes some time to remove dimension (configuratble interval) to remove completely until then it appears with `-` value on the dashboard. If we want to hide the dimension we need to add `hidden` flag to the dimension (in addition to `obsolete`)


```sh
CHART 'example.random' '' 'A Random Number' 'random' 'random' '' '' '70000' '1' '' 'go.d' 'example'
DIMENSION 'random0' 'random 0' '' '' '' ''
DIMENSION 'random1' 'random 1' '' '' '' ''
DIMENSION 'random2' 'random 1' '' '' '' 'obsolete hidden'
```


More details: > https://learn.netdata.cloud/docs/agent/collectors/plugins.d#external-plugins-api

**Comment by ilyam8** [comment]
I think #6683 is a proper fix.

**Comment by marcomusso** [comment]
Ok, I have to assume to keep some sort of states between runs or re-evaluate #6683 accounting option.

What about the problem of the metric not being available (for a non-changing DIMENSION) if `allmetrics` is called with format and source?

**Comment by ilyam8** [comment]
I mean i need to try those systemd go libs and see what info we could get from them. Probably there are several collectors.
