### ISSUE TITLE
Document how to claim nodes in Kubernetes

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#8779]
From @cakrit in #8755: 

> When this is finalized, please state also what we'll do for k8s and especially our helm chart.

We need a section in `claim/README.md` that explains how users running Netdata in k8s can claim their nodes.

@cakrit or @amoss — Can either of you provide me with more information on this, or point me to another engineer who has some experience in this. I know Ilya has been doing k8s work, but I'm not sure if it's related to this. I'm also completely unversed in k8s, so unlike Docker, I have no foundation to start from.

**Comment by cakrit** [comment]
@knatsakis or @ncmans should be able to provide the info.

**Comment by ncmans** [comment]
@ilyam8 do we have instructions on how to claim agents on kubernetes/via our helm chart?

**Comment by ilyam8** [comment]
as far as i know we dont, i didnt think about it at all but i guess we need only to add some `args` (if token and rooms are set) 🤷‍♂️

**Comment by ilyam8** [comment]
i think there are some problems we need to address with persistent claiming stuff too 🤔

**Comment by cakrit** [comment]
The task in on the Cloud SRE team to specify how claiming will be done in k8s. Claiming should mandate that `master.alarms.persistence` is `true`. For the link between the two, see and reply to [this comment](https://github.com/netdata/helmchart/issues/93#issuecomment-622363852).

**Comment by cakrit** [comment]
Waiting on @knatsakis for this one, it shouldn't be closed.

**Comment by lgg42** [comment]
I'm interested in this. I could open a PR on the helm chart for claiming nodes. Our cluster autoscales up and down so we fancy this feature in order to use netdata cloud.

**Comment by knatsakis** [comment]
@joelhans now that we are done with netdata/helmchart#79 we should be able to proceed with this one.

The instructions for claiming with the Helm chart can be summarized as:

- Enable peristence
- Set `parent.claiming.enabled`, `parent.claiming.token` and `parent.claiming.rooms`

Note that this is for claiming the `parent` only. You can have a look at netdata/helmchart#79

LMK if you need anything else

**Comment by joelhans** [comment]
I have access to a k8s cluster again, so I'll be experimenting with claiming and figuring out how to best document the process.

**Comment by joelhans** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add documentation for claiming a k8s cluster parent node](https://trello.com/c/rdKDQlUb/261-add-documentation-for-claiming-a-k8s-cluster-parent-node)
