### ISSUE TITLE
MySQL/MariaDB slave-status with named slaves

### ISSUE THREAD

**Issue by Hufschmidt** [netdata/netdata#8785]
##### Bug report summary
The [mysql](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/mysql/mysql.chart.py#L11) chart python plugin uses the command `SHOW SLAVE STATUS;` to query the information, but MariaDB supports multiple/named slaves, which either requires `SHOW SLAVE "<name>" STATUS;` or `SHOW ALL SLAVES STATUS;` (prefered)  to be used.

##### OS / Environment
* MariaDB 10.x

##### Netdata version
v1.21.1

##### Component Name
* MySQL Python plugin

##### Steps To Reproduce
* Bootstrap 2 MariaDB servers (eg. using docker)
* Use syntax `CHANGE MASTER "<name>" TO [...]` instead of `CHANGE MASTER TO [...]` to connect slave with master

##### Expected behavior
* Slave information (eg. seconds behind master) should show up in netdata

##### Additional Information
* Documentation for MariaDB: 
  * Slave configuration: <https://mariadb.com/kb/en/change-master-to/>
  * Slave status: <https://mariadb.com/kb/en/show-slave-status/>
* Documentation for MySQL
  * Slave configuration: <https://dev.mysql.com/doc/refman/8.0/en/change-master-to.html>
  * Slave status: <https://dev.mysql.com/doc/refman/8.0/en/show-slave-status.html>
* The syntax differs between MariaDB (connection-name) and MySQL (channels), so the plugin would probably need to be able to detect if mysql or mariadb is used and be able to support multiple slaves/charts.

**Comment by ilyam8** [comment]
Hi

> The syntax differs between MariaDB (connection-name)

`Connection_Name` returned only with `SHOW ALL SLAVES STATUS`

> https://mariadb.com/kb/en/show-slave-status/#column-descriptions

@Hufschmidt If there are severl source and we use `SHOW SLAVE STATUS` result is several rows w/o `Connection_name`, right? like

```cmd
*************************** 1. row ***************************
                Slave_IO_State: Waiting for master to send event
                   Master_Host: master
                   Master_User: my_repl_user
                   Master_Port: 3306
                 Connect_Retry: 10
... 
*************************** 2. row ***************************
                Slave_IO_State: Waiting for master to send event
                   Master_Host: master
                   Master_User: my_repl_user
                   Master_Port: 3306
                 Connect_Retry: 10
...
```

**Comment by ilyam8** [comment]
So basiaclly we need to use `SHOW SLAVE STATUS;` for `mysql` and `SHOW ALL SLAVES STATUS;` for `mariadb`

We are going to support only `go` version and deprecate python at some point, there is a PR that adds all features/fixes to the `go` version

> https://github.com/netdata/go.d.plugin/pull/404

I gonna fix the problem in that PR
