### ISSUE TITLE
ebpf collector and netdata-kernel sources review

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#8788]
- Validate custom ebpf library's compatibility against multiple kernel versions, depending on nominal kernel version ranges that define the various builds.
    - Validate that the chosen kernel version ranges cover all cases
    - Identify dead code and remove any `#if`s pointing to irrelevant kernel versions
         - Reduce the number of library builds
- Validate that the 2 libbpf builds cover all supported kernels.
- Validate that kprobe functionality matches the user output in ebpf VM program.
    - Examine the linux kernel source code for multiple kernel versions.
    - Validate the coverage of the probes.
         - Identify cases that are missed.
- Investigate tracepoints versus kprobes in ebpf VM program.
     - Investigate whether tracepoints can replace existing kprobes.
          - Compare syscalls to existing probed functions.
     - Tracepoints are *practically kernel version agnostic and simplify ebpf compatibility.
        (*raw tracepoints only supported above kernel version 4.17)
- Validate ebpf VM program kprobe kernel compatibility hack.
     - Investigate the stability of the system when misrepresenting the kernel version the ebpf program has been built against.

**Comment by mfundul** [comment]
It's not about the functions though, it's what we present to the user. So if we're telling the user it's about `write()` syscalls, then it doesn't really matter if we cannot cover `vfs_write()`, as long as we're catching all relevant syscalls. To conclude, it's not whether the kprobes are technically equivalent, but whether the user-facing output can be reproduced.

**Comment by thiagoftsm** [comment]
> It's not about the functions though, it's what we present to the user. So if we're telling the user it's about `write()` syscalls, then it doesn't really matter if we cannot cover `vfs_write()`, as long as we're catching all relevant syscalls. To conclude, it's not whether the kprobes are technically equivalent, but whether the user-facing output can be reproduced.

All right, I got it, but unless I am missing something we said for users that we are monitoring the `vfs_` functions on the dashboard ( `web/gui/dashboard_info.js` ) and also in the documentation ( `collectors/ebpf_process.plugin/README.md` ). I do not remember other places that we documented these features related to IO.

**Comment by mfundul** [comment]
I understand we're telling our users about `vfs_write` etc functions, but we don't tell them what it means and I don't believe many understand what those functions translate to.

I am arguing that it could be better to trace syscalls, group them into write/read categories and present this information to the users instead.

If we were to do that, then it would be easier for a file-system tracing ebpf program to maintain kernel compatibility.
