### ISSUE TITLE
Values for chart colors ant themes

### ISSUE THREAD

**Issue by olg33** [netdata/netdata#8789]
Hi,
I'm learning the basics of dashboard creation and currently I'm trying to get information in the following items:

The data-colors parameter. Is there a table or a document that shows all the possible values we can use?

> <div data-netdata="unique.id"
 data-colors=" ? "
 ></div>

The netdataTheme. Same, any document that shows values available.
 

> var netdataTheme = '?'

I've been looking for this info with no kuch, so any help would be appreciated.

Thank you.

**Comment by ilyam8** [comment]
had quick search through the source code

https://github.com/netdata/netdata/blob/a153129c0c01492d44073a141f5ee1d5e174d037/web/gui/dashboard.js#L1853-L1872

> The netdataTheme.

I think themes are: black, white.

**Comment by olg33** [comment]
Thanls ilyam, much appreciated.
