### ISSUE TITLE
Add ability to show the server ip in the alert

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8792]
##### Feature idea summary
We have a master/slave Netdata architecture and it would be a good idea if we can have the machine IP (the source IP of the slave sending the metric) in the alert templates.

**Comment by thiagoftsm** [comment]
To bring this new feature we would need to add to `host` structure the ip, this information is already present when we start the thread to receive the information, but we do not store it inside the `host`.

After to bring this variable to `host`, we need to change `alarm-notify.sh` to consider more one argument and finally change the function `health_alarm_execut()` (health/health.c) .

Thank you for your suggestion @yasharne , I will talk with the team for we bring this feature.

**Comment by carsten-AEI** [comment]
My question #8770 (sorry for self-promotion) is somehow related as it would very possibly also need to extend the host data structure and `alarm-notify.sh` to accommodate a `reason` text in the alert and - if considered - would probably be easier if tackled together with this issue.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
