### ISSUE TITLE
mdstat.mdx_disks alarm doesn't work

### ISSUE THREAD

**Issue by dtipro** [netdata/netdata#8793]
##### Bug report summary
The default alarm for failed mdstat disks no longer works, the "total" variable was replaced by "down" in https://github.com/netdata/netdata/pull/6164 but the alarm wasn't updated to reflect this change.

##### OS / Environment

```
Linux hostname 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 netdata v1.21.1

##### Component Name

health

##### Steps To Reproduce

1. Navigate to alarms > mdstat
2. mdstat disks shows `-`

##### Expected behavior

mdstat disks should show number of failed disks.

**Comment by ilyam8** [comment]
@dtipro thx for reporting!

**Comment by thiagoftsm** [comment]
I am already creating a PR for it.

**Comment by thiagoftsm** [comment]
@ilyam8, please, take a look on #8795.

@dtipro , case you have conditions to also test the PR, it will be great.

Thank you for your report.

**Comment by dtipro** [comment]
@thiagoftsm The changes in https://github.com/netdata/netdata/pull/8794 fixed the issue, it now displays the correct number of disks instead of a -.

**Comment by thiagoftsm** [comment]
Thank you for your time @dtipro !
We expect to merge this PR soon.
