### ISSUE TITLE
Collector frequency

### ISSUE THREAD

**Issue by YHYJ** [netdata/netdata#8798]
##### Question summary

What is the maximum frequency of the collector?

##### OS / Environment

Linux / not docker

**Comment by ilyam8** [comment]
There is global minimum `update_every` in the `[global]` section of the `netdata.conf`.

You can change it for the specific plugin in the `netdata.conf` (internal plugins) or plugin configuration file (external plugins).

And you can set `update_every` per plugin job (python.d, go.d).

**Comment by YHYJ** [comment]
Thanks!
I mean how quickly the collector frequency can be reached
I set `update_every = 0.1`, there is no data on the page, so the minimum value of update is 1?
I want the frequency to reach 100 Hz, can i?

**Comment by ilyam8** [comment]
No, it is possible. Minimum is 1 second. `update_every` is in seconds.

**Comment by Ferroin** [comment]
There has been discussion a couple of times in the past about the possibility of sub-second collection intervals. It's usually not gotten anywhere because it's not a particularly high priority.

**Comment by YHYJ** [comment]
Ok.
Now I set `update_every = 2`, but why the page refreshes every 4 seconds

**Comment by ilyam8** [comment]
Browser page?

**Comment by YHYJ** [comment]
Yes!

**Comment by mfundul** [comment]
It also depends no what you're displaying at the time. If you are using `memory mode = dbengine` and you change the `update every` interval then the old data are not discarded, but are displayed altogether with a common frequency. If you want to only see the latest data, stop netdata and delete the database which would be at `var/cache/netdata/dbengine`.

**Comment by YHYJ** [comment]
I mean set `update_every = 2`, according to the document browser page should also be refreshed every 2s, but why is it refreshed every 4s

**Comment by ilyam8** [comment]
For me it is 2.

**Comment by YHYJ** [comment]
1. Now `update_every = 1` (`update_every = 2` has had similar problems)
2. I use ”chart zoom in“, as shown in the figure, only see the data of 16:06:20 and 16:06:22, there is no data of 16:06:21
![20](https://user-images.githubusercontent.com/21995281/80301892-4f852400-87d9-11ea-8940-051f6d1c8bdc.png)
![22](https://user-images.githubusercontent.com/21995281/80301905-6166c700-87d9-11ea-9140-eceb31d862b1.png)
3. I am not sure it can be reproduced, this also seems to be related to the frequency of writing data to redis

**Comment by ilyam8** [comment]
global `update_every` is min update_very, it doesnt mean all modules collect data with that freq, but a collector update_every >= global update_every.

PSI 

https://github.com/netdata/netdata/blob/1115a0cf78e6f0d1bddb5b3b4627b5817f10d9f0/collectors/proc.plugin/proc_pressure.c#L8-L9

**Comment by YHYJ** [comment]
**global** `update every = 1`, I haven't modified it, and there is no `update_every` defined in "HPU.chart.py " and "HPU.conf", I always use **[plugin: python.d]** `update every`

**Comment by ilyam8** [comment]
I see no problem, your [screenshot](https://github.com/netdata/netdata/issues/8798#issuecomment-619508052) is from proc plugin module 
> https://github.com/netdata/netdata/blob/master/collectors/proc.plugin/proc_pressure.c

Its min `update_very` is 2.

**Comment by YHYJ** [comment]
ok, thanks!
