### ISSUE TITLE
Container Restart Policy

### ISSUE THREAD

**Issue by ElleshaHackett** [netdata/netdata#8800]
##### Feature idea summary
https://hub.docker.com/r/netdata/netdata described a Docker run commands but they don't include a restart policy. 

##### Expected behavior
I would be default include `--restart=unless-stopped` in those commands so that when a host machine is restarted the Container also startup again if it wasn't manually stopped. Alternatively I would suggest to at least mention the `--restart` flag as optional in the documentation with a note that host restart doesn't automatically start the Netdata container.

**Comment by prologic** [comment]
@joelhans Can you take care of this?

**Comment by joelhans** [comment]
@prologic Yeah, I'll take care of this and #8663 today.
