### ISSUE TITLE
add tags or/and fields to measruments for opentsdb backend

### ISSUE THREAD

**Issue by vpapas** [netdata/netdata#8801]
In case the backend is set to opentsdb it would be nice to have some tags (or/and field keys) in order to reduce the number of measurements and reduce cardinality.

In our setup we use influxdb as backend and as a result we have millions of measurements and series with only one tag key (host) which results to an unresponsive database (high CPU and memory usage) due to only one index.
 
You can see in the screenshot below the difference between netdata and telegraf (telegraf has less measuremnts):

![image](https://user-images.githubusercontent.com/17230013/79973420-35c5a300-84a0-11ea-982d-7931b5c428e8.png)
 

For example, instead of the following series (44 measurements):

```
netdata.apps.cpu_system.antivirus
netdata.apps.cpu_system.apps.plugin
netdata.apps.cpu_system.auth
netdata.apps.cpu_system.backup
netdata.apps.cpu_system.balancer
netdata.apps.cpu_system.build
netdata.apps.cpu_system.charts.d.plugin
netdata.apps.cpu_system.containers
netdata.apps.cpu_system.cron
netdata.apps.cpu_system.dhcp
netdata.apps.cpu_system.email
netdata.apps.cpu_system.fail2ban
netdata.apps.cpu_system.fping
netdata.apps.cpu_system.ftpd
netdata.apps.cpu_system.httpd
netdata.apps.cpu_system.java
netdata.apps.cpu_system.kernel
netdata.apps.cpu_system.ksmd
netdata.apps.cpu_system.logs
netdata.apps.cpu_system.media
netdata.apps.cpu_system.named
netdata.apps.cpu_system.netdata
netdata.apps.cpu_system.nfs
netdata.apps.cpu_system.nms
netdata.apps.cpu_system.node.d.plugin
netdata.apps.cpu_system.nosql
netdata.apps.cpu_system.other
netdata.apps.cpu_system.php
netdata.apps.cpu_system.print
netdata.apps.cpu_system.proxy
netdata.apps.cpu_system.python.d.plugin
netdata.apps.cpu_system.rabbitmq
netdata.apps.cpu_system.samba
netdata.apps.cpu_system.sidekiq
netdata.apps.cpu_system.sql
netdata.apps.cpu_system.ssh
netdata.apps.cpu_system.system
netdata.apps.cpu_system.tc_qos_helper
netdata.apps.cpu_system.time
netdata.apps.cpu_system.timedb
netdata.apps.cpu_system.unicorn
netdata.apps.cpu_system.vpn
netdata.apps.cpu_system.wifi
netdata.apps.cpu_system.zookeeper
```
Netdata should send the following (1 measurement):

measurement: netdata.apps.cpu_system
tags key: process
tag key values for key="process":

- antivirus
- apps.plugin
- auth
- backup
- balancer
- build
- charts.d.plugin
- containers
- cron
- dhcp
- email
- fail2ban
- fping
- ftpd
- httpd
- java
- kernel
- ksmd
- logs
- media
- named
- netdata
- nfs
- nms
- node.d.plugin
- nosql
- other
- php
- print
- proxy
- python.d.plugin
- rabbitmq
- samba
- sidekiq
- sql
- ssh
- system
- tc_qos_helper
- time
- timedb
- unicorn
- vpn
- wifi
- zookeeper

This approach will create more indexes to the database and data exploration will be faster.

**Comment by vlvkobal** [comment]
There is a plan to implement labels on the metric level, but it's an epic project which involves a database redesign. Some discussions and links are in #6503, #7891.

Right now you can use the `send charts matching` option in the `[backends]` section.

**Comment by vlvkobal** [comment]
Closed in favor of a [label & tag support product epic](https://github.com/netdata/product/issues/915).
