### ISSUE TITLE
Handle components that are optional at runtime as optional components in our Docker images.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8805]
Right now, our Docker images are huge. They unconditionally bundle all of the dependencies, including ones which are optional at runtime, even though users may not need all of them.

it would be nice to support handling those dependencies that are optional at runtime _at runtime_ in the Docker images, thus reducing our Docker image size and cutting down on the potential attack surface for users who don't need them.

My initial thought is to have an environment variable listing what packages to fetch and install on startup, to all be handled as part of the entry-point script.

This will need both product grooming and technical grooming before going any further.

**Comment by ilyam8** [comment]
>  They unconditionally bundle all of the dependencies

Is it possible to ge a list of these dependencies and their sizes?

**Comment by prologic** [comment]
> My initial thought is to have an environment variable listing what packages to fetch and install on startup, to all be handled as part of the entry-point script.

This is what the Plex image does. So 👍
