### ISSUE TITLE
Build failed: Check your system clock

### ISSUE THREAD

**Issue by lamka02sk** [netdata/netdata#8806]
#### Question summary
I am trying to install netdata on our new servers but can't figure out why is this error happening. Basically, build is failing with the following error:
```
checking whether build environment is sane... configure: error: newly created file is older than distributed files!
Check your system clock
 FAILED
 ```

When I checked time with `date` and `hwclock` commands, there is nothing wrong with it. I also installed `ntp` to ensure that time is synchronized. There is just one thing that is different on this server from other servers I use netdata on. The system timezone was changed in OS post-install script. This is what the script looks like:
```
locale-gen sk_SK.UTF-8
localectl set-locale LANG=sk_SK.UTF-8
echo "export LANG=sk_SK.UTF-8" >> /root/.bashrc
timedatectl set-timezone Europe/Bratislava
```

I have no idea what might be wrong and I seem to be the only one having this issue :(

##### OS / Environment
Ubuntu Server 18.04 (4.15.0-91-generic)
No containers or VMs used

##### Expected results
Build should not fail

**Comment by prologic** [comment]
Would you be able to provide some more information?

- How did you attempt to installer netdata? Please show us the command used.
- What is the output of `date` and `realpath /etc/localtime`
- The full output logs of your attempted install.
- The contents of `config.log` if you can find that

Thanks!

**Comment by lamka02sk** [comment]
- How did you attempt to installer netdata? Please show us the command used.
I used command from your website as usual without any changes: `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

- What is the output of `date` and `realpath /etc/localtime`
`date` outputs `Št apr 23 13:06:27 CEST 2020`, which is the correct date and time. `realpath /etc/localtime` outputs `/usr/share/zoneinfo/Europe/Bratislava` also as expected.

- The full output logs of your attempted install.
https://gist.github.com/lamka02sk/526b376392713fb9f23488ef8689fe2a#file-gistfile1-txt

- The contents of `config.log` if you can find that
https://gist.github.com/lamka02sk/aae0907fec27b92dfefd9977b56809c6#file-gistfile1-txt

Thank you!

**Comment by prologic** [comment]
@lamka02sk Are you still able to reproduce this with a new attempt? I'm not able to determine any root cause from the logs you have provided (_thank you_). Please make sure your clocks are in fact in sync (_even a couple of seconds out can cause this_).

**Comment by lamka02sk** [comment]
So, I was curious and inspected the generated ./configure file...and I found the problem! Installer is using `ls` command to check if the created test file is newer than distributed files. We replaced `ls` with `exa`, which is _mostly_ compatible and unfortunately this check isn't.

I am sorry about any trouble. I hope this will help someone in the future.

**Comment by prologic** [comment]
> We replaced ls with exa, which is mostly compatible and unfortunately this check isn't.

TIL: `ex`! Can you link me to this? I've never heard of anyone replacing `ls` beyond relacing coreutils with something like busybox.

**Comment by lamka02sk** [comment]
`exa` is `ls` replacement written in Rust. It is not really a drop-in replacement (many options are the same, but also many are different), but it has much better default settings and Git support! https://the.exa.website/
What we did is we basically replaced ls binary inside /bin folder with exa binary and updated ls aliases like this:
```
wget -c https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
unzip exa-linux-x86_64-0.9.0.zip
rm exa-linux-x86_64-0.9.0.zip
mv /bin/ls /bin/l
mv exa-linux-x86_64 /bin/ls
echo "alias ls=\"ls\"" >> /root/.config/fish/config.fish # Web use fish, but it will be very similar for bash
```
