### ISSUE TITLE
Netdata not showing Virtual Network Interfaces for VMs on xcp-ng

### ISSUE THREAD

**Issue by biggen1684** [netdata/netdata#8810]
Netdata is currently not showing virtual network interfaces for VMs on xcp-ng when looking at the default Netdata dashboard as shown below:

![netdata_no_nic](https://user-images.githubusercontent.com/26392652/80101369-eb433580-8536-11ea-8cda-64f2ecdd5ebf.png)

This was noted by @vlvkobal [during the initial build of Netdata for xcp-ng](https://github.com/netdata/netdata/issues/5357#issuecomment-475668021) and it doesn't appear it was ever resolved.  I've created a duplicate [ticket](https://github.com/xcp-ng/xcp/issues/379) over at xcp-ng as I'm not sure if its an issue with Netdata getting metrics or xcp-ng reporting metrics.

This is all with Netdata build v1.19.0 which is the build that is packaged and supported with xcp-ng 8.1.

As it stands currently, its not possible to properly monitor network activity on any VMs via Netdata on xcp-ng.

**Comment by vlvkobal** [comment]
https://github.com/xcp-ng/xcp/issues/379:
> stormi moved this from To Do to Need dev in Team board on 10 Jul

It looks like we can do nothing with the xenstat plugin until the functionality is available from `libxenstat`.

I'm closing this. Please reopen the issue when conditions for further development on the Netdata side are in place.
