### ISSUE TITLE
Add support for auto claiming a freshly installed NetAgent agent via kickstart

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8819]
As per title.

TBD.

cc @amoss @dim08

**Comment by manos-saratsis** [comment]
Same should be for users installing from source, the supports needs to be added to netdata-installer.sh

**Comment by prologic** [comment]
> Same should be when installing from source, the support needs to be added to netdata-installer.sh

FYI `kickstart.sh` actually calls out to `netdata-installer.sh` and uses a lot of stuff in our `functions.sh`. The `kickstart-static64.sh` is a bit more special; but yes we will of course make this work "everywhere" :) That's the plan!

**Comment by cakrit** [comment]
So here we just provide 3 more command line params and at the end, after installation is completed and if the params where provided, we call the claiming script, right?

**Comment by prologic** [comment]
Sounds reasonable to me. 👍
