### ISSUE TITLE
2 servers same version diffrent UI

### ISSUE THREAD

**Issue by BCNelson** [netdata/netdata#8829]
##### Question summary
I have two servers both running Ubuntu 18.04 and vv1.21.1-93-ge5a1128f
One has what I think is the normal UI the other is slightly different.
![image](https://user-images.githubusercontent.com/5659892/80334785-765e4d00-880f-11ea-89f0-3a4e018697e1.png)
![image](https://user-images.githubusercontent.com/5659892/80334815-8fff9480-880f-11ea-8c06-44c7b54a0c59.png)
Any Ideas on what I did
##### OS / Environment
ubuntu 18.04/ vv1.21.1-93-ge5a1128f

**Comment by thiagoftsm** [comment]
Hi @BCNelson ,

Netdata brought a new dashboard wih the last release, it is possible you are having problem with browser cache, or one is using the `classic` dashboard, while the other is using the `react` dashboard.

Best regards!

**Comment by BCNelson** [comment]
Thanks it was browser cache.
