### ISSUE TITLE
Netdata slave stores dbengine with the option web=none

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8832]
##### Bug report summary

Although we have set the slaves to only stream the metrics and disabled dbengine by setting `memory mode = none` in the `netdata.conf` file, I got this alert on one of the slaves:
![image](https://user-images.githubusercontent.com/7656049/80363540-9aff0700-8899-11ea-9ba7-2d8e3281ea5d.png)
after checking the `/opt/netdata/var/lib/netdata/health` and `/opt/netdata/var/cache/netdata/dbengine` I realized there are database files in them:
![image](https://user-images.githubusercontent.com/7656049/80363819-06e16f80-889a-11ea-8f4e-35863235acbc.png)
![image](https://user-images.githubusercontent.com/7656049/80363841-0ea11400-889a-11ea-9c03-857f9b2df8b7.png)

##### OS / Environment

```
Linux redis-03.db.x.y.z 4.4.0-171-generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.6 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.6 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

 
various netdata version from 1.19.0 to 1.21.1
##### Component Name

dbengine

**Comment by mfundul** [comment]
Did this alarm run on the master's database or in the slave's dashboard?

In general, changing settings in `netdata.conf` requires restarting the agent to be applied. You can safely delete the files in `var/cache/netdata/dbengine/` if they are not being used. Can you share the `error.log` of the slave?

**Comment by yasharne** [comment]
@mfundul This alert is on the slaves' dashboard and we have never enabled the DB engine on our slaves, so I haven't changed the configuration file. The error logs were disabled so I don't have any logs to share now.

**Comment by mfundul** [comment]
`dbengine` is the default memory mode so another explanation could be that `netdata.conf` is wrong, corrupted or unreadable in the slave.

**Comment by yasharne** [comment]
@mfundul This is the `netdata.conf` file, the only potential problem I see is a different indention:
```
#
# Ansible managed
#
[global]
	update every = 10
    memory mode = none
	error log = False 
	debug log = False
	access log = False

[web]
	mode = none

[registry]
    enabled = False
    registry to announce = http://172.16.76.7:19999

[plugin:python.d]
	command options = -ppython3

[example.random]
	enabled = no

[example.random2]
	enabled = no	

[plugin:proc:/proc/net/sockstat6]
	ipv6 TCP sockets = False
	ipv6 UDP sockets = False
	ipv6 UDPLITE sockets = False
	ipv6 RAW sockets = False
	ipv6 FRAG sockets = False

[system.ipv6]
	enabled = False

[ipv6.packets]
	enabled = False

[ipv6.mcast]
	enabled = False

[ipv6.mcastpkts]
	enabled = False

[ipv6.icmp]
	enabled = False

[ipv6.icmprouter]
	enabled = False

[ipv6.icmpneighbor]
	enabled = False

[ipv6.icmpmldv2]
	enabled = False

[ipv6.icmptypes]
	enabled = False

[ipv6.udppackets]
	enabled = False

[ipv6.ect]
	enabled = False

[ipv6.sockstat6_tcp_sockets]
	enabled = False

[ipv6.sockstat6_udp_sockets]
	enabled = False

[ipv6.sockstat6_raw_sockets]
	enabled = False

[ipv6.errors]
	enabled = False

[ipv6.udperrors]
	enabled = False

[ipv6.udperrors]
	enabled = False
```

**Comment by yasharne** [comment]
@mfundul Can I also delete `health` directory inside  `/opt/netdata/var/lib/netdata/` on the slave's machine safely?

**Comment by mfundul** [comment]
> 
> 
> @mfundul Can I also delete `health` directory inside `/opt/netdata/var/lib/netdata/` on the slave's machine safely?

It's safe as long as the netdata service is stopped.

**Comment by mfundul** [comment]
@yasharne if this is still an issue can you please turn on error logging for the slave that is misbehaving?

**Comment by yasharne** [comment]
I fixed the spacing problem in the `netdata.conf` file and the then stopped the netdata and deleted both health and dbengine directories inside `/opt/var/netdata` and started the netdata service again and I don't see health and dbengine databases being generated again, So I think the problem was spacing 
Thanks @mfundul

**Comment by mfundul** [comment]
> 
> 
> I fixed the spacing problem in the `netdata.conf` file and the then stopped the netdata and deleted both health and dbengine directories inside `/opt/var/netdata` and started the netdata service again and I don't see health and dbengine databases being generated again, So I think the problem was spacing
> Thanks @mfundul

That's great! Closing this then.
