### ISSUE TITLE
Add the functinallity to disable the nodes feature

### ISSUE THREAD

**Issue by misterbit-pro** [netdata/netdata#8833]
##### Feature idea summary
Add the ability to disable the nodes feature. The reason is that there are people like me who only have a server for private use and most of the time this is only one server. So the sign up and every thing else is also not required.

##### Expected behavior
1. The option to disable at build time with a flag
2. In the settings page

Thanks for developing such a great tool.

**Comment by ilyam8** [comment]
Hey, @misterbit-pro.

Assuming you are referring to the Netdata Cloud. You can disable it, see https://learn.netdata.cloud/docs/agent/aclk#disable-the-aclk
