### ISSUE TITLE
Unable to display puppet chart on custom HTML page

### ISSUE THREAD

**Issue by davebuchholz-bny** [netdata/netdata#8834]
##### Bug report summary
Unable to display puppet chart on custom HTML page
##### OS / Environment
```
Linux puppet-pgh01.eagleaccess.com 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.8 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.8"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
/etc/os-release:HOME_URL="https://www.redhat.com/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.8"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.8 (Maipo)
```

##### Netdata version
netdata v1.21.1 

##### Component Name
web 
##### Steps To Reproduce
1. Enable and setup puppetserver monitoring. 
2. Use the chart URL api/v1/charts to find the name of one of the puppet server charts. Eg: puppet_puppetserver.jvm_heap
3. Create a div for the chart using the dashboard sample: 
```
<div class="dash-graph"  data-netdata="puppet_puppetserver.jvm_heap">.
```
4. Load the page, see that the URL being requested is not correct, there is an extra "chart" in the generated URL. Error message on web page shows: puppet_puppetserver.jvm_heap: chart not found on url "/api/v1/chart?chart=puppet_puppetserver.jvm_heap". I also tried with a few other div names from the sample code. Same result.

##### Expected behavior
Should display the selected chart via "/api/v1/data?chart=puppet_puppetserver.jvm_heap"

**Comment by jacekkolasa** [comment]
closing, as there's not enough information to fix it. @davebuchholz-bny if there's still an issue, please reopen
