### ISSUE TITLE
Unable to add node via Magiclink

### ISSUE THREAD

**Issue by drupalbee** [netdata/netdata#8835]
When trying to add a new server to my netdata cloud account, when I click on the "magiclink" it fails to load and authenticate.  I have tested this on Mac OS, Safari, Chrome, Firefox and Windows using Chrome.   Each event fails to load:  https://unpkg.com/@snackbar/core@1.7.0/dist/snackbar.min.js.map

**Comment by cakrit** [comment]
Hi @drupalbee, we did get a fix in last week. Can you please provide your netdata version? Assigning to @jacekkolasa

**Comment by drupalbee** [comment]
I literally just installed it prior to creating this ticket.  so:  netdata
1.9.0

**Comment by drupalbee** [comment]
I had installed via the apt installer and now removed and installing via the git installer.

**Comment by cakrit** [comment]
The latest stable version is 1.21.1, but that has an issue with the magic link, that's fixed in the nightlies. 1.22 is coming out next week. Out of curiosity, which installation method gave you 1.9.0? We recommend using our own binary packages, or kickstart.sh.

**Comment by drupalbee** [comment]
@cakrit As I stated, it was installed via the apt installer.  "apt-get install netdata" that's where 1.9 came from.

**Comment by cakrit** [comment]
We don't maintain those packages ourselves. We can only help in this forum with installations of the latest stable or nightly. You could reach out to the package maintainers themselves.
