### ISSUE TITLE
Netdata does not write inside correct log after rotate

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#8839]
##### Bug report summary
After the log rotate to be executed, I observed that Netdata continued storing data in the old file:

```bash
$ ls -l /var/log/netdata/
-rw-r--r-- 1 netdata netdata    0 Apr 25 23:18 access.log
-rw-r--r-- 1 netdata netdata    0 Apr 25 23:18 debug.log
-rw-r--r-- 1 netdata netdata    0 Apr 26 03:20 error.log
-rw-r--r-- 1 netdata netdata 499K Apr 27 17:54 error.log-20200426
```

##### OS / Environment
```
Linux malta2183.startdedicated.com 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.7.1908 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.7.1908 (Core)
/etc/system-release:CentOS Linux release 7.7.1908 (Core)
```

##### Netdata version
netdata v1.21.1-110-g63315d1 

##### Component Name
Daemon

##### Steps To Reproduce

1. Start Netdata
2. Let the Operate System rotate the logs

##### Expected behavior
After the rotate, Netdata should store inside the new file.

**Comment by cakrit** [comment]
This should be very simple to fix, if it's still happening.

**Comment by underhood** [comment]
@Ferroin maybe related to following?
When I look at systemd service file `/usr/lib/systemd/system/netdata.service` inside the PIDfile is set to:
`PIDFile=/var/run/netdata/netdata.pid`

But when I look at `/etc/logrotate.d/netdata` I see it tries to use nonexistent `/opt/netdata/var/run/netdata/netdata.pid` to send signal to:
```
/opt/netdata/var/log/netdata/*.log {
	daily
	missingok
	rotate 14
	compress
	delaycompress
	notifempty
	sharedscripts
	postrotate
		/bin/kill -HUP `cat /opt/netdata/var/run/netdata/netdata.pid 2>/dev/null` 2>/dev/null || true
	endscript
}
```

**Comment by underhood** [comment]
@Ferroin  What I am not sure yet is how we end up in this state... maybe install method related? When I compile on my local system the `system\` folder contains the correct (same) path in both `netdata.service` and `netdata.logrotate`.

**Comment by Ferroin** [comment]
Yeah, I have no idea how that state could have happened either.

Either way this could theoretically be prevented by fixing #8244.

**Comment by stelfrag** [comment]
Closing in favor of https://github.com/netdata/netdata/issues/10539
