### ISSUE TITLE
configure script pulls in json-c unconditionally if detected

### ISSUE THREAD

**Issue by diizzyy** [netdata/netdata#8841]
If json-c gets detected it's included in the build even if ```--disable-jsonc``` is set.
Tested using netdata 1.21.1 on FreeBSD 12.1 and 13-CURRENT.

**Comment by amoss** [comment]
Hello, this does sound like a bug - thank you for reporting it. We currently have some problems with the mixture of json parsers that we have in different areas of the code. The fix that we have decided on is that we are going to make json-c a hard dependency of the agent and use it everywhere. This patch is currently under preparation and will be released in about a week. At which point this option will be deprecated and all builds of the agent will use json-c.

**Comment by diizzyy** [comment]
I see, thanks for the prompt reply!
