### ISSUE TITLE
Broken URLs in Documentation

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#8848]
##### Bug report summary

Discovered 2 broken/outdated documentation links as below on the same page:

FIRST URL
[https://github.com/netdata/netdata/blob/master/docs/tutorials/collect-apache-nginx-web-logs.md#custom-log-formats-and-fields](url)

Section:
> We do have **extensive documentation** on how to build custom parsing for Nginx and Apache logs.

Bad url is 
`https://github.com/netdata/netdata/blob/master/collectors/go.d.plugin/modules/weblog/README.md#custom-log-format `

SECOND URL

Here:
[https://github.com/netdata/netdata/blob/master/docs/tutorials/collect-apache-nginx-web-logs.md#monitor-nginx-or-apache-web-server-log-files-with-netdata](url)

Section:
> The **go.d plugin** is currently compatible with Nginx and Apache.

Bad URL is:
`https://github.com/netdata/netdata/blob/master/collectors/go.d.plugin/modules/weblog/README.md `

##### OS / Environment
```
N/A
```

**Comment by joelhans** [comment]
Thanks for catching this, @TheOldMan2000!

I fixed both of these links in this commit: https://github.com/joelhans/netdata/commit/b77afe173e802831703f0fdd5bc4999e75361cd5

I'll be creating a PR for this change (and others) shortly, and will aim to get them merged ASAP.

**Comment by TheOldMan2000** [comment]
Thanks Joel, much appreciated. 😀
