### ISSUE TITLE
macOS builds fails with --require-cloud and cannot find openssl libraries

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#8862]
While investigating #8854 I found that I could not build Netdata on my macOS (_which is my primary dev machine_):

It fails with:

```
checking if cloud functionality should be enabled... yes
configure: WARNING: OpenSSL required for agent-cloud-link but not found. Try installing 'libssl-dev' or 'openssl-devel'.
checking if libmosquitto static lib is present (and builds)... no
checking if libwebsockets static lib is present... yes
checking if netdata agent-cloud-link can be enabled... no
configure: error: User required agent-cloud-link but it can't be built!
 FAILED
```

I had to do this to get it to buidl:

```
  503  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
  504  ./netdata-installer.sh --dont-wait --dont-start-it --disable-go --require-cloud --install /tmp/netdata
  505  brew info openssl
  506  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  507  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
  508  set | grep PKG
  509  ./netdata-installer.sh --dont-wait --dont-start-it --disable-go --require-cloud --install /tmp/netdata
  510  history | tail
```

I could have sworn I fixed this by adding a commit to @Ferroin 's PR #8286 but I can no longer find the commits I added :/

**Comment by prologic** [comment]
Figured this out and will have a fix shortly...

Don't know why/how got changed to break this -- It _was_ working at one point when I fixed it and I found the commits I made to fix it, they are in `master`.

**Comment by prologic** [comment]
#8865 that fixed builds for macOS is __reverted__ due to #9135 (_but was found earlier then user reports_). Putting this back in my backlog after #9130 is cleaned up and merged.

**Comment by prologic** [comment]
Unfortunately, no. I haven't had an opportunity to get back to this at the moment. How many nodes do you have to manage? Would you be able to try running the Static Netdata agent on them via `kickstart-static64`?

**Comment by mrbrutti** [comment]
I tried, with `brew install netdata` with `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` and with clonning master and executing `sudo ./netdata-installer.sh --install /usr/local`

**Comment by mrbrutti** [comment]
I assume you meant this, I just tried it and it says it is linux only. 
```
~ matt$ bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)
 ABORTED  Static binary versions of netdata are available only for Linux, but this system is Darwin
```

**Comment by mrbrutti** [comment]
what i don't understand is why if this is just an issue of not picking up the OpenSSL libraries why the exports are failing to do a proper compile.

**Comment by prologic** [comment]
Hmm I'm so sorry I had a brain fart. Yes of course our static builds only build for Linux :/ But this is wrong and needs to be fixed.

**Comment by mrbrutti** [comment]
No need to apologize. Let me know if you do have a solution in mind and I will be happy to test it in some of my nodes.

**Comment by mrbrutti** [comment]
`sudo LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./netdata-installer.sh --install /usr/local --disable-telemetry --require-cloud` worked.

**Comment by prologic** [comment]
Are you able to claim it via Netdata Cloud and connect it?

**Comment by mrbrutti** [comment]
Yes. It looks like the only issue w/ the configuration was the lack of `LDFLAGS`.  I tested in two systems and it is working. One system had some issues w/ launchctl, after registering, but it is working now.

**Comment by prologic** [comment]
Would you be willing to put up a PR that fixes this for macOS users in our `netdata-installer.sh` script?

**Comment by mrbrutti** [comment]
https://github.com/netdata/netdata/pull/9360

**Comment by prologic** [comment]
> Let me know if this will work. I tested it on my boxes and it works. #9360

Thank you! I have tested your PR and it also works. Its approved. @Ferroin Please also test and review.

**Comment by Ferroin** [comment]
With the merge of #9360, this should be fixed now.
