### ISSUE TITLE
[QUESTION] What Technologies Does netdata Use? How Are They Integrated? What frameworks Are Involved? And How Is It All Built Together?

### ISSUE THREAD

**Issue by Rubix982** [netdata/netdata#8868]
##### Question summary

PLEASE READ THIS FIRST

Hello! 
First of all, this isn't an issue with anything I have faced in `netdata`, these are some questions that I had some `netdata` itself. It's not an issue. I decided to open an issue because the issue page at netdata/netdata said,

```
Question
You just want to ask a question? Go on.
```

Please remove this issue if you think this is irrelevant and guide me to somewhere else where I can ask my questions. I would highly appreciate it. 

> Actual Question,

I'm really, really, really impressed by `netdata`, it seems really UI friendly, interactive, wholesome, and everything seems right. It's something that I would recommend to everyone around me to use if they like having a deeper understanding of how much of their machine is utilizing some resource.  In fact, I'm a university student, currently a sophomore, trying to build a kind of UI which just shows you basic OS statistics, such as CPU / GPU usage, system info, and network related statistics, just like in `[stacer](https://github.com/oguzhaninan/Stacer)` if anyone has used that.

My current project is the first real big project of mine. Trying to integrate testing, CI/CD pipeline, some automation, automatic documentation, building, using CMake in something so big for the first time, really trying to explore proper software engineering, development, and just trying to research about interfaces and accesses to data provided by Operating Systems.

`netdata` seems like something inspirational in these circumstances, with a lot of work put into it. So I just had some questions that I wanted to ask,

1): I've seen that `netdata` primarily uses C, JS, Python, and Shell for the code. However, how are they all connected? Why did the design choice go for JS and Python? How are they built together? I, just a user, just ran the curl script locally and it just worked. How did you guys do that? 
2): Are you guys using some framework? For my Uni project, I just chose QT as the obvious choice to go along with C and some shell scripting to automate the process. If so, what frameworks allowed you to integrate all three languages together?
3): How did you integrate the software with kubernetes and docker? That seems pretty hard to me as a beginner.

I hope you can understand my confusion and intrigue at the same time. Basically, what I'm trying to ask is how was this project built from the bottom up? That would be really amazing to know.

##### OS / Environment

OS: `Arch Linux`

##### Component Name

Nothing to do with components.

##### Expected results

Just some answer. Everything else is fantastic.

**Comment by prologic** [comment]
Hi! Welcome to NetData! :)

Allow me to _try_ to answer some of your questions as best as I can but broadly speaking, it's a bit hard to go into specifics as a) I'm new to the company myself and b) its had a lot of engineering effort put into it by many very talented engineers!

----

> 1): I've seen that netdata primarily uses C, JS, Python, and Shell for the code. However, how are they all connected? Why did the design choice go for JS and Python? How are they built together? I, just a user, just ran the curl script locally and it just worked. How did you guys do that?

C is primary chosen as the most commonly available and portable language across a wide variety of systems. We can build the software on almost _anything_ that has a C compiler. This includes GCC and Clang and _might_ even compile with SCC or TinyCC (_untested_). C also gives us the best performance, footprint and development effort balance. Netdata therefore requires very little resources to run and even smaller amounts of memory. It also consumes very little CPU as its written with very highly optimized C.

JS and Python don't really come into play here with the "Core" Agent per se, JS, Python, Bash are all used as ways to write external collectors that "plug-in" to the Netdata agent to extend what the agent is cable to collect. There are also a whole swath of new collectors being written in Go -- But they all use the same API interface (_a stdin/stdout UNIX Pipe_).

> 2): Are you guys using some framework? For my Uni project, I just chose QT as the obvious choice to go along with C and some shell scripting to automate the process. If so, what frameworks allowed you to integrate all three languages together?

The Web Frontend is largely written in HTML/Javascript as it typical of most web frontends. Lately the Web UI is being rewritten to use the React JS framework.

QT is a Native Desktop GUI library/framework and doesn't fit here with Netdata (_or really any distributed monitoring agent/solution for that matter_).

> 3): How did you integrate the software with kubernetes and docker? That seems pretty hard to me as a beginner.

Both Docker and Kubernetes (_which uses the Docker Engine as its primary container engine__) expose HTTP API(s) that you can talk to to do sll kinds of things like querying statistics about containers, images, volumes as well as control the state of containers and cluster resources. Its not too magical just have to read through the rather large API docs of both of these techs.

I hope this helps a bit! Keep up the studies!

**Comment by Rubix982** [comment]
Hello!

> Allow me to try to answer some of your questions as best as I can but broadly speaking, it's a bit
> hard to go into specifics as a) I'm new to the company myself and b) its had a lot of engineering
> effort put into it by many very talented engineers!

Thank you! It obviously is a great deal of work by mean talented engineers. It's a lot of work and time spent into this project. 

Just a few cross questions I want to ask from your comment,

1): 
> There are also a whole swath of new collectors being written in Go -- But they all use the same
> API interface (a stdin/stdout UNIX Pipe).

Why decide with `Go`, won't that make the development a bit harder? The tech stack already has C/C++, Python, Javascript, and Shell. The inclusion of a completely different language might add more to difficulties than in maintainability - no? I have largely read the most developers tend to keep their tech stack smaller as it can help out hugely in the long run for maintainability purposes, or when some components need to be upgraded or updated.

2):
> QT is a Native Desktop GUI library/framework and doesn't fit here with Netdata (or really any
> distributed monitoring agent/solution for that matter).

The fact that it won't fit with `netdata` makes sense, but why would you say that it doesn't also fit with any distributed monitoring agents as well?

3):
> Its not too magical just have to read through the rather large API docs of both of these techs.

Oh God the docs. :D

Anyways, thank you for your time! Your reply added to my experience and current knowledge. It was helpful.

**Comment by prologic** [comment]
> Why decide with `Go`, won't that make the development a bit harder? The tech stack already has C/C++, Python, Javascript, and Shell. The inclusion of a completely different language might add more to difficulties than in maintainability - no? I have largely read the most developers tend to keep their tech stack smaller as it can help out hugely in the long run for maintainability purposes, or when some components need to be upgraded or updated.

The short answer is writing external collectors in Go is more portable. Having to distribute software in interpreted languages (_bytecode or not_) is difficult to say the least.

> The fact that it won't fit with `netdata` makes sense, but why would you say that it doesn't also fit with any distributed monitoring agents as well?

Short answer is that QT/GTK/wWidgets/etc is just not a portable platform to write user interfaces in. The industry at large as moved to the Web and Web technologies for good reason. Try to imagine how you'd get your QT application runing on system X wher eyou've built and tested it on system Y.

> Anyways, thank you for your time! Your reply added to my experience and current knowledge. It was helpful.

You're welcome!

**Comment by Rubix982** [comment]
> Having to distribute software in interpreted languages (bytecode or not) is difficult to say the least.
I have never thought about this before. Something I should probably research on more.

> Try to imagine how you'd get your QT application runing on system X where you've built 
> and tested it on system Y.
I would have to write some checks if all the packages are available at compile as well as run time. If not, I would have to ask for a lot of permissions from the user to setup packages on their machine - and it may not be guaranteed that the same setup works across all platforms... got it.

I think I have my questions answered now. Thank you for your time, again. :P
