### ISSUE TITLE
autogen is not available on Ubuntu 18.04, but it is

### ISSUE THREAD

**Issue by g0rbe** [netdata/netdata#8869]
##### Bug report summary
`kickstart.sh` states that `autogen` is not available on Ubuntu 18.04:

```
Searching for autogen ...
WARNING
package autogen is not available in this system.
You may try to install without it.
```

But it is available:

```
autogen/bionic 1:5.18.12-4 amd64
  automated text file generator
```

Nothing serious, installed manual and `kickstart.sh` found it:

```
apt install autogen
```

##### OS / Environment
```
Linux XXX 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

##### Netdata version

 
```
netdata v1.21.1-109-nightly
```

##### Steps To Reproduce

`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

**Comment by prologic** [comment]
This comes from here:

https://github.com/netdata/netdata/blob/166958349599708ae34397a8407aa35982f8c81c/packaging/installer/install-required-packages.sh#L576-L586

A PR to fix this is welcome! I will happily review it. Be sure you re-test on several Ubuntu 18.xx versions which you can easily do with Docker.
