### ISSUE TITLE
Configuration to ignore disk congestion on mdadm check

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#8873]
##### Question summary
I'm trying to deal with two alarms that happen every time cron attempts to check the mdadm arrays with `echo check > /sys/block/md0/md/sync_action`
On Ubuntu this is managed by a cron job in `/etc/cron.d/mdadm` that runs a script `/usr/share/mdadm/checkarray`

I've come up with a solution by appending `AND $mdstat.md0_operation.check == 0` to the end of the warn and crit sections for the alarms in disks.conf

```
# -----------------------------------------------------------------------------
# disk congestion

# raise an alarm if the disk is congested
# by calculating the average disk utilization
# for the last 10 minutes

template: 10min_disk_utilization
      on: disk.util
      os: linux freebsd
   hosts: *
families: *
  lookup: average -10m unaligned
   units: %
   every: 1m
   green: 90
     red: 98
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1)) AND $mdstat.md0_operation.check == 0
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1)) AND $mdstat.md0_operation.check == 0
   delay: down 15m multiplier 1.2 max 1h
    info: the percentage of time the disk was busy, during the last 10 minutes
      to: sysadmin


# raise an alarm if the disk backlog
# is above 1000ms (1s) per second
# for 10 minutes
# (i.e. the disk cannot catch up)

template: 10min_disk_backlog
      on: disk.backlog
      os: linux
   hosts: *
families: *
  lookup: average -10m unaligned
   units: ms
   every: 1m
   green: 2000
     red: 5000
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1)) AND $mdstat.md0_operation.check == 0
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1)) AND $mdstat.md0_operation.check == 0
   delay: down 15m multiplier 1.2 max 1h
    info: average of the kernel estimated disk backlog, for the last 10 minutes
      to: sysadmin
```
My question: Is this a good way to deal with these alarms or is there a better way to catch arrays that might not be named `md0`? I wasn't sure if a wildcard could be used like: `$mdstat.*_operation.check`

Also do you think this would be useful to add to the default `disks.conf` file for other users?

Edit: This solution doesn't really work because at the end of an mdadm check `$mdstat.md0_operation.check == 0` before disk usage has returned to normal as per the lookup value in the alarms. So an alarm is triggered at the conclusion of every mdadm check.

##### OS / Environment
Ubuntu 18.04

##### Component Name
health.d/disks.conf
proc.plugin/mdstat

##### Expected results
Silence expected disk congestion alarms whenever mdadm checks arrays.

**Comment by thiagoftsm** [comment]
Hi @Steve8291 ,

> My question: Is this a good way to deal with these alarms or is there a better way to catch arrays that might not be named md0?  I wasn't sure if a wildcard could be used like: $mdstat.*_operation.check

Right now the alarms does not accept `simple patterns` for `crit` or warn`, so it is necessary to specify the whole value without wildcard.

The strings written for `crit` and `warn` are evaluated element by element, case you use an `OR` it could raise an alarm depending of the results of the whole vector.

Unfortunately I am without any RAID hardware to test this alarm. @ilyam8 do you have conditions to test a possible solution?

**Comment by Steve8291** [comment]
I think I've got it:
`$mdstat.md0_operation.check == 0` evaluates as false and keeps alarm from triggering if mdadm check has started.
However, when mdadm check completes, the above will evaluate as true and the 10min average of disk.util will still be high enough to trigger an alarm. This was a problem so I'm using the `$utilization` and `$backlog` variables to check the current values to be sure they are greater than `$green` or `$red` thresholds. This way  the alarm can't trigger until current values also hit the required thresholds. I also added a hysteresis around the critical or warning thresholds for the `$utilization` and `$backlog` variables.

I've tested this and no more alarms are triggered when mdadm checks arrays.
I'd love to hear if anyone has thoughts on how I did that or can see any flaws in it?
Thanks.

```
# -----------------------------------------------------------------------------
# disk congestion

# raise an alarm if the disk is congested
# by calculating the average disk utilization
# for the last 10 minutes

template: 10min_disk_utilization
      on: disk.util
      os: linux freebsd
   hosts: *
families: *
  lookup: average -10m unaligned
   units: %
   every: 1m
   green: 90
     red: 98
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1)) AND $mdstat.md0_operation.check == 0 AND $utilization > $green * (($status >= $WARNING) ? (0.7) : (1))
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1)) AND $mdstat.md0_operation.check == 0 AND $utilization > $red * (($status == $CRITICAL) ? (0.7) : (1))
   delay: down 15m multiplier 1.2 max 1h
    info: the percentage of time the disk was busy, during the last 10 minutes
      to: sysadmin


# raise an alarm if the disk backlog
# is above 1000ms (1s) per second
# for 10 minutes
# (i.e. the disk cannot catch up)

template: 10min_disk_backlog
      on: disk.backlog
      os: linux
   hosts: *
families: *
  lookup: average -10m unaligned
   units: ms
   every: 1m
   green: 2000
     red: 5000
    warn: $this > $green * (($status >= $WARNING)  ? (0.7) : (1)) AND $mdstat.md0_operation.check == 0 AND $backlog > $green * (($status >= $WARNING) ? (0.7) : (1))
    crit: $this > $red   * (($status == $CRITICAL) ? (0.7) : (1)) AND $mdstat.md0_operation.check == 0 AND $backlog > $red * (($status == $CRITICAL) ? (0.7) : (1))
   delay: down 15m multiplier 1.2 max 1h
    info: average of the kernel estimated disk backlog, for the last 10 minutes
      to: sysadmin
```

**Comment by thiagoftsm** [comment]
Hi @Steve8291 ,

I was studying now the [variables](https://learn.netdata.cloud/docs/agent/collectors/proc.plugin/) that you selected and the [proc file](https://raid.wiki.kernel.org/index.php/Mdstat) that is monitored and I do cannot find nothing wrong with your solution, but as I already said, I am without any RAID to test and I am also a long time without to work with a RAID. For sure, your logic looks good to me.

Best regards!

**Comment by Steve8291** [comment]
Thanks @thiagoftsm
