### ISSUE TITLE
DO_NOT_TRACK=0 creates .opt-out-from-anonymous-statistics

### ISSUE THREAD

**Issue by D34DC3N73R** [netdata/netdata#8875]
When using docker, setting the environment variable DO_NOT_TRACK=0 results in .opt-out-from-anonymous-statistics still being created. I'd like to have the option available in my unraid template but not disable anonymous statistics by default.

**Comment by Pingger** [comment]
So are aksing to revert #7404? ...

**Comment by D34DC3N73R** [comment]
I'm asking for a way to include the environment variable, but not opt out. As it is now, including the DO_NOT_TRACK environment variable creates the .opt-out-from-anonymous-statistics file regardless of what it's set to. DO_NOT_TRACK=0, DO_NOT_TRACK=-0, DO_NOT_TRACK=1 all result in the creation of the .opt-out-from-anonymous-statistics file.

**Comment by prologic** [comment]
Just set it to a. null value.

This was the intention behind the PRs which were taken from some recommendations. The expressions look for a non-null `DO_NOT_TRACK` environment value. Setitng it to `0` or `1` is kind of meaningless and just conventaionl. YOu can set it to `yes` `foo` and its still considered a non-null string.

**Comment by D34DC3N73R** [comment]
That seems to work, thanks for the tip
