### ISSUE TITLE
Sync data between ephemeral(slave) nodes and master. Or master<->master

### ISSUE THREAD

**Issue by splastunov** [netdata/netdata#8876]
Hello!

We decide to try to collect stats from clients VDS with netdata.
For first look it is very nice and fast, but we have an issue.

For security reason we decided to use unique API-KEY for each VDS + use param ```allow from = VDS_IP```. So we protected netdata from "hackers" that decided to corrupt data of other VDS.
In this case we have to regenerate stream.conf by cron and we have to restart netdata to reread stream.conf. I found another issue [#6432](https://github.com/netdata/netdata/issues/6432) that describe plans to refactor configuration method, but I think there is no changes done yet.
Netdata restart process takes about 30-40 seconds, so we have "holes" in charts of ephemeral(slave) nodes. Is there any workaround for it?
We are useing  ```memory mode memory mode = dbengine```

I have few ideas and questions:
1) Idea: Use multiple masters. Question:  If we will restart them in different time will they sync missed data?
2) Idea: Use netdata proxy with stream config that allow any API-KEYs. So it will cache data and then sync with master after it restart. 
Question:  I did not find how to accept any API-KEY. I tried to put [*] but it does not work. If there any way to make it works.
3) Use some dynamic configuration, but did not find any information about when it will be implemented.

Main reason of this request is to protect data corruption from rogue clients that decided that they are cool hackers.

Thank you.

**Comment by mfundul** [comment]
@thiagoftsm correct me if I'm wrong.

1. There is no syncing in netdata streaming currently so this will not work.
2. Again, I don't believe any syncing will take place here.

It is in our plans to improve streaming though, so as to more closely resemble some form of consistent replication.

**Comment by splastunov** [comment]
Thank you for fast response.

Is there any suggestion to master config to speed up restart process?
I found information at issues from 2017 that ```memory mode = map``` will work faster than ```dbengine```. Is it true for our days or not?

**Comment by mfundul** [comment]
> 
> 
> Thank you for fast response.
> 
> Is there any suggestion to master config to speed up restart process?
> I found information at issues from 2017 that `memory mode = map` will work faster than `dbengine`. Is it true for our days or not?

It's not really black and white. `map` will trigger page faults which can be very inefficient, so it will depend on the size of your DB and the size of the available system RAM. Moreover, there is no compression in `map`. You have to experiment with it.

**Comment by splastunov** [comment]
Thank you.

Just tested.
There is no difference in restart time between ```map``` and ```dbengine```.

I have checked restart process again and realized that master restart fast enough(about 5-7 seconds), but it takes about 30-40 seconds at slaves to reconnect to stream. I think that it is because of I set param ```update every = 10```.
I tried to change this param on slave to ```update every = 1``` and now it reconnect much faster and gap becam very small(5-7 seconds). It is ok, but I would not like to have such a lot off data on master. Is there any way to send data from slave every 1 second, but show average of 10 seconds on master without backendDB? Or maybe there is an option to force slave reconnect faster?

**Comment by splastunov** [comment]
At stream.conf we have param ```timeout seconds```. If I set at stream.conf ```timeout seconds = 1``` and at netdata.conf ```update every = 10```, I've got a lot off errors at logs ```could not send metrics for 1 seconds - closing connection.....```
Netdata does not have any data to send every 1 sec and trying to reconnect, but it should not because connection to master is OK.
Is it a bug if feature?

**Comment by thiagoftsm** [comment]
> @thiagoftsm correct me if I'm wrong.
> 
>     1. There is no syncing in netdata streaming currently so this will not work.
> 
>     2. Again, I don't believe any syncing will take place here.
> 
> 
> It is in our plans to improve streaming though, so as to more closely resemble some form of consistent replication.

@mfundul you are right, we are not doing synchronization, but @cakrit enforced the necessity to bring this on other communication channel that we have.
We need to change our handshake in the stream protocol to start bring this for the master.

**Comment by thiagoftsm** [comment]
> Is it a bug if feature?

Hi @splastunov,

Thank you for the tests you have done, Considering your description and the error you copied, I would classify this as a bug. I set the label `needs triage` for your question, because I will investigate it more next week.

Best regards!

**Comment by splastunov** [comment]
@thiagoftsm thank you for your attention!

I found a way to dynamically reload configuration without restart netdata.
I'm greatnoob in C, but this way works.

I found method [load_stream_conf](https://github.com/netdata/netdata/blob/master/streaming/rrdpush.c#L69) that is loading ```stream.conf```. It calls another method [appconfig_load](https://github.com/netdata/netdata/blob/983a26d1a2c110b35db252b4b79c3f03eb4eeb4b/libnetdata/config/appconfig.c#L504) that have 4 keys.
`int appconfig_load(struct config *root, char *filename, int overwrite_used, const char *section_name)
{...}`
I was really interested in third key ```int overwrite_used```.

I tried to copy load_stream_conf at rrdpush.c and changed this way
`static void load_stream_conf_update() {
    errno = 0;
    char *filename = strdupz_path_subpath(netdata_configured_user_config_dir, "stream.conf");
        info("Reloading stream config");
        appconfig_unlock(&stream_config);
    if(!appconfig_load(&stream_config, filename, 1, NULL)) {
        info("ReloadingCONFIG: cannot load user config '%s'. Will try stock config.", filename);
    }
    freez(filename);
}`
So I just set third key at ```appconfig_load``` to 1.

After that I found place where error occur when [master can not find API-KEY](https://github.com/netdata/netdata/blob/master/streaming/rrdpush.c#L1533) and called after it new method.
And that's it!
Config reloading on the go when some new slave trying to stream data to master.

I understand that it is ugly and could brake something, but it is really what I would like to achieve.

**Comment by splastunov** [comment]
@thiagoftsm any updates about bug with timeouts?

**Comment by thiagoftsm** [comment]
@amoss are the fixes that you are working right now also solving this problem?

**Comment by thiagoftsm** [comment]
Hi @splastunov ,

> @thiagoftsm any updates about bug with timeouts?

We are working with stream these days and we are fixing some bugs and bringing improvements. I will let the @amoss to answer you, because he is the person working with stream these days.

best regards!

**Comment by amoss** [comment]
Hi @splastunov, the patch that I am working on now will fix your problem. When the receiving netdata restarts it will replicate the missing data from the sender to fill the gap in the chart. It's under development now, it should be in the nightly build next week.

**Comment by splastunov** [comment]
@amos thank you for great news!

During investigation of sync problem I found another bug that is described [here](https://github.com/netdata/netdata/issues/8876#issuecomment-622951786)
I thought that you are working on it now : )

**Comment by ilyam8** [comment]
@splastunov if there is another bug it makes sense to open a new issue (if @amoss fix doesnt fix it)

**Comment by amoss** [comment]
@splastunov I would treat that as more of a feature than a bug :) Have you tried increasing the timeout so that it is longer than the `update_every` interval?

**Comment by splastunov** [comment]
@amoss if timeout is longer than ```update_every``` all is fine. 
It seems that it is really some kind of feature.

If you will fix data synchronization, there will be no need to set timeout shorter then ```update_every```.

**Comment by splastunov** [comment]
Hello!

Is there any update on syncing data between ephemeral(slave) nodes and master?
I have updated to latest version, but still have gaps when netdata restarts on master node.

My work around with dynamic reloading stream.conf does not work correctly.
After reloading stream.conf without netdata restart, netdata begin mixing data from different ephemeral(slave) nodes...
So I have to restart netdata when new nodes added to stream.conf
