### ISSUE TITLE
Netdata service is stopped after an upgrade with apt

### ISSUE THREAD

**Issue by MrFreezeex** [netdata/netdata#8878]
##### Bug report summary
After doing an `apt upgrade netdata` the netdata service is no longer running.
We want to use unattended-upgrades to automatically update netdata on all of our servers, but at each update all of our netdata instances are stopped.

##### OS / Environment

Debian 10/Ubuntu 18.04

##### Netdata version
v1.21.1
 

##### Component Name
N/A

##### Steps To Reproduce

1. Install netdata using packagecloud repository https://packagecloud.io/netdata/netdata/install
2. Start netdata
2. Upgrade netdata using apt
3. Netdata is stopped using SIGTERM (just before the upgrade AFAIK)

##### Expected behavior
Netdata should be started after an upgrade (at least if the service was running before attempting the upgrade).
I don't have much experience with debian packaging so I don't really know what is the best option, but I saw that for instance nginx/apache are automatically started after an install/upgrade, perhaps a solution like that would be sufficient ?

If it's not suitable maybe netdata could restart itself (if the service is started) after the completion of the upgrade ?

**Comment by thiagoftsm** [comment]
Hi @MrFreezeex ,

Could you give us additional information from your  `error.log`?

Best regards!

**Comment by MrFreezeex** [comment]
Yes sure !

I see this in the error.log file during an upgrade :
```
2020-05-03 00:55:30: netdata INFO  : MAIN : SIGNAL: Received SIGTERM. Cleaning up to exit...
2020-05-03 00:55:30: netdata INFO  : MAIN : Shutting down command server.
2020-05-03 00:55:30: netdata INFO  : MAIN : Shutting down command event loop.
2020-05-03 00:55:30: netdata INFO  : MAIN : Shutting down command loop complete.
```
The rest of the logs are related to the shutting down of netdata and its plugins.

I also see similar logs in journalctl :
```
May 03 00:55:30 bookstack-1 systemd[1]: Stopping Real time performance monitoring...
-- Subject: Unit netdata.service has begun shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit netdata.service has begun shutting down.
May 03 00:56:30 bookstack-1 systemd[1]: netdata.service: State 'stop-sigterm' timed out. Killing.
May 03 00:56:30 bookstack-1 systemd[1]: netdata.service: Killing process 30396 (netdata) with signal SIGKILL.
May 03 00:56:30 bookstack-1 systemd[1]: netdata.service: Main process exited, code=killed, status=9/KILL
May 03 00:56:30 bookstack-1 systemd[1]: netdata.service: Failed with result 'timeout'.
May 03 00:56:30 bookstack-1 systemd[1]: Stopped Real time performance monitoring.
-- Subject: Unit netdata.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit netdata.service has finished shutting down.
```

**Comment by yasharne** [comment]
Hi @MrFreezeex,
Can you do the following steps and send the results?
- `sudo su -s /bin/bash netdata`
- `systemctl cat netdata | grep ExecStart=`, this gives you the `ExecStart` command. For example mine is `/opt/netdata/usr/sbin/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D`
- Copy the command and run it as the netdata user and send the output.

**Comment by MrFreezeex** [comment]
The full command to start netdata appears to be `/usr/sbin/netdata -D -P /var/run/netdata.pid` for me.

The netdata doens't stop when launching directly netdata without systemd (while upgrading it with apt). It simply output a single line (`2020-05-04 10:39:05: netdata INFO  : MAIN : SIGNAL: Not enabling reaper`).

It seems that the upgrade use systemd to stop netdata service
