### ISSUE TITLE
Netdata registry cannot find itself: failed

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8881]
##### Bug report summary

We have a few master nodes each storing metrics from different slaves. In order to find all slaves in a single address, we have created a registry server.
The registry is behind the load balancer and can be accessed via an address (e.g. netdata.x.y.z).
The problem is When I click on the registry server in the `my nodes` section:
![image](https://user-images.githubusercontent.com/7656049/80899140-a92da700-8d21-11ea-98e6-edd2a2448e5a.png)
I get this error:
![registry](https://user-images.githubusercontent.com/7656049/80899162-278a4900-8d22-11ea-8f49-2a70ce93ad48.png)

Here is the `netdata.conf` file in the registry server:
```
#
# Ansible managed
#
[global]
	memory mode = dbengine
	update every = 1
	debug log = /opt/netdata/var/log/netdata/debug.log
	error log = /opt/netdata/var/log/netdata/error.log
	access log = /opt/netdata/var/log/netdata/access.log

[web]
	default port = 19999

[registry]
    enabled = yes
    allow from = *
    registry to announce = https://netdata.x.y.z
```

##### Netdata version

netdata v1.21.1

##### Component Name

Registry

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

When you access the URL `https://MASTER_IP:19999/api/v1/info`, can you see all slaves in the `mirrored_hosts` list?

Best regards!

**Comment by yasharne** [comment]
@thiagoftsm I'm not sure if I have understand the registry usage right, So here is my shorten scenario:
- We made a master netdata server (netdata-master-01) to collect metrics from all the slaves.
- on the master node, we defined itself as a registry and on the slaves we defined its master node as the registry server
- After a while we realized me made SPOF by a single netdata master, so we decided to have multiple master nodes (netdata-master-02 and netdata-master-03) 
- Now that we have multiple masters, we cannot see all the slaves in one netdata dashboard and we need to check each master to find the relevant slave
- We came with the idea of using a registry server (netdata-registry-01 which is not the slave of any host) so we don't have difficulty finding a slave.
- We installed netdata on a server and made it a registry server by this configuration:
```
#
# Ansible managed
#
[global]
	memory mode = dbengine
	update every = 1
	debug log = /opt/netdata/var/log/netdata/debug.log
	error log = /opt/netdata/var/log/netdata/error.log
	access log = /opt/netdata/var/log/netdata/access.log

[web]
	default port = 19999

[registry]
        enabled = yes
        allow from = *
        registry to announce = https://netdata-central.x.y.z
```
and put the netdata registry with the IP of 172.16.76.5 behind the load balancer with the address of https://netdata-central.x.y.z
- Now when I open this address, I see our registry server inside `my nodes` section:
![image](https://user-images.githubusercontent.com/7656049/80938811-b87b2600-8def-11ea-8541-2c451d9bfb1d.png)
And when I click on it:
![aaaaaaaaaa](https://user-images.githubusercontent.com/7656049/80938959-3dfed600-8df0-11ea-8d73-16de55f8abf7.png)
- So I changed the `netdata.conf` of one of our slaves (which I can see it on `netdata-master-01` and had its master as its registry) to this:
```
[registry]
	enabled = no
	registry to announce = https://netdata-central.x.y.z
```
- But now when I open the slave dashboard via the master node, I still cannot see the node added to the registry:
![image](https://user-images.githubusercontent.com/7656049/80939318-89fe4a80-8df1-11ea-959e-d247e393720b.png)

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

I cannot see any error in the steps you did. I also followed all the same steps you described here changing for my local network address and everything worked as expected. Let me do some questions for you to help you more:

1 - I saw that you used:

```
registry to announce = https://netdata-central.x.y.z
```

Are you using `TLS` certificate on master?

2 - The version 1.21 has  a new dashboard based on `react`. Did you have the same problem with old Netdata version?

Best regards!

**Comment by yasharne** [comment]
Hi @thiagoftsm , 
1 - The master nodes are not behind the load balancer, so we access them via their IP address and there are no certificates on them.
2 - The registry server was installed with the netdata version 1.21.1 so I don't know if it was related to the version, but I had a problem when we used to define each slave's master node as the registry and I updated the slaves and the masters to version 1.21.1 and renamed the hostnames of two of our slaves, then I couldn't access them via the registry anymore because the registry (netdata master) was trying tho open them via their old name

**Comment by thiagoftsm** [comment]
> Hi @thiagoftsm ,
> 1 - The master nodes are not behind the load balancer, so we access them via their IP address and there are no certificates on them.

Considering it does not have certificate, please, change your `registry to announce =` to  `http://netdata-central.x.y.z`

> 2 - The registry server was installed with the netdata version 1.21.1 so I don't know if it was related to the version, but I had a problem when we used to define each slave's master node as the registry and I updated the slaves and the masters to version 1.21.1 and renamed the hostnames of two of our slaves, then I couldn't access them via the registry anymore because the registry (netdata master) was trying tho open them via their old name

This is another issue that we will need to change, the name must be updated after each connection. ( @amoss this is something that we can fix with the next upgrades we will bring to fix the gaps, it is 2 lines code maximum ).

**Comment by yasharne** [comment]
@thiagoftsm Seting `registry to announce` to `http://netdata-central.x.y.z` didn't solve the problem and now I cannot even see the registry server inside the registry dashboard:
![image](https://user-images.githubusercontent.com/7656049/81156885-a6d68180-8f9b-11ea-92f0-7c956c07c320.png)
P.S: `http://netdata-central.x.y.z` is only accessible via `https` and `http` requests redirects to `https`

**Comment by thiagoftsm** [comment]
@yasharne can you give the name of the tool that you are using as load balancer ? When I set everything with direct access, I could not recreate the problem.

**Comment by yasharne** [comment]
@thiagoftsm we use `HA proxy`

**Comment by yasharne** [comment]
@thiagoftsm I also have tried another scenario, here is the registry configuration on the registry server:
```
[registry]
	enabled = yes
	allow from = *
	registry to announce = http://172.16.76.5:19999
```
and use this as the registry configuration on the slaves:
```
[registry]
	enabled = none
	registry to announce = http://172.16.76.5:19999
```
but I still have the same problem which is the slave is not added to the registry when I open it on the slave's master node. 
Should I do a specific configuration on the master nodes?

**Comment by yasharne** [comment]
@thiagoftsm Some nodes are added to the registry server but I cannot open them on the registry server :
![image](https://user-images.githubusercontent.com/7656049/81588922-434eb880-93ce-11ea-83f7-e49d349694a8.png)
![image](https://user-images.githubusercontent.com/7656049/81589235-81e47300-93ce-11ea-85cd-91f76c9f8f0d.png)
I don't get it, the address is correct but why netdata cannot open it?

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

Firstly I apologize the delay, please, can you open the browser developer tools and send us the network information?
Days ago I helped another user to configure a network that is more or less like yours and we opened another port to take care of registry, you can see more details [here](https://github.com/netdata/netdata/issues/8947), but I am not sure if the solution we found for him can also help you.

Best regards!

**Comment by yasharne** [comment]
Thanks @thiagoftsm ,
I'm not sure if this is what you've asked, but here is the output:

![image](https://user-images.githubusercontent.com/7656049/82119514-7dd0a080-9794-11ea-8ab0-f4d98f0008de.png)

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

This was exactly what I wanted, now I think I have enough information to talk with our frontend guys, thank you!
@jacekkolasa There is a problem with our dashboard that is not allowing @yasharne to open his hosts, please, take a look on the image and please, identify the error that is happening in our js files.

**Comment by jacekkolasa** [comment]
@yasharne i'm closing this issue since it was related to old dashboard version, but if you'll have more problems, please feel free to reopen or create new ticket. Thanks!
