### ISSUE TITLE
Netdata across lots of low-RAM servers

### ISSUE THREAD

**Issue by Daniel15** [netdata/netdata#8885]
##### Question summary
I have around 20 servers that have around 3 GB free disk space and 100 MB free RAM each (256 MB VPSes with around 150 MB RAM in use). I'd like to monitor at least basic metrics - things like CPU and RAM usage, etc. I have another server with a lot of RAM that runs Prometheus for long-term monitoring and for feeding into Grafana dashboards, which already scrapes data from Netdata instances on other servers.

I'm wondering what the best setup is for these low-RAM servers.

1. Have a 'central' Netdata server and use streaming. I'm wondering how much bandwidth this would use though, as this would all be going over the internet. Are there estimates on bandwidth usage for streaming?
2. Use standard `dbengine` with low `history`, scrape the metrics into Prometheus, and just use Prometheus UI 
3. Use Prometheus "node exporter" instead

Any recommendations?

**Comment by bjoe2k4** [comment]
I am using the streaming option and 1500 metrics at an interval of 10s almost saturates a dialup connection (56-64 kbit/s or 7-8 kb/s), taken from the network interfaces metric while nothing else is running.
