### ISSUE TITLE
netdata won't install on Proxmox/Debian 10

### ISSUE THREAD

**Issue by ipkpjersi** [netdata/netdata#8886]
##### Bug report summary
I am unable to install netdata on Proxmox/Debian 10, the installer fails with this:
```
[/tmp/netdata-kickstart-h2JrEY]# curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/sha256sums.txt  OK  

[/tmp/netdata-kickstart-h2JrEY]# curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz  OK  

 ABORTED  Tarball checksum validation failed. Stopping netdata installation and leaving tarball in /tmp/netdata-kickstart-h2JrEY 
```
I tried updating netdata from `v1.21.1-124-nightly` to `v1.21.1-128-nightly` but it wasn't working, so I uninstalled it with the provided uninstall script, and then tried clean installing it but now it throws a checksum validation error. I can access the checksum just fine via curl manually, so I am not quite sure what the issue is.

##### OS / Environment

```
Linux myserver 5.3.18-3-pve #1 SMP PVE 5.3.18-3 (Tue, 17 Mar 2020 16:33:19 +0100) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"

```
##### Component Name
The installer is broken for me, I'm not sure what component that is.

##### Steps To Reproduce

1. Try to run `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

##### Expected behavior
I expect the application to install, however, it does not install.

**Comment by prologic** [comment]
I cannot reproduce this in a fresh container. I would guess this is intermittent networking/infra issues. Could you try again? Thanks!

**Comment by ipkpjersi** [comment]
I tried manually grabbing the checksums with curl, and that was working fine, but you are right it does seem to be an intermittent issue as it seems to be fine for me now. I can no longer reproduce this issue.

**Comment by prologic** [comment]
Glad it worked for you, there _might_ be some area for improvement re reliability in the `kickstart.sh` code, I'll have a look. We should probably fail early though rather than claiming we can't checksum what we downloaded against something we didn't expect.

**Comment by 0xpr03** [comment]
On debian 10 you can install netdata via apt from the default repos, the .dpkg builds aren't working
