### ISSUE TITLE
Netdata debian install (with apt) doesn't set suid on plugins

### ISSUE THREAD

**Issue by MrFreezeex** [netdata/netdata#8888]
##### Bug report summary
The setuid bit on netdata plugins is not set on needed plugins (cgroup-network, perf ...).
It also seems that netdata apply a chmod on the whole `/usr/libexec/netdata/plugins.d` directory during package installation as even the ebpf plugin installed manually loose his setuid bit when upgrading the netdata package using apt.

##### OS / Environment
Ubuntu 18.04

##### Netdata version
v1.21.1
 

##### Component Name
N/A

##### Steps To Reproduce

1. Install netdata using packagecloud repository https://packagecloud.io/netdata/netdata/install
2. `ls -l /usr/libexec/netdata/plugins.d` and no binaries have the setuid bit set.

I attached outputs of the ls command with:
1. Before upgrading the package with manually installed ebpf and setuid bits all set correctly (also manually with `chmod u+s $file`)
2. With a netdata package upgrade (`apt upgrade netdata`) => suid bits set previously disappeared
3. With the kickstart script script => all the suid bits are set correctly

[nd_ls_suid.txt](https://github.com/netdata/netdata/files/4573785/nd_ls_suid.txt)

##### Expected behavior
Set the setuid bit on needed plugins and do not change setuid on the ebpf plugin (as it not installed with the package).

**Comment by prologic** [comment]
You are right. I can confirm this on a Debian install.

Compared with a static64 install:

```#!sh
# find /opt/netdata -perm /4000
/opt/netdata/bin/fping
/opt/netdata/usr/libexec/netdata/plugins.d/ioping
/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin
/opt/netdata/usr/libexec/netdata/plugins.d/cgroup-network
#
```

And Debian Buster:

```#!sh
root@4d494142b408:/# find /usr/libexec/netdata/plugins.d/ -perm /4000
root@4d494142b408:/#
```

@Ferroin If I recall you had done some work towards permissions/ownerships IIRC. Can you help me understand why we do a bunch of `chown/chmod` in the packaging and what the best fix here would be?
