### ISSUE TITLE
cache settings for Agent

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata#8889]
### Feature idea summary
Currently we set `Cache-Control: public` setting in response headers. That can can cause old dashboard files being requested, even if they don't exist anymore (hashed files from previous build). We should change our cache strategy:

on every path that returns `index.html`, set:
```
Cache-Control: no-cache
Cache-Control: no-store
Expires: 0
```
All other assets can have current cache setting, and updates will be controlled by hashed filenames.

In the future we should extend that behaviour to all `html` files, and use [ETags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag)

##### Expected behavior
After installation, on `localhost:19999`, `localhost:19999/`, and `http://localhost:19999/host/{SLAVE_NODE_NAME}` calls we should see new `Cache-Control` response headers

We should fix that as soon as possible.

**Comment by amoss** [comment]
Switching off the cache seems like an over-reaction, should we not put
```
Cache-Control: must-revalidate
```
into the standard headers instead? (@cosmix)

**Comment by cosmix** [comment]
I'm good with that, as long as the `Expires` header is valid for the cases that @jacekkolasa has in mind, e.g. `index.html` etc.

**Comment by jacekkolasa** [comment]
We agreed with @amoss that ETags is a way to go here

**Comment by cosmix** [comment]
Etags are indeed the best way forward. Thanks

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
