### ISSUE TITLE
freebsd_ipfw plugin separation?

### ISSUE THREAD

**Issue by samm-git** [netdata/netdata#8890]
##### Question summary

Hi, i am netdata user/contributor. I am using it on the FreeBSD and found that ipfw graphs are not enabled. After all i found that to collect ipfw data i have to run netdata from root, what looks like a dangerous option and seems to be overkill for such a small task.

My proposal is to either create linkable freebsd plugin or even separate one (freebsd_ipfw) to be able to use suid flag on this specific binary. Let me know if you think it is a good idea, i cam try to make such PR.

##### OS / Environment

FreeBSD 12.1/amd64

##### Component Name

freebsd.plugin, see https://github.com/netdata/netdata/blob/master/collectors/freebsd.plugin/freebsd_ipfw.c#L87

**Comment by vlvkobal** [comment]
We have to make the plugin external the same way as we did with other plugins that need root permissions.

**Comment by samm-git** [comment]
@vlvkobal thank you. Do you think ipfw part of the plugin needs to be externalized? As FreeBSD plugin itself seems to not require root, only its ipfw part...

**Comment by vlvkobal** [comment]
Yes, only the ipfw part.

**Comment by Duffyx** [comment]
I like this idea. Given the fact that the plugin is implemented in C, I reckon casting commands using sudo privileges will not be possible? (similarly how samba python plugin works, using "sudo smbstatus" commands)

**Comment by ilyam8** [comment]
we dont need sudo for external plugins, we can `setcap`
> https://learn.netdata.cloud/docs/agent/collectors/apps.plugin#permissions

**Comment by samm-git** [comment]
@ilyam8 please read topic you replying to. We are now talking about FreeBSD, so setcap is not an option in this case.

**Comment by samm-git** [comment]
If we talking about FreeBSD - nearest alternative is  Mandatory Access Control (see mac(4)). However, i am not aware of mac for the raw sockets (and we need them) plus it will still require separation of the ipfw plugin. Anyway - it is 100% offtopic here @ilyam8, so as i mentioned  - 100% non-relevant comment.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
