### ISSUE TITLE
De/Incremental storage

### ISSUE THREAD

**Issue by Pingger** [netdata/netdata#8896]
##### Feature idea summary
Incremental/Decremental storage. By that I mean:
- Last (config) days full granularity
- up to (config) month: (configurable, 1/2, 1/3, 1/4, ...) granularity
- after that: third group of even less granularity

##### Expected behavior
Save storage space at the cost of data-granularity. But retain a much longer timeframe of information. 
So as soon as a cache file drops out of a granularity group, reprocess it in the background to reduce the granularity and storage cost.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
