### ISSUE TITLE
Building packages for Ubuntu 20.04 (Focal)

### ISSUE THREAD

**Issue by berendt** [netdata/netdata#8906]
Currently only packages up to Ubuntu 19.10 (Eoan) are available on Packagecloud. Please add the build for Ubuntu 20.04 (Focal).

**Comment by berendt** [comment]
@prologic Can you take a look at this, please?

**Comment by sirikon** [comment]
For anyone looking for Ubuntu 20.04 apt packages: There's a Netdata package available in Ubuntu universe: https://packages.ubuntu.com/focal/netdata

As of today it's a bit outdated (1.19.0), but good enough until this gets done :)

**Comment by pgassmann** [comment]
@Ferroin @prologic Is there something holding this back? focal is the current LTS release of Ubuntu, released 3 months ago, and now the default on many cloud providers.
Currently I just use the `eoan` repository as a workaround. It is working great, so I assume building it for focal directly should not be a big issue.

**Comment by Ferroin** [comment]
It's largely a combination of us having expected to have reworked our binary packaging by now (which would have updated our list of platofrms we provide packages for as part of the process) and other things coming up that were higher priority.

I'll be looking into this some time today or tomorrow, I _think_ you're right that there shouldn't be any changes needed beyond just adding it to the package build process, in which case you should hopefully see packages through our official channels either Friday or some time early next week.

**Comment by prologic** [comment]
@Ferroin As this was still in `Backlog` and assigned to us both, I assume you haven't started yet. So I'll get this done today.
