### ISSUE TITLE
Service fails to start: `Cannot cd to directory '/usr/lib64/netdata/conf.d'`

### ISSUE THREAD

**Issue by esamson** [netdata/netdata#8917]
##### Bug report summary

I have netdata installed from RPMs from Package Cloud repo. All is working well when using **1.20.0**. This error happens on a new machine I set up with **1.21.1** installed.

The service fails to start. `journalctl -u netdata.service` says:

```
May 06 06:01:15 ip-10-0-1-88.ec2.internal netdata[9188]: Cannot cd to directory '/usr/lib64/netdata/conf.d'
May 06 06:01:15 ip-10-0-1-88.ec2.internal systemd[1]: netdata.service: main process exited, code=exited, status=1/FAILURE
May 06 06:01:15 ip-10-0-1-88.ec2.internal systemd[1]: Unit netdata.service entered failed state.
May 06 06:01:15 ip-10-0-1-88.ec2.internal systemd[1]: netdata.service failed.
```

Comparing file listings of the installed packages do show that `/usr/lib64/netdata/conf.d` is indeed missing in the more recent version.

* [netdata-1.20.0.txt](https://github.com/netdata/netdata/files/4585030/netdata-1.20.0.txt)
* [netdata-1.21.1.txt](https://github.com/netdata/netdata/files/4585031/netdata-1.21.1.txt)

##### OS / Environment

```
Linux ip-10-0-1-88.ec2.internal 4.14.173-137.229.amzn2.x86_64 #1 SMP Wed Apr 1 18:06:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Amazon Linux"
/etc/os-release:VERSION="2"
/etc/os-release:ID="amzn"
/etc/os-release:ID_LIKE="centos rhel fedora"
/etc/os-release:VERSION_ID="2"
/etc/os-release:PRETTY_NAME="Amazon Linux 2"
/etc/os-release:ANSI_COLOR="0;33"
/etc/os-release:CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
/etc/os-release:HOME_URL="https://amazonlinux.com/"
/etc/system-release:Amazon Linux release 2 (Karoo)
```

##### Netdata version

 netdata v1.21.1

##### Component Name

Packaging?

##### Steps To Reproduce

1. sudo yum install netdata 
2. sudo systemctl start netdata.service
3. journalctl -u netdata.service

##### Expected behavior

Netdata starts.

**Comment by esamson** [comment]
I no longer see this issue in the latest release, **1.22.1-1.el7**.

**Comment by iigorkarpov** [comment]
This issue is back again. Version 1.30.1-2.el7

**Comment by isaacloven** [comment]
I have the same issue with  1.31.0-1.el7

**Comment by jrwren** [comment]
I had a very similar issue with v1.29.3 as packaged in Ubuntu 21.10 universe but `Cannot cd to directory '/home/netdata'` I worked around it by `cd /home; sudo ln -s /var/log/netdata/`

**Comment by dogsbody-josh** [comment]
Seeing this issue again on CentOS 7 and Netdata version 1.44.3. 

After some similar problems during running the installation script to those in [issue 9863](https://github.com/netdata/netdata/issues/9863) (solved by moving the installer script to /root/tmp and making executable), Netdata refused to start with this error:
```
Mar 19 11:36:26 host.fqdn netdata[14615]: time=2024-03-19T11:36:26.732+00:00 comm=netdata source=daemon level=alert errno="2, No such file or directory" tid=14615 thread=netdata msg="Cannot change directory to '/usr/lib64/netdata/conf.d'"
```

I can see that there were files in `/usr/lib/netdata/conf.d/` instead so I just soft linked them to the missing location with:
```
mkdir -p /usr/lib64/netdata/conf.d
ln -s /usr/lib/netdata/conf.d/ /usr/lib64/netdata/conf.d
```
Restarting Netdata then got things working. 

Unfortunately there is still no streaming of metrics to the parent server but that will probably be a separate issue.

**Comment by ilyam8** [comment]
@dogsbody-josh I think you are not using Netdata's official packages. Which repository did you install Netdata from?

**Comment by dogsbody-josh** [comment]
@ilyam8 you are correct. I actually managed to realise that myself and just wrote up my findings on [issue 13840](https://github.com/netdata/netdata/issues/13840#issuecomment-2007151126) as I believe that is the true source of the problems I ran into.
