### ISSUE TITLE
Add db support to store a batch of data

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8920]
* Parse the `RBEGIN`, `RSET`, `REND`  responses
* Store into the data using the `store_metric_next` callback.
* If the final gap drops below a threshold (1 second? 2 seconds?) then the gap-filling ends and we drop into the normal sender/receiver thread loops.
* Test
* Evaluate and tune
    - If the memory pressure caused by the extra filling / flushing is too high then we will need to throttle the replication speed.
    - May need limits on the size of gap to fill
    - Either this converges to a small gap (if the link latency is low) and we switch to normal streaming, or if the link latency is too high then we stay in gap-filling replication mode indefinitely. Check this does not impact latency

Note: this implementation will skip `rrdset_done` (and the interpolation) and write directly to the dbengine (using `store_metric_next`). This ensures that we do not interpolate the values twice. We can then update the `latest_stored` / `collected` times at the end of the batch. This means that the dbegine can handle filling / flushing the pages without writing new code to do this.

**Comment by MrZammler** [comment]
Closing because of https://github.com/netdata/netdata/pull/12556
