### ISSUE TITLE
Sender should push gap data on reconnect

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8922]
* New message in the backward direction REPLICATE chart start end now
* Sender will respond with `RBEGIN dim1 dim2 dim3...`
* Followed by `RSET val1 val2 val3...` for each sample in the range
* Ends with `REND now`
* Sender side will pull data from the db to fill the responses.
* On incoming streams use the last slew estimate and the new timestamp to estimate the gap

**Comment by stelfrag** [comment]
> This issue has been inactive for 30 days. It will be closed in one week, unless it is updated.

keep it
