### ISSUE TITLE
Log lines sent to stdout/stderr instead of log files at startup.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#8926]
##### Bug report summary

On startup, Netdata prints a log message about the reaper code to stdout/stderr instead f logging it in the configured log files.

##### OS / Environment

All systems, though it's not overtly visible unless you manually restart the agent through the service manager (or by just manually starting it), and it may be masked in some cases if the method of starting the agent redirects stdout/stderr.

##### Netdata version

All versions since the merge of #7059

##### Component Name

area/daemon

##### Steps To Reproduce

1. Restart Netdata
2. Observe log line in terminal output.

##### Expected behavior

All log entries should go to the configured logging destination.

---

I suspect this is just a case of us logging something before we actually set up the configured log files.

**Comment by mfundul** [comment]
This happens because the print is executed before log file configuration has taken place.

**Comment by Saruspete** [comment]
Hello,

for what is worth, the logs are still sent to stdout if the log folder (/var/log/netdata) does not exists.
Maybe a configuration to create automatically the configured folders (if permissions allows it) would be a nice addition ?

**Comment by Ferroin** [comment]
@Saruspete Agreed, though I'd say it shouldn't even be a config option, on startup we should try to create any missing directories that we're configured to use. The fact that we choke if our cache directory is missing is even more ridiculous than handling of logging TBH...
