### ISSUE TITLE
Why can't i delete this server it isn't even mine?

### ISSUE THREAD

**Issue by BR0KK** [netdata/netdata#8928]
I Just added a few ubuntu installs to my netdata. 

In my overview i now see every PC but there is one i didn't add and its not even mine. 

london3.my-netdata.io 

Why is this server even inside my nodes page?
![netdata](https://user-images.githubusercontent.com/2887095/81209942-701b5e00-8fd1-11ea-9145-b758dda768b2.JPG)

?

**Comment by jacekkolasa** [comment]
@BR0KK That node exists here only because you accessed it, and you were automatically logged in to the cloud. It is kind of a "visible nodes" list. You can remove it by scrolling down and clicking trash icon on the right of url in "Node URLs" - and then clicking "Forget"

**Comment by jacekkolasa** [comment]
I'll close this now but please ask here if you have other questions
