### ISSUE TITLE
Add UUID to the slave URL

### ISSUE THREAD

**Issue by heya0** [netdata/netdata#8932]
##### Feature idea summary
In the replication mode, when two slaves have the same host name, their URLs are the same(http://xx.xx.xx.xx:19999/host/hostname/). After testing, both URLs point to the slave that added later, so that we cannot access another slave. If the UUID or IP of each slave is added to the URL, they can be perfectly distinguished.
##### Expected behavior
When slave nodes have the same host name, they can still be accessed separately.

**Comment by thiagoftsm** [comment]
Hi @heya0 ,

I agree with your suggestion, this would solve this problem.
@jacekkolasa and @amoss we need to change the server response, but probably it is necessary to change something on front end.

Thank you for your suggestion!

Best regards!

**Comment by jacekkolasa** [comment]
To do this, we would also need to add that UUID information into the /charts endpoint (which is an unfortunate source of stream-nodes information).

Url (IP) won't work here, Netdata Agent doesn't know the address.

@dim08 FYI

**Comment by amoss** [comment]
We already support accessing replicated agents by their GUID, you can just replace the hostname with the GUID in the URL, e.g.:
```
http://xx.xx.xx.xx:19999/host/22222222-2222-2222-2222-222222222222/
```
This handles part of what you need. Is there a specific place that the urls with the hostnames are shown that is causing a problem?

**Comment by heya0** [comment]
YES，in node menu, the URL of the node is through the host name.

![netdata-node-menu](https://i.loli.net/2020/05/18/Fk2E89OSaZxA1o5.png)

**Comment by jacekkolasa** [comment]
@amoss that's good news, however Dashboard has no access to that GUID yet. Dashboard renders slave nodes from information in `/api/v1/charts`, there is only `hostname` there

**Comment by ilyam8** [comment]
Fixed in https://github.com/netdata/netdata/pull/10771
