### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by Cat7373** [netdata/netdata#8933]
##### Feature idea summary
Provide a multi-language support framework to allow contributors familiar with other languages to submit translations in other languages to make it more friendly to non-native English speakers.

##### Expected behavior
\-

**Comment by ilyam8** [comment]
Imo this is nice to have but doesnt worth - it is hard to maintain, if we had it it would be outdated/partially translated all the time. Keep in mind that our documentation is constantly changing. And we cant guarantee quality of the translation. 

@joelhans

**Comment by ilyam8** [comment]
btw https://github.com/netdata/localization

**Comment by ilyam8** [comment]
> more friendly to non-native English speakers

As a non-native English i prefer docs in E (original!) over broken Ru (there are always bugs in translation) any day.

**Comment by joelhans** [comment]
@Cat7373, are you referring to the product itself, as in the content in the dashboard, or the documentation? Or both?

Regarding the documentation, we've moved away from that localization project @ilyam8 linked above for the exact reason he mentioned—it's very difficult to move quickly on translations and ensure docs fixes are distributed quickly across translations. I do want to support translations in our docs, but we need to build a more formal (and probably automated) solution. For now we recommend users rely on in-browser translations, as while not perfect, will at least always be up-to-date.

**Comment by ilyam8** [comment]
i think it is wontfix atm, no need to keep it open
