### ISSUE TITLE
send notify over Matrix protocol

### ISSUE THREAD

**Issue by okias** [netdata/netdata#8934]
##### Feature idea summary
Matrix is an open protocol for real-time communication. It is designed to allow users with accounts at one communications service provider to communicate with users of a different service provider via online chat, Voice over IP, and Videotelephony.

##### Expected behavior
Would be nice to be able receive alerts on Matrix channels.

**Comment by ilyam8** [comment]
@okias 👋 

take a look

https://github.com/netdata/netdata/pull/5741

Probably you can take over it and finish the PR

**Comment by ilyam8** [comment]
Fixed in #9196
