### ISSUE TITLE
How to see openvpn server status  inside docker container with netdata

### ISSUE THREAD

**Issue by farzinnasiri** [netdata/netdata#8935]
I have the following container running on my ubuntu server:
https://github.com/kylemanna/docker-openvpn

I use this for my open vpn connections.
I installed netdata on my server and everything works but I want to monitor my openvpn connections. How can achieve this>
##### OS / Environment
Ubuntu server 16.04

##### Expected results
openvpn monitoring

**Comment by ilyam8** [comment]
There is openvpn collector which uses management interface to get clients number/traffic stats

> https://github.com/netdata/go.d.plugin/tree/master/modules/openvpn#openvpn-monitoring-with-netdata


It is disable by default because of mi limitations

> Currently, the OpenVPN daemon can at most support a single management client any one time.
