### ISSUE TITLE
Enable CPU frequency chart

### ISSUE THREAD

**Issue by Compizfox** [netdata/netdata#8938]
I want to have the CPU clock frequency chart enabled in Netdata. If I'm not mistaken, this is handled by `proc.plugin`, which is enabled by default. However, my Netdata instance does not have the CPU frequency chart.

In [the docs](https://learn.netdata.cloud/docs/agent/collectors/proc.plugin/#monitoring-cpus) I found this statement:

> If more than 50 cores are present in a system then CPU thermal throttling, frequency, and idle state charts are disabled.

The machine in question has a Threadripper 3970X (32 cores, 64 threads). Is it possible that the threads are counted as 'cores', and that is why the charts are disabled?

Is it possible to turn the charts back on using a config option?

**Comment by ilyam8** [comment]
i see that 50 limitation it is hardcoded

https://github.com/netdata/netdata/blob/77749bb923dc2ff33f39f8e5f40f98f427435ef0/collectors/proc.plugin/proc_stat.c#L488-L504

**Comment by mfundul** [comment]
That's not a problem @ilyam8 .

The "cores" word is wrong in this document. In reality it's what linux calls "processors" or "CPUs". The computer architecture term would be "hardware threads".

If you want to enable all of the options that are automatically disabled due to high processor count in `proc_stat` module you need to enable in `netdata.conf` section `[plugin:proc:/proc/stat]` the following boolean configuration options:
```
    keep per core files open = yes
    keep cpuidle files open = yes
    core_throttle_count = yes
    package_throttle_count = yes
    cpu frequency = yes
    cpu idle states = yes
```

As a result, you will have more charts, more CPU overhead and more open file descriptors from netdata.

**Comment by Compizfox** [comment]
Thanks for the quick response!

> The "cores" word is wrong in this document. In reality it's what linux calls "processors" or "CPUs". The computer architecture term would be "hardware threads".

Ah, right, like I suspected ;)

> If you want to enable all of the options that are automatically disabled due to high processor count in proc_stat module you need to enable in netdata.conf section [plugin:proc:/proc/stat] the following boolean configuration options:

So it is possible to override this behaviour in the config. Thanks!

**Comment by Compizfox** [comment]
Okay, quick second question: the clock frequency figures I see in the Netdata chart differ from those I obtain from /proc/cpuinfo under load.

In Netdata, the frequency doesn't exceed 3.7 Ghz (the CPU's base clock), but using /proc/cpuinfo I see it boosting to about 4.1 GHz.

**Comment by mfundul** [comment]
It's taken from `/sys/devices/system/cpu/cpuX/cpufreq/scaling_cur_freq`.
