### ISSUE TITLE
Is this value the number of characters, size in bits/bytes?

### ISSUE THREAD

**Issue by mbarper** [netdata/netdata#8942]
https://github.com/netdata/netdata/blob/fece01fc269ebe0b6cea58aad3677b6788b0f441/collectors/apps.plugin/apps_plugin.c#L98

**Comment by vlvkobal** [comment]
`static char cmdline[MAX_CMDLINE + 1];`

**Comment by thiagoftsm** [comment]
Hi @mbarper ,

This is calculated in bytes, as you can see here:

https://github.com/netdata/netdata/blob/fece01fc269ebe0b6cea58aad3677b6788b0f441/collectors/apps.plugin/apps_plugin.c#L1124

Best regards!

**Comment by mbarper** [comment]
I have processes with much more size than that and the string defined to detect the process as a service is beyond that size. I had to change the string to something before that size and it is not as accurate as the first one. Any chance to modify it? or any other advise?

**Comment by thiagoftsm** [comment]
> I have processes with much more size than that and the string defined to detect the process as a service is beyond that size. I had to change the string to something before that size and it is not as accurate as the first one. Any chance to modify it? or any other advise?

Hello @mbarper ,

This strings supports 16kb, how many bytes would be necessary to support your process? You can change this defintion for the size that you want you also can  create a PR suggesting the change in the variable size.

Best regards!
