### ISSUE TITLE
go.d.plugin: log timestamp is always in UTC

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8949]
##### Bug report summary

Netdata is not following the server's timezone, as you see, there are 4:30 hours delay between the servers current time and the times appeared in the log file:
![image](https://user-images.githubusercontent.com/7656049/81473091-9596aa80-9211-11ea-8922-4d07322eb198.png)
 

##### OS / Environment

```
Linux netdata-plugins-01.tool.x.y.z 4.4.0-176-generic #206-Ubuntu SMP Fri Feb 28 05:02:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 netdata v1.21.1

**Comment by ilyam8** [comment]
@yasharne thx for reporting!

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

Netdata gets the time to write the log from the function

https://github.com/netdata/netdata/blob/ca3019e403df01cdc23d55b5534c11c0b85f8823/libnetdata/clocks/clocks.c#L67

But, according the documentation ( `man 3 clock_gettime`) :

```
CLOCK_REALTIME
               A  settable  system-wide  clock that measures real (i.e., wall-clock) time.  Setting this clock requires appropriate privileges.  This clock is affected by discontinuous jumps in the system time (e.g., if the system administrator manually changes the clock), and by the incremental adjustments performed by adjtime(3) and NTP.
```

Considering the manual information, let me ask something to you, does your server update their time using NTP? It looks like that Netdata using UTC to store the logs.

**Comment by yasharne** [comment]
Hi @thiagoftsm, 
yes use NTP

**Comment by ilyam8** [comment]
@thiagoftsm there is no connection with libnetdata

**Comment by thiagoftsm** [comment]
> @thiagoftsm there is no connection with libnetdata

The logs written inside `error.log` use the function I reported to get the date @ilyam8, this was the motive I asked the information. The difference between times that we see can have relationship with some changes made by NTP according official documentation of the function called from libnetdata. It is possible we need to change the function that we use to get the time before to write the log.

**Comment by ilyam8** [comment]
I think the problem is using UTC time in go.d logger

**Comment by thiagoftsm** [comment]
> I think the problem is using UTC time in go.d logger (ill fix it)

Thank you @ilyam8 !

**Comment by thiagoftsm** [comment]
@yasharne are you have problems with other logs?
Or do you have this time difference only with go.d?
I assumed that you had problems with all.

**Comment by ilyam8** [comment]
it is only with go.d according his screenshot and i confirm it, there is a bug

**Comment by thiagoftsm** [comment]
I agree that the screenshot is only showing go.d, this is the motive I asked about the rest.

**Comment by ilyam8** [comment]
ok, i've found the problem

There is hack in netdata daemon

https://github.com/netdata/netdata/blob/ae0d6007f1b2caf32202c95bd47a3e5ccfe80fa0/daemon/main.c#L585-L588

It breaks golang std lib local time identification, it fallbacks to UTC

https://github.com/golang/go/blob/5aaeda19c1876ecec85406726b544ac49c8f799b/src/time/zoneinfo.go#L74-L80

https://github.com/golang/go/blob/5aaeda19c1876ecec85406726b544ac49c8f799b/src/time/zoneinfo_unix.go#L28-L52

@mfundul

**Comment by ilyam8** [comment]
@amoss please take a look too, @mfundul said you are the right person to fix!

**Comment by amoss** [comment]
It doesn't look like it requires any specialist knowledge - we should read the timezone properly on startup and cache the result. @dim08 can add it to the current list of bugs and whoever has capacity next week when the current dev-cycle finishes can fix it.

**Comment by ilyam8** [comment]
if [i understand the problem](https://stackoverflow.com/questions/4554271/how-to-avoid-excessive-stat-etc-localtime-calls-in-strftime-on-linux) it is not about us caching/not caching

> If the TZ variable is set, glibc will use the TZ variable and it will read the timezone from a file matching what's set in the TZ variable once(or until tzset() is called) - on the first call in a program that needs that information .

> If the TZ env variable is not set, glibc will go look at the /etc/localtime file every time (or rather it will check if /etc/localtime has changed since the last time it was read - which is what the stat() calls does)
