### ISSUE TITLE
Netdata SNMP stopped creating charts when failed to connect to a server.

### ISSUE THREAD

**Issue by kevinp1005** [netdata/netdata#8950]
I have a config file of thousands of SNMP Devices that we are trying to get the traffic data. When I run netdata, some of the charts are created and it is working properly, but not all of them are created, when I test the config file, it stopped creating charts after some errors (RequestTimedOutError).
![Screen Shot 2020-05-10 at 13 00 39](https://user-images.githubusercontent.com/25806608/81491218-57a39000-92be-11ea-956b-76df7afaf15b.png)

...

![Screen Shot 2020-05-10 at 13 01 39](https://user-images.githubusercontent.com/25806608/81491223-71dd6e00-92be-11ea-912f-390ae3119d86.png)

Is this the expected result ?

Here's my config file.
![Screen Shot 2020-05-10 at 13 02 34](https://user-images.githubusercontent.com/25806608/81491232-96d1e100-92be-11ea-8260-e2ee9a8beb98.png)

##### OS / Environment
Centos 7
##### Component Name
SNMP

##### Expected Results
It should continue to create charts for the next one when fail to connect.

**Comment by ilyam8** [comment]
> I have a config file of thousands of SNMP Devices
> thousands of SNMP Devices

wow! 😲 

___

>  it stopped creating charts after some errors

Do you mean there is no updates after RequestTimedOutError? I am not clear what is _stopped creating charts_

**Comment by kevinp1005** [comment]
@ilyam8 Yes, this is just an assumption, I can't be sure of the problem because the error log is not telling me much. Let's say i have 3000 devices configured in the config file, total charts that are created is only 1000 devices. If I changed it to only 100 devices, total charts created is only 60 devices. I'm not sure what stopped it. Here's another error that I get other than the RequestTimeOut.



![Screen Shot 2020-05-10 at 19 07 52](https://user-images.githubusercontent.com/25806608/81521727-a151b080-937a-11ea-80b4-f4d8e3c06ca6.png)

**Comment by kevinp1005** [comment]
@ilyam8 The error only occurred if I configure it with more than hundreds of devices, if i just put this device in its own in the config file, it works.

**Comment by kevinp1005** [comment]
[UPDATE] : I run the debugging script for node.d.plugin. Here's what I got before the error occurred

![Screen Shot 2020-05-11 at 12 18 40](https://user-images.githubusercontent.com/25806608/81523964-27bdc080-9382-11ea-83c5-3e1c42494d37.png)
.

![Screen Shot 2020-05-11 at 12 19 21](https://user-images.githubusercontent.com/25806608/81523957-1f658580-9382-11ea-921c-7c3bfb416868.png)

Does this have anything to do with it?

**Comment by nikobearrr** [comment]
I am also using netdata SNMP and I have gotten to the following observation: if you write a wrong oid (typo or it generally doesn't exist on the device) netdata snmp throws an error "it doesn't exist". Everything which is configured afterwards in the json will not be drawn as it seems the SNMP stops processing on the first error.

**Comment by kevinp1005** [comment]
@nikobearrr 
>Everything which is configured afterwards in the json will not be drawn as it seems the SNMP stops processing on the first error.

do you have the solution for this?

**Comment by nikobearrr** [comment]
Hi @kevinp1005, the only solution I have is to remove the "unknown" oid from the json and restart netdata

**Comment by ilyam8** [comment]
> Everything which is configured afterwards in the json will not be drawn as it seems the SNMP stops processing on the first error.

doesnt sound good, we need to check it

**Comment by kevinp1005** [comment]
@ilyam8 this happen to me as well, but i am sure that my configuration file is correct, for me the problem only occurred if i put more than 100 devices. I tried to update net-snmp to the latest version, but the problem still occurred. Is this net-snmp problem?

**Comment by ilyam8** [comment]
> but i am sure that my configuration file is correct,

i think it is any error, not invalid oid only (request timeout)

> problem only occurred if i put more than 100 device

probably some limitations of the current implementation, not sure, we need to check

**Comment by kevinp1005** [comment]
@ilyam8 do you have any suggestion in which file we have to check ? is [here](https://github.com/netdata/netdata/blob/master/collectors/node.d.plugin/snmp/snmp.node.js) a good start assuming this is a collector problem?

**Comment by ilyam8** [comment]
> I tried to update net-snmp to the latest version, but the problem still occurred. Is this net-snmp problem?

btw we use net-snmp that is shipped with netdata

https://github.com/netdata/netdata/blob/master/collectors/node.d.plugin/node_modules/net-snmp.js
