### ISSUE TITLE
Instrumenting my own app with open telemetry

### ISSUE THREAD

**Issue by 3tilley** [netdata/netdata#8953]
Hello,

This is more of a theoretical question, but am I right to think that if I want to instrument my own app or proprietary db, I need to write netdata-specific collectors? Is there a vision to be able to use hook into apps that have opentelemetry instrumentation?

**Comment by amoss** [comment]
@dim08 / @ilyam8 - Interesting question, what do you think?

**Comment by dim08** [comment]
Hi there, thank you for sharing your feedback. It is an interesting idea that we need to assess further. So I will add it on our funnel for future review. Since, we currently have limited capacity we cannot guarantee that this feature will be prioritised anytime soon.

**Comment by andrewm4894** [comment]
@dim08 not sure i'm the right person to assign this one too.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
