### ISSUE TITLE
How to send alarm notice through Python?

### ISSUE THREAD

**Issue by heya0** [netdata/netdata#8958]
##### Question summary
My SMS service provider, their API only supports Python / Java / go for sending SMS, I only see that curl is used to send notifications in `plugins.d/alarm-notify.sh`, how to use Python? 

Should I put the python script for sending SMS in the `custom_sender()` function in `plugins.d/alarm-notify.sh`, and then let this function call the python script?
##### OS / Environment
RHEL7.6 NETDATA 1.21
##### Component Name
alarm notification
##### Expected results
could easily call the python API provided by SMS service provider.

**Comment by cakrit** [comment]
> Should I put the python script for sending SMS in the `custom_sender()` function in `plugins.d/alarm-notify.sh`, and then let this function call the python script?

1. Create your python script and test it outside of netdata
2. Follow the instructions [here](https://learn.netdata.cloud/docs/agent/health/notifications/custom)
