### ISSUE TITLE
Cleaning the cache directory

### ISSUE THREAD

**Issue by lukasmalkmus** [netdata/netdata#896]
Is the cache directory ever cleaned up? I couldn't find a hint in the wiki or the config file. I think this is important to know because I don't want old data to fill my disk.

**Comment by ktsaou** [comment]
You are right, they are not cleaned. The only safe way to clean them though is to stop netdata and then delete all files that are too old. netdata maps these files to memory and does not write until it is closed.

**Comment by LukasMa** [comment]
Okay, so I think I'm going for a custom bash script. Could be a feature for future releases.

**Comment by ktsaou** [comment]
This will be fixed with the new database format we are designing.
So, I am closing it.
