### ISSUE TITLE
JSON-C isn't fetched from Sources

### ISSUE THREAD

**Issue by FrankFromHR** [netdata/netdata#8970]
##### Bug report summary

Updated two machines to try and test out the new version of Netdata Cloud, however I'm not able to connect them as the JSON-C doesn't seem to be fetched from sources. 

 --- Prepare JSON-C ---
cat: packaging/jsonc.version: No such file or directory
sha256sum: sha256sums.txt: no properly formatted SHA256 checksum lines found
 FAILED  jsonc files checksum validation failed.

 FAILED  Unable to fetch sources for JSON-C.

Same error in the updates on both machines. 

##### OS / Environment
```
Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic

Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.3.1611 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.3.1611 (Core)
/etc/system-release:CentOS Linux release 7.3.1611 (Core)

```

##### Netdata version
netdata v1.22.0-8-nightly

 

##### Component Name
Netdata Cloud

##### Steps To Reproduce
Upgrade using /etc/cron.daily/netdata-updater

##### Expected behavior
JSON-C would be fetched from sources.

**Comment by Ferroin** [comment]
Fix merged. We're on schedule to release version 1.22.1 within the next 48 hours with this and an assortment of other fixes.

**Comment by doodie** [comment]
tried 1.221 and same issue

`-- Configuring incomplete, errors occurred!
See also "/tmp/netdata-jsonc-Huhddu/json-c-json-c-0.14-20200419/CMakeFiles/CMakeOutput.log".
See also "/tmp/netdata-jsonc-Huhddu/json-c-json-c-0.14-20200419/CMakeFiles/CMakeError.log".
 FAILED

[/tmp/netdata-jsonc-Huhddu/json-c-json-c-0.14-20200419]# env CFLAGS= CXXFLAGS= LDFLAGS= make
make: *** No targets specified and no makefile found.  Stop.
 FAILED

[/root/netdata-v1.22.1]# mkdir -p /root/netdata-v1.22.1/externaldeps/jsonc /root/netdata-v1.22.1/externaldeps/jsonc/json-c
 OK

[/root/netdata-v1.22.1]# cp /tmp/netdata-jsonc-Huhddu/json-c-json-c-0.14-20200419/libjson-c.a /root/netdata-v1.22.1/externaldeps/jsonc/libjson-c.a
cp: cannot stat '/tmp/netdata-jsonc-Huhddu/json-c-json-c-0.14-20200419/libjson-c.a': No such file or directory
 FAILED

 FAILED  Failed to build JSON-C.`

**Comment by Ferroin** [comment]
@doodie I'm fairly certain that that's a different issue, JSON-C had to have been fetched and unpacked correctly, otherwise it wouldn't have gotten to trying to configure and build it. Can you open a new issue and include all of the output from the installer.
