### ISSUE TITLE
Unable to locate default installation directories

### ISSUE THREAD

**Issue by NCook15** [netdata/netdata#8971]
I'm trying to make some adjustments to the netdata.conf file, but none of the default Netdata installation directories seem to exist where they should be. I made a new installation of Netdata today, and ran into the problem described in [#3764](https://github.com/netdata/netdata/issues/3764).

While searching for the config file, I found that none of the expected directories were created in their expected locations during installation, listed out here: https://learn.netdata.cloud/docs/agent/configuration-guide/. Nor was I able to find where the config file was actually put.

However, I am able to see the config file when opening http://my.hostname:19999/netdata.conf. When I try to download it, I get the "no such file or directory" error. Any thoughts on this? 

Installation Details:

I installed Netdata in Docker, which is running on my Synology 216+II NAS, running DSM 6.2.2-24922 Update 4. The CPU is a INTEL Celeron N3060. I followed these instructions: https://learn.netdata.cloud/docs/agent/packaging/docker.

**Comment by ilyam8** [comment]
> However, I am able to see the config file when opening

there is a bug, see #8969

**Comment by ilyam8** [comment]
Configuration files are in `/etc/netdata` btw

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ docker exec -it netdata ls -l /etc/netdata
total 40
drwxr-xr-x    1 root     root          4096 May 12 00:25 charts.d
drwxr-xr-x    1 root     root          4096 May 12 00:25 custom-plugins.d
-rwxr-xr-x    1 root     root          2045 May 12 00:25 edit-config
drwxr-xr-x    1 root     root          4096 May 12 00:25 go.d
drwxr-xr-x    1 root     root          4096 May 12 00:25 health.d
-rw-r--r--    1 root     root           208 May 12 00:25 netdata.conf
drwxr-xr-x    1 root     root          4096 May 12 00:25 node.d
lrwxrwxrwx    1 root     root            23 May 12 00:25 orig -> /usr/lib/netdata/conf.d
drwxr-xr-x    1 root     root          4096 May 12 00:25 python.d
drwxr-xr-x    1 root     root          4096 May 12 00:25 ssl
drwxr-xr-x    1 root     root          4096 May 12 00:25 statsd.d
```

**Comment by NCook15** [comment]
That's odd... I do see the files when I run the command you listed, but there is no netdata directory when I look in `/etc/`. I also looked for it, and tried to edit the netdata.conf file as both user and root, and always ended up with a "no such file or directory" error. Could this be a permissions problem? Apologies, I'm pretty new to this, and there's probably a simple thing I'm missing.

`NCook15@Winterfell:/$ sudo docker exec -it netdata ls -l /etc/netdata`
`total 12`
`drwxr-xr-x    1 root     root             0 May 12 00:25 charts.d`
`drwxr-xr-x    1 root     root             0 May 12 00:25 custom-plugins.d`
`-rwxr-xr-x    1 root     root          2045 May 12 00:25 edit-config`
`drwxr-xr-x    1 root     root             0 May 12 00:25 go.d`
`drwxr-xr-x    1 root     root             0 May 12 00:25 health.d`
`-rw-r--r--    1 root     root           208 May 12 00:25 netdata.conf`
`drwxr-xr-x    1 root     root             0 May 12 00:25 node.d`
`lrwxrwxrwx    1 root     root            23 May 12 00:25 orig -> /usr/lib/netdata/conf.d`
`drwxr-xr-x    1 root     root             0 May 12 00:25 python.d`
`drwxr-xr-x    1 root     root             0 May 12 00:25 ssl`
`drwxr-xr-x    1 root     root             0 May 12 00:25 statsd.d`

**Comment by ilyam8** [comment]
> That's odd... I do see the files when I run the command you listed, but there is no netdata directory when I look in /etc/

Keep in mind this directory is _inside_ docker container, it is no in `/etc/`

**Comment by NCook15** [comment]
Ah, ok, that makes sense. Thanks, @ilyam8. Since it's inside the docker container, is there a way to edit it? I was going to try the workaround listed in [#3764](https://github.com/netdata/netdata/issues/3764), setting `web files owner = root` to see if it fixes the "Access to file '/usr/share/netdata/web/index.html' is not permitted" problem I'm running into.

However, I will wait and see what comes out of #8969.

**Comment by ilyam8** [comment]
well, to persist configuration files i would suggest to use bind volume

- create temp netdata and copy user configs to the `netdataconf/`

```cmd
docker run --rm -d --name netdata_tmp netdata/netdata
docker cp netdata_tmp:/etc/netdata/ netdataconf/
docker stop netdata_tmp
```

 - create netdata and mount `netdataconf/`
```cmd
docker run -d --name=netdata \
  -p 19999:19999 \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v $(pwd)/netdataconf:/etc/netdata:ro \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  netdata/netdata
```

___

so you have all netdata configs in the host system.

**Comment by ilyam8** [comment]
And you need to wait for v1.22.1 docker image, v1.22.0 has broken web
