### ISSUE TITLE
Container with Netdata as non-root is not working.

### ISSUE THREAD

**Issue by dmnc-net** [netdata/netdata#8972]
##### Bug report summary
Docker: Netdata can't access index.html while running as non-root user. `/usr/sbin/netdata` is running under `netdata` user. Even with exported `DOCKER_USR` variable I can't change it.
It seems to be ignored or not passed to container because `DO_NOT_TRACK` is not working neither (I've tried to export variables and also run docker command like this: `DOCKER_USR="root" docker run -d --name=netdata ...`).

Error: `Access to file is not permitted: /usr/share/netdata/web//index.html`

##### OS / Environment
- host: Debian 10 (kvm guest), kernel release 4.19.0-9-amd64, version 4.19.118-2 (2020-04-29)
- Docker version: 9.03.8, build afacb8b7f0
- Netdata: Docker container from `netdata/netdata:latest` (Alpine based)

##### Netdata version
netdata v1.22.0-7-g656c7556

##### Docker command
```bash
docker run -d --name=netdata \
  -p 19999:19999 \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  --env VIRTUALIZATION=kvm
  netdata/netdata
```
source: [Netdata learn](https://learn.netdata.cloud/docs/agent/packaging/docker/#run-the-agent-with-the-docker-command)

##### solution?
Dirty solution is edit `/usr/sbin/run.sh` and set `exec /usr/sbin/netdata -u root` instead of `-u "${DOCKER_USR}"`

##### tests
ssh into the container:
- user running Netdata: `ps`
- permissions issue: `curl localhost:19999`

**Comment by dmnc-net** [comment]
I see, I can control the `DOCKER_USR` and `DO_NOT_TRACK` with `--env` during the container creation. But still, I don't want to run that as root (even inside the container) and the Netdata Learn Docker command produces permission issue.

**Comment by dmnc-net** [comment]
So this is at least working Docker command:
```
docker run -d --name=netdata \
  -p 19999:19999 \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  --env VIRTUALIZATION=kvm \
  --env DOCKER_USR=root \
  --env DO_NOT_TRACK=1 \
  netdata/netdata
```

- `DOCKER_USR` env
- `DO_NOT_TRACK` to stop anon. statistics
- bind Docker socket

**Comment by Cellane** [comment]
@dmnc-net This also fixed my Netdata deployment in Dokku, thank you! 🎉

**Comment by ilyam8** [comment]
dup of #8969
