### ISSUE TITLE
smartd: after 30 min netdata loose logs 'connection'

### ISSUE THREAD

**Issue by k0ste** [netdata/netdata#8975]
##### Bug report summary

1. Restart smartd;
2. Restart netdata;
3. Now netdata get smartd metrics;
4. After 30 minutes:

```
May 12 12:00:36 ceph-osd3 netdata[289930]: 2020-05-12 12:00:36: netdata LOG FLOOD PROTECTION resuming logging from process 'netdata' (prevented 329 logs in the last 1200 seconds).                   
May 12 12:00:36 ceph-osd3 netdata[289930]: 2020-05-12 12:00:36: netdata INFO  : PLUGINSD[python.d] : RRDSET: chart name 'smartd_log.read_error_rate' on host 'ceph-osd3' already exists.              
May 12 12:00:36 ceph-osd3 netdata[289930]: 2020-05-12 12:00:36: netdata INFO  : PLUGINSD[python.d] : RRDSET: chart name 'smartd_log.throughput_performance' on host 'ceph-osd3' already exists.       
May 12 12:00:36 ceph-osd3 netdata[289930]: 2020-05-12 12:00:36: netdata INFO  : PLUGINSD[python.d] : RRDSET: chart name 'smartd_log.spin_up_time' on host 'ceph-osd3' already exists.                 
May 12 12:00:36 ceph-osd3 netdata[289930]: 2020-05-12 12:00:36: netdata INFO  : PLUGINSD[python.d] : RRDSET: chart name 'smartd_log.reallocated_sectors_count' on host 'ceph-osd3' already exists.    
May 12 12:00:36 ceph-osd3 netdata[289930]: 2020-05-12 12:00:36: netdata INFO  : PLUGINSD[python.d] : RRDSET: chart name 'smartd_log.seek_error_rate' on host 'ceph-osd3' already exists.              
May 12 12:00:36 ceph-osd3 netdata[289930]: 2020-05-12 12:00:36: netdata INFO  : PLUGINSD[python.d] : RRDSET: chart name 'smartd_log.seek_time_performance' on host 'ceph-osd3' already exists.        
```

And more logs... After this netdata is not catch smartd metrics.

Full logs for smartd & netdata from start
[netdata.service.log](https://github.com/netdata/netdata/files/4613525/netdata.service.log)
[smartd.service.log](https://github.com/netdata/netdata/files/4613526/smartd.service.log)

##### OS / Environment

```
Linux ceph-osd3 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.7.1908 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.7.1908 (Core)
/etc/system-release:CentOS Linux release 7.7.1908 (Core)

```

##### Netdata version

netdata v1.21.1

**Comment by ilyam8** [comment]
hi @k0ste,i think it is expected, smartd module removes all log files which have not been updated in last 30 minutes


https://github.com/netdata/netdata/blob/8562dbbb343c28c3ccf473ebe590587fdca2a160/collectors/python.d.plugin/smartd_log/smartd_log.chart.py#L651-L661

https://github.com/netdata/netdata/blob/8562dbbb343c28c3ccf473ebe590587fdca2a160/collectors/python.d.plugin/smartd_log/smartd_log.chart.py#L613

https://github.com/netdata/netdata/blob/8562dbbb343c28c3ccf473ebe590587fdca2a160/collectors/python.d.plugin/smartd_log/smartd_log.chart.py#L22

**Comment by k0ste** [comment]
@ilyam8, thanks. I found that my deploy is 3600 seconds, instead of defaults 1800.

https://github.com/smartmontools/smartmontools/blob/master/smartmontools/smartd.cpp#L150

It's possible to set `DEF_AGE` via netdata.conf?

**Comment by ilyam8** [comment]
Yes, it is possible - set `age` parameter in the module conf file

**Comment by k0ste** [comment]
I meant `netdata.conf`, not module conf. In this case, it's time to add new features to deployment tool...

Thanks

**Comment by ilyam8** [comment]
> It's possible to set DEF_AGE via netdata.conf?


Oh, man, didnt notice **via netdata.conf** part 🙈 

No, it is not possible, it is module specific parameter
