### ISSUE TITLE
After upgrade to v1.22.0-8-nightly, Cloud-available is False

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#8976]
After check `http://NODE:19999/api/v1/info`:
cloud-enabled: true
cloud-available: false
agent-claimed: false
aclk-available: false

CentOS7, and netdata cloud function is working fine before the upgrade.

Let me know what info you need to help to diagnostic.

**Comment by thiagoftsm** [comment]
Hi @startryst,

Did you claim your agent? Do you have ACLK errors inside your error.log?

Best regards!

**Comment by thiagoftsm** [comment]
Depending of your logs, it is possible this error has relationship with #8977.

**Comment by startryst** [comment]
> Hi @startryst,
> 
> Did you claim your agent? Do you have ACLK errors inside your error.log?
> 
> Best regards!

No, I tired to run the netdata-claim.sh script, but there isn't such script in my machine.

below is the output of ACLK in error.log:
```
grep -i ACLK /var/log/netdata/error.log
2020-05-12 03:32:50: netdata ERROR : MAIN : This agent doesn't have ACLK.
```

**Comment by startryst** [comment]
And since I indicate below earlier, where I think it's not about claim, it's about the system isn't ready:
cloud-available: false
agent-claimed: false
aclk-available: false

**Comment by startryst** [comment]
The below screenshot is the one will show-up every time I opened the dashboard of netdata
![Screen Shot 2020-05-12 at 7 35 22 PM](https://user-images.githubusercontent.com/22472752/81683741-f67be800-9488-11ea-8473-96ab6a0e0fcd.jpg)

**Comment by underhood** [comment]
@startryst We have a new revamped Cloud version with v1.22 that has as consequence brought some new dependencies with it as the way agent communicates with Cloud has changed.

Can you check if `json-c-devel` is present in your system?

**Comment by startryst** [comment]
> @startryst We have a new revamped Cloud version with v1.22 that has as consequence brought some new dependencies with it as the way agent communicates with Cloud has changed.
> 
> Can you check if `json-c-devel` is present in your system?

No, that package is not installed in my CentOS 7, let me know how should I proceed to get it fixed.

**Comment by prologic** [comment]
If you run `./packaging/installer/install-required-packages.sh` frmo our repo this will bring in the new / missing deps. `kickstart.sh` also uses this as well. Not sure how you installed Netdata on to your system though?

**Comment by startryst** [comment]
> If you run `./packaging/installer/install-required-packages.sh` frmo our repo this will bring in the new / missing deps. `kickstart.sh` also uses this as well. Not sure how you installed Netdata on to your system though?

My netdata installed using the suggested/default way, which auto update is turned on, instead of doing anything, can I just wait until my netdata upgraded to v1.22.1, since I see some patches around JSON-C is on that release.

You know if this is the easiest/untouchable way....

**Comment by prologic** [comment]
Unfortunately the `netdata/updater.sh` which is run via Cron doesn't automatically touch your system and update build dependencies (_and IHMO it should.n't_). This is one case where breaking changes and new hard dependencies require some manual intervention. I would suggest you simply re-run `kickstart.sh` again which does everything.

**Comment by startryst** [comment]
> Unfortunately the `netdata/updater.sh` which is run via Cron doesn't automatically touch your system and update build dependencies (_and IHMO it should.n't_). This is one case where breaking changes and new hard dependencies require some manual intervention. I would suggest you simply re-run `kickstart.sh` again which does everything.

where is the `kickstart.sh`? and I assume this will keep my existing configuration unchanged.
