### ISSUE TITLE
web_log_apache.response_codes Escalated to CRITICAL

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#8979]
##### Question summary

What is

```
web_log_apache.response_codes
CHART
last collected secs = 00:01:01 ago
number of seconds since the last successful data collection
ALARM
```
and what am I supposed to do in response to this?

There is no explanation here https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/web_log/.

Apache here is your average facilitator interface - it's not really doing anything.

**Comment by ilyam8** [comment]
Hi @stdedos 

`web_log` modules collects data every second, so we expect to have data and if there is no data - alarm

https://github.com/netdata/netdata/blob/8562dbbb343c28c3ccf473ebe590587fdca2a160/health/health.d/web_log.conf#L4-L14


> last collected secs = 00:01:01 ago

As you see last time web_log returned data - 00:01:01 ago

I think `error.log` is a good place to start

> grep web_log error.log

**Comment by stdedos** [comment]
I am coming up empty:

```console
/var/log/apache2/# grep -Trin web_log
/var/log/apache2/#
```

**Comment by ilyam8** [comment]
Yeah, it is likely the case, i see it takes up to 60 seconds to handle log rotation for web_log.

> /var/log/apache2/# grep -Trin web_log


i meant in the netdata error.log (i installed in `/opt/`)

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:/opt/netdata/var/log/netdata$ ls -l error.log
-rw-r--r-- 1 netdata netdata 5444 May 12 08:25 error.log
```

**Comment by stdedos** [comment]
```console
/var/log/netdata$ grep web_log -TrinI
error.log.1: 385       :2020-05-10 04:36:43: go.d INFO: main[main] module 'web_log' disabled by default
error.log.1: 654       :2020-05-10 07:36:44: python.d INFO: plugin[main] : [web_log] built 13 job(s) configs
error.log.1: 945       :2020-05-10 07:36:44: python.d ERROR: web_log[nginx_log] : /var/log/nginx/access.log not readable or not exist
error.log.1: 946       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[nginx_log] : check failed
error.log.1: 947       :2020-05-10 07:36:44: python.d ERROR: web_log[nginx_log2] : /var/log/nginx/localhost.access_log not readable or not exist
error.log.1: 948       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[nginx_log2] : check failed
error.log.1: 949       :2020-05-10 07:36:44: python.d INFO: web_log[apache_log] : Collected data: ['request', 'code', 'bytes_sent', 'address']
error.log.1: 950       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[apache_log] : check success
error.log.1: 951       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[apache_log2] : already served by another job, skipping it
error.log.1: 952       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[apache_log3] : already served by another job, skipping it
error.log.1: 953       :2020-05-10 07:36:44: python.d ERROR: web_log[apache_vhosts_log] : /var/log/apache2/other_vhosts_access.log is empty
error.log.1: 954       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[apache_vhosts_log] : check failed
error.log.1: 955       :2020-05-10 07:36:44: python.d ERROR: web_log[gunicorn_log] : /var/log/gunicorn/access.log not readable or not exist
error.log.1: 956       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[gunicorn_log] : check failed
error.log.1: 957       :2020-05-10 07:36:44: python.d ERROR: web_log[gunicorn_log2] : /var/log/gunicorn/gunicorn-access.log not readable or not exist
error.log.1: 958       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[gunicorn_log2] : check failed
error.log.1: 959       :2020-05-10 07:36:44: python.d ERROR: web_log[apache_cache] : /var/log/apache/cache.log not readable or not exist
error.log.1: 960       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[apache_cache] : check failed
error.log.1: 961       :2020-05-10 07:36:44: python.d ERROR: web_log[apache2_cache] : /var/log/apache2/cache.log not readable or not exist
error.log.1: 962       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[apache2_cache] : check failed
error.log.1: 963       :2020-05-10 07:36:44: python.d ERROR: web_log[httpd_cache] : /var/log/httpd/cache.log not readable or not exist
error.log.1: 964       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[httpd_cache] : check failed
error.log.1: 965       :2020-05-10 07:36:44: python.d ERROR: web_log[squid_log1] : /var/log/squid3/access.log not readable or not exist
error.log.1: 966       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[squid_log1] : check failed
error.log.1: 967       :2020-05-10 07:36:44: python.d ERROR: web_log[squid_log2] : /var/log/squid/access.log not readable or not exist
error.log.1: 968       :2020-05-10 07:36:44: python.d INFO: plugin[main] : web_log[squid_log2] : check failed
error.log.1:1009       :2020-05-10 07:36:54: python.d INFO: web_log[apache_log] : chart 'web_log_apache.vhost' was suppressed due to non updating
error.log.1:1010       :2020-05-10 07:36:54: python.d INFO: web_log[apache_log] : chart 'web_log_apache.port' was suppressed due to non updating
error.log.1:1760       :2020-05-12 07:36:50: alarm-notify.sh: INFO: sent email notification for: sntentos-precision-t3620 web_log_apache.response_codes.last_collected_secs is WARNING to 'root'
error.log.1:1764       :2020-05-12 07:37:40: alarm-notify.sh: INFO: sent email notification for: sntentos-precision-t3620 web_log_apache.response_codes.last_collected_secs is CRITICAL to 'root'
error.log: 263 :2020-05-12 04:39:10: go.d INFO: main[main] module 'web_log' disabled by default
error.log: 530 :2020-05-12 07:39:10: python.d INFO: plugin[main] : [web_log] built 13 job(s) configs
error.log: 821 :2020-05-12 07:39:11: python.d ERROR: web_log[nginx_log] : /var/log/nginx/access.log not readable or not exist
error.log: 822 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[nginx_log] : check failed
error.log: 823 :2020-05-12 07:39:11: python.d ERROR: web_log[nginx_log2] : /var/log/nginx/localhost.access_log not readable or not exist
error.log: 824 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[nginx_log2] : check failed
error.log: 825 :2020-05-12 07:39:11: python.d INFO: web_log[apache_log] : Collected data: ['request', 'code', 'bytes_sent', 'address']
error.log: 826 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[apache_log] : check success
error.log: 827 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[apache_log2] : already served by another job, skipping it
error.log: 828 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[apache_log3] : already served by another job, skipping it
error.log: 829 :2020-05-12 07:39:11: python.d ERROR: web_log[apache_vhosts_log] : /var/log/apache2/other_vhosts_access.log is empty
error.log: 830 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[apache_vhosts_log] : check failed
error.log: 831 :2020-05-12 07:39:11: python.d ERROR: web_log[gunicorn_log] : /var/log/gunicorn/access.log not readable or not exist
error.log: 832 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[gunicorn_log] : check failed
error.log: 833 :2020-05-12 07:39:11: python.d ERROR: web_log[gunicorn_log2] : /var/log/gunicorn/gunicorn-access.log not readable or not exist
error.log: 834 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[gunicorn_log2] : check failed
error.log: 835 :2020-05-12 07:39:11: python.d ERROR: web_log[apache_cache] : /var/log/apache/cache.log not readable or not exist
error.log: 836 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[apache_cache] : check failed
error.log: 837 :2020-05-12 07:39:11: python.d ERROR: web_log[apache2_cache] : /var/log/apache2/cache.log not readable or not exist
error.log: 838 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[apache2_cache] : check failed
error.log: 839 :2020-05-12 07:39:11: python.d ERROR: web_log[httpd_cache] : /var/log/httpd/cache.log not readable or not exist
error.log: 840 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[httpd_cache] : check failed
error.log: 841 :2020-05-12 07:39:11: python.d ERROR: web_log[squid_log1] : /var/log/squid3/access.log not readable or not exist
error.log: 842 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[squid_log1] : check failed
error.log: 843 :2020-05-12 07:39:11: python.d ERROR: web_log[squid_log2] : /var/log/squid/access.log not readable or not exist
error.log: 844 :2020-05-12 07:39:11: python.d INFO: plugin[main] : web_log[squid_log2] : check failed
error.log: 890 :2020-05-12 07:39:20: alarm-notify.sh: INFO: not sending notification for CLEAR of 'sntentos-precision-t3620.web_log_apache.response_codes.last_collected_secs' (last status was UNINITIALIZED)
error.log: 893 :2020-05-12 07:39:21: python.d INFO: web_log[apache_log] : chart 'web_log_apache.vhost' was suppressed due to non updating
error.log: 894 :2020-05-12 07:39:21: python.d INFO: web_log[apache_log] : chart 'web_log_apache.port' was suppressed due to non updating
```

**Comment by stdedos** [comment]
Your rotation seems off too:
```
error.log.1:1760       :2020-05-12 07:36:50: alarm-notify.sh: INFO: sent email notification for: sntentos-precision-t3620 web_log_apache.response_codes.last_collected_secs is WARNING to 'root'
error.log.1:1764       :2020-05-12 07:37:40: alarm-notify.sh: INFO: sent email notification for: sntentos-precision-t3620 web_log_apache.response_codes.last_collected_secs is CRITICAL to 'root'
error.log  : 263       :2020-05-12 04:39:10: go.d INFO: main[main] module 'web_log' disabled by default
error.log  : 530       :2020-05-12 07:39:10: python.d INFO: plugin[main] : [web_log] built 13 job(s) configs
```

**Comment by ilyam8** [comment]
> error.log.1: 385       :2020-05-10 04:36:43: go.d INFO: main[main] module 'web_log' disabled by default
error.log.1: 654       :2020-05-10 07:36:44: python.d INFO: plugin[main] : [web_log] built 13 job(s) configs

> error.log: 263 :2020-05-12 04:39:10: go.d INFO: main[main] module 'web_log' disabled by default
error.log: 530 :2020-05-12 07:39:10: python.d INFO: plugin[main] : [web_log] built 13 job(s) configs

i see both `go.d` and `python.d` plugins were restarted at 07:36:43 and at 07:39:10

Did you restart it manually?

**Comment by stdedos** [comment]
I was _a lot_ asleep at the time, so no. Could it be automatic updates of netdata?

I do have https://github.com/liske/needrestart installed (which could trigger this as post-update hook), but all updates are manual and explicitly verified by me (_and I was asleep at-the-time_)

**Comment by ilyam8** [comment]
> Could it be automatic updates of netdata?

Could be, but there are 2 restarts 🤔

Do you get this alarm every morning?

**Comment by stdedos** [comment]
No, it's the second time I am getting this alarm over my netdata period. The first time it scared me as _hell_, and now again too (considering again, that this apache does nothing more than facilitating this or that, and by no means anything else, getting any considerable amount of traffic etc etc).

After my epiphany with log rotation I feel a lot more relaxed (and a lot more inclined to say that this is a bug on your side).

**Comment by ilyam8** [comment]
> a bug on your side

if so you would get the alarm every log rotate interval

and i am not sure why there is 2 restarts

> https://github.com/netdata/netdata/issues/8979#issuecomment-627256287

anyway i think it is safe to add delay up timeout to the alarm

something like

```
    delay: down 5m up 70s multiplier 1.5 max 1h 

```

**Comment by ilyam8** [comment]
@stdedos [i see](https://linux.die.net/man/8/logrotate) there is `-f` parameter to force log rotation, could you test it? Does log rotation cause the alarm?

**Comment by stdedos** [comment]
> > a bug on your side
> 
> if so you would get the alarm every log rotate interval

As I was investigating, I was dumb enough to purge all of my compressed rotation 😕
So ... it is 1-2 months that my server needs to rotate logs? Maybe, but that's a very thin chance. So probably there is some race condition that could go on (and I don't know why the rotation delay would be so much).

> and i am not sure why there is 2 restarts
> 
> > [#8979 (comment)](https://github.com/netdata/netdata/issues/8979#issuecomment-627256287)

Beats me 😕 netdata is silent for me, except with my disk space alarm and VMWare auto-snapshot feature (they are pretty close, and I get like 2+2 emails every ~3 hours or so)

> anyway i think it is safe to add delay up timeout to the alarm
> 
> something like
> 
> ```
>     delay: down 5m up 70s multiplier 1.5 max 1h 
> ```

I guess I can try this can call this quits too

> [i see](https://linux.die.net/man/8/logrotate) there is `-f` parameter to force log rotation, could you test it? Does log rotation cause the alarm?

I can try that tomorrow I guess

**Comment by stdedos** [comment]
It seems that I am log-rotating daily, so no need to force to logrotate.
Also, no warning today. So I guess this really happens once in a blue moon.

Can I add only an override to the alarm to some other, non-netdata file, or do I have to patch that specific file? At this time, I cannot decide if it's cleaner to patch the file itself, or override it cleanly, separately, with my own (the latter being more clear) - or if you support something like that at all

**Comment by ilyam8** [comment]
well, as for all user configs you need to `edit-config` it (we have stock and user configs, stock are being overwritten on every update)

from `/etc/netdata`

> sudo ./edit-config health.d/web_log.conf

Add changes to the `/etc/netdata/health.d/web_log.conf`

**Comment by stdedos** [comment]
That looks like much coarse that the +1,-1 change I wanted to do 😕

Cost/benefit (given the cost) does not seem worth it

**Comment by ilyam8** [comment]
> That looks like much coarse that the +1,-1 change I wanted to do

do you mean a PR?

i dont want to do it because

> So I guess this really happens once in a blue moon.

and i am not really understand why, i need to check it (to play with logrotate)

**Comment by stdedos** [comment]
> That looks like much coarse that the +1,-1 change I wanted to do

My expectations:
```
$ sudo ./edit-config health.d/web_log.conf
override: 
template: last_collected_secs
delay +: up 70s # or I could settle with replacing the whole line
```

Reality:

`mv /usr/.../health.d/web_log.conf /etc/netdata/health.d/web_log.conf`

(It's not _really_ `mv`, but it looks clear to me that from now on, the `/usr/` file is ignored)

> > So I guess this really happens once in a blue moon.
> 
> and i am not really understand why, i need to check it (to play with logrotate)

**Comment by ilyam8** [comment]
> (It's not really mv, but it looks clear to me that from now on, the /usr/ file is ignored)


yes, if there is a user config we ignore the stock config, that is how you change stock - copy it to the user dir and make changes there.

edit-config is a helper script

**Comment by stdedos** [comment]
> yes, if there is a user config we ignore the stock config, that is how you change stock - copy it to the user dir and make changes there.

This is why I call this overkill. I don't want to fall back in configuration, for one very small change.

In a sense, I would much more prefer resolving `dpkg` diff-conflicts each time, rather than risk falling behind updates.

Or even keep getting the error.
