### ISSUE TITLE
v1.22.0 Access to file '/usr/share/netdata/web/index.html' is not permitted

### ISSUE THREAD

**Issue by GNURub** [netdata/netdata#8983]
Using docker image netdata/netdata:v1.22.0 I get this error:

`Access to file '/usr/share/netdata/web/index.html' is not permitted`

(With version v1.21.1 works fine!)

**Comment by spupuz** [comment]
same error here

**Comment by ilyam8** [comment]
hi @GNURub, we are working on it

dup of #8969
