### ISSUE TITLE
ACLK related metrics

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#8989]
##### Feature idea summary
We should have a few basic metrics in Netdata related to ACLK.
This will help debug issues and prevent the need to add debug messages everywhere.

Example:
- kbps upload/download per second
- messages per second
- size of outgoing queue
- size of incoming data queue (between LWS and MOSQ)
- latency?

##### Expected behavior
New charts in `Netdata Monitoring` group of Netdata Dashboard related to ACLK

**Comment by amoss** [comment]
This is a good idea, we should have the same for streaming instead of the current logging.
