### ISSUE TITLE
Remove old docs generation scripts and CI checks

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#8990]
We need to remove all of the scripts, Netlify deploy previews, and CI checks related to building the old documentation site, which no longer exists. This is already interrupting the process of merging PRs, since the Netlify checks inevitably fail for one reason or another.

Here is my plan for removing this old logic:

1. **Remove scripts to build translations**. We're already having issues with the localization project causing build failures, and no one should be spending time maintaining these files. A broken link in the localization repo means nothing, since those files are not published anywhere.
2. **Clean up the `buildhtml.sh` script** so that it's as simple as possible. It doesn't need to run `mkdocs` if it's only checking for broken links.
3. **Convert the link-checking script into its own CI action** that can verify whether links are structured correctly in the documentation. This will ensure we don't merge PRs in netdata/netdata that contain broken links.
4. **Wind down localization project**. Add a notice to the README that it's not being used/maintained any more. Search the docs for any mentions of it, and remove.
5. **Remove all the old docs generation tooling**, minus the link-checking CI, in a fashion similar to what @prologic wanted to do with #8783.

Here's the CI currently exists on the Learn site:

1. **A daily job checking for broken internal links**. This check uses [broken-link-checker](https://www.npmjs.com/package/broken-link-checker) by running `npx broken-link-checker $WEBSITE_URL --ordered --recursive --exclude-external` to check all _internal_ links. If it finds any broken internal links, it creates an issue with the output so I know which link to fix.
2. **A weekly job checking for broken external links**. This never existed with the old docs site, so it's actually an enhancement over what we had. This runs `npx broken-link-checker $WEBSITE_URL -rof --exclude-internal --requests=2 --exclude "netdata.cloud/" --exclude "https://www.linkedin.com/company/my-netdata.io/" --exclude "https://github.com/" --exclude "my-netdata.io" --exclude "http://localhost" --exclude "firehol.org" --exclude "circleci.com" --exclude "redis.io" --exclude "telegram.org" --exclude "t.me"` to check all _external_ links, and again creates an issue if it finds any.
3. **A Markdown link checking GitHub Action on every PR**. This will catch any additional link errors that somehow escaped the initial checks in netdata/netdata.

And a plan for additional Learn CI:

1. **Automated ingest/deployment of changed docs**. I currently do the process manually, but we can automate it. It can run every day, every hour, or on manual trigger.
2. **Deploy previews for PRs in netdata/netdata**. This would replicate the behavior we used to have with the Netlify deploys using the automated ingest/deploy process. I'm not sure about how to do this yet, but @prologic confirmed to me that it's possible.

cc @cakrit

**Comment by prologic** [comment]
As discussed we can also trigger a downstream workflow from the merge of a PR to netdata/netdata that changes documentation. This is possible.

**Comment by prologic** [comment]
The only thing missing here is the Preview(s) -- But to be honest I never found them that useful myself and I preview to review the diffs and use the rich diff viewer in Github itself on things like Markdown.

**Comment by cakrit** [comment]
- The previews ARE useful, html isn't the same as markdown. I'm ok with temporarily not having them.
- Needs another task, to kill the localization project itself. Change its main README and any mention of it in the docs to begin with and eventually archive the project.

Other than that, I'm good with the plan.

**Comment by prologic** [comment]
> The previews ARE useful, html isn't the same as markdown. I'm ok with temporarily not having them.

@joelhans Are you able to look into what options we have here with Docusaurus? We just need a way to trigger some workflows to build the thing and host _that_ version somewhere.

**Comment by joelhans** [comment]
@prologic I'll investigate the previews. I never used them either, but if others find them useful, let's make sure they get added at some point.

@cakrit I added a step about localization. Can you help review the PRs related to this project? We can, and _should_, remove all the old docs tooling ASAP. #8991, #8994, and #9003 in particular.

**Comment by joelhans** [comment]
I also just ported over the work I did in #9003 to the Learn site. This way, we'll have link validation on the PR stage going in to netdata/netdata and an additional link validation check when I rebuild the docs site.

**Comment by cakrit** [comment]
Please complete the work between the two of you, I really can't help at all this week.

**Comment by joelhans** [comment]
Closing this, as I've accomplished all the tasks involved in removing old CI and creating new CI to enforce the necessary checks in the repo. We'll plan out and prioritize the deploy previews portion of this in the weeks ahead.
