### ISSUE TITLE
Netdata Cloud - Total Network Bandwidth - exclude interfaces

### ISSUE THREAD

**Issue by Nordikk** [netdata/netdata#8995]
Hi, I didn't find a solution to this via Google, so I'm now asking here.

In the Netdata Cloud, specifically in the metric "Total Network Bandwidth", how can I exclude interfaces from there? I want to exclude the interfaces marked in the screenshot. (The interface cgroup_bluemine.net_eth0 doesn't even exist anymore.)

![Anmerkung 2020-05-12 180147](https://user-images.githubusercontent.com/48895515/81717548-f70d8200-947a-11ea-97dd-ab30242b899a.png)

**Comment by ilyam8** [comment]
@Nordikk 👋 i am pretty sure it is on roadmap and will be fixed soon

@manos-saratsis please take a look

**Comment by manos-saratsis** [comment]
@Nordikk thx for using Netdata Cloud. It's a valid concern and we will add it in the roadmap.

**Comment by Nordikk** [comment]
Alright! Thanks for the quick answer. Have a nice day :)

**Comment by squash** [comment]
This issue is still unsolved. Is there a issue tracking it other than this one?
