### ISSUE TITLE
Netdata cloud 'see our documentation' uses JS link

### ISSUE THREAD

**Issue by webash** [netdata/netdata#8997]
##### Bug report summary
The link 'see our documentation' link on the 'claim first nodes' page doesn't populate the `href` tag of the `<a>`, so you can't middle click/use your own link handler. Please use a standard link.

##### OS / Environment

```
https://app.netdata.cloud/spaces/<space>/rooms/<room>/onboarding/claimNodes
```

##### Netdata version

Netdata Cloud

##### Component Name

Netdata Cloud

##### Steps To Reproduce

1. Sign-up
2. Go through onboarding steps
3. Get to 'claim' page

##### Expected behavior

Link should utilise standard `<a href="destination">` HTML rather than a JS onclick.

**Comment by builat** [comment]
@webash should be resolved. Please confirm.

**Comment by webash** [comment]
Yeap! Working! Thanks!
