### ISSUE TITLE
Manage claimed nodes does not actually allow management of already claimed nodes

### ISSUE THREAD

**Issue by webash** [netdata/netdata#8998]
##### Bug report summary

When clicking 'Manage claimed nodes' in a Space, you'd expect options for managing nodes that have already been claimed, instead the fly-out shows instructions for _claiming_ nodes, and shows recently claimed nodes. There are no management or deletion capabilities here.

##### OS / Environment

```
Netdata Cloud > select a space > click space dropdown > click Manage claim nodes
```

##### Netdata version

 Netdata Cloud

##### Component Name

Netdata Cloud

##### Steps To Reproduce

1. Netdata Cloud
2. select a space 
3. click space dropdown 
4. click Manage claim nodes

##### Expected behavior

I would expect to be able to delete nodes here. Instead even if that node doesn't exist anymore, there is no explicit node deletion, just the removal from a war room. However this doesn't forget the ID / node entirely, and leaves it lingering as if you try to re-register the node, it will say the ID is in use.

**Comment by ilyam8** [comment]
@manos-saratsis take a look

**Comment by ryansk** [comment]
Same issue, here. Following documentation, I'm not actually able to re-register the node, either.

https://learn.netdata.cloud/docs/agent/claim/#unclaim-remove-an-agent-from-netdata-cloud

> Failed to claim node with the following error message:"already claimed"

I tried removing `/var/lib/netdata/cloud.d`, however, I still have the above error. I also removed the node from the previous war room.

**Comment by manos-saratsis** [comment]
@webash Under 'Manage claimed nodes' you can currently see the claiming command and the list of the claimed nodes. We will soon offer a feature letting users to unclaim/delete their nodes from the space.

@ryansk To reclaim/re-register the agent (after removing the /var/lib/netdata/cloud.d/ directory) it is necessary to pick a new identity, this can be done by adding -id=$(uuidgen) to the claiming script parameters.
