### ISSUE TITLE
brew upgrade netdata not getting latest

### ISSUE THREAD

**Issue by breenjoe** [netdata/netdata#9001]
##### Bug report summary
check for updates in application interface at http://localhost:19999 on update tab.
indicates that there is a new version of netdata available (at time of writing latest version is v1.22.1)
run brew upgrade netdata command in terminal on mac - this shows "warning: netdata 1.21.1 already installed." but doesn't upgrade it to the latest available.

##### OS / Environment
```
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
```

##### Steps To Reproduce
1. brew upgrade netdata
2. doesn't upgrade to latest

##### Expected behavior
netdata should be upgraded to version v1.22.1 (latest version at time of writing).

**Comment by ilyam8** [comment]
its over 9k issue 😄

**Comment by prologic** [comment]
Troll :P

**Comment by prologic** [comment]
Anyways... I'm working on this...

**Comment by breenjoe** [comment]
It's working now. :)

**Comment by prologic** [comment]
Looks like I was ~2 days late to the party:

```#!sh
(⎈ |netdata-testing:infra)
prologic@Jamess-iMac
Tue May 19 12:34:34
~/Netdata/homebrew-core
 (master) 141
$ git log ./Formula/netdata.rb
commit 15cf40e00af9e496d2fa36137a8ccbdbe10e352b
Author: Issy Long <me@issyl0.co.uk>
Date:   Sun May 17 21:40:58 2020 +0000

    netdata: update 1.22.1 bottle.
.
.
.
```

This is good! Nothing for me to do here.

**Comment by prologic** [comment]
@issyl0 Is there some way we can help you get `netdata.rb` updated faster to avoid issues like this? Is it something we can automate and automatically send [homebrew-core](https://github.com/Homebrew/homebrew-core) a PR when we release a new version?

**Comment by issyl0** [comment]
@prologic Absolutely. There are a variety of GitHub Actions that can check for releases and automatically run `brew bump-formula-pr`. The one I've used most is https://github.com/marketplace/actions/bump-homebrew-formula.

**Comment by prologic** [comment]
Thank you! I'll look into this!
