### ISSUE TITLE
How to delete Claimed Nodes?

### ISSUE THREAD

**Issue by Nirjonadda** [netdata/netdata#9002]
We have deleted War Room because can not edit War Room name. So we have added new Room But can not Claiming command for this room.

```
Base URL: https://app.netdata.cloud
Id: c88435e0-8887-11ea-bccc-00163c8e5889
Rooms: 16428807-abfe-49e9-b83a-7268cf130e4f
Hostname: mysite.com
Proxy:
Netdata user: netdata
The agent cloud base url is set to the url provided.
The cloud may have different credentials already registered for this agent ID and it cannot be reclaimed under different credentials for security reasons. If you are unable to connect use -id=$(uuidgen) to overwrite this agent ID with a fresh value if the original credentials cannot be restored.
Failed to claim node with the following error message:"already claimed"
[root@na ~]#
```

**Comment by Nirjonadda** [comment]
OK done [this steps](https://learn.netdata.cloud/docs/agent/claim/#unclaim-remove-an-agent-from-netdata-cloud) but still having this issue.

```
cd /var/lib/netdata
sudo rm -rf cloud.d/
```

**Comment by RoyalClem** [comment]
I am having the same issues too. I updated netdata, and now my cloud.d is regenerated. The cloud.d folder is empty, but still getting the same issue.

`Base URL: https://app.netdata.cloud
Id: b8c2765e-93e9-11ea-b4fa-dca63263e3be
Rooms: 6cd64977-c22c-4433-98fd-d227490bd4a9
Hostname: gestachpi
Proxy:
Netdata user: netdata
Extracting public key from private key.
writing RSA key
The agent cloud base url is set to the url provided.
The cloud may have different credentials already registered for this agent ID and it cannot be reclaimed under different credentials for security reasons. If you are unable to connect use -id=$(uuidgen) to overwrite this agent ID with a fresh value if the original credentials cannot be restored.
Failed to claim node with the following error message:"already claimed"
`

**Comment by manos-saratsis** [comment]
@Nirjonadda @RoyalClem  When you claim nodes these nodes are claimed to a space and you can add/remove them to rooms. Select a War Room from the left panel, go to Top Navigation Bar -> War Room -> Manage War Room -> Nodes and press the green "+" button to add nodes that are claimed in the space to this War Room.

As you deleted the `cloud.d` directory then your agent will no longer have access to the credentials that it was claimed with. To reclaim the agent it is necessary to pick a new identity, this can be done by adding `-id=$(uuidgen)` to the claiming script parameters.

fyi over the next months we will offer a feature letting users to unclaim their nodes

**Comment by Nirjonadda** [comment]
Perfect, Thanks

**Comment by Nirjonadda** [comment]
> the next months we will offer a feature letting users to unclaim their nodes

@manos-saratsis Do you added ability to delete Recently Claimed Nodes?

**Comment by weijing24** [comment]
> > the next months we will offer a feature letting users to unclaim their nodes
> 
> @manos-saratsis Do you added ability to delete Recently Claimed Nodes?

Seems 1.23.1 still can't delete Recently Claimed Nodes

**Comment by manos-saratsis** [comment]
@Nirjonadda @weijing24 this will be probable done by end of August. Reasoning is that we want to ship some other cool features first. You can delete nodes from War Rooms and if you like re-claim your agents (see my comment above) but the already claimed nodes will remain under Manage Claimed Nodes for now.

**Comment by Nirjonadda** [comment]
@manos-saratsis Please do you have any update?

**Comment by tinyhammers** [comment]
Hey guys...
+1 for this from me too.
I've removed the node from the War Room, and deleted the `/var/lib/netdata/cloud.d` directory, but I'd like to be able to remove it completely from the Space, as I'm trying to automate deployment with Ansible, so need to keep re-running my playbooks, but I'm getting the already claimed error as well.

**Comment by manos-saratsis** [comment]
@Nirjonadda @tinyhammers thx for your patience. Unclaiming is important but we focus on other features first that will improve the monitoring capability of Cloud. Please stay tuned and use the workaround for now.

**Comment by Nirjonadda** [comment]
@manos-saratsis Please let me update when are implemented ability delete Recently Claimed Nodes.

**Comment by arpogo** [comment]
I have dynamic scaling infrastructure, 1 Netdata agent on every prod instance.
But for this i have many dead instances in list, i tried to make a jenkins job for cleaning up dead instances.. but unfortunately only one way to use "netdata cloud api" - https://app.netdata.cloud/api/v1/spaces/${ND_SPACE}/rooms/${ND_ROOM}/nodes 
Is using Cookie - that is really not great,

Would be great to have as min. some Token to get/delete nodes.
Or would to auto-remove unreachable nodes after some time (could be configuration in config)

**Comment by manos-saratsis** [comment]
@arpogo we will offer this feature within the upcoming months. Apologies for the inconvenience in the meanwhile.

**Comment by Nirjonadda** [comment]
> 
> 
> @arpogo we will offer this feature within the upcoming months. Apologies for the inconvenience in the meanwhile.


Now end of November. So when happen this ability?

**Comment by LtSich** [comment]
I try to delete 1 node to claim it on another account.
I have delete the cloud.d directory and run the claim command with -id=$(uuidgen), this generate a new ID but I have this error : 
Failed to claim node with the following error message:"Unknown HTTP error message"
And without the -id param I've got the error that this node is already claimed...
And claimed_id is always the same, must be stored somewhere else.. 

Actually my node is no more up on the old account, and I can't link it to my other account...

**Comment by arpogo** [comment]
> I try to delete 1 node to claim it on another account.
> I have delete the cloud.d directory and run the claim command with -id=$(uuidgen), this generate a new ID but I have this error :
> Failed to claim node with the following error message:"Unknown HTTP error message"
> And without the -id param I've got the error that this node is already claimed...
> And claimed_id is always the same, must be stored somewhere else..
> 
> Actually my node is no more up on the old account, and I can't link it to my other account...

What is connection with current topic ? Please check FAQ there is good description how to reclaim your node.

**Comment by manos-saratsis** [comment]
@LtSich Apologies for the inconvenience. Unclaiming will be delivered within the first months of 2021.
I advice to use the instructions in our documentation https://learn.netdata.cloud/docs/agent/claim#remove-and-reclaim-a-node

**Comment by arpogo** [comment]
Still relevant...still waiting...

As we have dynamic infrastructure it's really taking some time daily to remove dead instances.
Also, couldn't find any API to do that.. 
Would be great to have ability to identify instance by some name/id that can be same reused when old instance is dead.

**Comment by manos-saratsis** [comment]
@arpogo apologies for all the delay. Currently you can remove them from a War Room only manually. We understand that this is not convenient and we will be soon working both on unclaiming from GUI and from the claiming script but also on improving War Room management. We do not plan to expose an api for now.

**Comment by louis-lau** [comment]
For dynamic infra a setting to automatically delete a node after it's been offline for a while would also be nice idea.

**Comment by OdysLam** [comment]
Since we have moved our support process to our new Community Forums at https://community.netdata.cloud, I am closing this issue!

Let's continue the discussion there, with a new topic in the Netdata Cloud Support or Feature Request category. 

Best,
Odysseas

**Comment by shinebayar-g** [comment]
Will this feature implemented by this year?

**Comment by danesparza** [comment]
This page does not exist in community (or is marked private).  Is this something that is not an option?  I find that hard to believe.

**Comment by cakrit** [comment]
Here's a more updated community link: https://community.netdata.cloud/t/deleting-a-node-from-the-ui/28/15

The delete functionality was added a little over a month ago, and has been greatly improved with yesterday's deployment. If you access the space settings and go to Nodes, you see the following table that allows you to filter all offline nodes, mass select them and bulk delete them. No more deleting one by one and it works great for the "All nodes" room too.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/43294513/181786101-f91df8db-086d-45fd-a6a2-e8efdb9ca0cb.png">
