### ISSUE TITLE
mysql go plugin is not showing the replication lag time in the alert template

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9006]
##### Bug report summary

Mysql replication lag is not showing the current value in the alert template:
![image](https://user-images.githubusercontent.com/7656049/81771531-7ab98400-94f8-11ea-9035-3c2545ff012b.png)
the color is green so the alert is fine but since the value is undefined, I'm not sure if we get alarmed if the threshold is passed 
Here is the alert template for this database:
```
template: mysql_replication_lag_mariadb-08
      on: mysql.slave_behind
   hosts: mariadb-08.db.x.y.z 
    calc: $seconds
   units: seconds
   every: 10s
#    warn: $this > (($status >= $WARNING)  ? (5)  : (10))
#     critical when 6h:30m behind master
    crit: $this > 23400
   delay: up 15s down 15m multiplier 1.5 max 1h
    info: the number of seconds mysql replication is behind this master
      to: dba
```
Here is the corresponding chart:
![image](https://user-images.githubusercontent.com/7656049/81772482-38de0d00-94fb-11ea-9976-c593f62cdc4c.png)

I'm using go version of the MySQL plugin and I didn't have such problem with the python version:
![image](https://user-images.githubusercontent.com/7656049/81771845-501bfb00-94f9-11ea-97a9-841bc0394256.png)
Alert template:
```
template: mysql_replication_lag
      on: mysql.slave_behind
   hosts: !mariadb-08.db.x.y.z *
    calc: $seconds
   units: seconds
   every: 10s
#    warn: $this > (($status >= $WARNING)  ? (5)  : (10))
#     crit: $this > (($status == $CRITICAL) ? ({{mysql_replication_min_critical}}) : ({{mysql_replication_max_critical}})) 
    crit: $this > 900
   delay: up 15s down 15m multiplier 1.5 max 1h
    info: the number of seconds mysql replication is behind this master
      to: dba
```
I'm not sure if it is related or not but the netdata update interval on `mariadb-08` is 10 seconds and on the other host is 5 seconds.

##### Netdata version

 
Both master and slave are running `v1.22.0`
##### Component Name

go.d.plugins
##### Expected behavior

Show the current value instead of `undefined`

**Comment by ilyam8** [comment]
> calc: $seconds

should be `$seconds_behind_master` or `$time`

https://github.com/netdata/go.d.plugin/blob/b33118b931768edbb5803166905555576e4c17db/modules/mysql/charts.go#L496

**Comment by yasharne** [comment]
@ilyam8 so there is an inconsistency in the alert templates? because it calculates the `$seconds` in the template:
https://github.com/netdata/netdata/blob/master/health/health.d/mysql.conf#L90
I'm migrating some of our plugins from their python version to the go version, is there any way to check if the alert templates are compatible with the go version plugins?
