### ISSUE TITLE
Disk backlog question

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#9007]
##### Question summary
I have received an e-mail for disk backlog issues for the highlighted region:

![netdata-backlog_alarm-vivaldi_2020-05-13_10-16-21](https://user-images.githubusercontent.com/133706/81783036-734ba800-9503-11ea-8b82-065c9f3b09fe.png)

but not for the region that precedes it.

* Is there some heuristic that this alarm is working on?
* Is there a list of the top 10 processes (or something), so that I can find the culprit of this one? (although I do have a suspect)

**Comment by stdedos** [comment]
Given no objections @stale, I'd prefer a response 😃

**Comment by ilyam8** [comment]
> Is there some heuristic that this alarm is working on?

Hi

https://github.com/netdata/netdata/blob/1bd8a255441de6056a0d51a7bb787f76b590ffb6/health/health.d/disks.conf#L158-L164


> Is there a list of the top 10 processes (or something), so that I can find the culprit of this one? (although I do have a suspect)

We have not top processes and processes in general, there are process groups - see appl.plugin charts.

**Comment by stdedos** [comment]
> > Is there some heuristic that this alarm is working on?
> 
> Hi
> 
> https://github.com/netdata/netdata/blob/1bd8a255441de6056a0d51a7bb787f76b590ffb6/health/health.d/disks.conf#L158-L164

I haven't graduated reading netdata configuration 😅.

I assume this means "for a sliding window average between [-10,0) minutes from now"?

> > Is there a list of the top 10 processes (or something), so that I can find the culprit of this one? (although I do have a suspect)
> 
> We have no top processes and processes in general, there are processes groups - see appl.plugin charts (`Applications` section on the dashboard).

Good to know, thanks!
Would someone fix the links that lead to https://github.com/netdata/netdata/blob/master/docs/Add-more-charts-to-netdata.md ?

I am on v1.22.1-256-nightly (the latest?), and I am getting a semi-dead link.

**Comment by ilyam8** [comment]
> I assume this means "for a sliding window average between [-10,0) minutes from now"?

Yes.

> Would someone fix the links that lead to /docs/Add-more-charts-to-netdata.md@master ?

@joelhans please take a look

**Comment by stdedos** [comment]
Well, the e-mail arrived ~02:50 in the night ... so I guess it kinda looks like it made sense? 😕 

I would think a more spot-on notification would be in order, but I am not complaining. I would've snored equally loud at-the-time 😁

**Comment by joelhans** [comment]
> Would someone fix the links that lead to https://github.com/netdata/netdata/blob/master/docs/Add-more-charts-to-netdata.md ?

@stdedos Where are you seeing these links? I've been poking around and I haven't been able to find links that point to that document.

**Comment by stdedos** [comment]
I think it is on "Add more charts" on the main page of Netdata app (or something like that, I don't have access to it at the moment)

**Comment by joelhans** [comment]
Oh, I see them now. Yes, I'll be sure to change those links. Thanks for letting us know.
