### ISSUE TITLE
New UI questions

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#9008]
##### Question summary

![netdata-backlog_alarm-vivaldi_2020-05-13_10-16-21](https://user-images.githubusercontent.com/133706/81783036-734ba800-9503-11ea-8b82-065c9f3b09fe.png)

* Highlighting animation seems a bit off to me - in the way that from the time I Alt+Click, to the time I click again, there is nothing obvious on what I started. If it would be too taxing to continuously focus the mouse and draw a fake highlight region, could at least half of this information be drawn at the time?
   Like "Highlighted time-frame: $start to ....", and draw thin bar at the start time.
* The sidebar on the left (not visible in the screenshot) - is this only for switching between cloud accounts/instances? If so, for me that doesn't care for that stuff - could it be removed? (or repurposed, see next)
* I used to be able to have stored, among my three instances, links to the other two instances (something-something configuring something on all three nodes as being my own netdata servers to each other).
  * Now that doesn't seem to work like that anymore?
  * Can it be so that the nodes are "permantely" stored as Visited/Bookmarked Nodes, or have the aforementioned sidebar repurposed?

**Comment by stdedos** [comment]
pls @stalebot

**Comment by ilyam8** [comment]
@dim08 please take a look, ther are user experience agent dashboard related question

**Comment by dim08** [comment]
Hi there will try to address this as part of a new feature we are currently designing

**Comment by stdedos** [comment]
Kindly use automated closing https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue so I can keep track of this.

Thanks!
