### ISSUE TITLE
Netdata not printing shown area, reverts to `$now` instead

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#9009]
##### Bug report summary
I have a specific area shown & highlighted, and I press Print.
I expect I will print what I see.

Instead, I am printing `$now`:
![netdata-print_bug-vivaldi_2020-05-13_10-45-00](https://user-images.githubusercontent.com/133706/81786843-de4bad80-9508-11ea-9750-76716257eed1.png)

##### OS / Environment

```
latest Ubuntu Xenial
```

##### Netdata version

 v1.22.1-4-nightly

##### Component Name

Web Component Printing

##### Steps To Reproduce

1. ...
2. ...

**Comment by jacekkolasa** [comment]
fixed in https://github.com/netdata/netdata/pull/10122, thanks @stdedos!

**Comment by stdedos** [comment]
I am glad! I am wondering though; what was the issue? I only see a dependcy pull, and not actual code changes in the PR.

**Comment by jacekkolasa** [comment]
We moved dashboard to separate repo, the fix was in this pr: https://github.com/netdata/dashboard/pull/159 , and that was the specific fix: https://github.com/netdata/dashboard/pull/159/commits/e0557c37f2180f8052a925d918441dab877f4f34
It was a bug that happened during dashboard rewrite to react.js

**Comment by stdedos** [comment]
I see! Thank you for the disambiguation! :-D
