### ISSUE TITLE
Bash auto-completion for `./edit-config`

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#9010]
##### Feature idea summary
https://github.com/netdata/netdata/issues/8979#issuecomment-627830109

For `sudo ./edit-config he`<kbd>Tab</kbd> I am getting `health.d` (since directory exists), but nothing
For `sudo ./edit-config health.d/we`<kbd>Tab</kbd>

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
