### ISSUE TITLE
Alarms view more menu

### ISSUE THREAD

**Issue by Nirjonadda** [netdata/netdata#9011]
Alarms view more menu are not showing correctly from drop/down.

![ScreenShot00349](https://user-images.githubusercontent.com/6899856/81797811-8b292900-950f-11ea-82a9-400703920379.png)

**Comment by ilyam8** [comment]
@manos-saratsis take a look

**Comment by manos-saratsis** [comment]
@Nirjonadda thx for using Netdata Cloud! We will soon resolve this. Can you please share your browser and screen size to help us reproduce in the meanwhile?

**Comment by builat** [comment]
@Nirjonadda please, confirm that issue resolved for you

**Comment by manos-saratsis** [comment]
Closing this
