### ISSUE TITLE
Master-Slave Cloud Support MVP1

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#9013]
##### Feature idea summary
Implement Master-Slave (streamed nodes) support for Cloud in Agent in the scope defined by grooming as MVP1 (See details on #8909).

Communicate and test with cloud team.

Some time buffer was added to estimate due to expected on-the-go changes during implementation *(e.g. cloud or agent team figuring out original message format is not good during implementation)*.

Implementation steps:
- [ ] Exact message formats defined and agreed upon with cloud team and documentation updated accordingly
- [x] Master Sends slave list to cloud upon connection together with their respective GUIDs for clear node identification by cloud.
- [x] Claimed agent sends updates when new slave connects or existing slave disconnects
- [ ] If claimed agent connects or disconnects from it's master it has to inform cloud about it
- [x] Claimed node sends node GUID with all messages
- [ ] End-To-End Testing with cloud team

##### Expected behavior
Slave nodes visible to cloud.

**Comment by underhood** [comment]
This has been canceled and will be implemented in another way.

**Comment by chrisdukey** [comment]
Just wondering is this possible yet? I have a master with slaves connected and it would be very useful to be able to see the slaves in the cloud console

**Comment by stelfrag** [comment]
> Just wondering is this possible yet? I have a master with slaves connected and it would be very useful to be able to see the slaves in the cloud console

We are working on this
