### ISSUE TITLE
Avoid the initial `cd /etc/netdata` for `./edit-config`

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#9016]
##### Feature idea summary

https://github.com/netdata/netdata/issues/8979

```
cd /etc/netdata
sudo ./edit-config health.d/web_log.conf
```

Skip the `cd` and instead, for the full context of `./edit-config`, we `cd` to its parent directory (i.e. `/etc/netdata` in this case)

**Comment by prologic** [comment]
@stdedos Can you help me understand the problem we're solving here? I don't object to this btw just not sure what the benefit ie either way :)

**Comment by stdedos** [comment]
It feels a little wrong that, in order to run a script/program, I need to `cd` in its directory

**Comment by Ferroin** [comment]
I would tend to agree, `edit-config` only works right now if you're in `/etc/netdata` (or the equivalent for your install prefix), which feels kind of odd.

**Comment by stdedos** [comment]
It's not complicated ... just about 10 lines to clean this up, "safeguard it", and make the `cd` inside `edit-config`'s context.

The question is, who is not bored at this time 😛

**Comment by prologic** [comment]
@stdedos Looks like you just volunteered 🤣PR welcome!

**Comment by stdedos** [comment]
https://www.youtube.com/watch?v=nr9M7XF_CBg

**Comment by prologic** [comment]
🤣😂😂

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
