### ISSUE TITLE
service discovery: ci/cd

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#9020]
##### Feature idea summary

Part of #8925

There are no checks at all in the sd repo

> https://github.com/netdata/agent-service-discovery

We need to add following checks:

- build
- vet
- test
- format

In addition:

- docker publish workflow

##### Expected behavior

have proper ci/cd in the sd repo

**Comment by ilyam8** [comment]
i added [following checks]( https://github.com/netdata/agent-service-discovery/tree/master/.github/workflows)


- go vet
- go test
- go format
- yamllint
- golangci-lint

Having all those checks allows me continue working on it and have all PRs tested.

---

I am closing this issue, its main purpose was to add basic ci/cd.

There is no main pkg atm, nothing to build (`build` step will be added later, same for `docker publish`).

**Comment by ilyam8** [comment]
@prologic ^^

**Comment by prologic** [comment]
I saw :)
