### ISSUE TITLE
Button title for hover feedback

### ISSUE THREAD

**Issue by 0x11DFE** [netdata/netdata#9022]
##### Feature idea summary
While trying to hover between the button (options) on the top right corner,
I could not explain what are all the icon meaning so i thought adding a title html attribute could help.

##### Expected behavior
Adding a title attribute could help describing the icons.

##### Example
```html
<a href="#" title="Print"></a>
```
![preview](https://user-images.githubusercontent.com/43712252/81812729-d26ee400-9526-11ea-95e1-97ac3d0ff0d8.png)

**Comment by jacekkolasa** [comment]
thanks @0x11DFE , great idea, we'll implement it soon!

**Comment by Jiab77** [comment]
I was going to create an issue about the fact there is no more tooltips or indication about the meaning of the icon. Why this decision? It's a non-sense regarding the understanding of the UI.

**Comment by ilyam8** [comment]
That is fixed.
