### ISSUE TITLE
netdata alarm custom sender prints the variable name instead of its value

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9023]
##### Bug report summary

We have a webhook which we use to send the Grafana alerts into it, and now we want to use it to send the netdata alerts as well, I can send the alerts in the custom section of the `health_alarm_notify.conf` file, but it doesn't show the contents of the variable files I've used in it:
![image](https://user-images.githubusercontent.com/7656049/81822080-eaa32b00-9547-11ea-8b8f-e233ce2f554f.png)

Here is the configuration:
```
for phone in ${to}; do
     httpcode=$(docurl --location \
                    --request POST \
                    'https://grafamatrix.apps.x.y.z/send/!KqfmcjsqalzkzqPvSj:a.b' \
                    --header 'Content-Type: application/json' \
				    --data-raw '{
                        "evalMatches":[
                          {
                            "value":1,
                            "metric":"Count",
                            "tags":{}
                          }
                        ],
                        "imageUrl":"${images_base_url}/images/banner-icon-144x144.png",
                        "message":"${info}",
                        "orgId":1,
                        "panelId":2,
                        "ruleId":1,
                        "ruleName":"Panel Title alert",
                        "ruleUrl":"http://localhost:3000/d/hZ7BuVbWz/test-dashboard?fullscreen\u0026edit\u0026tab=alert\u0026panelId=2\u0026orgId=1",
                        "state":"alerting",
                        "tags":{
                          "tag name":"tag value"
                        },
                        "title":"[Alerting] Netdata on "
                        }'\
      )
```

##### Netdata version

 v 1.22.0

##### Component Name

health.d

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

Is the variable `$images_base_url` exported for the whole environment? 
Another doubt, please, can you run the command `shell-check` in the file that has this script? After to copy it and run in my local machine, I got errors like:

```
for phone in ${to}; do
^-- SC1073: Couldn't parse this for loop. Fix to allow more checks.
                    ^-- SC1061: Couldn't find 'done' for this 'do'.
```

and

```
In aa line 6:
                                    --data-raw '{
                                               ^-- SC2016: Expressions don't expand in single quotes, use double quotes for that.
```

These errors can explain possible problems that you are having.

Best regards!

**Comment by yasharne** [comment]
Thanks @thiagoftsm , your explanations helped me find the solution, I ended up creating a `payload` variable and pass it to the `--data-raw` to fix the problem
