### ISSUE TITLE
Can I monitoring sshfs process?

### ISSUE THREAD

**Issue by kozicpetar** [netdata/netdata#9024]
##### Question summary
On many linux servers I have set mounted drive over sshfs. I don't have any information about status service and that mount.

Because I'm using netdata to send metrics to prometheus I checked scrape metrics on url:
`hostname.com/api/v1/allmetrics?format=prometheus` but there is no one process for sshfs.

I tried to set apps_groups.conf and I added
```
sshfs: sshfs*
```
Also, I tried with
```
sshfs: sshfs
```
and
```
sshfs: *sshfs*
```
but without success.

If I try to list process with command:
`ps faxu | grep sshfs`

I can see process:
```
root     29519  0.0  0.1 985988  2860 ?        Ssl  May03   1:00 sshfs user@remote_server:/remote_location /local_mount_point -o rw,IdentityFile=/id.rsa,reconnect,StrictHostKeyChecking=no,ServerAliveInterval=30,ServerAliveCountMax=5,uid=1000,gid=1000,allow_other,dev,suid
```
I have systemd init for control of service.

##### OS / Environment
Ubuntu 18.04

##### Component Name
Netdata
`netdata v1.22.1`

##### Expected results

Expected is to see some sshfs process.

**Comment by vlvkobal** [comment]
Please do
```
cat /proc/29519/stat
cat /proc/29519/cmdline
```

**Comment by kozicpetar** [comment]
Yes, that is valid.

`cat /proc/29519/stat`

```
29519 (sshfs) S 1 29519 29519 0 -1 1077936192 26384 0 10811 0 1661 4805 0 0 20 0 12 0 777728009 1009512448 397 18446744073709551615 94559576526848 94559576599356 140737178333984 0 0 0 0 4096 16387 0 0 0 17 1 0 0 0 0 0 94559578699848 94559578704144 94559601217536 140737178340950 140737178341246 140737178341246 140737178341353 0
```

`cat /proc/29519/cmdline`

```
sshfs user@remote_server:/remote_location/local_mount_point,IdentityFile=/id.rsa,reconnect,StrictHostKeyChecking=no,ServerAliveInterval=30,ServerAliveCountMax=5,uid=1000,gid=1000,allow_other,dev,suid
```

**Comment by vlvkobal** [comment]
It's strange. Every configuration you mentioned should work. Did you restart Netdata after changing the `apps_groups.conf`?

**Comment by kozicpetar** [comment]
Yes, several times and I tried to set that on several servers, same configuration.

Do I need to enable something special in netdata.conf

This is my netdata.conf

```
[global]
OOM score = -1000
history = 0

[web]
default port = 19000

[health]
enabled = False

[plugin:apps]
update every = 1
```

and I tried to add
```
[plugins]
apps = yes
```

but same results.

**Comment by vlvkobal** [comment]
Could you show your application groups with the "Which dimensions to show" option set to `All`
![image](https://user-images.githubusercontent.com/22008543/81917423-d578db80-95dd-11ea-8276-a0055d79f6d0.png)

**Comment by vlvkobal** [comment]
Even better to do it for the `apps.processes` chart.

**Comment by kozicpetar** [comment]
Here it is:

![Screenshot 2020-05-14 at 11 30 41](https://user-images.githubusercontent.com/53332414/81918120-62b83200-95d6-11ea-8a6e-344396eadb9c.png)

**Comment by vlvkobal** [comment]
It looks like you have many more groups in the chart than are seen in the screenshot. Have you scrolled it and checked if there is an `sshfs` group?

Please check your `error.log`. Do you have something like this in the log?
```
2020-05-14 12:13:02: apps.plugin ERROR : MAIN : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf' (errno 2, No such file or directory)
2020-05-14 12:13:02: apps.plugin INFO  : MAIN : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
2020-05-14 12:13:02: apps.plugin INFO  : MAIN : Loaded config file '/usr/lib/netdata/conf.d/apps_groups.conf'
2020-05-14 12:13:02: apps.plugin INFO  : MAIN : started on pid 71303
2020-05-14 12:13:02: netdata INFO  : PLUGINSD[apps] : connected to '/usr/libexec/netdata/plugins.d/apps.plugin' running on pid 71303
```

**Comment by kozicpetar** [comment]
I scrolled and enlarge whole lists, there is no sshfs.

Yes, I have that error in error.log

**Comment by vlvkobal** [comment]
Please share that part of your log.

**Comment by kozicpetar** [comment]
Sorry, that error in log is old.

When I restar netdata I get this:

```
apps.plugin INFO  : MAIN : Loaded config file '/etc/netdata/apps_groups.conf'
apps.plugin INFO  : MAIN : started on pid 727
```

**Comment by vlvkobal** [comment]
I think this is the problem:
```
# -----------------------------------------------------------------------------
# ssh servers and clients

ssh: ssh* scp dropbear
```

Put the line with `sshfs` group before `ssh`.

**Comment by kozicpetar** [comment]
Great, it's works.
Thank you very much on fast repsonse @vlvkobal
