### ISSUE TITLE
Backend: How can I add "host tag" to my metrics?

### ISSUE THREAD

**Issue by MykhailoSobol** [netdata/netdata#9026]
##### Question summary

Hello! I enabled backend with config 
> [backend]
    type = prometheus_remote_write
    host tags = tagtag="test", tagtag2="test1"
    destination = xx.xx.xxxx:8428
    remote write URL path = /api/v1/write
    enabled = yes

I expected that my metrics will have two new tag(label)
`netdata_system_ram_MiB_average{chart="system.ram",dimension="buffers",family="ram",instance="name-001", tagtag="test", tagtag2="test1"}`
but I received:
`netdata_system_ram_MiB_average{chart="system.ram",dimension="buffers",family="ram",instance="name-001"}`

I checked host tags but host tags is OK

> ~# curl 127.0.0.1:19999/api/v1/info
	"host_labels": {
		"tagtag": "test",
		"tagtag2": "test1",
		"_os_name": "Ubuntu",
		"_os_version": "20.04 LTS (Focal Fossa)",
		"_kernel_version": "5.3.0-51-generic",
		"_system_cores": "12",
		"_system_cpu_freq": "3200000",
		"_system_ram_total": "67365351424",
		"_system_disk_space": "1997791232",
		"_architecture": "x86_64",
		"_virtualization": "none",
		"_container": "unknown",
		"_container_detection": "none",
		"_virt_detection": "systemd-detect-virt",
		"_is_master": "false"
	},

How can I add "host tag" to my metrics? or  I'm doing something wrong.

##### OS / Environment
os_name: "Ubuntu
os_version: 20.04 LTS (Focal Fossa)
kernel_version: 5.3.0-51-generic
netdata: 1.22.1
storage providers: victoriametrics v1.35.3

##### Expected results
How can I add "host tag" to my metrics?

**Comment by vlvkobal** [comment]
You can't. Your tags are in
```
netdata_host_tags_info{host_tag1="host_value1",host_tag2="host_value2"} 1 1589382397462
netdata_host_tags{host_tag1="host_value1",host_tag2="host_value2"} 1 1589382397462
```

There is a plan to implement labels on the metric level, but it's an epic project which involves a database redesign. Some discussions and links are in #6503, #7891.

**Comment by ilyam8** [comment]
@MykhailoSobol hi

it is not implemented, there is no way to add tags/labels to all metric sets atm

@vlvkobal correct me if i am wrong

**Comment by MykhailoSobol** [comment]
Thank you for the answer
