### ISSUE TITLE
apps.plugin service name support

### ISSUE THREAD

**Issue by mbarper** [netdata/netdata#9028]
##### Feature idea summary

This idea is for apps.plugin

I have a lot of troubles to monitor services based in a string that is searched in 

-  ps -e or /proc/PID/stat
-  in case of substring mode: /proc/PID/cmdline

This problems come when users run command containing that string configured in apps_groups.conf and then the processes number change, and values for KPIs as well.

My idea is add support to set the service name as string and then search for that service name in /proc/PID/cgroup file. 

##### Expected behavior

Lets use an example:

- In apps_groups.conf you can add something like(I will use pipeline as a special character to determine is a service name instead of asteriks or nothing for strings):

`mymagicservice: |systemd-timesyncd.service|`

- In the apps.plugin code you can search that string into /proc/PID/cgroup file to get the PID of the service and keep going as the plugin does from there:

```
#> cat /proc/$(pidof /lib/systemd/systemd-timesyncd)/cgroup 
11:freezer:/
10:cpu,cpuacct:/system.slice/systemd-timesyncd.service
9:memory:/system.slice/systemd-timesyncd.service
8:hugetlb:/
7:devices:/system.slice/systemd-timesyncd.service
6:cpuset:/
5:pids:/system.slice/systemd-timesyncd.service
4:perf_event:/
3:net_cls,net_prio:/
2:blkio:/system.slice/systemd-timesyncd.service
1:name=systemd:/system.slice/systemd-timesyncd.service
#>
```

As you can see in the line numbered as "1" you have the name and can get a match.

**Comment by mbarper** [comment]
If you agree with me about adding this feature I could try to do it myself but I have my C/C++ quite forgoten.

**Comment by dim08** [comment]
Hi there, thank you very much for your feedback and support! 
Since this issue is a deep change that may affect multiple new functionalities on the agent right nav bar, would you like to share with us a more concrete technical design before start coding? 
We will definitely encourage you to write a PR but let's first assess the wider impact.

**Comment by vlvkobal** [comment]
I think there are two things we should define before implementing the feature: parsing logic for `/proc/PID/cgroup` and configuration syntax. @mbarper please elaborate on your suggested design.

BTW
> /proc/[pid]/cgroup (since Linux 2.6.24) This file describes control groups to which the process with the corresponding PID belongs. The displayed information __differs__ for cgroups version 1 and version 2 hierarchies.

>1. For cgroups version 1 hierarchies, this field contains a unique hierarchy ID number that can be matched to a hierarchy ID in /proc/cgroups.  For the cgroups version 2 hierarchy, this field contains the value 0.

Is the ID number always 1 for `systemd`? How does it look in the cgroups version 2?

**Comment by JMUsero** [comment]
according to https://man7.org/linux/man-pages/man7/cgroups.7.html

>         /proc/[pid]/cgroup (since Linux 2.6.24)
>               This file describes control groups to which the process with
>               the corresponding PID belongs.  The displayed information dif‐
>               fers for cgroups version 1 and version 2 hierarchies.
> 
>               For each cgroup hierarchy of which the process is a member,
>               there is one entry containing three colon-separated fields:
> 
>                   hierarchy-ID:controller-list:cgroup-path
> 
>               For example:
> 
>                   5:cpuacct,cpu,cpuset:/daemons
> 
>               The colon-separated fields are, from left to right:
> 
>               1. For cgroups version 1 hierarchies, this field contains a
>                  unique hierarchy ID number that can be matched to a hierar‐
>                  chy ID in /proc/cgroups.  For the cgroups version 2 hierar‐
>                  chy, this field contains the value 0.
> 
>               2. For cgroups version 1 hierarchies, this field contains a
>                  comma-separated list of the controllers bound to the hier‐
>                  archy.  For the cgroups version 2 hierarchy, this field is
>                  empty.
> 
>               3. This field contains the pathname of the control group in
>                  the hierarchy to which the process belongs.  This pathname
>                  is relative to the mount point of the hierarchy.

**Comment by OdysLam** [comment]
@mbarper Thanks for the suggestion and welcome to our community! Members such as yourself are the core of every open source project, so a big thank you is in order!

Can't wait to work with you towards an improvement 👍

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forum and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
