### ISSUE TITLE
Dark theme for app.netdata.cloud

### ISSUE THREAD

**Issue by 2-man** [netdata/netdata#9040]
Please, make dark version for app.netdata.cloud
My eyes 🔥🔥

Thank you 💚

**Comment by manos-saratsis** [comment]
@2-man on it! Please give us a month and stay tuned :)

**Comment by 2-man** [comment]
Next month with sunglasses 😎

**Comment by jaydio** [comment]
Hey guys, any update on this? :dark_sunglasses:

**Comment by manos-saratsis** [comment]
@jaydio It's prioritized and mid September it will be out.

**Comment by manos-saratsis** [comment]
@jaydio @2-man no more sunglasses, go to app.netdata.cloud and Profile/Settings. Soon it will be the default one after we fix some bugs

**Comment by jaydio** [comment]
@manos-saratsis now we're talking, you guys rock! ;-)

**Comment by 2-man** [comment]
Oh @manos-saratsis you're saving my eyes, thank you!
