### ISSUE TITLE
monitor number of open tables - table cache usage

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#9041]
##### Feature idea summary
For monitoring MySQL, It would be helpful to see not only query cache, but also table open cache in mysql charts.
There are 3 parameters that are easy to get from command line, but would be helpful to see in charts, namely:

- open_tables (this is table cache utilization, can be checked with `show global status like 'open_tables'`)
- opened_tables (this is counter of open tables, can be checked with `show global status like 'opened_tables'`)
- table_open_cache (this is user-defined table cache size, can be checked as `select @@table_open_cache`)

##### Expected behavior
It would be handy to display `table_open_cache` and `open_tables` on one chart.
`opened_tables` is a counter increasing with opening each and every table that is not currently cached, so it grows all the time and can be significantly higher then `opened_tables` and `open_tables`, so it should be displayed separately.

**Comment by thiagoftsm** [comment]
Hi @ekexcello ,

I ran the queries now on a local MariaDB and I verified that the queries are working fine on MariaDB  `10.4.13`, but I am many years without to work directly with MySQL, so I have few doubts:

1 - Is there a minimum version that these queries will run?
2 - Would make sense to convert the first two proposed charts `open_tables` and `opened_tables` as dimensions of one chart?

Best regards!

**Comment by ilyam8** [comment]
@ekexcello 👋 

if it is possible it would be very helpful to see those queries result.

**Comment by thiagoftsm** [comment]
@ilyam8 this is the result on MariaDB 10.5.4:

```
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7
Server version: 10.5.4-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [mysql]> show global status like 'open_tables';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| Open_tables   | 30    |
+---------------+-------+
1 row in set (0.000 sec)

MariaDB [mysql]> show global status like 'opened_tables';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| Opened_tables | 36    |
+---------------+-------+
1 row in set (0.000 sec)

MariaDB [mysql]> select @@table_open_cache;
+--------------------+
| @@table_open_cache |
+--------------------+
|               2000 |
+--------------------+
1 row in set (0.000 sec)
```

**Comment by ilyam8** [comment]
> 2 - Would make sense to convert the first two proposed charts open_tables and opened_tables as dimensions of one chart?

I think no, `opened_tables` is counter (we use it for rate), `open_tables` is gauge.

**Comment by ekexcello** [comment]
Hello.

Sorry for the delay. As for minimal version - unfortunately, have no information about it. The oldest server we have is 10.3.22, these parameters already present. In fact, they should be present in mysql 5.x, these settings are very basic and common subject for tuning. 
Output on one of our servers looks like:
```
Your MariaDB connection id is 62986807
Server version: 10.4.13-MariaDB-log Source distribution

MariaDB [(none)]> show global status like 'open_tables';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| Open_tables   | 93748 |
+---------------+-------+

MariaDB [(none)]> show global status like 'opened_tables';
+---------------+----------+
| Variable_name | Value    |
+---------------+----------+
| Opened_tables | 13580726 |
+---------------+----------+

MariaDB [(none)]> select @@table_open_cache;
+--------------------+
| @@table_open_cache |
+--------------------+
|             500000 |
+--------------------+
```

and on another server...

```
MariaDB [(none)]> show global status like 'open_tables'; select @@table_open_cache;
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| Open_tables   | 500000 |
+---------------+--------+

+--------------------+
| @@table_open_cache |
+--------------------+
|             500000 |
+--------------------+
```

From this example it's clear that a) `opened_tables` can have significantly higher value comparing to `open_tables` as `opened_tables` is a counter and b) `table_open_cache` value is upper limit for `open_tables` value. Thus, having  `table_open_cache` on same chart with `open_tables` is handy while `opened_tables` should be separate chart, it can't be combined.

**Comment by ilyam8** [comment]
> show global status like 'open_tables';
> show global status like 'opened_tables';

This data present in `SHOW GLOBAL STATUS` (we do this query), we dont need `show global status like ...` queries. We need just to use it.
