### ISSUE TITLE
Securing the access.

### ISSUE THREAD

**Issue by PrakashLakhara** [netdata/netdata#9042]
How can we make it secure. Accessing with user name and password ?

**Comment by ilyam8** [comment]
Hi @PrakashLakhara 

There is nothing built-in for securing access with username/password

We suggest to run Nedata behind web server/proxy if you need username/password auth.

See

> https://learn.netdata.cloud/docs/agent/running-behind-nginx

---

related #3501

---

@dim08 take a look, probably we need to rethink it and implement at some point
