### ISSUE TITLE
Disabling cloud still performs requests to app.netdata.cloud

### ISSUE THREAD

**Issue by xPaw** [netdata/netdata#9043]
##### Bug report summary

I put `[global] enabled = false` in `/var/lib/netdata/cloud.d/cloud.conf`

Info api response:
```
	"cloud-enabled": false,
	"cloud-available": false,
	"agent-claimed": false,
	"aclk-available": false
```

##### OS / Environment

```
Debian 10
```

##### Netdata version

netdata v1.22.1-17-nightly

##### Component Name

Web/dashboard

##### Steps To Reproduce

1. Disable cloud
2. Open the dashboard and monitor requests in devtools to `sso/sign-in`

##### Expected behavior

When cloud is disabled, I expect netdata not to perform any external requests on the dashboard.

**Comment by jacekkolasa** [comment]
@xPaw currently `cloud-enabled` setting is related more to Agent-Cloud connection (not Browser-Cloud), so we don't display Call To Actions to Cloud, notifications about insufficient dependencies or sign-in button. But we load the iframes, in case users sign in on different Agent, to have the Visited Nodes list. We don't store any information when you're not logged in, but if you want to prevent those calls, could you for example set `cloud base url = https://example.com`?

**Comment by xPaw** [comment]
>  could you for example set cloud base url = https://example.com?

That does work, but feels like a hack, really.

The same issue happens with the registry, setting it to disabled still performs requests, and the only way to avoid that is to change the url.

**Comment by jacekkolasa** [comment]
I agree, it's a hack, i'm giving this hint because we just don't have that feature yet... :( `"cloud-enabled": false` serves a little different purpose.

Another option would be setting `respect do not track policy = yes` in `/etc/netdata/netdata.conf` - this way no call to cloud is made, but you need to configure browser to add DNT flag. This is how it works in old Dashboard (accessible still with `/old` suffix). In new dashboard it doesn't work now because of a bug, but it will be fixed very soon (https://github.com/netdata/netdata/issues/9036)

**Comment by xPaw** [comment]
The ideal solution I see is when cloud and registry are set to disabled, actually disable anything related to these features.

**Comment by jacekkolasa** [comment]
I agree that we should allow disabling it completely, but for this we would need to add new flags. CC @cakrit @dim08

**Comment by amoss** [comment]
I think that is the meaning of the `cloud-enabled` flag. If it is set to false then it means the user explicitly switched off cloud support, either the way that @xPaw has described or by passing `--disable-cloud` to the installer. In either case there should be no cloud related navbars shown and no requests to sso. 

I think that the other meaning that @jacekkolasa is thinking of is the `aclk-enabled` flag which indicates if the cloud dependencies failed to build, but the user did not indicate that they wanted to remove the cloud features.

**Comment by jacekkolasa** [comment]
@amoss we have decided with @manos-saratsis to always try to check if user is signed in - only to have the possibility to see Visited Nodes. So it's a feature completely unrelated to Agent-Cloud Link. We disable sign-in button in this case but leave the possibility for SSO open if you've signed in on other Agent.

**Comment by manos-saratsis** [comment]
@jacekkolasa I think @xPaw and @amoss are right. If a user has `[global] enabled = false` they shouldn't see even visited nodes served by the Cloud unless they setup their private registry. I'll add a separate issue to track this.

**Comment by cakrit** [comment]
Guys, let's please fix this quickly, it's clearly a bug from a user's perspective, regardless of what was discussed internally. No calls whatsoever to the cloud for iframes or anything else with cloud disabled. Local registry entries can be shown just with the local "off-line" UI.

**Comment by xPaw** [comment]
I did a clean reinstall and this is still an issue.

**Comment by amoss** [comment]
@manos-saratsis / @jacekkolasa What is happening with this bug - is there a plan to fix it?

**Comment by jacekkolasa** [comment]
@amoss we should have time in next week to fix few issues in Agent Dashboard, so we can definitely work on this one.

**Comment by amoss** [comment]
That sounds great. We also have some problems that are affecting the Network Viewer that are very important but we can talk about those separately.

**Comment by jacekkolasa** [comment]
@xPaw thanks for your help and reminders, the fix will be in nightlies in several hours, and in next stable release.
