### ISSUE TITLE
Azure Monitor export support

### ISSUE THREAD

**Issue by zack-shoylev** [netdata/netdata#9050]
##### Feature idea summary
It would be great if it was possible (and there was a guide on how) to export Netdata metrics to [Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/overview).

##### Expected behavior
Azure Monitor uses their own custom restful APIs to ingest metrics - see https://docs.microsoft.com/en-us/rest/api/monitor/metrics%20(data%20plane)/create
It might be possible to directly dump json into it; or alternatively go through an intermediary like Prometheus and then export to Azure Monitor (just an example, not sure if that works).

##### Additional Information
This is based on a user request.

**Comment by ilyam8** [comment]
Closing this issue due to the low interest in this feautre.

If there is anybody who is interesed in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.
