### ISSUE TITLE
Bundle missing in ClearLinux* OS: ERROR when running one line installation script

### ISSUE THREAD

**Issue by thoggs** [netdata/netdata#9051]
As I title, I noticed that, when trying to run the installation script using the --stable-channel flag, on Clear Linux * OS (Server), the script returns an error, claiming that lib libuuid-devel (package uuid is speaking) -dev).

**I solved the problem by installing:**
=> devpkg-util-linux bundle 

**ERROR:** netdata failed to build...
**OS:** Clear Linux* OS - Server
**Netdata v1.22.1**

**Comment by Ferroin** [comment]
@thoggs Thank you for reporting this! I'll have a PR up with a fix shortly, and it should hopefully be in the nightly builds within the next few days.

**Comment by thoggs** [comment]
> @thoggs Thank you for reporting this! I'll have a PR up with a fix shortly, and it should hopefully be in the nightly builds within the next few days.

Thank you very much for your attention.
I am also a developer, and I understand about Shell Script, maybe I can help the project to progress even more...

**Comment by thoggs** [comment]
Hello,
Tested, problem solved...

![Captura de Tela 2020-05-26 às 01 15 35](https://user-images.githubusercontent.com/43221193/82861328-ac681d00-9ef2-11ea-91a3-52cb147c70c6.png)
