### ISSUE TITLE
Dashboard - Incorrect links in Replicated Nodes menu

### ISSUE THREAD

**Issue by projik** [netdata/netdata#9056]
##### Bug report summary
The 'Replicated Nodes' menu sets the URL for the 'Master' node to the URL of whichever node you are viewing. This means that:

1.  You can't return to the dashboard of the master node by clicking on it in the menu
2. You get an error if you try to click on another node in the menu.

##### OS / Environment

```
Linux ip-172-31-6-252 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.6 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.6 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

 netdata v1.22.1-33-nightly

##### Component Name

web component (dashboard)

##### Steps To Reproduce
![netdata-dashboard-bug](https://user-images.githubusercontent.com/911823/82021236-de48da80-96cd-11ea-8c8a-22fb053da788.gif)

1. Stream one or more metadata slaves to a master Netdata node
2. Open the dashboard of the master node
3. Click on the hamburger icon to open the menu.
4. Click on a menu link for one of the slave nodes
5. Click on the menu link for the master node - (links to the node you are already on)
6. Click on the link of another slave node - (you get an error - Nesting of hosts is not allowed.)

##### Expected behavior

Menu items should successfully link to the relevant node dashboard.

**Comment by thiagoftsm** [comment]
Hi @projik ,

It is possible your problem has relationship with space on hostname, could you access these hosts on old dashboard? @jacekkolasa we had a problem like this before, do you remember whether we brought a fix?

Best regards!

**Comment by projik** [comment]
Hi @thiagoftsm,

I replaced the spaces in the hostnames with dashes and that has fixed the problem.

I don't know if there was a problem on the old dashboard, I only started the streaming set-up in the last 24 hours.

David

**Comment by thiagoftsm** [comment]
Thank you for the feed back @projik !
When I heard about this problem before, it was with the old dashboard, probably Netdata did not fix this problem yet.
I am glad that you could fix the problems in your side. I will keep this issue open, for we remember to fix this in a near future.

best regards!

**Comment by jacekkolasa** [comment]
@projik you're right, there is a bug, thanks for submitting the issue! I think the bug was also present in old dashboard (<1.22). I've fixed this, it should land soon in nightly build
