### ISSUE TITLE
Permit to change installation directory and user

### ISSUE THREAD

**Issue by Hierosme** [netdata/netdata#9057]
It look impossible to change the installation directory, when using kickstart script, and the kick start script require root acces for create user/group directory.

If i can change the user/group , and installation directory then we'll can simulate netdata installation.
(still have systemd , but will be happy without)

#### Feature idea summary
**--user**=the username to user
**--group**=the group name to use
**--prefix**=the directory where install netdata

##### Expected behavior
The goal is simply install netdata in a controled environement for permit installation tests.
Actually we devellope a ansible-role for netdata , and all that static value make our job almost impossible.

Regards

**Comment by thiagoftsm** [comment]
Hi @Hierosme ,

Netdata allows to use `--install /directory` to specify a destination, on the other hand, for user and group, I think we do not have this option. @Ferroin and @prologic can you confirm this? If we do not have, I have to say that I liked @Hierosme suggestion we could think more about to bring these new options.

Thank you for your suggestion @Hierosme !

**Comment by Hierosme** [comment]
May be that the kickstart-static64.sh, but --install look to be a unknow option

```
"cmd": [
        "bash",
        "kickstart-static64.sh",
        "--local-files",
        "/tmp/prometheus_exporter/netdata-v1.22.1.gz.run",
        "/tmp/prometheus_exporter/sha256sums.txt",
        "--dont-wait",
        "--non-interactive",
        "--dont-start-it",
        "--stable-channel",
        "--disable-telemetry",
        "--install",
        "/opt/lulu"
    ],
STDERR:

Unknown option '--install' or invalid number of arguments. Please check the README for the available arguments of kickstart-static64.sh and try again
```
Our goal is to simulate massive installation of netdata on our DEV venv, without compilation, and without root access. (just test files download and setting templates)

We have push to later the **systemd**  but in case a option like **--no-install-systemd-service** will help.

Thanks for you assistance.

**Comment by Ferroin** [comment]
As of right now, there unfortunately no easy way we can support either of these for our static build. There are a number of default config options that are determined at compile time based on the user and prefix that Netdata is being configured to use.

**Comment by Hierosme** [comment]
Yep understand the hard requirement for static build.

Our work arround is to make our devellopemnt and tests inside a LXE container.
In any way thanks to have take a look and i hope it will help to improve netdata distribution design.

By the way in that case **/opt** is the perfect location.

Regards

**Comment by prologic** [comment]
Assuming this was about `kickstart-static64.sh` I am closing this as "won't fix". As @Ferroin stated this is rather hard to do realistically and we _have_ to make certain assumptions with our statically built agent that we distirbute via `kickstart-static64.sh` so we can guarentee things work correctly.
