### ISSUE TITLE
system.ram High Utilization Warnings

### ISSUE THREAD

**Issue by Snuggle** [netdata/netdata#9059]
##### Bug report summary
I keep getting a warning/critical alarm for the `system.ram` module, which in turn is sending critical notifications about my server to my phone.

My VM server has a high amount of buffers usage but for some reason this is being taken into account in the `system.ram` alarm notification. Shouldn't buffers be counted in the variable `$used_ram_to_ignore` since they're just a disk cache and can be dropped in an instant?

#### Alarm about system.ram usage too high
![image](https://user-images.githubusercontent.com/26250962/82058422-a4bba380-96bc-11ea-9f19-3d483d899478.png)
#### The `system overview - ram` section shows almost no memory free.
![image](https://user-images.githubusercontent.com/26250962/82058485-bac96400-96bc-11ea-9005-871a3616663d.png)
#### The `memory - system` section shows over 20 GiB of memory is actually available.
![image](https://user-images.githubusercontent.com/26250962/82058599-ddf41380-96bc-11ea-90f1-1863f090476c.png)
#### In addition, `free -mh` shows over 20 GiB of memory is available and 20 GiB is currently used in buffers/cache.
```
snuggle in ~ 
❯ free -mh
              total        used        free      shared  buff/cache   available
Mem:           46Gi        26Gi       554Mi        56Mi        20Gi        20Gi
Swap:          23Gi        30Mi        23Gi
```

##### OS / Environment
```
snuggle on hug in ~ 
❯ neofetch
           .MMM..:MMMMMMM                  snuggle@hug 
          MMMMMMMMMMMMMMMMMM               ----------- 
          MMMMMMMMMMMMMMMMMMMM.            OS: Red Hat Enterprise Linux 8.2 (Ootpa) x86_64 
         MMMMMMMMMMMMMMMMMMMMMM            Host: Z10PE-D8 WS 
        ,MMMMMMMMMMMMMMMMMMMMMM:           Kernel: 4.18.0-193.el8.x86_64 
        MMMMMMMMMMMMMMMMMMMMMMMM           Uptime: 3 days, 23 hours, 44 mins 
  .MMMM'  MMMMMMMMMMMMMMMMMMMMMM           Packages: 972 (rpm) 
 MMMMMM    `MMMMMMMMMMMMMMMMMMMM.          Shell: fish 3.1.0 
MMMMMMMM      MMMMMMMMMMMMMMMMMM .         Resolution: 1024x768 
MMMMMMMMM.       `MMMMMMMMMMMMM' MM.       Terminal: /dev/pts/4 
MMMMMMMMMMM.                     MMMM      CPU: Intel Haswell Xeon E5-2630 v3 (32) @ 3.200GHz 
`MMMMMMMMMMMMM.                 ,MMMMM.    GPU: 09:00.0 ASPEED Technology, Inc. ASPEED Graphics Family 
 `MMMMMMMMMMMMMMMMM.          ,MMMMMMMM.   Memory: 26709MiB / 48008MiB 
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                           
         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                            
            `MMMMMMMMMMMMMMMMMMMMMMMM:
                ``MMMMMMMMMMMMMMMMM'


```

```
snuggle in ~ 
❯ uname -a; grep -Hv "^#" /etc/*release
Linux hug 4.18.0-193.el8.x86_64 #1 SMP Fri Mar 27 14:35:58 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux"
/etc/os-release:VERSION="8.2 (Ootpa)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VERSION_ID="8.2"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
/etc/os-release:HOME_URL="https://www.redhat.com/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
/etc/redhat-release:Red Hat Enterprise Linux release 8.2 (Ootpa)
/etc/system-release:Red Hat Enterprise Linux release 8.2 (Ootpa)
```

##### Netdata version

 (Installed using the Kickstart script on RHEL 8.)

##### Component Name
collectors, proc.plugin, system.ram

##### Steps To Reproduce

1. Run a RHEL 8 server with high buffers memory usage.
2. Get warning/critical alarms about abnormally high memory usage.

##### Expected behavior

I would have expected netdata to ignore the amount of buffered memory in use with alarms, since it is a cache that can be dropped within a moment.

In fact under memory.system, the available memory usage is over 20 GB of available memory. This section knows that there isn't an issue. I shouldn't be given a critical alarm constantly for this.

**Comment by thiagoftsm** [comment]
Hi @Snuggle ,

I understand your point of view that buffers could be ignored inside the formula, but considering that buffers are inside the memory, the current formula is not wrong and I think to keep the buffers like it is right now, it is the most safety approach.

Best regards!

**Comment by mfundul** [comment]
While it is unusual to have high buffer usage (usually it's high cache usage), as long as the buffers are not dirty and they are accounted for as "available" memory, which they are in this case, I tend to agree that this is a bug. What do you think @Ferroin ?

**Comment by Snuggle** [comment]
@mfundul Any idea what kind of scenarios could cause high buffer usage? For some reason it seems that QEMU/KVM disk caching is showing up as buffer usage on my RHEL system.

**Comment by mfundul** [comment]
> 
> 
> @mfundul Any idea what kind of scenarios could cause high buffer usage? For some reason it seems that QEMU/KVM disk caching is showing up as buffer usage on my RHEL system.

Not sure, maybe qemu opened a block device directly instead of opening an image file? This would be one scenario I can think of that can allocated "buffered" memory instead of "cached".

**Comment by amoss** [comment]
The charts seems to be inconsistent. Consistent approaches for Netdata are:
1. The memory in the buffers is free/avail and it should count against the alarm
2. The memory in the buffers is not free/avail and it should not count against the alarm.

I'll take a look at the code in the collector and see what we are doing. @mfundul may be on the right track if we are tracking the clean/dirty state of the memory differently in different parts of the code.

**Comment by Snuggle** [comment]
@mfundul Is correct, though. I have qemu opening two block devices directly.

**Comment by amoss** [comment]
I think the alarm is not tracking the most useful values, inside the collector we do this:
```
    unsigned long long MemUsed = MemTotal - MemFree - MemCached - Buffers;
```
This is not strictly correct as @mfundul mentioned above. Some of the cached memory may be dirty in which case it should be considered used, but we can't see that detail from the `/proc` interface. There is a lot more detail about why this is inaccuracte here: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773

> It is wrong because Cached includes memory that is not freeable as page
> cache, for example shared memory segments, tmpfs, and ramfs, and it does
> not include reclaimable slab memory, which can take up a large fraction
>of system memory on mostly idle systems with lots of files.

The kernel gives us the `available` number to overcome this. It seems that the alarm is being calculated on the less useful values, I suggest that we change the alarm to track:
```
($total - $available) * 100 / $total
```
It would then be triggered when the kernel's estimate of the level of available RAM drops, instead of the our local estimate of which RAM is in use.

**Comment by amoss** [comment]
@thiagoftsm / @stelfrag Can you look at the PR to change the alarm definitions. The original definition of the alarm was wrong in the way that @Snuggle reported. We cannot assume that all of the memory in use in buffers is in use.

With the change please consider if the two alarms are now redundant: do we need to track our estimate of used memory if we have an alarm triggered by the kernel's estimate of available memory?

**Comment by thiagoftsm** [comment]
@amoss I made a request `https://localhost:19999/host/zeus/api/v1/alarm_variables?chart=system.ram` to check both alarms. I agree with two things that I could see on your PR:

1 - The math for `ram_in_use` looks more accurate now.
2 - I also agree that users will receive two alarms, one saying that `ram available` is less than 10% and `ram in use` is more than 90%. They won't receive in the exactly same time, because warns have difference levels. Considering both alarms we have inside this file, I would comment the alarm `ram_available` and move forward only with `ram_in_use`.

**Comment by amoss** [comment]
Hello. @thiagoftsm you are supposed to be on vacation, please stop working :)

I added a link to the PR on https://github.com/netdata/netdata/issues/3381 as it should fix the problem there as well.

I would recommend keeping `ram_available` and removing `ram_in_use` as the kernel estimate will be more accurate than our estimate.

**Comment by thiagoftsm** [comment]
The final result will be the same, @stelfrag , @ilyam8 , @Ferroin and @vlvkobal you are also reviewers on this, what do you think?

**Comment by amoss** [comment]
No, the final result will be different. The calculation on `ram_in_use` assumes that all memory in cache and buffers is available. This is not accurate, as explained in the thread that I linked to above. The `ram_available` relies on the kernel to do the calculation and it has a more accurate view of the system.

**Comment by Snuggle** [comment]
It doesn't seem as if https://github.com/netdata/netdata/pull/8913 from https://github.com/netdata/netdata/issues/3381 has fixed this issue as my memory usage is still reported as much higher than it actually is?

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/26250962/121712350-931d1900-cad3-11eb-97b9-529f3aeaa672.png">
<img width="872" alt="image" src="https://user-images.githubusercontent.com/26250962/121712475-af20ba80-cad3-11eb-9fbc-75e978e168b7.png">
<img width="486" alt="image" src="https://user-images.githubusercontent.com/26250962/121712508-b778f580-cad3-11eb-8ce0-ebc5fd166d0a.png">
