### ISSUE TITLE
[macOS / Homebrew] This agent was built without the dependencies for Cloud and cannot be claimed

### ISSUE THREAD

**Issue by breenjoe** [netdata/netdata#9061]
##### Bug report summary
Installed the latest version with brew upgrade netdata
Then tried to claim the node using the following:
`sudo netdata-claim.sh -token=tokenkey -rooms=room-key -url=https://app.netdata.cloud`
The following message is returned:

> This agent was built without the dependencies for Cloud and cannot be claimed

##### OS / Environment
10.15.4 (19E287)

Place the output from the command in the code section below.  
 -->
```
This agent was built without the dependencies for Cloud and cannot be claimed
```

##### Steps To Reproduce

1. ...
2. ...

**Comment by ilyam8** [comment]
hi @breenjoe 

> Installed the latest version with brew upgrade netdata

unfortunately we dont maintain Netdata brew package

cc @prologic @Ferroin

**Comment by daneroo** [comment]
If anyone knows how to contact the brew formula maintainer, please leave any hints here. Thanks

**Comment by prologic** [comment]
It can be. I've been in touch with the maintainer already; but I'll put up a PR to fix this myself this time. Stay tuned, I'll try to get this done today.

**Comment by eXcalibre** [comment]
That’s great Prologic James. Thanks and looking forward to the post.

**Comment by bbusschots** [comment]
I am getting the same error but on CentOS 6 using the official installer script!

**Comment by vladsol** [comment]
> I am getting the same error but on CentOS 6 using the official installer script!

Yep.

**Comment by sean-perryman** [comment]
I am adding my +1 on the official install script not working for my running CentOS 6.

**Comment by prologic** [comment]
__Please note:__ This issue only affects Homebrew users on macOS. This should not be affecting other systems; if you are experiencing similar problems on other systems please either open a new ticket with details or briefly comment here what's going on with your installation. Unless you are installing Netdata explicitly with `--disable-cloud` you should not be seeing this on systems like CentOS. AFAIK we only have an issue with building NetData Cloud support or the Agent on Ubuntu 14.04 (#8905)

**Comment by prologic** [comment]
I've just realized circling back on this that updating the Formulae in homebrew-core is probably going to be quite hard as we unfortunately bundle libmosquitto and libwebsockets at this time because we need special patches for the ACLK. I _might_ have to provide a different Homebrew Formulae here as a Tap. cc @Ferroin

**Comment by vladsol** [comment]
> This issue only affects Homebrew users on macOS
Well... As i said, on CentOS 6, without --disable-cloud, i got the same error "This agent was built without the dependencies for Cloud and cannot be claimed".
Nothing special. Installed with bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel --disable-telemetry

**Comment by prologic** [comment]
For CentOS 6.x specifica issues related to Netdata Cloud and claiming or lack of support for please see #9152

**Comment by xxdesmus** [comment]
Debian 10 -- official installer script, same issue. Additionally, the updater says I am up to date.
```
bash /usr/libexec/netdata/netdata-updater.sh
Wed 27 May 2020 03:42:22 PM CEST : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Wed 27 May 2020 03:42:22 PM CEST : INFO:  Current Version: 001022001143
Wed 27 May 2020 03:42:22 PM CEST : INFO:  Latest Version: 001022001143
Wed 27 May 2020 03:42:22 PM CEST : INFO:  Newest version (current=001022001143 >= latest=001022001143) is already installed
```

**Comment by unixfox** [comment]
I also encounter the same error when installing netdata from the official repositories of ArchLinux: https://www.archlinux.org/packages/community/x86_64/netdata/

**Comment by jonasrejman** [comment]
Hello. Discovered net data recently - very, very impressive.

I get the cloud to work on centOS in VM no problem.

However, I have the same issue on MacOS with home-brew ... This agent was build .... etc.
I would like to use netdata to monitor about a dozen MacOS workstations.

Is there any update on how to link the agent to the cloud on MacOS?

As an alternative to homebrew, the documentation describes a way to build from sources.
This is however seems a bit over my head.

Any hints in the right direction are very much appreciated!

J

**Comment by prologic** [comment]
Unfortunately we haven't been able to get back to this yet. The way the Formula is built in Homebrew-core missed two important dependencies for the ACLK to work correctly. Mostly libwebsockets and our custom libmosquitto fork.

@rickard-von-essen / @issyl0 Can either of you help us out here with this Formula? I'd be more than happy to discuss and review any PRs.

**Comment by rickard-von-essen** [comment]
I can have a look. 

> I've just realized circling back on this that updating the Formulae in homebrew-core is probably going to be quite hard as we unfortunately bundle libmosquitto and libwebsockets at this time because we need special patches for the ACLK. 

Can you elaborate on this? How is this bundled, where are the patch etc.

**Comment by prologic** [comment]
> Can you elaborate on this? How is this bundled, where are the patch etc.

The patches for libmosquitto are found in [this fork](https://github.com/netdata/mosquitto). We currently cannot push these upstream at this time. cc @amoss  for details.

lihwebsockets is stock-standard and taken from upstream -- But we "vendor" the source in the installer `netdata-installer.sh` and pin the version/checksum in `./packaging/libwebsockets.*`:

```#!sh
$ cat packaging/libwebsockets.*
166d6e17cab64bfc10c2a71799c298284540a1fa63f6ea3de5caccb34502243c  v3.2.2.tar.gz
3.2.2
```

Hope this help!

**Comment by Ferroin** [comment]
> > Can you elaborate on this? How is this bundled, where are the patch etc.
> 
> The patches for libmosquitto are found in [this fork](https://github.com/netdata/mosquitto). We currently cannot push these upstream at this time. cc @amoss for details.
> 
> lihwebsockets is stock-standard and taken from upstream -- But we "vendor" the source in the installer `netdata-installer.sh` and pin the version/checksum in `./packaging/libwebsockets.*`:
> 
> ```
> $ cat packaging/libwebsockets.*
> 166d6e17cab64bfc10c2a71799c298284540a1fa63f6ea3de5caccb34502243c  v3.2.2.tar.gz
> 3.2.2
> ```
> 
> Hope this help!

Also, see the various `bundle-*.sh` scripts under `packaging/` to see how we handle bundling this stuff in our own packaging code (for DEB and RPM packages). The ones for LWS and mosquitto are run before the rest of the netdata build, while the dashboard one is run afterwards. In theory these could be directly used by the Homebrew code to pull things in correctly.

**Comment by prologic** [comment]
@rickard-von-essen Sorry I've been away on vacation and just got back. Are you still interested/willing to help us with this? LMK :)

**Comment by rickard-von-essen** [comment]
@prologic i did a very small start on this but I'm on vacation so I probably won't work on this for at least a month or so.

**Comment by AussieJD** [comment]
+1 on the "This agent was built without the dependencies for Cloud and cannot be claimed ".

This is doing my head in a little, as I had previously added the same mac to a war room in the cloud [ there have been many uninstalls and re-installs since ] ... not sure how I actually did that now....

Novice netdata user, but long term OSX / UNIX user.... so happy to help test it that helps at all....

- jd

**Comment by genevera** [comment]
@prologic still not working as of 13 Aug 2020

**Comment by prologic** [comment]
This is still in our backlog and is unfortunately not trivial to support the current form of the brew formulae on core. Building from source however should work on macOS (_many of us do dev on macOS for example_), you could try this method as a work-around in the meantime? Thanks for your patience!

**Comment by TheWojtek** [comment]
> Building from source however should work on macOS (_many of us do dev on macOS for example_), you could try this method as a work-around in the meantime?

Built from source using
`$ brew install --build-from-source netdata `

- still no cloud dependencies. I assume it's not only netdata that needs to be compiled?

**Comment by rickard-von-essen** [comment]
@TheWojtek no like this 👉  https://github.com/netdata/netdata/blob/master/packaging/installer/README.md#automatic-one-line-installation-script

**Comment by TheWojtek** [comment]
@rickard-von-essen This doesn't install the Homebrew version of Netdata, which is the whole point of this thread.

`Last login: Thu Aug 27 17:36:39 on ttys000

➜  ~ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
/var/folders/cg/85crdrh11rxcrw1s5ppbk33w0000gn/T/netdata-test.XXXXXXXXXX.htxU2b6f: line 1: -e: command not found
/var/folders/cg/85crdrh11rxcrw1s5ppbk33w0000gn/T/netdata-test.XXXXXXXXXX.SKs9OQoR: line 1: -e: command not found
/var/folders/cg/85crdrh11rxcrw1s5ppbk33w0000gn/T/netdata-test.XXXXXXXXXX.T0kSHzOa: line 1: -e: command not found

Unable to find a usable temprorary directory. Please set $TMPDIR to a path that is both writable and allows execution of files and try again.
System            : Darwin
Operating System  : Darwin 18.7.0
Machine           : x86_64
BASH major version: 
 WARNING  Cannot detect the packages to be installed on a Darwin - Darwin 18.7.0 system. 

Press ENTER to attempt netdata installation > 
 --- OK, let's give it a try... --- 
[/Users/wojtek]$ curl -q -sSL --connect-timeout 10 --retry 3 --output /sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt curl: (23) Failed writing body (0 != 477)
 FAILED  

[/Users/wojtek]$ curl -q -sSL --connect-timeout 10 --retry 3 --output /netdata-latest.tar.gz https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz curl: (23) Failed writing body (0 != 1388)
 FAILED  

grep: /sha256sum.txt: No such file or directory
 ABORTED  Tarball checksum validation failed. Stopping netdata installation and leaving tarball in  

➜  ~ sudo bash <(curl -Ss https://my-netdata.io/kickstart.sh)
Password:
bash: /dev/fd/11: Bad file descriptor
`

**Comment by rickard-von-essen** [comment]
> This doesn't install the Homebrew version of Netdata, which is the whole point of this thread.

@TheWojtek no it doesn't and he didn't say it would.

**Comment by TheWojtek** [comment]
@rickard-von-essen OK, thanks, I assumed that in a thread regarding Netdata from Homebrew the actual context is Homebrews "--build-from-source", not "generally build from source".
The script never worked on my Macs anyway, which is why I used Homebrew.

OK, seems it's a matter of sitting patiently until the relevant patches for the dependencies are included in the Homebrew repositories.

**Comment by prologic** [comment]
Thanks for your patience! We _do_ plan to work on fixing/addressing this, but it is a non-trivial amount of work and I _think_ we would have to basically start having out own Homebrew tap that contains our dependences. Bare with us!

**Comment by prologic** [comment]
@Ferroin Added to "Refinement" so we can discuss how to approach this as per my comment above.

**Comment by rickard-von-essen** [comment]
> I think we would have to basically start having out own Homebrew tap that contains our dependences

Don't think that would make a big difference. The only really good reason to have your own tap is that your formula doesn't follow the rules that `homebrew-core` has.

**Comment by rickard-von-essen** [comment]
I started to work on this yesterday a bit... I'll report back in a few days.

**Comment by rickard-von-essen** [comment]
Success! 🎉 

<img width="1428" alt="Screenshot 2020-09-01 at 11 39 17" src="https://user-images.githubusercontent.com/557699/91834066-d8a8dd80-ec47-11ea-8dbd-f3e1ddf68a8f.png">

I'll clean it up and then submit a PR for review.

**Comment by rickard-von-essen** [comment]
See https://github.com/Homebrew/homebrew-core/pull/60472

**Comment by prologic** [comment]
Oh wow! 😲 Thank you @rickard-von-essen  Very nicely done ! I'll take a look at this.

**Comment by prologic** [comment]
@Ferroin Please have a look at the PR in Homebrew/homebrew-core#60472

**Comment by rickard-von-essen** [comment]
@prologic yes please have a look. I haven't used Netdata Cloud before so I might have missed something. But at least I managed to run the `netdata-claim.sh` script and hook up my MacBook to my account.

**Comment by Ferroin** [comment]
> > I think we would have to basically start having out own Homebrew tap that contains our dependences
> 
> Don't think that would make a big difference. The only really good reason to have your own tap is that your formula doesn't follow the rules that `homebrew-core` has.

Sounds like we have official reason to have one now: https://github.com/Homebrew/homebrew-core/pull/60472#discussion_r481074604

**Comment by rickard-von-essen** [comment]
@Ferroin give them a few days to debate it.

**Comment by prologic** [comment]
I'll give them to next week to umm and ahh over this. 😀

**Comment by amoss** [comment]
I don't really want to jump into the Homebrew thread as well but the argument seemed strange to me. Why is it ok for python to vendor libraries "because they are different to the system versions" but not Netdata?

**Comment by Ferroin** [comment]
@amoss Their argument revolves around the fact that getting `pip` to properly handle things in a usable way on macOS for a custom Python install (instead of the system copy of Python) is exceedingly difficult.

Their argument about us needing to support system copies of LWS is perfectly valid and not unique to Homebrew at all. Their insistence on mosquitto not being vendored is a bit more excessive, but they're correct that we _should_ be actively pushing those patches upstream (or properly document if they've actively been rejected).

**Comment by amoss** [comment]
Hmmm. Getting our product to work correctly with a system install of mosquito is exceedingly impossible. I can see their point about LWS. Does the system copy have the libcap support that caused us problems?

**Comment by Ferroin** [comment]
libcap wasn't the issue IIRC, it was that we insist on SOCKS5 support even for users who are never going to use it.

**Comment by amoss** [comment]
Wow. I thought that we had a silent failure at link time if libcap support wasn't compiled into the target library. Was that a different issue?

If it is only the SOCK5 support then we should make it optional so that we can install against the system library.

**Comment by Ferroin** [comment]
No, wait, you're right, there was some issue related to linking involving libcap, but I thought it was that _we_ needed to link libcap in if we tried to statically link a version of LWS that had been built against libcap.

The SOCKS5 thing was the big one though, because most distros _don't_ build LWS with SOCKS5 support (they kind of assume you're going to use libsocks instead of the SOCKS5 functionality that's built into LWS if you need SOCKS5 support, because _most_ stuff needs it for more than just websockets).

**Comment by prologic** [comment]
I am closing this issue we "won't fix" as per [this comment](https://github.com/Homebrew/homebrew-core/pull/60472#discussion_r483508692) and [that comment](https://github.com/Homebrew/homebrew-core/pull/60472#discussion_r487635156) -- This is not high enough priority for us to work on at this stage and there are several hard blockers we haven't been able to resolve at this point, furthermore anyone wishing to connect macOS hosts via a Netdata Agent connected to Netdata Cloud __can__ do so by building from source without problems.

Thank you for your patience! 🙏

**Comment by AWHubGit** [comment]
I tried to build netdata for macOS exactely as per
https://learn.netdata.cloud/docs/agent/packaging/installer/methods/macos#install-netdata-from-source
sudo ./netdata-installer.sh --libs-are-really-here --require-cloud --install /usr/local

Build fails: configure: error: User required agent-cloud-link but it can't be built!
.../lib/mosquitto.c:59:10: error: implicit declaration of function 'mach_absolute_time' is invalid in C99

Installed the Judy library before proceeding compiling Netdata successfully, but then /usr/include/Judy.h doesn't exist building own copy. env: libtoolize: No such file/directory. Failed to build libJudy.

This replies to "anyone wishing to connect macOS hosts via a Netdata Agent connected to Netdata Cloud can do so by building from source without problems!!!!"
