### ISSUE TITLE
308 redirect to http site when running behind SSL termination proxy

### ISSUE THREAD

**Issue by asdokfgsopdkg** [netdata/netdata#9065]
##### Bug report summary
Netdata master is running behind a GCP HTTPS proxy.

Node streaming is working fine (streaming ingress is done via GKE LoadBalancer and NOT via the HTTPS proxy).

When I mouse over a streaming node in the dashboard, the link to it is https.
When I click on the node, a http 308 redirect is given to the client, with a `location: http://...` header, which redirects the browser to plain text.
When the browser then tries to load the plain text link, it fails since the load balancer is only listening on HTTPS

##### OS / Environment
GKE 1.15 cluster, Netdata deployed with Helmchart

##### Netdata version
1.22.1

##### Component Name
Dashboard

##### Steps To Reproduce
Run Netdata in HTTP mode behind a HTTPS reverse proxy that performs SSL termination
Stream metrics to it from another node
Hover over a streaming system and observe https link
Click on link
Observe 308 redirect
Observe redirection to http and failure

##### Expected behavior
308 redirect should be to a https link

**Comment by thiagoftsm** [comment]
@jacekkolasa , I think this has relationship with the dashboard instead the agent, because the streaming is working correctly, but case I am wrong, please, let me know.

**Comment by cakrit** [comment]
@jacekkolasa I believe we had seen this in the past and fixed it, apparently it's reared its ugly head again.

**Comment by jacekkolasa** [comment]
@asdokfgsopdkg can you please check if adding `/` at the end of link (the one with https://) will not result in broken redirect?

**Comment by asdokfgsopdkg** [comment]
@jacekkolasa I can confirm adding a `/` fixes the problem 
(that is right click on a streaming host, copy link, paste, add /)

**Comment by prologic** [comment]
Could this have something to with it?

https://github.com/netdata/netdata/blob/5675f2f48ae4b66526e739c4c5094da1b85ce0e9/web/server/web_client.c#L1346-L1351

**Comment by jacekkolasa** [comment]
@prologic yeah, that's possible, very good catch! Now i know why our demo sites, under `https://` were always switching to `http://`. We should definitely respect requested protocol in redirect. @thiagoftsm can you groom/take this task?

Separately from this, trailing slashes will be placed on FE side

**Comment by asdokfgsopdkg** [comment]
https://www.eff.org/https-everywhere is a reasonably trustable browser based workaround in the mean time

**Comment by cakrit** [comment]
@thiagoftsm can u please fix the hard-coded https mentioned in https://github.com/netdata/netdata/issues/9065#issuecomment-631849380? It doesn't look like the `url` param will have the protocol (http/https), but the `web_client` struct _should_ have the hint required to select between http and https.

**Comment by thiagoftsm** [comment]
> @thiagoftsm can u please fix the hard-coded https mentioned in [#9065 (comment)](https://github.com/netdata/netdata/issues/9065#issuecomment-631849380)? It doesn't look like the `url` param will have the protocol (http/https), but the `web_client` struct _should_ have the hint required to select between http and https.

Yes @cakrit . Netdata already has a flag to control the protocol, today I was busy working with health bugs, but tomorrow I will start the day fixing this bug.

**Comment by thiagoftsm** [comment]
Hi @cakrit and @asdokfgsopdkg ,

The protocol was only part of the necessary changes to fix the bug with the PR https://github.com/netdata/netdata/pull/9722.
@asdokfgsopdkg I have two questions for you to confirm that all possible scenarios were covered in the [PR](https://github.com/netdata/netdata/pull/9722). I used nginx proxy, because I do not have a GCP HTTPS proxy to test. I could replicate the same bug you reported here and I was able to fix it. For this I had to consider the following headers available in nginx:

```
X-Forwarded-Proto
X-Forwarded-Host
```

I opted to use `X-Forwarded-Host` instead `X-Forwarded-For`, because nginx and google have different formats for this last header, please, can you confirm that `X-Forwarded-Host` on GCP HTTPS can be configured as `IP:PORT`? If it is not possible , which header do we have the pair `IP:PORT` used to access the proxy?

Best regards!

**Comment by prologic** [comment]
@thiagoftsm We _should_ also respect inbound requests to the agent and the request schema in all redirect responses. For example you hit an agent with https:// and you have to redirect, make sure your `Location:` header also respects the requested URI schema. It makes no sense to do a redirect from https:// -> https:// on the same origin (_and vice versa_).

**Comment by thiagoftsm** [comment]
This is happening now @prologic, and the tests that  I propose in #9722 considered this scenario.
Thank you to call attention for this.

**Comment by prologic** [comment]
> This is happening now @prologic, and the tests that I propose in #9722 considered this scenario.
> Thank you to call attention for this.

Thanks! And no problems! I wouldn't have mentioned it _could_ I understand and read C which I find cryptic at the best of times 😋
