### ISSUE TITLE
Using Pull Dog

### ISSUE THREAD

**Issue by ffMathy** [netdata/netdata#9072]
I recently launched a service that I believe could be helpful in this repository. It's free to use (from a demo-cluster pool of free servers), and I need feedback. I think it could really be a win-win for us both.

https://dogger.io

It automatically spawns up a Docker-based test environment for each of your pull requests, based on a docker-compose.yml file that you choose.

I think it could be helpful in general, to test things out in production before they are merged.

What do you think? It is already used by the [Portainer project](https://github.com/portainer/portainer), and they have been very happy with it so far.

**Comment by prologic** [comment]
Hello @ffMathy! Thank you for your suggestion. It is of course a great idea; However the types of test scenarios we actually need to cover, a Docker-based solution will not really help us cover. We also need to use virtual machine, bare-metal machines as well as eBPF which are only available on Kernels 4.11+ with KPROBES (_and other required options_) enabled.

On top of that, we also need to ensure we oeprate correctly inside of a Kubernetes (k8s) environment.

So it isn't as simple as spinning up a bunch of machines and using `docker-compose up` I'm afarid.

**Comment by ffMathy** [comment]
Thank you for your reply - much appreciated.

Your situation is of course perfectly understandable and makes a lot of sense. 

I assumed part of your application and some types of features would be enough to test in Docker, so that it would still provide value in some way, but I guess there aren't a lot of features or additions that are of that kind 👍

One final thing... If Kubernetes was supported too, would it then be useful?

Once again thanks!

**Comment by prologic** [comment]
> I assumed part of your application and some types of features would be enough to test in Docker, so that it would still provide value in some way, but I guess there aren't a lot of features or additions that are of that kind 👍

There are of course many scenarios we can test with Docker containers. And we do already and are working on increasing this coverage.

> One final thing... If Kubernetes was supported too, would it then be useful?

Possibly. But like everything we would evaluate the feasability of the solutions.
