### ISSUE TITLE
netdata master only can handle 4 slave ?

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [netdata/netdata#9073]
##### Question summary
is the master node only can handle 4 slave streaming data ?

i have 4 machine A,B,C,D on my home LAN, and i let the A as master with dbengine and B,C,D stream  data to A.
now i can see A,B,C,D on the A 's web left-top panel ( home A with slave B,C,D). and i can see the B,C,D with `http://A:19999/host/{B,C,D}` . they are work well. i'm very happy~

then, i want to monitor my vps . so i install the netdata on my vps machine E , and set the stream to my home DynamicIP, and set a Port redirect in my route (openwrt) to let E can stream to the machine A.  now, i can see the E on the A 's web panel , nearby B,C,D .   it work well. i'm very happy~

and then , i install netdata in vps F,G,H , and let F,G,H streaming to E . then i can see the F,G,H on the E 's web left-top panel . it work well. (now the E is run on proxy mode, it collaction from F,G,H and stream data to A .)

but, now when i back to see the A 's web panel, it's behavior interesting. when i reload the page with ctrl+f5 ( i use Firefox), the nodes show on the A's web panel will change. some times it show [A , B,C,D,E] somethins is [A,B,C,D,F] , some times is [A,B,C,D,G].
simplify, the A,B,C,D always show on it, but E,F,G,H only show one with no-rule. and if you manual visit a machine which not showing now on the A's panel by `http://A:19999/host/xxxx`, it tell you `This netdata does not maintain a database for host: xxxxx` , but if the machine show on panel ,the page (`http://A:19999/host/xxxx`) work back.

and then, i let the LAN machine D run in proxy mode, so the stream chain change to `A <- [B,C,D]` , `D<-[E]`, `E<-[F,G,H]` , now i can see the E,F,G,H on the D's web panel, but in A's web panel, same issue.

then, i install netdata on my vps I,J,K,L , and let I,J,K,L stream to E. now,  interesting happend,
on the D, only show the D,F,G,H,I .  on the E, only show the E,F,G,H,I. on the A, it show A,B,C,D with a random one of F,G,H,I,J . 

totally say, i never see the web left-top panel show more than 4 slave at once time. 
the node only showing in the panel can be see on the `http://xxxxxxxx:19999/host/xxxx` .

> is it a bug ? or it's a feature ?

BTW:
use `ls -all /var/cache/netdata/` i can see the db on every server.
the A have 8 dir with UUID and 1 named dbengine .
the D have 5 dir with UUID and 1 named dbengine .
the D have 7 dir with UUID and 1 named dbengine .
it seems so interesting.

##### OS / Environment
Archlinux newgest / Manjaro newgest
netdata v1.22.1 / v1.21.1 install from pacman

##### Component Name
the streaming / db / proxy / master-slave

##### Expected results
i want to monitor all my machine on the one on my LAN server A.
```

[my PC]   ===web===> A 
                     ^
                     |
                  B, C, D
                        ^
                        ||
                     <router>
                        ||
                    vps E
                        ^
                        |
               vps  F,G,H,I,J,K,L,.........

```

**Comment by mfundul** [comment]
Look for suspicious errors in your master netdata server's error log `var/log/netdata/error.log`. Also look for any alarms that may have been triggered in the master's dashboard.

You may have hit a file descriptor limit. Look [here](https://github.com/netdata/netdata/tree/master/database/engine#file-descriptor-requirements) for how to increase it. I have successfully set-up a master server with 1000 slaves so 4 slaves should not be a problem.

**Comment by Lyoko-Jeremie** [comment]
@mfundul 
yes, you are right.
after i set the `LimitNOFILE` , it work well.

thank you very much ~~
