### ISSUE TITLE
netdata master server uses more ram than expected

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9076]
##### Bug report summary

We have defined in the master node to allow each slave to use 64Mb of ram and 256Mb of disk in the `netdata.conf` file:
```
[global]
	memory mode = dbengine
	dbengine disk space = 256
	page cache size = 64
	update every = 10
```
On the Other hand, 50 slaves are streaming to this master, So I expect 3264Mb of ram dedicated to all nodes (51*64mb).
Also, we have 51 dbengine files, so I expect 51* 256Mb= 13056Mb of dbengine file size on the disk, according to the charts, compression ration is about 87% :
![image](https://user-images.githubusercontent.com/7656049/82151591-6d422800-9871-11ea-9af4-021c9cadd59b.png)
So the size of the uncompressed metrics will be about 100430 Mb with 3% footprint mentioned [here](https://github.com/netdata/netdata/tree/master/database/engine#memory-requirements), I expect 3012 Mb of additional ram usage because of dbengine
summing 3012Mb and 3264 Mb of ram, I expect about 6276 MB of ram usage, But I see netdata is using about 10.8 Gb of ram:
![image](https://user-images.githubusercontent.com/7656049/82151758-71227a00-9872-11ea-8e7d-0e3672fa149c.png)
And I see dbengine is using more ram than expected:
![image](https://user-images.githubusercontent.com/7656049/82151813-c3fc3180-9872-11ea-9718-4894f71964de.png)
I checked the dbengine file for each slave and they are not even using the whole 256Mb:
![image](https://user-images.githubusercontent.com/7656049/82152199-e98a3a80-9874-11ea-9b46-39a689543727.png)
So I think the ram usage will increase even more

##### OS / Environment

```
Linux netdata-master-c4-02.x.y.z 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 netdata v1.22.1

##### Component Name

stream

**Comment by mfundul** [comment]
You seem to have a lot of dbengine memory allocated to collectors. How many metrics does each slave collect? Over 5000?

You should check out the calculator here: https://learn.netdata.cloud/docs/agent/database/calculator/

The `metadata` metric in the `netdata.dbengine_ram` seems to be bigger than expected for 50 slaves.

This way you should be able to approximately calculate dbengine memory consumption and we can compare with real-world physical memory allocation of the netdata process itself.

**Comment by yasharne** [comment]
Thanks @mfundul for your explanation, Yes some of our bare metals are also streaming to this master and the collected metrics vary from 8000 to 16000 on them, others collect about 1500 metrics
The number returned by the calculator is almost correct, the `metadata` is now over `1.5Gb`

**Comment by mfundul** [comment]
Let's see now, with 87% compression savings and 256MB disk space we get about 256/0.13=2GB of uncompressed metrics per slave. That is 100GB of uncompressed storage for 51 nodes. In that case the `metadata` can go up to 3GB when all database files are full.

**Comment by yasharne** [comment]
Thanks @mfundul for your explanations, I guess I have to disable the unnecessary plugins on the bare metals and reduce the page cache size to somehow handle this.
