### ISSUE TITLE
[Cloud] Combine multiple interfaces into one graph

### ISSUE THREAD

**Issue by jackmawer** [netdata/netdata#9080]
(Related to #8995.)
Currently, when looking at the nodes page on cloud, if the user has multiple disks or network interfaces, they are bombarded with graphs for that one node, obscuring the rest.
![image](https://user-images.githubusercontent.com/3983253/82210569-3c143700-9907-11ea-88b6-76d3a7c2abd1.png)

I propose that instead all of these interfaces are combined to reflect the title of the column, so that there is one graph for total network usage over all interfaces. The user can then click on the particular node if they want to investigate a specific interface's usage.

This data already appears to exist on the node's page itself:
![image](https://user-images.githubusercontent.com/3983253/82210762-93b2a280-9907-11ea-8916-e7193aab128a.png)

**Comment by ilyam8** [comment]
@manos-saratsis take a look

**Comment by Ferroin** [comment]
Overall fix would be to match on `system.io` and `system.net` contexts.

@jackmawer You can actually do this by hand with the following steps:

1. Click the gear icon at the far right of the metrics headers.
2. In the dropdown that opens, hover the metric group you want to change.
3. On the far right of the line a pencil icon should appear, click that to edit the metric group.
4. Update the context as mentioned above.

You'll unfortunately have to do this for each war room in your space.

**Comment by jackmawer** [comment]
@Ferroin thanks very much for the workaround!
I still think changing the contexts of the default metric set would align better with the titles

**Comment by Ferroin** [comment]
> I still think changing the contexts of the default metric set would align better with the titles

I absolutely agree, I've done the same in all of my spaces too (though mostly because of disks in my case (one of my systems has a total of 26 charts for disks because the default pulls in LVM volumes too)).

**Comment by manos-saratsis** [comment]
@jackmawer thx for using Cloud! Regarding your request, we want to give the option to see one chart per node & column with the use of aggregate functions (eg Sum, Sum of Absolute, Min, Max, Average). Stay tuned.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
