### ISSUE TITLE
Netdata high availability best practices 

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9082]
##### Question summary
We have 5 clusters of netdata masters, each cluster has two machines with a shared IP address using `keepalived` watching the `netdata` systems unit.
In most cases, everything is fine unless in situations where the machines inside the cluster cannot see each other and the master node changes in the cluster, after 10 minutes we start to get lots of `last collected` alerts from the first master but everything else is fine.
I wonder if there are any best practices on how to implement netdata high availability plan

**Comment by ilyam8** [comment]
> I wonder if there are any best practices on how to implement netdata high availability plan


I think there are no best practices, at least we have no such page in our documentation.

As for HA in general i heard that master/master replication is in our plan.

> cannot see each other and the master node changes in the cluster

Does that mean _split-brains_ situation? some nd ~~slaves~~ [children](https://github.com/netdata/netdata/pull/9323) stream to A, some to B?

If you mean keealive leader (i dont know their terms) is being changed i suspect there should be `preempt` feature or something like that. (node A fails to send keepalives, node B declares itself as aleader, node A back to normal and get leader back 😄).

**Comment by ilyam8** [comment]
@dim08 in general `nd` high availability setup is a good topic to think about.

**Comment by ilyam8** [comment]
@yasharne if you dont mind it would be nice to have clear view what is happening in your case, do a step by step description, i am not quite sure i understand actual sequence of events and results of these events.

**Comment by yasharne** [comment]
@ilyam8 We have two parent nodes, each has `keepalived` installed on and a separate IP address, we also have a shared IP between these two parents managed by `keepalived`, these `keepalived` instances will choose a server to be the parent and dedicate the shared IP to the parent server, each `keepalived` checks if the local netdata instance on the servers are running, they also check if both `keepalived`s can see each other, so either if the parent server restarts or the netdata service stops, the other server will be promoted to be the parent and the shared IP now belongs to the second server.
In our scenario, we had an issue when the local `keepalived` couldn't make sure the local netdata instance is running (could be kernel problem or something else), so it tells the other `keepalived` instance I don't run the netdata so now you should be the new parent (whereas the netdata was running on the first parent), so now all the metrics go to the new parent and the first parent which is not getting any metrics anymore starts to raise `last collected` alarm for every single child streaming metrics to it

**Comment by ilyam8** [comment]
Ok, i see, this is expected, thx.

I assume parent/parent replication should fix the issue (implying first parent really is unavailable). cc @amoss

**Comment by yasharne** [comment]
@ilyam8 parent/parent replication needs alert deduplication, if one parent sends an alert, another parent should not send the alert

**Comment by cakrit** [comment]
Don't know anything about `keepalived`, but it looks like you can execute a script when the old parent loses its IP:

Keyword | Definition | Type
-- | -- | --
notify_backup | specify a shell script to be executed during transition to backup state | path
notify_fault | specify a shell script to be executed during transition to fault state | path

That script could for example [silence alarms](https://learn.netdata.cloud/docs/agent/web/api/health#health-management-api),  if the old parent is still running, or modify `netdata.conf` on the old parent to ensure that health checks no longer run at all, or even do something to stop netdata and keep it from restarting, until an admin has resolved the root cause. Similarly,  a `notify_master` script could enable alarms on the new parent.
