### ISSUE TITLE
Prometheus backend's optional TYPE and HELP lines repeated for each instance of each metric

### ISSUE THREAD

**Issue by jeffgdotorg** [netdata/netdata#9088]
##### Bug report summary
This issue is related to #9085 but does not break the parser I'm using the way that one does, and strikes me as harder to fix.

When the optional `TYPE` and/or `HELP` lines are enabled in the Prometheus backend (by setting `help=yes` and/or `types=yes` in the URL parms), the enabled lines appear before every instance of every metric. This behavior contradicts the [Prometheus project's specification](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#comments-help-text-and-type-information) for the textual exposition format, which states, in part:

> Only one `HELP` line may exist for any given metric name.

And:

> Only one `TYPE` line may exist for a given metric name. The `TYPE` line for a metric name must appear before the first sample is reported for that metric name.

##### OS / Environment
CentOS 7 in VM (no container in the mix):

```
/etc/centos-release:CentOS Linux release 7.6.1810 (Core) 
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.6.1810 (Core) 
/etc/system-release:CentOS Linux release 7.6.1810 (Core) 
```

##### Netdata version
`netdata v1.22.1-55-g140734a` 

##### Component Name
`backends/prometheus`

##### Steps To Reproduce
1. Build and install Netdata from master / e99692f145f710930723081d2e5bbf8868be2080
2. Start Netdata service
3. Fetch `http://127.0.0.1:19999/api/v1/allmetrics?format=prometheus&types=yes&help=yes`

##### Expected behavior
Output includes embedded `TYPE` and `HELP` lines just once per metric name:

```
# HELP netdata_netdata_db_points_points_persec_average: dimension "read", value is points/s, gauge, dt 1589833074 to 1589833083 inclusive
# TYPE netdata_netdata_db_points_points_persec_average gauge
netdata_netdata_db_points_points_persec_average{chart="netdata.db_points",family="queries",dimension="read"} 57.0000026 1589833083000
netdata_netdata_db_points_points_persec_average{chart="netdata.db_points",family="queries",dimension="generated"} -1.2000000 1589833083000
```

##### Actual behavior
Output includes extra embedded lines, with a set appearing once before every instance of every metric name:

```
# COMMENT homogeneous chart "netdata.db_points", context "netdata.db_points", family "queries", units "points/s"
# COMMENT netdata_netdata_db_points_points_persec_average: dimension "read", value is points/s, gauge, dt 1589833074 to 1589833083 inclusive
# COMMENT TYPE netdata_netdata_db_points_points_persec_average gauge
netdata_netdata_db_points_points_persec_average{chart="netdata.db_points",family="queries",dimension="read"} 57.0000026 1589833083000
# COMMENT netdata_netdata_db_points_points_persec_average: dimension "generated", value is points/s, gauge, dt 1589833074 to 1589833083 inclusive
# COMMENT TYPE netdata_netdata_db_points_points_persec_average gauge
netdata_netdata_db_points_points_persec_average{chart="netdata.db_points",family="queries",dimension="generated"} -1.2000000 1589833083000
```

Note also that those lines starting with `# COMMENT` really ought to start `# HELP` instead, and the ones starting `# COMMENT TYPE` should start with `# TYPE` (as explained in #9085).

**Comment by ilyam8** [comment]
@vlvkobal indeed, `&types=yes&help=yes` output is broken

**Comment by vlvkobal** [comment]
Netdata doesn't have `# HELP` lines, look at https://github.com/netdata/netdata/issues/9089#issuecomment-674889387. Both, `# COMMENT` and `# TYPE` lines are different for every dimension. We can't fix the issue while our existing data model is used so I'm closing it.

You are welcome to share your ideas on Netdata redesign. There are a lot of open issues with discussions, related to the data model.
