### ISSUE TITLE
Prometheus HELP lines incorrectly formatted (when enabled via query parm)

### ISSUE THREAD

**Issue by jeffgdotorg** [netdata/netdata#9089]
#### Bug report summary
Related to #9085 but does not break the parser I'm using the way that one does, so less critical from my perspective. Also related to #9088 but this one seems easier to fix.

When the Prometheus backend's optional HELP lines are enabled (by adding `help=yes` to the query parameters), the resulting lines incorrectly start with `# COMMENT` instead of `# HELP` as specified in the [Prometheus project's specification](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#comments-help-text-and-type-information) for the textual exposition format, which states, in part (*emphasis mine*):

> Lines with a `#` as the first non-whitespace character are comments. They are ignored unless the first token after `#` is either `HELP` or `TYPE`. Those lines are treated as follows: *If the token is `HELP`, at least one more token is expected*, which is the metric name. All remaining tokens are *considered the docstring for that metric name*.

The Prometheus docs do not mention a role for the sequence `# COMMENT` so I surmise this is a case of crossed wires during late-night hacking ;)

##### OS / Environment
CentOS 7 in VM (no container in the mix):
```
/etc/centos-release:CentOS Linux release 7.6.1810 (Core) 
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.6.1810 (Core) 
/etc/system-release:CentOS Linux release 7.6.1810 (Core) 
```

##### Netdata version
`netdata v1.22.1-55-g140734a`

##### Component Name
`backends/prometheus`

##### Steps To Reproduce
1. Build and install Netdata from master / `e99692f145f710930723081d2e5bbf8868be2080`
2. Start Netdata service
3. Fetch `http://127.0.0.1:19999/api/v1/allmetrics?format=prometheus&help=yes`

##### Expected behavior
Output includes embedded lines of the form:

```
# HELP netdata_disk_avgsz_KiB_operation_average: dimension "writes", value is KiB/operation, gauge, dt 1589833074 to 1589833083 inclusive
```

##### Actual behavior
Output includes embedded lines of the form:

```
# COMMENT netdata_disk_avgsz_KiB_operation_average: dimension "writes", value is KiB/operation, gauge, dt 1589833074 to 1589833083 inclusive
```

**Comment by ilyam8** [comment]
I see they have COMMENT Entry in their parser, dont know what it means

https://github.com/prometheus/prometheus/blob/e825282dd1b7a62999ed50d5c8039c5fdda89bea/pkg/textparse/interface.go#L72-L82

**Comment by jeffgdotorg** [comment]
> I see they have COMMENT Entry in their parser, dont know what it means

I don't think this tells us that `# COMMENT` is necessarily A Thing, but that the parser understands some unit which is retrieved by calling the `Comment()` method. I'd have to study the whole parser to be sure, and to do that I'd need to learn to read Go properly, so I'm leaning on my experience with parsers I've made using antlr in this assessment. Happy to be shown wrong.

The [Prometheus `node_exporter`](https://github.com/prometheus/node_exporter/) might also be illustrative, particularly given its association with the Prometheus project writ large. That agent gives output like this (full output in [this gist](https://gist.github.com/jeffgdotorg/dce92906c6a89b9dec44180db5597bb3)):

```
# HELP node_filesystem_avail_bytes Filesystem space available to non-root users in bytes.
# TYPE node_filesystem_avail_bytes gauge
node_filesystem_avail_bytes{device="/dev/sda1",fstype="xfs",mountpoint="/"} 3.7144436736e+10
node_filesystem_avail_bytes{device="rootfs",fstype="rootfs",mountpoint="/"} 3.7144436736e+10
node_filesystem_avail_bytes{device="tmpfs",fstype="tmpfs",mountpoint="/run"} 9.1860992e+08
node_filesystem_avail_bytes{device="tmpfs",fstype="tmpfs",mountpoint="/run/user/1000"} 1.92733184e+08
```

No occurrences of `# COMMENT` to be found, which I think indicates that it's a totally valid construction, but does not have its own independent meaning.

**Comment by ilyam8** [comment]
i see prom parser skips all comments (comment everything that starts with `#` but w/o HELP,TYPE)

https://github.com/prometheus/prometheus/blob/8224ddec23598152d7506b7b39f5235a77b5e036/scrape/scrape.go#L1121-L1122

So you can add any comments but they are not being parsed by the parser

**Comment by ilyam8** [comment]
i was not trying to argue, just did a quick search

**Comment by vlvkobal** [comment]
Netdata doesn't have `# HELP lines`. The purpose of `# COMMENT` is different and we can't convert it to `# HELP`. Look at https://github.com/netdata/netdata/issues/1497#issuecomment-270218288.

I'm closing the issue and the corresponding PR.
