### ISSUE TITLE
[GUIDE] -> How to install Netdata on FreeBSD

### ISSUE THREAD

**Issue by thoggs** [netdata/netdata#9095]
Hello,
I recently did a Netdata installation tutorial on FreeBSD, for the community of that operating system; and I would like to share it here too, in case any future Netdata user chooses to install on FreeBSD.
The official Netdata tutorial for FreeBSD does not work properly, due to the lack of some components of the cmake package, and does not instruct how to mark the Netdata service as bootable (start during the boot process), something simple but that makes a difference for those who are having the first contact with Netdata on FreeBSD.

Note: this guide aims to cover any version of FreeBSD, provided that the Netdata team maintains support for that operating system.

**GUIDE =>** https://forums.freebsd.org/threads/guide-how-to-install-netdata-on-freebsd.75465/

See you...
![Captura de Tela 2020-05-19 às 05 21 50](https://user-images.githubusercontent.com/43221193/82302930-a8874880-9990-11ea-8b7f-ce89aed2cd5a.png)

**Comment by thiagoftsm** [comment]
Hi @thoggs ,

Netdata has a directory called `docs/step-by-step`, please, take a look in this directory and the file formats there. You can adapt your text to the format we use and create a PR for it.
Thank you for your post in the cited forum.

Best regards!

**Comment by joelhans** [comment]
Thanks for taking the time to write up the steps that worked for you! We rely quite heavily on the communities for our various supported operating systems to make sure the docs are up-to-date.

We could also make an effort to "port" some of this information to https://github.com/netdata/netdata/blob/master/packaging/installer/methods/freebsd.md, since you say those instructions did not work for you initially.

@thoggs please let us know if you're interested in submitting a PR. I could also handle this myself, but I'll need a day or two to work through my existing tasks!

**Comment by thoggs** [comment]
> Hi @thoggs ,
> 
> Netdata has a directory called `docs/step-by-step`, please, take a look in this directory and the file formats there. You can adapt your text to the format we use and create a PR for it.
> Thank you for your post in the cited forum.
> 
> Best regards!

Yes, I find it much more interesting to create a PR that instructs FreeBSD users to install Netdata on FreeBSD

**Comment by thoggs** [comment]
> please let us know if you're interested in submitting a PR. I could also handle this myself, but I'll need a day or two to work through my existing tasks!

Great, I am interested, we can talk about it when you have free time...

**Comment by thiagoftsm** [comment]
Hi @thoggs ,

Considering that @joelhans, our specialist, already gave us the link talking about the Netdata installation on FreeBSD, I will give a suggestion to you, change the specified file that he gave us and create your PR with the text you made. 

Best regards!

**Comment by thoggs** [comment]
> Hi @thoggs ,
> 
> Considering that @joelhans, our specialist, already gave us the link talking about the Netdata installation on FreeBSD, I will give a suggestion to you, change the specified file that he gave us and create your PR with the text you made.
> 
> Best regards!

Perfect, I'll do it tomorrow, I'm already putting it as one of my activities ...

Lengths, my noble friend!
