### ISSUE TITLE
Ability to enable/disable alarms for certain hours of the day

### ISSUE THREAD

**Issue by nicknaychov** [netdata/netdata#9097]
Hi
Great work on that project, you guys are rockstars!
System can fit almost all my monitoring needs , however I think there is small room for improvement.
I would like to be able to enable certain alarm for certain time frame only.  
I am monitoring calls and I have set an alarm for lack of new calls in past minute so i will get notified if something with traffic gets wrong. But because during midnight hours 12-4 AM there is almost no call attempts, alarm get triggered falsely. So if there is way to turn off some alarms during certain time interval would be good thing to have or to apply different thresholds depending on time.

Thanks

**Comment by dim08** [comment]
Hi there! Thank you for your positive feedback. We will add this feature in our roadmap. Would you be interested in sharing some data to help us during the design phase? (i.e. a snapshot of the agent)

**Comment by nicknaychov** [comment]
hi

thank you for your response. Sure I can do that, let me know how, when 
and what you need from me.

**Comment by Saruspete** [comment]
Hello,

This reminds me of an old request, merged last year #3187

Can you check if it's what you need ?

Cheers,

**Comment by nicknaychov** [comment]
Hi

you are right this is similar, however the solution you implemented does 
not seems to have ability to configure time periods during which certain 
alarms to be silenced, instead you need to do dynamic API calls. I think 
if you have static file where you can just configure the time periods 
during which certain alarms will be disabled or to apply different 
thresholds depending on time will be easier.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
