### ISSUE TITLE
[Cloud] Please sort nvidia-smi in dashboard order by GPU id

### ISSUE THREAD

**Issue by pureexe** [netdata/netdata#9100]
##### Feature idea summary
Currently, nvidia-smi on cloud dashboard look weird. they are in random order  which hard to read.
![image](https://user-images.githubusercontent.com/1303847/82345517-8ee11200-9a1f-11ea-9fc9-9533c1625c26.png)

##### Expected behavior
It's should sort by GPU id like this. (this photo was editted)

![image](https://user-images.githubusercontent.com/1303847/82346090-3d855280-9a20-11ea-97c0-6413efcf5c3d.png)

**Comment by ilyam8** [comment]
hi @pureexe is order correct on the agent dashboard?

**Comment by ilyam8** [comment]
ok, i checked the code, the order is correct 100%

https://github.com/netdata/netdata/blob/d1a463a01b26e039d33b4d279bc3922fe76cc48e/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L430-L434

**Comment by ilyam8** [comment]
@manos-saratsis it seems the charts are not sorted by chart priority

**Comment by pureexe** [comment]
![image](https://user-images.githubusercontent.com/1303847/82363438-04f17300-9a38-11ea-8e9b-faf3de261894.png)
It sorted correctly in agent dashboard

**Comment by pureexe** [comment]
Problem solve on June 30. Thank you so much.
![Imgur](https://i.imgur.com/nt38NqF.png)

**Comment by manos-saratsis** [comment]
@pureexe thx for letting us know!
