### ISSUE TITLE
Visual indication for n° of silenced alarm

### ISSUE THREAD

**Issue by ovv** [netdata/netdata#9102]
##### Feature idea summary

Display some kind of indicator in the web UI showing the number of silenced alarms and/or if all alarms are silenced.

It sometime happen that I forget to turn on alarms after doing some work on the server, a visual indicator of that would be a nice way to remember I forgot something.

**Comment by manos-saratsis** [comment]
@ovv thanks for the hint. We should add it both on the Agent and the Cloud
Cc @oyabun @AndyWindy

**Comment by manos-saratsis** [comment]
Closing this, is tracked with a different issue

**Comment by ovv** [comment]
@manos-saratsis can you give a link to the other issue

**Comment by manos-saratsis** [comment]
@ovv I cannot but when is done I'll let you know with a comment on this one

**Comment by ovv** [comment]
@manos-saratsis Hello, is this still tracked ? Any chance it will happen ?

**Comment by manos-saratsis** [comment]
@ovv we still have not implemented silencing via the GUI. It's a nice idea and there is a chance it can happen within the next quarter Cc @dim08 who is the product manager for alerting
