### ISSUE TITLE
Improve dbengine calculator/docs for multi-node setups

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#9106]
After receiving some feedback, both internally and from users, I think we need to explain a few things about the database engine a little more clearly.

Most of the confusion is around multi-node setups, how much disk space is required to store all the streamed metrics, and what they should set `dbengine disk space` to. See this image for a situation that caused confusion for the user.

![image001](https://user-images.githubusercontent.com/1153921/82375750-e064af00-99d5-11ea-8c1e-a422626e4f1e.png)

They don't understand the discrepancy between **3299194 MiB** in required disk space and a `dbengine disk space` setting of only **3296**. My impression is that the `dbengine disk space` setting means each _dbengine instance_ is allowed 3296 MiB in disk space, and because this system would have 1001 dbengine instances, the entire configuration would require 3299194 MiB in disk space.

If my impression is correct, we need to communicate this better to users, both in the calculator and the dbengine docs. My action items once I get confirmation:

1. Confirm that the values outputted by the [calculator](https://learn.netdata.cloud/docs/agent/database/calculator) are correct when there is more than 1 slave node.
2. Improve the copy on the calculator to emphasize the difference between the size of dbengine instances and the entire required disk space.
3. Improve the text in the dbengine docs to convey the same point.

cc @zack-shoylev @mfundul

**Comment by mfundul** [comment]
Your impression is correct. This will have to change when we implement multi-host database. Then there will only be 1 database for all hosts in the agent.

**Comment by joelhans** [comment]
@mfundul Thanks. I'll take care of putting together some updates and ping you as a reviewer when it's ready.
