### ISSUE TITLE
Netdata Cloud Agent on FreeBSD

### ISSUE THREAD

**Issue by manjotsc** [netdata/netdata#9109]
Can't add netdata to netdata cloud.

![Inked82404344-0f5b3f00-9a2f-11ea-8955-df549ec7ff5c_LI](https://user-images.githubusercontent.com/51430971/83343055-dbe8a200-a2c3-11ea-85f4-03332f42a692.jpg)

**Comment by ilyam8** [comment]
@manjotsc hi, how did you install netdata?

**Comment by manjotsc** [comment]
freebsd : pkg install http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/netdata-1.22.1.txz

**Comment by ilyam8** [comment]
@manjotsc we dont maintain [netdata freebsd pkg](https://www.freebsd.org/cgi/ports.cgi?query=netdata&stype=all)

@mmokhi can you help?

**Comment by manjotsc** [comment]
@mmokhi help needed

Thanks,

**Comment by stevenh** [comment]
This is because of the libwebsockets and mosquitto, why are these internal deps and static?

**Comment by manjotsc** [comment]
@stevenh where can I get those for FreeBSD.
Thanks

**Comment by stevenh** [comment]
They are in the ports tree but they are old.

I have an updated port I'm working on which now compiles and links to shared libs but still doesn't work I get the following:
```
2020-05-30 01:04:06: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 128.722 seconds
2020-05-30 01:06:15: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-05-30 01:06:15: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/XXX/challenge
2020-05-30 01:06:15: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-05-30 01:06:15: netdata ERROR : ACLK_Main : Challenge failed:  (errno 22, Invalid argument)
```
I suspect my patching of `mosquitto` may have an issue as `netdata` depends on a custom version :(

**Comment by stevenh** [comment]
Ok found the issue if `libwebsockets` is compiled with `IPv6` you get this error, at least if the host itself doesn't have valid `IPv6` configuration.

**Comment by stevenh** [comment]
@manjotsc the following 3 bug requests include the patches needed to add cloud support the ports tree version of netdata.

Also note that you must configure libwebsockets with IPv6 disabled based on my experience above.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246878
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246880
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246884

**Comment by stevenh** [comment]
@ilyam8 could you add a FreeBSD label so its easy to find all the FreeBSD related issues?

**Comment by ilyam8** [comment]
[added](https://github.com/netdata/netdata/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aos%2Fbsd)

**Comment by stevenh** [comment]
Thanks much appreciated, if you see any other label them and I'll do my best to have a look.

**Comment by Ferroin** [comment]
> This is because of the libwebsockets and mosquitto dependencies which are not detected.
>
> Why are these internal and static?

libmosquitto currently requires special patches that aren't upstream (we've been working to get the required changes upstream, but I'm not certain of the current status of this).

libwebsockets currently needs to be built with an option that most Linux distributions do not build it with (because we for some reasond ecided to handle SOCKS5 support in a non-standard way, note that I'm not hugely happy about this either). In theory this _should_ be possible to handle correctly on FreeBSD if using the Ports tree, but right now we don't support using a system-provided copy of LWS (see https://github.com/netdata/netdata/issues/8961, I'm also not very happy about this either as it means that we can't get proper Gentoo support).

**Comment by underhood** [comment]
@Ferroin  SOCKS5 support we use standard from libwebsockets... problem was many distros had libwebsockets without SOCKS5 support compiled in.

**Comment by Ferroin** [comment]
@underhood Yes, because they assume that apps will use libsocks from Dante instead of using the LWS functionality because most tools that use SOCKS need more than just WebSockets to work over it.

IOW, we're using the LWS provided SOCKS implementation, but that's not the standard way to use SOCKS on Linux.

**Comment by stevenh** [comment]
Thanks for detailed info @Ferroin 

Once I get a little bit of free time I will extract my automake changes from the FreeBSD port and put in the PR, that will allow it netdata to be compiled with local shared or static if thats of interest?

**Comment by Ferroin** [comment]
> Thanks for detailed info @Ferroin
> 
> Once I get a little bit of free time I will extract my automake changes from the FreeBSD port and put in the PR, that will allow it netdata to be compiled with local shared or static if thats of interest?

I can't comment on the position of the team as a whole on this, but I for one would be ecstatic to have such an option.

**Comment by amoss** [comment]
I'm about to review @stevenh's PR to see if we can merge it. @underhood what is the status of getting our changes to LWS upstream so that we can rely on a particular version number in the system instead of our custom port?

**Comment by underhood** [comment]
The changes were for Mosquitto not LWS. I can't remember the reason anymore but there was no attempt to get the changes upstream.

**Comment by Just-Insane** [comment]
Was this ever resolved? It seems like the package was never built with cloud support (or at least not in a way I've been able to get to work across two machines). I also haven't gotten an install via `kickstart.sh` to work due to dependency issues on FreeBSD 12

**Comment by MrZammler** [comment]
@78Star Hi!

Our current master branch should be able to compile on FreeBSD 12... I'll do a check on a VM, and will let you know, probably would need to compile it...

Thanks!
