### ISSUE TITLE
[Cloud] Sensor temperature on 2950x always show over heat in cloud dashboard. but it work fine in agent dashboard

### ISSUE THREAD

**Issue by pureexe** [netdata/netdata#9110]
##### Bug report summary
Machine that use Threadripper 2950x is show incorrect sensor temperature in cloud but it show correctly in agent.

However, This problem doesn't happend in Threadripper 2920x and 3960x

![image](https://user-images.githubusercontent.com/1303847/82402613-16ae3700-9a87-11ea-94aa-2a5572378ae8.png)

##### OS / Environment

```
Linux vision03-desktop 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 netdata v1.22.1-59-nightly

##### Component Name

bug in the cloud dashboard show as picture above

##### Steps To Reproduce

1. install netdata on 2950x machine
2. pair account with cloud data
3. add temperature matrix

##### Expected behavior

temperature should show around  50-90 degree as show in the right of screen capture.

**Comment by Mormacill** [comment]
Same Problem here.
![1](https://user-images.githubusercontent.com/31103546/83956030-b9bdc980-a859-11ea-9df6-414a0d6d2930.PNG)

**Comment by ilyam8** [comment]
Issue moved to [netdata/netdata-cloud #131](https://github.com/netdata/netdata-cloud/issues/131) via [**ZenHub**](https://www.zenhub.com/)
