### ISSUE TITLE
netdata: spawn/spawn.c:202: create_spawn_server: Assertion `ret == 0' failed.

### ISSUE THREAD

**Issue by bashirs-investing** [netdata/netdata#9113]
Hi , 
netdata stoped working on the server 
is it a known issue for you , since i looked up for this issue and couldn't find information  / solution regarding it  

 when try to restart the service get this error : 
Starting netdata...2020-05-20 14:45:30: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2020-05-20 14:45:30: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
                                                           [  OK  ]

and from the log file : 
```
2020-05-20 14:45:30: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 350000, max = 350000
2020-05-20 14:45:30: netdata INFO  : MAIN : Adjusted my Out-Of-Memory (OOM) score from 0 to 1000.
2020-05-20 14:45:30: netdata INFO  : MAIN : Adjusted netdata scheduling policy to idle (5), with priority 0.
2020-05-20 14:45:30: netdata INFO  : MAIN : Running with process scheduling policy 'idle'
2020-05-20 14:45:30: netdata INFO  : MAIN : netdata started on pid 58514.
2020-05-20 14:45:30: netdata INFO  : MAIN : Initializing spawn client.
netdata: spawn/spawn.c:202: create_spawn_server: Assertion `ret == 0' failed.
```
OS:
```
runing on : 
CentOS release 6.8 (Final)
Linux  3.10.79-1.el6.elrepo.x86_64 #1 SMP Mon May 18 12:08:18 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

```
netdat version : 

netdata v1.22.1-74-nightly

tried to uninstall and reinstall netdata , same issue

**Comment by mfundul** [comment]
I don't see this problem with CentOS 6 and `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` installation method.

How did you install?

**Comment by bashirs-investing** [comment]
i did install it using the same method.

**Comment by mfundul** [comment]
Did you give any special arguments? Did you install libuv yourself or did the script install it? What's you libuv version?

**Comment by mfundul** [comment]
Ah, another thing is that I've got a more up-to-date CentOS installation, which is:
```
CentOS release 6.10 (Final)
```

**Comment by bashirs-investing** [comment]
libuv-devel-1.7.5-1.el6.x86_64
libuv-1.7.5-1.el6.x86_64


and it was installed  by the script

**Comment by mfundul** [comment]
Your system packages seem to be at least 3 years old. Centos 6.9 was release on April 5, 2017 and you have 6.8

However, I don't necessarily think the packages themselves are related to this problem.

1. Do you have any special configuration in `/etc/netdata.conf` regarding netdata users and permissions?

2. Is the netdata binary located in `/usr/sbin/netdata`? Can you run `ls -lZ /usr/sbin/netdata`?

3. Can you share your `var/log/netdata/error.log`?

**Comment by bashirs-investing** [comment]
1. no special configuration . still with the default configuration from the install .

2. yes it's located at : /usr/sbin/netdata
-rwxr-xr-x root root ?                                /usr/sbin/netdata

Can you share your var/log/netdata/error.log?

# cat /var/log/netdata/error.log
2020-05-21 06:45:30: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 350000, max = 350000
2020-05-21 06:45:30: netdata INFO  : MAIN : Adjusted my Out-Of-Memory (OOM) score from 0 to 1000.
2020-05-21 06:45:30: netdata INFO  : MAIN : Adjusted netdata scheduling policy to idle (5), with priority 0.
2020-05-21 06:45:30: netdata INFO  : MAIN : Running with process scheduling policy 'idle'
2020-05-21 06:45:30: netdata INFO  : MAIN : netdata started on pid 4495.
2020-05-21 06:45:30: netdata INFO  : MAIN : Initializing spawn client.
netdata: spawn/spawn.c:202: create_spawn_server: Assertion `ret == 0' failed.

**Comment by mfundul** [comment]
I cannot reproduce this problem for some reason.

Can you try installing the statically built netdata binary? This could solve any dependency related issues.  First you should uninstall by running `/usr/libexec/netdata/netdata-uninstaller.sh`.

Then you can install the static binaries following the [instructions](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64).

**Comment by bashirs-investing** [comment]
now getting this error : 

2020-05-21 10:31:27: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 350000, max = 350000
2020-05-21 10:31:27: netdata INFO  : MAIN : Adjusted my Out-Of-Memory (OOM) score from 0 to 1000.
2020-05-21 10:31:27: netdata ERROR : MAIN : Cannot adjust netdata scheduling policy to idle (5), with priority 0. Falling back to nice. (errno 38, Function not implemented)
2020-05-21 10:31:27: netdata ERROR : MAIN : Cannot get my current process scheduling policy. (errno 38, Function not implemented)
2020-05-21 10:31:27: netdata INFO  : MAIN : netdata started on pid 15796.
2020-05-21 10:31:27: netdata INFO  : MAIN : Initializing spawn client.
Assertion failed: ret == 0 (spawn/spawn.c: create_spawn_server: 202)

**Comment by mfundul** [comment]
What are the contents of `etc/netdata/netdata.conf`?

**Comment by bashirs-investing** [comment]
[netdata.conf.txt](https://github.com/netdata/netdata/files/4662143/netdata.conf.txt)

default didn't changed anything in it

**Comment by bashirs-investing** [comment]
by the way i have another servers that  stoped working with centos 6.10
CentOS release 6.10 (Final)
3.10.80-1.el6.elrepo.x86_64 



and have another server that atill working fine : 
CentOS release 6.10 (Final)
3.10.105-1.el6.elrepo.x86_64

**Comment by mfundul** [comment]
That doesn't look right.
The installation folder should have changed to be under `/opt/` for the static binaries.
Can you verify that you're indeed running netdata under `/opt/`?
There should be `/opt/netdata/usr/sbin/netdata` and `/opt/netdata/etc/netdata/netdata.conf`.

Can you run `ldd /opt/netdata/usr/bin/srv/netdata`?

**Comment by bashirs-investing** [comment]
sorry sent you the wrong conf from different server 
this is the conf form /opt/netdata/etc/netdata/netdata.conf

--> cat netdata.conf 
# netdata can generate its own config which is available at 'http://<netdata_ip>/netdata.conf'
# You can download it with command like: 'wget -O /opt/netdata/etc/netdata/netdata.conf http://localhost:19999/netdata.conf'


 -->ldd /opt/netdata/usr/bin/srv/netdata
	statically linked

**Comment by mfundul** [comment]
For the sake of debugging, what happens if netdata runs as root? To test this you can add this to the global netdata configuration in `netdata.conf`:
```
[global]
	run as user = netdata
```
and restart the service.

**Comment by bashirs-investing** [comment]
same error

**Comment by mfundul** [comment]
I need you to compile a C test program to compare your machines that work to the machines that don't work, to try and find out why exactly netdata fails.

You should create a `test.c` file with contents:
```
#include <stdio.h>
#include <uv.h>

int main(int argc, char **argv)
{

    size_t exepath_size;
    char exepath[FILENAME_MAX];
    int ret;

    exepath_size = sizeof(exepath);
    ret = uv_exepath(exepath, &exepath_size);
    printf("ret=%d size=%d path=\"%s\"\n", ret, exepath_size, exepath);

  return 0;
}
```

You build it by running `gcc test.c -o test -luv`. This will create the `./test` binary. Then you can run this program in the good CentOS machine and the bad one, and share the output to see what's going on.

**Comment by bashirs-investing** [comment]
same output on both 
ret=0 size=10 path="/root/test"

**Comment by mfundul** [comment]
What if you put the `./test` binary in `/usr/sbin` and run it as root and as netdata user?
E.g.
```
cp ./test /usr/sbin/
sudo -u netdata /usr/sbin/test
sudo -u root /usr/sbin/test
```

**Comment by bashirs-investing** [comment]
on both server same result with root and netdata users   , but i see the size is different than running in /root 
 
 ret=0 size=14 path="/usr/sbin/test"

**Comment by mfundul** [comment]
@bashirs-investing could you run the latest code from master branch, or wait one day for the next nightly, to get some more verbose output from netdata?

**Comment by mfundul** [comment]
@bashirs-investing can you test #9339 ?
To compile from source you'd have to do the following:
```
git clone https://github.com/netdata/netdata.git
cd netdata/
git fetch origin pull/9339/head:PR9339
git checkout PR9339 
```

To get any additional changes from the PR if it's needed you'd have to run:
```
git pull origin pull/9339/head
```
from the same `netdata/` directory.

To replace the existing installation you need to install the dependencies and afterward run the installer. Run those from the `netdata/` directory:
```
sudo packaging/installer/install-required-packages.sh netdata
```
If your installation is under `/opt/netdata` then run the installer this way:
```
sudo ./netdata-installer.sh --install /opt
```
otherwise run it this way for the default location:
```
sudo ./netdata-installer.sh 
```

**Comment by bashirs-investing** [comment]
yup it solved the problem . 

now it's working
