### ISSUE TITLE
Server went "Unreachable" and I got NO notification

### ISSUE THREAD

**Issue by drayvs** [netdata/netdata#9121]
I am wondering if its possible to create notifications on netdata cloud, so if server in question is unreachable I know about it ?

My server runs on Ubuntu 18.04 LTS.

Another question I have is about customizing notifications, so I don't get spammed about FIFO errors for example (I get 10-20 notices about those a day, how they are >0, and how they fixed themselfs)...

I am sorry if my questions were answered already, but I couldn't find a newby forum for netdata :(

**Comment by ilyam8** [comment]
> I am wondering if its possible to create notifications on netdata cloud, so if server in question is unreachable I know about it ?

Actually a good idea.

@manos-saratsis take a look

**Comment by ilyam8** [comment]
> Another question I have is about customizing notifications

The only way to tune an alarm is

- copy the alarm from stock dir to the user dir (there is `edit-config` helper script in the `/etc/netdata`)
- tune the alarm
- restart netdata service

If you want to disable an alarm

> you can disable an alarm notification by setting the 'to' line to: silent

**Comment by drayvs** [comment]
> > Another question I have is about customizing notifications
> 
> The only way to tune an alarm is
> 
> * copy the alarm from stock dir to the user dir (there is `edit-config` helper script in the `/etc/netdata`)
> * tune the alarm
> * restart netdata service
> 
> If you want to disable an alarm
> 
> > you can disable an alarm notification by setting the 'to' line to: silent

I am sorry if this is a stupid question, but where is "stock dir" on Ubuntu 18.04 ?

**Comment by ilyam8** [comment]
see

> https://learn.netdata.cloud/docs/agent/configuration-guide

---

i installed Netdata in `/opt`

in my case, stock dir is

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ ls /opt/netdata/usr/lib/netdata/conf.d/
apps_groups.conf  charts.d       ebpf_process.conf  go.d       health_alarm_notify.conf  health_email_recipients.conf  mongodb.conf  python.d       statsd.d
aws_kinesis.conf  charts.d.conf  fping.conf         go.d.conf  health.d                  ioping.conf                   node.d.conf   python.d.conf  stream.conf
```

user dir

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ ls /opt/netdata/etc/netdata/
apps_groups.conf  charts.d  charts.d.conf  claim.d  custom-plugins.d  edit-config  go.d  go.d.conf  health.d  netdata.conf  node.d  orig  python.d  ssl  statsd.d  stream.conf
```

**Comment by amoss** [comment]
@manos-saratsis / @dim08 This is a good idea. One way to achieve this would be to add an ACLK chart to the agent that shows the current connection state / usage and allow alarms to be defined on it.

**Comment by drayvs** [comment]
> see
> 
> > https://learn.netdata.cloud/docs/agent/configuration-guide
> 
> i installed Netdata in `/opt`
> 
> in my case, stock dir is
> 
> ```batchfile
> ilyam@debian-s-1vcpu-1gb-fra1-01:~$ ls /opt/netdata/usr/lib/netdata/conf.d/
> apps_groups.conf  charts.d       ebpf_process.conf  go.d       health_alarm_notify.conf  health_email_recipients.conf  mongodb.conf  python.d       statsd.d
> aws_kinesis.conf  charts.d.conf  fping.conf         go.d.conf  health.d                  ioping.conf                   node.d.conf   python.d.conf  stream.conf
> ```
> 
> user dir
> 
> ```batchfile
> ilyam@debian-s-1vcpu-1gb-fra1-01:~$ ls /opt/netdata/etc/netdata/
> apps_groups.conf  charts.d  charts.d.conf  claim.d  custom-plugins.d  edit-config  go.d  go.d.conf  health.d  netdata.conf  node.d  orig  python.d  ssl  statsd.d  stream.conf
> ```

Ok, sorry for long reply, I had to change server... Because old one was going unreachable for no apparent reason.
So you told me to copy alarm from stock, and tune it.

First question What is Alarm? I can only assume you talk about health_alarm_notify.conf
which I already have in /etc/netdata ( I had to set it up for my Telegram notifications).

But I don't see any mentions of "net_fifo.enp1s0" errors, how do I customise these notifications?

**Comment by ilyam8** [comment]
@drayvs 

> https://learn.netdata.cloud/docs/agent/health/reference#health-entity-reference

**Comment by drayvs** [comment]
@ilyam8 
Ok, i think I figured it out, I need to copy
/usr/lib/netdata/conf.d/health.d/net.conf
into
/etc/netdata/health.d/

And edit
# FIFO errors
As I see fit, then restart netdata service.

Did I get it right? And then I have to repeat this on every server.

**Comment by ilyam8** [comment]
> Did I get it right? And then I have to repeat this on every server.

Unfortunately yes

> I had problems finding where exactly fifo errors are configured, I had to copy all files and search their content... which was pretty annoying

Well, you choose some words from the alarm and then `grep <word> -R *` in the health.d  😄

**Comment by amoss** [comment]
@underhood - is it possible to set alarms on the new ACLK charts as that would be a better way of generating notifications that a server is unreachable?

**Comment by underhood** [comment]
@amoss - well they are the same charts like any other. Therefore it should be possible to set alarms on them.

However of course if ACLK goes offline then the notification will not reach the cloud. So if the feature requested here is cloud sending the notification we will have to implement something on cloud side.

**Comment by squash** [comment]
Just wanted to chime in that this feature (alerts for unreachable hosts) is the primary reason I'm still looking for a monitoring system. Subscribed to the bug hoping to hear some movement happening!

**Comment by manos-saratsis** [comment]
@drayvs @squash We will soon ship Centralized Alarm Notification in Netdata Cloud. Having notifications for unreachable hosts is a priority and will be shipped within the next days.

**Comment by manos-saratsis** [comment]
@drayvs @squash due to some issues, we will be releasing the feature soon

**Comment by drayvs** [comment]
@manos-saratsis did you release this feature yet? And can I get norifications via telegram that server "x" is unreachable?

**Comment by manos-saratsis** [comment]
@drayvs This feature is expected to go out next week. Initially you will receive notifications only via email. Later on more integrations will be added.

**Comment by rjbathgate** [comment]
@manos-saratsis - is there a 'new feature' email I can subscribe to (or similar?) as I'm really keen to use this once it's available, and also keep in loop going forward.

**Comment by manos-saratsis** [comment]
@rjbathgate please wait a couple of days and we will ship it. As an admin you will be able to allow email notifications for a space and all users will be able to manage the notifications they receive for every Space & War Room they are in.

**Comment by rjbathgate** [comment]
@manos-saratsis any update on this? Apologies if I'm being inpatient.
