### ISSUE TITLE
Add Netdata Static ARM builds (kickstart-static-arm)

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#9123]
ssia See [comment](https://github.com/netdata/netdata/issues/9055#issuecomment-632049417)

**Comment by Ferroin** [comment]
Just my opinions on this:

* For 32-bit ARM, we should only support EABI systems, not OABI (different kernel+libc ABI's, OABI has been deprecated for years now, but there are still some systems in the wild using it).
* There are 3 sub-architectures that I would say are worth supporting:
    * ARMv6: This gets us support for a number of older ARM systems. We should probably build it using softfloat instead of hardfp support, as that will get us the best portability.
    * ARMv7a: This gets us operational support on a vast majority of newer 32-bit ARM systems. A properly curated ARMv6 build _would_ run here, but ARMv7a was a significant performance boost over ARMv6 so it makes sense to have a separate build.
    * AArch64: Gets us newer ARM system support. Baseline ARMv8.1 is probably what we want here.

**Comment by prologic** [comment]
Fine. We should only start with work once we have access to ARM hardware virtual or bare-metal. THis reminds me to follow up with TerraSwitch who are poised to provide us with virtual ARM resources.

**Comment by Ferroin** [comment]
Not stale, just slow. This will be comming as part of an impending redesign our our packaging and installation options.

**Comment by prologic** [comment]
Not stale.

**Comment by prologic** [comment]
Not stale.

**Comment by bioshazard** [comment]
Very interested in armv6 builds for RPi Zero
