### ISSUE TITLE
Disable XHRs to github.com made by dashboard

### ISSUE THREAD

**Issue by nthuemmel** [netdata/netdata#9127]
Is there a way to disable the XHR sent to `https://api.github.com/repos/netdata/netdata/releases/latest` by the netdata dashboard? If not, would it be possible to add an option to do so?

Background: I'm running netdata behind another webserver which sets a fixed `Content-Security-Policy` header. This header forbids access to external sites. The connection attempts made by the netdata dashboard trigger CSP violation alerts. I cannot change the header to allow these connections.

**Comment by jacekkolasa** [comment]
@dim08 @cakrit currently we do this call to know if users have newest version. Do you think we should add an option in `netdata.conf` to disable that check?

**Comment by cakrit** [comment]
Sure, why not? Simple and effective.
