### ISSUE TITLE
Command to uninstall and to make sure none of your code is still on system?

### ISSUE THREAD

**Issue by superchap** [netdata/netdata#9133]
##### Question summary

I really wanted a real time network monitoring tool to see how much bandwidth (download) I was using at any given time. Netdata looked GREAT! Download for Linux Mint was going swimmingly. Unfortunately, I have ZERO interest in providing ANY DATA ('anonymous' or not) to Google. I tried to 'pass some code' or wuddever to avoid having any information go to Google Analytics and the whole instantly aborted. I don't want to give you any other 'environment' information for fear of you sharing (passing) it to Googel .. you know, the 'do no evil' gang. cough cough. Wholly livingphukk ! ARE YOU KIDDING ME? What command do I run in Linux Mint terminal to MAKE SURE ALL of your netdata code that was downloaded has been purged and that NONE of it remains. I'd use it if you could ensure me there was ZERO CHANCE of ANY of my system or computer usage information was being 'trasferred' or 'shared' or 'seen' or 'archived' by any thing any one any group yadda yadda. You get it. I've attached a screen shot and the terminal session. Please advise asap. TIA.
![Netdata terminal screen capture](https://user-images.githubusercontent.com/6477792/82627847-f7abc400-9bb0-11ea-9b32-96896dc7bf8d.png)
[Netdata.txt](https://github.com/netdata/netdata/files/4665890/Netdata.txt)

**Comment by prologic** [comment]
Hello @superchap 👋

I can only assume you installed Netdata like this:

```#!sh
bash <(curl -Ss https://my-netdata.io/kickstart.sh)   
```

if you look at the "Get Agent" section of our [website](https://www.netdata.cloud/#installation) you'll note the following options:

<img width="647" alt="Screen Shot 2020-05-25 at 15 59 15" src="https://user-images.githubusercontent.com/1290234/82782888-b3663f80-9ea0-11ea-8710-bee6336c9aea.png">

If you untick "Anonymous Statistics" you'll get a command you can copy/paste like so:

```#!sh
bash <(curl -Ss https://my-netdata.io/kickstart.sh)   --disable-telemetry
```

We also respect the `DO_NOT_TRACK` environment variable and if set to a non-zero length string will have the same effect.

----

If you still wish to uninstall Netdata; you _may_ do so with the uninstaller script which can be found normally (_by default_) at:

```#!sh
sudo /usr/libexec/netdata/netdata-uninstaller.sh -f -y
```

**Comment by superchap** [comment]
Thank you!
Appreciate the follow up.
Honorable.

**Comment by prologic** [comment]
You're welcome! Please let me know what you do so I can close this issue out. Otherwise feel free to ask more questions here I'll do the best I can to answer!

**Comment by superchap** [comment]
Please leave it with me James. I'll reconsider with the new information
you've provided.
https://youtu.be/_CWWkuz0u3s
