### ISSUE TITLE
Question: Long term health alarms

### ISSUE THREAD

**Issue by QuantumlyTangled** [netdata/netdata#9136]
##### Question summary

My question is, if it is possible to get metrics from the past weak and avg them out. If I can do that may I be pointed in the right direction? I get that I can set a check interval but if possible I would like to check every day for the last 9 days to average out the total bandwith use. Reason for that is Contabo's bandwith policy.

##### OS / Environment
Ubuntu 18.04

**Comment by thiagoftsm** [comment]
Hello @QuantumlyTangled ,

Take a look on this issue https://github.com/netdata/netdata/issues/8877, I am working with a person there that is monitoring the whole month of data, the user gave example of alarms that he is using. If this  cannot help you, please, let me know.

Best regards!

**Comment by Pingger** [comment]
Also keep in mind the pitfall I found: https://github.com/netdata/netdata/issues/8877#issuecomment-633162797
