### ISSUE TITLE
Can't be installed in China (one line installation script)

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#9138]
`raw.githubusercontent.com`, and `storage.googleapis.com` is unable to connect within china, I assume everyone knows the reason, so any plan to have a secondary repository to let the broader China users to enjoy the simplicity of one line installation script?

I tried other methods as well: rpm by package cloud, but it turns out the netdata.conf is different than the one line installation script.

For offline installation, tried without any luck, and it's a bit too much.

**Comment by prologic** [comment]
Duplicate of #8527

**Comment by startryst** [comment]
any new development/progress on this?
