### ISSUE TITLE
Services module and alarm

### ISSUE THREAD

**Issue by mo0nsniper** [netdata/netdata#914]
Good news everyone,

I have implemented a netdata module for systemd services.

Screenshot:
![capture](https://cloud.githubusercontent.com/assets/6639472/18338964/280e5d78-75a5-11e6-8e7e-13d8cb83d372.PNG)

Summary chart 
Lists the total number of running, dead, exited and failed services on the system.

Status chart
Lists the status of the services on the system. 
The values are: 
1=running, -2=dead, -3=exited, -4=failed.

I have tried to put the status for services 0,1,2,3 or 0,-1,-2,-3 but the 0 line wasn't shown.
Also tried 1,-1,-2,-3 but 1 and -1 were hard to distinguish in the legend.
If you have any suggestions about the values let me know.

Alarm
I also wanted to implement an alarm for when a service is in the failed status for more than one minute but I can't seem to make it work. Maybe someone could help me with it.

The files can be found in my forked repo of netdata: [here](https://github.com/mo0nsniper/netdata)
services.chart.sh plugin [here](https://github.com/mo0nsniper/netdata/blob/master/charts.d/services.chart.sh)
services.conf alarm [here](https://github.com/mo0nsniper/netdata/blob/master/conf.d/health.d/services.conf)

**Comment by mo0nsniper** [comment]
Could someone have a look over the alarm config and help me make it work?

Thank you.

**Comment by ktsaou** [comment]
The problem with this setup is that you get a dynamically generated set of dimensions. For each of this dimensions you will need an alarm. Unfortunately, I did not foresee this, so it is not supported at the moment. For all alarms, if you need to match a dimension, it has to be declared with the alarm.

So, to create a static alarm for dimension `XXX`, you would need something like this:

```
   alarm: 1min_XXX_alive
  lookup: max -1m unaligned of XXX
   every: 1m
    warn: $this < 1
```

The above gives the `max` value of XXX for the last minute. If it was running within the last minute, it will be 1, otherwise it will be reason of failure (-1, -2, etc).

**Comment by mo0nsniper** [comment]
Thanks ktsaou for your help, now the individual alarm is working.
Indeed individual alarms for services would be needed also.

Do you see any possibility to implement a check on all the chart dimmesions for making this work? And do you think this would be helpfull for other scenarios?

**Comment by ktsaou** [comment]
It could be useful in a few cases. But it requires quite some work. Templating requires handling overrides (i.e. apply this template to all dimensions except this one), uniqueness (do not add the same alarm twice), handle properly the case there dimensions are added while the chart is running, etc. So I have to re-model the internal structures somehow.

My main concern now is to centralize the alarms to a central netdata, much like the registry. So, don't expect any progress on this soon.

**Comment by ktsaou** [comment]
Also, I think the solution you have given is somewhat limited.

I think of extending apps.plugin to generate a specific set of charts for running applications. For example, if you say that you want to monitor mysqld, a new set of charts will be created monitoring everything related about mysqld (cpu, memory, swap, disk I/O, open files, sockets, pipes, number of processes, etc). This will allow a lot more checks to be made (i.e. alarms on memory leaks, memory size, disk I/O, etc per application).

Another solution could be to use the cgroups already created by systemd. Same idea: track everything from the cgroup metrics and apply alarms on them too. A special setting could select which of the cgroups you need and which you don't (to prevent adding thousands of charts - not that netdata will care, but all these charts will need memory).

**Comment by mo0nsniper** [comment]
It's good to know that the feature is planned and will be included. 
One way to implement an alarm in the current setup is to put it on the summary failed dimension.
This will generate an alarm when any service is in failed status but you don't know from the notification email which one. And a failed ntp is different from a failed mysqld let's say.

I think that monitoring the system services with the help of the system services manager (systemd or sysVinit) is better. It's a complete and cheap solution. Complete because you can monitor all the installed services without having to configure rules for each one. And cheap because all the rules for when a service is running or failed are in the service file (.unit file or init.d script)

Also when a service is not running there are more than one reason why and the services manager knows the status. Maybe the service process is not runing because the user has stopped the service (service mysql stop) or maybe the mysql process has died and the service is failed. I think is easier to rely on the services manager for knowing this.

**Comment by ktsaou** [comment]
@mo0nsniper the services manager knows that a service is either running or not running. It does not know if it is running but not working, or if it runs but is operating poorly.

I understand your need, but I still find it primitive. I will always prefer to collect metrics to verify that a service is working as expected.

**Comment by mo0nsniper** [comment]
Yes, knowing that a service is also working as expected is always better than the service status running. And I know that you will implement it :)

Also the method for monitoring by collecting metrics could take into account the service status. If it's stopped then it's ok that the process is not running or other metrics are missing.

**Comment by AckRiteris** [comment]
Your script would not be compatible with systems that do not use systemctl, so should it really be added to netdata? Not so sure. Wanted to thank you for it either way, adapted it for CentOS 6.7 :) Good work!

**Comment by mo0nsniper** [comment]
Hi @AckRiteris,

Yes, the script is based on systemd functionality, so it can't work without it. But many distributions use systemd now. 
About it being included @ktsaou can judge that.
I'm glad you found it useful.

Cheers

**Comment by ktsaou** [comment]
netdata now supports systemd services, by monitoring the relevant cgroups.

I am closing this, considering done. If you believe there is something missing, please post.

**Comment by adrfantini** [comment]
Sorry for posting on an old issue, and I'm not sure if this is related, but would it be possible to report service failures, issuing alarms for each failed service?

**Comment by mo0nsniper** [comment]
You can put an alarm for when the service status is failed (-4)

**Comment by adrfantini** [comment]
> You can put an alarm for when the service status is failed (-4)

Thanks. Would you be able to point me to some starting instructions on how to do this for all services at the same time? I do not want to monitor a specific service.

**Comment by cakrit** [comment]
You can  understand how alarms are configured by reading about [health monitoring](https://docs.netdata.cloud/health/)

**Comment by pjones** [comment]
I don't see the `services.status` chart in API variable list or the source code for netdata.  I have cgroup charts for memory usage, disk usage, etc. but no status variables.  Am I missing something?

**Comment by cakrit** [comment]
@pjones please open a new issue with the question, so we can help you there. You can refer to this one if you like.

**Comment by pjones** [comment]
@cakrit I'm happy to open a new issue, I'm just not sure if it should be a feature request or a bug.  Please answer this question to guide me:

Does netdata have a built in chart with the name `services.status` as mentioned in this issue that we can use to set alerts for when systemd services fail?

Thank you.

**Comment by mo0nsniper** [comment]
This is not included in netdata, you can find it in my forked repo here: https://github.com/mo0nsniper/netdata

**Comment by pjones** [comment]
@mo0nsniper Thank you.  This is what I was after.  Do you plan on opening a PR to get this included in netdata?

**Comment by adrfantini** [comment]
> This is not included in netdata, you can find the files in my forked repo here: https://github.com/mo0nsniper/netdata

Interesting, would you mind expanding on what would I need to pluck to add this feature to my netdata installation?

**Comment by mo0nsniper** [comment]
@pjones glad you find it usefull. There were discussions to have services monitored another way.

**Comment by mo0nsniper** [comment]
@adrfantini you need to install the services.chart.sh script from here: https://github.com/mo0nsniper/netdata/blob/master/charts.d/services.chart.sh in the charts.d folder in netdata

Optionally there is the alarm file from here https://github.com/mo0nsniper/netdata/blob/master/conf.d/health.d/services.conf to monitor failed services but when I wrote it you couldn't monitor all the services just individual ones. I don't know if that functionality has been included in netdata.

**Comment by pjones** [comment]
@mo0nsniper May I recommend that you open a PR so there is a clear location to discuss how to monitor systemd services.  Since this is a closed issue around cgroups I think a PR would be the best place to move the discussion.

Thank you very much.

**Comment by adrfantini** [comment]
> @adrfantini you need to install the services.chart.sh script from here: https://github.com/mo0nsniper/netdata/blob/master/charts.d/services.chart.sh in the charts.d folder in netdata
> 
> Optionally there is the alarm file from here https://github.com/mo0nsniper/netdata/blob/master/conf.d/health.d/services.conf to monitor failed services but when I wrote it you couldn't monitor all the services just individual ones. I don't know if that functionality has been included in netdata.

This is very helpful, it works wonderfully. Any way to integrate it inside the default "systemd Services" menu in the dashboard?

**Comment by It4lik** [comment]
Hi, 

I'd also like to see this feature implemented in Netdata. Monitoring systemd services at cgroup level is great for performance monitoring (ram, cpu, open files, etc) but is nearly irrelevant regarding systemd "oneshot" services. 
Oneshot services are services that expects the process to exit at some point. 

I recently wrap a backup script in a oneshot service. Metrics that I'd be interested in are exit code and execution time. 
It would be nice if Netdata was able to send an alert if this backups fails or take too much time.

**Comment by ilyam8** [comment]
i see the [script](https://github.com/mo0nsniper/netdata/blob/master/charts.d/services.chart.sh) does

> https://github.com/mo0nsniper/netdata/blob/master/charts.d/services.chart.sh

The command is not expensive

```
[ilyam@pc ~]$ time systemctl --no-legend --no-pager --plain --state=loaded --all --type=service 1>/dev/null

real	0m0,009s
user	0m0,004s
sys	    0m0,004s
```

So, if this feature is needed it is not hard to implement it in python or go. We can have it disabled by default. But at least people will be able to use it.

**Comment by Ferroin** [comment]
Just a thought, but monitoring for oneshot services might be a good fit for the event support being planned in #6523.

**Comment by Mic92** [comment]
Are dynamic alerts now supported? https://docs.netdata.cloud/health/tutorials/dimension-templates/#using-foreach-with-alarm-templates

I tried

```
 template: failed_services
       on: Services.status
       os: linux
   lookup: min -1m unaligned foreach *
    every: 1m
     crit: $this != -4
     info: service is failed
       to: sysadmin
```

but it does not seem to work :(

**Comment by Mic92** [comment]
The follwing works: 

```
    alarm: real_failed_services
       on: Services.status
       os: linux
   lookup: average -1m unaligned foreach *
    every: 1m
     crit: $this < -3
     info: service is failed
       to: sysadmin
```

**Comment by mo0nsniper** [comment]
Nice. Glad you made it to work.

**Comment by Mic92** [comment]
I rebased your branch to a current netdata revision: https://github.com/Mic92/netdata/tree/systemd

**Comment by scatenag** [comment]
I vote for integration in netdata Master release. :)

**Comment by ilyam8** [comment]
We added [Systemd units state](https://github.com/netdata/go.d.plugin/tree/master/modules/systemdunits#systemd-units-state-monitoring-with-netdata) collector and [alarms](https://github.com/netdata/netdata/blob/master/health/health.d/systemdunits.conf).

It collects Active state

> The active state (i.e. whether the unit is currently started or not)

If Sub state is important we can add it too. Feel free to request!

> The sub state (a more fine-grained version of the active state that is specific to the unit type, which the active state is not)
