### ISSUE TITLE
Monitoring Apache

### ISSUE THREAD

**Issue by Akkor70** [netdata/netdata#9142]
##### Question summary
Apache Monitoring
##### OS / Environment
Ubuntu Server 18.04
##### Expected results
Monitor Apache

I would like to monitor apache with netdata but I havent' found an example on how to
I try to follo the guide found under /etc/netdata/python.d/apache.conf but I'm not able to obtain the goal
Could You help me to correctly configure Netdata ?

**Comment by ilyam8** [comment]
Hi

check

> https://learn.netdata.cloud/docs/agent/configuration-guide

you need to copy apache.conf to use dir and configure a job

If there are any problems `python.d.plugin` has debug mode

> https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin#how-to-debug-a-python-module

**Comment by Akkor70** [comment]
Sorry but in wich path I have to copy apache.conf ? inside /etc/netdata ?
How to correctly edit apache.conf file to show apache charts in netdata ?

**Comment by ilyam8** [comment]
it is enabled, as i said, have you tried debug mode?

> https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin#how-to-debug-a-python-module

---

This is default configuration

https://github.com/netdata/netdata/blob/68c1145cb31e4ce4253ba9279283633b8b4f5c4e/collectors/python.d.plugin/apache/apache.conf#L75-L85

If you need to change something you need to cd `/etc/netdata` (the path depends on your install path) and

`./edit-config pyhton.d/apache.conf`

**Comment by ilyam8** [comment]
btw it is in the module readme

> https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/apache#configuration

**Comment by Akkor70** [comment]
I'm on Ubuntu server 18.04 and I don't have none of this path written in the debug

# execute the plugin in debug mode, for a specific module
/opt/netdata/...................
/usr/libexec/........................

**Comment by Akkor70** [comment]
Any help ?

**Comment by ilyam8** [comment]
Show debug mode output? It is impossible to help without it.

**Comment by Akkor70** [comment]
I have tryed to launch this debug command as netdata user and I have this output. What does it means ?

```
netdata@ubuntu:/root$ ./go.d.plugin -d -m apache
bash: ./go.d.plugin: Permission denied
```

**Comment by ilyam8** [comment]
cd to plugins.d and do `ls -l`

**Comment by Akkor70** [comment]
Do You need this ?

```
root@ubuntu:/etc/netdata/python.d# ls -l
total 180
-rwxr-xr-x 1 netdata netdata 2883 May 24 19:23 apache.conf
-rwxr-xr-x 1 netdata netdata 3223 Jan 27  2018 beanstalk.conf
-rwxr-xr-x 1 netdata netdata 3915 Jan 27  2018 bind_rndc.conf
-rwxr-xr-x 1 netdata netdata 2914 Jan 27  2018 chrony.conf
-rwxr-xr-x 1 netdata netdata 3387 Jan 27  2018 couchdb.conf
-rwxr-xr-x 1 netdata netdata 1494 Jan 27  2018 cpufreq.conf
-rwxr-xr-x 1 netdata netdata 3049 Jan 27  2018 dnsdist.conf
-rwxr-xr-x 1 netdata netdata 2889 Jan 27  2018 dns_query_time.conf
-rwxr-xr-x 1 netdata netdata 3082 Jan 27  2018 dovecot.conf
-rwxr-xr-x 1 netdata netdata 3167 Jan 27  2018 elasticsearch.conf
-rwxr-xr-x 1 netdata netdata 2635 Jan 27  2018 example.conf
-rwxr-xr-x 1 netdata netdata 3228 Jan 27  2018 exim.conf
-rwxr-xr-x 1 netdata netdata 3066 May 28 11:01 fail2ban.conf
-rwxr-xr-x 1 netdata netdata 3736 Jan 27  2018 freeradius.conf
-rwxr-xr-x 1 netdata netdata 4108 Jan 27  2018 go_expvar.conf
-rwxr-xr-x 1 netdata netdata 3060 Jan 27  2018 haproxy.conf
-rwxr-xr-x 1 netdata netdata 3182 Jan 27  2018 hddtemp.conf
-rwxr-xr-x 1 netdata netdata 2727 Jan 27  2018 ipfs.conf
-rwxr-xr-x 1 netdata netdata 3255 Jan 27  2018 isc_dhcpd.conf
-rwxr-xr-x 1 netdata netdata 1162 Jan 27  2018 mdstat.conf
-rwxr-xr-x 1 netdata netdata 3014 Jan 27  2018 memcached.conf
-rwxr-xr-x 1 netdata netdata 3129 Jan 27  2018 mongodb.conf
-rwxr-xr-x 1 netdata netdata 7583 May 24 19:16 mysql.conf
-rwxr-xr-x 1 netdata netdata 3586 Jan 27  2018 nginx.conf
-rwxr-xr-x 1 netdata netdata 3332 Jan 27  2018 nsd.conf
-rwxr-xr-x 1 netdata netdata 3848 Jan 27  2018 ovpn_status_log.conf
-rwxr-xr-x 1 netdata netdata 3102 Jan 27  2018 phpfpm.conf
-rwxr-xr-x 1 netdata netdata 2701 Jan 27  2018 postfix.conf
-rwxr-xr-x 1 netdata netdata 3848 Jan 27  2018 postgres.conf
-rwxr-xr-x 1 netdata netdata 2900 Jan 27  2018 powerdns.conf
-rwxr-xr-x 1 netdata netdata 3040 Jan 27  2018 rabbitmq.conf
-rwxr-xr-x 1 netdata netdata 3394 Jan 27  2018 redis.conf
-rwxr-xr-x 1 netdata netdata 2741 Jan 27  2018 retroshare.conf
-rwxr-xr-x 1 netdata netdata 2400 Jan 27  2018 samba.conf
-rwxr-xr-x 1 netdata netdata 2013 Jan 27  2018 sensors.conf
-rwxr-xr-x 1 netdata netdata 4388 Jan 27  2018 smartd_log.conf
-rwxr-xr-x 1 netdata netdata 4783 Jan 27  2018 squid.conf
-rwxr-xr-x 1 netdata netdata 3220 Jan 27  2018 tomcat.conf
-rwxr-xr-x 1 netdata netdata 2480 Jan 27  2018 varnish.conf
-rwxr-xr-x 1 netdata netdata 6881 Jan 27  2018 web_log.conf
```

**Comment by ilyam8** [comment]
> /usr/lib/x86_64-linux-gnu/netdata/plugins.d

how did you install netdata? what is your netdata versrion?

**Comment by Akkor70** [comment]
I installed with default ubuntu/debian command apt install netdata

netdata 1.9.0

**Comment by ilyam8** [comment]
1.9.0 is ancient, latest is 1.22.1

remove it using your package manager

Install latest

> https://learn.netdata.cloud/docs/agent/packaging/installer

**Comment by Akkor70** [comment]
Installed .....now I see fail2ban monitor but nothing about apache

**Comment by ilyam8** [comment]
Can you get data from `http://127.0.0.1/server-status?auto` ?

default job uses that address

**Comment by Akkor70** [comment]
ok solved.....find a vhost that was obfuscating server status
Thanks
