### ISSUE TITLE
Adding Raspberry Pi CPU temp sensor graph to custom webpage

### ISSUE THREAD

**Issue by rjsears** [netdata/netdata#9144]
I have setup Netdata to see my Raspberry Pi temps on my main page as well as the netdata.cloud view of my Pi. However when I attempt to add it to a small custom page, it fails and shows "No Data" instead of the graph

I pulled the data-netdata line (`<div data-netdata="sensors.temp_thermal_zone0_thermal_thermal_zone0"`) directly from my dashboard and any change to it results in the "chart not found on URL" error. This just shows "empty" or "no data" depending on which chart I try to use. 

            <div data-netdata="sensors.temp_thermal_zone0_thermal_thermal_zone0"
            data-dimensions="user"
            data-chart-library="dygraph"
            data-width="150px"
            data-after="-60"
            data-points="60"
            data-title="Pi CPU Temp"
            data-units=""
            data-colors="#FF5555"
            ></div>

I used this as a guide:

https://learn.netdata.cloud/docs/agent/web/gui/custom/

##### OS / Environment
Raspberry Pi4 running Netdata 1.22.1.104

**Comment by rjsears** [comment]
Bump....

**Comment by ilyam8** [comment]
@rjsears perhaps chart or dimension ir wrong?

Check the chart/dimension via http api

> https://editor.swagger.io/?url=https://raw.githubusercontent.com/netdata/netdata/master/web/api/netdata-swagger.yaml


>  `curl -X GET "http://HOST/api/v1/chart?chart=CHART" -H "accept: application/json"`
