### ISSUE TITLE
cant uninstall 64bit netdata that was installed via kickstart

### ISSUE THREAD

**Issue by StaticReality** [netdata/netdata#9145]
##### Question summary
I installed and been updating 64bit netdata via kickstart
`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`
current netdata version installed: v1.22.1-109-gaf1aecea

I want to remove all of netdata and use the RHEL repo instead to manage / update the install. When I looked up the uninstall method:
https://learn.netdata.cloud/docs/agent/packaging/installer/uninstall/
it mentions to look for /etc/netdata/ but this does not appear when I'm looking for it:
```
┌─[root@gsm4]─[~]
└──╼ # ls -la /etc/net*
-rw-r--r-- 1 root root 767 Aug  8  2019 /etc/netconfig
-rw-r--r-- 1 root root  58 Mar 31 21:50 /etc/networks
```
I believe this is a result of me installing the 64bit version of netdata as I dont have this issue on another centos7 server with 32bit netdata being installed.

##### OS / Environment
centos7
```
┌─[root@gsm4]─[~]
└──╼ # cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
```
##### Expected results
https://learn.netdata.cloud/docs/agent/packaging/installer/uninstall/
does not work with 64bit of netdata

**Comment by prologic** [comment]
You need only do two things:

1. Stop Netdata with e.g: `sudo systemctl stop netdata`
2. Remove Netdata with e.g: `sudo rm -rf /opt/netdata`

This is the only place where Netdata static installs itself to via `kickstart-static64.sh`

Alternatively the uninstallation scripts _always_ work regardless of installation method:

```#!sh
prologic@ubuntu2004:~$ sudo /opt/netdata/usr/libexec/netdata/netdata-uninstaller.sh --help
netdata-uninstaller.sh [-h] [-f ] -- program to calculate the answer to life, the universe and everything

where:
    -e, --env    path to environment file (defauls to '/etc/netdata/.environment'
    -f, --force  force uninstallation and do not ask any questions
    -h           show this help text
    -y, --yes    flag needs to be set to proceed with uninstallation
prologic@ubuntu2004:~$ sudo /opt/netdata/usr/libexec/netdata/netdata-uninstaller.sh -f -y
Stopping a possibly running netdata...
.
.
.
```

**Comment by prologic** [comment]
If you have any further queries please don't hestitate to ask!
