### ISSUE TITLE
question - how to setup netdata for mutiple domain

### ISSUE THREAD

**Issue by patidarashok** [netdata/netdata#9149]
Hello, 

I installed netdata on ubuntu 16.04 for getting insight of nginx 
I can see nginx.local over the dashboard. 

I have setuped 5 different virutal host on  /etc/nginx/site-availbe/1.conf 2.conf 3.conf etc. 
and setup separate access/error log for each domain, which is written in /var/log/nginx

My Question/issue is
I cant see separate error logs of each domain and i also want to get error logs in detail not number. Like if i need to download so i can easily get it.  

If i doing something wrong please let me know, here i am very new.

**Comment by gilwi** [comment]
Hello,
I'm willing to help, so I'll try reproduce your setup and see if I can help.
It would be kind to:
 - tell how you installed netdata on your ubuntu instance (git clone, script, apt)?
 - be more specific when you describe your problem (`/etc/nginx/site-availbe/1.conf` has some typos I guess)
For that last point, can you please execute these commands and post your outputs (of course replace anything you think is sensitive information):
 - `ls -l /etc/nginx/`
 - `ls /etc/nginx/sites-enabled` 
 - `nginx -V`
Cheers
