### ISSUE TITLE
CentOS 6.x via kickstart has no cloud support

### ISSUE THREAD

**Issue by zack-shoylev** [netdata/netdata#9152]
##### OS / Environment
CentOS 6

##### Netdata version
netdata v1.22.1-96-nightly
Installed via kickstart script

##### Component Name
Cloud claiming not working - agent built without cloud dependencies

##### Steps To Reproduce
Use kickstart script to install agent on centos 6
copy-and-paste claim command
> This agent was built without the dependencies for Cloud and cannot be claimed

##### Expected behavior
Claiming should work when agent is installed via kickstart script

**Comment by mvmagalhaes** [comment]
This agent was built without the dependencies for Cloud and cannot be claimed - centos6

**Comment by underhood** [comment]
@zack-shoylev by kickstart you mean regular one or `kickstart-static64`?

**Comment by underhood** [comment]
I think this one should be solved by 1ac12904b0697f1a3131af2f9ed3addc6b396ad9
