### ISSUE TITLE
CentOS 7 no metrics displayed for nodes

### ISSUE THREAD

**Issue by zack-shoylev** [netdata/netdata#9153]
##### Bug report summary
Nodes do not load any metrics

##### OS / Environment
CentOS 7

##### Netdata version
Agent v1.22.1-96-nightly 

##### Component Name
Cloud

##### Steps To Reproduce
Claim 5 CentOS 7 nodes in the same space
Only one of them shows any metrics

##### Expected behavior
Metrics should be displayed for all nodes

also see https://netdata.zendesk.com/agent/tickets/111

**Comment by underhood** [comment]
@zack-shoylev did you clone VM? does each node have unique id different from the other ones?

Can you check `cat /var/lib/netdata/registry/netdata.public.unique.id` *(or equivalent dir if you installed into prefix)*

**Comment by underhood** [comment]
@zack-shoylev, I cannot access the zendesk, can you provide any more details? It sounds like the case of duplicated netdata ids? Could it be? Do we have any information to support or dismiss this?

**Comment by zack-shoylev** [comment]
Similar in https://netdata.zendesk.com/agent/tickets/144

Deleted war room, reclaimed nodes, but metrics are missing.

**Comment by zack-shoylev** [comment]
I do not believe either case had anything to do with VM cloning or similar.

**Comment by underhood** [comment]
@zack-shoylev can you send me the info from zendesk i do not have access.
@cakrit should i have access for zendesk?

**Comment by zack-shoylev** [comment]
Sorry for the delay, this was traces to the 500 errors/server side problems, which should be now resolved.
