### ISSUE TITLE
Working modules stopped working.

### ISSUE THREAD

**Issue by penguennoktanet** [netdata/netdata#9159]
### Question summary
I was using netdata with prometheus and grafana for last 2 months. Suddenly this morning 2 of my netdata started to behave strangely.

1 of the netdata stopped spooling apache2 data. I debugged the apache module with debug and everything seems fine (/usr/libexec/netdata/plugins.d/python.d.plugin apache debug trace). Also on error log, notting seems relevant about apache exists. (Some "Cannot process /proc/|pid|/io (command 'apache2') (errno 13, Permission denied)" messages occurs but it's a busy web server). But when I looked up netdata page or "allmetrics api output", I can not see any apache lines.

On the other hand, the second netdata runs 2 modules (written by me. Simply counts files on folders). Same as apache problem, when I debug run the scripts, it runs smoothly. But "allmetric api" output does not include any information.

I checked "pyhton.d.conf" and "default_run" is yes.

Any ideas?

**Comment by stelfrag** [comment]
Hi @penguennoktanet, you do not mention the version you are using, but most likely you are affected by #9156. You can view that issue for more details. 

A fix has been applied to master.

**Comment by penguennoktanet** [comment]
> Hi @penguennoktanet, you do not mention the version you are using, but most likely you are affected by #9156. You can view that issue for more details.
> 
> A fix has been applied to master.

Yes, you are right. This is why I hate auto updates. :) I did not realized it is auto-updated too. I revert with  "bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel" to 1.22.1 and problem is gone.

Thanks for the help..
