### ISSUE TITLE
Switching from nightly to stable releases

### ISSUE THREAD

**Issue by Dmitry-SoftServe** [netdata/netdata#9160]
##### Question summary
Hello. Is it possible to switch from nightly to stable releases without netdata reinstall?
##### OS / Environment
Ubuntu 16.04

**Comment by prologic** [comment]
Hello! A Netdata reinstall is mostly equivalent to an update. Recommend you backup your `/etc/netdata` first with `cp -a ...` first; but if you just run `kickstart.sh` with the appropriate options you should be fine.
