### ISSUE TITLE
Plugins no longer generating charts

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#9166]
##### Question summary
I lost all of my charts today except for the ones generated by the Netdata Internal Plugin.
I didn't know if this had anything to do with the new nightly build or something else.
I initially thought it might be a problem with not enough file descriptors but I checked:
`sysctl fs.file-nr`
`fs.file-nr = 4000	0	1598778`
That looks like I have plenty of file descriptors not in use.
Then I changed from my memory mode from `dbengine` to `memory mode = ram` but that didn't help either.
When I run a debug on any of the modules for any collector they show no problems.
I'm getting the following errors in my error logs:

> 2020-05-26 10:30:26: ebpf.plugin ERROR : MAIN : [EBPF_PROCESS] Cannot load /usr/libexec/netdata/plugins.d/libnetdata_ebpf.so.4.16.18 default library. (errno 2, No such file or directory)
> 2020-05-26 10:30:26: ebpf.plugin ERROR : MAIN : [EBPF_PROCESS] Cannot load library.
> 2020-05-26 10:30:26: netdata ERROR : PLUGINSD[ebpf] : read failed: end of file (errno 9, Bad file descriptor)
> 2020-05-26 10:30:26: netdata ERROR : PLUGINSD[ebpf] : '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 5894) disconnected after 0 successful data collections (ENDs).
> 2020-05-26 10:30:26: netdata ERROR : PLUGINSD[ebpf] : child pid 5894 exited with code 3.
> 2020-05-26 10:30:26: netdata ERROR : PLUGINSD[ebpf] : '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 5894) exited with error code 3 and haven't collected any data. Disabling it.
> 2020-05-26 10:30:26: ebpf_process.plugin ERROR : MAIN : [EBPF PROCESS] setrlimit(RLIMIT_MEMLOCK) (errno 1, Operation not permitted)
> 2020-05-26 10:30:26: netdata ERROR : PLUGINSD[ebpf_process] : read failed: end of file (errno 9, Bad file descriptor)
> 2020-05-26 10:30:26: netdata ERROR : PLUGINSD[ebpf_process] : '/usr/libexec/netdata/plugins.d/ebpf_process.plugin' (pid 5899) disconnected after 0 successful data collections (ENDs).
> 2020-05-26 10:30:26: netdata ERROR : PLUGINSD[ebpf_process] : child pid 5899 exited with code 2.
> 2020-05-26 10:30:26: netdata ERROR : PLUGINSD[ebpf_process] : '/usr/libexec/netdata/plugins.d/ebpf_process.plugin' (pid 5899) exited with error code 2 and haven't collected any data. Disabling it.
> 2020-05-26 10:30:26: netdata ERROR : MAIN : This agent doesn't have ACLK.
> 2020-05-26 10:30:27: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 5893) disconnected after 0 successful data collections (ENDs). (errno 9, Bad file descriptor)
> 2020-05-26 10:30:27: netdata ERROR : PLUGINSD[go.d] : child pid 5893 killed by signal 15.
> 2020-05-26 10:30:27: netdata ERROR : PLUGINSD[charts.d] : '/usr/libexec/netdata/plugins.d/charts.d.plugin' (pid 5895) disconnected after 0 successful data collections (ENDs). (errno 9, Bad file descriptor)
> 2020-05-26 10:30:27: netdata ERROR : PLUGINSD[python.d] : '/usr/libexec/netdata/plugins.d/python.d.plugin' (pid 5904) disconnected after 0 successful data collections (ENDs). (errno 9, Bad file descriptor)
> 2020-05-26 10:30:27: netdata ERROR : PLUGINSD[python.d] : child pid 5904 killed by signal 15.
> 2020-05-26 10:30:37: netdata ERROR : PLUGINSD[charts.d] : '/usr/libexec/netdata/plugins.d/charts.d.plugin' (pid 6116) disconnected after 0 successful data collections (ENDs). (errno 9, Bad file descriptor)
> 2020-05-26 10:30:47: netdata ERROR : PLUGINSD[charts.d] : '/usr/libexec/netdata/plugins.d/charts.d.plugin' (pid 6207) disconnected after 0 successful data collections (ENDs). (errno 9, Bad file descriptor)
> 2020-05-26 10:30:57: netdata ERROR : PLUGINSD[charts.d] : '/usr/libexec/netdata/plugins.d/charts.d.plugin' (pid 6294) disconnected after 0 successful data collections (ENDs). (errno 9, Bad file descriptor)

##### OS / Environment
Netdata:    v1.22.1-123-nightly
OS:         Ubuntu 18.04.4 LTS (bionic)
Kernel:     4.15.0-101-generic
Apache:     2.4.29
PHP-fpm:  7.2.24
Netdata running as a unix socket on reverse proxy through Apache
##### Component Name
plugins.d/charts.d.plugin
plugins.d/python.d.plugin
plugins.d/go.d.plugin

##### Expected results
Charts should be created for all the collectors.

**Comment by stelfrag** [comment]
Hi @Steve8291. Thank you very much for the report. Unfortunately you are affected by  #9156. You can view that issue for more details.

A fix has been applied to master.
