### ISSUE TITLE
WMI exporter not working with Netdata

### ISSUE THREAD

**Issue by zack-shoylev** [netdata/netdata#9167]
##### Bug report summary
Could not get the WMI exporter to work with Netdata as per https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi/

##### OS / Environment
Ubuntu 18.04.4 LTS

##### Netdata version
v1.22.1-104-nightly 

##### Component Name
WMI Exporter

##### Steps To Reproduce
Install WMI exporter on monitored machine
Configure Netdata machine go.d/wmi.conf with edit-config

##### Expected behavior
WMI Exporter should be detected by Netdata

**Comment by ilyam8** [comment]
Hi @zack-shoylev 

There is debug mode

> https://github.com/netdata/go.d.plugin/tree/master/modules/wmi#troubleshooting

Have you tried it? The problem should be clear from the output. If it is not - share debug output.

**Comment by steenh65** [comment]
Hi Zack,
Here is the files that you ask for:
[error.log.2.gz](https://github.com/netdata/netdata/files/4684153/error.log.2.gz)
[error.log](https://github.com/netdata/netdata/files/4684154/error.log)
[wmi.txt](https://github.com/netdata/netdata/files/4684193/wmi.txt)

Best Regards,

Steen

**Comment by ilyam8** [comment]
hi @steenh65 

see my post above

> https://github.com/netdata/netdata/issues/9167#issuecomment-634176299

---

From the error log

```cmd
2020-05-26 17:57:18: go.d INFO: main[main] loading 'wmi' configuration
2020-05-26 17:57:18: go.d ERROR: main[main] skipping 'wmi': yaml: unmarshal errors:
  line 20: cannot unmarshal !!str `update_...` into orchestrator.moduleConfig
```

It means there is error in your `wmi.conf` - it is in [YAML](https://yaml.org/) format.

There is online YAML syntax validator

> https://codebeautify.org/yaml-validator

**Comment by ilyam8** [comment]
This error is configuration syntax error.

However there were breaking changes in `wmi_exporter` v0.13.0

> https://github.com/prometheus-community/windows_exporter/releases/tag/v0.13.0

It is no longer `wmi_exporter`, it is `windows_exporter` since v0.13.0.

Sync with upstream was added in https://github.com/netdata/go.d.plugin/pull/394

It is not in netdata v1.23.0, will be in the new go.d.plugin release
