### ISSUE TITLE
OVS and DPDK in Netdata

### ISSUE THREAD

**Issue by MuhammadMunir12** [netdata/netdata#9184]
##### **Question summary** 
I was looking for a plugin that can help getting stats of OVS (open virtual switch) and DPDK (data plane development kit). I couldn't find any collector(internal or external) that supports these two.
Is there any other way to integrate these two with Netdata using available plugins? Or we have to write a custom plugin? If yes, then how it can be done?

##### **OS / Environment**
Centos 7, Ubuntu 18.04

##### **Component Name**
OVS, DPDK

##### **Expected results**
Metrics and KPIs investigation

**Comment by ilyam8** [comment]
hi @MuhammadMunir12 

There is no such collectors, yes.

It looks like we can use this library to get ovs stats

> https://github.com/digitalocean/go-openvswitch/

stats
- https://github.com/digitalocean/go-openvswitch/blob/8ce3b42187295b76795386bf309a9ee49c5d9ad1/ovsnl/datapath.go#L77-L88

- https://github.com/digitalocean/go-openvswitch/blob/8ce3b42187295b76795386bf309a9ee49c5d9ad1/ovsnl/datapath.go#L90-L97

**Comment by MuhammadMunir12** [comment]
Hey, @ilyam8 
Thank you for your response. 

As you mentioned the library to use for getting ovs stats, let me check if I can get any outcome from this, otherwise i would have to wait for its collector from Netdata or anyone who has written its collector.  

Anyways, thanks.

**Comment by ilyam8** [comment]
> let me check if I can get any outcome from this

Yeah, check it, interface is pretty simple

https://github.com/digitalocean/go-openvswitch/tree/master/ovsnl#ovsnl

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
