### ISSUE TITLE
using backends for long term storage

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#9187]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#131](https://netdata.zendesk.com/agent/tickets/131)
**Group:** Support
**Requester:** sk@rose.dental
**Assignee:** Zack
**Issue escalated by:** Christopher Akritidis

**Original ticket description:**

<blockquote><div class="zd-comment zd-comment-pre-styled" dir="auto"><div dir="ltr">hi,<div><br></div><div>i configured a graphite&nbsp;backend to store the metrics. but it seems something does not work. how can i debug if the data is flowing to the backend? in my case the backend is a local carbon-relay-ng (graphite).</div><div><br></div><div>thanks&nbsp;for your help</div><div><br></div><div>sebastian<br><br><div><br></div>-- <br><div dir="ltr"><div dir="ltr">Sebastian Krämer<div>CTO</div><div><br></div><div>rose GmbH</div><div>Vaalser Str. 259<br></div><div>52074 Aachen</div></div></div></div></div></div></blockquote>

**Comment by thiagoftsm** [comment]
@vlvkobal I think we could answer this question given instructions to configure the exporting.

**Comment by vlvkobal** [comment]
The question was
> how can I debug if the data is flowing to the backend?

`nc -l -p 2003`

**Comment by cakrit** [comment]
*Comment made from Zendesk by Zack on 2020-05-27 at 18:31:*

<blockquote><div class="zd-comment" dir="auto">Hello Sebastian!<br><br>Please have a look at <a href="https://github.com/netdata/netdata/issues/9187" rel="noreferrer">https://github.com/netdata/netdata/issues/9187</a><br></div></blockquote>

**Comment by dotob** [comment]
thanks a lot. netdata does send...so it must be something different.
