### ISSUE TITLE
Server type indication to adapt default alarms thresholds

### ISSUE THREAD

**Issue by fayak** [netdata/netdata#9197]
##### Context/Problem

I really appreciate netdata and its way of working, however there's something that bother me every time I deploy it to a new infra. All the default alarms make a lot of sense, but they don't take into account the kind of server there are deployed into. I have to trick using ansible the alarm configuration and threshold to avoid being flooded by alarms that may be too sensitive.

For example, I often have a dedicated server for CI jobs, running gitlab-ci with docker. Every time a job is being pulled by gitlab-CI, the CPU goes up to 100%, the system is heavily loaded, but it's working fine and it is expected behaviour. However, I receive almost every time multiple alerts from netdata with "last collected: 10s". Having my database server too loaded to answer is 10s is an issue, my CI worker isn't.

##### Solution

That's why I would love to have some kind of indication of the kind of server netdata is being deployed to, to adapt the default alarm thresholds. What's naturally coming to my mind would be the following:
- `gate`, with higher thresholds on alarms related to network. Indeed, a gateway, being exposed to internet, frequently gets flooded for few seconds by incoming traffic, etc.
- `CI`, where things like CPU usage, last collected, etc would be less important since high-load peaks are expected and normal
- `database` with adapted thresholds for things like I/O or latency
- ...

Such "kind of server" information could be set during the installation, maybe with a flag, or in the `netdata.conf` under the `[global]` section, with something like
```
[global]
    server_kind = CI # Can be "default", "CI", "DB", .... see [doc](link to doc)
```

Such solution would reduce the burden to configure alarms for specific hosts.

This is an idea that came to me while spending quite some time increasing the alarms thresholds on many of my servers, this may not be the best solution for this problem. Feel free to add your opinion, or to tell me to piss off if it's not a good idea or too complicated to implement.

#### Expected behaviour

Easily set the kind of server and receive less false-alarms due to thresholds too strict.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
