### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by cosminilie** [netdata/netdata#92]
I noticed your project today and it seems very nice with lots of great features (liked a lot the very simple plugin system) but the main issue for us is that we have also windows servers. 

Is a windows port being planned or in the roadmap?

Our long term idea is to integrate one of these real time systems with prometheus (https://prometheus.io) for long time statistical storage and this can be done nicely with the API.

**Comment by Kubuxu** [comment]
It would require total rewrite of almost everything apart from the web UI. I don't think it is/will be planned.

**Comment by xitude** [comment]
It could work with the new Linux for Windows 10 integration.
http://www.theverge.com/2016/3/30/11331014/microsoft-windows-linux-ubuntu-bash

**Comment by ktsaou** [comment]
Hm... there could be a windows plugin to collect metrics through WMI.

netdata itself is not very linux specific. It needs POSIX and it has a lot of linux specific data collectors (which can be removed), but I think it shouldn't be so hard to port it, given that someone knows how to write a windows service in C and a data collector for WMI.

**Comment by seanvree** [comment]
Hate to reopen this issue, but has there been any movement on getting Windows support?

**Comment by philip-ulrich** [comment]
I have to agree with @ktsaou. It's definitely that outlandish of an idea to get this on Windows and it shouldn't really be too hard. I don't do Windows dev, but unfortunately work with Windows a lot. There is a large audience that this could benefit if there is a windows app made.

**Comment by MartynKeigher** [comment]
I stumbled upon this project about 5 days ago and so far so VERY VERY good. I have a mix of both Linux and Windows systems under management (most being Windows) and a Windows agent for netdata would be simply amazing!!

I am planning on 2 different 'mini projects': 

1. Getting netdata on all my linux-based servers & then pumping the data into graphite (as shown here: https://github.com/firehol/netdata/wiki/netdata-backends)
2. Netdata on a Pi. (Mostly Pi3, but i still do have several Pi2's out there).

Sadly, the dev of the Windows 'plugin' and/or 'agent' is way beyond my skillset - so I'll wait patiently like the rest of the peeps on this thread. To echo both @seanvree and @philip-ulrich above... has any movement happened on that project at all??

Keep up the awesome work on this project!! I genuinely believe that this is going to replace our mix/mash of so many different products. So SO awesome!!! The Windows agent would just be the icing on the cake!!

I also see that you can spit alerts out to Slack too!! Yet another HUGE +1 for you guys on that one!! :) 

Regards,

Martyn.

**Comment by seanvree** [comment]
All,

So I FINALLY got my Grafana install up and running on my Windows 10 box.  (It's not easy as all these apps are designed for linux)  So, I got Grafana working, InfluxDB all working as windows native services without having to run VMs.  So, I'll re-look at getting this to work.

If anyone is using Grafana/Graphite in Windows I'd love to talk about getting this stuff to work. 

I'm pretty good at getting python based applications working in Windows.  

I plan on doing some work on it tonight (Dec 20th)

Cheers 

eanvree@hotmail.com

**Comment by khannz** [comment]
Hello, everyone. Can you please explain a bit for me (too late, not perfect docs and so on, sorry), how exactly netdata works?

- Does it heave any central app, that collects everything from agents/collectors/whatever?
- It makes some cluster-like stuff with each node where general code runs to exchange with collected data and present it on any node via web iface?
- It have some other approach?

Asking all of it here since I'm wondering, how I can help to make it work on Windows platform - my situation is almost like @philip-ulrich described above 😒

**Comment by ktsaou** [comment]
Hi @khannz .

netdata supports all possible setups: autonomous collector/dashboard, headless data collector, proxy, store and forward proxy, central node, etc.

To support another system it is pretty simple. Internally it has multiple layers. For any POSIX compliant system, only the data collection layer needs to ported. Check for example the freebsd, or macos layers.

I can also abstract various common POSIX functions. I have already moved all locks to a separate layer, I can also move pthreads and probably more POSIX functions.

So, if you can write a data collection layer for WMI, I can abstract everything else to make it simpler for the whole system to work on windows.

**Comment by khannz** [comment]
@ktasou, great thanks for explanation! So 'realtime' data flow is not necessary (hey, we are talking about windows)? WMI/Powershell checks that occurs more often than 1/sec for let's say 500-700 metrics can generate serious load :/

So can I guess, there is no rules for checks frequency?

**Comment by ktsaou** [comment]
> So can I guess, there is no rules for checks frequency

In netdata, yes there are, both globally and per module. We already do this for several "slow" modules.

**Comment by SyFry** [comment]
I second the idea for a windows collector/agent.  Realtime high resolution metrics isn't a requirement for me at least.

**Comment by EatonZ** [comment]
A blogger I follow advertised this and it looked amazing. Was sad to find out there isn't any Windows support when I went to download. ):

+1 for Windows support!

**Comment by apg007** [comment]
Here's an open source data collector that has a WMI plugin. 
https://github.com/bloomberg/collectdwin

**Comment by botzill** [comment]
Hey guys!

Any examples/guide on how can we integrate that with netdata?

**Comment by BrickerBrickerOneNine** [comment]
I would LOVE windows support. omg.

**Comment by jLynx** [comment]
I would just like to point out that you can gets all the same data from WMI and with the program called AIDA64, you can get even more information, like fan speeds, temperatures, CPU utilization per core etc etc. Basically anything under the sun.

I think that if there was is an easy way to select WMI and then map those items the the existing items on the dashboard then this could be a near perfect solution

**Comment by Ferroin** [comment]
The biggest issue is not data collection, that's easy (most of the generic Python plugins should work out of the box, and it shouldn't be too hard to abstract away the dependence on `/proc` in most of the core stuff), it's the fact that Windows is not POSIX (and in some cases has drastically different semantics from POSIX, with the VFS interface and the process creation semantics being prime examples), and writing services for Windows is not exactly easy (and for Netdata to be practical for Windows, it has to be able to run as a service).

**Comment by businessportal** [comment]
Why would one want to do a superb job such as netadata within a windows environment? The only good metric of a windows machine is "Crashed" "NotCrashed"

**Comment by VSG24** [comment]
I'd like a windows port as well.

**Comment by Daniel15** [comment]
I'd also love to see Windows support. Most of my servers are Linux, but I do have a few running Windows Server 2016. Windows Subsystem for Linux isn't doable as it's not supported on Server 2016.

**Comment by cakrit** [comment]
Windows support is expected in 2019, with the first step being the change to use libuv (#2637). Unfortunately we can't be more specific than that right now, but it is definitely on our roadmap.

**Comment by Daniel15** [comment]
Sounds great!

This project might be good inspiration for the data collection side of things: https://github.com/martinlindhe/wmi_exporter

**Comment by ktsaou** [comment]
Actually, we could use `wmi_exporter` before we have our own windows version. We are building a prometheus / openmetrics scraper in netdata, so we could collect windows metrics with that...

**Comment by marcoslonggo** [comment]
That would be amazing. Having windows monitoring is what is stopping us today to get netdata as the de-facto monitoring solution for our corporation.

**Comment by BrickerBrickerOneNine** [comment]
I would also use Windows Monitoring heavily. We have linux systems but
windows would be a huge improvement for us

**Comment by Ferroin** [comment]
For those who are adventurous, you can probably scrape some data off of Windows systems with current versions of Netdata through creative use of SNMP.  A pretty sizable percentage of the things exposed via WMI that we would theoretically be collecting with Netdata can also be exposed through SNMP on Windows Server systems.

**Comment by mflor35** [comment]
Maybe a Windows client is possible by building it using .Net Core.

https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/monitor-app-health

**Comment by Ferroin** [comment]
It's already been stated that a Windows port will happen, and there's already even been a statement of the first steps towards that.

**Comment by mflor35** [comment]
@Ferroin You are right! I skimmed throgh and missed @cakrit comment.

**Comment by irvintim** [comment]
For our project, Windows support would be a huge plus.  We monitor a ton of Windows servers.   I'm wondering if one way to make this easier is to focus solely on the collector and streamer, and not worry about having all the features.  So, a collector that grabs all the WMI data, and converts it to a netdata stream to send to an external netdata server.  It feels like this model would be a good addition to the netdata collection, I can think of a number of devices where data collection is important, but presentation, backend-support, etc. wouldn't be required (network gear, containers, embedded SBCs, IoT devices, etc.)

**Comment by ilyam8** [comment]
I see there is [wmi_exporter](https://github.com/martinlindhe/wmi_exporter), it even collects [windows containers](https://github.com/martinlindhe/wmi_exporter/pull/320)

So the collector is ready, we need to parse the output and convert it to netdata's format

**Comment by cakrit** [comment]
But we'll still be using a netdata running on Linux to collect that information via HTTP requests. This is actually an excellent idea and we really should prioritize it. But it's not related to the netdata port, which is what this issue is about. @ilyam8 I suggest you create a new issue for the new wmi collector and we put it on the top of our TODOs.

**Comment by ilyam8** [comment]
Guys, please have a look #6001. Does it makes sense to implement in that way?

**Comment by cakrit** [comment]
- [ ] Create design for the implementation. #6395
- [ ] Plan & Implement (TBD)

**Comment by expsl** [comment]
Has a decision been made on using WMI?

It might be better to use the PDH API or Remote Registry as WMI has latency issues and may lead to high CPU utilisation if collecting large amounts of counters.

This other project faced a similar issue: 
https://github.com/oshi/oshi/issues/505

**Comment by expsl** [comment]
I will be putting together a brief requirements specification for the team, besides what has already been mentioned if there is any wish list or suggestions for the Windows agent, please add your comments here.

**Comment by thiagoftsm** [comment]
Hi @expsl ,

An Windows agent continue being a company goal, but for while we are working in other Netdata features. We expect to start converting part of our code that runs only with Unices libraries (posix threads, for example ) in generic libraries like `libuv` as first step in this direction.

Best regards!

**Comment by expsl** [comment]
Hi All,

I have just completed the brief spec, here is a summary of the key points, please feel free to comment and share your feedback.

**Key Monitoring Areas** 

Windows monitoring is a broad area; the preliminary specification should focus on these key areas in order of priority: 

1) Windows Performance Counters

2) Windows Service Status

3) Log file monitoring

**Comment by expsl** [comment]
**Windows Performance Counters**

Windows Performance Counters are visible in the ‘Perfmon’ tool or Windows Performance Monitor. 

These counters expose more than 2,000 metrics about the operating system, processes, and various application specific counters. 

There are various interfaces available to programmatically access performance counters, namely; 

1) WMI
2) PowerShell
3) C# Libraries
4) C and C++ Performance Counters API
5) Performance Data Helper (PDH) API
6) Registry Query of HKEY_PERFORMANCE_DATA 

In order to select the best method for extracting data, we have to understand where the data is ultimately stored and what methods are the most efficient. 

![Performance_Counter_Methods_PNG](https://user-images.githubusercontent.com/8287731/80358665-5d0cdd80-88af-11ea-9389-9f41b1e6f9a8.png)

_Image 1 – Visual Hierarchy of Access Methods_ 

WMI, C++ and C# API’s all ultimately connect to the PDH API Interface, this means typically slower access times. 

PowerShell (To be confirmed) connects to WMI / W32 libraries using the reflection method. 

The best options are reading the registry directly using RegQueryValueEx or accessing via the **PDH API**. 

The **PDH API** has been around for ages and is part of every windows machine, however the PDI API is a **blocking API**, it uses an internal mutex to manage access (One call at a time) even though on the surface it is able to accept multiple concurrent calls. 

The following Open Source project ran into issues with WMI and started using the PDH API, then eventually querying the registry directly: 

https://github.com/oshi/oshi/issues/505 

In order to have a complete asynchronous system that is able to handle per second polling, we will need to access the registry directly. 

The PDH API can also be used to complement direct registry access especially when iterating through counter names.

**Comment by thiagoftsm** [comment]
Hi @expsl ,

Thank you very much for your work, this will help us a lot! :)

**Comment by soroshsabz** [comment]
I think native support of windows is needed, and WSL is not best match solution, if the performance is acceptable, still WSL is just work around solution.

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Silvenga** [comment]
@jkowall doesn't WSL2 execute in a VM? It doesn't have access to the host's information. Even WSL1 had very limited access to the host (and if the host had Hyper installed, no information about the host, only the management VM). 

Remember that HyperV is a type 1 hypervisor. On a server with HyperV roles installed, only performance counters have access to host outside of the management OS VM.

**Comment by jkowall** [comment]
@Silvenga correct it's inside a VM, but they've done a lot of integrations and GUI support is coming soon for apps on linux (X). It does have a lot of access to host info including CPU measurements and such. I can see them from within the app. You can also measure the physical volumes from WSL, so some things are working, but others don't for netdata.

**Comment by Raki72** [comment]
Netdata is now working nicely in the Linux Subsystem of Windows 10. I installed it with this tutorial: https://www.how2shout.com/how-to/how-to-install-netdata-on-windows-10-wsl.html?unapproved=203499&moderation-hash=f4b8e97f2042454b9ca2825a70ed0519#comment-203499

One problem stays - Netdata uses an insane amount of CPU. For me it's about 700%. This is making the resource measurements quite absurd. But anway, well done. :)

**Comment by mfundul** [comment]
> 
> 
> Netdata is now working nicely in the Linux Subsystem of Windows 10. I installed it with this tutorial: https://www.how2shout.com/how-to/how-to-install-netdata-on-windows-10-wsl.html?unapproved=203499&moderation-hash=f4b8e97f2042454b9ca2825a70ed0519#comment-203499
> 
> One problem stays - Netdata uses an insane amount of CPU. For me it's about 700%. This is making the resource measurements quite absurd. But anway, well done. :)

Netdata is hitting [this](https://github.com/microsoft/WSL/issues/4898#issuecomment-592196721) WSL bug.

**Comment by mfundul** [comment]
> 
> 
> > Netdata is now working nicely in the Linux Subsystem of Windows 10. I installed it with this tutorial: https://www.how2shout.com/how-to/how-to-install-netdata-on-windows-10-wsl.html?unapproved=203499&moderation-hash=f4b8e97f2042454b9ca2825a70ed0519#comment-203499
> > One problem stays - Netdata uses an insane amount of CPU. For me it's about 700%. This is making the resource measurements quite absurd. But anway, well done. :)
> 
> Netdata is hitting [this](https://github.com/microsoft/WSL/issues/4898#issuecomment-592196721) WSL bug. This is what's causing the high CPU utilization and it should go away when Microsoft fixes it.

**Comment by doumhfr** [comment]
> > > Netdata is now working nicely in the Linux Subsystem of Windows 10. I installed it with this tutorial: https://www.how2shout.com/how-to/how-to-install-netdata-on-windows-10-wsl.html?unapproved=203499&moderation-hash=f4b8e97f2042454b9ca2825a70ed0519#comment-203499
> > > One problem stays - Netdata uses an insane amount of CPU. For me it's about 700%. This is making the resource measurements quite absurd. But anway, well done. :)
> 
> Netdata is hitting [this](https://github.com/microsoft/WSL/issues/4898#issuecomment-592196721) WSL bug. This is what's causing the high CPU utilization and it should go away when Microsoft fixes it.

bug or not I don't think we could consider as a working solution to nées WSL

**Comment by mfundul** [comment]
> 
> 
> > > > Netdata is now working nicely in the Linux Subsystem of Windows 10. I installed it with this tutorial: https://www.how2shout.com/how-to/how-to-install-netdata-on-windows-10-wsl.html?unapproved=203499&moderation-hash=f4b8e97f2042454b9ca2825a70ed0519#comment-203499
> > > > One problem stays - Netdata uses an insane amount of CPU. For me it's about 700%. This is making the resource measurements quite absurd. But anway, well done. :)
> > 
> > 
> > Netdata is hitting [this](https://github.com/microsoft/WSL/issues/4898#issuecomment-592196721) WSL bug. This is what's causing the high CPU utilization and it should go away when Microsoft fixes it.
> 
> bug or not I don't think we could consider as a working solution to nées WSL

It's not a working solution. It could be considered "runnable" if the bug is fixed which may be useful to a small number of people that can take advantage of the agent itself, hence I explained what the CPU utilization problem is.

**Comment by cakrit** [comment]
I think I saw a couple of workarounds on the WSL issue thread, but I didn't read it carefully. I don't understand "nées WSL", what does that mean?

**Comment by jpylypiw** [comment]
I've been thinking about deploying Netdata enterprise-wide for some time now, but my current state was also that Windows is not supported.
I was already so motivated to program a collector for Windows data when I stumbled upon this link: https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi/
Apparently Windows is already supported by Netdata and some metrics are displayed.
I will test it today and report back afterwards.

**Comment by Ferroin** [comment]
> I've been thinking about deploying Netdata enterprise-wide for some time now, but my current state was also that Windows is not supported.
> I was already so motivated to program a collector for Windows data when I stumbled upon this link: https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi/
> Apparently Windows is already supported by Netdata and some metrics are displayed.
> I will test it today and report back afterwards.

I can comment from personal experience that the WMI collector works pretty well.

However, the main goal that this issue exists to track is native support for running Netdata _on_ Windows without needing to use a VM or WSL.

**Comment by expsl** [comment]
New Relic just announced that it will be open sourcing its agents, this includes specific application agents as well as the windows infrastructure agent.

For more details see:
https://opensource.newrelic.com/

Repo:
https://github.com/newrelic/infrastructure-agent

Open Telemetry Standard:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/README.md

**Comment by cakrit** [comment]
@expsl this is very interesting, but I couldn't locate the definition of the API between the agent and New Relic itself. Open Telemetry doesn't provide an exposition format, Open Metrics (Prometheus) is one and I doubt the agent exposes metrics to New Relic using that. Do you have a few more pointers on how we could possibly use this to get metrics into Netdata? If that wasn't the purpose of this post, then it's not relevant to this discussion.

**Comment by ilyam8** [comment]
The implementation of this feature is nearing completion and will be formally announced in the forthcoming release, scheduled for the next 2-4 weeks.

**Comment by socialmediavideo** [comment]
Snapchat is a go-to platform for sharing fun, short-lived videos with friends and followers. But what if you want to save a Snapchat video permanently without the watermark? Whether you're a content creator, social media manager, or simply want to keep a memorable Snap, you’ve probably searched for a [Snapchat video downloader without watermark online free](https://socialmediavideodownloader.com). The good news? Your search ends here.

In this article, we’ll introduce you to the ultimate solution that allows you to download Snapchat videos without watermark online for free – [SocialMediaVideoDownloader.com](https://socialmediavideodownloader.com/).

✅ Why [Download Snapchat Videos](https://socialmediavideodownloader.com) Without Watermark?
Downloading Snapchat videos is useful for several reasons:

🔄 Reposting on other platforms like Instagram, TikTok, or YouTube Shorts.

🎨 Editing or repurposing videos for your own content.

💾 Archiving memories without losing quality or branding interference.

🎓 Saving educational or entertaining videos for later reference.

However, downloading Snapchat videos often comes with an annoying watermark that reduces the video’s aesthetic appeal and makes repurposing difficult. That’s where a reliable, watermark-free solution becomes essential.

🚀 The Ultimate Solution: SocialMediaVideoDownloader.com
When it comes to downloading Snapchat videos without a watermark, [SocialMediaVideoDownloader.com](https://socialmediavideodownloader.com/) stands out as the most powerful and user-friendly tool available online—for free.

🔍 Key Features:
Feature	Description
🎯 No Watermark	Download Snapchat videos clean—without any branding or logos.
🌐 100% Online	No need to install any software or app. Just open your browser and go.
🆓 Completely Free	No hidden costs, no sign-ups, and unlimited downloads.
⚡ Fast Downloads	Lightning-speed processing and downloading.
📱 Mobile & Desktop Friendly	Works smoothly on Android, iOS, Windows, and macOS.
🔐 Safe & Secure	Your data and video links are never stored or shared.
🎥 Supports All Snapchat Video Types	Stories, Spotlight videos, public profiles, and more.

🛠️ How to Use [Snapchat Video Downloader](https://socialmediavideodownloader.com) Without Watermark (Step-by-Step)
Downloading a Snapchat video without watermark is quick and effortless with SocialMediaVideoDownloader.com:

Open Snapchat and find the video you want to download.

Copy the video link (from public stories, spotlight, or profile).

Go to 👉 [SocialMediaVideoDownloader.com](https://socialmediavideodownloader.com/)

Paste the link in the input box.

Click on "Download".

Select the No Watermark option and save the video to your device.

📂 Done! Your high-quality, watermark-free Snapchat video is ready for use.

🎯 Who Should Use This Tool?
This free Snapchat video downloader without watermark is perfect for:

Influencers & Creators: Download videos to repurpose across platforms.

Social Media Managers: Save client content for editing and analytics.

Students & Teachers: Archive educational Snap videos for presentations.

General Users: Preserve memories without cluttering them with logos.

🧩 Snapchat Video Types Supported
Not all tools support every type of Snapchat video—but this one does:

📖 Snapchat Stories

✨ Snapchat Spotlight videos

📹 User-generated public videos

🔗 Snapchat video links shared via messages

Whatever you need, it’s covered.

❓ Frequently Asked Questions (FAQs)
🔸 Is this tool really free?
Yes! SocialMediaVideoDownloader.com is completely free to use without limits.

🔸 Will the downloaded video have any watermark?
No. The downloader provides an option to get videos without any watermark.

🔸 Is login required to use the tool?
Not at all. You don’t need to sign up or log in to download videos.

🔸 Can I use this on my phone?
Absolutely. It works perfectly on all mobile browsers and devices.

🔸 Is this tool safe?
Yes. It uses secure HTTPS connections and doesn’t store any personal data.

🏁 Conclusion
If you’re looking for a [Snapchat video downloader without watermark online free](https://socialmediavideodownloader.com), look no further than [SocialMediaVideoDownloader.com](https://socialmediavideodownloader.com/). It’s fast, safe, free, and works like a charm for all types of Snapchat videos—whether it's stories, spotlight clips, or public videos.

No more screen recording. No more blurry videos with logos. Just clean, high-quality content ready to use, share, or repurpose.

**Comment by jo-chemla** [comment]
For anyone interested and watching this thread, here is the [blog announcement](https://www.netdata.cloud/blog/netdata-native-windows-agent/) and [windows doc](https://learn.netdata.cloud/docs/netdata-agent/installation/windows). 

`Anonymous access to the dashboard of Windows nodes is not allowed`, so one has to login to a netdata cloud instance - no self-hosted-only capabilities. 

Plus there is no way for me to see the dashboard on `localhost:19999` - probable bug because this windows instance is my only connected node in my only space, I can see the dashboard blurred with what looks like playing metrics, but with a modal to upgrade. I've tried rebooting and stopping/restarting the netdata service, with no luck. By tweaking things, on the cloud webui, I removed the windows-laptop dashboard and cannot find a way to get it back other than full uninstall/reinstall. 

> This dashboard is locked, so you can't see it. Upgrade for no limitations or Change your active node selection to unlock it
> The node JONATHAN-LAPTOP is locked.Windows agent is not supported.

**Comment by thiagoftsm** [comment]
> Plus there is no way for me to see the dashboard on `localhost:19999` - probable bug because this windows instance is my only connected node in my only space, I can see the dashboard blurred with what looks like playing metrics, but with a modal to upgrade. I've tried rebooting and stopping/restarting the netdata service, with no luck. By tweaking things, on the cloud webui, I removed the windows-laptop dashboard and cannot find a way to get it back other than full uninstall/reinstall.

Did you try to log in on the right side when "the dashboard appeared blurred with what looked like playing metrics"? If so, what Windows version and browser are you using?

**Comment by jo-chemla** [comment]
Thanks for getting back. I've been running latest netdata windows installer `netdata 2.5.4.0`, and am running recent `Windows 11 Pro N 24H2`. I'm indeed logged-in as shown on the below screenshot. Also I did input the Claim-token and room-id that I could find on the `Room settings, Nodes, Claiming Details` during installation. Active Node selection only shows this laptop as live, but I cannot edit or delete it. 

Note that the screen is localhost:19999, but when I login to netdata.cloud, the room is empty. When trying to add a node to the room from the cloud, I can see the laptop node listed, but selection is disabled. 

Also, is it possible to edit claiming token and room-id without full uninstall/reinstall cycle? Finally, b ydeleting the blurring div I can see the dashboard live data is correct, but I'm hoping this is a config bug on my side. 

![Image](https://github.com/user-attachments/assets/1800a97f-79db-42f6-8f1e-46534d228281)

**Comment by thiagoftsm** [comment]
Hello @jo-chemla ,

I discussed your concerns with our team to better understand the situation regarding our Windows version. First, we apologize for any unclear messaging. I'll be working with the documentation team (@kanelatechnical ) to improve clarity in both the dashboard and official documentation.

As outlined in our [doucmentation](https://learn.netdata.cloud/docs/netdata-agent/installation/windows),  these messages are expected on Microsoft Windows unless you have a paid subscription.

When we initially released the Windows version, we offered a 14-day trial subscription. After consulting with @constantinenikitiadis, , we've decided to reintroduce this trial access. You and others can now request access here: https://b6yi53u6qjm.typeform.com/to/UuzweVXk.

Best regards!

**Comment by jo-chemla** [comment]
Thanks for getting back. I don't want to use the netdata cloud, and am just self-hosting agents myself on some local-only machines I need to monitor that cannot reach the internet. 

I don't understand why the windows integration is paywalled, is it not part of the open-source portion of netdata? If I'm self-hosting the standalone agent or a child reporting to a parent on my network, with the cloud disabled, surely I would not need a subscription right? 

As shown in this [community thread](https://community.netdata.cloud/t/suddenly-local-dashboard-is-limited-to-5-nodes/7111/18), relative to the introduced 5 nodes limit in Local webui from v2 to v3, that change led to quite some backlash. It would be interesting - although pretty sensitive - to see how many long-time users sticked to netdata v2, how many abandoned for an alternative, how many old users upgraded to v3 and how many new users joined since. 
Edit: reported alternative in the thread: If you don’t want to subscribe to a paid plan - to stay on Netdata v2.1.1 (Parent) and use `/v3` endpoint.
