### ISSUE TITLE
Netdata service wait for network

### ISSUE THREAD

**Issue by djrm05** [netdata/netdata#9200]
Hi,

Im  running netdata on Ubuntu 20.04 and it seems any time the machine is rebooted, specifically the node.d module for snmp doesn't work at start. Looking to the netdata.service it is due to use network.target instead of network-online.target, so using the second one system can be rebooted and netdata is perfectly starting later on. Now the question is if there is any other workaround for this as changing netdata.service is not good as any update overwrite the file and happens the same...

Any help would be appreciated

Thanks

**Comment by djrm05** [comment]
anyone?

**Comment by ilyam8** [comment]
hi @djrm05 

This is totally make sense, the problem is

> https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

---

> network-online.target

> This will ensure that all configured network devices are up and have an IP address assigned before the service is started. network-online.target will time out after 90s. Enabling this might considerably delay your boot even if the timeout is not reached.

> It is strongly recommended not to pull in this target too liberally: for example network server software should generally not pull this in (since server software generally is happy to accept local connections even before any routable network interface is up), its primary purpose is network client software that cannot operate without network.
