### ISSUE TITLE
Netdata offline install ebpf collector is missing 

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#9201]
I am trying to upgrade from 1.20.0 to the latest offline version (netdata-v1.22.1.gz.run) on CentOS 6.5 and seeing that the install completed but there is no trace of the ebpf collector. 

Ran the check for compatibility and it didn’t return any errors. The mount steps were carried out successfully as well. In the plugin location I see a ebpf_process.py. Thought there should be ebpf.py. Wonder what am I missing. No ebpf errors in logs either.

**Comment by gamefundas** [comment]
Running the plugin manually throws the following error

./ebpf_process.plugin
2020-05-28 15:50:56: ebpf_process.plugin INFO  : MAIN : [EBPF PROCESS] does not have a configuration file. It is starting with default options.
2020-05-28 15:50:56: ebpf_process.plugin ERROR : MAIN : [EBPF_PROCESS] Cannot load /opt/netdata/usr/libexec/netdata/plugins.d/libnetdata_ebpf.so. (errno 22, Invalid argument)
2020-05-28 15:50:56: ebpf_process.plugin ERROR : MAIN : [EBPF_PROCESS] Cannot load library.

also this whole ebpf vs ebpf_process is confusing. The docs refer to ebpf.conf and ebpf.plugin but this installation seems to have everything with _process. As per the error it seems that we are missing some libraries too.

**Comment by thiagoftsm** [comment]
Hello @gamefundas ,

Please, correct if I am wrong, but I think CentOS `6.x` uses kernel `2.6.x` as its basis, and the eBPF was brought with kernel 3.10.x. 
I also would like to call attention for the fact that CentOS 7.6 or newer only can run the eBPF, because RH team brought a lot of updates to it, because the kernel would not have conditions to run. the collector.



Best regards!

**Comment by thiagoftsm** [comment]
@prologic we should not install eBPF plugin on kernels that is not compatible, we need to take a look on this.

**Comment by prologic** [comment]
> @prologic we should not install eBPF plugin on kernels that is not compatible, we need to take a look on this.

There are two ways to handle this;

a) We skip installing the kernel-collector in the Netdata installer -- We used to do this; but now I _need_ this to always be effectively installed because we also want to support the Netdata Static kickstartf64 + eBPF -- Which we do not know the Kernel ahead of time.
b) We teach `ebpf.plugin` to just bail and stable itself permanately if it is being run on a Kernel we just simply cannot support?

Either way; we are in a posotion where we kind of need both things to happen :)

**Comment by thiagoftsm** [comment]
When I create a PR to compile Netdata with static libraries, I will bring `b)`.

**Comment by gamefundas** [comment]
> Hello @gamefundas ,
> 
> Please, correct if I am wrong, but I think CentOS `6.x` uses kernel `2.6.x` as its basis, and the eBPF was brought with kernel 3.10.x.
> I also would like to call attention for the fact that CentOS 7.6 or newer only can run the eBPF, because RH team brought a lot of updates to it, because the kernel would not have conditions to run. the collector.
> 
> Best regards!

Amazon Linux is a cocktail of CentOs Redhat and Fedora so not much clue what exact version of CentOs its based on. This is what I get from the release information.

cat /etc/*elease
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)

**Comment by thiagoftsm** [comment]
Amazon is a special case that we will need to take a look, this distribution is working like Debian, Ubuntu and RHEL family, it has their own configuration, this means that probably on kernel 4.14 they are using the ABI that was released with kernel 4.15 and this is not allowing you to run .

I will confirm this with the SRE team and we will bring a patch ASAP.

**Comment by prologic** [comment]
@gamefundas I have an interesting perhaps silly question; but let's see... :)

How would you feel about using a custom AMI based off of "some" Amazon LInux that we install a custom (_non-hacked up_) Kernel complete with Netdata pre-installed ready to go?

Alternatively we could reach out to AWS and work with their engineers to help us bring Netdata + eBPF monitoring to their flavor of LInux :)

**Comment by gamefundas** [comment]
@prologic I got a little delayed responding back on this. 

I would say that custom/external AMI may not be a preferred option with people in general as most firms would already be managing security/vulnerability using their own devops engineering process. There is a very streamlined audit process to validate software packages, update images quarterly etc to certify AMI's and yum repo's in the organization and its going to be a hard sell for something like this.

I am still wondering how the compatibility check didn't fail indicating epbf feature isnt supported by  Netdata.

**Comment by prologic** [comment]
@gamefundas No worries :) It was mostly a tongue-in-cheek comment. We have a few problems supporting our eBPF plugin on the Redhat family of Linux dustri(s) which include CentOS and Amazon Linux. We're working on it however. Stay tuned!

**Comment by prologic** [comment]
@thiagoftsm What's the status of this issue? From what I can see originally this was reported against a Netdata Static install which we don't support yet for eBPF. We have plans to fix that though, so is this issue still relevant? Perhaps we document that Netdata Static + eBPF is not currently yet supported and update our docs?

**Comment by thiagoftsm** [comment]
@joelhans I do not remember if we added this specific information related to eBPF.plugin in our documentation, it will need to go in the release note for sure.

**Comment by joelhans** [comment]
@thiagoftsm I don't recall mentioning in the eBPF docs that it's not compatible with static builds. I'll add it to the release notes now and work up a PR for the eBPF docs later today.

**Comment by prologic** [comment]
Thanks @joelhans !

**Comment by prologic** [comment]
With #9418 merged that documented eBPF not currently working with our Netdata Static installs; I'm going to close this. However to be __clear__ we actually do fully plan to support this and ti should be available before the next release. Please correct me if I'm wrong @thiagoftsm :)

**Comment by prologic** [comment]
@gamefundas Appreciate your patience whilst we work through the technical details of supporting the eBPF kernel collector with our static builds.
