### ISSUE TITLE
netdata-claim.sh: command not found

### ISSUE THREAD

**Issue by manval70** [netdata/netdata#9202]
When creating a bug report please: When run script to claim a node

##### OS / Environment

```
Ubuntu Server 18.04 LTS
```

##### Netdata version

 1.9

##### Steps To Reproduce

1. ...
2. ...

**Comment by prologic** [comment]
Looks like we don't include the script in the source dist:

```#!sh
~/Netdata/netdata
 (static64_plus_ebpf) 0
$ find . | grep 'netdata-claim.sh'
./claim/netdata-claim.sh
./claim/netdata-claim.sh.in

$ sift 'netdata-claim.sh'
netdata.spec.in:449:%{_sbindir}/netdata-claim.sh
packaging/docker/Dockerfile:49:    mv /usr/sbin/netdata-claim.sh    /app/usr/sbin/ && \
packaging/installer/netdata-uninstaller.sh:493:  rm_file "/usr/sbin/netdata-claim.sh"
claim/Makefile.am:7:    netdata-claim.sh \
claim/Makefile.am:14:    netdata-claim.sh \
claim/Makefile.am:18:    netdata-claim.sh.in \
claim/claim.c:78:              "exec netdata-claim.sh %s -hostname=%s -id=%s -url=%s -noreload %s",
claim/claim.c:86:    info("Executing agent claiming command 'netdata-claim.sh'");
claim/README.md:51:sudo netdata-claim.sh -token=TOKEN -rooms=ROOM1,ROOM2 -url=https://app.netdata.cloud
claim/README.md:78:netdata-claim.sh -token=TOKEN -rooms=ROOM1,ROOM2 -url=https://app.netdata.cloud
claim/README.md:96:docker exec -it netdata netdata-claim.sh -token=TOKEN -rooms=ROOM1,ROOM2 -url=https://app.netdata.cloud
claim/README.md:165:You can now move on to claiming. When you claim with the `netdata-claim.sh` script, add the `-proxy=` parameter and
claim/README.md:169:sudo netdata-claim.sh -token=MYTOKEN1234567 -rooms=room1,room2 -url=https://app.netdata.cloud -proxy=socks5h://203.0.113.0:1080
claim/README.md:283:sudo netdata-claim.sh -token=TOKEN -rooms=ROOM1,ROOM2 -url=https://app.netdata.cloud -id=$(uuidgen)
claim/README.md:305:A Space's administrator can claim an Agent by directly calling the `netdata-claim.sh` script either with root privileges
claim/README.md:326:netdata-claim.sh -token=MYTOKEN1234567 -rooms=room1,room2
```

@amoss @Ferroin Any reason we omitted it or just forgot to add it?

**Comment by amoss** [comment]
It is generated during the build (there is a substitution that needs to execute based on the target installation directories). It should be present *after* the installer is run - not before.

**Comment by prologic** [comment]
@manval70 Can you please provide more details? Your bug report is very sparse and contains few details. Can you produce some output logs we can look at? Thanks!

**Comment by ilyam8** [comment]
> netdata-claim.sh: command not found

possible cause - `netdata-claim.sh` is not in PATH

```cmd
[ilyam-pc ~]# netdata-claim.sh
bash: netdata-claim.sh: command not found
```

> /opt/netdata/usr/sbin/netdata-claim.sh

**Comment by manval70** [comment]
I think the installation for ubuntu repo (sudo apt-get install netdata) does not include netdata-claim.sh.
I re-install netdata using bash <(curl -Ss https://my-netdata.io/kickstart.sh) and it's ok now.

**Comment by manval70** [comment]
Yes... It works!.
I uninstall netdata and install again using bash <(curl -Ss https://my-netdata.io/kickstart.sh) .
![image](https://user-images.githubusercontent.com/65911684/83390481-97abed80-a3fa-11ea-822e-b3b1c814a9d0.png)

**Comment by ProfessorManhattan** [comment]
Issue still exists for Mac OS X

**Comment by prologic** [comment]
There is a fix for macOS and Cloud support in #9360

**Comment by kurdtpage** [comment]
I am running Linux Mint 20 and I ran the installation via the website using `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` and when I try `sudo netdata-claim.sh -token=<token> -rooms=<rooms> -url=https://app.netdata.cloud` I get:
`sudo: netdata-claim.sh: command not found`
I have searched for the netdata-claim.sh file, but it is not on the system.

**Comment by kurdtpage** [comment]
I have found a workaround for Ubintu/Linux Mint:
```
cd /opt/netdata/usr/sbin/
sudo chmod +x netdata-claim.sh
sudo ./netdata-claim.sh <params>
```

**Comment by OdysLam** [comment]
@joelhans A number of users report issues with the claiming script, which is not added to PATH for some reason. Perhaps we can add a debugging mention in the claiming docs?

**Comment by OdysLam** [comment]
@prologic , this seems relevant. thoughts?
https://community.netdata.cloud/topic/126/any-idea-how-to-use-compile-netdata-cloud-under-archlinx

**Comment by AysadKozanoglu** [comment]
if installed netdata from with one-liner kickstart script than you can find netdata-claim under:

```/opt/netdata/bin/netdata-claim.sh```

**Comment by gusarg81** [comment]
Hi. same case for me. netdata-claim.sh does not exist when installing from Ubuntu repo.
