### ISSUE TITLE
Ubuntu Server in Azure: This agent was built without the dependencies for Cloud and cannot be claimed

### ISSUE THREAD

**Issue by manval70** [netdata/netdata#9209]
When creating a bug report please: Running the script to claim a node

##### OS / Environment

```
Ubuntu 18.04 LTS run in Azure
- Virtualization: microsoft
- Operating System: Ubuntu 18.04.4 LTS
- Kernel: Linux 5.3.0-1022-azure
- Architecture: x86-64
```

##### Netdata version

 netdata v1.22.1-151-nightly

##### Steps To Reproduce

1. ...
2. ...

**Comment by manval70** [comment]
Error message: The installer could not prepare the required dependencies to enable Netdata Cloud functionality
![image](https://user-images.githubusercontent.com/65911684/83161625-57eeb880-a111-11ea-8a6c-fa50ef54c628.png)

**Comment by prologic** [comment]
@manval70 How did you install the Netdata agent on this system?

**Comment by manval70** [comment]
I'm not sure. I think using sudo apt-get install netdata.
I will re-install netdata using bash <(curl -Ss https://my-netdata.io/kickstart.sh) to see if it works.

**Comment by manval70** [comment]
Yes... It works!.
I uninstall netdata and install again using bash <(curl -Ss https://my-netdata.io/kickstart.sh) .
![image](https://user-images.githubusercontent.com/65911684/83398849-d648a480-a408-11ea-9a63-a6780d050cf1.png)
