### ISSUE TITLE
would it be possible to have an option in the installer to not install netdata with the netdata cloud portion so its all locale?

### ISSUE THREAD

**Issue by ninja85a** [netdata/netdata#9215]
##### Question summary
to have the option to have an install of netdata with no cloud portion installed
##### OS / Environment
all supported
##### Component Name
netdata cloud I guess
##### Expected results
to have a installer option to not install anything related to the cloud so its all local

**Comment by ilyam8** [comment]
hi @ninja85a 

https://github.com/netdata/netdata/blob/acf797af761c19ca5f27fd4a78e44cbbaf27e35f/netdata-installer.sh#L196

**Comment by ninja85a** [comment]
thanks I really should look for this stuff closer
