### ISSUE TITLE
Alert for Slave Going Down / Unreachable

### ISSUE THREAD

**Issue by E46-S54** [netdata/netdata#9217]
Hey Netdata team,

It seems that there have been a few questions/feature requests regarding a slave going down or becoming unreachable. Unless I've missed something it still unfortunately seems like it's a missing feature, one that a lot of people would see as quite important.

I have looked into this to see if there is a way to implement this, by dynamically generating an `fping` config using the `mirrored_hosts` list from `/api/v1/info` 

It's not perfect, but we can gather a list of currently streaming hosts doing something like this, ready to insert into the fping config file:
`curl -s localhost:19999/api/v1/info  | python3 -c "import sys, json; print(json.load(sys.stdin)['mirrored_hosts'])" |  tr -d "[],\'"` 

This isn't ideal because:
- fping plugin doesn't seem to re-read config periodically / on run and I can't see a way of doing this without a full netdata restart
- if a host is down, and netdata master restarts, it won't appear on the mirrored_host list, meaning it could be missed entirely
- I'm unsure on when a host would stop appearing in mirrored_hosts - meaning if it went down it could stop appearing, and wouldn't be checked

Are there any plans on adding in a slave up/down alarm from the master? IMO it's the only thing that is missing from Netdata. With typical cloud workloads where VMs can be ephemeral, it would be great to have a dynamic up/down functionality that didn't require a restart.

Thanks

**Comment by tinyhammers** [comment]
+1 from me. 
Its the one thing that I wish ND did better. Maybe if a node is set to master, it can have an additional feature to ping all its hosts and alert if one doesn't respond? (Is that what health checks do on that master?)
Or, could that/is that something that Netdata Cloud could do? Send an alert if one of the collected nodes doesn't report in?

**Comment by amoss** [comment]
@dim08 A question for product to consider.

**Comment by dim08** [comment]
@amoss I have grouped this feature under ACLK/Claiming Improvements. Please include it in the technical grooming for the following release.

**Comment by E46-S54** [comment]
@dim08 @amoss is there any further information around this, please?

**Comment by dim08** [comment]
Hi @E46-S54 thank you for the follow up. I have prioritised this feature as part of ACLK improvements. Based on the current engineering capacity we are expected to have it resolved within the next 1-2 months.

**Comment by E46-S54** [comment]
🙇  
@dim08 
That is really good to know, thanks!

Are you planning for this be available as part of the self-hosted version?

**Comment by amoss** [comment]
Hello, this is a good idea for a feature. I agree that it will add something of value to Netdata when monitoring collections of child nodes. Internally we need to have a discussion with @netdata/product about the ways in which we could do this, and how they would look for users. In addition to that we want to have a discussion with you about the different options for doing this, and which ones would match the feature that you want to see.

Currently alarms are defined against changes in chart values. Adding new kinds of alarms has both benefits and drawbacks. Inside the code we can change an alarm state directly when a child connects or disconnects:

* Benefit: easy to put in one case.
* Benefit: does not cost much in performance.
* Drawback: special cases make the code more complex.
* Drawback: lack of configuration means that it has to work the same way for everybody.

There would be another approach, which is that we don't show useful information about streaming in Netdata charts. We could add charts (similar to the ones recently added to show ACLK stats) and then those charts could have alarms defined on them in the normal way in the config file. Some ideas for streaming charts that might be useful:

* Number of connected child nodes.
* Bandwidth / latency from the connected child nodes.
* Upstream bandwidth / latency.
* Connection uptime for child node connections.

The benefits here are that we add charts that make diagnosing problems with streaming easier, and at the same time we give users a way to add configurable alarms against those new metrics that would solve the original problem. For example, an alarm if the number of connected children goes below X, or the connection uptime for a child is below X. This might make it more useful to a wider range of users.

**Comment by cakrit** [comment]
Charts. Definitely charts. Great idea @amoss !
