### ISSUE TITLE
Netdata, slack notification MacOS

### ISSUE THREAD

**Issue by coffeina** [netdata/netdata#9219]
##### Question summary
How to check the connection between netdata and slack if netdata is installed on  OSX Mojave?
I used `/usr/libexec/netdata/plugins.d/alarm-notify.sh test` but is seemas like this command does not work at all. 
##### OS / Environment
MacOS, Mojave

**Comment by ilyam8** [comment]
Hi @coffeina 

what is the output from `/usr/libexec/netdata/plugins.d/alarm-notify.sh test` ?

What is your `bash` version? Ther is ancient version of `bash` on macOS by default.

**Comment by coffeina** [comment]
Hi @ilyam8 
autput of: `/usr/libexec/netdata/plugins.d/alarm-notify.sh test`

is `$ /usr/libexec/netdata/plugins.d/alarm-notify.sh test
-bash: /usr/libexec/netdata/plugins.d/alarm-notify.sh: No such file or directory`
`
Bash version: 
`$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
`

**Comment by coffeina** [comment]
The whole installation was performed using: `brew install netdata` command

**Comment by ilyam8** [comment]
oh, it is not in `/usr/libexec/netdata/plugins.d/`

check directories

> brew list netdata

---

i am not sure it works with bash 3.x, it is likely you need install latest bash (brew install bash)

**Comment by coffeina** [comment]
```
brew list netdata
/usr/local/Cellar/netdata/1.22.1/.bottle/etc/ (2 files)
/usr/local/Cellar/netdata/1.22.1/homebrew.mxcl.netdata.plist
/usr/local/Cellar/netdata/1.22.1/lib/netdata/ (168 files)
/usr/local/Cellar/netdata/1.22.1/libexec/netdata/ (201 files)
/usr/local/Cellar/netdata/1.22.1/sbin/netdata
/usr/local/Cellar/netdata/1.22.1/sbin/netdata-claim.sh
/usr/local/Cellar/netdata/1.22.1/sbin/netdatacli
/usr/local/Cellar/netdata/1.22.1/share/netdata/ (96 files)
```

**Comment by ilyam8** [comment]
so it is in `/usr/local/Cellar/netdata/1.22.1/libexec/netdata/`

**Comment by coffeina** [comment]
ok you are right
