### ISSUE TITLE
Exporting using prometheus remote_write directly to Cortex

### ISSUE THREAD

**Issue by lorddaren** [netdata/netdata#9220]
##### Question summary
Based on the documentation [remote_write](https://learn.netdata.cloud/docs/agent/exporting/prometheus/remote_write) and based on the link [Storage Providers](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage) I thought it was possible to do a remote write directly to Cortex. I wanted to accomplish this so that I did not have to set up a Prometheus infrastructure as well. 

When I tried to set up the exporting feature to write directly to Cortex I get an error from cortex stating: 

Netdata Logs:
```
2020-05-29 08:50:00: netdata INFO  : MAIN : EXPORTING: received 181 bytes from dbaautomation01 connector instance. Ignoring them. Sample: 'HTTP/1.1 400 Bad Request  Content-Type: text/plain; charset=utf-8  X-Content-Type-Options: nosniff  Date: Fri, 29 May 2020 14:49:50 GMT  Content-Length: 22    snappy: corrupt input '
```

Cortex Logs:
```
level=info ts=2020-05-29T14:48:34.525241567Z caller=cortex.go:336 msg="Cortex started"
level=error ts=2020-05-29T14:48:49.524824439Z caller=pool.go:161 msg="error removing stale clients" err="too many failed ingesters"
level=error ts=2020-05-29T14:48:50.934486151Z caller=push.go:23 org_id=fake traceID=1e332ee51a618528 err="snappy: corrupt input"
level=debug ts=2020-05-29T14:48:50.934604512Z caller=logging.go:44 traceID=1e332ee51a618528 msg="POST /api/prom/push (400) 218.688µs"
```

I compiled netdata with prometheus remote write capabilities by installing the necessary snappy and protobuf libraries:

```
Installed Packages
Name        : snappy
Arch        : x86_64
Version     : 1.1.0

Name        : protobuf
Arch        : x86_64
Version     : 3.6.1
```

I guess my question is what am I doing wrong, or am I doing it wrong altogether and I should have Prometheus sitting in between.

##### OS / Environment
`Linux version 3.10.0-1062.1.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)`

##### Component Name
prometheus_remote_write

##### Expected results
Netdata is pushing metrics directly into the distributor of Prometheus endpoint (`/api/prom/push`)

**Comment by vlvkobal** [comment]
Please check your Netdata setup using a [Remote Write Adapter Example](https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage/example_write_adapter).

**Comment by Xorso** [comment]
Running the server mentioned in the comment above shows that stats are posting like they from netdata. I am guessing this is an issue with Cortex. I did notice in the Cortex docs that a header needs to be sent along with the payload. Is there a way to configure Netdata to send header information during post?


Entry from remote_writer server:
```
netdata_system_idlejitter_microseconds_lost_persec_average{chart="system.idlejitter", dimension="max", family="idlejitter", instance="host01.example.com"}
  1221.800000 1591018827000
```

[Cortex Remote Write Header Details](https://cortexmetrics.io/docs/apis/#remote-api)

**Comment by vlvkobal** [comment]
Netdata sends an HTTP header
```
POST /receive HTTP/1.1
Host: arch-esxi
Accept: */*
Content-Length: 314
Content-Type: application/x-www-form-urlencoded
```

The only thing that is missing
> The HTTP request should contain the header X-Prometheus-Remote-Write-Version set to 0.1.0

**Comment by vlvkobal** [comment]
Could you test #9302? Does it work correctly with Cortex?
