### ISSUE TITLE
Change ebpf.plugin to compile with static library

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#9225]
#### Feature idea summary
`ebpf.plugin` has only pointers to functions that are filled when it is loaded, but we do not need them when we link the binary statically, it is necessary to remove these references to compile Netdata statically.

We have different possibilities that can be used to bring the static library for the eBPF.plugin, but all them must remove the dynamic loading from the ebpf.plugin. The following options have been considered now:

- Link the libraries during compilation time, more details [here](https://github.com/netdata/netdata/issues/9225#issuecomment-647779656) .
- Build everything on kernel-collector repository, more details [here](https://github.com/netdata/netdata/issues/9225#issuecomment-647791250).
- Final decision [here](https://github.com/netdata/netdata/issues/9225#issuecomment-648741678)

##### Expected behavior
To have conditions to use `-static` package from `kernel-collector` repo.

**Comment by thiagoftsm** [comment]
The first possible road would be to do download of the `static` libraries from [kernel collector](https://github.com/netdata/kernel-collector) and to do the linkage during the compilation time.

**Comment by thiagoftsm** [comment]
Another option to do the `static`  linkage will be to move the whole `ebpf.plugin` to  [kernel collector](https://github.com/netdata/kernel-collector) repository. To do this we will need to do the following changes in the `eBPF.plugin`:

-  Use `pthreads` directly instead `netdata_thread`
-  Create a short version of libnetdata on `kernel collector` repository that will have:
    - Netdata configuration parser.
    - Heartbeat defined inside `clocks` directory.
    - eBPF, this is the simplest to move.
    - Some functions used to parse `/proc`.
    - AVL trees that are used with configuration parser.
    - Functions like `freez` and `strdupz` would need to be copied, or we will need to change them for standard library functions.

The changes on `eBPF.plugin` aren't enough, because we will create 5 versions of the `eBPF.plugin`. To avoid load all the 5 plugins to check who is working correctly with the kernel, we will create another small software that will be the launcher of the correct eBPF.plugin for the specific kernel.

[Top](https://github.com/netdata/netdata/issues/9225#issue-627608900)

**Comment by amoss** [comment]
Meeting summary:

* Option 1: download complete eBPF collector from kernel collector repo
    - Build on local machine:
    - Requires: collector (versioned)
    - Build remotely: BPF program, libBPF (fork), collector (with libnetdata)
    - Requires: kernel source, clang 5+ or gcc 10, libelf

* Option 2: download static libraries from kernel collector repo
    - Build on local machine: collector (with libnetdata)
    - Requires: libBPF (versioned)
    - Build remotely: BPF program, libBPF (fork)
    - Requires: kernel source, clang 5+ or gcc 10, libelf

* Option 3: BPF programs in kernel collectors, build everything else locally at install-time
    - Build on local machine: libBPF (fork), collector (with libnetdata)
    - Requires: linux headers, libelf 
    - Build remotely: BPF program
    - Requires: kernel source, clang 5+ or gcc 10

Decision:
* Option 1 is the default.
* Option 3 is available for users, but is not an option that we support.
* Submodule for libnetdata, separate repo - pulled into both collector and netdata.
* Can also use to vendor other dependencies.

**Comment by vlvkobal** [comment]
After a long discussion with Thiago, we have identified that in reality the existing code in the kernel-collector repository can be simplified a lot:
- we need to prebuild only two versions of BPF programs;
- we need just a small patch for the libbpf library (for kernels < 4.15) instead of using three libraries;
- we don't need the existing complexity to build the code on different systems if we move libpf to netdata/netdata.

We are still investigating if there are any pitfalls we missed.

**Comment by vlvkobal** [comment]
I checked libbpf on several distributions. It can be built succesfully on
- Ubuntu 20.04 - 5.4.0
- Ubuntu 18.04 - 4.15.0
- Ubuntu 16.04 - 4.4.0
- OpenSUSE 15.1 - 4.12.14
- Debian 9 - 4.9.0
- CentOS 7 - 3.10.0

It looks like we don't need any patches at all.

**Comment by thiagoftsm** [comment]
> I checked libbpf on several distributions. It can be built succesfully on
> 
>     * Ubuntu 20.04 - 5.4.0
> 
>     * Ubuntu 18.04 - 4.15.0
> 
>     * Ubuntu 16.04 - 4.4.0
> 
>     * OpenSUSE 15.1 - 4.12.14
> 
>     * Debian 9 - 4.9.0
> 
>     * CentOS 7 - 3.10.0
> 
> 
> It looks like we don't need any patches at all.

We will only need to add four `ifdef`s to cover the changes made on kernel `4.15`.
@vlvkobal a doubt, did you need to install only `libelf-devel` and `kernel-headers`?

**Comment by vlvkobal** [comment]
Only `libelf-devel`.
No need for `kernel-headers`.
No need for `ifdefs` - it works on 4.4 out of the box.

**Comment by thiagoftsm** [comment]
Our version will need to test `linux/version.h`, but I am glad that the original needs only `libelf-devel`.
