### ISSUE TITLE
Ubuntu Server 20.04 - Raspberry Pi 4 - Unmet Dependencies libjson-c-dev

### ISSUE THREAD

**Issue by Issam2204** [netdata/netdata#9229]
I'm trying to install Netdata on my Raspberry Pi 4 using Ubuntu Server 20.04. At some point I get the following unmet dependicies error:

The following packages have unmet dependencies: libjson-c-dev : Depends: libjson-c4 (= 0.13.1+dfsg-7) but 0.13.1+dfsg-7ubuntu0.3 is to be installed E: Unable to correct problems, you have held broken packages.

When going to the Ubuntu packages website I do see the package being listed for Arm64, but there is no website to download it from: https://packages.ubuntu.com/focal/libjson-c-dev

Does anybody know how to install libjson-c-dev on the Raspberry Pi 4?

Thanks!

**Comment by prologic** [comment]
Hi @Issam2204 We (Netdata) do not specifically maintain [this Ubuntu netdata package](https://packages.ubuntu.com/focal/netdata) package. We'll see if we can get the maintainers in the community to fix this. In the meantime I would suggest you use our static installer.

**Comment by ilyam8** [comment]
Will be possible to install Netdata Agent on a RPi using our packagecloud repo after https://github.com/netdata/netdata/pull/10769 is merged.
