### ISSUE TITLE
Installation error related to netdata cloud 

### ISSUE THREAD

**Issue by Jafar412** [netdata/netdata#9230]
Whenever I open netdata an error message displays with "Installation error , The installer could not prepare the required dependencies to enable Netdata Cloud Functionality"
What could be that ? 

Thanks

**Comment by thiagoftsm** [comment]
Hi @Jafar412 ,

When you were installing or updating Netdata, did you received any error message while you were installing?
What is the Linux distribution or BSD system that you tried to install?

Best regards!

**Comment by Jafar412** [comment]
Hi @thiagoftsm 

No as I remember there were no error messages ,

The linux distribution is ubuntu 18.04 

Thanks

**Comment by thiagoftsm** [comment]
Hi @Jafar412 ,

Considering that the installation was fine, I have more two doubts:

1 -  Did you claim your host?
2 - Do you have additional errors inside your `error.log` talking about ACLK?

Best regards!

**Comment by Jafar412** [comment]
Hi @thiagoftsm 

For the first point what do you mean by claim you host? Can you explain more pls

For the second port there was nothing mention ACLk in the error.log of netdata 

Thanks!

**Comment by thiagoftsm** [comment]
Hi @Jafar412,

When the new cloud was released, it was brought the necessity to [claim](https://learn.netdata.cloud/docs/agent/claim) the node for we have condition to see the agent on the [new cloud](https://app.netdata.cloud/). The claim in the context that I asked you, it is an action with the script `netdata-claim.sh` to register a host on the cloud.

About the ACLK messages, I suspect that you did not establish any communication with the cloud before, probably this was the motive you did not have errors.

@underhood am I missing something here in the steps to fix the problem that @Jafar412 is having?

You are welcome!

Best regards!

**Comment by prologic** [comment]
@Jafar412 Did you upgrade your Netdata agent(s)? This is required.

See the doc son [getting started](https://learn.netdata.cloud/docs/cloud/get-started); specifgically:

> Before you get started with Cloud, you should have at least one Agent installed. See our installation guide for details.

Easiest way to do this is to just re-run `kickstart.sh` or `kickstart-static64.sh` on your system.

**Comment by Jafar412** [comment]
@prologic yes , I upgraded it before 

 Ok I'll check it again @prologic @thiagoftsm 

Thanks!

**Comment by Jafar412** [comment]
Hi @thiagoftsm @prologic  
I did try to reinstall and upgrade it 
It worked with no problems,Thanks all! 
I'm going to close it
