### ISSUE TITLE
This request in cron ./netdata-updater.sh reset and clean each time the netdata.conf file.

### ISSUE THREAD

**Issue by drkt7** [netdata/netdata#9237]
Hi

if my cron run: /opt/netdata/usr/libexec/netdata/netdata-updater.sh

this file reset and clear my netdata.conf and netdata not work each time...

I have to rewrite the whole configuration each time

- netdata version: v1.22.1-175
- Centos 6-7

Thanks

**Comment by prologic** [comment]
Duplicate of #8531
