### ISSUE TITLE
HTTP Content-Security-Compliance for (java)script

### ISSUE THREAD

**Issue by Pingger** [netdata/netdata#9238]
##### Feature idea summary
Webinterface compliance to the Content-Security-Compliance `script-src` (see https://content-security-policy.com/)

##### Expected behavior
Hi,

when the Content-Security-Compliance `script-src 'self'; resource-src 'self'` is set, the webinterface does not work. To make it work the additional setting `'unsafe-inline'` is required `script-src 'self' 'unsafe-inline'; resource-src 'self' 'unsafe-inline'`. As the name suggests: this is unsafe behaviour. 
To fix this all inline scripts would need to be replaced with `<script src="blih blah blupp.js" />` 
Addtionally it would be nice not to have to whitelist `googleapis.com` in the Content-Security-Compliance Header. Or in other words don't load script from third party websites. Because: Why should google know, when I open the netdata interface, on which server, from which IP, with which browser, ...

Greetings

**Comment by thiagoftsm** [comment]
Hi @Pingger ,

Thank you for your suggestion, I assigned this issue to Front End team for them to analyse your suggestion.

Best regards!

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
