### ISSUE TITLE
i cannot display oracledb metrics

### ISSUE THREAD

**Issue by aokanarik** [netdata/netdata#9241]
##### Question summary
Although I did configure https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/oracledb as in the link,
I can't view oracle db metrics on the netdata ui screen. can you help me?

**Comment by ilyam8** [comment]
Hi @aokanarik 

Python plugin has debug mode, see

https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin#how-to-debug-a-python-module

**Comment by aokanarik** [comment]
> Hi @aokanarik
> 
> Python plugin has debug mode, see
> 
> https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin#how-to-debug-a-python-module

Thank you, I solved the problem.
