### ISSUE TITLE
Musl cannot load ebpf programs

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#9242]
##### Bug report summary
According official [documentationt](https://wiki.musl-libc.org/functional-differences-from-glibc.html) musl does not work with the current flags we are passing to `dlopen`, it is necessary to change them.

##### OS / Environment
```
All 
```

##### Netdata version
netdata v1.22.1-182-g41c31b52

##### Component Name
ebpf collector

##### Steps To Reproduce

1. Install Netdata using script `kickstart_static64.sh`

##### Expected behavior
To be able to load ebpf programs with musl

**Comment by prologic** [comment]
IHMO this is not a bug per se but a design decision by the musl developers. It has come up a few times over the years in various mailing list threads. I'm not sure we can really "fix" this except to redesign how we appraoch this?

**Comment by amoss** [comment]
@prologic / @thiagoftsm This is now working isn't it? Can we close the issue?

**Comment by thiagoftsm** [comment]
@amoss kickstart-static64 is not installing ebpf.plugin, but I am closing this issue, because @vlvkobal already fixed it.

**Comment by prologic** [comment]
Thanks @thiagoftsm !
