### ISSUE TITLE
can't claim nodes

### ISSUE THREAD

**Issue by RubenKelevra** [netdata/netdata#9247]
##### Bug report summary
I tried to add 4 nodes in 4 different locations around the world to my Cloud account, all 4 fail repeatedly with

```
Failed to claim node with the following error message:"Gateway Timeout"
```

##### OS / Environment

2x ArchLinux
2x CentOS 7

##### Netdata version
Both CentOS 7:

```netdata v1.22.1-184-nightly```

Both ArchLinux:

```netdata v1.22.1-179-nightly```

**Comment by RubenKelevra** [comment]
Just tried it again, got 2 timeouts, but was able to add all 4 nodes now.

**Comment by underhood** [comment]
would you be willing to share `claimed_id` of those nodes? This way we can check the logfiles on the Cloud side.

You can find the claimed_id by:
`cat /var/lib/netdata/cloud.d/claimed_id`
or the same folder prefixed by `/opt/netdata` depending on your install method

**Comment by prologic** [comment]
@RubenKelevra We haven't had a response from you in a while. Were you able to get these nodes connected after-all? We'd very much like to help you get these online. You should not be receiving 504 Gateway Timeout errors.

**Comment by RubenKelevra** [comment]
It looked like just a fluke at that they. Everything works fine now :)

**Comment by prologic** [comment]
> It looked like just a fluke at that they. Everything works fine now :)

Nice! I'm glad it worked for you finally! We've been hard at work making things more and more stable!
