### ISSUE TITLE
netdata cloud ACLK fail: data too large for modulus

### ISSUE THREAD

**Issue by fayak** [netdata/netdata#9253]
##### Bug report summary

I can't register some netdata nodes to netdata cloud. I followed the instructions, and error.log reports periodically : 

```
2020-06-02 17:30:54: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 1024.000 seconds
2020-06-02 17:47:58: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-06-02 17:47:58: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/60f9eb64-8e0d-11ea-bc11-525400a597de/challenge
2020-06-02 17:47:58: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-06-02 17:47:58: netdata ERROR : ACLK_Main : Decryption of the challenge failed: error:04065084:rsa routines:rsa_ossl_private_decrypt:data too large for modulus
2020-06-02 17:47:58: netdata ERROR : ACLK_Main : Output buffer for encoding size=512 is not large enough for 18446744073709551615-bytes input
2020-06-02 17:47:58: netdata INFO  : ACLK_Main : aclk_send_https_request POST
2020-06-02 17:47:59: netdata ERROR : ACLK_Main : Challenge-response failed: {"errorCode":"TODO trace-id","errorMsgKey":"ErrIncorrectResponse","errorMessage":"incorrect challenge response"}
```

`/api/v1/info` returns:
```
	"cloud-enabled": true,
	"cloud-available": true,
	"agent-claimed": true,
	"aclk-available": false
```

##### OS / Environment

debian 10

```
$ uname -a && lsb_release -a
Linux db-2 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

Also:

```
/var/lib/netdata/cloud.d $ openssl rsa -in private.pem -text -noout
RSA Private-Key: (2048 bit, 2 primes)
# private things
$ cat cloud.conf                                                                                                                                                         
[global]
  enabled = yes
  cloud base url = https://app.netdata.cloud
$ curl https://app.netdata.cloud -I
HTTP/2 200
# normal things
```

##### Netdata version

installed from -edge apt repo

```
$ netdata -V
netdata v1.22.1-184-nightly
```
 

##### Component Name

Netdata cloud I reckon

##### Steps To Reproduce

1. install netdata from apt
2. `sudo netdata-claim.sh -token=bigtoken -rooms=biguuid -url=https://app.netdata.cloud`
3. `systemctl restart netdata`

##### Expected behavior

Having netdata able to contact netdata.cloud

**Comment by underhood** [comment]
Would you be willing to share your agent claimed_id? This way we can go and take a look also from the cloud side.

normally it is stored here `/netdata/var/lib/netdata/cloud.d/claimed_id` or that folder prefixed by `/opt/netdata/...`

Also did you try to reclaim node as suggested by #9206. See https://learn.netdata.cloud/docs/agent/claim#remove-and-reclaim-a-node and last comment on #9206

**Comment by fayak** [comment]
Yes, it's already in the logs I pasted ;) `60f9eb64-8e0d-11ea-bc11-525400a597de`

No I did not, I tried to claim it again, but without removing `cloud.d`, I'll try whenever I can and let you know how it goes

**Comment by fayak** [comment]
Ok so it seems to be working, but I now have 2 servers on netdata cloud, and I don't find how to remove the inactive one ...

**Comment by underhood** [comment]
@fayak thanks, didn't notice that (already shared claimed id) :D. That GitHub scrolling is really awkward :/.

Ok 1st in top left corner of cloud:
![Screenshot from 2020-06-03 10-11-23](https://user-images.githubusercontent.com/6674623/83612603-e97f7f80-a582-11ea-9663-269791c7ca33.png)

Then on right side pannel should open and continue like this:
![Screenshot from 2020-06-03 10-11-49](https://user-images.githubusercontent.com/6674623/83612635-f2705100-a582-11ea-85fc-6b7df9c98f53.png)

Does this help?

**Comment by fayak** [comment]
Awesome, thanks ! I never found that button !

So problem fix for me, I'll let you judge whether this issue should be closed or not

**Comment by underhood** [comment]
Glad to be able to help and thanks for cooperation from your side as well.

Well, our product team already knows about this kind of stuff (not exclusively from #9206).
Just to make sure I am pinging:
- @manos-saratsis I think are improvements planned already.
- @joelhans any docu improvements necessary?
