### ISSUE TITLE
Netdata cloud UI improvement - hiding menu on domain-click

### ISSUE THREAD

**Issue by fayak** [netdata/netdata#9256]
##### Feature idea summary

That's a simple one ....

Could it be possible to have to same behavior when clicking on n°1 than the one when we click on n°2 ? (see attached screenshot)

It's a bit counter-intuitive, I always fall for it first

![netdata](https://user-images.githubusercontent.com/11300056/83612384-a1f8f380-a582-11ea-99ac-b0531714a647.jpg)

##### Expected behavior

The menu hides when clicking on the active domain on the left

**Comment by manos-saratsis** [comment]
@fayak We will not implement your suggestion because by clicking on the Space icons users can navigate to different spaces. Thx for using Netdata Cloud and for sharing your idea with us though!
