### ISSUE TITLE
How to use vendor specific SNMP MIB ? 

### ISSUE THREAD

**Issue by okasap** [netdata/netdata#9258]
##### Question summary
I want to use PAN snmp collector with PAN fw specific mibs. How can i install this PAN-COMMON-MIB and run on netdata
##### OS / Environment
I am running docker version on my MAC. 
Linux version 4.19.76-linuxkit  (gcc version 8.3.0 (Alpine 8.3.0)) #1 SMP Tue May 26 11:42:35 UTC 2020

##### Component Name
netdata
v1.22.1-58-ga01364a8
##### I am getting the error below when I ran 
/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp
2020-06-03 14:03:44: node.d.plugin: ERROR: snmp: 192.168.55.10: OID 1.3.6.1.4.1.25461.2.1.2.3.9.1.7 gave error: NoSuchInstance: 1.3.6.1.4.1.25461.2.1.2.3.9.1.7

**Comment by ilyam8** [comment]
hi @okasap 

can you get a response using `snmpget` from cmd?

**Comment by okasap** [comment]
no..

SNMPv2-SMI::enterprises.25461.2.1.2.3.9.1.7 = No Such Instance currently exists at this OID

**Comment by ilyam8** [comment]
well, try `snmpwalk`

> snmpwalk -v1 -c COMMUNITY 192.168.55.10 1.3.6.1.4.1.25461.2.1.2.3.9.1.7

**Comment by okasap** [comment]
snmpwalk -m PAN-COMMON-MIB -v 2c  -c public 192.168.55.10 1.3.6.1.4.1.25461.
2.1.2.3.9.1.7
PAN-COMMON-MIB::panVsysActiveUdpCps.1 = INTEGER: 0

**Comment by ilyam8** [comment]
then it is

`1.3.6.1.4.1.25461.2.1.2.3.9.1.7.1`

---

this should work

> snmpget -v1 -c COMMUNITY 192.168.55.10 1.3.6.1.4.1.25461.2.1.2.3.9.1.7.1

**Comment by okasap** [comment]
Thanks.. this works ..
