### ISSUE TITLE
Streaming of metrics in netdata 1.12.0-1+deb10u1 (debian.org repo)

### ISSUE THREAD

**Issue by Horkyze** [netdata/netdata#9270]
##### Question summary

Should the streaming of metrics from one netdata instance to another work in the netdata version that is in the official Debian repo - https://packages.debian.org/buster/netdata ?

I have tried it, on Debian Buster, but in the left top corner, I am not able to select the host.
![image](https://user-images.githubusercontent.com/1040383/83748957-45b9d080-a663-11ea-92a5-334c34451528.png)
I verified that the metrics are streaming:
- in logs
- traffic on interface increased. 

**NOTE:** this works as expected in the latest netdata version, even without creating cloud login, I would like to use the version from Debian, because of stability, so thats why I am asking. 

##### OS / Environment

Debian Buster (10)
```
# uname -a
Linux yoda 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux

# netdata -v
netdata v1.12.0
```

##### Expected results
I expect the other host (slave) to be visible in the master node (to which the metrics are streamed)

**Comment by ilyam8** [comment]
Hi @Horkyze 

> netdata v1.12.0

is ancient

> https://github.com/netdata/netdata/releases

**Comment by Horkyze** [comment]
@ilyam8 so there is no way to achieve it in the older version?

**Comment by thiagoftsm** [comment]
Hi @Horkyze ,

Netdata 1.12 had the streaming working and it also had registry, in theory if the package was created with the necessary dependencies, you should have it running. There are features that are only enabled on Netdata during the compilation time, if somehow the maintainers did not allow them, you won't be able to run.

Best regards!
