### ISSUE TITLE
default green/red WARNING/CRITICAL threshold values are set too low for normal operations

### ISSUE THREAD

**Issue by mailinglists35** [netdata/netdata#9272]
##### Feature idea summary
I would not consider this a bug, but I get flooded with notifications whenever I fart in machines where netdata is installed. A bit of file copying -> alerts. a bit of cpu usage -> alerts. a bit of load -> alerts. a bit of iscsi network traffic -> alerts. 

This is insane and returning to normal alertless life (for situations where there is really nothing to worry because it's just normal usage of resources) requires heavy alteration of values in health.d/disks.conf, health.d/load.conf, health.d/disks.conf

##### Expected behavior
I like for example how disk fill estimation works; that is one of great alerts tuned right.

but for disk, load and network I should get only near fatality alerts, not for when I burn the disks for doing a zfs scrub or a 5Tb data transfer over network or run some tasks inside a couple of virtual guests that rise the overall system load. yes, packets happen to drop sometimes and system load increases above 1. but the default values worry really too much for nothing.

**Comment by ilyam8** [comment]
@mailinglists35 hey, we have improved our stock alarms and will keep doing that. If you have specific examples, please share, and let's have a discussion.

**Comment by mailinglists35** [comment]
@ilyam8 I've been thinking about it during holiday while keeping getting email alerts on my phone. I think no matter how we try to tune the thresholds, we also need a third eye to detect false alarms.

I've submitted the idea here: https://community.netdata.cloud/t/false-alarms-detection/1607
