### ISSUE TITLE
Not send telegram notifications when a critical alarm?

### ISSUE THREAD

**Issue by timchou** [netdata/netdata#9275]
here is health_alarm_notify.conf:
`SEND_TELEGRAM="YES"

TELEGRAM_BOT_TOKEN="1168xxxxxxxx"

DEFAULT_RECIPIENT_TELEGRAM="-47xxxxxx"`

when I run test alarm ,I can receive alarms:
/usr/libexec/netdata/plugins.d/alarm-notify.sh test

But I never received a real notification...

Here is a critical situation:

![image](https://user-images.githubusercontent.com/352302/83762798-81c45400-a6aa-11ea-9dd2-9f8d8c8ba48b.png)
 and I didn't receive...

Is there any configure wrong?

**Comment by ilyam8** [comment]
Hi @timchou 

Did you check `error.log`?

**Comment by timchou** [comment]
> Hi @timchou
> 
> Did you check `error.log`?

hi @ilyam8 ,Thanks for replying.

/var/log/netdata/error.log is empty..

**Comment by ilyam8** [comment]
Literally empty? It seems it was rotated, check `error.log.1`

And

i see `china` and `telegram`, any chance it is blocked or something? 😄

**Comment by timchou** [comment]
> Literally empty? It seems it was rotated, check `error.log.1`
> 
> And
> 
> i see `china` and `telegram`, any chance it is blocked or something? 😄

I use VPN :)

I will check the log later, any keyword I can search?

**Comment by ilyam8** [comment]
> VPN :)

reported 👮‍♂️ 😄 

---

There is a way to test notifications

> https://learn.netdata.cloud/docs/agent/health/notifications#testing-notifications

Check it too, it should send message to your tg channel

**Comment by timchou** [comment]
> > VPN :)
> 
> reported 👮‍♂️ 😄
> 
> There is a way to test notifications
> 
> > https://learn.netdata.cloud/docs/agent/health/notifications#testing-notifications
> 
> Check it too, it should send message to your tg channel

[Doge]

@ilyam8 ,the notification test was successfully.I can receive test notifications.
But I never received a REAL notification.Even there are critical alarms in netdata.

Also I didnt see any error about notifications in error.log:(

**Comment by ilyam8** [comment]
Stock alarm 

https://github.com/netdata/netdata/blob/5776deefc2ab4a9c0c47c9ccb78d75d50187f3ab/health/health.d/ram.conf#L26-L37

It has no `delay: up` option, so an notification should have been sent right after the alarm is up.

> Also I didnt see any error about notifications in error.log:(

I suggest to trigger the ararm and check right after it.

**Comment by timchou** [comment]
Hi @ilyam8 Here is a disk space usage alarm happened just now.
and again I didn't receive telegram notify.
Please take a look :)

![image](https://user-images.githubusercontent.com/352302/83986503-98e79800-a96f-11ea-87f4-fa321e789683.png)
this is alarm

![image](https://user-images.githubusercontent.com/352302/83986518-a2710000-a96f-11ea-9005-4712e4e344ba.png)
error log is empty

![image](https://user-images.githubusercontent.com/352302/83986816-b2d5aa80-a970-11ea-8a04-b9ede55542e1.png)
here is a test notify.I can receive it.

![image](https://user-images.githubusercontent.com/352302/83986780-98033600-a970-11ea-9762-f504f927f777.png)
here is headth conf

Thanks

**Comment by thiagoftsm** [comment]
Hi @timchou ,

I was seeing the your files, and I was thinking in the possibility of the Linux is not rotating the logs, if this is happening your `error.log.1` could have data for June 1st, please, can you check if you had the log inside `error.log.1`?

About the telegram, I remember that when I tested the original PR, I had problems to create the configuration, but I found [this link](https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id) that helped me.

Best regards!

**Comment by timchou** [comment]
Hi @thiagoftsm 
Thanks for replying.

I checked error.log.1, there is no info after 2020-5-31:
![image](https://user-images.githubusercontent.com/352302/83989502-35626800-a979-11ea-9c2e-b4eea11ec097.png)


About telegram, I can receive test notify,so I think the group chat id is correct.
![image](https://user-images.githubusercontent.com/352302/83989560-5fb42580-a979-11ea-843d-2d226b745513.png)

any other idea?

**Comment by thiagoftsm** [comment]
I will do another request for we understand exactly what is happening on `alarm-notify.sh`, because we are missing the error.log, this is another problem that we will need to take a look. 

Let us change the file `/usr/libexec/netdata/plugins.d/alarm-notify.sh` Please, add the following line inside the function `send_telegram` between the lines `http_code=$(docurl.. )` and before the line `if [ "$httpcode = "200" ]; then` :

````
echo $httpcode >> /tmp/return_from_curl
``` 

And when the alarm is raised, please, copy the content of the file here.

Best regards!

**Comment by timchou** [comment]
![image](https://user-images.githubusercontent.com/352302/84037152-c31d7200-a9d0-11ea-90f0-3fb1b6e591e6.png)
@thiagoftsm I have added the code and when the alarm raised, I will post here.

Thank you

**Comment by timchou** [comment]
@thiagoftsm 
After one night long,there is no /tmp/return_from_curl file ...Even there is alarm.

![image](https://user-images.githubusercontent.com/352302/84095534-225f9e80-aa32-11ea-9615-d9e26c618696.png)


ls: cannot access '/tmp/return_from_curl': No such file or directory

**Comment by timchou** [comment]
But when I run : bash -x /usr/libexec/netdata/plugins.d/alarm-notify.sh test

I can see the content of /tmp/return_from_curl

**Comment by timchou** [comment]
So it means netdata didn't call "/usr/libexec/netdata/plugins.d/alarm-notify.sh" ?
