### ISSUE TITLE
i cannot export metrics to mongodb

### ISSUE THREAD

**Issue by aokanarik** [netdata/netdata#9280]
##### Question summary
Hello to everyone,

I cannot export metrics to mongodb, even though I have made the destination according to mongo connection string uri and the requirements and configuration settings on exporting engine reference page.

Is there anyone can help me?

**Comment by ilyam8** [comment]
Hi @aokanarik 

What is your nd version? Did you check `error.log`? What is your exporting configuration?

**Comment by aokanarik** [comment]
> Hi @aokanarik
> 
> What is your nd version? Did you check `error.log`? What is your exporting configuration?

nd version is netdata v1.22.1-206-nightly.

Yes, I check it. I saw that: 

"""2020-06-05 16:04:50: netdata LOG FLOOD PROTECTION too many logs (201 logs in 880 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 320 seconds."""

And here you are: export config
[exporting:global]
       enabled = yes
    # send configured labels = yes
    # send automatic labels = no
    # update every = 10


[mongodb:mongodb-connector]
      enabled = yes
      destination = mongodb://admin:admin@mongodb-node-1,mongodb-node-2:27017,mongodb-node-3:27017/?authSource=admin&replicaSet=replicaname
      database = netdata
      collection = netdata_collection
    # data source = average
    # prefix = netdata
    # hostname = my_hostname
    # update every = 10
    # buffer on failures = 10
    # timeout ms = 20000
    # send names instead of ids = yes
    # send charts matching = *
    # send hosts matching = localhost *

**Comment by vlvkobal** [comment]
Please grep for EXPORTING in your log.

**Comment by aokanarik** [comment]
netdata ERROR : EXPORTING : MongoDB support isn't compiled

**Comment by vlvkobal** [comment]
Look at the [documentation](https://learn.netdata.cloud/docs/agent/exporting/mongodb#prerequisites). You should [install libmongoc](http://mongoc.org/libmongoc/current/installing.html).

**Comment by aokanarik** [comment]
Package mongo-c-driver-1.3.6-1.el7.x86_64 already installed and latest version

**Comment by vlvkobal** [comment]
Have you reinstalled Netdata from the source? Find what's wrong with MongoDB support in `config.log` in the Netdata source directory.

**Comment by ilyam8** [comment]
> Package mongo-c-driver-1.3.6-1.el7.x86_64 already installed and latest version

Probably an order? 🤔  you need compile netdata after the package is intalled

**Comment by aokanarik** [comment]
> Have you reinstalled Netdata from the source? Find what's wrong with MongoDB support in `config.log` in the Netdata source directory.

i have reinstall with this command. (curl -Ss https://my-netdata.io/kickstart.sh)

**Comment by aokanarik** [comment]
> > Package mongo-c-driver-1.3.6-1.el7.x86_64 already installed and latest version
> 
> Probably an order? 🤔 you need to compile netdata after the package is intalled

How can I do that?

**Comment by vlvkobal** [comment]
> i have reinstalled with this command. (curl -Ss my-netdata.io/kickstart.sh)

[Install Netdata on Linux manually](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual). Use [`netdata-installer.sh`](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual#install-netdata).

**Comment by aokanarik** [comment]
> > i have reinstalled with this command. (curl -Ss my-netdata.io/kickstart.sh)
> 
> [Install Netdata on Linux manually](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual). Use [`netdata-installer.sh`](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual#install-netdata).

i have reinstalled that way. but issue go on

**Comment by aokanarik** [comment]
![21](https://user-images.githubusercontent.com/32803162/83896129-5437e300-a75c-11ea-94e4-aaf284e046c3.PNG)

this error.log

**Comment by aokanarik** [comment]
> Have you reinstalled Netdata from the source? Find what's wrong with MongoDB support in `config.log` in the Netdata source directory.

i saw that in config.log  but i did not find the version of requested. what can you suggest for this error?
![image](https://user-images.githubusercontent.com/32803162/83928441-7baca100-a798-11ea-9f6f-4fb340ba68d5.png)

**Comment by aokanarik** [comment]
someone can help me?

**Comment by thiagoftsm** [comment]
Hi @aokanarik ,

According your `config.log`, it was identified the version `1.3.6` of libmongoc on your system, this was the motive that your netdata was not installed with support to `libmongoc`. 

I saw you wrote:

```
Package mongo-c-driver-1.3.6-1.el7.x86_64 already installed and latest version
```

I am supposing you used the package manager to install the package. This means that your distribution is not updating `libmongoc` frequently, because the latest version is [1.16.2](http://mongoc.org/) . You can get the latest version from `mongoc` site and compile it with the following commands:

```
# tar xzf mongo-c-driver-1.16.2.tar.gz
# cd mongo-c-driver-1.16.2
# mkdir cmake-build
# cd cmake-build
# cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DCMAKE_INSTALL_PREFIX=/ ..
# make
# make install
```

The `mongoc` site also have instructions to instlall using distribution [packages](http://mongoc.org/libmongoc/current/installing.html), please, check if the steps you did were the same they described.

Best regards!

**Comment by aokanarik** [comment]
> Hi @aokanarik ,
> 
> According your `config.log`, it was identified the version `1.3.6` of libmongoc on your system, this was the motive that your netdata was not installed with support to `libmongoc`.
> 
> I saw you wrote:
> 
> ```
> Package mongo-c-driver-1.3.6-1.el7.x86_64 already installed and latest version
> ```
> 
> I am supposing you used the package manager to install the package. This means that your distribution is not updating `libmongoc` frequently, because the latest version is [1.16.2](http://mongoc.org/) . You can get the latest version from `mongoc` site and compile it with the following commands:
> 
> ```
> # tar xzf mongo-c-driver-1.16.2.tar.gz
> # cd mongo-c-driver-1.16.2
> # mkdir cmake-build
> # cd cmake-build
> # cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
> # make
> # make install
> ```
> 
> The `mongoc` site also have instructions to instlall using distribution [packages](http://mongoc.org/libmongoc/current/installing.html), please, check if the steps you did were the same they described.
> 
> Best regards!


thank you so much, it works.

**Comment by zazer0** [comment]
Still not working in 2025
