### ISSUE TITLE
plugin metrics don't show up in Prometheus

### ISSUE THREAD

**Issue by Dimitrisgian1** [netdata/netdata#9281]
##### Bug report summary
I added a custom plugin to Netdata, which works fine on the Netdata UI and I can see the metrics on http://host:19999/api/v1/allmetrics , but on Prometheus I don't have the option to view my plugin's metrics. I can see all other Netdata metrics on Prometheus and even see the netdata_netdata_pythond_runtime_ms_average with the name of my plugin in the chart name, but none of the data my plugin sends. I enabled the example plugin (provided by Netdata as an example) as well to see if that shows up on Prometheus, but it's the same story. It shows up in netdata_netdata_pythond_runtime_ms_average but has no option to show its own data. 

##### OS / Environment
I am using two seperate VMs, one with Netdata and one with Prometheus and they both run Ubuntu 18.04. It's a simple setup, no master/slave setup, just one simple Netdata and one Simple Prometheus, not using containers either.

```
Linux monitoring-demo-usecasev1-1-1-prometheus-v1-1-vm-1 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.2 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.2 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
netdata v1.22.1-206-nightly
 

##### Component Name
python.d

##### Steps To Reproduce
Below is every command I run on Netdata:
 - mkdir /home/ubuntu/papajohn
 - cd  /home/ubuntu/papajohn
 - sudo wget  https://my-netdata.io/kickstart.sh
 - sudo bash /home/ubuntu/papajohn/kickstart.sh --dont-wait
 - sudo sed -i "s/127.0.0.1/$(hostname -I | awk '{print $1}')/g" /etc/netdata/netdata.conf
 - sudo apt-get install nodejs -y
 - sudo apt-get install npm -y
 - sudo npm install nodejs-websocket 
 - wget https://github.com/papajohn-uop/demo_open/raw/master/f.zip
 - unzip -P otigris ./f.zip
 - sudo cp /home/ubuntu/papajohn/monitor_mme_poc.chart.py /usr/libexec/netdata/python.d/
 - wget https://raw.githubusercontent.com/papajohn-uop/demo_open/master/do.ne
 - sudo cat /home/ubuntu/papajohn/do.ne
 - touch /home/ubuntu/do.ne.txt
 - sudo echo papajohn > /home/ubuntu/do.ne.txt
 - wget -N https://raw.githubusercontent.com/papajohn-uop/demo_open/master/monitor_mme_poc.chart.py
 - sudo cp /home/ubuntu/papajohn/monitor_mme_poc.chart.py /usr/libexec/netdata/python.d/
 - sudo systemctl restart netdata
 - wget -N https://raw.githubusercontent.com/papajohn-uop/demo_open/master/wrap_plugin.sh

Below is every command I run on Prometheus:
 - sudo mkdir /run/mytempdir
 - cd /run/mytempdir && curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest | grep "browser_download_url.*linux-amd64.tar.gz" | cut -d '"' -f 4 | wget -qi -
 - sudo useradd -r prometheus 
 - sudo mkdir /opt/prometheus
 - sudo chown prometheus:prometheus /opt/prometheus
 - sudo tar -xvf /run/mytempdir/prometheus-*linux-amd64.tar.gz -C /opt/prometheus --strip=1
 - sudo touch /etc/systemd/system/prometheus.service
 - sudo echo -e "
     [Unit] 
     \nDescription=Prometheus Server 
     \nAssertPathExists=/opt/prometheus
     \n
     \n[Service]
     \nType=simple
     \nWorkingDirectory=/opt/prometheus
     \nUser=prometheus
     \nGroup=prometheus
     \nExecStart=/opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml --log.level=info
     \nExecReload=/bin/kill -SIGHUP $MAINPID
     \nExecStop=/bin/kill -SIGINT $MAINPID
     \n
     \n[Install]
     \nWantedBy=multi-user.target" > /etc/systemd/system/prometheus.service
 - sudo echo -e "\n  - job_name\0072 '{{ Netdata_IP }}'
     \n
     \n    metrics_path\0072 '/api/v1/allmetrics'
     \n    params\0072
     \n      format\0072 [prometheus_all_hosts]
     \n    honor_labels\0072 true
     \n    static_configs\0072
     \n      - targets\0072 ['{{Netdata_IP}}\007219999']" >> /opt/prometheus/prometheus.yml  
 - sudo systemctl start prometheus
 - sudo systemctl enable prometheus
 - sudo rm -r /run/mytempdir

##### Expected behavior
The expected behavior would be for Prometheus to have an option in the expression drop-down-menu saying something either like netdata_monitoring_mme_poc or like netdata_example.

![Prometheus view](https://user-images.githubusercontent.com/30804541/83878856-6ce8ce80-a745-11ea-963c-4905e749b112.PNG)

![Prometheus expression search](https://user-images.githubusercontent.com/30804541/83879209-f4ced880-a745-11ea-9087-0486966f8117.PNG)

![Netdata UI view](https://user-images.githubusercontent.com/30804541/83878712-3b700300-a745-11ea-996e-27dab7b9d7a0.PNG)

![Netdata allmetrics view](https://user-images.githubusercontent.com/30804541/83878988-a4f01180-a745-11ea-82e6-11fe77f96d4c.PNG)

**Comment by Dimitrisgian1** [comment]
By the way, I do the installation this way because I am doing it through an Orchestrator (OSM) and using the one liner has issues.

**Comment by ilyam8** [comment]
do you see them in?

>  http://host:19999/api/v1/allmetrics?format=prometheus

**Comment by Dimitrisgian1** [comment]
yes! 

![Capture](https://user-images.githubusercontent.com/30804541/83884446-9148a900-a74d-11ea-85b2-e6de0c292180.PNG)

**Comment by ilyam8** [comment]
metrics name is `netdata + chart context + units`, you need to add prexix to your context.

See

https://github.com/netdata/netdata/blob/2b9246a4ae7b69c0bde8466881ebdd5384b9a7a2/collectors/python.d.plugin/apache/apache.chart.py#L26-L27

we always add `collector_name.context`, ^^ `apache.workers`

**Comment by Dimitrisgian1** [comment]
IT'S ALIVE !!! It worked perfectly! Thank you very much for this, I appreciate it very much! You are the best!
