### ISSUE TITLE
Add LSPHP to list of PHP Handlers in apps_groups.conf

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#9282]
##### Feature idea summary

If you are using Litespeed's PHP Handler called LSAPI which is available and supported in recent WHM/CPanel versions then PHP resources are not shown in PHP stats throughout the dashboard (they show as 0 or -).

Please can you therefore add LSAPI recognition by editing the line php: in the web/ftp section of apps_groups.conf to include **lsphp*** 

`php: lsphp* php*`

##### Expected behavior
Use of lsphp* in apps_groups.conf allows Netdata to correctly display PHP usage again when using the LSAPI PHP handler.

Thank you.

**Comment by ilyam8** [comment]
Same https://github.com/netdata/netdata/issues/9283#issuecomment-639553204

If you are, please make it one PR (both this issue and #9283)

**Comment by TheOldMan2000** [comment]
Sorry, newbie here! Don't want to mess it up!

**Comment by thiagoftsm** [comment]
Hi @TheOldMan2000 I created a PR to bring the requested changes, please, test it for us.

**Comment by TheOldMan2000** [comment]
Thanks, that will do nicely sir.
