### ISSUE TITLE
Add Imunify antivirus to apps_groups.conf

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#9283]
##### Feature idea summary

Please add recognition for Imunify antivirus malware scanner by editing the antivirus section of apps_groups.conf to include **imunify360*** as below

`antivirus: clam* *clam imunify360* `

##### Expected behavior

Netdata to recognise Imunify malware/antivirus solutions in WHM/CPanel similar to ClamAV.

Thank you.

**Comment by ilyam8** [comment]
hi @TheOldMan2000 

Are you willing to make a PR?

**Comment by TheOldMan2000** [comment]
Sorry, I'm new to Github and don't understand that side of it yet!

**Comment by thiagoftsm** [comment]
I created only one PR to fix both requests.
