### ISSUE TITLE
Is it still intended to be able to resize chart height using touch iOS iPad?

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#9286]
##### Question summary
Not sure if it's just me, can anyone with an iPad or a touch enabled device please confirm whether it's still possible to resize the height of individual charts on the Netdata Dashboard? It stopped working for me around when the new UI was released with the left-side panel.

##### OS / Environment
iOS 13.4.1 Safari and Chrome browsers.
CentOS 7 Virtuozzo Cloud VPS

##### Component Name
Web dashboard

##### Expected results

Ability to drag to resize the height of charts on Netdata Dashboard.

**Comment by jacekkolasa** [comment]
Hi @TheOldMan2000 indeed, there's a bug, it was working before properly. In case you're not aware - you can always access the old dashboard using `/old` suffix. Thanks for the report!
