### ISSUE TITLE
Netdata can not show cgroups/containers ran by kubelet without access to kubernetes cluster information 

### ISSUE THREAD

**Issue by jiuchen1986** [netdata/netdata#9287]
##### Bug report summary

When we upgrade netdata to 1.22.1, it can not show cgroups/containers ran by kubelet without access to kubernetes cluster information, which worked before 1.20. I've checked out the code, and I believe the problem is here:
![image](https://user-images.githubusercontent.com/33239761/83919496-8b43cf80-a72f-11ea-8226-17344e836109.png)

##### OS / Environment

```
Linux base-image-2 4.12.14-197.34-default #1 SMP Tue Feb 25 13:00:08 UTC 2020 (3701ec1) x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="SLES"
/etc/os-release:VERSION="15-SP1"
/etc/os-release:VERSION_ID="15.1"
/etc/os-release:PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
/etc/os-release:ID="sles"
/etc/os-release:ID_LIKE="suse"
/etc/os-release:ANSI_COLOR="0;32"
/etc/os-release:CPE_NAME="cpe:/o:suse:sles:15:sp1"
```

##### Netdata version

 netdata v1.22.1

##### Component Name

cgroup-name.sh
##### Steps To Reproduce

1. install netdata 1.22.1 on a kubernetes worker node without kubectl/kubeconfig
2. no cgroup/container metrics come out in GUI which are set up by kubelet

##### Expected behavior

Metrics of cgroup/container ran by kubelet should be seen in GUI even without any access to kubernetes.

**Comment by ilyam8** [comment]
related PR: #7416

copying [my comment](https://github.com/netdata/netdata/pull/7416#issuecomment-636196712) from there

> Well, good point. If i understand it right a cggroup is disabled if `cgroup-name` bash script returns `3`, doesnt sound good (but we need to skip pause containers at the same time).

https://github.com/netdata/netdata/blob/885caf08dd41a770489f91db6d226260122e0b94/collectors/cgroups.plugin/sys_fs_cgroup.c#L1171-L1174

https://github.com/netdata/netdata/blob/885caf08dd41a770489f91db6d226260122e0b94/collectors/cgroups.plugin/cgroup-name.sh.in#L114-L117

**Comment by cakrit** [comment]
Please first approve and merge #8671 
After that, we can change the top-level logic to default to the normal container handling, when the k8s-specific naming fails for any reason.

**Comment by cakrit** [comment]
@jiuchen1986 can you please test PR #9321?

**Comment by jiuchen1986** [comment]
@cakrit Sorry for late response. Yes the fix works fine for us now. Thanks for the support.
