### ISSUE TITLE
Add Drone CI Server plugin

### ISSUE THREAD

**Issue by davidak** [netdata/netdata#9288]
##### Feature idea summary

The Drone CI Server exposes some metrics. It would be nice to have a graph from the data.

https://docs.drone.io/server/metrics/

This is how the data looks: https://gist.github.com/davidak/88d4bfedc04806fedf7f6bf3c91934fe

For example:

**Drone CI Stats**

- drone_build_count
- drone_user_count
- drone_repo_count

**Drone CI Builds**

- drone_pending_builds
- drone_running_builds

**Drone CI Jobs**

- drone_pending_jobs
- drone_running_jobs

##### Expected behavior

- Document setup with authentication
- Fetch data from http
- Visualize as graphs

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).

**Comment by davidak** [comment]
I'm actually not interested in Drone anymore since it's not fully open source. There is a fork: https://github.com/woodpecker-ci/woodpecker
