### ISSUE TITLE
Capture tcpdump

### ISSUE THREAD

**Issue by hostingfuze** [netdata/netdata#9292]
##### Feature idea summary
When a ddos attack occurs, the server informs me by email, but I also want to save those traffic captures with the following command:

#    tcpdump -nn -vvv -c 10000 -w ddos-`date +%F_%T`.pcap

where to be saved in a folder for a web server to be easily downloaded and hosted.

**Comment by ilyam8** [comment]
That is possible by writing a custom script (that captures/saves network dump) and using [alarm-line-exec](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-exec).
