### ISSUE TITLE
Streaming agent fails to reconnect to master

### ISSUE THREAD

**Issue by kromit** [netdata/netdata#9300]
##### Bug report summary
Out master went down for maintenance. After restart only about a half of agents were able to reconnect to the master and send streams. Agent error:
```
2020-06-09 08:32:10: netdata INFO  : STREAM_SENDER[sender.domain.com] : STREAM sender.domain.com [send to netdata.domain.com:19999]: connecting...
2020-06-09 08:32:10: netdata INFO  : STREAM_SENDER[sender.domain.com] : STREAM sender.domain.com [send to netdata.domain.com:19999]: initializing communication...
2020-06-09 08:32:10: netdata ERROR : STREAM_SENDER[sender.domain.com] : SSL cannot connect with the server:  error:00000000:lib(0):func(0):reason(0) 
```

Restarting the agent service fixes the issue so it is not a master problem.

##### OS / Environment

Agents run on Centos7 or Centos8. Installed via static kickstarter. No updates were run on agents or something like this.

##### Netdata version

v1.22.1

##### Component Name

streaming

##### Steps To Reproduce

1. setup agent -> master streaming
2. stop master for longer periode > 1h
3. restart master.
4. repeat until agent fails to reconnect.

##### Expected behavior

Agents always reconnects to the master when master is available

**Comment by ilyam8** [comment]
Hi @kromit 

> v1.22.1

what is exact version?

Can you `netdata -v` ?

**Comment by kromit** [comment]
That is the version. The output is `netdata v1.22.1`. 
I do not use nightly updates since it deleted entire configuration on all nodes once.

**Comment by thiagoftsm** [comment]
Hi @kromit ,

Are you using TLS connections?
Another doubt, can you access master dashboard  on slave using `curl`?

Best regards!

**Comment by kromit** [comment]
I am using SSL key and cert on master with
```
bind to = *:8080=dashboard|registry|badges|management^SSL=optional *:19999=streaming
```

But this does not matter since the master is definitively reachable.  Some agents have no trouble reconnecting, some so. Its about 50/50 chance. On exactly identical machines. Restarting the slave agent service fixes the connection issue.

**Comment by mfundul** [comment]
How many slaves would that be? Be sure to check the master's `error.log` for errors. It could also be related to file descriptor limits or something else.

**Comment by kromit** [comment]
20+ nodes total. On the master it looks like this.
```
2020-06-09T11:49:11.839794221Z 2020-06-09 13:49:11: 80431: 112 '[123.x.x.x]:17489' 'CONNECTED'
2020-06-09T11:49:11.839814273Z 2020-06-09 13:49:11: 80431: 112 '[123.x.x.x]:17489' 'DISCONNECTED'
2020-06-09T11:49:16.848683472Z 2020-06-09 13:49:16: 80432: 105 '[123.x.x.x]:17491' 'CONNECTED'
2020-06-09T11:49:16.848718101Z 2020-06-09 13:49:16: 80432: 105 '[123.x.x.x]:17491' 'DISCONNECTED'
2020-06-09T11:49:21.857819287Z 2020-06-09 13:49:21: 80433: 96 '[123.x.x.x]:17493' 'CONNECTED'
2020-06-09T11:49:21.857843804Z 2020-06-09 13:49:21: 80433: 96 '[123.x.x.x]:17493' 'DISCONNECTED'
```
The update rate is set 5 hence the delay.

Again, the master is not the problem. All I need to fix this is to restart the slave, like I've already did 10+ times.

**Comment by amoss** [comment]
It's an interesting issue. The error reported from the openssl library is not very helpful and simply indicates that the underlying BIO failed, but not why. We have seen some problems recently on static installations on CentOS that relate to openssl but they were problems retrieving the certificate roots so they don't apply here. We've made large changes to the streaming code this month but they don't affect this as it involves an older version of the agent.

The test-case scenario (shutting down the receiving node and then allowing the senders to reconnect after a delay) is something that I've done a few hundred times this month without seeing the same problem. I suspect this is because I'm using Debian 10.

We can set up a test sequence to try to replicate the problem but it will take a while due to the nature of the test.

**Comment by amoss** [comment]
And seconds after posting....

This is probably the problem:
```
bind to = *:8080=dashboard|registry|badges|management^SSL=optional *:19999=streaming
```

This configuration is unusual, it means that `HTTPS_ENABLED` is set in the code and some of the connections are SSL but others are not. So after the return from `connect_to_any` we may have a socket in either state. I can take a look at this after we merge the current changes.

**Comment by amoss** [comment]
@kromit Hello, did you try removing the `^SSL=optional` from your configuration to see if it fixes the problem?

**Comment by stelfrag** [comment]
Closing since it has been a while without a response. Please reopen if needed
