### ISSUE TITLE
What causes HTTP_VALIDATION_NOT_SUPPORTED?

### ISSUE THREAD

**Issue by yambakshi** [netdata/netdata#9307]
##### Question summary
I'm receiving HTTP_VALIDATION_NOT_SUPPORTED when requesting charts from Netdata.
What could cause my request to fail on HTTP_VALIDATION_NOT_SUPPORTED?

##### OS / Environment
CentOS 7

##### Component Name
Web

##### Expected results
HTTP will be validated successfully

**Comment by thiagoftsm** [comment]
Hi @yambakshi ,

Netdata only returns this message when the Header sent by the client is not completely understood. What is the software that you are using to do requests for Netdata?

Best regards!

**Comment by yambakshi** [comment]
Hey @thiagoftsm ,
Thanks for the response!
The request is sent sent by the client goes to a proxy server and then to netdata.
These are the proxy request headers:
```
accept:"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
accept-encoding:"identity"
accept-language:"en-US,en;q=0.9,he-IL;q=0.8,he;q=0.7"
connection:"close"
content-length:2
content-type:"application/json"
host:"localhost:9842"
referer:"https://localhost:3001/my-website"
sec-fetch-mode:"nested-navigate"
sec-fetch-site:"same-origin"
upgrade-insecure-requests:"1"
user-agent:"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
x-forwarded-for:"127.0.0.1"
x-forwarded-host:"127.0.0.1"
x-forwarded-proto:"http"
x-forwarded-server:"localhost.localdomain"
```

Thanks!

**Comment by thiagoftsm** [comment]
Hi @yambakshi ,

It looks like that the headers are fine, probably the original request is having problem. I would say possibles problems that come in my mind:

1 - The proxy is not finishing the request with `\r\n\r\n`.
2 - The proxy is using a request that is not expect, for example, `POST`. Netdata works mainly with `GET` and `OPTIONS`.
3 - There is a TLS misconfiguration in one of the sides, either Netadata or Proxy.

Is it possible you use a sniffer like wireshark or tcpdump to get a complete request?

Best regards!

**Comment by yambakshi** [comment]
Thanks @thiagoftsm !
Problem was the proxy server added some redundant headers, request body and request query.
Removing them solved the issue.
Thanks!
