### ISSUE TITLE
Linux slab info

### ISSUE THREAD

**Issue by Daniel15** [netdata/netdata#9314]
Netdata currently displays reclaimable and unreclaimable slab usage:
![](https://d.sb/2020/06/firefox_10-10.51.05.png)

However, it would be useful to also show the types of the slabs that are in use, similar to the output from `slabtop`.

My exact use case is that I'm encountering a memory leak in the kernel with `kmalloc-64` slabs, so I'd like to see how the number and size of `kmalloc-64` slabs is rising over time across all my servers, to see how many are affected by this issue. Just looking at overall slab usage is not sufficient, as it could be other slabs using the memory (like `ext4_inode_cache`, which is totally fine)

`slabtop` sources this information from `/proc/slabinfo`.

**Comment by Daniel15** [comment]
Even just the top 10 types would be useful, or some way of logging particular types (so I could enable it just for the generic `kmalloc-*` types)

**Comment by Saruspete** [comment]
Hello,

This collector is [already available](https://github.com/netdata/netdata/tree/master/collectors/slabinfo.plugin), but indeed was disabled by default as it leads to large quantities of dimensions in some setups.

To enable it, just set it in netdata.conf:
```
[plugins]
  slabinfo = yes
```

Cheers

**Comment by ilyam8** [comment]
thx @Saruspete 

fixed in https://github.com/netdata/netdata/pull/6800

**Comment by Daniel15** [comment]
> 
> 
> Hello,
> 
> This collector is [already available](https://github.com/netdata/netdata/tree/master/collectors/slabinfo.plugin), but indeed was disabled by default as it leads to large quantities of dimensions in some setups.
> 
> To enable it, just set it in netdata.conf:
> 
> ```
> [plugins]
>   slabinfo = yes
> ```
> 
> I may add more configuration features to it, but didn't had any request of this kind so far... but feel free :)
> 
> Cheers

Oh wow, I didn't know about this! Is this documented on the Netdata site anywhere?

**Comment by thiagoftsm** [comment]
Hi @Daniel15 ,

There is a description about this plugin and the motive it is disabled in this [link](https://learn.netdata.cloud/docs/agent/collectors/slabinfo.plugin).

Best regards!

**Comment by Saruspete** [comment]
@Daniel15 If you think of features / configuration / filter that would be useful for this plugin, please tell us (or better, propose a PR :) ) 

I made it to debug kernel issues on trading environment, but I would love to hear about other usages !
