### ISSUE TITLE
cannot claim node - code error 28

### ISSUE THREAD

**Issue by euggge** [netdata/netdata#9319]
##### Bug report summary

whenever i try to claim a node i get the following error:
```
Failed to connect to https://app.netdata.cloud, return code 28.
```
##### OS / Environment

```
Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version

 
netdata v1.22.1-248-nightly

##### Steps To Reproduce

1. ... Install netdata
2. ... Claim node

##### Expected behavior

for the node to be claimed

**Comment by underhood** [comment]
@euggge did you try again after some time? could it be some intermittent unavailability of the `app.netdata.cloud`?

**Comment by euggge** [comment]
i doubt it, i tried it multiple times in the span of 3 days, both with the stable e and the nightlty version, same error

**Comment by underhood** [comment]
are you able to to `wget https://app.netdata.cloud`?
I can try this on RPi tomorrow, I have one lying around (not sure it is 2nd or 3rd gen)

**Comment by euggge** [comment]
yes wget works as expected 
```
--2020-06-11` 20:01:11--  https://app.netdata.cloud/
Resolving app.netdata.cloud (app.netdata.cloud)... 35.196.244.138
Connecting to app.netdata.cloud (app.netdata.cloud)|35.196.244.138|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5238 (5.1K) [text/html]
Saving to: ‘index.html’

index.html          100%[===================>]   5.12K  --.-KB/s    in 0.002s  

2020-06-11 20:01:17 (2.92 MB/s) - ‘index.html’ saved [5238/5238]
```

> I can try this on RPi tomorrow, I have one lying around (not sure it is 2nd or 3rd gen)

thanks!

**Comment by underhood** [comment]
@euggge 
I just tried on a fresh installation of `raspbian`. With Raspbery Pi.

```
root@rpi-devel:~# cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls
            vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

...

Hardware	: BCM2835
Revision	: a01041
Serial		: 0000000078f8f00e
Model		: Raspberry Pi 2 Model B Rev 1.1
```

```
root@rpi-devel:~# cat /etc/debian_version
10.4
```

Installed by: `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --disable-telemetry`

And claimed by **_(as root user)_**:
```
netdata-claim.sh -token=XXXXXXXX -rooms=YYYYYYY -url=https://app.netdata.cloud

Token: ****************
Base URL: https://app.netdata.cloud
Id: XXXXXXXXX
Rooms: YYYYYYYYYY
Hostname: rpi-devel
Proxy: 
Netdata user: netdata
Generating private/public key for the first time.
Generating RSA private key, 2048 bit long modulus (2 primes)
.....+++++
............................+++++
e is 65537 (0x010001)
Extracting public key from private key.
writing RSA key
Node was successfully claimed.
```

![Screenshot from 2020-06-12 11-09-53](https://user-images.githubusercontent.com/6674623/84486910-55a66580-ac9e-11ea-9957-9ddd77a1c0c0.png)


@euggge What install method did you use? Are you behind any proxy/firewall? *(e.g. wget picking up proxy settings but claiming script doesnt?)*

**Comment by underhood** [comment]
What we can try if you still cannot claim it is:
1. Delete all files under `/var/lib/netdata/cloud.d/`.
1. Delete file `/var/lib/netdata/registry/netdata.public.unique.id`.
1. Restart Netdata -> this should generate new identity file `/var/lib/netdata/registry/netdata.public.unique.id`
1. Try to claim again with this new identity (cloud will see your agent as a completely new/fresh).

**Comment by euggge** [comment]
> @euggge What install method did you use? Are you behind any proxy/firewall? (e.g. wget picking up proxy settings but claiming script doesnt?)

i installed via `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
I tried disabling my router's firewall, still no luck. I don't use any proxy

> @euggge What we can try if you still cannot claim it is:
Delete all files under /var/lib/netdata/cloud.d/.
Delete file /var/lib/netdata/registry/netdata.public.unique.id.
Restart Netdata -> this should generate new identity file /var/lib/netdata/registry/netdata.public.unique.id
Try to claim again with this new identity (cloud will see your agent as a completely new/fresh).
This will basically restart the whole process from beginning which might help in case the claiming got stuck in some weird state between unclaimed and claimed due to some random error and cannot recover.

Same error after deleting the files and restarting netdata:

```
# netdata-claim.sh -token=XXXXXXXXX -rooms= YYYYYYYYYY -url=https://app.netdata.cloud
Token: ****************
Base URL: https://app.netdata.cloud
Id: XXXXXXXXX
Rooms: YYYYYYYYYY
Hostname: raspberrypi
Proxy: 
Netdata user: netdata
Generating private/public key for the first time.
Generating RSA private key, 2048 bit long modulus (2 primes)
..........+++++
......................................................+++++
e is 65537 (0x010001)
Extracting public key from private key.
writing RSA key
Failed to connect to https://app.netdata.cloud, return code 28
```

**Comment by underhood** [comment]
Hmmm strange...
Not sure what the problem can be at this point.

If you are willing to play with it a bit you can see the claiming script tries to just use `curl` if available and `wget` as fall back if curl not installed on system.
```
        URLCOMMAND="curl --connect-timeout 5 --retry 0 -s -i -X PUT -d \"@${CLAIMING_DIR}/tmpin.txt\""
```
additionally, we can try and skip the deletion of `tmpout.txt`.
`rm -f "${CLAIMING_DIR}/tmpout.txt"` in netdata-claim.sh and then take a look into it

**Comment by underhood** [comment]
If using curl the error code 28 seems to be:
```
CURLE_OPERATION_TIMEDOUT
    Operation timeout. The specified time-out period was reached according to the conditions. 
```
might make sense to try and increase the --connect-timeout?

**Comment by euggge** [comment]
> might make sense to try and increase the --connect-timeout?

that fixed it! I modified the netdata.claim.sh script following your suggestion as follows:
`URLCOMMAND="curl --connect-timeout 10 --retry 5 -s -i -X PUT -d \"@${CLAIMING_DIR}/tmpin.txt\""`
and I was finally able to claim the node
Thanks again. 

However i wonder why it takes so long to establish a connection. I have a gigabit fiber connection to my home and the rpi wired directly to the router

**Comment by underhood** [comment]
Yes that is definitely weird. What is the load on that raspberry pi? Is it possible that it is simply too busy and TLS handshake is simply not done in time because of that?

**Comment by euggge** [comment]
the load it's usually pretty low and i'm using google dns
```
pi@raspberrypi:~ $ uptime
 16:04:46 up 3 days, 21:30,  2 users,  load average: 0.16, 0.22, 0.45
pi@raspberrypi:~ $ dig

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49441
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;.				IN	NS

;; ANSWER SECTION:
.			86928	IN	NS	j.root-servers.net.
.			86928	IN	NS	d.root-servers.net.
.			86928	IN	NS	e.root-servers.net.
.			86928	IN	NS	i.root-servers.net.
.			86928	IN	NS	m.root-servers.net.
.			86928	IN	NS	b.root-servers.net.
.			86928	IN	NS	g.root-servers.net.
.			86928	IN	NS	c.root-servers.net.
.			86928	IN	NS	f.root-servers.net.
.			86928	IN	NS	h.root-servers.net.
.			86928	IN	NS	k.root-servers.net.
.			86928	IN	NS	a.root-servers.net.
.			86928	IN	NS	l.root-servers.net.

;; Query time: 8 msec
;; SERVER: 8.8.4.4#53(8.8.4.4)
;; WHEN: Fri Jun 12 16:04:53 BST 2020
;; MSG SIZE  rcvd: 239

```

**Comment by underhood** [comment]
hmm, what I think is I close this issue as it seems to be unique for you. I want to improve however the error reporting in claiming script and maybe add flag `--conect-timeout` to it for cases where connection is slower for whatever reason

**Comment by underhood** [comment]
@euggge How about the cloud connection after you claimed it. Is it working OK?

**Comment by euggge** [comment]
The netdata cloud is working flawlessly. I’ll keep investigating on the connection problem on my end. A flag for —connect-timeout could be useful, i agree. Thanks again

**Comment by shimco** [comment]
I experienced a similar issue on about 10 out of 20 the arm boards I installed on.
removing the files mentioned above and then running the netdata-claim.sh script again worked eventually on all devices, (sometimes it took more than 10 attempts).

I used this one liner to speed up the tedious process before retrying netdata-claim.sh again:
`
sudo rm /var/lib/netdata/cloud.d/* ; sudo rm /var/lib/netdata/registry/netdata.public.unique.id ; sudo systemctl restart netdata
`

**Comment by OdysLam** [comment]
Hi @shimco,

Welcome to our community and thanks for sharing your experience! The use-case sounds interesting, would you care to tell us more about it? Is it in a professional setting or you are an IoT enthusiast like me? What boards would those be? (Rpi3/4?)

Cheers :)

**Comment by shimco** [comment]
> Hi @shimco,
> 
> Welcome to our community and thanks for sharing your experience! The use-case sounds interesting, would you care to tell us more about it? Is it in a professional setting or you are an IoT enthusiast like me? What boards would those be? (Rpi3/4?)
> 
> Cheers :)

HI OdysLam,
Thanks for your reply, I'd just like to say aside from this issue during install Netdata has been fantastic, I have been following the project for a while now, using it on a few personal devices first with a view to deploying it on production devices at work once cloud functionality was working, I finally got around to doing that yesterday!

In this case, we have 10 rpi3 boards running Raspbian and 10 orange pi zero boards running Armbian Xenial ( https://www.armbian.com/orange-pi-zero/ ) which are used to provide an SDN to bridge edge locations worldwide. 
When running the netdata-claim.sh script with the -verbose flag the script would hang at the curl command and eventually timeout after roughly 2 minutes. Interestingly, these devices have all been cloned from a base image (one base for each type of board) with identical setups besides hostname and ssh keys so it is unusual that some worked the first time, while others took multiple attempts. They all had a stable internet connection at the time as I was ssh'ed into the remote boxes. 
Only one of the OPZ boards failed to install the first time, the .environment file didn't exist so running kickstart.sh with the --allow-duplicate-install flag fixed that.

As a side note, after playing with Netdata cloud for a day now, for these sort of IOT deployments, it would be great to be able to build a dashboard that can simply display a metric such as system.uptime if a device is online with a green background, and if the device is offline or unreachable show a red background and display how long it has been since data was last received from the device. I want to build something like this that can monitor large numbers of devices on one screen and give access to non-tech based staff who can then easily see the fundamental status of remote devices without overwhelming them. 

Cheers!

**Comment by Ferroin** [comment]
For reference, the numeric error codes are exit codes from cURL, which map to the error codes and descriptions listed [here](https://curl.haxx.se/libcurl/c/libcurl-errors.html). 28 indicates that the request timed out.

**Comment by lvrach** [comment]
I had the same issue when I tried to claim my netdata agent on a Synology NAS `x86_64 GNU/Linux synology_apollolake_718+`.

All my attempts to curl app.netdata.cloud from the NAS took more than 5seconds, where other machines from the same network took around 300ms.

The reason seems to be DNS lookup:
```
curl -w "@/tmp/curl-format.txt" -o /dev/null -s  "https://app.netdata.cloud"
     time_namelookup:  5.020683s
     time_connect:  5.176094s
     time_appconnect:  5.504878s
     time_pretransfer:  5.505039s
     time_redirect:  0.000000s
     time_starttransfer:  5.662840s
	     ----------
    time_total:  5.662942s
 
```
I want to dig (no pun intended) into this further.

It worked after I increased the connect-timeout:
```
-       URLCOMMAND="curl --connect-timeout 5 --retry 0 -s -i -X PUT -d \"@${CLAIMING_DIR}/tmpin.txt\""
+      URLCOMMAND="curl --connect-timeout 15 --retry 0 -s -i -X PUT -d \"@${CLAIMING_DIR}/tmpin.txt\""
```

**Comment by orgoj** [comment]
Same problem with --connect-timeout 5. Increase timeout to 10 is working.

**Comment by ilyam8** [comment]
@Ferroin perhaps increasing connect-timeout on every retry in case of 28 will do. What do you think?
