### ISSUE TITLE
how to disable lxc.monitor

### ISSUE THREAD

**Issue by lds-lds** [netdata/netdata#9325]
hello
since using the snap version of lxd, lxc.monitor and lxc.payload has appeared on the netdata interface
I only need lxc.payload
How to disable lxc.monitor ?
thank you for all your work

**Comment by ilyam8** [comment]
Hi 

Check [plugin:cgroups] `enable by default cgroups matching` in the `netdata.conf.

Syntax: https://learn.netdata.cloud/docs/agent/libnetdata/simple_pattern

**Comment by lds-lds** [comment]
Thank you for this information.
I test as soon as possible

**Comment by lds-lds** [comment]
great il works, thanks :)
[plugin:cgroups]
        enable by default cgroups matching =  !*/init.scope  !/system.slice/run-*.scope  *.scope  /machine.slice/*.service  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.socket  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/*   !/lxc.pivot  !/lxc.payload  !/machine  !/qemu  !/system  !/systemd  !/user  *

**Comment by lds-lds** [comment]
no actually it doesn't work at all.
I don't think I understood the logic to get only lxd.payload

**Comment by lds-lds** [comment]
Ok there is a difference in the organization of the cgroups tree between lxd versions 3.x.x and 4.x.x

example in 3.x.x

```
ls -l /sys/fs/cgroup/memory/

-rw-r--r--  1 root root 0 17 juin  09:26 cgroup.clone_children
--w--w--w-  1 root root 0 17 juin  09:26 cgroup.event_control
-rw-r--r--  1 root root 0 17 juin  08:19 cgroup.procs
-r--r--r--  1 root root 0 17 juin  09:26 cgroup.sane_behavior
drwxr-xr-x  2 root root 0 17 juin  08:19 init.scope
drwxr-xr-x  5 root root 0 17 juin  08:20 lxc.monitor
drwxr-xr-x  5 root root 0 17 juin  08:20 lxc.payload
-rw-r--r--  1 root root 0 17 juin  08:20 memory.failcnt
--w-------  1 root root 0 17 juin  09:26 memory.force_empty
-rw-r--r--  1 root root 0 17 juin  09:26 memory.kmem.failcnt
-rw-r--r--  1 root root 0 17 juin  09:26 memory.kmem.limit_in_bytes
-rw-r--r--  1 root root 0 17 juin  09:26 memory.kmem.max_usage_in_bytes
-r--r--r--  1 root root 0 17 juin  09:26 memory.kmem.slabinfo
-rw-r--r--  1 root root 0 17 juin  09:26 memory.kmem.tcp.failcnt
-rw-r--r--  1 root root 0 17 juin  09:26 memory.kmem.tcp.limit_in_bytes
-rw-r--r--  1 root root 0 17 juin  09:26 memory.kmem.tcp.max_usage_in_bytes
-r--r--r--  1 root root 0 17 juin  09:26 memory.kmem.tcp.usage_in_bytes
-r--r--r--  1 root root 0 17 juin  09:26 memory.kmem.usage_in_bytes
-rw-r--r--  1 root root 0 17 juin  08:19 memory.limit_in_bytes
-rw-r--r--  1 root root 0 17 juin  09:26 memory.max_usage_in_bytes
-rw-r--r--  1 root root 0 17 juin  09:26 memory.memsw.failcnt
-rw-r--r--  1 root root 0 17 juin  08:19 memory.memsw.limit_in_bytes
-rw-r--r--  1 root root 0 17 juin  09:26 memory.memsw.max_usage_in_bytes
-r--r--r--  1 root root 0 17 juin  08:20 memory.memsw.usage_in_bytes
-rw-r--r--  1 root root 0 17 juin  09:26 memory.move_charge_at_immigrate
-r--r--r--  1 root root 0 17 juin  09:26 memory.numa_stat
-rw-r--r--  1 root root 0 17 juin  09:26 memory.oom_control
----------  1 root root 0 17 juin  09:26 memory.pressure_level
-rw-r--r--  1 root root 0 17 juin  09:26 memory.soft_limit_in_bytes
-r--r--r--  1 root root 0 17 juin  08:20 memory.stat
-rw-r--r--  1 root root 0 17 juin  09:26 memory.swappiness
-r--r--r--  1 root root 0 17 juin  08:20 memory.usage_in_bytes
-rw-r--r--  1 root root 0 17 juin  08:19 memory.use_hierarchy
-rw-r--r--  1 root root 0 17 juin  09:26 notify_on_release
-rw-r--r--  1 root root 0 17 juin  09:26 release_agent
drwxr-xr-x 79 root root 0 17 juin  08:19 system.slice
-rw-r--r--  1 root root 0 17 juin  09:26 tasks
drwxr-xr-x  3 root root 0 17 juin  08:19 user.slice


and in lxd 4.x.x

```
ls -l /sys/fs/cgroup/memory/

-rw-r--r-- 1 root root    0 Jun 17 09:52 cgroup.clone_children
--w--w--w- 1 root root    0 Jun 17 09:52 cgroup.event_control
-rw-r--r-- 1 root root    0 Jun 16 04:52 cgroup.procs
-r--r--r-- 1 root root    0 Jun 17 09:52 cgroup.sane_behavior
drwxr-xr-x 2 root root    0 Nov 18  2019 lxc.monitor
drwxr-xr-x 2 root root    0 Jun 14 12:02 lxc.monitor.my-container
drwxr-xr-x 2 root root    0 Nov 18  2019 lxc.payload
drwxrwxr-x 2 root 1000000 0 Jun 14 12:02 lxc.payload.my-container
drwxr-xr-x 2 root root    0 Nov 24  2019 lxc.pivot
-rw-r--r-- 1 root root    0 Nov 18  2019 memory.failcnt
--w------- 1 root root    0 Jun 17 09:52 memory.force_empty
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.kmem.failcnt
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.kmem.limit_in_bytes
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.kmem.max_usage_in_bytes
-r--r--r-- 1 root root    0 Jun 17 09:52 memory.kmem.slabinfo
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.kmem.tcp.failcnt
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.kmem.tcp.limit_in_bytes
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.kmem.tcp.max_usage_in_bytes
-r--r--r-- 1 root root    0 Jun 17 09:52 memory.kmem.tcp.usage_in_bytes
-r--r--r-- 1 root root    0 Jun 17 09:52 memory.kmem.usage_in_bytes
-rw-r--r-- 1 root root    0 Nov 18  2019 memory.limit_in_bytes
-rw-r--r-- 1 root root    0 Apr 28 21:57 memory.max_usage_in_bytes
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.move_charge_at_immigrate
-r--r--r-- 1 root root    0 Jun 17 09:52 memory.numa_stat
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.oom_control
---------- 1 root root    0 Jun 17 09:52 memory.pressure_level
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.soft_limit_in_bytes
-r--r--r-- 1 root root    0 Nov 18  2019 memory.stat
-rw-r--r-- 1 root root    0 Jun 17 09:52 memory.swappiness
-r--r--r-- 1 root root    0 Nov 18  2019 memory.usage_in_bytes
-rw-r--r-- 1 root root    0 Nov 18  2019 memory.use_hierarchy
-rw-r--r-- 1 root root    0 Jun 17 09:52 notify_on_release
-rw-r--r-- 1 root root    0 Jun 17 09:52 release_agent
-rw-r--r-- 1 root root    0 Jun 17 09:52 tasks

```

**Comment by ilyam8** [comment]
@lds-lds 

> I don't think I understood the logic to get only lxd.payload

There is cgroups filter

> https://learn.netdata.cloud/docs/agent/collectors/cgroups.plugin#enabled-cgroups

> Netdata uses the following pattern list (it checks the pattern against the path of the cgroup)

Probably i am missing something, it doesnt work for you?
