### ISSUE TITLE
Unit is not resizing on ebpf charts

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#9332]
##### Bug report summary
Netdata does not have units conversion for `bytes/s` and `B/s`.

##### OS / Environment
```
All  supported OS
```

##### Netdata version
netdata v1.22.1-268-g78a19f94
 
##### Component Name
dashboard

##### Steps To Reproduce

1. Start netdata
2. Start a download
3. take a look on ebpf socket charts

##### Expected behavior
Resize `bytes/s`.

**Comment by thiagoftsm** [comment]
@jacekkolasa I am fixing this for the old dashboard, but I am not sure if this also fixes for the react dashboard.

**Comment by vlvkobal** [comment]
It isn't fixed yet. It should be fixed in https://github.com/netdata/dashboard/issues/88.
