### ISSUE TITLE
cannot find index.html but it runs fine

### ISSUE THREAD

**Issue by zilexa** [netdata/netdata#9334]
##### Question summary
I used the installation instructions to install Netdata on Ubuntu Budgie 19.10 and it runs just fine. However I would like to slightly modify the default system dashboard top overview, adding a temperature gauge. 
Strangely, every documentation online points to /web/index.html. This does not exist in my install! The folder /usr/share/netdata does not even exist. 
The only thing I could find is `/opt/netdata/netdata-web-files/index.html` which contains 16 lines, the 16th line is huge and does not contain anything like the file here: 
https://github.com/netdata/netdata/blob/2ba7db38468400e1b1e8365e30ee8f3b776b9215/web/index.html#L1155

Where is this information (the System Overview top head gauge etc) stored in my case?
##### OS / Environment
Ubuntu Budgie 19.10
##### Component Name
Netdata installed natively using the script from Netdata
##### Expected results
I expect the index.html file to contain the configuration of the System overview. 
I also had expected it in /usr/share/netdata instead of /opt/netdata/netdata-web-files/

**Comment by zilexa** [comment]
Anyone who can point me in the right direction?

**Comment by ilyam8** [comment]
> /opt/netdata/netdata-web-files/index.htm

ho did you install it?

---

This files is in the 

> /opt/netdata/usr/share/netdata/web
