### ISSUE TITLE
Netdata start fails with "database/engine/rrdengineapi.c:80: rrdeng_metric_init: Assertion `0' failed."

### ISSUE THREAD

**Issue by Kovah** [netdata/netdata#9336]
##### Bug report summary
I have an issue similar to #9113 but I am not sure if it's really the same problem. Netdata has stopped yesterday and won't start again:

```
[...]
2020-06-14 06:30:47: netdata INFO  : MAIN : Metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00001.mlf" loaded (size:254011).
2020-06-14 06:30:47: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00002.mlf".
2020-06-14 06:30:47: netdata ERROR : MAIN : FAILED to generate GUID for GET
netdata: database/engine/rrdengineapi.c:80: rrdeng_metric_init: Assertion `0' failed.
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.
```

I can remember that Netdata showed issues with not being able to connect to the cloud or something similar last week, but it worked without issues.

##### OS / Environment
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

netdata v1.22.1-276-nightly

(Which is really weird, because I selected the stable channel when I installed Netdata?!)

##### Steps To Reproduce

I am not sure, as I don't know how this issue is linked to my specific configuration or not.

i already ran the Netdata installer again, but the issue persists.

##### Expected behavior

Netdata should run normally.

**Comment by stelfrag** [comment]
Hi @Kovah would it be possible to share the two metadata log files so we can pin point the issue

- /var/cache/netdata/dbengine/metadatalog-00000-00001.mlf
- /var/cache/netdata/dbengine/metadatalog-00000-00002.mlf

you can send me directly at stelios@netdata.cloud

**Comment by Kovah** [comment]
I sent the files to the email address, as well as the complete error log file in case other information is needed.

**Comment by stelfrag** [comment]
> I sent the files to the email address, as well as the complete error log file in case other information is needed.

Thank you -- files received. We are taking a look right now

**Comment by mfundul** [comment]
@Kovah do you run any custom collectors that are not bundled with netdata?

Can you send any older logs to Stelios (previous `error.log` files) to see what the timeline has been?

**Comment by Kovah** [comment]
I am not sure, I set up Netdata a year ago, but I don't think that I installed some custom plugins. Is there a way to check that?

I sent additional logs to the email address. As far as I can tell, the error first appeared at 2020-06-14 06:30:47, after a log rotation where Netdata seem to have restarted or something. Maybe an update?
