### ISSUE TITLE
Can't reclaim node into netdata cloud

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#9346]
when claim the node to cloud, get back below, and let me know how can I remove the node from cloud and add it back?
```
The cloud may have different credentials already registered for this agent ID and it cannot be reclaimed under different credentials for security reasons. If you are unable to connect use -id=$(uuidgen) to overwrite this agent ID with a fresh value if the original credentials cannot be restored.
Failed to claim node with the following error message:"already claimed"
```

**Comment by joelhans** [comment]
Hi @startryst!

Have you seen these instructions in our docs? https://learn.netdata.cloud/docs/agent/claim#remove-and-reclaim-a-node

If you already claimed the node, you have to delete the `cloud.d` directory, and then run the claiming script again, but add `-id=$(uuidgen)` to the end of it. For example:

```
sudo netdata-claim.sh -token=TOKEN -rooms=ROOM1,ROOM2 -url=https://app.netdata.cloud -id=$(uuidgen)
```

Let us know how that goes and we can try diagnosing other things if it doesn't work.

**Comment by startryst** [comment]
> Hi @startryst!
> 
> Have you seen these instructions in our docs? https://learn.netdata.cloud/docs/agent/claim#remove-and-reclaim-a-node
> 
> If you already claimed the node, you have to delete the `cloud.d` directory, and then run the claiming script again, but add `-id=$(uuidgen)` to the end of it. For example:
> 
> ```
> sudo netdata-claim.sh -token=TOKEN -rooms=ROOM1,ROOM2 -url=https://app.netdata.cloud -id=$(uuidgen)
> ```
> 
> Let us know how that goes and we can try diagnosing other things if it doesn't work.

Thanks, solved exactly as you pointed out!

**Comment by spmsupun** [comment]
Delete the volume if you use docker.
