### ISSUE TITLE
Persist installation logs even when the install was successful.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#9348]
##### Feature idea summary

We currently remove our installation logs after a successful install, even if there were non-fatal errors during the install. This makes it difficult in some cases to figure out what might have gone wrong when optional components didn't get built.

##### Expected behavior

Users are able to view installation logs even for successful installs.

@manos-saratsis

**Comment by prologic** [comment]
Let's prioritise this as low for now; we have much more critical things to get done at the moment; like actually fixing our current backlog of bugs.

That being said; I _think_ a reasonable approach to this is:

- Store the installation log in `/var/log/netdata/installer.log`
- Rotate this to a maximum of N installations/updates where `N` is a small non-zero number.

**Comment by thiagoftsm** [comment]
I liked the option to store the log on `/var/log/netdata/installer.log` we should move with this option instead the local directory,

**Comment by Ferroin** [comment]
Dredging up an old issue that I never responded further to, I agree that the correct approach is to actually put logs under `/var/log/netdata` and use some sanely limited log rotation.

My thoughts would be that this should additionally:

* Create `/var/log/netdata` if it doesn’t exist.
* Rotate any existing install log as the absolute first thing it does.
* If installing under a prefix, ideally place logs where Netdata would place them by default under that prefix.
* Fall back to putting the log in the current working directory if and only if the log directory cannot be accessed and/or cannot be created.
* Rotation should not involve compression (we’re already way too heavy when it comes to installs and upates).
* I would default to saving the logs for the last five installs.

**Comment by Ferroin** [comment]
See also #10472, which should ideally be solved at the same time as this if this issue gets tackled first.

**Comment by raven428** [comment]
@Ferroin  I've performed [several changes](https://github.com/netdata/netdata/compare/c5732041b...19601322a) to enable logging in according to [your dredging](https://github.com/netdata/netdata/issues/9348#issuecomment-881425964). Could you please take a look? If these changes are enough I'll start a pull request, else I'll continue my improvements.

**Comment by bpbbc1979** [comment]
Unsubscribe

**Comment by Ferroin** [comment]
@raven428  Can you please open a PR with the changes? Just open it as a draft (you can select this in a dropdown  and @mention me in the description.  We tend to prefer such an approach because it makes it easier to keep track of discussion about the changes in the context of the project itself.

From a cursory glance, the changes themselves do look pretty good though.

**Comment by raven428** [comment]
replacing the commit owner

**Comment by ilyam8** [comment]
> This makes it difficult in some cases to figure out what might have gone wrong when optional components didn't get built.

I am not sure we need the install log, especially in `/var/log/netdata/`. The described issue was solved with deferred errors. Closing for now, if someone thinks we need it - please reopen.
