### ISSUE TITLE
Automating Netdata plugins enabling/disabling 

### ISSUE THREAD

**Issue by MuhammadMunir12** [netdata/netdata#9357]
##### Question summary
I have a query that is it possible or any way to enable or disable plugins and per-plugin configs automatically? 
Currently we have to enable them manually by editing the **netdata.conf** file that is tedious process sometimes. 
Any insights about automating this thing will be helpful. 

##### OS / Environment
RHEL 7.7

##### Component Name
All
##### Expected results
Getting rid of manually enabling plugin and its configs.

**Comment by ilyam8** [comment]
Hi 

> Getting rid of manually enabling plugin and its configs.

What would you propose?

**Comment by MuhammadMunir12** [comment]
Hey @ilyam8 
I was thinking of bash script or python script, it's just a wild idea or may be there's any other case I'm just looking into it if I can do this or not.

**Comment by ilyam8** [comment]
Related: https://github.com/netdata/netdata/issues/6432

But it is quite complex, far from being refined atm and there is no work underway.

**Comment by MuhammadMunir12** [comment]
yeah but that was just a thought.
