### ISSUE TITLE
Delete unreachable node from Netdata Cloud

### ISSUE THREAD

**Issue by DeWaRs1206** [netdata/netdata#9358]
Hello everyone,
During my tests for Netdata Cloud (which looks awesome btw), I created and delete some nodes that are now displayed as "unreachable". I can't find a way to remove these nodes from the dashboard. Is this possible ?

##### Expected results
Been able to manually remove nodes from the dashboard. 

Thanks a lot for your answer.

**Comment by TSD26** [comment]
Try the Manage Warroom link at the top for whichever room these nodes are in.  From that pop-up menu switch to the middle tab (Nodes).  Checkmark your node, then go to the gear icon - remove.

**Comment by DeWaRs1206** [comment]
@TSD26 thanks, it works. Not really intuitive tbh, but at least it works :) 
Thanks a lot !

**Comment by whysthatso** [comment]
i just had the same question, and i too believe the solution is not too intuitive.

thanks

**Comment by ilyam8** [comment]
There are 2 _not too intuitive_ in a row, perhaps it is something you want to know @manos-saratsis

**Comment by whysthatso** [comment]
as netdata cloud interface is quite new, i'm curious if there's a place where to dump some ui feedback, or feedback in general? i have a bunch of small quirks gathered that don't seem to make too much sense to pollute the agent repo issues with, but might be indicative for some areas to look into for the frontend devs. any advice?

**Comment by manos-saratsis** [comment]
@DeWaRs1206 @whysthatso @TSD26 Thank you for using Cloud and for letting us know your thoughts. Initially we did not provide the ability to remove a node from a War Room through the Nodes View but only through the War Room management screens. I would love to hearing your thoughts please use the help button at the button-right of Netdata Cloud Cc @zack-shoylev

**Comment by whysthatso** [comment]
>  please use the help button at the button-right of Netdata Cloud

not sure what that means, could you be more specific?

**Comment by manos-saratsis** [comment]
Did a typo. See below the button that is on the bottom-right.
<img width="352" alt="Screen Shot 2020-06-18 at 3 19 28 PM" src="https://user-images.githubusercontent.com/19746055/85019330-4e3bfc00-b177-11ea-9a27-e6eff55f48da.png">

**Comment by planetahuevo** [comment]
I just came here to read how to do this. It could be improved...

**Comment by manos-saratsis** [comment]
@planetahuevo sorry for this. We will offer unclaiming early in 2021.
Until then https://learn.netdata.cloud/docs/agent/claim#remove-and-reclaim-a-node
Thx for using Netdata Cloud!

**Comment by brizzbane** [comment]
> @planetahuevo sorry for this. We will offer unclaiming early in 2021.
> Until then https://learn.netdata.cloud/docs/agent/claim#remove-and-reclaim-a-node
> Thx for using Netdata Cloud!

This is still not implemented, correct?

**Comment by HG00** [comment]
Hi folks, 

I saw from here that i need to remove it from the "Manage War Room" view, so i looked for that and found the decoy version under the left menu (More... Manage War Room*s*). From here i can see a list of war rooms, but there's a nodes tab, clicking on that just gives a list of nodes under the claiming script that you can do nothing with. By luck i found that clicking the war room name dropdown gave me the "real" menu i was after - "Manage War Room"

FWIW: An icon or menu per node in the "nodes" view is what i was hoping for, 2nd prize was clicking on the node name which should take me to a node-specific page, and from there i would expect some "node actions" to be available. It might be helpful to add a link to the war room settings in the main/left menu next to the war room name in the list - eg 
* General  [...]
* WarRoom1  [...]
with [...] expanding the same as the menu entry in the main war-room view (I thought this was only a room-switching shortcut, not an actions menu.

**Comment by SR-G** [comment]
I'm 100% confused and i'm not able to find anymore how to remove a node from the UI...

This has always been a very difficult and time-consuming task (i can't believe it's so complex to find this feature inside the UI), but this time, after having upgraded all my agents, i'm not able to find anywhere that remove feature ... is it still availble somewhere ?!

Under "Manage War Room" (from top) > "Manage Nodes", i have a list of nodes, but there is no way (anymore ?) to checkbox anything...

**Comment by jwaring** [comment]
+1 on SR-G comment. I too cannot find a way to remove unreachable nodes

**Comment by iculookn** [comment]
same, found this topic because I could not find a way to remove a node.

**Comment by jwaring** [comment]
Thanks for the quick response @MrZammler. Look forward to the new feature coming out

**Comment by laurnts** [comment]
The option to delete unreachable node from the manage war room is gone in my case
<img width="716" alt="Screenshot 2022-04-22 at 01 49 18" src="https://user-images.githubusercontent.com/5869140/164568957-403793b9-b6e1-4ee1-8241-509ce9ba5ebd.png">

**Comment by ildar170975** [comment]
Confirm. No checkbox to remove a node

**Comment by lamk0006** [comment]
Yes, it is not there anymore. It was there previously back in december-january

**Comment by narcarsiss** [comment]
Same Issue here, We did a decommission of 20 nodes and now :\ stuck with a large list of unreachables.

**Comment by Darkvgold** [comment]
Any changes regarding removing nodes from the web panel?

**Comment by MrZammler** [comment]
Hi guys, sorry there are no news on this, it is still being worked on.

**Comment by nderambure** [comment]
Hello, does the remove a node feature be so hard to add ? I'm a bit confused, the interface is so messy and seems way more complex that removing a node, but I'm sure Netdata Cloud has its reasons ?

**Comment by marmig0404** [comment]
> Hello, does the remove a node feature be so hard to add ?

I would suspect not, given that it existed on the interface not so long ago (thus the closed issue).

**Comment by tiliarou** [comment]
I'm trying netdata these days and can't believe that there is no option to remove nodes ?! WTH...

**Comment by laurnts** [comment]
Yes this kinda horrible, it's getting hard to sort out the unreachable because it's decommissioned or it's really unreachable due to an error. Hopefully it's resolved soon

**Comment by x-zvf** [comment]
Not being able to remove dead nodes is pretty bad, it'd be great if this issue would be prioritised, especially since it was possible in the past...

**Comment by PatTheMav** [comment]
It should be noted that this seems to also impact functionality of the dashboards, as missing nodes will inevitably interfere with the "Overview" tab of the "General" war room, as it will try to fetch data from nodes you cannot remove anymore.

**Comment by danesparza** [comment]
Just came here to try to figure this out.  This is such an old issue.  I'm evaluating Netdata and this is really a major sticking point with evaluation.  It makes netdata look incredibly unprofessional.

**Comment by MrZammler** [comment]
Hi guys!

There is a recent update on this on this discussion thread -> https://github.com/netdata/netdata/discussions/12674.

**Comment by ProfessorManhattan** [comment]
This is like the prettiest UI but I just spent 20 minutes and I couldn't figure it out

**Comment by laurnts** [comment]
<img width="1531" alt="Screenshot 2022-07-05 at 18 08 42" src="https://user-images.githubusercontent.com/5869140/177370919-f356a327-d2c3-4a2c-8eab-32f407fdbf72.png">
Now there is a delete node button exist! Problem solved! 👍

**Comment by cakrit** [comment]
FYI this functionality has been greatly improved with yesterday's deployment. If you access the space settings and go to Nodes, you see the following table that allows you to filter all offline nodes, mass select them and bulk delete them. No more deleting one by one and it works great for the "All nodes" room too.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/43294513/181785148-0d0d9e4f-07ca-4ff8-8dde-10e1f0247763.png">

**Comment by blankster** [comment]
@cakrit, thanks a lot. That made Netdata a lot nicer for people who love keeping their structures clean 👏

**Comment by cakrit** [comment]
The kudos go to @AlexNti @jacekkolasa @burbuli8ra @christophidesp @hugovalente-pm and @dimko

**Comment by uglytunaz** [comment]
This is what worked for me.  Take the node you want to delete offline.  Then under My Nodes in left pane, click on node name.   Should see a pop-up with error message and an option to delete (there maybe a couple of entries in pop-up that have to be deleted)
