### ISSUE TITLE
Unexpected dbengine flushing errors

### ISSUE THREAD

**Issue by Xenthys** [netdata/netdata#9361]
#### Question summary
Should I worry a lot about "netdata.dbengine_global_errors" and the fact it happens on a quite unused server with SSDs? They are far from being loaded or slow according to my hdparm & dd tests, and Netdata itself also reports a very low usage.

#### OS / Environment
Currently running Proxmox 6.2, so using a Debian 10 base.
Linux 5.4.34-1-pve #1 SMP PVE 5.4.34-2 (Thu, 07 May 2020 10:02:02 +0200) x86_64
Netdata stable v1.22.1, nightly unfortunately no longer wanted to start after an update.
Processor model in case it has any use:  Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz

#### Component Name
I assume `dbengine` here, though I let you be the judge as you certainly know more than I do!
![Screenshot](https://my.stupid.pics/RXnHepB.png)

#### Expected results
There shouldn't be any difficulty for Netdata to flush pages on disk given all the margin I have left on the hardware it runs on. This happened after a few days Netdata was running, a service restart apparently did the trick but should probably not be necessary. It may happen again in a few days, I will eventually edit this issue to report back.

**Comment by mfundul** [comment]
Related to https://github.com/netdata/netdata/issues/8384
