### ISSUE TITLE
Have way of disabling sign-in/update/netdata cloud links in default dashboard

### ISSUE THREAD

**Issue by saintaardvark** [netdata/netdata#9362]
##### Feature idea summary

It would be great to have a version of the default dashboard that did not include sign-in/update/netdata cloud links.

##### Expected behavior

The default dashboard is a great summary of activity on the system, but for my users the sign-in, update and netdata cloud buttons will be confusing or irrelevant.  I could imagine a couple mechanisms for achieving this:

- A configuration switch, like the one already in place to turn off Google Analytics, to turn off some or all of these features.

- Another demo page (like the ones already in `web/gui`) that duplicates the functionality of the index page, but without the sign-in/etc.

##### A couple questions

- As I understand it, the default page is configured in a different way than custom dashboards.  Is there somewhere I can see the charts that are used to build that page?

- Would you be open to a PR to add a demo page that implemented this?

**Edit:**  After playing with the dashboard a bit, I realized that `npm run start:node-view` is pretty much exactly what I'm after.  Is there a way to have that view in a separate page?

**Comment by manos-saratsis** [comment]
@saintaardvark Thx for sharing your thoughts. We already provide this option, see:
https://learn.netdata.cloud/docs/agent/aclk#disable-the-aclk

**Comment by saintaardvark** [comment]
Hi @manos-saratsis -- thanks very kindly for pointing that out to me...I had completely missed it when going through the Netdata documentation.  That configuration option is perfect for not displaying the sign-in buttons.  

However, I'm still left wondering:

- Is there a way to disable the "updates available" button?

- Is there a way to have the view shown by `npm run start:node-view` in a separate page?

Many thanks in advance for any help you can give.

**Comment by jacekkolasa** [comment]
hi @saintaardvark !
Currently we don't have an option to disable "updates available" button. To do it, we would need to add a flag to netdata.conf and expose it via api. I'm not sure how big priority would that be, @dim08 what do you think?

Currently there is also no option to display dashboard from `npm run start:node-view` task, this was done only for development purposes. There are no installation scripts to support that build. But if that suits you, you can do it manually: replace `...npm run start` at the end of this task with `...npm run build`, remove `REACT_APP_IS_MAIN_DASHBOARD=true ` from `"build": ` task, and run `npm run start:node-view`. Then you'll have the app built in `/build` directory, you just need to host it.


> As I understand it, the default page is configured in a different way than custom dashboards. Is there somewhere I can see the charts that are used to build that page?

The default dashboard is built dynamically, based on `/dashboard_info.js` and output of `/api/v1/charts`. There is no static html here. If you want to see those charts configuration you can do it by inspecting elements in browser console, for example by doing: `$("[data-netdata]")`

**Comment by manos-saratsis** [comment]
@saintaardvark we do not plan to remove the "updates available"

**Comment by saintaardvark** [comment]
Hey @manos-saratsis and @jacekkolasa - many thanks for the additional info, this helps a lot!

**Comment by haldi4803** [comment]
> @saintaardvark Thx for sharing your thoughts. We already provide this option, see: https://learn.netdata.cloud/docs/agent/aclk#disable-the-aclk

works pretty well with editing the cloud.conf file to no.
But is there a docker variable for this?

**Comment by MrZammler** [comment]
> > @saintaardvark Thx for sharing your thoughts. We already provide this option, see: https://learn.netdata.cloud/docs/agent/aclk#disable-the-aclk
> 
> works pretty well with editing the cloud.conf file to no. But is there a docker variable for this?

Hi @haldi4803 

Can you try with this https://github.com/netdata/netdata/pull/13106 ?

**Comment by sijanec** [comment]
Hello! I added the following configuration

```
# /var/lib/netdata/cloud.d/cloud.conf
[global]
    enabled = no
```

But the Sign in button and the Netdata Cloud advertising bar on the top of the page are still visible. What configuration do I use to remove the advertisements and cloud functionality from the web UI?
![slika](https://github.com/netdata/netdata/assets/42650898/4b1ca49b-4085-4f94-a9a2-f25c36e8a773)

**Comment by Rush** [comment]
@sijanec I have the very same questions. While I appreciate the ability to use Netdata Cloud, I also need an ability to self-host without losing of privacy and without the confusion of different cloud Sign In buttons.
