### ISSUE TITLE
Absence of browser preferred language setting breaks graphs

### ISSUE THREAD

**Issue by amichelic** [netdata/netdata#9371]
##### Bug report summary
When there's no preferred language for web pages set in the browser, charts stop working (JavaScript error). Nothing displayed at all.

##### OS / Environment
Netdata platform doesn't matter. Verified in Firefox: 68.8.0esr (Linux/amd64).

##### Netdata version
netdata v1.22.1-302-g5bc76f3b

##### Component Name
web (dashboard)

##### Steps To Reproduce
1. Open Firefox
2. about:preferences
3. "Choose your preferred language for displaying pages" - click "Choose"
4. remove all language settings so that the list is completely empty
5. click Ok
6. all charts disappear, JS console shows a few stack traces; first one:
```
RangeError: "invalid language tag: "
    xAxisTimeString date-time.ts:97
    axisLabelFormatter dygraph-chart.tsx:236
    x dygraph-tickers.js:435
    a dygraph-tickers.js:214
    addXTicks_ dygraph.js:1937
```

##### Expected behavior
Expect charts to still show data, regardless of language setting.

**Comment by nodiscc** [comment]
This also happens if you set `user_pref("intl.accept_languages",				"en-US, en");` in a Firefox user.js file (such as https://github.com/pyllyukko/user.js/blob/master/user.js#L216). Disabling this preference makes the dashboard work again.

**Comment by jacekkolasa** [comment]
@amichelic @nodiscc thanks for your input! The fix is merged and will be added in next release
