### ISSUE TITLE
Some agents not setting $active_processors alarm variable

### ISSUE THREAD

**Issue by willhseitz** [netdata/netdata#9375]
##### Question summary
I am running a distributed setup with ~10 hosts streaming to a central server. Lately, I have been receiving a lot of "high system load" alerts. After some checking, I found that the `$active_processors` alarm variable is not being set on most of my systems, so the alarm is defaulting to 2 cpu cores (when most of my systems are 8+). When checking `https://my.central.server/host/specific.node/api/v1/alarm_variables?chart=system.load`, there is no `active_processors` variable under `host_variables` on the systems affected.

What's the best why I can debug this? I checked docs and I did not find a way to debug _internal_ plugins, like `proc.plugin`.
Thanks!

##### OS / Environment
Central host: Ubuntu 18
Most streaming nodes: Ubuntu 18

##### Component Name
`system.load`

**Comment by willhseitz** [comment]
also posted on reddit about the issue: https://www.reddit.com/r/netdata/comments/h9jj11/excessive_system_load_alerts_active_processors/

**Comment by thiagoftsm** [comment]
Hi @willhseitz,

Please, can you run the shell script `./daemon/system-info.sh` that is inside netdata repo on a system that is not setting properly the variable and give us the output?

best regards!

**Comment by willhseitz** [comment]
@thiagoftsm thanks, is there an email I can send the info to, please?

**Comment by thiagoftsm** [comment]
Hello @willhseitz , please, send to thiago@netdata.cloud.

**Comment by thiagoftsm** [comment]
Hi @willhseitz ,

Thank you very much to report us the problem and to send me the email, thanks your email I could eliminate a possible source of problem.
I tested Netdata 1.22.1  as child and I observed that the missed variable was present with it, I also tested the latest version of Netdata and I could not find more the variable.
Please, can you run the command `netdata -v` on a host that has the variable present? I am working with the team now to find the PR that removed this variable.

Best regards!

**Comment by willhseitz** [comment]
All my servers are set to autoupdate on the nightly build. Both with and without variable are on `netdata v1.22.1-303-nightly`.

In case it helps, I just emailed the system-info for one of our servers that _does_ have the variable set

**Comment by thiagoftsm** [comment]
Hi @willhseitz ,

Today I discovered that we are having problems on sender process that is not sending sometimes the missing variables to the receiver process.
We will work to fix this during this week.

best regards!

**Comment by willhseitz** [comment]
Hi @thiagoftsm and @amoss , I manually updated some systems that didnt have the host variables via the kickstart script to `v1.22.1-318-nightly`, but I am still not getting those variables some times. Is #9396 included in the nightly build?

**Comment by thiagoftsm** [comment]
Hi @willhseitz ,

It looks like that our kickstart has a problem, I am running the latest Netdata now, and we have the version `netdata v1.22.1-331-g641a4592` not the version you are running.
@Ferroin, please, can you confirm the version of the latest nightly?

Best regards!

**Comment by ilyam8** [comment]
> https://storage.googleapis.com/netdata-nightlies/latest-version.txt

`v1.22.1-318-nightly`

**Comment by thiagoftsm** [comment]
Thank you @ilyam8 !

**Comment by thiagoftsm** [comment]
Hello @willhseitz ,

I retest now using a VM and I observed that the variable was sent to `receiver`. I decided to expand the test to be sure that this was not a coincidence, so I created 10 LXC clients and I configured the stream on them. When they connected to the `receiver` all hosts sent the correct variables, please, can you also update the `receiver` to confirm that the problem was fixed? I am believing that thanks the fact the master was not updated or restarted, the problem persists.

Best regards!

**Comment by amoss** [comment]
I don't think that the version running on the parent node (receiver) will make a difference. As long as the child node (sender) is running the new code the problem should be fixed. Can we find out why the kickstart has delivered the old version (@prologic / @Ferroin ) ?

**Comment by ilyam8** [comment]
@willhseitz hi

the fix was not in the nightly at that moment, now it is, you need to update your nd instances one more time

**Comment by amoss** [comment]
@willhseitz, it turns out that working out which commits were in the nightly was slightly more complex that we realized. @ilyam8 has a nice trick for doing it:
```
git rev-list $(git describe --abbrev=0)..HEAD --reverse | awk NR==318
```
This shows that the nightly was the day before the fix was merged. The nightly that had index `337` and onwards contain the fix.

**Comment by thiagoftsm** [comment]
> I don't think that the version running on the parent node (receiver) will make a difference. As long as the child node (sender) is running the new code the problem should be fixed. Can we find out why the kickstart has delivered the old version (@prologic / @Ferroin ) ?

I am thinking that this can be another bug, all the tests that I made with success had a common pattern, I compiled both parent and children. It is possible that when the child is sending the data, some variables are not updated.
