### ISSUE TITLE
Netdata Cloud - Alarms not viewable

### ISSUE THREAD

**Issue by Rhywden** [netdata/netdata#9385]
I updated the clients to the latest versions through the bash script in case that is somehow related.

But basically the issue is this: When using Edge Chromium, I'm seeing alarms on some clients but when I then click on said clients, the Alarms tab states that there are no issues. Though I can actually see the details for the alarms for about half a second before they vanish.
I then tried a different browser (Firefox), this browser displayed the alarms for a while and I chalked it up to incompatibilities. However, after a short while Firefox did the same thing.

The screenshot should show the problem quite clearly:

![image](https://user-images.githubusercontent.com/84586/85186054-1af08e80-b297-11ea-9ca1-71c77ab82fa7.png)

You can also see that the console threw no errors. It's a bit difficult to triage problems if I don't see the info about them.

**Comment by phiberoptick** [comment]
I thought it was just me.

I can confirm I have been getting the same recently in Chromium on Arch Linux.
Version 83.0.4103.106 (Official Build) Arch Linux (64-bit)

When first loading the page and clicking on any of the nodes to bring up the alarm screen, it is usually blank:
![Screenshot_2020-06-20_20-36-08](https://user-images.githubusercontent.com/2384869/85214191-f697bf00-b335-11ea-8d3e-541fb6005aa6.png)

If I reload the page, I get this:
![Screenshot_2020-06-20_20-39-48](https://user-images.githubusercontent.com/2384869/85214210-33fc4c80-b336-11ea-9206-2135072d3551.png)

Finally, if I click to be brought to the alarm, this is what I see:
![Screenshot_2020-06-20_20-35-17](https://user-images.githubusercontent.com/2384869/85214224-555d3880-b336-11ea-8c83-478b04367852.png)

When following one of the links that shows 404 in the error console, I receive this error:
`{"ErrorCode":"","ErrorMsgKey":"ErrNodeResourceNotFound"}`

**Comment by manos-saratsis** [comment]
@Rhywden @phiberoptick thx for your comments, we will investigate and come back to you soon.

**Comment by Rhywden** [comment]
Seems to have been fixed. Thank you also for setting a max-height for Nodes in the overview - previously I could not use the "Total Network Bandwidth" because one node had over 20 virtual devices (due to Docker).

**Comment by manos-saratsis** [comment]
@Rhywden still not fully fixed but we are on it
