### ISSUE TITLE
Automatic Unit Conversion Does Not Work For d3pie Charts

### ISSUE THREAD

**Issue by NoahTroy** [netdata/netdata#9386]
I currently have a pull request open to add support for Vnstat to netdata. I've noticed, however, that the d3pie charts I'd like to use do not automatically convert all units, like the stacked charts do. This has been noticed by several testers across different OS's. You can find the full code/implementation in [this pull request](https://github.com/netdata/netdata/pull/8955).

If you do not want to set up your own server, feel free to [look at my test server](http://51.79.87.85:19999/#menu_vnstat_submenu_average_data_rate_ens3;theme=slate) as an example, which already has the Vnstat plugin installed, and is currently demonstrating the problem with certain units (for example, values provided in kilobits/s convert fine, but not values provided in bytes).

If you have any questions or need any more information, please feel free to let me know.

**Comment by jacekkolasa** [comment]
@NoahTroy you were absolutely right, d3pie was not using auto-scaling properly, fix is merged, thanks!

**Comment by NoahTroy** [comment]
I'm glad it's been fixed, thank you! :)
