### ISSUE TITLE
External collectors (orchestrators) file locking jobs registry

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#9387]
### Feature idea summary

Related https://github.com/netdata/product/issues/1143

One and only one job with same `moduleName_jobName` should be in the running state. It is easy to achieve for a plugin and we do it.

The problem: we cannot guarantee that this condition is met globally - across all plugins. There is no single source of truth at the moment.

This allows us to get rid of [_disabled by default_](https://github.com/netdata/go.d.plugin#why-disabled-how-to-enable) workaround and make any migration (py=>go, bash=>go, bash=py) easier.

---

We decided to use file locks to sync between plugin.

General flow:

- Netdata sets `NETDATA_LOCK_DIR` env variable, plugins  use it to store lock files.
- a plugin should _register_ a job before the job starts.
- a plugin should _unregister_ a job after the job stops.
- it is not mandatory to release all lock on process exit (os does it for us, it closes all FDs on a process exit => releases all the locks).
- a plugin should keep file lock (open fd) acquired while the job is up and running.

Register:
- create the file lock if it is not created
- acquire the lock

Unregister:
- release the lock

Registration call result:
- on **success**: start the job
- on **fail**: drop the job.
- on **error**:
  - _too many open files error_: drop the job.
  - any other: go.d starts, other drop.

##### Expected behavior

The following plugins implement file locking registry.

- [ ] charts.d
- [x] python.d
- [x] go.d
- [ ] node.d

**Comment by ilyam8** [comment]
> a plugin should keep file lock (open fd) acquired while the job is up and running.

@mfundul have we ever had problems with open files limit? I know there is _per process_ limit, external plugin are processes, so not a big deal, but i think there is _per user_ limit 🤔

**Comment by Ferroin** [comment]
Per-user limits only exist if the system administrator has configured them, and most sysadmins do not do so.

However, there may be _per-service_ limits imposed by systemd or through whatever container orchestration the user may be running Netdata under, but those are usually also only present if the sysadmin configures them.

**Comment by ilyam8** [comment]
> there may be per-service limits imposed by systemd or through whatever container orchestration the user may be running Netdata under, but those are usually also only present if the sysadmin configures them.

There are limits per process, i noticed it working on [go plugin file locking registry](https://github.com/netdata/go-orchestrator/pull/45).


linux open files limit

```cmd
[ilyam@ilyam-pc ~]$ ulimit -n
1024
```

macOS open files limit

```cmd
64 ilyam:helmchart (master)$ ulimit -n
256
```

**Comment by ilyam8** [comment]
I doubt we want to add it to bash/node.d plugins
