### ISSUE TITLE
error: automatic one-line installation script

### ISSUE THREAD

**Issue by pkrasam** [netdata/netdata#9390]
##### Question summary
I ran the one-line installation script `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` and `systemctl status netdata` shows errors

##### OS / Environment
Operating System: Ubuntu 18.04.4 LTS
Kernel: Linux 4.15.0-88-generic

##### Component Name
netdata

##### Expected results
```
CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
SIGNAL: Not enabling reaper
netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
```

**Comment by prologic** [comment]
Is your Netdata Agent otherwise operating normally? Can you access the Agent Dashboard by visiting http://IP:19999/

**Comment by arturrocha** [comment]
Same here, seeing syslog error for that. Netdata works normally. http access normal.

2020-06-24 07:24:38 | xxxx | Error (3) | EBPF.PLUGINPROCFILE PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
-- | -- | -- | --
  | 2020-06-24 07:24:37 | xxxx | Error (3) | EBPF.PLUGIN Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.

**Comment by prologic** [comment]
I _think_ these errors in the logs are somewhat normal. We have a bit of a verbose/noisey logging AFIAK. cc @amoss / @ilyam8 to confirm.

**Comment by amoss** [comment]
This is normal. It is because our logging does not distinguish between errors and infos. There is an issue created to fix it, should be in one of the next sprints. I can't link it here as it is in the product repo (cc @netdata/product).

**Comment by ilyam8** [comment]
Both errors from https://github.com/netdata/netdata/issues/9390#issuecomment-649061830 should be `info` level @thiagoftsm. It is ok to not have configuration in the user dir.

**Comment by prologic** [comment]
Thanks @amoss !

@pkrasam I think we can close this. As stated these are "normal" (_for various definitions of normal_) and as long as Netdata is operating for you otherwise there is no bug/problem here I can. see. Feel free to close the issue yourself if you're all good.

**Comment by thiagoftsm** [comment]
> Same here, seeing syslog error for that. Netdata works normally. http access normal.
> 
> 2020-06-24 07:24:38 | xxxx | Error (3) | EBPF.PLUGINPROCFILE PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
> 
> 2020-06-24 07:24:37 | xxxx | Error (3) | EBPF.PLUGIN Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.

Hi @arturrocha ,

These messages are default messages, the plugin tries to load some files that users edited first, it this is not possible, it loads the stock files.

Best regards!

**Comment by ilyam8** [comment]
@thiagoftsm what do you think about https://github.com/netdata/netdata/issues/9390#issuecomment-649460961

I see no reason for those messages to be `error` level, i would even call it a bug

**Comment by thiagoftsm** [comment]
I think it is a good approach @ilyam8, I am creating an issue now and when the code freeze finishes, I will create a PR doing this.

**Comment by arturrocha** [comment]
based on rsyslog doc [1], I added this to /etc/rsyslog.conf to filter the messages before sending to the syslog server.

:msg, contains, "Cannot open file '/etc/netdata/apps_groups.conf'" stop
:msg, contains, " Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file." stop

[1] https://www.rsyslog.com/doc/v8-stable/configuration/filters.html

**Comment by cybersholt** [comment]
I had something similar happen after a reboot, same error message "netdata INFO  : MAIN : SIGNAL: Not enabling reaper", netdata service would just hang, the only thing that I've changed recently is to claim it with netdata cloud, I tried several other solutions such as reinstalling, reinstalling via different method & in the end I had to uninstall and reinstall then it worked out fine.


   Static hostname: server.cybersholt.com
         Icon name: computer-vm
           Chassis: vm
        Machine ID: f4719bcac02f437eba1f2df68f5455de
           Boot ID: 462b2cfc08e74a878b94aa3e9509cc92
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1127.8.2.el7.x86_64
      Architecture: x86-64

netdata -v
netdata v1.23.0-9-nightly
