### ISSUE TITLE
Typo in netdata/packaging/installer/methods/synology.md

### ISSUE THREAD

**Issue by meulie** [netdata/netdata#9395]
#3 of Create startup script mentions:
Make sure /etc/rc.local is executable: chmod 0755 /etc/rc.netdata

This should be:
Make sure /etc/rc.netdata is executable: chmod 0755 /etc/rc.netdata

**Comment by ilyam8** [comment]
hi @meulie, are you willing to make a PR with the fix?

**Comment by meulie** [comment]
Willing: yes. Knowledgeable how to: not, unfortunately...  :$

**Comment by ilyam8** [comment]
Oh oh, so it would be your first PR? No worries, not a big deal

> https://opensource.com/article/19/7/create-pull-request-github
> https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
