### ISSUE TITLE
Groom Inform Cloud about ACLK failure after claiming

### ISSUE THREAD

**Issue by underhood** [netdata/netdata#9401]
#### Feature idea summary
Product Ask: 
 - "Claim for 1st time. If the claiming is successful but the ACLK is not established we should provide hints to the user and if possible send a hint to the Cloud so additional info can be presented to the Cloud users"

##### Expected behavior
On Cloud we should be able to show different messages for Unreachable agents:
- ACLK dependencies are not installed
- No connectivity to Cloud
- Offline
- Initiation phase

**Comment by underhood** [comment]
@netdata/cloud-be should we create an HTTPS endpoint for this (where agent can report failure to make ACLK connection)?

**Comment by underhood** [comment]
@manos-saratsis is this still valid issue? Do we have new one that replaces this one?

**Comment by manos-saratsis** [comment]
@underhood this is still valid. ACLK needs to be traceable. Cloud needs to know all the connects & disconnects and if possible the reason why eg timeout, connection refused, libraries missing. An endpoint will help.

**Comment by underhood** [comment]
This will be achieved by combination of:
https://github.com/netdata/netdata/issues/13705
https://github.com/netdata/netdata/issues/12626
and the elastic events in cloud
