### ISSUE TITLE
Update agent build system

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#9403]
#### Summary

Switch the agent to a semi-static build. All external dependencies other than libc will be statically linked into the agent so that we have a known configuration of dependency versions. Each dependency can be overridden individually to link against system libraries or pre-supplied versions.

**Comment by amoss** [comment]
@prologic We had some details left over to clear up after the meeting. Let's discuss them here. I've started by linking in a couple of existing open issues (the request to support system libraries instead of our custom deps, and the need for a machine-readable list of deps).

**Comment by prologic** [comment]
List of open issues I'm aware of:

- eBPF support (_plan in the works_)
- How we should handle NodeJS / Python collectors.
- Can this approach work on really old systems with super old Kernels? e.g: 2.x?
` `#ifdef` checks at compile time, accept4()
- different variants of builds

This is the current list of "open issues" I am aware of that we need to discuss/resolve. Other than that the rest of the plan is sound and we'll cut issues appropriately and iteratively deliver this in parallel to what we have until we can deprecate and remove the old distribution methods.

**Comment by prologic** [comment]
Not stale. Waiting on @amoss to get back from vacation...

**Comment by prologic** [comment]
Not stale.
