### ISSUE TITLE
Exporter prefix parameter seems broken

### ISSUE THREAD

**Issue by aurrelhebert** [netdata/netdata#9405]
##### Bug report summary
I added a Graphite exporter datasource with a prefix set as below:

```
[graphite:Test_Graphite]
enabled = yes
destination = 127.0.0.1:2003
prefix = test
hostname = localhost
send charts matching = system.cpu
```

And when listening for the TCP output I got:
```
netdata.HOSTNAME.local.system.cpu.user;_os_name=mac;_os_version=10.13.6;_kernel_version=17.7.0;_system_cores=N;_system_cpu_freq=YYYYYY;_system_ram_total=unknown;_system_disk_space=XXXX;_architecture=x86_64;_virtualization=unknown;_container=unknown;_container_detection=none;_virt_detection=none;_is_master=false 34.7498290 1592938577
```
I expected to get "test" as metrics prefix.

##### OS / Environment
- uname -a; sw_vers                      # macOS

```
Darwin HOSTNAME 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G8037
```

##### Netdata version
netdata: stable 1.22.1
Diagnose infrastructure problems with metrics, visualizations & alarms
https://netdata.cloud/
/opt/netdata/1.22.1 (596 files, 8.5MB) *
  Built from source on 2020-06-23 at 18:17:38

##### Component Name
Graphite exporter

##### Steps To Reproduce
1. Start a Graphite exporter
2. Listen to the TCP connection

##### Expected behavior
All my metrics were prefixed by netdata when I expected a custom set prefix (test here)

**Comment by vlvkobal** [comment]
Please add the prefix to the global section
```
[exporting:global]
prefix = test
```
Does it work for you?

**Comment by aurrelhebert** [comment]
Indeed with the global prefix it's working fine! Thanks for the turnaround :)
