### ISSUE TITLE
Segmentation fault (code=killed, signal=SEGV

### ISSUE THREAD

**Issue by marioem** [netdata/netdata#9411]
#### Bug report summary

I'm running Netdata on seven Raspberry Pis, on one of them the daemon dies after day of working due to segmentation fault:
```
$ sudo systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Wed 2020-06-24 23:54:24 CEST; 24s ago
  Process: 1295 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 1296 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 1297 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 1298 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 1299 ExecStart=/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D (code=killed, signal=SEGV)
 Main PID: 1299 (code=killed, signal=SEGV)
```
[error.log.1.zip](https://github.com/netdata/netdata/files/4828227/error.log.1.zip)

Removing /var/cache/netdata resolves the issue (I'm not expecting however this to be a permanent fix).

##### OS / Environment

Raspberry Pi 3 A+
[syslog.1.zip](https://github.com/netdata/netdata/files/4828232/syslog.1.zip)

```
Linux raspi-06 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

```

##### Netdata version
```
netdata v1.22.1-332-nightly
 ```
 

##### Steps To Reproduce
Nothing particular. I've just installed it via 
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

and... boom SEGV

##### Expected behavior
No segmentation fault

**Comment by mfundul** [comment]
@marioem after removing `/var/cache/netdata` did you see the issue again or is it not reproducible anymore?

**Comment by marioem** [comment]
Less that 24 hours after removing `/var/cache/netdata` it is still up and running.

**Comment by marioem** [comment]
Still up 40 hours after removing cache.

**Comment by marioem** [comment]
But less that 72 hours after it is back
```
Jun 27 07:30:41 xxxxxxxx systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
```

**Comment by amoss** [comment]
Can we have a copy of your database cache before you delete it? It will be a huge help to us in replicating the crash so that we can fix it. If you are happy to share the data then please chat to @mfundul about sending a copy so that he can analyse how it has been corrupted.

**Comment by mfundul** [comment]
You can send any files you don't want to share publicly, but don't mind sending to netdata, to my e-mail (markos@netdata.cloud) or to support@netdata.cloud

**Comment by bjoe2k4** [comment]
Same here on a raspi3b with raspbian buster. I could send the /var/cache/netdata folder (has about 1hr of logs with 10s interval) if @marioem hasn't sent yet.

**Comment by mfundul** [comment]
> 
> 
> Same here on a raspi3b with raspbian buster. I could send the /var/cache/netdata folder (has about 1hr of logs with 10s interval) if @marioem hasn't sent yet.

Great. Please send `var/log/netdata/*` and `var/cache/netdata/*` to markos@netdata.cloud

**Comment by bjoe2k4** [comment]
Done.

**Comment by marioem** [comment]
Got another SEGV, this time it was quick to get there. @mfundul, I've sent you two tarballs, hope you've got them.

**Comment by mfundul** [comment]
@marioem @bjoe2k4 can you test #9436 ?
To compile from source you can do the following:
```
git clone https://github.com/netdata/netdata.git
cd netdata/
git fetch origin pull/9436/head:PR9436
git checkout PR9436
```

To get any additional changes from the PR if it's needed you'd have to run:
```
git pull origin pull/9436/head
```
from the same `netdata/` directory.

To replace the existing installation you need to run the installer. Run those from the `netdata/` directory:
```
sudo ./netdata-installer.sh
```

**Comment by bjoe2k4** [comment]
I can confirm it's working again with #9436  (I didn't delete the old netdata folders which produced the crash).

FWIW, i got also quite confused from the error log where timestamps are mixed, go.d uses utc-time whereas everything else uses localtime.

**Comment by mfundul** [comment]
> 
> 
> I can confirm it's working again with #9436 (I didn't delete the old netdata folders which produced the crash).
> 
> FWIW, i got also quite confused from the error log where timestamps are mixed, go.d uses utc-time whereas everything else uses localtime.

The timestamps are a different issue: https://github.com/netdata/netdata/issues/8949

**Comment by ilyam8** [comment]
> go.d uses utc-time whereas everything else uses localtime.

balme netdata daemon 😄 

https://github.com/netdata/netdata/issues/8949#issuecomment-638294959

**Comment by marioem** [comment]
Same for me, compiled with #9436 and launched with old cache folders, and it's working for the time being. Will keep you posted after 24h.

**Comment by ratulb** [comment]
Same issue here - in ubuntu 20.04 lxc container.

root@worker-1:~# systemctl status containerd
● containerd.service - containerd container runtime
     Loaded: loaded (/etc/systemd/system/containerd.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: signal) since Sun 2020-10-11 09:37:45 UTC; 2s ago
       Docs: https://containerd.io
    Process: 2577 ExecStart=/usr/local/bin/containerd (code=killed, signal=SEGV)
   Main PID: 2577 (code=killed, signal=SEGV)
Oct 11 09:37:45 worker-1 systemd[1]: containerd.service: Main process exited, code=killed, status=11/SEGV
Oct 11 09:37:45 worker-1 systemd[1]: containerd.service: Failed with result 'signal'.

**Comment by ratulb** [comment]
Also,
**There is no /var/cache/netdata**
root@worker-1:~# ls -la /var/cache/netdata
ls: cannot access '/var/cache/netdata': No such file or directory

**Comment by mfundul** [comment]
@ratulb please create a new issue and include all the required information (from the issue template), plus the logs (e.g. found in `var/log/netdata/` with the relevant path prefix if required, (e.g. `/opt/netdata/var/...`).

**Comment by ratulb** [comment]
Apologies!!!

Figured out my containerd binary got corrupted.

Thanks anyway.
________________________________

**Comment by OdysLam** [comment]
Welcome to our community @ratulb ! We are glad that you made it work in the end :)
