### ISSUE TITLE
alarm-notify.sh critical severity filtering behavior change with CLEAR alarm email notifications?

### ISSUE THREAD

**Issue by dwdixon** [netdata/netdata#9412]
##### Question summary
I upgraded to netdata 1.22.1 (previously on 1.18.x) and it seems that now when the email alarm recipients are set to receive critical alarms (e.g.  `username@domain.com|critical` ) via health_alarm_notify.conf that they do not receive the corresponding CLEAR notification when the CRITICAL alarm clears...?  Am I doing something stupid or missing something obvious or did something change between 1.18.x and 1.22.1 that breaks this?  My health_alarm_notify.conf worked fine sending corresponding CLEAR emails prior to upgrading to 1.22.1 ?
##### OS / Environment
Tested this and reproduced on both Ubuntu 16.04 LTS and 18.04 LTS w/ sendmail.
##### Component Name
health?
##### Expected results
Shouldn't the email addresses configured to receive critical alarms also receive the corresponding CLEAR alarms for the CRITICAL alarms that have fired?

```
+ echo '# SENDING TEST CLEAR ALARM TO ROLE: sysadmin'
# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
++ hostname
++ date +%s
+ /usr/libexec/netdata/plugins.d/alarm-notify.sh sysadmin servername 1 1 3 1593043002 test_alarm test.chart test.family CLEAR CRITICAL 100 90 /usr/libexec/netdata/plugins.d/alarm-notify.sh 1 3 units 'this is a test alarm to verify notifications work' 'new value' 'old value' 'evaluated expression' 'expression variable values' 0 0
2020-06-24 19:56:42: alarm-notify.sh: DEBUG: Loading config file '/usr/lib/netdata/conf.d/health_alarm_notify.conf'...
2020-06-24 19:56:42: alarm-notify.sh: DEBUG: Loading config file '/etc/netdata/health_alarm_notify.conf'...
2020-06-24 19:56:42: alarm-notify.sh: DEBUG: SEVERITY FILTERING for exampleuser@domain.com|critical VIA email: ALLOW: recipient has been notified for this alarm (will only receive CRITICAL notifications from now on)
2020-06-24 19:56:42: alarm-notify.sh: DEBUG: SEVERITY FILTERING for exampleuser@domain.com|critical VIA email: BLOCK: recipient should not receive this notification
2020-06-24 19:56:42: alarm-notify.sh: FATAL: All notification methods are disabled. Not sending notification for host 'servername', chart 'test.chart' to 'sysadmin' for 'test_alarm' = '100' for status 'CLEAR'.
+ '[' 1 -ne 0 ']'
+ echo '# FAILED'
# FAILED
+ test_res=1
+ last=CLEAR
+ id=4
+ exit 1
```

**Comment by ilyam8** [comment]
> Shouldn't the email addresses configured to receive critical alarms also receive the corresponding CLEAR alarms for the CRITICAL alarms that have fired?

Sounds correct, it would expect the same.

@thiagoftsm ?

**Comment by thiagoftsm** [comment]
Hi @dwdixon and @ilyam8 ,

I know what is happening here, according the text in our `health_alarm_notify.conf` we should have only critical alarms when `|critical` is set:

https://github.com/netdata/netdata/blob/4f5d6fbcf4f78c8ec8aa302304699457cead8315/health/notifications/health_alarm_notify.conf#L166

so I made a [PR](https://github.com/netdata/netdata/pull/7769) to fix the code behavior.
I agree with both of you that we should have options, like `|CLEAR|CRITICAL|WARN` to specify the exact kind of emails we would send for our users.
@dim08 we need to plan this feature, this is not the first issue requiring that the old behavior returns.

Best regards!

**Comment by dwdixon** [comment]
Hi @dim08 @thiagoftsm has this change been captured in another issue and being worked toward?  I noticed it's been flagged as inactive/stale and just wanted to make sure the full changes are planned to be worked out and eventually merged?

**Comment by thiagoftsm** [comment]
@dim08 , is there a plan to create  this feature for next increments?

**Comment by cakrit** [comment]
So it's basically a matter of just adding back those two `return` lines and verifying that a WARNING or a CLEAR notification will only be sent for an alarm that had gone to CRITICAL. The initial bug report that caused PR #7769 was therefore not triaged appropriately, the WARNING alarms the users were seeing were probably for alarms that had gone to CRITICAL. 

Testing should also be very straightforward, one alarm that moves to CRITICAL and then goes to WARNING and back to CLEAR, vs an alarm that goes to WARNING and then clear. In the first case, a user notified for CRITICAL alarms should get 3 notifications, in the second the user should receive no notifications.

Please progress with this fix.

**Comment by thiagoftsm** [comment]
Hi @dwdixon ,

I am closing this issue, because the PRs #9698 and #9740 are fixing this issue and the confusion that our documentation was creating, but if the problem persists in your side, please, let us know.

Best regards!
