### ISSUE TITLE
New UI questions - Sidebar/Nodes

### ISSUE THREAD

**Issue by stdedos** [netdata/netdata#9419]
Somewhat related to https://github.com/netdata/netdata/issues/9008:

On one browser, I am getting the "visited nodes" functionality, but on another one I don't:

![image](https://user-images.githubusercontent.com/133706/85749484-9035e680-b711-11ea-90b3-ffcc39b67723.png)

Would this (and/or that https://github.com/netdata/netdata/issues/9008) be "somewhat related" to a modal I barely saw saying "Error: _something something_ netdata cloud."?
I only saw it once, didn't pay enough attention to it, and I cannot find it again.

**Comment by manos-saratsis** [comment]
@stdedos thx for reporting this. Can you please let us know the agent version and Browsers, their version and OS so we can take a look? Also are you signed in on both browsers?

The visited nodes functionality moves to Cloud when you are signed in. Lack of connectivity to Cloud could have caused this. We show toast notifications when the [ACLK](https://learn.netdata.cloud/docs/agent/aclk) cannot be established.

**Comment by stdedos** [comment]
Well ... you are not going to like it: :stuck_out_tongue_closed_eyes: 
```
 OK : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.142 Safari/537.36
FAIL:  Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
```

I don't use, and I don't want to use Netdata Cloud. All metrics are only mine :heart: 
I hope you can respect that, and I that I don't have to block hosts for that :sweat_smile:

**Comment by manos-saratsis** [comment]
Thx for sharing the browser versions. Did you sign in to Netdata Cloud with any of these browsers?

Btw we keep metadata in Cloud so still the metrics are only yours :)
We respect that you do not want to use Cloud, you can disable Cloud via: https://learn.netdata.cloud/docs/agent/aclk#disable-the-aclk

**Comment by stdedos** [comment]
> Thx for sharing the browser versions. Did you sign in to Netdata Cloud with any of these browsers?

Given that I am avoiding cloud-_almost_-everything, I am inclined to say no.

> We respect that you do not want to use Cloud, you can disable Cloud via: [learn.netdata.cloud/docs/agent/aclk#disable-the-aclk](https://learn.netdata.cloud/docs/agent/aclk#disable-the-aclk)

I think I've done something related, but when I did it (long ago), I `touch`ed something after-the-fact.
I didn't know that the default kickstarting installation (done ~1 year ago, but I don't remember exactly) had cloud activated-by-default - I would've already done something by that time.

**Comment by manos-saratsis** [comment]
@stdedos thx. It will take some weeks to respond due to other priorities & vacation. Cc @jacekkolasa

**Comment by manos-saratsis** [comment]
Cc @jacekkolasa a topic to look at

**Comment by stdedos** [comment]
Also, it seems that the one node that has "visited nodes" list, does not add a new one, if I visit it

**Comment by jacekkolasa** [comment]
@stdedos are your other agents configured to use private registry as well? https://learn.netdata.cloud/docs/agent/registry#run-your-own-registry

Please make sure you don't block third party cookies, in Chrome this setting is under chrome://settings/cookies, in Firefox under about:preferences#privacy

**Comment by stdedos** [comment]
> @stdedos are your other agents configured to use private registry as well? [learn.netdata.cloud/docs/agent/registry#run-your-own-registry](https://learn.netdata.cloud/docs/agent/registry#run-your-own-registry)

I have configured them to use _my registry_ - the one that has the bookmarks.
However, I do expect that the visited nodes registry would be something like "local storage"-populated

> Please make sure you don't block third party cookies, in Chrome this setting is under chrome://settings/cookies, in Firefox under about:preferences#privacy

Actually, by sheer wtf, I used to accept 3rd-party cookies, so that's not it.
However, it won't happen again for sure

**Comment by stdedos** [comment]
> Would this (and/or that #9008) be "somewhat related" to a modal I barely saw saying "Error: _something something_ netdata cloud."?
> I only saw it once, didn't pay enough attention to it, and I cannot find it again.

Still happens again

![vivaldi_2020-09-23_09-59-36](https://user-images.githubusercontent.com/133706/98908936-cf4eb380-24c9-11eb-9419-59e939f8eb1f.png)

... but I don't want netdata to prepare anything

**Comment by manos-saratsis** [comment]
@stdedos if you have disabled aclk for access to Netdata Cloud (with https://learn.netdata.cloud/docs/agent/aclk#disable-the-aclk) we should fix it Cc @jacekkolasa

**Comment by stdedos** [comment]
I just did it manually, so I guess I haven't had it disabled.

I tried doing `--reinstall` (to make sure `--disable-cloud` is passed), but it does not let me (current >= new).
Can I somehow force it to reinstall (without uninstalling manually and/or otherwise loosing settings)?

**Comment by manos-saratsis** [comment]
@Ferroin do you have a hint?

**Comment by Ferroin** [comment]
No idea. `--reinstall` _should_ do it provided that the same type of install (regular kickstart.sh versus kickstart-static64.sh) is done.

I’d need to see the output from actually running the installer to figure out what’s going on here.

**Comment by Ferroin** [comment]
Also, reopening this, it’s still an issue...

**Comment by stdedos** [comment]
> No idea. `--reinstall` _should_ do it provided that the same type of install (regular kickstart.sh versus kickstart-static64.sh) is done.

Well, "I think" I used `kickstart.sh` and not `kickstart-static64.sh` because (a) I didn't know it, and (b) I don't really need it.

> I’d need to see the output from actually running the installer to figure out what’s going on here.

```console
u@h [2020-11-20 22:26:00]:~$ bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry --disable-cloud
 --- Found existing install of Netdata under: / --- 
 --- Attempting to update existing install instead of creating a new one --- 
[/home/usr]$ sudo //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron [sudo] password for usr: 
Παρ 20 Νοέ 2020 10:26:34 μμ EET : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Παρ 20 Νοέ 2020 10:26:34 μμ EET : INFO:  Current Version: 00102600000222
Παρ 20 Νοέ 2020 10:26:34 μμ EET : INFO:  Latest Version: 00102600000222
Παρ 20 Νοέ 2020 10:26:34 μμ EET : INFO:  Newest version (current=00102600000222 >= latest=00102600000222) is already installed
 OK  

 --- Updated existing install at /usr/sbin/netdata --- 
u@h [2020-11-20 22:26:34]:~$ 
```

**Comment by Ferroin** [comment]
OK, that’s expected output without the `--reinstall` option. Because the installer is seeing an existing installation, it’s just trying to update that (which intentionally does not modify the installation options on the existing install, so that people can just run the installer and not have to remember what options they initially passed in). The `--reinstall` option should skip that check and just run a new install.

We should probably add a warning to the output if the options passed don’t match up with what the existing install was created with...

**Comment by stdedos** [comment]
> The `--reinstall` option should skip that check and just run a new install.

Currently, it seems that this is not an option (as my output is effectively the same as the one above)

> We should probably add a warning to the output if the options passed don’t match up with what the existing install was created with...

Write the `--reinstall` workaround too in that case

**Comment by stdedos** [comment]
@stale, it's your teams' lack of activity

**Comment by OdysLam** [comment]
Thanks @stdedos for bringing this up on our attention. It seems that we dropped the ball on this one.  We are sorry for not getting back to you earlier.

Pinging @Ferroin  and @manos-saratsis again.

**Comment by Ferroin** [comment]
Apologies about not getting back on this.

> > The `--reinstall` option should skip that check and just run a new install.
> 
> Currently, it seems that this is not an option (as my output is effectively the same as the one above)

Most likely you were running into a bug in the option parsing code in the kickstart script that was causing it to be sensitive to the order in which the options were passed. This has since been fixed, so the newest copy of the kickstart script _should_ work correctly with the `--reinstall` option here.

@stdedos if you could double check to see if this is the case or not that would be appreciated.

**Comment by stdedos** [comment]
The installer seems to work; however, the /etc/cron.daily/netdata-updater gives:
```
line 44: 3: Bad file descriptor
```
