### ISSUE TITLE
"registry to announce" not honoured in alarm-notify.sh

### ISSUE THREAD

**Issue by olivluca** [netdata/netdata#9427]
With the latest release (1.23.0), the url in the notification always points to https://app.netdata.cloud (and, btw it goes to a 404 page) even with "registry to announce" set.
I see in alarm-notify.sh that it overrides the local registry url if the file /var/lib/netdata/registry/netdata.public.unique.id exists.
I tried to remove that file but it is regenerated as soon as netdata restart.
In the previous version the notifications used the correct, internal, url.

**Comment by thiagoftsm** [comment]
Hi @olivluca ,

I discovered that the problem was created by the new `spawn` server that was introduced with the latest version.
I am creating a PR that will fix this bug right now.
We apologize for the bug! And thank you very much to give us the feedback.

Best regards!
