### ISSUE TITLE
[TEST] exporting/.../test_exporting_engine.h: error: unknown type name mongoc_uri_t

### ISSUE THREAD

**Issue by candrews** [netdata/netdata#9430]
##### Bug report summary
netdata 1.23.0 has a failing test:
```
In file included from exporting/tests/test_exporting_engine.c:3:
exporting/tests/test_exporting_engine.h:161:1: error: unknown type name ‘mongoc_uri_t’
  161 | mongoc_uri_t *__wrap_mongoc_uri_new_with_error(const char *uri_string, bson_error_t *error);
      | ^~~~~~~~~~~~
exporting/tests/test_exporting_engine.h:161:72: error: unknown type name ‘bson_error_t’
```

Here's the full build output: https://729724.bugs.gentoo.org/attachment.cgi?id=646548
And here's the downstream bug report: https://bugs.gentoo.org/729724
##### OS / Environment

```
$ uname -a; grep -Hv "^#" /etc/*release
Linux irrational 5.4.33-gentoo-x86_64 #2 SMP Sat Apr 18 15:49:12 EDT 2020 x86_64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz GenuineIntel GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.7
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo/Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:HOME_URL="https://www.gentoo.org/"
/etc/os-release:SUPPORT_URL="https://www.gentoo.org/support/"
/etc/os-release:BUG_REPORT_URL="https://bugs.gentoo.org/"
```

##### Netdata version

 1.23.0

##### Component Name

tests
##### Steps To Reproduce

Run tests using `make check`

##### Expected behavior

Tests should pass.

**Comment by thiagoftsm** [comment]
Hi @candrews ,

I ran a grep on my `mongoc.h` and I observed that I have this declaration inside it:

```
bash-5.0$ grep -r mongoc_uri_t /usr/include/libmongoc-1.0/*
/usr/include/libmongoc-1.0/mongoc/mongoc-uri.h:typedef struct _mongoc_uri_t mongoc_uri_t;
```

In my case, I compiled the `mongo-c-driver-1.16.2`. What is your `libmongoc` version?

Best regards!

**Comment by candrews** [comment]
I do not have `libmongoc` installed. In this case, I don't believe the test should be run at all.

**Comment by thiagoftsm** [comment]
I am according with you. @vlvkobal looks like we are missing some checks before run our unit tests.
