### ISSUE TITLE
Improve Agent Release: Nightly for the stable on release day.

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#9431]
Without refactoring the entire release process (_plan in the works but significant work/effort_); we can:

- Move the nightly build/publish process to GHA (_mostly done already_)
- Trigger this workflow from Travis via `dispatch-events` using `curl` from the existing Travis release flows.
- Add a step to also trigger the same workflow on the day of the release.

This will ensure we have a nightly on the day of the release for the current version being released.

**Comment by prologic** [comment]
This will of course increase the release time by about an hour as it takes that long to build the nightly artefacts.

**Comment by Ferroin** [comment]
Our release process has shifted such that we no longer need to disable nightly builds on release days, so this can be closed.
