### ISSUE TITLE
Error update to Netdata 1.23 with netdata-updater.sh

### ISSUE THREAD

**Issue by drkt7** [netdata/netdata#9432]
Hi

i have this error when a update netdata version: v1.22.1-332-gd875f4c5 to v1.23.0-4-nightly

[root@nws2032 ~]# /opt/netdata/usr/libexec/netdata/netdata-updater.sh
Entering /tmp/netdata-updater-lhhWrh
Fri Jun 26 20:56:26 EDT 2020 : ERROR:  FAILED TO UPDATE NETDATA : Static binary checksum validation failed. Stopping netdata installation and leaving binary in /tmp/netdata-updater-lhhWrh

**Comment by prologic** [comment]
@drkt7 I have a suspicion as to why you _might_ have received this error when trying to update; however are you able to try this again? Let me know if it still persists. Also are you on the stable or nightly channel in your installation?

**Comment by drkt7** [comment]
yes the versions are correct. But I deleted and reinstalled the latest version to fix the problem

Thanks

**Comment by thiagoftsm** [comment]
Hi @drkt7 ,

Considering your last message, I understand that the problem was fixed and I am closing the issue. Please, reopen it if the problem persists.

Best regards!
