### ISSUE TITLE
netdata 1.23.0 failed on the dbengine test

### ISSUE THREAD

**Issue by chenrui333** [netdata/netdata#9435]
relates to Homebrew/homebrew-core#56993

netdata 1.23.0 currently failed on the dbengine test when running unittest, I just disabled the unittest for the upgrade

Couple of questions:
- any way that we can separate out the dbengine test from the other unittest suites?
- any way to solve this `Host machine GUID is not valid` error

Full log is in that PR. Thanks!

**Comment by mfundul** [comment]
`Host machine GUID is not valid` in this case is harmless and is not the reason the test fails.

Can anybody else who has a macos platform reproduce this failure by running `/usr/sbin/netdata -W unittest`?

I can't think of a reason why it is specifically failing on macos and not on linux, the logs are not useful.

**Comment by prologic** [comment]
@mfundul 

```#!sh
$ ./netdata -W unittest
.
.
.
ALL TESTS PASSED
```

**Comment by mfundul** [comment]
This commit https://github.com/netdata/netdata/commit/3a1625f480b6a48c8fcd6e99f557b7d41bafcb59 has broken the unittests:
```
2020-06-29 17:38:42: netdata FATAL : netdata : Cannot create unique machine id file '(null)'. Please fix this. # : Bad address
```

**Comment by thiagoftsm** [comment]
Hi @chenrui333 ,

Thank you for your report, I created a PR that will fix this bug.

Best regards!

**Comment by mfundul** [comment]
@thiagoftsm that bug that you're fixing doesn't exist in the stable release code (1.23.0) so I don't think it will fix this issue.

**Comment by thiagoftsm** [comment]
> @thiagoftsm that bug that you're fixing doesn't exist in the stable release code (1.23.0) so I don't think it will fix this issue.

I updated the comment on the PR. Unfortunately I do not have any Mac to debug this issue.
