### ISSUE TITLE
netdata 1.23.0 on parent is not showing the child's netdata version

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9437]
##### Bug report summary

I had a dashboard which indicates how many netdata are using what version of netdata:
![image](https://user-images.githubusercontent.com/7656049/85954567-a4861780-b98d-11ea-8c0d-9542ea247108.png)
I'm using this metric:
```
count (netdata_info{job="netdata-central"}) by (version)
```
But after updating the netdata on parents to 1.23.0, this metric shows 1.23.0 as the version for all children streaming to this parent as well:
![image](https://user-images.githubusercontent.com/7656049/85954659-5ae9fc80-b98e-11ea-8878-c40e9a0bcfef.png)
This can cause trouble when I want to update our child's netdata agent because I don't know exactly which child is running older netdata

##### Component Name

v1.23.0

**Comment by thiagoftsm** [comment]
Hi @yasharne ,

Firstly we apologize for the problem. The latest release brought a lot of improvements on the stream, but it also brought this bug. I am already creating a bug fix for it and possibility tomorrow it will be merged on master branch.

Best regards!
