### ISSUE TITLE
Deactivate Docker monitoring

### ISSUE THREAD

**Issue by auxua** [netdata/netdata#9443]
##### Question summary

I have several servers (Ubuntu 18.04) that are spanning a docker swarm for several hundred containers. Netdata cannot deal with that many containers as it tries to monitor all of them and permanently occupies one full CPU without being able to serve a netdata page. How can I deactivate the docker monitoring of netdata?

I tried adding ``enable cgroup docker = no`` to the ``[plugins]`` section, the ``enabled = no`` to sections ``[plugin:cgroups]`` and ``[plugin:go.d]`` as stated in some issues here from many years ago

##### OS / Environment

Ubuntu 18.04, current netdata nightly, One-line installer

##### Component Name

Docker

##### Expected results

Deactivate Docker monitoring

**Comment by ilyam8** [comment]
Hi @auxua 


`netdata.conf`

```
[plugins]
  cgroups = no
```

**Comment by ilyam8** [comment]
perhaps decreasing `update_every` will do

```
[plugins:cgroups]
  update every = 5
```

**Comment by ilyam8** [comment]
> and permanently occupies one full CPU

btw what occupies one full CPU? `netdata` process?

i created 300 containers (busybox), web ui navigation feels quite laggy, but i have no 100% cpu usage

<img width="1151" alt="Screenshot 2020-06-29 at 18 51 22" src="https://user-images.githubusercontent.com/22274335/86027580-8f66c280-ba39-11ea-87e8-d1fdc8ae8b7e.png">

**Comment by auxua** [comment]
Thank you @ilyam8 for the replies.

I tried that, but still netdata takes one full CPU core and is not able to serve the monitoring page. As the servers are only serving as docker swarm, I have no clue, what else is triggering the problems - also they started as the container amount was increasing. Is there a way to detect, what netdata is having trouble with? Logs, etc?

![image](https://user-images.githubusercontent.com/1534703/86093273-fa061580-baae-11ea-9bd0-94abff594c06.png)

**Comment by ilyam8** [comment]
What is your netdata version?

show output of the following command

> ps faxu | grep netdata

**Comment by auxua** [comment]
The netdata version is v1.23.0-24-nightly

The output of the command is

![image](https://user-images.githubusercontent.com/1534703/86097455-f9707d80-bab4-11ea-84bf-693285dbe2b4.png)

**Comment by ilyam8** [comment]
sure? no other plugins?

```cmd
[ilyam@ilyam-pc ~]$ ps faxu | grep netdata
netdata    20949  1.0  1.0 599080 346480 ?       Ssl  июн29  10:19 /opt/netdata/usr/sbin/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D
netdata    20961  0.0  0.0  24276  7984 ?        Sl   июн29   0:00  \_ /opt/netdata/usr/sbin/netdata --special-spawn-server
netdata    21150  0.2  0.0  19652  7832 ?        S    июн29   2:20  \_ /opt/netdata/usr/libexec/netdata/plugins.d/cups.plugin 1
netdata    21154  0.9  0.1 224424 53524 ?        Sl   июн29   8:51  \_ /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata    21156  0.0  0.0 725900 18852 ?        Sl   июн29   0:24  \_ /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata    21157  1.0  0.0  65356 11996 ?        S    июн29   9:50  \_ /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
root       21437  0.5  0.0 385704  7708 ?        Sl   июн29   5:12  \_ /opt/netdata/usr/libexec/netdata/plugins.d/ebpf.plugin 1
```

**Comment by auxua** [comment]
Yes, nothing else to see in there

**Comment by ilyam8** [comment]
Well, if cgroups plugin is the cause the problem should be fixed after

> https://github.com/netdata/netdata/issues/9443#issuecomment-651197122


could you

> pwd && grep "\[plugins\]" netdata.conf -A 25


And lets check netdata logs.

```cmd
cd /var/log/netdata
systemctl stop netdata.service
cp /dev/null error.log
systemctl start netdata.service

# wait a bit
```

and share `error.log` content

**Comment by auxua** [comment]
So for your first command:


```
/etc/netdata
[plugins]
        cgroups = no
        # PATH environment variable = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
        # PYTHONPATH environment variable =
        # proc = yes
        # diskspace = yes
        # cgroups = yes
        # tc = yes
        # idlejitter = yes
        # enable running new plugins = yes
        # check for new plugins every = 60
        # slabinfo = no
        # node.d = yes
        # charts.d = yes
        # python.d = yes
        # perf = yes
        # fping = yes
        # apps = yes
        # go.d = yes
        # ioping = yes
        # enable cgroup docker = no
        # search for cgroups under /sys/fs/cgroup/devices = no

[health]
        # silencers file = /var/lib/netdata/health.silencers.json
        # enabled = yes
```

For the logs, please find the file attached.
Looks like it is loading hundreds of cache files - is this normal for netdata or a hint for loaded caches?

[error.log](https://github.com/netdata/netdata/files/4856897/error.log)

**Comment by ilyam8** [comment]
> Looks like it is loading hundreds of cache files - is this normal for netdata or a hint for loaded caches?


@mfundul  please take a look

**Comment by auxua** [comment]
@ilyam8 You are right - a complete removal and reinstall solved my problem on all machines. Interestingly, I could see the netdata dashboard for a short period of time on one machine. It indicated that netdata was handling nearly 1 million alarms - so maybe during one of the nightly updates it increased that number extremely...
