### ISSUE TITLE
FreeNAS 11.3 Jail - Update 1.22.1 -> 1.23.0 failed

### ISSUE THREAD

**Issue by abrbon** [netdata/netdata#9444]
On my Freenas 11.3-U3.2 i have Netdata installed in a jail (used build from git)
It is configured with autoupdate feature.

This has worked for me just fine from 1.21.x till 1.22.1.
But from v1.22.1 -> 1.23.0 it failed with the following error:

```
config.status: executing depfiles commands
config.status: error: in '/tmp/netdata-updater-piSyIw/netdata-v1.23.0':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See 'config.log' for more details
 FAILED
`

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues

Mon Jun 29 18:35:40 CEST 2020 : ERROR:  FAILED TO UPDATE NETDATA : FAILED TO COMPILE/INSTALL NETDATA
```

I tried the "--disable-dependency-tracking" option but it is not recognized as an option.

**Comment by nmindz** [comment]
Same issue here.
```
[/tmp/netdata-updater-V1UkyB/netdata-v1.23.1]# mkdir -p /tmp/netdata-updater-V1UkyB/netdata-v1.23.1/externaldeps/libwebsockets
 OK

[/tmp/netdata-updater-V1UkyB/netdata-v1.23.1]# cp /tmp/netdata-libwebsockets-XXXXXX.abQ0HWnT/libwebsockets-3.2.2/lib/libwebsockets.a /tmp/netdata-updater-V1UkyB/netdata-v1.23.1/externaldeps/libwebsockets/libwebsockets.a
 OK

[/tmp/netdata-updater-V1UkyB/netdata-v1.23.1]# cp -r /tmp/netdata-libwebsockets-XXXXXX.abQ0HWnT/libwebsockets-3.2.2/include /tmp/netdata-updater-V1UkyB/netdata-v1.23.1/externaldeps/libwebsockets
 OK

 OK  libwebsockets built and prepared.


 --- Run autotools to configure the build environment ---
[/tmp/netdata-updater-V1UkyB/netdata-v1.23.1]# autoreconf -ivf
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I build/m4
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: not using Libtool
autoreconf-2.69: running: /usr/local/bin/autoconf-2.69 --force
autoreconf-2.69: running: /usr/local/bin/autoheader-2.69 --force
autoreconf-2.69: running: automake --add-missing --copy --force-missing
autoreconf-2.69: Leaving directory `.'
 OK

[/tmp/netdata-updater-V1UkyB/netdata-v1.23.1]# ./configure --prefix=/opt/netdata/usr --sysconfdir=/opt/netdata/etc --localstatedir=/opt/netdata/var --libexecdir=/opt/netdata/usr/libexec --libdir=/opt/netdata/usr/lib --with-zlib --with-math --with-user=netdata CFLAGS=-O2 LDFLAGS=
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... amd64-unknown-freebsd11.3
checking host system type... amd64-unknown-freebsd11.3
checking for gcc... no
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking whether cc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of cc... gcc3
checking for cc option to accept ISO C99... none needed
checking for g++... no
checking for c++... c++
checking whether we are using the GNU C++ compiler... yes
checking whether c++ accepts -g... yes
checking dependency style of c++... gcc3
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for __attribute__((returns_nonnull))... yes
checking for __attribute__((malloc))... yes
checking for __attribute__((noreturn))... yes
checking for __attribute__((noinline))... yes
checking for __attribute__((format))... yes
checking for __attribute__((warn_unused_result))... yes
checking for struct timespec... yes
checking for clockid_t... yes
checking for library containing clock_gettime... none required
checking for clock_gettime... yes
checking for sched_setscheduler... yes
checking for sched_getscheduler... yes
checking for sched_getparam... yes
checking for sched_get_priority_min... yes
checking for sched_get_priority_max... yes
checking for getpriority... yes
checking for setpriority... yes
checking for nice... yes
checking for recvmmsg... yes
checking for int8_t... yes
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for inline... inline
checking whether strerror_r is declared... yes
checking for strerror_r... yes
checking whether strerror_r returns char *... no
checking for _Generic... yes
checking for __atomic... yes
checking size of void *... 8
checking whether sys/types.h defines makedev... yes
checking for sys/types.h... (cached) yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking for sys/prctl.h... no
checking for sys/vfs.h... no
checking for sys/statfs.h... no
checking for sys/statvfs.h... yes
checking for sys/mount.h... yes
checking for accept4... yes
checking operating system... freebsd with id 2
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking for PTHREAD_PRIO_INHERIT... yes
checking for pthread_getname_np in -lpthread... no
checking for sin in -lm... yes
checking if libm should be used... yes
checking for uv_fs_scandir_next in -luv... yes
checking for LZ4_compress_default in -llz4... yes
checking for JudyLIns in -lJudy... yes
checking for ZLIB... yes
checking if zlib should be used... yes
checking for UUID... yes
checking for SHA256_Init in -lcrypto... yes
checking for X509_VERIFY_PARAM_set1_host in -lcrypto... yes
checking for JSON... yes
checking for json_object_get_type in -ljson-c... yes
checking for dlopen in -ldl... yes
checking if netdata dbengine should be used... yes
checking if netdata https should be used... yes
checking if json-c should be used... yes
checking for memory allocator... system
checking for mallopt... no
checking for mallinfo... no
checking for LIBCAP... no
checking if libcap should be used... no
checking if cloud functionality should be enabled... detect
checking if libmosquitto static lib is present (and builds)... yes
checking if libwebsockets static lib is present... yes
checking if json-c available for ACLK... yes
checking if netdata agent-cloud-link can be enabled... yes
checking if netdata agent-cloud-link should/will be enabled... yes
checking if apps.plugin should be enabled... yes
checking for IPMIMONITORING... no
checking if freeipmi.plugin should be enabled... no
checking for httpConnect2 in -lcups... no
checking for cups-config... no
checking if cups.plugin should be enabled... no
checking linux/netfilter/nfnetlink_conntrack.h usability... no
checking linux/netfilter/nfnetlink_conntrack.h presence... no
checking for linux/netfilter/nfnetlink_conntrack.h... no
checking for NFACCT... no
checking for LIBMNL... no
checking if nfacct.plugin should be enabled... no
checking for YAJL... no
checking for xenstat_init in -lxenstat... no
checking for XENLIGHT... no
checking if xenstat.plugin should be enabled... no
checking linux/perf_event.h usability... no
checking linux/perf_event.h presence... no
checking for linux/perf_event.h... no
checking if perf.plugin should be enabled... no
checking if ebpf.plugin should be enabled... no
checking if slabinfo.plugin should be enabled... no
checking for LIBCRYPTO... no
checking for LIBSSL... no
checking for LIBCURL... yes
checking for curl_easy_init in -lcurl... yes
checking for cJSON_free in -laws-cpp-sdk-core... no
checking for Aws::Kinesis::Model::PutRecordRequest in -laws-cpp-sdk-kinesis... no
checking if kinesis backend should be enabled... no
checking for GRPC... no
checking for PUBSUB... no
checking for c++... /usr/bin/c++
checking if pubsub exporting connector should be enabled... detect
checking for PROTOBUF... no
checking for snappy::RawCompress in -lsnappy... no
checking for protoc... no
checking for c++... (cached) /usr/bin/c++
checking if prometheus remote write backend should be enabled... no
checking for LIBMONGOC... no
checking if mongodb backend should be enabled... no
checking for setns... no
checking if cgroup-network can be enabled... no
checking whether C compiler accepts -flto... yes
checking if -flto builds executables... no
checking if LTO should be enabled... no
checking for CMOCKA... no
configure: CMocka not found on the system. Unit tests disabled
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating netdata.spec
config.status: creating backends/graphite/Makefile
config.status: creating backends/json/Makefile
config.status: creating backends/Makefile
config.status: creating backends/opentsdb/Makefile
config.status: creating backends/prometheus/Makefile
config.status: creating backends/prometheus/remote_write/Makefile
config.status: creating backends/aws_kinesis/Makefile
config.status: creating backends/mongodb/Makefile
config.status: creating collectors/Makefile
config.status: creating collectors/apps.plugin/Makefile
config.status: creating collectors/cgroups.plugin/Makefile
config.status: creating collectors/charts.d.plugin/Makefile
config.status: creating collectors/checks.plugin/Makefile
config.status: creating collectors/diskspace.plugin/Makefile
config.status: creating collectors/fping.plugin/Makefile
config.status: creating collectors/ioping.plugin/Makefile
config.status: creating collectors/freebsd.plugin/Makefile
config.status: creating collectors/freeipmi.plugin/Makefile
config.status: creating collectors/cups.plugin/Makefile
config.status: creating collectors/idlejitter.plugin/Makefile
config.status: creating collectors/macos.plugin/Makefile
config.status: creating collectors/nfacct.plugin/Makefile
config.status: creating collectors/node.d.plugin/Makefile
config.status: creating collectors/plugins.d/Makefile
config.status: creating collectors/proc.plugin/Makefile
config.status: creating collectors/python.d.plugin/Makefile
config.status: creating collectors/slabinfo.plugin/Makefile
config.status: creating collectors/statsd.plugin/Makefile
config.status: creating collectors/ebpf.plugin/Makefile
config.status: creating collectors/tc.plugin/Makefile
config.status: creating collectors/xenstat.plugin/Makefile
config.status: creating collectors/perf.plugin/Makefile
config.status: creating daemon/Makefile
config.status: creating database/Makefile
config.status: creating database/engine/Makefile
config.status: creating database/engine/metadata_log/Makefile
config.status: creating database/engine/global_uuid_map/Makefile
config.status: creating diagrams/Makefile
config.status: creating exporting/Makefile
config.status: creating exporting/graphite/Makefile
config.status: creating exporting/json/Makefile
config.status: creating exporting/opentsdb/Makefile
config.status: creating exporting/prometheus/Makefile
config.status: creating exporting/prometheus/remote_write/Makefile
config.status: creating exporting/aws_kinesis/Makefile
config.status: creating exporting/pubsub/Makefile
config.status: creating exporting/mongodb/Makefile
config.status: creating exporting/tests/Makefile
config.status: creating health/Makefile
config.status: creating health/notifications/Makefile
config.status: creating libnetdata/Makefile
config.status: creating libnetdata/tests/Makefile
config.status: creating libnetdata/adaptive_resortable_list/Makefile
config.status: creating libnetdata/avl/Makefile
config.status: creating libnetdata/buffer/Makefile
config.status: creating libnetdata/clocks/Makefile
config.status: creating libnetdata/config/Makefile
config.status: creating libnetdata/dictionary/Makefile
config.status: creating libnetdata/ebpf/Makefile
config.status: creating libnetdata/eval/Makefile
config.status: creating libnetdata/locks/Makefile
config.status: creating libnetdata/log/Makefile
config.status: creating libnetdata/popen/Makefile
config.status: creating libnetdata/procfile/Makefile
config.status: creating libnetdata/simple_pattern/Makefile
config.status: creating libnetdata/socket/Makefile
config.status: creating libnetdata/statistical/Makefile
config.status: creating libnetdata/storage_number/Makefile
config.status: creating libnetdata/storage_number/tests/Makefile
config.status: creating libnetdata/threads/Makefile
config.status: creating libnetdata/url/Makefile
config.status: creating libnetdata/json/Makefile
config.status: creating libnetdata/health/Makefile
config.status: creating registry/Makefile
config.status: creating streaming/Makefile
config.status: creating system/Makefile
config.status: creating tests/Makefile
config.status: creating web/Makefile
config.status: creating web/api/Makefile
config.status: creating web/api/badges/Makefile
config.status: creating web/api/exporters/Makefile
config.status: creating web/api/exporters/shell/Makefile
config.status: creating web/api/exporters/prometheus/Makefile
config.status: creating web/api/formatters/Makefile
config.status: creating web/api/formatters/csv/Makefile
config.status: creating web/api/formatters/json/Makefile
config.status: creating web/api/formatters/ssv/Makefile
config.status: creating web/api/formatters/value/Makefile
config.status: creating web/api/queries/Makefile
config.status: creating web/api/queries/average/Makefile
config.status: creating web/api/queries/des/Makefile
config.status: creating web/api/queries/incremental_sum/Makefile
config.status: creating web/api/queries/max/Makefile
config.status: creating web/api/queries/median/Makefile
config.status: creating web/api/queries/min/Makefile
config.status: creating web/api/queries/ses/Makefile
config.status: creating web/api/queries/stddev/Makefile
config.status: creating web/api/queries/sum/Makefile
config.status: creating web/api/health/Makefile
config.status: creating web/gui/Makefile
config.status: creating web/server/Makefile
config.status: creating web/server/static/Makefile
config.status: creating claim/Makefile
config.status: creating aclk/Makefile
config.status: creating spawn/Makefile
config.status: creating parser/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: error: in `/tmp/netdata-updater-V1UkyB/netdata-v1.23.1':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
 FAILED


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues


Tue Jul  7 12:33:43 -03 2020 : ERROR:  FAILED TO UPDATE NETDATA : FAILED TO COMPILE/INSTALL NETDATA
```
Running inside a `11.3-RELEASE` jail built manually with `iocage`. I decided to run a regular BSD jail, update my dependencies from there and follow [this guide](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/freebsd).

Everything went fine (and installed fine) until I reached the step that emphasizes it *very* important to update Netdata using the provided script. With the update script, all goes down and it just breaks.

**Comment by prologic** [comment]
I fixed this in #9413 already for FreeBSD;

```#!sh
$ sift -C 3 '\-\-disable\-dependency'
netdata-installer.sh-301-# See: https://github.com/netdata/netdata/issues/9163
netdata-installer.sh-302-if [ "$(uname -s)" = "FreeBSD" ]; then
netdata-installer.sh-303-  make="gmake"
netdata-installer.sh:304:  NETDATA_CONFIGURE_OPTIONS="$NETDATA_CONFIGURE_OPTIONS --disable-dependency-tracking"
netdata-installer.sh-305-fi
```

Can you confirm the same fix on FreeNAS? I _assume_ it reports differently the output of `uname -s` and therefore the same conditional variables are not set to construct a correct build.

**Comment by abrbon** [comment]
> I fixed this in #9413 already for FreeBSD;
> 
> ```
> $ sift -C 3 '\-\-disable\-dependency'
> netdata-installer.sh-301-# See: https://github.com/netdata/netdata/issues/9163
> netdata-installer.sh-302-if [ "$(uname -s)" = "FreeBSD" ]; then
> netdata-installer.sh-303-  make="gmake"
> netdata-installer.sh:304:  NETDATA_CONFIGURE_OPTIONS="$NETDATA_CONFIGURE_OPTIONS --disable-dependency-tracking"
> netdata-installer.sh-305-fi
> ```
> 
> Can you confirm the same fix on FreeNAS? I _assume_ it reports differently the output of `uname -s` and therefore the same conditional variables are not set to construct a correct build.

Hi,

I have never used the SIFT command before, i tried inside my jail with netdata but it throws all kinds off errors.

`
root@netdata-custom:~/netdata # sift -C 3 '\-\-disable\-dependency'
aclocal.m4-  [--enable-dependency-tracking],
aclocal.m4-  [do not reject slow dependency extractors])
aclocal.m4-AS_HELP_STRING(
aclocal.m4:  [--disable-dependency-tracking],
aclocal.m4-  [speeds up one-time build])])
aclocal.m4-if test "x$enable_dependency_tracking" != xno; then
aclocal.m4-  am_depcomp="$ac_aux_dir/depcomp"
--
aclocal.m4-  if test $am_rc -ne 0; then
aclocal.m4-    AC_MSG_FAILURE([Something went wrong bootstrapping makefile fragments
aclocal.m4-    for automatic dependency tracking.  Try re-running configure with the
aclocal.m4:    '--disable-dependency-tracking' option to at least be able to build
aclocal.m4-    the package (albeit without support for automatic dependency tracking).])
aclocal.m4-  fi
aclocal.m4-  AS_UNSET([am_dirpart])
--
configure-  --disable-silent-rules  verbose build output (undo: "make V=0")
configure-  --enable-dependency-tracking
configure-                          do not reject slow dependency extractors
configure:  --disable-dependency-tracking
configure-                          speeds up one-time build
configure-  --enable-plugin-nfacct  enable nfacct plugin [default autodetect]
configure-  --enable-plugin-freeipmi
--
configure-$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
configure-as_fn_error $? "Something went wrong bootstrapping makefile fragments
configure-    for automatic dependency tracking.  Try re-running configure with the
configure:    '--disable-dependency-tracking' option to at least be able to build
configure-    the package (albeit without support for automatic dependency tracking).
configure-See \`config.log' for more details" "$LINENO" 5; }
configure-  fi
--
config.log-config.status:1498: error: in `/root/netdata':
config.log-config.status:1504: error: Something went wrong bootstrapping makefile fragments
config.log-    for automatic dependency tracking.  Try re-running configure with the
config.log:    '--disable-dependency-tracking' option to at least be able to build
config.log-    the package (albeit without support for automatic dependency tracking).
config.log-See `config.log' for more details
config.log-
--
netdata-installer.log-CFLAGS="-O2" LDFLAGS="" ./netdata-installer.sh --stable-channel --disable-telemetry --disable-cloud --disable-dependecy-tracking -u --install /usr/local 
netdata-installer.log-
netdata-installer.log-# Sun Jun 28 22:54:53 CEST 2020
netdata-installer.log:CFLAGS="-O2" LDFLAGS="" ./netdata-installer.sh --stable-channel --disable-telemetry --disable-cloud --disable-dependency-tracking -u --install /usr/local 
netdata-installer.log-
netdata-installer.log-# Sun Jun 28 22:57:18 CEST 2020
netdata-installer.log:CFLAGS="-O2" LDFLAGS="" ./netdata-installer.sh --stable-channel --disable-telemetry --disable-cloud --disable-dependency-tracking -u --install /usr/local 
netdata-installer.log-
netdata-installer.log-# Sun Jun 28 22:57:30 CEST 2020
netdata-installer.log-CFLAGS="-O2" LDFLAGS="" ./netdata-installer.sh --stable-channel --disable-telemetry --disable-cloud -u --install /usr/local 
--
config.status-$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
config.status-as_fn_error $? "Something went wrong bootstrapping makefile fragments
config.status-    for automatic dependency tracking.  Try re-running configure with the
config.status:    '--disable-dependency-tracking' option to at least be able to build
config.status-    the package (albeit without support for automatic dependency tracking).
config.status-See \`config.log' for more details" "$LINENO" 5; }
config.status-  fi
--
autom4te.cache/traces.0-  [--enable-dependency-tracking],
autom4te.cache/traces.0-  [do not reject slow dependency extractors])
autom4te.cache/traces.0-AS_HELP_STRING(
autom4te.cache/traces.0:  [--disable-dependency-tracking],
autom4te.cache/traces.0-  [speeds up one-time build])])
autom4te.cache/traces.0-if test "x$enable_dependency_tracking" != xno; then
autom4te.cache/traces.0-  am_depcomp="$ac_aux_dir/depcomp"
--
autom4te.cache/traces.0-  if test $am_rc -ne 0; then
autom4te.cache/traces.0-    AC_MSG_FAILURE([Something went wrong bootstrapping makefile fragments
autom4te.cache/traces.0-    for automatic dependency tracking.  Try re-running configure with the
autom4te.cache/traces.0:    '--disable-dependency-tracking' option to at least be able to build
autom4te.cache/traces.0-    the package (albeit without support for automatic dependency tracking).])
autom4te.cache/traces.0-  fi
autom4te.cache/traces.0-  AS_UNSET([am_dirpart])
--
autom4te.cache/output.0-  --disable-silent-rules  verbose build output (undo: "make V=0")
autom4te.cache/output.0-  --enable-dependency-tracking 
autom4te.cache/output.0-                          do not reject slow dependency extractors
autom4te.cache/output.0:  --disable-dependency-tracking 
autom4te.cache/output.0-                          speeds up one-time build
autom4te.cache/output.0-  --enable-plugin-nfacct  enable nfacct plugin @<:@default autodetect@:>@
autom4te.cache/output.0-  --enable-plugin-freeipmi 
--
autom4te.cache/output.0-$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
autom4te.cache/output.0-as_fn_error $? "Something went wrong bootstrapping makefile fragments
autom4te.cache/output.0-    for automatic dependency tracking.  Try re-running configure with the
autom4te.cache/output.0:    '--disable-dependency-tracking' option to at least be able to build
autom4te.cache/output.0-    the package (albeit without support for automatic dependency tracking).
autom4te.cache/output.0-See \`config.log' for more details" "$LINENO" 5; }
autom4te.cache/output.0-  fi
--
autom4te.cache/output.1-  --disable-silent-rules  verbose build output (undo: "make V=0")
autom4te.cache/output.1-  --enable-dependency-tracking 
autom4te.cache/output.1-                          do not reject slow dependency extractors
autom4te.cache/output.1:  --disable-dependency-tracking 
autom4te.cache/output.1-                          speeds up one-time build
autom4te.cache/output.1-  --enable-plugin-nfacct  enable nfacct plugin @<:@default autodetect@:>@
autom4te.cache/output.1-  --enable-plugin-freeipmi 
--
autom4te.cache/output.1-$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
autom4te.cache/output.1-as_fn_error $? "Something went wrong bootstrapping makefile fragments
autom4te.cache/output.1-    for automatic dependency tracking.  Try re-running configure with the
autom4te.cache/output.1:    '--disable-dependency-tracking' option to at least be able to build
autom4te.cache/output.1-    the package (albeit without support for automatic dependency tracking).
autom4te.cache/output.1-See \`config.log' for more details" "$LINENO" 5; }
autom4te.cache/output.1-  fi
Error: 1 files skipped due to very long lines (>= 262144 bytes). See options --blocksize, --err-show-line-length and --err-skip-line-length.
root@netdata-custom:~/netdata # netdata-installer.sh-301-# See: https://github.com/netdata/netdata/issues/9163
netdata-installer.sh-301-#: Command not found.
root@netdata-custom:~/netdata # netdata-installer.sh-302-if [ "$(uname -s)" = "FreeBSD" ]; then
Illegal variable name.
root@netdata-custom:~/netdata # netdata-installer.sh-303-  make="gmake"
netdata-installer.sh-303-: Command not found.
root@netdata-custom:~/netdata # netdata-installer.sh:304:  NETDATA_CONFIGURE_OPTIONS="$NETDATA_CONFIGURE_OPTIONS --disable-dependency-tracking"
NETDATA_CONFIGURE_OPTIONS: Undefined variable.
root@netdata-custom:~/netdata # netdata-installer.sh-305-fi
netdata-installer.sh-305-fi: Command not found.
root@netdata-custom:~/netdata # 

`

**Comment by prologic** [comment]
Sorry I did not mean for you to try to re-run my command-line search against our codebase. `sift` is a tool I use for quick/fast grep'ing against local files. It extremely fast :)

What I asked was this:

> Can you confirm the same fix on FreeNAS? I assume it reports differently the output of uname -s and therefore the same conditional variables are not set to construct a correct build.

Meaning the same/similar fixes I applied in the aforementioned PR #9413 where I said:

> I fixed this in #9413 already for FreeBSD;

If you are unable to do this, that's fine. I'll try to prioritise spinning up a FreeNAS VM to do some testing with (_I don't have access to FreeNAS based hardware at all here so I'm limited to virtual instances_).

Let me know if you are able to apply the same `--disable-dependency-tracking` and `CFLAG` changes as per the PR I mentioned, if not let me know.

**Comment by nmindz** [comment]
@prologic About `uname - s` on FreeNAS:

```
 Mon Jun  1 15:04:31 EDT 2020

FreeNAS (c) 2009-2020, The FreeNAS Development Team
All rights reserved.
FreeNAS is released under the modified BSD license.

For more information, documentation, help or support, go he
re:
http://freenas.org
Welcome to FreeNAS

Warning: settings changed through the CLI are not written to
the configuration database and will be reset on reboot.

root@bjorn[~]# uname -s                                          FreeBSD                                                          root@bjorn[~]# uname -sr                                         FreeBSD 11.3-RELEASE-p9                                          root@bjorn[~]#
``'

**Comment by prologic** [comment]
Thanks for the clarification! I'm a bit baffled then, because the fix I did in the mentioned PR should also be applied here as well. But for some reason your OP reports a very similar error/problem we originally had on FreeBSD (_which I fixed_). Perhaps FreeNAS is somehow different enough (_like pfSense_) that it _may_ as well not really be FreeBSD at all :/ I'll have to go spin up a VM to dig further; I don't have access to any pfSense or FreeNAS machines (_I hope I can get/construct virtual machines of like I did with FreeBSD on Virtualbox_).

**Comment by nmindz** [comment]
@prologic If all you need is to read diagnostic data from, I might be able to provide you with access to one instance.

**Comment by abrbon** [comment]
I got it working now.

- I just downloaded the latest 1.23.1 tarball version from github directly in my netdata Jail.
- Then i unzipped it there.
- And then copied the complete code from the netdata-installer.sh from https://github.com/netdata/netdata/blob/master/netdata-installer.sh to replace the netdata-install.sh from the tarball.
- And then installed netdata with this netdata-install.sh 

This way i was able to make it work.

So it seems like the netdata-install.sh file in the tarball is not the correct file.
Quick way for me to check was to look at line 301 from the netdata-installer.sh files.
In the tarball the following part was missing:

```
make="make"
# See: https://github.com/netdata/netdata/issues/9163
if [ "$(uname -s)" = "FreeBSD" ]; then
  make="gmake"
  NETDATA_CONFIGURE_OPTIONS="$NETDATA_CONFIGURE_OPTIONS --disable-dependency-tracking"
fi
```

For me the install now works on my jail in FreeNAS 12.1 BETA

**Comment by Ferroin** [comment]
@abrbon Can you please confirm if this is still an issue or not? There have been a number of build and packaging related changes since v1.23.0 and it may be fixed now in current versions.

**Comment by abrbon** [comment]
> @abrbon Can you please confirm if this is still an issue or not? There have been a number of build and packaging related changes since v1.23.0 and it may be fixed now in current versions.

Hi Ferroin,

Yes i can confirm this issue has been resolved for me.

However another issue i now have is that the auto-update doesn't seem to work.
If i run the "/etc/periodic/daily/netdata-updater" script manually it does work fine altough i have to answer 1 question during the script with "Y" before it can continue and finish the update.
Unfortunatelly i can't remember which question it was :( 
I will have to setup a seperate installation on my server and install an older version and run the update script again.

**Comment by Ferroin** [comment]
> > @abrbon Can you please confirm if this is still an issue or not? There have been a number of build and packaging related changes since v1.23.0 and it may be fixed now in current versions.
> 
> Hi Ferroin,
> 
> Yes i can confirm this issue has been resolved for me.
> 
> However another issue i now have is that the auto-update doesn't seem to work.
> If i run the "/etc/periodic/daily/netdata-updater" script manually it does work fine altough i have to answer 1 question during the script with "Y" before it can continue and finish the update.
> Unfortunatelly i can't remember which question it was :(
> I will have to setup a seperate installation on my server and install an older version and run the update script again.

Hmm, that’s strange. Once you’ve got more info, please feel free to open a new issue, as that’s almost certainly a bug (probably a result of differences between FreeBSD and GNU userspace).

**Comment by abrbon** [comment]
> Hmm, that’s strange. Once you’ve got more info, please feel free to open a new issue, as that’s almost certainly a bug (probably a result of differences between FreeBSD and GNU userspace).

I have opened a new issue for this update issue on my TrueNAS server.
