### ISSUE TITLE
i see gaps in netdata charts and after sometime can't connect to netdata on 19999 just says waiting

### ISSUE THREAD

**Issue by fasihb** [netdata/netdata#9451]
##### Question summary
i have installed netdata on few servers but on one server it's acting weird. I see the errors in my email notification
host is critical - 10min dbengine global flushing errors - netdata.dbengine_long_term_page_stats

I looked at other issues over here and followed them and raised "page cache size" and "dbengine disk space" but didn't help. 

server is busy moderately. it has over 300GB memory and 80 cores
current load avg -- load average: 29.95, 34.41, 35.86

also, made changes to netdata.conf and restarted few times no changes
the other weird thing is when i try to stop it's taking like 3 to 5 mins to stop and then upon start i can hit the page but immediately sees gaps in the chart and after sometime i can't even hit the page it's just sit and says waiting

i did curl to run some apis and i don't get results as well. 

my netdata.conf is pretty much default except this. i tried adjusting higher or lower still no luck
  history = 7200
  update every = 1
  memory mode = dbengine
  page cache size = 500
  dbengine disk space = 2000

I also tried dbengine on / disk or a faster storage mount no difference

##### OS / Environment
centos 7
netdata version -latest v 1.23

**Comment by mfundul** [comment]
@stelfrag consider setting https://github.com/netdata/netdata/blob/62ce25168560104393651c3754b102cd99945977/database/engine/rrdengineapi.c#L10 to 0 as a workaround for all those related issues until we fix the problem with flushing errors.

**Comment by fasihb** [comment]
Hello,
I see that's a setting in the code. How do i update it in my env?

Thanks,
-Fasih

**Comment by bmatheny** [comment]
@mfundul can you link to any related open issues? It sounds like this is a known issue but I couldn't find any ongoing work. I'd rather not fix this myself if someone is already working on it. Thanks!

**Comment by mfundul** [comment]
> 
> 
> @mfundul can you link to any related open issues? It sounds like this is a known issue but I couldn't find any ongoing work. I'd rather not fix this myself if someone is already working on it. Thanks!

Sure, https://github.com/netdata/netdata/issues/8384
