### ISSUE TITLE
More options inside `ebpf.conf`

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#9455]
##### Feature idea summary
We need to add the next new sections and options for `ebpf.conf`:

```
[network viewer] 
  maximum dimensions = 500 
  ips = 192.68.0.0/2 192.167.0.0-192.168.255.255 4204:14c:5b72:1234:5678:1aee:ac11:cbb5/24
  hostnames = google.*  *example*
  ports = 2000-2009  ssh !144
[service names]
  19999 = netdata
```

The function `read_collector_values` needs to be changed to also parse these new values.

The options related to `ips` and `ports` will need to be converted to linked list in bigendian format to speed up the comparison with data read from kernel ring.

**Comment by ilyam8** [comment]
Have you considered using ip ranges/cidr format? It seems much more natural for IPs filtering.

**Comment by thiagoftsm** [comment]
I agree @ilyam8 , and other users already requested feature like this https://github.com/netdata/netdata/issues/8008.
We could use some code from https://github.com/thiagoftsm/iprange as @ktsaou already suggested for a case like this.

**Comment by thiagoftsm** [comment]
For more details about the change in the format, please, take a look at https://github.com/netdata/product/issues/488#issuecomment-660336651

**Comment by ilyam8** [comment]
Could you update OP?

It is not clear what is syntax/logic for `ips`/`ports`/`hostnames`.

I see there could be 2 different ways to match:

- return on first match: `false` if the pattern is negated (`!`), `true` otherwise
- match at least one positive pattern AND do not match any of negated patterns: `true` if the condition is met, `false` otherwise.

Which one of these 2 are u using for `ips`/`ports`/`hostnames`?

**Comment by thiagoftsm** [comment]
`hostnames` follows all rules that we have for simple patterns.
For `ips` and `ports`, when a range is denied `!139-145` We are rejecting the whole range, we always discard everything until the next space. 

About the space, we work as  an `OR`, the `IP` and `PORT` must be inside one of the possible specified ranges.

**Comment by ilyam8** [comment]
well, it is not clear for me still. There are 2 match logics in my post above.

Which one? Or there is another one? Can you explain **match condition** for `ips/ports`? If there is documentaion please give me the link.

**Comment by thiagoftsm** [comment]
The first is used:

``` 
return on first match: false if the pattern is negated (!), true otherwise [order is important]
```
