### ISSUE TITLE
Netdata - Pfsense unbound

### ISSUE THREAD

**Issue by andrema2** [netdata/netdata#9459]
Hi 

I'm trying to get unbound stats to appear on netdata on my pfsense. Netdata is running and getting a lot of data but unbound.

I looked for the go.d.plugin and it's not installed on the system. I know unbound-control is working and it's generating stats. 

To install Netdata I followed the guide for it on Netdata's page.

**Comment by ilyam8** [comment]
Hi, check this issue

https://github.com/netdata/netdata/issues/8549

Installing - it seem you need to download go.d.plugin yourself

See https://github.com/netdata/netdata/issues/8549#issuecomment-612179807 

(download latest - https://github.com/netdata/go.d.plugin/releases/latest)

**Comment by andrema2** [comment]
HI I was able to download the plugin 

if i run ./go.d.plugin -d -m unbound I can see a bunch of statistics coming from unbound, but still after stop and starting Netdata service I don't see it on the page. 

What am I missing ?

**Comment by ilyam8** [comment]
> if i run ./go.d.plugin -d -m 

i guess it is because you run it as a `root` user, am i right? Try as `netdata` 😄 



Check this comment

> https://github.com/netdata/netdata/issues/8549#issuecomment-608622748

**Comment by andrema2** [comment]
This is part of the result of the run above

[ INFO  ] main[main] plugin.go:102 instance is started
[ INFO  ] main[main] setup.go:39 loading config file
### **[ INFO  ] main[main] setup.go:47 looking for 'go.d.conf' in [/usr/etc/netdata /usr/usr/lib/netdata/conf.d]
[ WARN  ] main[main] setup.go:51 couldn't find config, will use defaults**
[ INFO  ] main[main] plugin.go:106 using config: enabled 'true', default_run 'true', max_procs '0', explicitly enabled modules '0'
[ INFO  ] main[main] setup.go:66 loading modules
[ INFO  ] main[main] setup.go:85 enabled/registered modules: 1/43
[ INFO  ] main[main] setup.go:90 building discovery config
[ INFO  ] main[main] setup.go:116 looking for 'unbound.conf' in [/usr/etc/netdata/go.d /usr/usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:120 couldn't find 'unbound' module config, will use default config
[ INFO  ] main[main] setup.go:128 dummy/read/watch paths: 1/0/0
[ INFO  ] discovery[manager] manager.go:90 registered discoverers: [dummy discovery]
[ INFO  ] discovery[manager] manager.go:95 instance is started
[ INFO  ] discovery[dummy] discovery.go:50 instance is started
[ INFO  ] run[manager] run.go:30 instance is started
[ INFO  ] discovery[dummy] discovery.go:51 instance is stopped
[ INFO  ] build[manager] build.go:91 instance is started
[ INFO  ] unbound[unbound] init.go:19 reading '/etc/unbound/unbound.conf'
[ INFO  ] unbound[unbound] init.go:41 applying configuration: ["statistics-cumulative": 'no', "control-enable": 'yes', "control-interface": '127.0.0.1', "control-port": '953', "control-user-cert": '', "control-key-file": '/var/unbound/unbound_control.key', "control-cert-file": '/var/unbound/unbound_control.pem']
[ DEBUG ] unbound[unbound] init.go:51 changing 'tls_key': '/etc/unbound/unbound_control.key' => '/var/unbound/unbound_control.key'
[ DEBUG ] unbound[unbound] init.go:55 changing 'tls_cert': '/etc/unbound/unbound_control.pem' => '/var/unbound/unbound_control.pem'
[ DEBUG ] unbound[unbound] init.go:66 changing 'address': '127.0.0.1:8953' => '127.0.0.1:953'
[ DEBUG ] unbound[unbound] unbound.go:82 using address: 127.0.0.1:953, cumulative: false, use_tls: true, timeout: 1s
[ DEBUG ] unbound[unbound] unbound.go:84 using tls_skip_verify: true, tls_key: /var/unbound/unbound_control.key, tls_cert: /var/unbound/unbound_control.pem
[ DEBUG ] run[manager] run.go:41 tick 0
[ INFO  ] unbound[unbound] job.go:152 check success
[ INFO  ] unbound[unbound] job.go:172 started, data collection interval 1s

**Comment by andrema2** [comment]
As per above it doesn't find some files. But it is using its default. 
I guess not find it, makes it doesn't start with the service. What should I do to force it recognize that the unbound needs to start ?

**Comment by ilyam8** [comment]
i see collector extracts all parameters from the `/etc/unbound/unbound.conf`, seems good.

```cmd
[ INFO  ] unbound[unbound] init.go:19 reading '/etc/unbound/unbound.conf'
[ INFO  ] unbound[unbound] init.go:41 applying configuration: ["statistics-cumulative": 'no', "control-enable": 'yes', "control-interface": '127.0.0.1', "control-port": '953', "control-user-cert": '', "control-key-file": '/var/unbound/unbound_control.key', "control-cert-file": '/var/unbound/unbound_control.pem']
[ DEBUG ] unbound[unbound] init.go:51 changing 'tls_key': '/etc/unbound/unbound_control.key' => '/var/unbound/unbound_control.key'
[ DEBUG ] unbound[unbound] init.go:55 changing 'tls_cert': '/etc/unbound/unbound_control.pem' => '/var/unbound/unbound_control.pem'
[ DEBUG ] unbound[unbound] init.go:66 changing 'address': '127.0.0.1:8953' => '127.0.0.1:953'
[ DEBUG ] unbound[unbound] unbound.go:82 using address: 127.0.0.1:953, cumulative: false, use_tls: true, timeout: 1s
[ DEBUG ] unbound[unbound] unbound.go:84 using tls_skip_verify: true, tls_key: /var/unbound/unbound_control.key, tls_cert: /var/unbound/unbound_control.pem
```

---

as i mentioned above the problem is permissions - try to run the plugin in the debug mode as `netdata` user

**Comment by ilyam8** [comment]
btw does the plugin prints charts after initialization? Do you see them in the debug output?

**Comment by ilyam8** [comment]
@TDJ211 @andrema2

if you guys have time it would be nice to update [unbound module readme](https://github.com/netdata/go.d.plugin/tree/master/modules/unbound#unbound-monitoring-with-netdata) with instruction how to get it working on bsd systems. PRs are welcome!

**Comment by andrema2** [comment]
Ok, so now I've created the go.d.conf and unbound.conf
The line for unbound is uncommented.
This is the result of the ./go.d.plugin -d -m unbound before the statistics starts to show

[ INFO  ] main[main] plugin.go:102 instance is started
[ INFO  ] main[main] setup.go:39 loading config file
[ INFO  ] main[main] setup.go:47 looking for 'go.d.conf' in [/usr/etc/netdata /usr/usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:54 found '/usr/etc/netdata/go.d.conf
[ INFO  ] main[main] setup.go:61 config successfully loaded
[ INFO  ] main[main] plugin.go:106 using config: enabled 'true', default_run 'true', max_procs '0', explicitly enabled modules '1'
[ INFO  ] main[main] setup.go:66 loading modules
[ INFO  ] main[main] setup.go:85 enabled/registered modules: 1/43
[ INFO  ] main[main] setup.go:90 building discovery config
[ INFO  ] main[main] setup.go:116 looking for 'unbound.conf' in [/usr/etc/netdata/go.d /usr/usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:123 found '/usr/etc/netdata/go.d/unbound.conf
[ INFO  ] main[main] setup.go:128 dummy/read/watch paths: 0/1/0
[ INFO  ] discovery[manager] manager.go:90 registered discoverers: [file discovery: [file reader]]
[ INFO  ] discovery[manager] manager.go:95 instance is started
[ INFO  ] run[manager] run.go:30 instance is started
[ INFO  ] build[manager] build.go:91 instance is started
[ INFO  ] discovery[file manager] discovery.go:71 instance is started
[ INFO  ] discovery[file reader] read.go:39 instance is started
[ INFO  ] discovery[file reader] read.go:40 instance is stopped
[ INFO  ] unbound[local] init.go:19 reading '/usr/local/etc/unbound/unbound.conf'
[ INFO  ] unbound[local] init.go:41 applying configuration: ["statistics-cumulative": 'no', "control-enable": 'yes', "control-interface": '127.0.0.1', "control-port": '953', "control-user-cert": '', "control-key-file": '/var/unbound/unbound_control.key', "control-cert-file": '/var/unbound/unbound_control.pem']
[ DEBUG ] unbound[local] init.go:51 changing 'tls_key': '/usr/local/etc/unbound/unbound_control.key' => '/var/unbound/unbound_control.key'
[ DEBUG ] unbound[local] init.go:55 changing 'tls_cert': '/usr/local/etc/unbound/unbound_control.pem' => '/var/unbound/unbound_control.pem'
[ DEBUG ] unbound[local] init.go:66 changing 'address': '127.0.0.1:8953' => '127.0.0.1:953'
[ DEBUG ] unbound[local] unbound.go:82 using address: 127.0.0.1:953, cumulative: false, use_tls: true, timeout: 1s
[ DEBUG ] unbound[local] unbound.go:84 using tls_skip_verify: true, tls_key: /var/unbound/unbound_control.key, tls_cert: /var/unbound/unbound_control.pem
[ INFO  ] unbound[local] job.go:152 check success
[ INFO  ] unbound[local] job.go:172 started, data collection interval 1s
[ DEBUG ] run[manager] run.go:41 tick 0

Looks like netdata doesn't know it has to start the plugin

**Comment by andrema2** [comment]
> btw does the plugin prints charts after initialization? Do you see them in the debug output?

No there it no charts. Why do you think it is a permission issue ? 

I try to look for the unbound.go file. It doesn't exist on my pfsense. Should it exist ?

**Comment by ilyam8** [comment]
> Looks like netdata doesn't know it has to start the plugin

check logs


(cd to netdata log dir) `grep unbound error.log`

**Comment by andrema2** [comment]
Tks, it was looking in a different place for the unbound.conf
