### ISSUE TITLE
Add support for a bulk-data query to the web-server

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#9464]
#### Summary

Add support for bulk data queries to the web API. Queries will look like this:
```
host:19999/api/v1/snapshot?charts=system.cpu,system.load,system.io&after=-300&points=10
```

* The returned data will be a single json value encoding an array of dictionaries, one dictionary per chart.
* The `charts` parameter will encode a comma separated list of chart ids. The `,` is a reserved character in URL schemas and may need to be decoded from `U+002C` if the sending agent has encoded it.
* Wildcards should be supported - mapping the `,` separators to spaces would allow simple patterns to be passed (the `*` may be encoded byt he sending agent).
* In particular the query should allow metrics to be downloaded from all charts (that is `?charts=*` or `?charts=%2A`).

The query must support time-ranges and aggregation of data-points in the same way as the existing `data?` query.

Necessary parameters:
* `charts` - comma separated list of simple patterns.
* `before` - absolute or relative timestamp specifying the ending point of the data.
* `after` - absolute or relative timestamp specifying the start point of the data.
* `group` - specifying the aggregation function if points are grouped.
* `gtime` - time in seconds per group

Note: `options`, `callback` and `format` will not be supported. There will be a single format supported by the endpoint.

* Add a configuration option to limit the maximum range of bulk-data queries to prevent DoS of the agent. This should support limits by maximum number of points (per chart) and by time ranges.

Sample result (**white-space not included in result**, only here for clarity):
```
[
  "system.cpu": {
      "start_time":1593432863,
      "end_time":1593432873,
      "format" : "plain",
      "dimensions" : [
          {
             "id" : "guest_nice",
             "data" : [0,0,0.25,0,0.7]
          },
          {
             "id" : "guest",
             "data" : [0,0.25,0,0.0143523,0.7]
          },
          ....
      ]
  },
  "system.load" : ...
]
```

* The `format` field is for a future extension. Initially the only supported mode will be arrays of data values as shown. Transport-layer compression must be supported as with other web queries so that if the requesting agent supports a compression scheme then the result should be compressed.
* The query can be accessed either via http or as an encapsulated request over the ACLK. There will not be a separate protocol message - the headers and URL are passed for encapsulated requests.

**Comment by andrewm4894** [comment]
@amoss one thing might be how we handle charts that capture data on different frequencies and how we can keep track of that without it getting too inefficient. 

e.g it i want chart.a and chart.b but chart.a is every 1 sec and chart.b is every 5 sec. 

We may be ok to just infer the frequency from the length of `data` perhaps.

But just wondering if this might get a bit crazy if had lots of charts all with different random frequencies. Trying to actually put a timestamp back against each data point could get tricky is my fear. 

I may be over complicating things but just wanted to mention.

**Comment by amoss** [comment]
I've avoided duplicating the meta-data into the response to cut down on size. The `update_every` values are part of the chart metadata so the caller could choose to batch by update frequencies in the call.

**Comment by amoss** [comment]
Let's leave this open until after the charts meeting as we may end up needing this. Feel free to re-close after the meeting if this is no longer relevant.

**Comment by amoss** [comment]
Let's leave this open until after the charts meeting as we may end up needing this. Feel free to re-close after the meeting if this is no longer relevant.

**Comment by amoss** [comment]
@dim08 You win this time :)
