### ISSUE TITLE
Memory usage went way up with version 1.23.x

### ISSUE THREAD

**Issue by shoopdawoop** [netdata/netdata#9471]
After upgrading from v1.22.0 to v1.23.1 memory usage went up by a lot.

I noticed because the Ubuntu 18.04 LTS VM (VMware Fusion) I tested this on  was running just fine with a single CPU core and 1 GB RAM. After upgrading to v1.23.1 the VM crashed hard (out of memory).

So I tried again (rolled back to a snapshot) but assigned two CPU cores and 2 GB RAM to the same VM.
The update went fine, again, but this time I could see the memory footprint go up by a lot right after the update.

<img width="214" alt="ram-goes-boom" src="https://user-images.githubusercontent.com/6615875/86478002-db6f7b00-bd49-11ea-99b1-1d0bb2aa13e4.png">

Before updating: memory usage with netdata 1.22.0 running (idle): ~300 MB
After updating: memory usage with netdata 1.23.1 running (idle): ~1.6 GB

This no longer seems lightweight.

To check I did a fresh install of netdata (via install script) on a Ubuntu 20.04 LTS VM (2 CPU cores, 2 GB RAM) and got about the same results:

Memory usage with netdata 1.23.1 stopped: ~470 MB
Memory usage with netdata 1.23.1 started ~1.6 GB

So, what might be causing this?

**Comment by vlvkobal** [comment]
Please look at the `apps.mem`chart. What group of applications is using the memory?

**Comment by shoopdawoop** [comment]
Correction: I was running netdata 1.22.1 before updating to 1.23.1.

The apps.mem chart looks fine to me (Ubuntu 20.04 LTS, netdata v1.23.1).

<img width="160" alt="ub20-apps mem" src="https://user-images.githubusercontent.com/6615875/86512213-614dfd80-be00-11ea-9bc1-70459e976755.png">


Same on the Ubuntu 18.04 LTS VM...

Before (netdata v1.22.1):

<img width="168" alt="apps-mem-18 04-v1 22 1 " src="https://user-images.githubusercontent.com/6615875/86512206-3bc0f400-be00-11ea-9299-de2193e469f0.png">

After (netdata v1.23.1):

<img width="163" alt="apps-mem-18 04-v1 23 1 " src="https://user-images.githubusercontent.com/6615875/86512208-4085a800-be00-11ea-8e4d-e739be2bdc44.png">

On the Ubuntu 18.04 LTS VM, before updating a 'free -h' gives me

Mem:  1.9G
Used: 278M
Free: 1.3G

After updating to netdata 1.23.1 a 'free -h' gives me

Mem:  1.9G
Used: 1.6G
Free: 75M


With netdata service stopped:

Mem:  1.9G
Used: 261M
Free: 1.4G

And with netdata service started again:

Mem:  1.9G
Used: 1.6G
Free: 71M

**Comment by cakrit** [comment]
Something is very strange here @shoopdawoop. Can you please a `top` and/or a `ps faux` to show what is actually using the memory? Memory can't just go nowhere, netdata itself should have seen that 1.3G being used by a process in one application group. It looks like the memory used by all of the apps together doesn't even come close to the Used memory shown in the total mem chart and in `free -h`

**Comment by shoopdawoop** [comment]
Thanks, cakrit.

I just looked into the issue again today and it seems like updating to v1.24.0 stable solved the issue on a Ubuntu 20.04 LTS VM and on a Ubuntu 18.04.5 LTS VM, both running with 1 GB RAM. I'm not sure if I was missing something before, but for now I consider this problem solved.
