### ISSUE TITLE
./go.d.plugin: No such file or directory

### ISSUE THREAD

**Issue by prophoto** [netdata/netdata#9472]
New to Netdata, please bear with me. Experienced Linux sysadmin. Installed Netdata for the first time today on one of my webservers.  Was hoping to monitor OS stats as well as apache custom logs. 

##### Bug report summary
Attempting to troubleshoot web_log go plugin. https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin. I've been searching for over 2 hours but can't find any additional documentation on how to run this plugin. Your docs say its installed with Netdata but maybe not?

bash-4.2$ ./go.d.plugin -d -m web_log
bash: ./go.d.plugin: No such file or directory

##### OS / Environment
/etc/centos-release:CentOS Linux release 7.6.1810 (Core) 
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.6.1810 (Core) 
/etc/system-release:CentOS Linux release 7.6.1810 (Core)

**Comment by ilyam8** [comment]
Hi. go.d.plugin is not in PATH.

if your netdata is running

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ ps faxu | grep "[n]etdata"
netdata  12137  0.2 10.8 291164 110792 ?       Ssl  Jul01   7:09 /opt/netdata/usr/sbin/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D
netdata  12154  0.0  0.2  44392  2368 ?        Sl   Jul01   0:00  \_ /opt/netdata/usr/sbin/netdata --special-spawn-server
netdata  12289  0.3  1.9 724868 19524 ?        Sl   Jul01  12:20  \_ /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata  12291  0.1  5.1 107020 53056 ?        Sl   Jul01   6:36  \_ /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata  12293  0.8  0.4  35300  4732 ?        S    Jul01  29:24  \_ /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1 no-groups no-users
netdata   3718  0.2  0.3  10224  3324 ?        S    17:24   0:32  \_ bash /opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin
```

> netdata  12289  0.3  1.9 724868 19524 ?        Sl   Jul01  12:20  \_ /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1

> cd /opt/netdata/usr/libexec/netdata/plugins.d/

**Comment by prophoto** [comment]
[centos@server9 opt]$ ps faxu | grep "[n]etdata"
netdata  19828  0.6  3.7 323240 38064 ?        Ssl  20:21   0:16 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D
netdata  19832  0.0  0.0  63268   332 ?        Sl   20:21   0:00  \_ /usr/sbin/netdata --special-spawn-server
netdata  19945  0.0  0.0   9692   932 ?        S    20:21   0:01  \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata  19959  0.0  1.2 142856 12672 ?        Sl   20:21   0:01  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata  19960  0.8  0.1  56292  1672 ?        S    20:21   0:23  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
root     19961  0.2  0.1 222360  1044 ?        Sl   20:21   0:07  \_ /usr/libexec/netdata/plugins.d/ebpf.plugin 1
netdata  19963  0.0  0.2 723452  3012 ?        Sl   20:21   0:01  \_ /usr/libexec/netdata/plugins.d/go.d.plugin 1

[centos@server9 opt]$ cd /opt/netdata/usr/libexec/netdata/plugins.d/
-bash: cd: /opt/netdata/usr/libexec/netdata/plugins.d/: No such file or directory

**Comment by ilyam8** [comment]
yeah, you have installed it not int `/opt`, see


```cmd
netdata  19963  0.0  0.2 723452  3012 ?        Sl   20:21   0:01  \_ /usr/libexec/netdata/plugins.d/go.d.plugin 1
```

So `cd /usr/libexec/netdata/plugins.d/`

**Comment by prophoto** [comment]
I just ran your one line installer, where it actually put the files was up to you haha

bash <(curl -Ss https://my-netdata.io/kickstart.sh)

**Comment by prophoto** [comment]
Ok now I know why the plugin is failing. Netdata is a member of apachelogs. Tried with Selinux set to permissive. Netdata still can't read access_log. Suggestions?

[centos@server9 conf]$ sudo ls -lat /var/log/httpd/access_log
-rwxr-x--x. 1 root apachelogs 17739986 Jul  3 21:42 /var/log/httpd/access_log
[centos@server9 log]$ sudo su -s /bin/bash netdata
bash-4.2$ cat /var/log/httpd/access_log
cat: /var/log/httpd/access_log: Permission denied

**Comment by ilyam8** [comment]
I see it is readable for `apachelogs` groups members, but you get _Permission denied_, it is likely you are right and the problems is SELinux. I have no exp with SELinux so not much help from me 🤷‍♂️

**Comment by thiagoftsm** [comment]
Hello @prophoto ,

I am not sure if this can help, because I am not specialist in SELinux, but I had to use `audit2allow` to enable Netdata to run `ebpf.plugin` on CentOS 7.x . You can find details in this [link](https://learn.netdata.cloud/docs/agent/collectors/ebpf.plugin#creation-of-bpf-policies). Probably you will need to do few steps that I did to also enable Netdata to read these files.

Best regards!

**Comment by prophoto** [comment]
Wasn't an SELinux issue, some kind of special protected directory. Found answer here, question was perfectly relevant even though some idiots downvoted it and got it closed on stack.

https://serverfault.com/questions/548541/apache-logs-other-user-read-permissions#comment1001205_548544

chmod go+rX /var/log/httpd
