### ISSUE TITLE
portcheck and x509 stop working for a while

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9473]
##### Bug report summary

We encountered a strange problem, one a netdata child, we have a few `portcheck` module destination and a few `x509` certificate checks. The system was working as expected until a few days ago (I'm not sure if it is related or not but after updating parents to version `1.23.0`), now every few hours, we start to get lots of `last collected` error from these two plugins. I can telnet to the destinations without any problem and in the meantime, our Blackbox exporter can collect metrics from the `portcheck` destinations.
After running `TCPdump` on the server, I realized netdata is not sending any metrics to the portcheck targets. after about 15 to 20 minutes, everything backs to normal (tcpdump also shows the packets being sent ) until a few hours later which this problem will happen again.
The netdata version on the netdata child was `1.22.1` but even updating to `v1.23.0` didn't fix the problem

##### OS / Environment

```
4.4.0-176-generic #206-Ubuntu SMP Fri Feb 28 05:02:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 parent: v1.23.0
child: v1.22.1 updated to v1.23.0

##### Component Name

go.d plugin

**Comment by ilyam8** [comment]
Hi

Did you check logs?

**Comment by yasharne** [comment]
Hi @ilyam8 
Yes I did, during the successful collection, I get this output:
```
2020-07-04 11:09:39: go.d INFO: portcheck[google] check success
2020-07-04 11:09:39: go.d INFO: portcheck[google] started, data collection interval 10s
2020-07-04 11:58:45: go.d INFO: portcheck[google] check success
2020-07-04 11:58:45: go.d INFO: portcheck[google] started, data collection interval 10s
```
As you can see, between 11:09 to 11:58 (which we had the problem) I didn't see any output in the log file

**Comment by yasharne** [comment]
Also for X509 plugin I didn't find any error and the last log was successful collection of the metrics

**Comment by ilyam8** [comment]
> portcheck and x509 stop working for a while

only go collectors? do you see gaps only only on go collectors charts?

**Comment by yasharne** [comment]
@ilyam8 Yes only go collectors, 
I see A LOT of gaps on the go collectors chart, some of them leading to `last collected` errors, e.g.
![image](https://user-images.githubusercontent.com/7656049/86514017-00d0b780-be24-11ea-9dad-b9da997fabc9.png)

**Comment by yasharne** [comment]
And also this machine makes a lot of alert causes parent server crash because of high system load.
The parent is only monitoring 51

**Comment by ilyam8** [comment]
did u try debug mode during problem periods?

**Comment by yasharne** [comment]
@ilyam8 Ilthough I have set the `NETDATA_USER_CONFIG_DIR` to point to the `/opt/netdata/etc/netdata/` directory, when I run `/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin -d -m x509check` I get this error:
```
[ INFO  ] main[main] plugin.go:102 instance is started
[ INFO  ] main[main] setup.go:39 loading config file
[ INFO  ] main[main] setup.go:47 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ WARN  ] main[main] setup.go:51 couldn't find config, will use defaults
[ INFO  ] main[main] plugin.go:106 using config: enabled 'true', default_run 'true', max_procs '0', explicitly enabled modules '0'
[ INFO  ] main[main] setup.go:66 loading modules
[ INFO  ] main[main] setup.go:85 enabled/registered modules: 1/43
[ INFO  ] main[main] setup.go:90 building discovery config
[ INFO  ] main[main] setup.go:116 looking for 'x509check.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:120 couldn't find 'x509check' module config, will use default config
[ INFO  ] main[main] setup.go:128 dummy/read/watch paths: 1/0/0
[ INFO  ] discovery[manager] manager.go:90 registered discoverers: [dummy discovery]
[ INFO  ] discovery[manager] manager.go:95 instance is started
[ INFO  ] run[manager] run.go:30 instance is started
[ INFO  ] build[manager] build.go:91 instance is started
[ INFO  ] discovery[dummy] discovery.go:50 instance is started
[ INFO  ] discovery[dummy] discovery.go:51 instance is stopped
[ ERROR ] x509check[x509check] x509check.go:69 error on validating config: source is not set
[ ERROR ] x509check[x509check] job.go:144 init failed
```

**Comment by ilyam8** [comment]
well, 🤷‍♂️, if it was set it would work

https://github.com/netdata/go.d.plugin/blob/c4db41e5edc0f75893dfafec2068aa6022413fe2/cmd/godplugin/main.go#L59-L100

However you can use `-c` option to set modules config dir.

**Comment by yasharne** [comment]
@ilyam8  I will set `NETDATA_STOCK_CONFIG_DIR` as well, I hope this will fix the main problem

**Comment by yasharne** [comment]
Nope it didn’t help :(

**Comment by ilyam8** [comment]
> did u try debug mode during problem periods?

?

+ `grep go.d error.log`

**Comment by yasharne** [comment]
@ilyam8 
As I mentioned earlier I didn't find anything in the logs (it won't log anything during the period of not responding)
But I couldn't run the debug because it mostly happens in the middle of the night and I cannot test it.

**Comment by yasharne** [comment]
Installing netdata binaries again has fixed the problem apparently, so I'm going to close this issue
