### ISSUE TITLE
How to change to stable release update after nightly release installation?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#9476]
Installed netdata with automatically update and nightly update, but wish to change to stable release, any way to do that rather than reinstall again with `--stable-channel`?

**Comment by prologic** [comment]
@startryst Hi 👋 You would in fact be effectively downgrading if you wanted to do this (_even if we had the tooling for this_). You would be better of just re-installing with the right option -- Which btw is also what upgrading does anyway.

FWIW you _could_ modified the following (_the default location_) hwoever I cannot vouch for this;

```#!sh
prologic@debian:~$ cat /etc/netdata/.environment | grep RELEASE_CHANNEL
RELEASE_CHANNEL="nightly"
```

I would suggest you just re-install :)

**Comment by prologic** [comment]
Closing as duplicate of #9160

**Comment by startryst** [comment]
> @startryst Hi 👋 You would in fact be effectively downgrading if you wanted to do this (_even if we had the tooling for this_). You would be better of just re-installing with the right option -- Which btw is also what upgrading does anyway.
> 
> FWIW you _could_ modified the following (_the default location_) hwoever I cannot vouch for this;
> 
> ```
> prologic@debian:~$ cat /etc/netdata/.environment | grep RELEASE_CHANNEL
> RELEASE_CHANNEL="nightly"
> ```
> 
> I would suggest you just re-install :)

ok, I'll go with re-install then. Thanks.
