### ISSUE TITLE
Problem with netdata-updater

### ISSUE THREAD

**Issue by camjesus2** [netdata/netdata#9478]
Hi all,
I've been struggling with this issue for the last few days and finally I think I have some useful info.
First, my setup:

4 Debian buster based machines on a 3 childs/1 parent setup. The parent uses ELK backend for long term storage. 1 child is a VM, all others are physical machines. Another child is an OpenMediaVault server for backups. Last child is a SAMBA File Server. All running last nightly versions of netdata.

Now the issue:
I'll describe 2 issues on 2 different machines, but I think it's actually symptoms of the same issue. Here goes:
1) On the samba file server, every morning the SAMBA monitoring is disabled. I need to go to python.d.conf and re-enable `SAMBA: yes`. It seems that the update process replaces python.d.conf and doesn't honor the SAMBA directive. Everything else seems to work as expected.
2) On the OMV server, every morning, the netdata service is stopped. Restarting it works perfectly until next morning. After a lot of log digging (with no clear culprit) I've decided to disable netdata-updater all together. It seems to be working. Updating with `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` seems to have no issues.

This seemed to have started somewhere between 1.19 and 1.23 (I bit vague, I know)
Any ideas on how to solve/troubleshoot? Manual updating is not that bad, still...

Best regards!

**Comment by ilyam8** [comment]
> On the samba file server, every morning the SAMBA monitoring is disabled.

There are stock and user directories with config files. 

> https://learn.netdata.cloud/docs/agent/configuration-guide


updater overwrites stock config files on every update, you need to make changes in user configs

**Comment by camjesus2** [comment]
According to this:
https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin/samba
samba needs to " be explicitly enabled in python.d.conf".

Is the documentation wrong?

Ilya Mashchenko <notifications@github.com> escreveu no dia sábado,
4/07/2020 à(s) 15:01:

**Comment by ilyam8** [comment]
no, it is not wrong, it should be explicitly enabled (`samnba: yes`) in the `python.d.conf`

**Comment by camjesus2** [comment]
Then, again, after I enable it, the updater disables it every morning.

Ilya Mashchenko <notifications@github.com> escreveu no dia sábado,
4/07/2020 à(s) 17:14:

**Comment by ilyam8** [comment]
see my comment

> https://github.com/netdata/netdata/issues/9478#issuecomment-653769932

you need to make changes in user config, not in stock (which is overwritten by the updater)

Make changes in the `/etc/netdata/pyhton.d.conf`

**Comment by camjesus2** [comment]
There is no  /etc/netdata/pyhton.d.conf.
Should I copy the "stock" one?


Ilya Mashchenko <notifications@github.com> escreveu no dia sábado,
4/07/2020 à(s) 17:23:

**Comment by ilyam8** [comment]
yes, there is `edit-config` script in the `/etc/netdata`

```
cd /etc/netdata
./edit-config python.d.conf
```
