### ISSUE TITLE
Add mongo-c-driver to netdata Docker image to support mongoDB exporter

### ISSUE THREAD

**Issue by Vincinator** [netdata/netdata#9479]
NetData is amazing. I love it. 

To use NetData's mongoDB exporter, the ```libmongoc >= 1.7.0``` library must be installed before NetData is built.
However, the Docker images do not have the required library installed before NetData is built. 

##### Feature idea summary
Out of box support for MongoDB exporting for NetData docker images.

Below you will find an exemplary patch that adds ```mongo-c-driver-dev``` packet to the NetData Docker images.

```diff
diff --git a/packaging/docker/Dockerfile b/packaging/docker/Dockerfile
index c36554c8..2244a6c5 100644
--- a/packaging/docker/Dockerfile
+++ b/packaging/docker/Dockerfile
@@ -24,6 +24,10 @@ ENV EXTRA_INSTALL_OPTS=$EXTRA_INSTALL_OPTS
 COPY . /opt/netdata.git
 WORKDIR /opt/netdata.git
 
+# Dependencies to build mongoc
+RUN apk update && \
+    apk add --upgrade mongo-c-driver-dev --repository=http://dl-cdn.alpinelinux.org/alpine/v3.11/community/
+
 # Install from source
 RUN chmod +x netdata-installer.sh && \
    cp -rp /deps/* /usr/local/ && \
@@ -57,6 +61,10 @@ ARG ARCH
 # This image contains preinstalled dependecies
 FROM netdata/base:${ARCH}
 
+RUN apk update && \
+    apk add --upgrade mongo-c-driver-dev --repository=http://dl-cdn.alpinelinux.org/alpine/v3.11/community/
+
+
 # Copy files over
 RUN mkdir -p /opt/src
 COPY --from=builder /app /
```

Please note that the mongo-c-driver-dev package should be installed in the ```netdata/base``` and in the ```netdata/builder```.  

##### Expected behavior

An option to use the mongoDB exporter feature with Netdata's docker images.

**Comment by prologic** [comment]
Hello @Vincinator Thank you for the detailed request! Are you willing to put up a PR? I can help you with this; there are in fact two images you need to modify to make this happen in [helper-images](https://github.com/netdata/helper-images) namely the builder and base images that you see we inherit from above.

A PR from you would be wonderful :)

**Comment by hqwisen** [comment]
Hello,

I stumbled on the same issue and tried also another approach, so I am putting it here. Not especially better, but since the base image is based on 3.9 I found a bit weird to use repos for v3.11. Here you go:

```
RUN wget https://github.com/mongodb/mongo-c-driver/releases/download/1.16.0/mongo-c-driver-1.16.0.tar.gz && \
    tar xzf mongo-c-driver-1.16.0.tar.gz && \
    cd mongo-c-driver-1.16.0 && \
    # Compile libbson first
    mkdir cmake-build-libbson && cd cmake-build-libbson && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DENABLE_MONGOC=OFF .. && \
    make install && \
    cd .. && mkdir cmake-build-mongoc && cd cmake-build-mongoc && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF .. && \
    make install
```

You still need to copy the compiled libs (mainly `libbson*` and `libmongoc*` from `/usr/lib/`) in the main stage, since it's apparently required at runtime.

**Comment by prologic** [comment]
Hmm in that case we are probably okay with also bumping the base image version of alpine we use as long as we throughly test it.

**Comment by Vincinator** [comment]
Hello @prologic, ah thanks - I was wondering where the Dockerfiles for base images are.
 
Ok, I will bump up the versions of builder and base to alpine 3.11, and add the library to these images as well. 
I will create an PR here [helper-images ](https://github.com/netdata/helper-images). 

I agree with @hqwisen that it feels weird to use a 3.11 repo on a 3.9 alpine image.

**Comment by Vincinator** [comment]
Unfortunately alpine 3.11 repos do not provide the ```py-mysqldb``` package in the [repos](https://pkgs.alpinelinux.org/packages?name=py-mysqldb&branch=v3.11), which is previously required by the netdata base image.

**Comment by prologic** [comment]
> Unfortunately alpine 3.11 repos do not provide the py-mysqldb package in the repos, which is required by the netdata base image.

That's okay. Just make sure Python 3.x is installed and `pip` is also available and just `pip install` the required python libraries. I really have a thing against using a package manager for things that are already well packaged personally -- So if they're not in Alpine APK packages, they are in PyPi (_hopefully pre-packaged as wheels_).

**Comment by Ferroin** [comment]
> > Unfortunately alpine 3.11 repos do not provide the py-mysqldb package in the repos, which is required by the netdata base image.
> 
> That's okay. Just make sure Python 3.x is installed and `pip` is also available and just `pip install` the required python libraries. I really have a thing against using a package manager for things that are already well packaged personally -- So if they're not in Alpine APK packages, they are in PyPi (_hopefully pre-packaged as wheels_).

I'm not certain that this one is in PyPI actually, and it's not just Alpine that's dropped it, it's disappearing from a lot of distros.

On a separate note, if we're updating the base images, we should be umping to the latest Alpine, which is 3.12, not 3.11.

**Comment by Vincinator** [comment]
> On a separate note, if we're updating the base images, we should be umping to the latest Alpine, which is 3.12, not 3.11.

Absolutely, I thought the same and bumped the alpine version to 3.12 in the PR.

> I'm not certain that this one is in PyPI actually, and it's not just Alpine that's dropped it, it's disappearing from a lot of distros.

The [py-mysqlclient](https://pkgs.alpinelinux.org/package/v3.9/community/x86/py-mysqlclient)  and the [py-mysqldb](https://pkgs.alpinelinux.org/package/v3.9/community/x86/py-mysqldb) alpine packages are referring both to the source [farcepest/MySQLdb1](https://github.com/farcepest/MySQLdb1) GitHub Repo.

The mysql client library for python2.x is [MySQL-python](https://pypi.org/project/MySQL-python/) (which does not support python 3.x currently) also points to that [farcepest/MySQLdb1](https://github.com/farcepest/MySQLdb1) GitHub Repo.

The [mysqlclient](https://pypi.org/project/mysqlclient/) python package adds support for python3 and is a fork of MySQLdb1. The fork can be found as [PyMySQL/mysqlclient-python](https://github.com/PyMySQL/mysqlclient-python) GitHub Repository.

Thus, I added the mysqlclient pip package to the PR [80 at the netdata/helper-images](https://github.com/netdata/helper-images/pull/80)

**Comment by prologic** [comment]
@Vincinator Since your PR is merged and this is working for you (_right?_) can I close this?

**Comment by Vincinator** [comment]
@prologic Sure! thanks for your support on this! :)
