### ISSUE TITLE
KernelCare and Netdata conflicts with kprobe events

### ISSUE THREAD

**Issue by sdeepakbz** [netdata/netdata#9480]
##### Bug report summary

I installed Netdata on cPanel server with KernelCare. KernelCare is unable to apply kernel patches due to kprobe events created by the netdata.
We reached out kernel care support and they investigated the issue with Kernel Care Patch.  Find an image for reference below
http://prntscr.com/tbt6ih
##### OS / Environment

```
Linux node.server.com 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)
```
##### Netdata version

  currently its removed. Installed yesterday using kickstrat script. so version will be Netdata v1.23.1 latest.
##### Component Name

kprobe events conflicts with kernel patching
##### Steps To Reproduce

1. Install cPanel on CentOS 7
2. Install KernelCare
3. Let kernelCare patch the kernel using cronjobs or run `/usr/bin/kcarectl --update` It will give an error.
Unable to apply patch (/var/cache/kcare/patches/none-1773540921d02e0d50f5433c8c3a4d5a02a14c33-5-edf/kpatch.edf.bin 5 255 CentOS Linux 3.10.0-1127.el7.x86_64, default, , , False)
More information from KernelCare Support:
http://prntscr.com/tbt6ih
4. uninstall netdata
5. try kernel patching and it fails.
6. remove kprobe events.
6. kernel patching successfully.
7. Server crashes to kernel panic and booting stuck with kprobe errors.
images: http://prntscr.com/tbrlly
http://prntscr.com/tbrprn
8. booted server to rescue mode
9. manual removal the netdata lines from the /sys/kernel/debug/tracing/kprobe_events file.
10. booted the system and centos kernel booted fine
##### Expected behavior

1) Uninstall should remove all the kprobe events from the system
2) Support for KernelCare patching on cPanel Servers.

**Comment by thiagoftsm** [comment]
Hi @sdeepakbz ,

On CentOS 7.x I only could run the ebpf.plugin and to install the `kprobes` after I change the SELinux specific configuration. When Netdata installs the `kprobe` it does not block other systems to install their `kprobe`, because we are customizing our entries inside `/sys/kernel/debug/tracing/kprobe_events`. 

I will take a look on KernelCare to try understand what it does, because I never worked with it before and I will bring more details during next week.

Best regards!

**Comment by thiagoftsm** [comment]
Hi @stephenrauch ,

I could identify a problem in the collector that was not allowing the plugin to close as expect. I created the PR #9484 that will fix the problem. When it is merged, you will be able to use `systemctl stop netdata` to install KernelCare and after this you can restart netdata using `systemctl start netdata`.

Best regards!

**Comment by sdeepakbz** [comment]
@thiagoftsm there is another concern that the netdata events are still present in /sys/kernel/debug/tracing/kprobe_events file
even after netdata is Uninstalled from the System.
Due to these events kernelcare care auto patch cron always fails including manual patching. If we clean the /sys/kernel/debug/tracing/kprobe_events and kernel patching is successful.

Kernelcare team said that "KernelCare is trying to patch do_fork(), but kprobe is blocking this."

**Comment by sdeepakbz** [comment]
Tried creating a test environment on AWS CentOS 7 image.
Installation gets stuck almost in the end and Instance is unreachable
http://prntscr.com/tcgoi6
http://prntscr.com/tcgpmy

Rebooting the instance boots the server but netdata status show.
systemctl status netdata
● netdata.service
   Loaded: masked (/usr/lib/systemd/system/netdata.service; masked; vendor preset: disabled)
   Active: inactive (dead)

Jul 06 08:23:48 ec2-13-58-160-243.us-east-2.compute.amazonaws.com systemd[1]: ...
Hint: Some lines were ellipsized, use -l to show in full

ran the install script again and it finishes successfully but netdata service is not active
http://prntscr.com/tcgxc5

`2020-07-06 08:44:04: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1024, max = 4096
2020-07-06 08:44:04: netdata INFO  : MAIN : Out-Of-Memory (OOM) score is already set to the wanted value 1000
2020-07-06 08:44:04: netdata INFO  : MAIN : Adjusted netdata scheduling policy to idle (5), with priority 0.
2020-07-06 08:44:04: netdata INFO  : MAIN : Running with process scheduling policy 'idle'
2020-07-06 08:44:04: netdata INFO  : MAIN : netdata started on pid 16726.
2020-07-06 08:44:04: netdata INFO  : MAIN : Initializing spawn client.
2020-07-06 08:44:04: netdata INFO  : MAIN : Executing /usr/libexec/netdata/plugins.d/system-info.sh
Spawn server is up.
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_NAME=none
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_ID=none
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_ID_LIKE=none
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_VERSION=none
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_VERSION_ID=none
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_DETECTION=none
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_NAME=CentOS Linux
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_ID=centos
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_ID_LIKE=rhel fedora
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_VERSION=7 (Core)
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_VERSION_ID=7
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_DETECTION=/etc/os-release
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_KERNEL_NAME=Linux
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_KERNEL_VERSION=3.10.0-1127.13.1.el7.x86_64
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_ARCHITECTURE=x86_64
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_VIRTUALIZATION=xen
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_VIRT_DETECTION=systemd-detect-virt
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CONTAINER=unknown
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CONTAINER_DETECTION=none
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_LOGICAL_CPU_COUNT=2
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_VENDOR=GenuineIntel
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_MODEL=Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_FREQ=2400000000
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_DETECTION=lscpu
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_TOTAL_RAM=3971751936
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_RAM_DETECTION=procfs
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_TOTAL_DISK_SIZE=32212254720
2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_DISK_DETECTION=sysfs
2020-07-06 08:44:04: netdata INFO  : MAIN : Configuring locking mechanism for global GUID map
2020-07-06 08:44:04: netdata INFO  : MAIN : Cannot open the file /var/lib/netdata/health.silencers.json, so Netdata will work with the default health configuration.
2020-07-06 08:44:04: netdata INFO  : MAIN : CONFIG: cannot load user config '/etc/netdata/stream.conf'. Will try stock config.
2020-07-06 08:44:04: netdata ERROR : MAIN : HEALTH [ec2-13-58-160-243.us-east-2.compute.amazonaws.com]: cannot open health file: /var/lib/netdata/health/health-log.db.old (errno 2, No such file or directory)
2020-07-06 08:44:04: netdata INFO  : MAIN : Found 3 files in path /var/cache/netdata/dbengine
2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf"
2020-07-06 08:44:04: netdata INFO  : MAIN : Matched file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf"
2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000000001.njf"
2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/metadatalog-00000-00001.mlf"
2020-07-06 08:44:04: netdata INFO  : MAIN : Initializing data file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf".
2020-07-06 08:44:04: netdata INFO  : MAIN : Data file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf" initialized (size:4096).
2020-07-06 08:44:04: netdata INFO  : MAIN : Loading journal file "/var/cache/netdata/dbengine/journalfile-1-0000000001.njf".
2020-07-06 08:44:04: netdata INFO  : MAIN : Journal file "/var/cache/netdata/dbengine/journalfile-1-0000000001.njf" loaded (size:4096).
2020-07-06 08:44:04: netdata INFO  : MAIN : Found 3 files in path /var/cache/netdata/dbengine
2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf"
2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000000001.njf"
2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/metadatalog-00000-00001.mlf"
2020-07-06 08:44:04: netdata INFO  : MAIN : Matched file "/var/cache/netdata/dbengine/metadatalog-00000-00001.mlf"
2020-07-06 08:44:04: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00001.mlf".
2020-07-06 08:44:04: netdata ERROR : MAIN : File length is too short.

2020-07-06 08:44:04: netdata ERROR : MAIN : 1 metadata log files failed to load.
2020-07-06 08:44:04: netdata ERROR : MAIN : Failed to scan path "/var/cache/netdata/dbengine".
2020-07-06 08:44:04: netdata ERROR : MAIN : Failed to initialize metadata log file event loop.
2020-07-06 08:44:04: netdata INFO  : MAIN : Freed 0 bytes of memory from page cache.
2020-07-06 08:44:04: netdata ERROR : MAIN : Host 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com': cannot initialize host with machine guid '75d3a43a-bf36-11ea-a76f-02a9de2b35a2'. Failed to initialize DB engine at '/var/cache/netdata'.
2020-07-06 08:44:04: netdata INFO  : MAIN : Freeing all memory for host 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com'...
2020-07-06 08:44:04: netdata ERROR : MAIN : RRDHOST 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com' removed from index, deleted the wrong entry.
2020-07-06 08:44:04: netdata ERROR : MAIN : Request to free RRDHOST 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com': cannot find it
2020-07-06 08:44:04: netdata INFO  : MAIN : SYSTEM_INFO: free 0x27e2410
2020-07-06 08:44:04: netdata FATAL : netdata : Cannot initialize localhost instance with name 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com'. # : Success

2020-07-06 08:44:04: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'FATAL' 'netdata:netdata' '1413@daemon/mai:main           /0'
2020-07-06 08:44:04: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2020-07-06 08:44:04: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'EXIT' 'ERROR' '-'
2020-07-06 08:44:04: netdata INFO  : MAIN : EXIT: cleaning up the database...
2020-07-06 08:44:04: netdata INFO  : MAIN : Cleaning up database [18446744073709551615 hosts(s)]...
2020-07-06 08:44:04: netdata INFO  : MAIN : EXIT: removing netdata PID file '/var/run/netdata/netdata.pid'...
2020-07-06 08:44:04: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.`

cPanel
CentOS 7
KernelCare (no patch applied yet)
ConfigServer Firewall (Deactivated Status)

**Comment by sdeepakbz** [comment]
On fresh AWS + CentOS 7 image installation went fine but it didn't add any kprobe events to the /sys/kernel/debug/tracing/kprobe_events file on the system.
http://prntscr.com/tco76r

However, netdata installation on testing cPanel server also didn't add any kprobe events. But the production server have those events even if netdata is uninstalled.

**Comment by thiagoftsm** [comment]
> @thiagoftsm there is another concern that the netdata events are still present in /sys/kernel/debug/tracing/kprobe_events file
> even after netdata is Uninstalled from the System.
> Due to these events kernelcare care auto patch cron always fails including manual patching. If we clean the /sys/kernel/debug/tracing/kprobe_events and kernel patching is successful.
> 
> Kernelcare team said that "KernelCare is trying to patch do_fork(), but kprobe is blocking this."
> 
> I will try to reproduce the issue on test environment with same stack and provide the details if required.

Hi @sdeepakbz ,

I pushed another commit for the PR I created few days ago. I tested extensively on CentOS 7.x today, and I observed that on old kernels the plugin was not cleaning correctly the file every time it ran. The commit that I pushed is adding a script to help clean the probes, this script is also called from `systemd` when it is stopping the service. Systemd is also used during the uninstall process, I hope these changes will help to remove the problems, at least during my tests it looks like that it fixed.

Best regards!

**Comment by thiagoftsm** [comment]
> Tried creating a test environment on AWS CentOS 7 image.

Did you disable SELinux on this image to run ebpf.plugin? On CentOS 7.x the plugin is not expected to run, thanks the default SELinux configuration.

Best regards!

**Comment by thiagoftsm** [comment]
> On fresh AWS + CentOS 7 image installation went fine but it didn't add any kprobe events to the /sys/kernel/debug/tracing/kprobe_events file on the system.
> http://prntscr.com/tco76r
> 
> However, netdata installation on testing cPanel server also didn't add any kprobe events. But the production server have those events even if netdata is uninstalled.

As I said, the plugin cannot run with default SELinux configuration, please can run the next command and give us the output?

```
grep ebpf /var/log/netdata/error.log
```

Finally, I apologize the delay to answer you, but I am working in another features that is taking my time.

Best regards!

**Comment by mfundul** [comment]
> 
> 
> Tried creating a test environment on AWS CentOS 7 image.
> Installation gets stuck almost in the end and Instance is unreachable
> http://prntscr.com/tcgoi6
> http://prntscr.com/tcgpmy
> 
> Rebooting the instance boots the server but netdata status show.
> systemctl status netdata
> ● netdata.service
> Loaded: masked (/usr/lib/systemd/system/netdata.service; masked; vendor preset: disabled)
> Active: inactive (dead)
> 
> Jul 06 08:23:48 ec2-13-58-160-243.us-east-2.compute.amazonaws.com systemd[1]: ...
> Hint: Some lines were ellipsized, use -l to show in full
> 
> ran the install script again and it finishes successfully but netdata service is not active
> http://prntscr.com/tcgxc5
> 
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1024, max = 4096
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Out-Of-Memory (OOM) score is already set to the wanted value 1000
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Adjusted netdata scheduling policy to idle (5), with priority 0.
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Running with process scheduling policy 'idle'
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : netdata started on pid 16726.
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Initializing spawn client.
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Executing /usr/libexec/netdata/plugins.d/system-info.sh
> > Spawn server is up.
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_NAME=none
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_ID=none
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_ID_LIKE=none
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_VERSION=none
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_VERSION_ID=none
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_CONTAINER_OS_DETECTION=none
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_NAME=CentOS Linux
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_ID=centos
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_ID_LIKE=rhel fedora
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_VERSION=7 (Core)
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_VERSION_ID=7
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_HOST_OS_DETECTION=/etc/os-release
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_KERNEL_NAME=Linux
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_KERNEL_VERSION=3.10.0-1127.13.1.el7.x86_64
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_ARCHITECTURE=x86_64
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_VIRTUALIZATION=xen
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_VIRT_DETECTION=systemd-detect-virt
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CONTAINER=unknown
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CONTAINER_DETECTION=none
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_LOGICAL_CPU_COUNT=2
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_VENDOR=GenuineIntel
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_MODEL=Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_FREQ=2400000000
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_CPU_DETECTION=lscpu
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_TOTAL_RAM=3971751936
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_RAM_DETECTION=procfs
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_TOTAL_DISK_SIZE=32212254720
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : NETDATA_SYSTEM_DISK_DETECTION=sysfs
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Configuring locking mechanism for global GUID map
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Cannot open the file /var/lib/netdata/health.silencers.json, so Netdata will work with the default health configuration.
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : CONFIG: cannot load user config '/etc/netdata/stream.conf'. Will try stock config.
> > 2020-07-06 08:44:04: netdata ERROR : MAIN : HEALTH [ec2-13-58-160-243.us-east-2.compute.amazonaws.com]: cannot open health file: /var/lib/netdata/health/health-log.db.old (errno 2, No such file or directory)
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Found 3 files in path /var/cache/netdata/dbengine
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf"
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Matched file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf"
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000000001.njf"
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/metadatalog-00000-00001.mlf"
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Initializing data file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf".
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Data file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf" initialized (size:4096).
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Loading journal file "/var/cache/netdata/dbengine/journalfile-1-0000000001.njf".
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Journal file "/var/cache/netdata/dbengine/journalfile-1-0000000001.njf" loaded (size:4096).
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Found 3 files in path /var/cache/netdata/dbengine
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/datafile-1-0000000001.ndf"
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000000001.njf"
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/metadatalog-00000-00001.mlf"
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Matched file "/var/cache/netdata/dbengine/metadatalog-00000-00001.mlf"
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00001.mlf".
> > 2020-07-06 08:44:04: netdata ERROR : MAIN : File length is too short.
> > 2020-07-06 08:44:04: netdata ERROR : MAIN : 1 metadata log files failed to load.
> > 2020-07-06 08:44:04: netdata ERROR : MAIN : Failed to scan path "/var/cache/netdata/dbengine".
> > 2020-07-06 08:44:04: netdata ERROR : MAIN : Failed to initialize metadata log file event loop.
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Freed 0 bytes of memory from page cache.
> > 2020-07-06 08:44:04: netdata ERROR : MAIN : Host 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com': cannot initialize host with machine guid '75d3a43a-bf36-11ea-a76f-02a9de2b35a2'. Failed to initialize DB engine at '/var/cache/netdata'.
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Freeing all memory for host 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com'...
> > 2020-07-06 08:44:04: netdata ERROR : MAIN : RRDHOST 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com' removed from index, deleted the wrong entry.
> > 2020-07-06 08:44:04: netdata ERROR : MAIN : Request to free RRDHOST 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com': cannot find it
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : SYSTEM_INFO: free 0x27e2410
> > 2020-07-06 08:44:04: netdata FATAL : netdata : Cannot initialize localhost instance with name 'ec2-13-58-160-243.us-east-2.compute.amazonaws.com'. # : Success
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'FATAL' 'netdata:netdata' '1413@daemon/mai:main           /0'
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'EXIT' 'ERROR' '-'
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : EXIT: cleaning up the database...
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : Cleaning up database [18446744073709551615 hosts(s)]...
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : EXIT: removing netdata PID file '/var/run/netdata/netdata.pid'...
> > 2020-07-06 08:44:04: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
> > EOF found in spawn pipe.
> > Shutting down spawn server event loop.
> > Shutting down spawn server loop complete.
> 
> cPanel
> CentOS 7
> KernelCare (no patch applied yet)
> ConfigServer Firewall (Deactivated Status)

@sdeepakbz there appears to be some corruption in your cache folder. You can delete the metric database by running `rm -f /var/cache/netdata/dbengine/*` to resolve this.

**Comment by sdeepakbz** [comment]
> I pushed another commit for the PR I created few days ago. I tested extensively on CentOS 7.x today, and I observed that on old kernels the plugin was not cleaning correctly the file every time it ran. The commit that I pushed is adding a script to help clean the probes, this script is also called from `systemd` when it is stopping the service. Systemd is also used during the uninstall process, I hope these changes will help to remove the problems, at least during my tests it looks like that it fixed.
> 
> Best regards!

Yes, now uninstalling netdata removes the /sys/kernel/debug/tracing/kprobe_events events as well correctly.

> @sdeepakbz there appears to be some corruption in your cache folder. You can delete the metric database by running `rm -f /var/cache/netdata/dbengine/*` to resolve this.

Thanks this fixed the startup of netdata process. Probably unexpected shutdown of the server while netdata was installing caused the cache corruption.

> > Tried creating a test environment on AWS CentOS 7 image.
> 
> Did you disable SELinux on this image to run ebpf.plugin? On CentOS 7.x the plugin is not expected to run, thanks the default SELinux configuration.
> 
> Best regards!

You are correct. SELinux was permissive. I disabled it and uninstalled netdata - rebooted server - started installation of netdata - got stuck in the end again and server restart itself - got masked status of netata and I started netdata kickstart again and the server restarted itself -  started the installation and it got successful > netdata was crashed > removed contents from /var/cache/netdata/dbengine/ directory as suggested by @mfundul and process started.

Further, I checked the kprobe events and can see they were added but did not found do_fork() event in the list and kernelcare patching went successful without any issues. I am not sure why do_fork() event is not added in this fresh installation of netdata.


[root@ec2-13-58-160-243 ~]# cat /sys/kernel/debug/tracing/kprobe_events
p:kprobes/p_netdata_tcp_sendmsg_1 tcp_sendmsg
p:kprobes/p_netdata_tcp_cleanup_rbuf_1 tcp_cleanup_rbuf
p:kprobes/p_netdata_tcp_close_1 tcp_close
p:kprobes/p_netdata_udp_recvmsg_1 udp_recvmsg
r:kprobes/r_netdata_udp_recvmsg_1 udp_recvmsg
p:kprobes/p_netdata_udp_sendmsg_1 udp_sendmsg
p:kprobes/p_netdata_do_exit_1 do_exit
p:kprobes/p_netdata_vfs_write_0 vfs_write

[root@ec2-13-58-160-243 ~]# kcarectl --update
Updates already downloaded
No updates are needed for this kernel
Kernel is safe

**Comment by thiagoftsm** [comment]
Hi @sdeepakbz ,

> Further, I checked the kprobe events and can see they were added but did not found do_fork() event in the list and kernelcare patching.

How is the output of the following command after the patch to be applied?

```
$ grep do_fork /proc/kallsyms
ffffffffa209acc0 T do_fork
ffffffffa2cf6340 d do_fork_test
```

Best regards!

**Comment by sdeepakbz** [comment]
Hello,

I am getting same

```
[root@ec2-13-58-160-243 ~]# grep do_fork /proc/kallsyms
ffffffff9349acc0 T do_fork
ffffffff940f6340 d do_fork_test
```
[root@ec2-13-58-160-243 ~]#

**Comment by thiagoftsm** [comment]
Hello @sdeepakbz,

I was a little busy last days with new features, so I did not have time to learn and test cPanel. Today I separated a time to move forward with everything I needed, unfortunately I could install cPanel on a VM, but when I tried to use `kcarectl --update` I discovered that I needed a license that is generated for a public IP, but the unique server that I have with public ip has CentOS 8, so I need to do more questions for you:

1 - Please, can you run the command `dmesg` and give me the error related to do_fork?
2 - Can you get any error inside your `error.log` that has relationship with ebpf.plugin?

Best regards!

**Comment by Ferroin** [comment]
@thiagoftsm In theory this is probably not specific to KernelCare. AFAICT, it's an interaction between our usage of kprobes and the Linux kernel's live patching functionality (I believe we're causing one of the live patching sanity checks to fail, it gets really picky about the state of the kernel being patched to ensure it actually works).

Unfortunately, I'm not sure of any other easy way to test this, because kernel live patching is a really niche thing (it only ever makes sense if you're truly unable to bring individual nodes down for kernel updates as it caries a pretty significant risk and can't actually 'fix' quite a few classes of bugs) and the required infra setup is not usually provided publicly.due to the amount of effort that has to go into it to get it right.

**Comment by thiagoftsm** [comment]
Thank you @Ferroin !
Do you know a Linux distribution that could help me to replicate this problem? I could not see this error with distributions I am working.

**Comment by Ferroin** [comment]
> Thank you @Ferroin !
> Do you know a Linux distribution that could help me to replicate this problem? I could not see this error with distributions I am working.

Unfortunately, I don't know of any free ones that provide kernel live patching support. I _think_ paid versions of OEL and RHEL offer it, but I'm not certain.
