### ISSUE TITLE
Go plugin is not following NETDATA_USER_CONFIG_DIR in version 1.23.0

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9481]
##### Bug report summary

We seem to have a problem with child netdatas running version `1.23.0` of netdata with `go.d.plugin` version `0.19.2`.
We always install the prebuilt binary package and had a problem running go plugins because the prebuild binary was looking for the configuration in  `/etc/netdata` or `/usr/lib/netdata/conf.d` whereas the prebuilt package is installed under `/opt/netdata` and configuration files are inside `/opt/netdata/etc/netdata/go.d/`. We overcome this problem by setting the `NETDATA_USER_CONFIG_DIR` variable to `/opt/netdata/etc/netdata/` but after updating the netdatas, apparently go plugins are not reading this variable. here is the sample output of debugging `mysql` plugin in `go.d`:
```bash
echo $NETDATA_USER_CONFIG_DIR
/opt/netdata/etc/netdata/

/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin -d -m mysql
[ INFO  ] main[main] plugin.go:102 instance is started
[ INFO  ] main[main] setup.go:39 loading config file
[ INFO  ] main[main] setup.go:47 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ WARN  ] main[main] setup.go:51 couldn't find config, will use defaults
[ INFO  ] main[main] plugin.go:106 using config: enabled 'true', default_run 'true', max_procs '0', explicitly enabled modules '0'
[ INFO  ] main[main] setup.go:66 loading modules
[ INFO  ] main[main] setup.go:85 enabled/registered modules: 1/43
[ INFO  ] main[main] setup.go:90 building discovery config
[ INFO  ] main[main] setup.go:116 looking for 'mysql.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:120 couldn't find 'mysql' module config, will use default config
[ INFO  ] main[main] setup.go:128 dummy/read/watch paths: 1/0/0
[ INFO  ] discovery[manager] manager.go:90 registered discoverers: [dummy discovery]
[ INFO  ] discovery[manager] manager.go:95 instance is started
[ INFO  ] discovery[dummy] discovery.go:50 instance is started
[ INFO  ] discovery[dummy] discovery.go:51 instance is stopped
[ INFO  ] run[manager] run.go:30 instance is started
[ INFO  ] build[manager] build.go:91 instance is started
[ ERROR ] mysql[mysql] mysql.go:58 DSN not set
[ ERROR ] mysql[mysql] job.go:144 init failed
[ DEBUG ] run[manager] run.go:41 tick 0
```

##### Netdata version

v1.23.0 

##### Component Name

go.d

**Comment by ilyam8** [comment]
You need to set both `NETDATA_USER_CONFIG_DIR` and `NETDATA_STOCK_CONFIG_DIR`

see

https://github.com/netdata/go.d.plugin/blob/c4db41e5edc0f75893dfafec2068aa6022413fe2/cmd/godplugin/main.go#L59-L100

**Comment by ilyam8** [comment]
Well, i kind of agree that it could work only with `NETDATA_USER_CONFIG_DIR`, but netdata deamon set both of them.

If you want to debug there is `-c` option.

**Comment by ilyam8** [comment]
However it makes sense and it is very easy to fix, ill do it.

Set both `NETDATA_USER_CONFIG_DIR` and `NETDATA_STOCK_CONFIG_DIR` to get it working with current version.

**Comment by yasharne** [comment]
Thanks @ilyam8 m setting `NETDATA_STOCK_CONFIG_DIR` solved the problem
