### ISSUE TITLE
MacOS/Catalina memory, swap and net info graphs disappear - after reboot or netdata service restart

### ISSUE THREAD

**Issue by fate8383** [netdata/netdata#9485]
##### Bug report summary
MacOS/Catalina memory, swap and net info graphs disappear - after reboot or netdata service restart. It works all good after brand new installation but after reboot they are gone.

##### OS / Environment
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
ProductName:    Mac OS X
ProductVersion: 10.15.5
BuildVersion:   19F101

##### Netdata version

 v1.23.1

##### Component Name

I guess charts component.
##### Steps To Reproduce

1. Install > brew install netdata
2. Restart service > brew services restart netdata
or full system reboot

I have several times uninstalled and reinstalled netdata just to make sure. My uninstalls are complete removal as in rm -rf all netdata directories. It works after new installation but again after rebooting the service or full system they are gone.

**Comment by barneyonline** [comment]
I too have this issue - I only see the CPU and Disk Read/Write information.

**OS / Environment**

ProductName: Mac OS X
ProductVersion: 10.15.5
BuildVersion: 19F101

**Netdata version**

v1.23.2

**Comment by vlvkobal** [comment]
I can replicate it on macOS 10.15.6.
When I delete `/usr/local/var/cache/netdata/*` it works again until the next restart.

**Comment by mfundul** [comment]
> 
> 
> I can replicate it on macOS 10.15.6.
> When I delete `/usr/local/var/cache/netdata/*` it works again until the next restart.

Does this happen on latest master? Does this happen with `memory mode = save`?

**Comment by vlvkobal** [comment]
```
2020-08-07 13:52:35: netdata INFO  : MAIN : Host 'mac-mini' (at registry as 'mac-mini') with guid '5cf6a2a0-d89a-11ea-9cc1-34363bd51656' initialized, os 'macos', timezone 'EEST', tags '', program_name 'netdata', program_version 'v1.23.2'
, update every 1, memory mode dbengine, history entries 3996, streaming disabled (to '' with api key ''), health enabled, cache_dir '/usr/local/var/cache/netdata', varlib_dir '/usr/local/var/lib/netdata', health_log '/usr/local/var/lib/n
etdata/health/health-log.db', alarms default handler '/usr/local/Cellar/netdata/1.23.2/libexec/netdata/plugins.d/alarm-notify.sh', alarms default recipient 'root'
```

**Comment by vlvkobal** [comment]
The issue occurs in the latest master (v1.23.2-142-g5a718bb8) as well.

**Comment by vlvkobal** [comment]
I can't replicate the issue with `memory mode = save`.
