### ISSUE TITLE
Health notification alarm link - 404 not found

### ISSUE THREAD

**Issue by andrezaycev** [netdata/netdata#9487]
##### Bug report summary

`404 page not found`error after click any Telegram alarm link. 

![image](https://user-images.githubusercontent.com/9984761/86574822-61d9c600-bfb1-11ea-8290-48381e90ca67.png)

**Example link** 
```
https://app.netdata.cloud/alarms/redirect?agentID=*****&host=****&chart=ip.tcp_accept_queue&family=tcp&alarm=1m_tcp_accept_queue_overflows&alarm_unique_id=1593409109&alarm_id=1594007158&alarm_event_id=5&alarm_when=1594023698
 ```
Agents claimed in app.netdata.cloud

##### Netdata version

 netdata v1.23.1-38-nightly

##### Steps To Reproduce

1. Claim agents to cloud
2. Click to alarm link in Telegram alarm message

**Comment by thiagoftsm** [comment]
> https://app.netdata.cloud/alarms/redirect?agentID=*****&host=****&chart=ip.tcp_accept_queue&family=tcp&alarm=1m_tcp_accept_queue_overflows&alarm_unique_id=1593409109&alarm_id=1594007158&alarm_event_id=5&alarm_when=1594023698

Your link is correct, so I  think we are having problem on the Cloud side. I assigned your issue to a cloud developer and to myself for we work on this.

Best regards!

**Comment by weijing24** [comment]
@thiagoftsm any update?

**Comment by thiagoftsm** [comment]
@manos-saratsis, @cakrit and @amoss  this is a missing feature since the cloud was released, please, can you bring an update here? Our users are able to redirect alarms only when they have a local register.

**Comment by cakrit** [comment]
Indeed, we had left it out and forgot about this one. We'll discuss, maybe we'll want to do something different here.

**Comment by cakrit** [comment]
I am doing a PR to temporarily have that URL replaced with at least a proper link to https://app.netdata.cloud
We will revisit this functionality, as a lot has changed in the past few months.
