### ISSUE TITLE
Correct method to remove host from registry

### ISSUE THREAD

**Issue by foamz** [netdata/netdata#9488]
We have a private Netdata registry and all nodes in our EC2 environment automatically install Netdata and is configured to stream metrics to the registry. This works beautifully... 
The issue we have is when we terminate a node. Since we have two guys that occasionally maintain Netdata and a bigger team of infrastructure guys, it has become increasingly difficult to manage when nodes are terminated. SMS's fly all over the place and not everyone knows when an alarm is a real problem or not.

So far I haven't been able to find docs or info on how I can handle terminated nodes and remove them from the registry. My best guess would be to remove the node information on the registry server located in `/var/lib/netdata` and restarting Netdata, I'm not particularly fond of this idea.
We don't use Netdata cloud, our policies does not allow it.

##### Question summary
What is the correct method to remove a node from the registry? 

##### OS / Environment
Amazon Linux. 
Netdata 1.22

##### Expected results
Node removed from registry and no alarms sent out for said node.

**Comment by thiagoftsm** [comment]
Hello @foamz ,

You are right, we need to improve our documentation related to registry. You can delete entries from your database `/var/lib/netdata/registry/registry.db` or you can use the URL that is written in our source code `/api/v1/registry?action=delete&machine=${machine_guid}&name=${hostname}&url=${url}&delete_url=${delete_url}` to remove entries.

I will copy all URLs that we have inside our source code, if you need more information direct from your registry:

```
// Pings a netdata server:
// /api/v1/registry?action=hello
//
// Access to a netdata registry:
// /api/v1/registry?action=access&machine=${machine_guid}&name=${hostname}&url=${url}
//
// Delete from a netdata registry:
// /api/v1/registry?action=delete&machine=${machine_guid}&name=${hostname}&url=${url}&delete_url=${delete_url}
//
// Search for the URLs of a machine:
// /api/v1/registry?action=search&machine=${machine_guid}&name=${hostname}&url=${url}&for=${machine_guid}
//
// Impersonate:
// /api/v1/registry?action=switch&machine=${machine_guid}&name=${hostname}&url=${url}&to=${new_person_guid}
```

Let us know if you have more doubts.

Best regards!

**Comment by foamz** [comment]
Hi @thiagoftsm 

Thank you for your help. I ran the `access` and `delete` actions, both returning ok, but the node is still available in the registry and web.

```
http://10.3.8.4:19999/api/v1/registry?action=access&machine=1f54f00e-999f-11e9-842f-02644be06a56&name=test-node-01&url=http:%2F%2F10.3.8.4%2Fhost%2Ftest-node-01%2F
```
returns:
```
{
	"action": "access",
	"status": "ok",
	"hostname": "netdata-server",
	"machine_guid": "263d07dc-bd32-11ea-bd5d-0242ac1c0002",
	"person_guid": "25d0d17f-3883-4454-8609-1b98e102c992",
	"urls": [
		[
			"1f54f00e-999f-11e9-842f-02644be06a56",
			"http://10.3.8.4/host/test-node-01/",
			1594128273000,
			1,
			"test-node-01"
		]
	]
}
```

Then I run `delete`:
```
http://10.3.8.4:19999/api/v1/registry?action=delete&machine=1f54f00e-999f-11e9-842f-02644be06a56&name=test-node-01&url=http:%2F%2F10.3.8.4%2Fhost%2Ftest-node-01%2F&delete_url=http:%2F%2F10.3.8.4%2Fhost%2Ftest-node-01%2F
```
returns:
```
{
	"action": "delete",
	"status": "ok",
	"hostname": "netdata-server",
	"machine_guid": "263d07dc-bd32-11ea-bd5d-0242ac1c0002"
}
```

Confirming deletion, but node is still there:
```
curl -s http://10.3.8.4/api/v1/info |jq .mirrored_hosts
[
  "netdata-server",
  "test-node-01"
]
```

I also tailed the Netdata logs and get no error, unless I try run the delete action twice:
```
2020-07-07 13:31:14: netdata INFO  : WEB_SERVER[static2] : Registry Request Verification: URL not found for person, person: '25d0d17f-3883-4454-8609-1b98e102c992', machine '1f54f00e-999f-11e9-842f-02644be06a56', url 'http://10.3.8.4/host/test-node-01/'
```

Is this a bug or am I doing something wrong?

**Comment by thiagoftsm** [comment]
Hi @foamz ,

You are not doing nothing wrong, let me explain.
The `mirrored_hosts` shows the list of the host that was created when they were connected with the Netdata running, if you restart your netdata, this list will be refreshed, on the other hand, I agree with you that when I remove a registry of a specific computer, it could be removed from the list.
@mfundul are registry db and host db are 100% linked? 

Best regards!
