### ISSUE TITLE
tc-qos helper is disabled after error

### ISSUE THREAD

**Issue by sereeds** [netdata/netdata#9493]
Since recent upgrade to Netdata 1.23.1-1, my QOS graphs stop updating after a some time.  Sometimes 4 hours, sometimes 20 mins.  Restarting Netdata is a temporary fix for the issue, but the error occurs and stops the tc-qos helper.
I have multiple machines running the same OS and version of Netdata, all have the same issue with the QOS chart.
I have pasted relevant error:

Is there any way to have the tc-qos helper restart on error instead of disabling it?
Or possibly a way to reject the bad data that is causing it to fail?

Thank you.

/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 21: 1593797528 * 1000 + 051259698: value too great for base (error token is "051259698")
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 58: [: : integer expression expected
/usr/lib/netdata/plugins.d/tc-qos-helper.sh: Cannot use current_time_ms_from_uptime() - new time 20 is older than the last 93199240 - falling back to current_time_ms_from_date().
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 21: 1593797528 * 1000 + 077823748: value too great for base (error token is "077823748")
2020-07-03 11:32:08: netdata ERROR : PLUGIN[tc] : child pid 454007 exited with code 1.
2020-07-03 11:32:08: netdata ERROR : PLUGIN[tc] : TC: tc-qos-helper.sh exited with code 1. Disabling it.

**Comment by thiagoftsm** [comment]
Hi @sereeds ,

The script is having problem to with the values it is getting, please, can you inform us your Operate System version for we try to recreate the problem?

Best regards!

**Comment by sereeds** [comment]
I am running Arch Linux, which is a rolling release.  Updated today.
I did notice that I was still running firehol 3.1.5.  I have now upgraded to firehol 3.1.6, and I will see if the problem persists.

**Comment by sereeds** [comment]
Confirmed the QOS chart stops after some time.
firehol 3.1.6
netdata v1.23.1

2020-07-06 17:16:20: tc-qos-helper.sh: INFO: Loading config file '/usr/lib/netdata/conf.d/tc-qos-helper.conf'...
2020-07-06 17:16:20: tc-qos-helper.sh: INFO: Loading config file '/etc/netdata/tc-qos-helper.conf'...
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 21: 1594077380 * 1000 + 078779334: value too great for base (error token is "078779334")
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 58: [: : integer expression expected
/usr/lib/netdata/plugins.d/tc-qos-helper.sh: Cannot use current_time_ms_from_uptime() - new time 30 is older than the last 373051270 - falling back to current_time_ms_from_date().
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 21: 1594077381 * 1000 + 01400971: value too great for base (error token is "01400971")
2020-07-06 17:16:21: netdata ERROR : PLUGIN[tc] : child pid 1470500 exited with code 1.
2020-07-06 17:16:21: netdata ERROR : PLUGIN[tc] : TC: tc-qos-helper.sh exited with code 1. Disabling it.
2020-07-06 17:16:21: netdata INFO  : PLUGIN[tc] : cleaning up...
2020-07-06 17:16:21: netdata INFO  : PLUGIN[tc] : thread with task id 1394732 finished

**Comment by thiagoftsm** [comment]
Hi @sereeds ,

Thank you for your initial feedback, I created an environment with `Firehol 3.1.6` and the latest `Netdata` like you, I am waiting for the collector fails. The unique difference from my environment for yours it is the fact I am using CentOS 8.2.2004, but this should not be a problem, because I am looking an error inside the collector.

I will return when I have more information.

Best regards!

**Comment by thiagoftsm** [comment]
Hi @sereeds ,

I am 8 hours without any problems, if in I can complete 24 hours without stop, I will install the Arch Linux and verify possible problems when running on Arch.

Best regards!

**Comment by thiagoftsm** [comment]
Hi @sereeds ,

After 32 hours collecting without any errors on  CentOS 8.x, I think that we have a problem when we are running on Arch Linux environment, I will get the same Arch Linux you are running today, and I will try to replicate this on Arch. I did not stop the plugin on CentOS, so I will have at least two environments to test the plugin.

Best regards!

**Comment by ilyam8** [comment]
i think the error is self-explanatory

```cmd
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 21: 1593797528 * 1000 + 051259698: value too great for base (error token is "051259698")
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 58: [: : integer expression expected
/usr/lib/netdata/plugins.d/tc-qos-helper.sh: Cannot use current_time_ms_from_uptime() - new time 20 is older than the last 93199240 - falling back to current_time_ms_from_date().
/usr/lib/netdata/plugins.d/loopsleepms.sh.inc: line 21: 1593797528 * 1000 + 077823748: value too great for base (error token is "077823748")
```

perhaps we need something like that?

- error

```cmd
0 go.d.plugin (prometheus *+%)$ echo $(( 1593797528 * 1000 + 077823748 ))
-bash: 1593797528 * 1000 + 077823748: value too great for base (error token is "077823748")
```

 - fix

```cmd
1 go.d.plugin (prometheus *+%)$ echo $(( 1593797528 * 1000 + 10#077823748 ))
1593875351748
```

@prologic ?

**Comment by thiagoftsm** [comment]
@sereeds ,

I was talking with @ilyam8 now,  and I would like to do a request for you that will also help me to check if I have the same Arch Linux that you have, please, can you give us the output of the following commands?

```
bash-5.0$ date --version
date (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
bash-5.0$ date +'%s * 1000 + %-N / 1000000'
1594299384 * 1000 + 529866656 / 1000000
```

Best regards!

**Comment by sereeds** [comment]
It appears I have the same output as you.

`date --version`
date (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.

`date +'%s * 1000 + %-N / 1000000'`
1594299655 * 1000 + 18343426 / 1000000

**Comment by ilyam8** [comment]
ok

this script exits with error after some time

https://github.com/netdata/netdata/blob/b9f9d8f771a03d5f246cba23719585d0ebc90fae/collectors/charts.d.plugin/loopsleepms.sh.inc#L21

```cmd
while true; do echo $(($(date +'%s * 1000 + %-N / 1000000'))); sleep 0.2; done
```

if i fix it with `10#` it never exits

```cmd
while true; do echo $(($(date +'%s * 1000 + 10#%-N / 1000000'))); sleep 0.2; done
```

**Comment by sereeds** [comment]
Excellent work @ilyam8 
Thank you.
I have applied your fix to my systems.

**Comment by ilyam8** [comment]
@sereeds please lets us know if it fixes the bug

**Comment by sereeds** [comment]
It's been over 8 hours, and I've pushed over 20 GB through 2 different boxes.
The chart is still working good; I believe this fix has solved the issue.
Thank you.
