### ISSUE TITLE
[IPFS-plugin] netdata's fast polling causes massive CPU-load by IPFS

### ISSUE THREAD

**Issue by RubenKelevra** [netdata/netdata#9505]
##### Bug report summary
I searched a while for the reason of the high CPU load of IPFS, turns out the fast polling of metrics via the IPFS plugin causes IPFS to use an enormous amount of CPU load - two threads are fully saturated on an AMD EPYC 7702P just to return those metrics.

There's a [bug report](https://github.com/ipfs/go-ipfs/issues/7528) on go-ipfs for this issue since metrics shouldn't really cause THAT much CPU load.

As a workaround, I suggest asking the IPFS-daemon every 2 minutes for the data until it's fixed on the go-ipfs-side.

##### OS / Environment

ArchLinux

##### Netdata version

netdata v1.23.1-49-nightly
 

##### Component Name
`collectors/python.d.plugin/ipfs`

##### Steps To Reproduce

1. use IPFS
2. use netdata

##### Expected behavior
No major increase in CPU load on a machine running both daemons.

**Comment by ilyam8** [comment]
have you enabled `pinapi` option?

https://github.com/netdata/netdata/blob/11e4ac13577ebe65b24e7b2a7bd594ae5e128539/collectors/python.d.plugin/ipfs/ipfs.conf#L65-L68

**Comment by ilyam8** [comment]
There are several requests

https://github.com/netdata/netdata/blob/11e4ac13577ebe65b24e7b2a7bd594ae5e128539/collectors/python.d.plugin/ipfs/ipfs.chart.py#L111-L122

Perhaps one of them causes high cpu usage? Can you debug it? (disable them one by one)

**Comment by ilyam8** [comment]
> As a workaround, I suggest asking the IPFS-daemon every 2 minutes for the data until it's fixed on the go-ipfs-side.

Why 2 minutes and not 10 seconds? How long does it take to execute ipfs module `get_data`?

**Comment by RubenKelevra** [comment]
> have you enabled `pinapi` option?
> 
> https://github.com/netdata/netdata/blob/11e4ac13577ebe65b24e7b2a7bd594ae5e128539/collectors/python.d.plugin/ipfs/ipfs.conf#L65-L68

Nope

> There are several requests
> 
> https://github.com/netdata/netdata/blob/11e4ac13577ebe65b24e7b2a7bd594ae5e128539/collectors/python.d.plugin/ipfs/ipfs.chart.py#L111-L122
> 
> Perhaps one of them causes high cpu usage? Can you debug it? (disable them one by one)

I wrote a cpu profile, it's clearly the repo request.

Btw there's no bandwidth graph shown, just peers, repo size and repo objects.


> > As a workaround, I suggest asking the IPFS-daemon every 2 minutes for the data until it's fixed on the go-ipfs-side.
> 
> Why 2 minutes and not 10 seconds? How long does it take to execute ipfs module `get_data`?

Because 200% which is barley keeping up means if we cut it in 10 parts is still above 10% two times on a fast processor.

That's unacceptable, since Netdata should be able to run on very low-end machines as well.

**Comment by ilyam8** [comment]
> Repo stuff isn't really changing that much either, so maybe we can buffer the values in the plugin and ask the API only every 2 minutes?

Well, it is not possible to have different charts with different `update_every`

i sugges to make `repo` request optional and disabled by default.

**Comment by ilyam8** [comment]
> i suggest to make repo request optional and disabled by default - same we did with pin/ls.

@RubenKelevra if you have time a PR is welcome ☺️

**Comment by RubenKelevra** [comment]
Okay, will look into this. Feel free to assign me to this

**Comment by ilyam8** [comment]
@RubenKelevra any updates?

**Comment by RubenKelevra** [comment]
@ilyam8 sorry for the delay, not feeling well right now. When I'm healthy again I'll get right to this. :)

**Comment by ilyam8** [comment]
@RubenKelevra it is a simple change and i did it, the changes are pretty straighforward and no really tests are needed, but test the [PR](https://github.com/netdata/netdata/pull/9687) when you have time.

And get well 🤞
