### ISSUE TITLE
Claim giving me a unknown HTTP error message

### ISSUE THREAD

**Issue by CX32** [netdata/netdata#9506]
##### Bug report summary

When I run the claim script it tells me that the node was already claimed. I overwrite this with the `-id=$(uuidgen)` parameter but I receive this error message: `Failed to claim node with the following error message:"Unknown HTTP error message"`

##### OS / Environment

```
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version

 netdata v1.23.1-49-nightly

##### Component Name

Claim script

##### Steps To Reproduce

1. Run the claim script with the `-id=$(uuidgen)` parameter
2. Get error `Failed to claim node with the following error message:"Unknown HTTP error message"`

##### Expected behavior

Node to be claimed successfully

**Comment by underhood** [comment]
Are you behind any proxy?
Is access to https://app.netdata.cloud direct and working from the machine where you attempt claiming?
Did you attempt to do it again afterwards to rule out some intermittent connection issue?

**Comment by cakrit** [comment]
Closing due to no response.
