### ISSUE TITLE
netdata streaming on openshift

### ISSUE THREAD

**Issue by itamar-marom** [netdata/netdata#9511]
#### Question summary
My environment include VMs and pods on Redhat Openshift.
My master agent is running on openshift with EXPOSE 19999 and external route.
When I try to stream an agent on a VM to the master I get stuck and I think it's because our Openshift currently block by default every non-HTTP protocol from outside to inside the cluster. Am I right ? If I am, will it be changed ? and why it's not an HTTP request ?
It's also important to note that when I setup my master on a VM it works perfectly.

just in case here's my error.log (those 4 lines over and over again):
INFO    : STREAM_SENDER[my-server] :  Waiting for connection to ip x.x.x.x port 19999 to be established
ERROR : STREAM_SENDER[my-server] :  Timed out while connecting to 'x.x.x.x', port '19999'. select() returned 1 (errno 115, Operation now in progress)
ERROR : STREAM_SENDER[my-server] : STREAM my-server [send to NETDATAMASTER]: failed to connect
INFO    : STREAM_SENDER[my-server] : STREAM my-server [send to NETDATAMASTER]: connecting...

##### OS / Environment
VM is RHEL7
OPENSHIFT 3
NETDATA v:1.22

**Comment by thiagoftsm** [comment]
Hello @itamar-marom ,

Netdata uses an HTTP-like protocol to start the stream, it is not officially a HTTP, but it has the same format, but after the handshake, the protocol used is not more something that looks like a HTTP protocol, if you can allow all traffics from and to port 19999, it is possible that you won't have more problems.

Best regards!

**Comment by itamar-marom** [comment]
I wish it was possible but sometimes security comes first.
Thank you for your answer!

**Comment by thiagoftsm** [comment]
Hi @itamar-marom ,

I agree with the sentence `security comes first`, so I have to do a question for you that will help us to improve Netdata. What is the exact problem that is not allowing Netdata to run inside your Network? If you have the list of words that starts each message, would this allow you to run Netdata?

Best regards!

**Comment by itamar-marom** [comment]
Hi @thiagoftsm ,
Openshift have a main router (HAPROXY) for outside traffic (and that's for security; Openshift is well known for it's restrictions). The only thing he works with is HTTP/S traffic. I guess that after the first handshake, the node sends to the master no-HTTP format and the HAPROXY does not allow it.

**Comment by thiagoftsm** [comment]
Thank you for your explanation @itamar-marom !
Considering that it only accepts HTTP/S, my suggestion for you to use Netdata in this environment, it is to configure TLS cryptography on [client](https://learn.netdata.cloud/docs/agent/streaming#options-for-the-sending-node) and in the server [side](https://learn.netdata.cloud/docs/agent/web/server#enabling-tls-support),   with this additional configuration, the communication will be completely encrypted. 

Best regards!
