### ISSUE TITLE
Removed charts from one machine

### ISSUE THREAD

**Issue by jordibiosca** [netdata/netdata#9516]
Hey,

I have netdata on several machines on my network and I've lost some charts on one of them. I've tried restarting netdata and installing a new version but nothing changed. Right now, I'm using the version v1.23.1-62-nightly for the machine not showing the charts of _net_errors_, _net_drops_ and _net_events_ at the **Network Interfaces** family. Can someone help me with that issue?

**Comment by thiagoftsm** [comment]
Hi @jordibiosca ,

Please, can you share your error.log with us?

Best regards!
