### ISSUE TITLE
[Feature Request] Implement Content Security Policy (CSP) best practices in Netdata

### ISSUE THREAD

**Issue by whalehub** [netdata/netdata#9523]
#### Feature idea summary
It is currently impossible to write a _safe_ Content Security Policy for a self-hosted instance of Netdata because attempting to whitelist the sha256 hashes of its numerous inline styles and scripts results in a header which exceeds the maximum size allowed by Nginx. To get Netdata to work correctly, the `unsafe-inline` option must be used both in the `script-src` and the `style-src` directives, which defeats a large part of the purpose of implementing a CSP in the first place.

#### Expected behavior
In order to follow best practices, Netdata must externalize all of its inline scripts and style sheets into `.js` and `.css` files respectively and reference them accordingly in its HTML files.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
