### ISSUE TITLE
War room keeps circling

### ISSUE THREAD

**Issue by weijing24** [netdata/netdata#9524]
#### Summary
Hi, I have two war rooms, `server-info` works perfect, but `http-check` keeps circling. I can't see any information from this room. I have tried reclaimming node to this room, but still not worked. Any one have ideas or same problems?
![image](https://user-images.githubusercontent.com/8737314/87218866-47c12e80-c389-11ea-8d60-be10f88b1d1d.png)

#### Component Name
netdata cloud, War Rooms

**Comment by weijing24** [comment]
Update:

If I add the node to `server-info`, I can see nodes.

**Comment by cakrit** [comment]
This is old and it hasn't been looked into. @weijing24 I expect that you can delete that problematic room and just put any other nodes it had elsewhere, they will still exist in your workspace. If you're still having problems, better email support@netdata.cloud which is focused on Netdata Cloud, or even better, post on https://community.netdata.cloud.
