### ISSUE TITLE
elasticsearch_last_collected, once alarm is raised, won't go away until netdata restart

### ISSUE THREAD

**Issue by tmikaeld** [netdata/netdata#9525]
##### Bug report summary

alarm: elasticsearch_last_collected
on: elasticsearch_local.cluster_health_status

Once alarm is raised, won't go away until netdata restart.

##### OS / Environment

```
Debian GNU/Linux 9 (stretch)
```

##### Netdata version

 
netdata v1.23.1-67-nightly

##### Component Name

elasticsearch_local

##### Steps To Reproduce

1. Start Elasticsearch
2. Stop data collection
3. Wait until alarm
4. Start data collection
5. Alarm persists

##### Expected behavior

Alarm should go away when data collection is OK again.

**Comment by ilyam8** [comment]
@tmikaeld

**Comment by tmikaeld** [comment]
Will do, thanks!

**Comment by tmikaeld** [comment]
I'll close and reopen if it's a problem still
