### ISSUE TITLE
geo-location of fail2ban denied attempts and jailed ip's

### ISSUE THREAD

**Issue by comperem** [netdata/netdata#9527]
##### Feature idea summary
the next step in monitoring fail2ban logs is listing, or even plotting geo-location of failed intrusion attempts and banned IP addresses on a world map. location does not have to be precise, but country would be very informative.

##### Expected behavior
In addition to current fail2ban monitoring (which is outstanding, by the way) these two additions would take fail2ban intrusion logging to the next level:

(a) table of time, intrusion date, and IP addresses with country would be quite helpful. using geoiplookup to identify country could populate a tooltip or label along the time axis in the standard netdata time series chart

(b) plot of intrusion attempts on a map would show intrusion locations quicky for the RDF database collected. geoip is already somewhat available with netdata here: https://www.fail2ban.org/wiki/index.php/HOWTO_use_geoiplookup

This is probably the file that would be the place to start:
https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/fail2ban/fail2ban.chart.py

Getting the geoip lookup database figured out and connected is half the battle.

**Comment by ilyam8** [comment]
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).
