### ISSUE TITLE
Compilation in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Abjorge95** [netdata/netdata#9528]
##### Bug report summary

Whet trying to install Netdata into my net Ubuntu Server 20.04 LTS, the installation break when trying to compile GEN netcatacli.

##### Log

`  GEN      netdatacli
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(context.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(libwebsockets.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(logs.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(lws-ring.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(output.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(close.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(vhost.c.o): relocation R_X86_64_32 against hidden symbol `available_roles' can not be used when making a PIE object
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(pollfd.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(service.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(wsi.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(wsi-timeout.c.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(sequencer.c.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(header.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(parsers.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(ops-h1.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(ops-ws.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(client-ws.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(client-parser-ws.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(server-ws.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(ops-raw-skt.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(ops-raw-file.c.o): relocation R_X86_64_32 against hidden symbol `role_ops_raw_file' can not be used when making a PIE object
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(connect.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(client.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(client.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(client-handshake.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(tls-network.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(tls.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(x509.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(ssl.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(tls-server.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(openssl-server.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(tls-client.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(openssl-client.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(sha-1.c.o): relocation R_X86_64_32S against `.rodata.cst16' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(http2.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(hpack.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(ops-h2.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(unix-caps.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(unix-file.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(unix-misc.c.o): relocation R_X86_64_32S against `.rodata.cst32' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(unix-init.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(unix-service.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(unix-sockets.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(unix-fds.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(server.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(buflist.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(base64-decode.c.o): relocation R_X86_64_32S against `.rodata.str1.16' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(vfs.c.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(dummy-callback.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(network.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(sorted-usec-list.c.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(adopt.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(ops-listen.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(tls.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:4327: netdata] Error 1
make[2]: Leaving directory '/tmp/netdata-kickstart-siojnk/netdata-v1.23.1-73-ged83879d'
make[1]: *** [Makefile:5460: all-recursive] Error 1
make[1]: Leaving directory '/tmp/netdata-kickstart-siojnk/netdata-v1.23.1-73-ged83879d'
make: *** [Makefile:2947: all] Error 2
 FAILED   

 FAILED  

 ABORTED  netdata-installer.sh exited with error `

**Comment by Abjorge95** [comment]
Greetings,

I followed the manual guide in order to compile with GCC like explained on the page and it worked, yet, not im getting the below erros on service status.

`Jul 12 18:39:02 lb0host02 ebpf.plugin[55656]: Does not have a configuration file inside '/etc/netdata/ebpf.conf. It will try to load stock file.`
`Jul 12 18:39:02 lb0host02 ebpf.plugin[55656]: PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'`

===== Full service status =====

● netdata.service - Real time performance monitoring
     Loaded: loaded (/lib/systemd/system/netdata.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2020-07-12 18:39:02 UTC; 5s ago
    Process: 55484 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 55486 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
    Process: 55497 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
    Process: 55498 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
   Main PID: 55499 (netdata)
      Tasks: 45 (limit: 16624)
     Memory: 54.2M
     CGroup: /system.slice/netdata.service
             ├─55499 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D
             ├─55501 /usr/sbin/netdata --special-spawn-server
             ├─55636 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
             ├─55650 /usr/libexec/netdata/plugins.d/go.d.plugin 1
             ├─55652 /usr/libexec/netdata/plugins.d/apps.plugin 1
             └─55658 /usr/bin/python3 /usr/libexec/netdata/plugins.d/python.d.plugin 1

Jul 12 18:39:02 lb0host02 systemd[1]: Starting Real time performance monitoring...
Jul 12 18:39:02 lb0host02 systemd[1]: Started Real time performance monitoring.
Jul 12 18:39:02 lb0host02 netdata[55499]: CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
Jul 12 18:39:02 lb0host02 netdata[55499]: 2020-07-12 18:39:02: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Runni>Jul 12 18:39:02 lb0host02 netdata[55499]: SIGNAL: Not enabling reaper
Jul 12 18:39:02 lb0host02 netdata[55499]: 2020-07-12 18:39:02: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Jul 12 18:39:02 lb0host02 ebpf.plugin[55656]: Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file.
Jul 12 18:39:02 lb0host02 ebpf.plugin[55656]: PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf'
Jul 12 18:39:02 lb0host02 ebpf.plugin[55656]: Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps>

**Comment by Abjorge95** [comment]
Greetings,

Weard update, but true, the fault above prevents me from visiting myip:19999 dashboard, but, if i use the cloud key to add to my cloud account, the new host will be added and all graphs are working and providing data and interaction.

**Comment by prologic** [comment]
Very similar (_if not identical_) to #8882

**Comment by Ferroin** [comment]
The build issue on Ubuntu 20.04  mentioned in the original post seems to be resolved as of at least release 1.25 (tested that, the current nightly, and the current master branch, and all seem to build without issue).

I'm working on trying to reproduce the issue with accessing the dashboard once built and installed.

**Comment by Ferroin** [comment]
OK, just checked, and I cannot reproduce the failure to access the dashboard on an up to date Ubuntu 20.04 system with v1.25, the current nightly, or the current master branch.

@Abjorge95 Can you please confirm if you are still seeing these issues or not? If not I'd say this issue can probably be closed.

**Comment by Ferroin** [comment]
Closing due to lack of response and inability to reproduce the issue.
