### ISSUE TITLE
ebpf.plugin segfault

### ISSUE THREAD

**Issue by mkauzlar** [netdata/netdata#9529]
On every machine we installed netdata we have many errors such as:

[Mon Jul 13 06:39:01 2020] EBPF PROCESS[20218]: segfault at 6410 ip 0000000000006410 sp 00007f3f77e3fb78 error 14 in ebpf.plugin (deleted)[55973a385000+10000]
[Mon Jul 13 06:39:08 2020] trace_kprobe: Event kprobes/r_netdata_vfs_write_0 doesn't exist.
[Mon Jul 13 06:39:08 2020] trace_kprobe: Event kprobes/r_netdata_tcp_sendmsg_0 doesn't exist.

All machines are either Ubuntu servers or Mint warkstations:
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"

Netdata is v1.23.1-77-nightly

The above error doesn't seem to create any problem on the system itself however monitoring systems keep on alerting.

**Comment by thiagoftsm** [comment]
Hi @mkauzlar ,

Is this happening when Netdata is ending? If this is the case, we already have a [PR](https://github.com/netdata/netdata/pull/9484) for this, if it is not, please, let me know and I will try to replicate and fix it.

Best regards!

**Comment by mkauzlar** [comment]
Hi @thiagoftsm,

I think it's related to the restart. It happens every day when this cron runs:
/etc/cron.daily/netdata-updater

Best regards

**Comment by thiagoftsm** [comment]
Thank you for your answer @mkauzlar !

> I think it's related to the restart. It happens every day when this cron runs:
We already have a fix for it and we will have the solution applied to master in the next days.

Best regards!
