### ISSUE TITLE
Reliance on fonts.gstatic.com for netdata cloud.

### ISSUE THREAD

**Issue by dragon2611** [netdata/netdata#9532]
This gets blocked on my network by a pihole, I could whitelist it but ideally it would be nice if there wasn't such an external dependency.

Mostly netdata cloud works but the chevrons don't display under visited nodes and the alt text makes the UI layout look awful.

<img width="270" alt="Screenshot 2020-07-13 at 14 04 13" src="https://user-images.githubusercontent.com/6185399/87307606-d1036d00-c511-11ea-93b3-cb7512b2a69d.png">

Filing it as a feature request because it's not really a bug (I.e working as designed)

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
