### ISSUE TITLE
Most alarms are disappearing after restart and "phantom" disks

### ISSUE THREAD

**Issue by aldem** [netdata/netdata#9534]
##### Bug report summary
I have noticed that only few alarms (from usually long list) are visible (in "All alarms" tab), so I tried to investigate what happens.

Deletion of dbengine data solved the issue... till netdata was restarted again - after restart I could see only fraction of all alarms:

![image](https://user-images.githubusercontent.com/754722/87366042-0347b580-c578-11ea-991a-270f508752a5.png)

That's all - subsequent restart didn't help, but deletion of data helps - once, until next restart.

Disabling all plugins didn't help too - the behavior was still the same.

Additional issue was related to deleted LVM devices - once deleted, they are still shown in netdata (even after restart and full browser refresh), and they even show some activity(!), though they are definitely do not exist anymore in the system - but probably this is unrelated and is worth dedicated ticket.

##### OS / Environment
```
Linux nuff 5.4.44-2-pve #1 SMP PVE 5.4.44-2
Debian 10 (Proxmox VE 6.2-9)
```

##### Netdata version
v1.23.1-77-g013c9da6

##### Steps To Reproduce
1. Remove all dbengine data files
2. Run netdata with this config:
```
[global]
        history = 90000
        memory mode = dbengine
        page cache size = 512
        dbengine disk space = 2048
        access log = none

[plugins]
        enable running new plugins = no
```
3. Check metrics and alarms
4. Restart
5. Check again

If the issue is not reproducible I could provide collected dbengine files (1st and 2nd run) and error logs (though there is nothing unusual).

Not sure if this is related to my hardware configuration or something else, but the observed problem is stable on at least two systems - mentioned above (real hardware) and on up-to-date Ubuntu 18.04 (QEMU guest) with completely fresh (first time) netdata install using kickstart script. Both systems are idling and have plenty of unused resources, so this is not RAM or disk space related.

Stable version (1.23.1) does not have this issue.

**Comment by ilyam8** [comment]
It was eary to reproduce for me

- stop netdata
- delete dbengine data
- start netdata
- check all alarms
- restart netdata
- check all alarms

After start:

<img width="432" alt="Screenshot 2020-07-14 at 11 06 59" src="https://user-images.githubusercontent.com/22274335/87401625-0ddb6c80-c5c3-11ea-951f-9c3401fc5743.png">


After restart:

<img width="434" alt="Screenshot 2020-07-14 at 11 10 52" src="https://user-images.githubusercontent.com/22274335/87401672-1b90f200-c5c3-11ea-8471-d01898c8fa02.png">

**Comment by ilyam8** [comment]
@aldem thx for reporting!
