### ISSUE TITLE
Identify and fix `make dist` CI checks for missing files

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#9542]
We keep getting biten by this.

Most recently:

- [This PR fixed missing `bundle-ebpf.sh`](https://github.com/netdata/netdata/pull/9539)
- [ This PR introduces `bundle-ebpf.sh` but forgot to include it in the dist](https://github.com/netdata/netdata/pull/9450)

However according to the [CI Check that ran](https://github.com/netdata/netdata/runs/823477814) it passed.

Clearly the check is either wrong or missing some functionality.

**Comment by prologic** [comment]
@Ferroin Please look into this as a matter of mid-pri when you have other things out of the way. We keep getting bitten by this. Let's not get bitten again :)

**Comment by thiagoftsm** [comment]
Hi @Ferroin ,

Can we close this issue? Or do we need to do something here?

Best regards!

**Comment by Ferroin** [comment]
This can be closed as it’s been completely resolved.
