### ISSUE TITLE
Copyright 2018?

### ISSUE THREAD

**Issue by ntlug** [netdata/netdata#9548]
##### Bug report summary

I printed off a PDF using the printer icon off the netdata dashboard, and the report at the bottom says:

Netdata (https://github.com/netdata/netdata/wiki)
Copyright 2018, Netdata, Inc (mailto:info@netdata.cloud).
Copyright 2016-2018, Costa Tsaousis (mailto:costa@tsaousis.gr).

##### OS / Environment

```

```

##### Netdata version

netdata v1.23.1-93-nightly

 

##### Component Name

netdata

##### Steps To Reproduce

Print something from netdata.

1. ...
2. ...

##### Expected behavior

I'm guessing that I should expect copyrights to 2020.

**Comment by ilyam8** [comment]
hi

i think it is the first date, you read it as `2018 - present`.

**Comment by ntlug** [comment]
I think I was tired.  Little things.  Sorry about the false alarm.
