### ISSUE TITLE
Incorrect display of LVM volume names in dashboard sidebar

### ISSUE THREAD

**Issue by aldem** [netdata/netdata#9554]
##### Bug report summary
After creating/removing volumes in LVM netdata shows previous (deleted) names instead of actual ones, while in chart itself it is correct.

I could not reproduce it with regular volumes so I believe this is LVM-bound (though I maybe wrong).

##### OS / Environment
```
Linux xub 5.4.0-40-generic #44~18.04.1-Ubuntu SMP
Ubuntu 18.04 fully updated, running in KVM
```

##### Netdata version
`v1.23.1-93-g8677f158` (stable) and `v1.23.1-100-gf4826b08` (latest nightly)

Plugins disabled, dead simple config, as usual:
```
[global]
        history = 90000
        memory mode = dbengine
        timezone = CET
        dbengine disk space = 1024
        page cache size = 256

[plugins]
        enable running new plugins = no
```

##### Steps To Reproduce
Create test LVM group & volumes (substitute /dev/sdX to your test disk):
```bash
# All commands are executed succesfully unless noted otherwise
pvcreate /dev/sdX
vgcreate vg /dev/sdX
# thin pool
lvcreate -L 1G -T vg/thin
lvcreate -V 1G -n t1 lvg/thin
lvcreate -V 1G -n t1 vg/thin
# regular volume
lvcreate -n lv1 -L 1G vg
```

After refreshing UI netdata shows on sidebar (under "Disks") all created volumes:
![image](https://user-images.githubusercontent.com/754722/87704150-3e2a3300-c79c-11ea-89d9-f6750dadde79.png)

Now get rid of them:
```bash
lvremove -y vg/lv1
lvremove -y vg/t1
lvremove -y vg/thin
```

After refresh netdata shows no LVM volumes anymore, as expected, so we create one again:
```bash
lvcreate -n v1 -L 1G vg
```
and re-check what we actually have:
```
# lvs -a

  LV      VG Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  v1      vg owi-a-s--- 1,00g                                                    

# lsblk -i

NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0  100G  0 disk 
|-sda1    8:1    0    4G  0 part [SWAP]
`-sda2    8:2    0   96G  0 part /
sdb       8:16   0   10G  0 disk 
`-vg-v1 253:0    0    1G  0 lvm  
```

Now after refreshing netdata UI... now on sidebar netdata show one of volumes which was created previously but does not exist:

![image](https://user-images.githubusercontent.com/754722/87704458-b5f85d80-c79c-11ea-9ba0-3d1f69e5567c.png)

Looks like as this "phantom" has replaced `vg-v1` as any attempt to access `vg-v1` show activity on `vg-thin tmeta`, and no wonder, as chart name (on the left) shows _proper_ name:
![image](https://user-images.githubusercontent.com/754722/87706638-218ffa00-c7a0-11ea-9f07-ffe3a4773a30.png)

##### Expected behavior

Correct display of volume names on sidebar.

**Comment by aldem** [comment]
Couple more glitches which are probably related:

![image](https://user-images.githubusercontent.com/754722/87735198-2327e500-c7d5-11ea-87fd-81c5bb0c4b44.png)

What is wrong:
- Sidebar: /var/lib/vz (existing mountpoint on LVM volume `npve-vz`)
- All I/O activity charts: unrelated (but existing) LVM volume `sraid-svar` (correct values for this volume)
- Space/files charts: volume which is indeed mapped to `/var/lib/vz` (correct values for this mount)

Another:

![image](https://user-images.githubusercontent.com/754722/87736052-700cbb00-c7d7-11ea-9c8c-812a35e9419a.png)

What is wrong:
- Sidebar: /raid/storage (existing mountpoint on LUKS non-LVM volume `/dev/mapper/oraid`)
- All I/O activity charts: existing but unrelated volume `npve-vz` (this is where `/var/lib/vz` from the above actually mounted)
- All space/files charts: correct name and values for this mountpoint and volume

And as in original report, restart (there were many) does not solve the issue, netdata `v1.23.1-100-gf4826b08`, however, sometimes (not always, most likely only when volumes are removed) restart makes a "gap" in collection - ca. 5 minutes in length, which is not normal (usually just few seconds are missing).

**Comment by RX14** [comment]
I can reproduce on netdata 1.23.2: ![](https://elixi.re/i/ebfo1ok9.png)

This is `lessar_left__cache`'s charts showing up under the heading of `lessar-test--vm`, which is a LV I had previously deleted.

**Comment by Ferroin** [comment]
I _think_ I know what's going on here, but don't have a concrete solution for how to fix it. Unless I'm mistaken, we use the actual `/dev/dm-*` path to keep track of the device stats (we actually have to use either that or the device  numbers to do so, there's not any other way, and the device numbers map 1:1 with the `/dev/dm-*` paths, so they would have the same issue). However, the uniqueness of a `/dev/dm-*` path (and device numbers) mapping to an LVM volume name is only guaranteed while the volume both exists and is active. Removing old LVs and adding new ones (or removing old ones and then deactivating and reactivating others) can cause reuse of the same path and device numbers. I believe what's happening here is that the newly created devices which are using paths/device numbers that were previously in use on the system are getting attached to the existing charts by Netdata, and Netdata only does the LVM volume name lookups for newly created charts, not reattachment to old ones.

I don't think there's any way we can completely fix this, though we should probably be using more than just the device path or device number for the chart context (probably either a hash of the DM table for the device, or a UUID if the system provides one that isn't just computed from the path or device numbers).

**Comment by ilyam8** [comment]
Yeah, the problem is using old metadata for a new chart (assuming chart id is the same, but family, etc 
 is different).

**Comment by aldem** [comment]
dmeventd is emitting events when there are changes in configuration - why not rescan and check mappings after every event which involves creation/deletion?

Or, as a last resort, it could be done once per minute, should not be that expensive, and in any case it should be re-examined on every restart.

**Comment by Ferroin** [comment]
We can't really rely on dmeventd always running and notifying about this, but if it's there we should probably use it. Same goes for watching for events from udev for this type of thing.

**Comment by aldem** [comment]
Well, polling once in a while (as an option) could be solution then, as there are systems where additions/deletions of volumes are quite frequent (and snapshots are volumes too).

**Comment by vlvkobal** [comment]
As I see it, there are two ways of solving the problem, both of them aren't simple.
1. We can rename the family when a new chart is created with a previously existing id but in this case, we need at least to rebuild variables for the changing chart. There may also be other dependencies. That will mend the name in the menu but previous data will still be displayed in the same chart as far as the chart id is the name of a reused device (`/dev/dm-*`). @mfundul, @stelfrag what do you think about this?
2. Another solution is to use UUIDs of LVM volumes as chart ids and map them to device-names to get stats from `/proc/diskstats`.
