### ISSUE TITLE
Installation from local files is broken

### ISSUE THREAD

**Issue by skibbipl** [netdata/netdata#9558]
##### Bug report summary
I wanted to install netdata on a system with blocked internet connectivity to external sites. So I followed the documentation and used this command to install netdata but I got following errors:
```
[user@server tmp]$ bash kickstart-static64.sh --local-files netdata-v1.23.2.gz.run sha256sums.txt
 --- Installation sources were given as input, running installation using "netdata-v1.23.2.gz.run" ---
[/tmp/netdata-kickstart-7No7HT]$ cp netdata-v1.23.2.gz.run /tmp/netdata-kickstart-7No7HT/netdata-latest.gz.run
cp: cannot stat `netdata-v1.23.2.gz.run': No such file or directory
 FAILED

[/tmp/netdata-kickstart-7No7HT]$ cp sha256sums.txt /tmp/netdata-kickstart-7No7HT/sha256sum.txt
cp: cannot stat `sha256sums.txt': No such file or directory
 FAILED

grep: /tmp/netdata-kickstart-7No7HT/sha256sum.txt: No such file or directory
 ABORTED  Static binary checksum validation failed. Stopping netdata installation and leaving binary in /tmp/netdata-kickstart-7No7HT
```
I think the problem is that offline installer first goes to created temporary dir and then tries to copy non existing files there.

##### OS / Environment
```
Linux server 2.6.32-754.25.1.el6.x86_64 #1 SMP Wed Nov 20 15:07:26 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/redhat-release:Red Hat Enterprise Linux Server release 6.10 (Santiago)
```
I also tried this on fresh debian with the same result.

##### Netdata version
N/A 

##### Component Name
Installer

##### Steps To Reproduce
`bash kickstart-static64.sh --local-files netdata-v1.23.2.gz.run sha256sums.txt`

##### Expected behavior
Installer working as expected.

**Comment by prologic** [comment]
@skibbipl Thanks for reporting. While we look into this, in the meantime can you try just running the Makeself archive directly? It should be a self-extracting shell script.

**Comment by Ferroin** [comment]
@skibbipl Can you please confirm if this is still an issue? We've made a lot of changes to the installer code recently and it may be fixed as a result.

**Comment by skibbipl** [comment]
`netdata-v1.24.0.gz.run` seems to be working fine for offline installation.
