### ISSUE TITLE
streaming problem with api key

### ISSUE THREAD

**Issue by itamar-marom** [netdata/netdata#9562]
##### Question summary
STREAMING problems with API KEY

##### OS / Environment
RHEL 7.x
netdata v1.21.1
isolated environment 

##### Component Name
I'm having trouble with my streaming to master with API KEY.
bellow is my master stream.conf:

```cmd
[aaa-bbb-ccc]
enabled = yes
allow from = *
default history = 3600
default memory mode = ram
health enabled by default = auto
```

and my slave's stream.conf:

```cmd
[stream]
enabled = yes
destination = masternode:19999
api key = aaa-bbb-ccc
```

of course my key was made by uuidgen command.

here is the master error log:
```cmd
netdata INFO : WEB_SERVER[static3] : clients wants to STREAM metrics.
netdata ERROR : WEB_SERVER[static3] : STREAM [receive from [x.x.x.x]:port]: API key 'aaa-bbb-ccc' is not allowed. Forbidding access.
```

here is the slave error log:

```cmd
netdata INFO : STREAM_SENDER[x.x.x.x] : STREAM x.x.x.x [send to masternode:19999]: connecting...
netdata INFO : STREAM_SENDER[x.x.x.x] : STREAM x.x.x.x [send to masternode:19999]: initializing communication...
netdata INFO : STREAM_SENDER[x.x.x.x] : STREAM x.x.x.x [send to masternode:19999]: waiting response from remote netdata...
netdata ERROR : STREAM_SENDER[x.x.x.x] : STREAM x.x.x.x [send to masternode:19999]: server is not replying properly (is it netdata?).`
```

also my master access.log:
```
`'ACCESS DENIED - KEY NOT ENABLED' host 'x.x.x.x' api key 'aaa-bbb-ccc' machine guid '...'
```
```

**Comment by thiagoftsm** [comment]
Hi @itamar-marom ,

The configuration that you are showing us looks like correct, so but this message is only shown when the key does not match 100%. Is it possible that server or child has utf-8 editor? 

Another thing that I would like to call attention, it is the fact that Netdata released `1.23.2` last week, please, can you update to confirm that this is not a bug already fixed?

Best regards!

**Comment by underhood** [comment]
not sure UTF-8 can be an issue here since uuid keys can involve only ASCII chars with which UTF-8 is backward compatible

**Comment by itamar-marom** [comment]
ITS A UTF-8 PROBLEM WITH VSCODE :(
If I write the conf file in putty it works...

**Comment by underhood** [comment]
@itamar-marom thanks for the info. @thiagoftsm this is strange we have to investigate this. Do we use any special characters in this config? If we just use ASCII chars (<=127) then UTF-8 == ASCII and it should not be a problem.

**Comment by thiagoftsm** [comment]
Hi @underhood ,

When our parser reads the line, it does not care for the character encode

https://github.com/netdata/netdata/blob/1a3a13397d4c6a87e69e1b65c31fadeac7a47e9d/libnetdata/config/appconfig.c#L646

We also do not have any restriction to the value name:

https://github.com/netdata/netdata/blob/1a3a13397d4c6a87e69e1b65c31fadeac7a47e9d/libnetdata/config/appconfig.c#L160

Considering that @itamar-marom is correct, I arrived in the conclusion that the unique possible problem was encode.
I never heard this problem on Netdata before, but in the past I had problems with other Linux software that did not allow UTF-8 and my user was using UTF-8 terminal.
