### ISSUE TITLE
Error loading shared library libjson-c.so.4: No such file or directory

### ISSUE THREAD

**Issue by Vorsku** [netdata/netdata#9573]
##### Bug report summary
Fresh Docker install and container won't start

##### OS / Environment
```
Linux docker-pi-03 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version
Latest version via netdata/netdata:latest
 

##### Component Name
Core?

##### Steps To Reproduce
docker-compose.yml file: 
https://pastebin.com/9fKkMPvG

docker-compose up

Resulting errors: 
https://pastebin.com/gYEb7dyV

##### Expected behavior
Container to start

**Comment by Ferroin** [comment]
@Vorsku I cannot reproduce this locally with our current Docker images. Can you please try pulling the latest image and see if that fixes things for you? If you still see the issue, please post the output of `docker image inspect netdata/netdata:latest` run on the host where the container is running (if you're worried about possibly sensitive data, all I'm interested in is the contents of the "Id", "RepoDigests", "Created", and "RootFS" keys).

**Comment by Vorsku** [comment]
@Ferroin looks like the new version is working now, thanks.

**Comment by Ferroin** [comment]
> @Ferroin looks like the new version is working now, thanks.

@Vorsku Glad to hear it.

I'd suggest double checking the storage on the system in question BTW. The exact errors you were getting are rater reminiscent of stuff I've seen before in cases of at-rest data corruption, and the fact that pulling the latest image fixed it would be consistent with that possibility.

**Comment by mfundul** [comment]
> 
> 
> > @Ferroin looks like the new version is working now, thanks.
> 
> @Vorsku Glad to hear it.
> 
> I'd suggest double checking the storage on the system in question BTW. The exact errors you were getting are rater reminiscent of stuff I've seen before in cases of at-rest data corruption, and the fact that pulling the latest image fixed it would be consistent with that possibility.

If it's an SD card device it's also notoriously consistent with the data corruption possibility.

**Comment by Zeik0s** [comment]
> 
> 
> > @Ferroin looks like the new version is working now, thanks.
> 
> @Vorsku Glad to hear it.
> 
> I'd suggest double checking the storage on the system in question BTW. The exact errors you were getting are rater reminiscent of stuff I've seen before in cases of at-rest data corruption, and the fact that pulling the latest image fixed it would be consistent with that possibility.

will also try the upgrade, but i have the same Error on an x64 VServer, with some HDDs as Storage. So i presume for me that i don't have any data at rest corruption.
