### ISSUE TITLE
help pages extremely slow

### ISSUE THREAD

**Issue by glaszig** [netdata/netdata#9578]
##### Bug report summary

this is happening on learn.netdata.cloud.
the inspector showed me insane amounts of css style invalidations _every second_.
after some time, safari even shows a warning "this website uses a lot of energy".

usage in safari is a pain, in firefox not so much but still noticeable. battery drain is insane for a static page.

<img width="319" alt="Bildschirmfoto 2020-07-21 um 15 38 52" src="https://user-images.githubusercontent.com/201135/88062705-78fbe480-cb69-11ea-95c9-9b187c49cd46.png">
<img width="308" alt="Bildschirmfoto 2020-07-21 um 15 30 45" src="https://user-images.githubusercontent.com/201135/88062716-7c8f6b80-cb69-11ea-9c23-4f7d8baff880.png">

##### OS / Environment
macOS 10.14.6
Safari 12.1.2
Firefox 78.0.2

**Comment by prologic** [comment]
I don't seem to be able to reproduce this here.

Specs:

- macOS 10.15.5
- Safari 13.1.1
- Firefox 78.0.2

**Comment by ilyam8** [comment]
> this is happening on learn.netdata.cloud.

@joelhans please take a look

**Comment by cakrit** [comment]
We don't need to reproduce by hand, let's improve what's shown in https://developers.google.com/speed/pagespeed/insights/?hl=en-US&url=learn.netdata.cloud

**Comment by zack-shoylev** [comment]
@cakrit I'm not sure how much we can rely on pagespeed to drive improvements. It's good to find specific issues, but the overall score does not seem that bad.

If you run it against netdata.cloud, it scores 12.
If you run it against developers.google.com it scores a 45.
For comparison learn.netdata.cloud scores 55.

Some more notes from looking into this: 
The script stuff can maybe be improved by updating and reconfiguring docusaurus. See https://v2.docusaurus.io/docs/docusaurus.config.js/#scripts
The CSS and fonts might need some work also.

**Comment by zack-shoylev** [comment]
I verified we are running on the latest docusaurus.
The docusaurus conf seems to be properly configured (we don't even use any extra scripts).

@glaszig are the CSS style invalidations happening on Firefox or just Safari?

Otherwise I don't see much we can do unless we can track down the original issue.

**Comment by zack-shoylev** [comment]
@joelhans we can discuss further when you are back, but performance mostly looks alright to me. We can maybe get 500ms if we compromise with fonts.

**Comment by prologic** [comment]
The _thing_ here is we moved from a docs site using a static site generator to a much more complicated services with a dynamic backend. Not that I _think_ that was a bad idea or anything, just that the expectation that it will ever be as "fast" as it was when we used a static site generator are unrealistic. We _did_ have the option of exploring [Hugo](https://gohugo.io/) as an alternative to the tools we were using to generate the site but unfortunately we didn't go down this path.

Perhaps we could also talk to the guys that now host the [learn.netdata.cloud](https://learn.netdata.cloud) -- Maybe they have some monitoring tools and insights into performance or some upgrades we can pay for to make it go faster?

**Comment by prologic** [comment]
We also don't currently run this through Cloudflare's CDN and Edge proxies at all.

<img width="1038" alt="Screen Shot 2020-08-13 at 20 51 22" src="https://user-images.githubusercontent.com/1290234/90126303-cc4b0680-dda6-11ea-966c-24415bda04d1.png">

We _could_ enable "Orange Cloud" here as a first step?

**Comment by zack-shoylev** [comment]
I looked at netlify briefly and it seems if you want "Enterprise-grade global edge network" you have to contact them for pricing. But yes, we should put it behind some CDN?

Otherwise, https://www.uptrends.com/tools/cdn-performance-check looks ok to me, but maybe there are better tools to check with.

**Comment by glaszig** [comment]
i was able to narrow excessive cpu usage down to when scrolling happens. i'm attaching a profile dump created with fx dev edition 80.0b7 on macOS 10.14.6. hope that helps.

https://silo.glasz.org/netdata-fx-profile.json

i don't think this is a cdn issue:
<img width="281" alt="activity" src="https://user-images.githubusercontent.com/201135/90155737-f4793c00-dd8b-11ea-8a50-f680450fd23b.png">

**Comment by joelhans** [comment]
Thanks for the profile, @glaszig. Looking into this is high on my list of TODOs, although I haven't been able to reproduce it myself either, as I've been out the last few weeks.

@zack-shoylev I've been working on some optimizations in the background, but I haven't really proven that anything is making a huge difference yet. I was playing with fonts first, then was going to try lazy-loading the Swiftype search stuff to see if I can cut a few requests from the initial page load.

But yes, let's chat about this soon. If we can figure out where some optimizations could be made, I can file some issues upstream.

@prologic I say we enable the Cloudflare CDN/proxies. It may not improve the speed scores, but if it improves the user experience, I'm in. The site is still hosted by Netlify. I don't know much about the quality of their service compared to anything else. Maybe there's a better alternative.

**Comment by zack-shoylev** [comment]
Just one more thing @glaszig, do you have GPU (hardware) acceleration enabled in the browser? If it only happens when scrolling this could explain it.

**Comment by glaszig** [comment]
hardware acceleration is off. webgl as well.
<img width="668" alt="perf" src="https://user-images.githubusercontent.com/201135/90163793-dbc25380-dd96-11ea-89d8-0c1eb0bbcfa8.png">
<img width="578" alt="webgl" src="https://user-images.githubusercontent.com/201135/90163825-e7ae1580-dd96-11ea-8f6c-33e826e9fe39.png">

i just noticed, any mouse interaction (hover over links, scrolling) let's cpu usage shoot up. same in safari.
in safari i can see the scroll bar jiggling around (up/down) a little crazy while scrolling.

maybe there's some scrolljacking happening? excessive tracking of mouse events? that is what it "feels like (tm)".

**Comment by zack-shoylev** [comment]
@glaszig The Safari issue is likely separate and has to do with CSS (though I haven't been able to reproduce). We may have to look into it a bit more. It is also likely Safari specific.

The CPU usage spiking is expected with GPU acceleration off, I think. In any browser. Turn it on and give it a try.

**Comment by joelhans** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve performance on PageSpeed/Lighthouse](https://trello.com/c/Kakfaw9E/243-improve-performance-on-pagespeed-lighthouse)

**Comment by prologic** [comment]
> @prologic I say we enable the Cloudflare CDN/proxies. It may not improve the speed scores, but if it improves the user experience, I'm in. The site is still hosted by Netlify. I don't know much about the quality of their service compared to anything else. Maybe there's a better alternative.

Done.
