### ISSUE TITLE
crashed in __strlen_avx2

### ISSUE THREAD

**Issue by wildlee2** [netdata/netdata#9582]
Fedora server 32, netdata installed via dnf. 
Daily updated, started crashing few days back (I can trace the exact start, however every minute restart flooded the log). 

Kernel > 5.7.9-200.fc32.x86_64
netdata >  v1.23.1

Process 26636 (netdata) of user 979 dumped core. Stack trace of thread 26636: #0 0x00007f5e911304f7 __strlen_avx2 (libc.so.6 + 0x1624f7)  systemd-coredump

Process 778 (netdata) crashed in __strlen_avx2() netdata

I smell that strlen_avx2 is problem related to kernel / cpu / -> CPU i5-4460 CPU @ 3.20GHz so maybe I am reporting to wrong site :] If that is the case, sorry about that. 

`Process 1346770 (netdata) of user 979 dumped core.

Stack trace of thread 1346770:
#0  0x00007ff5106f74f7 __strlen_avx2 (libc.so.6 + 0x1624f7)
#1  0x00007ff51060297e __vfprintf_internal (libc.so.6 + 0x6d97e)
#2  0x00007ff5106039bc buffered_vfprintf (libc.so.6 + 0x6e9bc)
#3  0x00007ff510600a24 __vfprintf_internal (libc.so.6 + 0x6ba24)
#4  0x0000564348193889 error_int.constprop.0 (netdata + 0xfa889)
#5  0x00005643480fda80 rrdsetcalc_unlink (netdata + 0x64a80)
#6  0x00005643480fdbef rrdcalc_unlink_and_free (netdata + 0x64bef)
#7  0x00005643480ed560 health_reload_host (netdata + 0x54560)
#8  0x0000564348101798 reload_host_labels (netdata + 0x68798)
#9  0x00005643480a78c2 main (netdata + 0xe8c2)
#10 0x00007ff5105bc042 __libc_start_main (libc.so.6 + 0x27042)
#11 0x00005643480a94ae _start (netdata + 0x104ae)

Stack trace of thread 1346885:
#0  0x00007ff510696c5e epoll_wait (libc.so.6 + 0x101c5e)
#1  0x00007ff510096149 uv__io_poll (libuv.so.1 + 0x24149)
#2  0x00007ff5100853ac uv_run (libuv.so.1 + 0x133ac)
#3  0x0000564348117177 metalog_worker (netdata + 0x7e177)
#4  0x00007ff50ffcc432 start_thread (libpthread.so.0 + 0x9432)
#5  0x00007ff510696913 __clone (libc.so.6 + 0x101913)

Stack trace of thread 1346771:
#0  0x00007ff510696c5e epoll_wait (libc.so.6 + 0x101c5e)
#1  0x00007ff510096149 uv__io_poll (libuv.so.1 + 0x24149)
#2  0x00007ff5100853ac uv_run (libuv.so.1 + 0x133ac)
#3  0x000056434813239d spawn_client (netdata + 0x9939d)
#4  0x00007ff50ffcc432 start_thread (libpthread.so.0 + 0x9432)
#5  0x00007ff510696913 __clone (libc.so.6 + 0x101913)

Stack trace of thread 1346884:
#0  0x00007ff510696c5e epoll_wait (libc.so.6 + 0x101c5e)
#1  0x00007ff510096149 uv__io_poll (libuv.so.1 + 0x24149)
#2  0x00007ff5100853ac uv_run (libuv.so.1 + 0x133ac)
#3  0x000056434810fb13 rrdeng_worker (netdata + 0x76b13)
#4  0x00007ff50ffcc432 start_thread (libpthread.so.0 + 0x9432)
#5  0x00007ff510696913 __clone (libc.so.6 + 0x101913)`

**Comment by mfundul** [comment]
Please update to `v1.23.2`, this bug should have been fixed.

**Comment by wildlee2** [comment]
Since the package is not available yet at dnf,  I have only option to update manually, right? 
Or perhaps I ll just wait till the update lands, not sure how long that might take.

**Comment by mfundul** [comment]
You can try manually [here](https://learn.netdata.cloud/docs/agent/packaging/installer) or try the official packages [here](https://packagecloud.io/netdata/netdata).

**Comment by wildlee2** [comment]
I am just quite lazy to manually install it, and I am not dnf expert, I dont want mess up dnf configs with f32/f31 version mismatch I all just wait.  In the mean time, I just dowgraded to 1.21, seems to work fine, and as this bug is known and fixed, I quess we can close this. 
Thanks for info.
