### ISSUE TITLE
Netdata taking 100% CPU

### ISSUE THREAD

**Issue by aviadcye** [netdata/netdata#9595]
##### Bug report summary
Netdata process is taking 100% CPU (in top).
After the process starts using 100%, using strace gives the below lines in a loop:
```
getrandom("\xfb\x46\xab\xa3\xe1\xb2\x5f\xd3\x2c\xc7\x59\x2f\xd0\x1a\x24\xa2", 16, GRND_NONBLOCK) = 16
getpid()                                = 337222
getuid()                                = 997
getpid()                                = 337222
getppid()                               = 1
gettid()                                = 337222
pread64(168, "\1\7\0", 3, 503563)       = 3
pread64(168, "\221\0\0\0", 4, 503566)   = 4
pread64(168, "CONTEXT 806c4941-b398-4c63-8519-"..., 149, 503570) = 149
pread64(168, "\1\7\0", 3, 503719)       = 3
pread64(168, "\212\0\0\0", 4, 503722)   = 4
pread64(168, "CONTEXT 806c4941-b398-4c63-8519-"..., 142, 503726) = 142
pread64(168, "\1\7\0", 3, 503868)       = 3
pread64(168, "\336\0\0\0", 4, 503871)   = 4
pread64(168, "CONTEXT f420db72-c040-11ea-9d3e-"..., 226, 503875) = 226
access("/dev/random", R_OK)             = 0
getrandom("\x1f\xbe\x54\x47\x0b\x8e\xdb\x6a\x82\x00\xe3\xef\x7e\x9e\x7c\x12", 16, GRND_NONBLOCK) = 16
getpid()                                = 337222
getuid()                                = 997
getpid()                                = 337222
getppid()                               = 1
gettid()                                = 337222
pread64(168, "\1\7\0", 3, 504101)       = 3
pread64(168, "\216\0\0\0", 4, 504104)   = 4
pread64(168, "CONTEXT 1741c90f-7dc3-49cc-8c41-"..., 146, 504108) = 146
pread64(168, "\1\7\0", 3, 504254)       = 3
pread64(168, "\207\0\0\0", 4, 504257)   = 4
pread64(168, "CONTEXT 1741c90f-7dc3-49cc-8c41-"..., 139, 504261) = 139
pread64(168, "\1\7\0", 3, 504400)       = 3
pread64(168, "\220\0\0\0", 4, 504403)   = 4
pread64(168, "CONTEXT 1741c90f-7dc3-49cc-8c41-"..., 148, 504407) = 148
pread64(168, "\1\7\0", 3, 504555)       = 3
pread64(168, "\325\0\0\0", 4, 504558)   = 4
pread64(168, "CONTEXT f420db72-c040-11ea-9d3e-"..., 217, 504562) = 217
access("/dev/random", R_OK)             = 0
getrandom("\x55\xf1\xff\x11\xb6\xb1\xfe\x45\xac\x40\x17\xbc\x43\xe7\x75\x67", 16, GRND_NONBLOCK) = 16
getpid()                                = 337222
getuid()                                = 997
getpid()                                = 337222
getppid()                               = 1
gettid()                                = 337222
pread64(168, "\1\7\0", 3, 504779)       = 3
pread64(168, "\221\0\0\0", 4, 504782)   = 4
pread64(168, "CONTEXT 3fce5cf4-58dc-4dd5-ad58-"..., 149, 504786) = 149
pread64(168, "\1\7\0", 3, 504935)       = 3
pread64(168, "\212\0\0\0", 4, 504938)   = 4
pread64(168, "CONTEXT 3fce5cf4-58dc-4dd5-ad58-"..., 142, 504942) = 142
pread64(168, "\1\7\0", 3, 505084)       = 3
pread64(168, "\325\0\0\0", 4, 505087)   = 4
pread64(168, "CONTEXT f420db72-c040-11ea-9d3e-"..., 217, 505091) = 217
access("/dev/random", R_OK)             = 0
getrandom("\xc5\xda\x60\x8f\x66\x5d\xd9\x4f\x8d\xd8\xd7\x49\x06\xb2\xc3\xb8", 16, GRND_NONBLOCK) = 16
getpid()                                = 337222
getuid()                                = 997
getpid()                                = 337222
getppid()                               = 1
gettid()                                = 337222
pread64(168, "\1\7\0", 3, 505308)       = 3
pread64(168, "\221\0\0\0", 4, 505311)   = 4
pread64(168, "CONTEXT ed6d4312-fc58-4928-b8f1-"..., 149, 505315) = 149
pread64(168, "\1\7\0", 3, 505464)       = 3
pread64(168, "\212\0\0\0", 4, 505467)   = 4
pread64(168, "CONTEXT ed6d4312-fc58-4928-b8f1-"..., 142, 505471) = 142
pread64(168, "\1\7\0", 3, 505613)       = 3
pread64(168, "\325\0\0\0", 4, 505616)   = 4
pread64(168, "CONTEXT f420db72-c040-11ea-9d3e-"..., 217, 505620) = 217
brk(0x55d1192d5000)                     = 0x55d1192d5000
access("/dev/random", R_OK)             = 0
getrandom("\x39\x83\x98\x77\xed\x1d\x86\x0b\x17\x82\xbd\x1b\x06\x13\xb5\x15", 16, GRND_NONBLOCK) = 16
getpid()                                = 337222
getuid()                                = 997
getpid()                                = 337222
getppid()                               = 1
gettid()                                = 337222
```

##### OS / Environment
Not using a container.

```cmd
uname -a; grep -Hv "^#" /etc/*release  # Linux
Linux ip-172-31-6-43 5.4.0-1020-aws #20-Ubuntu SMP Fri Jul 10 05:52:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version
Version: netdata v1.23.2-44-nightly

##### Steps To Reproduce
Actually I don't exactly know... It seems to related to my ansible playbook that installs it, if it's not already installed.

**Comment by aviadcye** [comment]
[nlogs.gz](https://github.com/netdata/netdata/files/4965659/nlogs.gz)
Added logs directory

**Comment by mfundul** [comment]
I would suggest backing up the cache files in `var/cache/netdata` in something like a zip file for future reference. You could send them to me if you don't have any privacy concerns at markos@netdata.cloud

In any case, I believe clearing the cache directory may work around the issue for now:
`rm -rf var/cache/netdata/*`

**Comment by aviadcye** [comment]
What may be in the cache other then metrics?

**Comment by mfundul** [comment]
> 
> 
> What may be in the cache other then metrics?

The corresponding metadata that reside in the `.mlf` files such as:
- dimension names, ids, units
- chart names and properties
- host GUID, domain name, labels

**Comment by aviadcye** [comment]
Cache dir sent

**Comment by aviadcye** [comment]
Cache dir deleted and CPU utilisation did subside.
Thank you for the super prompt response! :)

**Comment by mfundul** [comment]
> 
> 
> Cache dir deleted and CPU utilisation did subside.
> Thank you for the super prompt response! :)

No problem, it's not clear if this is a deadlock situation yet. It may be the case that your agent is producing a lot of metadata that take a long time to process, and would eventually move forward. However, it is a performance issue, especially since you're probably not using all those metadata.

Chances are, you have a lot of ephemeral metrics, which you don't actually need to use after they are gone. Are you using a lot of temporary containers? This is one scenario which would result in blowing up the metadata size. This could be useful for somebody that is interested in looking up the archived metrics, but at this point it's probably not useful for most users.

If your use case is such that creates a lot of metadata you could limit this a little bit by reducing the disk space size of dbengine. If you want to completely avoid archived metrics then you may consider other database [memory modes](https://learn.netdata.cloud/docs/agent/database).

**Comment by aviadcye** [comment]
I don't think that we create "a lot" of temp containers... I'm that sure how many we do, but I think its like 10 tmp ones at most.

**Comment by mfundul** [comment]
> 
> 
> I don't think that we create "a lot" of temp containers... I'm that sure how many we do, but I think its like 10 tmp ones at most.

It's all relative, for instance if you create 10 containers per hour and your database retention history is 10 days then this would be 2400 hosts(containers) times maybe 500 metrics then that would be over 1million metrics worth of metadata.

**Comment by mfundul** [comment]
In your case it was over 400 thousand metrics.

**Comment by aviadcye** [comment]
So every time we deployed, we would compound to the problem... got it 👍

**Comment by mfundul** [comment]
@aviadcye we can work on fixing the overheads long-term but for the short term I'd say you can try a different memory mode (such as `save` instead of `dbengine`) which does not suffer from this problem whatsoever. I'm reopening this to keep track of it as a performance bug.

**Comment by aviadcye** [comment]
actually I wanted to use the dbengine (mainly because it is the new shiny)... should I reconsider?
What is the time table in your opinion?(I can live with deleting the cache for now in the deployment script, if it should be fixed in a month or so)

**Comment by mfundul** [comment]
> 
> 
> actually I wanted to use the dbengine (mainly because it is the new shiny)... should I reconsider?
> What is the time table in your opinion?(I can live with deleting the cache for now in the deployment script, if it should be fixed in a month or so)

`dbengine` does have a lot of advantages, such as much lower RAM utilization, much longer retention period, the ability to change data collection frequency without invalidating previous history. In general, metrics are not deleted with `dbengine`, only rotated due to disk space quota.

In the future there will be more features tied to it. One of which is what affects you, which is the ability to lookup archived metrics. That is metrics that are not currently being collected, or even metrics belonging to streaming child hosts that are offline or were ephemeral.

The truth is that performance hasn't been put in the time table yet, so I don't know if this will happen within a month, but it could and probably should.

Another thing you might want to try is set `dbengine disk space = 64` which could cut down the maximum startup delay considerably.

**Comment by aviadcye** [comment]
thank you, i'll do the limiting for now.

**Comment by Zeblote** [comment]
We've encountered the same issue with netdata suddenly taking up 100% cpu. Though in this case this is a server that doesn't really do anything all day, it just runs a simple perforce service. We're not deploying any containers or anything.

Tried to just leave it for a while but it does not recover. After clearing the cache folder like above, the 100% cpu usage went away.

![image](https://user-images.githubusercontent.com/6764788/88397239-f327a580-cdc3-11ea-8b40-ecfdf4da6533.png)

What's interesting here is the spike just before, which netdata associates with "build". I'm assuming that was a netdata update. Maybe something can go wrong there?

**Comment by mfundul** [comment]
> 
> 
> We've encountered the same issue with netdata suddenly taking up 100% cpu. Though in this case this is a server that doesn't really do anything all day, it just runs a simple perforce service. We're not deploying any containers or anything.
> 
> Tried to just leave it for a while but it does not recover. After clearing the cache folder like above, the 100% cpu usage went away.
> 
> ![image](https://user-images.githubusercontent.com/6764788/88397239-f327a580-cdc3-11ea-8b40-ecfdf4da6533.png)
> 
> What's interesting here is the spike just before, which netdata associates with "build". I'm assuming that was a netdata update. Maybe something can go wrong there?

Yes this should be the netdata update, which cause netdata to restart.

That looks like a different issue, I don't know what happened here, but it's practically impossible for netdata to monitor itself during start-up, which was the case for the original issue reported here. So it's either a second netdata instance being monitor, or netdata itself stuck in a high "system CPU" usage livelock.

Can you share your `var/log/netdata/error.log` files? We'll probably create a separate github issue for this.
