### ISSUE TITLE
EPEL netdata and CloudPackage netdata installation requirements and modules

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#9596]
Hello

When I installed netdata last version from epel release on Centos7 server it works but go plugin is not include :-(
When I installed netdata last version from official repo on Centos7 server it does not work because netdata expect glibc 2.26 whereas it is 2.17 on centos7
When I installed netdata from kickstart.sh it is hanged up (there is a current issue on it) and I need to install lots development tools

How can I install netdata now ! :-( :)

**Comment by jrevillard** [comment]
Same issue for me, I hope that a fix will be available really quickly !
