### ISSUE TITLE
plugin docker_engine does not detect my containers

### ISSUE THREAD

**Issue by omaralitou** [netdata/netdata#9600]
hi,
I configured the docker-engine plugin but I can't find my different containers.
I find that number of container running and we pause but I cannot find the metircs for each container.

thanks

**Comment by ilyam8** [comment]
Hi @omaralitou 

[cgroups](https://github.com/netdata/netdata/tree/master/collectors/cgroups.plugin#cgroupsplugin) plugin detects containers and collects their metrics.

`docker_engine` collects metrics exposes by the engine iteself ([still experiemental](https://docs.docker.com/config/daemon/prometheus/))

> https://github.com/netdata/go.d.plugin/tree/master/modules/docker_engine#charts

**Comment by ilyam8** [comment]
> but I cannot find the metircs for each container.

on the dashboard, each container has its own section on the dashboard menu.

**Comment by omaralitou** [comment]
thanks
