### ISSUE TITLE
Netdata Disk Read and Disk Write + CloudLinux

### ISSUE THREAD

**Issue by pmjcreations** [netdata/netdata#9603]
##### Question summary

Hello Community,

When I installed Netdata before installing CloudLinux OS 8, I can see Disk Read and Disk Write.

But once I converted the OS to CloudLinux, Disk Read and Disk Write aren't visible.

Anyone here using Netdata on a CloudLinux server that could see Disk Read and Disk Write?

##### OS / Environment

CloudLinux OS 8

##### Component Name

Disk Read and Disk Write

##### Expected results

Disk Read and Disk Write must be visible like the demo https://london.my-netdata.io/

But my Netdata dashboard isn't showing them
![chrome_c4pFxib8tu](https://user-images.githubusercontent.com/7301824/88449472-c6779a80-ce64-11ea-9b7b-81db6705a9a3.png)

**Comment by vlvkobal** [comment]
Check if you have access to `/proc/diskstats`. Are there any errors for diskstats module in `error.log`?

**Comment by pmjcreations** [comment]
Hi @vlvkobal,

`/proc/diskstats` says `-bash: /proc/diskstats: Permission denied`

This file has 444 (read-only) permission.

Would that the reason? If yes, what is the permission level that I need to make?

**Comment by vlvkobal** [comment]
@Ferroin do you have any ideas why `/proc/diskstats` can't be read?

**Comment by mfundul** [comment]
> 
> 
> @Ferroin do you have any ideas why `/proc/diskstats` can't be read?

@vlvkobal I think @pmjcreations just ran the command `/proc/diskstats` and since the file is not an executable the output you get is `Permission denied`. The command you were looking for was probably `ls -l /proc/diskstats`.

**Comment by vlvkobal** [comment]
Thank you @mfundul! My bad, I didn't read the message carefully. @pmjcreations please do `grep diskstats /var/log/netdata/error.log`. Do you see any errors?

**Comment by pmjcreations** [comment]
Hi @vlvkobal,

netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot open file '/proc/diskstats' (errno 1, Operation not permitted)

**Comment by vlvkobal** [comment]
A hint kindly provided by @ilyam8 
https://blog.cloudlinux.com/kernel-and-kernel-module-for-cloudlinux-8-and-cloudlinux-7-hybrid-updated

@pmjcreations could you check if this helps?

**Comment by pmjcreations** [comment]
@vlvkobal, my instance is created after CloudLinux fixed that issue.

And I checked both dependencies.

Here are the versions:

My Kernal version is `4.18.0-147.8.1.el8.lve.x86_64` and kmod-lve version is `kmod-lve-2.0-16.el8.x86_64`.

**Comment by vlvkobal** [comment]
@Ferroin @prologic any thoughts on the matter?

**Comment by prologic** [comment]
> @Ferroin @prologic any thoughts on the matter?

Just about to read this... Give me an hour or so.

**Comment by prologic** [comment]
So basically if I'mr eading this right:

```
Cannot open file '/proc/diskstats' (errno 1, Operation not permitted)
```

This is the underlying problem?

This is `EPERM` (_different to `EACCESS`_) and I have a suspicion this _might_ have something to do with an LSM (_Linux Security Module_) such as ArpAmor or SELinux. 🤔

**Comment by prologic** [comment]
Some Q(s):


- Are you `root` when you try to run `ls -l /proc/diskstats`?
- What are the attributes on the `/proc` path? Run: `lsattr /proc`
- What are the mount options on the `/proc` mountpoiunt? Run: `mounts | grep proc`

Can you share the output of these? Thanks!

**Comment by pmjcreations** [comment]
Hi @prologic,

- Yes, I was the root

- I see many lines like this:
`lsattr: Inappropriate ioctl for device While reading flags on /proc/fb`

And a few like:
`lsattr: Operation not supported While reading flags on /proc/mounts`

Do you want me to add every line here?

- mounts | grep proc says:
`-bash: mounts: command not found`

**Comment by pmjcreations** [comment]
mount | grep proc says:

```
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime,gid=1006,hidepid=2)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15803)
proc on /usr/share/cagefs-skeleton/proc type proc (rw,nosuid,relatime,gid=1006,hidepid=2)
systemd-1 on /usr/share/cagefs-skeleton/proc/sys/fs/binfmt_misc type autofs (rw,nosuid,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15803)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
```

**Comment by prologic** [comment]
@pmjcreations  Thanks!

One last thing; Do you have SELinux enabled on this box?

**Comment by pmjcreations** [comment]
Nope, @prologic 

`SELinux status:                 disabled`

**Comment by prologic** [comment]
@pmjcreations I'm sort of stumped in that case :/ Are you willing to grant me remote access to the box in question if I hand you my public ssh key?

**Comment by pmjcreations** [comment]
I get that working now, @prologic.

I had to add `netdata` to `clsupergid` group.

Then a Netdata restart solved my issue.

![KotAGlAOva](https://user-images.githubusercontent.com/7301824/89009443-2f11bc00-d32a-11ea-8d8d-06049a0a36d5.png)

**Comment by dogsbody-josh** [comment]
We're experiencing this issue as we test the rollout of netdata. We're also testing on CloudLinux 8 and this issue is likely due to [CageFS limiting access](https://docs.cloudlinux.com/shared/cloudlinux_os_components/#general-information-and-requirements-2) to `/proc`. 

I wonder if Netdata has any existing advice on handling usage on such a system with CageFS enabled?

**Comment by ilyam8** [comment]
@dogsbody-josh I don't think we have, but common sense tells me you either accept that you have a limited view (majority of system metrics come from `/proc`) or disable CageFS for the `netdata` user. I think it's better to ask on CloudLinux/CageFS forums. It would be very nice if you shared their response/your solution here.

**Comment by dansleboby** [comment]
@dogsbody-josh 

> **⚠️ Warning:** This tutorial is provided **as‑is**, with no guarantees. Use at your own risk. I’m not responsible for any damage or data loss.

Run the following as `root`

 1. Check if `/proc` is hidden from non‑root
```shell
> mount | grep ' on /proc '
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime,gid=1000,hidepid=invisible)
```
If you see `hidepid=invisible` (or `hidepid=2`), that means non‑root users are blocked. The line will also show `gid=1000`, meaning group 1000 can still see it.

2. Identify the group name for GID 1000
```shell
> getent group 1000
clsupergid:x:1000:polkitd,mailman,netdata
# e.g. clsupergid
```

3. Add the `netdata` user to that group
```shell
> usermod -aG clsupergid netdata
```

4. Remount /proc
```shell
> mount -o remount /proc
```

5. Verify access
```shell
> sudo -u netdata cat /proc/diskstats
```

6. Restart netdata 
```
> systemctl restart netdata
```

Tested on:
```shell
> uname -r
5.14.0-362.18.1.el9_3.x86_64

> cat /etc/os-release
NAME="CloudLinux"
VERSION="9.5 (Vyacheslav Zudov)"
ID="cloudlinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CloudLinux 9.5 (Vyacheslav Zudov)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:cloudlinux:cloudlinux:9::baseos"
HOME_URL="https://www.cloudlinux.com"
DOCUMENTATION_URL="https://docs.cloudlinux.com"
BUG_REPORT_URL="https://cloudlinux.zendesk.com"
REDHAT_SUPPORT_PRODUCT="CloudLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.5"
```
