### ISSUE TITLE
insufficient handling of gearman function name

### ISSUE THREAD

**Issue by bokutin** [netdata/netdata#9604]
Hello,

##### Bug report summary

The function name of gearadmin --status may include spaces, tabs, /, | or ^M etc.

in https://github.com/netdata/netdata/blob/f75eb6674800063b9f53763c2db32c4eeaf7994e/collectors/python.d.plugin/gearman/gearman.chart.py#L141 , it does not have any such assumption.

##### OS / Environment

```
FreeBSD hostXX 12.1-RELEASE-p2 FreeBSD 12.1-RELEASE-p2 GENERIC  amd64
pkg install netdata-1.23.1
```

##### Netdata version

 
netdata v1.23.1

##### Component Name

python.d/gearman.chart.py

##### Steps To Reproduce

1. gearman -w -f "prefix1 func1"

##### Expected behavior

When I access http://localhost:19999/ , I get ERROR 405: Cannot download charts index from server: http://localhost:19999/api/v1/charts .

---

I solved it as follows, but it doesn't seem like good code.

```
# diff -u /usr/local/libexec/netdata/python.d/gearman.chart.py-00 /usr/local/libexec/netdata/python.d/gearman.chart.py
--- /usr/local/libexec/netdata/python.d/gearman.chart.py-00     2020-07-25 12:00:19.000000000 +0900
+++ /usr/local/libexec/netdata/python.d/gearman.chart.py        2020-07-25 14:37:03.872963000 +0900
@@ -4,6 +4,9 @@
 
 # Gearman Netdata Plugin
 
+import re
+import urllib.parse
+
 from copy import deepcopy
 
 from bases.FrameworkServices.SocketService import SocketService
@@ -138,9 +141,13 @@
             raise GearmanReadException()
 
         job_lines = raw.splitlines()[:-1]
-        job_lines = [job.split() for job in sorted(job_lines)]
+        #job_lines = [job.split() for job in sorted(job_lines)]
+        job_lines = [job.rsplit(maxsplit=3) for job in sorted(job_lines)]
 
         for line in job_lines:
+            #line[0]  = line[0].replace("\t", '-')   # If it is tab, it works
+            #line[0]  = re.escape(line[0])           # not works
+            line[0]  = urllib.parse.quote(line[0])  # It works, but it's dirty. Especially for UTF8.
             line[1:] = map(int, line[1:])
 
         return job_lines
```

Inserting a separator such as tab in the function name is done as follows.
https://metacpan.org/pod/Gearman::Client#Gearman::Client-%3Enew(%options) prefix option

Thanks,

**Comment by ilyam8** [comment]
hi, can you show `gearadmin --status` output?

**Comment by bokutin** [comment]
Hi, thank you for having interest.

```
# gearadmin --status
prefix1	fetch_data	0	0	80
prefix1	sync_data	0	0	40
aaあほ\n aa	0	0	0
aaあほ/a2	0	0	0
prefix1	dispatch_data	0	0	40
aaあほ\n
 aa2	0	0	0
prefix1	say_hello	0	0	40
aaあほ|\n
 aa2	0	0	0
aa aa	0	0	0
prefix1/func1	0	0	0
aaあほ aa	0	0	0
aaあほ\n
 aa	0	0	0
prefix1 func1	0	0	0
prefix1| \t\n
func1	0	0	0
.
```

I did an experiment as shown below to find out what value a function name can have, so it is dirty.
gearman -w -f "prefix1| \t\n^Mfunc1"
gearman -w -f "aaあほ\n aa"
etc ...

**Comment by ilyam8** [comment]
```
aaあほ|\n
 aa2	0	0	0
```

so we need to join `aaあほ|` and ` aa2`? Is `aaあほ|aa2` ok? (no spaces)

If so perhaps something like this will do

```python
output = """
prefix1	fetch_data	0	0	80
prefix1	sync_data	0	0	40
aaあほ\n aa	0	0	0
aaあほ/a2	0	0	0
prefix1	dispatch_data	0	0	40
aaあほ\n
 aa2	0	0	0
prefix1	say_hello	0	0	40
aaあほ|\n
 aa2	0	0	0
aa aa	0	0	0
prefix1/func1	0	0	0
aaあほ aa	0	0	0
aaあほ\n
 aa	0	0	0
prefix1 func1	0	0	0
prefix1| \t\n
func1	0	0	0
.
"""


def get_worker_data():
    jobs, current_job = list(), list()

    for line in output.splitlines()[:-1]:
        words = line.split()
        if len(words) == 0:
            continue

        current_job.extend(words)

        try:
            name = ''.join(current_job[:-3])
            values = [int(w) for w in current_job[-3:]]
        except (IndexError, ValueError):
            continue

        current_job = list()
        job = [name]
        job.extend(values)
        jobs.append(job)

    return jobs


for wd in get_worker_data():
    print(wd)

```

Result:

```cmd
0 playground $ python3 play.py 
['prefix1fetch_data', 0, 0, 80]
['prefix1sync_data', 0, 0, 40]
['aaあほaa', 0, 0, 0]
['aaあほ/a2', 0, 0, 0]
['prefix1dispatch_data', 0, 0, 40]
['aaあほaa2', 0, 0, 0]
['prefix1say_hello', 0, 0, 40]
['aaあほ|aa2', 0, 0, 0]
['aaaa', 0, 0, 0]
['prefix1/func1', 0, 0, 0]
['aaあほaa', 0, 0, 0]
['aaあほaa', 0, 0, 0]
['prefix1func1', 0, 0, 0]
['prefix1|func1', 0, 0, 0]
```

**Comment by bokutin** [comment]
I did a little more research.

I think it's faster to have a look at the test script.

```
#!/usr/local/bin/perl

use rlib;
use Modern::Perl;
use Data::Dumper;
use Gearman::Client;
use Gearman::Worker;
use JSON::MaybeXS;
use URI::Escape;

my $bin = "\xFF"; # binary, not ascii

my $worker = Gearman::Worker->new;
$worker->job_servers( '127.0.0.1' );

$worker->register_function( "func1\t<-tab",               sub {}) or die;
$worker->register_function( "func1\x0a<-LF",              sub {}) or die;
$worker->register_function( "func1\x0d\x0a<-CR_LF",       sub {}) or die;
$worker->register_function( "func1 <-space",              sub {}) or die;
$worker->register_function( "func1$bin<-binary_or_empty", sub {}) or die;
$worker->register_function( "func1<-binary_or_empty",     sub {}) or die;

my $client = Gearman::Client->new;
$client->job_servers( '127.0.0.1' );

my $text = "";
$client->_job_server_status_command( # same as "echo status | nc 127.0.0.1 4730"
    "status\n",
    sub {
        my ($js, $line) = @_;
        $text .= $line."\n";
    },
);

my @func;
push @func, { job => $1, queued => $2, running => $3, capable => $4 }
    while $text =~ m{^(.*?)\t(\d+)\t(\d+)\t(\d+)$}msg;
$_->{job_hex} = uri_escape $_->{job} for @func;
@func = sort { $a->{job_hex} cmp $b->{job_hex} } @func;

say JSON::MaybeXS->new->canonical->pretty->encode( \@func );

__END__

% ./test.pl | cat -v
[
   {
      "capable" : "1",
      "job" : "func1\t<-tab",
      "job_hex" : "func1%09%3C-tab",
      "queued" : "0",
      "running" : "0"
   },
   {
      "capable" : "1",
      "job" : "func1\n<-LF",
      "job_hex" : "func1%0A%3C-LF",
      "queued" : "0",
      "running" : "0"
   },
   {
      "capable" : "1",
      "job" : "func1\r\n<-CR_LF",
      "job_hex" : "func1%0D%0A%3C-CR_LF",
      "queued" : "0",
      "running" : "0"
   },
   {
      "capable" : "1",
      "job" : "func1 <-space",
      "job_hex" : "func1%20%3C-space",
      "queued" : "0",
      "running" : "0"
   },
   {
      "capable" : "1",
      "job" : "func1<-binary_or_empty",
      "job_hex" : "func1%3C-binary_or_empty",
      "queued" : "0",
      "running" : "0"
   },
   {
      "capable" : "1",
      "job" : "func1M-^?<-binary_or_empty",
      "job_hex" : "func1%FF%3C-binary_or_empty",
      "queued" : "0",
      "running" : "0"
   }
]
```

It seems that any value can be used as the function name.

According to JOB_ASSIGN of http://gearman.org/protocol/ , it seems to be a constraint only for "NULL byte terminated function name".

I tried the following two as if they were dependent on the server implementation, but the behavior was the same.
https://www.freshports.org/devel/gearmand
https://www.freshports.org/devel/p5-Gearman-Server

I'm sorry that I found it troublesome.

**Comment by bokutin** [comment]
It seems impossible to write a complete parser for the "status" output by gearman spec.

The function name can take any value except \0.
(Even line breaks and binaries)

I tried netdata to figure out the state of gearman.
But now I wrote what I want to record in rrd.
I also needed a history like this: https://github.com/netdata/netdata/issues/3235
However, munin's 5 minute resolution is unacceptable, so I set the resolution to 3 seconds and history to 7 days.

The word "あほ" used above is not suitable for committing. In that case, avoid using it.

Although a complete parser cannot be written in the specification, if you want to improve it so that it will work even if the function name includes tabs or spaces, the test data shown below is fine.

```
output = """
func1	1	2	3
myapp1 func1	3	4	5
myapp1	func1	6	7	8
myapp1/func1	9	10	11
<script>alert('Hi!')</script>	12	13	14
 func1	15	16	17
.
"""
```

It may be unsuitable to use it for screen display without converting the function name.

The reason comes from the gearman specification.

**Comment by ilyam8** [comment]
> It seems impossible to write a complete parser for the "status" output by gearman spec.

@bokutin i understand the problem, i think it is ok to **ignore all those edge cases** (`Even line breaks and binaries`).

But we need to handle prefixes:

```cmd
func1	1	2	3
myapp1 func1	3	4	5
```

right?

**Comment by bokutin** [comment]
It depends on how far you want the edge case to be, but in my case prefix_separator defaults to tab, so yes.
https://metacpan.org/pod/Gearman::Objects#prefix_separator([$separator]) default tab

```
func1	1	2	3
myapp1<tab(hex09) not space(hex20)>func1	3	4	5
```

**Comment by ilyam8** [comment]
>  but in my case prefix_separator defaults to tab

I think we need to handle thix case: prefix and any space as a separators.
