### ISSUE TITLE
Fails to create UNIX socket with error "errno 30, Read-only file system"

### ISSUE THREAD

**Issue by Hubro** [netdata/netdata#9606]
##### Bug report summary

Fails to create UNIX socket with the error: "errno 30, Read-only file system"

##### OS / Environment

```
Linux server 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

netdata v1.12.0

##### Component Name

web

##### Steps To Reproduce

Clean install on Debian 10:

    sudo apt-get install netdata

Use this `netdata.conf`:

```
[global]
        run as user = netdata
        web files owner = root
        web files group = root
        # Netdata is not designed to be exposed to potentially hostile
        # networks. See https://github.com/netdata/netdata/issues/164
        bind socket to IP = 127.0.0.1

[web]
        bind to = unix:/run/netdata/netdata.sock tcp:127.0.0.1:19999
```

Restart netdata:

    sudo systemctl restart netdata

Check output:

    journalctl _SYSTEMD_UNIT=netdata.service

<pre>
Jul 25 14:50:43 nebula netdata[10841]: LISTENER: failed to remove existing (probably obsolete or left-over) file on UNIX socket path '/run/netdata/netdata.sock'.
Jul 25 14:50:43 nebula netdata[10841]: LISTENER: UNIX bind() on path '/run/netdata/netdata.sock' failed.
Jul 25 14:50:43 nebula netdata[10841]: 2020-07-25 14:50:43: netdata ERROR : MAIN : LISTENER: failed to remove existing (probably obsolete or left-over) file on UNIX socket path '/run/netdata/netdata.sock'. (errno 30, Read-only file system)
Jul 25 14:50:43 nebula netdata[10841]: 2020-07-25 14:50:43: netdata ERROR : MAIN : LISTENER: UNIX bind() on path '/run/netdata/netdata.sock' failed. (errno 30, Read-only file system)
Jul 25 14:50:43 nebula netdata[10841]: 2020-07-25 14:50:43: netdata ERROR : MAIN : LISTENER: Cannot create unix socket '/run/netdata/netdata.sock'
Jul 25 14:50:43 nebula netdata[10841]: 2020-07-25 14:50:43: netdata INFO  : MAIN : LISTENER: Listen socket tcp:127.0.0.1:19999 opened successfully.
Jul 25 14:50:43 nebula netdata[10841]: LISTENER: Cannot create unix socket '/run/netdata/netdata.sock'
Jul 25 14:50:43 nebula netdata[10841]: LISTENER: Listen socket tcp:127.0.0.1:19999 opened successfully.
</pre>

The `netdata` user has write access to the directory:

<pre>
$ ls -lah /run/netdata 
total 0
drwxr-xr-x  2 netdata netdata  40 Jul 25 14:57 .
drwxr-xr-x 23 root    root    780 Jul 25 14:40 ..
</pre>

I have confirmed this by writing a file as the `netdata` user:

<pre>
$ sudo -u netdata touch /run/netdata/test.txt
$ ls -lh /run/netdata 
total 0
-rw-r--r-- 1 netdata netdata 0 Jul 25 15:05 test.txt
</pre>

Why does netdata think this is a read-only file system? Is it running in a chroot jail by default on Debian?

##### Expected behavior

I expected netdata to successfully open a UNIX socket at the specified path.

**Comment by Hubro** [comment]
I figured it out, it was due to these lines in the systemd service file:

```
# Hardening

NoNewPrivileges=false
PermissionsStartOnly=true
# CAP_SETGID is required for setgroups()
# CAP_NET_RAW is needed by fping, see #864370
CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_SYS_PTRACE CAP_SETGID CAP_SETUID CAP_NET_RAW
PrivateTmp=true
ProtectHome=read-only
ProtectSystem=full

ReadOnlyDirectories=/
ReadWriteDirectories=/proc/self
ReadWriteDirectories=/var
```

I fixed it by overriding the service file:

    sudo EDITOR=vim systemctl edit netdata.service

With this config:

```
[Service]
ReadWriteDirectories=/run/netdata
```

So this was not a bug in netdata.

**Comment by Ferroin** [comment]
Reopening this because it is, IMO, a bug (we're the ones who ship the systemd unit files, so it's a bug in the unit file but not Netdata itself).

**Comment by prologic** [comment]
@Ferroin Do you have a PR for this already? It seems to be in Review?

**Comment by Ferroin** [comment]
@Hubro This should be fixed in tonight's nightly (by whitelisting `/run/netdata` in the systemd sandboxing).
