### ISSUE TITLE
name  measurements  changes

### ISSUE THREAD

**Issue by omaralitou** [netdata/netdata#9609]
hi,
I configured netdata backends with influxdb and I enabled the Cgroups plugin to collect metrics from my containers and it works fine and netdata creates measurements with a prefix_name of container_name metric.

but the problem that I have when I restart my containers the id and the name of the container change and netdata creates new measurements with new name and it is not normal because I have to make performance predections but each time times the name of the measures changes.

- how to manage measurement names with netdata.

thanks

**Comment by vlvkobal** [comment]
> when I restart my containers the id and the name of the container change

Do you mean that you are creating new containers? Names and IDs don't change on stop/start.

Can't you use the [`--name` option](https://docs.docker.com/engine/reference/run/#name---name) to make container names persistent?
