### ISSUE TITLE
Netdata export alarms [Resolved]

### ISSUE THREAD

**Issue by Abjorge95** [netdata/netdata#9612]
Greetings,

I have been looking on Wiki and on Github for a way to export the alarms that are generated by Netdata, this could be for example by http url json or something like that when ever a new alarms is generated or an old one is cleared, this because i built a custom alarm monitoring platform for a project and would like to include all the hardware / OS alarms from Netdata.

Is this possible? Is this a feature that i can't manage to find? Or we are only able to export metrics / graphs data?

Best regards.

**Comment by thiagoftsm** [comment]
Hi @Abjorge95 ,

You can do the following request to Netdata:

`curl http://YOUR_IP:19999/api/v1/alarms?active`

To get the current active alarms, you can also request

`curl http://YOUR_IP:19999/api/v1/alarms?all`

to see all alarms.
Finally you can get the alarm log list using:

```
curl http://YOUR_IP:19999/api/v1/alarm_log
```

All requests will return to you a JSON output.

Best regards!

**Comment by Abjorge95** [comment]
Greetings,

This is great, didn't know, thank you very much for the reply :)
This is exactly what i was looking for!

Kindest regards.

**Comment by thiagoftsm** [comment]
I am glad I could help you. :)
I am closing this question now, but be free to reopen if you need another help in this direction.

Best regards!
