### ISSUE TITLE
Ubuntu 18.04: "This agent was built without the dependencies for Cloud and cannot be claimed" even on updated machines

### ISSUE THREAD

**Issue by jcormier** [netdata/netdata#9615]
##### Bug report summary
Servers which were installed using kickstart script and have auto update on, are not being built for cloud

Trying to run kickstart script again reports no update needed.

 ```
$ bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel --dont-wait --auto-update
 --- Found existing install of Netdata under: / ---
 --- Attempting to update existing install instead of creating a new one ---
[/home/jcormier]$ sudo //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron [sudo] password for jcormier:
Mon Jul 27 20:13:45 UTC 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Mon Jul 27 20:13:45 UTC 2020 : INFO:  Current Version: 001023002067
Mon Jul 27 20:13:45 UTC 2020 : INFO:  Latest Version: 001023002067
Mon Jul 27 20:13:45 UTC 2020 : INFO:  Newest version (current=001023002067 >= latest=001023002067) is already installed
 OK

 --- Updated existing install at /usr/sbin/netdata ---
$ sudo netdata-claim.sh -token=... -url=https://app.netdata.cloud
This agent was built without the dependencies for Cloud and cannot be claimed
```

##### OS / Environment

```
Linux albert 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
and
Linux userv1 4.18.0-13-generic #14~18.04.1-Ubuntu SMP Thu Dec 6 14:09:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:VERSION="18.04.2 LTS (Bionic Beaver)"
```

##### Netdata version

 # netdata -V
netdata v1.23.2-67-nightly

##### Component Name
cloud

##### Expected behavior
Short of uninstalling and then reinstalling there doesn't appear to be a way to get the updater to build the new cloud support.  I'd like to not have to uninstall then reinstall netdata on all my machines.  And risk losing any conf changes in /etc/netdata

**Comment by jcormier** [comment]
Ran the install-required-packages script to see what packages I might be missing that are new since netdata was first installed.

```
 $ bash <(curl -sSL https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh) -i metadata
...
The following NEW packages will be installed:
  autogen autogen-doc cmake cmake-data libarchive13 libelf-dev libjson-c-dev libjsoncpp1 libopts25-dev librhash0 netcat netcat-traditional python3-bson
  python3-bson-ext python3-gridfs python3-pymongo python3-pymongo-ext
The following packages will be upgraded:
  libuuid1 uuid-dev
```

If I install these is there a way to force the updater to rebuild?

**Comment by Ferroin** [comment]
> Ran the install-required-packages script to see what packages I might be missing that are new since netdata was first installed.
> 
> ```
>  $ bash <(curl -sSL https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh) -i metadata
> ...
> The following NEW packages will be installed:
>   autogen autogen-doc cmake cmake-data libarchive13 libelf-dev libjson-c-dev libjsoncpp1 libopts25-dev librhash0 netcat netcat-traditional python3-bson
>   python3-bson-ext python3-gridfs python3-pymongo python3-pymongo-ext
> The following packages will be upgraded:
>   libuuid1 uuid-dev
> ```
> 
> If I install these is there a way to force the updater to rebuild?

Actually, if you install those now, the next auto-update should automatically build cloud support (it doesn't try to pull in new dependencies, but builds based off of what's actually on the system. The only two out of that list that should actually be needed are `cmake` and `libjson-c-dev`, plus their dependencies.

**Comment by jcormier** [comment]
Yeah that worked.  Just wish I didn't have to wait a full day to run the netdata-claim script, guess its time to use the at command...
