### ISSUE TITLE
Netdata Community now available

### ISSUE THREAD

**Issue by zack-shoylev** [netdata/netdata#9616]
Hi all,

We've launched a [message board](https://community.netdata.cloud) for Netdata. You will be able to find many of us there. Registration is via email, Github, or Google, and we'll likely integrate it with Cloud at some point.

We are using the open-source [NodeBB](https://nodebb.org) project with a [Netdata theme](https://github.com/netdata/nodebb-theme-persona-netdata); pull requests welcome. The software has good Github integrations available.

We also published a blog post with a lot [more details](https://www.netdata.cloud/blog/the-netdata-community/).

**Comment by Steve8291** [comment]
Don't know if anyone else is experiencing this but I can't register for the message board. Both Firefox and Safari fail when trying to answer the captcha. Firefox never shows the challenge pics and Safari accepts the answer, green check in box, and then gives the same message as Firefox after clicking "Register Now"

>  Registration Error
> Captcha not verified, are you a robot?

**Comment by zack-shoylev** [comment]
I am not aware of others with the same issue, but I will look into it!

**Comment by zack-shoylev** [comment]
@Steve8291 I did a few tests and I ran into some issues with reCaptcha... sometimes. I switched the captcha to hCaptcha and that seems to work better.. Let me know if that helps.

**Comment by Steve8291** [comment]
Worked great. Thanks.
