### ISSUE TITLE
Netdata, slack notification only work for test scripts

### ISSUE THREAD

**Issue by seagel** [netdata/netdata#9617]
Hello,

I am using netdata installed on macos (High Sierra).
I have configured slack in the config file (health_alarm_notify.conf).

While testing is manually as in through test scripts it seems to work but not the other way.

Here is my config file : 
`
SEND_SLACK="YES"
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/****/***"
DEFAULT_RECIPIENT_SLACK="channel_name"
`
I am using stress-ng to put load on my machine and alarms are triggered and shown in the dashboard and also browser notifications are shown but nothing in slack.

I am not able to figure out what is the issue ?

**Comment by ilyam8** [comment]
Hi, did you check `error.log`?

Do you have [`delay`](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) option in your alarms?

**Comment by seagel** [comment]
`template: 10min_cpu_usage
      on: system.cpu
      os: *
   hosts: *
  lookup: average -1m unaligned of user,system,softirq,irq,guest
   units: %
   every: 1m
    warn: $this > (($status >= $WARNING)  ? (15) : (25))
    crit: $this > (($status == $CRITICAL) ? (15) : (25))
    delay: down 1m up 1m
    info: average cpu utilization for the last 10 minutes (excluding iowait, nice and steal)
      to: sysadmin`
This is the alarm config I'm using.

I checked my brew - netdata logs but found nothing there.

**Comment by cakrit** [comment]
Please run `grep alarm-notify /var/log/netdata/error.log` and post here what you see, when your alarms change state.

**Comment by thiagoftsm** [comment]
Hi @seagel ,

Yesterday the `stale[bot]` called attention that there are not more iterations in this issue, could you solve your problem with Slack?

Best regards!

**Comment by ilyam8** [comment]
> delay: down 1m up 1m

> up 1m

Delay could be the reason.

**Comment by ilyam8** [comment]
closing due to incactivity

**Comment by quaint-engineer** [comment]
I faced the same issue on my macOS setup. The issue was that the `alarm-notify.sh` script was still the system's bash `/bin/bash` rather than `/usr/local/bin/bash`.

My work around was to edit the file's interpreter directive

```
#!/usr/local/bin/bash
#shellcheck source=/dev/null disable=SC2086,SC2154

# netdata
# real-time performance and health monitoring, done right!
# (C) 2017 Costa Tsaousis <costa@tsaousis.gr>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Script to send alarm notifications for netdata
```

/usr/local/Cellar/netdata/1.26.0/libexec/netdata/plugins.d/alarm-notify.sh

I hope this helps.
