### ISSUE TITLE
duplicated uuid seems to be recognized as same server (cloud)

### ISSUE THREAD

**Issue by ktjd123** [netdata/netdata#9618]
##### Feature idea summary

Saved AWS EC2 instance as ami and started another instance with it.

Then netdata cloud seems to recognize as same instance . even I changed netdata name.

##### Expected behavior

recognize as different instance.

**Comment by underhood** [comment]
You can claim the second node with different ID as following:
`sudo netdata-claim.sh -token=TOKEN -rooms=ROOM1,ROOM2 -url=https://app.netdata.cloud -id=$(uuidgen)`

Even better you can generate new UUID for the node by deleting `/var/lib/netdata/registry/netdata.public.unique.id` - Agent will generate new ID on next start up. Then claim the node.

**Comment by ktjd123** [comment]
@underhood thank you for solution
