### ISSUE TITLE
[netdata.spec] rpm package has bad default permissions 4750 to all files in /usr/libexec/netdata

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#9620]
##### Bug report summary

In PR #6369 the line  `%defattr(4750,root,netdata,0750)` around [457](https://github.com/netdata/netdata/blame/master/netdata.spec.in#L457) introduced by  2c3b4cd set the setuid bit by default for all files in `/usr/libexec/netdata`. 

This is not critical per se, as :
- scripts doesn't honor the setuid bit
- external binaries in `plugind.d` are external because they need the setuid bit
- users need to be in group `netdata` to execute the setuid binaries

But it needs to be cleaned nonetheless.

##### OS / Environment

OS: RHEL6, 7, 8

##### Netdata version
On all rpm packages created by `contrib/rhel/build-netdata-rpm.sh` since v1.16 

##### Component Name
`/netdata.spec.in`

##### Steps To Reproduce
```
git clone https://github.com/netdata/netdata.git
cd netdata
./contrib/rhel/build-netdata-rpm.sh
rpm -qvlp ~/rpmbuild/RPMS/x86_64/netdata-*.rpm | grep /usr/libexec/netdata 
```

You'll see the user permissions are `-rwsr-x---` (user exec is 's' for setuid) instead of `-rwxr-x---`

##### Expected behavior
Only explicitely set required binary setuid, not all.

**Comment by prologic** [comment]
Thanks @Saruspete !
