### ISSUE TITLE
multiple prometheus reading metrics from the netdata cause problem

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9625]
##### Bug report summary

We have two Prometheis servers with exact same  configurations, one of the jobs on these servers is to read metrics from our parent netdata servers. the problem is, apparently some time one of the prometheis cannot read the metrics from some parents correctly, e.g. we have this output on one of our prometheus servers:

![image](https://user-images.githubusercontent.com/7656049/88798225-d1f6f880-d1b9-11ea-8f89-05196bafa385.png)

But the other one showing the consistent data:
![image](https://user-images.githubusercontent.com/7656049/88798548-4b8ee680-d1ba-11ea-8ca6-73948c7f5ae7.png)

I checked the prometheis and they don't reach timeout, in fact, they read metrics in less than 4 seconds and the timeout is 90 seconds

##### OS / Environment

```
4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 1.23.0

##### Expected behavior

Both prometheis should have almost the same data

**Comment by mfundul** [comment]
Since `v1.23.0` has some well known bugs can you upgrade to `v.1.23.2` to be sure if this is a new issue?

**Comment by amoss** [comment]
Hi,

We've having some trouble trying to work out what might be happening in this scenario. The lack of metrics could have several different causes, for example a network problem or a problem servicing the request because the CPU is saturated.

* Can we start by comparing the chart on the Netdata node with the two Prometheus charts?
* What does a `/api/v1/data?` query show on the chart for that time-range, i.e. do the dips in the charts occur in the json format or only when pulling the metrics in Prometheus format?

**Comment by cakrit** [comment]
No response since August. Closing, please comment so we can reopen, if you still have an issue with the latest version.
