### ISSUE TITLE
Installer and updater should sanely handle `/tmp` being mounted with `noexec`.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#9626]
Currently we require a usable `/tmp` that is not mounted with `noexec` for our install, which causes otherwise sanely configured system to not work correctly.

Based on discussion between myself and @prologic, the plan is to update our installation and update tooling to fall back to `$PWD` if `/tmp` is mounted with `noexec` so that such systems work properly (or at least so that fewer of them fail).

**Comment by prologic** [comment]
Thanks @Ferroin
