### ISSUE TITLE
Samba monitoring stopped working after update

### ISSUE THREAD

**Issue by camjesus2** [netdata/netdata#9640]
Hi all!
Running netdata (v1.23.2-91-nightly) on Debian Buster (Linux EHFS 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux)

After a recent (around July 20th) netdata update, SAMBA monitoring stopped working.
When I start netdata, the log shows 
```
2020-07-31 13:54:11: python.d INFO: plugin[main] : [samba] built 1 job(s) configs
2020-07-31 13:54:11: python.d ERROR: samba[samba] : not allowed to run sudo for command '/usr/local/samba/bin/smbstatus -P'
2020-07-31 13:54:11: python.d INFO: plugin[main] : samba[samba] : check failed
```

However, running `su -s /bin/bash netdata` as netdata returns `/usr/local/samba/bin/smbstatus -P
`
Running `sudo -n smbstatus -P` as netdata works as expected

any clues?

Best regards,
Carlos

**Comment by ilyam8** [comment]
Hi @camjesus2 

Show the output the following commond

> sudo -n -l /usr/local/samba/bin/smbstatus -P

**Comment by camjesus2** [comment]
hi @ilyam8,
I've made a mistake on my post. 
Running  `sudo -n -l smbstatus -P` as netdata returns `/usr/local/samba/bin/smbstatus -P`

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/blob/cfd74bbb406fc118d58016f659fcab4a96de1da7/collectors/python.d.plugin/samba/samba.chart.py#L124-L129

we execute `sudo -n -l /usr/local/samba/bin/smbstatus -P` and expect to see `/usr/local/samba/bin/smbstatus -P`

---

Add

```python
self.info('WANT={0}, GOT={1}'.format(smbstatus, allowed))
```

right after line 126 (`allowed = self._get_raw_data(command=command)`)

and check it in the debug mode (again, as `netdata` user)

> ./python.d.plugin debug samba

**Comment by camjesus2** [comment]
Here goes.  It seems there is one extra slah in WANT. Could that be it?

17:02-EHFS:/usr/libexec/netdata/python.d# su -s /bin/bash netdata
netdata@EHFS:/usr/libexec/netdata/python.d$ ../plugins.d/python.d.plugin debug samba
2020-07-31 17:03:36: python.d INFO: plugin[main] : using python v2
2020-07-31 17:03:36: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2020-07-31 17:03:36: python.d DEBUG: plugin[main] : loading '/etc/netdata/python.d.conf'
2020-07-31 17:03:36: python.d DEBUG: plugin[main] : '/etc/netdata/python.d.conf' is loaded
2020-07-31 17:03:36: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2020-07-31 17:03:36: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2020-07-31 17:03:36: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2020-07-31 17:03:36: python.d DEBUG: plugin[main] : [samba] looking for 'samba.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2020-07-31 17:03:36: python.d DEBUG: plugin[main] : [samba] loading '/etc/netdata/python.d/samba.conf'
2020-07-31 17:03:36: python.d DEBUG: plugin[main] : [samba] '/etc/netdata/python.d/samba.conf' is loaded
2020-07-31 17:03:36: python.d INFO: plugin[main] : [samba] built 1 job(s) configs
2020-07-31 17:03:36: python.d DEBUG: samba[samba] : Executing command '/usr/bin/sudo -n -l /usr/local/samba/bin//smbstatus -P'
2020-07-31 17:03:36: python.d INFO: samba[samba] : WANT=/usr/local/samba/bin//smbstatus -P, GOT=[u'/usr/local/samba/bin/smbstatus -P\n']
2020-07-31 17:03:36: python.d ERROR: samba[samba] : not allowed to run sudo for command '/usr/local/samba/bin//smbstatus -P'
2020-07-31 17:03:36: python.d INFO: plugin[main] : samba[samba] : check failed
2020-07-31 17:03:36: python.d INFO: plugin[main] : no jobs to serve
2020-07-31 17:03:36: python.d INFO: plugin[main] : exiting from main...

**Comment by ilyam8** [comment]
> It seems there is one extra slah in WANT. Could that be it?

> /usr/local/samba/bin//smbstatus

Yes. I wonder where does it come from 🤔 

https://github.com/netdata/netdata/blob/cfd74bbb406fc118d58016f659fcab4a96de1da7/collectors/python.d.plugin/samba/samba.chart.py#L111

---

could you try in `python` interpreter

```python
PATH = os.getenv('PATH', '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin').split(':')

def find_binary(binary):
    """
    :param binary: <str>
    :return:
    """
    for directory in PATH:
        binary_name = '/'.join([directory, binary])
        if os.path.isfile(binary_name) and os.access(binary_name, os.X_OK):
            return binary_name
    return None

find_binary('smbstatus')
```

---

if it returns `/usr/local/samba/bin//smbstatus` then the fix is 

```
return os.path.normpath(binary_name)
```

**Comment by ilyam8** [comment]
Oh, some of your PATHes ends with `/`

**Comment by ilyam8** [comment]
@camjesus2 can you test the fix #9641 ?

**Comment by camjesus2** [comment]
@ilyam8 

> Oh, some of your PATHes ends with /
Indeed they do. Damn copy/paste

After modifying collection.py as per #9641, running  `python.d.plugin debug samba` does not give any errors and seems to work as expected.

**Comment by camjesus2** [comment]
Sorry, but I've been out on the road and couldn't follow up on this. 
Again, after modifying collection.py as per #9641, running `python.d.plugin debug samba` as netdata does not give any errors and seems to work as expected.
However, `systemctl start netdata` still throws
```
python.d ERROR: samba[samba] : not allowed to run sudo for command '/usr/local/samba/bin/smbstatus -P'
python.d INFO: plugin[main] : samba[samba] : check failed
```

Did I miss something?

Best regards
Carlos

**Comment by ilyam8** [comment]
You did not. If it doesnt work after the change check https://github.com/netdata/netdata/issues/9640#issuecomment-667171495 again

**Comment by camjesus2** [comment]
hummm. after #9640 and #9641, running `python.d.plugin debug samba` as netdata gives 
```
2020-08-03 20:40:39: python.d INFO: plugin[main] : using python v2
2020-08-03 20:40:39: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2020-08-03 20:40:39: python.d DEBUG: plugin[main] : loading '/etc/netdata/python.d.conf'
2020-08-03 20:40:39: python.d DEBUG: plugin[main] : '/etc/netdata/python.d.conf' is loaded
2020-08-03 20:40:39: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2020-08-03 20:40:39: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2020-08-03 20:40:39: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2020-08-03 20:40:39: python.d DEBUG: plugin[main] : [samba] looking for 'samba.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2020-08-03 20:40:39: python.d DEBUG: plugin[main] : [samba] loading '/etc/netdata/python.d/samba.conf'
2020-08-03 20:40:39: python.d DEBUG: plugin[main] : [samba] '/etc/netdata/python.d/samba.conf' is loaded
2020-08-03 20:40:39: python.d INFO: plugin[main] : [samba] built 1 job(s) configs
2020-08-03 20:40:39: python.d DEBUG: samba[samba] : Executing command '/usr/bin/sudo -n -l /usr/local/samba/bin/smbstatus -P'
2020-08-03 20:40:39: python.d INFO: samba[samba] : WANT=/usr/local/samba/bin/smbstatus -P, GOT=[u'/usr/local/samba/bin/smbstatus -P\n']
2020-08-03 20:40:39: python.d DEBUG: samba[samba] : Executing command '/usr/bin/sudo -n /usr/local/samba/bin/smbstatus -P'
2020-08-03 20:40:39: python.d INFO: plugin[main] : samba[samba] : check success
CHART netdata.runtime_samba '' 'Execution time for samba' 'ms' 'python.d' netdata.pythond_runtime line 145000 5
DIMENSION run_time 'run time' absolute 1 1

2020-08-03 20:40:39: python.d DEBUG: samba[samba] : started, update frequency: 5
2020-08-03 20:40:42: python.d DEBUG: samba[samba] : Executing command '/usr/bin/sudo -n /usr/local/samba/bin/smbstatus -P'
CHART samba.smb2_rw '' 'R/Ws' 'KiB/s' 'smb2' 'smb2.rw' area 60001 5 '' 'python.d.plugin' 'samba'
DIMENSION 'smb2_read_outbytes' 'readout' incremental 1 1024 ' '
DIMENSION 'smb2_write_inbytes' 'writein' incremental -1 1024 ' '
DIMENSION 'smb2_read_inbytes' 'readin' incremental 1 1024 ' '
DIMENSION 'smb2_write_outbytes' 'writeout' incremental -1 1024 ' '

BEGIN samba.smb2_rw 0
.
.
.
.
```

**Comment by camjesus2** [comment]
starting netdata gives
```
2020-08-03 20:51:41: python.d INFO: samba[samba] : WANT=/usr/local/samba/bin/smbstatus -P, GOT=[]
2020-08-03 20:51:41: python.d ERROR: samba[samba] : not allowed to run sudo for command '/usr/local/samba/bin/smbstatus -P'
2020-08-03 20:51:41: python.d INFO: plugin[main] : samba[samba] : check failed
```
WANT!=GOT

**Comment by ilyam8** [comment]
hi @ntlug, any ideas?

**Comment by ntlug** [comment]
> hi @ntlug, any ideas?

I'm looking.  I run the nightlies, haven't seen the issue.

**Comment by ntlug** [comment]
Taking a wild guess, something didn't reenable requiretty in your sudo?

**Comment by camjesus2** [comment]
Neither Defaults    !requiretty nor Defaults    requiretty nor removing the line entirely made any difference.
Is the line in `python.d.plugin debug samba` output,  `WANT=/usr/local/samba/bin/smbstatus -P, GOT=[u'/usr/local/samba/bin/smbstatus -P\n']` what you expect?

**Comment by ilyam8** [comment]
That is why check fails/not fails

We execute `/usr/bin/sudo -n -l COMMAND` and expect to get `COMMAND`


> 2020-08-03 20:40:39: python.d DEBUG: samba[samba] : Executing command '/usr/bin/sudo -n -l /usr/local/samba/bin/smbstatus -P'
2020-08-03 20:40:39: python.d INFO: samba[samba] : WANT=/usr/local/samba/bin/smbstatus -P, GOT=[u'/usr/local/samba/bin/smbstatus -P\n']


`/usr/local/samba/bin/smbstatus -P` == `/usr/local/samba/bin/smbstatus -P` (new line removed)

**Comment by ilyam8** [comment]
I dont understand why it works in debug mode as `netdata` user and doesnt work in the normal mode.

**Comment by ilyam8** [comment]
there is [no problem according](https://github.com/netdata/netdata/issues/9640#issuecomment-668237628) @ntlug (samba plugin author, nightly channel user), i am closing this issue (a bug) but we can continue to debug your problem @camjesus2 here

**Comment by camjesus2** [comment]
Hy Ilya,
thanks for all your help. Good to know it's not a bug but a configuration
issue.
I still can't monitor samba even though I could in the past.
I'm just not really sure where to go from here.
Any ideas, again would be appreciated.

Best regards,
Carlos

Ilya Mashchenko <notifications@github.com> escreveu no dia sexta, 7/08/2020
à(s) 12:39:

**Comment by tycho** [comment]
I ran into this, and there's a problem with the systemd service definition.

I modified `ExecutableService.py` to print the stdout/stderr from the command:
```
2020-11-04 23:36:54: python.d ERROR: samba[samba] : cmd: '['/usr/bin/sudo', '-n', '-l', '/usr/bin/smbstatus', '-P']', stdout: '', stderr: 'sudo: unable to change to root gid: Operation not permitted
```
Note that I can run this manually as the netdata user:
```
# su -s /bin/bash - netdata
[netdata@elbereth /]$ /usr/bin/sudo -n -l /usr/bin/smbstatus -P
/usr/bin/smbstatus -P
```

The `CapabilityBoundingSet` in the systemd service doesn't have sufficient capabilities for sudo:
```
# Capabilities
# is required for freeipmi and slabinfo plugins
CapabilityBoundingSet=CAP_DAC_OVERRIDE
# is required for apps plugin
CapabilityBoundingSet=CAP_DAC_READ_SEARCH
# is required for freeipmi plugin
CapabilityBoundingSet=CAP_FOWNER
# is required for apps, perf and slabinfo plugins
CapabilityBoundingSet=CAP_SETPCAP
# is required for perf plugin
CapabilityBoundingSet=CAP_SYS_ADMIN
# is required for apps plugin
CapabilityBoundingSet=CAP_SYS_PTRACE
# is required for ebpf plugin
CapabilityBoundingSet=CAP_SYS_RESOURCE
# is required for fping app
CapabilityBoundingSet=CAP_NET_RAW
# is required for cgroups plugin
CapabilityBoundingSet=CAP_SYS_CHROOT
```
If I add this, it starts working:
```
# is required for samba plugin
CapabilityBoundingSet=CAP_SETGID CAP_SETUID  
```

**Comment by ilyam8** [comment]
Hey, guys. Can someone share the output of `smbstatus -P`?

**Comment by camjesus2** [comment]
As root:
# smbstatus -P
**** SMBD loop
****************************************************************
connect_count:
   2
disconnect_count:
  0
idle_count:
 57
idle_time:
   0
cpu_user_time:
752001
cpu_system_time:
726917
request_count:
  48
push_sec_ctx_count:
 34
push_sec_ctx_time:
   0
set_sec_ctx_count:
  11
set_sec_ctx_time:
  0
set_root_sec_ctx_count:
 54
set_root_sec_ctx_time:
   0
pop_sec_ctx_count:
  34
pop_sec_ctx_time:
  0
**** System Calls
*************************************************************
syscall_opendir_count:
   0
syscall_opendir_time:
  0
syscall_fdopendir_count:
   5
syscall_fdopendir_time:
  0
syscall_readdir_count:
1010
syscall_readdir_time:
  0
syscall_rewinddir_count:
   1
syscall_rewinddir_time:
  0
syscall_mkdirat_count:
   0
syscall_mkdirat_time:
  0
syscall_closedir_count:
  5
syscall_closedir_time:
   0
syscall_open_count:
  0
syscall_open_time:
   0
syscall_openat_count:
426
syscall_openat_time:
   0
syscall_createfile_count:
  0
syscall_createfile_time:
   0
syscall_close_count:
 419
syscall_close_time:
  0
syscall_pread_count:
   0
syscall_pread_time:
  0
syscall_pread_idle:
  0
syscall_pread_bytes:
   0
syscall_asys_pread_count:
  0
syscall_asys_pread_time:
   0
syscall_asys_pread_idle:
   0
syscall_asys_pread_bytes:
  0
syscall_pwrite_count:
  0
syscall_pwrite_time:
   0
syscall_pwrite_idle:
   0
syscall_pwrite_bytes:
  0
syscall_asys_pwrite_count:
   0
syscall_asys_pwrite_time:
  0
syscall_asys_pwrite_idle:
  0
syscall_asys_pwrite_bytes:
   0
syscall_lseek_count:
   0
syscall_lseek_time:
  0
syscall_sendfile_count:
  0
syscall_sendfile_time:
   0
syscall_sendfile_idle:
   0
syscall_sendfile_bytes:
  0
syscall_recvfile_count:
  0
syscall_recvfile_time:
   0
syscall_recvfile_idle:
   0
syscall_recvfile_bytes:
  0
syscall_renameat_count:
  0
syscall_renameat_time:
   0
syscall_asys_fsync_count:
  0
syscall_asys_fsync_time:
   0
syscall_asys_fsync_idle:
   0
syscall_asys_fsync_bytes:
  0
syscall_stat_count:
 28
syscall_stat_time:
   0
syscall_fstat_count:
 477
syscall_fstat_time:
  0
syscall_lstat_count:
   0
syscall_lstat_time:
  0
syscall_fstatat_count:
   1
syscall_fstatat_time:
  0
syscall_get_alloc_size_count:
416
syscall_get_alloc_size_time:
   0
syscall_unlinkat_count:
  0
syscall_unlinkat_time:
   0
syscall_chmod_count:
   0
syscall_chmod_time:
  0
syscall_fchmod_count:
  0
syscall_fchmod_time:
   0
syscall_fchown_count:
  0
syscall_fchown_time:
   0
syscall_lchown_count:
  0
syscall_lchown_time:
   0
syscall_chdir_count:
  12
syscall_chdir_time:
  0
syscall_getwd_count:
   5
syscall_getwd_time:
  0
syscall_fntimes_count:
   0
syscall_fntimes_time:
  0
syscall_ftruncate_count:
   0
syscall_ftruncate_time:
  0
syscall_fallocate_count:
   0
syscall_fallocate_time:
  0
syscall_fcntl_lock_count:
  0
syscall_fcntl_lock_time:
   0
syscall_fcntl_count:
   0
syscall_fcntl_time:
  0
syscall_linux_setlease_count:
  0
syscall_linux_setlease_time:
   0
syscall_fcntl_getlock_count:
   0
syscall_fcntl_getlock_time:
  0
syscall_readlinkat_count:
  0
syscall_readlinkat_time:
   0
syscall_symlinkat_count:
   0
syscall_symlinkat_time:
  0
syscall_linkat_count:
  0
syscall_linkat_time:
   0
syscall_mknodat_count:
   0
syscall_mknodat_time:
  0
syscall_realpath_count:
  9
syscall_realpath_time:
   0
syscall_get_quota_count:
   0
syscall_get_quota_time:
  0
syscall_set_quota_count:
   0
syscall_set_quota_time:
  0
syscall_get_sd_count:
  0
syscall_get_sd_time:
   0
syscall_set_sd_count:
  0
syscall_set_sd_time:
   0
syscall_brl_lock_count:
  0
syscall_brl_lock_time:
   0
syscall_brl_unlock_count:
  0
syscall_brl_unlock_time:
   0
syscall_brl_cancel_count:
  0
syscall_brl_cancel_time:
   0
syscall_asys_getxattrat_count:
   0
syscall_asys_getxattrat_time:
  0
syscall_asys_getxattrat_idle:
  0
syscall_asys_getxattrat_bytes:
   0
**** ACL Calls
****************************************************************
get_nt_acl_count:
  0
get_nt_acl_time:
   0
get_nt_acl_at_count:
   0
get_nt_acl_at_time:
  0
fget_nt_acl_count:
  20
fget_nt_acl_time:
  0
fset_nt_acl_count:
   0
fset_nt_acl_time:
  0
**** Stat Cache
***************************************************************
statcache_lookups_count:
   1
statcache_misses_count:
  1
statcache_hits_count:
  0
**** SMB Calls
****************************************************************
SMBmkdir_count:
  0
SMBmkdir_time:
   0
SMBrmdir_count:
  0
SMBrmdir_time:
   0
SMBopen_count:
   0
SMBopen_time:
  0
SMBcreate_count:
   0
SMBcreate_time:
  0
SMBclose_count:
  0
SMBclose_time:
   0
SMBflush_count:
  0
SMBflush_time:
   0
SMBunlink_count:
   0
SMBunlink_time:
  0
SMBmv_count:
   0
SMBmv_time:
  0
SMBgetatr_count:
   0
SMBgetatr_time:
  0
SMBsetatr_count:
   0
SMBsetatr_time:
  0
SMBread_count:
   0
SMBread_time:
  0
SMBwrite_count:
  0
SMBwrite_time:
   0
SMBlock_count:
   0
SMBlock_time:
  0
SMBunlock_count:
   0
SMBunlock_time:
  0
SMBctemp_count:
  0
SMBctemp_time:
   0
SMBmknew_count:
  0
SMBmknew_time:
   0
SMBcheckpath_count:
  0
SMBcheckpath_time:
   0
SMBexit_count:
   0
SMBexit_time:
  0
SMBlseek_count:
  0
SMBlseek_time:
   0
SMBlockread_count:
   0
SMBlockread_time:
  0
SMBwriteunlock_count:
  0
SMBwriteunlock_time:
   0
SMBreadbraw_count:
   0
SMBreadbraw_time:
  0
SMBreadBmpx_count:
   0
SMBreadBmpx_time:
  0
SMBreadBs_count:
   0
SMBreadBs_time:
  0
SMBwritebraw_count:
  0
SMBwritebraw_time:
   0
SMBwriteBmpx_count:
  0
SMBwriteBmpx_time:
   0
SMBwriteBs_count:
  0
SMBwriteBs_time:
   0
SMBwritec_count:
   0
SMBwritec_time:
  0
SMBsetattrE_count:
   0
SMBsetattrE_time:
  0
SMBgetattrE_count:
   0
SMBgetattrE_time:
  0
SMBlockingX_count:
   0
SMBlockingX_time:
  0
SMBtrans_count:
  0
SMBtrans_time:
   0
SMBtranss_count:
   0
SMBtranss_time:
  0
SMBioctl_count:
  0
SMBioctl_time:
   0
SMBioctls_count:
   0
SMBioctls_time:
  0
SMBcopy_count:
   0
SMBcopy_time:
  0
SMBmove_count:
   0
SMBmove_time:
  0
SMBecho_count:
   0
SMBecho_time:
  0
SMBwriteclose_count:
   0
SMBwriteclose_time:
  0
SMBopenX_count:
  0
SMBopenX_time:
   0
SMBreadX_count:
  0
SMBreadX_time:
   0
SMBwriteX_count:
   0
SMBwriteX_time:
  0
SMBtrans2_count:
   0
SMBtrans2_time:
  0
SMBtranss2_count:
  0
SMBtranss2_time:
   0
SMBfindclose_count:
  0
SMBfindclose_time:
   0
SMBfindnclose_count:
   0
SMBfindnclose_time:
  0
SMBtcon_count:
   0
SMBtcon_time:
  0
SMBtdis_count:
   0
SMBtdis_time:
  0
SMBnegprot_count:
  0
SMBnegprot_time:
   0
SMBsesssetupX_count:
   0
SMBsesssetupX_time:
  0
SMBulogoffX_count:
   0
SMBulogoffX_time:
  0
SMBtconX_count:
  0
SMBtconX_time:
   0
SMBdskattr_count:
  0
SMBdskattr_time:
   0
SMBsearch_count:
   0
SMBsearch_time:
  0
SMBffirst_count:
   0
SMBffirst_time:
  0
SMBfunique_count:
  0
SMBfunique_time:
   0
SMBfclose_count:
   0
SMBfclose_time:
  0
SMBnttrans_count:
  0
SMBnttrans_time:
   0
SMBnttranss_count:
   0
SMBnttranss_time:
  0
SMBntcreateX_count:
  0
SMBntcreateX_time:
   0
SMBntcancel_count:
   0
SMBntcancel_time:
  0
SMBntrename_count:
   0
SMBntrename_time:
  0
SMBsplopen_count:
  0
SMBsplopen_time:
   0
SMBsplwr_count:
  0
SMBsplwr_time:
   0
SMBsplclose_count:
   0
SMBsplclose_time:
  0
SMBsplretq_count:
  0
SMBsplretq_time:
   0
SMBsends_count:
  0
SMBsends_time:
   0
SMBsendb_count:
  0
SMBsendb_time:
   0
SMBfwdname_count:
  0
SMBfwdname_time:
   0
SMBcancelf_count:
  0
SMBcancelf_time:
   0
SMBgetmac_count:
   0
SMBgetmac_time:
  0
SMBsendstrt_count:
   0
SMBsendstrt_time:
  0
SMBsendend_count:
  0
SMBsendend_time:
   0
SMBsendtxt_count:
  0
SMBsendtxt_time:
   0
SMBinvalid_count:
  0
SMBinvalid_time:
   0
**** Trans2 Calls
*************************************************************
Trans2_open_count:
   0
Trans2_open_time:
  0
Trans2_findfirst_count:
  0
Trans2_findfirst_time:
   0
Trans2_findnext_count:
   0
Trans2_findnext_time:
  0
Trans2_qfsinfo_count:
  0
Trans2_qfsinfo_time:
   0
Trans2_setfsinfo_count:
  0
Trans2_setfsinfo_time:
   0
Trans2_qpathinfo_count:
  0
Trans2_qpathinfo_time:
   0
Trans2_setpathinfo_count:
  0
Trans2_setpathinfo_time:
   0
Trans2_qfileinfo_count:
  0
Trans2_qfileinfo_time:
   0
Trans2_setfileinfo_count:
  0
Trans2_setfileinfo_time:
   0
Trans2_fsctl_count:
  0
Trans2_fsctl_time:
   0
Trans2_ioctl_count:
  0
Trans2_ioctl_time:
   0
Trans2_findnotifyfirst_count:
  0
Trans2_findnotifyfirst_time:
   0
Trans2_findnotifynext_count:
   0
Trans2_findnotifynext_time:
  0
Trans2_mkdir_count:
  0
Trans2_mkdir_time:
   0
Trans2_session_setup_count:
  0
Trans2_session_setup_time:
   0
Trans2_get_dfs_referral_count:
   0
Trans2_get_dfs_referral_time:
  0
Trans2_report_dfs_inconsistancy_count:
   0
Trans2_report_dfs_inconsistancy_time:
  0
**** NT Transact Calls
********************************************************
NT_transact_create_count:
  0
NT_transact_create_time:
   0
NT_transact_ioctl_count:
   0
NT_transact_ioctl_time:
  0
NT_transact_set_security_desc_count:
   0
NT_transact_set_security_desc_time:
  0
NT_transact_notify_change_count:
   0
NT_transact_notify_change_time:
  0
NT_transact_rename_count:
  0
NT_transact_rename_time:
   0
NT_transact_query_security_desc_count:
   0
NT_transact_query_security_desc_time:
  0
NT_transact_get_user_quota_count:
  0
NT_transact_get_user_quota_time:
   0
NT_transact_set_user_quota_count:
  0
NT_transact_set_user_quota_time:
   0
**** SMB2 Calls
***************************************************************
smb2_negprot_count:
  2
smb2_negprot_time:
   0
smb2_negprot_idle:
   0
smb2_negprot_inbytes:
472
smb2_negprot_outbytes:
 568
smb2_sesssetup_count:
  2
smb2_sesssetup_time:
   0
smb2_sesssetup_idle:
   0
smb2_sesssetup_inbytes:
 4100
smb2_sesssetup_outbytes:
 514
smb2_logoff_count:
   0
smb2_logoff_time:
  0
smb2_logoff_idle:
  0
smb2_logoff_inbytes:
   0
smb2_logoff_outbytes:
  0
smb2_tcon_count:
   3
smb2_tcon_time:
  0
smb2_tcon_idle:
  0
smb2_tcon_inbytes:
 300
smb2_tcon_outbytes:
240
smb2_tdis_count:
   1
smb2_tdis_time:
  0
smb2_tdis_idle:
  0
smb2_tdis_inbytes:
  68
smb2_tdis_outbytes:
 68
smb2_create_count:
  14
smb2_create_time:
  0
smb2_create_idle:
  0
smb2_create_inbytes:
5564
smb2_create_outbytes:
 3137
smb2_close_count:
 12
smb2_close_time:
   0
smb2_close_idle:
   0
smb2_close_inbytes:
 1056
smb2_close_outbytes:
1488
smb2_flush_count:
  0
smb2_flush_time:
   0
smb2_flush_idle:
   0
smb2_flush_inbytes:
  0
smb2_flush_outbytes:
   0
smb2_read_count:
   0
smb2_read_time:
  0
smb2_read_idle:
  0
smb2_read_inbytes:
   0
smb2_read_outbytes:
  0
smb2_write_count:
  0
smb2_write_time:
   0
smb2_write_idle:
   0
smb2_write_inbytes:
  0
smb2_write_outbytes:
   0
smb2_lock_count:
   0
smb2_lock_time:
  0
smb2_lock_idle:
  0
smb2_lock_inbytes:
   0
smb2_lock_outbytes:
  0
smb2_ioctl_count:
  5
smb2_ioctl_time:
   0
smb2_ioctl_idle:
   0
smb2_ioctl_inbytes:
696
smb2_ioctl_outbytes:
1051
smb2_cancel_count:
   0
smb2_cancel_time:
  0
smb2_cancel_idle:
  0
smb2_cancel_inbytes:
   0
smb2_cancel_outbytes:
  0
smb2_keepalive_count:
  0
smb2_keepalive_time:
   0
smb2_keepalive_idle:
   0
smb2_keepalive_inbytes:
  0
smb2_keepalive_outbytes:
   0
smb2_find_count:
   7
smb2_find_time:
  0
smb2_find_idle:
  0
smb2_find_inbytes:
 768
smb2_find_outbytes:
73258
smb2_notify_count:
   0
smb2_notify_time:
  0
smb2_notify_idle:
  0
smb2_notify_inbytes:
   0
smb2_notify_outbytes:
  0
smb2_getinfo_count:
  2
smb2_getinfo_time:
   0
smb2_getinfo_idle:
   0
smb2_getinfo_inbytes:
217
smb2_getinfo_outbytes:
 200
smb2_setinfo_count:
  0
smb2_setinfo_time:
   0
smb2_setinfo_idle:
   0
smb2_setinfo_inbytes:
  0
smb2_setinfo_outbytes:
   0
smb2_break_count:
  0
smb2_break_time:
   0
smb2_break_idle:
   0
smb2_break_inbytes:
  0
smb2_break_outbytes:
   0

Ilya Mashchenko ***@***.***> escreveu (segunda, 26/08/2024
à(s) 10:21):
