### ISSUE TITLE
Netdata causing PiHole access.log to grow very large 

### ISSUE THREAD

**Issue by silentwolf15** [netdata/netdata#9642]
**Version:** netdata v1.23.2-91-nightly

**Issue:** Netdata is accessing the api so often that the /var/log/lighttpd/access.log log file grows almost out of control

-rw-r--r-- 1 www-data www-data     4378 Jul 25 09:14 error.log.1
-rw-r--r-- 1 www-data www-data      747 Jul 30 10:15 error.log
-rw-r--r-- 1 www-data www-data **71470202** Jul 31 13:47 access.log

This is less then one days worth of logs!

**Comment by ilyam8** [comment]
Hi, i see it is 71MB. Is it a problem? What is log rotate period? Daily?

It is 5 requests per `update_every`, this parameter is configurable.

https://github.com/netdata/go.d.plugin/blob/53903fae83db4cbe2f5c962e85db70ae86f557bd/modules/pihole/collect.go#L97-L104

**Comment by ilyam8** [comment]
> PiHole access.log

Is pi-hole related? I see it is lighttpd log

**Comment by silentwolf15** [comment]
It's an issue when I am using Log2Ram for /var/log directory :) Raspberry Pi only has so much RAM available :)

**Comment by ilyam8** [comment]
It is possible to not log some requests, that is how to do it for Apache

> https://github.com/netdata/netdata/issues/5385#issuecomment-463505236

I guess lighttpd has something similar

---

> It's an issue when I am using Log2Ram

well, as i said `update_every` is user configurable, change to `5` or whatever you think is ok

**Comment by silentwolf15** [comment]
Thank you!
