### ISSUE TITLE
MySQL not showing in

### ISSUE THREAD

**Issue by alexcavazos67** [netdata/netdata#9649]
I installed netdata in my web server. Apache appears but I cannot get MySQL to show up. I've read all the past posts and ran all the recommended measures but without success. I am attaching all the relevant files.

### **uname**
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"

### **netdata** -V 
netdata v1.23.2-105-nightly

### **$(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V**
netdata v1.23.2-105-nightly

### **/etc/netdata/python.d.conf**
    enabled: yes
    apache_cache: no
    chrony: no
    example: no
    gunicorn_log: no
    go_expvar: no
    mysql: yes
    nginx_log: no

### **/etc/netdata/python.d/mysql.conf**
    mycnf1:
    name     : 'local'
    'my.cnf' : '/etc/my.cnf'
    mycnf2:
    name     : 'local'
    'my.cnf' : '/etc/mysql/my.cnf'
    debiancnf:
    name     : 'local'
    'my.cnf' : '/etc/mysql/debian.cnf'
    socket1:
    name     : 'local'
    socket   : '/var/run/mysqld/mysqld.sock'
    socket2:
    name     : 'local'
    socket   : '/var/run/mysqld/mysql.sock'
    socket3:
    name     : 'local'
    socket   : '/var/lib/mysql/mysql.sock'
    socket4:
    name     : 'local'
    socket   : '/tmp/mysql.sock'
    tcpipv4:
    name     : 'local'
    host     : '127.0.0.1'
    port     : '3306'
    tcpipv6:
    name     : 'local'
    host     : '::1'
    port     : '3306'
    ###
    ### User root
    ###
    mycnf1_root:
    name     : 'local'
    user     : 'root'
    'my.cnf' : '/etc/my.cnf'
    mycnf2_root:
    name     : 'local'
    user     : 'root'
    'my.cnf' : '/etc/mysql/my.cnf'
    socket1_root:
    name     : 'local'
    user     : 'root'
    socket   : '/var/run/mysqld/mysqld.sock'
    socket2_root:
    name     : 'local'
    user     : 'root'
    socket   : '/var/run/mysqld/mysql.sock'
    socket3_root:
    name     : 'local'
    user     : 'root'
    socket   : '/var/lib/mysql/mysql.sock'
    socket4_root:
    name     : 'local'
    user     : 'root'
    socket   : '/tmp/mysql.sock'
    tcp_root:
    name     : 'local'
    user     : 'root'
    host     : 'localhost'
    port     : '3306'
    tcpipv4_root:
    name     : 'local'
    user     : 'root'
    host     : '127.0.0.1'
    port     : '3306'
    tcpipv6_root:
    name     : 'local'
    user     : 'root'
    host     : '::1'
    port     : '3306'  
    ###
    ### User netdata
    ###
    mycnf1_netdata:
    name     : 'local'
    user     : 'netdata'
    'my.cnf' : '/etc/my.cnf'
    mycnf2_netdata:
    name     : 'local'
    user     : 'netdata'
    'my.cnf' : '/etc/mysql/my.cnf'
    socket1_netdata:
    name     : 'local'
    user     : 'netdata'
    socket   : '/var/run/mysqld/mysqld.sock'
    socket2_netdata:
    name     : 'local'
    user     : 'netdata'
    socket   : '/var/run/mysqld/mysql.sock'
    socket3_netdata:
    name     : 'local'
    user     : 'netdata'
    socket   : '/var/lib/mysql/mysql.sock'
    socket4_netdata:
    name     : 'local'
    user     : 'netdata'
    socket   : '/tmp/mysql.sock'
    tcp_netdata:
    name     : 'local'
    user     : 'netdata'
    host     : 'localhost'
    port     : '3306'
    tcpipv4_netdata:
    name     : 'local'
    user     : 'netdata'
    host     : '127.0.0.1'
    port     : '3306'
    tcpipv6_netdata:
    name     : 'local'
    user     : 'netdata'
    host     : '::1'
    port     : '3306'

**Comment by ilyam8** [comment]
hi

do as `netdata` user

> ./python.d.plugin debug mysql

---

did you create `netdata` mysql user?

> https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mysql#requirements

**Comment by alexcavazos67** [comment]
mysql user missing. SOLVED.
