### ISSUE TITLE
Can't install and configure netdata in UBUNTU 16.04

### ISSUE THREAD

**Issue by HuyQuachHCM** [netdata/netdata#9653]
Hello everyone. I follow the instructions from netdata website, I get the following error::
- Fist, i install following command:
  apt-get install zlib1g-dev uuid-dev libmnl-dev gcc make git autoconf autogen automake pkg-config. 
- Second i clone git : 
![image](https://user-images.githubusercontent.com/69178310/89243783-0261eb00-d62f-11ea-96cd-6a206ffe681d.png)
- Third i get the following error:
![image](https://user-images.githubusercontent.com/69178310/89243825-21607d00-d62f-11ea-8715-a0ad52f85e85.png)
I have followed the above steps but I cannot fix the error when installing netdata
Can I ask everyone to help me fix the error above?
Thanks all,

**Comment by prologic** [comment]
Hello @HuyQuachHCM 👋

Can you please try the following steps:

```console
git clone https://github.com/netdata/netdata.git
cd netdata
./packaging/installer/install-required-packages.sh
sudo ./netdata-installer.sh
```

We have tools to make this easy for you. You can also just execute the following for an even quicker install:

```console
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

**Comment by HuyQuachHCM** [comment]
@prologic Thank you so much.

**Comment by prologic** [comment]
You're welcome! 🤗
