### ISSUE TITLE
SSO fail in Vivaldi

### ISSUE THREAD

**Issue by danmichaelo** [netdata/netdata#9654]
##### Bug report summary

If I press the green "Sign-in" button at the top right on one of my nodes, say http://some-host:19999, I can sign it at https://app.netdata.cloud/, but when I get back to http://some-host:19999, I'm not signed in there.

So similar problem to #6298, but I'm not sure if it's really related, since I do not get the same error in the console. Instead I get this:

![image](https://user-images.githubusercontent.com/434495/89272627-b74fd400-d63e-11ea-9741-e0dd8dda27f6.png)

It seems to be browser-related though. If I try signing in from the same host in Chrome, it works as expected: I get redirected back and can see my other nodes as well as a "Sign out" button.

I've tried starting again in a private window in Vivaldi, but the issue persists.

##### OS / Environment

* Fedora 31 with Netdata not running in a container

##### Netdata version

* netdata v1.23.2-115-nightly

##### Component Name

Netdata Cloud

##### Steps To Reproduce

1. Open Vivaldi
2. Open http://some-host:19999
3. Press the "Sign in" button at the upper right corner
4. Sign in, if not already signed in

##### Expected behavior

After being authorized at https://app.netdata.cloud/, I should get redirected back to http://some-host:19999, and signed in there.

**Comment by danmichaelo** [comment]
Update: It *is* related to #6298. Turns out Vivaldi also disables third party cookies by default. After I unchecked that option, it worked as expected.

**Comment by ilyam8** [comment]
@jacekkolasa is this something we need/plan to fix?

**Comment by jacekkolasa** [comment]
@danmichaelo thanks for letting us know. BTW. i installed Vivaldi (for the first time, on macOS) and it seems to be working fine, with third party cookies enabled by default (maybe they've changed the default setting? i'm not sure..). Anyway, there's not much we can do right now. I hope that in the future we will be able to ask user for single-sign-on consent via browser API. Safari is trying to do something like this with their Storage Access API and perhaps we'll experiment with this.

I'm closing this now, but feel free to reopen if you have other questions
