### ISSUE TITLE
Netdata master crashing at streaming set-up

### ISSUE THREAD

**Issue by mfundul** [netdata/netdata#9662]
> 
> 
> Hi,
> 
> I have a similar if not the same issue with Netdata crashing at startup. I deleted all db files but it did not fix the issue.
> 
> Basic system informations
> 
> ```
> Linux ip-172-31-34-68 5.3.0-1030-aws #32~18.04.1-Ubuntu SMP Tue Jun 30 23:04:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> 2GB Ram
> 1CPU
> ```
> 
> Netdata version
> `v1.23.2-24-nightly`
> 
> Installation source
> `netdata.cloud`
> 
> Installation command & parameters
> `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
> 
> Netdata acts as a master, receiving streams from multiple agents (5). All agents are updated to the last version.
> All worked fine until it began crashing, maybe an auto update is causing this issue?
> 
> Here is the valgrind output
> 
> ```
> ==5233== Memcheck, a memory error detector
> ==5233== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==5233== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
> ==5233== Command: /usr/sbin/netdata -D
> ==5233== 
> 2020-07-20 13:17:46: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
> 2020-07-20 13:17:46: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
> ==5233== Thread 17 STREAM_RECEIVER:
> ==5233== Invalid read of size 1
> ==5233==    at 0x4C32CF2: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==5233==    by 0x184200: create_label (in /usr/sbin/netdata)
> ==5233==    by 0x14CDA9: pluginsd_label_action (in /usr/sbin/netdata)
> ==5233==    by 0x14BD31: pluginsd_label (in /usr/sbin/netdata)
> ==5233==    by 0x17C8FD: parser_action (in /usr/sbin/netdata)
> ==5233==    by 0x1B4D27: rrdpush_receive (in /usr/sbin/netdata)
> ==5233==    by 0x1B5041: rrdpush_receiver_thread (in /usr/sbin/netdata)
> ==5233==    by 0x12F23F: thread_start (in /usr/sbin/netdata)
> ==5233==    by 0x559B6DA: start_thread (pthread_create.c:463)
> ==5233==    by 0x58D4A3E: clone (clone.S:95)
> ==5233==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
> ==5233== 
> ==5233== 
> ==5233== Process terminating with default action of signal 11 (SIGSEGV)
> ==5233==  Access not within mapped region at address 0x0
> ==5233==    at 0x4C32CF2: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
> ==5233==    by 0x184200: create_label (in /usr/sbin/netdata)
> ==5233==    by 0x14CDA9: pluginsd_label_action (in /usr/sbin/netdata)
> ==5233==    by 0x14BD31: pluginsd_label (in /usr/sbin/netdata)
> ==5233==    by 0x17C8FD: parser_action (in /usr/sbin/netdata)
> ==5233==    by 0x1B4D27: rrdpush_receive (in /usr/sbin/netdata)
> ==5233==    by 0x1B5041: rrdpush_receiver_thread (in /usr/sbin/netdata)
> ==5233==    by 0x12F23F: thread_start (in /usr/sbin/netdata)
> ==5233==    by 0x559B6DA: start_thread (pthread_create.c:463)
> ==5233==    by 0x58D4A3E: clone (clone.S:95)
> ==5233==  If you believe this happened as a result of a stack
> ==5233==  overflow in your program's main thread (unlikely but
> ==5233==  possible), you can try to increase the size of the
> ==5233==  main thread stack using the --main-stacksize= flag.
> ==5233==  The main thread stack size used in this run was 8388608.
> ==5233== 
> ==5233== HEAP SUMMARY:
> ==5233==     in use at exit: 14,270,977 bytes in 159,046 blocks
> ==5233==   total heap usage: 239,290 allocs, 80,244 frees, 28,620,770 bytes allocated
> ==5233== 
> ==5233== LEAK SUMMARY:
> ==5233==    definitely lost: 4,239 bytes in 418 blocks
> ==5233==    indirectly lost: 0 bytes in 0 blocks
> ==5233==      possibly lost: 210,543 bytes in 6,709 blocks
> ==5233==    still reachable: 14,056,195 bytes in 151,919 blocks
> ==5233==         suppressed: 0 bytes in 0 blocks
> ==5233== Rerun with --leak-check=full to see details of leaked memory
> ==5233== 
> ==5233== For counts of detected and suppressed errors, rerun with: -v
> ==5233== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
> ==5233== could not unlink /tmp/vgdb-pipe-from-vgdb-to-5233-by-root-on-???
> ==5233== could not unlink /tmp/vgdb-pipe-to-vgdb-from-5233-by-root-on-???
> ==5233== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-5233-by-root-on-???
> Segmentation fault (core dumped)
> ```
> 
> Also my logs are full of segfaults:
> 
> ```
> [Mon Jul 20 13:15:53 2020] STREAM_RECEIVER[4241]: segfault at 0 ip 00007fc230570811 sp 00007fc227ce1178 error 4 in libc-2.27.so[7fc2303e2000+1e7000]
> [Mon Jul 20 13:15:53 2020] Code: 2e 0f 1f 84 00 00 00 00 00 31 c0 c5 f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 89 f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 1f <c5> fd 74 0f c5 fd d7 c1 85 c0 0f 85 df 00 00 00 48 83 c7 20 83 e1
> [Mon Jul 20 13:16:24 2020] STREAM_RECEIVER[4473]: segfault at 0 ip 00007f6047dca811 sp 00007f6041d40178 error 4 in libc-2.27.so[7f6047c3c000+1e7000]
> [Mon Jul 20 13:16:24 2020] Code: 2e 0f 1f 84 00 00 00 00 00 31 c0 c5 f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 89 f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 1f <c5> fd 74 0f c5 fd d7 c1 85 c0 0f 85 df 00 00 00 48 83 c7 20 83 e1
> [Mon Jul 20 13:16:55 2020] STREAM_RECEIVER[4706]: segfault at 0 ip 00007f85dbf77811 sp 00007f85d5eed178 error 4 in libc-2.27.so[7f85dbde9000+1e7000]
> ```
> 
> If you need more info let me know.

@raduburla do you still have this problem after updating to the latest master?

_Originally posted by @mfundul in https://github.com/netdata/netdata/issues/9521#issuecomment-667010587_

**Comment by mfundul** [comment]
@raduburla I've created a new issue since this is a different situation than where you posted your comment https://github.com/netdata/netdata/issues/9521#issuecomment-667065911

**Comment by mfundul** [comment]
I've reproduced this. The way to do it is to create an invalid list of labels for the child node that is streaming. I added the following in the child's `/etc/netdata/netdata.conf`:
```
[host labels]
    type =
    location = gr-heraklion
    installed = 20200810
```
The first label has got a null value and causes this crash.

**Comment by mfundul** [comment]
@raduburla is it possible you have an invalid `[host labels]` section in one of your child nodes?

**Comment by raduburla** [comment]
I never touched that section of netdata.conf but just to be sure i reinstalled netdata to get a fresh netdata.conf. 
So I ma running the latest nightly on child (netdata v1.23.2-151-nightly) but the problem still exists. Only conf file changed is stream.conf.

When installing I also get this error, maybe it helps

```
 --- eBPF Kernel Collector --- 
[/tmp/netdata-kickstart-EElOVU/netdata-v1.23.2-151-g0e5f2e38]# ./packaging/check-kernel-config.sh 
WARNING: Your kernel appears to be older than 4.11 or you are using RH version older than 7.6.1810. This may still work in some cases, but probably won't.
 Missing Kernel Config: BPF
 FAILED   

Warning: Kernel unsupported or missing required config (eBPF may not work on your system)
 --- Installing eBPF plugin --- 
 Detected GLIBC
[/tmp/netdata-kickstart-EElOVU/netdata-v1.23.2-151-g0e5f2e38]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-ebpf-GnKTeU/netdata-kernel-collector-glibc-v0.4.8.tar.xz https://github.com/netdata/kernel-collector/releases/download/v0.4.8/netdata-kernel-collector-glibc-v0.4.8.tar.xz 
 OK   

```

My stream.conf file
```
# netdata configuration for aggregating data from remote hosts
#
# API keys authorize a pair of sending-receiving netdata servers.
# Once their communication is authorized, they can exchange metrics for any
# number of hosts.
#
# You can generate API keys, with the linux command: uuidgen


# -----------------------------------------------------------------------------
# 1. ON CHILD NETDATA - THE ONE THAT WILL BE SENDING METRICS

[stream]
    # Enable this on child nodes, to have them send metrics.
    enabled = yes

    # Where is the receiving netdata?
    # A space separated list of:
    #
    #      [PROTOCOL:]HOST[%INTERFACE][:PORT][:SSL]
    #
    # If many are given, the first available will get the metrics.
    #
    # PROTOCOL  = tcp, udp, or unix (only tcp and unix are supported by parent nodes)
    # HOST      = an IPv4, IPv6 IP, or a hostname, or a unix domain socket path.
    #             IPv6 IPs should be given with brackets [ip:address]
    # INTERFACE = the network interface to use (only for IPv6)
    # PORT      = the port number or service name (/etc/services)
    # SSL       = when this word appear at the end of the destination string
    #             the Netdata will encrypt the connection with the parent.
    #
    # This communication is not HTTP (it cannot be proxied by web proxies).
    destination = ec2-ip-of-server.eu-west-1.compute.amazonaws.com:19996:SSL

    # Skip Certificate verification?
    #
    # The netdata child is configurated to avoid invalid SSL/TLS certificate,
    # so certificates that are self-signed or expired will stop the streaming.
    # Case the server certificate is not valid, you can enable the use of
    # 'bad' certificates setting the next option as 'yes'.
    #
    ssl skip certificate verification = yes

    # Certificate Authority Path
    #
    # OpenSSL has a default directory where the known certificates are stored,
    # case it is necessary it is possible to change this rule using the variable
    # "CApath"
    #
    #CApath = /etc/ssl/certs/

    # Certificate Authority file
    #
    # When the Netdata parent has certificate, that is not recognized as valid,
    # we can add this certificate in the list of known certificates in CApath
    # and give for Netdata as argument.
    #
    #CAfile = /etc/ssl/certs/cert.pem

    # The API_KEY to use (as the sender)
    api key = api-key-was-here

    # The timeout to connect and send metrics
    timeout seconds = 60

    # If the destination line above does not specify a port, use this
    default port = 19999

    # filter the charts to be streamed
    # netdata SIMPLE PATTERN:
    # - space separated list of patterns (use \ to include spaces in patterns)
    # - use * as wildcard, any number of times within each pattern
    # - prefix a pattern with ! for a negative match (ie not stream the charts it matches)
    # - the order of patterns is important (left to right)
    # To send all except a few, use: !this !that *   (ie append a wildcard pattern)
    send charts matching = *

    # The buffer to use for sending metrics.
    # 1MB is good for 10-20 seconds of data, so increase this if you expect latencies.
    # The buffer is flushed on reconnects (this will not prevent gaps at the charts).
    buffer size bytes = 1048576

    # If the connection fails, or it disconnects,
    # retry after that many seconds.
    reconnect delay seconds = 5

    # Sync the clock of the charts for that many iterations, when starting.
    initial clock resync iterations = 60

# -----------------------------------------------------------------------------
# 2. ON PARENT NETDATA - THE ONE THAT WILL BE RECEIVING METRICS

#    You can have one API key per child,
#         or the same API key for all child nodes.
#
#    netdata searches for options in this order:
#
#    a) parent netdata settings (netdata.conf)
#    b) [stream] section        (above)
#    c) [API_KEY] section       (below, settings for the API key)
#    d) [MACHINE_GUID] section  (below, settings for each machine)
#
#    You can combine the above (the more specific setting will be used).

# API key authentication
# If the key is not listed here, it will not be able to push metrics.

# [API_KEY] is [YOUR-API-KEY], i.e [11111111-2222-3333-4444-555555555555]
[API_KEY]
    # Default settings for this API key

    # You can disable the API key, by setting this to: no
    # The default (for unknown API keys) is: no
    enabled = no

    # A list of simple patterns matching the IPs of the servers that
    # will be pushing metrics using this API key.
    # The metrics are received via the API port, so the same IPs
    # should also be matched at netdata.conf [web].allow connections from
    allow from = *

    # The default history in entries, for all hosts using this API key.
    # You can also set it per host below.
    # If you don't set it here, the history size of the central netdata
    # will be used.
    default history = 3600

    # The default memory mode to be used for all hosts using this API key.
    # You can also set it per host below.
    # If you don't set it here, the memory mode of netdata.conf will be used.
    # Valid modes:
    #    save     save on exit, load on start
    #    map      like swap (continuously syncing to disks - you need SSD)
    #    ram      keep it in RAM, don't touch the disk
    #    none     no database at all (use this on headless proxies)
    #    dbengine like a traditional database
    default memory mode = ram

    # Shall we enable health monitoring for the hosts using this API key?
    # 3 possible values:
    #    yes     enable alarms
    #    no      do not enable alarms
    #    auto    enable alarms, only when the sending netdata is connected. For ephemeral child nodes or child system restarts,
    #            ensure that the netdata process on the child is gracefully stopped, to prevent invalid last_collected alarms
    # You can also set it per host, below.
    # The default is taken from [health].enabled of netdata.conf
    health enabled by default = auto

    # postpone alarms for a short period after the sender is connected
    default postpone alarms on connect seconds = 60

    # need to route metrics differently? set these.
    # the defaults are the ones at the [stream] section (above)
    #default proxy enabled = yes | no
    #default proxy destination = IP:PORT IP:PORT ...
    #default proxy api key = API_KEY
    #default proxy send charts matching = *


# -----------------------------------------------------------------------------
# 3. PER SENDING HOST SETTINGS, ON PARENT NETDATA
#    THIS IS OPTIONAL - YOU DON'T HAVE TO CONFIGURE IT

# This section exists to give you finer control of the parent settings for each
# child host, when the same API key is used by many netdata child nodes / proxies.
#
# Each netdata has a unique GUID - generated the first time netdata starts.
# You can find it at /var/lib/netdata/registry/netdata.public.unique.id
# (at the child).
#
# The host sending data will have one. If the host is not ephemeral,
# you can give settings for each sending host here.

[MACHINE_GUID]
    # enable this host: yes | no
    # When disabled, the parent will not receive metrics for this host.
    # THIS IS NOT A SECURITY MECHANISM - AN ATTACKER CAN SET ANY OTHER GUID.
    # Use only the API key for security.
    enabled = no

    # A list of simple patterns matching the IPs of the servers that
    # will be pushing metrics using this MACHINE GUID.
    # The metrics are received via the API port, so the same IPs
    # should also be matched at netdata.conf [web].allow connections from
    # and at stream.conf [API_KEY].allow from
    allow from = *

    # The number of entries in the database
    history = 3600

    # The memory mode of the database: save | map | ram | none | dbengine
    memory mode = save

    # Health / alarms control: yes | no | auto
    health enabled = yes

    # postpone alarms when the sender connects
    postpone alarms on connect seconds = 60

    # need to route metrics differently?
    # the defaults are the ones at the [API KEY] section
    #proxy enabled = yes | no
    #proxy destination = IP:PORT IP:PORT ...
    #proxy api key = API_KEY
    #proxy send charts matching = *
```

All my other child nodes (4 of them) are configured the same way, the only differences are OS and kernel version.

**Comment by raduburla** [comment]
here is the output

```
{
	"version": "v1.23.2-151-nightly",
	"uid": "0f54a858-db15-11ea-a226-000c296c4f9c",
	"mirrored_hosts": [
		"atlassian"
	],
	"alarms": {
		"normal": 3,
		"warning": 0,
		"critical": 0
	},
	"os_name": "Debian GNU/Linux",
	"os_id": "debian",
	"os_id_like": "unknown",
	"os_version": "8 (jessie)",
	"os_version_id": "8",
	"os_detection": "/etc/os-release",
	"cores_total": "4",
	"total_disk_space": "214748364800",
	"cpu_freq": "2294000000",
	"ram_total": "6276067328",
	"container_os_name": "none",
	"container_os_id": "none",
	"container_os_id_like": "none",
	"container_os_version": "none",
	"container_os_version_id": "none",
	"kernel_name": "Linux",
	"kernel_version": "3.16.0-6-amd64",
	"architecture": "x86_64",
	"virtualization": "",
	"virt_detection": "systemd-detect-virt",
	"container": "unknown",
	"container_detection": "none",
	"host_labels": {
		"_os_name": "Debian GNU/Linux",
		"_os_version": "8 (jessie)",
		"_kernel_version": "3.16.0-6-amd64",
		"_system_cores": "4",
		"_system_cpu_freq": "2294000000",
		"_system_ram_total": "6276067328",
		"_system_disk_space": "214748364800",
		"_architecture": "x86_64",
		"_virtualization": "",
		"_container": "unknown",
		"_container_detection": "none",
		"_virt_detection": "systemd-detect-virt",
		"_is_parent": "false",
		"_streams_to": "ec2-ip-of-server.eu-west-1.compute.amazonaws.com:19996"
	},
	"collectors": [
		{
			"plugin": "tc.plugin",
			"module": ""
		},
		{
			"plugin": "idlejitter.plugin",
			"module": ""
		},
		{
			"plugin": "statsd.plugin",
			"module": "stats"
		},
		{
			"plugin": "cgroups.plugin",
			"module": "stats"
		},
		{
			"plugin": "proc.plugin",
			"module": "/proc/stat"
		},
		{
			"plugin": "netdata",
			"module": "stats"
		},
		{
			"plugin": "diskspace.plugin",
			"module": ""
		},
		{
			"plugin": "web",
			"module": "stats"
		}
	],
	"cloud-enabled": true,
	"cloud-available": true,
	"agent-claimed": false,
	"aclk-available": false
}
```

**Comment by mfundul** [comment]
The bug is probably caused by this label `"virtualization": ""`.

**Comment by mfundul** [comment]
> 
> 
> The bug is probably caused by this label `"virtualization": ""`.

@Ferroin @prologic this line:
https://github.com/netdata/netdata/blob/56bc902bc6e08d191be8ec8a2c7833f322773610/daemon/system-info.sh#L18
can lead to empty `VIRTUALIZATION` variable.

**Comment by prologic** [comment]
> can lead to empty `VIRTUALIZATION` variable.

We should probably default to "some" value. What though? `unknown`?

**Comment by mfundul** [comment]
> 
> 
> > can lead to empty `VIRTUALIZATION` variable.
> 
> We should probably default to "some" value. What though? `unknown`?

We can be consistent with the other place:
https://github.com/netdata/netdata/blob/56bc902bc6e08d191be8ec8a2c7833f322773610/daemon/system-info.sh#L30

**Comment by mfundul** [comment]
@raduburla can you test the pull request to see if your problem is fixed. You can compile netdata from source in your nodes by doing the following:

```git clone https://github.com/netdata/netdata.git
cd netdata/
git fetch origin pull/9715/head:PR9715
git checkout PR9715```
To get any additional changes from the PR if it's needed you'd have to run:

```git pull origin pull/9715/head```
from the same netdata/ directory.

To replace the existing installation you need to run the installer. Run those from the netdata/ directory:

```sudo ./netdata-installer.sh```

**Comment by prologic** [comment]
@mfundul And yes here:

https://github.com/netdata/netdata/blob/56bc902bc6e08d191be8ec8a2c7833f322773610/daemon/system-info.sh#L30

We have `none`.

So which do we want? `none` or `unknown`? 😀

**Comment by mfundul** [comment]
> 
> 
> @mfundul And yes here:
> 
> https://github.com/netdata/netdata/blob/56bc902bc6e08d191be8ec8a2c7833f322773610/daemon/system-info.sh#L30
> 
> We have `none`.
> 
> So which do we want? `none` or `unknown`? 😀

@amoss will answer this one. In my opinion though, `unknown` means something very different than `none`.

**Comment by prologic** [comment]
@mfundul https://github.com/netdata/netdata/pull/9716

**Comment by prologic** [comment]
> @amoss will answer this one. In my opinion though, unknown means something very different than none.

The _issue_ I have is that I'm not convinced we can reliably detect "no virtualisation at all" vs. "we just couldn't figure it out, but it might be" kind of thing.

**Comment by mfundul** [comment]
@raduburla no need to test the Pull Request anymore, it has been merged to master so you can use the one-line official installation method or wait for tomorrow for the nightly updates to be installed.

**Comment by raduburla** [comment]
@mfundul I just tested it, it works now :)
No empty host labels now

```
                "_virtualization": "unknown",
                "_container": "unknown",
```

Thank you
