### ISSUE TITLE
Optimise size of Docker Image

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#9664]
Recently the size of our Docker Image has increased from ~500MB to ~700MB.

- [Slack thread](https://netdata-cloud.slack.com/archives/CTGECGQMA/p1596497612040300)

Suspected cause: https://github.com/netdata/helper-images/pull/80

cc @amoss @ilyam8

**Comment by prologic** [comment]
Tried to utilise [docker-slim](https://github.com/docker-slim/docker-slim) today but unfortunately its a little too clever and doesn't really work out very well. It strips too much and doesn't have context on what needs to remain.

**Comment by Ferroin** [comment]
Closing this as it’s about as good as it can get without a significant redesign our how our Docker image works, which will be handled as a separate issue.
