### ISSUE TITLE
DEB/RPM CI build tests in Travis should not test i386

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#9665]
ssia

Mostly because the LXC images we use do not have `i386` images for some systems we do the RPM/DEB build test cycle on. The original intention was to only perform an RPM/DEB package build cycle test on only one system/arch each just as a way to ensure we don't break packaging.

**Comment by prologic** [comment]
Example failed job:

- https://travis-ci.com/github/netdata/netdata/builds/178487688
  - https://travis-ci.com/github/netdata/netdata/jobs/368469563

**Comment by Ferroin** [comment]
This should be fixed.
