### ISSUE TITLE
Netdata installation fails

### ISSUE THREAD

**Issue by ibyteapps** [netdata/netdata#9671]
##### Bug report summary

My netdata installation crashed today and it wouldn't let me browse to index page. After a few suggested solutions, I decided to start with a fresh install. So I uninstalled netdata and used kickstart. I got the following error during installation

/tmp/netdata-libwebsockets-1yhMPF/libwebsockets-3.2.2/include/libwebsockets/lws-genhash.h:79:18: error: field 'ctx' has incomplete type
         HMAC_CTX ctx;
                  ^
make[2]: *** [CMakeFiles/websockets.dir/lib/core/alloc.c.o] Error 1
make[1]: *** [CMakeFiles/websockets.dir/all] Error 2
make: *** [all] Error 2
 FAILED   

[/tmp/netdata]# mkdir -p /tmp/netdata/externaldeps/libwebsockets 
 OK   

[/tmp/netdata]# cp /tmp/netdata-libwebsockets-1yhMPF/libwebsockets-3.2.2/lib/libwebsockets.a /tmp/netdata/externaldeps/libwebsockets/libwebsockets.a 
cp: cannot stat '/tmp/netdata-libwebsockets-1yhMPF/libwebsockets-3.2.2/lib/libwebsockets.a': No such file or directory
 FAILED   

 FAILED  Failed to build libwebsockets. 

##### OS / Environment

```
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)
```

##### Steps To Reproduce

1. This is for a fresh install of netdata 
2. ...
<img width="1216" alt="Screenshot 2020-08-05 at 21 09 15" src="https://user-images.githubusercontent.com/10578050/89459050-f88bd500-d75f-11ea-9229-2cae7db226ab.png">

##### Expected behavior

I would like to have a working installation of netdata please.

**Comment by rymonroe** [comment]
I have a similar issue where I installed netdata last week without issue and just tried on machine with same specs and got error.

**Comment by Ferroin** [comment]
Do you possibly have multiple versions of OpenSSL installed? Usually stuff like this crops up when trying to build on a system which has multiple API incompatible versions of OpenSSL (for example, 0.9 and 1.1) installed at the same time.

**Comment by prologic** [comment]
@Ferroin is right and this is [documented here](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/source#linking-errors-relating-to-openssl) as such I am closing this issue. Please refer to the documentation. Alternatively please consider [Installing the static version](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64).
