### ISSUE TITLE
Netdata localization

### ISSUE THREAD

**Issue by LimeZky** [netdata/netdata#9672]
Hi there, I noticed that https://github.com/netdata/localization has been archived. It seems that Netdata stops localization. Why not start it again?

**Comment by LimeZky** [comment]
I am very willing to help with it.

**Comment by cakrit** [comment]
We're still making radical changes to our documentation, which inevitably affects any localization effort. We should revisit this when the bigger reorganization steps are completed.

**Comment by LimeZky** [comment]
OK, once the update completes, please contact me, I will help with the localization (Simplified Chinese). Besides, completed document can also be translated.

**Comment by joelhans** [comment]
@LimeZky Thanks for requesting to pitch in! While @cakrit is right that the docs are still undergoing some big changes, the bigger blocker to localization is that framework for the docs site doesn't yet support translations. They're working on it (see facebook/docusaurus#2651), but it may be a few more months until they merge the necessary code.

I'll close this for now, write your username down in my notes about localization, and ping you when we're ready.
