### ISSUE TITLE
Config files seems nonexistent

### ISSUE THREAD

**Issue by stemy2** [netdata/netdata#9673]
##### Bug report summary
I'd like to mute all alarms, but the config files mentioned in the doc doesn't exist.

##### OS / Environment
OS: Yunohost 4 (Based on Debian 10)
Kernel: 4.19.0-9-amd64

##### Netdata version
1.22.1
 

##### Component Name
Config files

##### Steps To Reproduce
1. Trying different methods to mute alarms mentioned in the doc.
2. The response is the same for all config files (netdata.api.key, alarm-notify.sh, netdata.conf): no such file or directory.

##### Expected behavior
Being able to find then modify the said config files to mute alarms.

**Comment by cakrit** [comment]
Please go through https://learn.netdata.cloud/guides/step-by-step/step-04 and let us know if you still aren't able to do this.

**Comment by stemy2** [comment]
I does not work, i have the message `connection failed`.

**Comment by stemy2** [comment]
I found 3 netdata.conf using the command find in CLI. Wich one is the right file ?

```
/tmp/tmp.iVm9kslHCo/system/netdata.conf
/opt/netdata/etc/netdata/netdata.conf
/etc/nginx/conf.d/netdata.stemy.me.d/netdata.conf
```

**Comment by ilyam8** [comment]
> /opt/netdata/etc/netdata/netdata.conf

this one
