### ISSUE TITLE
200 response code is red in web_log.detailed_response_codes

### ISSUE THREAD

**Issue by xPaw** [netdata/netdata#9674]
##### Bug report summary

On `response_statuses` and `response_codes` charts, the success/2xx code is using green color, but on `detailed_response_codes` chart, the 200 code is red, and 400 is yellow which is confusing.

![image](https://user-images.githubusercontent.com/613331/89506319-9b316b80-d7d3-11ea-89a0-74f7b9acf6fb.png)

##### Netdata version
netdata v1.23.2-131-nightly

##### Component Name
web ui

**Comment by ilyam8** [comment]
@xPaw this chart has dynamic dimensions - no dimensions on start, we add them (http resp codes) as they appear in the logs, so there is no predefined order, but color depends on the order.

**Comment by xPaw** [comment]
Hm, I thought so, but I never saw it be any other color over the years.

**Comment by ilyam8** [comment]
If you set `Setting=>Performance=>Which dimension to show?=>All` you will see that there is _green_ http code already.

**Comment by xPaw** [comment]
Indeed, I can see green being 101 code.

Does netdata have any mechanism for dimensions to suggest its color?

**Comment by ilyam8** [comment]
No, it doesnt.

I think it is possible to overwrite some parameters like color in [dashboard_info.js](https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info.js) but i am not sure.

You could set this option to `no`

https://github.com/netdata/netdata/blob/79c56b71c4567ce947e755b5fbe6d0b4eeffd046/collectors/python.d.plugin/web_log/web_log.conf#L70

If it is `no` you get 5 charts with detailes response codes - one for code family (1xx, 2xx, ...)

**Comment by ilyam8** [comment]
> Does netdata have any mechanism for dimensions to suggest its color?

@jacekkolasa if there is something please halp

**Comment by jacekkolasa** [comment]
> Does netdata have any mechanism for dimensions to suggest its color?

@xPaw No, unfortunately there is no option to specifically assign colors to dimensions. But if the order is always the same, you can override colors in dashboard_info.js, for example:

```
        colors: [NETDATA.colors[1], "#00FF00"], // get second color from the palette, and one custom color
```
