### ISSUE TITLE
kickstart-static64 --target ignores destination

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#9677]
##### Bug report summary
While I was testing  the installation using `netdata-v1.23.2-119-g0daf574d.gz.run` I observed that `--target` is ignored and by default it installs everything inside `opt`. The option `--target` only worked with relative paths, but it gives errors related `/opt/netdata`.

##### OS / Environment
```
Linux hades 5.4.55 #1 SMP Sat Aug 1 13:19:31 UTC 2020 x86_64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="14.2"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=14.2
/etc/os-release:PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
/etc/os-release:HOME_URL="http://slackware.com/"
/etc/os-release:SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:VERSION_CODENAME=current

```

##### Netdata version
1.23.2-119 

##### Component Name
Installer

##### Steps To Reproduce
1. Run `./netdata-v1.23.2-119-g0daf574d.gz.run --target`

##### Expected behavior
To have the final installation in the specified path.

**Comment by Ferroin** [comment]
This has been discussed before (though i do not recall where). Quite simply, we cannot support the `--target` option with the static install as we have to determine default paths at build time and the static install consists of an already built copy of Netdata.

The correct fix here is to remove the `--target` option from the static installer.

**Comment by prologic** [comment]
> The correct fix here is to remove the --target option from the static installer.

Does this _imply_ we would fork Makeself in some way or submit patches upstream to fix this for us?

**Comment by prologic** [comment]
I'm "Icing" this as it was reported internally and I _doubt_ any of our users really pay attention to the `--help` of the Makeself self-extracting archive or care too much to diddle with anything beyond just running `kigkstart-static64.sh` like our docs indicate.

**Comment by Ferroin** [comment]
> > The correct fix here is to remove the --target option from the static installer.
> 
> Does this _imply_ we would fork Makeself in some way or submit patches upstream to fix this for us?

I don't think so, I'm pretty sure it's our install code that's handling the option, not the makeself boilerplate code.

**Comment by Ferroin** [comment]
> I'm "Icing" this as it was reported internally and I _doubt_ any of our users really pay attention to the `--help` of the Makeself self-extracting archive or care too much to diddle with anything beyond just running `kigkstart-static64.sh` like our docs indicate.

Users have brought this up before, so there are some who are affected by it. I would have linked back to the prior issues about it, but can't seem to find them.

**Comment by Ferroin** [comment]
Closing as `wontfix` since we simply cannot fix it.
