### ISSUE TITLE
How do I get the target server system information like OS, Distro, Arch etc.

### ISSUE THREAD

**Issue by git1977** [netdata/netdata#9678]

**Comment by ilyam8** [comment]
Hi @git1977 


It is not on the dashboard, but you can get that info from `/api/v1/info` endpoint

**Comment by git1977** [comment]
Thank you. I am able to see all the detailed information on default port 19999.
In my scenario, I have connected netdata to promethues. Can I access this/similar information in promethues by any chance?

**Comment by ilyam8** [comment]
> Can I access this/similar information in promethues by any chance?

No, it is not possible. @vlvkobal correct me if i am wrong
