### ISSUE TITLE
Stable Docker Image

### ISSUE THREAD

**Issue by badi95** [netdata/netdata#9682]
Is there a stable tag for netdata docker images on dockerhub? I like to check for image updates for my containers regularly, but don't want to be running the nightly of netdata.

**Comment by prologic** [comment]
Yes. Use a tagged release.

**Comment by badi95** [comment]
The only options I see for tags on dockerhub are "latest", which is nightly, and specific versions like "v1.23.2". Is there a way to get the newest tagged release automatically like from a "stable" tag on dockerhub?

**Comment by ilyam8** [comment]
i think bash script will do

```cmd
0 ~ $ wget -q https://registry.hub.docker.com/v1/repositories/netdata/netdata/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}' | grep -o -E v[0-9.]+ | sort --version-sort --field-separator=- | uniq | tail -n 1
v1.23.2
```
