### ISSUE TITLE
How does netdata running inside a docker container send email notifications?

### ISSUE THREAD

**Issue by ovizii** [netdata/netdata#9689]
The reason I am asking is because I see this kind of errors in my netdata container lgos:

```
2020-08-07 12:11:44: alarm-notify.sh: WARNING: Cannot find file '/etc/netdata/health_alarm_notify.conf'.
sendmail: can't connect to remote host (127.0.0.1): Connection refused
2020-08-07 12:11:44: alarm-notify.sh: ERROR: failed to send email notification for: my.domain.tld net_drops.ens3.inbound_packets_dropped is WARNING to 'root' with error code 1.

```

##### OS / Environment
Debian 10
##### Expected results
Notification emails being sent

**Comment by thiagoftsm** [comment]
Hi @ovizii ,

You need to configure [health_alarm_notify.conf](https://learn.netdata.cloud/docs/agent/health/notifications/email) for Netdata sends email for a destination.

Best regards!

**Comment by ovizii** [comment]
thanks for the pointer but I need some more info. As I mentioned I am using netdata via docker setup like this: https://learn.netdata.cloud/docs/agent/packaging/docker and there is no mentioning of mounting a persistent volume which I assume I would need to provide health_alarm_notify.conf with the correct configuration. 

Any pointers how best to mount this? Or should I simply do this in my docker-compose.yml and edit that local conf file accordingly?:

```
volumes:
  -  /some/local/path/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf
```

**Comment by thiagoftsm** [comment]
@ovizii what you wrote makes sense to me, but I am not a docker specialist.
@ilyam8 can you confirm that to map the `health_alarm_notify.conf` is enough to have alarms working on docker? Is it also necessary to do some network configuration?

**Comment by ilyam8** [comment]
> sendmail: can't connect to remote host (127.0.0.1): Connection refused

Do you have mail server running on the host?

**Comment by ilyam8** [comment]
>  Or should I simply do this in my docker-compose.yml and edit that local conf file accordingly?:

Yes, dont edit it with `vim`, its default behavior is to create a file and replace the old one which changes inode. (changes are not propagaged if i remember it correctly).

**Comment by Ferroin** [comment]
As of https://github.com/netdata/helper-images/pull/82 being merged, we bundle msmtp in the Docker image in a way that allows Netdata to use it directly for email notification delivery. You will need to modify the `/etc/msmtrc` file in the container to correctly configure msmtp to relay to a valid mail server. The Arch Linux wiki has [a page about msmtp](https://wiki.archlinux.org/index.php/Msmtp) that provides good info on basic configuration.

**Comment by ovizii** [comment]
thanks for all the pointers, I will check it out this week. Let me close this thread for now although I will re-open it if I have more questions or post some final finding once I've got it running.

**Comment by juanvasquezreyes** [comment]
I was able to make it work by just putting the environment variable of my SMTP Server
example using docker-compose
environment:
      - SMTPHOST=x.x.x.x
