### ISSUE TITLE
Benchmarks analysis for Network Viewer

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#9690]
##### Feature idea summary
We need to determine the impact of the Network Viewer part of the eBPF plugin on CPU, memory resources and UI usage experience. Based on that information we should tune the Network Viewer module to provide maximum information without breaking Netdata usability.
- Check if UI is usable with different combinations of chart/dimension number. Find a limit when UI begins behaving in an undesirable way. Find if it's dependent on resources available to Netdata agent/browser. Measure the CPU load of the browser as well so that we can see how it degrades the system performance before it hits any complete failure.
- Measure CPU and memory usage for the eBPF plugin / Netdata agent when there are a lot of network connections established.
- Measure the CPU and memory usage on a lightly loaded system as well. We need to know how the CPU load scales up as the network traffic increases.

##### Expected outcome
- We should choose an approach for the creation of the charts (one chart with many dimensions / many charts with less dimensions / something in between).
- We should define caps for stored and displayed dimensions.
- We know how does the CPU load scale with network traffic. both in the collector and in the browser.
- We know what are the hard limits for displaying dimensions/charts in the dashboard.

**Comment by thiagoftsm** [comment]
Talking about the limits, last time that we talked about this I remember it was defined:

-  We will store for inbound and outbound dimensions in the format `destination port:PROTOCOL`
-  We have defined a limit to store connections and we were storing them using a kind of race condition. 

Should we think again about  the policy to store dimensions?
