### ISSUE TITLE
Security policy does not specify how non-netdata people can report vulnerabilities

### ISSUE THREAD

**Issue by joestringer** [netdata/netdata#9691]
It appears that the security policy as currently written requires an @netdata.cloud account on Google Groups to "create a post". When following the link on the [security page](https://github.com/netdata/netdata/security/policy) (https://groups.google.com/a/netdata.cloud/forum/#!newtopic/security), users not signed in with such an account are directed to an authorization page:

![image](https://user-images.githubusercontent.com/1243336/89678467-0d718100-d8a4-11ea-8d21-77329e2068b1.png)

The process should clearly explain how external users may report vulnerabilities, whether this involves signing up for an account or reporting via another mechanism. The posts there should of course not be visible to those outside the security group or reporter.

**Comment by cakrit** [comment]
Thanks for the report, the fix is in #9696
