### ISSUE TITLE
Is there a way to open port 19999 automatically during installation

### ISSUE THREAD

**Issue by git1977** [netdata/netdata#9692]
Can we open automatically the needed port(default 19999) during netdata installation?

**Comment by ilyam8** [comment]
> open automatically the needed port

@git1977 what do you mean? Open where?

**Comment by ilyam8** [comment]
You mean some firewall?

**Comment by git1977** [comment]
I have my machine on AWS EC2. I am thinking if there is a way to open the port 19999 automatically without doing it manually on AWS security group.

**Comment by ilyam8** [comment]
No, i dont think we can do it during install. I suggest to ask aws support.
