### ISSUE TITLE
Directory structure has been changed in LXC 4.0

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#9697]
Posted in "No longer getting all metrics from LXD containers after switch to Snap", but defines a new issue:

This issue has now reverted for me, as of a few versions ago. I am up to date on `v1.23.1-77-g013c9da6` and seeing the exact same symptoms as before.

I am also seeing lots of the error messages in my error log you refer to earlier:

`2020-07-13 12:45:06: netdata INFO  : PLUGIN[cgroups] : CGROUP: maximum number of cgroups reached (1000). Not adding cgroup '/lxc.payload.xxxx/system.slice/console-setup.service'`

Has your code been reverted / removed from the latest Netdata versions?!

_Originally posted by @Kramerican in https://github.com/netdata/netdata/issues/6481#issuecomment-657500941_

**Comment by vlvkobal** [comment]
Directory structure [has been changed](https://linuxcontainers.org/lxc/news/#major-changes) since LXC 4.0

**Comment by vlvkobal** [comment]
@Kramerican @webdock-io, #9645 is ready. You can build Netdata from source and test it.
```
git clone git://github.com/vlvkobal/netdata.git --branch fix-ignored-lxc
cd netdata
sudo ./netdata-installer.sh
```

**Comment by Kramerican** [comment]
@vlvkobal It works almost perfectly.! I have sent you an email with some comments / questions regarding a few metrics which I can no longer find. But in general this seems to work
