### ISSUE TITLE
Disk space utilization for LXD storage pools no longer present (LXD 4.2)

### ISSUE THREAD

**Issue by Kramerican** [netdata/netdata#9699]
I cannot find disk space utilization anymore - before we could access disk utilization with:

`disk_space._var_lib_lxd_storage_pools_lxd_containers_CONTAINERNAME`

But I cannot for the life of me find storage pools anywhere on the latest LXD and latest Netdata

**Comment by vlvkobal** [comment]
The diskspace plugin monitors the disk space usage of mounted disks. You don't have `/var/lib/lxd/` in your system and you [don't have mountpoints for your containers](https://discuss.linuxcontainers.org/t/rootfs-mount-locations-on-the-host-with-snap-lxd/2390/4) anymore. You can check it by running the `mount` command.

Please look at ["How to view the files of your LXD container from the host"](https://blog.simos.info/how-to-view-the-files-of-your-lxd-container-from-the-host/). Does it help you?
