### ISSUE TITLE
[Bug]: Systemd service file should properly honor what user Netdata is configured to run as.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#9701]
Currently, the systemd unit files we install blindly assume that the Netdata user and group names are `netdata`. While this works for the common case, it fails horribly in two cases:

* The user has installed with different username for the `netdata` user.
* The user has configured Netdata to run as a different user than the `netdata` user.

A reliable solution to this is non-trivial, and probably involves having Netdata itself handle switching to the user it's supposed to run as instead of having systemd do so prior to running Netdata.

**Comment by prologic** [comment]
> The user has installed with different username for the netdata user.
> The user has configured Netdata to run as a different user than the netdata user.

Can we just simply not allow this in the first place? cc @amoss -- I find allowing "to much" flexibility to be problematic here honestly. It unnecessarily complicates what we have to support and the packaging/ci and testing code/infra we have to write and maintain.

**Comment by prologic** [comment]
I also wouldn't call this a "bug" per se so have categorised as an "enhancement". Its really a missing feature of how we package/ship the SystemD Unit.

**Comment by Ferroin** [comment]
No, this is a bug, we currently support both of these configurations, but do not work correctly in either of them without further user intervention.

Just having Netdata be responsible itself for dropping to the correct user account, always starting it as root, and then making it create the directories it needs if they aren't there (like it should be doing anyway) should fix this, it's just not something we can trivially fix with packaging changes.

**Comment by prologic** [comment]
Fine 👍

**Comment by amoss** [comment]
I agree that it is a bug - if we support the option to change the username then we have to support it everywhere.

**Comment by cpipilas** [comment]
@Ferroin It's a bug and needs to be fixed. Let's add in our backlog for proper grooming/sizing since to my understanding we are talking about horizontal changes in the agent.

**Comment by Ferroin** [comment]
On further inspection, this doesn’t appear to need any changes to the agent code to be fixed, but the relevant agent code could use a bit of cleanup for sanity reasons so I’ll take care of that at the same time.
