### ISSUE TITLE
netdata.spec: libbpf is bundled even though it is disabled at compile time

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#9705]
##### Bug report summary
When bundling for RHEL6, the specfile does not check if EBPF is available and fails to compile it.
In more recent versions the collector should not be available (from config) but still manages to compile and get packaged.

##### OS / Environment
RHEL6.10. Should be appliable to all redhat versions

##### Netdata version
v1.24.0

##### Component Name
netdata.spec.in

##### Steps To Reproduce

1. Use a RHEL6 environment with latest netdata version
2. ensure you don't have either package `elfutils-libelf-devel` or `bpftool`
3. launch `contrib/rhel/build-netdata-rpm.sh

##### Expected behavior
If `configure` detects EBPF is not avaiable, do not reference it in the specfile, and do not try to compile it. 
Unfortunately, it seems not to be an option available to completely disable ebpf at compile time (like nfacct or freeipmi)

**Comment by prologic** [comment]
@thiagoftsm Can you handle making the build tooling changes here?

**Comment by Saruspete** [comment]
Sorry, forgot to push the associated PR.
