### ISSUE TITLE
Health stopped working

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#9706]
##### Bug report summary
While I was testing the PR #9698 I observed that initially I did not receive any alarm. After this I decided to clean up the `dbengine` files and starting my tests again, it worked during few hours, but after I change from a branch to another and recompile I stopped to receive any alarm.

In the first time that the problem happend, I observed that I had thousands of errors like this:

```
Ignoring metric with out of order timestamp
``` 

but, when the problem happens again, I did not receive more this error message.

##### OS / Environment
```
Linux hades 5.4.57 #1 SMP Sat Aug 8 12:10:00 UTC 2020 x86_64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="14.2"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=14.2
/etc/os-release:PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
/etc/os-release:HOME_URL="http://slackware.com/"
/etc/os-release:SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:VERSION_CODENAME=current
```

##### Netdata version
netdata v1.24.0-8-ga15e450e2
 

##### Component Name
Health
Dbengine

##### Steps To Reproduce
1. Start Netdata
2. Configure an alarm, for example:

```
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -3s at 0 every 3 percentage foreach *
 units: %
 every: 10s
  warn: $this > 1
  crit: $this > 4
```
3. Stop Netdata ( I did not test sending -USR2, all the problems happening when I was stopping Netdata, recompiling and starting it again)
4. Verify alarms and logs.

##### Expected behavior
To have alarms running, independent of the Netdata version or branch, on my case, I used the cited PR and the master branch, and I had problems with both.

**Comment by stelfrag** [comment]
@thiagoftsm  How did you recompile

**Comment by thiagoftsm** [comment]
I always compile using the following command line:

```
CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-lto --dont-wait --dont-start-it
```

**Comment by stelfrag** [comment]
I verified that the alarm is not triggered (as you described). The USR2 signal (health reload) 'fixes' it without restart but it looks like a bug

**Comment by stelfrag** [comment]
The bug was introduced in 1.23.2 when trying to defer health configuration for archived charts
