### ISSUE TITLE
When behind a filtering proxy, react-dashboard hangs for 90sec before showing graphs

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#9708]
##### Bug report summary
When using 1.24 behind a filtering proxy, the new react dashboard loads the chart definition, is still responsive, but the charts data doesn't load before the query to "app.netdata.cloud" finishes (after 90seconds). Also the buttons "+" and some other are broken (they don't react at all).

This also fails if netdata was configured with --disable-cloud 

Note: I don't see the query as "pending" in the network debug tab.. 

When keeping the old dashboard, the problem does not arise.

##### OS / Environment
Linux RHEL 7.7

##### Netdata version
1.24.0 

##### Component Name
React-dashboard 

##### Steps To Reproduce

1. Install the new react-dashboard
2. Drop the connection to app.netdata.cloud, eg with iptables: `sudo iptables -A OUTPUT -d app.netdata.cloud -j DROP`
3. reload the dashboard

##### Expected behavior
The charts should load, whether the connection to app.netdata.cloud is working or not.
The buttons requiring the cloud should be greyed, or fully disabled if netdata is build with "--disable-cloud".

**Comment by prologic** [comment]
@jacekkolasa Please take a look at this ☝️

**Comment by jacekkolasa** [comment]
thanks @Saruspete! I see there is an issue when the private registry is setup and it's not reachable. Can you please check if you have changed the default registry? (`registry to announce` field in netdata.conf). Can you check if any other calls are pending in your case?

**Comment by Saruspete** [comment]
Hi @jacekkolasa  !
we didn't change the default registry, but disabled it (`[registry] enabled = no`). Our proxy is kinda restrictive and sometimes doesn't refuse properly (eg with 403) urls.
In the "network" tab of the browser debugger, it's the "app.netdata.cloud" that is taking 90sec, matching the delay I had with the rendering of graphs. 

Also, the cloud related features, like the options / "3 lines" button on the right of "Netdata" logo is kept blank, without error message, and the green "+" button is inactive too, but not greyed/disabled.

**Comment by jacekkolasa** [comment]
hi @Saruspete , i still haven't been able to reproduce your issue. I assume that you've checked that there are no other calls that take the same amount of time? (90s). I've applied a fix (here)[https://github.com/netdata/netdata/pull/9786] to newest Netdata that can help in one case. Can you please check if reinstallation helps?

**Comment by Saruspete** [comment]
Yeah, checked no other call was in progress, with firefox & chromium.

I'm out of office and cannot test before end of month, but will ask a colleague to try in the meantime. I'll be able to gather more details when back at the office.

**Comment by Saruspete** [comment]
Seems to have fixed the issue.

Thanks a lot @jacekkolasa !

**Comment by jacekkolasa** [comment]
Great news @Saruspete , thanks for your help on this issue!
