### ISSUE TITLE
Changing installation directory

### ISSUE THREAD

**Issue by git1977** [netdata/netdata#9710]
Looks like netdata installs in /opt/ directory. Is there any option to change it to /etc/ directory?

**Comment by thiagoftsm** [comment]
Hi @git1977 ,

How are you installing Netdata? When we compile the branch, we can pass as argument the option `--install /opt`, the command would be:

```
./netdata-installer.sh --install /opt
```

Considering that you said that by default it installs on `/opt`, I will assume that you are using another Netdata script, so you can also try the option `--target` to specify a destination.

Best regards!

**Comment by git1977** [comment]
@thiagoftsm Thank you
