### ISSUE TITLE
Unknown HTTP error during Cloud Claim

### ISSUE THREAD

**Issue by smilebasti** [netdata/netdata#9719]
I am having the same issue as #9506. As it was closed i opened this new one.

I ran the automatic one-line installation script on one server which runs Ubuntu 18.04. During the installation i did not have any Errors. Afterwards i created my Cloud-Access on wanted to claim my first Node by copying and pasting the code. 

During the claim i got the Error: Failed to claim node with the following error message:"Unknown HTTP error message"
After it lists Token,Base Url, Id, Rooms, Hostname, Proxy and Netdata user.

netdata -v shows v1.24.0. During installation also have chosen the stable version.
Is there already a solution for this or where can i grab the log-files?
Thanks ahead

**Comment by prologic** [comment]
Are we able to see the full output/logs please as well as the `/var/log/netdata/error.log` -- maybe `grep -i aclk`. Please don't include your tokens in the output 👍 cc @amoss

**Comment by smilebasti** [comment]
Ok after a reboot it showed it was already claimed after i tried to claim it again.
I resolved it by unclaiming it and reclaiming the node. Now it worked and it shows up in the Warroom.
