### ISSUE TITLE
From metric name, is there a general logic to grab the unit?

### ISSUE THREAD

**Issue by git1977** [netdata/netdata#9720]
From netdata metric name, I am trying to grab the unit dynamically. I see that it is mostly the last word. Is it reliable way of doing this or may be there is another logic which is out there.

**Comment by prologic** [comment]
@ilyam8 ☝️

**Comment by git1977** [comment]
> I think it depends on [exporting connector](https://learn.netdata.cloud/docs/agent/exporting), @git1977 what do you use?

I am using prometheus.

**Comment by ilyam8** [comment]
@vlvkobal for some reason we dont add `units` if `as-collected`

example

https://github.com/netdata/netdata/blob/75a56ff0b241910eefad68c87b3f95fe786ebd2d/exporting/prometheus/prometheus.c#L592-L618
