### ISSUE TITLE
How to programatically check if installation is successful and metrics are emitted by netdata

### ISSUE THREAD

**Issue by git1977** [netdata/netdata#9723]
I have written a small bash script which calls netdata script(kickstart.sh). I would like to programmatically check whether netdata installation is successful and metrics are being successfully emitted on 19999. I am using the following command to check, but getting a 400 bad request.
Please help.

`curl -I http://localhost:19999`

Response:
`HTTP/1.1 400 Bad Request`

**Comment by stelfrag** [comment]
Hi @git1977 

Similar to what you have written the following will display the last 5 seconds of metrics collection on the `system.cpu` charts dimension `user`

```
curl  http://localhost:19999/api/v1/data?chart=system.cpu\&after=-5\&dim=user
```

Example output
```
{
 "labels": ["time", "user"],
    "data":
 [
      [ 1597208452, 0.5025126],
      [ 1597208451, 1.889893],
      [ 1597208450, 1.4178482],
      [ 1597208449, 0.505476],
      [ 1597208448, 1.1904762]
  ]
}
```

would what be helpful?

**Comment by git1977** [comment]
yes that command works, but in bash script how to gab that command and programmatically determine that there is valid output which indirectly tells metrics are accessible so installation and configuration went all well.

**Comment by ilyam8** [comment]
We use `/api/v1/info` for liveness and readiness probing in k8s

https://github.com/netdata/helmchart/blob/9dfcf366f973edb450b1f08295306a6ea2f6b66c/templates/deployment.yaml#L85-L96

**Comment by Ferroin** [comment]
> > so installation and configuration went all well.
> 
> `/api/v1/info` will do
> 
> We use `/api/v1/info` for liveness and readiness probing in k8s
> 
> https://github.com/netdata/helmchart/blob/9dfcf366f973edb450b1f08295306a6ea2f6b66c/templates/deployment.yaml#L85-L96

We also use the same endpoint for health checks in our Docker images, and it's what I would personally recommend using for checking that Netdata is running. However, if you want ot actually ensure data is being collected and that the dashboard is being served correctly, you will need to use other endpoints.

**Comment by git1977** [comment]
Thank you guys.
