### ISSUE TITLE
High CPU usage by netdata after upgrade from 1.23 to 1.24

### ISSUE THREAD

**Issue by Mic-Pod** [netdata/netdata#9727]
##### Bug report summary
High CPU usage by netdata after upgrade from 1.23 to 1.24 (stable channel). Top show that ebpf.plugin is responsible for this.

##### OS / Environment
Ubuntu Server 18.04.5 LTS
Netdata installed via bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel

##### Netdata version
v1.24.0

##### Component Name
ebpf.plugin

##### Steps To Reproduce
Screen from prometheus shows increased usage of CPU by netdata after upgrade to 1.24. After netdata service restart, it's better for a moment but after some time CPU usage is high again.
##### Expected behavior
CPU usage was lower before upgrade to 1.24
![netdata_2](https://user-images.githubusercontent.com/57563877/89994475-78e29680-dc88-11ea-8d91-b15b5fd30739.jpg)
![netdata_1](https://user-images.githubusercontent.com/57563877/89994483-7a13c380-dc88-11ea-9bd4-5f9bfd650828.jpg)

**Comment by vlvkobal** [comment]
Related but are discussed in a wrong issue
https://github.com/netdata/netdata/issues/8242#issuecomment-668397894
https://github.com/netdata/netdata/issues/8242#issuecomment-669988930

**Comment by doodie** [comment]
same issue here.

OS - CentOS Linux release 7.7.1908 (Core)
Netdata - netdata v1.24.0-35-nightly
install - bash <(curl -Ss https://my-netdata.io/kickstart.sh)

<img width="516" alt="Screen Shot 2020-08-14 at 8 04 41 AM" src="https://user-images.githubusercontent.com/1712241/90264680-4f4f7980-de06-11ea-9471-4e6d8c392a84.png">
<img width="935" alt="Screen Shot 2020-08-14 at 8 15 02 AM" src="https://user-images.githubusercontent.com/1712241/90264695-524a6a00-de06-11ea-8a37-ba702de3642c.png">

**Comment by thiagoftsm** [comment]
Hi @doodie ,

I merged a PR now that can fix this problem on CentOS 7.x, tomorrow after the nightly to be released, this should be fixed, please, let us know if this does not happen.

Best regards!

**Comment by doodie** [comment]
@thiagoftsm ,

confirming that the nightly build fixed the issue for myself. CPU is now around the low single digits.

Thanks.

**Comment by thiagoftsm** [comment]
Thank you to confirm @doodie, I am closing this issue now, please, be free to reopen if the problem appears again.
