### ISSUE TITLE
using dbengine multihost results in connection/data loss to children as a result of "too slow disk"

### ISSUE THREAD

**Issue by svrnwnsch** [netdata/netdata#9730]
##### Bug report summary

We have a Parent where 37 children are streaming around 3700 metrics each 2 seconds to parent. With the old dbengine setup per child everything is working fine. After upgrading to 1.24 and deleting the old db cache we now had problems and alerts lik "ipv4 tcphandshake last collected secs = 00:02:10 ago" for many children periodically after ~20 minutes. Looking into the dbengine netdata metrics revealed that the parent reported at the same time that the disk was to slow to write all metrics from the dbengin to disk. At the same time and during the time where data was not gather from children, netdata reported higher CPU usage.

My assumptions is now that before, each dbengin wrote to disk a different times smaller size of data and the disk was fast enough for netdata to write everything, and with the new single dbengine the data is now written at the same time which causes problems on netdata side.

To mitigate the data loss we reverted back to 1.23.2 on the parent. All children continue running on 1.24.0 (stable release channel)

##### OS / Environment

netdata in docker container on ubuntu server

##### Netdata version

1.24.0 docker
 

##### Component Name

dbengine

##### Steps To Reproduce

1. ...
2. ...

##### Expected behavior

Keep the same disk/io requirements for new dbengine which worked with old seperated dbengins.

**Comment by mfundul** [comment]
May be related to #https://github.com/netdata/netdata/issues/8384

Can you share your `var/log/netdata/error.log*` files? You may send them to me at markos@netdata.cloud if you don't want them to be public.

**Comment by svrnwnsch** [comment]
I looked into the nedata docker container:
```

**Comment by amoss** [comment]
The container wires the logs to `stdout` so that the logging is handled by docker on the host instead of inside the container. You can then retrieve from docker using something like (assuming your container name):
```
docker logs netdata >error.log 2>&1
```

**Comment by svrnwnsch** [comment]
I updated the parent server to docker hubs `netdata:latest` and I can confirm that the problem no longer exists.

**Comment by amoss** [comment]
Good news. @mfundul will be happy to hear it when he returns next week.
