### ISSUE TITLE
Bandwidth template of net interface is no longer available?

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#9731]
![image](https://user-images.githubusercontent.com/22472752/90020083-ef5fb280-dce1-11ea-9553-50c6144b3867.jpeg)

As above the bandwidth measurement of network interface is the indicator to show how many traffic is flowing through the interface.

A few month ago, this parameter is available in the alarm list, but no longer there any more`netdata v1.24.0-10-nightly`:

**Comment by cakrit** [comment]
@startryst where do you see it missing? I see the required variables when I do e.g. https://frankfurt.my-netdata.io/api/v1/alarm_variables?chart=net.eth0 (that's running v1.26)
