### ISSUE TITLE
Coverity Defect CID 361262

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#9735]
#### Summary
When a new dimension is created under a chart it must be properly configured so that it can part of the health system so that it can be used in alarms etc.

Currently we do not do the configuration if the dimension is in archive mode. The configuration is done when a dimension switches to non-archive, active mode.

This causes performance/scaling issues because right now the configuration function needs to hold a host lock for each dimension that needs to be configured.

The lock sequence right now looks like this:

- Chart lock
- Attempt host lock
  - Lock acquired
    - Configure dimension
    - Release host lock
  - Lock failed after a timeout
    - Skip the configuration
- Release chart lock

Note that the dimension is not configured if the host lock fails

---

We need a way to record the dimensions that need to be configured and do the configuration outside the dimension creation/activation function.

**Comment by amoss** [comment]
Options here include:
* Backing out of the host lock and reacquiring the locks in the correct order (moving the flag changes onto the appropriate code paths at the right time).
* Adding a fine-grained lock for accessing the calculation variables (and updating the other access sites in the code to use it).
