### ISSUE TITLE
Data endpoint returns data for parent node instead of child

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#9739]
#### Summary

Due to possibly an internal state corruption in a multidb environment

##### Initial state

- Parent node **futura**
- Child node **alpine**
- Parent node is down
- Child node is down

- Starting parent
- Access **localhost:19999/host/alpine/archivedcharts**
  - Charts are present in archived mode (as they should be)

- Access **localhost:19999/host/alpine/api/v1/data?chart=system.cpu**
  - The endpoint delivers updated metrics for the parent node

The ***localhost:19999/host/alpine/api/v1/data?chart=system.cpu*** should not deliver updated metrics at all 

The error.log has a lot of **Ignoring metric with out of order timestamp.** entries

**Comment by mfundul** [comment]
Did randomly reproduce it once yesterday but I have failed to recreate the conditions since.

**Comment by mfundul** [comment]
Fixed by https://github.com/netdata/netdata/pull/9855
