### ISSUE TITLE
Delete unreachable node from room

### ISSUE THREAD

**Issue by Zorgji** [netdata/netdata#9741]
```
I've installed netdata on k8s cluster and pushed to netdata cloud. It's all doing well!
I've been testing with a few clusters but how can I remove unreachable ones?
```

![Screen Shot 2020-08-13 at 7 18 50 PM](https://user-images.githubusercontent.com/36134132/90136711-9e5fc500-dd9a-11ea-900f-030a99b09f4d.png)

**Comment by Zorgji** [comment]
![Screen Shot 2020-08-27 at 12 54 15 AM](https://user-images.githubusercontent.com/36134132/91341702-ea315600-e7ff-11ea-9b41-01aeee42c284.png)
```
Now It's solved. Thanks!
```

**Comment by bakhtiyarsierad** [comment]
how to fix this? can share to me?

**Comment by MrZammler** [comment]
Hi @bakhtiyarsierad !

In the cloud interface, go to the room you want to remove nodes from it.

In the upper left corner, click on the pull-down menu, and select `List Nodes`. It will open up a list with all the nodes in the room, and you can select which ones to remove:

![image](https://user-images.githubusercontent.com/1905463/144995880-1464fd56-992b-4211-9824-30a8776e4ffa.png)

Click on the trashcan icon you will find next to a node to remove it.

**Comment by cakrit** [comment]
See https://github.com/netdata/netdata/issues/9358#issuecomment-1199437124 for the latest update on this.
