### ISSUE TITLE
python.d.plugin ignores SIGPIPE

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#9742]
##### Bug report summary
While I was debugging the issue #9342 I have observed that every time `Netdata` was crashing, `python.d.plugin` is never closing, this means that this plugin is not considering SIGPIPE.

##### OS / Environment
```
Linux hades 5.4.58 #1 SMP Wed Aug 12 10:47:14 UTC 2020 x86_64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz GenuineIntel GNU/Linux
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="14.2"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=14.2
/etc/os-release:PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
/etc/os-release:HOME_URL="http://slackware.com/"
/etc/os-release:SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:VERSION_CODENAME=current
```

##### Netdata version
netdata v1.24.0-26-gd897c6512
 

##### Component Name
python.d.plugin

##### Steps To Reproduce

1. Start Netdata configured with dbengine an an alarm that is raised with a high frequency, for example

```
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -1s percentage foreach *
 units: %
 every: 1s
  warn: $this > 1
  crit: $this > 4
```
2. Send the command `killall -USR2 netdata` at least 4 times.

##### Expected behavior
If Netdata crashes, `python.d.plugin` cannot continue as a zombie process.

**Comment by ilyam8** [comment]
> If Netdata crashes

it does not. Debian 10 droplet on DO.

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ /opt/netdata/usr/sbin/netdata  -v
netdata v1.24.0-30-g1d4c8a4

ilyam@debian-s-1vcpu-1gb-fra1-01:~$ cat /opt/netdata/etc/netdata/health.d/test.conf
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -1s percentage foreach *
 units: %
 every: 1s
  warn: $this > 1
  crit: $this > 4

ilyam@debian-s-1vcpu-1gb-fra1-01:~$ ps aux | grep netdata
netdata  18562  1.9  8.1 272824 83392 ?        Ssl  18:01   0:04 /opt/netdata/usr/sbin/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D
netdata  18666  0.9  0.4  37488  4676 ?        S    18:01   0:02 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1 no-groups no-users
netdata  18667  0.6  2.1 725188 21660 ?        Sl   18:01   0:01 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata  18668  0.2  0.3  10224  3472 ?        S    18:01   0:00 bash /opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin 1
netdata  18669  0.6  5.1 107032 53028 ?        Sl   18:01   0:01 /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1

ilyam    20018  0.0  0.0  12716   972 pts/0    S+   18:05   0:00 grep netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ sudo killall -USR2 netdata

ilyam@debian-s-1vcpu-1gb-fra1-01:~$ ps aux | grep netdata
netdata  18562  2.0  8.1 272984 83656 ?        Ssl  18:01   0:04 /opt/netdata/usr/sbin/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D
netdata  18666  0.9  0.4  37488  4676 ?        S    18:01   0:02 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1 no-groups no-users
netdata  18667  0.6  2.1 725188 21660 ?        Sl   18:01   0:01 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata  18668  0.2  0.3  10224  3472 ?        S    18:01   0:00 bash /opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin 1
netdata  18669  0.6  5.1 107032 53028 ?        Sl   18:01   0:01 /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
ilyam    20053  0.0  0.0  12716   936 pts/0    S+   18:05   0:00 grep netdata
```

**Comment by ilyam8** [comment]
```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ for i in $(seq 1 50); do sudo killall -USR2 netdata; done
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ ps aux | grep netdata
netdata  18562  0.8  8.2 273592 84184 ?        Ssl  18:01   0:07 /opt/netdata/usr/sbin/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D
netdata  18666  0.9  0.4  37488  4676 ?        S    18:01   0:08 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1 no-groups no-users
netdata  18667  0.5  2.2 725188 22788 ?        Sl   18:01   0:04 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata  18668  0.2  0.3  10224  3472 ?        S    18:01   0:02 bash /opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin 1
netdata  18669  0.3  5.1 107032 53028 ?        Sl   18:01   0:02 /usr/bin/python /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1
ilyam    20919  0.0  0.0  12716   936 pts/0    S+   18:16   0:00 grep netdata
```

**Comment by thiagoftsm** [comment]
A suggestion, add a sleep command to have time to raise alarms. In my case I was sending -USR2 once per minute.

**Comment by ilyam8** [comment]
It is not in the OP

> Send the command killall -USR2 netdata at least 4 times.

Can you provide exact command/script to trigger the issue?

**Comment by thiagoftsm** [comment]
> Can you provide exact command/script/sequence to trigger the issue?

Yes, let's go by steps:

1 - I am using the following alarm:

```
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -1s percentage foreach *
 units: %
 every: 1s
  warn: $this > 1
  crit: $this > 4
```

2 - I start the `parent` with at least 1 `child` connected to it.
3 - I run the following script after one minute running:

```
bash-5.0# for i in `seq 1 10`; do curl -o stable http://localhost:19999/host/zeus/api/v1/data?chart=system.cpu ;  killall -USR2 netdata ; sleep 60 ; done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   449  100   449    0     0   438k      0 --:--:-- --:--:-- --:--:--  438k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   449  100   449    0     0   438k      0 --:--:-- --:--:-- --:--:--  438k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   449  100   449    0     0   438k      0 --:--:-- --:--:-- --:--:--  438k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   449  100   449    0     0   438k      0 --:--:-- --:--:-- --:--:--  438k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 19999: Connection refused
netdata: no process found

^C
bash-5.0# ps aux| grep netdata
thiago   15275  0.2  0.3  61616 28508 ?        Sl   20:30   0:01 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
root     19976  0.0  0.0   6692  2836 pts/3    S+   20:36   0:00 grep netdata
```

As you can see on my computer, after Netdata crashes due spawn server, I only have `python.d.plugin` the remaining process were closed when they received `SIGPIPE`.

**Comment by ilyam8** [comment]
Do i really need parent/child setup?

> thiago   15275  0.2  0.3  61616 28508 ?        Sl   20:30   0:01 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1


Why the user is `thiago`?

**Comment by thiagoftsm** [comment]
> Do i really need parent/child setup?

No it is possible to crash spawn server with only one Netdata, the requirement is an alarm that is raising many times during a minute.

> Why the user is thiago?

To simplify my life while I am working with Netdata.

**Comment by ilyam8** [comment]
>  is an alarm that is raising many times during a minute.

didnt really work for me https://github.com/netdata/netdata/issues/9742#issuecomment-673629368

> To simplify my life while I am working with Netdata.

I try to reproduce exactly same conditions, it is hard because of lack of details in OP

**Comment by ilyam8** [comment]
ok, `60` is to long, i made it `5`

```cmd

$ cat /opt/netdata/etc/netdata/health.d/temp.conf
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -1s percentage foreach *
 units: %
 every: 1s
  warn: $this > 1
  crit: $this > 4
```

```cmd
$ for (( i=1; ; i++ )); do curl -s -o stable http://localhost:19999/api/v1/data?chart=system.cpu; CURL_RET=$?; echo "TICK $i: $CURL_RET"; killall -USR2 netdata ; sleep 5 ; done
TICK 1: 0
TICK 2: 0
TICK 3: 0
TICK 4: 0
TICK 5: 0
TICK 6: 0
TICK 7: 0
TICK 8: 0
TICK 9: 0
TICK 10: 0
TICK 11: 0
TICK 12: 0
TICK 13: 0
TICK 14: 0
TICK 15: 0
TICK 16: 0
TICK 17: 0
TICK 18: 0
TICK 19: 0
TICK 20: 0
TICK 21: 0
TICK 22: 0
TICK 23: 0
TICK 24: 0
TICK 25: 0
TICK 26: 0
TICK 27: 0
TICK 28: 0
TICK 29: 0
TICK 30: 0
```

---

cant reproduce, my distro is manjaro, latest netdata

**Comment by thiagoftsm** [comment]
I will verify with other distribution and update the information here.

**Comment by amoss** [comment]
Is there any progress on finding a way to reproduce this or should it be closed?

**Comment by ilyam8** [comment]
I know that `python.d.plugin` has keepalive func and it writes `\n` every second, and i rememeber i added it to fix exactly this issue and it was fixed.

I could reproduce it, i [couldnt even reproduce](https://github.com/netdata/netdata/issues/9742#issuecomment-674544440) `netdata` crash sending `USR2`.

**Comment by thiagoftsm** [comment]
@ilyam8 I am attaching my current [alarm log](https://github.com/netdata/netdata/files/5105366/db.zip) that will help you to recreate the problem.  To create the problem I used the following alarms:

```
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -3s at 0 every 3 percentage foreach *
 units: %
 every: 1s
  warn: $this > 1
  crit: $this > 4
```

and

```
alarm: example_alarm1
      on: example.random
   every: 2s
    warn: $random1 > (($status >= $WARNING)  ? (55) : (75))
    crit: $random1 > (($status == $CRITICAL) ? (75) : (95))
    info: random
      to: sysadmin

alarm: example_alarm2
      on: example.random
   every: 2s
    warn: $random2 > (($status >= $WARNING)  ? (55) : (75))
    crit: $random2 > (($status == $CRITICAL) ? (75) : (95))
    info: random
      to: sysadmin
```

We discovered that while I was working to create the PR #9773 that the problem happens when Netdata tries to schedule a command that was never executed when it is updating the alarm log. You need to load an alarm log that has stored flags that will force Netdata to reschedule a command that was never scheduled during the current runtime.

Today I had the same problem, because the PR was not merged:

```
bash-5.0$ for i in `seq 1 10`; do killall -USR2 netdata ; sleep 60 ; done
netdata: no process found
^C
bash-5.0$ ps aux| grep netdata
thiago    3690  0.3  0.3  69800 28516 ?        Sl   20:15   0:00 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
thiago    4673  0.0  0.0   6692  2748 pts/3    S+   20:18   0:00 grep netdata
```

If you  cannot recreate the problem running Manjaro, this can mean that probably there was an update for newest kernels when some crash happens, I tested on kernel 5.4.59 and olders.

**Comment by ilyam8** [comment]
> You need to load an alarm log that has stored flags

I am not really understand what it means, i feel like we are going rounds. Sorry for keep asking that again and again but can you just give me a list of actions i need go reproduce it, like

 - do this
 - do that

---

It seems i cant understand the sequence, i did

> https://github.com/netdata/netdata/issues/9742#issuecomment-674544440

no luck

**Comment by thiagoftsm** [comment]
No problem, let me try to clarify for you.

Firstly I will remember what Netdata does, every time that Netdata is running we are storing values inside `health_alarm_log` like the flags, and when the spawn server executes a command it can store the flag HEALTH_ENTRY_FLAG_EXEC_IN_PROGRESS. When an event with this flag is loaded again, it is loading the flag as it was stored and if this alarm entry is scheduled again to execute, it crashes the spawn server and Netdata is closed.

The problem happens, because it loads the flags and these flags do not have a scheduled process associated to it. 

Now, you need to do this:

1 - Stop your Netdata
2 - Overwrite your alarm log with [this](https://github.com/netdata/netdata/files/5105366/db.zip)
3 - Create the suggested alarms from this [link ](https://github.com/netdata/netdata/issues/9742#issuecomment-677900231)
4 - Start Netdata
5 - Run the following command: `for i in `seq 1 10`; do killall -USR2 netdata ; sleep 60 ; done`

This should crash Netdata.

best regards!

**Comment by thiagoftsm** [comment]
This problem affects only `python 3.8`, after to upgrade for python `3.9` I could not recreate the problem, so it does not have relationship with the plugin.
