### ISSUE TITLE
1.24.0 can not be crosscompiled due to libbpf (externaldep)

### ISSUE THREAD

**Issue by BKPepe** [netdata/netdata#9750]
##### Bug report summary
```
checking if perf.plugin should be enabled... yes
checking for libelf... yes
checking for struct bpf_prog_info... yes
checking for externaldeps/libbpf/libbpf.a... configure: error: cannot check for file existence when cross compiling
```

##### OS / Environment
My OS:
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Steps To Reproduce

1. Download SDK for OpenWrt
2. Use this Makefile https://github.com/openwrt/packages/commit/2de28dd95b8c92e2e76038314cab2e180a4cd554
and change version and hash

##### Expected behavior
It should be compiled even when cross compiling, because package libbpf is not available in OpenWrt
https://github.com/openwrt/packages/pull/12949 

Also, why ebpf plugin can not be disabled as others like nfacct/freeipmi and so on?

**Comment by prologic** [comment]
@BKPepe I've aded this to our backlog, not sure when we'll be able to get to it.

In the meantime, what are you cross-compiling from and to?

Yes I _think_ we should have a flag to disable eBPF (_if we don't already_).

**Comment by BKPepe** [comment]
The last time, when I checked it, there wasn't any flag to disable eBPF. I'm cross-compiling locally from Ubuntu 20.04 to several OpenWrt devices mostly Turris routers - powerpc 8540, arm_cortex-a9_vfpv3-d16, aarch64_cortex-a53.

**Comment by Ferroin** [comment]
Yeah, we're missing an option to disable this in the configure script. The install script option only coincidentally works because it involves bundling a library...

**Comment by KickerTom** [comment]
This issue is still there, I can't cross-compile latest version getting the same error as OP. The problem is that the check for the header, causing the error "cannot check for file existence when cross compiling", happens **before** checking the "disable-ebpf" option. I have moved the test before all the ebpf checks in configure.ac and cross compilation with disabled ebpf works for me now.

**Comment by Ferroin** [comment]
@KickerTom Would you possibly be willing to open a PR with that change?

**Comment by KickerTom** [comment]
Sure, I was not just sure such a simple change is worth the hassle of signing the agreement and all that :-).

**Comment by OdysLam** [comment]
@KickerTom,

Thank you so much for this contribution. It doesn't matter if it's small or big, every PR counts towards creating a free OSS Monitoring Agent for all! If you want to participate more in our community, we invite you to https://community.netdata.cloud!

P.S Welcome to the Netdata Community. We are looking forward to interacting with you more :)
