### ISSUE TITLE
Netdata (ebpf.plugin) consuming 50% CPU

### ISSUE THREAD

**Issue by zeacot** [netdata/netdata#9757]
##### Bug report summary

After Install of netdata, in some time it starts consuming arounf 50% of CPU. I have to restart it everytime. After Restart it settles down. But in sometime it again reaches 50%.
I have attached my htop output of netdata. Check below link
https://imgur.com/smQUdfs

I use Netdata for monitoring my servers. I am facing this issue since past 4-5 days.
##### OS / Environment

```
 uname -a; grep -Hv "^#" /etc/*release
Linux rinf-arena 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)
```

##### Netdata version

netdata v1.24.0

##### Steps To Reproduce

This happens after some period of time. Once I reboot netdata, everything goes back to normal. But after sometime it agains start consuming 50% of CPU

**Comment by ilyam8** [comment]
hi @zeacot check `Applications` sections, is it `ebpf.plugin`? 

See https://github.com/netdata/netdata/issues/9727

**Comment by thiagoftsm** [comment]
Hi @zeacot , 

If it has relationship with `ebpf.plugin`, please, take a look in the comment https://github.com/netdata/netdata/issues/9727#issuecomment-674131475 , instead to get the stable, you could install the latest nightly that should have the problem fixed.

Best regards!

**Comment by amoss** [comment]
@zeacot Are you able to install the nightly to see if the patch fixes your issue?

**Comment by thiagoftsm** [comment]
@amoss the ebpf issue https://github.com/netdata/netdata/issues/9727#issuecomment-674131475 was closed after we received the confirmation that the issue was fixed, I did not close this, because @zeacot did not say the problem had relationship with ebpf.plugin.

**Comment by amoss** [comment]
Not explicitly :) But the screenshot of htop shows ebpf. I've changed the issue title to reflect this.

**Comment by thiagoftsm** [comment]
My fault, I missed the screenshot.

@zeacot I am closing this issue, because it was already fixed. I apologize for the problem we created for you and our users.
Please, be free to reopen the issue if it is affecting you yet, for I do a more deeper investigation, but it looks like the exact same problem reported at #9727.

Best regards!
