### ISSUE TITLE
How to reinstall?? after installing cmake

### ISSUE THREAD

**Issue by bighippo999** [netdata/netdata#9758]
##### Question summary
I'm trying to connect to cloud and getting 'This agent was built without the dependencies for Cloud and cannot be claimed'
I believe cmake wasn't installed on the server, so I've installed it.
but I can't figure out how to convince 'bash <(curl -Ss https://my-netdata.io/kickstart.sh)' to reinstall.
It keeps checking the versions and exiting "INFO:  Newest version (current=001024000045 >= latest=001024000045) is already installed"
I've searched both git and the docs, but I can't find anything about what to use to force it to reinstall. Am I missing something obvious?

##### OS / Environment
Unbuntu 18.04.5 LTS

**Comment by thiagoftsm** [comment]
Hi @bighippo999 ,

The message you are showing `INFO: Newest version (current=001024000045 >= latest=001024000045) is already installed` is print when `netdata-updater` runs on your system, this is done by `kickstart` when it finds the script installed:

https://github.com/netdata/netdata/blob/5625d4727f38fc1d3060ab890f18d80ea8cf7d7e/packaging/installer/kickstart.sh#L299

. I think the simplest way for you to reinstall Netdata would be to remove `${ndprefix}/usr/libexec/netdata/netdata-updater.sh` from your system and using `kickstart` again.

@prologic and @Ferroin is there a parameter that we can give to kickstart to force reinstall?

Best regards!

**Comment by Ferroin** [comment]
There currently is not an option to force a reinstall if there's an existing install that we can run the updater against. This was an oversight on my part when I reworked the detection and handling of existing installations in #9408. I'll make a point to work on fixing this tomorrow.

Short term, just removing the updater script as @thiagoftsm should work to force a reinstall.

**Comment by bighippo999** [comment]
Thanks guys,

Unfortunately removing netdata-updater.sh didn't work (the 2nd bit of this):
`root@HODR01:~# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 --- Found existing install of Netdata under: / ---
 --- Attempting to update existing install instead of creating a new one ---
[/root]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron Mon Aug 17 10:01:32 BST 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Mon Aug 17 10:01:32 BST 2020 : INFO:  Current Version: 001024000055
Mon Aug 17 10:01:32 BST 2020 : INFO:  Latest Version: 001024000055
Mon Aug 17 10:01:32 BST 2020 : INFO:  Newest version (current=001024000055 >= latest=001024000055) is already installed
 OK

 --- Updated existing install at /usr/sbin/netdata ---
root@HODR01:~#
root@HODR01:~#
root@HODR01:~# mv /usr/libexec/netdata/netdata-updater.sh /usr/libexec/netdata/netdata-updater.old
root@HODR01:~#
root@HODR01:~#
root@HODR01:~# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 --- Found existing install of Netdata under: / ---
 ABORTED  Existing installation detected which cannot be safely updated by this script, refusing to continue.

root@HODR01:~#`

But I realised the newest/latest version numbers were different to what I post the other day. So tried to connect to cloud again and it worked :) must have automatically update on the weekend. Sadly I didn't have the foresight to install cmake on the other servers at the same time, so they still can't be connect yet, but I don't mind waiting for an update to just fire and make it work for them too.

**Comment by Ferroin** [comment]
This is probably going to be a bit more involved than I first thought, digging into it has revealed a number of other bugs in the associated code that I had not previously noticed, and it's going to be easier long-term to fix all of those in one pass. I hopefully should still have a PR up some time later today or tomorrow though.

In the immediate short term, removing the netdata-updater script and then re-running the install with the switch `--allow-duplicate-install` and the _exact_ same value for the `--install` option as the original install should work to side-step this issue for regular `kickstart.sh` installs (for static installs with `kickstart-static64.sh` this won't work due to one of the aforementioned bugs).
