### ISSUE TITLE
Netdata Agent only for cloud usability

### ISSUE THREAD

**Issue by xenforq** [netdata/netdata#9760]
##### Question summary
Does the agent support toggling features to make the only function sending statistics and data to Netdata Cloud?

##### OS / Environment
Any already supported environment.

##### Component Name
n/a

##### Expected results
- Disable the locally hosted dashboard
- Keep sending statistics to the cloud per usual
- Convert the agent to a monitor that just sends data

**Comment by joelhans** [comment]
First off, sorry that it took so long for us to get you a response. The first two expected results are possible, but the third is not, as Netdata Cloud needs to query your node's local database to stream metrics to your browser.

To disable the local dashboard, open `netdata.conf`.

```
cd /etc/netdata
sudo ./edit-config netdata.conf
```

Scroll down to the `[web]` section, then change `mode = none`.

```
[web]
    mode = none
```

Restart the Agent with `service netdata restart`. Your local dashboard is now disabled, but you can still see all your metrics and alarm statuses in Netdata Cloud.

For a little more detail, see my [community thread](https://community.netdata.cloud/topic/92/running-a-headless-netdata-agent-with-cloud-compatibility) on the topic. If anyone has tried this out already, we'd love to hear your experiences!
