### ISSUE TITLE
netdata down after latest update (netdata v1.24.0-49-nightly) auto restart loop

### ISSUE THREAD

**Issue by StaticReality** [netdata/netdata#9761]
##### Bug report summary

Netdata is broken after latest update. Noticed the graphs stopped updating (instead of the usual gap from the update), and when issuing a refresh on the browser received a: ERR_CONNECTION_REFUSED. Found system in a dead state so issued a restart and service is stuck in an "auto-restart" loop. Verify nothing else is running on the netdata port via `netstat -nap`

##### OS / Environment

```
# systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/usr/lib/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2020-08-16 09:55:46 CDT; 5s ago
  Process: 2065 ExecStopPost=/usr/libexec/netdata/plugins.d/reset_netdata_trace.sh (code=exited, status=0/SUCCESS)
  Process: 2062 ExecStart=/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D (code=exited, status=1/FAILURE)
  Process: 2059 ExecStartPre=/bin/chown -R netdata:netdata /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 2056 ExecStartPre=/bin/mkdir -p /var/run/netdata (code=exited, status=0/SUCCESS)
  Process: 2053 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 2051 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 2062 (code=exited, status=1/FAILURE)

Aug 16 05:04:09 gsm4.kukaservers.com systemd[1]: Unit netdata.service entered failed state.
Aug 16 05:04:09 gsm4.kukaservers.com systemd[1]: netdata.service failed.

```

##### Netdata version

netdata v1.24.0-49-nightly 

##### Component Name

service

##### Steps To Reproduce

1. update netdata automatically via pre-installed cron
2. watch netdata website go down
3. issue a systemctl status netdata and see service is down

##### Expected behavior

small gap in metrics, not service stuck in a "auto-restart" state:

output from systemctl status netdata
Active: activating (auto-restart) (Result: exit-code) since Sun 2020-08-16 05:15:12 CDT; 6s ago

**Comment by StaticReality** [comment]
Tried restarting, or at least initializing the installer and it fails saying on latest version already:
```
# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 --- Found existing install of Netdata under: / ---
 --- Attempting to update existing install instead of creating a new one ---
[/var/log/netdata]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron Sun Aug 16 05:17:05 CDT 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Sun Aug 16 05:17:05 CDT 2020 : INFO:  Current Version: 001024000049
Sun Aug 16 05:17:05 CDT 2020 : INFO:  Latest Version: 001024000049
Sun Aug 16 05:17:05 CDT 2020 : INFO:  Newest version (current=001024000049 >= latest=001024000049) is already installed
 OK

 --- Updated existing install at /usr/sbin/netdata ---
```

**Comment by thiagoftsm** [comment]
@prologic and @Ferroin it looks like this is the same issue we had reported at #9758 .

**Comment by Ferroin** [comment]
Yes, it is the same as #9750, closing this as a duplicate and properly recategorizing that one.
