### ISSUE TITLE
installation directory differences between kickstarter.sh 

### ISSUE THREAD

**Issue by git1977** [netdata/netdata#9765]
I have 3 questions:
Q1
I see when i run the script in this [link](https://learn.netdata.cloud/docs/agent/packaging/installer#automatic-one-line-installation-script)  it is installing in /etc/netdata but if I use the script in this [link](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64) , it is installing netdata in /opt/netdata. Not sure why is the difference. when is kickstart-64 to be used? 
Q2:how to find the location of netdata.conf used? In the browser I tried <localHostIP>:19999/netdata.conf, I get a message "You are not allowed to access this resource." 
Q3: Why is installation of netdata taking more than 10-15 minutes. I tried on multiple distro new servers(Amazon linux, ubuntu, red hat, Suse linux). Is this the expected installation time? Any tips to reduce this?

**Comment by Ferroin** [comment]
The normal 'kickstart.sh' install currently builds a copy of Netdata locally This is why it takes so much time, and why it's able to let the user specify what prefix they want Netdata installed under (which is none by defualt). `kickstart-static64.sh` uses a pre-built statically linked copy of Netdata, and thus can only install in a fixed prefix. It's intended to be used on systems where you can't build Netdata for some reason (or may not be able to get all the dependencies).

As far as the location of `netdata.conf`, it will always be under `$PREFIX/etc/netdata`, where `$PREFIX` is the prefix that Netdata is installed under (so `/` for normal `kickstart.sh` installs, or `/opt/netdata` for `kickstart-static-64.sh` installs). You _should_ be able to access the config through the API endpoint you used, if you're not having any success doing so (and do not have anything in your config that would cause the request to be blocked), that's a bug.

**Comment by prologic** [comment]
@git1977 Does this answer your questions? As for when you should use `kickstart.sh` vs. `kickstart-static6.sh` -- The difference is only that `kickstart.sh` (_currently_) builds from source whilst `kickstart-static64.sh` just installs a prebuilt static binary as @Ferroin explained. If you want the fastest installation go with `kickstart-static64.sh`.

Does this all help and answer your questions?

**Comment by git1977** [comment]
For kickstart-static64.sh, how would I change the installation path similar to kickstart.sh?

**Comment by Ferroin** [comment]
It's not possible to do so. There are some paths we have to configure at compile time which can't be changed at install time, so we unfortunately have to have a fixed installation path for any prebuilt copies of Netdata.

**Comment by git1977** [comment]
ok thank you.
