### ISSUE TITLE
Long statsd timer names break streaming replication

### ISSUE THREAD

**Issue by vince-lessbits** [netdata/netdata#9768]
##### Bug report summary

Long statsd timer names are breaking replication.  We generate statsd statistics names programmatically to reflect module paths within our application.

The streaming receiver keeps closing the connection to the sender upon receiving chart definitions with long names.

This causes gaps in collection which can be seen in the Netdata UI.

This also effectively breaks centralized health alerting for the sending node since the streaming connection is constantly thrashing.

The situation causes a spike in tcp handshake errors on the receiving node.  I have used this to alert me to problems with streaming replication.

##### OS / Environment

```
Linux sysops 5.0.0-1025-gcp #26~18.04.1-Ubuntu SMP Mon Nov 11 13:09:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.3 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.3 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic

```

##### Netdata version

 
netdata v1.23.2

This has been observed in 1.21.1 and above.

Our dev environment is running 1.18.1 and does NOT have this issue so far with the chart names we've generated.
##### Component Name

Streaming Replication
##### Steps To Reproduce

Follow the README here:  https://github.com/vince-lessbits/netdata-test

##### Expected behavior

The receiver should log why it closes a streaming conection, without debug flags.
Replication should work with arbitrarily long chart names.

It would be nice if an error with a single chart didn't destroy all replication.  This seems like a big risk for headless collectors.

**Comment by vince-lessbits** [comment]
My apologies for the duplication with https://github.com/netdata/netdata/issues/9734

I didn't see the reply on the community site.

**Comment by amoss** [comment]
Thanks for the bug report - very easy to track down the problem with your replication steps.

Supporting arbitrarily long chart names is not an option for us. They are packed into a structure in memory that needs to be a fixed size for efficiency reasons. Reworking that aspect of Netdata would affect the database and the legacy memory modes.

We will need to find a way to mitigate the problem in the stats.d collector. @stelfrag / @vlvkobal Do you have any ideas on how we can process the charts names in the stats.d collector to preserve uniqueness but shorten them to fit within the limit?

**Comment by vlvkobal** [comment]
> how we can process the charts names in the stats.d collector to preserve uniqueness but shorten them to fit within the limit?

Probably, the simplest way is to truncate the name and add a UUID to the end of the string.

**Comment by amoss** [comment]
> Probably, the simplest way is to truncate the name and add a UUID to the end of the string.

That could work. If we use a hash of the full (untruncated name) then we don't need to track UUIDs. So the example from @vince-lessbits 's test case is:
```
this-is-a.long_statsd_timer_name.to_simulate_programmatically_generated_names_from_mod_paths
```
This would get truncated to some prefix and then the hash of the name, e.g.:
```
this-is-a.long_statsd_timer_name.to_simulate_programmatically_generated99fe341e
```
I'm looking in the code to see which length limit it exceeded. It doesn't look like `RRD_ID_LENGTH_MAX` as it is not long enough. Perhaps a limit in the config structures?

**Comment by ilyam8** [comment]
> We generate statsd statistics names programmatically to reflect module paths within our application.

> to reflect module paths within our application.

> Probably, the simplest way is to truncate the name and add a UUID to the end of the string.

Does it make sense? The gist of long names is to give some meaning, if we remove the meaning do we need the metric at all?

**Comment by amoss** [comment]
> Does it make sense? The gist of long names is to give some meaning, if we remove the meaning do we need the metric at all?

It maximizes the amount of meaning that we can provide within a fixed amount of space.

**Comment by ilyam8** [comment]
@vince-lessbits [what do you think](https://github.com/netdata/netdata/issues/9768#issuecomment-675350635)?

**Comment by vince-lessbits** [comment]
Thank you for the replies and thank you for making netdata!

I will agree that "arbitrarily long" chart names might be unnecessary, but I believe the test case is a reasonable length to support.  I really hope there's a way to get this fixed. I think that the hash would be difficult to explain to my coworkers.

I have experimented with the source code a little bit and I found that increasing this buffer https://github.com/netdata/netdata/blob/master/streaming/rrdpush.h#L84 to 1024 fixes the replication issues.

The sending side will attempt to send a string that is 520 characters without the newline:
```
CHART "statsd_timer_this-is-a.long_statsd_timer_name.to_simulate_programmatically_generated_names_from_mod_paths" "long_statsd_timer_name.to_simulate_programmatically_generated_names_from_mod_paths" "statsd private chart for timer this-is-a.long_statsd_timer_name.to_simulate_programmatically_generated_names_from_mod_paths" "milliseconds" "timers" "statsd_timer.this-is-a.long_statsd_timer_name.to_simulate_programmatically_generated_names_from_mod_paths" "area" 90000 1 "  store_first " "statsd.plugin" "private_chart"
```

**Comment by amoss** [comment]
The limit on the names should be 200 characters. If increasing that buffer fixes your problem then it suggests there is a problem with reassembling the lines before they are fed into the parser. I will take a look at what we are doing.

**Comment by amoss** [comment]
Yes, your analysis is correct. The buffer in the receiver is too small to allow the line to be reassembled before it hits the parser. Thank you for looking into it. I'll create a PR for it now and we should get it reviewed and into the master branch quickly.

**Comment by amoss** [comment]
@vince-lessbits Thank you for the effort in digging into the problem and fixing it. I've asked our Marketing people to add you to the contributor of the month list so they should send you some free Netdata swag :)

**Comment by vince-lessbits** [comment]
@amoss Thank you and the netdata team for the quick fix!

**Comment by amoss** [comment]
Thank you again. I think you did all the work here :) All I did on the PR was check the defines and the other points in the code that touch the buffer. Nice investigative work to find the problem and work out how to fix it.
