### ISSUE TITLE
Netdata update failing.

### ISSUE THREAD

**Issue by pnunn** [netdata/netdata#9772]
#### Question summary
I seem to be unable to update my netdata installation.  I am running netdata v1.23.2-79-nightly and was prompted to update today. 

Unfortunately when I try and update I'm getting

bash kickstart.sh
 --- Found existing install of Netdata under: / ---
 --- Existing install appears to be handled manually or through the system package manager. ---
 ABORTED  Existing installation detected which cannot be safely updated by this script, refusing to continue.

Now.. I did initially install with the package manager, but then purged that install and removed everything from the system, then installed with the kickstart script.

I have looked at the script, but can't for the life of me work out why its still hitting the failure.

Everything is installed under /etc/netdata as far as I can tell.
 
##### OS / EnvironmentI
Ubuntu 20.04 server

##### Component Name
I am not finding any file called natdata-updater.sh on the system anywhere (which seems to crop up in other reports).

##### Expected results
I guess the update runs?

**Comment by Ferroin** [comment]
Pretty sure this is a bug (not entirely sure _where_ yet though), so I'm recategorizing it as such.

Could you please share the contents of `/etc/netdata/.environment` from the system you're seeing the issue on? If you installed under a prefix (such as `/opt/netdata`) it would be at that path under the prefix instead.

**Comment by pnunn** [comment]
OK, I don't have a .environment file anywhere on this system associated with netdata (searched the entire disk).

Is that the problem, faulty install by the sounds.

**Comment by Ferroin** [comment]
Yeah, that sounds like it's a bad install. If you add `--allow-duplicate-install` to the kickstart command you should be able to use the kickstart script to reinstall the existing install and that _should_ get you to a working state.
