### ISSUE TITLE
Custom service-discovery for more services (e.g. Redis/Kafka/Elastic)? (With my attempts inside)

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/netdata#9774]
##### Question summary

Hi thanks for the wonderful netdata! I [know](https://learn.netdata.cloud/guides/monitor/kubernetes-k8s-netdata#service-discovery-services-running-inside-of-pods) netdata supports 22 apps for service discovery. However, I need to monitor things like Redis and Kafka, which is not in the list. I wonder **how to add my custom service-discovery**? 

My attempts:

1. I found that finally the generated go.d.yml is used by the go.d plugin code [here](https://github.com/netdata/go.d.plugin/blob/0c764a2f426627192e26299e7327960165cebf0a/cmd/godplugin/main.go#L67). Thus it seems non-Golang modules cannot be used? :/
2. I have another idea: **Can we support Prometheus metrics exporting**? Many apps like redis/kafka/... have prometheus exporter. Thus, if we support prometheus, we can happily collect a lot of apps even if the classical Netdata collectors cannot work.

Thanks!

EDIT: It is said that this is related to @netdata/agent , could you please provide some suggestions? Thanks!

##### OS / Environment

Linux

##### Component Name

netdata on kubernetes

##### Expected results

N/A

**Comment by cakrit** [comment]
- @joelhans  Does https://github.com/netdata/agent-service-discovery/ appear in https://learn.netdata.cloud? I haven't found it.
- @ilyam8 The service discovery readme doesn't mention where the config file is located in a default netdata installation. Do we also edit with with edit-config?
- @joelhans We really should add something in the netdata/helmchart readme as well, to tell people how they can configure service discovery.

@fzyzcjy we have a [generic prometheus collector](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/prometheus) in Netdata v1.24, with the default configuration only looking for endpoints in localhost. And yes, the next step is to link it with the service discovery in kubernetes, so we can do exactly what you are saying.

**Comment by fzyzcjy** [comment]
@cakrit Thanks very much! So will "the next step" you mentioned be done soon?

I really love Netdata (it is sooooo powerful!) and do not want to go to other solutions, so I can wait for one or two weeks :)

**Comment by ilyam8** [comment]
> The service discovery readme doesn't mention where the config file is located in a default netdata installation.

it is only for k8s == there is `ConfigMap`

https://github.com/netdata/helmchart/blob/de2587edcef4074a0a14a3804962ffa8268558b9/values.yaml#L10-L17

ConfigMap source by default is the text file in the helmchart repo

> https://github.com/netdata/helmchart/blob/master/sdconfig/child.yml

---

> Thus it seems non-Golang modules cannot be used?

Yes.

> Can we support Prometheus metrics exporting

Yes, we plan it to add some prometheus endpoints identification patterns to [the default service-discovery config](https://github.com/netdata/helmchart/blob/de2587edcef4074a0a14a3804962ffa8268558b9/sdconfig/child.yml#L7-L54) soon.

**Comment by joelhans** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Supplement service discovery documentation](https://trello.com/c/UDR1jjNF/248-supplement-service-discovery-documentation)

**Comment by joelhans** [comment]
@cakrit The service discovery README isn't current on Learn. I'm making a note to edit the ingest process to make that happen. Either you or @ilyam8 have recommendations on where it should go? **Collecting metrics -> External plugins -> Service discovery**?

I'll also work with Ilya on adding some configuration details to the Helmchart README.

Speaking of the Helmchart... should we have that on Learn too? It wasn't really built with so many external repositories in mind, but I think it could be extended without too much chaos.

**Comment by cakrit** [comment]
The instructions for the Helmchart are where people expect them to be, on the chart itself, so I wouldn't bother adding it to learn, as long as the search brings up a result that links to it.

Service Discovery only works for go.d plugins, so it belongs there. It also just works in Kubernetes now, so it needs a link from whatever we have on k8s.

**Comment by ilyam8** [comment]
> It also just works in Kubernetes now

Yeah,

This issue is about service discovery, so:

This is go.d overview diagram

https://drive.google.com/file/d/1DeXZu9TxUc4MRqYB3D5EguKvrvkwtWMv/view?usp=sharing

There is `File Discovery` which reads/watches files and produces job configs.

It is likely we add some other sources directly to the go.d at some point (ex.: parse /proc, call `ps` or something like that).

Any ideas are welcome.

**Comment by ilyam8** [comment]
> kubectl edit ...

It is not specififc thing, you can edit any resource using `kubectl edit` (i guess internally it is download & apply).

> https://github.com/kubernetes/kubectl/blob/de605093327f52a06c2ba64d9f3279cd801bea1b/docs/book/pages/imperative_porcelain/editing_workloads.md#editing-resources

**Comment by fzyzcjy** [comment]
Hi sorry for disturbing, I wonder when will prometheus be added (since my project will be soon released)? If not very soon, can I do it and will you accept PRs :)

> Yes, we plan it to add some prometheus endpoints identification patterns to the default service-discovery config soon.

**Comment by ilyam8** [comment]
Well, soon ~ 2 weeks.

> since my project will be soon released

What prometheus endpoints do you want to monitor?

**Comment by fzyzcjy** [comment]
By the way, IMHO, I may also need to hint the port to be scraped somewhere (e.g. in the annotations)

**Comment by fzyzcjy** [comment]
Hi how is it going? If it is not added, I am going to try to add it by myself and make a PR today. Is it welcomed?

**Comment by fzyzcjy** [comment]
Hi I have created a PR! https://github.com/netdata/helmchart/pull/137 :)

**Comment by ilyam8** [comment]
@fzyzcjy hi, this is very nice you managed to get prometheus endpoints identificited!

As i mentions in the PR there is wip - https://github.com/netdata/helmchart/pull/134

and it is blocked by netdata v1.25 release and sd release (which i do right after netdata v1.25, not really a blocker)
