### ISSUE TITLE
Netdata Cloud is extremely slow for users in countries like China (because of GFW)

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/netdata#9777]
##### Bug report summary

Hi thanks for the wonderful library! I want to use Netdata Cloud very much. However, in China there is "the great firewall" which bans us from accessing part of the global network. Thus, visiting Netdata Cloud is extremely slow here. IMHO, the nodes (with Netdata Agent installed on them) need to communicate with app.netdata.cloud. However, it is illegal to install any proxy on the nodes (our app servers) to go over the wall, so **Netdata Agent in China cannot communicate with app.netdata.cloud smoothly**. Thus we cannot happily use this feature :(

(My naive ideas: Maybe add some servers which is not banned by Chinese goverment. Or, maybe create a self-hosted version of Netdata Cloud. Actually I love the current cloud very much since I do not need to self-host. However the network cannot be accessed smoothly.)

Thanks!

##### OS / Environment

```
N/A
```

##### Netdata version

 latest

##### Component Name

N/A

##### Steps To Reproduce

N/A

##### Expected behavior

N/A

**Comment by prologic** [comment]
cc @manos-saratsis @cakrit 

AFAIK we _do_ have plans for self-hosting Netdata Cloud one day, its on the long-term roadmap.

Regarding installing servers in CN, I'm not sure how feasible that would be in terms of Netdata Cloud.

**Comment by prologic** [comment]
Related issue #8527

**Comment by ilyam8** [comment]
> Regarding installing servers in CN

I assume it is no go. @cakrit correct me if i am wrong.

**Comment by fzyzcjy** [comment]
@ilyam8 @prologic Sad to hear that :( Actually there are more than 1 billion people in China, so this is really a HUGE portion of users of Netdata.

**Comment by prologic** [comment]
> @ilyam8 @prologic Sad to hear that :( Actually there are more than 1 billion people in China, so this is really a HUGE portion of users of Netdata.

Its not really up to us, we have to prioritise our efforts and use resources accordingly. This is up to @cakrit and @ktsaou really. I _think_ from a technical perspective we can definitely provide both Netdata Agent installation (_in the same easy to use 1-liner_); the Netdata Cloud SaaS however I'm not 100% sure on; maybe but maybe @manos-saratsis can chime in here with "technical feasibility"? From a "networking" point of view it might mean having Netdata servers in CN where we can internally route requests into our cloud services? 🤔 I wonder how Google and other clouds do this? (_I'm not sure what is and isn't blocked in CH tbh :/_)

**Comment by fzyzcjy** [comment]
@prologic Unfortunately, we do NOT have Google here. So I HAVE TO use a paid proxy to go to the outside world every day (you know, I cannot do programming without google).Proxy on my own computer is ok (though also illegal); but for Netdata Cloud, the agent on *the production server* has to connect to the cloud, but this is *not ok* since that server will be *banned* by the government once it finds it using proxy. 😢

**Comment by cakrit** [comment]
Hold on for a week or two, we'll need to have an internal discussion on what we'll do with China.

**Comment by fzyzcjy** [comment]
@cakrit Thanks soooooo much!

**Comment by smzcs** [comment]
cannot install netdata:

curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-ckglkAc4NR/sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt curl: (28) Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
 FAILED  


GFW, really a bad thing for the Chinese people

**Comment by fzyzcjy** [comment]
Hi half a year have passed, thus I wonder what is the current situation? It seems Netdata Cloud is still quite slow when visiting from China.

Espeicially considering that, Netdata Cloud seems to have much richer features now (compared with half a year ago and compared with netdata agent), I cannot wait to use it!

Thanks

**Comment by cakrit** [comment]
Apologies for not replying here earlier, as we did have the internal discussion back in August. 
We do not intend to make any moves in the foreseeable future to conform to the legal requirements for reliable and high performant access from China. We hope the wonderful members of our community in China can assist us to at least make the agent more easily available in China. 

Netdata Cloud is a free service that requires unrestricted internet access at this time. Unfortunately, we do not have plans for localized or on-premises hosting in the foreseeable future. We should mention that the agent [streaming and replication](https://learn.netdata.cloud/docs/agent/streaming) feature could potentially be useful to some users. For example, perhaps netdata agents inside China could stream metrics to agents outside China, which could then be claimed in a Netdata Cloud workspace.

I wish we could be more helpful, but we are tirelessly working on a roadmap that will ensure we'll be successful enough to cover as many of our user's needs as possible, in the long run.

**Comment by fzyzcjy** [comment]
@cakrit Thanks for the reply!

> We hope the wonderful members of our community in China can assist us to at least make the agent more easily available in China.

I am willing to help if I can

**Comment by ilyam8** [comment]
Hi, @fzyzcjy no updates to my knowledge. Assigned it to me so it is not get forgotten.

**Comment by fzyzcjy** [comment]
:(

**Comment by fzyzcjy** [comment]
Hi, is there any updates or future plans? The netdata-grafana plugin looks quite interesting, but I cannot use it due to the issue :(

**Comment by cakrit** [comment]
It would be too large of an undertaking for us at this stage of the company. I expect that we'll have an on-premise version of Netdata Cloud long before we attempt to do something specifically for China.

**Comment by fzyzcjy** [comment]
I see. Looking forward to it!
