### ISSUE TITLE
Custom Hangouts alerts

### ISSUE THREAD

**Issue by Bearzooka** [netdata/netdata#9784]
##### Feature idea summary

Google Hangouts notifications are a great mechanism to notify people, but the current behaviour sends all the information as an attachment that is not visible in the notification of mobile devices.

It would be more useful to have a line of text with the summary for the alert (Host, Context, Level, etc.) at the top of the message and then the attachment, that way mobile devices would get a notification that is readable at a glance.

##### Expected behavior

Ability to customise the content of alarms sent to Hangouts.

**Comment by thiagoftsm** [comment]
This issue has relationship with #9785 , when this is closed, the other also needs to be.
