### ISSUE TITLE
Threads for Hangouts Alerts

### ISSUE THREAD

**Issue by Bearzooka** [netdata/netdata#9785]
##### Feature idea summary
Instead of each new alert creating a new thread, it would be useful to have pre-created threads in Google Hangouts and configure them in NetData so it appends new messages to them, to create better traceability of an issue.

##### Expected behavior
The configuration file could have, in addition to the URL for the webhook, a field for the thread, that if provided will be used for all the messages of that particular alert. This way the messages will be linked in a single thread which provides readability.

**Comment by Bearzooka** [comment]
This is the code I use to insert the thread on another application.

```
url = ("https://chat.googleapis.com/v1/spaces/%s/messages?key=%s&token=%s" % (space, key, token))
message_headers = {'Content-Type': 'application/json; charset=UTF-8'}
data = ("{'text': '%s', 'thread': {'name' : 'spaces/%s/threads/%s'}}" % (message, space, thread)).encode('utf-8')
```

**Comment by thiagoftsm** [comment]
Hi @Bearzooka ,

To bring this new feature we will need to change the payload send  to hangout

https://github.com/netdata/netdata/blob/b1505b45f87de267f7a374f5c4a2dee33056a5b8/health/notifications/alarm-notify.sh.in#L1886

we will also need to add a structure like we have for email

https://github.com/netdata/netdata/blob/b1505b45f87de267f7a374f5c4a2dee33056a5b8/health/notifications/alarm-notify.sh.in#L2385

Your request is not complicated to bring, I am adding it for my backlog to work on this when I have a time.

Best regards!

**Comment by thiagoftsm** [comment]
Hello @Bearzooka ,

I am sorry for the delay, but I was busy with other projects. Today I made the PR you requested, it is set as draft, because the documentation needs to be improved, but if you have a time to test it, please, let me know if I achieved what was expected.

Best regards!
