### ISSUE TITLE
Plugin to check time since last modification of a file

### ISSUE THREAD

**Issue by nodiscc** [netdata/netdata#9794]
##### Feature idea summary

When monitoring periodic/scheduled tasks such as `cron` job runs, one often wants to ensure a generated file is not older than an acceptable threshold - for example for a daily backup, a file updated on backup success should not be older than 24h (+/- tolerance for varying backup durations).

##### Expected behavior

I have looked in existing netdata plugins but did not find anything relevant. There are plugins for time-related monitoring (such as the x509check plugin which checks time until expiration of SSL certificates), but nothing related to file modification times.

I wrote a simple python.d plugin that monitors time since last modification of files, and nothing more: https://gitlab.com/nodiscc/netdata-modtime/ ([Github mirror](https://github.com/nodiscc/netdata-modtime)). It is a very simple plugin with basic configuration/alarms examples and basic error handling.

![](https://i.imgur.com/kP91ldr.png)

Now I am wondering, would you be interested in including something similar in netdata?

You could pick the module directly from my repo (or rewrite it... I think python.d plugins are not your platform of choice?). Or would there be a need for a more "generic" plugin for file-related monitoring? eg. counting the number of files in a directory, alerting on absence/presence of files...

I think this would be a useful addition.

**Comment by Ferroin** [comment]
For the record, you can kind of do this using the monit collector, because monit itself can track this, but it's a bit complicated and you'd end up having to set the limits in the monit configuration, not the Netdata configuration.

However, I do think having such a plugin natively would be useful, though I would personally probably take a different approach (one dimension per monitored filesystem object instead of one job per monitored filesystem object).

@ilyam8 Your thoughts on this given that you'd probably be the person implementing it in Go if we went that way?

**Comment by ilyam8** [comment]
We have:

- [httpcheck](https://github.com/netdata/go.d.plugin/tree/master/modules/httpcheck)
- [portcheck](https://github.com/netdata/go.d.plugin/tree/master/modules/portcheck)
- [x509check](https://github.com/netdata/go.d.plugin/tree/master/modules/x509check)

We could add `filecheck`.

>  it in Go

Yes, it very easy to write it in go.

**Comment by ilyam8** [comment]
> I would personally probably take a different approach

Lets discuss/agree on implementation and we add it.

**Comment by nodiscc** [comment]
Well since it would be a generic `filecheck` plugin, here a some use cases that it should probably cover:
- alert when a file is older/newer than a certain time
- alert when a file is present/absent
- alert when a directory contains more/less than `n` files
- alert when a file size is above/below `n` b/kb/Mb...

> one dimension per monitored filesystem object instead of one job

Why not... but it might make the chart hard to read (suppose you have a file with a normal lifetime of one year, and one with a normal lifetime of 5min... in the same chart). The downside of one job per file is that the number of charts can quickly grow if you have a lot of objects.

**Comment by Ferroin** [comment]
> Well since it would be a generic `filecheck` plugin, here a some use cases that it should probably cover:
> 
> * alert when a file is older/newer than a certain time

For this specifically, we should probably allow the user to match on any of atime, mtime, ctime, or btime.

> * alert when a file is present/absent
> * alert when a directory contains more/less than `n` files
> * alert when a file size is above/below `n` b/kb/Mb...

Monitoring what type of file it is likely to be useful and not too hard to do, same (potentially) for the hard link count.
 
> > one dimension per monitored filesystem object instead of one job
> 
> Why not... but it might make the chart hard to read (suppose you have a file with a normal lifetime of one year, and one with a normal lifetime of 5min... in the same chart). The downside of one job per file is that the number of charts can quickly grow if you have a lot of objects.

My thought was to still allow for having multiple jobs but allowing the user to configure a single job to monitor multiple objects. IOW, users could still configure one job per file if they wanted, but could also group files with similar check requirements together as a single job (which i believe would make writing alarms easier too).

**Comment by ilyam8** [comment]
Ok, it is getting ~~complicated~~ interesting! 😄 

I see we need to collect:

- file stats:
  - size
  - mod time
  - creation time ??
  - present/absent

- dir stats:
  - num of files

~ telegraf plugins:
 - https://github.com/influxdata/telegraf/tree/master/plugins/inputs/filecount
 - https://github.com/influxdata/telegraf/tree/master/plugins/inputs/filestat

**Comment by Ferroin** [comment]
Personally, my suggestion for the structure would be to allow each job to define one set of conditions to monitor, and then have a key for a list of paths to check.

Something along the lines of (borrowing existing Go plugin conf syntax):

```yaml
jobs:
  - name: File Checks
    paths:
    - /foo/bar.txt
    mtime: true
    ctime: true
    size: true
  - name: Dir Checks
    paths:
    - /baz
    mtime: false
    ctime: true
    size: false
    nfies: true
```

I wouldn't differentiate between file/dir for the things we can monitor, would suggest using raw dirent counts instead of explicitly trying to handle the fact that some filesystems have two explicit entries in the count for empty directories and some don't, and feel that existence should be implicit.

We might also consider adding the ability to check if a directory appears to be a mount point, but that should bedisabled by default because it requires two `stat()` calls (one for the dir, one for it's parent).

**Comment by nodiscc** [comment]
> if it is one module (filecheck) or two (filecheck, dircheck)

I think it should be one generic module which handles all kinds of filesystem objects using `stat()` (unless that introduces unnecessary complexity for the configuration or maintenance...)

Another useful feature would be counting the number of lines in a file matching a regex (which should be disabled by default). For example I would like to count the number of `warnings`, `error`s and `suggestion`s in reports produced daily by [lynis](https://cisofy.com/lynis/). That may be a job for a separate module since a simple `stat` is not capable of this. I will probably write a custom module with hardcoded logic in the mean time.

> allowing the user to configure a single job to monitor multiple objects

Your configuration example looks fine! But I don't see how to make alarms easily configurable, if jobs can watch several files. For example in my module (one job per file), an alert configuration looks like:

```yaml
  alarm: modtime_last_rsnapshot_success
     on: modtime_last_rsnapshot_success.file_age
   calc: $file_age
  every: 10s
   warn: $this > 88200
   crit: $this > 90000
  units: seconds
   info: time since last modification
     to: sysadmin
```

How would that look like with your example? (eg. warning when `/foo/bar.txt` has mtime older than 24h, warning when `/xyz.txt` has mtime older than 48h)

**Comment by ilyam8** [comment]
I tend to disagree with

> I wouldn't differentiate between file/dir for the things we can monitor

There are different things we want to have monitored for files and dirs, i dont relly like when it is a flat list of options and some of them work for one case and doesnt for others (ex.: `nfiles` works only for dirs).

It is likely we will add additional _checks_ for _files_ and for _dirs_ and they are different so flat configuration is confusing.

Also i dont think we need `size`, `mtime` options, at least in the beginning, filestat check monitors:
 - existence
 - size
 - mod_time

There is no really need to disable something, we can add it later. I suggest to not add complexity unless it is needed (but keep it in mind designing module, so later we dont need to add breaking changed to the module config).


From what i see filestat check is need only selector - what files to monitor. We need to support file names _globbing_, it means probably we need not only include but exclude options.


```yaml
selector:
  include: [PATH1, ...]
  exclude: [PATH1, ...]
```

If we are going to add dir checks to the same module it should be

```yaml
file:
  selector:
    include: [PATH1, ...]
    exclude: [PATH1, ...]  
dir:
  option: value
```

**Comment by ilyam8** [comment]
> Another useful feature would be counting the number of lines in a file matching a regex

```yaml
filestat:
  selector:
    include: [PATH1, ...]
    exclude: [PATH1, ...]
filecontent:
  selector:
    include: [PATH1, ...]
    exclude: [PATH1, ...]
  content_related_option: ...
```

🤔

**Comment by nodiscc** [comment]
> I think it should be one generic module which handles all kinds of filesystem objects using stat() (unless that introduces unnecessary complexity for the configuration or maintenance...)

>> i dont relly like when it is a flat list of options and some of them work for one case and doesnt for others

True

> There is no real need to disable something, we can add it later

True

> Another useful feature would be counting the number of lines in a file matching a regex

As I said it could probably be done in a separate `linecount` module... in fact it's very similar to what the `web_log` module does, except it doesn't care for the time and always parses the whole file. Do one thing.

> We need to support file names globbing

Do we? It would probably make configuration more complicated? Is that one chart per file matching the glob? x3 for existence/size/mtime... And how do you configure alarms for each one of those?

The simplest configuration I see: `filecheck.conf`

```yaml
jobs:
  dir_checks:
    - /var/somedir
    - /var/some/other/dir
  file_checks:
    - /var/backup_timestamp
    - /var/some_other_file
```

- Every `dir_check` reports existence, mtime, number of files in 3 different charts (so in this example, 6 charts)
- Every `file_check` reports existence, mtime, size in 3 different charts (so in this example, 6 charts)
- You can access every chart in alarms using `filecheck./path/to/object.{existence,mtime,nfiles,size}`
  - are `/` allowed in chart names?
  - otherwise we can replace them with `_` in chart names but beware of conflicts between `/var/backup/timestamp` and `/var/backup_timestamp` for example

ctime does not work everywhere (on ext4 it's the inode creation time... not that useful to monitor), so I don't think it's worth a chart.

**Comment by ilyam8** [comment]
> Do we? It would probably make configuration more complicated?

I think we do. Checking exact file is ok but i am pretty sure we will get a request to add filename globbing, usecase - checking all files in a directory. In my opinion this is a _legit_ request and it make sense to add it from the very beginning. Considering that we need a way to exclude a specific file, thats is i suggested.

```
selector:
  include: [PATH1, ...]
  exclude: [PATH1, ...]
```

It doesnt really make configuration more complicted, because common use case is

```yaml
selector:
  include: [PATH1, ...]
```

But there is a way to exclude something adding `exclude` option. And we already have this _matcher_ implemented - https://github.com/netdata/go.d.plugin/blob/master/pkg/matcher/expr.go.


---

```yaml
jobs:
  dir_checks:
    - /var/somedir
    - /var/some/other/dir
  file_checks:
    - /var/backup_timestamp
    - /var/some_other_file
```

Then it is not `filecheck`, we have dir check functionality there. I would like to have the name that reflects functionality.

---

I think there are two different modules - `filecheck/dircheck` or `filestat/dirstat`.

**Comment by ilyam8** [comment]
So `filecheck` is basically same as telegraf's [`filestat`](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/filestat) input.

`dircheck` is [`filecount`](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/filecount).

---

I suggested 

```yaml
stat:
  selector:
    include: [PATH1, ...]
    exclude: [PATH1, ...]
  stat_specific_option: ...
```

because if we name it `filecheck` we are not tied with `stat` related metrics and can expand the module later, not sure tho.

**Comment by ilyam8** [comment]
Oh, and globbing allows to add files to check in runtime.

**Comment by Ferroin** [comment]
> So `filecheck` is basically same as telegraf's [`filestat`](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/filestat) input.
> 
> `dircheck` is [`filecount`](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/filecount).

I see little value to splitting them, 95% of the code is likely to be identical for both modules. Perhaps just create a single module with a name like 'fsobjectcheck'?

> 
> I suggested
> 
> ```yaml
> stat:
>   selector:
>     include: [PATH1, ...]
>     exclude: [PATH1, ...]
>   stat_specific_option: ...
> ```
> 
> because if we name it `filecheck` we are not tied with `stat` related metrics and can expand the module later, not sure tho.

Hmm, yeah, I could see value to being able to match on xattr names/values and/or stuff like the attributes reported by `lsattr`.

Also, we may want to look into making this internally stateful with event-triggers via fanotify/inotify/kqueue for the side actually making the checks, `stat()` is _super_ expensive, so we should try to make this avoid calling it if at all possible (and by leveraging fanotify/inotify/kqueue properly, we could reduce calls to `stat()` to only when we know things have changed).

**Comment by ilyam8** [comment]
> 95% of the code is likely to be identical for both modules

I dont think it is 95%, but `fsobjectcheck` sounds not bad!

**Comment by ilyam8** [comment]
@nodiscc initial version is https://github.com/netdata/go.d.plugin/pull/445

See `limitations` in the description, my goal was to provide the functionality asap and improve later.

Any comments/suggestions are welcome.

**Comment by nodiscc** [comment]
Thanks a lot @ilyam8 @Ferroin  for working on this. The inital version of the module looks great and covers my initial use case. I will give it a try (once the next netdata release including your module is out, afraid I will not get the chance earlier) and report back. Thanks again

**Comment by nodiscc** [comment]
> I will give it a try and report back

I've been using the `filecheck` plugin for 2 years to monitor the last modification time of a few state files [[1]](https://github.com/nodiscc/xsrv/blob/master/roles/backup/templates/etc_netdata_go.d_filecheck.conf.d_rsnapshot.conf.j2) [[2]](https://github.com/nodiscc/xsrv/blob/master/roles/backup/templates/etc_netdata_health.d_filecheck.conf.d_rsnapshot.conf.j2), and it's working very reliably. Thanks again.
