### ISSUE TITLE
How to disable/remove unwanted charts from netdata default dashboard.

### ISSUE THREAD

**Issue by GemzzK** [netdata/netdata#9800]
want to know proper way to disbale/remove unwanted graphs/charts from right side menu. Like from below picture you can see highlighted areas that i want to remove from list and dont want to monitor. I`ve already changed options from netdata.conf file for ipv6 under [Plugins:proc] sockstat6 and snmp6 but no luck
![image](https://user-images.githubusercontent.com/67978637/90811010-4cd8ac80-e33d-11ea-8670-de6233af1027.png)

**Comment by thiagoftsm** [comment]
Hi @GemzzK ,

You will need to change your `netdata.conf` and set for the collector that you do not want to see charts the option `enabled = no`, for example, to disable information about IPV6 and udp, you need to change the following lines:

```
[ipv6.sockstat6_udp_sockets]
        # enabled = yes
```

Best regards!
