### ISSUE TITLE
Netdata Stream option 3. how to get this working and bit explanation

### ISSUE THREAD

**Issue by GemzzK** [netdata/netdata#9801]
I was exploring net data streaming options because i have 4 slaves sitting behind same public ip. Master confuses them and doesn't show all of them in list i have to restart netdata on master server and after doing that netdata shows different slave but doesn't show all of them. So, it only shows one slave at a time because they are sitting behind same public ip. So, i was searching through options and found the below option but how to get this working is not clearly mentioned/practiced by someone. Can someone let me know will this resolve my issue and how to configure this. So, netdata will take all my slaves as independent. Currently, i have same API key for all of my slaves but different hostnames.

```cmd
# -----------------------------------------------------------------------------
# 3. PER SENDING HOST SETTINGS, ON PARENT NETDATA
#    THIS IS OPTIONAL - YOU DON'T HAVE TO CONFIGURE IT

# This section exists to give you finer control of the parent settings for each
# child host, when the same API key is used by many netdata child nodes / proxies.
#
# Each netdata has a unique GUID - generated the first time netdata starts.
# You can find it at /var/lib/netdata/registry/netdata.public.unique.id
# (at the child).
#
# The host sending data will have one. If the host is not ephemeral,
# you can give settings for each sending host here.

[MACHINE_GUID]
    # enable this host: yes | no
    # When disabled, the parent will not receive metrics for this host.
    # THIS IS NOT A SECURITY MECHANISM - AN ATTACKER CAN SET ANY OTHER GUID.
    # Use only the API key for security.
    enabled = no

    # A list of simple patterns matching the IPs of the servers that
    # will be pushing metrics using this MACHINE GUID.
    # The metrics are received via the API port, so the same IPs
    # should also be matched at netdata.conf [web].allow connections from
    # and at stream.conf [API_KEY].allow from
    allow from = *

    # The number of entries in the database
    history = 3600

    # The memory mode of the database: save | map | ram | none | dbengine
    memory mode = save

    # Health / alarms control: yes | no | auto
    health enabled = yes

    # postpone alarms when the sender connects
    postpone alarms on connect seconds = 60

    # need to route metrics differently?
    # the defaults are the ones at the [API KEY] section
    #proxy enabled = yes | no
    #proxy destination = IP:PORT IP:PORT ...
    #proxy api key = API_KEY
    #proxy send charts matching = *
```

**Comment by roedie** [comment]
Hi,

This is not an issue with having multiple hosts behind the same IP. I have lots of hosts behind the same IP and it just works since all the hosts have a different GUID. Can you share your config of both the parent and child hosts?

Maybe there is also a hint in the error log.

**Comment by amoss** [comment]
The public IP address is not used to identify the child nodes - the hostname is used. If all four child nodes have the same hostname then they will not be shown as different nodes. There is an explicit setting in the `netdata.conf` that can be used to override the hostname for an agent if this is the problem.

Another possibility is that the four nodes all have the same `GUID` (perhaps they were copied from the same disk image?). Could you verify that the four nodes have distinct hostnames and `GUID`s? If they do then we will need to see some of the `error.log` from the parent node to try to diagnose the problem.

**Comment by GemzzK** [comment]
> Hi,
> 
> This is not an issue with having multiple hosts behind the same IP. I have lots of hosts behind the same IP and it just works since all the hosts have a different GUID. Can you share your config of both the parent and child hosts?
> 
> Maybe there is also a hint in the error log.

If i have to set GUID for multiple host behind same ip. how this can be achieved. Currently, im using API key for all hosts and the hosts behind same ip are having this issue. So, i thought of using GUID but im not sure how this can be done. I need to know which settings i have to modify to achieve tihs.

**Comment by roedie** [comment]
The API key can be the same for all hosts. I have that as well. The settings you post above are not going to help you. You need to figure out why only one hosts can connect. So, please have a look at my first reply.
