### ISSUE TITLE
Detect OOM killer over an app

### ISSUE THREAD

**Issue by mbarper** [netdata/netdata#9816]
##### Question summary

It is possible to detect with Netdata when the OS perform a OOM killer action over a running application?

##### OS / Environment

Ubuntu 18, CentOS7

##### Component Name

Netdata, maybe a Netdata plugin

##### Expected results

Get a metric with the OOM killer instances happened or a way to know some app is being killed.

**Comment by Saruspete** [comment]
Hello,

The only notification of OOM is when the kernel send some logs to syslog / dmesg. So I would rather suggest that you place this in your log management facility.

One way would be to modify a plugin collecting logs, like the [squidlog](https://github.com/netdata/go.d.plugin/tree/master/modules/squidlog) in go.plugin.d and parse /var/log/message (or other, depending on the syslog configuration) for OOM messages.

Among the data being parsed, it should handle cgroups identification, as it's the most common way to generate enough OOM, without the machine being unusable.

Cheers,

**Comment by alexmyczko** [comment]
It would also be great if that plugin you want to write would consider log entries of https://github.com/hakavlad/nohang.
