### ISSUE TITLE
Question: Getting Netdata to reload psql database list

### ISSUE THREAD

**Issue by merspieler** [netdata/netdata#9822]
##### Question summary
I've got an application, which creates and destroys psql databases on demand.  
Netdata lags behind, when it comes to displaying new databases as well as shows dropped databases as warnings. How do I get netdata to stay up-to-date with the changes on the databases?

It seems to me, that netdata only reads the lists of databases at startup.

Dropped databases stick around and give warnings while new ones are not shown at all.
##### OS / Environment
Debian Stable
Psql version 11+200+deb10u3
Netdata: v1.24.0-120-nightly

##### Expected results
I'd like to configure netdata to read the list of databases every 5 minutes or so.

**Comment by amoss** [comment]
@ilyam8 How complex would this be to implement - would it fit well with migrating the collector from python to go?

**Comment by ilyam8** [comment]
Migrating postgres to go is far from simple, we need to add this feature to python module

**Comment by ilyam8** [comment]
As for complexity - shouldnt be a lot of work, but i didnt really check how many changes we need to do.

**Comment by ilyam8** [comment]
> It seems to me, that netdata only reads the lists of databases at startup.

yes, indeed

**Comment by ilyam8** [comment]
Closing in favor of #13387. This is already implemented in go version.
