### ISSUE TITLE
Netdata still sends notifications to telegram, but notification is set to slient

### ISSUE THREAD

**Issue by joshuabeny1999** [netdata/netdata#9827]
##### Bug report summary

I enabled Netdata on my servers and disabled the disk_space time notification. Due it will fire every night for my backup disk.
![image](https://user-images.githubusercontent.com/55023662/91394672-fa1a5b80-e83a-11ea-8f69-2652ac2be56f.png)

But I still get the notifications via Telegram:
![image](https://user-images.githubusercontent.com/55023662/91396029-6006e300-e83b-11ea-9342-2d14be29dd25.png)

##### OS / Environment

```
joshua@joshuah:~$ uname -a; grep -Hv "^#" /etc/*release
Linux joshuah 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

```
joshua@joshuah:~$ $(ps aux | grep -E -o "[a-zA-Z/]+netdata ") -V
netdata v1.24.0
```
##### Component Name
/health/notifications

##### Steps To Reproduce

1. Setup netdata with kickstart.sh
2. Use `sudo /etc/netdata/edit-config health_alarm_notify.conf`and add Settings for telegram
3. Use `sudo /etc/netdata/edit-config health.d/disks.conf` and slience alarm
4. Restart netdata
5. Verify in GUI that alarm is set to slient.

##### Expected behavior

I would expect no notification sent to my telegram Bot for slienced alarms.

**Comment by thiagoftsm** [comment]
Hello @joshuabeny1999 ,

Firstly I apologize the delay to answer you, but I was in vacation.

Today I was working with this issue, and I observed that we have a string comparison to avoid send notifications inside our main script:

https://github.com/netdata/netdata/blob/d8e96eba6b241905e7ec84e75223a290acc67149/health/notifications/alarm-notify.sh.in#L637

this is working as expected.

I also observed that when I do a request for all alarms (`https://localhost:19999/api/v1/alarms?all`) we are sending to dashboard the information that the alarm is silent:

https://github.com/netdata/netdata/blob/d8e96eba6b241905e7ec84e75223a290acc67149/health/health_json.c#L177

but, we are not sending the alarm flag set as silent

https://github.com/netdata/netdata/blob/d8e96eba6b241905e7ec84e75223a290acc67149/health/health_json.c#L175

Considering what we have written in our [documentation](https://learn.netdata.cloud/guides/monitor/stop-notifications-alarms#edit-the-file-to-enable-silencing), I tend to agree with you that the dashboard should not show notification.

@cakrit , @amoss, @stelfrag, @underhood  before we fix this I have two questions for we discuss, we are already sending enough information for the dashboard does not show the alarm, but we are also missing the flag in the health.  Should we update the documentation saying that `to: silent` is not applied to dashboard? Or can I work with FrontEnd team to also remove alarms from dashboard when it is silent?

Best regards!

**Comment by joshuabeny1999** [comment]
Hi @thiagoftsm 
Thanks for your reply.

Hope you had a great vacation.

> https://github.com/netdata/netdata/blob/d8e96eba6b241905e7ec84e75223a290acc67149/health/notifications/alarm-notify.sh.in#L637
> 
> this is working as expected.
> 

For me this does not work. I set int the alarm config `to: slient` for the out_of_disk_space time alarm but I still get the telegram notification every night during backup. There a screenshot from last night:
![image](https://user-images.githubusercontent.com/55023662/91856552-00f40480-ec67-11ea-8952-6292636e4934.png)

Have I configured the` /etc/netdata/health_alarm_notify.conf` wrong?

I only changed the telegram part:
```sh
#------------------------------------------------------------------------------
# telegram (telegram.org) global notification options

# multiple recipients can be given like this:
#                  "CHAT_ID_1 CHAT_ID_2 ..."

# enable/disable sending telegram messages
SEND_TELEGRAM="YES"

# Contact the bot @BotFather to create a new bot and receive a bot token.
# Without it, netdata cannot send telegram messages.
TELEGRAM_BOT_TOKEN="<<MYBOTTOKEN>>"

# To get your chat ID send the command /getid to telegram bot @myidbot
# (https://t.me/myidbot). Each user also needs to open a conversation with the
# bot that will be sending notifications.
# If a role's recipients are not configured, a message will be sent to
# this chat id (empty = do not send a notification for unconfigured roles):
DEFAULT_RECIPIENT_TELEGRAM="<<MYTELEGRAMID>>"
```
The description of the variable `DEFAULT_RECIPIENT_TELEGRAM` says it send a notification if a role is unconfigured or unknown... So will be the slient associated to an unkown role? Need i add my telegram id elsewhere?

Best Regards
Joshua


---
/etc/netdata/health.d/disks.conf part with slient alarm:
```sh
# -----------------------------------------------------------------------------
# disk fill rate

# calculate the rate the disk fills
# use as base, the available space change
# during the last hour

# this is just a calculation - it has no alarm
# we will use it in the next template to find
# the hours remaining

template: disk_fill_rate
      on: disk.space
      os: linux freebsd
   hosts: *
families: *
  lookup: min -10m at -50m unaligned of avail
    calc: ($this - $avail) / (($now - $after) / 3600)
   every: 1m
   units: GB/hour
    info: average rate the disk fills up (positive), or frees up (negative) space, for the last hour


# calculate the hours remaining
# if the disk continues to fill
# in this rate

template: out_of_disk_space_time
      on: disk.space
      os: linux freebsd
   hosts: *
families: *
    calc: ($disk_fill_rate > 0) ? ($avail / $disk_fill_rate) : (inf)
   units: hours
   every: 10s
    warn: $this > 0 and $this < (($status >= $WARNING)  ? (48) : (8))
    crit: $this > 0 and $this < (($status == $CRITICAL) ? (24) : (2))
   delay: down 15m multiplier 1.2 max 1h
    info: estimated time the disk will run out of space, if the system continues to add data with the rate of the last hour
      to: slient
```

**Comment by thiagoftsm** [comment]
Hi @joshuabeny1999 ,

Fortunately everything was fine. Thank you!

> The description of the variable DEFAULT_RECIPIENT_TELEGRAM says it send a notification if a role is unconfigured or unknown... So will be the slient associated to an unkown role? Need i add my telegram id elsewhere?

I also have telegram configured in my side. The silent is not associated with `unknown` role and you do not need to add the id.

Now about the alarm you copied here, it looks like that there  was a typo error, please, take a look in the next line:

```
 to: slient
```

Instead `silent`, we have the  word `slient`. I think this is the source of the problem you are having.

Best regards!

**Comment by joshuabeny1999** [comment]
Hi @thiagoftsm 

That could be it. I will update the configuration from 'slient' to 'silent'. This is a nasty typo i made...

I will check if the notifications are gone this night and then will set this bug to close if it then is fixed. Or do you want to keep the bug open for this issue you had with the dashboard? For me it is fine if I login to netdata cloud or connect to the dashboard to still see the alarm, but I do not want to be notified via telegram.

What i found in the [documentation ](https://learn.netdata.cloud/guides/monitor/stop-notifications-alarms#edit-the-file-to-enable-silencing)(Could be also a typo):
![image](https://user-images.githubusercontent.com/55023662/91876704-520ef300-ec7d-11ea-93a7-c6546f304a0a.png)
There is once 'silence' written instead of 'silent'

Best Regards
Joshua

**Comment by thiagoftsm** [comment]
You can close this issue if your problem is fixed, we will have an internal discussion and I will open another issue for the dashboard if it is necessary. 

Thank you to show us this error in our documentation, I will create a PR to fix it right now.

**Comment by joshuabeny1999** [comment]
It worked. This night I did not get the notification. Thanks for your help.

**Comment by amoss** [comment]
The instructions in the notification are out of date - we should be asking users to use netdatacli to reload the the health instead.

**Comment by thiagoftsm** [comment]
Hi everybody,

I am glad we could help you @joshuabeny1999 !
@amoss I will bring an update for our documentation.

Best regards!
