### ISSUE TITLE
ARGH! Segfault

### ISSUE THREAD

**Issue by tinyhammers** [netdata/netdata#9830]
Hey guys...

For some reason this morning, my Netdata master box is not playing at all nicely.
From what I can see, Netdata is segfaulting.
I'm getting this error
```
[Thu Aug 27 09:19:59 2020] TCP: request_sock_TCP: Possible SYN flooding on port 19999. Sending cookies.  Check SNMP counters.
[Thu Aug 27 09:20:01 2020] STREAM_RECEIVER[29738]: segfault at 0 ip 00007fa7ccbce225 sp 00007fa79b916e18 error 4 in netdata[7fa7cc71f000+60f000
```
That is from `dmesg`

Have you come across this before? I'm not too sure what to do.
I have updated to 1.24.0, but the error is persisting.

**Comment by tinyhammers** [comment]
UPDATE:
Yesterday I updated a bunch of nodes to v1.24. Myself and my boyzzz have been looking to see if there are any discrepancies and running `curl 'http://127.0.0.1:19999/api/v1/info' |grep -A30 label` has shown that the virtualization value is null on the updated machines.
```"host_labels": {
                "_os_name": "Debian GNU/Linux",
                "_os_version": "8 (jessie)",
                "_kernel_version": "3.16.0-7-amd64",
                "_system_cores": "12",
                "_system_cpu_freq": "2400000000",
                "_system_ram_total": "16865558528",
                "_system_disk_space": "80530636800",
                "_architecture": "x86_64",
                "_virtualization": "",
                "_container": "unknown",
                "_container_detection": "none",
                "_virt_detection": "systemd-detect-virt",
                "_is_parent": "false",```
We've manually updated the value on one of the boxes and that seems to have stopped our master from crashing when it streams.

**Comment by tinyhammers** [comment]
UPDATE UPDATE:
Looks like its this issue https://github.com/netdata/netdata/pull/9715
I'm going to try pulling that fixed file to the boxes I updated yesterday, hopefully that should do it, so mebbe that file just needs merging into the release.
I'll update you when its done.

**Comment by amoss** [comment]
That fix went into the nightly after the release so grabbing the latest nightly may fix your problem.

**Comment by tinyhammers** [comment]
Jaysus. So that was a mission. Thought I'd sorted it but I missed machine somewhere and it kept crashing. 
Found it and updated the file and its all working now, so can confirm that has fixed it.
Cheers chaps 😃
