### ISSUE TITLE
exporting metrics sent - health alarms

### ISSUE THREAD

**Issue by wccropper** [netdata/netdata#9833]
##### Question summary
Moved from backend to exporting.conf. Now receiving alarms:
`exporting metrics sent = - 
percentage of metrics sent to the external database server`
It is unclear what is causing this and how to keep it from happening.
##### OS / Environment
CentOS7
##### Component Name
netdata.exporting alarms
##### Expected results
No new alarms after the move to exporting. Hundreds of emails a day about depreciation of the the backend became too much.

**Comment by vlvkobal** [comment]
> It is unclear what is causing this and how to keep it from happening.

![image](https://user-images.githubusercontent.com/22008543/91531482-8731e300-e915-11ea-8af9-a3e0f732a0db.png)
You receive the alarm when not 100% of metrics were sent to an external database.

Look at `netdata.exporting_<your_instance>_metrics` chart in "Netdata Monitoring" -> "exporting <your_instance>" section in the dashboard menu.
