### ISSUE TITLE
Migrating data from native/standard NetData database to MongoDB

### ISSUE THREAD

**Issue by geraldo-netto** [netdata/netdata#9841]
##### Question summary
Dear Friends, I'm trying to migrate all metrics from native/standard NetData database to MongoDB
and I could not find a specific tutorial on it which makes me guess that there is no straight forward process to do it
Do you happen to have by any chance, any suggestion on how to do it?
I'm interested not only in writing the new/real-time data that I saw I can do with the exporters configuration but, I also want to migrate all the past data

##### OS / Environment
8 AWS instances (16 CPUs, 64 GB RAM)
Red Hat 7.7
NetData 1.23.1-38 nightly

##### Component Name
Exporters, database engine

##### Expected results
Migrate/consolidate all past and current data from standard NetData database engine to MongoDB

Thank You Very Much/Kind Regards,
Geraldo Netto

**Comment by thiagoftsm** [comment]
Hello @geraldo-netto ,

To export all the data to a MongoDB, you can follow this [tutorial](https://learn.netdata.cloud/docs/agent/exporting/mongodb) and of course, if you have any other doubt, please let us know.

Best regards!

**Comment by geraldo-netto** [comment]
Hello @thiagoftsm ,

But will it synchronize MongoDB with past values?
As far as I understood, if the exporter is configured, it will start pushing data from now on, not the past data
Or am I missing something?

Thank You Very Much :)

**Comment by thiagoftsm** [comment]
Hello @geraldo-netto ,

Unfortunately this won't do synchronization, Netdata is starting to work with synchronization on streams, but is a working in progress, for sure it is a good idea to also have this for exporting and  I will talk with our team (@vlvkobal , @amoss and @dim08 ) about this. 

For while, until where I know, we only export from the moment the exporting is configured.

On the other hand, It is possible to do a workaround using our [web api](https://learn.netdata.cloud/docs/agent/web/api) to get the data and after this to write another tool to export the missing data.

You are welcome! :)
