### ISSUE TITLE
netdata-swagger.json produces error in Swagger Editor

### ISSUE THREAD

**Issue by OdysLam** [netdata/netdata#9846]
Swagger editor: https://registry.my-netdata.io/swagger/#/
Source file: https://github.com/netdata/netdata/blob/master/web/api/netdata-swagger.json

Possibly the .yaml file could be affected as well.

**Comment by OdysLam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix netdata-swagger syntax error](https://trello.com/c/M0NDcAl3/55-fix-netdata-swagger-syntax-error)

**Comment by OdysLam** [comment]
File at https://github.com/netdata/netdata/blob/master/web/api/netdata-swagger.json does not have the error. I assume that we have fixed the .json file but the change has not propagated to https://registry.my-netdata.io/netdata-swagger.json.

**Comment by underhood** [comment]
@OdysLam yes you are right the file that is served by link from https://learn.netdata.cloud/docs/agent/web/api serves file https://registry.my-netdata.io/netdata-swagger.json
and it is different from latest version from git which is ok:
![Screenshot from 2020-09-02 09-55-10](https://user-images.githubusercontent.com/6674623/91954841-a7411800-ed02-11ea-8d79-d40223706760.png)

So solving this will require figuring out who is responsible for https://registry.my-netdata.io/netdata-swagger.json and how it gets updated.

**Comment by underhood** [comment]
This was closed by @prologic updating the London3/CDN77 server.
In the future, there might be a discussion on how to better keep it up to date or host the API files elsewhere.

**Comment by prologic** [comment]
> This was closed by @prologic updating the London3/CDN77 server.
> In the future, there might be a discussion on how to better keep it up to date or host the API files elsewhere.

No discussion required. Added to release process https://github.com/netdata/internal/commit/d6b0531856053de2766387b25fde989f1cea2a7a
