### ISSUE TITLE
pam_unix(sudo:auth): conversation failed

### ISSUE THREAD

**Issue by fluxcap1** [netdata/netdata#9848]
I am running netdata (netdata-1.10.0-lp152.3.7.x86_64) on openSUSE_Leap_15_2. When I start the service I see these error messages in the service status -

```
# systemctl status netdata
● netdata.service - Real time performance monitoring
   Loaded: loaded (/usr/lib/systemd/system/netdata.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-08-28 08:37:16 PDT; 31min ago
  Process: 15752 ExecStartPre=/bin/chown -R netdata:netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 15742 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 15757 (netdata)
    Tasks: 26
   Memory: 79.6M
   CGroup: /system.slice/netdata.service
           ├─15757 /usr/sbin/netdata -P /run/netdata/netdata.pid -D
           ├─15773 /bin/bash /usr/lib/netdata/plugins.d/tc-qos-helper.sh 1
           ├─15795 /usr/bin/python /usr/lib/netdata/plugins.d/python.d.plugin 1
           └─15796 /usr/lib/netdata/plugins.d/apps.plugin 1

Aug 28 08:37:16 flux systemd[1]: Starting Real time performance monitoring...
Aug 28 08:37:16 flux systemd[1]: Started Real time performance monitoring.
Aug 28 08:37:17 flux sudo[16036]: pam_unix(sudo:auth): conversation failed
Aug 28 08:37:17 flux sudo[16036]: pam_unix(sudo:auth): auth could not identify password for [root]
````

The errors are last two lines, I can access the UI just fine. Do I need to configure pam for this?, if not how to fix this?

**Comment by Ferroin** [comment]
I'm fairly certain what you're seeingis an error message from one of the data collectors. A small handful of them need to use `sudo` to call out to the commands they use to get the data they collect, and like most of the other collectors they run a check at startup to see if they can run and then log an error if they can't.

**Comment by fluxcap1** [comment]
> I'm fairly certain what you're seeing is an error message from one of the data collectors. A small handful of them need to use `sudo` to call out to the commands they use to get the data they collect, and like most of the other collectors they run a check at startup to see if they can run and then log an error if they can't.

netdata is running as netdata user and as a group member of netdata, wheel. I have set NOPASSWD in sudoers for the members of wheel group (this is not the best thing to do but in order to debug I did this. The error still persists. Why not use pam type setup similar to cockpit? Please let me know if you need more information, I will get back to you as soon as I can.

**Comment by fluxcap1** [comment]
This issue is resolved after appending sudoers file -

````
netdata ALL=(ALL)       NOPASSWD: /usr/bin/smbstatus -P
````

**Comment by fluxcap1** [comment]
````pam_unix(sudo:auth): conversation failed````

exists.
