### ISSUE TITLE
Snappy/protobuf/... installation in docker image in order to use prothmethus remote write

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/netdata#9851]
##### Question summary

Hi thanks for this wonderful lib! I am trying to use the [promethus remote write](https://learn.netdata.cloud/docs/agent/exporting/prometheus/remote_write) functionality, but it says that I need to install snappy & protobuf and re-install netdata from source. However, I do not see such dependencies in [the netdata dockerfile](https://github.com/netdata/netdata/blob/master/packaging/docker/Dockerfile), neither do I see from [netdata:builder](https://hub.docker.com/r/netdata/builder/dockerfile) (or [here](https://github.com/netdata/helper-images/blob/master/builder/Dockerfile)). Thus, how shall I do that in the image? Shall I create my own Dockerfile? IMHO Netdata is soooooo popular that there must exist a solution already so I should not create my wheel.

Thanks very much!

##### OS / Environment
docker

##### Component Name
n/a

##### Expected results
n/a

**Comment by vlvkobal** [comment]
@Ferroin, @prologiс, your comments are welcome 😉.

**Comment by fzyzcjy** [comment]
@vlvkobal @Ferroin @prologic Thanks!

**Comment by Ferroin** [comment]
This is probably something we should add to our official Docker images. I actually thought we had it in them, but apparently i was mistaken.

**Comment by fzyzcjy** [comment]
@Ferroin Thanks! Looking forward to see the new image :)

**Comment by prologic** [comment]
Added to our backlog! Can't say exactly when we'll get to this, but hopefully soon as we're nearing the end of our "bug fix" rampage :)

**Comment by fzyzcjy** [comment]
@prologic Thanks! Btw, could you please provide some advice if I need to do it myself? IMHO I will need to copy the official dockerfile, modify it, and build on my own

**Comment by Ferroin** [comment]
@fzyzcjy In this case the Dockerfiles that need updated are actually in https://github.com/netdata/helper-images. https://github.com/netdata/helper-images/blob/master/builder/Dockerfile (which is what gets used to actually build Netdata for the final Docker image) will need to be updated to have the development packages for these, and https://github.com/netdata/helper-images/blob/master/base/Dockerfile (which is used as the base for the final image) needs the runtime libraries added.

**Comment by prologic** [comment]
@fzyzcjy I would _prefer_ if you contributed a PR to our Docker images as pointed out by @Ferroin above. This would be great, we can help you review this and get it merged!

**Comment by fzyzcjy** [comment]
Thanks and I will have a try!

**Comment by fzyzcjy** [comment]
PR created :) https://github.com/netdata/helper-images/pull/87

**Comment by prologic** [comment]
> @prologic @Ferroin PR created :) [netdata/helper-images#87](https://github.com/netdata/helper-images/pull/87)

Thank you! 🙇‍♂️ We will review this soon!

**Comment by prologic** [comment]
Done with https://github.com/netdata/helper-images/pull/87
