### ISSUE TITLE
Editing cgroups alarm

### ISSUE THREAD

**Issue by Pomdre** [netdata/netdata#9856]
I have alarms from cgroups but can not find the alarm file under /etc/netdata/health.d/ Where can I find it?
Thanks 👍

**Comment by thiagoftsm** [comment]
Hello @Pomdre ,

For you have alarms defined inside `/etc/netdata/health.d/ ` you need to edit yourself or to used the script `/etc/netdata/edit-config`. When you do not have alarms inside this directory, this means that you are using stock alarms that are stored inside `/usr/lib/netdata/conf.d/health.d/`

Best regards!
