### ISSUE TITLE
Support Opsgenie alarm notifications

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#9858]
#### Feature idea summary
Create alerts in Opsgenie.
We had a call with Atlassian and the first action point is to create alerts in OpsGenie from the agent. 

https://docs.opsgenie.com/docs/alert-api#create-alert
https://docs.opsgenie.com/docs/integrations-framework

##### Expected behavior
Add Opsgenie notifications, create alarms.

**Comment by tinyhammers** [comment]
+1,000,000,000 from me for this. Currently using Zapier to shunt stuff from Netdata to OpsGenie.
Native integration could be the one thing to redeem the horror that has been 2020 so far.

**Comment by thiagoftsm** [comment]
Hello @tinyhammers , 

If you have conditions, please, could you test the PR #9879? I used the official Opsgenie documentation to integrate Netdata with Opsgenie, but I do not have a big experience with the platform, so it is possible I missed something.

Thank you!

**Comment by tinyhammers** [comment]
Hey @thiagoftsm... 

That works perfectly. Alert came through as expected.
Are you able to set the priority of the alerts? So Critical alert is P1, Needs Attention is P2?
That would be the only thing I would say was needed.

Thanks for this 👍

**Comment by tinyhammers** [comment]
OpsGenie ranks alerts like this:

P1 - Critical
P2 - High
P3 - Moderate
P4 - Low
P5 - Informational

I'd say your choice is right for a default.

Users can filter alerts in the OpsGenie integration anyway, so you can assign your own priorities based on the alert contents if that's your cup of tea.

<img width="400" alt="Screenshot 2020-09-04 at 14 25 11" src="https://user-images.githubusercontent.com/878379/92244160-74da1b00-eeba-11ea-9c19-7c20c70a6901.png">
This is what I use currently for stuff coming on from Zapier.

**Comment by thiagoftsm** [comment]
> I'd say your choice is right for a default.

Thank you to give us this explanation!

I pushed an update for the PR few minutes ago and after we receive the answer we are waiting for, we will move forward the PR.
