### ISSUE TITLE
Can't claim node

### ISSUE THREAD

**Issue by UAnton** [netdata/netdata#9864]
##### Bug report summary
Can't claim node to the cloud. Get errors:
`Failed to claim node with the following error message: "Gateway Timeout"`
`Failed to claim node with the following error message:"Unknown HTTP error message"`

##### OS / Environment
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

 netdata v1.24.0-160-nightly

##### Steps To Reproduce

1. Install netdata
2. Try claim node

**Comment by arbabkhalil** [comment]
I am also facing the gateway timeout issue

**Comment by arbabkhalil** [comment]
@UAnton I am still facing this issue.

**Comment by arbabkhalil** [comment]
> I am also facing the gateway timeout issue

Got solved for me now, i think it is an intermittent issue.
