### ISSUE TITLE
Export dashboard results via http link and time range

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#9872]
I am trying to find a way to extract and archive the dashboard snapshots as part of our performance tests and see that there is a way to restrict the dashboard view to a certain time window using the "after/before" url parameters. Then I can manually choose to export the dashboard view in to a netdata archive/snapshot which can then be loaded in the future for analysis.

Is there a way for me to avoid this manual step and rather have the snapshot generated via a direct URL itself? This can help take automatic snaphots of the dashboard and archived against the test results for future analysis.

**Comment by amoss** [comment]
@jacekkolasa Do we have a way to do this via a URL?

**Comment by jacekkolasa** [comment]
@gamefundas unfortunately not. When you're taking snapshot, there are some metadata stored too, so some logic already written in javascript is needed. But i agree it would be good to have this snapshot feature available as an URL, automatically outputting the exported file. Right now the only automated solution which i think of could be something like `iMacros` (browser extension, in where you can record your navigation steps and repeat them automatically).

cc @dim08

**Comment by gamefundas** [comment]
What we have right now is pretty close to my requirements, I am able to query the dashboard by passing a time range. All I need to do is find a way to script the export call and the confirm button that shows up in the modal dialog. Perhaps Selenium in headless mode might do the trick. Will see if that does it. Thanks for the quick response. 

If there is a chance of this feature getting implemented then we can leave the issue open, else this can be closed.

**Comment by Saruspete** [comment]
I would love this feature too, but I soon realized it was made in JS by the dashboard, from the API output. 

I made a python script to somewhat recreate the format, but it's missing some charts, and the filtering may be bad as the colors in the charts are not properly kept (and sometimes, even the dimensions are messed-up)
https://github.com/Saruspete/netdata.tools/blob/master/netdata_export.py

If you can provide more details on how the exporting works in the dashboard (what format it expects, what ordering must be kept, etc...) it would be lovely !

**Comment by Saruspete** [comment]
Keep it open please.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.

**Comment by NikolayS** [comment]
@ilyam8 may we learn what was decided back then in 2020? The feature would be really great to have – Netdata turned out to be an excellent tool for various experiments and benchmarks – if you have a series of experiment runs and need to collect metrics with visualization, export and import done programmatically is exactly what's needed.

**Comment by vitabaks** [comment]
I'm agree with @NikolayS , we would really appreciate the automation of export netdata snapshots .

**Comment by ilyam8** [comment]
@NikolayS Nothing was decided to my knowledge. We like this feature and have added it to the product team evaluation feature request list.

cc @cpipilas
