### ISSUE TITLE
"web service up" badge is always grey

### ISSUE THREAD

**Issue by FedericoCeratto** [netdata/netdata#9873]
On Netdata 1.12.0 the "web service up" badge appears as always grayed-out. However the service is healthy and is reported healthy on the HTTP status chart.

Live example: http://5.255.91.77/api/v1/badge.svg?chart=httpcheck_codesearch.status&alarm=web_service_up&refresh=auto

Also, the badge does not contain the service name and there is no documentation on how to override the string "web service up".

**Comment by thiagoftsm** [comment]
Hi @FedericoCeratto ,

We are currently working to release Netdata 1.25, so I will suggest you to upgrade your Netdata.

I also remember we made upgrades for badges like [this](https://github.com/netdata/netdata/pull/7809) in recent new versions. You can also take a look in our [documentation](https://learn.netdata.cloud/docs/agent/web/api/badges) to see more options about badges.

Best regards!

**Comment by FedericoCeratto** [comment]
Thank you @thiagoftsm , I'm aware of the new releases but this is a production server.

**Comment by thiagoftsm** [comment]
All right @FedericoCeratto ,

I am not sure that is your case, but I remember other users that were using old versions, because they were not using our  [official repo](https://packagecloud.io/netdata/netdata), if this is your case, it is possible you add it to your list and start using the new features.

Best regards!

**Comment by amoss** [comment]
I'm closing this as it is a bug that affects a very old version of Netdata. If you upgrade to a new version and still see the bug then please reopen this issue for us to look into.
