### ISSUE TITLE
Estimate the remaining time of free RAM

### ISSUE THREAD

**Issue by JPAMaia** [netdata/netdata#9876]
Hi, I'm new to netdata and i would like to know if it's possible to estimate the remaining time until the memory runs out.
I've tried the following example https://learn.netdata.cloud/docs/agent/health/reference?q=units&size=n_20_n#example-3, but adapted to the mem.available chart.
However, it's not possible to use something like a linear regression function to calculate the remaining time?

**Comment by amoss** [comment]
We don't have any operators in the alarm expression language that would allow you to encode linear regression. The approach in the disk-space alarm (calculate the rate and calculate when it would intersect zero) is the most that can be done with the arithmetic operators that we support.

**Comment by JPAMaia** [comment]
Ok. Many thanks!
