### ISSUE TITLE
Alerting for process time

### ISSUE THREAD

**Issue by tinyhammers** [netdata/netdata#9883]
Hey guys...

Is it possible to measure the time a child process has been running for?
Had an issue where a mysql child process hung, created a massive ibdata1 file, which we got an alert about when the disk was 90% full.
Be nice to catch the processes if they hang around too long.

I've split out mysql from sql in apps_groups.conf, so I can see that specifically in User groups > Processes, but its showing me the time for the parent. Is there a way to dig further into the tree, then get an alert if one of the kids goes over specific time threshold. 

Thanks 😊

**Comment by thiagoftsm** [comment]
Hi @tinyhammers ,

Netdata has the chart `apps.uptime` that shows the period of time that a process is running. There are years that I do not work with mysql, but I remember it is a multi thread database instead a multi process. If you have conditions to give name for the threads, you can create a group specific for these threads and create an alarm for them.

Best regards!

**Comment by tinyhammers** [comment]
Ahh, OK. 
I'll look at that. 
Thanks 😃
