### ISSUE TITLE
netdata-installer.sh fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by RayGo75** [netdata/netdata#9884]
##### Bug report summary

I am trying to install netdata on my Ubuntu 20.04 laptop that is running slow. My hope is that it will help me figure out what I need to do to speed it up. This machine runs my PLEX media server so I need it to run as fast as possible. 
I used the instructions found on

https://pure-media.info/index.php/2017/07/20/set-real-time-performance-monitoring-netdata-ubuntu-16-04/ 

I just noticed that this site looks like it is from 2017, If there is a better site to use please let me know.
After cloning the netdata.git I went to the netdata directory and ran 'sudo ./netdata-installer.sh' and got several errors. I then found that I was missing libuv1-dev from a closed PR from this site. After installing that and running 'sudo ./netdata-installer.sh' I got a whole lot of different errors. 
The file I attached is the output of 'sudo ./netdata-installer.sh 2>&1 | tee -a ~/netdata-installer-output.log'

[netdata-installer-output.log](https://github.com/netdata/netdata/files/5176850/netdata-installer-output.log)

If you need any thing else to help me get this installed and running just let me know.

##### OS / Environment

Linux raygo-Ubuntu 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

```

```

##### Steps To Reproduce

1. ...
2. ...

##### Expected behavior

I hope I have included all the information you need to help me with this issue.
I look forward to hearing from you with a possible solution.

**Comment by Ferroin** [comment]
Can you check if you still have issues after following our [official installation guide](https://learn.netdata.cloud/docs/agent/packaging/installer)? I very strongly suspect that you're having issues due to the instructions in the article you linked being more than three years old (a _lot_ has changed since then).

**Comment by RayGo75** [comment]
That did the trick... Thank you.

**Comment by RayGo75** [comment]
Used the one step installation script and it worked flawlessly.
