### ISSUE TITLE
dbengine not built in Docker image due to unrecognized libjudy option

### ISSUE THREAD

**Issue by lassebm** [netdata/netdata#9889]
##### Bug report summary
`configure` fails with `configure: WARNING: unrecognized options: --with-libjudy`. See: https://travis-ci.com/github/netdata/netdata/jobs/381699001#L1691.

##### OS / Environment
Docker image.

##### Netdata version
`master` branch.
 
##### Component Name
Packaging.

##### Steps To Reproduce
Build Docker image.

##### Expected behavior
dbengine built in Docker image.

**Comment by Ferroin** [comment]
This actually affects all bundling of libJudy, not just the Docker images, PR will be up shortly to fix it.

@prologic

**Comment by Ferroin** [comment]
This actually got fixed by #9893, which i hadn't realized before going to work on a PR to fix it.
