### ISSUE TITLE
Alarms are not logged in netdata when the repeat option is enabled

### ISSUE THREAD

**Issue by JPAMaia** [netdata/netdata#9901]
##### Bug report summary
Netdata alarms do not appear in the netdata alarm log section when they are configured to repeat the notifications.

##### OS / Environment
```
Test environment composed of several virtual machines configured by Ansible v2.9.13
Virtual Machines OS: CentOS Linux release 8.1.1911 (Core)
```

##### Netdata version
 netdata v1.24.0 -> installed from script kickstart-static64.sh with arguments stable-channel and no-updates

##### Component Name
Health

##### Steps To Reproduce
Test-case scenario: mem.available alarm

1. Install and start netdata in remote VM
2. Copy ram.conf file into remote VM
ram.conf file:
```
alarm: ram_available
on: mem.available
os: linux
hosts: *
calc: ($avail + $system.ram.used_ram_to_ignore) * 100 / ($system.ram.used + $system.ram.cached + $system.ram.free + $system.ram.buffers)
units: %
every: 10s
warn: $this < (($status >= $WARNING)  ? (45) : (40))
crit: $this < (($status == $CRITICAL) ? (16) : (10))
delay: down 15m multiplier 1.5 max 1h
repeat: warning 60s critical 30s
info: estimated amount of RAM available for userspace processes, without causing swapping
to: sysadmin
```
3. Restart netdata with command `systemctl restart netdata`
4. execute command `stress --vm 4 --timeout 10s` in remote VM
5. alarm is triggered
![image](https://user-images.githubusercontent.com/61503518/92592912-32d51e80-f298-11ea-9c15-d8e4200b070a.png)
6. alarm is not logged
![image](https://user-images.githubusercontent.com/61503518/92592994-4b453900-f298-11ea-9079-476133d165ab.png)
7. comment repeat alarm line in ram.conf file:
```
alarm: ram_available
on: mem.available
os: linux
hosts: *
calc: ($avail + $system.ram.used_ram_to_ignore) * 100 / ($system.ram.used + $system.ram.cached + $system.ram.free + $system.ram.buffers)
units: %
every: 10s
warn: $this < (($status >= $WARNING)  ? (45) : (40))
crit: $this < (($status == $CRITICAL) ? (16) : (10))
delay: down 15m multiplier 1.5 max 1h
# repeat: warning 60s critical 30s
info: estimated amount of RAM available for userspace processes, without causing swapping
to: sysadmin
```
8. copy ram.conf file into remote VM
9. restart netdata with `systemctl restart netdata`
10. execute command `stress --vm 4 --timeout 10s` in remote VM
11. alarm is triggered
![image](https://user-images.githubusercontent.com/61503518/92593282-c60e5400-f298-11ea-9273-4f6009d89660.png)
12. alarm is logged
![image](https://user-images.githubusercontent.com/61503518/92593324-d32b4300-f298-11ea-8963-bee7d8a56d68.png)

##### Expected behavior
The alarm should be appear in the netdata alarms log in order to enable its behavioral analisis

**Comment by thiagoftsm** [comment]
Hello @JPAMaia ,

When the repeat was developed, the original idea was storing inside the alarm-log only when the events changed the status, like the alarms without `repeat`, and thanks this motive conditions like 

https://github.com/netdata/netdata/blob/a195025ec69bef0ebfaf0e979b41d8a9a0f4097c/health/health.c#L934

were inserted in the code, but I liked your idea.  Considering that other users could prefer to receive alarms like it is delivered today, I suggest we create an additional condition for health,  with this new option users will specify that they want to have the `repeated` alarms stored inside the alarm log and not only changes on alarm status. Do you agree with this idea? 

Best regards!

**Comment by JPAMaia** [comment]
Hi @thiagoftsm ,

Thanks for looking into this issue!
I agree with the idea of having an option to customize the alarm log. 
A suggestion would be to extend this and create an option to filter the wanted alarm status.
For example,
```
[health]
    # show the following status in alarm log
    log status: warning critical cleared
    # show all status in alarm log
    log status: all
    # show repeated alarms in alarm log
    log repeated: true
```
This could help users filter alarms and status they do not wish to see.

Best Regards!

**Comment by thiagoftsm** [comment]
Hi @JPAMaia ,

Considering that we have a conclusion about what is necessary according your last [comment](https://github.com/netdata/netdata/issues/9901#issuecomment-689573172), I converted the issue from `bug` to `feature request`.  I will talk with the product team (@dim08 ) for we bring this necessary feature.

Thank you very much for your suggestion!

Best regards!

**Comment by MrZammler** [comment]
This has been implemented in https://github.com/netdata/netdata/pull/12226

Thanks @JPAMaia for the report!
