### ISSUE TITLE
netdata suddenly doesn't start

### ISSUE THREAD

**Issue by ZerataX** [netdata/netdata#9906]
##### Bug report summary

Netdata immideately stops when trying to start it via the systemd file

##### OS / Environment
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=19.10
/etc/lsb-release:DISTRIB_CODENAME=eoan
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 19.10"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="19.10 (Eoan Ermine)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 19.10"
/etc/os-release:VERSION_ID="19.10"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=eoan
/etc/os-release:UBUNTU_CODENAME=eoan
```

##### Netdata version

netdata v1.24.0-204-nightly

##### Steps To Reproduce

1. I installed netdata (via the one line script)
 like a year ago and I now noticed that probably since end of August it stopped working (last message it send to a matrix channel)
2. Trying to reinstall (by running the script again, with `--reinstall`) didn't seem to change anything, but also doesn't give any errors during installation

[error.log](https://github.com/netdata/netdata/files/5198150/error.log)

systemctl just repeats this

```
Sep 09 16:03:08 phantom.dmnd.sh systemd[1]: Started Real time performance monitoring.
Sep 09 16:03:08 phantom.dmnd.sh netdata[15537]: SIGNAL: Not enabling reaper
Sep 09 16:03:08 phantom.dmnd.sh netdata[15537]: 2020-09-09 16:03:08: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Sep 09 16:03:12 phantom.dmnd.sh systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
Sep 09 16:03:12 phantom.dmnd.sh systemd[1]: netdata.service: Failed with result 'exit-code'.
```

**Comment by Ferroin** [comment]
@mfundul Based on the error log, this one looks like an issue with the dbengine.

**Comment by mfundul** [comment]
@ZerataX you've got some database corruption going on. You should delete your cache folder `var/cache/netdata/*` and start fresh.

**Comment by ZerataX** [comment]
yeah that seemed to have worked, thanks!
