### ISSUE TITLE
Ability to add alarm events as overlays 

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#9910]
#### Feature idea summary

I think it could useful to be able to overlay in some way counts or 'points' for alarm events on the Netdata charts. This way i could see on any chart what alarms are firing and when in case it helps me notice any interesting behavior.

##### Expected behavior

Something like a toggle on the alarms to turn the alarm overlay on/off on all charts - and when you hovered over any alarm event you see a quick popup of all the alarms triggered at that time: 

![image](https://user-images.githubusercontent.com/2178292/92726123-0d621680-f365-11ea-9abd-03fb1d88bd65.png)

**Comment by cakrit** [comment]
We should prioritize this. Related to #6523

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
