### ISSUE TITLE
Keep unix socket between restarts

### ISSUE THREAD

**Issue by zebulon501** [netdata/netdata#9916]
##### Bug report summary

When binding the netdata socket to a unix domain socket (i.e. "bind to = unix:/var/run/netdata.sock") and using it to a http reverse proxy in a docker container, each time netdata is restarted, the reverse proxy need to be restarted as the netdata socket is destroyed an recreated each time.

##### OS / Environment

```
Ubuntu 20.04
docker reverse proxy
```

##### Netdata version

`netdata v1.24.0`

##### Component Name

`libnetdata/socket/socket.c::create_listen_socket_unix()`

##### Steps To Reproduce

1. Configure netdata to bind to a unix domain socket
2. Map this socket to in a docker container running nginx serving as a reverse proxy to expose netdata --> netdata is accessible through the reverse proxy
3. Restart netdata --> netdata is no more accessible as the unix domain socket has changed
4. recreated the docker container --> netdata is accessible again

##### Expected behavior

Netdata reuse the existing scoket

**Comment by thiagoftsm** [comment]
Hi @zebulon501 ,

I am not sure about what is happening on docker, but I tested now Netdata direct on my host using nginx as reverse proxy and I could access Netdata trough my it after Netdata restart.

I used the following `netdata.conf`:

```
[web]
     bind to =  unix:/tmp/netdata/netdata.sock 
```

and my nginx.conf is:

```
server {
        listen       8082;
        server_name  localhost;
        location / {
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https; #New
            proxy_http_version 1.1;
            proxy_pass_request_headers on;
            proxy_set_header Connection "keep-alive";
            proxy_store off;
            gzip on;
            gzip_proxied any;
            gzip_types *;
            rewrite ^/netdata(/.*)$ $1 break;
            proxy_pass http://unix:/tmp/netdata/netdata.sock
         }

        #error_page  404              /404.html;
        location = /50x.html {
            root   /var/www/html;
        }
    }
```

How are you mapping your unix socket?

Best regards!

**Comment by zebulon501** [comment]
Hi @thiagoftsm, thanks for your quick answer!

I map directly the netdata socket in the docker container: `docker run ... -v /tmp/netdata/netdata.sock:/tmp/netdata/netdata.sock ...`. The issue is that when it gets removed and recreated during the start up of netdata, the container still uses the old i-node.

After some more testing, it appear that mapping the directory containing the Unix socket (`docker run ... -v /tmp/netdata:/tmp/netdata ...`) allows for clean restarts but then you need to create an additional directory to avoid exposing to much data in the container.

A nice addition would also be to add a note about this socket being destroyed and recreated in the documentation file `docs/Running-behind-nginx.md`.

Thanks for your time and best regards,

**Comment by thiagoftsm** [comment]
Hi @zebulon501 ,

> , it appear that mapping the directory containing the Unix socket (docker run ... -v /tmp/netdata:/tmp/netdata ...) allows for clean restarts but then you need to create an additional directory to avoid exposing to much data in the container.

I am not sure if this is a default docker behavior, but I am glad that this can fix the problem. @ilyam8, @prologic  and @Ferroin you have a longer experience with docker than me, is this the unique way to fix this problem?

> A nice addition would also be to add a note about this socket being destroyed and recreated in the documentation file docs/Running-behind-nginx.md.

I agree 100%, after we receive a new input from the teammates that I am asking some instructions, we will move forward with this.

You are welcome, let us know if you need any help. :)

**Comment by zebulon501** [comment]
Hi @thiagoftsm,

After some further investigations, the issue I'm facing comes from the fact that I've put the Unix socket in `/var/run/netdata`  and this folder is managed by the systemd service file, i.e. created when the service is started and disposed when the service is stopped. Adding `RuntimeDirectoryPreserve=yes` to the service files allows to preserve this directory.

**Comment by thiagoftsm** [comment]
>  Adding RuntimeDirectoryPreserve=yes to the service files allows to preserve this directory.

@Ferroin and @prologic , should we add this on our files to avoid problems for other users?

**Comment by prologic** [comment]
> > Adding RuntimeDirectoryPreserve=yes to the service files allows to preserve this directory.
> 
> @Ferroin and @prologic , should we add this on our files to avoid problems for other users?

Its possible it has other unintended side effects for other users with a different setup. so No I don't htink we should.. Documenting this is probably enough. cc @joelhans

**Comment by OdysLam** [comment]
@zebulon501 Welcome to our community. We are glad that you. managed to solve this :) 
Happy monitoring!
(p.s we also have our [forums](https://community.netdata.cloud))

**Comment by thiagoftsm** [comment]
Thank you @prologic !

I will work with @joelhans to document this.

Best regards!
