### ISSUE TITLE
High memory consumption on netdata 1.23.2

### ISSUE THREAD

**Issue by nikobearrr** [netdata/netdata#9920]
##### Bug report summary
I have noticed that one of our netdata instances is consuming too much memory ~4.6G
We run netdata on all our hosts (more than 50) and normally, as seen so far, netdata runs with approx. 250MB memory usage.
Netdata is deployed globally and is run with docker. All hosts run on the same OS. There is nothing special about this particular one.

##### OS / Environment

```
Linux server01 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
```
FROM netdata/netdata:v1.23.2
```

run in docker:

```Docker version 18.09.2, build 6247962```

##### Steps To Reproduce
I don't really know the steps to reproduce. We have been running netdata for 1y+ and this is the first time I have noticed. 
After restarting the consumption went back to normal.

![netdata_memory](https://user-images.githubusercontent.com/8693064/93017787-64255580-f5dc-11ea-8aaf-326dc3053a94.png)

I'd like to hear how can I debug this / what is interesting for the team to see when this happens?

**Comment by thiagoftsm** [comment]
Hi @nikobearrr ,

You are using an old Netdata, probably this problem was already fixed, because we had reports like this for distributions using kernels older than `4.19`.
Please, could you upgrade for the latest Netdata version to confirm this? 

Best regards!

**Comment by mfundul** [comment]
It's possible that you've got a lot of ephemeral containers that create hundreds of thousands of archived metrics. Can you also share the "Netdata Monitoring"->"dbengine" part of the dashboard?

`memory mode = dbengine` will keep track of all of them. A workaround is to reduce your `dbengine multihost disk space` [quota](https://github.com/netdata/netdata/blob/master/database/engine/README.md#configuration).

If `dbengine` is your issue here, another workaround is to use something like `memory mode = save`.

**Comment by nikobearrr** [comment]
Thank you both for your suggestions.

I have updated to 1.25.0 and I have seen the same. Something that I have forgotten was to check the logs. I could see there was showing an error about "cgroup". There was 1 container which was constantly restarting. I have fixed this and now it seems OK. I'd expect that goes together with what @mfundul suggested.

Here are the screenshots of dbengine when I was running 1.23.2 before I restarted the container. Can you tell me what should I look at here to find those archived metrics?

<img width="1470" alt="dbengine1" src="https://user-images.githubusercontent.com/8693064/93294129-c22f8400-f7fa-11ea-9dae-8a5c59cbbab6.png">

<img width="1457" alt="dbengine2" src="https://user-images.githubusercontent.com/8693064/93294120-be036680-f7fa-11ea-9743-da8752c02436.png">

**Comment by mfundul** [comment]
I wanted to take a look at the memory consumption graph for `dbengine`. Is this host a master in a parent-child set-up? Newer netdata versions use a multi-host DB (many children are stored in the same `dbengine` instance) whereas v1.23.2 creates a new instance for every child host.

For backward compatibility reasons multi-host DB is only enabled for new children that connect. If you delete your cache (`/var/cache/netdata/*`) all metrics will be stored in the multi-host `dbengine` instance by default. You also lose all your metric history and data. If this action drops your memory consumption significantly it's another sign that maybe there are too many archived metrics.

To get the total number of metrics from the multi-host `dbengine` instance of v1.25 you can run the command:
```
strings -n5 /var/cache/netdata/dbengine/*.mlf | grep DIMENSION | wc -l
```
You can compare this to the `used_by_collectors` metric of the `netdata.page_cache_stats` chart, which is the number of metrics actively being collected. If there is a large delta here it means there are many archived metrics that are not being collected any more.

**Comment by nikobearrr** [comment]
Hi @mfundul isn't the second picture showing the dbengine memory consumption? 

The host is not part of a parent-child setup. We only have registry, but we dont stream metrics. We deploy the netdata globally and export metrics to graphite. Each host reports for itself.

This is the relevant config:

```
[registry]
enabled = no
registry to announce = http://netdata-master:19999

[web]
default port = 19999
```

We also have `[plugins]` but that seems irrelevant. `netdata-master` is the registry

**Comment by mfundul** [comment]
> 
> 
> Hi @mfundul isn't the second picture showing the dbengine memory consumption?
> 

It does yes. However, archived metrics are part of the netdata database and not part of `dbengine`, so it doesn't show here. You can try running the above command anyway, it should tell us something.

**Comment by nikobearrr** [comment]
Since I have put the 1.25.0 and fixed the restarting container it seems fine ( < 300MB memory usage).
I ran the command on the current one and it shows `8318`. On the UI it says `Every second, Netdata collects 6929 metrics`

**Comment by mfundul** [comment]
> 
> 
> Since I have put the 1.25.0 and fixed the restarting container it seems fine ( < 300MB memory usage).
> I ran the command on the current one and it shows `8318`. On the UI it says `Every second, Netdata collects 6929 metrics`

That seems like a small amount of extra archived metrics. Let's see if this gets out of hand for some reason. Maybe you ran into another bug that caused this. There have been many bugfixes since v1.23.2

**Comment by mfundul** [comment]
Please reopen if the problem persists.

**Comment by nikobearrr** [comment]
Thank you for your time
