### ISSUE TITLE
Streaming Bandwidth optimization

### ISSUE THREAD

**Issue by ofirule** [netdata/netdata#9924]
### Background

I have multiple IOT devices running netdata v1.23.2
They are all deployed as follows:
- conf :  `update every = 10` and `memory mode = none`
- and only the following metrics are collected and streamed:  `system.cpu` `system.ram` `disk_space._`

My goal is to optimize the bandwidth on my devices since bandwidth over mobile data is expensive  

I took network dumps using `tcpdump` for 1 hour and while analyzing it I found : 

- netdata streaming is responsible for 2000-2200 packets.
- netdata streaming messages are quite big and not ideally serialized

### Expectations
- I was expecting that the amount of packets would be around -  (number of samples per hour) * 2 = (60 * 6) *2 = 720 . (The *2 is for tcp acks)

### Suggested solutions
- Adding a streaming buffer which send, all metrics in a single tcp msg. Also it may be configured to send all collected metrics data in X number of seconds. Will allow users to `update every` 1 sec but getting it in the remote stream host every X seconds, and will save a lot of tcp bandwidth overhead
- Use a known good serialize for the sent streams (I have had a very good experience with protobuf)
- Allow users to configure streams to use udp instead of tcp

**NOTE**: I may be unaware of some netdata internals and have done some speculations creating this analysis

**Comment by mfundul** [comment]
Thank you for your contribution. You are right that the streaming protocol is not efficient with relation to bandwidth or number of packets. However, it is not something we intend to do in the near future due to lack of resources.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
