### ISSUE TITLE
Problem with installing in raspberrypi

### ISSUE THREAD

**Issue by ZYL9** [netdata/netdata#9930]
About the dependence 
The other dependencies are 
libssl-dev 
libtool 
libuv1-dev
...
maybe more.
It took me all afternoon to set up...
hope you guys can improve the readme

**Comment by prologic** [comment]
@ZYL9 I'd really _recommend)_ you choose another installation method on a RPi, especially if it has an SD Card. Please choose either a Static Binary installation or Docker as appropriate for needs, both are well documented. Thanks!

**Comment by ZYL9** [comment]
yeah! 
After all the hard work, it was worth it!
thanks for your work!

**Comment by joelhans** [comment]
Glad to hear you got Netdata set up on your Raspberry Pi! Out of curiosity, did you use a kickstart script or Docker?

If you're interested, I just published this new guide about Raspberry Pis, Pi-hole, and Netdata just yesterday: https://learn.netdata.cloud/guides/monitor/pi-hole-raspberry-pi :wink:

**Comment by ZYL9** [comment]
to be honest I'm a super rookie
I dont know how Docker works
I got an error yesterday when I used Kickstart
it seems to be "Exec format error"
and I dont know why
so I download your project and try to build on my own
hope these would help you

**Comment by stelfrag** [comment]
Closing this. @ZYL9 please feel free to comment on your progress
