### ISSUE TITLE
prefix for metricname not working

### ISSUE THREAD

**Issue by git1977** [netdata/netdata#9933]
Hello all,

I am trying to attach a prefix to the metric names, but when I go to this url to see the metrics I see 'netdata_' instead of the prefix I am using in netdata.conf. I am sure I am doing something wrong, but not sure what it is.

`<ip:19999>api/v1/allmetrics?format=prometheus&help=yes`
Here is my netdata.conf I am using:
[global]
bind socket to IP = 0.0.0.0
[backend]
prefix = mynetmetric

**Comment by vlvkobal** [comment]
Have you restarted Netdata? You can check the effective configuration using the http://localhost:19999/netdata.conf API call.
