### ISSUE TITLE
netdata installer isn't detecting `ld`

### ISSUE THREAD

**Issue by marcelmfs** [netdata/netdata#9938]
##### Bug report summary
Had this error thrown at me on a fresh install server:

```
collect2: fatal error: cannot find ‘ld’ compilation terminated
```

##### OS / Environment
```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
# uname -a
Linux hostname 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
#
```

##### Netdata version
latest from fresh install 

##### Component Name
netdata installer

##### Steps To Reproduce
1. Had a fresh RHEL7 install, with no `ld`
2. run the installer

##### Expected behavior
the dependencies detection should include binutils for RHEL.

**Comment by thiagoftsm** [comment]
HI @marcelmfs ,

Please, can you verify that `ld` is in your `$PATH`?

Best regards!

**Comment by marcelmfs** [comment]
It wasn't installed. 

I'm only saying that the dependency detection step could include the check for the binutils package in RHEL. Otherwise the installer fails.

Best,

**Comment by prologic** [comment]
> It wasn't installed.
> 
> I'm only saying that the dependency detection step could include the check for the binutils package in RHEL. Otherwise the installer fails. I had to manually install the package in order to finish the installation, but if the installer have a dependency check, it might as well include binutils.

The installer already has this and __in fact__ already installs all required dependencies before attempting to build the software.

How did you install Netdata exactly?

> run the installer

This doesn't tell me much. Which installer did you run? There is __only_- one officially supported installer and that's our `kickstart-*.sh` script(s) which combine `./packaging/installer/install-required-packages.sh` and `./netdata-installer.sh`. If you ran the later from a Git checkout or Source dist tarball, then yeah I can see you'd be missing a significant no. of dependencies we already take care of installing for you on numerous platforms

**Comment by prologic** [comment]
Unless there is something specific, I'm closing this as "won't fix" as it is both well documented and well supported. I don't think we need to add autotools steps to detect `ld` in my opinion as any software that is built with language X requires tools for said language to be pre-installed. That's a given.

**Comment by Ferroin** [comment]
@prologic Actually, we don't explicitly pull in or check for binutils, we (sanely) assume that ensuring GCC is present will also ensure that binutils is present, because a vast majority of distros do not let you install any compiler without having a working assembler and linker.

However, I agree that this is not a normal case and is almost certainly a result of an abnormal configuration on the user's system (I've checked myself, you cannot install GCC on an RHEL system without also having binutils without actively going out of your way to do so, neither DNF nor YUM will let you, you have to invoke RPM directly to manually install the packages).

**Comment by marcelmfs** [comment]
The case happened as follows:
1) Got a server provisioned by one of our customers
2) Tried installing netdata using `bash <(curl -sS https://my-netdata.io/kickstart.sh)`
3) The install-required-packages.sh installed needed libraries
4) One of the builds failed with missing `ld`
5) Manually installed binutils
6) ran the installer again
