### ISSUE TITLE
Register netdata in Consul

### ISSUE THREAD

**Issue by kozicpetar** [netdata/netdata#9941]
Hi folks,
I found here closed task because inactivity with same question #3808

Can netdata register to Consul?
Because I'm using auto provision of netdata on newly installed virtual machines with Ansible and I'm using netdata with Prometheus that will be cool stuff in process of automation if netdata can be added in Consul.
Because Prometheus can doing discover and auto adding node to scrape from Consul.
On that way every new installed and registered netdata in Consul will be visible in Prometheus.
Thanks in advanced.

**Comment by prologic** [comment]
@kozicpetar Hi 👋I'm not aware of this being a first-class feature of Netdata. However that being said I would just register the service yourself via Consul API or CLI tooling. Tightly coupling this doesn't make sense to me. This is the same approach taken by (_for example_) [registrator](https://github.com/gliderlabs/registrator) LMK if this helps! 🤗

**Comment by OdysLam** [comment]
Hey @kozicpetar,

Did you manage to get this going, I would love to learn more about your experience, as I recently created a small sample application where I used Consul for dynamic configuration management of Netdata (https://github.com/netdata/netdata-community/tree/main/configuration-management/Consul). The automatic provision of netdata + service discovery + dynamic configuration creates an interesting story for Consul + Netdata Agent. What do you think?

**Comment by kozicpetar** [comment]
@OdysLam 
Hi, I didn't manage that. I don't have time right now, but I will check your project for sure. Thank you.

**Comment by ilyam8** [comment]
@kozicpetar the correct link is https://github.com/netdata/community/tree/main/configuration-management/consul-quickstart#configuration-management-with-consul
