### ISSUE TITLE
V1.25 stopped collecting MySQL data after install on Centos 

### ISSUE THREAD

**Issue by jamesnr** [netdata/netdata#9944]
New version 1.25 was installed last night and has stopped collecting any MySQL stats. I have tried a re-install, though the install process states that the latest version is already installed. What stats are needed or recommended process to reconnect?

Runnung under Plesk
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-862.3.3.el7.x86_64

I have restarted MySQL just in case as well, no joy. Anything else needed?

Thank you.

**Comment by ilyam8** [comment]
Hi

Lets check error logs

cd to netdata var log dir and

```cmd
cp /dev/null error.log
restart netdata.service
# wait a bit
grep -i mysql error.log
```

**Comment by jamesnr** [comment]
OK, that worked and kick-started the processes. MySQL data now being collected. Thank you.
