### ISSUE TITLE
How does one get the hostname on a netdata docker to follow the hostname of the server?

### ISSUE THREAD

**Issue by huntson** [netdata/netdata#9948]
##### Question summary
How does one get the hostname on a netdata docker to follow the hostname of the server?
##### OS / Environment
Synology 6.2
##### Expected results
I have a Synology unit running a netdata docker.  I'm very new to the docker world so I feel this might be an easy one however I'd like the docker to display the hostname in the upper left hand corner when on the netdata page rather than just saying netdata.  How would I go about doing this?

**Comment by prologic** [comment]
Hi @huntson There is a `-h/--hostname` option in `docker run`. See if this help you achieve your goals.

**Comment by aureliomarcoag** [comment]
You can also use `hostname` on docker-compose:
```
version: '3.8'
services:
  node01:
    image: "netdata-agent:01"
    hostname: node01
```

**Comment by Ferroin** [comment]
On top of both of the Docker-specific options mentioned above, you can actually override the hostname used by Netdata itself in all of it's alerts/dashboard/cloud functionality by setting the `hostname` key in the `[global]` section of `netdata.conf` for that install of Netdata.

**Comment by huntson** [comment]
> On top of both of the Docker-specific options mentioned above, you can actually override the hostname used by Netdata itself in all of it's alerts/dashboard/cloud functionality by setting the `hostname` key in the `[global]` section of `netdata.conf` for that install of Netdata.

The ideal solution would be something that allows netdata to read directly from the host that the docker is on rather than customizing the hostname on a per-docker basis.  I'm not above doing that however so please see my comments regarding that.

**Comment by huntson** [comment]
> Hi @huntson There is a `-h/--hostname` option in `docker run`. See if this help you achieve your goals.

Would you mind giving me step-by-step instructions on how/where to run this on my Synology install please?

**Comment by huntson** [comment]
> You can also use `hostname` on docker-compose:
> 
> ```
> version: '3.8'
> services:
>   node01:
>     image: "netdata-agent:01"
>     hostname: node01
> ```

Would you mind giving me step-by-step instructions on how/where to run this on my Synology install please?

**Comment by prologic** [comment]
@joelhans Would you mind updating our docs per the above comments from me, @Ferroin and @aureliomarcoag regarding the various ways to override/customize the hostname that is seen/used by the Netdata Agent when run in a Docker container?

Basically:

- Pass a `-h/--hostname` option to `docker run`
- Add a `hostname:` key/value pair into your `docker-compose.yml`
- Add a `hostname = ` key/value pair into your `[global]` section of your `netdata.conf`

Thanks! 🙇‍♂️

**Comment by huntson** [comment]
Still having the same issue years later.  No one here actually solved the problem: they just decided to find ways to manually write the hostname.  Silly
