### ISSUE TITLE
Silencing alarms documentation

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#9954]
https://learn.netdata.cloud/guides/monitor/stop-notifications-alarms should probably be mentioning or be merged with the info under https://learn.netdata.cloud/docs/agent/web/api/health#health-management-api 

https://learn.netdata.cloud/docs/agent/health/notifications should probably be linking to those two, or to a single merged doc that will be produced. 

FYI @prologic / @Ferroin / @ncmans / @knatsakis

**Comment by prologic** [comment]
cc @joelhans 

As an aside, this is great but this is entirely missing some UI and API calls. We (today) use AlertManager (https://alertmanager.corp.app.netdata.cloud/#/silences) to actively silence problematic alarms for a time period until we resolve the problematic alarm cause.

We need to build out something useful here. cc @manos-saratsis

**Comment by manos-saratsis** [comment]
@prologic we will centrally manage alarm configuration from Cloud at some point. Silencing alarms can be handled from there. In the meanwhile users can use the Netdata agent alarm configuration and shortly they will be able to silence email notifications for the Spaces&War Rooms they are in.
