### ISSUE TITLE
Set time interval in Netdata Cloud dashboards

### ISSUE THREAD

**Issue by MahdiGhiasi** [netdata/netdata#9955]
##### Feature idea summary

Currently user can set the time interval of all charts via a button on the top right corner on each node page. However, it is not available in the dashboards, and user has to use Shift+Scroll to change the intervals.

Having such control in dashboards makes them easier to use.

##### Expected behavior

Have a set of buttons for controlling the time interval of dashboards on top right corner, just like there is on the nodes page.

**Comment by ilyam8** [comment]
@manos-saratsis take a look

**Comment by manos-saratsis** [comment]
@MahdiGhiasi thx for your feedback and for using Netdata Cloud. We are working on a date-time picker that will let users configure the timeframe in every view including Dashboards.

**Comment by ilyam8** [comment]
Implemented
