### ISSUE TITLE
Questions related to a customized bandwidth graph.

### ISSUE THREAD

**Issue by olg33** [netdata/netdata#9959]
I have created a customized graph to display bandwidth arriving into two network interfaces: ens192 and ens224 in my Ubuntu 18.04 VM. 

Traffic is displayed using a dygraph chart as shown below:

                   div data-netdata="net.ens192"
                    data-dimensions="received"
                    data-title="Additional Comments"
                    data-chart-library="dygraph"
                    data-colors="#5DA5DA"
                    data-width="90%"
                    data-height="100%"
                    data-after="-300"
                    ></div>

                    div data-netdata="net.ens224"
                    data-dimensions="received"
                    data-title="Additional Comments"
                    data-chart-library="dygraph"
                    data-width="90%"
                    data-height="100%"
                    data-after="-300"
                    ></div>

Part of the resulting graph is as follows:

![Capture](https://user-images.githubusercontent.com/61751672/93644566-40914f00-f9d0-11ea-9968-b96634f62946.JPG)

First question is, Is there any way to remove or edit the legend in the red circle? I removed the

                   data-dimensions="received"

parameter but the legend still displayed.

My second question is, in addition to the dygraph chart, I'm also including a gauge chart to monitor the same interfaces:

                    div data-netdata="net.ens192"
                    data-dimensions="received"
                    data-title="Downstream"
                    data-chart-library="gauge"
                    data-width="15%"
                    data-height="15%"
                    data-after="-300"
                    data-colors="#00b3b3"
                    ></div>

                   div data-netdata="net.ens224"
                    data-dimensions="received"
                    data-title="Downstream"
                    data-chart-library="gauge"
                    data-width="15%"
                    data-height="15%"
                    data-after="-300"
                    data-colors="#05FFA1"
                    ></div>

But in spite of monitoring the same interfaces, the graph is displaying different values:

![Capture1](https://user-images.githubusercontent.com/61751672/93649939-2e68de00-f9db-11ea-8760-56b2fac79e59.JPG)

net.ens192 on dygraph chart shows 7.3 Mb/s while net.ens192 on gauge chart shows 5.40 Mb/s
net.ens224 on dygraph chart shows 725 Kb/s while net.ens224 on gauge chart shows 492 Kb/s

Could you tell why this behavior and how to correct it if possible?

Thank you.

**Comment by ilyam8** [comment]
> First question is, Is there any way to remove or edit the legend in the red circle? I removed the

It is possible to remove the legend completely - `data-legend="no"`

**Comment by olg33** [comment]
Thanks!
