### ISSUE TITLE
netdatacli not located in /usr/bin/

### ISSUE THREAD

**Issue by ionutnechita** [netdata/netdata#9961]
To stop netdata run:

  /usr/bin/netdatacli shutdown-agent

/usr/bin/netdatacli shutdown-agent
-bash: /usr/bin/netdatacli: No such file or directory

OS:
Debian 11 Sid

**Comment by thiagoftsm** [comment]
Hi @ionutnechita ,

I ran now a `whereis netdatacli` and I had this following output:

```
bash-5.0$ whereis netdatacli
netdatacli: /usr/sbin/netdatacli /opt/netdata/bin/netdatacli
```

Please, can you also run the command `whereis` on your System?

Best regards!

**Comment by ionutnechita** [comment]
whereis netdatacli
netdatacli: /usr/sbin/netdatacli

this error is displayed during installation.
it's something minor, just display. I think it can be fixed by kidnapping a fix.

./netdata-installer.sh
...
To stop netdata run:

/usr/bin/netdatacli shutdown-agent

**Comment by thiagoftsm** [comment]
Now it is clear what is happening, the `netdata-installer.sh` has a typo error as we can see in the next line:

https://github.com/netdata/netdata/blob/f6a1be4daac668a13c829963351875c236851d79/netdata-installer.sh#L1622

I will create a PR to fix now .

Thank you very much for your error report.

**Comment by thiagoftsm** [comment]
@vlvkobal  to complement my previous question, take a look in the Makefie.am:

https://github.com/netdata/netdata/blob/f6a1be4daac668a13c829963351875c236851d79/Makefile.am#L728

how it is expected inside `netdata-claim.sh`:

https://github.com/netdata/netdata/blob/f6a1be4daac668a13c829963351875c236851d79/claim/netdata-claim.sh.in#L92

And finally our uninstaller script:

https://github.com/netdata/netdata/blob/f6a1be4daac668a13c829963351875c236851d79/packaging/installer/netdata-uninstaller.sh#L463

Unless I am missing something, the `netdatacli` is  expected inside `/usr/sbin/`.

**Comment by OdysLam** [comment]
@ionutnechita Thanks for this fix and welcome to our community :)

**Comment by JohnPierpontMorgan** [comment]
i face smilliar problem

the command 
netdatacli-reload-health doesn't working ,
it says "command not found" , but there is literally netdatacli in netdata/bin folder
![example](https://github.com/netdata/netdata/assets/144676755/c6791032-4286-4aed-8d3f-f9c8edf88823)
