### ISSUE TITLE
Customizing colors on dygraph charts

### ISSUE THREAD

**Issue by olg33** [netdata/netdata#9975]
I'm creating a customized graph to display incoming and outgoing traffic on network interface.
I see that the default color for these graphs is green for received traffic and red for sent traffic::

![Capture](https://user-images.githubusercontent.com/61751672/93951787-43b07600-fd15-11ea-8c8d-dbc07daaaa88.JPG)

I'd like to know whether there is a way to customize these colors. I see that gauge charts have a `data-colors` parameter, but for some reason it doesn't seem to work on dygraph charts.

Thank you.

**Comment by ilyam8** [comment]
I am pretty sure it is possible to overwrite the color and i recall i used `data-colors` parameter and it worked.

@jacekkolasa correct me if i am wrong

**Comment by olg33** [comment]
In the above graph I have the following settings:

                   data-netdata="net.ens192"
                    data-dimensions="received"
                    data-chart-library="dygraph"
                    data-width="90%"
                    data-height="100%"
                    data-after="-300"
                    data-colors="#3366FF"
                   

                   data-netdata="net.ens192"
                    data-dimensions="sent"
                    data-append-options="absolute"
                    data-chart-library="dygraph"
                    data-colors=#3366FF
                    data-width="90%"
                    data-height="100%"
                    data-after="-300"
                    data-colors="#3366FF"
                   

3366FF is blue, but colors are still green and red.

**Comment by olg33** [comment]
After creating a new template from scratch, now it works. Not sure what was wrong but colors are now being taken,

Thanks.
