### ISSUE TITLE
use netdata docker  Monitor Nginx 

### ISSUE THREAD

**Issue by hope1234567hope** [netdata/netdata#9976]
use netdata docker  Monitor Nginx ，but  not find nginx data
The steps are as follows：
1 docker run -d --name=netdata \
  -p 19999:19999 \
  -v netdataconfig:/etc/netdata \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  netdata/netdata

2 Enable Nginx Stub_Status Module

3 go into container 
cd /etc/netdata 
vi python.d/nginx.conf  
update_every : 10
priority     : 90100
local:
  url     : 'http://localhost/stub_status'

but I don't see it on the interface？？？？？why？

**Comment by ilyam8** [comment]
Hi. Is nginx accesible from the netdata container?

```cmd
0 ~ $ docker exec -it netdata curl http://127.0.0.1/stub_status
```

**Comment by ilyam8** [comment]
I think it is not, to get your configuration working you need [`host` networking mode](https://docs.docker.com/network/host/)

**Comment by hope1234567hope** [comment]
thanks ilyam8 .
I found solutions;   Modify to host IP,not  localhost
vi python.d/nginx.conf
update_every : 10
priority : 90100
local:
url : 'http://192.168.137.153/stub_status'

but 
[root@forp ~]# python -m SimpleHTTPServer 8887 

then  other window  run  :   
[root@forp ~]# ip addr show dev ens33 | grep 192.      
    inet 192.168.137.153/24 brd 192.168.137.255 scope global noprefixroute dynamic ens33

[root@forp ~]# docker exec -it netdata curl http://192.168.137.153:8887    but this is hung.
why？

**Comment by hope1234567hope** [comment]
> thanks ilyam8 .
> I found solutions; Modify to host IP,not localhost
> vi python.d/nginx.conf
> update_every : 10
> priority : 90100
> local:
> url : 'http://192.168.137.153/stub_status'
> 
> but
> [root@forp ~]# python -m SimpleHTTPServer 8887
> 
> then other window run :
> [root@forp ~]# ip addr show dev ens33 | grep 192.
> inet 192.168.137.153/24 brd 192.168.137.255 scope global noprefixroute dynamic ens33
> 
> [root@forp ~]# docker exec -it netdata curl http://192.168.137.153:8887
> but this is hung. why？

sorry，a moment ago  ，docker exec -it netdata curl http://192.168.137.153:8887  has   a result

**Comment by ilyam8** [comment]
> I found solutions; Modify to host IP,not localhost

👍
