### ISSUE TITLE
Postgresql error in log in Version 11 

### ISSUE THREAD

**Issue by nklamann** [netdata/netdata#9980]
##### Bug report summary
In a postgres version 11 server the following lines occur in the error log of the database 

```
2020-09-22 12:22:38.216 UTC [13357] netdata@postgres ERROR:  function pg_last_xlog_receive_location() does not exist at character 112
2020-09-22 12:22:38.216 UTC [13357] netdata@postgres HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2020-09-22 12:22:38.216 UTC [13357] netdata@postgres STATEMENT:
        SELECT
            application_name,
            pg_xlog_location_diff(
              CASE pg_is_in_recovery()
                WHEN true THEN pg_last_xlog_receive_location()
                ELSE pg_current_xlog_location()
              END,
            sent_location) AS sent_delta,
            pg_xlog_location_diff(
              CASE pg_is_in_recovery()
                WHEN true THEN pg_last_xlog_receive_location()
                ELSE pg_current_xlog_location()
              END,
            write_location) AS write_delta,
            pg_xlog_location_diff(
              CASE pg_is_in_recovery()
                WHEN true THEN pg_last_xlog_receive_location()
                ELSE pg_current_xlog_location()
              END,
            flush_location) AS flush_delta,
            pg_xlog_location_diff(
              CASE pg_is_in_recovery()
                WHEN true THEN pg_last_xlog_receive_location()
                ELSE pg_current_xlog_location()
              END,
            replay_location) AS replay_delta
        FROM pg_stat_replication
        WHERE application_name IS NOT NULL;
```

##### OS / Environment

```
Linux mail 5.4.60-1-pve #1 SMP PVE 5.4.60-2 (Fri, 04 Sep 2020 10:24:50 +0200) x86_64 GNU/Linux
/etc/iredmail-release:1.3.1  PGSQL edition.
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"

```

##### Netdata version

 netdata v1.25.0

##### Component Name

collectors/python.d.plugin/postgres

##### Steps To Reproduce

1.Start an postgres cluster in version 11:

postgres (PostgreSQL) 11.7 (Debian 11.7-0+deb10u1)

2. ... netdata connects and builds the chartzs, but the error mentioned above occurs in the postgres log

##### Expected behavior

No errors in postgres log

**Comment by ilyam8** [comment]
Hi, thx for reporting.

@anayrat could you help?

**Comment by anayrat** [comment]
I wonder how could it be possible. We choose the query regarding postgres' version :
https://github.com/netdata/netdata/blob/f5c2b5595fd2e76431b3ea58eece807dd9b89244/collectors/python.d.plugin/postgres/postgres.chart.py#L655-L658

If we detect postgres above 9.6 we use the new default query:
https://github.com/netdata/netdata/blob/f5c2b5595fd2e76431b3ea58eece807dd9b89244/collectors/python.d.plugin/postgres/postgres.chart.py#L418-L447

Maybe netdata doesn't detect postgres version. Could you enable debug and provide more logs? It should tell us which version it has detected.
https://github.com/netdata/netdata/blob/f5c2b5595fd2e76431b3ea58eece807dd9b89244/collectors/python.d.plugin/postgres/postgres.chart.py#L1047-L1048

**Comment by nklamann** [comment]
On the same box existed a 9.6 Cluster some days ago. At which times takes netdata the inventory of the existing services ? How does it know that postgres exists at all ? 

Is it possible / useful to force netdata to scan again ? If yes, how can it be done ?

**Comment by ilyam8** [comment]
> Is it possible / useful to force netdata to scan again ?

Restart `netdata.service` will do.

**Comment by nklamann** [comment]
@anayrat 

I managed to start a debug run  and it gives the correct version but "superuser: False", maybe that is the culprit ?

`
2020-09-24 04:37:32: python.d DEBUG: plugin[main] : postgres[socket] was previously active, applying recovering settings
2020-09-24 04:37:32: python.d DEBUG: postgres[socket] : server version: 110007
2020-09-24 04:37:32: python.d DEBUG: postgres[socket] : superuser: False
2020-09-24 04:37:32: python.d DEBUG: postgres[socket] : discovered databases ['postgres', 'amavisd', 'fail2ban', 'iredadmin', 'iredapd', 'roundcubemail', 'vmail']
2020-09-24 04:37:32: python.d DEBUG: postgres[socket] : discovered secondaries: []
2020-09-24 04:37:32: python.d DEBUG: postgres[socket] : discovered replication slots: []
2020-09-24 04:37:32: python.d INFO: plugin[main] : postgres[socket] : check success

`
The postgres.conf is small  and came with iredmail
`
socket:
    name     : 'local'
    user     : 'netdata'
    password : 'ATB3TiL_4MkPGP_'
    database : 'postgres'
chart_cleanup : 0
`
`
root@mail /etc/netdata # grep ^local  /etc/postgresql/11/main/pg_hba.conf
local all     postgres   peer
local all     all                 md5
`
I changed netdata to superuser and it works
