### ISSUE TITLE
How to install python2 into a customized livecd rhel8 ISO within kickstart?

### ISSUE THREAD

**Issue by JsliStorSwift** [netdata/netdata#9983]
##### Question summary
How to install python2 into a customized livecd rhel8 ISO within kickstart?
I want to use kickstart to generate a customized RHEL8 LiveCD ISO. And I want to install Python 2 into this LiveCD ISO. But I don't know how to write the correct lines in kickstart.

the following is the content of my kickstart:

repo --name=base --baseurl=file:///var/www/html/rhel/8.1/os/x86_64/BaseOS
repo --name=appstream --baseurl=file:///var/www/html/rhel/8.1/os/x86_64/AppStream/
...
%packages
...
python2
...
%end
...
but the command "livecd-creator" always reported an error: Error creating Live CD : Failed to find package 'python2' : no package matched: python2.

When I replaced python2 with @python27:2.7/common, the error became Error creating Live CD : Failed to find group 'python27:2.7/common' : no such group: @python27:2.7/common.

So how can I install Python 2 into my LiveCD ISO?

##### OS / Environment
RHEL8

##### Component Name
livecd-creator

##### Expected results
no error

**Comment by OdysLam** [comment]
Hey @JsliStorSwift ,

Welcome to our community. I think this resource is a good start for your question! https://www.linux-live.org/

Closing this issue, as it's not related to netdata.
