### ISSUE TITLE
Centos 7 Apache charts nolonger displaying correctly

### ISSUE THREAD

**Issue by jamesnr** [netdata/netdata#9987]
The Apache charts are not providing the totals by say connection type on the right-hand side after upgrade to version 1.25. This is only for the Apache stats. Any ideas how to get the stats working, also the lines clearly drawn again?

![image](https://user-images.githubusercontent.com/71431693/94153884-390cf280-fe75-11ea-8305-01eeedbc9527.png)

```cmd
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

#
##### Netdata version
netdata d5e1197
 
Thank you.

**Comment by ilyam8** [comment]
Hi. Could you

- stop `netdata.service`
- `rm -rf` dbengine data (this step deletes all your historical data)
- start `netdata.service`

```cmd
[ilyam@ilyam-pc ~]$ systemctl stop netdata
[ilyam-pc ilyam]# cd /opt/netdata/var/cache/netdata/dbengine/
[ilyam-pc dbengine]# rm -rf *
[ilyam-pc dbengine]# systemctl restart netdata
[ilyam-pc dbengine]#
```

**Comment by ilyam8** [comment]
And share `grep -i apache error.log` output after the restart

**Comment by jamesnr** [comment]
Thanks for the fast response!! In regards to the directory /opt/netdata/var/cache/netdata/dbengine/, I can get to /opt/netdata/var/cache/netdata/ but this directory is empty. Any ideas? Apologies.

**Comment by ilyam8** [comment]
It depends on you install path. Try `var/cache/netdata/dbengine/.

**Comment by jamesnr** [comment]
Thanks, yes I did look, missed it. 

Hasn't made any difference. I missed getting you the error log. Is it a must as I'll redo and collect the data, the log file is particularly large at the moment.

**Comment by ilyam8** [comment]
Lets see, do as `root`

```cmd
systemctl restart netdata.service
cp /dev/null /var/log/netdata/error.log
systemctl start netdata.service
# wait a bit
grep -i apache /var/log/netdata/error.log
```

**Comment by jamesnr** [comment]
OK, done, thank you for your patience. I have

2020-09-24 20:01:30: go.d INFO: main[main] looking for 'apache.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
2020-09-24 20:01:30: go.d INFO: main[main] found '/usr/lib/netdata/conf.d/go.d/apache.conf
2020-09-24 21:01:30: charts.d: INFO: apache: is disabled. Add a line with apache=force in '/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2020-09-24 20:01:30: go.d ERROR: lighttpd[local] error on parsing response from http://127.0.0.1/server-status?auto : found 'BusyWorkers',apache data
2020-09-24 20:01:30: go.d ERROR: apache[local] http://localhost/server-status?auto returned HTTP status 403
2020-09-24 20:01:30: go.d ERROR: apache[local] check failed
2020-09-24 20:01:30: go.d INFO: apache[local] check success
2020-09-24 20:01:30: go.d INFO: apache[local] started, data collection interval 1s
2020-09-24 20:01:30: go.d WARNING: web_log[apache] check failed: creating log reader: no matched files
2020-09-24 20:01:30: go.d ERROR: web_log[apache] check failed
2020-09-24 20:01:30: go.d WARNING: web_log[apache] check failed: creating log reader: open /var/log/apache2/access_log: permission denied
2020-09-24 20:01:30: go.d ERROR: web_log[apache] check failed
2020-09-24 20:01:30: go.d WARNING: web_log[apache] check failed: creating log reader: no matched files
2020-09-24 20:01:30: go.d ERROR: web_log[apache] check failed
2020-09-24 20:01:30: go.d WARNING: web_log[apache_vhosts] check failed: creating log reader: no matched files
2020-09-24 20:01:30: go.d ERROR: web_log[apache_vhosts] check failed
2020-09-24 20:01:30: go.d ERROR: prometheus[apache_exporter_local] Get "http://127.0.0.1:9117/metrics": dial tcp 127.0.0.1:9117: connect: connection refused
2020-09-24 20:01:30: go.d ERROR: prometheus[apache_exporter_local] check failed
2020-09-24 20:01:30: go.d ERROR: prometheus[apache_flink_exporter_local] Get "http://127.0.0.1:9160/metrics": dial tcp 127.0.0.1:9160: connect: connection refused
2020-09-24 20:01:30: go.d ERROR: prometheus[apache_flink_exporter_local] check failed
2020-09-24 21:01:30: python.d ERROR: plugin: main: cannot load '/etc/netdata/python.d/apache.conf' : [Errno 2] No such file or directory: '/etc/netdata/python.d/apache.conf'. Will try stock version.
2020-09-24 20:01:30: go.d ERROR: prometheus[apache_flink_metrics_reporter_local] Get "http://127.0.0.1:9249/metrics": dial tcp 127.0.0.1:9249: connect: connection refused
2020-09-24 20:01:30: go.d ERROR: prometheus[apache_flink_metrics_reporter_local] check failed
2020-09-24 21:01:31: python.d INFO: apache: localhost: check() => [FAILED]
2020-09-24 21:01:31: python.d INFO: apache: localipv4: check() => [OK]
2020-09-24 21:01:31: python.d INFO: apache: localipv6: check() => [DROPPED] (already served by another job)
2020-09-24 21:01:31: python.d ERROR: web_log: apache_log: /var/log/apache2/access.log not readable or not exist
2020-09-24 21:01:31: python.d INFO: web_log: apache_log: check() => [FAILED]
2020-09-24 21:01:31: python.d ERROR: web_log: apache_log2: /var/log/apache2/access_log not readable or not exist
2020-09-24 21:01:31: python.d INFO: web_log: apache_log2: check() => [FAILED]
2020-09-24 21:01:31: python.d ERROR: web_log: apache_log3: /var/log/httpd/access_log not readable or not exist
2020-09-24 21:01:31: python.d INFO: web_log: apache_log3: check() => [FAILED]
2020-09-24 21:01:31: python.d ERROR: web_log: apache_vhosts_log: /var/log/apache2/other_vhosts_access.log not readable or not exist
2020-09-24 21:01:31: python.d INFO: web_log: apache_vhosts_log: check() => [FAILED]
2020-09-24 21:01:31: python.d ERROR: web_log: apache_cache: /var/log/apache/cache.log not readable or not exist
2020-09-24 21:01:31: python.d INFO: web_log: apache_cache: check() => [FAILED]
2020-09-24 21:01:31: python.d ERROR: web_log: apache2_cache: /var/log/apache2/cache.log not readable or not exist
2020-09-24 21:01:31: python.d INFO: web_log: apache2_cache: check() => [FAILED]
2020-09-24 21:01:33: netdata INFO  : PLUGINSD[python.d] : RRD database for chart 'apache_local.workers' on host xxxx' is 0.03437 secs in the future (counter #1812667, update #4). Adjusting it to current time.
2020-09-24 21:01:33: netdata INFO  : PLUGINSD[python.d] : RRD database for chart 'apache_local.bytesperreq' on host xxxx' is 0.03445 secs in the future (counter #1812667, update #4). Adjusting it to current time.
2020-09-24 21:01:33: netdata INFO  : PLUGINSD[python.d] : RRD database for chart 'apache_local.connections' on host xxxx' is 0.03456 secs in the future (counter #1812667, update #4). Adjusting it to current time.
2020-09-24 21:01:33: netdata INFO  : PLUGINSD[python.d] : RRD database for chart 'apache_local.bytespersec' on host xxxx' is 0.03468 secs in the future (counter #1812667, update #4). Adjusting it to current time.

**Comment by ilyam8** [comment]
i see, do

```cmd
sudo ls -l /var/lib/netdata/lock/
```

---

to fix the bug go to `/etc/netdata/` and

as `netdata` or `root` user

` ./edit-config python.d.conf

and change 

`# apache: yes` to `apache: no` in there

---

i will check why we have both go and py `apache_local` jobs running (it seems because of `override` name in the python apache config)

**Comment by ilyam8** [comment]
```cmd
2020-09-24 21:01:31: python.d INFO: apache: localhost: check() => [FAILED]
2020-09-24 21:01:31: python.d INFO: apache: localipv4: check() => [OK]
```

hold on, it is old version of `python.d.plugin`, current log messages

https://github.com/netdata/netdata/blob/f47b430780b812b37b5bba241982c4741dc934b7/collectors/python.d.plugin/python.d.plugin.in#L643-L646

**Comment by ilyam8** [comment]
So the issue is having both python and go version of apache collector enabled.

What is your netdata version? (you said v1.25 but it seems it is not). How did you install it?

**Comment by jamesnr** [comment]
It was installed with a nightly update. Not manually. I can do a full manual update. 

I haven't edited the "python.d.conf". Still need to?

**Comment by ilyam8** [comment]
> I can do a full manual update.

do

**Comment by jamesnr** [comment]
Have done so. Thanks

**Comment by ilyam8** [comment]
fixed?

**Comment by jamesnr** [comment]
No. Have restarted netdata too. Still the same.

**Comment by ilyam8** [comment]
I dont understand how come you have old `python.d.plugin` 😄 

lets do

```cmd
ps faxu | grep "[n]etdata"
ls -l /usr/libexec/netdata/plugins.d/ | grep .d.plugin
cat /usr/libexec/netdata/plugins.d/python.d.plugin
```

**Comment by jamesnr** [comment]
Done - still the same. Have restarted netdata too and refreshed the page. Still the same.

**Comment by ilyam8** [comment]
Share the commands output, they do nothing, i need the output

**Comment by jamesnr** [comment]
As requested:
ps faxu | grep "[n]etdata"
netdata  22068  1.8  0.1 344784 149856 ?       Ssl  Sep24  10:58 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global process scheduling policy keep -W set global OOM score keep
netdata  22084  1.0  0.0 212992 25900 ?        Sl   Sep24   6:12  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata  22099  0.4  0.0 731068 22768 ?        Sl   Sep24   2:28  \_ /usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata  31137  4.7  0.0  18372  4900 ?        S    06:27   5:48  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
netdata  44496  0.1  0.0   9700  1520 ?        S    08:28   0:00  \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1

ls -l /usr/libexec/netdata/plugins.d/ | grep .d.plugin
-rwxr-xr-x 1 root root       19123 Sep 14 09:08 charts.d.plugin
-rwxr-xr-x 1 root netdata 22581248 Aug  4 13:49 go.d.plugin
-rwxr-xr-x 1 root root       11060 Sep 14 09:08 node.d.plugin
-rwxr-xr-x 1 root root       14803 Sep 14 09:08 python.d.plugin

cat /usr/libexec/netdata/plugins.d/python.d.plugin
#!/usr/bin/env bash
'''':; exec "$(command -v python || command -v python3 || command -v python2 ||
echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''

# -*- coding: utf-8 -*-
# Description:
# Author: Pawel Krupa (paulfantom)
# Author: Ilya Mashchenko (l2isbad)
# SPDX-License-Identifier: GPL-3.0-or-later

import gc
import os
import sys
import threading

from re import sub
from sys import version_info, argv
from time import sleep

GC_RUN = True
GC_COLLECT_EVERY = 300

PY_VERSION = version_info[:2]

USER_CONFIG_DIR = os.getenv('NETDATA_USER_CONFIG_DIR', '/etc/netdata')
STOCK_CONFIG_DIR = os.getenv('NETDATA_STOCK_CONFIG_DIR', '/usr/lib/netdata/conf.d')

PLUGINS_USER_CONFIG_DIR = os.path.join(USER_CONFIG_DIR, 'python.d')
PLUGINS_STOCK_CONFIG_DIR = os.path.join(STOCK_CONFIG_DIR, 'python.d')


PLUGINS_DIR = os.path.abspath(os.getenv(
    'NETDATA_PLUGINS_DIR',
    os.path.dirname(__file__)) + '/../python.d')


PYTHON_MODULES_DIR = os.path.join(PLUGINS_DIR, 'python_modules')

sys.path.append(PYTHON_MODULES_DIR)

from bases.loaders import ModuleAndConfigLoader  # noqa: E402
from bases.loggers import PythonDLogger  # noqa: E402
from bases.collection import setdefault_values, run_and_exit  # noqa: E402

try:
    from collections import OrderedDict
except ImportError:
    from third_party.ordereddict import OrderedDict

BASE_CONFIG = {'update_every': os.getenv('NETDATA_UPDATE_EVERY', 1),
               'priority': 60000,
               'autodetection_retry': 0,
               'chart_cleanup': 10,
               'penalty': True,
               'name': str()}


MODULE_EXTENSION = '.chart.py'
OBSOLETE_MODULES = ['apache_cache', 'gunicorn_log', 'nginx_log', 'cpufreq', 'cpuidle', 'mdstat', 'linux_power_supply']


def module_ok(m):
    return m.endswith(MODULE_EXTENSION) and m[:-len(MODULE_EXTENSION)] not in OBSOLETE_MODULES


ALL_MODULES = [m for m in sorted(os.listdir(PLUGINS_DIR)) if module_ok(m)]


def parse_cmd():
    debug = 'debug' in argv[1:]
    trace = 'trace' in argv[1:]
    override_update_every = next((arg for arg in argv[1:] if arg.isdigit() and int(arg) > 1), False)
    modules = [''.join([m, MODULE_EXTENSION]) for m in argv[1:] if ''.join([m, MODULE_EXTENSION]) in ALL_MODULES]
    return debug, trace, override_update_every, modules or ALL_MODULES


def multi_job_check(config):
    return next((True for key in config if isinstance(config[key], dict)), False)


class RawModule:
    def __init__(self, name, path, explicitly_enabled=True):
        self.name = name
        self.path = path
        self.explicitly_enabled = explicitly_enabled


class Job(object):
    def __init__(self, initialized_job, job_id):
        """
        :param initialized_job: instance of <Class Service>
        :param job_id: <str>
        """
        self.job = initialized_job
        self.id = job_id  # key in Modules.jobs()
        self.module_name = self.job.__module__  # used in Plugin.delete_job()
        self.recheck_every = self.job.configuration.pop('autodetection_retry')
        self.checked = False  # used in Plugin.check_job()
        self.created = False  # used in Plugin.create_job_charts()
        if self.job.update_every < int(OVERRIDE_UPDATE_EVERY):
            self.job.update_every = int(OVERRIDE_UPDATE_EVERY)

    def __getattr__(self, item):
        return getattr(self.job, item)

    def __repr__(self):
        return self.job.__repr__()

    def is_dead(self):
        return bool(self.ident) and not self.is_alive()

    def not_launched(self):
        return not bool(self.ident)

    def is_autodetect(self):
        return self.recheck_every


class Module(object):
    def __init__(self, service, config):
        """
        :param service: <Module>
        :param config: <dict>
        """
        self.service = service
        self.name = service.__name__
        self.config = self.jobs_configurations_builder(config)
        self.jobs = OrderedDict()
        self.counter = 1

        self.initialize_jobs()

    def __repr__(self):
        return "<Class Module '{name}'>".format(name=self.name)

    def __iter__(self):
        return iter(OrderedDict(self.jobs).values())

    def __getitem__(self, item):
        return self.jobs[item]

    def __delitem__(self, key):
        del self.jobs[key]

    def __len__(self):
        return len(self.jobs)

    def __bool__(self):
        return bool(self.jobs)

    def __nonzero__(self):
        return self.__bool__()

    def jobs_configurations_builder(self, config):
        """
        :param config: <dict>
        :return:
        """
        counter = 0
        job_base_config = dict()

        for attr in BASE_CONFIG:
            job_base_config[attr] = config.pop(attr, getattr(self.service, attr, BASE_CONFIG[attr]))

        if not config:
            config = {str(): dict()}
        elif not multi_job_check(config):
            config = {str(): config}

        for job_name in config:
            if not isinstance(config[job_name], dict):
                continue

            job_config = setdefault_values(config[job_name], base_dict=job_base_config)
            job_name = sub(r'\s+', '_', job_name)
            config[job_name]['name'] = sub(r'\s+', '_', config[job_name]['name'])
            counter += 1
            job_id = 'job' + str(counter).zfill(3)

            yield job_id, job_name, job_config

    def initialize_jobs(self):
        """
        :return:
        """
        for job_id, job_name, job_config in self.config:
            job_config['job_name'] = job_name
            job_config['override_name'] = job_config.pop('name')

            try:
                initialized_job = self.service.Service(configuration=job_config)
            except Exception as error:
                Logger.error("job initialization: '{module_name} {job_name}' "
                             "=> ['FAILED'] ({error})".format(module_name=self.name,
                                                              job_name=job_name,
                                                              error=error))
                continue
            else:
                Logger.debug("job initialization: '{module_name} {job_name}' "
                             "=> ['OK']".format(module_name=self.name,
                                                job_name=job_name or self.name))
                self.jobs[job_id] = Job(initialized_job=initialized_job,
                                        job_id=job_id)
        del self.config
        del self.service


class Plugin(object):
    def __init__(self):
        self.loader = ModuleAndConfigLoader()
        self.modules = OrderedDict()
        self.sleep_time = 1
        self.runs_counter = 0

        user_config = os.path.join(USER_CONFIG_DIR, 'python.d.conf')
        stock_config = os.path.join(STOCK_CONFIG_DIR, 'python.d.conf')

        Logger.debug("loading '{0}'".format(user_config))
        self.config, error = self.loader.load_config_from_file(user_config)

        if error:
            Logger.error("cannot load '{0}': {1}. Will try stock version.".format(user_config, error))
            Logger.debug("loading '{0}'".format(stock_config))
            self.config, error = self.loader.load_config_from_file(stock_config)
        if error:
            Logger.error("cannot load '{0}': {1}".format(stock_config, error))

        self.do_gc = self.config.get("gc_run", GC_RUN)
        self.gc_interval = self.config.get("gc_interval", GC_COLLECT_EVERY)

        if not self.config.get('enabled', True):
            run_and_exit(Logger.info)('DISABLED in configuration file.')

        self.load_and_initialize_modules()
        if not self.modules:
            run_and_exit(Logger.info)('No modules to run. Exit...')

    def __iter__(self):
        return iter(OrderedDict(self.modules).values())

    @property
    def jobs(self):
        return (job for mod in self for job in mod)

    @property
    def dead_jobs(self):
        return (job for job in self.jobs if job.is_dead())

    @property
    def autodetect_jobs(self):
        return [job for job in self.jobs if job.not_launched()]

    def enabled_modules(self):
        for mod in MODULES_TO_RUN:
            mod_name = mod[:-len(MODULE_EXTENSION)]
            mod_path = os.path.join(PLUGINS_DIR, mod)
            if any(
                [
                    self.config.get('default_run', True) and self.config.get(mod_name, True),
                    (not self.config.get('default_run')) and self.config.get(mod_name),
                ]
            ):
                yield RawModule(
                    name=mod_name,
                    path=mod_path,
                    explicitly_enabled=self.config.get(mod_name),
                )

    def load_and_initialize_modules(self):
        for mod in self.enabled_modules():

            # Load module from file ------------------------------------------------------------
            loaded_module, error = self.loader.load_module_from_file(mod.name, mod.path)
            log = Logger.error if error else Logger.debug
            log("module load source: '{module_name}' => [{status}]".format(status='FAILED' if error else 'OK',
                                                                           module_name=mod.name))
            if error:
                Logger.error("load source error : {0}".format(error))
                continue

            # Load module config from file ------------------------------------------------------
            user_config = os.path.join(PLUGINS_USER_CONFIG_DIR, mod.name + '.conf')
            stock_config = os.path.join(PLUGINS_STOCK_CONFIG_DIR, mod.name + '.conf')

            Logger.debug("loading '{0}'".format(user_config))
            loaded_config, error = self.loader.load_config_from_file(user_config)
            if error:
                Logger.error("cannot load '{0}' : {1}. Will try stock version.".format(user_config, error))
                Logger.debug("loading '{0}'".format(stock_config))
                loaded_config, error = self.loader.load_config_from_file(stock_config)

            if error:
                Logger.error("cannot load '{0}': {1}".format(stock_config, error))

            # Skip disabled modules
            if getattr(loaded_module, 'disabled_by_default', False) and not mod.explicitly_enabled:
                Logger.info("module '{0}' disabled by default".format(loaded_module.__name__))
                continue

            # Module initialization ---------------------------------------------------

            initialized_module = Module(service=loaded_module, config=loaded_config)
            Logger.debug("module status: '{module_name}' => [{status}] "
                         "(jobs: {jobs_number})".format(status='OK' if initialized_module else 'FAILED',
                                                        module_name=initialized_module.name,
                                                        jobs_number=len(initialized_module)))
            if initialized_module:
                self.modules[initialized_module.name] = initialized_module

    @staticmethod
    def check_job(job):
        """
        :param job: <Job>
        :return:
        """
        try:
            check_ok = bool(job.check())
        except Exception as error:
            job.error('check() unhandled exception: {error}'.format(error=error))
            return None
        else:
            return check_ok

    @staticmethod
    def create_job_charts(job):
        """
        :param job: <Job>
        :return:
        """
        try:
            create_ok = job.create()
        except Exception as error:
            job.error('create() unhandled exception: {error}'.format(error=error))
            return False
        else:
            return create_ok

    def delete_job(self, job):
        """
        :param job: <Job>
        :return:
        """
        del self.modules[job.module_name][job.id]

    def run_check(self):
        checked = list()
        for job in self.jobs:
            if job.name in checked:
                job.info('check() => [DROPPED] (already served by another job)')
                self.delete_job(job)
                continue
            ok = self.check_job(job)
            if ok:
                job.info('check() => [OK]')
                checked.append(job.name)
                job.checked = True
                continue
            if not job.is_autodetect() or ok is None:
                job.info('check() => [FAILED]')
                self.delete_job(job)
            else:
                job.info('check() => [RECHECK] (autodetection_retry: {0})'.format(job.recheck_every))

    def run_create(self):
        for job in self.jobs:
            if not job.checked:
                #  skip autodetection_retry jobs
                continue
            ok = self.create_job_charts(job)
            if ok:
                job.debug('create() => [OK] (charts: {0})'.format(len(job.charts)))
                job.created = True
                continue
            job.error('create() => [FAILED] (charts: {0})'.format(len(job.charts)))
            self.delete_job(job)

    def start(self):
        self.run_check()
        self.run_create()
        for job in self.jobs:
            if job.created:
                job.start()

        while True:
            if threading.active_count() <= 1 and not self.autodetect_jobs:
                run_and_exit(Logger.info)('FINISHED')

            sleep(self.sleep_time)
            self.cleanup()
            self.autodetect_retry()

            # FIXME: https://github.com/netdata/netdata/issues/3817
            if self.do_gc and self.runs_counter % self.gc_interval == 0:
                v = gc.collect()
                Logger.debug("GC full collection run result: {0}".format(v))

    def cleanup(self):
        for job in self.dead_jobs:
            self.delete_job(job)
        for mod in self:
            if not mod:
                del self.modules[mod.name]

    def autodetect_retry(self):
        self.runs_counter += self.sleep_time
        for job in self.autodetect_jobs:
            if self.runs_counter % job.recheck_every == 0:
                checked = self.check_job(job)
                if checked:
                    created = self.create_job_charts(job)
                    if not created:
                        self.delete_job(job)
                        continue
                    job.start()


if __name__ == '__main__':
    DEBUG, TRACE, OVERRIDE_UPDATE_EVERY, MODULES_TO_RUN = parse_cmd()
    Logger = PythonDLogger()
    if DEBUG:
        Logger.logger.severity = 'DEBUG'
    if TRACE:
        Logger.log_traceback = True
    Logger.info('Using python {version}'.format(version=PY_VERSION[0]))

    plugin = Plugin()
    plugin.start()

**Comment by ilyam8** [comment]
I suggest to completely remove your netdata and install it again from source

**Comment by jamesnr** [comment]
OK. I'll get that done.

**Comment by jamesnr** [comment]
All works fine now.
