### ISSUE TITLE
Cant see the child at my prometheus server

### ISSUE THREAD

**Issue by juanvasquezreyes** [netdata/netdata#9994]
I'm running netdata in one VM, enabled to receive metrics from childs, I configure the childs to send the metrics to the parent, that part is working and I can see it in the UI

Also I need to export the metrics to a prometheus server, currently I only see the parent metrics in prometheus, how can I see the child metrics in prometheus?

### These are the configs at my parent node
**exporting.conf**
```
[exporting:global]
    enabled = yes
    # send configured labels = yes
    # send automatic labels = no
    update every = 10

[prometheus:exporter]
    send names instead of ids = yes
    send configured labels = yes
    send automatic labels = yes
    send charts matching = *
    send hosts matching = localhost *
    #prefix = netdata-parent
```
**stream.conf**
```
[11111111-2222-3333-4444-555555555555]
        # enable/disable this API key
    enabled = yes

    # one hour of data for each of the child nodes
    default history = 3600

    # do not save child metrics on disk
    default memory = ram

    # alarms checks, only while the child is connected
    health enabled by default = auto
```

**netdata.conf**
[global]
        memory mode = dbengine
        page cache size = 32
        dbengine disk space = 256
        dbengine multihost disk space = 1024

### these are the configs at my children node
**stream.conf**
```
[stream]
    # stream metrics to another Netdata
    enabled = yes

    # the IP and PORT of the parent
    destination = <URL OF MY PARENT>:19999

        # the API key to use
    api key = 11111111-2222-3333-4444-555555555555

```
**netdata.conf**
[global]        
        memory mode = none
[health]        
        enabled = no

Please let me know what I'm missing to see at my prometheus the childs, I do can see them in the UI and also in the db files at my parent, I'm trying to follow this design https://user-images.githubusercontent.com/1153921/84290043-0c1c1600-aaf8-11ea-9757-dd8dd8a8ec6c.png

or how should I see the child at prometheus?

**Comment by ilyam8** [comment]
Hi @juanvasquezreyes 👋 

See https://learn.netdata.cloud/docs/agent/exporting/prometheus#streaming-data-from-upstream-hosts

(format - `prometheus_all_hosts`)

**Comment by juanvasquezreyes** [comment]
Do I need the export.conf in each node and in prometheus,yaml set the target to each node as well?

**Comment by ilyam8** [comment]
You need to set prom scrape job params as in the link above, you get all the data from the parent node.

**Comment by juanvasquezreyes** [comment]
Perfect, its now working, thank you

**Comment by OdysLam** [comment]
@juanvasquezreyes 

Welcome to our community! If you have any questions about configuration or our A W E S O M E [netdata cloud](https://app.netdata.cloud), come and join us at our [forum](https://community.netdata.cloud).
