### ISSUE TITLE
 How to compare multiple monitoring machines

### ISSUE THREAD

**Issue by hope1234567hope** [netdata/netdata#9995]
How to compare multiple monitoring machines？
One interface displays the same monitoring items of multiple machines？ Zabbix has this feature。

**Comment by ilyam8** [comment]
Hi @hope1234567hope 

> One interface displays the same monitoring items of multiple machines？ Zabbix has this feature。

Can you share a screenshot?

**Comment by hope1234567hope** [comment]
in zabbix，have "Aggregation in graphs"  to display more machines。
you can see “https://pmmdemo.percona.com/graph/”，this   can  compare multiple machines。

**Comment by ilyam8** [comment]
@hope1234567hope i see there are 2 options:
 - use netdata.cloud
 - use [dash dashboard](https://learn.netdata.cloud/docs/agent/web/gui/custom#dash-multi-host-dashboard) (requires parent/child setup)

**Comment by hope1234567hope** [comment]
thanks, Can these functions be operated on the interface
The Dash Dashboard was a bit complicated for me

**Comment by ilyam8** [comment]
I dont get what is

> be operated on the interface

did you try netdata cloud?

**Comment by hope1234567hope** [comment]
In our country，i  Can not  visit  netdata cloud. 
ask you a question，docker install netdata，my ip is 11.11.114.208，
this is my python.d/mongodb.conf   ：
remote207:
    name : 'remote207'
    authdb: 'admin'
    host : '11.11.114.207'
    port : 27017
    user : 'netdata'
    pass : '1234qwer'
but web not display remote207？why？

**Comment by ilyam8** [comment]
@hope1234567hope could be a lot of reasons, see https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin#how-to-debug-a-python-module
