### ISSUE TITLE
Packets Dropped: Are they inbound or outbound?

### ISSUE THREAD

**Issue by gaia** [netdata/netdata#9997]
My alerts say inbound:

![image](https://user-images.githubusercontent.com/87547/94385298-a335c980-00f9-11eb-9acb-1764aef8d3be.png)

but the monitored machine says outbound (TX packets dropped)

![image](https://user-images.githubusercontent.com/87547/94385174-4803d700-00f9-11eb-91cf-456ef2698612.png)

tap201i0 faces the internet
tap201i1 faces the LAN's hypervisor guests (and is itself a guest: pfsense for all other guests)

**Comment by vlvkobal** [comment]
The alerts inform you about drops from the container's point of view. It's logical, that RX/TX are reversed on the host side.
